### ISSUE TITLE
No motion without manual power on

### ISSUE THREAD

**Issue by 8Roman8** [MarlinFirmware/Marlin#10004]
bugfix 2.0.x
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1792921/configuration.zip)

No motion possible before manual activating the PSU with M80 or LCD,
if AUTO_POWER_CONTROL is activated, even when the heater etc. are running and the PSU was activated by power control. 

When you start the heated bed or so, the PSU goes on, then you try to home all exes, but nothing happens before you achtivate the PSU manually by M80 (the PSU is still running by auto power contol). 
After that the movement is possible.

**Comment by thinkyhead** [comment]
Thanks for the report. This is now patched!
