### ISSUE TITLE
[bugfix-2.0.x] - LCD blank when using UBL and RAMPS 1.4

### ISSUE THREAD

**Issue by viper93458** [MarlinFirmware/Marlin#10013]
[Config Files.zip](https://github.com/MarlinFirmware/Marlin/files/1795203/Config.Files.zip)
### Description

Sometime after 2/26/18, the Bugfix-2.0.x branch starting giving a Blank LCD after the compile and upload finishes whenever I have UBL enabled. Bi-Linear compiles and works fine, but UBL appears to be stuck in some sort of loop when the controller boots up. If you actually connect to it from a host computer (I.E. S3D), you will see it load the UBL mesh (all zeros and inactive), but then before finishing the output of all controller variables, etc.... it appears to reload/reboot and keep doing it over and over.

I am using a REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

### Steps to Reproduce

1. Flash a recent download of bugfix-2.0, enable UBL and compile/upload. The LCD will light up but stay blank.

**Expected behavior:** [What you expect to happen]

The controller to fully boot, the display to show the logo and ultimately end up at the screen that allows control of the printer from the LCD. (I.E. normal operation)

**Actual behavior:** [What actually happens]

The display stays lit up but blank.

#### Additional Information

Issue 9920 seems to have the same LCD blanking issue and they discovered a workaround by flashing a simple sketch followed by a reflash of the current bugfix, however the issue recurs. They also had success with 1.1.x. I simply went back to a version from 2/26/18 which didn't exhibit this behavior. I have been watching all commits and testing over and over (as recently as last night) without success.

**Comment by teemuatlut** [comment]
See #10009

**Comment by viper93458** [comment]
@teemuatlut thank you for the reference. I will attempt this fix however I don’t see a watchdog reset message. Also, I am using a Mega2560. I will report back tomorrow.

**Comment by Bob-the-Kuhn** [comment]
You'll only see the watchdog reset message on a DUE based system.

**Comment by viper93458** [comment]
The controller does indeed boot after flashing the latest bugfix-2.0.x as of 1:00PM PST on 3/9/18 however I saw the logo flash, saw the boot through the USB connection to the host, saw the UBL mesh scroll a few times, saw the logo again (the unit rebooted itself), saw the UBL mesh scroll a few times again and then it returned to the normal LCD screen that you see when the controller boots properly. So the status is that it did indeed boot, although it appears to be doing something strange on bootup whereby it appeared to loop a couple of times.

William

**Comment by viper93458** [comment]
I forgot to mention that I used my same CFG files that are attached here and didn't mess with the watchdog values. I simply downloaded the current codebase, compiled and uploaded. Of course I then did M502, M500, M501. Testing function now. :)

William

**Comment by viper93458** [comment]
I don't see the logo twice during boot anymore (actually since the first time after flash), but it sill appears to load the UBL mesh 3 times before completing the boot. I may be mistaken about the mesh loading 3 times, I just see what appears to be the same information scroll 3 times. Doesn't seem to hurt anything, just slows the controller boot after an estop, initial power up, etc...

**Comment by viper93458** [comment]
Seeing as how it appears to work, I will close this out.

Thanks!

-William

**Comment by thinkyhead** [comment]
> I just see what appears to be the same information scroll 3 times.

If you continue to see this, let us know. Maybe it's the same mesh saved in 3 slots, or maybe UBL is calling its mesh load more than once in error.

**Comment by viper93458** [comment]
I still see it happening. Can I somehow delete meshes in other slots and just stick with slot 0?

William

**Comment by thinkyhead** [comment]
> Can I somehow delete meshes…?

Not that I'm aware of. If you want to limit the number of meshes to just one, you can replace `MarlinSettings::calc_num_meshes` with this:
```cpp
uint16_t MarlinSettings::calc_num_meshes() { return 1; }
```

So far I'm unable to determine how the information is being repeated 3 times. I'll have to flash UBL onto one of my boards and do some debugging later.
