### ISSUE TITLE
[bug] PRINTER_EVENT_LEDS not resetting (as of March 1st)

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#10012]
got mine working.
when hotbed and/or hotend are heating and printing it is red.
When print is done and it is cooling, it is yellow (sort of).
when both temps are < 50°C it is green (maybe I'll make it blue then it might really be yellow).
HOWEVER, if I start another print b4 it turns green (blue) it stays yellow. It does not reset to red.
same old build from 3/1/18 bugfix-1.1.x.63b1358

**Comment by thinkyhead** [comment]
Make this change in `Marlin_main.cpp` in `gcode_M190` and see if it fixes the issue for you…
```diff
-     uint8_t old_red = 255;
+     uint8_t old_red = 127;
```
