### ISSUE TITLE
MKS BASE 1.4 Stepper Pins

### ISSUE THREAD

**Issue by rt1970** [MarlinFirmware/Marlin#10022]
I have MKS BASE 1.4 Board with HR4982 Stepper.
I uncomment in Pins_MKS_BASE.h the PIN-Config for MS1 and MS2

Here is the error (and many more lines):
```
In file included from sketch\src\module\../inc/../HAL/HAL_AVR/HAL_AVR.h:46:0,
                 from sketch\src\module\../inc/../HAL/HAL.h:38,
                 from sketch\src\module\../inc/MarlinConfig.h:28,
                 from sketch\src\module\stepper_indirection.h:47,
                 from sketch\src\module\stepper.h:46,
                 from sketch\src\module\stepper.cpp:47:
sketch\src\module\../inc/../pins/pins_MKS_BASE.h:42:33: error: pasting "/* Digital 3  / Pin 5   / PE3*/" and "_DDR" does not give a valid preprocessing token
#define X_MS1_PIN           5   // Digital 3  / Pin 5   / PE3
                                ^
sketch\src\module\../inc/../HAL/HAL_AVR/fastio_AVR.h:90:36: note: in definition of macro '_SET_OUTPUT'
 #define _SET_OUTPUT(IO) do {DIO ## IO ## _DDR |= _BV(DIO ## IO ## _PIN); } while (0)
                                   ^
sketch\src\module\stepper.cpp:1514:5: note: in expansion of macro 'SET_OUTPUT'
    SET_OUTPUT(X_MS1_PIN);
    ^
sketch\src\module\stepper.cpp:1514:16: note: in expansion of macro 'X_MS1_PIN'
    SET_OUTPUT(X_MS1_PIN);
               ^
sketch\src\module\../inc/../pins/pins_MKS_BASE.h:42:33: error: pasting "/* Digital 3  / Pin 5   / PE3*/" and "_PIN" does not give a valid preprocessing token
#define X_MS1_PIN           5   // Digital 3  / Pin 5   / PE3
                                ^
sketch\src\module\../inc/../HAL/HAL_AVR/fastio_AVR.h:90:61: note: in definition of macro '_SET_OUTPUT'
#define _SET_OUTPUT(IO) do {DIO ## IO ## _DDR |= _BV(DIO ## IO ## _PIN); } while (0)
                                                         ^
sketch\src\module\stepper.cpp:1514:5: note: in expansion of macro 'SET_OUTPUT'
     SET_OUTPUT(X_MS1_PIN);
     ^
```

**Comment by 8Roman8** [comment]
Which arduino ide du you use? 

I had the same issue, I had to delete the comments on the lines with "/*" in the error code.. 

My English is very bad but I hope you understand me^^

**Comment by rt1970** [comment]
I use Arduino 1.9.0 beta
I have another try with Marlin 2.x It is new Board MKS_BASE_HEROIC. Thats my stepper-ICs. But same errors. Sorry for my bad english. Im from germany.

**Comment by 8Roman8** [comment]
Probier mal die Kommentare hinter den Definitionen zu löschen in den Zeilen die in der Fehlermeldung auftauchen...


`#define X_MS1_PIN 5 // Digital 3 / Pin 5 / PE3` --> `#define X_MS1_PIN 5`

also in der Datei  ../pins/pins_MKS_BASE.h

**Comment by rt1970** [comment]
Tatsächlich! Wär ich nie drauf gekommen! // ist eigentlich immer Kommentar... Geht wohl nur in neuer Zeile beim Arduino... VIELEN Dank! Mal sehen ob ihm die Leerzeichen vor den PIN-Ziffern auch stören oder ob ich jetzt (endlich) 128 Step´s einstellen kann. Ist schon ziemlich laut der Tevo Tornado...
Schade er druckt grad noch was. Kann die Firmware erst in ca. 1h testen.
Kurze Frage: Wie stell ich den Stepper auf 1/128? War irgendein M Befehl glaub ich...
M350 S128
Und dann alle Werte für X, Y, Z und E um wieviel multipliizieren?

**Comment by 8Roman8** [comment]
128 / "alte microsteps" * "alte sterps/mm"

du hast zb davor 32 microsteps und 80steps/mm gehabt: 128/32*80= 320steps/mm

**Comment by rt1970** [comment]
Achso.. ok...
Hab jetzt an der T8 Welle Z=400 Steps/mm. Sollte also auf 1/4 Microschritte laufen. Wieviel Steps sind es dann bei 1/128? Z=12800?

**Comment by 8Roman8** [comment]
Genau

**Comment by rt1970** [comment]
So. Getestet. Firmware Marlin 2.0 bugfix
M350 X128 zeigt mir auch X: 01 an. Aber die X-Achse ruckelt nur ganz langsam zum Zielpunkt. Auch beim X-Homing ruckelt und knattert er nur... Mit 2570 fährt er zu weit. geschätzt will er um die 1200 haben. Schon alles merkwürdig. Schade!

**Comment by 8Roman8** [comment]
ich hab gerade gesehen, dass das board einen 8 bit microcontroller hat, das ist für 128 microsteps einfach zu langsam... Ich bin davor davon ausgegangen, dass es ein 32bit contoller ist...

ich würde höchstens auf 32 microsteps gehen sonst hast du immer Probleme, dass der controller nicht mitkommt.
Was zusätzlich noch sein könnte ist, dass die Pulsdauer zu klein ist, in conf_adv 
#define MINIMUM_STEPPER_PULSE auf 2 setzen.

Gestern hatte einer hier das selbe Problem^^

Der atmega2560 packt max. 40.000 Steps pro Sekunde.
Beispiel 1: 80steps/mm, Geschwindigkeit 100mm/s --> 80*100=8.000steps/s < 40.000--> OK
Beispiel 2: 640steps/mm, Geschwindigkeit 100mm/s --> 640*100=64.000steps/s > 40.000 --> NICHT OK

**Comment by rt1970** [comment]
Och schade...
ABER: #define MINIMUM_STEPPER_PULSE stand auf 0
Ich setze die mal auf 2 und teste.
Die Geräusche haben sich tatsächlich nach Überlastung angehört. Hatte sogar 1x ein Reboot.
Warum würde dann aber ein 2130 Stepper am 8bit Board laufen? Andere Ansteuerung/Verarbeitung?

**Comment by 8Roman8** [comment]
TMC2130 kann mit nativen 256 microsteps angesteuert werden, das machen aber die wenigsten.
Man steuert die treiber mit zb 16 microsteps an und diese werden im Treiber intern auf 256 interpoliert um die Motoren leise zu machen.

**Comment by rt1970** [comment]
Ist der Mega256 wohl doch zu schwach. Keine Änderung. Leider.
Auch M350 I1 brachte nichts

**Comment by 8Roman8** [comment]
Aber dein Hauptproblem wurde gelöst oder?
Vielleicht kannst du dann das issue schließen...

**Comment by rt1970** [comment]
Hatte ich ein Problem? Wollte eigentlich nur Ruhe im Wohnzimmer ;-)
Ja hast recht! Problem gelöst und vielen Dank!
