### ISSUE TITLE
Help! Can't compile bugfix-2.0.x

### ISSUE THREAD

**Issue by jacobsokolove** [MarlinFirmware/Marlin#10025]
### Description

Compiling Never Completes

### Steps to Reproduce

1. Downloaded the Newest 2.0 Bugfix
2. Configured Everything (namely, enabled the use for an inductive sensor, sw spi, software serial, tmc 2130, 2208
3. Tried to compile and upload

I'm not sure why it won't compile. I'm using a standard ramps board and mega combo.

[Marlin 2.0 Hypercube - Copy.zip](https://github.com/MarlinFirmware/Marlin/files/1797636/Marlin.2.0.Hypercube.-.Copy.zip)

**Comment by Spawn32** [comment]
You have to poste the compile errors, if not it's hard to help you for the dev's..

**Comment by jacobsokolove** [comment]
There aren't any errors. It never finishes compiling. I waited for about 40 minutes and it never finished compiling. I checked and I never had any issues with previous versions of marlin (even on the same device I'm using to upload everything).

**Comment by ghost** [comment]
delete temp folder

**Comment by thinkyhead** [comment]
What environment are you using to compile with?

**Comment by thinkyhead** [comment]
What environment are you using to compile with?
I just compiled your project with Arduino IDE 1.8.5 and had no issues.

**Comment by jacobsokolove** [comment]
I was using Arduino IDE 1.8.5 in windows 10 on a microsoft surface. I'll try deleting my temp file to see if that would help, but why would that fix it? what causes that issue?

**Comment by Bob-the-Kuhn** [comment]
Most likely it's just another Microsoft bug.  Windows has a reputation for things like that.

**Comment by jacobsokolove** [comment]
Honestly, this is the first time I've had a windows issue. interesting. If linux was better supported on the surface, I'd use it.
