### ISSUE TITLE
[FR] Tramming Z with autolevel probe.

### ISSUE THREAD

**Issue by dot-bob** [MarlinFirmware/Marlin#10049]
My printer uses dual z steppers that get out of sync fairly often when power is removed.  I have been using dual Z endstop at the top of the Z axis but it is more then a meter tall.  This often takes a couple of minutes to travel to the top then back down to the bed.

Since the printer has an auto level probe tramming dual Z steppers could take place after homing X and Y utilizing the autolevel probe.  With  Z_SAFE_HOMING enabled perhaps you could define the probe points with something like (XMAX/6, YMax/2) then (5*XMAX/6, YMAX/2), tram the z steppers then probe the center as normal.  This would greatly speed up the tramming those with independent control of dual Z steppers

**Comment by boelle** [comment]
@dot-bob 

think this has been added now

/**
 * Z Steppers Auto-Alignment
 * Add the G34 command to align multiple Z steppers using a bed probe.
 */
