### ISSUE TITLE
TMC2130 Software-SPI: driver-failure during print

### ISSUE THREAD

**Issue by LichtiMC** [MarlinFirmware/Marlin#10043]
For testing purposes I have only fitted the X-axis with an TMC2130-driver.

I'm using Arduino DUE SAM3X8E with SMART_RAMPS board, SPI is configured like this:
```C++  
  #define TMC_USE_SW_SPI
  #define TMC_SW_MOSI       51
  #define TMC_SW_MISO       50
  #define TMC_SW_SCK        52
```
With this configuration printing starts fine, but after a random time the tmc-driver fails and just stands still. I think I can rule out temperature problems as my H-Bot printer is using 400ma stepper motors. The tmc doesn't even get warm, the motors get warm to approximately 40 degrees:
```C++
  #define X_CURRENT          400  // rms current in mA. Multiply by 1.41 for peak current.
  #define X_MICROSTEPS        16  // 0..256
```

This happened with the 2 last prints:
![image](https://user-images.githubusercontent.com/18006112/37246080-ed79fb8c-24a2-11e8-9818-306b40427445.png)

Could this problem arise due to a bug in the software?
How could I debug the failure?
Thanks

**Comment by 8Roman8** [comment]
A had a similar issue with tmc2208, my acceleration was too high and the motor driver itself shuts down...

**Comment by LichtiMC** [comment]
These are my acceleration-values:
```C++
/**
 * Default Max Acceleration (change/s) change = mm/s
 * (Maximum start speed for accelerated moves)
 * Override with M201
 *                                      X, Y, Z, E0 [, E1[, E2[, E3[, E4]]]]
 */
#define DEFAULT_MAX_ACCELERATION      { 1000, 1000, 100, 10000 }

/**
 * Default Acceleration (change/s) change = mm/s
 * Override with M204
 *
 *   M204 P    Acceleration
 *   M204 R    Retract Acceleration
 *   M204 T    Travel Acceleration
 */
#define DEFAULT_ACCELERATION          1000    // X, Y, Z and E acceleration for printing moves
#define DEFAULT_RETRACT_ACCELERATION  1000    // E acceleration for retracts
#define DEFAULT_TRAVEL_ACCELERATION   1000    // X, Y, Z acceleration for travel (non printing) moves
```
What values are you using?
Thanks.

**Comment by 8Roman8** [comment]
Hm... I think 1000 isn't so high... 
Do you use "high" voltage motors? 400ma looks too little for a standard motor, maybe yor psu voltage to little for the combination of your motor and the driver

**Comment by LichtiMC** [comment]
Don't think so.
I use 24V, A4988 Stepper Motor Driver and these motors for months now without a problem.
(It's the (upgraded) Creality Ender 4 printer.)
The only problem is with the TMC2130 driver.

**Comment by teemuatlut** [comment]
Try to enable monitoring so that Marlin will tell you when the driver reports an error condition.
You can decide for yourself whether or not you want to automatically stop the print.

**Comment by LichtiMC** [comment]
I have (and always had) following options set:
```C++
#define MONITOR_DRIVER_STATUS

  #if ENABLED(MONITOR_DRIVER_STATUS)
    #define CURRENT_STEP_DOWN     50  // [mA]
    #define REPORT_CURRENT_CHANGE
    #define STOP_ON_ERROR
  #endif
```
Shouldn't it already have stopped the print with these settings, instead of going ahead printing without the X-axis?

I printed again with M122 S1 and Serial logging enabled:
Left: M122 after failure < -- > Right: M122 before failure (as usual)
![image](https://user-images.githubusercontent.com/18006112/37247875-66da2112-24c3-11e8-85e4-3f67b513d5e6.png)
... looks like somehow TMC2130 is resetting itself mid print ... anybody an idea why?
I try to resolder the connections... but... not expecting too much from it...

~~Update: Print is running for over 7 hours now... maybe a loose connection after all? \*holdingthumbs\*~~

**Comment by LichtiMC** [comment]
@#%$§! 😉
![image](https://user-images.githubusercontent.com/18006112/37253747-e9710b46-2535-11e8-9cb3-efc104fd6c71.png)
```
Send: M122
Recv: 		X
Recv: Enabled		false
Recv: Set current	400
Recv: RMS current	718
Recv: MAX current	1012
Recv: Run current	12/31
Recv: Hold current	6/31
Recv: CS actual		0/31
Recv: PWM scale	0
Recv: vsense		0=.325
Recv: stealthChop	false
Recv: msteps		256
Recv: tstep		17213
Recv: pwm
Recv: threshold		0
Recv: [mm/s]		-
Recv: OT prewarn	false
Recv: OT prewarn has
Recv: been triggered	false
Recv: off time		0
Recv: blank time	16
Recv: hysterisis
Recv: -end		-3
Recv: -start		1
Recv: Stallguard thrs	0
Recv: DRVSTATUS	X
Recv: stallguard
Recv: sg_result		0
Recv: fsactive
Recv: stst
Recv: olb		X
Recv: ola		X
Recv: s2gb
Recv: s2ga
Recv: otpw
Recv: ot
Recv: Driver registers:	X = 0x60:00:00:00
```
Now trying the hardware spi! Stay tuned...

**Comment by 8Roman8** [comment]
Have you tried the standalone mode? Maybe this depends on the driver itself?

**Comment by thinkyhead** [comment]
@LichtiMC You described the drivers as staying pretty cool. But it can never hurt to put a fan directly over them. They may jump in temperature under certain conditions. Also, it's not a bad idea to have some spares and swap them out to see if the problem is reproducible with 2 or more drivers.

**Comment by LichtiMC** [comment]
Thanks, now I'm testing HW-SPI and started printing 30 min. ago.
I already have a fan for the board.

And as I have "#define MONITOR_DRIVER_STATUS" enabled it should give me some error message over serial or at least stop printing when a temperature problem arises, shouldn't it?

Update: Same problem with HW-SPI, so I guess my driver is damaged... replacing it with my good old A4988 driver for now... and starting a new try, when the new drivers arrive.

**Comment by towe96** [comment]
Dear LichtiMC, have you had success with your new drivers?
I've just bought 5 TMC2130's from Watterot which experience the same issue you described - only that for me, X Y and E stop together all at the same time. I too have the "E0:00:00:00" driver register contents, which do sort of indicate an odd reset or communication issue.

I've tried reducing acceleration and jerk, different currents (which didn't work) and even disabling Stealthchop - which did work, but I could've just kept using the A4988s at that point.
I'm running them on 24V as well with a step-up converter and 100 µF capacitors between VM and GND, directly on the driver.

Perhaps I'll try the lower SPI speeds intended for SD card functionality and see if that makes a difference. It's odd that the Z and Z2 drivers respond perfectly well though - maybe it's a thermal issue still?
When running only two Chinese Fysetc TMC2130s on X and Y, they didn't have temperature issues at all though, and the heatsink is cold as well. Also, if it were thermally related, I suspect it should've just reduced the current like the Fysetc ones once did.

**Comment by boelle** [comment]
@LichtiMC 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
