### ISSUE TITLE
SD card problem

### ISSUE THREAD

**Issue by cjake** [MarlinFirmware/Marlin#10065]
I can't read SD card.
The log show this message:
```
16:00:15.882 : start
16:00:15.882 : echo: External Reset
16:00:15.882 : Marlin1.0.2
16:00:15.882 : echo: Last Updated: Dec 17 2016 19:39:29 | Author: (geeetech, I3 config)
16:00:15.882 : Compiled: Dec 17 2016
16:00:15.882 : echo: Free Memory: 3748  PlannerBufferBytes: 1232
16:00:15.882 : echo:Hardcoded Default Settings Loaded
16:00:19.211 : echo:SD init fail
16:00:19.291 : FIRMWARE_NAME:V1.0.03  Sprinter/grbl mashup for gen6 FIRMWARE_URL:https://github.com/Ultimaker/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:I3proB EXTRUDER_COUNT:1 UUID:00000000-0000-0000-0000-000000000000
16:00:19.321 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X: 0.00 Y:0.00 Z:0.00
16:00:19.321 : echo:Active Extruder: 0
16:00:19.321 : Begin file list
16:00:19.331 : End file list
```
I changed display circuit with another one but the problem is the same.
Thanks for your help.

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by cjake** [comment]
Thanks for reply. I'm a newbie. May you tell me how fix procedure?
Thx a lot.

**Comment by thinkyhead** [comment]
Download, configure, and flash [this version](https://github.com/MarlinFirmware/Marlin/archive/bugfix-1.1.x.zip) onto your machine. If you need help with with configuration and troubleshooting, please use the following resources:
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube

**Comment by Phr3d13** [comment]
@thinkyhead I have 2 machines running the gt2560 board, I could probably maintain most of the Geeetech macnines if you'd like me to fork and make a folder tree of as many of them as I can, I would.

**Comment by thinkyhead** [comment]
@Phr3d13 —
What does your question pertain to? Is it related to GPL compliance?
This thread is about an SD card reading issue.

**Comment by Phr3d13** [comment]
I meant more like example configs for most/all of the Geeetech machines. I have 4 of them. A Pro W, a Pro C, a Rostock 301, and a Mecreator2.

**Comment by thinkyhead** [comment]
@Phr3d13 — We'd be happy to have them in the `example_configurations` folder. The more, the merrier!

**Comment by Phr3d13** [comment]
Can't do anything about the Rostock 301 at the moment, as it runs the GTM32Pro board, but the rest of the machines I have, I can add as soon as I get them as tweaked as I can.

**Comment by boelle** [comment]
@cjake 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
