### ISSUE TITLE
[bugfix-1.1.x] X2_CS_PIN?

### ISSUE THREAD

**Issue by toenish** [MarlinFirmware/Marlin#10076]
I use the latest bug fix  and now Marlin complains about 'X2_CS_PIN':
`'X2_CS_PIN' was not declared in this scope`

I haven't enabled TMC drivers and this pin is nowhere defined. The problem comes in
`#if ENABLED(DUAL_X_CARRIAGE)` in pins.h

**Comment by thinkyhead** [comment]
You should always post your Configuration when reporting an issue so we can immediately do a test build. Otherwise it takes us several minutes to follow up, stealing time from other issues and our development work.

**Comment by thinkyhead** [comment]
I'm unable to reproduce your issue by building the latest bugfix with `DUAL_X_CARRIAGE` and minimal options enabled. We'll need your configurations to look any further into it.

**Comment by thinkyhead** [comment]
Issue solved. Will push the update shortly.

**Comment by thinkyhead** [comment]
Changes merged. Thanks for the report.
