### ISSUE TITLE
[FR] M913 settings is missing in the M503 report

### ISSUE THREAD

**Issue by mshicom** [MarlinFirmware/Marlin#10087]
### Description
I am using the tmc2130 stepper motor driver and I often rely on M503 to make backups of my machine settings, but I found that the M913 setting for TMC hybrid threshold speed is not shown in the M503 outputs, which I think is kind of a bug.  Hope this can be fixed.

**Comment by teemuatlut** [comment]
I'll add "EEPROM support for hybrid threshold" to my growing TODO list.

**Comment by thinkyhead** [comment]
@teemuatlut — I'm implementing the EEPROM support. What is the range of valid values for `M913`? I want to make sure the defaults for non-TMC axes are reasonable, or at least obviously impossible. For the moment, I'll just store 0 as the placeholder.

**Comment by teemuatlut** [comment]
You can use 8bit values 0...255 but typically stealthChop has a max speed of about 110mm/s.
I'd consider 100 to be a good enough default value.

**Comment by thinkyhead** [comment]
In the process of adding `M913` support I noticed that the EEPROM is skipping the `M906` output for `IS_TRAMS` in `M503`. That's now fixed as part of the patch.

**Comment by thinkyhead** [comment]
Q: Is `SENSORLESS_HOMING` potentially supportable for TMC5130?

**Comment by teemuatlut** [comment]
A: Yes.

**Comment by swilkens** [comment]
This was provided for in https://github.com/MarlinFirmware/Marlin/pull/10102.

@mshicom or @thinkyhead can close the issue :)

**Comment by sjasonsmith** [comment]
I agree with @swilkens that this was included in the referenced PR. That was about 2.5 years ago, so I don't know whether it still works, but if there are issues it should come back as a bug report.
