### ISSUE TITLE
Extruder only turning in one direction

### ISSUE THREAD

**Issue by Bricky785** [MarlinFirmware/Marlin#10080]
Hello,

I installed Marlin 1.1.8 on a MKS GEN 1.4 with TMC2208 for XYZ and LV8729 for E on my TEVO Tornado. However the extruder is only turning in one direction. I had the jumpers set to 1/16 and 1/32 and that doesn`t change anything. I adjusted the E-Steps and the extruder is extruding the perfect amount of filament. But when it comes to retraction the extruder will turn forward just much faster so that the extruder gear is slipping and grinding into the filament. 

When I try to retract filament with Pronterface the extruder keeps turning in the wrong direction. I plugged the X-Stepper cable into the extruder and the extruder is turning in both directions. 
I can`t find any setting in Marlin that solves this issue. For the XYZ Axis I can invert the endstop but for E there is no endstop. There is only an option to invert the whole axis but that doesnt work. 

Can you tell me whats wrong and which settings do i have to change?

**Comment by thinkyhead** [comment]
Are you using `LIN_ADVANCE`?

Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by Bricky785** [comment]
LIN_ADVANCE is disabled. 

I think I'm already using bugfix-1.1.x because I downloaded the firmware two days ago and the zip is called Marlin 1.1.x.

**Comment by thinkyhead** [comment]
"`1.1.x`" isn't "`bugfix-1.1.x`"

https://github.com/MarlinFirmware/Marlin/archive/bugfix-1.1.x.zip

**Comment by Bricky785** [comment]
My fault! I will try the bugfix version.

**Comment by Bricky785** [comment]
Okay, I took all my settings and put them in the bugfix firmware. Nothing has changed. The extruder is still only turning in one direction.

**Comment by 8Roman8** [comment]
Have you tried to swap the driver?

whitch pulse Duration have you configuren in configuration adv? The datasheet of LV8729 say you need min 500ns.

**Comment by 8Roman8** [comment]
not an tmc2208

**Comment by Bricky785** [comment]
With a TMC2208 as the driver for the extruder it doesn't move and makes a loud squeaking noise.

**Comment by 8Roman8** [comment]
Have you checked your cables?

**Comment by Bricky785** [comment]
Yes, the cables are fine. Otherwise it also wouldn't turn into the other direction i think.

**Comment by Bob-the-Kuhn** [comment]
Step pulse width on all AVR CPUs is in the 14uS range so that isn't a problem.  On the 32 bit CPUs it's about 0.6uS.

You may have a defective driver or socket and the direction signal isn't getting through.  Try disabling the prevent cold extrusion option and then:
1) swap a new driver into the E socket.
2) move the E cable to X and see if it runs in both directions.

**Comment by Bricky785** [comment]
Thank you very much Bob!

I moved the E-cable to X and it worked fine. Then I moved the LV8729 from E to X, set the jumpers to 1/16 and the stepper only moved in one direction. So it must be a defective driver  I think. I will order a new one and that will hopefully solve this issue.

Thanks to all of you!

**Comment by reloxx13** [comment]
@Bricky785  sorry i know this is old, but did a new driver fix it as u suggested?

this actually comes up often in the fb groups right now, seems like a batch of defective drivers or that those 8729 tend to fail after some time.

**Comment by Maxracingshox** [comment]
Two out of three lv8729 I ordered showed the same exact defect as described by the op. I am not even bothering the seller for a refund, but I am pretty pissed tbh. Mostly because I have no spare atm and this error set me back a lot of time... Well.... the journey is the reward, isn't it? ;)
