### ISSUE TITLE
MK2_MULTIPLEXER- relay switches, driver without signal

### ISSUE THREAD

**Issue by honzahs** [MarlinFirmware/Marlin#10098]
When the MK2_MULTIPLEXER function is enabled, the relay switches. Unfortunately, only E1 works. E2 and E3 and E4 are switched on, but no signal from the stepper driver is in them. Where is the error?
FW: bugfix-1.1.x

**Comment by revilor** [comment]
What is the state of the status LEDs on the multiplexer (there is one per relay) when you select T0, T1, T2, T3?

**Comment by honzahs** [comment]
lights up. There is no such problem. I think so

**Comment by AnHardt** [comment]
Likely the sequence of the wires from the stepper driver to the switch is wrong. 
Likely A and B coils do not match.

**Comment by honzahs** [comment]
I measured the signal from the output of the board. E0 signal has, E1 E2 E3 signal is not

**Comment by thinkyhead** [comment]
Do you have `LIN_ADVANCE` enabled?

Please ZIP up your `Configuration.h` and `Configuration_adv.h` files and drop them into your next reply. We're going to need them if we are going to do any testing.

**Comment by honzahs** [comment]
thanks. Okey, here files:
[Marlin-bugfix-1.1.x.zip](https://github.com/MarlinFirmware/Marlin/files/1811852/Marlin-bugfix-1.1.x.zip)

**Comment by honzahs** [comment]
//#define LIN_ADVANCE

**Comment by revilor** [comment]
My stepper multiplexer works just fine with Marlin so this is probably a hardware issue. Just to be sure: we are talking about this ![stepper switcher](https://d17kynu4zpq5hy.cloudfront.net/igi/prusa3d/2PKETgpXNmMHvxZB.huge)

Then please check the status of the LEDs to rule out some wiring issue. When you put the stepper switcher as on the picture the topmost LED (D1) will always be on (power indicator). The two LEDs below (D2 and D3) will show the binary representation of the index of the currently selected stepper.
So it's

Tool | D1 | D2 | D3
------------ | ------------- | ------------- | -------------
T0 | ON | OFF | OFF
T1 | ON | ON | OFF
T2 | ON | OFF | ON
T3 | ON | ON | ON

**Comment by honzahs** [comment]
Yes exactly this type. switching to another extruder does not flow into E-IN. the switch itself works

**Comment by honzahs** [comment]
@revilor  can you please send me your configuration? I'd like to try it out

**Comment by honzahs** [comment]
switching E1
![1](https://user-images.githubusercontent.com/32460101/37436145-c589c1b0-27e6-11e8-9b89-0f27e0647a7f.jpg)
switching E2
![2](https://user-images.githubusercontent.com/32460101/37436146-c5a99328-27e6-11e8-9f23-ca628a584e86.jpg)
switching E3
![3](https://user-images.githubusercontent.com/32460101/37436147-c5c6ef18-27e6-11e8-8de5-424326123f50.jpg)
switching E4
![4](https://user-images.githubusercontent.com/32460101/37436148-c5e81b84-27e6-11e8-9435-c3d047dcddbc.jpg)

simply is not the master signal for the stepper motor for E2, E3 and E4. E1 works.
measured on stepper driver

**Comment by honzahs** [comment]
my full package Marlin
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1813493/Marlin.zip)

**Comment by revilor** [comment]
That's exactly how it is supposed to be. So it's not a Marlin issue but related to the switcher board itself. Maybe a cold solder joint at one of the relay pins?

**Comment by AnHardt** [comment]
https://github.com/prusa3d/MK2mm_Stepper_switch/blob/master/stepper-switch.pdf

A+,A-,B+,B- != A+,B+,A-,B-

**Comment by honzahs** [comment]
so why is not the signal going to E-IN?

**Comment by simon-jouet** [comment]
@honzahs did you figure this out by any chance? I just built my own MK2 multiplexer and I'm having pretty much the same issue.

If I enable MK2_MULTIPLEXER and do tool change I can hear the relays clicking but any extrusion isn't working. (except for tool 0).

To debug things out, I disabled the multiplexer in the config and manually used M42 to set the pins state of the multiplexers and in that case it's working perfectly fine (I need to M18 between tool change)

I did something along those lines in prontrface for debugging
```
G91 ; Relative mode (easier to test extrusion)
G0 E10; Extrude on T0
M18 ;Disable steppers
M42 P40 S255 ; Switch to T1
G0 E10; Extrude on T1
M18
M42 P42 S255 ; Switch to T3
G0 E10
M18
M42 P40 S0 ;Switch to T2
G0 E10
```

**Comment by revilor** [comment]
Ok guys, I guess the root of all evil is this option:

```cpp
#define DISABLE_INACTIVE_EXTRUDER true
```
Change the value to false and I'm 99.9% sure all four extruders will work.

**Comment by simon-jouet** [comment]
@revilor that was it for me, thanks :). That's with the latest Marlin 2.x and a custom MK2 like multiplexer

If it's of any use, my config is the following
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1826771/Marlin.zip)

**Comment by honzahs** [comment]
@revilor Yes it is. two days ago I came alone

**Comment by thinkyhead** [comment]
> Ok guys, I guess the root of all evil is this option:

Aha. Very nice catch. We'll patch that today… or now.
