### ISSUE TITLE
[FR] Dynamic current control with TMC2130 / TMC2208

### ISSUE THREAD

**Issue by 8Roman8** [MarlinFirmware/Marlin#10111]
Is it possible to adjust the stepper current dynamicaly to prevent lost steps additional to hybrid threshold?
So this would be possible tu run higher/ lower currents than normal for short times.

This feature would keep the drivers and the motors cooler 
and would step up the current only when needed.

something like this:
#define *_CURRENT_RUN                 400      //mA
#define *_CURRENT_MAX                 1200   //mA
#define *_CURRENT_THRESHOLD     80      //mm per second

The function could adjust the current lineary from 80mm/s to #define DEFAULT_MAX_FEEDRATE.
I think this could make spreadCycle mode unnecessary.

**Comment by teemuatlut** [comment]
Trinamic has this coolStep technology that uses motor load to determine appropriate current for the driver.
I'll be adding support for it soon but don't want to add new features before 1.1.9 is out.

If you want to try how it works there's an example sketch with the TMC2130 library. I'd recommend using the IDE plotter to better visualize the changes. As with all the examples, remember to detach your belt(s) before uploading.

Unfortunately it only works with spreadCycle, but the benefit is that we could use higher max currents as most of the time the driver would use lower actual currents.

Also I believe higher currents are needed more for acceleration and not necessarily for higher velocities.

**Comment by 8Roman8** [comment]
Maybe this feature could be used to increase current during de/acceleration or use spreadcycle only in this time.

I don't "like" the spreadcycle mode, because my whole housing (thin wood) of my machine resonate and is extremely loud ^^

![20180204_192932](https://user-images.githubusercontent.com/28136411/37506622-02f5434e-28eb-11e8-9611-265a4918c2be.jpg)
If that's impossible please tell me and I will close the issue/ fr request.

**Comment by teemuatlut** [comment]
That would require us to start analyzing the queue quite a bit more than we do now.
For your case I would suggest you either lower your acceleration/jerk settings or increase current as much as your cooling allows. The Watterott stepstick protectors allow you to put a second heatsink under the driver PCB, increasing your cooling capacity.
There are also other ways to deal with vibrations.

**Comment by 8Roman8** [comment]
Question to others:
Is there a interest on this or a similar feature? 

If not I will close this thread.

**Comment by nightdemonx** [comment]
As you correctly siad @teemuatlut, your task is implemented in the coolstep feature. Do not reinvent the wheel.

**Comment by 8Roman8** [comment]
Sure, but coolstep uses the spreadcycle mode, the feature I requested would not needs the mode... 

But it seems I'm only one who wants the funcion and I close the request.

**Comment by thinkyhead** [comment]
> But it seems I'm only one who wants the funcion and I close the request.

Either that or people have lives and haven't yet had an adequate chance to respond to the request.

**Comment by alfredanil** [comment]
digital current control like coolStep is a must have feature. It can be configured through the spi bus as well. There's yet another feature called dcStep which slows down the motor when it reaches motor torque limit. If it can synchronize the speed of all other drives accordingly then this could be really big advantage with using Trinamic driver tmc2130.

**Comment by thinkyhead** [comment]
> which slows down the motor when it reaches motor torque limit

Due to the way Marlin works, we can only slow down all motors together, and we have to do it programmatically. If steppers decide to slow down on their own the results are unpredictable.

**Comment by AmyTheCute** [comment]
I know this is super old but I'd love this! specially with my pancake stepper that gets SUPER hot.
