### ISSUE TITLE
How to turn off buzzer/beeper?

### ISSUE THREAD

**Issue by Nikolay1243** [MarlinFirmware/Marlin#10124]

**Comment by 8Roman8** [comment]
With not defining it? 

//#define SPEAKER

**Comment by Nikolay1243** [comment]
That's already commented out. From what I understand, a speaker is deferent to the buzzer/beeper in marlin

**Comment by cjsoong** [comment]
@ThatBulgarian Pin define disable ... for example #define BEEPER_PIN 37 ---> -1

**Comment by ghost** [comment]
@cjoong  thks ! 😄

**Comment by thinkyhead** [comment]
> In your board's pins file `#define BEEPER_PIN -1` will do it.
