### ISSUE TITLE
TMC2130 Ramps Compile error

### ISSUE THREAD

**Issue by dedalodaelus** [MarlinFirmware/Marlin#10128]
### Description

I'm trying to compile the git release 1.1.8 with a TMC2130 and RAMP 1.4. I cannot compile, and the throw these error:
```
TMC2130Stepper\src/TMC2130Stepper_UTILITY.h: In function 'void print_HEX(uint32_t)':
TMC2130Stepper\src/TMC2130Stepper_UTILITY.h:6:5: error: 'Serial' was not declared in this scope

I commented the Serial lines from the utility file and I got the following error:

stepper_indirection.cpp:183: error: 'class TMC2130Stepper' has no member named 'hysterisis_start'
```
Anyone can point in the right direction?

#### Additional Information
 
[TMC2130-Compile-error-CFG.zip](https://github.com/MarlinFirmware/Marlin/files/1821243/TMC2130-Compile-error-CFG.zip)

**Comment by teemuatlut** [comment]
This is because a recent bugfix required changes to both Marlin and the libraries.
You need to either downgrade the library or upgrade Marlin to bugfix-1.1.x branch.
