### ISSUE TITLE
Delta Auto Calibration With BLTouch Not Working

### ISSUE THREAD

**Issue by Cjslezak** [MarlinFirmware/Marlin#10129]
### Description

When I hit **Prepare>Delta Calibration>Auto Calibration** on my HE3D K280 3d printer it fails to level.  
 In the configuration.h file I set the correct offsets using **X_PROBE_OFFSET_FROM_EXTRUDER** and **Y_PROBE_OFFSET_FROM_EXTRUDER** for my bltouch but it's completely ignoring them and running a z probe outside of the build area and failing every test.  Either I'm missing something or something's wrong.  Any help would be appreciated!

Video showing my issue: https://vimeo.com/260521105
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1821234/Configuration.zip)

### Steps to Reproduce

1. [First Step]
Click **Prepare** on the LCD
2. [Second Step]
Click **Delta Calibration** on the LCD
3. [and so on...]
Click **Auto Calibration** on the LCD

**Expected behavior:** [What you expect to happen]
Automatically calibrate the bed.

**Actual behavior:** [What actually happens]
Probing outside build area and failing.

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* Read the "Contributing" page (under "Helpful resources") for additional guidelines.

**Comment by thinkyhead** [comment]
What version of Marlin are you using?

**Comment by Cjslezak** [comment]
I'm using Marlin 1.1.8  
Upon a very long time of experimenting I found a workaround for my issue.  For some reason when I set the Delta Calibration Radius in Configuration.h the printer refused to acknowledge it.  I figured out how to set the radius with g-code so that the probe doesn't fall off the bed, but when I run G33 it still thinks that the probe is on the tip of the extruder.

**Comment by Cjslezak** [comment]
I'm watching it do it's first print and due to the offsets not registering the first layer is looking pretty terrible.

**Comment by LVD-AC** [comment]
For calibration carriages need to be at specific positions so the effector (nozzle) needs to be at the center and the other calibration points, not the probe. So set the delta_calibration_radius small enough the probe stays on the bed. (Either in FW followed with M502 or by M665 Bx.xx)

**Comment by thinkyhead** [comment]
> set the delta_calibration_radius small enough the probe stays on the bed.

In firmware configuration the automated method is to use:
```cpp
#define DELTA_CALIBRATION_RADIUS \
  (DELTA_PRINTABLE_RADIUS - max(abs(X_PROBE_OFFSET_FROM_EXTRUDER), abs(Y_PROBE_OFFSET_FROM_EXTRUDER)))
```

**Comment by AnHardt** [comment]
That's crap. The length of the diagonal would be right.

**Comment by AnHardt** [comment]
Even better would be to test against a circle with `DELTA_PRINTABLE_RADIUS`, but a shifted by `PROBE_OFFSET_FROM_EXTRUDER` center.

**Comment by thinkyhead** [comment]
> Even better would be to test against a circle with DELTA_PRINTABLE_RADIUS, but a shifted by PROBE_OFFSET_FROM_EXTRUDER center.

Well, in fact the bounds checking has been altered so it does exactly that for general probing. However, I believe it's vital for `G33` calibration that the center of the probe area be in the center of the bed.

**Comment by LVD-AC** [comment]
Indeed this was to restrictive; for calibration the probe must stay on the bed in order to be able to probe even if it goes outside the printable area between the towers.

In order to set delta_printable_radius you need to move the effector around to see at what point the arms or effector start hitting one of the belts; for delta_calibration_radius you need to move the effector around to see at what point the probe no longer sees the bed and triggers (probes are mostly mounted in between towers not to restrict the printable area). The arms hitting the belts (at the towers) and the probe running of the bed (between towers) are 2 different things that are unrelated and can't be calculated.

**Comment by Cjslezak** [comment]
So I can't use an eccentric probe to do G33 calibration?  Would UBL work better?  I made the DELTA_CALIBRATION_RADIUS small enough that the probe doesn't fall off of the bed, but the bottom layer on all of my prints still looks pretty bad.
Is there a bed leveling function that takes PROBE_OFFSET_FROM_EXTRUDER into effect?  I've already got the offset set up for my probe in the firmware.

**Comment by LVD-AC** [comment]
Sure you can use an eccentric probe. But every hardware has it's specific problems to be solved. Eccentric probes are much more sensible to effector tilt, resulting in a different z_offset being reported on different positions of the bed. This will make probing less accurate so calibration (G33) or bed levelling (G29) will suffer from that. Further G33 calibration will be more accurate the larger you set the delta_calibration_radius, eccentric probes will have to use a smaller radius as nozzle probes, so they will be less accurate. But G33 provides good results on any decent build delta printer.

What is your final std.dev at the end of G33?

**Comment by Cjslezak** [comment]
My std.dev is 0.279

**Comment by Cjslezak** [comment]
Just ran a longer scan and got std.dev .062  Will test it out later.

**Comment by LVD-AC** [comment]
This indicates hardware problems. For reference (after a lot of tweaking the hardware) I obtain std.dev < 0.020 every time and flat layers all over the build plate as result.

**Comment by Cjslezak** [comment]
What sort of hardware tweaking did you do?

**Comment by LVD-AC** [comment]
Stabilizing the rods with springs, new effector, linear rails with new carriages,... but it all depends on YOUR printer build. Part of the fun with cheap Chinese kits; it gets you started but a lot of room for improvement.

**Comment by boelle** [comment]
@Cjslezak still having issus when using latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
