### ISSUE TITLE
latest bugfix 2.0.x - no more able to use the printer

### ISSUE THREAD

**Issue by MasterPIC** [MarlinFirmware/Marlin#10125]
I was using a previous bugfix 2.0.x with no issues at all.
I just tried to switch to latest release to test Lin_advance 1.5.
Unfortunately I see "unknown command" answers are sent by my printer soon after XY homing (and all the following commands are "unknown" as if there are communication issues):
```
Send: M155 S2
Recv: ok P127 B31
Recv:  T:132.75 /0.00 B:39.05 /0.00 @:0 B@:0
Recv:  T:131.73 /0.00 B:38.97 /0.00 @:0 B@:0
Recv:  T:130.84 /0.00 B:38.97 /0.00 @:0 B@:0
Send: G91
Recv: ok P127 B31
Send: G28 X0 Y0
Recv:  T:129.96 /0.00 B:38.97 /0.00 @:0 B@:0
Recv: X:-34.00 Y:-8.00 Z:4.00 E:0.00 Count X:-3400 Y:-800 Z:1600
Recv: ok P127 B31
Send: G90
Recv: echo:Unknown command: ""
```
I'm using an Anet A8. Switching back to a previous release I've no issues...

**Comment by MasterPIC** [comment]
My BLOCK_BUFFER_SIZE was set at 128 (on my Anet I'm keeping SD support disabled).
Switching it back to 16 seems fixing the issue.
Anyway something seems broken...

**Comment by Bob-the-Kuhn** [comment]
The BLOCK_BUFFER_SIZE has been 16 in the default and A8 Configuration_adv.h files for at least the last 9 months.

Did you have it set to 128 in your EEPROM previously?

**Comment by MasterPIC** [comment]
I was using 128 previously with no issues.

**Comment by Bob-the-Kuhn** [comment]
What is the RAM usage with 128 on the latest and the one that worked?

**Comment by MasterPIC** [comment]
Latest with BLOCK_BUFFER_SIZE = 128 (not working):
Sketch uses 115270 bytes (90%) of program storage space. Maximum is 126976 bytes.
Global variables use 16022 bytes of dynamic memory.

------------------------------------------------------------

Latest with BLOCK_BUFFER_SIZE = 16 (working):
Sketch uses 115272 bytes (90%) of program storage space. Maximum is 126976 bytes.
Global variables use 6166 bytes of dynamic memory.

------------------------------------------------------------

Previous with BLOCK_BUFFER_SIZE = 128 (working):
Sketch uses 116954 bytes (92%) of program storage space. Maximum is 126976 bytes.
Global variables use 15418 bytes of dynamic memory.

**Comment by Bob-the-Kuhn** [comment]
Looks like the newest version takes 600 more bytes than the older version which resulted in running out of RAM.  What's happening is the stack is over writing some of the global variables which results in erratic behavior.

If you want the bigger block size then 64 looks like it'll be small enough that you'll have reliable operation.

**Comment by MasterPIC** [comment]
Hi @Bob-the-Kuhn 
Thanks.
I just found that enabling slim menus makes it possible to keep higher buffer size (64) together with SD support. I'm going to test.
I think the issue can be closed.. Thanks again.
