### ISSUE TITLE
How to config stop printing 

### ISSUE THREAD

**Issue by hzxiaoyu** [MarlinFirmware/Marlin#10138]
### Description

My delta print use 1.1.x- bugfix now . When I used sd card to print, and I stoped printing manual, the heat is off,and the motors is stay.But I want the heat keep stay so I can restart quick and the motors is off so I can move the  nozzle by hand. I cant find anywhere to config it.

**Comment by thinkyhead** [comment]
That is not an available option due to safety concerns. If you want to modify Marlin to leave the heaters on for "Stop SD Print" you must change the following code in `ultralcd.cpp`…
```diff
  void lcd_sdcard_stop() {
    card.stopSDPrint(
      #if SD_RESORT
        true
      #endif
    );
    clear_command_queue();
    quickstop_stepper();
    print_job_timer.stop();
-   thermalManager.disable_all_heaters();
    #if FAN_COUNT > 0
      for (uint8_t i = 0; i < FAN_COUNT; i++) fanSpeeds[i] = 0;
    #endif
    wait_for_heatup = false;
    lcd_setstatusPGM(PSTR(MSG_PRINT_ABORTED), -1);
    lcd_return_to_status();
  }
```

**Comment by boelle** [comment]
@hzxiaoyu 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
