### ISSUE TITLE
Servo pins not givng out 5V

### ISSUE THREAD

**Issue by RedDragon99** [MarlinFirmware/Marlin#10139]
Hello
I have a problem and after 2 hours of trying to solve it I decided to ask you here
I tried every solution on the internet but none of them works
I am using BLTOUCH sensor for auto leveling
I configured the required settings to enable it.
But it still doesnt work... the sensors light doesnt even blink.
I tried measuring the pins with multimeter and they dont give out 5V as they should.
My other endstops are working.
And RAMPS are connected to arduino MEGA
RAMPS are also being powered 12V for the stepper motors
ANd yea I am using this for my DELTA project.

And my configuraion.h:

https://pastebin.com/N3DtnFve

**Comment by TheSFReader** [comment]
If you're using a RAMPS setup, did you provide 5v to the servo lines? This can be done via a specific pin on the board either by an external 5v wire, or by bridging it with the neighboring vcc pin.

**Comment by RedDragon99** [comment]
RAMPS are connected via the arduino MEGA ...
All the endstops have 5V when measured with multimeter
And I have 12V connected to the RAMPS for driving my stepper motors.

**Comment by kAdonis** [comment]
Do you have this jumper set on RAMPS?
![image](https://user-images.githubusercontent.com/35379348/37558553-d426abb2-2a15-11e8-9bac-4d1e19fb5507.png)

**Comment by RedDragon99** [comment]
Ooh yea I didnt know I had to do that
Yea its working know thanks!!!
