### ISSUE TITLE
Z-axis problems with new FW

### ISSUE THREAD

**Issue by ProtoprintCZ** [MarlinFirmware/Marlin#10143]
Hello guys! :)

I have a problem with Marlin 1.1.18. With the old version it works ok but with the new one it always jumps in the Z axis (while the X and Y axes are OK) (see video here: https://www.facebook.com/Demonix691/videos/10204277656739474 ) 

- Was tried also bugfix verzion and results are the same
- Options are used from Kosseel XL (which I set with my own dimensions)
- When I control it manualy, works fine
- I have drivers  drv8825, Current 1A (based od earlier best practice)
- Not using correction, only autocalibration (always is set the same)

Thank you very much in advance!

Steven

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by thinkyhead** [comment]
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as requested in the Issue template) and drop them into your next reply. We'll check them over and see if anything is amiss.

**Comment by sh4jonny** [comment]
Change
```cpp
#define MINIMUM_STEPPER_PULSE 0
```
to **2** for your 8825

**Comment by Bob-the-Kuhn** [comment]
If you are using a DUE then changing it to 2 is useful.  For the 8 bit board the actual minimum stepper pulse is in the 14uS range even when  **MINIMUM_STEPPER_PULSE** is set to 0.

**Comment by boelle** [comment]
@ProtoprintCZ 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
