### ISSUE TITLE
Sled Mounted Z-axis Endstop for Z-probing (Auto Bed Leveling)

### ISSUE THREAD

**Issue by oliasmage** [MarlinFirmware/Marlin#1014]
Hello. I have a new design that mounts the Z-axis endstop on a sled that can be docked on the right of the X-axis. I have modified Marlin to support this new feature and while it works, I occasionally encounter a MSG_ERR_KILLED error when using my new dock/undock code.

Is there some way I can send you the difference file and we can discuss the code? Or should I create a fork and put the code there?

I've posted the thing on Thingiverse: http://www.thingiverse.com/thing:396692.

My contact is d r c h a r l e s b e l l at g m a i l dot c o m

Thanks.

**Comment by boelle** [comment]
i will close this one as there has not been any activity and the original poster should really just submit a pull request

**Comment by ChuckBell** [comment]
Hi,

Forgive me. What was I supposed to do? I thought I had. Should I reopen this?

Chuck

**Comment by AnHardt** [comment]
All is well. The sled-probe is in the code-base for a while. The unbelievable long delay until the kill pin reacts was shortened some weeks ago.
We just closed this forgotten issue.

**Comment by ChuckBell** [comment]
Thanks! :)
