### ISSUE TITLE
gcode_M915 snapshotting wrong current setting for Z2

### ISSUE THREAD

**Issue by ToddBeaulieu** [MarlinFirmware/Marlin#10159]
In the routine gcode_M915, the motor current values are saved for Z and Z2, but the value for Z2 is actually fetched from Z, so the result is that Z2's current setting is overwritten with Z's setting when using the M915 code.

      uint16_t Z_current_1 = stepperZ.getCurrent();
      uint16_t Z2_current_1 = stepperZ.getCurrent(); // Incorrect

**Comment by teemuatlut** [comment]
Fixed in #9930

**Comment by boelle** [comment]
@ToddBeaulieu problem solved?

@thinkyhead think we can close this one

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
