### ISSUE TITLE
TMC 2130 changes require a eeprom reset

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#10157]
I'm not sure if this is a bug or some feature I don't understand, but I noticed that when ever I change the current in the config and then reflash it won't take effect until I manually reset the eeprom (m502 ->m500) and then power cycle the printer)

I'm using the latest Bugfix 1.1.x

expected behavior:
Changes in config take effect after flashing and reboot

actual behavior:
I need to send m502 -> m500 everytime I change the current in the config and flash the firmware.

You can easily see this with the m122 command.

After changing current to 1000mah and flashing and reboot m122 still shows the old value. After sending m502 and then m502 it shows the new value

**Comment by GMagician** [comment]
As I know every parameter that is written in eeprom override firmware defaults.
If there is some gcode to update current you have to use it and then M500 to save new value.
This way everytime you turn on you get updated values

**Comment by AnHardt** [comment]
If you are always changing the config and reflash - simply turn off the EEPROM.

Purpose of the EEPROM is to let the values in it survive a reflash.
