### ISSUE TITLE
M203 + FR > 100% = issue

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#10186]
Hello,

Using Marlin 1.1.8, my original value for extruder feedrate (FR) is 25. When I use M203 E400 with detault 100% FR speed, everything does ok but if I alter the FR to 125% (using LCD) , for example, the extruder speed go very slow (!).  

The wanted behaviour is
increasing FR the extruder speed need to speed up too, not slow down.

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by mtmello2003** [comment]
Issue is vanish in bugfix-2.0.x

Thanks
