### ISSUE TITLE
Latest Marlin  - No heated Bed - Solved

### ISSUE THREAD

**Issue by Wireman64** [MarlinFirmware/Marlin#10183]
Just changed to TMC2130 and the latest Marlin and all is working fine except D8 does not trigger. I use a Mosfet on the the output.
Thermistor and Heated Bed are all checked out an OK.
Thermistor reports correct temp to Pronterface.
Power supply etc are all OK.
When I reconfigure to EEF D8 triggers with M106.
I have tried several Ramps boards and it is the same on all of them.
Ramps with no drivers installed also shows the same problem so i am assuming the problem is with Marlin..
Any help would be greatly appreciated..

**Comment by boelle** [comment]
@Wireman64 if solved maybe click the close botton below?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
