### ISSUE TITLE
Release strategy and use of branches.

### ISSUE THREAD

**Issue by joris57** [MarlinFirmware/Marlin#10180]
As a medium-term Marlin user, I very much appreciate the features that have been recently added to Marlin and the efforts that are put in by the developers.

But I also frequenly despair because of the lack of stability of the code, when it comes to plainly using my printers (and not regression testing Marlin).

Would it not make sense to split the branches for bugfixing of the current stable release off from the development branch? At the moment, it looks like both activities are running in bugfix-1.1.x, resulting in a massively unstable branch (bugfix-1.1.x) and a stable branch that doesn't get it's bugs fixed for months (1.1.x). I refer to the approach used by the Debian project.

I'd love to hear the views from other users and the development team.

**Comment by Roxy-3D** [comment]
The Marlin code base is very large.   And the development team is very small.    

I understand your thinking.   And I'm actually in agreement.   But the problem is everybody contributing is a  'volunteer'.  They work on things that are of interest to them.   So just telling those developers how things have to be is going to be counter productive.

I am willing to work with you to accomplish what you want.   But it can't put extra barriers in front of the developers.   One idea would be to organize enough people that share your view and I'll empower that group to maintain a branch that is 'solid' and fully tested.   I'll even go so far as to say none of the developers will touch your branch.   Only your test and certification group can make changes to the branch.   My only constraint would be I want this (currently imaginary) branch to follow closely behind the bugfix branch.  Maybe within 3 or 4 weeks....

If you are willing to expend effort to make it happen...   I will help (and empower) you to make it happen.

**Comment by TheSFReader** [comment]
@Roxy-3D I'm not sure the "imaginary" branch following closemly the "bugfox" branch would be what joris is thinking about, but as I understand the text,, a branch that consists of ONLY bug fixes to the last official release, excluding any new feature. 

So when say 1.10.0 is out, a new branch 1.10.0-bugfix is created, on which only bugfixes (maybe originating from the 1.1.x-bugfix "dev branch") are applied. That way, people who want/need the most stable version get that one, while more adventurous people get the "1.1.x-bugfix"/"2.x-bugfix" with a more up-to-date feature set. 

I'm not sure how many people would take the load for that, but while, I, as a developper understand the need to go forward.  as a user I would really welcome a way to get a clean/stable version when I need to install on my primary "working" 3D printer.

**Comment by Roxy-3D** [comment]
Well...  We can debate what the best mechanism is to accomplish the goal.   Having a team of people that check out and verify the 'correctness' of different points of time in the bugfix branch is the key item.   The stable or release branch tag could be moved to that point in time.

I really don't care how we accomplish the goal.   But we do need to make progress in that direction.

**Comment by TheSFReader** [comment]
Only problem with the moving slider is that at any point on the "bugfix" branch, new features or major updates can be introduced, potentially introducing regressions, whereas applying/backporting the known fixes to a specific commit should _converge_ to a "mostly correct/stable" version.

**Comment by joris57** [comment]
So I envisage 2 workflows and 4 formal branches :

1) Bugfix workflow : bugfixes are developed and tested against the 'bugfix' branch and applied to the 'stable or production' branch, the 'development' branch and the 'testing' branch.

2) Development workflow : new/improved functionality is developed and unit tested against the 'development' branch and then applied to the 'testing' branch for integrated testing and deployment by users, who like living on the bleeding edge and need the new/improved funcionality.

At agreed points in time, testing branch gets frozen for final testing and stabilisation (only bugfixes get applied) until deemed stableand ready for the larger audience. Then commits are applied to stable and bugfix branches.

If a testing team could be marshaled, that would be great, but I believe that even the separation of the bugfix and development workflows by itself will contribute to stability.

Makes sense?

**Comment by AnHardt** [comment]
The real art is to judge  if a PR solves more problems than it causes - how risky it is.
There are low risky new features like adding a new board where errors likely only affect these new feature.
And there are fixes for seemingly minor bugs breaking Marlin completely. 

The art to jude this isn't spread widely - especially not, when it's your own PR.

**Comment by fiveangle** [comment]
![michael jackson popcorn](https://user-images.githubusercontent.com/2219447/37859137-cc9c9c7e-2ecc-11e8-9dcc-8f24e83e8657.gif)

**Comment by joris57** [comment]
@AnHardt I agree with your last statement and would even go so far that in practical terms, it's impossible (based on some very bad experiences in my professional life).

However, what we **can** do is:
1) Make the bugfixing environment less 'fluid', by segregating it from the development environment. I don't think you can argue that that would not contribute to the **quality and/or risk** of the bugfixes.
2) Limit the changes to the 'stable' branch to bugfixes, which limits the **number** of changes.

Those who still want the new functionality, can opt for the 'testing' branch (but will still have a fall back if things go belly-up). At the moment, that fall-back is not available: 1.1.x is buggy and bugfix-1.1.x is unstable. Scylla or Charibdis?

If at a later stage, there are types of functional improvement that are deemed harmless (like introduction of new boards), exceptions can still be agreed upon.

@fiveangle Meaning?

**Comment by fiveangle** [comment]
Just here to read the comments...

**Comment by joris57** [comment]
@fiveangle I was hoping for a more substantial contribution, but ok.

**Comment by thinkyhead** [comment]
The "Pull Request" feature of GitHub obviates the need to maintain multiple branches in the main repository. The contributor simply keeps the branch in their own fork. Hopefully they keep it up to date while it's being evaluated, but to do this effectively requires `git rebase` which is not supported by the Github Desktop application and not well-understood by 99% of contributors. (As a result, the project Owners end up doing the necessary rebasing to keep the more useful PRs from getting stale — a power granted to us by the creation of a PR.)

**Comment by boelle** [comment]
@thinkyhead has this one not served its purpose?

**Comment by joris57** [comment]
@boelle With all due respect, but I've not seen any progress on this and, more disappointing, not even the recognition of the issues with the current approach. I'll close the issue.

**Comment by thinkyhead** [comment]
At the moment the `bugfix-2.0.x` branch is the dev branch for `2.0.x`. Too late to rename it. The `bugfix-1.1.x` branch is the bug-fix branch for 1.1.9. There will be no further 1.1.x releases. After the 2.0.0 release we will revisit the question of whether to keep a separate `bugfix-2.0.x` and `dev-2.0.x` branch. But for now, the single branch is the only one we need.
