### ISSUE TITLE
[1.1.8] Please upgrade your toolchain

### ISSUE THREAD

**Issue by Titi9237** [MarlinFirmware/Marlin#10190]
Hi, I have some trouble to compile the Marlin Firmware on Ubuntu 17

### Description
I get a SanityCheck error asking me to update my packages.
```
SanityCheck.h:36:4: erreur : #error "Marlin requires C++11 support (gcc >= 4.7, Arduino IDE >= 1.6.8). Please upgrade your toolchain."
But, I am in the last version of everything : 
ii  arduino        2:1.0.5+dfsg all          AVR development board IDE and bui
ii  gcc             4:7.2.0-1ubu amd64        GNU C compiler
```
### Steps to Reproduce
Just try to compile the Marlin.ino file from Arduino won't work and will raise the previous error.

Expected behavior: to compile

#### Additional Information
All is done with a newly downloaded and freshly unzipped  MarlinFirmware !

**Comment by Bob-the-Kuhn** [comment]
I just downloaded 1.1.8, made no changes, compiled with 1.8.5 and had no errors.

If you're on a Windows machine try rebooting.  For me that fixes a lot of strange errors like this.

If that's not the fix then download 1.8.5 installer or 1.9 beta and re-install Arduino.

**Comment by teemuatlut** [comment]
> arduino 2:1.0.5

Upgrade your Arduino version. You're using v1.0.5.

**Comment by Titi9237** [comment]
Sorry, noob mistake... Thanks !

**Comment by ghost** [comment]
Have the same issue here.

```
    In file included from MarlinConfig.h:42:0,
                 from dac_mcp4728.cpp:33:
    SanityCheck.h:36:4: error: #error "Marlin requires C++11 support (gcc >= 4.7, Arduino IDE >= 1.6.8).     Please upgrade your toolchain."
       #error "Marlin requires C++11 support (gcc >= 4.7, Arduino IDE >= 1.6.8). Please upgrade your toolchain."
```



![image](https://user-images.githubusercontent.com/8059009/46261683-f5b95c80-c4c4-11e8-8a4d-09c21b3a1cb1.png)

**Comment by thinkyhead** [comment]
1.0.5 is too old. Upgrade to 1.8.7. Linux downloads are posted at https://www.arduino.cc/en/Main/Software

**Comment by ghost** [comment]
got it. Thx
