### ISSUE TITLE
[2.0.x] STM32F1 compilation - Timers broken by macros

### ISSUE THREAD

**Issue by xC0000005** [MarlinFirmware/Marlin#10225]
I deleted my old fork and created a nice clean one so I wouldn't have a weird GIT history on PRs, and it looks like STM32F1 timer functions are broken by a change (and my code was really, really out of date).
The error manifests as:
```
Marlin/src/HAL/HAL_LPC1768/../../inc/../HAL/HAL_STM32F1/HAL_timers_Stm32f1.h: In function 'void HAL_timer_restrain(uint8_t, uint16_t)':
Marlin/src/HAL/HAL_LPC1768/../../inc/../HAL/HAL_STM32F1/HAL_timers_Stm32f1.h:61:30: error: 'timertimer_num' was not declared in this scope
#define TIMER_DEV(num) CAT (&timer, num)
^
Marlin/src/HAL/HAL_LPC1768/../../inc/../HAL/HAL_STM32F1/HAL_timers_Stm32f1.h:60:21: note: in definition of macro 'CAT'
#define CAT(a, ...) a ## __VA_ARGS__
^
Marlin/src/HAL/HAL_LPC1768/../../inc/../HAL/HAL_STM32F1/HAL_timers_Stm32f1.h:88:56: note: in expansion of macro 'TIMER_DEV'
#define HAL_timer_get_count(timer_num) timer_get_count(TIMER_DEV(timer_num))
^~~~~~~~~
Marlin/src/HAL/HAL_LPC1768/../../inc/../HAL/HAL_STM32F1/HAL_timers_Stm32f1.h:159:30: note: in expansion of macro 'HAL_timer_get_count'
const hal_timer_t mincmp = HAL_timer_get_count(timer_num) + interval_ticks;
^~~~~~~~~~~~~~~~~~~
```
The short of this is that we call
```cpp
HAL_timer_get_count(timer_num)
```
Which is
```cpp
#define HAL_timer_get_count(timer_num) timer_get_count(TIMER_DEV(timer_num))
TIMER_DEV is 
#define CAT(a, ...) a ## __VA_ARGS__
#define TIMER_DEV(num) CAT (&timer, num)
```
so it becomes timertimer_num.

The last version I know worked had these as functions so the macros couldn't do this. I'm looking at it, but the simplest fix appears to be to turn TIMER_DEV back into a function. That doesn't make it the right fix, but it seems to work.

**Comment by Bob-the-Kuhn** [comment]
FYI - here's my notes (via Thinkyhead) on modifying the commit history.  You can combine them (squash), kill them (drop) and rewrite the commit comments.

For details see the **Make the PR pretty & sync to main**  section of the [Contributing Code with Pull Requests](http://marlinfw.org/docs/development/getting_started_pull_requests.html) page in the Marlin docs WIKI.

```bash
# Please use the following procedure to rebase to the latest code and to squash all excess commits:

git remote -v
git remote add upstream https://github.com/MarlinFirmware/Marlin.git
  # only do this if the first command doesn't show this setting
git fetch upstream
git rebase upstream/bugfix-2.0.x -Xours
git rebase upstream/bugfix-1.1.x -Xours  ;#ALWAYS USE UPSTREAM
   git add Marlin/ultralcd.cpp
   git rebase --continue
   git rebase --abort
git rebase -i  upstream/bugfix-2.0.x
git rebase -i upstream/bugfix-1.1.x
  # pops up a window where you can select commits to be squashed into one
git push -f
```

NOTE - the  **-Xours** flag is optional.  It tells GIT to use the Marlin code if there is a conflict with the local repository's code.

**Comment by xC0000005** [comment]
Yes. I forked my original repo from a fork of a fork of a fork, and git (correctl) assumed the parent commits were part of the archeological history of anything I did. RE: This fix, I am going to try and get the STM32F1 code recompiling. SPI is also broken but I see there's another issue regarding that.

**Comment by xC0000005** [comment]
I created a PR to address the general STM32F1 compilation failures (and one malyan lcd specific bug), #10229.

**Comment by xC0000005** [comment]
Closing now that the PR is committed.
