### ISSUE TITLE
MATLAB Interface instead of the LCD

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#10224]
Hi there,

I wish to make a friendly user interface using MATLAB/GUI instead of the LCD. I know that i have to make a serial connection between the computer and arduino but i can't find where to write my commands of code in "ultralcd.cpp".
Any help will be much appreciated.

Thanks in advance.

**Comment by Roxy-3D** [comment]
If your Matlab interface is going to be sending GCodes...  The interface will be in Marlin_main.cpp.

**Comment by ghost** [comment]
@Roxy-3D 
Thank you, it will. But, I'm not in that phase yet. I just want to get rid off the LCD at first, so everything the LCD displays and the commands it sends need to be done by MATLAB/GUI. How to make all of that happen? 
Thanks very much

**Comment by Roxy-3D** [comment]
Just turn off the LCD (by not enabling one) at the bottom of Configuration.h      But really....   Especially when trying to debug, you are going to benefit from having a display that tells you where the machine thinks its nozzle is at, and the nozzle and bed temperature.   

If you pull down a fresh copy of Marlin...  The LCD Panel is turned off by default.
```
/**
 * LCD TYPE
 *
 * Enable ULTRA_LCD for a 16x2, 16x4, 20x2, or 20x4 character-based LCD.
 * Enable DOGLCD for a 128x64 (ST7565R) Full Graphical Display.
 * (These options will be enabled automatically for most displays.)
 *
 * IMPORTANT: The U8glib library is required for Full Graphic Display!
 *            https://github.com/olikraus/U8glib_Arduino
 */
//#define ULTRA_LCD   // Character based
//#define DOGLCD      // Full graphics display
```

I would enable the LCD Panel active...    It will burn some CPU cycles...   But pretty much, it is inert and won't affect the other work you are doing.

**Comment by ghost** [comment]
you are absolutely right! but what i am trying to do is the following
instead of sending the commands using the LCD menus and controllers, i wish to control and monitor the whole process using matlab, in order to get rid of the LCD and SDcard after a while when everything is stable. So, my matlab interface should display the location of the nozzle (on X,Y, and Z axes), nozzle and bed temperature, feed rate,...etc

I want to build an interface just like the LCD to ease the process. But in order to do that, i need to know exactly where i should add new lines of code to govern the process and give exactly what i need.

Thank you very much for your help, it's really appreciated.

**Comment by Roxy-3D** [comment]
You might want to look and PronterFace and Repetier Host.   Both are Open Source and used heavily in different Marlin applications.    If the printer is running, it will be hard to communicate X & Y information just because there is a lot of time spent doing serial communications and the printer will be moving during this time.    

But both PronterFace and Repetier Host dynamically track temperatures and the Z Height.

**Comment by ghost** [comment]
that's true, i can solve the time problem using higher baudrate for the serial communication which i believe matlab has no problem with high baudrate, it will keep tracking smoothly.

thank you so much for your help.
