### ISSUE TITLE
[bugfix-2.0.x]: STEVAL-3DP001V1 status

### ISSUE THREAD

**Issue by TerryBarnaby** [MarlinFirmware/Marlin#10223]
I note that the STEVAL-3DP001V1 is stated as a HAL in development. Is there any status on this ?
I have checked out the bugfix-2.0.x branch and I don't see this board listed in boards.h.

**Comment by TerryBarnaby** [comment]
I note that the STEVAL-3DP001V1 is stated as a HAL in development. Is there any status on this ?
I have checked out the bugfix-2.0.x branch and I don't see this board listed in boards.h.

**Comment by thinkyhead** [comment]
It is not under very active development and is only in the early alpha stages.

**Comment by TerryBarnaby** [comment]
So is there any code for this board somewhere to start with ?
I have some issues with the Marlin 1.0.2 based code that ST supplies for the board and was thinking of trying to port/use Marlin 2.0.x with this board. Or is it best to start with the HAL_STM32F7 port ?

**Comment by thinkyhead** [comment]
From our perspective it would be most valuable to get more complete support in the `bugfix-2.0.x` branch — pins file, HAL changes, `platformio.ini` target, etc. — so at least we can get a successful compilation and the minimum of functionality. Some libraries are unusable with STM32F1, as you can see in `platformio.ini` with the `lib_ignore` section…
```ini
[env:STM32F1]
platform     = ststm32
framework    = arduino
board        = genericSTM32F103RE
build_flags  = !python Marlin/src/HAL/HAL_STM32F1/stm32f1_flag_script.py
  ${common.build_flags}
lib_deps     = ${common.lib_deps}
lib_ignore   = U8glib-HAL
  c1921b4
  libf3c
  lib066
  Adafruit NeoPixel_ID28
  Adafruit NeoPixel
  libf3e
  TMC26XStepper
lib_ldf_mode = 1
src_filter   = ${common.default_src_filter}
monitor_baud = 250000
```
… The same will probably be true for STM32F401VE.
