### ISSUE TITLE
Firmware Filament retract while heating (~150C)

### ISSUE THREAD

**Issue by G3DBuilder** [MarlinFirmware/Marlin#10236]
I would like to see the Firmware do an Extruder retraction during the initial heating phase. Repetier Firmware has this feature.  It keeps the plastic from oozing all over the printer while the extruder heats up. On my printer that has repetier fw the extruder retracts 5mm when the temp reaches 140C.  I cannot find this setting in configuration.h or configuration_adv.h

**Comment by Zer0t3ch** [comment]
Not sure how we would go about doing this. Maybe add it as part of M109? (I'd think not as a part of M104, to avoid tampering with motors in the background)

How does Repetier handle it? I'm looking around, and I can't find any clear documentation about Repetier or their GCode, specifically in relation to this.

**Comment by AnHardt** [comment]
Depends a bit on if in relative mode or not, but 
```
M140 S140
G0 Z-3
M140 S230
```
does not need an extra g-code.

**Comment by Zer0t3ch** [comment]
@G3DBuilder If you want to use @AnHardt's suggestion and you're using CURA, put the first two lines of that gcode at the end of your "start" gcode in your printer config. It should work sufficiently to get it up to a minimal temp and retract, then the CURA-generated stuff will take over and set the actual long-term temp that you have set in your print profile.

It's probably doable to add what you want as an integrated part of the firmware gcode handling or something, but I doubt it's necessary given how well this "manual" solution should get the job done. The only point of that would be to offload the heat/retraction decisions to the firmware layer, but it seems redundant considering how easily it can be handled by existing gcode.

**Comment by boelle** [comment]
@thinkyhead maybe change to feature request issue?

@G3DBuilder have you considered heating up when nozzle is 0.05 to 0.1mm from bed? i do that and have no ooze
