### ISSUE TITLE
[1.1.8] ultralcd.cpp MENU_ITEM_EDIT Macro don't shows/convert utf-8 chars 

### ISSUE THREAD

**Issue by schimmi70** [MarlinFirmware/Marlin#10256]
ultralcd_impl_HD44780.h | void lcd_implementation_drawedit | line 1008 

must call **lcd_printPGM_utf**  not  **lcd_printPGM**

**Comment by thinkyhead** [comment]
We won't be patching 1.1.8. Would you say the same change is needed for the current codebase?

**Comment by thinkyhead** [comment]
Looks that way. So… now patched!
