### ISSUE TITLE
[2.0] MSK SBASE - Error:EEPROM datasize error. // Error:Field esteppers mismatch.

### ISSUE THREAD

**Issue by manutenfruits** [MarlinFirmware/Marlin#10263]
### Description

Gcode M500 to save EEPROM doesn't work, throws error.

### Steps to Reproduce

1. Reset board
2. Send M500

**Expected behavior:** The settings are saved and you get back control of the printer.

**Actual behavior:** Throws an error and OctoPrint cuts communication.

#### Additional Information

* I tried to isolate the issue by changing the minimum things and discard that it was some misconfiguration. My `Configuration.h` is just uncommenting `EEPROM_SETTINGS`, adding `DEBUG_EEPROM_READWRITE` like I read on another issue and setting the board to `BOARD_MKS_SBASE`. You can check out all the files on my [GitHub fork](https://github.com/MarlinFirmware/Marlin/compare/bugfix-2.0.x...manutenfruits:test-m500).
* The error seems to be related to some format mismatch with `esteppers`. Check out the console output on M500:

```
Send: M500
[...]
Recv:  write_data(100,268467976,4...)
Recv:  f_lseek()=9
Recv: Error:Field esteppers mismatch.
Changing monitoring state from 'Operational' to 'Error: Field esteppers mismatch.
'
Recv:  write_data(102,268467958,1...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443364,16...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443384,16...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443432,16...)
Recv:  f_lseek()=9
Recv:  write_data(102,268441992,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443412,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443408,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443400,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443428,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443404,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443464,16...)
Recv:  f_lseek()=9
Recv:  write_data(102,268441920,12...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467984,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467959,1...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467960,1...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467988,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467961,1...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467962,1...)
Recv:  f_lseek()=9
Recv:  write_data(102,268468024,8...)
Recv:  f_lseek()=9
Recv:  write_data(102,268468016,8...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467963,1...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467964,1...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467992,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467996,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268468000,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443668,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443664,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268443660,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268468004,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467968,2...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467965,1...)
Recv:  f_lseek()=9
Recv:  write_data(102,268468068,32...)
Recv:  f_lseek()=9
Recv:  write_data(102,268441193,1...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268468044,22...)
Recv:  f_lseek()=9
Recv:  write_data(102,268468100,44...)
Recv:  f_lseek()=9
Recv:  write_data(102,268468008,6...)
Recv:  f_lseek
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv:  write_data(102,268467972,4...)
Recv:  f_lseek()=9
Recv: ok
```

**Comment by p3p** [comment]
This has come up a bit recently, the LPC1768 platform running on the MKS SBASE seems to have an issue reading the onboard sdcard (where we save the eeprom.dat file on the LPC1768 platform), I assume that you can't access the usb drive to flash firmware either?

**Comment by manutenfruits** [comment]
> I assume that you can't access the usb drive to flash firmware either?

I'm not sure I understand. My process to flash the firmware is to copy it on the sd card and pop it in the board. I've connected to the board using USB and that used to work fine, the SD would be mounted fine as an external drive in my computer, but haven't tried with Marlin.

**Comment by p3p** [comment]
It should also be mounted as an external drive with Marlin, well unless the sd-card cannot be accessed. As flashing does work, meaning the boot-loader can access the sd-card, the issue must be with the pin configuration but unfortunately I don't have an mks sbase to test with and everything works as expected on my re-arm.

**Comment by thinkyhead** [comment]
The error is interesting. "`Field esteppers mismatch`" indicates that the eeprom index testing is failing right on the first field to be written. Try adding some more logging so we can see what's going on with the test values:

```diff
+   SERIAL_ECHO_START_P(port);
+   SERIAL_ECHOPAIR_P(port, "eeprom_index=", eeprom_index);
+   SERIAL_ECHOLNPAIR_P(port, "Expected index is ", offsetof(SettingsData, esteppers) + EEPROM_OFFSET);
    _FIELD_TEST(esteppers);
```

**Comment by p3p** [comment]
@thinkyhead I think that may be a false positive due to the sd-card access error though I could be jumping to conclusions, `f_lseek()=9` indicates the file was never opened (empty data structure) so the seek failed.

**Comment by manutenfruits** [comment]
@thinkyhead I added the logging, this is what I got.
```
Send: M500
Recv:  write_data(100,268467976,4...)
Recv:  f_lseek()=9
Recv: echo:eeprom_index=102Expected index is 106
Recv: Error:Field esteppers mismatch.
Changing monitoring state from 'Operational' to 'Error: Field esteppers mismatch.
'
Recv:  write_data(102,268467958,1...)
Recv:  f_lseek()=9
[...]
```

also, should I be able to see an eeprom.dat file in the SD card? I see nothing, I'll try with other sd cards and report back.

**Comment by manutenfruits** [comment]
I used a different SD card and it worked perfectly! I plugged it in my computer and I can see an `eeprom.dat` file now. Not sure what the problem is, but top card (4GB class 6, Transcend MicroSDHC) *doesn't* work, but bottom card (16GB Class 10, Centon MicroSDHC) *does* work just fine. Funny thing is, the one that works fine here had trouble running in a Raspberry Pi before. I need a better SD Card  supplier 😒 
![image](https://user-images.githubusercontent.com/2961735/38175009-f07bc81c-35a3-11e8-9cbb-cc1ff3f896f7.png)

Thanks everybody for helping me troubleshoot!

**Comment by p3p** [comment]
As nice as it is to know the onboard sd-card does work on the MKS-SBase, that was unexpected. On other issues changing the sd-card hadn't seemed to help (and I've had no problams with any of my diverse collection on the Re-ARM), can you confirm flashing was working correctly from the other card, if it was there should be no reason Marlin cannot access it as well.

**Comment by manutenfruits** [comment]
so reading works fine, but in the faulty card it seems to be unable to write to it.

**Comment by thinkyhead** [comment]
Hmm. Hopefully in future we can provide a better error message in the case of faulty SD card writes.
