### ISSUE TITLE
[FR] Electronics Temp display

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1026]
TMC's can report internal temp (i think) and for FET's and DRV8825 (and others) one could take a free thermistor input and use that as electronics temp

for displays it of course needs a new symbol

**Comment by boelle** [comment]
this one will not benefit many and is more work than it will it give back

i will simply just mount a heatsink on my electronics and and slow rpm fan that comes on with the extruder fan

**Comment by boelle** [comment]
missing label

**Comment by boelle** [comment]
would this be an easy one to add ?

**Comment by ellensp** [comment]
The request is somewhat poorly defined...  
You have potentially X TMC + a thermistor (ie 5+)
What temperature should it show? All of them? (not all at once!) , highest? lowest? average? rotate through all of them?  
Does it just show the temp?  (in which case its fairly pointless)
Does it take actions based on temp? If so what? 

Are you aware there is a USE_CONTROLLER_FAN  option that already monitors electronics and turn on a fan if needed? It doesn't have a display...

**Comment by boelle** [comment]
I do use the controller fan but I don't know temp of say FET's  or the
TMC's

lør. 25. apr. 2020 18.22 skrev ellensp <notifications@github.com>:
