### ISSUE TITLE
[2.0.x] Can't compile for Due if EXTRUDER_AUTO_FAN_SPEED != 255

### ISSUE THREAD

**Issue by tayalex** [MarlinFirmware/Marlin#10270]
1. Board RURAMPS4D
2. E0_AUTO_FAN_PIN 8
3. EXTRUDER_AUTO_FAN_SPEED 127

**Comment by tayalex** [comment]
1. Board RURAMPS4D
2. E0_AUTO_FAN_PIN 8
3. EXTRUDER_AUTO_FAN_SPEED 127

**Comment by thinkyhead** [comment]
@Bob-the-Kuhn — Is the `_GET_TIMER` macro for Due simply incorrect or not yet implemented? It currently does nothing.
```cpp
/// check if pin is a timer
#define _GET_TIMER(IO)
```

**Comment by numanair** [comment]
I can reproduce the issue with the malyan m200 board.

**Comment by thinkyhead** [comment]
@numanair — This seems to compile fine.
I just commented out `E0_AUTO_FAN_PIN` so it uses the default pin, `PB8`.
```cpp
//#define E0_AUTO_FAN_PIN -1
```

**Comment by boelle** [comment]
@tayalex was problem solved ???

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
