### ISSUE TITLE
full graphic smart controller A8

### ISSUE THREAD

**Issue by manotroll** [MarlinFirmware/Marlin#10273]
what parameter should I use to use this LCD on the A8 motherboard?

**Comment by thinkyhead** [comment]
`REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`

**Comment by manotroll** [comment]
I'll test and report if it worked.

**Comment by yo8aiv** [comment]
for me it didn't work. - only beeper works and seems i can select something when i press the encoder but no image. 
i have tried everything. just white screen no image
is there a tutorial to test separatley with arduino this LCD ? 
thanks.
is this one https://reprap.org/forum/thumbcache/ec9/17b/ffa/878/ed2/f30/db6/fe2/6e7/f2a/5d_800x400.png

**Comment by thinkyhead** [comment]
Is the contrast adjusted correctly?

**Comment by benlye** [comment]
The `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` is not directly compatible with the Anet board - you need to have some kind of adapter to convert the wiring.  Do you have one?  The details and a couple of options are in the Anet pins file.

**Comment by yo8aiv** [comment]
Thanks for answering. Yes, I have done the wiring according to the Anet pins file. I tested the 2 variants for RepRap in there with no success.

I have tried a least 5 times in a 3 days triple-checking the wiring. The last 4 times I used Arduino Dupont cables for easy identification of pins.

Here I posted a video for the seller showing that nothing happens:
https://youtu.be/KBgbZYa41oA

The only place I found same LCD ppl made it work is here…
https://reprap.org/forum/read.php?4,492402  
…but isn't very clear.

**Comment by manotroll** [comment]
> 
> 
> I'll test and report if it worked.

even changing this parameter is not working

**Comment by thinkyhead** [comment]
If someone can use `PINS_DEBUGGING` to figure out the pins on the EXT plugs, then it's theoretically possible to produce a pins file for the Anet A8 with pin assignments that line up with the standard connectors like those used for the RRDFGSC.

**Comment by benlye** [comment]
> If someone can use `PINS_DEBUGGING` to figure out the pins on the EXT plugs, then it's theoretically possible to produce a pins file for the Anet A8 with pin assignments that line up with the standard connectors like those used for the RRDFGSC.

The Anet A8 pins are already well known, and are documented in the [pins file](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/pins_ANET_10.h#L218).

It's not possible to attach a non-Anet display to the Anet board without a hardware adapter because the 5V and GND pins are in different positions and those cannot be reassigned in the config.  You can either [hack a pair of 10-pin cables](https://www.thingiverse.com/thing:2103748) or get a [PCB adapter ](https://aisler.net/benlye/anet-lcd-adapter/pcb)made.

**Comment by Bob-the-Kuhn** [comment]
A variation on the PCB adapter would be to mount the four connectors to a perf board and then solder 30 AWG (wire wrap) wires as needed.

**Comment by boelle** [comment]
@manotroll 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
