### ISSUE TITLE
Ambient temperature won't let to start print

### ISSUE THREAD

**Issue by xyyzyyx** [MarlinFirmware/Marlin#10283]
I start print at let say 0 degrees ambient temp the Min temp issue occures a cannot do anything besides hard reset (mostly min temp bed). I have to heat bed up to about 5 degrees in differend way for example by touching hand to the bed and then I can start print.
I belive an ambient temp sensor with temp comparition would be useful together with "testing" heatup  for few second to se if temp changes and if not then before the "min temp error".
Is it a simple way to solve it?

**Comment by me-honest** [comment]
You can change the mintemp threshold in the config file, I believe. Setting it to something like -5 degrees should do the trick.

**Comment by xyyzyyx** [comment]
Sure I can change it and already did, but it doesn't solve the problem. A lot of temp sensors are unstable at about 0 degrees (temp jumps few degrees up an down), so it won't start. There should be a possibility to start a testing heatup with comparison to ambient temp sensor. I believe it should work similar to this - when temp of the bed changes (goes up) in comparison to ambient temp, heating goes further, but if not it stops and gives min temp error.

**Comment by boelle** [comment]
@xyyzyyx 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
