### ISSUE TITLE
new libraries for arduino

### ISSUE THREAD

**Issue by REPHUK** [MarlinFirmware/Marlin#10287]
Hi
After load the last libraries 
Marlin 1.1.8 will not load in pronterface...

**Comment by thinkyhead** [comment]
What version of Arduino are you using? Have you tried closing Marlin in Arduino, quitting Arduino, and re-building Marlin? Are you sure you have the baud rate correctly set? What board are you using? Have you tried other host software? Have you tried reverting the problem libraries in Arduino to older versions to figure out which library is involved? How big is your Marlin install? Does your board have enough flash and SRAM to handle all the enabled options?

**Comment by boelle** [comment]
@REPHUK 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
