### ISSUE TITLE
Q: Best way to set pins in pins_XXX.h if same pin can have different functions

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#10284]
Hi!

What is the best way to set pins_XXX.h if same pin can have diffrent functions depending on current config.

Example 1:
MKS Gen 1.4 doesnt have Z_PROBE_PIN but i can set it to Z_MAX if i use only normal Z_MIN endstop for G28
Example 2:
Azteeg X5 GT board can use same pin for X_CS_PIN or X_ENABLE_PIN (same for Y,Z,E0, E1) depending on driver type

**Comment by landodragon141** [comment]
Do you mean repurpose a pin you aren't using for something else?

**Comment by thinkyhead** [comment]
Most pins files assign `Z_MIN_PROBE_PIN` to the `Z_MAX_PIN` by default, but this can be overridden in `Configuration.h`. If the board you're using doesn't supply the pin or set it to the pin you prefer, simply add a define for `Z_MIN_PROBE_PIN` anywhere in your `Configuration.h` file.

**Comment by thinkyhead** [comment]
Since the `pins_AZTEEG_X5_GT.h` file doesn't define any of the stepper CS pins, those will also need to be defined in `Configuration.h`.

**Comment by alexxy** [comment]
@thinkyhead how to define them in Configuration.h? And same question about Z_MIN_PROBE_PIN

**Comment by thinkyhead** [comment]
Just define them. For example:
```cpp
#define X_CS_PIN P1_22
#define Z_MIN_PROBE_PIN P1_29
```
