### ISSUE TITLE
M110 for set line number how to get  the current line printed?

### ISSUE THREAD

**Issue by amrithmmh** [MarlinFirmware/Marlin#10290]
so `M110` is used to set the line number to resume print job but how do you get the line number which is being printed ?

**Comment by thinkyhead** [comment]
There is no way to get that information. The host software keeps track of the last line number it sent, and Marlin will only send a request to the host to re-send a line, by number, if the line failed to be properly transmitted.

**Comment by amrithmmh** [comment]
so @thinkyhead how is the pause and resume in octoprint implemented if line being printed cannot be known?

**Comment by thinkyhead** [comment]
> so @thinkyhead how is the pause and resume in octoprint implemented if line being printed cannot be known?

OctoPrint is a host. It knows what lines it has sent. When it pauses, it simply stops sending lines.

**Comment by boelle** [comment]
@amrithmmh 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by amrithmmh** [comment]
@boelle its very old comment 
but thanks for the info

**Comment by boelle** [comment]
yeah and i think you have solved the problem right?

**Comment by amrithmmh** [comment]
@boelle not solved my problem but understood that there is  a queue
