### ISSUE TITLE
Stop a print in progress

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#10295]
Hello there,
I'm currently interfacing my printer using MATLAB. I send commands to the printer by the means of gcode.
i.e: G28 auto home. And it is working just fine. But, when i try to stop a print, the printer stops for a bit and then continue printing.

I used this sequence of code, and after that, it continues to print.
```gcode
M410
M0 [S1]
M104 S0
M140 S0
G28
G92 E0
G1 E-5  F300
G28 E0
M84
M117 Print Aborted
```
So, what gcode is used to stop a print in progress?!

**Comment by Roxy-3D** [comment]
Probably the place to start is look at the menu structure in ultralcd.cpp.

**Comment by thinkyhead** [comment]
`M0` or `M1` (with no `S` parameter) will stop a print until you press the controller button. Note that if this method is used, the heaters will remain on indefinitely.

**Comment by thinkyhead** [comment]
There is no G-code to stop an SDCard print in-progress.

`M410` doesn't kill the print job, it just kills the current move.

`M0` or `M1` (with no `S` parameter) will stop a print until you press the controller button or (with EMERGENCY_PARSER) send an `M108` command from the host. Note that if this method is used, the heaters will remain on indefinitely.

If `ADVANCED_PAUSE_FEATURE` plus `NOZZLE_PARK_FEATURE` plus `PARK_HEAD_ON_PAUSE` are enabled, you can use `M125` to pause printing and park the nozzle. Heaters will be turned off after a certain period of time.

(Note that `G28 E0` doesn't do anything different from `G28`.)

**Comment by boelle** [comment]
@AhmadGhzawi 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by InsanityAutomation** [comment]
For reference to not leave this closed without resolution, M524 was added which provides the requested function.
