### ISSUE TITLE
TMC2130 + REPRAP DISCOUNT FULL GRAPHIC SMART CONTROLLER = SD INIT  ISSUE SOLVED

### ISSUE THREAD

**Issue by CHILLYSMOKES** [MarlinFirmware/Marlin#10292]
I think this might help a bunch of people and I don't know how else to spread the word about an issue plaguing me and others for weeks, now.  LCD shows SD Card Inserted but SD Card Not Found.

Nowhere did I find the fix for this until I was almost finished porting all my settings from 1.1.8 to 1.1xx bugfix as a last resort to get the SD card to successfully init.

pins_RAMPS.h

//#define SDSS               53      //<--------------------new

I found this line where I made a note because I had to use pin 53 for X_CS_PIN on initial activation of the Trinamic drivers.  Afterward, having a huge issue with the serial connection from OctoPrint and long running prints die near the end I figured I needed to activate and run my prints from SD until I could figure out the serial connection issue.  So I moved all the CS pins to AUX 2 to plug in the LCD adapter into AUX 3, solder pins on top of the adapter and plug the Trinamic SPIs into those to share MOSI, MISO, and CLK with the LCD/SD.  Shoulda worked.... but I forgot the change I made above.  Recompiled/uploaded and WHAM....  SD works flawlessly.  This would only fix your SD init issue if you first commented the line out or changed the pin assignment for some reason.  I hope this helps someone else and saves somebody some time.

**Comment by LichtiMC** [comment]
"M43 I"-command comes in really handy with such kind of issues... as I learned recently...

**Comment by thinkyhead** [comment]
Guy goes to a doctor, says "Doc, whenever I move my arm like this it hurts a lot!" Doctor replies, "My medical advice is to not move your arm like that. That will be $200."
