### ISSUE TITLE
Symbols displaying incorrectly on RepRapDiscount Smart Controller with 20x4 HD44780 LCD

### ISSUE THREAD

**Issue by jackw01** [MarlinFirmware/Marlin#10312]
### Description
![img_20180404_210628](https://user-images.githubusercontent.com/22643669/38347222-f2e3e780-384e-11e8-9f72-40a5104aefd4.jpg)

Starts to occur when turning the printer on with the feedrate symbol not appearing correctly, and more symbols stop working over time over a period of several hours to several days. Reuploading the firmware did not fix the issue. Using Marlin 1.1.8.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1878570/Configuration.zip)

### Steps to Reproduce

1. Turn on the printer

**Comment by gloomyandy** [comment]
I think that this has already been fixed in the 1.1.x bugfix. Try using that version.
