### ISSUE TITLE
[FR] Implement PWM scaling factor for FANs

### ISSUE THREAD

**Issue by comps** [MarlinFirmware/Marlin#10314]
Inspired by http://doku.radds.org/dokumentation/other-electronics/psu-power-supply-unit-and-electrical-good-sizing/ , it would be useful if Marlin could apply a coefficient to the PWM FAN value to facilitate voltage control (running 12V fan on 24V terminals).
There seems to be something similar for the heater (`BANG_MAX` and `PID_MAX`) and the bed (`MAX_BED_POWER`) and there is `SOFT_PWM_SCALE`, but seemingly only for the slow software PWM.

For example, with a factor of 0.25, setting 255 would result in actual PWM of ~64. The reason for this (instead of simply limiting the max value like other settings) is software interaction - ie. "50% fan" in a slicing software is translated as `S127` and should result in half the power (32) of "100% fan" (64).

The scaling factor should apply to other features like `FAN_KICKSTART_TIME`, `FAN_MIN_PWM`, `CONTROLLERFAN_SPEED`, etc., to ensure that the fan doesn't get blown up.

Thanks.

**Comment by thinkyhead** [comment]
It's a fine idea. In principle I think we'd want to scale the _range_ between `FAN_MIN_PWM` and 255 (or, `FAN_MAX_PWM`) by the scaling factor, because the min PWM is generally the lowest value at which the fan will turn.

**Comment by comps** [comment]
That's probably a better idea, especially since I now see I understood `FAN_MIN_PWM` wrong, the algorithm doesn't set `FAN_MIN_PWM` for anything between 1 and `FAN_MIN_PWM`, it scales it up:
```
#define CALC_FAN_SPEED(f) (tail_fan_speed[f] ? ( FAN_MIN_PWM + (tail_fan_speed[f] * (255 - FAN_MIN_PWM)) / 255 ) : 0)
```
Given this, is it possible that the feature might be as simple as this?
```diff
diff --git a/Marlin/src/module/planner.cpp b/Marlin/src/module/planner.cpp
index cd95bb04f..0ec1509df 100644
--- a/Marlin/src/module/planner.cpp
+++ b/Marlin/src/module/planner.cpp
@@ -575,8 +575,14 @@ void Planner::check_axes_activity() {
 
     #endif // FAN_KICKSTART_TIME > 0
 
-    #ifdef FAN_MIN_PWM
-      #define CALC_FAN_SPEED(f) (tail_fan_speed[f] ? ( FAN_MIN_PWM + (tail_fan_speed[f] * (255 - FAN_MIN_PWM)) / 255 ) : 0)
+    #if defined(FAN_MIN_PWM) || defined(FAN_MAX_PWM)
+      #ifndef FAN_MIN_PWM
+        #define FAN_MIN_PWM 0
+      #endif
+      #ifndef FAN_MAX_PWM
+        #define FAN_MAX_PWM 255
+      #endif
+      #define CALC_FAN_SPEED(f) (tail_fan_speed[f] ? ( FAN_MIN_PWM + (tail_fan_speed[f] * (FAN_MAX_PWM - FAN_MIN_PWM)) / 255 ) : 0)
     #else
       #define CALC_FAN_SPEED(f) tail_fan_speed[f]
     #endif
```

`FAN_KICKSTART_TIME` would use it as it's defined just before `CALC_FAN_SPEED` and `CONTROLLERFAN_SPEED` should arguably remain separate as its PWM value is either 0 or a constant value. Also it likely uses different power outputs / fan type.

I don't (yet) have a 24V system set up, but I'll see if I can test it on a 12V machine.

**Comment by comps** [comment]
Fixed in latest bugfix branches.
