### ISSUE TITLE
G28 disables leveling, needing to send M420 S1 to reenable it

### ISSUE THREAD

**Issue by jaanshgo** [MarlinFirmware/Marlin#10326]
I've been digging into the marlin_main.cpp for many hours now with no luck. It may be to my lack of C++ skills but I cant figure out how to re enable bed leveling after I call G28. I read somewhere that there was a command on configuration.h file that would reenable it but I didnt have such a command on the file. Any help will be greatly appreciated.

**Comment by ManuelMcLure** [comment]
You need RESTORE_LEVELING_AFTER_G28, but that's only in bugfix-1.1.x and bugfix-2.0.x so you won't find it if you're running 1.1.8.

**Comment by thinkyhead** [comment]
After `G28` you can ensure leveling is re-enabled in all cases by using `M420 S1`.
