### ISSUE TITLE
Error "'DOGLCD_CS' was not declared in this scope" with Exit Status 1

### ISSUE THREAD

**Issue by Geric2004** [MarlinFirmware/Marlin#10327]
### Description
I keep getting this error. I'm pretty new to Marlin so please forgive me if I made some mistakes in this post.

**Expected behavior:** 
Compile and Upload to my Ramps Arduino Board Sandwich.

**Actual behavior:** 
Fails at compiling and gives this Error
[Marlin 1.1.x.zip](https://github.com/MarlinFirmware/Marlin/files/1882962/Marlin.1.1.x.zip)

**Comment by Bob-the-Kuhn** [comment]
Welcome to Marlin and the not always obvious world of the configuration files.

ULTRA_LCD and DOGLCD are automatically defined for the REPRAP_DISCOUNT_SMART_CONTROLLER,   

The compile error goes away if you change lines 1324 & 1325 in the file **Configuration.h**
FROM:
```
#define ULTRA_LCD   // Character based
#define DOGLCD      // Full graphics display
```
TO:
```
//#define ULTRA_LCD   // Character based
//#define DOGLCD      // Full graphics display
```

----

You may want to check out this [method of configuring Marlin](https://github.com/akaJes/marlin-config/).  Eventually you'll end up with a browser based method of downloading & configuring Marlin.  It's created & supported by a Marlin user.  It always trails Marlin a bit so it's not for bleeding edge users.

**Comment by Geric2004** [comment]
Thanks! I was having a rough time figuring it out.

**Comment by Bob-the-Kuhn** [comment]
Great!

Can I close the issue?

**Comment by Geric2004** [comment]
One last question, I tried it and there is no display on the Full Smart Graphic controller. (I have it connected to a laptop only since I haven't migrated all the electronics from my old board. The Display is the only thing connected)

**Comment by Bob-the-Kuhn** [comment]
Make sure your config file matches your LCD.  Lots of similar names:
- REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
- REPRAP_DISCOUNT_SMART_CONTROLLER
- ELB_FULL_GRAPHIC_CONTROLLER
- REPRAPWORLD_GRAPHICAL_LCD

If one end is a MKS product and the other isn't then chances are good that the connectors on the 10 pin cables are rotated 180 degrees from each other.  If that's the case then you'll need to either modify one end (pry the housings up, rotate and push them back down), make custom cables with one end reversed or shave the keying plugs off one end of the cables and plug it in backwards.

**Comment by Geric2004** [comment]
I have a Chinese Ramps Kit (That came with the Display, Ramps Shield and Arduino Clone) And I checked the name printed on the LCD it self it says RepRap Discount Full Graphic Smart Controller. I still can't find a fix for it.

**Comment by Bob-the-Kuhn** [comment]
Nothing from MKS so that's not the problem.

In the ZIP file posted earlier, the REPRAP_DISCOUNT_SMART_CONTROLLER was enabled.  The correct one for your display is REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER.  You'll need to update that if you haven't already done that.

**Comment by Geric2004** [comment]
Thank you so much! It finally worked. You may close this issue now

**Comment by Bob-the-Kuhn** [comment]
FANTASTIC!
