### ISSUE TITLE
Progress bar never reaches 100%

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#10330]
We're finding that the progress bar stays stuck at 99% in most SD card prints.

I'm not exactly sure how to go about fixing this. I suspect that what is happening is that "ultralcd.cpp" only updates the progress when [IS_SD_PRINTING is true](https://github.com/MarlinFirmware/Marlin/blob/ac3fab7a9680a880fd1b113be7e758c6dabb2a57/Marlin/ultralcd.cpp#L627):

```
    // Set current percentage from SD when actively printing
    #if ENABLED(LCD_SET_PROGRESS_MANUALLY)
      if (IS_SD_PRINTING)
        progress_bar_percent = card.percentDone();
    #endif
```

But once a print finished, that flag is probably set to false before the ultralcd has a chance to refresh. Perhaps removing the if statement would fix the problem? Would there be any concerns in calling card.percentDone() when not printing?

Does anyone have any better suggestions to cause the progress bar to reach 100%?

**Comment by marcio-ao** [comment]
Actually, disabling that if does not seems to fix the issue.

**Comment by marcio-ao** [comment]
So far the only way I can get the progress bar to show 100% is by adding the following to the end GCODE in the slicer:

```
M73 P100 ; Set progress bar to 100%
G4 P100 ; Wait for the LCD to refresh
```

Obviously, this is not ideal.

**Comment by marcio-ao** [comment]
It looks like the reason for the "if" statement, is that when printing from the host with LCD_SET_PROGRESS_MANUALLY enabled, M73 writes the value specified by the user to progress_bar_percent. If we were to constantly overwrite that with card.percentDone(), then M73 would not work. It only is safe to do so when printing from SD, hence the "if" statement. However, at the end of the print, it appears IS_SD_PRINTING gets set to false before ultralcd.cpp has a chance to update the value on the screen, so the progress bar is frozen at some number which may not be necessarily 100%. Frustrating.

**Comment by thinkyhead** [comment]
At the end of a print the progress bar should be cleared to zero, so that is what is now done. If it is getting set at some other point after being reset to 0, please let us know!

**Comment by marcio-ao** [comment]
> At the end of a print the progress bar should be cleared to zero, so that is what is now done. If it is getting set at some other point after being reset to 0, please let us know!

I guess whether it is 0 or 100 doesn't matter too much. But getting stuck at 99% was a problem. Prior to this PR, it the value would never have gotten updated past 99% when LCD_SET_PROGRESS_MANUALLY was enabled.

**Comment by thinkyhead** [comment]
The issue was that, unlike the non-settable percentage, which asks the card how far in its file it is and therefore gets 0 when the file is closed, the settable version simply wasn't being cleared to zero.
