### ISSUE TITLE
Not raising Z after G30

### ISSUE THREAD

**Issue by Squid116** [MarlinFirmware/Marlin#10349]
Running bugfix 1.1.x

Since I pulled the latest about 2 weeks ago, z is no longer raised after a g30, it is raised a bit, but not the full amount as per a G28.  Running a subsequent G30 Xnn Ynn causes the bltouch to go into fault mode as it doesn't have clearance to deploy the probe.

No biggie as I can manually raise z after each probe, but it does slow down my manual bed leveling

here is my config:
https://github.com/Squid116/Marlin/blob/bugfix-1.1.x/Marlin/Configuration.h

and config_adv:
https://github.com/Squid116/Marlin/blob/bugfix-1.1.x/Marlin/Configuration_adv.h

**Comment by thinkyhead** [comment]
You should set `Z_AFTER_PROBING` to the height you want at the end of `G30`.

**Comment by Squid116** [comment]
Sorry, could have sworn I had done that, I'll check later on tonight.

**Comment by Squid116** [comment]
Sorry - didn't get to check this last night (I got carried away on Issue 10341), but I am 99.99% sure you are right, so I'll close this one and re-open if it doesn't work out when I test it (I also didn't notice the 4 corner leveling has been patched, so keen to test that instead of manual g30 scripts).

**Comment by Squid116** [comment]
I just got back to this one, even when I do have Z_AFTER_PROBING set, I dont see a raise after G30 (but do after G28 and G29)

**Comment by thinkyhead** [comment]
The default behavior of `G30` is to probe down and stop.
To get it to deploy/stow for each `G30` use `G30 E1`.

**Comment by TypQxQ** [comment]
Having the same problem.
I have setup:
```
#define Z_CLEARANCE_DEPLOY_PROBE   15 
#define Z_CLEARANCE_BETWEEN_PROBES  10
#define Z_AFTER_PROBING           10
#define Z_PROBE_LOW_POINT          -2
```
After isuing `G30 E1 `the nozzle smashed into my bed after probing. I do have the BLTouch setup as a `Z_MIN_PROBE_ENDSTOP`.
When the `Z_AFTER_PROBING` was disabled, the `G30 E1` was same as `G30`.

**Comment by Squid116** [comment]
@TypQxQ - doesn't sound like quite the same problem as me, might be a seperate issue?

@thinkyhead I'm happy to close this if you are, G30 E1 works for me.
