### ISSUE TITLE
[BUG] TMC2130 Problems in general.

### ISSUE THREAD

**Issue by deathmock5** [MarlinFirmware/Marlin#10347]
### Description

TMC2130 only one direction.

Purchased 3 Driver chips, connected the SPI with standard wiring.

https://hackadaycom.files.wordpress.com/2016/09/tmc-wiring-01.jpg

Disabled end stops as having them on causes them to not move.

Disabled silent step to see if it would help.

Tried 3 different drivers, sockets, and motors. Using 6 pin motors but same behavior on a 4 pin motor.

Tried another ramps 1.4 shield same deal.

Tried another driver board form a different manufacture same result.

Drivers work as anticipated in a different commercial printer that already had tmc2130s in it.

I have exhausted my debugs.

### Steps to Reproduce

1. Install
2. Setup firmware: http://www.instructables.com/id/Upgrading-RAMPS-14-With-TMC2130-Stepper-Drivers/
3. Using repiter host, move any motor in + or -

**Expected behavior:** It moves y forward and back

**Actual behavior:** it moves y back and back.

#### Additional Information

Configuration:

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1888346/Marlin.zip)

**Comment by Grogyan** [comment]
I would suggest looking at your endstops, making sure they are plugged in correctly

**Comment by deathmock5** [comment]
No end stops attached. Using software end stops.

**Comment by teemuatlut** [comment]
Post your M119 output.

**Comment by thinkyhead** [comment]
It's not stated what version of Marlin you're using. Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch.

**Comment by deathmock5** [comment]
M119:
19:18:06.520 : Reporting endstop status
19:18:06.520 : x_min: open
19:18:06.520 : y_min: open
19:18:06.520 : z_min: open

**Comment by deathmock5** [comment]
Marlin 1.1.x bugfix

**Comment by Lyr3x** [comment]
> TMC2130 only one direction.

Did you ever inserted the driver in the wrong direction to the ramps board? This happened to me with one driver and this driver just moved into one direction since then

**Comment by deathmock5** [comment]
Nope. Ill have to breadboard the chips and find out whats what.

**Comment by boelle** [comment]
@deathmock5 what did the breadboarding end with?

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by deathmock5** [comment]
A bit inconclusive. With regular steppers on BB it works, With TMC2130 nothing. Not even turning the wrong way.

**Comment by boelle** [comment]
@deathmock5 if you are still on 1.1.x try 2.0.x

**Comment by marchelh** [comment]
Did you try to pull down the enable pin? Even so the datasheet says that when in SPI mode the pin in tristate is working, and the enablement of the driver is done by SPI command, I couldn’t get it to work without grounding the enable pin.

**Comment by boelle** [comment]
@deathmock5 did you give 2.0.x a go? 1.1.x is not updated anymore
