### ISSUE TITLE
bltouch homing strange behaviour

### ISSUE THREAD

**Issue by dedalodaelus** [MarlinFirmware/Marlin#10348]
Hello I'm running a Prusa Clone with ramps 1.4SB and TMC2130 and BLtouch.

I'm using Marling Bugfix1.1.X

The problem seems that Z homing do no work with my glass bed (or hard materials), the nozzle continues to go down, even when the probe touch the bed. If I place a credit card or paper block the sensor works fine. 
Can anyone help with this issue?

I attach a video where it can be seen:
[https://www.youtube.com/watch?v=FIXEjqmwTa0](https://www.youtube.com/watch?v=FIXEjqmwTa0)

I also attach my config files.
[bltouch-issue-cfg-files.zip](https://github.com/MarlinFirmware/Marlin/files/1888371/bltouch-issue-cfg-files.zip)
Thanks in advance

**Comment by thinkyhead** [comment]
This sounds like a BLTouch electronics issue. Marlin can't do anything about it if there's no trigger signal from the probe. See if it helps to enable `ENDSTOPPULLUP_ZMIN_PROBE`.

**Comment by dedalodaelus** [comment]
Thanks, for the answer, Currently I using this define:
``#define ENDSTOPPULLUPS``
It enables the `ENDSTOPPULLUP_ZMIN_PROBE` define? or I should disable it?

**Comment by GMagician** [comment]
Maybe bltouch doesn't trigger because is too high. The card thickness is enough to let it trigger.

**Comment by dedalodaelus** [comment]
I will try with a kapton tape, but I don't think is too high, but I will try anyway and get back to you.

**Comment by GhostlyCrowd** [comment]
I have the same setup and my BL touch is working fine, I'd also agree its probably too high.

**Comment by psavva** [comment]
I've had this exact same problem.  Your bltouch is too high.  Try put spacers between your bltouch and your mount as lower the bltouch by 1 or 2mm.  Your nozzle is pushing your bed down, and the pin on the bltouch cannot trigger...

**Comment by dedalodaelus** [comment]
You were right, the probe was too high, I lowered it and worked perfectlly. Thanks to all for your support.

**Comment by thinkyhead** [comment]
Ah, right. Apparently that pullup is set by `ENDSTOPPULLUPS`. I don't see a point in disabling it.
