### ISSUE TITLE
Z Probe failed to retract on proximity probe.

### ISSUE THREAD

**Issue by ChrisP28** [MarlinFirmware/Marlin#10354]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* Read the "Contributing" page (under "Helpful resources") for additional guidelines.

**Comment by psavva** [comment]
Any details on the issue would be helpful, as well as your configuration files

**Comment by ChrisP28** [comment]
I work away so I’ll have to get the configuration files when I return. Thanks

**Comment by thinkyhead** [comment]
Great. Please start a new issue and fill out all the requested information.
