### ISSUE TITLE
[bugfix-1.1.x] SanityCheck X_MIN_ENDSTOP_INVERTING 

### ISSUE THREAD

**Issue by Ludy87** [MarlinFirmware/Marlin#10359]
### Description

I try to activate SENSORLESS_HOMING and get the error.

       SanityCheck.h:1446: error: #error "SENSORLESS_HOMING requires X_MIN_ENDSTOP_INVERTING when homing to X_MIN."

       #error "SENSORLESS_HOMING requires X_MIN_ENDSTOP_INVERTING when homing to X_MIN."

### Steps to Reproduce

1. activeate SENSORLESS_HOMING in Configuration_adv.h
2. compiling

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1891676/Configuration.zip)

sorry for my bad English

**Comment by psavva** [comment]
In your configuration.h file, change
#define X_MIN_ENDSTOP_INVERTING false
to
#define X_MIN_ENDSTOP_INVERTING true

**Comment by thinkyhead** [comment]
Yep! We often use `#error` to tell you what you need to change.

**Comment by Ludy87** [comment]
When set to true, the ENDSTOP is triggered and is not open!

**Comment by marcio-ao** [comment]
Do you have the pullup resistors enabled?

**Comment by Ludy87** [comment]
<del>No, why?</del>

EDIT: Yes, this error is same!

**Comment by marcio-ao** [comment]
@Ludy87 : I'm just trying to narrow down the problem. If the ~~endstops~~ pullup resistors had not been enabled, it would explain why sensorless homing was not working for you.

**Comment by Ludy87** [comment]
Real? Before have i update install, no error!

**Comment by marcio-ao** [comment]
@Ludy87 : I believe you when you say something is wrong, I just don't know what.

**Comment by thinkyhead** [comment]
@Ludy87 — Try `M502` followed by `M500` and re-start the machine to see if it helps.

**Comment by thinkyhead** [comment]
@marcio-ao — The line that was removed setting diag1….
Should it perhaps just have been _changed_ instead?

**Comment by marcio-ao** [comment]
@thinkyhead : I could have changed it to the following:

`st.diag1_active_high(0); // For sensorless homing`

However, this is supposed to be the power up default. I suppose people could be having issues if they upgraded their FW and did not cycle the power on their printers.

**Comment by thinkyhead** [comment]
It's certainly possible for the stepper drivers to maintain voltage —and thus previous state— across reboots. But it sounds like the issue would indicate corrupted state.

**Comment by Ludy87** [comment]
sorry, it was a short on the board. Apologize a lot!
