### ISSUE TITLE
Pause and subsequent Cancel causes UI to become unresponsive.

### ISSUE THREAD

**Issue by ralxnder** [MarlinFirmware/Marlin#10357]
### Description

Updated to Octoprint 1.3.7.  The UI becomes unresponsive after a pause subsequent resume. Even if I refresh the page I can no longer control the printer. I have to disconnect and re-connect.

### Steps to Reproduce

1. Start any print.
2. Pause the print.
3. Cancel the print.

**Expected behavior:** [What you expect to happen]
I expect the UI to refresh so that I can control the printer or load other gcode files.

**Actual behavior:** [What actually happens]
GUI controls become unresponsive and requires a re-connect.

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* Read the "Contributing" page (under "Helpful resources") for additional guidelines.
![2018-04-09 15_34_31-octoprint](https://user-images.githubusercontent.com/6548415/38518716-b4daf3d2-3c0b-11e8-9693-111311e483aa.png)

**Comment by psavva** [comment]
It seems this should be opened up on the Octoprint project.

https://github.com/foosel/OctoPrint
