### ISSUE TITLE
hot end thermistor 300 celsius + hotend does not want to heat up

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [MarlinFirmware/Marlin#10356]
![img_20180407_062225](https://user-images.githubusercontent.com/4707623/38515722-a670c206-3bfa-11e8-965b-fcfb5ef70df8.jpg)

**Comment by ManuelMcLure** [comment]
This is most likely a hardware issue with the hotend thermistor input on your motherboard or an incorrect thermistor selection in your configuration.

**Comment by REVIEWGAMINGMAN** [comment]
would reflashing the bootloader help

**Comment by ManuelMcLure** [comment]
I would very much doubt it.

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by REVIEWGAMINGMAN** [comment]
[
![img_20180411_073033](https://user-images.githubusercontent.com/4707623/38618793-3caca6e8-3d60-11e8-8ca9-8596859ad97e.jpg)
](url)

**Comment by REVIEWGAMINGMAN** [comment]
![img_20180411_073022](https://user-images.githubusercontent.com/4707623/38618828-4fb85a48-3d60-11e8-938c-49582c27da67.jpg)

**Comment by Grogyan** [comment]
Thermistor is damaged and needs replacing

**Comment by boelle** [comment]
@REVIEWGAMINGMAN did you try replacing thermistor?

@thinkyhead think we can close this one

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
