### ISSUE TITLE
Sanity Check Z probe

### ISSUE THREAD

**Issue by deadmanArt** [MarlinFirmware/Marlin#10361]
hi all hope someone is able to help have this print and need to reinstall the firmware on it to resolve an issue.

i got it mostly all worked out apart from 
```
In file included from sketch\MarlinConfig.h:42:0,

                 from G:\Documents\Marlin-1.1.8 - VOXEL\MarlinBackup\MarlinBackup.ino:31:

SanityCheck.h:712: error: #error "You must enable either Z_MIN_PROBE_ENDSTOP or Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN to use a probe."

     #error "You must enable either Z_MIN_PROBE_ENDSTOP or Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN to use a probe."

      ^

exit status 1
#error "You must enable either Z_MIN_PROBE_ENDSTOP or Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN to use a probe."
```
[Configuration.h.zip](https://github.com/MarlinFirmware/Marlin/files/1892538/Configuration.h.zip)

[Configuration_adv.h.zip](https://github.com/MarlinFirmware/Marlin/files/1892537/Configuration_adv.h.zip)

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* Read the "Contributing" page (under "Helpful resources") for additional guidelines.

**Comment by psavva** [comment]
What Sensor are you using for your bed levelling?

**Comment by thinkyhead** [comment]
To resolve the issue…

You must enable either `Z_MIN_PROBE_ENDSTOP` or `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN`.

**Comment by boelle** [comment]
@deadmanArt 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
