### ISSUE TITLE
[FR] Fichier source Crealty3D CR-10S officiel

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#10378]
https://github.com/ShenzhenChuangxiang3D/Marlin/releases/tag/CR-10S--1.1.0-RC3

https://youtu.be/kJxaSKwwMGk

**Comment by thinkyhead** [comment]
Yes indeed. I created that repository last night.

**Comment by idanmos** [comment]
Will anyone think to import the 'Resume on Power-Loss (SDCard-based)' feature?
I think this can be great.

**Comment by valerie16901** [comment]
Yes, please!
But it will be great to have an option to enable it or disable it from the menu, since it makes continuous heavy use of the SD Card during SD printing maybe not everyone would want it enabled.

**Comment by thinkyhead** [comment]
> Will anyone think to import the 'Resume on Power-Loss (SDCard-based)' feature?

![image](https://user-images.githubusercontent.com/698003/38717195-00cffd86-3eab-11e8-9e99-553daf7ebc2a.png)

**Comment by boelle** [comment]
@thinkyhead funny title/subject, what does it mean?

**Comment by InsanityAutomation** [comment]
@boelle @shitcreek The needful from here has been incorporated. This can be closed.
