### ISSUE TITLE
4 Independent Extruders 

### ISSUE THREAD

**Issue by marcmillet** [MarlinFirmware/Marlin#10376]
I am working on project where i have 4 independent extruders. They are in two different X axis bars, which share the same Y (both bars move together) but i have 4 separate x axis steppers. It occured to me to enable the dual x-carriage and add some code that changes the pins defined for both X steppers, depending on which tool is selected. Where and how can i add such code?

If someone has a better idea, i'll be willing to hear them.

**Comment by thinkyhead** [comment]
Follow the `DUAL_X_CARRIAGE` breadcrumbs throughout the code to see the plethora of locations where changes will be needed, starting with `stepper_indirection.h`…
