### ISSUE TITLE
Bad Z offset with AUTO_BED_LEVELING_LINEAR and NOZZLE_CLEAN_FEATURE

### ISSUE THREAD

**Issue by kakou-fr** [MarlinFirmware/Marlin#10377]
### Description

I use a bltouch and  just switched from `AUTO_BED_LEVELING_BILINEAR` to `AUTO_BED_LEVELING_LINEAR` because I use a clean glass. If the NOZZLE CLEAN FEATURE is activated, the z offset is bad. The nozzle doesn't move down when it must be clean, and so it move up (for me 10mm) after cleaning. When the print start, the nozzle is 10mm too high. I use marlin 1.1.8 bugfix.

### Steps to Reproduce

My start gcode, if i disable "G12 P1 S2 T3", all works well
```gcode
G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode
M107 ;start with the fan off
M420 Z10 ; Z height 1cm after no compensation
G28 X0 Y0 ;move X/Y to min endstops
G28
G29
G1 X110
M109 S[first_layer_temperature]
G12 P1 S2 T3
G1 Z15.0 F9000 ;move the platform down 15mm
G92 E0 ;zero the extruded length
G1 F9000
M117 Printing...
M300 S2793 P1800 ;BIP
```

**Comment by thinkyhead** [comment]
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as requested in the Issue template) and drop them into your next reply. We'll check them over and see if anything is amiss.

**Comment by thinkyhead** [comment]
To gather more information:

- Download Marlin `bugfix-1.1.x` or `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Add the line `M111 S247` before your `G12` command. Slice a simple model.
- Run the G-code up to the point where it is about to start printing, then abort.
- Copy the log output into a **.TXT file** and attach it to your next reply.

**Comment by kakou-fr** [comment]
My config file are available [here](https://drive.google.com/open?id=1NZT_7-qGXsHWolodb6Hpb1xVaFL2IqAC)

I use the latest bugfix-1.1.x

I will do the other test this afternoon

**Comment by boelle** [comment]
@kakou-fr what did the test end with?

**Comment by kakou-fr** [comment]
@boelle I switched to Klipper :)

**Comment by boelle** [comment]
@kakou-fr then maybe click the green close button below
