### ISSUE TITLE
Seemingly random motion after "Stop print"

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#10372]
The "Stop Print" command from the LCD menu sometimes generates a seemingly random move prior to stopping that can sometimes cause the printer to run into the limits.

1. Start a print from the LCD
2. Select "Stop Print"
3. Watch the hotend carefully.
4. Repeat this several times... it does not always happen.

**Expected behavior:** The printer should stop immediately.

**Actual behavior:** Every few times, the printer hotend will move in a seemingly random direction prior to stopping.

On the 1.1.8 stable branch, I see this behavior along with a momentary flash of the "Print Pause" screen. On the "bugfix 2.0.x" branch, it seems as if the LCD flash has been fixed, but the random motion after stop print remains.

**Comment by thinkyhead** [comment]
I haven't seen this issue yet, but I will do some testing soon. Preliminary questions:
- Does this only happen if the carriage is already moving?
- Does the carriage move in XY and/or Z, or just the extruder motor?

Any theories as to where this extra move is coming from?

**Comment by marcio-ao** [comment]
I had a theory, but I've ruled it out. Some of the people at my company had been reporting this issue more than others. At first, I thought maybe it had to do with what model was being printed. I thought maybe that the error was being caused by some line of GCODE from the original model being left in the planner after a stop. This would mean that the error would be less noticeable on prints with small movements (such as benchy), while more noticeable on bigger parts with bigger movements. But I printed a big cube and in every time I tried it, the print seemed to stop on command. So that theory seems to be wrong and at the moment I do not know under what circumstances the extra moves crop up.

**Comment by thinkyhead** [comment]
Interesting… Well hopefully a 100% reproducible case can be devised. I was looking to make sure the Stepper ISR is disabled as part of the process, and apparently it is.

**Comment by januar3829** [comment]
> - Does this only happen if the carriage is already moving?
> - Does the carriage move in XY and/or Z, or just the extruder motor?

In that moment I pressed "Stop Print" it actually stoped (firsts dot on the bed), just to make a movement in the same direction as before (Y-Axis) with a little X-offset and then come to rest (second dot) 
![stop](https://user-images.githubusercontent.com/33001508/38731950-a2367364-3f1c-11e8-8e1e-3ca9ebc23c84.jpg)

**Comment by marcio-ao** [comment]
@januar3829 : Yes, that looks like exactly it.

**Comment by thinkyhead** [comment]
It has the appearance of the previous block getting repeated. Keep an eye on this effect and see if that is consistent. I've patched the bugfix branches with some redundancies that probably won't have any effect, but be sure to use the latest code anyway.

**Comment by januar3829** [comment]
Sorry, I forgot to mention that this issue started when I updated from 1.1 to 1.1.8

**Comment by thinkyhead** [comment]
@januar3829 — 1.1.0 ?

**Comment by januar3829** [comment]
Yes, 1.1.0, it was the original Firmware on my Tevo Tornado

**Comment by thinkyhead** [comment]
I've added a patch that does Stop Print a little differently.
See if the current `bugfix-1.1.x` behaves any better.

**Comment by januar3829** [comment]
I'll test your patch as soon as I've figured out how to use apply a  bugfix
But there's one more question related with this topic: I don't want the Printer to cool down after I stopped a Print, where can I adapt that?

**Comment by thinkyhead** [comment]
> I don't want the Printer to cool down after I stopped a Print, where can I adapt that?

`ultralcd.cpp`:

```diff
  void lcd_sdcard_stop() {
    card.stopSDPrint();
    clear_command_queue();
    quickstop_stepper();
    print_job_timer.stop();
-   thermalManager.disable_all_heaters();
    #if FAN_COUNT > 0
      for (uint8_t i = 0; i < FAN_COUNT; i++) fanSpeeds[i] = 0;
    #endif
    wait_for_heatup = false;
    lcd_setstatusPGM(PSTR(MSG_PRINT_ABORTED), -1);
    lcd_return_to_status();
  }
```

**Comment by marcio-ao** [comment]
Closing this ticket since I haven't seen this problem in a while.
