### ISSUE TITLE
TMC 2130 not working properly

### ISSUE THREAD

**Issue by craitor** [MarlinFirmware/Marlin#10382]
I am using TMC 2130 stepper drivers. However, my stepper motors are constantly disabled.

I am using the RAMPS 1.4 together with the repetier software. I have the most recent version of Marlin installed. The TMC2130 are from Watterrot.

I ran the M122 command in Repetier and the stepper motors are constantly disabled. Here is the output I obtained from the M122 command:
```
00:33:24.966 : X	Y	Z
00:33:24.966 : Enabled	false	false	false
00:33:24.966 : Set current	800	800	800
00:33:24.970 : RMS current	1436	1436	1436
00:33:24.970 : MAX current	2025	2025	2025
00:33:24.970 : Run current	25/31	25/31	25/31
00:33:24.974 : Hold current	12/31	12/31	12/31
00:33:24.974 : CS actual	0/31	0/31	0/31
00:33:24.974 : PWM scale	0	0	0
00:33:24.974 : vsense	0=.325	0=.325	0=.325
00:33:24.978 : stealthChop	false	false	false
00:33:24.978 : msteps	256	256	256
00:33:24.978 : tstep	0	0	0
00:33:24.978 : pwm
00:33:24.978 : threshold	0	0	0
00:33:24.982 : [mm/s]	-	-	-
00:33:24.982 : OT prewarn	false	false	false
00:33:24.982 : OT prewarn has
00:33:24.982 : been triggered	false	false	false
00:33:24.983 : off time	0	0	0
00:33:24.987 : blank time	16	16	16
00:33:24.987 : hysterisis
00:33:24.987 : -end	-3	-3	-3
00:33:24.987 : -start	1	1	1
00:33:24.987 : Stallguard thrs	0	0	0
00:33:24.991 : DRVSTATUS	X	Y	Z
00:33:24.991 : stallguard
00:33:24.991 : sg_result	0	0	0
00:33:24.991 : fsactive
00:33:24.991 : stst
00:33:24.991 : olb
00:33:24.991 : ola
00:33:24.991 : s2gb
00:33:24.995 : s2ga
00:33:24.995 : otpw
00:33:24.995 : ot
00:33:24.995 : Driver registers:
00:33:24.995 : X = 0x00:00:00:00
00:33:24.995 : Y = 0x00:00:00:00
00:33:24.998 : Z = 0x00:00:00:00
```
I attached the config files

[code.zip](https://github.com/MarlinFirmware/Marlin/files/1901839/code.zip)

**Comment by teemuatlut** [comment]
We've got some debugging steps for you to follow on the [Marlin homepage](http://marlinfw.org/docs/features/tmc_drivers.html). I suggest you start with wiring and pin definitions.

* Test the current bugfix branch of Marlin posted on GitHub (in case your issue is already fixed).
* Use the latest TMC Stepper libraries.
* Check all wiring and wire crimps.
* Check 12V (24V) power in the Vm pin and 5V (3.3V) in the Vio pin.
* Check that configured pins match your firmware configuration.
* Enable TMC_DEBUG and send M122 to see the debugging output.
  * Reported register values of either 0x00000000 or 0xFFFFFFFF are bad responses.
* Try the examples provided by the respective library. Please detach any belts beforehand however, as the examples will not respect any endstop signals or physical limits. You may need to change the pin definitions.

If nothing works, please also post a picture of your wiring.

**Comment by craitor** [comment]
A baud rate of 200000 isn't a standard that can be selected by repetier however. Howe would I go around this issue?

**Comment by thinkyhead** [comment]
> A baud rate of 200000 isn't a standard that can be selected by repetier however. Howe would I go around this issue?

Are you responding to the correct issue? There's no mention of Baud Rate in the above reply.

If your host can't use a baud rate of 200000, that's fine. After you grab the `bugfix-1.1.x` branch for testing and move your configuration over, set `BAUDRATE` in the configuration to 115200. Or, use a different host application that _can_ set a baud rate of 200000.

**Comment by craitor** [comment]
Yes, I accidentally looked at a different issue.

So I did some further testing on the hardware, which doesn't seem to be the issue. I replaced the TMC 2130 drivers with regular Polulu drivers and the motors worked fine, which seems to indicate that the Ramps and arduino hardware are intact. 

I checked my pin selections - they seem to be fine.

Here is the wiring:

![img_20180417_234026](https://user-images.githubusercontent.com/32019984/38916379-0494bff2-429c-11e8-89f2-f88270864561.jpg)
![img_20180417_232749](https://user-images.githubusercontent.com/32019984/38916381-04b21f7a-429c-11e8-9855-450f118197a6.jpg)

The driver register values are still 0x00:00:00:00.

The config files are identical

**Comment by craitor** [comment]
I know there are some other tmc 2130 stepper driver that need to bridge 2 connections on the side of the chip. I don't think these Watterrot stepper drivers do however to enable SPI mode. Am I wrong?

**Comment by thinkyhead** [comment]
Good question. I would have to hunt and check the datasheet to answer.

**Comment by CHILLYSMOKES** [comment]
You don't need to bridge anything on the Watterotts, only the chinesium ones. Do you use a relay or atx function to remote power on your printer?

**Comment by Ludy87** [comment]
Try: remove all Jumpers from your board!

**Comment by landodragon141** [comment]
Did you solder the pins for SDO, SDI, SCLK, and CS facing down? If so follow Ludy87's advice and pull the config jumpers from under the driver.

**Comment by Dark-Noir** [comment]
Similar problem here, everything is setup correctly but after one minute of printing i got a driver error from the extruder driver. Now the drivers are no longer working at all (all four of them), i tryed reflashing, resoldering etc.
12v and 5v are there, now jumpers set under the drivers.

Running already on Marlin bugfix from today.

```
Recv:                    X  Y  Z  E0
Recv: Enabled		false	 false	  false   false
Recv: Set current	1000 1000 1000 1000
Recv: RMS current	994	  994   994   994
Recv: MAX current	1402	1402	1402	1402
Recv: Run current	17/31	17/31	17/31	17/31
Recv: Hold current	8/31	8/31	8/31	8/31
Recv: CS actual		0/31	0/31	0/31	0/31
Recv: PWM scale	0	0	0	0
Recv: vsense		0=.325	0=.325	0=.325	0=.325
Recv: stealthChop	false	false	false	false
Recv: msteps		256	256	256	256
Recv: tstep		1048575	1048575	1048575	1048575
Recv: pwm
Recv: threshold		0	0	0	0
Recv: [mm/s]		-	-	-	-
Recv: OT prewarn	false	false	false	false
Recv: OT prewarn has
Recv: been triggered	false	false	false	false
Recv: off time		0	0	0	0
Recv: blank time	16	16	16	16
Recv: hysteresis
Recv: -end		-3	-3	-3	-3
Recv: -start		1	1	1	1
Recv: Stallguard thrs	0	0	0	0
Recv: DRVSTATUS	X	Y	Z	E0
Recv: stallguard
Recv: sg_result		0	0	0	0
Recv: fsactive
Recv: stst		X	X	X	X
Recv: olb		X	X		X
Recv: ola		X	X		X
Recv: s2gb
Recv: s2ga
Recv: otpw
Recv: ot
Recv: Driver registers:	X = 0xE0:00:00:00
Recv: 	Y = 0xE0:00:00:00
Recv: 	Z = 0x80:00:00:00
Recv: 	E0 = 0xE0:00:00:00
```

The driver registers sometimes, but most of the time it only says 0x00:00:00:00

**Comment by landodragon141** [comment]
First off drop your current. You are probably overheating your drivers at 1A. I'd set it to 850-800 and try again. You really don't need that much current for the TMC2130s.

**Comment by Dark-Noir** [comment]
> First off drop your current. You are probably overheating your drivers at 1A. I'd set it to 850-800 and try again. You really don't need that much current for the TMC2130s.

Didn't changed anything. I had increased the current because of skipping steps/layer shifting. Also my drivers didn't get hot.

**Comment by Ludy87** [comment]
check your Wires, is your SPI connected with SD Card or Display? Try SPI SW on a free pins.
Post your config File.

**Comment by Dark-Noir** [comment]
> check your Wires, is your SPI connected with SD Card or Display? Try SPI SW on a free pins.
Post your config File.

Yeah, i have a 12864 display with SD card reader and a BLTouch, so i had to use some other pins. I don't use sensorless homing and i didn't connect the cables for it.

![img_20180604_134939](https://user-images.githubusercontent.com/8070059/40916073-ab588562-67fe-11e8-9f13-6805616eba4e.jpg)

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2068094/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/2068095/Configuration_adv.txt)
[pins_RAMPS.txt](https://github.com/MarlinFirmware/Marlin/files/2068096/pins_RAMPS.txt)

**Comment by Ludy87** [comment]
You must change the wire from driver, and enable
``` cpp
   #define TMC_USE_SW_SPI
   #define TMC_SW_MOSI       -1
   #define TMC_SW_MISO       -1
   #define TMC_SW_SCK        -1
```
and write your new pin Numbers

**Comment by Dark-Noir** [comment]
> You must change the wire from driver, and enable
> 
> #define TMC_USE_SW_SPI
> #define TMC_SW_MOSI -1
> #define TMC_SW_MISO -1
> #define TMC_SW_SCK -1
> 
> and write your new pin Numbers

Why i can't use HW SPI? A new Arduino didnt fixed the Problem.
Can i use 63,65,66 from AUX2?

**Comment by Ludy87** [comment]
Try it or forget it😊

**Comment by Dark-Noir** [comment]
> Try it or forget it😊

A new Arduino didn't fixed the Problem.
I use now 63,65,66 from AUX2 for SW SPI. Drivers seems to work, i do a test print now.

Edit: Seems to work now, but why is HW SPI broken? It is a bug in marlin?

**Comment by Ludy87** [comment]
The load on the pins is too high.

**Comment by landodragon141** [comment]
If you have a screen and or SD Card attached to the HW SPI it's too much to also put the 2130's on that same bus.

**Comment by teemuatlut** [comment]
> If you have a screen and or SD Card attached to the HW SPI it's too much to also put the 2130's on that same bus.

Not true. The TMC2130 only need SPI communication to initialize the parameters when you start the machine. Any comms after that is either because `MONITOR_DRIVER_STATUS` is enabled or you sent a related `M` command.

**Comment by thinkyhead** [comment]
@teemuatlut — Any chance that a noisy CS pin could cause data bound for the LCD to get to the TMCs and cause mayhem?

**Comment by teemuatlut** [comment]
Unlikely as the datagram would have to follow a very specific pattern required by the driver.

**Comment by towe96** [comment]
Did software SPI fix your issues? I have the same driver issue - suddenly stopping amidst a print, but software SPI made no difference to me. @Dark-Noir

**Comment by Dark-Noir** [comment]
@towe96 I bought a Rumba plus board, since then no problems.

**Comment by boelle** [comment]
@craitor still having an issue?

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
