### ISSUE TITLE
M118 Not working as expected

### ISSUE THREAD

**Issue by benlye** [MarlinFirmware/Marlin#10388]
### Description

The `M118` command is not working as expected when trying to send output to the console - when the text includes an `A` or an `E` anywhere in the string the output misbehaves.

I've tested in bugfix-1.1.x and bugfix-2.0.x and found the same behaviour in both.

#### No parameter

**Command:** 
`M118 A bad thing happened!`

**Expected behavior:**
```
Send: M118 A bad thing happened!
Recv: A bad thing happened!
Recv: ok
```

**Actual behavior:**
```
Send: M118 A bad thing happened!
Recv:  bad thing happened!
Recv: ok
```

####  `A` parameter
`M118 A1 ACTION:dostuff`

**Expected behavior:**
```
Send: M118 A1 ACTION:dostuff
Recv: //ACTION:dostuff
Recv: ok
```

**Actual behavior:**
```
Send: M118 A1 ACTION:dostuff
Recv: ACTION:dostuff
Recv: ok
```

####  `E` parameter
`M118 E1 Event happened`

**Expected behavior:**
```
Send: M118 E1 Event happened
Recv: echo:Event happened
Recv: ok
```

**Actual behavior:**
```
Send: M118 E1 Event happened
Recv: Event happened
Recv: ok
```

### More information
It seems that if an `A1` parameter is given then the presence of a letter `A` anywhere in the string breaks the expected behaviour.  If an `E1` parameter is given the presence of the letter `E` anywhere in the string breaks.

Also, the `A1` behaviour as implemented is broken as it puts a space after the `//`, when OctoPrint expects no space between the slashes and the commands.

It seems like this is just trying to be too clever, and adding unneeded complexity.  Could we scrap the `A` and `E` parameters altogether and just make it behave like `M117` - the whole argument is treated as a string and sent to the console as entered.  That would leave it up to the user to prepend `//`  or `echo:` as they need.

**Comment by benlye** [comment]
My testing of this behaviour was partially thwarted by OctoPrint, which converts terminal commands to uppercase for all commands except `M117` by default.  I've opened a PR on OctoPrint (https://github.com/foosel/OctoPrint/pull/2573) to add `M118` to the auto-uppercasing blacklist.

**Comment by thinkyhead** [comment]
Now patched in the bugfix branches. Please confirm whether it works and close this issue if we got it.

**Comment by benlye** [comment]
Perfect - thanks!
