### ISSUE TITLE
No Extrusion if retract value over 4mm

### ISSUE THREAD

**Issue by Mak3rde** [MarlinFirmware/Marlin#10384]
### Description
No Extrusion if retract value over 4mm
Marlin 1.1.8rc NO lin_adv
Mks Gen_L
Titan extruder/0.9 stepper/bowden/Volcano

### Steps to Reproduce
1. retract value of 4mm or more 
2. slice
3. start job with octoprint/  or s3d via usb

**Expected behavior:** 
print should work

**Actual behavior:**
start gcode including nozzle prime ,working as expected
when the actual slicer gcod starts, extruder stops moving, no extrusion at all
Tested with Slic3r pursa edition, cura 3.2.1, S3D 4.0

**Comment by thinkyhead** [comment]
Firmware retraction or slicer-based retraction?

Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by boelle** [comment]
@phillipsko tried what thinky suggested?

**Comment by Mak3rde** [comment]
Uff that's a long time ago I really don't know what I did to get it back
working, meanwhile i changed to Klipper fw.

Am Mi., 20. Feb. 2019, 12:28 hat Bo Herrmannsen <notifications@github.com>
geschrieben:

**Comment by boelle** [comment]
@phillipsko then maybe hit the green close botton below?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
