### ISSUE TITLE
Long Press Does not Exit UBL G29

### ISSUE THREAD

**Issue by msticninja** [MarlinFirmware/Marlin#10393]
When doing a G29 P1 or P2, long pressing the encoder button does not exit/abort process.
Marlin 1.1.x-bugfix, checked out today 4/12/18.
[Marlin_config.zip](https://github.com/MarlinFirmware/Marlin/files/1905623/Marlin_config.zip)
PS So you don't have to dig through the config, it's a reprap discount full graphics controller.

**Comment by thinkyhead** [comment]
Strange. Because this code reads the LCD encoder's button directly:
```cpp
#if ENABLED(NEWPANEL)
  if (is_lcd_clicked()) {
    SERIAL_PROTOCOLLNPGM("\nMesh only partially populated.\n");
    lcd_quick_feedback(false);
    STOW_PROBE();
    while (is_lcd_clicked()) idle();
    lcd_external_control = false;
    restore_ubl_active_state_and_leave();
    lcd_quick_feedback(true);
    safe_delay(50);  // Debounce the Encoder wheel
    return;
  }
#endif
```

**Comment by msticninja** [comment]
Is that code active even during the first part of P2 B, when you are first measuring the shim to determine its thickness? IIRC that's the exact point I was trying to escape from, maybe that's intended? 

Also, I should start a different Issue, but maybe it's a known issue for Delta printers still: The LCD UBL Edit menu does not respect endstops and tries to go to an invalid location when entering the interactive mesh editing, and moves outside the build area. Like, waaaay out. 

One more with UBL, G29 P2 B T worked fine, but while homing at the end of the G29, it did not stop when endstops were hit, and kept ramming the effector arms into the endstops. Naturally I lost the mesh edits because I had to hard reset. :D

I'll create separate issues and get more info for them if they aren't known issues.

PS Thanks for the help and all the hard work, been using Marlin for a couple years, wouldn't change if I had to.

**Comment by thinkyhead** [comment]
Right, there's no abort from `P2 B` shim measurement, only from the `P1` mesh point probing and the `P2` fill-in other points. (And also from `G29 P4` mesh fine-tuning.)

**Comment by thinkyhead** [comment]
> The LCD UBL Edit menu does not respect endstops and tries to go to an invalid location when entering the interactive mesh editing

It does that right on start, eh? We'll have to add some logging to see what's going on there.

**Comment by msticninja** [comment]
Yes, it does it on start, I'll get some more info and open an Issue. If you aren't supposed to be able to abort from shim measurement, I'd say this Issue is closed. It aborts out of P4 fine, so I'll just keep an eye for it next time I do P2 after the shim section.
