### ISSUE TITLE
2.0.x - 13 April - u8g.h bug (again)

### ISSUE THREAD

**Issue by Nume1977** [MarlinFirmware/Marlin#10395]
This seems to be a regression bug, tested with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER enabled and using Arduino IDE to compile:

```
sketch\src\lcd\u8g_fontutf8.h:12:17: fatal error: u8g.h: No such file or directory

 #include "u8g.h"
```
or
```
sketch\src\lcd\u8g_fontutf8.h:12:17: fatal error: u8g.h: No such file or directory

 #include <u8g.h>
```

**I have just checked, compilation is working until the "[2.0.x] 6th-order jerk-controlled motion planning in real-time for AVR " commit, the next commit after that one breaks compilation!**

**Comment by rmoravcik** [comment]
Try to replace u8g.h with clib/u8g.h, this worked for me

**Comment by thinkyhead** [comment]
Try `#include <U8glib.h>`. This issue originates with #10213.

**Comment by thinkyhead** [comment]
@yhfudev — We'll need a definitive fix for this issue. I'm not sure where "u8g.h" is supposed to be, but currently not all user build tools are finding it.

**Comment by thinkyhead** [comment]
@yhfudev — We also need good documentation on how to use the scripts in `buildroot/share/fonts`. I have some patches for items in that folder which I will post shortly in another PR for your review. Meanwhile, please review a92776d.

**Comment by p3p** [comment]
> I'm not sure where "u8g.h" is supposed to be, but currently not all user build tools are finding it.

It's in the lib folder in Marlins u8glib-HAL library, clib in the normal Arduino version, I'm not sure how Arduino decides what sub directories to add the the Include Path or why it stopped working, neither library specifies in the associated library descriptor. No idea why it stopped being found though..

**Comment by yhfudev** [comment]
The current source code can't support both of "end user" and "travis build system" at the same time. The path 'lib/u8g.h' (u8glib-HAL) currently only used in the travis/platformio script. so we need to change the include to '<clib/u8g.h>'. Fortunately, the clib/u8g.h needed only in one file u8g_fontutf8.h. I'm working on this issue, and will submit the PR with a set of changed files that can support both "end user" and "travis".

**Comment by p3p** [comment]
I presume if it really is necessary to bypass the api and access the c header directly from the subdirectory the directory name can be changed in Marlins u8glib-HAL to simplify things.

**Comment by yhfudev** [comment]
It is needed by the utf8 engine in the file u8g_fontutf8.c,
The PR #10419 will handle the "lib/u8g.h" and "clib/u8g.h" problem.

**Comment by p3p** [comment]
We need to fix this without workarounds, such as the added Include path in platformio.ini, or the Travis only fix in your PR, normal PlatformIO builds will still be broken.
