### ISSUE TITLE
[2.0.x] MKS SBASE + SD Card + Software SPI not working

### ISSUE THREAD

**Issue by warbunnies** [MarlinFirmware/Marlin#10400]
What changes need to be made to the current firmware to get the software sd card to work?

I have:
- enabled in the config file & #define SD_CHECK_AND_RETRY
-broken out the miso, mosi, & sck to the suggested locations and check 4 times that it was wired right.
-also broke out the SD detect pin because it wasn't working for some reason...but now it is on pin 2_13!
-I tried several different spi_pin.h files people have been floating around and nothing worked. Is there a "this spi_pin.h file is the officially right one of the sbase"?

I'm running out of things to try.  Any ideas?

**Comment by p3p** [comment]
> I tried several different spi_pin.h files people have been floating around and nothing worked. Is there a "this spi_pin.h file is the officially right one of the sbase"?

As far as I'm aware the officially correct one is the one we have, there should be no need to change it. Hopefully someone with an mks sbase can help you, I maintain the LPC1768 platform but do not have access to this board, only the connector is different though, it 'should' work when wired correctly.

**Comment by warbunnies** [comment]
Hmm... maybe something is wrong with my cable then. The sd card detect on the main screen didn't work until I broke out the pin. Thank you for updating me. I'll try some dupont connectors and see if i can get this working.

**Comment by zhenguwu** [comment]
@warbunnies Have you gotten yours to work? 

I've tried several fixes from past posts but my sd card is still not detected and eeprom is not saved.

**Comment by warbunnies** [comment]
No I have not. Though I am curious about one thing. 
```cpp
#define SCK_PIN            P1_22   // J8-2 (moved from EXP2 P0.7)
#define MISO_PIN           P1_23   // J8-3 (moved from EXP2 P0.8)
#define MOSI_PIN           P2_12   // J8-4 (moved from EXP2 P0.5)
``` 
The MOSI_PIN is not p0.5. 
The rr glcd pinout for Mosi is pin 6 on EX2 and the sbase Mosi is p0.9. 
Pin 5 on the rr glcd is the BTN_EN1 and p0.5 on the sbase pinout is for the x-stepper motor breakout. 

Is this a typo? or just poorly explained? Cause right now I've got the MOSI pin from the rr glcd running to P2_12

**Comment by p3p** [comment]
@michaelwu21 The onboard sdcard used for eeprom and flashing is unrelated to these settings, it is connected to `P0_07 (SCK)` `P0_08 (MISO)` `P0_09 (MOSI)` this cannot be modified and from the schematic (I only have one for mks sbase v1.2) this is correct, Others have had issues with the onboard sd-card, reformatting or changing the card has helped but I haven't been able to reproduce the issue on my Re-ARM and I have a lot of sd cards.

@warbunnies I think that is a typo, should be P0.9. 
In `pins_MKS_SBASE.h` `SDSS` is set as `P0_06` which is the onboard sd cards select pin, shouldn't that be `P0_28`, or just not specified in which case I think it will be autodefined as `SS_PIN`

**Comment by warbunnies** [comment]
I will see if switching the SDss pin from 0_06 to P0_28 or unspecified and see what happens

**Comment by warbunnies** [comment]
#define LCD_PINS_D4      P0_15   // EXP1.5

also curious about this. Not sure if it matters for the sd card but exp1.5 is pin 0_14. Any pinout I can find doesn't have a p0_15 on exp1

**Comment by p3p** [comment]
The schematic I have shows that as being correct, but I can't confirm it without the hardware. It shouldn't be a problem unless you are using a character display (doesn't use spi).

**Comment by warbunnies** [comment]
Seems I've been messing around too much. I got a new error:
```
arm-none-eabi-objcopy:.pioenvs\LPC1768\firmware.bin: Permission denied
*** [.pioenvs\LPC1768\firmware.bin] Error 1
```
thoughts?

**Comment by p3p** [comment]
something must have it open or didn't release the file properly, suggest a restart

**Comment by warbunnies** [comment]
Yep just needed a restart. It probably didn't release when I uploaded it to my email

**Comment by warbunnies** [comment]
This might help clear things up for me a little bit. 
I'm using a `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`

the pins_mks_sbase.h file only has:
```cpp
#if ENABLED(ULTRA_LCD)
  #define BEEPER_PIN       P1_31   // EXP1.1
  #define BTN_ENC          P1_30   // EXP1.2
  #define BTN_EN1          P3_26   // EXP2.5
  #define BTN_EN2          P3_25   // EXP2.3
  #define SD_DETECT_PIN    P2_13   // EXP2.7
  #define LCD_PINS_RS      P0_16   // EXP1.4
  #define LCD_SDSS         P0_28   // EXP2.4
  #define LCD_PINS_ENABLE  P0_18   // EXP1.3
  #define LCD_PINS_D4      P0_15   // EXP1.5
#endif // ULTRA_LCD
```
but the `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` is a DOGLCD 
So where are the pins for the Doglcd defined???

**Comment by p3p** [comment]
The Display/Controller defines are a bit of a maze but the `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` is defined as a `ULTIPANEL` that in turn defines it as an `ULTRA_LCD` .. I think, but anyway it does use those defines, and the global spi defines further down, I guess setting `SDSS` correctly didn't fix anything. Does your onboard card work?

**Comment by warbunnies** [comment]
The onboard card loads the firmware correctly so I assume that is fine.

**Comment by warbunnies** [comment]
Having done the compiling and testing at home. It is definitely defined as an ultra_lcd. But I have not been able to get the sd card working. Still at sd card inserted on main screen, then "no sd card" in menu. 

Next question is from the pins_mks_sbase.h, it says: 
 "A custom cable
 * is needed to pick up 5V for the EXP1 connection."
EXP1 provides 5v. Is that not enough amps or something? The screen is appears properly powered so I would assume it is fine.

**Comment by thinkyhead** [comment]
> The Display/Controller defines are a bit of a maze

To help navigate the maze…

![image](https://user-images.githubusercontent.com/698003/39166319-a3d9a2c4-474e-11e8-999c-974963b22fcb.png)

**Comment by warbunnies** [comment]
Thank you. What does the varying levels of green mean?

**Comment by warbunnies** [comment]
I have been digging around for any sorta answer. The smoothieware defines the spi speed as 500000. I was wondering how to set the spi speed. I've been digging around and found this:

```cpp
Marlin_speed[0] = 8333333; //(SCR:  2)  desired: 8,000,000  actual: 8,333,333  +4.2%  SPI_FULL_SPEED
Marlin_speed[1] = 4166667; //(SCR:  5)  desired: 4,000,000  actual: 4,166,667  +4.2%  SPI_HALF_SPEED
Marlin_speed[2] = 2083333; //(SCR: 11)  desired: 2,000,000  actual: 2,083,333  +4.2% SPI_QUARTER_SPEED
Marlin_speed[3] = 1000000; //(SCR: 24)  desired: 1,000,000  actual: 1,000,000         SPI_EIGHTH_SPEED
Marlin_speed[4] =  500000; //(SCR: 49)  desired:   500,000  actual:   500,000         SPI_SPEED_5
Marlin_speed[5] =  250000; //(SCR: 99)  desired:   250,000  actual:   250,000         SPI_SPEED_6
Marlin_speed[6] =  125000; //(SCR:199)  desired:   125,000  actual:   125,000         Default from HAL.h
```

which sounds like it is used when setting:
```cpp
/*
 * SD CARD: SPI SPEED
 *
 * Enable one of the following items for a slower SPI transfer speed.
 * This may be required to resolve "volume init" errors.
 */
//#define SPI_SPEED SPI_HALF_SPEED
//#define SPI_SPEED SPI_QUARTER_SPEED
```

in the config. so I tried SPI_SPEED_5
but while I was compiling I noticed that the firmware reset the SPI_SPEED twice before it finished compiling. Did it do anything to change the #define Spi_speed if the value gets changed twice? Could the spi speed be the problem?

**Comment by p3p** [comment]
With SPI speed can always be a problem, especially when used over wires instead of pcb traces and for more than ~10cm, (it wasn't designed for that), smoothieware doesn't officially support external sd cards for this reason.

That bit of code is in the HardwareSPI section and not in use, it's not possible at the moment because of the way the hardware is designed and what Marlin expects to share, that is why we define `LPC_SOFTWARE_SPI` in the pins file, setting SPI_SPEED in the config is correct and will slow down the SoftwareSPI implementation, This is the exact code my Re-ARM uses but configured to use different pins, at full speed and without any problems.

Sorry I'm not being much help on this I wish I could afford to buy the board to help you (and others) out, although MKS doesn't have the best reputation over at smothieware apparently.

**Comment by warbunnies** [comment]
Smoothie has its own reputation to worry about. 

Thank you for the info though! I'm gonna keep at it and I will post if I find a damn solution. Everything else works soo damn well. But i really cant have it connected to my computer for every print...

**Comment by Bob-the-Kuhn** [comment]
I just got in a MKS SBASE v1.3.  I hooked up the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER per the readme. The LCD's on board SD card worked immediately.

I'll need to think about this some more to see if I can reproduce the problem.

**Comment by warbunnies** [comment]
Hi bob, 
Man do i have questions. So the sbase has 4 pins on it that are for the sd card. Did you mess with those at all? are they flipped on or off? Also could you share every file you had to modify for the sd? I would really love to have something to compare to.

**Comment by Bob-the-Kuhn** [comment]
I just enabled the SDSUPPORT and the LCD in Configuration.h.

I did use toady's version of bugfix-2.0.x

How about zipping up your Configuration.h, Configuration_adv.h and your pins_MKS_SBASE.h files and attaching them to your reply.  That way I'll know for sure we're on the same page.

You could also post pictures of J8, EXP2, on the MKS and EXP2 on the LCD.

**Comment by thinkyhead** [comment]
> What does the varying levels of green mean?

The darkest shade is a first-order define, set directly for the associated LCD controller. The next lightest is set as a result of that, with the next lightest following from _that_… and so on…

**Comment by warbunnies** [comment]
[marlin-upload-github.zip](https://github.com/MarlinFirmware/Marlin/files/1953285/marlin-upload-github.zip)

Here are the files. I'll take pictures when I can. So you didn't mess with any of the switches of the sbase?

**Comment by Bob-the-Kuhn** [comment]
Your files work on my system if I either comment out **SD_DETECT_PIN** or I set it to the pin I'm using.

It didn't matter if your **SDSS** change was in or out.  The **SS_PIN** is what selects the SD card on the LCD.

**Comment by warbunnies** [comment]
![other_pins](https://user-images.githubusercontent.com/12589176/40590475-7670be78-61cd-11e8-90ec-45c2bccf7510.jpg)
![sbase_sdcard-enable_pins](https://user-images.githubusercontent.com/12589176/40590476-767f4920-61cd-11e8-8a19-3ff5e317e117.jpg)
![sd-detect_pin](https://user-images.githubusercontent.com/12589176/40590477-768d349a-61cd-11e8-85c4-5902b30fc2c3.jpg)
![sd-detect_pin2](https://user-images.githubusercontent.com/12589176/40590478-7699fb26-61cd-11e8-9ef6-d67bb2dc08fe.jpg)

Sorry Its been so long here is how I wired it. Let me know if I did something wrong. 
Edit: sorry havent uploaded anything. didnt realize it wouldnt list the file name. The bottom picture of the blue wire pin is the sd detect. the detect is working just fine. I'm curious what position your sd card enable pins on the sbase are set to.

**Comment by cdedwards** [comment]
I found that the MKS Sbase v1.3 board I have has a voltage of 4.7v instead of 5v. This caused issues with the REPRAP Graphics board not being bright enough. The trim pot underneath the display had to be adjusted for proper brightness.

**Comment by warbunnies** [comment]
Does that have anything to do with the SD card not working...?

**Comment by warbunnies** [comment]
I finally found a fix! I'm gonna have to cross test and see if it was one or both of the steps I did but I'll get back with that later today or tomorrow. 

1)moved the pins (miso,sck,mosi) to the 5th stepper motor breakout pins instead of the suggest pins cause it wasnt working. 
2)reformatted the sd card to fat32. 

The main difference between the pin switches was that the lcd would freeze when I put in the sd card. So i figured it was at least trying to read the card finally and stalling. So I reformatted the sd card and it is now printing like a charm. 

Also the sbase really needs more breakout pins... I love 32bit marlin but I might have to find a different 32 bit board.
(seriously the S-curve acceleration is awesome)

**Comment by thinkyhead** [comment]
It's possible the suggested SPI pins are in conflict with some other function. What does the `M43` (`PINS_DEBUGGING`) report say about those pins?

**Comment by warbunnies** [comment]
Omg i did not know M43 was a thing... darn it that would have been so much easier! >< Its a bit of a busy week for me but ill see if i can find some time to check.

**Comment by boelle** [comment]
@warbunnies 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
