### ISSUE TITLE
Compilation error with Bluetooth enabled for Teensylu - effect of logic mistake in Serial.h

### ISSUE THREAD

**Issue by gosewski** [MarlinFirmware/Marlin#10412]
There is a logic mistake in MarlinSerial.h and serial.h files that makes the enabled Bluetooth option prevents compilation throwing the error: 

"bluetoothSerial wasnot declared in this scope"

The reason is:

1) In MarlinSerial.h there is 
```
// Use the UART for Bluetooth in AT90USB configurations
#if defined(USBCON) && ENABLED(BLUETOOTH)
  extern HardwareSerial bluetoothSerial;
#endif
```
which is logically OK. This is the only `bluetoothSerial` definition in the whole Marlin code.

2) However, in serial.h we have:
```cpp
#ifdef USBCON
  #include <HardwareSerial.h>
  #if ENABLED(BLUETOOTH)
    #define MYSERIAL bluetoothSerial
  #else
    #define MYSERIAL Serial
  #endif // BLUETOOTH
#else
  #include "MarlinSerial.h"
  #define MYSERIAL customizedSerial
#endif
```
As we have USBCON defined for Teensylu, the `MarlinSerial.h` will be not included. This makes declaration of `extern HardwareSerial bluetoothSerial` missing in the compiling code. So, when it comes to line
```cpp
 #define MYSERIAL bluetoothSerial 
```
the error message is thrown as the bluetoothSerial was not declared indeed.

My simple Fix was to modify serial.h like this:

```cpp
#ifdef USBCON
  #include <HardwareSerial.h>
  #if ENABLED(BLUETOOTH)
    extern HardwareSerial bluetoothSerial;
    #define MYSERIAL bluetoothSerial
  #else
    #define MYSERIAL Serial
  #endif // BLUETOOTH
#else
  #include "MarlinSerial.h"
  #define MYSERIAL customizedSerial
#endif
```
Now I can compile Marlin with Bluetooth support for Teensylu and it works.

Cheers,
Greg

**Comment by thinkyhead** [comment]
Reported in #7110 and fixed in 42866db251a4016d123f063a1e6f434a8fb5266e
