### ISSUE TITLE
Marlin and THB6128 Driver

### ISSUE THREAD

**Issue by leseaw** [MarlinFirmware/Marlin#1041]
Hi,

i have an problem with this.
Moves are all fine.
in print, it puts the tracks in order 1-2mm direction Endstop.
Where is my mistake?
The driver to fast for marlin?
I print with 60mm/s.
Or is there a setting for it somewhere?

Thanks for an answer.

**Comment by Tommy-LSA** [comment]
It seems that the issue isn't a general issue of THB6128. I have tested the brand new RAPS128 (Pololu compatible THB6128) from here: http://max3dshop.org/index.php/default/elektronik/raps128.html?___SID=U This works perfectly without any changes in Marlin. X+Y 320 steps/mm on GT2 40teeth. So it seems that the optocoupler on the THB6128 Boards need an other timing or something like that. The RAPS128 hasn't couplers. If someone like to test this drivers - the ENA Pin have to be inverted in configuration.h for this Axis

See Video: https://www.youtube.com/watch?v=W7PykPQL2qs

**Comment by CONSULitAS** [comment]
@boelle @leseaw 

Could #1385 be the cause for this issue? You should try the proposed changings and test. What do you think?

**Comment by thinkyhead** [comment]
Post a new issue if this is persisting with the latest Development branch. Preparing for a code freeze, perhaps…

**Comment by thinkyhead** [comment]
@Wurstnase I'd be curious to see if #2033 makes any difference. If so we can call it a bug fix.

**Comment by tonnico** [comment]
On the Due the standard trapezoid_generator_reset() need ~2,5µs. The AVR should need much more time. So I think we get here at minimum 5µs delay for a DIR setup.
