### ISSUE TITLE
[1.1.8] Bug with Linear Advance

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#10425]
I use Y-Splitter for dual extruder with single nozzle.

I use the gcode script below to configure the filament change (E1 to E2 or E2 back to E1), in custom user commands:
```cpp
  #define USER_DESC_4 "Change to E2"
  #define USER_GCODE_4 "M203 E400\nG92 E0\nG91\nG1 E-3 F120\nG1 E-2.5 F60\nG1 E-120.5 F18000\nG92 E0\nG91\nT1\nG1 E+120.5 F18000\nG1 E+2.5 F60\nG1 E+3 F120\nM203 E25\nG92 E0\nG90"
  
  #define USER_DESC_5 "Change to E1"
  #define USER_GCODE_5 "M203 E400\nG92 E0\nG91\nG1 E-3 F120\nG1 E-2.5 F60\nG1 E-120.5 F18000\nG92 E0\nG91\nT0\nG1 E+120.5 F18000\nG1 E+2.5 F60\nG1 E+3 F120\nM203 E25\nG92 E0\nG90"
```
With linear advance disabled in Marlin, The extruder distance are ok (retract about 150mm of filament) but the exactly same script running after enable linear advance, make the retract distance about 15 or 20mm (!).

Its looks like  bug for me!

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by mtmello2003** [comment]
I did the test today, with the bugfix-2.0.x and the issue is completely vanish but I found another one, get involved the same extruder change scritpt: the extruder motor reverse is not working when changing the E1 to E2...

**Comment by mtmello2003** [comment]
please close this trhead, I will open another one. 

Just to make the things organized! :)

Linear advanced is okay right now
