### ISSUE TITLE
Errors when verify code with generic delta configuration files.

### ISSUE THREAD

**Issue by Nossolov** [MarlinFirmware/Marlin#10426]
Thank you for great job !
With 1.1.8 version, configuration.h & configuration_adv.h from Generic Delta example files.
I have many errors when i verify code 
```
pins.h : 294 EXTRUDEUR_0_AUTO_FAN_PIN was not declared in this scope.
sketch/pins.h : 452 : 5 note in expansion of macro '_H0_PINS'
sketch/marlin_main?cpp : 363 : 30 note in expansion of macro 'SENSITIVE_PINS'
sketch/marlin_main?cpp : In fonction 'void clamp_to_software_endstop(float*)'
Marlin_main.cpp : 7700 : error : 'min_software_endstops' was not declared in this scope
Marlin_main.cpp : 7705 : error : 'max_software_endstops' was not declared in this scope
'CONTROLLERFAN_PIN' was not declared in this scope
```
I try to do some changes in code, but i am not good enough to solve anything !
Thank you for your help.

**Comment by Nossolov** [comment]
Forget something  : board used is RAMPS_EFB
Adding line in pins_RAMPS.h after line 152 in IS_RAMPS_EFB section 
#define CONTROLLERFAN_PIN -1
One problem solved !

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by Nossolov** [comment]
Everything fine with bugfix 1.1.x
Not try 2.0.x but i will.
Thank you a lot.
I close !
