### ISSUE TITLE
[FR] Make DELTA_DIAGONAL_ROD_TRIM_TOWER adjustable variables

### ISSUE THREAD

**Issue by Zezoh** [MarlinFirmware/Marlin#10422]
Thank you for your great work, 

Is there a possibility to add  a way to change the diagonal rod length for each tower using LCD instead of doing it in Configuration.h file ( //#define DELTA_DIAGONAL_ROD_TRIM_TOWER { 0.0, 0.0, 0.0 })

Steps to Follow: 

1. Using G33 for Delta Auto-Calibration 
2. Print a testing model it could be a hexagon shape
3. Measure hexa model and adjust each rod separately with LCD. 

Regards,

**Comment by thinkyhead** [comment]
Enable `DELTA_CALIBRATION_MENU` and you'll find it at the bottom of the "Delta Calibration" menu.

**Comment by thinkyhead** [comment]
Actually, no. These values are not variable. We'll put it on the TODO list for Marlin 2.0.

CC: @LVD-AC

**Comment by Zezoh** [comment]
Thanks Scott,

**Comment by LVD-AC** [comment]
> Print a testing model it could be a hexagon shape
> Measure hexa model and adjust each rod separately with LCD.

Dimensional errors are most likely NOT caused by a wrong diagonal rod value. You better know what you're doing before messing with it. Just for this reason I'm not in favor to make DELTA_DIAGONAL_ROD_TRIM_TOWER changeable to easy (G-code, LCD).

**Comment by Zezoh** [comment]
Dear Luc, thank you for your feedback, can you please provide more details about the causes of   dimensional errors, 

I used this guide (https://www.thingiverse.com/thing:1274733 )

**Comment by LVD-AC** [comment]
Diagonal rod length is (should be) pretty accurately known; applying the rather large corrections required to compensate for dimensional errors is just making sure you get the rod length wrong.

**Comment by cjsoong** [comment]
@Zezoh You can try my modified version to meet your needs.
DELTA_DIAGONAL_ROD_TRIM_TOWER & DELTA_RADIUS_TRIM_TOWER  adjustable .
[Marlin-bugfix-2.0.x_20180417b.zip](https://github.com/MarlinFirmware/Marlin/files/1925981/Marlin-bugfix-2.0.x_20180417b.zip)

**Comment by Zezoh** [comment]
Thanks @cjsoong, I will give it a try

**Comment by boelle** [comment]
@Zezoh what was the result?

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by evandene** [comment]
> @Zezoh You can try my modified version to meet your needs.
> DELTA_DIAGONAL_ROD_TRIM_TOWER & DELTA_RADIUS_TRIM_TOWER adjustable .
> [Marlin-bugfix-2.0.x_20180417b.zip](https://github.com/MarlinFirmware/Marlin/files/1925981/Marlin-bugfix-2.0.x_20180417b.zip)

I was looking up your configuration file and I was wondering how you did set your EXTRUDER feedrate. I couldn't find any steps per unit set for the extruder(s)
Could you help please?
