### ISSUE TITLE
Bugfix-2.0.x Arduino IDE compile error

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#10433]
### Compile error using Arduino IDE 1.9.0-Beta

Library U8Glib installed.

### Steps to Reproduce

1. Download Marlin bugfix-2.0.x
2. Start Arduino IDE 1.9.0-Beta by double clicking Marlin.ino
3. Click verify button

**Expected behavior:**
Successful compilation
**Actual behavior:** 
```
In file included from C:\Users\jbwin\AppData\Local\Temp\arduino_build_484165\sketch\src\lcd\u8g_fontutf8.c:12:0:

C:\Users\jbwin\AppData\Local\Temp\arduino_build_484165\sketch\src\lcd\u8g_fontutf8.h:12:22: fatal error: clib/u8g.h: No such file or directory

 #include <clib/u8g.h>

                      ^

compilation terminated.
```

**Comment by teemuatlut** [comment]
Make sure you're using the latest commit as this was addressed very recently.
If it's still an issue after, please let us know.

**Comment by itmachinist** [comment]
Just downloaded and it is still giving this error.

**Comment by ghost** [comment]
@teemuatlut, I was using the latest commit. Downloaded the branch zip just before posting the issue.

**Comment by p3p** [comment]
#10441 should fix this issue

**Comment by ghost** [comment]
All good now. Thanks!
