### ISSUE TITLE
Need help with new TMC2130  - Same results with TMC2208

### ISSUE THREAD

**Issue by pmbroth** [MarlinFirmware/Marlin#10432]
Using the latest 1.1x  bugfix.

I have replaced my x and y axis  from (8825), I'm still keeping the 8825 on my z axis and extruders in 32 bit mode.  I put in the white generic tmc2130, in stand alone mode.  I have the MKS Gen 1.4 board.  I removed the 3 jumpers on the board under the driver.   Adjusted the voltages accordingly.

I have adjusted the steps in the firmware.  If I X home or Y home it works perfectly.  If I go to do a Z home, it will first go through x and y homing normal, and then when getting ready to do z homing, the extruder moved quickly across the x axis (max) , and then crashes at the end, where it will wait a second, and then try to level, I shut it off.

If I put my 8825 back and adjust the steps, put the jumpers back on, no issues.

I have attached my configs
[config.zip](https://github.com/MarlinFirmware/Marlin/files/1916236/config.zip)

Thank you in advance
Brian

**Comment by scottyedmonds** [comment]
Looking at your `Configuration_adv.h` it appears you haven't enabled TMC2130 on lines 1033 & 1035

`// CHOOSE YOUR MOTORS HERE, THIS IS MANDATORY
//#define X_IS_TMC2130 <- need to remove the //
//#define X2_IS_TMC2130
//#define Y_IS_TMC2130`

**Comment by pmbroth** [comment]
Hello

I thought you only do that if using the spi mode? Thank you.

Brian

**Comment by pmbroth** [comment]
I'm not using spi, so based on the comments in the marlin firmware, I do not have to uncomment out the x,y,z.  I'm just trying as dumb tmc213, like a tmc2100

**Comment by melvinisken** [comment]
I don't know if this applies, but: Are you sure that you configured the 2130 correctly? The datasheet says "To activate standalone mode, tie pin SPI_MODE to GND. SPI is off. The driver works in spreadCycle mode or stealthChop mode. With regard to the register set, the following settings are activated" (then followed by the settings tables). I don't know if this only applies to the original Watterott boards or the clones as well. So only setting the config pins is not enough, you need to enable the standalone mode additionally.

**Comment by pmbroth** [comment]
Hello

I appreciate the help.   I’m using an mks  gen 1.4 board. And I have tried it with the jumpers off and on, which are under the driver labeled ms1,ms2 and ms3, under  the driver.

What is strange is that x homing and y homing work perfectly. It is when I do a g28 or on my lcd do a all home or z home.    The x and y homing work perfectly.  When it gets to do the z home, the carriage goes fast to the end I the x axis slams it waits a sec, then  begins the z homing.  The steps are all set properly and for what I have read in standalone mode there is nothing else to do.
Thank you

Brian

**Comment by pmbroth** [comment]
I removed the 4 cfg pins from the drivers, as I found on YouTube video to do.  I tried with jumpers on and jumpers off.  X and Y home perfect.  When I try to do Z home, the x axis goes across the axis crashing into the end, and then the printer begins to do the z home. If I put my original drivers back, change the steps back in firmware, and flash all works perfectly.  I have no idea.    Any ideas?  I ordered new drivers 2208, to see if those work and I ordered tmc2100 as well.

**Comment by pmbroth** [comment]
I Just tried tmc2208 in stealthchope 2 mode the same exact problem. After x and y homes perfectly.  Z home will then the cause the extruder to go across at high speed the x axis, and slamming into the end, and then tried to home.  Help!!

**Comment by pmbroth** [comment]
I figured it out!!!!   The settings were not being stored in firmware for the steps.  I had to reset  the firmware - and it works!!!!

**Comment by swapsCAPS** [comment]
@pmbroth Do you mean you had to do an M502 first? 
That's the issue I'm currently facing. 
The 2208's are in msteps: 8 when the board initially gets power. 
After doing an M502 they go to their configured value.

**Comment by thinkyhead** [comment]
@swapsCAPS — Is that still the case if you follow `M502` with `M500`?

**Comment by swapsCAPS** [comment]
@thinkyhead Sorry for the late response was traveling. Yes it is still the case after. I think the issue is that I use an external PSU switch. When the drivers lose power they also lose their settings. Currently I have configured OctoPrint to send an `M502` before each print as a workaround. Definitely not ideal though. I believe the drivers are set to 8 msteps because `M1` and `M2` are not connected.

**Comment by thinkyhead** [comment]
An `M501` might also work, as it also calls `settings.postprocess`.
