### ISSUE TITLE
E0 doesn't work if dual Z axis is selected

### ISSUE THREAD

**Issue by Andycart** [MarlinFirmware/Marlin#10430]
Extruder E0 won't operate if dual z axis steppers function is selected.

If I connect my Z stepper motors in series and de-select dual z axis steppers in configuration_adv.h E0 works fine and the Z steppers operate correctly. If I select z axis dual steppers and plug one stepper into Z and one into E1 they both work fine but E0 no longer functions. 

My machine uses core XY kinematics

**Expected behavior:** E0 operates

**Actual behavior:** E0 doesn't operate
#### Additional Information
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1913991/Configuration.zip)

None

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by Andycart** [comment]
Downloaded and installed today's bugfix version and all seems good. Thank you.
