### ISSUE TITLE
[Question] Need help implementing probe retry

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#10444]
I am trying to implement code that runs a recover sequence after a failed probe. If G29 fails, I need it to execute the following sequence of GCODEs before the next attempt:

```
G28                       ; Home Axis
G0 Z5 F6000               ; Move to bottom of printer
G91                       ; Set relative motion mode
M211 S0		  	  ; Turn off soft endstops
M400                      ; Finish moves
M906 Z600                 ; Lower Z motor current
G0 Z-15 F500              ; Skip steppers against lower Z mounts
G90                       ; Return to absolute mode
M400                      ; Finish moves
M906 Z960                 ; Restore Z motor current
M211 S1			  ; Turn soft endstops back on
G28                       ; Rehome
M117 Leveling done.
G12 P0 S12 T0             ; Clean the nozzle
```

I've mostly gotten it to work by changing:

```
void process_parsed_command() {
       ...
        case 29: // G29 Detailed Z probe, probes the bed at 3 or more points,
                 // or provides access to the UBL System if enabled.
                 gcode_G29();
                 break;
         ...
```

With:

```
void process_parsed_command() {
       ...
        case 29: // G29 Detailed Z probe, probes the bed at 3 or more points,
                 // or provides access to the UBL System if enabled.
                 gcode_G29();
                 if(!planner.leveling_active) {
                     // If probe failed, level X axis, rewipe and repeat G29
                     enqueue_and_echo_commands_P(PSTR("G28\nG0 Z5 F6000\nG91\nM211 S0\nM400\nM906 Z600\nG0 Z-15 F500\nG90\nM400\nM906 Z960\nM211 S1\nG28\nM117 Leveling done.\nG12 P0 S12 T0\nG29"));
                 }
                 break;
         ...
```

The good news is that this actually works surprizingly well, the bad news is that it has a few odd glitches:

- The "ok" is issued immediately after the first probe failure, even thought the recovery and reprobe have not taken place yet. No "ok" is issued if the probe succeeds after one or more retry.
- If "G29" fails, one or two commands immediately after the "G29" may execute out-of-order before the recovery macro initiates.

Any ideas how to solve these two problems?

-- Marcio

**Comment by thinkyhead** [comment]
> The "ok" is issued immediately after the first probe failure, even thought the recovery and reprobe have not taken place yet. No "ok" is issued if the probe succeeds after one or more retry.

- "ok" is only sent for commands sent from the host that were queued. It isn't printed for commands placed in the queue by `enqueue_and_echo_commands_P`.
- "ok" just means a command sent by the host was queued, and it doesn't imply success.

> If "G29" fails, one or two commands immediately after the "G29" may execute out-of-order before the recovery macro initiates.

- Commands from all sources go into a single queue and are then executed later. There's no function as yet to throw away the commands in the queue in a host-compatible way. You would need to rewind `gcode_LastN` and then call `flush_and_request_resend` to tell the host that it needs to re-send the commands you threw away. You may need to add tracking to differentiate between commands in the queue that came from the host print job.

Anyway, the retry should really be done as C++ code from within the `G29` command rather than being done as G-code through the queue. Just wrap all the code within `G29` in a `do...while`. You can home using `home_all_axes` rather than queueing a `G28`.

**Comment by marcio-ao** [comment]
> Anyway, the retry should really be done as C++ code from within the G29 command rather than being done as G-code through the queue.

This is not really a good solution. There is no one-to-one correspondence between C++ code and GCODE and there is no decent documentation on the C++ functions (while there is great documentation of the GCODE in Marlinfw.org). Marlin really needs the ability to execute GCODE macro strings from PROGMEM. This would allow a lot of things which are currently implemented in C++ to be simple macros in "Configuration.h", i.e:

```
#define HOMING_SEQUENCE "G28\nG0 X10 Y10 Z10"
#define LEVELING_SEQUENCE "G0 Z5 F6000\nG91\nM211 S0\nM400\nM906 Z600\nG0 Z-15 F500\nG90\nM400\nM906 Z960\nM211 S1\nG28"
```

While I'm sure there are some challenges to implementing this (otherwise you probably would have done it already), I'm sure that in the long run it would allow for the elimination of a lot custom C++ code in Marlin and make it a lot more configurable by users that aren't programmers.

I understand you have a concern about memory, but I don't think this would take an ungodly amount of memory. The toughest thing would be to allow recursion (i.e. when during the processing of a macro another macro would be called), but this could be solved by having a small stack which contained a pointer to the currently executing macro as well as the character index within that macro. A hard limit could be set on the depth of nesting, to preserve buffer space. The implementation could look something like this:

```
const char* macro_stack[5];

void executeMacro(const char* macroStr) {
   // Push macro into the execution stack
   macro_stack[4] = macro_stack[3];
   macro_stack[3] = macro_stack[2];
   macro_stack[2] = macro_stack[1];
   macro_stack[1] = macro_stack[0];
   macro_stack[0] = macroStr;
}

// Check to see if there is a GCODE in the macro stack pending execution,
// if so, copy it to buffer
bool popMacroGCODE(char *buffer) {
  if(macro_stack[0] == NULL) {
    // Macro stack is empty
    return false;
  }

  // Get next macro
  next_delim = strchr_P(macro_stack[0], '\n');
  gcode_len = next_delim - macro_stack[0];
  strncpy_P(buffer, macro_stack[0], gcode_len);
  macro_stack[0] += gcode_len;
  // If at the end of the current macro, pop it from the stack
  if(*macro_stack[0] == '\0' ) {
    macro_stack[4] = NULL;
    macro_stack[3] = macro_stack[4];
    macro_stack[2] = macro_stack[3];
    macro_stack[1] = macro_stack[2];
    macro_stack[0] = macro_stack[1];
  }
}

void marlinCommandProcessingLoop() {
  while(1) {
     char gcode[255];
     if(popMacroGCODE(gcode)) {
        executeGCODE(gcode);
     } else {
        // Process command from SD card or USB
     }
  }
}
```

**Comment by marcio-ao** [comment]
I'm actually willing to implement this myself, even if it is on my own branch. But in order to do this, I sort of need to know what is the function in Marlin that actually takes a GCODE string and processes it? Basically, what is the equivalent of "executeGCODE(gcode)" above?

**Comment by marcio-ao** [comment]
I guess the difference is that `enqueue_and_echo_commands_P` puts the command into the queue. This means that commands will not be executed immediately.

However, it looks like the main driver for command execution in Marlin is:

```
void process_next_command() {
  char * const current_command = command_queue[cmd_queue_index_r];

  if (DEBUGGING(ECHO)) {
    SERIAL_ECHO_START();
    SERIAL_ECHOLN(current_command);
    #if ENABLED(M100_FREE_MEMORY_WATCHER)
      SERIAL_ECHOPAIR("slot:", cmd_queue_index_r);
      M100_dump_routine("   Command Queue:", (const char*)command_queue, (const char*)(command_queue + sizeof(command_queue)));
    #endif
  }

  // Parse the next command in the queue
  parser.parse(current_command);
  process_parsed_command();
}
```

So, could I perform immediate command execution simply by calling "parser.parse();" and "process_parsed_command();" in a loop?

**Comment by marcio-ao** [comment]
@thinkyhead : Deleting my previous suggestions since I found a much easier way to accomplish exactly what I needed. I created a PR, not necessarily because I want the code merged, but because I would like you to review and let me know if there are any problems with my implementation:

https://github.com/MarlinFirmware/Marlin/pull/10448

**Comment by marcio-ao** [comment]
Closing this issue since I already found a good way to implement this (it is now PR #10450)
