### ISSUE TITLE
[Bug report] 3-point or Linear delta erratic movement in curves.

### ISSUE THREAD

**Issue by GuillermoElectrico** [MarlinFirmware/Marlin#10449]
### Description

Erratic movement in curves and sawtooth when using 3 points or linear as autolevel in a delta.

Regardless of the figure, on any wall other than a straight the nozzle seems to jump, leaving a crest or zipper in the figure instead of leaving a continuous line. It does not occur if bilinear is used using the same gcode.

### Steps to Reproduce

I have tried it both in the current branch 1.1.8 and in the branch 1.1.x bugfix and marlin 2.0 bugfix:

1. Configure autolevel 3-point or Linear and load the firm
2. Print for example a 3DBenchy

-It will be seen as irregularities in the front part of the helmet and during the printing (regardless of the speed) when going through that area you will notice a movement in jumps.

3. Configure autolevel in bilinear and load the firm
4. Print the same gcode used before (the 3DBenchy from before)

 -It can be compared that the lines of the whole front part are smooth and during printing all movements are smooth.

In principle there should not be any difference between the pieces, printed using an autolevel or another, regardless of the first layer.

Tested on all branches with the same problem, regardless of the layer height or speed used.

If a completely flat bed is used (in my case a flat aluminum bed) with the 3-point or linear is more than enough to level the bed, being unnecessary any autolevel mesh (with the saving of time in measurement and possible problems that give the mesh).

In addition to another problem that I have, with 3-point the height of the nozzle is the same in the whole bed, with bilinear one side is higher than another, it is not well leveled. The side where the sensor is is lower than the side where the sensor can not measure. (but that is another matter).

#### Additional Information

To the left 3-point (also does the same with linear) to the right with Bilinear (Same gcode).
![wp_20180418_21_53_21_rich_li](https://user-images.githubusercontent.com/20523283/38955688-afefcd38-4355-11e8-9402-e6f3f2239be9.jpg)
![wp_20180418_21_53_29_rich_li](https://user-images.githubusercontent.com/20523283/38955689-b00f5e64-4355-11e8-9058-a52b76142788.jpg)

**Comment by thinkyhead** [comment]
Linear leveling is more computationally expensive than bilinear leveling, with 9 float multiplications for every segment.

Are the results any better if you reduce the speed of printing of the the number of `DELTA_SEGMENTS_PER_SECOND` (`M665 S`)?

**Comment by thinkyhead** [comment]
> with bilinear one side is higher than another, it is not well leveled

This usually indicates the sensor is changing its angle and not remaining perfectly perpendicular throughout the leveling process. This can be checked by taping a long skewer or straw to the probe, and observing its angle as the effector is moved around.

**Comment by GuillermoElectrico** [comment]
I'm going to try DELTA_SEGMENTS_PER_SECOND at 80 (now I'm using 100) and I'll tell you.

On the other topic, I will check and if that will change the sensor support (and location), to try.

If it's a computationally problem, then it's not a bug.

Thank you.

P.D. Not results, 80 it is still marked a lot, it is not a solution
