### ISSUE TITLE
[FR] Hotend offsets LCD menu

### ISSUE THREAD

**Issue by bruce356** [MarlinFirmware/Marlin#10451]
Mendel style Cartesian Dual-X Carriage printer, RUMBA board and RepRap Discount Full Graphic Smart Controller. CUSTOM_USER_MENUS is a brilliant idea (by Tannoo and others).

Hi, looking for help (not sure if anyone is interested, I am not a programmer) to create a GLCD menu item to view current offsets and to be able to change them for XYZ (M218 command) and then store updated to eeprom.

Currently I set these initially in configuration.h
```cpp
#define HOTEND_OFFSET_X {0.0, 291.2}
#define HOTEND_OFFSET_Y {0.0, -0.18}
#define HOTEND_OFFSET_Z {0.0, 0.08}
```
and then fine tune through a host program like Pronterface.
A computer is not always available and it would be great to be able to fine tune using a menu item on the GLCD.

example images from repetier:-
![img_20180414_111140](https://user-images.githubusercontent.com/209844/38963918-6a9ad6b6-43b3-11e8-9345-f8c1bb8aeaff.jpg)
![img_20180412_181312](https://user-images.githubusercontent.com/209844/38963922-6f9e34a0-43b3-11e8-9cef-7f917e8b7136.jpg)

Thanks and regards bruce

**Comment by thinkyhead** [comment]
Custom user menus can only be assigned a static G-code string.
What you're looking for requires writing code for a new menu.

**Comment by marcio-ao** [comment]
At the moment, I think hot end offsets are hard-coded into Marlin at compile time. For an upcoming project, we want to have run-time configurable hot-end offsets. So I second this request.

**Comment by thinkyhead** [comment]
> I think hot end offsets are hard-coded

They're not hardcoded, and can be changed at runtime by the `M218` command mentioned in the OP.

**Comment by InsanityAutomation** [comment]
@boelle @shitcreek this one is done too
