### ISSUE TITLE
[bugfix-2.0.x] EEPROM datasize error

### ISSUE THREAD

**Issue by thisiskeithb** [MarlinFirmware/Marlin#10458]
### Description

Flashing the latest bugfix-2.0 as of yesterday resulted in an "EEPROM datasize Error" and I can no longer connect to my printer using OctoPrint.

I successfully flashed my board several times before this error using the same build of Marlin. I believe this error cropped up after I enabled `#define LCD_SET_PROGRESS_MANUALLY`
in Configuration_adv.h.

I have an MKS Gen-L 1.0 with 4 TMC2100 drivers. 

See [attached .zip](https://github.com/MarlinFirmware/Marlin/files/1929315/marlin_bugfix20_datasize_error.zip) for my config files & log output from OctoPrint.

**Comment by thinkyhead** [comment]
> Flashing the latest bugfix-2.0 as of yesterday resulted in an "EEPROM datasize Error" and I can no longer connect to my printer using OctoPrint.

If it has an SD card slot, then make a G-code file containing:
```gcode
M502 ; default settings
M500 ; save settings
```
Save this file on SD and run it from the LCD controller. Maybe that will fix the EEPROM.

**Comment by thisiskeithb** [comment]
I ran the .gcode file and power cycled the board. OctoPrint still reports the same error.

**Comment by thinkyhead** [comment]
If you simply disable `EEPROM_SETTINGS` you're able to connect?

**Comment by thisiskeithb** [comment]
I couldn't connect using OctoPrint, so I used a Windows machine with Arduino IDE. I was able to revert back to Marlin 1.1.8 & OctoPrint was able to connect fine. I recompiled the same build of bugfix-2.0.x that I was working from with `#define LCD_SET_PROGRESS_MANUALLY` commented out and OctoPrint connects fine.

**Comment by thinkyhead** [comment]
Well, if you get a chance to flash `bugfix-1.1.x` with `EEPROM_SETTINGS` disabled, I'd be interested in the results.

**Comment by thisiskeithb** [comment]
I ported my 1.1.8 settings (including `LCD_SET PROGRESS_MANUALLY`) to the latest `bugfix-1.1.x` branch with `EEPROM_SETTINGS` disabled and OctoPrint didn't complain about datasize. Enabling `EEPROM_SETTINGS` works as well. Attached are my config files. 

[bugfix-1.1.x_config_files.zip](https://github.com/MarlinFirmware/Marlin/files/1930511/bugfix-1.1.x_config_files.zip)

**Comment by thinkyhead** [comment]
Interesting. And yet, `bugfix-2.0.x` is still acting up?

**Comment by thisiskeithb** [comment]
I spoke too soon. OctoPrint disconnected after my post flash GCODEs of M502 & M500 ran:

https://pastebin.com/VBZnjn9M

edit: Or maybe it's fine? OctoPrint appears to be extra cautious and disconnects when you run an M500 command and EEPROM is disabled.

**Comment by benlye** [comment]
OctoPrint will disconnect anytime it receives a string containing 'Error:'.  

You can disable this behaviour:
1. Go to **Settings -> Serial Connection**
1. Click on the **Behaviour** tab
1. Change the **What to do on a firmware error** option to one of the other options.

This won't fix the original problem with the datasize error, but it might help you keep debugging.

**Comment by zhenguwu** [comment]
I'm having the same issue with the latest Marlin 2.0 on Mks sbase v1.3. Stock dvr drivers, config is basically the stock config without much changed.

https://pastebin.com/sYN4tBz9

Also, external sd card is still not working on sbase. Looking at spi_pins.h, the SCK and MISO pins are set to P0_15 and P0_17, which do not exist on EXP1

**Comment by p3p** [comment]
>I'm having the same issue with the latest Marlin 2.0 on Mks sbase v1.3

@michaelwu21 if I remember correctly your issue is that the onboard sd-card is not working so you get eeprom data errors as Marlin cannot read the card, this is not related to any of the spi settings in Marlin. Most people seem to be able to get their onboard sd-cards working with the sbase if they format them, or change to another. This is something I want to investigate but I haven't found a card that doesn't work for me yet.

> Looking at spi_pins.h, the SCK and MISO pins are set to P0_15 and P0_17, which do not exist on EXP1

The pins specified in `spi_pins.h` file for the LPC176x platform are defaults (and correct for the primary hardware spi port used on the Re-ARM), they are overridden by the boards pins file, `pins_MKS_SBASE.h` in your case. This shows that you need to use J8 and software spi, also it states you need to make a custom cable for controllers and external sd-cards.

The one error I can see in `pins_MKS_SBASE.h`, `#define SDSS  P0_06` should be `#define SDSS  P0_28` I've already told you about in #10174, also it really should work with `SDSUPPORT` disabled in the config, but you confirmed that did not fix the issue. I'm afraid its hard to debug something without the specific hardware and when for most people with it it seems to work.

**Comment by thisiskeithb** [comment]
To answer your question, @thinkyhead: Yes. With @benlye's comment, you can tell OcoPrint to ignore errors, but that's probably not a good fix.

**Comment by zhenguwu** [comment]
Yeah I'm using ignore errors on octoprint which is how I got the terminal log(with the datasize error)

Still, I'd like to get eeprom to work- That was the main reason I updated to latest marlin, the older version I used simply would not do anything with the eeprom commands.

**Comment by thinkyhead** [comment]
I don't think OctoPrint should be disconnecting when it receives an error like "EEPROM disabled" in response to `M500`. Marlin has responded in just the same way for a long time. And this is hardly a fatal error. It just means `M500` cannot be used.

As for the "datasize" error, if it exists only in Marlin 2.0.x then we can compare the two bugfix branches and there ought to be some obvious discrepancy. The error indicates that the data written doesn't match the structure that we've defined to describe the data, and it's meant to catch a coding error. So, looking for that now……

**Comment by thinkyhead** [comment]
I don't see any obvious differences in comparing the two bugfix branches. So, here's something you can do to help track down the error. In `configuration_store.cpp` enable this option at the top of the file:
```cpp
#define DEBUG_EEPROM_READWRITE
```
Then when you boot the firmware and Marlin reads the EEPROM, it will report the first datafield where it finds a discrepancy between the expected offset and the actual offset. This will help narrow down the exact point where there's a mismatch.

**Comment by thisiskeithb** [comment]
Here's the output from OctoPrint after flashing bugfix-2.0.x with `DEBUG_EEPROM_READWRITE` enabled, as well as `EEPROM_SETTINGS` and `LCD_SET_PROGRESS_MANUALLY`

https://pastebin.com/GiywKXZB

For good measure, attached are the config files used:
[bugfix-2.0.x-DEBUG_EEPROM_READWRITE.zip](https://github.com/MarlinFirmware/Marlin/files/1934870/bugfix-2.0.x-DEBUG_EEPROM_READWRITE.zip)

**Comment by thinkyhead** [comment]
The logs show no errors. So I guess… congratulations…?

**Comment by zhenguwu** [comment]
Huh. I tried enabling #define DEBUG_EEPROM_READWRITE, and surprisingly the datasize error disappeared.

However, there is no eeprom.dat saved on the sd card.

I did notice the following from octoprint output:
```
Send: N2 M21*18
Recv: echo:SD init fail
Recv: ok
Send: N3 M117 Octopi Connected*86
Recv: echo:SD init fail
Recv: Error:Line Number is not Last Line Number+1, Last Line: 0
Recv: Resend: 1
```

**Comment by CaptCode** [comment]
not the best solution for this problem but at least the connection between the printer and octoprint is (and stays) established.

Octoprint:
Go to Settings -> Serial connections and select the Tab "Behaviour"
Under "Error handling" tick the box "Ignore".

Et voila!

Hope this helps...
