### ISSUE TITLE
bed heating error

### ISSUE THREAD

**Issue by deadmanArt** [MarlinFirmware/Marlin#10464]
hi guy/girls

I had a problem with my bed and heating it heats but only gets to like 43 max then error out. tried to turn off
```cpp
 //#define THERMAL_PROTECTION_BED
```
and
```cpp 
#if ENABLED(THERMAL_PROTECTION_BED)
  #define THERMAL_PROTECTION_BED_PERIOD 127    // Seconds
  #define THERMAL_PROTECTION_BED_HYSTERESIS 4 // Degrees Celsius
```
have done a 
[bed heating problem.zip](https://github.com/MarlinFirmware/Marlin/files/1932838/bed.heating.problem.zip)

Mega 2560 +RAMPS 1.4 Mosfit installed
![30772260_193488708042966_19050436_o](https://user-images.githubusercontent.com/38233402/39062909-538c0958-4508-11e8-867f-cc69503de052.jpg)
does the GND and/or the D8 need to be wired up?? or just the - Bed + 
 
https://www.ebay.com.au/itm/3D-Printer-Parts-Heating-Controller-MKS-MOSFET-for-Heatbed-Extruder-Module-TE717/232297350149?epid=18016023452&hash=item3616004405:g:THMAAOSw0RdaMOnu

**Comment by cdedwards** [comment]
1. Connect power supply to the "Power", please notice the anode and cathode.
2. Connect heatbed wire to the "Hotbed", please notice the anode and cathode.
3. Either:
    - Connect the direct digital control signal to Gnd, D8, or
    - Connect the control signal of Ramps1.4 or MKS MOSFET to -Bed+.
4. Please only choose one signal group to connect.

You can only use one of the # 3 options. You probably want gnd/d8 on a RAMPS board.

**Comment by boelle** [comment]
@deadmanArt 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
