### ISSUE TITLE
[bugfix-2.0.x] Fade height problem

### ISSUE THREAD

**Issue by letgo04** [MarlinFirmware/Marlin#10474]
I tried most recent verions around these days. now I tested with 17.04
platform RADDS with tmc2100.

1. Setting MBL then z-offset around -0.1 in LCD controller and saved 
2. Without setting fade height, MBL works well. no problem.
3. Set fade height to 2

**Expected behavior:**
 till 2mm z axis should move for compensation. 

**Actual behavior:**
yes. from 2mm, it doesn't move for compensation, but from first layer to 2mm layer whenever moving next layer, it looks like z jumping around 1mm or a bit more(1~3mm)(I couldn't measuer exact height) By the way in LCD controller, z height looks normal.
And during printing, when adjusting fade height from 2 to 0, in contrary z moved to nozzle as height as it jumped before(it is just my guess, when I see it as my observation)

there is no problem without fade height till now.

#### Additional Information

I have tried to debug this for around week. and what I found out is that

planner.h
```cpp
inline static float fade_scaling_factor_for_z(const float &rz) {
  static float z_fade_factor = 1.0;
  if (z_fade_height) {
    if (rz >= z_fade_height) return 0.0;
    if (last_fade_z != rz) {
      last_fade_z = rz;
      z_fade_factor = 1.0 - rz * inverse_z_fade_height;
    }
    return z_fade_factor;
  }
  return 1.0;
}
```
when I changed
```cpp
 z_fade_factor = 1.0 - rz * inverse_z_fade_height;
```
to
```cpp
 z_fade_factor = some const number like 0.5 
```
then there is no problem. it works as expected as I am.

*more information.
set fade height to 0.2 or less than 1,  z offset changes. it go far away from nozzle.
but without fade height or with above 1, it looks there is no z-offset problem.

**Comment by thinkyhead** [comment]
> - "from first layer to 2mm layer … z jumping around"
> - "without fade height or with above 1, it looks there is no z-offset problem."

So… I'm confused. Are you setting it to 2 and seeing problems at that value, or are you setting it to 0.2 and that's when it exhibits problems?

**Comment by letgo04** [comment]
problem exist whenever I set fade height.
I tested simply by using lcd controller..
tested fade height 1 and 10. 
1. reboot print
2. auto home
3. after finished auto home, turn on bed leveling in lcd menu
4.  set fade height
5.  when I use move_z(in lcd controller) till fade height,  I saw it moves actually 5mm(when fade height set 1 and I moved to 1mm) and 14mm(when fade height set 10 and I moved to 10mm)
6. over the fade height, it moves well.

**Comment by letgo04** [comment]
maybe I found why it happens.

first before talking about the problem.
I wanna check that I am right. when I begin printing or autohome, I could see z height around 8. and then became 0. this value 8 was made by MBL? right?(it is close the distance between nozzle and bed.)

if I were right.

when I was printing, my setting was
print layer height = 0.2
fade height = 2
z_offset = -0.75
and offset made by mbl around 8

in planner.h
```cpp
     inline static float fade_scaling_factor_for_z(const float &rz) {
        static float z_fade_factor = 1.0;
        if (z_fade_height) {
          if (rz >= z_fade_height) return 0.0;
          if (last_fade_z != rz) {
            last_fade_z = rz;
            z_fade_factor = 1.0 - rz * inverse_z_fade_height;
          }
          return z_fade_factor;
        }
        return 1.0;
      }
```
z fade factor is calculated like above.
let's substitude
z_fade_factor = 1.0 - rz * inverse_z_fade_height( rz = 0, 0.2, 0.4, 0.6 ... , inverse_z_fade_height = 1/2)
z_fade_factor = 1.0 - 0.2 * 1/2 = 0.9
at next layer : z_fade_factor = 1.0 - 0.4 * 1/2 = 0.8 and so on

in mesh_bed_leveling.h
```cpp
  static float get_z(const float &x0, const float &y0
    #if ENABLED(ENABLE_LEVELING_FADE_HEIGHT)
      , const float &factor
    #endif
  ) {
    const int8_t cx = cell_index_x(x0), cy = cell_index_y(y0);
    const float z1 = calc_z0(x0, index_to_xpos[cx], z_values[cx][cy], index_to_xpos[cx + 1], z_values[cx + 1][cy]),
                z2 = calc_z0(x0, index_to_xpos[cx], z_values[cx][cy + 1], index_to_xpos[cx + 1], z_values[cx + 1][cy + 1]),
                z0 = calc_z0(y0, index_to_ypos[cy], z1, index_to_ypos[cy + 1], z2);

    return z_offset + z0
      #if ENABLED(ENABLE_LEVELING_FADE_HEIGHT)
        * factor
      #endif
    ;
  }
```
it returns z_offset + z0 * factor

z_ offset : const value(in my case -0.75) and I will assume it is 0 for calculation below.
z0 is calculated by MBL data, so it is variable(maybe in my case around 8)

let's substitude
get_z = 8 *0.9 = 7.2
next get_z = 8 *0.8 = 6.4 
...

there is 0.8 height difference. and add print layer height 0.2. finally 1mm difference between layer.
That's why it looks like jumping. am I right??

If I were right, To solve it. I thought of that

find the  biggiest value(or middle) from MBL data, then add inverse  value to all of data. (ex. if the biggiest value is -8.27 add 8.27) and save this value for const offset of MBL. Then it would be

get_z = z_offset + offset of MBL + z0 * factor

**Comment by letgo04** [comment]
I test it as I wrote here. by using gcode G29. modifyed MBL data and also z offset.
it looks there is no jumping z.

**Comment by thinkyhead** [comment]
```cpp
get_z = 8 * 0.8 = 6.4
```
What makes you think that `z0` would ever be 8.0? The mesh values are supposed to center around 0 and typical values should all be from -0.5 to 0.5 (where 0.5 is extreme warping).

Please show us your mesh, with `M420 V`.

**Comment by letgo04** [comment]
```
SENT: M420 V
READ: Mesh Bed Level data:
READ: Num X,Y: 3,3
READ: Z offset: 0.00000
READ: Measured points:
READ:         0        1        2
READ:  0 -9.58750 -9.40000 -9.60000
READ:  1 -8.92499 -9.04999 -9.12499
READ:  2 -8.74999 -8.89999 -8.72499
```

**Comment by thinkyhead** [comment]
Hmm. You're doing something wrong there. The nozzle should be right at the bed when doing MBL mesh measurements, and the mean value should be 0. Let's do some logging!

- Download Marlin `bugfix-1.1.x` or `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed and enable leveling.
- Copy the log output into a **.TXT file** and attach it to your next reply.

**Comment by letgo04** [comment]
The nozzle should be right at the bed when doing mesh measurements?
even if physical distance is aroun 9mm?

and I have 300 * 300 mm size bed.

**Comment by thinkyhead** [comment]
Yes! When doing MBL measurement, the nozzle moves to each point in turn and then goes down to the bed. You put a piece of paper under the nozzle and adjust the nozzle up and down to the point where it just grabs the paper but you can still move it pretty easily. Then you click (or without an LCD, do `G29 S2`) to save the height value and move to the next point. Repeat until all points are saved.

**Comment by letgo04** [comment]
Yes. I understand how to use MBL. by the way, with this physical distance 9mm, how nozzle and bed can meet nearly 0 distance when beginning MBL??
this 9 mm is decided by mechanic endstop of z. maybe if I adjust height of z endstop upper 9mm, they could meet. but in my structure it is impossible to install endtop upper.

**Comment by thinkyhead** [comment]
> this 9 mm is decided by mechanic endstop of z

Are you saying that when you home Z to the minimum endstop, the nozzle stops at 9mm above the bed? Is this a Hall effect endstop that allows the nozzle to move farther down after it triggers?

**Comment by letgo04** [comment]
I modified source a bit.
after finishing MBL, I made average value of  MBL, then subtract it from each data of MBL.
finally set average value to z offset.

No problem now. Thanks.

**Comment by thinkyhead** [comment]
Ok, but it sounds like your configuration is quite messed up.

**Comment by boelle** [comment]
@letgo04 still having issue with latest bugfix 2.0?

if you dont have problems then maybe consider clicking the green close button below?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
