### ISSUE TITLE
[bugfix 2.0] G28.cpp, tweaks cause Z homing with G28 X/Y

### ISSUE THREAD

**Issue by paukstelis** [MarlinFirmware/Marlin#10476]
### Description

There is an issue here with the additions of Z_AFTER PROBING:

```cpp
   #if Z_HOME_DIR < 0
      if (home_all || homeZ) {
        #if ENABLED(Z_SAFE_HOMING)
          home_z_safely();
        #else
          HOMEAXIS(Z);
        #endif
      } // home_all || homeZ
      #if HOMING_Z_WITH_PROBE && Z_AFTER_PROBING
        move_z_after_probing();
      #endif
```

**Expected behavior:** [What you expect to happen]

No movement of Z when using G28 X/Y

**Actual behavior:** [What actually happens]
Z gets parked at the Z_AFTER_PROBING height

Moving the last "if" inside the curly braces should do the trick?

**Comment by thinkyhead** [comment]
Thanks! That's not just a good idea; it should be the law.
