### ISSUE TITLE
[2.0.x] Not reversing stepper motor (with LIN_ADVANCE)

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#10492]
Using:
```cpp
// A dual extruder that uses a single stepper motor
#define SWITCHING_EXTRUDER
#if ENABLED(SWITCHING_EXTRUDER)
#define SWITCHING_EXTRUDER_SERVO_NR 1
#define SWITCHING_EXTRUDER_SERVO_ANGLES { 145, 25 } // Angles for E0, E1[, E2, E3]
#if EXTRUDERS > 3
#define SWITCHING_EXTRUDER_E23_SERVO_NR 1
#endif
#endif
```
When I use the script to change between extruders:
```cpp
  #define USER_DESC_4 "Change to E2"
  #define USER_GCODE_4 "M203 E400\nG92 E0\nG91\nG1 E-3 F120\nG1 E-2.5 F60\nG1 E-120.5 F18000\nG92 E0\nG91\nT1\nG1 E+120.5 F18000\nG1 E+2.5 F60\nG1 E+3 F120\nM203 E25\nG92 E0\nG90"
  
  #define USER_DESC_5 "Change to E1"
  #define USER_GCODE_5 "M203 E400\nG92 E0\nG91\nG1 E-3 F120\nG1 E-2.5 F60\nG1 E-120.5 F18000\nG92 E0\nG91\nT0\nG1 E+120.5 F18000\nG1 E+2.5 F60\nG1 E+3 F120\nM203 E25\nG92 E0\nG90"
```
The stepper motor do not auto reverse in E2.

This issue do not happen in 1.1.x.

Thanks

**Comment by mtmello2003** [comment]
Hey, I got the trigger that start the issue: 

#define LIN_ADVANCE

If I disable the Linear advance, the issue do not occur and the stepper motor revert happen with success.

**Comment by Sebastianv650** [comment]
@mtmello2003 are you familliar with the switching extruder code? I did a quick search for SWITCHING_EXTRUDER in planner and stepper files without success. The question is, where is the reversement handled?

**Comment by mtmello2003** [comment]
I think I didn´t get the point you asking but if it helps: when I run the T1 gcode, the stepper motor is reverted and return back rotation with T0.

**Comment by Sebastianv650** [comment]
OK, the problem is (again, like for duplication mode) in the stepper control macros, found in:
- stepper_indirection.h
- stepper.cpp

My problem is I always end up confused when looking at these macros using macros using.. It's like standing between two mirrors, looking into infinity X-)
Try the follwing, in stepper.cpp, inside `void Stepper::advance_isr()` you will find an #if #endif block like this:

```cpp
    #if ENABLED(MK2_MULTIPLEXER) // For SNMM even-numbered steppers are reversed
      #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) E## INDEX ##_DIR_WRITE(e_steps < 0 ? !INVERT_E## INDEX ##_DIR ^ TEST(INDEX, 0) : INVERT_E## INDEX ##_DIR ^ TEST(INDEX, 0)); }while(0)
    #elif ENABLED(DUAL_X_CARRIAGE) || ENABLED(DUAL_NOZZLE_DUPLICATION_MODE)
      #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) { if (e_steps < 0) REV_E_DIR(); else NORM_E_DIR(); } }while(0)
    #else
      #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) E## INDEX ##_DIR_WRITE(e_steps < 0 ? INVERT_E## INDEX ##_DIR : !INVERT_E## INDEX ##_DIR); }while(0)
    #endif
```

Add a line (note the SWITCHING_EXTRUDER one) so it becomes:

```cpp
    #if ENABLED(MK2_MULTIPLEXER) // For SNMM even-numbered steppers are reversed
      #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) E## INDEX ##_DIR_WRITE(e_steps < 0 ? !INVERT_E## INDEX ##_DIR ^ TEST(INDEX, 0) : INVERT_E## INDEX ##_DIR ^ TEST(INDEX, 0)); }while(0)
    #elif ENABLED(DUAL_X_CARRIAGE) || ENABLED(DUAL_NOZZLE_DUPLICATION_MODE)
      #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) { if (e_steps < 0) REV_E_DIR(); else NORM_E_DIR(); } }while(0)
    #elif ENABLED(SWITCHING_EXTRUDER)
      #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) E## INDEX ##_DIR_WRITE(e_steps < 0 ? INVERT_E## INDEX ##_DIR ^ TEST(INDEX, 0) : !INVERT_E## INDEX ##_DIR ^ TEST(INDEX, 0)); }while(0)
    #else
      #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) E## INDEX ##_DIR_WRITE(e_steps < 0 ? INVERT_E## INDEX ##_DIR : !INVERT_E## INDEX ##_DIR); }while(0)
    #endif
```

If it works, I have to check what has to be done to support more than T0 and T1.

**Comment by mtmello2003** [comment]
I did the code changes in stepper.cpp but unfortunately didn´t work.

Same issue: with LA activated the extruder motor do not reverse. When I comment the tag //#define LIN_ADVANCE, works okay.

The code altered seems do not take effect in LA behavior.

**Comment by Sebastianv650** [comment]
That's realy strange as I just adopted the MK2_MULTIPLEXER define which I assume is working. @thinkyhead, any idea? Every second extruder needs direction reversement, so the only affected macro should be SET_E_STEP_DIR, which I tried?

**Comment by thinkyhead** [comment]
> any idea?

Try this instead:
```cpp
void Stepper::advance_isr() {

  #if ENABLED(MK2_MULTIPLEXER) // For SNMM even-numbered steppers are reversed
    #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) E0_DIR_WRITE(e_steps < 0 ? !INVERT_E## INDEX ##_DIR ^ TEST(INDEX, 0) : INVERT_E## INDEX ##_DIR ^ TEST(INDEX, 0)); }while(0)
  #elif ENABLED(DUAL_X_CARRIAGE) || ENABLED(DUAL_NOZZLE_DUPLICATION_MODE)
    #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) { if (e_steps < 0) REV_E_DIR(); else NORM_E_DIR(); } }while(0)
  #elif ENABLED(SWITCHING_EXTRUDER)
    #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) { switch (INDEX) { \
        case 0: case 1: E0_DIR_WRITE(!INVERT_E0_DIR ^ TEST(INDEX, 0) ^ (e_steps < 0)); break; \
        case 2: case 3: E1_DIR_WRITE(!INVERT_E1_DIR ^ TEST(INDEX, 0) ^ (e_steps < 0)); break; \
                case 4: E2_DIR_WRITE(!INVERT_E2_DIR ^ TEST(INDEX, 0) ^ (e_steps < 0)); \
    } } }while(0)
  #else
    #define SET_E_STEP_DIR(INDEX) do{ if (e_steps) E## INDEX ##_DIR_WRITE(e_steps < 0 ? INVERT_E## INDEX ##_DIR : !INVERT_E## INDEX ##_DIR); }while(0)
  #endif

  . . .
```

**Comment by mtmello2003** [comment]
I couldn´t compile the new code block on stepper.cpp.

I´ve got this error (only with the code block inserted. If I use original stepper.cpp, no problem to compile):

[compileError.txt](https://github.com/MarlinFirmware/Marlin/files/1997204/compileError.txt)


[stepper.cpp.notok.txt](https://github.com/MarlinFirmware/Marlin/files/1997202/stepper.cpp.notok.txt)
[stepper.cpp.ok.txt](https://github.com/MarlinFirmware/Marlin/files/1997203/stepper.cpp.ok.txt)

**Comment by thinkyhead** [comment]
Additional patches have been made to the bugfix branches, as both the direction and stepping behavior needed fixing, so please test again. Compile errors should also be fixed.

**Comment by mtmello2003** [comment]
I got the latest 2.0-bugfix today and could compile but with LA activated, no extruder stepper motor run. 

T0 move the servo to the defined angle, same with T1 but no moviment to the stepper motor.
