### ISSUE TITLE
Not able to control 3DTouch using Creality CR-10 Sample code

### ISSUE THREAD

**Issue by jluna0413** [MarlinFirmware/Marlin#10491]
### Description
 I have been struggling to get code to trigger anything on my 3D Touch sensors. They run a self test  when I connect printer to 5V, but when running gCode commands I get ie
```
SENDING:M280 S120 P
echo:SD init fail
```
or any other commands

**Comment by thinkyhead** [comment]
What version of Marlin are you using? Have you enabled the `BLTOUCH` option and set your probe offsets? Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as requested in the Issue template) and drop them into your next reply. We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
@jluna0413 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
