### ISSUE TITLE
[bugfix-2.0.x] Low Memory Warning.

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#10490]
Compiling it using Arduino Mega, I´ve got the warning:

Sketch uses 157284 bytes (61%) of program storage space. Maximum is 253952 bytes.
Global variables use 6442 bytes (78%) of dynamic memory, leaving 1750 bytes for local variables. Maximum is 8192 bytes.
Low memory available, stability problems may occur.

Is this a think that I need to pay attention or could run okay, even with low memory available?

**Comment by Bob-the-Kuhn** [comment]
Short answer is that it'll probably run reliably.

The M100 command can be used to check on memory usage.  You use it to fill the area between the variables and the stack and then go back after doing a print to see if the pattern is still there.  If there's more than 100-200 bytes of undisturbed pattern then chances are good that it'll be stable.

M100 is enabled in Configuration.h

```
 * This code watches the free memory block between the bottom of the heap and the top of the stack.
 * This memory block is initialized and watched via the M100 command.
 *
 * M100 I   Initializes the free memory block and prints vitals statistics about the area
 *
 * M100 F   Identifies how much of the free memory block remains free and unused. It also
 *          detects and reports any corruption within the free memory block that may have
 *          happened due to errant firmware.
```
