### ISSUE TITLE
[2.0.x]Re-Arm Compiler Error, if Emergency Parser enabled

### ISSUE THREAD

**Issue by kAdonis** [MarlinFirmware/Marlin#10499]
When trying to compile Bugfix 2.0x ( commit ad58b62) for LPC1768
PlatformIO throws an error:

![error](https://user-images.githubusercontent.com/35379348/39136942-a5eeb8f6-471c-11e8-9a58-76de57a8c3dd.JPG)
with Emergency_Parser commented, it compiles  fine.

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/1939092/configs.zip)

Thanks for this great firmware

**Comment by thinkyhead** [comment]
Currently `EMERGENCY_PARSER` isn't implemented for LPC1768.

**Comment by kAdonis** [comment]
Bad luck, thank you

**Comment by thinkyhead** [comment]
@kAdonis `EMERGENCY_PARSER` is now implemented for LPC1768. Cheers!

**Comment by kAdonis** [comment]
@thinkyhead 
You are so great!
That was tremendously fast.
Thank you

**Comment by thinkyhead** [comment]
You can chalk it all up to the speedy genius of @p3p!
