### ISSUE TITLE
bugfix-1.1.x compile error: 'current_temperature_chamber' was not declared in this scope.

### ISSUE THREAD

**Issue by StevenBruinen** [MarlinFirmware/Marlin#10505]
### Description

Compile error with April 24th 1.1.x bugfix build:
```
temperature.cpp: In static member function 'static void Temperature::checkExtruderAutoFans()':

temperature.cpp:562: error: 'current_temperature_chamber' was not declared in this scope

     if (current_temperature_chamber > EXTRUDER_AUTO_FAN_TEMPERATURE)
```
### Steps to Reproduce

Compile the April 24thl bugfix-1.1.x 

#### Additional Information

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1942496/Configuration.zip)

**Comment by StevenBruinen** [comment]
After looking in the code I see that "Temperature::current_temperature_chamber" only is available when HAS_TEMP_CHAMBER is enabled but the variable is also used in the HAS_AUTO_FAN code. 

#if HAS_TEMP_CHAMBER
  float Temperature::current_temperature_chamber = 0.0;
  int16_t Temperature::current_temperature_chamber_raw = 0;
  uint16_t Temperature::raw_temp_chamber_value = 0;
#endif

#if HAS_AUTO_FAN

[...]

  if (current_temperature_chamber > EXTRUDER_AUTO_FAN_TEMPERATURE)
    SBI(fanState, pgm_read_byte(&fanBit[5]));

**Comment by systemik** [comment]
I do have the same issue and don't understand how to fix it. Function declaration is not done because this define is not triggered : 
#define HAS_TEMP_CHAMBER (PIN_EXISTS(TEMP_CHAMBER) && TEMP_SENSOR_CHAMBER != 0 && TEMP_SENSOR_CHAMBER > -2) 
Which is normal is you don't have PIN defined.

I see this error only if I enable the FAN pin on the configuration_adv.h for #define E0_AUTO_FAN_PIN.

**Comment by StevenBruinen** [comment]
For now I've disabled the code in "temperature.cpp" in the HAS_AUTO_FAN section by addding // in front of them.

#if HAS_AUTO_FAN

[...]

// if (current_temperature_chamber > EXTRUDER_AUTO_FAN_TEMPERATURE)
// SBI(fanState, pgm_read_byte(&fanBit[5]));

**Comment by thinkyhead** [comment]
Thanks for the heads-up. Patched!
