### ISSUE TITLE
[FR] Support for Analog (IR) Z Probes

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#10513]
https://miscsolutions.wordpress.com/mini-height-sensor-board/

this probe can output analog values and if doing the probing slow enough there must be some benefit to it right?

> Automatic selection of a 4-level analog output for printer electronics that support it

**Comment by landodragon141** [comment]
The main benefit would be that you could set different feedrates for the values. That way it would slow down the z movement in steps as it gets closer to the bed.

**Comment by boelle** [comment]
my thought also

but given that its an analog value would the probing not be more precise also?

**Comment by comps** [comment]
> but given that its an analog value would the probing not be more precise also?

Not necessarily, the ADC'd value could be less precise than high-frequency checking for a digital state change.

If the sensor allows us to reliably correlate an analog value to a distance with sub-0.1mm precision, the biggest advantage would be skipping the whole "probe z distance" tuning step.

**Comment by thinkyhead** [comment]
I would recommend staying far away from IR probes. Our testing with (at MarkerArm) has shown them to be highly susceptible to variations in the color and texture of the surface, and that any variations in a surface will throw off their readings. The sensor linked above is described as working well with black paper under glass, but I can guarantee it would have a hard time with typical print surfaces, which are often rough, scuffed, and multi-colored.

**Comment by boelle** [comment]
well it was just an idea

it has worked well for me with the mk42 from orballoprinting.com

that one is matt black on its own and i have just put the supplied PEI on top of it

just dialing in my first layer height and after that i will do a first layer test for the whole bed, that is going to be a 250*210 square just 0.2mm high

**Comment by boelle** [comment]
on a cleanup cycle here and i have tested the ir priobe and yes its far from ideal

to many factors can be in play here, to much sunlight can false trigger.... if the bed is heated up or not... if its to shiny.... not correct color etc

and using an hall effect sensor i can only imagine it will require a lot to make it perfect

hmmm thinking of it... is that not what the bl touch does?

**Comment by landodragon141** [comment]
That's exactly what the bl touch does.

**Comment by boelle** [comment]
are there any way to have the bl touch to output the analog value from the halleffect?

or is it better to just probe very slow and use the digital output?

**Comment by AnHardt** [comment]
Even FSRs are analoge. (Force Sensing Resistor)

The number of readings of the sensor is critical.
With the 'old' endstop system we tested once per step - what is the highest achievable resolution. The max probing speed was 'z-jerk-speed'.
With the 'new' endstop system we are either using the interrupts, what has the same resolution, or we test about 1000 times a second (heater interrupt). Calculate yourself how slow you must probe to achieve the same resolution.
An analog sensor, tested in our usual ADC-loop (in the heater interrupt) is testing about 1000 / NR_ANALOG_SENSORS / 2 / 16 times a second. Where NR_ANALOG_SENSORS is thermistors + filament with sensors + probe + ... . Guess what that means for probing speed. Less than 20 steps per second.

**Comment by landodragon141** [comment]
Getting the "analog" signal from a bl touch is in practical terms impossible. This is because of the way the bl touch is designed. It contains a microprocessor that reads the hall effect sensor and emits a pulse to the arduino. The trick is the hall effect is triggered when the pin (which has a little magnet on the top) gets pushed close enough to the solenoid that it gets yanked up. This is highly repeatable assuming your environment is stable (no emp pulse guns, freeze rays, laser vision, etc.). This isn't at all like a hall effect based encoder which I believe is what you are thinking of when you are talking about analog.
