### ISSUE TITLE
Display Current Buffer on LCD

### ISSUE THREAD

**Issue by cfelicio** [MarlinFirmware/Marlin#10510]
Hi All,

I have been using Marlin and Repetier for a while, and with the new advance algo, I'm inclined to move all my printers to Marlin.

One of the features that I find quite interesting on Repetier is that they display the current buffer on the LCD. Is this something that Marlin can add in the future?

Thanks! :-)

**Comment by Roxy-3D** [comment]
Current buffer?  This doesn't make sense to me....

But if you spend $2.00 (including shipping!) on eBay you can buy an 8x8 LED display.     
https://www.ebay.com/itm/MAX7219-Dot-Matrix-8x8-Led-Display-Module-MCU-Control-For-Arduino-Innovation/222709799381?epid=1672606113&hash=item33da89d9d5:g:QmgAAOSwbw1aATcc

And in Configuration_adv.h,  you can enable the #define MAX7219_DEBUG setting.
The default example code watches the Head, Tail, and how full the serial buffers are with commands.

I have these displays on my development printers.  And I can tell you, most of the time, the serial buffers  have all slots full with commands waiting to be processed (performed).

**Comment by cfelicio** [comment]
cool, I will try that, thanks! :-)
