### ISSUE TITLE
Z Endstop Triggered on CNC Machine During Cuts

### ISSUE THREAD

**Issue by Mschindl301** [MarlinFirmware/Marlin#10528]
So I am using the Marlin Firmware in combination with a Ramps 1.4 board to run a modified Shapeoko 2 CNC machine. Everything is working fine, and it had made some very small successful cuts, but I have run into an issue. The Z endstop will get triggered during Z axis movements and it will kill that movement command, causing the drill to be higher than it should be. In the Pronterface menu, it will echo back that it hit the endstop, and will always do this at a random position. There is an X endstop and Y endstop on the machine but no Z endstop plugged in. I am using Marlin 1.1.6 right now.

I originally thought this was because nothing was plugged in to the Z Min port, and that the Arduino pin was floating. I tried to enable the pull-up command for the Arduino board but still no luck.

Is there a way to disable to the Z endstop from triggering all together?

**Comment by thinkyhead** [comment]
In `Conditionals_post.h` try this:
```diff
- #define HAS_Z_MIN (PIN_EXISTS(Z_MIN) && !IS_X2_ENDSTOP(Z,MIN) && !IS_Y2_ENDSTOP(Z,MIN) && !IS_Z2_OR_PROBE(Z,MIN))
- #define HAS_Z_MAX (PIN_EXISTS(Z_MAX) && !IS_X2_ENDSTOP(Z,MAX) && !IS_Y2_ENDSTOP(Z,MAX) && !IS_Z2_OR_PROBE(Z,MAX))
+ #define HAS_Z_MIN false
+ #define HAS_Z_MAX false
```

**Comment by Mschindl301** [comment]
This seems to have fixed this issue! Thank you!
