### ISSUE TITLE
[2.0.x] RAMPS FD V2.1 motor vibrate when machine starts up if EEPROM enabled

### ISSUE THREAD

**Issue by kevintong116** [MarlinFirmware/Marlin#10533]
I am now using RAMPS FD V2.1  with due
If I enable the EEPROM function, motor vibrate for a moment when the machine starts up/ being reset
This does not happen if EEPROM not enabled

What is the reason?

configuration.h is attached
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1951566/Marlin.zip)

**Comment by thinkyhead** [comment]
Hard to say. The EEPROM does some extra initialization based on stored values. Try `M502`, `M500` and see if it behaves better on the next reboot.

**Comment by kevintong116** [comment]
M502, M500 does not help

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands.

**Comment by boelle** [comment]
@kevintong116 did you test with the latest `bugfix-2.0.x` ?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
