### ISSUE TITLE
[bugfix-2.0.x] chamber sensor but no explanation

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#10536]
in the config i see

#define TEMP_SENSOR_CHAMBER 0 and #define CHAMBER_AUTO_FAN_PIN -1

does this mean we now can monitor or even control the chamber temp, or what is the purpose behind the 2 defines?

**Comment by GMagician** [comment]
Maybe this can give you some answer: #10045

**Comment by boelle** [comment]
@GMagician it does :-D thanks for that
