### ISSUE TITLE
[bugfix-2.0.x] load script makes printer reset

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#10545]
This short Gcode makes the printer reset

G90 ; absolute positioning
G92 E0 ; zero the extruded length
M109 S225 ; wait for extruder temp
G1 E100 F1800 ; load 100mm Fast
G1 E200 F1800 ; load 100mm Fast
G1 E300 F1800 ; load 100mm Fast
G1 E400 F1800 ; load 100mm Fast
G1 E500 F1800 ; load 100mm Fast
G1 E600 F1800 ; load 100mm Fast
G1 E700 F1800 ; load 100mm Fast
G1 E800 F1800 ; load 100mm Fast
G1 E900 F100 ; load 100mm Slow
M104 S0 ; extruder off
M84 ; disable motors

i use it to load filament from octoprint

**Comment by Bob-the-Kuhn** [comment]
No error messages?

Please zip & post the log.

**Comment by boelle** [comment]
Nope no log


Den fre. 27. apr. 2018 17.37 skrev Bob-the-Kuhn <notifications@github.com>:

**Comment by boelle** [comment]
Same thing happens if I heat the extruder manual and send G1 E100 F1800

Den fre. 27. apr. 2018 17.37 skrev Bob-the-Kuhn <notifications@github.com>:

**Comment by Bob-the-Kuhn** [comment]
Yes, no log if printing from the SD card.

Do you have both the LCD & host connected?  

I thought we had prints being done for every source of resets.

**Comment by boelle** [comment]
only LCD and octoprint

Prints? this is just a script to heat up and unload the filament... no printing is being done

that is what is strange to me, i use ocotprint to heat up the nozzle to 225 and then i send G1 E100 F1800 from the terminal... the printer resets

and there is no error in the terminal

**Comment by boelle** [comment]
so just sending these 2 lines from the terminal in octoprint is enough to make it reset

M109 S225
G1 E100 F1800

last one is send when temp is at 225

**Comment by thinkyhead** [comment]
Your E micro-steps of 32x is the problem, as we discussed.
Reduce them or go slower on E and the board will not reset.

**Comment by boelle** [comment]
at least i did set the ramps to 16x microstep and of course halfed the steps pr mm

same thing happened so now i will change the script to use half feedrate ie F1800 will be F900

EDIT: that did the trick.... now the questions is if it worked with 32 microstep and F900 would the higher microstep make for better prints in general?

**Comment by thinkyhead** [comment]
> would the higher microstep make for better prints in general?

No. An extruder should be totally fine with 8x or even 4x micro-stepping.
