### ISSUE TITLE
[FR] Received commands that aren't enabled due to a compile-time option should reply with something like "FEATURE NOT ENABLED"

### ISSUE THREAD

**Issue by Zer0t3ch** [MarlinFirmware/Marlin#10546]
Even something as simple as "Not allowed" as a generic error message when receiving any command that wasn't enabled at compile-time would be wonderful. Just spend 15 minutes tearing my hair out because G26 wasn't doing anything and wasn't providing any output other than "OK". (Which I believe happens after any batch of serial communications, but still)

I could be wrong in my assumption, but I believe this is the standard result when attempting to run any command that isn't compiled in, even commands that don't exist anywhere. (Just tested `G99999`) Would it be possible to put some kind of "stub" into all the commands that exist but aren't enabled for some reason or another that outputs something like "FEATURE NOT ENABLED" and possibly even output "UNKNOWN COMMAND" for any received commands that don't exist? I understand there's an attempt to stay lightweight with what we use PROGMEM for, but this should be a relatively small change if implemented correctly, and it could even be disabled with a configuration option for people who need to skim every last byte of PROGMEM for stuff they don't care about.

**Comment by GMagician** [comment]
I'll take a look at it but I think that new features will be only included in 2.0 version

**Comment by GMagician** [comment]
@Zer0t3ch it seems that there are some host software compatibility issues adding this feature, read #10555, Marlin developpers are waiting an answer from host developpers.

**Comment by Zer0t3ch** [comment]
Is it outputting the errors _instead_ of the OK that's causing issues? I kinda went down that link chain, but I don't see anyone clarifying what problems were arising for other devs.

**Comment by GMagician** [comment]
@Zer0t3ch you can read all here: #10554

**Comment by boelle** [comment]
@Zer0t3ch 

still having issues?

**Comment by boelle** [comment]
missing label

**Comment by InsanityAutomation** [comment]
This is done and should be closed.
