### ISSUE TITLE
[2.0.x] MKS SBASE disable MULTIPLE_PROBING did not work

### ISSUE THREAD

**Issue by haudamekki** [MarlinFirmware/Marlin#10551]
I'm using a Precision Piezo for probing my Z axis and want to disable MULTIPLE_PROBING by outcommenting it, but it did not work. After making the change and sending a G28 the Probe did  just the same, first a fast and then a slow probe. Also changin Z_PROBE_SPEED_SLOW to the same value as Z_PROBE_SPEED_FAST has no effect.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1956494/Configuration.zip)

**Comment by Bob-the-Kuhn** [comment]
Try setting it to 1 rather than commenting it out.

**Comment by thinkyhead** [comment]
```cpp
#if MULTIPLE_PROBING && MULTIPLE_PROBING < 2
  #error "MULTIPLE_PROBING must be >= 2."
#endif
```

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by haudamekki** [comment]
I have tried it with the latest bugfix-2.0.x branch and have the same Problem.
Can't disable MULTIPLE_PROBING.
Can't change the speed for Z_PROBE_SPEED_SLOW
Can't set MULTIPLE_PROBING to 1 as mentioned above by thinkyhead

**Comment by thinkyhead** [comment]
Please follow this procedure to gather more information:

- Disable `MULTIPLE_PROBING` so that only a single probe will be done.
- Enable `DEBUG_LEVELING_FEATURE` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed.
- Copy the log output into a **.TXT file** and attach it to your next reply.

**Comment by haudamekki** [comment]
I have disabled MULTIPLE_PROBING and enabled DEBUG_LEVELING_FEATURE.
Performing a G28 the Printer does a fast and a slow probe.
Performing a G29 the Printer does only one probe per Point.

[debug.txt](https://github.com/MarlinFirmware/Marlin/files/1957817/debug.txt)

**Comment by haudamekki** [comment]
Sorry it was my own Fault...
It's not probing, it's Z_HOME_BUMP settings I'm searching for.
Can I disable the home bump for Z?

**Comment by haudamekki** [comment]
I have found it
Setting Z_CLEARANCE_BETWEEN_PROBES in Configuration.h and Z_HOME_BUMP_MM in Configuration_adv.h both to 0 disables the second bump

**Comment by thinkyhead** [comment]
Yes, but it may also affect your `G29`. I've just added a patch to the bugfix branches so you can just set `Z_HOME_BUMP_MM` to 0 and it will only affect `G28`.

**Comment by haudamekki** [comment]
THX works perfect
