### ISSUE TITLE
[FR] Support for MKS Mini Panel

### ISSUE THREAD

**Issue by bipsendk** [MarlinFirmware/Marlin#10562]
### Description

Support of MKS MiniPanel in Marlin

#### Additional Information

A new type for Display is probably needed - MKS_MINIPANEL

Information about configuration changes in standard/repository code is located at http://reprap.org/wiki/MKS_MINI_12864

Having this display type supported directly in the code will make it easier to migrate configuration from an existing Marlin version to a newer one when relevant.

**Comment by kAdonis** [comment]
It Is already supported in bugfix1.1x
look at Configuration.h line 1726
```
//
// MKS MINI12864 with graphic controller and SD support
// http://reprap.org/wiki/MKS_MINI_12864
//
//#define MKS_MINI_12864
```
