### ISSUE TITLE
LED_CONTROL_MENU bug 1.1x/2.0x

### ISSUE THREAD

**Issue by cdedwards** [MarlinFirmware/Marlin#10569]
LED_CONTROL_MENU in configuation_adv.h needs to be sanity checked. If this is enabled without NEO_PIXEL, then make will fail due to missing functions.

if ENABLED(NEO_PIXEL) && ENABLED(LED_CONTROL_MENU)
in configuration_adv.h would suffice. or get really fancy and add the logic to sanitycheck.h

**Comment by thinkyhead** [comment]
Don't forget `BLINKM`, `RGB_LED`, `RGBW_LED`, and `PCA9632` are also supported.
