### ISSUE TITLE
[FR] Option for minimum LCD support

### ISSUE THREAD

**Issue by Looxoor** [MarlinFirmware/Marlin#10578]
### Description

Since I have a board with very constrained program memory (Anet) and solely control the printer via Octoprint, I would like to be able to strip the firmware of all menus, essentially just use the LCD to show the normal status screen.
In my current config I'm using 98% of the available memory and there are several features I'd like to enable (without purchasing a new board).

I'd like an option in e.g. configuration_adv.h:

```
// Disables all menus and use LCD for status screen only.
// This is useful if you need to free up program memory 
// and only use an external controller for your printer
#define LCD_STATUS_ONLY
```
I believe this would benefit more people than me.
Although I understand that this might be too much work if I'm a minority with these wishes.

**Comment by MasterPIC** [comment]
Did you define SLIM_LCD_MENUS (in configuration_adv.h)?

**Comment by Looxoor** [comment]
To be honest, I just saw that option and that inspired me to open this issue.
I haven't yet compiled with that on (which I will the next time).
The thing is that, at least the way I interpreted the comments, it only affects seldom used menu items, which I thought maybe changed only a few percentage points of free memory.

At least how I imagine it, stripping the entire menu object and everything related to it would make a more substantial impact.

I may very well be wrong.

**Comment by MasterPIC** [comment]
I also own an Anet A8 (managed by Octoprint, with many info shown by the display, Led case and ABL) and I think you'll be impressed by the memory freed by the slim menu. Anyway you can also opt for disabling SD support thanks to Octoprint.

**Comment by Looxoor** [comment]
All right, I'll definitely try that and see if I can enable G26, linear advance and advanced pause.
Thanks!

Just curious though, did my idea at least make a little sense?

**Comment by MasterPIC** [comment]
Surely some memory is still used for LCD, also with SLIM_LCD_MENUS defined...
I don't remember if I've mesh validation enabled: I simply make a G29 calibration with ABL before each print.
What I know is that I wasn't able to switch from ABL to UBL because of memory. But I don't think that disabling SD and LCD support would solve this limitation.

P.s. I'm using Linear advance (1.5) and advanced pause too (required to be able to change filament while a print is in progress).

**Comment by Looxoor** [comment]
Yeah, I think maybe not the individual menu items as much as the menu logic itself, i.e. The button actions and such would make the biggest impact to get rid of. Just off the top of my head.

Oh, I have ABL with bilinear grid as well, I'd just like a simple way to test the entire bed since I can't probe all the way to the front in my case.

Ah, I'm still on mainline 1.1.8, is the bug fix branch stable enough to use full time? Reading about the differences I have opted out of even trying linear advance 1.0, waiting and hoping for 1.1.9 stable to come soon. Maybe I should just take the plunge then?

When I couldn't fit advanced pause I took the octoprint path of M0 instead of M600 for filament change procedure and it actually works flawlessly. I'd just prefer a native solution.

**Comment by Looxoor** [comment]
Wow, that was fast, thanks @thinkyhead!

**Comment by thinkyhead** [comment]
I wanted to see how much work it would take. Turns out, not that much!

**Comment by Looxoor** [comment]
Tried to compile it (downloaded the latest bugfix an hour ago) with the "NO_LCD_MENUS" option for the first time today and got two errors during compilation:

First, in "G26_Mesh_Validation_Tool.cpp":
```
'is_lcd_clicked' was not declared in this scope
```

I commented out the G26 option in configuration.h and tried to compile again,
then the next compile time error occured:

This time in temperature.cpp
```
'ADC_KEYPAD_PIN' was not declared in this scope
```

So I had to comment out no lcd menus for now and use slim lcd menus instead.

Hope this helps.

**Comment by thinkyhead** [comment]
@Looxoor — These errors should be cleared up now.

**Comment by Transvistinator** [comment]
Hate to re-open an old issue, but getting the same error plus a bunch more when enabling NO_LCD_MENUS.

Slim menus works, but Isn't freeing up enough :/

https://pastebin.com/QKBL09N9
