### ISSUE TITLE
RADDS Extension Board

### ISSUE THREAD

**Issue by porcinus** [MarlinFirmware/Marlin#10572]
Hello,
First of all, thanks for your great job, Marlin work better than ever so a huge thanks to devs and contributors ;)

My current problem don't come from Marlin itself but from the way RADDS extension board has been design.
For any who want to use it to driver more than 3 extruders, the VDD pin of the drivers are powered by a Due pin and not with onboard 3.3v (look strange to me but why not...) so you need to set pin 25 to OUTPUT and HIGH.

Is there any legit way via configuration files to set it the way it need to be or the only current way is to edit Marlin.ccp by adding into "void setup()" :
```cpp
pinMode(25, OUTPUT);
digitalWrite(25, HIGH);
```
PS: sorry for my english, not my main language :/
Thanks

**Comment by Bob-the-Kuhn** [comment]
If I read the RADDS schematic correctly, Vdd is attached directly to 3.3V.

If you have a newer schematic please post it.

[RADDS_26_sch.pdf](https://github.com/MarlinFirmware/Marlin/files/1959213/RADDS_26_sch.pdf)

**Comment by porcinus** [comment]
The schema you send is only the main board, not extension.

Extension one:
![image](https://user-images.githubusercontent.com/698003/39413705-0545cc00-4bf4-11e8-936d-151b9e1adf83.png)

D25 is VDD for E4 and E5
D69 is for E6

E3, E4 and E5 on Marlin FW

**Comment by porcinus** [comment]
As said before, I don't know why it has been done that way since it's done the right way on the main board.
I am pretty sure it can generate some overheat on the mcu (RADDS main board fully hide Due motherboard as most other shield)

**Comment by Bob-the-Kuhn** [comment]
I think it's time to clip a couple of pins on the right angle header and jumper in the 3.3V.

**Comment by porcinus** [comment]
When you buy the extension board, header is already solder. So need to desolder the header pin from the main board.
In my case, I have on main+extension board about 9 steppers, 3 thermistors, 1 servo, LCD+SD and all needed endstop connected so I am not going to put out of the printer the main board, the only way for me is to modify extension board by making a jumper wire from endstop header.

Can directly input 3.3v to a pin with no assignation be a problem?

**Comment by Bob-the-Kuhn** [comment]
You should isolate the DUE I/O pins or risk burning them up.

**Comment by porcinus** [comment]
I think about trying to make a interface board between main and extension board with a ams1117-3.3 to take power from 5v input to VDD and MSi pin, it will be a little bit more noisy but I don't think that will cause any trouble to run drivers.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
