### ISSUE TITLE
Does this work for all AVR processors? 

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#10597]
Should we make some GPIO macro's and change things?

http://www.instructables.com/id/Arduino-is-Slow-and-how-to-fix-it/

**Comment by p3p** [comment]
That is what fastio.h is, direct port manipulation, Marlin uses Arduino methods very rarely.

**Comment by Roxy-3D** [comment]
OK...   So this is really just a different implementation of FastIO.  Right?   Why can't we use this to do get rid of the Arduino methods that still exist?   (I'm just trying to understand !)

And digitalWrite()'s are fast, right?

**Comment by p3p** [comment]
> And digitalWrite()'s are fast, right?

No digitalWrite is hopelessly slow, no problem if your just turning something on or off every now and then but you should never generate a signal with it, digitalWrite is about 5us to toggle, direct port manipulation (with a compile time known pin) about 125ns

I should clarify that I'm not saying digitalWrite is badly implemented, it does what its supposed to, make changing a pin robust and generic. Doing so just requires a fair bit more error checking than generally is needed when we know what we're doing.

**Comment by thinkyhead** [comment]
The only place where we still use `digitalWrite` or `digitalRead` is when the pin number is in a variable, so can't be handled by the pre-compiler. For all cases where we know what the pin number will be ahead of time, we use the fastio `WRITE` / `READ` macros.

**Comment by Roxy-3D** [comment]
OK!!!   That helps!   I was noticing that an older copy of Max7219_Debug_LEDs.cpp used the digitalWrite() function.   But the current version is using WRITE().   

Thanks everybody!
