### ISSUE TITLE
[PROBLEM] Printer halted TMC2130

### ISSUE THREAD

**Issue by Blaster1920** [MarlinFirmware/Marlin#10593]
Hi guys,
I've just finished to configure my delta into the standard configuration that comes with the latest bugfix (1.1).
I have a mks gen 1.4 board with bltouch active and working.
I already remapped pinramps in order to use the external sd and bltouch with tmc2130 (chinese, v1.1).
I've activated sensorless mode and left just the bltouch in the proper xmin connector. All the endstop connections aboard the TCM 2130s has been wired to the endstops pins.
When I try to home only the X works and even if I don't do anything, after xx seconds repetier shows:
```
21:05:00.382 : Y driver error detected:
21:05:00.382 : X	Y	Z	E0
21:05:00.382 : Enabled		false	false	false	false
21:05:00.382 : Set current	800	800	800	800
21:05:00.382 : RMS current	1436	1436	795	795
21:05:00.382 : MAX current	2025	2025	1121	1121
21:05:00.382 : Run current	25/31	25/31	25/31	25/31
21:05:00.382 : Hold current	12/31	12/31	12/31	12/31
21:05:00.382 : CS actual		0/31	0/31	12/31	12/31
21:05:00.382 : PWM scale	0	0	48	10
21:05:00.382 : vsense		0=.325	0=.325	1=.18	1=.18
21:05:00.382 : stealthChop	false	false	true	true
21:05:00.382 : msteps		256	256	16	16
21:05:00.382 : tstep		0	0	1048575	1048575
21:05:00.382 : pwm
21:05:00.382 : threshold		79	79	79	263
21:05:00.382 : [mm/s]		1601.27	1601.27	100.08	30.06
21:05:00.382 : OT prewarn	false	false	false	false
21:05:00.382 : OT prewarn has
21:05:00.382 : been triggered	false	false	false	false
21:05:00.382 : off time		0	0	5	5
21:05:00.382 : blank time	16	16	24	24
21:05:00.382 : hysteresis
21:05:00.382 : -end		-3	-3	2	2
21:05:00.382 : -start		1	1	3	3
21:05:00.382 : Stallguard thrs	5	5	5	0
21:05:00.382 : DRVSTATUS	X	Y	Z	E0
21:05:00.382 : stallguard
21:05:00.382 : sg_result		0	0	0	0
21:05:00.382 : fsactive
21:05:00.382 : stst		X	X	X	X
21:05:00.382 : olb
21:05:00.382 : ola
21:05:00.382 : s2gb
21:05:00.383 : s2ga
21:05:00.383 : otpw
21:05:00.383 : ot
21:05:00.383 : Driver registers:	X = 0x80:00:00:00
21:05:00.383 : Y = 0x80:00:00:00
21:05:00.383 : Z = 0x80:0C:00:00
21:05:00.383 : E0 = 0x80:0C:00:00
21:05:00.392 : Error:Printer halted. kill() called!
```
Is it a bug or I did something wrong?

**Comment by teemuatlut** [comment]
Please clean up your issue formatting.

The printer is halted if a response contains an active error bit. This can be because of a faulty connection and thus a faulty SPI response or as is intended, because the driver has encountered an error.
If you feel like this is a false positive, you can disable `STOP_ON_ERROR`. This feature was added so that Marlin can abort a print and save both time and material in case a driver has shut down in order to protect itself.

**Comment by Blaster1920** [comment]
How could I clear out the problem? Expecially in case of a faulty SPI response.

**Comment by teemuatlut** [comment]
You can try running my [TMC debugging branch](https://github.com/teemuatlut/Marlin/tree/TMC_debugging_v2) that has a better way of handling the errors. Especially to tell what was the original cause for it.

**Comment by lokus77** [comment]
Have you tried reset eeprom settings?
I had lots of problems changing from 2 to 5 TMC2130. 
My M122 was OK, but moving any  Z or E0 axis, system halted on 2-3 seconds.
Then i readed "try clear eeprom". M502+ M500, and problems solved!

**Comment by mephistchan** [comment]
> Have you tried reset eeprom settings?
> I had lots of problems changing from 2 to 5 TMC2130.
> My M122 was OK, but moving any Z or E0 axis, system halted on 2-3 seconds.
> Then i readed "try clear eeprom". M502+ M500, and problems solved!

You are genius, M502+M500 sloved the problem
