### ISSUE TITLE
[bugfix-1.1.x] Linear Advance 1.5 is extremely loud

### ISSUE THREAD

**Issue by Lyr3x** [MarlinFirmware/Marlin#10596]
I tested Lin. Adv. 1.5 for a few weeks now and it was working fine and the results of the prints were awesome. Today i turned Lin. Adv. off due to another problem. 
I just realised that the printer was incredibly loud with Lin. Adv. K=0.6. I mean it was damn loud compared to K=0 (stealthChop).

Is this normal? Should it be so loud?

**Comment by thinkyhead** [comment]
Duplicate of #10272
