### ISSUE TITLE
[2.0] FR PanelDue Integration

### ISSUE THREAD

**Issue by bwgeez02** [MarlinFirmware/Marlin#10609]
I have been chatting with dc42 about getting PanelDue support in Marlin. I'm no programmer/coder, so I'll just copy/paste his response. 

"PanelDue talks GCode over a serial interface. So the only thing you would need to do in Marlin to support is is to support the GCodes it uses, which are the ones with [JSON responses](http://reprap.org/wiki/G-code#M408:_Report_JSON-style_response). Specifically, M408 S0 and S1, M20 S2, and M36. You don't need to support all the M408 response fields because PanelDue will use whatever it finds."

"PanelDue already adjusts the GCodes it sends and what it displays when the host announces that it is Smoothieware or Repetier in the M408 response, to avoid using or displaying features not supported by those firmwares. We could do the same for Marlin if necessary."

"If you are serious about adding this support to Marlin, I can make a PanelDue display controller board available."

Thanks!

**Comment by thinkyhead** [comment]
Seems like an interesting controller!

I've added preliminary PanelDue support at the linked [pull request](https://github.com/MarlinFirmware/Marlin/pull/10610) without the SD file listing and printing parts. If anyone wants to test the feature, simply connect the panel to an enabled serial port and enable `PANELDUE` in `Configuration.h`. Direct download of the branch is [here](https://github.com/thinkyhead/Marlin/archive/bf2_paneldue_json_M408.zip).

> If you are serious about adding this support to Marlin, I can make a PanelDue display controller board available.

We'd love to have a unit to test and to refine the feature.

---
- `M20` still needs work to add the `P` parameter for selecting a folder and for printing long filenames. The existing implementation just prints the whole directory with full DOS 8.3 paths.
- `M36` still needs to be implemented. The `M27 C` command is similar, so part of that code can be re-used.

**Comment by bwgeez02** [comment]
@thinkyhead , where do you want me to send a controller?

**Comment by thinkyhead** [comment]
Hi @bwgeez02 — I look forward to being able to test the code with the actual device! Please use the mailing address shown on this page: http://www.thinkyhead.com/support

**Comment by bwgeez02** [comment]
Ordered one for me and one for you. USPS 2-3 day shipping. Can't wait! Thanks for all the contributions you and everyone else makes to the open source community!

**Comment by thinkyhead** [comment]
Thanks! I look forward to spiffing it up. Our controller integration is pretty lacking right now.

**Comment by thinkyhead** [comment]
Closing this, as it is now superseded by #10610.
