### ISSUE TITLE
Q: Is stepper.synchronize needed in G92?

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#10611]
According to reports the typical `G92 E0` that slicers add before each layer leads to visible seams in the print due to the pause introduced by `planner.synchronize` at the start of `G92`.

The synchronize is included to ensure that the current planner/stepper positions aren't changed prematurely, while there are still moves in the planner, and it's pretty important —especially with XYZ positions— to make sure that the stepper/planner counts don't get out of phase. They need to be trustworthy for forward kinematics.

The E position is less important, since it isn't used for any form of forward kinematics (to restore the logical position based on the steppers). So it should be perfectly safe to skip `stepper.synchronize` when only updating the E axis. However, if E is changed at the moment that `G92` is executed, it messes with planner blocks that are already queued. When `planner.buffer_steps` is called (assuming E is sent to this method in absolute coordinates) it depends on the current planner E position being based on the previously-executed block to know how far to move E.

So, the long and short of this is, we could drop the `stepper.synchronize` for changes in E only if the E coordinate sent to all planner move functions is guaranteed to be relative-only, so that there's no dependency on the E position in the planner. Then the E value tracked by the planner can be purely arbitrary.

So, it makes sense to convert all E moves to relative before sending them to the planner.

CC: @MarlinFirmware/general-maintainers @MarlinFirmware/32bit-maintainers

---
To eliminate the need to `stepper.synchronize` in response to `G92 E`, I've started converting the planner/stepper to do only relative E moves. So far it's looking good, in that it reduces the amount of code in planner and stepper.

I've also added a small `planner.buffer_e_move` method that buffers an e-only move, useful in a few places.

The tedious part is locating all calls that expect the E value to be absolute. The number of calls is only in the dozens, so I should have something ready for testing within a day or so.

**Comment by GMagician** [comment]
Assumption: I may not know exactly how marlin is working at so low level hence I can write inappropriate thing.

I think that things will be easier acting like some industrial CNC works, using linked queues.
Tools change and G92 can store values as offset to current machine coordinates. When someone uses G92 or T then new offset are stored. When positions are required then proper offsets are added and then values are stored in planner. Using this approach only offset are changed when command are issued and planner doesn't care since it has only to execute its queued commands.

**Comment by thinkyhead** [comment]
A question has come up about lost steps due to rounding down to the nearest step. Assuming an extruder has a typical 500 steps per mm, each lost step amounts to only 2 millimeters per meter of filament, or 0.2%. This is pretty negligible, but if it's very concerning, some steps can be made up by always adding 1/2 step before rounding, so there will be an equal number of rounding errors in the opposite direction on average.

**Comment by thinkyhead** [comment]
Simplicity in the planner/stepper classes ends up being complexity in some of the high level code. So, I'm taking another approach. Some notes:

- The E position is ok to sync with the planner position with `G92` since it's ahead of the next G1-G5 move and its planner blocks, and it's ok to set E with the stepper class at any point also. The E position in the stepper class is pretty negligible, as it is never back-propagated to the planner or the logical position. (And if it is, well, that could be removed without any major harm.)
- Change of the XYZ position (in `G92`, for example) _does_ have to wait for a stepper.`synchronize` before it can be set, but only because it would alter the stepper count positions in the middle of active stepping, and those need to keep their integrity for forward kinematics. The planner positions are totally fine to write from the high-level code, because they are synchronous.

Given the latter point, there actually is a way to eliminate `stepper.synchronize` from `G92` and any other commands that might want to rewrite the stepper counts. The key would be to set a flag in the planner (`sync_next_block`) which would cause the planner to set a `sync_position` flag in the next block it creates, along with the XYZE count values that should be set in the stepper class. The stepper ISR would just check this flag when grabbing a new block. If the flag is set it will copy the given position to its counters.

That will allow for any number of `G92` to be inserted in-between moves, and there would never be any pausing.

So I'm going to set aside the relative-E work I've been doing and revisit it later. It will be much simpler to add this flag and special code than to chase down every move to the planner and convert E to a relative value.
