### ISSUE TITLE
Use E1 Port for Z2

### ISSUE THREAD

**Issue by WillShawx** [MarlinFirmware/Marlin#10612]
### Description

Hi, i am using a MKS Gen V1.4 On a Reprap printer with dual Z Motors.

Is it possible for me to use the spare E1 Port to drive the second Z Motor by making some firmware modifications or do i have to use an adaptor like this (https://www.ebay.co.uk/itm/Stepper-motor-adapter-to-put-2-stepper-motors-in-series-not-parallel-z-axis-3D/282873720059?hash=item41dc966cfb:g:-NEAAOSwhcNadNCl)

**Comment by thinkyhead** [comment]
If you simply enable `Z_DUAL_STEPPER_DRIVERS` the first unused E plug will be automatically assigned to Z2.

**Comment by WillShawx** [comment]
So how does the board differentiate between the extruder motor and the Z Motor? do i have to boot it up without Z2 Plugged in first? or is it simply plug and play once i upload the new sketch? 

thanks

**Comment by thinkyhead** [comment]
Plug and play. The stepper driver at the position with "E1" silkscreened on the board becomes your Z2 stepper driver.

**Comment by WillShawx** [comment]
Thanks! Much Appreciated
