### ISSUE TITLE
DRV8825's

### ISSUE THREAD

**Issue by WillShawx** [MarlinFirmware/Marlin#10617]
### Description

When i attempt to use DRV8825's on Marlin 1.1.8, the motors vibrate and don't spin. However, using the exact same drivers on Repetier Firmware, i get no issues at all.

**Comment by Nossolov** [comment]
I change A4988 by DRV8825 on a Ramps board with Marlin 1.1.8. No problem but need to adjust current.

**Comment by WillShawx** [comment]
I’m using MKS GEN 1.4

**Comment by p3p** [comment]
Marlin 1.1.8 defaults to `#define MINIMUM_STEPPER_PULSE 0` in `Configuration_adv.h` (this was changed in bugfix) DRV8825's require that you change it to `#define MINIMUM_STEPPER_PULSE 2`, you didn't supply configs as the issue template requested so I can only assume you haven't.

**Comment by thinkyhead** [comment]
> DRV8825's require that you change it to `#define MINIMUM_STEPPER_PULSE 2`

It may not matter on AVR, but it can't hurt.

**Comment by boelle** [comment]
@WillShawx 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
