### ISSUE TITLE
[Marlin 1.1.x] Anet A8 ovresize compilation with autobed leveling

### ISSUE THREAD

**Issue by kerosix** [MarlinFirmware/Marlin#10628]
Hi everybody,

I've just received a capactive sensor et I put it in my anet a8 (original motherboard).
I 've setup the configuration.h file by foloowing videos & tutos.

When I compile, I have the message : 
_Le croquis utilise 127184 octets (100%) de l'espace de stockage de programmes. Le maximum est de 126976 octets.
Les variables globales utilisent 4369 octets de mémoire dynamique.
Croquis trop gros ; vois http://www.arduino.cc/en/Guide/Troubleshooting#size pour des conseils de réduction.
Erreur de compilation pour la carte Anet V1.0_

How can I solve this issue by keeping the auto bed leveling activated ?

Thanks a lot

**Comment by BastR** [comment]
You need to disable some features to save space.

Trying to deactivate:

-linear advance
-nozzle park feature
-advanced pause feature
-disable_M503
-eeprom_chitchat

You can also base yourself on a  firmware that I modified : https://docs.google.com/spreadsheets/d/1HHkxEB_dc4mfbdVfpQMmQvy1ZBBg6NkmXGtIvfU21MU/edit#gid=0

Et accessoirement rejoindre notre communauté facebook autour de l'Anet pour plus d'aide: https://www.facebook.com/groups/anet3d/

**Comment by boelle** [comment]
@kerosix 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
