### ISSUE TITLE
[BUG] [2.0.x] [TMC2130] Compiling fails with TMC2130 + SD_Support enabled

### ISSUE THREAD

**Issue by dw-0** [MarlinFirmware/Marlin#10625]
Used with:
`MOTHERBOARD BOARD_RAMPS4DUE_EFB`

Enable `#define SDSUPPORT` and `#define HAVE_TMC2130` results in an compiling-error:
```
In file included from sketch\src\HAL\HAL_DUE\../../inc/MarlinConfig.h:36:0,

                 from sketch\src\HAL\HAL_DUE\DebugMonitor_Due.cpp:25:

sketch\src\HAL\HAL_DUE\../../inc/../HAL/HAL_DUE/SanityCheck.h:50:6: error: #error "DUE software SPI is required but is incompatible with TMC2130 hardware SPI. Enable TMC_USE_SW_SPI to fix."

     #error "DUE software SPI is required but is incompatible with TMC2130 hardware SPI. Enable TMC_USE_SW_SPI to fix."

      ^

exit status 1
Fehler beim Kompilieren für das Board Arduino Due (Programming Port).
```
 So the error-message basically tells me, i should enable software-SPI and not use hardware-SPI.
But i want to use hardware-SPI. So this is not quite a solution which is valid for me.
I could disable SD-Support but again, that is no real valid option since i want to print from SD-Card.

Is it not possible that SD and TMC2130 use the same hardware-SPI pins on a due?
On a Mega2560 is works just fine.

Config files:
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/1976494/configs.zip)

**Comment by Ludy87** [comment]
buy you be a new board - MKS :-)
Why try your not SPI_HW?

**Comment by dw-0** [comment]
I guess i don't quite understand your "solution". You can write it in german if you want.
I won't buy new hardware because of this if that's what you were saying.

> Why try your not SPI_HW?

I don't know what you mean.

**Comment by Ludy87** [comment]
Okay, ausnahmsweise - gibt eigentlich mecker.

Das sollte SPI_SW heißen, du kannst doch die gleichen Pins verwenden. Sie müssen nur die gleiche Pinbelegung entsprechen.

Du aktivierst die SPI_SW und nennst die Pinbelegung wie sie original für SPI sind.

-----
Google-Transplantation

That should be called SPI_SW, you can use the same pins. You just have to match the same pinout.

You activate the SPI_SW and name the pin assignments as they are original for SPI.

**Comment by Bob-the-Kuhn** [comment]
Here's an excerpt from the sanity check file.  It has some info on why the error was generated.

Basically the DUE's hardware SPI does not allow control of the shared pins with a software SPI.  

```cpp
/**
 * HARDWARE VS. SOFTWARE SPI COMPATIBILITY
 *
 * DUE selects hardware vs. software SPI depending on whether one of the hardware-controllable SDSS pins is in use.
 *
 * The hardware SPI controller doesn't allow software SPIs to control any shared pins.
 *
 * When DUE software SPI is used then Trinamic drivers must use the TMC softSPI.
 *
 * When DUE hardware SPI is used then a Trinamic driver can use either its hardware SPI or, if there are no shared
 * pins, its software SPI.
 *
 * Usually the hardware SPI pins are only available to the LCD. This makes the DUE hard SPI used at the same time
 * as the TMC2130 soft SPI the most common setup.
 */
```

**Comment by dw-0** [comment]
Well, i tried quite a bit the last days to get it running, without success.
Im not sure if the issue i am having right now is based on faulty SPI settings or whatsoever.

I activated softSPI for the TMC and set the pins to the exact same pins hwSPI uses. (D50, D51, D52).
For testing purposes i set the CS pin for the x-driver to D65 and connected the SPI as usual.

Compiling works fine, no error message, but an instant driver error on bootup which said overtemperature of x-driver / short coil A to ground / short coil B to ground.

A `M122` shows me a `Driver registers: X = 0xFF : FF : FF : FF` so it seems like the driver doesn't get recognized by the firmware?

What is the issue here? Any clue?

~~My next step will be, to switch to a different driver, but i am pretty sure that its not broken or fried.~~
EDIT: Switched the driver, issue still occurs, so the driver itself isn't the problem.

**Comment by Bob-the-Kuhn** [comment]
You need to use different pins.  The hardware & software SPIs don't play nicely with each other.  They must be separated.

**Comment by dw-0** [comment]
Interesting... yes it actually worked now with setting the softSPI pins to D4, D5 and D6 for testing purposes.
I was happy that there was no driver error after booting and the firmware actually recognized my x-driver correctly.
Then i installed a TMC2130 for y as well, and set the CS pin for it to D66.
BOOM... driver error.
Changing the CS pin for y from D66 to D44 solved the problem.

I am still wondering why D66 seems to "break" stuff in my case?

For now it seems that things will work... i didn't connected my motors yet but i am pretty confident that they will run.

**Comment by Bob-the-Kuhn** [comment]
Do a **M43 I** and see if any functions are tied to D66.

M43 is enabled by PINS_DEBUGGING in Configuration_adv.h

**Comment by dw-0** [comment]
M43 I output is as follows:
`PIN: 66    MAX6675_SS    Input=1`

Googling gave me the result, that the max6675 is a thermocouple, but i don't use one of this kind.
A quick lookup in the `pins_RAMPS.h` for pin 66 gave me the following result:
```
Line 139:     #define TMC_SW_MOSI    66
Line 188:   #define E0_SERIAL_RX_PIN   66
Line 206: // SPI for Max6675 or Max31855 Thermocouple
Line 208:   #define MAX6675_SS       66   // Do not use pin 53 if there is even the remote possibility of using Display/SD card
Line 208:   #define MAX6675_SS       66   // Do not use pin 53 if there is even the remote possibility of using Display/SD card
Line 210:   #define MAX6675_SS       66   // Do not use pin 49 as this is tied to the switch inside the SD card socket to detect if there is an SD card present
Line 210:   #define MAX6675_SS       66   // Do not use pin 49 as this is tied to the switch inside the SD card socket to detect if there is an SD card present
Line 353:     #define LCD_PINS_D5         66
Line 527:       #define DOGLCD_CS         66
```

I guess one is just not allowed to use D66 as a CS pin for TMC driver since it interferes somehow with those definitions?

**Comment by Bob-the-Kuhn** [comment]
Comment out that line and see what happens.

What might be happening is the TMCV code is setting that pin as an output but later the thermal software sets it to an input.

**Comment by dw-0** [comment]
I commented out the section of the MAX6675_SS and a new M43 gave me as result:
`PIN: 66  <unused/unknow>  Input=1`

Setting the CS Pin for Y to Pin D66 still gave me an Driver Error and the firmware doesn't recognize the driver. So something still is interfering with the usage of D66 as a CS pin for a TMC Driver.
I don't know what it is, but its fine for me, i can just use another pin and it works.
If you want me to make further test because you see it as a problem which should get fixed, so tell me and i try to help. :)

**Comment by thinkyhead** [comment]
> `PIN: 66 <unused/unknown> Input=1`

That's odd. If `Y_CS_PIN` is set to 66 then it _**should**_ show up in the pins debug output as such:

```
PIN: 66 Y_CS_PIN Input=0
```

Do you see `Y_CS_PIN` in the pins debug output anywhere else?
For example, the default is 49, so if it's not changed it should show up as:

```
PIN:49 Y_CS_PIN Input=0
```

Try this change in `Configuration_adv.h` and see what the pins debug output says:
```diff
  #define Y_IS_TMC2130
+ #define Y_CS_PIN 66
```

**Comment by dw-0** [comment]
@thinkyhead Sorry for this super late response, but i had to tackle some other issues with my printer and then stick to the simple workaround of just assigning another pin.

Some general information:
The commit i currently use is the following: `b7a8dcc`

But now, that i changed my electronics again a bit, i want to update this bugreport again.

I changed from a normal Ramps 1.4 to a Ramps 1.6+ on an Arduino Due.
The "special thing" on the Ramps 1.6+ is the "hardwired-spi". That means the `MOSI`, `MISO`, `SCK` and `CS` Pins of each TMC2130 driver don't need to be wired with jumper cables anymore. Those connections are already integrated in one layer of the PCB.

So far so good, nothing special actually, but....

Since there is/was no documentation about what pins each one of the CS-pins is assigned to, i checked by myself:
![ramps1.6+_cs-pin_definitions](http://puu.sh/CBab0/b08e8c4897.jpg)

As you can see, the Ramps 1.6+ PCB "wires" the `CS_E1` to `D66`.
And that leads to the update of this bugreport.
I still was not able to get `D66` sucessfully defined as the `CS_E1` pin in Marlin. I did the same like i mentioned already in one of my comments before and commented out the `MAX6675_SS` to make sure `D66` is not used by any function anymore at all. But that does not fix the problem. The E1 driver will still throw an error if i send a `M122` for a TMC debug log. So i just assume the same thing @Bob-the-Kuhn suspects, that the pin isn't assigned to anything, but the firmware somehow is still not able to completely "let loose" from this pin from its former definition.

I was able to (like before) define `D44` for `CS_E1` and just jumper the `D66` to `D44`.
Flashed firmware again -> all drivers are detected.
Rechecked to confirm, defined `D66` for `CS_E1`, flashed firmware -> tmc connection error
Switched back to `D44` -> works fine again.

And @thinkyhead , to answer your questions, when i define the CS pins, i don't see them anywhere else. I also made sure to look up the whole `configuration.h`, `configuration_adv.h` and `pins_RAMPS.h` for any other uses of `D66` and commented them out, still no success in using it.

So, maybe you might want to look into it if you have the time for it. Since it is no criticial bug which breaks things, the priority might be pretty low anyways. And for now it is pretty easy with the workaround of simply jumper `D66` to `D44`.

**Comment by boelle** [comment]
@th33xitus so this is still a problem?

**Comment by dw-0** [comment]
@boelle i am still on commit `b7a8dcc` and with this commit it's a clear: yes.
I can test it out again later today with the newest commit. Did you guys changed some stuff to the code so it should be fixed? I then will report back asap after i flashed the newest bugfix.

**Comment by boelle** [comment]
bugfix 2.0 is the thing to use these days, it changes a lot and bugs are constant being fixed

**Comment by dw-0** [comment]
don't get me wrong. i use the bugfix 2.0 for "ages" now.
so the `b7a8dcc` commit is a bugfix 2.0 commit as well, from december 2018. (21'st dec 2018 to be precise).

i will flash the newest bugfix 2.0 commit today and report back :)

**Comment by boelle** [comment]
:-D always use latest commit

**Comment by dw-0** [comment]
Flashed bugfix 2.0 commit `a43e892`.
I can confirm that the problem is **NOT** resolved yet.

The firmware will compile fine with D66 defined as any CS_PIN, but the corresponding TMC-driver won't work after flashing.

**Comment by boelle** [comment]
@th33xitus does it stil fail to compile?

**Comment by dw-0** [comment]
I have to check again to be honest.
Since i found out how to work around that issue (with the D44 to D66 jumper) i still use that workaround. I will try to compile it later today or maybe tomorrow and report back.

**Comment by boelle** [comment]
@th33xitus did you have any luck?

**Comment by boelle** [comment]
@th33xitus is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
