### ISSUE TITLE
Auto calibration fails to reach bed starts at endstops 

### ISSUE THREAD

**Issue by bssman89** [MarlinFirmware/Marlin#10627]
The Auto Calibration fails to reach the heated bed of my printer and starts at the top near the endstops
the delta height is correct at 315 mm not sure if a bug in the firmware or just an issue on my part 

im using the firmware release Marlin-AC-G-force8a-AC  on a flsun delta printer

**Comment by forkoz** [comment]
That's G-force... not plain marlin

**Comment by bssman89** [comment]
i fixed it i had some settings wrong in the firmware
