### ISSUE TITLE
[Q] using 2nd extruder as heated chamber control/monitor on LCD

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#10624]
i have asked this on facebook too but want target as wide i can

i have a pretty good setup and only need to nail the filament change/runout

while i added a small pigtail for max chips so i can use thermocouples i have also attached a thermistor to T2 so i can monitor the chamber temp on the LCD

my plan was to enable a 2nd extruder and use that to monitor and maybe later control the temp

that has some downsides thou:

i use the 2nd extruder stepper on the ramps board as i have a dual z stepper and endstop setup to keep the 2 Z in sync automatic

D8-D10 are taken up also and i would really hate to making any more mod to the wiring. to control heating of the chamber my plan was to use a free pin on aux 1 or 2

any tips on how i could make a workarround would be much welcomed

current config and pins file in the zip

pins file is changed as the default pin for the filament runout switch was taken up

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1976477/configuration.zip)

i know that there are a chamber sensor pin defined but that only gives temp over serial and no way to control temp

i want the temp on lcd and a way to control it, i can live with the extruder symbol on the display and i will just find a heater that can work fast enough

an alternative would be a 2nd heated bed but i assume that would be way more work

**Comment by boelle** [comment]
hmmm... i could go in to the pins file for ramps and add a 3rd extruder if its not there and set all pin numbers to -1

and then switch over pin numbers with the 2nd extruder, my reason for this is that the first free extruder will be used for the 2nd Z stepper driver

@thinkyhead does the idea sound good? or are there better ways?

**Comment by thinkyhead** [comment]
> does the idea sound good? or are there better ways?

As a thoroughgoing software engineer, I believe code written
specifically for the application is better than hacking the system.

**Comment by boelle** [comment]
i was also more thinking of it as workaround until the feature is there
