### ISSUE TITLE
[Q] Additive step rates?

### ISSUE THREAD

**Issue by forkoz** [MarlinFirmware/Marlin#10623]
Maybe I don't know how to search for this.

So marlin max single step rate is 10khz. If you are running 1/32 on 1.8deg 16T motor this means a speed of 50mm/s. But since we aren't talking about only a single axis, I assume it all adds up?

i.e
X at 50mm/s = 10khz
Y at 50mm/s = 10khz
Z is probably slow but will have some steps in 1/32s lets say 10khz too.
Extruder, some steps too.

So now we are demanding ~40khz for a print move at top speed? And printing at say 80mm/s will result in lost position/missed steps?

**Comment by GMagician** [comment]
Well I'm not the one who can answer to you but I have mega2560 with 1/32, 0.9deg with 16T belt and I'm working at 90mm/s with no issues

**Comment by oysteinkrog** [comment]
Yes it all adds up, when the maximum step rate is exceeded Marlin will "double up" the pulses, meaning that it will send two pulses in the same step, effectively reducing your microstepping level.

**Comment by forkoz** [comment]
Well I know about quad, double step. At 1/32s the total is ~200mm/s in quad step between all axis? And no axis can travel faster than 50mm/s then? 

So going to 20T pulleys and putting Z in 1/16 will free up steps for X & Y speed or no? Or does a typical printing move fall under the limit?

Basically does this work, add up X+Y+Z+E and divide into 40,000? With upper death limit of 64K (16khz, which supposedly jitters)

**Comment by oysteinkrog** [comment]
Yes I think that is correct, but I'm not an expert on the actual code. I have some practical experience, as there used to be a bug where if you exceeded the limit, movement would "stutter". My experiments back then seemed to confirm that it's a simple matter of summing it up.

**Comment by forkoz** [comment]
So moving to 20T pulley and reducing Z seems to have helped. I have a "top" speed of a single axis (x/Y) of 375mm/s until the motor starts skipping. Printing at 62mm/s seems to make for very good prints.

**Comment by boelle** [comment]
@forkoz 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
