### ISSUE TITLE
Autolevel work reversed 

### ISSUE THREAD

**Issue by demonbd** [MarlinFirmware/Marlin#10637]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by demonbd** [comment]
hi after one week of test i dont solve the problem , mi printer correct the level on the wrong direction, i have tested the bilinear and ubl but impossible to solve 

on the zip the configuration file 
![img_1512](https://user-images.githubusercontent.com/39035109/39677557-38f38e14-517d-11e8-8bfd-e30e3733382b.JPG)
![img_1513](https://user-images.githubusercontent.com/39035109/39677558-39159a5e-517d-11e8-8d7e-a14dfde4930d.JPG)


Regards

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1978003/Marlin.zip)

**Comment by Roxy-3D** [comment]
Print a G26 mesh validation pattern...    and it will help you tune the mesh.

But before you do that...   lower the mesh points around the back left of that picture by .10mm or .15mm

**Comment by demonbd** [comment]
ok

**Comment by demonbd** [comment]
sorry but it's impossible to print , i retake tomorrow

**Comment by demonbd** [comment]
![img_1538](https://user-images.githubusercontent.com/39035109/39698826-b98a6998-51f6-11e8-885c-5762961cc2e9.JPG)
![Uploading IMG_1539.JPG…]()

**Comment by demonbd** [comment]
![img_1539](https://user-images.githubusercontent.com/39035109/39698868-e4522044-51f6-11e8-8a76-19f5e3c1e522.JPG)

**Comment by Roxy-3D** [comment]
I think you would benefit from going to an 8x8 or 10x10 mesh.    I can see low to high to low transitions within a single mesh cell.    Can you post your current G29 T mesh map?    From the picture up above, it kind of looks like your Z_PROBE_OFFSET_FROM_EXTRUDER is not calibrated accurately.

And if you are willing to bump your mesh resolution up to 8x8 or 10x10, re-probe...   And please repost a new (higher resolution) G26 and the G29 T mesh map.

**Comment by demonbd** [comment]
Z_PROBE_OFFSET_FROM_EXTRUDER is 1.9

**Comment by thinkyhead** [comment]
> `Z_PROBE_OFFSET_FROM_EXTRUDER` is 1.9

Unless the nozzle itself is the probe, `Z_PROBE_OFFSET_FROM_EXTRUDER` should be a **negative** value.
Try `M851 Z-1.9`, `M500` and…
```cpp
#define Z_PROBE_OFFSET_FROM_EXTRUDER -1.9
```

**Comment by demonbd** [comment]
Is , sorry i have loss the – on write

Z_PROBE_OFFSET_FROM_EXTRUDER is 1.9

Unless the nozzle itself is the probe, Z_PROBE_OFFSET_FROM_EXTRUDER should be a negative value. Try M851 Z-1.9, M500 and…

#define Z_PROBE_OFFSET_FROM_EXTRUDER -1.9

**Comment by boelle** [comment]
@demonbd still having an issue?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
