### ISSUE TITLE
[2.0.X] POWER_LOSS_RECOVERY - firmware crashes when attempting to write into bin file

### ISSUE THREAD

**Issue by Nutz95** [MarlinFirmware/Marlin#10632]
I'm using trunk version 0500d20d30c9813f47343211c17c005f84d6a51c from today (06 th may 2018), the branch 2.0.X

-I'm using Re-arm + GLCD

I have enabled feature POWER_LOSS_RECOVERY  and what is see is that after a few moves the firmware crashes systematically.
On the debug output i have some messages about init file failed.

I've looked through the code inside file "**Marlin/Src/sd/cardreader.cpp**" and around line 1026 and 1048 i saw that the function void **CardReader::openJobRecoveryFile(const bool read)** is opening the bin file to store the power loss data, but if anything fails, it only displays a message on the serial output.

In the other side, inside function **int16_t CardReader::saveJobRecoveryInfo()** 
we are doing a "  **jobRecoveryFile.seekSet(0)**;" and then a **jobRecoveryFile.write(...)** without checking if the **jobRecoveryFile** has been opened properly or not.

in my case for some reason it cannot write data into my sd card (the file bin is created but is empty).
So afterward i get my firmware to crash and i suspect it comes from this missing sanity check.

I'm i missing something? did you guys had the same issue?

**Comment by thinkyhead** [comment]
The feature has not been heavily tested, and is a more-or-less direct port of the feature supplied by Creality. We'll do more debugging of it soon.

**Comment by Nutz95** [comment]
Ok thanks, i hope this feedback was useful enough.
