### ISSUE TITLE
what are the various pins used for reprap full graphic smart controller lcd +sd card

### ISSUE THREAD

**Issue by amrithmmh** [MarlinFirmware/Marlin#10640]
kindly anyone tell me what are the pins that can be used to directly control the lcd and sd card in full graphic smart controller reprap

note:i have gone through the marlin files and found some pins in pins_RAMPS.h but unable to correctly understand the pins.
i need to use `U8GLIB_ST7920_128X64_1X(E, RW, RS, RST)` directly to print something onscreen

**Comment by Bob-the-Kuhn** [comment]
I don't understand the question.

If the following isn't what you're looking for then please supply more details.

Usually you don't have to worry about pins.  If all you want to do is connect that display to the RAMPS card and use it then do the following:
1. Plug the Smart Adapter onto the RAMPS card
2. Plug the two cables into the adapter and the displaay.
3. In Configuration.h uncomment REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by vilsed** [comment]
http://reprap.org/mediawiki/images/5/51/RRD_FULL_GRAPHIC_SMART_CONTROLER_SCHEMATIC.pdf

I think this is what you're looking for.

**Comment by amrithmmh** [comment]
@vilsed i have gone through the schematic lcd5, lcd6,lcd7 pins are placed on air and no connection?

**Comment by amrithmmh** [comment]
@Bob-the-Kuhn no i dont want to use it with ramps board. whoever has written marlin code for the lcd will surely know the pins connection

**Comment by vilsed** [comment]
@amrithmmh Yes, it appears so. The LCD is being controlled only through SPI interface. If you need a 128x64 display for some other project and you want to push the data through DB0-7 pins, I'd suggest using a generic 12864LCD module, like this one:

https://www.ebay.com/itm/5V-12864-LCD-Display-Module-128x64-Dots-Graphic-Matrix-LCD-Blue-Backlight/201546165293?epid=590996533&hash=item2eed166c2d:g:oEkAAOSwCU1YpmVJ

**Comment by amrithmmh** [comment]
@vilsed i wanted an easy and compact lcd+sd card just like smart lcd controller...if i buy the 128x64 i need to make a pcb or circuit board 
Is there a shield for 128x64 + sd card(one in parallel interface other in spi interface)

**Comment by Bob-the-Kuhn** [comment]
What board are you wanting to attach the LCD to?

With that info I can make recommendations on hardware and firmware.

----

Attached is the Smart LCD adapter when it's attached to the Re-ARM board.  It shows the pins that have to be attached in order for the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER to be functional.

The Re-ARM did some VERY strange things so here's the majic decoder for this graphic:
1.  The names of the pins are what is important.
2.  Ignore the Px_xx and Dxx info.  That's specific to the Re-ARM. 
3.  Make sure that pin 10 on EXP1 is 5V.  The REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER won't run on 3.3V.
4. LCD4 serves as the SCK for the display
5. LCDE serves as the MOSI for the display
6.  LCDRS is the command/data/regisiter select for the display.

One caveat with that LCD.  The LCD4 signal is the SCK for the display BUT it can NOT be shared with any other SPI device.  The display portion doesn't have a real chip/slave select so it responds to every LCD4 transition.  


![re-arm lcd adapter rev 4](https://user-images.githubusercontent.com/20692583/39978998-5bc4e262-5709-11e8-83a0-d9baaf4f0b42.jpg)

**Comment by amrithmmh** [comment]
@Bob-the-Kuhn exactly what i was looking for thank you very much!!!

**Comment by amrithmmh** [comment]
one final doubt ....**LCDRS** is the **slave select** for LCD and **SD_CSEL** is the **ss** for SD card right?

**Comment by thinkyhead** [comment]
I’d expect LCDRS to be the reset button on the LCD, since that’s the usual meaning of RS. If it has no CS/SS specific to the LCD, then I’d expect SD_CSEL LOW to be inverted and used as LCD_CS (assuming the LCD has its own dedicated SPI lines). But don’t quote me on that.

**Comment by amrithmmh** [comment]
@thinkyhead  will try like that thanks

**Comment by Bob-the-Kuhn** [comment]
The LCD section of the `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` is a strange beast.  It doesn't have a select line.  It assumes that it has a dedicated SPI channel.  It always clocks in MOSI whenever SCK is active and then acts on it.

The logical names for the LCD pins in Marlin are:
- `LCD_PINS_RS`
- `LCD_PINS_ENABLE`
- `LCD_PINS_D4`

Their functions are:
- MOSI - `LCD_PINS_ENABLE`
- SCK - `LCD_PINS_D4`
- Register select (command/data) - `LCD_PINS_RS`

**Comment by c3D-Dan** [comment]
Sorry to draw up an old thread, but has anyone managed to get both the LCD and SD card reader working perfectly?  Care to share your setup?
