### ISSUE TITLE
[bugfix-2.0.x] Compile error when #define TEMP_SENSOR_0 -3

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#10646]
So i got the MAX31855 board wired in for the hotend

changed thermistor setting to -3 and compile failed:

https://pastebin.com/CghfBbDA

are there other places i need to change things to make it work?

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1981692/Configuration.zip)

**Comment by boelle** [comment]
in the zip is also the pin file for ramps

the only thing in there that relates to the error is:

```
// SPI for Max6675 or Max31855 Thermocouple
#if DISABLED(SDSUPPORT)
  #define MAX6675_SS       66   // Do not use pin 53 if there is even the remote possibility of using Display/SD card
#else
  #define MAX6675_SS       66   // Do not use pin 49 as this is tied to the switch inside the SD card socket to detect if there is an SD card present
#endif
```

but that it just does not makes sense for me

**Comment by p3p** [comment]
It's the Arduino IDE bug  which means the compile fails because of comments on the same line as defines, remove the comment

> but that it just does not makes sense for me

It makes no sense to anyone why Arduino (or maybe avr-gcc) seems to have developed this oddity in its preprocessor, you can tell its this problem whenever you see `error: pasting`

**Comment by Grogyan** [comment]
I have already raised this as an issue #8010

**Comment by p3p** [comment]
@Grogyan Your issue is unrelated, caused by a missing definition in Re-ARM pins file

**Comment by Grogyan** [comment]
I had tried a long time ago with a standard MEGA and RAMPS, to the same effect.
So because I can run with the MEGA with under the 1.x moniker, it hasn't been a huge priority for me.

So am guessing that ReArm and MEGA under 2.x is going to cause the same for the MAX31855.

**Comment by boelle** [comment]
So can this be called a bug ?

**Comment by thinkyhead** [comment]
A bug in GCC, yes. Remove the comment from the problem `MAX6675_SS` pin definition as a workaround.

**Comment by boelle** [comment]
ahh... yet another one, remember i had a similar issue with another pin


Thanks, only thing left is my "problems" with the filament runout/change part.

**Comment by boelle** [comment]
compiled and flashed, but now it goes straight to min temp error or max temp error if max chip is disconnected, so at least i did connect it to the right port

will try and disable it and see what temp it gets

**Comment by boelle** [comment]
still getting max temp error

![image](https://user-images.githubusercontent.com/3832239/39747051-774bba8a-52ac-11e8-92bc-46185a6342fd.png)

that is there i have connected the max chip, just checked it again

**Comment by boelle** [comment]
the error

![image](https://user-images.githubusercontent.com/3832239/39747512-ceeb5380-52ad-11e8-9afc-6ba381d570a9.png)

**Comment by boelle** [comment]
that was with the min temp set to crazy -50000 and max set to crazy 52750

with min temp set to 5 and max set to 275 i get this on serial:

Recv: Error:MINTEMP triggered, system stopped! Heater_ID: 0
Recv: Error:Printer halted. kill() called!

**Comment by boelle** [comment]
when i used a normal thermistor i did not get any errors even if i disconnected it, the temp was just 0 in that case

and my head cant figure how to disable this check, would like to see what the temp reads out to

**Comment by boelle** [comment]
even with //#define THERMAL_PROTECTION_HOTENDS i get the max temp error

**Comment by boelle** [comment]
so back to normal settings i started to look at the "hidden" files (those that do now show up in the IDE

\src\module\temperature.cpp

i commented out line 803 & 804
```cpp
   // if (current_temperature[0] > min(HEATER_0_MAXTEMP, MAX6675_TMAX - 1.0)) max_temp_error(0);
   // if (current_temperature[0] < max(HEATER_0_MINTEMP, MAX6675_TMIN + .01)) min_temp_error(0);
```
now id there is no max chip connected i reports 800 degree

if i connected a max chip it alternates between 0 and 800

as i have prepared a plug for the bed with CS being D65 i tried both plugs and the outcome was the alternating between 0 and 800 on both

will try and recheck supply voltage

**Comment by boelle** [comment]
hmm... just connected with octoprint to check serial

Recv: Error:Temp measurement error! MAX31855 Open Circuit

**Comment by boelle** [comment]
will check for that and voltage

**Comment by boelle** [comment]
i checked for that its now more stable, all i did was tighten the screw terminals on the tiny max breakout board

i now get:

 ```
Recv:  T:1800.00 /0.00 B:22.50 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.50 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.47 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.50 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.50 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.50 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.47 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.53 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.47 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.47 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.50 /0.00 @:0 B@:0
Recv: Error:Temp measurement error! MAX31855 Open Circuit
Recv: Error:Temp measurement error! MAX31855 Open Circuit
Recv: Error:Temp measurement error! MAX31855 Open Circuit
Recv:  T:0.00 /0.00 B:22.47 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.44 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.47 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.50 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.50 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.47 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.53 /0.00 @:0 B@:0
Recv: Error:Temp measurement error! MAX31855 Open Circuit
Recv: Error:Temp measurement error! MAX31855 Open Circuit
Recv: Error:Temp measurement error! MAX31855 Open Circuit
Recv: Error:Temp measurement error! MAX31855 Open Circuit
Recv: Error:Temp measurement error! MAX31855 Open Circuit
Recv:  T:0.00 /0.00 B:22.50 /0.00 @:0 B@:0
Recv:  T:0.00 /0.00 B:22.50 /0.00 @:0 B@:0
```

**Comment by boelle** [comment]
could it be that my max chip is not the MAX31855 but the MAX31855K ?

**Comment by boelle** [comment]
i rechecked everything again, no obvisous errors found 

i checkeced every single wire from the ramps board to the max breakout and one of the dupont crimps would not go on all the way so will crimp on a new connector later

but funny enough without the CS wire attached i get -39 degree's but serial says something else

Recv:  T:-2040.00

with CS connected i get 800 in display but 1800 on serial

and then i still get some open circuit errors

**Comment by boelle** [comment]
DOH... (i think)

max chip is a 3.3V device but the data pins on the ramps are 5v

need to get hold of some resistors so i can make a divider

**Comment by boelle** [comment]
also when i read forums etc there is a lot of confusion on how to connect

some say that miso and mosi needs to cross

its a board that looks like this

![image](https://user-images.githubusercontent.com/3832239/39756057-5ccafcd6-52c8-11e8-8c2b-d12038a185eb.png)

just the max chip and a capacitor

**Comment by boelle** [comment]
This is how i understand it

SO is ouput at 3.3v which is high enough that the Mega can read it as high or low
CS is chip select from the Mega and i need to get that down to 3.3V 
SCK also needs to be brung down to 3.3V

since its only one way i would assume resistor can do it at a pinch, a level shifter is better but it takes longer to get here

**Comment by Bob-the-Kuhn** [comment]
The MAX31855 is 5V tolerant so no need for a level shifter.

SO goes to MISO (Master In, Slave Out).

**Comment by boelle** [comment]
is the MAX31855K also tolerant?

**Comment by boelle** [comment]
https://www.maximintegrated.com/en/support/faqs/max31855-faq.html

> Can I drive the MAX31855 SPI pins with a 5V supply?
> No, the MAX31855's SPI interface must not have voltage higher than 4.0V applied. High voltage andhigh current (through a voltage divider) will induce self-heating resulting in cold-junction andthermocouple temperature errors, as well as possible damage to the SPI interface pins.

**Comment by boelle** [comment]
but at least i got connectins right the first time 

before i used voltage dividers it said 800 degree's constant, not it's anywhere from -90 to -10 ,that is on the lcd. Serial is more stable but a hell lot negative:

```
Recv:  T:-512.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-512.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-496.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-576.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-481.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-490.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-506.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-512.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-493.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-510.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-512.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-576.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-544.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-552.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-574.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-552.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-627.75 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-628.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-640.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-570.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-576.00 /0.00 B:21.47 /0.00 @:0 B@:0
Recv:  T:-512.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-512.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-512.00 /0.00 B:21.50 /0.00 @:0 B@:0
Recv:  T:-584.00 /0.00 B:21.47 /0.00 @:0 B@:0


```

**Comment by boelle** [comment]
to rule out i damaged i solder on screw terminal and header on another breakout and use the other thermistor.

i ordered 4 of those breakout as they where cheap and i futureproofed my stock with a thermocouple cartridge from e3d and a normal thermocouple (so i could put one on bed when/if it becomes an option)

output on serial is now 

```
Recv:  T:-1506.00 /0.00 B:21.16 /0.00 @:0 B@:0
Recv:  T:-1422.00 /0.00 B:21.19 /0.00 @:0 B@:0
Recv:  T:-1452.00 /0.00 B:21.16 /0.00 @:0 B@:0
Recv:  T:-1512.00 /0.00 B:21.12 /0.00 @:0 B@:0
Recv:  T:-1536.00 /0.00 B:21.19 /0.00 @:0 B@:0
Recv:  T:-1440.00 /0.00 B:21.09 /0.00 @:0 B@:0
Recv:  T:-1460.00 /0.00 B:21.16 /0.00 @:0 B@:0
Recv:  T:-1424.00 /0.00 B:21.09 /0.00 @:0 B@:0
```

and just for giggles i switched place on the thermocouple wires and got this on serial

```
Recv:  T:-1023.75 /0.00 B:20.94 /0.00 @:0 B@:0
Recv:  T:-1019.75 /0.00 B:20.87 /0.00 @:0 B@:0
Recv:  T:-1023.75 /0.00 B:20.94 /0.00 @:0 B@:0
Recv:  T:-1023.75 /0.00 B:20.87 /0.00 @:0 B@:0
Recv:  T:-1019.75 /0.00 B:20.91 /0.00 @:0 B@:0
Recv:  T:-1023.75 /0.00 B:20.94 /0.00 @:0 B@:0
Recv:  T:-1023.75 /0.00 B:20.78 /0.00 @:0 B@:0
Recv:  T:-1023.75 /0.00 B:20.91 /0.00 @:0 B@:0
Recv:  T:-1015.75 /0.00 B:20.87 /0.00 @:0 B@:0
```

the wires came with a red and blue fork connectors so there is no doubt what is what

**Comment by Bob-the-Kuhn** [comment]
You are correct, the MAX31855 is not 5V tolerant.

I was originally looking at a breakout board but further reading said it had logic shifters on the board.

**Comment by boelle** [comment]
:-) now i just have to figure why it reports those crazy negative numbers back

**Comment by TadyTheFish** [comment]
Try swapping the thermocouple wires around?

**Comment by boelle** [comment]
tried that
tried another thermocouple (have 2 in total of same type, K type)
tried another breakoutboard (have 4 )
tried 10nf cap on the thermocouple terminals


will try and hook up the breakout boards to an arduino uno and load a max31855 test sketch and see if it also reports "crazy" numbers there

**Comment by TadyTheFish** [comment]
How long are your wires for the SPI com? I don't know the SPI is running in Marlin but it must be 1MHz or more.. So any long wires act like an antenna. But that would probably give you corrupt data...

**Comment by boelle** [comment]
if i unplug the breakout board i get a constant -99 and if i plug in the breakout with no thermocouple the output on serial just says thermocouple disconntected

but give me an hour and i will see if its the same on the uno

**Comment by TadyTheFish** [comment]
Thats what I was just about to say.. Load a test sketch..

**Comment by boelle** [comment]
getting a solid 2047.75 so far

how often do marlin ask what temp the hotend is, i can asjust my sketch to do the same interval

**Comment by boelle** [comment]
test sketch:

```
#include <SPI.h>
#include "Adafruit_MAX31855.h"


int maxSO =  5;
int maxCS = 6;
int maxSCK = 7;
//Create a MAX31855 reference and tell it what pin does what
Adafruit_MAX31855 kTC(maxSCK, maxCS, maxSO);


void setup() {
  Serial.begin(9600);
  // The MAX31855 needs a little time to stabilize
  delay(500);
}

void loop() {   
  
  Serial.print("C = "); 
  Serial.println(kTC.readCelsius());   
  // delay so it doesn't scroll too fast.
  delay(3000);
}
```

**Comment by TadyTheFish** [comment]
Isn't that wrong? What is your actual temp

**Comment by boelle** [comment]
20'ish

**Comment by boelle** [comment]
at what interval does marlin ask for temp? i guess a lot faster than every 3 sec

**Comment by boelle** [comment]
anyways i have ordered a sparkfun branded breakout that will be here either tomorrow or monday. sadly no mail today as its Christ's ascension (i hate holidays in general)

EDIT:

my conclusion so far is that wire lenght  does not matter as i get the same readings on the printer
its not the thermocouples either as they direct attached to a multimeter behave like you would expect and they both give about the same values

my biggest suspect is the small breakout itself, i have found out that my local seller get them from aliexpress which is not the biggest assurance for quality, in fact i have googled up some romurs that there are someone that makes a living making fake chips that could result in this and that same aliexpress shop is know to sell them. on top of that maxim have made a few bad batches and dont have a clue which ones they are.

so i hope i get the sparkfun breakout tomorrow, it sure looks a lot more like they have given it some more thought with chokes and a cap on the thermocouple terminal

EDIT2:

for the fun of it i placed the thermocouple in front of the exhaust vent of my laptop. i get same readings as anywhere else in the room.

```
C = -2048.00
C = 2047.75
C = -2048.00

```

EDIT3: swapping the wires:
```

C = 193.00
C = -87.00
C = -159.00
C = -172.00
C = 127.00
C = 210.75
C = 249.25
C = 282.75
```

**Comment by boelle** [comment]
@thinkyhead is there anything we can do about the GCC errors? if not i'm tempted to close this one as my readings on an uno are the same as when connected to printer and i'm 90% sure that its a bad or counterfeit chip or just a bad designed breakout

**Comment by thinkyhead** [comment]
>  is there anything we can do about the GCC errors? 

As already explained, those are due to a bug in GCC. As a workaround, you should remove end-of-line comments from any pins that cause errors for you. We are _not_ going to edit all the pins definitions throughout Marlin.

**Comment by Grogyan** [comment]
As mentioned from the Facebook group, if there are caps on the thermocouple lines, and ensure that there is 3.3V going into the board.

If still not working, then it is likely that they have counterfeit devices on them.
