### ISSUE TITLE
Small corexy size bug ? or is it me, going crazy here :)

### ISSUE THREAD

**Issue by Spawn32** [MarlinFirmware/Marlin#10658]
Really need some help here.

I have a Tronxy X5s corexy with a mks sbase and bugfix 2.0.

My problem is that whatever i do mechanically i always end up with yellow side ( see link) being 0.2mm
bigger than the other side, the red side is spot on:

calib link: http://forums.reprap.org/read.php?397,530210

I have re tension'd the belts 10 times, all my pulleys are the same size, motors are the same brand and modell.
The gantry is a bit weak on the X5S so i printed a new strong one and was sure it would fix it, but again, 0.2mm wrong...

also tested with the original controller (a melzi with bugfix 2.0 ), same thing, 0.2mm

I have also taken the frame apart several times t be sure it is 100% square and it is :) also re enforced all corners..

Since there seems to be no other option, could this be a slight firmware bug ?
The really strange thing is that it dosen mater if i print a 20x20mm cube or a 40x40, it's always 0.2mm wrong..

anyone else seeing this ? or could some corexy user test the stl for me ? include here...

I know 0.2mm is not much, but i am going to print a planetary gearbox in fiber nylon and need 0.05mm accuracy :/

If not a bug, is there some way to tweek / force  this in config ? would be easy with a normal printer, but the corexy's are problematic with this kind a stuff :/

[testcube-40x40x10x5.zip](https://github.com/MarlinFirmware/Marlin/files/1985361/testcube-40x40x10x5.zip)

**Comment by thinkyhead** [comment]
It may indicate a backlash issue. You can test this by doing a move in one direction, then trying a short (0.2mm) move in the other direction. If the axis doesn't move, then there's too much slack or slippage somewhere in the drive system.

If you print the cube in a diagonal orientation it will probably come out shorter from corner-to-corner, but may have better dimensions from edge-to-edge.

At this time there's no backlash compensation in Marlin, though it may be added later. Backlash compensation for CoreXY may present some extra challenge.

**Comment by Spawn32** [comment]
Thank you for the input @thinkyhead 
have now checked for backlash on y +/- and x +/- using a caliper, if i move 20mm and go back 0.2, i get 19.8mm, so no backlash..

Printed the same testcube without rotating it 45 degrees, and her comes the funny part, spot on..
comes out at 40.15 x 40.15, the other print gave me 39.99 on the "red" side and 40.19 on the yellow side.

So, i still have some kind of problem. Too bad there isn't a `M579`, or is there some way of tweaking it in Marlin ?

I know x and y steps should / must be equal on a corexy, but what happens if i change one of them ?

easy to re calc the x and y to get it down to 40mm from 40.15, but the main problem will still be in the background :)

EDIT:
Did another test print, this time it came out on two sides (edge to edge) 40.16 and the other two 40.11 (edge to edge), and as you say, edge to edge is more accurate than corner to corner..

so, what to do, my pulleys are new full metal with bearings, cogged and not cogged depending on inner or outer compared to the belt, belt is also new and steel reinforced...

**Comment by thinkyhead** [comment]
Check your G-code to see that it is producing a cube in the correct dimensions. It may be expecting a wider outer wall.

**Comment by boelle** [comment]
@Spawn32 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone
