### ISSUE TITLE
Dual endstop and auto bed leveling

### ISSUE THREAD

**Issue by Koby88** [MarlinFirmware/Marlin#10655]
Hi all first i want to apologize for my bad English because it is not my native language...
Now i want to know if someone can help me with my Z homing..
I have bltouch and i want to use additional two z axis endstops because i have two separate lead screw on z axis and i want to occasionally make them same level. I know how to do that by enabling dual endstop in marlin, what i dont know is how to setup that bltouch is used for probing (min endstop) and two others endstop for Z max so i can disable it throughg code, coz i dont need every time to go z max just to synchronize them.
I want if it is possible that my g code look like this:
```cpp
G28 X0; home x axis
G28 Y0; home y axis
G28 Z0; home z axis to bltouch
G28 E0; for home z to max position so i can delete this command when im not using it...
```
I hope you can understand me and that you gonna help me if you can, thanks in adwance

**Comment by thinkyhead** [comment]
If your Z endstops are set at the max positions, then `G28 Z` will always home to max.
There's no option to switch to the probe for Z homing at this time.

**Comment by Koby88** [comment]
Yes i know, but i want to use my Z min like default G28 Z0, and to assign new letter to Z max endstops, something like E letter so i dont need to home E every time.

**Comment by thinkyhead** [comment]
> but i want to use my Z min like default G28 Z0, and to assign new letter to Z max endstops

No such option exists at this time. You may want to find a developer for hire who can implement this for you. It's unlikely to ever be added as a standard feature to the main Marlin project.

**Comment by boelle** [comment]
@Koby88 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone
