### ISSUE TITLE
[FR] Support for filament tracking system

### ISSUE THREAD

**Issue by Hebign** [MarlinFirmware/Marlin#10664]
Could it be possible to implement support for this?

https://cults3d.com/fr/mod%C3%A8le-3d/outil/filament-tracking-system
https://www.genapart.com/electronique/el1086/

**Comment by thinkyhead** [comment]
We would definitely welcome an implementation submitted by the makers of this unit.

**Comment by Hebign** [comment]
For that to be possible, it would already be necessary that the parameters of Marlin allow it, here is what it is necessary to activate in Repetier so that it works:

 Paramètres (firmware Repetier 0.92.9):

 

Jam detection pin : Broche du fin de course sur lequel est connecté le module de détection.

JAM_STEPS : Nombre de pas moteur théorique entre deux signaux (3,6 x nombre de pas par mm de l'extrudeur)

JAM_SLOWDOWN_STEPS : Nombre de pas entre deux signaux au-delà duquel l'impression va être ralentie.

JAM_SLOWDOWN_TO : % de ralentissement de l'imprimante.

JAM_ERROR_STEPS : Nombre de pas entre deux signaux au-delà duquel on considère qu'il y a une anomalie importante (colmatage, fin de bobine...)

JAM_MIN_STEPS : Nombre de pas minimum avant de prendre en compte un nouveau changement de signal. (Permets d'avoir un signal "propre", en passant la zone où peut se produire un éventuel "balbutiement" au changement d'état du capteur")

JAM_ACTION : Choix de l'action à effectuer quand un "bourrage" est détecté.

**Comment by Hebign** [comment]
https://www.genapart.com/accueil/infos-d%C3%A9tecteur/

**Comment by thinkyhead** [comment]
> For that to be possible, it would already be necessary that the parameters of Marlin allow it

Well, specifically I mean they would need to write the whole implementation, including those (or similar) parameters, the pin assignments, the configuration option to enable the sensor, and any LCD items that ought to go along with it. I would write the implementation, but I have too much else going on right now.

**Comment by GenaUser** [comment]
This module is connected to a "signal" pin and a ground / 5V power supply, like the end-stop sensors.
You can read the description of this Repetier firmware option at the section "Jam and out of filament detection" on this page: https://www.repetier.com/documentation/repetier-firmware/rf-installation/

**Comment by boelle** [comment]
@Hebign try and ask the makers of the unit to submit a PR against bugfix 2.0

**Comment by Hebign** [comment]
@boelle what's a "PR" please ?

**Comment by InsanityAutomation** [comment]
None needed. Lulzbot already implemented support for this style system awhile ago. Take a look at

// Enable this option to use an encoder disc that toggles the runout pin
    // as the filament moves. (Be sure to set FILAMENT_RUNOUT_DISTANCE_MM
    // large enough to avoid false positives.)
    //#define FILAMENT_MOTION_SENSOR

**Comment by InsanityAutomation** [comment]
@boelle @shitcreek this is also done
