### ISSUE TITLE
[2.0.x] ESP8266 + RAMPS-FD V1 - Dual serial ports not working

### ISSUE THREAD

**Issue by rockman256** [MarlinFirmware/Marlin#10666]
Hi!
Esp connected to D18 and D19 port (serial 1).

When in config:
```cpp
#define SERIAL_PORT -1
#define SERIAL_PORT_2 1     
```
Work USB connection, bot not work ESP8266.

And when i change
```cpp
#define SERIAL_PORT 1
#define SERIAL_PORT_2 -1
```
ESP8266 work is fine, but i can't connect to USB.      
What i need to do? I want use wifi and usb connections.

**Comment by rockman256** [comment]
Forget add:
When config is 
#define SERIAL_PORT 1
#define SERIAL_PORT_2 -1
and i plug in SD card at discount smartramps lcd -  system is visibe it as USB disk. But can't connect by serial port.

**Comment by thinkyhead** [comment]
DUE only supports a single serial host interface.

**Comment by boelle** [comment]
@thinkyhead maybe we can close this one?
