### ISSUE TITLE
Anet A8 - Can any unused J3 pin be used to add a thermistor?

### ISSUE THREAD

**Issue by dboa** [MarlinFirmware/Marlin#10665]
My heatbed thermistor isn't working properly, is there a way to wire the thermistor trough the unused J3 connection from my anet A8 and change the code on the Marlin Firmware?

Thank you all in advance.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by Bob-the-Kuhn** [comment]
I don't think so.

**IF** I'm reading the correct schematic, all the analog inputs are already used.  The only possibility is if you're not using a LCD.  There are analog inputs on that connector.

I'm looking at a schematic for the Anet 3D/A6/A8 board.  At least that's what the comments say.

Any chance that the problem is a bad thermistor or a bad connection?

**Comment by dboa** [comment]
I tried to resolder the resistor, and it gets burned when I try to use it,
If I exchange the termistors, both of them show correcty as the extruder termistor.

I'm going to try to use it without the LCD, since I'm using OCTOPI, it might be OK.

Thank you for the input...

**Comment by dboa** [comment]
@Bob-the-Kuhn correct me if I'm wrong, but acording to the Anet A8 Board LCD 2004 schematics:
https://github.com/ralf-e/ANET-3D-Board-V1.0/blob/master/ANET3D_LCD2004_board.png
Isn't the ext-a2 pin unused? Wouldn't I be able to use it for the thermistor?

**Comment by Bob-the-Kuhn** [comment]
What resistor are you working with?  Is it the 4.7K on the Anet board?

Sounds like there is a wiring problem.  Does the resistor burn up if the cable is removed?  

Maybe remove the cable and attach a thermistor directly to the board.

**Comment by dboa** [comment]
@Bob-the-Kuhn I put the thermistor directly to the board.

Looks like the capacitor is burned as well, maybe that's whats burning the resistor (4.7K)?

**Comment by Bob-the-Kuhn** [comment]
Yes, the cap needs to be at least removed.

I doubt that 5V is enough to cause the damage.  You may have stepper motor power shorted to that pin in the cable.

**Comment by boelle** [comment]
@dboa 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone
