### ISSUE TITLE
display don't work

### ISSUE THREAD

**Issue by dakota72** [MarlinFirmware/Marlin#10678]
### Description

I try to compile Marlin 1.1.x in my arduino mega 2560 board with ramps 1.4 and lcd 12864.
I have uncomment  the `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` define
but when I programmed the arduino the lcd is supplied ma don't work(white screen), 
instead the serial works and arduino answer the commands.
I try to program an old version of Marlin and the display works fine!
what's wrong?

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1990680/Configuration.zip)

**Comment by cjsoong** [comment]
@dakota72 Configuration.h setting error
LCD12864 is the choice
```cpp
  #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```

**Comment by dakota72** [comment]
ooops! :+1: 
many thanks !
