### ISSUE TITLE
MKS Sbase + Thermocouple + AD8495

### ISSUE THREAD

**Issue by Studna3D** [MarlinFirmware/Marlin#10683]
Hi,
I copy example `Configuration.h` and `Configuration_adv.h` for MKS Sbase to Marlin bugfix, but I can not compile. I must delete from `platformio.ini `
```diff
  extra_scripts = Marlin/src/HAL/HAL_LPC1768/lpc1768_flag_script.py
- ,Marlin/src/HAL/HAL_LPC1768/upload_extra_script.py
```

After this, compile is fine, but when I set thermocouple AD8495 in `Configuration.h` and record on my MKS Sbase, temperature show still 0. 
I use dual switching extruder. 
Can anyone help me?

**Comment by thinkyhead** [comment]
To fix the issue with the `upload_extra_script.py` you may need to edit these:
```py
target_drive = "REARM"
upload_disk = ""
```
See http://marlinfw.org/docs/basics/install_platformio.html

Assuming the AD8495 is properly connected to an analog input, it should give some kind of temperature reading. Zero most likely indicates a bad connection.

**Comment by Studna3D** [comment]
When I had older version Marlin Bugfix, I adjusted configuration for AD595  with same connection and it worked fine. 
Now both are not working. (neither AD595 or AD8495 when I set up in confinguration.h)

**Comment by thinkyhead** [comment]
Interesting. We added AD8495 support just [8 days ago](https://github.com/MarlinFirmware/Marlin/commit/b50afa9897) so I'll double-check that [nothing got botched](https://github.com/MarlinFirmware/Marlin/commit/a556a8c506) in that patch.

**Comment by Studna3D** [comment]
Thank you very much for answer. 
After new update, now it is OK.

But now I find mistake on my TFT display. When I set -4 on temp_sensor_0, temp_sensor_1 and temp_sensor_bed 0 = 5, display not show temperature, when i set temp_sensor_bed_0=0, display show temperature hotend 1 and hotend 2 good.
On the computer It shows correctly in both cases.
 
Second problem is motion. 
I use Z_SAFE_HOMING and when I set G28, the head moves to the center of the bed. It is good.
But when I enter G28 for the second time, the printer sees the center of the bed as a point of X0 Y0 and move from this point and hit to frame printer.
Does anyone know the solution?

**Comment by thinkyhead** [comment]
> when I enter G28 for the second time, the printer sees the center of the bed as a point of X0 Y0 

That's odd. `G28` should start out by resetting the position. And when it's done homing XY the XY position should always be set to your home XY position (0,0 in the case of homing to minx,miny).

**Comment by thinkyhead** [comment]
> when i set temp_sensor_bed_0=0, display show temperature hotend 1 and hotend 2 good.

Might be some odd logic going on in ultralcd code. I'll check it over and patch if needed.

What kind of TFT display are you using?

**Comment by Studna3D** [comment]
MKS TFT 3.2

**Comment by Studna3D** [comment]
If I click after G28 to -X or -Y on computer, printer head moves to endstop min positions X0 or Y0, but if I click home X or home Y, printer head moves only +5mm from center bed.
I used COREXY.

**Comment by thinkyhead** [comment]
- What do `M114` and `M119` say after `G28`?
- What does `M114` and `M119` say after `G28 X` or `G28 Y`?
- Are you using TMC2130 with `SENSORLESS_HOMING`?

**Comment by Studna3D** [comment]
After G28
```
N15 M114*19
X:190.000000 Y:165.000000 Z:0.180000 E:0.000000 Count A:142000 B:10000 Z:576
N16 M119*29
Reporting endstop status
x_min: TRIGGERED
x_max: open
y_min: TRIGGERED
y_max: open
z_min: TRIGGERED
z_max: open
```
And after G28 X
```
N16 M114*16
X:0.000000 Y:0.000000 Z:4.000000 E:0.000000 Count A:0 B:0 Z:12800
N17 M119*28
Reporting endstop status
x_min: TRIGGERED
x_max: open
y_min: open
y_max: open
z_min: open
z_max: open
```
I am using MKS SBase standart stepper driver DRV8825 and clasic opto endstop.

**Comment by thinkyhead** [comment]
How is it that you have both "min" and "max" endstops?
You may want to disable `USE_XMAX_PLUG`, `USE_YMAX_PLUG`, and `USE_ZMAX_PLUG`.

Please ZIP up your `Configuration.h` and `Configuration_adv.h` files and drop them into your next reply. We'll check them over and see if anything else is amiss.

**Comment by Studna3D** [comment]
On my printer, I have both min and max endstop. 
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1998387/configuration.zip)

**Comment by thinkyhead** [comment]
> On my printer, I have both min and max endstop.

Marlin only acknowledges and uses one endstop per-axis.

**Comment by Studna3D** [comment]
Note for configuration.h:
I use servo switching extruder and I have set Z_HOTTEND_OFFSET for better configuration hotends (the first is higher than the second) -> I must change also tool_change.cpp

**Comment by thinkyhead** [comment]
> I click home X or home Y, printer head moves only +5mm from center bed.

According to your log it looks like `G28 X` does home the X axis until it hits the endstop.
Does that mean the button you're clicking is not sending `G28 X`?

**Comment by Studna3D** [comment]
If I send G28 and G28 X consecutively:  
```
13:30:47.902 : N15 G28*39
13:30:47.904 : echo:Active Extruder: 0
13:31:05.596 : echo:Active Extruder: 0
13:31:05.603 : X:190.000000 Y:165.000000 Z:0.180000 E:0.000000 Count A:142000 B:10000 Z:576
13:31:11.785 : N16 M114*16
13:31:11.792 : X:190.000000 Y:165.000000 Z:0.180000 E:0.000000 Count A:142000 B:10000 Z:576
13:31:21.915 : N17 M119*28
13:31:21.929 : Reporting endstop status
13:31:21.930 : x_min: TRIGGERED
13:31:21.931 : x_max: open
13:31:21.933 : y_min: TRIGGERED
13:31:21.934 : y_max: open
13:31:21.935 : z_min: TRIGGERED
13:31:21.936 : z_max: open
13:31:30.857 : N18 G28 X0*98
13:31:30.860 : echo:Active Extruder: 0
13:31:31.962 : echo:Active Extruder: 0
13:31:31.969 : X:0.000000 Y:165.000000 Z:4.000000 E:0.000000 Count A:66000 B:-66000 Z:12800
13:31:36.688 : N19 M114*31
13:31:36.695 : X:0.000000 Y:165.000000 Z:4.000000 E:0.000000 Count A:66000 B:-66000 Z:12800
13:31:39.202 : N20 M119*24
13:31:39.204 : Reporting endstop status
13:31:39.206 : x_min: TRIGGERED
13:31:39.207 : x_max: open
13:31:39.208 : y_min: TRIGGERED
13:31:39.209 : y_max: open
13:31:39.210 : z_min: open
13:31:39.211 : z_max: open
```

**Comment by thinkyhead** [comment]
If your XY axes are in the middle of the bed, at X190, Y165, it's odd that your X and Y endstops show up as triggered. Maybe these endstops are mis-configured. It would most likely be the `ENDSTOPPULLUPS` settings.

**Comment by Studna3D** [comment]
My settings is in configuration.zip

**Comment by thinkyhead** [comment]
> My settings is in configuration.zip

Well, we're not going to edit them for you. If you're seeing endstops as triggered when they're not supposed to be triggered, change your endstop pullup settings.

**Comment by Studna3D** [comment]
Now it's OK.
```cpp
// Enable pullup for all endstops to prevent a floating state
//#define ENDSTOPPULLUPS
#if DISABLED(ENDSTOPPULLUPS)
  // Disable ENDSTOPPULLUPS to set pullups individually
  //#define ENDSTOPPULLUP_XMAX
  //#define ENDSTOPPULLUP_YMAX
  //#define ENDSTOPPULLUP_ZMAX
  //#define ENDSTOPPULLUP_XMIN
  //#define ENDSTOPPULLUP_YMIN
  //#define ENDSTOPPULLUP_ZMIN
  //#define ENDSTOPPULLUP_ZMIN_PROBE
#endif

// Enable pulldown for all endstops to prevent a floating state
#define ENDSTOPPULLDOWNS
#if DISABLED(ENDSTOPPULLDOWNS)
  // Disable ENDSTOPPULLDOWNS to set pulldowns individually
  //#define ENDSTOPPULLDOWN_XMAX
  //#define ENDSTOPPULLDOWN_YMAX
  //#define ENDSTOPPULLDOWN_ZMAX
  #define ENDSTOPPULLDOWN_XMIN
  #define ENDSTOPPULLDOWN_YMIN
  //#define ENDSTOPPULLDOWN_ZMIN
  //#define ENDSTOPPULLDOWN_ZMIN_PROBE
#endif
```
How does it look with MKS TFT settings?

**Comment by thinkyhead** [comment]
I looked around but didn't locate the logical error in the LCD display settings yet. I'll do some testing using your configs and see what shakes out.

Are you using `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` as your LCD option?

Can you take pics of the LCD when it's not working and attach to your next reply? I'd like to see what it's displaying, if not the correct temperatures.

**Comment by Studna3D** [comment]
I tried set LCD option for `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`

![repetier](https://user-images.githubusercontent.com/39165514/40071163-52618fa0-5870-11e8-91ff-d4b60e01b86d.PNG)
![20180515_184443](https://user-images.githubusercontent.com/39165514/40071265-89b897aa-5870-11e8-99ec-5427471f3d4a.jpg)
![20180515_184449](https://user-images.githubusercontent.com/39165514/40071266-89e8c7c2-5870-11e8-8c16-15d2ed8b6a12.jpg)
![20180515_184456](https://user-images.githubusercontent.com/39165514/40071268-8a110e08-5870-11e8-9d32-f174f766a0b5.jpg)

**Comment by thinkyhead** [comment]
We don't have an option for your display, which just sends G-code commands to Marlin. To support it we will need to know how it connects to the board and its internal protocol. The only display of this general type we currently support is `MALYAN_LCD` and I doubt your display is compatible with that option.

**Comment by Studna3D** [comment]
Display is conected to AUX-1
![ftmq6unin63czon large](https://user-images.githubusercontent.com/39165514/40574061-f70329f2-60cb-11e8-952e-9439da3c6eb6.jpg)

**Comment by thinkyhead** [comment]
Right, so it's connected to serial port 0 on the board, pins `P0_02` and `P0_03`. Now we'll just have to research how its communication protocol works, so we know how to talk to it.

[MKS-TFT-Protocol.pdf](http://osoyoo.com/wp-content/uploads/2016/07/MKS-TFT-Protocol.pdf)
[MKS-TFT28-DataSheet.pdf](http://osoyoo.com/wp-content/uploads/2016/07/MKS-TFT28-DataSheet.pdf)

**Comment by boelle** [comment]
@Studna3D is this still relavant?
