### ISSUE TITLE
K-factor Calibration Pattern generator : unexplained error message for certain input values

### ISSUE THREAD

**Issue by joris57** [MarlinFirmware/Marlin#10697]
I'm using the K-factor Calibration Pattern generator with following values:

Starting Value for K: 0.5
Ending Value for K: 1.1
K-factor Stepping: 0.1

This causes an error message : Your K-Factor range cannot be cleanly divided. Check highlighted Pattern Settings.

In my math, 0.1 **is** a divisor of (1.1-0.5), so this looks like a bug.

**Comment by Sineos** [comment]
The K-Factor Range equals to End minus Start => 1.1 - 0.5 = 1.05
The division of 1.05 by 0.1 equals to 10.5, which is no _clean_ divisor. Except your printer is able to print half lines 😜

**Comment by comps** [comment]
> The K-Factor Range equals to End minus Start => 1.1 - 0.5 = 1.05

1.1 - 0.5 = 0.6
0.6 / 0.1 = 6

**Comment by Sineos** [comment]
hmm, right 😛 
I'll check.

**Comment by Sineos** [comment]
https://github.com/MarlinFirmware/MarlinDocumentation/pull/160

False positive due to rounding error in JS. For JS equals 0.6/0.1 = 6.00000000001
