### ISSUE TITLE
[Bugfix 2.0] Last Bugfix does not compile: PI not defined

### ISSUE THREAD

**Issue by Bergerac56** [MarlinFirmware/Marlin#10698]
The last bugfix (32 bit) 7d78f3476b3a8f6e6640d2e279f7e1d5ef5e1a23 does not compile due to the non definition of PI in G26.cpp

The problem is introduced by this commit : 6671c064cd83e3e8495c73ec4dbd2406811f36ea

Had to add #define PI 3.141592654 (perhaps not the best place to add it but does the job)

      #if ENABLED(ARC_SUPPORT)
        #define PI 3.141592654
        #define ARC_LENGTH(quarters)  (INTERSECTION_CIRCLE_RADIUS * PI * (quarters) / 2)
        float sx = circle_x + INTERSECTION_CIRCLE_RADIUS,   // default to full circle
              ex = circle_x + INTERSECTION_CIRCLE_RADIUS,
              sy = circle_y, ey = circle_y,
              arc_length = ARC_LENGTH(4);

**Comment by boelle** [comment]
what do you use to compile with? not sure if it makes a difference but  if using arduino IDE have you tried ver 1.9.0 ?

**Comment by ManuelMcLure** [comment]
I've put in a couple of pull requests to fix this. If you want to fix it yourself just replace `PI` with `M_PI` - that's guaranteed to be defined for all build platforms.

**Comment by Bergerac56** [comment]
Thanks. Will do
