### ISSUE TITLE
Q: How to add a dummy stepper to ramps config?

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#10709]
now that i got thermocouple working i wanted to "hack" in support for heated chamber 

i thought: since i have a thermistor input free for a 2nd extruder that i dont use anyway why not use that to take chamber temp readings. i would only need to say i have 2 extruders and add a dummy extruder since i want to use the 2nd  extruder socket for a dual z stepper setup. i added this:

```cpp
#define E1_STEP_PIN        40
#define E1_DIR_PIN         64
#define E1_ENABLE_PIN      59
#ifndef E1_CS_PIN
  #define E1_CS_PIN        63
#endif
```

i tried to use -1 for pin numbers but then compile complained that the stepper was not there, so i figured that any free pin would make do

**Q: is it possible to add a dummy that do not take up any pins?**

i thought why not add a 2nd heater so i dont have to change the wiring and i would just need to change pin numbers once i decide to add a heating element

i added these 2 lines:

```cpp
  #define HEATER_1_PIN     42
  #define FAN1_PIN         44
```

in this section

```cpp
#if ENABLED(IS_RAMPS_EFB)                      // Hotend, Fan, Bed
  #define FAN_PIN        RAMPS_D9_PIN
  #define HEATER_BED_PIN RAMPS_D8_PIN
  #define HEATER_1_PIN     42
  #define FAN1_PIN         44
```

again i would have liked to not take up any real pins before i knew that a chamber heater is needed

of course my simple thinking did not work

**Comment by thinkyhead** [comment]
We already have formal support for a chamber temperature sensor.
Just set these options in your `Configuration.h`:

```cpp
#define TEMP_SENSOR_CHAMBER 1
#define TEMP_CHAMBER_PIN    2   // Analog Input
```
…setting `TEMP_CHAMBER_PIN` to whatever analog input your sensor is connected to.

**Comment by boelle** [comment]
yeah but that does not output the temp to LCD 

so that is why i wanted just a dummy stepper driver as a workaround to not have full chamber temp control... i can live with the symbol is a hotend

I have changed the title back, reason is that i know how to configure chamber sensor and that is not what i'm after. i want to add a dummy stepper since that will allow me temp on the LCD and it will when i have the time for it also allow me to control chamber temp. using a 2nd extruder is far from perfect but its a workaround that i can live with. the only questionable part is how fast the heater for the chamber works, if its needed that is.... bed and hotend all add to the heating requirements

**Comment by thinkyhead** [comment]
"[FR] Display Chamber Temperature on LCD"

**Comment by boelle** [comment]
Hmm i could go with that title. Do we have a FR for full chamber control?

we do have an FR for chamber temp in display here: https://github.com/MarlinFirmware/Marlin/issues/973

So maybe rename this one to full chamber control ? that comes more close to what i have gotten with an extra extruder workaround thou i had to spend some of the free pins

**Comment by boelle** [comment]
closing this one  in the hope that one day we have true chamber control and not just a chamber temp on the serial line
