### ISSUE TITLE
 Incorrect temperature of the heat platform when using a thermocouple AD8495 on it

### ISSUE THREAD

**Issue by nightdemonx** [MarlinFirmware/Marlin#10720]
### Description

Incorrect temperature of the heat platform when using a thermocouple AD8495

### Steps to Reproduce

1. Set #define TEMP_SENSOR_BED -4
2. Compile and flash

**Expected behavior:** [What you expect to happen]
Correct value of temperature
**Actual behavior:** [What actually happens]
Temp of extruder and bed are same also if i heated only extruder

#### Additional Information
My solution is: on Conditionals_post.h
--- #define HAS_ADC_TEST(P) (PIN_EXISTS(TEMP_##P) && TEMP_SENSOR_##P != 0 && TEMP_SENSOR_##P > -2)
+++ #define HAS_ADC_TEST(P) (PIN_EXISTS(TEMP_##P) && TEMP_SENSOR_##P != 0 && TEMP_SENSOR_##P > -5)

**Comment by Printalect** [comment]
Thermocouples are slightly different. Not sure what board or thermocouple you have....
1.) Check that you connected them into a Thermocouple terminal and not a thermistor terminal. Polarity matters.

2.) Try an additional thermocouple breakout board.

3. ) Can change the gain in the config adv. I double the gain for Type K.


![image](https://user-images.githubusercontent.com/18374296/39961948-8fd840e4-55f6-11e8-8eea-5bd56962534a.png)

**Comment by nightdemonx** [comment]
@Printalect. thank for you reply. Added AD8495 thermocouple to Marlin it is my [commit](https://github.com/MarlinFirmware/Marlin/commit/e911635fb1604b7ab2c2bd9f829446c2718697d8) and it worked fine. But after [some optimization](https://github.com/MarlinFirmware/Marlin/commit/81b632c2558257c31b2f762e9bf8237c03638e07) of code it is not work right.

**Comment by Printalect** [comment]
You'd need to extrapolate some more. 

What part is not working right? Is the temp too high? too Low? ...not compiling?

**Comment by Printalect** [comment]
I'm not exactly sure what your issue is?

What board are you using and are you using the latest Firmware?

**Comment by thinkyhead** [comment]
`HAS_ADC_TEST` is now defined this way:
```cpp
#define HAS_ADC_TEST(P) (PIN_EXISTS(TEMP_##P) && TEMP_SENSOR_##P != 0 \
  && DISABLED(HEATER_##P##_USES_MAX6675))
```
If the current code still doesn't work, let us know and we'll look into it.

**Comment by nightdemonx** [comment]
now all is fine! Thank you!
