### ISSUE TITLE
[bugfix-2.0.x] Random Axis Shutdowns

### ISSUE THREAD

**Issue by Zwaubel** [MarlinFirmware/Marlin#10725]
I'm recently experiencing random axis shut offs during prints:

The printer is starting of just fine and in the middle of an arbitrary layer one axis shuts off and is deactivated (so thath I can move the axis by hand) for the rest of the print and the printer is continuing its print job in two dimensions rather than in three.

When canceling the print, the axis comes back to life immediately as if nothing had happened.
It's not always happening, but if the error ocurres, than its specific to one gcode file.

I checked those files but did not find any command that could have caused that behavior.
Interestingly whenever this strange behavior ocurred, the corresponding stl files was sliced by either cura 3.3.1 or slic3r prusa edition. This does not apply the other way around: cura 3.3.1 and slic3r prusa edition don't always produce unprintable gcode.

Gcode files produced with with cura 15.04 never have led to axis shutdowns...

I checked my electronics twice, recalibrated the currents, improved the cooling... all without any effect.

Machine details:
cartesian printer, RAMPS1.4+Mega2560, no heated bed

GCODE files that caused the issue:
[gcode_files.zip](https://github.com/MarlinFirmware/Marlin/files/1997966/gcode_files.zip)

printer config:
[config.zip](https://github.com/MarlinFirmware/Marlin/files/1997967/config.zip)

picture of the treefrog print failing (z axis was randomly shut off):
![20180512_235813](https://user-images.githubusercontent.com/25179994/39961902-c75bb510-5640-11e8-8678-9d8676851f1a.jpg)

**Comment by kaushikvemparala** [comment]
Hi, is it the same axis each time? if yes, which one?
thanks,
kaushik

**Comment by Zwaubel** [comment]
No it's not. There is a tendency that the x axis is mostly affected by the issue, but as you can see in the picture, while printing the tree frog it was the z axis that shut off. It is unpredictable...

**Comment by thinkyhead** [comment]
Is this only occurring in the latest code?
And not occurring with code from —say— three to five days ago?

**Comment by Zwaubel** [comment]
I'm struggling with this issue since about 2 - 3 weeks (all based on the bugfix-2.0.x branch). 
The refactoring of the planner and stepper (#10688) did not change anything on those random shutdowns..
Or are your referring to the layer shift issue (#10446)?

Maybe it is just time to move to a 32 bit board. The trusty old 8 bit mega really is at the border of its computational capacity and with all the upcoming features and ideas for Marlin 2 the mega will probably become a bottleneck for whats possible. 🙈 
I just can not find a 32 bit board that fits my needs and wishes..

**Comment by Zwaubel** [comment]
Unfortunately the problem still remains even with ejtagles planner and stepper optimisations.
Just tried to print another treefrog and the X axis randomly shut off mid print.

Here is the gcode file sliced with cura 3.3.1:
[GRNEO_treefrog_45_cut.zip](https://github.com/MarlinFirmware/Marlin/files/2012159/GRNEO_treefrog_45_cut.zip)

And here is a picture of what happened:
![20180517_094440](https://user-images.githubusercontent.com/25179994/40164148-0ed16982-59b9-11e8-8516-f0335a7b1818.jpg)

**Comment by smoki3** [comment]
I also noticed some layer shift errors. First i thought my motors **are losing** steps but that isn't the issue

**Comment by thinkyhead** [comment]
I'm unable to reproduce this issue on my hardware. Random axis shutoffs would tend to indicate faulty stepper drivers. The firmware only shuts down drivers when certain features are enabled, and then only after a period of inactivity. If you turn off all the `DISABLE_INACTIVE_*` features the code to turn off the steppers won't even be compiled in, so you can use that to rule out auto-shutoff.

**Comment by Zwaubel** [comment]
@thinkyhead
Thank you for trying, anyways. 
I tuned my printers motion settings and I think therewith fixed its compatibility with gcode produced with slic3r (no steploss or shutdowns on 6+ hour prints). I had to drastically slow down my maximum x and y axes velocity. They are now at 90 mm/s (max), everything higher than that would randomly lead to thunk noises, steploss up until complete axis shutdowns. Playing with the stepper current did nothing but an increase of the  temps of the electronics.
I'm using tmc2208 on x, y and z operating in stealth chop 2.0, and a drv for the extruder. My printer is quite small, 150mm for all axes. Is the atmega 2560 just to weak to enable higher speeds?

Is your printer working fine with the latest cura from ultimaker?
To me it seems almost like gcode files made with cura 3.3 are somehow too complex for the AVR and cause parsing errors. Those files are by far the biggest compared with cura 15.04 or slic3r..

**Comment by thinkyhead** [comment]
I've been using S3D and haven't used Cura in a while. I'll do some test cubes soon and see how they look with the two slicers.

**Comment by thinkyhead** [comment]
>  They are now at 90 mm/s (max), everything higher than that would randomly lead to thunk noises, steploss up until complete axis shutdowns.

As we're trying to figure out a way to prevent thermal shutdown (thunk) please check and see if 1.1.8 is just as bad. If it doesn't give you as much trouble, then you could join the search party and help us track down the point in time where the trouble begins. Once we know the day and hour where the problem began, we should be able to at least mitigate the issue.

**Comment by Zwaubel** [comment]
Sorry for the delayed response. I had a surgery last week and I'm currently a little handicapped. 

Just found something interesting in the FAQ of the Klipper Firmware:


### My TMC motor driver turns off in the middle of a print

There have been reports of some TMC drivers being disabled in the middle of a print. (In particular, with the TMC2208 driver.) When this issue occurs, the stepper associated with the driver moves freely, while the print continues.

It is believed this may be due to "over current" detection within the TMC driver. Trinamic has indicated that this could occur if the driver is in "stealthChop mode" and an abrupt velocity change occurs. If you experience this problem during homing, consider using a slower homing speed. If you experience this problem in the middle of a print, consider using a lower junction_deviation setting.

**Comment by Zwaubel** [comment]
I'm closing this issue for now. Slic3r made GCode works fine, Cura rarely messes up but I'm not using it that often so I can live with that.
BTW: ejtagles latest commits did improve the overall printer performance and reliability by a lot! @ejtagle, @thinkyhead and everyone else who was involved: Thank you for all your time and effort you put into your contributions.
