### ISSUE TITLE
Velleman K8400 marlin 1.1.8 compile error

### ISSUE THREAD

**Issue by petri1973** [MarlinFirmware/Marlin#10750]
### Description

Wrong settings in configuration.h file

### Steps to Reproduce

Tried to compile directly moving configuration files to root directory from newest build 1.1.8

**Expected behavior:** Compile without errors

**Actual behavior:** Compile error

#### Additional Information

Sanity check reports error in configuration.

Line 788: "#define Y_MIN_POS 20" causes error, should be 0 (zero).
as default bed size is set to 200 x 200 on lines 783, 784.

Error message: 
static assertion failed: Movement bounds ([XY]_MIN_POS, [XY]_MAX_POS) are too narrow to contain [XY]_BED_SIZE.

Fix:

Change #define Y_MIN_POS value to 0 (zero)

**Comment by thinkyhead** [comment]
Thanks for the report. This is now patched.
