### ISSUE TITLE
Marlin 2.0 resume printing issue!

### ISSUE THREAD

**Issue by phongbkap** [MarlinFirmware/Marlin#10756]
Hello!
I just tested **_Marlin 2.0_** on my Reprap 3D printer - _MKS Gen v1.4_ board, Reprap_smart_Controller_LCD.., almost functions are working well, just only RESUME printing isse happen. 
When I cut off power during printing to test, then power up printer. there is a notify that "**Resume printing" & "stop printing**". I choose Resume however, after machine warm up again Hotend & Bed it homes and there is a message on the screen "**_Home Z first_**" and nothing happen then.
So, I cannot resume print!
Anyone can help me? Does Marlin 2.0 work with 8bit processor?
Thanks

**Comment by Eno423** [comment]
I thought that Marlin 2 was specifically for 32bit processors///

IE you would have to be running the MKS Sbase....but i would also assume that you wouldnt have been able to flash 2.0 to a non Sbase....so not 100% sure

**Comment by ManuelMcLure** [comment]
> I thought that Marlin 2 was specifically for 32bit processors///

Marlin 2 adds support for 32 bit processors, but also supports all 8-bit boards that are supported by 1.1.x.

**Comment by thinkyhead** [comment]
> I choose Resume however, after machine warm up again Hotend & Bed it homes and there is a message on the screen "Home Z first" and nothing happen then.

Resume on power-loss is still experimental. We'll work on debugging and improving it, and should have it working by the time 1.1.9 is released.

**Comment by boelle** [comment]
@phongbkap is the problem still there with latest bugfix 2.0?
