### ISSUE TITLE
Z-Axis moves a lot faster than other axis, also does not home properly.

### ISSUE THREAD

**Issue by AlexScotland** [MarlinFirmware/Marlin#10758]
Just updated my firmware on my Kossel Mini.  
When I try to reset all axis' to home, the Z-Axis moves down (around half way), then moves back to the top indefinitely, resulting in that horrid grinding noise.  
I can move each axis individually (except move Extruder does nothing), but the Z-Axis seems to move a lot further than the values im dialing in.

Any Ideas if this is a known bug? or configuration.h issues?

Can send my config.h file, but I have only changed invert y axis to false, and uncommented 

> #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

It is also noted that on the info screen, X, Y and Z blink into "?"

**Comment by thinkyhead** [comment]
> It is also noted that on the info screen, X, Y and Z blink into "?"

It does that until the axes are homed.

> When I try to reset all axis' to home, the Z-Axis moves down (around half way), then moves back to the top indefinitely, resulting in that horrid grinding noise.

This is because your configuration is messed up. When you home a delta, all carriages should move together towards the top until one of them hits an endstop. Then the other two carriages should move up individually and bump the endstops twice.

If your machine isn't behaving that way, then you probably have your homing directions or stepper directions backwards. Make sure all of these match, either all `true` or all `false`:
```cpp
// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
#define INVERT_X_DIR false
#define INVERT_Y_DIR false
#define INVERT_Z_DIR false
```
…and make sure the steppers are plugged into the board all the same way.

Your weird behavior could also be due to the endstops being set incorrectly. When the endstops are not pressed, `M119` should report them all as "open." And when any endstop is pressed, it should show as "TRIGGERED." If `M119` shows otherwise, you probably need to change these:
```cpp
#define X_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Y_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
```

If endstops show up with random states on `M119` then you may need to enable pullups:
```cpp
// Enable pullup for all endstops to prevent a floating state
#define ENDSTOPPULLUPS
#if DISABLED(ENDSTOPPULLUPS)
  // Disable ENDSTOPPULLUPS to set pullups individually
  //#define ENDSTOPPULLUP_XMAX
  //#define ENDSTOPPULLUP_YMAX
  //#define ENDSTOPPULLUP_ZMAX
  //#define ENDSTOPPULLUP_XMIN
  //#define ENDSTOPPULLUP_YMIN
  //#define ENDSTOPPULLUP_ZMIN
  //#define ENDSTOPPULLUP_ZMIN_PROBE
#endif
```

**Comment by AlexScotland** [comment]
Thanks for the reply!

I inverted the logic on my X and Y because they were showing triggered (Now they are open).
Now when I Home, it moves the Z axis first upwards and keeps grinding indefinitely at the top.
This printer worked with Marlin v1, did wiring change? or is it still the same?

When I try homing through repetier host, it moves the Z axis down halfway, and the X axis indefinitely, tangling the extruder in the treads.

Quick edit:
I tried using the configurations for the Kossel XL, and it seemed to work fine when I inverted the direction of x, y and z.  Gonna try a test print.

**Comment by AlexScotland** [comment]
Now the Z-Axis is too much (G0 Z0 pushes it against the build plate for a while).  Which value in the Configuration.h do I need to change? i've tried the Manual_z_home but it does not seem to do much

EDIT:  Okay I have fixed that issue by making the overall height (DELTA_HEIGHT) = to 303 so the extruder just barely isnt on the bed.  The extruding stepper motor was moving backwards, but invert E0 to false seemed to do the trick.

**Comment by thinkyhead** [comment]
Glad you got it sorted. We're too busy chasing bugs and working on 32-bit support lately to entertain support requests, so we have to put them at the bottom of the triage list. You may get quicker and more thorough responses going forward by using these community resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
