### ISSUE TITLE
Not moving servo for switching extruder

### ISSUE THREAD

**Issue by Studna3D** [MarlinFirmware/Marlin#10766]
The servo doesnt switch when I change extruder nozzle. The last version of the code was working.

**Comment by GMagician** [comment]
Please your configuration. I have it perfectly working

Which version are you using? I'm on bugfix-2.0.x, if you are on 1.1 better to try bugfix-1.1.x first

**Comment by Studna3D** [comment]
I use bugfix-2.0.x. and MKS Sbase. The last version Bugfix 2.0.x was working, but now the servo not moving. 
I watched the code here and saw change in tool_change.cpp 6 days ago.

**Comment by GMagician** [comment]
well I'm using a "yesterday" copy of it and it's working. If you attach your configuration I can try to look which differences with mine and check involved code

**Comment by Studna3D** [comment]
It is my configuration
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2017429/configuration.zip)

**Comment by GMagician** [comment]
Ah ok, I also have SWITCHING_NOZZLE not only SWITCHING_EXTRUDER. My cnf is a single stepper used for move filament and 2 nozzles switching. switching is done by a servo
What about yours configuration?

about:

> I watched the code here and saw change in tool_change.cpp 6 days ago.

if I'm not wrong developers moved some methods from one class to other

**Comment by GMagician** [comment]
Are you sure you are using this cnf files?
I see `#define NUM_SERVOS 3` but just below '#define SERVO_DELAY { 300 }', it should not compile

**Comment by GMagician** [comment]
by the way try to change

`#define DO_SWITCH_EXTRUDER (SWITCHING_EXTRUDER_SERVO_NR != SWITCHING_NOZZLE_SERVO_NR)
`

to

#define DO_SWITCH_EXTRUDER true

in tool_change.cpp line 350.. there are other part in code to change, I'll post a PR

**Comment by Studna3D** [comment]
I changed define switching extruder and switching nozzle together and it's working. 
Thank you very much!

**Comment by GMagician** [comment]
@Studna3D when both SWITCH are enabled the define can be left untouched

**Comment by GMagician** [comment]
I think this can be closed, also a PR has been posted and should fix it.
When merged, if you have again issues, you can reopen
