### ISSUE TITLE
1.1.8-bugfix: "Fade height" on LCD wrong

### ISSUE THREAD

**Issue by insanity67** [MarlinFirmware/Marlin#10761]
Hi!
I have a problem, and dont know if this is a bug or ok: Fade height shown by M503 is 2mm, on LCD showing 0mm. If I change this on the LCD to 1mm, M503 shows 1mm.
When I save this, and restart printer, M503 shows 1mm, but again 0mm on the LCD.

Best regards!

**Comment by thinkyhead** [comment]
Sounds like a potential bug. We'll look into it!

**Comment by thinkyhead** [comment]
>  on LCD showing 0mm

I assume you mean, when you go to the "Tune" menu or the "Bed Leveling" menu and want to edit the value, it shows 0 as the current edit value, yes?

**Comment by insanity67** [comment]
Yes, the current value shown is always 0.00 after restart/reset of the printer. Looks like the value is read from EEPROM at boot (because showing in M503) but somehow the LCD uses another variable to show that is not populated?!

**Comment by thinkyhead** [comment]
And you are using the latest `bugfix-1.1.x` branch? So far as I can tell, in the current code that temporary variable _is being set_ prior to showing the edit item. However, if it's set with `M420 Znnn`, `M501`, or `M502` then you have to exit and re-enter the menu for it to update on-screen.

**Comment by insanity67** [comment]
Yes the latest branch, pulled yesterday.
OK thanks, I have to test if that happened with `M420 Z`.
But right after restart/reset it shows 0, there was no `M420` at this state?

But, would it not be better to also show the value entered with `M420 Z` on LCD?

**Comment by insanity67** [comment]
Finally had some time to test:
When I power on my printer, in the menu under "tune" the "Fade Height" is 0.00.
As soon as I start a print (even while preheating, no `M420` in the GCode) the "Fade Height" is showing the correct value from EEPROM.

Dont know if this is a bug, or a wanted behaviour? I would find it better if the value was there after I start the printer.

**Comment by thinkyhead** [comment]
Ok, so it's good in the Tune menu but incorrect in the Prepare menu.

**Comment by insanity67** [comment]
Yes, Prepare Menu shows 0.0 right after printer power up. As soon as I start the print Prepare changes to Tune, and there is my Value from EEPROM.

**Comment by thinkyhead** [comment]
Ok, I've patched the two bugfix branches to fix the issue. Should work better now.

**Comment by insanity67** [comment]
Compiled, tested -> works! Thanks for your great support!
