### ISSUE TITLE
Swap TEMP_BED_PIN 

### ISSUE THREAD

**Issue by crashoverdone** [MarlinFirmware/Marlin#10762]
Hi,

Iam having issues on my heated bed temp sensor. I think a shorted T1. So after google about this i've found some solutions and i've tryied nearly all.

My board is a RAMPS 1.4 and Marlin 1.1.8. My pins_RAMPS.h
```cpp
//
// Temperature Sensors
//
#define TEMP_0_PIN         13   // Analog Input
#define TEMP_1_PIN         15   // Analog Input
#define TEMP_BED_PIN       14   // Analog Input
```

and my configuration.h
```cpp
#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_4 0
#define TEMP_SENSOR_BED 1
```
So in first i tested my sensor by connecting to T0 and its gives normal reading.
After i change in pins_RAMPS.h to this:
```cpp
#define TEMP_0_PIN         13   // Analog Input
#define TEMP_1_PIN         14   // Analog Input
#define TEMP_BED_PIN       15   // Analog Input
```
to see if it was possible to use T2 insted of T1 for bed sensor but the reading temperature its wrong it shows 115ºC insted of 20ºC (room temp).

I whould like to know if its possible and how to change de pins so i can use T2 for TEMP_BED_PIN

Thanks

**Comment by GMagician** [comment]
Theoretically it should be possible. What If you connect to T2 your working sensor (the one in T0) maybe you have some other issue on T1 input

**Comment by crashoverdone** [comment]
GMagician thank you for your suggestion but i've tried that too.
both sensores are ok only the T1 not ok and changing the pins_RAMPS.h as i mentioned before gives a bad reading on T2. I dont know if its needed to change other file or just this one.

**Comment by GMagician** [comment]
Maybe you have some issues even on T2, sure T2 is really working?
Changing pin as you've done should be enough

**Comment by crashoverdone** [comment]
GMagician maybe you're right. Is there a way to measure to check that?

**Comment by GMagician** [comment]
You can try to disconnect all sensor and match read values.
I'm almost sure that changing pins in .h is enough. You can try also moving T2 input to T0 and see if it works. This way you confirm that pin swapping is working.

**Comment by crashoverdone** [comment]
GMagician, hi and thanks a lot for your tips.
My ramps its f...ed so i order a  new one and all fine.

**Comment by GMagician** [comment]
Happy to have helped you and a little sorry for your board...

Now you can close this, I think

**Comment by JoHo82** [comment]
Hi.
I stuck in a problem with my Ender 2
.
I demaged the Pin A6 (long story short: I pressed the screws on the Heatbed and so made a short circuit between 12V and the TempBedPin...)

So I now try to move the TempBedPin to A5 (which is free at my board). I soldered it to the pin.
Then I changed #define TEMP_BED_PIN in "pins_SANGUINOLOLU_11.h" from 6 to 5:

#define TEMP_0_PIN 7 // Analog Input (pin 33 extruder)
#define TEMP_BED_PIN 6 // Analog Input (pin 34 bed)

to

#define TEMP_0_PIN 7 // Analog Input (pin 33 extruder)
#define TEMP_BED_PIN 5 // Pin swapped from 6 to 5

But it doesn't work. It shows me constantly 44°C (what is different to 110°C that it showed when it was set to A6)

What is wrong? do i need to make additional settings?

Thanks!

**Comment by shitcreek** [comment]
My guess is that pin 6 has a circuit whereas pin 5 is just a regular analog pin. https://reprap.org/mediawiki/images/8/83/Sanguinololu-schematic.jpg
