### ISSUE TITLE
Dual Z Driver problem

### ISSUE THREAD

**Issue by Gigahertz77** [MarlinFirmware/Marlin#10771]
Marlin 1.1.6

For E1 ( Z2 ) the number sequence is this 
```cpp
 /*                                     X, Y, Z, E0 [, E1[, E2[, E3[, E4]]]]
 */
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 100.40, 100.45, 803.98, 200.18, 803.98 } 
```
or 
```cpp
 /*                                     X, Y, Z, E0 [, E1[, E2[, E3[, E4]]]]
 */
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 100.40, 100.45, 803.98,  803.98, 200.18,  }
```

**Comment by GMagician** [comment]
There is a ',' at end DEFAULT_AXIS_STEPS_PER_UNIT tha shouldn't be there...I think this will set to 0 the value. You can repeat same value or, if missing, last E value will be used.

Don't checked code about this but read only reported defines

**Comment by thinkyhead** [comment]
When using Dual Z axes they both use the value in the Z (3rd) position, so you only need 4 values in each array.
```cpp
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 100.40, 100.45, 803.98, 200.18 } 
```

**Comment by boelle** [comment]
@Gigahertz77 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
