### ISSUE TITLE
EMERGENCY_PARSER logic seems to be flipped

### ISSUE THREAD

**Issue by mamoit** [MarlinFirmware/Marlin#10770]
In the Configuration file, the `EMERGENCY_PARSER` documentation states that:
__Enable an emergency-command parser to intercept certain commands as they enter the serial receive buffer, so they cannot be blocked__

I assume that the intended behavior is that defining this flag would allow for `M108`, `M112` and `M410`to be take effect as close to instantly as it gets.

But it seems that the logic is flipped, as shown [here](https://github.com/MarlinFirmware/Marlin/blob/8b35f2c8460e398fbd1ae9754350106fa45cdba2/Marlin/Marlin_main.cpp#L1096), [here](https://github.com/MarlinFirmware/Marlin/blob/8b35f2c8460e398fbd1ae9754350106fa45cdba2/Marlin/Marlin_main.cpp#L7961) and [here](https://github.com/MarlinFirmware/Marlin/blob/8b35f2c8460e398fbd1ae9754350106fa45cdba2/Marlin/Marlin_main.cpp#L12195).

Shouldn't these `DISABLED` be actually `ENABLED`?

* `M112` works with `EMERGENCY_PARSER` both enabled and disable, taking effect instantly in the for former, and some time for the latter.
* `M108` to simulate a screen click does not work at all with the `EMERGENCY_PARSER` enabled, but with it disabled, it does work as expected.

If this is the case we will be more than happy to submit a PR, but we wanted to ask for an opinion first.

**Comment by ManuelMcLure** [comment]
The reason those are `DISABLED` is because when `EMERGENCY_PARSER` is used those codes are handled directly in the emergency parser (`emergency_parser.h`) so it doesn't make sense to also check for those codes outside the emergency parser.

**Comment by mamoit** [comment]
Learning every day :)
I'm currently working with `1.1.8` so that file does not exist, but I tracked that it comes from [here](https://github.com/MarlinFirmware/Marlin/commit/11bbcfd69e7c3d767b9811ed12558f436242bc69#diff-1f9a07f1960a1d914dd73e765ec4104cL82).
Thanks @ManuelMcLure!
And sorry @thinkyhead for opening a dumb issue (still getting used to the codebase).

**Comment by mamoit** [comment]
I think I ran into `M108`'s behavior described in #9254 (or lack thereof), and assumed the whole logic was flipped, but it actually seems to just be an `M108` problem (digging deeper and deeper into the code).
