### ISSUE TITLE
Thermistor and thermocouple used together may cause incorrect thermistor readings

### ISSUE THREAD

**Issue by zeleps** [MarlinFirmware/Marlin#10773]
### Description

Using a thermocouple sensor AFTER a thermistor sensor causes incorrect thermistor temperature reading in Marlin 2.0

### Steps to Reproduce

1. Configure TEMP_SENSOR_0 as any thermistor (e.g. 5)
2. Configure TEMP_SENSOR_1 (or any subsequent sensor) as any thermocouple (e.g. -1)
3. Sensor 0 reading is calculated based on the linear function of the thermocouple instead of the appropriate thermistor table.

#### Additional Information

This is a bug in temperature.cpp, Temperature::analog2temp function. Each case statement in the thermocouples switch should have a break statement in the end, otherwise sensors with no thermocouple code fall through (incorrectly) to the next case statement (which might be defined). So the switch statement should be changed to:

```C
  switch (e) {
    case 0:
      #if ENABLED(HEATER_0_USES_MAX6675)
        return raw * 0.25;
      #elif ENABLED(HEATER_0_USES_AD595)
        return TEMP_AD595(raw);
      #elif ENABLED(HEATER_0_USES_AD8495)
        return TEMP_AD8495(raw);
      #else
	break;
      #endif
    case 1:
      #if ENABLED(HEATER_1_USES_AD595)
        return TEMP_AD595(raw);
      #elif ENABLED(HEATER_1_USES_AD8495)
        return TEMP_AD8495(raw);
      #else
	break;
      #endif
    case 2:
      #if ENABLED(HEATER_2_USES_AD595)
        return TEMP_AD595(raw);
      #elif ENABLED(HEATER_2_USES_AD8495)
        return TEMP_AD8495(raw);
      #else
	break;
      #endif
    case 3:
      #if ENABLED(HEATER_3_USES_AD595)
        return TEMP_AD595(raw);
      #elif ENABLED(HEATER_3_USES_AD8495)
        return TEMP_AD8495(raw);
      #else
	break;
      #endif
    case 4:
      #if ENABLED(HEATER_4_USES_AD595)
        return TEMP_AD595(raw);
      #elif ENABLED(HEATER_4_USES_AD8495)
        return TEMP_AD8495(raw);
      #else
	break;
      #endif
    default: break;
  }
```

**Comment by GMagician** [comment]
Thank you for your report, I made a PR for it
