### ISSUE TITLE
Compile fails with LCD_PROGRESS_BAR does not apply to graphical displays.

### ISSUE THREAD

**Issue by DaveAhrendt** [MarlinFirmware/Marlin#10780]
Most recent .zip as of 5/15/

Using the Folger I3-2020 example files untouched it compiles OK.
Uncomment #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER only. This is the only change made to the example files.
Compile fails with:
SanityCheck.h:375: error: #error "LCD_PROGRESS_BAR does not apply to graphical displays."
     #error "LCD_PROGRESS_BAR does not apply to graphical displays."

If you disable SDSUPPORT you can compile but you have no sd support.

**Comment by thinkyhead** [comment]
Try also disabling `LCD_PROGRESS_BAR`.

> Uncomment `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` only. This is the only change made to the example files.

You must also comment out `#define REPRAP_DISCOUNT_SMART_CONTROLLER`.
