### ISSUE TITLE
[2.0.X] BUG? #define POWER_LOSS_RECOVERY - not work correctly

### ISSUE THREAD

**Issue by rockman256** [MarlinFirmware/Marlin#10795]
#define POWER_LOSS_RECOVERY does not work.
After turning the power off and on.
- resume print
The printer warms up the table and hotend, then XY goes home, returns to the print place.
The display shows "Continuation" and everything is on it.
Further printing does not continue.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2020254/Marlin.zip)

**Comment by thinkyhead** [comment]
Yes, there may still be bugs in this new feature. I plan to work on it soon. We have other issues open about it, so I'll just close this one.

**Comment by ShaggyDog18** [comment]
similar here:  however, The printer warms up the table and hotend, then XY goes home and... starts printing there, without going to the last printing position...
