### ISSUE TITLE
eixo x invertido

### ISSUE THREAD

**Issue by CelsoCoelho** [MarlinFirmware/Marlin#10805]
impressora delta com marlin fw está com eixo x invertido, ao clicar x+ a mesma vai para x- , os eixos " z" e "y" estão normais,  com o repetier fw fica normal.

**Comment by braga-dev** [comment]
Hey so the problem this gentleman is saying is that he have the X_AXIS inverted. And the solution is simple so i'm going to translate the solution to him.

Então basicamente tens a direção do eixo de x invertida. Precisas de trocar [aqui](https://github.com/MarlinFirmware/Marlin/blob/9b63430f349f7083d09d2db24d24908e1d277379/Marlin/Configuration.h#L751) para o inverso do que tens. Ou seja se tiveres TRUE  mete FALSE, e se tiveres FALSE mete TRUE.
