### ISSUE TITLE
[FR] EXTRUDER_AUTO_FAN_SPEED from console?

### ISSUE THREAD

**Issue by forkoz** [MarlinFirmware/Marlin#10807]
I bought an 8CFM fan for printing at 250c+. For PLA I don't need all 8cfm. I could not find a command to set the fan speed from the console. Is there not one? It would sure be nice. Or maybe scale the fan with extruder temperature.

**Comment by braga-dev** [comment]
You can use M106 to set fan speed, like "M106 S255" will set the fan speed to his maximum.

I believe new version of Cura does auto scale the fan with the layer height, I dont know if it does with extruder temperature

**Comment by braga-dev** [comment]
I just noticed, are you talking about the piece blower or the extruder fan?

**Comment by forkoz** [comment]
Extruder fan.

**Comment by thinkyhead** [comment]
This feature does not exist at this time.

**Comment by ellensp** [comment]
duplicate of https://github.com/MarlinFirmware/Marlin/issues/10280
