### ISSUE TITLE
FLSUN Kossel Big Size with Heated Bed Auto leveling issue.

### ISSUE THREAD

**Issue by ItsDrunkLuck** [MarlinFirmware/Marlin#10816]
I have just purchased a new 3D Printer and i cant get the thing working. I'm kind of new to all of this but i have a basic understanding of it. the original issue was that when i tried to auto calibrate it, it would just ram the nozzle into the bed. so i downloaded the debug version of the configuration for Marlin  1.1.8, and activated the "DEBUG_AUTO_LEVELING" or something like that. The problem now, is that when i try to run the code "G29" it doesn't move the Y tower motor at all.
Help?

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. Marlin 1.1.8 is getting kind of long in the tooth at this point, and your issue may already be fixed.

**Comment by ItsDrunkLuck** [comment]
@thinkyhead I saw a thread that was created around April 22nd that you posted on, and I followed through with the steps and its not really working.

**Comment by ItsDrunkLuck** [comment]
@thinkyhead i downloaded "Marlin 1.1.x". I extracted the files into a separate Folder. After that i went into to this location: "Marlin-bugfix-1.1.x\Marlin\example_configurations\delta\FLSUN\auto_calibrate" and i copied that config files to the main Marlin folder, replacing the original config files. now, instead of ramming the bed, it contracts against the Y tower.

**Comment by ItsDrunkLuck** [comment]
@thinkyhead sorry im sending  so many, here is a video of what happens. the tower on the far end is my X, the one closest on the left is my Y, and the right is my Z. [https://drive.google.com/open?id=1K7EHEITUWO_LH-1kAv7TMGqdhtFzwkQk](url)

**Comment by thinkyhead** [comment]
What does `M119` say when the carriages are not hitting the endstops? And then what does it say when you trigger each of the endstops? Do they all appear to be working correctly?

**Comment by ItsDrunkLuck** [comment]
I've been messing with it a bit and i got rid of that problem, problem is, now its ramming the bed again. ill send another video. Ill also be sending a video of what happens when it homes on the X and Y, it does one tower at a time and i don't know if it is normal. G28: [https://drive.google.com/open?id=1jBMQ3uZIEtl_M_p1sCNsxHL8lL-XhDBN](url) G29: [https://drive.google.com/open?id=1b3ZSRbm_EyeBHFujfYIM9h0ehtfTwLb0](url)

**Comment by ItsDrunkLuck** [comment]
@thinkyhead

**Comment by ItsDrunkLuck** [comment]
i checked the endstops and they all seem to be working

**Comment by ItsDrunkLuck** [comment]
well no, my Z max is always triggered regardless whether or not the switch is activated.

**Comment by ItsDrunkLuck** [comment]
I have discovered that my Z Max Switch is always triggered. I switched it to X Max and it said X Max was triggered. so i know its a problem with the wire.
This probably isnt a Marlin issue.

**Comment by boelle** [comment]
@ItsDrunkLuck still having an issue if using latest bugfix 2.0?

if its not a marlin issue then maybe hit the green close button below

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
