### ISSUE TITLE
Issues when using K-factor Calibration Pattern in Delta

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#10813]
Hi,
In the delta, "Bed Shape" is set to "Round", but `G1 Z30 Xnn Ynn Fnn ;move away from the print` in "finish" is generate G1 command for Cartesian printer.
For Round it is safe to set it to "G1 Z30 X0 Y0 ".

**Comment by Sineos** [comment]
Thanks for the feedback. Will update.

**Comment by thinkyhead** [comment]
Update merged!
