### ISSUE TITLE
[FR] Tuning Z-offset on LCD Screen

### ISSUE THREAD

**Issue by Fourmi** [MarlinFirmware/Marlin#10835]
Hi,

Possible to make a feature for tuning Z offset on LCD screen ?
i make a google sheet to explain.
[Z-offset Tuning ](https://docs.google.com/spreadsheets/d/1qhyDCcUXyRs7eXB9-S-V7gBr81MqOKYM9TACI3_DAhE/edit#gid=0)

First step already run on my lcd screen, it's for the second .......

thx

**Comment by thinkyhead** [comment]
It's on our TODO list already. Except the procedure would be:
1. Home XYZ, move XY to bed center.
2. User adjusts nozzle until it touches the bed (i.e., paper test)
3. A click sets this as Z=0, then a probe is done at bed center.
4. Z (when the probe triggers) is negated and saved as the Z offset.

**Comment by Fourmi** [comment]
Ok, Nice Thinkyhead ;)

**Comment by thinkyhead** [comment]
I hope it will work well! Setting it manually is such a hassle.

**Comment by boelle** [comment]
@Fourmi did it work?

**Comment by Fourmi** [comment]
Hi @boelle  !
Yes we make a menu on LCD for "touch_MI" sensor , but we don't make  pull request again, i think we can soon .
You can found the firmware on my github here >https://github.com/Fourmi/Marlin_TouchMI
Screenshot of menu >https://gyazo.com/02540dbb34fd0e98b62b86f86808fd57
Now you can tune your Z Offset in 30 seconds & on a single screen ,very easy ;)
Thx

**Comment by boelle** [comment]
could you submit a PR to bugfix 2.0?

**Comment by Fourmi** [comment]
Hum PR  on 1.1.9, i didn"t make on 2.0 but it's possible, but you can do if you want ;)

**Comment by boelle** [comment]
1.1.9 is outdated hence i suggest 2.0.x

no i cant do it, i'm not a code person

**Comment by InsanityAutomation** [comment]
@boelle @shitcreek I believe this is already done as well, and overlaps somewhat with babystepping

**Comment by boelle** [comment]
we can always open it again if its not the case :-D
