### ISSUE TITLE
[1.1] Extruder auto fan is slow/under powered?

### ISSUE THREAD

**Issue by forkoz** [MarlinFirmware/Marlin#10834]
### Description
I have configured extruder auto fan on HE1 like so:
```cpp
#define E0_AUTO_FAN_PIN MOSFET_D_PIN
#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED   255  // == full speed
```
The fan spins but seemingly too slow, I bought extra fast fan and its working just like my old fan.
I checked voltage from the heater pin and its 12.x volts

### Steps to Reproduce

Wire fan to DC power supply.
Wire fan to MKS GenL and use auto fan.

**Expected behavior:** [What you expect to happen]
Equal speed.

**Actual behavior:** [What actually happens]

Marlin fan is slow/quiet, 12v supply fan is faaaaast.

**Comment by MikeLud** [comment]
Forkoz,

I have the same board and have the extruder fan setup the same way and it is working fine. Maybe you have some the wire insulation in the terminal and you are not making a good connection

Mike.

**Comment by forkoz** [comment]
I will check.. I also found 12v power supply was putting out extra volts, like 15-16. That could account for it. Just because it says 12v on the box doesn't mean its 12v :(

**Comment by boelle** [comment]
@forkoz 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
