### ISSUE TITLE
[Bugfix 2.0] Build errors caused by platformio.ini

### ISSUE THREAD

**Issue by TGMods** [MarlinFirmware/Marlin#10839]
### Description

Unable to compile for Re-ARM with platformio.ini as published.

### Steps to Reproduce

I down loaded Bugfix_2.0 (‎24 ‎May ‎2018, ‏‎09:45:19) changed configuration.h to my settings and started the build. I have used both Atom and VS Code with the same result on two different PCs running Windows 10.

**Expected behavior:** [What you expect to happen]

Bugfix_2.0 to build for Re-ARM.

**Actual behavior:** [What actually happens]

Failed almost as soon as it started (see Compile error.txt). After a lot of head scratching I traced it to platformio.ini, line 163
```
extra_scripts   = Marlin/src/HAL/HAL_LPC1768/lpc1768_flag_script.py, Marlin/src/HAL/HAL_LPC1768/upload_extra_script.py
```
Commenting out line 163 resulted in a linker error (see link error.txt).

Changing line 163 to
```
extra_scripts   = Marlin/src/HAL/HAL_LPC1768/upload_extra_script.py
```
allowed the build to complete with no errors.

#### Additional Information

I used the modified platformio.ini to upload the new firmware to my Re-ARM and I'm currently printing with it on my HyperCube.

[Config and error reports.zip](https://github.com/MarlinFirmware/Marlin/files/2035952/Config.and.error.reports.zip)

**Comment by Bob-the-Kuhn** [comment]
Something changed in Windows and **upload_extra_script** no longer works


Please try the attached file.  It uses a different method of getting the info.  It runs on my Win10 machine.


[upload_extra_script.zip](https://github.com/MarlinFirmware/Marlin/files/2037424/upload_extra_script.zip)

**Comment by thinkyhead** [comment]
I'd tell the PlatformIO developer to stop changing things, but whenever I point at others I can't help notice I've got 4 fingers pointing back at myself.

**Comment by TGMods** [comment]
@Bob-the-Kuhn @thinkyhead Thanks guys, that fixed it.
