### ISSUE TITLE
Marlin bubfix 1.1.x No more access to the printer menu (Creality CR-10)

### ISSUE THREAD

**Issue by Hebign** [MarlinFirmware/Marlin#10830]
Hello,
Since I installed this version, I can not access the menu of my creality cr-10.
The display of the screen is normal, I can vary the flow via the main button of the box, but when I click on it, nothing happens, no more access to the menu.
I do not know if I missed something, but I find no solution.
The printer prints normally otherwise.

**Comment by viper93458** [comment]
I had the same issue yesterday in the 2.0 bugfix and downloaded the 2.0 bugfix from today and the issue went away. I imagine it was resolved for 1.x bugfix too.

William

**Comment by Hebign** [comment]
Thank you William for the info.. I'll try again

**Comment by thinkyhead** [comment]
It was a typo. Should be fixed. Cheers!

**Comment by Hebign** [comment]
Yes, tested today, fixed ! Thanks
