### ISSUE TITLE
FLSUN Delta G33 Escalates Quickly

### ISSUE THREAD

**Issue by Floppynator** [MarlinFirmware/Marlin#10842]
Hi Guys,

you are my last hope. i have a Flsun Delta and i dont get G33 runs well. No matter wich Firmware i use. In this case i used 1.1.x-bugfix branch.

I think a video says more than 1000 word.. look here. 
G28 Works well, also G1 Z10 F5000 for example
https://youtu.be/vPvUQfIGAH0 

Here you can see what happened i run G33 after G28
https://youtu.be/yyxTxGpoCMQ

any ideas whats happened? i tryed another driver but have the same issue. also with Marlin 1.1.8

please help me :(

**Comment by Floppynator** [comment]
AUTO_BED_LEVELING_UBL and AUTO_BED_LEVELING_BILINEAR also do the same :(

**Comment by Floppynator** [comment]
oh wow, now i get it. After 6h of pain.
The Spring from mech. z-enstop probe are loose and there triggered random z-min...

holy moly

**Comment by thinkyhead** [comment]
The important thing is that it's not _my_ fault. Thanks for the update!

**Comment by Floppynator** [comment]
Shure. But it would be Nice the Printer Not run over the printable Max and stop his movement :) Look at the Second Video, i Hit the panic Button. Otherwise the effector brake off :)

**Comment by thinkyhead** [comment]
Let's ask the author his opinion…

@LVD-AC — What do you make of the second video?

**Comment by Floppynator** [comment]
G33 Delta Autocalibration
