### ISSUE TITLE
[2.0.x-bugfix] bug with Reprapdiscount display

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#10863]
Hello,

After compile latest bugfix, using non graphical reprapdiscount display, it is impossible to see anything:

![whatsapp image 2018-05-26 at 14 57 45](https://user-images.githubusercontent.com/15361590/40579029-7473bad6-60f5-11e8-977e-060fb1647122.jpeg)

config files:
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2041853/Marlin.zip)

**Comment by ejtagle** [comment]
@mtmello2003: Should be fixed by #10864 , once pushed. If you want to try it, please do and report if it fixes the problem for you  👍

**Comment by MasterPIC** [comment]
My Anet A8 was totally bricked too.
To be able to revert to a previous working firmware release I had to upload the firmware before the screen became corrupted (just within a few seconds from a power cycle). In a few words a few seconds after power up I had "not in sync" errors while trying to flash the working firmware and printer communication not working...
I'm going to try #10864 ...

**Comment by MasterPIC** [comment]
I confirm screen is fixed and the printer seems to be working as expected thanks to #10864

**Comment by mtmello2003** [comment]
Yes, solved the issue!

Tks

**Comment by Roxy-3D** [comment]
I merged it so we don't get people confused...   

Thank You @ejtagle

**Comment by boelle** [comment]
@mtmello2003 if issue is solved then maybe hit the green close button below

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
