### ISSUE TITLE
Add "Calibration Procedures" to the firmware

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#1086]
I would like to suggest adding some standard calibration procedures added to Marlin firmware, to do the sorts of things we need to do frequently. Off the top of my head:

- Loading, ejecting, and changing filament
- Measuring and setting axis steps
- Measuring and setting extruder steps
- Tuning ideal speed + acceleration + jerk settings
- Manual bed leveling
- Determining ideal temperature for materials
- Calculating heater hystereses
- Tuning motor voltages

I suggest implementing these as optional add-ons in their own files for different varieties of robot, since each one will need its own terminology and procedure. These will make good reference code for vendors who want to add their own setup and calibration menu for novice end-users, especially those building from kits.

**Comment by Nandox7** [comment]
Are any of these planned to be added.
I particularly miss the: Loading, ejecting, and changing filament

I'm using the bQ fork of the firmware that has it and is super handy.
Maybe worth pulling from them the code for it?

**Comment by thinkyhead** [comment]
@Nandox7 Check out the `FILAMENTCHANGEENABLE` setting.

**Comment by Nandox7** [comment]
@thinkyhead thanks. But it's not quite the same. As far I've seen it only gets enabled after you initiate a print.
It would me much handier to have it in the "Prepare" menu as load/unload filament.

**Comment by paclema** [comment]
Some time ago, I make this PR with this changes now implemented on bq fork:
https://github.com/MarlinFirmware/Marlin/pull/943
Se here anexample:https://youtu.be/aDPXX78EvQ4?t=134

**Comment by thinkyhead** [comment]
Aha. For some reason I thought it must already have been in the Prepare menu. Definitely should be there as an option!

**Comment by thinkyhead** [comment]
@paclema I like the M700-M702 codes. In general I think it's always best when new options, like filament change or other utilities, come with a menu option and some GCode, to provide the most control options. Good work!

**Comment by paclema** [comment]
Ty @thinkyhead ! If you want, I can code it again to make a new PR.. or if i can help in other way just tell me ;)

**Comment by Nandox7** [comment]
Cool. It would be great if the full workflow would be merged.
Is not seen in the video but the normal workflow is to ask for a temperature and wait for the heating to happen before inserting the filament, making it compatible with any filament type. 
(not just PLA as seen in the video)

**Comment by thinkyhead** [comment]
@paclema A pull request against the current Development branch is definitely the way to go. Then we can see how `FILAMENTCHANGEENABLE` fits in, or whether this has everything needed to just supersede it.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
