### ISSUE TITLE
[1.1.x-bugfix] bug with sdcard support

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#10862]
Hello,

Using the tag:
```cpp
#define SDSUPPORT 
```
with REPRAP DISCOUNT (non graphical display) got compile error:
```
In file included from sketch\MarlinConfig.h:26:0,

                 from sketch\Sd2Card.cpp:29:

Sd2Card.h:100:39: error: pasting "/* SPI Master In Slave Out pin*/" and "_DDR" does not give a valid preprocessing token

   #define SPI_MISO_PIN MISO_PIN       // SPI Master In Slave Out pin
```
config files:
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2041829/Marlin.zip)

**Comment by ejtagle** [comment]
@mtmello2003 : This a bug of the C preprocessor that some Arduino and some PlatformIO environments are using. Just remove the comments (```//``` onwards) and it will compile and work

**Comment by mtmello2003** [comment]
That´s weird! I did as you recomended and it worked!

Tks

**Comment by jhoblitt** [comment]
I saw this error with 1.8.6 but it went away after upgrading to `1.8.7`.

**Comment by paul29163** [comment]
> @mtmello2003 : This a bug of the C preprocessor that some Arduino and some PlatformIO environments are using. Just remove the comments (`//` onwards) and it will compile and work

Great, completed as stated and compiled with no issues, Thanks.

**Comment by disappear123df** [comment]
> @mtmello2003 : This a bug of the C preprocessor that some Arduino and some PlatformIO environments are using. Just remove the comments (`//` onwards) and it will compile and work

where do i find the (`//` onwards)
