### ISSUE TITLE
Servomotor is shaking with G28

### ISSUE THREAD

**Issue by hevilp** [MarlinFirmware/Marlin#10878]
### Description

Servomotor is shaking random when homing (G28)

### Steps to Reproduce

1.  I set #define NUM_SERVOS to 1  and connected my Servomotor (HS-225MG )
2. Send G28

All axis goes to home, but the Servormotor is shaking around

If I do not home, the motor works nice with M280

Why does it shakes and struggles 
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2042880/Configuration.txt)
when I use G28?

**Comment by GMagician** [comment]
What's the servo purpose?
No BLTOUCH, SWITCHING_EXTRUDER, SWITCHING_NOZZLE
Sure it's not EMI noise?

**Comment by hevilp** [comment]
SWITCHING_EXTRUDER is the purpose, I commented it again, even with SWITCHING_EXTRUDER enabled it is shaking.

For debugging I just commented it again.

**Comment by GMagician** [comment]
If you try to move steppers? what happens

**Comment by hevilp** [comment]
The x y z moves normal, jittering is still there

**Comment by GMagician** [comment]
So issue is present when you move axes, not home as a command...emi noise I think

**Comment by hevilp** [comment]
I connected the servo now on 5V on the MKS GEN L and got no problems, before they got the power direct from the PSU (lowered to 5V)

**Comment by GMagician** [comment]
The problem was differential in potential on GND I suppose
