### ISSUE TITLE
[2.0.x] Building multiple configurations at once

### ISSUE THREAD

**Issue by waddyano** [MarlinFirmware/Marlin#10877]
I am sure I could come up with some approach of my own but I wondered if there was a suggested technique of easily building multiple configurations at once e.g. same platformio environment but different Configuration.h?

**Comment by Bob-the-Kuhn** [comment]
PlatformIO actually tries to compile every environment in platformio.ini.  It just skips the ones that don't apply to the specified target.

In theory you could set a flag in each environment and then a bunch of #if statements could make the selections.  You'd also need to modify the build folder for each flavor.

With PlatformIO it's like a dog walking on its hind legs, not pretty or effiicent but it can be done.

You're better off going with Visual Studio **Community**.  It's designed for what you're wanting to do.

**Comment by waddyano** [comment]
Thanks for the reply hadn't had time to comment earlier. Indeed the way I did it so far is to create a new environment with an extra compile switch and #ifdefs. I actually didn't realize that you could use full visual studio - currently using VS Code or often the command line but have just looked at what sort of project it creates. It is just a makefile based project that drives the pio command line so not really that much different. Now I am very used to visual studio for editing - more so than vs code - but  "platformio init --ide" doesn't seem to do a good job of creating a sensible header and source folder structure inside the solution - maybe I will try and write a script to organize the project/solution better.

**Comment by boelle** [comment]
@waddyano 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
