### ISSUE TITLE
random layer slides 

### ISSUE THREAD

**Issue by istyszy** [MarlinFirmware/Marlin#10876]
Hello, 

I have upgraded my AnetA8 printer with Ramps + tmc2130 drivers for all steppers.
I have the sensor less homing  enabled for X and Y.
In the flowing link are some photos.
[ Link Photo ](https://drive.google.com/file/d/1BQJ6CXWWJZXi2Fzy8gsjAbF9GFmSQwk1/view?usp=sharing)

 I tried with 
          - The latest release (1.1.8)
          - The daily bugfix build (CONFIGURATION_H_VERSION 010109) 

Anyone have any ideeas?
Thnek you!

**Comment by ArtieFM** [comment]
Add active Cooling for the drivers (Fan) and crank up the current, switch between Stealthchop and Spreadcycle. Make it work on 1.1.8 before you switch to Bugfix. This issue is also discussed in https://github.com/MarlinFirmware/Marlin/issues/10446

**Comment by larsnordstrom** [comment]
I have been working with these 2130 for some time and there are alot of factors that could cause this.
Too high or too low current, too high causes the motors to get too hot and **lose** steps, too low make them have too little torque. Acceleration is another cause for this problem, jerk is too.
Homing sensitivity too for some reason, hybrid threshold can cause issues too.

I use stock A8 motors with genuine 2130 so we have a pretty similar setup, you can try these values and they should work as startingpoint:
**Config**
```cpp
#define DEFAULT_ACCELERATION          400 
#define DEFAULT_RETRACT_ACCELERATION  1000
#define DEFAULT_TRAVEL_ACCELERATION   1000 
#define DEFAULT_XJERK                 7.0
#define DEFAULT_YJERK                 7.0
```
**Config adv.**
```cpp
#define X_CURRENT          630  
#define X_MICROSTEPS        16 
#define Y_CURRENT          630
#define Y_MICROSTEPS        16
#define Z_CURRENT          600
#define Z_MICROSTEPS        16
#define Z2_CURRENT         600
#define Z2_MICROSTEPS       16
#define E0_CURRENT         400
#define E0_MICROSTEPS       16
#define X_HYBRID_THRESHOLD     130 
#define Y_HYBRID_THRESHOLD     130
#define Z_HYBRID_THRESHOLD      10
#define Z2_HYBRID_THRESHOLD     10
#define E0_HYBRID_THRESHOLD     40
#define X_HOMING_SENSITIVITY  14
#define Y_HOMING_SENSITIVITY  14
```

**Comment by istyszy** [comment]
Hello, last night i tried one more print, and i noticed my steppers for X and Y axis where getting very hot, so i decided to start fresh. 

Previously i had `MONITOR_DRIVER_STATUS` disabled.

I have Ramps + tmc2130 (for all steppers X/Y/Z/E0) and an SD card reader. [Sd card link ](https://www.tindie.com/products/mmm999/micro-sd-card-reader-module-for-arduino/)

Now i have `MONITOR_DRIVER_STATUS` enabled and i am getting Driver error PRINTER HALTED Please reset. If i remove the SDcard reader there are no errors. 

I found someone had a  similar problem **#10133** and i tried to modify the TMC drivers to:
```cpp
SPI.beginTransaction(SPISettings(16000000/8, MSBFIRST, SPI_MODE0));
```
and there is still the same problem.

Any **ideas**?

**Comment by larsnordstrom** [comment]
@istyszy Don't overcomplicate things, lower the current and acceleration. These cheap Anet steppermotors are only rated for 900mA, mine are atleast. So running at 600-650 is all you can run. I found 600-630 to be the sweetspot and 400 for the extruder(I'm using bowden with bondtech).

**Comment by mbuc** [comment]
If you don't already have some, add heatsinks to the tops of each TMC2130.  Have a decent fan blowing across the entirety of it.  I have a 120mm fan next to my RAMPS board with a good path for airflow.

You can also add heatsinks on the bottoms of the driver boards if you lift them up on some dupont connectors.
