### ISSUE TITLE
BLTouch Not Deploying

### ISSUE THREAD

**Issue by osdcommand** [MarlinFirmware/Marlin#10899]
I'm having an issue with my BLTouch sensor, and getting it to run on Marlin. I have a ramps 1.4 board, with a 550W ATX power supply. I can't get my BLTouch to deploy, be it using the manual commands, or the auto leveling feature. I've set up the firmware as specified in the manual. I've triple checked the connections to the servo and z endstop pins, but that doesn't seem to be the issue. Whenever I try to deploy or store the pin, the LED goes from a dim blue to a slightly darker blue, and won't "trigger", even when I pull the pin out manually. What am I doing wrong?

**Comment by thinkyhead** [comment]
Do you have the servo ~~12V~~ 5V jumper installed on the board?

**Comment by osdcommand** [comment]
I'm not entirely sure what that is, so I'd have to assume not. What is that, and what does it do? I'm a bit new to working with auto leveling.

**Comment by thinkyhead** [comment]
There's a 2-pin header usually, right next to the servo connectors. It requires a jumper to be installed on it or there will be no power supplied to the servo connectors.

**Comment by osdcommand** [comment]
I don't see one on my ramps 1.4, and I can't really find any diagrams online for it either. Do you have a picture of yours, by any chance?

**Comment by kAdonis** [comment]
this jumper supplies 5V to the servo connectors:
![image](https://user-images.githubusercontent.com/35379348/40812044-1fc46ec0-6534-11e8-86c6-b3b2962a4802.png)

**Comment by osdcommand** [comment]
It works now, you guys are the best. Thank you again!
