### ISSUE TITLE
M914 - TMC Bump Sensitivity values not applied correctly/value-range not as intended

### ISSUE THREAD

**Issue by dw-0** [MarlinFirmware/Marlin#10896]
I guess the two pictures describe the problem best:
![screenshot8](http://puu.sh/Avbjk/f6fcd11ed2.png)
![screenshot9](http://puu.sh/Avbju/a88a5fc688.png)

In the marlin documentation you give a range from -63 to +64 which is actually wrong:
http://marlinfw.org/docs/gcode/M914.html

You have a range from **-63** to **+63**.
If you put in **-64** it automatically sets the value to **-63**.
If you put in **+64** it sets the value to **-64**, which should actually not even be possible.

**Comment by teemuatlut** [comment]
The correct range is -64..+63, but you're right that there's a bug in `M914` and the documentation needs to be corrected as well.

**Comment by dw-0** [comment]
Ah yes sorry, of course the range is -64 to +63. :)
