### ISSUE TITLE
Need help reading second extruder position.

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#10905]
I've noticed that the code for updating my color LCD is not working properly with dual-extruder printers. It seems like half of the problem was that I was assuming destination[] had individual values for each extruder, but this is not the case. The best I can make of it, it looks like I have to change the active_extruder, so I changed the code in the setter in the Extensible_UI_API to the following:

```
  void setAxisPosition_mm(const axis_t axis, float position, float _feedrate_mm_s) {
    #if EXTRUDERS > 1
      const int8_t old_extruder = active_extruder;
    #endif
    switch(axis) {
      case X:
      case Y:
      case Z:
        break;
      case E0: active_extruder = 0; break;
      #if EXTRUDERS > 1
        case E1: active_extruder = 1; break;
        #if EXTRUDERS > 2
        case E2: active_extruder = 2; break;
          #if EXTRUDERS > 3
          case E3: active_extruder = 3; break;
          #endif
        #endif
      #endif
      default: return;
    }
    set_destination_from_current();
    switch(axis) {
      case X:  destination[X_AXIS] = position; break;
      case Y:  destination[Y_AXIS] = position; break;
      case Z:  destination[Z_AXIS] = position; break;
      case E0: destination[E_AXIS] = position; break;
      case E1: destination[E_AXIS] = position; break;
      case E2: destination[E_AXIS] = position; break;
      case E3: destination[E_AXIS] = position; break;
    }

    float old_feedrate = feedrate_mm_s;
    feedrate_mm_s = _feedrate_mm_s;
    prepare_move_to_destination();
    feedrate_mm_s = old_feedrate;
    #if EXTRUDERS > 1
      active_extruder = old_extruder;
    #endif
  }
```

Now, the second half of the equation is to make the getter work. Right now I have this:

```
  float getAxisPosition_mm(const axis_t axis) {
    switch(axis) {
      case X:  return current_position[X_AXIS];
      case Y:  return current_position[Y_AXIS];
      case Z:  return current_position[Z_AXIS];
      case E0: return current_position[E_AXIS];
      case E1: return current_position[E_AXIS+1];
      case E2: return current_position[E_AXIS+2];
      case E3: return current_position[E_AXIS+3];
      default: return 0;
    }
  }
```

This has the same problem as the setter, however, because it appears as if current_position[] doesn't have entries for the additional extruders. If I merely change "active_extruder", the values are not going to magically appear in "current_position[E_AXIS]" ... I would have to call something to populate that value. I have no idea what that might be and trying to figure it out by reading "ultralcd.cpp" isn't helping.

Thanks in advance for any tips!

-- Marcio

**Comment by thinkyhead** [comment]
Correct. Slicers and Marlin regard multiple extruders as a single axis, and quite often reset the E position to zero between layers. If you want to accumulate the E movement for one or multiple extruders, you’ll need to add up all E movement (forward and backward) as it arrives and store in a separate accumulator array. Note that these accumulated values may have nothing to do with the actual value of the (single, active) E axis. That is, you wouldn’t be able to use that value in a G1 command, for example.

**Comment by marcio-ao** [comment]
@thinkyhead: Okay. It looks like it does not make sense to show separate values for the different extruders in the UI. We've decided to just show one value, as in the Ultralcd code.
