### ISSUE TITLE
CONTROLLER_FAN already running on pre-heat?

### ISSUE THREAD

**Issue by insanity67** [MarlinFirmware/Marlin#10908]
Hi!

I use USE_CONTROLLER_FAN on the latest bugfix, and noticed that the controller fan kicks in if I only preheat via the Prepare menu. Shouldnt it be only running if a stepper moves? Marlin comment says "The fan will turn on automatically whenever any stepper is enabled"

Thank you!

**Comment by tig33r** [comment]
I think description is little wrong because controller fan should work with bed/head heating to cool mosfets in controller board.

**Comment by insanity67** [comment]
OK that makes sense, thank you!
