### ISSUE TITLE
[2.0.x] Case Light  vs LED Control contrary behavior

### ISSUE THREAD

**Issue by mr-miky** [MarlinFirmware/Marlin#10917]
In Main menu / case light / Case Light : Off , press the encoder and the word changes to ON and the light turns ON, so the menu item shows the current lighting status.
In Main menu / Led Control / Lights Off , press the encoder and the word changes to ON and the light turns off, so the menu item shows the next lighting status. 

It is probably the case to standardize behaviors.

**Comment by Bergerac56** [comment]
I confirm. This is the case since a long time...

**Comment by GMagician** [comment]
This should me fixed..please close if confirmed

**Comment by mr-miky** [comment]
I'll check out tonight

**Comment by mr-miky** [comment]
I checked with the oscilloscope and now the behavior is the same for both menu items so that's fine.
