### ISSUE TITLE
[2.0.x]  Case Light + LCD menu, build fails 

### ISSUE THREAD

**Issue by mr-miky** [MarlinFirmware/Marlin#10915]
I connected the "case light" to an output and enabled the lcd menu to control it.
In `fastio_STM32F4.h`, `USEABLE_HARDWARE_PWM` is missing and the compilation fails.

Just add to `fastio_STM32F4.h` `#define USEABLE_HARDWARE_PWM(p) 1` since the implementation of the PWM made in Stm32Generic allows all pins to operate in PWM out.

NB `stm32_PWM.c` of `STM32Generic` is buggy.  See comments of @ktand in issue #10787.

**Comment by thinkyhead** [comment]
Added `USEABLE_HARDWARE_PWM` to `fastio_STM32F4.h`.
