### ISSUE TITLE
[1.1.x bugfix] Noisy motors with the TMC2208

### ISSUE THREAD

**Issue by Seref** [MarlinFirmware/Marlin#10924]
I have the Ramps 1.4 board and the TMC2208 and for some reason the TMC2208 started making the high pitched noise, I'm not sure why before switching to the Ramps I used the Anet board and soldered the cables from the stepper to the board (I used Marlin 1.1.8 then) and the stepper driver just worked fine.

I also rolled back to 1.1.8 without any improvements :(

**Comment by teemuatlut** [comment]
Does the communication to and from the drivers work?
