### ISSUE TITLE
Feature request: Specify different maxspeeds for raising and lowering z-axis

### ISSUE THREAD

**Issue by scottlawsonbc** [MarlinFirmware/Marlin#1092]
#### Current problem
Z-axis motor(s) are often under more load when raising the z-axis when compared to lowering the z-axis.

This load difference varies from negligible to quite significant depending on the lead screw choice and the mass that must be lifted (as well as many other factors). Because of this load difference, the z-axis travel speed must be limited to the max speed of the direction experiencing the highest load. 

I tested this on my printer by finding the maximum speed without skipping in both directions. For my particular printer, the maxspeed when lowering was 1.8 times higher than the maxspeed when raising.

#### Proposed feature
I propose adding the ability to specify a different maxspeed for raising and lowering the z-axis. This option will permit printers to move faster when lowering the z-axis.

This will reduce the time needed for a print to begin by several seconds, and reduce the time needed to perform a restart if the print fails on the first layer. The benefit is relatively minor and would likely require minimal changes to the code.

**Comment by orangeudav** [comment]
+1

**Comment by bkubicek** [comment]
I think its more useful to have acceleration and deceleration a separate
value.
if gravity does not shift your axis, when the tilt the printer 90 degree,
as in most printers i have seen,
you deceleration is 9800 mm/sec^2.
Yes,thats not entirely correct, as moving friction is different from
holding friction. But then again, if you tip the axis to move, and it stops
by itself, very very quickly, we are in the same region.

Much more complex, a rpm-dependent acceleration would be very nice. But
very difficult, as it would destroy the linear acceleration/deceleration
profiles.

Bernhard

**Comment by nophead** [comment]
A stepper motor has more torque at lower speeds. That is far more significant than static versus dynamic friction. So the maximum speed is less when working against gravity, which means having different accelerations will not fix the problem on its own. It also means just because it can hold the axis against gravity doesn't mean it can decelerate at the same rate from high speed.

**Comment by scottlawsonbc** [comment]
I've plotted the minimum lead screw torque needed to raise or lower a vertically mounted load. The values are for `load=2kg`, `lead screw diameter = 10mm`, and `friction coefficient μ=0.15`. The physics behind the calculations can be found [starting on page 9 of this write-up on power screws [pdf]](http://nptel.ac.in/courses/112105125/pdf/module-6%20lesson-1.pdf).

![image](https://cloud.githubusercontent.com/assets/2927085/5946929/4183bcee-a6ee-11e4-8abc-92a1dd9de467.png)

As pitch increases, we would expect the lowering torque to fall until it becomes negative, at which point the lead screw system is back-driven by gravity and the motor must actively support the load when idle.

For a given lead screw pitch, diameter, and coefficient of friction, we can compute the ratio of raising torque `T_r` to lowering torque `T_l` as:

`T_r / T_l = (cosθ + μsinθ) / (cosθ - μsinθ) * (μcosθ + sinθ)/(μcosθ - sinθ)`

where `θ = arctan(pitch / (π * diameter))` and `μ = coefficient of friction`

We could potentially use the ratio `T_r / T_l`, to compute separate limits for up/down travel speed of the Z-axis (with some safety margin). To compute these values automatically, the pitch, diameter of lead screw, and coefficient of friction would need to be specified in Marlin.

**Comment by Grogyan** [comment]
I would have to disagree.
As most home built 3D printers use threaded rod, which is not absolutely concentric down it's entire length, also the material at which people use for their lead screws makes a huge difference, plus the friction coefficient between the lead screw and the nut material, all needs to be taken to account.
All modern printers have virtually negligible torques, as this is essentially a worm driven system anyways capable of virtually infinite torque.
Here, the feed rates, which is set in firmware as a maximum value is what might need to be tweaked, if any (my Sells Mendel needs that tweaking, but this is an isolated design case).

**Comment by scottlawsonbc** [comment]
@Grogyan who are you disagreeing with?

**Comment by AnHardt** [comment]
Am 28.01.2015 06:59, schrieb Bernhard Kubicek:

> I think its more useful to have acceleration and deceleration a separate
> value.

Hello Bernhard.
How much, do you think, can this speed up 3D-printing? I suppose the
time my z-axis is moving is less then 0.1 %. Ok, with ABL its moving
constantly - but slooooow. So even if you can increase the z-Speed by
two - the win in print-time can only be 0.1 %.

Is this worth the effort?

Andreas

**Comment by nophead** [comment]
I overlap the lowering and raising of the Z axis with the bed heating and cooling so it has zero effect on the total build time. It would make aborting prints and calibration and testing a bit faster, that's all.

**Comment by thinkyhead** [comment]
Anecdote: My X axis is barely moved by gravity because it uses PLA bushings and there's a little bit of binding. However, this seems to improve my print accuracy in X because there's zero play and zero backlash. I don't worry about the X motor working too hard because it manages fine, and stepper motors always put out lots of torque.

**Comment by boelle** [comment]
i also give this the thumb down... it will not add anything... 

in fact i will risk my neck on this one and close it.... the work required to implement it is far bigger than the advantage and it will not benefit enough people
