### ISSUE TITLE
Einsy Rambo MMU Question

### ISSUE THREAD

**Issue by Sloppsta** [MarlinFirmware/Marlin#10926]
Hey guys, Sorry to bug you, but I have the Einsy Rambo and just preordered the MMU 2.0 upgrade to go on a hypercube style printer I am building. My question is this.
Looking at pins_einsy.h i see that E_MUX2_PIN is pin 78, but looking at the einsy rambos schematics, pin 78 is not connected.
<img width="661" alt="capture" src="https://user-images.githubusercontent.com/32474335/40887434-a50774d6-66fd-11e8-9dac-f8f59b5011c0.PNG">

Am I just looking at this wrong?

Thanks
```cpp
// Průša i3 MK2 Multiplexer Support
//
#define E_MUX0_PIN         17
#define E_MUX1_PIN         16
#define E_MUX2_PIN         78   // 84 in MK2 Firmware, with BEEPER as 78
```

**Comment by 3d-gussner** [comment]
@Sloppsta Made a pull request https://github.com/prusa3d/Prusa-Firmware/pull/182 in the past for the Prusa MK2 branch this and other PRs never made it into the MK3 branch.
The E_MUX2_PIN stayed from the early MMUv1 super switch stage.
As the MMUv2 has a own ATmega2560 controller board with 3x TMC2130 drivers i expect that it will be serial communication between the EINSY (P3 pin 3/5 TX2/RX2) and MMUv2 board. With 5 filaments in MMUv2 it will be hard to squeeze that in 2-bit (MMUv1) ...maybe they are doing something else ... we will see.
Hope that helps

**Comment by amoose136** [comment]
I have one on the way that should arrive sometime late this month or next and will be in the same boat as far as getting it working with Marlin goes.

**Comment by Sloppsta** [comment]
I will probably not recieve mine until October.  Maybe someone smarter than myself can help bring the new mmu into marlin!

**Comment by boelle** [comment]
@Sloppsta 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
