### ISSUE TITLE
With Thermal Protection turned off...   MINTEMP BED shutdown still happens...

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#10921]
I'm messing with a Re-ARM / RAMPS board combo that isn't plugged into a printer.

It would seem to me, with Thermal Protection turned off, it shouldn't halt with a 

Err: MINTEMP BED 
PRINTER HALTED

message.    A couple of #ifdef's will fix this...  But I'm thinking it would be best to factor in everybody's thoughts on this prior to making the change.

**Comment by thinkyhead** [comment]
`MINTEMP` / `MAXTEMP` are always enabled, and respond to disconnected or shorted thermistor wires that return clearly impossible temperatures.

**Comment by Roxy-3D** [comment]
And as it turns out...
```cpp
#define BOGUS_TEMPERATURE_FAILSAFE_OVERRIDE
```
Will shut them down if needed.
