### ISSUE TITLE
[2.0.x] Disabling and re-enabling ABL during print causes Z miscalculation

### ISSUE THREAD

**Issue by zeleps** [MarlinFirmware/Marlin#10929]
### Description

This was first detected in the tool_change() function (tool_change.cpp @ line 384), but seems to be a broader issue with disabling ABL mid-print.

My setup has two bowden exrtuders / two fixed hotends, and I'm using the HOTEND_OFFSET_X/Y macros to reposition the gantry after a issuing a Tx code (X=29.4, Y=-0.4 for the second hotend). I'm using bilinear ABL (5x5), which works great when printing with a single material. I'm also using Z_PROBE_OFFSET_FROM_EXTRUDER = -0.45.

When ABL is enabled, the T0/T1 code causes the newly selected hotend to start at a lower Z than it should (my estimation is ~0.1mm lower), causing both hotends to collide with the print. This happens on every tool switch operation, so the print is messed up. After a few layers (all layers including a tool change op), the problem is obvious, as the inactive hotend irons the print, while the active one overextrudes, and the total height of the print is approximately half of what it should be.

A deeper search led me to comment out tool_change.cpp lines 384 and 427 (both set_bed_leveling_enabled() calls), which eliminated the problem. Then I tried to disable / re-enable ABL from the slicer's entry / exit code for the extruder (using M420 S0/1), which caused the problem to reappear.

Please note that during the problematic print, the display shows the correct Z value (what it's supposed to be), but the actual position of the hotend is visibly lower than that.

I haven't had a chance to perform more tests or debug the planner code, but can do upon request. I suspect that the problem will reproduce in a single material print if I include a M420 S0/1 pair on layer change, but I didn't have a chance to try it yet.

### Steps to Reproduce

1. Configure firmware managed position of the gantry (HOTEND_OFFSET_X/Y macros). Enable bilinear ABL.

2. Start a dual print ([this](https://www.thingiverse.com/thing:533814) is a good and brief example, but I've tried some more with the same results) with ABL activated (include M420 S1 in the slicer's start GCode).

3. On the first tool change, you'll notice that the active hotend is lower than it should be and that the print is pressed against the print surface and overextruding.

4. By the end of the print, the model is messed up and is almost half the height it should be.

5. Try the same print without activating ABL (use M420 S0), and the problem disappears. Alternatively, comment out tool_change.cpp lines 384 and 427.

**Comment by zeleps** [comment]
Update: looking at older problematic prints, which were made with Z_PROBE_OFFSET_FROM_EXTRUDER = 0.18, the height problem was evident but not as severe. This might be a lead, but I cannot confirm it at the moment, as this was not the only change I've made since then.

**Comment by zeleps** [comment]
Update: I ran a single material print with M420 S0 / S1 pairs between layers, with and without moving the printhead while ABL was inactive, but the problem did not appear. So far, the problem has appeared only when the tool_change() function is used.

**Comment by boelle** [comment]
@zeleps is this still an issue?

**Comment by zeleps** [comment]
@boelle I haven't really checked it recently; I'll do some tests (probably this weekend) and come back.

**Comment by zeleps** [comment]
@boelle I tried a couple of tests with the latest changeset, and it seems that the issue is now resolved. You can close this item.

**Comment by boelle** [comment]
:-D
