### ISSUE TITLE
[2.0.x] Some strange compile warnings

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#10932]
While compiling I get these strange warnings...is it normal?

1>Warning! Ignore unknown `build_dir` option from `[platformio]` section
1>Detected non-PlatformIO `board_build.f_cpu` option in `[env:megaatmega2560]` section
1>Detected non-PlatformIO `monitor_speed` option in `[env:megaatmega2560]` section

**Comment by p3p** [comment]
PlatformIO likes changing config keywords, (which is expected on a maturing service), as a rule we only support the newest version as that is what is auto-downloaded by the IDE updater. These keywords are valid on the current 'stable' and 'latest' versions.

**Comment by GMagician** [comment]
Upgraded and solved, thanks
