### ISSUE TITLE
[2.0.x] X_DUAL_ENDSTOP Problem with X2

### ISSUE THREAD

**Issue by viper93458** [MarlinFirmware/Marlin#10936]
### Description

Similar to issue 10897, I am seeing problems with the X2 stepper in the dual stepper config. Y is working properly. I am not using dual Z. When homing X with dual X endstops configured, when either the X1 or X2 motor hits the endstop, both motors stop and the second motor doesn't continue on to hit the endstop. If I then manually trigger the second endstop (The one that hasn't yet triggered), the gantry will back up like normal and move forward again (bump) but again, as soon as the first endstop is hit, the whole axis stops moving so that the second endstop isn't hit. At this point, the motor that hit the first endstop will stay engaged, but the second motor never locks but instead stays free to manually move that side of the gantry (even if I manually trigger the second endstop).

I can move the axis using the host software at this point but it is ever so slightly skewed. The software MAX endstops are observed.

M119 shows both endstops triggering properly when manually triggering.

Again, the Y axis works as expected and the config for both dual X and dual Y are identical from what I can tell.

### Steps to Reproduce

Download the latest bug fix-2.0.x from 6/4/18 at 9:20PM
Configure using my attached configuration.h and configuration_adv.h
Setup dual endstops on the X using XMIN and XMAX endstops on the RAMPS 1.4 and AVR
Home X and observe that the second endstop doesn't work as expected. 

**Expected behavior:** [What you expect to happen]
When the first endstop triggers, the second motor continues on till hitting the second endstop and then the gantry will back off per the bump values and trigger both endstops again at which point the machine will consider itself homed.

**Actual behavior:** [What actually happens]
See the description above.

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/2070838/Configs.zip)

**Comment by viper93458** [comment]
Just  checking in to see if anyone has any thoughts on this one? I know everyone is busy with much higher priority work, just hoping someone who may have developer level knowledge of the endstop code might have some ideas. :)

Keep up the great work!

-William

**Comment by thinkyhead** [comment]
We seem to have a general dual endstops bug. See #10897, for example. This is probably due to recent changes to the endstops code by @ejtagle. I merged the code to get it tested and shake out the bugs. Evidently there are still bugs to shake out.

**Comment by viper93458** [comment]
Problem appears resolved as of recent bug fix updates. I loaded a version from a few hours ago and all seems well now. Thanks!
