### ISSUE TITLE
STM32F4 hardware question

### ISSUE THREAD

**Issue by mr-miky** [MarlinFirmware/Marlin#10940]
I'm making a board to control my 3d printer. The board should mount a stm32f4 but I need a clarification.
The doubt that I have is if it is better to put the DIR, STEP, ENABLE signals of the various steppers on the same port (so I thought it was recommended for AVR)  to minimize jitter making single writes for all steppers.
On a 16-bit port I can put X, Y, Z, Extruder 1, and in case Extruder 2
How about ?
Thank you

**Comment by ejtagle** [comment]
basically, Marlin right now is doing acces to each individual bit of each port, so it makes no difference
