### ISSUE TITLE
[Marlin-bugfix-2.0.x] Maybe a bug? Re-bump not working on Z

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#10942]
As per subject re-bump works on X and Y when homing but not on Z

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/2074361/Configurations.zip)

is there something in the config that prevents it?

**Comment by ejtagle** [comment]
Try enabling ENDSTOP_NOISE_FILTER and see if that makes a difference...

**Comment by boelle** [comment]
that did not help

but my probe has disconnected at the plug

the strange thing is that i dont use the probe for homing but rather i have dual z drivers and dual z endstops

should it not disregard the probe during homing?

**Comment by ejtagle** [comment]
During homing the probe should be ignored...

**Comment by boelle** [comment]
it is not

if i have the probe connected and i home i get the rebump

if i remvoe the probe i dont get it

and as you can see in my config i use max endstops and when i home the Z goes up

i does not make sense to me

**Comment by GMagician** [comment]
I also have dual Z, dual switches and bltouch and it works for me, but I have `#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
` disabled

**Comment by boelle** [comment]
well i have to have that enabled as that is where the probe is connected

x is connected to x min, y to y min, one z endstop to z max, the other z is connected to x max, probe is conncected to z min

**Comment by GMagician** [comment]
Yes but I think that when this is enabled probe is used to home (I have to check code)

**Comment by boelle** [comment]
i can home my machine no problem

its the rebump that is missing if the probe is not connected

remember my machine is set to use the max endstop and not the probe

rebumb is where it touches the endstop and then move away and then goes towards the endstop again at slow speed.

**Comment by GMagician** [comment]
> y to y min

USE_YMIN_PLUG is disabled

**Comment by boelle** [comment]
oh yes.... forgot to tell that i have swapped pin numbers in the ramps pin file

but to make it clear x and y are working 100% as they should

**Comment by GMagician** [comment]
you also have:
#define Z2_USE_ENDSTOP _XMIN_

**Comment by boelle** [comment]
yes... as i said i swapped some pin numbers in the pin file

will attach that one, it will make more sense. But i did not want to change the plugs on the board so i just changed the pin file

**Comment by GMagician** [comment]
ok I wrote message before explorer refresh

**Comment by boelle** [comment]
[pins_RAMPS .zip](https://github.com/MarlinFirmware/Marlin/files/2078111/pins_RAMPS.zip)

rename file to pins_RAMPS.h

ITS not a zip file

**Comment by boelle** [comment]
reason why i'm lazy is that all my wires are secured with zip ties and i have to waste about 5-10 zip ties... so it was more easy to change arroun pin numbers

**Comment by GMagician** [comment]
well I have to check code to go further..

**Comment by boelle** [comment]
yeah, its a funny one

everything works 100% as it should if z probe is connected. what is interesting is that it should not care about the probe

UBL also works fine.... 

its only when i disconnect the probe it does not home Z correctly...

**Comment by GMagician** [comment]
Sure your config is updated?
`#define Z2_USE_ENDSTOP XMIN` should be `#define Z2_USE_ENDSTOP _XMIN_`

**Comment by boelle** [comment]
let me double check... but it was prob one of those that might have slipped past my nose when i updated the config

**Comment by boelle** [comment]
nope its correct as you would have seen in the configs attached to first post

```
#define Z_DUAL_STEPPER_DRIVERS
#if ENABLED(Z_DUAL_STEPPER_DRIVERS)
  #define Z_DUAL_ENDSTOPS
  #if ENABLED(Z_DUAL_ENDSTOPS)
    #define Z2_USE_ENDSTOP _XMIN_
    #define Z_DUAL_ENDSTOPS_ADJUSTMENT  0
  #endif
#endif
```

**Comment by boelle** [comment]
hmm... will check the attached config to make sure you got the right data

EDIT: attached config was the same

**Comment by GMagician** [comment]
ok I think I understood. I opened it in a linux mint SO under virtualbox. It display underscores as space...

**Comment by GMagician** [comment]
In code I see something like:
`#define HOMING_Z_WITH_PROBE (HAS_BED_PROBE && Z_HOME_DIR < 0 && ENABLED(Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN))`

I really think that this define will do something "not wanted" when defined. I think you can try to remark it and define Z_MIN_PROBE

**Comment by boelle** [comment]
yeah, i think you found it

to me is looks strange that just because i have a probe and z home dir  is some value and  the probe uses z min endstop pin then homing with probe is enabled autoamtic

but when i do a home is uses the microswitch endstops

but it kind of halfway make sense why it will not rebump


not sure if this is a bug.... but its not correct either.

**Comment by boelle** [comment]
forgot... will test this tomorrow, had visitors today and have to take printer off and store it

**Comment by thinkyhead** [comment]
> should it not disregard the probe during homing?

Yes, it does (or should) ignore the Z probe during homing. (Since your `Z_HOME_DIR` is 1 the `HOMING_Z_WITH_PROBE` value will be FALSE.)

Be sure to disable all endstop plugs that have nothing attached, otherwise the firmware will read them while homing.

```cpp
#define USE_XMIN_PLUG
//#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
#define USE_XMAX_PLUG
#define USE_YMAX_PLUG
#define USE_ZMAX_PLUG
```

There's a new general issue where dual _endstops_ are not re-bumping (See #10936, #10897) probably caused by the recent endstops code revamp by @ejtagle. The problem seems to exist for some but not for others, and for some only in `bugfix-1.1.x` but not in `bugfix-2.0.x` so we're not sure yet what the exact cause is.

The recommended course right now is to go back to an earlier version of Marlin.

**Comment by boelle** [comment]
> The recommended course right now is to go back to an earlier version of Marlin.

I mange by keeping sure the Z probe does not disconnect. 

There is only one plug not in use, and remember i did swap the pin numbers in the pins file so i would not have to waste 10 zip ties, i did attach the pins file a few post back. Remember its not a zip file but i just renamed the extension so i could attach it

> where dual axes are not re-bumping

i dont have dual axis but could it still have some influence?

**Comment by thinkyhead** [comment]
> i dont have dual axis but could it still have some influence?

If you're not using dual _**endstops**_ (correction) then disable this:
```cpp
  #define Z_DUAL_ENDSTOPS
```

**Comment by boelle** [comment]
i meant i dont have dual x axis or dual y axis, but i do have dual Z endstops

**Comment by boelle** [comment]
and i just re-read your post and see that you wrote dual endstops..... me getting tired here :-(

**Comment by thinkyhead** [comment]
Right, and you're also using dual Z steppers (aka "dual Z axis"), so each one is connected to a separate stepper driver, Z and Z2. So if someone asks in future if you're using a dual axis, the answer is "yes."

**Comment by boelle** [comment]
forgot this one, is it a bug when it does not do rebump because i disconnect the probe. which i think it should ignore since the probe is not used for homing

or should it be closed? i was just thinking about labels

**Comment by thinkyhead** [comment]
> is it a bug when it does not do rebump because i disconnect the probe

It might be, but you should use `M119` to see if connecting and disconnecting the probe has any effect on endstop readings.

**Comment by boelle** [comment]
output from octoprint terminal

before disconnect:
```
Send: N901 M119*34
Recv: Reporting endstop status
Recv: x_max: open
Recv: y_max: open
Recv: z_min: open
Recv: z_max: open
Recv: z2_max: open
Recv: filament: TRIGGERED
Recv: ok
```

after disconnect:
```
Send: N902 M119*33
Recv: Reporting endstop status
Recv: x_max: open
Recv: y_max: open
Recv: z_min: TRIGGERED
Recv: z_max: open
Recv: z2_max: open
Recv: filament: TRIGGERED
Recv: ok
```

zmin is the probe and that is the only one i would expect to change status

**Comment by thinkyhead** [comment]
We'll keep tweaking the endstop code, and hopefully eliminate all unwanted false-positives.

**Comment by boelle** [comment]
just going through my issues here and want to know if this was a bug or not? 

ie why does homing Z depend to max endstops on whatever the touchprobe is connected or not? if you ask me it should not matter, only when the probe is actually used

if it can not be seen as a bug i wanted to close this one

**Comment by boelle** [comment]
closing this one as it seems its not regarded as a bug
