### ISSUE TITLE
Please update the G-code reprap wiki and keep it up to date

### ISSUE THREAD

**Issue by bubnikv** [MarlinFirmware/Marlin#10946]
Hello.

Would you please update the G-code reprap wiki and keep it up to date? We at Prusa3D are quilty of the same sin and we should update the Wiki as well. If we do not do that, we risk collisions of new G-codes.

@PavelSindler is responsible for the Prusa3D fork. Pavel, we should update the RepRap wiki.

Thank you guys.

**Comment by thinkyhead** [comment]
We try to! If there's something missing that we forgot, please add it yourself.

**Comment by boelle** [comment]
@thinkyhead think we can close this one
