### ISSUE TITLE
Arduino Nano Pin mapping \help wanted

### ISSUE THREAD

**Issue by gian1312** [MarlinFirmware/Marlin#10968]
Sorry for the abuse of the issues.
I cannot get on the RepRap right now.
I am implementing a new board.
For the Arduino mega pin mapping there are nice layouts with the corresponding numbers.
Sadly, for the Nano 328P I cannot find any pinouts with the single numbers (1,2,3,4,..) just with the letter number combination.
Is there any way to calculate it or look it up?
Kind Regards

**Comment by Ludy87** [comment]
https://img3.picload.org/image/rargiocw/arduino-nano-pinout.png

**Comment by gian1312** [comment]
Thanks a lot
