### ISSUE TITLE
[bugfix-2.0.x] cardreader lsDive issue

### ISSUE THREAD

**Issue by simon-jouet** [MarlinFirmware/Marlin#10973]
### Description

In 2168d6ac lsDive was modified to pass NULL instead of an empty string however in https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/sd/cardreader.cpp#L113 prepend is used without checking if it's NULL or not. I changed back from NULL to "" and I can list the files fine.

### Steps to Reproduce

1. Have an sdcard with a folder (on windows "System Volume Information" will be created automatically)
1. M21 to init the SD card
2. M20 to list the files -- crash

**Expected behavior:** list the files

**Actual behavior:** crash

#### Additional Information

That's on my custom HAL that i'm working on, but quickly looking at the code it looks like the issue is more global. Is anyone using bugfix-2.0.x with the SDcard at the moment? (I would guess so)

**Comment by GMagician** [comment]
Thanks for this report

**Comment by thinkyhead** [comment]
Patched!
