### ISSUE TITLE
Marlin 1.1.6 and 1.1.8 freezing or rebooting at long prints

### ISSUE THREAD

**Issue by italocjs** [MarlinFirmware/Marlin#10981]
Hello all, 
I'm experiencing an issue with both marlin 1.1.6 and 1.1.8 (i've tried to upgrade to see if the issue would be  gone, and didnt work)

ive been making four new 3d printers, all four have the following setup
>arduino mega
>ramps 1.4
>drivers a4988 at 16 microstepping
>screen 12864 full graphic display (red board, blue screen)
>using new and formatted at fat32 sd cards
>BLTouch from anticlabs 
>heated bed MK2
>12v - 30A PSU 

This issue only happens with long prints, more than 8 hours at least. the screen will either freeze (the data on it still the same) or sometimes it reboot,  (once the all data disappeared, and the screen was full blue),  I can print 20 smallers files (which together will be longer than the 8 hours), and there will be no problems

I have a proper cooling on the ramps and a good PSU, the issue is not to power failures because i'm running the printers from two separated UPS. so i'm pretty lost on the reason.

I've checked the Gcode and its not corrupted (this happened to me a few times before, because i've removed it before S3D finished 

Did anyone had something similar? i'm guessing it might be because the bltouch, because they are the only thing that is different on these four machines from all the others (running older firmwares but with inductive sensors), But i have no experience coding or debuging this kind of issue

Thank you all for this awesome firmware and community :D

**Comment by italocjs** [comment]
Oh, forgot to say, i've connected it to the usb to read the serial output and its normal, i've only been receiving the temperature on Simplify 3D, no errors or weird stuff until it hangs and reboot (then it prints the marlin beginning header and stuff)

**Comment by italocjs** [comment]
If someone need or want to read the code, here it is, (all the marlin folder) https://drive.google.com/open?id=1XAl6hxkenffgrxMZt2JllOs0urh_sgsY

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by italocjs** [comment]
I'll be trying it tomorrow, 
As for using bugfix, is there any advice to use it? (i'll burn the firmware and leave the machine probably unattended)

**Comment by thinkyhead** [comment]
> is there any advice to use it?

Use with caution. It contains some code that is not as well-tested as release versions.

**Comment by italocjs** [comment]
Update:  I've been using v2.0.0 bugfix for a week now without any issue,  i've printed about 45hours on one printer and 30h on another, no rebooting and freezings anymore.  

Thanks marlin dev. team :+1: 
Closing the issue

**Comment by silam1215** [comment]
@italocjs
I have the same issue with my kossel linear plus (marlin 1.1.8). I am going to try bugfix 2.0. But i have no idea how to use bugfix 2.0. Can you give me some instruction?

**Comment by thinkyhead** [comment]
>  i have no idea how to use bugfix 2.0

Essentially the same as 1.1.
