### ISSUE TITLE
Teensy 3.6

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#10994]
@teemuatlut 

hi i saw that you have started on a pin file for teensy 3.5/3.6

i wonder if you have ever printed with it and if it's an "ok" board for marlin?

i used an issue since i did not know any other way to get in contact. will close this one as soon its posted to it does not take up space on the list

**Comment by teemuatlut** [comment]
Never printed. It was just a rough idea where everything could go.

**Comment by boelle** [comment]
oki, not sure if its the correct question to ask, but how would you rate the teensy to say a Due?

if one if better than the other etc.

I thought that is better as its runs faster and if i remember correct it also have a FPU

EDIT: do we not have a list somewhere that list what MCU marlin supports?

**Comment by teemuatlut** [comment]
I'd say the Teensy is better in almost every way.
It's faster, it has an FPU and better support from the developer.
The downside is that there are no commercial boards running either Teensies or even the chip itself. Teensy also has fewer available pins but depending on the implementation that may not be a limitation.

https://github.com/MarlinFirmware/Marlin/issues/7076#issue-236576233

**Comment by boelle** [comment]
aha :-) 

so it would not be a bad thing if we got a shield for it, 

what i noted is that the pin map you made in top of the pin file did not have all the internal pins, but i guess that is due to that you only made a rough start?

will thinker about the shield idea, i guess a shield that has same features as Ramps FD 2.2 (yes there is a non released version with this number) 

i exclude RADDS here as its not open source in any way etc.

**Comment by boelle** [comment]
i think with some time i could mod the schematic for ramps FD in kicad, but doing tracks and placing components i would need help with.

but then again would it be worth the trouble?

**Comment by boelle** [comment]
tried to play arround with the thought of using Ramps FD 2.2 as a base for a Teensy shield, the kicad schematics is made of of several schematics and i had a go for the power part and came up with this

![image](https://user-images.githubusercontent.com/3832239/41233587-2a3f14dc-6d8a-11e8-9ea9-5cf8fa62a11e.png)

**Comment by thinkyhead** [comment]
A few months ago Paul Stoffregen expressed an interest in making a 3D printer board based around it, but we haven't received any updates on that.

**Comment by boelle** [comment]
my problem is that i dont know kicad well and not 100% in to the schematic of Ramps FD

i got hold of V2.2 which is many version past the unsafe ones and its 3.3V level. there are just a few things that i'm unsure off and then i suck at routing tracks

but i figured that it would be a good starting point. My plan was to make it a shield just like for arduino due but for a teensy instead and then get 3 or 10 boards made and put components on them

**Comment by boelle** [comment]
@teemuatlut & @thinkyhead do we know any that are good at electronics design in kicad that might be able to adjust an Ramps like board to fit with a Teensy instead? i'm going to finish my hypercube next month and will need electronics for it. I would have gone with an Due and Ramps FD 2.2 but if i could get the Teensy instead i think i would be better off.

as an alternative i could go just hardwiring the teensy to some FET modules and Stepper expanders instead. But i would rather have a real pcb than that

**Comment by boelle** [comment]
dont bother..... it does not have enough pins

lets put this no to rest, no need to reply

**Comment by boelle** [comment]
trying again 

@teemuatlut in the teensy pins file heater 0 is connected to pin 30... but so is E0_DIR_PIN, was that a typo?

also HEATER_BED_PIN and E0_STEP_PIN  share pin 31

**Comment by teemuatlut** [comment]
It's an unfinished plan that has never had any relation to actual hardware.

**Comment by boelle** [comment]
oki... will try and connect as many i can with the plan you did and see where i end up

i have been told that the teensy do not have enough pins but i want to see that for myself before i belive that
