### ISSUE TITLE
Junction Deviation default value and changing it on LCD

### ISSUE THREAD

**Issue by FiCacador** [MarlinFirmware/Marlin#10996]
### Description

The default JUNCTION_DEVIATION_MM 0.02 is too slow on curves, I guess it's a typo and it was meant to be 0.2.
Also the new option to change the value on LCD (Control -> Motion -> Jerk -> Junction Dev) is locked at 0, maybe it only accepts integer values, as that is what happened with jerk, and the new junction deviation value never reaches 1.

### Steps to Reproduce

Configure Configuration_adv.h with Junction Deviation enabled.

#### Additional Information

I also have enabled:
#define JUNCTION_DEVIATION_INCLUDE_E
#define LIN_ADVANCE.

**Comment by thinkyhead** [comment]
Two PRs are in place to address the LCD editing issue.

The low (0.02) value is intentional. See https://github.com/MarlinFirmware/Marlin/issues/9917#issuecomment-396085333
