### ISSUE TITLE
Capacitance Sensor Z-Level Failure 

### ISSUE THREAD

**Issue by Grant-fm** [MarlinFirmware/Marlin#11016]
### Description

I have a capacitance sensor, recently installed, on my printer that stops working when I unplug my computer USB cable to the controller board.  The sensor accuracy is impacted by the heat bed (when it is heating the sensor calibration alters), the hot end, and fan.  It appears that the electrical fields around the sensor are problematic.  Having said that, these issues I can somewhat deal with, however, having to keep my laptop connected to the board is more perplexing.  

### Steps to Reproduce

1. Connect the sensor to the 24V power terminals and the signal wire, with an apposing diode, to the Z-min signal pin
2. Plug a printer in to the board (the sensor should work)
3. Now unplug the USB cable from the computer (now the sensor will stop working)
4. By stop working, what I mean is the sensor light goes out and the sensor no longer operates
5. By plugging in the computer USB cable to the controller board again, the sensor light comes back on and the sensor works perfectly.  (I don't see why this would happen?)

When you send an M119 command you get a Sensor Triggered flag back (while Z Min is Open.  

#### Additional Information
Board - MKS -GEN L 
Sensor - LJC18A3-B Z/AX
Marlin 1.1.x

Print surface Aluminium / silicon heating pad / glass top

**Comment by thinkyhead** [comment]
It doesn't sound like a firmware bug. For help with electronics / wiring / hardware issues, try the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)

**Comment by houseofbugs** [comment]
@Grant-fm you have a grounding issue on the machine.

**Comment by boelle** [comment]
@Grant-fm 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
