### ISSUE TITLE
Z axis won't move at all in Prusa i3 MK2 Clone with TMC 2130

### ISSUE THREAD

**Issue by GuSeiffer** [MarlinFirmware/Marlin#11022]
I'm new to github so please forgive me if I make any mistakes. Now to the printer:

### Issue description
I recently started building a 3D printer with tmc 2130 following q3ok's tutorial on GitHub. Managed to make everything work except the Z axis. For some reason it doesn't even turn on. Both of the Z's motors worked when I plugged them in X pins in Ramps, but they won't work plugged in their proper pins.
here is the Marlin I'm using:
https://github.com/q3ok/Marlin/tree/MK2Clone-r2
and assembly tutorial
https://mk2clone.dozuki.com/c/MK2Clone_r2_assembly_guide
Will include some pictures at the end.

### Compile errors
 I see in the code that `//#define Z_IS_TMC2130` is commented. I tried do simply change it, but got an error message ( I really don't know a lot about it, but to me, when I uncommented the code it was supposed to work, no?) 

<details><summary>Build Log</summary>

```
Arduino: 1.8.5 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

sketch\Marlin_main.cpp: In function 'void do_homing_move(AxisEnum, float, float)':

sketch\Marlin_main.cpp:2822:94: warning: default argument given for parameter 3 of 'void do_homing_move(AxisEnum, float, float)' [-fpermissive]

 static void do_homing_move(const AxisEnum axis, const float distance, const float fr_mm_s=0.0) {

                                                                                              ^

In file included from sketch\Marlin_main.cpp:247:0:

sketch\Marlin.h:472:6: note: previous specification in 'void do_homing_move(AxisEnum, float, float)' here

 void do_homing_move(const AxisEnum axis, const float distance, const float fr_mm_s=0.0);

      ^

sketch\Marlin_main.cpp:2822:94: warning: 'void do_homing_move(AxisEnum, float, float)' was declared 'extern' and later 'static' [-fpermissive]

 static void do_homing_move(const AxisEnum axis, const float distance, const float fr_mm_s=0.0) {

                                                                                              ^

In file included from sketch\Marlin_main.cpp:247:0:

sketch\Marlin.h:472:6: note: previous declaration of 'void do_homing_move(AxisEnum, float, float)'

 void do_homing_move(const AxisEnum axis, const float distance, const float fr_mm_s=0.0);

      ^

sketch\endstops.cpp:186:81: warning: backslash and newline separated by space

       if (TEST(endstop_hit_bits, A ##_MIN) || TEST(endstop_hit_bits, A ##_MAX)) \ 

 ^

sketch\stepper_indirection.cpp: In function 'void tmc2130_init()':

stepper_indirection.cpp:221: error: 'initializedStepperZ' was not declared in this scope

   #define _TMC2130_INIT(ST, SPMM) tmc2130_init(stepper##ST, ST##_MICROSTEPS, ST##_HYBRID_THRESHOLD, SPMM, initializedStepper##ST)

                                                                                                           ^

sketch\stepper_indirection.cpp:237:7: note: in expansion of macro '_TMC2130_INIT'

       _TMC2130_INIT( Z, planner.axis_steps_per_mm[Z_AXIS]);

       ^

exit status 1
'initializedStepperZ' was not declared in this scope

```
</details>

### Firmware version
I'm using Marlin V1.1.

Oh yeah, and in his tutorial q3ok uses 2 drivers for the Z motors. Is it really necessary? Shoud I plug both of them in Z's tmc 2130 or one in Z and one in E1?

Thanks!
![img_20180614_110357_hht](https://user-images.githubusercontent.com/40270023/41417482-db628a24-6fc3-11e8-8221-a603ff7d2898.jpg)
![img_20180614_110647_hht](https://user-images.githubusercontent.com/40270023/41417486-dd93b8b8-6fc3-11e8-9251-f016bd26cef0.jpg)
![img_20180614_110651_hht](https://user-images.githubusercontent.com/40270023/41417489-df51e328-6fc3-11e8-9313-cb7dfbffe881.jpg)
![img_20180614_110655_hht](https://user-images.githubusercontent.com/40270023/41417492-e0cc7826-6fc3-11e8-8cec-768a30f7ef1d.jpg)
![img_20180614_110658_hht](https://user-images.githubusercontent.com/40270023/41417498-e2c276b2-6fc3-11e8-97f6-067885ea65ed.jpg)

**Comment by teemuatlut** [comment]
Your code is failing at a point that is not part of the main Marlin project.
You need to bring this into the attention of the fork's developer.
