### ISSUE TITLE
Fastio.h _AVR_ATmega328P PINC7 not declared

### ISSUE THREAD

**Issue by gian1312** [MarlinFirmware/Marlin#11048]
Hi all

I hope I am at the right place here.
If I use an AVR_ATmega328P based board (Nano, 2009) and use pins higher than 20 in the pins.h file. I get compiling errors. Like PINC7 is not declared.

Where are these variables declared? 

Best Regards and thanks a lot.

**Comment by AnHardt** [comment]
There is no chance to compile a recent Marlin for a 328P.
Even if you deactivate everything, it's simply too large.
