### ISSUE TITLE
bugfix-2.0.x: Question Junction Deviation and Linear Advance

### ISSUE THREAD

**Issue by gloomyandy** [MarlinFirmware/Marlin#11049]
When using Junction Deviation and Linear Advance at the same time should the option to include E in the junction deviation planning be enabled (JUNCTION_DEVIATION_INCLUDE_E), or will this cause any sort of problem? In general is there any advice on when to use the various new options like Junction Deviation, Linear Advance, Adaptive Step Smoothing and any associated settings? Does enabling them require changes be made to any other settings (acceleration?), is it sensible to combine them etc?

**Comment by thinkyhead** [comment]
`JUNCTION_DEVIATION_INCLUDE_E` removed.
