### ISSUE TITLE
Fade height does not accept LCD screen input in bigfix-2.0x

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#11054]
With Bilinear Bed Leveling enabled, fading height is adjustable via Gcode and the menu item appears on the LCD screen.  Using the up and down arrows, the value can be adjusted up or down from zero.  Pushing any of the horizontal buttons does not record the change.  This is a minor bug in that the Gcode entry does work

### Steps to Reproduce

1. load bugfix 2.0 on an Anet A8 equipped with an inductive probe and stock display.  
2. enable bed leveling and fading in configuration.h
3. attempt to set fading height in Gcode (Success!)
4. attempt to set fading height on the LCD screen (Failure!)

**Expected behavior:** Gcode can be set by the LCD menu on an Anet A8 with the stock display 

**Actual behavior:** input is ignored

#### Additional Information

Worked fine in 1.1.8

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
Okay
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2111551/Marlin.zip)

**Comment by thinkyhead** [comment]
Thanks for the report! This is now patched in the bugfix branches.
