### ISSUE TITLE
[bugfix-2.0.x] Raize Z after G28

### ISSUE THREAD

**Issue by rmcbc** [MarlinFirmware/Marlin#11064]
In v1.1.8 after G28 the Z is moved (10mm + value in M851) up, and with bugfix-2.0.x Z stays in zero (position defined in M851), what can I do to have the same beaviour?

**Comment by ruggb** [comment]
no idea but maybe check this out
```cpp
//#define Z_AFTER_PROBING           5 // Z position after probing is done
```
about line 803 in configuration.h

**Comment by thinkyhead** [comment]
I just peeked at the `G28` code in 1.1.8 and compared it to the latest code, and I can see no extra raise done in 1.1.8 at the end of `G28`. So maybe there's a setting that didn't get moved over in your upgrade.

If you can't figure it out and want to get more insight, enable `DEBUG_LEVELING_FEATURE` in 1.1.8 and issue the command `M111 S247` to enable maximum logging before `G28`. Copy the log output into a text file. Then do the same with `bugfix-2.0.x` and compare the logs to see what's different.

**Comment by boelle** [comment]
@rmcbc 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
