### ISSUE TITLE
min/max redefinitions bug

### ISSUE THREAD

**Issue by grownseed** [MarlinFirmware/Marlin#11063]
### Description

Latest Marlin bugfix-2.0.x:
When trying to include certain libraries for ESP, compiling returns errors such as:
```
Marlin/src/module/stepper.h:150:107: error: no matching function for call to 'max(long int, long unsigned int)'
```

It appears Marlin redefines its own min/max, which clashes with the std::min/max from the ESP libs.

There appears to be more details in this comment: https://github.com/esp8266/Arduino/issues/398#issuecomment-356034907

I have very little experience with this and therefore have a hard time understanding what needs to be done. That said if anybody has any suggestions I'd be happy to help with a PR (if code changes are indeed required).

**Comment by thinkyhead** [comment]
Try replacing `max` with `MAX`.

**Comment by grownseed** [comment]
Thanks @thinkyhead, I don't actually use `min`/`max` in my own code, the issue is between Marlin and the ESP libs if I understand correctly. Are you suggesting I try redefining `min`/`max` to `MIN`/`MAX` in the Marlin code directly, e.g. [here](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/inc/Conditionals_post.h#L42) and as I just noticed you did here https://github.com/MarlinFirmware/Marlin/commit/7406f04029da76d4c6564677ed783d9fb55fba45 ?

I thought this might be too big a change, but if you don't see any issues I'm happy to try.

**Comment by thinkyhead** [comment]
Just in `stepper.h`: Where `max(...)` appears, try `MAX(...)` instead. If it works I'll patch `stepper.h`.

**Comment by grownseed** [comment]
@thinkyhead had to change all the `max(...)` to `MAX(...)` and `min(...)` to `MIN(...)` in both `module/stepper.h` and `inc/Conditionals_post.h`, and I can compile with these changes :+1:

**Comment by thinkyhead** [comment]
Good news. I'll do that patch asap.

**Comment by boelle** [comment]
@grownseed is problem gone away with latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
