### ISSUE TITLE
Trinamic driver SPI control

### ISSUE THREAD

**Issue by pgScorpio** [MarlinFirmware/Marlin#11073]
The current SPI support for the trinamic drivers requires all tmc chips to be connected to miso and mosi of the processor and require a separate chip select pin for each channel.
For many printer configurations however this is a pain in the ass because there are not so many pins available/accessible (many times forcing you to use the endstop pins for cs and use tmc stallguard as endstop, which has its own problems).

The TMC chips however can be used in cascade where miso/mosi are connected from chip to chip and they all share one common chip select.

It should be possible to use this mode in marlin, which would simplify the interconnection and reduce the number of used IO pins.

[TMC-SPI.pdf](https://github.com/MarlinFirmware/Marlin/files/2124099/TMC-SPI.pdf)

**Comment by thinkyhead** [comment]
I don't think this is currently supported by the TMC2130Stepper library that we use. You should post your suggestion to https://github.com/teemuatlut/TMC2130Stepper/issues

**Comment by Grogyan** [comment]
Perhaps a shift register such as the 74HC595 or 74HC164 is a better solution?

**Comment by pgScorpio** [comment]
Discussion moved to https://github.com/teemuatlut/TMC2130Stepper/issues/41
