### ISSUE TITLE
Auto Bed leveling goes straight down instead of making a grid

### ISSUE THREAD

**Issue by poptogordon** [MarlinFirmware/Marlin#1107]
Hello,

I just put the auto bed leveling on my printer (custom Cartesian style). I am using RAMPS 1.4 and the latest Marlin Firmware. I followed the instructions and the system partially works now. I can get the servo to move properly and I have the offsets calculated and the z- endstop triggers correctly.

The problem arises when I use the G29 command to probe the bed. The Z axis comes down at X0 Y0 as if it were homing at the corner (which is off the bed for me). If I hit the z-endstop with my hand it will stop the descent, retract for a second, extend the endstop again and continue straight down. This process repeats for the exact number of probe points that I expected but all of them are straight down. 

I have examined and compared my config.h with other people that have this successfully working and I cannot find any significant differences. I am very puzzled at the moment, any help would be appreciated.

Gordon

**Comment by poptogordon** [comment]
A quick update that I noticed. When I initiate the G29 command the x and y are 0 because I just homed x and y. However once the series of straight down movements have completed with me manually triggering the z endstop the x and y are not 0. The readout on Repetier Host displays the following:

```
23:31:30.673 : Bed x: 50.00 y: 60.00 z: -2.18
23:31:31.841 : Bed x: 140.00 y: 60.00 z: -2.26
23:31:33.852 : Bed x: 140.00 y: 140.00 z: -4.22
23:31:34.934 : Bed x: 50.00 y: 140.00 z: -4.25
23:31:34.942 : Eqn coefficients: a: -0.00 b: -0.03 d: -0.68
23:31:34.946 : planeNormal x: 0.00 y: 0.03 z: 1.00
23:31:34.950 : echo:endstops hit:  X:154.50 Y:117.00 Z:-4.25
```

The readout says that the x and y have moved but they have not. They have not even made any noise. This printer already has at least 20 hours of printing on it so I know that the motors work fine.

What do I do to make this work as it should?

Thanks,
Gordon

**Comment by aneox** [comment]
the same problem like in first post. Istead to move x and y from 0, it tries to probe out of bed

**Comment by luismanson** [comment]
do you know how much? i endedup finding a few mistakes on my setup, what i did to test is to put a big foam in the bed and a cardboard over it. That way nothing gets broken if the X keeps going down until you can abort the probing

**Comment by thinkyhead** [comment]
We recently fixed a bug in M600 that could cause the X axis to move in unpredictable ways, and otherwise cleaned up the implementation. Check the latest Development branch and see if it's still exhibiting this behavior.

**Comment by boelle** [comment]
is this still an issue with a fresh copy of marlin and IDE updated to latest non-beta?

will close this one soon as it seems people dont have an issue anymore

**Comment by thinkyhead** [comment]
Delta Bed leveling from jrocholl's fork, plus a fuller implementation of G29 were both merged recently. Bed leveling should be a different experience now.

**Comment by boelle** [comment]
ok as no one else have responded i will close this one... can always reopen if plese comment that the issue it not gone

**Comment by alow2004** [comment]
hello, i have the same issue with my purse i3 printer, with the latest marlin firmware installed... (1.02)

**Comment by thinkyhead** [comment]
@alow2004 This issue has probably been fixed in the current code: https://github.com/MarlinFirmware/Marlin/tree/Development We may not patch it in 1.0.2, as we are getting close to the release of 1.1.0. But we do need feedback on how the latest code is working, if you feel like installing it and giving it a go.
