### ISSUE TITLE
[bugfix-2.0.X] 6/18/18 too big to compile with bed leveling

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#11080]
### Description

Marlin bugfix-2.0.x appears to have grown!  I can no longer compile it without OptiBoot on an Anet A8 board. 

### Steps to Reproduce

1. Use my configuration.h to compile without Optiboot for an A8 board. 

2. will fail with not enough memory

**Expected behavior:**

Should compile at about 98% memory used.

**Actual behavior:** 

Fails to compile.  Probably some code optimization is needed. 

#### Additional Information  

Here's my configuration.h

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2125745/Marlin.zip)

**Comment by thinkyhead** [comment]
Indeed. We haven't gotten down to size optimization yet, what with all the other things being adjusted. Meanwhile, for 128K boards we recommend using `SLIM_LCD_MENUS` to save some space.

**Comment by bill-orange** [comment]
Yes, I tested with `#define SLIM_LCD_MENUS` and it compiles with 93% of program storage used.  A considerable difference!

**Comment by thinkyhead** [comment]
The old maxim "premature optimization considered bad" bugs me, but I still tend to follow it. I hope we'll get both bugfix branches slimmed down before the release of 1.1.9 so they're as optimal as possible. But there have been a lot of changes, so it might not be easy.

**Comment by Roxy-3D** [comment]
One thing you can try is turning on the original MESH_BED_LEVELING.  It is very small.   It doesn't have all the support functions that the other bed leveling systems have.  But if you have a well tuned mesh, it will perform very well.

It is very possible you can get that to squeeze onto your board.

**Comment by bill-orange** [comment]
@Roxy-3D for my situation, I think using the Slim LCD Menu structure will be best.  My mesh is not all that great.
