### ISSUE TITLE
[FR] Edit UBL mesh Without an LCD

### ISSUE THREAD

**Issue by evertonramires** [MarlinFirmware/Marlin#11088]
UBL is great, but beeing able to run the whole process including assisted fine tuning over serial com would be very useful for hosts like octopi. We have a touch display, no need to a second oldschool one!

**Comment by Roxy-3D** [comment]
You can also edit mesh points with M421.    The syntax varies depending on what bed leveling system you are using.

**Comment by thinkyhead** [comment]
> run the whole process including assisted fine tuning over serial com 

Pretty complex, and basically would need a companion OctoPrint plugin that mates with the feature if there is to be a back-and-forth communication process.

**Comment by Roxy-3D** [comment]
> being able to run the whole process including assisted fine tuning over serial com would be very useful or hosts like octopi. 

If somebody is willing to code up the client side of things...   It would be straight forward to put the control elsewhere.   The client could do a G29 W to find out all the details of the mesh.   (The mesh points, how many there are, the distance between them, etc.)    And then a G29 T will give the actual values.

With a touch display you could outline an area and then pull it up or push it down.  The client could edit the values by sending the appropriate M421 commands to the various mesh points within an area.

But for now...   The LCD Panel works to edit the mesh.

**Comment by sjasonsmith** [comment]
@GypsyRobot I believe this capable already exists. According to the [Marlin documentation for UBL](https://marlinfw.org/docs/gcode/G029-ubl.html) this can be done with a combination of G42 and M421 commands.

![image](https://user-images.githubusercontent.com/20053467/92969243-6eefb700-f431-11ea-90e7-33afd275f387.png)
