### ISSUE TITLE
timeout error after compilation/upload Ramps 1.4 Mega 2560 Marlin 1.1.8

### ISSUE THREAD

**Issue by dabossie** [MarlinFirmware/Marlin#11082]
Hello, 
compiling went OK, but at the end of the upload I get a message. 
avrdude: verification error, first mismatch at byte 0x10141
Is that fatal?

best regards Piet.

**Comment by GMagician** [comment]
I think that the error is due to mismatch values between cpu flash content and file to be written...
If I'm correct this is not a good thing. If you retry and get always same error maybe your chip flash is gone...

**Comment by dabossie** [comment]
The error is gone when I separate the Ramps from the Arduino Mega.
Is that normal?

**Comment by GMagician** [comment]
No it's not. Is board powered by USB? What do you have connected on ramps?

**Comment by dabossie** [comment]
No I have an external power source and the Arduino is connected via the USB port, ofcourse.
There are no peripheral devices connected to the Ramps, I'm configuring so I can swap my Anet bord for this, when I'm satisfied.

**Comment by GMagician** [comment]
Have you ever used ramps with other CPU? Maybe you have a faulty board

**Comment by dabossie** [comment]
It crossed my mind, but at the moment i'm building an AM8 from scratch and when that printer is printing OK I want use the RAMPS config.
So it is not so imminent at the moment and I put it aside, for now.
Will pick it up when the AM8 is up and running.

**Comment by boelle** [comment]
@dabossie is the problem still there when using latest bugfix 2.0 ?

**Comment by dabossie** [comment]
I terminated the project.

**Comment by boelle** [comment]
Then maybe click the close button?
