### ISSUE TITLE
Bad temperature reading LINEAR_ADVANCE

### ISSUE THREAD

**Issue by margaale** [MarlinFirmware/Marlin#11092]
With latest bugfix 1.1.x, as now(#11084), I'm seeing bad temperature readings about the nozzle. I'm using PID Temp in the nozzles and the bed too. There seems to be high reading that is fooling marlin so it lets the temperature go low enough to abort the printing with a thermal runaway error. As soon as i set K to 0.00 ~~everythings starts working as usual~~ the situtation improves.

Update: Removing completly linear advance fixes this problem

**Comment by gloomyandy** [comment]
What sort of control board are you using, how much free memory do you have when you build Marlin? Others have reported odd temperature issues, which turn out to be caused by some sort of memory overrun issue due to low memory.

**Comment by margaale** [comment]
An arduino mega with Ramps 1.4.
This is after compiling marlin; 
Sketch uses 220074 bytes (86%) of program storage space. Maximum is 253952 bytes.
Global variables use 5860 bytes (71%) of dynamic memory, leaving 2332 bytes for local variables. Maximum is 8192 bytes.

**Comment by gloomyandy** [comment]
That looks like more free memory than the folks that had the other problem, so I guess that it is not that causing your issues.

**Comment by margaale** [comment]
It seems that lowering Extruder Acceleration and retraction acceleration helps a little.

**Comment by Sineos** [comment]
Duplicate to #10900

**Comment by thinkyhead** [comment]
It may be more that the Stepper ISR eats up so much time that the Temperature ISR is getting shorted. One workaround may be to reduce the number of micro-steps on your axes to free up the processor a bit more.

**Comment by margaale** [comment]
Just to let you know. After latest bugfix (now) I get no bad readings. I guess that the pr that ensures ADC conversion has everything to do with this.
