### ISSUE TITLE
ZOffset and auto homing not working with BLTouch probe

### ISSUE THREAD

**Issue by bfrakes256** [MarlinFirmware/Marlin#11107]
Printer Wanhao IIIP (Monoprice) with standard extruder.

Arduino with Ramps 1.4 board.

Installed BLTouch probe and updated the Marlin software.  Marlin 1.1.8

The BLTouch probe extends and retracts on command.  Distance from bed to bottom of BLTouch housing is 8.3mm.  Probe activates the light at 1.7mm above the nozzle in contact with the bed.

Marlin3d software shows that the printers will set the corners and center of the bed normally.

When I try to home Z, it moves down and crashes the bed.  The only way to stop it is disconnect and reconnect which resets the motors.   Setting the safe homing to the center of the bed and telling it to probe the bed, it homes x and y then puts the nozzle in the x 0 y 0 instead of the center of the bed.  Of course the BLTouch does not find the bed and keeps going.

Moving the extruder to the center of the bed and forcing it to try to sense the bed, it crashes into the bed and buzzes until reset.  

No matter what I try, ZOffset cannot be set.

Check the code several times and I don't see any issues.  Attached is a zip with configuration.h and configuration_adv.h

Any help appreciated....

**Comment by kAdonis** [comment]
you could start with
`#define Z_PROBE_OFFSET_FROM_EXTRUDER 0 `
-1.7 is way too much, when your Bltouch is 8.3mm above the Nozzle
then you have a starting point to set your actual z offset

your Configuration files are outdated, I assume you used Marlin3d software?
you really should edit the configs matching your marlin version "by Hand"

**Comment by bfrakes256** [comment]
Not using the 3d software to edit.  Using the Arduino IDE.

Outdated how?

I've not done any C++ programming in a long time.

**Comment by kAdonis** [comment]
your Configuration.h is version 010100
Configuration.h from Marlin 1.1.8 is version 010107
I have no Idea from C/C++

**Comment by bfrakes256** [comment]
Ok, I'll match them up and try the new setting.

**Comment by bfrakes256** [comment]
It is now working.
