### ISSUE TITLE
How to make UBL work properly

### ISSUE THREAD

**Issue by ryan34side** [MarlinFirmware/Marlin#11108]
Hello

Is it possible to have precise orders to operate the UBL?
1) What should we put to turn it on the first time once the z OFFSET and done ?

2) And what should we put in the gcode not to redo the leveling of the bed and especially when you turn off and restart the printer ?

thank you very much because with all the posts I see a little of everything and I can not know what to do as command

I have a cr10s with a bl touch and the UBL

thank you very much
@Roxy-3D 
Nicolas

sorry for English I'm french!

**Comment by dw-0** [comment]
Did you take a look into the documentation?
http://marlinfw.org/docs/features/unified_bed_leveling.html

**Comment by ryan34side** [comment]
yes I saw but I do not know what to put in the boot script if I want to do other print but without redo g29 p1 leveling @th33xitus

is it mandatory to fill in unseen points in the mesh? because i can not run g29 p3 and do not know how to tell if there is a non-polled point? how to see it?

**Comment by forkoz** [comment]
G29 T - show points
G420 L0 S1; << inside start script to activate bed leveling mesh. You can also have it turn on all the time after G28 from configuration.h and then just to G29 A once.

**Comment by ryan34side** [comment]
@forkoz 
For levelling : 
G28
G29 P1
G29 A
G29 S1

for de startup script /

G28
G29t
G420 L0 S1
G28 A

it's exact ?

**Comment by Roxy-3D** [comment]
If you set it up so UBL is active at power up (or reset)....   You don't even need a G29 in your start up script.   It will load the mesh and UBL will be active.    Or...  you can do it the other way and do a 
- G28
- G29 L 1
- G29 A
in your start up script.

**Comment by ryan34side** [comment]
thank you very much i note it and realized a good leveling once i have registered  in the config.h my z offset extruder i have to do /

G28
G29 P1
G29 A
G29 S1

good ?

@Roxy-3D

**Comment by Roxy-3D** [comment]
You don't want a G29 P1 in your start up script.   You use that to build and fine tune a mesh that you save in the EEPROM.    And you call it up and use it later.  Once the mesh is built and fine tuned (and saved) you put this in your Slic3r's start up script:    https://github.com/MarlinFirmware/Marlin/issues/11108#issuecomment-399942648

**Comment by ryan34side** [comment]
ok vut we agree to do the leveling I use it well 
G28
G29 P1
G29 A
G29 S1

?

**Comment by Roxy-3D** [comment]
To build the mesh and save it...  Use the 'Quick Start' instructions located towards the top of:

http://marlinfw.org/docs/features/unified_bed_leveling.html

The following command sequence can then be used as a quick-start guide to home, level, and then fine-tune the results. These commands are for a ‘normal’ setup; see the relevant addenda for concerns and gcode sequences related to setups without an lcd or z-probe.:
```
;------------------------------------------
;--- Setup and initial probing commands ---
;------------------------------------------
M502            ; Reset settings to configuration defaults...
M500            ; ...and Save to EEPROM. Use this on a new install.
M501            ; Read back in the saved EEPROM.  

M190 S65        ; Not required, but having the printer at temperature helps accuracy
M104 S210       ; Not required, but having the printer at temperature helps accuracy

G28             ; Home XYZ.
G29 P1          ; Do automated probing of the bed.
G29 P2 B T      ; Manual probing of locations USUALLY NOT NEEDED!!!!
G29 P3 T        ; Repeat until all mesh points are filled in.

G29 T           ; View the Z compensation values.
G29 S1          ; Save UBL mesh points to EEPROM.
G29 F 10.0      ; Set Fade Height for correction at 10.0 mm.
G29 A           ; Activate the UBL System.
M500            ; Save current setup. WARNING: UBL will be active at power up, before any `G28`.
;---------------------------------------------
;--- Fine Tuning of the mesh happens below ---
;---------------------------------------------
G26 C P5.0 F3.0 ; Produce mesh validation pattern with primed nozzle (5mm) and filament diameter 3mm 
                ; PLA temperatures are assumed unless you specify, e.g., B 105 H 225 for ABS Plastic
G29 P4 T        ; Move nozzle to 'bad' areas and fine tune the values if needed
                ; Repeat G26 and G29 P4 T  commands as needed.

G29 S1          ; Save UBL mesh values to EEPROM.
M500            ; Resave UBL's state information.
```

**Comment by ryan34side** [comment]
thank you for your help I will test tonight !! @Roxy-3D

**Comment by forkoz** [comment]
I don't really even need fine tuning on my printer. I just do
G29 P1
G29 P3
G29 S
M500

This is good because I get different mesh values with different bed temperature. Maybe I should save them all to different positions like S0, S1, S2, etc. I only generate a new mesh when I mess with carriage or Z screws or change materials that use different bed temperature.

**Comment by ryan34side** [comment]
I tested everything works apparently the only problem is when I turn off or I turn on the printer or when I do a print justa after a leveling the height of the z is not good. after for the print after the height returns to the correct height. I do not understand

thanks for help

@Roxy-3D

**Comment by Roxy-3D** [comment]
Can you re-write that with different words.   I don't understand what you are trying to communicate.
Also...    Please consider turning on the Z-BabyStepping in Configuration_adv.h.   And also the 'Double Click' option for it.    That makes it much easier to get the first layer going down right.

**Comment by boelle** [comment]
@ryan34side is this still an issue?

**Comment by boelle** [comment]
@thinkyhead think we can close this one
