### ISSUE TITLE
bugfix-2.0.x: Motion control jerky when acceleration is low

### ISSUE THREAD

**Issue by nebbian** [MarlinFirmware/Marlin#11101]
### Description

When the acceleration is set to low values (I used 100), all motion including travel moves is very jerky.  It appears as if the motion is broken up into segments, and the end of each segment is treated like a stop.

### Steps to Reproduce

1. Configure your marlin for use on a delta (not sure if this is related, but I'm using a delta)
2. In the start GCode, set the acceleration to 100.  eg. M201 X100 Y100 Z100
3. Print the file.

**Expected behavior:** 
The extruder will slow down smoothly at the end of a move, when there is a sharp corner.

**Actual behavior:** [What actually happens]
The extruder moves in a series of small pulses, even when moving in a straight line, and even when travelling.

#### Additional Information

I tried using both bezier curve and jerk, both acceleration schemes provided the same behaviour.

This seems to have been introduced between 8th April 2018, and today, as the previous version of the 2.0 branch didn't exhibit this behaviour.

Configuration is here:
[marlin_configuration_pulsing.zip](https://github.com/MarlinFirmware/Marlin/files/2130568/marlin_configuration_pulsing.zip)

An image showing the issue is here.  Each blob represents where the extruder slows down markedly.
![img_8404](https://user-images.githubusercontent.com/489642/41816983-bd4b20d8-77c4-11e8-8a65-7c51dc7c7ea1.jpg)

**Comment by ejtagle** [comment]
Could you try PR #11098 and see if it makes a difference ?

**Comment by nebbian** [comment]
Hi ejtagle, I can confirm that your branch has fixed this issue, on the exact same file that previously gave issues.  Nice work 👍 
Hopefully your request gets pulled in soon.

**Comment by thinkyhead** [comment]
Changes have been merged. Appears to be solving a pile of lingering motion issues.

**Comment by nebbian** [comment]
Thanks @thinkyhead, I can confirm that the latest 2.0 branch is working perfectly for me.
