### ISSUE TITLE
ERROR ? in get z correction

### ISSUE THREAD

**Issue by colchonerox** [MarlinFirmware/Marlin#11100]
I turn on the printer command to print a gcode from SD.
Heats the bed and heats E1 but when this list jumps this error.
? in get z correction (lx0 = 298.99, ly0 = 298.99)
Where can I modify this error?

Have Marlin 1.1.6 and have TMC2130 drivers.

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by boelle** [comment]
@colchonerox did you what thinky suggested?
