### ISSUE TITLE
[Help] Get RADDS2LCD working

### ISSUE THREAD

**Issue by freakezoid1604** [MarlinFirmware/Marlin#11114]
Hi
is it possilble to add the RADDS2LCD it to Marlin/Marlin2.0? It connects a RepRapDiscount Full Graphic Smart Controller to RADDS board.
Here the link to the RADDS2LCD Project https://www.thingiverse.com/thing:1740725
I try to add it, but i was not able to do it.
Thanks

**Comment by smoki3** [comment]
So it's easy... 

Enable the Full Graphic Reprap Discount Display first.

Then open pins_RADDS.h
Scroll down to 

```cpp
  #elif ENABLED(REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER)

    #define LCD_PINS_RS     46
    #define LCD_PINS_ENABLE 47
    #define LCD_PINS_D4     44
```
Change the lines to:
```cpp
    #define LCD_PINS_RS     42
    #define LCD_PINS_ENABLE 43
    #define LCD_PINS_D4     44
```

**Comment by freakezoid1604** [comment]
I did that but it didn't work, but i will try it again in the evening.
But thanks for your answer. I will give you an feedback.

**Comment by smoki3** [comment]
Its working using this for more than a year now

**Comment by freakezoid1604** [comment]
![Image](https://i.imgur.com/Wa6rAo6.jpg)
On my side it didn’t work
 
#elif ENABLED(REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER)
  
    #define LCD_PINS_RS     42
    #define LCD_PINS_ENABLE 43
    #define LCD_PINS_D4     44

    //#define LCD_PINS_RS     46
    //#define LCD_PINS_ENABLE 47
    //#define LCD_PINS_D4     44

    #define BEEPER_PIN      41

    #define BTN_EN1         50
    #define BTN_EN2         52
    #define BTN_ENC         48

**Comment by smoki3** [comment]
Does it work on repetier for you? otherwise I think its an adapter/lcd error

**Comment by freakezoid1604** [comment]
Yes it works
![Image](https://i.imgur.com/3SpfXvh.jpg)

**Comment by smoki3** [comment]
can you upload your config?

**Comment by freakezoid1604** [comment]
Here my config.
For testing i use a blank marlinfw down load. i only adujst the board and the pin plus the full graphic display
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2137747/Configuration.zip)

**Comment by smoki3** [comment]
You dont use RADDS as board. 

  #define MOTHERBOARD BOARD_RAMPS_14_EFB

should be   #define MOTHERBOARD BOARD_RADDS

**Comment by freakezoid1604** [comment]
Arg mix a folder and the project in arduino
give me some seconds i try again

**Comment by freakezoid1604** [comment]
but the same situation
Aber das gleiche Fehlerbild
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2137807/Configuration.zip)

**Comment by smoki3** [comment]
So have you tried to connect a host? Or press the reset button on the RADDS. It doesnt boot with the display at the first time. 
Also please connect the thermistors. 
Because Marlin doesn't start as far as I know without thermistors.

**Comment by freakezoid1604** [comment]
i have aready thermistors on the board. Also i connect the powersupply. i press the button for the reset many times (ond RADDS and on the due)

**Comment by smoki3** [comment]
Are you able to control your printer with a host?

**Comment by freakezoid1604** [comment]
Yes I can connect and operate the board. So it seem it run

**Comment by smoki3** [comment]
So really weird. I use the same adapter for over one year without any problems.

**Comment by freakezoid1604** [comment]
Version 3 yes with the 1kohm resistors
![Image](https://i.imgur.com/ziFtU5p.jpg)

**Comment by smoki3** [comment]
Ok my versions doesn't have the resistors

**Comment by freakezoid1604** [comment]
Maybe it could be the problem but on repetier it works fine so hm.

**Comment by freakezoid1604** [comment]
Maybe that helps to Help me
https://www.screencast.com/t/7fvrdHpAWWQj

**Comment by smoki3** [comment]
I think that the schematic of you adapter PCB.

**Comment by freakezoid1604** [comment]
![Image](https://i.imgur.com/3EIWksi.jpg)
That’s the schematics

**Comment by smoki3** [comment]
yes here its working fine. On all firmwares i have ever tested

**Comment by freakezoid1604** [comment]
with that change?

Then open pins_RADDS.h
Scroll down to

  #elif ENABLED(REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER)

    #define LCD_PINS_RS     46
    #define LCD_PINS_ENABLE 47
    #define LCD_PINS_D4     44

Change the lines to:

    #define LCD_PINS_RS     42
    #define LCD_PINS_ENABLE 43
    #define LCD_PINS_D4     44

**Comment by smoki3** [comment]
Yes exactly

**Comment by thinkyhead** [comment]
Marlin now has `RADDS_DISPLAY` as an LCD option.
