### ISSUE TITLE
[bugfix-2.0.x] TMC2208 - Unknown command: "M122"

### ISSUE THREAD

**Issue by TiToMoskito** [MarlinFirmware/Marlin#11126]
I updated to the latest bugfix-2.0.x and enabled TMC_Debug.
I followed this guide to get the UART Connection: https://3d-druckerei.blogspot.com/2018/03/blog-post.html

This are my Configs:
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2140621/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/2140622/Configuration_adv.txt)

Board: MKS Gen 1.4
Drivers: 5 x TMC2208 (X,Y,Z1,Z2,E0)

**Comment by mce076** [comment]
configuration_adv.h line 1138 you have not defined HAVE_TMC2208

`//#define` HAVE_TMC2208

**Comment by TiToMoskito** [comment]
Thank you very much
