### ISSUE TITLE
Auto Temp

### ISSUE THREAD

**Issue by 3Dmaniac** [MarlinFirmware/Marlin#11157]
Hi guys,

In the display options (Control>temperature), i see an option called Auto temp.
In it i can see a max temp value, min temp value and a factor value.
Turning it on i see no changes. Starting a print i see no changes.

What does this feature do?

Thanks

**Comment by AnHardt** [comment]
https://github.com/MarlinFirmware/Marlin/blob/ac3fab7a9680a880fd1b113be7e758c6dabb2a57/Marlin/Configuration_adv.h#L110-L123

Autotemp tries to forecast the energy needed to melt the filament. Instead of waiting for the PID to put more energy in, because the temperature dropped, it tries to put the energy in before the temperature drops.  Not well tested.

**Comment by 3Dmaniac** [comment]
Hi AnHardt,

thanks for the answer.

So, if i turn the auto temp feature on, it will override the PID routine?
And this will work without any modification on the print gcode as long as the print gcode temperature is set between min temp and max temp?

Thanks

**Comment by thinkyhead** [comment]
The PID still runs, but the temperature target is adjusted dynamically also.

**Comment by 3Dmaniac** [comment]
I tried to turn the Auto temp mode on with a max temp of 205 and min temp of 200 and next, i ran a gcode print were the temperature was set by the slicer with 195degrees. The firmware used the temperature from the gcode (195degrees) and not the one from the auto temp mode.

**Comment by thinkyhead** [comment]
Did you also add `M109 F<factor> S<min> B<max>` to your startup G-code? It has to come after all other `M109` commands or auto-temp will be canceled.

**Comment by boelle** [comment]
@3Dmaniac 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
