### ISSUE TITLE
Marlin and this printer

### ISSUE THREAD

**Issue by d2crafty** [MarlinFirmware/Marlin#11155]
Anybody know of this mb / printer and if marlin would be compatible with it.  [https://imgur.com/gallery/I95zApd](url)
![motherboard](https://user-images.githubusercontent.com/7044117/42121396-13d409a2-7be3-11e8-8679-d42410171588.jpg)
![tdevyn3](https://user-images.githubusercontent.com/7044117/42121398-1807e836-7be3-11e8-9755-31cba5c47ccd.jpg)
![tis](https://user-images.githubusercontent.com/7044117/42121399-1941ca8c-7be3-11e8-837e-175e3c2e36e0.jpg)

**Comment by thinkyhead** [comment]
Marlin doesn't yet support WiFi. Marlin probably doesn't support that LCD controller. We can't see what the name of the board is, because most of the name is obscured by the ribbon cable at top.

**Comment by thinkyhead** [comment]
You might also ask around at:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)

**Comment by d2crafty** [comment]
[well,](https://imgur.com/gallery/2uTTrL6) i found out what kind of print it is, its a teco imaging systems printer.  

https://www.youtube.com/watch?v=tKlHQZV3hvY&t=3s  ..
problem is getting anything to work with it, their company doesn't reply to anything.  

I'm wondering if its worth gutting the computer and rewiring the whole thing with a rambo board
it does have some interesting hardware inside, including the proximity sensor and some good stepper motors.

**Comment by d2crafty** [comment]
[](url)

**Comment by Bob-the-Kuhn** [comment]
What is the processor on the board?  The biggest chip looks like it has a TI logo on it.

**Comment by Bob-the-Kuhn** [comment]
Here's a link to the "3D and inkjet" printer division.  Good luck.

https://tw.linkedin.com/in/damson-lai-8b9a7b22

**Comment by d2crafty** [comment]
![teco chip](https://user-images.githubusercontent.com/7044117/42427415-3f28936e-82e3-11e8-93c1-3a14e781290a.jpg)

some of it is smudged out.  but it is a TI AM3356BZ0Z60 chip?  my eye sight isn't as good as it used to be.  So I did the android way

**Comment by Grogyan** [comment]
http://www.ti.com/lit/ds/symlink/am3356.pdf
This is the datasheet you are looking for
Which encompasses the AM3356BZCZ60 pictured above

**Comment by Bob-the-Kuhn** [comment]
That's an ARM® Cortex®-A8 32‑Bit RISC Processor. 

I'm not aware of anyone trying to port Marlin to an A8 ARM processor.  It takes a **LOT** of work to create a new HAL.

**Comment by d2crafty** [comment]
seems one of my chips fried yesterday.  
![a1407](https://user-images.githubusercontent.com/7044117/43039067-400109dc-8cda-11e8-8310-c91bbbc16b1d.jpg)
![a1414](https://user-images.githubusercontent.com/7044117/43039069-42431514-8cda-11e8-8d92-813a14c2c750.jpg)

board still works, the lcd seems gone.  So I'm assuming it was probably lcd driver? 

If I were to run another board with this commercial printer, is it worth running a rumba with marlin? or another 32bit board like a smoothie?
