### ISSUE TITLE
Future?: Adding autolevel configuration into eeprom & menu

### ISSUE THREAD

**Issue by Toffe87** [MarlinFirmware/Marlin#1116]
https://github.com/Bevaz/Marlin/tree/Auto_level_2.00

He have inside Control -> Motion the following:

Z Offset:  (For adjusting for servo)
Z Extend angle:  (For servo)
Z Retract angle: (For servo)

Could this be "forked" into the main git? Its really nice to be able to configure the z-offset instad of needing the computer & firmware upload each time.

**Comment by boelle** [comment]
is this still an issue with a fresh copy of marlin and IDE updated to latest non-beta?

**Comment by thinkyhead** [comment]
The value is saved and restored in the EEPROM currently

```
EEPROM_WRITE_VAR(i, zprobe_zoffset);
...
EEPROM_READ_VAR(i, zprobe_zoffset);
```
