### ISSUE TITLE
[2.0.x] custom startup code/ pin initialisation

### ISSUE THREAD

**Issue by TheLongAndOnly** [MarlinFirmware/Marlin#11166]
I need to set some pins permanently to high to configure my RADDS Extension Board properly. Is there any recommended way to do this in Marlin?

**Comment by thinkyhead** [comment]
Add to `setup()` in `Marlin.cpp`…
```cpp
OUT_WRITE(MY_PIN, HIGH);
```

**Comment by TheLongAndOnly** [comment]
Wouldn't this be a kind of "brute force" solution?
What about this option: Add the option to create a board_init() function and a define BOARD_HAS_INIT. When enabled, the board_init() function is called from setup()...

**Comment by iosonopersia** [comment]
But you still would have to manually edit Marlin code to insert those 'OUT_WRITE(MY_PIN, HIGH);' lines... I don't see the point...

**Comment by TheLongAndOnly** [comment]
Sure, but it could be moved to the correct context. Personally I don't think that a core file should be edited for configuration/setup purposes. I came to the conclusion, that a function would not work, als the boards have no cpp yet. But it could be done through a BOARD_INIT macro.

**Comment by xC0000005** [comment]
Do these need to initialize after Marlin is running? In the malyan boards with pullup transistors for USB, I turn them on in a variant initi function in the board definition.

**Comment by thinkyhead** [comment]
> Personally I don't think that a core file should be edited for configuration/setup purposes.

If it's just for your own setup then it's fine. If it's for everyone, then #11170 is better.
