### ISSUE TITLE
Where can I find the bugfix files and how do I implement them into the marlin project?

### ISSUE THREAD

**Issue by jaanshgo** [MarlinFirmware/Marlin#11163]
I apologize if this has a very simple answer but I just can't find any info or links to the bugfix "branch" or how to use it. Any help would be greatly appreciated.

**Comment by MikeLud** [comment]
@jaanshgo 
The below link might help you.

http://marlinfw.org/docs/basics/install.html

**Comment by ManuelMcLure** [comment]
The main download page at

[http://marlinfw.org/meta/download/](url)

also has a link where you can download daily versions of the bugfix branches if you don't want to mess with Git.
