### ISSUE TITLE
Q: Lost link to MCU list

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#11188]
Hi, i lost a link that listed different MCU's, how fast they run and how much memory etc each has

i cant remember if its in the wiki or if it was in the form of an issue, but google was far from my friend on this one

best i could find was this one: https://github.com/MarlinFirmware/Marlin/issues/7076

but that was not the one i was after

**Comment by Sineos** [comment]
This one? https://reprap.org/wiki/Comparison_of_Electronics

**Comment by boelle** [comment]
nope...

it was not a electronics list... it was a list of MCU's.... Arduino Mega.... Due.... Teensy

**Comment by tig33r** [comment]
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x#current-hals

Current HALs section

**Comment by boelle** [comment]
yep, that was the one, link saved :-D
