### ISSUE TITLE
EEPROM and LCD Bed Leveling cannot be enabled together.

### ISSUE THREAD

**Issue by Splic3dBread** [MarlinFirmware/Marlin#11184]
Trying to get Marlin 1.1.8 working on cr-10 had been a 12 hour straight nightmare. Scraping everything and starting over has fixed some of my issues even though the configuration files were almost identical (files were somehow currupted?), but now there's a new problem. Going down the configuration.h and compiling with each change to figure out what's causing errors has shown me that having EEPROM settings enabled along with LCD Bed Leveling + Mesh Bed Leveling creates a "Error Compiling for Board Sanguino Error". Btw, everytime one of these "mystery errors" with no conceivable explanation occur that's the output, nothing else whatsoever. Using LCD Bed Leveling + Manual Probing + Any other bed leveling works fine with EEPROM. I tried compiling with ramps1.4 as the board and it compiled just fine.

**Comment by Splic3dBread** [comment]
Of course right after posting this I figured out what has been causing all my problems, the CR-10 board doesn't have enough storage space. Sorry for the spam, I wish I could delete issues....

**Comment by AnHardt** [comment]
**You**, at least could close it.

**Comment by thinkyhead** [comment]
@Splic3dBread — You can try enabling `SLIM_LCD_MENUS` to save on space. And I recommend you try the [TH3DStudio version of Marlin](https://github.com/houseofbugs/TH3D-Marlin/releases), which is constantly being tuned and refined, and will be getting the latest Marlin improvements in an upcoming version.
