### ISSUE TITLE
Error Compiling for Board Sanguino

### ISSUE THREAD

**Issue by Splic3dBread** [MarlinFirmware/Marlin#11182]
I'm trying to update my CR-10s firmware and Arduino is giving me "Error Compiling for Board Sanguino". Keep in mind that this is simply when compiling and not uploading so it's not a problem with the bootloader installation.

Here's what I have verified and things I've tried...

Reinstalling the Arduino IDE and deleting all local files
I've inserted [this](https://raw.githubusercontent.com/Lauszus/Sanguino/master/package_lauszus_sanguino_index.json) link to preferences
Sanguino selected for board
Latest version of Sanguino (1.0.2)
Prgrammer AVRISP mkII selected
Atmega1284 or Atmega1284P (16 Mhz) selected for processor
Creality Melzi Board selected for board
Reprap Discount Full Graphic Smart Controller selected for LCD
U8glib library included in configuration.h
I was able to dig up some obscure case of marlin not compiling because the baud rate was higher than the max baud rate set in the sanguino's board.txt but unfortunately changing that did not help. I even tried uploading an older version of marlin for the CR-10, the original source code infact and it still gave me the same error!

I'm absolutely stumped. It's so frustrating because I effectively have a bricked printer but there's nothing actually wrong with it!

**Comment by Splic3dBread** [comment]
I was able to narrow it down to an LCD issue. For some reason all the marlin configs I'm looking at have the reprap discount full graphic display selected but I needed to use the one specifically for the cr-10, I didn't even notice it was there. Is the CR-10 stock display option new to Marlin 1.1.8?

**Comment by cjsoong** [comment]
@ @Splic3dBread 
The CR-10 has two mainboard versions, the Sanguino 1284P & Mega2560.
Please confirm the MPU Type on your mainboard?
1.Sanguino 1284P mainboard:
 board type: BOARD_MELZI_CREALITY 
 LCD type:  CR10_STOCKDISPLAY

2.Mega2560 mainboard: 
 board type ..BOARD_RAMPS_14_EFB  
 LCD Type: REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by Bob-the-Kuhn** [comment]
FYI - the CR10 display was added in September 2017.

**Comment by boelle** [comment]
@Splic3dBread 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
