### ISSUE TITLE
Enable bed and nozzle heating simultaneously when starting print

### ISSUE THREAD

**Issue by stibinator** [MarlinFirmware/Marlin#11185]
Is there a reason why the bed is heated first and then the nozzle when starting a print, rather than them both heating at once? It takes a lot longer, especially if the nozzle is already hot, because it cools down while the bed is heating and then has to heat all over again.

Steps to reproduce:
Print from SD

Expected:
Bed and nozzle heat to required temps, simultaneously.

Observed:
bed ehats, then nozzle heats

**Comment by thinkyhead** [comment]
The heating commands `M109` and `M190` wait, while the commands `M104` and `M140` don't wait. Hosts and slicers decide which of these commands to use.

**Comment by stibinator** [comment]
Ok, thanks. I'll go make the feature request for Cura instead.
