### ISSUE TITLE
[2.0.x] Ender -3 BLTouch - hotend goes up 20mm after probing

### ISSUE THREAD

**Issue by lestzx** [MarlinFirmware/Marlin#11189]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2159249/Configuration.zip)
I have an issue with Marlin setup. After probing the z height, the nozzle goes up (also with Auto Home) and it starts printing to high. I use 3DTouch and Petsfang on my Ender 3 printer.

Thank you for your help

PS
I use mks gen l motherboard with TMC 2208 drivers on all axis and extruder (all 3 pins under them are placed)

**Comment by MikeLud** [comment]
@lestzx 
You need to adjusts the below setting in Configuration.h file, try a setting like -1.8 this will lower the nozzle by 0.2mm. Mine is set to -1.6
`#define Z_PROBE_OFFSET_FROM_EXTRUDER -2   // Z offset: -below +above  [the nozzle]`

**Comment by lestzx** [comment]
It doesn't change anything. After probing it goes to Z-20 every time

**Comment by seandop** [comment]
I'm experiencing this issue, also. TMC2130 drivers with MKS Gen L board. BLtouch v2. I did not experience this behavior in any of the 1.1.x builds.

**Comment by thinkyhead** [comment]
Assuming this is solved.
