### ISSUE TITLE
BLTouch not triggering after the first touch and crashing the bed

### ISSUE THREAD

**Issue by bfrakes256** [MarlinFirmware/Marlin#11180]
Installing a BLTouch in Marlin and been having issues with it probing the first time, not reversing the z motor and crashing into the bed.

I've tested the BLTouch with a voltmeter and it does trigger on the correct pins.  As the pin hits the sensor the voltage drops then comes back to the original voltage as it goes into the flashing mode which indicates a problem.

The distance from the nozzle to the bottom of the housing on the BLTouch is set to 8.3mm as specified.  Tried reducing this distance to see if it will trigger earlier with not joy.

Marlin seems to be configured correctly but I may have missed something.

Have not tried changing the BLTOUCH_DELAY value...

Ideas?

Help appreciated...

**Comment by bfrakes256** [comment]
It is now working

**Comment by CWSpear** [comment]
@bfrakes256 what did you do to get it working?

**Comment by bfrakes256** [comment]
Are you referring to the btouch?

Fiddled and changed to the beta version of the Arduino software if so...

Lots if fiddling with Marlin...

;-)

On 3/20/2019 4:10:24 PM, Cameron Spear <notifications@github.com> wrote:
@bfrakes256 [https://github.com/bfrakes256] what did you do to get it working?
