### ISSUE TITLE
old issue of z axis banding resolved now without additional processing, in #define

### ISSUE THREAD

**Issue by jamesdanielv** [MarlinFirmware/Marlin#1119]
change 
#define DEFAULT_AXIS_STEPS_PER_UNIT   {78.7402,78.7402,200.0 * 8/3,760*1.1}
to
#define DEFAULT_AXIS_STEPS_PER_UNIT   {78.7402,78.7402,int ((200.0*8/3)*10)/10,760*1.1}  // default steps per unit for Ultimaker

this removes details that are mis calculated by float process and effect the <> zero approach to determine if the number is met in firmware. it is a simple rounding of number to +/- 0.1

**Comment by boelle** [comment]
is this still an issue with a fresh copy of marlin and IDE updated to latest non-beta?

**Comment by jamesdanielv** [comment]
I would think it to be as it is a mathematical rounding error that results from use of float, and the lower level of single precision. i doubt the IDE handles floats differently. I have not installed latest version of marlin, I have downloaded it and i don't see where changes have been made to the float processing of a float as it approaches zero. I will look in more detail when time permits.

**Comment by boelle** [comment]
ok let us know when you have more info.. i will then upgrade it to a verified bug so it can get in to a milestone and be fixed

**Comment by nophead** [comment]
@jamesdanielv, are you aware 0.1, 0.2 and 0.3 are recurring fractions in binary? If fact I think only 0.5 is exact in binary. So you don't keep things exact by limiting the number of decimal digits in the number you are trying to represent in floats.

I don't follow the logic of this. Please can you give a worked example with numbers that shows how this truncation of the decimal fraction produces more even Z steps

**Comment by thinkyhead** [comment]
Here and there the code has been tweaked to round floats, mainly for display. If there are places where it says `if (myFloat == 0)` where it should say `if (myFloat > -0.00001 && myFloat < 0.00001)` then someone will have to point out where.

**Comment by jamesdanielv** [comment]
I'm not sure that will fix it. what i should have stated is that if errors will exist because of the use of numbers that are not calculated and completely stored accurately and behave as irrational numbers do to the outcome calculation of float conversion and are then rounded off, and so on, rather than have errors from rounding and constant subtraction, have the error be a sum of the entire build, and have the entire math for the build be from rational numbers that are truncated before being used for float based on a constant small error from rounding of a number to prevent inconsistent build layers that is within the precision of the float math.

 this is why averaging out the individual steps to the precision of single float would prevent z height errors and miscalculations. however it would cause the entire build to be fraction higher or lower, but within tolerance, and all the layer height would be consistent. read IEEE_754-1985
http://en.wikipedia.org/wiki/IEEE_754-1985. the issue is with repeated operations and an approximation to the nearest number capable from single float or as the answer that is rounded.  

single floating point as we know it on the arduino is not accurate. this is why we should fix the value used for the float math.

**Comment by jamesdanielv** [comment]
nophead, perhaps the answer is to round the step size the way binary processes rational/irrational  numbers to within the precision of the single float before used.

**Comment by nophead** [comment]
Doesn't the compiler do exactly that? If you write 533.3333333 in the source code and assign it to a float it will truncate it to fit the accuracy of the float's 24 bit mantissa. If you write 533.3 it will do exactly the same but the result is less accurate. It is still a recurring binary fraction and will be truncated. I don't see how it helps to use a less accurate value before truncation.

My own firmware works in steps, so there are no errors after the host converts floating point G code values to stepper motor units rounded to the nearest step. I use 1mm pitch lead screws and use layer heights that are multiples of stepper motor full steps.

**Comment by thinkyhead** [comment]
I would like to see hard data on the exact cumulative error that is being alleged. A Z axis might move 200mm in a large print, and might only ever move in a single direction, so you'd have to have a pretty large error to start seeing real effects.

**Comment by boelle** [comment]
So there is no issue really? or are we just debating back and forth making a novel long list?

**Comment by jamesdanielv** [comment]
there are over a 100000 iterations of calculations with a float number that constantly gets rounded and truncated on a 200mm z height build for z steps done single point precision on the arduino. the error is there, it is just a matter of how much of an issue it is perceived, and what method to go about and correct for it. One way correct for it is to allow a number that is within the precision of single float, so that accuracy is maintained with each iteration of subtraction for step counts. but this just keeps the layers even, the entire build will always have a tolerance range.

**Comment by nophead** [comment]
But 533.3 is not within the precision of any binary floating point number. It is infinitely recurring as are many other exact decimal fractions. You would have to round it to an integer to guarantee it was exactly represented in floating point.

**Comment by brainscan** [comment]
This is all way over my head to be honest but I've never seen z axis banding on other cnc machines so what method do they use? Surely the answer is already out there.

**Comment by nophead** [comment]
Assuming no BAL the Z coordinate in the gcode should be multiplied by the steps per MM to find the target motor position in steps. It should be accurate to the nearest step and that is the best it can do. If you use layer heights that are not exact multiples of motor steps then you will get slightly uneven layers as some will be n steps and some n+1.  

Using a lead screw with 533.3333333 steps per mm is not a good idea as no layer heights are going to correspond to an exact number of motor steps.

**Comment by boelle** [comment]
think i will close this one as people cant show any evidence that there is a problem with marlin itself...

sorry but to keep development etc rolling we cant make have this noise
