### ISSUE TITLE
G28 while HOMING_Z_WITH_PROBE wrong behavior when probe miss the bed

### ISSUE THREAD

**Issue by nightgryphon** [MarlinFirmware/Marlin#11206]
### Description

I use Creality CR-10S with manually deployed Z probe installed to the left and below the nozzle. Both the endstop and probe are functional and share the same pin. The pin triggered if any of endstop or probe triggered.

With Z_SAFE_HOMING disabled G28 command perform Z homing at X0Y0 assuming the Z homing still performed by probe not the endstop (HOMING_Z_WITH_PROBE = true). But while assume homing by probe it does not move XY according to the probe to nozzle offset. This make probe to miss the bed and leveling actually performed by Z endstop. After that the Z probe offset is substracted from current position wchich put the software Z home position far below actual endstop and physical limits. When print starts axis try to move beyond physical limits crushing the endstop and slamming hard in to bed with nozzle ripping the print surface.

There has to be configuration setting to set G28 homing performed by endstop while mesh leveling by the probe AND still respecting the probe to bed spacing while homing X and Y
May be as advanced function is to assume endstop based homing if at XY homing point the probe is beyond print bed limits (probe X<0 || Y<0 || X>X_MAX || Y>Y_MAX)

This also expose the wrong behavior of COMPLETELY ignore the physical endstops by default. There should be some tolerance to physical endstop but NOT ignore them. Ignoring the endstops cause too big axis move to physically crush the endstop sensors and risk of more machine damage.

Furthermore the firmware ignore Z endstop even 

while ENDSTOPS_ALWAYS_ON_DEFAULT enabled

### Steps to Reproduce

1. [First Step]
The machine with endstop share pin with bed probe. The probe is to the left and below the extruder and trigger above the endstop trigger position

Configuration.h
Z_SAFE_HOMING - disabled
Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN - true / enabled
PROBE_MANUALLY - disabled
FIX_MOUNTED_PROBE - true / enabled
Z_HOME_DIR -1 (default)
X_PROBE_OFFSET_FROM_EXTRUDER -38
Y_PROBE_OFFSET_FROM_EXTRUDER -9
Z_PROBE_OFFSET_FROM_EXTRUDER -4

Configuration_adv.h
ENDSTOPS_ALWAYS_ON_DEFAULT - enabled

2. [Second Step]
upload firmware
G28
G1 X0Y0Z0

**Expected behavior:** [What you expect to happen]
move to home position

**Actual behavior:** [What actually happens]
move to lower point beyond limits ignoring endstops

#### Additional Information

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/2168630/Config.zip)

**Comment by nightgryphon** [comment]
here is the quick patch. May be there has to be made other changes but this seems to fix the issue for my case. Has to do more testing.

```
diff --git a/Marlin/Marlin_main.cpp b/Marlin/Marlin_main.cpp
index 4f4271a..780a540 100644
--- a/Marlin/Marlin_main.cpp
+++ b/Marlin/Marlin_main.cpp
@@ -1467,14 +1467,22 @@ static void set_axis_is_at_home(const AxisEnum axis) {
     if (axis == Z_AXIS) {
       #if HOMING_Z_WITH_PROBE
 
-        current_position[Z_AXIS] -= zprobe_zoffset;
+        if (  (current_position[X_AXIS] + X_PROBE_OFFSET_FROM_EXTRUDER > 0)&&(current_position[X_AXIS] + X_PROBE_OFFSET_FROM_EXTRUDER < X_BED_SIZE)&&
+              (current_position[Y_AXIS] + Y_PROBE_OFFSET_FROM_EXTRUDER > 0)&&(current_position[X_AXIS] + Y_PROBE_OFFSET_FROM_EXTRUDER < Y_BED_SIZE) ) {
+          current_position[Z_AXIS] -= zprobe_zoffset;
 
         #if ENABLED(DEBUG_LEVELING_FEATURE)
           if (DEBUGGING(LEVELING)) {
             SERIAL_ECHOLNPGM("*** Z HOMED WITH PROBE (Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN) ***");
             SERIAL_ECHOLNPAIR("> zprobe_zoffset = ", zprobe_zoffset);
+          };
+        } else {
+          if (DEBUGGING(LEVELING)) {
+            SERIAL_ECHOLNPGM("*** Z HOMED WITH ENDSTOP (Z PROBE miss the bed) ***");
+            SERIAL_ECHOLNPAIR("> zprobe_zoffset = ", zprobe_zoffset);
           }
         #endif
+        }
 
       #elif ENABLED(DEBUG_LEVELING_FEATURE)
 ```

**Comment by gloomyandy** [comment]
What version of Marlin are you using (your config files do not look like the latest bugfix version)? You should probably retest with the latest bugfix as there have been a lot of changes in the probe and endstop area.

**Comment by nightgryphon** [comment]
Aww. I see in the 1.1.x bugfix the
#define HOMING_Z_WITH_PROBE (HAS_BED_PROBE && Z_HOME_DIR < 0 && ENABLED(Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN))
was just roughly removed from Conditionals_post.h leaving all the connected code in Marlin_main.cpp unchanged. Especially it affects deployable probes homing code. That means people with deployable probes like BLtouch are not able to home by they sensors anymore as the probe deploy code is blocked now. So when they use Z_SAFE_HOMING the head will slam in to the bed as the sensor was not deployed before homing. It looks it is a bug in bugfix release. 

It is completely wrong method of fixing bugs by randomly removing code without fixing the things rely on it. Someone done a dirty job for marlin firmware...

PS Also the Z_AFTER_PROBING seems to be broken now in bugfix.
The related "bad" commit is 27 Apr "Reorder some conditionals" 
https://github.com/MarlinFirmware/Marlin/commit/e931bc7e7289ff4fc26c7cfd24980c505ba255c9#diff-ffba036d1fad5d16fc1b010038edf9e0

**Comment by gloomyandy** [comment]
HOMING_Z_WITH_PROBE is still there it is just in a different header file (Conditionals_LCD.h). Both of these files will still be included by Marlin_main.cpp. 

So did you actually test with the latest bugfix? If so what happens and can you upload the configuration files that you used.

**Comment by nightgryphon** [comment]
oh. what was the idea of moving that definition to LCD header? Ok. I've missed that it was moved not  removed so i was wrong. 
Will be able to test 'bugfix' branch at the evening in about 5 hours from current moment.

**Comment by thinkyhead** [comment]
With the latest code a failed homing should result in a call to `kill`.

**Comment by nightgryphon** [comment]
I've done testing with bugfix release. The wrong behavior is still there. After G28 actually performed by endstop the firmware still think that it was the probe and shift z homing by probe z offset. After that G1 Z0 just bury head in to bed ignoring z endstop. Here is the config.

So all two misbehavior are still present:
- think homing done by the probe not the endstop while probe position out of bed
- ignoring z endstop and its tolerance (at least in G1 it ignore endstop)

[Config11206.zip](https://github.com/MarlinFirmware/Marlin/files/2172566/Config11206.zip)

**Comment by nightgryphon** [comment]
here is the quick patch for the first part of the issue by add check if the probe within probe working area while homing Z. 
But the ignore endstop is still has to be fixed. It is dangerous behavior to ignore physical endstop.
Also it can be good to add config option to manually tell firmware that while homing the endstop is used not the probe. (or to force using probe)

```
diff --git a/Marlin/Marlin_main.cpp b/Marlin/Marlin_main.cpp
index 3897f79..0b252f9 100644
--- a/Marlin/Marlin_main.cpp
+++ b/Marlin/Marlin_main.cpp
@@ -1495,14 +1495,26 @@ static void set_axis_is_at_home(const AxisEnum axis) {
     if (axis == Z_AXIS) {
       #if HOMING_Z_WITH_PROBE
 
-        current_position[Z_AXIS] -= zprobe_zoffset;
+        // check if the probe position within probe working area. 
+        // If probe within limits then homing done by probe else assume that was an endstop 
+        if (  (current_position[X_AXIS] + X_PROBE_OFFSET_FROM_EXTRUDER > MIN_PROBE_X)&&
+              (current_position[X_AXIS] + X_PROBE_OFFSET_FROM_EXTRUDER < MAX_PROBE_X)&&
+              (current_position[Y_AXIS] + Y_PROBE_OFFSET_FROM_EXTRUDER > MIN_PROBE_Y)&&
+              (current_position[Y_AXIS] + Y_PROBE_OFFSET_FROM_EXTRUDER < MAX_PROBE_Y) ) {
+          current_position[Z_AXIS] -= zprobe_zoffset;
 
         #if ENABLED(DEBUG_LEVELING_FEATURE)
           if (DEBUGGING(LEVELING)) {
             SERIAL_ECHOLNPGM("*** Z HOMED WITH PROBE (Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN) ***");
             SERIAL_ECHOLNPAIR("> zprobe_zoffset = ", zprobe_zoffset);
+          };
+        } else {
+          if (DEBUGGING(LEVELING)) {
+            SERIAL_ECHOLNPGM("*** Z HOMED WITH ENDSTOP (Z PROBE miss the bed) ***");
+            SERIAL_ECHOLNPAIR("> zprobe_zoffset = ", zprobe_zoffset);
           }
         #endif
+        }
 
       #elif ENABLED(DEBUG_LEVELING_FEATURE)
 
```

[bug11206a.zip](https://github.com/MarlinFirmware/Marlin/files/2173360/bug11206a.zip)

**Comment by gloomyandy** [comment]
Is there a reason why you are not using the Z_SAFE_HOMING option as this seems to designed to handle this sort of situation? If you want the Z homing to happen at a different point you can do that by specifying Z_SAFE_HOMING_X_POINT/Z_SAFE_HOMING_Y_POINT I think this will also take into account the probe x/y offset. 

Also perhaps you could explain why you wish to use the probe for homing sometimes, but endstops at other times? Marlin seems to be designed on the basis of using one or the other (though my understanding is that you can use endstops for homing and the probe for levelling). It may help the devs to come up with the best solution if they fully understand why the current setup does not meet your needs.

Did you test the endstops with ENDSTOPS_ALWAYS_ON_DEFAULT enabled and the latest bugfix? My understanding is that there has been a lot of work in this area.

**Comment by nightgryphon** [comment]
I DON'T wish to use probe for homing. Exactly the opposite situation. My probe require manual install/remove to the head. So it is not always there but i still need to be able to home axis.  I wish to home with endstops and than install probe to do bed multipoint probing. Or to stay with just homing level if that enough for the case. Or perform homing by endstops than load saved mesh. I don't want install and remove probe every time i need to just home axis.
And i can't use Z_SAFE_HOMING because it expect that probe is deployed which is not my case.
And yes, i have set ENDSTOPS_ALWAYS_ON_DEFAULT but that work only for XY axis
I have attached the config i've used for bugfix version testing

**Comment by gloomyandy** [comment]
If you don't want to use the probe for homing then I don't think you should have Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN defined (as that will trigger the use of the probe for homing) and ideally you should use a different pin for the probe. Do you have any other pins available (are any of the MAX pins free?). You may still be able to share the Z min endstop pin, but that is getting beyond my knowledge of Marlin configuration. Perhaps @thinkyhead can comment?

**Comment by nightgryphon** [comment]
But my manually installed probe share pin with z-endstop switch. Where to set that probe is using the same pin?

**Comment by nightgryphon** [comment]
May be good idea is to add the special config setting to inform firmware that the endstop used for homing instead of probe. This will allow users to combine all homing options like Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN and Z_SAFE_HOMING. 

Anyway the patch i've posted add some automatic safety by checking probe working bounds. The worst case is home position become higher than required if the probe will trigger earlier than endswitch. But this is way better than head crash in to the table like i've got.

**Comment by nightgryphon** [comment]
Sorry for multiple replies, ca't edit at the moment.
For Creality CR-10S it is problematic to use other pins as the board is installed within separate metal enclosure. Adding more wires will require drilling extra holes and installing connectors and such stuff. Adding probe to Z-endstop require just two intermediate connectors to plug in to existing factory Z-endstop connector

**Comment by gloomyandy** [comment]
Yes I can see that the CR10 might be tricky to add extra sensors to. You may be able to define Z_MIN_PROBE_ENDSTOP and then set Z_MIN_PROBE_PIN to be the same pin as used for your Z end stop to share the pin. But I've never tried that, so be careful and ready to turn things off if it looks like things will crash into the bed! One problem that you may have (if it works at all) is that when probing it may look to Marlin as if the z endstop has triggered rather than the probe. Actually thinking about it you may want to try using sharing the X or Y endstop pin with the probe as they may not get "armed" when probing (as nothing is moving in X or Y)! Just a thought but maybe worth a try? Good luck!

**Comment by thinkyhead** [comment]
> You may be able to define `Z_MIN_PROBE_ENDSTOP` and then set `Z_MIN_PROBE_PIN` to be the same pin as used for your Z end stop to share the pin.

Yes, that should work!
