### ISSUE TITLE
lcd viki2 + rambo 1.3 l 

### ISSUE THREAD

**Issue by labotecno** [MarlinFirmware/Marlin#11203]
hello every one  ! 

i try to upgrate one airwolf hd2x , i have one lcd graphic viki2 , i get it compliled but i have blank screen , someone can to help me to geting this working ? 
thank you very much
[config.zip](https://github.com/MarlinFirmware/Marlin/files/2164320/config.zip)

**Comment by labotecno** [comment]
no body can to help me ?

**Comment by GMagician** [comment]
Have you tryed with bugfix?

**Comment by labotecno** [comment]
yes i try with bugfix and i get a problem with i dont get on the scope delay10s , the only how compiled good is with firmware 1.1.8 but i get blank screen . its not a connection problem because i get it working with this firmware 
[Marlin-Development.zip](https://github.com/MarlinFirmware/Marlin/files/2167710/Marlin-Development.zip)

**Comment by fiveangle** [comment]
Your "working" config doesn't have viki2 defined:

`//#define VIKI2`

**Comment by labotecno** [comment]
wait this one working , but i need the last one marlin working with viki2 someone can to help me ????
[firmwareviki2.zip](https://github.com/MarlinFirmware/Marlin/files/2168864/firmwareviki2.zip)

**Comment by boelle** [comment]
@labotecno 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
