### ISSUE TITLE
[2.0.x] Stm32f1 SDCard in SPI mode problem

### ISSUE THREAD

**Issue by jmz52** [MarlinFirmware/Marlin#11225]
### Description

I have a STM32F103C8T6 'bluepill' board with SD card connected to pins PA4-PA7.
M21 commands results in "SD init fail" error message.
Logic analyzer shows incorrect SS state, Clock Polarity and Clock phase (comparing to working example from STM)

### Additional information

Incorrect SS state is caused by spiBegin() from HAL_spi_Stm32f1.cpp
```
   WRITE(SS_PIN, HIGH);
   SET_OUTPUT(SS_PIN);
```
The 'SET_OUTPUT' macro forces low pin state discarding previously set high.

Clock Polarity and Clock phase are defined in spiInit() from HAL_spi_Stm32f1.cpp
```
  spiConfig = SPISettings(clock, MSBFIRST, SPI_MODE0);
```
SPI_MODE3 ensures correct clock polarity and phase.

Swapping lines in spiBegin() and setting SPI mode to SPI_MODE3 solves the problem.
Tested on 1GB, 2GB and 32GB cards.

**Comment by thinkyhead** [comment]
Thanks for the fix. Now merged!
