### ISSUE TITLE
Z_HOME_BUMP_MM overlapped by Z_CLEARANCE_BETWEEN_PROBES

### ISSUE THREAD

**Issue by StreakingJerry** [MarlinFirmware/Marlin#11231]
with Z_CLEARANCE_BETWEEN_PROBES set to 5 and  Z_HOME_BUMP_MM set to 2.
it seem 2mm bump can not be achieve. the bump distance is still 5mm

**Comment by gloomyandy** [comment]
Are you using a probe to home Z if so then I think it makes sense for Z_CLEARANCE_BETWEEN_PROBES to be used. 

What version of Marlin are you using? Where are your configuration files (see the issue template for how to upload them).

**Comment by StreakingJerry** [comment]
I used the newest bugfix-1.1.x. The case is my headbed is 200*200 but the frame is 300*300. Therefore when the nozzle goes from outside of the bed to inside of bed it need more clearance, like 5mm or 10mm. But when do the bump, 10mm obviously too high. It waste a lot of time, 1mm should be enough I think. But in my case  Z_HOME_BUMP_MM does not work. When it bump it will always take the Z_CLEARANCE_BETWEEN_PROBES
[config.zip](https://github.com/MarlinFirmware/Marlin/files/2182558/config.zip)

**Comment by thinkyhead** [comment]
### `motion.cpp`:
```diff
    #if HOMING_Z_WITH_PROBE
-     (axis == Z_AXIS && (Z_HOME_BUMP_MM)) ? MAX(Z_CLEARANCE_BETWEEN_PROBES, Z_HOME_BUMP_MM) :
+     (axis == Z_AXIS && (Z_HOME_BUMP_MM)) ? Z_HOME_BUMP_MM :
    #endif
```
