### ISSUE TITLE
QUICK_HOME leads to crash if Y endstop hit first.

### ISSUE THREAD

**Issue by StreakingJerry** [MarlinFirmware/Marlin#11232]
I have set the ENDSTOPS ALWAYS ON but it still seems that if y-endstop be hitted first then it will just lead to a crash. Also  if you type G28 twice, the second G28 will just skip the Z clearance step. I don't know if this normal.

**Comment by gloomyandy** [comment]
What version of Marlin are you using?

**Comment by StreakingJerry** [comment]
1.1.8

**Comment by gloomyandy** [comment]
You should probably retest with the latest bugfix as there have been many changes in the endstop code.

**Comment by StreakingJerry** [comment]
THX. I have tested and this problem is fixed in the newest bugfix-1.1.x. But there is a new problem that make the sdcard print impossible. I will put it in a new issue.
