### ISSUE TITLE
Feature request: acustic alarm signal when reaching maximum temperatur

### ISSUE THREAD

**Issue by Chrisu02** [MarlinFirmware/Marlin#1123]
Hello.

I just noticed that it may be a security problem when using a relais that when the relais may fail and make permanent power, even if marlin makes a save stop (M999) the bed which is powered by the relais will still warmup further.
so if `m not at the same room i probably don`t notice this in time which may be dangerous.

wouldn`t be useful if there would also be a acustic signal that warn you when the printer is overheating ?

**Comment by boelle** [comment]
given that there has not been any activity i will kills this one...

you can use a thermal fuse to protect against overheating.
