### ISSUE TITLE
added command

### ISSUE THREAD

**Issue by mjhejazi** [MarlinFirmware/Marlin#11242]
Hello
plz added G54,...,G59 to Command
tank you

**Comment by revilor** [comment]
Out of curiosity: what would be the use case for those gcodes in the context of a 3D printer? And wouldn't it be possible to emulate the behavior of G54 ... using G92?

**Comment by thinkyhead** [comment]
```cpp
/**
 * CNC Coordinate Systems
 *
 * Enables G53 and G54-G59.3 commands to select coordinate systems
 * and G92.1 to reset the workspace to native machine space.
 */
//#define CNC_COORDINATE_SYSTEMS
```
