### ISSUE TITLE
Bugfix-1.1.x SDCARD print not working

### ISSUE THREAD

**Issue by StreakingJerry** [MarlinFirmware/Marlin#11241]
The first step of my gcode is G28, which is generated automatically by Cura. 
After the auto homing then the system looks stuck for about 3 seconds, then it just restart.
Here is my configuration.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/2182750/config.zip)

**Comment by thinkyhead** [comment]
Solved?

**Comment by boelle** [comment]
@wuhao19920619 tried the lastest bugfix 2.0? is the problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
