### ISSUE TITLE
[FR] Let 'level corners' option always be visible and let this do the homing procedure instead

### ISSUE THREAD

**Issue by MathijsG** [MarlinFirmware/Marlin#11250]
### Description

Lately I missed the level corners option on my Marlin CR-10. And somehow I found out that it randomly shows up. After a while of reflashing, manually hardcoding the feature in the Marlin code, and still having it not showing up, I discovered it was due to not having homed the printer before accessing this menu. 

Later on I discovered that more people where seem to be missing this option, and I've helped them saying that they should need to home the thing first. 

Which leads me to the proposed Feature Request: Always show the option to level corners in the menu, and just let the procedure home the thing. Now people are often stuck missing this item randomly (perceived as random). I was wondering what the possible downsides would be, and couldn't really think of any.

**Comment by MathijsG** [comment]
Why is this closed? This is still actual.

**Comment by thinkyhead** [comment]
The option is always visible in the `bugfix-2.0.x` branch. Marlin 1.1.x is end-of-life.
