### ISSUE TITLE
ANET a8 Marlin SD Card not work, fan starts running

### ISSUE THREAD

**Issue by Sebasoy** [MarlinFirmware/Marlin#11274]
Hello, with anet A8 and marlin 1.1.8, bugfix 1.1.8 and bugfix 2.0, in none of them the problem is solved.

The sd card file list is empty and any action on the sd card causes the fan to spin.

**Comment by thinkyhead** [comment]
Any better in the latest `bugfix-2.0.x` branch?

**Comment by Sebasoy** [comment]
nop. tryed with speeds options but none worked to me. maybe is something
related with the board. with the original firmware there was a noise in the
fan when files were downloaded to the sd card via USB. The enable fan
output from the microcontroller shares the control of the sd card logic.

**Comment by thinkyhead** [comment]
Use a multimeter and test if there's a short between the fan pin and the SD / SPI / serial pins.

**Comment by boelle** [comment]
@Sebasoy did you try what thinky suggested?

**Comment by boelle** [comment]
@thinkyhead think we can close this one
