### ISSUE TITLE
Strange regular infill shifting MKS Sbase BugFix 2.0.x

### ISSUE THREAD

**Issue by As3uS** [MarlinFirmware/Marlin#11286]
Hi everyone, after verifying / change mecanical parts i come for aksing you why my infill have blank space.
It's not excatly layershifting because next layer come perfecly over the previous. 
And infill never cross the border

Try Cura, S3D an different stl files it's the same result and same pattern what do you think ?
Change nema, pulley, verify belt tension, steps 16/32, speed and always the same result.

Material : Mks Sbase, mgn12H, Core XY
Firware: bugfix 2.0.x July 2018

Thank a lot 

![img_20180717_012152](https://user-images.githubusercontent.com/34066941/42788832-2d97f380-8962-11e8-8465-647d20a489cb.jpg)

[Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/2199659/Marlin-bugfix-2.0.x.zip)

**Comment by ManuelMcLure** [comment]
I've seen behavior like this if the nozzle is too close to the bed as one row pushes/pulls the adjoining row. Does this happen only on the first layer or do you see it also on higher layers?

**Comment by As3uS** [comment]
I, yes sorry after many test and long Time if test i do a quick offset for the capture it's not accurate but with correct offset calibration it's the same resuIt. 

I wait 3 layer count and the shifting flip 90° he follow the infill pattern you des on the picture. But my part ils correctif formed with ugly blank Space :)

I trying to print a part with hole and on the second layer the printhead is at the good place and without any shifting. 

It's only during infill not on the contouring. I try 30cm square and 10cm square il Always the same pattern i try an other board same issue

I Hope you understand because it's a very worse english ;)

**Comment by As3uS** [comment]
Sorry i make a mistake closing

**Comment by As3uS** [comment]
Solved, linear bearing on my extruder seems to live his life alone.
