### ISSUE TITLE
Feature Request: More decimals on LCD displays

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1128]
To really fine tune a printer from the LCD (if one attached) it could be very beneficial that the display jumps on 0.01 steps and not 0.1

is possible when controlled over serial via tools like pronterface make the steps the same, thou the ZYX knobs dictates the jumps... but via command line...?

**Comment by thinkyhead** [comment]
Currently X and Y show 1 decimal place, and Z shows 2. Should be pretty rare that you need to jog Z in steps under 0.05mm, as this is at the limits of FDM resolution.

**Comment by boelle** [comment]
hehe.. i created this one way back when i had a display attached and at that time the jump was 0.1mm... my current electronics dont have digi lines enough for a display...

also the reason why i debate with myself about getting a Ramps board again

**Comment by AnHardt** [comment]
On the 12864 we currently only have one digit behind the dot.
How about a 'floating point' ?

**Comment by boelle** [comment]
if its 2 digits and i could jump in 0.01mm at a time it vould be more than enough

**Comment by AnHardt** [comment]
Currently we deal with some extremely ugly number formats. Easy to calculate, but ugly. For example:
   Vz-jerk: +000.40
   Xsteps/mm: +080.00

We don't need the '+' and we don't need leading zeros.
With the same string length we could do nicer things.

```
-999999
-99999.
-9999.9
-999.99
-99.999
-9.9999
-0.0001
0.00000
0.00001
9.99999
99.9999
999.999
9999.99
99999.9
999999.
9999999
```

or with a limit to 2 digits behind the dot

```
-99999
-9999.
-999.9
-99.99
- 9.99
- 0.01
  0.00
  0.01
  9.99
 99.99
999.99
9999.9
99999.
999999
```

Wouldn't be to hard to calculate.

**Comment by thinkyhead** [comment]
Z only shows 2 digits when it requires it, but it will do so.

**Comment by AnHardt** [comment]
@thinkyhead 
No.

```
// Convert float to string with +123.4 format
char *ftostr31(const float &x) {
  int xx = abs(x * 10);
  conv[0] = (x >= 0) ? '+' : '-';
  conv[1] = (xx / 1000) % 10 + '0';
  conv[2] = (xx / 100) % 10 + '0';
  conv[3] = (xx / 10) % 10 + '0';
  conv[4] = '.';
  conv[5] = xx % 10 + '0';
  conv[6] = 0;
  return conv;
}
```

I really don't see any chance for this code to produce 2 digits behind the dot.

**Comment by thinkyhead** [comment]
@AnHardt ~~Then the code has been changed. It used to do so.~~ Oh I see, you refer to the edit screen, and not the Info Screen. :hamster:

**Comment by AnHardt** [comment]
@thinkyhead 
As far i can follow with git history it is the same. I'm quite sure you improved the format only for the hitachis.

**Comment by thinkyhead** [comment]
@AnHardt Ah, well I am partial to the Hitachis... Huh, well that should be adjusted on DOGM, and we should make the edit options look better all over too...

**Comment by CONSULitAS** [comment]
@AnHardt Hallo Andreas,
as told before:
I would like the dynamic version, but limited to **three** digits:

```
-999999
-99999.
-9999.9
-999.99
-99.999
 -9.999
 -0.000
  0.000
  9.999
 99.999
999.999
9999.99
99999.9
999999.
9999999
```

One simple reason: I would like to use my printer to mill and drill small PCBs - like others.

For setting the correct tooltip coordinates you need some more precision. But I don't think that a cheap 3D printer can archive more than 0.001 mm precision. So this is more than enough!

Many thanks in advance!
