### ISSUE TITLE
[2.0.x] Problem in Travis build for PRs

### ISSUE THREAD

**Issue by TheLongAndOnly** [MarlinFirmware/Marlin#11284]
Travis builds on PRs currently fail due to platform.io dependencies:

.piolibdeps/Arduino-L6470/L6470/L6470.cpp:12:19: fatal error: L6470.h: No such file or directory

Resolution of dependencies works on my local clone.

**Comment by Roxy-3D** [comment]
Oooops...   I didn't see this thread.   I kind of created a duplicate thread:   https://github.com/MarlinFirmware/Marlin/issues/11289

Recommendations on the best way to fix it are welcome.    What Pull Request caused it?   Is it something small so it makes sense to just revert it?    Or can we just fix the problem more easily?

I don't know (or understand) what the PlatformIO problem is.

**Comment by soimy** [comment]
Just submit PR#11288 for a fix

**Comment by Roxy-3D** [comment]
> Just submit PR#11288 for a fix

We will know soon if that fixes it.   I merged it.  And kicked off some Travis checks.   

UPDATE:  No...  It didn't fix it...  I'm going to revert until things are better understood.

**Comment by soimy** [comment]
Oh, at least the fix works for me

Update: Just go through travis log but seems PR#11288 has passes all test? So what's wrong with that PR?

**Comment by Roxy-3D** [comment]
But **THANKS** for the help!!!!

**Comment by soimy** [comment]
You are welcomed, sorry that didn't help. I'm struggling to get my RAMPS FD V2 up and running 32bit marlin

**Comment by soimy** [comment]
@Roxy-3D take a look here, https://github.com/ameyer/Arduino-L6470/commit/7ca50fac5527db7c36f8bb753e6e0d77ece23469
This might be the source of the problem

**Comment by Roxy-3D** [comment]
What is that?  Is that a null byte just before the new line?

**Comment by soimy** [comment]
No, just indicate the recent commit which changed the header location. That result in PIO complaining missing header file.
