### ISSUE TITLE
BUG: drive by hand is one direction good, other way the number of steps to the stepperdiver is wrong

### ISSUE THREAD

**Issue by bommel382** [MarlinFirmware/Marlin#11293]
### Description
Marlin 1.1.8
drive the axle over a 128x64 display (one direction is good, other way is bad "missing signals")

### Steps to Reproduce

1. [First Step]  i load the marlin 1.1.8 on my mega 2560 board with ramps 1.4
2. [Second Step] then i will drive a axis (no matter which axis, all have the same problem)
3. [and so on...]  when i go to Prepare -> Move axis -> Move Z (Y or X) -> then i will drive only, what i have chosen 1mm (from 0,1 / 1 / 10mm)   in one way the board give the right number of pulse to the stepper driver.... in the other direction gets the stepper driver only ONE square wave singal (no matter which unit, signals missing)

i do not find the problem :-( 

i have test that with two equal boards ( mega 2560 arduino + ramps 1.4 + 12864 display )

Expected behavior:  
when i select a value (0,1mm / 1mm / 10mm) must the stepper get the same square wave signale, no matter WHICH DIRECTION

no matter i select direction, the number of square wave signale MUST BE THE SAME (left and right... only the DIR must change)

Actual behavior:  
in one direction the number of square wave signale are correct numbers.
other way, there a lot of missing square wave signale <-- there is ONLY ONE PEAK  

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2202195/Configuration.zip)

i will drive 1mm each "click" latching point 
![k-p1060731_move_z_1mm](https://user-images.githubusercontent.com/41336069/42826324-6f264cac-89e4-11e8-8c35-762a9b12822a.JPG)

the signal do i measure on the Z DRIVE STEP PIN
![k-p1060727_step_pin_z](https://user-images.githubusercontent.com/41336069/42827383-80ea2448-89e6-11e8-956f-fc9a735778e9.JPG)

one way all signals are good and the numbers of then is correct
![k-p1060739_up_signal_ok](https://user-images.githubusercontent.com/41336069/42826326-6f777fd2-89e4-11e8-8031-1b14ea9078af.JPG)

on the other way, I HAVE ONLY ONE PEAK and many missing  <-- that is the big problem
![k-p1060741_down signal_wrong](https://user-images.githubusercontent.com/41336069/42826322-6e8b0530-89e4-11e8-913d-36c4ebd6ca54.JPG)

PLEASE HELP
what is wrong on the firmware ?

**Comment by xC0000005** [comment]
Do you have software endstops enabled so the printer only "moves" in the upward direction? If so, homing, followed by moving the head logically outward should then allow it to move back.
