### ISSUE TITLE
not an issue, but a question about of marlin g-codes

### ISSUE THREAD

**Issue by bhgv** [MarlinFirmware/Marlin#11316]
i'm playing with stm32 ports of marlin ([marlin_cetus_3d](https://github.com/etet100/marlin_cetus_3d) and [STM32-Marlin-Port](https://github.com/Rejdok/STM32-Marlin-Port)). i'm trying to support of marlin in my [lua.gcode.sender](https://github.com/bhgv/lua.gcode.sender).

(i test a controller without connection to steppers)

when i send for example `G1X100Y100Z100F100` , and immediately after - `M114` (get current position info if i understood correctly) it give me x:100 y:100 z:100 without gradual change of coordinates. 

perhaps some preliminary settings are needed? or M114 returns not the current position of he tool?

could you give me some small, but workable on marlin g-code for testing? and could you tell me with which command of marlin i can get the current position of the tool? and the format of the response?

thanks

**Comment by ManuelMcLure** [comment]
I believe the simple answer is that there is no way to get the exact real time position of the tool - only the resulting position of the last queued movement command. If you want to make sure that the tool is actually at the position reported by `M114` you can execute `M400` to ensure that all queued moves have completed before executing the `M114`.
