### ISSUE TITLE
Mix extruder do not use DISTINCT_E_FACTORS for second extruder motor

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#11326]
1.1.x-bugfix

My config.h:
```cpp
#define EXTRUDERS 1

//#define SINGLENOZZLE

#define MIXING_EXTRUDER
#if ENABLED(MIXING_EXTRUDER)
  #define MIXING_STEPPERS 2        // Number of steppers in your mixing extruder
  #define MIXING_VIRTUAL_TOOLS 7 //16  // Use the Virtual Tool method with M163 and M164
  //#define DIRECT_MIXING_IN_G1    // Allow ABCDHI mix factors in G1 movement commands
#endif

#define DISTINCT_E_FACTORS
#define DEFAULT_AXIS_STEPS_PER_UNIT   {159.0568463, 159.0568463, 802.6794205, 173.06, 1658 }
```
Using mix extruder option (cyclops hotend), the second E step/mm is completely ignored by marlin and it uses the first E step/mm value. 

I have two different extruders: "mk8" for E0 and "gregs wade" for E1. Both need different step/mm config and DISTINCT_E_FACTORS tag is enabled.

The gcode command also gets error:
>>> M92 T1 E1658.00
SENDING:M92 T1 E1658.00
echo:M92 Invalid extruder 1

**Comment by GMagician** [comment]
I have not checked code and maybe this is a real bug, but have you tryed with M502  M500?

**Comment by mtmello2003** [comment]
Yes, for sure. EEPROM were my first check!

**Comment by thinkyhead** [comment]
`DISTINCT_E_FACTORS` is not supported with `MIXING_EXTRUDER` at this time.

**Comment by boelle** [comment]
@thinkyhead so we can close this one? or make it a feature request?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
