### ISSUE TITLE
Z axsis switch doesn't work

### ISSUE THREAD

**Issue by Blisk** [MarlinFirmware/Marlin#11322]
### Description

After uploading marlin 1.1.8 to my I3 printer and autobed levelling was already enabled Z axis switch doesn't work. I tested with M119 code and it say z_min: open
when I press z switch it say z_min triggered.
X and Y works OK.

I also noticed when I press Z home in repetier, on LCD shows this G28 Z forbidden
Can't find what can be wrong.

### Steps to Reproduce

[Marlin-1.1.8_02212018_Geetech_i3_Pro.zip](https://github.com/MarlinFirmware/Marlin/files/2212975/Marlin-1.1.8_02212018_Geetech_i3_Pro.zip)

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by ghost** [comment]
#5824

That may help.

**Comment by Blisk** [comment]
I have installed bugfix 1.1.X and problem is solved.
