### ISSUE TITLE
[bugfix-1.1.x] Dual X carriage UBL Z axis lowers closer to bed on tool change

### ISSUE THREAD

**Issue by bruce356** [MarlinFirmware/Marlin#11330]
### Description
bugfix v1.1x commit 3bbb121
I have a problem with UBL on my dual X carriage Cartesian printer.
For every tool change to T1 the Z axis lowers closer to bed (by about 0.10 or 0.15 but the GLCD continues to show the correct height off bed for the first layer of 0.25mm ).
Print is printing a single layer test piece with multiple skirt outlines per tool.

Z remains at that lowered height when T0 is activated for printing at first layer the second time, on tool change back to T1 the Z axis lowers again closer to bed. Over several cycles, this results in the hotend nozzles crashing into the bed.

I think that some time back @thinkyhead became aware of this.

Note! When bed levelling is configured to use Bilinear the above Does Not occur.
Also when UBL is activated but the levelling numbers are all left at 0.00 the above does not occur.

Thanks and regards - bruce

### Steps to Reproduce

1. [First Step] download configure latest bugfix 1.1.x
2. [Second Step] print model requiring both extruders eg different colours
3. [and so on...] the problem shows up

#### Additional Information

[Marlin Dual-X Bilinear & UBL Configs.zip](https://github.com/MarlinFirmware/Marlin/files/2216621/Marlin.Dual-X.Bilinear.UBL.Configs.zip)

Thanks - Bruce

**Comment by bruce356** [comment]
Hi @Roxy-3D  and @thinkyhead I know your busy but is there any chance this would or could be rectified in the near future. If not what is the possibility of adding "save multiple Bilinear mesh points to eeprom" as for UBL  (0 to9 slots), as bilinear is working for me as it should but at present can only save one mesh.
 
By orcinus
[bugfix-1.1.x] Dual X carriage kinematics completely broken #10749
1. with hotend Z offset set up, every tool change to T1 appears to "shave off" the Z offset, but does not "restore" it on tool change back to T0 - in time, this results in a hotend crashing into the bed
** Issue 1 is UBL specific (just confirmed by disabling UBL).

Regards - bruce

**Comment by thinkyhead** [comment]
Let's consolidate the Dual X + UBL discussion at #11412.
