### ISSUE TITLE
G10/G11 Fwretract when using Mixing Extruder

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#11349]
Hi. When I use G10 / G11 using a mixing extruder (Diamond Hotend) the retraction uses the mixing ratio as retraction for each stepper motor instead of the full amount of retraction.

For example: If I have a 10mm retraction setup and my current tool uses a mixing ratio of 0.1/0.3/0.6 then each motor will retract as 1mm/3mm/6mm. Is there any way to make all of the motors retract the same amount of mm ignoring the tool mixing ratio ?

**Comment by ejtagle** [comment]
It should work like that: Retraction using the mixing ratio. What is the purpose of equal retraction ?

**Comment by sergiofagundes** [comment]
Example:
T0 ; Using a mixing ratio (1.0, 0.0, 0.0)
more gcodes here...
G10 ; end of layer retraction (on Simplify3D)
T1 ; New tool Using a mixing ratio (0.1, 0.3, 0.6)
G11 ; OPS!!! Problem, will unretract all 3 filaments, worst yeat - the 1st filament was retracted at 100% ratio but unretracted at only 10% ratio.

In repetier the G10/G11 will make an equal retraction. The purpose is to avoid ooze filament, jamming the hotend.

Mixing factors should be used for printing purposes. It would be nice to have an option to have the G10/G11 to use equal retraction or mixing ratio retraction.

**Comment by tcm0116** [comment]
I started working addressing this issue a few month ago before I moved. I should hopefully be able to get back to looking at it soon.

**Comment by sergiofagundes** [comment]
Hi tmc0116. Let me know if you get this issue fixed. Thank you.

**Comment by boelle** [comment]
@sergiofagundes is the problem gone with latest bugfix 2.0?

**Comment by tcm0116** [comment]
@boelle - this has been fixed

**Comment by boelle** [comment]
then either @sergiofagundes  or @thinkyhead should give the green close botton some love :-D

**Comment by sergiofagundes** [comment]
Hi. I have stopped using the diamond hotend so I can't test it. I'm using prusa mk3 mmu2 and have given up with diamond hotend.
