### ISSUE TITLE
[LPC1768] Software pull up/pull down resistors.

### ISSUE THREAD

**Issue by forkoz** [MarlinFirmware/Marlin#11347]
So as you know pull up/pull down is software settable on Sbase and other LPC boards. Does this mean they do not have external resistors for this like AVR? What's the value of this internal resistor? If it is different than 4.7kohm doesn't that throw off the temperature readings? I noticed the config option for different resistors in the temp sensor selection and my readings seem higher by a few degrees. Should I be turning this resistor off for my NPN SN08 as it probably has its own?

**Comment by p3p** [comment]
The ADC just reads the voltage it's up to the board to have the thermistor voltage divider, the Re-ARM and MKS SBase seem to have them set appropriately. There may very well be some variation from what you were reading with AVR as the hardware is completely different, the ADCs are "more accurate" at 12 bits but also more susceptible to noise (3.3v reference and just not being that good) being why they are so heavily filtered before even getting to Marlins normal filtering.

**Comment by forkoz** [comment]
I took a DMM and measured temperature resistor to ground. Its about 5.47K. There is like a 2 to 3 degree difference from my thermostat. Since all LPC pins have the internal resistor on by default does this mean the temperature probe has HW resistor + pullup active?

And then my probe using a temperature pin has 5.47k resistance too. Though I don't know if it means much since its active on positive voltage.. maybe just more ohms to overcome?

I moved probe to unused E1 pin and turned off the pullup.. I get better repeat-ability now go figure.

**Comment by gloomyandy** [comment]
Looking at section 15.4 of the following it looks like the pull up/down feature is only enabled for a digital input pin, when set as an analog input they will not be active.
https://www.nxp.com/docs/en/data-sheet/LPC1769_68_67_66_65_64_63.pdf

**Comment by p3p** [comment]
@gloomyandy That was my understanding but I just found this in the UM10360 lpc176x User Manual:

```
29.6.3 Accuracy vs. digital receiver
The ADC function must be selected via the PINSEL registers in order to get accurate
voltage readings on the monitored pin. The PINMODE should also be set to the mode for
which neither pull-up nor pull-down resistor is enabled.
```

So I'm double checking things now

**Comment by p3p** [comment]
@forkoz although as it says above it may be best practice to set the pin no pullup, no pulldown it doesn't appear to change the readings at all, so you may have to live with the couple of degree offset. (I will change it though as it could possibly effect reading stability)
