### ISSUE TITLE
Q: Any of marlin features that could make circle objects "fuzzy"

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#11353]
i'm trying to dialing in my tolerances and i get a strange fuzzy surface on circle objects

![simple test](https://user-images.githubusercontent.com/3832239/43144062-86c331ea-8f5c-11e8-9ff3-491cf82de4e9.png)

the outside of the box is crisp and sharp

but the inside of the box is not, and the same with the dish, resulting in that they fuse together

there needs to be at least 1mm in difference of diamter and they need to be printed next to each other to be able to push them together

any clue's and pointers are welcome

i did a thin wall object to make sure i dont over or under extrude
and i have also done a pid tune

**Comment by Blisk** [comment]
when I print from computer, circles are disaster and still don't know why, but when I print from SD card, circles are ok, like it should be.

**Comment by boelle** [comment]
hmm... and since octoprint is a computer it could be that

a few pics of it here: https://photos.app.goo.gl/rH8ByFgcM6VWKKk57

and my single wall cube test thing: https://photos.app.goo.gl/amKWv9rR59kRnWnP8

**Comment by boelle** [comment]
anyways dinner time, will print the same gcode from sd card later tonight, thanks for the tip

**Comment by Blisk** [comment]
exactly, I get the same, but when printing form SD card, circles are nice and smooth

**Comment by boelle** [comment]
yeah... when it prints the circles do not sound like one fluid and smooth montion

**Comment by boelle** [comment]
same gcode just copied to a sd card makes a huge difference

thanks for that one @Blisk  :-D

@thinkyhead are there any buffer since i could increase or am at the limit with mega+ramps?

**Comment by GMagician** [comment]
Maybe you can increse RX_BUFFER_SIZE (and let octoprint knows you have a bigger buffer. Repetier has a configuration parameter)

**Comment by boelle** [comment]
i will try that tomorrow :-D

**Comment by GMagician** [comment]
With mega2560 I'm using 1024 and in repetier I set 768

**Comment by Blisk** [comment]
I also have 2560 and will try this tomorrow, because I like to print it like before from PC. That worked for some time but now doesn't anymore.

**Comment by boelle** [comment]
Same here, but its time to get some sleep soon

i have done firmware changes etc so printer is ready, just need to make sure i have same code on sd card and octoprint so i can compare

**Comment by Roxy-3D** [comment]
If you print a sheet with a circle bored out of it...  What ever the diameter of the circle is, it will be less when it is printed.    Is that what is making stuff not fit correctly for you?

You might want to try it and use a micrometer on your printed part.

**Comment by jonathanweinberg** [comment]
You might want to have a read about this issue here (I’m not the author): http://lokspace.eu/bad-print-quality-with-usb-or-octoprint-the-solution-is-here/

EDIT: Since I read what I posted and it seems like an awful spammy way to post a link, the gist is you have to mess with `BLOCK_BUFFER_SIZE` / `BUFSIZE` / `DEFAULT_MINSEGMENTTIME`

**Comment by boelle** [comment]
@Roxy-3D nope its not the diameter that is the problem its the surface quality

when printing from sd card everything is ok

when printing from octoprint the surface gets fuzzy with a lot of micro "blobs"

**Comment by boelle** [comment]
@jonathanweinberg its not spammy if its helping :-D just got up so will have breakfast first

**Comment by boelle** [comment]
anyways, closing this one to reduce my footprint on the issue list, sd card printing is one fix but will have a look at  @jonathanweinberg link also
