### ISSUE TITLE
[Bugfix 2.x] SD use with  BOARD_AZSMZ_MINI and AZSMZ_12864

### ISSUE THREAD

**Issue by xamxamxam** [MarlinFirmware/Marlin#11350]
Hello
I use Marlin Bugfix 2.x in BOARD_AZSMZ_MINI and LCD AZSMZ_12864.
As you knowin this configiration there are 2 SD readers.
I noticed that the SD in Motherboard is used to be mounted as Disk in usb connection with pc and the SD in LCD is used to read and write from the "panel commands" for example to print directly from SD.
In this situation I can't write directly a gcode using the mounted disk.
Is there something to do in Conf to change this situation?
Is it normal?
Thanks

Massimo

**Comment by AnHardt** [comment]
> Is there something to do in Conf to change this situation?
Is it normal?

No.
Yes.

Simplified: Up to now both of the systems, Pc and Marlin, are buffering a bit of the SD content. If one of the sides would change content buffered on the other side, the other side wouldn't realize that. File system corruption is more than just likely then.
