### ISSUE TITLE
Please improve error messages for automation

### ISSUE THREAD

**Issue by AndKe** [MarlinFirmware/Marlin#11359]
### Description

"Error" or !! not used where it should ?

### Steps to Reproduce

if printer fail , outputting lines like this: 
![screenshot from 2018-07-24 22-38-42](https://user-images.githubusercontent.com/1468842/43165964-873015e2-8f95-11e8-8714-aac1825c99e3.png)

it won't be detected by any smart feature like: 
![screenshot from 2018-07-24 22-38-56](https://user-images.githubusercontent.com/1468842/43165872-4d0c4ab6-8f95-11e8-9242-9b8dd9c2625a.png)

**Expected behavior:** [What you expect to happen]

I would expect OctoPrint to stop

**Actual behavior:** [What actually happens]

OctoPrint continues, because there is no string like "Error:" or "!!" 
-and the original error is buried beyond buffer...

**Comment by thinkyhead** [comment]
That string is standardized and should be recognized (and handled) by hosts. You might want to submit a report about this to the OctoPrint project.

**Comment by AndKe** [comment]
is "Printer stopped" the string to look for , or , is there maybe a preceding message I missed, that should be handled as well ?

Thank you.  - I'll suggest that for OctoPrint once you answer.
