### ISSUE TITLE
Different preheat temp for dual hotends

### ISSUE THREAD

**Issue by xtendo-org** [MarlinFirmware/Marlin#11355]
Marlin supports dual extruder setup by setting `#define EXTRUDERS 2`. With a dual extruder printer, It is possible to use filaments of different material for each extruder. Obviously, they would have different printing temperature, so it would be desirable to have different "preheat" temps for E0 and E1. But the preheat part of `Configuration.h` is like:

    // PLA preset
    #define PREHEAT_1_TEMP_HOTEND 210
    #define PREHEAT_1_TEMP_BED     60
    #define PREHEAT_1_FAN_SPEED   255 // Value from 0 to 255

    // ABS preset
    #define PREHEAT_2_TEMP_HOTEND 240
    #define PREHEAT_2_TEMP_BED    110
    #define PREHEAT_2_FAN_SPEED   255 // Value from 0 to 255

So that there is only one "hotend" temperature for one preset. I've also checked the LCD screen UI, but Control → Temperature → Preheat PLA conf only shows:

* Temperature
* Fan speed: 255
* Nozzle: 210
* Bed: 60
* Store settings

Again, only one entry of "Nozzle."

As far as I've checked, this is not configurable and requires modification of code, so I presume this is a feature request.

**Comment by plloppii** [comment]
Go to ultralcd.cpp line 1682 and 1734, there you can see the code for the two material preheat menus. 
You can customize what kind of presets you want from there. Its not too hard to do, but let me know if you need any help.
