### ISSUE TITLE
Bug in 1.3.1 - LCD function "Stop Print"

### ISSUE THREAD

**Issue by jpralves** [MarlinFirmware/Marlin#1136]
It seems that the function lcd_sdcard_stop() - Called by the LCD "Stop Print" function - in file ultralcd.cpp is driving the X or Y axis to the far end due to this code:
```
+ #if X_MAX_POS < 250
+ plan_buffer_line(X_MIN_POS, 150, current_position[Z_AXIS]+20, current_position[E_AXIS], manual_feedrate[X_AXIS]/60, active_extruder);
+ #else
+ plan_buffer_line(X_MAX_POS-15, Y_MAX_POS-15, Z_MAX_POS-15, current_position[E_AXIS], manual_feedrate[X_AXIS]/60, active_extruder);
+ #endif
```
Its dangerous and in the case of the Hephestos should be removed. I've seen this behaviour several times in my Printer.

**Comment by boelle** [comment]
is this still an issue with a fresh copy of marlin and IDE updated to latest non-beta?

**Comment by jpralves** [comment]
Yes.

The correction doesn't work either.
I'll post a new correction (remove the code between the "ifdef")
As someone said before the "planner" is in a strange state after a stop so
it can do strange stuff.

Regards,

João

On Wed, Mar 11, 2015 at 8:58 AM, Bo Herrmannsen notifications@github.com
wrote:

> is this still an issue with a fresh copy of marlin and IDE updated to
> latest non-beta?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1136#issuecomment-78226097
> .

## 

Joao Alves

**Comment by boelle** [comment]
ok, when you submit the pull request then let us know issue # 1136  so we can close this one faster

**Comment by boelle** [comment]
did you post a new correction?

**Comment by paclema** [comment]
@jpralves is this issue of MarlinFirmware or bq/Marlin? https://github.com/bq/Marlin/pull/1

**Comment by boelle** [comment]
hmm.... i'm closing this one... this issue list if  for marlin only and not forks...

**Comment by jpralves** [comment]
I confirm.
The issue was for the hephestos fork.

Regards,

Joao

On Tue, Mar 17, 2015 at 7:25 PM, Bo Herrmannsen notifications@github.com
wrote:

> hmm.... i'm closing this one... this issue list if for marlin only and not
> forks...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1136#issuecomment-82554193
> .

## 

Joao Alves
