### ISSUE TITLE
Can't set Z probe offset

### ISSUE THREAD

**Issue by focamonca** [MarlinFirmware/Marlin#11375]
I'm on marlin 1.1.x

### Description

I have a Delta printer. (see the pics)
I've just upgraded it with Hiwin and new carbon rods.
I can't set the proper nozzle height and so the printer goes too close to the bed and don't extrude.

### Steps to Reproduce

- I have a nozzle based probe
- i have optic endstop
- This system always worked with this setup
- I upgraded marlin fw and back then i have this problem
- I tried + or - 0.4mm and even 1mm buth nothing changes

**Expected behavior:**   the nozzle height should change

**Actual behavior:** it stays always 3.4mm too low

#### Additional Information

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2232157/Marlin.zip)
![img_20180726_113046](https://user-images.githubusercontent.com/19846692/43265178-54b132aa-90e8-11e8-8994-1949728568d4.jpg)
![img_20180726_113051](https://user-images.githubusercontent.com/19846692/43265180-54cd83b0-90e8-11e8-8309-3cab35368e81.jpg)
![img_20180726_113103](https://user-images.githubusercontent.com/19846692/43265182-54ede0f6-90e8-11e8-9e43-8ae719b5b04c.jpg)
![img_20180726_113041](https://user-images.githubusercontent.com/19846692/43265183-550c5aea-90e8-11e8-8761-246ac7d58f6c.jpg)

**Comment by focamonca** [comment]
I updated the firmware to the bugfix version but it is always 0.5mm too close to the bed no matter the value I set on Z_PROBE_OFFSET

**Comment by thinkyhead** [comment]
The probe Z offset should be a small positive number for your setup.

You might want to try `M665 H` to adjust the delta height (the Z homed position). Try subtracting 0.5 from the current value (as shown by `M503`). Then do `M500` and re-home with `G28`.

**Comment by boelle** [comment]
@focamonca problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
