### ISSUE TITLE
[bugfix-2.0.x] bltouch stows when homing Z

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#11378]
The probe reacts fine to gcodes but when the printer homes, it does not deploy but stows. The print head crashes into the bed after that.
It worked fine yesterday and stopped working after I flashed 2018-07-26 05:58:28 -0500.

**Comment by GMagician** [comment]
It shouldn't but I think is something I did with bltouch. Maybe I saw where is the problem.

**Comment by GMagician** [comment]
@hamster65 try posted pr, it should fix

**Comment by tig33r** [comment]
Almost destroyed my head today too cause of failed homing Z axis ;/ Version before you bltouch commit is working good.

**Comment by GMagician** [comment]
@tig33r sorry, for sure it was not my intention

**Comment by tig33r** [comment]
No problem :) this is preety normal when you want to test new feature in beta or even alpha phase. 👍

**Comment by GMagician** [comment]
It should work now, see PR

**Comment by GMagician** [comment]
May you test #11397, it should be only a cosmetic thing, if ok post there and close this
