### ISSUE TITLE
[bugfix-2.0.x] AXIS_IS_TMC 

### ISSUE THREAD

**Issue by frech-tech** [MarlinFirmware/Marlin#11387]
Hey, 
in the newest bugfix the AXIS_IS_TMC function was implemented. Unfortunately the AXIS_IS_TMC doesn't return TRUE for all axis apart from XYZ. In the drivers.h the if conditions doesn't seem to work. E. g. #if ENABLED(Y_DUAL_STEPPER_DRIVERS) doesn't trigger although Y_DUAL_STEPPER_DRIVERS is enabled. 
I'm using TMC2130 on X, Y, Y2, Z, Z2 and E0.

**Comment by teemuatlut** [comment]
The issue is because `drivers.h` is included before `Configuration_adv.h` in `MarlinConfigPre.h`.
The order can't be changed as there are certain sections that rely on the new macros.

**Comment by teemuatlut** [comment]
https://github.com/teemuatlut/Marlin/tree/bf2_fix_smart_drivers

**Comment by thinkyhead** [comment]
I've applied a patch, so please give the latest code a test and see if it's compiling properly.

**Comment by boelle** [comment]
@JackDaFlow did you give latest bugfix 2.0 a go?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
