### ISSUE TITLE
[FR] UBL - Alter a mesh point using gcode 

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#11390]
Hello,

Is there the possibility to implement some gcode to edit by command any UBL mesh point?

It can be usefull to edit some wrong point by terminal command or scripts, for example, without using LCD.

**Comment by Roxy-3D** [comment]
* M421 - Set a single Z coordinate in the Mesh Leveling grid. X<units> Y<units> Z<units> (Requires MESH_BED_LEVELING or AUTO_BED_LEVELING_UBL)

**Comment by Roxy-3D** [comment]
That comment is wrong...   M421 works with Bi-Linear also.

**Comment by mtmello2003** [comment]
thats perfect! 

thank you and sorry I didnt find this gcode.
