### ISSUE TITLE
using multi bed multi thermistor 

### ISSUE THREAD

**Issue by nimajodan** [MarlinFirmware/Marlin#11401]
Hi what can I do if I want to use two beds instead of one. how can i add thermistors & sensors in marlin????

**Comment by GMagician** [comment]
Currently is not supported, you have to write code

**Comment by nimajodan** [comment]
hi tnx for  ur answer. there is another problem with  the hardware either. my ramps 1.4 only has 3  output 4 heaters but i'm going to need 1 more what can i do with that??

**Comment by thinkyhead** [comment]
External MOSFET controlled by 5V digital logic.
