### ISSUE TITLE
[2.0.x] Can't compile DUE with *_DRIVER_TYPE TMC2208

### ISSUE THREAD

**Issue by byebyedizzy** [MarlinFirmware/Marlin#11408]
Marlin 2.0.0 fails to compile for Arduino DUE board when any of *_DRIVER_TYPE is set to TMC2208.

Arduino IDE output:
```
----------------------------
Arduino: 1.8.5 (Windows 8.1), Board: "Arduino Due (Programming Port)"

Build options changed, rebuilding all
In file included from sketch\src\module/stepper_indirection.h:66:0,

                 from sketch\src\module/stepper.h:224,

                 from sketch\src\Marlin.cpp:36:

C:\Users\user\Documents\Arduino\libraries\TMC2208Stepper\src/TMC2208Stepper.h:9:28: fatal error: SoftwareSerial.h: No such file or directory

 #include <SoftwareSerial.h>

                            ^

compilation terminated.

exit status 1
Error compiling for board Arduino Due (Programming Port).
```

As far as I see the cause is unconditional include of SoftwareSerial.h in stepper_indirection.cpp - some boards have no SoftwareSerial implemented. And one of them is DUE.

**Comment by weed2all** [comment]
Hi man...have you managed to have tmc2208 uart on arduino due?i have arduino due + radds board and i realy want to have tmc2208 uart on this...

**Comment by thinkyhead** [comment]
@teemuatlut — Is this simply not possible for Due, or could it be patched in the future?

**Comment by teemuatlut** [comment]
HardwareSerial is supported, but there's no (official) SoftwareSerial library for the DUE platform.
Anyone is welcome to try to get [this ](https://github.com/antodom/soft_uart)working however.

**Comment by thinkyhead** [comment]
> Anyone is welcome to try to get this working however.

I put it on the TODO list…

**Comment by weed2all** [comment]
So any news on software serial for arduino due?

**Comment by teemuatlut** [comment]
No

**Comment by weed2all** [comment]
😣😣😣😣

**Comment by CypisPiotr** [comment]
Let me ask this - all we need is to configure soft_uart library to work with TMC2208Stepper ? 
I'm totally new to this, so be polite please.

**Comment by teemuatlut** [comment]
Something along those lines, yes.
