### ISSUE TITLE
[2.0.x] Z step loss with junction deviation enabled

### ISSUE THREAD

**Issue by alexyu132** [MarlinFirmware/Marlin#11405]
Enabling junction deviation seems to cause issues with the z axis during z-hops. During a hop the z raises correctly but doesn't drop back to the original z height, so every hop causes the z to incorrectly increase.

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2238369/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/2238373/Configuration_adv.txt)

Configs attached. Does junction deviation handle the case where the Z axis needs less aggressive values? Smoothieware includes a junction deviation value for the Z axis that can be tuned separately, but I don't see one in Marlin.

**Comment by hexane360** [comment]
AFAIK, junction_deviation allows for tuning of per-axis jerks through per-axis max accelerations. I don't know your printer setup, but 400 mm/s^2 seems pretty high for a leadscrew. Try lowering this and see if the problem still occurs. I have a very fine leadscrew, but 100 mm/s^2 is working for me. Issue #9917 is a good resource for troubleshooting junction deviation.

**Comment by alexyu132** [comment]
I'll try that, though unfortunately it looks like some areas of short segments still cause skips and layer shifting in the XY axes. Probably going to stick with traditional jerk for now.

**Comment by hexane360** [comment]
If that solved the Z axis, maybe your max accelerations are too high in XY as well, causing your layer shifting.

**Comment by alexyu132** [comment]
Lowering the junction deviation ended up fixing the Z problem. However, I've tested traditional jerk with up to 9000 accel and 80 jerk on my printer and it somehow didn't lose XY steps, so it's still possible that something's off about junction deviation. The worst parts seem like short segments like those in honeycomb infill - these cause the printer to seem to ignore any acceleration/junction speed limits and results in loud grinding noises from the steppers. Maybe CoreXY has something to do with it?

**Comment by thinkyhead** [comment]
> Maybe CoreXY has something to do with it?

Yes, I think junction deviation is probably unsuitable for CoreXY due to its methodology.
