### ISSUE TITLE
[Q] Laser support

### ISSUE THREAD

**Issue by tia777** [MarlinFirmware/Marlin#11410]
Hello all my friends . I can't figure out how to make a g-code for a laser with Marlin firmware . through what program can I send a ready G-code ? And what you need to do to be able to manage through the program grbl Control and Repetier-Host . who can help me suggest ?

**Comment by thinkyhead** [comment]
```cpp
#define SPINDLE_LASER_ENABLE
```

`M3` : Laser On, set PWM power
`M5` : Laser Off

Various programs can generate laser G-code through a plugin. For example there are a few Laser extensions for **InkScape**.

![image](https://user-images.githubusercontent.com/698003/47988592-41ed5300-e0a8-11e8-8f61-3f52439e05f8.png)
