### ISSUE TITLE
[Info] Layer shifting

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#11413]
Is this issue still present or has been fixed (or still waiting to get answers)?

**Comment by forkoz** [comment]
AFAIK, no. At least for LPC1768. I'm using 3us pulse and have never seen it because of that work around.

**Comment by houseofbugs** [comment]
Have many machines running the latest bugfix and it has not presented step loss. However there are random pauses with the new S curve acceleration and junction deviation enabled. I am going to disable 1/2 and see if the issue persists. I am opening a issue report now on that.
