### ISSUE TITLE
Creality3d CR-2020 motherboard support

### ISSUE THREAD

**Issue by sandro197802** [MarlinFirmware/Marlin#11427]
creality cr-2020 motherboard support in bugfix 2.0.x

I don't see anything about cr-2020 in Marlin supported boards, is it possible to support it?

**Comment by houseofbugs** [comment]
The best thing is to request source from Creality if you own the machine and then share it out so it can be added.

**Comment by sandro197802** [comment]
I asked it and received the .hex and, as soon as I understand, it's useless to extract the pinout of the board.
I have also requested a workable version without having a positive answer

**Comment by boelle** [comment]
well it seems that we have to start shout that they have gone closed source again

**Comment by sandro197802** [comment]
I'm thinking about flashing a ramps configuration on that board, I think it's a custom version with standard pinout. I'll check some pins to have confirmation

**Comment by boelle** [comment]
yeah you need a 100% trustworthy pin file at least

you will also need to put on a bootloader i think

**Comment by sandro197802** [comment]
Having the pinout will be the best, a pin.h good too. I also believe it hasn't the bootloader, this is another problem😓

**Comment by MachineryEnchantress** [comment]
Have asked every day this week...doing my best.

It's quite difficult now.

**Comment by boelle** [comment]
burning a bootloader is not the biggest issue, there are tons of examples on how to do that

but yeah, the board needs to defined in arduino ide so that you can tell it the correct bootloader to program on to the board

**Comment by boelle** [comment]
@sexycyborg 

no one demands more than your best, but you are the only one the world knows that have contact with Creality and that knows both the western world and how business is done in china

so you are a very famous person :-D

**Comment by sandro197802** [comment]
@sexycyborg 

Thank you so much for the effort you're putting to make these two worlds a bit closer.
Keep us informed about any news

**Comment by sandro197802** [comment]
@boelle burning it is easy but without a pinout I'n not sure about wiring between this board and Arduino uno

**Comment by boelle** [comment]
both boards will have a 6 pin connector and for burning just the bootloader you dont need a pinout, its a international standard

![image](https://user-images.githubusercontent.com/3832239/43660891-97f7feb2-9760-11e8-966f-8ef39a545f72.png)

**Comment by sandro197802** [comment]
Wow, thanks a lot 👌👌

**Comment by boelle** [comment]
most likely you will find a 6 pin somewhere on the creality board

and with a multimeter you can quickly find pin 2 and 6 :-D it should give you 5v when powered

**Comment by boelle** [comment]
btw how does the board inside the printer look like?

**Comment by sandro197802** [comment]
I found it and I can read pin numbers on the pcb 👍🏻

**Comment by sandro197802** [comment]
![img_20180803_172535](https://user-images.githubusercontent.com/36819019/43661539-f8c4d2ea-9762-11e8-9847-717f655209cf.jpg)
![Uploading IMG_20180803_172542.jpg…]()

**Comment by boelle** [comment]
this is just an example guide: https://www.instructables.com/id/Flashing-a-Bootloader-to-the-CR-10/

it might be a different board but most of it will be the same

**Comment by boelle** [comment]
sorry for asking so much, but what model printer is it? i might be able to find a guide for your precise printer

**Comment by sandro197802** [comment]
It's a creality3d cr-2020, nothing found on the web

**Comment by boelle** [comment]
this one: https://www.gearbest.com/3d-printers-3d-printer-kits/pp_608133.html

?

**Comment by sandro197802** [comment]
I like this board, it looks robust and well designed, but its original firmware is too poor. I don't want to change the board with another, I rather send the printer back and buy a Wanhao D6 or a monoprice maker ultimate

**Comment by sandro197802** [comment]
Yes, that one

**Comment by boelle** [comment]
can you see what text is on the big chip in the middle of board?

but yes looks like a nice printer

we need to make sure we put on the correct bootloader for this board

**Comment by sandro197802** [comment]
It's a mega2560

**Comment by sandro197802** [comment]
But burn bootloader without a firmware to flash is useless right now

**Comment by sandro197802** [comment]
What's the best way to map pins on a board?

**Comment by boelle** [comment]
yes but we can prepare as much as possible

**Comment by boelle** [comment]
hmm.... the slow but best way is to track wires from chip to stepper drivers and fet's(transistors)

**Comment by sandro197802** [comment]
Does a multimeter help?

**Comment by boelle** [comment]
nope.... you have to look at pin one on big chip, where does that go.... then pin 2....

very slow work but its the most precise way

of course we can hope @sexycyborg has more luck

**Comment by boelle** [comment]
anyways... its getting late here so i will go to bed very soon

will be arround tomorrow

**Comment by sandro197802** [comment]
Thanks for your help, 
Have a good night😉

**Comment by silentninja1** [comment]
FYI, I have a nearly working build on one of these I had started awhile ago. IIRC all I was missing was the power enable pin. Ill dig it back up and go over it again soon.

**Comment by houseofbugs** [comment]
@silentninja1 can you share the pins for that board? Been trying to get Creality to release source and it's falling on deaf ears.

**Comment by houseofbugs** [comment]
Also that 2560 should NOT need the bootloader. I don't have that board to test but typically only the 1284P boards need the bootloader burned.

**Comment by Roxy-3D** [comment]
> FYI, I have a nearly working build on one of these I had started awhile ago. IIRC all I was missing was the power enable pin. Ill dig it back up and go over it again soon.

If somebody has a machine with the Power Enable Pin wired up....   It should not be too hard to find out what pin it is on using M43.     Even an LED can be used to find the correct pin number.   And at that point, you could add it to your almost correct Configuration.h files and have a reverse engineered setup.

**Comment by silentninja1** [comment]
Ive talked to Tim a bit offline here, but neither of us has actual hardware to find the last remaining pin with. Ill see about getting something in hand at some point to finish following it back.

**Comment by sandro197802** [comment]
@sexycyborg Am I too optimistic hoping in a creality source code release?

**Comment by thinkyhead** [comment]
@sandro197802 — Keep nagging Creality3D. They need to be reminded we are here.

**Comment by MachineryEnchantress** [comment]
I ask a couple of time a week, have no idea why they are making such a big deal of it...

**Comment by sandro197802** [comment]
I don't understand too... This printer needs some basic Marlin feature such as MBL for its concave plate. I cannot recommend this printer to any other people that ask me, I seggest wanhao D6 or Monoprice maker ultimate because of the possibility to flash Marlin

**Comment by sandro197802** [comment]
@thinkyhead Here in Italy we say "There is no worse deaf than those who do not want to hear"...

**Comment by sandro197802** [comment]
I'm going ahead by myself 
![img_20180829_192632_410](https://user-images.githubusercontent.com/36819019/44804402-8698d180-abc1-11e8-89e6-11005abd63e4.jpg)

**Comment by sandro197802** [comment]
https://youtu.be/oZoFR2P4yrg

**Comment by sandro197802** [comment]
Creality3d has finally released the source code!!!
