### ISSUE TITLE
Endstop PWM on einsy Rambo

### ISSUE THREAD

**Issue by Djamuka** [MarlinFirmware/Marlin#11426]
Hi there, I have an Eisny Rambo 1.1a and use the sensorless endstop, with this option I have two more Pin from the X and Y endstop and they are PWM.
So I wanted to connect an RGB strip LED and control it with PWM, the pin définition for RGB LED:
```cpp
  #define RGB_LED_R_PIN 12
  #define RGB_LED_G_PIN 5
  #define RGB_LED_B_PIN 11
  #define RGB_LED_W_PIN -1
```
Pin 5 work as expected, but pin 11 and 12 just don't PWM it's 1 or 0 !!! what's wrong? can I use this pin with PWM or there's something that block the use?

Thanks for the answer.

**Comment by thinkyhead** [comment]
Pin 5 uses timer 3A. Pins 11 and 12 use timer 1A and 1B. Timer 1 is reserved by Marlin. You can enable `PINS_DEBUGGING` and use the `M43` command to get details about the pins on your board. Pins associated with timer 5 may be the best choice, if available.
