### ISSUE TITLE
[Info] M125 with SDSUPPORT

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#11428]
What is the purpose of M125 when SDSUPPORT is enabled?

I tried to raise this command when I was printing with repetier, head moved to park position and immediately restarted printing but with wrong Z position (raised)

**Comment by thinkyhead** [comment]
At present, if `SDSUPPORT` is enabled, `M125` will not pause. When `SDSUPPORT` is enabled it should probably check whether an SD print is in progress and if not then call `wait_for_filament_reload`.

**Comment by GMagician** [comment]
> wait_for_filament_reload

That what is missing I think. Only pause is called and no resume at all. I think that this may lead to bad behaviour.

**Comment by thinkyhead** [comment]
The above-linked PR should do the right thing.
