### ISSUE TITLE
Bug BLTouch/3DTouch - Nozzle crash in bed glass

### ISSUE THREAD

**Issue by nacho87** [MarlinFirmware/Marlin#11420]
I configure the bl touch/3d touch in the new version of marlin and in the bugfix 2 but the Deploy and stow of the 3d touch work only in the menuin the lcd but if use Auto - Home option in the lcd ,the 3d touch don't deploy the sensor and the nozzle crash in the bed.

Thanks

**Comment by GMagician** [comment]
Please post your configuration

**Comment by nacho87** [comment]
@GMagician 

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2247382/Configuration.zip)

Is the configuration.h that appear in "example_configurations\Geeetech\Prusa i3 Pro B\bltouch" with some modifcations in the steps

**Comment by GMagician** [comment]
Try enabling Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN as I think this is what you have and use zmin input for bltouch.

**Comment by nacho87** [comment]
@GMagician Great, thanks works again , thank you. sorry for bother with this issues. If you want i can send on PR for change the file "example_configurations\Geeetech\Prusa i3 Pro B\bltouch" or add one comment in the readme.md about this thing.
I think the gt2560 rev a+, had the pin for the servo but the other without the plus dont have this pin and is necessary user the z_max pin. 

You can close this

**Comment by GMagician** [comment]
@nacho87 I can't close it, you have to do it
