### ISSUE TITLE
filament sensor on marlin 1.19

### ISSUE THREAD

**Issue by stefi01** [MarlinFirmware/Marlin#11423]
I transfered all the settings from marlin 1.18 to 1.19 and i get an error with the filament width sensor.
works as it should without problem in 1.18 and the settings were double checked against 1.18

temperature.cpp:1067: error: 'FILWIDTH_ERROR_MARGIN' was not declared in this scope

     if (ABS(filament_width_nominal - filament_width_meas) <= FILWIDTH_ERROR_MARGIN)

                                                              ^

sketch\temperature.cpp: In static member function 'static void Temperature::readings_ready()':

temperature.cpp:1752: error: 'raw_filwidth_value' was not declared in this scope

     current_raw_filwidth = raw_filwidth_value >> 10;  // Divide to get to 0-16384 range since we used 1/128 IIR filter approach

                            ^

**Comment by GMagician** [comment]
Post configuration.h and configuration_adv.h. Missing define should be in latter file

**Comment by stefi01** [comment]
Here are the files, github would not let me upload the original file format so converted them.
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2251323/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/2251324/Configuration_adv.txt)

**Comment by Scratchbuild52** [comment]
I have the same problem. I saw it is declared but in a different place than 1.18. Can you please look at this.

Regards

**Comment by thinkyhead** [comment]
Now patched in the bugfix branches.

**Comment by ve3sjk** [comment]
Can you tell me where to find the fixed files i just turned on the Filament sensor and i am also receiving the error: 'FILWIDTH_ERROR_MARGIN' was not declared in this scope and the display is showing zero for filament reading with 1.80 volts on A5

**Comment by stefi01** [comment]
i am getting the same error, coppied exactly as it was in 1.18 so i stayed
at 1.18 as it works with that version

**Comment by ve3sjk** [comment]
Thanks for the reply I will download 1.1.8 from the repository
And do a comparison against 1.1.9 and try and make the
Changes needed to get it working in the newest version.

**Comment by ve3sjk** [comment]
I posted a way to fix the compile error in 1.1.9 to the open ticket
On github. Basically moving 3 lines of code in the temperature.cpp
File. This allowed compile and seems to get the sensor working.

Regards,
Steve

**Comment by stefi01** [comment]
I downloaded the latest bug fix marlin, transferred all the settings yet again from 1.1.8 to 1.1.9 without any further changes and it compiled and uploaded with out problem, all works now 👍
