### ISSUE TITLE
[2.0.x] Z_Min gets ignored after a finished print

### ISSUE THREAD

**Issue by Seref** [MarlinFirmware/Marlin#11436]
When starting the Printer it (mostly) works fine, homing (G28 in the gcode not over the menu) works and it stops when MIN_Z is triggered.

After I finished a print and start another one MIN_Z triggers but it ignores it for some reason until I manually home it again over the menu or restart the printer.

Im using a kfb2.0 board which is basically an Atmega2560 and a Ramps 1.4 EFB on one board and an inductive probe (which also lights up and I rechecked the cables they are all working).

**Comment by GMagician** [comment]
Limit switches are checked only while homing. If you need a constant check you have to enable ENDSTOPS_ALWAYS_ON_DEFAULT or play with M120, M121 in your gcode

**Comment by Seref** [comment]
@GMagician I don't need a constant check, after I finished printing I printed something else and during that homing sequence the MIN_Z triggering didnt stop the Z Axis. Because of that the hotend rammed the heatbed, this happened two times.

**Comment by GMagician** [comment]
ops sorry, misunderstood

**Comment by GMagician** [comment]
Thid is what I didn't undestood:

> After I finished a print and start another one MIN_Z triggers but it ignores it for some reason until I manually home it again over the menu or restart the printer.

So you are saying that during second print (where you have in gcode G28) it crash on the bed while homing?

**Comment by Seref** [comment]
Yes, I either have to manually home over the lcd menu (this only worked one time when it crashed) or restart the printer.

I'm using `#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN` and didnt really change much, it worked reliably well on 1.1.x-bugfix.

And like I said for some reason this only happens when I dont turn off/reset the printer and directly start another print from the sd card (or serial) the prints normally start with G28 and then G29 but it already crashes on G28.
