### ISSUE TITLE
[FR] StealthChop / Spreadcycle LCD menu

### ISSUE THREAD

**Issue by pipersw** [MarlinFirmware/Marlin#11442]
Could you add a menu in LCD in case of use TMC2130 for switching between StealthChop or Spreadcycle mode ? it could be usefull for testing purpose or if we would be quiet at night and powerfull the day without the need of re compiling the code

**Comment by Atatoth** [comment]
Good idea :)

**Comment by oakdesign** [comment]
If you TMC are configured in hybrid mode you already have this Basic function on Hand just with M913 set the threshhold Speed to a value that the Driver will not Switch and stay in the desired mode

**Comment by teemuatlut** [comment]
It's coded and coming. No timetable though at this point as there are quite a few items on the list before this one.

**Comment by Seref** [comment]
Would this also be possible on TMC2208?

**Comment by Flawl3ssSWE** [comment]
Seref, I don't think so since the TMC2130 can be controlled from the firmware (SPI) and is there able to set the different modes, but the TMC2208 is configured thru UART and not thru the firmware.

**Comment by Seref** [comment]
@Flawl3ssSWE but according to the spec sheets you can even though it's over UART and not SPI controll the driver and set the modes over that. And Marlin also offers an option to use the UART connection of the TMC2208.

http://marlinfw.org/docs/hardware/tmc_drivers.html

**Comment by teemuatlut** [comment]
> Would this also be possible on TMC2208?

Yes.

**Comment by oakdesign** [comment]
https://up.picr.de/33495745bo.jpg
2208 Wired die UART Firmware comm

**Comment by boelle** [comment]
@pipersw still with us?

**Comment by pipersw** [comment]
Yes, I am on Duet 2 wifi now but I follow for some people on TMC2208 and 2130

**Comment by sjasonsmith** [comment]
@boelle, I think this is done and can be closed? I used that menu today!

I can't confirm that it works with TMC2130 drivers, but it was there with my 2208s!

**Comment by pipersw** [comment]
Thx
