### ISSUE TITLE
DIRECT_MIXING_IN_G1 question

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#11448]
Using a diamond hotend 3in1out - with this option enabled in firmware can I use the following code:

G1 E-15 A0.33 B0.33 C0.34  ; I want to mimic the Repetier fwretract (all steppers retracting 5mm each)

1) Is this that DIRECT_MIXING_IN_G1 option allows to do ?
2) Will this code affect the current mix factors (active tool) ?

**Comment by thinkyhead** [comment]
1. That is correct
2. Yes. It overwrites the current mix factors.

**Comment by boelle** [comment]
@sergiofagundes 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
