### ISSUE TITLE
TMC2130 OT prewarn

### ISSUE THREAD

**Issue by madmattco** [MarlinFirmware/Marlin#11451]
### Description

I keep getting ot prewarn errors for my x and e drivers upon boot.
I am using genuine drivers for this.
I have tried every free digital pin there is and also using software spi.
Always the same result. So far I have seen this on both 1.1.x bugfix, 1.1.8, 1.1.9, 2.0.x bugfix.
Also, even though Z is shown in a working state, I get strange vibrations when I move the Z axis.

Here is my current config
[TEVO_BLACK_WIDOW_Marlin_1.1.8_BLT.zip](https://github.com/MarlinFirmware/Marlin/files/2259289/TEVO_BLACK_WIDOW_Marlin_1.1.8_BLT.zip)

Here is the debug log.
```
Recv: 		X	Y	Z	E0
Recv: Enabled		false	false	false	false
Recv: Set current	500	500	600	1000
Recv: RMS current	489	489	581	550
Recv: MAX current	689	689	819	776
Recv: Run current	15/31	15/31	18/31	17/31
Recv: Hold current	7/31	7/31	9/31	8/31
Recv: CS actual		31/31	31/31	9/31	31/31
Recv: PWM scale	255	18	1	255
Recv: vsense		1=.18	1=.18	1=.18	1=.18
Recv: stealthChop	true	true	true	true
Recv: msteps		0	0	16	0
Recv: tstep		4294967295	4294967295	4294967295	4294967295
Recv: pwm
Recv: threshold		247	247	164	40
Recv: [mm/s]		0.00	0.00	0.00	0.00
Recv: OT prewarn	true	false	false	true
Recv: OT prewarn has
Recv: been triggered	false	false	false	false
Recv: off time		15	5	5	15
Recv: blank time	54	54	54	54
Recv: hysterisis
Recv: -end		12	12	12	12
Recv: -start		8	8	4	8
Recv: Stallguard thrs	0	0	0	0
Recv: DRVSTATUS	X	Y	Z	E0
Recv: stallguard		X			X
Recv: sg_result		1023	0	0	1023
Recv: fsactive		X	X	X	X
Recv: stst		X	X	X	X
Recv: olb		X		X	X
Recv: ola		X	X		X
Recv: s2gb		X	X		X
Recv: s2ga		X			X
Recv: otpw		X			X
Recv: ot		X			X
Recv: Driver registers:
Recv: 	X = 0xFF:FF:FF:FF
Recv: 	Y = 0xFF:FF:F8:00
Recv: 	Z = 0xC1:FF:00:0F
Recv: 	E0 = 0xFF:FF:FF:FF
```

**Comment by teemuatlut** [comment]
There are some improvements coming to the monitoring logic but in the end the fact is that the logic is only acting upon the information it received from the driver. And your drivers gave an output of all high, which makes Marlin think the driver has all the possible problems. This of course is not a valid response and should be treated as such. Just not yet in the upstream branches.

You can either disable the monitoring or if you want, you can try my dev branch once I get it online and see if that makes a difference. This might possibly happen tomorrow.

**Comment by Kochleffel** [comment]
same Problem here,
Monitoring is of for testing. sensorless homing doesnt work.
```
23:11:25.827 : N18 M122*27
23:11:25.831 : X	Y
23:11:25.831 : Enabled		false	false
23:11:25.834 : Set current	500	500
23:11:25.837 : RMS current	883	883
23:11:25.837 : MAX current	1245	1245
23:11:25.840 : Run current	15/31	15/31
23:11:25.842 : Hold current	7/31	7/31
23:11:25.842 : CS actual		4/31	0/31
23:11:25.845 : PWM scale		255	0
23:11:25.848 : vsense		0=.325	0=.325
23:11:25.848 : stealthChop	true	false
23:11:25.851 : msteps		0	256
23:11:25.851 : tstep		4294967295	0
23:11:25.854 : pwm
23:11:25.854 : threshold		0	1581
23:11:25.856 : [mm/s]		-	100.02
23:11:25.856 : OT prewarn	true	false
23:11:25.859 : OT prewarn has
23:11:25.862 : been triggered	true	false
23:11:25.862 : off time		15	0
23:11:25.865 : blank time	24	16
23:11:25.865 : hysteresis
23:11:25.865 : -end		12	-3
23:11:25.867 : -start		8	1
23:11:25.867 : Stallguard thrs	8	8
23:11:25.870 : DRVSTATUS	X	Y
23:11:25.870 : stallguard		X
23:11:25.874 : sg_result		1023	0
23:11:25.874 : fsactive		X
23:11:25.874 : stst		X
23:11:25.876 : olb		X
23:11:25.876 : ola		X
23:11:25.876 : s2gb		X
23:11:25.879 : s2ga		X
23:11:25.879 : otpw		X
23:11:25.879 : ot		X
23:11:25.882 : Driver registers:	X = 0xFF:04:FF:FF
23:11:25.884 : Y = 0x00:00:00:00
```

all fine on Marlin-bugfix-1.1.x

**Comment by madmattco** [comment]
Any update on your dev branch?

**Comment by teemuatlut** [comment]
It's uploaded as the `master` branch, but doesn't work currently. I'm looking into it later today as I need to start making PRs to upstream.

**Comment by madmattco** [comment]
Any luck yet

**Comment by gericho** [comment]
So, a temporary workaround I found, is to enable #define EEPROM_SETTINGS in configuation.h, then just after the boot, give a M502 to load factory (coded) settings, and save them with M500, after this I can home G28 XY without crashing. The problem comes only with the 1.1.9 since it works on the 1.1.8. And yes, the M122 gives "Recv: OT prewarn false true false" (where is false false false on 1.1.8) so a prewarn OT error on the Y axis, that is exactly the one that I can't home without crashing. To be noted, the cables and drivers are OK, I already swapped them just in case and receive the OT error always on the same axis.

**Comment by gericho** [comment]
Updating TMC2130 library to 2.5.0 and using Marlin 2.0.x+ solved the issues alltogether

**Comment by boelle** [comment]
@madmattco did bugfix 2.0 also fix it for you?

**Comment by boelle** [comment]
@thinkyhead think we can close this one
