### ISSUE TITLE
(Question) Max X Y Z Position

### ISSUE THREAD

**Issue by tscheims1** [MarlinFirmware/Marlin#11454]
I'm going to build a large printer (e.g. 4m x 2m x1.5m). is there a limitation in the X Y Z maximum distance or is there a limitation in the maximum movement distance?

**Comment by AnHardt** [comment]
The axis length in mm is theoretically nearly unlimited (float).
The axis length in steps is limited to be a int32.
So as long there is a reasonable value for steps/mm 4m should be fine.

MAX_INT32 / axis_length > steps/mm

**Comment by tscheims1** [comment]
Thank you for the clarification.
