### ISSUE TITLE
Stepper not moving when activating PIDTEMPBED

### ISSUE THREAD

**Issue by samuel9554** [MarlinFirmware/Marlin#11456]
My board is a Printrboard REV E.

When I enable PIDTEMPBED the stepper will not move.

Anyone having the same issue?

I use the fork from Marcio at this link.

https://github.com/marcio-ao/Marlin/tree/pr-M425-backlash-compensation/Marlin

**Comment by fg89o** [comment]
I have the same problem. I am using Arduino Mega + RAMPS 1.4 with the official release 1.1.9.

Did you solve it?. Please share. Thank you.

**Comment by Thairay** [comment]
Try m502 m500. Somehow fixed it for me.

**Comment by fg89o** [comment]
Today I reuploaded the version 1.1.8 and everything worked fine. Then I tried again the version 1.1.9 with no luck.

Tomorrow I will try your suggestions and I will report the results here.

**Comment by fg89o** [comment]
@Thairay thank you very much. Your solution fixed my problem too.

I used today version of bugfix branch.

**Comment by thinkyhead** [comment]
Always do `M500`, `M502` on any new installation of Marlin, and always do this before reporting issues as well, since very often it's just old EEPROM data confusing the firmware.
