### ISSUE TITLE
Request for Servo initial position on start

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#11453]
I would like to make a request for next version of Marlin to allow initiallization of servo positions on startup of Marlin. Something like #define SERVO_START_POS {90, 120, -1, ...}, so on startup servo0 moves 90o, servo2 120o, servo3 (-1) don't move....

**Comment by thinkyhead** [comment]
We'll be adding a feature in the near future allowing users to specify G-code to run on various events, including startup. So servos could be moved using that feature, if needed.
