### ISSUE TITLE
SLIM_LCD_MENUS Question

### ISSUE THREAD

**Issue by MstrVLT** [MarlinFirmware/Marlin#11455]
https://github.com/MarlinFirmware/Marlin/blob/f816d6f70fd15b351634d0545ef2b8302853bf46/Marlin/ultralcd.cpp#L178

I set SLIM_LCD_MENUS and CR10_STOCKDISPLAY i see empty Control menu. Can it be better to make an additional condition?

**Comment by thinkyhead** [comment]
Marlin 1.1.x is end-of-life and won't be getting any more patches. Marlin 2.0.x should do better in this area.
