### ISSUE TITLE
1.1.9+ Will not fit on some controller boards

### ISSUE THREAD

**Issue by JimF42** [MarlinFirmware/Marlin#11474]
### Description

I guess this will just be more of an FYI for the developers/maintainers of Marlin, but 1.1.9 no longer fits on my controller board. It's an ANET board for my A6 printer. the Arduino compiler tells me that the compiled image will not be able to load on to the board. It turns out that I am short 920 bytes.

My rig has an added auto bed leveler that I have added to the configuration.h files, so perhaps an image without auto bed leveling will still fit.

I do understand that I don't actually have a "leading edge" controller here and that if I want to actually run 1.1.9 and probably 2.x, I will now need to start swapping out hardware.

I am more mentioning it since you may still have a call for 1.1.8 for a while because of this, or at least until these cheap controller boards start coming out with more memory.

**Comment by marcio-ao** [comment]
@JimF42: I may be mistaken, but I think the ANET uses an ST7920 display. If so, you may want to try the "LIGHTWEIGHT_UI" option in "Configuration_adv.h" and see if it helps get you under the limit.

**Comment by JimF42** [comment]
@marcio-ao Actually, all I know for sure is that it is a dot-addressable display as opposed to a character display. I don't know the model number of the display.

When I look on this site, https://3dprint.wiki/reprap/anet/a6, it says the machine has a 12864 display and does indeed resemble this one on Amazon (the buttons are laid out different on mine, but it uses the dual ribbon cables, etc.) https://www.amazon.com/Sintron-Graphic-Display-Controller-Printer/dp/B06WP8BSBB

Is this the same as a ST7920? If so, where can I find out what LIGHTWEIGHT_UI actually means, I don't seem to see any docs on how it will be different.

When I look in my configuration.h file the following display settings are enabled.

    //
    // SAV OLEd LCD module support using either SSD1306 or SH1106 based LCD modules
    //
    //#define SAV_3DGLCD
    #if ENABLED(SAV_3DGLCD)
      //#define U8GLIB_SSD1306
      #define U8GLIB_SH1106
    #endif
    ...
    //
    // ANET and Tronxy Graphical Controller
    //
    #define ANET_FULL_GRAPHICS_LCD    // Anet 128x64 full graphics lcd with rotary encoder as used on Anet A6
                                      // A clone of the RepRapDiscount full graphics display but with
                                      // different pins/wiring (see pins_ANET_10.h).

**Comment by marcio-ao** [comment]
@JimF42: The lightweight GUI was an option I added for our printers. Rather than using just bitmaps, it uses a hybrid graphical/text-mode that takes advantage of the built-in character generator in the ST7920 chip. I didn't write it with the intent to save PROGMEM, so I haven't tested it to see whether it does, but it is possible that it will prevent the larger bitmaps from loading and save you a few bytes.

I do not know for sure whether your display has the correct chip to make it work, but you can try it real fast by uncommenting the following line in "Configuration_adv.h":

```
//#define LIGHTWEIGHT_UI
```

If your display comes up garbled, or does not work, then it means it is not compatible.

**Comment by tobecwb** [comment]
I'm using a Arduino Mega 2560, with SD Card, Graphic Display, Bed Leveling with 3d touch sensor, TMC2130, and some other functions. All this option don't "fit" on Arduino Mega, even with `LIGHTWEIGHT_UI`. I have to disable the SD Card function (I'm using Octoprint, so, don't need anymore), or reduce the level bed probe points.

**Comment by JimF42** [comment]
@tobecwb Interesting points... I was looking at other boards if I wanted to upgrade and I _assumed_ that the Mega would have had more PROGMEM (I have 124 KB on my Anet board). I guess I need to look closer when I get serious about that.

And yes, disabling the SD Card support now gives me just under 16K bytes left. I too am using Octoprint and don't need SD support.

**Comment by thinkyhead** [comment]
Tim Hoogland (@houseofbugs) is doing a lot of work to reduce the binary size in his fork of Marlin. Try https://github.com/houseofbugs/TH3D-Marlin/releases and see if they help.

**Comment by roel8032** [comment]
I have the same problem.
The software does not fit on the Anet A6 board. But when i switch back to:
#define LCD LANGUAGE en
in configuration.h it fits.
not with:
#define LCD LANGUAGE nl

**Comment by roel8032** [comment]
It fits on Anet A6 when you comment (in file configuration.h):

//#define EEPROM_CHITCHAT   // Give feedback on EEPROM commands. Disable to save PROGMEM.

**Comment by Atatoth** [comment]
What for is chitchat then??

**Comment by roel8032** [comment]
Don't know yet
