### ISSUE TITLE
Z position unknown after autohome

### ISSUE THREAD

**Issue by ryandeleon1** [MarlinFirmware/Marlin#11482]
I recently updated the firmware on my Gmax Gcreate 1.5+ to Marlin 1.1.8

Now after autohoming the printer the x and y positions read the correct values but the z position will read a set of characters. "*,-(" on the LCD screen. After this happens the printer will not move in the z direction and autohoming the printer again causes head to raise in the z direction indefinitely until it is turned off.

**Comment by thinkyhead** [comment]
### Z: *,-(

So, Z is obviously at Pirate height.

What does `M114` say after you do a `G28`?

**Comment by ghost** [comment]
Im having the same problem. M114 returns:
```
X:197.00 Y:228.00 Z:0.00 E:0.00
Count X:15760 Y:18240 Z:-214783648
```

**Comment by thinkyhead** [comment]
Do you see the same issue in 1.1.9?

**Comment by ghost** [comment]
They have not released their version of 1.1.9 yet.

**Comment by thinkyhead** [comment]
Try updating their configuration files for 1.1.9, which has hundreds of patches since 1.1.8. We don't patch old versions, so 1.1.8 will forever be as it is today.

**Comment by boelle** [comment]
@ryandeleon1 is problem gone if you use bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead think we can close this one
