### ISSUE TITLE
[1.1.9] CUSTOM_USER_MENUS

### ISSUE THREAD

**Issue by roel8032** [MarlinFirmware/Marlin#11481]
In Version: 1.1.9
If the following code is made:

 #define USER_DESC_4 "Bedleveling > Z4"
 #define USER_GCODE_4 "\nG28\nG29" "G90" "nG0 X100 Y100 F5000\nG1 Z4 F5000"

The machine excutes:
1. G28 and G29
2. "\nG28\nG29" "G90" "nG0 X100 Y100 F5000\nG1 Z4 F5000"
3. The end script code writen in configuration.h
#define Z_PROBE_END_SCRIPT "G1 X100 Y190 F5000\nG1 Z10"

Result is that the machine does not stop at, the position in 2.
But in the endstript position.

Second problem:
In the CUSTOM_USER_MENUS you can place movements.
The machine starts to move, unless G28 and/or G29 is done.
Result: the machine goes beyond the limits.

**Comment by thinkyhead** [comment]
```
#define USER_GCODE_4 "\nG28\nG29" "G90" "nG0 X100 Y100 F5000\nG1 Z4 F5000"
```

That's all kinds of screwed up. There should always be a `\n` between commands.
