### ISSUE TITLE
#define NOZZLE_PARK_FEATURE  WHY IT'S GOING ALL WAY UP ?

### ISSUE THREAD

**Issue by bogaskilop** [MarlinFirmware/Marlin#11497]
### Description

I just  configured  1.1.9  and set like in 1.1.6 or 1.1.8  park position to 👍 
#define NOZZLE_PARK_POINT { (X_MIN_POS + 314), (Y_MIN_POS ) }

and I wanted to start a print and just after  G28 and G29 it' moving all the way up on Z axis  ( to Z MAX to XY park point?

in 1.1.6 or 1.1.8  after G27 it goes on same Z height  to xy from nozzle_park_point and really prefer that 
than moving  all the way up on Z axis before print or over filament change.

**Comment by bogaskilop** [comment]
today i got  some time and i downloaded  rc bugfix again  and  still same situation how can i make it to work like in 1.1.6  marlin so  nozzle park position will be  xy which i set in configuration.h  and Z   on same level or  +5 on Z from current Z position ? 

normaly after G29  i got G27  adn it goes   to my park position 👍 
#define NOZZLE_PARK_POINT { (X_MIN_POS + 314), (Y_MIN_POS ) }

and o Z is  10 mm in that position so how to set it like that  in 1.1.9 or 1.1.x bugfix ?

that Z axis will go up for about 10 mm or 5 mm and not all the way up to Z MAX ?

**Comment by MoellerDi** [comment]
did you try:
```cpp
#define NOZZLE_PARK_POINT { (X_MIN_POS + 314), (Y_MIN_POS ), 5 }
```
According to the config file a park position is defined as { X, Y, Z }, not sure but it seems you missed Z.

**Comment by bogaskilop** [comment]
MoellerDi 

yes I wasnt using Z in 1.1.6   and in default 1.1.6  Z stays on same level   when pause was pressed and G27 executed.  becouse when you let say set up my x y park position and add Z 5 mm   and you already with biger model on your build plate  let say you presed pause or want to change filament  and pritn is already  higher  than 5 mm on Z   let say it is alredy on 100  it will crash into model moving to Z 5 :(

thats why I wan to know how to set Z position to stay in same level when pause was executed.

**Comment by thinkyhead** [comment]
> it will crash into model moving to Z 5

The Z element is a raise, not a position.

**Comment by bogaskilop** [comment]
Ok Thinkyhead i will try this  but please explain me  why it goes all the way up to Z_max if Z is not specified in  park position ? 

1.1.6    -- > #define NOZZLE_PARK_POINT { (X_MIN_POS + 314), (Y_MIN_POS ) }
and it works good  if i used same setting in 1.1.x bugfix it goes to ZMAX

**Comment by thinkyhead** [comment]
With 1.1.9 / 2.0 `NOZZLE_PARK_POINT` requires X, Y, and Z.
If no Z is specified, the Z value is _random_.

An assertion has now been added to the bugfix branches to catch this oversight.
