### ISSUE TITLE
[1.1.9] Reboot at manual (prepare move axis E) extruding

### ISSUE THREAD

**Issue by Tofoillote** [MarlinFirmware/Marlin#11496]
### Description

While attempting to move filament via "prepare" "move axis" "Extruder" 10 or 1 or 0.1 mm first step is shown on screen then screen go blue and printer reboot.

Printing Gcode works fine.

### Steps to Reproduce

Load some filament.
Go in prepare "preheat PLA end"
When temp is ok go in "prepare" "move axis" "Extruder" chose a value.
Turn the encoder one direction
value freeze.
wait for reboot.

This configuration is for Creality Ender-3 based on one finded in present Github.

[Marlin_1.1.9_CR_ENDER-3.zip](https://github.com/MarlinFirmware/Marlin/files/2273210/Marlin_1.1.9_CR_ENDER-3.zip)

**Comment by thinkyhead** [comment]
Try lowering the `MANUAL_FEEDRATE` for the E axis and see if it helps.

**Comment by boelle** [comment]
@Tofoillote did you try what thinky suggested?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by Tofoillote** [comment]
Yep you can close it. I did assume haven't find the origin, but following flashing did works.

**Comment by boelle** [comment]
only you can close it with the close button below

**Comment by Tofoillote** [comment]
Thanks, I'm a bit newbie.
