### ISSUE TITLE
Z after homing 

### ISSUE THREAD

**Issue by xarbit** [MarlinFirmware/Marlin#11516]
I have a delta printer running the latest Marlin.
Currently (and before on 1.1.8) when the printer homes or reaches the endstops, it travels down around 70mm and stops. 

Where can I set that value? Want to reduce the traveling position.. 

I cannot figure it out.. any guidiance would be really appriciated.

Thanks

**Comment by xarbit** [comment]
This might be based on the same report found here: https://github.com/MarlinFirmware/Marlin/issues/4823

**Comment by thinkyhead** [comment]
You can disable `DELTA_HOME_TO_SAFE_ZONE`. Marlin automatically determines the highest point where full XY movement is possible.
