### ISSUE TITLE
[bugfix 2.0.x] Adding LPC43xx Framework

### ISSUE THREAD

**Issue by GadgetNutt** [MarlinFirmware/Marlin#11517]
Greetings.

I'm working on integrating the LPC43xx code for the upcoming Smoothieboard V2 and have come up with a snag.  I have created a parallel framework beside LPC1768 and a PlatformIO build for the LPC4330, but I don't know how to make the library.json file selective for each depending on which PlatformIO build is selected.

I'd appreciate some input on this.

**Comment by p3p** [comment]
The CMSIS folder contains the library so it should really be called `CMSIS-LPC1768`, your frameworks library would need to be in another folder with its own library.json, 

The LPC176x framework will be removed from Marlin soon to simplify the platform and make it easier to maintain, changing to using a custom PlatformIO [framework](https://github.com/p3p/pio-framework-arduino-lpc176x) instead, as you are probably using the nxplpc PIO platform you could do something similar for LPC43xx, (although I use a custom version of that too to add the framework)

I'm not sure how Smoothieware2 will be using the M0 co processor (and the FPGA on the pro) will Marlin be able to run just on the LPC43xx and have access to all the hardware?

**Comment by GadgetNutt** [comment]
Thank you p3p.

From what Arthur said in this video, that would be my guess.

https://www.youtube.com/watch?v=vGpA_oNiEmY
