### ISSUE TITLE
[1.1.9] tmc2130 randomly reset on movment 

### ISSUE THREAD

**Issue by uyoyo117** [MarlinFirmware/Marlin#11514]
### Description

while homing or moving the printer will halt and reset, using ramps and a mix of tmc2130 and tmc2100  

### Steps to Reproduce

1. use config files to burn marlin 1.1.9 on ramps
2.preform 2,3 homing on axis using tmc2130
3.profit of random resats

**Actual behavior:** [What actually happens]
it starts moving and midway is resating
#### Additional Information
 i am using it on a custom p208m and tronxy x1 and i got the same problem
config files are added

[p208m.zip](https://github.com/MarlinFirmware/Marlin/files/2278979/p208m.zip)
[tronxy x1.zip](https://github.com/MarlinFirmware/Marlin/files/2278984/tronxy.x1.zip)

**Comment by truglodite** [comment]
Ramps and 256 microstepping will not work. Try 16 microsteps instead (I use 32, but 16 is more common). The interpolation is what will make it smoother with RAMPS. High actual microsteps (like 256) only works on certain 32bit setups (tmc26xx, etc.).

**Comment by uyoyo117** [comment]
After some testing and experimenting, I found out that the microsteping is being processed inside the driver and not mega, and in 1 microsteping its doing the same, in 16 its not moving, 32 weird noises and iregular movement, 128 moving perfectly, and no step per mm adjustment was required. Which make me belive the problem come from new tmc2130 makros...

**Comment by thinkyhead** [comment]
For TMC2130 stepper drivers, always set 16x micro-stepping on the jumpers and for calculating steps-per-mm in the firmware. This permits the use of their internal 256 micro-steps interpolation.

**Comment by boelle** [comment]
@uyoyo117 is the problem still there?

**Comment by uyoyo117** [comment]
Yep

**Comment by boelle** [comment]
and you are using bugfix 2.0?

**Comment by uyoyo117** [comment]
Bugfix 1.1.9

**Comment by boelle** [comment]
use 2.0

1.1.9 is kind of put in the grave

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
