### ISSUE TITLE
Delta printer does't work 

### ISSUE THREAD

**Issue by nhatsunflower** [MarlinFirmware/Marlin#11525]
<!--
Hi everyone !
I'm building a delta pritnter with Marlin 1.1.8 firmware. 
I have met some issues and I lost more than 3 weeks to fix it but it still didn't work>
When  using the auto calibration on the printer. All steps in delta auto calibaration works perfectly then I store setting and I see everything about delta settings on LCD is changed.  But when I try to print or move X,Y,Z axis. the center is always perfect. then it acts like a rainbow from side to side of x and y. Autotune fails.  Manual tune fails. Never saves the settings!  I always hit store and they show but it's like it ignores them.  
Please help me !

**Comment by GMagician** [comment]
Please fill issues form as required so maybe someone may help you
