### ISSUE TITLE
STM32F407VET6 and STM32F103RCT6 it reboot when going home

### ISSUE THREAD

**Issue by semos2k** [MarlinFirmware/Marlin#11529]
### Description

I am installing marlin 2.0.x on the boards: STM32F407VET6 and STM32F103RCT6 at the time of homing, the board reboot.

### Steps to Reproduce

1. tested NO and NC
```cpp
#define X_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define X_MAX_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define Y_MAX_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define Z_MAX_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define ENDSTOP_INTERRUPTS_FEATURE (active and inactive)
```
**Expected behavior:** Homing

**Actual behavior:** reboot board, does not work on any of the axes.

**Comment by AnHardt** [comment]
Are you sure your endstops are not shorting 5V to ground?

**Comment by semos2k** [comment]
yes, they work properly with an arduino board.

**Comment by thinkyhead** [comment]
Working with the latest `bugfix-2.0.x`?

**Comment by AnHardt** [comment]
Rebooting while moving or at the moment an endstop is hit?
Reboot when endstop is manually triggered - without movement?

**Comment by boelle** [comment]
@semos2k tried latest bugfix 2.0 ?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
