### ISSUE TITLE
Head position on z axis only increases when autoleveling

### ISSUE THREAD

**Issue by vbgfhfngfdtyreyt** [MarlinFirmware/Marlin#11523]
### Description

When autoleveling, the z position of the head only increases. The head moves to each point in the XY plane, but it just increases the position on the z axis!

I have a folger2020, which has the z axis inverted. I'm guessing that this sort of printer might be rare enough that autoleveling was never tested for an inverted z axis. However, if this is the case, the fix could be easy, just multiplying by -1 for certain z axis moves. I tried looking through Marlin_main.cpp to see if anything obvious stood out to me, but I unfortunately am not familiar with the code base yet. Happy to help resolve this any way I can.

### Steps to Reproduce

1. G28 Z0
2. G28 X0 Y0
3. G29

**Expected behavior:**

I expect autoleveling to function as normal. I used to have another printer with a non inverted z axis, and autoleveling worked fine on that printer.

**Actual behavior:**

What actually happens is the head position on the z axis continually increases. It never decreases. The head moves to the correct XY coordinates for the test points, but keeps moving upwards! By the time the fourth point is reached, the Z position is nearly at 200mm.

#### Additional Information

My Configuration.h from bugfix-2.0.x branch:
https://gist.github.com/vbgfhfngfdtyreyt/a45757ff68227124f9184fb406ef3689

I tested with the zip download from the Marlin website, and then branches 1.1.x, bugfix-1.1.x, and bugfix-2.0.x. Same result with all 4 attempts.

**Comment by ikarisan** [comment]
Maybe we are facing the same issue: https://github.com/MarlinFirmware/Marlin/issues/11532

**Comment by thinkyhead** [comment]
This symptom indicates that your probe is mis-wired and Marlin sees it as always triggered. Test with `M119` while fixing the probe until you have it reliably reporting "triggered" only when it's actually triggered.

**Comment by vbgfhfngfdtyreyt** [comment]
I feel very stupid now...For anyone reading this: I didn't have the zmax pin enabled so the probe pin was reading as triggered at all times. Thank you!
