### ISSUE TITLE
[bufix-2.0.x latest] DUE+RAMPS-FD V2 extruder auto fans not working

### ISSUE THREAD

**Issue by scott0122** [MarlinFirmware/Marlin#11537]
When I `#define E0_AUTO_FAN_PIN FAN1_PIN` in `Configuration_adv.h`, the fan does not start when the extruder's temperature goes above `EXTRUDER_AUTO_FAN_TEMPERATURE 50`.
If I send `M106 P1 S255` manually, the fan does not start either.
Then I reboot DUE, the fan starts immediately (hotend temperature >50 currently).
But the fan does not stop when the hotend temperature go below 50.

So I `#define E0_AUTO_FAN_PIN -1` to disable auto fan and manual send `M106 P1 S255`, and the fan starts.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2284867/Marlin.zip)

**Comment by cjsoong** [comment]
@scott0122  FAN1_PIN ?? pins_RAMPS_FD_V1.h & pins_RAMPS_FD_V2.h did not see this definition. 
I am setting #define E0_AUTO_FAN_PIN 11 or 2   is ok.

**Comment by thinkyhead** [comment]
Assuming this is solved in `bugfix-2.0.x`.
