### ISSUE TITLE
[bugfix-2.0.x] G28 and UBL: Z moves up and up with every X/Y move 

### ISSUE THREAD

**Issue by ikarisan** [MarlinFirmware/Marlin#11532]
I just flashed the most recent bugfix-2.0.x version ( aa9d329560eb9c8de2dd68bbf0797c200e540b33 ) and I have a homing issue. On every X move the Z axis moves up. After a second G28 I ended up near below Z max. :( 

See this video: https://youtu.be/pz5_J92eIMY 
=> First G28 on 00:03
=> Second G28 on 00:36

This happens on

G28,
G28 X,
G28 Y and
G28 Z

With an older version (around 07. August) everything worked fine.
EDIT: Branch_e4ecade is working fine
I am using TMC2208 for X and Y on a MKS Gen 1.4 board. 

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2281315/Marlin.zip)

**Comment by ikarisan** [comment]
After doing some further investigations I can clearly say, that 0af22549a6780d3486da895be7a920bd6c02927f is the last working version. Beginning from c93538e9f3d409c9b96921d0d9ed4681fa0226b6 (UBL/planner patch tweaks) the homing is broken.

**Comment by YMita2017** [comment]
Same situation but bugfix-1.1.x.
From 1.1.7 to 1.1.9, same.
Use same setting from 1.17 to 1.1.9.
At autohoming, or G28, always Z moves up and up.
At 1.1.7, Z move up before X homing, but Z not move untill Y homing finish.
I'm using Precision Piezo.

**Comment by Graham-3D** [comment]
I am having the same issue.  I installed [bugfix-2.0.x] from a day or so back (not sure of the version) and my printer is behaving the same as in the video. I reverted back to 1.1.9 and everything works correctly again. I also have a BLTouch (Well 3D Touch). Identical settings copied over as far as I can tell.

**Comment by smoki3** [comment]
Same here @thinkyhead 

Seems UBL is also broken with BLTouch.

Also after homing if I move X and Y axis the first time my Z axis is raising but the z coordinates are still the same

**Comment by Graham-3D** [comment]
My issue here has been fixed by [2.0.x] Fix UBL/Homing #11566

**Comment by thinkyhead** [comment]
Assuming everything is configured correctly, BLTouch should work fine with 1.1.9 and 2.0.x.

**Comment by boelle** [comment]
@ikarisan tried latest bugfix 2.0 ?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
