### ISSUE TITLE
Bugfix 2.0 - Re-Arm + Ramps : Servo pin problem

### ISSUE THREAD

**Issue by J-charles-C** [MarlinFirmware/Marlin#11547]
I,

I, have an RE-ARM with Ramps 1.6
One E3D Chimera
One layer Fan
One hotend fan (use with E0_AUTO_FAN_PIN)

This config works fine with my MKS GEN and Marlin 1.1.8.

### Description

My motherboard is configured on EEB.
E0 & E1 are wired on D10 et D9.
Hotbed is on D8.
With an IFR520, my layer fan is tired on SERVO3_PIN (P1_18). It's work fine.

I wan't connect with IFR 520 an Hotend fan on Other servoPin, but its don't turn on.

`
#ifndef FAN_PIN
  #if ENABLED(IS_RAMPS_EFB) || ENABLED(IS_RAMPS_EFF)   // Hotend, Fan, Bed or Hotend, Fan, Fan
    #define FAN_PIN        RAMPS_D9_PIN
  #elif ENABLED(IS_RAMPS_EEF) || ENABLED(IS_RAMPS_SF)  // Hotend, Hotend, Fan or Spindle, Fan
    #define FAN_PIN        RAMPS_D8_PIN
  #elif ENABLED(IS_RAMPS_EEB)                          // Hotend, Hotend, Bed
    #define FAN_PIN        P1_18  // (4) IO pin. Buffer needed
  #else                                                // Non-specific are "EFB" (i.e., "EFBF" or "EFBE")
    #define FAN_PIN        RAMPS_D9_PIN
  #endif
`

`
#define E0_AUTO_FAN_PIN P1_19
#define E1_AUTO_FAN_PIN -1
#define E2_AUTO_FAN_PIN -1
#define E3_AUTO_FAN_PIN -1
#define E4_AUTO_FAN_PIN -1
#define CHAMBER_AUTO_FAN_PIN -1
#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED   255  // == full speed
`

### Steps to Reproduce

When extruder is hot, hotend fan don't turn on.

**Expected behavior:** [What you expect to happen]

I wan't have the two fan 

#### Additional Information

* I
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/2287548/Archive.zip)

best

**Comment by J-charles-C** [comment]
I,

If i switch ServoPin (E0_AUTO_FAN_PIN P1_1**8** & FAN_PIN P1_1**9**) 
E0_AUTO_FAN_PIN works fine and turn on when hotend is hot but Layer fan don't turn on with M106 command.

I can't use two ServoPin at the same time.

**Comment by kAdonis** [comment]
Your Problem could be the IRF 520, this Mosfet is not made for 3,3V devices like the Re-Arm
Pins 2_04, 2_05, 2_07 (D8, D9 and D10 on RAMPS)  and P1_18 (Servo) are level shifted to 5V, which is enough for an IRF 520 (VGS(th)=2-4V). 
But the other Pins on the servo Header deliver only 3,3V which **might be** not enough for your IRF 520 to switch.
You could try a logic-level-Mosfet for example an IRLZ34N, I found this by googling, I am no expert in electronics, there will be better choices for sure.
The SevenSwitch from your #11545 should work also (uses MOSFET IRLB 8743)
Or your issue is caused by something completely different

**Comment by J-charles-C** [comment]
I,

I have used this bridge for 5V to servo :
![re-arm_ramps-wiring-5v](https://user-images.githubusercontent.com/22807221/44107043-74f75f90-9ff6-11e8-9a72-2fd99e35cc32.jpg)

**Comment by kAdonis** [comment]
That doesn't matter. I was talking about the voltage level on the signal pin itself.
 Pin1_18 5V 
 Pin 1_19 3,3V
 the other Servo pins also 3,3V

**Comment by J-charles-C** [comment]
Thanks for your help.

I connected with a Y the 5V from the RESARM to the VCC pin and 5V from the RAMPS.

I just measured, I have 4.6 volts on the input of IFR520.

best.

**Comment by kAdonis** [comment]
Sorry, I don't understand what you mean.

**Comment by kAdonis** [comment]
![vcc](https://user-images.githubusercontent.com/35379348/44109729-094db188-9ffe-11e8-8e0a-bb5c770f89ad.jpg)
Don't connect 5V to VCC_Pin on RAMPS! You will probably damage your RE-Arm!

**Comment by J-charles-C** [comment]
It works like that from the beginning.

Here is a tutorial to feed the servospin in 5V
http://doc.3dmodularsystems.com/re-arm-32bits-upgrade-for-scalar-3d-printer/
best.

The Y is a trick read on a forum

**Comment by kAdonis** [comment]
I understand you are delivering  5V to the middle pins on the servo connector, this is fine
But this doesn't change the output voltage on the servo-signal pins, you don't need the 5V from the servo header for a Mosfet.
I still don't know what you mean with "Y"

**Comment by J-charles-C** [comment]
I still don't know what you mean with "Y"

It's parallel wiring. One point to two point.

best

**Comment by kAdonis** [comment]
You really connected 5V to the VCC-Pin on the Picture above?
I just checked the Re-Arm design files, there is no protection diode, this connection directly feeds 5V to the LPC
I can't believe this is working, the MCU must be boiling hot

**Comment by J-charles-C** [comment]
yes i do.

It's source of my problem ?

If I unplug VCC pin, TFT and full graphic are off.

With VCC and 5v ramps pin connected to 5V of Re-arm, i have 4,6 volts to all my servos pin.



**New test :** 

if I configure a single IFR520 on pinservo  P1_19 or P_20, it does not work.

If I configure two, with one on the P1.18 and the second onP1_19 or P_20, only the one on the servo pin 1.18 works.

If I configure two of them  using P1.18 and P-21, two IFR520 works.

conclusion, I do not order pin 1_19 and 1_20, why?


### **conclusion, I do not order pin 1_19 and 1_20, why?**



best

**Comment by kAdonis** [comment]
I am suprised that it works at all, but your Re-Arm is probably damaged
Unplug the VCC-Pin!
maybe the electronics inside the chip for pin 1_19 and 1_20 is destroyed, I can't help you with that

The LCD needs 5V, you need a special cable, look here:
http://panucattdevices.freshdesk.com/support/solutions/articles/1000243195-lcd-display-installation

**Comment by J-charles-C** [comment]
Dammaged on Ramps or Re-Arm ?

**Comment by J-charles-C** [comment]
I have test a switch of the Pin in Ramps.h and with the same effect pin_ramps_re_arm.h

#define SERVO1_PIN          6
#define SERVO2_PIN          4  // Origin 5
#ifndef SERVO3_PIN
  #define SERVO3_PIN        5  // Origin 4


The fan runs connected to the SERVO3_PIN while the addresses are inverted with the SERVO2_PIN.

best

**Comment by kAdonis** [comment]
I am not sure , if i understand you
I don't know why you are changing the  pin defines
Pin 1_18 is physically connected to the Servo pin to the right , no matter what you define

![servoheader](https://user-images.githubusercontent.com/35379348/44157012-a56f7200-a0b1-11e8-80bc-a59ca32342df.jpg)


and pins_RAMPS.h is not even used by Marlin when you use a Re-Arm

> Dammaged on Ramps or Re-Arm ?

I think your Re_Arm is damaged

I cannot help you

**Comment by J-charles-C** [comment]
Ok, I thought I could redistribute the servo ports.

I modified Ramps.h because it serves as support in the Re-Arm. the file pin_ramps_re_arm.h send back to him.


How to connect the BL-touch to another port that SERVO1_PIN, to release my two servopin that still work?

Thanks for your help.

**Comment by kAdonis** [comment]
Is your BLToch connected to Servo1 Pin? What is on Servo0 pin?

**Comment by J-charles-C** [comment]
Sorry  my bl-touch is on Servo0 pin (D11)

 Servo1 pin &  Servo2 pin are out of service

 Servo3 pin is for my fan layer.

**Comment by J-charles-C** [comment]
Hello,

Thanks again for your help.

I found a solution by remapping one of my IRF520 on an enstop.

Like that, I order my two fans and my BL touch.

I'll have to look at this damaged card problem.

cordially

**Comment by J-charles-C** [comment]
I, 

i change Ramps and i solve my problem of servo pin out of service.

Many thanks kAdonis
cordially
