### ISSUE TITLE
BOARD_MIGHTYBOARD_REVE  200   // Makerbot Mightyboard Revision E

### ISSUE THREAD

**Issue by aamcle** [MarlinFirmware/Marlin#11546]
Marlin 1.1.9.

The above board is listed in Boards_h but throws an "Unknown Motherboard" error when I try to compile the sketch. It is not listed in  Tools, Board Manager so I can't actually use Marlin firmware.

**Comment by thinkyhead** [comment]
In `Configuration.h`:
```cpp
#define MOTHERBOARD BOARD_MIGHTYBOARD_REVE
```
In Arduino IDE:
![image](https://user-images.githubusercontent.com/698003/45415493-68ac8180-b643-11e8-9dc1-a31ed4b8d2c8.png)
