### ISSUE TITLE
Wanhao D6, Marlin 1.1.9 Adaptive step smoothing hesitation

### ISSUE THREAD

**Issue by mmakam2** [MarlinFirmware/Marlin#11558]
Hi, I believe this is a limitation with the 8bit controller, but with adaptive step smoothing on, sometimes around tight corners and curves my printer hesitates and gets all jerky getting through that. I think it runs out of processing ability, but if there is someway to resolve that it would be great because i get really nice prints with the smoothing turned on.

Printer: Wanhao D6

**Comment by houseofbugs** [comment]
USB or SD printing?

**Comment by mmakam2** [comment]
Octoprint

**Comment by Deneteus** [comment]
Octoprint using PI Zero W? or Pi3?

**Comment by mmakam2** [comment]
Pi 3 b+

**Comment by mmakam2** [comment]
Goes away if I slow down printing feedrate.

**Comment by ejtagle** [comment]
probably running out of processing power... a possibility is to reduce maximum steps per second
