### ISSUE TITLE
Unable to load settings EEPROM Marlin Plugin

### ISSUE THREAD

**Issue by RogerHman** [MarlinFirmware/Marlin#11568]
Im a noob who has run out of ideas! Any help is appreciated. 

I have upgraded my CR-10 with autobed lvl. I want to change z-offsett via plugin or control box but cant do either.

I have checked the forum and i have all these settings enabeled.
```cpp
#define EEPROM_SETTINGS // Enable for M500 and M501 commands
#define DISABLE_M503    // Saves ~2700 bytes of PROGMEM. Disable for release!
#define EEPROM_CHITCHAT   // Give feedback on EEPROM commands. Disable to save PROGMEM.
```
`SDSUPPORT` is off to save space.

I'm running Marlin 1.1.8. but same problem with 1.1.6

**Comment by AnHardt** [comment]
The EEPROM code was changed for 1.1.9 and even more for bugfix-1.1.x .
We will not touch 1.1.6 nor 1.1.8 any more.
Reporting bugs for those old versions doesn't make any sense.
Test bugfix-1.1.x or bugfix-2.0.x.

What do you mean with 'plugin'? 
What do you mean with 'control box'?

What 'forum'? This is a bug tracker. Not a beginners forum.

Please - next time fill the issue form or at least read it.

**Comment by RogerHman** [comment]
sorry. i misunderstood. plugin is the octoprint plugin eeprom marlin editor. Controlbox is the controlbox/reprap controller of the 3d printer! 

anyhow. its the same in 1.9!

**Comment by RogerHman** [comment]
wrong version
