### ISSUE TITLE
[1.1.9] Very strange G28 behavior (almost hits Z limit going up) 

### ISSUE THREAD

**Issue by Costin-Nox** [MarlinFirmware/Marlin#11582]
### Description

Printer: Creality CR-20 (new one)

When performing a G28 Home all, the printer will perform both X and Y touches twice, going up between them. Initially, it goes up in small increments. If performed after a print (any print, including printing the UBL validation) it will go up significantly higher and faster. Almost like it's using completely different configuration values.

I initially was running 1.1.8 without this issue present, i updated to 1.1.9 and it started since then.

### Steps to Reproduce

1) Finish or cancel a print
2) Perform G28

#### Additional Information

Config files:

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2299150/Marlin.zip)

Video showing the behavior:

(first 2/3 behavior after a print, last 1/3 i perform it again and it behaves 'normal')

https://youtu.be/hIihjOswZXM

**Comment by smoki3** [comment]
have you tried the latest version? It should be fixed with the latest commit.

**Comment by Costin-Nox** [comment]
Oh just saw the commit from 2 days ago, I thought they killed updates on this one. Thanks for the heads up, I'll give it a shot

Issues fixed in the last commit.
