### ISSUE TITLE
Babystepping only working in Z+ direction.

### ISSUE THREAD

**Issue by LichtiMC** [MarlinFirmware/Marlin#11581]
Please try out babystepping with latest bugfix.
The homing issue is fixed, but if I do Z-babystepping it only works in + Direction.
Therefore I end up with nozzle too far from bed and can't reverse direction anymore.

Printer: CoreXY
UBL enabled in firmware but deactivated for testing. (No mesh and M420 S0)

**Comment by LichtiMC** [comment]
I guess #11532 is because of the same bug.

**Comment by forkoz** [comment]
On cartesian it is working compiled Aug 14, 2018. But switched to bilinear for now. It must mean UBL is still broken?

**Comment by bruce356** [comment]
Also on my Cartesian its working compiled today 18/08/2018  version db30650

**Comment by J-charles-C** [comment]
I 
Works on corexy With aug 12 version of Marlin 2.0.

Best
