### ISSUE TITLE
Autotune: Get always PID suggestions like ~5/~0.2/~17 which are far off

### ISSUE THREAD

**Issue by dgrat** [MarlinFirmware/Marlin#11593]
Working PID:
Last days I tried to get some working PIDs on my printer. My setup seems to work relatively well with PID-Terms in the range of ~5/~1/~35-45 and probably even higher D-Terms, Leading to 1°C oscilations.  

Autotune:
In the last days I repeated Autotune over and over, with and without fan and for a temperatures of 240 and 280°C. I alwas get PIDs in the same range of ~5/~0.2/~17 Plus minus ~0.5/~0.1/~2. The consistence would be awesome if the result would be working. The D-term is way to low in relation to the PI-terms. The I-term on the other hand is too low to keep up with the cooling fan. The temperatures with these PIDs oscilates during tuning by 10-15 degrees and during print by at least 5. 

Observation:
The tuning function seems to oscilate around these wrong PID-terms with mini steps forth and back, over and over. 

Conclusion:
Neither the PIDs nor the min/max temperature variation change . Autotune should fail at this point, but it continues for several runs :/

Suggestion:
Would it make sense to start with a fixed P/I-term and first optimize the D-term with bigger increment? Later one can increase the I-term and P. 

Question:
Are there maybe some settings in the config file to improve Autotune? The allowed min/max deviation of 10 degrees seems wrong at least in my file?!

**Comment by RudyBenner** [comment]
You might try a little lower in 
```cpp
#define BANG_MAX 225
```
instead of 255.
should settle in 2-3 oscillations.
```cpp
// Comment the following line to disable PID and enable bang-bang.
#define PIDTEMP
#define BANG_MAX 225 //255     // Limits current to nozzle while in bang-bang mode; 255=full current
#define PID_MAX BANG_MAX // Limits current to nozzle while PID is active (see PID_FUNCTIONAL_RANGE below); 255=full current
#define PID_K1 0.95      // Smoothing factor within any PID loop
#if ENABLED(PIDTEMP)
  //#define PID_AUTOTUNE_MENU // Add PID Autotune to the LCD "Temperature" menu to run M303 and apply the result.
  //#define PID_DEBUG // Sends debug data to the serial port.
  //#define PID_OPENLOOP 1 // Puts PID in open loop. M104/M140 sets the output power from 0 to PID_MAX
  //#define SLOW_PWM_HEATERS // PWM with very low frequency (roughly 0.125Hz=8s) and minimum state time of approximately 1s useful for heaters driven by a relay
  //#define PID_PARAMS_PER_HOTEND // Uses separate PID parameters for each extruder (useful for mismatched extruders)
                                  // Set/get with gcode: M301 E[extruder number, 0-2]
  #define PID_FUNCTIONAL_RANGE 10 // If the temperature difference between the target temperature and the actual temperature
                                  // is more than PID_FUNCTIONAL_RANGE then the PID will be shut off and the heater will be set to min/max.

  // If you are using a pre-configured hotend then you can use one of the value sets by uncommenting it

 
  // ANET A8 Standard Extruder at 210 Degree Celsius and 100% Fan
  //(measured after M106 S255 with M303 E0 S210 C8)
  #define DEFAULT_Kp 12.85
  #define DEFAULT_Ki 0.67
  #define DEFAULT_Kd 61.33
```

**Comment by dgrat** [comment]
Actually, I converted to a 24V system and lowered BANG_MAX to 48. It works till 72. Beyond this the overshoot are too high (or the D-term too small?).
