### ISSUE TITLE
[bugfix-2.0.x] Homing / BLTouch not deployed , Nozzle crash in bed glass

### ISSUE THREAD

**Issue by Stephane-80** [MarlinFirmware/Marlin#11591]
Hello I have upgraded to the today version 
and now  BLTouch never gets deployed during homing or by the Bltouch menu in marlin
someone else has this problem?
before this upgrade with the same config it worked
thanks , 
best regards , Stephane

**Comment by Stephane-80** [comment]
Maybe I have a hardware problem , sorry

**Comment by NSchnitzler** [comment]
sometimes the sensor doesn't get to idle position, but keeps scratching on the Glass during G29

**Comment by julianCast** [comment]
My bltouch will deploy but it wont stop when contact the bed and it will crash my nozzle. So tired of this.

**Comment by julianCast** [comment]
This is for those with the same problem:
I fixed it ! I can't believe it was just the height (the distance between nozzle and bltouch), I trusted a downloaded mount, I modified just 1 mm and it work perfect everytime. Hardware problems are the best. phew.

**Comment by boelle** [comment]
@Stephane-80 problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
