### ISSUE TITLE
1.1.9 Compile error: 'ADC_KEYPAD_PIN' was not declared in this scope

### ISSUE THREAD

**Issue by Looxoor** [MarlinFirmware/Marlin#11600]
### Description

When trying to compile 1.1.9 i got the following error:
'ADC_KEYPAD_PIN' was not declared in this scope

The error occurred in "temperature.cpp" on line 2256.

### Steps to Reproduce

Perhaps related to NO_LCD_MENUS ?
I haven't tried to use it since my last issue with it.

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2304098/Marlin.zip)

**Comment by thinkyhead** [comment]
> "Requires `ADC_KEYPAD_PIN` to be assigned to an analog pin."

```cpp
//
// ANET and Tronxy 20x4 Controller
//
#define ZONESTAR_LCD              // Requires ADC_KEYPAD_PIN to be assigned to an analog pin.
                                  // This LCD is known to be susceptible to electrical interference
                                  // which scrambles the display.  Pressing any button clears it up.
                                  // This is a LCD2004 display with 5 analog buttons.
```

**Comment by Looxoor** [comment]
I understand that it's required by the LCD, but since the pin is assigned in "pins_ANET_10.h", here

`#if ENABLED(ULTRA_LCD) && ENABLED(NEWPANEL)
  #define LCD_SDSS           28
  #if ENABLED(ADC_KEYPAD)
    #define SERVO0_PIN       27   // free for BLTouch/3D-Touch
    #define LCD_PINS_RS      28
    #define LCD_PINS_ENABLE  29
    #define LCD_PINS_D4      10
    #define LCD_PINS_D5      11
    #define LCD_PINS_D6      16
    #define LCD_PINS_D7      17
    #define BTN_EN1          -1
    #define BTN_EN2          -1
    #define BTN_ENC          -1
    #define ADC_KEYPAD_PIN    1`

I'm guessing that's conflicting with the NO_LCD_MENUS somehow, because it compiles correctly with SLIM_LCD_MENUS.

Maybe removing the `&& ENABLED(NEWPANEL)` from the PIN definitions would help?

Thanks again.
