### ISSUE TITLE
Bugfix 2.0 TMC2130 - Setting INTERPOLATE FALSE - Causes printer to halt when homing

### ISSUE THREAD

**Issue by GhostlyCrowd** [MarlinFirmware/Marlin#11602]
### Description

Defining INTERPOLATE as false on TMC2130's causes the eeprom to corrupt sending G28. Eeprom would get corrupted, Losing all PID settings and heatbed bed  turn its self on.

1. Defining INTERPOLATE as false on TMC2130's 
2. Flash
3. Send G28, printer halts, PID settings are lost and you heatbed will start heating at MAX.

**Expected behavior:** The Printer to work proper, Home and the bed not to go rogue. 

**Actual behavior:** G28  the steppers would move the printer would halt and the eeprom would get corrupted, Losing all PID settings and My bed would turn its self on.

Recv: echo:PID settings:
Recv: echo:  M301 P0.00 I0.00 D0.00
Recv: echo:  M304 P-512.00 I-0.00 D0.00

**Comment by teemuatlut** [comment]
This doesn't make much sense. The `INTERPOLATE` option doesn't enable any additional code and it doesn't modify anything else other than flip one bit on a command that gets sent anyway. It's also not supported by the EEPROM feature. `stepper_indirection.cpp` is the only file that references the option.
I very much doubt that enabling/disabling `INTERPOLATE` is the cause for the issues.

**Comment by GhostlyCrowd** [comment]
I know it doesn't make sense but its exactly what happened.  

After Flashing back with it turned back on, and clearing the eeprom before and after flash its back working again. So no idea. 

It was 100% reproducible as well. Id clear and then  fix PID in the eeprom, G28 the printer would halt saying it detected an error as soon as the steppers started to move, Bed would turn on to max temp and M503 would report PID like posted above.

I archived the clone I was using of the bugfix branch and just started with a fresh clone today. merged in my config changes and ramps pin changes to the default configs and ramps pins.  Like i said its all working again, I'll try again later, but right now i need to print some parts for another printer.
