### ISSUE TITLE
1.1.9 unable to compile with NO_LCD_MENUS enabled

### ISSUE THREAD

**Issue by Looxoor** [MarlinFirmware/Marlin#11613]
### Description

In reference to an issue I posted before it got [closed](https://github.com/MarlinFirmware/Marlin/issues/11600).

I have since posting that issue tested switching from NO_LCD_MENUS to SLIM_LCD_MENUS and it compiles beautifully.

The referenced pin is assigned in "pins_ANET_10.h" on line 156 and forward:

```cpp
#if ENABLED(ULTRA_LCD) && ENABLED(NEWPANEL)
  #define LCD_SDSS           28
  #if ENABLED(ADC_KEYPAD)
    #define SERVO0_PIN       27   // free for BLTouch/3D-Touch
    #define LCD_PINS_RS      28
    #define LCD_PINS_ENABLE  29
    #define LCD_PINS_D4      10
    #define LCD_PINS_D5      11
    #define LCD_PINS_D6      16
    #define LCD_PINS_D7      17
    #define BTN_EN1          -1
    #define BTN_EN2          -1
    #define BTN_ENC          -1
    #define ADC_KEYPAD_PIN    1
```

If I remember correctly `NEWPANEL` is the menus that gets deactivated with `NO_LCD_MENUS`?
Maybe removing the `&& ENABLED(NEWPANEL)` from the PIN definitions would help?

EDIT: I tried removing the &&, still failed, I don't have enough knowledge to troubleshoot further.

Thanks again.

**Comment by Looxoor** [comment]
I couldn't help but to try something, so I changed the aforementioned line to

```cpp 
#if ENABLED(ULTRA_LCD) || ENABLED(NEWPANEL)
```

And it compiles, 74% memory usage down from 91%. I don't know if this breaks anything but I think it's a reasonable change?

However, it only works if I disable the M73 command in configuration_adv.h since the sanity check for it now considers the machine to be configured without an lcd.

Do you think the current implementation of NO_LCD_MENUS could fail other checks for the same reason?

**Comment by thinkyhead** [comment]
The affected define is this one…
```cpp
#if ENABLED(NO_LCD_MENUS)
  #undef ULTIPANEL
#endif
```
The meaning of `ULTIPANEL` is that the controller has some kind of user interface. You can have an `ULTRA_LCD` without an `ULTIPANEL` and you'll get a display, but no menus.

The meaning of `NEWPANEL` is a controller wheel with three `ENC` pins rather than an SPI-based button interface.

So I think the correct change is just to make it `#if ENABLED(ULTRA_LCD)`.
