### ISSUE TITLE
Marlin 2.0.x RAMPSFDv1 Inverted Heater Not Work

### ISSUE THREAD

**Issue by kde47** [MarlinFirmware/Marlin#11619]
if I define in Marlin, the board RAMPS FDv1 without any other changes to the config.h, then the power amp outputs are not inverted. It seems like the #define INVERTED HEATER is not declared from the RAMPSFDv1 pins.h. The Mosfet exits are on when they should be off. and are off, if they should be on.

**Comment by thinkyhead** [comment]
Should be resolved now!
