### ISSUE TITLE
Bad printing of circles from PC

### ISSUE THREAD

**Issue by Blisk** [MarlinFirmware/Marlin#11622]
### Description

When I print from SD card printer prints nice round smooth circles. But when I print the same from PC, printing is slow and printing circles have many short pauses after that circles are really bad, with alot of bumps.

I have downloaded marlin bugfix 1.1.x today and uploaded it.

**Comment by comps** [comment]
It's a known limitation for "higher-resolution" circles (too short segments) on 8bit hardware and Marlin, especially when printing via USB. The situation is better with an SD card (I never figured out why, the serial line is hardly taxed), but only slightly.

Using 32bit boards might be better, but other issue threads here seem to indicate Marlin in general has issues with many small segments regarding acceleration/jerk.

It seems we're still pretty far from an ideal single-step segment resolution.

(TL;DR - use lower resolution STL)

**Comment by Blisk** [comment]
Yes but this use to work, that start to happend suddenly I think it is not because updating merlin

**Comment by MiddleMan5** [comment]
Can you post the following information:

- Slicing Software, Version, Slicing Configuration
- Marlin Version and Config (or output of M503)
- Printer Hardware Version and Motherboard

**Comment by Blisk** [comment]
Slicing software is Repetier 2.1.3
Slicing configuration is CuraEngine
Marlin version is bugfix-1.1.x 31.7.2018
http://zerobin.povej.net/?025fc5b0329fc006#BZSAiAN/l1QZ31cO4eZT1JCCSRDco26enH4Nn3PuSI0=
Printer is Geeetech I3 pro C board is GT2560 rev.A

I also have a problem with shifting layer when I print from SD card with this version of marlin.
Sometimes it shift to X, sometimes to Y for a mm or less. Belt are tighten, but not too much and all screws are tightened. I have also slow down moving and printing speed. Before that din't happend. I updated marlin because of auto bed leveling and filament out switch.

**Comment by gloomyandy** [comment]
In terms of missed steps, what stepper drivers does that board have and do you have them correctly defined in your configuration file?

**Comment by MiddleMan5** [comment]
This is a completely unofficial, unrecommended test, but could you add the following:
```cpp
#if ENABLED(STUTTER_FIX)
  OCR1A = (OCR1A < (TCNT1 +16)) ? (TCNT1 + 16) : OCR1A;
#endif
```

To line 1408 (or thereabouts) of stepper.cpp in the marlin repo, then recompile and flash for your board.
Add the code directly **after** the line that looks like:
```cpp
// If there is a current block
  if (current_block) {
**insert code here**
```

then, in Configuration.h add:
```cpp
#define STUTTER_FIX
```
so that you can control it.

It's a timer overflow hack, and adding it to my branch has alleviated the stuttering I was seeing

**Comment by Blisk** [comment]
I have regular Nema 17 stepper motors, which works ok with original marlin, but not with latest, where I have constant layer shifting

**Comment by Blisk** [comment]
MiddleMan5
I did that but still when I print, circles are not nice round but it is the same as before.

**Comment by Blisk** [comment]
Here are results of printing.
No.1 is printed by SD card with original stock firmware.
No.2 is printed with PC with original stock firmware
No.3 and No.4 is printed with PC with Marlin bugfix-1.1.x 31.7.2018
![20180829_154932](https://user-images.githubusercontent.com/2773050/44792172-986b7c00-aba3-11e8-9b16-404b1c608385.jpg)

**Comment by henry42** [comment]
Hi, I am facing the same problem.
when I print from pc, the circle is changed to lots of points and printed really slow. but when using sd everything is ok.
It happened just in the version 1.1.9, it was fine in 1.1.8.

**Comment by Blisk** [comment]
Can it be a problem settings on PC for port?

**Comment by henry42** [comment]
> Can it be a problem settings on PC for port?

I found that it happened only if when I use cura.

If I export to the gcode, and use Printrun to print the model, everything seems fine.
I think maybe the problem is cura.
Have a try.
