### ISSUE TITLE
The link to 32 bit support in the README.md is broken

### ISSUE THREAD

**Issue by mrjohnc** [MarlinFirmware/Marlin#11621]
In the sentence 'Marlin's newly reorganized code will be easier to work with and form a stronger starting-point as we get into 32-bit CPU support and the Hardware Access Layer (HAL).' the link to 32-bit CPU support is a 404 error.

**Comment by thinkyhead** [comment]
What `README.md` are you referring to?

**Comment by mrjohnc** [comment]
The one that appears on https://github.com/MarlinFirmware/Marlin

The paragraph is this one (bold is the broken link)


<h3>Future Development</h3>

Marlin 1.1 is the last "flat" version of Marlin!

Arduino IDE now has support for folder hierarchies, so Marlin 1.2 will have a hierarchical file structure. Marlin's newly reorganized code will be easier to work with and form a stronger starting-point as we get into **32-bit CPU suppor**t and the Hardware Access Layer (HAL).
