### ISSUE TITLE
[bugfix-2.0.x] MKS SBASE eeprom save/load error

### ISSUE THREAD

**Issue by LazyMechanic** [MarlinFirmware/Marlin#11624]
### Description

I have an MKS SBASE v1.3 with EEPROM enabled (`#define EEPROM_SETTINGS`) in compiled Marlin 2.0. When I use command M500 or M501 the plate dissapear from the list of external storage devices for a few seconds. Then, after a minute, the plate dissapear from the list completly and all 5 diodes light up. There is no possibility to connect to the plate using Pronterface/Simplify3D/Cura too. After board reboot, it is still working. I've compared eeprom.dat file before and after M500 and there is new information saved on it. I have an option don't use EEPROM, but it will make printer setting up process complicated.

### Steps to Reproduce

1. Have MKS SBASE v1.3
2. Enable EEPROM in config
3. Plug in the board into the computer via USB
4. Connect to the board using Pronterface / Cura / Simplify3D / etc.
5. Send M500 / M501 and wait a minute
6. We now have the disabled board

**Expected behavior:** [What you expect to happen]
M500 doesn't disable the board

**Actual behavior:** [What actually happens]
M500 disable the board

#### Additional Information
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/2314438/configs.zip)

**Comment by p3p** [comment]
There are issues with the SD card EEPROM emulation and USB conflicting (depending on many factors) but there is a new feature to store the EEPROM in the flash memory (probably will be the default in the future) that can be enabled by adding `#define FLASH_EEPROM`  to the sbase pins file, (or your config)

**Comment by LazyMechanic** [comment]
Wow. Thanks, it worked.
