### ISSUE TITLE
With X and Y motors on, Z only goes up with G28. With both motors disabled it homes properly.

### ISSUE THREAD

**Issue by JAdams12** [MarlinFirmware/Marlin#11633]
Hey all, I’m having an issue with my Z homing.

### Description

I cannot home Z or probe the bed. I’m using an inductive probe. The z axis moves up, moves up, pauses (as if the probe returned a trigger signal), goes up, does the same thing again then stops. This only happens with X and Y motors enabled, disabling steppers and using G28 Z the Z axis homes fine.

### Steps to Reproduce

1. Home X and Y
2. Home Z
3. Error occurs

Alternative..

1. Disable X and Y steppers
2. Home Z
3. Z homes fine

**Expected behavior:** Z homes properly or probes properly with G29

**Actual behavior:** Z moves up, acts like it triggers, moves up, acts like it triggers, stops

#### Additional Information

Note I’ve confirmed this isn’t a hardware issue by configuring Repetier firmware for my printer, probing worked fine but I prefer Marlin as I have less communication issues with my Raspberry Pi. 

I have also replaced the probe and have confirmed that the triggering is working correctly with M119.

I have tried both Marlin 1.1.9 and 1.1.5 (currently on 1.1.5 because that’s where I ran out of ideas)

I’ll upload my config files in a minute. EDIT: Uploaded both files

[JAdams12_ConfigFiles_1_1_5.zip](https://github.com/MarlinFirmware/Marlin/files/2317254/JAdams12_ConfigFiles_1_1_5.zip)

Thank you so much

Jack

Edit: I think it may be important to point out that I have edited the fan pinouts in my configuration files so I have a MOSFET on pin 16 running the print cooling and a hot end fan on pin 9. So ignore that if you see it

**Comment by JAdams12** [comment]
I'm guessing that this must have something to do with electrical noise on the probe? That's what I assume given some more testing I've done. I'm just not sure how to rectify the issue, if Repetier Firmware works with it there needs to be a way to make Marlin work with it too.

Gonna try more Marlin versions and see if one randomly works.

**Comment by JAdams12** [comment]
Enabling ENDSTOP_NOISE_FILTERING on 1.1.9 fixed the issue!

**Comment by thinkyhead** [comment]
Adding a small capacitor inline with the probe signal line can help reduce electrical noise.

**Comment by JAdams12** [comment]
@thinkyhead

I have an assortment of caps, what value would work? Does that work on a probe or just the mechanical ones?

**Comment by thinkyhead** [comment]
Adding a 3.3k Ohm pull-up to the input is the best solution. The capacitor might not be required, but doesn’t hurt. Even 1nF should be enough.

**Comment by JAdams12** [comment]
@thinkyhead 

Thank you so much. I’ll make the modifications!

**Comment by JAdams12** [comment]
@thinkyhead 

Sorry to bother you but I just have a quick question before wiring anything else up here. 

First off, a small electrolytic cap would be ok right? I don’t need ceramic? 

Second, I have my probe running at 12v with the +12 signal returning from the probe to the board running through a 15k resistor to take it down to a voltage that won’t fry the board. I tied a 10k resistor between the ~5v signal back to the board and the ground attached to the arduino ground. So with that, would I still want to tie a 3.3k resistor between the ~5v signal and the ground or would the 10k be all I needed? Granted I clearly still have electrical noise I’m just not sure what exactly I should do. 

Thank you again and sorry! 

Edit: I’m now seeing that I need to tie the signal return to 5v. I’ll try that now!

**Comment by thinkyhead** [comment]
I think any cap with the right rating should work. Pick one least susceptible to induction.
