### ISSUE TITLE
Marlin 1.1.9 does not recognize negative offsets in X and Y axis.

### ISSUE THREAD

**Issue by sigourosandreas** [MarlinFirmware/Marlin#11634]
### Steps to Reproduce

1. I have attached the configuration files:
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/2317400/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2317401/Configuration.txt)

Paste them in the 1.1.9 marlin and run the program. It should give you the same error like mine.

2. [Second Step]
3. [and so on...]

**Expected behavior:** Run the program without any error.

**Actual behavior:** The new firmware will be uploaded in the board correctly.

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by oakdesign** [comment]
Double post?
