### ISSUE TITLE
[1.1.9] SD_FINISHED_RELEASECOMMAND defined but not used

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#11638]
The configuration option "SD_FINISHED_RELEASECOMMAND" has been replaced by "SD_FINISHED_STEPPERRELEASE". As a consequence, "SD_FINISHED_RELEASECOMMAND" is no longer used anywhere and should be removed.

**Comment by thinkyhead** [comment]
I see them both. And in both 1.1.x and 2.0.x codebases. For example:
```cpp
#if ENABLED(SD_FINISHED_STEPPERRELEASE) && defined(SD_FINISHED_RELEASECOMMAND)
  if (!cleaning_buffer_counter) enqueue_and_echo_commands_P(PSTR(SD_FINISHED_RELEASECOMMAND));
#endif
```

**Comment by marcio-ao** [comment]
@thinkyhead: That's odd. I could have sworn I grepped through the entire code base. I guess I missed that. Good catch. I'll close this ticket as irrelevant.
