### ISSUE TITLE
[FR] STM32 SD card SDIO support

### ISSUE THREAD

**Issue by svs072477** [MarlinFirmware/Marlin#11641]
Is it possible to add support for the SD card via SDIO on STM32?

**Comment by gloomyandy** [comment]
The usual method for supporting SD cards by Marlin is via the SD card SPI interface. Are there reasons to use SDIO on the STM32 rather than SPI?

**Comment by svs072477** [comment]
Speed 4-bit SDIO is much higher than with the SPI. Well e if stm32 SDIO supports it, then why not use?
Why use stm32, and do not use its capabilities other than frequency?

**Comment by gloomyandy** [comment]
Are there boards that actually have the required connections between the STM32 and the SD card in place?

**Comment by svs072477** [comment]
I am now making such a Board, except that I added the connection of the esp 32 module to the microcontroller via a separate SPI instead of UART. Use UART files are written via WIFI very slow
But my knowledge of programming is not enough to deal with a large project like Marlin

**Comment by jmz52** [comment]
MKS Robin uses SDIO interface to SD card.
And there are number of F1/F4 dev boards that have SD card reader wired to SDIO.

**Comment by boelle** [comment]
@svs072477 still working on this?

**Comment by sjasonsmith** [comment]
At least some boards are now using SDIO in both STM32 and STM32F1 HALs.
Closing this, as it seems to already be implemented.
