### ISSUE TITLE
Need help with TMC2130 

### ISSUE THREAD

**Issue by Wojimus** [MarlinFirmware/Marlin#11646]
Hi, The bug I'm encountering is the driver registers of my TMC2130 Drivers are 0x00000000. I have tested and there is approximately 5V going to the stepper drivers when the printer is turned on. I have been trying to bugfix this on my own for two months testing both 1.1.8, 1.1.8 bugfix, 1.1.9 and now 2.0 bugfix however none of these have solved my issue. I have triple checked the wiring but have also included pictures and my configuration files. I have been trying to bugfix this on my own for the past two months and would hate to have to revert to standard drivers. Thank you beforehand for any help anyone provides and if you require anything such as a voltage reading or any other file I will be happy to assist.

Also to help explain my wiring:
Yellow = MOSI
Green = SCK
Orange = MISO

Individual colours are CS

[Config Files.zip](https://github.com/MarlinFirmware/Marlin/files/2321082/Config.Files.zip)
![20180825_221455](https://user-images.githubusercontent.com/6164143/44623058-4386e780-a8bd-11e8-82ea-b207e0526046.jpg)
![20180825_221438](https://user-images.githubusercontent.com/6164143/44623060-45e94180-a8bd-11e8-889c-d19a1cbe974f.jpg)

**Comment by thinkyhead** [comment]
Be sure to do `M502`, `M500` to eliminate spurious symptoms caused by old EEPROM values.

**Comment by kAdonis** [comment]
Do you power your RAMPS only from USB?
The TMC drivers need 12V connected to your RAMPS **before** you connect USB

**Comment by Wojimus** [comment]
Thanks for the quick replies, @thinkyhead Unfortunately M502 and M500 Didnt produce any positive result, and @kAdonis It has also got 12V coming from the power supply.

**Comment by kAdonis** [comment]
have you checked the solder bridges on your drivers? Described in #8480

**Comment by Wojimus** [comment]
@kAdonis The solder bridge is not connected, Should it be?

**Comment by kAdonis** [comment]
No, the blue solder bridge should be open for SPI mode

**Comment by Wojimus** [comment]
@kAdonis Too bad that would have been an easy fix, I should also let everyone know that I have tested this with two Arduino Mega's and Two Ramps 1.4 boards.

**Comment by workheart** [comment]
take a Breadboard and a single arduino (mega/uno/nano) and try to get one single stepper with one single driver to run. p.ex. try https://github.com/teemuatlut/TMC2130Stepper/tree/master/examples/Live_tune.
or some other example sketches from arduino IDE, if one works: do a happy dance & test the others, than you can roule out that. if all are good, back to ramps, and start installing one after the other. always recompire firmware, smal steps but you know where the error started

**Comment by oakdesign** [comment]
Have you tried to use other CS Pins as you are using the PWM Pins o the Servo Header, so maybe reassing to AUX-2 40,42,65

Another hint maybe 
`#if DISABLED(SDSUPPORT)
  #define MAX6675_SS       66   // Do not use pin 53 if there is even the remote possibility of using Display/SD Card
#else
  #define MAX6675_SS       66   // Do not use pin 49 as this is tied to the switch inside the SD card socket to detect if there is an SD card present
#endif`
is causing troble as it reassings pin 66

**Comment by boelle** [comment]
@Wojimus problem solved?
