### ISSUE TITLE
Premature endstop enable on homing

### ISSUE THREAD

**Issue by vector76** [MarlinFirmware/Marlin#1164]
Homing enables and disables endstop detection and it works, however, endstops are enabled before it waits for the movement queue to be flushed via st_synchronize().  This causes the already-queued commands to be processed with endstops enabled.

Ordinarily this has no effect, since there are rarely movement commands that meet these conditions simultaneously: just prior to a homing command and endstops triggered.

I first came across it on a Printrbot Metal Simple which has an inductive z-probe and auto-leveling.  In this case the first few layers have the z-endstop triggered.  The bed-leveling compensation produces small nonzero z components to pure X Y movements.  If the print is very thin and homing is done after the print, some of the commands are truncated because endstops are enabled.

I was also able to reproduce this using only the X endstop.  This requires that the home X0 position be slightly beyond the point that triggers the X endstop.

The g-code below produces different behavior if a homing command (near the end) is added.

I believe this may be a simple fix -- simply add st_synchronize() before enabling endstops within G28.

    G21           ; set units to millimeters
    G90           ; use absolute coordinates
    G28 X0 Y0     ; home
    G1 X10 Y45   
    G1 X0.03      ; to exhibit bug, this must trigger X endstop
    G1 X0.01 Y40
    G1 X0.03 Y45
    G1 X0.01 Y40
    G1 X0.03 Y45
    G1 X0.01 Y40
    G1 X0.03 Y45
    G1 X0.01 Y40
    G1 X0.03 Y45
    G1 X0.01 Y40
    G1 X0.03 Y45
    G1 X0.01 Y40
    G1 X0.03 Y45
    G1 X0.01 Y40
    G1 X0.03 Y45
    G1 X0.01 Y40
    G1 X0.03 Y45
    ; G28 X0  ; without homing, nothing unsual.  With homing, previous commands exhibit different behavior

**Comment by boelle** [comment]
is this still an issue with a fresh copy of marlin and IDE updated to latest non-beta?

**Comment by thinkyhead** [comment]
@vector76 So do you think inserting `st_synchronize()` before [this line](https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/Marlin_main.cpp#L1555) is still necessary to fix the problem?

**Comment by boelle** [comment]
since @vector76 did not respond i will assume there is no issue anymore and close this one... it can always be reopened
