### ISSUE TITLE
[bugfix-2.0.x] Pausing a print and immediately resuming doesn't restore temp setpoints.

### ISSUE THREAD

**Issue by XBrav** [MarlinFirmware/Marlin#11640]
If you accidentally pause a print from the LCD menu and resume prior to the cached instructions completing, the print will continue, however the temperature setpoints for bed and nozzle will not be restored.

Configurations are attached. 

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2320346/Marlin.zip)

**Comment by boelle** [comment]
@XBrav still having issues with latest bugfix 2.0 ?

**Comment by XBrav** [comment]
I'll try it out this weekend and see if it is sorted out. Thanks!

**Comment by boelle** [comment]
@XBrav was it sorted out?

@thinkyhead i think we can close this one

**Comment by XBrav** [comment]
Hi Bo,

Unfortunately I have no time to test it out for the next while. Let's close
this, and I'll open a new ticket with further diag data if it persists.

**Comment by boelle** [comment]
good idea

only you can close by clicking the close button below, or @thinkyhead can do it once he have time
