### ISSUE TITLE
Marlin 1.1.9 Heatbed no longer heating or reading temperature

### ISSUE THREAD

**Issue by Gaz83** [MarlinFirmware/Marlin#11644]
I am using Octopi to control my printing and ever since upgrading to Marlin 1.1.9, my heatbed no longer heats up and does not read the temperature.

My heat bed is from a duplicator i3. 

I set the bed thermistor to 99 and downloaded a custom thermistor table to match. This has worked fine in version 1.1.8 but does not work in 1.1.9

[MarlinData.zip](https://github.com/MarlinFirmware/Marlin/files/2320882/MarlinData.zip)

**Comment by kAdonis** [comment]
you have set:

```
#define TEMP_SENSOR_BED 0
#define TEMP_SENSOR_CHAMBER 99
```
what you want is:
```
#define TEMP_SENSOR_BED 99
#define TEMP_SENSOR_CHAMBER 0
```

**Comment by Gaz83** [comment]
Well I am a dumb ass lol. Right so I corrected that and now I have a new issue. Every time I try a print I get this.

Error:MINTEMP triggered, system stopped! Heater_ID: bed

I had a quick look in the configuration file and noticed #define BED_MINTEMP 5. When I monitor in Octoprint it says the bed is off, where as the extruder is giving me a temperature reading of about 20 degree c.

So I change the 5 to a 1. Now I don't get the error but I did notice that in Octoprint that the bed says off until it hits 10 degrees c, then I get a reading.

Does this seem normal?

**Comment by kAdonis** [comment]
This it not normal
The temperature readings from bed and hotend should both show room temperature, when the printer is cold.
Your thermistortable is wrong.
You could try one of the standard tables and measure the real temperature yourself to find the best table for your thermistor

In the example config for the duplicator 6:

`#define TEMP_SENSOR_BED 1`

**Comment by AnHardt** [comment]
From your thermistor table:
> // 100k bed thermistor (Thermistor table 1 but -20 Deg)
const short temptable_99[][2] PROGMEM = {

Does it make you wonder?

**Comment by Gaz83** [comment]
Nope, because I'm a newbie lol. 

Quote from person who created the table for the duplicator i3

> I had to create a custom thermistor table because the standard board uses 10k pull-up resistors instead of 4.7K. (Not sure how good the table is.)

**Comment by thinkyhead** [comment]
The format of thermistor tables has changed, also. I'm not sure what the true values ought to be, but the format of thermistor tables is now like this:

```cpp
// 100k bed thermistor (Thermistor table 1 but -20 Deg)
const short temptable_99[][2] PROGMEM = {
  { OV(  174), 300 },
  { OV(  186), 295 },
  { OV(  199), 290 },
  { OV(  214), 285 },
  { OV(  230), 280 },
  { OV(  247), 275 },
  { OV(  266), 270 },
  { OV(  287), 265 },
  { OV(  309), 260 },
  { OV(  334), 255 },
  { OV(  362), 250 },
  { OV(  392), 245 },
  { OV(  426), 240 },
  { OV(  462), 235 },
  { OV(  503), 230 },
  { OV(  548), 225 },
  { OV(  598), 220 },
  { OV(  653), 215 },
  { OV(  714), 210 },
  { OV(  782), 205 },
  { OV(  858), 200 },
  { OV(  942), 195 },
  { OV( 1036), 190 },
  { OV( 1141), 185 },
  { OV( 1258), 180 },
  { OV( 1388), 175 },
  { OV( 1534), 170 },
  { OV( 1697), 165 },
  { OV( 1879), 160 },
  { OV( 2082), 155 },
  { OV( 2308), 150 },
  { OV( 2561), 145 },
  { OV( 2842), 140 },
  { OV( 3153), 135 },
  { OV( 3498), 130 },
  { OV( 3878), 125 },
  { OV( 4296), 120 },
  { OV( 4751), 115 },
  { OV( 5246), 110 },
  { OV( 5780), 105 },
  { OV( 6350), 100 },
  { OV( 6954),  95 },
  { OV( 7587),  90 },
  { OV( 8244),  85 },
  { OV( 8915),  80 },
  { OV( 9594),  75 },
  { OV(10270),  70 },
  { OV(10933),  65 },
  { OV(11573),  60 },
  { OV(12182),  55 },
  { OV(12752),  50 },
  { OV(13277),  45 },
  { OV(13753),  40 },
  { OV(14179),  35 },
  { OV(14554),  30 },
  { OV(14880),  25 },
  { OV(15159),  20 },
  { OV(15396),  15 },
  { OV(15593),  10 },
  { OV(15757),   5 },
  { OV(15890),   0 }
};
```

**Comment by boelle** [comment]
@Gaz83 is this still an issue when using bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
