### ISSUE TITLE
[bugfix-2.0.x] Marlin crashes when setting fade high during print

### ISSUE THREAD

**Issue by ikarisan** [MarlinFirmware/Marlin#11659]
Hi!

I am running "Marlin bugfix-2.0.x" (ba1919c1eb3b617f8570b74c8540ead3212f992f) and every time I try to change the fade hight via the graphical display (RepRap discount) Marlin crashes and resets as soon as I press the button.

**Comment by boelle** [comment]
@ikarisan is this still an issue if you use todays copy of bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
