### ISSUE TITLE
Scara kinematic

### ISSUE THREAD

**Issue by d185** [MarlinFirmware/Marlin#11663]
### Description
Any plans to implement 5 bar SCARA kinematic in 1.1.9 or 2.0? It is super useful kinematic for compact 3Dprinter. 

### Steps to Reproduce
PAVLOG make fork 3 years ago with support 5 bar SCARA kinematics. But it is not working in latest releases of Marlin.
APrinter also have this kinematics

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue. 
![2scara](https://user-images.githubusercontent.com/42758109/44696450-9e4b4b00-aa45-11e8-9bf2-a22787d689cb.gif)

* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by thinkyhead** [comment]
Marlin has support for SCARA kinematics, but they have not been touched for some time in the main repository. See the SCARA example configuration. A more complete version of SCARA kinematics —supporting tool offsets and other helpful features— will be contributed back to Marlin by the MakerArm project once they start shipping units.
