### ISSUE TITLE
Dual X Carriage and sensorless endstops TMC2130

### ISSUE THREAD

**Issue by workheart** [MarlinFirmware/Marlin#11669]
**setup**
arduinomega2560 with ramps-alike board , Marlin 2.0.bugfix 
6x tmc2130 Dual X Carriage 
30V on VM
5.00 VCC #
### Steps to Reproduce
use a Arduino mega based Board, setup for Dual X carriage 
with TMC2130 drivers for X and X2 including SPi AND Diag1 for endstops on X_min and x_max
Change corresponding lines in Conf_adv to enabel DUAL_X_CARRIAGE and
double check your pinout for SPI and Endstops
Home X
**Expected behavior:** [What you expect to happen]
 X2 Homes to 1 (and stops at the end)
than X homes to - 1
**Actual behavior:** [What actually happens]
X2 Homes to 1 and does not respond to physical end
 [ERROR] Error:Printer halted. kill() called 

#### Additional Information
**what I tried to solve**: to be sure the problem is not Hardware based, i changed the Pinout so that X1 is X2 and vice versa 
it is always "firmware X2" and not hardware related that X2 does not react on a Physical barrier.
as on dual X carriage X2 is always Homing bevor X1 is homing, i also wired up a microswitch to fake a endsop X2 "x-max" and than X1 Homes and there sensorless homing is working.

**mit head hurts on this:** X2 is homing to 1 X1 is homing to -1 so diag1 is conected to X-min (X1) and X-max (X2) is that correct? how can i further troubleshoot? do you have any cloue, or does someone know this should work?

**Bonus Quest::**
Diag1 is HIGH ~3.8V as "open" and LOW ~0V on closed, is it possible to Change that behavior, or (more importend) the timeing how long it is LOW (as i do hav supression caps 10uF) on my endstops and theoretical they could supress a too short LOW 

[dualXconfig.zip](https://github.com/MarlinFirmware/Marlin/files/2329723/dualXconfig.zip)

**Comment by Roxy-3D** [comment]
Ha!!!   I can probably help you with this...   But what 'Ramps like' board has 6 stepper motor sockets?   All the ones I've seen have 5 sockets.

I suggest you turn off the Quick Homing (#define QUICK_HOME) for starters...   And for IDEX,  X homes to X_Min.  X2 homes to X_Max.   Both of those end stops switches need to work!!!    Can you verify that with M119???    If you can get the simple homing to work...  Then we can play with the more complicated stuff.

**Comment by workheart** [comment]
perfect! i will try the quick home disabling trick, 
(easyes fist) 
I do know for sure that sensorless Homing (ther is no endstop) is working with this driver ont this port and this motor. I do know that the sensorless Homing works on X_min if i use a microswitch on X_max but i will test it in ~22h. just did shut down the workshop :-) 
on the  Board: it is home grown PCB

**Comment by bruce356** [comment]
Hi is this method of homing the X and X1 axis accurate enough for dual colour printing etc.
End stop for Y it does not matter if its not exactly the same at each homing.
To get the required accuracy on the X axis I used "Magnetic Hall Effect Endstops".
https://www.reprap.me/hall-e-endstop.html
regards - bruce

**Comment by workheart** [comment]
I do t think it is a problem for me as i mostly print with 0.8 to 1.2mm nozzles, but you ar right i didnt think about that, i will test it once it works.

**Comment by workheart** [comment]
@roxy sadly the quick home trick did not change the behavior, also i thing the problem with quick homing waa solved a few bugfixes ago (ther was an issiue with quick homing sensorless homing x&y)
Ao thats not the problem. 
I go and try to remapp.the pins so x2 acts as x without dual x carriage to truly verify that the sensorless treshold and driver settings ar correct and the problem is not Hardware related. Will be about tomorrow evening

**Comment by workheart** [comment]
Okay I tested the Hardware, if i "Change the drivers" or better switch the pinout so that another stepper and endstop i used for X2/X_MAX it oesend work either, so thats not the Problem here. it has to be Firmware related. where is the sensorless routine based? I will look around maybe i find something
Oh and i can confirm that X2 does stop if the endstop gets triggerd (by disconecting Diag1) 
but the stepper does nearly a complete revolution befor it stoped

**Comment by thinkyhead** [comment]
You may want to play around with your sensorless homing thresholds.

**Comment by workheart** [comment]
@thinkyHead the treshold is set to 1 witch works fine (nearly to low) if it is not setup as dual X carriage.

**Comment by Roxy-3D** [comment]
>  Problem here. it has to be Firmware related. where is the sensorless routine based? 

I have a number of IDEX changes to merge.    The IDEX code does have some bugs in it.   It will be another week before I have tested stuff to put back into the bugfix 2.0.0 code base.   Please be patient. 
(The DXC_AUTO_PARK_MODE is mostly unaffected by any bugs I've found so far...  )

**Comment by workheart** [comment]
Okay i'll add som mechanical endstops for further testing and get back ti it later. 
Thanks so far

**Comment by boelle** [comment]
@workheart any news?

**Comment by workheart** [comment]
I sadly have to confess that I moved to klipper FW with my IDEX machine... and got bored with it as it is just printing as it should, never used it again.
so for the Bug: sorry i dont know about the latest changes, but I might get back on it as i am testing a new PCB in some days (weeks)

**Comment by boelle** [comment]
@workheart oki, remember to use bugfix 2.0, its both 8 bit and 32 bit

**Comment by boelle** [comment]
@workheart had time to test the new pcb?

**Comment by workheart** [comment]
I am still on the elektrical part, we can close it if I find the time to
test it i will reopen the bug, if still existent.

Bo Herrmannsen <notifications@github.com> schrieb am Mi., 13. März 2019,
22:00:

**Comment by boelle** [comment]
sounds like a good plan, but only you can do it
