### ISSUE TITLE
[bugfix-2.0.x]  ENDSTOP_INTERRUPTS_FEATURE issues (reset, bltouch flickering, stepper noises)

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#11675]
When I enable ENDSTOP_INTERRUPTS_FEATURE, my steppers seem to receive random pulses. They move very slow or to the wrong direction and make unusual noise. At the same time, the bltouch starts to randomly deploy / stow. After some seconds, the arduino mega resets or looses communication with octoprint.

I use optical endstops now but I have experienced similar effects with mechanical endstops (micro switches) before, although not to that much extend. They would not trigger reliably with the interrupt feature enabled.

I guess what is happening here is an "interrupt storm". when the optical endstops are right at the threshold between 0 and 1. The LED at the endstops is half lit.
ENDSTOP_NOISE_FILTER does not change anything.

Is ENDSTOP_INTERRUPTS_FEATURE usefull after all? Saving CPU cycles during print is certainly important, but I think the endstops are not polled during printing, or am I wrong?

**Comment by forkoz** [comment]
On a 32 bit board you have enough CPU. On 8 bit board it helps a little. This much trouble its not worth it.
