### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by littlepedro78** [MarlinFirmware/Marlin#11670]
Arduino error: pasting "/* (bed)*/" and "_RPORT" does not give a valid preprocessing token
any help

![img_2376](https://user-images.githubusercontent.com/10800994/44784941-8c75bf00-ab8f-11e8-9610-91ec0526b4f7.JPG)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by cjsoong** [comment]
@littlepedro78  Do not use Arduino IDE V1.86, change back to V1.85.

**Comment by littlepedro78** [comment]
thanks solved
