### ISSUE TITLE
Automatic bilinear bed leveling doen't seen to be working properly

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#11679]
Even though I am using  bilinear autoleveling (3 X 3), I have  high and low spots on large test prints.  My grid looks like this: 
1 2 3
4 5 6
7 8 9

'7' is always too low and '6' is always too high.  I need advice.  Here's my setup:

I am running an Anet A8 using Octoprint and Marlin 2.x.  I have successfully added an inductive probe.  I have added G29;M501;M420 S1; to my start code after the last G28.  I have tested my probe accuracy and found an acceptable standard deviation (0.0027 actually, I think the correct term is population standard deviation).  When I run the bed visualizer in OctoPrint, I get a visualization of a symmetrical bed with a 0.4 mm hump in the middle (apparently not unusual).   My Z axis steppers are level.  My leadscrews and Z axis guide rods are no better and no worse than anyone else.  My best Z offset is -2.3 even though to just pass a sheet of paper I need to be down to -3.1 (odd).  Printing with a Z offset of -3.1 practically grinds into the bed.  I dont see this oddity as a problem as long as I know Z-2.3 is good.

What can I do to rid my printer of these high and low spots?  How can I find and fix the root problem.  If the root problem can not be addressed is there a way to program compensations into Marlin?  Should I be running a 5 X 5 pattern maybe?

Thoughts and advice?

Thanks,

Bill

**Comment by thinkyhead** [comment]
Make sure there is no twist in your X gantry. Even a small twist, or something pulling on the wires, etc., may be enough to misalign the probe during the procedure and produce garbage readings.

**Comment by bill-orange** [comment]
Could you expand on “twist in X gantry”?

**Comment by RudyBenner** [comment]
M420 S1 in your start script AFTER any G28. This was supposed to be fixed but is still problematic. I use M420 S1 Z2 to include fade height.

**Comment by bill-orange** [comment]
Put the M420 S1 after G28, okay. Before or after the G29 or does it matter?

**Comment by RudyBenner** [comment]
After the last G28. 

Here are a few lines from a gcode file.

; generated by Slic3r Prusa Edition 1.40.1+win64 on 2018-08-31 at 01:01:38

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.80mm

M107
M190 S50 ; set bed temperature and wait for it to be reached
M104 S200 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M900
M420 S1 Z4
; Filament gcode

I do not do a G29 for every print. But when I do, I turn on the bed heat.


M190 S60 ; bed heat on
G28 ;Home
G29
M190 S0 ; heat off
G28 Z
M420 P1 Z2

works for me.

**Comment by bill-orange** [comment]
On the second set of start code, doesn’t the G28 Z erase the G39 data you just collected?  I would think that you would need an M500 after the G29 and an **M501** after the G28 Z. 

In any case, I will move my M420 around and see if it matters. At this point I need, for starters, to figure out if the problem is mechanical or software.

**Comment by thinkyhead** [comment]
~~`M502` is a bad idea. It resets all settings to defaults.~~

**Comment by bill-orange** [comment]
Ah, not M502. I miss typed. M501 to store, not reset.  It will store your settings.
