### ISSUE TITLE
[2.0.x] Too long extrusion during filament change

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#11697]
I executed command by LCD and I got title message on host. I think this is not good, long extrusion check should not be considered during filament purge after change...

Am I wrong?

**Comment by GMagician** [comment]
And it's also weird.
My cnf has `EXTRUDE_MAXLENGTH 200` and:
```c++
  #define PAUSE_PARK_RETRACT_LENGTH
  #define FILAMENT_CHANGE_UNLOAD_LENGTH      100
  #define FILAMENT_CHANGE_SLOW_LOAD_LENGTH     0
  #define FILAMENT_CHANGE_FAST_LOAD_LENGTH    75
  //#define ADVANCED_PAUSE_CONTINUOUS_PURGE
  #define ADVANCED_PAUSE_PURGE_LENGTH         25
  #define FILAMENT_UNLOAD_RETRACT_LENGTH      13
  #define FILAMENT_UNLOAD_PURGE_LENGTH         8
```

I'll do it once again to test when message is asserted

Edit: It seems to assert it when restart printing.....

**Comment by GMagician** [comment]
Done other tests...echo messages appears after execution exited M600...
I also noticed in other situation a fast extruder advance while printer just after resume

**Comment by GMagician** [comment]
Ok. I found something weird...don't know how reference parameters works in c++ so I can't say if this is a code or compiler bug

Guilty code is in `Planner::set_position_mm` and line seems to be:
```c++
position[axis] = LROUND(axis_steps_per_mm[axis_index] * (v +
    #if ENABLED(AUTO_BED_LEVELING_UBL)
      axis == Z_AXIS && leveling_active ? ubl.get_z_correction(current_position[X_AXIS], current_position[Y_AXIS]) :
    #endif
    0
  ));
```

computed extruder value is 0. Just adding round brakets after `v` variable solve.

Here I attach original code disassembler and new my fix disassambler
[original.txt](https://github.com/MarlinFirmware/Marlin/files/2343753/original.txt)
[modified.txt](https://github.com/MarlinFirmware/Marlin/files/2343754/modified.txt)

**Comment by thinkyhead** [comment]
Thanks for catching this regression!

**Comment by GMagician** [comment]
May you give me an explanation about why brackets solve this?

I now how pointers works but reference is something like pointer for a specific type (is it?) when you add a value it should not change pointer base? What really happens on code?

Thanks

**Comment by AnHardt** [comment]
Without the brackets
```
(((v + axis) == Z_AXIS) && leveling_active)
```
is the condition, instead of adding the conditional value to v.

With brackets **you** can express what **you** want and don't have to trust in a **random** order of the compilers/languages priorities. Better have a few to much than omitting one. The compiler will optimise away, the additional ones (where you agree with the compiler), anyway. Adding brackets isn't a matter of not knowing about the languages priorities but expressing your explicit will how to do it. (Don't touch my brackets!)

**Comment by GMagician** [comment]
@AnHardt  I think this is not the issue, result was 0 but if you add 0 or 1 to 'v' you will never get such result

EDIT: sorry now is clear you said "test condition is different"

**Comment by AnHardt** [comment]
Did i say "condition**s** value"? I mean "condition**al** value", so either `ubl.get_z_correction(current_position[X_AXIS], current_position[Y_AXIS])` or `0` should be added to `v`.
if you compare `((v + axis) == Z_AXIS)` you will always get '0' (except for a very few special combinations of v and axis) - `false` for the condition and for that the therm behind the ':' is selected - also `0`.

Exceptions, assuming Z_Axis is 2, Y_AXIS is 1; X_AXIS is 0:
v=0, axis= Z_AXIS;
v=1, axis= Y_AXIS;
v=2, axis= x_AXIS

Maybe that translates badly from German to English - but i don't think so - maybe from English to your language.

**Comment by GMagician** [comment]
No it's me I misunderstood you..I edited my previously as soon as I correctly understood

**Comment by GMagician** [comment]
Since understood real cause, is not better to read something like:
```c++
position[axis] = LROUND(axis_steps_per_mm[axis_index] * (v +
    #if ENABLED(AUTO_BED_LEVELING_UBL)
      (axis == Z_AXIS && leveling_active) ? ubl.get_z_correction(current_position[X_AXIS], current_position[Y_AXIS]) :
    #endif
    0
  ));
```
instead of current solution?

**Comment by thinkyhead** [comment]
Code is patched, so all should be well now.
