### ISSUE TITLE
What does " Error: EEPROM datasize error." mean

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#11699]
I am running an Anet A8 using Octoprint and Marlin 2.x using Bilinear Bed Leveling.

 I tried changing `#define GRID_MAX_POINTS_X 3` to `#define GRID_MAX_POINTS_X 4`

I get the usual flash successful message but then an Octopi disconnect with Error: "EEPROM datasize error." 

On the LCD screen all appears well.

I suspect that I don't have enough EEPROM left for a 4 x 4 matrix since I am already on the ragged edge memory wise with the stock ANET board.

What does this error mean?

**Comment by GMagician** [comment]
> I suspect that I don't have enough EEPROM left for a 4 x 4 matrix

I think so or not enough to store current eeprom data structure

**Comment by thinkyhead** [comment]
> What does this error mean?

It means you need to do `M502`, `M500` to update the EEPROM, because you've changed the required storage size of the EEPROM by modifying `GRID_MAX_POINTS_X`.

**Comment by bill-orange** [comment]
This is my post flash code so that can not be it.  M502; M851 Z-2.48; M500; M117 Firmware Updated

**Comment by thinkyhead** [comment]
Un-comment this line in `configuration_store.cpp`, re-flash, and we'll be able to see the general location where the data-size differs…
```cpp
//#define DEBUG_EEPROM_READWRITE
```

**Comment by bill-orange** [comment]
Done! Oddly with `#define DEBUG_EEPROM_READWRITE`  I did not receive an error!  I made no additional changes ( other than the mesh size of course).  I can not explain it.

This is looking even more "bug-like" but difficult to reproduce.
