### ISSUE TITLE
[question][ATOM] preprocessor colors

### ISSUE THREAD

**Issue by Amachete** [MarlinFirmware/Marlin#11705]
Hello

I have just changed to ATOM, instead of using Arduino ide-Notepad++ and I am missing the "dim" of preprocessor blocks not actived.

I mean, I would like to see dimmed the preprocessor blocks which are disabled...

Is this posible with ATOM-Platformio?

Marlin uses as much Preprocessor blocks....that I think  you all are using this feature.

I googled but I was not able to find out how to do it.

Thank you all!

**Comment by thinkyhead** [comment]
Google Atom isn't as tightly integrated with the compiler as some other coding environments. And Visual Studio Code (VSCode) can't discern disabled blocks either.

Only editors / IDEs that access the low-level intermediate representation of the code can do this trick. If Atom and VSCode *could* manage it, they'd at least require the code to be compiled first. Maybe in the future there will be an update or plugin that can interpret the code.
