### ISSUE TITLE
Backtrace function definition

### ISSUE THREAD

**Issue by silentninja1** [MarlinFirmware/Marlin#11700]
Im getting a compile error about a duplicate definition of backtrace. Commenting out the empty definition on line 99 of Marlin/src/HAL/shared/backtrace/backtrace.cpp

void backtrace(void) {}

Seems to resolve the issue, but it seems its been there almost 2 weeks. Anyone else seeing that, or is their compiler happily ignoring the empty definition? I wouldve expected somebody else to have seen it since the last commit here was so long ago.

**Comment by thinkyhead** [comment]
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files and drop them into your next reply. We'll try compiling with them.

**Comment by silentninja1** [comment]
@thinkyhead It appears to be an ardunio ide issue, with the nightly build the error went away. The current "Stable" release is anything but... Compile errors on comments and more... Platform IO has some linter issues still on conditionals. I may go back to some of the visual studio plugins again for the moment. Hard to find a reliable method of building 2.0 that I can point people to.

**Comment by thinkyhead** [comment]
A linter isn't going to be very reliable because linters only operate on individual files, so they can't see `#include` dependencies outside of those directly referenced within each file. PlatformIO builds a dependency map, but doesn't seem to use it for linting.
