### ISSUE TITLE
Auto Leveling using Grid

### ISSUE THREAD

**Issue by MYasirSheikh** [MarlinFirmware/Marlin#1170]
Hi,

Can anyone provide me a link to the mathematical model details, used for the least square method in auto bed leveling using grid.
Also what actually qr_solve does. Need help for development

Thanks in advance :)

**Comment by boelle** [comment]
closing this one as there has been no messesges 3 months

**Comment by thinkyhead** [comment]
@MYasirSheikh Look up "least squares algorithm" to get the math. We're in the process of replacing this general solution code with something that just handles our case, which should make the code a lot simpler.

**Comment by thinkyhead** [comment]
@MYasirSheikh Look up "least squares algorithm" on Google to get the math. We're in the process of replacing this general solution code with something that just handles our case, which should make the code a lot simpler.
