### ISSUE TITLE
#define BLTOUCH causes Marlin compile error in 1.1.19

### ISSUE THREAD

**Issue by inventabuild** [MarlinFirmware/Marlin#11710]
### Description

When I eliminate the // in front of #define BLTOUCH and go to compile the firmware I get the following errors:
```
C:\Users\Mitch\Documents\Arduino\libraries\U8glib\src\clib\u8g_ll_api.c: In function 'u8g_NextPage.constprop':

C:\Users\Mitch\Documents\Arduino\libraries\U8glib\src\clib\u8g_ll_api.c:395:1: internal compiler error: Segmentation fault

Please submit a full bug report,

lto-wrapper.exe: fatal error: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.14.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/program files/windowsapps/arduinollc.arduinoide_1.8.14.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

Error compiling for board Arduino/Genuino Mega or Mega 2560.
```
### Steps to Reproduce

1. `//#define BLTOUCH` in `Configuration.h`
2. `#define BLTOUCH` in `Configuration.h`
3. Compile Marlin

**Expected behavior:** Firmware should compile

**Actual behavior:** Compile errors as stated above

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.
[Marlin-1.1.9_modified_for_TAZ4 - Copy.zip](https://github.com/MarlinFirmware/Marlin/files/2343839/Marlin-1.1.9_modified_for_TAZ4.-.Copy.zip)

**Comment by GhostlyCrowd** [comment]
Not an issue with Marlin. It's a bug in the new gcc compiler included in Arduino IDE.
To get Around either use Arduino IDE 1.8.5 or Platformio based Tools.
