### ISSUE TITLE
[ASK] Filament Zigzag and Extruder too close

### ISSUE THREAD

**Issue by dbstwn** [MarlinFirmware/Marlin#11728]
**Hi..** 

Before this, I have been try several 3D Printer, start from Cultivate, until now I am build m 3D Printer for myself, and I am doing some changing, the endstop Z I have been change using proximity metal sensor, LJ12A3-4-Z/BX, and it works well.

But I faced several problem that I have never been faced before.

1. The filament is filling out not linear, which mean the filament make a geometric like a zig-zag, (left and right. and I do not know how to solve this problem.

2. After several layers, the filament's geometric is nice, linear and order. But after 10th or 15th layer, the extruder is too close to the object, caused the object attracted from the top, and the object is moving. I have been read some article about increasing the Z-Stepper Feedrate and velocity, but it doesn't work. Because, after I changed the Z-Stepper until 1800, it still too close.

Could anyone help me to get out of these problems ?
The pictures:
https://intip.in/Problem1
https://intip.in/Problem21
https://intip.in/Problem22
https://intip.in/Problem23

Thank you.

**Comment by thinkyhead** [comment]
Be sure to use `M502`, `M500` whenever you change the configuration and re-flash.

**Comment by boelle** [comment]
@nechveirst 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
