### ISSUE TITLE
[2.0] To change  Fade height with LCD + sd card printing = Print crash

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#11720]
When i begin a print , if i want to change FADE HEIGHT with the lcd , the print crash and , i have to restart a new print

**Comment by rmoravcik** [comment]
What electronics are you using? Did you tried to measure voltage of power supply? Is it stable? 

For example, I have Full Graphic Smart Controller and software cannot control it's contrast.

**Comment by studiodyne** [comment]
It's a firmware bug , i used this feature before the new ' lcd menus configuration'

**Comment by rmoravcik** [comment]
I'm sorry, I very quickly read your problem and misread it. So ignore my previous post...

I've just checked the code and menu "Fade Height" is still there under "Tune" menu that's visible during SD-print, but you have to enable it in Configuration.h

```
    //
    // Leveling Fade Height
    //
    #if ENABLED(ENABLE_LEVELING_FADE_HEIGHT) && DISABLED(SLIM_LCD_MENUS)
      MENU_MULTIPLIER_ITEM_EDIT_CALLBACK(float3, MSG_Z_FADE_HEIGHT, &new_z_fade_height, 0, 100, _lcd_set_z_fade_height);
    #endif
```

So, you have to have ENABLE_LEVELING_FADE_HEIGHT enabled and SLIM_LCD_MENUS disabled.

**Comment by studiodyne** [comment]
Hi thks to help me , but , because of bad translation , you don't understand my issue

When i begin a print ,  if i want to change  FADE HEIGHT with the lcd , the printing crash and , i have to restart a new print

Thks
