### ISSUE TITLE
Configuration entry in menu is missing

### ISSUE THREAD

**Issue by LineF** [MarlinFirmware/Marlin#11726]
Hello,

I'm currently using marlin bugfix-2.0.x branch with commit 491e7016 (02.09.2018).
I noticed that during printing the menus for adjusting speed, acceleration and jerk aren't accessible any more. The complete configuration menu entry is missing during printing.

In my last used version (about may '18) the menu entries were still there.

In the configuration files I didn't find any option to get the menu entry back.
The options were very helpful to adjust printing parameters while printing!

How can I get the entries back again? Did I miss something?

Martin

**Comment by marcio-ao** [comment]
See this comment:

https://github.com/MarlinFirmware/Marlin/pull/10360#issuecomment-417802100
