### ISSUE TITLE
[FR] Make manual E moves relative (esp. multi-extruder)

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#11724]
Suppose the user wants to extrude 50mm from E1 and 10mm from E2 at powerup. Currently, this is what they have to do:

- Pre-heat nozzles
- Go to Movement > Move Axis > Extruder 1
- Turn the knob until the position goes from 0mm to 50mm (50 mm will be extruded from E1)
- Go to Movement > Move Axis > Extruder 2
- Turn the knob until the position goes from 50mm to 60mm (10 mm will be extruded from E2)

This makes sense if you understand that internally Marlin only has one "axis position" for both extruders, but to an end-user it makes no sense and isn't particularly helpful if they want to extrude or retract a particular amount of filament without having to do math. For the user, it would make more sense if it worked like this:

- Pre-heat nozzles
- Go to Movement > Move Axis > Extruder 1
- Turn the knob until the position goes from 0mm to 50mm (50 mm will be extruded from E1)
- Go to Movement > Move Axis > Extruder 2
- Turn the knob until the position goes from 0mm to 10mm (10 mm will be extruded from E2)

I think this could be accomplished by storing the current value of the E axis when the user enters the "Extruder 1" or  "Extruder 2" screen and subtracting that out from the value that is shown in the adjuster. That way, the adjuster will always begin at 0 mm and will represent a relative offset, rather than an absolute position.

**Comment by marcio-ao** [comment]
This is what I came up with in `ultralcd.cpp`:

```cpp
 #ifdef LCD_MANUAL_EXTRUDE_RELATIVE
    float manual_move_e_origin = 0;
 #endif

 void _lcd_move_e(
    #if E_MANUAL > 1
      const int8_t eindex=-1
    #endif
  ) {
  ...
  if (lcdDrawUpdate) {
     ...
     lcd_implementation_drawedit(pos_label, ftostr41sign(current_position[E_AXIS]
        #if IS_KINEMATIC
          + manual_move_offset
        #endif
        #if defined(LCD_MANUAL_EXTRUDE_RELATIVE)
          - manual_move_e_origin
        #endif
      ));
    }
  }

  void _lcd_move_distance_menu(const AxisEnum axis, const screenFunc_t func) {
    _manual_move_func_ptr = func;
    START_MENU();
    #if LCD_HEIGHT >= 4
      switch (axis) {
        ...
        default:
          STATIC_ITEM(MSG_MOVE_E, true, true);
          #ifdef LCD_MANUAL_EXTRUDE_RELATIVE
            manual_move_e_origin = current_position[E_AXIS];
          #endif
          break;
      }
    #endif
    MENU_BACK(MSG_MOVE_AXIS);
    MENU_ITEM(submenu, MSG_MOVE_10MM, lcd_move_menu_10mm);
    MENU_ITEM(submenu, MSG_MOVE_1MM, lcd_move_menu_1mm);
    MENU_ITEM(submenu, MSG_MOVE_01MM, lcd_move_menu_01mm);
    END_MENU();
  }
```

Thoughts?

**Comment by thinkyhead** [comment]
Seems like a reasonable idea. I can't think of too many use-cases where someone would very much need to see the real E coordinate.

**Comment by marcio-ao** [comment]
@thinkyhead: In my implementation above, I declared a new float variable "manual_move_e_origin", but it seems like when IS_KINEMATIC is declared, "manual_move_offset" has a similar purpose. I wonder if these two functionalities can be combined and save on RAM? I don't understand enough about what is happening when IS_KINEMATIC is defined to combine the two functionalities, however.

**Comment by marcio-ao** [comment]
I made my original suggestion into a PR (https://github.com/MarlinFirmware/Marlin/pull/11733).

I did not attempt to save RAM by reusing "manual_move_offset" since it looks like that may be a non-trivial change. Using a different variable does keep the two use cases clearly separated and makes it easy to disable the feature in "Configuration_adv.h" if it is not desired.

**Comment by thinkyhead** [comment]
The `manual_move_offset` variable is the accumulator for all manual moves.
