### ISSUE TITLE
TMC2130 and dual motors on the z axis with wrong directions

### ISSUE THREAD

**Issue by oangelo** [MarlinFirmware/Marlin#11735]
### Description

I'm having a very strange problem. Using the TMC2130 (SPI) and two motors on the z axis, a very strange behavior happens. When the z-axis should rise, each motor rotates in opposite directions, bending the x-axis. When the z-axis must be lowered, both motors rotate in the same direction and the x-axis descends correctly. I already tried both versions of bugfix (1.1, 2.0) without lucky.

**Comment by ManuelMcLure** [comment]
Are both motors connected to the same driver or are they on separate drivers?

**Comment by RudyBenner** [comment]
Could you reverse the motor connections on one motor?

**Comment by oangelo** [comment]
@ManuelMcLure , I have separate drivers. @RudyBenner , reverse the motor connections will fix one direction (up) and mess the other (down). I was using DRV8825 before, and it was working fine. I guess the problem is related with TMC2130.

**Comment by teemuatlut** [comment]
> reverse the motor connections will fix one direction (up) and mess the other (down). 

Flip only one.

**Comment by kAdonis** [comment]
It looks like, one of your drivers is not receiving the direction signal
Check the pinheaders at the TMC2130. Are they soldered properly? Especially the DIR pin

**Comment by oangelo** [comment]
Indeed, one of the drivers dir pin was not working. Thanks for the support guys.
