### ISSUE TITLE
[2.0] stepper drive inconsistent

### ISSUE THREAD

**Issue by maukcc** [MarlinFirmware/Marlin#11742]
On our system we tested the 2.0 firmware and got some strange results.
![img_20180906_151043](https://user-images.githubusercontent.com/1001516/45159905-561bed80-b1e8-11e8-855d-a7a49e03488f.jpg)
On the left is a test piece printed with 1.1 RC6 on the right with 2.0
Everything is the same, only the firmware has changed.

**Comment by LichtiMC** [comment]
Newer firmware (I think since about feb. 18 or so) produces such results all the time (at least for some) and apparently nobody knows why...

**Comment by kAdonis** [comment]
Some Details about your hardware and configuration would be helpful

**Comment by maukcc** [comment]
Processor : Arduino mega (this issue also occurs with due)
stepperdrivers: Leadshine DM442

settings in 2.0:
#define MINIMUM_STEPPER_DIR_DELAY 50000
#define MINIMUM_STEPPER_PULSE 15

Is the MINIMUM_STEPPER_DIR_DELAY being used on both upwards and downwards slope of the pulse ?

**Comment by kAdonis** [comment]
I am no expert, but I wrote you because your print looks a lot like mine (issue #11047) This should affect only 32bit, coreXY machines, but the Issue isn't solved yet
According to the DM442 datasheet your driver needs a minimum step pulse width of 2.5μs and a driver dir delay of 5000ns. So step pulses being too short seems not to be your problem, nevertheless you could check with a logic analyzer.

**Comment by maukcc** [comment]
As stated this happens with a 8bit Mega and also with the 32bit Due. (our electronics can handle both)
We checked with a scope, and confirmed that when the dir pulse got high the step pulse was behind it, but we could not get a clear image of the dir pulse going low, and if the step pulse was behind that as well. At this point I am guessing it is not.

It is also highly consistent. When we print a rectangle of 30x30x50mm  It always moves the same amount to X+ and Y+, giving us a tower of Pisa, with the same angle every time.  So over 50mm in Z direction it moves 0.9mm in X+ direction and 0.7mm in Y+ direction. So that is 3-4micrometers every layer.
The rectangle is printed CCW, and I am willing to bet that when we could print it CW it would move in X- and Y-.

**Comment by maukcc** [comment]
Duplicate of #11047
Closing
