### ISSUE TITLE
BLtouch often wont retract

### ISSUE THREAD

**Issue by julianCast** [MarlinFirmware/Marlin#11756]
### Description

I know there are so many issues about the bltouch, I'm close to giving up, but I want to give it another chance.
- Tevo tarantula
- mks 1.4 base
- smart 2.0 bltouch

### Steps to Reproduce

1. Cancel/finish a print, then G29.

**Expected behavior:** Auto leveling correctly

**Actual behavior:** The bltouch stick will deploy but it wont retract when touching the bed. Crash.
#### Additional Information

I can send logs,serials, files, videos,check things, try specific branch,...anything you guys need to fix this common problem

**M48 Z-Probe Repeatability Test**
Finished!
Mean: -0.000525 Min: -0.015 Max: 0.014 Range: 0.029
Standard Deviation: 0.009111
X:100.00 Y:134.00 Z:15.00 E:0.00 Count X:8000 Y:10720 Z:24000

**Comment by brandstaetter** [comment]
Which version? configuration.h and configuration_adv.h?

**Comment by GMagician** [comment]
Well, if my memory is right, bltouch automatically stow after detection, even without "marlin code".
If it doesn't stow it may means it doesn't detect, this may answer to "then crash on the bed".
Have you checked proper position of top screw?

**Comment by julianCast** [comment]
I have JimBrown now, this is the zip with the configuration.h and advanced, Im posting the issue here because of this happens with marlin also (https://github.com/MarlinFirmware/Marlin/issues/6807).
This is the 1.1.x version.

@GMagician If the problem were the screw always would crash, but it's just sometimes.

@brandstaetter 
[configurations.zip](https://github.com/MarlinFirmware/Marlin/files/2362229/configurations.zip)

**Comment by julianCast** [comment]
This is for those with the same problem:
I fixed it ! I can't believe it was just the height (the distance between nozzle and bltouch), I trusted a downloaded mount, I modified just 1 mm and it work perfect everytime. Hardware problems are the best. phew.

**Comment by thinkyhead** [comment]
> the distance between nozzle and bltouch

Great! That's what I was going to suggest checking first. This is a common issue.
