### ISSUE TITLE
Why my printer is ignoring the endstops?

### ISSUE THREAD

**Issue by Xenoyr** [MarlinFirmware/Marlin#11760]
Hi, first of all sorry for my bad english, and thanks
I open another thread because the old oine has been closed
But anyway I have the same problem, My printer is ignoring the endstop
If the logic is setted true/false, or the endstop is constantly active/closed
so, or the mottors can go to only one direction, segnalating that the endstop is constatly active
or if they can go to both direction, but the endstop arent readen
so, isnt a problem of the  logic of endstop, and also it isnt a problem with bad connection of cables

Im using the more recent version of Marlin
with an trigorilla 2560 1.4 and ctc i3 wood body
with tmc2208 driver

And Also I follow this scheme
![image](https://user-images.githubusercontent.com/40528627/45240263-4f749f80-b2e8-11e8-80b0-795126a1f248.png)

**Comment by GMagician** [comment]
Have you tested your endstops with M119?
No press should be all "open" and when you keep pressed one, it should give you "triggered".
Post also your current configuration (attach files)

**Comment by Xenoyr** [comment]
@GMagician the z and y are showed as triggered
for the files.. after because.. well I change my pc
and for any reason, transferring the files
even with copy and pasting (idk)
my changes of marlin are gone, so actually, I dont have a copy of my configuratione >.<

**Comment by brandstaetter** [comment]
Check out #11730 for a configuration example for the Anycubic Kossel - you can use it as starting point to modify things to your needs

**Comment by Xenoyr** [comment]
@GMagician Im using this configuaration:
[marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2373030/marlin.zip)
with this setting, m119: x,y,z = open
but
still the same problem

**Comment by Xenoyr** [comment]
up

**Comment by GMagician** [comment]
@Xenoyr it's ok that you have open when micros are released, but when you press them? M119 reports proper endstop triggered?

**Comment by Xenoyr** [comment]
@GMagician Even when I press them, they say Always open
but if I reverse the logic of endstop, opposite problem
always triggered

**Comment by AnHardt** [comment]
Do you have the right board configured?
Test the boards pins. Take a wire and connect the pins to ground -- M119. Then connect to 5 or 3.3V - M119. If neither shows triggered you are either testing the wrong pins, or they are defect.
Test the endstops without the board, with just power and a voltmeter.
If the switches do work, connect them correctly.

**Comment by Xenoyr** [comment]
@AnHardt the endstops works..  I just tested them in a different board
yeah.. I change the board name, and take the name from the board section
Im a newbie.. so I think I didnt understanstand well what I need to do for testing the pinboards..

**Comment by brandstaetter** [comment]
Which board hardware are you using, maybe you picked the wrong board name?

**Comment by Xenoyr** [comment]
@brandstaetter trigorilla 2560 1.4,

**Comment by Xenoyr** [comment]
up

**Comment by Xenoyr** [comment]
I dont think its the motherboard, because I just buy another 3d printer (anycubic i3 mega), (but nevere tryed with the basics driver), and with tmc2208 I still have the same problem

**Comment by Xenoyr** [comment]
@brandstaetter , @AnHardt , @GMagician  maybe I undestand why, the steppers can work in a determinate area, if this dont coincide with the actually aerea of the 3d printer, they can go over the actually area of the 3d printer, even ignoring the endstop, and also if the area of the steppers < 3d printer aerea, they also dont touch any "barrier" of the 3d printer, how I can solve this issue?

**Comment by GMagician** [comment]
ENDSTOPS_ALWAYS_ON_DEFAULT will keep endstops always under control. But if your software limits (the ones in config) are smaller...no way to move outside them

**Comment by Xenoyr** [comment]
@GMagician Thanks, I watch the configuration that I was using, and also a marlin stock one, that was commented; but what if the area doesnt coincide with the 3d printer? anything like this:  https://imgur.com/a/nCt2xgO

**Comment by GMagician** [comment]
You are in trouble ;-)

Layout you propose is a little bit weird. In such situation your "usable" area is the intersection of the two.
In proposed case, since you can't use "3d print area" left lower corner as 0,0 since is not reachable I would consider 0,0 the lower left corner of "stepper operative area" and max XY will be upper right corner of intersection.
Usually "stepper operative area" is bigger then "printable area" so you can move all over the bed and get some free area in the borders. this such standard situation 0,0 is lower left corner of bed.

**Comment by Xenoyr** [comment]
@GMacician
So.. to solve this problem What I can do? I Remember there is a section below of the bed area, that might move the operative section area of the stepper in the right area..but, how can I give the precise value?

**Comment by thinkyhead** [comment]
> up

http://opensoul.org/99ways/#34

**Comment by boelle** [comment]
@Xenoyr problem solved?
