### ISSUE TITLE
[2.0.x] Delta Calibration > Delta Height: no speed up when turning knob faster

### ISSUE THREAD

**Issue by brandstaetter** [MarlinFirmware/Marlin#11779]
### Description

When setting the temperature, there's a speed up of the value change if you turnthe knob/encoder faster.
In the `Configuration > Delta Calibration > Delta Settings > Height` this speedup does not happen, which makes it a bit annoying if the value has to be changed by a larger amount.

### Steps to Reproduce

1. `Configuration > Delta Calibration > Delta Settings > Height` 
2. Turn encoder knob slow and fast

**Expected behavior:** bigger value change when turning faster

**Actual behavior:** same value change independent of speed

Configuration see #11730

**Comment by boelle** [comment]
@brandstaetter problem solved?

**Comment by brandstaetter** [comment]
@boelle nope. Did not notice any changes.

**Comment by boelle** [comment]
i just saw the PR merged and the silence so assumed problem was fixed in the latest bugfix 2.0

**Comment by brandstaetter** [comment]
Oh, no, there were no related changes in that change.

**Comment by boelle** [comment]
missing a label

**Comment by thinkyhead** [comment]
Soon this will be changed. In the meantime, patch your code thusly…
```diff
- MENU_ITEM_EDIT_CALLBACK(float52sign, MSG_DELTA_HEIGHT, &delta_height, delta_height - 10, delta_height + 10, _recalc_delta_settings);
+ MENU_MULTIPLIER_ITEM_EDIT_CALLBACK(float52sign, MSG_DELTA_HEIGHT, &delta_height, delta_height - 10, delta_height + 10, _recalc_delta_settings);
```
