### ISSUE TITLE
set z home offset

### ISSUE THREAD

**Issue by marcostrullato** [MarlinFirmware/Marlin#11771]
Hi everyone, 

I have a custom anet a8 where I installed marlin 1.1.8. 
The printer has an hallon sensor (https://www.thingiverse.com/thing:2838259) 

I'm struggling with setting the offset, it looks like something funky is going on.

These are the command I'm sending to set home:

```
>>> g28
SENDING:G28
>>> g0 z0
SENDING:G0 Z0
echo:Probe Z Offset: -1.09
>>> M851 Z-1.09
SENDING:M851 Z-1.09
echo:Probe Z Offset: -1.09
>>> m500
SENDING:M500
echo:Settings Stored (642 bytes; crc 45841)
```

Then to verify the setting I go z home

```
>>> g0 z0
SENDING:G0 Z0
```

With this the printer moves back up 1.09 cm.

What do you think?

**Comment by jfint** [comment]
I had this happen, send a G28.  Then tgry a G1 Z0, are teh G28 it worked for me.

**Comment by thinkyhead** [comment]
First, update to 1.1.9.

Second, `M851` is for a probe, not for an endstop. `M206` is the command for setting a home offset.

**Comment by boelle** [comment]
@marcostrullato tried what thinky suggested?

**Comment by boelle** [comment]
@Thinkyhead i think we can close this one
