### ISSUE TITLE
G29 fails after a G28 if Z_PROBE_OFFSET_FROM_EXTRUDER is above -2mm

### ISSUE THREAD

**Issue by Patrick60** [MarlinFirmware/Marlin#11780]
Hi,

I've installed version 1.1.9 and I noticed an issue I didn't have with 1.1.8. When executing a G29 command (after a G28, so Z position is known), the probe (BLTouch) doesn't go down enough and stops before hitting the bed. In the method run_z_probe(), there's a calculation to find the target z position when probing:

const float z_probe_low_point = TEST(axis_known_position, Z_AXIS) ? -zprobe_zoffset + Z_PROBE_LOW_POINT : -10.0;

I think that it should be zprobe_zoffset  without the minus sign. In my case it's -3.50 and the default value for Z_PROBE_LOW_POINT  is -2. So the z target is -(-3.50) - 2 = 1.50 and it'sabove the bed. I've increased Z_PROBE_LOW_POINT to -5 to fix it, so no big deal. I just wanted to mention it.

**Comment by thinkyhead** [comment]
The equation is correct.

If the probe extends below the nozzle, then we expect that the nozzle will be above the bed, at around `-zprobe_zoffset` when the probe triggers. But, just in case the bed varies, the `Z_PROBE_LOW_POINT` is also added on, giving a little more movement distance. Yes, indeed, you do want the nozzle to be at 1.50mm above the bed in the case you described. If a BLTOUCH decided to fail, this will do less damage to the pin than if the probe continues to move down to where the nozzle is touching or below the bed.
