### ISSUE TITLE
Power loss feature bug (Cr-10S)

### ISSUE THREAD

**Issue by Liger0** [MarlinFirmware/Marlin#11786]
Hi there. I just updated to the latest TH3D_UFW_U1.R2.1a Firmware, which is initially based on Marlin 1.1.9.
When the print ends and I normally switch the power off, it will trigger this function anyway since when I turn it on it will ask me if I want to resume or stop the print, which is useless since it ended already.
On the stock cr-10S firmware I didn't have this issue.

**Comment by thinkyhead** [comment]
Please test the current bugfix branches to see if the problem still exists there. If not, then we can close this issue as solved.

**Comment by Liger0** [comment]
> 
> 
> Please test the current bugfix branches to see if the problem still exists there. If not, then we can close this issue as solved.

I don't unfortunately have time to test the stock marlin firmware right now, but even the latest TH3d firmware based on Marlin still doesn't solve it, so I guess it should be the same for Marlin since the code isn't changed.

**Comment by InsanityAutomation** [comment]
TH3D is well behind the bugfix branches. You cant take that as an assumption on if an issue still exists. 2.0 has had heavy modifications in many places since his last snapshot. (which i believe is 1.1.9)

**Comment by thinkyhead** [comment]
Marlin 1.1.x is end-of-life and won't be receiving much attention, so to get the latest patches, including this week's patches to power-loss recovery, you'll have to migrate to Marlin 2.0.x.
