### ISSUE TITLE
Spelling Error "Leveling" vs "Levelling"

### ISSUE THREAD

**Issue by CriticalPoint** [MarlinFirmware/Marlin#11791]
### Description

Throughout Marlin v1.1.9, the spelling of "Levelling" is incorrectly spelt as "Leveling"

### Steps to Reproduce

#define MESH_BED_LEVELING
#define LCD_BED_LEVELING
1. Use Mesh_Bed_Leveling via the LCD

**Expected behavior:**
It works, but the OCD in me makes me audibly gag

**Actual behavior:**
You see the message "Leveling Done!"

#### Additional Information ####

Doing a find and replace can mitigate the spelling error, however it will throw an error as Arduino cannot then reference the file "mesh_bed_leveling.h", as this is also spelt wrong.

**Comment by CriticalPoint** [comment]
![levelling](https://user-images.githubusercontent.com/3483630/45296277-6b9b5b00-b4f9-11e8-9d17-f45cffa714d6.jpg)
Urgh, don't worry, I've just reali**s**ed that it's cultural

**Comment by CriticalPoint** [comment]
My friend David has something to say about all this - https://www.youtube.com/watch?v=om7O0MFkmpw

**Comment by rmoravcik** [comment]
Well, you can create a new language file (`language_en-uk.h`) and translate strings to British English. :-)

**Comment by Roxy-3D** [comment]
I'm a horrible speller....   And I know I have spelling errors in my code and comments....

Oh well....

**Comment by CriticalPoint** [comment]
Isn't that part of your workflow, to revisit the code once it's complete and tidy it up, spell check et-cetera? Personally I always go through my code once it works, I wouldn't put my name to it until it's finished.

Possibly a bit different for me, being a professional, but I still believe one should put 110% into anything they make, physical or not!

**Comment by thinkyhead** [comment]
> Urgh, don't worry, I've just realised that it's cultural

True. We don't have _courgettes_ and _aubergines_ here in the States.

> Isn't that part of your work flow, to revisit the code once it's complete and tidy it up, spell check et-cetera?

I take it upon myself to clean up any submission that I can review before it gets merged, and I spent ages doing cleanup when I first arrived on the scene. Part of it is having my name associated with the commits, but I also think it's important to provide consistent and readable code with concise and clear commentary for people new to the codebase who may be wanting to modify it or study it academically.

That said, the HAL is currently in a process of rapid expansion and elaboration, so I'm holding off on a big cleanup and overhaul of that folder until a bit later on.

**Comment by Roxy-3D** [comment]
> Possibly a bit different for me, being a professional, but I still believe one should put 110% into anything they make, physical or not!

Is that extra 10% (of the 100%) being critical of other people's donated effort?   Is it raising issues about spelling mistakes that are not real and in no way affect the quality of the code.   Is it an extra 10%?  Or is it just being unappreciative and ignorant?

**Comment by thinkyhead** [comment]
Well, of course his handle _is_ "**Critical**Point." 🤣

**Comment by CriticalPoint** [comment]
Duped by my phones auto-correct, thanks for the edits thinky, just the right amount of cunting, I can tell we'd get along well.

Either way, the response was specifically directed at Roxy's "Oh well...", and not even maliciously, it's just that I personally can't stand the laissez-faire "don't really care that it's not finished as it works" approach. That 10% Roxy is the inferred additional effort that mitigates my previous statement, one might even call it pride.

Noted that I originally believed it to be a typo, because I'm stoopid and didn't realise it was spelt differently between the two adaptations of said common language. I then remembered a funny video I watched and thought "Hey, I'll post that and that might get a laugh" and then didn't think too much more about it.

I thought I'd do as rmoravcik suggested and create the language file, the easiest way being to clone the preexisting language_en.h and make the changes, but I found that in that file, the word was already spelt with a pair of L's.

![levelling_language_en_h](https://user-images.githubusercontent.com/3483630/45417826-f48dd000-b67a-11e8-9331-2be5df89b51e.jpg)

Anyway, I didn't mean to trigger anyone, I appreciate the project and the efforts that people donate to the common cause, thinky you've helped me lots over the past year or so, I went through a spell (ha haaa) of searching for fairly niche issues and your name came up more than most, so for that alone I'm thankful.

And yes, you've nailed it, that is exactly why my handle contains the word, because I am extremely critical. It's nothing short of a curse.

**Comment by CriticalPoint** [comment]
> thinky you've helped me lots over the past year or so, I went through a spell (ha haaa) of searching for fairly niche issues and your name came up more than most, so for that alone I'm thankful.

To be more precise I'm referring to Grbl on the whole, as opposed to Marlin specific issues

**Comment by thinkyhead** [comment]
No worries, CP, and happy to help out in those niches where I can! I do like the idea of a UK English language file. If you have one started, please post and I'll see that it's added to the codebase. Because of the way Marlin works, it only needs to contain the strings that differ from US English.
