### ISSUE TITLE
[1.1.x] - Multiple k-factors

### ISSUE THREAD

**Issue by margaale** [MarlinFirmware/Marlin#11803]
No issues here. Just sharing that i ported over the 2.0 feature (#11789) into my 1.1.x fork.

margaale/marlin@969a9743ced21fff42615d099b3aaea68918b476

Thanks for your work and dedication

**Comment by thinkyhead** [comment]
Looks good! I hope we'll have Marlin 2.0 out at least in an official beta some time before the end of the year.
