### ISSUE TITLE
Add support for Megatronics v3.0

### ISSUE THREAD

**Issue by Faiotech** [MarlinFirmware/Marlin#1180]
Why Marlin v1.0 have not support for that board?

I tried to upload this version (with modification in configuration.h and pins.h for megatronics v.3) but there's some problem in serial comunication I think there is more than a pins configuration.

**Comment by boelle** [comment]
closing this one... as said in other issues support for new hardware should come from the inventors and not us

**Comment by thinkyhead** [comment]
Sounds like it's already working, at this point. But if needed we can peek at @morgan-it's pins.h file.
