### ISSUE TITLE
M205 is in units/min or units/s?

### ISSUE THREAD

**Issue by eyal0** [MarlinFirmware/Marlin#11818]
https://github.com/MarlinFirmware/Marlin/blob/c37d3ae97d9372d2aba0ef5bc1146181740bc815/Marlin/src/gcode/config/M200-M205.cpp#L132

According to the documentation here: http://marlinfw.org/docs/gcode/M205.html

It ought to be in units/min.  However, it is assigned to a variable with suffix "_mm_s", which means mm/s.  That's off by a factor of 60.

Should that line have the MMM_TO_MMS macro invoked?  Or is the documentation wrong?

**Comment by thinkyhead** [comment]
The documentation was wrong. Now fixed, thanks!

**Comment by eyal0** [comment]
I see that new documentation already.  Thanks for your prompt fix!
