### ISSUE TITLE
[2.0.x, Question] Does LINEAR_ADVANCE support dual extruders?

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#11810]
Does LINEAR_ADVANCE currently support dual extruders? We are seeing some fairly bad dual-prints when that feature is enabled, although it looks fine on a single extruder hotend. Just curious whether LINEAR_ADVANCE takes into account the possibility that you might have multiple extruders.

**Comment by Bluelinegecko** [comment]
It looks like someone was already working on this and merged it in a few days ago in this thread #11789

**Comment by marcio-ao** [comment]
I guess that thread is about using different K factors per nozzle. So I guess it is supposed to work fine with duals? In my particular case, both nozzles have the same K factor. It just wasn't sure to me whether the algorithm in Marlin had been implemented to take into account two nozzles (in which case each nozzle would need its own set of state variables, as the pressure in each would be different)

**Comment by marcio-ao** [comment]
Attached is a photo of what we are seeing on a dual print -- on the right side there are alternating layers of over and under extrusion. The left print was done with LIN_ADVANCE and JUNCTION_DEVIATION off, while the right print was done with LIN_ADVANCE and JUNCTION_DEVIATION on. Though I have not tested both features independently, I suspect LIN_ADVANCE as the cause of the problem.

The material is PLA on both nozzles, so independent K factors should not be needed.

![img_4558](https://user-images.githubusercontent.com/29129419/45447221-22c7db80-b68c-11e8-9041-c63ddcd886f3.JPG)

**Comment by margaale** [comment]
Yesterday i saw something similar in my printings. Just finished installing a chimera an i saw an overextrusion on the second nozzle. Both are well calibrated on their own. Printing exclusivelly with the second nozzle works as usual...
![img_20180912_203842](https://user-images.githubusercontent.com/20794934/45458870-18c5cd00-b6cc-11e8-8e71-5348a78ba4f8.jpg)
Violet is hips as support and is printed fine. White is abs and that's the second nozzle

**Comment by Sebastianv650** [comment]
As long as we are talking about classic dual nozzle systems and not mixing ones it should work. But I was never able to test it as I don't have a multi nozzle printer.
Some questions:
- A print using only nozzle 1 is OK?
- A print using only nozzle 2 is OK?
- When both nozzles are used in a print but one nozzle is only used up to some height below the max. print height, does the print looks OK above this level where only one nozzle is working again?

**Comment by marcio-ao** [comment]
Just to update this post, we were able to get a good print with just LINEAR_ADVANCE turned on. So perhaps it is a combination of LIN_ADVANCE and JUNCTION_DEVIATION, or it actually is JUNCTION_DEVIATION that is causing a problem.

**Comment by margaale** [comment]
> A print using only nozzle 1 is OK?
A print using only nozzle 2 is OK?
When both nozzles are used in a print but one nozzle is only used up to some height below the max. print height, does the print looks OK above this level where only one nozzle is working again?

- Yes
- Yes
- No

> Just to update this post, we were able to get a good print with just LINEAR_ADVANCE turned on. So perhaps it is a combination of LIN_ADVANCE and JUNCTION_DEVIATION, or it actually is JUNCTION_DEVIATION that is causing a problem

Mine has the same settings. Gonna try this weekend all the posible combinations
