### ISSUE TITLE
Marlin 2.0 sensorless homing on Delta

### ISSUE THREAD

**Issue by grieml** [MarlinFirmware/Marlin#11823]
Hello everyone, 

yesterday I tried Marlin 2.0 on my delta machine. I use the einsy rambo and also enabled sensorless homing:

I played around with the sensitivity but the Z axis keeps crashing. X and Y axis homing works fine. Any Ideas what to do?

Same issue with Marlin 1.1.9

Thanks for your help!

**Comment by tonokip** [comment]
In pins_EINSY_RAMBO.h on line 70 replace:
#define Z_STOP_PIN     10

with:
#define Z_STOP_PIN     Z_DIAG_PIN

**Comment by grieml** [comment]
it worked! Thank you very much - saved me a lot of time!

**Comment by thinkyhead** [comment]
@tonokip — Do you recommend that as a permanent change to the pins file?

**Comment by boelle** [comment]
@tonokip what thinky said ^^^

@grieml is this still a problem when using latest bugfix 2.0?

**Comment by boelle** [comment]
@Thinkyhead i think we can close this one
