### ISSUE TITLE
SanityCheck.h:352:6: error: #error "BLUETOOTH is only supported with AT90USB."

### ISSUE THREAD

**Issue by sandeepdohare** [MarlinFirmware/Marlin#11820]
[config.zip](https://github.com/MarlinFirmware/Marlin/files/2377845/config.zip)

Hi
I tried uploading new Marlin firmware 1.1.9 , for which i have updated the configuration.h file , with latest arduino ide when i tried compiling the firmware i faced a compilation error .Since i don't know the programming language .I couldn't figure out what the issue ,This might be very stupid issue , Kindly guide me to resolve the issue.

Expected behavior : compilation should not have much problem

It showed the error as mentioned below 
```
 [In file included from C:\Users\OPTIMUS\AppData\Local\Temp\arduino_build_740002\sketch\MarlinConfig.h:42:0,

                 from C:\Users\OPTIMUS\AppData\Local\Temp\arduino_build_740002\sketch\G26_Mesh_Validation_Tool.cpp:27:

SanityCheck.h:352:6: error: #error "BLUETOOTH is only supported with AT90USB."

     #error "BLUETOOTH is only supported with AT90USB."

      ^

exit status 1
#error "BLUETOOTH is only supported with AT90USB."]
```

**Comment by MrAlvin** [comment]
In your configuration.h, check to see if  it has: 
#define BLUETOOTH

If it does, change it to: 
//#define BLUETOOTH

Edit: Oh, I see that you have included a copy of you configuration.h. 
and indeed, it does contain: 
#define BLUETOOTH

Change that to: 
//#define BLUETOOTH

**Comment by sandeepdohare** [comment]
Thanks, Mr Alvin for your help... Finally uploaded the firmware and it's working...
