### ISSUE TITLE
Ender 3/Cura bug/issue

### ISSUE THREAD

**Issue by Gazza-USA** [MarlinFirmware/Marlin#11829]
[TH3DUF_R2_configH.zip](https://github.com/MarlinFirmware/Marlin/files/2384987/TH3DUF_R2_configH.zip)

I have recently updated my Ender 3 to the latest Firmware using UNIFIED_VERSION "TH3D U1.R2.1d".

I have noticed that as the nozzle and bed temperatures heat up that it is now not reported in Cura during the initialization phase (previous version V1.0.03 ? - Factory default woul dreport this every second or so) .   I assume this is due to the new PID loop not reporting the result until it is finished it's PID desired value.

I have tried issuing an Auto Report Temperature M155 S1 and this has not helped.

Thanks.

**Comment by thinkyhead** [comment]
Marlin sends the temperature report to the host at one second intervals during `M109` / `M190`.

Anyway, we can't support third-party forks of Marlin. You will need to post an issue at https://github.com/houseofbugs/TH3D-Unified-U1.R2/issues if you're having an issue with TH3D's pre-configured Marlin.
