### ISSUE TITLE
Unknown command: "G30 X110 Y110"

### ISSUE THREAD

**Issue by arteck** [MarlinFirmware/Marlin#11824]
last version from Git 1.1.9 Standard Printer Standard Anet A8, Sensor ROKO SN04-N 

what i do 
```
G28 ; home all
G1 X110 Y110 ; move nozzle in center
M211 S0 ; disable software endstop
; now move your nozzle manually onto the bed such that it (strongly) grips paper.
G92 Z0 ; tell the printer that this is Z = 0
G30 X110 Y110 ; move the sensor over the center and let it trigger
```

and here is end

```
Recv:  T:21.50 /0.00 B:22.00 /0.00 @:0 B@:0
Send: G30 X110 Y110Recv: echo:Unknown command: "G30 X110 Y110"
Recv: okRecv:  T:21.50 /0.00 B:22.00 /0.00 @:0 B@:0
```

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2380780/Configuration.txt)

**Comment by MrAlvin** [comment]
It would seem that the G30 command is only compiled into the firmware, if a probe has been enabled 

These probe types, should include the G30 code in the firmware
FIX_MOUNTED_PROBE
Z_PROBE_ALLEN_KEY
HAS_Z_SERVO_PROBE/BLTOUCH
Z_PROBE_SLED
SOLENOID_PROBE

Did you enable one of these probe types in configuration.h? 

Edit: Oh, I see that you have included a copy of your configuration.txt.
Try to enable FIX_MOUNTED_PROBE
And then try the G30 command again

**Comment by arteck** [comment]
that's it
