### ISSUE TITLE
TMC2130 configuration

### ISSUE THREAD

**Issue by Yoonutz** [MarlinFirmware/Marlin#11834]
Hello everyone,
I am currently building my printer and I want to have it on TMC2130 drivers. I followed this tutorial https://www.youtube.com/watch?v=AVHVCPcFHUs&t=216s letter by letter and the values I get at M122 are 0:00:00:00:00 on all drivers. I have reconfigured everything from scratch and still got these values. Please tell me what informations you need more in order to help me solve this problem. Thank you

**Comment by teemuatlut** [comment]
See this first http://marlinfw.org/docs/hardware/tmc_drivers.html#troubleshooting

**Comment by pipersw** [comment]
Did you have connected the 12V power supply ? the registers are not read until 12V is powered.

**Comment by boelle** [comment]
@Yoonutz 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
