### ISSUE TITLE
Marlin 2.0 MKS Sbase v1.3 with Plataform.io

### ISSUE THREAD

**Issue by oriaj3** [MarlinFirmware/Marlin#11836]
### Steps to Reproduce

1. Open Plataform.io and Marlin 2.0.
2. Choose in platformio.ini "env_default = LPC1768"
3. Choose in configuration.h "  #define MOTHERBOARD BOARD_MKS_SBASE"
4. Compile. 

**Expected behavior:** Compile marlin for mks sbase v1.3. 

**Actual behavior:** 
When I'm going to compile marlin for LPC1768 with Plataform.io I get the following:

> Marlin\src\module\stepper_indirection.cpp: In function 'void reset_stepper_drivers()':
> Marlin\src\module\stepper_indirection.cpp:585:11: error: 'static void Stepper::set_directions()' is private within this
>  context
> stepper.set_directions();
> ^~~~~~~~~~~~~~
> In file included from Marlin\src\module\stepper_indirection.cpp:38:0:
> Marlin\src\module\../module/stepper.h:475:17: note: declared private here
> static void set_directions();
> ^~~~~~~~~~~~~~
> Marlin\src\module\stepper_indirection.cpp:585:26: error: 'static void Stepper::set_directions()' is private within this
>  context
> stepper.set_directions();
> ^
> In file included from Marlin\src\module\stepper_indirection.cpp:38:0:
> Marlin\src\module\../module/stepper.h:475:17: note: declared private here
> static void set_directions();
> ^~~~~~~~~~~~~~
> Compiling .pioenvs\LPC1768\libc60\CMSIS\LPC1768\driver\lpc17xx_emac.o
> *** [.pioenvs\LPC1768\src\src\module\stepper_indirection.o] Error 1
> Compiling .pioenvs\LPC1768\libc60\CMSIS\LPC1768\driver\lpc17xx_exti.o
>  [ERROR] Took 5.34 seconds

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by brandstaetter** [comment]
see #11833 - this should fix it

**Comment by oriaj3** [comment]
I have solved it by adding the following to the stepper.h file:

>   // Allow reset_stepper_drivers to access the internal set_directions method.
   friend void reset_stepper_drivers();
