### ISSUE TITLE
Heated Bed wont turn on after Autotune if PIDTEMPBED is enabled.

### ISSUE THREAD

**Issue by MotoGP1199** [MarlinFirmware/Marlin#11840]
So I've used Auto Tune multiple times without issue.  I went to do auto tune on my heated bed and it wouldn't work.  I Then enabled "#define PIDTEMPBED".   Went trough the process of M303 and placed the values in my configuration.h.   After the upload when I start up my printer the heater gets halted and will not heat up at all.  If I disable PIDTEMPBED then the heater works again.   Not sure what to do.  Attached are my files.

Edit to add:  The values I received from the bed autotune were
```cpp
  //Tevo Tornado w/ Mirror
  #define DEFAULT_bedKp 136.93
  #define DEFAULT_bedKi 23.54
  #define DEFAULT_bedKd 199.10
```

MKS Gen L V1.0 Board.
Marlin 1.1.9
Tevo Tornado
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2386292/Marlin.zip)

**Comment by MotoGP1199** [comment]
Also is there a G-Code that will take Marlin back to the main Info Screen.  I would like to add it after my custom commands so I don't have to back out of every menu.  Thanks.

**Comment by Looxoor** [comment]
Stupid question, but have you tried M502/M500?
Just to ensure there aren't any EEPROM conflicts.

**Comment by vinivinilos** [comment]
Hi! I got exactly the same problem. I hardcoded my PID values and flashed the firmware but still doesn't work. With Marlin 1.1.8 everything works well.

**Comment by MotoGP1199** [comment]
Ok So I did the M502/M500 and now it is heating up the bed just fine.  I usually do that every time, not sure why I didn't.  But now that I entered in my new probe offsets (new hot end) and it will not auto level or even auto home.  It will home X and Y but not Z.  If I change X offset to a negative value it will auto home and allow Z to auto level.  If I keep the X offset as a positive number (my probe is now on the right of the nozzle, It will Home X and Y and then when it goes to home Z it roughly centers the probe on the bed, acts if it is going to lower and then displays "STOPPED" in the messages.

Only settings changed are these.  And I have been making sure to do M500/M502 now.
```cpp
#define X_PROBE_OFFSET_FROM_EXTRUDER 48  // X offset: -left  +right  [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER -2  // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER -0.755   // Z offset: -below +above  [the nozzle]
```
I moved my probe (BLTouch) from the left side of the nozzle to the right due to new hotend/fan setup.

**Comment by MotoGP1199** [comment]
Ok I got the bed leveling to work.  The firmware I had used to compile had bed leveling and BLtouch already set up.  However they never defined the boundaries for the probe only the probe offset.  For some reason it doesn't care if you have the probe on the left with these not configured but if you have the probe on the right and don't configure the boundaries it will start a regular Z home then pause with confusion and just say STOPPED with no other explanation.

**Comment by thinkyhead** [comment]
> if you have the probe on the right and don't configure the boundaries it will start a regular Z home then pause with confusion and just say STOPPED 

If you see this again, check the serial output. It should include more detail about the cause.
