### ISSUE TITLE
[2.0 bugfix] LPC1768 Re-Arm USB Serial triggers watchdog 

### ISSUE THREAD

**Issue by oakdesign** [MarlinFirmware/Marlin#11842]
### Description

On a fresh install of bugfix-2.0 on Re-Arm board. Default config 
only with Motherboard setup
define MOTHERBOARD BOARD_RAMPS_14_RE_ARM_EFB
and 
define SERIAL_PORT -1
USB Serial connection is only working for the first 30-60 seconds after reset. For Detailed description see Additional Information with screenshots below
### Steps to Reproduce

1. Build bugfix-2.0 for LPC1768
2. Load to SD Card
3. Reset Re-Arm. Firmware.bin is flashed Firmware.CUR with recent timestamp is present.
4. Connect through Host software immediatly after reset.
5. Issue GCode Commands M502, M500, M501 works (eeprom.dat beeing generated)
6. Wait for 30-60 seconds
7. Device Manager refreshes SD Card appears on file Explorer
8. Retry Gcode Commands
9. watchdog seem to have triggered, board halted

behavior has been reproduced on 3 different Machines Win7 64bit, 8,1, 10 with different Host software Repetier Host, Pronterface and Visual Stucio Code Platforio Serial Monitor.

Reflashing smoothiware o Re-Arm runs stable without any board crashes

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information
After loading firmware.bin file form and reset Device Manager shows Marlin USB Serial
![boot1](https://user-images.githubusercontent.com/1496441/45594844-d5a47c00-b9a1-11e8-8b48-8aa4ecb557f8.JPG)
Host software can connect to board and GCode command can be issued. At that time SD is not showing up as Device in File Explorer
![boot4](https://user-images.githubusercontent.com/1496441/45594854-f2d94a80-b9a1-11e8-85d9-4712abb8ffad.JPG)
After 30-60 Seconds device Manager refreshes and SD Card shows up in File Explorer
![boot2](https://user-images.githubusercontent.com/1496441/45594852-e94fe280-b9a1-11e8-8a43-f346c60fa1aa.JPG)
Host connection now fails with timeout
![boot5](https://user-images.githubusercontent.com/1496441/45594857-f79dfe80-b9a1-11e8-8984-a3ec27aadb2d.JPG)
Marlin USB Serial is dropped and Smoothie shows up in device manager
![boot6](https://user-images.githubusercontent.com/1496441/45594858-fb318580-b9a1-11e8-966b-fe73e2407486.JPG)

If after boot no immediate connetion on USB is beeing established and waiting untilSD show up in File Explorer no serial connection through host can be established as COM port not found error. Even so at that time the Marlin Serial USB still shows up in the device manager
![boot3](https://user-images.githubusercontent.com/1496441/45594853-eead2d00-b9a1-11e8-8460-995a2321c6f6.JPG)

[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/2386442/Configuration.h.txt)

**Comment by p3p** [comment]
We are working on stabilising the USB, some people do seem to have more problems than others with disconnects, you can try putting `#define FLASH_EEPROM` in your config to enable the flash eeprom emulation instead of sd card file and see if that helps.

**Comment by oakdesign** [comment]
Will try and Report bck

**Comment by oakdesign** [comment]
I merged all commits as of yesterday into my branch, rebuild and reflashed. My issue seems to be fixed. 
USB Serial seems to b e stable and survives the boot up. So without haven further analyzed the commits since my last build yesterday I now doubt that is was the serial itself causing the trouble. One of the commits must have fixed an issue that on the one hand didn't affect compiling but cuased to crash on runtime. 

Will close this one for now
