### ISSUE TITLE
Code Sprints Anyone?

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#1184]
One way to push through lots of extant issues and pull requests is by setting milestones and doing periodic code sprints. Marlin is now developed by a large enough group that it seems like this could be doable. Initial sprints would focus on integrating support for printers already in the pull request queue, then feature or improvement milestones can be set later on. There might even be enough developers here in my city (Seattle) that we could do some coding sessions in person.

Then Marlin can start getting some version tags, and we could even start a 2.0 branch that brings more beauty to the code and lets the C++ optimizer do the work of pruning unused root methods, etc. It would be good to start dealing with things like configs, "lcd_implementation" headers, pins.h, language.h, and other files that are becoming unwieldy.

Obviously such big change is hard to make in the active release branch, but a 2.x branch would allow for some more serious reform. Where the planner is already optimal we don't need to mess around, but the less important and less-often-executed portions of the codebase can benefit from leveraging C++ and would make it cleaner and more consolidated to add new hardware, language, and feature support.

**Comment by stv0g** [comment]
Nice idea, I'm in.

We should find some convenient way to communicate: IRC, MailingList? Ideas?

**Comment by boelle** [comment]
or here?

Den tirsdag den 6. januar 2015 skrev Steffen Vogel <notifications@github.com

**Comment by boelle** [comment]
hmmm... looking at a irc channel

#marlin-firmware
#marlin

both are free.... other ideas?

**Comment by boelle** [comment]
for now #marlin-firmware it is

**Comment by thinkyhead** [comment]
@stv0g Well, the real purpose of a sprint is to identify one or two issues, and then gather resources to focus on those. Sometimes it means fixing a broken feature, sometimes it might mean bringing code up to speed with the latest Arduino libraries, or we may identify core problems, such as managing I2C communication with dumbed-down thermocouples. Or, just pick some of the trickier issues in the queue and bang on them semi-collaboratively for a period of time.

@boelle [Milestone Bug Fixing Round #2](https://github.com/MarlinFirmware/Marlin/milestones/Bug%20Fixing%20Round%202) is cleared already, and there are only a couple of bugfix PRs in the queue. No serious issues that I am aware of today.

I'm contemplating how we can implement a "code freeze" – basically only allowing bug-fix commits for a period of time while deferring new features – and then having a test round before tagging a new version 1.0.3. I'm particularly interested in getting the new tag set before merging #1456 particularly, since this is a relatively major change – not that we've shied away from allowing some less-tested code into Development for the community to debug.

Perhaps it makes sense to start a new branch for this purpose. Then bug-fixes can be applied to a "beta-103" or "rc-103" branch, while still allowing new features to go into the Development branch during the test period. Once the beta branch seems solid, we can add a "1.0.3" tag to the code and move forward to the next set of milestones.

**Comment by boelle** [comment]
i have poked arround a bit and created a new milestone as there where some verified bugs that was not attached to one... dont be scared by the end date... it can be adjusted

as for a new branch... hmmm... i would just jump in version number until we also have the potential bugs sorted... 

say jump to 1.1.0 or 2.0.0 ?

**Comment by CONSULitAS** [comment]
@boelle Hi Bo,

i think it does not make sense to give it a big version jump to something like 2.0, because everybody would think that there is a major work since 1.0.2. At this time i think Marlin ist fast but constantly growing rather than making major steps.

A 2.0 would make sense for example if we support a new hardware platform like 32 bit ARM.

Perhaps it would be best to change the version number to a system like Ubuntu uses. So we would have a **release 2015.03** and everybody knows easily how old his Marlin is. And no discussions anymore if it is worth to make a major release. :-)

Cheers Jochen

**Comment by nophead** [comment]
Yes that is what OpenScad does with versions and it works very well.

**Comment by boelle** [comment]
then i'm in.... whatever keeps the ball rolling

Den fredag den 6. marts 2015 skrev Chris notifications@github.com:

**Comment by CONSULitAS** [comment]
yes, have a look at http://www.openscad.org/downloads.html

They even use yyyy.mm for "stable" releases and yyyy.mm.dd for "development snapshots".

**Comment by boelle** [comment]
where dd is date right?

on work but off in 3.5 hours

should i rename the old releases while at it?

Den fredag den 6. marts 2015 skrev CONSULitAS notifications@github.com:

**Comment by vandarin** [comment]
Don't rename the old releases, that will just cause even more confusion.

**Comment by boelle** [comment]
oki... but did i get the point with dd ?

**Comment by vandarin** [comment]
Yes, mm=month and dd=day, both with leading zeros.

**Comment by boelle** [comment]
so next one would be 2015.mm.dd.... i can work with that....

**Comment by thinkyhead** [comment]
2015.03 could be the next big release if we keep on plugging away!
