### ISSUE TITLE
MarlinFirmware Discord Channel

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#11846]
Here's the MarlinFirmware Discord URL: https://discordapp.com/channels/461605380783472640/461605380783472643

Invite link for the #general channel: https://discord.gg/n5NJ59y

**Comment by pen25** [comment]
getting invalid invite.

**Comment by thinkyhead** [comment]
The previous link expired. I have posted a new one above.

**Comment by alexxy** [comment]
Seems working =)

**Comment by boelle** [comment]
@thinkyhead i made a post yesterday, maybe pin that and close this one?

**Comment by boelle** [comment]
@thinkyhead this should be pinned just like the "The Marlin 2.0 32-bit thread"

**Comment by Silithas** [comment]
Top link is invalid, second small link doesn't do anything.

**Comment by thinkyhead** [comment]
Links both work for me.

**Comment by github051** [comment]
How to upload marlin firmware in to MKS Robin v2.4 board

**Comment by boelle** [comment]
@thinkyhead thinks its wise to disable comments
