### ISSUE TITLE
Dear Marlin professionals , I am almost done but...

### ISSUE THREAD

**Issue by clarakim1** [MarlinFirmware/Marlin#11847]
Dear Marlin Firmware programming professionals,

Recently, my friend updated Marlin Firmware for me and we thought that it was almost done and....there was only one thing remaining to correct but it is out of our control. We already tried various things.

For example, when I try to print a Totoro's body (Japanese animation character), the bottom side is printed perfectly but the y-axis stepping out happened to the upper side.

Basically, I heard that the Y-axis stepping out problems are related to acceleration, Jerk and speed so we tried to fix it. You can see my configuration.h file in this posting.

What could I do to figure it out?

Please, give me your advice.

Hopefully, I would like to use the newest Marlin Firmware 1.1.9 and share with my friends in our 3D printer community. Moreover, I really would like to use LED options in new Firmware, too!

Thank you in advance and have a blessed day. 
Always I appreciate your great concern.

Warmest regards,
Clara Kim

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
