### ISSUE TITLE
Marlin 1.1.9 Auto home G28 failsafe

### ISSUE THREAD

**Issue by Pyriame** [MarlinFirmware/Marlin#11878]
### Description
hi,
I install Marlin 1.1.9 on a CR-10 S4 (400mmx400mmX400mm). 
I run a G28 (auto home) X moves until it stops and Y moves about 10cm and the printer makes a safe. I turn off and turn on the printer. I launch again G28. X moves up to the stop and Y moves about 10cm further and then again safe. I stubborn and I turn back on. New G28 and this time Y moves, meets it stop, Z goes down and the auto home is OK.

Same problem at the end of an impression

### Steps to Reproduce

just launch G28 with big Bed 40cmx40cm 

#### Additional Information

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2399089/Configuration.zip)

**Comment by AnHardt** [comment]
Denoise your Y-endstop.

**Comment by Pyriame** [comment]
my bed does not have time to move to y-endstop
is there an option in Marlin to define a maximum or minimum displacement length that generates failsafe?
Normally there is a displacement that the truck does not meet the Endstop? With the original firmware I had never had this problem

**Comment by thinkyhead** [comment]
When homing the moves towards endstops are done for double the defined width or depth (800mm in your case). If the procedure is stopping early, there's something wrong with your configuration or your hardware. Try enabling `ENDSTOP_NOISE_FILTER` to see if it helps.

**Comment by Pyriame** [comment]
It's OK with this modification.

Thx thx thx
