### ISSUE TITLE
BLTouch returns "triggered" when issuing M119 command and probe up

### ISSUE THREAD

**Issue by noodleboy91** [MarlinFirmware/Marlin#11877]
### Description

Firmware: Marlin 1.1.x
Hardware: Wanhao Duplicator i3 (200x300mm bed), RAMPS 1.4 conversion, BLTouch

**Expected behavior:** I believe that it should be returning z_min as "open" when the probe is stowed (up), and "triggered" when deployed (down) (I may be incorrect on this last part and it may be "open" when deployed as well).

**Actual behavior:** What I am actually seeing, M119 returns (when x and y are against the endstop, and the BLTouch probe is in the air not touching anything and retracted):
```
x_min: open
y_min: open
z_min: triggered 
```
I have tweaked the configuration.h (attached) 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2398896/Configuration.zip)
and made sure that the parameters are set:
```
// Mechanical endstop with COM to ground and NC to Signal uses "false" here (most common setup).
#define X_MIN_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define X_MAX_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define Y_MAX_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define Z_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MIN_PROBE_ENDSTOP_INVERTING false // set to true to invert the logic of the probe.  
```

I am not at home but can provide the Configuration.adv if needed later. I have also checked my wiring and it has good continuity. The sensor was purchased through Amazon (ASIN: B01FFV2TOS) and shipped from 3D Printer Universe, it appears to be genuine and not a "clone" (has QR code and serial). Please advise, thank you.

Just wanted to add, if I unplug the sensor I get "open"

**Comment by AnHardt** [comment]
@thinkyhead 
The added 'comment' on the wiki page for M119 still does not show up for me.

@nexgen91 
If M119 shows triggered for a  BL-Touch (or clone), that's the error state. The triggered *pulse* of a BL-Touch can only be seen at random.
Likely your probe can't completely deploy/extend. Try higher.

**Comment by noodleboy91** [comment]
> Try higher

Thank you, higher what though (sorry Im confused)? my z axis is about 50mm off the bed.

> M119 shows triggered for a BL-Touch (or clone), that's the error state

I would like to confirm which pins the BL touch connects to are these correct? 
![e807bf22-3da3-11e7-8725-7c05c4844a8d](https://user-images.githubusercontent.com/6373822/45787404-28509300-bc43-11e8-98a8-80373fc755f1.jpg)
Is there a chance that one of my files may be pointing the firmware to look for the probe on different pins? Maybe I need to completely wipe the Arduino and re-upload the code?

**Comment by AnHardt** [comment]
Please study the BL-Touch docu for the reasons of the error state and how to fix, if to fix.

**Comment by noodleboy91** [comment]
> Please study the BL-Touch docu for the reasons of the error state and how to fix, if to fix.

Is that the "manual" located on the Antclabs page? Sorry I am a complete newb to this sensor, and how it is set up and there seems to be a lot of outdated or conflicting information, and documentation that applies to many different models of printer, which is confusing the crap out of me :(

**Comment by thinkyhead** [comment]
Google takes me here: https://www.antclabs.com/manual

**Comment by InsanityAutomation** [comment]
There is a diode on the black and white wires for the probe input. I've seen this when they were backwards. Not a dry contact switch.

**Comment by AnHardt** [comment]
Buying a shi**y product, because of clevver advertisement, results in a bad experience. I hope you learned from that. BL-Touch is wannabe patented, neither the firmware is open, nor the hardware   For that the clones around, if not licenced, can't be really the same. For that, no support by Me. Just disencouraging comments. 

---------
                             1.000.000.000 flies can't fail. Eat more shit.
---------

**Comment by noodleboy91** [comment]
> Buying a shi**y product, because of clevver advertisement, results in a bad experience. I hope you learned from that. BL-Touch is wannabe patented, neither the firmware is open, nor the hardware For that the clones around, if not licenced, can't be really the same. For that, no support by Me. Just disencouraging comments.

So what your saying is I should return this one, which was purchased here: https://www.amazon.com/BLTouch-Leveling-Sensor-Premium-Printer/dp/B01FFV2TOS/ref=sr_1_1?m=A3O53RCZ1OROMM&s=merchant-items&ie=UTF8&qid=1483465267&sr=1-1#feature-bullets-btf (which is linked on Antclabs page) and order from somewhere else? Im even more confused...

**Comment by noodleboy91** [comment]
Going off this chart, and assuming "NOT TRIGGERED" is "open" in repetier-host

STATE---------- | Normal-BLTOUCH----| Fake-BLTOUCH
RETRACTED----| NOT TRIGGERED------| TRIGGERED
EXTRACTED----| NOT TRIGGERED------| NOT TRIGGERED
TOUCH PLANE-| TRIGGERED------------| TRIGGERED
ERROR---------| TRIGGERED-------------| NOTHING

I am getting "open" during error mode, so I am assuming this is not a fake, but some other issue. I am going to try to put in the below code I found here: https://github.com/MarlinFirmware/Marlin/issues/5817 which is supposed to make the fake one work and see what happens, will report back. If it makes it work, I am going to return it and order from one of the other sources listed on Antclabs instead.

```
    //#define BLTOUCH
    #define Z_ENDSTOP_SERVO_NR 0
    #define Z_SERVO_ANGLES {10,90} // Z Servo Deploy and Stow angles
    #define NUM_SERVOS 1
    #define SERVO_DELAY 750  // milliseconds 500 is marginal
    #define Z_MIN_PROBE_ENDSTOP_INVERTING true
    #define Z_MIN_PROBE_ENDSTOP
```

**Comment by tcm0116** [comment]
> So what your saying is I should return this one

No. He apparently doesn't like the BLTouch and has decided to promote his opinion rather than provide any useful guidance. 

Have you checked to make sure the white and black wires aren't swapped? That can cause issues.

**Comment by noodleboy91** [comment]
> > So what your saying is I should return this one
> 
> No. He apparently doesn't like the BLTouch and has decided to promote his opinion rather than provide any useful guidance.
> 
> Have you checked to make sure the white and black wires aren't swapped? That can cause issues.

Gotcha :) Thank you, I have checked them, and swapped them and got the same output, hooking up one of the wires at a time (reveresed) or un-hooking them completely results in "open".

**Comment by noodleboy91** [comment]
> There is a diode on the black and white wires for the probe input. I've seen this when they were backwards. Not a dry contact switch.

I thought that was just on the older version. My'n says "SMART V2.0" below the serial number, which is to the right of the QR code, it also says "MADE IN KOREA" "ANTCLABS" and "BLTouch" placed around the PCB, everything is telling me the thing is not a clone, is there somewhere to put in the serial and have it verified (I know I have had this on 18650 batteries before). I found this: http://id2db.com/genuine.php and it says it is genuine and give me a date of manufacture (2018-07-18), I also email Antclabs. Maybe my probe is messed up somehow?

**Comment by InsanityAutomation** [comment]
I've bought at least half a dozen from the exact same Amazon listing, and they've all worked fine. Can compare to my config here if you want - https://github.com/InsanityAutomation/Marlin/tree/Creality_Marlin2.0.x?files=1

**Comment by noodleboy91** [comment]
> I've bought at least half a dozen from the exact same Amazon listing, and they've all worked fine. Can compare to my config here if you want - https://github.com/InsanityAutomation/Marlin/tree/Creality_Marlin2.0.x?files=1

Thank you for the reply, it looks like your Configuration.h is written different than the format I am used to seeing, not sure if that is a new version of Marlin or that is how the firmware has to be written for the Creality?

**Comment by noodleboy91** [comment]
From the looks of it, maybe I recevied a bad sensor :(

**Comment by InsanityAutomation** [comment]
It's written for 2.0 - the 1.1.9 version is here - https://github.com/InsanityAutomation/Marlin/tree/TM_CR10?files=1 - also it's setup to allow a non technical person to select machine options up top.

**Comment by noodleboy91** [comment]
> 
> 
> It's written for 2.0 - the 1.1.9 version is here - https://github.com/InsanityAutomation/Marlin/tree/TM_CR10?files=1 - also it's setup to allow a non technical person to select machine options up top.

Thank you, Im a technician (avionics), but coding is not my strong suite :) so I appreciate that. If it makes any difference, the white wire is reading shorted to ground (with three wire connector plugged in, when 3-wire is disconnected white is not shorted to ground) my power/ground and 3-wire are separate ribbons, and I am reading 111Ohms between the white and black wires, not sure what is normal, but would appreciate it if anyone can measure theirs please. Is there any measurements (ohms, volts, etc) I can take off the RAMPS board on the Z_min pins to ensure there are no issues there?

Ran the test I have seen and here are my results:
```
M119 ; should return OPEN; returned "z_min: TRIGGERED" (25mm up from bed)
(x and y returned open, sitting on the endstops)
Z_MIN_ENDSTOP_INVERTING: set to false
Z_MIN_PROBE_ENDSTOP_INVERTING: set to false
M280 P0 S10 ; should deploy the probe and the orange LED will be OFF: Check
M119 ; should return OPEN: returned "z_min: TRIGGERED"
M280 P0 S90 ; should stow the probe and the orange LED will be ON; Check
M280 P0 S60 ; puts it into the M119 test mode.
The probe should remain stowed and the blue LED should be OFF. If it's ON then the unit needs to be adjusted; Check
M119 ; should return TRIGGERED; returned "z_min: open" (25mm up from bed)
(x and y returned open, sitting on the endstops)
M280 P0 S160 ; returns it to normal operation
M119 ; should return OPEN; returned "z_min: open" (25mm up from bed)
(x and y returned open, sitting on the endstops)
```

My black wire is going to ground and white is going to signal on the z_min endstop header. After completing the steps above I prevented the pin from deploying and still had x y and z return "open". I rest the board and tried the same thing and got the same (all open).

Here are my config files:
Configuration.h - https://pastebin.com/xNvzUPXA
Configuration_adv.h - https://pastebin.com/Lc9hfyUn
Pins.h - https://pastebin.com/uU11PYvG

**Comment by noodleboy91** [comment]
I hooked up my original Z endstop and I am getting "open" when not engaged, and "TRIGGERED" when engaged, so it appears the RAMPS is seeing the change.

**Comment by AnHardt** [comment]
http://marlinfw.org/docs/gcode/M119.html

**Comment by noodleboy91** [comment]
> 
> 
> http://marlinfw.org/docs/gcode/M119.html

There is an error I guess, maybe just a bad probe... Have another on order, we shall see how it goes I guess.

**Comment by noodleboy91** [comment]
Got it working, did not use predefined BLTouch used the following code instead, M43 S says it is BLTouch probe:

```
#define Z_MIN_ENDSTOP_INVERTING false 
#define Z_PROBE_SERVO_NR
#define Z_SERVO_ANGLES { 10, 90 } // Z Servo Deploy and Stow angles
#define NUM_SERVOS 1
#define SERVO_DELAY { 750 }  // milliseconds 500 is marginal
#define Z_MIN_PROBE_ENDSTOP_INVERTING false 
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
```
I have safe homing enabled, and it is working, and I can issue a G28 command, however after I home and issue a G0 Z0 command the nozzle is sitting about 3.4-3.6mm above the bed, I have tried G28 --> G0 Z0 --> Attempt to move Z axis down via LCD and Repetier but it will not let me move the Z axis down below this point (even after issuing M211 S0 to disable software endstops). I have found a work around by changing the Z offset via M851 Z-3.45 command and saveing to firmware, which gets it closer but I would like to know if there is an easier way to do this than shooting in the dark plugging 3.44, 3.45, 3.46, 3.47 etc in as above. I tried the method on Antclabs page Anthony Quayle manual (below), but like I said can not move Z negative.

```
M851 ; note the number
M851 Z0 ; set the offset to zero
G28
G1 Z0
The LCD display should show Z = 0
From the display go to the Menu then Prepare/Move axis/0.1mm/Move Z
Now move the Z axis slowly down until the nozzle is the right distance from the build plate (folded
piece of paper or thin card).*
Note the Z axis value on the display it should be something like -1.5
M851 Z-1.5 ; to set the offset you got in the previous step.
M500 ; Stores the values in EEPROM so that it is not reset when you power the printer off and on.
Thats it  – you are ready to print.
If you find that you need to increase or decrease the gap then do:
M851 Z-1.4 ; this would make the gap bigger or
M851 Z-1.6 ; this would make the gap smaller
M500 ; to save the value to EEPROM
(remember the -1.4, -1.5 and -1.6 are just examples , yours will be different)
```

**Comment by p3p** [comment]
you probably need to set your probe offset
```
#define X_PROBE_OFFSET_FROM_EXTRUDER 10  // X offset: -left  +right  [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER 10  // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER 0   // Z offset: -below +above  [the nozzle]
```

**Comment by noodleboy91** [comment]
> you probably need need to set your probe offset
> 
> ```
> #define X_PROBE_OFFSET_FROM_EXTRUDER 10  // X offset: -left  +right  [of the nozzle]
> #define Y_PROBE_OFFSET_FROM_EXTRUDER 10  // Y offset: -front +behind [the nozzle]
> #define Z_PROBE_OFFSET_FROM_EXTRUDER 0   // Z offset: -below +above  [the nozzle]
> ```

Here are my current settings, however the printer appears to be ignoring the Z value (x and y are very close to perfect), I am using this mount from thingiverse: https://www.thingiverse.com/thing:2394428
Not 100% happy with where it puts the probe, but its what i have at the moment, maybe I will make a new design later.

```
#define X_PROBE_OFFSET_FROM_EXTRUDER 41  // X offset: -left  +right  [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER - 40  // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER 3.5   // Z offset: -below +above  [the nozzle]
 ```

**Comment by p3p** [comment]
> ```#define Z_PROBE_OFFSET_FROM_EXTRUDER 3.5   // Z offset: -below +above  [the nozzle]```

should this be negative? the probe has to hit the bed to trigger so it's below the nozzle.

**Comment by noodleboy91** [comment]
> > `#define Z_PROBE_OFFSET_FROM_EXTRUDER 3.5 // Z offset: -below +above [the nozzle]`
> 
> should this be negative? the probe has to hit the bed to trigger so it's below the nozzle.

I was wondering the same thing :) can anyone confirm this? I will give it a try and see what happens when I get a chance. That might be my problem, I was thinking the probe retracted,went here not deployed, that would make sense.

**Comment by noodleboy91** [comment]
Tried a negative offset (even tried -10) and it is still sitting about 4-6mm high.

**Comment by thinkyhead** [comment]
> can anyone confirm this?

Yes. Unless your nozzle IS the probe, the `Z_PROBE_OFFSET_FROM_EXTRUDER` should always be negative.

**Comment by boelle** [comment]
@nexgen91 is this still an issue with latest bugfix 2.0?

**Comment by noodleboy91** [comment]
> 
> 
> @nexgen91 is this still an issue with latest bugfix 2.0?

I am not sure sorry, I am still on Marlin 1.1 my printer has been working ok with the configuration I created, so I have not tried anything else 🙂

**Comment by boelle** [comment]
oki, you prob know this but 2.0 is both 32 bit and 8 bit :-D
