### ISSUE TITLE
[Bugfix-2.0.x] Error:EEPROM datasize error.

### ISSUE THREAD

**Issue by Ludy87** [MarlinFirmware/Marlin#11883]
### Description

I flash Marlin new for update from 1.1.9 to Bugfix-2.0.x and i see EEPROM ERROR.

Result from `#define DEBUG_EEPROM_READWRITE`

	echo:Marlin bugfix-2.0.x
	echo: Last Updated: 2018-01-20 | Author: (none, default config)
	echo:Compiled: Sep 20 2018
	echo: Free Memory: 2675  PlannerBufferBytes: 1472
	Error:Field lcd_preheat_hotend_temp mismatch.
	[ERROR] Error:Field lcd_preheat_hotend_temp mismatch.

	Error:EEPROM datasize error.
	[ERROR] Error:EEPROM datasize error.

	echo:Index: 581 Size: 593
	echo:Hardcoded Default Settings Loaded

**Comment by Looxoor** [comment]
Hi!

Enter M502 followed by M500 to reinitialize the EEPROM with the current settings in your configuration files.

**Comment by Ludy87** [comment]
i tried and the Result is be same

**Comment by seaquest37** [comment]
Hi Ludy87,

I suggest to fix the first error.

Error:Field lcd_preheat_hotend_temp mismatch.
[ERROR] Error:Field lcd_preheat_hotend_temp mismatch.

In the Marlin_main.cpp, we found: 
lcd_preheat_hotend_temp[material] = constrain(v, EXTRUDE_MINTEMP, HEATER_0_MAXTEMP - 15);

Check in the Configuration.h if you have a kind of typo for theses variables like:

EXTRUDE_MINTEMP = 270,5; //instead of 270.5 or 270.; etc..
HEATER_0_MAXTEMP 

I guess this caused the "mismatch" and change the expected size value of the compiled EEPROM.

Let us know.

**Comment by cjsoong** [comment]
@Ludy87 
Do you use z probe servo?
Disable these four items try again! (need to do M502 & M500)
//#define Z_PROBE_SERVO_NR 0
//#define Z_SERVO_ANGLES {170,111}
//#define NUM_SERVOS 1
//#define EDITABLE_SERVO_ANGLES

**Comment by bill-orange** [comment]
This problem seems to keep cropping up.  I had this issue also.  Take a look at closed issue #11699.  the resolution of my problem made absolutely no sense.

Bill

**Comment by Ludy87** [comment]
@seaquest37 No, nothing like that found

@cjsoong this is my problem. Whats is the alternative?

     EDITABLE_SERVO_ANGLES is this Problem

**Comment by cjsoong** [comment]
@Ludy87 
Try my modified version.
I am using it on my machine now.
https://drive.google.com/file/d/1wEF-51bp7OMicY-_3ljFHX5rOZP5Mip2/view?usp=sharing

**Comment by Ludy87** [comment]
Thank you @cjsoong i have this code changed 

    // AUTO_BED_LEVELING_UBL
    //
    bool planner_leveling_active;                         // M420 S  planner.leveling_active
    int8_t ubl_storage_slot;                              // ubl.storage_slot
    
    //
    // SERVO_ANGLES
    //
    //uint16_t servo_angles[NUM_SERVO_PLUGS][2];                 // M281 P L U
    uint16_t servo_angles[NUM_SERVOS][2];                 // M281 P L U

    //
    // DELTA / [XYZ]_DUAL_ENDSTOPS
    //

---
@thinkyhead can it to complications come in?

**Comment by alexxy** [comment]
Seems like same issiu as #11757

**Comment by Ludy87** [comment]
@alexxy i have a problem with NUM_SERVO_PLUGS. I have fixed with NUM_SERVOS

**Comment by Ludy87** [comment]
https://github.com/MarlinFirmware/Marlin/commit/3041f06ad1f00b1895ccedb3a3dcbc32fc01cff9
