### ISSUE TITLE
Error:Printer halted. kill() called! on homing

### ISSUE THREAD

**Issue by Arakahn** [MarlinFirmware/Marlin#11884]
Help!

Every time I try to home any axis (or start a print job for that matter), I get this error when the axis arrives at it's home position. I have no mechanical endstop, using a MKS GEN1.4 board.

Attached here is my config and my printer settings in Repetier Host
![capture](https://user-images.githubusercontent.com/43348379/45835106-1b7d7f00-bcd7-11e8-81bf-72d9c87f58ce.JPG)

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2402358/Configuration.txt)

.

Been banging my head for 2 days trying to get this thing working.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by ejtagle** [comment]
You NEED an endstop !! .. Marlin, as safety measure, if after performing any homing operation does not detect an endstop triggered, will stop the machine.
This is to avoid mechanical damage to the structure of your printer, as there is no way to ensure the homing movement is not forcing or bending any mechanical part, and thus destroying your printer.
There is no workaround, and never will be. Safety first!

**Comment by djice024** [comment]
I have the same problem, only that I do have endstops. As soon as the printer touches one it sends out that error code and stops moving. I have a delta machine. my configuration.h is attached. Why is this? And how can I fix it?
