### ISSUE TITLE
[bugfix-2.0.x] Extruder motor spins with Z

### ISSUE THREAD

**Issue by roguecode** [MarlinFirmware/Marlin#11891]
### Description

Bizarre problem here. 
As soon as I activate MIXING_EXTRUDER (with number of steppers set to 2 or 3), the active extruder spins at the same time as the Z motor.
I thought this was a wiring issue somehow, except:
- It only happens when enabling MIXING_EXTRUDER
- It only spins the activate tool
- It always goes forward, regardless if you move Z up or down
- It DOESN'T spin extruder if the hotend is below EXTRUDE_MINTEMP
- Also doesn't spin unless I have first moved the extruder (i.e. only spins if motor has been activated/enabled)

### Steps to Reproduce

Version: 1.1.x branch and 2.0.x, and the behavior is the same.
Hardware: RUMBA, using all stepper ports

I've been using mixing extruder alright on a different motherboard, so this may be related to the RUMBA? 
I have not changed any files except Configuration.h.

On the off-chance it means anything: I tried changing the RUMBA pins file so that E0 was the E1 pins on the board, and E1 was the E2 pins on the board. Same behavior, not really sure what I expected 🤔

**Comment by roguecode** [comment]
I just tested loading Repetier firmware onto it, and it works correctly. So this does seem like a Marlin issue.

**Comment by thinkyhead** [comment]
Try the latest bugfix branches, which have had some of the mixing extruder code patched in recent days.
