### ISSUE TITLE
TMC 2130 Dual Endstop not Triggering Second X/Y Stepper

### ISSUE THREAD

**Issue by Reaction-Time** [MarlinFirmware/Marlin#11893]
### Description

Dual endstop functionality does not work when using TMC 2130's in the sensorless homing mode.

Currently attempting to get an MPCNC working with automatic squaring, using sensorless homing instead of endstops. _dual X/Y motors are enabled, so is dual endstops for X/Y_. Dual X/Y motors are working correctly, however, when trying to home/square only one TMC will trigger and will stop only one motor. 
 
### Steps to Reproduce

1. Ramps 1.4 with 4 TMC'S 
2. Set up dual X/Y motors 
3. Set up TMC sensorless home settings
4. Enable dual endstop

**Expected behavior:** For both TMC's to trigger when homing 

**Actual behavior:** One TMC (Either X1 or Y1 depending on axes being homed) will trigger, leaving the X2/Y2 motor spinning and hitting the physical machine min.
#### Additional Information

[MPCNC Marlin 1.9.zip](https://github.com/MarlinFirmware/Marlin/files/2407676/MPCNC.Marlin.1.9.zip)

**Comment by teemuatlut** [comment]
I don't think this has been coded yet at this point.
I've been looking more into the whole sensorless homing code and it'll get some updates when I get all the other things done first. I'll see if I can address this issue along the way as well.

**Comment by Reaction-Time** [comment]
Perfect, thank you.

**Comment by mattywillo** [comment]
Should be fixed with #13061

**Comment by boelle** [comment]
@Reaction-Time problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by mattywillo** [comment]
Definitely closable imo, I've been doing the exact use case referenced by the issue (MPCNC with TMC2130s) for the last month with no problems.
