### ISSUE TITLE
[2.0.x] Z doesn't move down after home

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#11894]
I'm facing a very weird issue.

Before home:
    Z moves both directions (ok never goes below 0 but after a rise I can lower)
After home:
    move rise but doesn't lower

Displayed quote increase and decrease correctly, movement is properly loaded into planner (`Planner::_buffer_steps` returns true and `recalculate()` is called) and M119 return all endstop open.

Super weird thing: I loaded new firmware to get this issue but going back with PR it persists.

I'm proceeding to try to understand why planner skip it

Of course M502 and M500 after every time I update firmware

**Comment by AnHardt** [comment]
Try `ENDSTOP_NOISE_FILTER`.

**Comment by GMagician** [comment]
I think I discovered the issue...I left Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN enabled but it shoudn't do anything since I don't have any probe

**Comment by GMagician** [comment]
@AnHardt the issue is not during home. Home is done ok, it is after it I can't move Z anymore down

**Comment by AnHardt** [comment]
`ENDSTOPS_ALWAYS_ON_DEFAULT` ?

**Comment by GMagician** [comment]
No, and using interrupt

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2407948/Marlin.zip)

**Comment by GMagician** [comment]
@AnHardt I can move z up 50mm, then m119 (all open), and then down 10mm.
Everything is ok but it doesn't move down..never..
Now I'm checking inside stepper isr to see why it stop...

Edit: Weird thing is that before home it moves...

**Comment by GMagician** [comment]
added a debug test inside stepper isr just after `endstops.update()` call.
my variable is or'ed with `abort_current_block` and reset on M119 call. No abort so endstops are not cause. Also `set_directions` is called this confirm move is queued

**Comment by GMagician** [comment]
I'm wondering, even if this is not my situation since I have DUAL_Z, if code below
```cpp
    #elif ENABLED(Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN)
      UPDATE_ENDSTOP_BIT(Z, MIN);
    #elif Z_HOME_DIR < 0
      UPDATE_ENDSTOP_BIT(Z, MIN);
    #endif
```

should not be:
```cpp
    #elif BED_HAS_PROBE && ENABLED(Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN)
      UPDATE_ENDSTOP_BIT(Z, MIN);
    #elif Z_HOME_DIR < 0
      UPDATE_ENDSTOP_BIT(Z, MIN);
    #endif
```

**Comment by GMagician** [comment]
@ejtagle I think I've found my issue cause. one question not related in endstop.cpp:
```cpp
  #if ENABLED(ENDSTOP_INTERRUPTS_FEATURE) && ENABLED(ENDSTOP_NOISE_FILTER)
    if (endstop_poll_count) update();
  #elif DISABLED(ENDSTOP_INTERRUPTS_FEATURE) || ENABLED(ENDSTOP_NOISE_FILTER)
    update();
  #endif
```

may not be:
```cpp
  #if ENABLED(ENDSTOP_INTERRUPTS_FEATURE) && ENABLED(ENDSTOP_NOISE_FILTER)
    if (endstop_poll_count) update();
  #elif DISABLED(ENDSTOP_INTERRUPTS_FEATURE)
    update();
  #endif
```

is just short form and act the same

**Comment by GMagician** [comment]
@ejtagle another question:
what is purpose of:
```cpp
  #if DISABLED(ENDSTOP_NOISE_FILTER)
    if (!abort_enabled()) return;
  #endif
```
inside EndStop.update?

I suspect that if endstops are "globally enabled" and filter is not enabled you MISS to update endstops.

sequence example:
Endstops.enable_globally(true);
Endstops.enable(false)
endstops are always enabled but you don't test them

I'll make a PR to solve my problem and I'll do what you will suggest me, so don't post any PR to fix them

**Comment by GMagician** [comment]
@thinkyhead, @AnHardt and @ejtagle I finally discovered what is the real bug but I have some doubt about how to solve it.
What happens in my dual Z dual endstop (but I think this may be a problem for everyone):
Axes do home and once both endstops are detected firmware calls `validate_homing_move` and everything is ok but after that it aligns Z and one of the axis may release the endstop.
~~Interrupts promptly may reset `hit_state` but~~ `live_state` is set because of at least one micro is pressed.
Interrupts are disabled and live_state will never be updated again. M119 will report real input status so when I raise with Z it correctly say "open" but `live_state` tells another story and will block all "towards home" movements.
Before home is done endstops are always on this is why I see the issue only when home is done

What must be done is to clear live_state at home end if and only if endstops are not "continuosly" tested. 
I think that hit_state and live_state should be reset after `validate_homing_move` and not inside.
Any hint?

**Comment by AnHardt** [comment]
Add DELTA style home adjustments in **every** case. Be sure that adjustment is always bigger than home bump mm for that axis. Here set the software endstop limits.

**Comment by GMagician** [comment]
@AnHardt I think I don't understand (it's not the first time I misunderstand you, please be patient). adjustment is to properly align Z dual stepper, value is mechanical dependent and will move only one stepper and may not be bigger than bump.
Don't know what is "DELTA style" since mine is cartesian and I never worked with delta printers

**Comment by AnHardt** [comment]
Deltas do have home adjustments , not only for 1 axis of a pair, but 3 adjustments for all 3 of their axes. If those adjustments are big enough, after homing all hardware endstops are free. This is a requirement for proper working software endstops anyway.

**Comment by GMagician** [comment]
On cartesian I think this is not possible. Home is often done approaching bed, endstop are adjusted to be 'hit at pos 0', can't be lower that bed. Delta homes far from bed and can move far from endstops.
My idea is to remove `hit_on_purpose` call from the position it is now and move it after dual alignment and clear also live_state (when interrupt are enabled and endstop are not always tested).
My problem is with G38. I'm not sure what's its purpose. It seems that it bypass endstops when ENDSTOP_NOISE_FILTER is disabled and Endstop on interrupts are enabled.

Edit: hit_on_purpose is ok and it works. since aligned motor will move in opposite home direction, when just one endstop is released, generated interrupt will detect such direction and will not set hit_state again

**Comment by thinkyhead** [comment]
> after homing all hardware endstops are free

This must also certainly be the case after we lower the nozzle below the "safe height," which is an optional part of `G28` homing. So homing-validation on Delta will have to be ensured to happen only at the points where endstops are known to be triggered.

**EDIT: Re-checked and everything looks ok in this regard.**
