### ISSUE TITLE
ubl anet A8

### ISSUE THREAD

**Issue by manotroll** [MarlinFirmware/Marlin#11890]
is it possible to use ubl in anet a8?
can the data be stored in sd card?

what would be the way to do automatically with 9 points being 3 on each side of the table and 3 on the middle part?

**Comment by thinkyhead** [comment]
> is it possible to use ubl in anet a8?

Yes.

> can the data be stored in sd card?

No. It is stored in EEPROM.

> what would be the way to do automatically with 9 points being 3 on each side of the table and 3 on the middle part?

UBL probes **a regular grid** according to the configured settings:
```cpp
#define UBL_MESH_INSET 0          // Mesh inset margin on print area
#define GRID_MAX_POINTS_X 3       // Don't use more than 15 points per axis, implementation limited.
#define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X
```

For more information: http://marlinfw.org/docs/features/unified_bed_leveling.html

**Comment by pastapojken** [comment]
Unless i'm mistaken(read: enabling it by just uncommenting the ubl define and doing nothing else) the A8 doesn't have enough memory to store Marlin with UBL.
