### ISSUE TITLE
LPC1768 error   set motherboard to an LPC1768 motherboard

### ISSUE THREAD

**Issue by awesomebender** [MarlinFirmware/Marlin#11896]
So I am having a problem  compiling marlin 2.0 using platform.io in atom.io I changed the motherboard to the mks base board and changed the environment to LPC1768 and hit compile and then it had an LPC1768 error I don't know much about programing please help me

Steps to Reproduce

   1 Open Plataform.io and Marlin 2.0.
   2 Choose in platformio.ini "env_default = LPC1768"
   3 Choose in configuration.h " #define MOTHERBOARD BOARD_MKS_SBASE"
   4 Compile.

[Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/2409199/Marlin-bugfix-2.0.x.zip)

**Comment by forkoz** [comment]
It would help to copy and paste the error here.

**Comment by gloomyandy** [comment]
and for you to upload your configuration files.

**Comment by awesomebender** [comment]
I'm having problems copying the error from atom.io

**Comment by thinkyhead** [comment]
Screenshots also work.

**Comment by gauix4** [comment]
you should find that

<img width="1680" alt="capture d ecran 2018-10-27 a 16 45 53" src="https://user-images.githubusercontent.com/23041016/47605549-4d85ad80-da08-11e8-8552-0a2d552aa93a.png">

**Comment by gauix4** [comment]
tutorial video ! :) 
https://www.youtube.com/watch?v=gMPdsBumWCQ

**Comment by boelle** [comment]
@awesomebender problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by PillatV** [comment]
I had the same issue and spend around may be 1h before i got that configuration located in config folder not used. Please use configuration files located in Marlin folder.
