### ISSUE TITLE
ABL problem, left side is always higher than right side.

### ISSUE THREAD

**Issue by hadisalame** [MarlinFirmware/Marlin#11908]
Hi,
I'm facing this problem (attached in picture) from long time, I tried all marlin versions and now I'm using marlin1.1.9.
When the printer takes the measurements for ABL and start printing ALWAYS it doesn't work properly, the left side is higher than right side.

I tried 3point prob, linear, Bilinear and all does the same, I tried a lot of tricks like changing the glass thickness, changing the sensors, changing the homing direction of X and Y axises and so many tests.
I tried servo with endstop sensor, inductive, Bltouch, and now I'm using infrared sensor, I checked the M48 repeatability test for all the sensors and all of them were too accurate.
I searched a lot for a solution and I found that maybe the X-axis is twisted, So I checked it and it is not 

Could any one help me?

![img-20180918-wa0031](https://user-images.githubusercontent.com/7039631/45953747-af22b880-c013-11e8-90a6-01bfdb807564.jpeg)

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/2410805/Configuration_adv.zip)

**Comment by RavenWarrior** [comment]
Could your config think x+ is x- and vice verse?
ie, does it seem to level ok then skew once you try a print?

**Comment by ManuelMcLure** [comment]
> I searched a lot for a solution and I found that maybe the X-axis is twisted, So I checked it and it is not

How exactly did you determine this?

**Comment by Roxy-3D** [comment]
Almost for sure...   you have a small twist in your X Axis.   That causes the probed readings of the bed to be offset different amounts from the nozzle on one side versus the other side.

If you are using a mesh based leveling system (Bi-Linear or UBL) you can ignore it and just edit your mesh points on the right side to be a little bit higher.   (Just do one area an see how that works out for you before doing the whole bed.)

But really....  you are better off fixing the twist in the X Axis and regenerating your mesh.

**Comment by thinkyhead** [comment]
You can confirm that there's a mechanical issue by using `MESH_BED_LEVELING` or `PROBE_MANUALLY`. Since these use the nozzle as the probe they are immune to subtle alignment problems. If you find that you get better results with the manual probing methods, it's a strong demonstration that there's a mechanical issue in need of fixing.

**Comment by razerraz** [comment]
Hi,

Take a look here : 
https://framagit.org/razer/bed_leveling_fix

And in case you're using Octoprint : 
https://framagit.org/razer/Octoprint_ABL_Expert
