### ISSUE TITLE
[1.1.9] Case light doesnt work on MKS GEN L 

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#11901]
LED case lighting doesnt work on the mks gen L board  on the second extruder output (D7) , unless you comment out this line:
#define MOSFET_D_PIN 7 in the pins_mks_gen_L file.
With the line still active, the case light will always turn itself off after about half a  second.

This was unexpected for me, because in the previous releases it did work without having to comment out this line.

**Comment by dough29** [comment]
Why not using any other free pin like 4, 5, 6 ,11 (...) ?

**Comment by thinkyhead** [comment]
@meav33 — Can you please ZIP and attach your `Configuration.h` and `Configuration_adv.h` file so that we can figure out what `MOSFET_D_PIN` is being assigned to? Thanks.

**Comment by thinkyhead** [comment]
@meav33 — First, please check `bugfix-1.1.x` and/or `bugfix-2.0.x` to see if the issue has already been patched. Then, please ZIP up your `Configuration.h` and `Configuration_adv.h` files and drop them in a reply at https://github.com/MarlinFirmware/Marlin/issues/11901 so that we can figure out what `MOSFET_D_PIN` is being assigned to. Thanks.

**Comment by rarincarp** [comment]
Hello. I have a very similar problem I can not enable the fans in the lights tells me to use another pin.
do not offend me but I'm Italian and I understand very little English.
I can not even understand what change I have to do to fix the bug you described
ps
I am writing to you through a translator

[Uploading my.config.rar.zip…]()

please be read I read a lot and I lose so many hours but my language does not help me.

**Comment by rarincarp** [comment]
I could not sleep tonight! the firmware tormented me.
Resolved
it was a bug and not my mistake

**Comment by boelle** [comment]
@meav33 is problem gone in latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
