### ISSUE TITLE
Z axis raises after homing - first layer in air

### ISSUE THREAD

**Issue by welo78** [MarlinFirmware/Marlin#11903]
Hello I seem to have a problem with first layer being in air. 

After homing with G28 and being at X0Y0Z0, the nozzle touches the bed precisely ... the Z axis raises to 0.2 (on display) and should start printing the first layer. However it raises to almost 5mm and start printing mid air.

Idk what changed ... The problem is persistent even after I physically move the endstop lower (using endstop switch on Z) ... then the nozzle digs into the bed at 0,0,0 but the first layer is ok. Bed is not movable up or down... 

Any help or suggestions ?

UPDATE: steps for Z are set correctly. If moved by 10 mm up, it moves by 10mm ... even the prints are OK  but the problem is the "first step" from Z0 to Z0.2 which is more like 5.2mm ... I would move the endstop but my nozzle is in X0Y0 which means it would drill through bed

**Comment by renatocarusos** [comment]
I'm having a similar problem in a delta. it looks like the M851 command is ignored. Following.

**Comment by welo78** [comment]
I fixed the problem by replacing the Z endstop switch. Idk why but it 90 % of the time would rise too much, when I replaced the switch it rises as it should.

**Comment by thinkyhead** [comment]
Probably a noisy switch. When probing, if the Z keeps raising, it's almost always a sign of a switch that is sending a "triggered" signal.
