### ISSUE TITLE
Offset bug, I believe..

### ISSUE THREAD

**Issue by renatocarusos** [MarlinFirmware/Marlin#11911]
### My offset with M851 does not make the nozzle down to the bed.

I have a mini delta with capacitive sensor probe. 

### To Reproduce
In 1.1.9 ;
    bugfix-1.1.x ;
    bugfix-2.0.x ;

1. G33 P1 ;
2. M211 S0 ;
3. Go down until the nozzle touches the bed ;
4. M851 Z-[how much did he come down] ;
5. M211 S1 ;
6. [still with nozzle leaning on the bed] G33 P0 ;
7. G29 ;
8. M500 ;

**I expected** her to make the offset.

**Actual behavior,** it does not descend, it prints at the z-probe level.

Tank you all.

**Comment by GMagician** [comment]
If you try to move up & down Z after G28, it will?
Look at #11894 if you are in the same situation

**Comment by renatocarusos** [comment]
@GMagician 
Yes, normally. Even after this routine, both manual and gcode G0 Z0 move the nozzle to the bed, but when it is to print, it stops at the zprobe level [without offset]. 

My slicer is Simplify3D and the "Update Firmware Configuration" option is not enabled, and also the "Global G-Code Offsets" are naturally zeroed.

Some other clue? Ty.

**Comment by tcm0116** [comment]
You might need to run `G33 P1` instead of `G33 P0` for step 6. Can you give that a try and report back?

**Comment by renatocarusos** [comment]
> You might need to run `G33 P1` instead of `G33 P0` for step 6. Can you give that a try and report back?

![dogma_buddy_christ](https://user-images.githubusercontent.com/39814643/45976639-b4850080-c01d-11e8-80d8-40900204fd47.jpg)

**Comment by renatocarusos** [comment]
Tanks @GMagician @tcm0116 !
