### ISSUE TITLE
[Marlin-1.1.x] ask for help :) i have Question Logo BOOT SCREEN Marlin

### ISSUE THREAD

**Issue by ghostlife300** [MarlinFirmware/Marlin#11910]
Logo BOOT SCREEN Marlin. Can I change or delete it?
URL Imgur question : https://imgur.com/a/hkX0FK5
If possible Where is the file?

**Comment by GMagician** [comment]
Is not possible without coding but I really think that in respect to community it should stay where it is.
If you want you can add your custom logo

**Comment by Palatis** [comment]
it's encouraged that manufactures keeps the official marlin logo, and provide a custom bootscreen.
dig through the example config directory for an example.

you can also customize the other icons (such as the nozzle, heatbed, fan), too.

**Comment by Roxy-3D** [comment]
Seriously????    You come here and say "I want to use your firmware, but I don't want anybody to know I didn't write or maintain it."      

Are you some kind of @$$ hole?
