### ISSUE TITLE
[bugfix-2.0.x] Number has dissappeared from graphical babystepping screen

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#11922]
I flashed marlin 2.0 today and now it only shows the arrows and the nozzle, but no number for the Z offset. It was fine when I flashed 2.0 about 3 days ago.

I am also missing options to adjust acceleration, speed, junction deviation an k-factor during print.

**Comment by BETLOG** [comment]
Confirming; missing digits in "Probe Z Offset".

Also; probably related: https://github.com/MarlinFirmware/Marlin/issues/11757

Send: M500
Recv: echo:Settings Stored (609 bytes; crc 39413)
Recv: Error:EEPROM datasize error.

**Comment by InsanityAutomation** [comment]
Pr #11973 should have fixed this last night. Can you confirm?

**Comment by BETLOG** [comment]
Confirming fixed. (my bad on not checking commit code against what I was using)
Menu screen - Beautiful. Having the digits here is very useful if a little fugly.
Adjustment screen - It was much better with the graphic indicating what meant up and what meant down. The new screen display is a downgrade.
![2018-10-01--23-44-39](https://user-images.githubusercontent.com/12265451/46292326-fdb3f200-c5d3-11e8-93c5-99609383242d.jpg)

edit: using:
```
#define BABYSTEPPING
#if ENABLED(BABYSTEPPING)
  //#define BABYSTEP_XY                     // Also enable X/Y Babystepping. Not supported on DELTA!
  #define BABYSTEP_INVERT_Z false           // Change if Z babysteps should go the other way
  #define BABYSTEP_MULTIPLICATOR  1         // Babysteps are very small. Increase for faster motion.

  //#define DOUBLECLICK_FOR_Z_BABYSTEPPING  // Double-click on the Status Screen for Z Babystepping.
  #if ENABLED(DOUBLECLICK_FOR_Z_BABYSTEPPING)
    #define DOUBLECLICK_MAX_INTERVAL 1250   // Maximum interval between clicks, in milliseconds.
                                            // Note: Extra time may be added to mitigate controller latency.
  #endif

  //#define MOVE_Z_WHEN_IDLE                // Jump to the move Z menu on doubleclick when printer is idle.
  #if ENABLED(MOVE_Z_WHEN_IDLE)
    #define MOVE_Z_IDLE_MULTIPLICATOR 1     // Multiply 1mm by this factor for the move step size.
  #endif

  //#define BABYSTEP_ZPROBE_OFFSET          // Combine M851 Z and Babystepping
  #if ENABLED(BABYSTEP_ZPROBE_OFFSET)
    //#define BABYSTEP_HOTEND_Z_OFFSET      // For multiple hotends, babystep relative Z offsets
    #define BABYSTEP_ZPROBE_GFX_OVERLAY   // Enable graphical overlay on Z-offset editor
  #endif
#endif
```

**Comment by InsanityAutomation** [comment]
In order to get the graphical overlay, you need to enable BABYSTEP_ZPROBE_OFFSET as it is dependent on it.

**Comment by BETLOG** [comment]
facepalm
