### ISSUE TITLE
USEABLE_HARDWARE_PWM(CASE_LIGHT_PIN=5) fails on AVR (Atmega-2560)

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#11924]
@AnHardt @Bob-the-Kuhn       I have a Case Light on Pin 5 of an AtMega-2560.

M43 Reports:
`PIN:   5   Port: E3            CASE_LIGHT_PIN                         Output = 1    TIMER3A    PWM:  -25536    WGM: 0    COM3A: 0    CS: 2    TCCR3A: 0    TCCR3B: 2    TIMSK3: 2   non-standard PWM mode   compare interrupt enabled

The USEABLE_HARDWARE_PWM(5) macro fails if the parameter is 5 on AVR Atmega-2560.   5 is a PWM pin, but right now it can't be used for CASE_LIGHT because something is setup wrong on the pin.

**Comment by thinkyhead** [comment]
Case light has a brightness setting. For PWM it must be on a pin with a free PWM timer. Pin 5 might not be entirely free, as timer 3 belongs to servos. So pin 5 can't be used if there's a `BLTOUCH`.
```cpp
// USEABLE_HARDWARE_PWM leads to…
    #define PWM_CHK_SERVO(p)   (p == 5)  // PWM3A
```
```cpp
SET_OUTPUT(CASE_LIGHT_PIN);
if (USEABLE_HARDWARE_PWM(CASE_LIGHT_PIN))
  analogWrite(CASE_LIGHT_PIN, n10ct);
else {
  const bool s = case_light_on ? !INVERT_CASE_LIGHT : INVERT_CASE_LIGHT;
  WRITE(CASE_LIGHT_PIN, s ? HIGH : LOW);
}
```
```cpp
#if ENABLED(MENU_ITEM_CASE_LIGHT)

  #include "../feature/caselight.h"

  void case_light_menu() {
    START_MENU();
    //
    // ^ Main
    //
    MENU_BACK(MSG_MAIN);
    MENU_ITEM_EDIT_CALLBACK(int8, MSG_CASE_LIGHT_BRIGHTNESS, &case_light_brightness, 0, 255, update_case_light, true);
    MENU_ITEM_EDIT_CALLBACK(bool, MSG_CASE_LIGHT, (bool*)&case_light_on, update_case_light);
    END_MENU();
  }
#endif // MENU_ITEM_CASE_LIGHT
```

**Comment by Roxy-3D** [comment]
Yes...  In the case where the pin get gets setup to use PWM to vary brightness.
But Pin 5 is being claimed to be "non-standard PWM mode".   And it only is 100% on or 100% off.

In other words....   USEABLE_HARDWARE_PWM(CASE_LIGHT_PIN) is returning false.

I was hoping I could tweak one of the settings: TIMER3A PWM: -25536 WGM: 0 COM3A: 0 CS: 2 TCCR3A: 0 TCCR3B: 2 TIMSK3: 2    such that USEABLE_HARDWARE_PWM(CASE_LIGHT_PIN) will return true.

**Comment by thinkyhead** [comment]
If you're not using a `BLTOUCH` and `NUM_SERVOS` is 0 then I believe Timer 3 should be free. But you can try commenting out this line wherever you find it:
```cpp
#define _useTimer3
```
…and this might free up Timer 3.

**Comment by boelle** [comment]
@Roxy-3D should this one still be keept open?

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
