### ISSUE TITLE
[SOLVED] [1.19 bugfix] Compile Error board Anet

### ISSUE THREAD

**Issue by roel8032** [MarlinFirmware/Marlin#11933]
In file; Sd2Card.h line 104:
#define SPI_SCK_PIN SCK_PIN

Error:
Stray '\302' in program.

Does anybody know how to solve?

Arduino IDE version: 1.8.7. Windows.

**Comment by Phr3d13** [comment]
Does it work with arduino ide 1.8.5?

**Comment by roel8032** [comment]
Solved!

Already solved. Removed spaces in the error line. And inserted them aquin. It looks it were SHIFT Spaces. Compiler does not like shift spaces. Error maybe because of inserting code from other text editor.
