### ISSUE TITLE
X driver error detected: overtemperature

### ISSUE THREAD

**Issue by josemsotov** [MarlinFirmware/Marlin#11931]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by Spawn32** [comment]
As it says here:  Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

We don't even know what stepper you have, but sounds like a TMC..

And do you have a Fan over your TMC's, they need it :)
