### ISSUE TITLE
New to auto bed leveling

### ISSUE THREAD

**Issue by N3evin** [MarlinFirmware/Marlin#11935]
Hi everyone! I'm using an Anet A8 and trying to get my auto-bed leveling setup. However, when I enter bed level menu, it just start homing xyz and ask me to begin to probe manually instead of auto-leveling. I am not sure if I am doing it right.

I also tried sending G29, however, it just stops at one corner and only moves to the next point when I called G29 again.

I am new to this and wanted to set up auto-bed leveling.

https://pastebin.com/n7VTyMcN

**Comment by razerraz** [comment]
in your configuration.h

PROBE_MANUALLY is enabled
FIX_MOUNTED_PROBE is disabled
