### ISSUE TITLE
total time of printer life

### ISSUE THREAD

**Issue by morgan-it** [MarlinFirmware/Marlin#1193]
Nice Feature Request:
should be nice to have a counter for total print hours of a printer, it should be displayed in lcd or on serial via an Mcode

**Comment by boelle** [comment]
i cant see this will benefit the greater community.... you should always check your machine manual anyways

**Comment by morgan-it** [comment]
i see that should be interesting to know the total amount of print time, at least to define the correct hoverauled time
what  do you mean for " machine manual" here we are not playng around industrial printers!

**Comment by boelle** [comment]
what i means is that the total print time will not benefit many people

and the only thing i could figure that you can use total print time for is to plan when to do maintenance.. and for that you should always check your machine yourself and not rely on how long the machine have been used

**Comment by thinkyhead** [comment]
At the moment total print time isn't stored anywhere, and Marlin doesn't (by design) write to EEPROM without direct user intervention, plus the EEPROM is cleared on version upgrades. While this isn't a bad idea, unfortunately Marlin isn't quite set up for it yet.
