### ISSUE TITLE
[1.1.9] Negative Y_PROBE_OFFSET_FROM_EXTRUDER, assertion error on compilation

### ISSUE THREAD

**Issue by tsmaa** [MarlinFirmware/Marlin#11945]
### Description

When setting up a 3dtouch in front of the nozzle with negative Z_probe offset, assertion happened on compilation. bugfix branch 1.1.9

### Steps to Reproduce

1. [First Step]
   On 300x300x400 Creality CR-10 Bed dimension with 3dtouch or bltouch,
 (file configuration.h)

   #define X_PROBE_OFFSET_FROM_EXTRUDER 0  // X offset: -left  +right  [of the nozzle]
   #define Y_PROBE_OFFSET_FROM_EXTRUDER -43  // Y offset: -front +behind [the nozzle]

2. [Second Step]
   Assertion error happened from sanitycheck.h
static_assert(BACK_PROBE_BED_POSITION <= MAX_PROBE_Y, "BACK_PROBE_BED_POSITION is outside the probe region.");

**Expected behavior:** 
 no assertion/error on compilation

**Actual behavior:** 
Assertion error

#### Additional Information
This is not a bug fix !!!
The workaround to this issue is: 

Step 1. Place double slash to comment line 949 (sanitycheck.h)
// static_assert(BACK_PROBE_BED_POSITION <= MAX_PROBE_Y, "BACK_PROBE_BED_POSITION is outside the probe region.");

Step 2. Place a double slash to comment line 4995 (marlin_main.cpp)
               !position_is_reachable_by_probe(left_probe_bed_position, front_probe_bed_position)
            || !position_is_reachable_by_probe(right_probe_bed_position, back_probe_bed_position)
          #endif
        ) {
//          return;

WARING !!! Modification on production 3dprinter is at your own risk. double-check offsets and dimensions before compilation !

**Comment by thinkyhead** [comment]
You totally forgot to attach your configurations.

**Comment by tsmaa** [comment]
Configuration files attached for checking.
Have a nice day

**Comment by tsmaa** [comment]
Close this thread, please.
Issue solved on Marlin bugfix 1.1.9 source downloaded on January 7, 2019
How ? i don't know....

Thank you
Have a nice day
