### ISSUE TITLE
How to implement u8g ST7920 for STM32F4?

### ISSUE THREAD

**Issue by mr-miky** [MarlinFirmware/Marlin#11955]
I'm trying to run the display (chipset st7920) directly with a spi hardware (STM32F405) without necessarily doing bitbangig of the pins.

From what I understand I have to define U8G_HAL_LINKS.
I do not understand whether I should include the U8glib library, or U8glib-HAL / U8glib-HAL-dev. 

I tried with the first one, the compilation is successful but the display is completely dead. With the other two the compilation fails with errors that at the moment I do not remember well.

I took a look at the HAL of the LPC1768 and there is u8g_com_HAL_LPC1768_st7920_hw_spi.cpp, I suppose I have to implement something equivalent for STM32F4.

Can someone give me some advice on what I have to actually implement in order not to become crazy?

Thank you

 Marlin 2.0 .x  bugfix update to head ...

**Comment by thinkyhead** [comment]
> I took a look at the HAL of the LPC1768 and there is `u8g_com_HAL_LPC1768_st7920_hw_spi.cpp`, I suppose I have to implement something equivalent for STM32F4.

That's basically it. Start by duplicating the LPC1768 stuff over to the STM32F4 HAL and build on it. You may be able to ask @Bob-the-Kuhn for some additional guidance.

**Comment by mr-miky** [comment]
And again constructor of ug8lib tries to use spi with uninitialized hardware and enters an infinite while () loop after reset.

`while(__HAL_SPI_GET_FLAG(&spiHandle, SPI_FLAG_RXNE) == RESET);`

STM32GENERIC is becoming a nightmare ....

**Comment by thinkyhead** [comment]
Arduino STM32 is now an option.

**Comment by xC0000005** [comment]
STM32 generic doesn't init systick before some constructors without a fix. If you insist on using that core (and my M200 V2 support is currently on it, since i haven't managed to make it work with the official core yet), clone STM32GENERIC from my repo, which at least has that fixed + a few others. The official core is coming along. You can build using the Arduino IDE and edit in PIO/whatever you like.

**Comment by mr-miky** [comment]
Thank you. I do not insist on using STM32Generic but at the moment when I use official STM32 I get some code that does not work on the board I designed.
I added a bit of #ifdef to the marlin code since the serial changes name and something else. The build of the source ends correctly but then nothing works. I do not like the management of pin names in the official version. I have to edit variant.h and variant.cpp, so that PA0 is associated with D0 and then D0 is translated into PA_0 through enumerations and arrays. It seems to me only a waste of resources.

**Comment by jmz52** [comment]
You might want to look at https://github.com/MarlinFirmware/U8glib-HAL/blob/dev/src/clib/u8g_com_stm32duino_hw_spi.cpp
It is an implementation of communication function for MKS Mini 12864 using HW SPI interface (STM32F1/F4 HALs)
It works without U8G_HAL_LINKS.

**Comment by boelle** [comment]
@mr-miky 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
