### ISSUE TITLE
[Bugfix 2.0.x] Build fails with #define BUSY_WHILE_HEATING  commented out   

### ISSUE THREAD

**Issue by mr-miky** [MarlinFirmware/Marlin#11954]
I aligned marlin 2.0 bugfix to the latest version in github and from that moment the compilation fails with:

`../src/module/temperature.cpp:2440:17: error: 'MarlinBusyState' does not name a type
           const MarlinBusyState old_busy_state = gcode.busy_state;
                 ^~~~~~~~~~~~~~~
../src/module/temperature.cpp:2535:28: error: 'old_busy_state' was not declared in this scope
         gcode.busy_state = old_busy_state;`

I noticed that it happens because I have disabled BUSY_WHILE_HEATING

temperature.cpp 19452 of 29/09/18

**Comment by Ludy87** [comment]
Disable HOST_KEEPALIVE_FEATURE and try again

**Comment by mr-miky** [comment]
It compiles correctly but, if I have not misunderstood, this disables all "busy" not only those during warm up

**Comment by Ludy87** [comment]
Edit this File \Marlin\src\module\temperature.cpp

Line 2440

    const GcodeSuite::MarlinBusyState old_busy_state = gcode.busy_state;

Line 2569

    const GcodeSuite::MarlinBusyState old_busy_state = gcode.busy_state;

 try again

**Comment by mr-miky** [comment]
Perfect thank you very much. Now the compilation ends correctly.

**Comment by Ludy87** [comment]
@thinkyhead is this a Bug or a Feature?

**Comment by thinkyhead** [comment]
It's a bug, to be sure. Forgot to test with that option disabled.
