### ISSUE TITLE
Unable to Compile for MKS SBase

### ISSUE THREAD

**Issue by fabemit** [MarlinFirmware/Marlin#11956]
### Description

Unable to compile using Platform IO for the MKS SBASE after updating to the latest version of Marlin 2.0 Bugfix today and also to the latest version of Platform IO. Previously everything was compiling fine.

Marlin 2.0 Bugfix 
Platform IO 1.0.2 Core 3.6.1a4
NXP LPC 3.4.1

Issues

1. E2END error ( Have now defined in pins file - #define E2END 0xFFF )
2. Missing Semi Colon ( M104_M109.cpp Line 93 - set_temp = no_wait_for_cooling || parser.seenval('R'); )

3. arm-none-eabi-g++: fatal error: /Users/~/.platformio/packages/toolchain-gccarmnoneeabi/bin/../l
ib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/lib/nano.specs: attempt to rename spec 'link' to already defined spec 'nano_link'

This last issue i cannot fix myself and to be honest don't know if the previous issues were fixed properly either :-)

**Comment by p3p** [comment]
Always supply your configs as requested in the issue template, 

1. E2END should not be required by Marlin core anymore its been pushed back behind the HAL, are you trying to run the MKS SBASE with a physical EEPROM chip (spi, i2c)?

2. yup it will be fixed soon

3. you can't (shouldn't be able to) be using NXP LPC 3.4.1 as the platformio.ini file specifies (`platform          = nxplpc@<3.4.0`), the linking issue is a known problem with their newer scripts.

**Comment by GMagician** [comment]
@p3p for point 2 there is already a PR to be merged

**Comment by fabemit** [comment]
No problem will remember in future :-)

1. As far as i am aware does the MKS Sbase not use i2c for setting the stepper currents?

2. That's Great :-)

3. Mine just says - platform = nxplpc no mention of version?  think mine must still be an older version of the platformio.ini

**Comment by p3p** [comment]
Can you redownload, you seem to have a corrupt version of Marlin.

**Comment by thinkyhead** [comment]
Built for MKS SBASE earlier today. No issues.

**Comment by boelle** [comment]
@Bobblejot problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
