### ISSUE TITLE
home only on 1 \ 4 of the bed ..  marlin 1.1.9 

### ISSUE THREAD

**Issue by marco1703** [MarlinFirmware/Marlin#11969]
### Description

All that has to do from the home onwards does it in 10 x 10 instead of in the whole surface of the bed ... I try to attach a video

- marlin 1.1.9
- bltouch
- mks 1.4 gen
- bed 220 x 220

**Comment by marco1703** [comment]
![Image](https://i.imgur.com/tdfnJnG.jpg)

**Comment by p3p** [comment]
Always supply your configs as requested in the issue template.

**Comment by marco1703** [comment]
Sorry

Marlin 1.1.9-mks gen 1.4- tmc2100-220x220x240- motor 0,9 deg 1,7 amp

**Comment by p3p** [comment]
> Additional Information
> - Include a ZIP file containing your Configuration.h and Configuration_adv.h files.

We need the configuration files used to build Marlin in order to start to help you.

**Comment by marco1703** [comment]
Ok one moment

**Comment by Roxy-3D** [comment]
> marco1703 commented 2 days ago
> Ok one moment

Two days ago is 'one moment' ?   We'll get back to you in a 'day or two' when we have the configuration files.
