### ISSUE TITLE
White Highlight

### ISSUE THREAD

**Issue by ISAndreiva** [MarlinFirmware/Marlin#11965]
Hello!
I do not know if this is the right place for this but here is my ideea:
On my cr-10 with stock firmware the menus i was hovering was highlighted in white and i would like that in marlin 1.1.9 if posibile.
Thanks!

**Comment by AnHardt** [comment]
Would you please be so kind to read, at least `Configuration.h` and `Configuration_adv.h` completely.
```
  // Enable to save many cycles by drawing a hollow frame on the Info Screen
  #define XYZ_HOLLOW_FRAME

  // Enable to save many cycles by drawing a hollow frame on Menu Screens
  #define MENU_HOLLOW_FRAME
```
