### ISSUE TITLE
Modify FAN SPEED VALUE OF 255 points to 10,000??

### ISSUE THREAD

**Issue by luisluna2** [MarlinFirmware/Marlin#11975]
Hello friends, I have interesting in modify Firmware Marlin for some proposes, my one specific question is:

how can INCREASE THE "255 POINTS" TO for example "10,000 POINTS" IN MARLIN FOR EXTRUDER, BED AND FAN?

**Comment by mr-miky** [comment]
Ten thousand ? Is it a bit like an odometer of a car that counts in centimeters / inches  :-P

**Comment by thinkyhead** [comment]
What is it that you are trying to do? You should explain at length in your native language and let us run it through Google Translate to get a better understanding of your intentions.

**Comment by mr-miky** [comment]
Or it is Italian and meant ten point zero zero zero (in Italian we use the point as a separator for the thousands and the comma for the decimals). It would make sense if intended as a 0-10V control, but this is just my guess.

**Comment by thinkyhead** [comment]
Fans connected to a board might be 5V, 12V, or 24V.

**Comment by mr-miky** [comment]
It is a typical convention for some proportional analog controls 0V = off, 10V full power 5V = half etc etc.
Maybe he has GCODE with 0-10V but I'm still hypothesizing.

**Comment by GMagician** [comment]
It will be better to think about 0-100% and convert it to dac 0-255. This will be voltage independent,
but no host software will use it I suspect.

**Comment by luisluna2** [comment]
Hablo Español, disculpen mi mal inglés, lo que intento hacer es modificar en Marlin el S del ventilador de S0-255 a S0-10,000.

Digamos que sólo quiero cambiar el 255 por el valor 10,000 para alcanzar el 100%

Entonces quedaría así: 

S0 = 0V
S10,000=10V
S5000= 5V

**Comment by thinkyhead** [comment]
Your G-code won't be compatible with any known slicers, but you can accomplish this by altering the code in `GcodeSuite::M106`.
```diff
-   const uint16_t s = parser.ushortval('S', 255);
+   const uint16_t s = map(parser.ushortval('S', 255), 0, 10000, 0, 255);
```
(You won't be allowed to use the comma, as in `S10,000`. You must use `S10000` instead.)

**Comment by thinkyhead** [comment]
Your G-code won't be compatible with any known slicers, but you can accomplish this by altering the code in `GcodeSuite::M106`.
```diff
-   const uint16_t s = parser.ushortval('S', 255);
+   const uint16_t s = map(parser.ushortval('S', 10000), 0, 10000, 0, 255);
```
(You won't be allowed to use the comma, as in `S10,000`. You must use `S10000` instead.)

**Comment by luisluna2** [comment]
@thinkyhead Perfect!, I will Try dear, thank you!

**Comment by luisluna2** [comment]
@thinkyhead Friend, in what file need modify?

**Comment by thinkyhead** [comment]
Come on, surely you know how to copy, paste, and multi-file search to look for the line marked in red above.

**Comment by luisluna2** [comment]
All Marlin's are different, in my case no exist the red line like you was put, but Now I can check M106 Command, exist a similar line. I check in 4 versions of Malin.

Thank you for you Help.

**Comment by thinkyhead** [comment]
It's in the `GcodeSuite::M106` method in Marlin 2.0.x (`M106_M107.cpp`) or the `gcode_M106` function in Marlin 1.1.x (`Marlin_main.cpp`). The line is identical in both.

![image](https://user-images.githubusercontent.com/698003/46423309-e112d980-c6fb-11e8-81fb-e4f41f17485f.png)
