### ISSUE TITLE
[Bugfix-2.0.x]  HAL_STM32/fastio_STM32.h

### ISSUE THREAD

**Issue by mr-miky** [MarlinFirmware/Marlin#11999]
The official STM32duino has support for hardware pwm and only for certain pins so I think it's time to update
I do not know if STM32duino has some define to identify it .

```
#ifdef STM32GENERIC
  #define USEABLE_HARDWARE_PWM(p) true
#else
  #define USEABLE_HARDWARE_PWM(p) digitalPinHasPWM(p)
#endif
```
Serials also change their names from SerialUARTx to Serialx  (STM32Ggeneric , STM32Duino)

**Comment by hasenbanck** [comment]
The STM32 HAL is targeting only the official STM32 core. You can still use the old STM32 cores (F4 and F7) if you need STM32GENERIC support.
