### ISSUE TITLE
[bugfix-2.0.x] Z probe offset menu is empty on RepRapDiscount display

### ISSUE THREAD

**Issue by ikarisan** [MarlinFirmware/Marlin#11991]
After upgrading to the bugfix version of 2018-10-02 ( a3ec805c97262e35894e37c219bde1adfe404210 ) neither the "Tune / Probe Z offset" nor the Configuration/Advanced Settings/Probe Z Offset" menu of my RepRapDiscount display (REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER) shows content. It is just a blank screen. : (

**Comment by thinkyhead** [comment]
Should be working now.
