### ISSUE TITLE
[bugfix-2.0.x] Error:EEPROM datasize error when enabled 2 servos (dondolo + bltouch)

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#12015]
Hi!

I get this error with recent bugfix-2.0.x branch. Configs attached
[config.zip](https://github.com/MarlinFirmware/Marlin/files/2451053/config.zip)

```
Compiled: Oct  5 2018
Free Memory: 2724  PlannerBufferBytes: 1488
Error:EEPROM datasize error.
ttyUSB0 PC> Error:EEPROM datasize error.

Index: 607 Size: 615
Hardcoded Default Settings Loaded

```

**Comment by gloomyandy** [comment]
Have you tried doing an m502 followed by m500 to reset the default values and store them in eeprom. You will often usually to do this when installing a new version of the firmware.

**Comment by alexxy** [comment]
yes. doesnt work for me. actualy it wasfirst thing that i tryed.

**Comment by blairq** [comment]
im getting it too. also the machine started skipping steps and so... already did a m502 and m500. changed z_offset (i use a touch sensor) , saved the changes but they didnt go to the eeprom. 
flashed 2 times. same error.

**Comment by GMagician** [comment]
@alexxy @blairq have you tried with DEBUG_EEPROM_READWRITE and check log

**Comment by blairq** [comment]
no, its related to https://github.com/MarlinFirmware/Marlin/commit/c40ea1f0fd28f421bad4f25b660e2316e4c5f2e6

i changed back #define EEPROM_OFFSET 0 to the original #define EEPROM_OFFSET 100 and everything works fine again. 

had to do a m502 - m500 again

**Comment by mrambossek** [comment]
i can confirm that there seems to be some kind of issue. after upgrading last night, i keep getting
```
Error:EEPROM CRC mismatch - (stored) XXXXX != YYYYY (calculated)!
echo:Hardcoded Default Settings Loaded
```
EDIT: i did M502/M500 .. many times. i am aware of what it does. i still kept getting the crc errors.

i changed EEPROM_OFFSET back to 100 as suggested by https://github.com/MarlinFirmware/Marlin/issues/12015#issuecomment-427486004 and now it seems to work again. so appearently those 100 bytes ARE somehow used? :)

**Comment by alexxy** [comment]
I tryed with DEBUG_EEPROM_READWRITE

```
SENDING:M500
Error:Field lcd_preheat_hotend_temp mismatch.
Error:Field lcd_preheat_hotend_temp mismatch.
```

**Comment by alexxy** [comment]
Actualy error is the same as for #11883 and #11757

**Comment by GMagician** [comment]
@thinkyhead in servo.h there is something not correct I think `extern uint16_t servo_angles[NUM_SERVOS][2];`. Not related with this but may lead to memory corruption since I think it should use `NUM_SERVO_PLUGS`

Edit: Maybe not corruption since NUM_SERVOS should always be bigger but I think not correct anyway
       Also in servo.ccp there is `uint16_t servo_angles[NUM_SERVOS][2];`

Edit2: Ok I don't understand... in eeprom data struct is used `NUM_SERVO_PLUGS` hence this should be used all over the code but this is not true... is it not too weird all this?

**Comment by GMagician** [comment]
@thinkyhead sorry to bother but shouldn't I see `eeprom_index` changed every read/write? I see it is incremented only in `EEPROM_SKIP`

**Comment by alexxy** [comment]
I have NUM_SERVOS  = 2  in Configuration.h 
But may be problem is that i use BLTOUCH? and enabled editable servo angles?

**Comment by alexxy** [comment]
Disableing EDITABLE_SERVO_ANGLES solves issue (so seems like its a root of problem)

**Comment by GMagician** [comment]
@alexxy not sure about problem but I think that this mixing of `NUM_SERVOS` and `NUM_SERVO_PLUGS` on `servo_angles` may lead to some problem...

**Comment by GMagician** [comment]
@alexxy that confirm me that such mix is the issue...

**Comment by alexxy** [comment]
NUM_SERVO_PLUGS not defined in Marlin/src/module/servo.h

**Comment by GMagician** [comment]
@alexxy try replacing `NUM_SERVOS` with `NUM_SERVO_PLUGS` in servo.cpp and servo.h where `servo_angles` are referred

**Comment by GMagician** [comment]
If it will fix I'll post a PR

**Comment by GMagician** [comment]
OT @alexxy your dondolo works fine? I decided to remove it because of too much problem with not in use filament retraction

**Comment by alexxy** [comment]
@GMagician it works. but its hard to calibrate offsets

**Comment by GMagician** [comment]
> 
> 
> @GMagician it works. but its hard to calibrate offsets

Dondolo? or fix? If dondolo is no a problem of offsets. The problem is that the unused filament is not kept in position when head moves. When you come back to such filament you miss material (you have to create a tower but then no benefit from having two nozzles)

**Comment by alexxy** [comment]
Dondolo works.

**Comment by cjsoong** [comment]
@alexxy 
If your problem has not been resolved, you can try my modified version.
No EEprom data size error & M281 can set the servo angle.
https://drive.google.com/file/d/1dixj-e1lBUvuxazjgOgqVz0tbXnl2zKI/view?usp=sharing

**Comment by monterman** [comment]
@alexxy could you help me with my issue.   see here please https://github.com/teemuatlut/Marlin/issues/27

thank you.
