### ISSUE TITLE
[2.0.x] Compile error with SDCARD_SORT_ALPHA

### ISSUE THREAD

**Issue by Ccleorina87** [MarlinFirmware/Marlin#12018]
Error while compile latest Marlin 2.0.x

*** [.pioenvs\megaatmega2560\lib195\libU8glib-HAL_ID1932.a] Error 1

Sorry i have no idea what these error are...

**Comment by Ludy87** [comment]
Your error Message is very small, post the details before this lines.

**Comment by Ccleorina87** [comment]
> Your error Message is very small, post the details before this lines.
```
Compiling .pioenvs\megaatmega2560\FrameworkArduino\wiring_digital.c.o
Compiling .pioenvs\megaatmega2560\FrameworkArduino\wiring_pulse.S.o
Compiling .pioenvs\megaatmega2560\FrameworkArduino\wiring_pulse.c.o
Compiling .pioenvs\megaatmega2560\FrameworkArduino\wiring_shift.c.o
Archiving .pioenvs\megaatmega2560\libFrameworkArduino.a
Archiving .pioenvs\megaatmega2560\lib8ff\libU8glib-HAL_ID1932.a
c:\users\gabriel john\.platformio\packages\toolchain-atmelavr\bin\../lib/gcc/avr/4.9.2/../../../../avr/bin/ar.exe: .pioenvs/megaatmega2560/lib8ff/U8glib-HAL_ID1932/clib/chessengine.c.o: No such file or directory
*** [.pioenvs\megaatmega2560\lib8ff\libU8glib-HAL_ID1932.a] Error 1
WindowsError: [Error 2] The system cannot find the file specified: 'c:\\Users\\Gabriel John\\Desktop\\Marlin 2.0.0x V36\\.pioenvs\\.sconsign.dblite':
File "C:\Users\Gabriel John\.platformio\packages\tool-scons\script\..\engine\SCons\Script\Main.py", line 1346:
_exec_main(parser, values)
File "C:\Users\Gabriel John\.platformio\packages\tool-scons\script\..\engine\SCons\Script\Main.py", line 1309:
_main(parser)
File "C:\Users\Gabriel John\.platformio\packages\tool-scons\script\..\engine\SCons\Script\Main.py", line 1091:
nodes = _build_targets(fs, options, targets, target_top)
File "C:\Users\Gabriel John\.platformio\packages\tool-scons\script\..\engine\SCons\Script\Main.py", line 1283:
jobs.run(postfunc = jobs_postfunc)
File "C:\Users\Gabriel John\.platformio\packages\tool-scons\script\..\engine\SCons\Job.py", line 113:
postfunc()
File "C:\Users\Gabriel John\.platformio\packages\tool-scons\script\..\engine\SCons\Script\Main.py", line 1280:
SCons.SConsign.write()
File "C:\Users\Gabriel John\.platformio\packages\tool-scons\script\..\engine\SCons\SConsign.py", line 109:
syncmethod()
File "C:\Users\Gabriel John\.platformio\packages\tool-scons\script\..\engine\SCons\dblite.py", line 129:
self._os_unlink(self._file_name)
Exception WindowsError: (2, 'The system cannot find the file specified', 'c:\\Users\\Gabriel John\\Desktop\\Marlin 2.0.0x V36\\.pioenvs\\.sconsign.dblite')
in <bound method dblite.__del__ of <SCons.dblite.dblite object at 0x04083510>> ignored
```

**Comment by Ludy87** [comment]
Try "PlatformIO: Clean"

**Comment by Ccleorina87** [comment]
> Try "PlatformIO: Clean"

Not working... i might reinstall vscode again... if it working after that

**Comment by Ccleorina87** [comment]
> Try "PlatformIO: Clean"

Already try it... still the same... reinstall Vscode and platformio still the same... try older backup of Marlin 2.0.x 3 days ago working fine... im lost now... on latest one cant...

**Comment by Ccleorina87** [comment]
> Try "PlatformIO: Clean"

funny things is... disable My Avast Antivirus and its working... now this is wired...

**Comment by Ccleorina87** [comment]
> Try "PlatformIO: Clean"

i found out if i Enable these #define SDCARD_SORT_ALPHA the error comeback

**Comment by thinkyhead** [comment]
You didn't fill out the template and provide all requested items, so we don't have enough information to help. Please ZIP your `Configuration.h` and `Configuration_adv.h` files and attach them to your next post.

**Comment by Ccleorina87** [comment]
> You didn't fill out the template and provide all requested items, so we don't have enough information to help. Please ZIP your `Configuration.h` and `Configuration_adv.h` files and attach them to your next post.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2453502/Marlin.zip)

**Comment by Ccleorina87** [comment]
i jump the gun saying the SDCARD_SORT_ALPHA... it's so random error... i try compile SDCARD_SORT_ALPHA disable again if fail to compile... enable also error... im lost now...

**Comment by thinkyhead** [comment]
I just did a build of the current `bugfix-2.0.x` branch in PlatformIO (VSCode) using your configs (plus random `_Bootscreen.h` and `_Statusscreen.h`) and the build was successful.

**Comment by Ccleorina87** [comment]
![error 1](https://user-images.githubusercontent.com/31613820/46580856-7943f200-ca5f-11e8-8382-91640d7beac6.png)
![error 2](https://user-images.githubusercontent.com/31613820/46580857-7943f200-ca5f-11e8-92f7-b1a97f060c86.png)

I always get these error... sometime it successful... if i try build again get either these 2 error... i already reinstall VSCode and platformIO... i'm lost... My backup firmware 5 days ago build without any error...

**Comment by Ccleorina87** [comment]
> I just did a build of the current `bugfix-2.0.x` branch in PlatformIO (VSCode) using your configs (plus random `_Bootscreen.h` and `_Statusscreen.h`) and the build was successful.

Ok already fix... i close these issue... All run perfectly
