### ISSUE TITLE
dual z endstop offset

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#12014]
have individual offset for dual z endstop been added in one of the many changes to bugfix 2?

**Comment by GMagician** [comment]
as I know..no

**Comment by boelle** [comment]
oh, i will double check that mine is at same level from frame origin

but i can bet my life on it that one was 0.2mm different from the other

of course bed "level" could take care of that but if there was an individual offset for the 2 endstops using the bed level to adjust for that would be avoided and hence less use of the z steppers

**Comment by GMagician** [comment]
maybe I misunderstood you but single offset is enough to align Z motors. Why do you need a second offset? just to raise home?

edit: just 2 endstops and 1 motor or 2 motors?

**Comment by boelle** [comment]
dual z endstops and dual z drivers/chips

**Comment by GMagician** [comment]
Then why do you need 2nd offset? the result wil be a "raised" home or do I miss something?

**Comment by boelle** [comment]
z2 endstop is 0.2mm lower than z1 enstop

**Comment by boelle** [comment]
but the printer thinks they are on same height

**Comment by GMagician** [comment]
You have Z_DUAL_ENDSTOPS_ADJUSTMENT to align them

**Comment by boelle** [comment]
ahh, will give it a look

EDIT... there was no explanation just a standard 0

how does it work?

**Comment by GMagician** [comment]
z moves both to endstops when endstop is reached its related motor is stopped. then raise and repeat the same procedure. At the end depending on sign one axis is raised by that amount

**Comment by boelle** [comment]
i think you misunderstood again

i have dual z endstops and dual z stepper drivers

when i home (to z max) Z goes up, if one side comes first it stops and a bit after the other side stops

BUT what if left endstop is 0.2mm lower than right side endstop? then it will not be level

i need to tell marlin that one side is 0.2mm lower or higher

how do i tell that right side needs to be moved 0.2mm down after homing?

**Comment by boelle** [comment]
ahhhhh found the help text above....  

 * Use X_DUAL_ENDSTOP_ADJUSTMENT to adjust for mechanical imperfection. After homing both motors
 * this offset is applied to the X2 motor. To find the offset home the X axis, and measure the error
 * in X2. Dual endstop offsets can be set at runtime with 'M666 X<offset> Y<offset> Z<offset>'.
 */

**Comment by boelle** [comment]
so i need to change 0 to +0.2mm  as i want Z2 to go 0.2mm up so **it's** at same height as Z1

but i would have liked to move Z1 down 0.2mm instead, is that possible or do i need to change endstops and driver so the side with lowest endstop is Z1 ?

**Comment by GMagician** [comment]
don't remember correctly but +0.2 move up Z1 -0.2 move up Z2 or viceversa

**Comment by GMagician** [comment]
no possibility to move down, just up (opposite home)

**Comment by GMagician** [comment]
you may rise one axis and then paly with MANUAL_Z_HOME_POS to let the system thinks it's up than 0

**Comment by GMagician** [comment]
paly=play

**Comment by GMagician** [comment]
I lost something....M666 seems for delta....do you have a delta or a cartesian?

**Comment by boelle** [comment]
cartesian

**Comment by GMagician** [comment]
forget my last...m666 may let you change offset. 
?_DUAL_ENDSTOPS_ADJUSTMENT is default value for such parameter

**Comment by boelle** [comment]
i guess i just have to play arround with values 0.2 is not much so might use a bigger value to see what happens and then use the correct value

@thinkyhead you might want to add a bit more explanation to the section

**Comment by GMagician** [comment]
Note that since I have home down I talked about my situation. Since your home is up all is negated

**Comment by boelle** [comment]
yep, that is why i said i wanted to play with it and use larger numbers so i can easy see what happen

ie use 1 or 2 mm instead of 0.2mm and then play arround if i need + or - in front of it

but i would still say that a few more words explaining it would be helpfull

**Comment by GMagician** [comment]
> but i would still say that a few more words explaining it would be helpfull

I agree. 

I played the same like you when I activated dual Z

**Comment by thinkyhead** [comment]
The adjustment is always away from the endstop direction. Negative or positive doesn't matter — the absolute value is used. I may add a note to configs about it.

**Comment by GMagician** [comment]
@thinkyhead value is taken as absolute and axis will move away from endstop but sign is used to decided which axis should move. But it's not clear if positive will move Z1 or Z2

**Comment by thinkyhead** [comment]
Oh right, important detail! But if you think about how it works, it's only natural. You don't want to have steppers pushing farther towards either endstop… only away.
