### ISSUE TITLE
ADVANCED_PAUSE_FEATURE issue in version 1.1.9

### ISSUE THREAD

**Issue by Foxbiker** [MarlinFirmware/Marlin#12023]
Hallo,

today I want to make final adjustment of the ADVANCED_PAUSE_FEATURE function on my printer but I found trouble with the parametr FILAMENT_CHANGE_UNLOAD_LENGTH. I can set anything but extruder everytime unload only 100mm of the filament. I try oficial Marlin 1.1.9 and bug fix version but without change. So I would like to ask if somebody not forgot some fix value somevhere in the program.

Best regards

Radek

**Comment by thinkyhead** [comment]
`M502`, `M500`.

**Comment by Foxbiker** [comment]
Thank you, now I undertanding .
