### ISSUE TITLE
Extra G code on "Stop printing" menu item

### ISSUE THREAD

**Issue by gordio** [MarlinFirmware/Marlin#12024]
Is is possible to add extra action (increase Z) on activating "Stop printing" in the menu?
And how if yes?

**Comment by thinkyhead** [comment]
Note that the cancellation of an SD print causes the heaters to be turned off, so take heed of that with your choice of commands to add. Here's an example of the change you might make:
```diff
void loop() {

  for (;;) {

    #if ENABLED(SDSUPPORT)
      card.checkautostart();
    #endif

    #if ENABLED(SDSUPPORT) && ENABLED(ULTIPANEL)
      if (abort_sd_printing) {
        abort_sd_printing = false;
        card.stopSDPrint(
          #if SD_RESORT
            true
          #endif
        );
        clear_command_queue();
+       enqueue_and_echo_commands_P(PSTR("G1 X150 Y290\nM300 S880 P250"));
        quickstop_stepper();
        print_job_timer.stop();
        thermalManager.disable_all_heaters();
        #if FAN_COUNT > 0
          for (uint8_t i = 0; i < FAN_COUNT; i++) fan_speed[i] = 0;
        #endif
        wait_for_heatup = false;
        #if ENABLED(POWER_LOSS_RECOVERY)
          card.removeJobRecoveryFile();
        #endif
      }
    #endif // SDSUPPORT && ULTIPANEL

    if (commands_in_queue < BUFSIZE) get_available_commands();
    advance_command_queue();
    endstops.event_handler();
    idle();
  }
}
```

**Comment by boelle** [comment]
@gordio 
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone
