### ISSUE TITLE
Delta Auto Calibration Question

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#12022]
When doing a G33 to auto calibrate a delta printer, if I got something like:

0.058 std dev

Can I continue doing G33 till I got a better std dev ? Or I need to reset first with M502/M500 before trying to do a G33 again ?

**Comment by thinkyhead** [comment]
AFAIK no `M502`,`M500` is required.

**Comment by tcm0116** [comment]
You can run `G33` again in order to continue to refine the results. If you want to calibrate from scratch, then you'd want to run `M502` before `G33`.

**Comment by LVD-AC** [comment]
You can re-run G33 or do a G33 Fx to force the routine to do x iterations and take the best result.

**Comment by boelle** [comment]
@sergiofagundes 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone
