### ISSUE TITLE
MKS Gen L not recognized

### ISSUE THREAD

**Issue by baharmark** [MarlinFirmware/Marlin#12025]
when pressing verify I get error unknown mother board value set configuration.h.
this is the #define BOARD_MKS_GEN_L         53    // MKS GEN L

**Comment by thinkyhead** [comment]
Make sure your `Configuration.h` says:
```cpp
#define MOTHERBOARD BOARD_MKS_GEN_L
```
…and not something odd like…
```cpp
#define BOARD_MKS_GEN_L
```

**Comment by baharmark** [comment]
ok it just has board because that was in board.h

**Comment by baharmark** [comment]
and did not change.

**Comment by thinkyhead** [comment]
Please ZIP and attach your `Configuration.h` and `Configuration_adv.h` files to your next post.

**Comment by baharmark** [comment]
I made no changes to adv
[Documents.zip](https://github.com/MarlinFirmware/Marlin/files/2453574/Documents.zip)

**Comment by thinkyhead** [comment]
Um… Please try again. Your `Configuration.h` is full of garbage.
![image](https://user-images.githubusercontent.com/698003/46577643-fb291200-c9b0-11e8-9bac-c5dc3e6af8b2.png)

**Comment by baharmark** [comment]
hope this better
[Documents.zip](https://github.com/MarlinFirmware/Marlin/files/2453580/Documents.zip)

**Comment by thinkyhead** [comment]
As already pointed out, your `MOTHERBOARD` definition is wrong. It should be:
```cpp
#define MOTHERBOARD BOARD_MKS_GEN_L
```
…not…
```cpp
#define MOTHERBOARD BOARD_MKS_GEN_L         53    // MKS GEN L
```

**Comment by baharmark** [comment]
thank you that did it.
