### ISSUE TITLE
[Bugfix-2.0.x] EEPROM CRC mismatch after 2 printer reset

### ISSUE THREAD

**Issue by F0x06** [MarlinFirmware/Marlin#12037]
### Description

When i reset my printer 2 times i got `Error:EEPROM CRC mismatch - (stored) 32608 != 3663 (calculated)!`

### Steps to Reproduce

1. Restore fail-safe
2. Configured my printer (Delta calibration etc...)
3. Save settings (M500)
4. Power-off the printer
5. Power-it back on
6. Connect to serial (When connects it restarts the printer, this is the second reset)
Then i got 

PS: If i don't use serial and just power of the printer 2 times i get the same result

```
Connecting...
start
Printer is now online.
echo:Marlin bugfix-2.0.x
echo: Last Updated: 2018-01-20 | Author: @f0x06
echo:Compiled: Oct  8 2018
echo: Free Memory: 3028  PlannerBufferBytes: 1472
Error:EEPROM CRC mismatch - (stored) 364 != 28739 (calculated)!
[ERROR] Error:EEPROM CRC mismatch - (stored) 364 != 28739 (calculated)!
```

**Expected behavior:** Keep my EEPROM settings

**Actual behavior:** EEPROM CRC mismatch and can't recover my settings

#### Additional Information

Version: d5017e2788f042d5b149a1e16dcbdc672d092015
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/2457229/Configs.zip)

**Comment by mrambossek** [comment]
This sounds like the problem I had, see https://github.com/MarlinFirmware/Marlin/issues/12015#issuecomment-427556710

**Comment by F0x06** [comment]
@gmrambossek Thanks for the ref ! :)

**Comment by thinkyhead** [comment]
Uncomment this option in `configuration_store.cpp` and the read/write functions will give us a better indication of which fields in the EEPROM read/write are misbehaving.
```cpp
// Check the integrity of data offsets.
// Can be disabled for production build.
//#define DEBUG_EEPROM_READWRITE
```

**Comment by F0x06** [comment]
@thinkyhead I'll try this when i can, maybe tomorrow 👍
