### ISSUE TITLE
[Bugfix-2.0.x] emergency parser when homing and auto bed leveling - no action

### ISSUE THREAD

**Issue by Ludy87** [MarlinFirmware/Marlin#12031]
I try M112 execute when the printer home (G28) and auto bed leveling (G29).

The printer continues home and auto bed leveling without stopping.

MKS Gen v1.4 with TMC2130

**Comment by AnHardt** [comment]
M112 does work.
But to make it work always, the hosts have to send it even when not having received an 'ok' before and even then, when they think Marlins RX-buffer is full. No known host, except dumb terminal programs, does that.

**Comment by Ludy87** [comment]
I have tested this with pronterface as a terminal

**Comment by thinkyhead** [comment]
No workaround if Marlin hasn't actually received "M112."
