### ISSUE TITLE
[Potential BUG] Error:EEPROM datasize error

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#12048]
decided it was time to update to latest bugfix 2 and i used winmerge to compare the config files so i could port over my old settings

for some reason i cant get it to same to eeprom i get: 

**Error:EEPROM datasize error**

config files attached

using ramps board, dual z endstops and dual z drivers. 

should i clear the eeprom?

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2460644/Configuration.zip)

**Comment by boelle** [comment]
i tried the clear eeprom sketch found within arduino IDE, still the same

right after connect i get:
```
Recv: echo:EEPROM version mismatch (EEPROM= Marlin=V60)
Recv: ok
Send: M501
Recv: echo:EEPROM version mismatch (EEPROM= Marlin=V60)
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
```
so it has to do with version i guess

**Comment by boelle** [comment]
```
Send: M502
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M500
Recv: echo:Settings Stored (629 bytes; crc 63216)
Recv: Error:EEPROM datasize error.
Recv: ok
[...]
```

**Comment by boelle** [comment]
one more odd thing i just noted

i can move Z down, but not up

ie i can home and since i have max z endstops it moves up like it should and does the retouch like with x and y axis

and then i can issue G0 Z1 and it goes down

but if i then issue G0 Z2 it does not move up again

**Comment by boelle** [comment]
corrected some of the travel limits in firmware so nozzle ends up the right place on the bed

right after flashing firmware i get:
```
Send: M504
Recv: Error:EEPROM datasize error.
Recv: echo:Index: 629 Size: 625
Recv: ok
Send: M501
Recv: Error:EEPROM datasize error.
Recv: echo:Index: 629 Size: 625
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
```

**Comment by boelle** [comment]
and when i compile i sometimes get this, and then i just compile again
```
sketch\src\module\temperature.cpp: In function 'print_heaterstates':

sketch\src\module\temperature.cpp:2402:3: internal compiler error: Segmentation fault

   }

   ^

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Users\boher\Desktop\Firmware\Arduino IDE 1.9.0\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/users/boher/desktop/firmware/arduino ide 1.9.0/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
```

**Comment by boelle** [comment]
also the extruder is kind of acting up

will try and load an version from 29/7 with same config

**Comment by Ludy87** [comment]
Try this https://github.com/MarlinFirmware/Marlin/issues/12037#issuecomment-42796525 and write your result

**Comment by boelle** [comment]
will do later

but now trying the version i got 29/7 and at least i can now move z both up and down without any issue

dinner soon and will try #12037 with the version from today once i get back

**Comment by thinkyhead** [comment]
To get more information about where the EEPROM error lies you can enable the `DEBUG_EEPROM_READWRITE` option in `configuration_store.cpp` and re-flash. On `M501` and `M500` this will print a message to the console indicating which field in the EEPROM is the wrong size.

**Comment by boelle** [comment]
will do so in a an hour or so.... just switched to direct drive and dialing that in before i mess more with firmware

but i can say as much the same config with the version from 29/7 works

would it be wise to upload both new and old config files? or does it not matter that much?

**Comment by thinkyhead** [comment]
Regardless of configuration there should be no EEPROM errors.

**Comment by boelle** [comment]
oki, i just thought that it could be nice to compare configs, but then again i have used winmerge to compare the 2 config files so they should be the same

not sure if i get arround to flash the firmware today, its 1am and even the best need some sleep :-D

but it will be the first thing i do in the morning

**Comment by boelle** [comment]
Send: M502
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M500
Recv: Error:Field lcd_preheat_hotend_temp mismatch.
Recv: ok
[...]
Send: M501
Recv: echo:EEPROM version mismatch (EEPROM=ERR Marlin=V60)
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]

**Comment by boelle** [comment]
did an edit above to include M501

**Comment by thinkyhead** [comment]
Change `EEPROM_OFFSET` to 100 and try again. This might fix the issue.

**Comment by boelle** [comment]
also in configuration_store.cpp?

**Comment by thinkyhead** [comment]
Yes. That's where `EEPROM_OFFSET` lives.

Already patched in `bugfix-2.0.x`.

**Comment by boelle** [comment]
oki.. but will try it and confirm first.

**Comment by boelle** [comment]
still getting this at boot/connecting:

Send: M504
Recv: echo:EEPROM version mismatch (EEPROM=ERR Marlin=V60)
Recv: ok
Send: M501
Recv: echo:EEPROM version mismatch (EEPROM=ERR Marlin=V60)
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]

**Comment by boelle** [comment]
when trying to save settings:

Send: M502
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M501
Recv: echo:EEPROM version mismatch (EEPROM=ERR Marlin=V60)
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M500
Recv: Error:Field lcd_preheat_hotend_temp mismatch.
Recv: ok
[...]

**Comment by rmoravcik** [comment]
I just tested https://github.com/MarlinFirmware/Marlin/commit/b2c1cd7eda5aaec3ec9ef5322e9502025ce2a2f2 and it's working fine. The version from 7th of october wasn't working for me too

**Comment by boelle** [comment]
well i will give the lastest bugfix 2 another go tomorrow

**Comment by iamaldovanucci** [comment]
Having the same issue with the MKS SBASE. Seems to be related to the display and or SD Support. All I have to test with is a Full Graphic Display but if I disable the display and SD card EEPROM works fine. This is my first bug report so I'm not entirely sure what else to share. Just did a fresh build of b2c1cd7 in VS Code with platform.io to make sure I didn't goof something up.

**Comment by boelle** [comment]
@iamaldovanucci 

you can be right, see the error i got: Recv: Error:Field lcd_preheat_hotend_temp mismatch.

and in the first post you can see my config, and i too use the full graphic display

tomorrow when i have time i will try and disable the display and see how that goes, but it would then mean i cant use the sd card and i need that

one leasson learned is to have a copy of what used to work :-D

**Comment by JohnnyTheOne** [comment]
I have the same problem

18:52:32.256 : N16 M502*19
18:52:32.256 : echo:Hardcoded Default Settings Loaded
18:52:38.818 : N17 M501*17
18:52:38.818 : Error:EEPROM datasize error.
18:52:38.818 : echo:Index: 537 Size: 569
18:52:38.834 : echo:Hardcoded Default Settings Loaded
18:52:44.850 : N18 M504*27
18:52:44.850 : Error:EEPROM datasize error.
18:52:44.850 : echo:Index: 537 Size: 569


19:04:55.665 : Error:Field parser_volumetric_enabled mismatch.
19:04:55.665 : Error:EEPROM datasize error.

[Configuration.h](https://github.com/JohnnyTheOne/MarlinJTO/blob/JTO-A6/Marlin/Configuration.h)
[Configuration_adv.h](https://github.com/JohnnyTheOne/MarlinJTO/blob/JTO-A6/Marlin/Configuration_adv.h)

**Comment by JohnnyTheOne** [comment]
I have enabled #define NO_VOLUMETRICS and the problem is gone

**Comment by boelle** [comment]
oki, will try this

i totally forgot it as i'm still trying to dial in my printer, but think my part cooling fan duct does not provide enough cooling

will start by downloading a fresh copy and then port over my old settings

**Comment by boelle** [comment]
right out the box i get these compile errors, but i guess those are related to the compiler and not my config. is remember correct @thinkyhead once said that comments after a pin number needs to be removed. will try removing the comment on this one

   #define CONTROLLER_FAN_PIN 4        // Set a custom pin for the controller fan

and #define INVERT_Y_DIR flse needs to be corrected too

```
In file included from c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\hal.h:38:0,

                 from sketch\src\inc/MarlinConfig.h:30,

                 from sketch\src\Marlin.h:25,

                 from sketch\src\Marlin.cpp:31:

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\configuration_adv.h:201:39: error: pasting "/* Set a custom pin for the controller fan*/" and "_DDR" does not give a valid preprocessing token

   #define CONTROLLER_FAN_PIN 4        // Set a custom pin for the controller fan

                                       ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\fastio_AVR.h:84:42: note: in definition of macro '_SET_OUTPUT'

 #define _SET_OUTPUT(IO)       SBI(DIO ## IO ## _DDR, DIO ## IO ## _PIN)

                                          ^

sketch\src\Marlin.cpp:847:5: note: in expansion of macro 'SET_OUTPUT'

     SET_OUTPUT(CONTROLLER_FAN_PIN);

     ^

sketch\src\Marlin.cpp:847:16: note: in expansion of macro 'CONTROLLER_FAN_PIN'

     SET_OUTPUT(CONTROLLER_FAN_PIN);

                ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\configuration_adv.h:201:39: error: pasting "/* Set a custom pin for the controller fan*/" and "_PIN" does not give a valid preprocessing token

   #define CONTROLLER_FAN_PIN 4        // Set a custom pin for the controller fan

                                       ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\fastio_AVR.h:84:61: note: in definition of macro '_SET_OUTPUT'

 #define _SET_OUTPUT(IO)       SBI(DIO ## IO ## _DDR, DIO ## IO ## _PIN)

                                                             ^

sketch\src\Marlin.cpp:847:5: note: in expansion of macro 'SET_OUTPUT'

     SET_OUTPUT(CONTROLLER_FAN_PIN);

     ^

sketch\src\Marlin.cpp:847:16: note: in expansion of macro 'CONTROLLER_FAN_PIN'

     SET_OUTPUT(CONTROLLER_FAN_PIN);

                ^

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
```

**Comment by boelle** [comment]
```










In file included from c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\hal.h:38:0,

                 from c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\inc\marlinconfig.h:30,

                 from sketch\src\module\stepper.h:46,

                 from sketch\src\module\stepper.cpp:80:

sketch\src\module\stepper.cpp: In static member function 'static void Stepper::set_directions()':

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\configuration.h:913:22: error: 'flse' was not declared in this scope

 #define INVERT_Y_DIR flse

                      ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\fastio_AVR.h:69:7: note: in definition of macro '_WRITE_NC'

   if (V) SBI(DIO ## IO ## _WPORT, DIO ## IO ## _PIN); \

       ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\fastio_AVR.h:91:31: note: in expansion of macro '_WRITE'

 #define WRITE(IO,V)           _WRITE(IO,V)

                               ^

sketch\src\module\stepper_indirection.h:149:30: note: in expansion of macro 'WRITE'

   #define Y_DIR_WRITE(STATE) WRITE(Y_DIR_PIN,STATE)

                              ^

sketch\src\module\stepper.cpp:280:28: note: in expansion of macro 'Y_DIR_WRITE'

   #define Y_APPLY_DIR(v,Q) Y_DIR_WRITE(v)

                            ^

sketch\src\module\stepper.cpp:323:7: note: in expansion of macro 'Y_APPLY_DIR'

       A##_APPLY_DIR(INVERT_## A##_DIR, false); \

       ^

sketch\src\module\stepper.cpp:323:21: note: in expansion of macro 'INVERT_Y_DIR'

       A##_APPLY_DIR(INVERT_## A##_DIR, false); \

                     ^

sketch\src\module\stepper.cpp:335:5: note: in expansion of macro 'SET_STEP_DIR'

     SET_STEP_DIR(Y); // B

     ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\configuration.h:913:22: error: 'flse' was not declared in this scope

 #define INVERT_Y_DIR flse

                      ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\fastio_AVR.h:75:7: note: in definition of macro '_WRITE_C'

   if (V) port_bits = ~port_bits;                            /* For setting bits, invert the mask */ \

       ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\fastio_AVR.h:91:31: note: in expansion of macro '_WRITE'

 #define WRITE(IO,V)           _WRITE(IO,V)

                               ^

sketch\src\module\stepper_indirection.h:149:30: note: in expansion of macro 'WRITE'

   #define Y_DIR_WRITE(STATE) WRITE(Y_DIR_PIN,STATE)

                              ^

sketch\src\module\stepper.cpp:280:28: note: in expansion of macro 'Y_DIR_WRITE'

   #define Y_APPLY_DIR(v,Q) Y_DIR_WRITE(v)

                            ^

sketch\src\module\stepper.cpp:323:7: note: in expansion of macro 'Y_APPLY_DIR'

       A##_APPLY_DIR(INVERT_## A##_DIR, false); \

       ^

sketch\src\module\stepper.cpp:323:21: note: in expansion of macro 'INVERT_Y_DIR'

       A##_APPLY_DIR(INVERT_## A##_DIR, false); \

                     ^

sketch\src\module\stepper.cpp:335:5: note: in expansion of macro 'SET_STEP_DIR'

     SET_STEP_DIR(Y); // B

     ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\configuration.h:913:22: error: 'flse' was not declared in this scope

 #define INVERT_Y_DIR flse

                      ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\fastio_AVR.h:69:7: note: in definition of macro '_WRITE_NC'

   if (V) SBI(DIO ## IO ## _WPORT, DIO ## IO ## _PIN); \

       ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\fastio_AVR.h:91:31: note: in expansion of macro '_WRITE'

 #define WRITE(IO,V)           _WRITE(IO,V)

                               ^

sketch\src\module\stepper_indirection.h:149:30: note: in expansion of macro 'WRITE'

   #define Y_DIR_WRITE(STATE) WRITE(Y_DIR_PIN,STATE)

                              ^

sketch\src\module\stepper.cpp:280:28: note: in expansion of macro 'Y_DIR_WRITE'

   #define Y_APPLY_DIR(v,Q) Y_DIR_WRITE(v)

                            ^

sketch\src\module\stepper.cpp:327:7: note: in expansion of macro 'Y_APPLY_DIR'

       A##_APPLY_DIR(!INVERT_## A##_DIR, false); \

       ^

sketch\src\module\stepper.cpp:327:22: note: in expansion of macro 'INVERT_Y_DIR'

       A##_APPLY_DIR(!INVERT_## A##_DIR, false); \

                      ^

sketch\src\module\stepper.cpp:335:5: note: in expansion of macro 'SET_STEP_DIR'

     SET_STEP_DIR(Y); // B

     ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\configuration.h:913:22: error: 'flse' was not declared in this scope

 #define INVERT_Y_DIR flse

                      ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\fastio_AVR.h:75:7: note: in definition of macro '_WRITE_C'

   if (V) port_bits = ~port_bits;                            /* For setting bits, invert the mask */ \

       ^

c:\users\boher\appdata\local\temp\arduino_build_134145\sketch\src\hal\hal_avr\fastio_AVR.h:91:31: note: in expansion of macro '_WRITE'

 #define WRITE(IO,V)           _WRITE(IO,V)

                               ^

sketch\src\module\stepper_indirection.h:149:30: note: in expansion of macro 'WRITE'

   #define Y_DIR_WRITE(STATE) WRITE(Y_DIR_PIN,STATE)

                              ^

sketch\src\module\stepper.cpp:280:28: note: in expansion of macro 'Y_DIR_WRITE'

   #define Y_APPLY_DIR(v,Q) Y_DIR_WRITE(v)

                            ^

sketch\src\module\stepper.cpp:327:7: note: in expansion of macro 'Y_APPLY_DIR'

       A##_APPLY_DIR(!INVERT_## A##_DIR, false); \

       ^

sketch\src\module\stepper.cpp:327:22: note: in expansion of macro 'INVERT_Y_DIR'

       A##_APPLY_DIR(!INVERT_## A##_DIR, false); \

                      ^

sketch\src\module\stepper.cpp:335:5: note: in expansion of macro 'SET_STEP_DIR'

     SET_STEP_DIR(Y); // B

     ^

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
```

**Comment by boelle** [comment]
well it compiles

test print is done in 1½ hours and i can upload after that, hunting down a cooling issue

**Comment by boelle** [comment]
my config just in case it will be needed later on, i have the pins file for ramps included as i have added a dummy stepper and switched arround the thermistor inputs, for some reason they where not the same anymore and i dont want to touch the hardware if i can avoid it

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/2476474/Config.zip)

**Comment by boelle** [comment]
after flash and first boot:

```
Recv: echo:EEPROM version mismatch (EEPROM=V55 Marlin=V61)
Recv: ok
Send: M501
Recv: echo:EEPROM version mismatch (EEPROM=V55 Marlin=V61)
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
```

**Comment by boelle** [comment]
```
Recv: ok
[...]
Send: M502
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M500
Recv: echo:Settings Stored (629 bytes; crc 23185)
Recv: Error:EEPROM datasize error.
Recv: ok
[...]

```

will now try what @JohnnyTheOne suggests

**Comment by Phr3d13** [comment]
I thought the option "Initialize EEPROM" in the LCD menus was for instances such as this?

**Comment by boelle** [comment]
if it was i would think @thinkyhead would have said so

and what if people dont have a LCD?

**Comment by boelle** [comment]
but i'm lucky i have an lcd

but using "Initialize EEPROM" did not change anything

**Comment by boelle** [comment]
upps.... forgot to say that i tried @JohnnyTheOne suggestion and it did not change anything

so my 3 hour old config is still the one i use

**Comment by boelle** [comment]
going back to my copy from 29-7-2018

of course at first boot it complains about eeprom version, but it also shows that current version from today writes eeprom version to the eeprom, but no other errors and it only happens once

```
Send: M504
Recv: echo:EEPROM version mismatch (EEPROM=V61 Marlin=V55)
Recv: ok
Send: M501
Recv: echo:EEPROM version mismatch (EEPROM=V61 Marlin=V55)
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M502
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M500
Recv: echo:Settings Stored (679 bytes; crc 40706)
Recv: ok
[...]
```

**Comment by gloomyandy** [comment]
Did you try enabling DEBUG_EEPROM_READWRITE? It might help to identify what is causing the problem.

**Comment by boelle** [comment]
upps,,,, nope... will do in the morning

**Comment by boelle** [comment]
just before i go to bed, here it is

```
Send: M502
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M500
Recv: Error:Field lcd_preheat_hotend_temp mismatch.
Recv: ok
[...]

```

**Comment by dahuafschmied** [comment]
@boelle did you try my quick bugfix #12112?
for me it fixed the problem. there is one value just before the lcd_preheat_hotend_temp that is not existing but filled with dummy value. so the lcd_preheat_hotend_temp got the dummy value.

**Comment by boelle** [comment]
will try it later today

its mominlaw birthday so will be out most of the day

**Comment by boelle** [comment]
so... downloaded a fresh copy from today and in the process of porting over config

the new section  * Stepper Drivers makes me a bit in doubt if i have done it right 

//#define X_DRIVER_TYPE  DRV8825
//#define Y_DRIVER_TYPE  DRV8825
//#define Z_DRIVER_TYPE  DRV8825
//#define X2_DRIVER_TYPE A4988
//#define Y2_DRIVER_TYPE A4988
//#define Z2_DRIVER_TYPE DRV8825
//#define Z3_DRIVER_TYPE A4988
//#define E0_DRIVER_TYPE DRV8825
//#define E1_DRIVER_TYPE A4988
//#define E2_DRIVER_TYPE A4988
//#define E3_DRIVER_TYPE A4988
//#define E4_DRIVER_TYPE A4988
//#define E5_DRIVER_TYPE A4988

i'm mostly worrid since i have dual z drivers

my config is for 2 extruders but one of them is just "virtual" so i can use that one to display chamber temp on the display, i know there is a chamber temp sensor pin but that one only displays temp on serial data and not in display. it makes it more easy in octoprint too the way i do it

**Comment by boelle** [comment]
of course when compiling ther is still an error due to the compiler does like comments

so in configuration_adv

#define CONTROLLER_FAN_PIN 4        // Set a custom pin for the controller fan

becomes

#define CONTROLLER_FAN_PIN 4

**Comment by boelle** [comment]
still getting errors but not the same as before

```
Recv: Error:EEPROM datasize error.
Recv: echo:Index: 625 Size: 637
Recv: ok
Send: M501
Recv: Error:EEPROM datasize error.
Recv: echo:Index: 625 Size: 637
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M502
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M500
Recv: echo:Settings Stored (625 bytes; crc 28132)
Recv: Error:EEPROM datasize error.
Recv: ok
[...]

```

new zip file attached with configuration.h, configuration_adv.h, configuration_store.cpp and pins_RAMPS.h

and yes DEBUG_EEPROM_READWRITE is enabled :-)

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2496680/configuration.zip)

**Comment by dahuafschmied** [comment]
At your first posts you had a difference of 4 bytes (1x float) that would match to my bug. But now you have a 12 byte difference (3x float). It seams you have a different bug than mine.

**Comment by boelle** [comment]
yeah, i guess i'm lucky that i have an old copy that works so i can print while we figure this one out

but at least i dont have the Error:Field lcd_preheat_hotend_temp mismatch more

**Comment by Ludy87** [comment]
Your Command order is bad.

1. M502
2. M500
3. M501

**Comment by boelle** [comment]
What  order so you suggest ??

**Comment by boelle** [comment]
Same result when order is

M502
M500
M501

```
Send: M502
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M500
Recv: echo:Settings Stored (625 bytes; crc 28132)
Recv: Error:EEPROM datasize error.
Recv: ok
[...]
Send: M501
Recv: Error:EEPROM datasize error.
Recv: echo:Index: 625 Size: 637
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]

```

**Comment by boelle** [comment]
if i disable dual endstop

```
[...]
Send: M502
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M500
Recv: echo:Settings Stored (613 bytes; crc 31850)
Recv: Error:EEPROM datasize error.
Recv: ok
[...]
Send: M501
Recv: Error:EEPROM datasize error.
Recv: echo:Index: 613 Size: 625
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]

```

EDIT: same if also disable dual z drivers

**Comment by dahuafschmied** [comment]
just for test. try to disable AUTO_BED_LEVELING_BILINEAR. it is a default value that is before lcd preheat and has a default value with multi 3x floats. i whish you luck!

**Comment by rmoravcik** [comment]
Hi @boelle, @thinkyhead, I think I found the problem.

If you have a look to the definition of z3_endstop_adj in SettingsDataStruct, z3_endstop_adj defined only if Z_TRIPLE_ENDSTOPS is enabled, but MarlinSettings::save() and MarlinSettings::_load() wanted to write/read dummy also if Z_TRIPLE_ENDSTOPS is disabled.

There is also an problem with definition of toolchange_settings in SettingsDataStruct.

**Comment by boelle** [comment]
i think your idea and #12112 has been merged in

will test later today and hope it works :-)

but this is just part of testing, the more different setups the better

**Comment by boelle** [comment]
i can confirm its fixed

```
Recv: echo:EEPROM version mismatch (EEPROM=V55 Marlin=V62)
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M502
Recv: echo:Hardcoded Default Settings Loaded
Recv: ok
[...]
Send: M500
Recv: echo:Settings Stored (633 bytes; crc 40581)
Recv: ok
[...]
```

**Comment by boelle** [comment]
hmmm

for some reason i cant close my issues or create new ones, any idea why @thinkyhead ?

in any case i hit a new issue where print stops due to the z probe is triggered

since i use the pinda probe on my mendel90 with the mk42 bed there is no way arround this, it will remain triggered until about 1mm up (0,79+)

i have this in configuration_adv.h:

```
// If you want endstops to stay on (by default) even when not homing
// enable this option. Override at any time with M120, M121.
//#define ENDSTOPS_ALWAYS_ON_DEFAULT
```

sine the option is not enabled it should not have the endstops on when homing is done at start of print

a more interesting one:

```
  /**
   * This option allows you to abort SD printing when any endstop is triggered.
   * This feature must be enabled with "M540 S1" or from the LCD menu.
   * To have any effect, endstops must be enabled during SD printing.
   */
  //#define ABORT_ON_ENDSTOP_HIT_FEATURE_ENABLED
```

so since this feature is not  enabled and the other is not i would expect to be clear

but my print is aborted due to a z endstop hit, since my Z endstops are top/max mounted and work fine i would rule them out, the only other endstop is the probe itself

my config is still the same as 3 days ago so they can be found by scrolling up
https://github.com/MarlinFirmware/Marlin/issues/12048#issuecomment-431428871

**Comment by boelle** [comment]
hmmm... its not the same on every print so not sure what is going on

just started an 5 hour test print to dial in my retraction.... got  some of those very fine hair stringing
