### ISSUE TITLE
[Bugfix-2.0.x] Warning during compilation in PlatformIO (VSCode)

### ISSUE THREAD

**Issue by XBrav** [MarlinFirmware/Marlin#12052]
Marlin\src\gcode\bedlevel\G26.cpp: In function 'bool prime_nozzle()':
Marlin\src\gcode\bedlevel\G26.cpp:478:11: warning: unused variable 'Total_Prime' [-Wunused-variable]
float Total_Prime = 0.0;

Looks like the variable is sitting unused throughout the rest of the code. Can anybody else confirm if it can be removed from G26.cpp?

**Comment by thinkyhead** [comment]
It can't be removed, but I'll wrap it in an appropriate condition.
