### ISSUE TITLE
Marlin ADVi3++ with BL-Touch ABL doesn´t work

### ISSUE THREAD

**Issue by marcovignotto** [MarlinFirmware/Marlin#12050]
Hi everybody, 
I installed the ADVi3 firmware on a Wanhao i3 Plus with the BL-Touch and the Auto Bed Leveling doesn´t work.
The sensor works, I can control it from the LCD, performs the tunning and makes the grid/mesh.
I tried different starting scrpts with Simplyfy3d:

G28
G29

or 

G28 
M420 S1

or even:

G28
M420 S1
M420 Z1

or 

M420 S1 (I got that this commands use the mesh in the eprom)

from the log i get:
Bed Leveling On
Fade Height Off

In any case it doesn´t level the bed at all.

Has anyone an idea?

Thank you in advance

**Comment by thinkyhead** [comment]
We don't support 3rd-party forks of Marlin. You should post your question at https://github.com/andrivet/ADVi3pp-Marlin/issues/new
