### ISSUE TITLE
MKS GEN 1.4 + 5xTMC2208 Z2 no UART

### ISSUE THREAD

**Issue by superperf** [MarlinFirmware/Marlin#12065]
### Hello Everyone,

i popped in 5xTMC2208 prepared for UART. 
X,Y,Z1,E0 are working as expected.
R/Wr are fully functional.

Problem is on Z2. 
I can't figure out how to get RX working on Z2, because the only left RX/TX Pin Combinations not working.

Is someone here who can help me?

**Comment by AnHardt** [comment]
5 x TMC + 1 for the host = 6 serials. On a chip with only 4 UARTS. Means 2 soft serials. That's (too) ambitiously!

**Comment by teemuatlut** [comment]
Make sure the RX pins are interrupt capable.

**Comment by superperf** [comment]
Hi, thats what i've done. But it seems the ARduino MEGA isn't prepared for 5 UART + Serial Print through USB (Octoprint) :( I think i need to flip over the Extruder TMC into Standalone Mode to get both Z-Axis TMCs into UART

**Comment by superperf** [comment]
![image](https://user-images.githubusercontent.com/6002858/46834890-f4cdd800-cdac-11e8-8efa-87035ed30976.png)

thats my Software Serial Config. BUt Z2 is not readable through  UART :/

**Comment by teemuatlut** [comment]
I don't think there's inherently anything that would prohibit you from using all five. But it's not something I've tried myself.
You could try running two from HW Serial (I use serials 1 and 3) and three from SW UART. I know those two UARTS are accessible on a ramps board but I don't know about the MKS board.

**Comment by superperf** [comment]
> I don't think there's inherently anything that would prohibit you from using all five. But it's not something I've tried myself.
> You could try running two from HW Serial (I use serials 1 and 3) and three from SW UART. I know those two UARTS are accessible on a ramps board but I don't know about the MKS board.

yeah that could be possible. THink i need to evaluate a little bit more into this. The MKS Should be same as RAMPS with a little Bunch of PINS changed. Will keep Updating this :)

**Comment by nschermer** [comment]
I've tried the same with a ramps board using pin 57/58, but no success either. Confusing part is that the [instructable](https://www.instructables.com/id/UART-This-Serial-Control-of-Stepper-Motors-With-th/) here did the same and said it was working...

```
#define Z2_SERIAL_TX_PIN   57
#define Z2_SERIAL_RX_PIN   58
```

M122 output
```
		X	Y	Z	Z2	E0
Enabled		true	false	false	false	true
Set current	800	800	800	800	800
RMS current	795	795	795	1436	795
MAX current	1121	1121	1121	2025	1121
Run current	25/31	25/31	25/31	25/31	25/31
Hold current	12/31	12/31	12/31	12/31	12/31
CS actual	12/31	12/31	0/31	0/31	12/31
PWM scale	42	40	41	0	42
vsense		1=.18	1=.18	1=.18	0=.325	1=.18
stealthChop	false	true	false	false	true
msteps		16	16	16	256	16
tstep		1048575	0	1048575	0	1048575
pwm
threshold	0	0	0	0	0
[mm/s]		-	-	-	-	-
OT prewarn	false	false	true	false	false
OT prewarn has
been triggered	false	false	false	false	false
off time	5	5	5	0	5
blank time	24	24	24	16	24
hysteresis
-end		2	2	2	-3	2
-start		3	3	3	1	3
Stallguard thrs
DRVSTATUS	X	Y	Z	Z2	E0
stst		X	X	X		X
olb
ola
s2gb
s2ga
otpw
ot
157C
150C
143C
120C
s2vsa
s2vsb
Driver registers:	X = 0xC0:0C:00:00
	Y = 0x00:00:00:00
	Z = 0xC0:0C:00:00
	Z2 = 0x00:00:00:00
	E0 = 0xC0:0C:00:00
```

M43
```
PIN:  57   Port: F3 (A 3)  Z2_SERIAL_TX_PIN            Output = 1
PIN:  58   Port: F4 (A 4)  Z2_SERIAL_RX_PIN            Input  = 1
```

**Comment by boelle** [comment]
@andrebu89 problem solved?

**Comment by superperf** [comment]
not really, but it works with 4x uart tmcs. printer is printing and im
happy :D

Bo Herrmannsen <notifications@github.com> schrieb am Do., 21. Feb. 2019,
20:24:

**Comment by boelle** [comment]
if happy maybe click the green close bottom below
