### ISSUE TITLE
[2.0.x-bugfix] EEPROM datasize error

### ISSUE THREAD

**Issue by mgineer85** [MarlinFirmware/Marlin#12068]
### Description

Found an EEPROM datasize error. I searched here a little and found I have to enable the debug-output to assist with futher information. This is what the monitor prints:

```
Marlin bugfix-2.0.x
echo: Last Updated: 2018-01-20 | Author: (none, default config)
echo:Compiled: Oct 11 2018
echo: Free Memory: 86504  PlannerBufferBytes: 1664
Error:Field parser_volumetric_enabled mismatch.
Error:EEPROM datasize error.
echo:Index: 633 Size: 665
echo:Hardcoded Default Settings Loaded
```

### Steps to Reproduce

1. Load a fresh marlin 2.0.x-bugfix copy (I loaded today evening)
2. configure marlin (I disabled volumetric by #define NO_VOLUMETRICS, because I want to use marlin for openpnp)
3. setup in platform-io to compile for arduino due with radds shield
4. upload and start the monitor
5. reset eeprom and store again doesn't help...

#### Additional Information

* [Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2470240/Marlin.zip)

**Comment by formadi** [comment]
I have a same problem.

**Comment by Lyr3x** [comment]
Yep happend to me since yesterday too:
```Recv: echo: Free Memory: 3611  PlannerBufferBytes: 1648
Recv: Error:EEPROM datasize error.
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: EEPROM datasize error.
Recv: echo:Index: 565 Size: 597
```

- MKS Gen 1.4 with TMC2130
- Without disabling volumetric though!

**Comment by ikarisan** [comment]
Same here!

Resetted the EEPROM and also executed M502 and M500.
But after a reset, I am getting the same "EEPROM datasize" error.

**Comment by ikarisan** [comment]
Connecting...
start
Printer is now online.
echo:Marlin bugfix-2.0.x

Talking about this: af3bf6c9563fa6f9c6d10c8c62501f01bf5c3050 
```
echo: Last Updated: 2018-01-20 | Author: Shinji Ikari
echo:Compiled: Oct 12 2018
echo: Free Memory: 3352  PlannerBufferBytes: 1648
Error:Field parser_volumetric_enabled mismatch.
[ERROR] Error:Field parser_volumetric_enabled mismatch.

Error:EEPROM datasize error.
[ERROR] Error:EEPROM datasize error.

echo:Index: 525 Size: 557
echo:Hardcoded Default Settings Loaded
```

**Comment by cjsoong** [comment]
10/7 Downloaded Test ok
10/13 download test: EEPROM datasize error

**Comment by povlhp** [comment]
Compiled for Ender-3 with BLTouch. Error here as well.

**Comment by viper93458** [comment]
Ouch, I am seeing this one too. Welcome to testing! :)

**Comment by povlhp** [comment]
Fixed in 213e94b for me

**Comment by mgineer85** [comment]
@povlhp: you meant #12086 ?

**Comment by facet02** [comment]
Got the same Error:EEPROM datasize error... on my MKS Gen 1.4
Also have the problem with M23:
Send: M23 /sd/curahe~1.gcoRecv: echo:Now fresh file: /sd/curahe~1.gcoRecv: open failed, File: curahe~1.gco.Recv: ok

dont know if there is a realtion

**Comment by mgineer85** [comment]
can confirm that #12086 fixes the issue reported initially here.
@facet02 load the current version and try again. if the error still occurs, it's not likely to be related and you might open another issue for that.
