### ISSUE TITLE
G29 P1 not probing mesh edges

### ISSUE THREAD

**Issue by Bob-the-Kuhn** [MarlinFirmware/Marlin#12071]
I'm finally getting my printer back up and (mostly) running but I've forgotten a lot of the details.

I haven't figured out how to set my configuration files so that the boundaries of the printable area are probed by G29 P1.

I'm running bugfix 2.0 and UBL with a 4x4 mesh,.  The printable bed area is (0.0) through 260,260).  The entire printable area is probeable.

With these config files I get the four interior points being probed but none of the points on the boundaries.

[Configuration_files.zip](https://github.com/MarlinFirmware/Marlin/files/2471124/Configuration_files.zip)

**Comment by Roxy-3D** [comment]
#define MESH_INSET -10  

That doesn't seem like a good idea...       And why only a 4 x 4 mesh?  Wouldn't 8 x 8 or 10 x 10 make more sense?

**Comment by Bob-the-Kuhn** [comment]
**#define MIN_PROBE_EDGE 10** is what caused the boundary problems.

I still have something else wrong.  I think I have my Y probe offset set wrong.
