### ISSUE TITLE
Thermal Runaway, system stopped! Heater_ID: bed

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [MarlinFirmware/Marlin#12087]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by Ludy87** [comment]
your issues is a safety Features.

**Comment by TheSFReader** [comment]
And apart from the title, it seems you didn't in the least try and find out how to report properly the problem you have...

**Comment by psavva** [comment]
@REVIEWGAMINGMAN Please can you add the necessary information.

The most important being both the Configuration.h and Configuration_adv.h files.
Given the title, you may either have a hardware issue, or your config files need little adjustments.

**Comment by REVIEWGAMINGMAN** [comment]
no everything I have is new parts

**Comment by REVIEWGAMINGMAN** [comment]
any idea how to prevent this with a 12-hour print

**Comment by REVIEWGAMINGMAN** [comment]
no I did do some research since I was testing my printer for bags

**Comment by REVIEWGAMINGMAN** [comment]
the good news is the printer printed for 4 hours with no problems

**Comment by Grogyan** [comment]
@REVIEWGAMINGMAN you need to provide a LOT more information in your first post, there is nothing there for us to help you

**Comment by REVIEWGAMINGMAN** [comment]
ok

**Comment by toome123** [comment]
@REVIEWGAMINGMAN  May be is hardware problem, or config issue..

- You can tune these values in Configuration_abv.h
THERMAL_PROTECTION_PERIOD, 
THERMAL_PROTECTION_HYSTERESIS
- Make sure all connection of the termistors is ok.
- Make sure your power supply is good enough. 
- View what is recommend configurations for your printer...
