### ISSUE TITLE
Dual-Endstops not working correctly on Z-Axis

### ISSUE THREAD

**Issue by Ralph12345** [MarlinFirmware/Marlin#12081]
If I manually trigger Z2-endstop the Z-motor goes on. If I manually trigger Z1-endstop the homing stopped.

[https://youtu.be/YRoTM0d7N-Y](url)

Marlin bf 1.1.9

**Comment by MarphXL** [comment]
Use Marlin 1.1.7! Marlin 1.1.9, 2.0 and bf1.1.9 are buggy.
For more information look here: [https://github.com/MarlinFirmware/Marlin/issues/12020](https://github.com/MarlinFirmware/Marlin/issues/12020)

**Comment by thinkyhead** [comment]
Duplicate of #12020
