### ISSUE TITLE
EEPROM datasize error MKS gen 1.4 todays marlinbugfix2.0.x octoprint wont connect.

### ISSUE THREAD

**Issue by Glod76** [MarlinFirmware/Marlin#12085]

**Comment by Glod76** [comment]
Recv: echo:Marlin bugfix-2.0.x
Recv: 
Recv: echo: Last Updated: 2018-01-20 | Author: (Donnie Roszel, FT-5 R2 Chimera)
Recv: echo:Compiled: Oct 14 2018
Recv: echo: Free Memory: 2348  PlannerBufferBytes: 1648
Recv: Error:EEPROM datasize error.
Changing monitoring state from "Connecting" to "Error: EEPROM datasize error."
Changing monitoring state from "Error: EEPROM datasize error." to "Offline (Error: EEPROM datasize error.)"
Connection closed, closing down monitor

**Comment by Glod76** [comment]
[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/2476122/Configurations.zip)

**Comment by Glod76** [comment]
Seems to have fixed the error, thank you.

**Comment by swilkens** [comment]
If a merge fixed the issue, please close the issue report :)

**Comment by swilkens** [comment]
If a merge has fixed your issue, please close the issue :)
