### ISSUE TITLE
Babystepping not working

### ISSUE THREAD

**Issue by rb1205** [MarlinFirmware/Marlin#12099]
### Description

On current bugfix-1.1.x (last commit 5e0dffd) i'm having big issues with babystepping. No matter which way I rotate the dial, the Z axis moves in one direction. Sometimes it's up, sometimes it's down, but it's not related to how I rotate the encoder. It looks like it moves on the same direction UBL is compensating, but i'm not completely sure about that.

The value in the LCD changes correctly based on how I move the encoder (up or down), so it's not an issue with the encoder.

I have UBL compiled and active

Tried both with BABYSTEP_ZPROBE_OFFSET enabled or disabled, same behavior.

### Steps to Reproduce

1. Home the axes
2. Move the Z axis next to the printing bed, eg. G1 Z1
3. Initiate a slow XY movement, eg G1 F20 X20
4. Go to the babystepping page either via double click or by navigating the menu
5. Rotate the encoder clockwise, notice how the Z axis moves
6. Rotate the encoder counter-clockwise, notice how the Z axis moves

**Expected behavior:** [What you expect to happen]
The Z axis moves both up and down based on which way I turn the encoder

**Actual behavior:** [What actually happens]
The Z axis moves the same direction regardless of which way I turn the encoder

#### Additional Information

[Configuration ZIP file](https://www.dropbox.com/s/dxiglw1axyp0dt2/Configuration.zip?dl=0)

**Comment by thinkyhead** [comment]
Try increasing your `MINIMUM_STEPPER_PULSE` value.

**Comment by rb1205** [comment]
I crosschecked with different drivers and it works as expected. Closing.

**Comment by Fr33man85** [comment]
What is the conclusion, what solved the problem?

changes at MINIMUM_STEPPER_PULSE 

or 

changing the driver?

**Comment by rb1205** [comment]
Neither. I'm using industrial grade drivers that have strict requirements in term of direction reversal delay that can be violated by babystepping coupled with auto bed levelling, no matter how I configure Marlin.

Long story short, babystep only works if the z axis is still (duh) OR if the babystep and the level compensation movements are the same direction. If you try to babystep the "wrong" direction, the Z axis will lose steps and "snap" back. Kinda hard to explain, but with a bit of experience you learn how to make it work correctly.  

It's not ideal, but the reliability and power of these drivers make up for that long time. I'm finally done with losing prints due to overheating/underpowered/failing/whatever pololu & co. threw at me.

About the root cause, it looks like Marlin ignores the direction reversal delay when babystepping. Since "normal" drivers can work with that I'm not sure if that should be considered a bug or not.
