### ISSUE TITLE
L'auto-nivellement inductif corrige une pente qui n'existe pas

### ISSUE THREAD

**Issue by David-4l** [MarlinFirmware/Marlin#12100]
### Étapes à reproduire

Quand on démarre l'impression d'un objet, l'imprimante sonde et enregistre les valeurs pour normalement corriger les défauts du plateau mais l'imprimante corrige un défaut qui n'existe pas..

### Comportement attendu: [ Ce que vous prévoyez d'arriver]

Comme mon plateau est vraiment plat, le sondage ne devrait rien corriger car pas de défaut.

### Comportement réel: [Qu'est-ce qui se passe réellement]

L'imprimante se lève toujours de 1mm du plateau vers l'avant, le filament est donc bien appliqué sur l'arrière du plateau mais à l'avant le fil ne colle pas.
Ce problème à commencé en version 1.1.8 donc j'ai passé mon imprimante en 1.1.9 mais le problème est identique.

### Information complémentaire

Mon imprimante est une CTC prusa i3 pro B avec vis T8 et capteur de nivellement.

* Inclure un fichier ZIP contenant vos fichiers `Configuration.h` et` Configuration_adv.h`.
[Fichier marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2479658/Fichier.marlin.zip)

Pour toute information complémentaire, je reste à votre disposition

**Comment by thinkyhead** [comment]
Check your mechanical and electrical situation. When probe readings are good, bed leveling works just fine. Here's the boilerplate on where to get help and support:

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
