### ISSUE TITLE
TMC2130 communication problem when connecting to PS (overheat for all drivers) 

### ISSUE THREAD

**Issue by sergane1313** [MarlinFirmware/Marlin#12102]
Hi guys ! I am using tmc2130 v1.1 from China , ramps 1.4 with mega . I have a lot of problem with SPI communication such as when i pluged th PS to the printer i get from all drivers Overheat error and the register look like this 'X = 0xFF:FF:FF:FF for al 4 drivers (x , y, z , e0) i have no idea what is happening . I let my code here . (I have already checked all the wires for at least 10 times and everything seems fine ). to Hi guys ! I am using tmc2130 v1.1 from China , ramps 1.4 with mega . I have a lot of problem with SPI communication such as when i pluged the PS to the printer i get from all drivers Overheat error and the register look like this 'X = 0xFF:FF:FF:FF for all 4 drivers (x , y, z , e0) i have no idea what is happening . I let my code here . (I have already checked all the wires for at least 10 times and everything seems fine )

**Comment by sergane1313** [comment]
if you need more info, please let me know 
I am using bugfix 2.0 , i have already tried with 1.1.8 and 1.1.9
[config.zip](https://github.com/MarlinFirmware/Marlin/files/2482757/config.zip)

here is my config.h config_adv.h and pins_ramps.h

**Comment by swilkens** [comment]
That's an indication of not communicating properly between the board and the stepper, you might be using hardware SPI wiring with software SPI setup?

It would help if you:

- Fix this issue report, the title is a mess and the copy / pasted code is unreadable

- Upload some pictures showing how you have wired everything

- Upload a .zip file with your configuration.h and configuration_adv.h (don't copy / paste it here)

It is likely this is just a setup error, not a problem with the code.

**Comment by sergane1313** [comment]
![44113545_310896753061796_8184401486399143936_n](https://user-images.githubusercontent.com/31934947/47012702-86429e80-d14d-11e8-9c5f-43d67b3648bc.jpg)
![44178819_275332196315210_2621068861138534400_n](https://user-images.githubusercontent.com/31934947/47012705-88a4f880-d14d-11e8-9541-ec18cdc52de1.jpg)
![44115862_2113778255599966_3555922386362564608_n](https://user-images.githubusercontent.com/31934947/47012706-893d8f00-d14d-11e8-8233-1c2b939a47b5.jpg)

here are some photos with my wiring (i did not have split wires so i made some diy ones / i checked all the connection with a multimeter an everything is ok ) .
