### ISSUE TITLE
Progress bar not showing status when less than 2-3%

### ISSUE THREAD

**Issue by mmoraes80** [MarlinFirmware/Marlin#12113]
Hello,

I am currently using the latest Marlin version and I have noticed that the progress less than 2% is not shown in the progress bar when either printing from the SD directly from the printer control box nor when printing using Octoprint (in this case, the progress is correctly shown in OP web interface). The progress bar will remain empty and no % number will be shown until progress is greater than 2%.

### Steps to Reproduce

1. Just print anything.
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by mmoraes80** [comment]
Just start a print job. The progress bar will stay empty and no % number will be shown until progress >= 2%.

**Comment by thinkyhead** [comment]
This is by design, to preserve the status message for longer, but if you want to change it, just find the following text in the LCD code and change it to suit your preference:
```
progress_bar_percent > 2
```
