### ISSUE TITLE
TMC2130 vs TMC2130_STANDALONE which one to use in config.h ?

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#12111]
I'm changing my current drivers TMC2100 to TMC2130 SPI Mode, bought from Aliexpress (https://pt.aliexpress.com/item/3D-Printer-StepStick-TMC2130-V1-1-Stepper-Motor-Mute-Driver-Silent-Support-SPI-Stability-ramps-1/32896010992.html?spm=a2g03.10010108.1000016.1.610e2523nEeP2t&isOrigTitle=true)

In config.h which settings should I put for these drivers ? TMC2130 or TMC2130_STANDALONE ?

**Comment by Ludy87** [comment]
With SPI TMC2130
Without SPI as TMC2130_STANDALONE

**Comment by sergiofagundes** [comment]
Thanks !

**Comment by Ludy87** [comment]
@sergiofagundes close this issue

**Comment by boelle** [comment]
@sergiofagundes problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
