### ISSUE TITLE
[FR] Show remaining print time with M73

### ISSUE THREAD

**Issue by annego15** [MarlinFirmware/Marlin#12123]
The Slic3r Prusa Edition added a feature to show the remaining print time on the lcd by sending "M73 P{percent} R{remaining time in minutes}". 

M73 already exists in Marlin to set the progress in percentage, but i lacks the R argument for remaining time in minutes.

It would be really nice if you could add this to Marlin so you can see an accurate estimate from the slicer how many minutes until the end instead of the elapsed time.

**Comment by AnHardt** [comment]
Use M117 instead. No space left.

**Comment by thinkyhead** [comment]
> No space left.

Of course, it could blink between Elapsed time and ETA if space is tight.

**Comment by boelle** [comment]
@thinkyhead was this not added recently?

**Comment by GMagician** [comment]
This may be closed, I think
