### ISSUE TITLE
[2.0.x] Compile error

### ISSUE THREAD

**Issue by ModMike** [MarlinFirmware/Marlin#12142]
### Description

Please excuse the urgent request, I am at a friends company finalizing an install.

Compiling error when building using latest 2.0.x.  Used to compile fine

### Steps to Reproduce

Add the included files:

1. Configuration.h
2. Configuration_adv.h
3. Boards.h
4. Pins.h
5. pins_CREATBOT_DX.h

Compile using Atmega 2560 env.

### Actual Behaviour

```
Compiling .pioenvs/megaatmega2560/src/src/gcode/calibrate/G28.cpp.o
Compiling .pioenvs/megaatmega2560/src/src/gcode/calibrate/M666.cpp.o
Compiling .pioenvs/megaatmega2560/src/src/gcode/calibrate/M852.cpp.o
Compiling .pioenvs/megaatmega2560/src/src/gcode/config/M200-M205.cpp.o
In file included from Marlin/src/gcode/calibrate/G28.cpp:31:0:
Marlin/src/gcode/calibrate/../../module/tool_change.h:34:21: error: 'TOOLCHANGE_ZRAISE' was not declared in this scope
float z_raise = TOOLCHANGE_ZRAISE;
^
*** [.pioenvs/megaatmega2560/src/src/gcode/calibrate/G28.cpp.o] Error 1

```
#### Additional Information

[CBDX FILES.zip](https://github.com/MarlinFirmware/Marlin/files/2492702/CBDX.FILES.zip)

**Comment by p3p** [comment]
There has been an update to the configs in a recent PR
This was added to `Configuration.h`
```
// Z raise distance for tool-change, as needed for some extruders
#define TOOLCHANGE_ZRAISE     2  // (mm)
```
This was removed from `Configuration_adv.h`
```
// Default settings in "Auto-park Mode"
  #define TOOLCHANGE_PARK_ZLIFT   0.2      // the distance to raise Z axis when parking an extruder
  #define TOOLCHANGE_UNPARK_ZLIFT 1        // the distance to raise Z axis when unparking an extruder
```

**Comment by ModMike** [comment]
@p3p You bailed me out big time, thanks!
