### ISSUE TITLE
[2.0.x]Hotend Temp Instability On Latest 2.0 Version

### ISSUE THREAD

**Issue by PurelyAbrasive** [MarlinFirmware/Marlin#12149]
I have recently downloaded the latest version of 2.0 running a RAMPS/ReArm and I have been having issues with the Hotend temp not being stable.  The hotend is an E3D Titan Aero.  I have also ran the PID tuning a couple of times and the values are all pretty close to one another.
![tempinstablility](https://user-images.githubusercontent.com/17590678/47195303-4d5f2100-d329-11e8-883f-67e37a0d0d8a.png)

**Comment by AnHardt** [comment]
How much is that wave peak to peak? 2°C? Else locking beautiful.
You could try to reduce Kp.

**Comment by swilkens** [comment]
Is there actually a notable change between this and the previous version? What was the temperature fluctuation on your previous install? Can you go back to that previous version and check what the readings are?

Based on what we can see here, your hotend temp just swung upwards which is listed as 205.7 C, 0.7 C over the setpoint. That pretty good.
