### ISSUE TITLE
FWRETRACT and SINGLENOZZLE TOOL CHANGE coexistence ' not an issue'

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#12151]
@thinkyhead 
Hi , it's not an issue , just a suggestion
For all that use ' FWRETRACT ' , we use the Long Retract for tool changing
But now , tool changing is implemented
Is it possible to simplify the code to have only one possibility and no coexistence because 
-Tool change need to be set to ZERO , to use our actual flavor , because long retract + tool change = double long retract
- If we set FWRETRACT swap to zero , or TOOLCHANGE to zero , we have some sram eated and not used , because of float variables and menu implementations

Possible to have a codependent system ?

#define INTELLIGENT_TOOLCHANGE_FWRETRACT_SWAPPING_COEXISTENCE 
This option use the FWretract setting , toolchange menu deleted , and a smart filter that avoid a bad behavior , like this : If swapped , the toolchange process don't unload , just apply new tool and load it , update 'not swapped status ' to the actual. The tool change process will always make a verification of the swapping statuses before changing tool and update all swap statuses. With this system , any flavor can be used 'swapping or not before a tool change , and retracting after a toolchange or not ' , no corruption if some G10 S1 appears before a tool change or a G11 after the toolchange. And many line of code not compiled in this case : Easy for you :-) 

Or may be , you implement ' The loaded statuses ' in marlin , and tool change use them , fwretract must be rewritten without long retract , it's a good idea too because if we have reflexion about the long retract .... this option not need to exist ... it's a tool change function only. all is already written in fwretract it's easy to move it , in toolchange unit

May be , it's the end of the G10S1 ....
Just an idea for thinkyhead

**Comment by InsanityAutomation** [comment]
Im working on consolidating some more stuff in tool change. In that, there is a specific enable for filament swap on tool change and im expanding it to all tool change types. From this, it should be a matter of not enabling the dedicated filament swap if you're using the fwretract settings to accommodate.

**Comment by studiodyne** [comment]
i have rewritten my suggestion , please read once again 
i'm talking about implementing the LOADING STATUS OF THE EXTRUDERS , and all will be simplified

**Comment by InsanityAutomation** [comment]
There is branches in tool change to allow functionality even when fwretract is disabled. Hold off a few days and take a fresh look when I get a bit farther on what im working on, and it may  be better to see whats going on.

**Comment by InsanityAutomation** [comment]
I just updated my current working branch to pr #12137 so maybe you can get a picture of where im going.
