### ISSUE TITLE
[FR]  Filaments list presets for Extruder steps calibration

### ISSUE THREAD

**Issue by jremen** [MarlinFirmware/Marlin#12150]
As there is a constant need to calibrate extruder steps after each filament change, it would be great to have ability to create a custom filament list with predefined extruder steps.

User could then choose a filament from list he has created for a specific extruder calibration right after filament change.

A list could be created by sending Gcode command for easier naming directly on computer.

Steps to implementation:
1.) Calibrate extruder steps and save by M92 Exxx;
2.) Save current filament steps via gcode and name an entry for these settings ie. M145 S[index] Exxx (steps calibrated) PRUSA_PETG_BLK (for naming)
3.) M500 to save

Then, when user change the filament, he should be able to go to Filaments menu and select predefined filament he created in steps above.

**Comment by thinkyhead** [comment]
Sounds like a job for the slicer's filament profile. Seems like just more noise to burden the firmware with this. Just add `M221` with a flow percentage to your slicer's starting G-code when you determine the right adjustment for the filament.

**Comment by jremen** [comment]
Might be. Now the idea is that it would be in the firmware, while implementation in slicer engine of your choice might never come.

**Comment by AnHardt** [comment]
"Extrusion multiplier" is in Slicer (filament settings) since ages.

**Comment by jremen** [comment]
Extrusion multiplier is something else as precisely defined Extruder steps. Moreover, not everybody is using Slicer, personally I hate it.

**Comment by boelle** [comment]
Then maybe do the same in cura? or whatever slicer you want

**Comment by boelle** [comment]
missing label
