### ISSUE TITLE
[2.0.x] Z axis only moves upwards after homing

### ISSUE THREAD

**Issue by dahuafschmied** [MarlinFirmware/Marlin#12156]
### Description
Hi
I have an Anycubic i3 Mega with 8bit board, 5x TMC2208 standalone and REPRAP_DISCOUNT_SMART_CONTROLLER.
I am using the lastest Version of Marlin 2 from Github.
Here is my Repository: https://github.com/dahuafschmied/Marlin-for-Anycubic-i3-Mega/tree/bugfix-2.0.x
i have changed the config, config_adv, trigorilla1.4 pins and configuration_store (for #12112 fix)
here are the changes: https://github.com/MarlinFirmware/Marlin/compare/bugfix-2.0.x...dahuafschmied:bugfix-2.0.x

The bug:
I can move the z axis downward and upwards (nozzle to bed) bevore homing.
After Homing the z axis is only moveable upwards.

### Steps to Reproduce
compile my config.
move the z axis up and down
home the z axis
only up is possible

#### Additional Information
Video:
https://www.facebook.com/flatti/videos/10205276294664664/

Marlin 1.1.9 -> OK (up and down possible)
Disabled  #define Z_DUAL_ENDSTOPS  -> OK ( up and down possible, but this is needed, printer has 2 endstops and 2 stepper for Z)

checked the endstops with M119. -> they are OK
checked the endstops with M43 E0 -> they are OK

is the z axis moved downwards after homing the steppers are not spinning but the position is decremented on the display.

Thank you for your help

**Comment by GMagician** [comment]
You don't have an updated bugfix 2.0.version, it seems like you miss #11900

Edit: I checked and it seems present. Maybe it doesn't solve issue when `ENDSTOP_INTERRUPTS_FEATURE` is disabled. Do your board support this option? you may try to enable it and see what happens

**Comment by GMagician** [comment]
@dahuafschmied Instead of enabling interrupt feature you may try to remove line 281 `#if ENABLED(ENDSTOP_INTERRUPTS_FEATURE)` in endstops.cpp and its `#endIf` counterpart.
If it works I'll post a PR

**Comment by dahuafschmied** [comment]
@GMagician = hero! :-)
i can confirm your patch is fine. 

interrupt: my Y_MIN_PIN and Z2_MIN_PIN is not interrupt-capable
