### ISSUE TITLE
[1.1.9] TMC2130 setup

### ISSUE THREAD

**Issue by AleXthePunK** [MarlinFirmware/Marlin#12163]
### Description

I have searched bugfix, and I have searched the RepRap forum, and I can't seem to find what I am looking for. For this reason, this may be a bugfix.

With version 1.1.9, I am trying to enable the TMC2130.

In the configuration_adv.h file, the commands:
#define HAS_TRINAMIC is missing, and not commented out. 

#define X_IS_TMC2130 is missing, along with the other ones.

I can manually add all of the missing defines, but the bug is, it is not stated anywhere in the documentation, or on the reprap forum that these need to be added for 1.1.9.

Were they removed on purpose and/or I am missing something?

Thanks for your help!

**Comment by gloomyandy** [comment]
You probably no longer need those settings, instead you need to tell Marlin what each of your stepper drivers is. This is in Configuration.h....
```
/**
 * Stepper Drivers
 *
 * These settings allow Marlin to tune stepper driver timing and enable advanced options for
 * stepper drivers that support them. You may also override timing options in Configuration_adv.h.
 *
 * A4988 is assumed for unspecified drivers.
 *
 * Options: A4988, A5984, DRV8825, LV8729, L6470, TB6560, TB6600, TMC2100,
 *          TMC2130, TMC2130_STANDALONE, TMC2208, TMC2208_STANDALONE,
 *          TMC26X,  TMC26X_STANDALONE,  TMC2660, TMC2660_STANDALONE,
 *          TMC5130, TMC5130_STANDALONE
 * :['A4988', 'A5984', 'DRV8825', 'LV8729', 'L6470', 'TB6560', 'TB6600', 'TMC2100', 'TMC2130', 'TMC2130_STANDALONE', 'TMC2208', 'TMC2208_STANDALONE', 'TMC26X', 'TMC26X_STANDALONE', 'TMC2660', 'TMC2660_STANDALONE', 'TMC5130', 'TMC5130_STANDALONE']
 */
//#define X_DRIVER_TYPE  A4988
//#define Y_DRIVER_TYPE  A4988
//#define Z_DRIVER_TYPE  A4988
//#define X2_DRIVER_TYPE A4988
//#define Y2_DRIVER_TYPE A4988
//#define Z2_DRIVER_TYPE A4988
//#define Z3_DRIVER_TYPE A4988
//#define E0_DRIVER_TYPE A4988
//#define E1_DRIVER_TYPE A4988
//#define E2_DRIVER_TYPE A4988
//#define E3_DRIVER_TYPE A4988
//#define E4_DRIVER_TYPE A4988
//#define E5_DRIVER_TYPE A4988
```

**Comment by AleXthePunK** [comment]
Thank you, some how I missed that. I have a combination of the TMC2130 and A4988, and I wanted to make sure that marlin knew.

Note: I upgraded from an OEM 1.1.6 to Marlin FW 1.1.9, so a lot of the notes were missing. I just copied config files from the OEM version, big mistake!! I should have just gone through and re-set it up.
