### ISSUE TITLE
Einsy Rambo 1.1 and reprapdiscount smart LCD issue

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#12167]
I'm having an issue with this board and the lcd, I can compile and upload the firmware to the board, but the LCD is showing garbage characters. Interesting is that the bootloader shows without any problem, even when it is updating the firmware.

So I tried to download a ready compiled firmware (original Prusa MK3 firmware 3.4.1) and the LCD works flawless. But if I try to compile the Marlin or even the Prusa MK3 source the lcd is gargaged.

Is there anything in Arduino that is causing this, since it doesn't look a firmware problem.

**Comment by marcio-ao** [comment]
Try increasing CPU_ST7920_DELAY_2 from 250 to 300 in "ultralcd_st7920_u8glib_rrd_AVR.cpp":

```
...
#elif MB(MINIRAMBO) || MB(EINSY_RAMBO) || MB(EINSY_RETRO)
  #define CPU_ST7920_DELAY_1 DELAY_NS(0)
  #define CPU_ST7920_DELAY_2 DELAY_NS(300)
  #define CPU_ST7920_DELAY_3 DELAY_NS(0)
...
```

**Comment by sergiofagundes** [comment]
Hi. Fixed this.

It's not a firmware issue. Arduino needs a Rambo board to be added. Now everything works nice.
