### ISSUE TITLE
Bugfix2.0 - No numerical display for Y axis on LCD

### ISSUE THREAD

**Issue by RudyBenner** [MarlinFirmware/Marlin#12178]
Latest bugfix 2.0 does not display the Y axis position on the MKS MINI 12864 LCD. Just a blank where the numbers should be.
Marlin 1.1.9 does show the Y axis correctly. Bugfix 1.1.x also works correctly.

Have reloaded several times.

[Bugfix 2.0.x configs.zip](https://github.com/MarlinFirmware/Marlin/files/2499368/Bugfix.2.0.x.configs.zip)
[Marlin 1.1.9 configs.zip](https://github.com/MarlinFirmware/Marlin/files/2499369/Marlin.1.1.9.configs.zip)

**Comment by Lyr3x** [comment]
I can confirm. Exact same issue for me using the MKS MINI 12864 using bugfix-2.0: aa9202260dcf1add950afdb05942f3c0e89d9af4

**Comment by Lyr3x** [comment]
I can confirm on build: aa9202260dcf1add950afdb05942f3c0e89d9af4

**Comment by flywork39** [comment]
me too.

**Comment by RudyBenner** [comment]
Not a big deal, since I operate from Repetier Host, but it should eventually be addressed.

**Comment by thinkyhead** [comment]
Pretty odd! The code to draw it is the same for all graphical LCDs, and matches the technique used for X and Z. No special conditions for this display.

**Comment by swilkens** [comment]
I did a bisect and found that the offending commit is: https://github.com/MarlinFirmware/Marlin/commit/67a3c5a16ad0c202352ef19b5993ac0c7f52862d, https://github.com/MarlinFirmware/Marlin/commit/5b7dd553d3543d2e1a9305eca6060e35fe2fbed9 is fine.

That would be this pull request: https://github.com/MarlinFirmware/Marlin/pull/12132

@thinkyhead

**Comment by RudyBenner** [comment]
Please excuse my newbieness, how do I fix it?

**Comment by RudyBenner** [comment]
Looked for 

LCD_INFO_SCREEN_STYLE

Changed value to 1.

Error codes..
```
In file included from Marlin\src\HAL\HAL_AVR\../../inc/MarlinConfig.h:41:0,
from Marlin\src\HAL\HAL_AVR\HAL_spi_AVR.cpp:40:
Marlin\src\HAL\HAL_AVR\../../inc/SanityCheck.h:460:6: error: #error "Alternative LCD_INFO_SCREEN_STYLE requires 20x4 Character LCD."
#error "Alternative LCD_INFO_SCREEN_STYLE requires 20x4 Character LCD."
```
Does not compile. 1.1.9 and Bugfix 1.1.x work fine with this LCD

**Comment by thinkyhead** [comment]
I’ll check it out. @RudyBenner could I borrow your configuration files for testing?

**Comment by RudyBenner** [comment]
I posted both sets.  Compiles with Arduino IDE and also Marlin-Conf.

**Comment by thinkyhead** [comment]
Oh yeah, there they are. I'll have a patch shortly, I'm sure…

**Comment by thinkyhead** [comment]
> `LCD_INFO_SCREEN_STYLE` … Changed value to 1. … Error codes..
> Alternative LCD_INFO_SCREEN_STYLE requires 20x4 Character LCD.

Well, that is to be expected. `MKS_MINI_12864` is a _**Graphical**_ LCD.

**Comment by RudyBenner** [comment]
20 lashes

**Comment by RudyBenner** [comment]
![p_20181026_021851_vhdr_auto](https://user-images.githubusercontent.com/40361032/47548584-879b6600-d8c7-11e8-9231-0c7cc75c7be2.jpg)
![p_20181026_022417_vhdr_auto](https://user-images.githubusercontent.com/40361032/47548587-879b6600-d8c7-11e8-964f-bc04b22eaa6d.jpg)

**Comment by thinkyhead** [comment]
Now patched! Counterintuitively, by not providing enough buffer space for the Z string, the Y value ended up with a `nul` as its first character.
