### ISSUE TITLE
Strange issue with babystepping/move z while idle.

### ISSUE THREAD

**Issue by forkoz** [MarlinFirmware/Marlin#12179]
So I jumped at the chance to have quick access to move print head while the printer is idle. I have it configured like so:

```
#define BABYSTEPPING
#if ENABLED(BABYSTEPPING)
  //#define BABYSTEP_XY              // Also enable X/Y Babystepping. Not supported on DELTA!
  #define BABYSTEP_INVERT_Z false    // Change if Z babysteps should go the other way
  #define BABYSTEP_MULTIPLICATOR 5   // Babysteps are very small. Increase for faster motion.
  #define DOUBLECLICK_FOR_Z_BABYSTEPPING // Double-click on the Status Screen for Z Babystepping.
  #if ENABLED(DOUBLECLICK_FOR_Z_BABYSTEPPING)
    #define DOUBLECLICK_MAX_INTERVAL 1250   // Maximum interval between clicks, in milliseconds.
                                            // Note: Extra time may be added to mitigate controller latency.
  #endif
  #define MOVE_Z_WHEN_IDLE                // Jump to the move Z menu on doubleclick when printer is idle.
  #if ENABLED(MOVE_Z_WHEN_IDLE)
    #define MOVE_Z_IDLE_MULTIPLICATOR 1     // Multiply 1mm by this factor for the move step size.
  #endif
```

After a fresh reboot and before homing, the print head moves down when turning it to positive values. Then when subtracting the + values the head moves down again. This time, however positive values move the print head up.

I had envisioned using this feature to move the head quickly off of failed prints after reset but in this state it would be counter productive. With further testing I notice the normal "move Z" menu also does the same thing and so trying to move the head up on a fresh boot is now impossible. In the case off a crashed head this is very bad.

FYI, my Z motor direction is inverted so it sounds like the first move doesn't respect that.
#define INVERT_Z_DIR true

**Comment by AnHardt** [comment]
In case you are running bugfix-2.0.x try to readd
https://github.com/MarlinFirmware/Marlin/pull/12098/files#diff-a7c736c674fcde8ddf7bf0e86181e4c0L2110

**Comment by forkoz** [comment]
I am running 2.0x but I'm not using any mixing extruder. Its the Z that moves the wrong way.

.... I tried downloading a fresh repo and moving my config files + mksSbase pins. The behavior continues.
If moving from homed position, nozzle will hit the bed trying to move it up as it has to go down 2mm before it moves up.

**Comment by AnHardt** [comment]
Just that one line what has no relation to MIXING_EXTRUDERS. Without that line directions are initialised by the first regular move. If you try to babystep before the first move it might need an earlier initialisation.

**Comment by forkoz** [comment]
oooooh, I see the one highlighted. I added it back and this fixes the bug.

Any issue with PR to add this back? Consider printer has frozen with nozzle stuck on the piece. You reboot and go into motion menu to move nozzle away before it cools, babystepping or not nozzle moves down. Possibly by 10mm if you chose that setting. Potentially a very bad time if you can't make any other moves after reboot.

**Comment by gloomyandy** [comment]
I think I've also been seeing this issue. If I power the printer on, then (before any home), do a manual move then the printer will often move in the wrong direction. So I don't think you need to use babysteps to hit this problem. I managed to crash the head into the bed when I used the LCD to try and move it out of the way.

I'll try putting that line back and see if it helps as soon as I get chance.

**Comment by InsanityAutomation** [comment]
Fyi, set_directions() doesn't seem to fix every instance of improper direction. I still got errors while running through debugging idex stuff Sat and Sun.

**Comment by AnHardt** [comment]
Did you have any hint this could heal the world?

**Comment by silentninja1** [comment]
No, just based on this being a similar situation with a stepper moving the wrong direction figured id make mention that it could still occur in other scenarios and to keep an eye on it with the current builds.

**Comment by AnHardt** [comment]
Confused about who is who.

**Comment by silentninja1** [comment]
InsanityAutomation and this are both the same person, just a personal account on one device and company name tagged on the other. Sometimes forgot which im logged into where...

**Comment by forkoz** [comment]
Besides your debugging issue which shouldn't happen under normal operation, what should I look out for? Will it reverse mid print or something or retract vs extruding?

**Comment by silentninja1** [comment]
I ran into the X axis reversing direction during homing under a couple different scenarios. Quick home enabled was the most repeatable when Y made its home switch first.

**Comment by thinkyhead** [comment]
Did your recent patch solve this, @silentninja1 / @InsanityAutomation ?

**Comment by InsanityAutomation** [comment]
Yup, good at this point!

**Comment by gloomyandy** [comment]
If the "recent patch" is simply re-inserting the call to set_directions() then so far it works for me. If there is a better/more complete patch then can someone give me a pointer to it and I'll happily give it a try.

**Comment by InsanityAutomation** [comment]
The patch moved a set directions call back below setting of last moved in extruder. #12200

**Comment by gloomyandy** [comment]
Thanks @InsanityAutomation I see this has been merged so I'll give it a try in the next day or so (busy printing things at the moment).
