### ISSUE TITLE
 [bugfix-2.0.x] LIN_ADV is ignored

### ISSUE THREAD

**Issue by ikarisan** [MarlinFirmware/Marlin#12180]
Hi!

After facing some outer wall issues on my Anet AM8 and E3Dv6 bowden I thought that I might have chosen the wrong K-factor. So I printed the test pattern for values between 0.0 and 0.58. But every line looks the same! I guess that the set value is never used. 

![img_20181021_175943](https://user-images.githubusercontent.com/14032966/47270227-e0d26500-d568-11e8-9330-4d3115d3a741.jpg)
![img_20181021_190502](https://user-images.githubusercontent.com/14032966/47270228-e0d26500-d568-11e8-84aa-7fe9ec62c4ed.jpg)
![img_20181021_193429](https://user-images.githubusercontent.com/14032966/47270229-e0d26500-d568-11e8-93f4-e18219694318.jpg)
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2499446/Configuration.zip)
[KFactor_TestPattern.zip](https://github.com/MarlinFirmware/Marlin/files/2499448/KFactor_TestPattern.zip)

I am using this version: 71e19baf691a5252841cca5871a29d7a65b62e5f

**Comment by bwgeez02** [comment]
Try setting the start kfactor at 0 and end at 2.0 in 0.2 steps.

**Comment by rb1205** [comment]
With bowden you'll probably end up around **2**, while the highest factor in your test file is 0.6.... No wonder you're hardly seeing any difference. Go [here ](http://marlinfw.org/tools/lin_advance/k-factor.html) and build a custom test for your setup that goes eg to k=4 with 0.4 steps, then do a fine tuning file once you have an idea of what factor range works best

**Comment by ikarisan** [comment]
Maybe I have to close this issue.....

A few weeks ago I printed the test pattern and the best value was around 0.30 and 0.35 (on direct extruder I was using 0.12). But now, suddenly, the optimal value seems to be around 0.85! I don't know why.... but the new value does not fix the "bad curve quality" :(

**Comment by Lyr3x** [comment]
@rb1205 Thats absolutely not the case for my Bowden setup and Lin Adv. 1.5. Nearly for all types of Filament my k factor lays about 0.8

**Comment by thinkyhead** [comment]
> But now, suddenly, the optimal value seems to be around 0.85! I don't know why

Maybe the Bowden tube is a little loose in the hotend. Try doing a "cold pull" while pulling out the Bowden tube from the hotend. Clear off all the material and jam the tube as far into the hotend as you can. See if it makes a difference. Check both ends.

**Comment by boelle** [comment]
@ikarisan problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
