### ISSUE TITLE
[bugfix-2.0.x] RepRapDiscountSmartController LCD not working with DUE + RAMPS-FD v2

### ISSUE THREAD

**Issue by rafaljot** [MarlinFirmware/Marlin#12185]
LCD looks like not initialized. Serial communication with printer works.
Hardware is ok, Repetier works without any issue.

How to reproduce:
1.  download  bug fix-2.0.x
2. modify platform.ini file: 
env_default = DUE_USB
3. configuration.h:
#define MOTHERBOARD BOARD_RAMPS_FD_V2
...
#define REPRAP_DISCOUNT_SMART_CONTROLLER
4. Compile, upload

**Comment by cjsoong** [comment]
@ @rafaljot I have no problem... check your settings.
![img_20181023_131344](https://user-images.githubusercontent.com/26795599/47338692-7be35000-d6cb-11e8-8798-3287c7c93ebb.jpg)

**Comment by rafaljot** [comment]
Hi, Could you send me or attach your configs ? Is it last bug fix-2.0 ?

**Comment by tig33r** [comment]
Rotate connectors by 180 deg.

**Comment by rafaljot** [comment]
@tig33r . Connectors are OK. It works with Repetier.

**Comment by cjsoong** [comment]
@rafaljot 
[Marlin-bugfix-2.0.x_20181013.zip](https://github.com/MarlinFirmware/Marlin/files/2506155/Marlin-bugfix-2.0.x_20181013.zip)

**Comment by rafaljot** [comment]
@cjsoong  thank you.

It is problem with compiler. 

**PlaftormIO + OSX** - compile without warnings. Printer works but LCD doesn't. 

**Arduino 1.9 + OSX** - compile error /../../../../../../Users/_USER_NAME_/Library/Arduino15/packages/arduino/hardware/sam/1.6.11/variants/arduino_due_x/libsam_sam3x8e_gcc_rel.a: No such file or directory
(it exists in this folder. Probably /../../../../../../ is a problem)

I don't know why I can compile other projects in the same configuration without this issue, Repetier for instance.

**Arduino 1.9 + Windows** - OK

**Comment by Miran81** [comment]
@cjsoong do you use ramps-fd with arduino due ? ı download your files but your platformio.ini env=megaatmega2560 ?
