### ISSUE TITLE
Redefinable PINS for E1 (extruder 2) in "pins_RAMPS.h"

### ISSUE THREAD

**Issue by RepRapMe** [MarlinFirmware/Marlin#12191]
### Description

All firmwares for Creality CR-10 printers use the board RAMPS_14_EFB and in the "pins_RAMPS.h" the PIN settings for E1 (extruder 2) is already defined.
However the mainboard of the Creality CR-10 printers do not have the extra stepper driver for E1 soldered to the board, and if you want to have a dual extruder, you need to redefine the PINs for E1 to the AUX pins on the board.
To redefine the PINs you could change the file "pins_RAMPS.h", but it will be more convenient to define them in the "configuration.h".

### Steps to Reproduce

I'll suggest to add this to the "pins_RAMPS.h":
```cpp
#ifndef E1_STEP_PIN
  #define E1_STEP_PIN      36
#endif
#ifndef E1_DIR_PIN
  #define E1_DIR_PIN       34
#endif
#ifndef E1_ENABLE_PIN
  #define E1_ENABLE_PIN    30
#endif
```

**Comment by Ludy87** [comment]
The `configuration.h` is a "developer file" and the `pin_**.h` is a "fixed" configuration of the PINs that are set only once.

**Comment by InsanityAutomation** [comment]
The CRX ships with a 2.1 board that does have these soldered in. Though the MKS 1.4 pin definition is more accurate for these than ramps, as pin 7 is used for the second hotend output on the creality boards as well.

**Comment by Roxy-3D** [comment]
It would seem to me the best path forward would be to create a Creality CR-10 pins file.

**Comment by silentninja1** [comment]
I considered that, but it would be identical to the mks 1.4 file that exists now as all it does is add pin7... Everything else it physically has is identical, as is the mks.

**Comment by tcm0116** [comment]
The new CR-10 pins file could include `pins_RAMPS.h` and the `#undef` and `#define` as needed. See `pins_RAMPS_PLUS.h` and `pins_RAMPS_ENDER_4.h` as examples.

**Comment by InsanityAutomation** [comment]
Or just make it a duplicate name for including pins_MKS_GEN_13.h - might be clearer with **its** own file, but don't want to create a ton of duplicate stuff either.

**Comment by thinkyhead** [comment]
If CR-10 is shipping with something unique, then it should get its own pins file, set up exactly as Thomas describes.

**Comment by InsanityAutomation** [comment]
Easy enough. I can whip that together pretty quick. I'll add in the servo pin definition for how the bltouch is added to enders with an itndef on the buzzer.

**Comment by TheSFReader** [comment]
I think the Ender 3 uses the same board, doesn't it ? would this pins file need to be linked from the ender 3 conf ?

**Comment by InsanityAutomation** [comment]
No, ender 3 is a melzi, same as the old cr10. Ender 4 is a different board yet, but similar to the cr10s ramps clone.

**Comment by InsanityAutomation** [comment]
FYI #12229
