### ISSUE TITLE
M84 - where are you.

### ISSUE THREAD

**Issue by RudyBenner** [MarlinFirmware/Marlin#12195]
Is M84 missing from docs for GCODES at Marlinfw.org?

**Comment by swilkens** [comment]
It does almost the same as M18, and was thus probably combined to form "M18, M84 - Disable steppers"

 - http://marlinfw.org/docs/gcode/M018.html

There's a dedicated repository for Documentation related things, you can find that here:

 - https://github.com/MarlinFirmware/MarlinDocumentation/

**Comment by RudyBenner** [comment]
Thanks.

**Comment by swilkens** [comment]
If this solves the problem for you, please close the issue :)
