### ISSUE TITLE
Personal Config Ver numbering

### ISSUE THREAD

**Issue by tip32a** [MarlinFirmware/Marlin#12213]
I have converted my Folger-tech printer from Belts to screws in both x and y and added a modified version of a wades extruder.  I am trying to dial in the settings in Marlin Configure.h.  
I am using 1.1.8 FW
My Question
Is there a way to add a small comment (a date or rev number (maybe 6 to 8 digits)) that could pop up on the LCD on some screen that I could customize each time I update the firmware with my settings.

This way I can always know what modifications are loaded.  I would keep a journal that documents the changes and their results.

Thank you.

**Comment by swilkens** [comment]
You might use `#define CUSTOM_MACHINE_NAME "foo"` for this ?

it's defined in `Configuration.h`

Or do you mean something that will live update every time you change settings without updating the firmware.

**Comment by ManuelMcLure** [comment]
You could also override `STRING_SPLASH_LINE1` which by default gives the version of Marlin (i.e. "1.1.9" or "bugfix-1.1.x").

**Comment by tip32a** [comment]
Thank you both Swilkens and ManuelMcLure.
I will test both of these this evening.

**Comment by marcio-ao** [comment]
@tip32a: What we do is we edit "Marlin/src/inc/Version.h" and change:

```
#define SHORT_BUILD_VERSION "bugfix-2.0.x"
```

To:

```
#define SHORT_BUILD_VERSION "bugfix-2.0.x" LULZBOT_FW_VERSION
```
Then in "Configuration.h" we add the following:

```
#define LULZBOT_FW_VERSION ".1"
```
