### ISSUE TITLE
bugfix_2.0 G28 homing Z_HOMING_HEIGHT not working at all 

### ISSUE THREAD

**Issue by blairq** [MarlinFirmware/Marlin#12217]
### Description

using bltouch 
 no z raise working at all , not on homing (g28 or g28z )and not between z probing so 

z_homing_height  aint working

### Steps to Reproduce

1. flash marlin 2.0 bugfix 
2. do a g28

i expect to have a litle Z raise then g28x and g28y then head moves to middle of the bed and starts moving down (g28z) .. but .. touch probe is  working fine, leds 

it should have raised Z before homing X and Y , when it tries to home Z , it deploys probe but never raises again between probes,

**Comment by blairq** [comment]
solved. not a bug, just a bugfix. maybe. 

i have set up a  Z max with my tmc2130 sensorless homing  (mechanical max, cant go higher than that) and my zmin with my bltouch. 
g28 homes at zmin with the bltouch . 

z_max_endstop_inverting was not correctly set up to true so marlin always tought it was ALREADY  at Zmax every time 

it is actually a bug i think it should be a warning on compile. but it is now working as expected becouse when im at my max z and it tries to raise a bit it should check my zmax endstop and when i build this printer the first time that thing WASNT WORKING ,  if i had my z at MAX and i did a g28 , it just raised the z and shit hit the fan HARD.

**Comment by thinkyhead** [comment]
So, we do have a sanity check for inverting and pullups to be set a certain way when using sensorless homing. Was that sanity check not correct? Or is it possible that the TMC’s threshold error pin is not connected to the proper endstop plug, or that sensorless homing sensitivity was set so low as to always be triggered?

**Comment by blairq** [comment]
wiring was fine.

i think marlin is goeing away from using tmc on z axis so that may be the reason there are no checks for this.
there may  be a check like in x and y sensorles homing who tells you must set z_(max||min)_endstop_inverting must be on if using tmc sensorless homing (on Z)

**Comment by thinkyhead** [comment]
```cpp
#if ENABLED(SENSORLESS_HOMING)
  . . .
  #elif Z_SENSORLESS && Z_HOME_DIR == -1 && (!Z_MIN_ENDSTOP_INVERTING || DISABLED(ENDSTOPPULLUP_ZMIN))
    #error "SENSORLESS_HOMING requires Z_MIN_ENDSTOP_INVERTING and ENDSTOPPULLUP_ZMIN when homing to Z_MIN."
  #elif Z_SENSORLESS && Z_HOME_DIR ==  1 && (!Z_MAX_ENDSTOP_INVERTING || DISABLED(ENDSTOPPULLUP_ZMAX))
    #error "SENSORLESS_HOMING requires Z_MAX_ENDSTOP_INVERTING and ENDSTOPPULLUP_ZMAX when homing to Z_MAX."
  . . .
#endif
```

**Comment by boelle** [comment]
@blairq problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
