### ISSUE TITLE
Question on lcd_implementation_status_screen ?

### ISSUE THREAD

**Issue by fred2088** [MarlinFirmware/Marlin#12223]
Dear sirs,

we changed the lcd_implementation_status_screen() function from 1.1.x to make a custom status screen,

can't figure out which point to edit from 2.0.x

would you point me to the correct place ?

TIA

**Comment by thinkyhead** [comment]
![image](https://user-images.githubusercontent.com/698003/47559640-a277d580-d8db-11e8-84e1-496157053e91.png)

**Comment by fred2088** [comment]
thanks a lot,
the structure between 1.x and 2.0.x is a lot different
do 2.0.x support two status screen ?

**Comment by thinkyhead** [comment]
Two styles. Character displays only. Ciao!
