### ISSUE TITLE
Question on how to edit files from src ?

### ISSUE THREAD

**Issue by fred2088** [MarlinFirmware/Marlin#12221]
how to edit files from arduino IDE while all source file are in src <marlin 2.0>?
a new file is added to marlin.ino folder if selected sketch->add file, but it's not compiled ?

**Comment by thinkyhead** [comment]
Don't use Arduino IDE as an editor. That way lies madness.

**Comment by fred2088** [comment]
which editor suggested ? thanks

**Comment by thinkyhead** [comment]
Sublime Text 3, Notepad++, TextMate, Visual Studio Code, Atom, https://www.google.com/search?q=free+text+and+project+editors

**Comment by AnHardt** [comment]
The one you are used to. ;-)

**Comment by fred2088** [comment]
trying notepad++ x64, which no need to install, thanks
