### ISSUE TITLE
[Bugfix 2.0] Compile error due to MSG_HOTEND_TOO_COLD

### ISSUE THREAD

**Issue by Bergerac56** [MarlinFirmware/Marlin#12222]
I get a compile error with bugfix 2.0 : dacb5324e80b1725208dd034c5ea74ede356be56
To solve it, ultralcd.cpp needs a modification:
```cpp
#if ENABLED(PREVENT_COLD_EXTRUSION)
      if (axis == E_AXIS && thermalManager.tooColdToExtrude(eindex >= 0 ? eindex : active_extruder))
        MENU_BACK(**MSG_HOTEND_TOO_COLD**);
      else
    #endif
```
by
```
#if ENABLED(PREVENT_COLD_EXTRUSION)
      if (axis == E_AXIS && thermalManager.tooColdToExtrude(eindex >= 0 ? eindex : active_extruder))
        MENU_BACK(**MSG_ERR_HOTEND_TOO_COLD**);
      else
    #endif
```

**Comment by thinkyhead** [comment]
This was patched yesterday. `MSG_HOTEND_TOO_COLD` is defined in `language_en.h`. Try quitting and restarting Arduino IDE.

**Comment by Bergerac56** [comment]
@thinkyhead You are right. As I use a file language_en.h modified a long time ago, I forgot to see if no changes there. Sorry for that
