### ISSUE TITLE
Error in Marlin 2.0 - endstops - error: missing binary operator before token "("

### ISSUE THREAD

**Issue by TomTom076** [MarlinFirmware/Marlin#12235]
I used latest Marlin 2.0 fw with ATOM for a MKS SBASE 1.3. Build failed!
See error message in file.
Please HELP!
Thanks!
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/2521610/Config.zip)
![error atom 27102018](https://user-images.githubusercontent.com/44521147/47601909-3c707880-d9d7-11e8-86cf-092a57358bd9.jpg)

**Comment by Ludy87** [comment]
Update your Version https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

**Comment by TomTom076** [comment]
thanks.
i tried it with the link and the new fw, but nothing changed, error again.
Any ideas?

**Comment by p3p** [comment]
Make sure all the platformio packages/libraries are up to date, if that fails delete the platformio cache folder `%user%\.platformio` on windows.

**Comment by forkoz** [comment]
Here is the fix: https://github.com/MarlinFirmware/Marlin/issues/12166

**Comment by thinkyhead** [comment]
The only error I get with your configs and the current `bugfix-2.0.x` is this:
![image](https://user-images.githubusercontent.com/698003/47626729-928a0c80-dafa-11e8-9845-c6d9530b7117.png)

**Comment by forkoz** [comment]
He didn't include his pins file. I had the same error when they were interrupt capable pins. Probably needs PR to fix.

**Comment by boelle** [comment]
@TomTom076 problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
