### ISSUE TITLE
Gcode command "M420 Z" I need an explanation

### ISSUE THREAD

**Issue by marcovignotto** [MarlinFirmware/Marlin#12236]
Hi Everybody!
Since a while I installed the BLTouch sensor and I´m really sattisfied.
After the tunning I use the "M420 S1" command to use the grid and works.
I got that command spreads the leveling in the all height, for example on 10mm height a bit on the first layer and then the second, the third and so on till the end.

But what does the "M420 Z" command?
from the guide:

[Z<linear>] "Leveling fade Z height"

There are not so many examples about it and I got that has to be used with millimeters 
ex: "M420 Z1" means one millimeter
My interpretation is that it levels in 1 millimter instead the all height.
Is it like that?
Any experience?

Thanks in advance

**Comment by GMagician** [comment]
AFAIK It should reduce Z mesh correction and after specified height such correction is 0

**Comment by marcovignotto** [comment]
hi!
Thanks for the reply!
Can you please explain better? (I´m a newbie)

**Comment by gauix4** [comment]
this is the height between the sensor and the nozzle

**Comment by marcovignotto** [comment]
ah ok!
So I didn´t get it at all... 
thanks a lot!

**Comment by kAdonis** [comment]
> this is the height between the sensor and the nozzle

No, thats not true
@GMagician  has explained it correctly

**Comment by marcovignotto** [comment]
@kAdonis can you please clarify?
thanks

**Comment by kAdonis** [comment]
you create a mesh so that the nozzle follows the not perfectly flat bed
the applied correction gets smaller (Faded) every layer until the Leveling fade Z height is reached
okay?
