### ISSUE TITLE
using g-code in function

### ISSUE THREAD

**Issue by pisagor** [MarlinFirmware/Marlin#1223]
Hi i am trying to add specific functions in my prusa. I want to add filament change (upload)command on lcd screen. 
i am thinking like this=

Select change filament > extruder heating > running extruder motor (feed filament)> Done!

So i added this function in ultralcd.cpp

void filament_change()
{
      setTargetHotend0(plaPreheatHotendTemp);
      PSTR(G1 E20);
}

plaPreheat temprature work well but g comment is not working. How can i do that?

Sory for my english. 

Thanks.

**Comment by CONSULitAS** [comment]
@pisagor I think your Feature request should be resolved with PR #1423.

You could start any sequence of GCODE from LCD.

Please have a look and test if appropriate. Thanks for your feedback.

**Comment by boelle** [comment]
as this have been resolved and initial poster have made no new comments i will close this one

**Comment by thinkyhead** [comment]
Plus we now have a filament change function, and an even more fancy set of filament change functions pending after this round of bug fixes.

**Comment by schirrel** [comment]
hey @thinkyhead i was trying to implement change filament function when i read this. I also saw a part of code with this from #1423 
Where is this function of filament change, cuz o didn't found it :S

**Comment by KiteLab** [comment]
Grrrx tch tch p n't ~~release~~ u n ~~1.0.x~~ b! RC  RCBgFx expl https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/Marlin_main.cpp#L2669 Tschschsch!

Prt didel M600 dit https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/Marlin_main.cpp#L5296 Chrrr @!#?ß@

**Comment by Wackerbarth** [comment]
@KiteLab -- ???   En ingles, por favor.
