### ISSUE TITLE
H-Bot/CoreXY axis direction issues

### ISSUE THREAD

**Issue by FlailAway** [MarlinFirmware/Marlin#12244]
I am building an H-Bot and have configured marlin 1.1.9 as such. I can get the Alpha(X) and Beta(Y) axis to manually move (Prepare/Move Axis) in the correct directions but then Homing goes bananas.

Homing switches at front/Left.
G28 X0 Homes the Alpha correctly
G28 Y0 Homes the Beta correctly

Using G28 will first Home Alpha and then try Beta. Instead of the Beta going to the switch, it goes away from it in the "+" direction. It hits the end "+" of travel, rattles for a second or two then Homes correctly.

Can anyone/someone please point me at somewhere that shows the Configuration.h set up for H-Bot, as clearly, the basic CoreXY settings are not cutting it. I have tried all the connector swap combinations and nothing is improving it.

Thanks

**Comment by rjacobs1969** [comment]
I'm building a mini coreXY printer and had some problems with directions and homing. But after some try and error I found the correct settings. 

When X/Y is moving in the correct directions but homing isn´t check out the 
X_HOME_DIR and Y_HOME_DIR settings
Also check X_MIN_ENDSTOP_INVERTING / Y_MIN_ENDSTOP_INVERTING having these wrong also give strange homing behaviour

**Comment by towe96** [comment]
According to my short research, H-Bot has one axis inverted compared to CoreXY.
The homing direction settings comes to mind, or perhaps the CoreYX motion setting.

**Comment by Gav-in** [comment]
I had similar issues with my d-bot, and had to change INVERT_Y_DIR in the firmware before swapping/flipping stepper cables worked.

**Comment by boelle** [comment]
@FlailAway 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
