### ISSUE TITLE
"Error: Hotend too cold" on connection to the printer

### ISSUE THREAD

**Issue by flcu** [MarlinFirmware/Marlin#12253]
### Description

Receving "Hotend too cold" Error Message on connecting to the printer in Replicator-GUI

### Steps to Reproduce

I simply connect to my printer, then the error message appears. Connect Log from replicator attached.

**Expected behavior:** Connecting to the printer without an error message

**Actual behavior:** I get an annoying replicator alert on connect

I'm using a mixing extruder with 2 extruders and one hotend. I've traced the error message to the tool_change.cpp and I'm suspecting that somehow a tool change is triggered/attemped at connect?

The printer works fine afterwards, as the temperature reading and everything works fine?

I'm using Marlin Bugfix-2.0.x from 28.10.2018

#### Additional Information
[20181028_err_log_connect_too_cold.log](https://github.com/MarlinFirmware/Marlin/files/2522608/20181028_err_log_connect_too_cold.log)
[20181028_config_error_too_cold.zip](https://github.com/MarlinFirmware/Marlin/files/2522606/20181028_config_error_too_cold.zip)

**Comment by thinkyhead** [comment]
@InsanityAutomation — This machine tries to do a tool-change on startup. And it's a `SINGLENOZZLE`. So it's invoking the filament swap and throwing an error. Re-check the tool-change code for `SINGLENOZZLE` to see whether it's trying to invoke a filament swap when it shouldn't be. Clearly there are occasions when users will want to do a tool-change with a `SINGLENOZZLE` setup but not swap filaments.

**Comment by thinkyhead** [comment]
Meanwhile, @flcu — Change your `SINGLENOZZLE_SWAP_LENGTH` to 0.

**Comment by flcu** [comment]
@thinkyhead: this solves at least the error message, thank you - as I'm not using any toolchange functionality at the moment not an issue for me.

**Comment by InsanityAutomation** [comment]
Good morning, I'll take a closer look shortly, but in the meantime can you try the updated set of code at https://github.com/MarlinFirmware/Marlin/pull/12137

**Comment by thinkyhead** [comment]
You can close this if the original issue is solved.

**Comment by boelle** [comment]
@flcu 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one

**Comment by flcu** [comment]
Sorry guys, I've since switched hardware and software. The proposed fix "Change your SINGLENOZZLE_SWAP_LENGTH to 0." worked even though it's probabely not correct (as the length for a swap is different)...
