### ISSUE TITLE
sbase Marlin 2.0 Error: Detected unknown package 'framework-arduino-lpc176x'

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#12251]
I was trying to compile Marlin 2.0 for my sbase tonight, and I always get 
```
Processing LPC1768 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x
/archive/master.zip; board: nxp_lpc1768; framework: arduino)
-------------------------------------------------------------------------------
-
PackageManager: Installing framework-arduino-lpc176x @ >=0.0.2
Error: Detected unknown package 'framework-arduino-lpc176x'
```
I made change to the platformio.ini file as the env_default= LPC1768
and all necessary change in Configuration.h
with/without a sbase board connected.

Have no success, :-(, advice is really appreciated.

**Comment by gauix4** [comment]
https://youtu.be/gMPdsBumWCQ

**Comment by gauix4** [comment]
If you run pio update in the atom terminal what version of framework-arduino-lpc176x are you running,

**Comment by ghost** [comment]
it compiles now, I suspect my pfsense blocked something.

**Comment by InsanityAutomation** [comment]
Must've forgotten to sacrifice an old freebsd beastie before downloading technical things....

**Comment by gauix4** [comment]
so you can close this request Thank you
