### ISSUE TITLE
[FR] Store user parameters in EEPROM

### ISSUE THREAD

**Issue by mr-miky** [MarlinFirmware/Marlin#12255]
In the board I built I included the possibility that the printer provides the + 5V to a "device" aka orangePI / Raspberry through the USB connector, a kind of USB Otg.
The chip that limits the current and acts as a switch has a control connection which for the moment I control directly via digitalWrite () during setup ().
My intention would be to add an item on the menu that allows me to activate / deactivate the power supply to the USB. It is not a big problem because it is enough to imitate the lighting control. The problem is that I would like to save the state on EEprom and maybe dedicate a specific Gcode but keep the compatibility with the standard eeprom structure and without creating conflicts with GCodes.

**Comment by thinkyhead** [comment]
Follow the bouncing code. There are examples galore in the Marlin source code of G-codes that change parameters and of saving and loading those parameters from EEPROM.

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and production-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration, troubleshooting, and customization please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
