### ISSUE TITLE
undefined reference to `SdFatUtil::__brkval'

### ISSUE THREAD

**Issue by Nutz95** [MarlinFirmware/Marlin#1225]
Hello, i'v just downloaded the last marlin version (commit fe8d8beb7a9c5288a0fe4beb32bbf32bf93e923e) and when i enable either SDSUPPORT or REPRAP_DISCOUNT_SMART_CONTROLLER  i get this foliwng error on compilation:

SdFatUtil.cpp.o: In function `SdFatUtil::SerialPrintln_P(char const*)':
SdFatUtil.cpp:77: undefined reference to `SdFatUtil::__brkval'
SdFatUtil.cpp:77: undefined reference to `SdFatUtil::__brkval'
SdFatUtil.cpp:77: undefined reference to `SdFatUtil::__bss_end'
SdFatUtil.cpp:77: undefined reference to `SdFatUtil::__bss_end'
collect2: error: ld returned 1 exit status

I tried to download and update the SDFatUtil library but i still get this issue.
And when i get back to a previous version of marlin with the same defines enabled i can compile properly. Somehow i feel there is a regretion somewhere on this side.

I've also tried to download the "stable" version of marlin and yet still the same issue

Any idea?

**Comment by boelle** [comment]
closing as it should have been fixed with  PR #1228
