### ISSUE TITLE
Linear Advance 1.5 Causing Print To Stop

### ISSUE THREAD

**Issue by inventabuild** [MarlinFirmware/Marlin#12250]
I'm using Marlin 1.1.9 with LA 1.5 and K = 0.6 with my bowden extruder and it's causing my prints to pause mid-print: https://youtu.be/EYoc8PGj3Tw

Any idea what causes this?

**Comment by Sebastianv650** [comment]
Is this repeatable at this specific point in the gcode? If so, try to isolate the corresponding gcode lines and also try them with K=0 to see if that changes anything. Then please post your config files together with the gcode sniplet.

**Comment by swilkens** [comment]
Are you using USB / Serial connection to print? (i.e. from PC, via octoprint or similar)

If so, the buffer may simply be running out or you are experiencing communication issues. If this is the case, place the file on an SD card and attempt the print again.

**Comment by thinkyhead** [comment]
Do you happen to be using Simplify3D as your slicer? There's a known issue where it will add very small and very slow retractions that make the printer seem like it's pausing.

**Comment by inventabuild** [comment]
Hey thinkyhead, you nailed it!

With Linear Advance turned off S3D was still retracting real slow at repeatable points. On the following print at layer height 1.25 mm at the edge retraction points I got the slow retracts:

![simplify3d_retraction_issue_e-1_f3](https://user-images.githubusercontent.com/5142713/48034787-5e2fd500-e126-11e8-85b5-3d682f534e24.JPG)

Here's what the gcode looks like in that area (look at all those E-1 F3):

G1 Z1.250 F180
G1 E1.0000 F600
G1 X141.298 Y175.798 E0.0003 F2376
G1 X141.302 Y175.802 E-1.0000 F3
G1 Z1.350 F180
G1 X143.298 Y175.465 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X143.302 Y175.469 E0.0003 F2376
G1 X143.298 Y175.465 E-1.0000 F3
G1 Z1.350 F180
G1 X147.298 Y175.575 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X147.302 Y175.579 E0.0003 F2376
G1 X147.298 Y175.575 E-1.0000 F3
G1 Z1.350 F180
G1 X149.301 Y175.245 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 E-1.0000 F600
G1 Z1.350 F180
G1 X151.298 Y175.686 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X151.302 Y175.690 E0.0003 F2376
G1 X151.298 Y175.686 E-1.0000 F3
G1 Z1.350 F180
G1 X153.298 Y175.353 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X153.302 Y175.357 E0.0003 F2376
G1 X153.298 Y175.353 E-1.0000 F3
G1 Z1.350 F180
G1 X155.298 Y175.797 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X155.302 Y175.801 E0.0003 F2376
G1 X155.298 Y175.797 E-1.0000 F3
G1 Z1.350 F180
G1 X157.298 Y175.464 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X157.302 Y175.468 E0.0003 F2376
G1 X157.298 Y175.464 E-1.0000 F3
G1 Z1.350 F180
G1 X161.298 Y175.575 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X161.302 Y175.579 E0.0003 F2376
G1 X161.298 Y175.575 E-1.0000 F3
G1 Z1.350 F180
G1 X163.301 Y175.245 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 E-1.0000 F600
G1 Z1.350 F180
G1 X165.298 Y175.686 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X165.302 Y175.690 E0.0003 F2376
G1 X165.298 Y175.686 E-1.0000 F3
G1 Z1.350 F180
G1 X167.298 Y175.352 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X167.302 Y175.356 E0.0003 F2376
G1 X167.298 Y175.352 E-1.0000 F3
G1 Z1.350 F180
G1 X169.298 Y175.797 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X169.302 Y175.801 E0.0003 F2376
G1 X169.298 Y175.797 E-1.0000 F3
G1 Z1.350 F180
G1 X171.298 Y175.463 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X171.302 Y175.467 E0.0003 F2376
G1 X171.298 Y175.463 E-1.0000 F3
G1 Z1.350 F180
G1 X175.298 Y175.574 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X175.302 Y175.578 E0.0003 F2376
G1 X175.298 Y175.574 E-1.0000 F3
G1 Z1.350 F180
G1 X179.298 Y175.685 F10800
G1 Z1.250 F180
G1 E1.0000 F600
G1 X179.302 Y175.689 E0.0003 F2376
G1 X179.298 Y175.685 E-1.0000 F3
G1 Z1.350 F180
; solid layer

Looks like I'll need to start using another slicer until S3D sorts the bug out.

**Comment by boelle** [comment]
@inventabuild problem solved with latest bugfix 2.0 ?

**Comment by inventabuild** [comment]
Simplify 3D v4.1.1 appears to have fixed the problem.

**Comment by boelle** [comment]
then click close below
