### ISSUE TITLE
[2.0.x] Status message cut-off vertically

### ISSUE THREAD

**Issue by swilkens** [MarlinFirmware/Marlin#12268]
### Description

The status message appears to be positioned too low on the LCD screen, causing a cut-off. 

To a layman's eye, it seems there is enough separation between the progress bar and the status message to move the status message up and prevent this.

![naamloos](https://user-images.githubusercontent.com/13329383/47661108-ac7a2c80-db98-11e8-8fc0-741a52dd371c.png)

#### Additional Information

- Running current bugfix-2.0.x, up to https://github.com/MarlinFirmware/Marlin/tree/5ead0269676b80292a360e5b132204ebecdc40a5

 - Ender 3 Pro config

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/2525922/Configuration_adv.zip)

**Comment by gloomyandy** [comment]
See this PR https://github.com/MarlinFirmware/Marlin/pull/12224

**Comment by swilkens** [comment]
Thanks, I'll keep an eye on it!

**Comment by thinkyhead** [comment]
Patch merged.
