### ISSUE TITLE
[bugfix-2.0.x] MKS SBASE halt on E movement after M164

### ISSUE THREAD

**Issue by Gav-in** [MarlinFirmware/Marlin#12278]
### Description

On the MKS SBASE v1.3, any attempt to move a virtual extruder after setting the mixing ratio with M164 makes the firmware/lcd unresponsive.
### Steps to Reproduce

1. Configure bugfix-2.0.x for BOARD_MKS_SBASE, and #define MIXING_EXTRUDER with any number of physical and virtual extruders.
2. Boot the firmware, and execute g-code that prints using all virtual extruders.
3. Add the following to the start of the g-code, and run it again.
     M163 S0 P1.00; Cyan factor
     M163 S1 P0.00; Magenta factor
     M163 S2 P0.00; Yellow factor
     M163 S3 P0.00; Black factor
     M163 S4 P0.00; White factor
     M164 S6; Save mixture to tool 6

**Expected behavior:** [What you expect to happen]
The M164 in the above example should replace the default mixture for virtual tool 6 with a user-defined mixture (which is actually the same color), so the print should be identical with or without the changes.

**Actual behavior:** [What actually happens]
The program proceeds normally until the user-modified virtual tool is issued a move instruction, at which point the system becomes unresponsive.

#### Additional Information
M163/M164/M165 were all working with 5 physical/256 virtual extruders on the SBASE and bugfix-2.0.x until a couple of weeks ago, when RETRACT_SYNC_MIXING was added, along with shared hardware spi for the lcd/sd.  There are many compiler warnings.

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/2532264/Config.zip)

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by AnHardt** [comment]
Before the `M164 S6` `T6` prints normal? (Just to decrease the search radius.)

Please add `#define MIXER_NORMALIZER_DEBUG` in `Configuration.h`. Will this give any useful hints? Please paste the output of
```
M163 S0 P1.00; Cyan factor
M163 S1 P0.00; Magenta factor
M163 S2 P0.00; Yellow factor
M163 S3 P0.00; Black factor
M163 S4 P0.00; White factor
M164 S6; Save mixture to tool 6
```

**Comment by AnHardt** [comment]
> 5 physical/256 virtual extruders

V-tools are limited to 1-255. If `RETRACT_SYNC_MIXING` is defined 1-254. The 'retract tool' should not be selectable by T or M164. (tool number is a uint8_t. 256 will not fit in)

**Comment by AnHardt** [comment]
On Oct 16, 2018 we had a major update of the Mixing Extruders (#12098). If not already beyond, please update.

**Comment by Gav-in** [comment]
Yes, at boot T5 and above print normally using E0, as intended, and T0-4 use E0-4.  The debugging output shows M164 changing all factors to zero:

06:03:18.901 : Mixer: Relation before normalizing: [ 1.000 0.000 0.000 0.000 0.000 ]
06:03:18.901 : Mixer: Normalizing to             : [ 0 0 0 0 0 ]
06:03:18.901 : Mixer: Relation after normalizing:  [ nan nan nan nan nan ]

I never tried to use all of the 256 tools I enabled, but it did compile, and I did reduce it to 16 for testing when an issue arose.

The Oct 16 update of the Mixing Extruders is when the issue arose.  Mixing has not worked with any configuration options since then, though RETRACT_SYNC_MIXING works quite well.  Compiler warnings that appeared at the time include:
```
 Marlin\src\HAL\HAL_LPC1768\u8g\u8g_com_HAL_LPC1768_ssd_hw_i2c.cpp: In function 'uint8_t u8g_com_HAL_LPC1768_ssd_hw_i2c_fn(u8g_t*, uint8_t, uint8_t, void*)':
Marlin\src\HAL\HAL_LPC1768\u8g\u8g_com_HAL_LPC1768_ssd_hw_i2c.cpp:159:27: warning: ISO C++1z does not allow 'register' storage class specifier [-Wregister]
register uint8_t *ptr = (uint8_t *)arg_ptr;
^~~
Marlin\src\HAL\HAL_LPC1768\u8g\u8g_com_HAL_LPC1768_ssd_hw_i2c.cpp:178:27: warning: ISO C++1z does not allow 'register' storage class specifier [-Wregister]
register uint8_t *ptr = (uint8_t *)arg_ptr;
^~~

In file included from Marlin\src\module/planner.h:51:0,
from Marlin\src\Marlin.cpp:35:
Marlin\src\module/../feature/mixing.h: In static member function 'static uint8_t Mixer::get_next_stepper()':
Marlin\src\module/../feature/mixing.h:36:34: warning: integer overflow in expression [-Woverflow]
#define COLOR_MASK (COLOR_A_MASK - 1)                   // 0x7F or 0x7FFF
Marlin\src\module/../feature/mixing.h:87:25: note: in expansion of macro 'COLOR_MASK'
accu[runner] &= COLOR_MASK;
^~~~~~~~~~
```
Thanks for investigating the issue!

**Comment by AnHardt** [comment]
Please try PR #12293

**Comment by Gav-in** [comment]
Thank you so much!  I thoroughly tested all mixing functions, and everything works as described (except 254 virtual tools fails the check, lol.) I greatly appreciate the swift resolution.
