### ISSUE TITLE
[2.0.x] Compile error: ultralcd.cpp:397:23: error: 'progress_bar_ms' was not declared in this scope

### ISSUE THREAD

**Issue by dahuafschmied** [MarlinFirmware/Marlin#12271]
### Description

compile error in lastest version of marlin 2

### Steps to Reproduce

use my repro (actual marlin 2):
https://github.com/dahuafschmied/Marlin-for-Anycubic-i3-Mega/tree/bugfix-2.0.x

compile it....
progress_bar_ms is not declared in ultralcd.cpp

**Comment by dahuafschmied** [comment]
and this error:
ultralcd.cpp:719:7: error: too many arguments to function 'void lcd_implementation_init()'

**Comment by thinkyhead** [comment]
Could you post your configuration files, as requested in the template, so that we can more easily compile and test with your enabled options? Thanks!
