### ISSUE TITLE
[bugfix 2.0.x]  No values for X,Y&Z on full graphic LCD 

### ISSUE THREAD

**Issue by Bergerac56** [MarlinFirmware/Marlin#12274]
With the last bugfix 553622835911b520c6ba43bc03e71868f3972cb3 ( mks_sbase and full graphic LCD), there are no values appearing for X Y and Z on the info screen anymore. (And no blinking question marks when printer not yet "homed")

It seems to have been introduced in the long chain of changes made for the refactor of lcd menu (2bf18950ab2070e842c91057d5812dcaa1bff9a2).

**Comment by mr-miky** [comment]
I had noticed it too yesterday but then I forgot to report it

**Comment by gloomyandy** [comment]
Yep I'm seeing the same. I'm also using MKS SBase and full graphic LCD). Other values (like temperatures) are displayed and update when changed, the fan animation also works.

**Comment by gloomyandy** [comment]
@thinkyhead do you have a handle on this, or is it worth me spending some time trying to work out what the problem is?

**Comment by mr-miky** [comment]
in status_screen_DOGM.cpp line 406

```cpp
  // At the first page, regenerate the XYZ strings
  if (page.page == 0) {
    strcpy(xstring, ftostr4sign(LOGICAL_X_POSITION(current_position[X_AXIS])));
    strcpy(ystring, ftostr4sign(LOGICAL_Y_POSITION(current_position[Y_AXIS])));
    strcpy(zstring, ftostr52sp(LOGICAL_Z_POSITION(current_position[Z_AXIS])));
    #if ENABLED(FILAMENT_LCD_DISPLAY)
      strcpy(wstring, ftostr12ns(filament_width_meas));
      strcpy(mstring, itostr3(100.0 * (
          parser.volumetric_enabled
            ? planner.volumetric_area_nominal / planner.volumetric_multiplier[FILAMENT_SENSOR_EXTRUDER_NUM]
            : planner.volumetric_multiplier[FILAMENT_SENSOR_EXTRUDER_NUM]
        )
      ));
    #endif
  }
```


**page.page** is always 33 aka 0x21 .... 
 so "if" always fail and do not print coords.

**Comment by mr-miky** [comment]
Maybe this is the solution to the problem?
Check **first_page** instead of **page.page**

```cpp
  // At the first page, regenerate the XYZ strings
    if (first_page) {
//  if (page.page == 0) {
    strcpy(xstring, ftostr4sign(LOGICAL_X_POSITION(current_position[X_AXIS])));
    strcpy(ystring, ftostr4sign(LOGICAL_Y_POSITION(current_position[Y_AXIS])));
    strcpy(zstring, ftostr52sp(LOGICAL_Z_POSITION(current_position[Z_AXIS])));
    #if ENABLED(FILAMENT_LCD_DISPLAY)
      strcpy(wstring, ftostr12ns(filament_width_meas));
      strcpy(mstring, itostr3(100.0 * (
          parser.volumetric_enabled
            ? planner.volumetric_area_nominal / planner.volumetric_multiplier[FILAMENT_SENSOR_EXTRUDER_NUM]
            : planner.volumetric_multiplier[FILAMENT_SENSOR_EXTRUDER_NUM]
        )
      ));
    #endif
  }
```

**Comment by thinkyhead** [comment]
I just uploaded `bugfix-2.0.x` to my RAMPS board with graphical display and it's working fine for me.

**Comment by gloomyandy** [comment]
Yep all working for me now. Thanks.

**Comment by Bergerac56** [comment]
Works for me too
