### ISSUE TITLE
Corexy Y- Axis homing correctly but homing to wrong direction when auto homing

### ISSUE THREAD

**Issue by Louis-Cypher** [MarlinFirmware/Marlin#12287]
### Description

After Upgrading to Marlin 2.0.x I checked direction of motion for all axes of my printer (corexy; sparkcube derivate) as well as endstops. The printer homes correctly in case x and y axis is homed separately. As soon as i do an atuohome or G28. The printer homes x correctly but y is homed to the wrong direction (opposite direction of direction uses when homing y separately.  

### Steps to Reproduce

1. Home to y 
2. G28
3. fix broken parts ;-)

**Expected behavior:** Home to direction of single axis homing
**Actual behavior:** Homes to opposite direction

#### Additional Information
- I have very coarse motions on x and y wheras z is running as expected.
- I converted my config using marlin-config
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/2536598/configs.zip)

**Comment by Ludy87** [comment]
INVERT Y true

**Comment by Louis-Cypher** [comment]
Thanks, a lot. This would change my y- axis direction as well, right? Why does this only affect homing when doing autohome but not homing y? I'm still confused

BTW: This configuration printed more than 20kg of filament. Hence, I think it still should work

**Comment by Ludy87** [comment]
execute G0 Y50 and see if all right

**Comment by Louis-Cypher** [comment]
I already did that. Axis is moving to the right direction and endstop is in right direction. As I already pointed out homing of single axis (all of them!) works, autohome doesn't

**Comment by Louis-Cypher** [comment]
Inverting Y messes up axis direction as expected

**Comment by Louis-Cypher** [comment]
In my opinion homing of single axis has to happen in the same direction autohoming uses. Maybe I'm wrong...

**Comment by Louis-Cypher** [comment]
I cleared EEPROM once more and the problem is gone
