### ISSUE TITLE
BLTouch not Auto Homing on Tevo Tornado

### ISSUE THREAD

**Issue by Megladon7** [MarlinFirmware/Marlin#12296]
Updated to marlin 2.0 and when I try to auto home it moves to xy home fine but wont move down towards bed. The probe just goes in and out. I have the BLTouch from Antclabs and the wiring is correct. I have made sure my settings for z endstop are correct. I can make the probe go in and out and self test works great. Pulling my hair out trying to get this to work. 

See attached zip with cofig files. 

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2539020/Marlin.zip)

Fixed: -Z pin was falling out. Disregard or delete.

**Comment by TheSFReader** [comment]
I think you can close the issue, that would be easier ;-)
