### ISSUE TITLE
M600 added to sketch now marlin says sketch is to large not enough space. How do I fix please.

### ISSUE THREAD

**Issue by xfuzz** [MarlinFirmware/Marlin#12298]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by swilkens** [comment]
We need to know, at the very least:

- Which version of Marlin you are using
- The exact error output of the compiler
- Your printer make and model
- Your current configuration (configuration.h and configuration_adv.h)

As a first suggestion, here are some typical things you can disable to make space without losing anything dramatic:

- `#define ARC_SUPPORT` in `Configuration_adh.h`
- `#define SHOW_BOOTSCREEN` in `Configuration.h`

If they are enabled for your printer:
- `#define SHOW_CUSTOM_BOOTSCREEN` in `Configuration.h`
- `#define CUSTOM_STATUS_SCREEN_IMAGE` in `Configuration.h`

Typically, these kind of questions are best asked on:

- The official Marlin facebook group (https://www.facebook.com/groups/1049718498464482/)
- The facebook group for your specific printer
- The reddit group for your specific printer

**Comment by Roxy-3D** [comment]
Up above it says to attach:  Your current configuration (configuration.h and configuration_adv.h)
