### ISSUE TITLE
Pt100 with mks sbase always shows 300c

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#12309]
I tried to set #define TEMP_SENSOR_0  to 147 or 110, but nothing changed
the hotend temp is always 300 when the printer is turned on.
(the good thing is I know the temp controlled fan is working, when it sees 300c, it starts right away, lol)

I am connecting the pt100 directly to my board without amplifier, it was working with smoothies board so I assume the hardware still works just fine, maybe I missed something again in configuration?here is the config file.
thanks.

I think I should also include that the pt100 is from aliexpress.

and I read from e3d website 
Boards that do support PT100 sensors without an amplifier board include:
Ultimaker 2 electronics
Duet Wifi and Duet Ethernet, with PT100 daughter board 
Duet 0.6 and 0.8.5, with third-party digital PT100 interface board 

so amplifier is required?

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2544097/Configuration.zip)

**Comment by gloomyandy** [comment]
Just to clarify... You had this working with smoothieware using the same control board and the same temperature sensor? Have you changed any other hardware when switching to Marlin from smoothieware (for instance are you using a different display)?

How exactly have you connected the senor to your board, what pins are you using?

**Comment by ghost** [comment]
I don't change any hardware, not a single connection, I just plug the Pt100  xh2.54 2-pin connector to TH2 and follow the instruction found here http://forum.smoothieware.org/pt100 with Un-amplified PT100
It gives about the same temp on screen as my heated bed, and I autopid it and used it for some prints in PLA just fine.

**Comment by gloomyandy** [comment]
So when printing PLA what temperature readings did you get when running smoothieware? 

Unfortunately I don't have a pt100 so can't really test anything for you. But I don't see why there should be any sort of issue with using it with the SBase hardware given that you seem to have it working with Smoothieware. One thing I'm not sure about is how well Marlin is configured for the unamplified pt100, perhaps someone using it on another control board could comment?

**Comment by ghost** [comment]
```
temperature_control.hotend.enable              true
temperature_control.hotend.sensor              pt100
temperature_control.hotend.pt100linear         1
temperature_control.hotend.thermistor_pin      0.23
temperature_control.hotend.ampmod1_pin         nc
temperature_control.hotend.ampmod2_pin         nc
temperature_control.hotend.slope               0.0523809524 #slope for e3d pt100 amp
temperature_control.hotend.yintercept         -299.6        #yintercept for e3d pt100 amp
```
I have some lines in smoothies config,

and I found 
```cpp
#define PtA 3.9083E-3
#define PtB -5.775E-7
#define PtRt(T,R0) ((R0)*(1.0+(PtA)*(T)+(PtB)*(T)*(T)))
#define PtAdVal(T,R0,Rup) (short)(1024/(Rup/PtRt(T,R0)+1))
#define PtLine(T,R0,Rup) { OV(PtAdVal(T,R0,Rup)), T },
```
in marlin,  but I haven't figured out the correct formula to get it work.

**Comment by gloomyandy** [comment]
This thread may help...
https://github.com/MarlinFirmware/Marlin/issues/2912#issuecomment-268478912
the stuff about the pt100 starts about half way down. The thread gives new values for the Marlin table used to handle the device, you may want to try them. Good Luck! Please update this issue with how you get on.

**Comment by ghost** [comment]
sure I will try that out, in the meantime I found the formula that smoothie use for a liner relation
T = slope * ADC + yintersect when the PT100 is connect without an amplifier
wondering if this can be implemented in marlin in some way.

**Comment by ghost** [comment]
I just changed the thermister 147 file to
```
  PtLine(0,341,0)
  PtLine(50,406,0)
  PtLine(100,469,0)
  PtLine(150,531,0)
  PtLine(200,591,0)
  PtLine(250,650,0)
  PtLine(300,707,0)
  PtLine(350,763,0)
  PtLine(400,818,0)
```
and I got `E1 Err: maxtemp printer  halted`
if I use 4k7 pull up, I get temp of 400 instead of 300.....
I think I either change my hot end to the old one or switch back to smoothie
I like the UBL, maybe I just switch back the old hot end for now

**Comment by gloomyandy** [comment]
You seem to be specifying 0 for the pull up resistor value, this is almost certainly wrong.The SBase board has a 4.7K pull up resistor so that3rd entry should probably be 4700.

**Comment by thinkyhead** [comment]
```
  PtLine(  0,341,4700)
  PtLine( 50,406,4700)
  PtLine(100,469,4700)
  PtLine(150,531,4700)
  PtLine(200,591,4700)
  PtLine(250,650,4700)
  PtLine(300,707,4700)
  PtLine(350,763,4700)
  PtLine(400,818,4700)
```

**Comment by ghost** [comment]
When I add 4k7 pull up, the temp just jump to 400c :-(

**Comment by thinkyhead** [comment]
I believe the MKS SBASE has 3.3v logic, so maybe a different set of scaling factors is needed.

- https://github.com/makerbase-mks/MKS-SBASE/wiki/Using-PT100-Themperature-Sensor-with-MKS-Sbase
- https://github.com/MarlinFirmware/Marlin/issues/2912#issuecomment-268478912

**Comment by AnHardt** [comment]
Tables 100 and 147 are for raw PT-resistors. We compare resistances. Voltage is canceled out of the equation..

Only if the PT is behind an amplifier (module) we compare voltages (That's still unpatched - i think). In that case a ADC-input with no pullup is required.

**Comment by boelle** [comment]
@keshantao problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
