### ISSUE TITLE
Missing Servo Pins in pins_FYSETC_F6_13.h

### ISSUE THREAD

**Issue by Ahrenfelde** [MarlinFirmware/Marlin#12307]
### Description

Missing Servo Pins in `pins.h` file of the Fystec F6 board.

### Steps to Reproduce

**Actual behavior:** 
Pins missing

#### Additional Information
Edit the Servo Pins:
```cpp
// following are original pins for servos
#define SERVO0_PIN       13
#define SERVO1_PIN       11    // if you enable PS_ON_PIN , CONFLICT!
#define SERVO2_PIN       10    // if you enable FILWIDTH_PIN , CONFLICT!
#define SERVO3_PIN       4     // if you enable RGB_LED,it will CONFLICT!
```

**Comment by thinkyhead** [comment]
Why do you suppose PS_ON, FIL_RUNOUT, and RGB_LED_G pins are being assigned to the extra servo pins? Maybe @mroote has some insight.

**Comment by mroote** [comment]
I took those pins from the original pins.h provided by the manufacturer.  I think they just bound those pins to common functions for convenience as they are available and can supply power too. If you need to use 4 servo's you will likely have to change around your pins config but I don't think this is common for most printers. I haven't tested all pins on my board so if you see any to fix or incorrect just let us know.

**Comment by Ahrenfelde** [comment]
The Servo pins are nessesary for a Bltouch probe. Therefor i added this pins in my file. In the original wiki feom fystec this pins are included. In the file from marlin 2.0 not.

**Comment by mroote** [comment]
Could you share the change you had to make? I don't see any BLTouch pins in the wiki here: https://wiki.fysetc.com/F6_V1.3/#pin-definition

**Comment by thinkyhead** [comment]
608be96
