### ISSUE TITLE
On Tronxy X3A error: 'REPRAPWORLD_KEYPAD_MOVE_MENU' was not declared in this scope

### ISSUE THREAD

**Issue by Opilson** [MarlinFirmware/Marlin#12310]
At example configuration i had this error.

Fast solution - add this to end of ultralcd.h file

#define REPRAPWORLD_KEYPAD_MOVE_MENU (buttons_reprapworld_keypad & KEYPAD_EN_C)

**Comment by Ludy87** [comment]
Same https://github.com/MarlinFirmware/Marlin/issues/12299
https://github.com/MarlinFirmware/Marlin/issues/12285

Fix is in this PR https://github.com/MarlinFirmware/Marlin/commit/b31a9300b8a717d9b677b52ecb364b5d10b76dbc

**Comment by Opilson** [comment]
Thanks for fast reply!
