### ISSUE TITLE
bugfix-2.0.x LiquidTWI2

### ISSUE THREAD

**Issue by cdedwards** [MarlinFirmware/Marlin#12312]
LiquidTWI2 was attempting to compile for my ReArm board with Viki2 board. WProgram.h is missing and this fails. Needed to add a line to the lib ignore statement. the 30aa480 needs to be on it's own line in the platformio.ini for the LPC1768

lib_ignore        = Adafruit NeoPixel
  30aa480

**Comment by p3p** [comment]
With the PlatformIO LDF in the state it is, it tries to build libraries that downloaded for other platforms you've built without checking compatibility and ignores the src folders, I'm probably going to have to disable it again, and just manually add the few libraries lpc176x supports.

**Comment by cdedwards** [comment]
so make clean is not working either then? Not sure why I would be even attempting this lib as I have a Viki2 and a RR Full Graphic, one on the ReArm and the other on a 2560. niether of which would be using this lib.

**Comment by p3p** [comment]
Make clean doesn't remove downloaded libs just the object files, you would need to delete the `.piolibdeps` folder (or the library from it).

**Comment by 262mike** [comment]
but I can verify the "lib_ignore" works

**Comment by dot-bob** [comment]
LDF seems to be working for me if I use the default mode of chain instead of chain+

**Comment by thinkyhead** [comment]
@Bob-the-Kuhn — Any special reason we've chosen to use chain+ instead of chain for our builds?
