### ISSUE TITLE
Feature request: ADC measurement

### ISSUE THREAD

**Issue by Lukelectro** [MarlinFirmware/Marlin#1231]
Hello all,

I'm modifying my Mendel90 with a sharp IR distance sensor, so it can be used as a 3d scanner. I don't know yet if this idea will work but my plan is the following:

Have an M-code that returns a ADC measurement (Best would be if you could supply it with a parameter specifying on what pin you would want to measure).

Then, all other software can run on the computer. The other software sends the printhead (with the sensor) to a location (G1) and takes a measurement. It does this in a loop moving in X and Z, measuring Y. Then it converts those measurements to a list of points for use in OpenScad or Blender.

But ADC measurements would also be useful for other features. I think it would be nice to include this in marlin, it should not take to much codespace and can be useful for other measurements as well (other analogue sensors, details handled on the host side so the same Mcode can be used for all of them and printer firmware does not need to be changed)

I know ADC measurements are done in an interrupt, and I don't want to break temperature control. So far I've just quick-and-dirty added a case to the M-code statemachine in marlin.cpp, that does a adc measurement and returns the value.  (I used M111 but found out it is already in use so that will change, possibly to M1111).  It uses the arduino analog.Read(), and I would like to use the existing interrupt routine or at least not break it. 

Ttemperature.c is full of warnings not to use functions of it outside of it.  Is there a function I could use for this without breaking things? (I could write my own if not)

**Comment by boelle** [comment]
will close this one... only one have shown interest and no posts since the first one

**Comment by KiteLab** [comment]
Possible workaround:
Misuse a thermometer. 
Eventually make a new 'thermistortable'.
Be sure to disable all safety features.
Read the distance with M105.

**Comment by Lukelectro** [comment]
Ok, so the distance sensor idea does not work. Size of measurement area is too large. Simply said "pixels" ("voxels"? Datapoints?) are too big and too far apart.

Anyway. At least tried it.
