### ISSUE TITLE
[bugfix 2.0.x] velocity setting in lcd menu shows x axis 3 times, y and z are missing.

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#12326]
With REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER, I am unable to adjust the max velocity for y and z. This is what the display output looks like:
Vmax X:   250
Vmax X:   250
Vmax X:   250
Vmax E:   30
Changing one of the X-values changes all of them.

**Comment by thinkyhead** [comment]
Thanks for the report. Now patched!

**Comment by GMagician** [comment]
@thinkyhead you are too fast...Neither the time to read the issue...

**Comment by hamster65** [comment]
Super fast. And it works :) Thanks!
