### ISSUE TITLE
X, Y, Z, coordinates not showing on REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER with MKS Sbase

### ISSUE THREAD

**Issue by Glod76** [MarlinFirmware/Marlin#12329]
Marlin-bugfix-2.0.x 11.2.2019

### Description

X, Y, Z, coordinates not showing on REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER with MKS Sbase

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2546010/Marlin.zip)

**Comment by gloomyandy** [comment]
Test with the most recent version, it was fixed a few days ago...
https://github.com/MarlinFirmware/Marlin/issues/12274

**Comment by Glod76** [comment]
Confirmed Fixed as of 11.4.2018 release. Closing Ticket
