### ISSUE TITLE
SdFat Library Update?

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#1232]
I see that there are a few files from an earlier version of the SdFat library by Bill Greiman included in the Marlin project. It seems like a good idea to try updating Marlin to update the code for the latest version of SdFat – posted at https://github.com/greiman/SdFat – and to move these files out of Marlin, making SdFat a normal library dependency.

However, before exploring this, I would like to know the historical reasons for including portions of SdFat instead of using a library dependency. Was this intended to help with code size (by including only the functions you need) or more to help with predictability (having a version of SdFat with known properties)? What would be the downside of making this an external dependency?

Even if SdFat should remain inside the Marlin project folder, it should still be possible to update to the latest SdFat, which seems on first glance to have some good improvements over the currently-included version.

**Comment by boelle** [comment]
closing... fixed via PR #1357
