### ISSUE TITLE
Bugfix 2.0 Anycubic Kossel can't compile

### ISSUE THREAD

**Issue by TheMrCaveman** [MarlinFirmware/Marlin#12320]
Can't compile the 2.0 bugfixbranch for anycubic kossel linear plus.
```
sketch\src\lcd\menu\menu.cpp: In function 'menu_action_setting_edit_callback_int3.constprop':

sketch\src\lcd\menu\menu.cpp:175:1: internal compiler error: Segmentation fault

 DEFINE_MENU_EDIT_TYPE(int16_t, int3, itostr3, 1);
```
used the example configs from anycubic kossel

**Comment by Ludy87** [comment]
Upload your configuration files

**Comment by fiveangle** [comment]
He's saying the example configs included in Marlin won't build.

**Comment by Ludy87** [comment]
@fiveangle i tried and have no problems

**Comment by AnHardt** [comment]
> ...  internal compiler error: Segmentation fault ..

Not an error in Marlin - but in the Tool-chain!

Try to vary Arduino IDE version and/or Boardmanager version for your board.
