### ISSUE TITLE
Ramps with BLTouch, pin doesn't go down when homing Z

### ISSUE THREAD

**Issue by Brakow87** [MarlinFirmware/Marlin#12321]
I cant get the pin to drop down when homing Z.  It is a standard Ramps 1.4 board and all wiring is correct.  I cant get the pin to drop using the manual commands either.  Below is my configuration.h  PLEASE HELP my printer is dead!!

Link to Configuration.h and Configuration_adv.h
https://drive.google.com/drive/folders/1E99sQZHHIeK9RTDPtPCP1tDeRZpk0ivj?usp=sharing

**Comment by labotecno** [comment]
#define Z_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MIN_PROBE_ENDSTOP_INVERTING true // set to true to invert the logic of the probe.
you need to put the same like z min probe endstop inverting  so put true !

**Comment by Brakow87** [comment]
@labotecno I have made the changes you suggested to the two entries listed in your comment above, set both to true, and just for fun, set them both to false.  I got the same result.  When trying to home Z the pin on the BLTouch does not drop down.  But the Z axis does go down attempting to probe.  Ultimately hitting the bed with the nozzle because the pin is never deployed.

**Comment by kAdonis** [comment]
You wrote you are using a RAMPS 1.4 but you defined:

`  #define MOTHERBOARD BOARD_RAMPS_13_EFB`

try 

`  #define MOTHERBOARD BOARD_RAMPS_14_EFB`

Test BLTouch with:   M280 P0 S120
BLTouch manual: https://www.antclabs.com/manual

**Comment by labotecno** [comment]
ok so you have a problem with your conexion check it more ! whithout moving you axle z you can to stow or desploy the pin of the bltouch with lcd menu ! if you dont have it you have to put it 
other thing comented this to help you make homing separately 
#define INDIVIDUAL_AXIS_HOMING_MENU

**Comment by italocjs** [comment]
Something similar happened to me a few times, most of them, there was a bad contact between the servo pin on the ramps and the bltouch.  there once happened that pin sequence was inverted (+ on S, - on -, and S on+)  so the bltouch would light up, but not receive commands.

i'm attaching my config.h (working), hope it helps.

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2546060/Configuration.txt)

**Comment by xStolix** [comment]
I just updated to the latest bugfix now and also have the situation where the probe will not work, it goes through power on check fine but then it doesn't work on the LCD or Gcode. Bugfix from a few months ago works fine. I will dig some more but thought to look here to see if any one else was seeing the same thing. 

Update:.....Mine was me not remembering the correct pin number, have too many printers and kept entering the wrong pin number in the pins ramps.h DOH!

**Comment by thinkyhead** [comment]
As one extra troubleshooting step, enable `PINS_DEBUGGING` and then you can use `M43` to check that all the pins are set up correctly. The same option exists in Marlin 1.1.9 (and earlier `bugfix-2.0.x`) so you can compare the output from both to make sure nothing has changed.

**Comment by Brakow87** [comment]
Thank you for all of your help!!  It is greatly appreciated!!  I have figured out and resolved the issues.  I found that one of the wires was in fact damaged.  Replaced the wire and changed the board type to ramps_14, and everything came to life.  Thanks again to you all!

**Comment by JuergenBachmann** [comment]
Hi!
I have got the same problem. When i want to home de z axix, then the pin of the bl-touch is deployed and then retracted. But the homeing isn´t working. I´m using Marlin 2.0.x on a MKS Base 1.6.
it would be nice, if anybody will have a look to my configuration...
Thanks a lot!

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2611313/Configuration.zip)

**Comment by kAdonis** [comment]
Did you change anything or is the BLTouch new? is it a clone or an original?
Try: 
`#define BLTOUCH_DELAY 375   // (ms) Enable and increase if needed`
this is the standard setting

**Comment by JuergenBachmann** [comment]
The mainboard and the BLTouch are new - i think it´s an orginal

to enable the delay didn´t fix the problem

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
