### ISSUE TITLE
help to work power loss 

### ISSUE THREAD

**Issue by walidsmart** [MarlinFirmware/Marlin#12339]
hi all pro
have anice day
plasae i need help me to choose the best fromwer to good work power loss recovery at ramps 1.4 
1.1 bugfix 
2 bug fix 
1.9 marlin 
or another version 
thank you so much for help me

**Comment by thinkyhead** [comment]
Version `1.1.9`, `bugfix-1.1.x`, or `bugfix-2.0.x` are all equally good choices. If you run into any problems, please add your commentary to #11072.
