### ISSUE TITLE
Y-Offset at different layer hights

### ISSUE THREAD

**Issue by baeriwiliwonka** [MarlinFirmware/Marlin#12330]
Hi all,

I just updated to Marlin 1.1.9 and saw a Y layer offset issue several times.
At first I tought it was caused by a filament change, but the Y-offset happened one layer before the layer change and two times after the filament change, so that doesn't seem to be the root cause.

Also in a one coloured print I saw this issue, but at a different layer height.

Problem was independet from the source (Octorprint and SD tested).

I also want to exclude mechanical problems because with a very old firmware (1.1.0) I never had y-offset issues. So I guess somethings wrong in the firmware.

I used the preconfigured config for my CR10S.

### Description

Y offsets happened randomly at different layer heights

### Steps to Reproduce

Happened in every print since I reflashed to 1.1.9. No special steps to reproduce.

**Expected behavior:** [What you expect to happen]

No Y offsets at any layer height.

**Actual behavior:** [What actually happens]

Y-Offsets at random layerheight, but reproduceable with the same gcode file.
So the offset happenes for every model at the same layer height, but in a different model it happenes at another layer heiht. But it happens... 

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.
![45099871_172031980402125_9062039703573757952_n](https://user-images.githubusercontent.com/44751878/47967589-2447cb80-e05f-11e8-9617-f06ee158e2c1.jpg)

**Comment by baeriwiliwonka** [comment]
![2](https://user-images.githubusercontent.com/44751878/47967620-915b6100-e05f-11e8-8390-b4340119d74a.JPG)

**Comment by swilkens** [comment]
The step from 1.1.0 to 1.1.9 is a big one. However, considering that your printer is a popular one and we aren't seeing a flood of reports from users with similar issues, it seems likely that this is a mechanical problem.

Some things we might check:

- Is there a significant change in the acceleration, jerk or feedrate values for your printer between the firmware versions?

- Have you checked the sliced gcode on websites such as gcode.ws to verify that this is not an issue in the gcode?

- Have you checked belt tension? They tend to stretch with time.

- Have you tried 2.0.x-bugfix?

Typically, these problems are printer related - not firmware related. You might find more printer specific help on:

- Your printer's facebook group

- Your printer's subreddit

- The official Marlin facebook group (https://www.facebook.com/groups/1049718498464482/)

- The Marlin user's group (https://www.facebook.com/groups/3Dtechtalk/)

**Comment by boelle** [comment]
@baeriwiliwonka problem solved in latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
