### ISSUE TITLE
[Bugfix-2.0.x] presentation error Z Value

### ISSUE THREAD

**Issue by Ludy87** [MarlinFirmware/Marlin#12335]
### Description

wrong Z value when activated `MESH_EDIT_MENU`

```cpp
MENU_MULTIPLIER_ITEM_EDIT_CALLBACK(float43, MSG_MESH_EDIT_Z, &Z_VALUES(xind, yind), -(LCD_PROBE_Z_RANGE) * 0.5, (LCD_PROBE_Z_RANGE) * 0.5, refresh_planner);
```

### Steps to Reproduce

```cpp
#define AUTO_BED_LEVELING_BILINEAR
#define LCD_BED_LEVELING
#define MESH_EDIT_MENU
```

**Expected behavior:**
Display message should `Z Value:     0.000`

**Actual behavior:**
Display message is `Z Value:     --.*,(`

**Comment by thinkyhead** [comment]
Unable to reproduce.

**Comment by Ludy87** [comment]
I try again and it is same Problem

Motion->Bed Leveling->Edit Mesh

[Marlin_Config.zip](https://github.com/MarlinFirmware/Marlin/files/2548073/Marlin_Config.zip)

**Comment by thinkyhead** [comment]
What does `M420 V` say?

**Comment by Ludy87** [comment]
SENDING:M420 V
echo:Bed Leveling Off
echo:Fade Height Off

**Comment by thinkyhead** [comment]
I was hoping to see the values of your mesh, but apparently there isn't one…

**Comment by Ludy87** [comment]
This problem is before Bed leveling after is all right

```SENDING:M420 V
Bilinear Leveling Grid:
      0      1      2
 0 -0.088 -0.070 +0.025
 1 -0.050 +0.020 +0.170
 2 +0.070 +0.042 +0.222
echo:Bed Leveling On
echo:Fade Height Off

**Comment by thinkyhead** [comment]
I see. The menu should likely be hidden, then, if `leveling_is_valid` returns `false`.

**Comment by Ludy87** [comment]
yes it's better

**Comment by thinkyhead** [comment]
…because `NAN` isn't going to display anything pretty.
```cpp
void reset_bed_level() {
  #if ENABLED(DEBUG_LEVELING_FEATURE)
    if (DEBUGGING(LEVELING)) SERIAL_ECHOLNPGM("reset_bed_level");
  #endif
  set_bed_leveling_enabled(false);
  #if ENABLED(MESH_BED_LEVELING)
    mbl.reset();
  #elif ENABLED(AUTO_BED_LEVELING_UBL)
    ubl.reset();
  #elif ENABLED(AUTO_BED_LEVELING_BILINEAR)
    bilinear_start[X_AXIS] = bilinear_start[Y_AXIS] =
    bilinear_grid_spacing[X_AXIS] = bilinear_grid_spacing[Y_AXIS] = 0;
    for (uint8_t x = 0; x < GRID_MAX_POINTS_X; x++)
      for (uint8_t y = 0; y < GRID_MAX_POINTS_Y; y++)
        z_values[x][y] = NAN;
  #elif ABL_PLANAR
    planner.bed_level_matrix.set_to_identity();
  #endif
}
```

**Comment by Ludy87** [comment]
or default `0`?

**Comment by thinkyhead** [comment]
It wouldn't help. The bilinear mesh is never valid until a `G29` has been done to establish the mesh bounds and spacing between points. Having it be "not valid" until that point has a certain utility, as it prevents enabling leveling until data has been acquired.

**Comment by thinkyhead** [comment]
93d5b945dd56a6632395522f6c049e942e4b0166
