### ISSUE TITLE
TMC2130 probe cancel sensor less homing z ! Cartesian machine

### ISSUE THREAD

**Issue by labotecno** [MarlinFirmware/Marlin#12346]
Hello every one ! 5 days ago i try to get sensor less axle z working with TMC2130 with my labrap   , and i finish to get it working .
i use marlin 1.1.9 may be after i will use the bugfix 2 
why the #define FIX_MOUNTED_PROBE cancel the sensorless z ? 
if it can be make some change to do not cancel anything ? 
by the way , only TMC calibration #define TMC_Z_CALIBRATION make z axle calibration why ? 
thank you

**Comment by thinkyhead** [comment]
> why the `#define FIX_MOUNTED_PROBE` cancel the sensorless z ?

It doesn't. Where did you get that idea?

> only TMC calibration `#define TMC_Z_CALIBRATION` make z axle calibration why ?

You'll have to ask its author, @teemuatlut, who would be delighted to answer all your questions.

**Comment by labotecno** [comment]
Conditionals_post.h
#if ENABLED(SENSORLESS_HOMING)
  // Disable Z axis sensorless homing if a probe is used to home the Z axis
  #if HOMING_Z_WITH_PROBE
    #undef Z_HOMING_SENSITIVITY
only mesh leveling working for getting M851 
I will ask him thank you anyway.

**Comment by teemuatlut** [comment]
If you have a probe of any kind you should use that for Z axis homing. That's why the check is there.

`TMC_Z_CALIBRATION` is a script that runs the Z axis to its max to align the left and right side. It doesn't calibrate the drivers but the axis rail.

**Comment by labotecno** [comment]
It should very nice to use nozle for probe z , like a Delta , this option miss for tmc2130 sensorless z .

**Comment by moracabanas** [comment]
> If you have a probe of any kind you should use that for Z axis homing. That's why the check is there.
> 
> `TMC_Z_CALIBRATION` is a script that runs the Z axis to its max to align the left and right side. It doesn't calibrate the drivers but the axis rail.

Does it work if you have both Z motors in paralel with the same TMC2130?

**Comment by labotecno** [comment]
Yes It s working but it Will better with Two driver each One motors for current propose

**Comment by Govindarajulu97** [comment]
Hai guys my qut may out off this but i am trying to use this tmc2130 for my syringe pump project, in that i need to stop the motor when it reaches its max position as well i want to calculate the steps missed as well as steps travelled by the stepper,
can any one help me to know
1.How to calculate steps traveled/steps missed in SPI mode?
2.How to Stop the movement when it hits the end point?
Iam using Arduino uno,tmc2130 driver,stepper nema 17

**Comment by teemuatlut** [comment]
@Govindarajulu97 The TMC2130 only calculates missed steps in DCstep mode. Marlin does not support that nor does it suit our purposes (I've asked).
If you want to go ahead with your project, start by reading the datasheet, especially about using stallGuard and get familiar working with the internal driver registers.

Or maybe use an encoder for a feedback loop.

Your post doesn't tell much about your project but perhaps using Marlin isn't the way to go in the first place.

**Comment by teemuatlut** [comment]
> @moracabanas Does it work if you have both Z motors in paralel with the same TMC2130?

Yes it should work. All it does is lower the driver current and drive the Z axis past its maximum against some physical hard limit you've placed there.

**Comment by labotecno** [comment]
https://youtu.be/M9USgFEB0iM its working now i just need get the manual probe enable !!!! for research
