### ISSUE TITLE
[ 2.0.X ] Compilation fails from NO_LCD_MENU

### ISSUE THREAD

**Issue by Transvistinator** [MarlinFirmware/Marlin#12359]
Error compiling from the 2.0.X branch after configuring for NO_LCD_MENU.

Looks to be identical or similar to issue #10763

--------------------------
Downloaded the latest version of 2.0.X, configured for my printer and tried to compile with NO_LCD_MENU defined, in order to try and free up space for AUTO_BED_LEVELING_UBL

https://pastebin.com/78Vu8c40

**Expected behavior:**
It compiles 👍 

**Actual behavior:**
It doesn't compile. 👎 

As per #10763 using SLIM_LCD_MENUS works fine, but doesn't free up enough PROGMEM unfortunately.

Thanks for looking at this 

**Additional Information** 
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2558565/Marlin.zip)

**Comment by Ludy87** [comment]
you are Have a Melzi-Board or a Anet-Board?

**Comment by gloomyandy** [comment]
It would probably help if you supplied details of the compilation error.

**Comment by Transvistinator** [comment]
> 
> 
> you are Have a Melzi-Board or a Anet-Board?

Melzi 2.0 with a " Zonestar " LCD

Printer is a Tronxy P802M if that helps

**Comment by thinkyhead** [comment]
I can't reproduce the issue. I used your configurations and the current `bugfix-2.0.x` and it compiled just fine.

**Comment by swilkens** [comment]
Similar issue on Ender-3, different compile errors.

Configs:
[no_lcd_menus_compile_error.zip](https://github.com/MarlinFirmware/Marlin/files/2562139/no_lcd_menus_compile_error.zip)

- BOARD_MELZI_CREALITY

- CR10_STOCKDISPLAY

https://pastebin.com/raw/fCVK7x8z

**Comment by thinkyhead** [comment]
Working on it…

**Comment by Ludy87** [comment]
@thinkyhead 
that would not be better for @swilkens: 
[pins_SANGUINOLOLU_11.zip](https://github.com/MarlinFirmware/Marlin/files/2562984/pins_SANGUINOLOLU_11.zip)

**Comment by swilkens** [comment]
Apologies, I should have made a separate issue report

**Comment by Transvistinator** [comment]
> 
> 
> Working on it…

Tested the changes you did in your pull request, compiles like a charm.

Thank you <3

**Comment by thinkyhead** [comment]
The PR should be applicable for @swilkens  now too. At least, it compiles with the provided configurations.

**Comment by Ludy87** [comment]
I will try it myself later.

**Comment by swilkens** [comment]
> The PR should be applicable for @swilkens now too. At least, it compiles with the provided configurations.

It does indeed fix the issue for me.
