### ISSUE TITLE
sunon fans not work

### ISSUE THREAD

**Issue by userosos** [MarlinFirmware/Marlin#12360]
Hi!
I connected SUNON HA40201V4-A99-A like fans for cooling printing models and it work when i enabled 100% PWM. And not work if a set 50% PWM. Can i change PWM frequency?

**Comment by swilkens** [comment]
I had a similar issue and found that the SUNON fans (and indeed all brushless DC fans) do not handle duty cycle'd DC supply very well. You can find the lower limit where it will still spin by gradually increasing the rate until the fan starts spinning - but you will likely find that the fan refuses to spin until the value is quite high. 

This approach of fan control is a remainder from the brushed fan age where this duty cycle DC approach worked, DC brushless fans have private controller boards and need a variable DC voltage for effective speed control.

Some technical discussion on this can be found here:
http://forum.makergear.com/viewtopic.php?t=6310#p35390

Some slicers have a hacky method to improve control by blipping the fan to max for a short moment, using the inertia of the fan to keep it going at lower duty cycles.

It would be nice if board manufacturers (and perhaps Marlin?) move to functional PWM fans (i.e. proper PWM controllable fans, not duty cycle DC which fundamentally doesn't work for brushless fans), but all good things come slowly.

Either way, this is not a direct marlin issue.

**Comment by rmoravcik** [comment]
You have to buy a new Sunon fan without 'Auto Restart' feature (without letter A at the end of model number). That feature is causing it.

**Comment by userosos** [comment]
@rmoravcik What it mean -  'Auto Restart'?

**Comment by rmoravcik** [comment]
Well, a colleague of mine explained me this feature as a kind of protection, that is trying to automatically restart fan if fan is blocked (not spinning). So, if you try to control such fan with PWM, fan is not spinning enough and auto-restart will detect this as blocked state.

I personally replaced my old Sunon without auto-restart with a new one with auto-restart without knowing that too.

**Comment by userosos** [comment]
> 
> 
> Well, a colleague of mine explained me this feature as a kind of protection, that is trying to automatically restart fan if fan is blocked (not spinning). So, if you try to control such fan with PWM, fan is not spinning enough and auto-restart will detect this as blocked state.
> 
> I personally replaced my old Sunon without auto-restart with a new one with auto-restart without knowing that too.

Ok! Big thx! Can i fix it use hardware? Capacity for example?

**Comment by thinkyhead** [comment]
You could try a capacitor. No guarantee that it will work, but it will definitely smooth out the current.

**Comment by userosos** [comment]
@thinkyhead i connected Capacity 450 uF 65 V - it is work very good.

**Comment by ManuelMcLure** [comment]
Please be aware that adding a filtering capacitor may damage the fan MOSFET on your controller board, as described in further posts on the above linked forum thread.

**Comment by userosos** [comment]
@ManuelMcLure 
> Please be aware that adding a filtering capacitor may damage the fan MOSFET on your controller board, as described in further posts on the above linked forum thread.

What happend with MOSFET? I test it 5 mins. MOSFET is cold.
UPD: 10 min's - OK.

**Comment by ManuelMcLure** [comment]
Check out the fifth post on page 2 of http://forum.makergear.com/viewtopic.php?t=6310#p35650 for details.

**Comment by i-smuglov** [comment]
Solved it by enabling FAST_PWM_FAN instead of FAN_SOFT_PWM. Looks like the higher frequency that FAST_PWM mode provides is enough.

**configuration.h**
```
#define FAST_PWM_FAN
//#define FAN_SOFT_PWM
//#define SOFT_PWM_SCALE 0
```

Some kickstart may also help

**configuration.adv.h**
`#define FAN_KICKSTART_TIME 1000`
