### ISSUE TITLE
[bug] Layer Shifts on final 1.1.9

### ISSUE THREAD

**Issue by Anycubic** [MarlinFirmware/Marlin#12365]
### Description
I have a Delta printer. After upgrading from 1.1.0 to 1.1.9 I have layer shifts on pretty always same heights on both x and y axis. Reducing speed, acc and jerk, raising vref does not show any improvement. I also got this tested with same printer with magnetic effector and fisheye bearing and I have exactly same issue. 1.1.5 have same issue.

### Steps to Reproduce

1. Turn on printer
2. Print 3Dbenchy with "M420 S1" in the GCODE

If I print same object without "M420 S1" (so leveling disabled) everything is fine

**Expected behavior:** Flawless print

**Actual behavior:** Level shifts at always same heights

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2561620/Marlin.zip)

![img_20181108_132830](https://user-images.githubusercontent.com/31375394/48199611-e8fa1500-e35c-11e8-80bd-f0991f20aec6.jpg)
![img_20181108_131800](https://user-images.githubusercontent.com/31375394/48199612-e8fa1500-e35c-11e8-9907-4a07c1bbdbb3.jpg)

This is my first Bug report, this is not my native language. I tried my best, let me know what additional information you need.

**Comment by thinkyhead** [comment]
1.1.x is end-of-life and will not be receiving any more updates. Please test with `bugfix-2.0.x` and see if the issue is still present in that version of the firmware.

**Comment by Anycubic** [comment]
ok, I will do that.
Thank you

**Comment by boelle** [comment]
@Anycubic problem solved?

**Comment by Anycubic** [comment]
@boelle since then I switched to TMC2130 and still had the issue on 2.x. A few days ago I also changed the board with a Re-arm (hoping that more powerful CPU will sort skippings out), so need to test everything again

**Comment by boelle** [comment]
@Anycubic did you re-test?

**Comment by Anycubic** [comment]
Sorry but lately I'm very busy with my job, hope to have time to re-test in the next few days

**Comment by boelle** [comment]
@Anycubic maybe click close below and open new issue if problem is still there?

**Comment by Anycubic** [comment]
Ok, done
