### ISSUE TITLE
MONITOR_DRIVER_STATUS should work for tmc2660

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#12362]
With latest bugfox-2.0.x TMC drivers conditions seems changed and now bans MONITOR_DRIVER_STATUS for tmc2660
```
error: #error "MONITOR_DRIVER_STATUS requires at least one TMC2130 or TMC2208."
#error "MONITOR_DRIVER_STATUS requires at least one TMC2130 or TMC2208."

```

**Comment by teemuatlut** [comment]
Yes.

**Comment by alexxy** [comment]
???

**Comment by Ludy87** [comment]
tmc2660 is not supported for MONITOR_DRIVER_STATUS

**Comment by teemuatlut** [comment]
> tmc2660 is not supported for MONITOR_DRIVER_STATUS

[Actually it is.](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/feature/tmc_util.cpp#L100-L118)

> MONITOR_DRIVER_STATUS should work for tmc2660

"Yes."

**Comment by Ludy87** [comment]
Sorry, I confused it with DEBUG https://github.com/MarlinFirmware/Marlin/blob/525ea554a1e53cef7d60dfa8d33664a99bcd4a3f/Marlin/src/feature/tmc_util.cpp#L102 https://github.com/MarlinFirmware/Marlin/blob/525ea554a1e53cef7d60dfa8d33664a99bcd4a3f/Marlin/src/feature/tmc_util.cpp#L103

**Comment by thinkyhead** [comment]
Patched sanity-check to permit TMC2660.
