### ISSUE TITLE
[bugfix-2.0.x]  BLtouch 'touch' my bed control output on STM32F4

### ISSUE THREAD

**Issue by mr-miky** [MarlinFirmware/Marlin#12388]
It's been a while since I noticed it but I temporarily ignored it because I needed to complete HW debugging.

In summary it happens that bltouch goes to alter the state of the pin that controls the heater of the bed. At the time I have circumvented the problem by changing the pin that controls the bed.
It always seemed strange to me because all happens on PA0  a.k.a. pin 0 ...

Now that I'm near the finish line, with the debugger  I'm trying to figure out what really happens.
I added a brekpoint that monitor **pin** on servo class.
The strange thing is that servo_init ()  correctly set the servo pin and then disconnect it as expected, then from the next servo_probe_init () the servo control **pin** becomes pin 0 / PA0.
servo_probe_init (), through an infinite series of MACRO, call servo.move (...)

I do not understand the following:

From HAL/shared/servo.cpp

```
 *
 * Servo - Class for manipulating servo motors connected to Arduino pins.
 *
 * **attach(pin)           - Attach a servo motor to an i/o pin.**
 * attach(pin, min, max) - Attach to a pin, setting min and max values in microseconds
 *                         Default min is 544, max is 2400

```

```
void Servo::move(const int value) {
  constexpr uint16_t servo_delay[] = SERVO_DELAY;
  static_assert(COUNT(servo_delay) == NUM_SERVOS, "SERVO_DELAY must be an array NUM_SERVOS long.");
  if (this->attach(0) >= 0) {
    this->write(value);
    safe_delay(servo_delay[this->servoIndex]);
    #if ENABLED(DEACTIVATE_SERVOS_AFTER_MOVE)
      this->detach();
    #endif
  }
}

```

and in particular

**this-> attach (0)**

There are 3 possibilities: 
  ° I do not understand
  °  Nobody uses a servo / bltouch.
  ° All use bltouch connected to PA0
The first one is more probable and that's why I ask here ...

**Comment by mr-miky** [comment]
GRRRR!!! Again !!!!

Yet another flaw of STM32_GENERIC !!!

I did not realize that servo.cpp is a library implemented in STM32_GENERIC  :-(

**Comment by jmz52** [comment]
@mr-miky, second option is a correct one (Nobody uses a servo / bltouch)
Servo's code is broken (probably an uncompleted port from HAL_TEENSY35_36)
See if you can reuse code from HAL_STM32F1/HAL_Servo_Stm32f1.cpp.

If I recall correctly problem root cause was '#ifdef \_SERVO_H_' used in both module\servo.h from Marlin and libraries\Servo\src\Servo.h from stm32duino. Marlin defines \_SERVO_H_ first, effectively blocking library from stm32duino.
HAL_Servo_Stm32f1.cpp was modified to work without Servo library from stm32duino.

**Comment by boelle** [comment]
@mr-miky problem solved?

**Comment by mr-miky** [comment]
I made a patch that honestly is really horrible more than anything else to be able to finish the hardware test of my custom control board. I would like to find the time to fix it but I am very busy

**Comment by boelle** [comment]
@mr-miky submit pr to bugfix 2.0 and close this one

minimum close this one

**Comment by mr-miky** [comment]
Actually the problem in the source exists and closing the issue does not make the problem disappear.

**Comment by AnHardt** [comment]
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/shared/servo.cpp#L98-L99

is the key to your question.
`this-> attach(0)` does not mean "attach pin 0", but "attach the already known and stored in`servo_info[this->servoIndex].Pin.nbr` pin". If we do know the right servo object we already have the right pin. Only when we want to change the pin associated to the servo we have to call attach() with a different from 0 pin number. This implies: servos can't be connected to `PA0`.

**Comment by mr-miky** [comment]
@AnHardt 
I understood the mechanism but I suspect the stm32generic 'servo' library interprets it differently.
the problem is that attach (0) goes to alter the state of pin PA0.

from https://github.com/danieleff/STM32GENERIC/blob/master/STM32/libraries/Servo/src/Servo.cpp

`uint8_t Servo::attach(int pin) {`
`    this->pin = pin;`
`    this->minAngle = 0;`
`    this->maxAngle = 180;`
`    return 1;`
`}`

**Comment by mr-miky** [comment]
It seems to me that attach (0) brings more incompatibility than benefits.
`if (pin > 0) servo_info[this->servoIndex].Pin.nbr = pin;`
In the end it only avoids making a further pin assignment.

Please also note that in HAL / shared / servo.cpp at line 58 we read

`#if HAS_SERVOS && !(IS_32BIT_TEENSY || defined(TARGET_LPC1768) || defined(STM32F1) || defined(STM32F1xx) || defined(STM32F4) || defined(STM32F4xx) || defined(STM32F7xx))`

I do not understand why it happens that even having an STM32F4 the condition is false, however to the line
60
`#include "servo_private.h"`
the compilation would fail due to the error made by the condition
`#ifdef __AVR__`
`..#include "../HAL_AVR/ServoTimers.h"`
`#elif defined(ARDUINO_ARCH_SAM)`
`..#include "../HAL_DUE/ServoTimers.h"`
`#else`
`..#error "This library only supports boards with an AVR or SAM3X processor."`
`#endif`

**Comment by mr-miky** [comment]
@AnHardt   
"This implies: servos can't be connected to `PA0`." 
Perhaps you meant **nothing** can be connected to PA0

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by mr-miky** [comment]
I close it so you don't get bored but the problem still exists
