### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by hamlet600** [MarlinFirmware/Marlin#12399]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.
# @ @

**Comment by hamlet600** [comment]
i use bugfix2 when uncomment           #define BABYSTEP_ZPROBE_OFFSET     // Combine M851 Z and Babystepping

error in compile   sketch\src\lcd\menu\menu.cpp: In function 'void lcd_babystep_zoffset()':

sketch\src\lcd\menu\menu.cpp:374:9: error: 'thermalManager' was not declared in this scope

         thermalManager.babystep_axis(Z_AXIS, babystep_increment);


please guide me

**Comment by gloomyandy** [comment]
Please supply your configuration files. How recent is your bugfix-2.0.x? Please download the latest version and confirm that the problem still exists.

**Comment by Ludy87** [comment]
@gloomyandy ``THERMAL_PROTECTION_HOTENDS`` and ``THERMAL_PROTECTION_HOTENDS`` been disabled 

https://github.com/MarlinFirmware/Marlin/blob/a0c795b097a30eff006c8dff178abf5f1f1907fa/Marlin/src/lcd/menu/menu.cpp#L39-L41

dependency exists between the two functions

**Comment by AnHardt** [comment]
Try 
At the top of `\src\lcd\menu\menu.cpp`
```diff
@@ -33,11 +33,11 @@
 
 #if ENABLED(EEPROM_SETTINGS)
   #include "../../module/configuration_store.h"
 #endif
 
-#if WATCH_HOTENDS || WATCH_THE_BED
+#if WATCH_HOTENDS || WATCH_THE_BED || ENABLED(BABYSTEP_ZPROBE_OFFSET)
   #include "../../module/temperature.h"
 #endif
 
 #if ENABLED(BABYSTEP_ZPROBE_OFFSET)
   #include "../../module/probe.h"
```

**Comment by hamlet600** [comment]
it is last version bugfix2 and thermal protection for both hotend and bed are disabled

**Comment by hamlet600** [comment]
> Try
> At the top of `\src\lcd\menu\menu.cpp`
> 
> ```diff
> @@ -33,11 +33,11 @@
>  
>  #if ENABLED(EEPROM_SETTINGS)
>    #include "../../module/configuration_store.h"
>  #endif
>  
> -#if WATCH_HOTENDS || WATCH_THE_BED
> +#if WATCH_HOTENDS || WATCH_THE_BED || ENABLED(BABYSTEP_ZPROBE_OFFSET)
>    #include "../../module/temperature.h"
>  #endif
>  
>  #if ENABLED(BABYSTEP_ZPROBE_OFFSET)
>    #include "../../module/probe.h"
> ```

it's work thank you.
