### ISSUE TITLE
[bugfix 2.0.x] Test Issue on STM32F1

### ISSUE THREAD

**Issue by Weruminger** [MarlinFirmware/Marlin#12391]
### Description

Found out on PR#12389 that an error recognized on all other platforms haven't been recognized on STM32F1. Because the the issue was related to M106/M107 change I cannot imaging why it is not recognized on that plattform. 

Because the other platform related tests ran in failed state, there is no high pressure to have a look on it, but if there is work on platform related tests thi issue shall be investigate and solved.

I can not see that the root cause of the fails on other platforms will not be recognized on STM32F1.

### Steps to Reproduce

 have a look on
https://travis-ci.org/MarlinFirmware/Marlin/builds/453248476

**Expected behavior:** All platform related test shall failed.

**Actual behavior:** All platform related test except the STM32F1 failed.

#### Additional Information

(https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by Ludy87** [comment]
is newer https://travis-ci.org/MarlinFirmware/Marlin/builds/453252679

**Comment by Weruminger** [comment]
It is not the code to be tested i pointed on. it was the test it self. of course i fixed the code related to the failed test results. And so newer builds succeeded. 

But on the buggy code i did expect, that all platform tests failed because it is not a platform specific code part. 

If it help, i can revert the code to the buggy version to show the behaviour,

**Comment by Ludy87** [comment]
not necessary did not understand it correctly

**Comment by AnHardt** [comment]
We have seen that before when the MIXER test in STM32F1 did not bark about the overflow. 

Something is wrong there.

**Comment by p3p** [comment]
The same feature tests are not run on all platforms as not all features are supported, the AVR tests are designed to have the most code coverage on the platform-independent code paths, while the other platforms tests generally cover the platforms’ HAL implementations, but saying that, I'm not sure how the STM build didn't have that error. It seems generic ..

**Comment by Weruminger** [comment]
Okay, I‘ll describe my understanding of the workpattern , how to Interpret the Test Results. If one of all testbuilds failed,the root case may also affect the other platforms in Field. This is adequately to Test the Software. If faturetest are distributed intersectional over all platform related builds, higher coverage at smaller builtime are feasible and a high code quality is the result.

Am I right ?

**Comment by Weruminger** [comment]
Issue is clear and not anything to be fixed
