### ISSUE TITLE
[TODO] Software Serial for Arduino Due

### ISSUE THREAD

**Issue by weed2all** [MarlinFirmware/Marlin#12393]
i encountered on google someone that successfully made a software serial library for arduino due...how can this be a added to the marlin 2.0 in order that we(arduino due + radds users) can have our tmc2208 uart communication
Link for the library: 

https://github.com/antodom/soft_uart

**Comment by teemuatlut** [comment]
The initialization interface is quite different compared to _anything_ else, so you'd likely want to fork it and then create a pull request towards the TMCStepper library.
Adding support does not require changes to Marlin. Other than possibly clearing some sanity checking.

**Comment by weed2all** [comment]
Yeah..im not a programmer, I don't have the knowledge to do it..that why I asked.
Someone with the knowledge might give it a try...i would realy appreciate have this working on my radds

**Comment by weed2all** [comment]
What would be the simplest way to do this...integrate software serial library in marlin or like you said to fork that library and add a pull request to tmc library?

**Comment by teemuatlut** [comment]
Marlin does not handle software serial object for the TMC2208 drivers. Rather it passes the requested pins to the TMC library and it then creates the SW serial object.
The difference is that the `soft_serial` library adds some unique initialization requirements and I'm not overly excited about the fact. I'd like the interface to conform to the others before I would include the changes.

**Comment by weed2all** [comment]
Hmm ..ok..thank you for your answer...as I'm not an arduino programmer it would be very difficult for me to make this working any time soon I guess!

**Comment by thinkyhead** [comment]
A glue class hiding the `soft_uart` interface behind the `SoftwareSerial` interface would do the trick.

**Comment by weed2all** [comment]
Glad to hear this Scott!

**Comment by boelle** [comment]
@weed2all has this "issue" done its purpose?

**Comment by weed2all** [comment]
No man...i don't know how to do this yet...

**Comment by boelle** [comment]
click close and open new issue in future

**Comment by weed2all** [comment]
Man...what is happening with you...i see alot of post of you trying to close issues...this is a issue for SAM3X8E MCU.
Other issue that happen to be mine as well is for LPC1768 MCU

**Comment by boelle** [comment]
cleaning up the issue list is what is happening

i have maybe been to effective

**Comment by weed2all** [comment]
It is not yet solved man...i don't have the skills required to do what @thinkyhead pointed out...so it will be opened till get help to make it work...

**Comment by boelle** [comment]
and @thinkyhead told me that the issue list is not for question and help but for bug and feature request

see why its not easy to figure out?

**Comment by weed2all** [comment]
now it have a TODO header on it...

**Comment by boelle** [comment]
:-D

also i have read almost every single issue over last 3 days and my head feels like a sponge

but i can tell you many issues was solved but never closed
a lot of them should have been put on the discord server or facebook as they where just simple questions

so yeah man mistakes like this happens :-D

**Comment by weed2all** [comment]
Dont get me wrong...but instead to hunt down issues to close.. You can actualy help if you have the skills...

**Comment by boelle** [comment]
sadly my programming skills are equal zero :-(

i also had the due board but got an re-arm instead, so i have 2 new due's in a box somewhere, the have been out the box for maybe 10 mins and then back
