### ISSUE TITLE
Resume not happen after pause

### ISSUE THREAD

**Issue by hamlet600** [MarlinFirmware/Marlin#12411]
### Description

resume procedure is not complete

### Steps to Reproduce

enable PARK_HEAD_ON_PAUSE in advanced pause 

**Expected behavior:** 
after resume continue printing

**Actual behavior:** 
just come back to last position and do not start print

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/2572188/Configuration_adv.zip)

**Comment by thinkyhead** [comment]
How are you pausing and resuming? Host printing or SD printing?

**Comment by InsanityAutomation** [comment]
Most likely octoprint. They made a change on 1.3.7 that delayed state changes so they miss the resume command. Octoprint bug, not marlin if so.

**Comment by hamlet600** [comment]
i use pause from lcd(128x64) menu

**Comment by e-Mole** [comment]
Same as my strange printing pause (from LCD menu) behavior:

1. head is going to park position - o.k.
2. on LCD is now message about changing filament - wrong (but message only)
3. after enter (click) - screen with continue or purge option - o.k.
4. after continue (click) - head is going to last print position and will stand - wrong (why not continue printing now?)
5. on LCD is Info screen now - o.k.
6. it is necessary to enter menu (click) and select Resume - wrong (why confirm second time?)
7. after confirmation then print continue...

**Comment by thinkyhead** [comment]
> wrong (but message only)

If you're still seeing that then you should update.

**Comment by e-Mole** [comment]
No, message is now correct, but all others points are still valid.

**Comment by thinkyhead** [comment]
This should be a bit better now. `M125` was checking for SD print, but with SD print already paused by `M25` or LCD-based pause, it was getting the wrong answer.

**Comment by boelle** [comment]
@hamlet600 problem solved?

**Comment by e-Mole** [comment]
@boelle In my case - I did not test the last version. In January, however, this issue was still up to date.

**Comment by boelle** [comment]
we always need to test with latest bugfix 2.0

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
