### ISSUE TITLE
v_allowable为什么这么计算？

### ISSUE THREAD

**Issue by shiqingfeng** [MarlinFirmware/Marlin#12427]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by thinkyhead** [comment]
Marlin 2.0 uses `v_allowable_sqr` which requires less calculation.

**Comment by shiqingfeng** [comment]
需要较少的计算是什么意思？可以给出更详细的解释吗？

**Comment by thinkyhead** [comment]
For example, imagine that you want to know whether two points are within a certain distance of one another. You could do this:
```cpp
if (sqrt(sq(x2 - x1) + sq(y2 - y1)) < 10) { ... }
```
…but it is much faster to do this:
```cpp
if (sq(x2 - x1) + sq(y2 - y1) < 100) { ... }
```
