### ISSUE TITLE
Coders NEEDED

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1242]
So we git a decent amount of testers, but now we need some active coders that have time to spare

Currently i have listed 2 issues here that are rather old.... one is taken thou i belive...

https://github.com/ErikZalm/Marlin/issues/1220

List of coders so far:

@thawkins 
@vandarin
@fmalpartida

**Comment by boelle** [comment]
who could fix this one? https://github.com/ErikZalm/Marlin/issues/416

**Comment by thinkyhead** [comment]
Looking forward to all the issue links working once we've exhausted all these old ones!

**Comment by boelle** [comment]
well we are short of active coders that can worked focused on the milestones
