### ISSUE TITLE
[FR] Warning moving extruder motor with low extruder temp

### ISSUE THREAD

**Issue by Bezulba** [MarlinFirmware/Marlin#12435]
By default marlin has the feature enabled that you can't move the extruder motor when the extruder isn't heated. Only when I use the move axis option for the extrudermotor on my anet a6, I don't get a warning, it just doesn't move at all. Giving me the wrong impression something is wrong with the motor/cable/mainboard.

A warning would be nice, maybe even a check when you try to go into the move axis for the extruder menu?

**Comment by swilkens** [comment]
Which version of the firmware are you using?

Version bugfix-2.0.x has this feature, Motion -> Move Axis -> Extruder will show `Hotend too cold` if the nozzle is below whatever is set as the minimum temperature (175 by default afaik)
