### ISSUE TITLE
POWER_LOSS_RECOVERY Extruder Loop

### ISSUE THREAD

**Issue by hanif40** [MarlinFirmware/Marlin#12433]
I have a problem with the `POWER_LOSS_RECOVERY` in marlin 1.1.9 (also bugfix and up to 2.0), the problem is that when it recovers it makes everything perfect (returns to the correct position) but the extruder remains as in a loop between extrude and I do not extrude and never advance, what you notice is when you retract before printing (always talking about recovering the impression) it retracts a few centimeters (enough to remove the hotend filament) to then not extrude anything but the engine between yes and not.

In the configurations, activate the new fixtures and also leave as configured in version 1.1.8, now printing prints perfect, but the recovery after current loss there is no way that the extruder leaves that loop.

**Comment by hanif40** [comment]
154/5000
is the simplify3d that generates me the problem, change to 3d cure and it works very well.
I do not know what the simplify that causes the extruder loop can add.

SIMPLIFY3d

Starting
```gcode
G28 ; home all
G92 E0
G1 Z0.1 F1000
G1 X8.0 F2000
G1 Y60.0 E4.0 F1000.0 ; prime
G1 Y100.0 E8.5 F1000.0 ; prime
G92 E0
```

Ending
```gcode
M104 S0 ; turn off extruder
M140 S0 ; turn off bed
G91 ; use relative coordinates
G1 Z0.6 F5000 ; lift nozzle by 0.6mm
G90 ; use absolute coordinates
G28 X0 ; home X axis
G1 Y195 ; move Y axis to end position
M84 ; disable motors
M107 ; turn off fan
```

CURA3d

Starting
```gcode
G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode
M107 ;start with the fan off
G28 X0 Y0 ;move X/Y to min endstops
G28 Z0 ;move Z to min endstops
G1 Z15.0 F9000 ;move the platform down 15mm
G92 E0 ;zero the extruded length
G1 F200 E3 ;extrude 3mm of feed stock
G92 E0 ;zero the extruded length again
G1 F9000
;Put printing message on LCD screen
M117 Printing...
```

Ending
```gcode
M104 S0 ;extruder heater off
M140 S0 ;heated bed heater off (if you have it)
G91 ;relative positioning
G1 E-1 F300  ;retract the filament a bit before lifting the nozzle, to release some of the pressure
G1 Z+0.5 E-5 X-20 Y-20 F9000 ;move Z up a bit and retract filament even more
G28 X0 Y0 ;move X/Y to min endstops, so the head is out of the way
M84 ;steppers off
G90 ;absolute positioning
```

**Comment by thinkyhead** [comment]
See #12440 for an updated and optimized version of Power-Loss Recovery. Needs testing. Enable the `DEBUG_POWER_LOSS_RECOVERY` option in `power_loss_recovery.h` to get extra output to the serial console when recovering. (You should be able to connect a host when the "Resume"/"Cancel" menu appears and it will go back to recovery mode when it reboots.)

**Comment by hanif40** [comment]
the problem was solved by distilling that!

![image](https://user-images.githubusercontent.com/21147328/48595660-7c6eaf80-e934-11e8-93ad-c6a3bfcf3e48.png)

**Comment by thinkyhead** [comment]
I thought that might be involved. I'm not sure there's anything that can be done to work around it when saving power-loss data, but I will look at it. Does the G-code end up including `M83` when you use that option? Or does it just include a lot of `G92 E0` commands?

**Comment by boelle** [comment]
@hanif40 problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
