### ISSUE TITLE
[FR] [2.0.x] Ignore hotend temperature if target not set

### ISSUE THREAD

**Issue by ghulands** [MarlinFirmware/Marlin#12438]
### Description

I have a Formbot T-Rex 2 that has dual hotends that can be enabled or disabled by quickly unclamping it from the X-axis belt. A lot of the time I am only using the first extruder and leave the second one parked off to the side unclamped. I just started testing the 2.0.x firmware and got the Heating Failed message for the extruder that was unplugged (T1).

It would be good if a hotend can be disabled via an M-code so that it is not part of the temperature protection if it's disabled for that job.

**Comment by ghulands** [comment]
Tagging @Roxy-3D as they have a T-Rex 2+

**Comment by silentninja1** [comment]
The 2+ is totally different from the 2. They use different boards, 2+ is idex so each is on independent belts, ect. Roxy does not have a older 2 with the MKS Gen 1.4 board.

A more complete consideration for this case is to disable monitoring of a hotend that is not on, as in if temperature is 0 exclude from watchdog. This would be relevant to any multiple hotend system. Im not sure if theres any other issues in implementing such a thing though so ill let somebody who knows that section of code comment on if its feasible or not.

I can see it is something ive seen while working on a few machines, just didnt bother me enough to do anything about.

**Comment by ghulands** [comment]
The temperature reported is -15 for this printer when disconnected. Not sure if that is the same for all machines.

**Comment by silentninja1** [comment]
Thats based on the temp table for open circuit for enabled sensor. Not relevant to how I would look to implement though, which is ignore unless a non-0 target temperature is set.

**Comment by ghulands** [comment]
Sounds like a better approach than disabling via M-code. Updated title.

**Comment by TheSFReader** [comment]
Detail : I think an overhigh temp error should still be raised in the case of no target

**Comment by GMagician** [comment]
@ghulands you may close this, feature has been added

**Comment by boelle** [comment]
@thinkyhead what @GMagician said ^^^^

**Comment by InsanityAutomation** [comment]
Agreed @thinkyhead this one is done and can be closed.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by InsanityAutomation** [comment]
@boelle @shitcreek this is done
