### ISSUE TITLE
TMC2660 enable doesn't get pulled low

### ISSUE THREAD

**Issue by stefan85** [MarlinFirmware/Marlin#12447]
I made a board with an LPC1769 in combination with TMC2660 drivers (REARM pinning). After debugging I found that the enable lines of the drivers do not get pulled to GND to enable.

When I connect the enable pin to GND, the driver works fine. I can turn the motors off with M84. 
But somehow, the microcontroller doesn't control these pins. Is this a know issue, or is there someone else using this hardware combination?

**Comment by kAdonis** [comment]
@teemuatlut wrote in https://github.com/MarlinFirmware/Marlin/pull/11998#issue-220185771 :

>Add support for Trinamic TMC2660. Basically this means the Panucatt BSD2660 drivers.
Not every feature is written yet but I'd like to get the basic support going for a broader audience.
The drivers do not have an EN pin so the function is implemented in software through SPI, very similar to how TMC26x is not at the moment. The TMC2660 is based on 26x after all.

**Comment by stefan85** [comment]
I see. It is fixable with a jumper wire. Maybe in the future support could be added to pull this pin low.

Thank you for your answer and I will keep my eye on progressie for these drivers.

**Comment by boelle** [comment]
@stefan85 problem solved?

**Comment by stefan85** [comment]
Have not checked with latest firmware. Will try it this weekend

**Comment by boelle** [comment]
remember to use bugfix 2.0

**Comment by stefan85** [comment]
Problem is sovled, I can use software and hardware enable.

**Comment by boelle** [comment]
just curious, what was the fault?

**Comment by stefan85** [comment]
In a older version I used, I could only use software enable. But in later commit this was fixed. I tried it yesterday
