### ISSUE TITLE
new feature backlash compensation

### ISSUE THREAD

**Issue by hermes3008** [MarlinFirmware/Marlin#12449]
### Description

have some thing to compensate for backlash

like Repetier has

to help fix this

![c6a800a8017d669bab8712236c96b153_preview_featured](https://user-images.githubusercontent.com/28740393/48651220-6eb23c00-e9bf-11e8-8ab4-abdbc1d78ccb.jpg)

**Comment by AnHardt** [comment]
You might want to try
[2.0.x] Implementation of Backlash Compensation and M425 #11061

**Comment by marcio-ao** [comment]
Backlash compensation has been merged into upstream. Woohoo!

**Comment by boelle** [comment]
@hermes3008 problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
