### ISSUE TITLE
[FR] Add possibility to define multiple NEOPIXEL_PIN(S)

### ISSUE THREAD

**Issue by dough29** [MarlinFirmware/Marlin#12444]
Hello !

I'm using a WS2812b LED strip with an MKS Gen L v1.0 board.

The strip is wired to D4 pin and I was wondering if there is a way to define another pin (like D5) for a 2nd LED strip ?

I'm not familiar to C development and can't figure out if this feature is already implemented.

My idea is to have one strip on the left side of the printer and another one on the right side, they will behave the same.

I can wire the signal output from first strip to go to signal input of 2nd strip but it wont be really nice with "NEOPIXEL_IS_SEQUENTIAL" activated...

Thank you for reading me !

**Comment by AnHardt** [comment]
Is there any reason for not connecting both of the stripes to the same pin - in parallel?

**Comment by dough29** [comment]
That's a really good question !

I'll give a try and tell you the result ^^

**Comment by dough29** [comment]
So you are right !

I tested it and wiring the stripes to the same pin works great ^^

Thanks a lot.
