### ISSUE TITLE
G34 do nothing when enabling Z_STEPPER_AUTO_ALIGN

### ISSUE THREAD

**Issue by dough29** [MarlinFirmware/Marlin#12459]
I have a Creality CR-10 + MKS Gen L v1.0 + BLTouch (genuine) + Dual Z (one driver per Z motor), everything is working fine (G28, G29, printing and so on...).

You can find my custom config diff from bugfix-2.0.x here : https://github.com/MarlinFirmware/Marlin/compare/bugfix-2.0.x...dough29:test-z-auto-align

I enabled dual Z steppers auto-alignment :

`#define Z_STEPPER_AUTO_ALIGN`

I was thinking Y to go to 150 and X to 10 for a first Z probing and then X to 290 for second Z probing and alignment.

`Send: G34
Recv: ok`

Nothing happens.

Am I missing something ?

Thanks for reading me.

**Comment by dough29** [comment]
I found how to enable debug output so here is the result, did G28 just before :

Send: G34
Recv: >>> G34
Recv: Machine Type: Cartesian
Recv: Probe: BLTOUCH
Recv: Probe Offset X:-41 Y:-10 Z:-1.30 (Left-Front & Below Nozzle)
Recv: Auto Bed Leveling: BILINEAR
Recv:  (disabled)
Recv: 
Recv: set_bltouch_deployed(0)
Recv: > probing all positions.
Recv: >>> probe_pt(10.00, 150.00, raise, 0, probe_relative)
Recv:   current_position=(191.00, 160.00, 11.30) :
Recv: > PROBING FAILED!
Recv: <<< G34
Recv: ok

**Comment by GMagician** [comment]
>  PROBING FAILED!

it may give such error when position is not reachable. Can't extract your cnf from link so can't say more

**Comment by dough29** [comment]
Here are the files :
https://github.com/dough29/Marlin/blob/test-z-auto-align/Marlin/Configuration.h
https://github.com/dough29/Marlin/blob/test-z-auto-align/Marlin/Configuration_adv.h

For Z stepper auto align :

#define Z_STEPPER_AUTO_ALIGN
#define Z_STEPPER_ALIGN_X { 10, 290 }
#define Z_STEPPER_ALIGN_Y { 100, 100 }

I tried with lower values (my printer can easily reach 290) and nothen happens too.

**Comment by dough29** [comment]
Send: G34
Recv: >>> G34
Recv: Machine Type: Cartesian
Recv: Probe: BLTOUCH
Recv: Probe Offset X:-41 Y:-10 Z:-1.30 (Left-Front & Below Nozzle)
Recv: Auto Bed Leveling: BILINEAR
Recv:  (disabled)
Recv: 
Recv: set_bltouch_deployed(0)
Recv: > probing all positions.
Recv: >>> probe_pt(10.00, 10.00, raise, 0, probe_relative)
Recv:   current_position=(0.00, 0.00, 10.00) :
Recv: > PROBING FAILED!
Recv: <<< G34
Recv: ok

**Comment by GMagician** [comment]
I can't see what's wrong...
such error is raised when `position_is_reachable_by_probe` return `false`.
Validation is done with quote you see in

>  probe_pt(x, y)

output. In first example they are X10,Y150. Have you executed some G92 command?

**Comment by GMagician** [comment]
may you try to execute a G92 X0 Y0 post report you get?

**Comment by dough29** [comment]
I didn't plya with G92, here is the report :

(did G28 XY before)
Send: G92 X0 Y0
Recv: X:0.00 Y:0.00 Z:11.30 E:0.00 Count X:0 Y:0 Z:4520
Recv: ok
Send: G34
Recv: >>> G34
Recv: Machine Type: Cartesian
Recv: Probe: BLTOUCH
Recv: Probe Offset X:-41 Y:-10 Z:-1.30 (Left-Front & Below Nozzle)
Recv: Auto Bed Leveling: BILINEAR
Recv:  (disabled)
Recv: 
Recv: set_bltouch_deployed(0)
Recv: > probing all positions.
Recv: >>> probe_pt(10.00, 10.00, raise, 0, probe_relative)
Recv:   current_position=(0.00, 0.00, 11.30) :
Recv: > PROBING FAILED!
Recv: <<< G34
Recv: ok

**Comment by gloomyandy** [comment]
Can your machine get the probe (not the nozzle) to those locations? I suspect that is the problem. You have a fair offset for X which may be causing the issue.

**Comment by dough29** [comment]
BLTouch probe is left to the nozzle so X10 Y10 is where it can reach easily.

Xmin = 0 / XMAX = 320
Ymin = 0 / YMAX = 300

I tried with these settings :

  #define Z_STEPPER_ALIGN_X { 140, 160 }
  #define Z_STEPPER_ALIGN_Y { 160, 140 }

And it worked : you are right it looks like X,Y coordinates are out of reach, thank you !

**Comment by dough29** [comment]
So now my custom version is up to date and working Z stepper align : https://github.com/dough29/Marlin

Thanks a lot @gloomyandy 👍
