### ISSUE TITLE
After Preheat All Menue Options gone

### ISSUE THREAD

**Issue by AndreasHeisinger** [MarlinFirmware/Marlin#12456]
Hey,

ive installed Skynet Marlin on a Anet A8. 
Everything works fine. 
But when i start to preheat , the Menue is empty. No Options to move Axis, Preheat, Cooldown...
Also when Preheat Temperature is on. 
After Reset the Printer everything is visible. Start Preheat, the same no Menue Options.
Can anybody help me?

**Comment by Ludy87** [comment]
Skynet realy? Try Marlin Bugfix-2.0.x

**Comment by AndreasHeisinger** [comment]
Thank you! Can i use my configuration.h or should i edit the configuration.h form the bugfix ?

**Comment by Ludy87** [comment]
Change the bugfix configuration files (Configuration.h and Configuration_adv.h) to your needs.
The copy would lead to errors.

**Comment by thinkyhead** [comment]
We don’t do support for modified forks of Marlin. Please contact the Skynet project.
