### ISSUE TITLE
Pins.h needs cleanup

### ISSUE THREAD

**Issue by Lukelectro** [MarlinFirmware/Marlin#1245]
For example, in the sanguinololu pin assignments:

#define FAN_PIN            -1
 #if FAN_PIN == 12 || FAN_PIN ==13
  #define FAN_SOFT_PWM
#endif

Also, the various ifdef's could use clearer indentation: (In the part for GEN6)

    #define HEATER_2_PIN    -1
    #if MB(GEN6)
    #define HEATER_BED_PIN  -1    //changed @ rkoeppl 20110410
    #define TEMP_BED_PIN    -1    //changed @ rkoeppl 20110410 
    #else
    #define HEATER_BED_PIN   1    //changed @ rkoeppl 20110410
    #define TEMP_BED_PIN     0    //changed @ rkoeppl 20110410
    #endif
    #define SDPOWER          -1

**Comment by boelle** [comment]
also as we say in the readme.... if you have a fix dont open an issue but make a pull request instetad

clsing this one as it clearly not an issue....

**Comment by thinkyhead** [comment]
I would like to see pins.h get proper indentation also, and perhaps even split it up (similar to the languages files). We just have to make sure not to step on someone who might be adding new hardware support while the changes are still fresh.
