### ISSUE TITLE
[2.0.x]   Reprap discount full graphic smart controller

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#12454]
I undefined LCD_TIMEOUT_TO_STATUS  in configuration_adv because I don't want the lcd to return to the status screen after a while. This worked with marlin 1.8 but with the current 2.0 branch, the lcd returns to the status screen after some seconds. Do I have to set LCD_TIMEOUT_TO_STATUS to 0 to disable this feature?

I also noticed that during homing, there are two decimals displayed at the z axis. The second decimal does not fit on the lcd, you can just see a few pixels of it.

**Comment by Ludy87** [comment]
Marlin 1.1.8 and Bugfix-2.0.x is same of LCD_TIMEOUT_TO_STATUS equal!

Set to 4294967295 for 49 day 17 h

**Comment by thinkyhead** [comment]
Yes, you can set it to 0 to disable it in Marlin 2.0.

**Comment by thinkyhead** [comment]
As for the LCD issue, I assume you refer to the graphical LCD. I’ll look into it.
