### ISSUE TITLE
1.1.9 G33 crash head. (Probe Z-offset)

### ISSUE THREAD

**Issue by Cyper77** [MarlinFirmware/Marlin#12465]
> in delta calibration>Probe Z-offset item dont work properly. 
because menu item name must be "paper Z-offset" not probe.
my carbon fiber rod broken beacuse of this menu when probe attached.
zprobe works well but movement didnt stop and Bammm to table...
i found explanation in marlin sources. this was very sad to me :(
PAPER ! not a probe...
"G33 P-1" > Check the z-offset with a center probe and paper test.

**Comment by thinkyhead** [comment]
The `G33` feature is not well understood by anyone except its author, @LVD-AC. I'm not sure what the meaning of "with a center probe" is, or why the feature would even try to do anything without a probe attached.

**Comment by LVD-AC** [comment]
To probe for Z-offset G33 needs to probe (with the probe deployed) and do a paper test (with the probe retracted). G33 does call the right deploy() and retract() routines at the right time, but those do not pause if the probe requires user interaction. Detachable or manual deployable probes are just not supported in Marlin. IMO such a probe type is missing in configuration.h; and the implementation would be in the deploy() and retract() routines to send a message to deploy or retract the probe manually, and to wait for user interaction when done.

**Comment by Cyper77** [comment]
funny :), i explain movement (for delta Normally Opened(NO) probe attached)
-head moves to home z
-head moves to table
-first touch and retract
-and moves to table again for second touch maybe but full force
-this time software dont bother the probe signal, then still push head to table
-crash-bammm-smash etc....
