### ISSUE TITLE
Help with tmc2130

### ISSUE THREAD

**Issue by italocjs** [MarlinFirmware/Marlin#12460]
Hello guys, i've been trying to use the TMC2130 for the past two weeks since i bought it, but haven't managed to get a single successful print so far.

I bought three TMC2130 and replaced my (working) a4988.  i'm using the driver on standalone mode (soldered jumper), with a 15mm heatsink above it, and a 40mm fan directly above the drivers, so i don't believe overheating is a issue (i can keep my finger at it while working easily)..

I'm getting constant layer shifting on it, here are the things i already tried:
- decreased acceleration to 1000 on every axis
- reduced printing speed to 100mm/s
- reduced movement speed to 150mm/s
- increased current (1.1a rms = 1.7A peak | stepper is 1.7A)
- disabled S-Curve

Does anyone have any idea on how to fix this? If I put back the A4988 the printer works perfectly! Also, if possible, I'd like to keep using the standalone mode.

Printer kinematics: corexy
Steppers: 4.2kgf - 1.7a  17hs4401
Drivers: TMC2130 on X Y and Z
Firmware: latest 2.0.x (today's version)

**Comment by italocjs** [comment]
Update: found some information about stealthchop not being a good alternative for high speed, and when using standalone mode this is always activated.  i'm gonna change the driver wiring to enable only spreadcycle and try again.

**Comment by italocjs** [comment]
Changing the driver to spreadcycle helped but not solved 100%, im buying two tmc2208 to try before giving up and going back to the a4988

**Comment by swilkens** [comment]
There is some activity surrounding layer shift issues in the firmware at the moment:

https://github.com/MarlinFirmware/Marlin/issues/12403

I assume you've looked at things such as belt tension to make sure this isn't a mechanical issue?

**Comment by gloomyandy** [comment]
Just be aware that tmc2208 is in stealthchop by default and it is not easy to reconfigure them into spreadcycle, you can't do it via jumpers.

**Comment by italocjs** [comment]
> Just be aware that tmc2208 is in stealthchop by default and it is not easy to reconfigure them into spreadcycle, you can't do it via jumpers.

I've disabled the custom configs for tmc2130 on marlin and changed the TMC2130 to standalone as spreadcycle and it fixed the lost steps for me, so i'll keep trying on it, maybe the problem people here are having might be related to the transition between stealthchop and spreadcycle, 

About the 2208, i never used them before, but from what i read, i can change it using uart, just like the tmc2130 changes over spi

**Comment by italocjs** [comment]
> There is some activity surrounding layer shift issues in the firmware at the moment:
> 
> #12403
> 
> I assume you've looked at things such as belt tension to make sure this isn't a mechanical issue?

Confirmed, not mechanical issue, when i'm using the A4988 i have no lost steps

**Comment by gloomyandy** [comment]
Yes you can change them over uart, but you will probably need a uart per device rather than being able to share one set of pins like you can with spi. There are other ways but that gets more complex.

**Comment by boelle** [comment]
@italocjs problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
