### ISSUE TITLE
Not enough RAM Mega 2560

### ISSUE THREAD

**Issue by ISAndreiva** [MarlinFirmware/Marlin#12463]
Hello!
How could i decrease the RAM usage on my configuration ?
TIA
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2592262/Marlin.zip)

**Comment by Roxy-3D** [comment]
What are your values?   What do you want to get to?

Bump this down to 7:    #define GRID_MAX_POINTS_X 7
Turn this off:  // #define SDCARD_SORT_ALPHA

**Comment by ISAndreiva** [comment]
Thanks i will try that tommorow also why if i try to use tmc2130 insted of tmc2130_standalone it gives a error

**Comment by Roxy-3D** [comment]
I don't know about the tmc stuff....   Somebody else will need to jump in on that.

**Comment by RudyBenner** [comment]
Fix one problem at a time. Unless you like vertigo.

**Comment by ISAndreiva** [comment]
Yeah true thanks

**Comment by ISAndreiva** [comment]
Thanks the sorthing thing helped me :)
Now those tmcs

**Comment by teemuatlut** [comment]
If you want to report an error, it's usually helpful to describe said error.

**Comment by ISAndreiva** [comment]
Thanks for the advice but I got it working somehow thanks
