### ISSUE TITLE
[2.0.x] pins_RURAMPS4D_13.h error on definitions in display 

### ISSUE THREAD

**Issue by axl12ap** [MarlinFirmware/Marlin#12479]
Good morning,
there're 2 issues at lines 208 and 209 in this file.

The correct definitions are:

#define LCD_PINS_RS     63
#define LCD_PINS_ENABLE 64

under the "#elif ENABLED(REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER)" condition, because they cannot be same as LCD_PINS_D6 and LCD_PINS_D7 also.

Please correct them.

**Comment by boelle** [comment]
@axl12ap problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
