### ISSUE TITLE
[2.0.x, RFC] "Print from SD" as the last menu option

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#12487]
We modify our firmware to place the "Print from SD" as the very last option of the menu. The reason we do this is because it is a very commonly used option and moving to the bottom can be done with a quick flick of the wrist on the encoder. In Marlin upstream, it is placed in the second spot, presumably to make it accessible, but paradoxically that placement makes the user turn the encoder by a precise amount, which is hard.

I would like to propose that the "Print from SD" be moved to the very bottom. It may seem counter-intuitive to have the most used feature on the bottom, but once you try it, you will love it!

**Comment by Ludy87** [comment]
what about the users with button? Click, Click, Click ...

**Comment by swilkens** [comment]
With this frequently used option at the bottom of the menu, it might end up out of the visible menu scale if other features are enabled - requiring a user to have to scroll to even see the option.

If you know it's there you might prefer this, but it seems indeed counter intuitive to have a frequently used option out of screen.

**Comment by InsanityAutomation** [comment]
For scroll wheels, I agree with marcio. This is also closer to the 1.1.9 position where it's close to the bottom. Tier 1 manufacturing facilities actually have a workload calculation scale and a fine move is considered to take 2.5-3x the tact time as a rough move depending on if a tool is involved.

**Comment by marcio-ao** [comment]
@Ludy87: Good point. It probably would be a hindrance with a button. It sounds like the "ideal" location depends on whether you have a rotary encoder or not.

Even though it is a relatively small change to our FW, it involves moving a few lines of code from one position to another in "main_menu.cpp". The diffing algorithm in git isn't particularly smart about code that is moved (it treats it as a separate deletion and addition), so it means that if I move it and the original code is changed upstream, it generates a conflict I have to manually resolve.

So I guess I am just asking for a config option to do this, so I wouldn't have to deal with the conflicts. Or if possible, perhaps Marlin could configure the placement automatically based on whether the user has a rotary wheel or buttons -- that would help everyone. As @InsanityAutomation has pointed out, it really does save time to have it at the bottom if you have a rotary encoder.

**Comment by marcio-ao** [comment]
> With this frequently used option at the bottom of the menu, it might end up out of the visible menu scale if other features are enabled - requiring a user to have to scroll to even see the option.

@swilkens: There will always be features that are hidden unless the user scrolls, so I'm not sure this is a strong argument against using the most efficient placement for the particular controller. That said, just making it a configuration option and entirely up to the user would be a good compromise.

**Comment by Ludy87** [comment]
Or a other idea, the first position🤔

**Comment by InsanityAutomation** [comment]
First position is always back / exit so it would be the second, and thats exactly the scenario compared against above. Given some manufacturers issues with noise on the button line causing a ton of clicks, id be concerned changing that behavior.

**Comment by marcio-ao** [comment]
It looks like in the latest Marlin, the SD item is at the bottom, so closing this out.

**Comment by InsanityAutomation** [comment]
FYI see https://github.com/MarlinFirmware/Marlin/pull/12893/ for the rest of the menu fixups
