### ISSUE TITLE
[bugfix-2.0.x] Warnings: ultralcd.h:383:127: warning: type qualifiers ignored on function return type

### ISSUE THREAD

**Issue by dahuafschmied** [MarlinFirmware/Marlin#12486]
There are 5 warnings:
```
ultralcd.h:383:127: warning: type qualifiers ignored on function return type
static const char * const scrolled_filename(CardReader &theCard, const uint8_t maxlen, uint8_t hash, const bool **doScroll**);


MarlinSerial.cpp:47:68: warning: missing initializer for member 'MarlinSerial<MarlinSerialCfg<0u> >::ring_buffer_t::tail'
template<typename Cfg> typename MarlinSerial<Cfg>::ring_buffer_t **MarlinSerial**<Cfg>::tx_buffer = { 0 };


M200-M205.cpp:64:38: warning: enumeral and non-enumeral type in conditional expression
const uint8_t a = (i == E_AXIS **?** E_AXIS_N(target_extruder) : i);

lcdprint_hd44780.cpp:866:1: warning: missing initializer for member '_hd44780_charmap_t::idx2'
```

and

```
stepper.cpp:1110:8: warning: 'r1' may be used uninitialized in this function
and so on with r5,6,7,8,...
```

my repository:
https://github.com/dahuafschmied/Marlin-for-Anycubic-i3-Mega/tree/bugfix-2.0.x

**Comment by Ludy87** [comment]
I tried your config (not Fork), no error

**Comment by dahuafschmied** [comment]
Set Arduino Compiler warnings to All.
![arduino](https://user-images.githubusercontent.com/3955019/48768460-6147cb00-ecb9-11e8-83ed-c2a7a98eb4ff.png)

**Comment by Ludy87** [comment]
I have compile with PlatformIo, no warning

**Comment by dahuafschmied** [comment]
Most of the "Users" (not devs.) are compiling with Arduino!
And no warning with any compiler -> better code quality

**Comment by Ludy87** [comment]
what's your Version from Arduino IDE

**Comment by dahuafschmied** [comment]
1.9.0-Beta as described here:
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/README.md
(my daily comment on Arduino: "scheiß java") :-)

**Comment by thinkyhead** [comment]
Thanks! We're not too worried about warnings, and we'll continue to clear them up as we go along.
