### ISSUE TITLE
m600 function not working

### ISSUE THREAD

**Issue by ondrax1** [MarlinFirmware/Marlin#12494]
Hello, i have question. I have Anycubic with derhopp marlin 1.1.x  I update original FW, becouse i need function m600 and changing filament. But i have problem with this. I setup 
#define ADVANCED_PAUSE_FEATURE

and 

#define NOZZLE_PARK_FEATURE

After check, arduino ide wrote me     #error "ADVANCED_PAUSE_FEATURE currently requires an LCD controller or EMERGENCY_PARSER." And i setup function Emergency parser. After that i flash this FW to my printer. Pausing is working! (fantastic) but i dont know how i can continue print, after change filament. If i try make pause, temperatures goes to 0 and pring progress is stopped.

video here: https://youtu.be/RSgZyg1jOtM

(link here https://github.com/derhopp/Marlin-with-Anycubic-i3-Mega-TFT)

Sorry for my bad english.

Thank you so much

**Comment by thinkyhead** [comment]
To continue without an LCD you have to send `M108`.

**Comment by ondrax1** [comment]
Hello, i use pronter face. M600 in gcode make me pause, i change filament. Send m108 via ptonter face and problem
![image](https://user-images.githubusercontent.com/45208636/48916470-bedb4380-ee82-11e8-8c1b-fd3910b10b65.png)

enable "NOZZLE_PARK_FEATURE" (Configuration.h), "ADVANCED_PAUSE_FEATURE" (Configuration_adv.h) and "EMERGENCY_PARSER" (Configuration_adv.h).

**Comment by thinkyhead** [comment]
Try sending `M108` two or more times.

**Comment by boelle** [comment]
@ondrax1 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead think we can close this one
