### ISSUE TITLE
Servo pulse width

### ISSUE THREAD

**Issue by Studna3D** [MarlinFirmware/Marlin#12497]
Where can I change `#define MIN_PULSE_WIDTH`  or `#define MAX_PULSE_WIDTH`    for servo in code? 
I use MKS Sbase board. After upstream code servo doesn't move. I know this problem has previously resolved pulse change, because I use a digital servo HS-5645MG.

Thanks you for answer

**Comment by RudyBenner** [comment]
look for servo_private,h

**Comment by p3p** [comment]
Update the platformio lpc176x framework and see if that helps, there are issues with the hardware PWM so it has been disabled temporarily.

**Comment by Studna3D** [comment]
I tried it, but it didn't help.

**Comment by boelle** [comment]
@Studna3D try latest bugfix 2.0

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
