### ISSUE TITLE
SBASE missing?

### ISSUE THREAD

**Issue by RudyBenner** [MarlinFirmware/Marlin#12518]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by RudyBenner** [comment]
I no longer see mention of SBASE on marlinfw.org? 
Have they been banished?

**Comment by Ludy87** [comment]
Look here https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/README.md
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/Marlin/src/config/examples/Mks/Sbase
<del>http://marlinfw.org/docs/development/boards.html</del>

**Comment by RudyBenner** [comment]
Yes, that last link, show me where SBASE is please.
http://marlinfw.org/docs/development/boards.html

**Comment by Ludy87** [comment]
Sorry wrong link

**Comment by AnHardt** [comment]
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/core/boards.h#L175

It doesn't make much sense to search in the 1.x.x branches.

**Comment by RudyBenner** [comment]
so NOT in marlinfw.org

**Comment by thinkyhead** [comment]
> so NOT in marlinfw.org

This board list is maintained in a Google Doc:
http://marlinfw.org/docs/configuration/configuration.html#motherboard
