### ISSUE TITLE
PIDTEMPBED stops bed heating from LCD or print, heats through Pronterface (MAX_BED_POWER resolves issue)

### ISSUE THREAD

**Issue by NXSmiggy** [MarlinFirmware/Marlin#12511]
Running my Ultrabase through a MOSFET on an stock A8 board with Marlin 1.1.8. When I do PID tune through Pronterface the bed heats up no problem and completes the tune, but when printing from SD or using the Preheat PLA command on the printer to heat the bed, nothing happens and then I get "Bed Heating Failed"

As its working through Pronterface I know the wiring is ok

https://pastebin.com/q5ptKKc5

UPDATE: Disable PIDTEMPBED and enable MAX_BED_POWER allows printer control of bed heater again

**Comment by Ludy87** [comment]
Try Marlin [Bugfix-2.0.x](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x)

**Comment by thinkyhead** [comment]
…or Marlin 1.1.9. We don't provide updates for old releases.

**Comment by boelle** [comment]
@NXSmiggy problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
