### ISSUE TITLE
Marlin/src/sd/cardreader.cpp: if enabled AUTO_REPORT_SD_STATUS build failed

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#12516]
If you compile with AUTO_REPORT_SD_STATUS you'll get compile error because block defined two times

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/sd/cardreader.cpp#L118
and

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/sd/cardreader.cpp#L1053

So what instance of this is real one?

**Comment by alexxy** [comment]
Seems like related to 66580f32c2f4d39a82b77e4b6982e7ea6dde0766

**Comment by Ludy87** [comment]
remove Line 118-124 and try again

https://github.com/MarlinFirmware/Marlin/blob/fd2998efd5fb888eb1deb432c6790c3d506060c0/Marlin/src/sd/cardreader.cpp#L118-L124

**Comment by alexxy** [comment]
I already did it. Just not sure what instance supossed to be main one
