### ISSUE TITLE
[Bugfix-2.0 ]Linadvance 1.5 and 1.0 and the different values of K

### ISSUE THREAD

**Issue by mr-miky** [MarlinFirmware/Marlin#12519]
It happened to me, by mistake, to print gcode from the uSD or octoprint that had been prepared for Marlin 1.1.x.
The printer seemed crazy, then analyzing I found that the value of K sent  was for linadvance 1.0.

I wonder if it is not the case to check the value of K received and if it is outside an acceptable range, report it as an error or warning.

**Comment by thinkyhead** [comment]
`M900` already throws an error for out-of-range values, and won’t update the K value if it is outside the acceptable range, which is from 0 to 10. Marlin 1.1.9 and 2.0.x both have version 1.5 of Linear Advance.

**Comment by mr-miky** [comment]
So, theoretically, the printer should not print it?

In any case, the gcode files were certainly 1.1.8 or even earlier.
I have never updated the fw to 1.1.9 because I'm dedicated to 2.0 ...

Tonight I try again and see if it reports specific errors / warnings ...

**Comment by boelle** [comment]
@mr-miky still an issue?

**Comment by boelle** [comment]
@thinkyhead thinkwe can close this one
