### ISSUE TITLE
Ender-3 Pro updated _Statusscreen.h

### ISSUE THREAD

**Issue by Lord-Quake** [MarlinFirmware/Marlin#12537]
Here is a very mynute contribution from myself to the Marlin community :-)

Having an Ender-3 Pro I'd like to have the name shown in the status display.
After having stumbled on a YT video posted by Scott in January '18 I finally figured out how to make the changes.

![ender-3_pro_display](https://user-images.githubusercontent.com/29223282/48977975-1d800780-f0a5-11e8-8fe2-5178137688b2.jpg)

I created a folder `..\example_configurations\Creality\Ender-3 Pro`  and copied the files from the Ender-3 folder. You will then need to swap the file _Statusscreen.h with this one:

[_Statusscreen.zip](https://github.com/MarlinFirmware/Marlin/files/2612984/_Statusscreen.zip)

Maybe it's worth adding... ?

**Comment by Ludy87** [comment]
this isn't for Marlin 2.0

**Comment by thinkyhead** [comment]
Thanks! I’ll adapt your bitmap for Marlin 2.0 and stick it in the folder with the Ender 3 configuration, which already has the Creality version of the Ender logo. Is there any difference between the Ender 3 and the Ender 3 Pro that would require us to also have a separate `Configuration.h` file for it?

**Comment by Lord-Quake** [comment]
Thanks Scott! Both printers are the same concerning software so the `Configuration.h` would also be the same.
Only cosmetic difference would be `#define CUSTOM_MACHINE_NAME "Ender-3 Pro"` but that would be up to the end user.

**Comment by thinkyhead** [comment]
Ok, thanks! I’ll just put the extra status logo into a sub-folder, then. With the new scheme, the logo part is all that’s needed. Everything else comes from our core bitmaps file now.

**Comment by boelle** [comment]
@Lord-Quake problem solved?

**Comment by Lord-Quake** [comment]
Yes sir :-)

**Comment by ETE-Design** [comment]
Where to find the Ender-3 Pro Status Screen? Can only find the one for the Standard Ender-3

**Comment by J0hnMatrix** [comment]
Would like to have the Ender-3 Pro status screen too :)

**Comment by xtianpaiva** [comment]
Here @Lord-Quake 's `Ender-e Pro` icon ported to Marlin 2.0.x https://raw.githubusercontent.com/xtianpaiva/Marlin/ender-3-pro/Marlin/_Statusscreen.h
