### ISSUE TITLE
TMC2208 with weird noise when near the hybrid threshold value

### ISSUE THREAD

**Issue by italocjs** [MarlinFirmware/Marlin#12531]
Steps to reproduce:
Set the hybrid threshold to 60

>Move the head in a speed of 50 super silent
>Move the head in a speed of 59  (still in stealthchop) but shows some weird noises (kinda looks like it is changing from stealthchop and spreadcyle many times in the same move)
>Move the head in a speed of 70 loud, but normal for spreadcycle

Marlin version:  1.1.9
Drivers: TMC2208

**Comment by italocjs** [comment]
Also, not sure if its a problem with my driver, but the spreadcycle is way louder than any a4988!

**Comment by marcio-ao** [comment]
@italocjs: We've seen this behavior on the TMC2130 as well. Basically you have to avoid running the steppers anywhere near the threshold. In our FW, I set the threshold to 72, which when multiplied by 60 corresponds to a feedrate of 4320, which hopefully is a peculiar enough number that it doesn't show up in practice.

**Comment by pipersw** [comment]
I have both of them, and no noise @24V. 12V is to lower for these drivers.

**Comment by boelle** [comment]
@italocjs problem gone?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by italocjs** [comment]
Hi boelle, sorry i didnt reply, the issue is not solved at least for the last time i updated the firmware (on january this year), it stopped bothering me because i changed the driver to run on stealthchop all the time.  You can close this, but im not sure if it was fixed

**Comment by boelle** [comment]
@italocjs have you tried with new copy of bugfix 2.0?

**Comment by boelle** [comment]
i mean tried with 24V, trinamic do need above 18V to become noiseless

**Comment by italocjs** [comment]
Not with the latest version, i tried with mid-january latest bugfix on 2.0

Ill try testing with a 24v psu and post the result here.   If you want, you can close the issue

**Comment by boelle** [comment]
only you and @thinkyhead can close

there should be a close button  below but only you can see it

**Comment by boelle** [comment]
@italocjs please click close button below
