### ISSUE TITLE
[Bugfix 2.0] M106 ignored for Tools >0

### ISSUE THREAD

**Issue by akurz42** [MarlinFirmware/Marlin#12534]
### Description

In the latest Bugfix 2.0 versions the commands controlling the part cooling fans are ignored when a tool other than 0 is set. This used to work before (I have a version from 9th September that works fine),

### Steps to Reproduce

Connect to printer. Default Tool 0 is set.
```gcode
M106 S255
M107
T1
M106 S255
M107
T0
M106 S255
M107
```
**Expected behavior:** [What you expect to happen]
After `M106 S255` the part cooling fan is started at full speed, no matter which tool is set.

**Actual behavior:** [What actually happens]
The fan only works when Tool 0 is set.
Steps 1-4 are ok. Steps 5-6 show no effect at all. Steps 7 to 9 work fine again. All GCODEs are confirmed with "ok" in the terminal.

#### Additional Information

I am using a RADDS board and a THC-01 (3 materials) with a single hotend (SINGLENOZZLE is set). Settings in recent versions have always been the same as with the version from 9th September. The older version works, recent versions don't.

I've tried to address the fan directly (`M106 P0 S255`), used all kinds of combinations with FANMUXx_PIN to no avail.

**Comment by thinkyhead** [comment]
With `SINGLENOZZLE` you need to specify `M106 P1` when tool index 1 is selected, because `SINGLENOZZLE` remembers fan speeds on a per-tool-index basis. If no `P` parameter is given, `M106` currently assumes tool index 0. This may change in the future because slicers don’t know to do this when managing fan speeds on a single nozzle setup.

**Comment by akurz42** [comment]
Hi thinkyhead,

I've tried the P parameter, of course. When a tool other than 0 is set, no M106 command shows any effect, no matter if I use P0, P1, or P2 (I have 3 Extruders). That's valid for all combinations. I've tried all "P" parameters on all tools. Only M106 P0 S255 works when Tool 0 is set. When tool 1 is set nothing works, including M106 P1 S255.

Simply said: I haven't found an M106 command that makes the fan spin with a tool set other than 0.

Updated version of the test:

1. Connect to printer. Default Tool 0 is set.
2. M106 P0 S255
3. M107
4. T1
5. M106 P0 S255
6. M106 P1 S255
7. M106 P2 S255
8. M107
9. T0
10. M106 P0 S255
11. M107

1. works. None of the commands in 5-7 show any effect. 10 works.

Also, like I said I have an older version of bugfix 2.0.x running that works all right. Furthermore the way it's currently implemented - even if it would work - wouldn't work with most slicers right now as they don't use the P parameter at all. They assume that there's one part cooling fan, which especially with a single nozzle seems plausible enough to me.

Regards,
Alex

**Comment by InsanityAutomation** [comment]
Give this a shot and see if it does what youre looking for

https://github.com/InsanityAutomation/Marlin/tree/SingleNozzleM106Tweak

I modified multi extruder to default to active_extruder if P is not set, then set single nozzle to always set p to 0 before writing the fan speed, since the current command was still using the P value for the fan output setting. Also moved extra fan speeds above a branch which could return, causing it to never update a value.

**Comment by akurz42** [comment]
Ah, bad timing - I've just started a 13 hour print job, but I'll test it first thing tomorrow morning. Thanks for the effort!

**Comment by InsanityAutomation** [comment]
No problem. While youre at it, try the new single nozzle retract / purge and park at tool change with differing temps :)

**Comment by akurz42** [comment]
Sounds cool! On my testing list now :-)

**Comment by InsanityAutomation** [comment]
Adding these as well as storage for alternative extruder temps and fan speeds made the change in behavior you referenced, so at least there will be a positive reason (and no more tool change scripts in the slicer!)

**Comment by akurz42** [comment]
Bad news, then good news, then bad news again:
My print failed relatively early (bad), so I could test the tweak earlier than expected (good). Unfortunately the behaviour is exactly the same as before (bad):

T0
M106 S255 - works

T1
M106 S255 - doesn't

T1
M106 P1 S255 - doesn't work either.

Pity :(

**Comment by InsanityAutomation** [comment]
And you used the branch I linked, not current head right?

**Comment by akurz42** [comment]
Absolutely. "Marlin-SingleNozzleM106Tweak.zip" downloaded from "InsanityAutomation/Marlin - forked from MarlinFirmware/Marlin"

**Comment by thinkyhead** [comment]
From what I can gather, fan speeds ~~don't~~ may not take effect until the planner does a move. See if a simple `G1` does anything after setting fan speeds.

**Comment by thinkyhead** [comment]
Hmm, well actually, as long as `manage_inactivity` is being called, then `planner.check_axes_activity()` should be applying the set fan speeds when there are no blocks queued.

**Comment by thinkyhead** [comment]
Please ZIP your `Configuration.h` and `Configuration_adv.h` files and drop it on your next reply so that we can check them over.

**Comment by akurz42** [comment]
Ok, here's what I've tested:
```
T0, M106 S255, M107 --> works
T1, M106 S255, M107 --> nothing
T1, M106 P1 S255, M107 --> nothing
T1, M106 P0 S255, M107 --> nothing
T1, G1, M106 S255, M107 --> nothing
T1, G1, M106 P1 S255, M107 --> nothing
T1, G1, M106 P0 S255, M107 --> nothing
T1, M106 S255, G1, M107 --> nothing
T1, M106 P1 S255, G1, M107 --> nothing
T1, M106 P0 S255, G1, M107 --> nothing
T1, G1, M106 S255, G1, M107 --> nothing
T1, G1, M106 P1 S255, G1, M107 --> nothing
T1, G1, M106 P0 S255, G1, M107 --> nothing
```
Not really surprised as I've figured out something's wrong when the fan stopped at the first tool change in an actual print. The print went on fine with loads of G1s, only the fan was off.

I've attached my configs for the version I'm currently testing with, downloaded on 24th Nov. That's the one that doesn't work.
I've also added the config of a version I've downloaded on 9th September. This one works fine.

[Marlin-18-11-24.zip](https://github.com/MarlinFirmware/Marlin/files/2626951/Marlin-18-11-24.zip)
[Marlin-18-09-09.zip](https://github.com/MarlinFirmware/Marlin/files/2626952/Marlin-18-09-09.zip)

**Comment by akurz42** [comment]
Hi,

just checking in to see if the requested configs helped in any way?

Alex

**Comment by InsanityAutomation** [comment]
Holidays make for chaos. I'm struggling on automotive shutdown work and will hopefully be back to this soon. I have a creality crx set aside to test with.

**Comment by akurz42** [comment]
Hey, you do this for free in your free time, so please don't feel pushed. Enjoy the holidays and have a look next year if you want. No pressure. I just wanted to make sure the thread isn't forgotten.

For now the old, working version is fine.

Thanks!
Alex

**Comment by InsanityAutomation** [comment]
I'd much rather be working on this than the FANUC robot over profisafe on an s7 plc that's been consuming my time! You know the OEM spec is overly complicated when the Rockwell guys stop saying should've used AB and start saying they're glad it's you not them.... Lol

**Comment by akurz42** [comment]
Had to google most of what you've just said, but I sure want one of these robots :)
Maybe create a Marlin fork to control them? ;)

**Comment by InsanityAutomation** [comment]
@akurz42 please try the latest `bugfix-2.0.x` to confirm whether the above patch works.

**Comment by akurz42** [comment]
Sorry - got sidetracked by life...

Tested now and found all working. Big thanks and sorry for the late reply.

Alex
