### ISSUE TITLE
PID for Bed instead tunes Hot End

### ISSUE THREAD

**Issue by dorfman2** [MarlinFirmware/Marlin#12556]
### Description

While trying to PID tune my bed with the command
M303 E-1 S60 C10

It starts the test on my Hot End instead of the bed

### Steps to Reproduce

1. Start up Printer
2. Connect Via Octoprint Version 1.3.9 terminal
3. Send message "M303 E-1 S60 C10"

**Expected behavior:** 

Heated Bed should be tuned

**Actual behavior:**

The Hot end is tuned

#### Additional Information

**Printer**
Anet A6 (MOTHERBOARD BOARD_ANET_10)
External Mosfet for heated bed.
Marlin 2.x

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2629702/Marlin.zip)

Also, turning on PID
`#define PIDTEMPBED`
Causes the bed to not work at all.

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by Ludy87** [comment]
Same issued https://github.com/MarlinFirmware/Marlin/issues/12468

**Comment by dorfman2** [comment]
@Ludy87 Thanks and sorry for the duplication. Should I merge the issue or close mine?

Edit - I wrote this before reading the issue referenced. I'm writing the new firmware to my Anet, and will close the issue if the bugfix works.

**Comment by RudyBenner** [comment]
Line 436 in Configuration.h
You did not enable pidbed.

**Comment by dorfman2** [comment]
> 
> 
> Line 436 in Configuration.h
> You did not enable pidbed.

When attempting to run "M303 E-1 S60 C10," I had `#define PIDTEMPBED` enabled. I turned it off after PID tuning failed, because with it on the heated bed would not work at all. 

It sounds like I am running the firmware with the bug referenced in [https://github.com/MarlinFirmware/Marlin/issues/12468](url)

(edit - added description)

**Comment by dorfman2** [comment]
Confirmed Bed PID Tuning working.

Was using V62, Now on V63.

Thank you to @Ludy87 @RudyBenner for the prompt responses.
