### ISSUE TITLE
[2.0.x] SWITCHING_NOZZLE incorrect at startup and after pause.

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#12553]
When SWITCHING_NOZZLE is active, at startup Marlin does not initialize the servos to their correct initial positions. As a workaround I have added an `enqueue_and_echo_commands_P("T1\nT0");` to Marlin's startup, but this is a kludge and it seems like there should be a way to initialize things without causing the nozzles to move at power on.

A second related problem happens if the print is paused using M25 (from the LCD) and the user does something to cause the nozzle to switch over to the other one from the LCD. When Marlin resumes the print, it will do so from the wrong nozzle. It seems like when a pause happens, Marlin should save the `active_nozzle` so that it can be restored on resume.

**Comment by thinkyhead** [comment]
> at startup Marlin does not initialize the servos to their correct initial positions

See if #12559 helps (once it is passing Travis CI).

**Comment by marcio-ao** [comment]
This seems better now. Closing.
