### ISSUE TITLE
LCDs backlight control support ? (brightness/blink/on-off/animation)

### ISSUE THREAD

**Issue by yucelll** [MarlinFirmware/Marlin#12569]
Hello. I have an idea:

128x64 GLCD, 
2004 4x20 Character LCD
or other backlight LCDs

Note: LCD's backlight connected (+) and (-) with 100k resistance on board. If we want control the backlight, we diassemble (-) wire and connect to marlin cpntrol pin with transistor or mosfet.

I think;
**1. Brightness**: Users adjust change their LCD panel backlight (limit>0 - 255 PWM control)
Three Option for this: 

- Day Light(%100)
- Night Mode (%50 or etc..)
- Custom Mode (Users option %10 -%100)

**2.Blink**: If printer error(max temp,min temp,axis problem.. etc) and kill button click, backlight blink functions (1sec. on 1 sec. off(limit %10))

**3.On-off**: Users can on or off own backlight (off is %10)

**4.Animation**: If Printer power on; LCD backlight %0 between (users option or %100) in 4 sec.
example: Printer power on. 0.sec %0, 1.sec. %30 2.sec. %60 4.sec(users option or %100)

**But how?**
Using 1 pin for this. Then marhin configiration.h file define this property and add lcd menu line for control this.

edit for Phr3d13s ask.
edit2 for Andy Shaw ask.

**Comment by Phr3d13** [comment]
> 3.On-off: Users can on or off own backlight

If you turn off the LCD backlight via the LCD, how are you going to be able to see the menus to turn the backlight back on?

**Comment by yucelll** [comment]
> 
> 
> > 3.On-off: Users can on or off own backlight
> 
> If you turn off the LCD backlight via the LCD, how are you going to be able to see the menus to turn the backlight back on?

not completely closed 10% ..etc

**Comment by gloomyandy** [comment]
Do most of these displays actually provide access to the LCD backlight control? Just had a quick look at the full graphic smart controller and that does not seem to have access?

**Comment by yucelll** [comment]
> 
> 
> Do most of these displays actually provide access to the LCD backlight control? Just had a quick look at the full graphic smart controller and that does not seem to have access?

no, LCD backlight connected + and - with 100k resistance.
İf we want to control this, so we diassemble - wire and connect marlin backlight control pin  (with mosfet or transistor)

**Comment by mr-miky** [comment]
With 100k limiting the backlight current, the pwm control is not needed because there will never be enough current to illuminate the leds.
Maybe 100 Ohm?

You could use the KILL pin that arrives on the display board and command a 2n7002 / MMBF170 mosfet

**Comment by yucelll** [comment]
Yes. lcd board standart connected with 100k.
But we can remove 100k.

**Comment by mr-miky** [comment]
100k in series at the back light ??? If we consider 2.5 v of voltage drop on the backlight, assuming that the whole is powered at 5V, remain 2.5V that divided by 100k make 25 uA. With 25 micro amps the backlight does not make light or makes it so little that it looks dark.
Check the schematic ...

**Comment by boelle** [comment]
what lcd and controller combo will even make this possible?
