### ISSUE TITLE
[Q] POWER_LOSS_RECOVERY starts layer over?

### ISSUE THREAD

**Issue by diver197** [MarlinFirmware/Marlin#12561]
Choose to resume printing and reprint the whole model at the original height instead of continuing printing.

**Comment by thinkyhead** [comment]
Both the title and the post are pretty vague. What are you trying to say?

**Comment by cjsoong** [comment]
@diver197
You need to enable `#define SAVE_EACH_CMD_MODE`
### `power_loss_recovery.h`:
```cpp
#define SAVE_EACH_CMD_MODE
//#define DEBUG_POWER_LOSS_RECOVERY
```

**Comment by diver197** [comment]
我启动了POWER_LOSS_RECOVERY功能，在打印过程中，断电，再开电，选择恢复打印，他没有在断的地方打印，而是在断开的高度，进行新的打印，从头开始的。

**Comment by diver197** [comment]
Thank you！！！
