### ISSUE TITLE
[Bugfix 2.0] Layer fan not working when set to < 100% and FAST_PWM_FAN enabled

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#12572]
Hardware is Arduino Mega with Ramps, layer fan connected to standard pins on the ramps board. Software PWM not enabled. Works when FAST_PWM_FAN is disabled.

**Comment by InsanityAutomation** [comment]
I just tested some soft PWM configs yesterday without an issue. The standard pins should be hardware pwm and therefore not use softpwm. Id suggest closing the issue unless you want to validate an issue exists using softpwm on a non-hardware pwm pin.

**Comment by hamster65** [comment]
Thanks for looking into it. Closed.
