### ISSUE TITLE
I have an Anycubic kossel linear plus i just installed the mks sbase 1.3 in it came with the tft32_l 4.0 touch screen need help with marlin 2.0 setup and auto leveling.

### ISSUE THREAD

**Issue by tidus350** [MarlinFirmware/Marlin#12574]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by tidus350** [comment]
Ok so im new to 3d printing (bet ya heard that before) in my case its true like supper newb. I have an Anycubic kossel linear plus and in a month i had to replace the trigorilla board twice. The first board came bad. The second ran great for 2 weeks then just burned up literally so I've only done around 9 prints on it and about 3 of those didn't give me some type of trouble or didn't fail during printing. I decided this replacement to go for a 32 bit board and thought I was getting a Smoothieboard but instead ended up with a MKS SBASE v1.3 with the 3.2 touchscreen. I've tried using the smoothieware firmware and I'm just getting crash after crash into the bed, the touch screen isn't working, &c. so here I am looking at Marlin. Can anybody help?

The Marlin build for Trigorilla board with the auto-leveling worked great for auto-leveling and such; it just had issues with processing and printing, but at least it worked. I haven't had this MKS working at all in the 2 weeks I've had it. I would like to use grid leveling like I did with the Trigorilla, and then adjust z height &c.… I would like to use the touchscreen but if I can't right now, no big deal as I'm getting a Raspberry Pi next week to run it from, but it would be neat for my son to use. He is only 8 and already has bigger dreams for this thing than I do. I've included the original config for marlin 1.1.9 and what I'm working with now, Marlin 2.0x.

[KosselLinearPlusCustomz-master.zip](https://github.com/MarlinFirmware/Marlin/files/2637301/KosselLinearPlusCustomz-master.zip)
[New Config.zip](https://github.com/MarlinFirmware/Marlin/files/2637303/New.Config.zip)

**Comment by tidus350** [comment]
If you would like a labeled pic of how i wired the board just ask and ill supply.

**Comment by thinkyhead** [comment]
Yes, please post a picture. I'm sure it will be useful to anyone who finds this issue in the future.

**Comment by tidus350** [comment]
Ok so made some head way the ran into another brick wall. So here are my config files for anybody to look at and what im getting in ponterface. When i g28 for home it homes but then vibrates like fing crazy then  when i g33 for auto calibration it homes between each section but does nothing else during just echo busy. i included images of ponterface output.

[config.zip](https://github.com/MarlinFirmware/Marlin/files/2674364/config.zip)
![g28](https://user-images.githubusercontent.com/29417865/49912515-033d7c00-fe50-11e8-937e-4d87779766fa.jpg)
![g33](https://user-images.githubusercontent.com/29417865/49912519-05073f80-fe50-11e8-88b8-984fd717ef2c.jpg)

**Comment by p3p** [comment]
The MKS Sbase uses DRV8825 drivers (if using the inbuilt ones), so the drivers need set appropriately in the config.
```
#define X_DRIVER_TYPE  DRV8825
```

**Comment by tidus350** [comment]
Yes did that if you look at the config file you will see I set that as well
as the proper steps for steppers that was set for 400 but nema 17 are 200
per cycle that slowed it down but g33 just isn't working

**Comment by tidus350** [comment]
Thanks for the reply tho

**Comment by p3p** [comment]
Sorry didn't see the updated config.zip, in that config you have 
```
#define X_DRIVER_TYPE  DVR8825
```

it should be `DRV8825`

**Comment by boelle** [comment]
@tidus350 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by tidus350** [comment]
Yeah I found a different setup that actually worked 4 months ago I thought
this had been closed truth is mks boards just suck especially for the price
and so does any cubic I designed and built my own printer and I haven't had
an issue with it since it went online. Thanks for the reply tho it was as
helpful as the post boards.

**Comment by boelle** [comment]
only the one that opens the issue and @thinkyhead can close

you will see a close button below when you login to github

**Comment by boelle** [comment]
@tidus350 please click close button below
