### ISSUE TITLE
babbysteping RAMBO reprapdsicount full graphic smart controler

### ISSUE THREAD

**Issue by raptikCZ** [MarlinFirmware/Marlin#1257]
Hi,
 did I forget something install, or is it a bug?

from stable branch - compiled on windows 64b arduino ide 1.0.5

after enabling babbysteping got this:

Initilalizer fails to determine size of '__c'

ultralcd.cpp: In function 'void _lcd_babystep(int, const char*)':
ultralcd.cpp:371: error: initializer fails to determine size of '__c'

on this line:
    if (lcdDrawUpdate) lcd_implementation_drawedit(PSTR(msg), "");

**Comment by boelle** [comment]
when will you test?

**Comment by raptikCZ** [comment]
HI,
with development,downloaded about 1hour ago (now 12:38 - 4.1.2015)

1) i tried LCD_PROGRESS_BAR and this error occured:
  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
Arduino: 1.0.6 (Linux), Board: "Arduino Mega 2560 or Mega ADK"
ultralcd.cpp: In function ‘void lcd_goto_menu(void (*)(), uint32_t, bool)’:
ultralcd.cpp:199: error: ‘lcd_set_custom_characters’ was not declared in this scope
ultralcd.cpp: In function ‘void lcd_status_screen()’:
ultralcd.cpp:210: error: ‘progressBarTick’ was not declared in this scope
dogm_lcd_implementation.h:88: error: too many arguments to function ‘void lcd_implementation_init()’
ultralcd.cpp:271: error: at this point in file
dogm_lcd_implementation.h: In function ‘void lcd_update()’:
dogm_lcd_implementation.h:88: error: too many arguments to function ‘void lcd_implementation_init()’
ultralcd.cpp:1192: error: at this point in file
ultralcd.cpp: In function ‘void lcd_finishstatus()’:
ultralcd.cpp:1296: error: ‘progressBarTick’ was not declared in this scope

2) BABBYSTEPING in development works
i havent time to test it now,only compile, but today - latter i can test it.

**Comment by raptikCZ** [comment]
BABYSTEPPING working on my setup...
marlin development
rambo 1.2g, compiled on arduino ide 1.0.6, ubuntu 14.04 64b

**Comment by JoshyuNL** [comment]
I get the same error message while enabling the LCD_PROGRESS_BAR. Tested both with and without babystepping (didn't think they were connected, just making sure though).
Babystepping works fine now.

Here is a complete compilation log with LCD_PROGRESS_BAR defined:
https://gist.github.com/JoshyuNL/02e83d7086161b9c8119


This is on my reprap discount full graphics LCD on a RAMBO board.

**Comment by thinkyhead** [comment]
Sorry about that. DOGM and LCD_PROGRESS_BAR are not compatible (yet). And of course, LCD_PROGRESS_BAR is not intended for graphical displays.

**Comment by stv0g** [comment]
Why is it not intended? It assume thats it's a totally different implementation. But the DOGM display also (already?) has a progress bar?

**Comment by thinkyhead** [comment]
It already has a progress bar. This feature is intended specifically for the character-based displays, and #1343 addresses the issue to a point. I didn't want to presume to implement overlapping the progress bar with the message text, since they can co-exist on the larger display. However, the patch leaves open that potential. I also didn't want to confuse users of the graphical display by making the default that the progress bar is disabled, which is the default for character-based displays. The name is unfortunate, but actually I overlooked the existence of the DOGLCD progress bar. With this patch the compiler will issue a #warning (which few will probably notice) that explains the situation.

**Comment by boelle** [comment]
so as this was not intended for the mentioned display i have upgraded it to a verified bug but also put in the needs more work label... 

@thinkyhead or could i close this one?

**Comment by thinkyhead** [comment]
The original issue is fixed, and the conflict with dogm should no longer exist, so closing.
