### ISSUE TITLE
Endstop Interrupts.

### ISSUE THREAD

**Issue by RudyBenner** [MarlinFirmware/Marlin#12589]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by RudyBenner** [comment]
Came across this file How do I utulize this.
I would like to test for interrupts in MKS_GEN_L board.
[pin_interrupt_test.zip](https://github.com/MarlinFirmware/Marlin/files/2649279/pin_interrupt_test.zip)
Bugfix 2

[Config files.zip](https://github.com/MarlinFirmware/Marlin/files/2649406/Config.files.zip)

**Comment by AnHardt** [comment]
`pin_interrupt_test.ino` is a stand alone Arduino sketch. It just prints a list of the interrupt capable pins the Arduino framework knows about. Ideally these are the pins what can interrupt the processor. A (integrated) patch for the Arduino framework was needed to make that true for the Arduino Mega.

A brief look into that file would have offered this insight.

**Comment by RudyBenner** [comment]
I will have another look. Thanks for your help.

#5484

**Comment by RudyBenner** [comment]
I did as suggested and got results:

PINs causing interrupts are:
D2
D3
D10
D11
D12
D13
D14
D15
D18
D19
D20
D21
D50
D51
D52
D53
A8 = D62
A9 = D63
A10 = D64
A11 = D65
A12 = D66
A13 = D67
A14 = D68
A15 = D69
Arduino pin numbering!

In checking the appropriate pin files leads me to believe I can uncomment this line.
