### ISSUE TITLE
Cannot Compile for Anycubic Delta with many features enabled.

### ISSUE THREAD

**Issue by nickaus** [MarlinFirmware/Marlin#12587]
I'm trying to compile 1.1.9 for an Anycubic Delta Plus using the config file from example_configurations->delta->anycubic->kossel

It compiles fine with some of my options / features enabled but add one more any it fails.
 Remove one, any one and it complies !

Features are 
Board Fan (stepper driver fan)
Level Probe (type 2)
Heated Bed (type 2)

With these enabled it won't compile.
 Remove one and it will.

Errror is 
```
C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.15.0_x86__mdqgnx93n4wtt\libraries\LiquidCrystal\src\LiquidCrystal.cpp: In function 'clear.constprop':

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.15.0_x86__mdqgnx93n4wtt\libraries\LiquidCrystal\src\LiquidCrystal.cpp:180:1: internal compiler error: Segmentation fault
```
[Config Files.zip](https://github.com/MarlinFirmware/Marlin/files/2648445/Config.Files.zip)

**Comment by boelle** [comment]
@nickaus problem solved?

**Comment by nickaus** [comment]
Not solved.
Download 1.1.9 again today, configured and tried to compile = same problem.

**Comment by boelle** [comment]
try bugfix 2.0

**Comment by nickaus** [comment]
Compiles in 2.0 unless you enable #define FILAMENT_RUNOUT_DISTANCE_MM 
 With that enables the compile fails with a segmentation fault.

**Comment by boelle** [comment]
@thinkyhead configs are in first post, can you see anything wrong?

**Comment by nickaus** [comment]
Actually I take that back.
With all of the options enabled (probe, heated bed & runout sensor) it won't compile in 2.0 either.

**Comment by boelle** [comment]
i think we had an issue where the runout sensor enabled made it not compile, not sure

@thinkyhead could it be that we still have a gremlin in the closet?

**Comment by thinkyhead** [comment]
I'd like to have @nickaus's configurations for 2.0.x to see where the compile fails.

**Comment by nickaus** [comment]
Config files attached
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2923061/Configuration.zip)

**Comment by thinkyhead** [comment]
It compiles fine for me using your configurations. Be sure to use Arduino 1.8.8 or PlatformIO to build.
```
Sketch uses 173138 bytes (68%) of program storage space. Maximum is 253952 bytes.
Global variables use 5216 bytes (63%) of dynamic memory, leaving 2976 bytes for local variables. Maximum is 8192 bytes.
```
