### ISSUE TITLE
Delta on 1.1.9: On Begin and End of the print the effector seems to accelerate at maximum 

### ISSUE THREAD

**Issue by dgrat** [MarlinFirmware/Marlin#12586]
### Description

I noticed on my Delta printer that begin and end moves happen at infinite rate. During my start gcode, the effector goes to center and is appr. 5 cm over the build plate. After a moment the print starts and the effectors moves to the build plate. In that moment the movement is very fast, which could lead to missing steps. Actually, the motors make cracking sounds. Same for the movements after prints. Setting a maximum feed rate und unit does not really help. 

**Expected behavior:** 

All movements are within maximum feed rates

**Actual behavior:**

Some movements are out of maximum feed rates which overloads motors/drivers.

**Comment by dgrat** [comment]
I added a movie showing the problem at print start. At the end this behavior is more problematic, because of the longer distance up to the end stops. Yet, I was not able to figure out the source of the problem.

https://www.dropbox.com/s/uqawduk9p4fi083/VID_20181208_101152.mp4?dl=0

**Comment by boelle** [comment]
@dgrat problem still there in bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
