### ISSUE TITLE
Support for: Scoovo X9H

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1259]
@a4jp-com got a CD from the factory after  he mentioned that Marlin is GPL licensed,

he will provide a link to his server that will have a copy of this CD...

would be awesome if marlin could support it out the box

**Comment by a4jp-com** [comment]
Below is a link to a page on my server with the original GPL firmware and setup files.

http://a4jp.com/3d-printer-marlin-firmware/

**Comment by boelle** [comment]
will have a look at it after donner.... but will look at it today

**Comment by boelle** [comment]
at least we have the settings now... not many files changed i see... i assume that only files that have a BAK copy has been changed...

**Comment by a4jp-com** [comment]
I'm not exactly sure how much has been changed from the original but I can fix any Japanese options that are missing from updates even though I want an English menu.

**Comment by boelle** [comment]
i think the settings are the most important ones....  the rest we can do later on

but think you should keep firmware as is until we have fixed bugs first... no need to risk your printer

**Comment by a4jp-com** [comment]
Okay ^^

Thank you for help. I'll read through the code in the meantime.

**Comment by boelle** [comment]
@ErikZalm @MarlinFirmware/collaborators 

what from the zip file do we need to support this printer? there are some changes in other than the config's i'm not sure about... look for all files that also have an BAK copy...

this one should have a config folder as its a factory/kit machine...

**Comment by a4jp-com** [comment]
Sorry for the late reply. I started building a 3D printer and haven't updated the firmware on my Scoovo printer yet. I will try today ^^ It will be my first time doing this so any help with installation instructions would be great. Should I make a config folder and put the files into it?

**Comment by thinkyhead** [comment]
It might help to diff this release with its original source, which seems to be from around 3 Sept 2014. The BAK files are helpful, but figuring out how A4JP's changes compare to later patches, etc., could be tricky.

**Comment by a4jp-com** [comment]
I'll try my best.

**Comment by boelle** [comment]
closing since we have agreed that hardware support should come from the makers.

**Comment by a4jp-com** [comment]
Oh no. All I have is the files I gave you. If you could help it would be great. The original maker sold the company to a factory and they can make the machines but don't know much about the software :( Is a stable version of the software ready yet? I'd love to update the driver if it is working now.

**Comment by a4jp-com** [comment]
If I can set up the printer once I can tell people what to do after that. If it is okay could you open this thread till then if it is okay?

**Comment by thinkyhead** [comment]
@aj4p-com Just messing around I found that the basis for the firmware at http://a4jp.com/3d-printer-marlin-firmware/ comes from May 5, 2013. You can get that repo using this command from within the current Marlin repo:

```
git checkout `git rev-list -n 1 --before="2013-05-05 12:00" Release` -b may_5_2013
```

If you delete all the "BAK" files from the **marlin** folder included in Marlin-AJ4P and then do a comparison between the remaining files and the Marlin folder (using a diff tool such as BBEdit), you can clearly see all the customizations that were made to the May 5 version. It should be relatively straightforward to start with a fresh copy of Marlin (1.0.2 recommended) and apply the equivalent customizations.

If you get stuck in the process and have specific questions, please post them here.
