### ISSUE TITLE
[bugfix_1.1.x] E0 auto fan doesn't activate on MKS GEN 1.4

### ISSUE THREAD

**Issue by pipersw** [MarlinFirmware/Marlin#12597]
I have a fan extender on the servo port on MKS GEN 1.4.
I have defined the pins for the controler fan and the E0 auto fan.
I use the latest bugfix_1.1.x

The controler fan start and stop when the steppers are used, tried with pin D6, D5 and D4.
The E0 fan doesn't start when the temperature is higher than 50deg, on any pin D6, D5, D4.

I have swapped the fan, same issue.
I have swapped the fan extender with an another, same issue.

I use a bltouch on D11, so I want use D5 for controler fan and D4 for E0 fan.

I have declared in the configuration_adv.h:
```cpp
#define USE_CONTROLLER_FAN
#if ENABLED(USE_CONTROLLER_FAN)
  #define CONTROLLER_FAN_PIN 5        // Set a custom pin for the controller fan
  #define CONTROLLERFAN_SECS 60          // Duration in seconds for the fan to run after all motors are disabled
  #define CONTROLLERFAN_SPEED 255        // 255 == full speed
#endif

#define E0_AUTO_FAN_PIN 4
#define E1_AUTO_FAN_PIN -1
#define E2_AUTO_FAN_PIN -1
#define E3_AUTO_FAN_PIN -1
#define E4_AUTO_FAN_PIN -1
#define CHAMBER_AUTO_FAN_PIN -1
#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED   255  // == full speed
```

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2656609/configuration.zip)

**Comment by shitcreek** [comment]
Enable PINS_DEBUGGING and try M43 to see which pins are used for what

**Comment by pipersw** [comment]
Recv: PIN:   4   Port: G5        E0_AUTO_FAN_PIN             protected
Recv: .                          FIL_RUNOUT_PIN              protected
Recv: .                          SERVO3_PIN                  protected

Recv: PIN:   5   Port: E3        CONTROLLER_FAN_PIN          protected
Recv: .                          SERVO2_PIN                  protected

The pin 4 is used for E0 auto fan, and FIL_RUNOUT_PIN (function not used).
The pin 5 is OK, fan are on or off following stepper drivers activation.

If I swap pins, the pin defined for E0 auto fan pin doesn't activate when temperature higher than 50deg

**Comment by pipersw** [comment]
Test with 1.1.9 release, same issue.
test with #define FIL_RUNOUT_PIN -1 added before //#define FILAMENT_RUNOUT_SENSOR, and filament change disabled.

Send: M43 P4
Recv: PIN:   4   Port: G5        E0_AUTO_FAN_PIN             protected
Recv: .                          SERVO3_PIN                  protected
Recv: ok

Same issue

**Comment by pipersw** [comment]
with #define E0_AUTO_FAN_PIN 6 the extruder fan is spinning.

**Comment by federico9292** [comment]
MKS GEN L : pin 7 for the auto hotend fan solved! please highlight the solution, I spent hours finding that pin number! I wrongly cabled the fan, was in the same for the extruder : put into the other extruder mosfet, (D7) worked like a charm!

**Comment by thinkyhead** [comment]
Pin 7 is also named `MOSFET_D_PIN` on the MKS Gen boards, so you can probably also use
```cpp
#define E0_AUTO_FAN_PIN MOSFET_D_PIN
```
.
