### ISSUE TITLE
M851 not working on 1st print

### ISSUE THREAD

**Issue by Ivomola** [MarlinFirmware/Marlin#12599]
Hi. This is my first time writting a bug report as the code of conduct says, because it's the first time I write one from the computer lmao. Ok now in all seriousness, I have a Tevo Tarantula with the latest and gratest version of Marlin (1.1.9), and I have in my start gcode an M851 command to set the Z probe offset because in Cura because -2,70mm is too low and it won't let me put it, but a problem I noticed quite recently is that, when I print something for the first time after unplugging the printer, the offset doesn't work, I have to cancel the print and start it again for it to low the nozzle at the proper height. I tried to modify the start gcode to home Z twice, but that didn't solve anything. Below is the bug report.

Steps to reproduce the bug:
1. Unplug the printer
2. Plug it
3. Start a print

**Expected behavior:** The printer lowers the nozzle at the proper height

**Actual behavior:** The nozzle doesn't obey the offset and it stays way high until I cancel the print and start it over.

P.S.: @thinkyhead, I watched your interview at YouTube in Toms3D channel, and I must say, you're amazing. Thanks for everything.
[Config files.zip](https://github.com/MarlinFirmware/Marlin/files/2658477/Config.files.zip)

**Comment by RudyBenner** [comment]
Looking here:
```cpp
// @section extras

//
// EEPROM
//
// The microcontroller can store settings in the EEPROM, e.g. max velocity...
// M500 - stores parameters in EEPROM
// M501 - reads parameters from EEPROM (if you need reset them after you changed them temporarily).
// M502 - reverts to the default "factory settings".  You still need to store them in EEPROM afterwards if you want to.
//
#define EEPROM_SETTINGS // Enable for M500 and M501 commands
#define DISABLE_M503    // Saves ~2700 bytes of PROGMEM. Disable for release!
#define EEPROM_CHITCHAT   // Give feedback on EEPROM commands. Disable to save PROGMEM.
```
When you do a M501, it should echo the eeprom settings, including current M851. Like the following:

```
SENDING:M501
echo:V63 stored settings retrieved (586 bytes; crc 30826)
echo:  G21    ; Units in mm (mm)
echo:  M149 C ; Units in Celsius
echo:Filament settings: Disabled
echo:  M200 D1.75
echo:  M200 D0
echo:Steps per unit:
echo:  M92 X200.00 Y200.00 Z800.00 E280.00
echo:Maximum feedrates (units/s):
echo:  M203 X300.00 Y300.00 Z5.00 E25.00
echo:Maximum Acceleration (units/s2):
echo:  M201 X2000.00 Y2000.00 Z100.00 E10000.00
echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P400.00 R1000.00 T1000.00
echo:Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
echo:  M205 B20000.00 S0.00 T0.00 X10.00 Y10.00 Z0.30 E5.00
echo:Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:Auto Bed Leveling:
echo:  M420 S0 Z4.00
echo:  G29 W I0 J0 Z-0.33000
echo:  G29 W I1 J0 Z-0.15625
echo:  G29 W I2 J0 Z0.00125
echo:  G29 W I3 J0 Z0.20500
echo:  G29 W I0 J1 Z-0.13625
echo:  G29 W I1 J1 Z-0.03250
echo:  G29 W I2 J1 Z0.01250
echo:  G29 W I3 J1 Z0.12125
echo:  G29 W I0 J2 Z0.02125
echo:  G29 W I1 J2 Z0.01500
echo:  G29 W I2 J2 Z-0.02125
echo:  G29 W I3 J2 Z-0.01250
echo:  G29 W I0 J3 Z0.14000
echo:  G29 W I1 J3 Z0.08750
echo:  G29 W I2 J3 Z-0.02875
echo:  G29 W I3 J3 Z-0.07625
echo:Material heatup parameters:
echo:  M145 S0 H180 B70 F0
echo:  M145 S1 H240 B110 F0
echo:PID settings:
echo:  M301 P14.00 I0.71 D68.74
echo:  M304 P225.39 I39.30 D323.12
echo:Z-Probe Offset (mm):
echo:  M851 Z-2.42
echo:Linear Advance:
echo:  M900 K0.22
```

**After flashing, common practice is M502 followed by M500.**

Give it a try.
rudy

**Comment by RudyBenner** [comment]
Baud set at 1000000?

**Comment by Ivomola** [comment]
Thanks for your reply. First: I already tried that, but the point of not putting that in the start gcode is to not wear out the eeprom, as it has a limited number of writes, and to do that what I do is to not save things to the eeprom, and that's where the problem starts, because if at the second print the offset works without saving it, why can't it work at the first one?
And second: Yes, I have the baud at 1000000 because I have octoprint in the first raspberry pi and printing through usb is painfully slow, so I print from the SD card, and to speed up transfers I maxed out the baud rate. I have a shielded cable so no problems there.

**Comment by gloomyandy** [comment]
No idea about the M851 issue but unless you are changing your Z probe offset for each print (and if you are why are you doing that?), then why not simply configure it in your firmware, save that setting once to eeprom (if you are using eeprom) and have done with it? 

eeproms do have a limited number of write cycles, but it is a very high limit. The Arduino in your printer has a lifetime of at least 100000 cycles (and this is almost certainly a very conservative estimate). So even if with every print you write to the eeprom and do say 10 prints a day and print every day of the year you will not run out of eeprom lifetime for 27 years.

**Comment by Ivomola** [comment]
Wow. That's a very, very good answer. I will still report this as a possible bug, but as for my problem with the offset, now I know what to do. Again, thanks for your answer, great to know people like you are supporting marlin.

**Comment by AnHardt** [comment]
The position of `M851` matters. It has to be before homing to be active then.
