### ISSUE TITLE
[bugfix-2.0.x] Build errors after recent commit

### ISSUE THREAD

**Issue by nemphys** [MarlinFirmware/Marlin#12594]
After commit aaf862aef22caa136f4aa63d9fcc4e71c164ae33, I get the following error when trying to  build with NUM_SERVOS 1 (for a custom blower fan I have, not for a Z-probe):
```
/src/module/configuration_store.cpp: In static member function 'static bool MarlinSettings::save()':
/src/module/configuration_store.cpp:640:20: error: 'servo_angles' was not declared in this scope
       EEPROM_WRITE(servo_angles);
                                             ^
```
This can be fixed by changing `#if !HAS_SERVOS` to `#if !ENABLED(EDITABLE_SERVO_ANGLES)` (which makes sense after the commit's changes), but even after doing so, I get EEPROM CRC errors:
'EEPROM CRC mismatch - (stored) 53170 != 58028 (calculated)!'

Trying a `M502` & `M500`, I get:
```
echo:Settings Stored (586 bytes; crc 53170)
Error:EEPROM datasize error.
```

I suppose something broke with the commit.

**Comment by Ludy87** [comment]
no configuration file, no help

**Comment by nemphys** [comment]
Here you go:
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2657378/Configuration.zip)

**Comment by thinkyhead** [comment]
The issue is now patched.
