### ISSUE TITLE
sd card inserted but No SD Card. The solution.

### ISSUE THREAD

**Issue by ayoungtech** [MarlinFirmware/Marlin#12605]
Having built my second printer, I found that though the main menu detected the insertion of an SD card, the second menu said No SD card.  I spent a long time searching the net and the software for clues but reailsed that my first printer has the same RepRap controller and found that it worked OK with the second printer so it is a controller problem and nothing to do with the printer or the software.  A search of the display board schematic showed only one chip of significance and that was the SD card buffer chip.  Examining it, I could find no markings or indents to indicate pin 1 so I wondered if the original constructor had the same problem and just soldered the chip in hoping for the best.  Nothing to lose, I carefully removed the chip and turned it round.  That cured the problem!!!  So the RepRap controller boards have a 50/50 chance of the SD card buffer being the wrong way round.  Bad news is that unless you are adept at non-destructive removal of SMD chips, you are better off trying your luck with another controller.

**Comment by thinkyhead** [comment]
That's an interesting issue with those reprap controller boards. Hopefully most of them are ok.
