### ISSUE TITLE
Feature request: Automatic Pause and Park at intervals

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#12609]
I'm printing with PetG filament and I'm doing a manual insert gcodes to pause and park at every layer Zmm intervals so I can clean the nozzle from petg filament that acumulates at the nozzle.

I'd like to make a request to have an Menu option to turn on an automatic pause and park feature for every layer Zmm of print.

**Comment by sergiofagundes** [comment]
Just a question, can I put the #define PARK_HEAD_ON_PAUSE outside the //#define ADVANCED_PAUSE_FEATURE "if statment" to make the M25 - Pause SD print to park the nozzle ?

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
