### ISSUE TITLE
Microstepping are Not working Reprap

### ISSUE THREAD

**Issue by tarekmesto** [MarlinFirmware/Marlin#12607]
I have reprep 1.4 with drv8825, but in marlin firmware when I change the step per unit to 80 step/mm the software did not consider the mmicrostepping 1/32. when I define it as 
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 5, 5, 160, 5 } the printer works fine, without microstepping ??
how to solve this??

**Comment by thinkyhead** [comment]
Did you do `M502`, `M500` after flashing the new firmware?

**Comment by Roxy-3D** [comment]
> I have reprep 1.4 with drv8825, but in marlin firmware

There have been a lot of  bug fixes and improvements...    Can you load the current firmware and try your scenario out there?    We would love to discuss this problem in that context.   OK?

**Comment by boelle** [comment]
@tarekmesto problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
