### ISSUE TITLE
TMC2130 library confusion. Which one is needed for2.0.x?

### ISSUE THREAD

**Issue by Louis-Cypher** [MarlinFirmware/Marlin#12608]
### Description

I try to get my TMC2130 drivers running on a Bigtreetech RAMPS 1.6+ without success. I had two libraries installed but no success (getting bad register values).

Know I only have TMC2130Stepper by teemuatlut as advised in Configuration_adv.h but cannot compile anymore. Hence, I am wondering which is the correct set of libaries to install: 
- TMCStepper by teemuatlut
- TMCStepper2130 by teemuatlut
- Both

**Expected behavior:** [What you expect to happen]
Compiling with TMCStepper2130 by teemuatlut works

**Actual behavior:** [What actually happens]
I need TMCStepper by teemuatlut to compile successfully

[TMC2130.zip](https://github.com/MarlinFirmware/Marlin/files/2660431/TMC2130.zip)

**Comment by teemuatlut** [comment]
TMCStepper

**Comment by boelle** [comment]
@Louis-Cypher problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by Louis-Cypher** [comment]
Sorry for my late response. I sadly do not have access to my system for the 
next weeks but I think yes.

Am 21. Februar 2019 21:25:51 schrieb Bo Herrmannsen <notifications@github.com>:

**Comment by boelle** [comment]
@Louis-Cypher maybe click close below and open new issue if problem is still there
