### ISSUE TITLE
I can't invert my X Axis Motor

### ISSUE THREAD

**Issue by TheJasonPlayz** [MarlinFirmware/Marlin#12604]
I have configured Marlin and I almost have it figured out, but every time I auto-home the motor, it goes away from the X endstop and it sounds like the gears are grinding. I have tried to invert it but none of the methods are working. Can I have some help?

Here are my configurations:
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/2659954/Configuration.h.txt)

[Configuration_adv.txt.txt](https://github.com/MarlinFirmware/Marlin/files/2659955/Configuration_adv.txt.txt)

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
