### ISSUE TITLE
[Bugfix 2.0]  Left shifted icon (Not heating bed)

### ISSUE THREAD

**Issue by mr-miky** [MarlinFirmware/Marlin#12612]
Nothing terrifying, I just wanted to point out that the "classic" icon of the bed is moved to the left by 3 pixels compared to the icon of the bed in heating.

in  src/lcd/dogm/dogm_Statuscreen.h

replace:
```
const unsigned char status_bed_bmp[] PROGMEM = {
  B11111111,B11111111,B11000000,
  B11111111,B11111111,B11000000
};
```
with
```
const unsigned char status_bed_bmp[] PROGMEM = {
  B00011111,B11111111,B11111000,
  B00011111,B11111111,B11111000
};
```

**Comment by thinkyhead** [comment]
Whoops! I’ll fix that shortly.
