### ISSUE TITLE
Bang Bang do not wait

### ISSUE THREAD

**Issue by mtmello2003** [MarlinFirmware/Marlin#12611]
Using Bang Bang bed temperature method (instead of PID), the gcode M190 do not wait for the target temp defined.

**Comment by swilkens** [comment]
Please provide:

1. Your Configuration.h and Configuration_adv.h
2. The version of Marlin that you are using (1.1.9? 2.0.x-bugfix?)
3. Your printer model

How are you using the gcode? You didn't accidentally typo and use M109?

**Comment by mtmello2003** [comment]
Issue is vanished after update to latest marlin (2.0).

Can be closed.

**Comment by swilkens** [comment]
You can close the issue yourself while replying to the issue, there is a reply and close button :)
