### ISSUE TITLE
[Question] Speed limited by JUNCTION_DEVIATION?

### ISSUE THREAD

**Issue by MasterPIC** [MarlinFirmware/Marlin#12621]
Hi,
while trying to tune (mainly increase) my printer speeds, I found that max observed travel speed increases if I increase feedrate for travel moves even if there was already "space and time" to keep acceleration on before the tuning.

In a few words if I send
> M205 T200
> G1 X100 F10000

I get an higher max speed than the one observed with
> M205 T100
> G1 X100 F10000

But **during the movement** I see that **max speed is kept constant for a "long" time**.

I'm using JUNCTION_DEVIATION and also S_CURVE_ACCELERATION (bugfix-2.0.x up to date).
Is it the expected behaviour?

Thanks
Armando

**Comment by MasterPIC** [comment]
In both cases max speed is less than expected one...

**Comment by AnHardt** [comment]
No configs -> no comments.
Else i'm tempted to tell you about lowering segments/second.

**Comment by MasterPIC** [comment]
I'm using default values for Anet A8.

**Comment by AnHardt** [comment]
I don't think so. - Else you wouldn't have problems with `JUNCTION_DEVIATION`. `JUNCTION_DEVIATION` is commented out in the default A8-config.

PLONK.
