### ISSUE TITLE
[2.0] Info on row 4 LCD display

### ISSUE THREAD

**Issue by roel8032** [MarlinFirmware/Marlin#12629]
While printing in the lower line (line 4) on the LCD display the printer shows:

One after the other:
The LCD_PROGRESS_BAR
and
The file name, that is printing.
Also behind the file name, the word Layer, but not the actual layer number.

**Comment by marcio-ao** [comment]
@roel8032: Perhaps include a photo to make it easier for us to understand what you are referring to?

**Comment by boelle** [comment]
@roel8032 problem fixed?

**Comment by roel8032** [comment]
no

**Comment by boelle** [comment]
did you see what marcio-ao wrote?
