### ISSUE TITLE
G92 adds values from M206 - Not as expected.

### ISSUE THREAD

**Issue by Area5142** [MarlinFirmware/Marlin#1262]
Running the GCode:

    G92 Z0
    G1 Z0

I would expect no movement, but I get a one, if z home is set to a value with M206.
M114 confirms that the z home value is added to z after G92.

I only expected M206 home offsets to be used in G28/G29 to compensate for endstop offsets.
This is not the way I expect G92 to work - is it a bug?

(Tested on latest Marlin from github)

**Comment by boelle** [comment]
is this still an issue with latest dev ?

**Comment by alexborro** [comment]
I do not understand your post, but if you send both commands (G92 Z0, G1
Z0) I expect no movement at all - unless you are using a delta bot.

G92 and M206 do the same thing in a silly different way.. and the M206
offsets are salved at EEPROM which is not valid for G92.

Just to exemplify, both codes below do the same thing:

G28
G1 X2 Y3 Z4
G92 X0 Y0 Z0

G28
M206 X2 Y3 Z4

Cheers.

Alex.

2015-01-02 16:48 GMT-02:00 Bo Herrmannsen <notifications@github.com>:

> is this still an issue with latest dev ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ErikZalm/Marlin/issues/1262#issuecomment-68550844>.
>



-- 
*"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )*

Alex Borro

**Comment by Area5142** [comment]
@boelle Yes the lates fetch still has the issue.

The following two cases should, in my opinion, give same result:

    ; Case 1
    M206 Z0
    G92 Z0
    M114 ; reports Z=0
    G1 Z0 ; Result in no Z move

    ; Case 2
    M206 Z2
    G92 Z0 
    M114 ; reports Z=2
    G1 Z0 ; Result in 2mm Z downwards move

I tested this on my K8200 printer with Cartesian coordinate system. In other g-code interpreters G92 sets the exact value for the given axis (case 1).

I think the problem is in Marlin_main.cpp when the G92 command is executed:

    case 92: // G92
      if(!code_seen(axis_codes[E_AXIS]))
      // Code removed...
		current_position[i] = code_value()+add_homing[i];
      // Code removed...

Homing offset is added every time the G92 is executed.
If Z homing is zero nobody notice... but I experimented with M206 homing offset to get Z leveling correct in G28/G29 and got this side effect. 

Hope this better explains the issue.

The solution could be to only use M206 homing offsets in G28 + G29 and remove it in G92.

**Comment by boelle** [comment]
@alexborro did his reply make it more clear? do we have an bug here?

**Comment by Sunz3r** [comment]
i think its a bug.
after G92 i expect zero axis position ... so any offset useless here.
example; after moving my axis to my new home i reset position with G92

i agree with Area5142 ... so its solve this problem by removing "+add_homing[i]"

**Comment by daid** [comment]
I also think this is a bug. G92 should set the current position, not add a homing offset.

I removed this offset from the Ultimaker2 firmware, as I'm using the homing offset there to configure the bed Z height (homing is done to Z max, the offset is applied after that)
https://github.com/Ultimaker/Ultimaker2Marlin/blob/master/Marlin/Marlin_main.cpp#L1130

**Comment by alexborro** [comment]
I agree with @daid , If I use G92 I expect no other offset being added. But this is my opinion. Unfortunately we have no standard or regulation to follow.. At least I don't know. 
If other Marlin developers agree, we could remove the offset from G92.

Cheers.

Alex.

**Comment by darkjavi** [comment]
I also think that the purpose of G92 is to set 'final' position. Also home offsets are only to be applied after homing, right?
I ran a couple of test yesterday, removed the add_homing, daid's way, and the movement after G92 is gone... as well as the homing offsets. I think now I'll have to look to set them from the homing routine.

**Comment by ntoff** [comment]
G92, as described in the reprap wiki ( http://reprap.org/wiki/G-code#G92:_Set_Position )

> Allows programming of absolute zero point, by reseting the current position to the values specified

To me, typing G92 Z0 should tell the printer that wherever it currently is, it is at Z0. Adding a home offset to the zero point wouldn't exactly be "absolute zero" now would it.

**Comment by thinkyhead** [comment]
I think you're correct, `G92` should not add home offsets. I will patch this shortly.

**Comment by thinkyhead** [comment]
#1661 fixes this issue.
