### ISSUE TITLE
[QUESTIONS] [bugfix-2.0.x] Trying to use Marlin with GTM32 PRO VB

### ISSUE THREAD

**Issue by AluOne** [MarlinFirmware/Marlin#12622]
Hello,
after some small compiler errors I can build Marlin. 
( SINGLENOZZLE_SWAP_LENGTH is now TOOLCHANGE_FIL_SWAP_LENGTH
, IWatchdog.h: No such file or directory
,SERIAL_PORT_2 is not supported for your MOTHERBOARD)

Marlin started with EEPROM version mismatch.

< 17:34:50: start
> 17:34:50: N1 M110 *2
< 17:34:50: echo:PowerUp
> 17:34:50: N2 M110 *1
< 17:34:50: Marlin bugfix-2.0.x
> 17:34:50: N3 M115 *5
< 17:34:50: echo: Last Updated: 2018-01-20 | Author: (none, default config)
< 17:34:50: echo:Compiled: Dec 10 2018
< 17:34:50: echo: Free Memory: 49319  PlannerBufferBytes: 1408
< 17:34:50: echo:EEPROM version mismatch (EEPROM= Marlin=V63)
< 17:34:50: echo:Hardcoded Default Settings Loaded
> 17:34:54: N5 M111 S6 *66
> 17:34:54: N6 M111 S7 *64
< 17:34:54: FIRMWARE_NAME:Marlin bugfix-2.0.x (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Rostock 301 P4 EXTRUDER_COUNT:3 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
< 17:34:54: Cap:SERIAL_XON_XOFF:0
< 17:34:54: Cap:EEPROM:1
< 17:34:54: Cap:VOLUMETRIC:1
< 17:34:54: Cap:AUTOREPORT_TEMP:1
< 17:34:54: Cap:PROGRESS:0
< 17:34:54: Cap:PRINT_JOB:1
< 17:34:54: Cap:AUTOLEVEL:1
< 17:34:54: Cap:Z_PROBE:1
< 17:34:54: Cap:LEVELING_DATA:1
< 17:34:54: Cap:BUILD_PERCENT:0
< 17:34:54: Cap:SOFTWARE_POWER:0
< 17:34:54: Cap:TOGGLE_LIGHTS:0
< 17:34:54: Cap:CASE_LIGHT_BRIGHTNESS:0
< 17:34:54: Cap:EMERGENCY_PARSER:0
< 17:34:54: Cap:AUTOREPORT_SD_STATUS:0
< 17:34:54: Cap:THERMAL_PROTECTION:1
< 17:34:54: Cap:MOTION_MODES:0
< 17:34:54: echo:DEBUG:INFO,ERRORS
< 17:34:54: echo:DEBUG:ECHO,INFO,ERRORS

Than homing G28 only the motor X and Z are working. Y does not work.
Sometimes only the X motor is working.
The home procedure breaks by „Error:Printer halted. kill() called!“.
After that I reinstalled the Geeetech firmware to see if all motors are working 
and the homing works with three motors. 

> 18:47:12: N10 G28 *2
< 18:47:12: echo:N10 G28 *2
< 18:47:12: >>> G28 begin
< 18:47:12: >>> G28 delta begin
< 18:47:12: >>> home_delta begin
< 18:47:12: >>> home_delta homeaxis
< 18:47:12: >>> homeaxis(X)
< 18:47:12: Home 1 Fast:
< 18:47:12: Move Away:
< 18:47:13: Home 2 Slow:
< 18:47:33: Error:Printer halted. kill() called!

Any ideas what to do?
[config.zip](https://github.com/MarlinFirmware/Marlin/files/2664360/config.zip)

**Comment by AluOne** [comment]
Now I have written a small program that controls the motors individually and also there goes only the X motor.
Does anyone have the board running?

**Comment by AluOne** [comment]
Now it's a little clearer. X and Z motor worked but Y does not make a step. If I push the Y limit switch by hand, then the homing runs through. 
Because in my own program the Z motor didn't work but with Marlin.
Is there a special initialization for the motors except digitalWrite(Y_EN, LOW); ?

**Comment by AluOne** [comment]
The solution can be found hear. 
[https://github.com/MarlinFirmware/Marlin/pull/10898]

**Comment by boelle** [comment]
@AluOne submit an PR to bugfix 2.0

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by AluOne** [comment]
I think there have been no changes yet and we shouldn't close the call.
The main problem is still the eeprom.
I can't save any settings.
Is there a user who can work with the current version on the Rostock 301?

start
18:32:51.528 -> echo:PowerUp
18:32:51.528 -> Marlin bugfix-2.0.x
18:32:51.528 -> 
18:32:51.528 -> echo: Last Updated: 2018-01-20 | Author: (Alu One, default config)
18:32:51.528 -> echo:Compiled: Mar 27 2019
18:32:51.528 -> echo: Free Memory: 49463  PlannerBufferBytes: 1408
18:32:51.528 -> echo:EEPROM version mismatch (EEPROM= Marlin=V63)
18:32:51.528 -> echo:Hardcoded Default Settings Loaded

**Comment by Phr3d13** [comment]
Nope, I can't get a fully working build on my Rostock 301 either.

**Comment by AluOne** [comment]
Today I took a new test:

First after download the new version I copied the configuration header,
than compiled with Anduino 1.8.9.

>fatal error: IWatchdog.h: No such file or directory

If I delete the directory HAL_STM32 I can compile to the next error.

>#warning "SERIAL_USB is not set!"
>#error "Serial port 0 does not exist"

I can fix it in HAL.h with #define MYSERIAL0 MSerial1 in line 81
With these changes I get a binary that I can write to the GTM32 PRO board.
After booting I get the problem with EEPROM and SD card. 
With M500 I can save without a message but after booting I get the same error.

17:59:54.203 -> start
17:59:54.203 -> echo:PowerUp
17:59:54.203 -> Marlin bugfix-2.0.x
17:59:54.203 -> 
17:59:54.203 -> echo: Last Updated: 2018-01-20 | Author: (none, default config)
17:59:54.203 -> echo:Compiled: Jun  3 2019
17:59:54.203 -> echo: Free Memory: 50295  PlannerBufferBytes: 1408
17:59:57.381 -> echo:EEPROM version mismatch (EEPROM= Marlin=V67)
17:59:57.381 -> echo:Hardcoded Default Settings Loaded
18:00:00.147 -> echo:SD init fail
18:00:02.214 -> echo:SD init fail

It's a pity that no developer has the board or the printer.
Marlin is so much better than the original firmware but with my means I just can't get it to work.

**Comment by Phr3d13** [comment]
Using this set of configs and the tip above about removing the HAL_STM32 folder, I was able to get SD reading working, but SD writing is failing silently also causing SD EEPROM to fail (pretty sure that's the fallback option when EEPROM is enabled, but no EEPROM type is setup (SPI, I2C, SRAM)). Most other things appear to be working, LCD, SD detect, SD read, axis steppers, endstops, thermistors work (but readings are wrong), and heaters work. Fans don't appear to work either.
[Rostock 301 configs test.zip](https://github.com/MarlinFirmware/Marlin/files/3271747/Rostock.301.configs.test.zip)

**Comment by Phr3d13** [comment]
I tested writing to the SD via another method (octopi instead of Simplify3D) and SD writing appears to work. I don't know why EEPROM on SD isn't working any more, I've tried explicitly defining it, I've tried letting it be the thing that gets enabled because nothing else is. But apparently the SD can be read from and written to.

**Comment by Phr3d13** [comment]
Further testing, the eeprom.dat file is being written to the SD card, it isn't being read when the machine starts. Always:
```
09:03:05.241 : echo:EEPROM version mismatch (EEPROM= Marlin=V67)
09:03:05.241 : echo:Hardcoded Default Settings Loaded
```

**Comment by Phr3d13** [comment]
Have a PR submitted to get EEPROM working from SD reliably. Thanks to some help from Pinchies. Two small hurdles left: fans and temps.

**Comment by AluOne** [comment]
Nice to read about the next steps. I have tested your version (PR) and I can read and write to the SD card. I think it would be nice if we could access directly to the EEPROM.
I compiled now with platformio and there are no modifications needed.

**Comment by AluOne** [comment]
I tested my own temperature table(thermistor_1.h) with the values from Geeetech Repository. The values are displayed correctly up to 70 degrees. But I need a correction factor and get negative values. How can I avoid this?

`   const short  [][2] PROGMEM = {
    { OV( 1664-2930), 120 },
    { OV( 1801-2930), 115 },
    { OV( 1943-2930), 110 },
    { OV( 2090-2930), 105 },
    { OV( 2239-2930), 100 },
    { OV( 2389-2930),  95 },
    { OV( 2538-2930),  90 },
    { OV( 2686-2930),  85 },
    { OV( 2829-2930),  80 },
    { OV( 2968-2930),  75 },
    { OV( 3124-2930),  70 },
    { OV( 3246-2930),  65 },
    { OV( 3358-2930),  60 },
    { OV( 3461-2930),  55 },
    { OV( 3554-2930),  50 },
    { OV( 3653-2930),  45 },
    { OV( 3738-2930),  40 },
    { OV( 3810-2930),  35 },
    { OV( 3870-2930),  30 },
    { OV( 3912-2930),  25 },
    { OV( 3948-2930),  20 },
    { OV( 3977-2930),  15 },
    { OV( 4002-2930),  10 },
    { OV( 4022-2930),   5 },
    { OV( 4038-2930),   0 },
};`

**Comment by AnHardt** [comment]
Something in your circuit seems to be seriously wrong - if it produces voltages below GND level. The ADCs will not measure that but will be destroyed.

**Comment by AluOne** [comment]
Thank you for the note. The circuit is I think quite ok. The correction value was only for testing to display the values (I have no debugger).  I have a version from December that shows the temperatures correctly, but since then a lot has happened in temperature.cpp.

**Comment by rohklich** [comment]
Hi,
I want to get Geeetech's GTM32 PRO VD to work with marlin. With changed config and new added pins file it compiles without any hacking so far. Although, it's a somewhat different board, I think I will run into similar problems as you soon. 
But I don't want to start experimenting until I know, that I could go back to a working smartto version.
@AluOne Did you try or had any difficulties on flashing back geeetech's stock firmware? I have managed to read out a bin-file via st-link from the board, can i flash this back in case anything goes wrong?

**Comment by Phr3d13** [comment]
I have the bootloader for the pro VB board, and a method to get my Rostock 301 back to stock. I'm sure with the bootloader and method I have and the firmware you have, we should be able to get you back to a stock state.

**Comment by AluOne** [comment]
If I want to use the firmware from Geeetech, I use the tool "STM32 ST-Link Utility" from ST with a simple ST-Link dongle. First I write the bootloader from Geeetech and then I'll take Hyperterm to upload the firmware ([described in Geeetechs forum](http://www.geeetech.com/forum/viewtopic.php?f=20&t=18167)). With the bootloader from @Phr3d13 I think you can save some work.

**Comment by rohklich** [comment]
Where can I get the bootloader? And am I correct, if I assume you both talk about different bootloaders?
I planned to burn the firmware with a st-link dongle and stm's flash loader demonstrator. Does the smartto FW always depend on a bootloader? I hoped it was only to work with their FW-update tool.
@AluOne do you have a specific reason for using the st-link dongle just for the bootloader but burn the FW with Hyperterm?(via serial?)
Once I have a safe method to get back to stock, I can go further than examining the hardware. I collect what I learn [here](https://github.com/rohklich/geeetech-printer-hw) if you want to take a look.

**Comment by boelle** [comment]
@AluOne is this one solved?

**Comment by AluOne** [comment]
Unfortunately Marlin is not running with the GTM32 PRO Board yet. But we have made great progress. One of the last things is temperature control.
@boelle Maybe you can help us with that. With the correct therministor table at 20 degrees air temperature -1 degrees are displayed. If I hold my finger on the resistor, 17 degrees are displayed.
What settings can we change here?

**Comment by boelle** [comment]
i have no idea, i'm not a coder but just a concerned 3rd party

thought things looked solved and was just curious

**Comment by AluOne** [comment]
Maybe @AnHardt can give us a hint in which direction we should search?
This is the [thermistor table](https://www.geeetech.com/Documents/thermistor%20lookup%20table.txt).

**Comment by AnHardt** [comment]
> With the correct therministor table at 20 degrees air temperature -1 degrees are displayed. If I hold my finger on the resistor, 17 degrees are displayed.

Correct? Obviously not - else you'd get the right temperatures.
If the linked table should be the right one you don't have to replace Marlins table 1. Just use Marlins 11. Should be for the same sensor.

If that still shows wrong temperatures, check if the pullup resistor on the used ADC pin is really 4.7KOhm. But everything else would be a surprise.

How to make a custom table is common knowledge. Just search for that.

**Comment by AluOne** [comment]
Thanks for the good advice. 
With table no. 11 I get a value of - 10 at 20 degrees. 
Looks like the table or something else is wrong. 
If I adjust the values manually, I get sweeping values:

`{ OV(921), 40},
   { OV(931), 38},
   { OV(941), 37},
   { OV(951), 35},
   { OV(961), 33},
   { OV(971), 32},
   { OV(981), 29},
   { OV(991), 27},
   { OV(1001), 25},
   { OV(1011), 20},`

The vote does not match any table.
Is it possible to determine the remaining values from the determined values?
![hotbed](https://user-images.githubusercontent.com/8656422/60042318-bb7c9480-96bd-11e9-9c5d-83f9569ec5da.png)
The pullup resistor seems to be 4.7 K, but I didn't measure.

**Comment by AluOne** [comment]
Now I have created 2 new temperature tables for the sensors. At the bed I measured directly next to the sensor. On the aluminum plate the temperature does not arrive. At the hotend I measured at the top.
I have measured for the nozzle up to 200 C degrees for the bed up to 120 degrees
It would be great if someone could test the files on his Rostock 301.
Changes in configuration.h:

`#define TEMP_SENSOR_0 21`
`#define TEMP_SENSOR_BED 22`

Changes in thermistors.h:
`#if ANY_THERMISTOR_IS(21)`
`  #include "thermistor_21.h"`
`#endif`
`#if ANY_THERMISTOR_IS(22) `
`  #include "thermistor_22.h"`
`#endif`

[thermistor.zip](https://github.com/MarlinFirmware/Marlin/files/3345869/thermistor.zip)

**Comment by boelle** [comment]
will close this one as it mostly seems to be about creating a custom table

if its about adding suport for a new board a [FR] should be created instead

we can alway reopen if i got it wrong and this is a bug

**Comment by chepo92** [comment]
You can always ask/mention the author of  #10898 :D 
It took me two nights of scoping, reading forums and digitalWrites() to get the F****ng Y axis moving in 2018, and two years to see this :-1: 
I pushed the working solution long ago but made a mess as I wasn't very familiar with github and got closed. 
https://github.com/MarlinFirmware/Marlin/pull/11177#

Also I didn't know how to correctly implement this following marlin structure: 
https://github.com/MarlinFirmware/Marlin/pull/11177/commits/3a479e7beca39e630328cd28bfa50bcd05c19579

**Comment by chepo92** [comment]
> `#if ANY_THERMISTOR_IS(21)`
> ` #include "thermistor_21.h"`
> `#endif`
> `#if ANY_THERMISTOR_IS(22) `
> ` #include "thermistor_22.h"`
> `#endif`

This improved thermistor readings a lot!, , I'm checking with a multimeter and values are very close in my 301.
@AluOne would you PR those tables?, at this time there is already a thermistor 21 file
