### ISSUE TITLE
[32-bit, Archim] Babystepping Z while printing appears to move nozzle wrong distance.

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#12635]
As far as I can tell, babystepping is broken on the 32-bit Archim and possibly other 32-bit boards. When the nozzle is about 1mm above the bed at the start of a print, I call  `thermalManager.babystep_axis` as the user adjusts the offset during a print. The display shows the sum of all the babysteps requested converted into mm. This value is always way more than 1mm, being closer to about 3mm. I've added code to verify that babystepsTodo[] is being incremented and decremented correctly, so I believe the problem is deeper than that.

I suspect it is some sort of weird interaction between the temperature ISR (which is generating pulses for babystepping) and the stepper ISR (which is also generating pulses), but I don't know how to troubleshoot it further than that.

**Comment by marcio-ao** [comment]
So I came to the realization that the backlash compensation code I had recently added did a very similar thing to baby stepping: it added steps to an axis during a print.

So I did an experiment of disabling the current baby stepping code in the temperature ISR and instead made a modification to the planner that would inject the steps there:

```
#if defined(LULZBOT_BABYSTEP_WORKAROUND)
  void add_babystep_steps(const int32_t da, const int32_t db, const int32_t dc, const uint8_t dm, block_t * const block, float (&delta_mm)[ABCE]) {
      const bool positive[XYZ] = {  da > 0,  db > 0, dc > 0 },
                 non_zero[XYZ] = { da != 0, db != 0, dc != 0 };

      bool made_adjustment = false;

      LOOP_XYZ(i) {
        if (Temperature::babystepsTodo[i] != 0 && non_zero[i] && positive[i] == (Temperature::babystepsTodo[i] > 0)) {
            block->steps[i] += ABS(Temperature::babystepsTodo[i]);
            Temperature::babystepsTodo[i] = 0;
            delta_mm[i] = (positive[i] ? 1.0f : -1.0f) * block->steps[i] * Planner::steps_to_mm[i];
            made_adjustment = true;
        }
      }

      // If any of the axes were adjusted, recompute block->millimeters
      if (made_adjustment)
        block->millimeters = SQRT(sq(delta_mm[X_AXIS]) + sq(delta_mm[Y_AXIS]) + sq(delta_mm[Z_AXIS]));
  }
#endif
```

I then call that in the planner in the exact place where I call `add_backlash_correction_steps`.  This works fine and now the live adjustment does exactly what it is supposed to. So this confirms my suspicion that the babystepping code, as it is currently implemented (via the temperature ISR) has problems.

**Comment by ejtagle** [comment]
Babystepping from temperature ISR... That is not good. Stepper ISR runs at HIGHER priority than the temperature ISR, so the stepper will preempt the temperature ISR. Just imagine what could happen if, in the middle of a pulse generated by the Temperature ISR, the stepper ISR changes the direction of the motor, or creates a new pulse. You end with a completely unreliable count of pulses and directions.
Babystepping is a dangerous thing, and i also think that it should handled in the planner by injecting steps in the planner. That is the ONLY safe place to do it.

**Comment by marcio-ao** [comment]
@ejtagle: The patch I made to our FW seems to be one way to fix it, but there are significant problems with my implementation:

- Since it modifies planner blocks, it only works when the printer is printing.
- The babystepping only happens if the block in question already has steps in the same direction as the babystepping (if I subtract steps, the direction could change and I am trying to avoid this). If bed leveling were disabled, it may be that there are no steps in Z for an entire layer, so babystepping in Z would not happen at all.
- Babysteps only happen once new blocks are added, so there is a noticeable delay from the time in which the user does the babystepping to the time in which it actually happens.
- The delay is even more significant if there are long straight moves buffered prior to the babystepping.

It would seem like implementing a good babystepping routine that avoided these issues would be quite a bit more complicated than my patch.

**Comment by marcio-ao** [comment]
Initial testing seems to indicate that the workaround for #12983, setting MINIMUM_STEPPER_PULSE to 1 on Archim 2.0, improves and possibly resolves issues with babystepping.

To the eye, it seems that MINIMUM_STEPPER_PULSE to 1 makes it so babystepping moves the nozzle an appropriate distance, whereas before babystepping barely moved the nozzle. Given that we are in the final testing run of our prototype printers, we likely will continue to use our workaround of applying babysteps in the planner, as this solution has been tested and presents less risk to us, but I wanted to at least chime in that MINIMUM_STEPPER_PULSE has a good potential of solving this issue.

**Comment by marcio-ao** [comment]
Closing in favor of the workaround in #12983.
