### ISSUE TITLE
Delta Anycubic Kossel G33 ignore X_PROBE_OFFSET_FROM_EXTRUDER Y_PROBE_OFFSET_FROM_EXTRUDER 

### ISSUE THREAD

**Issue by Piranit** [MarlinFirmware/Marlin#12631]
Hi everyone
I have an Anycubic Kossel Linear Plus 3D printer
I am making improvements with two 5015 fans (for better bridges and etc)
also decided to make a calibration with the proximity sensor
![image](https://user-images.githubusercontent.com/8013207/49836469-72ad6000-fdab-11e8-901a-0732739f324b.png)
![image](https://user-images.githubusercontent.com/8013207/49836484-7b059b00-fdab-11e8-870e-f2ea287dd9fc.png)
![image](https://user-images.githubusercontent.com/8013207/49836504-88bb2080-fdab-11e8-99f4-e3c27599cc36.png)
![image](https://user-images.githubusercontent.com/8013207/49836509-8ce73e00-fdab-11e8-9771-332987c31840.png)

I'm using Marlin 1.1.9
in my case **X_PROBE_OFFSET_FROM_EXTRUDER  = -29** and **Y_PROBE_OFFSET_FROM_EXTRUDER = -57** (can check with G1 X29 Y57 F1000 and probe will be in bed center where nozzle is when G1 X0 Y0)
I've **already changed DELTA_CALIBRATION_RADIUS so that the probe check only inside bed**

but I have a problem, **G33 calibration does not build mesh properly** 
because **it ignores X_PROBE_OFFSET_FROM_EXTRUDER and Y_PROBE_OFFSET_FROM_EXTRUDER**
**I've found G33 code logic and X_PROBE_OFFSET_FROM_EXTRUDER and Y_PROBE_OFFSET_FROM_EXTRUDER are not taken into account there**
that's why the **calibration is going wrong**
![image](https://user-images.githubusercontent.com/8013207/49836591-ebacb780-fdab-11e8-86dc-f4f418fedda1.png)

**I can calibrate Z offset perfectly**
but bed **mesh calibrates wrong**

I've even moved probe sensor closer to a nozzle
![image](https://user-images.githubusercontent.com/8013207/49836656-2a427200-fdac-11e8-8cf1-b7ced8995e83.png)

but unfortunately, it's doesn't help(
here is an example of g33 print.
![image](https://user-images.githubusercontent.com/8013207/49836677-362e3400-fdac-11e8-8f44-ff420b2a26ac.png)
bugfix brunch doesn't help

Don't think that the probe isn't precise or it's broken. Here are the results of M48 command "Probe Accuracy Test". 
![image](https://user-images.githubusercontent.com/8013207/49868586-8cd05800-fe16-11e8-9316-a213eb24205e.png)
Probe works indeed ideally correctly.

Can anybody help make G33 calibration work with X_PROBE_OFFSET_FROM_EXTRUDER and Y_PROBE_OFFSET_FROM_EXTRUDER?

**Comment by LVD-AC** [comment]
G33 assumes the bed is **flat** and the towers are **square** to the bed. Bed **tilt** is not corrected by G33 and needs to be corrected mechanically in the build of the printer. G33 calibrates misaligned end-stops, delta radius and a not perfect equidistant triangle between the towers (tower angles). And for such calibration one needs to probe the height at specific positions of the mechanism (carriages, arms and effector) so for a center probe the 3 carriages should be at the same distance from the end-stops and the effector in the center so no XY_PROBE_OFFSET_FROM_EXTRUDER may be taken into account.

**Comment by Piranit** [comment]
I'm using Anycubic Ultrabase, so my bed is flat. 

So for delta g33 works only if z min probe is in center?
Is there any solution for my case? which calibration can I use for my delta if the probe is not in center?

**Comment by LVD-AC** [comment]
G33 works also fine with eccentric probes. It probes with the effector in the center and a number of points where the effector is on a circle. It does not matter if the probe has an offset or not.

**Comment by Piranit** [comment]
I'm not interested in different probe types
I need solution for my inductive proximity probe with offset from nozzle

**Comment by boelle** [comment]
@Piranit problem fixed?

**Comment by Piranit** [comment]
no

**Comment by boelle** [comment]
@Piranit tried latest copy of bugfix 2.0?

**Comment by Piranit** [comment]
no, I have already sold this printer...

**Comment by boelle** [comment]
then maybe click the close button below?

**Comment by Piranit** [comment]
no, I'd tell the customer to try the last bugfix 2.0
And then I'd decide if this issue is still actual
If it's not, I'll close it.

**Comment by boelle** [comment]
oki, it will just be hard for you to test yourself, it was just a thought

**Comment by Piranit** [comment]
@boelle but for now, can you show me where delta new calibration logic with x/y probe offset is?
