### ISSUE TITLE
[1.1.9] Range of Auto Temp Factor is limited <1 in LCD menu

### ISSUE THREAD

**Issue by Elump** [MarlinFirmware/Marlin#12643]
Hi,

I am wondering about Auto Temp Factor range limitation in LCD menu. Given range is 0 to 1.

Description:
To make Auto Temp useful, my printer needs factor >1 and I can't see any need to limit Auto Temp Factor to <=1.

Steps to Reproduce:
-activate Auto Temp 
-connect LCD with activate LCD menu
-change Auto Temp Factor in LCD menu

Expected behaviour:
reasonable range of Auto Temp Factor should be available in LCD menu

Actual behaviour:
Auto Temp Factor range is limited from 0 to 1.

Additional Information:
in ultralccd.cpp change 
`MENU_ITEM_EDIT(float52, MSG_FACTOR, &planner.autotemp_factor, 0, 1);`
to e.g.
`MENU_ITEM_EDIT(float52, MSG_FACTOR, &planner.autotemp_factor, 0, 10);`

**Comment by boelle** [comment]
@Elump problem fixed?

**Comment by Elump** [comment]
@boelle with following change the problem is fixed. But, I'm new to Git and can't do pull request...

in ultralccd.cpp change
<code>MENU_ITEM_EDIT(float52, MSG_FACTOR, &amp;planner.autotemp_factor, 0, 1);</code>
to e.g.
<code>MENU_ITEM_EDIT(float52, MSG_FACTOR, &amp;planner.autotemp_factor, 0, 10);</code>

**Comment by boelle** [comment]
using bugfix 2.0?

**Comment by AnHardt** [comment]
Please have a look on #13227 and #13226.
Is 10 enough?
