### ISSUE TITLE
TMC2130 Shut down mid-print without current reduction

### ISSUE THREAD

**Issue by towe96** [MarlinFirmware/Marlin#12644]
### Description
Setup:
CoreXY printer, 1/16th microstepping, MKS GEN 1.4 with Marlin 2.0, 5x TMC2130 by Watterot in SPI on a 24V step-up with 100uF capacitors directly on the drivers

### Steps to Reproduce

1. Acceleration > 3000, Current (RMS) > 700
2. Printing something like infill with many direction changes
3. Steppers for X, Y and E shut down - commands keep being sent, but the drivers report "disabled" in M122. Sending "M906 X700 Y700" or any other SPI command "wakes them back up" - is this thermal shutdown?

**Expected behavior:** Drivers reduce current if too hot - behaviour changes proportionally to cooling efforts

**Actual behavior:** Drivers just shut down without any message or "fault" reported, temperature flag not set - it doesn't matter whether I blow on the drivers with a 40mm fan, 120mm fan or no fan at all.

**Comment by Glod76** [comment]
Post configs for help

**Comment by towe96** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2683079/Marlin.zip)
[config+pins.zip](https://github.com/MarlinFirmware/Marlin/files/2683081/config%2Bpins.zip)

The changes in the pins_RAMPS.h is just using the XMIN pin for YMIN as well for sensorless homing (since it's CoreXY and only one motor pin is required) and changing out a broken thermistor pin for a working one.

**Comment by towe96** [comment]
Sadly this is still an issue for me.
Even at 3000 mm/s^2 acceleration and 775 mA, the drivers disengage after a longer print - in this case a lithophane. Speed is only 40 mm/s.
The drivers simply disengage, and the affected driver registers read 0xE0:00:00:00, while the working ones (Z and Z2) read 0x80:07:00:00.
There's no way it's a thermal issue - I now have both a 120mm and 40mm fan blowing at the heat sinks, and they never trigger the OT prewarning.

I'm just lost...

M122 after failure:
`Recv: 		X	Y	Z	Z2	E
Recv: Enabled		false	false	true	true	false
Recv: Set current	775	775	500	500	700
Recv: RMS current	1381	1381	489	489	1215
Recv: MAX current	1947	1947	689	689	1713
Recv: Run current	24/31	24/31	15/31	15/31	21/31
Recv: Hold current	12/31	12/31	7/31	7/31	10/31
Recv: CS actual		0/31	0/31	7/31	7/31	0/31
Recv: PWM scale	0	0	19	24	0
Recv: vsense		0=.325	0=.325	1=.18	1=.18	0=.325
Recv: stealthChop	false	false	true	true	false
Recv: msteps		256	256	16	16	256
Recv: tstep		1048575	1048575	1048575	1048575	1048575
Recv: pwm
Recv: threshold		0	0	0	0	0
Recv: [mm/s]		-	-	-	-	-
Recv: OT prewarn	false	false	false	false	false
Recv: OT prewarn has
Recv: been triggered	false	false	false	false	false
Recv: off time		0	0	3	3	0
Recv: blank time	16	16	24	24	16
Recv: hysteresis
Recv: -end		-3	-3	2	2	-3
Recv: -start		1	1	3	3	1
Recv: Stallguard thrs	2	2	0	0	0
Recv: DRVSTATUS	X	Y	Z	Z2	E
Recv: stallguard
Recv: sg_result		0	0	0	0	0
Recv: fsactive
Recv: stst		X	X	X	X	X
Recv: olb		X	X			X
Recv: ola		X	X			X
Recv: s2gb
Recv: s2ga
Recv: otpw
Recv: ot
Recv: Driver registers:
Recv: 	X	0xE0:00:00:00
Recv: 	Y	0xE0:00:00:00
Recv: 	Z	0x80:07:00:00
Recv: 	Z2	0x80:07:00:00
Recv: 	E	0xE0:00:00:00
Recv: 
Recv: 
Recv: ok`

M122 after reset:
`Recv: 		X	Y	Z	Z2	E
Recv: Enabled		false	false	false	false	false
Recv: Set current	750	750	500	500	700
Recv: RMS current	734	734	489	489	673
Recv: MAX current	1035	1035	689	689	949
Recv: Run current	23/31	23/31	15/31	15/31	21/31
Recv: Hold current	11/31	11/31	7/31	7/31	10/31
Recv: CS actual		11/31	11/31	7/31	7/31	10/31
Recv: PWM scale	0	0	0	0	0
Recv: vsense		1=.18	1=.18	1=.18	1=.18	1=.18
Recv: stealthChop	true	true	true	true	true
Recv: msteps		16	16	16	16	16
Recv: tstep		1048575	1048575	1048575	1048575	1048575
Recv: pwm
Recv: threshold		0	0	0	0	0
Recv: [mm/s]		-	-	-	-	-
Recv: OT prewarn	false	false	false	false	false
Recv: OT prewarn has
Recv: been triggered	false	false	false	false	false
Recv: off time		3	3	3	3	3
Recv: blank time	24	24	24	24	24
Recv: hysteresis
Recv: -end		2	2	2	2	2
Recv: -start		3	3	3	3	3
Recv: Stallguard thrs	2	2	0	0	0
Recv: DRVSTATUS	X	Y	Z	Z2	E
Recv: stallguard
Recv: sg_result		0	0	0	0	0
Recv: fsactive
Recv: stst		X	X	X	X	X
Recv: olb
Recv: ola
Recv: s2gb
Recv: s2ga
Recv: otpw
Recv: ot
Recv: Driver registers:
Recv: 	X	0x80:0B:00:00
Recv: 	Y	0x80:0B:00:00
Recv: 	Z	0x80:07:00:00
Recv: 	Z2	0x80:07:00:00
Recv: 	E	0x80:0A:00:00
Recv: 
Recv: 
Recv: ok`

**Comment by burk80** [comment]
alexsomesan commented on repetier forum.. (https://forum.repetier.com/discussion/comment/21465/#Comment_21465)

It is better to solder the spi pins on the bottom of the board instead of changing the pins on the top due to power lines F*ing up the spi data with the cable solutions..

Losing the connection to the 2130 board.

seems like this might be a similar problem

**Comment by boelle** [comment]
@towe96 problem fixed?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
