### ISSUE TITLE
Thermistor is stuck at 0 when enabling dual steppers for Y-axis

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#12652]
### Description

I have a 3d printer with 2 extruders. I want to sacrifice the second extruder to use the 2nd filament driver for driving the 2nd stepper on Y-axis. So in configuration_adv.h (attached), I added:
#define Y_DUAL_STEPPER_DRIVERS
This correctly re-purpose the 2nd filament stepper driver for Y-axis, however, now the extruder 0 thermistor always reads 0. I tried putting the two config files in the latest Marlin version (1.1.x) folder, and compile, but the issue still persists. 

#### Additional Information
[config.zip](https://github.com/MarlinFirmware/Marlin/files/2683035/config.zip)

 `Configuration.h` and `Configuration_adv.h`  attached.

Update: Trying to debug this issue, I actually ended up putting my RAMPS board on fire (smoke). But I think I have understood the source of issue:
I connected the board to PC, and noticed that Repetier displays the temperature correct, while LCD displays 0. THe LCD is a touch display with an STM32 chip, which I don't have access to the firmware. My assumption is that, the STM32 chip expects a certain format of update from Marlin, and as I have disabled the 2nd extruder to enable 2nd motor for Y-axis, the format of string going from Marlin to LCD has changed. Hence, the STM32 chip can not parse the string correctly, hence the thermistor values being stuck at 0. So what are my options? Is there anything from Marlin side that I can do to solve this issue?

**Comment by RudyBenner** [comment]
I see 

#define CONFIGURATION_H_VERSION 010109

in your config file.

**Comment by boelle** [comment]
@eyewy problem fixed?
