### ISSUE TITLE
Initial extrusion jerk \ print height incorrect if MIXING_EXTRUDER defined

### ISSUE THREAD

**Issue by HattonLe** [MarlinFirmware/Marlin#12651]
Am trying to get a 3 colour delta up and running. Had issues with E1 stepping with Z axis so moved to marlin 2.0 firmware recently to see if that sorted the issue. There was some improvement (i.e. I could move Z axis without E1 moving when hot, but now have a different problem.

Board is a Rumba. Only 1 hotend installed, but all 3 extruder drivers installed. I use UBL bed levelling with a fixed Z probe and use ....G28, G29 P1, G29 S1, G29 F10, G29 A, M500 to configure it).

If I compile with MIXING_EXTRUDER patched out (i.e. so it defaults to a single extruder), everything prints fine with a single extruder.

The problem --> If I compile with MIXING_EXTRUDER defined, I can not get the printer to begin a print on the print bed.

Here is the start of the gcode I am trying to print...
G28
G1 Z15 F3000
M107
G90
M82
M190 S92
M104 T0 S234
G92 E0
M109 T0 S234
M107
G0 X0 Y11.725 Z0.3 F9000
G0 X-0.108 Y11.972
G1 X-0.358 Y12.536 E0.03078 F1800

The initial gcode move to Z15 followed by waiting for heating to complete works fine, but print extrusion starts with quite a loud clunking move which ends up with the printer trying to print about 2 or 3mm above the print bed.

If I manually home the printer and manually issue G1 Z0, the print goes correctly to the print bed, so I am sure the printer height is calibrated correctly. If I turn off UBL the same fault occurs (i.e. big jerk noise and printing way above the bed).
(My bed is pretty close to the head even without UBL, so its not a bed leveling issue).

I have tried patching out things like stepper inactive disabling, and slowing feed speeds to no effect - Its some sort of algorithm issue due to multiple extruders.

**Comment by boelle** [comment]
@casiobearing problem fixed?
