### ISSUE TITLE
FIlament Runout Sensor Works but M600 trigger all the time

### ISSUE THREAD

**Issue by ntek92** [MarlinFirmware/Marlin#12669]
Hi! 

I got the filament runout sensor connected to the Y-Max pin, i have tested the endstops with the m119 command, and works fine! when the sensor ir pushed=triggered and when the sensor is pulled=open, but excecute the M600 all the time in every print job, i have marlin 1.1.6 and a clone ramps, thank you!<!--

**Comment by ntek92** [comment]
I forgot to say, also i have changed the logic of the endstop and define the pullup, but is the same

**Comment by boelle** [comment]
@ntek92 problem fixed?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
