### ISSUE TITLE
After G29 ABL, heaters are set to 0

### ISSUE THREAD

**Issue by jrmann1999** [MarlinFirmware/Marlin#12687]
After doing a G29 ABL in Marlin 1.1.x Bugfix, my Hot end and Bed heaters get set to off

### Steps to Reproduce

1. Issue G28 followed by G29
2. Start print code

**Expected behavior:** Bed Level process followed by printing with pre-heated equipment

**Actual behavior:** Bed Levels, heaters are then set to off causing cold extrude conditions (how I caught it)

Configuration's attached in the provided zip.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2696448/Marlin.zip)

**Comment by mr-miky** [comment]
see if it is the same situation as #12441

**Comment by jrmann1999** [comment]
Disabling the ABL Expert plugin as suggested in that thread solved the issue, thanks.

I have filed a bug with that developer.
