### ISSUE TITLE
G29 MBL squishing layers 

### ISSUE THREAD

**Issue by hermes3008** [MarlinFirmware/Marlin#12688]
### Description

G29 not using active setting for z offset

### Steps to Reproduce

1. Change z offset to higher value
2. Save to eeprom
3. Home(paper test success)
4. Level bed(paper test fail)

G29 use the new setting for z offset

G29 still uses default/uploaded z offset

#### Additional Information

More info tomorrow

**Comment by hermes3008** [comment]
Simple work around upload firmware with updated z offset

**Comment by boelle** [comment]
@hermes3008 problem solved?
