### ISSUE TITLE
[bugfix-2.0.x] pin confusion for filament runout sensor and E0_AUTO_FAN_PIN

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#12686]
Hi,

I connected a switch to Servo 3 of my ramps board as a filament runout sensor. (in configuration.h, it says  "RAMPS-based boards use SERVO3_PIN for the first runout sensor." Starting counting from 1, Servo3 is Pin D5. It did not work so I tried Servo4 (Pin D4) and that works.
In pin_ramps.h it says #define FIL_RUNOUT_PIN    4.
I did start to count at 1 because my bltouch is connected to "Servo4", according to "all" the tutorials for bltouch (that would be D11).

D4 was already occupied with my E0_AUTO_FAN, so I changed E0_AUTO_FAN_PIN to 5 but it does not work with Hardware PWM. I assumed all servo pins had hardware pwm and if not, it should throw an error during compilation since I set a PWM / fan speed value and did not define softpwm.

**Comment by boelle** [comment]
@hamster65 problem solved?
