### ISSUE TITLE
Is there a Null value for Pin remaping?

### ISSUE THREAD

**Issue by mchaos** [MarlinFirmware/Marlin#12685]
i am editing my pin config pinsRAMPS file. I am utilizing 2 of the servo pins for something else, but I do not wish to actually remap them to a pin. i am not going to be using them. But if I leave it blank, it will not compile as expected. Is there a null value I can put in so that it will compile?

Thanks,

**Comment by Ludy87** [comment]
set `-1`

**Comment by boelle** [comment]
@mchaos problem solved?
