### ISSUE TITLE
[FR] if bltouch probing fails, retract probe

### ISSUE THREAD

**Issue by Chompworks** [MarlinFirmware/Marlin#12698]
After encountering some probing fails on Marlin 1.1.9, where the probe stays deployed, here's a simple feature request - add a config.h option to allow that the bltouch is reset from the error state, and the probe is retracted if Marlin experiences a probing failure while doing G29 operations.

This is to avoid damage to the Bltouch if the deployed probe is dragged across the print in progress.

While I can imagine some people _may_ rather that the probe would stay deployed - I think that preference comes down to machine setup and adding the ability to determine that config at compile is a good idea generally. What do you think?

**Comment by Seraj22** [comment]
Very good idea
