### ISSUE TITLE
Use of Y splitter and 1 nozzle, and so 1 part fan, Marlin defines 2 fans!!

### ISSUE THREAD

**Issue by lulu3d** [MarlinFirmware/Marlin#12692]
OK, I don't know if this is a bug, but it certainly bugged me, but when I configured my Marlin 2.0 to be used with an Y-splitter (so 1 nozzle and 1 part fan) I get 2 part fans definitions? Result is, when I change tool, the part fan is not working for the second tool, as I don't have it! 
I use a MKS base 1.5 as board definition.

I finally resolved the situation in the pins_RAMPS.h file, where I commented out the line:

  #if HOTENDS == 1
   // #define FAN1_PIN       MOSFET_D_PIN
  #else

Is this normal, or did I missed something else in my config, so that I have just 1 part fan and be able to use two extruders?!
[Marlin Configs.zip](https://github.com/MarlinFirmware/Marlin/files/2698615/Marlin.Configs.zip)

**Comment by InsanityAutomation** [comment]
Some of the newer code allows a single nozzle to store temps and fan speeds across tool changes for the opposing material, so identical gcode can be run here and on an idex or chimera type machine. My assumption is that with a second fan defined, its not using the storage code but trying to control the other fan. Ill look into it a bit and see if we need to add a define with single nozzle to always use fan 0.

**Comment by lulu3d** [comment]
OK , Thanks for looking into it. ;-)

**Comment by InsanityAutomation** [comment]
FYI PR #12777 makes some improvements around this for you. If that meets how you expect it to function, please close this issue.

**Comment by lulu3d** [comment]
OK, thanks for the fix It worked for me.

**Comment by thinkyhead** [comment]
> so identical gcode can be run here and on an idex or chimera type machine

G-code should always be tailored to the specific machine.

**Comment by InsanityAutomation** [comment]
@thinkyhead in theory yes for best results, but in this case just mean that it functionally acts the same regardless of hardware and doesn't require crazy scripts or strange slicer hacks. It can doesn't mean it should :)
