### ISSUE TITLE
Marlin 2.0 vs reprapFirmware. Clash of the Titans

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#12707]
Marlin 2.0 and reprapFirmware.
Board used RURAMPS, Arduino DUE.
Is the firmware stable and productive for the Arduino DUE compared to the 32 bit reprapFirmware.
Interested in functionality and performance. And how will this affect print quality?

**Comment by Roxy-3D** [comment]
There is no clash.    People are free to use (and contribute code) where ever they want.

Your title is designed to stir up hard feeling and polarize the community.  We don't need that here.

**Comment by ghost** [comment]
Which one is better here's what I wanted to know

**Comment by vladimirRUS007** [comment]
Which one is better here's what I wanted to know

пт, 21 дек. 2018 г. в 21:22, Roxy-3D <notifications@github.com>:

**Comment by ghost** [comment]
I'll go to the reprap firmware branch, I'll write the same. People should know what are the pros and cons of each of them. Am I right??? answer me please
