### ISSUE TITLE
[bugfix-2.0.x] Set Delta height went missing in the last 2.0 bugfix branch

### ISSUE THREAD

**Issue by TheMrCaveman** [MarlinFirmware/Marlin#12716]
[config.zip](https://github.com/MarlinFirmware/Marlin/files/2705582/config.zip)

### Description

Configuration > Delta configuration > Set Delta height went missing in the last 2.0 bugfix branch???

G33 cleanup messed this up horribly!!!!! 

Please revert it back. All these cleaned up functions are needed on the anycubic

**Comment by LVD-AC** [comment]
G33 P1 still works, it was just removed from the LCD menu.

**Comment by TheMrCaveman** [comment]
Why is it removed from the lcd?

**Comment by Ludy87** [comment]
> Marlin\src\lcd\menu\menu_delta_calibrate.cpp

Add
```C++

    MENU_ITEM(gcode, MSG_DELTA_HEIGHT_CALIBRATE, PSTR("G33 P1"));
    MENU_ITEM(gcode, MSG_DELTA_Z_OFFSET_CALIBRATE, PSTR("G33 P-1"));

```
after this line https://github.com/MarlinFirmware/Marlin/blob/b7a8dcc35d23d555ff2a6ebd64c71068d30859f2/Marlin/src/lcd/menu/menu_delta_calibrate.cpp#L113

**Comment by TheMrCaveman** [comment]
So if i understand it right those functions still work but not from display?

**Comment by Ludy87** [comment]
It executes the G-code as in the console

**Comment by TheMrCaveman** [comment]
The 
MENU_ITEM(gcode, MSG_DELTA_Z_OFFSET_CALIBRATE, PSTR("G33 P-1"));

Is not working,..

**Comment by Ludy87** [comment]
what does the console say?

**Comment by TheMrCaveman** [comment]
Nothing happens when i press the button

**Comment by swilkens** [comment]
This link is the state of the 2.0.x-bugfix code just before the G33 changes:

https://github.com/MarlinFirmware/Marlin/tree/7a5e637a3750e2ac27dc5fe5b5793bc6b348413b

Alternatively you can get the latest code and manually revert the changes, but that will become problematic over time.

Finally you can request for this menu feature to be returned in a feature request.

**Comment by LVD-AC** [comment]
G33 P-1 was only needed because baby-stepping the z-offset had a bug in it on deltas. Now that bug is fixed it has become obsolete so it was removed. Use the standard Marlin functions to set the z-offset, they now finally work on deltas as well :smile:

**Comment by TheMrCaveman** [comment]
So how to set the z offset normally on marlin? This is confusing for me;) I only have delta's and a;ways did it with the P-1 command

And why is the delta height removed from menu?

**Comment by LVD-AC** [comment]
After the offset-bug had been fixed:
Finetuning the z-offset can be done better with baby-stepping and re-calibrating the height is no longer required after each z-offset change. This issue is a non-issue and can be closed. @thinkyhead
