### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by TheNitek** [MarlinFirmware/Marlin#12714]
Well, this isn't a bug, but I hope it's ok anyway ;-)

I wanted to say thank you to all those investing their time into this awesome project, to allow people like me to turn their cheap (or not so cheap) china printers into into awesome usable tools. What the marlin project is achieving is really impressive.

Thank you! Much appreciated!

**Comment by RudyBenner** [comment]
Think of it this way, your problems exercise and sharpen their skills.

**Comment by boelle** [comment]
@TheNitek please click the green close button

**Comment by thinkyhead** [comment]
HTH!
