### ISSUE TITLE
[bugfix-2.0.x] G28 O (home only when position unknown) crashed into physial limit on print start

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#12710]
I discovered G28 O (oh, not zero) which saves some time. I started a print, then realized I sliced with wrong parameters, stopped, moved the printhead to the side by hand (motors off), cleaned the bed and started the new print. The printhead crashed to the forward left limit.

I can reproduce this issue:
- Start a print (With G28 O as part of the start code, followed by G29)
- Abort the print (motors switch off, xyz on lcd are blinking now)
- Move the axis by hand
- Restart the print. Homing is skipped even though the position is unknown!

**Comment by GMagician** [comment]
That's normal. You don't have an encoder as feedback then when you manually move something no one but you can know that. By firmware point of view nothing has happend.

You simply can't use G28 O if you move something manually

**Comment by hamster65** [comment]
But once the stepper motors are switched off, the position is unknown anyway, so G28 O should not be skipped after that. This is also indicated by the blinking coordinates on the display.

**Comment by GMagician** [comment]
Once stepper are turned off position is "almost" known and error should be in between a full motor step.
Marlin consider a not known position only when G28 has never been done. So it you tollerate "the turn off" misalignment error and don't move anythink then you may use G28 O otherwise G28

**Comment by hamster65** [comment]
Ok, that makes sense. Thanks!

**Comment by dlitz** [comment]
I also ran into this issue with 2.0.x, and I really don't like this behaviour.  Thankfully you can define this in Configuration_adv.h: 

    #define HOME_AFTER_DEACTIVATE  // Require rehoming after steppers are deactivated
