### ISSUE TITLE
[Question] STM32F1 / HAL / GTM32PRO Related questions

### ISSUE THREAD

**Issue by Phr3d13** [MarlinFirmware/Marlin#12722]
Trying to finish up support for this board. I'm so close. Got a weird serial/hal issue sorted with help from @p3p in discord (PR - https://github.com/MarlinFirmware/Marlin/pull/12721). But still can't seem to get this lcd's sd card to work, and still can't get eeprom/saving working. The lcd is wired and behaves exactly like a reprap discount smart lcd. I've swapped lcds from my rostock 301 (gtm32pro board) and my a10m (gt2560 variant), and all features of both screen work when hooked up to my a10m. SD is only detected on the rostock 301, but not read. As far as eeprom, I know I can change/save values when on the stock firmware (Smartto). Does anyone have any knowledge / guidance regarding my situation?

**Comment by jmz52** [comment]
Try to add 10k resistor between 3V3 and MISO line on your SD card reader.

**Comment by Phr3d13** [comment]
@jmz52 Why would that do anything helpful? The SD card and LCD work as expected with the stock firmware, Smartto.

**Comment by jmz52** [comment]
@Phr3d13 I had a stability problem on board with no pullup resistor.
Also please retest is you are still getting the original problem on current code. SPI mode was changed from SPI_MODE3 to SPI_MODE0 few weeks ago (MKS MINI12864 does not work with in SPI mode other that mode 0)

**Comment by boelle** [comment]
@Phr3d13 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by thinkyhead** [comment]
@Phr3d13 — How goes the battle?

**Comment by Phr3d13** [comment]
@thinkyhead 
Re-tested this with bugfix-2.0.x branch from today (03/10/2019 6am-ish). Example config would not compile as-is. I had to change SERIAL_PORT to -1. Compiling with Arduino IDE 1.8.7 with the patched/fixed arduino-builder.exe. LCD produces garbage instead of boot screens, but shows things correctly once the default post-startup screen loads (the info menu with temps/speeds/etc.). Menus are mostly navigable, but some menu screens crash the board, forcing user to reboot. SD only works with SDIO enabled, and not all the time. It seems to hinge on whether or not the steppers are enabled. If anyone has successfully configured Marlin for this board/chip, I would love any help. I'm not a developer and really have no idea what I'm doing beyond making example configs. Please @ tag anyone you think would be helpful. 

@jmz52 

> @Phr3d13 I had a stability problem on board with no pullup resistor.

The SD reader works 100% on the stock firmware - Smartto. If it was a pullup resistor issue, wouldn't it effect Smartto as well?

**Comment by Phr3d13** [comment]
Is there anyone on the dev team with this board who has more of a clue than I do? I can whip up an example config like a boss, but really have no clue what I'm doing here in regards to adding support for this board that doesn't have enough in common with any other Marlin-supported board.

**Comment by thinkyhead** [comment]
> Compiling with Arduino IDE 1.8.7

1.8.8 is now the minimum recommended.

The various issues you describe sound like fun to debug. I have a GTM32 board but no way to really use and test it. It doesn't fit into the A10M or the A20M, and I've not yet had it powered and running by itself. I would also need to cannibalize the displays from the A10M / A20M to test display stuff. I suppose it would be best if I had an A30 to work with. 😁

**Comment by Phr3d13** [comment]
@thinkyhead If you're ok with it, I can offer up my Rostock 301 for developing on via teamviewer or something. Combine teamviewer and a video feed, and it'll be almost like being here.
