### ISSUE TITLE
LCD shows nothing in Arduino Due + Smart Ramps 1.4.2 + RepRapDiscount Full Graphic Smart Controller

### ISSUE THREAD

**Issue by simpai** [MarlinFirmware/Marlin#12733]
### Description

LCD shows nothing in Arduino Due + Smart Ramps 1.4.2 + RepRapDiscount Full Graphic Smart Controller. Only killing switch is working.

### Steps to Reproduce

1. Download Marlin bugfix_2.0.x latest  version and set
  ```cpp
  #define MOTHERBOARD BOARD_RAMPS_SMART_EFB
  #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
  ```

2. Follow instructions found in `pins_RAMPS_SMART.h`:
  - Use Smart Adapter like normal ramps 1.4
  - Remove the AUX3 pin header on the Smart Adapter
  - Leave SD card reader not working at this moment 
  - Leave SDSS unchanged (ie. 53) to use software SPI

3. I've found LCD is showing nothing so i googled and found issue #12294

and tried to use `U8GLIB_ST7920_128X64_4X` instead of `U8GLIB_ST7920_128X64_RRD`
```cpp
#define U8G_CLASS U8GLIB_ST7920_128X64_4X
#define U8G_PARAM LCD_PINS_D4, LCD_PINS_ENABLE, LCD_PINS_RS
//#define U8G_CLASS U8GLIB_ST7920_128X64_RRD
//#define U8G_PARAM LCD_PINS_D4, LCD_PINS_ENABLE, LCD_PINS_RS  
```

**Expected behavior:** Everything is working fine except SD card reader.

**Actual behavior:** LCD is showing nothing. Only kill switch is working.

#### Additional Information

My SMART-Ramps is this one:
https://www.aliexpress.com/item/SMART-Ramps-For-Arduino-Due-Like-Ramps-FD-or-RADDS-3D-print-unit-new-reference-control/32857403412.html

**Comment by boelle** [comment]
@simpai problem solved?

**Comment by simpai** [comment]
no. 
any sugestion?

**Comment by thinkyhead** [comment]
Does the screen work properly with MK4Duo or other Due-compatible firmware?

**Comment by boelle** [comment]
@thinkyhead think we can close this one, OP did not reply

**Comment by simpai** [comment]
@thinkyhead yes i'm using it with other board. sorry for late reply

**Comment by simpai** [comment]
i suspect that LCD is run in 5V but due supplies 3.3V and i don't know how to properly wire 5v to LCD.
