### ISSUE TITLE
Cannot upload gcode files with host

### ISSUE THREAD

**Issue by Grogyan** [MarlinFirmware/Marlin#1273]
RAMPS 1.4
RepRap Discount Full Graphic Display
Tried with Max6675 enabled and disabled
Repetier Host

When attempting to upload gcode files to the SD card the host interface program hangs
Tried all these variants with MAX6675 plugged into Pin 66 for MAX6675_SS
Setting the Temp sensor to -2 ie MAX6675 Host hangs
Setting the Temp sensor to -1 ie AD595 host still hangs
Setting the Temp Sensor to 1 ie normal thermistor, host does not hang, but no file gets uploaded

**Comment by boelle** [comment]
is this still the same with latest dev?

**Comment by boelle** [comment]
no response to my Q in 13 days... closing

**Comment by Grogyan** [comment]
Still the same. 
Seems to be a SPI issue.

**Comment by boelle** [comment]
yep... each SPI device needs a seperate CS line to the MCU

**Comment by Grogyan** [comment]
Have tried the newest, as of today, development branch.
Have noticed in Repetier that when it tries to upload any gcode file, it adds a space and a fullstop in addition to what you type into the file name in Repetier 1.06

**Comment by thinkyhead** [comment]
Hmm, if it works with the current Stable branch, then we should definitely make a comparison. Also figure out how long ago this problem arose, so maybe we can track it to a single commit.

**Comment by boelle** [comment]
is this still an issue with latest copy and latest non-beta IDE?

**Comment by boelle** [comment]
will close this one as there was no response.... can reopen if someone reports the issue is still there

**Comment by Grogyan** [comment]
Am still seeing this happen with the latest Dev Branch,
Repetier 1.06,
RAMPS 1.4,
Full Graphic display
Max6675 thermocouple

Could be an issue with Repetier

**Comment by AnHardt** [comment]
#1226 #1227

**Comment by AnHardt** [comment]
> Could be an issue with Repetier

Made some tests with different configurations
Mega - RAMPS1.4 - Dummy-temperature-sensors
without display - just sd-cadr
with REPRAP_DISCOUNT_SMART_CONTROLLER
with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

Test: upload file to sd-card for all hardware combinations
Octorint 1.1.1 worked
Pronterface 2014.03.10 worked
Cura 15.2.1 did not recognize the sd-card at all
Repetier-Host 1.06  failed on all hardware configurations

This means:
The upload error is independent of MAX6675 and REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
File upload with Repetier is not a valid test for #1226 #1227

**Comment by boelle** [comment]
would be very tempted to say that its not a marlin problem

**Comment by AnHardt** [comment]
Another interesting thing is that Repetier fails different depending on the case of filename.

cube.gco fails with:
14:56:36.060 : N31 M28 cube.gco *127
14:56:36.064 : echo:Now fresh file: cube.gco
14:56:36.070 : N32 M29 *9
14:56:36.084 : open failed, File: cube.gco .
14:56:36.084 : ok
14:56:36.084 : ok

while CUBE.GCO fails with:
14:58:24.646 : N68 M28 CUBE.GCO *83
14:58:24.648 : ok
14:58:25.688 : No firmware response detected for sd action. Assuming success and continue.
...
And not have loaded up.

**Comment by AnHardt** [comment]
@boelle 
Yes!

**Comment by boelle** [comment]
closeing then so we can focus or bugs in marlin,  and a small prayer that the people that do host software could fix it...

as always we can reopen... and people are welcome to debate on even if closed
