### ISSUE TITLE
[question] save cpu cycles

### ISSUE THREAD

**Issue by Alissonverd** [MarlinFirmware/Marlin#12735]
Dear friends.
To save CPU cycles I need remove the comment in ENDSTOP_INTERRUPTS_FEATURE?

// Enable this feature if all enabled endstop pins are interrupt-capable.
// This will remove the need to poll the interrupt pins, saving many CPU cycles.
// #define ENDSTOP_INTERRUPTS_FEATURE

The TMC2130 SPI need this feature enable or disabled?

Thank you

**Comment by teemuatlut** [comment]
Can't compile if you enable it.

**Comment by ghost** [comment]
This can only be enabled if your contoller board / printer combination has got the pin definitions for alll endstops set to those pins that the defined processor accepts as being interupt capable. You can google this. 
For example: My old Anet A8 with the stock Anet controller had all endstops on cpu pins that were interrupt capable and enabling this ENDSTOPS_INTERUPTS_FEATURE was successful.
I replaced that board with a Geetech GT2560 and sadly, the endstop pins are no longer interrupt capable, why the manufacturer chose the wrong pins,I don't know. Cannot enable this feature.
When you compile, your pin defintions and defined processor type are checked - it is well known which pins support interrupts and vice versa.
I need to say: Performance when not enabling was still ok, so no sweat. Works even without the interrupts.
IMHO this has nothing to do with TMC2130 SPI at all - it is only about saving some CPU cycles to not query the endstop switches every timer-tick.

**Comment by Alissonverd** [comment]
Thank you!!! I will disable and install TMC2130.
