### ISSUE TITLE
anet a8 restarts when buttons are pressed

### ISSUE THREAD

**Issue by AngryCarrot789** [MarlinFirmware/Marlin#12736]
whenever i click any button on the lcd board the printer restarts, whether it's the back button, up/down buttons or enter button.
is there any way to fix this??

**Comment by Ludy87** [comment]
check the cable connection from the display

**Comment by AngryCarrot789** [comment]
every connector is in correctly... still does it

**Comment by Ludy87** [comment]
Please send a `Configuration.h` `Configuration_adv.h` and` pin_*.h`

**Comment by AngryCarrot789** [comment]
where do i get those?

**Comment by AngryCarrot789** [comment]
also i dont yet have an SD card, i used repetier host over USB to print things, but i accidentally ripped the USB port off the main board. when i removed the whole connector and started it, it started restarting every time i pressed some buttons. i've tried cleaning the port area incase of shorts and looking for blown caps but there's nothing

**Comment by Ludy87** [comment]
Okay, you have the stock firmware, is that right?

Then you should deal with the flash of Marlin to rule out a software error.

**Comment by AngryCarrot789** [comment]
(saying i did have an SD card avaliable), i cant do anything with the LCD/buttons because it just restarts. how would i force it to reinstall the firmware? (if that's what you think i should do)

**Comment by Ludy87** [comment]
Flash works via Arduino IDE or PlatformIO
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x#building-marlin-20

**Comment by AngryCarrot789** [comment]
i'll just buy a new mainboard :)
would be much easier than having to solder wires onto the usb connector pads and trying to make all that work.

**Comment by trivalik** [comment]
Building marin and program via the usb cable, does not need any solder. So give it a try for later.

**Comment by AnHardt** [comment]
@triffid 
If you want to support someone - read his messages.

> ripped the USB port off the main board

**Comment by triffid** [comment]
@anhardt tagged the wrong person :P

**Comment by boelle** [comment]
@AngryCarrot789 problem solved?
