### ISSUE TITLE
Error:EEPROM datasize error.

### ISSUE THREAD

**Issue by WrQth** [MarlinFirmware/Marlin#12749]
### Description

Unable to use EEPROM with Azteeg X5 mini wifi, Error:EEPROM datasize error. Enabling "#define DEBUG_EEPROM_READWRITE" gives error "Marlin/src/module/configuration_store.cpp:696:19: error: 'SettingsData {aka struct SettingsDataStruct}' has no member named 'lcd_preheat_hotend_temp'; did you mean 'ui_preheat_hotend_temp'?" during build. No LCD installed just onboard SDcard.

### Steps to Reproduce

1. Flashed latest version 2.0.x
2. Multiple SD cards used

**Expected behavior:** M500 save settings

**Actual behavior:** Settings from M500 not saved and receive error

#### Additional Information
[Config_files.zip](https://github.com/MarlinFirmware/Marlin/files/2715395/Config_files.zip)

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by GMagician** [comment]
Maybe same issue than #12744?
#12746 may fix it

**Comment by WrQth** [comment]
#12746 fixed compile but now I get a different error from M500 which is "Error:Field home_offset mismatch"

**Comment by GMagician** [comment]
did m502 before?

**Comment by WrQth** [comment]
Yes, performed M502 without error then M500.

**Comment by GMagician** [comment]
try replace line 490 in configuration_store from:
```c++
dummy = float(DEFAULT_EJERK);
EEPROM_WRITE(dummy);
```

to:
```c++
const float max_jerk[XYZE] = { 10, 10, 0.3, DEFAULT_EJERK };
EEPROM_WRITE(max_jerk);
```

**Comment by WrQth** [comment]
Same error "Error:Field home_offset mismatch". I have Junction Deviation enabled so classic jerk isn't being used and if I am understanding the logic of that IF statement then the change made to the code isn't processed.

**Comment by Ludy87** [comment]
https://github.com/MarlinFirmware/Marlin/pull/12746 I tried and this error does not come anymore.

**Comment by GMagician** [comment]
@Ludy87 I checked code where it read data and it seems that in else it uses a for cycle. Am I wrong?

**Comment by GMagician** [comment]
@thinkyhead, @Ludy87 I think that #12720 has added this issue.
If jerk data is not saved in `save` function it must neighter be loaded in `load`.
Also it introduced a sanitycheck bug that I fixed with an already posted PR

**Comment by Ludy87** [comment]
@GMagician I do not understand why that does not work.
Jerk is disable everywhere if `JUNCTION_DEVIATION` is enable.

`planner.max_jerk` is also not called with `JUNCTION_DEVIATION` active.

**Comment by GMagician** [comment]
@Ludy87 you have to look to read function in correspondent `#else`. There is a for cycle that skip "dummy".
If you don't write such dummy values you also need to "not" skip them as well.

This is true if I didn't missed something :-)

**Comment by Nuttavoot** [comment]
I also get "EEPROM datasize error" when issue M500, M501, M504 on RE-ARM board and no file eeprom.data was created on the SD card.

**Comment by WrQth** [comment]
EEPROM is working properly after loaded build as of 9:00am EST 12/31/18 not sure if something was changed but my configs remained the same. However I did do one thing different before sending the M500 which was to set the home offsets via the M206 command equivalent to the home offset I had saved to EEPROM when I was using smoothieware, unlikely this made any different and it was something in the new build that resolved my issue.

**Comment by GMagician** [comment]
Yes has been rolled back code by @Ludy87

**Comment by Nuttavoot** [comment]
EEPROM commands work correctly for me as well for that build.

**Comment by boelle** [comment]
@WrQth problem solved?

**Comment by WrQth** [comment]
After rollback in DEC and since then on newer builds it has been working
