### ISSUE TITLE
Marlin 2.0 and GTM32 temperature issue

### ISSUE THREAD

**Issue by PvvS** [MarlinFirmware/Marlin#12743]
I managed to translate and install. But the problem is with temperatures. After cooling down, the LCD is set to 0 at the hotend i heatbed. After warming up, the temperature is correct. At least, according to the multimeter.

**Comment by macasero** [comment]
I have a spare board gtm32_mini_S and would like to test marlin 2, what ide did you use and what settings?

**Comment by boelle** [comment]
@PvvS problem solved?

**Comment by PvvS** [comment]
I have to test the last version on a weekend, but it is not yet. After cooling, it shows 0 degrees. After warming up the temperature.

**Comment by boelle** [comment]
did you do any further testing?

**Comment by PvvS** [comment]
Last weekend I downloaded the last build and the problem persists. Still the same symptoms. At room temperature it measures 0, the temperature is the same as the measured temperature.

**Comment by boelle** [comment]
could i ask that you add [BUG] in the title line so it becomes: [BUG]Marlin 2.0 and GTM32 temperature issue

and also attach your 2 config files as a zip file so that @thinkyhead can have a look

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
