### ISSUE TITLE
Delta printer problem - go down after G28 (-Z_PROBE_OFFSET_FROM_EXTRUDER)

### ISSUE THREAD

**Issue by e-Mole** [MarlinFirmware/Marlin#12754]
After homing (G28) my delta printer effector goes down (the downward shift is value of Z_PROBE_OFFSET_FROM_EXTRUDER).  But the printer height remains unchanged, so printing will start "under" the print bed (the print head crashes into the bed). I'm using a mechanical probe like allen key (Z_PROBE_OFFSET_FROM_EXTRUDER -3.90).
I changed this code in motion.cpp:
 
#
      #if HAS_BED_PROBE
        - zprobe_zoffset
      #endif

to older version:

 #
      #if HAS_BED_PROBE
        - zprobe_zoffset + Z_PROBE_OFFSET_FROM_EXTRUDER
      #endif

The problem disappeared.
Is this bug or my wrong configuration?

**Comment by LVD-AC** [comment]
You need to re-calibrate the delta_height after the latest fix.

**Comment by e-Mole** [comment]
@LVD-AC : Thanks for comment. I did the recalibration, but the result is the same. I did recalibrate the height classically with "paper test". Would it mean I have first to measure the distance of the probe and then subtract it from total height? This is very impractical... How to proceed correctly?

**Comment by LVD-AC** [comment]
In short 1) calibrate DELTA_HEIGHT so the probe probes at zero and 2) calibrate Z_PROBE_OFFSET_FROM_EXTRUDER so a paper test returns zero. You are mixing the 2 (like on printers without a probe).

Issue a probe command G30 X0 Y0 and use the return value of that to set the DELTA_HEIGHT. Or use G33 P1 to do this automatically.

**Comment by boelle** [comment]
@e-Mole still a problem?
