### ISSUE TITLE
3D touch ERROR ENDER 3 MARLIN TH3D U1.R2.7

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#12750]
### Description
I just installed a 3D touch on my ender 3 but I haven't been able to make it work 
BLtouch settings do appear in the LCD and I can stow and deploy.
### Steps to Reproduce
when I send G28 it homes X, Y when Z is probing it stops and prompts the following error
Error: Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)
I read that sometimes the probe isn't TRIGGERED so I tested with M119 and it was working
#### Additional Information
already tried using both custom probe and bltouch in the firmware but can't find the issue, I started following this guide 
https://www.youtube.com/watch?v=ocAeZRPVusw&t=620s
but I've read several guides trying to fix the issue
things that I've tried:
- #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN was already defined
- already changed the z offset for the probe
- simulated the touch using the Z endstop 
- I tried to enable pins_debugging but wasn't able to find it in the firmware

**Comment by GMagician** [comment]
What result did you get with M119? Since trigger is very fast you should never see it

**Comment by ghost** [comment]
> What result did you get with M119? Since trigger is very fast you should never see it
 Z marked triggered after it stoped for the error

**Comment by GMagician** [comment]
When Z start homing, can probe fully deploy?

**Comment by ghost** [comment]
it seems to probe twice, the first time it did the second it didnt

**Comment by GMagician** [comment]
So it deploy move Z down, trigger, stow, z raise, deploy again and move down then error?
Please detail sequence if not this way

**Comment by ghost** [comment]
once it's centered it seems like it starts with a self-test, then deploys, moves down, trigger, moves up a little bit, then deploys(seems like it doesn't deploy enough to the full length), instantly stows. then moves up a little bit again

**Comment by GMagician** [comment]
What about Z_CLEARANCE_DEPLOY_PROBE and Z_CLEARANCE_BETWEEN_PROBES values? maybe are to little to properly let probe deploy after trigger

**Comment by ghost** [comment]
HAD 
  #define Z_CLEARANCE_DEPLOY_PROBE   5
  #define Z_CLEARANCE_BETWEEN_PROBES 3 
changed both to 10 
error changed 
Error:STOP called because of BLTouch error - restart with M999

after uploading, I did M502 and M500 as recommended in some threads 

just in case I've a piece of foam above the bed in case it doesn't stop on time

**Comment by GMagician** [comment]
Such error raises when bltouch report triggered when it has to deploy.
If you execute M119 when stowed what do you get? and when manually deployed?

**Comment by ghost** [comment]
echo:enqueueing "M280 P0 S90"
Reporting endstop status
x_min: open
y_min: open
z_min: TRIGGERED
ok
echo:enqueueing "M280 P0 S10"
Reporting endstop status
x_min: open
y_min: open
z_min: open
ok

**Comment by ghost** [comment]
changed both clearances to 20 and G28 is working properly now (i will adjust it later so its low enough ). I proceeded to do G29, it does the first probing correctly and when moving to the second one it has an error again 

Error: STOP called because of BLTouch error - restart with M999

while it's moving to the second point the led is blinking when it stops XY movement it goes up and then goes to Z and stops

**Comment by ghost** [comment]
Don't know if it could be due to it not restarting the probe when moving to another location. at the moment after probing it goes up while led is blinking and then it resets before probing again. when it moves to the second location it seems like its not resetting the probe

**Comment by GMagician** [comment]
That's not good. M119 should always return open

**Comment by ghost** [comment]
I accidentally ordered two probes, I checked with both and it's not working. G28 and first corner work properly

**Comment by ghost** [comment]
> That's not good. M119 should always return open
I put custom probe and manually changed some settings to BLTOUCH do not know if that could be the issue

**Comment by GMagician** [comment]
Usually probe should report "open" because "triggered" lasts for 10ms only and you can't catch it.
Triggered is also reported when there is an error. Now, when you deploy manually led is blinking?

**Comment by swilkens** [comment]
Have you verified with vanilla marlin in stead of TH3D?

**Comment by ghost** [comment]
sorry for the late reply I was on vacation. I tried using vanilla marlin and it's working perfectly now 
thank you both for the help
