### ISSUE TITLE
Communicate with i2c twibus, Arduino to Arduino

### ISSUE THREAD

**Issue by bulior** [MarlinFirmware/Marlin#12756]
Is there a way to send gcodes like Homing (G28 X) from one Arduino or Microcontroller to An Arduino Mega with Marlin over i2c? 

Until now we can send something and Marlin would receive it but the Command wouldn't be executed. The received string would be printed in Serialmotior. How can we execute the received String? 

Best regards 
Ben

**Comment by GMagician** [comment]
Maybe you have to pass command to `enqueue_and_echo_command_now`

**Comment by bulior** [comment]
Is this a void and in which library is it?
Twinbus.cpp?

**Comment by GMagician** [comment]
You have to modify marlin firmware to get info via i2c and call such function when you have read commands

**Comment by miltostsalekkas** [comment]
I have the same issue. Could you give some more details about how that can be done?

**Comment by GMagician** [comment]
Don't know exaclty how to use i2c within marlin firmware but for sure you must call `enqueue_and_echo_command_now` when you have command string, searching inside Marlin source you can see that how/when it's called

**Comment by bulior** [comment]
Thanks @GMagician!

We have solved the problem and now we can receive Gcodes with an i2c Master.  
We customized twibus.cpp TWIBUS::echodata with your command:

> // static
> void TWIBus::echodata(uint8_t bytes, const char prefix[], uint8_t adr) {
>   echoprefix(bytes, prefix, adr);
> 
>    String gcode = "";
>   
>   while (bytes-- && Wire.available())
>   {
>     gcode = gcode + char(Wire.read());
>     //SERIAL_CHAR(Wire.read());
>   }
>   
>    int gcode_length = gcode.length() + 1;
>    char gcode_array[gcode_length];
>    gcode.toCharArray(gcode_array, gcode_length);
>    enqueue_and_echo_command(gcode_array);
> 
>   SERIAL_EOL();
> 
> }

**Comment by miltostsalekkas** [comment]
Thank you all very much.It works fine!

**Comment by boelle** [comment]
@bulior problem fixed?

**Comment by miltostsalekkas** [comment]
Yes.

**Comment by boelle** [comment]
click green close button below then
