### ISSUE TITLE
RADDS + REPRAP_DISCOUNT_SMART_CONTROLLER

### ISSUE THREAD

**Issue by mignolo4** [MarlinFirmware/Marlin#12765]
It seems that I had bad luck choosing the hw for  my 3d printer :-)

After I gave up with the issue here ( #12461 ), few days ago I had the opportunity to try the
REPRAP_DISCOUNT_SMART_CONTROLLER on the same 3dprinter (a DELTA style printer with RADDS board and ArduinoDue)

**The problem is:**
as soon as I choose that LCD, without any other change (apart the RADDS board) the compiling fails:

```
sketch\src\lcd\HD44780\ultralcd_HD44780.cpp:90:17: error: 'LCD_PINS_RS' was not declared in this scope
LCD_CLASS lcd(LCD_PINS_RS, LCD_PINS_ENABLE, LCD_PINS_D4, LCD_PINS_D5, LCD_PINS_D6, LCD_PINS_D7);
sketch\src\lcd\HD44780\ultralcd_HD44780.cpp:90:30: error: 'LCD_PINS_ENABLE' was not declared in this scope
LCD_CLASS lcd(LCD_PINS_RS, LCD_PINS_ENABLE, LCD_PINS_D4, LCD_PINS_D5, LCD_PINS_D6, LCD_PINS_D7);
exit status 1
Errore durante la compilazione per la scheda Arduino Due (Programming Port).
```

### Steps to Reproduce
- download the current build (bugfix-2.0.x obviously)
- edit configuration.h with
  ```cpp
  #define MOTHERBOARD BOARD_RADDS
  #define REPRAP_DISCOUNT_SMART_CONTROLLER
  ```
- compile -> errors

I suppose is not necessary but...
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2716807/Configuration.zip)

**Comment by GMagician** [comment]
remove `//` from your config in line with `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` if this is your lcd.
It seems `REPRAP_DISCOUNT_SMART_CONTROLLER` is not defined in radss

**Comment by mignolo4** [comment]
@GMagician 
`REPRAP_DISCOUNT_SMART_CONTROLLER` is my current lcd

edit:
I spent the whole afternoon trying different things, but I failed :-(

Mainly I tried to add this to the **pins_RADDS.h** :
```cpp
  #elif ENABLED(REPRAP_DISCOUNT_SMART_CONTROLLER)
    #define LCD_PINS_RS     42
    #define LCD_PINS_ENABLE 43
    #define LCD_PINS_D4     44
    #define LCD_PINS_D5     45
    #define LCD_PINS_D6     46
    #define LCD_PINS_D7     47
    #define BEEPER_PIN      41
    #define BTN_EN1         50
    #define BTN_EN2         52
    #define BTN_ENC         48
    #define SDSS            10
    #define SD_DETECT_PIN   14
```
under the  `#if ENABLED(ULTRA_LCD)` section.

At this point indeed **it compiles with no errors** but the lcd remain empty as before.
Through Repetier Host I can see the printer works as expected and the sdcard too.
This time, even the other firmwares don't work (tried RepetierFW and MarlinKimbra).
The display I'm using comes from a Anycubic Linear Plus.

So now the only display I could use is a RADDS_DISPLAY, but I'd rather not spend the money in another display.
@thinkyhead I'm lost without you (and your team), and onestly it seems strange to me that RADDS+FGLCD or SmartController are not so widespread out there :-)

**Comment by boelle** [comment]
@mignolo4 still an issue?

**Comment by mignolo4** [comment]
It was my fault, there was a mistake I did building the adapter + you need to add the above-mentioned  section to the "pins_RADDS.h" file.
You can close it, thank you @boelle 

N.B. Anyway I think it could be useful for everyone to add that section to the "pins_RADDS.h" file!

**Comment by boelle** [comment]
i can't close, only you and @thinkyhead  can close

but yes, if the comments in firmware needs to be more clear its also @thinkyhead that can do that

**Comment by ShadowOfTheDamn** [comment]
@mignolo4 I have the same problem and I have checked my adapter MANY TIMES. can you tell me what adapter you used and what was your mistake.
