### ISSUE TITLE
Delta printer problem - "stuttering" in peripheral bed zones

### ISSUE THREAD

**Issue by e-Mole** [MarlinFirmware/Marlin#12762]
### Description

When fast moving in peripheral zones (delta printer) - "stuttering" occurs (strange creaking, skipping steps (?)) - the exact position is lost. But this occurs only near of bed edge.
Tested with ver. 2.0.x and 1.1.9 (this problem does not happen in version 1.1.9).

### Steps to Reproduce

HW config: Arduino MEGA + RAMPS 1.4 + A4988,
bed diameter 265 mm,
diag_rod 278 mm,
segments/s 100

F8000
G0 Z100 X0Y-120 F8000 (stuttering)
G0 Z100 X0Y-110 F8000 (o.k)

F6000
G0 Z100 X0Y-120 F6000 (stuttering)
G0 Z100 X0Y-110 F6000 (o.k)

F4000
G0 Z100 X0Y-120 F4000 (o.k)
G0 Z100 X0Y-110 F4000 (o.k)

In this examples "skipping" occurs on towers X and Y a few mm before the end of movement (the movement of carriages is small on end movement).

Where could the problem be? Something in the configuration or bug in code?
[Marlin-config.zip](https://github.com/MarlinFirmware/Marlin/files/2716724/Marlin-config.zip)

**Comment by e-Mole** [comment]
Please, have any idea?

**Comment by boelle** [comment]
@e-Mole 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone

**Comment by thinkyhead** [comment]
It sounds like planner starvation. All you can really do is lower your print speed until the symptom abates.

**Comment by e-Mole** [comment]
@thinkyhead Unfortunately, the current maximum speed on my deltas is 60 mm / sec, making printing slower by half. That's really bad.

**Comment by boelle** [comment]
> All you can really do is lower your print speed

or you can upgrade to re-arm instead of Mega (the mega is VERY SLOW)

**Comment by e-Mole** [comment]
@boelle Hi, today I tested last 2.x version and problem with "stuttering" is gone! Thanks to all developers :-).
