### ISSUE TITLE
Ender 3 Example Configuration Bed Size

### ISSUE THREAD

**Issue by a1b0hph0b1a** [MarlinFirmware/Marlin#12763]
This is probably in the wrong place for this, but it's a stupidly quick fix for anyone who has the permissions to do so...

The bed size in the example configurations folder for the Creality Ender 3 is too small...

Marlin --> Example Configurations --> Creality --> Ender 3 --> Configuration.h

What is in the current file...
    #define X_BED_SIZE 220
    #define Y_BED_SIZE 220

What it should say...
    #define X_BED_SIZE 235
    #define Y_BED_SIZE 235

Issue is present in 1.1.X and 1.1.X-bugfix.

**Comment by swilkens** [comment]
Looks like it's 235 in the manufacturer firmware as well, can't directly see a reason why this would be 220 here.

Created the modifications for 1.1.x and 2.0.x
