### ISSUE TITLE
Not an issue just want to know how

### ISSUE THREAD

**Issue by tibuck** [MarlinFirmware/Marlin#12760]
I am using my printer as a Direct ink to PCB, it would be useful to invert motor direction for back side of the PCB, How would i do about adding a Mcode or a Gcode to Marlin to allow me to do the invert direction on the fly ?

**Comment by tibuck** [comment]
How do i add a Mcode or Gcode to invert stepper motor direction on the fly ?

**Comment by GMagician** [comment]
Some slicer let you mirror you object (Cura)

**Comment by tibuck** [comment]
> Some slicer let you mirror you object (Cura)

I understand what you are getting at, its not what i need, I use  copper boards of a set size and a alignment jig on the pen mount, When i print the top layer of the PCB i have it starting at 0.0,  when i flip the board over to print the second side, it all changes where the o.o is, Hens why i want to use a custom Gcode to have the new 0.0 to be on the opposite side of the axis. Something like the M569 in reprap firmware or like the M562 in the MP mini firmware.  it shouldn't be too hard to add a custom M-code invert stepper direction, i just don't know how to add it, probably in the marlin_main.cpp

**Comment by GMagician** [comment]
once you mirror your object you may use G92 in your gcode to shift origin

**Comment by GMagician** [comment]
I think there is nothing in marlin that let you switch on fly motor direction

**Comment by tibuck** [comment]
I already use the G92 to set the new 0.0 as a offset but regardless, the printers movements will always be in the direction set by the firmware, Marlin in this case, "There is nothing in marlin" YET, there is nothing till, someone asks or needs it lol, But im sure there probably was at one point,

**Comment by Knaudler** [comment]
hi
only way in marlin is m92 with negative values, but dont think it works on the fly

**Comment by tibuck** [comment]
> hi
> only way in marlin is m92 with negative values, but dont think it works on the fly

No it doesn't work for what i need, But i made a temp fix by adding a cable connector to that motor, I just flip the connections when i need it to go one way and flip it round to go the other. Not ideal but works till someone smarter then me can figure out how to make this a custom Gcode. But thank you for the suggestion nonetheless.

**Comment by GMagician** [comment]
I think is not possible to work that way. Now motor inversion is handled by constant variables used while compiling. Changing it will slow down code execution and I think is now a valid way.
Maybe can be handled adding gcode like CNC (X / Y mirror) but that's too much for my knowledge

**Comment by Roxy-3D** [comment]
One way to do it would be to tweak the macros used to feed steps to the stepper motors.  The IDEX machines have a 'Duplication Mode' that feeds pulses to both (independent) extruders.    If you look at the macros to see how that is done...    It is almost trivial to make the macros feed pulses that move the extruder(s) in an opposite direction.

The big problem is when you flip directions, you might want to update (or mirror) your current position so that the end stops are the 'correct' distance from where ever the nozzle is located.

The code I'm talking about is in stepper.c:
```
#elif ENABLED(DUAL_X_CARRIAGE)
  #define X_APPLY_DIR(v,ALWAYS) \
    if (extruder_duplication_enabled || ALWAYS) { \
      X_DIR_WRITE(v); \
      X2_DIR_WRITE(v); \
    } \
    else { \
      if (movement_extruder()) X2_DIR_WRITE(v); else X_DIR_WRITE(v); \
    }
  #define X_APPLY_STEP(v,ALWAYS) \
    if (extruder_duplication_enabled || ALWAYS) { \
      X_STEP_WRITE(v); \
      X2_STEP_WRITE(v); \
    } \
    else { \
      if (movement_extruder()) X2_STEP_WRITE(v); else X_STEP_WRITE(v); \
    }
#else
```

If you add an M command to toggle reversal on or off...  you would just need one if statement that checked that global flag to decide which way to set the direction.  (You aren't going to change this code!!!  This is for IDEX machines.  You actually want to change the non-IDEX macros...)

**Comment by boelle** [comment]
@tibuck 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone
