### ISSUE TITLE
Sanity Check error similar to "[2.0.x] Fix bad sanitycheck" #12748

### ISSUE THREAD

**Issue by xeddog** [MarlinFirmware/Marlin#12766]
### Description

As title says.  Build using platformio fails when G26 MESH validation is enabled and "AUTO_BED_LEVELING_BILINEAR" is also enabled:  Screenshot included.

### Steps to Reproduce
Just run Build in platformio again

**Expected behavior:** [What you expect to happen]
Successful Build
**Actual behavior:** [What actually happens]
Build fails as shown in screenshot

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

![screenshot from 2018-12-29 17-09-42](https://user-images.githubusercontent.com/8324160/50543408-d518a580-0b8c-11e9-862a-2b692b27b2a4.png)

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2716834/Configuration.zip)

**Comment by Roxy-3D** [comment]
The Sanity Check used to be correct and allow G26 to be built in the Bi-Linear bed leveling systems.    Some thing (simple???) must of broke...

**Comment by GMagician** [comment]
It's the same error I got and I hope it has been fixed by my PR

**Comment by xeddog** [comment]
The only reason I opened this issue is because #12748 Specifically talked about MESH levelling and I just wanted to make sure BiLinear was also included.  I would also **ASSUME** UBL would be the same.

**Comment by boelle** [comment]
@xeddog problem fixed?

**Comment by xeddog** [comment]
I completely forgot this was even opened.  Sorry.  And yes, the problem was resolved.
