### ISSUE TITLE
TMC2130 and Marlin 2.0 can't compile

### ISSUE THREAD

**Issue by pulster** [MarlinFirmware/Marlin#12764]
### Description

I'm trying to compile Marlin 2.0 and activating TMC2130 on Y axis. I cannot compile. I've included the error. 

I can compile if I use TMC2130_STANDALONE, but not when using TMC2130.

My pins file for GT2560_REV_A is the standard one given with Marlin, with removed Y_MAX_PIN and replaced by Y_CS_PIN.

#### Additional Information

[Configuration_files.zip](https://github.com/MarlinFirmware/Marlin/files/2716768/Configuration_files.zip)

Here is the error message:

Arduino: 1.9.0-beta (Mac OS X), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch/src/inc/../HAL/HAL_AVR/HAL.h:36:0,
                 from sketch/src/inc/MarlinConfig.h:30,
                 from sketch/src/Marlin.h:24,
                 from sketch/src/Marlin.cpp:31:
sketch/src/inc/../pins/pins_GT2560_REV_A.h:96:33: error: pasting "/* Must be enabled at startup to keep power flowing*/" and "_DDR" does not give a valid preprocessing token
 #define SUICIDE_PIN        54   // Must be enabled at startup to keep power flowing
                                 ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:82:42: note: in definition of macro '_SET_OUTPUT'
 #define _SET_OUTPUT(IO)       SBI(DIO ## IO ## _DDR, DIO ## IO ## _PIN)
                                          ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:100:35: note: in expansion of macro 'SET_OUTPUT'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                   ^
sketch/src/Marlin.h:242:27: note: in expansion of macro 'OUT_WRITE'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                           ^
sketch/src/Marlin.h:242:37: note: in expansion of macro 'SUICIDE_PIN'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                                     ^
sketch/src/inc/../pins/pins_GT2560_REV_A.h:96:33: error: pasting "/* Must be enabled at startup to keep power flowing*/" and "_PIN" does not give a valid preprocessing token
 #define SUICIDE_PIN        54   // Must be enabled at startup to keep power flowing
                                 ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:82:61: note: in definition of macro '_SET_OUTPUT'
 #define _SET_OUTPUT(IO)       SBI(DIO ## IO ## _DDR, DIO ## IO ## _PIN)
                                                             ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:100:35: note: in expansion of macro 'SET_OUTPUT'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                   ^
sketch/src/Marlin.h:242:27: note: in expansion of macro 'OUT_WRITE'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                           ^
sketch/src/Marlin.h:242:37: note: in expansion of macro 'SUICIDE_PIN'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                                     ^
In file included from sketch/src/inc/../HAL/HAL_AVR/HAL.h:36:0,
                 from sketch/src/inc/MarlinConfig.h:30,
                 from sketch/src/Marlin.h:24,
                 from sketch/src/Marlin.cpp:31:
sketch/src/inc/../pins/pins_GT2560_REV_A.h:96:33: error: pasting "/* Must be enabled at startup to keep power flowing*/" and "_RPORT" does not give a valid preprocessing token
 #define SUICIDE_PIN        54   // Must be enabled at startup to keep power flowing
                                 ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:77:48: note: in definition of macro '_WRITE'
 #define _WRITE(IO,V)          do{ if (&(DIO ## IO ## _RPORT) < (uint8_t*)0x100) _WRITE_NC(IO,V); else _WRITE_C(IO,V); }while(0)
                                                ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:100:51: note: in expansion of macro 'WRITE'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                                   ^
sketch/src/Marlin.h:242:27: note: in expansion of macro 'OUT_WRITE'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                           ^
sketch/src/Marlin.h:242:37: note: in expansion of macro 'SUICIDE_PIN'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                                     ^
sketch/src/inc/../pins/pins_GT2560_REV_A.h:96:33: error: pasting "/* Must be enabled at startup to keep power flowing*/" and "_WPORT" does not give a valid preprocessing token
 #define SUICIDE_PIN        54   // Must be enabled at startup to keep power flowing
                                 ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:67:21: note: in definition of macro '_WRITE_NC'
   if (V) SBI(DIO ## IO ## _WPORT, DIO ## IO ## _PIN); \
                     ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:89:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:100:51: note: in expansion of macro 'WRITE'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                                   ^
sketch/src/Marlin.h:242:27: note: in expansion of macro 'OUT_WRITE'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                           ^
sketch/src/Marlin.h:242:37: note: in expansion of macro 'SUICIDE_PIN'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                                     ^
sketch/src/inc/../pins/pins_GT2560_REV_A.h:96:33: error: pasting "/* Must be enabled at startup to keep power flowing*/" and "_PIN" does not give a valid preprocessing token
 #define SUICIDE_PIN        54   // Must be enabled at startup to keep power flowing
                                 ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:67:42: note: in definition of macro '_WRITE_NC'
   if (V) SBI(DIO ## IO ## _WPORT, DIO ## IO ## _PIN); \
                                          ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:89:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:100:51: note: in expansion of macro 'WRITE'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                                   ^
sketch/src/Marlin.h:242:27: note: in expansion of macro 'OUT_WRITE'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                           ^
sketch/src/Marlin.h:242:37: note: in expansion of macro 'SUICIDE_PIN'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                                     ^
sketch/src/inc/../pins/pins_GT2560_REV_A.h:96:33: error: pasting "/* Must be enabled at startup to keep power flowing*/" and "_WPORT" does not give a valid preprocessing token
 #define SUICIDE_PIN        54   // Must be enabled at startup to keep power flowing
                                 ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:68:21: note: in definition of macro '_WRITE_NC'
   else   CBI(DIO ## IO ## _WPORT, DIO ## IO ## _PIN); \
                     ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:89:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:100:51: note: in expansion of macro 'WRITE'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                                   ^
sketch/src/Marlin.h:242:27: note: in expansion of macro 'OUT_WRITE'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                           ^
sketch/src/Marlin.h:242:37: note: in expansion of macro 'SUICIDE_PIN'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                                     ^
sketch/src/inc/../pins/pins_GT2560_REV_A.h:96:33: error: pasting "/* Must be enabled at startup to keep power flowing*/" and "_PIN" does not give a valid preprocessing token
 #define SUICIDE_PIN        54   // Must be enabled at startup to keep power flowing
                                 ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:68:42: note: in definition of macro '_WRITE_NC'
   else   CBI(DIO ## IO ## _WPORT, DIO ## IO ## _PIN); \
                                          ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:89:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:100:51: note: in expansion of macro 'WRITE'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                                   ^
sketch/src/Marlin.h:242:27: note: in expansion of macro 'OUT_WRITE'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                           ^
sketch/src/Marlin.h:242:37: note: in expansion of macro 'SUICIDE_PIN'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                                     ^
sketch/src/inc/../pins/pins_GT2560_REV_A.h:96:33: error: pasting "/* Must be enabled at startup to keep power flowing*/" and "_WPORT" does not give a valid preprocessing token
 #define SUICIDE_PIN        54   // Must be enabled at startup to keep power flowing
                                 ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:72:30: note: in definition of macro '_WRITE_C'
   uint8_t port_bits = DIO ## IO ## _WPORT;                  /* Get a mask from the current port bits */ \
                              ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:89:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:100:51: note: in expansion of macro 'WRITE'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                                   ^
sketch/src/Marlin.h:242:27: note: in expansion of macro 'OUT_WRITE'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                           ^
sketch/src/Marlin.h:242:37: note: in expansion of macro 'SUICIDE_PIN'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                                     ^
sketch/src/inc/../pins/pins_GT2560_REV_A.h:96:33: error: pasting "/* Must be enabled at startup to keep power flowing*/" and "_RPORT" does not give a valid preprocessing token
 #define SUICIDE_PIN        54   // Must be enabled at startup to keep power flowing
                                 ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:74:10: note: in definition of macro '_WRITE_C'
   DIO ## IO ## _RPORT = port_bits & _BV(DIO ## IO ## _PIN); /* Atomically toggle the output port bits */ \
          ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:89:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:100:51: note: in expansion of macro 'WRITE'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                                   ^
sketch/src/Marlin.h:242:27: note: in expansion of macro 'OUT_WRITE'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                           ^
sketch/src/Marlin.h:242:37: note: in expansion of macro 'SUICIDE_PIN'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                                     ^
sketch/src/inc/../pins/pins_GT2560_REV_A.h:96:33: error: pasting "/* Must be enabled at startup to keep power flowing*/" and "_PIN" does not give a valid preprocessing token
 #define SUICIDE_PIN        54   // Must be enabled at startup to keep power flowing
                                 ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:74:48: note: in definition of macro '_WRITE_C'
   DIO ## IO ## _RPORT = port_bits & _BV(DIO ## IO ## _PIN); /* Atomically toggle the output port bits */ \
                                                ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:89:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^
sketch/src/inc/../HAL/HAL_AVR/fastio_AVR.h:100:51: note: in expansion of macro 'WRITE'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                                   ^
sketch/src/Marlin.h:242:27: note: in expansion of macro 'OUT_WRITE'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                           ^
sketch/src/Marlin.h:242:37: note: in expansion of macro 'SUICIDE_PIN'
   inline void suicide() { OUT_WRITE(SUICIDE_PIN, LOW); }
                                     ^
In file included from sketch/src/module/stepper.h:232:0,
                 from sketch/src/Marlin.cpp:36:
sketch/src/module/stepper_indirection.h:59:26: fatal error: TMCStepper.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

**Comment by Afrobaron** [comment]
I faced the same issue days ago on 1.1.9
You are running IDE 1.8.6 I am guessing.  When the error is produced it will jump to the file and error.

Take the comments from the lines there and move them to a new line. Recompile and it should work.
Looks like the IDE update has some issues at that point in the code previous versions don’t have.

**Comment by pulster** [comment]
Nope, running IDE 1.9.0 (requirement for Marlin 2.0).

**Comment by Afrobaron** [comment]
try moving the comments anyway.  I would bet it might do the trick.

**Comment by pulster** [comment]
You're right, it worked!

Thank you very much!
