### ISSUE TITLE
MKS Sbase v1.3 marlin usb driver

### ISSUE THREAD

**Issue by Thowra** [MarlinFirmware/Marlin#12779]
### Description
I installed Markin 2.0 on the MKS Sbase motherboard (LPC1768).
Windows shows "USB device marlin".
I've tried several drivers, but it doesn't work with one of them.
Operating System: Windows 7.
Which driver is good for it?

![driver](https://user-images.githubusercontent.com/46164261/50564484-7a668180-0d25-11e9-9439-bc56fb2834d0.png)

**Comment by gloomyandy** [comment]
You could try installing the smoothieware driver... https://github.com/MarlinFirmware/Marlin/issues/8618

The board is recognised automatically under Windows 10 (and Linux based systems).

**Comment by Thowra** [comment]
hi,
I tried this driver, but not working.
This link is died
http://marlinfw.org/docs/basics/install_arm.html

**Comment by gloomyandy** [comment]
Did you look at the issue I pointed you at above? That has a link to the smoothieware driver...
http://smoothieware.org/windows-drivers

**Comment by Thowra** [comment]
hi,
I tried this driver but wasn't good.
I reviewed Marlin's library and source code, I find this file.
Tis is good driver.
Problen solved :).

![driver2](https://user-images.githubusercontent.com/46164261/50565690-a8ea5980-0d31-11e9-9be4-1b0d21be99ca.png)

**Comment by gloomyandy** [comment]
If you have solved your problem please be sure to close the issue.
