### ISSUE TITLE
ctc prusa i3 pro b auto level

### ISSUE THREAD

**Issue by cwallyman** [MarlinFirmware/Marlin#12776]
I have ctc prusa I3 clone im having issues adding my auto level in the firmware its a anet auto level sensor need help.

**Comment by Afrobaron** [comment]
https://3dprint.wiki/reprap/anet/a8/improvement/autobedleveling

About half way down it covers the main changes needed for marlin.

**Comment by boelle** [comment]
@cwallyman problem solved?
