### ISSUE TITLE
Frimware MKS gen 1.4

### ISSUE THREAD

**Issue by formu25400** [MarlinFirmware/Marlin#12787]
Hello 
I'm looking for a marlin firmwar 1.1.9
For the mks gen 1.4 with TMC2130
With the connection as shown in the picture
![20190101_153318](https://user-images.githubusercontent.com/36988342/50573816-4d74a600-0ddb-11e9-8172-68c4f1c15b8e.jpg)

**Comment by Ludy87** [comment]
see in your board schematics, where is the pin and change this in your file.

https://ae01.alicdn.com/kf/HTB1STMIKFXXXXc_aXXXq6xXFXXXL/MKS-Gen-V1-4-3D-Printer-Control-Board-Motherboard-of-MEGA2560-RAMPS-1-4-With-USB.jpg

**Comment by formu25400** [comment]
Hehe ok ok I may be looking for the firmware I'm super novice 😊
I don't know which parameter I should touch or not 😊
For now I just found the schematic for the connection

**Comment by Ludy87** [comment]
the sourcecode has tag with its functions.
Even I, with my poor English skills, understood it.

**Comment by boelle** [comment]
@formu25 tried bugfix 2.0?
