### ISSUE TITLE
Thermistor/temperature problem 

### ISSUE THREAD

**Issue by One1Tick** [MarlinFirmware/Marlin#12785]
### Description

Hi and Happy New year!

I am trying desperately to install Marlin (1.1.9) but there is an issue with the thermistors behavior. I tried to find an answer on several facebook groups and on RepRap forum (seehttps://reprap.org/forum/read.php?415,842736) but nobody had this issue therefore I cannot go ahead to find a solution. Maybe it is a bug in Marlin ? I would really appreciated if someone can help me.

I have a Anet A8 which is working properly under A8 stock firmware so I don't think it is a hardware issue or a wrong wiring. 

Problems are :
1. The temp shown for the hot end it too low (9° whilst it is 18° in the room). Temp is fine for the bed.
2. If I warm the bed to 30° it goes up to 30° which is fine but if I warm up the hot endto 200°, the hot end warm which is also ok. BUT the temp shown for the bed increases to 110° without warming the bed above 30°. The bed is still around 30° then decrease a bit because it is not warming anymore dur to the temp shown at 110°.
3. If on the motherboard I connect the bed temp connector to the hot end entry, the temp shown for the hot end (which is in reality the bed) is 27° which is fine...
4. If I flash back the stock firmware on my anet, the 2 temp shown are ok.

I become crazy because I really want to use Marlin for security reasons and to be able to use a bltouch.

Any idea of the issue ? In config.h I have selected 5 et 5 and tried several others but without any success.

Any help will be appreciated. Thanks a lot in advance.

[Conf.h.zip](https://github.com/MarlinFirmware/Marlin/files/2719301/Conf.h.zip)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by ghost** [comment]
**Until I replaced the Anet A8 controller board with a better one, I ran Marlin 1.1.9. Just like you, I defined Motherboard to be ANET A10 etc.etc. and had no problems. So your symptoms are funny, I agree.**
Initially I thought maybe you have a wiring cross-connection somewhere on the sensors. But going to the stock firmware, you say, solves the problem.
Hmmm. 30° and 200° - the 110° would be somewhat like having the two sensors in parallel, averaging the two inputs. But with the stock firmware it does not happen?
A sensor broken? But with the stock firmware it does not happen?
I can understand your dilemma.
I checked the pin definitions for ANET A10 Arduino 1280 and Analog in for HE and BED is 7, 6 - that would be correct. I don't see anything else at the moment.

**Comment by One1Tick** [comment]
FanDjango, thanks for your time! Yes, it is working fine with stock firmware on my Anet A8 (see picture of my current print). I will try to reinstall Marlin 1.1.9 and get more info of the problem.
Thanks again.
![img_0121](https://user-images.githubusercontent.com/35428340/50574310-8d8d5600-0de6-11e9-86b9-b2ea7b5fd70e.jpg)
![octo](https://user-images.githubusercontent.com/35428340/50574311-8d8d5600-0de6-11e9-9f65-d9f8c18d01a6.jpg)

**Comment by RudyBenner** [comment]
Compiles good, code looks right in that section.

I have a feeling you have somehow, by some miracle, wired the two thermistors in series.
That is preposterous, I will admit. Yet much of what you describe supports my hunch.
(Hunches are the subconscious trying to get our attention.)
Trying to come up with a way that could happen. Have to admit I am not getting traction.
The epiphany will strike at an inopportune moment, in traffic.

Sound like a wiring problem. Nominal resistance is 100k ohms @ room temp. NTC
(negative temperature coefficient)
Get someone else to check your wiring, you have a blind spot. Go have a beer or tea.

Would a copy of the schematic be of any help to you? See the attached file.


[ANET3D_Board_Schematic.pdf](https://github.com/MarlinFirmware/Marlin/files/2719458/ANET3D_Board_Schematic.pdf)


rudy

**Comment by RudyBenner** [comment]
**I take back what I said about your config files.** The configuration_adv.h looks screwy. Configuration.h looks like it only had one change.
I suggest starting with the provided example files.
rudy

**Comment by ghost** [comment]
Consider setting the bed thermistor and then the hotend thermistor to one or the other of the "dummy debug" settings, thereby producing fixed values for first the one and the other. Test bed and then hotend separately first. Try to isolate the problem or get a better overview of what is happening in combination with what.
```
 *   998 : Dummy Table that ALWAYS reads 25°C or the temperature defined below.
 *   999 : Dummy Table that ALWAYS reads 100°C or the temperature defined below.
 *
 * :{ '0': "Not used", '1':"100k / 4.7k - EPCOS", '2':"200k / 4.7k - ATC Semitec 204GT-2", '3':"Mendel-parts / 4.7k", '4':"10k !! do not use for a hotend. Bad resolution at high temp. !!", '5':"100K / 4.7k - ATC Semitec 104GT-2 (Used in ParCan & J-Head)", '501':"100K Zonestar (Tronxy X3A)", '6':"100k / 4.7k EPCOS - Not as accurate as Table 1", '7':"100k / 4.7k Honeywell 135-104LAG-J01", '8':"100k / 4.7k 0603 SMD Vishay NTCS0603E3104FXT", '9':"100k / 4.7k GE Sensing AL03006-58.2K-97-G1", '10':"100k / 4.7k RS 198-961", '11':"100k / 4.7k beta 3950 1%", '12':"100k / 4.7k 0603 SMD Vishay NTCS0603E3104FXT (calibrated for Makibox hot bed)", '13':"100k Hisens 3950  1% up to 300°C for hotend 'Simple ONE ' & hotend 'All In ONE'", '20':"PT100 (Ultimainboard V2.x)", '51':"100k / 1k - EPCOS", '52':"200k / 1k - ATC Semitec 204GT-2", '55':"100k / 1k - ATC Semitec 104GT-2 (Used in ParCan & J-Head)", '60':"100k Maker's Tool Works Kapton Bed Thermistor beta=3950", '61':"100k Formbot / Vivedino 3950 350C thermistor 4.7k pullup", '66':"Dyze Design 4.7M High Temperature thermistor", '70':"the 100K thermistor found in the bq Hephestos 2", '71':"100k / 4.7k Honeywell 135-104LAF-J01", '147':"Pt100 / 4.7k", '1047':"Pt1000 / 4.7k", '110':"Pt100 / 1k (non-standard)", '1010':"Pt1000 / 1k (non standard)", '-4':"Thermocouple + AD8495", '-3':"Thermocouple + MAX31855 (only for sensor 0)", '-2':"Thermocouple + MAX6675 (only for sensor 0)", '-1':"Thermocouple + AD595",'998':"Dummy 1", '999':"Dummy 2" }
 */
#define TEMP_SENSOR_0 5 //§§§§ Anet A8 original thermistor
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_4 0
#define TEMP_SENSOR_5 0
#define TEMP_SENSOR_BED 5 //§§§§ Anet A8 original thermistor
#define TEMP_SENSOR_CHAMBER 0

// Dummy thermistor constant temperature readings, for use with 998 and 999
#define DUMMY_THERMISTOR_998_VALUE 25
#define DUMMY_THERMISTOR_999_VALUE 100

```
If you have setup the firmware updater in octoprint, you can compile a change in the marlin firmware and upload to the printer in a jiffy. Gives you upto 10 trial runs with different settings per hour, no need to unplug anything, just click-click.
Also: consider using Bugfix-2.0, that's closer to where the action is right now. I am using it and I prefer it to 1.9.x. I am worried that your pin-definitions are somehow warped, that would be one of the last ideas to consider and using 2.0.x would get you to the current pin/board files. Note though, that I also started off with 1.9.x and did not have this problem, so you can see this is only a shot in the dark.

**Comment by One1Tick** [comment]
> Your configuration.h file looks like only 1 change has been made.
> Your confuguration_adv.h looks like something from hell.
> 
> I suggest you start again, using the example files provided.
> 
> rudy

Thanks Rudy for your funny advices. I prefer beer than tea...
The files I provided are the one from "\Marlin-1.1.x\Marlin\example_configurations\Anet\A8" and as u notice I have made 1 modif in "Configuration.h" and nothing in the other.
Thanks.

**Comment by One1Tick** [comment]
> Consider setting the bed thermistor and then the hotend thermistor to one or the other of the "dummy debug" settings, thereby producing fixed values for first the one and the other. Test bed and then hotend separately first. Try to isolate the problem or get a better overview of what is happening in combination with what.

I am sorry I do not really understand what you mean... could you explain what to do step by step ? Thanks.

**Comment by One1Tick** [comment]
Btw; i also tried with the "Marlin-bugfix-1.1.x" version but nothing better.. I dont know how to try with "Marlin-bugfix-2.0.x" because there are only a coule of files provided and nothing for Anet A8, should I keep all other files from the previous version ?
Thanks again for your time.

**Comment by ghost** [comment]
Ok, stick with 1.9.x right now.
How do you currently compile your firmware (after modifying configuration.h)? arduino IDE 1.8.8?
How do you currently upload a newly compiled firmware to the printer? USB cable from arduino IDE or via octoprint?
So anyhow, do the following:
Set the thermistor values like follows (instead of type "5"):
```
 *   998 : Dummy Table that ALWAYS reads 25°C or the temperature defined below.
 *   999 : Dummy Table that ALWAYS reads 100°C or the temperature defined below.
 *
 * :{ '0': "Not used", '1':"100k / 4.7k - EPCOS", '2':"200k / 4.7k - ATC Semitec 204GT-2", '3':"Mendel-parts / 4.7k", '4':"10k !! do not use for a hotend. Bad resolution at high temp. !!", '5':"100K / 4.7k - ATC Semitec 104GT-2 (Used in ParCan & J-Head)", '501':"100K Zonestar (Tronxy X3A)", '6':"100k / 4.7k EPCOS - Not as accurate as Table 1", '7':"100k / 4.7k Honeywell 135-104LAG-J01", '8':"100k / 4.7k 0603 SMD Vishay NTCS0603E3104FXT", '9':"100k / 4.7k GE Sensing AL03006-58.2K-97-G1", '10':"100k / 4.7k RS 198-961", '11':"100k / 4.7k beta 3950 1%", '12':"100k / 4.7k 0603 SMD Vishay NTCS0603E3104FXT (calibrated for Makibox hot bed)", '13':"100k Hisens 3950  1% up to 300°C for hotend 'Simple ONE ' & hotend 'All In ONE'", '20':"PT100 (Ultimainboard V2.x)", '51':"100k / 1k - EPCOS", '52':"200k / 1k - ATC Semitec 204GT-2", '55':"100k / 1k - ATC Semitec 104GT-2 (Used in ParCan & J-Head)", '60':"100k Maker's Tool Works Kapton Bed Thermistor beta=3950", '61':"100k Formbot / Vivedino 3950 350C thermistor 4.7k pullup", '66':"Dyze Design 4.7M High Temperature thermistor", '70':"the 100K thermistor found in the bq Hephestos 2", '71':"100k / 4.7k Honeywell 135-104LAF-J01", '147':"Pt100 / 4.7k", '1047':"Pt1000 / 4.7k", '110':"Pt100 / 1k (non-standard)", '1010':"Pt1000 / 1k (non standard)", '-4':"Thermocouple + AD8495", '-3':"Thermocouple + MAX31855 (only for sensor 0)", '-2':"Thermocouple + MAX6675 (only for sensor 0)", '-1':"Thermocouple + AD595",'998':"Dummy 1", '999':"Dummy 2" }
 */
#define TEMP_SENSOR_0 999
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_4 0
#define TEMP_SENSOR_5 0
#define TEMP_SENSOR_BED 998
#define TEMP_SENSOR_CHAMBER 0

// Dummy thermistor constant temperature readings, for use with 998 and 999
#define DUMMY_THERMISTOR_998_VALUE 70
#define DUMMY_THERMISTOR_999_VALUE 200
```
Compile, upload and you should see hotend at 200 and bed at 70, it would prove software is ok and need to check wiring and so on.

**Comment by One1Tick** [comment]
Hi, to answer your questions before I was compiling/flashing through Arduino and a USB cable. Now I tried through octoprint (did not know this - very helpfull -> THX) and it is the same...
Tried with 999/998 + 70/200 and I see 200° / 70°, I don't understand... When you say check wiring you mean wiring of the MB? Thanks.

**Comment by ghost** [comment]
Ok, so now we have confirmed your firmware workflow is correct and we can do some checks (remembering: stock firmware ok, marlin not ok). 

It's either a bug in Marlin connected to some special setting in the config files or it is because the Anet A8 that you have got does not correspond to the config files.

So, I have checked your config files against the example configuration for Anet A8. **configuration.h** has only on line changed: the printer name. **configuration_adv.h** has no changes.

Now to do some experiments, here are some things to try: (you will need to search for where these lines are in configuration.h)

How about (I remember that the Anet V1.0 controller supported this):
```
#define PIDTEMPBED
//#define BED_LIMIT_SWITCHING
...
and
...
  #define DEFAULT_bedKp 407.37 //§§§§ my values, you can use them for now
  #define DEFAULT_bedKi 56.51  //§§§§
  #define DEFAULT_bedKd 734.18 //§§§§
```

Can you have a good look at your Anet controller board and check if it says Anet V1.0 on the board? Could it be a much newer version of their controller that Marlin does not know about?

**Comment by One1Tick** [comment]
Thanks again for your help! 
I will try this back at home. Version of the board is ANET3D 1-5. (see picture).

![img_0123](https://user-images.githubusercontent.com/35428340/50592319-ecf56f80-0e93-11e9-980e-62c8b6a16be6.jpg)

Just to be 100% sure, you want me to uncomment this "//#define PIDTEMPBED" (remove the // ) and comment this "#define BED_LIMIT_SWITCHING" (add // ) ? Right?

and put your PID values just a few lines below ?

to be like this : 

//===========================================================================
//============================= PID > Bed Temperature Control ===============
//===========================================================================

/**
 * PID Bed Heating
 *
 * If this option is enabled set PID constants below.
 * If this option is disabled, bang-bang will be used and BED_LIMIT_SWITCHING will enable hysteresis.
 *
 * The PID frequency will be the same as the extruder PWM.
 * If PID_dT is the default, and correct for the hardware/configuration, that means 7.689Hz,
 * which is fine for driving a square wave into a resistive load and does not significantly
 * impact FET heating. This also works fine on a Fotek SSR-10DA Solid State Relay into a 250W
 * heater. If your configuration is significantly different than this and you don't understand
 * the issues involved, don't use bed PID until someone else verifies that your hardware works.
 */
#define PIDTEMPBED

//#define BED_LIMIT_SWITCHING

/**
 * Max Bed Power
 * Applies to all forms of bed control (PID, bang-bang, and bang-bang with hysteresis).
 * When set to any value below 255, enables a form of PWM to the bed that acts like a divider
 * so don't use it unless you are OK with PWM on your bed. (See the comment on enabling PIDTEMPBED)
 */
#define MAX_BED_POWER 255 // limits duty cycle to bed; 255=full current

#if ENABLED(PIDTEMPBED)

  //#define PID_BED_DEBUG // Sends debug data to the serial port.

  //120V 250W silicone heater into 4mm borosilicate (MendelMax 1.5+)
  //from FOPDT model - kp=.39 Tp=405 Tdead=66, Tc set to 79.2, aggressive factor of .15 (vs .1, 1, 10)
  #define DEFAULT_bedKp 407.37
  #define DEFAULT_bedKi 56.51
  #define DEFAULT_bedKd 734.18

  //120V 250W silicone heater into 4mm borosilicate (MendelMax 1.5+)
  //from pidautotune
  //#define DEFAULT_bedKp 97.1
  //#define DEFAULT_bedKi 1.41
  //#define DEFAULT_bedKd 1675.16

  // FIND YOUR OWN: "M303 E-1 C8 S90" to run autotune on the bed at 90 degreesC for 8 cycles.
#endif // PIDTEMPBED

**Comment by ghost** [comment]
AHA! Anet V1-5. Don't do anything yet unless you feel like it. Let's do some research first to see if anyone else is having trouble as with respect to Anet V1.0 ( = "ANET 10" ). My Anet controller is one of the first, it doesnt even have a version. The example configs for ANET A8 are not very new and maybe they have changed something - it is a moving target. It is difficult to imagine what the change could be - have you checked all the other pins functions, is all the movement of all motors working correct and do all the endstops work?
Also, when you compile the marlin in arduino ide, have you set the right board? installed all the updates that arduino suggests? when the compile is finished, how many % of the ram space is used? Have you checked that the compiled code fits?
Can you make a better photo of this area:? 
![grafik](https://user-images.githubusercontent.com/5990805/50593151-78243480-0e97-11e9-8da4-4970e8f418a6.png)

**Comment by ghost** [comment]
Ok, after some surfing I think the board should be pin compatible with the older ones. I am running out of ideas, I am afraid. You need to do some more playing around and testing, like you did in your first post of this issue.

**Comment by One1Tick** [comment]
Better picture below.  2nd picture shows the card selected and the % memory used.

![img_0124](https://user-images.githubusercontent.com/35428340/50593600-401df100-0e99-11e9-841a-597378a73b54.jpg)

![arduino](https://user-images.githubusercontent.com/35428340/50593716-cdf9dc00-0e99-11e9-887e-1d43e53d677f.jpg)

**Comment by ghost** [comment]
Merde. All looks good.

**Comment by One1Tick** [comment]
Yes, shit! Ia it worth to try what you proposed regarding PIDTEMPBED?

**Comment by One1Tick** [comment]
BTW, does a new mb could correct the issue ? Maybe, maybe not...

**Comment by ghost** [comment]
New MB? 

Well, I had the Anet V1.0 MB with BLTouch (I can recommend) and two MOS FETs with Marlin, so on the safe side re. fire hazard and good comfort, automatic bed level on every print -> I can start print without even bothering to look how first level begins 👍 If you set it up really well in Marlin, this works perfect.
Why did I upgrade? Well, adding some more of the features of Marlin, like PAUSE and FILAMENT SENSOR exceeded the program memory of the ANET V1.0 AVR ATMEGA1284P, so I searched for a board using a ATMEGA2560, which has double that.
To what did I upgrade: GEETECH GT2560. Very satisfied up to now. Got PAUSE and FILAMENT sensor now

What's the next step: GT32 Pro soon. Even more features and speed and GT2560 not enough RAM, nearly on the limit for global dynamic variables. **->BEZIER curve accelleration needs CPU **

So, new MB will solve the problem? **I don't think you should give up so soon** but also remember some day you will want a better one. It would be nice to identify what the actual problem is. Depends how much time you have.

The connector for your HotEnd Thermistor: The single crimp terminals cannot be touching something by mistake? (does not explain why the stock firmware works, though).
You wrote: 

> If on the motherboard I connect the bed temp connector to the hot end entry, the temp shown for the hot end (which is in reality the bed) is 27° which is fine...

How about you swap both thermistor plugs. Then heat bed to (example) 30°, then heat hotend to 60°. How does that behave?


Do you have a Multimeter with a fine enough probe to take voltage measurements on the board? In that case I would like the voltages for the HE and the BED wires taken on the outside terminal. 

Re PIDTEMPBED: If you have time. It won't hurt. But I can't believe it would change anything. Or may exaclty that is the difference, hmmm. **Is there anyway in your wiring, that one of the heater connections is influencing one of the thermistor connections?** Before or after the MOSFETs. And depending on PIDTEMPBED Marlin is doing different way of heating. And due to your possible wiring fault, it reacts differently from the stock firmware. Marlin is reading the thermistor value at a different time than stock firmware, maybe.

**Comment by ghost** [comment]
Why double wires to the bed? Safety?
![grafik](https://user-images.githubusercontent.com/5990805/50596256-e242d680-0ea3-11e9-81fb-eb1f694f7677.png)

**Comment by One1Tick** [comment]
I got it like this and most of people I saw on facebook groups have the same.

![img_0126](https://user-images.githubusercontent.com/35428340/50596637-3306ff00-0ea5-11e9-9989-54e283613664.jpg)

**Comment by One1Tick** [comment]
> New MB?
>
> So, new MB will solve the problem? **I don't think you should give up so soon** but also remember some day you will want a better one. It would be nice to identify what the actual problem is. Depends how much time you have.

I have time, meanwhile anet works pretyt well with stock firmware but I would like to use bltouch and features from Marlin + safety reasons.

But I don't know how to solve my issue, I am a geek rather good in IT and electronics but not a pro!

> 
> The connector for your HotEnd Thermistor: The single crimp terminals cannot be touching something by mistake? (does not explain why the stock firmware works, though).
> You wrote:
> 
> > If on the motherboard I connect the bed temp connector to the hot end entry, the temp shown for the hot end (which is in reality the bed) is 27° which is fine...
> 
> How about you swap both thermistor plugs. Then heat bed to (example) 30°, then heat hotend to 60°. How does that behave?
> 
> Do you have a Multimeter with a fine enough probe to take voltage measurements on the board? In that case I would like the voltages for the HE and the BED wires taken on the outside terminal.
> 

I am currently printing something, I will do these tests afterwards and keep you posted.


> Re PIDTEMPBED: If you have time. It won't hurt. But I can't believe it would change anything. Or may exaclty that is the difference, hmmm. **Is there anyway in your wiring, that one of the heater connections is influencing one of the thermistor connections?** Before or after the MOSFETs. And depending on PIDTEMPBED Marlin is doing different way of heating. And due to your possible wiring fault, it reacts differently from the stock firmware. Marlin is reading the thermistor value at a different time than stock firmware, maybe.

I will also try this.

**Comment by ghost** [comment]
👍 Mine has only 4 pins for the bed. They did this, I suppose, to be less of a fire hazard - that connector is one of the first to get hot and burn the house down. I removed it and soldered the wires.

**Comment by One1Tick** [comment]
I read that solder the wires could be hazardous. What's your view?

**Comment by One1Tick** [comment]
Hello, I have tried to swap thermistors at room temp and at 30/60.... at least results are consistents! but strange, a good exercise to train our logical.

![clipboard01](https://user-images.githubusercontent.com/35428340/50651648-4f2d9d80-0f84-11e9-9f3e-4137e9c35ab0.jpg)

**Comment by ghost** [comment]
That table is VERY well done. Now, let's think about what it tells us. Gimme some hours and a beer :-)

**Comment by ghost** [comment]
To help with the thinking:
So we need to look at: (this is by the square cpu chip)
![grafik](https://user-images.githubusercontent.com/5990805/50653851-34125c00-0f8b-11e9-8b95-7390834433d8.png)
the yellow marked pins.
And this is next to the two white connectors:
![grafik](https://user-images.githubusercontent.com/5990805/50653960-8d7a8b00-0f8b-11e9-9821-a978f7374d24.png)

![grafik](https://user-images.githubusercontent.com/5990805/50653994-a97e2c80-0f8b-11e9-8469-294171c94007.png)
And check on the Motherboard:
![grafik](https://user-images.githubusercontent.com/5990805/50654288-a20b5300-0f8c-11e9-83f0-152ad072dfe9.png)
So: What causes that table (with Marlin) and with the stock firmware, you state that the table is "normal" (let's believe that for the moment).
Now beer.

**Comment by ghost** [comment]
There is a Marlin Debug command we should use to interrogate pins directly. Thats M43 and in the firmware you need to enable PINS_DEBUGGING.
```
//#define PINS_DEBUGGING
```
But: Will it tell you analog pins? Please test it - I cannot right now because I have a long print running, just like you before.
What we are looking for, trying to prove/unprove, is that maybe the pins assignements you are using in configuration.h (board setting), Arduino (board setting) are wrong somehow.

**It can't be a fault on the motherboard if the stock firmware works.**

**Unplugging either EXT or BED reflects on the reported temperature, so you would assume that both are being "touched" by the connection** But it is possible for ATMEGA Analog Pins to have cross-talk to an open pin - it would follow (but not exactly, always less than) the connected pin.

**Comment by One1Tick** [comment]
sorry, i do not follow you... what u want me to try/test?

**Comment by ghost** [comment]
Look up M43 in [http://marlinfw.org/docs/gcode/M043.html](url)
But to able to use it, you need to re-compile Marlin by enabling PIN_DEBUGGING in configuration_adv.h and upload. Then in OctoPrint, in the terminal, you can enter M43 etc. etc. Play with it...

**Comment by ghost** [comment]
Hold all your activity for the moment. I think I have found something.
In the source code of Marlin 1.1.x, in pins_ANET_10.h, there are the following lines:
```
#ifndef __AVR_ATmega1284P__
  #error "Oops!  Make sure you have 'Anet V1.0', 'Anet V1.0 (Optiboot)' or 'Sanguino' selected in the 'Tools -> Boards' menu and ATmega1284P selected in 'Tools -> Processor' menu."
#endif

#ifndef BOARD_NAME
  #define BOARD_NAME "Anet"
#endif

...
//
// Temperature Sensors
//
#define TEMP_0_PIN          7   // Analog Input (pin 33 extruder)
#define TEMP_BED_PIN        6   // Analog Input (pin 34 bed)
...
```
temp_0_pin IS 7 (arduino numbering) and temp_bed_pin IS 6, That is correct. But according to the schematic, it is connected to pins 30 and 31. So we need to address that.
Wrong board in Arduino. I am researching right now, but we on the right track.

**Comment by One1Tick** [comment]
ok, i am waiting...

**Comment by FanDjango** [comment]
Ok.
In file **pins_ANET_10.h** you will find
```
//
// Temperature Sensors
//
#define TEMP_0_PIN          7   // Analog Input (pin 33 extruder)
#define TEMP_BED_PIN        6   // Analog Input (pin 34 bed)
```
Please replace that by
```
//
// Temperature Sensors
//
#define TEMP_0_PIN          4   // Analog Input (pin 33 extruder)
#define TEMP_BED_PIN        3   // Analog Input (pin 34 bed)
```
recompile, upload to printer and meanwhile I am switching from beer to bordeaux. If you have good news, there will be a Veuve Cliquot.

**Comment by One1Tick** [comment]
Sorry no veuve-cliquot for time being... but a good boreaux is not so bad!

![img_0129](https://user-images.githubusercontent.com/35428340/50659080-ba369e80-0f9b-11e9-98e1-57be46a694c1.jpg)

**Comment by ghost** [comment]
No, dead end.
I am back to beginning.
Question: All other functions are working in Marlin - Movement of Axes and Endstops?

**Comment by ghost** [comment]
Yeah, I thought I had found something, but it was not logical so I deleted the post.
You got a crazy problem there, you must admit.

**Comment by ghost** [comment]
One interesting little fact came out of it, maybe it helps you find something:
![grafik](https://user-images.githubusercontent.com/5990805/50661043-29af8c80-0fa2-11e9-84dd-132a66d22446.png)

**Comment by One1Tick** [comment]
Hi, to answer your question, yes in Marlin everything else seems to work well ie x/y/z movements and endstops...

**Comment by muc-mac** [comment]
Hi, have you checked the temperature values with Octoprint or Pronterface after flashing Marlin 1.1.9?

**Comment by One1Tick** [comment]
Of course, temps are consistent between octoprint, pronterface and the anet's screen.

**Comment by ghost** [comment]
I have a new Anet A6 (I ordered it as a test bed for my planned new 32 bit controller so to not always disable my "production" printer) that just arrived today. Building it  aleady half finished by now and by tomorrow, ready for testing. It at this moment also has the Anet V1.5 controller board, I will hook it up and try my luck with Marlin. I will update you as soon as I have done that. Maybe I will have the same problem as you, we will see.

**Comment by ghost** [comment]
Ok, the Anet A6 is built and the Anet V1.5 controller is connected with preliminary wiring. It's all hanging loose. Stock Anet V2.0 Firmware, I tested the functions, all ok.
Then I did the following to install Marlin:
I uninstallted Arduino via the Windows 10 Setup/Apps.
I deleted Documents/Arduino/*** completely
I deleted userid/AppData/Local/Arduino15/** completely
Rebooted PC to be totally sure (not needed really but so what)
Fresh install of Arduino
Copy the anet board defs into Documents/arduino/hardware
Start Arduino and check that the Anet V.10 board (not optiboot) can be selected
Next:
Download current bugfix-2.0 Marlin (zip file) from github
Expand the Zipfile
dive into the folder until you get to Marlin/src/config/examples/Anet/A8
copy both config files you find there into Marlin, thereby overwriting the config files originally there (those were the defaults).
I didn't change ANYTHING in the config files for the test.
1st compile failed because u8glib was missing. Went into Arduino library manager, searched for it, installed it and compiled again. No error this time.
Attached USB cable to Printer (got no octoprint on this one). Uploaded, Success - Marlin 2.0 bugfix is on the printer. 
Tested heating and motion: All is well. No problem like yours.

Now you try same.

**Comment by RudyBenner** [comment]
Why not use the example file for A6?

**Comment by ghost** [comment]
Oh, I used A6. He should use A8. He's got an A8. This test-printer of mine is an A6.

**Comment by One1Tick** [comment]
OK let's do it! but in the "Marlin-bugfix-2.0.x" zipfile there are less files than in the other versions, what should I do ?

![image 1](https://user-images.githubusercontent.com/35428340/50726815-787c3400-1112-11e9-909d-2576d2462093.jpg)

**Comment by RudyBenner** [comment]
The same files are there, just in different places. Get used to it.

**Comment by ghost** [comment]
Its all now under /src in many subdirectories. It has been "reorganised" to allow for multiple hardware platforms. You will for example find the pin files under /src/pins 
Just use the marlin.ino as usual after setting up the configuration.h and configuration_adv.h by getting these from the (**watch out**) folder under src/config... as I wrote. NOT from the old examples of the V 1. Marlin. The new example folder is the one where to get them. Your screen shot makes me scared you are getting them on the right from the old one.

**Comment by One1Tick** [comment]
ok, ok, after cmpilation I got this from Arduino... is it a problem?

[log.txt](https://github.com/MarlinFirmware/Marlin/files/2729810/log.txt)

**Comment by ghost** [comment]
No, those warnings are not a problem. But I am sad that you see them because if you do a clean new install of Arduino and have deleted all configuration stuff before install a new clean one, you should not be seeing these compiler warnings. Have you turned them on in the Arduino preferences?
Any way, the compile has succeeded. So do the upload,
Before I compile and upload, by the way, I put a number in the printer name (Like Anet A8-1, Anet A8-2) each time I upload so I know that what I see in the printer is what I think I compiled.

**Comment by One1Tick** [comment]
Cool! My printer is currently printing... therefore I will try the next step (flash) tomorrow morning...

**Comment by ghost** [comment]
I repeat:
**But I am sad that you see them because if you do a clean new install of Arduino and have deleted all configuration stuff before install a new clean one, you should not be seeing these compiler warnings. Have you turned them on in the Arduino preferences?** I didn't get these warnings on my clean install settings.

**Comment by One1Tick** [comment]
No good news this morning, still the same...

1. Heat the hotend at 100°, the bed jump to 85° (without heating).
2. Increase HE to 200°, the bed jump to 110° and stabilize.
3. Decrease HE to 100°, then turn off HE...

![image 2](https://user-images.githubusercontent.com/35428340/50733911-562bfa00-1196-11e9-8cab-52145ce25601.jpg)

**Comment by One1Tick** [comment]
Then I have decided to have a look at the mb to see if there something suspicious but I did not find anything stange except the general low quality of the soldering but for that price I do not think we should expect perfection.

**Comment by ghost** [comment]
1. Does not explain why it works fine with the stock firmware. Really really True? Hmmmm. Otherwise, use new mainboard, if same problem with stock firmware.
2. Really a clean new install of Arduino? Clean Anet example file? Last chance for something to go wrong.

No more ideas here.

**Comment by One1Tick** [comment]
What means the messages received aftere the compilation ?

**Comment by force-e** [comment]
Guys, I had exactly the same issue on my Anet A8, after switching from stock firmware to Skynet: when printing for longer than aprox. 20 minutes my bed temperature would suddenly show very high values and the thermal runaway kicked in. Suspected my thermistor went bad so I did the bed/hotend thermistor swap and the problem persisted. Measured resistances and voltages and everything seemed to be okay.

I read you mentioned the PID tuning but did not read a confirmation that you actually did it. By default the bed PID control is disabled. I gave it a try, enabled bed PID, performed the PID tuning and stored the values and my printer seems to be printing fine now! So before buying a new mainboard, I'd suggest you to give this a try too!

NOTE: I am on Skynet 2.3.2

Be aware that you need to comment out the BED_LIMIT_SWITCHING define or you'll get a conflict error. Use the default PID settings for the bed and then perform autotune to determine the proper settings for your printer. Store them in your configuration.h, reupload and give it a try.

**Comment by One1Tick** [comment]
Thanks for your feedback. I did PID tuning but it hasn't change anythin. By the way I have ordered a RAMPS to replace my stock MB... It is an upgrade I wanted to do anyway.

**Comment by One1Tick** [comment]
Just finished installing a ramps 1.4 on my anet a8 and it is working like a charm...
