### ISSUE TITLE
DELTA_DIAGONAL_ROD doesn't change 

### ISSUE THREAD

**Issue by GrevanGER** [MarlinFirmware/Marlin#12789]
Machine: Anycubic Linear (not the plus, but also not the pully)
Board: Trigorilla 1.4
Marlin Version: 1.1.9

Issues: No matter how often I flash Marlin on to the board and no matter what I enter for DELTA_DIAGONAL_ROD, the value stays at 229mm. 
But since my printers rods are only 217mm long, I am getting dimensional inaccuracy in every print. 

I made sure that the upload itself is actually working, by changing the machines name etc. 
Every seems to be "editable" but the rod length. 

What am I doing wrong?

**Comment by AnHardt** [comment]
Temporarily disable EEPROM - or learn how to use it.

**Comment by GrevanGER** [comment]
Well, at least you pushed me in to the right direction. 
The problem was I did not use M502 after uploading. 

So if someone happens to have the same problem and stumbles over this thread, 
take a look at the discriptions of M500, M502 and M503. That should help.
