### ISSUE TITLE
[sbase] UBL/Bilinear Causes motors to stutter.

### ISSUE THREAD

**Issue by forkoz** [MarlinFirmware/Marlin#12791]
Downloaded the jan 1st commits and decided to give UBL and Bilinear a go, I was using linear for a while.

Made my grid and set it to print. First move to wipe after homing was stuttering all over the place. Motion is no longer smooth at all and everything vibrates.

Did something happen to these recently, I don't remember having this issue. I went back to linear and just like that its gone...

**Comment by forkoz** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2719717/Marlin.zip)

This didn't attach because github hates firefox now.

**Comment by Roxy-3D** [comment]
Did you do a M502 & M500 after turning on UBL/Bi-Linear?   If not...  That would explain the behavior.

**Comment by forkoz** [comment]
Yes, saved and wiped "eeprom". I tried both leveling systems and wiped each time, the Z offset actually reset when I flashed the FW too.

**Comment by boelle** [comment]
@forkoz problem fixed?
