### ISSUE TITLE
Where to enable the Extruder fan

### ISSUE THREAD

**Issue by gharryh** [MarlinFirmware/Marlin#12798]
### Description

Where to enable the Extruder fan

LS,

I have a BIQU KFB2.0 board. There are three places to connect a fan.
5V connector to connect a small fan
one 12V connector and a screw connector, also connect a extruder fan.

Where do I enable the fan on the connector and disable the one on the screw connector.

**Comment by RudyBenner** [comment]
https://github.com/luc-github/ESP3D/wiki/BIQU-KFB2.0

**Comment by boelle** [comment]
a better formulated question would help

you have an extruder fan, do you mean for part cooling while printing or a fan for the coldend heatsink ?

**Comment by boelle** [comment]
@gharryh 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone
