### ISSUE TITLE
[BUG] M30 fails (and missing newline)

### ISSUE THREAD

**Issue by msticninja** [MarlinFirmware/Marlin#12794]
Can't find any other reports of this since 2012, so here goes: M30 fails in marlin 2.0 on Re-arm(an LPC1768-based board), and is missing newline on M30 fail. Serial monitor must be reconnected, and SD card may need to be chkdsk'ed and, if so, will find deleted file as a lost chunk.
May only happen with advanced ok enabled, haven't had time to recompile without it yet.
Looks like maybe it has an extra period after the .gco? Haven't compared to a working output yet.

#### Additional Information

```
Send: M30 /2020ra~1.gco
Recv: Deletion failed, File: 2020ra~1.gco.ok P31 B63
```

[Marlin-conf.zip](https://github.com/MarlinFirmware/Marlin/files/2720266/Marlin-conf.zip)

**Comment by boelle** [comment]
@msticninja problem fixed?

**Comment by msticninja** [comment]
Not for me. I have just stopped using M30, and delete from the FlashAir interface(it is a wifi enabled SDcard). It may be fixed in newer versions, I haven't compiled new FW since January, but I also haven't heard of anybody doing anything to fix the problem, either. I've only seen one other person that encountered the problem, so...

**Comment by boelle** [comment]
same if you use bugfix 2.0?

**Comment by msticninja** [comment]
It is bugfix 2.0. Pretty sure that's the only branch that supports the Re-Arm(LPC1768). I'll probably try the latest github pull soon, but I was hoping to find a fix for NeoPixel on LPC1768 before flashing new firmware.

**Comment by boelle** [comment]
neopixels are not supported yet, they need to make an 32 bit library for it

**Comment by msticninja** [comment]
Yup, that's the fix I'm waiting for to recompile.

**Comment by boelle** [comment]
so they have made a neopixel library?

personally i have looked in to neopixels and re-arm, but also waiting for it

**Comment by msticninja** [comment]
No, apologies for being confusing. Since I don't strictly need M30 to function, I haven't actively tried to fix it. I've been waiting to see if someone can submit a working PR to adafruit's neopixel library to add support for LPC176X. LadyAda already said they'd accept a PR at https://github.com/adafruit/Adafruit_NeoPixel/issues/188, but they don't have the hardware to do it themselves. Until then, I don't have enough reason to compile new firmware, just to see if M30 is fixed.

**Comment by boelle** [comment]
missing label

**Comment by shitcreek** [comment]
Cleaning house. LMK if this issue needs to me reopened.
