### ISSUE TITLE
Configuration.h says Marlin defaults  Z_MIN_PROBE_PIN to Z_MAX_PIN, but that doesn't seem to work.

### ISSUE THREAD

**Issue by sidhant** [MarlinFirmware/Marlin#12792]
Configuration.h says

> (By default Marlin assumes the Z-Max endstop pin.)
>  * To use a custom Z Probe pin, set Z_MIN_PROBE_PIN below.

As such, I proceeded to leave it undefined, assuming that Marlin somewhere defines something on the lines of #define Z_MIN_PROBE_PIN Z_MAX_PIN, however it turns out that pin_RAMPS.h has the following:
`#ifndef Z_MIN_PROBE_PIN`
` #define Z_MIN_PROBE_PIN  32`
`#endif`
Result was my probe not working as it was plugged into Z_MAX_PIN.

In otherwords, I would expect that if configuration says there is a default, that is is defined before pin_RAMPS can detect if it is #undef'd?

**Comment by RudyBenner** [comment]
/**
 * Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
 *
 * Enable this option for a probe connected to the Z Min endstop pin.
 */
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN

this is the default setting

**Comment by RudyBenner** [comment]
Seems like there is a contradiction. 


/**
 * Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
 *
 * Enable this option for a probe connected to the Z Min endstop pin.
 */
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN is the default

**Comment by sidhant** [comment]
@RudyBenner Not sure I understand your comment. I am talking about the Z_MIN_PROBE_ENDSTOP and its behavior. The config comments suggests that Z_MIN_PROBE_ENDSTOP defaults to the Z-max endstop pin, however that is not the case.

**Comment by boelle** [comment]
@sidhant still having issues?

**Comment by sidhant** [comment]
@boelle No, I resolved it with an overriding #undef, however either the comment in the config should reflect the actual behavior better or #define Z_MIN_PROBE_PIN Z_MAX_PIN be defined appropriately. Its a minor annoyance however the statement that 

> (By default Marlin assumes the Z-Max endstop pin.)

is false.

**Comment by boelle** [comment]
maybe click the green close button

**Comment by sidhant** [comment]
Oops, sorry :-) Thank you for the reminder.

**Comment by sidhant** [comment]
On second thought.. you do realize that the core issue with the firmware remains unresolved? My workaround resolved *my* issue.

**Comment by boelle** [comment]
if others have the issue they will say it here then :-D

**Comment by boelle** [comment]
even if issue is closed

**Comment by thinkyhead** [comment]
Configuration of Z probes has been modified, along with commentary.

**Comment by volconst** [comment]
I was having the same issue - documentation is wrong for boards using pins_RAMPS.h. Why pin 32 is the default there?
