### ISSUE TITLE
[BUG] Filament change doesn't work on 2nd Extruder (E1)

### ISSUE THREAD

**Issue by Le-zOU** [MarlinFirmware/Marlin#12793]
### Steps to Reproduce

On Geeetech A20M, the unload filament option in LCD, works just fine for E0, but has no effect when choosing E1.

**Expected behavior:** unloads filament on E1

**Actual behavior:** nothing

#### Additional Information
configuration.h and adv_configuration.h
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2720121/Marlin.zip)

**Comment by Le-zOU** [comment]
[pause.zip](https://github.com/MarlinFirmware/Marlin/files/2720299/pause.zip)
pause.cpp file for information as the code is in there.
I'll have a look myself later

**Comment by boelle** [comment]
maybe make the title say: [Bugfix 2.0][BUG] Advance pause doesn't work on 2nd Extruder (E1)

**Comment by boelle** [comment]
@Le-zOU still a problem?

**Comment by boelle** [comment]
@Le-zOU did you have a look?

**Comment by Le-zOU** [comment]
sorry @boelle , have a look at what ?
I'm about 1 week behind current version/commits. I plan to flash on monday probably with latest commits at this point

**Comment by boelle** [comment]
have a look at what you said 2/1-2019, a little over 2 months ago

**Comment by Le-zOU** [comment]
Oh yeah I had a look but we'll didn't find anything although I'm not a developer :p

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by boelle** [comment]
@Le-zOU  does it work on 2nd extruder now?

**Comment by Le-zOU** [comment]
I'll have to check and probably update the FW on my printer, it's been a while I haven't used it. I was fighting other issues and gave up for other projects (restoring a 1966 Ford Mustang)

**Comment by boelle** [comment]
restoring the mustang gets a thumbs up from me 👍 
i think we can wait a bit more

**Comment by shitcreek** [comment]
Tested with latest build on A20M and it works flawlessly.
LMK if it's still an issue for you and thread needs to be reopened.

**Comment by Le-zOU** [comment]
Can you define "latest" ?
Thank you.
I've yet to take care of my A20M, but I'm glad it seems solved.

**Comment by shitcreek** [comment]
A build from 2 days ago, so technically not the latest but I don't think any changes has been made to the relevant codes.

**Comment by Le-zOU** [comment]
Just FYI, it works fine on a built that I use and is several month old. so keep it closed. (I finally got round to fix my A20M)
