### ISSUE TITLE
Changing the Z min probe's offset from the extruder in configuration.h has no effect on bilinear leveling

### ISSUE THREAD

**Issue by PeterDessev** [MarlinFirmware/Marlin#12807]
I have tried everything to get bilinear leveling to work on my Anycubic Kossel. My issue is that I have a button z minimum probe that is not on the nozzle, but no matter what I do the printer always levels as if the probe is on the nozzle. I have measured the offset from the nozzle in the x, y and z direction and put them all into the z-probe section of configuration.h but when I go to auto-level under prepare/delta calibration the probe offset values have no effect and it levels from the nozzle, not the probe.
Many other things related to bilinear calibration also have no effect such as MIN_PROBE_EDGE. I suspect I am not uploading the firmware properly, but on the official marlin page, it says that you can just press upload on the Arduino IDE and your good. Any ideas?
I am using marlin 1.1.9 and the leveling works, it is just not leveling in the middle and when it goes to the edges to level the probe goes over the edge of the build plate and then the leveling fails.

**Comment by Roxy-3D** [comment]
> I have tried everything to get bilinear leveling to work...

Have you tried making the changes in Configuration.h, compiling, uploading, and then doing a M502 and M500 ?

**Comment by boelle** [comment]
@SnowCheetah did @Roxy-3D suggestion help you?

**Comment by PeterDessev** [comment]
Unfortunately, it did not. I also went through both configurations again to make sure I hadn't messed something up, but it was all fine.

**Comment by boelle** [comment]
have you send the M502 and then M500?

a common thing is that eeprom stores settings and even thou you change them in firmware marlin will read from eeprom and not matter how much you change the firmware it will still read them from eeprom

**Comment by PeterDessev** [comment]
Yes. I did this several times using pronterface and the same thing happened.

**Comment by boelle** [comment]
maybe attach your 2 config files as a zip file, i will not have time to look over it today but maybe others can beat me to it

i have an extruder to take apart clean and reassemble (old extruder mount cracked)

**Comment by PeterDessev** [comment]
[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/2731119/Configurations.zip)
These are the two configuration files I am using. Hopefully, they will be of use.

**Comment by LVD-AC** [comment]
> when I go to **auto-level** under prepare/delta calibration 

?????
Bilinear leveling isn't available under the delta calibration lcd menu. You must have a really weird version of Marlin.

**Comment by boelle** [comment]
that raises one question:

where was marlin downloaded from? if the answer is that its the copy that came with the printer we have no way of being sure what you have. the printer manufacture could have done a ton of things to the code

download from here instead: https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

click the green botton and choose to download
next extract the zip file and compare your config to the ones you have so you can move over settings correctly, winmerge is a great app to compare files with and allows you to edit at the same time

**Comment by PeterDessev** [comment]
I downloaded marlin from the official github, and decided the first time around to use DaHai's anycubic configurations but then made my own. As for the bilinear part under the actual menu its just called auto calibration but I have bilinear calibration selected in the configurations

**Comment by LVD-AC** [comment]
**"Bilinear calibration"** does not exist in the configurations. You can have AUTO_BED_LEVELING_BILINEAR (G29) in the bed leveling section and DELTA_AUTO_CALIBRATION (G33) in de delta settings section of Config.h; two completely different things. I suggest you do some reading up to understand the difference between bed leveling (tilting and adjusting the bed) and calibration (setting the end-stops, delta height, delta radius and tower angles correctly). Things like X- and Y_PROBE_OFFSET_FROM_EXTRUDER, MIN_PROBE_EDGE,... are not used by DELTA_AUTO_CALIBRATION; that would mess things up. For delta calibration you should set DELTA_CALIBRATION_RADIUS to keep the circular probe mesh on the bed. **"Bilinear circles"** you've invented a new mathematical shape here :smile: hence the confusion. Bed leveling uses a rectangular probe mesh so those can be linear, bilinear,... and other settings apply depending on the case.

**Comment by PeterDessev** [comment]
Oh, ok. Thank you for the response. I'll check it out.
