### ISSUE TITLE
[bug] On Power Loss Recovery print starts over

### ISSUE THREAD

**Issue by TB1405** [MarlinFirmware/Marlin#12809]
hi 
the printer simply restarts the gcode. 
He also wants to home the z axis and will do AUTO_BED_LEVELING_LINEAR. 
no new file will be created on the SD card

**Comment by boelle** [comment]
attach your 2 config files as a zip file

**Comment by TB1405** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2730488/Configuration.zip)

**Comment by boelle** [comment]
@TB1405 and this is still a problem in bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by TB1405** [comment]
Problem is not sloved in actual bugfixes. Sorry i had a error with my Auto and was struggling with my printer. 
I have postet a Video in the marlin Facebook group

**Comment by maxlinux2000** [comment]
I think we can close this bug. Now the power loss, resume perfectly, but there is another problem,

please see: https://github.com/MarlinFirmware/Marlin/issues/13541

**Comment by robbycandra** [comment]
The problem fixed in bugfix 2.0.
Print start over happened if you use cura as slicer and power failure happened at Z less than 15mm.
To fix this. Delete G1 Z15 at line 11 of your gcode files.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
