### ISSUE TITLE
[2.0.x] STM32F1 hangs during initialization

### ISSUE THREAD

**Issue by jmz52** [MarlinFirmware/Marlin#12816]
### Description

STM32F103ZET6 (HAL_STM32F1) board hangs during initialization.

### Steps to Reproduce

1. Build Marlin-2.0.x with HAL_STM32F1
2. Flash Marlin firmware
3. Boot

**Expected behavior:**
Marlin works

**Actual behavior:**
Marlin hangs with no LCD screen and following text on COM port
`echo:Tool-changing:`
`echo: Z2.00`
`Er` - just two letters, no mistake here

#### Additional Information
Problem's root cause is https://github.com/MarlinFirmware/Marlin/pull/12753
Restoring line #include "../../inc/MarlinConfig.h" in watchdog_STM32F1.h solves the problem.

Code change in mentioned pull request also increases firmware size, so I suggest to revert the change.

**Comment by boelle** [comment]
@jmz52 problem fixed?
