### ISSUE TITLE
[Question] Marlin reboot

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#12815]
I saw that every time repetier connects to printer, marlin reboot. I'm wondering how repetier can do such operation. Is there a M code to do that?

**Comment by jmz52** [comment]
For arduino board this is a built-in feature - to reset when serial connection is established.
http://playground.arduino.cc/Main/DisablingAutoResetOnSerialConnection

**Comment by AnHardt** [comment]
For example a [Arduino (Mega](https://store.arduino.cc/arduino-mega-2560-rev3)) (Documentation/Automatic (Software) Reset)
Most other boards having a usb-chip have similar mechanisms.

**Comment by GMagician** [comment]
@jmz52 and @AnHardt thanks for quick response, now it's clear
