### ISSUE TITLE
[FR] TMC: Implement configurable homing current

### ISSUE THREAD

**Issue by comps** [MarlinFirmware/Marlin#12828]
On a cartesian machine, when homing Z with traditional limit switches or inductive/capacitative/etc. probes, the homing method can sometimes fail - the switch gets loose, the probe doesn't trigger, etc.
At the same time, the current required moving the X gantry downwards on a leadscrew is usually significantly lower (as far as I tried) than lifting the assembly up, especially on higher pitch like 8mm (prusa i3).

This means that we could likely reduce the current when moving towards an unknown limit, avoiding a potentially destructive situation (glass bed breaking, etc.).

Maybe this feature could be somehow combined with `CALIBRATION_CURRENT`, and/or also applied to X/Y homing as well, which (if homing slowly and with low acceleration) would also benefit from lower current than is needed for fast printing moves (direction changes), without limiting the feature to `SENSORLESS_HOMING`.

The icing on the cake would be stopping the machine / reporting the error, since (without `SENSORLESS_HOMING`), there should be no expected lost steps during homing and such condition may indicate a failed homing switch/probe, a debris-blocked leadscrew/ballscrew, etc.

**Comment by mtowara** [comment]
I agree that this would be a neat feature to have, however for the meantime you could also put that into your startup GCODE and reset the currents after homing.

**Comment by comps** [comment]
This is not exactly true with `Z_HOME_BUMP_MM` - the axis needs to move up for the bump and if the current specified is enough to move the axis up, then it might as well be the statically-set current for Z, thus negating the usefulness of this issue/feature.
The reduced current would need to be applied only for any "downwards" moves during homing.

**Comment by AnHardt** [comment]
When homing to MIN! Else the other way around.

**Comment by comps** [comment]
(Yes, it would be useful only in certain cases and not always when homing "down" or "towards MIN", ie. an Ultimaker-style machine where the bed moves upwards when homing to MIN couldn't use it unless it homed downwards to MAX. So the direction/use would need to be configurable.)

I was considering closing this as the scenario where such a feature would be useful is pretty narrow, but then again - the vast majority of printers running Marlin are likely those i3-style ones that would benefit from it, even if few of them use TMC drivers.

**Comment by boelle** [comment]
@comps could you add [FR] in title to it becomes: [FR] TMC: Implement configurable homing current

**Comment by boelle** [comment]
missing label
