### ISSUE TITLE
Delta calibration w/BLTOUCH: wierd jerky Z-probes after a first clean iteration

### ISSUE THREAD

**Issue by gtrevi** [MarlinFirmware/Marlin#12825]
SETUP:
I have an Anybubic Kossel Delta Linear plus, w/Trigorilla board and Marlin v1.1.9 .

ISSUE:
When performing a Delta Auto Calibration with my (original) BLTOUCH, after a first "clean" probing iteration, the subsequent probings are done with 10mm (roughly) “double-jerks” the Z height before performing the probe, and a resulting Z-Height that is 10mm less than the actual.

Facts: 
-	This behavior is consistent and repeatable at each printer reset.
-	If the printer is not reset, then a subsequent 2nd autocalibration will perform the wired Z-move probing right from the 1st iteration (instead of happening from the 2nd itaration).
 
I uploaded a video capturing the 1st & 2nd iteration after a printer reset: https://youtu.be/dQh8bF0jLqo

Does anyone have an idea on what could be the problem?

Many thanks for any help.

**Comment by boelle** [comment]
that looks normal, it probes the same spot twice. If i remember correct that is the default

i dont have a delta but i probe the same spot 4 times and marlin figures an avg value, i do it this way to even out tolerance issues

maybe it would help if you attached your 2 config files as a zip file

**Comment by gtrevi** [comment]
Yes, the double-probing is indeed normal (and as configured in the MULTIPLE_PROBING pre-processor def)... it's the double-jerk (happening between the probes, and not in the initial first iteration) that is absolutely *not* normal… otherwise why the first iteration behaves differently? 
Please see carefully the video to notice the different behavior between the two iterations.
Also, this was not happening some time ago when I was using a bulky "3D touch" clone.

I attached my two configs, hope they could help shading some light on this phenome.

Thanks!
[Marlin 1.1.9 configs.zip](https://github.com/MarlinFirmware/Marlin/files/2730776/Marlin.1.1.9.configs.zip)

**Comment by boelle** [comment]
@gtrevi problem fixed?

**Comment by gtrevi** [comment]
> @gtrevi problem fixed?

Unfortunately not: I kept experiencing the problem despite several tweaks... now on a Duet2 WiFi, which solved all at once.

**Comment by boelle** [comment]
tried bugfix 2.0?

**Comment by gtrevi** [comment]
> tried bugfix 2.0?

Yes, was using 2.0, fully compiled w/VS Code
