### ISSUE TITLE
[Bugfix 2.0 + Re-Arm] Odd flashing lines

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#12826]
so i got the re-arm setup complete and doing my first print with it (frame to hold it to printer)

i noticed that the lcd has some very strange flashinh lines on the display that was not there before

a 10 sec video of it: https://www.youtube.com/watch?v=uIjn_hgOQ9A

config files attached, the only odd change i had to do was adding a extra part cooling fan in the pins file so that one is included. i had to do that to be able to control an extra big fan i have that cools of the bed after print, without this change that fan would be on all the time
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2729554/Configuration.zip)

**Comment by boelle** [comment]
side Q: is my config correct in regards that eeprom is saved to a file or where it is saved as the re-arm should not have an eeprom, the commands work, i'm just unsure as i have not seen any files on the sd card other than the firmware

**Comment by gloomyandy** [comment]
On the Re-Arm and other LPC176x based boards eeprom is emulated (by default)  using flash memory pages. 

Do you still get the flashing lines if you do not have the extra fan defined?

**Comment by boelle** [comment]
will have to test that, but its kind of painfull to live without the fan as the wait time after print gets longer before the PEI release its hold on the print,

1 hour left of print before i can experiment :-/

i use one of these on the servo connector for the extra fan, it can drive 2 fans so one is defined as coldend heatsink fan that comes on if hotend is above 50C, the other is for cooling of the bed after print is done

http://www.geeetech.com/wiki/index.php/Reprap_Ramps1.4_RRD_Fan_Extender

i found out that pins not defined is always on, hence i defined this extra fan. with the mega2560 it was not needed and i could simply control the fan with M42 P11 S255 and M42 P11 S0

it will be very odd if defining extra fans in the pins file would have an effect on the display, but time will tell

**Comment by boelle** [comment]
same without that extra fan defined, but since its just a cosmetic thing i can live with it
maybe @thinkyhead knows what it could be and fix it at some point

**Comment by p3p** [comment]
It's unavoidable with an SD print from the controllers sd card, the displays do not adhere to the spi standard and listen to things they shouldn't on the shared bus (how the board is designed), If you are using the slot on the board (or a serial host) it shouldn't happen.

**Comment by boelle** [comment]
well using the onboard slot is a pain to get to since wires to the ramps board pass close to it
serial host is not an option either since its in another room and i have tried to print from octoprint and that gave worse print quality than from sd

but now i know why is happens and as said before its just cosmetic

**Comment by boelle** [comment]
btw... i closed the "issue" as there is nothing that can be done about it and i dont want to take up more issue footprint than need be

but i want to upgrade my 2 month old firmware and a new feature to me at least is junction deviation, are there any guides on how to use that?
