### ISSUE TITLE
[Q] Sensorlesshoming with two endstops

### ISSUE THREAD

**Issue by Ludy87** [MarlinFirmware/Marlin#12832]
Is it possible to trigger two z limit switches by sensorlesshoming?

**Comment by thinkyhead** [comment]
Wire the endstops together…?

**Comment by thinkyhead** [comment]
So, do you mean… When Z sensorless homing triggers, have both faux Z and Z2 endstops get set?

**Comment by Ludy87** [comment]
If steps are lost, the Z-axis alignment will be wrong.

My idea is to calibrate two stops for Z and <del>Z1</del> Z2 around the axis. When Z is triggered, <del>Z1</del> Z2 is also stopped by default. Or am I wrong?

**Comment by boelle** [comment]
@thinkyhead I think he means that he wants sensorless homing with dual z stepper drivers and dual z endstops

**Comment by boelle** [comment]
@Ludy87 i have dual z stepper drivers and dual z endstops on  mendel90, the Mendel90 is a bit different in that it homes to max (up)

when i home the 2 z steppers are sync'ed autoamtic, i imagine that goes sensor less is no problem

it might be a problem on systems where the load on the steppers gets less when homing, in my case the load on the steppers will get higher 

EDIT: i use normal mechanical endstops, not sensorless homing

**Comment by Ludy87** [comment]
@boelle 
I also use mechanical endstops at the moment. I have two Z motors with TMC2130 drivers, sensorlesshoming and I would like to use that.

**Comment by boelle** [comment]
just as i figured, i dont know how to do this, but maybe  just connect stepper driver Z endstop output to Zmin or Zmax.. then connect output from Z2 stepper driver to the correct pin i think default is Xmax

but i'm sure @thinkyhead will pop in and confirm

**Comment by kAdonis** [comment]
@Ludy87  I assume your printer uses leadscrews?
You need a lot of force to stop a leadscrew, did you try sensorless homing in z before?
You may not achieve a repeatable z- home position 
Be sure your Printer is rigid enough for this

**Comment by boelle** [comment]
@kAdonis he wants to do dual z stepper driver and dual Z endstop, but with sensorless homing instead of normal endswitch

**Comment by kAdonis** [comment]
Yes, I understand this
But I am concerned sensorless homing does not work at all with leadscrews

**Comment by boelle** [comment]
depends if load on motor gets higher or lower when homing :-D

**Comment by kAdonis** [comment]
depends on thread lead and pitch, friction, load on the Bed...

**Comment by Ludy87** [comment]
@kAdonis 
> I assume your printer uses leadscrews?

Yes

> You need a lot of force to stop a leadscrew, did you try sensorless homing in z before?

yes, with one Endstop trigger from TMC worked.

**Comment by boelle** [comment]
@kAdonis and if you home up or down :-D

**Comment by boelle** [comment]
if homing towards the bed gives less load on the motor homing up might give more load so that the stepper can detect it and hence it should work

but since it it works with one stepper all he would have to do is to connect the other stepper driver to the endstop pins

**Comment by kAdonis** [comment]
> yes, with one Endstop trigger from TMC worked

I never dared to try

>  but since it it works with one stepper all he would have to do is to connect the other stepper driver to the endstop pins

yes, I agree
Im curious, if its reliable
@Ludy87 please post your findings here

**Comment by boelle** [comment]
me interested too as i plan on getting the tmc2130's maybe at end of this month or next month.
my printer is running 24V for the steppers allready so i would just have to make up the spi/cs wireharrness and connect them to the endstop pins, 

the bigger advantage is that if it works i could get rid of the inductive probe and just use the nozzle

and the even bigger benefit would be that the probing can be done with the nozzle hot and ready, with the pinda probe it has to be done cold as they are sensitive to heat

**Comment by Ludy87** [comment]
No way the dual endstop works with TMC.
Maybe someone will have an idea or a patch later.

One endstop with TMC - OK.
