### ISSUE TITLE
Error while compiling marlin.ino on arduino

### ISSUE THREAD

**Issue by The3rdDimension** [MarlinFirmware/Marlin#12844]
**_i am trying to upgrade my creality cr-10s firmware to the new marlin 1.1.9 and while compiling the file on arduino after making the necessary changes i get an error_**

```
In file included from sketch\MarlinConfig.h:27:0,

                 from sketch\power_loss_recovery.cpp:27:

macros.h:164:57: error: operator '&&' has no right operand

 #define PIN_EXISTS(PN) (defined(PN ##_PIN) && PN ##_PIN >= 0)

                                                         ^

sketch\power_loss_recovery.cpp:209:11: note: in expansion of macro 'PIN_EXISTS'

       #if PIN_EXISTS(POWER_LOSS)

           ^

macros.h:164:57: error: operator '&&' has no right operand

 #define PIN_EXISTS(PN) (defined(PN ##_PIN) && PN ##_PIN >= 0)

                                                         ^

sketch\power_loss_recovery.cpp:278:9: note: in expansion of macro 'PIN_EXISTS'

     #if PIN_EXISTS(POWER_LOSS)

         ^

exit status 1
operator '&&' has no right operand
```
**Apologies if i havent posted properly as this is my first time**

**Comment by rmoravcik** [comment]
I tried to compile Marlin 1.1.9 using CR-10S configuration using Arduino 1.8.5 and 1.8.8 and it succeed.

What version of Arduino are you using?

**Comment by swilkens** [comment]
It seems some of your modifications have broken your copy of the firmware. Can you please zip your `configuration.h` and `configuration_adv.h` files and post them here?

**Comment by boelle** [comment]
@The3rdDimension problem fixed?
