### ISSUE TITLE
TMC 2208 UART Support on LPC1768/9

### ISSUE THREAD

**Issue by GriffinPaquette** [MarlinFirmware/Marlin#12854]
I have been working on a custom control board that makes use of TMC2208 drivers in UART mode. The main controller is a LPC1769, but I have not been able to get UART support to work. Initially, I had the drivers connected to port 1 which is not interrupt capable, but I transitioned one driver to P2.8 as TX (through the 1k shown below) and P2.13. As there is still an open issue similar to this, I wanted to make light that the situation is still present (older issue: https://github.com/MarlinFirmware/Marlin/issues/11853)

It seems that even still, I get no RX value when pinging M122:
```
  X	Y	Z	E
Enabled	false	false	false	false
Set current	200	800	800	800
RMS current	331	1436	1436	1436
MAX current	467	2025	2025	2025
Run current	5/31	25/31	25/31	25/31
Hold current	2/31	12/31	12/31	12/31
CS actual	0/31	0/31	0/31	0/31
PWM scale	0	0	0	0
vsense	0=.325	0=.325	0=.325	0=.325
stealthChop	false	false	false	false
msteps	256	256	256	256
tstep	0	0	0	0
pwm
threshold	0	0	0	0
[mm/s]	-	-	-	-
OT prewarn	false	false	false	false
off time	0	0	0	0
blank time	16	16	16	16
hysteresis
-end	-3	-3	-3	-3
-start	1	1	1	1
Stallguard thrs
DRVSTATUS	X	Y	Z	E
stst
olb
ola
s2gb
s2ga
otpw
ot
157C
150C
143C
120C
s2vsa
s2vsb
Driver registers:
X	0x00:00:00:00	Bad response!
Y	0x00:00:00:00	Bad response!
Z	0x00:00:00:00	Bad response!
E	0x00:00:00:00	Bad response!
Testing X connection... Error: All LOW
Testing Y connection... Error: All LOW
Testing Z connection... Error: All LOW
Testing E connection... Error: All LOW
```

Attached is a photo of my hardware connection to the driver. It matches what Watterott uses on their stepsticks.
![uart setup](https://user-images.githubusercontent.com/40618704/50801293-0f332700-12b2-11e9-9ae2-ff9e8243e421.PNG)

R29 is the 1k for TX and R27 is the 20k pulldown on PDN_UART

**Comment by teemuatlut** [comment]
The TMC2208 support on LPC may require some development time. Not yet sure when I want to tackle the issue and I know @p3p is quite busy these days as well.

**Comment by GriffinPaquette** [comment]
@teemuatlut I appreciate the comment. I would love to help aid in the effort. I can provide you with a board to test with once our last round prototyes come back if it could help you out?

We really want to ditch using a digipot and use full UART instead so anything that we can do to help with the integration would be excellent to know.

**Comment by teemuatlut** [comment]
Thank you for the offer but I think I can manage with the Re-Arm and the Azteeg board.
The way that I would start debugging this is first establish what valid UART communication looks like with AVR by using a logic analyzer. From there I could compare with what the LPC outputs and go from there.
It's entirely possible that the SW serial implementation for LPC doesn't actually work at all yet but p3p hasn't gotten around to rewriting it.

**Comment by GriffinPaquette** [comment]
Makes sense. I will break out my TX and RX pins and try the same just as a second reference. My guess is that the entire support might just not be there yet.

For clarification (sorry I am not a software guy) does @p3p handle the transmission to and from the MCU and your TMC libraries are effectively the universal component that all MCU’s use to communicate with the drivers?

**Comment by p3p** [comment]
I maintain the LPC176x framework that allows Marlin to run on the LPC176x MCUs, the Software Serial library that will let you use Serial on any pins, not just those with hardware UART support, is part of that. 

As far as I know the Software Serial library in the framework should work (at least for one port), but it wasn't written by me so I will need to find time to go over it and check,

**Comment by boelle** [comment]
@griffin-117 problem solved?
