### ISSUE TITLE
Problem with Z-axis after update Marlin

### ISSUE THREAD

**Issue by Gertclaes** [MarlinFirmware/Marlin#12857]
Hey Guys!
Newbie here!

I have an Anet A8 printer, which I upgraded several times on the hardware-matter.
Now I have a problem:
I needed to do some changes on Marlin, and I downloaded the most recent version. I've made the neccessary changes, and uploaded it to the ramps-board, and then the trouble started...

The z-axis isn't doing what he is supposed to do! When I wanna drop it a mm, it falls down 10 mm, going up->same problem...

Tried a different motor, stepper, megaboard, ramps (yes, I know, during the last years, I've collected some spareparts :-))....nothing helped and everything stays the same....even downgrading marlin didn't help..
Anybody have knowledge of this problem?
Thanks!

Gert

Have you read Marlin's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/code_of_conduct.md

Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use the Marlin Firmware forum at http://forums.reprap.org/list.php?415 or the Marlin Facebook Group https://www.facebook.com/groups/1049718498464482/.

Before filing an issue be sure to test the 1.1 and/or 2.0 "bugfix" branches to see whether the issue is already addressed.

-->

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by Glod76** [comment]
have you updated your steps for the z?

**Comment by Gertclaes** [comment]
well, when installing the new Marlin, I've made some changes, but nothing else like I did before...

After some searching on the internet, I found someone with the same problem. And they offered him a solution...
They claimed it was because of the stuff that was written on the eeprom! So you had to clear the eeprom first (M502) and then write the new parameters on it (M500)...and that's where I got struck...
As I told before, I'm a newbie and don't know how to do that....

**Comment by ghost** [comment]
I am not saying that the M502, M500 sequence will actually help you but it might be. Here's how to do it: You need to connect to the printer via a serial terminal and type in the GCODE commands M502 followed by M500 OR (better) use the terminal function to do the same in OctoPrint (or whatever interface to the printer you might be using) OR (last resort) put M502 and M500 in two lines of a file and print that, thereby sending these two commands to the printer. 
It really depends on what your setup looks like and what you have available - you didn't say much in your problem description.

**Comment by Gertclaes** [comment]
Thanks for the reply and the advice! I've tried to send the two commands and as you predicted....it didn't work, but now I know how to send commando's, so it wasn't a complete waste of time :-)
I did some looking into the problem again, and I noticed that the z-axis was moving 10 mm when I asked for 1 mm, I asked for 0.1mm and I got 1mm...I guess that's where the problem is! Now I'm gonna try to figure out how I can fix that! Any suggestions are welcome! 👍

**Comment by GMagician** [comment]
it seems your DEFAULT_AXIS_STEPS_PER_UNIT are 1/10 of what they should be

**Comment by Gertclaes** [comment]
it says 80, 80, 4000, 500
Aren't that kind of normal numbers?

**Comment by GMagician** [comment]
Depends on HW. I don't know Anet A8 but for a 1.8° stepper with 200 steps per round, 16 microsteps and 8mm pitch screw then 200*16/8 should be 400, not 4000

edit: you may look at https://www.prusaprinters.org/calculator/

**Comment by Gertclaes** [comment]
gonna change it and give it a try ! I'll keep you posted!

**Comment by Gertclaes** [comment]
it didn't change a thing...
Ok, maybe a silly question, but do I have to reset it one way or another after I uploaded the new parameters?

**Comment by GMagician** [comment]
Every time you change a .h parameter that is saved to eeprom you need to execute M502 and M500 to properly use it. Otherwise you will use the stored value

**Comment by Gertclaes** [comment]
Hey guys....
Believe it or not....it worked!!!!!
You can't believe how happy I am with this!! It took me three days, trying everything and you guys did it with a few messages!!
Whenever you are in Antwerp, give me a message and I'll buy you a beer! Or two, three,....

Thanks again!!!

Gert

**Comment by swilkens** [comment]
If your problem has been solved, don't forget to close the issue report :) 

(There is a button to do so at the bottom of the page "comment and close")

**Comment by Gertclaes** [comment]
Sorry for that :-)
