### ISSUE TITLE
X and Y homing issues

### ISSUE THREAD

**Issue by geakg-gone-wild** [MarlinFirmware/Marlin#12852]
I get a "error: printer halted. (kill() called!" Any time I home my machine with X or Y axis. I have just installed a 3D touch auto bed level sensor, ironically it works fine. I was using Sprinter firmware but it dosnt support auto bed level, so thus im stuck using marlin. I used the latest version of marlin and as it did years ago and it gave me nothing but issues, printer wouldnt move or home at all. I used the marlin 1.1x bug fix addition and now every thing is working correctly except X and Y homing cause the machine to throw out the "error: printer halted. (kill() called!" on Repetier Host

When I use the M119 command all Endstops show as open unless triggered, the endstops are working correctly. When I home the X and or Y it will do as it should and stop when it hits the endstop but thats when the errors pop up and the printer freezes/ no longer to give commands with out disconnecting and reconnecting to the printer again.

If I home my Z axis it will deploy the probe and come down and touch the bed 2x and no error code and I can still manually move the printer around with the program movements after homing z axis. I'm not sure what would cause this to happen only on X and Y but any help would be appreciated I am at my whits end. 

I use repeiter host but i downloaded printerrun jsut to see what would happen and it had the exact same effect/ errors.
[upload files marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2734224/upload.files.marlin.zip)

**Comment by geakg-gone-wild** [comment]
I tried the marlin bugfix 2.0 and it also has the same results.

**Comment by shitcreek** [comment]
Please provide more information: what printer/board are you using?

**Comment by geakg-gone-wild** [comment]
I am using ramps 1.4 board

I have tried all the variations of marlin that are on their website for download and none of them work correctly for me. both bug fixes work perfect except for the homing issue were it causes the printer to stop responding when X or Y is homed. I dont know if there is some sort of "check homing" setting that could be causing this?

I have tried the configuration.h settings with out the Z probe/ auto bed level settings to see if maybe it was it causing the issue some how but it did not change any thing with or with out the z probe hooked up I still get the same errors so its some thing else I'm missing. I've always had these issues with marlin firmware, I use the most basic 3D printing electronics found online. I don't understand how other people get it working with the same hardware with no issues. If I load Sprinter on to the arduino all the problems go away but then I cant use the auto bed level feature since its not supported in sprinter firmware.

**Comment by geakg-gone-wild** [comment]
The Printer its self if a i3 MK3 Hybrid, I built my self.

the frame is made from this: https://www.thingiverse.com/thing:971110

all of the inner parts for X axis are using the Prusa i3 MK3 parts.

Y axis I designed my own parts for, but they work fine, I've already tested the printers movements using Sprinter firmware.

I should note I have A LOT of printer building experience, at least 20+ printers. I normally use sprinter firmware which I know really well since I use it a lot. I liked Marlins set up because it is a mostly the same as sprinter as far as how the configuration.h files work and most of its settings are identical. I would jsut use sprinter since it dosnt give me any issues but I'd really like to put auto bed level on all of my printers, this situation has me in a halt because I'd like to build another 10+ printers but I'd really really like for them to have auto bed level.

**Comment by GMagician** [comment]
You may try enabling ENDSTOP_NOISE_FILTER. If it solves you have electric noise on endstop inputs

**Comment by geakg-gone-wild** [comment]
I did try that already, it didnt change any behavior. I am using optical endstops though, some thing I forgot to mention.

**Comment by GMagician** [comment]
Do printer halt when endstop is "pressed" or after motor move a little out of sensor?

**Comment by geakg-gone-wild** [comment]
soon as it hits the sensor it throws the code on repetier host. I made a small amount of progress. When I turn on pull ups for X and Y min I can now home the printer with out error codes, but If i try to print some thing I get the error code again. 

theres a catch though, If I home the Y axis first it will give me the error code, if I home X thenY no error code unless I try to print.

**Comment by GMagician** [comment]
If pull up solve homing it means sensor don't have it and just close to GND.
Do you have M120/M121 in your gcode?

**Comment by geakg-gone-wild** [comment]
I havnt added any G-code so I dont think I have the M120/M121 in my G-code.

Also, its only the Y axis causing the issue now. When I try to print X axis homes and then Y goes to home soon as it touches senor it gives me the error.

**Comment by GMagician** [comment]
> When I turn on pull ups for X and Y min I can now home the printer

you can home axes...

> When I try to print X axis homes and then Y goes to home soon as it touches senor it gives me the error.

you can't home when you start printing..

do I understood correctly?

**Comment by GMagician** [comment]
...maybe pull up is nopt strong enough

**Comment by geakg-gone-wild** [comment]
yes, correct whn i try to print errors come back. It seems some times when I home it gives the error randomly now, some times it homes fine some times it gives error.

I think it is firmware issue because when I install sprinter firmware every thing works fine with no issues at all but then I cant use auto bed level. with sprinter installed instead of marlin the printer works perfectly but sprinter does not have support for auto bed level feature.

**Comment by Micro-3D-GER** [comment]
**@Hello georg-gone-wild**

What endstops did you build for X and Y?
I have built these mechanical endstops for X and Y, here is an example such as Reprap Endstop

This is how I configure the X and Y MIN endstops
```cpp
// Enable pullup for all endstops to prevent a floating state
#define ENDSTOPPULLUPS
#if DISABLED(ENDSTOPPULLUPS)
  // Disable ENDSTOPPULLUPS to set pullups individually
  //#define ENDSTOPPULLUP_XMAX
  //#define ENDSTOPPULLUP_YMAX
  //#define ENDSTOPPULLUP_ZMAX
  #define ENDSTOPPULLUP_XMIN
  #define ENDSTOPPULLUP_YMIN
  #define ENDSTOPPULLUP_ZMIN
  #define ENDSTOPPULLUP_ZMIN_PROBE
#endif

// Mechanical endstop with COM to ground and NC to Signal uses "false" here (most common setup).
#define X_MIN_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define X_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Y_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MIN_PROBE_ENDSTOP_INVERTING false // set to true to invert the logic of the probe.
```

**Comment by boelle** [comment]
@geakg-gone-wild problem solved?
