### ISSUE TITLE
Bug with Filament Runout Sensor Script/ Advanced Pause Features

### ISSUE THREAD

**Issue by forum999** [MarlinFirmware/Marlin#12867]
despite being enabled in marlin 1.1.9, Advanced_Pause_Feature seems to have a bug when used with the filament runout sensor script and refuses to compile (Yet it compiles fine if i leave the Filament_Runout_Sensor commented/disabled?).

When i try to compile i get the following error (despite `ADVANCED_PAUSE_FEATURE` being uncommented and setup) (see attached pic).

```
In file included from sketch\MarlinConfig.h:42:0,

                 from sketch\G26_Mesh_Validation_Tool.cpp:27:

SanityCheck.h:502: error: static assertion failed: ADVANCED_PAUSE_FEATURE is required to use M600 with FILAMENT_RUNOUT_SENSOR.

     static_assert(NULL == strstr(FILAMENT_RUNOUT_SCRIPT, "M600"), "ADVANCED_PAUSE_FEATURE is required to use M600 with FILAMENT_RUNOUT_SENSOR.");

     ^

exit status 1
static assertion failed: ADVANCED_PAUSE_FEATURE is required to use M600 with FILAMENT_RUNOUT_SENSOR.
```
![marlin error](https://user-images.githubusercontent.com/34663705/50967995-ade99e80-14d1-11e9-814c-128ed5abcf3c.JPG)

**Comment by ghost** [comment]
Post the complete configure.h and configure_adv.h, maybe?

**Comment by forum999** [comment]
Apologies, i thought i had added them.

See attached zip


[config.h and config adv.h.zip](https://github.com/MarlinFirmware/Marlin/files/2746240/config.h.and.config.adv.h.zip)

**Comment by ghost** [comment]
I picked up the absolute current Bugfix-2.0.x, put in your configuration.h and configuration_adv.h and made the following quick changes:

1. configuration.h: commented out theTMC2208 stuff
//#include <TMC2208Stepper.h>
//#include <TMC2208Stepper_REGDEFS.h>
and changed all stepper driver defs to default.
2. configuration_adv.h: changed RETRACT_ZLIFT to RETRACT_ZRAISE.

No other changes.

Compile Successful, no errors.

FILAMENT_RUNOUT_SENSOR is defined and all is ok.

Duh

From when is your 2.0.x?

**Comment by forum999** [comment]
I believe its the one at the top where i clearly state this is from Marlin 1.1.9? Duh... 😂Lol

I wanted to update my current version of marlin so i didnt have to add all the changes etc into 2.0?

Inthink we can confirm though that this is a bug in 1.1.9 that seems to be fixed in 2.0

**Comment by ghost** [comment]
Hmmmm, that's funny, because your configuration.h contains a
```
#define CONFIGURATION_H_VERSION 020000
```
which led me to believe you want 2.0.x.

You might want to recheck the whole setup.

**Comment by ghost** [comment]
I should add, having a higher version in there than "needed" passes the sanity check with no errors being raised. I haven't checked the rest of the file as to whether it conforms more to 1.1.9 or more to 2.0.0, that's not the important point. **You are right, it probably got fixed sometime between 1.1.9 (yours) and Bugfix-2.0.0 (current git version)**

**Comment by forum999** [comment]
Hmm that is odd? Definately 1.1.9 

Thanks for the help,

**Comment by boelle** [comment]
@forum999 problem solved?
