### ISSUE TITLE
Ender 3 Configuration is using the wrong jerk setting

### ISSUE THREAD

**Issue by dajanamilk** [MarlinFirmware/Marlin#12871]
### Description
Hi, the configuration.h file for the ender 3 has the jerk value set to : 
#define DEFAULT_XJERK                 10.0
#define DEFAULT_YJERK                 10.0
#define DEFAULT_ZJERK                  0.3
#define DEFAULT_EJERK                  5.0

end the original ender 3 configuration file uses this settings:
#define DEFAULT_XYJERK                20.0    // (mm/sec)
#define DEFAULT_ZJERK                 0.4     // (mm/sec)
#define DEFAULT_EJERK                 5.0    // (mm/sec)

So the configuration.h for ender 3 should be:
#define DEFAULT_XJERK                 20.0
#define DEFAULT_YJERK                 20.0
#define DEFAULT_ZJERK                  0.4
#define DEFAULT_EJERK                  5.0

I did this change and didn't notice any change in print quality so we should keep with the original values created by creality.

**Comment by thisiskeithb** [comment]
When I created the request, it was my understanding that the jerk settings were halved at one point during Marlin development. Creality was using a version of Marlin from before this change, so I adjusted the settings appropriately.

Edit: Jerk values were reduced in [Marlin 1.1.8](https://github.com/MarlinFirmware/Marlin/releases/tag/1.1.8).

**Comment by swilkens** [comment]
Creality recently, upon request, made a more up to date version of their firmware source available:

https://www.creality3d.cn/download/firmware_c0001

That link now provides newer sources for the Ender 3 and Ender 3 Pro, now based off what seems to be Marlin 1.1.6 for the Ender 3. The "Pro" source appears older, but it's essentially the same as the non-pro anyway. The configuration files included there show:

> /**
>  * Default Jerk (mm/s)
>  * Override with M205 X Y Z E
>  *
>  * "Jerk" specifies the minimum speed change that requires acceleration.
>  * When changing speed and direction, if the difference is less than the
>  * value set here, it may happen instantaneously.
>  */
> #define DEFAULT_XJERK                 10.0
> #define DEFAULT_YJERK                 10.0
> #define DEFAULT_ZJERK                  0.4
> #define DEFAULT_EJERK                  5.0

Somewhat related, there are some noises going around about shifting from classic jerk to junction deviation as the standard.

**Comment by reloxx13** [comment]
after those jerk changes in the config i got heavy y layer shifts. im going back now and see if this was the reason.

ender 3 ( non-pro, marlin 2.0.x- cb643d87df16dd54d6e7779fe8565c9be04ec951 , 2019-01-02 )
cura 3.6 with disable jerk control



EDIT:
i tried to print 4 times now, updated the config from latest marlin and re-flashed, always get a y shift.

i reverted the jerks settings now and till now (0:45 print time) got no y shift.


NEW:
```
  //#define DEFAULT_XJERK 10.0
  //#define DEFAULT_YJERK 10.0
  //#define DEFAULT_ZJERK  0.3
```

OLD:
```
  #define DEFAULT_XJERK 20.0
  #define DEFAULT_YJERK 20.0
  #define DEFAULT_ZJERK  0.4
```
