### ISSUE TITLE
Intaso 100% problema _ [Anet A8 - Bowden - Marlin 1.1.9]    --------> Fix!

### ISSUE THREAD

**Issue by Lucaevo2** [MarlinFirmware/Marlin#12873]
Hi guys
I have a problem with my Anet.
Before switching to the Bowden and the Marlin 1.1.9 firmware, the printer printed fine.

Now I have this problem of infill. It almost seems like a steps issue.

In fact I tried to change some parameter in the code:

1. `#define DEFAULT_AXIS_STEPS_PER_UNIT { 80, 80, 400, 100 }`

Since:
Step Angle 1.8 °
Pulley Tooth 20
GT Pulley 2mm

With this I solved the problem of the infill mm the size of the calibration cube were wrong.

2. Then…
  ```
  #define DEFAULT_ACCELERATION 250
  #define DEFAULT_XJERK 3.0
  #define DEFAULT_YJERK 5.0
  ```

The result is improved but not solved.

3. I have returned to its original firmware. Printing better but the problem is not fixed.

I would not go back to direct extrusion, but I would solve this problem.

Does anyone have any ideas or better, a solution?

![img_20190111_102637](https://user-images.githubusercontent.com/46597684/51033084-7ac31000-15a2-11e9-912a-808120d7bbcd.jpg)

![img_20190111_120535](https://user-images.githubusercontent.com/46597684/51033144-ae9e3580-15a2-11e9-9755-b83c1adf33f8.jpg)

**Comment by vilsed** [comment]
It's not clear - are the external dimensions of your test cubes incorrect or are you just not satisfied with incomplete solid infill filling? Because if it's the latter, and you have changed the extruder itself - all you have to do is calibrate your E-steps/mm.

**Comment by Lucaevo2** [comment]
Sorry about my explanation. My problem concerns precisely with incomplete filling of the solid fill.
Now I try to calibrate my E-steps/mm.
Thank you so much for the support.
I'll keep you updated.

**Comment by Lucaevo2** [comment]
I calibrated the e-steps, but I did not solve it. I think it's a problem of setting up firmware when printing fills. I have the same problem:

https://youtu.be/Icw-mR_mzhg

**Comment by vilsed** [comment]
Interesting. Firmware has no business or, for that matter, no idea "what" it's printing. It does not matter if it's 20% infill, 100% infill or perimeters, firmware does not care. It just executes gcode commands it is given. Please share your configuration.h, configuration_adv.h and gcode file you're trying to print.

**Comment by Lucaevo2** [comment]
thank you for your support. 
I share the files:

configuration.h
configuration_adv.h
.gcode
.factory

now, I'm using Marlin 1.1.9 and simplify3d 4.0.0




[files.zip](https://github.com/MarlinFirmware/Marlin/files/2759301/files.zip)

**Comment by Lucaevo2** [comment]
I don't know if this can help.

On the web I found K-factor Calibration Pattern.
link: http://marlinfw.org/tools/lin_advance/k-factor.html

I also share the g.code generated by the website with the stock setting (I changed the temperatures and the printing speeds) and the result of the print

[K-factor.zip](https://github.com/MarlinFirmware/Marlin/files/2759365/K-factor.zip)

**Comment by vilsed** [comment]
Very very interesting. I didn't saw anything out of the ordinary in your files. Did you calibrate the extruder simply by extruding set amount and measuring how much filament was actually extruded? I find this method good only for rudimentary calibration, to get "close enough". For precise calibration I print with 100% infill and increase/decrease the E_steps/mm with M92 until I just achieve actually solid infill without gaps and without over extrusion. One more thing to check - does your filament move freely through the bowden tube? Is the extruder not skipping steps? If all those check out - try printing a bit slower, maybe at 30mm/s. If everything fails - you could try bugfix-1.1.x, but I still highly doubt that this is firmware related. I've had similar problems before, all times it was hardware/calibration related.

EDIT:
You have linear advance disabled, hence the calibration tool does not do anything. Either way, this isn't related to your issue.

**Comment by Lucaevo2** [comment]
Ok I followed your advice and i  "solved " (it isn't perfect) reinstalling the Marlin 1.1.9 with the parameter e-steps/mm calculated, it seems that now has assimilated.

But I found a new problem. 
Now the size on the Y-axis is wrong (smaller).

I share the photos of the progress.

[Progress.zip](https://github.com/MarlinFirmware/Marlin/files/2760917/Progress.zip)

**Comment by vilsed** [comment]
As far as extrusion  rate goes - I think you have it pretty much dialed-in for a bowden setup. As for the gaps and size mismatch in Y direction, I think it's a mechanical issue with the bed. Make sure that it can move freely. Make sure that the pulley on the motor is tight and not wobbly. If you have spring tensioners on your belts - remove them. They are more trouble than they're worth. These cheap chinese machines are notorious for problems like these. 

If everything seems correct, try lowering jerk and acceleration for the Y axis. 

One other problem I see with your test cube - lack of cooling/overheating. I'd suggest to always keep the part cooling fan at >80% for PLA. But this is completely unrelated.

**Comment by Lucaevo2** [comment]
I followed your suggestions and found that it was a mechanical problem of the bed. I disassembled all the axes bars and I cleaned them and oiled them.
Now it's fine!

The size of the y was wrong because of the friction, like every filling problem!

Now it's perfect

Thank you very much!

**Comment by vilsed** [comment]
Glad to help :)

**Comment by boelle** [comment]
@Lucaevo2 problem solved?
