### ISSUE TITLE
lcd variable display

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#12872]
Hi,
I want to display a variable on MKS MINI12864 but I could not do that. For example I want to display  extruder or bed degree values in the any other submenus with normal string. In the lcd screen "fatih 45/100". Only variable is 45 and others are normal string.

**Comment by Bob-the-Kuhn** [comment]
We've all been there.

Do a search for **LCD_INFO_MENU** and look at the code in the modules that it's used in.  You should be able to find some uesdul examples starting there.

**Comment by boelle** [comment]
@fatihbircan problem solved?
