### ISSUE TITLE
Einsy Rambo Fan causes freeze

### ISSUE THREAD

**Issue by Lyr3x** [MarlinFirmware/Marlin#12875]
Since today i have a weird problem with my Einsy Rambo. This mainboard has two controllable fans and as soon as layer FAN 1kicks in the motors wont move anymore until a reset. Heaters/Thermistors still working and i also can use the LCD. 

When connecting the Fan to the FAN 2 connector and start the fan everything is working fine. I tried to change the Pin mapping to FAN 1 is now the FAN 2 connector. After firmware upload and eeprom reset the behavior was the same. The fan is connected to the FAN 2 connector but declared as FAN 1 and when the fan start all movement stopped. 

Any Ideas?
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/2750387/Config.zip)

**Comment by revilor** [comment]
I don't know if this is relevant for your issue, but in Prusa Firmware the fan is on PIN 6

#define FAN_PIN              6
#define FAN_1_PIN           -1

**Comment by AnHardt** [comment]
Try `#define FAN_SOFT_PWM`.  Looks as if the hardware timer used for that fan-pin-hardware-pwm  is already in use for the stepper interrupt.

**Comment by Lyr3x** [comment]
I'll have a look at this next weekend and report to you 👍

**Comment by boelle** [comment]
@Lyr3x problem solved?
