### ISSUE TITLE
Issue when homing (during print job)

### ISSUE THREAD

**Issue by Flokri** [MarlinFirmware/Marlin#12882]
Hey. I've recently updated my Prusa i3 Hephestos to the Marlin 2.5.1 Firmware. I've also installed an inductive sensor for auto bed leveling. The leveling function did well with a previous firmware version. When I send the G28; G29; Command manually to the printer all works as expected BUT when I slice a file (don't matter which software I use) and want to print it the auto bed leveling doe not work anymore. 

The Z-axsis seems to be inverted. Instead of going down (towards the bed) the axis raises and stops at any height. I've checked the printer output and the sensor is not triggered so I have no clue why and when the print stops in midair. 

Following is my config file. I spend more than 20 hours finding the bug... Does of you may know why this is happening?

My [Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2914334/Configuration.zip)

**Comment by GMagician** [comment]
> Marlin 2.5.1 Firmware.

sure it's same firmware we have here? As I know we have 2.0.x as latest version

**Comment by Flokri** [comment]
My checked out version is 2.5.1 mz printer says it 1.8

**Comment by GregFax** [comment]
I'm having the same symptom/problem with my COREXY HyperCube going from v1.1.3 to v1.1.9.
It's kinda like Z axis homing has reversed direction, but the config settings are unchanged from my previous......
It's driving me crazy!
By the way, your config file says v1.1.7 (010107 just above "Getting Started".....

**Comment by boelle** [comment]
@Flokri problem solved?

**Comment by GregFax** [comment]
I eventually solved my particular case. 
I had missed setting Z_MIN_ENDSTOP_INVERTING and Z_MIN_PROBE_ENDSTOP_INVERTING to false, when I updated my config file to v1.1.9. That error alone caused the direction reversal when homing.
Frustratingly, all other moves occurred as expected, making the trouble shooting tedious.
I can TOTALLY recommend using a comparison text editor (like Notepad++) over scrolling thru the files when updating!!

**Comment by Flokri** [comment]
> 
> 
> @Flokri problem solved?

Suchergebnisse
Ergebnis zur Übersetzung

No not solved. But I know it depends on my heated bed. When I comment the heated bed code lines (so it's not available) the homig works fine during print. At first i thought it moight be a voltage issue but I could not found any thing abnormal measuring the circuits.

**Comment by boelle** [comment]
@Flokri i just read your first post again

> Marlin 2.5.1 Firmware

Marlin has not been released as that version, where did you get marlin from?

**Comment by Flokri** [comment]
> 
> 
> @Flokri i just read your first post again
> 
> > Marlin 2.5.1 Firmware
> 
> Marlin has not been released as that version, where did you get marlin from?

Sorry somehow there was a big mess with my firmware checkout. I use the latest 1.1.9 relase.

**Comment by boelle** [comment]
That can happen to the best of us :-D

Have you tried bugfix 2.0?

**Comment by boelle** [comment]
Also, if its not to much trouble for you can you edit the first post to make it  shorter?

remove the config as text and attach the 2 config files as a single zip file.

**Comment by Flokri** [comment]
> 
> 
> That can happen to the best of us :-D
> 
> Have you tried bugfix 2.0?

No. To be honest I didn't saw that version till you mentioned it. I will give it a try. Thank you :)

**Comment by boelle** [comment]
Kein Problem :-D

**Comment by boelle** [comment]
But we are trying to see if this issue has not been fixed in 2.0

the older versions will get updated in the end but i think it will be at much slower speed

**Comment by boelle** [comment]
remember that the structure of the config files have changed so you might want to use a tool like winmerge to compare the old config with the new and then move over settings

**Comment by boelle** [comment]
@Flokri had time to try 2.0?
