### ISSUE TITLE
Feature request: Prematurely aborting G29

### ISSUE THREAD

**Issue by orangeudav** [MarlinFirmware/Marlin#1288]
subj

**Comment by alhirzel** [comment]
The current way to do this is hardware reset; what would the abort feature look like?

**Comment by a0s** [comment]
Hmm, I want to send some gcode during `G29` to abort it.

**Comment by boelle** [comment]
I dont think this will benefit many and because of that i will close it

implementing it will require work, and we have to think about a few things: how many would benefit, how much will it complicate things, is it at all possible

of course you are always welcome to contribute and submit a PR

**Comment by thinkyhead** [comment]
Sometimes `M112` will work. (Not if `G29` comes from a print job, but it should work if `G29` was issued from a console.)
