### ISSUE TITLE
Z_PROBE_SPEED_FAST & Z_PROBE_SPEED_SLOW without function

### ISSUE THREAD

**Issue by chrisqwertz** [MarlinFirmware/Marlin#12890]
### Description

Z_PROBE_SPEED_FAST & Z_PROBE_SPEED_SLOW values are not applied with a BL touch.

### Steps to Reproduce

Set Z_PROBE_SPEED_FAST in my Configuration.h ln 824 to any value.

**Expected behavior:** Change of probing speed

**Actual behavior:** Uses Z Vmax (in my case 8mm/s) to to probing

#### Additional Information

(used M502; M500; after flashing)

[Mendel90 conf.zip](https://github.com/MarlinFirmware/Marlin/files/2752479/Mendel90.conf.zip)

**Comment by GMagician** [comment]
Are not applied when you do what?
Homing or whatever? These speeds are not used with G28 but with G29 and some other commands

**Comment by chrisqwertz** [comment]
I got it, Vmin and Vtravel min override the homing speeds. I think this is not the wanted behaviour as these minimal values are ment to be used while printing, or am I wrong?

**Comment by GMagician** [comment]
Not sure about that..vmin may be an absolute indicator, while vtravel maybe is more "printing" related...

**Comment by GMagician** [comment]
if seems that both limit velocities are used everytime. One is for extruder and for "cartesian" moves

**Comment by letthewookiewin7** [comment]
I'm having the same issue as chrisqwertz.  No issues homing on 1.1.7.  After flashing to 1.1.9 with the same settings, the second probe move on z is still done at the faster speed.

**Comment by boelle** [comment]
@chrisqwertz problem solved?

**Comment by chrisqwertz** [comment]
Upgrading to a 32bit board right now, Will take a bit before I can test again.

**Comment by letthewookiewin7** [comment]
I'm still experiencing it.  Is there a potential fix that I can test out?

**Comment by boelle** [comment]
@letthewookiewin7 still on 1.1.9? try 2.0

**Comment by thinkyhead** [comment]
> the second probe move on z is still done at the faster speed.

For `G28` homing with the probe, `HOMING_FEEDRATE_Z` applies to the first move, and `HOMING_FEEDRATE_Z / HOMING_BUMP_DIVISOR` applies to the second (bump) move.

**Comment by boelle** [comment]
@chrisqwertz had time to test?

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
