### ISSUE TITLE
MKS TFT28 communication error with MKS Gen1.4 

### ISSUE THREAD

**Issue by rouhit110** [MarlinFirmware/Marlin#12898]
Hi friends
what parameter in marlin  should I use to use this LCD on this controller?
I recently enabled the filament runout sensor
When the filament finished, the extruder is transferred to the park's place, and some retract.. But nothing happens when I reordering filament
The LCD does not show any messages. The nozzle turns off and the temperature is not displayed on the lcd. pause andstop items not work.
generally, the lcd get interrupted with the controller

I uncommented `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`
I use marlin 1.1.9 Bugfix1.1.x
If anyone can help me, I will be very grateful

**Comment by boelle** [comment]
@rouhit110 problem solved?

**Comment by thinkyhead** [comment]
Please test with the `bugfix-2.0.x` branch so we're all on the same page here. That branch contains all the latest patches.

**Comment by boelle** [comment]
@thinkyhead think we can close this one
