### ISSUE TITLE
[Question] Thermal runaway detection

### ISSUE THREAD

**Issue by Lyr3x** [MarlinFirmware/Marlin#12908]
Background: Yesterday my external Mosfet blew up causing an always HIGH Output of the Mosfet resulting in a heating heated bed. That happened while a print was running and I recognized the failure right after the print because the heated bed reached 98° which is  nearly maximum temp for the bed. Display showed 0/98°.
Since yesterday I thought that the default thermal runaway protection cover this type of failure but it doesn't.

Is there any safety feature I am not aware of to cover this? If the target temp is 0° and the temp is rising the firmware should give an error information, that the user can see that something is wrong.
Of course due to the blown Mosfet the firmware can't stop the unintended heating though.

**Comment by InsanityAutomation** [comment]
The only way the firmware can do anything about a fused relay or closed mosfet is cutting off the power supply. Unfortunately, most manufacturers do not connect the power supply to an enable relay therefore there is nothing else firmware can do. If the switch is physically fused right to a power source we have no control over, its stuck. Can either connect a relay or ssr to the PS_ON pin for your board to kill the power supply, or use a snapdisc thermalcouple on the bottom of the bed before the mosfet to kill power there if it gets too hot.

**Comment by Lyr3x** [comment]
Yep sure, that's why i mentioned the information idea. It is possible to detect an unintended behavior and inform the user isn't it?

**Comment by AnHardt** [comment]
If you are still able to reproduce the error, please try with target temp 1° instead of 0°.
Could be we have unintended behavior if the heater is "off" = 0.
I guess the detection has to be started, what likely is not done when the heater is off.

However, MAXTEMP-ERROR should be the next stage of escalation and give an error even if the heater is off..

**Comment by MasterPIC** [comment]
@Lyr3x thanks to your question I just realized that a thermal runaway caused by a MOSFET failure would keep my heated bed always powered on.
So I set an action command to send to the host when a thermal error occurs and set Octoprint accordingly so that the PSU is powered off in such a case.

In Configuration_adv.h we could add

`#define ACTION_ON_THERMAL_ERROR "thermal_error"`

and then add
```
#ifdef ACTION_ON_THERMAL_ERROR
  SERIAL_ECHOLNPGM("//action:" ACTION_ON_THERMAL_ERROR);
#endif
```
in temperature.cpp - Temperature::_temp_error (L659).

**Comment by ManuelMcLure** [comment]
If your motherboard has an available pin that can be configured as `PS_ON_PIN` you should use Marlin itself to control the power supply. For example on a RAMPS you can use the `PS_ON` pin, but it should be possible to configure a pin on any board that has a spare (although you may need to edit the `pins.h` file for that board). When Marlin sees a thermal error it will call `kill()` which will turn off the power supply even if for some reason OctoPrint can't see the problem. One less point of failure. You can still control the power supply from OctoPrint by telling it to use the `M80` and `M81` gcodes.

**Comment by MasterPIC** [comment]
kill is called after the error has been reported to the host.
If the host disconnects as soon as an error is reported ACTION_ON_KILL is useless.
This is the reason why I suggested the change.

@ManuelMcLure I was already using the only available pin to control the led case.
I agree with you about making the motherboard controlling the PS_ON_PIN; so I could opt for your solution and add an action command to control the led case...

**Comment by boelle** [comment]
@Lyr3x problem solved?

**Comment by thinkyhead** [comment]
Marlin does always throw `MAXTEMP` if the temperature goes over the configured maximum for the hotend or bed. But it doesn't always watch the hotend to make sure the temperature is dropping when the target temperature is below the current temperature. It would be possible to add this functionality at the cost of some additional SRAM and CPU usage per temperature sensor.
