### ISSUE TITLE
[Q] Marlin 2.0 HEATER_0_PIN on Teensy 3.6?

### ISSUE THREAD

**Issue by serdardogan** [MarlinFirmware/Marlin#12904]
### Description

Hi everyone,
I'm Teensy 3.6 user and I'm developing a shield right now. But in pins_TEENSY35_36.h, pin 30 is used as both E0_DIR_PIN and HEATER_0_PIN.

**Expected behavior:** I think HEATER_0_PIN pin 36 can be used

**Comment by serdardogan** [comment]
Also overlaps with HEATER_BED_PIN and E0_STEP_PIN.
I think HEATER_BED_PIN can be pin 23

**Comment by ajanky** [comment]
same problem here, just defining the Eagle file...
look at the comment graphics at the top of the file: E0 is moved to pins 17,18 and 19
However, I'm missing a Z Probe input - so if you have suggestions for added pins, lets share

**Comment by serdardogan** [comment]
Pins in the upper part of the graph in the pin file and in the different definitions in the lower part. 
Do I have to accept the pins specified in the graph on the top or the pins on the bottom?

**Comment by ajanky** [comment]
I have just noticed that there is in fact a total mismatch. I have defined a pin-file according the top graph and will test pins tomorrow on a breadbord. 
Seems there is no general accepted pin assignment yet. If I identify problems I will report here.

**Comment by serdardogan** [comment]
thank you so much. I will follow the updates.

**Comment by ajanky** [comment]
OK, you're pretty free to assign a new pin for the heater_0.
I have cleaned up the pin assignment for my purposes and started testing on a breadboard with scope. all outputs, endstops and Temp inputs work so far. Haven't tested display port yet. Tried to keep standard I2C and SPI port free. 
attached my current assignment. 
I will update after more tests.

![teensy_pins](https://user-images.githubusercontent.com/24829664/51432332-16edb680-1c36-11e9-80a3-31d535aab932.png)

**Comment by thinkyhead** [comment]
Please go ahead and use whatever pins seem most sensible to you. The current assignments may just be best-guess settings, since there are few if any boards based on these MCUs.

**Comment by serdardogan** [comment]
Thank you very much for helping. I can't wait to test it as soon as possible.

**Comment by boelle** [comment]
@serdardogan problem solved?

**Comment by serdardogan** [comment]
> 
> 
> @serdardogan problem solved?

I haven't checked in yet. I'il check it out as soon as possible. Sorry

**Comment by boelle** [comment]
@serdardogan had time to check?

**Comment by serdardogan** [comment]
> 
> 
> @serdardogan had time to check?

Sorry.
I'm trying to install teensy now, but I've encountered a compilation error, I can't load it

**Comment by serdardogan** [comment]
I am not getting the same error in my previous bugfix version.

My arduino compiler versiyon is 1.8.8 and teensyduino version is 1.45.

**Comment by boelle** [comment]
not tried with ide 1.9?

**Comment by serdardogan** [comment]
I can't test arduino ide 1.9 because teensyduino is don't install for ide version 1.9.
I'm using and tested Arduino ide 1.8.8 and can't install to teenys 3.6

**Comment by boelle** [comment]
and vscode+platformio does not support the teensy either?

**Comment by serdardogan** [comment]
> 
> 
> and vscode+platformio does not support the teensy either?

I have no idea about this. I didn't use yet.

**Comment by salfter** [comment]
> and vscode+platformio does not support the teensy either?

They do...haven't done much more yet than make the onboard LED blink faster, but the necessary compiler support is there.

**Comment by serdardogan** [comment]
> 
> 
> > and vscode+platformio does not support the teensy either?
> 
> They do...haven't done much more yet than make the onboard LED blink faster, but the necessary compiler support is there.

I don't use teensy too much, I also bought it a short time ago. I'm sorry you acted like this.
