### ISSUE TITLE
reprap smart lcd Marlin 2.0

### ISSUE THREAD

**Issue by davidcgu** [MarlinFirmware/Marlin#12910]
Good afternoon

I have an mks gen L main board with MKS TFT connected and one reprap LCD booth working at once.

Are running fine on 1.1.9 however I can not get running the LCD on 2.0 with same config than before.

I have un commented line:  #define REPRAP_DISCOUNT_SMART_CONTROLLER

Any advice?

**Comment by kAdonis** [comment]
Are you sure you have a **RepRapDiscount Smart Controller**?
or do you have a **RepRapDiscount FULL GRAPHIC Smart Controller**?

**Comment by davidcgu** [comment]
Is sure not a full grhaphic, is a 2004 with encoder & buzzer, I don't know how to attach here a picture.

Regards

**Comment by marcio-ao** [comment]
> I don't know how to attach here a picture

Just drag-and-drop an image file onto the text-box.

**Comment by davidcgu** [comment]
![img_20190114_110236](https://user-images.githubusercontent.com/34965121/51212889-e9dd9300-1919-11e9-9127-be9a7aac54a2.jpg)
![img_20181227_163021](https://user-images.githubusercontent.com/34965121/51212911-feba2680-1919-11e9-8553-5201ebd55d8f.jpg)

**Comment by boelle** [comment]
@davidcgu problem solved?
