### ISSUE TITLE
Bilinear bed leveling probe count

### ISSUE THREAD

**Issue by owca6666** [MarlinFirmware/Marlin#12914]
Hi guys, for the past couple days i managed to get marlin 1.1.9 working on my printer, but ive ran into a problem, i completely dont know how to change amount of points probe does on the bed.

Currently it does 3x3x3 i would want at least 4x4 grid or even 5 cuz my bed is warped in middle.

> #define GRID_MAX_POINTS_X 

when i change this to 4 or 5 octoprint gives me eeprom error, even when i make it ignore the error probe measures only 3 points on the bed.

**Comment by RudyBenner** [comment]
After you flash the firmware, you need to do M502, then M500 and some will say also M501. 

I prefer Repetier Host over the Octiprint, for work "under the hood"


rudy

**Comment by owca6666** [comment]
> After you flash the firmware, you need to do M502, then M500 and some will say also M501.
> 
> I prefer Repetier Host over the Octiprint, for work "under the hood"
> 
> rudy

OMG it worked, i tried to get that running for over a day...

Thank you very much :)
