### ISSUE TITLE
Using float values in MIN_X_POS and Y_MIN_POS fails the G29 Bed leveling command

### ISSUE THREAD

**Issue by rdar-lab** [MarlinFirmware/Marlin#12918]
After accurate measurement I changed the configuration in Marlin with the following values:
define X_MIN_POS -32.5
#define Y_MIN_POS -2.8
The configuration successfully validated, and I have successfully updated the printers FW.

However, when I tried to perform a G29 instruction it failed with the following error (error shown in Octoprint terminal):
Recv: ? (L,R,F,B) out of bounds.

Returning the values to integer resolved the issue

**Comment by RudyBenner** [comment]
#define X_MIN_POS -35
#define Y_MIN_POS -07

I think there will be variations between machines. The owner should expect to do a little work.

**Comment by RudyBenner** [comment]
Yes, an integer is expected.

**Comment by boelle** [comment]
@black-zone-1000 problem solved?

**Comment by rdar-lab** [comment]
@boelle  Is it possible to add a compile-time error instead of this very unsettling error when attempting to perform a G29?

**Comment by boelle** [comment]
dont know, i'm not a coder

**Comment by rdar-lab** [comment]
So maybe change this to a feature request to add the validation?
