### ISSUE TITLE
[bugfix-2.0.x] Menu (SD Card?) problems

### ISSUE THREAD

**Issue by gordio** [MarlinFirmware/Marlin#12915]
### Description
See item "Pause printing" without printing in progress, and "Print from SD Card" at last item in menu.
RAMPS 1.4 with RepRapDiscount Full Graphic Smart Controller

### Steps to Reproduce

0. "Install" Version 2.0.x (tested on latest 85f149befeebde5e67e9d0241d2708c30a356640 and 1a79878dff2d4846b1f58a45b8880a346fb9cb41)
1. Open menu.

**Actual behavior:**

Second line item is "Pause printing" BUT without printing in progress.

#### Additional Information

* No problems on fb8111553e1e2622aa739be933ed6273c83d4c56
* I don't use parking

**Comment by Poeschl** [comment]
The `Print from SD Card` was moved on https://github.com/MarlinFirmware/Marlin/issues/12487.

**Comment by InsanityAutomation** [comment]
And the rest of the menu fixups are sitting here https://github.com/MarlinFirmware/Marlin/pull/12893

**Comment by InsanityAutomation** [comment]
Can you confirm that things are correct at this point? And if so this issue can be closed.

**Comment by fakcior** [comment]
@InsanityAutomation The issue still exists.

**Comment by boelle** [comment]
@gordio problem solved?

**Comment by fakcior** [comment]
@boelle I can answer: Yes!

**Comment by boelle** [comment]
but only @gordio or @thinkyhead can close the issue :-D

**Comment by gordio** [comment]
@fakcior I trust you! :)
