### ISSUE TITLE
Probe Effector Offset for Deltas?

### ISSUE THREAD

**Issue by FlailAway** [MarlinFirmware/Marlin#12912]
Using 1.1.9, Anycubic Linear+ Delta
Is there a way to define an offset for a probe mounted 25mm behind the centre of the effector and directly inline with the Z-column?

I found this [https://github.com/MarlinFirmware/Marlin/issues/9158](url) but it does not seem to have a useful conclusion.

I also found #define LEFT_BED_PROBE_POSITION -(DELTA_PRINTABLE_RADIUS - MIN_PROBE_EDGE)) etc, but that doesn't seem to make sense to me with a circular bed for a Delta. 
Currently I have the "EDGE" set at 40 and it probes almost to the edge at the back and 30mm in from the front.

**Comment by emailcraigs** [comment]
I am wondering the same thing but slightly different. I also have the Anycubic Kossel Linear Plus. I tried to implement UBL. It probes fine and creates a mesh but the mesh is above the bed. I assume its because there is no where, that I can find, to input an offset for the fact that the Anycubic has a probe, version 2 for me, that fits on the effector and places the probe head in line with the nozzle but some 33mm below it. The result is that mesh validation starts printing in the air. I could manually change ALL the probe points...or I've heard of a total mesh shifting procedure I think, but I would rather just be able to input an offset if possible. Anyway, I don't want to hijack a thread but I think my issue coincides with FlailAway's issue.

**Comment by FlailAway** [comment]
That sounds strange, I can get it to probe and work, kind of, but at the **almost** correct level. My problem is the Anycubic hot-bed is cupped slightly and not evenly, so I need a bigger scanned area. I can't use a glass bed as the sensor will not read deep enough. I have built my own smaller effector with decent cooling fans so the Anycubic probe is no longer usable.

Did you use the Anycubic Kossel sample Configuration.h in Examples/Delta? You need to set the correct sensor type as v-1 is NO (Normally Open) and v-2 is NC (Normally Closed) [from memory]. There is a thread on his somewhere in the Marlin 2.0 section. You may also need to check the end-stop Inverting state.

Also check the Z_PROBE_OFFSET_FROM_EXTRUDER is set for the correct probe and length as v-1 and v2 are different. There is a good video on setting this up. [https://www.youtube.com/watch?v=GF6ZGKOuzhY](url).

**Comment by emailcraigs** [comment]
I see this line:

#define Z_MIN_ENDSTOP_INVERTING (ANYCUBIC_PROBE_VERSION + 0 == 1) // V1 is NO, V2 is NC

I didn't think It needed any modification because I had already stipulated "ANYCUBIC_PROBE_VERSION 2" earlier. Its not clear to me what needs to be modified. I have version 2, so should it be "+ 0 == V2" or "+ 0 == 2"  Sorry If I'm being daft.

**Comment by FlailAway** [comment]
"Daft," is OK, all too often that way myself. :) Just the single digit "2" is correct as the "V2" would throw a compile error but do no damage as you could never upload it. As you have "ANYCUBIC_PROBE_VERSION 2" defined that should take care of that. 

Did follow DaHai's video?

Also, Bi-Linear is a better option than UBL IMHO.

**Comment by emailcraigs** [comment]
I originally followed DaHai's video using Bi-linear and my mesh came out like this:

Bilinear Leveling Grid:
 READ: 0 1 2 3 4 5 6
 READ: 0 +336.908 +340.423 +319.195 +191.565 +212.797 +269.575 +310.879
 READ: 1 +340.294 +287.094 +287.097 +287.097 +287.097 +287.096 +350.783
 READ: 2 +318.615 +287.090 +287.088 +286.848 +286.844 +286.844 +382.631
 READ: 3 +191.135 +286.481 +286.484 +286.484 +286.849 +286.848 +286.847
 READ: 4 +212.002 +286.478 +286.478 +286.340 +286.342 +286.340 +254.751
 READ: 5 +268.457 +286.029 +286.030 +286.033 +286.338 +286.340 +264.943
 READ: 6 +309.238 +349.170 +381.119 +286.026 +254.285 +265.073 +279.111

ReaLLY Weird and not level at all. 

So I was trying UBL. This made me wonder if I was missing putting in an offset for the probe. Looking at the Configuration.h it seems that I did use ANYCUBIC_PROBE_VERSION 2 which should plug into the rest of the config and set the offset and Z_MIN_ENDSTOP_INVERTING automatically. So, I'm not sure what is going wrong.  Are saying that I should have this line:

#define Z_MIN_ENDSTOP_INVERTING (ANYCUBIC_PROBE_VERSION + 0 == 2) // V1 is NO, V2 is NC

and not what is there by default looking like this:

#define Z_MIN_ENDSTOP_INVERTING (ANYCUBIC_PROBE_VERSION + 0 == 1) // V1 is NO, V2 is NC

Based on the coding I thought it would work out to be "2+0 ==1 and thus come out to be FALSE which would then, based on the bottom line of code in that section result in:

Z_MIN_ENDSTOP_INVERTING FALSE

This would jive with it being a Version 2 probe.

**Comment by FlailAway** [comment]
It looks like your Z-end stop logic needs inverting. Those big numbers "336.908" suggest it is starting to probe then seeing the switch "triggered" and thinking that's already at the bed.

With it turned off, move the Z (all 3 sliders) down about 4" from the top then turn it on. Use the Arduino Console to send M119. Then hold the probe switch closed with a finger and send the M119. Hold the probe-switch closed the entire time until it prints the result.

Post those two sets of results here.

**Comment by emailcraigs** [comment]
M119 command by itself:

Reporting endstop status
x_max: open
y_max: open
z_min: open
z_max: open
ok


M119 command while holding switch up
Reporting endstop status
x_max: open
y_max: open
z_min: TRIGGERED
z_max: open
ok

**Comment by emailcraigs** [comment]
Interesting thing happened on the way to Albuquerque......When I did the M119 command I was like what the hey lets just tell it to level again and see what happens. I got this:

Bilinear Leveling Grid:
      0      1      2      3      4      5      6
 0 +6.682 +6.794 +6.345 +3.787 +4.222 +5.323 +6.110
 1 +6.667 +5.657 +5.695 +5.679 +5.682 +5.654 +6.973
 2 +6.259 +5.583 +5.586 +5.643 +5.700 +5.719 +7.649
 3 +3.751 +5.614 +5.551 +5.636 +5.689 +5.697 +5.754
 4 +4.163 +5.568 +5.532 +5.638 +5.694 +5.739 +5.113
 5 +5.266 +5.599 +5.560 +5.589 +5.655 +5.662 +5.310
 6 +6.072 +6.777 +7.372 +5.522 +4.978 +5.230 +5.540

I saved the mesh. Then I tried to print a spiral level test and it seems to be printing about 5.5 or 5.6 mm above the bed. I checked my delta height and z-probe offset and they are still correct. My current config has the probe offset at 13.2, the bugfix1.1 config for anycubic has it at 16.8, Da Hai's config has it as 14.2 and I measured mine and came up with 15.8. Things always seem to get more interesting for me. LOL.

**Comment by emailcraigs** [comment]
If I put the probe on, Home it, and then bring it down until I hear it click....I am 10.2mm away from 0.00. I can't see a correlation between any of the proscribed offsets and the mesh data points I'm getting. So, I have a mesh, I can print, but the spiral pattern I print shows uneven first layer in several areas. How do you read the mesh data points? Which one is the center of the bed?

**Comment by boelle** [comment]
@FlailAway problem solved?

**Comment by emailcraigs** [comment]
I switched to 1.1.9 and UBL. Everything works good if you do it manually from a console connection, and I have not looked back.

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
