### ISSUE TITLE
[bugfix-2.0.x] UBL + MANUAL_HOME_POSSITION

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#12925]
Seems like i have misubderstanding of ubl. In my case endstops doesnt correspond to bed corners. So they are actualy at

```
#define MANUAL_X_HOME_POS -35
#define MANUAL_Y_HOME_POS 380
#define MANUAL_Z_HOME_POS 442
```

bed parameters

```
// The size of the print bed
#define X_BED_SIZE 380
#define Y_BED_SIZE 380

// Travel limits (mm) after homing, corresponding to endstop positions.
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0
#define X_MAX_POS X_BED_SIZE
#define Y_MAX_POS Y_BED_SIZE
#define Z_MAX_POS 445
```

So when i trying to home and start ubl (possibly because of recent changes in ubl) then ubl starts probbing outside of bed.

**Comment by gloomyandy** [comment]
Have you tried setting X_MIN_POS to -35? That's how I would expect to set things up for a system that has a bed smaller than the travel area.

**Comment by shitcreek** [comment]
@alexxy Were you ever able to resolve this issue? If so, what was your solution and please consider closing this issue. Thanks.

**Comment by boelle** [comment]
@alexxy problem solved?
