### ISSUE TITLE
anycubic on 1.1.9 generating weird high number mesh

### ISSUE THREAD

**Issue by emailcraigs** [MarlinFirmware/Marlin#12924]
### Steps to Reproduce

1. Prepare
2. Bed Leveling
3. Level bed

**Expected behavior:** Generation of mesh to level build plate

**Actual behavior:** Weird mesh is generated and calibration print shows high and low areas. Here is the mesh:

Bilinear Leveling Grid:
READ:       0      1      2      3      4      5      6
READ:  0 +336.908 +340.423 +319.195 +191.565 +212.797 +269.575 +310.879
READ:  1 +340.294 +287.094 +287.097 +287.097 +287.097 +287.096 +350.783
READ:  2 +318.615 +287.090 +287.088 +286.848 +286.844 +286.844 +382.631
READ:  3 +191.135 +286.481 +286.484 +286.484 +286.849 +286.848 +286.847
READ:  4 +212.002 +286.478 +286.478 +286.340 +286.342 +286.340 +254.751
READ:  5 +268.457 +286.029 +286.030 +286.033 +286.338 +286.340 +264.943
READ:  6 +309.238 +349.170 +381.119 +286.026 +254.285 +265.073 +279.111

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.
[config files.zip](https://github.com/MarlinFirmware/Marlin/files/2762614/config.files.zip)

**Comment by emailcraigs** [comment]
Sorry. Anycubic Delta Kossel Linear Plus.

**Comment by boelle** [comment]
@emailcraigs problem gone in bugfix 2.0?

**Comment by emailcraigs** [comment]
Not sure. I'm using 1.1.9 with UBL and just building the mesh via console connection. I find the LCD command stuff to work erratically.

**Comment by boelle** [comment]
use bugfix 2.0

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
