### ISSUE TITLE
[bugfix-2.0.x] ULTRA_LCD + REPRAP_DISCOUNT_SMART_CONTROLLER is buggy

### ISSUE THREAD

**Issue by mordaha** [MarlinFirmware/Marlin#12937]
### Description

I connected standard  RepRap Smart LCD Controller to my DUE_USB+RURAMPS4D_13 (Marlin bugfix-2.0.x 32 bit) with this config:

```
#define REPRAP_DISCOUNT_SMART_CONTROLLER

#define ULTRA_LCD
#define NEWPANEL
#define LCD_WIDTH 20
#define LCD_HEIGHT 4
```

And it didn't work, it showed 2 strings of trash, something like this: https://i.imgur.com/RtGtHNw.png 

I debugged a little through the code and found that `LiquidCrystal lcd()` somehow initialized wrong or not initialized at all.

So, here, at L900 (https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/HD44780/lcdprint_hd44780.cpp#L900) in `lcd_put_wchar_max()`, `lcd.` is useless (pointing to a wrong device, not my?).

I added initialisation (hack) just before that `if`:
```  
  // initialize lcd()
  LCD_CLASS lcd(LCD_PINS_RS, LCD_PINS_ENABLE, LCD_PINS_D4, LCD_PINS_D5, LCD_PINS_D6, LCD_PINS_D7); 

  // TODO: fix the '\\' that doesnt exist in the HD44870
  if (c < 128) {
    lcd.write((uint8_t)c);
    return 1;
  }
```
And it started to work fine, as expected: https://i.imgur.com/incMr9w.png

I didn't debug through that lot of `#if ENABLED() -> #define` symbols, so i don't know where exactly the buggy code is, but i think it somewhere in defines/configs. May be lcd_i2c config somehow fired.

My full Configuration.h: https://pastebin.com/Q6J85X2k

How else can i help?

**Comment by gloomyandy** [comment]
I'm not sure if this is causing any of your problems but you should not have to define:
```C
#define ULTRA_LCD
#define NEWPANEL
#define LCD_WIDTH 20
#define LCD_HEIGHT 4
```

Normally just defining REPRAP_DISCOUNT_SMART_CONTROLLER should be enough, all of the other defines should get set automatically if they are required. Was there a reason for adding them explicitly?

**Comment by mordaha** [comment]
I googled it before install but i didn't find in code where REPRAP_DISCOUNT_SMART_CONTROLLER defines ULTRA_LCD, without UTRA_LCD it just not defines any pins (https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/pins_RURAMPS4D_13.h#L189)

my bet - the devil in defines, i am sure)

**Comment by mordaha** [comment]
(translating): with only #define REPRAP_DISCOUNT_SMART_CONTROLLER  it do nothing

**Comment by gloomyandy** [comment]
You should look at Conditionals_Lcd.h
If you look through that you should be able to see what gets defined. You really should not have to define the individual components.

**Comment by mordaha** [comment]
Again, i started from that point.
At first I defined only REPRAP_DISCOUNT_SMART_CONTROLLER and it didn't work. Blank screen.

**Comment by gloomyandy** [comment]
Yes I understand that, but that does not mean you need to define those settings to get things working. It is more likely that there is a problem with the pins file for your board and that the pins are not set correctly for the display you are trying to use.

**Comment by mordaha** [comment]
There is definitely bug in configs so i opened this issue!

**Comment by gloomyandy** [comment]
The thing you need to remember is that you are trying to use a new version of Marlin with new 32bit hardware. This new version does not always support all of the same displays etc. that the older 8 bit version did on all of the different control boards. In this case I suspect that no one has actually implemented support for the display you are trying to use on the control board you have.

In some cases (like the smoothieboard based boards (like MKS Sbase), it may be that it is simply not possible to support some of the displays. I'm not sure if that is the case with your hardware, but in the case of the MKS SBase board (which I'm more familiar with), the control board simply does not have connections from the cpu to the connectors used for the display for some of the signals required by a display like the one you are trying to use. But other displays (like the RepRapDiscount Full Graphic Smart Controller), which require different signals work fine. It may be that you need to use a different type of display with the control board you have chosen.

**Comment by mordaha** [comment]
I dont wanna somewhat hate you pal! ) i did it work and think that my experience will help you! nothing more) 
it works for me so i'd like to find the core of a problem with you to help all others users, plz don't hate me too!
I can do any experiments for you service!

**Comment by gloomyandy** [comment]
As I said you really should not have to set those defines yourself. How old is the 2.0.x you are using? Looking at the current code as far as I can see if you define REPRAP_DISCOUNT_SMART_CONTROLLER then the code in Conditionals_LCD.h should be defining ULTRA_LCD and NEWPANEL for you. In this file we have the following lines:
```C
#if ENABLED(ULTIMAKERCONTROLLER)              \
 || ENABLED(REPRAP_DISCOUNT_SMART_CONTROLLER) \
 || ENABLED(G3D_PANEL)                        \
 || ENABLED(RIGIDBOT_PANEL)                   \
 || ENABLED(ULTI_CONTROLLER)
  #define ULTIPANEL
#endif
```
then later in the same file there is
```C
#if ENABLED(ULTIPANEL)
  #define NEWPANEL  // Disable this if you actually have no click-encoder panel
  #define ULTRA_LCD
#endif
```
So as far as I can see ULTRA_LCD and NEWPANEL should be defined. So if you have the time the thing to understand is why they are not defined for you.

**Comment by mordaha** [comment]
Yes yes you are right, ULTRA_LCD is not an issue.
The screen shows blank or 2 strings of trash randomly after power on. This was confused me

The chronology was:
1. I set REPRAP_DISCOUNT_SMART_CONTROLLER and saw blank screen
2. I set ULTRA_LCD and saw 2 strings of trash - progress! (but this was random event)
3. I uploaded "hello world" sketch to check if pins are correct - screen shows "hello world" - pins are correct
4. I found the place in the code where marlin actually prints to the screen and added "initialization" of `lcd`: 
`LCD_CLASS lcd(LCD_PINS_RS, LCD_PINS_ENABLE, LCD_PINS_D4, LCD_PINS_D5, LCD_PINS_D6, LCD_PINS_D7);` 
right before that place  - voila, it works! 
If i remove this "initialization" - screen become blank or trashy.

My marlin is at 5f2d75f45b558c1eeeb18b commit

**Comment by gloomyandy** [comment]
It may be worth getting a more recent version of 2.0.x. You never know there may have been a bug introduced and fixed.

**Comment by claymore666** [comment]
Forgive me to hook into that conversation, but I think I have stumbled across a related issue and I too am thinking there is something wrong in the config.
I am trying to get an MKS GEN L running with Marlin 1.1.9 and the Ender 3 (ie CR10_STOCKDISPLAY to my knowledge) up and running - with one ribbon cable.

When reviewing the pinout I discovered that 
_#define CR10_STOCKDISPLAY_ will never set any pins for me as the _pin_ramps.h_ states:

`
#if ENABLED(ULTRA_LCD)
  //
  // LCD Display output pins
  //
  #if ENABLED(REPRAPWORLD_GRAPHICAL_LCD)

	...
  #elif ENABLED(NEWPANEL) && ENABLED(PANEL_ONE)

    ...
  #else
    #if ENABLED(CR10_STOCKDISPLAY)
      #define LCD_PINS_RS       27
      #define LCD_PINS_ENABLE   29
      #define LCD_PINS_D4       25

		...
    #endif

  #endif
`
Is it intentional to have set ULTRA_LCD in order to use CD10_STOCKDISPLAY? I guess thats also where @mordaha  is comming from...

**Comment by boelle** [comment]
@mordaha problem solved?

**Comment by mordaha** [comment]
"And it started to work fine, as expected: https://i.imgur.com/incMr9w.png"

for me - yes, not for marlin sources

**Comment by Miran81** [comment]
@mordaha  how it works ? photo links broken. I'm using due+ramps-fd and 2004 lcd. Lcd is not working. Just squares on screen.

**Comment by boelle** [comment]
> "And it started to work fine, as expected: https://i.imgur.com/incMr9w.png"
> 
> for me - yes, not for marlin sources

are you sure the problem is still here with todays copy of bugfix 2.0? have you tested?

your copy of marlin 5f2d75f is almost 3 months old now and its updated daily sometimes 2-3 times each day

**Comment by Miran81** [comment]
@boelle  ı think its about ULTRA_LCD but ı don't know

**Comment by mordaha** [comment]
>are you sure the problem is still here with todays copy of bugfix 2.0? have you tested?

i can in git ))

<img width="554" alt="image" src="https://user-images.githubusercontent.com/800239/54073476-9263ff80-4298-11e9-9392-9d6079306664.png">

**Comment by mordaha** [comment]
>@boelle ı think its about ULTRA_LCD but ı don't know

i think the problem is in that lot of defines, somewhere they are failed, but i don't know how to debug it :(

**Comment by Miran81** [comment]
@boelle you sad your lcd is work fine. How ?

**Comment by boelle** [comment]
my full graph display on re-arm+ramps ??

yes works fine

**Comment by Miran81** [comment]
@mordaha you sad work fine. How ? I have ramps-fd+due 2004 lcd

**Comment by mordaha** [comment]
@Miran81 i had explained it in the first message)

just added an initialization of lcd in the print function

**Comment by Miran81** [comment]
@mordaha can you share configuration.h please :)

**Comment by Miran81** [comment]
@mordaha i did it   // initialize lcd()
  LCD_CLASS lcd(LCD_PINS_RS, LCD_PINS_ENABLE, LCD_PINS_D4, LCD_PINS_D5, LCD_PINS_D6, LCD_PINS_D7);  and look at picture
![ramps-fd 2004 lcd](https://user-images.githubusercontent.com/48278092/54076998-7de92c80-42c3-11e9-90b8-149622917ead.jpeg)

**Comment by Miran81** [comment]
problem solved thank u all  💯  👍 👍 👍
