### ISSUE TITLE
[help-wanted] Trying to add i3plus board

### ISSUE THREAD

**Issue by killerm1** [MarlinFirmware/Marlin#12933]
Hi, I trying to adapt a i3 plus board to be used with this firmware dual end stop. I have remapped the end stop pins but cannot figure out how the remap the steppers. any help would be appreciated. link to pins.h https://github.com/andrivet/ADVi3pp-Marlin/blob/advi3%2B%2B/Marlin/pins_I3_PLUS.h

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone
