### ISSUE TITLE
Z probe past Bed

### ISSUE THREAD

**Issue by Cragster25** [MarlinFirmware/Marlin#12931]
I have looked through YouTube videos and other posts trying to fix my problem.

I have recently added a probe to my Anet A8 and was going through all the configuration.h changing what I needed to but after uploading and trying to auto home I got the error Z probe past bed. Would someone please tell me whats wrong, attached if my configuration.h file.
[config_h.txt](https://github.com/MarlinFirmware/Marlin/files/2765925/config_h.txt)

**Comment by Ludy87** [comment]
`#define Y_PROBE_OFFSET_FROM_EXTRUDER -147   // Y offset: -front +behind [the nozzle]`

far as the probe can not be gone.

**Comment by Cragster25** [comment]
The probe is in front of the extruded so isn’t that needed.

**Comment by GMagician** [comment]
Try RIGHT_PROBE_BED_POSITION 209 and BACK_PROBE_BED_POSITION 209
because I think probe can't reach 220 since you have X_PROBE_OFFSET_FROM_EXTRUDER 10 and Y_PROBE_OFFSET_FROM_EXTRUDER 10

**Comment by Cragster25** [comment]
It hasn’t got to that stage yet, it gets to homing X & Y but then comes up with the error for Z probe past bed.

**Comment by GMagician** [comment]
Sorry for previous wrong post but since your probe is 147mm in front (y side) you can probe only 220-147 in Y

**Comment by Cragster25** [comment]
Yeah that I mistyped it was only 47mm

**Comment by Cragster25** [comment]
I think it was my mistyped number as it have now homed.

**Comment by GMagician** [comment]
That's the same max is 220 and you can't probe at 210 with 47mm displacement

**Comment by shitcreek** [comment]
Please close issue if it is resolved. Thanks.
