### ISSUE TITLE
Unknown command: "M122"

### ISSUE THREAD

**Issue by sponge14** [MarlinFirmware/Marlin#12942]
I have set my XYZ and E0 driver types to TMC2208 in configuration.h  I have read where I am supposed to uncomment a line that says HAS_TRINAMIC, or something like that, but I cannot find that line in the latest 2.0 code.  If found HAS_TRINAMIC already defined in the Drivers.h file.

I am using a RE-Arm board with a RAMPS 1.6 board

When I try to send an M122 in Octorprint, I get the error Unknown command: "M122"

It seems the code is different now than has worked in the past?  Or am I just missing something here?

[Configuration - Copy.txt](https://github.com/MarlinFirmware/Marlin/files/2771589/Configuration.-.Copy.txt)
[Configuration_adv - Copy.txt](https://github.com/MarlinFirmware/Marlin/files/2771590/Configuration_adv.-.Copy.txt)

**Comment by Msq001** [comment]
uncomment #define TMC_DEBUG in Configuration_adv.h

**Comment by sponge14** [comment]
TMC_DEBUG was already uncommented and enabled, sorry I missed saying that earlier.

**Comment by teemuatlut** [comment]
`TMC2208_STANDALONE` tells Marlin that you do **not** have the communication lines wired to the driver and wish to run the driver in standalone mode. This only tunes the pulse timings to be suitable with the driver but does not enable any of the commands or features supported by the firmware, such as `M122`.

If you have wired the communication lines to the driver(s), use the correct option `TMC2208`.

> I have read where I am supposed to uncomment a line that says HAS_TRINAMIC

Don't do that.

> uncomment #define TMC_DEBUG in Configuration_adv.h

If running latest bugfix-2.0.x this is no longer necessary for `M122`.

**Comment by shitcreek** [comment]
@sponge14 Did you manage to resolve this issue? If so, what were your procedures and please considering closing the issue. Thanks.

**Comment by sponge14** [comment]
No, I haven't yet been able to resolve the issue.

**Comment by boelle** [comment]
@sponge14 problem solved in bugfix 2.0?
