### ISSUE TITLE
[bugfix-2.0.x] Power loss recovery with PSU control

### ISSUE THREAD

**Issue by Titi9237** [MarlinFirmware/Marlin#12945]
Hi,

### Description
I just tried the Power loss recovery option using a MKS220v DET. I also have the PSU control option. 
It is detecting a powerloss as expected but when I put the power back on, I can choose to restart the print but it does not restart the PSU.

Does anybody has an idea to solve this ?

I have my own Prusa I3 style printer with a Arduino/Ramps board and I am using the last version of Marlin bugfix-2.0

**Comment by Grogyan** [comment]
How is your power supply wired?
What Power supply are you using?
Are you using the PS_ON via a transistor if using a ATX Power Supply?

**Comment by Titi9237** [comment]
If is a Corsair 550W power supply with the green wire connected to the PS_ON pin.
I enabled the PSU_Default_Off option.

**Comment by boelle** [comment]
@Titi9237 problem solved?

**Comment by Titi9237** [comment]
Nope, but I have not tried the function since then.

**Comment by boelle** [comment]
maybe give it a go with latest copy of 2.0?

**Comment by AnHardt** [comment]
Maybe fixed by https://github.com/MarlinFirmware/Marlin/commit/89bbc30a09b854c1fa20f63113a92c33df65e19a

**Comment by Titi9237** [comment]
In theory, it seems to be the solution. Thanks !
But I will not be able to test it for the moment.
You can close the issue if necessary.

**Comment by boelle** [comment]
we cant close, only you and @thinkyhead can do so
