### ISSUE TITLE
[FR] MK3 runout sensor

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#12958]
Soon (maybe a week) I'll get a sensor and I'm going to implement it...that's a big challenge to me but how knows...

I'm here to ask to "Best marlin guys" what it's better approach.
I don't know how MK3 firmware does it but for sure it's far from current Marlin runout implementation.
I may try do follow 2 paths:
1) include MK3 code as indepented runut logic and adapt it to Marlin;
2) include MK3 adapting it to current Marlin implemented logic (I'm thinking about something like encoder sensor)

MK3 sensor uses i2c bus (SDA & SCL) so I think an interrupt to handle communication but despite of this everything else may safely follow 'FilamentSensorEncoder' like class logic

What do you think?

**Comment by dcwalmsley** [comment]
@Giuliano Zaro,

I recently incorporated Prusa's MMU2 upgrade kit to my HyperCube Core XY 
printer and with the help of @Revilor and @Ruud Rademaker's information I 
have the ability to reset MMU, and properly feed my specific PTFE tubing 
(565mm) for loading to and extracting from the direct-drive extruder.  What 
I need now is what you wrote, code to enable the optical sensor using 
(5vdc, Gnd, SDA, and SCL) to sense the filament for filament runout (M600).

I would be grateful if Devs could look into code to enable this feature or 
a work-around solution.

Best Regards,
Doug Walmsley

**Comment by GMagician** [comment]
@dcwalmsley I haven't wrote a single code line till now ;-)
I'm going to write something as soon as sensor will arrive.

Mine was just a hint request to know how to start to do that.
Currently Marlin runout support FILAMENT_RUNOUT_DISTANCE_MM to delay runout action, MK3 not (I think) so I'm wondering if MK3 implementation should just does what MK3 does or a full integration with current Marlin logic.

By the way I don't know if multi sensor is possible, sensor hasn't CS pin and I don't know if in protocol there is an "address" data.

**Comment by GMagician** [comment]
Move discussion to PR
