### ISSUE TITLE
G29 H - Asking just for a check

### ISSUE THREAD

**Issue by MasterPIC** [MarlinFirmware/Marlin#12968]
Hi,

G29 H (please refer directly to #12242 and #12610) probing works as expected.
But **I'm not sure** left and front (starting) probe positions and grid size (in mm) are stored/restored by M500/M501.
I found no commands to ask the printer to report starting probe positions and grid size. So I'm not sure the grid, after being stored to EEPROM, is still valid (within the area it should cover and limited to) if the printer has been switched off.

I'd appreciate a confirmation.

Thanks
Armando

**Comment by RudyBenner** [comment]
M115 will spit out some of what you need. You get to decode it yourself.

**Comment by MasterPIC** [comment]
I think M115 doesn't report the required info.
I just opened a new feature request: #12979

**Comment by MasterPIC** [comment]
In the meantime I found by myself that
bilinear_start[X_AXIS]
bilinear_start[Y_AXIS]
bilinear_grid_spacing[X_AXIS]
bilinear_grid_spacing[Y_AXIS]
are properly stored to (and restored from) EEPROM.
