### ISSUE TITLE
Dual Extruder : Heating coils and Motors Turn OFF

### ISSUE THREAD

**Issue by athulsnair** [MarlinFirmware/Marlin#12977]
### Description

Today I connected a Dual extruder to my printer. 
Control board: Arduino Mega + Ramps 1.4
Marlin version: 1.1.6

As a test print, tried to print two cubes. One assigned to Extruder 1 and other to Extruder 2. Print temperature for both extruder is 205 C. After starting the print, extruders are heating, and after a while printer stops. I mean, power to stepper motors turns OFF, Heating coil power turns OFF(LEDs indicating heating in Ramps). After a while an error window appears "**Error: Heating failed**". It shouldn't happen as I could see the temperature of both extruders are increasing. When working with single extruder(either Extruder1 or 2), this issue not happens. But when working with two extruder it happens. I have tried several times, let the extruders cool to room temperature then start the print. Sometimes it happens in the middle of print, after 1st layer.

### Steps to Reproduce

1. Place Two models in Repetier host
2. Assign each extruder to each model
3. Start print

**Expected behavior:** [What you expect to happen]

Extruder heats to given temperature and start printing

**Actual behavior:** [What actually happens]

Motors and heating coil turn off. **Error: Heating failed** error message after a while 

#### Additional Information

Video link: [https://drive.google.com/open?id=1uuigua2GWE2z0YK2kHFe-q2il40ATZdu](url)

Marlin files : 
[Marlin-1.1.x-20190121T095821Z-001.zip](https://github.com/MarlinFirmware/Marlin/files/2778458/Marlin-1.1.x-20190121T095821Z-001.zip)
Slic3r Config: 
[SLic3r-20190121T100343Z-001.zip](https://github.com/MarlinFirmware/Marlin/files/2778463/SLic3r-20190121T100343Z-001.zip)

In this video when Extruder 2 reaches around 150 C, motors and heating coil turn OFF

**Comment by AnHardt** [comment]
Are you sure your power supply is able to heat two hotends at the same time equally fast than one?
If not relax the parameters:
```
   * If you get false positives for "Heating failed", increase WATCH_TEMP_PERIOD
   * and/or decrease WATCH_TEMP_INCREASE. WATCH_TEMP_INCREASE should not be set
   * below 2.
   */
  #define WATCH_TEMP_PERIOD 20                // Seconds
  #define WATCH_TEMP_INCREASE 2               // Degrees Celsius
```

**Comment by kAdonis** [comment]
The 5 A polyfuse on the RAMPS may trip and cut the power

**Comment by athulsnair** [comment]
> The 5 A polyfuse on the RAMPS may trip and cut the power

They are getting heat though
How to confirm it?
If that's the issue how to solve?

**Comment by athulsnair** [comment]
> Are you sure your power supply is able to heat two hotends at the same time equally fast than one?
> If not relax the parameters:
> 
> ```
>    * If you get false positives for "Heating failed", increase WATCH_TEMP_PERIOD
>    * and/or decrease WATCH_TEMP_INCREASE. WATCH_TEMP_INCREASE should not be set
>    * below 2.
>    */
>   #define WATCH_TEMP_PERIOD 20                // Seconds
>   #define WATCH_TEMP_INCREASE 2               // Degrees Celsius
> ```

https://drive.google.com/open?id=1B0QhMxM7rf5rW_ZS4d5J1sufTolt2nef

Isn't this fast enough??

**Comment by kAdonis** [comment]
> They are getting heat though
> How to confirm it?

you could measure with a multimeter

> If that's the issue how to solve?

you could replace the polyfuse with an automotive fuse
https://reprap.org/forum/read.php?219,433454

**Comment by athulsnair** [comment]
> > They are getting heat though
> > How to confirm it?
> 
> you could measure with a multimeter
> 
> > If that's the issue how to solve?
> 
> you could replace the polyfuse with an automotive fuse
> https://reprap.org/forum/read.php?219,433454

My Heating coil resistance is around 4.9 ohm. So when connected to a 12V supply,  it's gonna draw 2.45A , two coils combined around 5A. 
Measured current is 6.9 A (Heating coils + Motors)
This might be overheating the Fuse in time and tripping the circuit. So I need a fuse with trip current above 7 A. I don't know whats the trace width in RAMPS for the heating coil, What would be the safe current??

**Comment by athulsnair** [comment]
@kAdonis Thanks, it was the issue with the poly fuse. I couldn't find a higher current one. Since i'm not using heat be, I interchanged the poly fuses. Now 11 A one is supplying current to motors and heating coil. Total current drawn is 7 A.

First I thought it might be a bug. That's why I posted here. 
Thanks for all the help. Closing this now
