### ISSUE TITLE
cool down after print stop

### ISSUE THREAD

**Issue by Thowra** [MarlinFirmware/Marlin#12976]
hi,
My colleague uses your printer like this:

Starts printing from the LCD menu, head and bed heating starts.
He immediately Stop print from LCD menu.
He remove SD card.
He copy new files to the card.
He insert the SD card.
He start new print.

The essence is that as long as you copy the files it will heat up the machine.
It is easier and faster than find the preheat option as a menu.
It works with older versions, but not works with Marlin 1.1.8.
The Marlin 1.1.8 cool down head and bed after he select "stop print" option.
How to solve this problem?

**Comment by ghost** [comment]
**ironic mode on**
I used to use my cars handbrake to initiate a nice drifting rear wheel powerslide. My new car now has an electro-hydraulic handbrake, so no more powerslides. How to solve this problem?
**ironic mode off**

I wonder, if the controller has some pins left over, one could think about a [FR] to be able to assign a user defined list of GCODES to a pushbutton?

I would also perhaps use that for preheating or for extrude 10mm or somethings like that and I have enough places near the display, where I could fit a few buttons.

**Comment by Thowra** [comment]
hi,
Good analogy
The push button is a good idea. 
I'll see where to connect.
The machine use Ramps 1.4 and Arduino (some free pins).
Is there a similar function in Marlin (external button)?
How to define external button in the Marlin?

**Comment by boelle** [comment]
or does marlin support setting a cool down temp?

M109 R30 to cool down to 30

**Comment by boelle** [comment]
if you read this page: https://github.com/MarlinFirmware/Marlin/wiki/M109

then M109 R30 would make things wait until it reaches that temp

**Comment by Thowra** [comment]
No external push button installation yet (I was no time to read how to can insert external button option in the Marlin.).
I turned on "custom commands", I resolved the issue temporarily.

**Comment by boelle** [comment]
@Thowra still working on this?

**Comment by Thowra** [comment]
Yes, but it doesn't work yet.

**Comment by boelle** [comment]
what version of marlin do you use?

**Comment by Thowra** [comment]
I use V2.0

**Comment by boelle** [comment]
ohh, my mistake

i read your first post and now i understand

this should be seen as a feature reqest

maybe close this issue and open a new one with title: [FR] Assign button to function

then in text of new issue write:

I would like to be able to attach a push button and assign functions to it, like preheat and cooldown of bed/nozzle
