### ISSUE TITLE
[bugfix-2.0.x] FR to improve ABL report

### ISSUE THREAD

**Issue by MasterPIC** [MarlinFirmware/Marlin#12979]
I think the user should be able to get:

bilinear_start[X_AXIS]
bilinear_start[Y_AXIS]
bilinear_grid_spacing[X_AXIS]
bilinear_grid_spacing[Y_AXIS]

I may be wrong but, on my Anet A8 with ABL enabled, I'm not able to get them. So I cant' check if the ABL grid loaded from EEPROM is to be replaced by a new one...

**Comment by gloomyandy** [comment]
This may be the best solution, but you never know there may be a better one, so could you please describe the problem you are trying to solve here? Why do you need to check if the grid can be replaced? What is it that needs to check (a program running on a PC? A user making use of an attached display?)?

**Comment by MasterPIC** [comment]
I prefer to use an ABL grid limited to the area required by the print. Then I store the grid to EEPROM to be able to reuse it.
But if a bigger print is required I need a new probing.
So I need to know the area covered by current ABL grid to figure out if it's still good on next print...

I could obviously store a grid that covers the entire printing area but I prefer to use a small grid spacing and to limit probing points to speed up probing.

**Comment by MasterPIC** [comment]
There is also another reason why I'm asking for this feature: I use the nozzle itself as a probe since I print directly on PCB (I use a PCB in place of glass to cover the entire hotbed). This solution obliges to keep the PCB clean to make probing working.
Current ABL grid can be visualized (e.g by Octopront bed visualizer plugin) to quickly detect if something went wrong during probing (i.e. a probing point unexpectedly lower than the others in the probing mesh). If I don't know the real position of that probing point on the hotbed I don't know where PCB is to be cleaned...

**Comment by gloomyandy** [comment]
Wouldn't you save more time in the long run by just probing the entire bed with a reasonable number of points and saving that?

I use UBL that way and hardly ever need to reprobe.

But I suppose that given that ABL has all of those options to set the position of the grid etc. it makes sense to have a way of retrieving them. I guess the question then is should it be via G29 T (which makes sense to me), or some other means (like the EEPROM report?).

**Comment by MasterPIC** [comment]
I just added the following code 
```
SERIAL_ECHOLNPGM("xmin:");
SERIAL_ECHOLN(bilinear_start[X_AXIS]);
SERIAL_ECHOLNPGM("ymin:");
SERIAL_ECHOLN(bilinear_start[Y_AXIS]);
SERIAL_ECHOLNPGM("x_spacing:");
SERIAL_ECHOLN(bilinear_grid_spacing[X_AXIS]);
SERIAL_ECHOLNPGM("y_spacing:");
SERIAL_ECHOLN(bilinear_grid_spacing[Y_AXIS]);
```
after

`print_bilinear_leveling_grid();`

in M420.ccp

and it works.
Surely a better solution is advisable.

**Comment by boelle** [comment]
maybe submit a PR to bugfix 2.0?

**Comment by MasterPIC** [comment]
I'm not sure it's the best solution.

**Comment by boelle** [comment]
i read the first post again, and i think that its a bit "overkill"

there is not reason to limit probing to just the area you print, in fact the bigger area the better

**Comment by boelle** [comment]
missing label
