### ISSUE TITLE
[2.0] missing acceleration on shorter manual movements

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#12980]
I just realized something odd: When I move the Z axis by 100mm, I can clearly hear the sound of the steppers when they accelerate or decelerate. But when I move the Z axis by 10 or 1 mm, there is no acceleration sound. It appears as if the motor goes to its target speed instantaneously.
(Edit:) x and y are affected as well. 100mm is smooth, 10 and 1 causes the printer to shake.
Can anyone reproduce this?

Steps per unit: 1200 (spindle driven lift with belt)
Max Feedrade: 10
Max Acceleration:  60
S-Curve and Junction deviation: off
Step smoothing: on

Firmware: pulled and compiled just an hour ago.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2779954/Configuration.zip)

**Comment by boelle** [comment]
@hamster65 problem solved?

**Comment by thinkyhead** [comment]
A start and a stop within a short interval is bound to cause more juddering than a start, long move, and gradual stop. The solution is to do shorter moves at a slower nominal feedrate so they have adequate time to produce an acceleration curve.
