### ISSUE TITLE
Support ino or another build+upload method

### ISSUE THREAD

**Issue by alhirzel** [MarlinFirmware/Marlin#1299]
I would like to use [ino](http://inotool.org) or another console tool to build Marlin, perhaps this can be achieved with ino by creating another folder under the ArduinoAddons folder and using the `--arduino-dist` option. Mostly I'd like to be separate from the Arduino IDE.

Has anyone gotten this working with ino or another tool?

**Comment by galexander1** [comment]
I've never used the Arduino IDE, and just use make with the Makefile that
already ships with Marlin...

**Comment by alhirzel** [comment]
Ah, I figured that was autogenerated/not to be used. Is the Makefile the workflow most people use?

**Comment by nophead** [comment]
I use ino.

**Comment by alhirzel** [comment]
@nophead would you mind sharing info on how you set it up?

**Comment by monkeydave** [comment]
To use ino just create a symlink to src folder and remove Marlin.pde like so

ln -s Marlin src
rm Marlin/Marlin.pde

Then build with 
ino build -m (YOUR BOARD TYPE)

**Comment by alhirzel** [comment]
Did this require you to install the Arduino platform add-ons system-wide? I have them installed in ~/sketchbook but ino doesn't seem to pick them up

**Comment by joco-nz** [comment]
I  had to install a number of dependent libraries.  That possibly could have been my ignorance/learning process in getting it working. You can also use an ino config file to tell it board type and USB port for the ino build and upload commands. Saving some typing.

**Comment by gregrebholz** [comment]
On OSX the Arduino IDE comes with avrdude and avr-gcc in the tools/ directory.  I use the Makefile from the command line and update AVR_TOOLS_PATH to point to /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/

**Comment by boelle** [comment]
i use ino too... i simply just open it in Arduino IDE....

but since there has  been no traffic should we not close this one?

**Comment by thinkyhead** [comment]
I'm using UECIDE from now on – and it apparently uses the .ino file.
