### ISSUE TITLE
2.0.x (jan 23) crash on USB print

### ISSUE THREAD

**Issue by Vertabreak** [MarlinFirmware/Marlin#12998]
So i spent about a week trying to figure out this crashing with UBL.
i was using G29 J in my start gcode and doing a pla mesh from the UBL tools menu.
the tests where run on 2 fractal models that are both 50MB STL files the hyper bowl and Dodecahedron.

https://www.thingiverse.com/thing:2994484 full size 0.1 layer height with a brim on cura
https://www.thingiverse.com/thing:27489 30% size 0.1 layer height with a brim on cura

my tests showed a crash reboot would happen around 4-10H mark depending on how much free ram i gave it. with 2kb ram free it crashed around 4-5 hours with 3kb ram free it would last about 10hours then the screen would go all crazy characters and it would restart marlin failing the print. i tried a great many combinations of features thinking maybe it was a conflict. but it still crashed even with the most basic of functions enabled. after a week i gave up and went back to bi-linear it does not crash at all simply switching to bi-linear. if you could look in to whats happening with UBL that would be great i really like the time it saves not needing to probe every single print. this crashing seem to only happen with very complex models like the above 50mb fractal STL files it seems like the complexity speeds up the problem making it show it self. all tests where run on the geeetech a10 and results where repeatable on both my machines as well as members of my discord. i ran testing on UBL nearly 24/7 for an entire week down time only happen when i was sleeping and it crashed.

**Comment by boelle** [comment]
@Vertabreak problem solved?

**Comment by Vertabreak** [comment]
not exactly but i seem to have tracked the cause back to printing from USB as the same thing also happens with or without UBL. when this happens the printer restarts on ttyusb1 and not ttyusb0 like normal. the same files print without issue from sdcard seems to have more to do with printing from USB. tested both front and back usb ports 2.0 and 3.0 ports they all result in the printer resetting eventually when printing for a long time. last time was from the rear ports around the 18 hour mark using bilinear mesh leveling. i do not think its the computers USB ports no other devices plugged in by usb act funny.

**Comment by Vertabreak** [comment]
going to close this one i think i tracked it back to a poor cable connection.
