### ISSUE TITLE
[FR] Documentation of M502 for "Factory defaults" should be more detailed

### ISSUE THREAD

**Issue by DerAndere1** [MarlinFirmware/Marlin#13009]
### Description

The meaning of M502 "Factory reset" / "Factory defaults" should be better described for those who want to adjust configuration.h: An [expanation like in the Wiki](https://github.com/MarlinFirmware/Marlin/wiki/EEPROM) should be added to the comments for the EEPROM-settings in configuration.h as well as to the [manual](http://marlinfw.org/docs/gcode/M502.html).

**Expected behavior:** 

configuration.h should read something like this:
```
//M502 - reverts to the default "factory settings" (coming from the firmware source code as it was uploaded). You still need to store them in EEPROM afterwards if you want to.
```

- The entry for M502 in the manual at http://marlinfw.org/docs/gcode/M502.html should read e.g.:

> M502 - Factory Reset 
> Reset all configurable settings to their factory defaults (coming from the firmware source code as it was uploaded)....

**Actual behavior:** 

- configuration.h only contains a short description:
`//M502 - reverts to the default "factory settings".  You still need to store them in EEPROM afterwards if you want to.
`
- The manual entry for M502 at http://marlinfw.org/docs/gcode/M502.html is equally ill-defined:

> M502 - Factory Reset 
> Reset all configurable settings to their factory defaults....

### ADDITIONAL INFORMATION
Applies to: Marlin 1.1.9, bugfix-1.1.x as well as to bugfix-Marlin2.0

**Comment by AnHardt** [comment]
> coming from the firmware source code as it was uploaded

Sounds to me as if the values are deeply hidden.
How about:
 ..  Coming from the firmwares configuration files.
