### ISSUE TITLE
[Bugfix 2.0.x]  Bed Heating Fails when attempting PID Autotune

### ISSUE THREAD

**Issue by Deneteus** [MarlinFirmware/Marlin#13007]
Is this issue still resolved. [BR] Bed PID Autotune kills Heater Immediately #9005 & M303 Bed PID Autotune fails #12468

I am having an issue with bed heating where it fails not too long after attempting to heat when running PID Autotune in Bugfix 1.1.x from 1/22/19 (files dated 1/10/19).

I used the stock CR-10 configs for the PID initially then tried to changing the hysteresis settings and its still not working correctly. It was working in a previous build from September 2018. These are 2017 CR-10 Stock boards and I have 2 printers exhibiting the same behavior.

Here are my configs: 
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2793607/Marlin.zip)

**Comment by Deneteus** [comment]
I abandoned 1.1.9 and compiled for Bugfix 2.0.x (2,5,2019) and had the same issue using PID Autotune at 240C for just the hot end alone so I re-ran PID Autotune again and got 2 printers to pass but the temp difference is +/- 7 to 10C.

 
![image](https://user-images.githubusercontent.com/6380390/52343320-57428800-29dd-11e9-86ab-d17ac72e2f51.png)


![image](https://user-images.githubusercontent.com/6380390/52343120-d3889b80-29dc-11e9-986b-fc5bfe965b9c.png)

**Comment by AnHardt** [comment]
PID auto-tuning oscillates the temperature around the target temperature by purpose to find the PID parameters.
I guess that's what your picture shows.This does not tell anything about the success of tuning.
Better show us:
```
M117 Waiting for heat up
M109 R240
M117 Holding temperature
M0 S300 
M117 Wating for cooling
M109 R150
M117 Holding temperature
M0 S300 
M117 Waiting for heat up
M109 R240
M117 Holding temperature
M0 S300 
M104 S0
M117 Ready
```

Without M303s  U parameter the new values are not used after the auto-tuning.
Without a M500 or setting them in the config (if EEPROM is off), the new values are lost after a reboot.

**Comment by AnHardt** [comment]
> I am having an issue with bed heating where it fails not too long after attempting to heat when running PID Autotune

How did it fail? What error message? At about what part of the temperature curve?

**Comment by Deneteus** [comment]
> PID auto-tuning oscillates the temperature around the target temperature by purpose to find the PID parameters.
> I guess that's what your picture shows.This does not tell anything about the success of tuning.
> Better show us:
> 
> ```
> M117 Waiting for heat up
> M109 R240
> M117 Holding temperature
> M0 S300 
> M117 Wating for cooling
> M109 R150
> M117 Holding temperature
> M0 S300 
> M117 Waiting for heat up
> M109 R240
> M117 Holding temperature
> M0 S300 
> M104 S0
> M117 Ready
> ```
> Without M303s U parameter the new values are not used after the auto-tuning.
> Without a M500 or setting them in the config (if EEPROM is off), the new values are lost after a reboot.

The error I received when the PID Autotune failed.

Recv: Error:Heating failed, system stopped! Heater_ID: 0
Recv: Error:Printer halted. kill() called!
Changing monitoring state from "Operational" to "Error: Heating failed, system stopped! Heater_ID: 0 - Printer halted. kill() called!"
Changing monitoring state from "Error: Heating failed, system stopped! Heater_ID: 0 - Printer halted. kill() called!" to "Offline (Error: Heating failed, system stopped! Heater_ID: 0 - Printer halted. kill() called!)"
Connection closed, closing down monitor

**I initially used the firmware menu PID Autotune after flashing which is when all 3 printers failed. Since Octoprint disconnected. I don't have the errors in the logs anymore since I re-ran it manually using** 

**M303 E0 S240 C8**

**Then it passed .**

Recv:  T:243.75 /0.00 @:38
Recv:  T:242.50 /0.00 @:38
Recv:  T:241.56 /0.00 @:38
Recv:  T:240.00 /0.00 @:38
Recv:  bias: 164 d: 90 min: 237.00 max: 243.75 Ku: 33.95 Tu: 26.05
Recv:  Classic PID
Recv:  Kp: 20.37 Ki: 1.56 Kd: 66.34
Recv: PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
Recv: #define DEFAULT_Kp 20.37
Recv: #define DEFAULT_Ki 1.56
Recv: #define DEFAULT_Kd 66.34

**Then I saved it using: M301 P20.37 I1.56 **D66.34 and received the following message.**

Recv:  T:63.15 /0.00 @:0
Recv:  T:62.45 /0.00 @:0
Recv:  T:61.85 /0.00 @:0
Recv:  T:61.18 /0.00 @:0
Send: M500
Recv: echo:Settings Stored (583 bytes; crc 53123)
Recv: ok
Recv:  T:60.56 /0.00 @:0
Recv:  T:59.93 /0.00 @:0
Recv:  T:59.24 /0.00 @:0

![image](https://user-images.githubusercontent.com/6380390/52372368-a14b5e00-2a1d-11e9-918f-c1bcdbd55fc0.png)

**I am re-running the test now because I couldn't see where the logs showed Autotune started but I can see the temps rising.**

**Comment by Deneteus** [comment]
I had to go into Octoprint and change the behavior setting so that it didn't disconnect from the printer, also enabled the serial.log since I had nothing to look at once it wiped. 

1. M301 P19.60 I1.42 D19.60
2. Recv: PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
Recv: #define DEFAULT_Kp 20.04
Recv: #define DEFAULT_Ki 1.42
Recv: #define DEFAULT_Kd 70.60

3.  Send: M301 P20.04 I1.42 D70.60
Recv: echo: p:20.04 i:1.42 d:70.60
Recv: ok
Recv:  T:149.98 /0.00 @:0
Recv:  T:147.84 /0.00 @:0
Recv:  T:145.48 /0.00 @:0
Recv:  T:143.38 /0.00 @:0
Recv:  T:141.32 /0.00 @:0
Send: M500
Recv: echo:Settings Stored (583 bytes; crc 20768)

4. Waited til the hot end temp lowers back to 25.4c 

![image](https://user-images.githubusercontent.com/6380390/52382530-40328300-2a3b-11e9-907e-04a8795ba87c.png)

5. Preheated the printer to Hotend: 240C Bed: :75C for PETG

6.  What's crazy is that it doesn't show the bed temp.  It's not even heating it.

![image](https://user-images.githubusercontent.com/6380390/52382755-29d8f700-2a3c-11e9-8f52-65ab14a8a314.png)

![image](https://user-images.githubusercontent.com/6380390/52382991-22661d80-2a3d-11e9-8624-cc5edb4b8004.png)

Config Files:  [Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2838826/Marlin.zip)
Octoprint Log: [octoprint log.txt](https://github.com/MarlinFirmware/Marlin/files/2838833/octoprint.log.txt)

**Comment by Deneteus** [comment]
> > I am having an issue with bed heating where it fails not too long after attempting to heat when running PID Autotune
> 
> How did it fail? What error message? At about what part of the temperature curve?

**Comment by Deneteus** [comment]
Nevermind the closed. Issue is unresolved. Browser was having an issue.

**Comment by Deneteus** [comment]
I figured out what the problem was with the bed temp. The temp sensor was disabled. Let me try this again.

**Comment by Deneteus** [comment]
So after it flashed I attempted the heat the bed up to temp and this is the error.

[octoprint bed heat failed log.txt](https://github.com/MarlinFirmware/Marlin/files/2839015/octoprint.bed.heat.failed.log.txt)

I am currently running PID Autotune on just the beds. 

Send: M303 E-1 C5 S80
Recv: PID Autotune start

I found a reference to a similar issue in #8942.

**Comment by Deneteus** [comment]
Alright. Here is the failure. Heating Failed

![image](https://user-images.githubusercontent.com/6380390/52386158-64e22700-2a4a-11e9-94f3-a0de14940026.png)

Recv: Error:Heating failed, system stopped! Heater_ID: bed
Recv: Error:Printer halted. kill() called!
Changing monitoring state from "Operational" to "Error: Heating failed, system stopped! Heater_ID: bed - Printer halted. kill() called!"
Changing monitoring state from "Error: Heating failed, system stopped! Heater_ID: bed - Printer halted. kill() called!" to "Offline (Error: Heating failed, system stopped! Heater_ID: bed - Printer halted. kill() called!)"
Connection closed, closing down monitor

[octoprint bed heat failed log #2.txt](https://github.com/MarlinFirmware/Marlin/files/2839045/octoprint.bed.heat.failed.log.2.txt)

I am going to test PID Tune on the bed at the 70C and then change the PID and test again at 75C.

**Comment by AnHardt** [comment]
Your bed is simply slow.
Relax
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Configuration_adv.h#L104-109
Or improve the bed heater. "More Power" ;-)

**Comment by Deneteus** [comment]
> Your bed is simply slow.
> Relax
> https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Configuration_adv.h#L104-109
> Or improve the bed heater. "More Power" ;-)

No, Because in previous builds it wasn't this slow on 3 separate printers. Besides the stock PID being inadequate there is something else going on here. In documentation it says after you run PID Autotune you can save the settings via M500. That's not happening either. I'll have some logs to post in a few.

![image](https://user-images.githubusercontent.com/6380390/52387046-50a02900-2a4e-11e9-8b7f-eb4fbdfaef4e.png)

![image](https://user-images.githubusercontent.com/6380390/52386996-15055f00-2a4e-11e9-9b6c-d70701671d71.png)

**It is enabled.**

![image](https://user-images.githubusercontent.com/6380390/52387347-872a7380-2a4f-11e9-8d11-d8de11e8c610.png)

**I had to manual enter the PID Settings. The documentation fails to mention that you have to use M304 
 to save the settings, It should at least link to the command.**

![image](https://user-images.githubusercontent.com/6380390/52387286-30bd3500-2a4f-11e9-9738-d9814dbb4a01.png)

**Comment by Deneteus** [comment]
So it failed again and I noticed a few things. 

1. * The LCD display did not show the temp it was being told to heat to but it showed the thermistor temp.

![image](https://user-images.githubusercontent.com/6380390/52396187-7b9e7300-2a76-11e9-8413-0911c01ad9a3.png)


2. * It was disconnected but no errors happened and the bed was cold.
3. * When I restarted Octoprint to reconnect and get the info it showed there were no bed PID settings which means they were erased after it failed.

[octoprint bed heat failed log #3.txt](https://github.com/MarlinFirmware/Marlin/files/2839232/octoprint.bed.heat.failed.log.3.txt)

**Comment by Deneteus** [comment]
> Your bed is simply slow.
> Relax
> https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Configuration_adv.h#L104-109
> Or improve the bed heater. "More Power" ;-)

Seems like I am not the only one that has run into this problem. #12265

When I was running 1.1.5, 1.1.6, 1.1.7 and 1.1.8 I wasn't having the same issue and 75C took no time to get to. It wasn't till 1.1.9 that these issues started popping up. Only one of my printers had issues getting near 100C and it was a board issue that went away after I added some insulation to the bed. I have 3 CR-10's and 1 CR-10S that was upgraded from Stock CR-10 which was one of the first few batches.

[octoprint bed heat failed log #4.txt](https://github.com/MarlinFirmware/Marlin/files/2840062/octoprint.bed.heat.failed.log.4.txt)

![image](https://user-images.githubusercontent.com/6380390/52401079-7cd79c00-2a86-11e9-90e7-2eb7c6b143e1.png)

**Comment by Deneteus** [comment]
So since Creality posted the source a month ago  I checked and the original firmware was using Bang-Bang for the CR-10 S3.  I am able to get to 75C fairly quick though with PidTempBed enabled though. 

https://github.com/Creality3DPrinting/CR10-Melzi-1.1.2/blob/master/Firmware/Marlin/Configuration.h

![image](https://user-images.githubusercontent.com/6380390/52402528-1ce2f480-2a8a-11e9-9e43-bdd484bc4f74.png)

![image](https://user-images.githubusercontent.com/6380390/52402567-371cd280-2a8a-11e9-8a40-9d8bfe7c8e03.png)

**Comment by Deneteus** [comment]
Failed to complete with no errors.

[octoprint bed heat failed log #5.txt](https://github.com/MarlinFirmware/Marlin/files/2840227/octoprint.bed.heat.failed.log.5.txt)


![image](https://user-images.githubusercontent.com/6380390/52403640-cc20cb00-2a8c-11e9-8c7a-93489d067d4c.png)

**Comment by Deneteus** [comment]
I kept wondering why it seemed off with the ramping. I checked the original source and the bed thermistor value  was set to 5 instead of 1. That would mean the profile example value was incorrect.

![image](https://user-images.githubusercontent.com/6380390/52403884-608b2d80-2a8d-11e9-862c-87e32796937d.png)

![image](https://user-images.githubusercontent.com/6380390/52403980-8d3f4500-2a8d-11e9-8f9a-6808acfdac1f.png)

**Comment by AnHardt** [comment]
From your logs i can see you are now able to store the PID settings.
Better - i can see how autotune fails.
For 80°C the heater is not able to increase WATCH_BED_TEMP_INCREASE °C in WATCH_BED_TEMP_PERIOD seconds - so "Heating failed".
This was not checked, during autotune,  for in versions before 1.1.9., so can not occur in earlier versions of Marlin.

For 75°C the case is a bit more complicated. Let me try to explain.
The autotune algorithm tries to center the target temperature between max. overshoot and min. undershoot. Because at 75°C the bed heater is already very slow the overshoot is very small when heating at full power and undershoot is huge at 0 power, the algorithm tries to gradually increase the power during the cooling phase. Because the bed heater can't heat more than 100% the overshoot stays very small (< 1°C) so in the next iteration the power at cooling is increased again - until a too high heater power (for cooling) is piked and the temperature of the bed is not falling below the target temperature anymore. Autotune fails with "PID Autotune failed! timeout" (Log 5 Line 186). This is not alerted by Octoprint because the "Error:" keyword is not in the message (and it shouldn't because this is no threatening problem - just an info).

If using a wrong thermistor setting for the bed, measuring a much lower temperature then you are used to, would explain the behavior. You are at a much higher temperature than supposed. That will look like a slow/weak heater.
If your board has a bed-power-led check, if it is constantly on during full power heat up. Else there may be a problem with the heater PWM. (rare)

The missing target temperature during autotune is normal. The display directly shows the value the 'normal' heater algorithm does use for its work. That is completely bypassed during autotune.

**Comment by Deneteus** [comment]
The bed doesn't have a power led but the SSR that Creality uses does. It turns Blue when there is heating. 

![image](https://user-images.githubusercontent.com/6380390/52429763-563b5480-2aca-11e9-8be5-9be350136982.png)

Now based on what you were saying doesn't that mean I should be adjusting the Max Power setting?

![image](https://user-images.githubusercontent.com/6380390/52429584-f04ecd00-2ac9-11e9-9374-2164d78a6232.png)

**Comment by AnHardt** [comment]
No! Every change here will decrease the maximum power - never increase.
As long as the LED is constantly on during (far) heatup all is well with the PWM.

**Comment by AnHardt** [comment]
Table | ADC | Temperature
--- | --- | ---
  5 | 600 |  high 80s  
  5  | 700 | low 80s 
 5 | 800 | ~65   
--- | --- | ---
 1 | 600 | high 90s
1 | 700 | upper 80s
1 | 800 | ~70

That's not much of a difference but at least the expected direction.

**Comment by Deneteus** [comment]
Why would an Autotune for the bed report nothing? 

![image](https://user-images.githubusercontent.com/6380390/52450312-18f1b980-2b00-11e9-92c8-67ef54933822.png)
****

**Comment by AnHardt** [comment]
M303 called with C <= 2?

**Comment by AnHardt** [comment]
No answer is an answer. See #13113

**Comment by Deneteus** [comment]
> M303 called with C <= 2?

No it was called with 5. And it's supposed to default to a specific amount of tests (3).
Thanks for the update!

![image](https://user-images.githubusercontent.com/6380390/52891931-ce9db780-3153-11e9-92eb-1b4b7e9a7e55.png)

**Comment by boelle** [comment]
@Deneteus problem solved?

**Comment by Deneteus** [comment]
> @Deneteus problem solved?

No, the problem still exists.

**Comment by boelle** [comment]
tried to insulate the underside of the bed so heat loss is keept to minimum?

**Comment by Deneteus** [comment]
> tried to insulate the underside of the bed so heat loss is kept to minimum?

I am testing this some more because in the current release I can get the bed to 70c without it failing on two out of 3 printers. No changes to the hardware were necessary.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by Deneteus** [comment]
As an update. I added bed insulation to the heat beds and had the exact same issue.
