### ISSUE TITLE
Error copiling with JUNCTION_DEVIATION enabled

### ISSUE THREAD

**Issue by dzieva** [MarlinFirmware/Marlin#13000]
Hello,
I am having error in configuration_store.cpp when compiling with JUNCTION_DEVIATION enabled.

### Description

configuration.h

//
// Use Junction Deviation instead of traditional Jerk Limiting
//
#define JUNCTION_DEVIATION
#if ENABLED(JUNCTION_DEVIATION)
  #define JUNCTION_DEVIATION_MM 0.08  // (mm) Distance from real junction edge
#endif

/**
 * Default Jerk (mm/s)
 * Override with M205 X Y Z E
 *
 * "Jerk" specifies the minimum speed change that requires acceleration.
 * When changing speed and direction, if the difference is less than the
 * value set here, it may happen instantaneously.
 */
#if DISABLED(JUNCTION_DEVIATION)
  #define DEFAULT_XJERK 10.0
  #define DEFAULT_YJERK DEFAULT_XJERK
  #define DEFAULT_ZJERK DEFAULT_XJERK // Must be same as XY for delta
#endif

#define DEFAULT_EJERK    5.0  // May be used by Linear Advance

**Actual behavior:** error: DEFAULT_XJERK ...YJERK ...ZJERK was not declared

![error](https://user-images.githubusercontent.com/35209392/51645828-15d1c780-1f5d-11e9-9bcc-e6a6e62dd64c.jpg)

**Comment by swilkens** [comment]
I can't replicate this on current 2.0.x-bugfix

* Which version of Marlin are you using?

* If an older version, can you try this with the most recent 2.0.x-bugfix?

* Can you please provide the complete `Configuration.h` and `Configuration_adv.h` files in a zip file, attached here?

**Comment by dzieva** [comment]
I'm using the latest version 2.0.x-bugfix

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2793592/Configuration.zip)

**Comment by dzieva** [comment]
My Workaround in configuration_store.cpp

![workaround](https://user-images.githubusercontent.com/35209392/51715605-9a394e80-2020-11e9-843c-c68233deb402.jpg)

**Comment by cacrippen** [comment]
I also had this problem, the fix worked great!! thank you for the help.
