### ISSUE TITLE
[bugfix-2.0.x] BLTouch does not work if SERVO0_PIN is defined in Configuration.h

### ISSUE THREAD

**Issue by ShaggyDog18** [MarlinFirmware/Marlin#13017]
[bugfix-2.0.x] BLTouch does not work if SERVO0_PIN is defined in Configuration.h
### Environment
Printer: Creality Ender-4
Stock board based on ATmega 2560; 
Image compiled in Arduino IDE
### Description
BLTouch is connected to vacant Z_MAX_PIN #19
Pin definition:
  #define SERVO0_PIN  19 
BLTouch does not work if it is defined in Configuration.h; still works fine in case SERVO0_PIN  is defined right in the pins_RAMPS.h like:
//
// Servos
//
#ifdef IS_RAMPS_13		
   #define SERVO0_PIN        19    //7   // RAMPS_13 // Will conflict with BTN_EN2 on LCD_I2C_VIKI
#else
   #define SERVO0_PIN       19    //11

### Root Cause
pins_RAMPS.h file is included after configuration.h and overrides definitions made in the configuration.h. 

### Solution
To prevent re-definition of SERVO0_PIN made in configuration.h add #ifndef to pins_RAMPS.h  like:
//
// Servos
//
#ifndef SERVO0_PIN	// prevent re-definition of SERVO0_PIN in case it was defined earlier
  #ifdef IS_RAMPS_13	
     #define SERVO0_PIN        7   // RAMPS_13 // Will conflict with BTN_EN2 on LCD_I2C_VIKI
  #else
     #define SERVO0_PIN       11
  #endif
#endif

Attached is an updated pins_RAMPS.h file.
[pins_RAMPS.zip](https://github.com/MarlinFirmware/Marlin/files/2808133/pins_RAMPS.zip)
Added lines 66 and 72...

**Comment by boelle** [comment]
@ShaggyDog18 problem solved?

**Comment by ShaggyDog18** [comment]
for me - yes, but what about others? 
Did you add a proposed solution to the pins_RAMPS.h file of the Marlin 2.0 distribution?

**Comment by boelle** [comment]
no you should submit a PR to bugfix 2.0

**Comment by ShaggyDog18** [comment]
what is PR? How to submit it?

**Comment by InsanityAutomation** [comment]
I just tucked this into one of my other PR's since I had it open.

**Comment by ShaggyDog18** [comment]
Thank you! 
I've described the solution; it is simple and according to the approach you use to define other pins in the pins_RAMPS.h ...

**Comment by InsanityAutomation** [comment]
Yup, the #ifnef is pretty common in this scenario and thats merged now. Feel free to close this issue!

**Comment by ShaggyDog18** [comment]
Great! Let's close this !

**Comment by boelle** [comment]
click the close button if you want to close

**Comment by ShaggyDog18** [comment]
Great! Let's close this !

**Comment by ShaggyDog18** [comment]
Great! Let's close this !
