### ISSUE TITLE
[bugfix-2.0.x] TUNE menu is missing

### ISSUE THREAD

**Issue by dahuafschmied** [MarlinFirmware/Marlin#13025]
since #12926 the TUNE menu is missing while printing with octoprint.
the first entry is PAUSE PRINT the next is CONFIGURATION

here is my repo:
https://github.com/dahuafschmied/Marlin-for-Anycubic-i3-Mega

**Comment by GMagician** [comment]
Menu is still there in code, when printer is printing...

Source line 110 in Marlin/src/lcd/menu/menu_main.cpp

**Comment by dahuafschmied** [comment]
and line 108 is disabling it. ;-)

**Comment by GMagician** [comment]
Right, missed it

**Comment by J-charles-C** [comment]
I,

same problem for me, i don't hav access to Tune Menu. 
Parts of menu are in english and not traduce to french. I have choice fr in configuration.H

I have the last commit.

best

**Comment by GMagician** [comment]
> Parts of menu are in english and not traduce to french

Missing translated message will be displayed in English. If you have mixed messages it's because none has updated French

**Comment by J-charles-C** [comment]
I,
Thanks @GMagician .

best

**Comment by J-charles-C** [comment]
@GMagician 

All is Ok after add ";"

Many thanks.

**Comment by GMagician** [comment]
Yes but I suspect that who made that code forgot a menu item there but I don't know what was its original intent

**Comment by InsanityAutomation** [comment]
Ill double check if anything is missing from what I had intended tonight. Been alot of hands in this area lately and more than a few overlapping merges in the past couple weeks.

**Comment by InsanityAutomation** [comment]
It looks like the PR's that added host command support for the pause / resume from the LCD and the ones moving the sd file menu around collided and left some crap behind. Im 90% sure thats the original conditions around the abort menu before it was modified to support an action command. If so, it can come out with the surrounding preprocessor. Ill verify shortly, and if so throw up a new PR to supersede that one.

**Comment by InsanityAutomation** [comment]
Since the one went in then the other pr behind it, this should be double closed! Can you verify and close this issue?

**Comment by dahuafschmied** [comment]
Fixed. Thank You
