### ISSUE TITLE
[bugfix-1.1.x] Select Mk2 multiplexer and dual Z Motor not Work

### ISSUE THREAD

**Issue by madnessracer** [MarlinFirmware/Marlin#13031]
Hello
I use a Trigorilla board (Ramps 1.4) with two Z-steppers and two limit Z-switches (min Z and max Z).
Works without problems.

Unfortunately, with this configuration, in the config.h option "MK2_MULTIPLEXER" 
can only be activated with the hint "MK2_MULTIPLEXER requires 2 or more EXTRUDERS."

If you change the number of extruders to 4 then you will get the message "No E stepper plug left for Z2"

But no more step driver is needed.

**Comment by revilor** [comment]
Have you also activated SINGLENOZZLE ?

**Comment by madnessracer** [comment]
I tried it with #define SINGLENOZZLE and without #define SINGLENOZZLE.
Both give the same result.

**Comment by boelle** [comment]
@madnessracer problem solved?

**Comment by madnessracer** [comment]
I hope that when I compile I get no more errors, but I could not test it yet

**Comment by boelle** [comment]
remember to test with bugfix 2.0

**Comment by boelle** [comment]
@madnessracer have you tested with 2.0 ?

**Comment by boelle** [comment]
@thinkyhead think we can assume OP dead on this one
