### ISSUE TITLE
Marlin 2.0: Z axis moves downwards only unless moved in both directions

### ISSUE THREAD

**Issue by towe96** [MarlinFirmware/Marlin#13044]
### Description

After a reset and switching to relative mode (`G91`), sending
`G1 Z1`
results in the stepper moving "downwards", even when sending multiple such commands.
Once a `G1 Z-1` has been sent (moving the stepper "downwards" as intended), `G1 Z1` moves the stepper in the "upwards" direction.

### Steps to Reproduce

1. Reset printer / reconnect to PC
2. Move Z axis via the onscreen menu or G-Code over USB

**Expected behavior:**
Commanding the Z axis to move upwards moves the Z axis upwards.
Commanding the Z axis to move downwards moves the Z axis downwards.

**Actual behavior:**
Commanding the Z axis to move upwards moves the Z axis downwards, unless it has been commanded to move downwards once before.

#### Additional Information
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/2807587/Config.zip)
[Video](https://www.youtube.com/watch?v=Vwods825EgU)

Setup:
TronXY XY-100 / iMakr STARTT printer
MKS GEN v1.4 board
DRV8825 drivers (swapping to A4988 made no difference in behavior)
Dual Z enabled (E1 driving Z2, disabling this made no difference in behavior)

It works as intended on Marlin 1.1.9.

**Comment by towe96** [comment]
It seems to have been fixed since the date of when I downloaded the copy of Marlin (19-01-28, 17:09 UTC) and now (19-01-29, 14:08 UTC).

**Comment by reloxx13** [comment]
should be fixed with https://github.com/MarlinFirmware/Marlin/pull/13032

got merged yesterday

pls update ur fw.

**Comment by towe96** [comment]
Yes, that seems to be the commit which fixed the issue.
