### ISSUE TITLE
Auto Bed Level setting Y to 55 when at 0

### ISSUE THREAD

**Issue by ScottAllsup** [MarlinFirmware/Marlin#13052]
### Description

When setting up the Anet A8 with the ROKO SN04-N. I have successfully added it to my printer and plugged into S_Z on the board. I have tested the sensor and it works fine. However when setting up within Marlin the Y Axis when doing a Auto Home is setting Y to 0 and then thinking it is 55 ?

The steps i have taken as stated in multiple youtube videos and https://3dprint.wiki/reprap/anet/a8/improvement/autobedleveling and searching the internet.

As stated in the various guides i edit the configuration.h and
Enable:
#define AUTO_BED_LEVELING_BILINEAR 

Set the probe offsets to 15 and 55:
#define X_PROBE_OFFSET_FROM_EXTRUDER 15   // X offset: -left  +right  [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER 55   // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER 0   // Z offset: -below +above  [the nozzle]

Enable:
#define Z_SAFE_HOMING

I am unable to enable the following:
  // Set the boundaries for probing (where the probe can reach).
  define LEFT_PROBE_BED_POSITION MIN_PROBE_EDGE
  define RIGHT_PROBE_BED_POSITION (X_BED_SIZE - MIN_PROBE_EDGE)
  define FRONT_PROBE_BED_POSITION MIN_PROBE_EDGE
  define BACK_PROBE_BED_POSITION (Y_BED_SIZE - MIN_PROBE_EDGE)
Due to exceeding the bed area ?

### Steps to Reproduce
**Expected behavior:** I expect the printer to center in the bed 110,110,0 and auto bed level.

**Actual behavior:** The bed goes to 0,hits the endstop, grinds and the display states the bed is at 55 (im assuming the probe offset is being applied?)

[configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2813457/configuration.txt)

**Comment by RudyBenner** [comment]
What a mess. Would edit out all the file content, attach them as a zip instead.

your problem is in here.

#define AUTO_BED_LEVELING_BILINEAR

Set the probe offsets to 15 and 55:
#define X_PROBE_OFFSET_FROM_EXTRUDER 15 // X offset: -left +right [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER 55 // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER 0 // Z offset: -below +above [the nozzle]

**Comment by ScottAllsup** [comment]
Sorry edited it. Saw that way on other posts to copied the format. 

Should the probe offsets also offset the safe_home position ?

**Comment by RudyBenner** [comment]
two big problems here, see if you can find it.


/**
 * A Fix-Mounted Probe either doesn't deploy or needs manual deployment.
 *   (e.g., an inductive probe or a nozzle-based probe-switch.)
 */
#define FIX_MOUNTED_PROBE

/**
 * Z Servo Probe, such as an endstop switch on a rotating arm.
 */
//#define Z_PROBE_SERVO_NR 0   // Defaults to SERVO 0 connector.
//#define Z_SERVO_ANGLES {70,0}  // Z Servo Deploy and Stow angles

/**
 * The BLTouch probe uses a Hall effect sensor and emulates a servo.
 */
//#define BLTOUCH
#if ENABLED(BLTOUCH)
  //#define BLTOUCH_DELAY 375   // (ms) Enable and increase if needed
#endif

**Comment by RudyBenner** [comment]
Line 781

**Comment by Micro-3D-GER** [comment]
**@Hello TDIScott93**

Please test this way
```
  // Set the boundaries for probing (where the probe can reach).
  //#define LEFT_PROBE_BED_POSITION MIN_PROBE_EDGE
  //#define RIGHT_PROBE_BED_POSITION (X_BED_SIZE - MIN_PROBE_EDGE)
  //#define FRONT_PROBE_BED_POSITION MIN_PROBE_EDGE
  //#define BACK_PROBE_BED_POSITION (Y_BED_SIZE - MIN_PROBE_EDGE)
```


```
  // Set the boundaries for probing (where the probe can reach).
  #if X_PROBE_OFFSET_FROM_EXTRUDER < 0
    #define LEFT_PROBE_BED_POSITION (MIN_PROBE_EDGE)
    #define RIGHT_PROBE_BED_POSITION (X_BED_SIZE - 1 - MIN_PROBE_EDGE + X_PROBE_OFFSET_FROM_EXTRUDER)
  #else
    #define LEFT_PROBE_BED_POSITION (X_PROBE_OFFSET_FROM_EXTRUDER + MIN_PROBE_EDGE)
    #define RIGHT_PROBE_BED_POSITION (X_BED_SIZE - 1 - MIN_PROBE_EDGE)
  #endif
  #if Y_PROBE_OFFSET_FROM_EXTRUDER < 0
    #define FRONT_PROBE_BED_POSITION (MIN_PROBE_EDGE)
    #define BACK_PROBE_BED_POSITION (Y_BED_SIZE - 1 - MIN_PROBE_EDGE + Y_PROBE_OFFSET_FROM_EXTRUDER)
  #else
    #define FRONT_PROBE_BED_POSITION (Y_PROBE_OFFSET_FROM_EXTRUDER + MIN_PROBE_EDGE)
    #define BACK_PROBE_BED_POSITION (Y_BED_SIZE - 1 - MIN_PROBE_EDGE)
  #endif
```

**Comment by ScottAllsup** [comment]
Okay so i missed an important information, i am running Marlin 1.1.9 (not bugfix)

Using the code above with 
#define X_PROBE_OFFSET_FROM_EXTRUDER 15 // X offset: -left +right [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER 55 // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER 0 // Z offset: -below +above [the nozzle]

It was the same issue. 

So i change Y_PROBE_OFFSET to 0. Same, again grinds on Y and believes 0 is 110. 

I have change the Y_PROBE_OFFSET to 110... went to 10.

So im quiet honestly lost and went back to basics i dropped the normal switch sensor back, removed all ABL. and the same issue was happening. 

When homing the printer it though 0 was 110. So i removed the hot bed and it seems the belt is slipping. Possibly coincidence when i introduced the ABL ?

Ordered a replacement fiber glass belt and will resume testing ABL (hopefully with success) It will arrive Monday  4th March. So will close this and if the issue persists hopefully re-open the issue.
