### ISSUE TITLE
[bugfix 2.0.x]: Custom bootscreen not working with MKS Mini Display

### ISSUE THREAD

**Issue by bipsendk** [MarlinFirmware/Marlin#13064]
### Description

When  specifying a custom bootscreen in the configuration (on a Fysetc F6 board - haven't tested with other boards), the custom bootscreen looks like random pixels and is not displayed for the specified duration.

### Steps to Reproduce

1. Create custom _Bootscreen.h (or copy example from e.g. Creality CR10)
2. Enable custom bootscreen in configuration.h
3. Compile code and upload to board
4. Reset board and observe display

**Expected behavior:** [What you expect to happen]

Custom bootscreen is displayed - also in the specified duration 

**Actual behavior:** [What actually happens]

Random pixels apparently being shown - and not in the specified time (I set it to 6000 msec - it was there for a maximum of 1 second)

#### Additional Information

Observed when compiled in VSCode with PlatformIO (Fysetc F6 board)
Also observed in code generated by Arduino IDE 1.9.0 beta (target Fysetc F6 board)

Display works OK with the status screen, the menus and so on...

![20190202_091913_072](https://user-images.githubusercontent.com/8531428/52161890-48ea2880-26cc-11e9-9614-4a667a94cee9.jpg)

[MKS-Mini-bootscreen.zip](https://github.com/MarlinFirmware/Marlin/files/2824202/MKS-Mini-bootscreen.zip)

**Comment by boelle** [comment]
@bipsendk problem solved?

**Comment by bipsendk** [comment]
@boelle - I will try again with a fresh clone of the 2.0 sourcecode. I will get back to you in a couple of days.

**Comment by bipsendk** [comment]
Still an issue. 
_Bootscreen.h located in same folder as Marlin.ino - and there is no compile error, so I assume the location is correct.

**Comment by bipsendk** [comment]
FYI: The Marlin bootscreen isn't displayed either...

**Comment by boelle** [comment]
tried to ask in these places?

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report.](https://github.com/MarlinFirmware/Marlin/issues/new/choose)

**Comment by bipsendk** [comment]
Did some more tinkering, at it seems to work now... Strange...

**Comment by hussainsail2002** [comment]
@bipsendk I am having the same issue , could you let me know what changes you made
