### ISSUE TITLE
Board will not hardware reset

### ISSUE THREAD

**Issue by cinealfa** [MarlinFirmware/Marlin#13062]
### Description

Pressing the button on the MKS Sbase does not reset the board.

### Steps to Reproduce

When you press the button nothing happens.

**Expected behavior:** [What you expect to happen]
Usually the board resets.

**Actual behavior:** [What actually happens]
Nada. LOL
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/2823400/Archive.zip)

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by gloomyandy** [comment]
What button are you pressing, the one on the board itself or the one on an attached display? The reset function in both cases is a hardware action and is not controlled by Marlin, so if it is not working then I would suggest you have some sort of hardware issue.

**Comment by cinealfa** [comment]
It is the one on the board. And it works in smoothieware.

**Comment by RudyBenner** [comment]
Both work here. Bugfix2.0.x and full graphic lcd on my sbase

**Comment by gloomyandy** [comment]
That button is wired directly to the reset pin on the processor, I really can't imagine how it can work for one and not the other. What makes you think it is not working? Does your printer boot at all with Marlin? What happens if you just power on your printer?

**Comment by gloomyandy** [comment]
Oh and it would help if you can provide some more details. When are you resetting the printer, are you doing this because there is a problem? After you press the reset button what happens, is Marlin still running? If you have the printer attached to a PC via USB do you here/see the printer USB device get reset? If you can please look in the PC device manager and report back on what USB device appears following a reset, it may be that your printer has rebooted into the bootloader rather than into Marlin.

**Comment by boelle** [comment]
@cinealfa problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by cinealfa** [comment]
No @boelle problem still persists reset button is ineffective.

**Comment by gloomyandy** [comment]
Have you tested that the reset button still works with Smoothieware, but not with Marlin? What about the other questions I asked above? I have just checked the Schematic again for the MKS SBase and the reset button on the main board is connected directly to the reset pin of the LPC1768. I really can't see how it can work for one firmware and not another.

**Comment by RudyBenner** [comment]
Reset works fine on my sbase running 2.0.x from the board.

**Comment by RudyBenner** [comment]
You have a schematic for SBASE? I have a schematic for smoothie board, not exactly the same.

**Comment by gloomyandy** [comment]
Yes there is a Schematic for the 1.2 version of the board available here:https://github.com/pixel3design-hub/MKS-SBASE-FULL-DOCUMENTED

There do not seem to be many changes between V1.2 and V1.3 of the board.

Oh and I also have an SBase 1.3 and reset works fine for me with it.

**Comment by RudyBenner** [comment]
Thank you very much, have starred that repository.
rudy
