### ISSUE TITLE
[Bugfix 2.0.x] RADDS 1.5 EEPROM read/write causes error

### ISSUE THREAD

**Issue by hansilein** [MarlinFirmware/Marlin#13065]
### Description
EEPROM read/write operations cause error when upgrading from Marlin4DUE to current Marlin 2.0.x.

### Steps to Reproduce

1. Install most current Marlin 2.0
2. Connect via serial port
3. Read and write eeprom (M502 + M500)

**Expected behavior:** 
Settings saved successfully.

**Actual behavior:** 
Settings cannot be saved or even read. Watchdog reset.
Error Log:
```
Connecting...
start
Printer is now online.
echo:PowerUp
Marlin bugfix-2.0.x
echo: Last Updated: 2018-01-20 | Author: (none, default config)
echo:Compiled: Feb  2 2019
echo: Free Memory: 86896  PlannerBufferBytes: 1344
echo:EEPROM version mismatch (EEPROM=V20 Marlin=V64)
echo:Hardcoded Default Settings Loaded
m502
SENDING:M502
echo:Hardcoded Default Settings Loaded
m500
SENDING:M500
echo:Error writing to EEPROM!
Error:Field esteppers mismatch.
[ERROR] Error:Field esteppers mismatch.
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
echo:Error writing to EEPROM!
```
#### Additional Information
I tried 2 different Marlin configurations. One with all features activated, that I really need and had allready activated in Marlin4Due. And one with a minimal configuration (board + eeprom) in order to exclude any configuration mistake.
But there was no difference, same output.

I also tested several known solutions for related or similar issues...
For example:
https://github.com/MarlinFirmware/Marlin/issues/11415
But that caused the same error and additionally a datasize error.

Another attempt was to erase the onboard I2C-EEPROM (24LC256) with a special Arduino sketch...
Result:
```
echo:EEPROM version mismatch (EEPROM= Marlin=V64)
```
or
```
echo:EEPROM version mismatch (EEPROM=? Marlin=V64)
```

RADDS-Board and Eeprom-IC are fully functional and tested... 
Marlin4Due is still working.

**Comment by bwgeez02** [comment]
What program are you using to upload the firmware?

**Comment by hansilein** [comment]
I am using Arduino IDE 1.8.7

**Comment by bwgeez02** [comment]
Post your configs in a zip file and someone can probably help.

**Comment by hansilein** [comment]
Unfortunenatly there is nearly nothing special to show in my configs...
Only the motherboard is configured and eeprom settings are activated.

There is no difference except of this.

[config.zip](https://github.com/MarlinFirmware/Marlin/files/2870190/config.zip)

**Comment by bwgeez02** [comment]
Try M501 then M500 instead of the M502.

**Comment by bwgeez02** [comment]
I use Arduino IDE (1.8.8). Sometimes I've had to uninstall it and delete the Arduino15 folder, then reinstall it to get it working.

**Comment by bwgeez02** [comment]
What main board are you using (the board the Radds shield is on)?

**Comment by hansilein** [comment]
M501 isn't possible:
```
m501
SENDING:M501
echo:EEPROM version mismatch (EEPROM=ʅR Marlin=V64)
echo:Hardcoded Default Settings Loaded
```
Or:
```
m501
SENDING:M501
echo:EEPROM version mismatch (EEPROM=ERR Marlin=V64)
echo:Hardcoded Default Settings Loaded
```

Actually Arduino IDE is fully functional and tested with many different boards...
Tested with Uno, Nano, Due (orignal + fake)
But I will uninstall and reinstall it later this evening.

I am using that RADDS 1.5 board on an original Arduino Due board.

I also opened a thread in the german part of reprap-forums.
Unfortunenatly I wasn't able to find enough time for an appropriate translation in this issue thread.
But there is a lot of serial output and that's not german.
[https://reprap.org/forum/read.php?247,846022](url)
I will try to translate it this evening....

**Comment by bwgeez02** [comment]
I copy/paste to google translate. Fastest workaround I've found.

**Comment by bwgeez02** [comment]
Have you read this? 

https://github.com/MarlinFirmware/Marlin/issues/11415

**Comment by hansilein** [comment]
Yes, I have... That was one of my first approaches to solve my problem. But without any success.

**Comment by hansilein** [comment]
My last approach:

```cpp
#include "../../core/serial.h"

// . . .

void eeprom_write_byte(uint8_t *pos, unsigned char value) {
  unsigned eeprom_address = (unsigned) pos;

  uint8_t res;

  eeprom_init();

  Wire.beginTransmission(eeprom_device_address);
  Wire.write((int)(eeprom_address >> 8));   // MSB
  Wire.write((int)(eeprom_address & 0xFF)); // LSB
  Wire.write(value);
  res = Wire.endTransmission();

  // wait for write cycle to complete
  // this could be done more efficiently with "acknowledge polling"
  delay(5);
  if (res != 0)  {
      SERIAL_ECHOLNPAIR("Wire ", res);
      SERIAL_ECHOLNPAIR("Pos  ", (uint8_t*)pos);
  }
}
```

in order to check the I2C connection. The result was "0"
So, everything ok...

**Comment by hansilein** [comment]
"AlterBastler" a member of reprap forum has found a solution...

#### `Marlin/src/HAL/HAL_DUE/persistent_store_eeprom.cpp`
```cpp
bool PersistentStore::write_data(int &pos, const uint8_t *value, size_t size, uint16_t *crc) {
  while (size--) {
    uint8_t * const p = (uint8_t * const)pos;
    uint8_t v = *value;
    // EEPROM has only ~100,000 write cycles,
    // so only write bytes that have changed!
    if (v != eeprom_read_byte(p)) {
      eeprom_write_byte(p, v);

      //delay after write operation
      delay(2);

      if (eeprom_read_byte(p) != v) {
        SERIAL_ECHO_MSG(MSG_ERR_EEPROM_WRITE);
        return true;
      }
    }
    crc16(crc, &v, 1);
    pos++;
    value++;
  };
  return false;
}
```

**Comment by thinkyhead** [comment]
Thanks for the info. I'll patch Marlin shortly.
