### ISSUE TITLE
Resume print stuck

### ISSUE THREAD

**Issue by budy238** [MarlinFirmware/Marlin#13069]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by budy238** [comment]
[New Compressed (zipped) Folder.zip](https://github.com/MarlinFirmware/Marlin/files/2825307/New.Compressed.zipped.Folder.zip)

**Comment by gloomyandy** [comment]
You need to fill out the issue report. It is unlikely that anyone will understand what problem you have just by your title.

**Comment by InsanityAutomation** [comment]
Same as #13073 see answer there

**Comment by boelle** [comment]
@budy238 is this still a problem?

and describe the problem in details

try bugfix 2.0

**Comment by boelle** [comment]
@thinkyhead think we can close, OP did not describe and has lost interest

**Comment by budy238** [comment]
I apologize for not responding I appreciate the diligent service
