### ISSUE TITLE
Q: LCD Resume print menu in standby

### ISSUE THREAD

**Issue by rmoravcik** [MarlinFirmware/Marlin#13073]
I just uploaded bugfix-2.0.x (https://github.com/MarlinFirmware/Marlin/commit/4d1093b3868a37ee0def13dbe2785f3ce98fcf6d) to my printer and I discovered that "Resume print" menu option is always visible even when printer is not doing any print job.

I've seen some LCD menu pause/resume fixes by @InsanityAutomation merged to bugfix-2.0.x recently.

So, my question is: Is this an regresion of those fixes or an intention to have it visible?

**Comment by ghost** [comment]
I have seen the same and have also been wondering

**Comment by InsanityAutomation** [comment]
It's intentional if you have host action commands enabled. The printer has no idea if you have paused the job from a remote host so that will send a resume command back to the host.

**Comment by ghost** [comment]
I am not sure I have "Host Action Commands" enabled. I believe that I don't. What are the exact #defines in question?

**Comment by InsanityAutomation** [comment]
After #13039 is merged it will be #define HOST_ACTION_COMMANDS, prior its these : 

//#define ACTION_ON_PAUSE   "pause"
//#define ACTION_ON_RESUME  "resume"
//#define ACTION_ON_PAUSED  "paused"
//#define ACTION_ON_RESUMED "resumed"
//#define ACTION_ON_CANCEL  "cancel"

**Comment by ghost** [comment]
Okidoki - Gotcha. 

But I do not have any of them defined.

**Comment by InsanityAutomation** [comment]
Just took a quick peak and it looks like the conditions around the menu got dropped. Ill add em back in as part of the PR mentioned above.

**Comment by rmoravcik** [comment]
It's fixed with commit https://github.com/MarlinFirmware/Marlin/commit/0a7ea7063f82bc914e5cbfb55f0db400d0c3c936. Thank you.
