### ISSUE TITLE
clarification needed on probe offset

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#13079]
#define Z_PROBE_OFFSET_FROM_EXTRUDER 0   //** Z offset: -below +above  [the nozzle]

I have a coreXY where +Z sets bed farther from nozzle.
If I want to set bed closer to nozzle than indicated by probe would I enter a + or - value

**ALSO**, in the docs for M851 on http://marlinfw.org/docs/gcode/M851.html this is indicated;

A probe that is triggered by the nozzle itself
M851 Z1.2

What does that mean? It seems inconsistent with the def above it == M851 Z -2.0 which says the nozzle is 2mm farther from the bed than the probe.

**Comment by reloxx13** [comment]
example:
printer ask: "okay wake up guys, where is my print position?"
if ur probe says "found the bed here, so here is 0"
now ur z offset says "okay, but ur nozzle is -2mm away from this point"
and ur printer accepts with "gj guys, ill go to probes 0 and go further down by -2 to have the nozzle at the bed, this is my print position"

**Comment by ghost** [comment]
> **ALSO**, in the docs for M851 on http://marlinfw.org/docs/gcode/M851.html this is indicated;
A probe that is triggered by the nozzle itself
M851 Z1.2

A typical "probe that is triggered by the nozzle itself" will need to go up again for printing after the nozzle has triggered when probing, because it relies on some elastic compression when hitting the bed going down. So Z is plus some millimeters.

Probes like the BLTouch need to trigger BEFORE the nozzle hits the bed, so after finding the zero, then nozzle needs be a bit lower for printing - so Z should be set to minus some millimeters.

**Comment by boelle** [comment]
@ruggb still working on this?

**Comment by ruggb** [comment]
I think I have it resolved;
a NOZZLE activated probe needs a positive Z offset. It triggers AFTER hitting the bed.
A separate probe (BL Touch) needs a negative Z offset, it trigger BEFORE the nozzle gets to the bed.
Maybe you could say that and it would be VERY clear.

**Comment by boelle** [comment]
it does say so in the config

#define X_PROBE_OFFSET_FROM_EXTRUDER 23  // X offset: -left  +right  [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER 9  // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER -0.215   // Z offset: -below +above  [the nozzle]

Z offset: -below +above  [the nozzle]

so it's VERY clear to me, and i'm not a super smart person :-D

**Comment by ruggb** [comment]
#define Z_PROBE_OFFSET_FROM_EXTRUDER -0.215 // Z offset: -below +above [the nozzle]
"-" indicated bed gets closer to nozzle
"below" indicates bed is farther from nozzle.
maybe not so clear, huh?

**Comment by boelle** [comment]
its clear to me that - means it triggers below nozzle
+means above the nozzle

**Comment by ruggb** [comment]
THAT is the confusion - you are talking about Zoffset then you explain it by where the nozzle triggers.
The Zoffset is opposite of where the nozzle triggers. saying - and below to me are mutually exclusive. It is either one or the other. But since you wrote it it is perfectly clear to you.

**Comment by boelle** [comment]
no i explain it by where the probe triggers

and it has been so since at least 2013 where i got my first printer, so its nothing new

**Comment by boelle** [comment]
but yes Z offset is oposite, but i have not seen any that use Z offset

**Comment by boelle** [comment]
and i did not write anything.... but i guess you mean you as collective again
