### ISSUE TITLE
UNKNOWN_Z_NO_RAISE not working with M701 & M702

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#13074]
UNKNOWN_Z_NO_RAISE not working with M701 & M702 commands.

Release: 1.1.9
Configurations:
NO_MOTION_BEFORE_HOMING: **disabled**
UNKNOWN_Z_NO_RAISE: **enabled**
**Printer type:** COREXY
**Physical Z axis endstops:** Only Z min
More: [Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/2826209/Configurations.zip)

**Comment by boelle** [comment]
@bealparslan problem solved?

**Comment by thinkyhead** [comment]
`UNKNOWN_Z_NO_RAISE` does only apply to `G28` for the sake of homing. `M701` and `M702` shouldn't be used without homing, but this is only ensured if `NO_MOTION_BEFORE_HOMING` is enabled.

**Comment by boelle** [comment]
@thinkyhead think we can close this one, seems OP is "dead"
