### ISSUE TITLE
[2.0.x] Is it possible to use HW 1 uart TMC2208

### ISSUE THREAD

**Issue by ShohninDmitriy** [MarlinFirmware/Marlin#13071]
Is it possible to use HW 1 uart and switch driver chips using addressing individual pins
![default](https://user-images.githubusercontent.com/20542738/52176238-f9d1ef80-27c0-11e9-9e4d-e838ec11dde0.png)

**Comment by gloomyandy** [comment]
Only with extra hardware, and the current TMC library does not support this type of operation. So realistically the answer is no it is not currently supported.

**Comment by ShohninDmitriy** [comment]
Very bad because there is no SW serial on stm32f103
