### ISSUE TITLE
[SOLVED] How to compile this for STM32F103C8/CB? 

### ISSUE THREAD

**Issue by Alfrederson** [MarlinFirmware/Marlin#13075]
I'm trying to get the bufix 2.0 to compile for STM32F103CB but I've had no luck so far. It compiles just fine for other boards based on different STM32F1 (i.e: env:mks_robin and env:stm32f1), but as soon as I change the "board" property in the environment to genericSTM32F103CB or genericSTM32F103C8, then I get errors like 

`In file included from Marlin\src\HAL\HAL_STM32F1\../../inc/MarlinConfig.h:30:0,
from Marlin\src\HAL\HAL_STM32F1\u8g_com_stm32duino_fsmc.cpp:31:
Marlin\src\HAL\HAL_STM32F1\../../inc/../HAL/HAL_STM32F1/HAL.h:40:10: fatal error: util/atomic.h: No such file or directory
#include <util/atomic.h>
^~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs\mks_robin\src\src\HAL\HAL_STM32F1\u8g_com_stm32duino_fsmc.cpp.o] Error 1
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:30:0,
from Marlin\src\HAL\shared\HAL_spi_L6470.cpp:32:
Marlin\src\HAL\shared\../../inc/../HAL/HAL_STM32F1/HAL.h:40:10: fatal error: util/atomic.h: No such file or directory
#include <util/atomic.h>
^~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs\mks_robin\src\src\HAL\shared\HAL_spi_L6470.cpp.o] Error 1
 [ERROR] Took 3.27 seconds` 

Which is the same result I get when trying to set the environment to Malyan M200. Is there a fix for this that doens't involve editing random .py files?

**Comment by RudyBenner** [comment]
no config files?

**Comment by Ketchu13** [comment]
You could add `"${workspaceFolder}"` at the end of your include path (PIO): 
File to edit: > X:/MarlinFirmware/Marlin/.vscode/c_cpp_properties.json

```JSON
{
    "!!! WARNING !!!": "PLEASE DO NOT MODIFY THIS FILE! USE https://docs.platformio.org/page/projectconf/section_env_build.html#build-flags",
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                ... ,
                "${workspaceFolder}"
            ],
            "browse": {...

```
But, it would be better to edit the python file that generates the building flags.

**Comment by Injineers** [comment]
yeah, im still waiting on someone to clean it up. I 1 time was able to compile, but had a mix of custom files. then I tried again & it didnt work

then I killed everything , & haven't been able to compile for it

**Comment by boelle** [comment]
@Alfrederson problem solved?

**Comment by Alfrederson** [comment]
> @Alfrederson problem solved?

I didn't try any further. I think I'll just move to a MCU with more flash.

**Comment by boelle** [comment]
Maybe close this one then?

fre. 22. feb. 2019 00.02 skrev Alfrederson <notifications@github.com>:

**Comment by Alfrederson** [comment]
The issue still persists. I would like to keep this open just to see if someone fixes the buildscript for stm32f103c8t6 because I have a board already designed to use it.

**Comment by boelle** [comment]
if you want something you have to send a PR to bugfix 2.0 or pay someone to make it for you

please close

**Comment by Injineers** [comment]
^^ Not sure any one is asking for anything new.

The issue is you are unable to compile Marlin 2.0 for the STM via platformio at the moment. All the guides that tell you how are now broken , or the info is all over the place that it is difficult to parse.

**Comment by boelle** [comment]
@thinkyhead thoughts on this one?

**Comment by jmz52** [comment]
@Alfrederson 
The genericSTM32F103CB and genericSTM32F103C8 boards are using new STM32 Core framework which is not compatible with HAL_STM32F1.
To force platformio to use maple-based framework you need to alter 'board' file.
In platforms\ststm32\boards\genericSTM32F103CB.json file replace
  `"variant": "MAPLEMINI_F103CB"`
by
  `"variant": "stm32f1"`

Env settings in platformio.ini:
>platform      = ststm32
>framework     = arduino
>board         = genericSTM32F103CB

Also you might need https://github.com/MarlinFirmware/Marlin/pull/13506 to get rid of https://github.com/MarlinFirmware/Marlin/issues/13503
Alternatively you can add `-DSTM32F1 -DdigitalPinHasPWM(P)='(PIN_MAP[P].timer_device != NULL)'` to  build_flags

**Comment by pscrespo** [comment]
#13366 fixed compiling errors for F103Cx. I would recommend using F103CB since F103C8 doesn't have enough flash (64KB vs. 128KB). In most cases, chips labelled as C8 are actually CB, as stated [here.](https://wiki.stm32duino.com/index.php?title=Blue_Pill#128_KB_flash_on_C8_version)
@jmz52 To be able to use libmaple again you can just change the platform to a previous version in platformio.ini:
`platform      = ststm32@<4.4.0`

**Comment by Alfrederson** [comment]
> @Alfrederson
> The genericSTM32F103CB and genericSTM32F103C8 boards are using new STM32 Core framework which is not compatible with HAL_STM32F1.
> To force platformio to use maple-based framework you need to alter 'board' file.
> In platforms\ststm32\boards\genericSTM32F103CB.json file replace
> `"variant": "MAPLEMINI_F103CB"`
> by
> `"variant": "stm32f1"`
> 
> Env settings in platformio.ini:
> 
> > platform      = ststm32
> > framework     = arduino
> > board         = genericSTM32F103CB
> 
> Also you might need #13506 to get rid of #13503
> Alternatively you can add `-DSTM32F1 -DdigitalPinHasPWM(P)='(PIN_MAP[P].timer_device != NULL)'` to build_flags

Changing the variant to stm32f1 made the compilation errors switch to 


`*** [.pioenvs\bluepill3D\src\src\HAL\HAL_STM32F1\HAL_spi_STM32F1.cpp.o] Error 1
C:\Users\Ruijorji\.platformio\packages\framework-arduinoststm32\STM32F1\system\libmaple\include/libmaple/nvic.h:112:15: error: duplicate 'inline'
static inline __always_inline void nvic_globalirq_enable() {
^~~~~~~~~~~~~~~
C:\Users\Ruijorji\.platformio\packages\framework-arduinoststm32\STM32F1\system\libmaple\include/libmaple/nvic.h:119:15: error: duplicate 'inline'
static inline __always_inline void nvic_globalirq_disable() {
^~~~~~~~~~~~~~~

C:\Users\Ruijorji\.platformio\packages\framework-arduinoststm32\STM32F1\cores\maple/ext_interrupts.h:109:15: error: duplicate 'inline'
static inline __always_inline void interrupts() {
^~~~~~~~~~~~~~~
C:\Users\Ruijorji\.platformio\packages\framework-arduinoststm32\STM32F1\cores\maple/ext_interrupts.h:123:15: error: duplicate 'inline'
static inline __always_inline void noInterrupts() {
^~~~~~~~~~~~~~~
*** [.pioenvs\bluepill3D\src\src\HAL\HAL_STM32F1\HAL.cpp.o] Error 1
*** [.pioenvs\bluepill3D\src\src\HAL\HAL_STM32F1\HAL_Servo_STM32F1.cpp.o] Error 1`

And so on, but it looks like it's getting closer

This is a nightmare, many different people seem to have got it working doing different things but there's no definite reason why compilation for STM32F103 stopped working in first place, so every "fix" ends up breaking it even more

**EDIT:** updating the ststm32 platform to 5.3.0 seems to get rid of those compile errors, now I have  errors like this:

```
from .piolibdeps\U8glib-HAL_ID1932\src\clib\u8g_com_arduino_common.c:46:

C:\Users\Ruijorji\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/wirish_types.h:65:9: error: unknown type name 'bool'
typedef bool boolean;
```

It seems that the errors now stem from the u8glib, hmmmmm

**Comment by Alfrederson** [comment]
Ok, so I got it to compile adding this to lib_ignore

```
  c1921b4
  U8glib-HAL
  Adafruit NeoPixel
  TMCStepper
  TMC26XStepper
  SailfishLCD
  SailfishRGB_LED
```

I'll burn the firmware to a STM32F103 board and see what happens

So, the fix is basically this:

- Change variant from MAPLEMINI_F103CB to stm32f1
- Update STSTM32 platform to 5.3.0
- Add the libraries that generate errors to lib_ignore until it compiles

Now it's kind of sad that I need to disable u8glib since I wanted to use that I2C oled display to save pins

**Comment by Alfrederson** [comment]
I compiled it, flashed a STM32F103C8 board with it and....... it worked! Now I can consider this issue solved

**Comment by jmz52** [comment]
@Alfrederson 
From what I see you are using some older version of framework-arduinoststm32.
In newer arduino framework version has two directories - framework-arduinoststm32 for STM32 Core and framework-arduinoststm32-maple for maple-base STM32F1 and STM32F4.
Solution I've proposed is for latest version.

As for U8glib - there is an updated version which works with both STM32 Core and maple.
Until PR https://github.com/MarlinFirmware/U8glib-HAL/pull/6 is merged you can use code from
https://github.com/jmz52/U8glib-HAL/archive/stm32-maple-and-core-fix.zip for your I2C SSD1306/SH1106 display,

**Comment by Alfrederson** [comment]
> @Alfrederson
> From what I see you are using some older version of framework-arduinoststm32.
> In newer arduino framework version has two directories - framework-arduinoststm32 for STM32 Core and framework-arduinoststm32-maple for maple-base STM32F1 and STM32F4.
> Solution I've proposed is for latest version.
> 
> As for U8glib - there is an updated version which works with both STM32 Core and maple.
> Until PR [MarlinFirmware/U8glib-HAL#6](https://github.com/MarlinFirmware/U8glib-HAL/pull/6) is merged you can use code from
> https://github.com/jmz52/U8glib-HAL/archive/stm32-maple-and-core-fix.zip for your I2C SSD1306/SH1106 display,

Ok, that's very good to know. That means I won't need to use a nextion or something like that.

**Comment by Alfrederson** [comment]
One more thing, I installed that library and added the -DU8G_HAL_LINKS flag to the entironment configuration and it compiles just fine, but how do I enable the display in the marlin configuration itself? Enabling U8GLIB_SSD1306 just gives me a "cannot find u8glib.h blah blah blah" error, do I need another step?

**Comment by jmz52** [comment]
You need to remove `-DU8G_HAL_LINKS` from build flags.
