### ISSUE TITLE
Advanced Pause not compiling with Serial Port 2 on MKS Sbase  

### ISSUE THREAD

**Issue by xStolix** [MarlinFirmware/Marlin#13088]
### Description

Similar to #9948  
Advanced pause on MKS SBase using LPC1768 generates an error when serial port 2 is defined. 
When serial port 2 is commented out it will compile with no errors but then you will not be able to use the TFT Display.
The error is:
```
Marlin\src\module\configuration_store.cpp:2346:52: error: 'port' was not declared in this scope
```
Using Atom with PlatformIO with bugfix within the week
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/2834828/Configuration_adv.zip)

**Comment by thinkyhead** [comment]
I'm working on a reform to the serial print code that should fix this. I'll let you know when the patch is in.

**Comment by thinkyhead** [comment]
The patch has been applied. As a result the compile error should be fixed.

**Comment by xStolix** [comment]
Great Thanks!
