### ISSUE TITLE
junction deviation defined 2x

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#13080]
the below listed code is in both configuration.h @692 and configuration.adv.h @494
bugfix 2.0 870757a build
```cpp
// Use Junction Deviation instead of traditional Jerk Limiting
//
//#define JUNCTION_DEVIATION
#if ENABLED(JUNCTION_DEVIATION)
  #define JUNCTION_DEVIATION_MM 0.02  // (mm) Distance from real junction edge
#endif
```

**Comment by thinkyhead** [comment]
Nope.
![image](https://user-images.githubusercontent.com/698003/52299479-169a2e80-294b-11e9-8129-a83c7d298dea.png)

**Comment by ruggb** [comment]
color me CONFUSED........sorry

**Comment by InsanityAutomation** [comment]
He verified it's an issue with how you merged your config files. It was moved, not copied.
