### ISSUE TITLE
Tronxy P802m

### ISSUE THREAD

**Issue by comtechnik** [MarlinFirmware/Marlin#13109]
Hi first,
I have a Tronxy P802 with Melzi Board is unfortunately defective.
But I had a RepRap Board v1.4 lying around I have now installed this.
Is there a ready Configuration.h
and what else I need. There is indeed the new Marlin 1.1.9 version in the but unfortunately not
finished configuration for the Tronxy P802 available, only others. Can you help me??

Many Thanks

**Comment by boelle** [comment]
https://www.facebook.com/groups/1049718498464482/

https://discord.gg/n5NJ59y

**Comment by boelle** [comment]
@thinkyhead think this one can be closed too
