### ISSUE TITLE
TMC2130 with 3 differents models of motors on same printer

### ISSUE THREAD

**Issue by tobecwb** [MarlinFirmware/Marlin#13102]
Currently, trying to use TMC2130 on a CR10 S-5.

- This printer has two pancake stepper motos on Z (wired in series)
- No name NEMA 17 on X axis;
- A big stepper motor on Y axis (JD42HS60-1500A-02F -> https://3dprinting.stackexchange.com/a/7694)

I have TMC2130 on all axis (including E0)!
Currently, all motors are running at 24V, and almost everything works ok.

All TMC2130 has active cooling fan (a big fan of 200mm), and no prewarn triggered.
Current of all drivers are at default value (800ma, including Y)...

If I disable STEALTHCHOP, got no layer shifts, but a horrible sound on Z motors... very loud!
If I enable STEALTHCHOP, silence... but layers shift **only in Y axis**!

I already tried to increase the Y current until 1200, but no success... always got layer shift.

I believe something must be changed only for Y axis. This stepper motor is bigger because moves a bed of 500x500mm, but I really don't know where start.

PS: I already checked the belts, and every mechanical parts of Y axis.

**Comment by landodragon141** [comment]
Try tuning the chopper settingd

**Comment by teemuatlut** [comment]
Things to try
* Update to latest firmware
* Reduce Y acceleration and/or jerk
* Disable interpolation
* Enable junction deviation
* Set spreadCycle only for Y motor

It seems there's not much information about your motor, specifically the coil resistance and voltage rating.  There's no telling if your motor actually is a good choice in the first place.

**Comment by tobecwb** [comment]
> Update to latest firmware

using Marlin 1.1.9 with latest TMC drivers

> Reduce Y acceleration and/or jerk

max acceleration was "1000", and jerk with 5.0

> Disable interpolation

with interpolation disabled, I got less layer shift, but still exists.

> Enable junction deviation
> Set spreadCycle only for Y motor

I will try

> Try tuning the chopper settingd

How? Any guide to indicate?

**Comment by bruce356** [comment]
Just my opinion, but a 500x500 bed is quite large and heavy, slow right down to compensate. The TMC2130 drivers are probably not power full enough (they are a low power driver) for your application, try a different driver one that matches the amperage capacity of the motor on your Y axis, make sure the stepper is power full enough & fit for purpose.

**Comment by tobecwb** [comment]
Yes, I was already thinking about changing the driver (at least for y axis).

**Comment by InsanityAutomation** [comment]
Mostly agreed with Bruce above, but also try spreadcyle on em for better performance under load as a last resort.

I read through the above a bit more thoroughly and in spreadcyle the noise sounds like it needs vref adjusted. May be on the edge. Video would help.

**Comment by boelle** [comment]
@tobecwb still working on this?

**Comment by tobecwb** [comment]
no!
changed the driver for Y axis...
it's possible to use TMC2130 in my case, but I have to slow down a lot the Y speed / acceleration / jerk.

used a drv8825 on Y, tunned the acceleration and jerk (tried with junction deviation too.. but because of lack of documentation how to tune this, changed back to jerk) and everything is working ok!

I already ordered some TMC2208 to try.. because TMC2208, at least theoretically, can delivery 1.4A...
and the DRV8825 was delivering 1.3A with no layer shift in my case.

I will close this! :D

**Comment by boelle** [comment]
and 2208 run cooler than 2130.

just remember to put fan on them so they get cooled
