### ISSUE TITLE
The blue TEMP_STAT_LED does not turn on after startup

### ISSUE THREAD

**Issue by Santobert** [MarlinFirmware/Marlin#13118]
### Description

I have installed two TEMP_STAT_LEDs onto a MKS Gen L. I've changed my configuration.h to:
```
#define TEMP_STAT_LEDS
#if ENABLED(TEMP_STAT_LEDS)
  #define STAT_LED_RED_PIN 6
  #define STAT_LED_BLUE_PIN 11
#endif
```

When the printer heats up, the red LED lights up as expected. After cooling down, the blue LED turns on.
But immediately after startup, no LED is on until the printer heats up.

### Steps to Reproduce

1. Change configuration.h as described
2. Flash firmware
3. Turn on the printer (no led is on)
4. Heat up (red is on)
5. Cool down and wait (blue is on)

**Expected behavior:** The blue led turns on immediately after startup

**Actual behavior:** No led is on

**Comment by GMagician** [comment]
Fixed

**Comment by Santobert** [comment]
Wow that was fast :)
Thank you

When will it be merged into branch 1.1.x ?

**Comment by GMagician** [comment]
I suspect 1.1.x branch doesn't accept PR anymore (this is for 2.0), but ready to post one if allowed

**Comment by Santobert** [comment]
Oh sad. Maybe i should upgrade to bugfix-2.0.x.
Actually i wanted to wait for the release of stable 2.0.x

**Comment by GMagician** [comment]
I'm using 2.0.x with mega2560 and it works like a charms

**Comment by Santobert** [comment]
I'll give it a try. Thank you

**Comment by GMagician** [comment]
@Santobert I also posted 1.1.x version...even if not merged you may just get source
