### ISSUE TITLE
[bugfix 2.0] Button not working for pause on stow/deploy with G29 P1

### ISSUE THREAD

**Issue by pandel** [MarlinFirmware/Marlin#13114]
Printer: Anycubic Kossel Linear Plus with Trigorilla 1.4, UBL active
Used commit: https://github.com/MarlinFirmware/Marlin/commit/9ae7cca5e969986171052dcfc1bf065a2410245b

PAUSE_BEFORE_DEPLOY_STOW is defined / activated in Configuration.h

When I run step one from UBL mesh generation menu, the printer first executes a G28 and then a G29 P1. During this it asks me to "Deploy Z-Probe", but doesn't react when I hit the button. It simply waits forever.

BUT: when I run "Delta Auto Calibration" it works as expected. The printer is homing all axis, drops the nozzle a bit, asks for "Deploy Z-Probe", I attach the probe and hit the button and the printer begins calibration.

What's going wrong here?

EDIT: FWIW, when I activate BILINEAR leveling, everything works as expected regarding deploy/stow. So it must be something in the G29 or UBL code going wrong here.

**Comment by pixelbucket** [comment]
Same issue here. Sending M108 will get you past "Deploy Z-Probe" but unfortunately you'll hit the same problem at "Stow Z-Probe" and the same solution won't work a second time.

**Comment by boelle** [comment]
tried with todays commit of 2.0?

**Comment by pandel** [comment]
No, at least I didn't. While tuning my printbed a *little*, I went from UBL to bilinear to no leveling at all anymore. Just Z probe offset and be fine...

**Comment by boelle** [comment]
@pandel oki, maybe click close below and open new issue in future if you find the problem again?

**Comment by pandel** [comment]
@boelle Ok, sure :-)!

**Comment by robbycandra** [comment]
Try with bugfix2.0 the problem still exist.
