### ISSUE TITLE
Logic error in UMB

### ISSUE THREAD

**Issue by drpjk** [MarlinFirmware/Marlin#13117]
### Description
I hope I will not be pilloried for this. I am no programmer but reading code for UBL in 1.1.8 ubl_motion -> line_to_destination_cartesion there seems to be logic error in the sections which deal with vertical and horizontal lines.

current_yi += down_flag;
while (current_yi != cell_dest_yi + down_flag) {
    current_yi += dyi
for downward movement this is correct
but for upward movements it move 2 cells which will mean the segment will have the remainder of the first cell plus all of a second cell.
the same applies to the horizontal lines.

I am sorry if I am wasting anyones time with this query

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by drpjk** [comment]
Mea culpa. It must be too late at night. the logic is correct. Please delete post

**Comment by gloomyandy** [comment]
If this is no longer an issue, please close it.

**Comment by Roxy-3D** [comment]
> Mea culpa. It must be too late at night. the logic is correct. Please delete post

Not a problem!  It is nice when a problem just goes away.   :)
