### ISSUE TITLE
[bugfix 2.0] M501 does not make correct line break before OK on trinamic drivers if you do not use stealthChop.

### ISSUE THREAD

**Issue by HansJakob** [MarlinFirmware/Marlin#13124]
### Description

If I use trinamic drivers but do not use stealthchop, Marlin does not make a line break before "OK" when I load the configuration from the EEPROM.

This is due to the function **"SERIAL_EOL_P (port);"** never run in the **"#if HAS_STEALTHCHOP ... #endif"** segment, in the file **"configuration_store.cpp"** if **"stepperY2.get_stealthChop_status()"** is false on all axes.

### Steps to Reproduce

1. Turn on trinamic-drivers in configuration, but turn of stealthchop.
2. Run M501 in the terminal.

**Comment by boelle** [comment]
@HansJakob still working on this?

remember to attach your 2 config files as zip file

@thinkyhead thoughts?

**Comment by boelle** [comment]
@thinkyhead think we can close this one
