### ISSUE TITLE
printing 3D with 1 Extruder

### ISSUE THREAD

**Issue by ROSnoob** [MarlinFirmware/Marlin#13127]
Hi , 

I have an Extruder MK8 and a card Ramps 1.4 installed on a arduino mega 2560, I would like to do 3D printing tests, to be able to install all the systems on a Kuka robot, I realized all the connections, but on arduino and precisely in the configruation file.h I selected the EFF mode because I do not have the Bed or external motors, my question is how can we extrude it directly on arduino, and how can we ignore all configurations because i'm not concerned about (engines, the bed , stepper)

Ps: this is the first time I use the ramps, I do not have much knowledge on the subject, thank you for your help and your attention

**Comment by AnHardt** [comment]
(Currently) impossible.
Extrusion needs to be synchronized with the xyz-motion., so should be managed by the same controller.
The kuka probably can't handle the e-stepper (likely has servo motors)
Marlin currently can't handle the kukas sevo-motors (completely different from model-servos).
Sending the same g-code to both controllers at the same time will not synchronize tight enough.
An other way to synchronize is currently not available.

**Comment by boelle** [comment]
@ROSnoob still working on this?

**Comment by ROSnoob** [comment]
@boelle Yes , I've solved this by creating my own Arduino program without using the entire firmware, I just took the functions that activates the extruder and the stepper motor that has the role of pushing the plastic wire, and for movements I just programmed my robot independently of Marlin .

I close issue, thanks all

**Comment by boelle** [comment]
remember to click close below :-D

**Comment by EdisonAltamirano** [comment]
@ROSnoob  could you please share your code of the Arduino extruder communication with Kuka?
