### ISSUE TITLE
[bugfix 2.0] With G29_RETRY_AND_RECOVER option, Marlin will not compile

### ISSUE THREAD

**Issue by 5a2v0** [MarlinFirmware/Marlin#13139]
### Description

Error while compiling Marlin 2.0.x bugfix in Arduino IDE 1.9 beta (and also with Arduino IDE version 1.8.8) when using #define G29_RETRY_AND_RECOVER

### Steps to Reproduce

1. decomment **#define G29_RETRY_AND_RECOVER** in the Configuration_adv.h file
2. Try to compile

**Expected behavior:** compile without errors

**Actual behavior:** compiling will fail with errors

[config.zip](https://github.com/MarlinFirmware/Marlin/files/2855820/config.zip)

![errors](https://user-images.githubusercontent.com/7579953/52636628-7a81a180-2ecd-11e9-81d7-5ad04746d574.jpg)

**Comment by InsanityAutomation** [comment]
I'm on mobile so I have not looked at your config files, but one thing to keep in mind is that this only supports bilinear and I believe mesh leveling. It does not support ubl.

**Comment by 5a2v0** [comment]
I'm using **#define AUTO_BED_LEVELING_BILINEAR**

**Comment by InsanityAutomation** [comment]
Just took a closer look, can you try with this PR

https://github.com/MarlinFirmware/Marlin/pull/13039

Seems some of the changes to support it got in there in a way it wasnt ready for.

**Comment by InsanityAutomation** [comment]
FYI, a couple fixes have been merged so please test this again and confirm.

Thanks

**Comment by boelle** [comment]
@5a2v0 still working on this?

**Comment by boelle** [comment]
@thinkyhead think we can close this one too :-)

**Comment by npmomchev** [comment]
With G29_RETRY_AND_RECOVER option, Marlin will not compile again. I use last release of Marlin 2.0
