### ISSUE TITLE
controller fan not working with software enable on TMC2130

### ISSUE THREAD

**Issue by Black6spdZ** [MarlinFirmware/Marlin#13133]
Controller Auto fan not working properly with SPI software enable on TMC2130 drivers.

On BIQU SKR v1.1 free pins are at a premium so the drivers were modified tying drivers EN pin to ground and using the controllers enable line for CS on each driver.

I am not currently using my heated bed so I wired the controller fan to P2_05.. 

update: if #define CONTROLLERFAN_SECS is 0, controller fan never starts even when moving steppers.. if any other value the fan runs indefinitely

I'm pretty certain the routines used to sense enabled drivers isn't implemented for SPI enable yet but could be wrong
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2858209/Marlin.zip)

**Comment by LinFor** [comment]
What board and fan connections do you use? Looks like conflict in pin assignments

**Comment by gloomyandy** [comment]
You will need to provide way more than that if you want to get help. Config files, pin files, what version of Marlin? What do you expect to happen, what actually happens.

**Comment by Black6spdZ** [comment]
so is it supposed to work with software enable on SPI connected TMC2130s? on a Biqu SKR 1.1 connected to the fan port P2_03.. I set standard FAN_PIN to -1 and controller fan to correct fan pin assignment.. I'm under the impression as soon as any steppers start moving it should come on correct? I could just keep it as standard part cooling fan and set in start gcode to run.. just hate doing bandaids like this when marlin should properly control it.. extruder auto fan works a treat!

**Comment by gloomyandy** [comment]
Posting your actual config files really does make it easier for people to understand what it is you are doing, because I'm still struggling to understand exactly what it is you have done. Isn't P2_03 used for the normal part cooling fan? Don't you need that? So config files and pins file please.

Also do you have any reason to believe that the software enable has anything to do with this problem? Did you have it working on the same hardware but using the normal enable mechanism?

**Comment by Black6spdZ** [comment]
I just use a combination extruder/parts cooling fan
so in my pins file I set 
#define FAN_PIN            -1 //P2_03 
^ is this the correct to disable normal parts cooling fan operation?

in config_adv I set
#define USE_CONTROLLER_FAN
#if ENABLED(USE_CONTROLLER_FAN)
  #define CONTROLLER_FAN_PIN P2_03 //-1        // Set a custom pin for the controller fan
  #define CONTROLLERFAN_SECS 0          // Duration in seconds for the fan to run after all motors are disabled
  #define CONTROLLERFAN_SPEED 255        // 255 == full speed
#endif

I will try again this evening just to rule out a prior typo. I just thought at first since the software enable is fairly new that this may now work with non-hardware pin enabled drivers

**Comment by Black6spdZ** [comment]
updated original post

**Comment by gloomyandy** [comment]
Try making the stepper enable values non-inverting.... Change
``` C
#define X_ENABLE_ON 0
#define Y_ENABLE_ON 0
#define Z_ENABLE_ON 0
#define E_ENABLE_ON 0 
```
To
``` C
#define X_ENABLE_ON 1
#define Y_ENABLE_ON 1
#define Z_ENABLE_ON 1
#define E_ENABLE_ON 1
```

**Comment by Black6spdZ** [comment]
That did the trick! Is this a specific fix that applies to this particular board or any that use software enable with these particular drivers?

**Comment by gloomyandy** [comment]
It applies to any board using TMC2130 drivers with software enable. It is not a fix just configuring things correctly for that mode of operation.

**Comment by Black6spdZ** [comment]
Ah ok.. I would have never guessed that change would have worked for this particular problem. Did i miss something in comments or documentation?

**Comment by gloomyandy** [comment]
Nope but I think all of the drivers that use software enable expect things that way. It basically comes down to what value they return for the enabled state, which in this case is 1.

No idea if it is documented anywhere I used the best source of documentation, the code itself.

**Comment by gloomyandy** [comment]
I suppose it may get changed in the future so that people do not have to change the config, but it only really impacts code that needs to check the enabled state (and not much does that).

**Comment by Black6spdZ** [comment]
yea, I was going to ask if future config might to checks on say tmc & software enable to flip that state.. so we can close this as its not a bug per se but a little idiot proofing would go a long way to help the project as a whole. Thanks guys!
