### ISSUE TITLE
Ramps EEB + RRD Fan Extender for extruder fan and model cooling fan + BLTouch

### ISSUE THREAD

**Issue by DangerD256** [MarlinFirmware/Marlin#13145]
I have ramps 1.4 with dual extruders and i want to connect 2 fans and BLTouch
1. Cooling fan for printing PLA controllable from LCD display and gcode.
2. Extruder fan auto on. (EXTRUDER_0_AUTO_FAN_PIN as i understood)
3. BLTouch
What should i change in configuration to make both work?
For printfan D4 is already set, for extruder i'll set EXTRUDER_0_AUTO_FAN_PIN 5
Also can i use BLTouch with that? As i read docs it also uses same port...

**Comment by AnHardt** [comment]
Displace the fan extender two pins to the right. That will servo 0 and 1 let usable for servos/bl-touch

**Comment by J-charles-C** [comment]
I,

http://www.3dmodularsystems.com/img/cms/RRD/RRDFanExtender_BLTouch.jpg

best

**Comment by boelle** [comment]
@DangerD256 still working on this?

**Comment by boelle** [comment]
@thinkyhead think we can close this one

**Comment by DangerD256** [comment]
Changed pin in ramps pin file, all works fine except when I try to calibrate bed using bltouch it starts measuring outside of bed, but that's another story

**Comment by boelle** [comment]
so if that is not related to this one maybe click close below?
