### ISSUE TITLE
[1.1.9] Using 2 individual Neopixel Strips (Caselight and "Printlight")

### ISSUE THREAD

**Issue by jb2304** [MarlinFirmware/Marlin#13161]
Hi everyone,
i'm trying to get 2 individual Neopixel-Strips working.
I got one strip on the Printer itself to light up the printing area. I also want to use it as "Printer-LED", that also shows the "printer events". 
It works as intended when i activate the lines in the codes.

The second strip is mounted in the case. I want to use this strip as case-light. It would just need to light up in the colour i set it to via the LCD-caselight-menu.
I tried "CASE_LIGHT_USE_NEOPIXEL" but with this option the caselight uses the same strip as the "Printer-LED". The second Strip does not light up at all.

Is it possible to use 2 Neopixel strips, controlled by different Pins on the board?

Thanks for any help.

**Comment by 7eggert** [comment]
There seems to be only one set of LED being supported, but in RGBW - if your case light was white only, you could make it work.

**Comment by jb2304** [comment]
A while ago i had a setup with standard rgbw strips. It worked fine, but it required 8 PWM Pins to be fully controllable. But now i don't have 8 free pins in my current setup. That was the reason i wanted to switch to neopixels. I wanted to be able to control the 2 strips only using 2 pins.

**Comment by 7eggert** [comment]
I have a similar idea, so if you'd share your once-working config file, I might happen to actually implement it, but I'm thinking about using a PCA9685.

**Comment by fred2088** [comment]
do you set to use different pin   ?
#define CASE_LIGHT_PIN 4 
#define NEOPIXEL_PIN    5

**Comment by 7eggert** [comment]
Currently I discovered the RGB PWM pins and your issue made me aware of possibly supporting more than one set of LED. I hoped to learn from your past experience.

**Comment by jb2304** [comment]
Hi, yes i set the Case and Neopixel Pin to different Pins. The commands where still using the same strip.

I've been through my files but i could not find my old build.
I basically definded 4 Pins for Standard Printer_LEDs (RGBW). For the caselights i defined another 4 pins in the Pins file and added a custom menu for it. So i was not using the standard caselight-menu.

**Comment by fred2088** [comment]
Neopixel only need 1 data pin to work with, case light and progress light need to be different pin...

**Comment by boelle** [comment]
@jb2304 please use bugfix 2.0

1.1.9 has been put in the grave a long time ago

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
