### ISSUE TITLE
Pause LCD Menu - purge more causes continue

### ISSUE THREAD

**Issue by bjbeare** [MarlinFirmware/Marlin#13178]
### Description

Filament Change menu item is confused.

When menu_advanced_pause_option() is called, the first menu item is "Purge more". This is consistent with the observed behaviour. The odd thing though is that selecting the menu pick causes an lcd_advanced_pause_resume_print() action. Selecting the "Continue" option causes further filament to be purged.

The code looks OK... but the behaviour on (at least my) printer is wrong.

### Steps to Reproduce

Perform a change filament operation for PLA.
This can be either on an idle machine or one in a print. The behaviour is the same.

**Expected behavior:** [What you expect to happen]
The action should correspond to the menu item.

**Actual behavior:** [What actually happens]
The menu picks are reversed.

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#how-can-i-contribute) for additional guidelines.

**Comment by bjbeare** [comment]
I don't see a problem with the code... and this looks like a 'stale build data' kind of problem. I cleaned out my temp directories in case something is being cached... but could well have missed something. I use the Arduino IDE.

**Comment by InsanityAutomation** [comment]
Can you confirm which date your snapshot was from? Ill test it again on this end with the current snapshot, But I want to be sure that you were working with a build after host prompt support was merged.

**Comment by bjbeare** [comment]
commit e00aad84afe1660bc27da6e3ea4db1f73a183474 (origin/bugfix-2.0.x)

**Comment by InsanityAutomation** [comment]
Thanks, can you post your configuration files as well? Just bumped my build to today and ill be flashing again shortly.

**Comment by InsanityAutomation** [comment]
My machine showed the same symptom. Found the problem and ill have a PR opened to fix it shortly.

**Comment by bjbeare** [comment]
Thanks!

**Comment by boelle** [comment]
@bjbeare so your issue is solved? maybe close this one

**Comment by bjbeare** [comment]
@boelle 
Verified. Thank you for the fix.
