### ISSUE TITLE
Marlin 2 won't compile

### ISSUE THREAD

**Issue by ISAndreiva** [MarlinFirmware/Marlin#13180]
Useing Arduino IDE 1.9 BETA and I can't comply marlin 2.0.
I am trying this in hopes to fix and tmc2130 issue.
I don't know if I need to add anything in this BUG report..
Report mesage:
[bug report.zip](https://github.com/MarlinFirmware/Marlin/files/2870766/bug.report.zip)

**Comment by ghost** [comment]
I gave a quick look and it seems like your config files are outdated, you'd probably get it to compile if your config.files were not missing latest additions.

**Comment by ISAndreiva** [comment]
Yes that was the issue thank you !

În sâm., 16 feb. 2019, 13:35 Sebastian Oyster <notifications@github.com a
scris:
