### ISSUE TITLE
Marlin 2.0 vs 1.1.9 XYZ calibration cube surface finish

### ISSUE THREAD

**Issue by engelbja** [MarlinFirmware/Marlin#13186]
Good day all
Have posted this at https://reprap.org/forum with no replys.

Have downloaded bugfix-2.0.x from [marlinfw.org] 2weeks ago
When printing a xyz calibration cube I get surface problems as per attached picture.

This defect will be printed when the xyz cube are exactly in the middle of my delta printer build plate and only on the Y axis - when I move it 30mm left/right/front/back - no problems. This told me that there are a mechanical problem. The anycubic linear plus are 2 months old, but I removed my rails, cleaned & oiled them (smooth as butter) and also checked, motor pinions and belts, stepper voltages. Exactly the same problem happening after this.
I moved back to marlin 1.1.9 and no issues - surface finish are 100%
I moved back to 2.0 and problem is back.

My feed rates/acceleration/jerk are copied from 1.1.9 and I basically copied all my other settings from 1.1.9 to 2.0.
I use exactly the same gcode.
1st picture are 1.1.9 and 2nd are 2.0 ( The xyz cubes were only printed 50% because the problem are at the bottom - On the side you will see where the Y start, just beneath it are the problem)
![img_20190212_145530](https://user-images.githubusercontent.com/46456499/52902511-43d3c000-321a-11e9-85d8-1e53f24166ed.jpg)
![img_20190212_144517](https://user-images.githubusercontent.com/46456499/52902513-49c9a100-321a-11e9-9b81-c0e4521dc182.jpg)

**Comment by landodragon141** [comment]
Please upload a copy of your configuration files.

**Comment by engelbja** [comment]
Sorry here it is

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2872970/Marlin.zip)

**Comment by boelle** [comment]
Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D
