### ISSUE TITLE
Commit 9472bbe causing constant "ok" responses when no timeout is set

### ISSUE THREAD

**Issue by wgm4321** [MarlinFirmware/Marlin#1318]
@i-make-robots

Commit 9472bbe causing constant "ok" responses when no timeout is set

This code causes the firmware to constantly send "ok" when the printer is idle as max_inactive_time is by default 0.   Note that the kill() is protected by testing for a non-zero max_inactive_time.   However, the "ok" response generation is not so when max_inactive_time is zero, millis() - previous_millis_ok) >  max_inactive_time/4  is always true.

```C
   if( (millis() - previous_millis_cmd) >  max_inactive_time )
     if(max_inactive_time)
       kill();

	// If 'OK' is garbled on sending PC won't receive it.  Both machines will wait on each other forever.
	// This resends OK if nothing is heard from PC for a while to avoid this bad case.
        if( (millis() - previous_millis_ok) >  max_inactive_time/4 ) {
		SERIAL_PROTOCOL(MSG_OK);
		previous_millis_ok=millis();
  }

```

**Comment by ErikZalm** [comment]
This issue was moved to MarlinFirmware/Marlin#1

**Comment by avluis** [comment]
Just saw this. Glad it wasn't just me (after updating my fork to latest dev).

**Comment by ErikZalm** [comment]
I reverted the patch.
It is not a good idea to send random oks. (Unless tested it works ok with all host software)
This is a known problem. If the fix was this simple it would be implemented a long time ago.
The reprap protocol is not very robust. But it is difficult to change.

**Comment by boelle** [comment]
Q... are you not also behind cura? if so could cura not be the first to use a better protocol?

but if a new protocol is needed how many host softwares need to be behind such a change? pronterface is one i guess...

**Comment by i-make-robots** [comment]
Not good because?

Printer recieves line N.
Printer Sends OK twice.
PC receives extra OK.
PC sends next line N+1 and N+2.
Printer says BADLINENUM?

If Marlin designs to make host happy and host designs to make Marlin happy
it's a giant game of chicken.  Someone has to go first.


On Wed, Jan 7, 2015 at 3:15 PM, Erik van der Zalm <notifications@github.com>
wrote:

> I reverted the patch.
> It is not a good idea to send random oks. (Unless tested it works ok with
> all host software)
> This is a known problem. If the fix was this simple it would be
> implemented a long time ago.
> The reprap protocol is not very robust. But it is difficult to change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarlinFirmware/Marlin/issues/1318#issuecomment-69110134>
> .
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by boelle** [comment]
host uses a protocol.... marlin has to use the same...

problem here is the protocol is not robust enough... its does not have
anything to do with making anybody happy... the protocol has to be
changed... of course more easy said than done

2015-01-08 0:21 GMT+01:00 Dan Royer <notifications@github.com>:

**Comment by nophead** [comment]
If the OK is garbled the host should time out waiting for it and send something to invoke one. It shouldn't wait forever, so I think there needs to be a change to the protocol even if it is weak.

**Comment by i-make-robots** [comment]
I agree, Chris.  One change in Marlin is easier than one change in every
host.

On Wed, Jan 7, 2015 at 4:15 PM, Chris <notifications@github.com> wrote:

> If the OK is garbled the host should time out waiting for it and send
> something to invoke one. It shouldn't wait forever, so I think there needs
> to be a change to the protocol even if it is weak.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarlinFirmware/Marlin/issues/1318#issuecomment-69116366>
> .
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by alexborro** [comment]
I'm facing a problem with such "OKs".... I use the serial for debugging the
code - unfortunately I don't have a JTAG...

Check the result of a single "M114" command sent by pronterface:


​

Cheers.

Alex.

2015-01-07 22:53 GMT-02:00 Dan Royer <notifications@github.com>:

> I agree, Chris. One change in Marlin is easier than one change in every
> host.
>
> On Wed, Jan 7, 2015 at 4:15 PM, Chris <notifications@github.com> wrote:
>
> > If the OK is garbled the host should time out waiting for it and send
> > something to invoke one. It shouldn't wait forever, so I think there
> needs
> > to be a change to the protocol even if it is weak.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/MarlinFirmware/Marlin/issues/1318#issuecomment-69116366>
>
> > .
> >
>
>
>
> --
> Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
> Raising Robot Literacy :: +1.604.916.2281
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarlinFirmware/Marlin/issues/1318#issuecomment-69119692>
> .
>



-- 
*"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )*

Alex Borro

**Comment by ErikZalm** [comment]
In my opinion think the host should timeout.
The firmware does not know when to expect a command. The host knows it send a command and expects an acknowledge.
The firmware can not acknowledge on something it does not receive.
Don't make a host problem a firmware problem.
At best we can send a "waiting for new command".

**Comment by bkubicek** [comment]
one might abuse a Serial info message for that, that can be sent to the
host. A default hosts will just show it on the screen, a clever host might
understand it.

Bernhard

**Comment by nophead** [comment]
Octoprint already does time outs and resends so I don't think it hangs on a missing OK.

Note that with correct hardware and software you should never need a resend. The USB protocol has a transport layer than already does CRC checks and resends. The data that arrives should always be correct even in the presence of noise or you get a disconnect. This is what happens for me with Marlin on Melzis. I never ever see corrupt data. 

Boards that do must either have bad track layout for the serial link between the USB chip and the atmega or perhaps baud rate errors or buffer overruns in the firmware. If you fix your hardware there is no longer a need for an error correcting protocol. USB already provides that.

**Comment by i-make-robots** [comment]
That's what OK means to me.

**Comment by lordofhyphens** [comment]
That  commit breaks pretty much everything, IMHO, current octoprint and Printrun. Printrun is less broken in that it just fills the UI with messages.

That commit is sitting in master branch. 

I've reverted it for my own use.

**Comment by boelle** [comment]
we dont use the master branch

**Comment by lordofhyphens** [comment]
Then what branch should people be using when trying to download/compile? Development? I didn't see a stable in this repo. -.-

**Comment by boelle** [comment]
yep dev.... we are still bug fixing, a stable release will not come before all bugs are sorted and we have tested the code to be stable... thou we lack coders that can help out and that can worked focused on the bugs

**Comment by lordofhyphens** [comment]
On 01/11/2015 04:26 PM, Bo Herrmannsen wrote:
>
> yep dev.... we are still bug fixing, a stable release will not come 
> before all bugs are sorted and we have tested the code to be stable... 
> thou we lack coders that can help out and that can worked focused on 
> the bugs
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MarlinFirmware/Marlin/issues/1318#issuecomment-69514897>.
>
I'll see what I can do to test stuff, but from looking at the many 
issues on github, I haven't noticed any of these bugs on my config.

-- 
--Joseph Lenox, BS, MS
I'm an engineer. I solve problems.

**Comment by boelle** [comment]
ok... https://github.com/MarlinFirmware/Marlin/milestones

these are the 2 milestones set so far... in them the most important bugs are listed....

if you are good at doing code we can use all the help we can get

**Comment by boelle** [comment]
@ErikZalm was this one fixed by your revert?

**Comment by boelle** [comment]
i will assume this one is fixed 

closing... reopen if needed
