### ISSUE TITLE
Where is the Marlin2.0 bootloader jump address in the STM32F103XXX, in which file to change?

### ISSUE THREAD

**Issue by bigtreetech** [MarlinFirmware/Marlin#13199]
### Description
Hi,Folks ,
We are developing BIGTREETECH SKR MINI V1.0,  which will be Very cost-effective product in Aliexpress. 
We have a problem： 
Where is the Marlin2.0 bootloader jump address in the STM32F103XXX, in which file to change？
(vscode  +platformIO)
Thanks

**Comment by thinkyhead** [comment]
I guess you figured out the bootloader and Marlin are two completely different things.
