### ISSUE TITLE
Einsy rambo 1.1a display and z-axis problems

### ISSUE THREAD

**Issue by thomaswang04** [MarlinFirmware/Marlin#13195]
Switch the main board on a cr-10 with a einsy rambo 1.1a. X and Y axis motors work perfectly fine however the z-axis is noticeably louder and will move on its own without commands. When a command is given to the z-axis it is very lound and jerky. I also have a problem with the display. I bought a mks display. However it only lights up and dosent show anything on the screen.

[Config and advanced config.zip](https://github.com/MarlinFirmware/Marlin/files/2873938/Config.and.advanced.config.zip)

**Comment by boelle** [comment]
Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D
