### ISSUE TITLE
Z offset adjust - err too far

### ISSUE THREAD

**Issue by HuguesDug** [MarlinFirmware/Marlin#13209]
Config:
Marlin 1.1.9 bug fix (was previously 1.1.9, 1.1.8 and manufacturer firmware).
Anet A8 with bed leveling sensor (manufacturer)

Problem:
I cannot adjust z offset from the LCD screen.
It returns a message: err too far.

No clue how to fix that.

As a workaround, I use Arduino IDE, change the value Z_PROBE_OFFSET_FROM_EXTRUDER in firmware, upload, M502 and M500.
It works, but is everything but easy and fast.

Any solution so the LCD menu do not return an error message ?

**Comment by boelle** [comment]
Please test with the latest `bugfix-2.0.x`

**Comment by HuguesDug** [comment]
I will... but I am not sure It will fit inside the EPPROM of the Anet board ! I am already full at 99% with current options.

**Comment by boelle** [comment]
then pick important options first or replace with better board :-D

**Comment by thinkyhead** [comment]
If you see that error, you're not adjusting the Z probe offset value. You're adjusting the `M206` (aka `M428`) "Home Offset" value.

**Comment by HuguesDug** [comment]
Hello thinkyhead.

My printer is in French :-)  So I guess your translation is the right one "home offset value". 
#define MSG_SET_HOME_OFFSETS                _UxGT("Regl. decal. origine")

And yes, it seams it is related to "M206". So, what is the cause of the error, and how to fix it ?

**Comment by thinkyhead** [comment]
You most likely don't really want to use home offsets, so just don't use them. If you actually must use them, you have to be within 2cm of an endstop to use that menu item or `M428`.
