### ISSUE TITLE
[2.0.x]Move Axis -> Move E -> FW Reset

### ISSUE THREAD

**Issue by reloxx13** [MarlinFirmware/Marlin#13213]
### Description

Heya,

if i use the LCD menu Move Axis -> Move E, choose a distance (e.g. 1mm) and than try to extrude filament, the firmware crashes.
E Stepper is working 1-2 seconds, LCD turns blank and it resets, showing the homescreen after a few seconds.

The Nozzle is heated above "min extrude temp" (test heated to 230°C).

Extruding works fine with octoprint controls or entering `G1 E15 F500` in terminal.

Just the lcd menu crashes the fw while trying to extrude manually.

#### Additional Information

Im on 2.0.x-bugfix from Feb 15, 2019.

Printer: Ender 3 with orginal Board. TL Smoothers on X and Y. ABL added.

You can find my fw configuration here on GitHub:

https://github.com/reloxx13/Marlin/blob/my-marlin/Marlin/Configuration.h
https://github.com/reloxx13/Marlin/blob/my-marlin/Marlin/Configuration_adv.h

**Comment by thinkyhead** [comment]
It's possible that the your "manual feedrate" setting for E is too high for the MCU to keep up. If this is the case, then lowering your `M203 E` value should prevent the reboot. You can get the current value using `M503 S0` in the host console.

**Comment by reloxx13** [comment]
ill try this, thanks for the hint!

**Comment by reloxx13** [comment]
heya,

changing the feedrate to 25 did not help, still resets during move e with lcd

no temrinal error message outputting, just a reset with no reason.

Edit: also tried with an Acceleration of 100.
```
Recv:  T:220.00 /220.00 B:22.66 /0.00 @:59 B@:0
Recv:  T:219.90 /220.00 B:22.54 /0.00 @:61 B@:0
Recv:  T:219.90 /220.00 B:22.58 /0.00 @:61 B@:0
Recv:  T:219.95 /220.00 B:22.66 /0.00 @:60 B@:0
Recv:  T:219.95 /220.00 B:22.62 /0.00 @:60 B@:0
Recv: start
Printer sent 'start' while already operational. External reset? Resetting line numbers to be on the safe side
Send: N0 M110 N0*125
Recv: echo:Marlin bugfix-2.0.x
Recv: 
Recv: echo: Last Updated: 2018-01-20 | Author: (ReloxX)
Recv: echo:Compiled: Feb 22 2019
Recv: echo: Free Memory: 9761  PlannerBufferBytes: 2912
Recv: echo:V64 stored settings retrieved (635 bytes; crc 17080)
Recv: echo:  G21    ; Units in mm (mm)
Recv: echo:  M149 C ; Units in Celsius
Recv: 
Recv: echo:Filament settings: Disabled
Recv: echo:  M200 D1.75
Recv: echo:  M200 D0
Recv: echo:Steps per unit:
Recv: echo: M92 X80.00 Y80.00 Z400.00 E93.00
Recv: echo:Maximum feedrates (units/s):
Recv: echo:  M203 X5000.00 Y5000.00 Z20.00 E25.00
Recv: echo:Maximum Acceleration (units/s2):
Recv: echo:  M201 X800.00 Y800.00 Z100.00 E5000.00
Recv: echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
Recv: echo:  M204 P4000.00 R1000.00 T4000.00
Recv: echo:Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
Recv: echo:  M205 B20000.00 S0.00 T0.00 X20.00 Y20.00 Z0.30 E5.00
Recv: echo:Home offset:
Recv: echo:  M206 X0.00 Y0.00 Z0.00
Recv: echo:Auto Bed Leveling:
Recv: echo:  M420 S0 Z0.00
Recv: echo:  G29 W I0 J0 Z-0.00083
Recv: echo:  G29 W I1 J0 Z-0.02583
Recv: echo:  G29 W I2 J0 Z-0.07417
Recv: echo:  G29 W I3 J0 Z-0.07000
Recv: echo:  G29 W I4 J0 Z-0.04167
Recv: echo:  G29 W I0 J1 Z-0.08250
Recv: echo:  G29 W I1 J1 Z-0.11583
Recv: echo:  G29 W I2 J1 Z-0.11750
Recv: echo:  G29 W I3 J1 Z-0.10417
Recv: echo:  G29 W I4 J1 Z-0.07667
Recv: echo:  G29 W I0 J2 Z-0.12083
Recv: echo:  G29 W I1 J2 Z-0.13333
Recv: echo:  G29 W I2 J2 Z-0.12250
Recv: echo:  G29 W I3 J2 Z-0.05833
Recv: echo:  G29 W I4 J2 Z-0.03833
Recv: echo:  G29 W I0 J3 Z-0.11250
Recv: echo:  G29 W I1 J3 Z-0.13833
Recv: echo:  G29 W I2 J3 Z-0.11167
Recv: echo:  G29 W I3 J3 Z-0.07583
Recv: echo:  G29 W I4 J3 Z-0.06417
Recv: echo:  G29 W I0 J4 Z-0.04750
Recv: echo:  G29 W I1 J4 Z-0.08417
Recv: echo:  G29 W I2 J4 Z-0.07917
Recv: echo:  G29 W I3 J4 Z-0.07833
Recv: echo:  G29 W I4 J4 Z-0.06750
Recv: echo:Material heatup parameters:
Recv: echo:  M145 S0 H220 B70 F0
Recv: echo:  M145 S1 H240 B0 F255
Recv: echo:PID settings:
Recv: echo:  M301 P20.05 I1.45 D69.41
Recv: echo:  M304 P320.15 I60.12 D426.20
Recv: echo:Z-Probe Offset (mm):
Recv: echo:  M851 Z-2.42
Recv: ok
Send: N0 M110 N0*125
Recv: ok
Send: M155 S2
Recv: ok
```

**Comment by thinkyhead** [comment]
Unable to reproduce crashing during E movement.

Make it even lower. Or use half as many micro-steps on the E axis and cut the e steps-per-mm in half.

**Comment by reloxx13** [comment]
In short: 
ADAPTIVE_STEP_SMOOTHING is causing the crash.

did u have this feature enabled when u tried to reproduce it?

but i wont understand what this should have to do with move e, its for moving multiple axes at same time as i understood. And also why it wont crash if moving E by terminal/gcode.


Long stroy and atleast one bottle of beer while waiting for heat to test move e:

M350 microsteps are disabled

Tried 
Maximum feedrates/acceleration  E1.00 now, same result.

Reflashed with latest 2.0.x bugfix from 2019-02-25
Used default example config for ender 3 from \Marlin\src\config\examples\Creality\Ender-3
PIO Cleaned before build
Resetted with M502
Works >.<

Example config and my config_adv
Stops working

My config and default config_adv
Works

Try and Error every feature i enabled in my config to find the issue.
Crash after enabling ADAPTIVE_STEP_SMOOTHING

Reverted everything to my config_adv, disabled ADAPTIVE_STEP_SMOOTHING
Works

Enabled ADAPTIVE_STEP_SMOOTHING again
crash on move e

**Comment by thinkyhead** [comment]
> ADAPTIVE_STEP_SMOOTHING

That is good to know. Maybe it has to be in combination with some other things to cause the crash, or maybe it is just over-taxing your board. It may be that the feature adds too much overhead, but interactions with other features is always possible.

The feature was largely implemented by @ejtagle and has not been modified since that time. It works well for many setups, but edge cases are always possible.

**Comment by reloxx13** [comment]
> 
> 
> > ADAPTIVE_STEP_SMOOTHING
> 
> That is good to know. Maybe it has to be in combination with some other things to cause the crash, or maybe it is just over-taxing your board. It may be that the feature adds too much overhead, but interactions with other features is always possible.
> 
> The feature was largely implemented by @ejtagle and has not been modified since that time. It works well for many setups, but edge cases are always possible.

but only over the lcd? is the lcd producing so much overhead just for E movement?
XYZ works fine, its just the E with the LCD. E movement over terminal works fine, too.

And the LCD code and the Extruder count got some rework not long ago. 
But just from looking/following the code i could not find an error (im not a C dev).

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by reloxx13** [comment]
more and more post about it in facebook creality groups.
