### ISSUE TITLE
INCH_MODE_SUPPORT should define G21 as a NOOP if undefined

### ISSUE THREAD

**Issue by b-morgan** [MarlinFirmware/Marlin#13228]
### Description

If INCH_MODE_SUPPORT is undefined, G20 is an unknown command as it should be (Marlin is, by default, operating in metric mode). G21, however, is found in many slicers and printer start gcode sections and should be accepted (as a NOOP) to avoid the unknown commands.

### Steps to Reproduce

1. Compile firmware with INCH_MODE_SUPPORT undefined
2. Load firmware into a printer
3. Issue a G21 command

**Expected behavior:** [What you expect to happen]

G21 is a NOOP

**Actual behavior:** [What actually happens]

Receive an echo:unknown command response

#### Additional Information
 
None

**Comment by marcio-ao** [comment]
@b-morgan: Genius! We actually had gone through the start GCODE for our printers to get rid of the G21, but in retrospect your idea is way better! Pushed a PR to fix this!
