### ISSUE TITLE
reprap discount full graphics LCD display not working

### ISSUE THREAD

**Issue by hawkan-rules** [MarlinFirmware/Marlin#1322]
I've defined  REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER in configurations.h. When I start the electronic it just shows the backlights and no text or nothing. 

Versions:
Running Marlin commit: 3d9f4ac7576e6f23a70f8d7986a6388d889ef9e4
U8glib:  version 1.16  and  version 1.17
Arduin: 1.0.6

I've tried a few older versions but havent got it working! :(

My printer is an Prusa I3 from replikeo.com http://replikeo.com/en/KIT001

**Comment by hawkan-rules** [comment]
Auto bed level is also enabled if that makes any difference.

**Comment by alexborro** [comment]
Are you sure your LCD is working properly with your board? Have you ever
got them working together with any other firmware?
Em 06/01/2015 14:03, "hawkan-rules" <notifications@github.com> escreveu:

**Comment by hawkan-rules** [comment]
Nope havent been able to see anything on the display at all! Is there some way to troubleshot the connection with the display??

**Comment by stv0g** [comment]
There are cheap logic analyzers out there. Or use an oscilloscope.

**Comment by JoshyuNL** [comment]
For me it works fine. Make sure you're wires are all connected correctly like mentioned above.
I think I've had it before that my wires were switched and I got a similar issue.

I've updated my copy of marlin this evening, haven't checked the changes in the last few days to see if they did anything to it but someone would've probably said something by now if they had.

**Comment by boelle** [comment]
@hawkan-rules still having trouble?

**Comment by hawkan-rules** [comment]
@boelle yes! 

I've also tried to rotate the cables 180 degress as well. Noting seems to be helping, I'm trying to get the display replaced by the seller as i suspect that it is broken.

**Comment by boelle** [comment]
also remember we are working on it

any chance you use thermocouples and not thermistors?

Den lørdag den 10. januar 2015 skrev hawkan-rules <notifications@github.com

**Comment by hawkan-rules** [comment]
@boelle I'm using a thermistors

**Comment by Grogyan** [comment]
I only get this in the current Development branch when using the MAX6675 thermocouple
What Thermistor are you using?

**Comment by hawkan-rules** [comment]
@Grogyan: Thermistor NTC100K3950 3950-1%

This is how my configuration.h looks like:
//1 is 100k thermistor - best choice for EPCOS 100k (4.7k pullup)

#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_BED 1

**Comment by boelle** [comment]
@hawkan-rules did you get the display replaced?

**Comment by hawkan-rules** [comment]
@boelle Nope and I'm guessing it might take two or three weeks before I get it! :S If you want you guys can resolve this issue and I'll repoen if the replacement isnt working.  Thanks for the help though!

**Comment by boelle** [comment]
reopen? we have not closed it... but these displays are on the SPI bus and we have several issues where its the SPI bus.... spi devices each need their own CS line so the MCU can tell what device it wants to talk to... as long there is only one device it MIGHT work... but really even if only one device it should use the CS line...

**Comment by Grogyan** [comment]
Problem is not related to thermocouple. I can't replicate it unless the cables are switched over.

**Comment by Grogyan** [comment]
Interesting to note that I have either blown up my LCD/Arduino, while testing out some other stuff.
Currently experiencing the same as OP, same config - no thermoouple.
Meaning that it is a hardware problem.

**Comment by hawkan-rules** [comment]
Got my new display and it worked! :)
