### ISSUE TITLE
BL touch not working

### ISSUE THREAD

**Issue by Telekmac** [MarlinFirmware/Marlin#13238]
I was just using my bl touch and I have had the configuration set and have e=been printing successfully with it for months. But just recently the probe stopped deploying all together. The self test fails and anything that requires deploying it fails. If i open it myself and do the reset command it will retract but not deploy. No firmware changes have been made besides readjusting the z offset.

**Comment by psavva** [comment]
Hi Telekmac, 

So you're saying you had no firmware changes.
Your probe is failing to deploy.  Sounds like a BLTouch hardware issue.

Start by checking all the wiring and also check the PIN.  Why did you need to adjust the z-offset after months of successful printing...  Maybe the  pin  is loose/dropped...

**Comment by boelle** [comment]
what @psavva said ^^^

**Comment by mr-miky** [comment]
It could also be a PWM problem on the control pin

**Comment by boelle** [comment]
could a to cheap board or controller board with badly picked parts be part of the problem? or maybe a noisy psu?

**Comment by einencool** [comment]
I had the problem, with a cheaper 3D Touch that the wire to the solenoid was broken. It was broken under the original tape at the top of the device...

It sounds a little bit similar..

**Comment by Telekmac** [comment]
I will be checking the wires for contunity tomorrow. I had to adjust the
offset fue to installing a glass bed. I dont think it is a board issue but
i will check.
