### ISSUE TITLE
[FR] Support for Slic3r PE M73

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#13249]
as the title says we should support slic3r PE's version of M73 which has the following format

![image](https://user-images.githubusercontent.com/3832239/53299650-6595fe00-383d-11e9-82a4-b040c57ff86a.png)

**M73 Pxxx Qxxx Rxxx Sxxx**
where P is the percentage of the total time already printed in normal mode, R is the time remaining for normal mode in minutes, Q is the percentage of the total time printed in the stealth mode, and S is the time remaining to the end of print in the stealth mode.

my suggestion would be to use the time to display the remaining time in current mode 
consider it a partner request to https://github.com/MarlinFirmware/Marlin/issues/13248

**Comment by brandstaetter** [comment]
Does Slic3r PE always write it out like that or only if the silent mode support is active?
![image](https://user-images.githubusercontent.com/644820/53305027-80d42e00-387c-11e9-84c7-f53ca47dfeee.png)

**Comment by boelle** [comment]
i have not tested it myself but i can do so tomorrow, ie generate some sample Gcode and post it here as a zip

**Comment by boelle** [comment]
btw... i run my printer as if it was an mk2.5, firmware has same movement settings etc as the mk2.5

the only changes i have is start and stop gcode and i print with 3 walls and not 2. other that its stock slicer settings

**Comment by revilor** [comment]
When you enable "Supports remaining times" in Printer Settings the gcode will contain M73 P.. R... When you enable "Supports silent mode" it will add additional M73 Q.. S...

**Comment by boelle** [comment]
more or less the same @einencool said :-D so i was not far off

**Comment by einencool** [comment]
Oh, I think there is a little mistake ;-)

In the picture in post number 1 there is the normal status bar and the text at the end was only a 
M117 command 
which was a replacement for the original M73 Pxxx Rxxx
I replaced it with Notepad++ and hoped, that it will count down in the status bar. 
The counter (ie 03:00) was there normal upcounting one...

But the M117 commands weren’t recognized any more, so it shows me all the time 185 min left...

Does anybody know how to get the variable for the „remaining print time“ or the complete print time counter from Slic3r??
Then I would just add this in the start gcode and will have the normal counter and in the status bar the whole time

**Comment by boelle** [comment]
that is what we should figure out...

i wrote that 03:00 could be used as the remaing time in whatever mode the printer is in
i say whatever mode because we dont have silent mode supported, but it could be that we get it, at least we should account that we will have silent mode some day

**Comment by boelle** [comment]
progress bar above 03:00 should jsut be updated with the % number from M73

**Comment by boelle** [comment]
but city of rome was not build in a day so it will take some time i'm sure

but since i'm not a coder it will have to be done on the mercy of others

**Comment by einencool** [comment]
The gcode from the picture doesn’t contain a M73 command. 
And in the config adv i haven’t activated the M73 option.
Yeah, would be great if it can work. But in my mind it would be even better to see the processing time AND the remaining time or the complete time.

In the gcode from slic3r PE is at the end the complete processing time , and when it would be possible to get this info on the screen instead of the program name, that would be great.
For me the Program name is not so important, Lately when the job is done, I know what it should be.....

**Comment by boelle** [comment]
@einencool we are not quite talking about your issue even thou its close related...

but yes... both printed time and time remaing time would be optimal... and it would have to work on both text displays and graphics ones

**Comment by boelle** [comment]
let's see what the code gods come up with

**Comment by ilachEU** [comment]
basic implementation for DOGM (changed files only)
[M73.zip](https://github.com/MarlinFirmware/Marlin/files/3002744/M73.zip)

**Comment by GMagician** [comment]
This may be closed now...I think

**Comment by rmoravcik** [comment]
Remaining time support was merged to bugfix-2.0.x (https://github.com/MarlinFirmware/Marlin/commit/e110f5abce90d139a768242780780832b09aa297)
