### ISSUE TITLE
[BUG] I2C OLED not working on LPC1768

### ISSUE THREAD

**Issue by obertr0n** [MarlinFirmware/Marlin#13257]
### Description

Tried to configure an LPC1768 based mainboard (Biqu SKR V1.1) to use an 0.96 SSD1306 OLED display. For connection I'm using P0.0 and P0.1 pins.

### Steps to Reproduce

1. In Configuration.h uncomment `#define U8GLIB_SSD1306`
  In pins_BIQU_SKR_V1.1.h I have set the E1 pins to -1:
  ```cpp
  #define E1_STEP_PIN        -1//P0_01
  #define E1_DIR_PIN         -1//P0_00
  #define E1_ENABLE_PIN      -1//P0_10
  ```

2. Connect `OLED_SDA` to `P0_0` (DIR pin)
  Connect `OLED_SCL` to `P0_1` (STEP pin)

3. Flash and reset

**Expected behavior:**
Display should operate properly and show all the info.

**Actual behavior:**
Display stays blank

#### Additional Information
I also tried to inspect the I2C bus with a cheap logic analyzer, but I'm not really familiar with SSD1306 chip. I can provide traces from PulseView if necessary.

**Comment by boelle** [comment]
where are the 2 config files ? put them here in a zip file

**Comment by kAdonis** [comment]
Many of these OLEDs can be configured by solder jumpers, check if yours is configured to use I2C and not SPI and verify it is using I2C slave address 0x3C

**Comment by obertr0n** [comment]
@kAdonis This is the display that I have, I did tested it with a bare Arduino code and it works OK over I2C.
![image](https://user-images.githubusercontent.com/10163987/53360748-07e9da80-393f-11e9-946e-b3a5374b01e1.png)
@boelle I did attached the ZIP with the Config files.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2902216/Configuration.zip)
And the pinout of the SKR
[SKR V1.1 PINOUT.pdf](https://github.com/MarlinFirmware/Marlin/files/2902218/SKR.V1.1.PINOUT.pdf)
pins.h file
[pins_BIQU_SKR_V1.1.h.zip](https://github.com/MarlinFirmware/Marlin/files/2902222/pins_BIQU_SKR_V1.1.h.zip)
Also, what is the purpose of these 2 files: `HAL_LCD_I2C_routines.c` and `u8g_com_HAL_LPC1768_ssd_hw_i2c.cpp` they seem to address the same device, SSD1306.

**Comment by obertr0n** [comment]
I had some time today to investigate more this problem.
What I have noticed is that the initialization sequence of the OLED is interrupted by ~40ms.
I couldn't figure out what exactly was causing this.
I also experienced something strange: when using USB power the logic analyzer shows the expected address 0x3C, but when using the power connector, the I2C address is 0x7F.
+ When powered by USB:
Delay between I2C init sequences:
![image](https://user-images.githubusercontent.com/10163987/53439134-0d602700-3a0a-11e9-9fd8-204af6bd0981.png)
First part:
![image](https://user-images.githubusercontent.com/10163987/53439211-400a1f80-3a0a-11e9-81bf-4237a9adb627.png)
Second Part:
![image](https://user-images.githubusercontent.com/10163987/53439283-6203a200-3a0a-11e9-851e-2838ac3485ea.png)

+ When powered by external power supply:
![image](https://user-images.githubusercontent.com/10163987/53439587-038af380-3a0b-11e9-8119-76cdfec3c2d2.png)

Another strange behavior is that the board disconnects from PC and "freezes" after ~2-5mins.

**Comment by obertr0n** [comment]
I have managed to get the display working, a standalone display + an encoder.
Here is the commit that is working with my setup:
https://github.com/obertr0n/Marlin/commit/b53a5bfd694c8bb8569efbb6b88cda306496938e

From what I could tell it works ok, to a point:
![image](https://user-images.githubusercontent.com/10163987/53564248-0b5bac80-3b5f-11e9-8432-00989dad7b86.png)
Any idea what might be causing the bottom line to display like that? For sure more testing has to be done.

**Comment by kAdonis** [comment]
Great you got it working!
The bottom line seems to be the first line from "3D Printer Ready" which should be at the bottom not at the top
Your display is shifted

**Comment by obertr0n** [comment]
I noticed that, what is strange is that it displays correctly for 1-2 mins and then that glitch is happening.
Really strange..

**Comment by dw-0** [comment]
@obertr0n are you using 5V or 3.3V as input voltage for the OLED?
I experienced kind of a similar strange behaviour with using 5V.
Using 3.3V instead works flawless.

**Comment by obertr0n** [comment]
only power it, or also level shift sda/scl?

**Comment by AnHardt** [comment]
Does the display return to normal when you switch to the menus and back, what should reinit the display?

**Comment by obertr0n** [comment]
@th33xitus  I tried powering the display from 3.3V. Unfortunately no change.

@AnHardt No..it displays every menu with that offset.

**Comment by thinkyhead** [comment]
Getting closer…. I would suggest scrutinizing the LCD init sequence. Maybe there's something different about the command-set for this display…?

**Comment by AnHardt** [comment]
The interesting part of the story is
> displays correctly for 1-2 mins and then that glitch is happening.

but reinitialising does not help. (Or don't we reinicialising any more?)

That makes a software problem unlikely.
Maybe interupted data transfer?

What are you doing in this 1-2 minutes?
Try to do nothing. No fan, no stepper, no heater activity - to minimize electrical noise and jitter in I2C timing.

Or can it be a heat problem? Also unlikely when powered and level-shifted to 3.3V. 
Can you feel a hot spot on the display/board?

What remains? Display-hardware fault?

**Comment by obertr0n** [comment]
@AnHardt My setup is just the SKR board, the standalone OLED + encoder on a breadboard + a stepper driver and a stepper motor.
This happens every time, regardless of doing something on the board or not. 

If it was an interruption in the data transfer, shouldn't  it restore to normal, even for a small period when a new refresh is done?

I just tested without doing anything, without the stepper driver and motor. Just the display and the encoder, powered from external adapter (12V) after ~3:30 the glitch appeared.
No signs of heat or anything like that.

**Comment by AnHardt** [comment]
Try some of the u8g-lib examples on the same hardware to find out if it's a Marlin problem or not.

**Comment by obertr0n** [comment]
Just checked with a 128x32 display, no change in code and after some time the same happened.
I will still poke around to see if I can find something.

**Comment by ShohninDmitriy** [comment]
It seems the problem is in the chip and the poor implementation of the I2C Protocol as even in the Klipper the same problem with hanging. And Smoothieware doesn't even support I2C in any way.

**Comment by obertr0n** [comment]
@ShohninDmitriy If this would be the case I would've expected to have it as a known bug. Or maybe there are not that many users of this small OLED displays.

**Comment by obertr0n** [comment]
Hi, it appears that I solved the issue, I don't really know if this is applicable for everyone, so I will leave my fork here for reference: https://github.com/obertr0n/Marlin/tree/marlin_2.0.x_ssd1306/Marlin
Affected files: 
 **HAL_LCD_I2C_routines.c**
**u8g_com_HAL_LPC1768_ssd_hw_i2c.cpp**

**Comment by psavva** [comment]
@thinkyhead ,. Is it worth that you review the changes as per the last comment and see if this is a bug in Marlin?

**Comment by istyszy** [comment]
![65176770_2384417738302062_7773814690349580288_n](https://user-images.githubusercontent.com/39673354/60039104-9ccacd80-96be-11e9-8df6-46cd2c73edd5.jpg)

Hello, i have an i2c OLED display, with marlin 2.0 (2019-06-24) + SKR V1.3, i use hardware i2c from E1. When the board starts everything is OK, display works as it should, but after 40 sec or so, the display crashes.
Did someone had this problem? I used the display with ramps+mega and never had any issues? I use u8glib_SH1160. (also tried U8GLIB_SSD1306 same result)

**Comment by istyszy** [comment]
@thinkyhead So, status update:
If i use the the source from: https://github.com/obertr0n/Marlin/tree/marlin_2.0.x_ssd1306/Marlin , the Oled display works perfectly, so i made the changes

Affected files:
**HAL_LCD_I2C_routines.c
u8g_com_HAL_LPC1768_ssd_hw_i2c.cpp**

to a new version of of marlin... the problem appars 
so i guess the problem is from somewhere else?

**Comment by Johetan** [comment]
@obertr0n 
I tried it also on an mks sgenl. Same result. Also level shifted, 3.3v, do you already a have a solution for platform.io compile?

**Comment by thinkyhead** [comment]
> see if this is a bug in Marlin?

I'm relying on the experts. I just clean up the place.

**Comment by parsa-0x1** [comment]
Hello everybody.
i am not clever as much as you. i need a simple example to learn ssd1306 with Lpc1768 keil compiler. who can help?
i really need it. Ive been searched everywhere. and i am not so talented to change other micro controller code. please help me. thank you so much.

**Comment by parsa-0x1** [comment]
can you send me a simple code about lpc1768 for ssd1306  with keil compiler??
