### ISSUE TITLE
[QUESTION] Min speed with junction deviation

### ISSUE THREAD

**Issue by ArtemKuchin** [MarlinFirmware/Marlin#13256]
A simple question that is not covered in places i looked.
(JD - junction deviation)

I want to clarify how movement start from stop position.
With JERK (without JD) marlin just start with speed of JERK and then continues accelerating to set speed (assuming final speed is more than JERK)

How does it work with JD enabled? Does it start from zero and uses acceleration or does start with  MINIMUM_PLANNER_SPEED  and then uses acceleration?

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report.](https://github.com/MarlinFirmware/Marlin/issues/new/choose)

**Comment by ArtemKuchin** [comment]
I have asked this question on reprap forum and in the facebook group and nobody could clarify the issue. Some more people aslo were interested in knowing this, but apparently only the developers can really answer it.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by thinkyhead** [comment]
I would have to study the code to be able to provide an answer.

**Comment by ArtemKuchin** [comment]
I would greatly appreciate it.

**Comment by AnHardt** [comment]
Should start with MINIMUM_PLANNER_SPEED, not with 0. But by default that's very low.

#define MINIMUM_PLANNER_SPEED 0.05 // (mm/sec)

It exists only to avoid timer overruns. If the speed would be zero it would need infinit timerticks to the next step.
