### ISSUE TITLE
Not compiling on MKS SGen 1.3

### ISSUE THREAD

**Issue by FelixHauser** [MarlinFirmware/Marlin#13254]
### Description

The Firmware does not compile for the MKS SGen v1.4

macOS
Platformio

### Steps to Reproduce

1. Copy/Replace the suggested Configuration.h and Configuration_adv.h (Anycubic Kossel)
2. Select correct board on configuration.h
3. Set LPC1768 as environment
4. Build for the LPC1768 as environment

**Expected behavior:** 

I expected to build a .bin file for me to upload

**Actual behavior:** 

Fails the build

#### Additional Information

I followed the instructions on the marlinfw.org site step by step, that´s why I am assuming this is an bug.

**Reported Errors**

These are the lines in red shown in the console after the failed build:
```
/Users/felix/.platformio/packages/framework-arduino-lpc176x/cores/arduino/HardwareSerial.h:161:8: error: expected '(' before 'co
nstexpr'

/Users/felix/.platformio/packages/framework-arduino-lpc176x/cores/arduino/HardwareSerial.h:204:8: error: expected '(' before 'co
nstexpr'

/Users/felix/.platformio/packages/framework-arduino-lpc176x/cores/arduino/HardwareSerial.h:238:3: error: expected '}' at end of 
input

/Users/felix/.platformio/packages/framework-arduino-lpc176x/cores/arduino/HardwareSerial.h:241:8: error: expected '(' before 'co
nstexpr'

/Users/felix/.platformio/packages/framework-arduino-lpc176x/cores/arduino/HardwareSerial.h:310:8: error: expected '(' before 'co
nstexpr'

*** [output/LPC1768/src/src/HAL/HAL_LPC1768/HAL.cpp.o] Error 1

/Users/felix/.platformio/packages/framework-arduino-lpc176x/cores/arduino/HardwareSerial.h:161:8: error: expected '(' before 'co
nstexpr'

/Users/felix/.platformio/packages/framework-arduino-lpc176x/cores/arduino/HardwareSerial.h:238:3: error: expected '}' at end of 
input

/Users/felix/.platformio/packages/framework-arduino-lpc176x/cores/arduino/HardwareSerial.h:241:8: error: expected '(' before 'co
nstexpr'

/Users/felix/.platformio/packages/framework-arduino-lpc176x/cores/arduino/HardwareSerial.h:310:8: error: expected '(' before 'co
nstexpr'

*** [output/LPC1768/src/src/HAL/HAL_LPC1768/HAL_spi.cpp.o] Error 1
```

**Comment by boelle** [comment]
remember to attach 2 config files as zip file, maybe also include your platformio.ini in the zip file

**Comment by FelixHauser** [comment]
As I mention, these are the two found on the examples folder

**Comment by boelle** [comment]
doooh, laughs on me :-D

**Comment by FelixHauser** [comment]
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/2898231/Archive.zip)
just in case...

**Comment by p3p** [comment]
@thinkyhead merged an api change for Serial ports, can you use the previous commit while this is being looked into.

https://github.com/MarlinFirmware/Marlin/archive/88cc1d1a31f7fe21f8a3796878d2ab22e2e66603.zip

**Comment by FelixHauser** [comment]
thanks @p3p I'll look into it right away

**Comment by p3p** [comment]
May have jumped to conclusions, I can't reproduce this issue using the configs supplied, make sure the platformio framework and libraries are all up to date.

I'm a bit confused with which examples you said you used as the MKS SGen does not have any (or a pins file), and the Anycubic Kossel runs an 8bit AVR.

**Comment by boelle** [comment]
if there is no pins file for the board it would also not have a board name to put in the the config files

make me wonder where the example or suggested config files mentioned in the first post comes from

**Comment by boelle** [comment]
just gave it a quick look, marlin does not have any example configs for the anycubic kossel

only 2.0 have example configs for anycubic i3 mega, and that was me submitting those after i helped a user to get his printer going (done over 1000 comments on an issue)

**Comment by p3p** [comment]
Anycubic Kossel is a delta so it's hidden in the delta sub folder.

**Comment by boelle** [comment]
ahh, but yes BOARD_TRIGORILLA_14

same as the i3 mega, but given that there is no pins file for the MKS SGen it might be the reason why it does not compile

**Comment by boelle** [comment]
hmmm

in the config its set to BOARD_MKS_SBASE, now i'm confused

**Comment by p3p** [comment]
Indeed the config supplied compiled fine as it uses the MKS SBase which is why I mentioned making sure that platformio framework and libs were upto date.  The confusion was with everything else not existing including the SGen 1.3.

**Comment by boelle** [comment]
i even google for SGen 1.3, no such board to be found anywhere

but there was an SBase 1.3 and Gen 1.3 but not SGen

vscode and platform io is my prefered choice over Arduino IDE as it updates libs etc automatic

only thing is to edit platformio.ini to correct build env

**Comment by p3p** [comment]
But there is an MKS SGen 1.0 that would build with the LPC176x platform (if supported, the SBase pins file may work somewhat) so I couldn't decide which part of the description was wrong, 

Even vscode needs told to update platformio, at least for me it does.

**Comment by boelle** [comment]
i dont see it

![image](https://user-images.githubusercontent.com/3832239/53304664-3486ef00-3878-11e9-8b7f-55394132386d.png)

**Comment by FelixHauser** [comment]
I meant SBase, I just made a typo...
I will try to build in my other computer, in which I will have to install everything from scratch

**Comment by boelle** [comment]
platformio.ini line 26

env_default = LPC1768

hmm.... just strange as it should actually build without errors

**Comment by thinkyhead** [comment]
Hi! It looks like your issue is with your build environment. Please close this issue if switching computers solves the problem for you.

**Comment by FelixHauser** [comment]
It's solved the problem. Sorry for the inconvenience. I hope at least it helps future issues.

**Comment by boelle** [comment]
no problemo... we have all been there before :-D
