### ISSUE TITLE
Marlin 2.0 AD595 Arduino Due

### ISSUE THREAD

**Issue by svs072477** [MarlinFirmware/Marlin#13268]
Marlin 2.0 Thermocouple k-type with AD595 RURAMPS + Arduino Due

When the temperature increases, the readings issued by the firmware, on the contrary, decrease. On Repetier Firmware works correctly

**Comment by boelle** [comment]
where are your 2 config files attached as zip?

**Comment by svs072477** [comment]
OK, I will add configs in the evening

**Comment by AnHardt** [comment]
Thermocouples are polar. Swap the connectors.

**Comment by svs072477** [comment]
Yes, indeed. Just when was the Repetier to the polarity readings are not dependent, or I was always hooked up correctly :)

**Comment by boelle** [comment]
so this is still an issue? just strange

**Comment by svs072477** [comment]
No, I Swap the connectors, and issue solved

**Comment by boelle** [comment]
@svs072477 then give the close button below a friendly thought :-D

**Comment by svs072477** [comment]
Oh, sorry
