### ISSUE TITLE
multiple filament runout sensors

### ISSUE THREAD

**Issue by mitchcecg** [MarlinFirmware/Marlin#13273]
I hope this is the correct place for this question if not please direct me to the correct place.

I have 3 extruders and I have 3 filament runout sensors that I can connect to pins on my rumba board. the question is does Marlin handle this and how to configure Marlin for this. I only see a way to have one filament runout sensor 

Thanx in advance for the help

**Comment by mitchcecg** [comment]
I hope this is the correct place for this question if not please direct me to the correct place.

I have 3 extruders and I have 3 filament runout sensors that I can connect to pins on my rumba board. the question is does Marlin handle this and how to configure Marlin for this. I only see a way to have one filament runout sensor 

Thanx in advance for the help

**Comment by ghost** [comment]
If they are three switches of the NC (normally closed type), you could wire them in series and consider them to be "one" switch. This was my situation.

If they are NO (normally open) you could wire them in parallel and consider them to be a single switch.

Sensors of the electronic type are typically open drain/open collector pulling to ground when triggered, these are like NO switches and can be wired in parallel (that's a wired-OR).

With both methods, of course you have no way to determine WHICH filament has run out - you need to determine that manually in such a case.

I would like to add:

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

Before posting a bug report please test with `bugfix-2.0.x` to check if problem is gone.

**Comment by boelle** [comment]
>  for this question 
> 
the correct place for questions are discord and facebook

**Comment by InsanityAutomation** [comment]
Also, for reference in Marlin 2.0 `Configuration.h` … `#define NUM_RUNOUT_SENSORS   3`

And 
```cpp
#define FIL_RUNOUT_PIN     xx
#define FIL_RUNOUT2_PIN    xx
#define FIL_RUNOUT3_PIN     xx
```
