### ISSUE TITLE
M190 broken?

### ISSUE THREAD

**Issue by RudyBenner** [MarlinFirmware/Marlin#13291]
Can someone check to confirm that M190 is broken. It does not wait.
I have tried previous backup config files, so I do not believe I broke it.
Bugfix2.0.x Gen_L

[Feb 27.zip](https://github.com/MarlinFirmware/Marlin/files/2922645/Feb.27.zip)

**Comment by kAdonis** [comment]
It was broken, but fixed now
Just download current version

**Comment by RudyBenner** [comment]
Will do, I thought I was losing my mind.
