### ISSUE TITLE
Logo for Marlin firmware

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1329]
It was mentioned on IRC chat the other day, so i thought of marlin the fish and started to look arround

http://imgur.com/gqhNTDS

its just starters.... 

thoughts?

**Comment by scotty1024** [comment]
Usage rights eg is the image open sourced at the same license level as Marlin source code? The whole Firefox vs Ice Weasel fork was over that frickin' Firefox logo image open source license.

**Comment by boelle** [comment]
it's based on an free drawing i found via google....

but BASED on... i have redrawn parts of it as i was not happy with the org.

**Comment by ErikZalm** [comment]
There already is a logo for Marlin.
I will add it soon.

**Comment by boelle** [comment]
ok :-D

**Comment by boelle** [comment]
can it be found on internet? if so i could add it?

**Comment by boelle** [comment]
anyways will close this one as the logo is allready there

**Comment by boelle** [comment]
@ErikZalm maybe drop the logo in the repro so we can have it shown on LCD displays also instead of the reprap thing

**Comment by scotty1024** [comment]
Not to beat the horse but repos like Marlin are based around the original authors of the contribution directly checking it into the repo. Or someone checking in something created by someone else that has an attached compatible license. Images are problematic to check in from a third party as they generally don't have attached licenses. 

I highly recommend a LogoLicense.txt file be checked in spelling out the license of the logo if it isn't 100% created by the person that checks it in.
