### ISSUE TITLE
Steppers doesnt work while printing

### ISSUE THREAD

**Issue by Duz1Adam** [MarlinFirmware/Marlin#13315]
Hello. First of all sorry my bad english. But i have a problem with my steppers.
I'm making a rep-rap 3D printer. I assembled the machine and performed the endswitch calibrations. when the machine is not printing, the steppers are moving its ok. But when I start printing, only the z-axis moves. it is also moving very fast. x and y axis doesnt move. I'm using ramps1.4 nema17 and a4988 engine driver. add my configuration file in the appendix. can those who know or help those who have this problem?

My Conf. File is;
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2932615/Configuration.txt)

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
