### ISSUE TITLE
safe homing and bed levelling issue

### ISSUE THREAD

**Issue by marquismatt** [MarlinFirmware/Marlin#13324]
Hi Guys 

I'm stuck on two things, I've set up ABL in config.h etc in 1.1.9
the first issue is that it wont compensate for the bed unevenness (levelled bed manually beforehand)
and now it wont safe home properly with G28 it will home the X and Y but when it goes to home the Z it hits the right hand side instead of stopping at the centre of the bed. any ideas on what I have missed or have done wrong would be greatly appreciated : ) 

hope it makes sense   

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2940886/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/2940887/Configuration_adv.zip)

**Comment by boelle** [comment]
have you tried on bugfix 2.0 also? its both 8 bit and 32 bit

**Comment by marquismatt** [comment]
I’ll have to have a look at 2.0
over the weekend 

Cheers for the reply

**Comment by boelle** [comment]
what result did you get in weekend testing 2.0?

**Comment by shitcreek** [comment]
@marquismatt  - any update?

**Comment by marquismatt** [comment]
Sorry guys for taking so long to reply. I ended up using 1.1.9 again after double checking everything it worked. I couldn’t find what I missed tho. Thanks for checking up

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by marquismatt** [comment]
Oops sorry
