### ISSUE TITLE
can not compile marlin 2.0 with mks sbase fails neopixel without even having neopixel uncommitted

### ISSUE THREAD

**Issue by rathorp80** [MarlinFirmware/Marlin#13329]
can not compile marlin 2.0 with mks sbase fails neopixel without even having neopixel uncommitted

[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/2944102/Configuration.txt)
[failed compile.txt](https://github.com/MarlinFirmware/Marlin/files/2944109/failed.compile.txt)

**Comment by p3p** [comment]
Update PlatformIO frameworks and libraries

**Comment by J-charles-C** [comment]
I,

P3P's answer yesterday when I asked the same question:

> Depends how you use PlatformIO to build Marlin.
> 
> Terminal:
> platformio update or pio update
> 
> Atom:
> Click the PlatformIO menu then select Update platforms, packages and libraries
> 
> Visual Studio Code:
> Click the Platform IO symbol (Alien head) on the left menu bar, in Quick access Menu click on Updates -> Update All
> 

best

**Comment by boelle** [comment]
@rathorp80 did updating PlatformIO frameworks and libraries solve the issue?
