### ISSUE TITLE
[HELP] E0 Auto Fan doesnt turn off after finished print

### ISSUE THREAD

**Issue by Fabialbo** [MarlinFirmware/Marlin#13323]
### Description

Auto Hotend fan wont turn of after finished print.
Strangly everything works fine (start & stop of fan) if I set temperures manually over the printer interface. 

### Steps to Reproduce

1. restart printer
2. Print normally
3. wait until finished

**Expected behavior:** Printer turns on/off autofan if hotendtemp is over/under set threshold

**Actual behavior:** Turns on perfectly at set temp but contiunes to run after print finished.

#### Additional Information

Firmware: 1.1.9

Printer: Ender 3 with orginal Board with BL-Touch

Ending G-Code:
  G4 ; Wait
  M220 S100 ; Reset Speed factor override percentage to default (100%)
  M221 S100 ; Reset Extrude factor override percentage to default (100%)
  G91 ; Set coordinates to relative
  G1 F1800 E-3 ; Retract filament 3 mm to prevent oozing
  G1 F3000 Z20 ; Move Z Axis up 20 mm to allow filament ooze freely
  G90 ; Set coordinates to absolute
  G1 X0 Y{machine_depth} F1000 ; Move Heat Bed to the front for easy print removal
  M84 ; Disable stepper motors

[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/2940770/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2940771/Configuration.txt)

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report.](https://github.com/MarlinFirmware/Marlin/issues/new/choose)
