### ISSUE TITLE
Marlin 2.0 Wont compile with MKS SBase

### ISSUE THREAD

**Issue by cinealfa** [MarlinFirmware/Marlin#13332]
### Description

Latest Bug 2.o Branch has error in compiling. maybe related to #13329 I am checking now. Updated platformio This did NOT resolve the error.

### Steps to Reproduce

1. Fresh install of Marlin source
2. Using archive of known good config files dated 1/31/19
3. initiate compile

**Expected behavior:** Program compiles
**Actual behavior:** Passes sanity check then throws the following error:
```
In file included from Marlin/src/lcd/dogm/status_screen_DOGM.cpp:32:0:
Marlin/src/lcd/dogm/dogm_Statusscreen.h:46:12: fatal error: ../../../_Statusscreen.h: No such file or directory
#include "../../../_Statusscreen.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/LPC1768/src/src/lcd/dogm/status_screen_DOGM.cpp.o] Error 1
```
Did a fresh reinstall of the src to see if that would change anything it is acting like maybe a file listing is mistyped.  
#### Additional Information
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/2945921/Archive.zip)

**Comment by kAdonis** [comment]
You have custom Bootscreen and Statusscreen enabled, you have to copy these files to your new marlin sources
```
// Enable to show the bitmap in Marlin/_Bootscreen.h on startup.
#define SHOW_CUSTOM_BOOTSCREEN

// Enable to show the bitmap in Marlin/_Statusscreen.h on the status screen.
#define CUSTOM_STATUS_SCREEN_IMAGE
```
You cannot expect marlin to compile with copied config files. You need to edit the corresponding configs every time you download marlin. I am using Notepad++ with the compare plugin for this

**Comment by reloxx13** [comment]
or use sourcetree to "merge" from git.

sourcetree is freeware gui git client.

**Comment by cinealfa** [comment]
ay caramba! How stupid of me
