### ISSUE TITLE
[BUG] mb ! +3(

### ISSUE THREAD

**Issue by guestisp** [MarlinFirmware/Marlin#13338]
marlin 1.1.8
I know it's an outdated version, but for no apparent reason, a 2:45 hours print was interrupted with the string `mb ! +3(` on the last line (Geeetech A20M)

As you can see from the attached photo, hotend and hotbed temperatures where still on.

Any idea ?

**Comment by guestisp** [comment]
![IMG_20190308_211352](https://user-images.githubusercontent.com/3944655/54055434-5e7fd000-41ed-11e9-839d-cecfb0c1b5eb.jpg)

**Comment by ManuelMcLure** [comment]
Printing from SD or through USB? Have you looked in the gcode file for that string, or even that the gcode file is complete?

**Comment by thinkyhead** [comment]
Please test the `bugfix-1.1.x` and/or `bugfix-2.0.x` branches to see whether it helps. If the problem has been resolved then we can close this issue. If the issue isn't resolved in either of those branches yet, then we should investigate further.

**Comment by guestisp** [comment]
Im unable to replicate and i don't know the source of this error (It this an error or just carbage shown on screen?)

**Comment by guestisp** [comment]
Printing from SD, gcode is complete and that string isn't in the gcode file.
When it happened, printer was frozen (no movements) but hotend and hotbed still turned on

**Comment by boelle** [comment]
@guestisp so this error only came up once?

maybe it was bad gcode and not a fault with marlin

**Comment by guestisp** [comment]
I think it was a defective SD card.
