### ISSUE TITLE
Conflicting declaration 'volatile bool wait_for_user' (bugfix-2.0.x)

### ISSUE THREAD

**Issue by rschaeuble** [MarlinFirmware/Marlin#13346]
### Description

Commit 60e82e3929bfd402384e7dea9d737796c96fa07f introduces a compile error:

```
In file included from ...\sketch\src\HAL\HAL_AVR\MarlinSerial.cpp:58:0:

...\sketch\src\feature\emergency_parser.h:35:22: error: conflicting declaration 'volatile bool wait_for_user'

 extern volatile bool wait_for_user, wait_for_heatup;

                      ^

In file included from ...\sketch\src\HAL\HAL_AVR\MarlinSerial.cpp:44:0:

...\sketch\src\marlin.h:336:15: note: previous declaration as 'bool wait_for_user'

   extern bool wait_for_user;
```

In `emergency_parser.h`,  `wait_for_user` is declared as volatile. Since the latest commit, `Marlin.h` now declares the same variable as non-volatile. This results in a conflicting duplicate definition, which the compiler rejects.

I have tried both Arduino IDE 1.8.8 and 1.9-beta, with identical results.

**Comment by noderat** [comment]
Confirm, I am also getting this duplicate definition error.

**Comment by AbuMaia** [comment]
Another confirmation.

**Comment by Vertabreak** [comment]
confirmed.

**Comment by ghost** [comment]
fixed here : https://github.com/MarlinFirmware/Marlin/pull/13349
