### ISSUE TITLE
[BUG] Filament Change with Mixing Extruder

### ISSUE THREAD

**Issue by brandstaetter** [MarlinFirmware/Marlin#13351]
### Description

When mixing extruder and filament change features are enabled, the filament change menu shows entries for E1 and E2, but klicking on E2 does nothing. E1 moves the extruders according to the defined mix

### Steps to Reproduce

1. enable ADVANCED_PAUSE_FEATURE
2. enable MIXING_EXTRUDER with MIXING_STEPPERS 2
3. navigate to the menu Filament change

**Expected behavior:** Entries for E1 and E2 really work on the specified steppers and ignore any mixture settings

**Actual behavior:** E2 does not work, E1 moves the steppers according to the configured mix settings

(Ping me if I need to attach my configs, don't think it's necessary here)

**Comment by Vertabreak** [comment]
Confirmed 
I would add if you set mix 100% to E1 or E0 and use E1 filament change the one set 100% is used. E2 should be the 3rd extruder that isn't hooked up.

**Comment by tcm0116** [comment]
I've noticed this same thing. It's been on my to-do list to look into it some more. I think the main thing to consider is that the filaments need to be changed one at a time as pushing too much filament into a mixing extruder when one of the other inputs is empty will create a huge mess!

**Comment by tcm0116** [comment]
@brandstaetter - I was working on fixing this when the control board in my machine blew up :-(

I have pushed the changes to the branch linked below, if you want to give them a try. `M600`, `M701`, and `M702` should work as expected. `M702` also supports `FILAMENT_UNLOAD_ALL_EXTRUDERS` when no `T` parameter is provided, and should unload all of the filaments simultaneously. The LCD code was already trying to erroneously send T parameters to the filament change commands, so it should work from the LCD and via the manual G-Codes.

https://github.com/tcm0116/Marlin/tree/2.0.x-mixing_filament_change

**Comment by boelle** [comment]
missing label

**Comment by thinkyhead** [comment]
Attempts have been made to fix up this combination, but mixing is still a bit of a hack, so some work may still be needed. Please test the latest 2.0.x code to see where it stands.

**Comment by boelle** [comment]
@brandstaetter have you tested with latest 2.0.x ?

**Comment by boelle** [comment]
@brandstaetter have you tested with latest 2.0.x ?

**Comment by brandstaetter** [comment]
Printer is still non-functional, no time to fix it unfortunately. Is there noone else who could test it?

**Comment by boelle** [comment]
i personal have problems with just the filament change (M600) option on a normal extruder

it skips the unload option, and i have posted on discord about it but so far no luck

my configs are also posted on discord in the  #marlin-v2 channel

**Comment by boelle** [comment]
@shitcreek @thinkyhead could it be that PR #13803 broke this?

**Comment by boelle** [comment]
@brandstaetter since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by Vertabreak** [comment]
i would note that it does function its just weird and labeled funny.

**Comment by boelle** [comment]
yep, my org problem is also gone, it works as its programmed

**Comment by boelle** [comment]
will close as i tested it and works
