### ISSUE TITLE
Problem With Simplify3d

### ISSUE THREAD

**Issue by kaijrock23** [MarlinFirmware/Marlin#13354]
Hi, I have a little problem and I feel sorry to bother you but I really don't know how to solve, I own an ender 3 pro, I printed different things with both cura and simplify3d using the exact same settings profile and all printed perfectly so far.
I upgraded from stock Marlin to Marlin 1.1.9, and now I have issues with my prints quality, solved with cura with "control jerk" turned off, but I have still problems with simplify3d.
I don't know how to call it, raw surface or a bit of layer shifting.
Here is a photo of the issues that I encounter with simplify3d is the unfinished model I did just to show the raw surface/layer shifting.
The second photo is the same model with the same settings printed in cura.
I tried using default creality's jerk value and the ones that came with the Marlin 1.1.9 no success, simplify3d just have that behavior, ringing/layer shifting/raw surface I don't even know how to classify this issue.
![53781112_2421688144716839_3876520855827644416_n](https://user-images.githubusercontent.com/48413818/54088207-d66c0880-435b-11e9-90a0-9c117b955e0a.jpg)
![53410183_2421688168050170_5903365727250808832_n](https://user-images.githubusercontent.com/48413818/54088206-d409ae80-435b-11e9-9611-57bba3ff557f.jpg)
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2949720/Marlin.zip)

**Comment by boelle** [comment]
try bugfix 2.0 also, 1.1.9 is old and not updated as much

2.0 is both 8 bit and 32 bit

**Comment by kaijrock23** [comment]
I have bed levelling and other small things added, since the bugfix 2.0.0 contains less files, it's safe to add just what I need and then flash over the 1.9.0 bugfix that I have already installed?

**Comment by kaijrock23** [comment]
Arduino:1.8.8 (Windows Store 1.8.19.0) (Windows 10), Scheda:"Sanguino, ATmega1284 or ATmega1284P (16 MHz)"

sketch\src\lcd\menu\menu.h: In function 'load':

sketch\src\lcd\menu\menu.h:165:18: internal compiler error: Segmentation fault

     static void  load(void *ptr, const int32_t value) { *((type_t*)ptr) = unscale(value);     }

                  ^

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.19.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/program files/windowsapps/arduinollc.arduinoide_1.8.19.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1

If I verify the marlin 2.0bugfix it gives me this issue.


> try bugfix 2.0 also, 1.1.9 is old and not updated as much
> 
> 2.0 is both 8 bit and 32 bit

**Comment by boelle** [comment]
bugfix 2.0.0 contains same amount of files, they are just split up differently

also upgrade to arduino ide 1.9 or vscode+platformio

**Comment by InsanityAutomation** [comment]
Arduino IDE 1.8.8 is fine, just get rid of the windows store version. It is known to be buggy and crash compilation very often. Please download it directly from the Arduino website.

Edit : Here is a branch setup for the creality machines already. Using a tested configuation may help determine the root of any issue. You will need to set machine options in the top of Configuration.h, but nothing outside the top few lines there will need to be touched.

https://github.com/InsanityAutomation/Marlin/tree/Creality_2.0_Devel

**Comment by kaijrock23** [comment]
I upgraded to Marlin 2.0, same exact issue with simplify3d, with cura still all ok.

**Comment by kaijrock23** [comment]
I always used the tested setup file in the default configuration files.

**Comment by kaijrock23** [comment]
Does simplify3d use jerk and acceleration from the printer or from it's own settings?

**Comment by robbycandra** [comment]
Actually you can compare the gcode file produced by cura vs simplify3d and see the differences between them.

**Comment by kaijrock23** [comment]
How?

**Comment by guestisp** [comment]
I think I have the same here.
Upgraded from 1.1.8 to 2.0.x and now surfaces are rough and "shifted". Slic3r exibit this issue, Simplify3D (with the Benchy) much, much less (but not perfect), Cura a little bit cleaner than Slic3r, but worse than S3D.

![IMG_20190330_185438 jpg 62ef91cf921e112946b8c4fdcaa773ac](https://user-images.githubusercontent.com/3944655/55656297-b7478600-57f6-11e9-9c4f-2c4a42d9a186.jpg)

**Comment by kaijrock23** [comment]
With cura I solved turning jerk control and acceleration off

**Comment by guestisp** [comment]
So you rely on firmware accelerations. which settings do you have ?

**Comment by kaijrock23** [comment]
![marlin](https://user-images.githubusercontent.com/48413818/55671342-7b143400-588f-11e9-9e8b-d77ac52fc3a3.PNG)

**Comment by kaijrock23** [comment]
I use the 1.1.6 ones they are from creality.

**Comment by guestisp** [comment]
I don't think it's the slicer acceleration control to add these artefacts. My slicer use the same acceleration and jerk values as per firmware, so leaving them disabled won't change anything

I've started to get these trouble when using Marlin 2. I'll try to revert to Marlin 1.1.8 and see

**Comment by kaijrock23** [comment]
Guestisp ti posso chiedere una cosa? Ma in simplify hai tipo negli script un gcode con scritto REPLACE M204 S ecc?

**Comment by guestisp** [comment]
No, perché?

**Comment by kaijrock23** [comment]
Perché sto continuando a fare prove, con cura ho risolto del tutto, disattivando jerk e acceleration lasciando il tutto nelle mani di Marlin, in simplify in starting gcode ho messo tutti i parametri presenti in Marlin, e sembra aver risolto il problema, in post processing avevo pure un gcode m204 S con valori alti e in più S non si usa più. Per questo chiedevo, visto che nessuno ci ha saputo aiutare ho continuato a cercare una soluzione concreta al problema.

**Comment by guestisp** [comment]
Ma hai anche te quelle bande orizzontali usando Slic3r ? Considera che Slic3r di default fa override dei settaggi del Marlin, quindi nelle impostazioni della stampante, su Slic3r, devi impostare gli stessi valori che hai in marlin.

**Comment by kaijrock23** [comment]
Non uso slic3r, quindi non saprei, dimmi i settaggi che usi magari c'è qualcosa di troppo alto.

**Comment by guestisp** [comment]
500 di accelerazione, junction deviation 0.02

**Comment by kaijrock23** [comment]
Hai provato usando il jerk invece di junction? X e y 10, E 0.3 e Z5?

**Comment by guestisp** [comment]
Si, non cambia nulla.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
