### ISSUE TITLE
[BUG] Level corners mode stays active after display timeout

### ISSUE THREAD

**Issue by Santobert** [MarlinFirmware/Marlin#13358]
### Description
The level corners mode stays active after timeout has reset the display and the info display is shown. After pressing the button again, the printer goes to the next corner and shows a weird mixture of the level corners menu and the main menu:
![IMG_20190310_210552](https://user-images.githubusercontent.com/15657682/54090838-b434b380-4378-11e9-9027-2d8db9eb90ef.jpg)

### Steps to Reproduce
1. Select level corners
2. Go through the process until the printer reached the first corner
3. Wait there until the timeout resets the display and the info display is shown
4. Hit the button

**Expected behavior:** When hitting the button from the info display the main menu should be shown

**Actual behavior:** The printer travels to the next corner and a weird display is shown

#### Additional Information

**Comment by shitcreek** [comment]
Could you select 'back'? What version of Marlin are you using?

**Comment by Santobert** [comment]
Yes, I can select 'back' and it works as expected. It leads back into the 'level bed' menu.
I am using the latest marlin 2.0 bugfix version.

**Comment by boelle** [comment]
maybe attach your 2 config files as a zip file?

**Comment by Santobert** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2982763/Marlin.zip)

**Comment by boelle** [comment]
missing label

**Comment by InsanityAutomation** [comment]
This has been fixed, so this one can be closed.
