### ISSUE TITLE
[BUG?] G29 P1 and failing probe

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#13360]
Executing G29 P1 (after G29 P0) if for some reason probe will fail, Marlin still retries forever to probe the same point. Is it the expected behaviour?

**Comment by InsanityAutomation** [comment]
UBL? I know a max number of tries was looked at once a while ago. I dont know what ever happened with that. Bilinear has G29_RETRY_AND_RECOVER however this doesnt work for UBL. Perhaps the best course is to complete the implementation?

**Comment by GMagician** [comment]
I'm almost sure it's UBL but I can't check until weekend

**Comment by GMagician** [comment]
@InsanityAutomation  I have `#define AUTO_BED_LEVELING_UBL`
