### ISSUE TITLE
EXAMPLE CONFİGURATİON FOR DELTA TYPE 3D PRİNTER

### ISSUE THREAD

**Issue by ebubekirn** [MarlinFirmware/Marlin#13374]
which one should i choose example configuration for marlin firmware. I have delta type 3d printer. But there are 7 different type for delta. There are : Anycubic, FLSUN, generic, Hatchbox_Alpha, kossel_mini, kossel_pro, kossel_xl.
My printer's height is 1 meter. Can you help me for this problem??

**Comment by reloxx13** [comment]
u dont need to use the example config.
take one which is almost like urs or use the generic one and adjust the config for ur printer.
tempsensor, steppers, board, endstops, size, etc.

read the configuration.h and configuration_adv.h, everything is described quite good in it.

boards:
http://marlinfw.org/docs/hardware/boards.html#board-list

could be outdated at some points if u use 2.0.x : 
http://marlinfw.org/docs/configuration/configuration.html#configuration.h

**Comment by ebubekirn** [comment]
thank you bro

**Comment by reloxx13** [comment]
pls close this if u r done, since u opened another issue this one is "done".

keep it clean ;p
