### ISSUE TITLE
[BUG] Print Paused - Press button to heat nozzle

### ISSUE THREAD

**Issue by yachtjim** [MarlinFirmware/Marlin#13379]
### Description

When printing the printer will pause and request that I hit a button to resume

### Steps to Reproduce

1. Start a print
2. Hours later the printer will pause
3. Follow on screen prompts to heat extruder, and resume print
4. Printer resumes
5. Screen stays on "Load Filament" prompt
6.  Extruder starts to cool off
7.  Have to manually turn off printer

**Expected behavior:** [What you expect to happen]

I expect the print to continue and never pause

**Actual behavior:** [What actually happens]

The print pauses half way through, then the screen gets hung up on "load Filament" even though it resumes printing.  Have to manually turn unit off to clear the screen.

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by yachtjim** [comment]
Photos


![20190312_084958](https://user-images.githubusercontent.com/48486106/54214925-755c4600-44bd-11e9-91b5-b9279534f645.jpg)
![20190312_085145](https://user-images.githubusercontent.com/48486106/54214929-75f4dc80-44bd-11e9-8bce-336951a0c919.jpg)
![20190312_085232](https://user-images.githubusercontent.com/48486106/54214908-6ffefb80-44bd-11e9-86e8-dfc22baa568f.jpg)
![20190312_085219](https://user-images.githubusercontent.com/48486106/54214914-72615580-44bd-11e9-98b9-f7b9f722c049.jpg)

**Comment by yachtjim** [comment]
I can hit the button after the last image but nothing happens, it will not clear off this screen.  Extruder starts to cool off, then I have to manually shut down.

**Comment by InsanityAutomation** [comment]
My first thought is it cant reach the target temp, as im assuming by then the part cooling fan is on. Can you try to unplug the part cooling fan to see if it will reach and maintain temperature? Needs to hold there long enough to stabilize to continue.

**Comment by yachtjim** [comment]
I am not using a part cooling fan. This printer will hold its temps very well and gets up to temp quickly.

**Comment by InsanityAutomation** [comment]
Ok, the images show it quite a bit away from the target temp still. Does it ever hold at 260 for 5-10s (whatever the hysteresis time is set to) or does it keep swinging back down around 252 and 256?

**Comment by yachtjim** [comment]
It stays at 260, on the dot,  Very steady for the duration of the print. These images were taken as the extruder was heating up, and then cooling down.

**Comment by yachtjim** [comment]
Sequence of photos:

Photo 1 - this is what I see when I first get to my printer in the morning after it has stopped overnight.  Printer is paused.  I click button.

Then photo 2 shows the next screen and extruder heating.   

Photo three is what is shown next, I click the button.  Once extruder gets to 260 print resumes.

Photo 4 shows it stuck on the same screen, and the extruder temp rapidly dropping.

**Comment by reloxx13** [comment]
please post the gcode u tried to print to confirm ur slicer is not putting a pause in.
be sure u disabled post processing if u use cura.

do u use octoprint?

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by InsanityAutomation** [comment]
FYI, a pause for the part cooling fan was added which may assist this issue since it appears it was having trouble re-stabailizing during the pause.

**Comment by boelle** [comment]
@yachtjim have you retested with latest bugfix 2.0.x ?

**Comment by boelle** [comment]
@yachtjim is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
