### ISSUE TITLE
[BUG] M141 / #12201 compilation problems

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [MarlinFirmware/Marlin#13370]
scattered compilation problems while trying to activate `M141` / #12201

1. missing defs:
```
Marlin/src/module/temperature.cpp:1056:40: error: 'CHAMBER_MINTEMP' was not declared in this scope
Marlin/src/module/temperature.cpp:1056:57: error: 'CHAMBER_MAXTEMP' was not declared in this scope
Marlin/src/module/temperature.cpp:1840:76: error: 'TEMP_CHAMBER_HYSTERESIS' was not declared in this scope
```
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/Configuration.h
```
#define CHAMBER_MINTEMP 5
#define CHAMBER_MAXTEMP 100
#define TEMP_CHAMBER_HYSTERESIS 3
```
2. missing vars: `port`
```
Marlin/src/module/temperature.cpp:2918:15: error: 'port' was not declared in this scope
```
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/module/temperature.cpp#L2911
```
          #if NUM_SERIAL > 1
            , port
          #endif
```
should really use `SERIAL_BOTH` - see #13301

3. base config snapshot:
https://github.com/random-builder/Marlin/tree/f531df1c494b3f85b2c986d14f2993c0e3f3ad14

**Comment by thinkyhead** [comment]
One issue per report, please, filling out the template. This is closed because the chamber temp issue is now resolved.
