### ISSUE TITLE
Manual bed leveling, incorrect Z height.

### ISSUE THREAD

**Issue by nique88** [MarlinFirmware/Marlin#13385]
Well hello,

I've got an issue I cannot figure out.
Since 1 month I use manual mesh bed leveling. After I printed something that had to be very accurate, the issue came up.

I printed a calibration cube to be sure. The x and the y are 19.8mm but the Z is 18.85mm.

I changed the hardware from the Z with my other printer but still the same measurement.
When I put the nozzle on the bed and set manually 1mm steps I measure exactly 1mm with the feeler gauge.

I think it has something to do with the MBL. I tried also different fade heights but nothing changed.
From what I can see is that the first couple mm of the prints are squished to much on eachother.

Also this difference in Z is not linear. On every object with different heights the difference in Z is around 1.15mm.

When I print with standard bed leveling I get the measurements spot on.
Edit: I don't set Z offset because I always use babystep at start of every print so the first layer is perfect, doing it by eye.

Who has the answer for this trouble?

Thanks in advance

Printer: ender 3
Software: Cura
Firmware: marlin 1.1.9

**Comment by reloxx13** [comment]
m420 s1 in startcode to apply the mesh?

measure z without printing, move it to 50mm, mark it with tape on the the profile, move up for 100mm, mark again and measure the distance ( hope u understand what i mean :p ).


ps
> * Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

**Comment by nique88** [comment]
The m420 I have in my start code.

I know where you want go to. The calibration of my Z is ok. I did the measurement and everything is ok. Also without mesh bed leveling the cali cube comes out nearly perfect.

Tonight I will add my config.

Thanks

**Comment by shitcreek** [comment]
@nique88  Has your issue been resolved? Can we close this issue?

**Comment by nique88** [comment]
It's not resolved.
But I use standard bed leveling now. It gave me headache!

Greetings



-------- Oorspronkelijk bericht --------
Van: Luu Lac <notifications@github.com>
Datum: 15-05-19 02:44 (GMT+01:00)
Aan: MarlinFirmware/Marlin <Marlin@noreply.github.com>
Cc: nique88 <n.hoogvelt@hotmail.com>, Mention <mention@noreply.github.com>
Onderwerp: Re: [MarlinFirmware/Marlin] Manual bed leveling, incorrect Z height. (#13385)


@nique88<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnique88&data=02%7C01%7C%7Ca013f961ab934a4fafc008d6d8ce89d0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636934778914678553&sdata=MTV1%2BtT1iwax%2FOpmt3M7PWr83UIev26oEPYT5QIAXHI%3D&reserved=0> Has your issue been resolved? Can we close this issue?

**Comment by boelle** [comment]
missing label
