### ISSUE TITLE
[FR] capability string: CHAMBER_TEMPERATURE

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [MarlinFirmware/Marlin#13380]
### Description

Please add support for chamber temperature capability string.
```
CHAMBER_TEMPERATURE:1
```

#### Additional Information

This will enable OctoPrint to support chamber temperature graphs.
https://github.com/foosel/OctoPrint/issues/321#issuecomment-471943240

**Comment by boelle** [comment]
you could add that as a PR maybe? i saw that you submitted some PR's not long ago

**Comment by Andrei-Pozolotin** [comment]
ok

**Comment by Andrei-Pozolotin** [comment]
works, thank you
```
Send: N1 M115
Recv: Cap:CHAMBER_TEMPERATURE:1
```
