### ISSUE TITLE
[BUG] M191 is disabled in source

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [MarlinFirmware/Marlin#13390]
M191 is disabled in source:

https://github.com/MarlinFirmware/Marlin/blob/67bee06e4371fca6511aae99125337b6e63560d8/Marlin/src/gcode/gcode.h#L579
```
  #if HAS_HEATED_CHAMBER
    static void M141();
    //static void M191();
  #endif
```
https://github.com/MarlinFirmware/Marlin/blob/67bee06e4371fca6511aae99125337b6e63560d8/Marlin/src/gcode/gcode.cpp#L400

```
      #if HAS_HEATED_CHAMBER
        case 141: M141(); break;                                  // M141: Set chamber temperature
        //case 191: M191(); break;                                // M191: Wait for chamber temperature to reach target
      #endif
```

**Comment by boelle** [comment]
missing label

**Comment by InsanityAutomation** [comment]
Chamber heaters are getting more common. This may need a review soon.

**Comment by boelle** [comment]
@Andrei-Pozolotin is this still disabled? chamber control has just been added to graphics (GLCD)

**Comment by Andrei-Pozolotin** [comment]
@boelle : yes, still disabled:
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/gcode/gcode.h#L621
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/gcode/gcode.cpp#L447

**Comment by boelle** [comment]
should be fixed when https://github.com/MarlinFirmware/Marlin/pull/15531 is merged

**Comment by GMagician** [comment]
This may be closed, above PR has been merged
