### ISSUE TITLE
[FR] (Hour Meter, and other counters...)

### ISSUE THREAD

**Issue by rsilvers129** [MarlinFirmware/Marlin#13400]
The Zortrax M200 keeps tract of printing hours. I love to know this for logging and maintenance purposes. It is much like an odometer on a car.

So my feature request is for the EEPROM to store number of hours and tenths that the machine is printing. Number of print starts. Maybe number of print aborts. Number of prints completed.

**Comment by reloxx13** [comment]
configuration.h
```
/**
 * Print Counter
 *
 * Track statistical data such as:
 *
 *  - Total print jobs
 *  - Total successful print jobs
 *  - Total failed print jobs
 *  - Total time printing
 *
 * View the current statistics with M78.
 */
//#define PRINTCOUNTER
```

if this is what u searched for, pls close this issue, thanks! :)

**Comment by boelle** [comment]
@rsilvers129 what @reloxx13 said ^^^

**Comment by rsilvers129** [comment]
Thanks. I was not aware.
