### ISSUE TITLE
[BUG] Babystepping with M851 offset reversed with FIXED_MOUNTED_PROBE.

### ISSUE THREAD

**Issue by KevMags** [MarlinFirmware/Marlin#13414]
### Steps to Reproduce

Use   FIXED_MOUNTED_PROBE with  BABYSTEP_ZPROBE_OFFSET from Bugfix 2.0 March 7.
Use babystepping to adjust nozzle, exit babystepping and observe change to Z offset.  

**Expected behavior:** [What you expect to happen]
Since the nozzle is the probe, babystepping closer to the bed should decrease z offset.

**Actual behavior:** [What actually happens]
Babystepping the nozzle closer to the bed causes the numeric display to increase and when exiting babystepping the Z offset is increased.  When using the nozzle as probe the offset should decrease.

#### Additional Information

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/2973829/Configs.zip)

**Comment by boelle** [comment]
define Z_PROBE_OFFSET_FROM_EXTRUDER 0 

needs to be a positive number

**Comment by boelle** [comment]
and just so you know you did not enable  #define BABYSTEP_ZPROBE_OFFSET

it still says  //#define BABYSTEP_ZPROBE_OFFSET


my advice would be to forget about babystepping and get the probe offset as close to perfect you can first, then start to figure out babystepping

i dont use babystepping since i made my probeoffset work perfectly

**Comment by KevMags** [comment]
I had changed  //#define BABYSTEP_ZPROBE_OFFSET after it didn't work correctly.

By turning my LCD knob clockwise the nozzle gets closer to the bed. When doing so the display for the z offset increases and after exiting baby stepping my offset is increased.  It should decrease since I am using FIXED_MOUNTED_PROBE (nozzle as probe) and in this configuration smaller z offset moves nozzle closer to the bed.

**Comment by InsanityAutomation** [comment]
This is actually just fine being a negative number. Its more often negative with retracting or stowing probes and positive with capacitive or IR.

Along with BABYSTEP_ZPROBE_OFFSET can you enable BABYSTEP_ZPROBE_GFX_OVERLAY and see if the graphical icons line up to actual motion?

**Comment by boelle** [comment]
@KevMags btw, can you add [BUG] in title? [BUG] Babystepping with M851 offset reversed with FIXED_MOUNTED_PROBE.

**Comment by boelle** [comment]
@KevMags did you try what @InsanityAutomation  suggested?

**Comment by KevMags** [comment]
@boelle.  No, I am unconcerned about the value being positive or negative.  I just wanted my z offset to be changed in the proper direction according the the babystepping that I use.

When I use babystepping (with the nozzle being the probe) to move the nozzle closer to the bed I need the z offset to be decreased.  The firmware is correcting the z offset in the wrong (opposite) direction than what is needed.  Due to using the nozzle as the probe, the correction is exactly opposite of what would be needed with a typical probe.  The firmware appears to not be aware of this.

**Comment by boelle** [comment]
@KevMags is this still an issue?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
