### ISSUE TITLE
Marlin\src\module\temperature.cpp:826:46: error: operator ',' has no right operand[BUG] (short description)

### ISSUE THREAD

**Issue by dekra54** [MarlinFirmware/Marlin#13410]
When I try to compile the current Marlin 2.0_bugfix with #define PID_DEBUG  enabled i get the following compile error: 
Marlin\src\module\temperature.cpp:826:46: error: operator ',' has no right operand

from 
https://github.com/MarlinFirmware/Marlin/blob/09eb30dc05a727e3816ab5a407f02ada18700e23/Marlin/src/module/temperature.cpp#L821-L829

```cpp
      #if DISABLED(PID_OPENLOOP)
        SERIAL_ECHOPAIR(
          MSG_PID_DEBUG_PTERM, work_pid[HOTEND_INDEX].Kp,
          MSG_PID_DEBUG_ITERM, work_pid[HOTEND_INDEX].Ki,
          MSG_PID_DEBUG_DTERM, work_pid[HOTEND_INDEX].Kd
          #if ENABLED(PID_EXTRUSION_SCALING),
            MSG_PID_DEBUG_CTERM, work_pid[HOTEND_INDEX].Kc
          #endif
        );
```

I tried to remove the , after `#if ENABLED(PID_EXTRUSION_SCALING)` and add it to `MSG_PID_DEBUG_DTERM, work_pid[HOTEND_INDEX].Kd` but this causes additional errors.

Edit: I use the latest VSCode with PlatformIO

**Comment by boelle** [comment]
please edit title so it becomes: [BUG] Marlin\src\module\temperature.cpp:826:46: error: operator ',' has no right operand

**Comment by boelle** [comment]
and then attach your 2 config files + notepad with compile errors in a single zip file

**Comment by Ludy87** [comment]
@boelle The mistake is identified, look into the PR

**Comment by boelle** [comment]
ahh so this has been fixed but not closed?
