### ISSUE TITLE
[BUG] G90/G91 and M82/M83 relative mode set

### ISSUE THREAD

**Issue by Msq001** [MarlinFirmware/Marlin#13443]
### Description
http://marlinfw.org/docs/gcode/M082.html According to the description of the `M82` command in this document, the actual effect of the marlin2.0 firmware is inconsistent. Docs for `M82` say "This command is used to override `G91` and put the E axis into absolute mode independent of the other axes", but actually when you use `G91` to set "`relative_mode = true`", even if you use "`M82`" to set `axis_relative_modes[E_AXIS] = false` extruder coordinates are still relative. Because the relative or absolute mode judgment condition in the `void GcodeSuite::get_destination_from_command()` function is `axis_relative_modes[i] || relative_mode`

### So
So. should we modify the document or firmware?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by shitcreek** [comment]
Thanks for bringing this issue to light, we are rectifying it here: #15218 
From now on, G90/G91 will set all axis to the respective mode and override any M82/M83 that was previously called.

**Comment by Msq001** [comment]
Thank you. will close this issue
