### ISSUE TITLE
Wrong behavior of STRINGIFY macro in Bltouch commands menu

### ISSUE THREAD

**Issue by AndreaMZ** [MarlinFirmware/Marlin#13462]
Hi, i have compiled Marlin 2 , commit hash 144018736aa1e0d466e0c0693cf7992190e4981f dated 18/03/2019 - branch bugfix-2.0.x
Compiled with GCC 8.2.0 emitting AVR binary code.

in module menu_configuration.cpp there are BlTouch commands like this
**MENU_ITEM(gcode, MSG_BLTOUCH_RESET, PSTR("M280 P" STRINGIFY(Z_PROBE_SERVO_NR) " S" STRINGIFY(BLTOUCH_RESET)));**
The gcode string obtained is wrong , the second STRINGIFY expands to "BLTOUCH_RESET" instead of "160" so the string sent to command interpreter is "M280 P0 SBLTOUCH_RESET" instead of the correct "M280 P0 S160"

I have temporary fixed the line as:
**MENU_ITEM(gcode, MSG_BLTOUCH_RESET, PSTR("M280 P" STRINGIFY(Z_PROBE_SERVO_NR) " S160" ));**

best regards
amz

**Comment by InsanityAutomation** [comment]
A pull request is already open with code to resolve this.

**Comment by InsanityAutomation** [comment]
FYI this is fixed upstream, please verify and close this issue.

**Comment by AndreaMZ** [comment]
ok

**Comment by AndreaMZ** [comment]
Further tests done : ok. bug closed
thank you for feedback
