### ISSUE TITLE
BLTouch 

### ISSUE THREAD

**Issue by jacobwtyler** [MarlinFirmware/Marlin#13480]
I’m trying to setup an ANTCLABS BLTouch on a CR10 after successfully setting one up on an Ender 3 last week. Tried everything I can think of so far and I can’t get the BLTouch to sense the build plate. The original Z endtop is disconnected. Firmware settings are in line with every tutorial I’ve found. I’m running Marlin 1.1.9 Vanilla. I’ve tried setting Z probe endstop inverting to true and false with no luck.  Endstop status is open with M119 command. Turned on probe logging in the adv.h tab and ran the M43 S command but I’m unsure what I was looking for. I made a quick video of the issue. If anyone would be willing to help me troubleshoot this, I’d be extremely thankful.  I’m out of ideas. 

https://youtu.be/f3q0sUNVZPs

**Comment by reloxx13** [comment]
Start with posting your configuration and use/try origin Marlin.

**Comment by Bob-the-Kuhn** [comment]
You may have a V3 BLTouch.  We're having problems with them.  Take a look at #13454 and #13345.

**Comment by Ragaroah** [comment]
Exact same issue I've been having @jacobwtyler. Marlin v2.0 (bugfix version) solved my issues, together with uncommenting:
#define BLTOUCH_V3

**Comment by jacobwtyler** [comment]
Is the v2.0 bugfix the stable release at this point? I’m going to try it when I get home in an hour but I want to be sure and try the correct version. Pull up resistor worked but the mesh leveling isn’t nearly as accurate as my other ender 3 with a v2.1 BLTouch. Hopefully it’s just the pull-up resistor causing issues and the bug fix will be the answer. Thanks for your help guys.

**Comment by jacobwtyler** [comment]
Yeah okay I’m going to expose my newbness but can anyone point me in the direction of the correct v2.0.x bug fix? I see @InsanityAutomation has a branch. Is that the one I should be trying?

**Comment by jacobwtyler** [comment]
Okay I’ve got the v2.0.c bug fix zip downloaded and extracted but there are no example configurations included. Obviously this would be way too hard to keep up with and fix bugs but I’m not sure how much I have to edit now that would’ve been included in the creality cr10 example configuration.h file. Is it pretty much just bed size or is there way more to it?

**Comment by InsanityAutomation** [comment]
@jacobwtyler can look at the CR10 branches here - https://github.com/InsanityAutomation/Marlin/tree/Creality_2.0_Devel

**Comment by jacobwtyler** [comment]
Cool. I think I’ve got it set up and ready to flash. Just wondering why there are way less tabs in v2.0. Is there anything I’m missing or have they been combined somewhere else?

**Comment by InsanityAutomation** [comment]
Arduino ide can't see subfolders.

**Comment by jacobwtyler** [comment]
Everything flashed fine and I was able to remove the pull-up resistor from the BLTouch on my CR10 and it worked! Great fix!

**Comment by psavva** [comment]
Suggest you close this issue :)
