### ISSUE TITLE
digitalPinHasPWM function unavailable on STM32F1

### ISSUE THREAD

**Issue by pinchies** [MarlinFirmware/Marlin#13503]
digitalPinHasPWM doesn't seem to work ... stops the builds working on STM32F1.

    platform = https://github.com/platformio/platform-ststm32.git
    framework = arduino
    board = genericSTM32F103ZE

Marlin\src\module\thermistor/../../inc/../HAL/HAL_STM32F1/fastio_STM32F1.h:52:33: error: 'digitalPinHasPWM' was not declared in this scope

It is available on STM32 (the official ST HAL):
\.platformio\packages\framework-arduinoststm32\STM32\cores\arduino\pins_arduino.h

But NOT on the Maple-based HAL (STM32F1).

**Comment by pinchies** [comment]
Once this is fixed && PR https://github.com/MarlinFirmware/Marlin/pull/13502 is accepted, it should also resolve issue https://github.com/MarlinFirmware/Marlin/issues/13489

**Comment by pinchies** [comment]
Example solution for this one, by programmers better than me:
https://github.com/jmz52/Marlin/commit/cc39d62ab608b4550fde4e3bd7b60ddba1f69bc3#diff-237285c047dad808f73698c139144e1aR306

**Comment by ShohninDmitriy** [comment]
the entire stm32f1 line does not compile with this error

**Comment by pinchies** [comment]
Ones that use software pwm will not fail, is that the only exception?
