### ISSUE TITLE
Problem when stopping a print (through SD Card)

### ISSUE THREAD

**Issue by LordDarkneo** [MarlinFirmware/Marlin#13517]
Hi there!

### Description

When stopping a print (started via SD Card), the hotend is going down, towards the printed part. Damaging the part is not a problem (as I cancelled the print), but it forces on all the Z axis and the bed... That is not really good for the printer... 

### Steps to Reproduce

You caneasily reproduce the issue:
1- Get a temperature tower on thingi
2- Print the tower
3- Stop the print at like 50/60% of the print and prepare to remove the already printed part!
4- Stay close to remove the tower when the hotend is moving down where it was when you stopped the print

**Expected behavior:** When cancelling the print, I would like to have the hotend going up (for like 5 cm)

**Actual behavior:** The hotend goes up for few cm and then goes down all over the printed part...

**Comment by 7eggert** [comment]
It should not go down but stay in place. (Still the nozzle will burn a hole into the print.)

Edit: Maybe you configured to disable the steppers on stop and your printer needs to keep the Z motors powered.

In order to do more than that, I created:
github.com/MarlinFirmware/Marlin/pull/12850; you can cherry-pick it.

**Comment by robbycandra** [comment]
I create PR to Park Nozzle when stop printing. #13547

**Comment by robbycandra** [comment]
This issue should be closed.

**Comment by LordDarkneo** [comment]
I'll try on the 2.0.x version then, that's it? So far I am still on 1.1.9.... 

Thanks for fixing this ! :)

**Comment by robbycandra** [comment]
@LordDarkneo , you can close this issue
