### ISSUE TITLE
[BUG] [bugfix-2.0.x] Ender 3 wrong CHOPPER_TIMING at config

### ISSUE THREAD

**Issue by ArturNadolski** [MarlinFirmware/Marlin#13551]
Current definition of CHOPPER_TIMING at Ender 3 Configuration_adv.h file:

#define CHOPPER_TIMING CHOPPER_DEFAULT_12V

Ender 3 is using 24V for steppers so CHOPPER_TIMING need to be set CHOPPER_DEFAULT_24V

**Comment by JosefKuchar** [comment]
Fixed now so it can be closed

**Comment by boelle** [comment]
@ArturNadolski can you confirm its fixed and click close button below?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by hhoweson** [comment]
I just download the latest release and noticed that the default chopper timing is still 12v for the ender 3 config, are we sure this has been fixed?

**Comment by ArturNadolski** [comment]
As I wrote at OP... Ender 3 is 24V so please set CHOPPER_DEFAULT_24V as default.

**Comment by hhoweson** [comment]
I only meant to point out that the issue has been closed yet it does not seem to be fixed

**Comment by InsanityAutomation** [comment]
Seems this was rebroken with a careless update last month. It had been fixed at one point.

**Comment by InsanityAutomation** [comment]
I should note this is only valid for people upgrading the board to an SKR or something as thats only used for uart controlled drivers.
