### ISSUE TITLE
 Dual -X-Carriage-Mode 

### ISSUE THREAD

**Issue by sikousikou** [MarlinFirmware/Marlin#1356]
EXTRUDER1_Z_OFFSET has no effect
"#define EXTRUDER1_Z_OFFSET 0.0" is defined alright but is not referenced any where in the code.

**Comment by thinkyhead** [comment]
You can blame this commit: https://github.com/MarlinFirmware/Marlin/commit/9547fb9dfb12152e620fdc03b48c563028c3d5fc

**Comment by buildrob** [comment]
Hi, that was part of an additional feature I was thinking about when implementing the Dual-X carriage mode. The feature would have added too much complication and so I removed it ... but obviously forgot to remove the #define which was associated with it.

**Comment by thinkyhead** [comment]
Thanks for the insight! We'll pull out this line soon.
