### ISSUE TITLE
After G29

### ISSUE THREAD

**Issue by starzleo** [MarlinFirmware/Marlin#1358]
Can we move X0 Y0 after a G29 ? if so, what should we put gcode ?
The G28 canceling the G29

thx

vincent (FR)

**Comment by starzleo** [comment]
why this question ?
I've a same problem https://github.com/MarlinFirmware/Marlin/issues/732

**Comment by boelle** [comment]
then write in #732 that you have the same problem... not create a new issue... it will make it harder to see who has a problem if they are spread on 10+ issues
