### ISSUE TITLE
[FR] Single SCARA support?

### ISSUE THREAD

**Issue by Power3DPrinting** [MarlinFirmware/Marlin#13589]
Hi, is single SCARA kinematics supported by Marlin as of mid 2019? if not, could anyone share how to rewrite the kinematics or add in a translator? Been curious for a while about 3D printer firmware and would really like to learn how to write my own. Thanks.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/10089
