### ISSUE TITLE
[BUG] Marlin 2.0 - Setting bed offsets creates unwanted behavior

### ISSUE THREAD

**Issue by paulpenney** [MarlinFirmware/Marlin#13594]
### Description

When setting an negative bed offset to make sure that the nozzle will be at the corner of the bed at X0 Y0, the printer does not act as expected. 

### Steps to Reproduce

#define X_MIN_POS -43
#define Y_MIN_POS -12

Printer is CR10S 4, using the CR10S5 example configuration in the marlin examples folder. 

**Expected behavior:** [What you expect to happen]

When homed, the printer should read -43 X and -12 Y at the endstops.

**Actual behavior:** [What actually happens]

When homed, the printer reads X "4" and Y "2" ... completely ignores the negatives and seems to only take snippits of each number that was input. 

#### Additional Information

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3050505/Configuration.zip)

**Comment by swilkens** [comment]
Something seems to have gone wrong with your bug report, please update the original post with the actual description of your issue.

When you do, please also ZIP your `Configuration.h` and `Configuration_adv.h` files and attach that ZIP file to the post.

**Comment by paulpenney** [comment]
> Something seems to have gone wrong with your bug report, please update the original post with the actual description of your issue.
> 
> When you do, please also ZIP your `Configuration.h` and `Configuration_adv.h` files and attach that ZIP file to the post.

Thanks, corrected.

**Comment by GMagician** [comment]
Try setting MANUAL_?_HOME_POS equal to ?_MIN_POS

**Comment by gloomyandy** [comment]
Please post a picture of whatever display it is you are referring to in the bug report.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by boelle** [comment]
@paulpenney is this still an issue?

**Comment by paulpenney** [comment]
Negative. 

Sent from Mail for Windows 10

**Comment by boelle** [comment]
oki doke, will close then

we can always reopen
