### ISSUE TITLE
[BUG] [bugfix-2.0.x] compile error when SWITCHING_NOZZLE is enabled

### ISSUE THREAD

**Issue by scott0122** [MarlinFirmware/Marlin#13604]
### Description

DUE+RAMPS-FD 2.1A

In file included from Marlin\src\module\tool_change.cpp:53:0:
Marlin\src\module\tool_change.cpp: In function 'void move_nozzle_servo(uint8_t)':
Marlin\src\module\tool_change.cpp:124:85: error: 'e' was not declared in this scope

[conf.zip](https://github.com/MarlinFirmware/Marlin/files/3051160/conf.zip)

**Comment by marcio-ao** [comment]
@scott0122: The fix has been merged. Please test and close this issue if it resolves the problem. Thanks!
