### ISSUE TITLE
[BUG] [bugfix-2.0.x] enable AUTO_BED_LEVELING_UBL cause M502 no response

### ISSUE THREAD

**Issue by scott0122** [MarlinFirmware/Marlin#13602]
### Description

DUE+RAMPD-FD 2.1a

enable AUTO_BED_LEVELING_UBL cause M502 no response

before AUTO_BED_LEVELING_UBL enabled and send M502
![image](https://user-images.githubusercontent.com/39105828/55677967-5918c100-5924-11e9-936f-4784a0226f71.png)

after AUTO_BED_LEVELING_UBL enabled and send M502
![image](https://user-images.githubusercontent.com/39105828/55874607-70c2a480-5bc5-11e9-9589-74072c966809.png)

[conf.zip](https://github.com/MarlinFirmware/Marlin/files/3051152/conf.zip)

**Comment by Ludy87** [comment]
it is written: "echo: hardcoded Default Settings Loaded". 🤔

What should your opinion still come from?

**Comment by scott0122** [comment]
> it is written: "echo: hardcoded Default Settings Loaded". 🤔
> 
> What should your opinion still come from?

***before*** AUTO_BED_LEVELING_UBL ***enabled*** and send M502
![image](https://user-images.githubusercontent.com/39105828/55687109-be5bc900-599b-11e9-991a-7f51e610b027.png)

**Comment by swilkens** [comment]
The pictures are the same. In all your pictures, `M502` responds with `Hardcoded Default Settings Loaded`. This is correct.

What is wrong in your opinion? M502 will only load the hardcoded settings, nothing else. Are you expecting more to happen?

**Comment by scott0122** [comment]
> The pictures are the same. In all your pictures, `M502` responds with `Hardcoded Default Settings Loaded`. This is correct.
> 
> What is wrong in your opinion? M502 will only load the hardcoded settings, nothing else. Are you expecting more to happen?

Sorry, I attached the wrong picture. Fixed~
