### ISSUE TITLE
Makefile doesn't include correct VPATH for Teensy variant

### ISSUE THREAD

**Issue by PxT** [MarlinFirmware/Marlin#1361]
Makefile references SPI.cpp and LiquidCrystal.cpp which are not found in the current code. I think these should be removed.  If you agree I can create a PR.

**Comment by monkeydave** [comment]
Doesn't it pull them from the arduino libraries directorys, see lines around 225.

**Comment by PxT** [comment]
Ah ok, see that now.  However on my board HARDWARE_VARIANT = Teensy and the compile failed on those files.  Looks like the paths are not getting pulled in correctly for that variant.

**Comment by boelle** [comment]
fixed by PR # 1363
