### ISSUE TITLE
[BUG] UBL correction not applied at xmax/ymax?

### ISSUE THREAD

**Issue by lutorm** [MarlinFirmware/Marlin#13613]
### Description

If the position is moved to the xmax/ymax mesh positions (the coordinate of the upper mesh points seen with G29 T), the correction is nulled out. Any position < xmax/ymax has correction. In my specific case, xmax/ymax is 285. If I move to x=284.99, everything works as expected. If I then move to x=285, there is a sharp change in z and the bed no longer corresponds to z=0. The same for y.

This is very confusing because when you move to a mesh point with g42, you expect the correction to be applied at that point. But this is not true for the upper mesh points.

The error does *not* exist for xmin/ymin. In my case xmin/ymin is 1, but moving to x=1 (or even x=0) does not result in a similar z-change.

### Steps to Reproduce

1. Configure UBL.
2. Load/Create a UBL mesh with nonzero corrections at the mesh x/y max positions.
3. Enable UBL.
4. Move to the max mesh x-position shown in G29 T.

**Expected behavior:** [What you expect to happen]

Since the max x-position is on the probed mesh, the bed should be at z=0.

**Actual behavior:** [What actually happens]

The bed does not correspond to z=0 but rather to about the z of that mesh point, indicating the correction is not applied.
 
#### Additional Information

[config.zip](https://github.com/MarlinFirmware/Marlin/files/3051914/config.zip)

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
