### ISSUE TITLE
[BUG] LPC1769 can't use ReprapDiscount GLCD

### ISSUE THREAD

**Issue by FLYmaker** [MarlinFirmware/Marlin#13617]
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
If I enable this line of code, he will report an error. Smoothie can use it

Why can't Marlin

**Comment by ManuelMcLure** [comment]
What exact board? There are several LPC1769 boards out there with different connections. What exact error? I’m using REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER just fine on my LPC1768-based Re-ARM.

**Comment by FLYmaker** [comment]
> 什么确切的板？有几个LPC1769板有不同的连接。什么确切的错误？我在基于LPC1768的Re-ARM上使用REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER就好了。
Self-made, based on smoothieboard 5x

**Comment by psavva** [comment]
Then I suggest checking your schematics, ensure pins are defined correctly, SPI interface on an oscilloscope, etc.

Please check https://github.com/MarlinFirmware/Marlin/issues/7076 for current supported boards.

**Comment by p3p** [comment]
> Why can't Marlin

It can, and does. 

Don't ignore issue templates they are there for a reason.
