### ISSUE TITLE
[BUG] Garbled display when using LIGHTWEIGHT_UI and steppers deactivate while in Z-Offset screen

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#13623]
### Description

Garbled display when using LIGHTWEIGHT_UI and steppers deactivate while in Z-Offset screen

### Analysis

Since the LIGHTWEIGHT_UI  uses the text buffer rather than the graphics buffer, it needs to be notified when Marlin enters and exits the status screen so that it can properly clean up after itself.

This notification is handled by the `MarlinUI::update()` method which monitors `currentScreen` and triggers a clear of the screen when transitioning in and out of `status_screen`.

However, on stepper timeout, the status screen gets painted directly outside of `MarlinUI::update()` in [Marlin.cpp](https://github.com/MarlinFirmware/Marlin/blob/9abe9aff56d44d42c9dc52679cc9f17592cd0bd4/Marlin/src/Marlin.cpp#L476):

```
        #if HAS_LCD_MENU
          ui.status_screen();
          #if ENABLED(AUTO_BED_LEVELING_UBL)
            if (ubl.lcd_map_control) {
              ubl.lcd_map_control = false;
              ui.defer_status_screen(false);
            }
          #endif
        #endif
```

This code was added in commit eb4bf93ea4 and it is unclear to me what the intent was. There are two possible solutions, depending on what was intended.

### Solution #1:

Replace `ui.status_screen()` with `ui.return_to_status()`. On stepper timeout, if the user was in the menu, they will be kicked back into the status screen.

### Solution #2

Only call `ui.status_screen()` if the user is already in the status screen:

```
        #if HAS_LCD_MENU
          if(ui.on_status_screen())
             ui.status_screen();
          #if ENABLED(AUTO_BED_LEVELING_UBL)
            if (ubl.lcd_map_control) {
              ubl.lcd_map_control = false;
              ui.defer_status_screen(false);
            }
          #endif
        #endif
```

### Solution #3

Remove the call to `ui.status_screen()`. It's unclear what it is accomplishing. If the intent was to draw the "?" for the position, I suspect this will get done automatically on the next LCD update. Without the redraw, the code would look like this:

```
        #if HAS_LCD_MENU && ENABLED(AUTO_BED_LEVELING_UBL)
            if (ubl.lcd_map_control) {
              ubl.lcd_map_control = false;
              ui.defer_status_screen(false);
            }
        #endif
```

@InsanityAutomation: The commit was yours. Can you shed any light on why you are repainting the status screen and whether any of the above solutions would be acceptable?

### Steps to Reproduce

1. Enable LIGHTWEIGHT_UI
2. Go into Z-offset screen
3. Wait a really long time for the steppers to inactivate
4. Notice that the screen is now garbled. It will remain garbled until you click to enter a menu, click again to exit the menu.

Another place where this happens is that if the user is playing one of the new games, the display will become garbled if the steppers timeout.

**Expected behavior:** On timeout, it should clear the graphics buffer prior to painting the text for the status screen.

**Actual behavior:** On timeout, the status screen is painted, which overlays the text on top of the graphics elements from the Z-offset screen.

**Comment by InsanityAutomation** [comment]
Solution #1 was the intended action here. Probably grabbed the wrong function here.

**Comment by marcio-ao** [comment]
I'm about to leave for the day, but just curious as to why you want to kick the user back to the status screen when the steppers timeout? What if they are about to get a high score in Space Invaders? :)

**Comment by InsanityAutomation** [comment]
From the babystepping screen, we dont want them adjusting z offset endlessly to a value that then rams through the bed on the next move when theyre active again :)

**Comment by marcio-ao** [comment]
@InsanityAutomation: It seems like then the correct solution is either to reset the stepper timeout when babystepping (so the steppers never timeout while the user is babystepping) or to return them to that status screen only if they are in the babystepping screen when the timeout happens. Personally, I think the first solution is better. Babystepping moves the steppers, so the idle timer should be reset.

**Comment by InsanityAutomation** [comment]
My initial thought was to defer stepper timeout like advanced pause does, but havnt had time to get back to that.

**Comment by marcio-ao** [comment]
I'll see if I can whip something together.

**Comment by marcio-ao** [comment]
@InsanityAutomation: It looks like @Roxy-3D already added the [required line](https://github.com/MarlinFirmware/Marlin/blob/ba31d39f6df480c390aa188024bca447eab1527f/Marlin/src/feature/babystep.cpp#L131) to "babystep.cpp" in commit 9cee81d47eea0c8700e265f10f103ca99499511f which keeps the steppers from timing out when babystepping.

I think we could safely remove `ui.status_screen()`, or perhaps even the entire block below, since timeouts should not happen while babystepping:

```
       #if HAS_LCD_MENU
          ui.status_screen();
          #if ENABLED(AUTO_BED_LEVELING_UBL)
            if (ubl.lcd_map_control) {
              ubl.lcd_map_control = false;
              ui.defer_status_screen(false);
            }
          #endif
        #endif
```

@Roxy-3D: Do you have any thoughts on this?

**Comment by InsanityAutomation** [comment]
That will reset it on each step, but if left idle on the screen for a long period will still idle out. This would need to be added to the menu function so its called repeatedly.

**Comment by marcio-ao** [comment]
@InsanityAutomation: I don't think that is needed either. @Roxy-3D[ added BSA_ENABLE](https://github.com/MarlinFirmware/Marlin/blob/ba31d39f6df480c390aa188024bca447eab1527f/Marlin/src/feature/babystep.cpp#L95) to the babystepping code. So as far as I can tell, if the steppers are disabled when babystepping commences, then they will be re-enabled.

**Comment by marcio-ao** [comment]
See my new PR https://github.com/MarlinFirmware/Marlin/pull/13630

**Comment by InsanityAutomation** [comment]
Thats fine for when the babysteped values are not stored by M851 as the probe offset, which is how Roxy operates, however with either of our firmware builds this means that when steppers are de-energized we may lose z position drifting slightly so it can no longer be relied on.

**Comment by marcio-ao** [comment]
@InsanityAutomation: So whenever the stepper de-energizes, the accuracy loss is far greater than any tuning the user may have done through babystepping? If that is the case, it doesn't matter if the user is returned to the main screen on stepper timeout, because their fine-tuning is borked from that point forward anyway.

I think it would be more correct to say BABYSTEP_ALWAYS_AVAILABLE is fundamentally incompatible DISABLE_INACTIVE_Z ... why not simply have the sanity check prevent these features from being used together?

**Comment by marcio-ao** [comment]
> however with either of our firmware builds this means that when steppers are de-energized we may lose z position drifting slightly so it can no longer be relied on.

For what it is worth, we no longer have DISABLE_INACTIVE_Z enabled on our Mini 2 or TAZ Pro.

**Comment by InsanityAutomation** [comment]
Short term incompatible avoids an issue there, but at some point ill do a proper defer like is done for parking. Personally I wouldnt want to leave a stepper humming all the time. A burned out driver has been the only major failure on one of my Taz6 machines after all.

**Comment by marcio-ao** [comment]
@InsanityAutomation: Well, your original implementation wasn't doing what you thought it was doing anyway, so I'll let this PR stand. If you wish, you can replace `ui.status_screen()` with `ui.return_to_status()` on your customized FW to get the behavior you intended, but I don't think that ought to happen in the official release as it is incorrect to return the user to the status screen _from any screen_ when the steppers de-energize.

**Comment by InsanityAutomation** [comment]
Yup, hence why I agreed with it above for now and ill get back to doing it completely some other time. There are likely other screens we would want them to return to status from though. The UBL mesh edit screens are a prime example.

**Comment by marcio-ao** [comment]
Closing this since it has been fixed.
