### ISSUE TITLE
[FR] hello and it possible to have sub marlin 2.0 build number to see the new update ex marlin bugfix 2.0 rc0104 etc rc0105? thank you

### ISSUE THREAD

**Issue by corv45** [MarlinFirmware/Marlin#13635]

**Comment by 7eggert** [comment]
If you use git to download Marlin, you can have a hexadecimal ID of the changes. You can also see a tree of the changes in the gitk program.

E.g. for today, there would already be 9 changes (click "commits" to see them and select the bugfix branch) - each change might be considered a version upgrade. Also when working with git, several people may work individually - the changes aren't ordered. Therefore version numbers aren't useful. ¢¢

**Comment by corv45** [comment]
oki for commits I did not know. and for you can have a hexadecimal identifier I can not find it?

**Comment by swilkens** [comment]
The list of commits shows you what was changed in time. There, you can also see the full code base at that point in time, so you can download `Marlin-2.0.x-5018fda` for example.

https://github.com/MarlinFirmware/Marlin/commits/bugfix-2.0.x

![Untitled](https://user-images.githubusercontent.com/13329383/55858625-7b068380-5b70-11e9-9db4-2b2d700894f5.png)

This is more of a git question than a Marlin question :)

**Comment by InsanityAutomation** [comment]
It can be done with a git hook however every single person actually merging anything in will need to have that set up in their environment. It's been discussed before, but as far as I know there is no way to have it done automatically if you merge from the web interface, or if it's merged by a user without their environment configured for it. That just makes it very difficult to actually maintain correctly at this scale.

**Comment by 7eggert** [comment]
The ID is a checksum for the commit. This checksum is the ID for the code at that point in time.

There are branch names, too, like bugfix-2.0.x, they are a pointer to that checksum, and they get updated on each commit.

Also you can have tags doing about the same, except they are not updated automatically. Github will show them as releases (as far as I instant-googled).
