### ISSUE TITLE
[BUG] Axis homes in wrong dir if Axis is inverted

### ISSUE THREAD

**Issue by hu1buerger** [MarlinFirmware/Marlin#13656]
### Description

When homing an axis that is inverted and 

### Steps to Reproduce

1. Version 2.0 commit: 5018fdacbeb0807fc255f83049044b89323eea55
2. #define INVERT_Y_DIR true
    #define Y_HOME_DIR -1
3. Run G28 Y

**Expected behavior
Expecting that the homing direction also switches

**Actual behavior
The Carriage drives in to the wrong dir and crashes in to the other end.

**Comment by robbycandra** [comment]
INVERT Y Dir  change motor direction
Y_HOME_DIR change Homing direction
To change switches you need to change From YMAX to YMIN. 

Your expected behavior is not correct.
Better close this issue.
