### ISSUE TITLE
[BUG] LCD menu and Z offset not saving 

### ISSUE THREAD

**Issue by bogaskilop** [MarlinFirmware/Marlin#13666]
when editing Z offset for bl touch  after setting up offset and choose  save settings  from lcd menu  settings are not saved   but   it changes and save   with M851  and m500 in terminal

**Comment by InsanityAutomation** [comment]
Can you test with todays bugfix branch? A PR was just merged that may fix this. If not we may need to take a closer look. If this is now working, please go ahead and close the issue. Thanks.

**Comment by bogaskilop** [comment]
will test  tomorrow on one printer i need to change few settings in firmware for new nozzle and different bl touch location so it is needed to put new firmware and what about my issue  #13773  ?

**Comment by InsanityAutomation** [comment]
@bogaskilop I dont have a width sensor to do any testing on that one with. If I had hardware here, I would be able to debug it. Ive gotten a couple reports of issues there.

**Comment by bogaskilop** [comment]
@InsanityAutomation ok do you know maybe on wich marlin version width sensor is working good?  i want to make few tests with this sensor and my printers.

**Comment by boelle** [comment]
maybe configs would be usefull?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
