### ISSUE TITLE
[FR] Disable bed heater when printing on higher layers

### ISSUE THREAD

**Issue by ArturNadolski** [MarlinFirmware/Marlin#13680]
Idea is to stop heating bed when there is no need for it. When all elements from first layer or layers have been printed there is no need to pump power to the bed.

**Comment by SJ-Innovation** [comment]
Yes there is a need for the bed to be powered... The part will shrink at the bottom and pop off the bed while still printing. If this is desired it can be easily implemented by adding the relavent gcodes to the print code. This should not be a firmware feature (imho).

**Comment by robbycandra** [comment]
Agree with @SJ-Innovation , it is gcodes job.

**Comment by LinoBarreca** [comment]
@boelle close this. It's a slicer setting.
