### ISSUE TITLE
[BUG][bugfix 2.x] Bed heating bad behaviour

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#13693]
This follow my previous #13070 and #12061.

I'm back with this because today I had same issue...usually I can work with bed temp of 90° (its slow to reach it but it can keep 90° for a whole 1h print).
Sometime (rare) I face a complete lock in temperature control. I faced always on output and out always off output with a correct thermistore feedback.
I'm wondering if this is not related to my "slow" heating that lead to an overflow/underflow computation.

My suspect are on:
temp_iState += pid_error;

if pwm works for too long far from 0%/100% temp_iState may overflow.

I'm sure that HW works perfectly because when problem is present I may solve it turning on/off bed heating using "repetier button". In one situation (bed was always on) turning off and on a couple of time solved for the whole print. This is why I think about some overflow computation

**Comment by 7eggert** [comment]
I'm using limit switching with a hysteresis of 0.2 °C - this might be a temporary solution for you. HTH

**Comment by GMagician** [comment]
I'm investigating on it...Not sure but I think I saw a target set point to 0...but that's not in gcode...

**Comment by GMagician** [comment]
I found a bad cable...not sure about it but I close this till next event...
