### ISSUE TITLE
[BUG] [bugfix-2.0.x] FILAMENT_WIDTH_SENSOR causes controller to freeze

### ISSUE THREAD

**Issue by klcjr89** [MarlinFirmware/Marlin#13701]
### Description

Enabling the `FILAMENT_WIDTH_SENSOR` feature causes my Azteeg X5 mini v3 controller board to hang/freeze and is nonresponsive.

### Steps to Reproduce

• Uncomment the `FILAMENT_WIDTH_SENSOR` definition to enable the feature.
• Compile firmware and place on SD card.
• Turn power switch on to controller and let it flash the new firmware.
• Firmware/controller freezes after Marlin boots and after a few seconds have passed (5 or less seconds).

**Expected behavior:**

I expect the controller board to not freeze.

**Actual behavior:**

The controller board freezes and is unusable. The screen freezes, and the encoder is unresponsive to clicks.

#### Additional Information

Zip file attached of config and board pin files.
[ConfigFiles.zip](https://github.com/MarlinFirmware/Marlin/files/3077929/ConfigFiles.zip)

**Comment by psavva** [comment]
Do you get any output from the serial monitor via your host software?

**Comment by klcjr89** [comment]
> Do you get any output from the serial monitor via your host software?

I don't use host software.

**Comment by klcjr89** [comment]
Any update on fixing this?

**Comment by Roxy-3D** [comment]
Using Host software will provide more information than what we have now.

Any update on the full set of error messages being produced?

**Comment by klcjr89** [comment]
I don't see how host software will report anything if the controller freezes. Regardless, I will hook it up if you want me to.

**Comment by klcjr89** [comment]
I just connected it to my computer, and it doesn't report anything of use before the controller freezes and disconnects from the computer..

![Image](https://i.imgur.com/jno3jt9.png)

**Comment by klcjr89** [comment]
Do I need to send `M111` before the controller hangs? If so, what gcode mask bit do I need to send appended to `M111`?

**Comment by klcjr89** [comment]
Any update on how to fix this and debug?

**Comment by klcjr89** [comment]
@Bob-the-Kuhn Any tips?

**Comment by klcjr89** [comment]
@thinkyhead What can be done? I'm struggling to figure this out.

**Comment by InsanityAutomation** [comment]
Discussed with the user on Discord and we found the issue. @klcjr89 can you close this once the above PR is merged?

**Comment by klcjr89** [comment]
@InsanityAutomation Absolutely

**Comment by boelle** [comment]
closing as the PR has been merged
