### ISSUE TITLE
Vase mode weird behavior

### ISSUE THREAD

**Issue by kaijrock23** [MarlinFirmware/Marlin#13725]
Hi, when I print in vase mode this happen
https://youtu.be/8rhoIhAdOjY
It happen only in vase mode tried cura and simplify same behavior with both.
Marlin 2.0 with preconfigured ender 3 files.
I always printed fine until today, vase mode too.

**Comment by shitcreek** [comment]
Have you checked your connections?

**Comment by kaijrock23** [comment]
Yes i did, I tried 3 different sd cards and other gcodes in vase mode, same results, I tried with USB connection and it printed without problem, just stopped for 1 sec for two time randomly but I read it is a simplify behavior glitch.

**Comment by kaijrock23** [comment]
So I think that the sd slot is the problem.

**Comment by robbycandra** [comment]
Ha.... @kaijrock23 , i know you print woman body from thingiverse. I print it with marlin 2.0 and no problem.
I guess it is your SD card problem, check sdcard Reader speed setting and speed class of your SDCard.

**Comment by kaijrock23** [comment]
I will contact creality and have a new motherboard, clearly it's the card reader that suddenly stopped working, any suggestion for a good SD card for the ender 3?

**Comment by robbycandra** [comment]
Try to change the SD Card first.

**Comment by kaijrock23** [comment]
Done, same results.

**Comment by Tymek** [comment]
I have the same problem with SKR v1.1, (bugfix-2 branch). Weird stuff.. Only _spiralize mode_ prints this way - other `.gcode`s work fine. (from Cura & Slic3r) If switching card solves this I will let you know.

**Comment by Tymek** [comment]
It worked. I reconnected everything today and sliced with stock settings where only printing mode was changed. "cannot reproduce :| "

**Comment by boelle** [comment]
will close this one as it seems to have been a hardware issue
