### ISSUE TITLE
[BUG] Steps/mm corrupt in config menu if go to edit them

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#13735]
Newest Marlin v2 build  #13727

Menu-Configuration-Advanced Settings-Steps/mm, then select one of them (as if to edit it)..

Value shown is totally wrong and unchangeable. It then sets the config to that wrong value, after which you cannot change.

This is on the new BigTreeTech SKR v1.3 board.

**Comment by marcio-ao** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/13696, which has already been fixed.

**Comment by ghost** [comment]
oops
