### ISSUE TITLE
G29 dont work: L,R,F,B out of Bounds

### ISSUE THREAD

**Issue by arnold-b** [MarlinFirmware/Marlin#13745]
Hello, 
i m using current BugFix 1.1.x. 

If i send G29 i get just the Message: ? (L,R,F,B) out of bounds. 

I don´t find the reason. 

Thanks

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/3091730/Configuration.txt)

**Comment by robbycandra** [comment]
Try Bugfix 2.0

**Comment by arnold-b** [comment]
At least on this Version i don´t get the bounds error. But on starting G29 marlin Moves the Z Axis with some Feed and the stepper lose steps. After one second it use the defined Feedrate. But the position is already wrong and probing fails. 


And second my z_min_probe_pin 11 dont work anymore. even it is defined. 

Is there any relaiable version. I´m tired of searching. Never touch a running system

**Comment by reloxx13** [comment]
u set a max feedrate on z to 2000 and wonder why its skipping?...

if its configured and connected correctly, probing works fine with 1.1.x and 2.0.x

try and set it up with default settings + probe and if it works push it higher.
and pls explain ur connection of the probe, what printer, and upload ur 2.0.x config and config_adv.
default z endstop disabled?

**Comment by arnold-b** [comment]
If found the problem. The stepper was skipping because of XY_PROBE_SPEED in configuration.h 
I didnt know it exist and it was on 8000.  
I don´t know why suddenly the developers using the word "speed" instead of "feedrate". Just makes it more complicated.

Probe_pin didnt work, because i used pullup on this pin
