### ISSUE TITLE
[BUG] During heating Marlin hangs. Printer never start to Print

### ISSUE THREAD

**Issue by arnold-b** [MarlinFirmware/Marlin#13766]
Hello, 
Marlin 2.0
if i start to Print. The Printer is endless heating. Even i i send stop or disconnect. Heating only stop on reset. 
This Version just waste time

**Comment by Idorobots** [comment]
Hi Mr Entitled, could you please include your Configuration.h and Configuration_adv.h and write some more about your setup?

**Comment by reloxx13** [comment]
Reading this non-explaining-anything issue was waste of time, too.

**Comment by boelle** [comment]
yeah i agree here, the issues is pointless so will close it and we can reopen if the OP comes up with a better and full descriptive text
