### ISSUE TITLE
[BUG] python 2  -> 3 script migration

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [MarlinFirmware/Marlin#13801]
when trying to migrate python 2 -> 3

[upload_extra_script.py](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_LPC1768/upload_extra_script.py) breaks build

https://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html#the-print-function

due to
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/platformio.ini#L162

```
File "/home/work/source/git/Marlin/Marlin/src/HAL/HAL_LPC1768/upload_extra_script.py", line 16
print '\nUnable to find destination disk (' + e + ')\n' \
^
SyntaxError: invalid syntax
========================== [ERROR] Took 2.00 seconds ==========================
```

**Comment by p3p** [comment]
Last time I checked PlatformIO didn't support Python 3 so this wasn't a problem, I see it still doesn't officially (according to the install guide) but they are working towards it, anyway fixing that error isn't a problem just by using `from __future__ import print_function` and moving to Python 3 print syntax,

**Comment by Andrei-Pozolotin** [comment]
pio 4.0.0 works fine on py3 when not using pio-ide
https://github.com/platformio/platformio-core/issues/895

**Comment by p3p** [comment]
Should be fixed now, tested with PlatformIO 4.0.0a10 on linux in a python 3 virtual env.

**Comment by Andrei-Pozolotin** [comment]
1. works, thank you
2. perhaps should keep this open for the rest of `*.py` migration

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by boelle** [comment]
closing this one as #13931 did fix the issue, can always reopen if its not the case

**Comment by Koby88** [comment]
Hi i hawe this problem like Andrei:
```
File "/home/work/source/git/Marlin/Marlin/src/HAL/HAL_LPC1768/upload_extra_script.py", line 16
print '\nUnable to find destination disk (' + e + ')\n' \
^
SyntaxError: invalid syntax
```
I m not a programmer or something like that im just regular guy truing to upload firmware to 3d printer, can you pls tell me what is sollution ?

**Comment by thinkyhead** [comment]
I barely know any Python, but according to Google either this…
```py
def print_error(e):
    print('\nUnable to find destination disk (', e, ')\n' \
          'Please select it in platformio.ini using the upload_port keyword ' \
          '(https://docs.platformio.org/en/latest/projectconf/section_env_upload.html) ' \
          'or copy the firmware (.pio/build/', env.get('PIOENV'), '/firmware.bin) manually to the appropriate disk\n')
```
…or maybe this…
```py
def print_error(e):
    print('\nUnable to find destination disk (%s)\n' \
          'Please select it in platformio.ini using the upload_port keyword ' \
          '(https://docs.platformio.org/en/latest/projectconf/section_env_upload.html) ' \
          'or copy the firmware (.pio/build/%s/firmware.bin) manually to the appropriate disk\n' \
          % (e, env.get('PIOENV')))
```

**Comment by Koby88** [comment]
I tried that but with no luck...

**Comment by thinkyhead** [comment]
‪Several resources are at your disposal.‬

‪- http://marlinfw.org‬
‪- http://forums.reprap.org/list.php?415‬
‪- https://discuss.toms3d.org/‬
‪- https://www.facebook.com/groups/1049718498464482/‬
‪- https://www.facebook.com/groups/3Dtechtalk/‬
‪- https://www.youtube.com/results?search_query=marlin+configuration‬
‪- https://discord.gg/n5NJ59y‬
