### ISSUE TITLE
[BUG] Compile error since commit "Update do_select_screen for general use (#13800)"

### ISSUE THREAD

**Issue by Patag** [MarlinFirmware/Marlin#13816]
### Description
Compile error since commit "Update do_select_screen for general use (#13800)" when menu "Services" is activated.
Observed in Arduino/AVR and Atom/PlateformiO/LPC1768 environements.
 
### Steps to Reproduce
1. Enable Print counter in Configuration.h
#define PRINTCOUNTER

2. Enable  Services (at least one) in Configuration_adv.h
 #define SERVICE_NAME_1      "Service S"
  #define SERVICE_INTERVAL_1  100 // print hours

3. Compile
**Expected behavior:** [What you expect to happen]
Compilation OK
**Actual behavior:** [What actually happens]
Compilation error
Marlin\src\lcd\menu\menu_service.cpp: In lambda function:
Marlin\src\lcd\menu\menu_service.cpp:40:44: error: 'index' is not captured

**Comment by sinus23** [comment]
Same here, if Service disable but not exploded additionally deactivated, although the function is deactivated, also the error

**Comment by ArtieH** [comment]
Same here.
PRINTCOUNTER is activated.
Activating any of the service Interval Watchdogs causes the compile error "error: 'index' is not captured"
Compiling with Atom/PlatformIO for LCP1768 Re-Arm.

Marlin\src\lcd\menu\menu_service.cpp: In lambda function:
Marlin\src\lcd\menu\menu_service.cpp:40:44: error: 'index' is not captured
print_job_timer.resetServiceInterval(index);
^~~~~

Marlin\src\lcd\menu\menu_service.cpp:39:6: note: the lambda has no capture-default
[]{
^
Marlin\src\lcd\menu\menu_service.cpp:34:37: note: 'const int index' declared here
inline void _menu_service(const int index, PGM_P const name) {
~~~~~~~~~~^~~~~
*** [.pioenvs\LPC1768\src\src\lcd\menu\menu_service.cpp.o] Error 1
