### ISSUE TITLE
[FR] Option to bypass thermistor lookup tables with sensor specs

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#13833]
Nice to have the option to specify thermistor parameters rather than have to use/create lookup tables.

So we could specify ..

**25C resistor value**
**Beta value**
**Pull-up resistor value**

**Comment by SJ-Innovation** [comment]
With modern STM32 processors this could be a valid approach due to the larger RAM and flash available, we could generate the table at runtime. For AVR and smaller controllers though a table saves on RAM usage as it is saved in flash by the compiler.

**Comment by ghost** [comment]
No no, you just use the formula directly, no table needed, no ram for a table needed.

// user defined parameters
#define NTC_SERIES_RESISTOR_OHMS  4700        // ntc pull-up resistor
#define NTC_RESISTANCE_25C_OHMS  100000   // ntc resistance at 25C
#define NTC_BETA                               3950        // ntc beta value

// fixed parameters
#define NTC_NOMINAL_TEMPERATURE     25
#define NTC_MAX_ADC                             1023
#define NTC_ABS_ZER0                              273.15f

float adc_value = averaged_adc_sample;
// prevent divide-by-zero
adc_value = (adc_value < 0.0001f) ? 0.0001f : (adc_value > NTC_MAX_ADC - 0.0001f) ? NTC_MAX_ADC - 0.0001f : adc_value;
float ntc_resistance = (float)(NTC_SERIES_RESISTOR_OHMS) / (((float)NTC_MAX_ADC / adc_value) - 1);
float steinhart = ntc_resistance * (1.0f / (NTC_RESISTANCE_25C_OHMS));
steinhart = logf(steinhart);
steinhart *= 1.0f / (NTC_BETA);
steinhart += 1.0f / (NTC_NOMINAL_TEMPERATURE + NTC_ABS_ZER0);
steinhart = 1.0f / steinhart;
float deg_c = steinhart - NTC_ABS_ZER0;

**Comment by doggyfan** [comment]
For the PID temperature loop to maintain correct temperature, you don't need to operate in direct deg C units, you can optimize that by using raw values, so no need to go through all the calculation.

You only really need to do the full formula when you want too tell the user the temp in degrees C.

You'd get rid of all that CPU flash usage due to all the look-up tables, that's assuming you did away with the tables all together (no reason not too). Really not sure why you have the tables ??

**Comment by psavva** [comment]
Why don't you do a pull request and see where it gets?

**Comment by ghost** [comment]
@psavva The code needs additions for that, I need to go more indepth into the Marlin code for that, which I am doing bit by bit, so will take time.

But yes, I will once I'm able.

**Comment by Idorobots** [comment]
Sounds like a nice new temp sensor type with some Configuration_adv.h setting for it.

**Comment by AnHardt** [comment]
Please don't confuse the Steinhart-Hart equation with the calculation where beta is used.

PID temperature control will not work with a exponentially distorted temperature (raw) signal.

**Comment by ghost** [comment]
Yes you're right of cause, the Steinhart-Hart equation is a little more involved (2 part).

Though the simpler log method is totally usable here.

**Comment by ghost** [comment]
arrgghh git .. long time in life but not using git.

I use TortoiseGit in windows 7 and I'm wondering how best to go about doing a pull request for Marlin ?

I've updated my Marlin code files on my PC in the Marlin git directory I have, so just need to do what's desired by the Marlin team .. whatever that might be ?

I presume I do a **push** to upload the code additions/changes, then create/add some comments about it in the **push request** section on this git site ?

**Comment by gloomyandy** [comment]
You should create a new branch based on the very latest 2.0.x code, then make only the changes needed for the pull request to that branch (so do not include any config files that are specific to your machine). You then need to push those changes to github and after doing that create a pull request. 

See here: http://marlinfw.org/docs/development/getting_started_pull_requests.html for details.

**Comment by ghost** [comment]
Thank you @gloomyandy

Tried to do a **push** but it says permission denied to me (after entering my username and password in TortoiseGit) ?

**Comment by p3p** [comment]
You missed 2 very important steps and are trying to push changes directly into Marlin, so .. probably a good thing you get permission denied ;)

From the guide start with `Set up GitHub, Fork, and Clone` and then continue at `Make a feature branch`

**Comment by ghost** [comment]
Sorry about that p3p. Think I've got it now, hopefully.

[wipes forehead}

**Comment by ghost** [comment]
ssshhh..eee, the pull request doesn't look like it should look like ?

Gone to the wrong branch :(

**Comment by p3p** [comment]
nearly there, you targeted the wrong branch (1.1.x) you need to target bugfix-2.0.x, you can change the target with the edit button at the top.

**Comment by ghost** [comment]
I blame the tablets ;)

you're a life saver p3p.

#13888
