### ISSUE TITLE
Manual Mesh Bed Leveling is not being used

### ISSUE THREAD

**Issue by DanS2D** [MarlinFirmware/Marlin#13830]
- Marlin 1.1.9
- Printer: Ender 3
- Slicer: Cura
- Using automatic Restore Mesh Leveling define. Have also tried putting a M420 S1 in my start gcode to no avail.

I've enabled Manual Mesh bed leveling via:

`#define MESH_BED_LEVELING `
`#define RESTORE_LEVELING_AFTER_G28` 
`#define GRID_MAX_POINTS_X 5`
`#define LCD_BED_LEVELING`

And define the points via the printers LCD. 

Response from M420 V1:

`Recv: Z offset: 0.00000`
`Recv: Measured points:`
`Recv:         0        1        2        3        4`
`Recv:  0 +0.09000 +0.11000 +0.20000 +0.25000 +0.30500`
`Recv:  1 +0.02500 +0.03500 +0.09000 +0.17500 +0.22000`
`Recv:  2 +0.01000 +0.04000 +0.06500 +0.09500 +0.18000`
`Recv:  3 +0.07500 +0.07500 +0.03500 +0.02000 +0.03500`
`Recv:  4 +0.19000 +0.09500 +0.06500 +0.09500 +0.08000`
`Recv: `
`Recv: echo:Bed Leveling On`
`Recv: echo:Fade Height 1.00`

When the print starts, the nozzle is roughly 0.2mm away from the bed. Removing all custom start gcode doesn't resolve the issue either.

I've been fighting this problem, trying to find a solution now for over a week now and have run out of things to try, that I've found via google/reddit etc. I didn't want to ask here, but you're my last hope.

What am I doing wrong?
Thank you

**Comment by reloxx13** [comment]
if u move down Z after homeing with the lcd to 0, is it on the bed?

**Comment by DanS2D** [comment]
> if u move down Z after homeing with the lcd to 0, is it on the bed?

It's slightly below it. By roughly 0.05mm.

I just used M42 I0 J0 (and so on) to move the extruder to to saved mesh points, to verify that they were valid, and on each one it moved to exactly where I positioned it earlier, when defining the mesh points.

As soon as a print starts though, it's like they never existed.

Here's the first section of the gcode cura is outputting for a raspberry pi case (so you can see more detail): https://gist.github.com/Revolt64/3aaff402cd6154016263ff679f3240cd

**Comment by reloxx13** [comment]
`M402 S1 ; restore bed level`

its m420 s1

u wrote m402 s1 in ur startcode.
   
   

> Stow the bed probe. The Z axis may raise up to make room for the probe to stow.   

http://marlinfw.org/docs/gcode/M402.html

http://marlinfw.org/docs/gcode/M420.html

**Comment by DanS2D** [comment]
> `M402 S1 ; restore bed level`
> 
> its m420 s1
> 
> u wrote m402 s1 in ur startcode.
> 
> > Stow the bed probe. The Z axis may raise up to make room for the probe to stow.
> 
> http://marlinfw.org/docs/gcode/M402.html
> 
> http://marlinfw.org/docs/gcode/M420.html

Stupid typo. I must have dyslexia. 
Updated the gist with the fixed gcode. It still exhibits the same issue. I've been trying this for days now (not with the typo, that was introduced whilst messing with the start gcode today it seems).

Any other ideas? I'm watching the Z position on the LCD screen whilst it's moving along the first layer, and there's no micro-stepping being performed (the z stepper isn't making micro adjustments either).

**Comment by DanS2D** [comment]
Figured it out, at long last.

Changing the command to specify which mesh to use finally fixed the issue!

M420 L0 S1
