### ISSUE TITLE
please, clean up double argument

### ISSUE THREAD

**Issue by Ludy87** [MarlinFirmware/Marlin#13842]
@Bob-the-Kuhn please, clean up all

```Configuration_adv.h```

```c++
  // Frivolous Game Options
  //#define MARLIN_BRICKOUT
  //#define MARLIN_INVADERS
  //#define MARLIN_SNAKE
```

https://github.com/MarlinFirmware/Marlin/blob/e43afb1a58c7272e5eb5c335ae129ee35e16f133/Marlin/Configuration_adv.h#L992-L1002

**Comment by Roxy-3D** [comment]
Done...

**Comment by Ludy87** [comment]
You forgot the other file 😅

**Comment by Roxy-3D** [comment]
Is there another Configuration_adv.h file that has two sets of 'Frivolous Game Options' ?
If so...    I didn't find it.

**Comment by Ludy87** [comment]
Yes, here are two examples

https://github.com/MarlinFirmware/Marlin/blob/142c8e2fed810c785fce1afadd0949025f178ad7/config/default/Configuration_adv.h#L995-L1003

https://github.com/MarlinFirmware/Marlin/blob/142c8e2fed810c785fce1afadd0949025f178ad7/config/examples/3DFabXYZ/Migbot/Configuration_adv.h#L995-L1003

and any files from config in the another directories

**Comment by Roxy-3D** [comment]
Oh!   So all of the Configuration_adv.h files have this issue?    OK, I'll get that patched in the next few days.

Thank you for the heads up.

**Comment by Ludy87** [comment]
I am creating a PR myself, if you want I can fix it right away.

**Comment by Roxy-3D** [comment]
OK!   Great...    

Thank You!

**Comment by Ludy87** [comment]
i close here, thanks for your work
