### ISSUE TITLE
[BUG] IDEX full control: Wrong nozzle z position after tool change

### ISSUE THREAD

**Issue by phuxman** [MarlinFirmware/Marlin#13875]
### Description

Wrong nozzle z position after a tool change in IDEX full control mode. The position shown on the display does not represent the real position.

Done on Vivendino TREX 3.

### Steps to Reproduce
Do by terminal (all movements absolute):
- Heat + Home everything
- Raise z (safe movement)

Then repeat for extruders T0/T1 alternating
- Switch to extruder (T0/T1)
- Move to defined position (G1 X200)
- Lower by Z0.1 steps until feeler gauge 0.1 is fitting good (G1 Z0.5,G1 Z0.4,...) -> Read Z on display
- Raise z (safe movement) (G1 Z10)
- Move extruder to safe position (G1 X-45/G1 X445)

**Expected behavior:** 

- Static value (ideally Z0.1)

**Actual behavior:** 

Increasing value after every tool change

T0->Z0.1 
T1->Z0.35
T0->Z0.4
T1->Z0.6
T0->Z0.65
T1->Z0.8
T0->Z0.8
T1->Z1.1
T0->Z1.4
T1->Z1.65
T0->Z1.7

#### Additional Information

Tool offsets:
- Probe (BLTouch 3) Z offset: -1.35
- Second tool Z offset: -0.05

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3135998/Configuration.zip)

**Comment by phuxman** [comment]
Needless to say: This behavior leads to the nozzles grinding deeper and deeper in the bed/material during print after every tool change.

**Comment by InsanityAutomation** [comment]
Can you test with #14117

**Comment by phuxman** [comment]
Hi. I tested it with the method described and the issue seems solved. The z position stays correct after tool changes. 

Should I close the issue?

**Comment by InsanityAutomation** [comment]
Go ahead, although technically it's not completely closed until @thinkyhead clicks the merge button

**Comment by phuxman** [comment]
Thank you very much for your efforts.

**Comment by phuxman** [comment]
I tried to print in idex full control mode and there is still some offset off after tool changes. It is now way smaller than before but after about 10 tool changes it becomes visible. I will provide further information on how to reproduce.

Is there something specific I can try/monitor to help identify the problem?

**Comment by InsanityAutomation** [comment]
I'll go over your config files tonight and see what you have atm. Mobile can't pull in the zip... Are you using any bed leveling?

**Comment by InsanityAutomation** [comment]
I know that config!!! Its mine! lol This issue was also reported some time ago by another user. Ive just been getting back around to looking into things with full control mode so hopefully ill find it soon. It appears to be an issue with adjustments applied by bed leveling as travel across the mesh is no longer linear.

**Comment by phuxman** [comment]
I am using ubl bed leveling. 

I think it is a small offset error which accumulates during tool changes. Was also thinking about the bed correction mesh data.

As soon the current print is ready I will start a idex full control print with ubl disabled.

Yes its yours. :P

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
