### ISSUE TITLE
[BUG] Changing EXTRUDERS changes layout of EEPROM

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#13889]
At the moment, it looks like the number of EXTRUDERS changes the layout of the EEPROM. This causes problems with printers such as our with interchangable toolheads.

Would it make sense to reserve an amount of space independent of number of extruders? At the least, the stuff related to EXTRUDERS would need to be moved to the end of the EEPROM so it doesn't cause everything else to shift.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by boelle** [comment]
@marcio-ao is the issue still there?

**Comment by marcio-ao** [comment]
@boelle: Yes.

**Comment by boelle** [comment]
> Would it make sense to reserve an amount of space independent of number of extruders?

to a non programmer like me the answer would be yes

**Comment by InsanityAutomation** [comment]
Not necissarily, eeprom space is finite and certain things that should rarely change on a machine should not hold space for everything.

I lean towards the latter option, tucking it either in static spacing in the 100 pre-config bytes or the tail end if there is space while watching mesh data which is at the end now since it utilizes the remainder for multiple UBL slots.

**Comment by boelle** [comment]
@thinkyhead @shitcreek time to have a look here before the issue gets lost and not fixed

**Comment by boelle** [comment]
@thinkyhead @shitcreek time to have a look here before the issue gets lost and not fixed

**Comment by boelle** [comment]
@thinkyhead @shitcreek time to have a look here before the issue gets lost and not fixed

**Comment by boelle** [comment]
i guess this one still needs to be worked on?

**Comment by boelle** [comment]
what can we do to fix this one?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
