### ISSUE TITLE
BLTOUCH firmware causes bed to mash into my nozzle

### ISSUE THREAD

**Issue by Aurawin** [MarlinFirmware/Marlin#13898]
### Description

BLTOUCH firmware configuration causes the sensor to mash the bed up into my nozzle.

### Steps to Reproduce
Board: BIQU Tango V1.0 based on Rumba
Firmware: bugfix-2.0
TRONXY-X5S 
BLTouch V3

#define ENDSTOPPULLUPS
#define USE_ZMIN_PLUG
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
 /**
   * BLTouch V3.0 and newer smart series
   * For genuine BLTouch 3.0 sensors. Clones may be confused by 3.0 command angles. YMMV.
   * If the pin trigger is not detected, first try swapping the black and white wires then toggle this.
   */

The following behaviours are consistant i.e. I have these symtoms each time I perform hardware/firmware settings iterations 1,2,3

1.) Behavior with:

Wired signal (white) to signal pin to z-min sig and (black) wire to grnd

	M280 P0 S120 works as expected running self test
	M280 P0 S160 works as expected releasing test and pulling up pin

	G28 X,Y home, BLT pin lowers and raises red light solid but ERROR:STOP called because of BLTouch (Red screen on Repetier) and Endstops Z on the display

	M43 S  : Servo probe test
		18:17:12.613 : .  using index:  0
		18:17:12.613 : .  deploy angle: 10
		18:17:12.614 : .  stow angle:   90
		18:17:12.615 : . probe uses Z_MIN pin: 33
		18:17:12.616 : . uses Z_MIN_ENDSTOP_INVERTING (ignores Z_MIN_PROBE_ENDSTOP_INVERTING)
		18:17:12.617 : . Z_MIN_ENDSTOP_INVERTING: false
		18:17:12.617 : . deploy & stow 4 times
		18:17:17.069 : WARNING - INVERTING setting probably backwards
		18:17:17.625 : please trigger probe
		18:18:53.441 : BLTouch compatible probe detected - pulse width (+/- 4mS): 12

2.) Behavior with:

Wired signal (black) to signal pin to grnd and (white)k wire to grnd

	M280 P0 S120 works as expected running self test
	M280 P0 S160 works as expected releasing test and pulling up pin

	G28 X,Y home, BLT pin lowers and raises and lowers no light and z raises right into the bed.

	M43 S  yields:
	
		18:24:09.132 : Servo probe test
		18:24:09.132 : .  using index:  0
		18:24:09.133 : .  deploy angle: 10
		18:24:09.133 : .  stow angle:   90
		18:24:09.134 : . probe uses Z_MIN pin: 33
		18:24:09.135 : . uses Z_MIN_ENDSTOP_INVERTING (ignores Z_MIN_PROBE_ENDSTOP_INVERTING)
		18:24:09.136 : . Z_MIN_ENDSTOP_INVERTING: false
		18:24:09.136 : . deploy & stow 4 times
		18:24:14.145 : please trigger probe
		
		Sensor repeatedly requests trigger BLT pin - manually trigger probe a few times and end with the following error:

		18:24:45.154 : trigger not detected
 

 3.) Behavior with:

	Wired signal (white) to signal pin to z-min sig and (black) wire to grnd
 
 Since Conditions_LCD.h includes the following code:

	Lines 472-478 removed
	   // Always disable probe pin inverting for BLTouch
	  #undef Z_MIN_PROBE_ENDSTOP_INVERTING
	  #define Z_MIN_PROBE_ENDSTOP_INVERTING false
	  #if ENABLED(Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN)
	    #undef Z_MIN_ENDSTOP_INVERTING
	    #define Z_MIN_ENDSTOP_INVERTING false
	  #endif

	  I removed the forced overriding of the Z_MIN_PROBE_ENDSTOP_INVERTING

	  #define Z_MIN_ENDSTOP_INVERTING true 
	  #define Z_MIN_PROBE_ENDSTOP_INVERTING true

	  Reboot

	  M43 S  yields:
		19:24:31.129 : Servo probe test
		19:24:31.129 : .  using index:  0
		19:24:31.129 : .  deploy angle: 10
		19:24:31.130 : .  stow angle:   90
		19:24:31.130 : . probe uses Z_MIN pin: 33
		19:24:31.132 : . uses Z_MIN_ENDSTOP_INVERTING (ignores Z_MIN_PROBE_ENDSTOP_INVERTING)
		19:24:31.133 : . Z_MIN_ENDSTOP_INVERTING: true
		19:24:31.133 : . deploy & stow 4 times
		19:24:36.141 : please trigger probe
		19:24:36.880 : BLTouch compatible probe detected - pulse width (+/- 4mS): 12

	    ---->>>  Looking great... Test no signal errors this time

	  G28 yields:

	  	X,Y,Z all homed properly.

	 
	 With the current state of Conditions_LCD.h this firmware is causing my bed to ram my nozzle.

	 Please fix

**Comment by Roxy-3D** [comment]
Have you reviewed the current issue list?   Is it possible this issue is already being worked on and addressed?   

https://github.com/MarlinFirmware/Marlin/issues/13858

https://github.com/MarlinFirmware/Marlin/pull/13814

https://github.com/MarlinFirmware/Marlin/pull/13841

(And that is not a full list of BL-Touch v3.0 threads....   But probably you will get your answers and code fixes from those 3 threads.)

With that said....   You did do a very good job of giving us the information we needed to help you!   I wish all issues had that type of information available!!!   Thanks!
