### ISSUE TITLE
[FR] (feature request title)

### ISSUE THREAD

**Issue by ats3788** [MarlinFirmware/Marlin#13914]

**Comment by ats3788** [comment]
Hello
Is it possible to handle a Fan  in the PCB Case with Marlin ????
I thought to use a Port on the Servo OutPut. I bought a MosFet Board to handel the 12 V for the Fan

**Comment by teemuatlut** [comment]
Configuration_adv.h
USE_CONTROLLER_FAN

**Comment by boelle** [comment]
will close this one as the feature is allready there
