### ISSUE TITLE
[BUG][bugfix-2.0.x] PROBING_FANS_OFF compile error

### ISSUE THREAD

**Issue by Alissonverd** [MarlinFirmware/Marlin#13920]
### Description

Compiler produce an error when PROBING_FANS_OFF is enabled.

### Steps to Reproduce

1. Download the last code from github (bugfix-2.0.x)
2. Compile with and without PROBING_FANS_OFF.

#### Additional Information

> c:\[...]\sketch\src\core\macros.h:188:36: note: in definition of macro 'ZERO'
>  #define ZERO(a)             memset(a,0,sizeof(a))
> 
> c:\[...]\src\gcode\control\M80_M81.cpp:100:27: error: 'class Temperature' has no member named 'paused_fan_speed'
>        ZERO(thermalManager.paused_fan_speed);
> 
> c:\[...]\src\core\macros.h:188:47: note: in definition of macro 'ZERO'
>  #define ZERO(a)             memset(a,0,sizeof(a))

No need modification on configuration files, only enable PROBING_FANS_OFF.

An older version (date 2018.12.30) dont appear this issue.

Arduino IDE 1.9
Windows 10 Pro

**Comment by Vertabreak** [comment]
In file included from /tmp/arduino_build_373670/sketch/src/gcode/control/../../inc/MarlinConfigPre.h:32:0,
                 from /tmp/arduino_build_373670/sketch/src/gcode/control/../../inc/MarlinConfig.h:28,
                 from /tmp/arduino_build_373670/sketch/src/gcode/control/../gcode.h:267,
                 from /tmp/arduino_build_373670/sketch/src/gcode/control/M80_M81.cpp:23:
/tmp/arduino_build_373670/sketch/src/gcode/control/M80_M81.cpp: In static member function 'static void GcodeSuite::M81()':
/tmp/arduino_build_373670/sketch/src/gcode/control/M80_M81.cpp:100:27: error: 'class Temperature' has no member named 'paused_fan_speed'
       ZERO(thermalManager.paused_fan_speed);
                           ^
/tmp/arduino_build_373670/sketch/src/gcode/control/../../inc/../core/macros.h:188:36: note: in definition of macro 'ZERO'
 #define ZERO(a)             memset(a,0,sizeof(a))
                                    ^
/tmp/arduino_build_373670/sketch/src/gcode/control/M80_M81.cpp:100:27: error: 'class Temperature' has no member named 'paused_fan_speed'
       ZERO(thermalManager.paused_fan_speed);
                           ^
/tmp/arduino_build_373670/sketch/src/gcode/control/../../inc/../core/macros.h:188:47: note: in definition of macro 'ZERO'
 #define ZERO(a)             memset(a,0,sizeof(a))
                                               ^

**Comment by Vertabreak** [comment]
this compile error started after https://github.com/MarlinFirmware/Marlin/commit/2f32a6612d0155fd01d15497205bb63e68ae1e7a commit.

**Comment by Vertabreak** [comment]
#define ADVANCED_PAUSE_FANS_PAUSE being enabled by it self also produces this error.

/tmp/arduino_build_75750/sketch/src/module/temperature.cpp: In member function 'void Temperature::set_fans_paused(bool)':
/tmp/arduino_build_75750/sketch/src/module/temperature.cpp:185:16: error: 'fans_paused' was not declared in this scope
       if (p != fans_paused) {
                ^

**Comment by Ludy87** [comment]
> #define ADVANCED_PAUSE_FANS_PAUSE being enabled by it self also produces this error.
> 
> /tmp/arduino_build_75750/sketch/src/module/temperature.cpp: In member function 'void Temperature::set_fans_paused(bool)':
> /tmp/arduino_build_75750/sketch/src/module/temperature.cpp:185:16: error: 'fans_paused' was not declared in this scope
> if (p != fans_paused) {
> ^

@thinkyhead 

does it make sense to change that?

https://github.com/MarlinFirmware/Marlin/blob/9853331b34ef6fd214a8f1fbc315e722c90b7341/Marlin/src/module/temperature.h#L382

to 

```c++
#if EITHER(PROBING_FANS_OFF, ADVANCED_PAUSE_FANS_PAUSE)
```

https://github.com/MarlinFirmware/Marlin/blob/9853331b34ef6fd214a8f1fbc315e722c90b7341/Marlin/src/module/temperature.cpp#L141

to

```c++
#if EITHER(PROBING_FANS_OFF, ADVANCED_PAUSE_FANS_PAUSE)
```

**Comment by Ludy87** [comment]
https://github.com/MarlinFirmware/Marlin/blob/9853331b34ef6fd214a8f1fbc315e722c90b7341/Marlin/src/gcode/control/M80_M81.cpp#L100

to
```c++
      ZERO(thermalManager.saved_fan_speed);
```
---

https://github.com/MarlinFirmware/Marlin/blob/9853331b34ef6fd214a8f1fbc315e722c90b7341/Marlin/src/module/temperature.cpp#L141-L143

to

```c++
  #if EITHER(PROBING_FANS_OFF, ADVANCED_PAUSE_FANS_PAUSE)
    bool Temperature::fans_paused; // = false;
    uint8_t Temperature::saved_fan_speed[FAN_COUNT]; // = { 0 }
  #endif
```
----

delete line
https://github.com/MarlinFirmware/Marlin/blob/9853331b34ef6fd214a8f1fbc315e722c90b7341/Marlin/src/module/temperature.cpp#L184

---

https://github.com/MarlinFirmware/Marlin/blob/9853331b34ef6fd214a8f1fbc315e722c90b7341/Marlin/src/module/temperature.h#L382-L384

to

```c++
      #if EITHER(PROBING_FANS_OFF, ADVANCED_PAUSE_FANS_PAUSE)
        static bool fans_paused;
        static uint8_t saved_fan_speed[FAN_COUNT];
      #endif
```
