### ISSUE TITLE
[FR] Progress for G29

### ISSUE THREAD

**Issue by guestisp** [MarlinFirmware/Marlin#13934]
During a G29, would be usefull to show, on LCD (and report via USB, for octoprint or similiar) the completed probes and the remaining ones, like:

`Calibrating 1/10`

Something similiar to the Original Prusa autocalibration.
Very useful with huge meshes and slow probe speed. My mesh is built with 10 (thinking to increase to 12) points, 3 probes and takes more than 1 hour. :)

Currently a generic "Doing G29" is shown, something more usefull like a progress indicator would be nice and useful

**Comment by InsanityAutomation** [comment]
This has actually been on my list for awhile but low priority. Itll get done.

**Comment by guestisp** [comment]
Thank you. Please also send the progress via USB, so that could be catched by octoprint or similiar

**Comment by InsanityAutomation** [comment]
Good thought, would need a plugin to display outside the terminal window though. If it's there I'm sure someone will do it!

**Comment by guestisp** [comment]
Exactly. I've tried to see the best place to add the progress. Probably in `unified_bed_leveling::probe_entire_mesh` by using `count` as the total number of points to probe

**Comment by guestisp** [comment]
I did a small progress on this, i'm able to update the terminal, but i'm having trouble in writing a string LCD.
Any advice ?

**Comment by InsanityAutomation** [comment]
Call lcd_setstatus(STRING)

Needs to handle bilinear and mesh leveling as well, so itll be more than just ubl. Probably tag the same lines I added onMeshUpdate for extui not long ago.

**Comment by guestisp** [comment]
I've made a PR. This works for new mesh build, 3-points mesh tilting and multiple points mesh tilt (G29 J)

Isn't the bilinear dismissed by UBL ?

**Comment by Roxy-3D** [comment]
> Needs to handle bilinear and mesh leveling as well, so itll be more than just ubl. Probably tag the same lines I added onMeshUpdate for extui not long ago.

That would be the best way to do it.   But it does increase the effort.   

A while ago we changed the mesh dimensions and mesh storage arrays to use consistent names so we could start trying to collapse the common code.    By doing this, we were able to get G26 to work for both UBL and Bi-Linear.    And the G26 code can be selectively turned on or off.

I would suggest this is a good opportunity to do something similar.   If the LCD Panel is used to generate a mesh...   It really shouldn't need to know if it is generating a UBL mesh or a Bi-Linear mesh.    And if this is true...   It ought to be able to draw the printer's bed and start populating mesh points that have been taken on the LCD Panel.   (Incidentally...   This should also be possible on the 20x4 LCD Panels using the special characters.   The Mesh Point editing on 20x4 screens does this currently.)

It would be a general case solution.   And a little more work than doing it just for UBL (or Bi-Linear), but it would be good to have common code for both bed leveling systems that can be turned off if the user would prefer to spend the program memory on something else.

> I've made a PR. This works for new mesh build, 3-points mesh tilting and multiple points mesh tilt (G29 J)

> Isn't the bilinear dismissed by UBL ?

No...   Bi-Linear results in much less program memory being consumed.   So for some people, that is a better solution.   Also, Bi-Linear does the actual Z-Height correction calculations differently.   So some people might prefer its approach.

**Comment by guestisp** [comment]
> No... Bi-Linear results in much less program memory being consumed. So for some people, that is a better solution.

Understood. So I can apply my PR to handle the bilinear as well, but ..... can you point me to the code :D ? in /feature/bedlevel I don't see the bilinear but only ubl/mbl/abl

> Also, Bi-Linear does the actual Z-Height correction calculations differently. 

Any example of what would differ ? We are OT here, but i'm fighting agains some strange issue that could be related to a wrong Z height calculation (like some layer thicker than others)

**Comment by Roxy-3D** [comment]
The Bi-Linear correction is done in the Planner Scheduling Code.   Roughly 1400 lines into the Planner.cpp module.

**Comment by guestisp** [comment]
@thinkyhead thank you for merging my PR
As there is a suggestion to not use more than 15 points per axis, won't be better to use uint8 instead uint16 for grid size variable? The maximum storable number would be 225 (15*15) that would fit in a 8bit int

**Comment by InsanityAutomation** [comment]
@boelle @shitcreek The initial PR was done and I finished extending it for bilinear and linear as well. This can be closed.
