### ISSUE TITLE
[BUG] Extruder moves lock firmware (SKR v1.3, A4988 and TMC2208)

### ISSUE THREAD

**Issue by PeteBurgess** [MarlinFirmware/Marlin#13932]
### Description

No extrusion and firmware lockup on manual extruder move. 

Board is an SKR v1.3 with TMC2208s on X and Y, and A4988 on E and Z. I've seen this before but it's when I've made a complete hash of the config. I usually just create a new clean one and go from there, but this time I'm stumped.

### Steps to Reproduce

- Bring nozzle to temperature
- Move axis menu
- Attempt to extrude any amount of filament

**Expected behavior:** 
Filament extruded

**Actual behavior:** 
No extrusion and firmware locks up (can't make navigate menus etc.)

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3152888/configuration.zip)

**Comment by reloxx13** [comment]
sounds like this #13213

try disabling ADAPTIVE_STEP_SMOOTHING and try again.

but the skr should have enough resources.

**Comment by PeteBurgess** [comment]
Potentially dumb question but I really don't understand the internals. Could buffer size affect this in any way ? The SKR's got plenty of resources and in order to try and troubleshoot I've removed Linear Advance and filament change options to free up memory.

I did fiddle with the buffer size though. Come to think of it, I've got onboard SD enabled too, which I didn't have turned on before.

**Comment by LastDragon-ru** [comment]
Extruder with TMC2208 doesn't work in StealthChop (there are several bugs about this) :( The good news it will work in SpreadCycle (but #13092) and/or Hybrid mode (`#define HYBRID_THRESHOLD`). In any case, TMC2208 also required:

```
#define MINIMUM_STEPPER_PULSE 1 // or 2 (only this required)
```

Non-extruder axes with TMC2208 also can stops if acceleration/speed too high -> so I would recommend trying to enable hybrid mode :)

**Comment by LastDragon-ru** [comment]
> Could buffer size affect this in any way ?

Yup (eg my delta on msk sbase doesn't work with value higher `BLOCK_BUFFER_SIZE 32`). Also, you can see Memory Usage after compiling.

**Comment by PeteBurgess** [comment]
Extruder's on an A4988 so don't have to worry about hybrid mode. 

@reloxx13 Adaptive Step Smoothing didn't make any difference. Thanks for the suggestion though.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
