### ISSUE TITLE
[BUG] (height error 327.67)

### ISSUE THREAD

**Issue by Goodfeat** [MarlinFirmware/Marlin#13945]
Hello, I found a bug in the marlin 2.0 firmware
 My printer - Delta, arduino DUE

The height in the UI interface does not match the real value.
The maximum height of my printer is 550mm.
Path errors: Ui menu-> configuration -> delta calibration -> delta setting-> height (+550) -> Height: 327.67 ???
I use REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

In the Ui interface, when adjusting a value above 327.67, the firmware does not allow installation.
Most likely this is due to the restriction of the int_16 data type. The values ​​of the limit height coincides with the maximum limit for int16 - 32,768

![IMG_20190508_192807](https://user-images.githubusercontent.com/44455128/57364950-7fea4180-71c7-11e9-81e9-8a6ff3e8c9f9.jpg)

**Comment by InsanityAutomation** [comment]
Can you test with todays bugfix branch? A PR was just merged that may fix this. If not we may need to take a closer look. If this is now working, please go ahead and close the issue. Thanks.

**Comment by Goodfeat** [comment]
Fixed!
