### ISSUE TITLE
[BUG] Missing zip file in [ Marlin_RTOS] repo?

### ISSUE THREAD

**Issue by howroyd** [MarlinFirmware/Marlin#13952]
The readme.MD states:

> Modified FreeRTOS files are in a .ZIP file alongside the Marlin source files.

Yet I cannot seem to find these in the repo.

Am I missing something obvious?

**Comment by howroyd** [comment]
...to clarify, on the [Marlin_RTOS](https://github.com/MarlinFirmware/Marlin/tree/Marlin_RTOS) branch

**Comment by Phr3d13** [comment]
I have no experience with this branch, but I also cannot find the zip in question. I also looked through the commit history and can't find when the file disappeared (or if it ever existed).

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by howroyd** [comment]
Still no zip file.  Keen to help out with the FreeRTOS stuff (I use it at work on a STM32F4) but can't due to missing config files!

**Comment by boelle** [comment]
i dont think they even have started or completed RTOS

@thinkyhead

**Comment by howroyd** [comment]
Ok, if that's the case may I suggest putting something in the readme.md ...it's a bit confusing.

Also, still keen to help out if I can.

**Comment by boelle** [comment]
well if you can there is always bugs to be sorted out

https://github.com/MarlinFirmware/Marlin/issues?q=is%3Aissue+is%3Aopen+label%3A%22Bug%3A+Potential+%3F%22+sort%3Acreated-asc

**Comment by InsanityAutomation** [comment]
As 32 bit platforms are becoming more available, tests showed very little if any true gain with RTOS. Take a look at the complexity of a custom linux kernel linux cnc needs to maintain for it...

**Comment by howroyd** [comment]
Yes I understand. Not criticising in any way. Just suggesting that the readme might be updated to reflect this?

**Comment by InsanityAutomation** [comment]
> 
> 
> Yes I understand. Not criticising in any way. Just suggesting that the readme might be updated to reflect this?

Id agree, but im not the maintainer or a member of the core team so I dont usually mess with the general house keeping stuff :)
