### ISSUE TITLE
What is this number "16777216" (2^24) in plan_buffer_line ???

### ISSUE THREAD

**Issue by alexborro** [MarlinFirmware/Marlin#1396]
Sorry my noob question, but can some explain me this line??

block->acceleration_rate = (long)((float)block->acceleration_st \* (16777216.0 / (F_CPU / 8.0)))

I cannot realize a relationship between acceleration_rate and 2^24 (16777216).

Cheers.

Alex.

**Comment by nophead** [comment]
It appears to be just scaling to allow a 32 bit long to represent acceleration in a fixed point notation. I.e. 8 bits of integer and 24 bits of fraction. It is used here: https://github.com/MarlinFirmware/Marlin/blob/5c7e38478bbebfbbd2f36f1d6aa2dcc869609654/Marlin/stepper.cpp#L699
