### ISSUE TITLE
[FR] Full Spanish Marlin 1.1.9

### ISSUE THREAD

**Issue by el-quique** [MarlinFirmware/Marlin#13968]
### Descripción

Actualización del Idioma Español para Marlin 1.1.9

### Pasos a Seguir

1. Copiar los archivos language_es.h y language_es_utf8.h en el directorio de Marlin

2. En Configuration.h agregar las siguientes lineas:

// Preheat Constants
#define PREHEAT_1_LABEL       "PLA" // linea agregada
#define PREHEAT_1_TEMP_HOTEND 185
#define PREHEAT_1_TEMP_BED     50
#define PREHEAT_1_FAN_SPEED     0 // Value from 0 to 255

#define PREHEAT_2_LABEL       "ABS" // linea agregada
#define PREHEAT_2_TEMP_HOTEND 200
#define PREHEAT_2_TEMP_BED     90
#define PREHEAT_2_FAN_SPEED     0 // Value from 0 to 255

3. En configuration,h elegir:
#define LCD_LANGUAGE es_utf8
#define DISPLAY_CHARSET_HD44780 WESTERN
o 
#define LCD_LANGUAGE es
#define DISPLAY_CHARSET_HD44780 WESTERN

#### Archivos Adjuntos
[language_espanol-Marlin_1.1.9.zip](https://github.com/MarlinFirmware/Marlin/files/3164437/language_espanol-Marlin_1.1.9.zip)

**Comment by el-quique** [comment]
#### Description
Spanish Language Update for Marlin 1.1.9

#### Steps to follow
1. Copy the language_es.h and language_es_utf8.h files to the Marlin directory

2. In Configuration.h add the following lines:

// Preheat Constants
#define PREHEAT_1_LABEL "PLA" // line added
#define PREHEAT_1_TEMP_HOTEND 185
#define PREHEAT_1_TEMP_BED 50
#define PREHEAT_1_FAN_SPEED 0 // Value from 0 to 255

#define PREHEAT_2_LABEL "ABS" // added line
#define PREHEAT_2_TEMP_HOTEND 200
#define PREHEAT_2_TEMP_BED 90
#define PREHEAT_2_FAN_SPEED 0 // Value from 0 to 255

3. In configuration, h choose:
#define LCD_LANGUAGE es_utf8
#define DISPLAY_CHARSET_HD44780 WESTERN
or
#define LCD_LANGUAGE is
#define DISPLAY_CHARSET_HD44780 WESTERN

#### Attached files
[language_espanol-Marlin_1.1.9.zip](https://github.com/MarlinFirmware/Marlin/files/3164437/language_espanol-Marlin_1.1.9.zip)

**Comment by Ludy87** [comment]
create a PR to submit changes

**Comment by Ludy87** [comment]
You mix the 1.1.x version with 2.0.x, that's not okay.

**Comment by Ludy87** [comment]
For special characters it does not need an extra file, but
```#define THIS_LANGUAGES_SPECIAL_SYMBOLS      _UxGT("ÁáçÉéÍíÑñÓóÚúüªº¡¿")```

**Comment by marcio-ao** [comment]
It looks like there is a separate PR for Marlin 2.0.x https://github.com/MarlinFirmware/Marlin/issues/13941

**Comment by el-quique** [comment]
This adapted for Marlin 1.1.9 and work fine

**Comment by boelle** [comment]
PR's should not be submitted as an issue with a zip file

**Comment by boelle** [comment]
will close this one as its not a FR nor a BUG, i have mentioned the post to @thinkyhead so he can grab the zip file and see if they are of any use
