### ISSUE TITLE
[FR] Any way to disable cooldown when stopping print ?

### ISSUE THREAD

**Issue by WADZoQUADZ** [MarlinFirmware/Marlin#13987]
In earlier marlin versions when hitting stop print it used to remain hot. Now it 1.1.9Bf it automatically cools down. Is there a feature or can there be to disable it from cooling down?

Sometimes we have it preheated then click the wrong file then stop it or sometimes we are adjusting the first layer height and stop it . Now everytime we have to wait for it to preheat all over again.

**Comment by reloxx13** [comment]
this is supposed, safe and correct. 

if u stop a print, the printer thinks its done. there is no reason to stay hot.
would be dangerously if the user has to cooldown himself.


stop selecting the wrong files.

**Comment by WADZoQUADZ** [comment]
i think your mistaken . It has always been this way in past marlin versions. In groups theres a whole bunch of people complaining about the change. There should at least be a option. Nobody wants to preheat to have to go a preheat again 10 seconds later. Sometimes its not you thats selecting the wrong file, its a laggy display and when you click on the file it starts printing a file one down from it

**Comment by ghost** [comment]
I agree. 99% of the times I cancel a print (due to poor adhesion on the first layer) so that I can retry moments laters. At least the printer now homes XY...because having the nozzle sit on top of the print was rather annoying. Now I still have to go to Temperature and preheat menus.

**Comment by boelle** [comment]
is this a feature request or bug?

**Comment by InsanityAutomation** [comment]
@boelle it was a FR and its done.
