### ISSUE TITLE
Dual Z stepper with X leveling

### ISSUE THREAD

**Issue by Mr-trix** [MarlinFirmware/Marlin#13995]
Hello

for Dual Z, with dual Z motors and stepper more a probe,
the X or Y bed leveling can be done by the two or more lead screw.
I don t know how add this in marlin but the script is ridicoulusly simple and better than two end stop + prob
One pics is better than 1000 words, so you can check it in action on this video (on duet)

Bed levelling using multiple independent Z motors: 
https://www.youtube.com/watch?v=02QAK0j4vfw

**Comment by teemuatlut** [comment]
https://github.com/MarlinFirmware/Marlin/blob/940ff8e7c8a5919681dcd6d6e87668381010151a/Marlin/Configuration_adv.h#L530-L549

**Comment by boelle** [comment]
will close as the feature is implemented with G34
