### ISSUE TITLE
[BUG] bugfix-2.0.x- g29 la tete ne se déplace pas parellèle au lit

### ISSUE THREAD

**Issue by francobusc** [MarlinFirmware/Marlin#14002]
bonjour, 

mon problème est sur une delta diy...

G28 fonctionne , je vais bien en home ok

G33 fonctionne aussi ok

G29 ne fonctionne pas correctement .... pas bon

la tête descend touche le bed ok...puis la tête se dirige vers le 2ème point et au lieu de se déplacer parallèle au bed et bien la tête monte en se déplaçant de 20mm plus ou moins puis descend pour sonder mais est trop haut

voir vidéo : 

g29 pas bon

https://mega.nz/#!HzoEjQLL!rm3g37M9xF8tXARcU3mOqXrF7KsfAVkH66dczQzf4SI

G33 est bon

https://mega.nz/#!ayRlhCTQ!oRwFuG2UxqqOFuXkH5VCDIVTTipCK-Q_NM7mvn_-5xo

j ai tester ici

AUTO_BED_LEVELING_BILINEAR

et

AUTO_BED_LEVELING_UBL

et j ai le même souci

merci pour votre aide

[marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3171436/marlin.zip)

---

Hello,

my problem is on a delta diy ...

G28 works, I'm fine in home ok

G33 also works ok

G29 does not work properly .... not good

the head goes down and touches the bed ok ... then the head goes to the 2nd point and instead of moving parallel to the bed and the head goes up 20mm more or less then goes down to sound but is too high

see video:

g29 not good

https://mega.nz/#!HzoEjQLL!rm3g37M9xF8tXARcU3mOqXrF7KsfAVkH66dczQzf4SI

G33 is good

https://mega.nz/#!ayRlhCTQ!oRwFuG2UxqqOFuXkH5VCDIVTTipCK-Q_NM7mvn_-5xo

I tested here

AUTO_BED_LEVELING_BILINEAR

and

AUTO_BED_LEVELING_UBL

and I have the same concern

Thanks for your help

[marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3171436/marlin.zip)

**Comment by francobusc** [comment]
j ai trouvé mon souci....je suis parti sur un fichier existant tevo little monster et as de souci...je ne sais pas pourquoi....
peut etre un mauvais fichier

---

I found my concern .... I left on an existing file tevo little monster and worry ... I do not know why ....
can be a bad file

**Comment by reloxx13** [comment]
english

**Comment by Bob-the-Kuhn** [comment]
Please close this issue if your problem has been solved.

---

Veuillez fermer ce problème si votre problème a été résolu.
