### ISSUE TITLE
4 extruders+ heated bed and heated chamber

### ISSUE THREAD

**Issue by etogburn** [MarlinFirmware/Marlin#1400]
I am in the middle of a new printer design/build and would love to use marlin with the new printer as I think it is superior to Repetier, however, Repetier supports up to 6 extruders which would allow me to use 4 real extruders and a dummy one for heated chamber control on my Azteeg X3 Pro. I would love to see marlin add support for a 4th extruder and a heated chamber (utilizing the M141 gcode). I know the 4th extruder has been discussed before but I cannot find anything on heated chamber requests.

I apologize. I actually just found heated build chamber requests.

**Comment by thinkyhead** [comment]
We have the 4th extruder feature pending – just submitted today – but no code yet for M141. But please add your "me too" to the feature request(s) that you found.
