### ISSUE TITLE
LCD doesn't work perfectly

### ISSUE THREAD

**Issue by D3bugg3RR** [MarlinFirmware/Marlin#14016]
Hello everyone, i installed bootloader in the tronxy x5s mainboard (atmega 1284P) and after that, the latest release of marlin firmware, i copied  all tronxy x5s files in the main directory and i uploaded the sketch, all works but the lcd is "disturbed"

Tronxy x5s have only configuration.h file (missing configuration_adv.h)

i used sanguino board and 1284P (16 Mhz)
![38836b16-6f57-460a-9369-f7812cc0e4ad](https://user-images.githubusercontent.com/35575032/57699325-c8867c80-7657-11e9-99ce-9970c1722c95.jpg)
![9ced7c23-dc11-4740-9c30-591cca881fbf](https://user-images.githubusercontent.com/35575032/57699329-ca504000-7657-11e9-86b4-b6024ea84e2f.jpg)

**Comment by jefersonbentesdacosta** [comment]
How did you solve your problem?

**Comment by InsanityAutomation** [comment]
@jefersonbentesdacosta it seems ardunio ide has been causing lcd issues, compiling with VS Code seems to fix it for most

**Comment by jefersonbentesdacosta** [comment]
I just added this lines to configuration.h

#define ST7920_DELAY_1 DELAY_NS(250)
#define ST7920_DELAY_2 DELAY_NS(250)
#define ST7920_DELAY_3 DELAY_NS(250)
