### ISSUE TITLE
How to modify the bootloder jump address of STM32F407 in the Marlin 2.0 firmware?

### ISSUE THREAD

**Issue by yangwenxiong** [MarlinFirmware/Marlin#14021]
Hello!How to modify the bootloder jump address of STM32F407 in the Marlin 2.0 firmware?

**Comment by shitcreek** [comment]
Take a look here: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/shared/backtrace/unwmemaccess.cpp

**Comment by yangwenxiong** [comment]
Hi, big brother, I tried to modify what you said, but it still doesn't work. Is there any other place to modify?

**Comment by yangwenxiong** [comment]
@shitcreek Hi, big brother, I tried to modify what you said, but it still doesn't work. Is there any other place to modify?

**Comment by yangwenxiong** [comment]
Thank you, it seems not the place you said, but I know where the problem is wrong!
