### ISSUE TITLE
[BUG] (enabling PIDTEMPBED causes feed rate all 3 axis to be very low)

### ISSUE THREAD

**Issue by Slipery** [MarlinFirmware/Marlin#14029]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Slipery** [comment]
Description
Steps to Reproduce
1. Using Marlin 1.1.9 on Ramps 1.4  with BL Touch and twin extruders with fan expander on D4 and D5
2. Enable PIDTEMPBED
Expected behavior:  Be able to auto tune PID Temp on Bed (this worked)
Actual Behavior: Travel in X Y and Z axis very slow.  Movement is only just perceptible.

By disabling PIDTEMPBED at line 509 movement returns to normal 
[CONFIG.zip](https://github.com/MarlinFirmware/Marlin/files/3185976/CONFIG.zip)

**Comment by robbycandra** [comment]
What is your board / processor ?

**Comment by Slipery** [comment]
Ramps 1.4 with arduino 2560

**Comment by robbycandra** [comment]
Maybe your setup needs better / faster board.
What about reduce other feature but still use PIDTEMP enable... Does it make the problem go away ?

**Comment by reloxx13** [comment]
read https://github.com/MarlinFirmware/Marlin/issues/11456

**Comment by Slipery** [comment]
yep M502 M500 solved it thanks all.
