### ISSUE TITLE
[BUG] sketch/src/feature/power_loss_recovery.cpp:285:40: error: 'struct job_recovery_info_t' has no member named 'active_hotend'

### ISSUE THREAD

**Issue by guestisp** [MarlinFirmware/Marlin#14031]
When building with `EXTRUDERS` >= 2 and `SINGLENOZZLE`

I'm not able to test with `SINGLENOZZLE` disabled as I only have a dual extruder single nozzle machine

```
sketch/src/feature/power_loss_recovery.cpp: In static member function 'static void PrintJobRecovery::resume()':
sketch/src/feature/power_loss_recovery.cpp:285:40: error: 'struct job_recovery_info_t' has no member named 'active_hotend'
     sprintf_P(cmd, PSTR("T%i S"), info.active_hotend);
                                        ^
exit status 1
```

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by guestisp** [comment]
I forgot to close.
I did a pull request, already merged, to fix this

**Comment by boelle** [comment]
:-D
