### ISSUE TITLE
MKS Gen V1.4 - Dual Z setup, Z2/E1 doesn't move

### ISSUE THREAD

**Issue by Earluke** [MarlinFirmware/Marlin#14038]
### Description

I have a Sunhokey Prusa I3 with a new MKS Gen V1.4 board and a mix of TMC2100 (X,Y,E0) and A4988 (both Z moptors).
 
As i have dual z stepper motors, but only one extruder (E0),  i have to use E1 for the 2nd Z stepper motor.

I did use the Marlin Configurator  to configure the driver types for each motor (X,Y,Z,E0,E1) and activated Z dual stepper drivers in configuration_adv.

### Steps to Reproduce

1. Use Marlin Configurator to create configuration + upload to printer
2. increase Z height manually via repetier host 

**Expected behavior:** both Z stepper motors to turn 
Only one z stepper motor turns (and the other can be turned by hand (no power))

I allready tried 10 different configuration files incl. 1.1.9 and 1.1.x and swapping motors (then the other one works, but never both)

I also made sure that my bed temp probe is activated (see other bug report).

**Comment by ghost** [comment]
Next thing to check, pin assignments for E1

**Comment by Earluke** [comment]
How exactly, what pin should E1 be assigned to?

FanDjango <notifications@github.com> schrieb am Do., 16. Mai 2019, 21:11:

**Comment by ghost** [comment]
Ähm. pins_..... file. Check the definitions, is there something there that might explain the failure to activate that stepper

**Comment by ghost** [comment]
In your configuration.h->you have defined the board. That points you to the pins file
See if all is ok. 
You didn't post your config so I'm using my crystal ball and everyone else would too

**Comment by robbycandra** [comment]
Check if you are using correct MotherBOard at configuration.h

**Comment by Earluke** [comment]
Reinstalled Repetier host and now it works perfectly.

THX for your help, BR Norbert

Am Sa., 18. Mai 2019 um 02:04 Uhr schrieb Robby Candra <
notifications@github.com>:

**Comment by shitcreek** [comment]
cool beans
