### ISSUE TITLE
[DOC] Missing M305 documentation

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#14040]
No mention of the M305 thermistor command here ..

http://marlinfw.org/meta/gcode
https://reprap.org/wiki/G-code#M305:_Set_thermistor_and_ADC_parameters

**Comment by RudyBenner** [comment]
Marlin\src\gcode\config\M305.cpp
Marlinfw if sometimes slow to get caught up.

**Comment by ghost** [comment]
hhmm, looks like a useful command, I'll have to try it. Thank yoiu @RudyBenner ;)

**Comment by RudyBenner** [comment]
can we close this?
