### ISSUE TITLE
[QUESTION] HAL value choice

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#14063]
What is the logic behind the choice of proper values for:
```c++
  #define TEMP_TIMER_FREQUENCY

  #define STEPPER_TIMER_RATE
  #define STEPPER_TIMER_TICKS_PER_US
  #define STEPPER_TIMER_PRESCALE

  #define PULSE_TIMER_RATE
  #define PULSE_TIMER_PRESCALE
  #define PULSE_TIMER_TICKS_PER_US
```

AFAIK:
`TEMP_TIMER_FREQUENCY` should always be 1000 (but maybe this must be rounded to something near such value for some CPU with low F_CPU)

??_TIMER_TICKS_PER_US should always be related to base frequency and prescaler used but in some HAL this is `STEPPER_TIMER_TICKS_PER_US ((STEPPER_TIMER_RATE) / 1000000)` and calculate prescaler using `CYCLES_PER_MICROSECOND / STEPPER_TIMER_TICKS_PER_US` but I think is done this way because important thing is to define a "frequency"

**Comment by xC0000005** [comment]
Following this. I had the same question, since defining a timer rate at compile time for Marlin doesn't reflect what really happens on STM32, being able to know what frequency a timer should run at is the key to being able to calculate the values properly.
