### ISSUE TITLE
[FR] G28 Start Script

### ISSUE THREAD

**Issue by sensei73** [MarlinFirmware/Marlin#14062]
Hello there, thanks to all for your Hard work!

I have a TouchMi sensor --> [see here!](https://www.hotends.fr/fr/home/64-capteur-auto-leveling-touch-mi.html)

It is activated by a magnet placed on the **RIGHT** side of the bed. So I need to go to Max_Bed_X to activated the sensor. It will be nice and user-friendly, if we could have a G28 start script possibility to activate this sensor as we have a G29 end script (I can disable it with it).

Actually I can achieve it by a dirty trick, a modification of G28.cpp but it's nasty.

Thanks in advance.

**Comment by ghost** [comment]
> a modification of G28.cpp but it's nasty.

Let's see it

**Comment by sensei73** [comment]
never mind, I needed this for a TouchMI probe but I did a real implantation of the probe there.
https://github.com/MarlinFirmware/Marlin/pull/14101
