### ISSUE TITLE
[QUESTION] What's HAS_TIMER's purpose

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#14073]
In fastio there is a HAS_TIMER define that I can't see used in Marlin, then why is it defined?

**Comment by ManuelMcLure** [comment]
It is used:
```
HAS_TIMER          85 src/HAL/HAL_STM32/fastio_STM32.h #define PWM_PIN(P)              HAS_TIMER(P)
HAS_TIMER          55 src/HAL/HAL_STM32F1/fastio_STM32F1.h #define PWM_PIN(P)              HAS_TIMER(P)
HAS_TIMER          55 src/HAL/HAL_STM32F4/fastio_STM32F4.h #define PWM_PIN(P)              HAS_TIMER(P)
HAS_TIMER          54 src/HAL/HAL_STM32F7/fastio_STM32F7.h #define PWM_PIN(P)              HAS_TIMER(P)
```

**Comment by xC0000005** [comment]
in HAL_STM32, it's correctly defined as digitalPinHasPWM.

**Comment by tpruvot** [comment]
Marlin/src/HAL/HAL_STM32F1/HAL.h:132:  #define digitalPinHasPWM(P) (PIN_MAP[P].timer_device != nullptr)
Marlin/src/HAL/HAL_STM32F1/fastio_STM32F1.h:53:#define HAS_TIMER(IO)         (PIN_MAP[IO].timer_device != nullptr)

**Comment by GMagician** [comment]
It's defined yes it's used no
I searched in the whole project and I only found the define...

**Comment by tpruvot** [comment]
you didnt search well
#define PWM_PIN(P)              HAS_TIMER(P)

**Comment by GMagician** [comment]
@tpruvot that's not completely correct, this is a define of a define, so only PWM_PIN is used and could be declared directly with HAS_TIMER content (both are inside fastio) but while PWM_PIN has a sense (it's used for sanity checks) the other?

**Comment by tpruvot** [comment]
its much more complicated, its not because a pin has a timer associated by default than PWM is enabled on it... and i dont even talk about the remap ones...

**Comment by GMagician** [comment]
There is also `USEABLE_HARDWARE_PWM` that is defined and never used...

**Comment by GMagician** [comment]
@tpruvot I know about it but since PWM_PIN is used in code and HAS_TIMER isn't I'm wondering why this has to be defined

**Comment by GMagician** [comment]
@Bob-the-Kuhn I think you added `USEABLE_HARDWARE_PWM` to HAL. Since it's never used in whole Marlin code, why has it to be present?

**Comment by Bob-the-Kuhn** [comment]
It was used at one time. Sounds like the code has changed and it's no longer used.

**Comment by Bob-the-Kuhn** [comment]
USEABLE_HARDWARE_PWM was part of the original "PWM for any pin" code back in the early days of the LPC1768 HAL.  That HAL has been re-written multiple times since then.  I'm not surprised that it's no longer used.
