### ISSUE TITLE
BLTouch Trigger, Nozzle into Bed

### ISSUE THREAD

**Issue by NelsonBlvd** [MarlinFirmware/Marlin#14077]
~~~~ 


When homing on my Anet A8 the BLTouch(v3.0) touches bed but z continues down 1-3 mm before stopping then rises and BLTouch flashes (alarm state) 
I attached my marlin instance and a video of printer doing its thing...


**Expected behavior:** touch bed and stop rise to 15mm on z-axis

**Actual behavior:** pushes nozzel into bed then rises to *15mm* on z-axis with "??" repeating in z location on LCD

#### Additional Information

[IMG_5184.zip](https://github.com/MarlinFirmware/Marlin/files/3201533/IMG_5184.zip)

[Marlin_base.zip](https://github.com/MarlinFirmware/Marlin/files/3201495/Marlin_base.zip)

**Comment by ghost** [comment]
I can see the probe deploying, it triggers, the trigger is not seen by the printer controller.

Try this first:

`#define Z_MIN_PROBE_ENDSTOP_INVERTING true` first.

It is a V3.0, the Marlin version is pre bugfix-2.0.x.

I don't know if it is an "early" V3.0 (pre Apr 5). These were slightly problematic.

You need bugfix-2.0.x to set these probes into 5V mode.

If they are not set explicitely to 5V mode, they will operate in open drain mode. That means you might need a resistor to pull up the signal line.

**Comment by NelsonBlvd** [comment]
Honerstly, ive tried both, setting it true/false has no effect on the printer

**Comment by NelsonBlvd** [comment]
changed to bugfix2.0 so i could also enable the 5v on BL Touch and nothing changed, still the EXACT same behavior as before with a couple of LCD screen bugs....
[Marlin2.0.zip](https://github.com/MarlinFirmware/Marlin/files/3205740/Marlin2.0.zip) < that is my "bugfix2.0" version of marlin.

**Comment by d3dorsett** [comment]
I have a similar issue with an SKR 1.3 board. 

Switching #define Z_MIN_PROBE_ENDSTOP_INVERTING from true to false did not make a difference, however, flipping the 2-pin (whtie & black) wires did fix the issue.

Maybe it is just my understanding of how Z_MIN_PROBE_ENDSTOP_INVERTING works. Does it invert the 2-pin connector (white & black) or the 3-pin (Red, Yellow, Brown)?

**Comment by ManuelMcLure** [comment]
``Z_PROBE_ENDSTOP_INVERTING`` does not affect the direction you need to connect the wires - they have to be connected in the right polarity regardless of the setting of ``Z_PROBE_ENDSTOP_INVERTING``. There is no way to change the polarity of the connection in software.

What that setting does is determine whether the endstop/probe is normally open or normally closed.

**Comment by Adanufgail** [comment]
I can confirm the same issue on a EZBOARD Lite with both a Genuine BLTouch and a 3DTouch, and I can confirm swapping the black and white wires fixed the crashing issue. Setting "#define Z_MIN_PROBE_ENDSTOP_INVERTING" to either true or false did nothing.

**Comment by InsanityAutomation** [comment]
That is an electrical item. These are not dry contact switches and there is a diode forcing polarity. Signal and ground here do matter. See the comment in Configuration_adv around all the bltouch options
```

   * Note: If the trigger signal of your probe is not being recognized, it has been very often
   *       because the BLACK and WHITE wires needed to be swapped. They are not "interchangeable"
   *       like they would be with a real switch. So please check the wiring first.
```

**Comment by boelle** [comment]
closed  as its a hardware issue and not marlin related
