### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by KiwiPedia12** [MarlinFirmware/Marlin#14100]
Hi.
I have three questions.
First, is it usable without a temperature sensor?
Second, is it possible to use only the x and y axes without using the z axis?
Finally, can I use the "Homing" function in this state?
Thank you.

**Comment by MasterPIC** [comment]
Hi,
I have just one question. Did you read the rules before going to open an "issue"?

**Comment by KiwiPedia12** [comment]
Oh! I did not read the rules properly.
I am very sorry.

**Comment by jellewie** [comment]
@HwangHanGyeol  you should be able to close this 'issue' by yourself. So the mods don't have to spend time doing it ;)
