### ISSUE TITLE
[BUG] SKR v1.3 - fan slows down/stops when heater is on

### ISSUE THREAD

**Issue by 040medien** [MarlinFirmware/Marlin#14111]
I just upgraded my printer with an SKR v1.3. I noticed that any time my single hotend is heating up, the hotend fan is turning off. When it almost reached temperature, it's turning off again, but running at a slower speed. Because of this, I'm suffering from heat creep.

I'm **not** using ADAPTIVE_FAN_SLOWING
I am using E0_AUTO_FAN_PIN

While I can't put my finger on it, I think that the part fan is also running at a slower speed.

Please see configs for additional context:
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/3218589/Configs.zip)

**Comment by jeroen85** [comment]
I guess you connected the fan to the HE1 terminals?
I use the same setup, but did not experience this problem.

**Comment by 040medien** [comment]
That's right. Would you mind sharing your configs?

**Comment by gloomyandy** [comment]
I have a similar setup which operates with no problems. My config is here:
https://github.com/gloomyandy/Marlin/tree/myskr1.3/Marlin

But what you describe sounds like a wiring problem or possibly an issue with your power supply. How do you have things wired? What voltage fans are you using? Does running the heated bed impact the fan speeds at all?

**Comment by 040medien** [comment]
Thank you Andy, that was the right hint! I am using two breakout boards between the board and the hotend connected with a ribbon cable.  Turns out they are using a common ground. It seems the terminal labels for the heater were flipped. Once I swapped the leads for the heater, everything worked fine!
