### ISSUE TITLE
Re-Arm+RAMP1.6Plus NOT WORKİNG MARLİN 2.0

### ISSUE THREAD

**Issue by orcunim** [MarlinFirmware/Marlin#14119]
Hello,

İ use TFT28. My printer pause, start, pause, start for 1-2 layer. İ upload new version. İ check it, all settings true.
İ open
#define RepRap Discount Smart Controller
But platformio give yellow error on upload
![7A6EB97B-CEF7-433B-8F01-25B56B017A9C](https://user-images.githubusercontent.com/51026211/58370913-a2849600-7efb-11e9-9043-70e6ae1c984d.jpeg)
![F3588C40-DB1F-4D6D-9E8D-7EEA9DAE3F48](https://user-images.githubusercontent.com/51026211/58370915-a2849600-7efb-11e9-8cba-63d6bf491368.jpeg)

**Comment by Ludy87** [comment]
Unuse Warning variable - no error

**Comment by orcunim** [comment]
But TFT28 dont working. what should I do? Screen is work one week ago.

**Comment by Ludy87** [comment]
TFT28 has its own controller maybe bad command is given.

**Comment by orcunim** [comment]
How can I fix ?  not currently active.  temperatures do not appear.  moving home is not working going home.  not connected briefly.

**Comment by orcunim** [comment]
Problem : Static electric //
