### ISSUE TITLE
[BUG] Error: Checksum Mismatch, Last Line: xx

### ISSUE THREAD

**Issue by orcunim** [MarlinFirmware/Marlin#14124]
Hello,

I use re-arm, ramps 1.6+ and TFT28. I upload last version but i started printer. the printer stops responding, and then resumes. İ try so much method in forum. İ print on pc. All great. After that copy sd card take tft. Touch print always pause start and error in screen.

1 month ago there was no problem.  with the latest update was like that.

![2FEDB825-0ED6-43C7-829F-F3AF686E0F37](https://user-images.githubusercontent.com/51026211/58374310-7ed94400-7f2b-11e9-85d3-3560ab427149.jpeg)

**Comment by orcunim** [comment]
Help please :(

**Comment by ShareEC** [comment]
I am suffering from the same problem.
I use marlin 2.0 firmware and  mks sgen board and mks tft 3.5.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
@orcunim or @SharePARTS 

Configurations, please
Please ZIP up your Configuration.h and Configuration_adv.h files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by dodoguigui** [comment]
[Checksum Mistmatch issue Marlin  2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/3708035/Checksum.Mistmatch.issue.Marlin.2.0.x.zip)
Hello,

I have the same problem. It's for Ender 3 with MKS Gen-L, MKS TFT 28, BlTouch and TMC 2208 in UART mode.

Please find Configuration.h and Configuration_adv.h file

Regards

**Comment by AnHardt** [comment]
Would not surprise me if the software serials for the TMC 2208 would block interrupts long enough to miss the interrupt requests from the hardware serial.

**Comment by boelle** [comment]
@orcunim still having issues?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by gokulvenkat** [comment]
I too have this issue did anyone found the solution

**Comment by Krzysiekzg** [comment]
Hi to all
for me in jgaurora a5 on skr 1.3 and marlin 2.0 also displayed error checksum mismatch last line, additionally the printer stopped randomly for 1-3 seconds spoiling the printout. this only occurred when printing from a USB connected with a cable to the mks tft 2.8 display. printing from a computer was ok

I think it's all because of the noise on the cables. I led the USB cable differently to which I connect the pendrive and the problem disappeared.

You can also create a protective screen of aluminum foil and insulation. it's worth checking it helped me out.
