### ISSUE TITLE
[FR] Mintemp tolerance time?

### ISSUE THREAD

**Issue by dtquandt** [MarlinFirmware/Marlin#14122]
Is there a way of adding some tolerance time to the mintemp error? My thermistor wire is very slightly borked and will sometimes lose connection for a fraction of a second, which is enough to kill the printer with a mintemp error. I've never seen it actually report 0 on the LCD, it's always reporting the correct temperature, but apparently it cuts out just enough to cause problems. If I could make it somehow need 3 seconds of 0 temp reporting to kill the print that would be so helpful...

**Comment by ghost** [comment]
Their is a setting in Configuration_adv.h that might help ..

```cpp
// The number of consecutive low temperature errors that can occur
// before a min_temp_error is triggered. (Shouldn't be more than 10.)
//#define MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED 0
```
