### ISSUE TITLE
[BUG?][STM32F1] Bad array size

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#14123]
Not sure because I can't compile such platform, but I'm going to work on Grand Central M4 and I'm replicating ADC DMA access..
With same logic I'm doing something like:
`#if ADC_PIN_COUNT > 0`
and it always evaluate to false
even a `#ifdef` ADC_PIN_COUNT
evaluate to false so I'm wondering what happens to:
`uint16_t HAL_adc_results[ADC_PIN_COUNT];`

**Comment by tpruvot** [comment]
Its "defined" locally, in same file... but its an enum, not a define

```enum TEMP_PINS : char {
  #if HAS_TEMP_ADC_0
    TEMP_0,
  #endif
  #if HAS_HEATED_BED
    TEMP_BED,
  #endif
  #if HAS_HEATED_CHAMBER
    TEMP_CHAMBER,
  #endif
  #if HAS_TEMP_ADC_1
    TEMP_1,
  #endif
  #if HAS_TEMP_ADC_2
    TEMP_2,
  #endif
  #if HAS_TEMP_ADC_3
    TEMP_3,
  #endif
  #if HAS_TEMP_ADC_4
    TEMP_4,
  #endif
  #if HAS_TEMP_ADC_5
    TEMP_5,
  #endif
  #if ENABLED(FILAMENT_WIDTH_SENSOR)
    FILWIDTH,
  #endif
    ADC_PIN_COUNT
};
```
