### ISSUE TITLE
Ender3-pro usb input broken, How can I communicate with mainboard?

### ISSUE THREAD

**Issue by sgsalman** [MarlinFirmware/Marlin#14120]
Hello there, 

My micro usb input is broken on mainboard. I need to connect my machine to computer to set the bed level and firmware update, so I can't now. Can I communicate by ISP to usb as I did before with micro usb?  I bought the bltouch v3 kit, so I have Isb to Usb part. Can I use this "ISP to USB" to communicate btw. comp and printer?

best regards.

**Comment by reloxx13** [comment]
search for "flash without bootloader"

stop asking questions here.

> Have you read Marlin's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md
> 
> Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use the Marlin Firmware forum at http://forums.reprap.org/list.php?415 or the Marlin Facebook Group https://www.facebook.com/groups/1049718498464482/.

**Comment by sgsalman** [comment]
@reloxx13 you guys act like everyone know everythings. I don't know something and I'm asking.

I already booted my printer, I just can't communicate with printer. thanks for info...

**Comment by lorenzodimauro97** [comment]
it literally say when you submit a bug report

"if you have any questions or need help use discord. this is ONLY for bugs"

**Comment by reloxx13** [comment]
and u guys act like this is a help forum.

**Comment by sgsalman** [comment]
@scippo97 okey u right, could u give me discord link, I couldnt find it.
