### ISSUE TITLE
[BUG] Values Cutoff with USE_BIG_EDIT_FONT Enabled

### ISSUE THREAD

**Issue by thisiskeithb** [MarlinFirmware/Marlin#14140]
### Description

Enabling `USE_BIG_EDIT_FONT` causes values to be cut off:
![IMG_3253](https://user-images.githubusercontent.com/13375512/58383243-1ae56880-7f89-11e9-815e-d8fd768c710d.jpeg)

### Steps to Reproduce

Grab the df77334 bugfix-2.0.x commit, and enable `USE_BIG_EDIT_FONT`.

I recompiled the 24b1818 commit from a few of days ago and the text is back to normal:

![IMG_3252](https://user-images.githubusercontent.com/13375512/58383269-829bb380-7f89-11e9-8e57-2baa662ffe87.jpeg)

**Expected behavior:** See full values when editing through the "big edit font" screens.

**Actual behavior:** Values are cut off.

**Hardware:** Creality Ender-3 with stock LCD (`CR10_STOCKDISPLAY`).

**Configs:** [Ender-3 - SKR 1.3 - 5-25-19.zip](https://github.com/MarlinFirmware/Marlin/files/3220415/Ender-3.-.SKR.1.3.-.5-25-19.zip)

**Comment by thisiskeithb** [comment]
I tested the commits in between the two I had tested previously and the bug was introduced in 44caf70.

**Comment by Patag** [comment]
In Marlin\src\lcd\dogm\ultralcd_DOGM.cpp, I just reverted to :
`        lcd_moveto(((lcd_chr_fit - 1) - (vallen + 1)) * one_chr_width, baseline); // Right-justified, leaving padded by spaces`
from :
`       lcd_moveto((lcd_chr_fit - (vallen + 1)) * one_chr_width, baseline); // Right-justified, leaving padded by spaces`
It is not tested on all possible "big edit font" screens,, but it seems to be running fine on most usual of them.
