### ISSUE TITLE
[BUG] Re-ARM failed send commands over USB. conection is OK and printer is ON

### ISSUE THREAD

**Issue by sl1pkn07** [MarlinFirmware/Marlin#14152]
### Description

i have issue whit the usb connection over MacOS (the pc more near at printer) (and presumably, yoth other OS)

i have configured the unit like the wiki say (http://marlinfw.org/docs/basics/install_rearm.html)

when open the pronterface and i try connect with the unit. the connection is OK. but any command inserted is recognized as Unknown, include the internal commands launched from pronterface iself

the printer works iself over the LCD

components: 
Original Re-ARM
RAMPS 1.4 Premium from StaticBoards
TMC2130 over SPI from StaticBoards
Stock Creality ender 3 LCD (+ custom cable following the pins_rearm file) connected to J3 pin header
stock thermisor and endstop from Ender 3 printer
24V power supply
Trianglelabs BLtouch (connected to servo 0 and wired the +5v PS_ON(?) pin header from rearm J2 +5v pin header)

### Steps to Reproduce

1. [First Step]
Download Marlin code from GIT (https://github.com/MarlinFirmware/Marlin/commit/5d96a6d983c065403216ed52a8c92ed22dc268ba)

2. [Second Step]
apply this configuration https://github.com/sl1pkn07/Marlin/commit/df333005bed13fb49abbc52b75a97a382bf78c3d (or clone the repository/branch (sL1_Changes_ReARM))

3. [and so on...]
build and upload to the rearm. and reboot the unit. using Atom+Platformio (linux)
4. []
connect the unit, with the shield and all components, include thermisor, drivers, endstops, etc include the unit over USB to the PC
5. []
Open the pronterface and try to connect

**Expected behavior:** [What you expect to happen]

connect and send/received commands it without problem

**Actual behavior:** [What actually happens]

Connection is OK, but when the protenface send her own commands, or send commands by hand, say " Unknown command". if for example send a "G29" over LCD and finish the leveling, is possible see the output, but not all times

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

https://github.com/sl1pkn07/Marlin/commit/835104272edff07b54778ff8500a7258c830d84c

* Provide pictures or links to videos that clearly demonstrate the issue.

![Captura de pantalla 2019-05-25 a las 22 13 11](https://user-images.githubusercontent.com/462213/58374182-54db4e00-7f3a-11e9-8c78-1c8f0a4ecd6e.png)

* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

*edit: rebased
*edit2: fix links

**Comment by sl1pkn07** [comment]
https://github.com/MarlinFirmware/Marlin/issues/10781#issuecomment-496229575

same issue if set `TEMP_SENSOR_BED` to 0

**Comment by sl1pkn07** [comment]
@syurev, with "the board hung again after I changed TEMP_SENSOR_BED from 0 to 1." you mean halt by `max_temp_bed` error?

i'm not sure why, but i raise this error today :/

TEMP_SENSOR_BED to 1 fix the halt, but the connection still fails as described

**Comment by sl1pkn07** [comment]
the halt problem is fixed with https://github.com/MarlinFirmware/Marlin/pull/14167

the main problem persist

testing with a dongle Bluetooth HC-06 connected, pin to pin (tx and rx crossed), in the port J4, configure the baudrate to `115200` bauds, and enable `SERIAL_PORT_2` to 0, i can able connect throught pronterface with the printer over BT

![Captura de pantalla 2019-05-28 a las 22 21 45](https://user-images.githubusercontent.com/462213/58509643-56558200-8197-11e9-833e-646b94a9e56e.png)

if try the same with the USB:

![Captura de pantalla 2019-05-28 a las 22 25 39](https://user-images.githubusercontent.com/462213/58509757-9ae11d80-8197-11e9-923e-4124c575cb85.png)

**Comment by Bob-the-Kuhn** [comment]
I'm not making any headway on my project so I thought I'd see if I could be of help.

Here's what I did:
1. Downloaded your commit, compiled it & uploaded to my Re-ARM. **RESULT:**  USB port came up for about a second and then hung.  No coms over USB.
2. Downloaded latest 2.0.x, set motherboard to Re-ARM, port to -1, compiled, copied to SD, moved SD to Re-ARM and rebooted.  **RESULT:** same as before (no comms over USB)
3. Set port 2 to 0, ... **RESULT:**  same as before (no comms over USB)
4. Enabled SDSUPPORT and RepRap full graphics LCD, … **RESULT:** Everything works fine.
5. Removed port 2, SDSUPPORT and RepRap full graphics LCD, …  **RESULT:** Connects just fine over USB.
6. Dropped your configuration files in, ..  **RESULT:**  SYSTEM hung (turns out it was because of bed over temperature error due to nothing attached to the thermal inputs).
7. Switched LCD to my RepRap full graphics LCD - now I could see the hang was because of the bed over temperature error.
8. Set bed and extruder to 998.  **RESULT:** SD card is mapped to PC as a drive and have normal USB communications.

Strange stuff.

I'm guessing that, at least on a Windows 10 PC, once the PC sees a port problem it'll continue to fail it until ???.  After that a good USB connection always comes up.

Have you tried your config with the very latest 2.0.x?

**Comment by Bob-the-Kuhn** [comment]
One theory: They just fixed a bug that corrected an out of bounds array subscript.  This type of problem has been known to cause all kinds of strange behavior with different symptoms depending on the options enabled.

**Comment by sl1pkn07** [comment]
yes, i test with it. my latest comment is with it (not exactly, is clone repo (latest commit fetched 0f04ba016fbd5397428125330b9caba6fe9d02ee) + my changes + this PR https://github.com/MarlinFirmware/Marlin/pull/14167 applied (for fix maxbedtemp halt)

**Comment by Bob-the-Kuhn** [comment]
PR #14167 was merged a day ago.  Are you now fully functional with **today's** 2.0.x?

**Comment by syurev** [comment]
For mine it work just fine for now.

> PR #14167 was merged a day ago. Are you now fully functional with today's 2.0.x?

**Comment by sl1pkn07** [comment]
rebase latest commit https://github.com/MarlinFirmware/Marlin/commit/9d9030a39c747da92adc2e0a9847a63e7bb8eaa6, same issue in Macos Mojave. but in windows 10 (with laptop) works without problem

i'm not sure if is a problem of the apple driver or what...

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by sl1pkn07** [comment]
The issue still here....

**Comment by boelle** [comment]
@sl1pkn07 is the issue still there?

**Comment by sl1pkn07** [comment]
if no one touch the serial code, seems yes (my mac is down at this moment)

greetings

**Comment by boelle** [comment]
ok, please let us know when your mac is up again

**Comment by boelle** [comment]
@sl1pkn07 is your mac up again?

**Comment by sl1pkn07** [comment]
nope. and idk when i can power on again

anyway, i close the issue, i have connect the printer over wifi with the ESP01 module, not want to need connect over usb anymore, so...
