### ISSUE TITLE
[BUG] Marlin 2.0.x: SKR v1.3 with TMC 2130 compilation error

### ISSUE THREAD

**Issue by biskero** [MarlinFirmware/Marlin#14154]
Hello,

I am compiling Marlin bugfix-2.0.x

 for SKR v1.3 with TMC 2130, dual extruder
getting errors during compilation:

`Compiling .pioenvs/LPC1768/src/src/gcode/bedlevel/mbl/M421.cpp.o
Marlin/src/feature/tmc_util.cpp: In instantiation of 'void tmc_status(TMC&, TMC_debug_enum) [with TMC = TMCMarlin<TMC2130Stepper, 'X', '0', (AxisEnum)0>]':
Marlin/src/feature/tmc_util.cpp:655:31:   required from here
Marlin/src/feature/tmc_util.cpp:579:38: error: 'class TMCMarlin<TMC2130Stepper, 'X', '0', (AxisEnum)0>' has no member named 'get_pwm_thrs'; did you mean 'en_pwm_mode'?
uint32_t tpwmthrs_val = st.get_pwm_thrs();`

There are other but are the same for Y, Z, E1, E2
Any suggestions?

thx

**Comment by teemuatlut** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/14134

**Comment by biskero** [comment]
thanks a lot, commenting TMC_DEBUG worked

**Comment by boelle** [comment]
@biskero so this one is "fixed" ?

**Comment by biskero** [comment]
@boelle I think so! can I close it ?

**Comment by boelle** [comment]
oki, then i will do a close, you can always ask for a reopen should you find that its not fixed
