### ISSUE TITLE
Viki LCD won't show SD card contents after removing and reinserting card

### ISSUE THREAD

**Issue by bryanboettcher** [MarlinFirmware/Marlin#1415]
When my machine (Makergear M2, RAMBO 1.3, Viki LCD) is powered on, the SD card works as expected.  Going to the "Print from SD card" menu displays the filesystem and printing works normally.

Upon removing the MicroSD card and transferring GCODE to it, the firmware is unaware of its reinsertion.  The display will change from "No SD card" to "Print from SD card", but the filesystem will not show up at all.  After resetting the machine, the SD card behaves properly again.

I am properly unmounting the SD card, and my workflow works on other machines with different LCD controlers (like the RepRapDiscount one with RAMPS).

**Comment by thinkyhead** [comment]
@bryanboettcher I have had this issue occasionally also. I discovered in my case that it helped to tighten the connection between the LCD/SD unit and the board. Once the plugs were nice and tight the problem went away.

**Comment by bryanboettcher** [comment]
This is definitely a firmware problem.  I had a printer that could read SD cards flawlessly, then stopped as soon as I changed the firmware to a newer version of Marlin.

**Comment by thinkyhead** [comment]
@bryanboettcher Have you tried an earlier version of Marlin? If you can find an earlier iteration that works, we can compare and see what has changed.

**Comment by bryanboettcher** [comment]
I did try an earlier version of Marlin, it works as expected.  It was a
modified version posted by MakerGear --
http://makergear.wdfiles.com/local--files/m2-lcd-panel/M2_LCD_Firmware_24Vw24Vheater.zip

I can't tell what version of Marlin it is, but it's before the switch to
.INO extension.  I tried setting the values of SDCARDDETECT to the other
values I found in pins.h (on the new Marlin), to no effect.

**Comment by thinkyhead** [comment]
Hmm, well I know it's a hassle to re-flash, but if you want to keep helping to track this down, Marlin now has [two tagged versions](https://github.com/MarlinFirmware/Marlin/tags), [1.0.1](https://github.com/MarlinFirmware/Marlin/tags/1.0.1) and [1.0.2](https://github.com/MarlinFirmware/Marlin/tags/1.0.2).

If you find that one of these works for you, then it will be an easier starting-point to see what's involved, since the tagged versions are only a couple months old and have fewer changes. If the SD card still flaky in these earlier versions, I can start asking around about SPI code and see what has changed in those regions over the past year or so.

**Comment by bryanboettcher** [comment]
I chased the problem down to fastio.h.  Attached are the good & bad
versions, but these are referenced from an old version of fastio.h
-- 62aab66299cc7942a9b3559474eeba7047528bcd

I go pretty cross-eyed trying to diagnose what's going on in here though.

On Tue, Feb 3, 2015 at 12:43 AM, Scott Lahteine notifications@github.com
wrote:

> Hmm, well I know it's a hassle to re-flash, but if you want to keep
> helping to track this down, Marlin now has two tagged versions
> https://github.com/MarlinFirmware/Marlin/tags, 1.0.1
> https://github.com/MarlinFirmware/Marlin/tags/1.0.1 and 1.0.2
> https://github.com/MarlinFirmware/Marlin/tags/1.0.2.
> 
> If you find that one of these works for you, then it will be an easier
> starting-point to see what's involved, since the tagged versions are only a
> couple months old and have fewer changes. If the SD card still flaky in
> these earlier versions, I can start asking around about SPI code and see
> what has changed in those regions over the past year or so.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1415#issuecomment-72602445
> .

< code removed >

**Comment by thinkyhead** [comment]
@bryanboettcher It looks like github has a limit on comment size, so unfortunately only the first file, (up to line 2918) was pasted into your comment. But are you saying that the commit you cite – https://github.com/MarlinFirmware/Marlin/commit/62aab66299cc7942a9b3559474eeba7047528bcd – is the one that broke SD remounting? I looked it over, and I see that it includes changes from two earlier commits, both adding pins definitions for RAMBo LCD. Commit for `pins.h`: https://github.com/MarlinFirmware/Marlin/commit/53614e51442adaa6f254f8323e2fc0449e9b63dd. Commit for `fastio.h`: https://github.com/MarlinFirmware/Marlin/commit/b42d24e31ef0060659236da1787bee87682fa68b.

So if you simply remove these pins definitions from your `pins_RAMBO.h` and `fastio.h` files, your SD card reinsertion then works ok?

**Comment by boelle** [comment]
is this one still active?

for big code use something like pastebin.com

**Comment by bryanboettcher** [comment]
It's still an issue, I will get the diff and post on pastebin tonight or
tomorrow night.

**Comment by boelle** [comment]
forgotten us? :-D

**Comment by bryanboettcher** [comment]
I haven't, but I don't have the time to go back and re-build my patch.
Sorry guys :(

**Comment by boelle** [comment]
bummer :-( well i will close this one then... it can still be read by everyone and if another user should have the same issue and see this one then please open a new issue
