### ISSUE TITLE
[BUG] Setting BED/CHAMBER to "user thermistor" type stops Marlin booting

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#14159]
ie in **Configuration.h** ..

```cpp
#define TEMP_SENSOR_0 11
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_4 0
#define TEMP_SENSOR_5 0
#define TEMP_SENSOR_BED 1000
#define TEMP_SENSOR_CHAMBER 0
```

**Comment by ghost** [comment]
Error is caused by recent user thermistor table fix.

Fix is to fix the BED and CHAMBER define names.

In ..

**Sanity_Check.h
Temperature.h
Temperature.cpp**

change ..

"**BED_USER_THERMISTOR**" to "**HEATER_BED_USER_THERMISTOR**"
"**CHAMBER_USER_THERMISTOR**" to"**HEATER_CHAMBER_USER_THERMISTOR**"

**note:** the warnings that show up due to this should show as errors not warnings at compile time.

**Comment by sl1pkn07** [comment]
sems with

~~~
#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_4 0
#define TEMP_SENSOR_5 0
#define TEMP_SENSOR_BED 1
#define TEMP_SENSOR_CHAMBER 0
~~~

also halt the machine (rearm+ramps)

**Comment by ghost** [comment]
When you say 'halt', do you mean it starts up OK but then stops (with an on-screen message) ?

The error I'm highlighting is crashing the CPU at boot-up, not halting it.

**Comment by sl1pkn07** [comment]
[VID_20190528_190337.zip](https://github.com/MarlinFirmware/Marlin/files/3229413/VID_20190528_190337.zip)


the first one, i think (in the vid the buzzer is disabled, because continuous buzz)

**Comment by ghost** [comment]
Can't extract the file from that zip.

Anyway, your problem is not connected to this threads issue. Your problem sounds like it's this one ..

https://github.com/MarlinFirmware/Marlin/issues/14139

**Comment by sl1pkn07** [comment]
download it again. just rename to mp4

Edit:
OH. then you can ignore it. sorry and greetings

**Comment by ghost** [comment]
mmm, your problem is as per other issue, not this one.
