### ISSUE TITLE
[BUG] G28 finishes far from origin (sensorless homing)

### ISSUE THREAD

**Issue by mat2k** [MarlinFirmware/Marlin#14169]
I am fairly sure this is unexpected behavior, but it might also be bad configuration from my part. 
I have a Cartesian prusa i3 rework clone, with TMC2130's configured to use sensorless homing. My bed is 200x200. Marlin 2.0 bugfix. I also have an allen probe with offsets x:25 and y:5
Since the collision points for the X carriage and Y bed are far from where I want the home to be (x: -27 and y: -92) I set X_MIN_POS and Y_MIN_POS to -27 and -92 and then also set MANUAL_X_HOME_POS and MANUAL_Y_HOME_POS to these same values. This means that I can probe the entire bed, so i set Z_SAFE_HOMING to [0,0]. The result is that when homing, each axis homes and then goes to the home position correctly.

The problem: After doing a "G28" (no arguments), both X and Y home and then move the probe to the origin point, and Z is probed. But after that, Marlin moves the nozzle to [2,75] (probe pos would be [27, 80]), while it should stay in the origin.
Doing a "G28 X Y" will home and then move to [0,0], and doing a "G28 Z" after that will probe the bed and stay in [0,0] too.

In the "probe.cpp" file, line 702, I found

```
  // Move the probe to the starting XYZ
  do_blocking_move_to(nx, ny, nz);
```
which I assume is the source of the issue.

This also happens after doing a Z align (Z34) after it ends.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
