### ISSUE TITLE
[BUG] Re-Arm with Ramps can not be connected to

### ISSUE THREAD

**Issue by kurtisane** [MarlinFirmware/Marlin#14168]
### Description
When connecting the Re-Arm Board without the Ramps Board on top Windows detects the Re-Arm successfully and I can upload and connect via Pronterface, but when the Re-Arm is on top of it Windows says that the Device can not be recognized and Pronterface can not connect.

The SD-Card is not shown anymore.

Drivers or Serial Port wrong ?
I tried -1 and 0 as Serial Port

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3229710/Marlin.zip)

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
