### ISSUE TITLE
[BUG] [BUG 2.0.x] 4ef364a broke STM32F1 build

### ISSUE THREAD

**Issue by berghauz** [MarlinFirmware/Marlin#14177]
### Description
Probes offset sanity check added by 4ef364a0735917a5ae5d31082330bbac87fc7a76 broke STM32F1 build. 

### Steps to Reproduce

1. Set build env to mks_robin
2. pio run -v

**Expected behavior:**
Build complete

**Actual behavior:** 

`
In file included from Marlin/src/HAL/HAL_STM32F1/../../inc/MarlinConfig.h:41:0,
from Marlin/src/HAL/HAL_STM32F1/HAL.cpp:36:
Marlin/src/HAL/HAL_STM32F1/../../inc/SanityCheck.h:988:3: error: non-constant condition for static assertion
static_assert(FLOOR(float(X_PROBE_OFFSET_FROM_EXTRUDER)) == float(X_PROBE_OFFSET_FROM_EXTRUDER), "X_PROBE_OFFSET_FROM_EXTRUDER must be an integer!");
In file included from Marlin/src/HAL/HAL_STM32F1/HAL.h:39:0,
from Marlin/src/HAL/HAL_STM32F1/HAL.cpp:34:
Marlin/src/HAL/HAL_STM32F1/../../core/macros.h:260:27: error: call to non-constexpr function 'float floorf(float)'
#define FLOOR(x)    floorf(x)
`

#### Additional Information
Tried with ststm32@5.3.0 and 5.4.0

**Comment by berghauz** [comment]
Ok, i have found #14101.

**Comment by tpruvot** [comment]
yep but you should keep that open, as he readded it to the PR

**Comment by berghauz** [comment]
Ok.

**Comment by tpruvot** [comment]
its maybe only doable in c++17, stm32 toolkit seems -std=gnu++11

**Comment by berghauz** [comment]
c++11 either but yes, not gnu++11

**Comment by tpruvot** [comment]
seems forced in Marlin/src/HAL/HAL_STM32F1/STM32F1_flag_script.py but not only there, unable to set it, its added two times...

**Comment by tpruvot** [comment]
ok, Marlin/Makefile:659:CXXSTANDARD = -std=gnu++11

**Comment by berghauz** [comment]
this makefile don't have any influence in building process, you could even delete it

**Comment by tpruvot** [comment]
indeed rmm, so i dunno, maybe forced by the sdk

**Comment by berghauz** [comment]
Yes, by framework-arduinoststm32-maple/tools/platformio-build-stm32f1.py but it didn't help either :)

**Comment by tpruvot** [comment]
yep im not german enough to fix such issue, deleted locally... :p

**Comment by boelle** [comment]
would config files be usefull here?

**Comment by tpruvot** [comment]
It was fixed by adding build_unflags in platformio.ini, can be closed i think.

**Comment by berghauz** [comment]
Yep
