### ISSUE TITLE
[FR] Level Corners w/ Probe Assistance

### ISSUE THREAD

**Issue by mat2k** [MarlinFirmware/Marlin#14170]
Instead of having to use a piece of paper to level the corners of the bed, it'd be better to have a feature that utilizes the probe to tell you roughly how much you need to adjust the corner heights. For example: 
probe a corner for reference, then raise Z, go to the next corner, probe, and tell the user to raise or lower the corner (if possible, estimate a number of turns to the bed screw/nut by having the user set the screw pitch in the Marlin setup), and wait for confirmation that the height adjustment has been done. Repeat the probing and adjustment until the difference to the first corner is less than a modifiable value (e.g. 0.02), then move to the next corner and repeat the process.
(If the difference is acceptable, move to the next corner without user input, and if all 4 corners are accepted, finish).

**Comment by thinkyhead** [comment]
This feature now exists in Marlin 2.0.6.
