### ISSUE TITLE
[BUG] Bad Z Position after a power loss resume

### ISSUE THREAD

**Issue by andriee86** [MarlinFirmware/Marlin#14194]
### Description
After a power loss resume my printer rise up the nozzle too much making the function not working.
Skr 1.3 board, marlin 2.0.x

### Steps to Reproduce
1. Take off power during a print
2. Restart the print with the power resume menu

**Expected behavior:** resume the print from last know layer

**Actual behavior:** rising up the z axis too much

#### Additional Information

Video: https://www.youtube.com/watch?v=Z7xMlFywO8Q

**Comment by yunstacknj** [comment]
I have the same problem.
Try the following changes, my problem is solved：
Modify file power_loss_recovery.cpp line 362, add following codes:
// Move back to the saved Z
  dtostrf(info.current_position[Z_AXIS], 1, 3, str_1);
  //sprintf_P(cmd, PSTR("G1 Z%s F200"), str_1);
  //gcode.process_subcommands_now(cmd);
    gcode.process_subcommands_now_P(PSTR("G1 Z0 F200"));
    
    // Restore Z position with G92.9
    dtostrf(info.current_position[Z_AXIS], 1, 3, str_1);
    sprintf_P(cmd, PSTR("G92.9 Z%s"), str_1);
    gcode.process_subcommands_now(cmd);

**Comment by andriee86** [comment]
> 
> 
> I have the same problem.
> Try the following changes, my problem is solved：
> Modify file power_loss_recovery.cpp line 362, add following codes:
> // Move back to the saved Z
> dtostrf(info.current_position[Z_AXIS], 1, 3, str_1);
> //sprintf_P(cmd, PSTR("G1 Z%s F200"), str_1);
> //gcode.process_subcommands_now(cmd);
> gcode.process_subcommands_now_P(PSTR("G1 Z0 F200"));
> 
> ```
> // Restore Z position with G92.9
> dtostrf(info.current_position[Z_AXIS], 1, 3, str_1);
> sprintf_P(cmd, PSTR("G92.9 Z%s"), str_1);
> gcode.process_subcommands_now(cmd);
> ```

mmmmm all the lines? some are "//"..... i tryed, it seemed working, i mean, the nozzle went back to right position but then rised up again....

**Comment by yunstacknj** [comment]
"//" is code comment, not affects operatio.  raise how much？Is the z position value in lcd right ?

**Comment by andriee86** [comment]
> 
> 
> "//" is code comment, not affects operatio. raise how much？Is the z position value in lcd right ?

yeah, but some of ur line code are commented, like: "//sprintf_P(cmd, PSTR("G1 Z%s F200"), str_1);
//gcode.process_subcommands_now(cmd);"
is it right or a mistake?

anyway i tryed a few times, with just the first part of ur code, the "// Move back to the saved Z" part, it does the first layer right but then on next layer is rising it up again,

and if u add all of ur code, with also the "// Restore Z position with G92.9" part, then it just go on the right layer but then rise it up again....

**Comment by yunstacknj** [comment]
not mistake，it is just comment old code. please upload your  power_loss_recovery.cpp file，i check it

**Comment by andriee86** [comment]
> 
> 
> not mistake，it is just comment old code. please upload your power_loss_recovery.cpp file，i check it

https://www.dropbox.com/s/xbb3578d6j3tb94/power_loss_recovery.cpp?dl=0

here we go, thanks mate :)

**Comment by yunstacknj** [comment]
[G92.cpp.zip](https://github.com/MarlinFirmware/Marlin/files/3257895/G92.cpp.zip)
[power_loss_recovery.cpp.zip](https://github.com/MarlinFirmware/Marlin/files/3257899/power_loss_recovery.cpp.zip)
replace my files, have a try， need to decompress

**Comment by tpruvot** [comment]
if you do a G1 Z0 onto the part to resume... will destroy it

**Comment by tpruvot** [comment]
this patch may work with your logic, untested yet http://sprunge.us/SMmtj0

**Comment by andriee86** [comment]
> 
> 
> [G92.cpp.zip](https://github.com/MarlinFirmware/Marlin/files/3257895/G92.cpp.zip)
> [power_loss_recovery.cpp.zip](https://github.com/MarlinFirmware/Marlin/files/3257899/power_loss_recovery.cpp.zip)
> replace my files, have a try， need to decompress

thanks buddy!! its all working now with ur files! dont know what wrong, but its working so fair enough for me ^^ really thanks!

**Comment by tpruvot** [comment]
yep, after a test.. my patch doesnt work, doesnt do a Z homing at all and seems to double the Z position.

relative position i guess... so

**Comment by robbycandra** [comment]
Fixed with PR #14230

**Comment by boelle** [comment]
@andriee86 can you confirm its fixed with PR #14230 ?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
