### ISSUE TITLE
[FR] Driver TMC 2209 support

### ISSUE THREAD

**Issue by biskero** [MarlinFirmware/Marlin#14209]
Hello,

any plans to add the TMC 2209 ?
Looks like it's a combination of the TMC 2130 and TMC 2208.

thx

**Comment by teemuatlut** [comment]
Yes.

**Comment by biskero** [comment]
very cool ! no timeframe ? :)

**Comment by teemuatlut** [comment]
I should be receiving a set of drivers this week (maybe next) and I can then do some basic testing.
But I have very limited access to my printers this month and the support might first be at a theoretical level for a bit.

**Comment by biskero** [comment]
sounds great, will order some for my skr v1.3 board

**Comment by ghost** [comment]
They'll go nicely with the new board ;) .. which has the lovely STM32F7 CPU :)

![SKR_Pro](https://user-images.githubusercontent.com/49303635/58825189-cd769480-8635-11e9-8cf4-56f0c61df203.jpg)

**Comment by biskero** [comment]
wow!

**Comment by everything-tech-related** [comment]
What's the difference between this and v1.3? 

Is that 6 stepper driver support?

**Comment by biskero** [comment]
from pic, better power connectors, 3 fuse, 6 drivers slots, a lot more pin connections.
But I have no idea for the rest.

**Comment by stricktech** [comment]
awsome glad to hear the 2209s will get worked on.

Thats the skr pro, i should be getting one around the 25th of this month (won it in the btt FB group)
They announed it in the FB group but nor release date yet, and they havent said much about it, besides what you can see.

**Comment by InsanityAutomation** [comment]
Yeah, id love to get one to throw an idex machine on here... Wonder why they want back to the STM32 chips though over the LPC, a bit more stable atm...

**Comment by everything-tech-related** [comment]
I'll be on  the lookout, but I just got the v1.3. Still installing and configuring....if theres no major difference I'll just pass on this board

**Comment by stricktech** [comment]
i read it was a stm32f4 but this image shows an h7 , so who knows, i guess we will find out soon enough
![skrpro](https://user-images.githubusercontent.com/50678364/58830907-02bcbb80-8611-11e9-9863-51f306a0406e.jpg)

**Comment by stricktech** [comment]
> I'll be on the lookout, but I just got the v1.3. Still installing and configuring....if theres no major difference I'll just pass on this board

i just got the skr 1.3 installed and set up on my cr10, the day before they announced i was one of the 10 they would be sending them to. depending on more info on the board, ill either tear cr10 back down, or use it on one of my other printers.

**Comment by ghost** [comment]
The STM32F4/7 MCU's are **_much_** more powerful than the old LPC chips, they have hardware FPU, faster CPU clock, more pin options etc. Saying that, the old LPC MCU's do just fine anyway for a 3D printer.

**Comment by InsanityAutomation** [comment]
> The STM32F4/7 MCU's are **_much_** more powerful than the old LPC chips, they have hardware FPU, faster CPU clock, more pin options etc. Saying that, the old LPC MCU's do just fine anyway for a 3D printer.

I'd say awesome in a couple months when we know the platform is stable! Before then questionable business decision but I won't complain too much as it gives us good accessible low cost hardware to debug on :)

**Comment by bigtreetech** [comment]
please reference this [PR](https://github.com/MarlinFirmware/Marlin/pull/14215)

**Comment by InsanityAutomation** [comment]
They found us talking about putting these on their boards! Thanks @bigtreetech im sure more of us will be getting these in our hands soon. I still cant find anywhere to buy a pro board yet :/

**Comment by stricktech** [comment]
They also make tmc2209 and started selling them last week, so they need the marlin support, they have not started selling the skr pro yet, but they created a fb group last night for release Info (bigtreetech skr pro user group)

**Comment by stricktech** [comment]
New image btt added to the group
![FB_IMG_1559649121232](https://user-images.githubusercontent.com/50678364/58877296-f4fd4980-8695-11e9-8d1d-ea7708e24d33.jpg)

**Comment by InsanityAutomation** [comment]
Yeah, I hopped on the group last night as well. Ive got an idex machine here that could use a better board than the atmega2560....

**Comment by Gerggg** [comment]
Hello, any news about this feature ? (TMC2209 support)

**Comment by Hedda** [comment]
FYI; both the FYSETC Cheetah board and BIQU BIGTREETECH SKR MINI-E3 boards are now Aliexpress

https://www.reddit.com/r/3Dprinting/comments/c1lttc/fysetc_cheetah_board_chinaclone_of_th3d_ezboard/

https://www.reddit.com/r/BIGTREETECH/comments/c0hdht/bigtreetech_skr_mini_e3_done/

Both these boards feature integrated TMC2209 drivers and STM32F103 32-bit based MCU

https://github.com/bigtreetech/BIGTREETECH-SKR-MINI-V1.1

**Comment by Gerggg** [comment]
Is the TMC 2209 compatible with Marlin's Linear advance?

**Comment by LinoBarreca** [comment]
it has been merged already.
https://github.com/MarlinFirmware/Marlin/pull/14249

**Comment by thisiskeithb** [comment]
@boelle: This issue can be closed since TMC2209s are supported.

**Comment by boelle** [comment]
same as before, we can reopen if we get major protests :-D
