### ISSUE TITLE
SD_MENU_CONFIRM_START selection order?

### ISSUE THREAD

**Issue by J-PN** [MarlinFirmware/Marlin#14205]
Hi,

I wonder how it would be possible to change the order of active command?

E.g. starting the print the assumption selection is Cancel. The Print is more used selection so I'd like to have that i.e. right corner option as a default. Would be a bit quicker to use.

**Comment by robbycandra** [comment]
It prevent user to make double click mistake.

**Comment by boelle** [comment]
is this a question?

**Comment by InsanityAutomation** [comment]
@boelle @shitcreek can close this one too as a general inquiry

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
