### ISSUE TITLE
[BUG] BLTouch down while moving

### ISSUE THREAD

**Issue by CAP1Sup** [MarlinFirmware/Marlin#14206]
So the problem is that after failing to bed level (the y-offset was wrong and the probe went behind the bed), I re-homed, but the problem is that the probe was down while leveling and was almost taken out by the bed.

1. Do a bed level and have the probe overshoot the back of the bed.
2. With a maximum distance to go past 0 being 2, it will fail probing.
3. After that, home the bed with safe homing enabled

The probe is supposed to retract after failing to probe.

The probe doesn't retract

[ConfigurationFiles.zip](https://github.com/MarlinFirmware/Marlin/files/3244770/ConfigurationFiles.zip)

**Comment by 5p4k** [comment]
For me the probe always stays down after leveling or homing, independently of success or failure of the bed level. As also mentioned in #12698, a deployed probe may be hit by the bed if printing close to the border (that's what happened to me), or may hit the print later on.
