### ISSUE TITLE
G28 (Micromake D1)

### ISSUE THREAD

**Issue by chenmaker** [MarlinFirmware/Marlin#14217]
i want turn on my 3Dprinter run a autohome(G28)
example-->https://github.com/Bougakov/Micromake-D1-3D-printer/blob/master/Installing%20custom%20firmware.md

**Comment by shitcreek** [comment]
~~auto0.g is probably the closest thing Marlin provides - https://github.com/MarlinFirmware/Marlin/wiki/Autostart~~

That said, this Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by thinkyhead** [comment]
We have a Micromake D1 and it can run Marlin. However, Marlin only comes with a C1 configuration. So it needs to be tweaked to run on the D1.

**Comment by thinkyhead** [comment]
Here is the configuration we use with the Marlin `bugfix-1.1.x` branch (which is 1.1.9 plus a few tweaks). [Micromake D1.zip](https://github.com/MarlinFirmware/Marlin/files/3289250/Micromake.D1.zip)

Maybe it will work for you.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
