### ISSUE TITLE
Configuration Marlin FW 2.0.x dual Z MKS SBASE

### ISSUE THREAD

**Issue by TomTom076** [MarlinFirmware/Marlin#14213]
Hello!
Tried to configure dual Z in Marlin 2.0.x latest version, download today. I have done the config in configuration.h and configuration_adv.h and plattformio.ini.
Board => MKS SBASE V1.3
E1 stepper should be Z2
Anybody an idea whtas going wrong?
Stepper E1 isn´t moving while Z1 is moving. Z2 is wobbling and not moving.

Thanks!!!!

Tom

[Config MKS SBASE.zip](https://github.com/MarlinFirmware/Marlin/files/3248993/Config.MKS.SBASE.zip)

**Comment by RudyBenner** [comment]
Corex machine? line 588
You did not define the stepper drivers. SBASE uses DRV8825. beginning line 644

Z2 is twitching? Wiring error for that stepper. Check the cable. 
Phases in series will produce low torque and ambiguous rotation.


#define X_DRIVER_TYPE  DRV8825
#define Y_DRIVER_TYPE  DRV8825
#define Z_DRIVER_TYPE  DRV8825
//#define X2_DRIVER_TYPE DRV8825
//#define Y2_DRIVER_TYPE DRV8825
//#define Z2_DRIVER_TYPE DRV8825
//#define Z3_DRIVER_TYPE DRV8825
#define E0_DRIVER_TYPE DRV8825
#define E1_DRIVER_TYPE DRV8825
//#define E2_DRIVER_TYPE DRV8825
//#define E3_DRIVER_TYPE DRV8825
//#define E4_DRIVER_TYPE DRV8825
//#define E5_DRIVER_TYPE DRV8825

**Comment by TomTom076** [comment]
Hi!
Yes COREX. And there was also a wiring error! Z2 is moving.
Thanks!
