### ISSUE TITLE
[FR] requesting information on fade height

### ISSUE THREAD

**Issue by leytanelectronics2** [MarlinFirmware/Marlin#14220]
I have been struggling to find any useful information on what the fade height is for my printer, I am using the anet a8 running on marlin 1.1.9 (i think) using the ramps 1.4 control board.

During the last few prints, I've done the first 1cm of the print comes out very irregular and lumpy on the outside like it's extruding more material than I programmed. 

While looking at the menu items I came across the fade height option which was set at 10, does this setting have anything to do with the first centimeter of my prints coming out over extruded or am I looking in the wrong place?

**Comment by RudyBenner** [comment]
![image](https://user-images.githubusercontent.com/40361032/59011351-6c4fec00-8802-11e9-995e-f96696de5368.png)

**Comment by RudyBenner** [comment]
I would suggest setting fad height to zero to see what the resultant change is.
M420 S1 Z0

**Comment by Vertabreak** [comment]
Fade tapers off the bed leveling over the set # in mm allowing the printers hardware to take over without mesh compensation at the set height.

**Comment by Vertabreak** [comment]
@boelle i answered this should be safe to close.
