### ISSUE TITLE
[Bugfix 2.0.x] AKLP Delta Auto Calibration Probing Fail Marlin bugfix 2.0.x

### ISSUE THREAD

**Issue by OutspokenPlanet** [MarlinFirmware/Marlin#14226]
### Description

Delta Auto Calibration Probing Fail

### Steps to Reproduce

1. Home all (G28)
2. Start Auto Calibration (G33)

**Expected behavior:** Run through several iterations of bed probing

**Actual behavior:** Runs first iteration no issue, second iteration probe near centre of bed ok, then fails at approx 4mm height at the X tower and reports STOW PROBE, which then is followed by PROBING FAILED

I've tried this on the original Trigorilla board and also a BigTreeTech SKR 1.3, both produce the same outcome

[AKLP config files.zip](https://github.com/MarlinFirmware/Marlin/files/3257464/AKLP.config.files.zip)

**Comment by maxarchx** [comment]
Same issue, you fixed it?

**Comment by GrgaPalcic** [comment]
Same issue, you fixed it?

**Comment by pkoller** [comment]
Same issue, how to fix it?

**Comment by OutspokenPlanet** [comment]
The fix seemed to be to make sure a decimal number is used in the delta section i.e. the delta height, delta radius etc.
