### ISSUE TITLE
[BUG] [BUG 2.0.x ] (Last stepper.h halt my Delta) bug after "Improve LV8729 stepping (#13776)"

### ISSUE THREAD

**Issue by dzieva** [MarlinFirmware/Marlin#14221]
### Description
My delta stopped moving properly, the steps got very slow and caught.
This happens with the MKS-SBASE with one more stepper (LV8729)
Since commit #13776
### Steps to Reproduce

Steeper.h has something wrong on line 168, but I also commented line 158 for prediction. now works as expected.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

Please correct module stepper.h
![Stepper h](https://user-images.githubusercontent.com/35209392/58905108-60b7d480-86df-11e9-9dd1-4a03a81ce464.JPG)

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by shitcreek** [comment]
What exactly do you mean by 'with one more stepper'? Are all your drivers LV8792? or just one? Please clarify.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
@dzieva is this still a problem?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
