### ISSUE TITLE
[BUG] TMC2130 not moving

### ISSUE THREAD

**Issue by phm07** [MarlinFirmware/Marlin#14242]
I recently bought some BigTreeTech TMC2130 drivers. I intended to use them in SPI mode, but they where pre-configured, so I had to use them in standalone mode. They didn't seem to work and they had some other issues so I decided to buy Fysetc TMC2130 V1.2 drivers which come in SPI mode by default. I installed them and wired the SPI connection (see picture below). They have the same issue as the old BigTreeTech drivers, instead of moving the stepper motors just stall, altough the new drivers don't make such a loud sound. Here you can see a video: https://www.youtube.com/watch?v=hKeMzUkRHCY
They are wired like this: http://puu.sh/DDgro/e5ab3b6d2f.jpg

M122 gives me the following result:
```
SENDING:M122
		X	Y	Z
Enabled		false	false	false
Set current	800	800	800
RMS current	795	795	795
MAX current	1121	1121	1121
Run current	25/31	25/31	25/31
Hold current	12/31	12/31	12/31
CS actual		12/31	12/31	12/31
PWM scale	0	0	0
vsense		1=.18	1=.18	1=.18
stealthChop	false	false	false
msteps		16	16	16
tstep		max	max	max
pwm
threshold		0	0	0
[mm/s]		-	-	-
OT prewarn	false	false	false
off time		3	3	3
blank time	24	24	24
hysteresis
-end		-1	-1	-1
-start		1	1	1
Stallguard thrs	0	0	0
DRVSTATUS	X	Y	Z
stallguard
sg_result		0	0	0
fsactive
stst		X	X	X
olb		X	X	X
ola		X	X	X
s2gb
s2ga
otpw
ot
Driver registers:
		X	0xE0:0C:00:00
		Y	0xE0:0C:00:00
		Z	0xE0:0C:00:00
Testing X connection... OK
Testing Y connection... OK
Testing Z connection... OK
>>> g28 Y
SENDING:G28 Y
echo:busy: processing
echo:busy: processing
Error:Printer halted. kill() called!
[ERROR] Error:Printer halted. kill() called!
```

My configuration:
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3268581/Configuration.zip)

**Comment by Patag** [comment]
Sounds like stepper cable issue. Depending on the steppers, cables may differ. I experienced this kind of issue.

**Comment by phm07** [comment]
The wiring of the steppers is 2B 2A 1A 1B, just like with the A4988s

**Comment by Patag** [comment]
Check (via wires colors) if it comply with stepper/board connections.

**Comment by phm07** [comment]
I still have the problem

**Comment by phm07** [comment]
In some tutorials I saw people soldering those little solder pads on the underside together like this: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH4VugYm4p5k7LBaZm4tEJnJ-Ng0Rp3OTxX0e6pGQ2WpS-F59LxA

The left solder pad came disconnected from factory, but the little ones on the right aren't soldered together at all. I'm not sure whether to connect them at all because I'm afraid to destroy something with my bad soldering skills and I'm not even sure if this is causing the problem. I read that this is only neccessary to enable StallGuard2 (which I don't need).

**Comment by kAdonis** [comment]
Your SPI connection is working so no need to solder. Your M122 shows ola and olb, which means: open load detected. This could be a cable issue or a false warning, but in your configuration,h you have:
```cpp
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 634, 638, 3170, 765 } 
```
these values are very high, are you sure you used 1/16 microsteps before?
if the video in the first post is from your printer, I would try this values
```cpp
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 400, 765 }
```

**Comment by phm07** [comment]
I changed my default steps/mm, but that didn't change anything. The stalling only was a bit quieter (you almost can't hear it anymore). I think the problem is the detected open load. This is really weird since the printer has worked perfectly before and the only thing I did was swapping the A4899 drivers and changing the options in the firmware.

**Comment by phm07** [comment]
I think I solved the problem. I soldered these little bridges (CFG4 to GND, CFG5 to VIO) on the y axis, and after that the y axis started working like intended. However the z axis also started working, but the x axis didnt. I soldered the bridges on the x axis and then it started working, too. The crosses at ola and olb partly disappeared. Thank you for your help!
