### ISSUE TITLE
[FR] RPW-Ultra thermistor table

### ISSUE THREAD

**Issue by VanessaE** [MarlinFirmware/Marlin#14258]
This is not actually a feature request.

Because I use an older firmware version, I am not confident that a proper fork/Pull Request would work out, so this is basically a "Please merge the following changes, I know they work" request.   As code goes, this change is trivial.

The RPW-Ultra hotend by Reifsnyder Precision Works comes with an unknown brand of 100k/NTC thermistor, due to an upstream vendor error.  As one might imagine, none of Marlin's existing tables work for it, though a couple come somewhat close.

So, since the thermistor works and is predictable, it doesn't make sense to replace it.  Since the manufacturer has a lot of them on-hand, it is likely that future RPW-Ultras will come with the same one.  Therefore, I've made a new table from scratch to match it.

Calibration methodology (warning!  bad science ahead! :grin:):

* Using a PeakMeter PM6501 with included thermocouple probe
* RPW-Ultra hotend, installed as part of a normal, production setup, with thermistor screwed into the upper thermistor hole; heat block is not insulated
* thermocouple probe inserted into the Allen socket hole of the grub screw in the hotend's secondary thermistor hole (I didn't have a suitable wrench to remove it)
* thermocouple oriented to get the hottest possible reading
* meter placed on my desk, propped upright, a few feet away from the hotend, with the thermocouple wire feeding through a slit in the printer's enclosure
* desk fan positioned to blow across it to prevent local heat build-up
* printer enclosure doors removed.
* Recorded ADC readings for 30° through 270° in 10° steps
  * Commanded printer to heat up to to somewhere close to the desired temperature, by guessing
  * tweak set temperature up/down a little at a time, until the printer's reading stops oscillating, and  thermocouple remains to within about ±0.2° of the desired temperature (well, until I got above 199.9°, beyond which my meter reads only in 1° increments).
* calculated resistances from the ADC readings for 30°, 150°, and 250° using `R = 4700 * ADC / (1024 - ADC)`
* plugged those resistance/temperature pairs into a Steinhart-Hart table generator
* double-checked the generated table against my recorded measurements
* flashed the firmware with the new table added and selected, and checked a few temperatures to make sure the printer's readings match the thermocouple after sufficient settling time.

The table below is the generated one, since it is a very close match to my recorded values.

For what it's worth, I chose 502 here because RPW-Ultra used to be known as the genuine J-head 12, but was re-branded, and it was originally supposed to use thermistor type 5 like previous J-head hotend models, if not for the above-mentioned upstream vendor error.

[tables/code deleted, see #14517]

**Comment by AnHardt** [comment]
Nice. Methodology seems to be correct.
The table could be a tiny bit better if the ADCvalues would have 2 or 3 decimals. (The OV(x) values are multiplied by 16 and become integers thereafter.)

**Comment by VanessaE** [comment]
For whatever reason, the generator (a spreadsheet I grabbed from Thingiverse) only used integers.  Or maybe I did something wrong.  Still seemed to work okay. :-)

**Comment by AnHardt** [comment]
How about https://www.thingiverse.com/thing:3300383 ?

**Comment by VanessaE** [comment]
That one just gives an empty page when I tell it to generate a table.  I guess something about it isn't LibreOffice compatible.  Just to make sure I did it right:  
![image](https://user-images.githubusercontent.com/1733537/59218348-1080bc80-8b8e-11e9-9acd-d6635a56b3f2.png)
(note: it says "R (ohm)" on cell `I1`, but the after-loading presets in the spaces below it are clearly kOhms, so that's what I used, just as with [the original spreadsheet](https://www.thingiverse.com/thing:103668), though stating the values in ohms makes no difference)

**Comment by InsanityAutomation** [comment]
I'll have to try it in a recent libreoffice version and see what happens. Iirc when I updated that spreadsheet for marlin 2.0 formatting I used Excel 2016.

**Comment by VanessaE** [comment]
As an aside, I think this should be renumbered to 512 instead of 502 (think "should be type 5, on a J-head 12").

**Comment by VanessaE** [comment]
@InsanityAutomation  did you ever fix that spreadsheet?

**Comment by VanessaE** [comment]
I guess further discussion should be directed to the pull request.
