### ISSUE TITLE
[BUG] Axis Max out with Print Pause

### ISSUE THREAD

**Issue by CAP1Sup** [MarlinFirmware/Marlin#14255]
My Y axis maxed out after parking. This is due to my home position on the Y axis being 5, not 0. The park position is set to 0, 0 because I forgot to change it. An error needs to be added so that park positions may not be outside of the printing area.

**Comment by ManuelMcLure** [comment]
Usually if your Y endstop is to the left of the bed, you set ``Y_MIN_POS`` to a negative number so your home position (front left corner of the bed) is 0,0. This makes your printer coordinates match your slicer coordinates and avoids a lot of problems down the road, such as this one.

**Comment by CAP1Sup** [comment]
Yeah, the problem is that the nozzle sits 5 mm in on the bed when it hits the endstop. Therefore, in order to prevent future occurrences, it would be nice to have an error in place.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
