### ISSUE TITLE
[BUG] LCD games should respect reversed direction input devices

### ISSUE THREAD

**Issue by pinchies** [MarlinFirmware/Marlin#14259]
The games don't respect the set option for printers with reverse direction inputs, so the controls are backwards.

e.g. Fix for Invaders game: multiply encoderPosition by (1-2*ui.encoderDirection)

    // Update Cannon Position
    int16_t ep = int16_t((1-2*ui.encoderDirection)*ui.encoderPosition);
    ep = constrain(ep, 0, (LCD_PIXEL_WIDTH - (CANNON_W)) / (CANNON_VEL));
    ui.encoderPosition = (1-2*ui.encoderDirection)*ep;

https://github.com/pinchies/Marlin/commit/bccb2ac72e26085787dedc7d2c9a9903668c6a82#diff-4f26cb56f12a074a344c2db8bf3b5fae

**Comment by shitcreek** [comment]
@thinkyhead

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by pinchies** [comment]
I posted the fix but I don’t know if it has been integrated? @thinkyhead

**Comment by boelle** [comment]
did you submit a PR?

**Comment by pinchies** [comment]
No... simply because I thought maybe my code was probably clunky and there would be a simple fix. The diff was supposed to show the way I did it, but I was confident that maybe somebody would use it to make a more efficient method.

**Comment by boelle** [comment]
but i think thinkyhead will pick up on this soon

**Comment by pinchies** [comment]
Thanks Bo. I imagine this is the lowest of the low in terms of priorities... 👍

**Comment by boelle** [comment]
yep and i'm just sweaping the floor :-)

**Comment by boelle** [comment]
@pinchies is the issue still there?

**Comment by pinchies** [comment]
I don't know sorry, I haven't been keeping up. Lets remove it for now. Thanks Bo.

**Comment by boelle** [comment]
oki doke, we can always reopen later if we need
