### ISSUE TITLE
Autotune don´t work

### ISSUE THREAD

**Issue by arnold-b** [MarlinFirmware/Marlin#14266]
Marlin Bugfix 2.0

Hello, 

if i try Autotune i always get alert "Termal Runaway" when heating reach first time the temperature. 

Hotend 12V50W 
Test Temp: 220 Degree

If i use 200 degree for autotune, then i get Temperature to high. The temperature is jumping from 195 degree up to 222 degree. before i used 20W without problem.  
The temperature is jumping during 1 sec from 195 to 222 or back. Losing 25 degree in 1 sec is physical  impossible. 

Increasing SOFT_PWM_SCALE also dont change anything. 
For me it looks like pwm is not realy working.  I will check tomorrow with scope

**Comment by Phr3d13** [comment]
Loose connections along the thermistor path can also cause this effect. Have you ruled that out already?

**Comment by arnold-b** [comment]
Hey, thanks. 
i used one plug for everything. after i used direct line for NTC, it worked normal.
