### ISSUE TITLE
Temp_sensor_0 13 cause Segementation Fault in M115.cpp

### ISSUE THREAD

**Issue by arnold-b** [MarlinFirmware/Marlin#14268]
Marlin 2.0 Bugfix
Hello, 

if i try to use TEMP_SENSOR_0 13 i get Segmentation fault in M115.cpp 32:3

**Comment by Phr3d13** [comment]
Can you provide the information requested in the template you deleted?

**Comment by arnold-b** [comment]
after i deleted the temp. files  of the compiler manualy it worked
