### ISSUE TITLE
[BUG] No TMC2208 connection on SKR v1.3

### ISSUE THREAD

**Issue by KoffeinKaio** [MarlinFirmware/Marlin#14274]
### Description

After removing the jumpers under the Steppers and inserting the UART jumper, TMC2208 is still recognized as "ALL LOW"

### Steps to Reproduce

1: Get TMC2208
2: Solder bridge for UART to PDM pin
3: remove jumper between stepper pins on the SKR1.3 board (not sure about that)
4: insert jumper on UART pins for axis
5: insert stepper driver
6: boot up (assuming all configuration in FW is set)

**Expected behavior:** [What you expect to happen]
UART Connection made

**Actual behavior:** [What actually happens]
UART Connection ALL LOW

#### Additional Information

FW Configuration:
@platformio.ini: env_default = LPC1768
```
  #define MOTHERBOARD BOARD_BIGTREE_SKR_V1_3 
  #define X_DRIVER_TYPE  TMC2208
  #define Y_DRIVER_TYPE  TMC2208
  #define Z_DRIVER_TYPE  TMC2208
```

Picture of stepper:
https://frupic.frubar.net/shots/38178.jpg

Picture of board:
https://frupic.frubar.net/shots/38177.jpg

**Comment by gloomyandy** [comment]
Are you sure that you have modified the driver boards correctly? In particular with the drivers you are using you may need to bridge the the two centre pins together (I can't see this bridge in your photo) as well as applying the solder bridge to enable UART use. Make sure that you are powering the board from a 12v/24v supply not from USB (from your photo it looks like you have the jumper set to USB).

Given the very many people using this combination (including myself) with Marlin it is very unlikely that there is a bug in Marlin causing your problem. Make sure you are using the latest version of Marlin (not the bigtreetech version), make sure that your platformio install is up to date and that all of the libraries have been updated. 

You will probably get better help for this specific issue from the bigtreetech facebook group or other online forums.

**Comment by marvelous240** [comment]
Not a bug.

**Comment by KoffeinKaio** [comment]
True sorry all.
I followed a guide which said "you need to short the bridge but not the nc pin on skr 1.3 boards"
As soon as I tested this, it worked. Thank you guys!

**Comment by Tollbringer** [comment]
@KoffeinKaio  Do you mind clarifying what you did exactly to correct? I have SKR v1.3 w/ 2208's (v3.0).
a.) do I need to solder under each driver for UART mode? (I was told shorting pins 1-2 on the SKR board was the same as the very difficult solder).
b.) Do I need to have any external jumper wires.

EDIT : Confirmed. With Steppers connected and External 24V/12v supply - NO SOLDERING required!
Use jumper on pins 1-2 under the stepper, drivers are now in UART mode! works with v3.0 drivers on SKR v1.3. I can not confirm any other configuration.

![stealth_chop_2208v3](https://user-images.githubusercontent.com/44956412/64925750-5d92b100-d7c3-11e9-88bb-8c96a6b730ba.jpg)


Thank you.

**Comment by theuncle** [comment]
@SirRedZ I'm in the same scenario but I can't get UART to work .
Can you be more specific in which  'Use jumper on pins 1-2 under the stepper' pins are ?

**Comment by Tollbringer** [comment]
I apologize.  I WISH I had taken a picture, but I believe this is the correct way to do it.
![SKR 1v3](https://user-images.githubusercontent.com/44956412/65379692-211af580-dc9a-11e9-940a-52613a724182.png)

I am not 100%, as my board is burried and installed/hidden so I can not verify.

**Comment by Tollbringer** [comment]
Note: Powering up without steppers/endstops (using internal +5v)  connected it reported no stealth. When I finished install I was happy to see It had worked as expected.

**Comment by NinDTendo** [comment]
@Tollbringer could you provide more information please?
I have the same setup ( skr 1.3 & tmc2208 v3.0 ), but I can't get it working as u did.

**Comment by Tollbringer** [comment]
@Nin-D-Tendo 

This was new to me but I don't mind trying to help. Do you feel the issue might be your firmware?

If so, I have included my Ender 3 - SKRv1.3 // 2208 v3.0 (jumpered on mainboard no solder)
This was my 1st time ever compiling Marlin 2.0x

Let me know if this helps you.

[-=SrZ=-]

[SKR 1.3 + TMC 2208v3_Ender3.zip](https://github.com/MarlinFirmware/Marlin/files/3904655/SKR.1.3.%2B.TMC.2208v3_Ender3.zip)
