### ISSUE TITLE
TMC2100 gets very hot

### ISSUE THREAD

**Issue by computerguy096** [MarlinFirmware/Marlin#14277]
Hi everyone,

I'm in a little bit of trouble here. I just purchased two TMC2100 SilentStepSticks from FYSETC to replace my loud A4988s on my RAMPS 1.4 board (X and Y axis) and while they work absolutely fine (set to spreadCycle w/interpolation), they get very hot along with their steppers that they are controlling. So hot in fact that after a few minutes of printing, I can't touch the steppers, and I know something is seriously wrong here.

To try solving this issue, I grabbed a lab power supply with a current meter, set it to 12V, hooked it up to my RAMPS and started moving one of my axis in Repetier. I noticed that while moving the current stays at 0.2A @12V (across the whole RAMPS, not related to Vref), which is okay, but if it stays idle (no movement) it draws almost 1A @12V !!! (that's 12 watts wasted on a single stepper, which is nuts).

Important things to mention:
- everything is set up for 1/16 microstepping (no jumpers under driver, adjusted speed in firmware, wired CFG1 and CFG2 on driver)
- I have Marlin 1.1.0 RC8 (latest stable release)
- Vref was set at 1.0V on both drivers
- my printer is self made, very similar to Prusa i3

Here are the steppers that I am using for all my axis: 
http://silnikikrokowe.pl/SX17-1005LQCEFdsen.pdf

Maybe they are not compatible with my RAMPS or my steppers ?

Any help would be appreciated, I've never worked with Trinamic drivers.

**Comment by shitcreek** [comment]
I'd suggest migrating to bugfix 2.0 (beta? version coming soon?) as it has many improvements and new features added which might have addressed this issue.  Marlin 1.1.0 is no longer worked on.

Also, have you seen this video? https://www.youtube.com/watch?v=c3v9E1AwDBE

That said: this Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
