### ISSUE TITLE
Tmc2208 uart mode driver based on stm32f407xxx board

### ISSUE THREAD

**Issue by yangwenxiong** [MarlinFirmware/Marlin#14293]
### Description

On stm32f407xxx board, has anyone debugged the uart mode of tmc2208? How to add software uart driver?

**Comment by teemuatlut** [comment]
Mainly the only prerequisite is a working SoftwareSerial library that follows the same API as Arduino AVR.

**Comment by yangwenxiong** [comment]
@teemuatlut  Do you have SoftwareSerial library ?

**Comment by teemuatlut** [comment]
No. The SoftwareSerial libraries are provided by each platform framework.

**Comment by yangwenxiong** [comment]
Debugging successfully
