### ISSUE TITLE
[BUG] Redundant sensor no longer work in latest bugfix2.0-fix

### ISSUE THREAD

**Issue by timmmoore** [MarlinFirmware/Marlin#14305]
### Description

If you enable redundant temp sensors in configuration.h. You get MSG_ERR_REDUNDANT_TEMP message as soon as marlin starts

### Steps to Reproduce

1. Set up configuration.h with redundant sensors
2. compile and load

**Expected behavior:** [What you expect to happen]
Works, sensors report similar value

**Actual behavior:** [What actually happens]
kill message as soon as marlin starts

#### Additional Information
The issue seems to be 2 fold:
1. in temperature.h and temperature.cpp
redundant temp reading uses temp_hotend struct array when reading ADC, this is sized by HOTENDS which is 1, so uses past end of array when reading temp_sensor_1.
2. In readings_ready() when the .acc accumulator for the ADC are reset for the sensors, temp_sensor_1 is not reset if it is a redundant sensor.

I think the problem was introduction as part of PR 12201.
I have code changes that works , if you want a push request

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/3294445/config.zip)

**Comment by thinkyhead** [comment]
The fix seems sound. Will merge it soon!
