### ISSUE TITLE
[BUG] Print waits on 'resume print' before beginning

### ISSUE THREAD

**Issue by shitcreek** [MarlinFirmware/Marlin#14331]
### Description

Latest commit initiates SD card automatically and loads up Auto0.g but waits until you press 'Resume print' before executing

UPDATE: The same thing happens when I start a print job. It will only display the name and does nothing else.

### Steps to Reproduce

1. Get latest Bugfix 2.0
2. Boot up with SD card containing auto0.g file inserted OR start a print
3. See 'auto0.g' | job name displayed

**Expected behavior:** Auto0.g executes as expected

**Actual behavior:** Nothing happens until 'Resume print'

#### Additional Information

CR-10s with default config

**Comment by brisma** [comment]
I also confirm this bug.

**Comment by just-jason** [comment]
Yes,I have the same problem

**Comment by robbycandra** [comment]
Confirmed, its from PR #14236 .

**Comment by shitcreek** [comment]
UPDATE: Scott's just patched the bug. 
https://github.com/MarlinFirmware/Marlin/commit/5ef105b2b06f2bdc82da25e858a3c374d3250c2c
