### ISSUE TITLE
[BUG] Thermal runaway protection does not seem to be working, at least when printer is not printing?

### ISSUE THREAD

**Issue by JunctionRunner** [MarlinFirmware/Marlin#14334]
Hello, so I've been trying to test marlins thermal runaway protection, however for some reason it seems to not be working, and I'm not sure if that's because the printer is not actively printing or because I perhaps didn't enable it properly.

Basically, I set the bed temperature to 60 degrees and held a hair dryer close to the center, and the temperature got up to 68 but did not trigger however this was very slow.

 I then set my bed temp to 25 and did the same and it rose rapidly, up to 47 before I stopped, and it still did not trigger a thermal runaway, this rise happened within 20 seconds.

I can't get the code insertion to work properly, so here are links to my configuration.h and configuration_advanced.h files. It looks like the threshold is 4 degrees within 20 or 40 seconds.

https://pastebin.com/FSfSrm0d
https://pastebin.com/Hjz12pRp

I'm running version 1.1.9, and everything else seems to work fine in regards to the temperature readout and control, I'm just not sure why this isn't triggering a shutdown.

I'm running on an Anet A8 Plus with the version 1.7 board. I do have octoprint hooked up but I don't see why that would interfere with this functionality.  I've definitely kept the temperature well above the target for over 40 seconds and it still doesn't trigger.

The only thing I can think of is that it mentions it has preset safe temperatures, so maybe the runaway temperature is something much higher, but then it doesn't make sense that it's looking for the current set temperature and has a set offset at which it will trigger.

**Comment by AnHardt** [comment]
That was worked on. Please try bugfix-2.0.x

**Comment by JunctionRunner** [comment]
Alright, I'll give that a shot, hopefully the setup isn't too different to the older version, probably forgotten a couple small details for my printer lol.

**Comment by XOIIO** [comment]
Ok, so slight issue, previously I had to set the bed's temp sensor as 99 for it to work, but in the new version if I set the bed temperature to 99 I get this error output when trying to upload.

Arduino: 1.8.9 (Windows 10), Board: "Anet V1.0 (Optiboot)"

In file included from sketch\src\inc/MarlinConfigPre.h:32:0,

                 from sketch\src\inc/MarlinConfig.h:28,

                 from sketch\src\Marlin.h:24,

                 from sketch\src\Marlin.cpp:31:

sketch\src\module/thermistor/thermistors.h:147:22: error: 'temptable_99' was not declared in this scope

 #define _TT_NAME(_N) temptable_ ## _N

                      ^

c:\users\xoiio\appdata\local\temp\arduino_build_869958\sketch\src\core\macros.h:189:37: note: in definition of macro 'COUNT'

 #define COUNT(a)            (sizeof(a)/sizeof(*a))

                                     ^

sketch\src\module/thermistor/thermistors.h:148:21: note: in expansion of macro '_TT_NAME'

 #define TT_NAME(_N) _TT_NAME(_N)

                     ^

sketch\src\module/thermistor/thermistors.h:211:25: note: in expansion of macro 'TT_NAME'

   #define BED_TEMPTABLE TT_NAME(THERMISTORBED)

                         ^

sketch\src\module/thermistor/thermistors.h:212:35: note: in expansion of macro 'BED_TEMPTABLE'

   #define BED_TEMPTABLE_LEN COUNT(BED_TEMPTABLE)

                                   ^

sketch\src\module/thermistor/thermistors.h:233:11: note: in expansion of macro 'BED_TEMPTABLE_LEN'

   &&      BED_TEMPTABLE_LEN < 256 &&  CHAMBER_TEMPTABLE_LEN < 256,

           ^

sketch\src\module/thermistor/thermistors.h:147:22: error: 'temptable_99' was not declared in this scope

 #define _TT_NAME(_N) temptable_ ## _N

                      ^

c:\users\xoiio\appdata\local\temp\arduino_build_869958\sketch\src\core\macros.h:189:48: note: in definition of macro 'COUNT'

 #define COUNT(a)            (sizeof(a)/sizeof(*a))

                                                ^

sketch\src\module/thermistor/thermistors.h:148:21: note: in expansion of macro '_TT_NAME'

 #define TT_NAME(_N) _TT_NAME(_N)

                     ^

sketch\src\module/thermistor/thermistors.h:211:25: note: in expansion of macro 'TT_NAME'

   #define BED_TEMPTABLE TT_NAME(THERMISTORBED)

                         ^

sketch\src\module/thermistor/thermistors.h:212:35: note: in expansion of macro 'BED_TEMPTABLE'

   #define BED_TEMPTABLE_LEN COUNT(BED_TEMPTABLE)

                                   ^

sketch\src\module/thermistor/thermistors.h:233:11: note: in expansion of macro 'BED_TEMPTABLE_LEN'

   &&      BED_TEMPTABLE_LEN < 256 &&  CHAMBER_TEMPTABLE_LEN < 256,

           ^

exit status 1
Error compiling for board Anet V1.0 (Optiboot).

**Comment by JunctionRunner** [comment]
Ok so problem with marlin 2.0, I've set the settings the same, temps and whatnot work, but homing is screwed up.

all of my end stops are set up as minimum, so x minimum, y minimum, and a bltouch.

I have to invert a couple of my motor directions and on malrin 1,1.9 everything works perfect.

#define INVERT_X_DIR true
#define INVERT_Y_DIR false
#define INVERT_Z_DIR true

#define X_HOME_DIR -1
#define Y_HOME_DIR -1
#define Z_HOME_DIR -1


the problem is when I set this up in 2.0 bugfix, my manual controls work the right way, but my x and y home in the wrong direction, opposite to the manual controls, but they work the right way if I un-invert the manual controls.

I can't change the home directions as everything is set up as minimum stops and it throws a bunch of errors.

Not sure if I should submit this as a new issue or leave it just in here?

**Comment by JunctionRunner** [comment]
Ah, apparently I had inverted the endstops for the old config that's probably what's going on.

**Comment by JunctionRunner** [comment]
Alright seems good, I'll be able to update in hopefully around 14 hours on this, can't use a hair dryer at this sort of hour.

**Comment by JunctionRunner** [comment]
Well, gave it a try and still doesn't give an error when the bed temp changes by a fair margin when it's not actively printing.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
@XOIIO is this still an issue?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
