### ISSUE TITLE
[FR] Anycubic Trigorilla 1.1 mainboard pin definitions

### ISSUE THREAD

**Issue by arkhnchul** [MarlinFirmware/Marlin#14343]
new 1.1 revision of Trigorilla 8-bit AVR boards found in Anycubic printers have servo pins different from boards with no marked revision, which use RAMPS pins and have predefined board named TRIGORILLA14 in both Marlin branches.
1.1 designations: 
S0 - pin 5
S1 - pin 4
S2 - pin 11
S3 - pin 6

more details here:
https://github.com/MNieddu91/Marlin-AI3M-BLTouch/wiki/Changes-for-Trigorilla-1.1
https://github.com/MNieddu91/Marlin-AI3M-BLTouch/commit/2b4c936c1a479911b7cf25a99fce4dabfcc3c7c5

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/14357.

**Comment by thisiskeithb** [comment]
This has been merged, so you can now use `BOARD_TRIGORILLA_14_11` for the 1.4, Rev 1.1 board.

**Comment by boelle** [comment]
closing this as the support has been added by @thisiskeithb
