### ISSUE TITLE
What requirements need to be met to add printer to example_configurations

### ISSUE THREAD

**Issue by avluis** [MarlinFirmware/Marlin#1436]
As per the title, is it a minimal configuration changes or all you need to be compatible while not breaking codebase?
Are we restricted to pins.h (and now the accompanying board pin file) and Configuration.h or can we modify more than that?

**Comment by thinkyhead** [comment]
The `example_configurations` folder is fine for any and all standardized printers, which have known dimensions and components. The `pins.h`, `pins_MYBOARD.h`, and `boards.h` files together deal with unique _boards_ that have different pins.

So, please DO submit example configurations.

And, while it's fine to submit new entries for the boards and pins, right now the only reason to do this for a RAMPS-based printer (for example) is to provide a name string for the LCD display. Soon, however, this will not require an entry in `pins.h`. We'll be able to do that in Configuration.h. So some of the `pins_MYBOARD.h` files will probably end up going away. I am assuming, of course, that other Marlin collaborators agree with me on this matter!
