### ISSUE TITLE
[BUG] Anycubic Kossel - Homing/Printing Issue

### ISSUE THREAD

**Issue by joshuajava** [MarlinFirmware/Marlin#14360]
Printer was working fine until a few days ago when I went into delta settings and lowered the delta height to save myself from babystepping Z each print. I lowered it my about 1mm. 

Now if I do anything with the printer (homing, leveling, print file) the printer either fails to home, or hits the endstops fine, goes down a bit, then back up, then down etc. 

I checked the board and reattached all wires but still the same problems happen. I've been slowly going crazy for days trying to fix this or at least figure out what's wrong. 

I should mention that I attempted to power my raspberry pi from the printer's power supply by adding a y-splitter cable, and although I couldn't get that working, the printer was working fine for a few days after I did it. The problems all started immediately after I lowered the delta height. 

I tried re-uploading the Marlin config. to the printer, but get strange errors. I think they might show exactly what the problem is, but I'm not familiar with all this enough to know, but I'm sure someone here is. 

It's a linear plus model printer. 

Most of the errors in Marlin seem to have something to do with Y. 

This Marlin config upload worked fine a few weeks ago with no errors at all, but now there are so many errors, all from the config. adv. file, which I never even touched. 

Here are some of the errors given:

sketch\Configuration.h:1124:38: note: in expansion of macro 'DELTA_PRINTABLE_RADIUS'

   #define FRONT_PROBE_BED_POSITION -(DELTA_PRINTABLE_RADIUS -(MIN_PROBE_EDGE))

                                      ^

sketch\SanityCheck.h:554:13: note: in expansion of macro 'FRONT_PROBE_BED_POSITION'

       #elif FRONT_PROBE_BED_POSITION < MIN_PROBE_Y

             ^

Configuration.h:550:34: error: floating constant in preprocessor expression

   #define DELTA_PRINTABLE_RADIUS 110.0 // mm. DaHai: From Anycubic Kossle source

                                  ^

sketch\Configuration.h:974:21: note: in expansion of macro 'DELTA_PRINTABLE_RADIUS'

 #define Y_MIN_POS -(DELTA_PRINTABLE_RADIUS)

                     ^

sketch\Conditionals_post.h:708:25: note: in expansion of macro 'Y_MIN_POS'

     #define MIN_PROBE_Y Y_MIN_POS

                         ^

sketch\SanityCheck.h:554:40: note: in expansion of macro 'MIN_PROBE_Y'

       #elif FRONT_PROBE_BED_POSITION < MIN_PROBE_Y

                                        ^

Configuration.h:550:34: error: floating constant in preprocessor expression

   #define DELTA_PRINTABLE_RADIUS 110.0 // mm. DaHai: From Anycubic Kossle source

                                  ^

sketch\Configuration.h:1125:35: note: in expansion of macro 'DELTA_PRINTABLE_RADIUS'

   #define BACK_PROBE_BED_POSITION DELTA_PRINTABLE_RADIUS -(MIN_PROBE_EDGE)

                                   ^

sketch\SanityCheck.h:556:13: note: in expansion of macro 'BACK_PROBE_BED_POSITION'

       #elif BACK_PROBE_BED_POSITION > MAX_PROBE_Y

             ^

Configuration.h:550:34: error: floating constant in preprocessor expression

   #define DELTA_PRINTABLE_RADIUS 110.0 // mm. DaHai: From Anycubic Kossle source

                                  ^

sketch\Configuration.h:977:19: note: in expansion of macro 'DELTA_PRINTABLE_RADIUS'

 #define Y_MAX_POS DELTA_PRINTABLE_RADIUS

                   ^

sketch\Conditionals_post.h:709:25: note: in expansion of macro 'Y_MAX_POS'

     #define MAX_PROBE_Y Y_MAX_POS

                         ^

sketch\SanityCheck.h:556:39: note: in expansion of macro 'MAX_PROBE_Y'

       #elif BACK_PROBE_BED_POSITION > MAX_PROBE_Y

                                       ^

exit status 1
missing binary operator before token "("

Anyone???

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
@joshuajava is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
