### ISSUE TITLE
[BUG] [bugfix-2.0.x] Probing infos on LCD incorrectly shown

### ISSUE THREAD

**Issue by Bergerac56** [MarlinFirmware/Marlin#14364]
When building a UBL mesh (MKS SBASE with Graphic LCD) the last line of the LCD shows the probing point position xxx/xxx (right end of the last line)

There is an issue when going above point 99. The last digit does not appear.

Before 99
![mini-IMG_20190622_144828](https://user-images.githubusercontent.com/27892880/59964364-f638ce00-94ff-11e9-9e8a-e5a1a952546d.jpg)

And when reaching 100:
![mini-IMG_20190622_145131](https://user-images.githubusercontent.com/27892880/59964366-00f36300-9500-11e9-84d4-61465ed995b7.jpg)

Obviously the last digit would have to be 4 (111/144 and not 111/14 )

A M117 followed by a string long enough to fill the full line is correctly displayed

Mainly a cosmetic issue but...

**Comment by boelle** [comment]
@Bergerac56 i assume this has not been fixed?

**Comment by Bergerac56** [comment]
@boelle Correct ;). It is still there. Not really an issue but not clean...

**Comment by Bergerac56** [comment]
It has been solved by the last bugfix version
