### ISSUE TITLE
[BUG] #define Z_SAFE_HOMING +  #define HOMING_BACKOFF_MM == G28 will crash nozzle.

### ISSUE THREAD

**Issue by forthereg** [MarlinFirmware/Marlin#14379]
Will keep it as short as i can :
#define Z_SAFE_HOMING  is set to probe middle of the bed ( works wonderful).
#define HOMING_BACKOFF_MM  set to move the nozzle to the middle after XY home ( works fine).
I have to Do a XY home and then a Z home afterwards desperately. this works fine.

But if i give it a G28 , It will XY home-> move probe to middle [ for Z safe home] --> do a Z probing in the middle, and then do a  ( HOMING_BACKOFF ) , which is a diagonal "move to the middle" even tho its already in the middle.

this will crash the nozzle into opposite sides of x0y0.  it will not even respect bed limits. 

so G28 needs an update in the middle ? or an absolute positioning for [ HOMING_BACKOFF] ?

thank you for everything you've done and continue to do so   <3 <3 <3 

Edit : ( so G28 will combine the XY movement of Zsafehome & HomingBackOff , incase i wasnt clear)

**Comment by BigIronGuru** [comment]
True, I just tested it

**Comment by AnHardt** [comment]
For me this is looking like a misunderstanding of what HOMING_BACKOFF_MM does or is meant for.
For me HOMING_BACKOFF_MM is to free the endstops by a few steps or 1/10mm. Just enough to free the (normal) endspops and or give the TMC sensorless endstops some room to accelerate before the steppers hammer the carriages against the limits again (they do need some speed to reliably detect the stall). The software endstops are set at the back upped place by purpose to avoid the hardware endstops are triggering before the software endstops.
Backing of to the middle of the bed does not make any sense to me. At least not with HOMING_BACKOFF_MM.

**Comment by BigIronGuru** [comment]
I fixed it. Do we want a PR on this?

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by forthereg** [comment]
Thank you . So once again , this will do a homing backoff  AFTER the move to middle of bed for Z probe home.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3439000/Configuration.zip)

**Comment by FanDjango** [comment]
I confirm that the described behaviour (**a homing backoff AFTER the move to middle of bed**) happens.

But according to @AnHardt this is not a problem because it **is looking like a misunderstanding of what HOMING_BACKOFF_MM does or is meant for**. 

Either disallow such a combination in the sanity check then, or maybe fix the code (it is a small change only).

**Comment by forthereg** [comment]
True, I imagine its just a matter of changing the move commands from relative to absolute. But then again i dont know much about marlin code.
But i will say having the nozzle always rest in the middle is a super nice feature for me as my cables are highly strained  at max/min :)

**Comment by InsanityAutomation** [comment]
My first thought for a change is to move the homing backoff into the actual homing command for an individual axis so it happens right after the switch is triggered. Maybe somewhere around line 1601 at the end of the homeaxis function in G28. For z this should check probe values to see if the raise for the probe is higher than the backoff and use the greatest number.

**Comment by InsanityAutomation** [comment]
Can you test with the above PR @forthereg ?

@AnHardt im reading that as the home bump function where this is more of post home clearance. Regardless, I think this positioning for the code is more correct.

**Comment by thinkyhead** [comment]
Question is whether to allow for deltas to back off on individual towers (or if this is needed) for the benefit of sensorless homing, etc. Current code assumes the back-off on Delta will only apply to Z, and like the others, backs off only at the end (currently also redundant if using the safe zone). The new PR could allow for deltas to back off the towers individually, and I think this would not harm delta homing, but the three backoff values must match or it breaks delta positioning (so perhaps on delta only use the Z setting and ignore X and Y).

**Comment by thinkyhead** [comment]
Question settled, and PR merged.

**Comment by InsanityAutomation** [comment]
Now that the dust has settled, care to test with a current snapshot @forthereg ?

**Comment by Roxy-3D** [comment]
> Question is whether to allow for deltas to back off on individual towers 

Huh?   Of course a Delta should be able to back off any tower it thinks makes sense.

**Comment by InsanityAutomation** [comment]
At this point if OP doesnt get back to us, based on whats been done id call this closed.

**Comment by forthereg** [comment]
Im sorry for my total noobness but i dont even know what PR means ! is it the current built/ fork ?
I tried the current download marlin 2.0.x  if that is the one you are asking.
the issue is resolved but now its acting broken in another way  :D 
Before it did a X - Y home  then a quick diagonal dash to homing back-off location. ( as it should)
i have quick Home BTW.
now  X clicks ,  and then a X Backoff (with  HOMING_BUMP_DIVISOR still applied) . then goes back to finishing Y home , and then Y backoff with  Y HOMING_BUMP_DIVISOR still applied.  ( taking its sweet time again ) .
But im glad to report the primary issue was solved .
just correct feedrate on backoff and maybe have the backoffs as in one move if possible as oppose to one by one, thank you.
wish i could have shown you a video :)

**Comment by forthereg** [comment]
The feedrate issue seems to go away if printer is given a move command Before homing.
But if first command after turn on is a home command then it will do this (which i cant even wrap my head around ) .
actually you can call this closed if you like. i will just use a separate g code after my home commands.  this reminds me of the old saying that you fix a bug and it creates 3 superbugs

**Comment by InsanityAutomation** [comment]
Reapplying the feedrate is an easy one. I'll try to remember to get it this weekend. As for backing off multiple together, that was breaking the feature on idex. If feedrate is fixed so it's a fraction of a second, shouldn't be a concern anymore.

**Comment by InsanityAutomation** [comment]
FYI, I made it back around to the feedrate adjustment for the backoff and thats merged now.

**Comment by boelle** [comment]
this one should be fixed by now and will close

can always reopen it if it should not be the case

**Comment by forthereg** [comment]
thank you Sir ... Sirs
