### ISSUE TITLE
TMC2208 MKS Gen v1.4 compiling error

### ISSUE THREAD

**Issue by andreashb2** [MarlinFirmware/Marlin#14374]
ERROR: "TMC2208 on Z2 requires Z2_HARDWARE_SERIAL or Z2_SERIAL_(RX|TX)_PIN." when compiling. Makes it impossible to use TMC2208 in UART mode with dual z-axis and mks gen v1.4

### Steps to Reproduce
1.#define MOTHERBOARD BOARD_MKS_GEN_13
2. #define Z2_DRIVER_TYPE TMC2208
3. #define Z_DUAL_STEPPER_DRIVERS
4. #define Z2_SERIAL_TX_PIN 58
#define Z2_SERIAL_RX_PIN 57
OR
4. #define Z2_HARDWARE_SERIAL Serial1

**Expected behavior:**
Should compile just fine

**Actual behavior:**

Error when compiling

Added conf, conf_adv, pins_ramps, pins_mks
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3317201/Marlin.zip)

**Comment by teemuatlut** [comment]
Built fine when I just tried it with up to date bugfix-2.0.x.
Maybe someone else can verify.

**Comment by Ludy87** [comment]
the same as @teemuatlut

**Comment by andreashb2** [comment]
Reinstalled Atom.io. Started with a new clean marlin file. Worked. Solved!
