### ISSUE TITLE
[BUG] U8g Error

### ISSUE THREAD

**Issue by SkuterGaming** [MarlinFirmware/Marlin#14382]
**Help!**

[Marlin 2.0]  When I try install: "RepRapDiscount Full Graphic Smart Controller",
 shows me a error:
" [.pioenvs\LPC1768\src\src\HAL\HAL_LPC1768\u8g\u8g_com_HAL_LPC1768_st7920_hw_spi.cpp.o] Error 1 "

u8glib is already install

**What to do ?**

**Comment by gloomyandy** [comment]
I think you need to post the full output around that error for anyone to be able to help.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

and yes full output

**Comment by boelle** [comment]
@SkuterGaming is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
