### ISSUE TITLE
[BUG] Error compiling for LPC1768

### ISSUE THREAD

**Issue by rmcbc** [MarlinFirmware/Marlin#14389]
### Description

After adding "https://github.com/mikeshub/SailfishLCD.git" in platformio gives an error:

SailfishLCD/SailfishLCD.h:91:10: fatal error: avr/pgmspace.h: No such file or directory

*** Temporary workarround

Remove "https://github.com/mikeshub/SailfishLCD.git" from lib_deps of LPC1768

**Comment by thisiskeithb** [comment]
~~Try changing it to https://github.com/mikeshub/SailfishLCD/archive/master.zip.~~

Edit: I just re-compiled with https://github.com/mikeshub/SailfishLCD.git and it worked. Are your libraries are up to date?

**Comment by rmcbc** [comment]
I use PlaformIO and it's the latest version with all libraries needed updated.
My config files:
[Firmware.zip](https://github.com/MarlinFirmware/Marlin/files/3320736/Firmware.zip)

**Comment by ghost** [comment]
I have been reverting that commit since yesterday and also reported this in the commit comments because I have the same problem for LPC1768.

**Comment by ghost** [comment]
Hmm, maybe I did something wrong but it compiles here (with your config and platformio.ini @rmcbc ) .  

Looking at this commit tho :  
https://github.com/mikeshub/SailfishLCD/commit/e35d62cfcf84b1b0541971dd9aedc91bf7d5cb65  

Make sure your libs are up-to-date ;) ( platformio home > left-side tabs > libraries > updates , or just delete the sailfish lib in your marlin folder and clean / rebuild)

**Comment by kAdonis** [comment]
I can confirm its working now, after updating libraries

**Comment by spilz87** [comment]
I had the same problem, it was solved after uninstall sailfishlcd library and let it install it automatically when compiling.
