### ISSUE TITLE
[FR] M281 not documented

### ISSUE THREAD

**Issue by Reywas62** [MarlinFirmware/Marlin#14392]
Add M281 description in the configuration.h file above #define EDITABLE_SERVO_ANGLES and also in the Marlin website gcode list.

**Comment by RudyBenner** [comment]
gcode.h has a bit of info

**Comment by sjasonsmith** [comment]
I see the following text in Configuration.h:
`// Edit servo angles with M281 and save to EEPROM with M500`

This seems adequate to me. It directs the user to the command number, and they can look it up in the GCode reference.
