### ISSUE TITLE
[BUG] fan and heat bed works together

### ISSUE THREAD

**Issue by barisyalcinfree** [MarlinFirmware/Marlin#14404]
Hello everyone. i have marlin on arduino mega with ramps 1,4. the problem is when i open the fan heat bed starts heating automaticly while printing or none. i send m106 code on pronterface bed start to heating up to 100 degrees and more. Never stops. Please help.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3326765/Marlin.zip)

**Comment by boelle** [comment]
@barisyalcinfree is the issue still there?

**Comment by barisyalcinfree** [comment]
Yes. İ connected fans external power supply    
And on print setting im closing cooling

**Comment by boelle** [comment]
have you checked that everything is connected correct?


![image](https://user-images.githubusercontent.com/3832239/65535887-97ba2c00-df02-11e9-8269-d65c668551ae.png)


its for the snappy but its good enough, you can disregard the MAX switches

**Comment by barisyalcinfree** [comment]
Yes same connection

**Comment by boelle** [comment]
your ramps pins file is not the one from https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/ramps/pins_RAMPS.h

where did you get marlin from?

**Comment by boelle** [comment]
and the beginning of configuration.h does not look like the start of https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/Configuration.h they should be the same down to line ~40

**Comment by boelle** [comment]
given that its most likely not marlin firmware, but a clone i will close this one

we cant do support on other than marlin downloaded from here
