### ISSUE TITLE
[BUG] Z_PROBE_LOW_POINT and height after homing (bugfix-2.0)

### ISSUE THREAD

**Issue by V1pr** [MarlinFirmware/Marlin#14406]
### Description

Auto bed leveling fails with "Probe failed" if Z_PROBE_LOW_POINT is set to too low (e.g. -5 in my case; -15 works). Homeing works ok, but after homeing my Z is raised to 12 (that is as expected)

Probing is a Geeetech 3D touch. Homeing works ok with it.

### Steps to Reproduce

Set Z_PROBE_LOW_POINT to lower value than Z (auto) height after homeing.

**Expected behavior:** Z_PROBE_LOW_POINT should be relative to zero, not to the starting height (when ABL started)

**Actual behavior:** after homeing Z is set to 12 in my case, then when I start ABL it fails on the first probe point (ABL_3POINT) if Z_PROBE_LOW_POINT is set to too low value (e.g.: -5)

#### Additional Information

Working config (set Z_PROBE_LOW_POINT to -5 to reproduce):
[Marlin-config.zip](https://github.com/MarlinFirmware/Marlin/files/3327347/Marlin-config.zip)

(other config files not changed)

**Comment by boelle** [comment]
@V1pr is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
