### ISSUE TITLE
Marlin 2.0 Mighty board Digipot not working

### ISSUE THREAD

**Issue by brotherchris** [MarlinFirmware/Marlin#14409]
### Description

Changing the digipot values in configuration_adv.h doesn't seem to make a difference. 

### Steps to Reproduce

Compile with might board and change values for voltage. 

I would expect the motor current to ramp up or down when I change it. 

Nothing changes when I change the values. 

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3327890/Marlin.zip)

**Comment by shitcreek** [comment]
Are you sure your stepper drivers even support digipot? If it does, maybe it is using EEPROM in which case you can reset to factory with M502 then save with M500 or set your or set with M906 or M907 then save with M500.

That said, this Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on this page.) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org Marlin Forum
Tom's 3D Forums
Facebook Group "Marlin Firmware"
Facebook Group "Marlin Firmware for 3D Printers"
Marlin Configuration on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.
