### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1441]
been away for a while.... what is the status @MarlinFirmware/collaborators  ?

**Comment by thinkyhead** [comment]
Welcome back. With March approaching it seems a good time to think about the first milestone. Bugs have been fixed here and there, and generally the codebase is feeling more solid every day.

Lots of interesting changes have been happening, including new German language options, full support for 4 extruders, contributions for BQ printer models (RAMPS-based), the breakup of pins.h, and most recently I took a first crack at cleaning up `process_commands` and moving Gcode handlers into their own functions, with a PR in the queue.
