### ISSUE TITLE
[BUG] Printer pauses starting a print (2.0 bugfix)

### ISSUE THREAD

**Issue by blueeagle69** [MarlinFirmware/Marlin#14427]
When starting a print from SD Card (https://github.com/MarlinFirmware/Marlin/issues/6164)

Printer pauses immediately when starting an SD card print, and won't start until I hit resume.

**Expected behavior:** Print should start

**Actual behavior:** Printer pauses and waits for me to select Resume Print. Also when I am in the new Print dialogue screen (2.0 bugfix), the encoder on my Smart Discount Graphic LCD is backwards despite going the correct way everywhere else.

**Comment by thisiskeithb** [comment]
The pause bug may have been reintroduced in https://github.com/MarlinFirmware/Marlin/commit/ce656e2a268a120ccef77a7d80cc5c1c4fcc7f7e. Does Marlin from https://github.com/MarlinFirmware/Marlin/commit/decfe3424fa4975ed9315feaa98ad7b56e719f4d work? [Download link](https://github.com/MarlinFirmware/Marlin/archive/decfe3424fa4975ed9315feaa98ad7b56e719f4d.zip).

You may need to comment/uncomment `#define REVERSE_MENU_DIRECTION` in`Configuration.h`.

Posting your configs would help troubleshoot further.

**Comment by InsanityAutomation** [comment]
@thisiskeithb with whats there I dont see how that could possibly contribute to this kind of bug. A few timer lines in a rarely used function and the z probe end script subcommand processing wouldnt touch anything near this.

**Comment by reloxx13** [comment]
post the gcode file to be sure there is no pause comand in it

**Comment by JimGWIn** [comment]
I am also having this issue. I have to click once to activate the menu and then click resume.

[Z_endstop_adj v1_SSR_Cover_.txt](https://github.com/MarlinFirmware/Marlin/files/3339731/Z_endstop_adj.v1_SSR_Cover_.txt)

**Comment by blueeagle69** [comment]
Here's my gcode, if you need it.
It's not the gcode, it was fine on 1.1.9

[Calibration Cube.zip](https://github.com/MarlinFirmware/Marlin/files/3340926/Calibration.Cube.zip)

**Comment by blueeagle69** [comment]
With https://github.com/MarlinFirmware/Marlin/commit/decfe3424fa4975ed9315feaa98ad7b56e719f4d it appears that the pausing before a print has been fixed.
However the reversed encoder options still persist in the new Start Print dialogue.
If I un-comment #define REVERSE_MENU_DIRECTION then the Start Print dialogue is now correct, but the main menus are backwards.
I also have #define REVERSE_ENCODER_DIRECTION un-commented, because if I don't then value changing is backwards.
I'm using a Discount Full Graphic LCD on my SKR 1.3
I'll just live with the Start Print dialog etc. backwards.
It isn't hard to remember to move the dial left to move right etc.
It's no big thing tbh.
But I have attached my configuration files just in case.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3341239/Marlin.zip)

**Comment by blueeagle69** [comment]
Okay scratch that, there is still a random pause before starting an SD card print with  decfe34.
I have Advanced Pause enabled. The printer randomly triggers it after starting a print.
Weirdly though, it doesn't do it all the time. Sometimes it will start a print as expected. Other times it will trigger the advanced pause and eject my filament.

**Comment by boelle** [comment]
@blueeagle69 is the issue still there?

**Comment by JimGWIn** [comment]
No the issue is solved Sent from my Samsung Galaxy smartphone.

**Comment by boelle** [comment]
i will close then, we can always reopen
