### ISSUE TITLE
[BUG] power loss recovery Z axis jumps up 1CM from print after re-homing

### ISSUE THREAD

**Issue by leytanelectronics2** [MarlinFirmware/Marlin#14449]
I have had the power loss recovery option activated in my copy of marlin V1.1but when it re_homes and goes to continue the print head jumps up 1CM from the actual print before continuing, anyone got any theories as to why this is happening and any options on how to fix this?

and if this issue has been solved already please link the solution to me.

this is an example from youtube that shows my current problem. https://www.youtube.com/watch?v=Z7xMlFywO8Q

**Comment by boelle** [comment]
Please test with the [`bugfix-2.0.x` branch](https://github.com/
MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) so we're all on the same
page here. That branch contains all the latest patches.

**Comment by boelle** [comment]
@leytanelectronics2 is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
