### ISSUE TITLE
[BUG] temperature.h

### ISSUE THREAD

**Issue by RudyBenner** [MarlinFirmware/Marlin#14442]
New behaviour This is with the default config files.

![image](https://user-images.githubusercontent.com/40361032/60376125-bdef2f00-99da-11e9-872f-bed7e8980933.png)

Way past my pay grade.

**Comment by klcjr89** [comment]
Bug is fixed now: https://github.com/MarlinFirmware/Marlin/commit/c9a8db33c34d69ea8d10893b76b30f2445c37977
