### ISSUE TITLE
[BUG] Marlin\src\core\../module/temperature.h:476:17: error: 'fs' was not declared in this scope

### ISSUE THREAD

**Issue by Glod76** [MarlinFirmware/Marlin#14443]
Marlin\src\core\../module/temperature.h:476:17: error: 'fs' 
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3341255/Marlin.zip)
was not declared in this scope

**Comment by klcjr89** [comment]
I have this issue too! I can't build the firmware due to all of the fan code changes that occurred today. I hope this is resolved quickly :)

**Comment by Glod76** [comment]
Same

**Comment by RudyBenner** [comment]
Reported a while ago #14442

**Comment by klcjr89** [comment]
> Reported a while ago #14442

All the more reason to squash it today :)

@thinkyhead

**Comment by klcjr89** [comment]
Bug is fixed now: https://github.com/MarlinFirmware/Marlin/commit/c9a8db33c34d69ea8d10893b76b30f2445c37977

**Comment by boelle** [comment]
closing as c9a8db3 seems to fix the issue, can always reopen
