### ISSUE TITLE
[BUG] Loop in configuration

### ISSUE THREAD

**Issue by RudyBenner** [MarlinFirmware/Marlin#14450]
For a few hours, since I suspect the platformio.ini update, strange things have been happening. .pioenv fills up with folders for every one of the selections. I don't even know how to describe this.

deleted C:\Users\RudolfBenner\.platformio and the marlin folder.

VSCode, although Marlin-Conf also has the same problem.

rudy

**Comment by RudyBenner** [comment]
![image](https://user-images.githubusercontent.com/40361032/60389662-e25b1200-9a93-11e9-9bec-cceb079bcaa9.png)

**Comment by thisiskeithb** [comment]
Does it compile successfully if you change `default_envs` to `env_default` in `platformio.ini`?

There was a change to that file 16 hours ago: https://github.com/MarlinFirmware/Marlin/commit/6550a222aab41d31c7338cd4f5bfc27427110fab.

**Comment by RudyBenner** [comment]
tried that, no joy.

**Comment by RudyBenner** [comment]
Is it working for you?

**Comment by RudyBenner** [comment]
right now, it is unusable.

**Comment by RudyBenner** [comment]
**Fixed. Your suggestion** was the logical choice, what I missed was the extra spaces on the previous lines.

![image](https://user-images.githubusercontent.com/40361032/60390711-bdbe6480-9aaa-11e9-988f-cbe04bc5632d.png)

**Comment by RudyBenner** [comment]
Bug needs fixing yet.

**Comment by RudyBenner** [comment]
I will leave my patch until it gets fixed.
