### ISSUE TITLE
[BUG] Now LCD unresponsive with SKR1.3 and TMC2209 UART during print

### ISSUE THREAD

**Issue by han9988** [MarlinFirmware/Marlin#14462]
### Description

With the libraries updates between 28. and 30. June the LCD (REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER) has become unresponsive with SKR1.3 and TMC2209 UART during print
Disconnected TFT and disabled SERIAL_PORT_2 but no luck.
Encoder move lag 15 sec or display simply reverts to default screen. The more moves in a layer the more unresponsive is the display

**Comment by BioGeekJoey** [comment]
I noticed this in the 15-ish seconds after the system rebooted, encoder clicks would do nothing. Haven't tried during prints.

**Comment by PKav89** [comment]
Did you solve the issue?
