### ISSUE TITLE
[FR] Individual Stealthchop activation on TMC2130 for each Axis

### ISSUE THREAD

**Issue by Massa0815** [MarlinFirmware/Marlin#14477]
### Description
Regarding TMC2130 in Configuration_adv.h

#define STEALTHCHOP

I want to setup Stealtchop or Spreadcycle for every axis individually.

I had some problems with losing stepps at the Z axis. Now i need to aktivate spreadcycle for Z Axis permanently.

**Comment by thisiskeithb** [comment]
This is can be done with `M569` - [Set TMC stepping mode](http://marlinfw.org/docs/gcode/M569.html).

Example to disable StealthChop on Z (use spreadCycle): `M569 S0 Z`

Note: `bugfix-2.0` allows you to define each axis individually through `Configuration_adv.h`:
```c++
  /**
   * TMC2130, TMC2160, TMC2208, TMC2209, TMC5130 and TMC5160 only
   * Use Trinamic's ultra quiet stepping mode.
   * When disabled, Marlin will use spreadCycle stepping mode.
   */
  #define STEALTHCHOP_XY
  #define STEALTHCHOP_Z
  #define STEALTHCHOP_E
```

**Comment by sjasonsmith** [comment]
This is already selectable as @thisiskeithb mentioned. It seems unlikely that separating X/Y is actually useful in configuration files. That would be very strange to enable it on X but not Y, for example.

Right now this seems addressed, so I will close this.
