### ISSUE TITLE
Modify Marlin for a new driver

### ISSUE THREAD

**Issue by Dps8** [MarlinFirmware/Marlin#14475]
Hi, I want to add a new driver to Marlin. First of all, I need to know how to do it. Second I am using recycled Epson printer drivers, so the signals change a lot, I need to know where I should modify so that using the common signals dir, enable, step introduce functions that work with the pins of these drivers. Also I must use more pins so I need to distribute the references to drivers and use those that are free on the Arduino.
In case you were wondering why I do not use the regular deivers. Well the answer is simple, I live in Cuba and I do not have access to these. But I have access to old electronic equipment (like printers) and of course I have the Arduino

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support or how-to questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
