### ISSUE TITLE
[BUG] [Marlin 2.0] Running M504 causes Filament Runout distance to jump to 500mm

### ISSUE THREAD

**Issue by NovaViper** [MarlinFirmware/Marlin#14476]
### Description
I notice that whenever I use M504 to check my EEPROM configuration to Marlin (since I just updated my SKR V1.3 to the very latest commit of Marlin, c9be936) it sets my FILAMENT_RUNOUT_DISTANCE_MM value to 500 mm, instead of my 25mm. I'm currently running Marlin 2.0

### Steps to Reproduce

1. Enable Filament runout and all subsequent required definitiions, ensure to have FILAMENT_RUNOUT_DISTANCE_MM defined too
2. Turn on the printer and plug into Octoprint/Pronterface
3. To get original value, first run M412
4. Run M504 to check EEPROM
5. Run M412, notice how the distance is completely different from the original we flashed

**Expected behavior:** My set settings not modified

**Actual behavior:** My settings, specifically my filament runout distance it changed

#### Additional Information

[MyMarlinConfig.zip](https://github.com/MarlinFirmware/Marlin/files/3348273/Marlin.zip)
Picture of what happens:
![image](https://user-images.githubusercontent.com/7191115/60482558-a2448c80-9c57-11e9-8dfd-c4d20b257c6b.png)

**Comment by marcio-ao** [comment]
Confirmed this bug. Will investigate.

**Comment by marcio-ao** [comment]
@NovaViper: I pushed a fix for this as a PR #14661. Thank you for your bug report.
