### ISSUE TITLE
Editable menu-items with longer descriptions do not fit on screen while editing - on graphical displays.

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#1447]
While editing the values on a DOGM-display a larger font is used, Due to that, for longer descriptions, text and value overlap.

Possible fixes in lcd_implementation_drawedit() in dogm_lcd_implementation.h:
a) Use the normal font. (will save 3012 bytes)
b) Split screen in 2 lines. ( will still allow only 13 characters, may use some additional bytes ) (but i don't need my glasses)

Any opinions?
Will fix it myself.

**Comment by thinkyhead** [comment]
I would like to see the difference, if you have a chance to post pictures. Otherwise, the Normal font _sounds_ like a better option!

**Comment by AnHardt** [comment]
Now:
![picture 24](https://cloud.githubusercontent.com/assets/211931/5992248/7f8cec14-aa21-11e4-96bd-0c2470ac9249.jpg)
![picture 25](https://cloud.githubusercontent.com/assets/211931/5992250/8517c226-aa21-11e4-82b1-6511ff3d2235.jpg)

**Comment by AnHardt** [comment]
Fix type a):
![picture 29](https://cloud.githubusercontent.com/assets/211931/5992281/c2e0020c-aa22-11e4-91ac-a41d450223ef.jpg)
![picture 30](https://cloud.githubusercontent.com/assets/211931/5992287/fd6c1104-aa22-11e4-921d-67f4e84fd1b5.jpg)

**Comment by AnHardt** [comment]
Fix type b):
![picture 32](https://cloud.githubusercontent.com/assets/211931/5992306/2b0c9cd6-aa24-11e4-97b3-bec509050803.jpg)
![picture 33](https://cloud.githubusercontent.com/assets/211931/5992307/300dd434-aa24-11e4-9625-5e4ab7c67bc8.jpg)

**Comment by thinkyhead** [comment]
Is it possible to detect if the line will (potentially) overlap, and then use the smaller font only in that case? That would make it self-adapting to user language preferences.

**Comment by AnHardt** [comment]
When i thought about centering i discovered that a simple strlen() does not work. Guess that the special characters are represented by two bytes. Have to investigate this.

**Comment by thinkyhead** [comment]
@AnHardt 

```
int my_strlen_utf8_c(char *s) {
   int i = 0, j = 0;
   while (s[i]) {
     if ((s[i] & 0xc0) != 0x80) j++;
     i++;
   }
   return j;
}
```

**Comment by AnHardt** [comment]
@thinkyhead 
Discovered the problem - me. Should have used strlen_P(). Results have been a bit random :-).
Autoadaption is on its way.

**Comment by AnHardt** [comment]
Impressions from the test-branch.
![picture 41](https://cloud.githubusercontent.com/assets/211931/6022388/adeb52b6-abbc-11e4-8432-dca77b22a0bb.jpg)
![picture 42](https://cloud.githubusercontent.com/assets/211931/6022394/b3452494-abbc-11e4-8faf-6688fb436c7d.jpg)
![picture 43](https://cloud.githubusercontent.com/assets/211931/6022404/c18db002-abbc-11e4-9231-1861949fc25b.jpg)
![picture 44](https://cloud.githubusercontent.com/assets/211931/6022407/c9fb730a-abbc-11e4-8958-bac0978f52de.jpg)
![picture 45](https://cloud.githubusercontent.com/assets/211931/6022411/d29cdc56-abbc-11e4-88d3-8ab9aa6b0960.jpg)
![picture 46](https://cloud.githubusercontent.com/assets/211931/6022414/d7e497a8-abbc-11e4-949b-0e6d4bf12513.jpg)
![picture 47](https://cloud.githubusercontent.com/assets/211931/6022420/df1409c8-abbc-11e4-9dc9-24ba163d45a7.jpg)
![picture 48](https://cloud.githubusercontent.com/assets/211931/6022421/e5c0ca2c-abbc-11e4-8dcf-38723172ede8.jpg)
![picture 49](https://cloud.githubusercontent.com/assets/211931/6022426/ed7c9e08-abbc-11e4-976a-24262ec9c379.jpg)
![picture 51](https://cloud.githubusercontent.com/assets/211931/6022440/0727b19e-abbd-11e4-87e9-ac4c9131568d.jpg)
![picture 52](https://cloud.githubusercontent.com/assets/211931/6022442/0c7d07a2-abbd-11e4-9602-40e0b7eba36e.jpg)
17 is the limit for a 3 digit value
![picture 53](https://cloud.githubusercontent.com/assets/211931/6022444/15fd8086-abbd-11e4-82ca-1539acbe2a51.jpg)
As before. No chance for the thermometer. But picture at least proves - working with different length of values.
![picture 54](https://cloud.githubusercontent.com/assets/211931/6022448/2269bc5e-abbd-11e4-874e-828ae7eb9e7e.jpg)

**Comment by AnHardt** [comment]
Thermometer workaround with some spaces.
![picture 55](https://cloud.githubusercontent.com/assets/211931/6022980/1c060b8e-abc1-11e4-9fa4-faf8abd500e1.jpg)

**Comment by thinkyhead** [comment]
Wow, yeah, that looks about perfect!
