### ISSUE TITLE
[BUG] SCARA Z axis movement does not work

### ISSUE THREAD

**Issue by svsergo** [MarlinFirmware/Marlin#14481]
Description
I am using Marlin 2.0 with SCARA type configuration with Pronterface to send the commands. When sending the Z command home, the stepper motor runs very slowly, about 1 pulse per second. After a short time, the program ends with an accident. The X and Y move commands work correctly. Pressing Home X or Home Y individually the Z stepper motor starts running at a slow speed and everything ends with a program crash. When you download the configuration default (no SCARA), all axes are working fine.
I changed all parameters in Configuration.h according to my SCARA robot:
•	MAKERARM_SCARA
•	SCARA_LINKAGE_1, SCARA_LINKAGE_2
•	SCARA_OFFSET_X, SCARA_OFFSET_Y
•	LIMIT SWITCH PLUGS
•	ENDSTOPPULLUPS
•	DEFAULT_AXIS_STEPS_PER_UNIT
•	HOMING DIRECTION
•	Bed size
Steps to Reproduce
1.	Use SCARA (MAKERARM) configuration
2.	Try to home with limit switch configuration as X_MAX, Y_MAX
3.	Pressing Home X or Home Y individually the Z stepper motor starts running at a slow speed and everything ends with a program crash.
I tried this same configuration on 1.1 and it worked great on there.

**Comment by thinkyhead** [comment]
Sorry about that. `MAKERARM_SCARA` is not supported and will soon be removed.

**Comment by svsergo** [comment]
Configuration MORGAN_SCARA, the error persists. Will MORGAN_SCARA support continue?

**Comment by svsergo** [comment]
Anyone have a working configuration MORGAN_SCARA?

**Comment by svsergo** [comment]
In the module planner.cpp  line 2691 when is enabled  #define SCALE_FEEDRATE_SCALING not taken into account the movement in the Z-axis, so the feedrate=0. If you disable #define SCALE_FEEDRATE_SCALING, returns home along the Z-axis works.

**Comment by boelle** [comment]
@svsergo is the issue still there?

**Comment by svsergo** [comment]
Yes there is. For myself, I decided to add zero control. It may not be right, but it works.
feedrate = (HYPOT(delta[A_AXIS] - position_float[A_AXIS], delta[B_AXIS] - position_float[B_AXIS]) * duration_recip > 0) ? HYPOT(delta[A_AXIS] - position_float[A_AXIS], delta[B_AXIS] - position_float[B_AXIS]) * duration_recip : fr_mm_s;

**Comment by boelle** [comment]
@svsergo is the issue still there? please test with latest 2.0.x

**Comment by svsergo** [comment]
I will check after the reconstruction of the mechanism is completed.

**Comment by boelle** [comment]
@svsergo is the reconstruct complte?

**Comment by svsergo** [comment]
Waiting for components from China.

**Comment by svsergo** [comment]
ENABLED #define SCALE_FEEDRATE_SCALING. Blocks motion  Z axis. In the new version, the error remained.

**Comment by boelle** [comment]
@svsergo since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by svsergo** [comment]
The result is the same.   In module "planner.cpp " line 2629 needs to be corrected :
```cpp
const feedRate_t feedrate = HYPOT(HYPOT(delta.a - position_float.a, delta.b - position_float.b), delta.z - position_float.z) * duration_recip;
```
The right solution that takes into account the movement of the three axes.

**Comment by boelle** [comment]
so from 
```cpp
const feedRate_t feedrate = HYPOT(delta.a - position_float.a, delta.b - position_float.b) * duration_recip;
```
to 
```cpp
const feedRate_t feedrate = HYPOT(HYPOT(delta.a - position_float.a, delta.b - position_float.b), delta.z - position_float.z) * duration_recip;
```
?

**Comment by boelle** [comment]
a PR made :-)
