### ISSUE TITLE
[FR] BigTreeTech SKR Pro v1.1

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#14484]
hello

request to add the BIGTREETECH SKR PRO V1.1
ARM cortex M4 32 bit
STM32F407ZGT6 MCU

https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1

merci

**Comment by govido** [comment]
I guess Bigtreetech will submit the changes needed as they advertise marlin 2.0 compatibility.
Yesterday the new E3 mini got merged from them, so I am looking forward to it.

**Comment by AnHardt** [comment]
> they advertise marlin 2.0 compatibility.

That doesn't mean anything to me. Doesn't the word advertisement say all you need to know?
I remember a well know Kickstarter announcing a new Marlin compatible probe.
No other single hardware item caused that deep changes in Marlins structure to make that "compatible" crap finally work. And worst - they continue to change their product, without a warning, to make it incompatible again.

Bigtreetechs history gives me some more hope.
Let's hope for the best.

**Comment by govido** [comment]
https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/firmware
;)
It is ready

**Comment by eightheads** [comment]
> https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/firmware
> ;)
> It is ready

Except they do not compile currently

**Comment by thisiskeithb** [comment]
There’s an [SKR Plus](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/blob/9d7eb10dc52165623bac6b6c841bac2e070e9606/firmware/stm32f407zgMarlin-bugfix-2.0.xV20190627-12864-5160SPI/Marlin/src/pins/pins_BIGTREE_SKR_PLUS_V1_0.h) pins file in there too. 

Wonder when BigTreeTech will announce that board.

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/14510, but it still doesn’t compile.

**Comment by yangwenxiong** [comment]
> See #14510, but it still doesn’t compile.

Are there any errors that can be sent out that I can help solve

**Comment by yangwenxiong** [comment]
@thinkyhead  Can help merge not

**Comment by Msq001** [comment]
#14510 this PR  was closed because of a conflict files. I will creat a new PR for this board， and https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/firmware this branch is work now， and Pay attention to the Readme.md

**Comment by govido** [comment]
As this board is completely new I didn't want to open a new issue directly.
The things I noticed so far (my board arrived yesterday):
- TMC2208 / 2209 are not working because software uart isn't supported yet 
- graphic lcd software spi isn't working (tested with fysetc mini 2.1)
- Neopixel is not supported, the library is ignored in platformIO config for this board
- emergency parser not implemented
- lots of pin definitions are missing in the pins file (LCDs, filament runot etc.)
- auto_fan_pin does not compile
- i2c oled display is working for now
- can configure software spi for tmc2130 (not tested yet)
- no option for internal sd card on stm32? or I overlooked an option...
- serial port 0 not working
- bltouch / servo not working 

not marlin related:
- the esp 01s port is not working over usb power (not enough current?), module works when powered seperately 

If I should test something let me know.
I have tmc2130, tmc2209 to play with, tft35, fysetc mini v2.1, bltouch

**Comment by Msq001** [comment]
https://github.com/MarlinFirmware/Marlin/pull/14543
1. this PR will support TMC2208/2209 uart mode
2. I have tested `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`(LCD12864) and `REPRAP_DISCOUNT_SMART_CONTROLLER`(LCD2004), They all work properly.
3. stm32 have not Serial port 0, it begin from Serial port 1
4. I have tested bltouch in `PA1` pins， it‘s ok.

I'll test your feedback one by one. Thank you very much!

**Comment by govido** [comment]
@Msq001
Nice,
I will take a look again at the terminal output while compiling. I got errors regarding display and bltouch, or they are coming from somewhere else...
If stm32 has no serial 0 there should be a comment added in configuration.h ;)

**Comment by govido** [comment]
@Msq001 
I tested the bltouch and fysetc options again.
I must have done something wrong in my first attempt, bltouch has no errors.
But the display throws this error right at the final compile stage...
```
Compiling .pioenvs\BIGTREE_SKR_PRO\src\src\sd\usb_flashdrive\lib\message.cpp.o
Compiling .pioenvs\BIGTREE_SKR_PRO\src\src\sd\usb_flashdrive\lib\parsetools.cpp.o
Compiling .pioenvs\BIGTREE_SKR_PRO\src\src\sd\usb_flashdrive\usb_host.cpp.o
Linking .pioenvs\BIGTREE_SKR_PRO\firmware.elf
.pioenvs/BIGTREE_SKR_PRO/src/src/lcd/dogm/u8g_dev_uc1701_mini12864_HAL.cpp.o:(.data.u8g_dev_uc1701_mini12864_HAL_2x_sw_spi+0x8): undefined reference to `u8g_com_HAL_AVR_sw_sp_fn(_u8g_t*, unsigned char, unsigned char, void*)'
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\BIGTREE_SKR_PRO\firmware.elf] Error 1 
```

**Comment by JPRauwolf** [comment]
With the new new version over at [https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1](hhttps://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1) they seem to got the tmc2208/2209 over uart working, at least it does compile. My RepRap display stopped working though so there is probably more to do.
Edit: broken link

**Comment by gerleimarci** [comment]
Please update the Neopixel library because Fysetc MINI12864 useless without it.

**Comment by yellobello** [comment]
Is it currently a better idea to use bigtreetech´s sources for the SKR Pro or use the current Marlin 2.0.x-bugfix Branch? maybe dev-2.1.x?
i.e. have the sources from Bigtreetech been merged already?

**Comment by thinkyhead** [comment]
> Please update the Neopixel library because Fysetc MINI12864 useless without it.

That project is at https://github.com/adafruit/Adafruit_NeoPixel

**Comment by thinkyhead** [comment]
> i.e. have the sources from Bigtreetech been merged already?

They periodically push updates here.

**Comment by Evg33** [comment]
SKR Pro and Neopixel demo: https://youtu.be/uGW9yKVrxyU

https://github.com/adafruit/Adafruit_NeoPixel/pull/206#issuecomment-531297764

**Comment by Evg33** [comment]
Now working with FYSETC_MINI_12864_2_1 

![image](https://user-images.githubusercontent.com/7160738/64887379-201e0e80-d671-11e9-81c5-ebf353b0c9b2.png)
![image](https://user-images.githubusercontent.com/7160738/64887385-244a2c00-d671-11e9-8d9e-7615431c7258.png)
![image](https://user-images.githubusercontent.com/7160738/64887503-6e331200-d671-11e9-9c28-2bd09bfcba31.png)

**Comment by Evg33** [comment]
fysetc 12864 mini merged https://github.com/MarlinFirmware/Marlin/commit/61e3f119f4791aa22af905e25c86f4a2a3753bc9

**Comment by Evg33** [comment]
neopixel PR: https://github.com/MarlinFirmware/Marlin/pull/15274

**Comment by Evg33** [comment]
Neopixel merged https://github.com/MarlinFirmware/Marlin/commit/12e0581f249d7aafb394a6b9ca511a9b5f337cba

**Comment by Romano26** [comment]
> Now working with FYSETC_MINI_12864_2_1
> 
> ![image](https://user-images.githubusercontent.com/7160738/64887379-201e0e80-d671-11e9-81c5-ebf353b0c9b2.png)
> ![image](https://user-images.githubusercontent.com/7160738/64887385-244a2c00-d671-11e9-8d9e-7615431c7258.png)
> ![image](https://user-images.githubusercontent.com/7160738/64887503-6e331200-d671-11e9-9c28-2bd09bfcba31.png)

Hello
you could send your files because I have the same configuration and I can not compile and I can not find the problem;
thank you

**Comment by LinoBarreca** [comment]
@boelle close this. it's already done.

**Comment by boelle** [comment]
done and thanks for the headsup

**Comment by boelle** [comment]
witch such a big list one man is almost not enough :-)
