### ISSUE TITLE
Menues on gaphical displays inconsistent

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#1448]
On DOGM-displays in all menues including SD-menu reversed text (white on black) is used to index the current line. But for editable menu-items '>' is used to indicate the current position and no highlighting.

Possible fix in _drawmenu_setting_edit_generic() in dogm_lcd_implementation.h:

step a: use the highligting code from lcd_implementation_drawmenu_generic() and _drawmenu_sd().
step b: introduce a function maybe 'highlight_current_menuitem()' and use it in the relevant functions.

Or maybe the other way around. Mark current menuitem with a '>' like on the character displays.

Any opinions?
Will fix it by myself.

**Comment by alexborro** [comment]
I think eu should be consistent. Highlight or > for all.

I prefer highlights because it saves space.

Cheers

Alex.
Em 01/02/2015 09:06, "Andreas Hardtung" notifications@github.com escreveu:

**Comment by AnHardt** [comment]
Now:
![picture 27](https://cloud.githubusercontent.com/assets/211931/5992255/bf788d74-aa21-11e4-9468-c5fac7c265dc.jpg)
![picture 28](https://cloud.githubusercontent.com/assets/211931/5992256/c667de32-aa21-11e4-8e97-0bc1637af36e.jpg)

**Comment by AnHardt** [comment]
Fix with highlighting:
![picture 34](https://cloud.githubusercontent.com/assets/211931/5992354/7bf9d4b8-aa26-11e4-9e09-85fd91e78f88.jpg)

**Comment by AnHardt** [comment]
@alexborro This will not save space on the display as implemented now. The space at the beginning of the line is used for the up-arrow used in the back-menu-item.
![picture 35](https://cloud.githubusercontent.com/assets/211931/5992377/9b2847b0-aa27-11e4-953f-a99b408b208f.jpg)
But this is redundant repeated at the end of the line.

If asked for i can remove this.

**Comment by thinkyhead** [comment]
I like more obvious highlighting, but we're used to **>** on character LCDs. Perhaps we should make it (yet another) configuration option. Users and vendors may have different preferences, eyesight issues, or whatever.

Looks like when highlighting in reverse the extra left column for **^** is redundant, so we could gain 2 characters in that situation. But menu item text still has to be shorter for the lowest common denominator, so nothing really is gained.

**Comment by AnHardt** [comment]
@thinkyhead It's absolutely no problem to use highlighting and '>' at the same time. I don't like the idea of making it configurable.  The length of the strings (max 17) is optimized for the 20xX character displays. We should not use the additional space without making a second string set. What I also don't want.

**Comment by thinkyhead** [comment]
@AnHardt Yes, exactly my point. Strings can't be longer without many additions. The language files actually did have LONG_ versions at one time, but they were unwieldy I guess and were removed.

**Comment by alexborro** [comment]
Sometimes we need to decide and go ahead. I vote for highlight and more
space.

Highlighting is a feature only available for graphic LCDs; that's the
reason we use > for other character display.

Almost all regular users are used to graphical user interface that uses
highlighting.

And I think highlighting an option make it more visible than > in all
cases.

Cheers

Alex.
Em 02/02/2015 07:49, "Scott Lahteine" notifications@github.com escreveu:

**Comment by AnHardt** [comment]
Fixed.
