### ISSUE TITLE
[BUG - 2.0.x bugfix] LPC1769 EEPROM values not loaded on boot

### ISSUE THREAD

**Issue by klcjr89** [MarlinFirmware/Marlin#14487]
Whatever code changes were made in the past 24 hours has broken the loading of EEPROM values on my Azteeg X5 mini board on boot.

Not sure why things have become more broken lately when it was pretty solid.

**Comment by thinkyhead** [comment]
Duplicate of #14470

**Comment by klcjr89** [comment]
This is still broken and I have no idea why.
