### ISSUE TITLE
[BUG] Anet A8 profile x/y offsets transposed

### ISSUE THREAD

**Issue by rigelhope** [MarlinFirmware/Marlin#14507]
In the sample configuration for the anet a8, X_MIN_POS and Y_MIN_POS offsets are transposed.

### Steps to Reproduce

1. upload marlin FW to anet a8 printer
2. autohome
3. start bed leveling, will begin on a a spot that is not on the bed, because the offsets are wrong.

**Comment by RudyBenner** [comment]
Works for me.

![image](https://user-images.githubusercontent.com/40361032/60690005-becc0900-9e91-11e9-8b62-8d3674e9964f.png)

**Comment by RudyBenner** [comment]
Since you did not provide any information, you will get nothing more.

**Comment by RudyBenner** [comment]
without supplying the required config files, you cannot expect more.

**Comment by rigelhope** [comment]
it's more of a nudge, so that people searching while aggravated because Y IT NOT WORK?!?! will get prompted to review those constants during the course of their troubleshooting.

~~the y-axis is, per the build/setup instructions, the stepper that drives the belt on the gantry~~, and it has the bigger offset between the x and y axes (i wound up adjusting it to -43 for my own purposes, and made the bed size smaller), so -33 is clearly the y offset, not the x. if you've transposed cables or something it will work, of course.

since the general recommendations with the Anet a8 are pretty universally to install marlin immediately so as to mitigate fire risk, some users may be unprepared for going over the configuration files with a fine toothed comb.

**Comment by ManuelMcLure** [comment]
Then the instructions are wrong. The Y axis is the one that moves the bed back and forth. The X axis is the one on the gantry. This was the case with my Anet A8 and is the case for all i3-style machines.

**Comment by ManuelMcLure** [comment]
Wait - is this an A8 (acrylic frame) or A8 Plus (aluminum extrusion frame)? These are very different printers even though they're both identified as "A8".

**Comment by ManuelMcLure** [comment]
https://www.china-gadgets.de/app/uploads/2016/11/A8-3D-Printer-Installation-Instructions-2016-6-30.pdf - shows the X motor on the gantry, not the Y motor.

**Comment by Patag** [comment]
@rigelhope 
I've been using an A8 (acrylic frame) for 6 months or so and I can confirm the X/Y_MIN_POS are correct (X=-33, Y=-10). Maybe your endstops are not fitted IAW instructions or you are talking about A8+ or you swapped X/Y wiring to steppers

**Comment by rigelhope** [comment]
yep, acrylic frame. reviewed instructions, i had them transposed. not sure how it happened but happened it did. closed.

**Comment by Patag** [comment]
Saying "Thanks" won't burn your mouth, knowing it's not a support site here.

**Comment by rigelhope** [comment]
Thanks!
