### ISSUE TITLE
[BUG] RADDS + ReprapDiscount Full Graphics Smart Controller shows blank LCD

### ISSUE THREAD

**Issue by ShadowOfTheDamn** [MarlinFirmware/Marlin#14557]
### Description

I have a DUE RADDS driver board.
trying to add a RepRap discount full graphic LCD without success.
please tell me if anymore information is needed or how I can use the hardware to help developers fix the issue.

### Steps to Reproduce

I made my own RADDS2LCD from the thingiverse link: https://www.thingiverse.com/thing:1740725
I only used the LCD ports from the RADDS board to EXP1 and EXP2 port. I dont need SD for now.

I have checked that my wirings are correct by using the GraphicsTest example available by U8glib in Arduino IDE using the following code:
U8GLIB_ST7920_128X64_4X u8g(44, 43, 42);	// SPI Com: SCK = en = 44, MOSI = rw = 43, CS = di = 42
Uploaded the code to my HW setup without touching anything except disconnecting the Hot end wires. It worked as expected without any problems.

I configured marlin for my setup and can be downloaded from the following files but the display only shows blank.
I am using 3 1K resistors as mentioned in the RADDS2LCD adapter.

**Expected behavior:** [What you expect to happen]

I expect the display to show something.

**Actual behavior:** [What actually happens]

Blank display backlight with two single pixel horizontal lines in the top and middle of the screen.
The button encoder is working fine. As I used it to auto home the printer and it worked. also checked the change of the pin state using M43 command.

#### Additional Information

[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/3373046/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/3373047/Configuration.txt)
[pins_RADDS.txt](https://github.com/MarlinFirmware/Marlin/files/3373049/pins_RADDS.txt)

**Comment by ShadowOfTheDamn** [comment]
Updates on the problem

at least I find good clue to solve the problem for now.
the problem is related to U8GLIB_ST7920_128X64_RRD

I managed to find that by changing lines 48 to 51 in ..\Marlin\src\lcd\dogm\ultralcd_DOGM.h to this:
``    #define U8G_CLASS U8GLIB_ST7920_128X64_4X ``
``   #define U8G_PARAM LCD_PINS_D4, LCD_PINS_ENABLE, LCD_PINS_RS     // Original u8glib device. 2 stripes, SW SPI ``
``    //#define U8G_CLASS U8GLIB_ST7920_128X64_RRD ``
``    //#define U8G_PARAM LCD_PINS_D4, LCD_PINS_ENABLE, LCD_PINS_RS ``
and by commenting the line 209 in ..\Marlin\src\lcd\dogm\u8g_dev_st7920_128x64_HAL.cpp :
``  //u8g_dev_t u8g_dev_st7920_128x64_rrd_sw_spi = { u8g_dev_st7920_128x64_HAL_4x_fn, &u8g_dev_st7920_128x64_HAL_4x_pb, U8G_COM_ST7920_HAL_SW_SPI }; ``

the display works but it is somehow a little bit slow and seems the top part of screen is a little bit out of sync with bottom half of the screen and it is really clear when you are using the dial to change some parameter like temperature or fan speed.
If you see the attached image it remains between 4% in bottom and 7% on top half when changing fan speed. 
[RRDS GLCD top and bottom half out of sync](https://user-images.githubusercontent.com/42454228/60968449-55854380-a332-11e9-8d79-987f010e596a.jpg)
I would be glad if any one with prior experience with Ug8lib library and St7920 driver help me out cause I have checked the delays before this solution with no success:
``#define ST7920_DELAY_1 DELAY_NS(400)``
``#define ST7920_DELAY_2 DELAY_NS(125)``
``#define ST7920_DELAY_3 DELAY_NS(440)``

**Comment by ShadowOfTheDamn** [comment]
Anyone? please help me.
I should add that I found that adding the LCD with the previous workaround, adds some millisecond freezing to the printer and I am seeing blobs like retraction points all over the place on parts which were super ok before adding the LCD.

**Comment by AnHardt** [comment]
This is not a support forum. We try to handle bugs and code improvements here.

We are bored by this problem. RADDS + ReprapDiscount Full Graphics Smart Controller was handled here several times (i guess). Please search.

ST7920 is an old, slow, buggy display controller. 

u8g-lib is a nice universal graphics library, but optimized to be universal and for saving memory, not for speed.

With writing our own u8g-device driver for the ST7920 we got some more speed.
If you really want to use the builtin u8g-device - you have to live whit its slowness.

Only our own device can be tuned by the custom delays. They are optimized by first setting ridicules high times, them shortening them, one by one, until you see pixel errors, then going back a step.

If the delays are not totally off you should see pixel errors.

Seeing nothing, usually is a pin or connection problem.

The problem seen in the picture is neither RADDS nor ReprapDiscount Full Graphics Smart Controller specific. It's a consequence of the [Picture Loop](https://github.com/olikraus/u8glib/wiki/tpictureloop) and programmers ignoring the consequences (Mainly: Don't change the screen content while in the loop, or at least if not in the first frame before drawing). It comes and goes almost always when some 'expert' tries to 'improve' the display code. Try to ignore it.

Currently it's worked on software SPI (again). It may help to use bugfix-2.0.x from a few days (weeks) before or later.

**Comment by ShadowOfTheDamn** [comment]
Thanks a lot @AnHardt. Then I will change my question. What type of LCD/Controller you propose with this kind of hardware I have RADDS + DUE.

**Comment by AnHardt** [comment]
For most users ReprapDiscount Full Graphics Smart Controller  is 'fast enough' when used with the Marlin driver. LIGHTWEIGHT_UI does use a char mode for the statusscreen. It does improve the speed a lot when not in the menues.
About all other graphical displays either transfer less data, do that with a higher speed or both.  
Because of much less transferred data the character based displays like ReprapDiscount Smart Controller or the RADDS-display burn much less time. They transfer only ~80 bytes per screen update, vs. ~1 KB with the normal graphical displays and ~2KB with a ST7920.
The importance of the time to produce the display content shrinkend with the 32-bit processor.
 Transfer times will become less important when we learn to use DMA for the transfer.

**Comment by ShadowOfTheDamn** [comment]
Thanks for the reply. Closing the issue. hope you would find some time to correct what you say you are supporting/developing. or remove it from your claims.
