### ISSUE TITLE
[BUG] TMC2209 UART broken on ATmega2560

### ISSUE THREAD

**Issue by EvilGremlin** [MarlinFirmware/Marlin#14561]
I want to use 3 drivers on single-pin UART, as should be possible with modified SoftwareSerial library (https://reprap.org/forum/read.php?415,848808,848808) but cannot connect even to single driver, getting "Testing X connection... Error: All LOW"
Is AVR initialization broken again in 2.0?

**Comment by thinkyhead** [comment]
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as requested in the Issue template) and drop them into your next reply. We'll use them in our testing.

**Comment by teemuatlut** [comment]
Trying to support modified framework libraries isn't really something I want to get into.
Try to first get your drivers the normal way.

**Comment by EvilGremlin** [comment]
Sorry, i was sure that i uploaded file...
Also, it doesn't work with standard library. I didn't get to play with modified yet.
[config_2209.zip](https://github.com/MarlinFirmware/Marlin/files/3383147/config_2209.zip)

**Comment by pkilar** [comment]
I got Rumba board + 3x TMC2209 working on single HW serial (Serial3). Remember to configure unique address for each of the TMC2209 drivers using DIP switches on the board. Attached is my config.
[TMC2209_hw_serial.zip](https://github.com/MarlinFirmware/Marlin/files/3389968/TMC2209_hw_serial.zip)

**Comment by EvilGremlin** [comment]
What commit/branch you running? Well, i'll try out HW serial anyway.

**Comment by pkilar** [comment]
I'm running bugfix-2.0.x:
commit caa87d5fe1d497fadf797091199568d282a797a0 (HEAD)
Author: Giuliano Zaro <3684609+GMagician@users.noreply.github.com>
Date:   Thu Jul 11 05:04:16 2019 +0200

    SD2Card cleanup (#14571)

**Comment by EvilGremlin** [comment]
Thanks, will try.

**Comment by boelle** [comment]
@EvilGremlin is the issue still there?

**Comment by boelle** [comment]
@EvilGremlin had a chance to play  arround with this one?

**Comment by EvilGremlin** [comment]
8.10 software serial still didn't work in any form.

**Comment by boelle** [comment]
8.10? is that arduino ide or some other tool i dont know of?

**Comment by EvilGremlin** [comment]
it's a date, october 8

**Comment by boelle** [comment]
ahh... i'm just a stupid european dude, we have date the other way round and almost always include year to make sure people get that its a date

ie 8/10-2019

free laughs on me for being slow :-D

**Comment by EvilGremlin** [comment]
Guess i'm also stupid kinda european dude :) I forgot how default date writing customs differ from country to country.

**Comment by boelle** [comment]
we could also write the same date as 19-10-8, there are a few other formats but i'm not that bored :-D

**Comment by boelle** [comment]
@EvilGremlin i guess none of the updates in the past 17 days has helped any?

@teemuatlut do you have any clue why this fails?

**Comment by EvilGremlin** [comment]
didn't update past 17 days, probably won't update for another 17 :)

**Comment by EvilGremlin** [comment]
Ok, so i finally updated and with all the changes it works now.
I've set TMC_BAUD_RATE to 57600 just in case.
