### ISSUE TITLE
[BUG] Cant compile 2.0 with #define AZSMZ_12864 

### ISSUE THREAD

**Issue by wailord284** [MarlinFirmware/Marlin#14569]
On the latest version of Marlin 2.0, defining the screen AZSMZ_12864  prevents me from compiling with either Arduino IDE or PlatformIO in visual studio code. By disabling AZSMZ_12864, I can compile normally. I am using a Smart Ramps with an Arduino DUE on a delta printer.

I get these errors in platformIO:
`In file included from Marlin/src/HAL/HAL_DUE/u8g_com_HAL_DUE_sw_spi.cpp:65:0:
Marlin/src/HAL/HAL_DUE/u8g_com_HAL_DUE_sw_spi_shared.h:27:26: error: variable or field 'u8g_SetPIOutput_DUE' declared void
 void u8g_SetPIOutput_DUE(u8g_t *u8g, uint8_t pin_index);
                          ^~~~~
Marlin/src/HAL/HAL_DUE/u8g_com_HAL_DUE_sw_spi_shared.h:27:26: error: 'u8g_t' was not declared in this scope
Marlin/src/HAL/HAL_DUE/u8g_com_HAL_DUE_sw_spi_shared.h:27:26: note: suggested alternative: 'uid_t'
 void u8g_SetPIOutput_DUE(u8g_t *u8g, uint8_t pin_index);
                          ^~~~~
                          uid_t
Marlin/src/HAL/HAL_DUE/u8g_com_HAL_DUE_sw_spi_shared.h:27:33: error: 'u8g' was not declared in this scope
 void u8g_SetPIOutput_DUE(u8g_t *u8g, uint8_t pin_index);
                                 ^~~
Marlin/src/HAL/HAL_DUE/u8g_com_HAL_DUE_sw_spi_shared.h:27:46: error: expected primary-expression before 'pin_index'
 void u8g_SetPIOutput_DUE(u8g_t *u8g, uint8_t pin_index);
                                              ^~~~~~~~~
Marlin/src/HAL/HAL_DUE/u8g_com_HAL_DUE_sw_spi_shared.h:28:25: error: variable or field 'u8g_SetPILevel_DUE' declared void
 void u8g_SetPILevel_DUE(u8g_t *u8g, uint8_t pin_index, uint8_t level);
                         ^~~~~
compilation terminated due to -fmax-errors=5.
Compiling .pioenvs/DUE/src/src/HAL/HAL_DUE/usb/udi_cdc_desc.c.o
Compiling .pioenvs/DUE/src/src/HAL/HAL_DUE/usb/udi_composite_desc.c.o
Compiling .pioenvs/DUE/src/src/HAL/HAL_DUE/usb/udi_msc.c.o
Compiling .pioenvs/DUE/src/src/HAL/HAL_DUE/usb/uotghs_device_due.c.o
Compiling .pioenvs/DUE/src/src/HAL/HAL_DUE/usb/usb_task.c.o
*** [.pioenvs/DUE/src/src/HAL/HAL_DUE/u8g_com_HAL_DUE_sw_spi.cpp.o] Error 1`

Here are my config files. I have just updated them to be on the newest config file layout. Thank you.
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/3379095/configs.zip)

**Comment by DerThommi** [comment]
Seems related to my Issue #14567

**Comment by shitcreek** [comment]
If this has been resolved, please share what you did and close the issue. Thank you.

**Comment by wailord284** [comment]
> If this has been resolved, please share what you did and close the issue. Thank you.

I haven't been able to test recently, but as of not long ago it was still not fixed.
However, someone with a similar issue proposed a solution that I have not yet tried.
https://github.com/MarlinFirmware/Marlin/issues/14567#issuecomment-513578304

**Comment by boelle** [comment]
@wailord284 still having issues?
