### ISSUE TITLE
[BUG] adding M43 will result in compile error

### ISSUE THREAD

**Issue by ShadowOfTheDamn** [MarlinFirmware/Marlin#14565]
[compile error.txt](https://github.com/MarlinFirmware/Marlin/files/3376040/compile.error.txt)

### Description

In the recent update of marlin after adding M43 to the configuration_adv.h I get compile error.

Just use the attached config files.

#### Additional Information
[compile error.txt](https://github.com/MarlinFirmware/Marlin/files/3376042/compile.error.txt)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/3376053/Configuration_adv.zip)

**Comment by Ludy87** [comment]
Bugfix: https://github.com/MarlinFirmware/Marlin/pull/14554

PR is released

**Comment by ShadowOfTheDamn** [comment]
Yes, That works now.
thanks and closing the issue.
