### ISSUE TITLE
Marlin\src\pins\pins_BIGTREE_SKR_PRO_V1.1.h

### ISSUE THREAD

**Issue by RudyBenner** [MarlinFirmware/Marlin#14564]

**Comment by RudyBenner** [comment]
I propose:

![image](https://user-images.githubusercontent.com/40361032/60940668-4064d200-a2aa-11e9-9c9a-2a4afe6e0374.png)

Should this be a PR?

**Comment by RudyBenner** [comment]
should this be a PR?

**Comment by thisiskeithb** [comment]
What would it accomplish?

Note that some board pins were just cleaned up to remove the `BOARD_NAME` ifndef statement: https://github.com/MarlinFirmware/Marlin/commit/44c8f29e47bb9fc00dbb42e5305dd463338f4630

**Comment by RudyBenner** [comment]
yes, I did see that this morning and the compile suffers, which is what I was trying to clean-up

**Comment by RudyBenner** [comment]
try the latest, then try my proposal.
