### ISSUE TITLE
tmc 2130 sifflement Z dual stepper drivers

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#14604]
hello

after activating #define Z_DUAL_STEPPER_DRIVERS the engine of the   of the driver  Z2 (E1)works but makes a hissing sound

I switched the cables and changed the driver no result

both engine on the same driver Z no whistling

#define X_DRIVER_TYPE  TMC2130
#define Y_DRIVER_TYPE  TMC2130
#define Z_DRIVER_TYPE  TMC2130
//#define X2_DRIVER_TYPE A4988
//#define Y2_DRIVER_TYPE A4988
#define Z2_DRIVER_TYPE TMC2130
//#define Z3_DRIVER_TYPE A4988
#define E0_DRIVER_TYPE LV8729
//#define E1_DRIVER_TYPE A4988
//#define E2_DRIVER_TYPE A4988
//#define E3_DRIVER_TYPE A4988
//#define E4_DRIVER_TYPE A4988
//#define E5_DRIVER_TYPE A4988

merci

**Comment by InsanityAutomation** [comment]
Sounds like vref needs to be adjusted, is there a POT near the driver? Compare to the other z driver that isnt hissing.

Edit, just spotted its SPI mode, so you can adjust it through the LCD or gcode.

**Comment by boubouexpress** [comment]
I forgot to say that I checked the driver adjustments in relation to the amperage of the motors

**Comment by boubouexpress** [comment]
Résolu
J’avais oublier activer pour le Z2 le stepping mode 
Désolé
