### ISSUE TITLE
extruder_multiply[active_extruder] not used?

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#1460]
I notice that the planner is using the current value of `extrudemultiply` but I can't find any location where `extruder_multiply[active_extruder]` (as set in M221) is copied into this variable, as I would expect with multiple extruders. Wherever it is that extruders are switched, that seems like the place where this value should be set. Perhaps in `planner.cpp` near `block->active_extruder = extruder;` ?

**Comment by tonnico** [comment]
Maybe there? https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/planner.cpp#L604

**Comment by MagoKimbra** [comment]
in my marlin i deleted extrudemultiply and use only extruder_multiply[active_extruder]...

**Comment by thinkyhead** [comment]
@MagoKimbra Great! That's a change that needs to come to the main branch, asap. It's definitely a bug.

**Comment by KiteLab** [comment]
Should work now.
Has to be tested.
