### ISSUE TITLE
[BUG] Controller fan timeout secs not honored in latest BF2

### ISSUE THREAD

**Issue by OneOfEleven** [MarlinFirmware/Marlin#14617]
No matter what we set **CONTROLLERFAN_SECS** too the controller fan always times out (turns off) approx 7 seconds after the steppers are deactivated.

Firmware is latest BF2.
Board is BTT SKR 1.3
Stepper drivers are TMC2208's (UART mode).

7 seconds is fine by us but thought you'd like to know about the timeout period apparently being ignored.

```cpp
/**
 * Controller Fan
 * To cool down the stepper drivers and MOSFETs.
 *
 * The fan will turn on automatically whenever any stepper is enabled
 * and turn off after a set period after all steppers are turned off.
 */
#define USE_CONTROLLER_FAN
#if ENABLED(USE_CONTROLLER_FAN)
  //#define CONTROLLER_FAN_PIN -1
  #define CONTROLLER_FAN_PIN SERVO0_PIN
  #define CONTROLLERFAN_SECS 10           // Duration in seconds for the fan to run after all motors are disabled
  #define CONTROLLERFAN_SPEED 70          // 255 == full speed
#endif
```

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
@OneOfEleven is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
