### ISSUE TITLE
[BUG] SKR Pro v1.1 and TMC 2209 in UART mode compilation error

### ISSUE THREAD

**Issue by biskero** [MarlinFirmware/Marlin#14615]
Hello,

I am trying to compile Marlin 2.0.x from yesterday for the SKR Pro v1.1 with TMC2209 in UART mode and I am getting some errors:
![Screen Shot 2019-07-13 at 9 22 47 PM](https://user-images.githubusercontent.com/13521595/61175958-647d2780-a5b8-11e9-9222-e8b96dc444cb.png)

also the Software Serial Pins in pins_BIGTREE_SKR_PRO_V1.1.h should be these, got them from SKR Pro facebook page;
![67180451_2488543284535986_2141550678961553408_n](https://user-images.githubusercontent.com/13521595/61175974-a0b08800-a5b8-11e9-8c3e-a554b88b9cf0.jpg)
 
any ideas? I can test things if needed, compiling on Ubuntu 18 in Atom/Platformio.
thx

**Comment by EvilGremlin** [comment]
Zip configuration files and attach to message. Also, note which version of TMCStepper library you use.

**Comment by biskero** [comment]
I have TMCStepper 0.4.5 in Arduino from github.com/teemuatlut/TMCStepper

Here are the config files:
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3389207/configuration.zip)

**Comment by Ludy87** [comment]
I think @teemuatlut has to work on it again.

**Comment by Ludy87** [comment]
Marlin can be compiled with this library FORK (https://github.com/Msq001/TMCStepper.git).

**Comment by zillarob** [comment]
I couldnt figure it out the single pin way that is currently in the pins file (Tx and Rx are the same pin) so changed to what is above and seems to work. M122 looks good for all of them anyway.
The board is setup for the 2 pin way and those pin numbers are off the btt pin diagram.

**Comment by EvilGremlin** [comment]
Single pin mode depends on support by either hardware port or software library. You cannot just put same ports in config and hope it'll work.

**Comment by Ludy87** [comment]
```c++
tmc_util.h:166:40: error: no matching function for call to 'TMC2208Stepper::TMC2208Stepper(const uint16_t&, const uint16_t&, const float&, const bool&)'
       TMC2208Stepper(RX, TX, RS, has_rx)
```

**Comment by zillarob** [comment]
@EvilGremlin  The pins file in Marlin currently is setup for single pin. I have never used it and not familiar with it so just changed the pins to what is called for in the pin diagram.
Single pin prob works or I would guess the pins file wouldnt be the way it is, but the board is setup for 2 pin so I gave it a shot that way and it worked.

**Comment by eightheads** [comment]
> @EvilGremlin The pins file in Marlin currently is setup for single pin. I have never used it and not familiar with it so just changed the pins to what is called for in the pin diagram.
> Single pin prob works or I would guess the pins file wouldnt be the way it is, but the board is setup for 2 pin so I gave it a shot that way and it worked.

The latest Marlin does not compile with 2 pins defined either. I'm getting the same error
`tmc_util.h:166:40: error: no matching function for call to 'TMC2208Stepper::TMC2208Stepper(const uint16_t&, const uint16_t&, const float&, const bool&)'
       TMC2208Stepper(RX, TX, RS, has_rx)`

**Comment by zillarob** [comment]
Good point. I was using the one on btt github and dont remember straying out of the shallow end =D

**Comment by biskero** [comment]
yes, I tried compiling both single pins or the above configuration but the error persists.

**Comment by Ludy87** [comment]
@biskero 

'platformio.ini'

Change `TMCStepper@<1.0.0` to `https://github.com/Msq001/TMCStepper.git`

**Comment by biskero** [comment]
It worked ! compiled successfully !
So it's the TMCStepper library that needs to be an update.
thx for the support  !

**Comment by teemuatlut** [comment]
SoftwareSerial is not supported internally by the STM32Duino framework.

**Comment by biskero** [comment]
@teemuatlut so does it means that the above pin layout is not ok? and the single pin layout is ok?
thx

**Comment by teemuatlut** [comment]
No SW Serial means HW Serial only.

Alternatively you can use the Bigtreetech fork or modify upstream Marlin.

**Comment by eightheads** [comment]
> No SW Serial means HW Serial only.
> 
> Alternatively you can use the Bigtreetech fork or modify upstream Marlin.

@teemuatlut,  I assume SoftwareSerial for STM32 chipsets will be added sometime relatively soon in the official TMCStepper library?

**Comment by teemuatlut** [comment]
TMCStepper will not be adding any internal Serial implementations. That's firmly in the realm of either the platform framework or a supporting library for the platform.
When that exists I can easily add STM into the supported list.

EDIT: SW Serial library has been added to the STM platform.

**Comment by Evg33** [comment]
#TMCStepper@<1.0.0
  https://github.com/bigtreetech/TMCStepper

**Comment by boelle** [comment]
@biskero is the issue still there?

**Comment by hackebike** [comment]
@boelle issue is not there anymore

**Comment by boelle** [comment]
oki, then i will close, we can always reopen :-D

**Comment by Evg33** [comment]
@RudyBenner can you show me yours platformio.ini Configuration.h and Configuration_adv.h  ?

**Comment by Evg33** [comment]
PR successfully tested with 2208 uart and 5160 spi.
Video: https://youtu.be/1tiIr5R-jok
At 2208, you need to solder 2 blue pins in the middle.
![image](https://user-images.githubusercontent.com/7160738/65544266-8df0f280-df1b-11e9-9d60-af9c4d544bef.png)
