### ISSUE TITLE
[QUESTION] SDSS vs LCD_SDSS

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#14616]
My configuration is mega2560 and ramsp and I'm using LCD sd but pin is defined by SDSS not LCD_SDSS, so when is expected to be used LCD_SDSS?

I'm always stuck in AGCM4 SD integration

**Comment by gloomyandy** [comment]
I think that LCD_SDSS is used when you have two SD card readers (both on the same bus) and want to be able to use either of them. In that case SDSS is used for the SD reader on the mainboard and LCD_SDSS is used for the LCD based SD reader. The SD card code will try first one reader and then the other with this setup.

**Comment by GMagician** [comment]
Well I was expecting to see LCD_SDSS used more than SDSS but that's ok
