### ISSUE TITLE
[BUG] (SKR v1.3 Homing-G28 Causes PID_BED_DEBUG Issues)

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#14626]
### Description

Marlin Bugfix 2.0 Current Branch crashes (Software Crash) when homing.

### Steps to Reproduce

1. Connect Terminal
2. G28 (Home)
3. Marlin Crash (echo: PID_BED_DEBUG : Input 21.25 Output 0.00 pTerm -212.50 iTerm 0.00 dTerm 13.35)

**Expected behavior:** Printer to Home

**Actual behavior:** Marlin Crashes

#### Additional Information
![2019-07-14_13-45-18](https://user-images.githubusercontent.com/51185309/61189233-6d650c00-a63f-11e9-84b3-2915c77bcc3d.jpg)

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by shitcreek** [comment]
says BLTouch error. Check if it is configured properly and the connection is good.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
@Mbombace is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by yaoyaobutao** [comment]
I'm using the skr v1.3 board on anycubic kossel ,having the same issue when sending G28 and it keep echoing pid_bed_debug

**Comment by jrprintin3d** [comment]
I`m using also the skr v1.3 board with TMC2208 driver and have the same issue at my mendel90.
