### ISSUE TITLE
Marlin hangs when very large feed rates are used

### ISSUE THREAD

**Issue by BDFife** [MarlinFirmware/Marlin#14636]
### Description

Marlin hangs ('hang' defined as the printer stopping mid-print and issuing echo:busy: processing continuously) when very large feed rates are provided. 

Cura (incorrectly) in some cases uses a default feedrate of F17987547480000 that was triggering this issue for me. While this is primarily a Cura problem, it would be nice if Marlin handled this more elegantly, or threw an error in the console.

### Steps to Reproduce

Using the Marlin bugfix-2.0.x code branch, my build was from 2019-06-26. 
A gcode file that triggers this issue is attached. 

#### Additional Information

My config files are located here: https://github.com/BDFife/MarlinConfigs/tree/master/Model3Rambo

[PS_xyzCalibration_cube_CuraFail.gcode.zip](https://github.com/MarlinFirmware/Marlin/files/3394704/PS_xyzCalibration_cube_CuraFail.gcode.zip)

**Comment by BDFife** [comment]
This issue is a dupe of #14454

**Comment by reloxx13** [comment]
dupe, so close it

also blame cura for using lightspeed as fallback...
