### ISSUE TITLE
[BUG] Delta-SKR1.3-TMC2208(UART) Auto bed leveling: probe crash on last point

### ISSUE THREAD

**Issue by maxarchx** [MarlinFirmware/Marlin#14653]
### Description
My printer: Anycubic Kossel Linear Plus with SKR1.3-TMC2208(UART) with lastest Marlin bugfix 2.0.
Trying to perform Auto Bed Leveling with probe from LCD screen. Probing starts and hits all the points, but when it reaches last probe point it is crashes probe to bed.

### Steps to Reproduce
1. Run Auto Bed Level from LCD screen.
2. Wait for bed leveling finishes.

**Expected behavior:** Probe checks all probe points and go to home position.

**Actual behavior:** Probe checks all probe points except last one and crashes to bed.

#### Additional Information
Configs:
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3401443/Marlin.zip)

**Comment by Bjerg** [comment]
I am having exactly the same problem do you also use bilinear bed level or?

But i am using MKS SGEN 

also using the same Anycubic Kossel Linear Plus

my Configs:
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3403852/Marlin.zip)

**Comment by maxarchx** [comment]
I have tried linear and bilinear. Results are same :(
Just noticed, that bed leveling starts in wrong position, with some offset from front bed edge. About 15-30mm. Hmmm.

**Comment by boubouexpress** [comment]
Modifier
#define Z_probe_low_point -2   (-8)

**Comment by maxarchx** [comment]
> Modifier
> #define Z_probe_low_point -2 (-8)

Did not help.

**Comment by maxarchx** [comment]
Just tried UBL bed leveling, and it failed too. It looks nice on start, and after 15-20 point checks probe begins move really weird and stucks out off bed.

**Comment by maxarchx** [comment]
Fixed it.
Commented this line:
//#define Z_AFTER_PROBING            8 // Z position after probing is done

There is some problem with **move_z_after_probing()** function on delta printer.

**Comment by boubouexpress** [comment]
j'ai mi a 40 au-lieu de 1 par défaut 
#define MESH_INSET 40              // Set Mesh bounds as an inset region of the bed

**Comment by boubouexpress** [comment]
video

https://www.youtube.com/watch?v=ONpKxkil16Q&t=1097s

**Comment by boubouexpress** [comment]
for the process of G29 p1 to work until the end I had to modify   #define MESH_INSET 45

**Comment by luxflow** [comment]
I also having this issue too on 41b7f16ab84908544091882a924a80aa4201b3d6
I use LV8729 driver so I think driver doesn't affect regarding this problem
here is my config
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3527906/Marlin.zip)
(anycubic linear plus + skr 1.3 + bilinear)


I didn't try Z_AFTER_PROBING yet, I will comment again after uncomment

**Comment by luxflow** [comment]
I confirmed that after I commented //#define Z_AFTER_PROBING 8
bed leveling works

**Comment by boelle** [comment]
@maxarchx this @luxflow suggest work for you too ?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
