### ISSUE TITLE
[BUG] [bugfix-2.0.x] On AZSMZ mini and AZSMZ lcd problem if enable SD ONBOARD

### ISSUE THREAD

**Issue by xamxamxam** [MarlinFirmware/Marlin#14656]
Hello
I have  AZSMZ mini and AZSMZ lcd , I tried to enable ONBOARD in SD in configuration_adv.h but the display stopped working.
The onboard SD started working but afyer a M21 I loosed the USB view of SD in windows.
I suppose a PINS definition problem ....
I rolled back the change ad the display returned ok.
Any suggestion?
Thanks

**Comment by xamxamxam** [comment]
Hello
I have  AZSMZ mini and AZSMZ lcd , I tried to enable ONBOARD in SD in configuration_adv.h but the display stopped working.
I suppose a PINS definition problem ....
I rolled back the change ad the display returned ok.
Any suggestion?
Thanks

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by xamxamxam** [comment]
Hello
Here they are
Thanks a lot


[Config.zip](https://github.com/MarlinFirmware/Marlin/files/3422078/Config.zip)

**Comment by boelle** [comment]
@xamxamxam is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
