### ISSUE TITLE
[FR] multiple neopixel pins

### ISSUE THREAD

**Issue by ronniebravo88x** [MarlinFirmware/Marlin#14662]
I'd like you to include the possibility of assigning neopixels to more than one pin. It is necessary for example to use the fysetc 12864 v2.1 panel and a neopixel strip at the same time.
Thank you.

**Comment by timmmoore** [comment]
I ran into this with a fysetc 12864 panel. I am putting together a PR containing the changes I did to support 2 neopixel strips.

**Comment by tpruvot** [comment]
It's PR #14667

**Comment by thisiskeithb** [comment]
The PR has been merged, so this issue can be closed.

**Comment by ronniebravo88x** [comment]
Thank you so much for the hard work. I'll try it as soon as I can.
