### ISSUE TITLE
[BUG] confirmation request

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#14686]
Hello
I have a RADDS with LCD RADDS original
I have two napes of 70cm
I activate in marlin 2.0 LCD RADDS
see the picture

the length of the tablecloth may cause this problem or I have not configured correctly

merci![IMG_20190717_124753](https://user-images.githubusercontent.com/12213323/61577018-01bcec00-aae2-11e9-8275-01872da039ad.jpg)

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boubouexpress** [comment]
hello
merci 
[marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3414338/marlin.zip)

**Comment by RudyBenner** [comment]
I see no obvious errors.

I believe you suspect the long ribbon cables could be picking up noise?
I would agree that is possible. I suggest you make a spiral of them, side by side (transposition)
to minimize EMI pickup, do not put next to other cables.

I see you are using the auto fans feature. Perhaps you can disable those lines to see if there
is a difference. One can easily restore the settings.

I did not check the pins file for conflicts.

I hope my english is adequate.

rudy

**Comment by boubouexpress** [comment]
thank you
I am french

I order connectors to shorten it

**Comment by boelle** [comment]
i had similar issue with a full graphic display, had to shorten the wires a lot
but screened cables could also be something to test

**Comment by boubouexpress** [comment]
c the length of the sheet that causes the interference.
