### ISSUE TITLE
[Question] pullup on sd detect

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#14708]
In AGCM4 to use onboard SD detect, input must have pullup.

I see that this is done only when EXTENSIBLE_UI is enabled, isn't pullup mandatory for other boards/lcds?

**Comment by GMagician** [comment]
Ok also lcd enable pull-up. But what about boards with on board sd? None set pullup

**Comment by gloomyandy** [comment]
Some boards like the SKR V1.3 that have onboard readers have pull up resistors on the board so no need for the MCU pull up.

**Comment by GMagician** [comment]
Ok, thanks, I'll add it in my hal only when Onboard sd is used
