### ISSUE TITLE
[BUG] zebra stipes with tmc drivers on cartesian

### ISSUE THREAD

**Issue by iliya-malecki** [MarlinFirmware/Marlin#14707]
### Description
with tmc2208 on skr1.3 im having a lot of zebra stipes, using cartesian kinematics. A friend has that problem too on cartesian, and doesnt have it on coreXY, with exact same settings.

### Steps to Reproduce
im using bigtreetech tmc2208 v3.0, gonna attach the config files. Cant get rid of them lines, so it is rather easy to reproduce with any settings)))

1. all microstepping modes give this result
2. adaptive step smoothing and s-curve doesnt help
3. square wave stepping makes it worse

#### Additional Information
[config.zip](https://github.com/MarlinFirmware/Marlin/files/3419107/config.zip)

![photo](https://user-images.githubusercontent.com/53195438/61663856-36939380-acda-11e9-83a4-c7feb9bcddd5.jpg)

![another](https://user-images.githubusercontent.com/53195438/61663866-3d220b00-acda-11e9-90eb-1dbf8b03d65c.jpg)

**Comment by gloomyandy** [comment]
See this thread for an investigation into what looks like the same thing on a Prusa-i3-Mk3.

https://forum.prusaprinters.org/forum/original-prusa-i3-mk3s-mk3-user-mods-octoprint-enclosures-nozzles-.../stepper-motor-upgrades-to-eliminate-vfa-s-vertical-fine-artifacts/

**Comment by iliya-malecki** [comment]
but tmc 2208 should give much more uniform current than other cheapeys like drv. Other 2208 give way less vfa than mine, so I am clearly doing something wrong with my firmware

**Comment by gloomyandy** [comment]
I don't think you are. Read the above thread, it varies from system to system. One thing is that the smoother your rails and other movements are the more you can see the vfa. Other faults can mask them.

**Comment by iliya-malecki** [comment]
I didnt change anything in my kinematics when I changed from cheap drivers to tmc2208, and the problem escalated only with new drivers

**Comment by gloomyandy** [comment]
So was the only thing you changed the drivers or did you also change the control board and the version of Marlin you use? If you really want to investigate what is going on you probably need to try "cheap drivers" on the same board and version of Marlin.

**Comment by iliya-malecki** [comment]
ye probably I should buy some of them a4988

**Comment by DerAndere1** [comment]
Did you try PID tuning? I heard it helped in another issue that was concerned with wave patterns. This fix was found by Gerald A. in the marlin facebook group: https://www.facebook.com/groups/1049718498464482/search/?query=heating%20cycles&epa=SEARCH_BOX

**Comment by boelle** [comment]
@IliyaMalecki tried what @DerAndere1 suggested?

**Comment by iliya-malecki** [comment]
@boelle it didnt help much, the problem is not connected with extrusion itself

**Comment by boelle** [comment]
have you checked that belts and pulleys are ok? loose screws etc?

are you trying to print faster than the printer can handle?

**Comment by iliya-malecki** [comment]
@boelle everything is checked and working properly. Still having problems

**Comment by boelle** [comment]
could you try and attach the model you printed? i will then try and print and see if i get the same result

**Comment by iliya-malecki** [comment]
okay, thank you

**Comment by boelle** [comment]
you forgot to attach the model

**Comment by iliya-malecki** [comment]
gonna attach it later, I'm a bit busy right now

**Comment by boelle** [comment]
still busy?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by iliya-malecki** [comment]
I'm solving it right now by installing new skr 1.3 and reprinting test models I'm gonna send you. And i fell for the trick, nice job

**Comment by boelle** [comment]
could be nice if you also attach the stl file, you might need to make a zip file

or is the test model from thingiverse?

**Comment by iliya-malecki** [comment]
[zebra.zip](https://github.com/MarlinFirmware/Marlin/files/3803771/zebra.zip)

didnt find the stl, i have been using this test for some time, and the original vanished somewhere.

**Comment by iliya-malecki** [comment]
and these are my results
![20191104_133739](https://user-images.githubusercontent.com/53195438/68119377-3d51b980-ff0b-11e9-97d4-4b6d6fcd0c66.jpg)
![20191104_133835](https://user-images.githubusercontent.com/53195438/68119380-3d51b980-ff0b-11e9-9f86-b8dc022e3024.jpg)

**Comment by boelle** [comment]
seems to be less that the white print

**Comment by iliya-malecki** [comment]
only thing changed is the board - except visuals of the plastic, of course, white pla shows the problem more

**Comment by boelle** [comment]
@thinkyhead @shitcreek time to have a look here before the issue gets lost and not fixed

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
