### ISSUE TITLE
[BUG] Re-Arm RRDFGSC LCD missing or lagging top half of the display

### ISSUE THREAD

**Issue by 2kingsrock** [MarlinFirmware/Marlin#14716]
### Description

Using the Re-Arm with Ramps 1.6+ connected to RepRap Discount Full Graphic LCD top half display lags or is missing when using the menus

### Steps to Reproduce

1. Scroll through various menus, top half can take additional time to sync with bottom half
2. Prevalent on bed level menu (1 of 9 steps)
3. The top half will be completely missing
* Note. Correctly working on Marlin 1.1.9 with Mega 2560, no issues with this.  Using it to base line the hardware. Swapped to 2.x bugfix Nightly on Re-Arm and the issue appears * 

**Expected behavior:** Even if screen lags in menus, it should re-sync 

**Actual behavior:** top half of screen goes missing / lags

#### Additional Information

Screen with Offsets applied is from 2.0 bugfix and shows home screen appears to be working fine, however the bed level menu shows a screen from this same build with the problems.  During scrolling through the menus in the 2.0 bugfix, the top half screen will lag and then sync.  I can take a video and grab the configuration.h and adv files tonight. 

![20190724_010224](https://user-images.githubusercontent.com/22711392/61799175-a39d4b00-adf8-11e9-8b57-04fccafa56d6.jpg)
![20190724_005427](https://user-images.githubusercontent.com/22711392/61799182-a7c96880-adf8-11e9-8e72-db845c720263.jpg)

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by boelle** [comment]
So 2.0.x is working perfectly?

remember to add configs as zip

**Comment by 2kingsrock** [comment]
Updated the original comment.  I can add in video, screen shots and configs later today.  This hardware is  working correctly on a 8bit Mega with Ramps 1.6+ on a printer kit CoreXY running Marlin 1.1.9.  I am using this current CORE XY working printer as a baseline and have been creating a conversion kit and process to migrate from the 8 bit Mega.  The goal is to unplug swap to the RE-ARM to get to 32bit running the 2.0x.  I have a series of different brand screens I can test with also this weekend to see if it is just with the RepRap Full Graphics, or if TFT or other 4 line displays display same artifacts.  looking forward to sorting this minor issue out!

**Comment by 2kingsrock** [comment]
[backup configs.zip](https://github.com/MarlinFirmware/Marlin/files/3429778/backup.configs.zip)
![20190724_225857](https://user-images.githubusercontent.com/22711392/61847171-b5720300-ae77-11e9-9c7c-cd14cbac3f91.jpg)
![20190724_005427](https://user-images.githubusercontent.com/22711392/61847174-b99e2080-ae77-11e9-9f82-31acd2481e69.jpg)

Bed level menu or actions seem to be where this issue is visible / repeatable.  Corner Level or Manual 9pt level.  Bottom half seems to be always correct.

**Comment by AnHardt** [comment]
This error is reasoned by changing the display contend inside u8glibs [picture loop](https://github.com/olikraus/u8glib/wiki/tpictureloop).
We do have a [state-machine](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/ultralcd.h#L47-L53) to manage the problems caused by that.
But obviously its use is to complicated for some programmers.

Have a look on working code. See how the states are managed an what they do mean.
I'm tired of that and learned to live with the problem.

**Comment by 2kingsrock** [comment]
1) allocate half local frame buffer (called 'page') in the microcontroller RAM (128x32 pixel)
2) clear page (128x32 pixel), set clipping to lines 0 to 31
3) execute draw()
4) transfer page to the upper half of the display frame buffer.
5) clear page (128x32 pixel), set clipping to lines 32 to 63
6) execute draw()
7) transfer page to the lower half of the display frame buffer

Thank you for the info, helps to rule out hardware conflicts / faults, etc.

**Comment by boelle** [comment]
any idea how and if this can be fixed?

**Comment by boelle** [comment]
@shitcreek i think this one is an easy to fix ?

**Comment by boelle** [comment]
@AnHardt how could we fix this one for good so it does not bite us again?

**Comment by boelle** [comment]
@2kingsrock i assume this one is still an issue?

**Comment by boelle** [comment]
@AnHardt how can we fix this one for good?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
