### ISSUE TITLE
[BUG] Marlin 2 Error Z_MIN_ENDSTOP_INVERTING

### ISSUE THREAD

**Issue by ice2009** [MarlinFirmware/Marlin#14737]
Hello :) 

I using capacity sensor for my printer (NPN). In my configuration.h i set
 #define Z_MIN_ENDSTOP_INVERTING **true** 
but i need 
#define Z_MIN_PROBE_ENDSTOP_INVERTING **false** 

bacause my sensor is npn. I connect sensor to Zmin on my board. But when i compiling this file i have error 
<img width="1080" alt="Snímka obrazovky 2019-07-27 o 0 06 24" src="https://user-images.githubusercontent.com/6351562/61983924-7fad5580-b002-11e9-8146-ce34d201d7d6.png"> this configuration works with me in marlin 1.1.9 but i use need marlin 2.0 because i use 32bit board with tmc2209. Anyone could you help me?

**Comment by ManuelMcLure** [comment]
Did you actually read the error message? If you’re using both a Z end stop and a Z probe (I.e. ``Z_MIN_PROBE_ENDSTOP_USES_Z_MIN_ENDSTOP_PIN`` is unset) then you must set ``Z_MIN_PROBE_PIN`` to tell Marlin where your probe is connected. If you don’t have a separate Z end stop and are using the probe for homing then ``Z_MIN_PROBE_ENDSTOP_USES_Z_MIN_ENDSTOP_PIN`` should be enabled.

**Comment by ice2009** [comment]
Okay but i connect sensor to z_min on board. I don't know pin number. I use fystec cheetah board.

**Comment by boelle** [comment]
where do you connect Z endstop? as @ManuelMcLure  said you are using both and they cant be connected to same pin

you also forgot to read the template when you created the issue, it tells you to attach your 2 config files as a zip file

**Comment by ice2009** [comment]
I connect my npn sensor to z_min on fystec cheetah board (see on image). I need Z_MIN_ENDSTOP_INVERTING to true function but Z_MIN_PROBE_ENDSTOP_INVERTING must be false because when i use true npn is still trigger. 
![f40d024ddf10c3e9d7fd8cf6b52f190c_display_large_large](https://user-images.githubusercontent.com/6351562/61991512-549e2280-b051-11e9-81fe-7dc258a1f5cb.jpg)

**Comment by boelle** [comment]
where do you connect Z endstop (not sensor/probe)?

attach 2 config files as zip

**Comment by ice2009** [comment]
> where do you connect Z endstop (not sensor/probe)?
> 
> attach 2 config files as zip

I replace z endstop (ender3) to ljc18a3-h-z/bx.

I use this configuration https://github.com/esamwis3/cheetah-bltouch end i uncomment bltouch and change Z_MIN_ENDSTOP_INVERTING  to true and Z_MIN_PROBE_ENDSTOP_INVERTING to false

**Comment by boelle** [comment]
you cant just use a config from outside marlin, you have to copy over settings manual

you can use a tool like winmerge to compare 2 files and make it easy to compare and copy over settings

**Comment by boelle** [comment]
here are the Ender 3 example configs 

https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/config/examples/Creality/Ender-3

**Comment by ice2009** [comment]
> here are the Ender 3 example configs
> 
> https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/config/examples/Creality/Ender-3

Yes i use all marlin https://github.com/FYSETC/Marlin-2.0.x-FYSETC and configuration for ender3 but when i replace z_endstop on marlin to npn capacity sensor and use Z_MIN_ENDSTOP_INVERTING true and npn endstop false i have error from first image.

**Comment by boelle** [comment]
that is not marlin, its a copy/fork of marlin and that is a different thing

use https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

and start out with the example config: https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/config/examples/Creality/Ender-3

**Comment by shitcreek** [comment]
Cleaning house. LMK if problem still persists after using the official Marlin copy and issue needs to be reopened.
