### ISSUE TITLE
[BUG] [2.0] issue with case light on MKS GEN L

### ISSUE THREAD

**Issue by mvoss96** [MarlinFirmware/Marlin#14750]
Hi, I'm facing the same issue as in https://github.com/MarlinFirmware/Marlin/issues/11901
Case lighting on MKS GEN L board automaticaly turs off after a split secnd, unless i uncomment #define MOSFET_D_PIN 7

Im using pin 7 (HE2) for the case light because im only using one hotend  , so i can hook up the leds to the output of the second heater.

**Comment by RudyBenner** [comment]
#define MOSFET_D_PIN 7
try //#define MOSFET_D_PIN 7

**Comment by RudyBenner** [comment]
I think that is the correct solution.

**Comment by shitcreek** [comment]
Re-assigning MOSFET_D_PIN to -1 instead. I don't think this is a bug but rather a conflict with pin doubly assigned.
