### ISSUE TITLE
[BUG]  STM32F407ZGT6  Neopixel Support unable to compile

### ISSUE THREAD

**Issue by ledfreak3d** [MarlinFirmware/Marlin#14756]
### Description

Unable to compile for Bigtree Skr pro board with neopixel support

### Steps to Reproduce

<Enable neopixel support for  build env BIGTREE_SKR_PRO>

**Expected behavior:** [Compiles succesfully 

**Actual behavior:** [Failed on neopixel ibrary

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3439463/Configuration.zip)

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by RudyBenner** [comment]
![image](https://user-images.githubusercontent.com/40361032/62012892-e1340800-b159-11e9-8fda-bea9ce9e96cb.png)
using your files.

**Comment by ledfreak3d** [comment]
Yep i know because  define neopixel is commented in.my version uncomment and see what happens

**Comment by RudyBenner** [comment]
This is what you sent.

![image](https://user-images.githubusercontent.com/40361032/62013067-edb96000-b15b-11e9-9091-3256f726fee7.png)

**Comment by RudyBenner** [comment]
Yup

![image](https://user-images.githubusercontent.com/40361032/62013126-936ccf00-b15c-11e9-91cc-c6720c6642d7.png)

**Comment by ledfreak3d** [comment]
![image](https://user-images.githubusercontent.com/3198346/62013395-40ae0a00-b192-11e9-9984-76c88e5fbb1b.png)

**Comment by mikeshub** [comment]
You need to edit your platformio.ini. In STM32F4 neo pixel is in the ignore. This is because the library does not really support 32 bit targets. If you want to help add support for neopixels to the STM32F4 here is what needs to be tested. The Adafruit NeoPixel library was just updated to work with LPC1768 targets. I'm pretty sure this is an easy fix, but I don't have an STM32F4 board to test this with. Here is the relevant code for anyone who feels like trying the fix:

https://github.com/adafruit/Adafruit_NeoPixel/pull/197/commits/0f78242a630d6d0ea27be42c9f830b9d17e9bc00

What needs to happen is where it has #elif defined(TARGET_LPC1768) that needs to be changed to an or with the correct target for the STM32F4. 

It is just two steps to do this.

* Edit platformIO.ini to have STM32F4 use the code from Adafruit's github. This should make it download the library automatically..
* Navigate to Adafruit_NeoPixel.cpp and add the STM32F4 target into the correct define

**Comment by ledfreak3d** [comment]
Ill give it a go and update you

Op di 30 jul. 2019 11:45 schreef mikeshub <notifications@github.com>:

**Comment by ledfreak3d** [comment]
Ok  its looking like this is going to work was abl to compile atleast let me check if they also work

 

Van: mikeshub <notifications@github.com> 
Verzonden: dinsdag 30 juli 2019 11:45
Aan: MarlinFirmware/Marlin <Marlin@noreply.github.com>
CC: Martijn <ledfreak3d@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [MarlinFirmware/Marlin] [BUG] STM32F407ZGT6 Neopixel Support unable to compile (#14756)

 

You need to edit your platformio.ini. In STM32F4 neo pixel is in the ignore. This is because the library does not really support 32 bit targets. If you want to help add support for neopixels to the STM32F4 here is what needs to be tested. The Adafruit NeoPixel library was just updated to work with LPC1768 targets. I'm pretty sure this is an easy fix, but I don't have an STM32F4 board to test this with. Here is the relevant code for anyone who feels like trying the fix:

adafruit/Adafruit_NeoPixel@ <https://github.com/adafruit/Adafruit_NeoPixel/commit/0f78242a630d6d0ea27be42c9f830b9d17e9bc00> 0f78242

What needs to happen is where it has #elif defined(TARGET_LPC1768) that needs to be changed to an or with the correct target for the STM32F4.

It is just two steps to do this.

*	Edit platformIO.ini to have STM32F4 use the code from Adafruit's github. This should make it download the library automatically..
*	Navigate to Adafruit_NeoPixel.cpp and add the STM32F4 target into the correct define

**Comment by ledfreak3d** [comment]
Hey Mike 

 

It does compile without errors now

But no light yet tried several of the  spare i/os but nothing yet

 

Van: mikeshub <notifications@github.com> 
Verzonden: dinsdag 30 juli 2019 11:45
Aan: MarlinFirmware/Marlin <Marlin@noreply.github.com>
CC: Martijn <ledfreak3d@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [MarlinFirmware/Marlin] [BUG] STM32F407ZGT6 Neopixel Support unable to compile (#14756)

 

You need to edit your platformio.ini. In STM32F4 neo pixel is in the ignore. This is because the library does not really support 32 bit targets. If you want to help add support for neopixels to the STM32F4 here is what needs to be tested. The Adafruit NeoPixel library was just updated to work with LPC1768 targets. I'm pretty sure this is an easy fix, but I don't have an STM32F4 board to test this with. Here is the relevant code for anyone who feels like trying the fix:

adafruit/Adafruit_NeoPixel@ <https://github.com/adafruit/Adafruit_NeoPixel/commit/0f78242a630d6d0ea27be42c9f830b9d17e9bc00> 0f78242

What needs to happen is where it has #elif defined(TARGET_LPC1768) that needs to be changed to an or with the correct target for the STM32F4.

It is just two steps to do this.

*	Edit platformIO.ini to have STM32F4 use the code from Adafruit's github. This should make it download the library automatically..
*	Navigate to Adafruit_NeoPixel.cpp and add the STM32F4 target into the correct define

**Comment by ledfreak3d** [comment]
Changed all of them compiles ok but no output on any pins

 

Van: mikeshub <notifications@github.com> 
Verzonden: dinsdag 30 juli 2019 11:45
Aan: MarlinFirmware/Marlin <Marlin@noreply.github.com>
CC: Martijn <ledfreak3d@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [MarlinFirmware/Marlin] [BUG] STM32F407ZGT6 Neopixel Support unable to compile (#14756)

 

You need to edit your platformio.ini. In STM32F4 neo pixel is in the ignore. This is because the library does not really support 32 bit targets. If you want to help add support for neopixels to the STM32F4 here is what needs to be tested. The Adafruit NeoPixel library was just updated to work with LPC1768 targets. I'm pretty sure this is an easy fix, but I don't have an STM32F4 board to test this with. Here is the relevant code for anyone who feels like trying the fix:

adafruit/Adafruit_NeoPixel@ <https://github.com/adafruit/Adafruit_NeoPixel/commit/0f78242a630d6d0ea27be42c9f830b9d17e9bc00> 0f78242

What needs to happen is where it has #elif defined(TARGET_LPC1768) that needs to be changed to an or with the correct target for the STM32F4.

It is just two steps to do this.

*	Edit platformIO.ini to have STM32F4 use the code from Adafruit's github. This should make it download the library automatically..
*	Navigate to Adafruit_NeoPixel.cpp and add the STM32F4 target into the correct define

**Comment by ledfreak3d** [comment]
Hey Mike

 

 

Ok so i twill compile but no output at all 

See modified files for more info

**Comment by mikeshub** [comment]
I'm not seeing the files. 

I'm not 100% but I think you will want to or the TARGET_LPC1768 with STM32GENERIC.

**Comment by ledfreak3d** [comment]
Here you go fors ome reason they where not included but they where in my send email very wierd

 

Van: mikeshub <notifications@github.com> 
Verzonden: woensdag 31 juli 2019 00:46
Aan: MarlinFirmware/Marlin <Marlin@noreply.github.com>
CC: Martijn <ledfreak3d@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [MarlinFirmware/Marlin] [BUG] STM32F407ZGT6 Neopixel Support unable to compile (#14756)

 

I'm not seeing the files.

**Comment by ledfreak3d** [comment]
not been able to get it working yet

**Comment by Evg33** [comment]
It's worked ! :)

https://youtu.be/uGW9yKVrxyU

**Comment by Evg33** [comment]
https://github.com/adafruit/Adafruit_NeoPixel/pull/206#issuecomment-531297764

**Comment by Evg33** [comment]
ladyada merged commit ccba64f into adafruit:master 1 hour ago

**Comment by Evg33** [comment]
Neopixel library fixed
https://github.com/MarlinFirmware/Marlin/issues/14484#issuecomment-531298624

**Comment by boelle** [comment]
@ledfreak3d still having issues?

**Comment by ledfreak3d** [comment]
Hey Bo Nope working great now

Op di 24 sep. 2019 21:26 schreef Bo Herrmannsen <notifications@github.com>:

**Comment by boelle** [comment]
oki closing then

**Comment by ledfreak3d** [comment]
Thsnks Bo

Op di 24 sep. 2019 21:33 schreef Bo Herrmannsen <notifications@github.com>:
