### ISSUE TITLE
[QUESTION] adding some code on marlin

### ISSUE THREAD

**Issue by henryprobosantoso** [MarlinFirmware/Marlin#14765]
i want to add some code like "analogWrite(PIN, Value)" whenever the extruder move, but i am confused about where should i place the code, please tell me how to do it.
thanks.

**Comment by reloxx13** [comment]
tell us what u want to do.
there are gcodes to trigger a pin.

**Comment by henryprobosantoso** [comment]
i just want to replace Extruder stepper with motor DC, and to control it i use PWM, so i just want to place code that generate PWM whenever the extruder move also when stop the PWM will be zero. But i dont know where to place it...
thanks ind advance

**Comment by shitcreek** [comment]
Did you ever figure this one out? We currently have M106, M3 and M4 to PWM power a spindle, laser or fan. I think it would be great to have it apart of G1 and utilizing the S parameter instead, especially in the case of a laser.

**Comment by henryprobosantoso** [comment]
yeay thanks @shitcreek , btw finally i can add some PWM function, with M106, thanks all, what i did just give a simple analogWrite function inside gcode_M106 function on marlin_main.cpp file, thanks all
