### ISSUE TITLE
[BUG] Possible Bug autolevel

### ISSUE THREAD

**Issue by Louis-Cypher** [MarlinFirmware/Marlin#14766]
Starting mid of May version of Marlin 2.0.x I cannot autolevel anymore. I tried to change various parameters starting from Z- probing speed to z-axis Minimum positions etc but sadly cannot get autobed leveling working again.

Others have reported the same behavior: https://reprap.org/forum/read.php?415,852720,853793#msg-853793

## Machine
Core XY running most recent datecode of Marlin 2.0.x. Same behaviour if running most recent 1.x Version. Used bilinear probing as well as linear. Inductive probe.

## What happens
G28 works fine
G29 starts leveling but more or less arbitrarily  stops with message "probing failed". I can see that the z-probe is triggered correctly. I enabled debugging but I cannot find anything of help in the debugging output. Please find debugging output as well as configuration attached. 

End of debugging- log:
```
>>> do_blocking_move_to(70.00, 39.00, 3.00)
<<< do_blocking_move_to
echo:busy: processing
  current_position=(70.00, 39.00, 3.00) : set_probe_deployed
deploy: 0
>>> do_blocking_move_to(70.00, 39.00, 3.00)
<<< do_blocking_move_to
Error:Probing failed
<<< probe_pt
  current_position=(70.00, 39.00, 3.00) : set_probe_deployed
deploy: 0
  current_position=(70.00, 39.00, 3.00) : > probing complete
<<< G29
X:70.00 Y:39.00 Z:3.00 E:0.00 Count A:8720 B:2480 Z:7680
ok
```

[leveling_debug.txt](https://github.com/MarlinFirmware/Marlin/files/3440955/leveling_debug.txt)

[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/3440971/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/3440972/Configuration_adv.h.txt)

**Comment by robbycandra** [comment]
It is not a bug.

You should raise your bed. 

It is fail because the probe cannot reach your bed. 
The correction should not bigger than 2 mm.

Another workaround is to change 
```
Z_PROBE_LOW_POINT -2
```
to bigger negatif number like -3

``
>>> do_blocking_move_to(70.00, 39.00, -2.00)
<<< do_blocking_move_to
echo:busy: processing
  current_position=(70.00, 39.00, -2.00) : sync_plan_position
  current_position=(70.00, 39.00, -2.00) : <<< do_probe_move
SLOW Probe fail!
  current_position=(70.00, 39.00, -2.00) : <<< run_z_probe
```

**Comment by Louis-Cypher** [comment]
Thanks a lot. That helped.

**Comment by Louis-Cypher** [comment]
Sorry, but I am not convinced that this behavior is correct. To which respect should I raise the bed? I am using the same probe for homing and bed leveling. It is an inductive probe connected to the Z-min limit switch connector. Hence, there should be no difference in Z-height. I changed the value to -3 and have the same problem again.

**Comment by Louis-Cypher** [comment]
For documentation purpose: During trying to fix the problem I misinterpreted and changed Z_PROBE_LOW_POINT to -3. This causes an offset of 3mm to the probe causing the problem detailed above (BTW: to me the comment behind the variable was not clearly understandable; I discovered the solution by searching something probe related in the config)
