### ISSUE TITLE
[BUG] X-axis prints concave.

### ISSUE THREAD

**Issue by Scratchbuild52** [MarlinFirmware/Marlin#14769]
Hi there,

I am not sure how long this issue exists because previously I just printed smaller pieces like parts of a printer etc. I now tried to print a print that was relatively big in size and I saw that it was printing the x-axis as concave. See attached picture. I now tried almost everything I could to get rid of the behaviour but the more I try the more I am convinced it must be a calculation error.

I can also detect the same happens when I do UBL bilinear by keeping my eye on the y-axis to see if it moves when it travels in the x-direction.

My hardware are as follows:
                             1) Hypercube Evolution
                             2) Marlin-2.Bugfix.1.1.x
                             3) Re-Arm Controller with Ramps 1.4 
                             4) DRV8825 stepper drivers 1/32 microstepping
                             5) 0.9 degree stepper motors

### Steps to Reproduce

1. I just need to create a stl that spans the whole x-axis of my printer: 270 x 290 x 250. 
2. Print the stl

**Expected behavior:** [What you expect to happen]

I expect the x-axis to print in a straight line from the beginning to the end.

**Actual behavior:** [What actually happens]

The printer prints the x-axis in a concave manner as shown in the photograph.
I also expect the x-axis to print a diagonal line where there is a binding problem, stepper problem or a driver problem. I would not expect the concave line it is printing at this stage because this will mean it prints to the middle of the line and then somehow detects there is a problem and then try to correct itself.

![Concave](https://user-images.githubusercontent.com/15769642/62045738-7096f500-b206-11e9-842c-06450b721c81.jpg)

When I look at the belts at the back of the printer I can clearly see the one belt is slower than the other and then in the middle the other stepper is slower. They should be traveling at precisely the same speed to accomplish a straight line.

#### What I did to try and find the problem:

1) I first checked the stl file if that is correct and verified it with one of my friends. I then created the stl file for printing the bands as in the picture.
2) I checked that there is no binding on any of the axis's.
3) I have retightened the belts
4) I have checked that the driver pulleys are the same size
5) I have downloaded the latest bugfix.

The only two things I did not try was replacing the stepper motors 

 and the drivers but as far as I can gather that will not cause a concave line but rather a diagonal or erratic diagonal line.

I have also attached the config files and the stl I am testing with. I just copied the stl a few times to get what I printed in the photo.

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/3441856/Configuration_adv.zip)

Regards

Nic

[Test.zip](https://github.com/MarlinFirmware/Marlin/files/3442132/Test.zip)

**Comment by shitcreek** [comment]
I recommend using bugfix 2.0 because if this is a bug, it might have already been addressed.
Have you printing the model rotated by 90* and see if you're getting the same result? You could try swapping x motor for y (more appropriately delta A motor and delta B motor) instead of replacing them by switching their plugs. You could also try swapping the drivers.

**Comment by Scratchbuild52** [comment]
Thanks for the reply. Will do, just picked up another problem, have to get a part printed before I can try again.

**Comment by RudyBenner** [comment]
Does the bed have to be square? 
Line 1050-1051

**Comment by thinkyhead** [comment]
If the X-axis smooth rods are at all twisted in relation to each other it can cause the gantry to twist, which moves the nozzle slightly in the Y direction. Look very carefully from the side, or set up a fixed camera, and observe whether the nozzle shifts at all as the carriage moves along the X axis.

**Comment by thinkyhead** [comment]
Rather than attaching the STL file, you should attach your `.gcode` file.

**Comment by thinkyhead** [comment]
Just in case this is not a bug, be sure to take advantage of the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by Scratchbuild52** [comment]
That would have been the next thing I checked, but I am busy with projects
at work and cannot look at it right now.
Will let you know as soon as I can and give feedback.

**Comment by lpgreini** [comment]
Hi,
I had the very same issue with my Hypercube Evolution. I tested firmwares 1.1.8, 1.1.9, 2.0.x bugfix. The issue was there on any firmware I tested. So I tested Repetier Firmware and, well, the issue was there too ;-)
So I began to switch hardware and the faulty part was the belts. I wanted to have the best and used those steel core belts. Those were just too hard for this kind of setup. I switched back to nylon core rubber belts and everything is fine now.
Give it a try ;-)

**Comment by lpgreini** [comment]
I forgot to say: no matter what belts you are using, it is worth switching them to others. Even if it's not steel core or something other special. They just may be of bad quality...

**Comment by Scratchbuild52** [comment]
Hi Lpgreini,
                     Thanks for your reply. At least I feel I have
somewhere to start. I actually do have the steel core belts on my printer,
well not now, I have pulled almost my whole printer apart to check it for
sqaureness and dimensional problems. I have quite a bit of building to do
to get back at the printing stage :-) , but I will definitely try the
switching of the belts.
Thanks again.

**Comment by Scratchbuild52** [comment]
Just feedback: It was the belts that was the problem
