### ISSUE TITLE
[BUG] STM32 #if (PC8 == PB0) condition passes no matter of I/Os

### ISSUE THREAD

**Issue by trouch** [MarlinFirmware/Marlin#14777]
@tpruvot 

Try this snippet somewhere in your sources, such as config file, with an STM32F1 build:
```
#if PC8 == PB0
   #error "Something weird !"
#endif 
```

You should have error thrown very quick. This issue avoids to use any pin for Ex_AUTO_FAN_PIN, CONTROLLER_FAN_PIN, and such since the pre-compiler fails when comparing them with FAN_PIN at SanityChecks.

**Comment by thisiskeithb** [comment]
Yep: See https://github.com/MarlinFirmware/Marlin/issues/14711 and https://github.com/MarlinFirmware/Marlin/issues/14732.

**Comment by thisiskeithb** [comment]
@tpruvot: There’s definitely something wonky going on with STM32F1.

**Comment by tpruvot** [comment]
indeed, they are enums... not defined constants
https://stackoverflow.com/questions/34677148/why-does-the-c-preprocessor-consider-enum-values-as-equal

**Comment by tpruvot** [comment]
i think i found a solution... but unsure it will work on all STM32F1 see #14785

**Comment by trouch** [comment]
thanks @tpruvot that works for me now 👍 
closing that issue.
