### ISSUE TITLE
[BUG] Motors buzz when HYBRID_THRESHOLD is activated

### ISSUE THREAD

**Issue by juchong** [MarlinFirmware/Marlin#14775]
### Description

Motors begin to buzz (and not move) during a homing operation, specifically during the HYBRID_THRESHOLD transition period. My printer uses TMC2130 drivers and an SKR1.3 board. I'm running the latest Marlin 2.0.x development build and am trying to use native 256 step mode without interpolation. It's important to note that reducing the number of steps to 16 from 256 allows HYBRID_THRESHOLD to operate properly. If HYBRID_THRESHOLD is disabled and the printer is operated in SpreadCycle mode only, then the printer also operates correctly. 

### Steps to Reproduce

1. See attached configuration. 
2. Assuming the hardware mentioned above is used, executing a `G28` command should force the printer to slowly (StealthChop) move the axes until the limit switches click.
3. Once the limit switches are tripped, a movement that should be executed in SpreadCycle mode will cause the motors to buzz loudly. 

**Expected behavior:** Fast movement and less buzzing

**Actual behavior:** Lots of buzzing and no movement

#### Additional Information
Configuration files attached. 
[buzzing_config.zip](https://github.com/MarlinFirmware/Marlin/files/3445472/buzzing_config.zip)

**Comment by mikeshub** [comment]
I'm running 256 microsteps with an SKR1.3 and TMC5160s and I'll try to replicate the hybrid threshold issue. My guess would be the step rates for the thresholds are not scaled up for over 16 microstepping when the calculations are done. 

EDIT: I was unable to replicate the issue. I printed with hybrid threshold. Z axis homed in spread cycle as is expected. The printer operated as expected switching in and out of spreadcycle. 

When you switched stepping modes and enabled hybrid threshold did you remember to use M502 and M500? I ask because I chased my tail a bit on 256 microsteps before realizing that I needed to have it load the right steps per mm. I had put the right steps per mm into the defines, but had neglected to update them in the printer's settings.

In the past whenever I've changed settings for the Trinamics I have best luck with a full power cycle of the printer instead of just hitting the reset button.

**Comment by R0GUEx** [comment]
This sounds for me as if the drivers are not receiving enough current. Have you tried adjusting the vref on your motors? Is your powersupply delivering enough power to the stepper drivers?

**Comment by juchong** [comment]
@mikeshub I issued an M502 followed by an M500 before testing. I also power cycled the printer after loading new firmware images. Could I take a look at your config files? I suspect it's a tiny configuration change that's unique to my setup.
@R0GUEx The printer moves in and out of spread cycle mode as expected when using 16 micro-steps. It also works if I disable StealthChop, so I suspect that insufficient current isn't the issue.

Edit: Video of the issue attached. Even though the G28 command doesn't usually include any "fast" movements if a bed probe is used, the X and Y axes will move quickly to the center of the bed. 
https://youtu.be/f0MR3OqHhQ8

**Comment by teemuatlut** [comment]
@mikeshub The TMCs don't support any gcodes that alter the microstepping setting so M500 doesn't do anything. M502 re-initializes the drivers so maybe that's what helped you. Powering off-on is still a good practice to clear the drivers though.

@juchong Can you try without XY quick homing?

**Comment by mikeshub** [comment]
@teemuatlut M500 does indeed do something which is to save the correct steps per mm. There isn't a gcode for microstepping, but M92 is pretty important when changing microstep modes if the user didn't change the defines to the correct steps per mm when switching microstepping modes. 

@juchong Here are the configs and pins headers.

[SKR.zip](https://github.com/MarlinFirmware/Marlin/files/3448628/SKR.zip)

**Comment by boelle** [comment]
@juchong is the issue still there?

**Comment by juchong** [comment]
@boelle I wasn't ever able to get native 256 microstepping working on my printer, even with the profile @mikeshub linked above. It looks like even his profile isn't using 256 microstepping, so he wouldn't have run into the issue either. I eventually reverted back to extrapolating 16 to 256 steps and moved on, but the bug is still present.

**Comment by boelle** [comment]
@juchong did you use 24V or 12V ? just a question that came to my head

**Comment by juchong** [comment]
@boelle I'm using 24V

**Comment by boelle** [comment]
oki, TMC suggest that as the voltage, so one thing less on the list of possible things

is the buzz loud?

**Comment by juchong** [comment]
Here's a video of the buzz @boelle: https://youtu.be/f0MR3OqHhQ8

**Comment by boelle** [comment]
wow, that is a giant BUZZ @teemuatlut any idea what that could be?

**Comment by teemuatlut** [comment]
Sounds like trying to go too fast.
________________________________

**Comment by boelle** [comment]
makes sense yes, either to fast or to fast and to little amps

**Comment by juchong** [comment]
@teemuatlut Not very likely. I was homing the machine. Keep in mind that reverting the settings to interpolating 256 steps from 16 works well. The issue seems to occur when jumping from stealth chop to the "louder" mode.

**Comment by boelle** [comment]
try home slower anyway, the more microsteps the less torque you have and hence you might need to do it slower

if anythng it can rule out that you are running to fast

**Comment by boelle** [comment]
@juchong did homing slower help? or is the issue still the same?

**Comment by boelle** [comment]
will close this one as it seems that @juchong dont have a problem anymore

we can reopen if multiple can confirm there is an issue with marlin
