### ISSUE TITLE
Missing define BLTOUCH_V3

### ISSUE THREAD

**Issue by DarkAlchy** [MarlinFirmware/Marlin#14783]
I have people telling me to uncomment that line in configuration_adv.h but in last week's commit or today's commit there is no sign of this in V2 bugfix.  Any ideas?

**Comment by thisiskeithb** [comment]
They are using `bugfix-1.1.x` or haven't updated their configs in a while.

Edit: It was removed May 7: https://github.com/MarlinFirmware/Marlin/pull/13814

**Comment by Ludy87** [comment]
https://github.com/MarlinFirmware/Marlin/blob/c1b99c43b6e3aec37dab84cd34357337f2c845fb/Marlin/src/inc/SanityCheck.h#L214

`BLTOUCH_V3 is obsolete. Please update your configuration.`

**Comment by Ludy87** [comment]
https://github.com/MarlinFirmware/Marlin/blob/c1b99c43b6e3aec37dab84cd34357337f2c845fb/Marlin/Configuration.h#L853

https://github.com/MarlinFirmware/Marlin/blob/c1b99c43b6e3aec37dab84cd34357337f2c845fb/Marlin/Configuration_adv.h#L530-L595

**Comment by DarkAlchy** [comment]
Thank you everyone.
