### ISSUE TITLE
[BUG] Marlin 2.0 Bugfix Compile error ESP on BIGTREETECH SKR PRO

### ISSUE THREAD

**Issue by dant220** [MarlinFirmware/Marlin#14790]
#14735 # Description

On the Bugfix 2.0 with the following config files:
[ESP_configs_Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/3449644/ESP_configs_Marlin-bugfix-2.0.x.zip)

I get the following error:
Error: The PlatformIO task detection didn't contribute a task for the following configuration:
{
    "type": "PlatformIO",
    "task": "Build (esp8266)",
    "problemMatcher": [
        "$platformio"
    ]
}
The task will be ignored.
Error: The PlatformIO task detection didn't contribute a task for the following configuration:
{
    "type": "PlatformIO",
    "task": "Build (esp8266)",
    "problemMatcher": [
        "$platformio"
    ]
}
The task will be ignored.

### Steps to Reproduce

1. Install the current release (I downloaded today's July 30 2019)
2. Insert the config files supplied above
3. Compile

**Expected behavior:** [What you expect to happen]
Sucessful Compilation

**Actual behavior:** [What actually happens]
You will see the errors above
#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by RudyBenner** [comment]
Your configuration.h file compiles here successfully. VSCode

**Comment by dant220** [comment]
you need to include the variant.h file. I enabled the following:
#define SERIAL_UART_INSTANCE    6 //ex: 2 for Serial2 (USART2)
I should have included this in the note. It is in the zip file.

**Comment by shitcreek** [comment]
Would you mind closing the issue if it has been resolved.
