### ISSUE TITLE
[FR] Using empty driver slot for turntable

### ISSUE THREAD

**Issue by SFRSKZ** [MarlinFirmware/Marlin#14799]
Im thinking on turntable, designed  files and then i thought messing with arduino and stepper modules and jumpers around... 

 why we dont use e1 for turntable? not an expert on these things but that would be great right? i m also using pi 3b+ and a webcam. so thinking on a little photogrammetry station.  

since ender 3 like printers using 4 motors, there is an empty room for 5. driver (for mks genl
 sgen l or skr boards)

**Comment by thisiskeithb** [comment]
Closing since marlin now supports a slew of extra axes.
