### ISSUE TITLE
Ugly format of values on displays

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#1480]
Fact - unnecessary leading 0s.
PID-s - unnecessary leading 0s - unnecessary sign.
![picture 68](https://cloud.githubusercontent.com/assets/211931/6096713/a769d99c-afa1-11e4-8550-3487b6fe6cf2.jpg)

Vz-jerk  - unnecessary leading 0s - unnecessary sign.
![picture 69](https://cloud.githubusercontent.com/assets/211931/6096714/ab2c5a6e-afa1-11e4-98a5-29ea1687efaa.jpg)

steps/mm all  - unnecessary leading 0s - unnecessary sign.
![picture 70](https://cloud.githubusercontent.com/assets/211931/6096716/aeed4f00-afa1-11e4-8a29-0ab74a11fafc.jpg)

Fact - unnecessary leading 0s.
PID-s - unnecessary leading 0s - unnecessary sign.
![picture 67](https://cloud.githubusercontent.com/assets/211931/6096724/d5ddac90-afa1-11e4-9a17-8767d5854385.jpg)

Vz-jerk - unnecessary leading 0s - unnecessary sign.
![picture 63](https://cloud.githubusercontent.com/assets/211931/6096720/c2e4bc96-afa1-11e4-866b-8ff492037738.jpg)

steps/mm all  - unnecessary leading 0s - unnecessary sign.
![picture 65](https://cloud.githubusercontent.com/assets/211931/6096719/bad00790-afa1-11e4-8e49-383a1b1fcda8.jpg)

Will try to fix.

**Comment by thinkyhead** [comment]
Great! I recently did this with the Z display on the status screen. More pleeze!

**Comment by thinkyhead** [comment]
We can move this conversation to the PR when that's ready. Closing issues to make room for a code freeze, perhaps!
