### ISSUE TITLE
Dual X carriage

### ISSUE THREAD

**Issue by hallphilip** [MarlinFirmware/Marlin#14811]
When I enable Dual X Carriage neither carriage will home and pops up a homing error. If I disable the feature everything homes just fine. any help with this would be great. I am willing to test anything. this was using the latest version on github.

**Comment by InsanityAutomation** [comment]
Turn off x dual endstops. Make sure use_xmin_plug is enabled. Attach the whole config file next time, its easier to look for things in the file where we know what matters than it is to look through a list of changes like this. Also likelihood of something important getting missed like this is high.

**Comment by hallphilip** [comment]
I'll Try that out, and thanks for the advice on future post.

**Comment by hallphilip** [comment]
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/3463946/Configuration.txt)

**Comment by hallphilip** [comment]
That still didn't help, I have no movement on E2, E1 won't home but I can move it manually. I noticed I also can't seem to get the Steps per mm set to use all my values using distinct E values.

**Comment by Roxy-3D** [comment]
@hallphilip    Did you do a M502 and M500 after loading the firmware?     You can either .ZIP up the files and attach them.   Or change the .h to .txt to attach them.

**Comment by hallphilip** [comment]
@Roxy-3D  thanks for the reply. I have not tried M500 or M502 yet because the SKR pro has no EEPROM, yet anyhow. Could that be an issue? Thanks for the info about the file attachment. My first attempt turned into a failure.

**Comment by hallphilip** [comment]
Is there any other info I can add to help solve this?

**Comment by Roxy-3D** [comment]
.ZIP up both the Configuration.h and the Configuration_adv.h files and post them.   The IDEX setup stuff is in Configuration_adv.h.   So that is the most interesting.

Not having EEPROM should not be a problem.   But the reason I was asking was there are a some IDEX setup numbers that get pulled from the EEPROM (if it is present).   For example, the parking location and the X & Y offsets.

**Comment by hallphilip** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3464316/Configuration.zip)
Thanks for the help.

**Comment by Roxy-3D** [comment]
This is an IDEX (Independent Dual Extruder) machine, right?

If so...   To turn on the IDEX features, you need to enable:

#define DUAL_X_CARRIAGE

**Comment by hallphilip** [comment]
It was turned on I had posted the wrong config. I had two on hand so I could still print with T0.

**Comment by hallphilip** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3464361/Configuration.zip)
 here is the correct one

**Comment by hallphilip** [comment]
I found a hardware issue with my E2 driver.

**Comment by InsanityAutomation** [comment]
Sounds good! Thanks for updating.
