### ISSUE TITLE
[FIXED] SKR Mini E3 & E3 DIP - Temp Error if USB connected on boot

### ISSUE THREAD

**Issue by reloxx13** [MarlinFirmware/Marlin#14818]
Heya,

if USB is plugged in and i power on the printer and pi, the printer will STOP with a temp error.

USB Device: Pi3b+ with octoprint, 5v pin taped on the usb plug to avoid back-powering.
Occurs with SKR mini E3 and E3 DIP (Ender 3).
Both are STM32F1, could also hit other STM32F1 boards.

Check other both issues at the bottom.

With the suggested workaround    
`#define BOGUS_TEMPERATURE_GRACE_PERIOD 2000`

The printer shows 72°C E0 and -14°C HB after boot with USB   

I tried multiple reboots.   

After unplugging USB and rebooting, the temp readings are okay.   
Plugging USB in now, the temp readings stay okay.   

#### Additional Information
I tried BTT fw and now im on latest marlin 2.0.x.
Config: https://github.com/reloxx13/Marlin/tree/my-skr-mini-e3/Marlin   

Issues from Bigtreetech   
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/issues/2#issuecomment-513237806
https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/issues/4   

PR STM32F1 SPI1 bugfix https://github.com/MarlinFirmware/Marlin/pull/14679   
   
i can grant a remote connection with USB (Windows/VSC) or a Pi with SSH and SPI pins connected if it helps debugging. Ping me in Discord.

**Comment by lovethat777** [comment]
Can confirm, had to set THERMAL_PROTECTION_GRACE_PERIOD to 6000 (ms)

**Comment by thinkyhead** [comment]
@p3p — I wonder if we can do something to get readings stabilizing or the ADCs initialized in a safer manner, and in some way get temperature readings started before SD initialization, even in those cases where settings need to be fetched from SD. I'm not sure the latency improvement can do anything about the readings we get on bootup being equivalent to a thermal runaway.

In the meantime we could try add some logging to the temperature reading and SD init routines and see what's going on in detail during these long boot-ups.

**Comment by reloxx13** [comment]
Wouldnt it be enough to update the temp reading after boot?   
It just sits there with the wrong temp on the LCD.   
   
When i connect USB after it booted, in octoprint i can see the correct temp readings.   
But im not sure now if i could start a print, sometimes it get bugged and wont execute any command, but it shows "connected".

**Comment by p3p** [comment]
@thinkyhead I can't really comment on whats going on with the STM boards, I don't know if they use any filtering (in addition to Marlins) like the LPC176x , as far as I can tell since adjusting the LPF the LPC176x doesn't have any issues at boot.

**Comment by opcow** [comment]
Just installed an SKR E3 DIP. My bogus temps are on the hotend and bed. I see 298C on the HE using a USB cable with no 5v line, -14C on the HE or both heaters if powered. The workaround of using BOGUS_TEMPERATURE_GRACE_PERIOD doesn't help since the bogus temp is never resolves.

Edit: the difference in readings is unrelated to the 5v line being active. Upon further testing, a connection to my Linux hosts (a PC running Ubuntu 19.04, and a Raspberry Pi running Raspbian)  causes the 298C reading. When connected to Windows 10 I get the -14C readings.

**Comment by lovethat777** [comment]
Are you using the lastest 2.0 bugfix release, if yes, THERMAL_PROTECTION_GRACE_PERIOD was [just removed](https://github.com/MarlinFirmware/Marlin/commit/5bc2fb022ca437d7e70f195bdb7d946ceb3a623a)

**Comment by tomoinn** [comment]
This is fixed, can confirm it's not an issue with the latest bugfix on skr mini e3
