### ISSUE TITLE
[BUG] During a print job Z does not engage.

### ISSUE THREAD

**Issue by DarkAlchy** [MarlinFirmware/Marlin#14822]
CoreXY (TronXY X5S) and before a print job I can easily G1 anywhere with Z but as soon as a print job begins Z disengages and never lowers with each layer.  I tried this with pronterface as a well as via the sd card and when I start the print I can move Z by hand with ease when it should be locked/engaged and hard to move as it sits ready to take layer commands.

G28 in any gcode file and X goes home, Y goes home, Z goes home and you can hear the click when the Z motor disengages.

**Comment by reloxx13** [comment]
upload ur configs.

which marlin version?

**Comment by J-charles-C** [comment]
I,

With day's commit, no problem with my Hypercube (CoreXY) and Re-Arm Motherboard.
best

**Comment by DarkAlchy** [comment]
I firmly believe, and I am about to test this, that the two issues I have up are interelated because I use 4800 steps/mm for Z.

**Comment by DarkAlchy** [comment]
Yep, I just tested and the 4800 steps/mm is the culprit and when I go to print nothing but I changed it to 2400 and Z was engaged and moved as it should.

**Comment by sjasonsmith** [comment]
I rebased my firmware last night to make sure I'm using the latest changes. While I've confirmed the issue configuring values > 3276 through the LCD, I've also verified that I can print fine with 6400 Z steps/mm when I configure it through the Configuration.h (with an EEPROM reset) or using the M92 command.

Either you don't have the right value saved (a stale value in the EEPROM will overwrite anything you change in Configuration.h), or some other configuration issue is at play. As reloxx13 said, you would need to upload your configuration files for anyone to be able to help with that. I'd also be interested in the output from a M503 command when you have the issue reproducing.

**Comment by DarkAlchy** [comment]
My EEPROM is off so I am only using configuration.h values.

**Comment by DarkAlchy** [comment]
I don't know what is going on and I am flustered beyond all belief.

I just changed over from 16 microstepping to 8 and changed my steps per mm from 4800 to 2400 and when I home Z it goes up and hits the endstop and locks up (M119 shows the endstop is triggered).  At least 4800, and 16, I can home Z.

Here are my config files with the 16 and 4800 in them and I hope someone spots something because I can't get Z to work.

@reloxx13 This is Marlin 2.0

[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/3464396/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/3464397/Configuration.txt)

**Comment by sjasonsmith** [comment]
Can you try reducing the max Z speed?

I know you've said your hardware can handle 30 mm/s, but that would require steps at 144 kHz, just for your Z axis. I have no idea how much Marlin can keep up with in your configuration, but lowering the speed will be a good troubleshooting step.

When I look at the examples which use high step rates, they almost all use a max Z speed of 5 mm/s. That would be a good place to start, and it close to your homing speed (6.66 mm/s) which seems to be working.

Also, can you verify whether you are running from a 12 or 24 V power supply?

**Comment by gloomyandy** [comment]
You might also want to set...
#define MINIMUM_STEPPER_PULSE 2
the default settings can cause problems with TMC drivers with SKR boards.

**Comment by DarkAlchy** [comment]
@gloomyandy That is a new one to me.

I switched out the driver for Z with a spare I had and it worked and 1/2 stepping while the other would not print.  Could that be because of that PULSE?

**Comment by DarkAlchy** [comment]
I am on 12v and I am down to 10mm/s on Z and homing, as well as non print moves, works.  10 is good for this from what I can see and hear from the motor.

**Comment by sjasonsmith** [comment]
Did you increase the pulse, as @gloomyandy suggested, or just change the speed? I'm wondering whether your speed could be cranked back up with the pulse increased.

Also, you have INTERPOLATE enabled for your drivers, so I suspect you won't hear much difference between 1/8 or 1/16 microstepping. Both should get interpolated to 1/256 on the motor side.

**Comment by DarkAlchy** [comment]
Interpolate I just turned on and is much quieter but not as quiet as it would be as more steps.  The speed I reduced and all of this is before gloomy's response.  Right now I am fighting with Amazon over this driver (on chat now with them)  and looks like I have to return all of this so when done I will install gloomy's suggestion and report back.

btw, I could not get 1/8 to work either so went to 1/2.

**Comment by DarkAlchy** [comment]
I can't tame Z.  I have tried gloomy's suggestion and suddenly everything stopped working even when I reverted back.

I don't get it because it homes and just plain locks up as soon as it hits the home button and that is where it stays.  I let the print test run to completion and M114 never responds.  Home Z no response.  Steps no longer matters nothing matters that I have tried yet X, Y, E0 works.

What can I try next?

**Comment by DarkAlchy** [comment]
Question but if I have this #define DEFAULT_MAX_FEEDRATE          { 500, 500, 5, 50 }  and I do a G1 Zxx F6000 shouldn't that 5 (300mm/m) make the F6000 into a F300?  I know in Marlin 1.x it did.

**Comment by DarkAlchy** [comment]
Something weird but I used to use Marlin from beta through 1.1.8 and setting the max feedrate was a global override but no longer.

Max feedrate
This is an important setting, it limits the seed of an axis. If the speed is to high,
the stepper motor will 'loose' steps, and your print will fail. The default is:
#define DEFAULT_MAX_FEEDRATE {1000, 1000, 500, 500} // (mm/sec)
For most printer the value 500 for the z axis is much to high, 5 is probably a
better choice.

I have - #define DEFAULT_MAX_FEEDRATE { 500, 500, 5, 50 } and if I do a G1 Zxx F6000 it stalls out the motor because it was too fast (you can hear it whine but not move) so I wonder why the global is no longer working as it used to?

**Comment by DarkAlchy** [comment]
As a final gasp I went into the pins file and made E1 my Z to test if there might have been a bad pin or solder joint or port, etc... and exactly the same outcome.  I have done all of the testing that I can, and I have tried all avenues with complete failure so nothing left that I can do for now.  I might not be able to use this SKR until Repetier catches up or Marlin 2.x does.  Not sure why it is just me but I am used to it.

Thank you to everyone who attempted to help but I am leaving this issue up since it has not be fixed.

**Comment by thinkyhead** [comment]
> For most printer the value 500 for the z axis is much to high, 5 is probably a

Indeed. Only the DELTA configurations use such high rates.

**Comment by DarkAlchy** [comment]
This issue is in Marlin and has not been solved so why the closing of it?

@thinkyhead Did your finger slip or are you trying to slip this issue under the rug?  No where did I say I have 500 for Z as that is beyond nuts and would not work no matter what I attempted to use.  The 500 I mentioned was from a quote from a website about Marlin and Marlin 2.0 is not obeying its own rules.  It is sporadic when it will or not but it is there.  If I shove a F6000 up its rear to move Z Z should cap at 300 (which is the 5 I use).
