### ISSUE TITLE
[BUG] [Bugfix 2.0.x] Invalid characters displayed

### ISSUE THREAD

**Issue by lovethat777** [MarlinFirmware/Marlin#14830]
### Description

Marlin 2.0

When using REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER, sometimes the "highlighted character" (i.e. the one being adjusted), for example when setting the bed temperature, is *sometimes* incorrect. Link to the exact model: https://www.aliexpress.com/item/32823608306.html

My wiring seems correct and the LCD works as expected (except from this bug)

The default configuration is used:
> #define LCD_LANGUAGE en
#define DISPLAY_CHARSET_HD44780 JAPANESE

Example below. The text should be "+013.0".

![invalid_char](https://user-images.githubusercontent.com/51493833/62417041-70ec2180-b646-11e9-83f5-9dddef3f562b.jpg)

If I use the knob back and forth, I can make it display "+013.0" as it should. The LCD has no dead pixel.

### Steps to Reproduce

1. Use the scroll wheel when setting any value using the LCD

**Expected behavior:** The correct text should be displayed

**Actual behavior:** Invalid characters are sometimes displayed

#### Additional Information

[Conf.zip](https://github.com/MarlinFirmware/Marlin/files/3464358/Conf.zip)

**Comment by thisiskeithb** [comment]
Have you tried shortening the cables/shielding them? The plain/common ribbon cables are prone to interference.

**Comment by AnHardt** [comment]
In the upper half of the screen is still half of a "1" visible.
This is not a noise problem but a consequence of violating u8gLibs [picture loop](https://github.com/olikraus/u8glib/wiki/tpictureloop).
You shall not change display content while in the picture-loop! - Or you have to redraw the entire screen.

**Comment by lovethat777** [comment]
This is clearly a bug that needs to be addressed. I'm seeing it consistently.

**Comment by boelle** [comment]
#define LCD_LANGUAGE en
#define DISPLAY_CHARSET_HD44780 JAPANESE

i always change it to WESTERN as i dont read or speak japanese

i never looked in to what the difference is but i have never had an issue when set to western

**Comment by 7eggert** [comment]
The DISPLAY_CHARSET_HD44780 is the burned-in character-set of your device. As long as you're using A-Z only, you won't notice an error, but for European languages, you'll see wrong characters on your **non-graphical** screen (not the screen used by the bug reporter).

**Comment by lovethat777** [comment]
Indeed, DISPLAY_CHARSET_HD44780 is the hardcoded charset of the device and cannot be changed by simply re-defing that directive.

> 
> 
> In the upper half of the screen is still half of a "1" visible.
> This is not a noise problem but a consequence of violating u8gLibs [picture loop](https://github.com/olikraus/u8glib/wiki/tpictureloop).
> You shall not change display content while in the picture-loop! - Or you have to redraw the entire screen.

This seems to be the problem

**Comment by boelle** [comment]
@lovethat777 is the issue still there?

**Comment by xyyx** [comment]
I have same issue on skr 1.3 and biqu reprap display clone

**Comment by boelle** [comment]
i have put the confirmed bug label on this one,  using a re-arm myself i have never seen this, but then again i use english as language (thou i'm from DK)

**Comment by boelle** [comment]
So how do we fix this one for good?
@AnHardt @thinkyhead @shitcreek

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
