### ISSUE TITLE
[Question] Serial Port RAMPS 1.4 AUX-4

### ISSUE THREAD

**Issue by AFUman** [MarlinFirmware/Marlin#14835]
Hello,
I would like to create a second comport for my WLAN module ESP-01. I would like to use AUX-4 D16 and D17 on my RAMPS 1.4. Where do I have to set this?
I am a freshman in 3D Printing and Marlin. Would be happy about a tip.

Chris

Marlin 1.1.9
TinyBoy E10 with TinyOLED V1.2

**Comment by shitcreek** [comment]
Look in the pins_RAMPS.h file.

Next time, try the Discord channel and/or our Facebook page as this place is for issue reporting and feature requests.
