### ISSUE TITLE
[Tool] for Development stepper.cpp

### ISSUE THREAD

**Issue by tonnico** [MarlinFirmware/Marlin#1484]
Hi guys,

I made a small Python tool. It uses math and matplotlib and simulate the stepper.cpp and a little bit the planner.cpp. You can easily take a look how the acceleration and deceleration works.

Maybe someone finds this usefull.

https://github.com/Wurstnase/Marlin4Due/tree/marlin4due_alpha/Scripts

**Comment by thinkyhead** [comment]
Wow, very nice. I'm sure the slicer writers will love to have this in their toolbox.

**Comment by tonnico** [comment]
now with quadstepping and plot with steps

**Comment by boelle** [comment]
should this be a feature request or a bug?

**Comment by tonnico** [comment]
This was just a small script to see how the stepper.cpp works. Nothing which will help most of programmers.
