### ISSUE TITLE
[BUG] M112 does not braek heat cycles when buffer is not empty

### ISSUE THREAD

**Issue by maukcc** [MarlinFirmware/Marlin#14864]
M112 stops M109 and M190 heat cycles, but only if the buffer is empty.

**Comment by GMagician** [comment]
maybe because emergency parser is not enabled?

http://marlinfw.org/docs/gcode/M112.html

**Comment by maukcc** [comment]
emergency parser is enabled.

**Comment by AnHardt** [comment]
Until now, EMERGENCY_PARSER is not available/implemented on all platforms. What are you testing with.

**Comment by maukcc** [comment]
MEGA2560

**Comment by maukcc** [comment]
I am guessing that Octoprint is the culprit here. As it is waiting for the buffer to clear before it sends any other command.
