### ISSUE TITLE
[BUG] SKR mini V1.1 can not compile with branch 4378

### ISSUE THREAD

**Issue by Udo-Nbg** [MarlinFirmware/Marlin#14872]
Could not Compile branch 4378 with SKR Mini V1.1

The previous branch 4350 i can compile and most Featutes (not fully integrated yet) works fine (TXT/GFX Display, Hotend, Thermistors, Fan)

The Setings are identical.
also when i copy the "configuration.h" from branch 4350 to branch 4378 i get the same errors.

**Comment by Ludy87** [comment]
what is the error message?

**Comment by Udo-Nbg** [comment]
Her are my complete Compiling Logs...
[Error Compiling-LOG SKR-MINI_V1.1 Marlin-bugfix-2.0.x branch 4378.txt](https://github.com/MarlinFirmware/Marlin/files/3478317/Error.Compiling-LOG.SKR-MINI_V1.1.Marlin-bugfix-2.0.x.branch.4378.txt)
[Success Compiling-LOG SKR-MINI_V1.1 Marlin-bugfix-2.0.x branch 4350.txt](https://github.com/MarlinFirmware/Marlin/files/3478319/Success.Compiling-LOG.SKR-MINI_V1.1.Marlin-bugfix-2.0.x.branch.4350.txt)

**Comment by Ludy87** [comment]
The bugfix is still in the waiting loop
https://github.com/MarlinFirmware/Marlin/pull/14861

**Comment by Ludy87** [comment]
@Udo-Nbg
fix is deployed

**Comment by Udo-Nbg** [comment]
branch 4382
it compile successful
and it should work

Thank You

**Comment by UncleBansh** [comment]
"@tpruvot tpruvot force-pushed the tpruvot:stm32f1_tmc_serial  branch from 943a543 to b76bf93 2 days ago"

after this dont compile on skr e3 dip
and compiling after delete this files
