### ISSUE TITLE
[Question] Disable Fan on pause

### ISSUE THREAD

**Issue by elahroodi** [MarlinFirmware/Marlin#14871]
Does anyone know how to Disable Fan on pause and Enable it on Resume ??
I really need it. thank for your help.

**Comment by InsanityAutomation** [comment]
Under ADVANCED_PAUSE_FEATURE in configuration_adv.h enable ADVANCED_PAUSE_FANS_PAUSE.

In the future, please utilize resources such as the discord server or facebook groups for general questions. This queue is intended for bug reports and development.
