### ISSUE TITLE
[BUG] E steps settings only in hundreds

### ISSUE THREAD

**Issue by kihope** [MarlinFirmware/Marlin#14884]
When i want set esteps in LCD only values are 0 - 100 - 200 - 300 etc, my board is skr 1.3

**Comment by macasero** [comment]
same here, also Initialitate eprom, doesn´t seam to work fine.

Pronterface M92 setting, M500 and M503 shows correct steps, but lcd settings only show units and set to hundreds

**Comment by shitcreek** [comment]
What version of Marlin are y'all using? Please provide more information.

**Comment by kihope** [comment]
I have Marlin 2, i downloaded about day ago when i was updating the printer

**Comment by shitcreek** [comment]
Could you provide your configs? What happens when you turn the dial fast vs slow?

**Comment by kihope** [comment]
https://github.com/kihope/TevoTrantula_Marlin-2.0_SKR_v1_3/blob/master/Configuration.h

Dont mind the mess please, i can change steps in config, however when i go to lcd all goes by hundred, so i even cant get the values i had before back, before step were able se by tenths if i remember now only by hundreds (as i mentioned: 0,100,200,nnn.. way up) i dont think it is caused by my config..

**Comment by shitcreek** [comment]
I don't see anything out of place in your config.
Are you using JimBrown's easyConfig 2.0 or Marlin bugfix 2.0?

**Comment by tpruvot** [comment]
see e7b3720b8193c76d1766898923b59261371e1c79 for a possible way to fix that. btw the default config for Z and E steps are incredibly huge imo

**Comment by MasterTim17** [comment]
I reverted this commit [2d98bb](https://github.com/MarlinFirmware/Marlin/commit/2d98bb39bd4cf0820fd3a0e6af33b1fdcae991c6) but havent tried it since then again
