### ISSUE TITLE
[BUG] Custom bootscreens not shown with MKS_MINI_12864 LCD

### ISSUE THREAD

**Issue by thisiskeithb** [MarlinFirmware/Marlin#14889]
### Description

Custom bootscreens are not shown when using the MKS Mini 12864 LCD (`MKS_MINI_12864`). This is similar to https://github.com/MarlinFirmware/Marlin/issues/13977, but is not specific to the SKR 1.3 (issue occurs on any hardware as long as the MKS Mini 12864 LCD is enabled.

### Steps to Reproduce

I'm testing with the default [Tevo Michelangelo](https://github.com/MarlinFirmware/Marlin/tree/2971b48a128662ab2f50a0a238aedfb64ec785d9/config/examples/Tevo/Michelangelo) configs/MKS Gen-L specifically, but this occurs on any board with the `MKS_MINI_12864` controller enabled.

**Expected behavior:** Custom bootscreen to be displayed.

**Actual behavior:** Blank screen before Marlin bootscreen/info is displayed.

#### Additional Information

Just to make sure the default Michelangelo bootscreen wasn't bad, I set `LCD_PRINTER_INFO_IS_BOOTSCREEN` and it looks fine.

Edit: Implementing the proposed changes to [u8g_dev_uc1701_mini12864_HAL.cpp](https://github.com/MarlinFirmware/Marlin/pull/14216/files#diff-ac8f66cf7a1dd42d7697eb49afcdae15) by @DrDitto in the now closed PR https://github.com/MarlinFirmware/Marlin/pull/14216, custom bootscreens are still not shown (at least not on the MKS Gen-L).

**Comment by thisiskeithb** [comment]
This appears to also be related to https://github.com/MarlinFirmware/Marlin/issues/14174 and https://github.com/MarlinFirmware/Marlin/issues/13732 since defining the lcd as `MINIPANEL` has the same behavior.

**Comment by thinkyhead** [comment]
If this change is reverted (plus any needed additions) is it better…?
```diff
- #define HAS_LCD_CONTRAST (HAS_GRAPHICAL_LCD && defined(DEFAULT_LCD_CONTRAST))
+ #define HAS_LCD_CONTRAST (                \
+      ENABLED(MAKRPANEL)                   \
+   || ENABLED(CARTESIO_UI)                 \
+   || ENABLED(VIKI2)                       \
+   || ENABLED(AZSMZ_12864)                 \
+   || ENABLED(miniVIKI)                    \
+   || ENABLED(ELB_FULL_GRAPHIC_CONTROLLER) \
+ )
```

**Comment by thinkyhead** [comment]
Consolidating discussion over at #14174…
