### ISSUE TITLE
[BUG] not compiling skr e3 dip TMC2208

### ISSUE THREAD

**Issue by UncleBansh** [MarlinFirmware/Marlin#14892]
### compile errors

> Linking .pio\build\BIGTREE_SKR_MINI\firmware.elf
> .pio\build\BIGTREE_SKR_MINI\liba72\libTMCStepper.a(SW_UART.cpp.o): In function `SoftwareSerial::read()':
> c:\Marlin/.pio\libdeps\BIGTREE_SKR_MINI\TMCStepper\src\source/SW_UART.cpp:331: multiple definition of `SoftwareSerial::read()'
> .pio/build/BIGTREE_SKR_MINI/src/src/HAL/HAL_STM32F1/SoftwareSerial.cpp.o:c:\Marlin/Marlin\src\HAL\HAL_STM32F1/SoftwareSerial.cpp:44: first defined here
> .pio\build\BIGTREE_SKR_MINI\liba72\libTMCStepper.a(SW_UART.cpp.o): In function `SoftwareSerial::available()':
> c:\Marlin/.pio\libdeps\BIGTREE_SKR_MINI\TMCStepper\src\source/SW_UART.cpp:340: multiple definition of `SoftwareSerial::available()'
> .pio/build/BIGTREE_SKR_MINI/src/src/HAL/HAL_STM32F1/SoftwareSerial.cpp.o:c:\Marlin/Marlin\src\HAL\HAL_STM32F1/SoftwareSerial.cpp:40: first defined here
> .pio\build\BIGTREE_SKR_MINI\liba72\libTMCStepper.a(SW_UART.cpp.o): In function `SoftwareSerial::flush()':
> c:\Marlin/.pio\libdeps\BIGTREE_SKR_MINI\TMCStepper\src\source/SW_UART.cpp:362: multiple definition of `SoftwareSerial::flush()'
> .pio/build/BIGTREE_SKR_MINI/src/src/HAL/HAL_STM32F1/SoftwareSerial.cpp.o:c:\Marlin/Marlin\src\HAL\HAL_STM32F1/SoftwareSerial.cpp:50: first defined here
> .pio\build\BIGTREE_SKR_MINI\liba72\libTMCStepper.a(SW_UART.cpp.o): In function `SoftwareSerial::write(unsigned char)':
> c:\Marlin/.pio\libdeps\BIGTREE_SKR_MINI\TMCStepper\src\source/SW_UART.cpp:343: multiple definition of `SoftwareSerial::write(unsigned char)'
> .pio/build/BIGTREE_SKR_MINI/src/src/HAL/HAL_STM32F1/SoftwareSerial.cpp.o:c:\Marlin/Marlin\src\HAL\HAL_STM32F1/SoftwareSerial.cpp:48: first defined here
> .pio\build\BIGTREE_SKR_MINI\liba72\libTMCStepper.a(SW_UART.cpp.o): In function `SoftwareSerial::stopListening()':
> c:\Marlin/.pio\libdeps\BIGTREE_SKR_MINI\TMCStepper\src\source/SW_UART.cpp:133: multiple definition of `SoftwareSerial::stopListening()'
> .pio/build/BIGTREE_SKR_MINI/src/src/HAL/HAL_STM32F1/SoftwareSerial.cpp.o:c:\Marlin/Marlin\src\HAL\HAL_STM32F1/SoftwareSerial.cpp:57: first defined here
> .pio\build\BIGTREE_SKR_MINI\liba72\libTMCStepper.a(SW_UART.cpp.o): In function `SoftwareSerial::listen()':
> c:\Marlin/.pio\libdeps\BIGTREE_SKR_MINI\TMCStepper\src\source/SW_UART.cpp:114: multiple definition of `SoftwareSerial::listen()'
> .pio/build/BIGTREE_SKR_MINI/src/src/HAL/HAL_STM32F1/SoftwareSerial.cpp.o:c:\Marlin/Marlin\src\HAL\HAL_STM32F1/SoftwareSerial.cpp:53: first defined here
> collect2.exe: error: ld returned 1 exit status
> *** [.pio\build\BIGTREE_SKR_MINI\firmware.elf] Error 1

**Comment by tpruvot** [comment]
i dont see any SW_UART.cpp in https://github.com/teemuatlut/TMCStepper/tree/master/src/source

**Comment by UncleBansh** [comment]
I use this lib
https://github.com/bigtreetech/TMCStepper

> i dont see any SW_UART.cpp in https://github.com/teemuatlut/TMCStepper/tree/master/src/source

**Comment by tpruvot** [comment]
ok, so.. try this for now... (ignore the .py stuff)
https://github.com/MarlinFirmware/Marlin/pull/14893/files

**Comment by tpruvot** [comment]
We only start this sotfware serial.. nice to see some code is already made...

**Comment by UncleBansh** [comment]
change
platformio.ini 
[env:BIGTREE_SKR_MINI]
`-DDEBUG_LEVEL=0` 
to
`-DDEBUG_LEVEL=0 -DHAVE_SW_SERIAL`

and
Marlin\src\HAL\HAL_STM32F1\SoftwareSerial.cpp
19 string to
`#if defined(__STM32F1__) && !defined(HAVE_SW_SERIAL)`

compiling with this fine. but cant check work on the board for now

**Comment by tpruvot** [comment]
its a good start..

**Comment by UncleBansh** [comment]
one more compile bug(

> Marlin\src\lcd\ultralcd.cpp: In static member function 'static void MarlinUI::update()':
> Marlin\src\lcd\ultralcd.cpp:767:9: error: 'touch_buttons' was not declared in this scope
>      if (touch_buttons) {
>          ^~~~~~~~~~~~~
> Marlin\src\lcd\ultralcd.cpp:767:9: note: suggested alternative: 'update_buttons'
>      if (touch_buttons) {
>          ^~~~~~~~~~~~~
>          update_buttons
> Marlin\src\lcd\ultralcd.cpp:805:5: error: 'else' without a previous 'if'
>      else wait_for_unclick = false;
>      ^~~~
> *** [.pio\build\BIGTREE_SKR_MINI\src\src\lcd\ultralcd.cpp.o] Error 1

**Comment by sl1pkn07** [comment]
thats is other error unrelated to this bug

https://github.com/MarlinFirmware/Marlin/pull/14912

**Comment by UncleBansh** [comment]
> change
> platformio.ini
> [env:BIGTREE_SKR_MINI]
> `-DDEBUG_LEVEL=0`
> to
> `-DDEBUG_LEVEL=0 -DHAVE_SW_SERIAL`



check on board. all works fine
somebody can add this in pull request? this looks like a fix of compiling for skr mini and skr e3.
then it can be closed. thanx.

**Comment by tpruvot** [comment]
the -DHAVE_SW_SERIAL is only when you add the lib, the custom TMCStepper lib from BIQ is not used in current platformio.ini

**Comment by UncleBansh** [comment]
> the -DHAVE_SW_SERIAL is only when you add the lib, the custom TMCStepper lib from BIQ is not used in current platformio.ini

Okey. can be closed. thank you alot
