### ISSUE TITLE
[BUG] Compile issue Marlin 2.0 for BIGTREETECH SKR Mini E3

### ISSUE THREAD

**Issue by Xenon-2510** [MarlinFirmware/Marlin#14896]
Description
Get  a compilation error when trying to compile for BIGTREETECH SKR MINI E3

Steps to Reproduce
Clone latest Marlin Github 2.0.bugfix
Replace configs with BIGTREETECH->SKR MINI E3->My Configuration files (attached)
Compile using enc:BIGTREE_SKR_MINI
Expected behavior:

Compiles correctly

Actual behavior:

In file included from c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\memory:62:0,
                 from C:\Users\arnoldc.BENTLEY\.platformio\lib\EspSoftwareSerial_ID168\src/circular_queue/circular_queue.h:27,
                 from C:\Users\arnoldc.BENTLEY\.platformio\lib\EspSoftwareSerial_ID168\src/SoftwareSerial.h:27,
                 from .pio\libdeps\BIGTREE_SKR_MINI\TMCStepper_ID5513\src/TMCStepper.h:18,
                 from Marlin\src\module/stepper_indirection.h:47,
                 from Marlin\src\module/stepper.h:221,
                 from Marlin\src\Marlin.cpp:37:
c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\stl_algobase.h:243:56: error: macro "min" passed 3 arguments, but takes just 2
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\stl_algobase.h:265:56: error: macro "max" passed 3 arguments, but takes just 2
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
Compiling .pio\build\BIGTREE_SKR_MINI\src\src\feature\Max7219_Debug_LEDs.cpp.o
In file included from c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\memory:62:0,
                 from C:\Users\arnoldc.BENTLEY\.platformio\lib\EspSoftwareSerial_ID168\src/circular_queue/circular_queue.h:27,
                 from C:\Users\arnoldc.BENTLEY\.platformio\lib\EspSoftwareSerial_ID168\src/SoftwareSerial.h:27,
                 from .pio\libdeps\BIGTREE_SKR_MINI\TMCStepper_ID5513\src/TMCStepper.h:18,
                 from Marlin\src\core\../module/stepper_indirection.h:47,
                 from Marlin\src\core\../module/stepper.h:221,
                 from Marlin\src\core\utility.cpp:42:
c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\stl_algobase.h:243:56: error: macro "min" passed 3 arguments, but takes just 2
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\stl_algobase.h:265:56: error: macro "max" passed 3 arguments, but takes just 2
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
In file included from c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\stl_algo.h:60:0,
                 from c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\algorithm:62,
                 from C:\Users\arnoldc.BENTLEY\.platformio\lib\EspSoftwareSerial_ID168\src/circular_queue/circular_queue.h:28,
                 from C:\Users\arnoldc.BENTLEY\.platformio\lib\EspSoftwareSerial_ID168\src/SoftwareSerial.h:27,
                 from .pio\libdeps\BIGTREE_SKR_MINI\TMCStepper_ID5513\src/TMCStepper.h:18,
                 from Marlin\src\module/stepper_indirection.h:47,
                 from Marlin\src\module/stepper.h:221,
                 from Marlin\src\Marlin.cpp:37:
c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\algorithmfwd.h:375:41: error: macro "max" passed 3 arguments, but takes just 2
     max(const _Tp&, const _Tp&, _Compare);
                                         ^
c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\algorithmfwd.h:388:41: error: macro "min" passed 3 arguments, but takes just 2
     min(const _Tp&, const _Tp&, _Compare);
                                         ^
c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\algorithmfwd.h:416:30: error: macro "min" requires 2 arguments, but only 1 given
     min(initializer_list<_Tp>);
                              ^
compilation terminated due to -fmax-errors=5.
*** [.pio\build\BIGTREE_SKR_MINI\src\src\Marlin.cpp.o] Error 1
In file included from c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\stl_algo.h:60:0,
                 from c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\algorithm:62,
                 from C:\Users\arnoldc.BENTLEY\.platformio\lib\EspSoftwareSerial_ID168\src/circular_queue/circular_queue.h:28,
                 from C:\Users\arnoldc.BENTLEY\.platformio\lib\EspSoftwareSerial_ID168\src/SoftwareSerial.h:27,
                 from .pio\libdeps\BIGTREE_SKR_MINI\TMCStepper_ID5513\src/TMCStepper.h:18,
                 from Marlin\src\core\../module/stepper_indirection.h:47,
                 from Marlin\src\core\../module/stepper.h:221,
                 from Marlin\src\core\utility.cpp:42:
c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\algorithmfwd.h:375:41: error: macro "max" passed 3 arguments, but takes just 2
     max(const _Tp&, const _Tp&, _Compare);
                                         ^
c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\algorithmfwd.h:388:41: error: macro "min" passed 3 arguments, but takes just 2
     min(const _Tp&, const _Tp&, _Compare);
                                         ^
c:\users\arnoldc.bentley\.platformio\packages\toolchain-gccarmnoneeabi\arm-none-eabi\include\c++\7.2.1\bits\algorithmfwd.h:416:30: error: macro "min" requires 2 arguments, but only 1 given
     min(initializer_list<_Tp>);
                              ^
compilation terminated due to -fmax-errors=5.
*** [.pio\build\BIGTREE_SKR_MINI\src\src\core\utility.cpp.o] Error 1

I have searched for any information but cannot find anything conclusive, I did find a similar issue here: https://github.com/MarlinFirmware/Marlin/issues/11968

Not sure if this helps.

[Default Config.zip](https://github.com/MarlinFirmware/Marlin/files/3485845/Default.Config.zip)

**Comment by tpruvot** [comment]
see #14892

**Comment by Xenon-2510** [comment]
I have made the changes referenced in #14892 and still have the same error when compiling

**Comment by tpruvot** [comment]
you installed EspSoftwareSerial which is not Marlin compatible at least.

**Comment by tpruvot** [comment]
There is none compatible listed in pio database yet... Need the fysetc SoftwareSerialM or the bigtree TMCStepper lib which include one... on the STM32F1.

**Comment by UncleBansh** [comment]
> I have made the changes referenced in #14892 and still have the same error when compiling

try this in platformio.ini

>

>  [common]
> default_src_filter = +<src/*> -<src/config> -<src/HAL> +<src/HAL/shared>
> build_flags = -fmax-errors=5
>   -g
>   -ggdb
> lib_deps =
>   U8glib-HAL=https://github.com/MarlinFirmware/U8glib-HAL/archive/dev.zip
>   LiquidCrystal@1.3.4
>   https://github.com/bigtreetech/TMCStepper
>   Adafruit NeoPixel@1.1.3
>   LiquidTWI2=https://github.com/lincomatic/LiquidTWI2/archive/master.zip
>   Arduino-L6470=https://github.com/ameyer/Arduino-L6470/archive/dev.zip
>   TMC26XStepper=https://github.com/trinamic/TMC26XStepper/archive/master.zip
>   SailfishLCD=https://github.com/mikeshub/SailfishLCD/archive/master.zip
>   SailfishRGB_LED=https://github.com/mikeshub/SailfishRGB_LED/archive/master.zip
>   SlowSoftI2CMaster=https://github.com/mikeshub/SlowSoftI2CMaster/archive/master.zip





> [env:BIGTREE_SKR_MINI]
> platform      = ststm32
> framework     = arduino
> board         = genericSTM32F103RC
> extra_scripts = buildroot/share/PlatformIO/scripts/STM32F1_SKR_MINI.py
> build_flags   = !python Marlin/src/HAL/HAL_STM32F1/STM32F1_flag_script.py
>   ${common.build_flags} -std=gnu++14
>   -DDEBUG_LEVEL=0 -DHAVE_SW_SERIAL
> build_unflags = -std=gnu++11
> lib_deps      = ${common.lib_deps}
> lib_ignore    = TMC26XStepper
>   libf3c
>   lib066
>   Adafruit NeoPixel_ID28
>   Adafruit NeoPixel
>   libf3e
>   #lib_ldf_mode  = chain
> src_filter    = ${common.default_src_filter} +<src/HAL/HAL_STM32F1>
> monitor_speed = 115200
> upload_protocol = stlink
> debug_tool = stlink

**Comment by tpruvot** [comment]
no no... i see no link to https://github.com/bigtreetech/TMCStepper there.
edit: hmm yea, i see it now :p direct url without TMCStepper= prefix (just add this line)

**Comment by UncleBansh** [comment]
> no no... i see no link to https://github.com/bigtreetech/TMCStepper there

look carefully in [common] ) 8 string)

**Comment by tpruvot** [comment]
i overheat, sorry ^^

**Comment by reloxx13** [comment]
i use a mini e3 myself with latest marlin and it compiles fine.

clean ur lib folders which are in ur marlin folder and not in git.

**Comment by reloxx13** [comment]
and u cannot copy the btt configs cause they almost always out of date, if u want take my config files as a start.

 u can find my config here: https://github.com/reloxx13/Marlin/tree/my-skr-mini-e3/Marlin

i merged them manually with git diffs (and tmc2209)

**Comment by UncleBansh** [comment]
not confirm compile without `-DHAVE_SW_SERIAL`  on skr e3 dip

**Comment by Xenon-2510** [comment]
Thank you so much, I have uninstalled the ESPSoftwareSerial and it has compiled successfully. 

@reloxx13 - Thanks, I will try your configs anyway as I see that you are using a BLTouch and I have been having intermittent issues with the probe triggering.
