### ISSUE TITLE
[Question] LiquidCrystal & Adafruit_Neopixel libraries

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#14902]
Why in platformio is there a bond with version? I checked latest downloaded by pio and the only remarkable difference is a "analogwrite" funciton. Removed forced version it compiles fine...

Same for adafruitneopixel (but I have to check differences here)

**Comment by GMagician** [comment]
neopixel new lib seems to have a different approch for samd51...but memory footprint seems bigger

**Comment by Ludy87** [comment]
why keep up-to-date if there is no error? Or are there new features?

Never change a running system! :-)

**Comment by GMagician** [comment]
if you say pio update project library you will get a warning then, about duplicated libraries

neopixel for sure has something different somewhere... a [++index] vs [index++] may do differences (don't checked yet starting index value) and for sure it support samd51 (even if with some hack on SysTick)

**Comment by GMagician** [comment]
> why keep up-to-date if there is no error

for the same reason you update marlin to new version :-D

**Comment by Ludy87** [comment]
I do not update Marlin :-P

That is of course one argument

**Comment by GMagician** [comment]
Joking aside, this new libs doesn't fix anything, it adds only support to esp32

**Comment by Ludy87** [comment]
New function is a argument 😊

**Comment by GMagician** [comment]
New newpixel library is required by samd51 to support 400KHz...current library doesn't support it. Also
current version uses "nop" to realize duty, new "disable" interrupts and uses Systick...with some hacks that need to be considered (millis will lose some amount of time)...what I can do?

**Comment by GMagician** [comment]
I don't use neopixel so I'll not care about this "issue" until someone will point it out.
