### ISSUE TITLE
Better support for Cyrillic, Japanese, UTF8

### ISSUE THREAD

**Issue by Nprod** [MarlinFirmware/Marlin#1492]
I've started adding bulgarian language support for the Hitachi HD44780 type character displays and have noticed that if the string is longer than about 9-10 characters, it gets cut off with plenty of room left on the screen. That makes it hard to add meaningful words to the menu without using a lot of abbreviations. In language_ru, quite frankly, it looks ugly since the "arrow" icons at the end of each menu entry don't line up with eachother and there is a lot of unused space on the right side.

Is this due to the 17 character limit for menu messages? Perhaps since cyrillic letters get converted by LiquidCrystalRus.cpp into a table address like "0x54", that causes the 17 character limit to get hit more easily?

**Comment by thinkyhead** [comment]
@Nprod It's possible the code there needs attention, if it is only counting bytes and not characters which might be 2 bytes long. Ostensibly the language support is there for utf-8 but we seem to use single-byte character codes almost everywhere. I don't know what the situation is with Cyrillic character displays, but I assume they provide single-byte character versions of all the most common characters...

**Comment by Nprod** [comment]
@thinkyhead That could be the case - it's like the length of the menu's label string is being reported way shorter than it's supposed to be. It's not related to the type of LCD display used because when using a non-cyrillic display it only substitutes the missing symbols for japanese katakana characters while the length of the menu item remains the same. 

Something worth mentioning here is that language_ru.h is the only file where i've seen some messages followed by a number of white spaces and  "\x7E" (arrow right). Example: 

```
#define MSG_CARD_MENU                       "Меню карты      \x7E"
```

**Comment by thinkyhead** [comment]
@Nprod Is it just the weird strings (arrows at the end, extra spaces, etc.) that are cut off? I posted a **strlen_utf8()** function on another issue, I'll dig that up and you can try it on Cyrillic...

**Comment by thinkyhead** [comment]
```
int my_strlen_utf8_c(char *s) {
   int i = 0, j = 0;
   while (s[i]) {
     if ((s[i] & 0xc0) != 0x80) j++;
     i++;
   }
   return j;
}
```

**Comment by Nprod** [comment]
@thinkyhead I don't think strlen is to blame here, because after looking into ultralcd_implementation_hitachi_HD44780.h i've noticed that not all the menu drawing functions use it. In some cases like line 635 you have a loop that's looking for a null character:

```
    while( ((c = pgm_read_byte(pstr)) != '\0') && (n>0) )
    {
        lcd.print(c);
        pstr++;
        n--;
    }
```

In any case, i'm attaching some photos to better illustrate the issue. In the first picture you have the messages on the left and the way they're being displayed on a cyrillic LCD on the right. The second picture is the same scenario, but using an LCD display that doesn't support cyrillic characters. The only thing that has changed are the symbols.

![lcdcyr1](https://cloud.githubusercontent.com/assets/10956716/6186342/ccea91c4-b380-11e4-826d-3f8b1f435bf4.jpg)
![lcdcyr2](https://cloud.githubusercontent.com/assets/10956716/6186343/ccef565a-b380-11e4-8eaf-cca3d46a3909.jpg)

**Comment by thinkyhead** [comment]
Huh, so if you were to add code to print out each byte that's being printed, do you think there would necessarily be a zero at those points where the string is being cut off?

**Comment by Nprod** [comment]
@thinkyhead I've been messing with arduino stuff for only a week but that would be my guess, yes. Strings containing only latin characters don't get cut off, in the same language file. Can you tell me how to modify it to print out each byte?

**Comment by thinkyhead** [comment]
@Nprod There are two possibilities actually. (1) Some characters are cues that the next byte means a different character (0xFF ?). (2) Some bytes which are zero are the second byte of a two-byte character code.

So, to see the bytes on the serial output (e.g., Pronterface), try inserting **SERIAL_ECHO** commands into loops in `ultralcd_implementation_hitachi_HD44780.h` where it's sending characters to the display... (Hopefully this works!)

```
while( ((c = pgm_read_byte(pstr)) != '\0') && (n>0) )
{
    SERIAL_ECHO_START;
    SERIAL_ECHOLN((int)c);
    lcd.print(c);
    pstr++;
    n--;
}
```

**Comment by thinkyhead** [comment]
This was brought up in #344 a couple of years ago. Will be good to see it fixed.

**Comment by Nprod** [comment]
@thinkyhead Ok, i got a dump of all the characters and the first thing that grabs attention is that all cyrillic strings output their characters as negative integers. I've made the second menu item to be all-latin ("ABCDEFGHIJKLMNOPQ") and it's the only "positive" sequence in the lot.

```
echo:-48
echo:-99
echo:-48
echo:-80
echo:-47
echo:-121
echo:-48
echo:-80
echo:-48
echo:-69
echo:-48
echo:-75
echo:-48
echo:-67
echo:32
echo:-48
echo:-107
echo:65
echo:66
echo:67
echo:68
echo:69
echo:70
echo:71
echo:72
echo:73
echo:74
echo:75
echo:76
echo:77
echo:78
echo:79
echo:80
echo:81
echo:-48
echo:-99
echo:-48
echo:-80
echo:-47
echo:-127
echo:-47
echo:-126
echo:-47
echo:-128
echo:-48
echo:-66
echo:-48
echo:-71
echo:-48
echo:-70
echo:-48
echo:-48
echo:-99
echo:-47
echo:-113
echo:-48
echo:-68
echo:-48
echo:-80
echo:32
echo:-48
echo:-102
echo:-48
echo:-80
echo:-47
echo:-128
echo:-47
echo:-126
```

This must be related to issue #344 but some messages can be more than 8 characters, as shown in my photo.

**Comment by AnHardt** [comment]
@Nprod 
I have a possible fix. Please test  #1508.

There is a small possibility i can provide a implementation for full graphic displays if you cold provide me with a link to the datasheet for your Russian character display. I need the pictures and the matching character codes to make a new conversation table into a dogm-font.

**Comment by AnHardt** [comment]
![picture 72](https://cloud.githubusercontent.com/assets/211931/6212426/6cf4b90e-b5e5-11e4-8f78-de494ea80f66.jpg)

**Comment by Nprod** [comment]
@AnHardt Your fix worked beautifully, thanks! So it was a fault with strlen after all?

You can find the datasheet here, font table is on page 14 - http://store.comet.bg/download-file.php?id=466

Displays with cyrillic support are surprisingly hard to find, the most common are by Ampire and a few by Winstar and Orient Display. The font table is the same for all of them though. What is "test multiline" for by the way?
![lcdcyr3](https://cloud.githubusercontent.com/assets/10956716/6214705/34e89d50-b603-11e4-97ea-87594786b12a.JPG)

**Comment by AnHardt** [comment]
@Nprod 
It was a combination of a not unicobe able strlen() and the part you discovered.
thest multiline was smugled in by https://github.com/MoonCactus/Marlin-JFR-features/commit/85e5aa4011cf65c0b09a4453bd1f3ac3752ba072#diff-34f7cdd618621ae7d8c113cf0b86a2f4R350
and will vanish soon - i hope.
Thanks for the link.

**Comment by AnHardt** [comment]
And an other annotation.
The 17 chars (rule) in the head of the language files is more a rude rule of thumb. For 16 chars wide displays this obviously can not be correct.
It's more like: display width - select column - (back-sub menu column or ':') - may be value length - may be other appended strings - one UNUSED COLUMN on the 20 chars width display (what i will investigate in the near future)

**Comment by Nprod** [comment]
Yeah i noticed that the 17 character limit is more of a guideline to make the menus look right. Ok, with this sorted, what about cases where a Hitachi 44780 type screen is used via PCF8574 extender? Then you need to use LiquidCrystal_I2C instead, but it doesn't support russian. I found a version that does here - https://github.com/treasure33/ARDUINO_LIB/tree/master/LiquidCrystal_I2C

What would be best - should this updated library be included with Marlin or should the user be expected to update it in their Arduino IDE? It's a very specific case that's useful only for electronics like Melzi and maybe Sanguinololu where the available I/O pins can be scarce.

**Comment by thinkyhead** [comment]
Good job @AnHardt. That's the fix we were looking for.

@Nprod I'm not sure, but as I understand it the `LiquidCrystalRus.cpp` and `LiquidCrystalRus.h` are included to deal with the lack of support in **LiquidCrystal_I2C**.

**Comment by Nprod** [comment]
@thinkyhead From what i understood, LiquidCrystalRus is based on the standard LiquidCrystal library from the Arduino IDE and it only applies when the LCD is connected using the standard parallel interface. If you declare that you're using an I2C interface with something like **LCD_I2C_TYPE_PCA8574** then it defaults to LiquidCrystal_I2C.h which doesn't support russian. I've linked to a modified version of it in my previous post which supposedly has that feature, but i haven't been able to test it yet. If it's not too different, it might be worth having it here instead.

**Comment by thinkyhead** [comment]
Hmm, if it's good enough we should include it in the Marlin package. Do you think it _also_ supersedes `LiquidCrystalRus.cpp` / `LiquidCrystalRus.h` ?

**Comment by Nprod** [comment]
@thinkyhead Hmm no, it's a different use case - controllers like the Panelolu2, or one of these black I2C extender boards that attach to the back of the LCD module: http://img.alibaba.com/img/pb/224/728/686/686728224_079.jpg It's a popular choice because it reduces the LCD pin count from 8 to 4 and leaves room to hook up other things like an encoder, extra fans etc.

**Comment by thinkyhead** [comment]
We should definitely make note of it in the Configuration comments for `LCD_I2C_TYPE_PCA8574` concerning support for Russian, that the other library is needed. We can include the alternative library too, we just have to name its root folder differently and document the situation clearly.

**Comment by Nprod** [comment]
Yeah, we could rename it to LiquidCrystal_I2CRus and switch to it automatically when russian language is selected, the way it's currently done between LiquidCrystal and LiquidCrystalRus. But if it supercedes LiquidCrystal_I2C it may be better to just let the user know that they should update their library. In any case i have to test it first. As soon as my I2C expander arrives in the mail, i'll report back here.

**Comment by AnHardt** [comment]
I did not analyse the _Rus._ -files to the end. But as far as i see they mainly deal wit the display hardware. The language specific part consists of a conversion table and a few lines of code to convert from Unicode to the displays charset. (https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/LiquidCrystalRus.cpp#L16
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/LiquidCrystalRus.cpp#L297)
I think this could be dealed with in the __inplenentation__ files. 

The remaining hardware dependent things feel (for me) somehow as if integrated at the wrong place. Maybe as special cases in ultralcd_implementation_hitachi_HD44780.h, where the i2c things could be wrapped around it. But this is far beyond my current scope.

While locking at the code i think - there are not hardware differences but the charset.

**Comment by Nprod** [comment]
@AnHardt Yes, the hardware is identical, only the font table in ROM is different. Cyrillic support is part of the original Hitachi HD44780 specification and it's up to the manufacturer to decide which one to flash. The developers of the standard arduino libraries (LiquidCrystal, LiquidCrystal_I2C) probably just didn't bother to support unicode because they never needed it. If you ask me the russian versions are better in every way since all they do is add that missing functionality. But who knows, maybe there's some hidden compatibility issues i'm missing...

All the I2C and Panelolu2 stuff is already supported in ultralcd_implementation_hitachi_HD44780.h, you just need to update the arduino libraries for russian support. 

It should be supported by 128x64 displays aswell since there's a GNU unicode font for U8glib - https://code.google.com/p/u8glib/wiki/fontgroupunifont

**Comment by AnHardt** [comment]
If the difference is only the charset i have a solution. Withe that one could use the normal i2c stuff. Please stand by.
Also working on the 128*64 displays.

**Comment by AnHardt** [comment]
@Nprod 
Would you please be so kind to test https://github.com/AnHardt/Marlin/tree/rus-remove-extrafiles?

**Comment by Nprod** [comment]
@AnHardt Hmm no, didn't work. It outputs the same type of broken text as what happens when you just add cyrillic text to language files that don't use LiquidCrystalRus. Perhaps theres something missing in the new lcd_print()?

**Comment by Nprod** [comment]
@AnHardt I just got it running successfully with an I2C interface. The library i posted before doesn't work correctly, but i found a more recent one: 

http://blockduino.blogspot.com/2014/03/LiquidCristalRusI2C.html

This library works with both english and russian languages so it can be used as a universal drop-in replacement. The only changes that need to be made are to replace any occurences of **"LiquidCrystalCyr_I2C"** to **"LiquidCrystal_I2C"**, as i've done here - http://nik.benzinestudios.com/Razni/LiquidCrystal_I2C.zip

By the way i noticed that there is a noticeable 1-second lag between clicking the encoder button and the main menu appearing when using I2C compared to parallel. Is this a fault with my cheapo port expander or Marlin's implementation?

**Comment by AnHardt** [comment]
@Nprod 
Updated the test-branch. https://github.com/AnHardt/Marlin/tree/rus-remove-extrafiles
 It's a good idea to use UNSIGNED chars when comparing with > 0x80! Sorry.
Would you please try again.

Sorry the I2C-stuff is outside my scope. I have no hardware to test.

**Comment by Nprod** [comment]
@AnHardt Works great! Your implementation makes it so much cleaner now, and i can safely add a new cyrillic language without the need to switch to LiquidCrystalRus in ultralcd_implementation_hitachi_HD44780.h, nice!

I will test it using I2C now - if my hunch is correct, it should work out of the box without changing any more code.

**Comment by Nprod** [comment]
@AnHardt Tested it with I2C - no problems. Consider your fix a complete success :)

**Comment by thinkyhead** [comment]
Will this mean that LiquidCrystalRus can go away? :pray:

**Comment by AnHardt** [comment]
In the tested branch it IS deleted. 
I think my pull request (#1508) is simple enough to be a fix for the original problem and can be applied now. 
Removing ' LiquidCrystalRus._' is a bigger thing, i'd like to do later when 'codefreze' is over. As a 'side effect' this will allow to write all the language__.h files to be written in Unicode. At least i will provide examples for 'ru' and 'de'.
The 12854 side of the problem will have to wait until the marlin symbols have been moved to an extra font.

**Comment by thinkyhead** [comment]
@AnHardt Merged #1508.

**Comment by boelle** [comment]
should this one still be open ?

**Comment by AnHardt** [comment]
Yes. Still working on the big solution including Cyrillic on the full graphic displays, UTF8 for all languages and Japanese. Test are going on - tooooo many possible combinations.

**Comment by boelle** [comment]
np then :-D

**Comment by boelle** [comment]
remember to submit pull requests as soon you have a part done so we can implement in small steps

**Comment by AnHardt** [comment]
@boelle 
Easier said than done. Things are pretty geared.

I have a new preview at: https://github.com/AnHardt/Marlin/tree/utf

All planned things are in place.
Cyrillic on the full graphic displays.
UTF8 for all when wanted.
Katakana on all displays. Katakana in UTF8.
'Kanji' on full graphic displays.
German in UTF8.
Finnish in UTF8.
Tree Hitachi fonts on full graphic displays for tests.
Separate font for Marlin symbols.
Full ISO fonts for Cyrillic, Katakana, European Languages in the right size.
Documentation.
Test_language.

Maybe I forgot to list same features here.

Remaining problems:
Cyrillic an especially katakana font have to be reviewed by someone who knows how this should look like.
Kana_UTF8 has to be reviewed by someone who knows what he does.
My English has to be checked.
A little merge-conflict in language.h has to be cleaned up.

**Comment by AnHardt** [comment]
Some pictures:
![picture 76](https://cloud.githubusercontent.com/assets/211931/6645770/87281792-c9bf-11e4-87a2-9345a3fd12a5.jpg)
Cyrillic on a graphic display.

![picture 79](https://cloud.githubusercontent.com/assets/211931/6645803/c5ff0cdc-c9bf-11e4-8f55-309e7d6ddbd9.jpg)
Cyrillic on a graphic display simulating Japanese Hitachi.

![picture 80](https://cloud.githubusercontent.com/assets/211931/6645830/efc2eaac-c9bf-11e4-815d-33ddf72ced8d.jpg)
Cyrillic on a Japanese Hitachi.

![picture 82](https://cloud.githubusercontent.com/assets/211931/6645856/12479b4a-c9c0-11e4-849a-205e58c13330.jpg)
Kana on a japanese Hitachi.

![picture 89](https://cloud.githubusercontent.com/assets/211931/6645906/6440b990-c9c0-11e4-87fd-c5f750592030.jpg)
'Kanji' on a graphic display.

![picture 91](https://cloud.githubusercontent.com/assets/211931/6645948/abe4b42c-c9c0-11e4-80e4-d264e5e469d9.jpg)
Kana on simulated Hitachi font.

![picture 90](https://cloud.githubusercontent.com/assets/211931/6646018/46e327a6-c9c1-11e4-959c-af8ef415176f.jpg)
Kana_UTF8 on ISO font. Look at the ligatures.

![picture 88](https://cloud.githubusercontent.com/assets/211931/6645972/d4e5a2be-c9c0-11e4-9cb0-7c98d5bb4a02.jpg)
Deutsch mit allen Umlauten. In KLEIN!

**Comment by AnHardt** [comment]
And the highlight for the europeans:
![picture 93](https://cloud.githubusercontent.com/assets/211931/6646186/c638ec74-c9c2-11e4-8928-083b0d34f149.jpg)
Full ISO charset on graphic displays.

![picture 94](https://cloud.githubusercontent.com/assets/211931/6646203/e9876cd2-c9c2-11e4-83b6-57b42a4e4677.jpg)
Separate Marlin symbols font.
Screenshots with language_test.h.

**Comment by Nprod** [comment]
Wow this looks amazing. Sadly i don't have a 128x64 screen to test the cyrillic font with... What about printing the whole alphabet and posting a screenshot?

**Comment by AnHardt** [comment]
@Nprod 
Here we go. Upper halve of ISO10646_5
![picture 96](https://cloud.githubusercontent.com/assets/211931/6647053/1e88520e-c9cb-11e4-8e3e-dbf281c7eeb6.jpg)
![picture 95](https://cloud.githubusercontent.com/assets/211931/6647025/ec955f08-c9ca-11e4-8510-49129a46beb0.jpg)

**Comment by Nprod** [comment]
@AnHardt OK, here is an image with corrections that need to be made in red. The letters marked with an arrow next to them need to be shifted up with one pixel. The first row in your first image has letters that are not part of the hitachi implementation and are likely for mongolian cyrillic... I'm not 100% sure how they're supposed to be, but i've made a guess anyway. 

![cyrcorrected](https://cloud.githubusercontent.com/assets/10956716/6649429/4cec39f4-c9f2-11e4-8864-306ec4868014.jpg)

**Comment by thinkyhead** [comment]
Ah, I see this is keeping active. We could start a new thread, or just change the topic of this one...

**Comment by AnHardt** [comment]
@Nprod 
Thanks for you review.
The different symbols from yesterday come from ISO10646_5. The reference was http://www.utf8-zeichentabelle.de/unicode-utf8-table.pl?start=1024 up to U+045F.
Corrected version:
![picture 97](https://cloud.githubusercontent.com/assets/211931/6651393/bae178f4-ca40-11e4-9163-348d5e392660.jpg)
![picture 100](https://cloud.githubusercontent.com/assets/211931/6651395/c952ee36-ca40-11e4-8992-b4bb02ea5ad6.jpg)

The simulated Hitachi ROM font looks like:
![picture 101](https://cloud.githubusercontent.com/assets/211931/6651400/e9747888-ca40-11e4-9507-c56df178a164.jpg)
![picture 102](https://cloud.githubusercontent.com/assets/211931/6651401/ee807d2c-ca40-11e4-97c5-eb6bcb98e1a8.jpg)

**Comment by AnHardt** [comment]
Updated https://github.com/AnHardt/Marlin/tree/utf wit the corrected fonts.

**Comment by Nprod** [comment]
@AnHardt Now it's much better, but you forgot to add one pixel in the letter Э (U+042D) - it looks exactly like the number 3. Refer to the pic i posted earlier as to how it should look like. Apart from that, it looks very good, the simulated hitachi ROM matches the code table from the datasheet too. Are there any other fonts that need to be tested?

**Comment by AnHardt** [comment]
@Nprod Now i got it. More like a big mirrored C with a - in the middle. 
The kana fonts have still to be revised. I'll make pictures later.
The 'kanji' font is unchanged but we have legal problems - see #1513.

**Comment by boelle** [comment]
have any contacted the author ?

**Comment by AnHardt** [comment]
This is the font to simulate Hitachi Japanese. Reference is https://www.sparkfun.com/datasheets/LCD/HD44780.pdf Page 17
![picture 103](https://cloud.githubusercontent.com/assets/211931/6652040/d0f656b8-ca5f-11e4-8679-e3af40abf7f5.jpg)
![picture 104](https://cloud.githubusercontent.com/assets/211931/6652042/e86844b4-ca5f-11e4-9fb3-ae1ee6ddfc2d.jpg)

The Katakana ISO font. Based on http://www.utf8-zeichentabelle.de/unicode-utf8-table.pl?start=12448 up to U+30FF.
![picture 105](https://cloud.githubusercontent.com/assets/211931/6652055/6c0d576e-ca60-11e4-8f4f-60652fa347b9.jpg)
![picture 106](https://cloud.githubusercontent.com/assets/211931/6652057/7198b066-ca60-11e4-9865-cd1746f32828.jpg)

**Comment by thinkyhead** [comment]
@boelle I did contact the author and ask about resolving licensing issues. I posted his reply on another topic. The translation I got was bad, so I could only get the basic gist. I believe he was asking for a link back to the source page and a credit in the source code. But, I may be reading it badly. Maybe it is worth it to hire a translation service on the internet. A decent translation would cost under $20 on the services I looked at.

I hope he isn't still asserting a non-commercial restriction. On the one hand, the GPLv3 forbids creating a distribution that removes rights, including adding a commercial use restriction. And it also forbids Marlin from taking any conditional contribution.

The font and the string translations are the problem. If someone were to "clean room" a Japanese font and also create original translations, the implementation itself is not under dispute. There is a Right Way to make a language contribution, and Kana – apart from the specific translations and font – must be as it is.

**Comment by boelle** [comment]
any chance i could have a go at it with google translate? not perfect i know but slicing it in bits might do the trick

**Comment by AnHardt** [comment]
Dear @boelle.
Would you please be so kind to cross-read #1513.

**Comment by boelle** [comment]
i did... i wanted to know what the author wrote in his native language

**Comment by boelle** [comment]
oh... there it was

**Comment by Nprod** [comment]
Hey i just noticed one more tiny correction that needs to be made - the letter д (U+0434) should be shifted down one pixel in order to match the way it looks on a hitachi display.

![cyrcorrected2](https://cloud.githubusercontent.com/assets/10956716/6666383/86ffcfa6-cbec-11e4-9be7-bf2b67b1c066.jpg)

**Comment by AnHardt** [comment]
OK. That's why i asked an expert. :-)

**Comment by AnHardt** [comment]
@Nprod 
If you are satisfied with the current solution you can close this.

Will we have a Bulgarian language file from you?

**Comment by Nprod** [comment]
@AnHardt Yes, the cyrillic support seems fine - i can't see anything wrong with the 128x64 screenshots and the hitachi display here works. If i find any other problems, i'll open a new issue.

And yes i will make a Bulgarian language file soon, just haven't had the time to work on it recently. Should i post it here when its done? It shouldn't take long.

**Comment by AnHardt** [comment]
@Nprod 
Better would be to use a pastebin or gist - and than post the address here.

**Comment by Nprod** [comment]
@AnHardt Alright, here you go:

http://pastebin.com/hs6VLc2H

It might be a little out of context in a few places but for the most part it's a complete working translation.

**Comment by AnHardt** [comment]
@Nprod 
Thanks a lot. PR will follow tomorrow. To tired for today.
