### ISSUE TITLE
[BUG] MKS Gen L - TMC 2208 - linear advance 

### ISSUE THREAD

**Issue by dodoguigui** [MarlinFirmware/Marlin#14925]
The extrusion stop when linear advance is activeted in Marlin 2.0.x.

**Comment by thisiskeithb** [comment]
This is a known issue with TMC2208s & linear advance. See https://github.com/MarlinFirmware/Marlin/issues/14634 for some possible workarounds.

**Comment by boelle** [comment]
@dodoguigui is the problem still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
