### ISSUE TITLE
[BUG] TMCStepper update to 0.4.6

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#14938]
### Description
TMCStepper update to 0.4.6,compile error.

### Steps to Reproduce

1.what TMCStepper.h change??
2. #define SW_CAPABLE_PLATFORM defined(__AVR__) || defined(TARGET_LPC1768) || defined(ARDUINO_ARCH_ESP32) || defined(ARDUINO_ARCH_STM32F1)
so it need #include <SoftwareSerial.h> file
3. delete  defined(ARDUINO_ARCH_STM32F1)

**Expected behavior:** correctly error

**Actual behavior:** no SoftwareSerial.h file

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by tpruvot** [comment]
see #14892

**Comment by ghost** [comment]
when i delete defined(ARDUINO_ARCH_STM32F1),it can correctly compile!

**Comment by boelle** [comment]
Include a ZIP file containing your Configuration.h and Configuration_adv.h files.

**Comment by ghost** [comment]
[my_config.zip](https://github.com/MarlinFirmware/Marlin/files/3504484/my_config.zip)

**Comment by tpruvot** [comment]
This problem was already fixed this week in PR #14861 (Aug 8)

**Comment by ghost** [comment]
Thanks! @tpruvot
