### ISSUE TITLE
[BUG] [env:STM32F1] lib_ignore   = U8glib-HAL can cause compilation errors

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#14939]
### Description
[env:STM32F1] lib_ignore   = U8glib-HAL ，can ignore u8g lib,so cause compilation errors.the errors is "conflicting types for 'random'";can not distinguish function overloading!

### Steps to Reproduce

1. use  platform.ini [env:STM32F1] lib_ignore   = U8glib-HAL
2. compile
3. conflicting types for 'random'"

**Expected behavior:** correctly compile

**Actual behavior:** conflicting types for 'random'"

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by boelle** [comment]
Include a ZIP file containing your Configuration.h and Configuration_adv.h files.

**Comment by ghost** [comment]
[my_config.zip](https://github.com/MarlinFirmware/Marlin/files/3504270/my_config.zip)

**Comment by tpruvot** [comment]
What is exactly your board/chip ?

**Comment by ghost** [comment]
stm32f103RET6    && my personal board according to mks-robin

**Comment by boelle** [comment]
@niu3niu still having problems?

**Comment by ghost** [comment]
@boelle  i have solve it.Thanks ! u can close this issue!
