### ISSUE TITLE
[BUG] TOUCH_MI_PROBE

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#14944]
hello
with the retract of the touch active, it follows that to perform autolevel the sensor is no longer deployed :(

#define TOUCH_MI_PROBE
#if ENABLED(TOUCH_MI_PROBE)
  #define TOUCH_MI_RETRACT_Z 0.5  
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/3498204/Configuration_adv.zip)

**Comment by boelle** [comment]
Include a ZIP file containing your Configuration.h and Configuration_adv.h files.

**Comment by boelle** [comment]
@boubouexpress do you still have issues?
