### ISSUE TITLE
[BUG] (2.0)Babystepping and Zprobe

### ISSUE THREAD

**Issue by maukcc** [MarlinFirmware/Marlin#14950]
Babystepping is not working when a Z-probe is enabled.
Is this intentional?

**Comment by reloxx13** [comment]
works fine for me

**Comment by boelle** [comment]
attach your 2 config files as zip

**Comment by maukcc** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3504978/Configuration.zip)

**Comment by boelle** [comment]
@maukcc still having issues?

**Comment by maukcc** [comment]
Nope fixed with #14314
