### ISSUE TITLE
[BUG] Marlin 2.0  Homing Z won't work with SKR Pro

### ISSUE THREAD

**Issue by budi67** [MarlinFirmware/Marlin#14958]
Hello all

 I just finished install Marlin 2.0 on my SKR PRO, but i have a problem with homing.

I have a bltouch and i must set my Z_offset to -8 
Bltouch ==> https://www.thingiverse.com/thing:2841443

But when it homing it stop at z0, i don't understant

A big thanks
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3506200/Configuration.zip)

**Comment by golfromeo-fr** [comment]
with the updates in the last 48 hours, the bltouch probing with my SKR PRO no longer works.
the bltouch now deploy/stow 3 times and no longer go down for probing
the probing fails

**Comment by golfromeo-fr** [comment]
is it related to 
https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/issues/31
?

**Comment by Chr157i4n** [comment]
> with the updates in the last 48 hours, the bltouch probing with my SKR PRO no longer works.
the bltouch now deploy/stow 3 times and no longer go down for probing
the probing fails

This sound like the same issue i have.

**Comment by golfromeo-fr** [comment]
I figured out my problem: the connector on the bltouch was "half" disconnected on the "Z-" side (vibrations?) and the signal pin/+5V/Ground were still attached (probe still doing deploy/stow

so yes the pin physically changed!
=> problem solved
---
<del>it looks like the Z probe pin has changed
the pin in pins_BIGTREE_SKR_PRO_V1.1.h has not changed it's PA2
#define Z_MIN_PROBE_PIN  PA2
but maybe the definition of PA2 has changed for some obscure reason</del>

---
<del>I have tried the M43 S command like @christianger  did</del>

<del>I have tried
#define Z_MIN_PROBE_ENDSTOP_INVERTING false
and 
#define Z_MIN_PROBE_ENDSTOP_INVERTING true
but the sequence only prints, ignoring the Z_MIN_PROBE_ENDSTOP_INVERTING value
Recv: . Z_MIN_PROBE_ENDSTOP_INVERTING: false</del>

<del>Z_MIN_PROBE_ENDSTOP_INVERTING, SERVO_DELAY are overrided in Conditionals_LCD.h</dev>

<del>Send: M43 S
Recv: Servo probe test
Recv: . using index:  0, deploy angle: 10, stow angle:   90
Recv: . Probe Z_MIN_PROBE_PIN: 11
Recv: . Z_MIN_PROBE_ENDSTOP_INVERTING: false
Recv: . Check for BLTOUCH
Recv: . Deploy & stow 4 times
Recv: WARNING: INVERTING setting probably backwards.
Recv: ** Please trigger probe within 30 sec **
Communication timeout while idle, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Recv: FAIL: No trigger detected
Recv: ok</del>

**Comment by budi67** [comment]
Hello

How do you active M43 ?
I have try to active #define PINS_DEBUGGING, but i have this error !!
Thanks
![debug](https://user-images.githubusercontent.com/23610289/63147342-17003a00-bffe-11e9-999b-4a74fb6347a1.PNG)

**Comment by golfromeo-fr** [comment]
> I have try to active #define PINS_DEBUGGING, but i have this error !!

https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/issues/31#issuecomment-521911559

**Comment by Patag** [comment]
@budi67  See #14894

**Comment by budi67** [comment]
Thanks Patag.

I have download a new firmware from Marlin and all started again from 0.
All work fine.

But as the SKR Pro as no Eeprom, where save the Mesh ?

**Comment by Chr157i4n** [comment]
You can use SD-Card EEPROM Emulation to store the values in the SD-Card of the LCD:


#define BOARD_NAME "BIGTREE SKR Pro 1.1"

// Use one of these or SDCard-based Emulation will be used
//#define SRAM_EEPROM_EMULATION   // Use BackSRAM-based EEPROM emulation
//#define FLASH_EEPROM_EMULATION  // Use Flash-based EEPROM emulation        


simply uncomment FLASH_EEPROM_EMULATION

(Marlin/src/pins/stm32/pins_BIGTREE_SKR_PRO_V1.1.h)

**Comment by budi67** [comment]
A big thanks for your answer Christianger, i will try this

**Comment by budi67** [comment]
I have uncomment   FLASH_EEPROM_EMULATION

For save it's M500 ??
I have try and i get this : 
Error:EEPROM disabled
[ERROR] Error:EEPROM disabled

In configuration.h  this option is enable ==> #define EEPROM_CHITCHAT

**Comment by gloomyandy** [comment]
@budi67 Do you have EEPROM_SETTINGS enabled? That needs to be on toy have M500 etc work.

**Comment by budi67** [comment]
Thanks Gloomyandy, it's ok, work fine

**Comment by budi67** [comment]
Sorry but another question about start gcode in slicer

G28 after just M420 S1 ?

And where are stocked the infos of the mesh ?, after a M500 i have nothing on the Board sd an nothing on TFT sd

**Comment by budi67** [comment]
In pronterface when i make M500 after a G29
It say : echo:Settings Stored (762 bytes; crc 20618)
If i make M501 : echo:EEPROM version mismatch (EEPROM=? Marlin=V68)
echo:Hardcoded Default Settings Loaded
If i make M503, i don't have the mesh data

**Comment by boelle** [comment]
@budi67 problem solved?

**Comment by budi67** [comment]
yes, problem solved, sorry for not given assets news, lots of worries right now
