### ISSUE TITLE
[FR] add Bed temp PID edit option to menu

### ISSUE THREAD

**Issue by sl1pkn07** [MarlinFirmware/Marlin#14952]
### Description

Active PIDTEMPBED and PID_AUTOTUNE_MENU only show pids for extruder, but not for bed

### Steps to Reproduce

1. [First Step]
enable PID_AUTOTUNE_MENU
enable PID_EDIT_MENU 
enable PIDTEMPBED
2. [Second Step]
go to LCD -> configuration -> advance -> temperature

**Expected behavior:** [What you expect to happen]

see the pid edit and autotune for extruder and bed

**Actual behavior:** [What actually happens]

only show the autotune and edit for extruder

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

https://github.com/sl1pkn07/Marlin/commit/bf7879df42289a81fc08b7f578fa49ee4ec65b14#diff-8270513bcf2a548cd418cdfe123f27d3R462-L540
* Provide pictures or links to videos that clearly demonstrate the issue.
![photo_2019-08-14_21-46-55](https://user-images.githubusercontent.com/462213/63051269-305d9500-bedd-11e9-839b-15978bee91df.jpg)
![photo_2019-08-14_21-46-54](https://user-images.githubusercontent.com/462213/63051361-66027e00-bedd-11e9-9d6d-493bc8ac04cf.jpg)

* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by shitcreek** [comment]
This isn't a bug as it is not in the code. This would be more a feature request. I'm working on getting it added.

**Comment by kaisertheone** [comment]
This Feature request is still open?
I am missing that option too now.
i flew over the code and found some "leftovers" regarding this point.

`#if ENABLED(PID_AUTOTUNE_MENU)

  #if ENABLED(PIDTEMP)
    int16_t autotune_temp[HOTENDS] = ARRAY_BY_HOTENDS1(150);
  #endif

  #if ENABLED(PIDTEMPBED)
    int16_t autotune_temp_bed = 70;
  #endif

  void _lcd_autotune(const int16_t e) {
    char cmd[30];
    sprintf_P(cmd, PSTR("M303 U1 E%i S%i"), e,
      #if HAS_PID_FOR_BOTH
        e < 0 ? autotune_temp_bed : autotune_temp[e]
      #elif ENABLED(PIDTEMPBED)
        autotune_temp_bed
      #else
        autotune_temp[e]
      #endif
    );
    lcd_enqueue_one_now(cmd);
  }`

unfortunately i cant figure out whats the problem.

**Comment by sl1pkn07** [comment]
The petition of this FR is still up

**Comment by sjasonsmith** [comment]
@sl1pkn07 have you tested with `bugfix-2.0.x`, after the change was merged 20 days ago?

**Comment by sl1pkn07** [comment]
Oh. First notice . Sorry

Closing
