### ISSUE TITLE
Probe servo retraction

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#1495]
Hi all. I found that a big issue is the lack of an option to disable the retraction of the probe during the G29 Bed Leveling.
Due to not great precision of little servos will be better to raise the entire z carriage by X mm than retract everytime the probe. Faster with more precision.

Thanks to read this request.

**Comment by CptanPanic** [comment]
Did you try the enhancement available with 'G29 E'  It is supposed to offer this.

**Comment by boelle** [comment]
@pixel3Design did you try as @CptanPanic  suggested?

**Comment by thinkyhead** [comment]
G29 E will delay retract until the last probe is done. So this is all set!
