### ISSUE TITLE
Abstraction Layer for User Interface ?

### ISSUE THREAD

**Issue by robbycandra** [MarlinFirmware/Marlin#14970]
Now we have many User Interface options for marlin. This makes marlin even more interesting.
We can use:
- Character based LCD like 2004
- Monochrome Graphic LCD like 12864
- TFT LCD but uses the u8glib monochrome library like MKS Robin, Longer3D
- TFT LCD with separate firmware such as MKS / Bigtree TFT
- TFT LCD which is more integrated with marlin using Extensible UI
- Using the SmartPhone Screen with the help of ESP32
- Using a Host like Octoprint

Can we implement some standard using the abstraction layer for UI functions?

Does anyone have other ideas about this user interface things?

**Comment by golfromeo-fr** [comment]
TFT screens are mostly active devices with a separate CPU and a communication channel with the marlin main board so they are not managed by Marlin, so it cannot be abstracted by Marlin
