### ISSUE TITLE
SKR V1.3 + Watterott TMC 5160 V1.4

### ISSUE THREAD

**Issue by Coffee0297** [MarlinFirmware/Marlin#14997]
Hello.
i had had some problems with the tmc 5160 v1.4 from watterott.
they have deleted the clk pin on the stepsticks. and put a DCO pin there instead. the DCO is an output if the stepper is in SPI mode, wich this is. BUT on the skr v1.3 the pin that the DCO pin is connected to is also the MOTO_MISO, aka the spi read.
i've bend the DCO pin on the stepstics out and it reads the spi again.

**Comment by boelle** [comment]
just confused here, is this a marlin bug?

**Comment by Coffee0297** [comment]
No it's a hardware issue i just think that it shuld be noted bc a lot of People are running watterott in eu

**Comment by boelle** [comment]
you should post it on discord instead as this list is for bugs only

https://github.com/MarlinFirmware/Marlin/issues/14694
