### ISSUE TITLE
[BUG] TMC5161 cant enable  debug option 

### ISSUE THREAD

**Issue by labotecno** [MarlinFirmware/Marlin#15001]
hello i buy recently the new TMC5161 , i get it working with spi , but i cant get it working with debug option , 
i cant get M122 state 
plesase can you help me with this issue !

**Comment by boelle** [comment]
-RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
-[Tom's 3D Forums](https://forum.toms3d.org/)
-Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
-Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
-[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
-Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by boelle** [comment]
closing as this is not a bug
