### ISSUE TITLE
[BUG] CR-10 Example Profile Thermistor Incorrect

### ISSUE THREAD

**Issue by Deneteus** [MarlinFirmware/Marlin#15039]
### Description: 

The thermistor type for the CR-10 and CR-10S is incorrect in the Example profile.

The thermistor for the heat bed is listed as 100K ohm NTC 3950FB. In the original CR-10 source Creality used 1 for both the bed and the hot end. These are also the only thermistors they sell for this printer.

### Steps to Reproduce

Please review the Example Configuration files for the CR-10 and CR-10S and review the thermistor settings for the bed and hot end. You will noticed the bed thermistor is set to 5.

https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/example_configurations/Creality/CR-10/Configuration.h

![image](https://user-images.githubusercontent.com/6380390/63634641-fdbf4500-c61e-11e9-9ad5-d0c348fb0d67.png)

https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/example_configurations/Creality/CR-10S/Configuration.h

![image](https://user-images.githubusercontent.com/6380390/63634781-b934a900-c620-11e9-953c-337f3237a277.png)

#### Additional Information

Creality CR-10 Github Config.h
https://github.com/Creality3DPrinting/CR-10/blob/master/Firmware/Marlin/Configuration.h

Official Site:
https://www.creality3donline.com/creality-5pcs-100k-ohm-ntc-3950fb-thermistors-with-cable-temperature-sensor-reprap-extruder-for-creality-3d-printer-mend-hot-bed_p0035.html

![image](https://user-images.githubusercontent.com/6380390/63634588-2f83dc00-c61e-11e9-9066-e52a471f88e6.png)

![image](https://user-images.githubusercontent.com/6380390/63634567-e2a00580-c61d-11e9-9bc2-443e480214ac.png)

**Comment by Deneteus** [comment]
Thanks Boelle. :)

**Comment by boelle** [comment]
no problemo :-)

**Comment by thisiskeithb** [comment]
See PR https://github.com/MarlinFirmware/Marlin/pull/15040.

**Comment by boelle** [comment]
so we can "swing the axe" on this one when the PR gets merged :-D

**Comment by thisiskeithb** [comment]
> so we can "swing the axe" on this one when the PR gets merged :-D

Yep.

These changes will be implemented in `bugfix-2.0.x` since `1.1.x` is no longer receiving support.

**Comment by Deneteus** [comment]
Bugfix-2.0.x is what I was testing when I noticed that the thermistor value was off.

**Comment by thisiskeithb** [comment]
> Bugfix-2.0.x is what I was testing when I noticed that the thermistor value was off.

Ahh. You linked `1.1.x`, so I was just making sure 😄

**Comment by sl1pkn07** [comment]
then if affect the creality printers, the ender series is affected?

**Comment by sl1pkn07** [comment]
ender series not, but CR-10_5S and CR-10mini yes:

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/config/examples/Creality/CR-10_5S/Configuration.h#L414

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/config/examples/Creality/CR-10mini/Configuration.h#L423

(?)

**Comment by thisiskeithb** [comment]
Looking at the Creality firmware for those machines, they should be updated as well. I'll update my PR.

edit: Now updated.
