### ISSUE TITLE
[FR] Dynamic Acceleration Adjustment

### ISSUE THREAD

**Issue by AmyTheCute** [MarlinFirmware/Marlin#15035]
### Description

Dynamic Acceleration control for Marlin!

#### Additional Information

https://duet3d.dozuki.com/Wiki/Gcode#Section_M593_Configure_Dynamic_Acceleration_Adjustment

this is stupidly cool! i saw a few people post the results and it makes a world of difference! it'd be great to have on marlin 2.0 :) specially with the 32-bit boards!

**Comment by Minims** [comment]
Is it the same thing as Resonance Compensation ?  :  https://www.klipper3d.org/Resonance_Compensation.html

**Comment by haarp** [comment]
I believe this is what #16531 is about. Am I wrong?

**Comment by thisiskeithb** [comment]
> I believe this is what #16531 is about. Am I wrong?

Indeed. Please migrate discussion to #16531 since it has had a lot more discussion.
