### ISSUE TITLE
K8200 wrong pin

### ISSUE THREAD

**Issue by rokrodic** [MarlinFirmware/Marlin#1504]
Hi.
The #define Z_ENABLE_PIN should be 63 !!! for K8200.

Current statement in pins_RAMPS_13.h:
# define Z_ENABLE_PIN       62

**Comment by thinkyhead** [comment]
How about 3DRAG? Same thing, you think?

**Comment by rokrodic** [comment]
As I know the PCBs are the same. I checked my setting for 63 and my K8200 printer now works...

**Comment by thinkyhead** [comment]
Great, should be patched now!
