### ISSUE TITLE
[BUG] PID

### ISSUE THREAD

**Issue by Tinchus2009** [MarlinFirmware/Marlin#15056]
Marlin version 2.0.x

Hello, just wanted to report this:
I was previously useing marlin 1.1.9 with great results. My PID settings were working really good with a temperatures with a variation of only +-0.3 degrees

I wanted to check the new features in 2.0.x so I moved there. 
I copied thr same PID settings, even the values. But now the temperature variations are too big. I reach target temp and them temperature drops like 7 dregrees, then goes again to target, sometime it overshoots 1 or 2 degrees, then drops 7 degrees or 8.
I ran the pid auto temp again, but I got the same results.

I went back to marlin 1.1.9 and everything works good again.
I have atached my configuration.h just in case you want to take a look and discard a confifuration problem before checking a posible bug.
My hardware is a arduina mega 2560 board.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3538909/Marlin.zip)

**Comment by Grogyan** [comment]
Did you update your eeprom settings when you switched from 1.1.9 to 2.0?

**Comment by Tinchus2009** [comment]
Yes, I erased the eprom completly just to be sure

**Comment by GMagician** [comment]
PID handling code has been changed in 2.0, recently (#14373). Not sure old values are still valid. try to re-execute tuning

**Comment by AnHardt** [comment]
Do you talk about the bed or the extruder?
If bed - PID is not on.
If extruder - why SLOW_PWM_HEATERS?

**Comment by Tinchus2009** [comment]
Im talking about the extruder
I did. First try was with old values. Then when it didnt worked, I ran the auto tune again and still was showing this behaviour. 
SLOW_PWM_HEATERS = I tried also with this feature enabled. My configuration uses a rele for the bed and heaters, so I tried this option just in case. It doesnt help either

**Comment by blueeagle69** [comment]
I have had the same issue since installing my SKR 1.3 and Marlin 2.0.
I have done multiple PID tuning runs, makes no difference.
Originally my extruder temp was overshooting by around 13 degrees on 2.0. With 1.9 it was perfect.
I have managed to get it down to an overshoot of around 7 degrees by playing about with PID_FUNCTIONAL_RANGE. Much better now, but slows down the print start or when changing filament etc, because it overshoots and then has to cool down to it's proper temperature.

**Comment by BrokenFish** [comment]
I have the same problem on my skr v1.3. Sometimes when i preheat it is perfect afterwards. But the moment I start the print I get big variations.

Edit:
Nevermind. For me it was an electrical problem.

**Comment by boelle** [comment]
@Tinchus2009 is this still a problem?

**Comment by Tinchus2009** [comment]
Yes. I tried everything. I have to say that is not the first time I use Marlin, Im using it and configuring printer with it sine at least 3 years, so Im quit sure Im not making a config mistake. Also I know how to set up a PID, even manually. I have tried everything, and it doesnt work. I went back not to marlin 1.1.9 and PID is working perfectly, so I can discard hardware issues too. Something is not well with PID in version 2 when used in 8 bit electronics.

**Comment by boelle** [comment]
how did you "Yes, I erased the eprom completly just to be sure"  ?

**Comment by thinkyhead** [comment]
Sometimes it can help to just manually tune the PID. If you can find a range of values that work well, we can compare those to the PID values that worked with 1.1.9 and see if there's some correlation or pattern to the discrepancy. So far I have not experienced PID problems, but I also haven't been paying the closest attention to my temperature graphs.

**Comment by Tinchus2009** [comment]
> 
> 
> how did you "Yes, I erased the eprom completly just to be sure" ?

From arduino IDE, there is an example script that erases the eprom.

**Comment by boelle** [comment]
that one will do, but also you can just send M502 and then M500

**Comment by boelle** [comment]
@Tinchus2009 any news?

**Comment by Tinchus2009** [comment]
No, I gave up with version 2.X, I went back to 1.1.9

**Comment by boelle** [comment]
will vlose this one

we can always reopen if multiple users can confirm there is an issue and we have their configs
