### ISSUE TITLE
[QUESTION] [2.0-BUGFIX] Increse Z Axis speed while probing

### ISSUE THREAD

**Issue by ISAndreiva** [MarlinFirmware/Marlin#15059]
Hello!
I've activated `#define BLTOUCH_HS_MODE`, but it barely hits the glass while the Z axis is going up.
Any way to increase the speed Z axis speed while probing so that can't happen?
Thanks in advance!

**Comment by RudyBenner** [comment]
#define Z_PROBE_SPEED_FAST HOMING_FEEDRATE_Z
