### ISSUE TITLE
[QUESTION] How to use mini UPS

### ISSUE THREAD

**Issue by manarsak** [MarlinFirmware/Marlin#15062]
Hi I have an mini ups when I want to lose power  that moves the axis Z 2mm
![2124611968-413015883](https://user-images.githubusercontent.com/25624009/63693197-b5b54380-c813-11e9-928d-8ac641b3a6b2.jpg)

**Comment by boelle** [comment]
i assume that you are asking how to use the mini ups? its hard to guess as you are only telling you have one

**Comment by manarsak** [comment]
I think you did not understand what I mean I mean when the loss of energy moving axis in order not to spoil the printing I have made several attempts but I face some mistakes

**Comment by boelle** [comment]
attach your 2 config files as a zip, some smarter than me might be able to figure out if you have it configured wrong

**Comment by InsanityAutomation** [comment]
Zaxis should NOT be moved on power loss. It is expected that it will retain last known position by resting on the print. If it has raised, it will most likely drift down slightly with no power and the risk of the print being scrapped instead of just a possible bump if stopped on a perimeter is extremely high. X/Y can rehome but Z cannot.

**Comment by manarsak** [comment]
Marlin.cpp

#if ENABLED(POWER_LOSS_RECOVERY)
void powerFailedDetect(void) {
  static bool isPowerFailed = false;
  if (!isPowerFailed && READ(POWER_LOSS_PIN) == POWER_LOSS_STATE) {
    isPowerFailed = true;
    thermalManager.disable_all_heaters(); //turn off heaters
    disable_all_steppers();

    SERIAL_ERROR_MSG("Power failed!");
      queue.clear();
    quickstop_stepper();

   queue.enqueue_now_P(PSTR("G91\nG1 E-10\nG1 Z10\n"));
    while (1) {
    #if ENABLED(USE_WATCHDOG)
      watchdog_reset();
    #endif
     queue.advance();   
      manage_inactivity(
        #if ENABLED(ADVANCED_PAUSE_FEATURE)
          no_stepper_sleep
        #endif
      );
    }
  }
}
#endif

#if !ENABLED(POWER_LOSS_RECOVERY)
static bool power_detect_enabled = false;
void GcodeSuite::M413()
{
  if (parser.seen('S'))
    power_detect_enabled = parser.value_bool();
  else {
    SERIAL_ECHO_START();
    SERIAL_ECHOPGM("Power-loss recovery ");
    serialprintln_onoff(power_detect_enabled);
  }
}              
#endif

**Comment by AnHardt** [comment]
> Zaxis should NOT be moved on power loss. It is expected that it will retain last known position by resting on the print. If it has raised, it will most likely drift down slightly with no power and the risk of the print being scrapped instead of just a possible bump if stopped on a perimeter is extremely high. X/Y can rehome but Z cannot.

Bla, bla, bla! Lift and home to z-max.

**Comment by AnHardt** [comment]
```
disable_all_steppers();

SERIAL_ERROR_MSG("Power failed!");
  queue.clear();
quickstop_stepper();
queue.enqueue_now_P(PSTR("G91\nG1 E-10\nG1 Z10\n"));
```
Doesn't make much sense. Disabling the steppers before the relative retraction and lift.

**Comment by manarsak** [comment]
I want to lift in order not to spoil the printing

**Comment by InsanityAutomation** [comment]
> I want to lift in order not to spoil the printing

and we're telling you that's exactly what it'll do because then the Z position will be unknown with no way to re reference.

**Comment by manarsak** [comment]
When we resume printing, we can reduce the axis with the same value we raised or can we move the axis X

**Comment by InsanityAutomation** [comment]
> When we resume printing, we can reduce the axis with the same value we raised or can we move the axis X

Except as I stated earlierfew machines if any will retain Z position without being supported when powered off. You're lucky enough it holds level let alone height. Also you have no guarantee whatsoever there is enough power to complete said move and no feedback if it doesn't.

**Comment by Roxy-3D** [comment]
@manarsak    SERIOUSLY...    Stubbornness is not the right way to get the Marlin Team to expend effort on your desires.    LISTEN to what the experts are saying.    Questions and discussions are OK.   But expend some effort to understand what the experts are trying to communicate.

**Comment by manarsak** [comment]
Thank you so much. Can I ask you another question

**Comment by manarsak** [comment]
I'm not stubborn. I just want to take advantage of this feature just to change. Thank you Marlin

**Comment by Roxy-3D** [comment]
Please allow me to give a hypothetical response to the above expertise that has been communicated.   Suppose you had a UPS that can provide 2 or 3 hours of +5 power, but only 30 seconds of +12 power.

Most stepper motors run off of 12 volts.    Most printer electronics run off of 5 volts.    It would be perfectly reasonable to watch for a Power Fail signal and use the 30 seconds you have of stepper power to move the nozzle away from the print, while using the +5 volts to the electronics to remember where you are.    

But you still have the problem that most stepper motors wont exactly hold position without power.    One solution might be to raise the nozzle a little bit upon power resumption and home the X and Y axis.   And then follow AnHardt's suggestion and home to Z-Max.   That might avoid a layer shift.   I don't know.      

That type of thinking and discussion is how the code base makes progress forward.

**Comment by manarsak** [comment]
Sir, I can when the loss of energy to save the place and then move the axis a little This panel is enough to move the axis when the loss of energy I want that when the loss of energy to save the current place and then move the axis step up or we can move the X axis instead of Z
We can shoot a video to see how the axis moves when energy is lost

**Comment by Grogyan** [comment]
@manarsak The mini UPS is kinda a trap.

It will not do, what you think it does, and the previous responses are accurate.

I will however say that, the mini UPS will NOT provide enough power to do anything like moving an axis on power loss. Josef Prusa has said, with his machines, and I strongly suggest looking into such a low cost Power Loss Recovery system.
Prusa Research developed Power Panic, to detect on the mains input, as soon as power is lost, thus using the really, big, capacitors in the power supply to put the machine into a safe state.
Another alternative to the Power Panic, is the MKS DET board, which operates in a similar fashion.

**Comment by manarsak** [comment]
Thank you I have solved the problem, which is when the loss of energy saves the place and then move the X axis to the beginning and after the resumption of printing returns X converter to the place before the loss of energy Thank you very much

**Comment by AnHardt** [comment]
Going exactly back to the stored position is perfectly possible. Alone the stored position is not the position the printhead had when stopping the print. The planner buffer makes the difference. That's rarely observed because in the perimeters the way in the buffer is usually short and in the infill, where the ways are long, the error is covered by the next layer. But if a layer change is lost in the buffer ...
