### ISSUE TITLE
Marlin bugfix-2.0.x seg fault when setting E0_AUTO_FAN_PIN to 7

### ISSUE THREAD

**Issue by colindembovsky** [MarlinFirmware/Marlin#15075]
### Description

I get a segmentation fault when defining a custom `E0_AUTO_FAN_PIN` for MKS_GEN_L motherboard. If the value is -1, or 9 (`HEATER_1_PIN`) then I get a successful compile. However, in my setup it should be pin 7. The pins.h file for the board defines `MOSFET_D_PIN` as 7, but I get the seg fault with this value too.

### Steps to Reproduce

1. Clone repo and set branch to `bugfix-2.0.x`
2. Change motherboard to `BOARD_MKS_GEN_L`
3. Define `BLTOUCH`
4. Define TMC2209 for stepper drivers
5. Define bilinear bed leveling
6. Compile <-- success
7. Set `E0_AUTO_FAN_PIN` to 7 in `Configuration_adv.h`
8. Compile <-- seg fault

**Expected behavior:** [What you expect to happen]
Successful compilation.

**Actual behavior:** [What actually happens]
```
sketch\src\gcode\queue.cpp: In function 'gcode_line_error':
sketch\src\gcode\queue.cpp:301:1: internal compiler error: Segmentation fault
 }
^

Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper.exe: fatal error: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.
```
#### Additional Information

Link to Configuration.h and Configuration_adv.h: https://github.com/colindembovsky/Marlin/tree/ender3/Marlin

**Comment by AnHardt** [comment]
That's a compiler (gcc) error. Use a different ArduinoIDE version.

**Comment by colindembovsky** [comment]
Thanks @AnHardt - Arduino IDE 1.8.9 had the segfault, but I got a clean compile on 1.8.7.

**Comment by solhaga12** [comment]
In queue.h try:
static void gcode_line_error(PGM_P const err, const int8_t port) _O2;

It's the same fix as in temperature.h:
static void manage_heater() _O2; // Added _O2 to work around a compiler error

**Comment by colindembovsky** [comment]
Hi @solhaga12 - I get a bit further (I think) but now I get a segfault in `parser.h`:

```
c:\users\colin\appdata\local\temp\arduino_build_144001\sketch\src\gcode\parser.h: In function 'linearval':

c:\users\colin\appdata\local\temp\arduino_build_144001\sketch\src\gcode\parser.h:376:124: internal compiler error: Segmentation fault

    static inline float    linearval(const char c, const float dval=0)    { return seenval(c) ? value_linear_units() : dval; }
```

**Comment by solhaga12** [comment]
Sorry, I haven´t got a clue.
