### ISSUE TITLE
[BUG] UBL ignores soft end stops, incorrect movements

### ISSUE THREAD

**Issue by 2kingsrock** [MarlinFirmware/Marlin#15074]
### Description

Failed Attempts to auto generate mesh.  Using fixed probe.  COREXY, SKR v1.3 / DRV 8825.  Dual Z steppers (Z and E1).  Ran UBL, will not move in Y away from home to back of bed. X seems erratic.  
### Steps to Reproduce

1. Cleared EEPROM (mesh bed is blank as expected)
2. Home (0,0,0) from left and start UBL cold mesh
3. Probe takes a few points and moves in X away from Home position.
4. As collection continues, sometimes the carriage will stay in the same position, with the LCD incrementing probe/point values 6/100 - 10/100 and not move.
4. System ignores Physical end stops / software end stops and overdrives edge locations.

**Expected behavior:** Probe should respect physical end stops / soft end stops / and any offsets / setbacks when collecting data for the mesh.

**Actual behavior:** System appears to run randomly hopping around, ignoring end stops, and slamming into the bed and sides.  :) 

#### Additional Information
This worked as expected 4-6 weeks ago.  I may have incorrect variables in the way I am using creating the misconfigured settings or there are some math errors generated in the base code during this collection.

System homes to (0,0,0) front left corner without issues.  Calibrated movement to edges of bed (320 x 320).  Runs and respects end stops during normal prints, movements.  I have tried to run a 'G29 P1' when the carriage is centered, still overdrives to front and sides.  Physically where the system thinks it should be (assuming the LCD has the correct location) and where the carriage is actually at, does not line up.  After homing, the LCD and location of carriage are synced.  After several probe / move attempts the LCD may show the X 100, Y150, Z 10.  Physically the carriage is at X 200, Y10, Z10 (or anywhere but where the LCD is displaying
[Upload_debug.zip](https://github.com/MarlinFirmware/Marlin/files/3544282/Upload_debug.zip)
). 

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by 2kingsrock** [comment]
I do have other controllers and drivers I could use to test if i needed to.  
Again currently running 8825, BigTree SKR V1.3, with LCD.  I took all the complicated items off, lol.
Thanks for the help and review of this issue. 

These values below seem questionable, especially if they are real x y z travel locations.  
During the time of the mesh collection, the Y stayed at 0, X wanted to move to negative values.
  
Recv: Machine Type: Core
Recv: Probe: FIX_MOUNTED_PROBE
Recv: Probe Offset X:45 Y:15 Z:-0.87 (Right-Back & Below Nozzle)
Recv: Auto Bed Leveling: UBL
Recv:  (disabled)
Recv: 
Recv: Raise Z (before homing) to 5.00
Recv: >>> do_blocking_move_to(0.00, 0.00, 5.00)
Recv: <<< do_blocking_move_to
[...]
Recv:   current_position=(0.00, 0.00, 5.00) : sync_plan_position
Recv: >>> do_blocking_move_to(-483.75, -498.75, 5.00)
[Upload_debug_v2.zip](https://github.com/MarlinFirmware/Marlin/files/3548294/Upload_debug_v2.zip)

**Comment by 2kingsrock** [comment]
Additional information...   Ran BILINEAR  in a 3 x 3 grid.  X stops at all  3 points (1, 2, 3) along front and stays within bed parameters.  Y does not advance during point check 4.  Probe point (4 stays on location 3 (it should have moved back in Y 160), 5 returns to location 2, Probe 6/7 returns to 1, etc.  

So the Probe is in the same spot A for points (1,6,7). Prob is at B for points (2,5,8).  Probe is at location C for points (3,4,9).  
[3x3_bilinear.txt](https://github.com/MarlinFirmware/Marlin/files/3548437/3x3_bilinear.txt)

**Comment by boelle** [comment]
@2kingsrock is this still an issue?

**Comment by Jimbo145** [comment]
I am encountering the same issue, with the same erratic movements, unsynced location readouts and overrun constraints.

Cartesian
Fixed Probe
Dual Z steppers (Z and E1)
TMC2130 drivers

**Comment by boelle** [comment]
@2kingsrock as many updates have been added in the last 27 days, is this still an issue?

**Comment by shitcreek** [comment]
Confirming strange behaviour with UBL and with today's build (11/15). Attempting the cold mesh leveling, after homing, it probes the 1st point in the middle then goes to the 2nd point and ends the process. In between points I can hear a faint beep from the speaker. Also it takes the LCD a few seconds to return to the main screen and about another second to update the display to show that it is probing. I will investigate further tomorrow.

Machine specs:
CR-10S, BTT SKR v1.3, TMC2208, BLTouch

--made some correction to my observation.

**Comment by boelle** [comment]
@shitcreek had time to play arround with this?

**Comment by shitcreek** [comment]
I think I've figured it out and you might kick yourself for this: `MIN_PROBE_EDGE` needs to be equal to or less than `MESH_INSET`
I can now set and probe any number of points long as `MIN_PROBE_EDGE` is not greater than `MESH_INSET`

I will investigate the code and see what exactly is the discrepancy.

**Comment by boelle** [comment]
@2kingsrock since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by boelle** [comment]
@2kingsrock is this still an issue?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by boelle** [comment]
a lot of updates and fixing has happend in the last week, is the problem still there?

**Comment by boelle** [comment]
@2kingsrock 
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

@shitcreek

**Comment by jahkeup** [comment]
I'm seeing this with an SKR 1.4 Turbo board (`LPC1769`) using TMC2209's running in UART mode. The travels made during `G29 P1` drastically differ from the actual position (which is closer to `X200`). However, the reported positions, from `M114 D`, after cancelling look pretty much the same compared to moves after homing.

I'm adding my configuration. The big bits I changed (that come to mind as related):

- sensorless homing
- reduced `*_BED_SIZE` and `MAX/MIN_POS` set
- bltouch

These run on a cannibalized Ender 3 frame. I've checked the belts' tension and confirmed the measurements of travel on every axis.

I'm now checking & testing my feedrate settings and have also spent a little time with the code trying to determine if `G29`'s `best` position is respecting all configured workspace offsets. 

I think, based on the reported positions, that it isn't an issue with the workspace calculations. I'm suspecting there may be either poor interaction with the drivers (either the drivers themselves or the TMCStepper lib) OR that there's an internal "rebase" of positioning that causes soft endstops to be "offset" from another base point. Take that with a grain of salt as I'm not familiar with the code enough to make a firm statement on anything.. really.

[jahkeup-config-1593821915-aab0d057.wip.tar.gz](https://github.com/MarlinFirmware/Marlin/files/4871900/jahkeup-config-1593821915-aab0d057.wip.tar.gz)

[G29-movement-failure.log.txt](https://github.com/MarlinFirmware/Marlin/files/4871905/G29-movement-failure.log.txt)

---

`M114 D` at the reported position just after cancelling an incorrect `G29 P1` run shows the following:

```
2020-07-03 16:25:43,736 - Recv: echo:M114 D
2020-07-03 16:25:43,737 - Recv: X:166.87 Y:191.15 Z:10.16 E:0.00 Count X:13462 Y:15351 Z:4085
2020-07-03 16:25:43,738 - Recv: 
2020-07-03 16:25:43,740 - Recv: Logical: X: 166.874 Y: 191.146 Z: 10.160
2020-07-03 16:25:43,741 - Recv: Raw:     X: 166.874 Y: 191.146 Z: 10.160
2020-07-03 16:25:43,742 - Recv: Leveled: X: 166.874 Y: 191.146 Z: 10.160
2020-07-03 16:25:43,743 - Recv: UnLevel: X: 166.874 Y: 191.146 Z: 10.160
2020-07-03 16:25:43,745 - Recv: Stepper: X:13462 Y:15351 Z:4085 E:0
2020-07-03 16:25:43,746 - Recv: FromStp: X: 166.873 Y: 191.146 Z: 10.160 E: 0.000
2020-07-03 16:25:43,748 - Recv: Diff:    X:-0.001 Y:-0.000 Z:-0.000 E: 0.000
2020-07-03 16:25:43,750 - Recv: ok P15 B15
```

Using `G1 X166.87 Y191.15` after a "fresh" `G28` shows the following:

```
2020-07-03 16:45:16,404 - Send: M114 D
2020-07-03 16:45:16,405 - Recv: echo:M114 D
2020-07-03 16:45:16,407 - Recv: X:166.87 Y:191.15 Z:10.16 E:0.00 Count X:13462 Y:15351 Z:4085
2020-07-03 16:45:16,409 - Recv: 
2020-07-03 16:45:16,411 - Recv: Logical: X: 166.870 Y: 191.150 Z: 10.160
2020-07-03 16:45:16,414 - Recv: Raw:     X: 166.870 Y: 191.150 Z: 10.160
2020-07-03 16:45:16,414 - Recv: Leveled: X: 166.870 Y: 191.150 Z: 10.160
2020-07-03 16:45:16,415 - Recv: UnLevel: X: 166.870 Y: 191.150 Z: 10.160
2020-07-03 16:45:16,416 - Recv: Stepper: X:13462 Y:15351 Z:4085 E:0
2020-07-03 16:45:16,416 - Recv: FromStp: X: 166.873 Y: 191.146 Z: 10.160 E: 0.000
2020-07-03 16:45:16,421 - Recv: Diff:    X: 0.003 Y:-0.004 Z:-0.000 E: 0.000
2020-07-03 16:45:16,422 - Recv: ok P15 B15
```

```patch
--- /tmp/M114-G1.txt    2020-07-03 16:51:22.663052854 -0700
+++ /tmp/M114-UBL.txt   2020-07-03 16:51:29.272037953 -0700
@@ -1,11 +1,11 @@
 Recv: echo:M114 D
 Recv: X:166.87 Y:191.15 Z:10.16 E:0.00 Count X:13462 Y:15351 Z:4085
 Recv:
-Recv: Logical: X: 166.870 Y: 191.150 Z: 10.160
-Recv: Raw:     X: 166.870 Y: 191.150 Z: 10.160
-Recv: Leveled: X: 166.870 Y: 191.150 Z: 10.160
-Recv: UnLevel: X: 166.870 Y: 191.150 Z: 10.160
+Recv: Logical: X: 166.874 Y: 191.146 Z: 10.160
+Recv: Raw:     X: 166.874 Y: 191.146 Z: 10.160
+Recv: Leveled: X: 166.874 Y: 191.146 Z: 10.160
+Recv: UnLevel: X: 166.874 Y: 191.146 Z: 10.160
 Recv: Stepper: X:13462 Y:15351 Z:4085 E:0
 Recv: FromStp: X: 166.873 Y: 191.146 Z: 10.160 E: 0.000
-Recv: Diff:    X: 0.003 Y:-0.004 Z:-0.000 E: 0.000
+Recv: Diff:    X:-0.001 Y:-0.000 Z:-0.000 E: 0.000
 Recv: ok P15 B15
```

**Comment by jahkeup** [comment]
Double checked everything and I'm confident I'm **not** seeing the same issue. My problem was that I built with misconfigured default accelerations in place. After some tuning, expected movements are used and now no illegal movements are made during `G29 P1`.

**Comment by thinkyhead** [comment]
> trying to determine if G29's best position is respecting all configured workspace offsets

Internally, UBL ought to be working with native coordinates, so workspace offsets don't apply.

The internal movement method `prepare_line_to_destination` (used by `_internal_move_to_destination` and `prepare_internal_move_to_destination`) is constrained to soft endstops, but when operations (such as `G28`) need free movement they set the `soft_endstops_enabled` to `false`.

The UBL procedures use the "blocking move" functions, which are also not affected by soft endstops.

Maybe the issue is something like the aforementioned "`MIN_PROBE_EDGE` needs to be equal to or less than `MESH_INSET`".
