### ISSUE TITLE
[BUG] M119 and bltouch pin down

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#15083]
Is it desired behaviour that M119 deploy bltouch (clone) and leave it deployed?

**Comment by InsanityAutomation** [comment]
Id say no! Sounds like the clone is interpreting the switch mode command as a deploy, though this is the first ive heard of it. While I hesitate to add yet another option, we could add a "Classic mode" that disables all but the most fundamental commands....

**Comment by GMagician** [comment]
I suspect sw_mode is the involved command. I may try to confirm that it's him (changing code), I'll let you know

**Comment by GMagician** [comment]
I think cause is `_reset_SW_mode`:
```c++
FORCE_INLINE static void _reset_SW_mode()      { if (triggered()) _stow(); else _deploy(); }
```

**Comment by InsanityAutomation** [comment]
Looks like thatd do it on genuine probes older than V2.0 as well.

**Comment by GMagician** [comment]
I tested, cause is `_set_SW_mode`

**Comment by GMagician** [comment]
> we could add a "Classic mode"

if issue is only in m119 I may say "who cares", I can keep it as it is
