### ISSUE TITLE
[FR] Add the ability to define TMC5161 stepper driver

### ISSUE THREAD

**Issue by mak0t0san** [MarlinFirmware/Marlin#15105]
### Description

The TMCStepper library has support for the TMC5161 driver, although it currently just imherits from the 5160 class and doesn't add any other functionality but there's a possibility that the TMC5161 class may have different logic.  https://github.com/teemuatlut/TMCStepper/blob/83193ffd1872e1c38c1225f558e99fc9aac78932/src/TMCStepper.h#L796

The Marlin Configuration.h file will allow me to specify TMC5161 as the driver type and successfully build, however the checks in the other files don't check for TMC5161 and as a result the Trinamic code doesn't become part of the compiled code.

For example, from drivers.h
```
#define HAS_TRINAMIC (    HAS_DRIVER(TMC2130) \
                       || HAS_DRIVER(TMC2160) \
                       || HAS_DRIVER(TMC2208) \
                       || HAS_DRIVER(TMC2209) \
                       || HAS_DRIVER(TMC2660) \
                       || HAS_DRIVER(TMC5130) \
                       || HAS_DRIVER(TMC5160) )
```

This should have the addition of 
`|| HAS_DRIVER(TMC5161)
` 
### Steps to Reproduce

1. In configuration.h, set the driver type to TMC5161
  `#define X_DRIVER_TYPE  TMC5161`
2. Confirm that the code will compile
3. The driver will not work

#### Additional Information

* Using TMC5160 as the driver type will work fine for now but it would be nice to have TMC5161 as its own type.  If this is a valid feature request, I don't mind going through the code and adding it where it is needed.

**Comment by thisiskeithb** [comment]
Superseded by https://github.com/MarlinFirmware/Marlin/issues/16365
