### ISSUE TITLE
[BUG]Marlin 2.0 - SKR 1.3 error: 'internalSerial' was not declared in this scope

### ISSUE THREAD

**Issue by Cybercat1991** [MarlinFirmware/Marlin#15119]
### Description

error: 'internalSerial' was not declared in this scope

### Steps to Reproduce

I had before my SKR 1.3 to expand with a MMU2, when setting Marlin 2.0 (22.8 download, synonymous with the current version) appears an error. pastbin-link inserted below.

#### Additional Information
https://pastebin.com/H0AJp4ce
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3562710/Configuration.zip)
[Marlin-2.0_22.8.2019.zip](https://github.com/MarlinFirmware/Marlin/files/3562716/Marlin-2.0_22.8.2019.zip)

**Comment by Ludy87** [comment]
> For AVR enable the UART port used for the MMU. (e.g., internalSerial)
> For 32-bit boards check your HAL for available serial ports. (e.g., Serial2)

**Comment by Cybercat1991** [comment]
> For AVR enable the UART port used for the MMU. (e.g., internalSerial)
> For 32-bit boards check your HAL for available serial ports. (e.g., Serial2)

Edit to   
#define INTERNAL_SERIAL_PORT 2
#define MMU2_SERIAL Serial2

**Additional Information**
https://pastebin.com/CmXtkSRp

**Comment by Cybercat1991** [comment]
/**
 * Select a secondary serial port on the board to use for communication with the host.
 * This allows the connection of wireless adapters (for instance) to non-default port pins.
 * Serial port -1 is the USB emulated serial port, if available.
 *
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT_2 2

and 

  // Serial port used for communication with MMU2.
  // For AVR enable the UART port used for the MMU. (e.g., internalSerial)
  // For 32-bit boards check your HAL for available serial ports. (e.g., Serial2)
  #define INTERNAL_SERIAL_PORT 2
  #define MMU2_SERIAL MSerial2

its work.

**Comment by Sjoerd** [comment]
@Sythx I got the error that `MSerial2` is not defined.
Could you share your config files with us?
