### ISSUE TITLE
[BUG] Filament change freezes printer (M600)

### ISSUE THREAD

**Issue by albert2004** [MarlinFirmware/Marlin#15145]
# Description
Printer freeze after changing filament

### Steps to Reproduce

1. Issue M600 to change filament.
2. Wait until extruder is parked and unload procedure finishes
3. Replace filament.
4. Press button to confirm finish or replacement.

After filament change and confirmation by pressing button, on serial console there is counting down from 8 to 2 (seconds).
At last point, I hear short extruder motor activation and printer freezes. LCD is blank, no reaction for serial commands.

**Expected behavior:** print resumes

**Actual behavior:** freeze of printer, needed cold restart

#### Additional Information
GIT revision: 12c595c61f4b3e0be2baa6a906718e155a797ea3

**Comment by thisiskeithb** [comment]
This probably related to https://github.com/MarlinFirmware/Marlin/issues/15138 which has been patched, so download a fresh copy and see if the issue persists.

**Comment by albert2004** [comment]
Yes, I can confirm. New version works again.
Closing.
