### ISSUE TITLE
[BUG] (MKS Robin Lite 1.1 - Won't boot anymore)

### ISSUE THREAD

**Issue by ETE-Design** [MarlinFirmware/Marlin#15143]
### Description

After updating to newest Bugfix 2.x the MKS Robin Lite 1.1 freeze at "Updating 100%" - 14 days ago it just worked...
Mabye it has something to do with U8glib-HAL, cause before I have some warnings / error now I have none, and it dosen't work anymore...

### Steps to Reproduce

1. Build MKSLite.bin
2. Put SD Card in Printer]
3. Turn on and wait
4. Freeze at "Updating 100%"

**Expected behavior:** [Flash 100% and then reboot]

**Actual behavior:** [Flash 100% and freeze]

**Comment by RudyBenner** [comment]
Try this
![image](https://user-images.githubusercontent.com/40361032/64138049-2be41800-cdc9-11e9-8664-be99f9db9e62.png)

**Comment by RudyBenner** [comment]
Try this
![image](https://user-images.githubusercontent.com/40361032/64138315-9184d400-cdca-11e9-96bd-be330b8a29fd.png)

**Comment by RudyBenner** [comment]
Missing bootscreen.h file in your zip file?

**Comment by anabos1758** [comment]
I have the same issue with ADMINLab Gantry S. The Marlin firmware code from Makerbase GitHub repository works(not up to date with offical Marlinfw repository).

**Comment by tpruvot** [comment]
may be fixed by #15172 on the robin, please try and report

**Comment by anabos1758** [comment]
Thanks, The problem is fixed. It is working.

**Comment by ETE-Design** [comment]
Anabos1758 - Same here... But now it won't find any files in my SD Card, same for you? Or can you share your configuration files then?

**Comment by anabos1758** [comment]
ETE-Degin
I am able to print from SD. However I have issues with 3DTouch (BLTouch
clone) deploys during print. I have abort at this point.
Here is my Config. I believe I took yours and added my settings.   I am
experimenting with 3DTouch on ADIMLab Gantry-s. I have enabled few configs
for debug/experiment.

**Comment by anabos1758** [comment]
[myconf.zip](https://github.com/MarlinFirmware/Marlin/files/3584387/myconf.zip)
My Config files

**Comment by RudyBenner** [comment]
I hope PC11 is not defined elsewhere.....

**Comment by anabos1758** [comment]
Thanks for the suggestion. I suspect electrical (noise or poor connection)
or faulty sensor (may need probe adjustment). However I added the following
to my code.
//Using WIFI module's IO Pin for servo
#ifdef NUM_SERVOS
 #ifdef PC11
  #undef PC11
 #endif
#define SERVO0_PIN PC11 //WIFI IO2 PIN
#endif

**Comment by tpruvot** [comment]
its not good to undef PC11, its SERVO0_PIN you "could" undefine, but i dont think its preset
