### ISSUE TITLE
[BUG] (marlin 2.0 M109 Reboot )

### ISSUE THREAD

**Issue by gogsi1** [MarlinFirmware/Marlin#15146]
After sending the M109 command, the printer goes to reboot.
Board: skr v1.3

**Comment by thisiskeithb** [comment]
Download a fresh copy of `bugfix-2.0.x`. This was fixed earlier today: https://github.com/MarlinFirmware/Marlin/commit/12344085c0b7e51a0f8bdf54955a284dfb2be24f
