### ISSUE TITLE
I can't find the pioenvs folder when I compile in Marlin 2.0 bugfix downloaded today

### ISSUE THREAD

**Issue by 3DMakerES** [MarlinFirmware/Marlin#15151]
I can't find the pioenvs folder when I compile in Marlin 2.0 bugfix downloaded today , the whole process is correct, but when I look for the folder to use the .bin file the pioenvs folder doesn't exist.

**Comment by p3p** [comment]
The firmware binary is in `.pio/build/ENV/` since PlatformIO 4

**Comment by 3DMakerES** [comment]
Thank you very much for the help, it is already resolved.
