### ISSUE TITLE
[BUG] z_min endstop not stopping dual z steppers in autohome

### ISSUE THREAD

**Issue by MDVerdant** [MarlinFirmware/Marlin#15167]

**Comment by GMagician** [comment]
not clear what you mean with 

> even when dual end stop commented out

but dual stepper requires dual endstops

**Comment by shitcreek** [comment]
Please follow the template and provide more information. Also, have you exhausted other sources and find that this is indeed a bug?

For best results getting help with configuration and troubleshooting, please use the following resources:

MarlinFW.org Marlin Documentation
RepRap.org Marlin Forum
Tom's 3D Forums
Facebook Group "Marlin Firmware"
Facebook Group "Marlin Firmware for 3D Printers"
Marlin Configuration on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

If you are using the spare extruder stepper, then you must enable:
`Z_DUAL_STEPPER_DRIVERS` in `configuration_adv.h`
and `Z2_DRIVER_TYPE` enabled, **not** `E1_DRIVER_TYPE` in `configuration.h`

@GMagician - dual stepper **does not** require dual endstops.

**Comment by boelle** [comment]
@shitcreek it has been suggested on discord that we get a bot to precheck that issues are created like they should be, just like octoprint does it. maybe poke your "boss" and ask if its not time to do some testing on it
