### ISSUE TITLE
[BUG] M109 Causes Printer to Reset

### ISSUE THREAD

**Issue by joeb15** [MarlinFirmware/Marlin#15178]
When running a `M109 S<temp>` by itself on the 2.0-bugfix branch, the printer resets.

The same issue is not found when running a `M190` for the bed.

Configuration:
Printer: Ender3 Base
Mainboard: SKR 1.3
Drivers: TMC 2208 UART
Marlin: 2.0-bugfix

**Comment by thisiskeithb** [comment]
Have you tried a more recent copy of `bugfix-2.0.x`? This should have been fixed in 12344085c0b7e51a0f8bdf54955a284dfb2be24f.
