### ISSUE TITLE
[BUG] I want to lift steps/mm  to 4000 over LCD controller, but is max about 3200 and going to 5 back.

### ISSUE THREAD

**Issue by Milu1980** [MarlinFirmware/Marlin#15182]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Milu1980** [comment]
with pc connection is possible, but i need it in the LCD controller...
thx for the help

**Comment by gloomyandy** [comment]
How recent a version of Marlin are you using? In theory this was fixed a short while ago...
https://github.com/MarlinFirmware/Marlin/issues/14821

**Comment by Milu1980** [comment]
Hi,

i use malin 2.0 skr 1.3 board

Andy Shaw <notifications@github.com> schrieb am Fr., 6. Sep. 2019 16:48:

**Comment by Milu1980** [comment]
I tryed with pc i set 4000 its done, but on the lcd i see 3000.
i dont know now, that 3 or 4000 steps/mm i have :(

Radics Milán <radicsmilan@gmail.com> schrieb am Fr., 6. Sep. 2019, 18:51:

**Comment by AnHardt** [comment]
The fix is no fix. INT = INT32. limit was and is 3276.7 . At least not for this problem.

**Comment by AnHardt** [comment]
For now ,set with M92. Check with M503.

**Comment by Milu1980** [comment]
hi, yes about 3200...
can i change it in marlin somewhere ?

AnHardt <notifications@github.com> schrieb am Fr., 6. Sep. 2019, 20:42:

**Comment by gloomyandy** [comment]
@AnHardt So I guess that @thinkyhead proposed fix of making the menu only allow int values (https://github.com/MarlinFirmware/Marlin/issues/14821#issuecomment-518049811) did not happen?

**Comment by AnHardt** [comment]
#14909

**Comment by gloomyandy** [comment]
Though I'm always a little suspicious when I see folks using non integral steps/mm, often means something else is wrong with the mechanics of the machine (I suppose if you have very low steps/mm it may make sense).

**Comment by Milu1980** [comment]
hi, because i have translate inside. 3d printer, laser cutter and milling

Andy Shaw <notifications@github.com> schrieb am Sa., 7. Sep. 2019, 08:37:

**Comment by AnHardt** [comment]
It only needs imperial sized lead-screws to need fractions.

**Comment by Milu1980** [comment]
i have just ball screws.

AnHardt <notifications@github.com> schrieb am Sa., 7. Sep. 2019, 08:49:

**Comment by Patag** [comment]
@AnHardt AFAIK, extruder step/unit can't be an integer (unless rounding) , PI being used in the calculation

**Comment by boelle** [comment]
@Milu1980 still having problems?

**Comment by Milu1980** [comment]
yes...

Bo Herrmannsen <notifications@github.com> schrieb am Di., 24. Sep. 2019,
21:12:

**Comment by boelle** [comment]
have you tried with latest 2.0.x ?

**Comment by Milu1980** [comment]
no, i will try on the weekend...

Bo Herrmannsen <notifications@github.com> schrieb am Di., 24. Sep. 2019,
21:15:

**Comment by Milu1980** [comment]
can you please tell me what was changed ? i have too much setting in my
version to change it

Radics Milán <radicsmilan@gmail.com> schrieb am Di., 24. Sep. 2019, 21:15:

**Comment by boelle** [comment]
no i just update my copy of marlin and copy over old settings when the 2 settings files change layout

you can use a tool like winmerge to compare files and copy your settings

**Comment by boelle** [comment]
@Milu1980 did you try the latest 2.0.x ?

**Comment by thinkyhead** [comment]
This should fix the issue… f00b48f9a8da77d0d603b74c843359b82ee306e3
