### ISSUE TITLE
[BUG] BLtouch (clone) is probing in air

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#15198]
I installed a bltouch on my delta, and I can run auto calibration, after that if I try to run UBL bed leveling my effector will go all the way down till the bltouch is triggered, but this only works for one or two probe points, and then the effector will rise to the height that the bltouch pin just touch the surface but won't trigger the pin.

I think somewhere in my config my calculation logic is wrong or it's a bug? because it does hit and trigger once or twice.

Thanks.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3587658/Marlin.zip)

**Comment by tvixen** [comment]
I suggest you use #define GRID_MAX_POINTS_X 3
for a start, before you set it to 10. Just to minimize your waiting time :D

1. Which type of BLTouch probe do you have. Version 2.0 or 3.0 or 3.1 ??
2. Are you running the calibration via LCD display or Pronterface 
3. In pronterface, what happen when you give it G29 T (how many points are measured)

**Comment by boelle** [comment]
@Ke5han tried what @tvixen suggested?

**Comment by boelle** [comment]
will close this one as it seems that @Ke5han dont have an issue anymore

we can always reopen it
