### ISSUE TITLE
[BUG] MINTEMP triggering, despite being set below room temperature

### ISSUE THREAD

**Issue by Gooberpatrol66** [MarlinFirmware/Marlin#15211]
### Description

Hotend heats as expected, then MINTEMP is triggered once it starts extruding. HEATER_0_MINTEMP is set to 5. The thermistor is functional and reports accurate temperature in Octopi graph.

### Steps to Reproduce

1. start a print job

**Expected behavior:** [What you expect to happen]
print job proceeds
**Actual behavior:** [What actually happens]
MINTEMP triggered, system stopped! Heater_ID: 0 - Printer halted. kill() called!
#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/3592506/config.zip)
* Provide pictures or links to videos that clearly demonstrate the issue.
https://3dprinting.stackexchange.com/questions/10993/mintemp-hotend-drops-to-175c-once-extrusion-starts

**Comment by shitcreek** [comment]
Are you certain this is not a hardware issue? Have you checked all your connections and cables?

**Comment by Gooberpatrol66** [comment]
It reports normal temperatures until right after the plastic starts coming out.

**Comment by shitcreek** [comment]
Marlin 1.x is no longer being worked on. Please try out Marlin 2.0 and report back if the problem still exists.

**Comment by Gooberpatrol66** [comment]
It was a frayed wire.
