### ISSUE TITLE
[BUG] Can't disable STEALTHCHOP on TMC2208 MKS_GEN_L in Marlin 2.0 bugfix 

### ISSUE THREAD

**Issue by porlock** [MarlinFirmware/Marlin#15228]
Commenting flowing lines
```
  #define STEALTHCHOP_XY
  #define STEALTHCHOP_Z
  #define STEALTHCHOP_E
```
does not disable STEALTHCHOP, even settings 
`  #define TMC_ADV() { stepperX.en_spreadCycle(true); }`

does noting

M122 shows STEALTHCHOP set to on, and motors works ulta silently, like on STEALTHCHOP, i test it on MKG_GEN_L

### Steps to Reproduce

1. Comment out this lines
```
  //#define STEALTHCHOP_XY
  //#define STEALTHCHOP_Z
  //#define STEALTHCHOP_E
```
2. add this line 
`#define TMC_ADV() { stepperX.en_spreadCycle(true); }`
3. Compile and install Marlin 2.0 bugfix on MKS_GEN_L with TMC2208 in UART mode
4. Test is  STEALTHCHOP is disabled on X axis or any other

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3602379/Marlin.zip)

**Comment by boelle** [comment]
attach your 2 config files as a zip, just as the issue template told you to

**Comment by porlock** [comment]
sure, i added it in initial post

**Comment by shitcreek** [comment]
Did you run M502 and M500 after flashing?

**Comment by porlock** [comment]
Nope, i did not, I thought that disabling STEALTHCHOP for axis is not stored in user eprom configuration, because i don't see any gcode that could change that setting without recompiling firmware.

**Comment by shitcreek** [comment]
I had an issue when I was setting up the EZBoard with StealthChop until I ran M502.

**Comment by reloxx13** [comment]
its stored

http://marlinfw.org/docs/gcode/M569.html

**Comment by porlock** [comment]
Thanks, will test it and get back, thanks.

**Comment by porlock** [comment]
Not a bug, my mistake sorry.
