### ISSUE TITLE
[BUG] 3x Compile error with UBL and TX Buffer set

### ISSUE THREAD

**Issue by reloxx13** [MarlinFirmware/Marlin#15235]
### Description
If a TX Buffer is set in configuration_adv.h, compiling fails with UBL enabled.   
But i dont know why its affected by UBL.   

```
marlin\marlin\src\core\serial.h:79:44: 
error: 'class HardwareSerial' has no member named 'flushTX'; did you mean 'flush'?
   #define SERIAL_FLUSHTX()      SERIAL_OUT(flushTX)
```
   
   
I think its a typo after serial simplifing (PR https://github.com/MarlinFirmware/Marlin/pull/13234 ):
Marlin\src\core\serial.h   
![grafik](https://user-images.githubusercontent.com/14855001/64774162-f3280980-d553-11e9-9be9-f004665728fe.png)

#### Additional Information
Config:   
https://github.com/reloxx13/Marlin/tree/my-skr-mini-e3/Marlin

![grafik](https://user-images.githubusercontent.com/14855001/64774004-aa705080-d553-11e9-8bbe-cd82f55093be.png)
   
```
// Transmission to Host Buffer Size
// To save 386 bytes of PROGMEM (and TX_BUFFER_SIZE+3 bytes of RAM) set to 0.
// To buffer a simple "ok" you need 4 bytes.
// For ADVANCED_OK (M105) you need 32 bytes.
// For debug-echo: 128 bytes for the optimal speed.
// Other output doesn't need to be that speedy.
// :[0, 2, 4, 8, 16, 32, 64, 128, 256]
#define TX_BUFFER_SIZE 32
```

**Comment by reloxx13** [comment]
I set TX Buffer to 0 and get the next error:

![grafik](https://user-images.githubusercontent.com/14855001/64774643-db9d5080-d554-11e9-81cf-995697e97107.png)

Sanity check missing to disable LCD Leveling when using UBL   
or   
Move //#define LCD_BED_LEVELING inside the IF for mesh/abl    
```
/**
 * Add a bed leveling sub-menu for ABL or MBL.
 * Include a guided procedure if manual probing is enabled.
 */
//#define LCD_BED_LEVELING
```

fixed myself with disabling LCD_BED_LEVELING

**Comment by reloxx13** [comment]
After that, i get the next thing.................    

Typo again?    

![grafik](https://user-images.githubusercontent.com/14855001/64776365-5d42ad80-d558-11e9-9666-beb289a7b5ee.png)

Marlin\src\lcd\menu\menu_ubl.cpp:
```
/**
 * UBL LCD "radar" map point editing
 */
void _lcd_ubl_map_lcd_edit_cmd() {
  char ubl_lcd_gcode[50], str[10], str2[10];
  dtostrf(pgm_read_float(&ubl._mesh_index_to_xpos[x_plot]), 0, 2, str);
  dtostrf(pgm_read_float(&ubl._mesh_index_to_ypos[y_plot]), 0, 2, str2);
  snprintf_P(ubl_lcd_gcode, sizeof(ubl_lcd_gcode), PSTR("G29 P4 X%s Y%s R%i"), str, str2, int(n_edit_pts));
  lcd_enqueue_one_now(ubl_lcd_gcode);
}
```

**Comment by thinkyhead** [comment]
> After that, i get the next thing.................

![image](https://user-images.githubusercontent.com/698003/64860309-6718ef00-d5f2-11e9-9a5e-2a7e901acddd.png)

Do we need to implement our own `snprintf_P` or provide a glue function/macro for STM32?
