### ISSUE TITLE
[BUG] G33 calibration randomly fails.

### ISSUE THREAD

**Issue by Strat00s** [MarlinFirmware/Marlin#15238]
### Description

I have delta and recently upgraded to a 32bit board (SKR 1.3) and also to TMC2130 (and I have 256 micro-stepping). No matter what, when I run my usual printer calibration routine (G33 P1, P2, P5, P10) it always randomly fails. It usually fails when probing near the towers. I have no idea what to do with it because it is sometimes able to finish (eg. the P2 command). And when I run it for the second time it fails.

### Steps to Reproduce

1. No idea!!! Use true 256 micro-stepping and run G33...

**Expected behavior:** Calibration finishes without any problems

**Actual behavior:** Fails randomly when calibrating.

#### Additional Information

It actually finished once (but I that was pure luck), and I was able to use the printer in that state until yesterday when I wanted to do some cable management and I had to take it apart.

Error image and video:
https://imgur.com/a/Ei92DpN

Configs:
[config.zip](https://github.com/MarlinFirmware/Marlin/files/3607051/config.zip)

**Comment by shitcreek** [comment]
For starters you should use 16 steps instead and set `INTERPOLATE` to true - this way you will not overburden your board.

Are you sure all your delta settings are configured correctly?
http://cdr2.com/delta-calibration.html
http://marlinfw.org/docs/gcode/M665.html

**Comment by Strat00s** [comment]
> For starters you should use 16 steps instead and set `INTERPOLATE` to true - this way you will not overburden your board.
> 
> Are you sure all your delta settings are configured correctly?
> http://cdr2.com/delta-calibration.html
> http://marlinfw.org/docs/gcode/M665.html

Define starter. I had this delta as 8-bit for 2 years now.
100MHz board should be more than enough for 256 steps. (interpolation does not increase resolution, correct?). I was able to calibrate it once and then use it for about 14 days without any problems.
Yes, all my delta settings are correct. It worked like a charm with my old 8-bit setup.
I guess I can always go the manual way.

**Comment by shitcreek** [comment]
"For starters" simply means to begin with and with more to follow. It does not mean you are a noob or anything condescending.

With interpolation, your 16 steps is converted to 256 steps. Why have your main board do all the calculation when it can be outsourced to the stepper drivers and yield the same result.

Stolen from https://forum.duet3d.com/topic/3980/correct-microstepping-settings/13:

No micro stepping:
GCODE "Move X 1mm" => Duet "calculate 100 step pulses" => TMC Stepper Driver "100 step pulses" => Motor "1mm"
x16 micro stepping:
GCODE "Move X 1mm" => Duet "calculate 1600 micro-step pulses" => TMC Stepper Driver "1600 micro-step pulses" => Motor "1mm"
x16 micro stepping with interpolation to x256:
GCODE "Move X 1mm" => Duet "calculate 1600 micro-step pulses" => TMC Stepper Driver "25,600 micro-step pulses" => Motor "1mm"
x256 micro stepping:
GCODE "Move X 1mm" => Duet "calculate 25,600 micro-step pulses" => TMC Stepper Driver "25,600 micro-step pulses" => Motor "1mm"

**Comment by Strat00s** [comment]
> "For starters" simply means to begin with and with more to follow. It does not mean you are a noob or anything condescending.
> 
> With interpolation, your 16 steps is converted to 256 steps. Why have your main board do all the calculation when it can be outsourced to the stepper drivers and yield the same result.
> 
> Stolen from https://forum.duet3d.com/topic/3980/correct-microstepping-settings/13:
> 
> No micro stepping:
> GCODE "Move X 1mm" => Duet "calculate 100 step pulses" => TMC Stepper Driver "100 step pulses" => Motor "1mm"
> x16 micro stepping:
> GCODE "Move X 1mm" => Duet "calculate 1600 micro-step pulses" => TMC Stepper Driver "1600 micro-step pulses" => Motor "1mm"
> x16 micro stepping with interpolation to x256:
> GCODE "Move X 1mm" => Duet "calculate 1600 micro-step pulses" => TMC Stepper Driver "25,600 micro-step pulses" => Motor "1mm"
> x256 micro stepping:
> GCODE "Move X 1mm" => Duet "calculate 25,600 micro-step pulses" => TMC Stepper Driver "25,600 micro-step pulses" => Motor "1mm"

Well yea, but that won't add any resolution at all.

Anyways, the problem is still there even with 16 micro-steps and interpolation. It still randomly fails for no good reason.
Video:
https://imgur.com/a/6I0esMt

**Comment by Strat00s** [comment]
I am clueless, so I tried it with A4988 drivers and it worked for the first time like a charm. So I have really no idea what is the problem then. Because when it worked once, it worked without any problems with the tmcs.
http://imgur.com/a/d9pFTmJ

**Comment by tvixen** [comment]
Did you remove the dip's on the board. That would explain why your 4988 would run, but not the 2208

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
