### ISSUE TITLE
[BUG] SKR v1.3 not registering with any memory on mac

### ISSUE THREAD

**Issue by Epicotch** [MarlinFirmware/Marlin#15244]
Recently, while I was making my own 3D printer, I seem to have bricked my SKR v1.3. On a mac, it registers with no memory, and I cannot upload any firmware on there. Also, the name seems to have been gone when I try to eject/remove the board.

Don't know how to reproduce, just happened while I was trying to upload firmware.

1. Open platformio on Atom
2. Attempt to upload my version of Marlin bugfix-2.0.x
3. Keep doing it until it breaks (that's what it seems like to me)

**Expected behavior:** The firmware is uploaded to the board.

**Actual behavior:** Unable to find or upload data to the board.

#### Additional Information

The computers can still access the boards via something such as Pronterface.

[Config_files.zip](https://github.com/MarlinFirmware/Marlin/files/3607951/Config_files.zip)

**Comment by shitcreek** [comment]
The firmware is loaded onto an SD card for LPC based boards such as the SKR v1.3. Put the `firmware.bin` file created by PlatformIO onto an SD and stick it into the SD slot on the board. Boot it up and the board will flash itself.

**Comment by Epicotch** [comment]
Thanks! I did that and it worked.

**Comment by shitcreek** [comment]
Glad I could help. Cheers.
