### ISSUE TITLE
[BUG] LED Control Menu

### ISSUE THREAD

**Issue by kaisertheone** [MarlinFirmware/Marlin#15261]
It is my first bug on Marlin 2.0 and Github ever.

got a compile error if i use the LED menu.
..\lcd\menu\menu_led row 75 there is something written about a MSG_SET_LEDS_DEFAULT but it was never declared anywehre.

I found it in the leds.h but something seems to not work correctly.
uncommenting the row solved the error.

**Comment by shitcreek** [comment]
`MSG_SET_LEDS_DEFAULT` should be in the language file. Which language are you using?

**Comment by kaisertheone** [comment]
Just the normal english language.

**Comment by shitcreek** [comment]
Which version of Marlin are you using? Check your `language_en.h` file if it's missing `MSG_SET_LEDS_DEFAULT`. I was able to compile the latest Marlin vanilla with `LED_CONTROL_MENU` without any issue.

**Comment by boelle** [comment]
@kaisertheone solved this one?

**Comment by kaisertheone** [comment]
Well i Found a workaround which is ok for me.(just commented the Line)
But the default entry is still not correct in the source.

**Comment by boelle** [comment]
Which version of Marlin are you using?

**Comment by boelle** [comment]
will close this one as it seems @kaisertheone dont have an issue anymore

if you have a fix for the issue please tell in detail

if its simple enough i could make a PR that fixes it
