### ISSUE TITLE
[BUG] Arduino DUE compilation error

### ISSUE THREAD

**Issue by Roman-RV78** [MarlinFirmware/Marlin#15299]
Hello. I get an error while compiling. Marlin 2.0 Bugfix Branch

_arm-none-eabi-gcc: error: CreateProcess: No such file or directory
exit status 1
Error compiling for board Arduino Due (Programming Port)._
[Conf.zip](https://github.com/MarlinFirmware/Marlin/files/3625210/Conf.zip)

On early bug fixes, compilation went through.

**Comment by tvixen** [comment]
Please fill out the Questions in the description!
It only takes a minimum of effort, but will make things a lot easier for everyone

**Comment by Roman-RV78** [comment]
Marlin-bugfix-2.0.x from 08/25/2019 compilation runs fine, today's bugfix also does not compile. Arduino IDE 1.8.10, error:
  arm-none-eabi-gcc: error: CreateProcess: No such file or directory

**Comment by sjasonsmith** [comment]
I think it has to do with some of the command line arguments being too long for Windows. I found references in other issues to it, but didn't happen across an easy solution. I encounter the same issue when I build your configs for DUE from the Arduino IDE.

The good news is that it builds fine in Visual Studio Code using Platform IO. Maybe you should set that up and build from there?

**Comment by ZS1FJK** [comment]
Hello
I also have this issue.
I have a archim 2 board and can only use Arduino to compile my marlin unfortunately. I am using today's bug fix and with Arduino 1.9.0 beta .
@sjasonsmith I found the same post about the arguments being too long for Windows.

**Comment by boelle** [comment]
@Roman-RV78 still having issues when using latest 2.0.x ?

**Comment by boelle** [comment]
@Roman-RV78 think the problem is you are not using ide 1.9 beta

**Comment by Roman-RV78** [comment]
I think the problem is in the Arduino IDE. Today's build also does not compile. In PlatformIO, everything compiles.

**Comment by boelle** [comment]
what version of arduino ide do you use?

**Comment by Roman-RV78** [comment]
1.8.10

**Comment by boelle** [comment]
1.9.0 beta is the recommended version

**Comment by ZS1FJK** [comment]
I have tried 1.9.0 beta and 1.8.10 both don't work for archim same error .

**Comment by boelle** [comment]
also if using vscode+plaform.io ?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
