### ISSUE TITLE
[BUG] Printer printing 13cm above printbed

### ISSUE THREAD

**Issue by Timzoet1** [MarlinFirmware/Marlin#15309]
I have only changed the `ENDSTOP_INVERTING` from `false`  to `true` but when i start printing it prints 13cm above the printbed.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3632412/Configuration.zip)

**Comment by reloxx13** [comment]
more infos needed

**Comment by Timzoet1** [comment]
It is on a ramps in a anet a8 and it homes on the right level

**Comment by Timzoet1** [comment]
I found the problem!!! 
I just had the cables off the motors the wrong way around and I don't know why but for some reason that caused it to print mid air.
