### ISSUE TITLE
Review configuration files default

### ISSUE THREAD

**Issue by alexborro** [MarlinFirmware/Marlin#1531]
Related to issue #1530 , I don't know why some configurations are set to "rare" options.

Temperature sensors 1 and 2 are set by default to "-1". How many reprappers over there use thermocouple?? I think majority use thermistor.. and just one extruder.

MOTHERBOARD is set to ULTIMAKER.. I think it should be set to "RAMPS" or "Unknown".. Some days ago I built a machine and forgot to set the Motherboard and of course the machine behavior was really weird.. my fault, but if the default was "nothing", it will break compilation and makes me set it accordingly. 

DEFAULT_AXIS_STEPS_PER_UNIT set to 78.7402 .. Again for Ultimaker.. This is a really unique value.. I think the most common is 80 steps/mm.. 

And so one..

Cheers.

Alex.

**Comment by thinkyhead** [comment]
@alexborro The Ultimaker defaults are mostly an historical artifact, from contributors with special affinities for Ultimakers. I agree the best default now is some kind of RAMPS or an UNKNOWN setting that will throw an #error. Common defaults also make sense. Helpful documentation about how to get the steps-per-unit values would also be nice. In my own config, I keep a block around that looks like this:

```
// default settings

#define XY_BELT_PITCH 2
#define XY_GEAR_TEETH 20

#define Z_ROD_PITCH 0.8

// NEMA17 with 16 microsteps
#define STEPS_NEMA17 200
#define MICROS_NEMA17 16

// PG with 50:1 ratio, 16 microsteps
#define STEPS_PG50 48
#define MICROS_PG50 16

// A typical Wade's Extruder. Gregstruder: 51/11 or 43/10
#define LG_GEAR_WADE 39
#define SM_GEAR_WADE 11

// Diameter of the drive wheel or hobbed bolt
#define DRIVE_DIAM_WADE 7
#define DRIVE_DIAM_MK7 10.56

// calculated step unit values
#define M_PI 3.14159265
#define STEPS_PER_TURN_NEMA17 (STEPS_NEMA17 * MICROS_NEMA17)
#define STEPS_PER_TURN_PG50 (STEPS_PG50 * MICROS_PG50)
#define GEAR_RATIO_WADE (LG_GEAR_WADE/SM_GEAR_WADE)
#define GEAR_RATIO_PG50 (50/1)
#define DRIVE_CIRC_WADE (DRIVE_DIAM_WADE * M_PI)
#define DRIVE_CIRC_MK7 (DRIVE_DIAM_MK7 * M_PI)

#define STEPS_PER_MM_XY (STEPS_PER_TURN_NEMA17 / (XY_BELT_PITCH * XY_GEAR_TEETH))
#define STEPS_PER_MM_Z  (STEPS_PER_TURN_NEMA17 / Z_ROD_PITCH)

// Some extruder steps-per-mm examples:

// Classic Wade
#define STEPS_PER_MM_WADE_39_11 (STEPS_PER_TURN_NEMA17 * GEAR_RATIO_WADE / DRIVE_CIRC_WADE) // = 515.91048

// MK7 Direct Drive with 50:1 PG motor
#define STEPS_PER_MM_MK7_50_1 (STEPS_PER_TURN_PG50 * GEAR_RATIO_PG50 / DRIVE_CIRC_MK7) // = 1157.49147

// A Wade that I bought, 48:10 (?) with 7mm diameter hobbed bolt
#define STEPS_PER_MM_MYWADE 694.49429712

#define DEFAULT_AXIS_STEPS_PER_UNIT   {STEPS_PER_MM_XY, STEPS_PER_MM_XY, STEPS_PER_MM_Z, STEPS_PER_MM_MK7_50_1}  // Default for Prusa i3 with GT2 belts
```

**Comment by alexborro** [comment]
I think we should review the config files and default set the most used
values.

2015-02-22 14:02 GMT-03:00 Scott Lahteine notifications@github.com:

> @alexborro https://github.com/alexborro The Ultimaker defaults are
> mostly an historical artifact, from contributors with special affinities
> for Ultimakers. I agree the best default now is some kind of RAMPS or an
> UNKNOWN setting that will throw an #error. Common defaults also make sense.
> Helpful documentation about how to get the steps-per-unit values would also
> be helpful. In my own config, I keep a block around that looks like this:
> 
> // default settings
> 
> #define XY_BELT_PITCH 2
> #define XY_GEAR_TEETH 20
> 
> #define Z_ROD_PITCH 0.8
> 
> // NEMA17 with 16 microsteps
> #define STEPS_NEMA17 200
> #define MICROS_NEMA17 16
> 
> // PG with 50:1 ratio, 16 microsteps
> #define STEPS_PG50 48
> #define MICROS_PG50 16
> 
> // A typical Wade's Extruder. Gregstruder: 51/11 or 43/10
> #define LG_GEAR_WADE 39
> #define SM_GEAR_WADE 11
> 
> // Diameter of the drive wheel or hobbed bolt
> #define DRIVE_DIAM_WADE 7
> #define DRIVE_DIAM_MK7 10.56
> 
> // calculated step unit values
> #define M_PI 3.14159265
> #define STEPS_PER_TURN_NEMA17 (STEPS_NEMA17 \* MICROS_NEMA17)
> #define STEPS_PER_TURN_PG50 (STEPS_PG50 \* MICROS_PG50)
> #define GEAR_RATIO_WADE (LG_GEAR_WADE/SM_GEAR_WADE)
> #define GEAR_RATIO_PG50 (50/1)
> #define DRIVE_CIRC_WADE (DRIVE_DIAM_WADE \* M_PI)
> #define DRIVE_CIRC_MK7 (DRIVE_DIAM_MK7 \* M_PI)
> 
> #define STEPS_PER_MM_XY (STEPS_PER_TURN_NEMA17 / (XY_BELT_PITCH \* XY_GEAR_TEETH))
> #define STEPS_PER_MM_Z  (STEPS_PER_TURN_NEMA17 / Z_ROD_PITCH)
> 
> // Some extruder steps-per-mm examples:
> 
> // Classic Wade
> #define STEPS_PER_MM_WADE_39_11 (STEPS_PER_TURN_NEMA17 \* GEAR_RATIO_WADE / DRIVE_CIRC_WADE) // = 515.91048
> 
> // MK7 Direct Drive with 50:1 PG motor
> #define STEPS_PER_MM_MK7_50_1 (STEPS_PER_TURN_PG50 \* GEAR_RATIO_PG50 / DRIVE_CIRC_MK7) // = 1157.49147
> 
> // A Wade that I bought, 48:10 (?) with 7mm diameter hobbed bolt
> #define STEPS_PER_MM_MYWADE 694.49429712
> 
> #define DEFAULT_AXIS_STEPS_PER_UNIT   {STEPS_PER_MM_XY, STEPS_PER_MM_XY, STEPS_PER_MM_Z, STEPS_PER_MM_MK7_50_1}  // Default for Prusa i3 with GT2 belts
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1531#issuecomment-75445069
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by thinkyhead** [comment]
Probably something like a vanilla Mendel i2 or i3.

**Comment by alexborro** [comment]
Ok, let's start our guesses.

For cartesians:
DEFAULT_AXIS_STEPS_PER_UNIT   {80,80,4000,500}
This is the most common in my country (GT2 belts, 20t pulley, 1.8º motors
and 0.8mm pitch screw for Z axis).

DEFAULT_MAX_FEEDRATE          {250, 150, 3.5, 25}
This is the values I usually get on Prusas i3.

DEFAULT_MAX_ACCELERATION      {3000,3000,100,10000}
I think the original one (9000 mm/s^2) is too aggressive with no major
benefits.

#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_BED 1
Again, most common config I see around my friends.

2015-02-22 15:47 GMT-03:00 Scott Lahteine notifications@github.com:

> Probably something like a vanilla Mendel i2 or i3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1531#issuecomment-75450575
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by thinkyhead** [comment]
Looks good, almost exactly my own settings. My default E Steps for an i3 with a Wade extruder and NEMA 17 with 16x micro-stepping is around 695. For my 2engineers PG 50:1 motor (16x) with MK7 drive gear, steps are around 1258. We might list a few common values for XY, Z, and E in the comments section.

As for Max Acceleration, that value has always been a little confusing to me, at least the E value. Whether 10,000 or 9,000 isn't it basically saying "no acceleration"? Or, is there a nuance here I'm missing? How does it interact with the low Jerk setting?

The Temp Sensors are right on. Exactly what most of us have. Thermocouples are far more rare.

**Comment by thinkyhead** [comment]
```
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_RAMPS_13_EFB
#endif
```

…and…

```
#define DISABLE_MAX_ENDSTOPS
```

…and, Thermal Runaway Protection on by default…?

**Comment by thinkyhead** [comment]
Might elaborate on the endstop switch values... Do I have this backwards? Can it be reversed due to the electronics?

```
const bool X_MIN_ENDSTOP_INVERTING = true; // NC Switch = false, NO switch = true
```

**Comment by nophead** [comment]
The default should be DISABLE_MAX_ENDSTOPS and X_MIN_ENDSTOP_INVERTING =
false as that is the most common usage.

It could be reversed electronically but I don't know of any boards that do
that. It is simply for people that wire their switches the wrong way I
think.

**Comment by thinkyhead** [comment]
@nophead Well I mainly want to determine if it's correct that **false** will always correspond to Normally Closed (NC) and **true** will always correspond to Normally Open (NO) since the comment there is pretty vague, and AFAIK these are the only two classes of endstop. I understand that electronics could use a closed switch to "pull the signal low" but yeah it must be simpler and cheaper to let the switches be open=low, closed=high...

**Comment by TheRogueZeta** [comment]
NC to ground is normally recommended as is keeps both sides at ground
potential during printing.  I've seen local user who had prints randomly
stop mid-way through prints when they had switches connected as NO. At our
meeting we swapped them around and uploaded the inverted code and it worked
perfectly.

-Jon

**Comment by thinkyhead** [comment]
@ZetaPhoenix I'm a big fan of the NC switch, myself, because Induced current doesn't affect them. But can you define "swapped them around"? Do you mean that the endstop plug was just flipped over, or that the NO switches were replaced with NC switches? If the same switches were used, but in a different "mode" then I guess we can leave the comments as they are.

**Comment by TheRogueZeta** [comment]
We swapped contacts on the mechanical switches and used the NC contact from
the NO contact and inverted the logic in marlin to handle the change.

-Jon

**Comment by thinkyhead** [comment]
@ZetaPhoenix Great, thanks!

**Comment by nophead** [comment]
Some people use optos instead of switches. In that case NC is the most
common but you can get optos with inverted outputs.

NC is preferred because it fails safe if it gets disconnected. It is more
immune to noise but not totally as current can be induced in the loop of
wire giving a voltage at the receiving end despite the switch end being
shorted. It is more immune to capacitively coupled noise but less immune to
inductively coupled noise.

**Comment by ntoff** [comment]
> Helpful documentation about how to get the steps-per-unit values would also be nice. 

Put a link to this in the documentation http://www.prusaprinters.org/calculator/

Maybe if we all upload our configs to pastebin or something but here's what I use on my mendel90

```
#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_BED 1

#define HEATER_0_MAXTEMP 260 *because my hot end is peek*

#define DEFAULT_AXIS_STEPS_PER_UNIT   {80,80,2560,83}  // Mendel90 1/16th microstepping - GT2 belts w/20 tooth pulley, M8x1.25 Z rods,  direct drive extruder 1:1 gearing
#define DEFAULT_MAX_FEEDRATE          {500, 300, 4, 25}    
#define DEFAULT_MAX_ACCELERATION      {5000,5000,25,10000}    

#define DEFAULT_ACCELERATION          2000    

#define DEFAULT_XYJERK                20.0
```

edit Oh and

> …and, Thermal Runaway Protection on by default…?

Not without documentation on it. The default values would see my K8200 claim thermal runaways all over the place because the heated bed was never able to maintain temperature up in the 90's and above. For the hot end, yes maybe have that on by default but the bed off by default since maybe not everyone even has a heated bed.

**Comment by boelle** [comment]
This is again one where i think why not have a web config tool that gives you a config file based on what machine you pick and settings etc

**Comment by thinkyhead** [comment]
@boelle We can pick up that info from the example_configurations (loading those configs into the web tool) or I can add a bunch of smaller files that only contain the customized settings and merge them into the base config, producing full configuration files for download. The customized settings can be in the form of #defines or in JSON, or just typical INI style...

**Comment by boelle** [comment]
:-D me ready to test in about 4 weeks or less.... my bootloader programmer is shot :-/

**Comment by thinkyhead** [comment]
I think a recent merge made the default MOTHERBOARD value BOARD_RAMPS_13, which is not defined. I'll make a tweak to address that issue, plus some others, to fix up default configs soon.

**Comment by boelle** [comment]
can this one be closed? did we not agree that ramps should be the default... and if not remebering wrong we also agreed that we would drop having default config unless they are providede by makers of hardware?

**Comment by Wackerbarth** [comment]
Two comments on this:

1) "they are provided by makers of hardware" -- Requiring a Custodian for each configuration is reasonable. However, that need not, and for orphan hardware cannot, be the maker. The project should assist the community in supporting any hardware configurations for which there is community support.

2) I suggest that there be NO default configuration. The first step in preparing to build the firmware would be to run a configurator or copy an example configuration into the "active position". (As a future enhancement, perhaps this mechanism can be refined into a menu selection, or other mechanism)
However, in the present methodology, there is a bias that makes ALL of the configuration files too complex and complicates maintaining the non-default configurations.

The issue of which cases to test in the Travis CI tests is not at issue. In fact, testing the current "default"
becomes cleaner because it now becomes just the same as any other.

**Comment by dantman** [comment]
Commenting on @Wackerbarth's 2). Defaulting to 'nothing' for things that aren't 98% ubiquitous does sound like a good idea.

**Especially** if we can make the Arduino compiler output display errors saying what setting (eg: MOTHERBOARD) needs configuration (even better, where to find it; but maybe that's tricky) or explaining why Marlin can't work reasonably without it.

**Comment by thinkyhead** [comment]
As a developer and tinkerer generally I'm a fan of being able to compile Marlin "out of the box" even if it's not for my specific printer. Makes it a lot easier to develop.

**Comment by Roxy-3D** [comment]
Agreed.   It should compile and run on the default configuration straight from the download.
