### ISSUE TITLE
[BUG] Compiling error

### ISSUE THREAD

**Issue by npmomchev** [MarlinFirmware/Marlin#15322]
### Description

if you allow "#define G29_RETRY_AND_RECOVER" and "#define HOST_PROMPT_SUPPORT" at the same time, compiling failed with error: 
Marlin\src\Marlin.cpp: In function 'void event_probe_recover()':
Marlin\src\Marlin.cpp:417:22: error: 'PROMPT_INFO' was not declared in this scope
       host_prompt_do(PROMPT_INFO, PSTR("G29 Retrying"));
### Steps to Reproduce

1. [Enable: #define G29_RETRY_AND_RECOVER]
2. [Enable: #define HOST_PROMPT_SUPPORT]
3. [Compiling...]

![Error](https://user-images.githubusercontent.com/32423200/65367088-f185d200-dc34-11e9-8e0f-660458211142.png)
![error2](https://user-images.githubusercontent.com/32423200/65367090-f480c280-dc34-11e9-8500-bbdb94cb512c.png)

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3638249/Marlin.zip)

**Comment by sjasonsmith** [comment]
PROMPT_INFO was removed a couple weeks ago. This line of code was probably supposed to be deleted.

**Comment by boelle** [comment]
@npmomchev tried with latest copy of 2.0.x ?

**Comment by boelle** [comment]
will close this one as it seems @npmomchev dont have an issue anymore

we can always reopen if its not the vase
