### ISSUE TITLE
Volumetric multiplier not updated using filament LCD menu

### ISSUE THREAD

**Issue by clefranc** [MarlinFirmware/Marlin#1532]
When the filament diameter is modified using the filament LCD menu, the volumetric multiplier is not updated.

ultralcd.cpp line 1041:

MENU_MULTIPLIER_ITEM_EDIT_CALLBACK(float43, MSG_FILAMENT_SIZE_EXTRUDER_0, &filament_size[0], 1.5, 3.25, calculate_volumetric_multipliers);

The calculate_volumetric_multipliers above is not executed?

The volumetric multiplier will be updated with the new filament diameter only if the volumetric extrusion is switched off/on or with a M200 command.

I've made this PR to show the behavior: https://github.com/MarlinFirmware/Marlin/pull/1524

**Comment by thinkyhead** [comment]
The part that is supposed to execute, but apparently doesn't for some reason, is this...

```
void menu_edit_callback_float43() {
  menu_edit_float43();
  if (LCD_CLICKED) (*callbackFunc)();
}
```

That code is supposed to be called through the expansion of `menu_edit_type(float, float43, ftostr43, 1000)`, which in turn should call into the utility function...

```
static void menu_action_setting_edit_callback_float43(const char* pstr, float* ptr, float minValue, float maxValue, menuFunc_t callback) {
  _menu_action_setting_edit_float43(pstr, ptr, minValue, maxValue);
  currentMenu = menu_edit_callback_float43;
  callbackFunc = callback;
}
```

And the menu item initialization looks okay also...

```
MENU_MULTIPLIER_ITEM_EDIT_CALLBACK(float43, MSG_FILAMENT_SIZE_EXTRUDER_0, &filament_size[0], 1.5, 3.25, calculate_volumetric_multipliers);
```

Definitely a conundrum to try to narrow down this issue.
