### ISSUE TITLE
None of the callback menu functions are executed

### ISSUE THREAD

**Issue by clefranc** [MarlinFirmware/Marlin#1533]
None of the callback menu functions are executed, exception of BOOL.

This affects:
lcd_control_temperature_menu
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L912
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L913
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L924
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L925
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L936
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L937
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L948
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L949

lcd_control_motion_menu
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L1014
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L1015
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L1016
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L1017

lcd_control_volumetric_menu
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L1041
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L1043
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L1045
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L1047

Originally discovered with https://github.com/MarlinFirmware/Marlin/issues/1532

**Comment by thinkyhead** [comment]
Haha! Well things are beginning to make more sense. One question might help me clear it up... the LCD_CLICKED macro.... It should be callable more than once in a loop, but does reading the clicked bit from the controller also clear it??

Meanwhile I'll look closer and see why BOOL is the only one that works...

**Comment by thinkyhead** [comment]
This issue probably still exists with these updates, but it's worth a try...
https://github.com/MarlinFirmware/Marlin/pull/1526/files

I will play around with this more when I get back to my workshop and can flash my board.

**Comment by clefranc** [comment]
I'll finally can go forward with the multiple filament PR, this nasty behavior was unexpected.

**Comment by clefranc** [comment]
The LCD_CLICKED in the BOOL callback function is called only once.

**Comment by thinkyhead** [comment]
This rotary encoder code implies that the button bit is persistent - we should be able to use LCD_CLICKED more than once. And in fact, I have used update menu code that calls it twice (for callback menu items) without any issue. So I'm looking closer at the logic, and at the most recent commits to see which might be involved. So far, nothing sticks out!

https://github.com/0xPIT/encoder/blob/arduino/ClickEncoder.cpp

**Comment by thinkyhead** [comment]
Well, BOOL is the only one of the callback functions that isn't defined via the `menu_edit_type` macro. So, perhaps this is the source of the issue. Perhaps try this, replace the `menu_edit_callback_ ## name` macro with these lines and see if it works...

```
bool _menu_edit_ ## _name () { \
  bool isClicked = LCD_CLICKED; \
  if ((int32_t)encoderPosition < 0) encoderPosition = 0; \
  if ((int32_t)encoderPosition > maxEditValue) encoderPosition = maxEditValue; \
  if (lcdDrawUpdate) \
      lcd_implementation_drawedit(editLabel, _strFunc(((_type)((int32_t)encoderPosition + minEditValue)) / scale)); \
  if (isClicked) { \
    *((_type*)editValue) = ((_type)((int32_t)encoderPosition + minEditValue)) / scale; \
    lcd_goto_menu(prevMenu, prevEncoderPosition); \
  } \
  return isClicked; \
} \
void menu_edit_ ## _name () { _menu_edit_ ## _name(); } \
void menu_edit_callback_ ## _name () { if (_menu_edit_ ## _name ()) (*callbackFunc)(); } \
 ...
```

**Comment by thinkyhead** [comment]
Ah, I see you are ahead of me!
