### ISSUE TITLE
[BUG] SKR 1.3 TMC Connection Error after restarting printing

### ISSUE THREAD

**Issue by tobyworks** [MarlinFirmware/Marlin#15336]
### Description

When first uploading marlin to printer i can use tmc 2209 fine. After reboot or reset the printers shows a TMC connection error and sensorless homing will not work anymore.

**Comment by shitcreek** [comment]
Please follow the template and provide more information such as your configuration files. But before you do, have you searched through the issues posted here to see if there isn't already a thread opened for this one? For example, could this issue be related to #15012 ?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
