### ISSUE TITLE
[FR] Standard protocol for communication with "smart" displays

### ISSUE THREAD

**Issue by extesy** [MarlinFirmware/Marlin#15348]
Some 3d printer manufacturers (Wanhao, Creality, etc) use "smart" colored touch screens which are capable of showing real-time print information such as temperature, time estimates, etc. They use modified Marlin for that and don't release their source code so nobody can reproduce the same functionality with other displays or motherboards.

So I'd like to request Marlin dev team to come up with some kind of a standard communication protocol with such display panels and let all Marlin users enjoy their beautiful displays and not have to fall back to ugly LCD12864 mode.

**Comment by jorgeassuncao** [comment]
+1 for that!

**Comment by vMeph** [comment]
this would be awesome !!!

**Comment by grego1981** [comment]
+1 from me!!

**Comment by extesy** [comment]
Looks like there's still demand, please don't close the ticket.

**Comment by sjasonsmith** [comment]
@InsanityAutomation isn't this what ExtUI is for? Is there actually anything actionable here, or is it done?

**Comment by InsanityAutomation** [comment]
@sjasonsmith pretty much, but a standardized protocol as mentioned is impossible as every screen needs a different protocol. ExtUI is as close as this is going to get.
