### ISSUE TITLE
[QUESTION] how to know if homing was done ?

### ISSUE THREAD

**Issue by spilz87** [MarlinFirmware/Marlin#15350]
Hello,

I’m looking for a gcode that can tell me if M114 returned values are “good”.
I mean if homing has been done before. 
It’s same kind of information than when “???” Blink or not on XYZ value on screen but through gcode 

Does it exist ?

Thanks for your help

**Comment by asko58** [comment]
You could issue a 'G28 O', if the position is known it will just do nothing, otherwise it will home.

**Comment by spilz87** [comment]
Thanks for your reply
But it’s to monitor a printer, so I don’t want to run a home, just get information :(

**Comment by boelle** [comment]
i think its better to ask on discord

-Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by han9988** [comment]
You could check the state of your endstops with M119. For example:

Sucessful homing:
 x_min: TRIGGERED
y_min: TRIGGERED
z_min: TRIGGERED

Ooopsy - something went wrong:
x_min: TRIGGERED
y_min: open
z_min: TRIGGERED

**Comment by boelle** [comment]
better ask here: 

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

the list is for bugs and fr's only
