### ISSUE TITLE
[BUG] ?? SKR PRO NEOPIXEL WRONG COLOURS

### ISSUE THREAD

**Issue by SISLANGER** [MarlinFirmware/Marlin#15355]
### Description

#define NEOPIXEL_TYPE   NEO_GRB works on SKR V1.3
 but wrong colours on SKR PRO V1.1

**Expected behavior:** 
Correct Colour

**Actual behavior:** [What actually happens]
Startup is wrong 

Colours at moment
Red produces green
Green produces blue
Blue produces red

**Comment by boelle** [comment]
wires connected correct on SKR PRO V1.1?

**Comment by SISLANGER** [comment]
Yeah signal to signal 
gnd to gnd

gnd & 5V off buck convertor

**Comment by SISLANGER** [comment]
also now will no longer light more than 2 - 4 neopixels despite 77 set

**Comment by extesy** [comment]
@SISLANGER I think you should ask @bigtreetech in https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/issues/ first before involving Marlin.

**Comment by boelle** [comment]
i would agree, if its a hardware issue then seek help from the maker of hardware :-)

**Comment by SISLANGER** [comment]
If it has been implemented into Marlin then it would be seen by author of that coding. Well at least that is my take on it. Sadly I can't just message them. I don't believe it to be hardware. Seems more of a timing issue with neopixel. Or perhaps Marlin 2 not updating firmware with the SKR Pro V1.1 like I experienced with SKR V1.3

If you wish to close the case then that is up to you as I know how busy you all get.

**Comment by sjasonsmith** [comment]
@SISLANGER, can you provide a minimal config that can reproduce the problem, that I can load and use on a board with nothing else connected?

I don't have a NeoPixel yet, but I'm expecting one next Wednesday. I could try to reproduce the issue. I would need the config and exact steps to reproduce (I've never used LEDs on my printers before).

**Comment by Promite2501** [comment]
Are you running a split ground to both the skr and buck converter?

**Comment by SISLANGER** [comment]
@sjasonsmith 

In simplest form
```cpp
// Support for Adafruit Neopixel LED driver
#define NEOPIXEL_LED
#if ENABLED(NEOPIXEL_LED)
  #define NEOPIXEL_TYPE    NEO_GRB // NEO_GRBW / NEO_GRB - four/three channel driver type (defined in Adafruit_NeoPixel.h)
  #define NEOPIXEL_PIN     PC9 //PB0 //PC9 // PE6 // LED driving pin
  //#define NEOPIXEL2_TYPE NEOPIXEL_TYPE
  //#define NEOPIXEL2_PIN    5
  #define NEOPIXEL_PIXELS 77 //77       // Number of LEDs in the strip, larger of 2 strips if 2 neopixel strips are used
  //#define NEOPIXEL_IS_SEQUENTIAL   // Sequential display for temperature change - LED by LED. Disable to change all LEDs at once.
  #define NEOPIXEL_BRIGHTNESS 255  // Initial brightness (0-255)
  #define NEOPIXEL_STARTUP_TEST  // Cycle through colors at startup

  // Use a single Neopixel LED for static (background) lighting
  //#define NEOPIXEL_BKGD_LED_INDEX  0               // Index of the LED to use
  //#define NEOPIXEL_BKGD_COLOR { 255, 255, 255, 0 } // R, G, B, W
#endif

#if ANY(BLINKM, RGB_LED, RGBW_LED, PCA9632, PCA9533, NEOPIXEL_LED)
  #define PRINTER_EVENT_LEDS
#endif


#define NUM_SERVOS 1 // Servo index starts with 0 for M280 command
#define SERVO_DELAY {300}
```

**Comment by SISLANGER** [comment]
@Promite2501 I have ground from PSU and signal meeting together soldered to lights together, same as always.

**Comment by Evg33** [comment]
@SISLANGER Play with #define NEOPIXEL_TYPE NEO_GRB 
May be NEO_RBG ?
Other Varants:
NEO_RGB
NEO_GRB
NEO_GBR
NEO_BRG
NEO_BGR

**Comment by sjasonsmith** [comment]
I just set up an authentic 12-pixel Adafruit NeoPixel RGB ring (model 1643) on an SKR Pro 1.1, and the colors are fine. I see the startup sequence at boot, then I manually tested colors using the M150 command.

I used the same pin from the settings @SISLANGER posted.
Here are all the enabled settings in my NeoPixel section:

```
// Support for Adafruit Neopixel LED driver
#define NEOPIXEL_LED
#if ENABLED(NEOPIXEL_LED)
  #define NEOPIXEL_TYPE   NEO_GRB
  #define NEOPIXEL_PIN     PC9
  #define NEOPIXEL_PIXELS 12
  #define NEOPIXEL_IS_SEQUENTIAL
  #define NEOPIXEL_BRIGHTNESS 127  // Initial brightness (0-255)
  #define NEOPIXEL_STARTUP_TEST  // Cycle through colors at startup
#endif
```

Here are my configs if you want to compare. This a nearly completely clean config, just essential board and NeoPixel settings modified.
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/3684323/Configs.zip)

This was built on the latest Oct 2nd bugfix, commit b82c0978cc38f429377af25d64a57408b802cd99. The Neopixel library is version 1.2.5.

**Comment by Evg33** [comment]
I have no problems with colors.
tested colors using the M150.
```
  #define NEOPIXEL_TYPE   NEO_GRB 
  #define NEOPIXEL_PIN     PE4       // LED driving pin strips are used
  #define NEOPIXEL_PIXELS 10       // Number of LEDs in the strip, larger of 2 strips if 2 neopixel strips are used
  #define NEOPIXEL_IS_SEQUENTIAL   // Sequential display for temperature change - LED by LED. Disable to change all LEDs at once.
  #define NEOPIXEL_BRIGHTNESS 127  // Initial brightness (0-255)
  #define NEOPIXEL_STARTUP_TEST  // Cycle through colors at startup

```

**Comment by SISLANGER** [comment]
> @SISLANGER Play with #define NEOPIXEL_TYPE NEO_GRB
> May be NEO_RBG ?
> Other Varants:
> NEO_RGB
> NEO_GRB
> NEO_GBR
> NEO_BRG
> NEO_BGR

Yeah I have tried those, and I have the colour working correctly but only a few LEDS

**Comment by SISLANGER** [comment]
> I just set up an authentic 12-pixel Adafruit NeoPixel RGB ring (model 1643) on an SKR Pro 1.1, and the colors are fine. I see the startup sequence at boot, then I manually tested colors using the M150 command.
> 
> I used the same pin from the settings @SISLANGER posted.
> Here are all the enabled settings in my NeoPixel section:
> 
> ```
> // Support for Adafruit Neopixel LED driver
> #define NEOPIXEL_LED
> #if ENABLED(NEOPIXEL_LED)
>   #define NEOPIXEL_TYPE   NEO_GRB
>   #define NEOPIXEL_PIN     PC9
>   #define NEOPIXEL_PIXELS 12
>   #define NEOPIXEL_IS_SEQUENTIAL
>   #define NEOPIXEL_BRIGHTNESS 127  // Initial brightness (0-255)
>   #define NEOPIXEL_STARTUP_TEST  // Cycle through colors at startup
> #endif
> ```
> 
> Here are my configs if you want to compare. This a nearly completely clean config, just essential board and NeoPixel settings modified.
> [Configs.zip](https://github.com/MarlinFirmware/Marlin/files/3684323/Configs.zip)
> 
> This was built on the latest Oct 2nd bugfix, commit [b82c097](https://github.com/MarlinFirmware/Marlin/commit/b82c0978cc38f429377af25d64a57408b802cd99). The Neopixel library is version 1.2.5.

I will give yesterdays update a try, and check neopixel version. Thank you

**Comment by Evg33** [comment]
@SISLANGER 
> Yeah I have tried those, and I have the colour working correctly but only a few LEDS

Can you show the photo of strip with M150 commands ?
Maybe you have 4 color strip ? (NEO_RGBW...)

**Comment by boelle** [comment]
@SISLANGER

Can you show the photo of strip with M150 commands ?
Maybe you have 4 color strip ? (NEO_RGBW...)

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
