### ISSUE TITLE
[BUG] MARLIN DOESN'T COMPILE WITH (BL)3DTOUCH-M851 ISSUE

### ISSUE THREAD

**Issue by akedziora96** [MarlinFirmware/Marlin#15364]
![error](https://user-images.githubusercontent.com/55790752/65602632-7b6ecb80-dfa4-11e9-91fc-ad34861678be.png)
 
It doesn't work with M851.cpp new fix (25.09.19). Any idea how to fix it ?

**Comment by Bergerac56** [comment]
I confirm this issue

This is not related to BL touch. I have the same issue with another type of Z Probe

**Comment by reloxx13** [comment]
link fix https://github.com/MarlinFirmware/Marlin/commit/b4ea1875bf6cc24fe4cd47967342d87116f329b3

**Comment by akedziora96** [comment]
![2019-09-25](https://user-images.githubusercontent.com/55790752/65610953-67ca6180-dfb2-11e9-9b0f-3764805659d5.png)

Still doesn't work :( I changed 44th comand line, saved and rebuilded with C, after all i have the same issue.

**Comment by sl1pkn07** [comment]
works for me (3dtouch from trianglelab)

**Comment by akedziora96** [comment]
For me too.

Wysłane z iPhone'a
