### ISSUE TITLE
"test multiline" should not be in ultralcd.cpp as default

### ISSUE THREAD

**Issue by kreidler** [MarlinFirmware/Marlin#1536]
Line 379 of ultralcd.cpp contains

/_JFR TEST_/      MENU_ITEM(gcode, "test multiline", PSTR("G4 S3\nM104 S50\nG4 S1\nM104 S200\nG4 S2\nM104 S0"));  // SD-card changed by user

which leds to an extruder heating process if selected. Should be not avialable in this live version.

**Comment by avluis** [comment]
Yep, agree.
Does Arduino have compile time arguments such as debug and release?
Would be a good way of keeping items out of compilation when building the hex binary.

**Comment by avluis** [comment]
Related:
https://github.com/MarlinFirmware/Marlin/issues/1530
https://github.com/MarlinFirmware/Marlin/issues/1531

**Comment by thinkyhead** [comment]
I have a PR pending that fixes this and other outstanding issues. I'll merge it forthwith. #1526
