### ISSUE TITLE
[BUG] Erratic Servo Deployed Z-Probe Operation  

### ISSUE THREAD

**Issue by Reywas62** [MarlinFirmware/Marlin#15370]
### Description

Probe deploys/retracts unexpectedly during probing sequence.  No heaters or fans active.  SKR V1.3.  I have been able to reproduce the behavior easily using M48 E, never got more than 5 probing cycles before erratic retract occurred and probing failed.   I do not see this issue with a previous pull dated 6//22/19.  Tested numerous times to confirm.       

### Steps to Reproduce

1. Run M48 E

**Expected behavior:** Probe should only move when commanded to do so.

**Actual behavior:** Probe deploys/retracts unexpectedly and erratically.

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Reywas62** [comment]
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/3653651/Configuration_adv.zip)
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3653652/Configuration.zip)

**Comment by shitcreek** [comment]
Just tested M48 E with a BLTouch without any issue. Probed ten times and returned deviation amount. Did you homed before issuing M48? Did you have any issue with G29?

**Comment by Reywas62** [comment]
The issue isn't specifically with M48. The problem occurs sporadically whenever the probe is deployed.  M48 E was just an easy way to activate the probe multiple times without having to do it manually.  As stated above, the issue does not occur with an earlier version of bugfix.

**Comment by boelle** [comment]
what version of bugfix do you use? 1.1.x or 2.0.x ?
where do you download from? please give direct link to page

**Comment by Reywas62** [comment]
bugfix-2.0.x downloaded from http://marlinfw.org/docs/basics/install.html

**Comment by boelle** [comment]
what kind of probe?

**Comment by boelle** [comment]
do you have 

//#define DEACTIVATE_SERVOS_AFTER_MOVE

or

#define DEACTIVATE_SERVOS_AFTER_MOVE

?

**Comment by Reywas62** [comment]
Servo Deployed Z-probe, old-school.  Uses a Tower Pro SG90 micro-servo and a micro-switch.
#define DEACTIVATE_SERVOS_AFTER_MOVE

**Comment by boelle** [comment]
then there are only 2 options left

either bad hardware or a fault in marlin, 

are the wires and connections good? crimped connections and not soldered? what voltage do the servo get? can it get enough juice?

**Comment by Reywas62** [comment]
As I said in the original post, the hardware works fine with an earlier version of bugfix (pulled on 6/22/19).

**Comment by boelle** [comment]
do you know the precise date it stopped working?

**Comment by Reywas62** [comment]
If you mean what pull-date it stopped working then no.  It is still working with the 6/22/19 pull.  When I have the time I plan on trying to figure out the specific pull date that it stopped working.

**Comment by boelle** [comment]
that would help the coders a great deal :-D

**Comment by boelle** [comment]
figured out the pull date?

**Comment by boelle** [comment]
closing this one until we have the pull date

we can reopen when we have the date  as that is important, without it we cant narrow it down
