### ISSUE TITLE
[BUG] Menu not available during printing

### ISSUE THREAD

**Issue by hapklaar** [MarlinFirmware/Marlin#15385]
### Description

When I press the knob on the RepRapDiscount Smart Controller during printing, I get a blank screen which can't be exited. It will automatically return to status screen after a while. Accessing the menu works fine when there is no print in progress

### Steps to Reproduce

1. Start print through Octoprint or from SD
2. Press menu knob on panel
3. behold blank LCD screen

**Expected behavior:** Show menu

**Actual behavior:** Blank LCD screen

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3659826/Configuration.zip)

- Anycubic Kossel Plus
- SKR 1.3 Board
- X/Y/Z/E0 = TMC2130 /w software SPI
- latest bugfix 2.0 code used

**Comment by hapklaar** [comment]
Seems I'm hit by the same issue as in #15045

Will try the fix mentioned there by setting BLOCK_BUFFER_SIZE to 64 and report back.

**Comment by hapklaar** [comment]
Yup, that fixed it. Might be something that can be tied to 32 bit board types.

**Comment by tpruvot** [comment]
was 16 so.. did you try with 32 ?

**Comment by hapklaar** [comment]
No, someone did try that however but wasn't successful (https://github.com/MarlinFirmware/Marlin/issues/12461#issuecomment-525027829)

I went to 64 immediately as I saw no downside to it.

**Comment by hapklaar** [comment]
Why is this closed, it's obviously not the same issue as in #15414 as this fix didn't work there

**Comment by shitcreek** [comment]
You said changing the buffer to 64 fixed your issue. The other issue is still open.
