### ISSUE TITLE
[BUG] Writing G29 mesh offset gives incorrect results

### ISSUE THREAD

**Issue by Bernie-X** [MarlinFirmware/Marlin#15381]
### Description

I am getting incorrect mesh data after I write a mesh z offset to a particular grid point.

### Steps to Reproduce

1. Home, bilinear probe, and receive report

- G28 G29

2. Want to change mesh data for grid point I2 J0 from -1.521 to -1.501

- G29 W1 I2 J0 Z.02 

3. Get new report

- M420 V

**Expected behavior:**

I would expect I2 J0 to be -1.501

**Actual behavior:**

I2 J0 is -.876 (or thereabout)

#### Additional Information

Using bugfix-1.1.9

**Comment by shitcreek** [comment]
You need to follow the template and provide your configuration files.
Marlin 1.x isn't worked on anymore, please try Marlin 2.0 and report if issue persists.

**Comment by thinkyhead** [comment]
The code of `G29 W` in 1.1.9 looks okay to me. It's quite simple. I think you might be seeing a spurious glitch in the matrix.

**Comment by Bernie-X** [comment]
Thanks all for your insight.  I figured out that I need to factor my home offset in calculating the desired mesh offset.  Hence, Mesh offset = Home offset<sub>z</sub> + Mesh<sub>desired ij</sub>
