### ISSUE TITLE
[FR] Four Z Axis Motorized ABL, G34

### ISSUE THREAD

**Issue by gmedlicott** [MarlinFirmware/Marlin#15392]
Feature request for four Z axis motorized ABL support to G34 command (G34 currently supports three motorized Z axis, #11302).

Used for moving gantry printers, where the XY plane is somewhat flexible, and four points are required to define the plane.  Eg. Voron 2, ExoCube, DIY etc.  

RepRapFirmware has this feature.

**Comment by InsanityAutomation** [comment]
Ive thought about this one in the past too. Limit really comes down to not many boards with enough drivers to do everything I want! lol I think this one will get done, but likely not before 2.0. Maybe a 2.1 milestone tag?

**Comment by alieneila** [comment]
Now that Quad Z is in, I'd like to bump this =D

**Comment by InsanityAutomation** [comment]
See open PR :)
