### ISSUE TITLE
[BUG] 3Dtouch Randomly deploys during grid leveling process and homing

### ISSUE THREAD

**Issue by Raymo99** [MarlinFirmware/Marlin#15412]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3665936/Marlin.zip)

### Description
3Dtouch clone probe randomly deploys during bed homing.  

### Steps to Reproduce
Using Marlin bugfix 1.1.x
Creality Ender 5 with standard board 
3Dtouch probe

**Expected behavior:**
I expect the probe should only deploy once per test point in the 3x3 grid

**Actual behavior:**
The probe randomly deploys then pops back up, 
It doesn't affect the leveling process, but seems like a bug.

#### Additional Information

Video of the behavior below and my config.h and adv.h are attached

https://photos.google.com/photo/AF1QipO5HW8eOeUfogYo-r5g-kSWnpskVKOJgF-tiHSY

also at:
https://youtu.be/MFussZalNMs

happy to do any further testing as needed.

Ray

**Comment by Raymo99** [comment]
added better video link

**Comment by shitcreek** [comment]
Marlin 1.x is no longer worked on. Please try Marlin 2.x and report back if issue persist. Also, please be certain it is not a faulty device and not a configuration issue.

Quick glance of your configuration.h shows that the 'BLTOUCH_DELAY' is set to 75. Try increasing it to 300 or 500.

**Comment by Raymo99** [comment]
sorry for the reply replying, it took me a while to figure out some issues while flashing 2.0, but its on there now.

Sadly the false deploy issue is still present.

The delay is Bltouch 500 as pre-defined in adv.h

What delayed me was not knowing that Define servo0_pin was implemented in  the pins creality file, but I got there eventually, you see I'm using pin 29 instead of pin 27...

**Comment by shitcreek** [comment]
That's good. Are you all set now? If so, please close the thread. Thanks.

**Comment by Raymo99** [comment]
Sorry, I may not have been clear enough... the problem is still present.
I still get false deploys of the probe.
Increased the delay to 1000, but the problem remains.

**Comment by shitcreek** [comment]
What about increasing `DELAY_BEFORE_PROBING`?

**Comment by Raymo99** [comment]
Good idea, but it still happens.
I used the default 200.

**Comment by Raymo99** [comment]
I'm going to put an oscilloscope on the control line for the Bltouch and see what is actually happening.
I hope it reveal something, more to follow...

**Comment by boelle** [comment]
@Raymo99 what did the scope say?

**Comment by Aurawin** [comment]
As I mentioned in a prior thread - I have this problem too.  I took my existing wires from the V3 blt and replaced my BLT with a clone.  (So it's not a wiring problem).

I already tried increasing the delay time - this does not help. The touch pin would still bounce inconsistently.  

I have worked around this issue by increasing the acceleration and feedrate of my z-axis.  I use the fast mode.  I have to say my probe repeatability is much more reliable with the clone.  I could never have done this with my authentic BLT V3

It was worth the trouble for the workaround.  I probe z-dual-axis and 6 point bi-linear on each print with single shot (extra probe disabled).  Now my startup times are minuscule.

My touch pin still lowers between probes when it should be raised as the probe moves from point to point.  But it's irrelevant because my bed is already out of the way by the time gravity takes effect.  lol.

**Comment by Raymo99** [comment]
Hi Bo,
Sorry, I didn't get around to putting a scope in it yet. But since you ask tben I will and provide results. 

It will be a few days be6i can get to do it.

Cheers 
Ray

**Comment by boelle** [comment]
@Raymo99 had time to play with the scope?

**Comment by Aurawin** [comment]
> @Raymo99 had time to play with the scope?

I recently disabled my BLT FAST probing.  And since doing that my probe is 100% keeping the pin up during all probing moves.

**Comment by boelle** [comment]
@Raymo99 maybe try what @Aurawin did and see if that makes it tick :-)

**Comment by Raymo99** [comment]
Yes I will.
Sorry but I've been tied up with another project and have not revisited this issue. You know how it goes, new projects are so much more appealing than older ones.
I will see if disabling BLT Fast has any effect, otherwise I'll make scope recordings of the control line on video.

**Comment by Raymo99** [comment]
It turns out I'm not using define BLTOUCH_HS_MODE or aka Fast.
so next step is to probe with a scope.

**Comment by Raymo99** [comment]
Ok folks, scope testing is completed.
There are no command line pulses which match the erratic drop's.
Conclusion is a bad clone BLT.

Case closed, not a bug in Marlin.

Thanks for the support.
