### ISSUE TITLE
[BUG] (Compilation error when including Servo Z Probe - Board SKRV1.3 )

### ISSUE THREAD

**Issue by himanshu0192** [MarlinFirmware/Marlin#15429]
Hi,
I am getting a compilation error while building the latest marlin firmware dated 28/08/2019. 
The issue comes when I enable 
#define Z_PROBE_SERVO_NR 0       // Defaults to SERVO 0 connector.
#define Z_SERVO_ANGLES { 13, 100 } // Z Servo Deploy and Stow angles
If I disable the above lines then the build is successful.
The build log is as follows
![image](https://user-images.githubusercontent.com/4150740/65837192-0687f280-e312-11e9-9056-9d8dcd2811a2.png)

Project files
[Uploading Marlin-bugfix-2.0.x.zip…]

Config Files
[Config_files.zip](https://github.com/MarlinFirmware/Marlin/files/3667871/Config_files.zip)
 
Using Atom + Platform.io on Windows 10

**Comment by tvixen** [comment]
Please use the default template for submitting errors/bugs. 
It's difficult for anyone to guess your hardware setup, even with the config files. 
Do you your have a bedleveling device of some kind ?
Was the 3dprinter working 100% before the new software ?

**Comment by sjasonsmith** [comment]
Your config builds just fine for me. I built on top of the latest bugfix-2.0.x commit, 5d81d7cefe98e63442e3babee6b21b2df8f02fa8.

**Comment by boelle** [comment]
as this builds just fine i will close

we can always reopen
