### ISSUE TITLE
[BUG] Error:Field probe_offset.z mismatch

### ISSUE THREAD

**Issue by Ludy87** [MarlinFirmware/Marlin#15423]
define `DEBUG_EEPROM_READWRITE` & `EEPROM_SETTINGS` and flash Marlin

open a terminal and write `M502` & `M500` & `M501`

```
Error:Field probe_offset.z mismatch.
[ERROR] Error:Field probe_offset.z mismatch.
```
The problem came with the PR https://github.com/MarlinFirmware/Marlin/commit/df1e51258a8bcc432deed9f5bd60df41a75b2c32

**Comment by thinkyhead** [comment]
Fixed with 74746c6573 … Thanks!
