### ISSUE TITLE
[BUG] Compiling with G26_MESH_VALIDATION but not ARC_SUPPORT fails

### ISSUE THREAD

**Issue by brianredbeard** [MarlinFirmware/Marlin#15426]
### Description

Seemingly, after pulling in 50e4545255605eb506c20eb107270038b0fe7bdb compiling with `G26_MESH_VALIDATION` but failing to enable `ARC_SUPPORT` fails.  Re-enabling `ARC_SUPPORT` causes the build to succeed.

### Steps to Reproduce

1.Perform a clean on the project
2. Enable `G26_MESH_VALIDATION`
3. Disable `ARC_SUPPORT`
4. Compile

Capture the following error:

```
Marlin/src/gcode/bedlevel/G26.cpp: In static member function 'static void GcodeSuite::G26()':
Marlin/src/gcode/bedlevel/G26.cpp:803:97: error: too many initializers for 'xy_float_t {aka XYval<float>}'
           xy_float_t p = { circle.x + _COS(ind    ), circle.y + _SIN(ind    ), g26_layer_height },
                                                                                                 ^
Marlin/src/gcode/bedlevel/G26.cpp:804:97: error: too many initializers for 'xy_float_t {aka XYval<float>}'
                      q = { circle.x + _COS(ind + 1), circle.y + _SIN(ind + 1), g26_layer_height };
```

#### Additional Information

Attached is the file `build.zip` which contains the configurations and a logs of successful and failed builds.
[build.zip](https://github.com/MarlinFirmware/Marlin/files/3668726/build.zip)

**Comment by DrDitto** [comment]
I have  no arc support and G26_MESH_VALIDATION enabled without compile error

**Comment by oliver-eifler** [comment]
if've got the same errors - never tried it with ARC_SUPPORT enabled...
changed (line 803/804 in gcode/G26.cpp)
```          
      xy_float_t p = { circle.x + _COS(ind    ), circle.y + _SIN(ind    ), g26_layer_height },
                     q = { circle.x + _COS(ind + 1), circle.y + _SIN(ind + 1), g26_layer_height };
```
to      

```         
     xyz_float_t p = { circle.x + _COS(ind    ), circle.y + _SIN(ind    ), g26_layer_height },
                      q = { circle.x + _COS(ind + 1), circle.y + _SIN(ind + 1), g26_layer_height };
```
and it compiled fine, anybody could confirm this?

**Comment by brianredbeard** [comment]
@oliver-eifler:  Good catch.  Putting three values in `xy_float_t`:

https://github.com/MarlinFirmware/Marlin/blob/f9400b6a3c4d09848292f1598df6e4ab4f0278f6/Marlin/src/core/types.h#L142

Which, the underlying `XYval` struct doesn't allow for:

https://github.com/MarlinFirmware/Marlin/blob/f9400b6a3c4d09848292f1598df6e4ab4f0278f6/Marlin/src/core/types.h#L179-L188

Could certainly cause problems. 

Zooming out a bit and reviewing the conditional in more detail also explains why it's only occurring when `ARC_SUPPORT` isn't present:
 
https://github.com/MarlinFirmware/Marlin/blob/f9400b6a3c4d09848292f1598df6e4ab4f0278f6/Marlin/src/gcode/bedlevel/G26.cpp#L776-L805
