### ISSUE TITLE
[FR] TMC2209 sensorless homing need StealthChop on xy and z.

### ISSUE THREAD

**Issue by CapitaineCrunche** [MarlinFirmware/Marlin#15424]
Can you add, in your sensorless homing description, Tmc2209 need StealthChop on xyz for working proprely.

**Comment by shitcreek** [comment]
How do you mean exactly by working properly? Does it not work in spreadcycle?

**Comment by CapitaineCrunche** [comment]
@shitcreek I mean you need to activate StealhChop on xyz for sensorless homing to work. It does'nt work in spreadcycle only. I find this in trinamic TMC 2209 datasheet.

**Comment by shitcreek** [comment]
PR created. Thanks for your contribution.
