### ISSUE TITLE
Missing "}" in Marlin_main.cpp in line 3893

### ISSUE THREAD

**Issue by tigertooth4** [MarlinFirmware/Marlin#1543]
Hi guys,

I noticed there's back bracket "}" missing in Marlin_main.cpp, line 3893, in the end of the super lengthy function  process_commands(). 

I'm using Xcode, the indentation is incorrect without it (the function list dropdown menu would not show functions behind process_commands().)

Although it seems the compilation is OK without it, it may cause some potential errors. With it, the compilation will pass.

**Comment by tigertooth4** [comment]
Sorry! I was wrong. Never mind!

**Comment by thinkyhead** [comment]
Thanks for the notice, even if it was mistaken. Braces are an easy one to miss, especially if the indentation isn't consistent. We're working on cleaning up the code a bit so it's more obvious where blocks start and end, and so code-folding will properly work in "naive" editors like TextMate and Sublime.
