### ISSUE TITLE
[BUG] (switch extruder SWITCHING_NOZZLE)

### ISSUE THREAD

**Issue by tgag25** [MarlinFirmware/Marlin#15444]
SWITCHING_NOZZLE(Dondolo and other)

file  tool_change.cpp
line 932: 
 current_position.z += _MAX(-diff.z, 0.0) +toolchange_settings.z_raise+nozzle_to_probe_offset.z;
line 909: 
  xyz_pos_t diff = hotend_offset[new_tool]-hotend_offset[old_tool];
to correct compilation error ....

problem since revision   23015

**Comment by Studna3D** [comment]
I have the same problem
