### ISSUE TITLE
[FR] LULZBOT TOUCH UI for FSMC display

### ISSUE THREAD

**Issue by silentst0rm** [MarlinFirmware/Marlin#15440]
Is it possible to run LULZBOT UI on MKS Robin FSMC display?

**Comment by tpruvot** [comment]
No, these external touch displays are standalone devices connected by a serial port to a Marlin board... So they have their own firmware...

**Comment by thisiskeithb** [comment]
> No, these external touch displays are standalone devices connected by a serial port to a Marlin board... So they have their own firmware...

The TFTs on the MKS Robin boards are "dumb" TFTs that don't use their own processor: https://www.aliexpress.com/item/33013776323.html

**Comment by marcio-ao** [comment]
The `LULZBOT_TOUCH_UI` can work on regular TFTs as long as you have a [FTDI FT800 or FT810 based EVE controller](https://www.ftdichip.com/EVE.htm). The `LULZBOT TOUCH_UI` is not serial based.

I would have to see the schematics for a MKS Robin to see if the motherboard uses a FTDI EVE chip.

**Comment by marcio-ao** [comment]
As far as I can tell, they do not use an FTDI controller chip, so the answer is no. The `LULZBOT_TOUCH_UI` is very specific to that particular chip so it won't work on anything else.

**Comment by psavva** [comment]
Will this work?

https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.com%2Fulk%2Fitm%2F172251934897

**Comment by TechsavvyCNC** [comment]
Yes that LCD and board would work with the lulzbot touch ui which is now called the TOUCH_UI_FTDI_EVE.
