### ISSUE TITLE
[BUG] LCD doesn't initialize properly on first power on when SD card is connected

### ISSUE THREAD

**Issue by alexyu132** [MarlinFirmware/Marlin#15454]
### Description

I'm currently running an AZSMZ board with its included AZSMZ 12864 LCD. The system is running off of a 24V PSU. When I power on my machine via the mains switch and an SD card is present in the display's reader, the LCD sometimes stays blank and sometimes displays a very faint and uneven image. The printer still acts as if the display is working properly and I can navigate the menus and print just fine. Adjusting the contrast upward helps, but parts of the display are still very faint even at max contrast. Rebooting the board via the reset button always fixes the issue and never produces a blank display with or without the SD card, but powering on with the mains switch when an SD card is inserted always seems to result in a faint or blank display.

#### Additional Information
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3688537/Configuration.zip)

Normal LCD:
![IMAG2309](https://user-images.githubusercontent.com/22603634/66173330-a4830200-e61d-11e9-99e7-fd2c0e4c41c4.jpg)

Faint LCD:
![IMAG2310](https://user-images.githubusercontent.com/22603634/66173331-a4830200-e61d-11e9-96ae-b2e2855e141e.jpg)

**Comment by alexyu132** [comment]
Updated title and description after tinkering around with it some more. I'd initially thought the problem was solely related to power cycling via the mains switch, but after further investigation the issue never happens when an SD card is not present in the LCD's reader. Could this be caused by some SPI conflict between the LCD and SD reader?

**Comment by tvixen** [comment]
Try a 22uf over your 5v supply on the LCD.

**Comment by boelle** [comment]
@alexyu132 still have an issue? is it a hardware problem and not a firmware problem?

**Comment by alexyu132** [comment]
I haven't had a chance to test adding a capacitor to the LCD, but after doing some digging it appears that the 3.3v regulator is probably the culprit. Closing as it seems to be more likely a hardware issue.
