### ISSUE TITLE
[BUG] Marlin-bugfix-2.0.x compile err

### ISSUE THREAD

**Issue by hn0550** [MarlinFirmware/Marlin#15456]
I enabled：
`#define MOTHERBOARD BOARD_RAMPS_FD_V2`
`#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`
IDE： compile err
if disable
//#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
compile through

I tested arduino-1.8.8，1.8.9，1.8.10，1.8.11，beta-1.9，I used the earlier version without this problem。

[myConfiguration.zip](https://github.com/MarlinFirmware/Marlin/files/3691424/myConfiguration.zip)

**Comment by RudyBenner** [comment]
looks like you included just the default configuration.h with your zip file?

**Comment by hn0550** [comment]
> 看起来您的zip文件中仅包含默认的configuration.h？

Sorry, this is my configuration file
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3691368/Configuration.zip)

**Comment by RudyBenner** [comment]
Linking .pio\build\DUE\firmware.elf
Checking size .pio\build\DUE\firmware.elf
Building .pio\build\DUE\firmware.bin
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [=         ]   9.2% (used 9032 bytes from 98304 bytes)
PROGRAM: [===       ]  25.5% (used 133780 bytes from 524288 bytes)
==================================== [SUCCESS] 
I did not change anything.

**Comment by hn0550** [comment]
> Linking .pio\build\DUE\firmware.elf
> Checking size .pio\build\DUE\firmware.elf
> Building .pio\build\DUE\firmware.bin
> Memory Usage -> http://bit.ly/pio-memory-usage
> DATA: [= ] 9.2% (used 9032 bytes from 98304 bytes)
> PROGRAM: [=== ] 25.5% (used 133780 bytes from 524288 bytes)
> ==================================== [SUCCESS]
> I did not change anything.
Thank you. What is your IDE version? OS version?
My is win10pro

**Comment by RudyBenner** [comment]
I will try to compile on Arduino IDE 1.8.9 now.

**Comment by hn0550** [comment]
> I will try to compile on Arduino IDE 1.8.9 now.
-------------------------------------------------------------
Thank you. This document is my error message.
[err.txt](https://github.com/MarlinFirmware/Marlin/files/3691484/err.txt)

**Comment by RudyBenner** [comment]
No luck with Arduino IDE

**Comment by RudyBenner** [comment]
My suggestion, provided you don't mind a challenge, learn to use VSCode. Bit of a steep learning curve. Instructions on marlinfw.org

**Comment by RudyBenner** [comment]
Update your libraries too.

**Comment by hn0550** [comment]
> VSCode
----------------------
MS Visual Studio Code?

**Comment by sl1pkn07** [comment]
yes

**Comment by hn0550** [comment]
> 链接.pio \ build \ DUE \ firmware.elf
> 检查大小.pio \ build \ DUE \ firmware.elf
> 构建.pio \ build \ DUE \ firmware.bin
> 内存使用情况-> [http://bit.ly/pio-memory-用法](http://bit.ly/pio-memory-usage)
> 数据：[=] 9.2％（使用98304字节中的9032字节）
> 程序：[===] 25.5％（使用524288字节中的133780字节）
> ================= ================== [成功]
> 我没有做任何更改。

-------------------------------------------
Thank you very much. I can compile it with VSCODE.  In addition, could you please tell me how the PlatformIO IDE USES the Arduino IDE download libraries? My English is poor, thank you

**Comment by RudyBenner** [comment]
Can you close this?
