### ISSUE TITLE
[BUG] Megatronics V3.0 cannot read Ext. SD and onboard SD with Marlin bugfix 2.0

### ISSUE THREAD

**Issue by swatkxs** [MarlinFirmware/Marlin#15455]
Hey guys, I have a Megatronics V3.0 and I have tried Marlin 1.1.7, 1.1.9 and 2.0.0, the #SDSUPPORT only work at 1.1.7.
here are the configration and configrationadv.

[config.zip](https://github.com/MarlinFirmware/Marlin/files/3688939/config.zip)

**Comment by boelle** [comment]
@swatkxs is this still an issue?

**Comment by boelle** [comment]
@swatkxs still having an issue? have you checked that your config is correct?

**Comment by boelle** [comment]
closing this one as it seems @swatkxs has solved his issue

we can always reopen

**Comment by swatkxs** [comment]
sorry，i have waited for too long, I forgot to check this comment, but I still have this issue. And I have uploaded my config, could someone help me have a check on it?
