### ISSUE TITLE
[BUG] _manual_goto_xy seems bugged on Marlin 2.0

### ISSUE THREAD

**Issue by AndreaMZ** [MarlinFirmware/Marlin#15471]
Hi all
Yesterday I have updated my marlin 2.0 git repository
(commit hash 5d81d7cefe98e63442e3babee6b21b2df8f02fa8)
after some testing i have noticed that the procedure
`_manual_goto_xy` in `bedlevel.cpp` has a strange behavior

I have patched the code
from
```cpp
do_blocking_move_to(pos, MANUAL_PROBE_HEIGHT); //  bugged
```
to
```cpp
do_blocking_move_to(pos.x,pos.y, MANUAL_PROBE_HEIGHT); // seems ok
```

the first invocation points to this definition
```cpp
FORCE_INLINE void do_blocking_move_to(const xy_pos_t &raw, const feedRate_t &fr_mm_s=0.0f)
```
so the `MANUAL_PROBE_HEIGHT` is mismatched to `feedRate`.

A test can be done trying the manual bed alignment : the extruder does not raise anymore between points. it moves slowly too.

kind regards
amz.

**Comment by thinkyhead** [comment]
Thanks for the note. This is now patched!
