### ISSUE TITLE
[BUG] Linear advance: actual extruder acceleration slower than retraction acceleration

### ISSUE THREAD

**Issue by BarsMonster** [MarlinFirmware/Marlin#15472]
### Description

I set Extruder acceleration and retract acceleration to very low values (10 mm/s2) to see how it works in slow motion. Retract/prime speed  is now expected, but linear advance is causing  veeeeery slow acceleration/deceleration of extruder when printing lines. I.e. extruder accelerate much slower during print moves, compared to retraction/prime moves - but acceleration limit is the same. 

Retracts are generated by Cura 4.3 (7mm). XY speeds and accelerations are much higher (100mm/s, 1000mm/s2), and not limiting the process. 

### Steps to Reproduce

1. M201 E10 ;Extruder acceleration
2. M204 R10 ;Retract acceleration
3. M900 K2 ;Requires bowden
4. Print retraction test spikes

**Expected behavior:** 

Almost all moves are limited by extruder acceleration. I.e extruder almost always accelerates/decelerates at maximum speed of 10mm/s2 for both print moves and retractions/priming.

**Actual behavior:** 

Print moves accelerate extruder ~10x slower compared to retraction, very slow acceleration/deceleration during print moves. 

#### Additional Information
Latest Marlin 2.0.x
Bowden extruder BMG

**Comment by boelle** [comment]
please attach your 2 config files just as the issue template tells you to

**Comment by boelle** [comment]
given the lack of activity and no config i will close this one

we can reopen when the configs are attached, without them there is no way for anyone to see what setup you have
