### ISSUE TITLE
[BUG] (y instead of z)

### ISSUE THREAD

**Issue by kaijrock23** [MarlinFirmware/Marlin#15485]
Hi in the move axis menu I have x.y,z,e, x is x, y is y, but if I want to move z I click z but is y, why?

**Comment by kaijrock23** [comment]
![15705314388847743162403173105288](https://user-images.githubusercontent.com/48413818/66389726-58431380-e9c9-11e9-91d5-548c857027f3.jpg)
![15705314647755595898304708823038](https://user-images.githubusercontent.com/48413818/66389744-65f89900-e9c9-11e9-9de4-23052d7121ee.jpg)

**Comment by shitcreek** [comment]
That's strange. Sometimes, on some machines, when you click down on the knob, it turns it a bit which then causes it to select either the option above or below the one you chose. Maybe this is the case, how many times have you tried it?

We can't help you much without more information. Is this a recent issue? What version of Marlin are you using? Configuration files?

**Comment by kaijrock23** [comment]
> That's strange. Sometimes, on some machines, when you click down on the knob, it turns it a bit which then causes it to select either the option above or below the one you chose. Maybe this is the case, how many times have you tried it?
> 
> We can't help you much without more information. Is this a recent issue? What version of Marlin are you using? Configuration files?

I tried many times, it's the latest build of Marlin 2.0, downloaded and compiled today, is there an option to look for to see if the y is instead of the Z in that variable?

**Comment by shitcreek** [comment]
Looks like it was a bug afterall and @thinkyhead  has addressed it: https://github.com/MarlinFirmware/Marlin/commit/cb1cb72c76c32e0fb7644874f326d3dd7d726543
Try again with the latest build.
