### ISSUE TITLE
_Statusscreen.h examples for Anet A6, A8 and A8 Plus

### ISSUE THREAD

**Issue by Lord-Quake** [MarlinFirmware/Marlin#15487]
I have prepared 3 examples for the above mentioned printers that may be included under printer examples if so desired.

Here an example for the Anet A8
![Anet_A8_Screen](https://user-images.githubusercontent.com/29223282/66416266-b4278f80-e9fd-11e9-9a2d-b4469f23c999.jpg)

File for the:
Anet A8: [_Statusscreen.zip](https://github.com/MarlinFirmware/Marlin/files/3703653/_Statusscreen.zip)
Anet A8 Plus: [_Statusscreen.zip](https://github.com/MarlinFirmware/Marlin/files/3703658/_Statusscreen.zip)
Anet A6: [_Statusscreen.zip](https://github.com/MarlinFirmware/Marlin/files/3703663/_Statusscreen.zip)

**Comment by Patag** [comment]
My A8 thanks you very much :-)

**Comment by shitcreek** [comment]
I've created a PR for this. Thank you for your contribution.

**Comment by Patag** [comment]
For Anet A8, just for (graphical) fun :-)

![A8](https://user-images.githubusercontent.com/48475891/66716396-adb66080-edcd-11e9-837c-638c5b31cc0f.jpg)
[_Statusscreen.zip](https://github.com/MarlinFirmware/Marlin/files/3721728/_Statusscreen.zip)
