### ISSUE TITLE
[FR] A modest proposal - a GUI frontend for configuration

### ISSUE THREAD

**Issue by cinealfa** [MarlinFirmware/Marlin#15486]
### Description

A Gui frontend for fast configuration
Would it be possible to have some sort of configuration parser to speed up changing settings although easy to understand, it is a painstaking process to manually have to review the settings. I would be great if ever new build could be parsed through some sort of tool ala mct(since it seems to be abandonware).
Thanks!

**Comment by shitcreek** [comment]
@thinkyhead 's got a configurator that's been in the works for some time. You can read all about it here: https://www.thinkyhead.com/blogs/thinkyhead/2015-03-06/marlin-configurator-part-1

**Comment by Vertabreak** [comment]
there is this project also https://github.com/akaJes/marlin-config i tried it out once.
