### ISSUE TITLE
[QUESTION] Is anyone working on E3D tool changer support?

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#15499]
We may be working on a printer that uses that tool changer and it would be nice not to duplicate anyone else's work.

If you have code you are working on, please let me know.

**Comment by boelle** [comment]
if not much mistaken @thinkyhead or @shitcreek got one to play with

could be wrong thou

**Comment by boelle** [comment]
Closing this one as it has gone stale

@shitcreek  and @thinkyhead can also be contacted on the discord server for questions

Marlin Discord server. Join link: https://discord.gg/n5NJ59y
