### ISSUE TITLE
[BUG] skr v1.3 "TMC CONNECTION ERROR"

### ISSUE THREAD

**Issue by whatnameshoulditake** [MarlinFirmware/Marlin#15504]
Hello,

I have a new skr v1.3 with TMC2130 v3.
I connected everything right and configured the Firmware as shown in the Bigtreetech manual,
but the LCD always says "TMC CONNECTION ERROR".
I also tried it with some previous releases of Marlin 2.0 (with no result)
Do you have any Ideas???
Or can anyone send me an already configured firmware (that would be she best option)?

Best Regards,

Simon;)

(sorry for my bad English)

**Comment by modwadd** [comment]
For which manual in detail?
also this: https://github.com/bigtreetech/BIGTREETECH-TMC2130-V3.0/blob/master/TMC2130-V3.0RM.pdf

**Comment by CharlyMai** [comment]
Did you have Power In for the Drivers?
Only USB Power do not work. 
I'll have the SKR1. 3 also in use with TMC2130 V3 and it works verry fine. 

Best Regards
CharlyMai

**Comment by whatnameshoulditake** [comment]
> 
> 
> For which manual in detail?
> also this: https://github.com/bigtreetech/BIGTREETECH-TMC2130-V3.0/blob/master/TMC2130-V3.0RM.pdf

Yes, I just followed this manual, but didn't hook up the wires bekause on the skr it´s not needed.

**Comment by whatnameshoulditake** [comment]
> 
> 
> Did you have Power In for the Drivers?
> Only USB Power do not work.
> I'll have the SKR1. 3 also in use with TMC2130 V3 and it works verry fine.
> 
> Best Regards
> CharlyMai

Of course I powered it on with 12v ;)
Could you send me your whole firmware (just to test)? If you want, you can send ist to simon@franzspeck.de

**Comment by CharlyMai** [comment]
You can download my Version of Marlin for a Laser.
It is for the SKR 1.3 with TMC2130 settings for X,Y,Z and E0

Best way is to verify the Settings in:
\\Marlin\src\pins\lpc1768\pins_BIGTREE_SKR_V1.3.h
\\Marlin\Configuration_adv.h
\\Marlin\Configuration.h

https://github.com/CharlyMai/Marlin_Laser.git

BR
CharlyMai

**Comment by CharlyMai** [comment]
Now you can look at my Marlin Ender3 Version.
It is for SKR1.3 with TMC2130 BLTouch and Stock Display:
https://github.com/CharlyMai/Marlin_Ender3.git

BR
CharlyMai

**Comment by LinFor** [comment]
Possible, your 2130 soldered in "stand-alone" mode?

**Comment by whatnameshoulditake** [comment]
> 
> 
> Now you can look at my Marlin Ender3 Version.
> It is for SKR1.3 with TMC2130 BLTouch and Stock Display:
> https://github.com/CharlyMai/Marlin_Ender3.git
> 
> BR
> CharlyMai

Hello,
Thanks a lot, now it is working;)
but the endstops are not working... any ideas?

**Comment by CharlyMai** [comment]
I use the normal Endstops exept Z. For Z i use BLTouch...
BR
CharlyMai

**Comment by modwadd** [comment]
Please comment which change finally was the solution.
BR
Kai

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
