### ISSUE TITLE
[BUG] LCD_MSG_A/B/C undefined in language_pl.h

### ISSUE THREAD

**Issue by SCiunczyk** [MarlinFirmware/Marlin#15508]
I can't compile last commit with polish language. Missing definition of LCD_MSG_A LCD_MSG_B LCD_MSG_C in the Marlin\src\lcd\language\language_pl.h.

In language_en.h in corresponding position are accordingly: LCD_STR_A LCD_STR_B LCD_STR_C

After change in language_pl.h to LCD_STR_A LCD_STR_B LCD_STR_C compilation goes fine.

Is this proper solution? If yes I can prepare PR. But have to know.

**Comment by boelle** [comment]
yes, please send the PR

**Comment by SCiunczyk** [comment]
Done.

**Comment by boelle** [comment]
will close this one then :-D
