### ISSUE TITLE
[BUG] SKR1.3 cannot be flashed with EXT2 attached MKS mini12864

### ISSUE THREAD

**Issue by karabas2011** [MarlinFirmware/Marlin#15517]
### Description

SKR1.3 + LCD mks mini 12864
MARLIN 2.0 from SKR github

SKR hangs during flashing.
If I disconnect ext2  it is flashed successfully

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
Success flashing

**Actual behavior:** [What actually happens]

hangs. Does not boot.  Even need to format micrtosd card.
If I disconnect LCD it is flashed successfully. Then I connect LCD and use printer as usually.
I thing it is related to shared SPI of secondary sdcard on lcd

**Comment by thisiskeithb** [comment]
> MARLIN 2.0 from SKR github

You’ll need to post in [BigTreeTech's SKR 1.3 issue queue](https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/issues) or download a copy of [`bugfix-2.0.x` from this repo](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) and see if your issue persists.

**Comment by boelle** [comment]
closing this one as we cant support SKR fork
