### ISSUE TITLE
[BUG] [Bugfix 2.0.x] Stutter after loading mesh w/ G29 or M420

### ISSUE THREAD

**Issue by Kokorone** [MarlinFirmware/Marlin#15513]
### Description

Printer will have consistent stutter on all steppers after a G29 is done prior to a print. 

### Steps to Reproduce

1. Compile Marlin (I tested today's build 10/10/2019)
2. Flash to printer
3. Prepare gcode with a G28 and G29 in the start code or load in old mesh with M420
4. Attempt to print from either Octoprint or from SD card

**Expected behavior:** [What you expect to happen]
Printer will print as normal

**Actual behavior:** [What actually happens]
Printer will stutter constantly, causing blobs of extrusion and in general a horrible print in a slow choppy manner

#### Additional Information

Printer is a Creality CR-10 using an SKR 1.3 with bilinear leveling enabled and TMC 2208's on all steppers with stealthchop enabled. Flashing firmware pulled from 10/5/2019 compiled with identical flags prints flawlessly so it appears to be a very recent commit that started causing this problem. Print does not appear to stutter if abl is not used (removing G29). Appears to be related to Junction deviation since switching to classic jerk fixes the issue. 

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3715923/Marlin.zip)

* Provide pictures or links to videos that clearly demonstrate the issue.
![IMG_0290](https://user-images.githubusercontent.com/32761171/66629073-85541980-ebb5-11e9-8af7-992284cd88b7.JPG)
![IMG_0288](https://user-images.githubusercontent.com/32761171/66630178-8f2b4c00-ebb8-11e9-99b7-35b8d1fd2168.JPG)

* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by GhostlyCrowd** [comment]
I'm palso in this same boat. Same print defects and the same pulsating stepper issue.

This seems ot happen with loading an existing mesh with M420 as well.

**Comment by GhostlyCrowd** [comment]
As an update tho this issue, Using ClassicJerk thus disabling Junction Devation is a work around for this bug.

**Comment by gretel** [comment]
made sure my jerk settings are non-zero (`M205`) but i got this plague, too.

**Comment by looxonline** [comment]
Had the same issue but I just installed the 11.10.19 build and now it works. Roxy made some commits relating to junction deviation so they may have fixed it.

**Comment by wffbos** [comment]
I still have the same issue. Cloned the bugfix branch 1hour ago. The problem seem to be less severe though. The stuttering movement is lesss, well, stuttering.
My steps to reproduce:
SKR v1.3
Tested with all TMC2208 uart  and all TMC2130 spi
G28
G29
X0 Y0 F10000
X150 Y150 F10000
Results in stuttering movement.

Enabling CLASSIC_JERK makes the problem go away.

**Comment by RMN9** [comment]
Yes. Confirmed. Was same situation.
CLASSIC_JERK activated -> no problem

**Comment by GhostlyCrowd** [comment]
Frsh Pull today. Used Roxy 3D's equations to set my JD settings. Also manually Set my Stepper puuls delay width and hz in Configuration_adv.h rather then letting it auto config from Configuration.h settings, and I'm printing perfectly fine now. 

No more pulsing steppers.

**Comment by boelle** [comment]
@Kokorone can you confirm what @GhostlyCrowd did works?

**Comment by Kokorone** [comment]
Did a pull of today's build with manually set pulse delay width and hz as stated with GhostlyCrowd's fix. Also set up square wave stepping and it appears to be moving correctly. Still a bug though, since setting driver names in configuration.h should automatically set the correct values that I manually defined in configuration_adv.h.

**Comment by boelle** [comment]
@shitcreek would you agree on the last statement?

@Kokorone maybe submit a PR with a true fix? things happen faster that way

**Comment by GhostlyCrowd** [comment]
Well I'm back there definitely is something funny still happening. Im getting micro stuttering still that i didnt notice right away. And My co worker can hear a high pitched whine from my printer that i cant hear because its out of my audible range but he said has never been there before.

**Comment by GhostlyCrowd** [comment]
Just went back to classic jerk and my co worker said the awful noise he could hear is gone.  The noise was just with the printer sitting idle after a G28 he could hear the noise

**Comment by Kokorone** [comment]
Agreed with Ghostly, faster movements like travel are still having a few stutters here and there with JD enabled as of the latest build on 10/30

**Comment by boelle** [comment]
@Kokorone i assume this is still an issue?

**Comment by Kokorone** [comment]
Not to the same extent as the original bug filed but yes it’s still having a stutter issue. @boelle

**Comment by boelle** [comment]
could it be that the MCU is overloaded and cant execute fast enough?

**Comment by GhostlyCrowd** [comment]
> could it be that the MCU is overloaded and cant execute fast enough?

Possibly, but that would mean we're already outrunning our 32 bit platforms with basic features. as this occours on LPC1768 for me.

**Comment by theofficialgman** [comment]
I seem to be experiencing something similar on 8 bit boards on the current version. When manual mesh bed leveling is active, the printer stops briefly after every segment interpolated between the start and end point of a move (SEGMENT_LEVELED_MOVES / LEVELED_SEGMENT_LENGTH in configuration.h). This occurs for all z values below the 5mm fade height which I have set. It seems that the buffer is not being populated or maybe the segments are being treated as individual lines where the printer has to come to a complete stop before starting the next line.

**Comment by Kokorone** [comment]
I cant say if the steppers have a high pitch noise, since I cant hear it, but this issue appears to be fixed on recent marlin builds since I have reverted any stepper pulse changes and there is no stutter present with JD enabled. Closing issue
