### ISSUE TITLE
[BUG] Compile error PID_LABEL and array bounds

### ISSUE THREAD

**Issue by viper93458** [MarlinFirmware/Marlin#15512]
### Description

Compile errors with current download for SKR Pro 1.1 and TMC2208
![image](https://user-images.githubusercontent.com/16829720/66622512-bd029780-eb9c-11e9-9de6-f945a2157d9a.png)

### Steps to Reproduce

1. Download current version from 8:30PM PST on 10/10/19
2. Configure platformio.ini for SKR Pro 1.1
3. Compile using my configs

**Expected behavior:** [What you expect to happen]
Successful compile

**Actual behavior:** [What actually happens]
Compile errors
![image](https://user-images.githubusercontent.com/16829720/66622559-f2a78080-eb9c-11e9-8112-7d8997c10989.png)

#### Additional Information
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/3715527/Configs.zip)

**Comment by boelle** [comment]
any clue what is wrong? maybe we can cook up a PR to fix it

**Comment by viper93458** [comment]
Sadly no. Not being a developer, I could only report what's happening. :(

**Comment by Cova** [comment]
I'm not sure what is wrong either - but having updated to the current code from a few months ago, I'm now getting this error as well.  In my case on a SKR V1.3 with TMC2208 drivers.

Easy workaround for the time being is to disable PID_AUTOTUNE_MENU - that gets everything compiling and working properly, just have to use a serial terminal to run a PID autotune now instead of being able to do it from the LCD.

**Comment by tubl07** [comment]
Also encountered this error using arduino ide 1.8.10 for mega2560 (RUMBA).  Disabled menu PID_AUTOTUNE_MENU to compile successfully.

**Comment by viper93458** [comment]
I tried and still got the array bounds error although the PID error went away.

-William

**Comment by viper93458** [comment]
Disabling BABYSTEP_DISPLAY_TOTAL  in Configuration_adv.h eliminates the array bounds error:

Previous:
#define BABYSTEP_DISPLAY_TOTAL

New:
//#define BABYSTEP_DISPLAY_TOTAL

-William

**Comment by boelle** [comment]
> Also encountered this error using arduino ide 1.8.10 for mega2560 (RUMBA). Disabled menu PID_AUTOTUNE_MENU to compile successfully.

tried ide 1.9.0 beta?

**Comment by viper93458** [comment]
Looks like the only issue left here is the babystep_display_total issue. Any thoughts on that piece?

-William

**Comment by boelle** [comment]
i think the PR merged 9 days ago has fixed the problem

please test again

**Comment by Cova** [comment]
I'm running with PID_AUTOTUNE_MENU enabled again so it seems fixed to me.

**Comment by boelle** [comment]
oki will close this one then

we can always reopen

**Comment by viper93458** [comment]
Yes, I was able to compile with PID_AUTOTUNE_MENU enabled and babystep_display_total enabled. Thanks!

-William
