### ISSUE TITLE
[BUG] TOUCH MI with NOZZLE_TO_PROBE_OFFSET 

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#15529]
sorry I'm a sucker it's my resolution duz is not good

**Comment by kramer04** [comment]
issue too with NOZZLE_TO_PROBE_OFFSET 
it seems not work because nozzle is out on the right X

**Comment by boelle** [comment]
maybe attach config so we know a bit about setup

**Comment by boelle** [comment]
closing this one due to missing configs

we can reopen when we have those

**Comment by kramer04** [comment]
i've attached the cong.zip . Don't you see it ?

Le mer. 30 oct. 2019 à 23:04, Bo Herrmannsen <notifications@github.com> a
écrit :

**Comment by boelle** [comment]
@kramer04 you cant attach files from email, you have to go to github for that

but we need config from @boubouexpress 

and we also need a far better description from him/her
