### ISSUE TITLE
Z_SAFE_HOMING X/Y_POINT

### ISSUE THREAD

**Issue by woodsmoke** [MarlinFirmware/Marlin#1553]
Core XY printer, Marlin development downloaded 02/03/15. Arduino 1.05, Config: #1549 

```
#define Z_SAFE_HOMING_X_POINT (X_MAX_LENGTH/2)
#define Z_SAFE_HOMING_Y_POINT (Y_MAX_LENGTH/2) 
```

Start Printer, G28 XY, G28 Z    //Gives probe outside bed area error
Start Printer, G28    //Homes XY, Moves to (X_MAX_LENGTH/2),(Y_MAX_LENGTH/2) and Homes Z correctly. 

However:

```
#define Z_SAFE_HOMING_X_POINT (X_MAX_LENGTH/6)
#define Z_SAFE_HOMING_Y_POINT (Y_MAX_LENGTH/77)    //Effectively arbitrary coordinates 
```

Start Printer, G28    //Homes XY, then Z, with no move to Safe Homing Point.

And:

```
#define Z_SAFE_HOMING_X_POINT 2
#define Z_SAFE_HOMING_Y_POINT 30  //Same arbitrary coordinates but as integers
```

Start Printer, G28    //Homes XY, then Z, with no move to Safe Homing Point.

**Comment by alexborro** [comment]
Are your probe able to reach such small coordinates like X=2 ??

2015-03-02 13:46 GMT-03:00 woodsmoke notifications@github.com:

> Core XY printer, Marlin development downloaded 02/03/15. Arduino 1.05,
> Config: #1549 https://github.com/MarlinFirmware/Marlin/issues/1549
> 
> #define Z_SAFE_HOMING_X_POINT (X_MAX_LENGTH/2)
> 
> #define Z_SAFE_HOMING_Y_POINT (Y_MAX_LENGTH/2)
> 
> Start Printer, G28 XY, G28 Z //Gives probe outside bed area error
> Start Printer, G28 //Homes XY, Moves to (X_MAX_LENGTH/2),(Y_MAX_LENGTH/2)
> and Homes Z correctly.
> 
> However:
> 
> #define Z_SAFE_HOMING_X_POINT (X_MAX_LENGTH/6)
> 
> #define Z_SAFE_HOMING_Y_POINT (Y_MAX_LENGTH/77) //Effectively arbitrary
> coordinates
> 
> Start Printer, G28 //Homes XY, then Z, with no move to Safe Homing Point.
> 
> And:
> 
> #define Z_SAFE_HOMING_X_POINT 2
> 
> #define Z_SAFE_HOMING_Y_POINT 30 //Same arbitrary coordinates but as
> integers
> 
> Start Printer, G28 //Homes XY, then Z, with no move to Safe Homing Point.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1553.

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by woodsmoke** [comment]
In my case, Marlin creates negative XY coordinates for safe homing (HOMING_POINT - PROBE). The coordinates are outside MIN to MAX positions range. 

Perhaps Marlin should generate an error, rather than simply defaulting to Z HOME at 0,0?

**Comment by woodsmoke** [comment]
It's the first time I've looked at the Marlin Source code, Apologies

**Comment by woodsmoke** [comment]
```
#if ((Z_SAFE_HOMING_X_POINT - X_PROBE_OFFSET_FROM_EXTRUDER) < X_MIN_POS )
     #error "The Safe Z Homing Coordinates are outside the X axis range of travel" 
  #endif
#if ((Z_SAFE_HOMING_Y_POINT - Y_PROBE_OFFSET_FROM_EXTRUDER) < Y_MIN_POS )
     #error "The Safe Z Homing Coordinates are outside the Y axis range of travel" 
  #endif
#else
```

Inserted around about line #1648 perhaps. It's an unlikely mistake to make really.

**Comment by thinkyhead** [comment]
Sanity checking these ranges is a good idea. The sanity-checking for config features lives in `Configuration_adv.h` so that's where these checks should probably go. We also have `L`, `R`, `B`, and `F` arguments to `G29` and I ought to add sanity checking for those as well, perhaps as another commit to #1556…

**Comment by thinkyhead** [comment]
#1556 and later commits added sanity checking. See if this issue is still happening with the latest code.
