### ISSUE TITLE
[BUG] temperature display error

### ISSUE THREAD

**Issue by hn0550** [MarlinFirmware/Marlin#15537]
What's the problem?
I found that my extruder heating temperature display error is large, heating to 180 degrees, the motherboard stopped heating immediately disappeared about 250 degrees. I am worried because I configured incorrectly and I used the default firmware still the same. But I used 2 thermistors on the extruder, one of them on the hot bed. Once the heating starts, the hot bed displays a normal temperature, while the extruder appears very cold. The hot bed temperature is 180 degrees. my thermistors is 100K

**Comment by boelle** [comment]
attach 2 config files just as the issue template told you to

**Comment by hn0550** [comment]
> attach 2 config files just as the issue template told you to
I'm sorry
The configuration file is as follows
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3721934/Configuration.zip)

**Comment by boelle** [comment]
reading this again i was thinking that maybe the thermistor is bad?

**Comment by hn0550** [comment]
> reading this again i was thinking that maybe the thermistor is bad?
---------------------------------------
I used two identical thermistors connected to the extruder to monitor the temperature, one connected to T0 and one connected to T1, but the temperature displayed was quite different.

![1](https://user-images.githubusercontent.com/10492313/67300683-f2a26b80-f520-11e9-865c-109ea0807a33.png)

**Comment by boelle** [comment]
just curious, where did you download marlin from?

**Comment by hn0550** [comment]
I found that the temperature monitoring lags behind when it is heated all the time, but there is no problem with the constant temperature in the machine printing process.

**Comment by boelle** [comment]
give direct link to where you get marlin from

**Comment by hn0550** [comment]
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x
It's right here

**Comment by boelle** [comment]
yes that is the correct place

sometimes we see people get marlin from other places

**Comment by hn0550** [comment]
I don't know what the problem is now, the hardware confirmation is good, I use ramps1.4+2560, and the result is the same with due+FDv2.  The temperature monitoring is wrong when heating, but the printing temperature is not a problem
