### ISSUE TITLE
[FR] E stepper definition

### ISSUE THREAD

**Issue by Developkings** [MarlinFirmware/Marlin#15548]
Hi there!

I would really like to see the option to define manually the extra extruders drivers to extra axis like:

//options : (E0, E1, E2 3 X2, X3, Y2, Y3, Z2, Z3)

Define e1: E0
Define e2: X2
Define e3: Z2

This would really give freedom of creation in how the machine works, later the same could also be applied to the endstops.
The actual options are nice but thez lack the possibilitz to have 2 dual drives like 2 X axis and 2 Z axis.

**Comment by DerAndere1** [comment]
Do you need independent control over two X/Y/Z axis steppers? For simultaneous movement of the dual Y (or X or Z) axes, you can wire two stepper drivers to one step/dir pin set or two steppers to one beefy driver. For independent dual X carriages, enable `DUAL_X_CARRIAGE`.
