### ISSUE TITLE
[BUG] (Mesh bed does not work at dulax Carriage)

### ISSUE THREAD

**Issue by Ziyayildizz3** [MarlinFirmware/Marlin#15562]
Hello, The mesh bed does not work in the double x carrier system. When I say the table levels, the axes are reset and they wait before nothing comes up.

**Comment by Evgeny-SPB** [comment]
Hello! I have the same problem on bugfix-2.0.x branch.
I have dual Z carriage (Z_DUAL_STEPPER_DRIVERS) setup on Prusa like printer with LPC1768 processor. Bed leveling is not working.

I did some research: Everything is working as [expected] before commit "Add custom types for position" (https://github.com/MarlinFirmware/Marlin/commit/50e4545255605eb506c20eb107270038b0fe7bdb)

After this commit Z axis stops moving after G29. Printer completes G29 and ignores all following commands to move Z axis. No mistakes or warnings is produced.

Behavior is similar to closed issue  (https://github.com/MarlinFirmware/Marlin/issues/15583). But I see no solution there.

**Comment by Ziyayildizz3** [comment]
It doesn't work when I send my mesh bed settings. I've recorded all levels of 25 points. When I throw it out of the repetier, the values I entered without leveling must be passed. Am not getting ...

**Comment by Ziyayildizz3** [comment]
Sample:
Mesh Bed Leveling:
M420 S0 Z0.00
G29 S3 X1 Y1 Z0.30000
G29 S3 X2 Y1 Z0.25000
G29 S3 X3 Y1 Z0.17500
G29 S3 X4 Y1 Z0.07500
G29 S3 X5 Y1 Z-0.00000
G29 S3 X1 Y2 Z0.25000
G29 S3 X2 Y2 Z0.20000
G29 S3 X3 Y2 Z0.17500
G29 S3 X4 Y2 Z0.10000
G29 S3 X5 Y2 Z-0.02500
G29 S3 X1 Y3 Z0.15000
G29 S3 X2 Y3 Z0.17500
G29 S3 X3 Y3 Z0.15000
G29 S3 X4 Y3 Z0.07500
G29 S3 X5 Y3 Z-0.00000
G29 S3 X1 Y4 Z0.02500
G29 S3 X2 Y4 Z0.07500
G29 S3 X3 Y4 Z0.05000
G29 S3 X4 Y4 Z0.05000
G29 S3 X5 Y4 Z-0.00000
G29 S3 X1 Y5 Z0.05000
G29 S3 X2 Y5 Z0.05000
G29 S3 X3 Y5 Z0.05000
G29 S3 X4 Y5 Z0.02500
G29 S3 X5 Y5 Z-0.00000
M500

**Comment by boelle** [comment]
@Ziyayildizz3 do you still have issues?

**Comment by boelle** [comment]
this is most likely been fixed with pr #15654 

closing

if its not the case we can reopen
