### ISSUE TITLE
active_extruder in plan_buffer_line function

### ISSUE THREAD

**Issue by clefranc** [MarlinFirmware/Marlin#1557]
I'm a beginner here, not the best coder, but looking at the "plan_buffer_line" function (planner.cpp),

https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/planner.cpp#L533

there is some use of "active_extruder" in it. I see the function is called with "active_extruder", but inside the function should it not use its argument name "extruder" instead?

It perhaps has no impact on the result of the code, just that I find it odd.

**Comment by thinkyhead** [comment]
@clefranc `active_extruder` is a global extern exposed in `Marlin.h`. This global is used in `plan_buffer_line`. The `extruder` argument to `plan_buffer_line` is also used, of course (for example, line 658). There might be some instances where these values can differ, so I'm hesitant to make any changes here just yet. We should look more closely at these vars, however.

**Comment by boelle** [comment]
can this one be  closed or?

**Comment by thinkyhead** [comment]
planner.cpp will be getting more attention soon.
