### ISSUE TITLE
Auto level sensor issue

### ISSUE THREAD

**Issue by gala2000** [MarlinFirmware/Marlin#15571]
Hello,

Today I installed my level sensor.  Everything worked well except for a few small things and the sensor worked reasonably well.  until I realized that the sensor is not working as soon as the bed starts to heat.  So the lamp on the sensor is completely off and it does not switch.  so I can not “go home“ and auto level before printing. I also tried the #probing_heaters_off function.  I can not go home with that either.

I also have pixel errors on the screen I do not know if that has a connection.

Sry for my bad English guys:)

**Comment by boelle** [comment]
is this a question or bug?

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
