### ISSUE TITLE
[QUESTION] Screen Problems

### ISSUE THREAD

**Issue by uok8252** [MarlinFirmware/Marlin#15580]
Hello everyone,
I got a problem about marlin 1.19 and 2.0
My screen doesn't work correctly.
I upload some videos about my problem.
( I install Repetier and screen works correctly but i want use marlin so please help me about problem)
[https://youtu.be/k5qs8QracL8](https://youtu.be/k5qs8QracL8)

**Comment by DiogoLambert** [comment]
I am having the same problem after updating the arduino!

**Comment by boelle** [comment]
is this a bug or question?

**Comment by uok8252** [comment]
> is this a bug or question?

We don't know.

**Comment by AnHardt** [comment]
The usual timing problems. Use the delays.

**Comment by boelle** [comment]
@AnHardt so this is an config error and not a marlin failure as such?

**Comment by boelle** [comment]
@uok8252  there are also these places you can get help

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by uok8252** [comment]
> The usual timing problems. Use the delays.

i can't fix can you help me please.
Here is my codes.
[Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/3741353/Marlin-bugfix-2.0.x.zip)

**Comment by boelle** [comment]
@uok8252 did you try any of the places i suggested?

**Comment by uok8252** [comment]
> @uok8252 did you try any of the places i suggested?

Yes i try discord but no body can help me ? My english not so good , so i understand little bit

**Comment by uok8252** [comment]
I upload with vscode and its fixed

**Comment by boelle** [comment]
oki, will close then :-D
