### ISSUE TITLE
[BUG] Fix DUE HAL serial defines (#15536)

### ISSUE THREAD

**Issue by Evg33** [MarlinFirmware/Marlin#15584]
BUG in "Fix DUE HAL serial defines"  (#15536)
After this patch Marlin not answer.
But DUE can be reflashed.

default_envs = DUE_USB
```
#define MOTHERBOARD BOARD_RURAMPS4D_13
#define SERIAL_PORT -1
#define SERIAL_PORT_2 1
#define BAUDRATE 250000
```

If I change file \Marlin\src\HAL\HAL_DUE\HAL.h  like this, then it works
```
#if SERIAL_PORT == -1
  //#define MYSERIAL0 Serial1
  #define MYSERIAL0 customizedSerial1
```

And review this please:
```  #if SERIAL_PORT_2 == -1
    #define MYSERIAL1 Serial1
```

**Comment by boelle** [comment]
you could maybe submit a PR to bugfix 2.0.x?
