### ISSUE TITLE
melzi restart on extruder turn on

### ISSUE THREAD

**Issue by johnd4321** [MarlinFirmware/Marlin#1560]
I am using Merlin firmware on a melzi board for a huxley printer.  It used to work, but now when I send a M104 T0 S205 command it resets the firmware.  Other commands including Gcode works.

**Comment by nophead** [comment]
Does it do the same if you disconnect the extruder? 

Seems like a hardware problem, a heater short or a short from the heater to the thermistor.

**Comment by johnd4321** [comment]
Sure nuf, disconnecting the extruder works, does not reset the board.
Definitely a short, will track it down, thanks!

On 3/4/2015 5:22 PM, Chris wrote:

> Does it do the same if you disconnect the extruder?
> 
> Seems like a hardware problem, a heater short or a short from the 
> heater to the thermistor.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MarlinFirmware/Marlin/issues/1560#issuecomment-77272815.

## 

"Printing 3D in Houston"
