### ISSUE TITLE
[BUG] The progress bar does not work

### ISSUE THREAD

**Issue by manarsak** [MarlinFirmware/Marlin#15601]
Hi, I used to show the remaining time to print with the percentage, but the progress bar is not moving and remains constant and the percentage is 99 What is the problem
![IMG_20191019_143629](https://user-images.githubusercontent.com/25624009/67148349-18204280-f29f-11e9-943f-a0ad946382bd.jpg)

**Comment by boelle** [comment]
have you tried asking these places?

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by manarsak** [comment]
My friend this is a problem in marlin and not a question

**Comment by boelle** [comment]
you did forget to attach config files as the issue template told you to so i assumed it was a question

**Comment by boelle** [comment]
could you attach your config files as zip?

maybe it can tell the code people something

**Comment by boelle** [comment]
closing this one due missing config files

we can reopen later
