### ISSUE TITLE
[BUG] Tevo Nereus on Marlin began to print circles with small twitches

### ISSUE THREAD

**Issue by artdezigner** [MarlinFirmware/Marlin#15617]
Good afternoon. Please, I need help: the printer began to print circles with small twitches and small speed. At what on a regular firmware prints normally (not problem in hardware). It happened just like that, typed well 3 days, and then suddenly began to type with twitches. Reflashing does not help.
![73504761_2633725713382749_2117288288447365120_n](https://user-images.githubusercontent.com/49458234/67231955-01b5ea80-f449-11e9-83b7-872be205df85.jpg)
Drivers X-Y-Z-E: lv8729 (128st) lv8729 (128st) a4988 (16st) a4988 (16st)

**Comment by boelle** [comment]
ask here instead:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

the issue list is not for questions or support
