### ISSUE TITLE
[FR] Marlin 1.1.x CLCD Korean support

### ISSUE THREAD

**Issue by portalab** [MarlinFirmware/Marlin#15629]
### Description
I think it is cool if my delta print supports korean CLCD interface.
But not support on 1.1x 
So I will try making korean interface for fun.

Language support list : http://marlinfw.org/docs/development/lcd_language.html

### Steps to Reproduce
1. Makes font with a few characters
2. translate as a code
3. Test
?

#### Additional Information
http://marlinfw.org/docs/development/lcd_language.html#mappers

**Comment by boelle** [comment]
use 2.0.x instead, 1.1.x is not updated much anymore

**Comment by portalab** [comment]
> use 2.0.x instead, 1.1.x is not updated much anymore

Okay, but My friends and me still use 1.1.9 release, so it will be great if it support  on 1.1.x  :)

**Comment by boelle** [comment]
upgrade to 2.0.x, there is not much support on 1,1.x

**Comment by shitcreek** [comment]
@portalab if you're willing to do all the legwork, I will gladly create a PR for it :)
