### ISSUE TITLE
[FR] Switchless homing

### ISSUE THREAD

**Issue by Zol-Tank** [MarlinFirmware/Marlin#15639]
### Description

Switchless homing. I'd would be nice if I could manually move the axis to their home position, tell Marlin "They're at home position", and have it simply accept those positions as home. On custom printers, it would be nice not having to worry about endstop switches.

**Comment by hackebike** [comment]
isn't that sensorless homing? I have a custom printer and I set some fix ends that make the home position, than using sensorless homing, the motor stops at the fix position.

**Comment by Zol-Tank** [comment]
Sensorless homing uses feedback from the steppers stalling to set home, requiring stepper drives capable of sensorless homing running in UART or SPI, plus having some robust for your axis to run into at the home position. What I'm talking about doesn't need any of that. It's simply telling Marlin "Your axis are at their home position right now".

**Comment by hackebike** [comment]
I see, so is a software config. What is the use case?

**Comment by Zol-Tank** [comment]
Yeah, basically. You move the axis by hand to their home position, and then you tell Marlin "They're at their home position". This way I don't need the cost or complexity of sensorless capable drivers in UART/SPI mode, nor do I need to somehow attach and wire switches to my axis. It just simplifies the hardware a bit, which is nice for custom or heavily modified printers.

**Comment by hackebike** [comment]
ok makes sense! I am using sensorless homing/probing for that reason to simplify hardware and wiring as my printer is huge. Also I read somewhere that when you move the motors/axis by hand they produce a reverse current which might damage the drivers, something to keep it in mind I guess.

**Comment by Zol-Tank** [comment]
Yes, they do, and they can even damage the drivers if you move them fast enough. However, I figure switchless homing like this would probably only be used by fairly experienced people who'd know better than to go zooming their axis around.

**Comment by LinFor** [comment]
"G92 X0 Y0 Z0" is not a solution to your problem?
It can be added in "custom commands" menu if you need use it from LCD

**Comment by Zol-Tank** [comment]
> "G92 X0 Y0 Z0" is not a solution to your problem?
> It can be added in "custom commands" menu if you need use it from LCD

I had no idea that was even a thing. That's great! So if I have a BLtouch, I should be able to do this to home the axis then level the bed, correct?
G92 X0 Y0
G28 Z
G29

**Comment by LinFor** [comment]
> So if I have a BLtouch, I should be able to do this to home the axis then level the bed, correct?

I didn't check this but probably yes

**Comment by thinkyhead** [comment]
The `MARLIN_DEV_MODE` option gives you `G28 S` for "simulated homing" with no movement. Use at your own risk.
