### ISSUE TITLE
Problem Marlin 2.0 ender 5

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#15633]
Hi, I have an ender 5 with Marlin 2.0, what value should I set to report the steps as in the picture?
I apologize for my incorrect English but I speak Italian.
Link video https://youtu.be/d3H36F7wwbE
![13](https://user-images.githubusercontent.com/56886091/67307819-6597ec00-f4f9-11e9-8c0b-cd58eafa88e7.JPG)
![12](https://user-images.githubusercontent.com/56886091/67307822-6597ec00-f4f9-11e9-9127-948d23fe502e.JPG)

**Comment by reloxx13** [comment]
> Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use the Marlin Firmware forum at http://forums.reprap.org/list.php?415 or the Marlin Facebook Group https://www.facebook.com/groups/1049718498464482/.
> 
> Or use discord: https://discord.gg/n5NJ59y

Or join Creality/Ender groups on FB.

and read marlin gcode docs.

@boelle

**Comment by ghost** [comment]
ok thanks. delete post
