### ISSUE TITLE
[BUG] Delta Bed Leveling failed (G33) on SKR v1.1 (bugfix-2.0.x)

### ISSUE THREAD

**Issue by weatherwarlock** [MarlinFirmware/Marlin#15638]
### Description
Delta with chimera with one nozzle
board: SKR v1.1 with TMC2130 SPI

### Steps to Reproduce
M502
M500
G28
G33 P7 V2

#### Additional Information
The log of a couple of attempts in the archive. Last attempt with settings from the archive
[BedLevelingError.zip](https://github.com/MarlinFirmware/Marlin/files/3758453/BedLevelingError.zip)

**Comment by weatherwarlock** [comment]
Probe as removables
https://www.thingiverse.com/thing:2492071

**Comment by shitcreek** [comment]
If you are using a removable probe, you should use `FIX_MOUNTED_PROBE` instead of `Z_PROBE_ALLEN_KEY`

**Comment by weatherwarlock** [comment]
my choice was based on a description(http://marlinfw.org/docs/configuration/probes.html):
> Z_PROBE_ALLEN_KEY This is a popular solution on deltas. A spare Allen key is used with an endstop switch to make a probe that’s deployed and stowed by turning the key 90 degrees. **You can either deploy and stow the key manually** or configure movements that bump the key against some fixed point. Options for this type of probe are included in the delta example configurations that come with Marlin.

And earlier like it was just another description on reprap

In January, there was a working firmware. When reflashing in July, received reports STOW PROBE, which then is followed by PROBING FAILED. In July I tried to fix it, then there was no time (and patience) to look for (who and where broke it). I think that now the problem is also related to this.
I think it would be nice to make the necessary STOW for Z_PROBE_ALLEN_KEY switchable in configuration(earlier, after G33, the head just returned to the home, without STOW).

**Comment by weatherwarlock** [comment]
I'm sorry, the contact was unstable
when I checked m119 - everything was fine, but when calibrating - it left
