### ISSUE TITLE
[BUG] TEMP_SENSOR_1_AS_REDUNDANT #error "TEMP_SENSOR_1 shouldn't be set with only 1 HOTEND."

### ISSUE THREAD

**Issue by DroneMang** [MarlinFirmware/Marlin#15634]
Hi,

I am working on trying dual thermistors for 1 hotend.  If I set the below I get the error.  Does this assume both thermistors are using the same sensor, and that temp sensor 1 gets the same value of 5 in this case because it is set for temp sensor 0?

If I set:

#define TEMP_SENSOR_1_AS_REDUNDANT

and set:

#define TEMP_SENSOR_0 5
#define TEMP_SENSOR_1 5

I get this error during compiling:
#error "TEMP_SENSOR_1 shouldn't be set with only 1 HOTEND."

Thank you,
DroneMang

**Comment by shitcreek** [comment]
Which version of Marlin are you using? In Marlin 2.0, this error is produced by `SanityCheck.h` when `TEMP_SENSOR_1_AS_REDUNDANT` is disabled:
`#elif TEMP_SENSOR_1 != 0 && DISABLED(TEMP_SENSOR_1_AS_REDUNDANT)
#error "TEMP_SENSOR_1 shouldn't be set with only 1 HOTEND."`

**Comment by boelle** [comment]
and also i think config files would help?
and also give direct link to where you got marlin from, just so we know what we are looking at

**Comment by psavva** [comment]
I'm going to suggest you try work the lastest Marlin 2.0. Looking so the code, I cannot tell that you'd be able to simulate the same error.

The other alternative is that something is mistyped in your conf files .

Please upload

**Comment by boelle** [comment]
@psavva who should upload what? we dont know if there is something mistyped as there are no config files

**Comment by psavva** [comment]
The person reporting the issue ;)

**Comment by boelle** [comment]
what should he upload that have not allready been asked for?

**Comment by DroneMang** [comment]
Here are the config files:
[config.zip](https://github.com/MarlinFirmware/Marlin/files/3758483/config.zip)

I downloaded this last night from github where it says clone or download, Marlin 2.0. No edits to this:
[Marlin-2.0--3.zip](https://github.com/MarlinFirmware/Marlin/files/3758486/Marlin-2.0--3.zip)

I have temp 1 set to 0 right now so it does compile but it should be set to 5. I am using Arduino IDE to compile.

**Comment by GMagician** [comment]
I tested attached cnf and compile fine (but using vscode)

**Comment by boelle** [comment]
what version of ide? 1.9.0 beta is recommended.... or vscode+platform.io

**Comment by GMagician** [comment]
Compiled correctly with vscode and ide 1.8.10

**Comment by DroneMang** [comment]
With temp 1 set to 5 and not 0?

**Comment by boelle** [comment]
prob as the config files are uploaded, so if the configfiles you attached is with temp 1 set to 0 then yeah

you should always upload files with correct settings even if they dont compile

**Comment by DroneMang** [comment]
Here are the config files that produce the error.  I'll upload with the correct settings in the future.  Thank you.

[config with error.zip](https://github.com/MarlinFirmware/Marlin/files/3759016/config.with.error.zip)

**Comment by GMagician** [comment]
It seems that to enable such function you have to write `#define TEMP_SENSOR_1_AS_REDUNDANT true`
but this is in contrast to what is written in all configuration files...

EDIT: not really true above statement....

**Comment by GMagician** [comment]
I think that is code may explain why you have this error:
```c++
#if EITHER(SINGLENOZZLE, MIXING_EXTRUDER)         // One hotend, one thermistor, no XY offset
  #undef HOTENDS
  #define HOTENDS       1
  #undef TEMP_SENSOR_1_AS_REDUNDANT
  #undef HOTEND_OFFSET_X
  #undef HOTEND_OFFSET_Y
#endif
```

but since you have just one "HOTEND" this shouldn't undefine `TEMP_SENSOR_1_AS_REDUNDANT`...

maybe @thinkyhead may say more

**Comment by GMagician** [comment]
@DroneMang please test my PR nr #15650

**Comment by DroneMang** [comment]
This compiles now with no errors (except the DOGM one which I'm assuming will get fixed soon).

Question, is there a way to view the temperature outputs of each thermistor in the terminal?  I would like to do some tests.

As it is now, the logic says to kill the print if the temperature difference is too large.  My friend pointed out that it could also be used in a redundant type way, where if one thermistor fails, a flag could be thrown but the print could continue with the 1 good thermistor.  But then how do you with confidence decide which is the good one and which to trust?

I prefer the current logic, but perhaps another option could be in the config file to allow the user to decide.

**Comment by boelle** [comment]
@GMagician when will the PR be sent to 2.0.x ? if allready done what is the PR number?

**Comment by GMagician** [comment]
Already been merged as I know it's #15650

**Comment by boelle** [comment]
you are right

will risk my neck and close this one then

we can always reopen if PR https://github.com/MarlinFirmware/Marlin/pull/15650 did not solve it

**Comment by DroneMang** [comment]
Just tested this last night. It works, but when the hotend is heating up it
must heat the sensors at different rates as it emergency shut down and
disconnected. I then reconnected and had it heat up to pla temps and it was
fine. I can just make the temp difference 15 instead of 10, but maybe there
can be a feature to wait until at temp before comparing them?
