### ISSUE TITLE
[BUG] Z Probe Offset Changes After G29 probe fail. 

### ISSUE THREAD

**Issue by fizz306** [MarlinFirmware/Marlin#15647]
If my BLtouch fails during G29, my Z Probe Offset needs to be changed manually by -.1mm. The only way to fix the issue is to cycle the power, which I don't care to do as my Octopi cycles when I shut the printer down. Anyone else having this issue?

**Comment by reloxx13** [comment]
use the search function, fill the issue template.

**Comment by boelle** [comment]
temporary closing this one as the issue template has clearly not been followed, when the issue template has been read and missing info has been added we can reopen it
