### ISSUE TITLE
[BUG] Fix for #15654 reverts #15636

### ISSUE THREAD

**Issue by lukaszzamel** [MarlinFirmware/Marlin#15659]
On bugfix-2.0.x commit efeb6efe773ed137f3a1d225f98b0f0b929c320b reverts changes from efeb6efe773ed137f3a1d225f98b0f0b929c320b. Guess this was not intended.

**Comment by shitcreek** [comment]
You linked the same PRs. I didn't realize a PR was already submitted for this issue - mine respects the new `*this` style just in case it is referred to elsewhere. I've tested both.

**Comment by boelle** [comment]
this gave me a small smile, but yes i guess one of the links is wrong :-D

**Comment by lukaszzamel** [comment]
yup. my bad. this is the second one b7db91c46d1db59646e6fc7037807f77f596ccdd

**Comment by lukaszzamel** [comment]
Ugh. Right. @shitcreek is correct. This can be closed.
