### ISSUE TITLE
Documentation - Is there a Changelog?

### ISSUE THREAD

**Issue by thiagopeixoto16** [MarlinFirmware/Marlin#1566]
Do we have a changelog? 
If not, is there any plans to make one? 

It will be great for the users to evaluate an version upgrade.

Thanks!

**Comment by boelle** [comment]
there are a kind of... on each release there are a link where all the commits can be read...

but its mostly still bugfixing... new features are last in line

**Comment by thiagopeixoto16** [comment]
Okay sir, thanks!

**Comment by thinkyhead** [comment]
The subject has come up recently. It takes some work to make a concise changelog. But one of the easier ways to gauge changes is to compare the Configuration files between releases. These reveal any new features and sometimes fixes. Bug-fixes and other enhancements take more work to track down in the issues list and commit logs. It also takes some extra work to maintain a Known Bugs list for tagged releases. The thing is, Marlin is always changing (improving!) and it's just hard to keep up with so much fluctuation.

**Comment by boelle** [comment]
i agree... but will close this one so we dont end up with an mount everest list of issues... but once we start to get to a a state we can call stable we should start to make a change log of some sorts
