### ISSUE TITLE
[BUG] status_screen_DOGM.

### ISSUE THREAD

**Issue by AzO95** [MarlinFirmware/Marlin#15665]
Hello,

After the last modification I can not compile anymore

Marlin\src\lcd\dogm\status_screen_DOGM.cpp:642:8: error: #else after #else
       #else // !DOGM_SD_PERCENT || !SHOW_REMAINING_TIME || !ROTATE_PROGRESS_DISPLAY
        ^
Marlin\src\lcd\dogm\status_screen_DOGM.cpp:594:0: error: the conditional began here
       #if ALL(DOGM_SD_PERCENT, SHOW_REMAINING_TIME, ROTATE_PROGRESS_DISPLAY)
 ^
Marlin\src\lcd\dogm\status_screen_DOGM.cpp:30:0: error: unterminated #if
 #if HAS_GRAPHICAL_LCD && DISABLED(LIGHTWEIGHT_UI)
 ^
*** [.pio\build\megaatmega2560\src\src\lcd\dogm\status_screen_DOGM.cpp.o] Error 1
============================================================================================== [FAILED] Took 54.97 seconds ==============================================================================================

Environment              Status    Duration
-----------------------  --------  ------------
megaatmega2560           FAILED    00:00:54.970

>

**Comment by anlupat** [comment]
I changed line 642 "#else // !DOGM_SD_PERCENT || !SHOW_REMAINING_TIME || !ROTATE_PROGRESS_DISPLAY" to "#endif" that fixed it for me.

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/15661

**Comment by shitcreek** [comment]
Issue has been fixed. Thanks for reporting.
