### ISSUE TITLE
[BUG] RUNOUT fails (Big size printing reveals some issues )

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#15674]
DONT CLOSE PLEASE , must be seriouly evaluated by @thinkyhead 

**RUNOUT BUGS**
(Invisible in little prints because of little blocks) , but not on big size printers(Crealty500 , Tronxy, Modix60/120)

- **RunoutSwitch polling after block completed => if runoutdistance=25 , countdown is 24 , and the next block is 20 ' big outline with 0.8 nozzle ' , no extrusion , print is damaged**

  - [FR] Substraction of the last extrusion in the countdown after the first detection
  - [FR] Go to pause if any extrusion command > countdown in progress
+ **Motion sensors** 
  - **Polling doesn't work on big extrusion command, if you have some big block of 200mm(500mm outline with 0.8 nozzle), the sensor is checked two times in 200 mm and if the two states checked are differents , the next block will run and we have two blocks wasted and 400mm of filament not extruded, the print is dead**

      - [FR]  Define a MOTION_SENSOR_PULSE_DISTANCE in config.h
      - [FR]  Create a Poll in stepper isr , every 'Encoder pulse distance '
      - [FR]  If encoder is stopped = Stop isr = create a new gcode with the remaining extrusion
      - [FR]  Go to pause and enqueue this new command to restart the print perfectly when out of pause

**By this way , you implement , a jam detection in marlin and it's a great feature**
_(With a rotary encoder that give 24 pulses for 36mm of feeding, Marlin can seriously protect the printing in many situations)_
The better algorithm for detecting a rotary movement is to check 3 points , the two last state and the new .
Move = XOR ( old state / last state / new state ) with this , NO RISK of false detection. 

@thinkyhead please help
_(I can't make this , because need to learn stepper isr , timing and more , it's too much for me ...Sorry you have to make it 😄 )_

**Comment by boelle** [comment]
so this is a kind of feature request?

**Comment by studiodyne** [comment]
@boelle ..... May be ... but just a functionnal sketch to give inspiration ,  when i will have time for this

**Comment by boelle** [comment]
its more that we have the list sorted in to either bugs or feature requests

support and discussions are meant to go on the discord server or forums

i know that there are a few open issue that fall outside that but they are sadly allready have so big roots that we cant close them before they have served their purpose

**Comment by studiodyne** [comment]
For the moment , i use this thread for information , and to see if some wants to begin a starting point or some sketches of code , or may be @thinkyhead decide to apply some updates after reading this
But if no job made after a few days , i will begin my own Pull Request , and make it it progressively , by asking help to perform it to the end

**Comment by boelle** [comment]
we can still call this a feature request then

if you dont mind i would change the title to [FR] RUNOUT big bugs ' in big printing' [Reflexions/Discussions]

**Comment by studiodyne** [comment]
If @thinkyhead have read this thread , you can close if you want 
Or if you prefer to rename as PR , it's ok 
Thks

**Comment by boelle** [comment]
there is no need to close it if it turns out to be a good idea :-D
positive thoughts from here

**Comment by InsanityAutomation** [comment]
I agree this is the next logical evolution. We're at the first stage of native jam detection and what's described here is probably a stage 3. Good goal to work towards for sure.

**Comment by studiodyne** [comment]
I have rewritten seriously the issue , to be understood the more seriously possible
And , by this way , a jam detection will be implemented
I have checked Stepper code , but , really too much for me , need to work six month on it to create a realistic code , with no stuttering isr , and more

Then  .... I ask for help

**Comment by boelle** [comment]
@thinkyhead time have a quick look here?

**Comment by boelle** [comment]
@thinkyhead time have a quick look here?

**Comment by boelle** [comment]
since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by boelle** [comment]
is the issue still the same with all the updates in the last 49 days?

**Comment by boelle** [comment]
btw, who can confirm there is an issue? use the same configs as OP and the same hardware if possible

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
