### ISSUE TITLE
Configuration.h reads v1.0.2 ??

### ISSUE THREAD

**Issue by bolsoncerrado** [MarlinFirmware/Marlin#1567]
Configuration.h reads v1.0.2 ??

**Comment by boelle** [comment]
yep... latest ver is 1.0.2

**Comment by bolsoncerrado** [comment]
What is this then, the WIP unreleased version?

![captura de pantalla 2015-03-05 a la s 17 25 51](https://cloud.githubusercontent.com/assets/10992914/6509022/be9fba36-c35c-11e4-96be-9dd852f6086c.png)

**Comment by boelle** [comment]
that is just a draft.... it will be released once next milestone is cleared

**Comment by boelle** [comment]
gone now... it was just a mistake by me when i made the draft... i by fault ticked the box to create a pre-release... 

normal users should not be able to see a draft... but mistakes happen..

will close this one as there is no issue in it
