### ISSUE TITLE
No Z motion possible after auto bed leveling with a working Z- Axis

### ISSUE THREAD

**Issue by Louis-Cypher** [MarlinFirmware/Marlin#15672]
### Description

Starting with the version of bugfix 2.0 I pulled yesterday I have a very strange behaviour. I can home all axis, do auto bed leveling but when I enter a G0 or G1 command *after* running G29 the motors are switched on but do not move at all. The display changes to the intended position, meaning that motion parameters seem to be completely wrong and my motor looses all steps. The strange thing is that the same motors work perfectly fine when I do homing even at high speeds.

The behaviour described above only is present after using auto bed leveling! Until the first G29 is sent I can move Z by sending G0 or using the Move Axis menu. After sending a G29 Z doesn't move anymore at all (but I can hear that the motors are activated). There is no probing failed message or the like.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3773480/Marlin.zip)

### Steps to Reproduce

1. Load configs
2. Perform G28
3. Perform G29
4. Send a G0 Z12

**Expected behavior:** Z- Axis moving to Z12

**Actual behavior:** Z- Axis doesn't move but Display showing Z 12

**Comment by reloxx13** [comment]
link https://github.com/MarlinFirmware/Marlin/issues/15450#issuecomment-539190835

**Comment by Louis-Cypher** [comment]
You're right. Appears to be the same bug, thanks. At least I know that setting Marlin up from scratch doesn't make any sense. I'll try to use mesh leveling to see whether this is messed up as well.

**Comment by boelle** [comment]
so we could in fact close this one so we dont have a dublicate?

this one will be mentioned in https://github.com/MarlinFirmware/Marlin/issues/15450#issuecomment-539190835 anyway

**Comment by shitcreek** [comment]
Closing duplicate issue. Please refer to the aforementioned open issue.
