### ISSUE TITLE
[FR] different driver current for sensorless_homing

### ISSUE THREAD

**Issue by danym21** [MarlinFirmware/Marlin#15686]
### Description
I use TMC5160 stepper drivers, since I use 0.9deg/step instead 1.8deg/step motors stallguard is not triggered  correctly with the the current that I use for printing.

as example for printing I use a current from 1100 mA and "STALL_SENSITIVITY  2" the machine is crashing, when I use "STALL_SENSITIVITY  1" Stallguard is trigger often in the middle of the way to the edge.  When I use a current from 462 for homing with "STALL_SENSITIVITY  2" all is working fine but on printing it is losing steps.

when this is useful for all, then I will share my code changes that I testing at the moment.
I add additional settings in the configuration_adv.h and changed the G28 source code.
at the moment it is working fine for me.

**Comment by thinkyhead** [comment]
When you have a PR submitted, we can close this issue and discuss the PR.

**Comment by danym21** [comment]
I have tried to submitt, can you check please?
