### ISSUE TITLE
[info] (arduino ide 1.8.10 is down) use 1.8.9 and wait the fix

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#15681]
all in the title

ARDUINO IDE 1.8.10 have serious corruption

1.8.9    69% sram
1.8.10 72%

and all is wrong in the firmware , on lcd too

**Comment by boelle** [comment]
1.9.0 beta
or vscode+platform.io 

is what is recommended

as this is not a problem with marlin firmware i will close this again.


EDIT: if this is really a marlin problem please attach your config files as the issue template told you too

and maybe have a look these places first

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

we can always reopen if you can point out why you think its a marlin problem
