### ISSUE TITLE
[BUG] G29 dosent use Probe offset 

### ISSUE THREAD

**Issue by PeterG555** [MarlinFirmware/Marlin#15685]
When im starting Autoleveling the probe will be placed outside the buildplate. I set an X Prope offset but it seems like that it will not be used.

**Comment by boelle** [comment]
You did not follow the issue template so have a look here

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

when you get back to here please fill in the missing info that the template told you to provide
