### ISSUE TITLE
[BUG] MKS SBase USB-Pronterface connection fails (Win10)

### ISSUE THREAD

**Issue by J-PN** [MarlinFirmware/Marlin#15697]
Version 26-Oct-19 and previous (but I cannot pinpoint how far)

This has worked some months ago but now I have issues. Connection to Pronterface stays 'Connection...' for ever with all following cases.

1) After connection the cable, USB is recognized as Standard Port Com3 (manually changed the speed 115200)
2) Installed the Smoothieboard signed driver
3) Installed the ..\Marlin\src\HAL\HAL_LPC1768\win_usb_driver, using UnSigned driver installation mode

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by J-PN** [comment]
Here they are, thanks.
[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/3785177/Configurations.zip)

Warnings:
Compiling .pio\build\LPC1768\src\src\gcode\probe\M851.cpp.o
In file included from Marlin\src\gcode\motion\../../inc/MarlinConfig.h:45,
Compiling .pio\build\LPC1768\src\src\gcode\probe\M951.cpp.o
                 from Marlin\src\gcode\motion\M290.cpp:23:
Marlin\src\gcode\motion\M290.cpp: In static member function 'static void GcodeSuite::M290()':
Marlin\src\gcode\motion\M290.cpp:127:55: warning: array subscript 2 is above array bounds of 'int16_t [1]' {aka 'short int [1]'} [-Warray-bounds]
         " Z", babystep.axis_total[BS_TODO_AXIS(Z_AXIS)]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Marlin\src\gcode\motion\../../inc/../core/serial.h:120:62: note: in definition of macro '_SELP_2'    
 #define _SELP_2(PRE,V)     do{ serial_echopair_PGM(PSTR(PRE),V); SERIAL_EOL(); }while(0)
Compiling .pio\build\LPC1768\src\src\gcode\queue.cpp.o
                                                              ^
Marlin\src\gcode\motion\../../inc/../core/serial.h:118:28: note: in expansion of macro '__SELP_N'    
 #define _SELP_N(N,V...)    __SELP_N(N,V)
                            ^~~~~~~~
Marlin\src\gcode\motion\../../inc/../core/serial.h:144:33: note: in expansion of macro '_SELP_N'
Compiling .pio\build\LPC1768\src\src\gcode\scara\M360-M364.cpp.o
 #define SERIAL_ECHOLNPAIR(V...) _SELP_N(NUM_ARGS(V),V)
Compiling .pio\build\LPC1768\src\src\gcode\sdcard\M20.cpp.o
                                 ^~~~Compiling .pio\build\LPC1768\src\src\gcode\sdcard\M21_M22.cpp.o
~~~
Marlin\src\gcode\motion\M290.cpp:122:7: note: in expansion of macro 'SERIAL_ECHOLNPAIR'
       SERIAL_ECHOLNPAIR("Babystep"
       ^~~~~~~~~~~~~Compiling .pio\build\LPC1768\src\src\gcode\sdcard\M23.cpp.o
~~~~

**Comment by boelle** [comment]
@J-PN many updates have been done in last 5 days, is this issue still present in 2.0.x ?

**Comment by J-PN** [comment]
Thanx. Though, I'm struggling to compile now.
/SanityCheck.h:28:4: error: #error "framework-arduino-lpc176x package is out of date
I've removed & re-load/install PlatformIO IDE 1.9.3 but ...

**Comment by p3p** [comment]
To fix your initial issue you need to enable the USB serial port, 
`#define SERIAL_PORT -1`

If you are on Windows 10 you didn't need the driver ..and definitely not 2 of them .. hopefully that doesn't hurt anything.

The out of date error shouldn't happen, are you using the old `platformio.ini` after downloading the Marlin update? If not then try removing the `.platformio` folder from your user directory,  `.pio` from the Marlin directory and try again.. PlatformIO should be downloading the new packages.

**Comment by J-PN** [comment]
Tnx, had all those issues :-$ 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3809904/Configuration.zip)

Though, still have a problem :-( Connecting the USB cable, recognized as Standard USB serial (Com3) Pronterface-Connect just gives Connecting... till USB cable is disconnected. The same happens if I change the driver as Smoothieware one.

Start to wonder if the motherboard's USB port is damaged???
(wouldn't make any difference that I have both TFT32 & LCD_FOR_MELZI connected ?)

**Comment by p3p** [comment]
Assuming you havn't messed things up by installing multiple drivers (Are you on windows 10? you didn't need any drivers in that case)

If the usb serial is showing up I doubt there is a problem with the port, its more than likely an issue with pronterface not handling 32bit boards properly (they don't restart on serial connection). I'd recommend testing with another host.

**Comment by J-PN** [comment]
I deleted the additional drivers and Yes Win10/x64 selects USB Serial Device (Com3) as ..\usbser.sys 10.0.1.18362

I installed the Repetier:
Connect Com3/115200: No start signal detected - force starting
-and on the bottom line '1 Command Waiting'

:-( Connection icon stays on till I remove the USB cable)

**Comment by p3p** [comment]
In the last config you posted `SERIAL_PORT` is still set to `0`, it should be `-1`, have you fixed that?

if you have could you try a different host program?

**Comment by J-PN** [comment]
Got it:
#define RX_BUFFER_SIZE 1024 // by default this is commented out

**Comment by p3p** [comment]
I can't say I have ever needed to enable that, and have no idea why it would be necessary for you, The USB Serial device does not use that value.

**Comment by J-PN** [comment]
Well, don't know but here's the files working.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3820591/Configuration.zip)

**Comment by p3p** [comment]
you're sure that you needed to set `RX_BUFFER_SIZE`  along with enabling the second serial port? If you are not using the onboard UART as well as the USB serial you should set `#define SERIAL_PORT -1` rather than enabling port 2.

**Comment by J-PN** [comment]
>you should set   rather than enabling port 2.

If I set 
   #define SERIAL_PORT -1
   //#define SERIAL_PORT_2 0
The TFT32 display doesn't respond that's why I didn't notice your comment

Though the TFT32 works when both are enabled
   #define SERIAL_PORT -1
   #define SERIAL_PORT_2 0

AND with
  //#define RX_BUFFER_SIZE 1024 
USB works as  well

**Comment by p3p** [comment]
> AND with
//#define RX_BUFFER_SIZE 1024
USB works as well

I'm glad you have it working but at no point does `RX_BUFFER_SIZE` interact with or is used by the usb serial, all this does it increase the hardware uart rx buffer from the default 256 to 1024, so it's a bit confusing.

**Comment by J-PN** [comment]
Yes, sorry being unclear. I meant that now I could comment out the buffer size line. Why I needed it mean while to get USB working is a bit mystery.
