### ISSUE TITLE
[BUG]  VScode Compilation fails

### ISSUE THREAD

**Issue by hn0550** [MarlinFirmware/Marlin#15694]
### Description
firmware: bugfix-2.0.x today download
In the same configuration
1、use vscode+ PlatformIO  Compile failed in ramps_1.4， Arduino IDE Compile successfully, but LCD  display abnormal.
2、use vscode+ PlatformIO  Compile successfully  in ramps_fd_v2，LCD display normal.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/3775858/config.zip)

**Comment by boelle** [comment]
works fine here
