### ISSUE TITLE
[BUG] ENDSTOP Don't work

### ISSUE THREAD

**Issue by hn0550** [MarlinFirmware/Marlin#15693]
### Description
Hardware:  Ramps FD V2.1
Firmware:   marlin bugfix-2.0x Download version today
fault:  endstop don't work , Open and close does not shut down the motor
[config.zip](https://github.com/MarlinFirmware/Marlin/files/3775813/config.zip)

**Comment by boelle** [comment]
test with M119

put finger on endstop and send M119
remove finger and send M119 again

**Comment by hn0550** [comment]
> test with M119
> 
> put finger on endstop and send M119
> remove finger and send M119 again
-----------------------------------------------
M119 display  open all min is open.  put finger   &  remove finger.
I confirm  endstop is normal
ramps1.4+marlin_bugfix_1.1.x+endstop is normal

**Comment by boelle** [comment]
vil close this one as fixed
