### ISSUE TITLE
[BUG] LCD-Manu- Mixer submenu all info on top of eachother

### ISSUE THREAD

**Issue by 3Dangel** [MarlinFirmware/Marlin#15707]
the Mixer menu after code changes, the toggle % information are all jammed on the left of the screen.
using Reprap full graphic discount LCD.
found the fix by changing the chr length and a value of x for the LCD-Length
Marlin 2 bug fix branch

**menu_mixer.cpp**
~~~~~~~~~~~~~~~~~~

#if DUAL_MIXING_EXTRUDER
 void _lcd_draw_mix(const uint8_t y) {
   char tmp[21]; // "100%_100%"    <============was 10 changed to 21
   SETCURSOR(2, y);
   lcd_put_u8str_P(GET_TEXT(MSG_MIX));
   SETCURSOR(LCD_WIDTH + 5, y);       <================= was -9 changed to +5
   sprintf_P(tmp, PSTR("%3d%% %3d%%"), int(mixer.mix[0]), int(mixer.mix[1]));
   lcd_put_u8str(tmp);

**Comment by boelle** [comment]
maybe send a PR so that all can benefit from your fix

**Comment by 3Dangel** [comment]
Oh! Ok.
Will do there.
Cheers
Thanks

**Comment by 3Dangel** [comment]
PR made
👍 
LCD/Menu/menu_mixer.cpp Lcd rpint wrong coordinate #15715
closing this issue report

**Comment by boelle** [comment]
no lets keep it open until pr is merged

**Comment by 3Dangel** [comment]
Okay! Thanks !!

**Comment by thinkyhead** [comment]
I've merged a patch that may do the trick. Check the latest.

**Comment by 3Dangel** [comment]
Thanks a lot! Will try tonight.
Many thanks to all of you who work on this mega project!!! Kudos!!!!
