### ISSUE TITLE
[BUG] Compile error SKR Mini E3 and 2.0.x

### ISSUE THREAD

**Issue by iLLDrDope** [MarlinFirmware/Marlin#15724]
Here is a copy of my error log. Trying to compile firmware for an SKR Mini E3 board and get the following errors. I've tried downloading Marlin 2.0 from the official git page as well as from BTT with the same results.

Compile error: https://pastebin.com/VG0BCyuP

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

and a small tip is to use a site like paste bin for logs etc

**Comment by iLLDrDope** [comment]
Thank you for fixing the title and moving the log to pastebin. I'm new here.

As requested; 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3786137/Configuration.zip)

**Comment by reloxx13** [comment]
the error is selfexplaining

```
#ifndef MOTHERBOARD
  #define MOTHERBOARD BMOTHERBOARD BOARD_BTT_SKR_MINI_E3_V1_2
#endif
```

```
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V1_2
#endif
```

use the example config to start up
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/config/examples/STM32/STM32F103RE/Configuration.h

**Comment by Lord-Quake** [comment]
If you are using a SKR MINI E3 **V1.2** then the board to select is
`#define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V1_2`
It will compile error free using version:
`#define STRING_DISTRIBUTION_DATE "2019-10-29"`

**Comment by reloxx13** [comment]
@iLLDrDope close this if its fixed!
