### ISSUE TITLE
Smart controller issue with latest Marlin. #1498

### ISSUE THREAD

**Issue by haqnmaq** [MarlinFirmware/Marlin#1573]
So someone else had this problem. It was #1498 , but they closed it without any solutions or possible solutions. I posted some comments in that thread that will hopefully narrow down the problem. Basically the Reprap Discount smart controller does not work anymore with Marlin on my RUMBA. The backlight lights up, but doesnt show any characters. I have more details in the other thread, but I believe this is a bug, based on the fact that I am not the only one experiencing the problem. I tried trouble shooting the problem, but to no avail. Let me know if you need more info.

**Comment by alexborro** [comment]
I have a RUMBA + RRD Smart Controller working fine on the latest Marlin.

Cheers.

Alex.
Em 06/03/2015 03:57, "haqnmaq" notifications@github.com escreveu:

**Comment by haqnmaq** [comment]
Care to share your config file? Particularly pertaining to the lcd. I don't get any errors when compiling, until I un-comment the smart controller. Once I un-comment that, I get the compiling errors and faulty lcd problem. Also, how recently did you update? I don't know how often they update Marlin, but my build of Marlin is only 2 days old.

**Comment by haqnmaq** [comment]
Here is someone else with the same problem. http://forums.reprap.org/read.php?146,445885 Unfortunately, they didn't provide any solutions.

**Comment by alexborro** [comment]
@haqnmaq , what _exactly_ LCD do you have??
The Graphic LCD is one type, the Smart Controller is other. 
Share some pictures and I will try to help you.

Cheers.

Alex.

**Comment by thinkyhead** [comment]
Check against the latest code which just got a potential solution (language defines conflict?). I'm skeptical that it fixes it, but I can check it out later if the problem persists.

**Comment by haqnmaq** [comment]
@alexborro I have the Smart Controller, not the larger Graphic lcd. Thanks for pointing that out, I just realized that the other person had the larger Graphic LCD controller. @thinkyhead I will check that tonight and let you know. Thanks for the help btw.

**Comment by haqnmaq** [comment]
Ok, so I was able to narrow down the problem with a brand new version of Marlin. So by just activating #define REPRAP_DISCOUNT_SMART_CONTROLLER and when #define DISPLAY_CHARSET_HD44780_JAPAN is activated , I don't get any compiling errors. But when I also activate Auto Bed Leveling, I get these compiling errors below.

```
SdFile.cpp.o:(.rodata._ZTV6SdFile+0x8): warning: internal error: out of range error
LiquidCrystal\LiquidCrystal.cpp.o:(.rodata._ZTV13LiquidCrystal+0x4): warning: internal error: out of range error
LiquidCrystal\LiquidCrystal.cpp.o:(.rodata._ZTV13LiquidCrystal+0x6): warning: internal error: out of range error
LiquidCrystal\LiquidCrystal.cpp.o:(.rodata._ZTV13LiquidCrystal+0x8): warning: internal error: out of range error
Wire\Wire.cpp.o:C:\Program Files (x86)\arduino-0023\libraries\Wire/Wire.cpp:256: warning: internal error: out of range error
Binary sketch size: 142382 bytes (of a 258048 byte maximum)
```

If I Deactivate the #define DISPLAY_CHARSET_HD44780_JAPAN setting, I get these errors.

```
expected ')'before 'STR_THERMOMETER'

ultralcd.cpp: In function 'void lcd_control_temperature_menu()':
ultralcd.cpp:791: error: expected `)' before 'STR_THERMOMETER'
ultralcd.cpp:791: error: expected `)' before 'STR_THERMOMETER'
ultralcd.cpp:792: error: expected `)' before 'STR_THERMOMETER'
ultralcd.cpp:792: error: expected `)' before 'STR_THERMOMETER'
ultralcd.cpp:793: error: expected `)' before 'STR_THERMOMETER'
ultralcd.cpp:793: error: expected `)' before 'STR_THERMOMETER'
ultralcd.cpp: In function 'void lcd_control_volumetric_menu()':
ultralcd.cpp:923: error: expected `)' before 'STR_h3'
ultralcd.cpp:923: error: expected `)' before 'STR_h3'
```

**Comment by haqnmaq** [comment]
So it seems to have something to do with the Auto Bed Leveling. It's only when the Auto Bed Leveling and the Smart Controller are activated when I get the compiling errors.

**Comment by nophead** [comment]
Perhaps the code is too big for your chip.

**Comment by haqnmaq** [comment]
Binary sketch size: 83140 bytes (of a 258048 byte maximum)

Doesn't seem like it.

**Comment by thinkyhead** [comment]
@haqnmaq I just tested with the latest code. Starting with the default configuration, I simply enabled `REPRAP_DISCOUNT_SMART_CONTROLLER` with the `JAPAN` character set option. **_No compile errors.**_ I then enabled `ENABLE_AUTO_BED_LEVELING` and got **_no errors**_. The ugly error you're getting is a linker error, and unless it's a "missing symbol" error, it's unlikely to be code-related.

You will get errors if you fail to define either `DISPLAY_CHARSET_HD44780_JAPAN` or `DISPLAY_CHARSET_HD44780_WESTERN`. I am adding an error check now to point this out.

**Comment by haqnmaq** [comment]
Ok, let me go through it again real quick.

**Comment by haqnmaq** [comment]
Huh. I Just enabled the Smart controller and autoleveling, with and without DISPLAY_CHARSET_HD44780_JAPAN or DISPLAY_CHARSET_HD44780_WESTERN enabled and I still get the error on both Arduino 23 and Arduino 1.0.0. I changed nothing else, just those 3 setings from the default and still get the errors.

**Comment by thinkyhead** [comment]
I'm using 1.5.2 at the moment.

**Comment by haqnmaq** [comment]
Ok, let me try that version.

**Comment by thinkyhead** [comment]
Also successfully compiled with 1.0.5... and 1.6.0.

**Comment by haqnmaq** [comment]
It compiled without errors in 1.5.2! Same exact file that I tested in 23 and 1.0.0. I used to remember they reccomended using arduino 23 for Marlin. Has that since changed? Thanks again for your help, I shouldnt have any other problems now, but I will let you know in a few.

**Comment by thinkyhead** [comment]
Arduino 1.0.1 added the **--relax** compiler option, which works around this problem.

I recommend using the most recent version of Arduino that you can for building Marlin.

**Comment by haqnmaq** [comment]
Awesome! It works! My printer is up and running again. Thanks for your help! Sorry for the runaround looking for errors.

**Comment by thinkyhead** [comment]
Not a problem. It was a good chance to make a better error message when the controller ROM isn't selected, and now we now the code is getting too big for old-school Arduino.
