### ISSUE TITLE
[FR] TMC5161 Support

### ISSUE THREAD

**Issue by DroneMang** [MarlinFirmware/Marlin#15730]
Hi,

I am wondering if there will be support added for the new TMC5161 drivers.  They are now available from Bigtreetech on Aliexpress, V1.0. Thank you to all the developers!

Differences to note in comparing 2209 and 5161 data sheets:
https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC5161-datasheet_Rev1.02.pdf
https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2209_Datasheet_V103.pdf
https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC5160_Datasheet_Rev1.10.pdf
5161:
StallGuard2 (older version than 2209)
DcStep™ (I think this would be turned off for 3D printing, 5160 has this feature as well.)
Resonance Dampening for mid-range resonances (Also off to not conflict with Adaptive Step Smoothing in Marlin?)
SPI & Single Wire UART (Same as 5160)
Voltage Range 8 … 40V DC (55V peak) (Lower than the 60V for the 5160)
2-phase stepper motors up to 3.5A RMS coil current (Lower than 5160)
Motion Controller with SixPoint™ ramp as intelligent peripheral (I think this would be turned off for 3D printing?)

2209:
StallGuard4 (This is a higher version than the 5161)
2-phase stepper motors up to 2.8A coil current (peak), 2A RMS
Voltage Range 4.75… 29V DC
Single Wire UART

**Comment by teemuatlut** [comment]
They're the same as 5160 but with internal FETs.

**Comment by boelle** [comment]
will close this one as the support is allready there

**Comment by DroneMang** [comment]
It would be nice to see it listed as one of the possible stepper options,
and for someone to test it eventually.

**Comment by boelle** [comment]
https://github.com/MarlinFirmware/Marlin/pull/15733

should take care of this
