### ISSUE TITLE
[BUG] Firmware update not making any changes

### ISSUE THREAD

**Issue by space-commits** [MarlinFirmware/Marlin#15732]
SKR Mini E3 Marlin 2.0 bugfix, Ender 3.

I've been trying to change the max temp on this board in configuration.h, changing maxtemp 0 to 300.
Just to test I also changed the PLA and ABS preheat presets.

I load the new firmware, a firmware.cur file is created, but my max temp is still 260, and the presets have not changed.

Any ideas?

**Comment by randellhodges** [comment]
You sure you changed the correct configuration file? I had an issue where my changes weren't being applied and it was because I had one of the files open in the /config directory and not the proper one in the /Marlin directory.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
will temp close this one until we have config files attached

please ping me by adding @ in front of my username when configs are attached
