### ISSUE TITLE
[FR] Anycubic Chiron support

### ISSUE THREAD

**Issue by elloder** [MarlinFirmware/Marlin#15742]
Hello everyone,
I wanted to install the TMC 2209 into my Anycubic Chiron, which needs the Marlin 2.0 to run, however, I have not found the Marlin 2.0 for the Chiron anywhere in this zip or on google... do any of you have any ideas if there is a Marlin 2.0 for the Chiron? Also I am a very big beginner in terms of the firmware so I would like to ask the specific differences between Marlin 2.O and the 1.1.
Cheers,
Maty.

**Comment by boelle** [comment]
> Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use the Marlin Firmware forum at http://forums.reprap.org/list.php?415 or the Marlin Facebook Group https://www.facebook.com/groups/1049718498464482/.

ask here first

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
