### ISSUE TITLE
[BUG] [1.1.9] Crash on M24

### ISSUE THREAD

**Issue by GilDev** [MarlinFirmware/Marlin#15743]
### Description

My Creality Ender-3 running Marlin 1.1.9 bugfix reboots when I resume a print from SD card.

### Steps to Reproduce

1. Print something from SD card
2. M25
3. M24

**Expected behavior:** Resume printing.

**Actual behavior:** Printer reboots.

#### Additional Information

[Configuration files](https://github.com/MarlinFirmware/Marlin/files/3795705/Configuration.zip)

**Comment by boelle** [comment]
use 2.0.x instead

**Comment by GilDev** [comment]
Yeah I am now, spent an hour migrating my config yesterday, but haven’t tried these steps yet (and will not be able to in the following weeks).

**Comment by boelle** [comment]
have you been able to test ?

**Comment by GilDev** [comment]
No sorry, still don't have access to my printer for 4 weeks.

**Comment by boelle** [comment]
will close this one, we dont work active on 1.1.9 anymore and 2.0 was just released yesterday
