### ISSUE TITLE
G29 - New homing behaviour?

### ISSUE THREAD

**Issue by avluis** [MarlinFirmware/Marlin#1574]
Just tried newest push on dev branch after merging on my fork for a Prusa i3v 12" with ABL.
Did the G29 command get modified/improved to home to center once done (before it stayed at the last corner where it proved) with the Auto Bed Leveling routine?

In an somewhat related note, I like to extrude a bit of filament (call it a anchor) before starting a print (usually along with a brim and/or skirt) and notice the new G29 behavior - should I modify my slic3r start G-code to move to a corner and do this or will this behavior change (not final, bug, etc)?

**Comment by tonnico** [comment]
Why should the printer move anywhere after a G29?
Use a G1 to move your printer in any edge you want.

**Comment by thinkyhead** [comment]
G29 did just get an update, so it's possible there may be a typo or bad logic. I'd like to hear more info about how it's behaving. Check out the code comments in Marlin_main.cpp in front of the gcode_G29 function for the latest flags. Also watch the serial output when using G29 to see if it reports anything unusual.

**Comment by avluis** [comment]
Got it, trying another print in a few to verify.

Seems like I have to update my probing points:
    `Send: G29`
    `Recv: ?Probe (L)eft position out of range.`
    `Recv: ok`

These were the values that were working before:
   `// set the rectangle in which to probe`
    `#define LEFT_PROBE_BED_POSITION  15`
    `#define RIGHT_PROBE_BED_POSITION 250`
   `#define BACK_PROBE_BED_POSITION  250`
   `#define FRONT_PROBE_BED_POSITION 50`

Is there anything new about how big of an area G29 will accept to probe in, or a way to measure probing points?
Before I forget, I am using OctoPrint as the host - latest dev as well - but that seems to work with no issue if I regress to a prior Marlin commit.

Update:
Looks like that was it, my LEFT_PROBE_BED_POSITION of 15 was too low - weird that it is different now, but new math requires new numbers - and if the new math fixes old issues, then bring the new numbers in I say.
Anyways, simply raising it by 5 puts the probe back where it used to be and the end of the G29 routine puts the extruder back where it used to end (the last probe position - meaning G29 is doing its thing).

I have to say, I love this:
`Bed Level Correction Matrix:`
`1.00 0.00 0.01`
`-0.00 1.00 0.00`
`-0.01 -0.00 1.00`

**Comment by thinkyhead** [comment]
Aha, good that is seems to be working correctly after all. I ought to put in a compile-time check for bad default values so that will be caught early. I should also include the probing limits in the serial error output.

I added new logic for the probe limits, and maybe this is something that needs enhancement too. It won't allow you to move the probe somewhere that would cause the nozzle to fall outside the bed limits. Before now it was not imposing any limits, so it may not respect the XY movement limits during probing.

**Comment by thinkyhead** [comment]
Bed size has been used as the hard limit on movement up to now. If we keep it that way, then you would have to increase the bed size in the firmware to allow the probe to go over the whole bed area. On the other hand, the total freedom of movement of the XY axes could be specified separately, and this would allow full motion. The downside is it would mean a pretty major change to a core configuration option. My current solution of limiting the probe to places where the nozzle is still within the bed may be a minor bummer, but it's consistent with the settings, which reasonably should forbid going past the set limits.

**Comment by avluis** [comment]
Nah - it makes sense to limit to the bed area - keeps things from crashing into each other.
So while it may not be ideal for many other reasons, there really aren't many ways to get around this limitation - after all, a 3D printer's bed has a dimensional limit and most extruder assemblies will be moving about the bed anyways.
In the end, it is nothing major once documentation is updated (provided) and takes into account the appropriate methods to setting probe limits.

**Comment by nophead** [comment]
Note this is not limiting to the bed size as that is not defined in the
firmware but is in the host. It is limiting to the axis limits, which by
definition is as far as the firmware is allowed to move the axes. Some
machines can travel past the bed and others can't.

**Comment by thinkyhead** [comment]
@nophead Ah yes, well I am using `MAX_X_POS`, etc., as the limit for nozzle position, so it sounds like these added sanity-checks are doing the right thing. I actually set my printer's axis limits to the same as my bed size (it can't go much further anyway) so I forgot that it wasn't actually the bed size, and it could differ from the bed size set in the slicer.

**Comment by nophead** [comment]
If it can go further then you should probably make your axis limits bigger as it is advantageous if you have a probe.

**Comment by ntoff** [comment]
> Some machines can travel past the bed and others can't.

Yeah my k8200 used to home to where the nozzle was about 3mm below the bed and about 5mm outside of the print area in X and Y. I had about 220mm of travel in all directions, but the actual print bed itself was still only 200x200.

**Comment by thinkyhead** [comment]
Can someone confirm that it works okay to set `MIN_X_POS` to a negative value? Of course, only bots with a MAX endstop will be able to test this...

**Comment by vandarin** [comment]
Yes, MIN_X_POS is fine being negative. I have 280mm of travel from -17 to +264.

**Comment by thinkyhead** [comment]
@vandarin Excellent. I guess that's the proper solution for users experiencing issues because of the new sanity-checking. Maybe I can update the error messages to point this out.

**Comment by alexborro** [comment]
I have negative X values even homing to X-Min. My X range is -4 to 325.

Working perfect.

Cheers.

Alex.
Em 09/03/2015 14:47, "Scott Lahteine" notifications@github.com escreveu:

**Comment by alexborro** [comment]
Scott, let's put all preprocessor sanity check in a separate file.. To make
config files clean.

Cheers.

Alex.
Em 10/03/2015 01:00, "Alex Borro" alexborro@gmail.com escreveu:

**Comment by thinkyhead** [comment]
@alexborro Gladly! I will roll a PR soon.

**Comment by boelle** [comment]
:-D shold this one stay open until the PR is merged?

**Comment by thinkyhead** [comment]
I have the sanity check issue in mind, meanwhile the original issue is all set.
