### ISSUE TITLE
[BUG] AVR2560 home with interrupt has been broken

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#15750]
There is something in recent PR that broke homing with interrupt with AVR.
I have endstops on X and Y (standard inputs) and Y fails...
M119 report correctly triggered but Y move to negative and never stops...

I went back to c80eda073 and there it works. I strongly suppose problem is in 35b1149d9 (Patch es int tests for Arduino 1.8.10)

I'll investigate....

**Comment by GMagician** [comment]
```c++
if (moreDigitalPinToPCMSK(pin) != nullptr) {
```
whill never return `nullptr`

**Comment by GMagician** [comment]
I think I have to read mega2560 datasheet to understand changes...

**Comment by GMagician** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3797357/Configuration.zip)

**Comment by GMagician** [comment]
Maybe better to reopen until merge has been done....

**Comment by minorminer59** [comment]
I can confirm this behavior. When homing the bed continues to hit Y at the Min.

**Comment by GMagician** [comment]
@minorminer59 you can use my PR to solve it, waiting it to be merged
