### ISSUE TITLE
[BUG] Sbase: No communication via hardware serial 2.

### ISSUE THREAD

**Issue by karabas2011** [MarlinFirmware/Marlin#15751]
Last marlin 2.0 on MKS Sbase.1
hardware serial Aux1 connected to raspberry and proved to work on smoothie firmware
Problem: 
No communication at any speed. No garbage on screen, no anything.
Configiration.h:

#define SERIAL_PORT -1
#define SERIAL_PORT_2 0
#define BAUDRATE 250000

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by Bergerac56** [comment]
Yes, it will be easier with configuration files ;)
I have a MKS TFT32 connected to PORT_2 of the SBASE and it works without any problem with the last bugfix release at least.

**Comment by karabas2011** [comment]
Do you set pins for AUX1 or comment them out in SBASE_PINS.h ?

**Comment by Bergerac56** [comment]
No I use the pins definitions as they are.

**Comment by Bergerac56** [comment]
Please post your config files and your pins.h file so I can compare them with mine

**Comment by karabas2011** [comment]
I found my problem, last hardware changes: wrong wireing
