### ISSUE TITLE
[BUG] Compilation Error (2.x)

### ISSUE THREAD

**Issue by psavva** [MarlinFirmware/Marlin#15763]
I think this may have broken LPC1768

https://github.com/MarlinFirmware/Marlin/pull/15762

In file included from Marlin\src\HAL\HAL_LPC1768\HAL.cpp:26:
Marlin\src\HAL\HAL_LPC1768\../shared/Delay.h: In function 'void enableCycleCounter()':
Marlin\src\HAL\HAL_LPC1768\../shared/Delay.h:49:7: error: 'DWT' was not declared in this scope
       DWT->CYCCNT = 0;
       ^~~
Marlin\src\HAL\HAL_LPC1768\../shared/Delay.h:50:20: error: 'DWT_CTRL_CYCCNTENA_Msk' was not declared in this scope
       DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
                    ^~~~~~~~~~~~~~~~~~~~~~
Marlin\src\HAL\HAL_LPC1768\../shared/Delay.h:50:20: note: suggested alternative: 'MPU_CTRL_HFNMIENA_Msk'
       DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
                    ^~~~~~~~~~~~~~~~~~~~~~
                    MPU_CTRL_HFNMIENA_Msk
Marlin\src\HAL\HAL_LPC1768\../shared/Delay.h: In function 'volatile uint32_t getCycleCount()':
Marlin\src\HAL\HAL_LPC1768\../shared/Delay.h:53:61: error: 'DWT' was not declared in this scope
     FORCE_INLINE volatile uint32_t getCycleCount() { return DWT->CYCCNT; }
                                                             ^~~
Compiling .pio\build\LPC1768\src\src\HAL\HAL_LPC1768\u8g\u8g_com_HAL_LPC1768_hw_spi.cpp.o
*** [.pio\build\LPC1768\src\src\HAL\HAL_LPC1768\HAL.cpp.o] Error 1

Config Attached: 

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/3800155/Configs.zip)

**Comment by buddybu** [comment]
I am also seeing this issue.  I can provide my configs if necessary.

If I undo this change in delay.h
  #if WITHIN(__CORTEX_M, 3, 7)
and replace it with 
  #if __CORTEX_M == 7

and this change in hal_stm32\hal.cpp:
#if (defined(__arm__) || defined(__thumb__)) && WITHIN(__CORTEX_M, 3, 7)
and replace it with
#if (defined(__arm__) || defined(__thumb__)) && __CORTEX_M == 7

I still cannot build, but instead get the error:
Set MOTHERBOARD to an LPC1768-based board when building for LPC1768.  

My MOTHERBOARD setting is:
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_BIGTREE_SKR_V1_3
#endif



[configs.zip](https://github.com/MarlinFirmware/Marlin/files/3800164/configs.zip)

**Comment by psavva** [comment]
Once I revert f0d952d33ac7b2fb491fc356ce1d399f4460d5e4  then all is good.
I'm looking at the updated implementation and logic looks good.
How does WITHIN work?  Maybe the root cause of the issue?

In macros.h this is the definition of WITHIN
#define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))

That would better been defined as BETWEEN, rather than WITHIN...

**Comment by randellhodges** [comment]
There is debate on the interwebs if BETWEEN is inclusive. It boils down to general usage is inclusive, aka "number between 1 and 10" but usually with physical objects, it isn't inclusive.

The choice to call it WITHIN was probably a choice to side step the ambiguity of inclusive since it implies inclusive. At least, that is how I read it. I could also be 100% wrong :)
