### ISSUE TITLE
[QUESTION] MMU2 Ramming Sequence accept G4 Pxx (Pause) 

### ISSUE THREAD

**Issue by xStolix** [MarlinFirmware/Marlin#15774]
Can MMU2.cpp be edited to accept a pause command in the Ramming Sequence? 

" { G4 , P2500 }, \ " to the Ramming Sequence 

Adding a pause to the MMU2 Ramming Sequence would allow tuning of the filament points when using the LCD to change filaments.

**Comment by boelle** [comment]
please ask here instead

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y

the issue list is for bugs and fr's only
