### ISSUE TITLE
[BUG] Compilation fails with DAC steppers and screen enabled

### ISSUE THREAD

**Issue by 0r31** [MarlinFirmware/Marlin#15803]
Hi all,

Please find below a bug i suspect in Marlin 2.0 current revision.

Regards,
Orel

### Description

As stated in the issue title, the compilation fails when DAC steppers and screen features are enabled.

### Steps to Reproduce

Configuration files: [Marlin_config.zip](https://github.com/MarlinFirmware/Marlin/files/3804767/Marlin_config.zip)

From the current revision of **bugfix-2.0.x** branch, just change the **MOTHERBOARD** to _BOARD_RIGIDBOARD_V2_ for instance (a board for which DAC steppers are enabled) and uncomment **REPRAP_DISCOUNT_SMART_CONTROLLER** in _Configuration.h_. Then compile using the default platformio environment.

**Expected behavior:** Compilation success.

**Actual behavior:** Compilation failure. See below for compilation log.

#### Additional Information

Compilation log: https://pastebin.com/eXsx7AWy

**Comment by 0r31** [comment]
Hi again,

First of all, thanks to @boelle to add the compilation log to pastebin. I was aware that putting a log "as it is" could be annoying but i have no clue on what to do with logs in the bug template.

Regarding the potential bug, i guess the issue is around the **GET_TEXT** macro or the way the **EDIT_ITEM** macro handles labels or the way **this label is built**...

I am fine to submit a pull request, but i want to be aligned with the coding rules...
It is easy to get rid of that bug in changing the _LABEL_ argument of this **EDIT_ITEM** call to a "valid" one, but it is not the right way to fix it.

Regards,
Orel

**Comment by boelle** [comment]
@dagorel did you make a PR to fix this?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by 0r31** [comment]
Hi @boelle ,

Actually it can be solved in defining new labels for each axis (MSG_DAC_PERCENT_X, MSG_DAC_PERCENT_Y, MSG_DAC_PERCENT_Z) and use MSG_DAC_PERCENT_##A in the EDIT_DAC_PERCENT macro. But i am not happy with this solution so i try to find another one before proposing a PR.

Regards,
Orel

**Comment by boelle** [comment]
@dagorel since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by 0r31** [comment]
Hi @boelle ,

It is the very same with the new 2.0 branch so i submit a pull request on the bugfix-2.0.x branch.

Regards,
Orel

**Comment by boelle** [comment]
:-) great, nice when people contribute

**Comment by boelle** [comment]
let hope @thinkyhead hits merge soon
