### ISSUE TITLE
[BUG] Bilinear_Subdivision cause problems with overcompensating ABL values

### ISSUE THREAD

**Issue by opiswahn** [MarlinFirmware/Marlin#15818]
### Description

**EDIT**
I'm fairly certain the cause here is Bilinear_Subdivision. With it enabled, the ABL probing is way off, producing an extremly offset mesh, that seems also to be overcompensated while printing, causing the nozzle to drop into the print cause the printer thinks the bed is off by more than 3mills there...
With Bilinear_Subdivision disabled, the ABL probing is very flat(as expected) and it prints very nicely.

I'm on a Ender-2 with a SKR E3 Mini v1.2 board. With the current Marlin version and ABL, I get some strange behavior while printing. 
On start, homing, ABL (with a 3dTouch) does it's  thing, and it begins to print. The first 1 or 2 layers look very good, but then is suddenly drops the nozzle while printing for a short period and backs up again.
Looks some kind of an inverted Z-Hop, the palces where this happens are pretty consistent through the print and through different print attempts.
I can only print 4 layers or so as the nozzle seems to drop lower every time and gets burried within the print at some point where I have to abort.

Does this sound familiar to anyone?

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3815890/Configuration.zip)

**Comment by boelle** [comment]
maybe ask here

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y

also

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by opiswahn** [comment]
@boelle uploaded the config files

**Comment by opiswahn** [comment]
I'm pretty sure it has to do something with ABL... this is the current mesh it produces:
![image](https://user-images.githubusercontent.com/5494461/68323788-69656a00-00c6-11ea-8023-bf70a3dc59b2.png)

With Marlin 1.1.9 some days ago it was nearly complete flat (sadly i have no visualization of that anymore), with the same sensor and same other hardware besides the board.

The movement it makes during the print match the topology, but the correction movements are rather harsh...

**Comment by opiswahn** [comment]
so... anything?

**Comment by boelle** [comment]
nope i dont have the issue myself and i just updated 3 days ago

**Comment by opiswahn** [comment]
It has definitly something to do with Bilinear_Subdivision... as soon as i disable it everything is ok. Activated with no matter what setting, the mesh is way off and extremly overcorrected in printing...

**Comment by shitcreek** [comment]
I think @akaJes is responsible for `Bilinear_Subdivision`, maybe he/she could chime in.

**Comment by boelle** [comment]
@akaJes ??

**Comment by tpruvot** [comment]
overcompensating ? i see the opposite here... its like if the mesh levels were 10x more flat than before... the xyze struct change, made in the end of september. to be more clear... the Z is compensating less than it should... i believe

**Comment by opiswahn** [comment]
Well, maybe it's manifesting differently on different setups... mine is definitly overcompensating, or better the mesh is overexaggerated...

**Comment by boelle** [comment]
@opiswahn btw what version of marlin are you using?

**Comment by opiswahn** [comment]
@boelle the latest one 2.0.x. Just updated from repo, faulty behavior remains...

**Comment by boelle** [comment]
@Roxy-3D any clue what could be wrong here?

**Comment by boelle** [comment]
@opiswahn since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by boelle** [comment]
is the issue still the same with all the updates in the last 33 days?

**Comment by boelle** [comment]
btw, who can confirm there is an issue? use the same configs as OP and the same hardware if possible

**Comment by opiswahn** [comment]
I'm still having the problems... nothing has changed here sadly

**Comment by boelle** [comment]
@opiswahn still no good news with the latest bugfix 2.0.x?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
