### ISSUE TITLE
[BUG] SKR mini E3 v1.2 compile error

### ISSUE THREAD

**Issue by mpguerreiro** [MarlinFirmware/Marlin#15826]
### Description

I just received my SKR mini E3 v1.2 and I want to change some parameters in the firmware for a Ender 5, but when compiling it always gives the same error! (error log below) I've spent hours and got nothing!!

### Steps to Reproduce
 
Fleshing a new Firmware

**Expected behavior:**

A new firmware to be flashed.

**Actual behavior:**
In the end: STM32F103RC_bigtree      FAILED 

#### Additional Information

![image](https://user-images.githubusercontent.com/56567047/68346039-f7ebe280-00ea-11ea-99a3-d6d41caa9b7f.png)

**Comment by thisiskeithb** [comment]
Read the error message. It’s telling you to install git.

**Comment by mpguerreiro** [comment]
> Read the error message. It’s telling you to install git.

Thank you a tone, problem solved!!
