### ISSUE TITLE
[BUG] [Solved] Error LCD

### ISSUE THREAD

**Issue by el-quique** [MarlinFirmware/Marlin#15825]
### Description

The last marlin generates an error on the LCD Full Graphics. I try Kimbra and it works well.
I don't want to use Kimbra it was just a test

### Steps to Reproduce
Marlin 2.0 
Board Rumba (8 bits)
Delta Printer: Geeetech Rostock 301
Heather Parallel active
Bltouch actie
Mixer Extruder (3 steper)
compiling with arduino ide 1.6.13 and 1.8.10

THX
Error in LCD
![eb606e06-522f-4bc4-a585-32547d720f4e](https://user-images.githubusercontent.com/5359805/68346151-227d7180-00d2-11ea-9e33-4bcae1485b22.jpeg)

No error LCD
![f28ce00a-97df-436e-ab9a-8599c05123b3](https://user-images.githubusercontent.com/5359805/68346074-f235d300-00d1-11ea-9a37-b7a4ecca5844.jpeg)

**Comment by el-quique** [comment]
![eb606e06-522f-4bc4-a585-32547d720f4e](https://user-images.githubusercontent.com/5359805/68346151-227d7180-00d2-11ea-9e33-4bcae1485b22.jpeg)

**Comment by el-quique** [comment]
Maybe errors in pins_runba.h?

**Comment by ellensp** [comment]
This isn't a bug, its the slow LCD supplied with your printer.  Marlin tries to push the LCD as fast as it can so it doesn't have to waste cpu cycles updating the LCD vs doing other important tasks.
add #define ST7920_DELAY_3 DELAY_NS(63) to your configuration.h (this is the default value for a 16mhz atmega based controller)
Try larger values than 63, many report 125 works on horridly slow LCD's

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by 3Dangel** [comment]
same as I suggested for another reported issue

#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER /
#define ST7920_DELAY_1 DELAY_NS(125) //these help keep the display from being weird
#define ST7920_DELAY_2 DELAY_NS(125)
#define ST7920_DELAY_3 DELAY_NS(125)
#endif

hope this helps

**Comment by el-quique** [comment]
> Configurations, please
> Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
> requested in the Issue template) and drop them into your next reply.
> We'll check them over and see if anything is amiss.

[Marlin_2.0-10-11-19.zip](https://github.com/MarlinFirmware/Marlin/files/3822028/Marlin_2.0-10-11-19.zip)

**Comment by el-quique** [comment]
> same as I suggested for another reported issue
> 
> #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER /
> #define ST7920_DELAY_1 DELAY_NS(125) //these help keep the display from being weird
> #define ST7920_DELAY_2 DELAY_NS(125)
> #define ST7920_DELAY_3 DELAY_NS(125)
> #endif
> 
> hope this helps

Solved. It's strange because i use Marlin 1.1.x until 2.0 (September) I never put those options and never problems. Thank you very much for your time

**Comment by ruggb** [comment]
see #15745 and #15833

**Comment by el-quique** [comment]
> see #15745 and #15833

Thx. Solution with 3Dangel comment.
