### ISSUE TITLE
[STYLE] Repeated if condition

### ISSUE THREAD

**Issue by Aldude** [MarlinFirmware/Marlin#15820]
In Marlin/Configuration_adv.h line 1376:

`#if PROBE_SELECTED && !IS_KINEMATIC && !IS_KINEMATIC`

**Comment by thisiskeithb** [comment]
Are you using the latest version of `bugfix-2.0.x`? It was fixed in https://github.com/MarlinFirmware/Marlin/commit/9dcccc11bae4fea52a9dc267d10f97e66282a718:

https://github.com/MarlinFirmware/Marlin/blob/f5b5b9e8ec17fd91b684861e760cf4882609c5bd/Marlin/Configuration_adv.h#L1392

**Comment by boelle** [comment]
is this a bug or just information?

**Comment by boelle** [comment]
will close this one as it fixed in 2.0.x

furthermore the details in the OP is rather "slim", no problem is described, no config.... 
everyone is left to wonder what the idea of the post is
