### ISSUE TITLE
[BUG] (MAXBEDTEMP HALTED after reflashing)

### ISSUE THREAD

**Issue by RMN9** [MarlinFirmware/Marlin#15834]
Hello. Today i take last version Marlin 2.x form github (Latest commit (https://github.com/MarlinFirmware/Marlin/commit/47805e18f85d7220332a84cfdbe7174cd44d9760))

Сonfigured files for my printer: Ender-3, SKR 1.3, TMC2209
Immediately after booting i see MAXTEMP BED HALTED.
If i using 
#define BOGUS_TEMPERATURE_GRACE_PERIOD 2000

Printer starting okay, and temp show correctly. 23-24 celsium. Not show another values 50-60-70 how it was in previous bug reports.

Same was here https://github.com/MarlinFirmware/Marlin/issues/14139
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3820844/Marlin.zip)

**Comment by Patag** [comment]
I confirm the bug... and the fix !
BTW, fix or workaround ?

**Comment by p3p** [comment]
Updating the framework should install `0.2.1`, that hopefully fixes the issue you shouldnt need a grace period if you didn't previously, https://github.com/MarlinFirmware/Marlin/pull/15719 increases how many bits of the adc reading Marlin can use and in some cases its causing problems.

I'm still looking into if it causes anything else weird, if you have a heart beat led you will see it flashing a lot faster for instance, because the temperature ISR is running fully more often.

**Comment by RMN9** [comment]
> 0.2.1

i Don't unsderstand what the framework?
installed
Vusial Studio 1.3.92
NXP Arduino LPC176x 0.1.0
TMCstepper 0.5.2

**Comment by ManuelMcLure** [comment]
Just delete the .pio folder and rebuild. That will pull the new framework.

**Comment by RMN9** [comment]
> Just delete the .pio folder and rebuild. That will pull the new framework.

Done. After this i start build.
`PACKAGES: framework-arduino-lpc176x 0.2.0, toolchain-gccarmnoneeabi 1.80201.190214 (8.2.1)`

**Comment by p3p** [comment]
> NXP Arduino LPC176x 0.1.0

That is the platform that builds Marlin for LPC176x, it installs the appropriate Arduino framework, how to update platformio depends on how you are using it, 

`platformio update` from the terminal, clicking on the alien symbol in VSCode and clicking `Update All` in the quick access menu, deleting the platformio cache folders.

PlatformIO should keep things upto date itself but I'm not sure if it checks every build.

**Comment by RMN9** [comment]
@p3p , i found your release
`0.1.0 Release released 4 days ago`
`framework-arduino-lpc176x 0.2.0 (installed)`

**Comment by ManuelMcLure** [comment]
@p3p Do you need to make a 0.1.1 release that fetches 0.2.1? Or change platformio.ini to fetch from master?

**Comment by p3p** [comment]
No the platform doesn't need a new release, It should be pulling down the updated framework as I've updated the remote(hosted on github) package manifest.

**Comment by RMN9** [comment]
1. Deleted .pio
2. Deactivated BOGUS_TEMPERATURE_GRACE_PERIOD 
3. Compiled
4. Flashing
5. MAXTEMP: Bed PRINTER HALTED.

11 oct 2019 i taken source code and compiled for same board only with TMC2208. Error with max temp not was present.

**Comment by p3p** [comment]
@407s what is the output from `platformio update`

**Comment by ManuelMcLure** [comment]
I just downloaded https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.0.zip as specified in platformio.ini and the manifest has:
```
{
    "framework-arduino-lpc176x": [
        {
            "url": "https://github.com/p3p/pio-framework-arduino-lpc176x/archive/0.2.0.zip",
            "version": "0.2.0"
        }
    ]
}
```
so there's something wrong here. Maybe a Github problem?

**Comment by ManuelMcLure** [comment]
Looks like platformio.ini should list
https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/release.zip
instead...

**Comment by p3p** [comment]
The platform uses the live (online) release branch manifest file, not the downloaded version one.

No the platformio.ini is correct.

**Comment by RMN9** [comment]
> @407s what is the output from `platformio update`

```
PS C:\Marlin\1.3-2209-BL\Marlin> platformio update
Updating tool-scons                      @ 2.20501.190826 [Up-to-date]
Updating tool-unity                      @ 1.20403.0      [Up-to-date]
Updating contrib-pysite                  @ 2.27.191017    [Up-to-date]
Updating contrib-piohome                 @ 2.3.3          [Up-to-date]

Platform Manager  
================  
Platform Atmel AVR
--------
Updating atmelavr                        @ 1.15.0         [Up-to-date]
Updating toolchain-atmelavr              @ 1.50400.190710 [Up-to-date]
Updating framework-arduinoavr            @ 4.1.2          [Up-to-date]

Platform NXP Arduino LPC176x
--------
Updating nxplpc-arduino-lpc176x          @ 0.1.0          [Detached]
Updating toolchain-gccarmnoneeabi        @ 1.80201.190214 [Up-to-date]
Updating framework-arduino-lpc176x       @ 0.2.0          [0.2.1]
Uninstalling framework-arduino-lpc176x @ 0.2.0:         [OK]
PackageManager: Installing framework-arduino-lpc176x @ 0.2.1
Downloading  [####################################]  100%
framework-arduino-lpc176x @ 0.2.1 has been successfully installed!
Uninstalling framework-arduino-lpc176x @ 0.1.3:         [OK]

Platform NXP Arduino LPC176x
--------
Updating nxplpc-arduino-lpc176x          @ 0.0.2          [Detached]
Updating toolchain-gccarmnoneeabi        @ 1.80201.190214 [Up-to-date]
Updating framework-arduino-lpc176x       @ 0.2.1          [Up-to-date]

Platform ST STM32
--------
Updating ststm32                         @ 5.7.0          [Up-to-date]
Updating tool-stm32duino                 @ 1.0.2          [Up-to-date]
Updating framework-arduinoststm32-maple  @ 1.10000.190819 [Up-to-date]


Library Manager
===============
Library Storage: C:\Users\Yuriy\.platformio\lib
Updating TMCStepper                      @ 0.5.2          [Up-to-date]
```

**Comment by p3p** [comment]
> Uninstalling framework-arduino-lpc176x @ 0.2.0:         [OK]
PackageManager: Installing framework-arduino-lpc176x @ 0.2.1
Downloading  [####################################]  100%

That's all you needed to do ^^

**Comment by RMN9** [comment]
Oooooohhh yes. Problem fixed. 

Sry for my english. He stayed on level "Edinburgh  the capital of Scotland".

`PACKAGES: framework-arduino-lpc176x 0.2.1, toolchain-gccarmnoneeabi 1.80201.190214 (8.2.1)  `

**Comment by sbaeder** [comment]
Not really intuitive to find this information when trying to compile and use the 11/7 build...Even after removing the .pio folder, platformio re-used the 0.2.0 version of the framework.

Eventually, removing all the platformio extensions related to the LPC176x caused it to be proplerly updated...

**Comment by J-charles-C** [comment]
I,

I have this problem and I did not understand how to solve it.


Imac-5K-de-Jean-Charles:Marlin-bugfix-08-11-19 Godjc$ platformio update
Updating tool-unity                      @ 1.20403.0      [Up-to-date]
Updating tool-pioplus                    @ 2.5.8          [Up-to-date]
Updating contrib-pysite                  @ 2.27.191017    [Up-to-date]
Updating contrib-piohome                 @ 3.0.0          [Up-to-date]
Updating tool-scons                      @ 2.20501.190826 [Up-to-date]

Platform Manager
================
Platform Atmel AVR
--------
Updating atmelavr                        @ 1.15.0         [Up-to-date]
Updating toolchain-atmelavr              @ 1.50400.190710 [Up-to-date]
Updating framework-arduinoavr            @ 4.1.2          [Up-to-date]

Platform NXP LPC
--------
Updating nxplpc                          @ 4.5.0          [Up-to-date]

Platform NXP Arduino LPC176x
--------
Updating nxplpc-arduino-lpc176x          @ 0.1.0          [Detached]
Updating toolchain-gccarmnoneeabi        @ 1.80201.181220 [Up-to-date]
Updating framework-arduino-lpc176x       @ 0.2.1          [Up-to-date]


Library Manager
===============
Library Storage: /Users/Godjc/.platformio/lib
Updating TMC2130Stepper                  @ 2.5.1          [Up-to-date]
Imac-5K-de-Jean-Charles:Marlin-bugfix-08-11-19 Godjc$ 

thanks

**Comment by RMN9** [comment]
Del folder with name .pio and then

Updating framework-arduino-lpc176x       @ `0.2.1 `         [Up-to-date]

But i see you already updated. Try uncomment BOGUS in pins of board for detection of problem.
`#define BOGUS_TEMPERATURE_GRACE_PERIOD`

![Screenshot_111](https://user-images.githubusercontent.com/12804127/68502540-b33e8380-0271-11ea-9fe5-900ae667b379.png)

**Comment by RMN9** [comment]
> find this information

i just do `platformio update`, and got `0.2.1`

**Comment by J-charles-C** [comment]
I,

I have already update.

**Comment by shitcreek** [comment]
@J-charles-C make sure you also deleted the .pio folder then relaunch vscode. Had this very issue and these steps resolved it.
