### ISSUE TITLE
[BUG] Marlin bugfix2.0 will not compile when a chamber is enabled

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#15861]
### Description

If you enable a heated chamber in marlin2 it  fails to compile
Marlin/src/gcode/temperature/M141_M191.cpp: In static member function 'static void GcodeSuite::M191()':
Marlin/src/gcode/temperature/M141_M191.cpp:70:5: error: 'lcd_setstatusPGM' was not declared in this scope 

### Steps to Reproduce
**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files. 
Most frustrating request, it is irreverent to this error.
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/3828339/configs.zip)

1. #define TEMP_CHAMBER_PIN P0_25_A2   //on my skr 1.3
2. #define HEATER_CHAMBER_PIN    P2_04  //just a test pin.
3. #define TEMP_SENSOR_CHAMBER 1 

Attempt to compile, its fails 

**Expected behavior:**

It should compile

**Actual behavior:** 

You get this error
Marlin/src/gcode/temperature/M141_M191.cpp: In static member function 'static void GcodeSuite::M191()':
Marlin/src/gcode/temperature/M141_M191.cpp:70:5: error: 'lcd_setstatusPGM' was not declared in this scope 

#### Additional Information

This is trying to reference 1.1.x code that is no longer present in 2.0
This also highlights another error which I will document shortly.

Updating lcd_setstatusPGM to ui.set_status_P in  Marlin/src/gcode/temperature/M141_M191.cpp fixes it. PR to follow.

**Comment by randellhodges** [comment]
I can confirm the compile error happens when you define a HEATER_CHAMBER_PIN. I had the others defined and didn't get error until I defined that one.
