### ISSUE TITLE
No Fan Adjustment? Bedtemp only 65?  please help the newbee

### ISSUE THREAD

**Issue by hitchhiker85** [MarlinFirmware/Marlin#15864]
Hi!

I am absolute new in this 3d printing game :)

I own a Ender2

After looking some Youtube videos i print the FreeABL mounts and flash bootloader and Marlin 2.0 via PlatformIO on VScode.

now i got some problems!

My K-Fan cant adjust now via Display an knob

My Bedtemp. for ABS can only adjust to 65.

can someone please help?

I have the sanguino mcu on it.

I dont know what i must change to get higher Bedtemp and K Fan adjustment direct on the Ender2.

Thanks

**Comment by swilkens** [comment]
Since you used PlatformIO to compile a new firmware for your printer, you must have made some changed to the `configuration.h` and `configuration_adv.h` files.

Please find those files, add them to a .zip file and post that here so we can have a look what you did :)

I also want to point out that these sort of "beginner" questions are usually best asked on the social media channels.

1. The official Marlin discord channel: https://github.com/MarlinFirmware/Marlin/issues/11846
2. The Marlin Facebook Group
3. Reddit's /r/3dprinting subreddit or /r/ender2 subreddit :)

**Comment by thisiskeithb** [comment]
> Have you read Marlin's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md
> 
> Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use the Marlin Firmware forum at http://forums.reprap.org/list.php?415 or the Marlin Facebook Group https://www.facebook.com/groups/1049718498464482/.
> 
> Before filing an issue be sure to test the 1.1 and/or 2.0 "bugfix" branches to see whether the issue is already addressed.

**Comment by hitchhiker85** [comment]
sorry!  i go to the forum! facebook is not mine!

thanks for help!

**Comment by swilkens** [comment]
Good luck :) !

Please remember to close issue reports when your question has been answered.

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
