### ISSUE TITLE
FIX_MOUNTED_PROBE Disables Z Sensorless Homing (2.0 "bugfix")

### ISSUE THREAD

**Issue by Totbenru** [MarlinFirmware/Marlin#15879]
I've recently converted to TMC2130 Sensorless homing on the Z Axis on all of my i3 machines in the print farm (Print head safe homed outside of Bed). 

Coming from an inductive probe, I was thinking I could still use the "Z Offset" from the LCD to conveniently make adjustments to the Z every now and then (after changing nozzles etc.), but enabling FIX_MOUNTED_PROBE disables the Z Sensorless Homing. Commenting out FIX_MOUNTED_PROBE makes Z sensorless work again, but of course removes the "Z Offset" adjustment from the LCD menu. 

For now I just use Home offset on the Z axis to set nozzle height, but this is inconvenient compared to the fast and precise Z Offset adjustment from the LCD. Thanks in advance.

P.S. For those wondering how and why Sensorless Homing on Z:

- Z is safe homed using hard stops with the print head outside the bed with the nozzle tip just 0.6mm below the surface of the bed. 
- I've never used Auto leveling as I tram my print farm beds (ultra flat Carbon Fiber) using a Test Indicator. Inductive sensors were just used to set distance of nozzle to bed.
- 90% of my print farm's prints are in ABS and all of them have enclosed chambers. Unless you use PINDA probes, Inductive Sensors have a habit of drifting sensing distance based on ambient temp (up to +/- 80 microns). Sensorless Homing on the Z simplifies wiring, operational reliability and is impervious to ambient temperature.

**Comment by boelle** [comment]
> FIX_MOUNTED_PROBE

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
