### ISSUE TITLE
[BUG] SKR-MINI-E3-V1.2 TouchMi -SDCARD

### ISSUE THREAD

**Issue by kramer04** [MarlinFirmware/Marlin#15895]
if I set the Z-offset for the TouchMi and save it, as soon as I start printing the printer freezes

### Steps to Reproduce
Go to configuration --> TouchMi --> Init TouchMi --> Probe Z Offset --> Save
 launch a print and the printer freezes
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3843031/Configuration.zip)

Expected to print after probing Z Offset

**Actual behavior:** [What actually happens]
The printer freezes and i've to to download again the firmware

Additional information

if i don't save i can launch a print

**Comment by damvcoool** [comment]
It maybe a Problem with the Virtual EEPROM, try modifying

Marlin/src/pins/stm32/pins_BTT_SKR_MINI_E3_V1_2.h

line 38
#define EEPROM_START_ADDRESS uint32(0x8000000 + 256 * 1024 - 2 * EEPROM_PAGE_SIZE)
to 
#define EEPROM_START_ADDRESS uint32(0x8000000 + 256 * 2048 - 2 * EEPROM_PAGE_SIZE)

**Comment by kramer04** [comment]
Now it seems that's ok.
No freeze

**Comment by boelle** [comment]
will close as fixed



> Now it seems that's ok.
