### ISSUE TITLE
[BUG] AUTO_BED_LEVELING_3POINT movement to far

### ISSUE THREAD

**Issue by schmerzlich** [MarlinFirmware/Marlin#15892]
Marlin-Dev2.1.x
Anet A8 Plus

AUTO_BED_LEVELING_3POINT ignores PROBE_OFFSET and point override (PROBE_PT_x_X) settings.

X - Axis runns in hard stop at X-max position.

The only way to set up usable probing positions is by setting the BED_SIZE smaller (as it is) or to set the MIN_PROBE_EDGE larger. But thats not the way of proper usability.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by shitcreek** [comment]
Is your machine a delta/scara?

**Comment by sjasonsmith** [comment]
> Marlin-Dev2.1.x

This branch isn't currently up to date. You should ignore it and keep using bugfix-2.0.x for now.
Can you try it with the latest state of bugfix-2.0.x and report back if you still have the issue? If yes, be sure to post configs.

You will have to patch up your configs a bit. Definition of probe offsets and points has all changed versus what you are using now.

Be sure to use the latest state of bf2. A change was committed 15 hours ago for one issue impacting non-mesh bed leveling and probe offsets.

**Comment by schmerzlich** [comment]
Hello sjasonsmith,
thank you, I'll try this evening and give you a report. 

Hey shitcreek, no it's not a delta.

**Comment by boelle** [comment]
what report do you have for us?

**Comment by schmerzlich** [comment]
I am sorry but everybody of my family is actually ill so I havent got any
time to analyse the problem so far.

Bo Herrmannsen <notifications@github.com> schrieb am Sa., 16. Nov. 2019,
11:05:

**Comment by boelle** [comment]
no problemo, have been ill myself with stomac flu

**Comment by sjasonsmith** [comment]
@schmerzlich, I'm sorry to hear your family was sick. I suggest we have @boelle (or you) close this issue, and it can be re-opened or a new one can be created if it doesn't work with the bugfix-2.0.x branch.

I have very recently tested AUTO_BED_LEVELING_3POINT on bugfix-2.0.x with and without custom probe points, and I believe it will work for you from that branch.

**Comment by boelle** [comment]
as @sjasonsmith says we can reopen this one if it does not work
