### ISSUE TITLE
[BUG] Ramps + RepRap Discount Smart Controller: Rotary Encoder not working

### ISSUE THREAD

**Issue by rocketkittens** [MarlinFirmware/Marlin#15896]
### Description
 Ramps + RepRap Discount Smart Controller:  
  **Rotary Encoder click opens menu, but rotating encoder doesn't move cursor**

### Steps to Reproduce
Configuration.h https://pastebin.com/raw/3Wifr32y  
Configuration_adv.h https://pastebin.com/raw/i3ejKMBs
Powered by: USB or 12v + 5v to Arduino

**Expected behavior:**
Rotating the rotary encoder on RepRap Discount Smart Controller should move cursor in the menu.

**Actual behavior:**
Cursor does not move when rotating the rotary encoder. However pressing/clicking the rotary encoder opens the LCD menu.

If this is not a software issue, how can i debug the rotary encoder component - check continuity while rotating, if i'm able to find the pin allocated to rotation?  It is not getting enough power?

I found a similar issue for the large LCD, not sure if related:
https://github.com/MarlinFirmware/Marlin/issues/10874
https://youtu.be/-IdReQPcRng

**Comment by shitcreek** [comment]
1.x is no longer being worked on. You should try 2.x.

**Comment by rocketkittens** [comment]
I'm unable to build 2.0-bugfix, unless i remove **'src\HAL\HAL_STM32'**:
**sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp:38:19: fatal error: timer.h: No such file or directory**

I managed to upload 2.0-bugfix, however i am having the exact same problem with encoder. How do i check if my encoder is broken? https://github.com/MarlinFirmware/Marlin/issues/6820#issuecomment-303836021

**Comment by ellensp** [comment]
Try the GLCD tester https://github.com/ellensp/rrd-glcd-tester  designed for a ramps 1.4 so check 1.5 hasnt changed the pins.

**Comment by rocketkittens** [comment]
> 
> 
> Try the GLCD tester https://github.com/ellensp/rrd-glcd-tester designed for a ramps 1.4 so check 1.5 hasnt changed the pins.

I tried it, it just fills the entire screen... I dont see any program. When i flash marlin, the LCD works. Just encoder rotation not working, click does.. very weird
https://github.com/ellensp/rrd-glcd-tester/issues/2

**Comment by rocketkittens** [comment]
**I found the issue,** i am working inside an enclosure and with poor lighting, i used a flashlight and noticed half of the Ramps board is not fully inserted into the Arduino, i made sure all pins are seated and viola!
