### ISSUE TITLE
[FR]  SKR mini E3 v1.2 should have 512K flash

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#15907]
as per this thread the SKR mini E3 v1.2 should have 512K flash in its default config

https://github.com/MarlinFirmware/Marlin/issues/15804

**Comment by tatusah** [comment]
This feature has already been made available https://github.com/MarlinFirmware/Marlin/commit/0f57818f2decca8340fd5fc86f9ea7b792d9d802
