### ISSUE TITLE
Marlin does not compile with MAX6675

### ISSUE THREAD

**Issue by Grogyan** [MarlinFirmware/Marlin#1591]
RAMPS 1.4
Arduino IDE 1.60
Development Branch

```
temperature.cpp: In function 'void manage_heater()':
temperature.cpp:529:59: error: 'max_temp_error' was not declared in this scope
     if (ct > min(HEATER_0_MAXTEMP, 1023)) max_temp_error(0);
                                                           ^
temperature.cpp:530:59: error: 'min_temp_error' was not declared in this scope
     if (ct < max(HEATER_0_MINTEMP, 0.01)) min_temp_error(0);
                                                           ^
```

Commit 9c9726d had some cleanup done of the code, which possibly broke code compilation for the MAX6675 

I did not have the time to check the code prior to this commit which endevours to squash #1227

**Comment by boelle** [comment]
i have marked it verfied and added it to a milestone

**Comment by Grogyan** [comment]
Shouldn't this be added to Milestone 3, which has the SPI issue earmarked for fixing?

**Comment by boelle** [comment]
dooh yes of course.... i guess there is a common issue that once fixed will solve them all

**Comment by AnHardt** [comment]
At least compiles again with pull request #1595.

**Comment by boelle** [comment]
but not with current code?

**Comment by AnHardt** [comment]
@boelle 
As the title of this issue says.

**Comment by thinkyhead** [comment]
I'm going to re-roll #1595 to keep those methods private, just move them above `manage_heater`.

**Comment by Grogyan** [comment]
Missing changes from #1595 
Does not compile without these changes

**Comment by thinkyhead** [comment]
@Grogyan Try again…? That code should work. Watch out for the Arduino IDE. It doesn't always notice code changes without a reload.

**Comment by Grogyan** [comment]
Compiles now.
All good.
