### ISSUE TITLE
[BUG] MKS Robin Lite v1.1. Freeze at "Update 100%"

### ISSUE THREAD

**Issue by inetd128** [MarlinFirmware/Marlin#15910]
I have the same issue like at:
https://github.com/MarlinFirmware/Marlin/issues/15143
1. Build MKSLite.bin
2. Put SD Card in Printer]
3. Turn on and wait
4. Freeze at "Updating 100%"

This problem appeared around 2-4 days ago. Because I compiled Marlin 5 days ago and firmware started after update. I just updated my Marlin sources from git yesterdays and get this problem.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by inetd128** [comment]
[conf.zip](https://github.com/MarlinFirmware/Marlin/files/3855529/conf.zip)

**Comment by inetd128** [comment]
ping

**Comment by boelle** [comment]
no need to post ping as text, the people with knowledge are very few and they work for free so it will just take time

**Comment by boelle** [comment]
btw what version are you using?

**Comment by inetd128** [comment]
Bugfix-2.0.x from git

**Comment by boelle** [comment]
@inetd128 since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by inetd128** [comment]
Has been tested few minutes ago. Nothing changed, Still freeze at "Update 100%".
BTW, there is absolutely the same bug https://github.com/MarlinFirmware/Marlin/issues/15998

**Comment by boelle** [comment]
oki... since the isuues are the same and you came first i will close the other one so we dont have to hunt down dublicates

**Comment by boelle** [comment]
@inetd128 is the issue still the same with all the updates in the last 16 days?

**Comment by boelle** [comment]
btw, who can confirm there is an issue? use the same configs as OP and the same hardware if possible

**Comment by inetd128** [comment]
Still the same

**Comment by boelle** [comment]
@inetd128  still no good news with the latest bugfix 2.0.x?

**Comment by inetd128** [comment]
I don't know. Switched to klipper 1 week ago.

**Comment by boelle** [comment]
will close this one

you where the only one with the problem and since you now run klipper it does not make much sense to keep it open, 

if others see this after its closed and they have the same problem we can reopen it
