### ISSUE TITLE
web configurator

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1592]
as suggested i'm creating this issue so it has its own list of discussion

@MagoKimbra created one and @thinkyhead  created one...

either way i think a tool as this should have its own web space

**Comment by thinkyhead** [comment]
:meat_on_bone: This actually works, but it's not affiliated with Github: https://rawgit.com/thinkyhead/Marlin/marlin_configurator/Marlin/configurator/index.html

As far as web-based configurators go, mine has the geek factor, but needs some work in the design area. Consider the current work what would eventually be the "Advanced" interface – not the default. More meta-data can be used to produce a bare-bones, "**only the options your machine needs**" view, with more selectable options so it's not easy to put in "illegal" values.

**Comment by boelle** [comment]
i wonder if marlin should have its own domain name?

Den torsdag den 12. marts 2015 skrev Scott Lahteine <
notifications@github.com>:

**Comment by daid** [comment]
You'll have to look around (or ask around) on the Ultimaker forums. But there is an online configurator which compiles as well as generating the config file. So that's very easy for people to use.

**Comment by boelle** [comment]
the one scott made? or somerhing we dont know?

Den torsdag den 12. marts 2015 skrev daid notifications@github.com:

**Comment by scotty1024** [comment]
$9000 USD for Marlin.org? Have they been smoking crack?

**Comment by boelle** [comment]
hehe some make a living of buying domains and sell them at insane prices

what about .net or .nl?

Den torsdag den 12. marts 2015 skrev scotty1024 notifications@github.com:

> $9000 USD for Marlin.org? Have they been smoking crack?
> 
> Sent from my iPad
> 
> > On Mar 12, 2015, at 3:37 AM, Bo Herrmannsen <notifications@github.com

**Comment by scotty1024** [comment]
Bo,

That isn't what is happening here. The domain is not registered. They are asking for $9000 because they think they can get it because it is desirable. Essentially it is more like  raising the price of gasoline after a hurricane tears up everything.

**Comment by boelle** [comment]
ok... let me try from little denmark

Den torsdag den 12. marts 2015 skrev scotty1024 notifications@github.com:

> Bo,
> 
> That isn't what is happening here. The domain is not registered. They are
> asking for $9000 because they think they can get it because it is
> desirable. Essentially it is more like raising the price of gasoline after
> a hurricane tears up everything.
> 
> > On Mar 12, 2015, at 5:46 AM, Bo Herrmannsen <notifications@github.com

**Comment by boelle** [comment]
here i get it listed as taken

Den torsdag den 12. marts 2015 skrev Bo Herrmannsen <
bo.herrmannsen@gmail.com>:

> ok... let me try from little denmark
> 
> Den torsdag den 12. marts 2015 skrev scotty1024 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> 
> > Bo,
> > 
> > That isn't what is happening here. The domain is not registered. They are
> > asking for $9000 because they think they can get it because it is
> > desirable. Essentially it is more like raising the price of gasoline after
> > a hurricane tears up everything.
> > 
> > > On Mar 12, 2015, at 5:46 AM, Bo Herrmannsen notifications@github.com
> > > wrote:
> > > 
> > > hehe some make a living of buying domains and sell them at insane prices
> > > 
> > > what about .net or .nl?
> > > 
> > > Den torsdag den 12. marts 2015 skrev scotty1024 <
> > > notifications@github.com>:
> > > 
> > > > $9000 USD for Marlin.org? Have they been smoking crack?
> > > > 
> > > > Sent from my iPad
> > > > 
> > > > > On Mar 12, 2015, at 3:37 AM, Bo Herrmannsen <
> > > > > notifications@github.com

**Comment by boelle** [comment]
Den torsdag den 12. marts 2015 skrev Bo Herrmannsen <
bo.herrmannsen@gmail.com>:

> here i get it listed as taken
> 
> Den torsdag den 12. marts 2015 skrev Bo Herrmannsen <
> bo.herrmannsen@gmail.com
> <javascript:_e(%7B%7D,'cvml','bo.herrmannsen@gmail.com');>>:
> 
> > ok... let me try from little denmark
> > 
> > Den torsdag den 12. marts 2015 skrev scotty1024 <notifications@github.com
> > 
> > > :
> > > 
> > > Bo,
> > > 
> > > That isn't what is happening here. The domain is not registered. They
> > > are asking for $9000 because they think they can get it because it is
> > > desirable. Essentially it is more like raising the price of gasoline after
> > > a hurricane tears up everything.
> > > 
> > > > On Mar 12, 2015, at 5:46 AM, Bo Herrmannsen notifications@github.com
> > > > wrote:
> > > > 
> > > > hehe some make a living of buying domains and sell them at insane
> > > > prices
> > > > 
> > > > what about .net or .nl?
> > > > 
> > > > Den torsdag den 12. marts 2015 skrev scotty1024 <
> > > > notifications@github.com>:
> > > > 
> > > > > $9000 USD for Marlin.org? Have they been smoking crack?
> > > > > 
> > > > > Sent from my iPad
> > > > > 
> > > > > > On Mar 12, 2015, at 3:37 AM, Bo Herrmannsen <
> > > > > > notifications@github.com

**Comment by Drakelive** [comment]
Hi Bo

marlinfirmware.org is available.

Drake

2015-03-12 15:19 GMT+01:00 Bo Herrmannsen notifications@github.com:

> Den torsdag den 12. marts 2015 skrev Bo Herrmannsen <
> bo.herrmannsen@gmail.com>:
> 
> > here i get it listed as taken
> > 
> > Den torsdag den 12. marts 2015 skrev Bo Herrmannsen <
> > bo.herrmannsen@gmail.com
> > <javascript:_e(%7B%7D,'cvml','bo.herrmannsen@gmail.com');>>:
> > 
> > > ok... let me try from little denmark
> > > 
> > > Den torsdag den 12. marts 2015 skrev scotty1024 <
> > > notifications@github.com
> > > 
> > > > :
> > > > 
> > > > Bo,
> > > > 
> > > > That isn't what is happening here. The domain is not registered. They
> > > > are asking for $9000 because they think they can get it because it is
> > > > desirable. Essentially it is more like raising the price of gasoline
> > > > after
> > > > a hurricane tears up everything.
> > > > 
> > > > > On Mar 12, 2015, at 5:46 AM, Bo Herrmannsen <
> > > > > notifications@github.com>
> > > > > wrote:
> > > > > 
> > > > > hehe some make a living of buying domains and sell them at insane
> > > > > prices
> > > > > 
> > > > > what about .net or .nl?
> > > > > 
> > > > > Den torsdag den 12. marts 2015 skrev scotty1024 <
> > > > > notifications@github.com>:
> > > > > 
> > > > > > $9000 USD for Marlin.org? Have they been smoking crack?
> > > > > > 
> > > > > > Sent from my iPad
> > > > > > 
> > > > > > > On Mar 12, 2015, at 3:37 AM, Bo Herrmannsen <
> > > > > > > notifications@github.com

**Comment by boelle** [comment]
might be worth considering...

what are peoples opinions ?

2015-03-12 15:28 GMT+01:00 Drake Drakan notifications@github.com:

**Comment by Drakelive** [comment]
A domain allows us to concentrate in one place Information, Wiki, Guides,
Documentations, RSS Feed, Forum and a complete Web Configurator.
Banner, Donations and Gadgets may also allow us to finance the project.

My opinion,  this is a necessary step and should be ready with the release
of version Stable

Drake

2015-03-12 16:06 GMT+01:00 Bo Herrmannsen notifications@github.com:

**Comment by scotty1024** [comment]
Domain paid for, droplet created at DigitalOcean. Waiting for things to stabilize and gel a bit.

Spinning up an Ubuntu image.

**Comment by boelle** [comment]
i agree...

so donations... who should take care of those and in what order should
donataions be spent?

2015-03-12 16:27 GMT+01:00 Drake Drakan notifications@github.com:

**Comment by scotty1024** [comment]
The domain is on its own NS account so it can be handed off. The droplet can be backed up and transferred. For now the domain and droplet are paid for.

Those that want to be admin for Wiki et al can be configured in with admin for the various services later today.

**Comment by thinkyhead** [comment]
Nice, thanks everyone! So do we get to install an AVR build system on this Ubuntu box?? Being able to download an HEX file seems to be request número uno.

Again, while the configurator built and hosted by @MagoKimbra is great, the thing I'm making is intended to be comprehensive and manageable from the live git repo, so changes go live right away, no FTP or rsync needed.

**Comment by scotty1024** [comment]
Absolutely. 

The droplet is easily enhanced as needed to give it more resources. Their top tier is currently 20 CPUs, 64GB RAM, 640 GB SSD, and 9TB of traffic for $640 USD a month. Currently it’s sized to 1 CPU, 1GB RAM, 30 GB SSD, 2 TB of traffic. I will monitor resource usage and adjust.

The domain is hooked to the droplet.
The droplet is LAMP’d.
The droplet is MediaWiki’d as you can see when you go to http://www.marlinfirmware.org http://www.marlinfirmware.org/

The Wiki can be moved but I don’t have a home page so the wiki is the landing page for now.

Let me know what you need for the web configurator e.g. account, packages….

Let me know what other goodies to light up.

I’m going to load the avr tool chain and head for bed.

**Comment by boelle** [comment]
also some sort of donation link for those of us that want to chip in on the
cost

2015-03-13 6:12 GMT+01:00 scotty1024 notifications@github.com:

**Comment by scotty1024** [comment]
I’ve used one of those silly free web site templating tools to whip up an idea of a landing page.

The Wiki remains the default page but you can slip around it and see the landing page here: http://www.marlinfirmware.org/index.html http://www.marlinfirmware.org/index.html

The avr tool chain is installed.

If you are ready to move forward with the build system I’m ready to work with you to begin wiggling it into the web site and droplet.

**Comment by scotty1024** [comment]
Hi Scott,

Forgot you already had code up I could copy over to start the conversation.

If you email me a password I will setup an account that will let you get in and start welding and sanding.

http://www.marlinfirmware.org/configurator/index.html http://www.marlinfirmware.org/configurator/index.html

scotty1024@me.com mailto:scotty1024@me.com

**Comment by thinkyhead** [comment]
Thanks Scotty, I will keep plugging away at the configurator to get the first phase (Advanced Interface) complete, and then get into the more public-facing side soon after that. I will contact you pretty soon about the dev account.
