### ISSUE TITLE
[FR] compact platformio.ini

### ISSUE THREAD

**Issue by bjoernwedi** [MarlinFirmware/Marlin#15936]
Applied some compacting on **platformio.ini (-100 lines)**:
https://github.com/bjoernwedi/Marlin/blob/feature/%2315936/platformio.ini
Escecially on STM32F103 boards, like the SKR_Mini Series.

**Comment by bjoernwedi** [comment]
Same manner the configuration.h motherboard, serial baud rate and ports can be defined and inherited. 
Also printers by config/examples would be managable.

**Comment by reloxx13** [comment]
its also possible now to load additional config ini files

https://docs.platformio.org/en/latest/projectconf/section_platformio.html#extra-configs

**Comment by bjoernwedi** [comment]
Applied some compacting on **platformio.ini** _(-100 lines)_:
https://github.com/bjoernwedi/Marlin/blob/feature/%2315936/platformio.ini
