### ISSUE TITLE
[BUG] Vietnamese language files contains defunct string names

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#15937]
### Description

language_vi.h contains defunct string names as of #14951 
Contains MSG_CARD_MENU and MSG_NO_CARD should have MSG_MEDIA_MENU and MSG_NO_MEDIA
Contains MSG_SD_INSERTED and MSG_SD_REMOVED should have MSG_MEDIA_INSERTED and MSG_MEDIA_REMOVED   
Contains MSG_INIT_SDCARD  and MSG_CHANGE_SDCARD should have MSG_INIT_MEDIA and MSG_CHANGE_MEDIA    
Contains MSG_SD_UPDATE should have MSG_MEDIA_UPDATE 
   
Although i'm sure this causes an error somewhere I didn't find it this way so there are no config files.  

Just go look at the file.

**Comment by boelle** [comment]
are you using bugfix 2.0.x ?

**Comment by GMagician** [comment]
In languages, missing defines will not raise an error, Marlin will simply switch to English version.

**Comment by shitcreek** [comment]
I've created a PR for this. Thanks for pointing it out.
