### ISSUE TITLE
[BUG] STM32 EXTI Conflicts

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#15947]
* In theory all pins of an F1 and F4 can rise interrupts when changing.
* But not more than 16 at the same time. All Px0 to Px15 share the same interrupt line, with x being the ports. Only one of the ports can be connected to an interrupt line.
* There are only 7 hardware interrupt vectors. 0 to 4 each have an own (like the EXTI on the AVRs). The groups 5-9 and 10-15 each [share a vector](https://github.com/stm32duino/Arduino_Core_STM32/blob/master/cores/arduino/stm32/interrupt.cpp#L90-L105) (like the PCIs on the AVRs). But this is sorted out nicely by the software system. Every interrupt line can have its own callback.

The problem with this: Some hardware designers seemingly made an unfortunate selection of pins for some functions.

For the BTT SKR PRO V1.1 , for example, there are conflicts between X_min_endstop [PB**10**] and Y-max-endstop (E1) [PE**10**] and the TMC RX/TX lines for Z [PE**1**] and E1 [PD**1**] if an interrupt is required.

**Comment by boelle** [comment]
is this a bug?

**Comment by AnHardt** [comment]
Likely this is the **reason** for several bugs, where one endstop is not working when endstop_interrupts is defined or a serial TMC does not want to communicate.

Developers have to check if such conflicts do exist on other STM32 boards. 
If yes, we cant really fix that in software, but we can give warnings to avoid that pin combinations.

At least we do know now the reason for, why some configurations do not work.

**Comment by AnHardt** [comment]
BTT SKR mini V1.1 
At least conflicts:
X_MIN [PA**2**] with X_MAX [PC**2**]
Y_MIN [PC**1**] with Y_MAX [PA**1**]

**Comment by sjasonsmith** [comment]
The SKR Pro only uses software serial for TMC drivers, which depends only on timer interrupts. Could there still be a conflict with this, or pin change interrupts are not used?

**Comment by AnHardt** [comment]
MKS Robin:
Y_MAX_PIN PC**4**
Z_MIN_PIN PA**4**

@sjasonsmith 
If the software serial does not use the EXTI the EXTI conflict does not matter.  
I don't really know the implementation of the **currently** used library. But i mean to remember to have seen attempts to use PCIs and timers instead of polling (maybe not for STMs).

**Comment by sjasonsmith** [comment]
> If the software serial does not use the EXTI the EXTI conflict does not matter.
> I don't really know the implementation of the **currently** used library. But i mean to remember to have seen attempts to use PCIs and timers instead of polling (maybe not for STMs).

AVR uses an interrupt to detect the start bit. LPC and STM32 just use a timer interrupt to poll. This would be good for us to remember though, if anyone attempted to re-implement it differently. This was mentioned when we submitted fixes to SoftwareSerial in Arduino_Core_STM32.

**Comment by boelle** [comment]
i assume that this has not changed in the recent 2.0 release?

**Comment by boelle** [comment]
what could we do about this one?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
