### ISSUE TITLE
irc channel

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1594]
is anyone actually using the channel? i drop in quickly from time to time but there hardly seems to be anyone using it...

i'm considering an unregister from my freenode registration.. others can of course register it

my grounds for this is that it seems to be prefered to discuss things in the issues instead...

**Comment by thinkyhead** [comment]
I would use it if there was something to discuss in real-time. But there may be other channels for that. G+ etc. That being said, I have lately grown more fond of IRC, but it works best when two or more are working on something and it helps to compare things in real-time.

**Comment by boelle** [comment]
oki doki, the channel stays, but i'm still looking for some suitble log
software

Den torsdag den 12. marts 2015 skrev Scott Lahteine <
notifications@github.com>:
