### ISSUE TITLE
[BUG] BLTOUCH configuration is missing

### ISSUE THREAD

**Issue by KiudLyrl** [MarlinFirmware/Marlin#15949]
### Description

BLTOUCH configuration is missing from 2.0 "bugfix"

### Steps to Reproduce

open `configuration.h`, ctrl+f, `X_PROBE_OFFSET_FROM_EXTRUDER` cannot be found

There is no `#if ENABLE(BLTOUCH)` block in the file

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/Configuration.h

**Expected behavior:** 

bltouch configuration is found

**Actual behavior:** 

bltouch configuration is missing

I don't know if this qualify as a bug, sorry if it's not

**Comment by Lord-Quake** [comment]
I'm sure you are using an older version of `configuration.h`. That's not a good idea.

You are looking for `NOZZLE_TO_PROBE_OFFSET` in the latest version.

**Comment by sjasonsmith** [comment]
And all the advanced BLTOUCH options moved to configuration_Adv.h.

**Comment by KiudLyrl** [comment]
Oh my bas, the tutorials I was watching were outdated :x
