### ISSUE TITLE
[BUG] Unable to compile Marling bugfix 2.0 with TMC5160 drivers on RUMBA32 board

### ISSUE THREAD

**Issue by DropbearNinja** [MarlinFirmware/Marlin#15952]
### Description

Unable to compile Marling bugfix 2.0 with TMC5160 drivers on RUMBA32 board

### Steps to Reproduce
**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files. 

1. clean arduino install
2. isntall stm32duino as per here: https://github.com/stm32duino/wiki/wiki/Getting-Started including stm32cubeprogrammer
3. install TMCstepper library
4. open marlin.ino
5. change only: 
`#define MOTHERBOARD BOARD_RUMBA32
#define X_DRIVER_TYPE  TMC5160`
6. ensure ENDSTOP_INTERRUPTS_FEATURE commented out (default)
7. try all combinations of active/commented out of:
'  //#define TMC_USE_SW_SPI
  //#define TMC_SW_MOSI       PA7
  //#define TMC_SW_MISO       PA6
  //#define TMC_SW_SCK        PA5'

**Expected behavior:** [What you expect to happen]

To compile

**Actual behavior:** [What actually happens]

Error:
`Arduino: 1.8.10 (Windows 10), Board: "3D printer boards, RUMBA32, STM32CubeProgrammer (DFU), Enabled (generic 'Serial'), CDC (no generic 'Serial'), Low/Full Speed, Smallest (-Os default), Newlib Nano (default)"

WARNING: library TMCStepper claims to run on avr architecture(s) and may be incompatible with your current board which runs on stm32 architecture(s).
c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::read()':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerial4readEv+0x0): multiple definition of `SoftwareSerial::read()'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerial4readEv+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::available()':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerial9availableEv+0x0): multiple definition of `SoftwareSerial::available()'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerial9availableEv+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::flush()':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerial5flushEv+0x0): multiple definition of `SoftwareSerial::flush()'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerial5flushEv+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::peek()':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerial4peekEv+0x0): multiple definition of `SoftwareSerial::peek()'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerial4peekEv+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::setSpeed(unsigned long)':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerial8setSpeedEm+0x0): multiple definition of `SoftwareSerial::setSpeed(unsigned long)'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerial8setSpeedEm+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::write(unsigned char)':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerial5writeEh+0x0): multiple definition of `SoftwareSerial::write(unsigned char)'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerial5writeEh+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::stopListening()':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerial13stopListeningEv+0x0): multiple definition of `SoftwareSerial::stopListening()'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerial13stopListeningEv+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::listen()':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerial6listenEv+0x0): multiple definition of `SoftwareSerial::listen()'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerial6listenEv+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::~SoftwareSerial()':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerialD2Ev+0x0): multiple definition of `SoftwareSerial::~SoftwareSerial()'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerialD2Ev+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::~SoftwareSerial()':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerialD2Ev+0x0): multiple definition of `SoftwareSerial::~SoftwareSerial()'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerialD2Ev+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::~SoftwareSerial()':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerialD0Ev+0x0): multiple definition of `SoftwareSerial::~SoftwareSerial()'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerialD0Ev+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::SoftwareSerial(unsigned short, unsigned short, bool)':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerialC2Ettb+0x0): multiple definition of `SoftwareSerial::SoftwareSerial(unsigned short, unsigned short, bool)'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerialC2Ettb+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::SoftwareSerial(unsigned short, unsigned short, bool)':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerialC2Ettb+0x0): multiple definition of `SoftwareSerial::SoftwareSerial(unsigned short, unsigned short, bool)'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerialC2Ettb+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::begin(long)':

SoftwareSerial.cpp:(.text._ZN14SoftwareSerial5beginEl+0x0): multiple definition of `SoftwareSerial::begin(long)'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerial5beginEl+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o: in function `SoftwareSerial::end()':

Multiple libraries were found for "SPI.h"
 Used: C:\Users\jonha\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.7.0\libraries\SPI
Multiple libraries were found for "IWatchdog.h"
 Used: C:\Users\jonha\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog
SoftwareSerial.cpp:(.text._ZN14SoftwareSerial3endEv+0x0): multiple definition of `SoftwareSerial::end()'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:SoftwareSerial.cpp:(.text._ZN14SoftwareSerial3endEv+0x0): first defined here

Multiple libraries were found for "TMCStepper.h"
 Used: C:\Users\jonha\OneDrive\Documents\Arduino\libraries\TMCStepper
Multiple libraries were found for "SoftwareSerial.h"
 Used: C:\Users\jonha\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.7.0\libraries\SoftwareSerial
c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.rodata._ZTV14SoftwareSerial+0x0): multiple definition of `vtable for SoftwareSerial'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.rodata._ZTV14SoftwareSerial+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial9cur_speedE+0x0): multiple definition of `SoftwareSerial::cur_speed'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial9cur_speedE+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.data._ZN14SoftwareSerial10rx_bit_cntE+0x0): multiple definition of `SoftwareSerial::rx_bit_cnt'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.data._ZN14SoftwareSerial10rx_bit_cntE+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial9rx_bufferE+0x0): multiple definition of `SoftwareSerial::rx_buffer'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial9rx_bufferE+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial10tx_bit_cntE+0x0): multiple definition of `SoftwareSerial::tx_bit_cnt'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial10tx_bit_cntE+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial9tx_bufferE+0x0): multiple definition of `SoftwareSerial::tx_buffer'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial9tx_bufferE+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial11rx_tick_cntE+0x0): multiple definition of `SoftwareSerial::rx_tick_cnt'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial11rx_tick_cntE+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial11tx_tick_cntE+0x0): multiple definition of `SoftwareSerial::tx_tick_cnt'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial11tx_tick_cntE+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial9active_inE+0x0): multiple definition of `SoftwareSerial::active_in'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial9active_inE+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial10active_outE+0x0): multiple definition of `SoftwareSerial::active_out'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial10active_outE+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial15active_listenerE+0x0): multiple definition of `SoftwareSerial::active_listener'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial15active_listenerE+0x0): first defined here

c:/users/jonha/appdata/local/arduino15/packages/stm32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: libraries\SoftwareSerial\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial5timerE+0x0): multiple definition of `SoftwareSerial::timer'; sketch\src\HAL\HAL_STM32\SoftwareSerial.cpp.o:(.bss._ZN14SoftwareSerial5timerE+0x0): first defined here

collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board 3D printer boards.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

#### Additional Information

config and pins file attached

Please help

[config.zip](https://github.com/MarlinFirmware/Marlin/files/3867613/config.zip)

**Comment by sjasonsmith** [comment]
The current STM32 Arduino Core has issues in the SoftwareSerial implementation, so we temporarily have our own in Marlin. SoftwareSerial is structured as a separate library within the Arduino Core, so we were able to exclude it using PlatformIO. It did not occur to us that this would cause a problem when building within ~~Marlin~~ Arduino (edited).

**Comment by sjasonsmith** [comment]
You don't actually need SoftwareSerial since you are using 5160 drivers. It is only needed as a dependency of TMCStepper, but it doesn't actually have to _work_ for your needs. As a temporary workaround you could probably delete `Marlin/src/HAL/HAL_STM32/SoftwareSerial.cpp` file, and let it use the version it finds in the Arduino Core.

That would probably _not_ work for someone using TMC 2208/9 drivers with software serial. It _might_ work if they are using separate RX/TX pins, but won't work with a single pin.

**Comment by DropbearNinja** [comment]
Thank you for such a quick and helpful reply! I tried removing the file, and it compiled and works as expected :) thank you so much!
