### ISSUE TITLE
[BUG] [Bugfix 2.0.x] FILAMENT RUNOUT without ADVANCED_PAUSE disables M125

### ISSUE THREAD

**Issue by karabas2011** [MarlinFirmware/Marlin#15955]
I am trying to pause print (filament sensor)  with nozzle park but without filament change features
But it disabling  ADVANCED_PAUSE_FEATURE disables M125 in many places in code.
Are there any ways to solve the problem?
SKR1.3 +marlin2.0  9-nov-2019

**Comment by ManuelMcLure** [comment]
No. ``PARK_HEAD_ON_PAUSE`` (which adds ``M125``) absolutely requires ``ADVANCED_PAUSE_FEATURE``.

**Comment by karabas2011** [comment]
There was some patches for avoiding  ADVANCE, 
something like PARK_HEAD_ON_PAUSE

**Comment by ManuelMcLure** [comment]
``PARK_HEAD_ON_PAUSE`` in the configuration files is inside a block that is controlled by ``ADVANCED_PAUSE_FEATURE``, so there is no way to enable one without the other.

**Comment by karabas2011** [comment]
Is there way to disable temp waiting on pause?

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
will temp close this one until we have the configs as required by the template

ping me by adding a @ before my username and we can reopen this one
