### ISSUE TITLE
[QUESTION] Where/how to set laser/spindle pwm frequency

### ISSUE THREAD

**Issue by Milu1980** [MarlinFirmware/Marlin#15966]
### Steps to Reproduce

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Milu1980** [comment]
Hi, i need to know the pwm frequency, because i build a high speed laser engraver, and i need higher frequency... i think is now just 1kHz,  but i dont find  any info... thx.

**Comment by shitcreek** [comment]
The laser and spindle feature is still a work in progress and the documentation is behind. We've got a PR for improving this feature https://github.com/MarlinFirmware/Marlin/pull/15335 - it has a specific define for setting the laser's pwm frequency.

**Comment by Milu1980** [comment]
this settings are not yet avaible in the marlin... know you how much is the
frequency now ? I would like to have 4 KHz. Thx.

Luu Lac <notifications@github.com> schrieb am Do., 21. Nov. 2019, 19:11:

**Comment by boelle** [comment]
Closing this one as questions do not belong to the list, debate etc can continue on discord

Marlin Discord server. Join link: https://discord.gg/n5NJ59y

@shitcreek goes under the username luulac
