### ISSUE TITLE
[BUG] skr1.1Pro TMC2209 Z- Sensorles Homing 

### ISSUE THREAD

**Issue by Lino77** [MarlinFirmware/Marlin#15985]
Hello Can it be That sensorless homing on the Z axis does not work. I want my Prusa clone on Z-max home, but no matter what value I enter (M914 Z0-255) he does not stop
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/3882901/Config.zip)

**Comment by hackebike** [comment]
As far as I know sensorless probing works fine. Which TMC 2209 do you have? I have BTT TMC 2209 v1.2 and both sensorless homing and probing works fine, you need to find the right sensitivity value. Here is a [video](https://www.youtube.com/watch?v=UJwzSTcQslo).

**Comment by Grogyan** [comment]
Need to point out that using Sensorless homing on Z axis is not advisable as it can damage your printer.

Z max isn't used on Prusa I3 clones

Did you at least used a jumper from the Z-MAX pin to the Z-DIAG pin on the TMC2209?

**Comment by hackebike** [comment]
on the skr pro you do not need to use any jumpers

**Comment by dch1921** [comment]
> Hello Can it be That sensorless homing on the Z axis does not work. I want my Prusa clone on Z-max home, but no matter what value I enter (M914 Z0-255) he does not stop
> [Config.zip](https://github.com/MarlinFirmware/Marlin/files/3882901/Config.zip)

You need to uncomment
//#define SENSORLESS_PROBING // StallGuard capable drivers only

for starters in configuration_adv.h

**Comment by Lino77** [comment]
I put zmax on diag but he does not react. Z Probing I do not want to use for probing I have a Pindasensor I just want the home on z-max, and that does not work. look at my config. at the tmc 2130 under marlin 1.1.9 with a rumba the printer reacted to z-max. it seems to me that zMax or min only works with probing enabled, and sensorless homing works only on x and y
#if ENABLED(SENSORLESS_HOMING)

#define X_DIAG_PIN       PB10 
  #define Y_DIAG_PIN      PE12   // PC15
  #define Z_DIAG_PIN      PG8    // PC4
  #define E0_DIAG_PIN     PE15   // PB23
  #define E1_DIAG_PIN     PE10   // PD0
  #define E2_DIAG_PIN     PG5   // PD0

  #if X_HOME_DIR < 0
    #define X_MIN_PIN      X_DIAG_PIN
    #define X_MAX_PIN      PE15
  #else
    #define X_MIN_PIN      PB10
    #define X_MAX_PIN      X_DIAG_PIN
  #endif

  #if Y_HOME_DIR < 0
    #define Y_MIN_PIN      Y_DIAG_PIN
    #define Y_MAX_PIN      PE10
  #else
    #define Y_MIN_PIN      PE12
    #define Y_MAX_PIN      Y_DIAG_PIN
  #endif

  #if Z_HOME_DIR < 0
    #define Z_MIN_PIN      Z_DIAG_PIN
    #define Z_MAX_PIN      PG5
  #else
    #define Z_MIN_PIN      PB8
    #define Z_MAX_PIN      Z_DIAG_PIN
  #endif

**Comment by boelle** [comment]
> 1.1.9

try with 2.0.x instead

**Comment by Lino77** [comment]
You misunderstood me I already use the 2.0. just wanted to say that she ever ran under 1.19.

**Comment by boelle** [comment]
@Lino77 since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by Lino77** [comment]
I have not come to the test yet

**Comment by boelle** [comment]
tried the test yet?
