### ISSUE TITLE
[BUG] Motor stutter return on Deltas after commit 4db68d704f with RRDFGDC

### ISSUE THREAD

**Issue by Kaween-prog** [MarlinFirmware/Marlin#15992]
Follow up to : "[BUG] Print resumes after pause, "wait for print to resume" stays on screen. #15414 

Marlin 2.0.x Bugfix (all commits I've tested so far after 4db68d704f) on SKR1.3 and using RRDFGD. Delta printer.

Description
Heavy motor stutter during movements on all towers, resulting is unusable bad print quality on a Delta printer. Not slicer related : the behavior can be observed while running onboard LCD commands (calibration, bed leveling)

Steps to Reproduce
* use firmware prior to 4db68d704f : print quality is excellent, however the display refresh is erratic and will for example cause the #"wait for print to resume" delay (#15414)
* flashing the fix (4db68d704f, all version including the most recent one on 24/11/19) solves the display resume problem, but reverts back to the very bad print quality due to motor jitter as first reported in 2018.  Porting the exact same configuration.h and configuration_adv.h between the two builds.
* eeprom values were reset with each new firmware build test to exclude the possibility of eeprom values causing the issue.

Note : specifically on Delta Machines.

Hardware :
Anycubic Predator Delta
SKR 1.3 Board
Bigtreetech 2.4TFT with 12864 emulation mode
X/Y/Z/E0 = TMC2208 in Uart mode, also tested with 2209 and normal non-uart Step/dir 2100's.
latest bugfix 2.0 code used + several older versions (same issue)

Personally, I still think the issue must be found in the acutal RRDFGDC routines : in the past, replacing the RRDFGDC with another display (Fysetc Mini) solved this issue while using the same build and exactly the same code (with of course the Fysetc as defined screen instead of the RRDFGDC).

Will check if this is again the case with this situation and I'll add the findings ASAP.

**Comment by boelle** [comment]
there is no 2.0.1 yet, typo?

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by Kaween-prog** [comment]
Hello,

here's both config files, As said, when using the build prior to 4db68d704f,  the machine will react well in terms of producing good print quality and smooth motor movement but it will show the "LCD response is erratic/delayed.  Versions after this point do not have any issues with screen updates, but at the cost of bad motor movement.

[stutter issue.zip](https://github.com/MarlinFirmware/Marlin/files/3883888/stutter.issue.zip)

Several people have reported the same issue, specifically when using the combination of Delta machines and the RepReapDiscountFullgraph displays, using different controller boards than the SKR1.3, so I'm presuming it's not a specific SKR issue.  

Thank you for your consideration and efforts.

Still need to dig up my Fysetc Mini and see if the same effect still applies (in other words, perfect behavior on both builds)

**Comment by Kaween-prog** [comment]
Update, tested with my Fysetc Mini. Same result : the axis motor movements are very stuttery and print quality is unusable with 4db68d704f and beyond.  Prior to 4db68d704f, motor movements are smooth and print quality is excellent using basically the same configuration files (some changes where needed as my version prior to 4db68d704f needed a different declaration in terms of bed limits and it didn't have the "classic jerk" variables.

Will do a test with the latest build available, was kinda confused about Marlin having thrown out the "DELTA_CALIBRATION_RADIUS" define and now asks me to use MIN_PROBE_EDGE inset : an example of how to use this could be helpful, as when I tried to implement this the G33 command danced the effector around the center for a couple of probes and then stalled the process instead of running the delta calibration radius range, so I clearly am not correctly implementing it.

**Comment by Kaween-prog** [comment]
Update : 

Whatever was broken in 4db68D7f seems to be fixed in  31e329f.  Movement with the Fysetc Mini is smooth, RRDFGDC not tested yet.  I'll check this later tomorrow, but so far whatever was broken seems to be fixed now.

Could someone please be so kind however to explain exactly how I have to define the value of the calibration radius ?  On the older builds, there was a simple DELTA_CALIBRATION_RADIUS, easy to use and it worked perfectly.

Now, during compilation I get an error, stating ""Remove DELTA_CALIBRATION_RADIUS and use MIN_PROBE_EDGE to inset the probe area instead."  However, I can't see to get this to work : when I define MIN_PROBE_EDGE to whatever value, the G33 command stops probing directly after probing the first center points : the effector does not move to the outer side of the bed at all, no error, G33 just "stops".

I'm sure I'm simply not understanding correctly how the new builds expects to find the correct .... well Delta calibration radius.  I fully understand this isn't a support forum, but a little pointer on what I need to do to make G33 work correctly again would be highly appriciated.

**Comment by boelle** [comment]
remember to hit close if display also work

**Comment by Kaween-prog** [comment]
I will ! If you or any other kind soul could give me a hint on the added question about the change in terms of Delta Calibration Radius I just added above, I'd be very greatful. :)

**Comment by Kaween-prog** [comment]
Headsup : the newer versions (after 261119) solve the issue : no motor stutter, both with the Fysetc Mini's and variations of the RRDFGDC's, inclusive the BTT Hybrid LCD's and while using both 2209 and 2208's in UART mode.

Bed leveling issue has been solved too.  Thank you for your attention.
