### ISSUE TITLE
[BUG] BOARD_MKS_ROBIN_LITE STM32F103RCT6

### ISSUE THREAD

**Issue by electrocoder** [MarlinFirmware/Marlin#15998]
### Description

STM32 MKS Robin lite Mother Board upload %100 not working. 

### Steps to Reproduce
My config files : [https://gofile.io/?c=jUKcwS](https://gofile.io/?c=jUKcwS)

1. Marlin bugfix-2.0.x download
2. Configuration.h -> #define MOTHERBOARD BOARD_MKS_ROBIN_LITE
3. Atom -> platformio.ini -> default_envs = mks_robin_lite
4. PIO Build 
5. Copy .pio/build/mks_robin_lite/mksLite.bin to SDCARD

upload %100 but froze

My Board Image: https://serving.photos.photobox.com/16920893a419135d6482a073ceeeaeac7b4d0740d99e7a3b1c58df559a69407d51512bbf.jpg
My TFT Image:
https://serving.photos.photobox.com/262235629f40b630be66146f1e379023d7191ef14ad62ea910049cb6fa6e55a6bb986dc7.jpg

**Comment by RudyBenner** [comment]
I believe the file you need to copy to the uSD card is 

**firmware.bin**

 Please give it a try, feedback, please.

**Comment by RudyBenner** [comment]
mksLite.bin and firmware.bin are the same size, but are not identical.

**Comment by RudyBenner** [comment]
> ### Description
> STM32 MKS Robin lite Mother Board upload %100 not working.
> 
> ### Steps to Reproduce
> My config files : https://gofile.io/?c=jUKcwS
> 
> 1. Marlin bugfix-2.0.x download
> 2. Configuration.h -> #define MOTHERBOARD BOARD_MKS_ROBIN_LITE
> 3. Atom -> platformio.ini -> default_envs = mks_robin_lite
> 4. PIO Build
> 5. Copy .pio/build/mks_robin_lite/mksLite.bin to SDCARD
> 
> upload %100 but froze
> 
> My Board Image: https://serving.photos.photobox.com/16920893a419135d6482a073ceeeaeac7b4d0740d99e7a3b1c58df559a69407d51512bbf.jpg
> My TFT Image:
> https://serving.photos.photobox.com/262235629f40b630be66146f1e379023d7191ef14ad62ea910049cb6fa6e55a6bb986dc7.jpg

nice build

**Comment by electrocoder** [comment]
firmware.bin does not work. I changed the file name to mksLite.bin. I get the same error. It's 100%.

**Comment by RudyBenner** [comment]
Platformio generates 2 bin files. One is **firmware.bin**, the other is **mksLite.bin**.

**Comment by RudyBenner** [comment]
I believe the uSD card needs to be formatted in FAT32 ? Is there a size limit?

**Comment by noahdavis319** [comment]
As previously described, please upload the **firmware.bin** file to the SD card, and not **mksLite.bin**

Additionally, if you are building on a Windows-based machine in Visual Studio Code, please specify what version of PlatformIO Core you are using. There are reports of 4.1.0 not generating working binary files for some people.

**Comment by boelle** [comment]
@electrocoder did you do what @noahdavis319 said?

> Platformio generates 2 bin files. One is **firmware.bin**, the other is **mksLite.bin**.
> As previously described, please upload the **firmware.bin** file to the SD card, and not **mksLite.bin**

**Comment by boelle** [comment]
@electrocoder since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by boelle** [comment]
https://github.com/MarlinFirmware/Marlin/issues/15910 same issue so this one is a dublicate and we dont need those

i couldd be wrong and in that case will reopen
