### ISSUE TITLE
[BUG] Get GCC ERRORs from Lint in PlatformIO with ATOM

### ISSUE THREAD

**Issue by GadgetAngel** [MarlinFirmware/Marlin#16009]
### Steps to Reproduce
**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files. 
links to my files:
https://drive.google.com/open?id=1U75R1UnMs2UsOXjmV9bdxrPTSJ9viGfe
https://drive.google.com/file/d/1xfOCJWDRIhYiZcrwPskgPNEMHB3I0Ir9/view?usp=sharing

1. download MarlinV2-bugfix
2. Make any change to Configuration.h or Configuration_adv.h
3. get GCC errors when compiling with PlatformIO in ATOM text editor on Window 10 machine

**Expected behavior:** [What you expect to happen]
NO  GCC errors should occur

**Actual behavior:** [What actually happens]
![compile_errors_with_MarlinV2 0_with_ATOM_PlatfromIO](https://user-images.githubusercontent.com/33468777/69637918-a7034600-1027-11ea-84f3-7ae4be813b80.png)

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

[MarlinV2.0-bugfix_ConfigurationFiles.zip](https://github.com/MarlinFirmware/Marlin/files/3892108/MarlinV2.0-bugfix_ConfigurationFiles.zip)

**Comment by boelle** [comment]
have you tried vscode+platformio ? i think atom is dead and outdated

**Comment by ellensp** [comment]
These configuration.h files are not current...  Many define names have to be updated  
I suspect this is not from the current official marlin github repository.

**Comment by boelle** [comment]
@GadgetAngel if these files are not from the marlin github repro we cant help you, you will have to ask for help where you got marlin from

**Comment by GadgetAngel** [comment]
I got those configuration.h files from the Marlin branch about 3 months ago.  Are you telling me you want me to download and reset ALL my customized Marlin firmware again from scratch?? That’s a lot of work, don’t you think?  If The only way you will help me is to either switch to VScode+Platformio and re-Download the MarlinV2.0-bugfix AND redo All my customizations then I ask that you provide me the http link to download the version you want me to have.

**Comment by GadgetAngel** [comment]
BTW, I thought ATOM+Platformio was the official editor for Marlin, is that not correct? Because that’s why I am using the ATOM editor.

**Comment by boelle** [comment]
nope vscode + platformio is the recommended one

https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

**Comment by boelle** [comment]
if the customize work is in the 2 config files you can use a tool like winmerge to compare your config with the one in marlin and then copy over the settings

**Comment by GadgetAngel** [comment]
since that is the case, please ask the people who maintain the pages for Marlin to Remove ATOM+Platformio as one of the editors to be used: 

![41D08BFB-8257-4DB9-A2B7-5735818C3E26](https://user-images.githubusercontent.com/33468777/69724217-7b489480-10e9-11ea-9ebd-afc982769781.png)

I have been dealing with software all my life and I am a master degree EE who has done instrumentation and control engineering as my career. I am now retired. 

I will switch to VScode+Platformio but if you will not help people who use ATOM+Platformio then please remove it from the list of recommended editors. It’s no big deal for me to move to VScode but for other users this would be a big task. 

I am still of the opinion that these GCC code errors need to be solved for ATOM+Platformio because ATOM+Platformio IS Listed as an editor.  I hope you can determine what the problem is.  If the solution is to NOT use ATOM, fine just tell me that.

Sorry I am now stepping down off my soap box.

**Comment by boelle** [comment]
> but if you will not help people who use ATOM+Platformio then

where did i say that?

**Comment by p3p** [comment]
@GadgetAngel Atom is still a valid editor but PlatformIO decided to move to VSCode as their editor of choice, the editor you use is of course up to you.

Saying that, the errors you are seeing are a problem with the linter software not being able to parse the C Preprocessor correctly as it doesn't know to pull in the required headers, This isn't a problem with the Marlin build, it's a cosmetic feature of the editor, so there is nothing we can do about them.

**Comment by GadgetAngel** [comment]
> > but if you will not help people who use ATOM+Platformio then
> 
> where did i say that?

If I read it wrong I apologize to you

**Comment by GadgetAngel** [comment]
> @GadgetAngel Atom is still a valid editor but PlatformIO decided to move to VSCode as their editor of choice, the editor you use is of course up to you.
> 
> Saying that, the errors you are seeing are a problem with the linter software not being able to parse the C Preprocessor correctly as it doesn't know to pull in the required headers, This isn't a problem with the Marlin build, it's a cosmetic feature of the editor, so there is nothing we can do about them.

Thank you p3p!! So basically if I stick with ATOM editor I will always see this due to the linter software....OK so I am now going to make the switch to VScode...I already use VScode for openHAB so it’s no big deal... You can close this bug so far as I am concern

Thank you all for your input

But mostly for maintaining Marlin SW

If I offended anyone, I do apologize

**Comment by boelle** [comment]
> nope vscode + platformio is the recommended one

but as @p3p said its up to you what you use :-D

but yes there are some benefits to vscode and platformio combo

**Comment by boelle** [comment]
> If I offended anyone, I do apologize

not me, passed the age of 42 and found out that life is short enough as is, so why waste time on small things :-D

**Comment by Patag** [comment]
Wow I'm 10y older than you !?! @boelle
