### ISSUE TITLE
[BUG] No PWM on STM32F446 + bltouch

### ISSUE THREAD

**Issue by DropbearNinja** [MarlinFirmware/Marlin#16008]
### Description

Setting up marlin with bltouch on a stm32f446 board
The probe does its' self test, but there is no blue led (indicating a pwm signal), and does not respond to any gcode
The probe is fine, checked on another printer and functions properly
I've got it hooked up to the right PWM pin

### Steps to Reproduce

In my pins.h"
```
#define NUM_SERVOS 1
#define SERVO0_TIMER_NUM 8
#define SERVO0_PIN         PD15
```

In config.h
`#define BLTOUCH`

In config_adv.h
no extra options enabled

**Expected behavior:** 
PWM signal

**Actual behavior:** 
no PWM signal

#### Additional Information
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3891743/Marlin.zip)

Many thanks for help

**Comment by xC0000005** [comment]
What environment and variant is set for this board?

**Comment by Drachenkaetzchen** [comment]
I can kinda confirm the issue. In my case, it's a Fysetc S6 board. Toggling the pin is fine with `M43`, verified using an oscilloscope. No change to the voltage when using `M280 P0 S10´ (stays at 0V).

Could be a general PWM issue, as the fan mosfets on the S6 also don't seem to receive any signal (need to verify though).

**Comment by boelle** [comment]
@DropbearNinja still arround?

**Comment by xC0000005** [comment]
I would look at the variant’s pins configuration to see if PWM is configured for it. The ST core doesn’t log an error if it isn’t. It’s in the variant pins c file.

**Comment by DropbearNinja** [comment]
Still here
Board is Rumba32
Environment?

**Comment by boelle** [comment]
> Environment?

what do you use to compile marlin

**Comment by DropbearNinja** [comment]
Arduino IDE

**Comment by DropbearNinja** [comment]
For comparison, mk4duo works out of the box

**Comment by boelle** [comment]
what version?

have you tried vscode+platformio ?

**Comment by DropbearNinja** [comment]
1.8.10

No I haven't

**Comment by boelle** [comment]
try 1.9 beta

that and vscode is the recommended these days

**Comment by boelle** [comment]
@DropbearNinja did it make any difference?

**Comment by DropbearNinja** [comment]
1.9 no
and i cant use vscode - platformio doesn't support my board

**Comment by DropbearNinja** [comment]
So my bltouch works fine using mk4duo + stm32duino + rumba32 (stmf446) + arduino IDE

Changing just to Marlin, everything else the same, no luck - has to be some way in which Marlin uses servo.h/cpp or timers.h?

**Comment by boelle** [comment]
i have no idea, i'm just the custodian dusting off the issue list and make sure title of issue is right  and that people dont forget to read the issue template

**Comment by DropbearNinja** [comment]
I managed to solve this, see https://github.com/Aus3D/RUMBA32/issues/8
