### ISSUE TITLE
[BUG] M112 in combination with Emergency_Parser does not behave properly

### ISSUE THREAD

**Issue by basgoossen** [MarlinFirmware/Marlin#16015]
With emergency parser enabled, M112 does not directly kill the machine. Instead it will pause for a second and afterwards moves from the buffer will be execured untill the buffer is empty.

This might lead to dangerous situations especially on big machines with potential long moves and large consequence.

More info and discussion about the problem can be found here: 
https://forum.v1engineering.com/t/skr-1-3-marlin-2-0-m112-em-halt-issue/12945/10

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by basgoossen** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3894213/Configuration.zip)
As per request. However my personal configuration files here are seemingly irrelevant (at least on the LPC1768). As the bug can be reproduced in 2 simple steps:

- Enable EMERGENCY_PARSER
- Send:
     G1 X50 Y50 F500
     G1 X100 Y50 F500
     M112
Next: Watch the machine complete the GCODE instead of EM Stopping, even though the serial stream stating:  "Printer halted. Kill() called!"

**Comment by boelle** [comment]
since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by boelle** [comment]
is the issue still the same with all the updates in the last 28 days?

**Comment by boelle** [comment]
btw, who can confirm there is an issue? use the same configs as OP and the same hardware if possible

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
