### ISSUE TITLE
My capacitive sensor is not detected 

### ISSUE THREAD

**Issue by Jimmy-Bondi** [MarlinFirmware/Marlin#16039]
I have a Geeetech Prusa i3 b pro (GT2560 A+)

I have installed 1.1.9 and my capacitive sensor is not detected.

I have done the following:
#define Z_MIN_ENDSTOP_INVERTING true
define Z_MIN_PROBE_ENDSTOP_INVERTING true
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define FIX_MOUNTED_PROBE

Without success - LED of the sensor lights up but with M119 the switch is still not active!

**Comment by ellensp** [comment]
Most likely a hardware issue, not a firmware issue. Please ask on https://reprap.org/forum/index.php  and you will need to add in more information, make and model of sensor and how you have wired it to the controller.

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
