### ISSUE TITLE
I cant Find Hot Use Hot End Fan Pins

### ISSUE THREAD

**Issue by DarkRecent** [MarlinFirmware/Marlin#16033]
I was upgrading my ender 3 pro with BTT SKR V1.3 and I was Doing it By watching This Video https://www.youtube.com/watch?v=GNGN2iSQ5j4 at minute 13.40 he uses auto fan feature The problem is my hot end cooling fan is not defined in pins.h . My question is how can I define Fan ports (I wanna use for HE1 2.4 pin) to stay active all time time or with auto fan feature. Btw That is The diagram for pins 
![resim](https://user-images.githubusercontent.com/36361171/69750644-504c5800-115e-11ea-9b21-aadbe13b2e2d.png)

**Comment by AnHardt** [comment]
Search for AUTO_FAN in Configuration_adv.h
Just put the pin_name/number in.
If already used in the pin-file, replace there with -1.

**Comment by DarkRecent** [comment]
sorry tho it was my stupidity. Looks like I wrote -P2_04 insted of P2_04 fixed it and now it's working perdectly ty for your time tho ^^
