### ISSUE TITLE
[BUG] Baby step double click not working

### ISSUE THREAD

**Issue by Neiljclements** [MarlinFirmware/Marlin#16043]
[Config_Files.zip](https://github.com/MarlinFirmware/Marlin/files/3903308/Config_Files.zip)
I am using an SKR1.3 with a 12864 Mini RGB display and it won’t allow you to access baby steps via a double click of the encoder.

When you try and double click it just returns to the info screen. I have tried clicking multiple times and at varying speeds, but nothing works.

I have read of similar issues with the 12864 Mini (non RBG) where is was solved by increasing the buffer size to 64 or 128, which I have tried, but it still won’t work. However, after increasing the buffer size I could access the menu options, which I couldn’t before, so I think there may be a connection.

I think the issue is similar to a previous bug report where the menu options couldn’t be accessed when the printer began printing and increasing the buffer size improved it. It doesn’t appear to be the case with the RGB version of the 12864 Mini.

I can access the Z offset menu via the ‘Tuning’ menu option once the print has begun. .

**Comment by Vertabreak** [comment]
to get the double click menu to work on my board i had to up the delay time to like 2 seconds for it to work hope this helps.

**Comment by Neiljclements** [comment]
Was this with the Mini RGB? Also, whilst I really appreciate the suggestion, which I will definitely be trying, that’s more of a workaround than a fix. I’m hoping there’s a proper fix so it operates like other displays. Thank you for the speedy reply. I’ll let you know if that works for me

**Comment by Vertabreak** [comment]
until i change the delay to be longer i simple was unable to click it fast enough to trigger it seems more like a over sight then a bug.

**Comment by Neiljclements** [comment]
Ahhhhh, so you’re saying it’s likely to do with double click timing, which you solved by increasing the delay to 2 seconds. Sorry, I misunderstood what you meant. So, you set it to 2000?

**Comment by Vertabreak** [comment]
i did but you may wish to try 3k or 4k if its still to short.
#define DOUBLECLICK_MAX_INTERVAL 2000   // Maximum interval between clicks, in milliseconds

**Comment by boelle** [comment]
this is most likely to be an issue of not doing the double click correct

you just have to get the click speed right

will close and we can reopen if it turns out to be a bug as such

**Comment by Neiljclements** [comment]
Yes, I'm doing the double click correct.  I have four other printers I use baby steps regularly and I have tried numerous times, at numerous speeds.
I have tried chaging the double click interval all the way up to 5000ms and it still won't work.

The only way I can access it is via the Tuning menu option.
