### ISSUE TITLE
[BUG] MKS Robin tft V2.0 don't work-  There are no buttons to move in the menus.

### ISSUE THREAD

**Issue by NachoFrutos** [MarlinFirmware/Marlin#16046]
Hello, today I have downloaded the latest version of marlin 2.0. I have compiled and generated the .bin file for the mks_robin board. And on the TFT screen you only see the information of the values. but noy there are buttons to enter the menus. attached configuration files.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3906112/Marlin.zip)

**Comment by shitcreek** [comment]
<del>The Marlin status screen is meant for displays with a dial button - it has no on screen button - even if it does, it would not be touchable.  You'll need to use the touch interface that came with your TFT. </del>

Here is a great how-to tutorial by Chris' Basement: https://www.youtube.com/watch?v=f651bIg4SCo

**Comment by thisiskeithb** [comment]
@shitcreek These boards have a tethered "dumb" tft that when the Robin is flashed with stock Marlin, they revert to the basic 12864/Marlin UI with touch buttons underneath (something like this, it's probably changed):

![image](https://user-images.githubusercontent.com/42916376/61160802-ee50c600-a4ce-11e9-9d5a-ebd1d4ec4e95.jpg)

They worked when I originally submitted the pins for the Robin boards, but code around the TFT has changed enough to break and I don't have physical hardware to test with for further debugging.

Maybe @tpruvot has some insight since those changes broke original functionality for the Robin TFTs 🙂

**Comment by shitcreek** [comment]
I stand corrected.

**Comment by thisiskeithb** [comment]
It's also what is holding up working Tevo Nereus configs unless @zillarob has some good news.

**Comment by KosVas91** [comment]
`//#define TOUCH_BUTTONS`
According to your config, you forgot to enable Touch Buttons.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by KosVas91** [comment]
> 
> 
> Configurations, please
> Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
> requested in the Issue template) and drop them into your next reply.
> We'll check them over and see if anything is amiss.

Topic starter attached config to the first post... and TOUCH_BUTTONS are not defined there.

**Comment by boelle** [comment]
uppsi, did not see the link to config :-(

**Comment by zillarob** [comment]
> It's also what is holding up working Tevo Nereus configs unless @zillarob has some good news.

I havent played with that one for a bit, may have to break it out again.

Like Kos said above though, he needs to start by enabling the buttons.

**Comment by tpruvot** [comment]
there is a sample config in marlin

**Comment by boelle** [comment]
We need actual config and not example ones??? Or did you mean the example config was a starting point?

**Comment by tpruvot** [comment]
i tested it ok during the last fix... with the sample in marlin tree, the one also used for travis test..

**Comment by boelle** [comment]
so is this one an user error with the config?

**Comment by tpruvot** [comment]
https://drive.google.com/file/d/19zjFjk2XoG93TN7go9lv5q_XIunrDD6u/view?usp=sharing

**Comment by boelle** [comment]
why a link to picture? you can just paste it here

**Comment by boelle** [comment]
![image](https://user-images.githubusercontent.com/3832239/69996012-73f21280-1551-11ea-93af-e4754fdf3c8a.png)
 posted on behalf of @tpruvot

**Comment by tpruvot** [comment]
was a test when i fixed the TFT in the last commit/PR

**Comment by boelle** [comment]
open in windows paint, ctrl+a followed by ctrl+c
then here ctrl+v

**Comment by boelle** [comment]
but my question remains, is there a bug in marlin or is it a user error (config error)

**Comment by tpruvot** [comment]
look like an user side error, if he didnt enable touch buttons... cant be working touch buttons

```
//=============================================================================
//============================  Other Controllers  ============================
//=============================================================================

//
// ADS7843/XPT2046 ADC Touchscreen such as ILI9341 2.8
//
#define TOUCH_BUTTONS
#if ENABLED(TOUCH_BUTTONS)
  #define BUTTON_DELAY_EDIT  50 // (ms) Button repeat delay for edit screens
  #define BUTTON_DELAY_MENU 250 // (ms) Button repeat delay for menus

  /* MKS Robin TFT v2.0 */
  #define XPT2046_X_CALIBRATION    12013
  #define XPT2046_Y_CALIBRATION    -8711
  #define XPT2046_X_OFFSET           -32
  #define XPT2046_Y_OFFSET           256

  /* MKS Robin TFT v1.1 */
  //#define XPT2046_X_CALIBRATION -11792
  //#define XPT2046_Y_CALIBRATION   8947
  //#define XPT2046_X_OFFSET         342
  //#define XPT2046_Y_OFFSET         -19
#endif
```

config/examples/Mks/Robin/Configuration.h

**Comment by boelle** [comment]
oki will close then

we can reopen if its a true bug

**Comment by NachoFrutos** [comment]
Hello, activating the #define TOUCH_BUTTONS option. the buttons appear but now it does not work when the button is pressed. I guess you have to calibrate the screen because with the values ​​of mks robin tft v2.0 it doesn't work. Is there any documentation or video that explains how to calibrate the screen? I test the screen when the board is connected by usb. I have no connected drivers or temperature sensors.. thank

**Comment by tpruvot** [comment]
even with wrong calibration values, the screen should be clickable somewhere... mirrored or rotated...

I did my test with the pasted values, and as you can see on the picture, its the V2.0 too

**Comment by thisiskeithb** [comment]
Makerbase updated their [Robin repo](https://github.com/makerbase-mks/MKS-Robin) recently, so could someone check if their version works still? I don't own any Robin/Robin Nano boards, so I can't help debug on that front.

If that code works, then it should be easy to port whatever settings/changes they made to get these tethered TFTs working properly on all Robin/Robin Nano boards.

**Comment by NachoFrutos** [comment]
Hi, I deleted all the files and downloaded the latest version marlin again. I have compiled with the sample files of mks robin. And everything works. Thank you very much. It can be completely closed. The problem has been user configuration error. I am very sorry for the waste of time and thank you all very much.
