### ISSUE TITLE
[BUG] Fysetc S6 PWM duty cycle too low

### ISSUE THREAD

**Issue by Drachenkaetzchen** [MarlinFirmware/Marlin#16056]
### Bug Description

When setting Fan1 speed to 100%, the PWM duty cycle is only 6% on the Fysetc S6.

### Workaround

Use `FAN_SOFT_PWM`.

### My Configurations

[Configuration.h](https://github.com/Drachenkaetzchen/Marlin/blob/PurpleCube-S6/Marlin/Configuration.h)
[Configuration_adv.h](https://github.com/Drachenkaetzchen/Marlin/blob/PurpleCube-S6/Marlin/Configuration_adv.h)

### Steps to Reproduce

1. Set Fan1 to 100%

**Expected behavior:**

PWM duty cycle of 100%

**Actual behavior:** [What actually happens]

PWM duty cycle of 6%

![DS1Z_QuickPrint6](https://user-images.githubusercontent.com/162974/69902562-92101500-138f-11ea-83ec-c369662a9fe8.png)

**Comment by Drachenkaetzchen** [comment]
When using `FAN_SOFT_PWM` the duty cycle is 100%, as expected.

**Comment by sjasonsmith** [comment]
This is similar to the SKR Pro behavior before the changes @LinoBarreca made, including the 20 kHz frequency you see here.

**Comment by LinoBarreca** [comment]
what kind of board is it? which architecture?

**Comment by LinoBarreca** [comment]
STM32... that's why. with 5.8.0 they should have fixed it. there was a bug in the duty cycle calculation which I think I saw being handled.

**Comment by LinoBarreca** [comment]
meanwhile you can just lower the PWM frequency, as I did in the skr-pro, to 1khz to have the correct duty cycle

**Comment by Drachenkaetzchen** [comment]
I think I tried that, but it had no effect. Maybe I messed something up, will try again later to verify

**Comment by Drachenkaetzchen** [comment]
I have found the relevant upstream issue:

https://github.com/stm32duino/Arduino_Core_STM32/issues/790

So it's related to 8 bit to 12 bit mapping and not the frequency.

**Comment by boelle** [comment]
i just made an PR to fix scara printers and that made me think on other issues

so if you know how to fix this one just let me know what file to change or add (or remove) and i could submit the PR

sorry if this is bad formulated (not the sharpest pencil arround)

**Comment by Drachenkaetzchen** [comment]
> i just made an PR to fix scara printers and that made me think on other issues
> 
> so if you know how to fix this one just let me know what file to change or add (or remove) and i could submit the PR
> 
> sorry if this is bad formulated (not the sharpest pencil arround)

it's an upstream issue, see link above

**Comment by boelle** [comment]
can marlin as project do anything about that?

**Comment by Drachenkaetzchen** [comment]
> can marlin as project do anything about that?

yes, wait for a newer upstream release and update library refs then

**Comment by Drachenkaetzchen** [comment]
also, of course, test with the new upstream release and verify that it works correctly. If not, notify the upstream authors and see what we can do to make it work.

**Comment by dinamitemic** [comment]
Hi, I've (hopefully) found a solution for this problem. 
As reported in this [PR](https://github.com/stm32duino/Arduino_Core_STM32/pull/814) from the stm32 core there is a problem in the definition of the pwm resolution.
In particular we've to change it in **buildroot\share\PlatformIO\variants\FYSETC_S6\variant.h** 
from:
`#define PWM_RESOLUTION          8`
to: 
`#define PWM_RESOLUTION          12`
Tryed it and now it works as expected. Tested with oscilloscope. [DEMO VIDEO](https://youtu.be/cgMZDhy4dXU)
 I think that from latest updates the default resolution is 12 bits and there is no need to declare it anymore, but not tested yet.
[HERE](https://github.com/dinamitemic/MarlinFW/commit/1e4b2526631ac713657189fdf9556756f6def42f) my commit with the proposed solution starting from v2.0.4.2

**Comment by sjasonsmith** [comment]
This is most likely already fixed. I will test it on my board to be sure.

**Comment by sjasonsmith** [comment]
I just tested this and verified that the duty cycle is now correct. Closing this as fixed.
