### ISSUE TITLE
[FR] (Auto cooldown extruder if not used)

### ISSUE THREAD

**Issue by italocjs** [MarlinFirmware/Marlin#16075]
Hi,  i had noticed a issue in particular on the machines we have, that when people heat the nozzle for whatever reason (like remove or change filament, just extrude, or preheat) and forget it heated the plastic degrades (turns brown or black and carbonize) sometimes clogging the printer.  

Is it possible to create a new config on where we could choose a timeout to cooldown the hotend if the printer doenst perform any extrusion movement?

**Comment by randellhodges** [comment]
A heater timeout would be a good feature. 

In the mean time, if you have Octoprint connected, there is a heater timeout plugin available that do this.

**Comment by italocjs** [comment]
This feature has been developed and its available on latest bugfix, Closing.
