### ISSUE TITLE
Junction Deviation missing from configuration_adv.h

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#16085]
I am doing the code compare between my BugFix configuration_adv and the release 2.0.0 configuration_adv.h.  Tedious but easy. I did discover that Junction Deviation appears missing in the release..

`#define JUNCTION_DEVIATION`  and the related code is not there.

Is this intentional, an oversight, renamed or did it move to a spot where I am not finding it?

**Comment by ManuelMcLure** [comment]
``JUNCTION_DEVIATION`` is now the default so there is no option for it. Instead you can disable it by enabling ``CLASSIC_JERK``.

**Comment by boelle** [comment]
will close this one as its a user misunderstanding and not a bug
