### ISSUE TITLE
[BUG] 'TMC_SW_MOSI' was not declared in this scope

### ISSUE THREAD

**Issue by Deema35** [MarlinFirmware/Marlin#16080]
### Bug Description

'TMC_SW_MOSI' was not declared in this scope

### My Configurations

BIGTREETECH SKR mini V1.1

### Steps to Reproduce

1. Enabel SPI mode
2. Compile code

#### Additional Information
I have solve thise bug by swap two line in file: pins_BTT_SKR_MINI_V1_1.h
![Безымянный](https://user-images.githubusercontent.com/11281841/70018260-9ce8c680-1596-11ea-9606-2f8153a8eb21.png)

**Comment by shitcreek** [comment]
closing since the fix has been merged.
