### ISSUE TITLE
[BUG] Dead link for AZSMZ 12864 LCD with SD

### ISSUE THREAD

**Issue by madmodder123** [MarlinFirmware/Marlin#16102]
The following link in Configuration.h is dead:

// AZSMZ 12864 LCD with SD
// https://www.aliexpress.com/store/product/3D-printer-smart-controller-SMART-RAMPS-OR-RAMPS-1-4-LCD-12864-LCD-control-panel-green/2179173_32213636460.html

Here is a live link directly from the AZSMZ store: https://www.aliexpress.com/item/32837222770.html
It also has some tutorials and links to thingiverse files to for mounting.

**Comment by shitcreek** [comment]
I've created the PR for this: https://github.com/MarlinFirmware/Marlin/pull/16106
Thanks.
