### ISSUE TITLE
[BUG] Software endstops ignore M206 settings

### ISSUE THREAD

**Issue by karabas2011** [MarlinFirmware/Marlin#16101]
recent Marlin 2 snapshot
SKR1.1 pro and SKR1.3
cartesian with Zmax homing

Since IDEX in duplicate mode does not need bed leveling and I turned it off, I tried to findout a way to set Zoffset via menu with M206. I wrote a hack to do this, but faced with the above problem.

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

Home to Z max
M114 shows Zmax
M206 Zxxx add offset
G28 Z
G1 Z0
M114 shows Zxxx insteed of 0

**Expected behavior:** [What you expect to happen]
M114 shows Z0

**Actual behavior:** [What actually happens]
M114 shows Zxxx insteed of 0

#### Additional Information
Currently workaround is to turn off software endstop Zmax

**Comment by ellensp** [comment]
the axis length does not change. you add xxx to Zmax, then Zmin becomes xxx

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
will close this one until requirements in the issue template are satisfied
