### ISSUE TITLE
Blank REPRAP_DISCOUNT_SMART_CONTROLLER

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#1611]
Get a blank display on plain Chonfiguration.h jut with uncommenting REPRAP_DISCOUNT_SMART_CONTROLLER beginning with commit https://github.com/thinkyhead/Marlin/commit/c37f7d15c9901fa839eb3dc16e84202d959965e8
Arduino 1.06

**Comment by avluis** [comment]
I am getting a blank display as well, could be this: https://github.com/MarlinFirmware/Marlin/pull/1607
Not 100% sure yet.

**Comment by avluis** [comment]
Looks like the serial interface is crashing after a bit of idle - cannot connect - so far I have to reset the printer to reconnect (to be able to flash - cannot connect long enough to print).

**Comment by AnHardt** [comment]
Got it! See #1615 
Pretty much all can have been affected.
