### ISSUE TITLE
[BUG] Latest Hourly build 

### ISSUE THREAD

**Issue by hawkeyez88** [MarlinFirmware/Marlin#16111]
Sorry about that - I was making some progress. Latest Error attached. Using latest nightly with Arduino 1.9.0 beta.

Arduino: 1.9.0-beta (Windows 10), Board: "Anet V1.0"

error: https://pastebin.com/j6qJkJ5G

**Comment by ellensp** [comment]
It's a little vague.

**Comment by boelle** [comment]
@hawkeyez88 and your error log is way to long, please use a site like paste bin

did it for you this time

**Comment by boelle** [comment]
can you compile with other versions of arduino IDE?

have you tried vscode+platoform.io ?

**Comment by hawkeyez88** [comment]
Thanks @boelle. I'll get the hang of github soon enough. I tried 1.8.8, 1.8.4, and 1.8.10. I have not tried cscode+platform.io. I will do that and report back. Thank You!

**Comment by boelle** [comment]
have you tried arduino ide 1.9 beta?

**Comment by hawkeyez88** [comment]
That was the first one I tried with.

**Comment by hawkeyez88** [comment]
The anet v1 board doesn't show up in vscode+platform.io when I try to import the arduino project, assuming that's what you wanted me to do?

**Comment by ellensp** [comment]
You don't import it, you open the folder that has the platformio.ini file.

**Comment by hawkeyez88** [comment]
With the latest error on the latest beat version of arduino again I'm back to this error :  
c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: region `text' overflowed by 7396 bytes

I was reading other pages on this for the past couple of days and haven't gotten anywhere, is it possible the board doesn't have enough free space for the new Marlin :(

**Comment by ellensp** [comment]
Times are moving on, 644p based controllers are long dead, 1284p  based controllers (such as the ANET V1.0) are in serous strife.  If you enable advanced features, such as ABL, and GLCDs, It just wont fit any more.  Now It could possibly be made to work, If someone want to put the many hours of work into optimizing the firmware. Or you could buy a modern controller for $25  dollars.

**Comment by boelle** [comment]
as @ellensp said with 644p options are slim to put it mild

https://github.com/boelle/Marlin/tree/OMC-with-SD-and-BEDLEVEL

is a setup for a 644p based printer, i had to disable a lot to make it fit, but i managed to have sd print and manual bed level

but things like saftety etc are gone-ski, i mainly have that setup for my first printer i got, not using it much but still keeping it just in case and for job where quality does not matter

**Comment by boelle** [comment]
will close this one as its not error in marlin as such

its a combination of limiting hardware and to many features enabled
