### ISSUE TITLE
Strange Message on Statusline

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#1612]
Get a strange Message on the Status-line since  https://github.com/thinkyhead/Marlin/commit/e3ca9137b54a908e240679c4546c3e301ad90edf

Plain Configuration.h. Just commented out REPRAP_DISCOUNT_SMART_CONTROLLER.

![picture 110](https://cloud.githubusercontent.com/assets/211931/6657731/69e35854-cb54-11e4-9925-cc1a2d230f9f.jpg)
expexted:
![picture 111](https://cloud.githubusercontent.com/assets/211931/6657733/7207b228-cb54-11e4-9c71-41f062f92bf7.jpg)

**Comment by thinkyhead** [comment]
Merged!
