### ISSUE TITLE
[BUG] lcd problem with u8glib

### ISSUE THREAD

**Issue by renzaaa** [MarlinFirmware/Marlin#16121]
![20191205_214622](https://user-images.githubusercontent.com/1631364/70270233-9df34100-17ac-11ea-9e97-c0ac086a246f.jpg)

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
also does it compile ? what do you use to compile?

**Comment by shitcreek** [comment]
Are you certain this is a bug and not a configuration, electrical or mechanical issue? Have you searched the issue queue to see if this issue hasn't been brought up and or resolved?
I've found this seemingly similar issue:
https://github.com/MarlinFirmware/Marlin/issues/5756

**Support Question?**
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**After seeking help from the community**, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**ALSO** you must follow the template and provide more information for people to have more of a clue as to what is going on - please do not expect people to do all the guesswork
