### ISSUE TITLE
[BUG] Endstops do not trigger on RAMPS

### ISSUE THREAD

**Issue by T-SquaredProductions** [MarlinFirmware/Marlin#16132]
### Bug Description

I tried to autohome my printer, but even with the endstops attached and their LEDs activating when hit, the printer will not properly home.

### My Configurations
[MARLINCONFIG.zip](https://github.com/MarlinFirmware/Marlin/files/3934414/MARLINCONFIG.zip)

### Steps to Reproduce

1. Use RAMPS 1.6
2. Go to 'Motion'>'Auto Home'

**Expected behavior:** I expected the printer to autohome to the minimum coordinates at the front left of the heating bed.

**Actual behavior:** The z-axis rises, the bed moves toward the user, and the z-axis rises again, as if the endstops have already been triggered. (Also, if reversed, the endstops will not stop the motors)

**Comment by boelle** [comment]
check your endstops with M119

ie make sure they are all NOT activated, then send M119 and see what the printer thinks

then put your finger on each endstop (one at a time) and send M119 again

**Comment by boelle** [comment]
@T-SquaredProductions since 2.0 was just released a few days ago has this changed this issue at all?

**Comment by boelle** [comment]
@T-SquaredProductions did you check the endstops?

**Comment by T-SquaredProductions** [comment]
> @T-SquaredProductions did you check the endstops?

Pronterface reports all of them are triggered when they are not. Do I need to invert their logic?

(Also, sorry for the delay. I've been working like mad on a project that I need to make in time for December 31st.)

**Comment by ManuelMcLure** [comment]
And they report open when you do trigger them? If so, then yes - you need to invert the logic.

**Comment by T-SquaredProductions** [comment]
Ok, Endstop problems fixed. They report normally, but now I have another problem that led to this: The z-axis motor moves up normally, but after that, motors do not engage or move, and after a few seconds, the printer halts with the usual "ERROR: Printer Halted. Please Reset." message. Pronterface reports a "Error:Printer halted. kill() called!" echo message.

**Comment by boelle** [comment]
better you hit close on this one and create a new since problem is not the same and config also have changed
