### ISSUE TITLE
[BUG] Compile Error Fysetc S6 

### ISSUE THREAD

**Issue by TB1405** [MarlinFirmware/Marlin#16137]
### Bug Description
Compiling my config isnt possible with the Fysetc S6 (for SKR PRO it works)
Have also added my pins_FYSETC_S6 because you need for compiling a filrunout Pin 

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3935287/Configuration.zip)
### Steps to Reproduce
load my config files into the marlin 2.0 build and try to compile  

Error 
https://pastebin.com/MZseXr1D

**Comment by sjasonsmith** [comment]
That is an odd error, as it isn't actually a compilation problem, more like the linker was executed with invalid arguments.

I can build your configs just fine from PlatformIO within VSCode on Windows. I tested building them on top of both the 2.0 and bugfix-2.0.x branches.

**Comment by TB1405** [comment]
But i only have a .elf firmware file. S6 needs also binary file or not?

**Comment by sjasonsmith** [comment]
My build generates a firmware.bin file at `Marlin/.pio/build/FYSETC_S6/firmware.bin`

**Comment by TB1405** [comment]
I sure i only have a firmware.elv file. 
I will check this tomorrow

**Comment by sjasonsmith** [comment]
The error output you posted does look related to packaging the final binary, so I believe that you probably are missing the .bin file, I just don't know why.

Make sure you have all your components updated in Platform IO. If you are in VS Code, you can find it here:

![image](https://user-images.githubusercontent.com/20053467/70380446-a18fe080-18f0-11ea-8a66-bacc472fe8f3.png)

**Comment by TB1405** [comment]
Same problem after the update. it only generate a .elf file and the error 1
also tried it with the newest bugfix

**Comment by boelle** [comment]
tried to hit the trashcan symbol?

![image](https://user-images.githubusercontent.com/3832239/70627488-973e5100-1c26-11ea-9a12-80edac72b972.png)

or delete these 2 folders?

![image](https://user-images.githubusercontent.com/3832239/70627529-aa512100-1c26-11ea-80ff-74939dc3e2ef.png)

of course need to restart vs code

**Comment by TB1405** [comment]
@boelle 
tried both but same problem

**Comment by TB1405** [comment]
have a new laptop and with this one it works.. dont know where was the problem.

**Comment by ModestAndroid** [comment]
I'm having this same issue. I've tried some of the suggestions above, as well as reinstalling Atom. Same error for Fysetc S6... 

Tried Atom and VSCode, same error.
