### ISSUE TITLE
Arduino EEPROM not pin marlin data???

### ISSUE THREAD

**Issue by RichardFalcos** [MarlinFirmware/Marlin#16134]
Hi, after a lot of research, I set up my first 3D printer, now I am setting up my second 400x400x400 printer, I am facing a problem that so far I could not solve. When I turn on, all motors spin in one direction only, and I don't know why they only spin both ways when I start EEPROM memory from the LCD panel, there in control> start EEPROM, when I turn it off, everything goes back, I've done several tests and nothing. Has anyone seen anything like this? Thank you

**Comment by ellensp** [comment]
No Configuration files... cannot look into this without them.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
