### ISSUE TITLE
[BUG] M48 not working

### ISSUE THREAD

**Issue by Geert-S** [MarlinFirmware/Marlin#16131]
I can't seem to get M48 working. Using the terminal of octoprint i send a M48 to the printer, it replys with: "Recv: echo:Unknown command: "M48""

**Comment by Drachenkaetzchen** [comment]
You have to explicitly enable that feature in your config as documented on [http://marlinfw.org/docs/gcode/M048.html](http://marlinfw.org/docs/gcode/M048.html)

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
since the issue template has not been followed i will close this one until all requirements in the issue template  is meet
