### ISSUE TITLE
[BUG] G29 Probing failed after 1 Probe Point

### ISSUE THREAD

**Issue by ilakuli** [MarlinFirmware/Marlin#16146]
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/3936177/Configs.zip)
### Bug Description

After updating from Bugfix to Marlin 2.0 release, my bltouch on my CR10S with SKR Pro board is acting weird. It homes normally, also the M48 Test works fine. But when I start a print or issue a G29 manually through console, it probes the first point fine, moves to the second but then does not depoly the bltouch and then of course fails probing.

I used the same BLTouch settings as I used in old Firmware (worked just fine). No hardware changes made to printer.

### Steps to Reproduce

1. Start Print with G29 in start script or issue G29 via Terminal

**Expected behavior:** 

Do 16 Point leveling (and then start printing if print started)

**Actual behavior:**

BLtouch fails to deploy at point 2 and probing fails. Still starts printing normally if print started

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/3936178/Configs.zip)

**Comment by Vertabreak** [comment]
gonna need to post configs for us to see whats happening.

**Comment by ilakuli** [comment]
I'm sorry there must have been an error uploading. I updated my initial comment.

**Comment by ilakuli** [comment]
No ideas?

**Comment by boelle** [comment]
nope no idea, i never had an issue with G29

the only difference we have is the BLtouch, i have an inductive probe

but you cant reuse old configs, use a tool like winmerge to compare old config with the new default and then copy over settings

once firmware is flashed send M502 and then M500, settings can be hiding in eeprom and give the most funny problems

**Comment by ilakuli** [comment]
I didn't use the same config files, I just copied the same settings to the new firmware by hand. But since then I changed to a different board flashed with the newest marlin release (just to test) and the Printer and bltouch work just fine. So I suspect the board has some kind of defect.

**Comment by boelle** [comment]
> So I suspect the board has some kind of defect.

that is not uncommon, a lot of these china boards are made fast and cheap, so errors will happen

**Comment by Thijsvanzwam** [comment]
i have the same issue here on a BTT SKR 1,4 using an inductive probe. Tried a switch at the z-stop connector but same error. When activating ABL using G29 or on the screen it probes 1 point and doesn't respond tot the z-stop at the second probe point, giving an error.
z-stop works fine on autohome so the connection on the board works
[config.zip](https://github.com/MarlinFirmware/Marlin/files/4533993/config.zip)

tried Marlin 2.0.5.3 and bugfix
