### ISSUE TITLE
[BUG] Runout sensor requires manual turn on after triggering

### ISSUE THREAD

**Issue by karabas2011** [MarlinFirmware/Marlin#16161]
### Bug Description

I use Runout sensor  ( actually 2 in 1, runout and spool loop)
During printing when first triggering I see menu 
where I choose extrude more or turn sensor ON. 
I press On and it continues printing. But sensor now is actually OFF. And no second triggering is possible until I go to main menu settings and turn on the sensor!

### My Configurations
Marlin 2.0 29-nov-2019
skr1.3 lcd MKS mini 12864 V2
TMC2208

### Steps to Reproduce

1. Start print
2. force runout to trigger
3. continui
4  force runout to trigger

**Expected behavior:** [What you expect to happen]
Pause as many times as it triggers

**Actual behavior:** [What actually happens]

Paused only first triggering
So menu item - turn on sensor - does not do anything. Or does not apply.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3938478/Marlin.zip)

 
#### Additional Information
Yes I can hack it to insert function to menu that will  autoturn on sensor 

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by InsanityAutomation** [comment]
That menu item toggles the state if the sensor is currently off. It probably needs a condition added to either never or always show it next to continue for motion monitoring sensors, since input state cannot be used directly there.

**Comment by karabas2011** [comment]
My hack. Is it correct?
```
void menu_pause_option() {
  START_MENU();
  #if LCD_HEIGHT > 2
    STATIC_ITEM(MSG_FILAMENT_CHANGE_OPTION_HEADER);
  #endif
  ACTION_ITEM(MSG_FILAMENT_CHANGE_OPTION_PURGE, [](){ pause_menu_response = PAUSE_RESPONSE_EXTRUDE_MORE; });
  #if HAS_FILAMENT_SENSOR
    // if (runout.filament_ran_out)
      runout.enabled = true;
      runout.reset();
      EDIT_ITEM(bool, MSG_RUNOUT_SENSOR, &runout.enabled, runout.reset);
   // else
  #endif
      ACTION_ITEM(MSG_FILAMENT_CHANGE_OPTION_RESUME, [](){ pause_menu_response = PAUSE_RESPONSE_RESUME_PRINT; });
  END_MENU();
} 
```

**Comment by karabas2011** [comment]
I think it is old bug. M119 is not in sync with  FIL_RUNOUT_INVERTING, and the whole runout code behaviouring is inverted.

**Comment by InsanityAutomation** [comment]
Its going to need a bit more than that as the extui handler needs updating as well to take 3 potential responses for runout in case of the encoder style and it needs to be set for only the encoder style.

**Comment by karabas2011** [comment]
No encoder at all. Just one endstop for runout and extra tension
![photo_2019-12-11_11-50-00](https://user-images.githubusercontent.com/2634978/70605921-75d06b80-1c0c-11ea-91a1-6c0c7db896ba.jpg)

**Comment by karabas2011** [comment]
```
  #if HAS_FILAMENT_SENSOR
    if (runout.filament_ran_out) { 
      runout.enabled = false;
      EDIT_ITEM(bool, MSG_RUNOUT_SENSOR0, &runout.enabled, runout.reset); 
      }
    else {
      runout.enabled = true;
      runout.reset();
   //   EDIT_ITEM(bool, MSG_RUNOUT_SENSOR, &runout.enabled, runout.reset);
    }
  #endif
```
Where MSG_RUNOUT_SENSOR0 is a reminder to activate sensor. 

But if I start  print with unactivated sensor, it calls pause but does not allow to turn on sensor...
Only manually via Settings

**Comment by tpruvot** [comment]
see PR #16230 it should fix that

**Comment by karabas2011** [comment]
Thanx! It fixes problem with start printing pause ( when I forget to close sensor ) 
But for my type of sensor I need menu  to prevent resume until I close the sensor.
this is what my code currently does. 

BTW No beeps on filament change! How to make it beep as set in Configuration_adv ?

**Comment by karabas2011** [comment]
New problem
Menu Resume does not reflect off-state of  sensor until you rotate encoder!
When you press "Purge more" regenerated menu assumes the sensor ON and misses menu item Sensor On/OFF, but if you rotate encoder that menu item appears(if sensor really off)!

So  ACTION_ITEM(MSG_FILAMENT_CHANGE_OPTION_PURGE, []{ pause_menu_response = PAUSE_RESPONSE_EXTRUDE_MORE; });
does check state of sensor incorrectly.

**Comment by boelle** [comment]
seems this one was solved, if a new issues had surfaced create a new PR for that

if this issue is not solved we can reopen
