### ISSUE TITLE
[BUG] (Marlin 2.0 SKR 1.3 error const_functions.h)

### ISSUE THREAD

**Issue by winstondm** [MarlinFirmware/Marlin#16173]
good night,

When you try to compile marlin 2.0, you return the following problem:

* Looking for const_functions.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:const_functions.h"
* Web  > https://platformio.org/lib/search?query=header:const_functions.h

What can I do?

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then we can reopen
