### ISSUE TITLE
[BUG] Build error with VS Code on the LPC1768 platform (SKR V1.3) with CR10S config file

### ISSUE THREAD

**Issue by Kaliin** [MarlinFirmware/Marlin#16192]
### Bug Description

I tried to build for the LPC1768 platform with CR10s configuration files(I just got an SKR V1.3) but it fails.

### My Configurations

Clean Windows 10 install (like 5 days ago), I also installed WinRAR.
I made all the necessary step to install VS Code and the platformio extension.
I tried Marlin2.0 downloaded from github, from the website and the bug-fix.
I tried to also compile from a not modified Marlin 2.0 (like just unzip it, and try to compile for the atmega platform but same problem appear)

My configuration files (Configuration.h, Configuration_adv.h and platformio.ini): 
[Configuration files.zip](https://github.com/MarlinFirmware/Marlin/files/3950506/Configuration.files.zip)

### Steps to Reproduce

1. Install VS Code and the platformio extension
2. Download Marlin 2.0.x from github and unzip it
3. Remove Configuration.h and Configuration_adv.h and copy and paste Marlin-2.0.x\config\examples\Creality\CR-10S content to Marlin-2.0.x\Marlin
4. Modify default_envs in platformio.ini to default_envs = LPC1768
5. Modify Configuration.h for the SKR v1.3 platform (change Serial_port, Serial_port_2 and motherboard)
6. Build
7. Fail :(

#### Additional Information

My terminal output: 
[Terminal Output.txt](https://github.com/MarlinFirmware/Marlin/files/3950430/Terminal.Output.txt)

Or with a simple copy and paste:

https://pastebin.com/1wBsNRur

**Comment by boelle** [comment]
please use pastebin.com for error logs

**Comment by ellensp** [comment]
You say all the right stuff, but the config file provided isn't modified for a skr1.3

**Comment by boelle** [comment]
have you tried the cleanup button?

![image](https://user-images.githubusercontent.com/3832239/70624602-e8e3dd00-1c20-11ea-8666-821515834337.png)


and as @ellensp says using the correct config might help too :-)

**Comment by Kaliin** [comment]
Sorry, I sent the wrong files, but the one I compile where modified!
I also tried with the cleanup button, It show success, but when I build it again, it fails.

It seems to me that it can't unpack a file, does anyone know what format is this file? maybe something is missing to my computer and it doesn't allow hom to read it (btw I open VS Code as an admin)

**Comment by ellensp** [comment]
The error listed is definitely something to do with your os...  unsupportedArchiveType: Can not unpack file 'c:\Users\sanfi\Downloads\Marlin-2.0.x\.pio\libdeps\LPC1768\_tmp_installing-gx773gst-package\None':    platformio has to be allowed to download files..  do you have  something blocking files?  overly protective antivirus?    and remove winrar in case it is causing issues.  Windows can unzip zip files without it.

**Comment by boelle** [comment]
attach the correct one so we have the same "picture" as you

**Comment by Kaliin** [comment]
It updated the files, I believe that I closed the Windows anti-virus or protection system, I will check that and desinstall winRar, I keep you updated.
Thank you!

**Comment by boelle** [comment]
if you use the build in windows antivirus it will not block it, it does not do on win10 home 64 bit

**Comment by boelle** [comment]
but yes winrar for zip files are not needed, and you can use free online extractors for most other packed files

http://online.b1.org/online

supports: b1, zip, jar, xpi, rar, 7z, arj, bz2, bzip2, tbz2, tbz, txz, cab, chm, chi, chq, chw, hxs, hxi, hxr, hxq, hxw, lit, cpio, deb, gz, gzip, tgz, tpz, hfs, iso, lzh, lha, lzma, rpm, tar, xar, z, taz, xz, dmg, cb7, cbr,
cbt, cbz

**Comment by Kaliin** [comment]
So, winRAR uninstalled, Windows security totally disabled, same error !
What format is it? Can I circumvent what it try to download? (like downloading and unzipping and pasting it where it should go)
Or is there something else that I should download? Like python or pip?

**Comment by boelle** [comment]
vs code should download everything you need

did you try to click the trash can?


![image](https://user-images.githubusercontent.com/3832239/70626105-12523800-1c24-11ea-929c-390e0bdc3148.png)

**Comment by boelle** [comment]
or delete these 2 folders manual

![image](https://user-images.githubusercontent.com/3832239/70626177-37df4180-1c24-11ea-9b07-128e2dae9370.png)

**Comment by Kaliin** [comment]
Yes I tried it and it succeded, this is the terminal output: https://pastebin.com/YL4Q27ab

I delete both of these folders, and fails again, and in Marlin-2.0.x\.pio\libdeps\LPC1768 there is nothing same with Marlin-2.0.x\.pio\build\LPC1768
(but there is a project.checksum in Marlin-2.0.x\.pio\build )

**Comment by ellensp** [comment]
also try running in verbose mode . To do this click on the console icon (last one on the right of boelle's image and type "platformio run -v"  <enter> It may tell you more about what is going on

**Comment by Kaliin** [comment]
Hmm interesting it showed 3 other errors saying "Platform incompatible library"

https://pastebin.com/V5pyk6cF

**Comment by ellensp** [comment]
himm try deleting the directory C:\Users\sanfi\\.platformio and try again

**Comment by Kaliin** [comment]
This seems to do it, it's building !
So apparently just deleting the .platformio made it reinstall.
I read that it can take some time to build, it has downloaded the U8glib-HAL (up to 100%) and now it just says Building. 
I will wait and if it works than I close the issue!
Thank you both!

**Comment by Kaliin** [comment]
It got stuck but after closing and reopening VS code, the building went smoothly!
Thank you!
