### ISSUE TITLE
[BUG] TMC2130 Doesn't work when powering the board first via USB 

### ISSUE THREAD

**Issue by safaenet** [MarlinFirmware/Marlin#16210]
### Bug Description
I switched from DRV8825 to TMC2130 (IdeaFormer) on all my axis (X, Y, Z, E0). But i couldn't make them move at all. Finally found out that Power Supply must be ON before the USB is connected. I'm using an ATX power supply and really need to have this feature on my Printer. Is there a way to solve this problem ? I have another DIY printer and it uses TMC2130 on X and Y (FYSTEC) but it doesn't have this problem. Is there a problem with the manufacturer ?
Marlin 1.1.9
Ramps 1.4

**Comment by safaenet** [comment]
Just wanted to add that the other printer which has no problem with ATX has an ACTIVE LOW solid state relay on the 12v 30amps power supply to turn it ON/OFF. But this one has a normal ACTIVE HIGH mechanical one on 24v 10amps power supply. Can relay working level be the issue ?

**Comment by safaenet** [comment]
Just changed relay config to ACTIVE LOW and made no difference!

**Comment by thisiskeithb** [comment]
This is normal. TMCs need full 12/24 power initially on boot or you'll see TMC CONNECTION errors.

**Comment by safaenet** [comment]
Isnt there a way to fix it ? to make them work along with ATX PSU ?

> This is normal. TMCs need full 12/24 power initially on boot or you'll see TMC CONNECTION errors.

**Comment by thisiskeithb** [comment]
> Isnt there a way to fix it ? to make them work along with ATX PSU ?

I believe `PSU_POWERUP_DELAY` is the feature you're looking for. See PR #16050:

> Some power supplies require an extended time to come online. In my case, I have a +24V PSU connected via a solid state relay which takes about one second to provide power. In conjunction with TMC2130 drivers, the delay of 100ms is too short and initializing them fail.

**Comment by houseofbugs** [comment]
This is not a bug but a config issue. The issue queue is for firmware bugs only, not technical support. This should be closed.

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
