### ISSUE TITLE
[FR] (Screen Saver Function For OLED Displays)

### ISSUE THREAD

**Issue by borland1** [MarlinFirmware/Marlin#16215]
### Description
Suggestion: Add ability to enable a 'Screen Saver Function' and countdown time-out 'Duration' in Configuration.h file.
Reason: Screen Saver Function could be useful to minimize screen burn-in for OLED displays.

### Feature Workflow
Setup:
1. Enable Screen Saver Function and Timeout Setting in Configuration.h file.

Firmware Operation:
1. When a countdown timer times-out with no rotary encoder input being detected, the display mode status is set to SLEEP (blank display).
2. Any detection of rotation of the rotary encoder, resets countdown timer and changes display mode to AWAKE (active display).

**Comment by ellensp** [comment]
Isn't this issue #4728

**Comment by borland1** [comment]
Similar, but power saving on OLED displays would be negligible.  For FR #4728, LCDs do use significant more power than OLED displays.  This FR is to minimize OLED burn-in over hundreds of hours of use.

**Comment by borland1** [comment]
Closing this. Reconsidering this FR as not necessary.
