### ISSUE TITLE
[BUG] SKR 1.3 SD DOESNT START TO HEAT

### ISSUE THREAD

**Issue by Erokawa** [MarlinFirmware/Marlin#16246]
### Bug Description
With SKR 1.3 i have been using a 2.0 version and everything were going perfectly, the problem is that when i updated the final version of marlin the sd was connecting correctly but when i try to print it doesnt start to heat nothing

PD: just by usb works

### My Configurations
https://drive.google.com/open?id=1U1PNlBJI6Re7Jsqg1XdGLNiTkBMjtan2
**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. try to print something with this config in a skr 1.3
2. if you start a print won't heat nothing will just run the time and it appears the name scrolling in the LCD

**Comment by shitcreek** [comment]
Could you post your gcode file?
Next time, please only include the config files and not the entire Marlin build, thank you.

**Comment by Erokawa** [comment]
Simply3D for some reason was generating gcodes of 0KB xD, okey thanks anyway i'll close this
