### ISSUE TITLE
Array[x] = { 1 }; don't work

### ISSUE THREAD

**Issue by tonnico** [MarlinFirmware/Marlin#1625]
Like in [stepper.cpp](https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/stepper.cpp#L91)
`volatile signed char count_direction[NUM_AXIS] = { 1 };`

This ends in { 1, 0, 0, 0 };
I don't know if this will change something in stepper.cpp but take care of it.

**Comment by alexborro** [comment]
I'm traveling today. Check whether this variable is used anywhere else or
not. I do not remember it.

Cheers

Alex
Em 17/03/2015 06:11, "Wurstnase" notifications@github.com escreveu:

**Comment by tonnico** [comment]
They will be all set in a non empty block. So we could remove the `= { 1 }` part.

**Comment by boelle** [comment]
will upgrade this to an verified one

**Comment by thinkyhead** [comment]
#1655 fixes this by initializing the whole array.
