### ISSUE TITLE
[FR] Adding Anet E10 Configuration files

### ISSUE THREAD

**Issue by Bazzofski** [MarlinFirmware/Marlin#16263]
### Description

Suggestion : adding configuration files for Anet E10 printers

**Comment by Vertabreak** [comment]
Does it need ported over from old version? Post original configuration and I'll port it over if that's the case.

**Comment by Bazzofski** [comment]
No, but i've made my own config files for Marlin 1.1.x .

**Comment by Vertabreak** [comment]
post old config files and ill port them over and submit them.

**Comment by Bazzofski** [comment]
Where should I post it ? Sorry, i'm pretty new on github.

**Comment by thisiskeithb** [comment]
> Where should I post it ? Sorry, i'm pretty new on github.

Zip up both your `Configuration.h` & `Configuration_adv.h` files and attach them in a reply.

> post old config files and ill port them over and submit them.

Love seeing more printers supported in vanilla Marlin 🙂

**Comment by Vertabreak** [comment]
Just zip them and drop them here in your next message. Porting over older configs has become kinda a thing I do lol. I don't charge for the work I do or anything but there is a link for tips when people want to.

**Comment by Bazzofski** [comment]
I didn't thought about zipping them, thanks ^^
[Marlin Anet E10 config.zip](https://github.com/MarlinFirmware/Marlin/files/3985004/Marlin.Anet.E10.config.zip)

**Comment by Vertabreak** [comment]
I'll run a diff on them shortly check back in a hour or two. Once I have a copy on my fork you can test them.

**Comment by Vertabreak** [comment]
k gonna need the full source copy as the config doesn't tell me everything. gonna check the source copy here on git-hub maybe it has what im looking for. copy here has what i was looking for so never mind.

**Comment by Vertabreak** [comment]
running the last few checks on the updated config should have something ready to test shortly.

**Comment by Vertabreak** [comment]
feedback on any alterations that maybe needed will be collected before dropping the PR.

**Comment by Bazzofski** [comment]
I can't flash it on my printer right now, I'll try tomorrow and tell you if everything is ok for the pr.

**Comment by Vertabreak** [comment]
Not anticipating any major issues just looking for confirmation. as all the hardware was existing supported stuff. I just set it up based on your original configurations.

**Comment by Bazzofski** [comment]
I don't see any alterations to add, you can create the pr. Thanks for your work !

**Comment by Vertabreak** [comment]
would like hardware confirmation that it runs on the printer some photos would be good ^^.
if you wanted to tip me for my work you can do so with this link https://www.paypal.me/vertabreaker if not that's ok to.

**Comment by Bazzofski** [comment]
I've tried to flash the firmware but it keeps showing error on compiling about undefined values, I've checked and they're defined in the advenced config file.

Logs : 

`sketch\src\feature\pause.cpp: In function 'bool unload_filament(const float&, bool, PauseMode)':

sketch\src\feature\pause.cpp:348:21: error: 'FILAMENT_UNLOAD_RETRACT_LENGTH' was not declared in this scope

   do_pause_e_move(-(FILAMENT_UNLOAD_RETRACT_LENGTH) * mix_multiplier, (PAUSE_PARK_RETRACT_FEEDRATE) * mix_multiplier);

                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sketch\src\feature\pause.cpp:348:21: note: suggested alternative: 'FILAMENT_UNLOAD_PURGE_LENGTH'

   do_pause_e_move(-(FILAMENT_UNLOAD_RETRACT_LENGTH) * mix_multiplier, (PAUSE_PARK_RETRACT_FEEDRATE) * mix_multiplier);

                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

                     FILAMENT_UNLOAD_PURGE_LENGTH

sketch\src\feature\pause.cpp:351:14: error: 'FILAMENT_UNLOAD_DELAY' was not declared in this scope

   safe_delay(FILAMENT_UNLOAD_DELAY);

              ^~~~~~~~~~~~~~~~~~~~~

sketch\src\feature\pause.cpp:351:14: note: suggested alternative: 'FILAMENT_UNLOAD_PURGE_DELAY'

   safe_delay(FILAMENT_UNLOAD_DELAY);

              ^~~~~~~~~~~~~~~~~~~~~

              FILAMENT_UNLOAD_PURGE_DELAY

**Comment by Vertabreak** [comment]
unsure what you attempted to compile or with what but i posted a fully compiled copy.
here is a prep copy plus a fully compiled copy that will only compile with vscode due to the tiny size of the board and how poorly Arduino optimizes code.

[Marlin-PR.zip](https://github.com/MarlinFirmware/Marlin/files/3988338/Marlin-PR.zip)

[firmware.hex.zip](https://github.com/MarlinFirmware/Marlin/files/3988435/firmware.hex.zip)

PR prep branch: https://github.com/Vertabreak/Marlin/tree/PR

**Comment by Vertabreak** [comment]
gotten a chance to test yet?

**Comment by Bazzofski** [comment]
Sorry for the delay. I tried to compile the hex file but didn't find how to do it, so i tried compiling your pr and I got those errors : 

https://pastebin.com/NrRHYxNK

Then I've tried the official 2.0.x release with the new config files and I get errors too : 

https://pastebin.com/BGvSFy5U

It doesn't seems to come from the config files.

**Comment by Vertabreak** [comment]
compiled normal for me unsure what might be the issue on your end are you sure you selected the right platform to compile for?

**Comment by Bazzofski** [comment]
I compiled it with vscode using platformio

**Comment by Vertabreak** [comment]
but did you set the correct environment for that board.

**Comment by Vertabreak** [comment]
![image](https://user-images.githubusercontent.com/45634861/71415742-3c93f480-262b-11ea-80b2-130c6f411a30.png)

**Comment by Vertabreak** [comment]
the default is mega2560 that is not the board you have if i recall its a sanguino_atmega1284p

**Comment by Bazzofski** [comment]
Yes, I imported the project with ATmega1284P selected and I've changed it too in the .ini file.

**Comment by Vertabreak** [comment]
![image](https://user-images.githubusercontent.com/45634861/71415861-e2dffa00-262b-11ea-8b30-0cf20635d03f.png)

ATmega1284P isn't a valid environment could be the issue.

**Comment by Vertabreak** [comment]
![image](https://user-images.githubusercontent.com/45634861/71416120-26873380-262d-11ea-88cc-425c3aae5b2d.png)

**Comment by Bazzofski** [comment]
I didn't change the environment, it set it automatically when I chose the board while importing the arduino project.

**Comment by Bazzofski** [comment]
![image](https://user-images.githubusercontent.com/58656201/71416211-ccec2c80-265f-11ea-9a10-f53bd4cc09c6.png)

**Comment by Vertabreak** [comment]
the preped copy i posted literally is all setup you just open the folder and click build.

**Comment by Vertabreak** [comment]
![image](https://user-images.githubusercontent.com/45634861/71416276-c3e26780-262d-11ea-9ef3-1e222923f1a8.png)

**Comment by Bazzofski** [comment]
Sorry, my bad ^^ I was using an other pr. I tried and this time it successfully compiled. But now avrdude won't flash the board with the "not in sync" error.
![image](https://user-images.githubusercontent.com/58656201/71416932-ff4b5900-2662-11ea-8ee1-7d99da006e7b.png)

**Comment by Vertabreak** [comment]
is the right com port selected and are the drivers installed. also are you sure there is a bootloader on the device to even be able to flash it like this.
![image](https://user-images.githubusercontent.com/45634861/71417113-a0212080-2631-11ea-8975-3850a2552f52.png)

**Comment by Bazzofski** [comment]
Yes, it is detected and It has a bootloader because i've already flashed old marlin versions on it.

**Comment by Vertabreak** [comment]
its the correct com port? its not trying to flash like another com device on the system.

**Comment by thisiskeithb** [comment]
> the default is mega2560 that is not the board you have if i recall its a sanguino_atmega1284p

So we're not troubleshooting a stock Anet E10 config?

**Comment by Vertabreak** [comment]
marlin default is mega2560 not talking about the printer.

**Comment by Vertabreak** [comment]
config is a direct port of the original.

**Comment by Bazzofski** [comment]
It's clearly the good com port, I can access the printer with pronterface with the same port.

**Comment by Vertabreak** [comment]
not really troubleshooting more like explaining how to use the tools required to flash the printer.

**Comment by Vertabreak** [comment]
maybe the baud rate is set incorrectly?

**Comment by Vertabreak** [comment]
unsure why just flashing the pre compiled hex file was the 2ed choice.

**Comment by Bazzofski** [comment]
I've changed the baudrate, I'll tell you when it's finished.

**Comment by Vertabreak** [comment]
kk finally flashing can get to the real testing.

**Comment by Bazzofski** [comment]
It gave me the same error, I'm gonna try flashing it directly with avrdude without vscode.

**Comment by Vertabreak** [comment]
i normally use octoprint to flash pre compiled hex files from vscode personally.

**Comment by Bazzofski** [comment]
Yes, but I don't have any octoprint set-up

**Comment by Vertabreak** [comment]
cura can flash hex files also.

**Comment by Vertabreak** [comment]
you didn't happen to have cura open when trying to flash did you or anything else connected to the printer as that could block the connection or even interrupt it mid flash.

**Comment by Bazzofski** [comment]
The port was free when I tried. I've tried to flash it with cura but it reset the printer when starting and disconnect it.

**Comment by Vertabreak** [comment]
cura auto connects and reboots marlin its just how cura works its kinda dangerous cus if you open cura mid flash you just bricked it. i have considered going over to the cura GitHub and dropping a PR to stop the auto connect seen it brick way to many boards. just ordered my 7th printer invested in a in circuit programmer a while back after having the cura thing happen a few times just not thinking so i could burn fresh boot loaders and revive them.

**Comment by Bazzofski** [comment]
That's a bit crappy from cura, did they release your pr ?

**Comment by Vertabreak** [comment]
if you really insist on using arduino disable any non vital features and manage to get arduino to compile it vscode just does a better job optimizing code so you can fit more. it was only a idea about submitting a pull request to stop the auto connect in cura but that's how these projects happen.

**Comment by Vertabreak** [comment]
id hate to make the suggestion but your on windows right have you tried rebooting lol.

**Comment by Bazzofski** [comment]
Yep, I'm on windows, I'v already had the reflex to reboot it xD but it didn't change anything. I think it's more of a board config problem, I'm gonna try something with arduino ide

**Comment by Vertabreak** [comment]
its all kinda weird cus Ive flashed the entire wrong boards hex file to the wrong printer several times it just doesn't boot up and i have to re-flash the right one.

**Comment by Bazzofski** [comment]
Yes, it's really weird, only the prepd vscode project you've sent is compiling. An only the arduino ide can flash the board but it can't compile the project.

**Comment by Vertabreak** [comment]
try the melzi environment in platformio 
default_envs = melzi
or
 default_envs =melzi_optiboot
apparently they are also ATmega1284P O.o

**Comment by Bazzofski** [comment]
Trying that and updating you when it's finished ^^

**Comment by Vertabreak** [comment]
i was digging around in the code and it says both them are also ATmega1284P.

**Comment by Bazzofski** [comment]
But technically if they're the same they should give the same result, no ?

**Comment by Vertabreak** [comment]
they seem to be variants so i'm thinking maybe.

**Comment by Bazzofski** [comment]
It seems to be working !

**Comment by Bazzofski** [comment]
It worked ! Thank you so much !

**Comment by Vertabreak** [comment]
guess it was the wrong variant its kinda odd you see one listed the chip name you figure its that not something else named something else. a new quirk to add to my list i guess lol.

**Comment by Bazzofski** [comment]
Yeah, it's always weird with those chinese printer. I even had to repair the board a few times and to finally replace it.

**Comment by Vertabreak** [comment]
now that marlin 2 is on there take it for a spin let me know if adjustments need to be made.
i don't think there will be anything major as it was a direct port and it was a semi newer version 1.1.8 so the settings where easy to copy over unlike with way older marlin versions.

**Comment by Vertabreak** [comment]
is the screen garbled at all do i need to add more delay?

**Comment by Bazzofski** [comment]
No, the screen is good, I had the problem on older versions but not on this one. I'm gonna test everything and tell you if it's good

**Comment by Vertabreak** [comment]
yea expecting the issue i built in some delay its a very common issue with them screens.

**Comment by Vertabreak** [comment]
you could shoe horn in a few more features if you really needed to.

**Comment by Vertabreak** [comment]
someone remind me to do testing and diagnostics on discord in private messages only from now on what a mess we made on the GitHub.

**Comment by Bazzofski** [comment]
I hope nobody will need to find something here xD

**Comment by Bazzofski** [comment]
The test print turn out to be pretty good
![IMG_20191224_190750](https://user-images.githubusercontent.com/58656201/71422281-e0f45600-2680-11ea-9af3-6a4a51863bf7.jpg)

2cents piece for comparison

**Comment by Vertabreak** [comment]
looks like its all good to go then and needs no major edits. i would imagine fine tuning to get it just right but that isn't the point of example configs to be perfect. it prints direct port no additional edits needed gonna call this complete.

**Comment by Vertabreak** [comment]
@boelle i think you can close this one.
