### ISSUE TITLE
[BUG] pinDebug_list.h missing X2_CS and Y2_CS

### ISSUE THREAD

**Issue by Windaub57** [MarlinFirmware/Marlin#16288]
pinDebug_list.h 
X2_CS and Y2_CS are missing.

**Comment by boelle** [comment]
maybe submit a PR to fix this?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
