### ISSUE TITLE
[BUG] Extruder keeps extruding always on G26 in Marlin 2

### ISSUE THREAD

**Issue by safaenet** [MarlinFirmware/Marlin#16287]
### Bug Description
Hi, I did the bed leveling via Unified Bed Leveling  on my prusa clone (Marlin 2). After that when using G26 P10 to do a test print it doesn't behave as expected. Filament drops out of nozzle even when z is high axis are moving to another point. actually the extruder doesn't stop extruding never.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
closing until configs are provided
