### ISSUE TITLE
[BUG] DAC steppers and 32 bits MCU

### ISSUE THREAD

**Issue by 0r31** [MarlinFirmware/Marlin#16285]
Hi all,

### Bug Description

There are issues when using both DAC steppers feature and any 32 bits MCU.

### My Configurations

You can find an example configuration in the attached archive file : [dac+32bits.zip](https://github.com/MarlinFirmware/Marlin/files/3991337/dac%2B32bits.zip).

### Steps to Reproduce

I just changed the board to _BOARD_SMOOTHIEBOARD_ and add stuff to enable DAC features in the smoothisboard pins file. Then i tried to compile: It fails as three avr arduino core macros are not defined for lpc1769: **word**, **highByte**, **lowByte**.

I naively tried to define them in _dac_mcp4728.cpp_ as I2C communication is based on 8 bits blocks:
```c
#ifdef MCU_LPC1769
  unsigned int makeWord(unsigned char h, unsigned char l) { return (h << 8) | l; }

  #define word(...) makeWord(__VA_ARGS__)
  #define lowByte(w) ((uint8_t) ((w) & 0xff))
  #define highByte(w) ((uint8_t) ((w) >> 8))
#endif
```

Then the compilation succeeds but it doesn't work as expected as there absolutely no voltage on the DAC (MCP4728) outputs.

**Expected behavior:** DAC steppers feature must work on any 32 bits MCUs.

**Actual behavior:** Compilation failure or no voltage on DAC outputs.

#### Additional Information

I am aware there is a built-in DAC on the lpc1769 but i don't use if for now (use of a separate MCP4728).

Feel free to ask for more information. I would be glad to answer.

**Comment by boelle** [comment]
@dagorel is this still a problem?

**Comment by 0r31** [comment]
Hi @boelle ,

Yes it is. I don't find any fix for now.

**Comment by 0r31** [comment]
Hi again @boelle ,

It seems there is an issue in the arduino fmk for lpc176x regarding the missing macros (discussed with @p3p ). I will send a PR to the appropriate github repo.

Fixing this part doesn' fix the whole stuff. As said in the first message there is no voltage on mcp chip outputs... still investigating.

**Comment by 0r31** [comment]
Hi @boelle,

Looks like the main issue is on choosing the I2C master address at the platform level.
I already managed it but there are still some issues.
I don't think it can be specifically related to the Marlin repo even if there might be some changes to be done in a near future.

That's why i close the issue for now.

Regards,
Orel
