### ISSUE TITLE
[FR] Can you add exemple files for JGaurora Magic Maker 3d Printer

### ISSUE THREAD

**Issue by sfm67** [MarlinFirmware/Marlin#16289]
### Description

Can you add exemple files for JGaurora Magic Maker since jgaurora has publish source code.

thanks

**Comment by DerAndere1** [comment]
My 7zip cannot extract JGaurora's firmware archive folder for the JGaurora Magic from http://www.jgaurora3d.com/list_21.aspx?page=1. 
@sfm67: If you can drag-and-drop a functional zip archive containing JGaurora's configuration.h and configuration_adv.h file in a comment here, I could prepare a pull request.

**Comment by Vertabreak** [comment]
just ported it and added to PR.

**Comment by DerAndere1** [comment]
@sfm67 You can download latest bugfix-2.0.x. It should contain the example config. If it works for you, please close this issue.

**Comment by Vertabreak** [comment]
If you have any issues let me know I'll assist n publish any changes as needed it was a direct port should be fine.

**Comment by sfm67** [comment]
hi, i have D/L Marlin 2.01, and only see example files for Jgaurora A1, A5 and A5S.

thanks

**Comment by sfm67** [comment]
thanks 💃
