### ISSUE TITLE
[FR] Home XY (if needed) before nozzle park

### ISSUE THREAD

**Issue by wikolii** [MarlinFirmware/Marlin#16307]
[Cfg files.zip](https://github.com/MarlinFirmware/Marlin/files/3998283/Cfg.files.zip)

### Description

I don't consider this a bug, but there's definitely an issue with the filament change command "M600" combined with NOZZLE_PARK_FEATURE and ADVANCED_PAUSE_FEATURE when the motor drivers have been disabled and the axis moved manually (Position unknown). This will cause sometimes X and Y to hit their limits and bump creating noises and possibly breaking something.
I think it would be wise to add a feature to either home X and Y before parking the nozzle always or home X and Y only in case the XY position is unknown (motors disabled).

### Steps to reproduce

1. X and Y positions have to be greater than the NOZZLE_PARK_POINT
2. Issue an M84 command: Stop idle hold / Motors Off. Or even let it timeout according to FW settings. (This is most commonly the case after a print job is finished or cancelled, the motors are disabled and one moves the axis by hand)
3. Issue an M600 command: Filament change pause
4. The printer will try to go further than the axis limits bumping into endstops switches, etc.

### Feature Workflow

1. Add a checkpoint: if the position is unknown before parking, either home XY or don't move the axis at all, just raise Z. One can move the XY axis by hand if necessary
2. Enjoy the music of the axis not hitting their ends.

**Comment by thisiskeithb** [comment]
You didn't include a zip with your config files, but you need to enable `HOME_BEFORE_FILAMENT_CHANGE` in `Configuration_adv.h`.

**Comment by thinkyhead** [comment]
While in principle it makes sense, it seems prudent that is should be optional, simply because endstops are not always the most positionally-accurate things, and at the same time leaving steppers powered on tends to heat them up more than keeping them moving, so both not-homing and not-staying-powered are often a preferred combination.

**Comment by wikolii** [comment]
Thanks for the responses. I added the required files

> You didn't include a zip with your config files, but you need to enable `HOME_BEFORE_FILAMENT_CHANGE` in `Configuration_adv.h`.

It's weird how i missed this feature, thanks. I also added the files
Still, the unreliability of the common endstop makes me think homing should only be triggered if the position is unknown, or ar least, let the user choose in the FW. I have seen layer-shiftlike errors caused by mid-print-homing.

> While in principle it makes sense, it seems prudent that is should be optional, simply because endstops are not always the most positionally-accurate things, and at the same time leaving steppers powered on tends to heat them up more than keeping them moving, so both not-homing and not-staying-powered are often a preferred combination.

I personally like the last option, not-homing and not-staying-powered, but this would't work during a print job. So not homing XY if position is unknown still looks like the best option here, imho.

**Comment by thisiskeithb** [comment]
@wikolii: After some more testing, I created issue #17663 and then PR #17681 to prevent the hotend/bed from crashing into the frame if `HOME_BEFORE_FILAMENT_CHANGE` is enabled.
