### ISSUE TITLE
[BUG] Not working RESTORE_LEVELING_AFTER_G28

### ISSUE THREAD

**Issue by bigtreeteche3** [MarlinFirmware/Marlin#16306]
After activating:  RESTORE_LEVELING_AFTER_G28
It does not restore the previous leveling stored in the eeprom. You have first to go into the menu and reset bed level manualy to on because it will set itself always back to off. After that it will restore the previous leveling after G28.

**Comment by Vertabreak** [comment]
when using other bed leveling that isn't UBL you need to load the mesh before starting the print.

**Comment by bigtreeteche3** [comment]
just by adding m420 s to the gcode?

**Comment by thinkyhead** [comment]
The `RESTORE_LEVELING_AFTER_G28` option causes `G28` to enable leveling if it was on before `G28`. It doesn't enable leveling if it was off before `G28`.

**Comment by thinkyhead** [comment]
> just by adding `M420 S` to the gcode?

That will enable leveling using the mesh currently stored in RAM.
