### ISSUE TITLE
[BUG] SKR Mini 1.2 Min Temp is not working when unplugging the thermistor

### ISSUE THREAD

**Issue by Seref** [MarlinFirmware/Marlin#16302]
When heating up the bed and the hotend to 60°C and 250°C and unplugging the thermistor it doesn't throw any errors, nor does it stop the hotend or heated bed, additionally the board crashes while powering the heated bed, which means that the heated bed continues to heat up.

What is also weird is that after a while the serial USB connection to Pronterface is interrupted and Windows starts to complain of a not working USB device.

I'm using Pronterface to control the printer.

I flashed 2.0.x and the behavior is the same on there too.

Here are my configurations:

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3993710/Configuration.zip)

**Comment by Seref** [comment]
Okay I tried to compare some versions (either bugfix or 2.0.x) but it really seems like the MIN_Temp check is broken or rather what happens afterwards.

**Comment by Seref** [comment]
I found a partial solution, disabling PID control for the heated bed allows the board to shut down power to the heated bed when it crashes, still no error is thrown and nothing else happens it just crashes after a while, not even kill() or anything comparable is called.

It's a bit weird using the printer without this feature fully working😅.

What I tried so far:
- tried multiple older versions up until the board was first included
- switched between different configs (no USB, USB, 512k with more features enables etc.)
- I also tried looking at the code myself and put a some prints into the temperature class to see where it stops when I unplug the thermistor, though it seems like it stops before (PID Enabled) the check in line 1142

> temp_bed.soft_pwm_amount = WITHIN(temp_bed.celsius, BED_MINTEMP, BED_MAXTEMP) ? (int)get_pid_output_bed() >> 1 : 0;

since no error gets printed out, (though it could be also due to a premature closure on the serial connection. I don't have a screen right now and don't know if anything should be displayed there, but since the printer crashes weirdly I don't think there would be anything on it either).
Additionaly

> thermal_runaway_protection(...);

doesn't trigger it either, otherwise kill() would be called.

So my guess is that it happens when the temperature is read in the ISR. Though I'm not sure were to look there and how to really debug that.

**Comment by Seref** [comment]
Okay after some more hours of testing I think I'm able to pinpoint it a bit more, it seems like the serial connection gets worse when using composite USB aka **STM32F103RC_bigtree_USB** or **STM32F103RC_bigtree_512K_USB**.

So for everyone who also got this problem with this board:
Just use the non USB version (**STM32F103RC_bigtree** & **STM32F103RC_bigtree_512K**), additionally now when using PID_TEMP for the heated bed it also shuts down correctly.

There still seems to be a bug with the serial connection because the error is only partially printed:

> **E**
![image](https://user-images.githubusercontent.com/9627396/71627635-e4915b00-2bf3-11ea-940f-43dac53ae042.png)

I think this is from the error message because it is the only thing that gets printed right after I unpluged the thermistor, the good thing now is that if the heated bed or the hotend gets MIN_TEMP triggered it won't be stuck in the current powering state it really shuts down.

This isn't a really fix as it is a workaround for the problem, and the problem itself is has more to do with the USB connection, atleast that is my current assumption.

**Comment by boelle** [comment]
@Seref still an issue?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by Seref** [comment]
I didn't really solve it, and as mentioned before I just turned off the composite USB feature, which kind of fixed it.
