### ISSUE TITLE
[BUG] LPC176x TMC SOFTWARE SPI too fast 

### ISSUE THREAD

**Issue by Windaub57** [MarlinFirmware/Marlin#16311]
### Bug Description

TMC sorftware SPI is running too fast and 40bits setup messages not fully sent to drivers, resulting in random and anarchic driver configuration.
Also drivers reporting is fully corrupted.

### My Configurations

Stock configuration, LPC176x boards, TMC2130 SPI drivers

### Steps to Reproduce

1. Setup any LPC176x boards with TMC SOFT SPI DRIVERS

**Expected behavior:** proper communication with driver, setup and feedback

**Actual behavior:** complete random communication, drivers not properly setup, feedback corrupted

#### Additional Information

used a logic analyser to check messages sent. Modified writeSCK_H and writeSCK_L timing in TMC_platforms.h to make it slower and got proper communication back. See attached photos before after.

<img width="1363" alt="before" src="https://user-images.githubusercontent.com/10937286/71385272-b655bf00-25e6-11ea-9a15-a76b3f815db5.png">
<img width="1335" alt="after" src="https://user-images.githubusercontent.com/10937286/71385275-b8b81900-25e6-11ea-964f-44633d7f656b.png">

**Comment by thinkyhead** [comment]
That file belongs to the `TMCStepper` repository, which is a [different project](https://github.com/teemuatlut/TMCStepper) under a different organization. Are you asking the maintainers of this project to head over there and fix `TMCStepper`? Or is there something that we can do here in our codebase to make `TMCStepper` behave as you are suggesting?

**Comment by sjasonsmith** [comment]
This sounds like something @p3p fixed recently. Make sure you are using the latest version of TMCStepper.

**Comment by Windaub57** [comment]
I do not have a full overview of Marlin to say if that could be a TMCStepper or Marlin issue. But if you think that 's only a TMCStepper, you can close it here and keep it for info.

For info, I used TMCStepper 0.6.1, latest Marlin (from yesterday) as well as latest LPC176x lib.

**Comment by sjasonsmith** [comment]
> For info, I used TMCStepper 0.6.1, latest Marlin (from yesterday) as well as latest LPC176x lib.

The fixes I referred to are in 0.6.1, so it sounds like they must need adjusted a bit more.

It seems you've already figured out what needs to change. I'd suggest you close it here and post a pull request to the TMCStepper project, along with your traces that back up the need for the change.

**Comment by Windaub57** [comment]
I'll do that!
