### ISSUE TITLE
[BUG] Screen doesn't turn on on skr 1.3 with cr10-S screen

### ISSUE THREAD

**Issue by Liger0** [MarlinFirmware/Marlin#16314]
### Bug Description

The screen doesn't turn on on a skr 1.3 with the double ribbon cable cr10-S screen

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3996943/Marlin.zip)

### Steps to Reproduce

1. Flash the firmware
2. Start the printer

**Expected behavior:** 
LCD should work

**Actual behavior:** 
LCD doesn't work

#### Additional Information

As what I heard the pins are reversed on the skr 1.3 exp1 and exp2, but I guess Marlin could account for it?

**Comment by ellensp** [comment]
The pins are flipped 180 degrees for some displays...  and no you can't correct for it in firmware as the power pins can't be changed.  You need a custom cable or to remove the keys on the cable so you can plug them in rotated 180, or cut new key slots. Or remove the plastic with the key slots from the back of the display.

**Comment by Liger0** [comment]
Could there be a comment in the FW at least at the LCD line? Since I just barely read about it by pure luck and it isn't written anywhere. I really struggled to find anything without any luck.

**Comment by Liger0** [comment]
I did cut the pin on one side of each wire and now it turns on. 
The issue is that, before the marlin logo, this happens:
![marlin broken](https://user-images.githubusercontent.com/20385116/71390477-d7c3a480-2600-11ea-970c-fa70ddcab188.jpg)

**Comment by ellensp** [comment]
Yes that is a known issue, give it  30 seconds and marlin will finish booting.

**Comment by ellensp** [comment]
see issue #15855

**Comment by boelle** [comment]
@ellensp so both this isse and #15855 could be closed?

**Comment by Liger0** [comment]
Could you add a disclaimer about inverting the pins please? People aren't omniscient and it's hidden and unclear in the skr pdf on github.

**Comment by ellensp** [comment]
@boelle This issue definitely. His screen is working, and it wasn't a firmware issue. As for 15855 After replacing he bootloader the issue is still gone for me...
