### ISSUE TITLE
[BUG] add support for thermistor type 99 in Marlin\src\lcd\thermistornames.h

### ISSUE THREAD

**Issue by nforceroh** [MarlinFirmware/Marlin#16334]
### Description

add support for thermistor type 99 in Marlin\src\lcd\thermistornames.h
something like 
#elif THERMISTOR_ID == 99
  #define THERMISTOR_NAME "User defined"

You can't compile unless this is defined if you use 99 as a custom table

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ellensp** [comment]
this is a bug. Missing  THERMISTOR_NAME for THERMISTOR_ID == 99 
99 is already used. Needs a better name than User defined "100k bed thermistor with a 10K pull-up resistor" according to https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/module/thermistor/thermistor_99.h#L25

**Comment by boelle** [comment]
@ellensp is this still an bug? or has it been fixed?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
