### ISSUE TITLE
[BUG] Temperatur always BANG_BANG?

### ISSUE THREAD

**Issue by TAOGde** [MarlinFirmware/Marlin#16347]
### Bug Description

I update to the latest 2.0.1 version. after preheat my noozle I saw that the PID settings not working. it looks always like BANG_BANG. No Autotune for PID has helped so far.
The setting for PID enabled is on at default in marlin.

### My Configurations

[Archiv.zip](https://github.com/MarlinFirmware/Marlin/files/4003611/Archiv.zip)

### Steps to Reproduce

Start compiling with latest Arduino.
turned PID on and off with the same result

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

<img width="606" alt="Bildschirmfoto 2019-12-27 um 00 09 49" src="https://user-images.githubusercontent.com/43980652/71493272-b56a9a80-283d-11ea-9072-8d0d0d444ded.png">

**Comment by thisiskeithb** [comment]
Did you transfer your old PID settings when you upgraded? You may also still need to run a [PID Autotune](http://marlinfw.org/docs/gcode/M303.html).

**Comment by ManuelMcLure** [comment]
There was a time when the way PID values were stored in EEPROM changed which resulted in bad PID behavior after updating Marlin. Check to make sure that Marlin really thinks the PIDs are what you specified. You might need to do a M502 to reset the EEPROM.

**Comment by TAOGde** [comment]
> Did you transfer your old PID settings when you upgraded? You may also still need to run a [PID Autotune](http://marlinfw.org/docs/gcode/M303.html).

> There was a time when the way PID values were stored in EEPROM changed which resulted in bad PID behavior after updating Marlin. Check to make sure that Marlin really thinks the PIDs are what you specified. You might need to do a M502 to reset the EEPROM.

i do a fresh install and start PID Autotune with storing the settings in the firmware for hardcode settings and store it in the eeprom.

booth are the same result.

**Comment by tatusah** [comment]
Are you absolutely sure you compiled the firmware with the PID temp enabled because the configurations you have linked show the PIDTEMP disabled?

**Comment by TAOGde** [comment]
> Are you absolutely sure you compiled the firmware with the PID temp enabled because the configurations you have linked show the PIDTEMP disabled?

Oh this is my test then. I tried with PID on and off in the config. With on I make the pidtune and always the temperature is +-5 Celsius to the set Temperatur. 

With the old firmware all was fine. Pidtune and the Temperatur was Max. +-0,5  Celsius

**Comment by tatusah** [comment]
Ok, so then it's not using BANG_BANG always if you have it set correctly. What was the old firmware version you used before and did you use the old configuration files? The configuration files you uploaded show PID_K1 value of 0.90 whereas current Marlin default example configs have value of 0.95. There was also other things missing from the configuration files that seem to indicate the config files might not be based on the actual 2.0.1 release. The comments for PID_K1 tell that it's a smoothing factor so I would try with the example value of 0.95 to see if this would fix the rather high oscillation of the temperature.

**Comment by TAOGde** [comment]
So, I try a new config from the default drawer.
Setting my PINs and Stepper. Flashed the printer, reset the eeprom, start the PIDAUTOTUNE.
After that I saved the settings in eeprom, load the eeprom and start the tooltemperature to 230°C
as you can see in the curve the autotune works but the temperature after the tune does a BANG-BANG.

i uploaded the new configuration also.

<img width="620" alt="Bildschirmfoto 2019-12-28 um 11 59 23" src="https://user-images.githubusercontent.com/43980652/71542673-82252a00-2969-11ea-970b-c6c0655c50aa.png">
[Archiv.zip](https://github.com/MarlinFirmware/Marlin/files/4006964/Archiv.zip)

Update:
i start a print. as you can see the autostartprinter function could not run. the time goes to 7 and then back to 9. the temperature runs crazy.
`
Recv: echo:busy: processing
Recv:  T:235.94 /240.00 B:60.03 /60.00 @:127 B@:21
Recv:  T:238.06 /240.00 B:60.02 /60.00 @:127 B@:22 W:9
Recv:  T:239.50 /240.00 B:60.01 /60.00 @:116 B@:23 W:8
Recv: echo:busy: processing
Recv:  T:239.94 /240.00 B:59.91 /60.00 @:108 B@:27
Recv:  T:241.80 /240.00 B:60.01 /60.00 @:61 B@:22 W:7
Recv:  T:240.31 /240.00 B:60.01 /60.00 @:103 B@:22 W:9
Recv: echo:busy: processing
Recv:  T:244.53 /240.00 B:60.02 /60.00 @:0 B@:22
Recv:  T:244.30 /240.00 B:60.01 /60.00 @:0 B@:23 W:9
Recv:  T:247.03 /240.00 B:60.00 /60.00 @:0 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:246.95 /240.00 B:59.99 /60.00 @:0 B@:24
Recv:  T:247.34 /240.00 B:60.03 /60.00 @:0 B@:22 W:9
Recv:  T:249.06 /240.00 B:59.95 /60.00 @:0 B@:26 W:9
Recv: echo:busy: processing
Recv:  T:249.45 /240.00 B:59.97 /60.00 @:0 B@:25
Recv:  T:246.17 /240.00 B:59.99 /60.00 @:0 B@:24 W:9
Recv:  T:248.83 /240.00 B:59.97 /60.00 @:0 B@:25 W:9
Recv: echo:busy: processing
Recv:  T:249.84 /240.00 B:59.92 /60.00 @:0 B@:27
Recv:  T:249.38 /240.00 B:59.99 /60.00 @:0 B@:24 W:9
Recv:  T:250.08 /240.00 B:60.07 /60.00 @:0 B@:20 W:9
Recv: echo:busy: processing
Recv:  T:248.91 /240.00 B:60.07 /60.00 @:0 B@:20
Recv:  T:248.98 /240.00 B:59.96 /60.00 @:0 B@:25 W:9
Recv:  T:249.30 /240.00 B:60.01 /60.00 @:0 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:248.36 /240.00 B:60.02 /60.00 @:0 B@:22
Recv:  T:247.34 /240.00 B:60.03 /60.00 @:0 B@:22 W:9
Recv:  T:246.56 /240.00 B:60.06 /60.00 @:0 B@:21 W:9
Recv: echo:busy: processing
Recv:  T:248.67 /240.00 B:60.05 /60.00 @:0 B@:21
Recv:  T:246.17 /240.00 B:60.05 /60.00 @:0 B@:21 W:9
Recv:  T:247.58 /240.00 B:59.96 /60.00 @:0 B@:25 W:9
Recv: echo:busy: processing
Recv:  T:245.23 /240.00 B:59.95 /60.00 @:0 B@:26
Recv:  T:247.11 /240.00 B:59.95 /60.00 @:0 B@:26 W:9
Recv:  T:242.19 /240.00 B:59.97 /60.00 @:0 B@:25 W:9
Recv: echo:busy: processing
Recv:  T:242.03 /240.00 B:60.01 /60.00 @:0 B@:23
Recv:  T:241.80 /240.00 B:60.05 /60.00 @:0 B@:21 W:9
Recv:  T:240.23 /240.00 B:60.01 /60.00 @:24 B@:23 W:8
Recv: echo:busy: processing
Recv:  T:239.50 /240.00 B:60.07 /60.00 @:39 B@:20
Recv:  T:239.94 /240.00 B:60.02 /60.00 @:24 B@:22 W:7
Recv:  T:238.38 /240.00 B:60.06 /60.00 @:61 B@:21 W:6
Recv: echo:busy: processing
Recv:  T:237.69 /240.00 B:60.02 /60.00 @:78 B@:22
Recv:  T:235.69 /240.00 B:60.00 /60.00 @:127 B@:24 W:9
Recv:  T:235.56 /240.00 B:60.05 /60.00 @:127 B@:21 W:9
Recv: echo:busy: processing
Recv:  T:235.19 /240.00 B:59.97 /60.00 @:127 B@:25
Recv:  T:233.31 /240.00 B:60.05 /60.00 @:127 B@:21 W:9
Recv:  T:234.38 /240.00 B:60.00 /60.00 @:127 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:236.06 /240.00 B:59.96 /60.00 @:127 B@:25
Recv:  T:234.13 /240.00 B:59.95 /60.00 @:127 B@:25 W:9
Recv:  T:233.75 /240.00 B:60.00 /60.00 @:127 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:233.75 /240.00 B:60.02 /60.00 @:127 B@:22
Recv:  T:234.50 /240.00 B:60.05 /60.00 @:127 B@:21 W:9
Recv:  T:233.69 /240.00 B:59.97 /60.00 @:127 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:234.19 /240.00 B:59.97 /60.00 @:127 B@:24
Recv:  T:235.50 /240.00 B:59.97 /60.00 @:127 B@:24 W:9
Recv:  T:236.69 /240.00 B:59.92 /60.00 @:127 B@:27 W:9
Recv: echo:busy: processing
Recv:  T:235.25 /240.00 B:60.05 /60.00 @:127 B@:21
Recv:  T:236.19 /240.00 B:60.00 /60.00 @:127 B@:23 W:9
Recv:  T:241.33 /240.00 B:59.99 /60.00 @:62 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:238.75 /240.00 B:60.03 /60.00 @:127 B@:21
Recv:  T:239.13 /240.00 B:60.02 /60.00 @:126 B@:22 W:8
Recv:  T:240.47 /240.00 B:59.99 /60.00 @:97 B@:23 W:7
Recv: echo:busy: processing
Recv:  T:241.41 /240.00 B:60.00 /60.00 @:73 B@:23
Recv:  T:240.55 /240.00 B:59.97 /60.00 @:97 B@:24 W:6
Recv:  T:244.06 /240.00 B:59.95 /60.00 @:2 B@:25 W:9
Recv: echo:busy: processing
Recv:  T:245.16 /240.00 B:60.02 /60.00 @:0 B@:22
Recv:  T:245.63 /240.00 B:60.03 /60.00 @:0 B@:21 W:9
Recv:  T:249.22 /240.00 B:59.99 /60.00 @:0 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:247.89 /240.00 B:59.99 /60.00 @:0 B@:23
Recv:  T:247.42 /240.00 B:60.01 /60.00 @:0 B@:22 W:9
Recv:  T:247.11 /240.00 B:59.96 /60.00 @:0 B@:25 W:9
Recv: echo:busy: processing
Recv:  T:248.44 /240.00 B:60.00 /60.00 @:0 B@:23
Recv:  T:249.30 /240.00 B:59.88 /60.00 @:0 B@:28 W:9
Recv:  T:248.83 /240.00 B:60.00 /60.00 @:0 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:248.75 /240.00 B:60.01 /60.00 @:0 B@:22
Recv:  T:250.86 /240.00 B:59.99 /60.00 @:0 B@:24 W:9
Recv:  T:251.09 /240.00 B:60.01 /60.00 @:0 B@:22 W:9
Recv: echo:busy: processing
Recv:  T:248.52 /240.00 B:59.97 /60.00 @:0 B@:24
Recv:  T:247.73 /240.00 B:60.00 /60.00 @:0 B@:23 W:9
Recv:  T:248.67 /240.00 B:59.99 /60.00 @:0 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:248.91 /240.00 B:59.96 /60.00 @:0 B@:25
Recv:  T:245.86 /240.00 B:60.02 /60.00 @:0 B@:22 W:9
Recv:  T:245.08 /240.00 B:60.02 /60.00 @:0 B@:22 W:9
Recv: echo:busy: processing
Recv:  T:245.94 /240.00 B:60.02 /60.00 @:0 B@:22
Recv:  T:244.53 /240.00 B:60.00 /60.00 @:0 B@:23 W:9
Recv:  T:245.31 /240.00 B:59.99 /60.00 @:0 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:245.23 /240.00 B:60.01 /60.00 @:0 B@:23
Recv:  T:242.42 /240.00 B:59.90 /60.00 @:0 B@:28 W:9
Recv:  T:242.81 /240.00 B:60.01 /60.00 @:0 B@:23 W:8
Recv: echo:busy: processing
Recv:  T:240.78 /240.00 B:60.00 /60.00 @:17 B@:23
Recv:  T:241.33 /240.00 B:60.02 /60.00 @:0 B@:22 W:7
Recv:  T:239.19 /240.00 B:59.92 /60.00 @:47 B@:27 W:9
Recv: echo:busy: processing
Recv:  T:238.81 /240.00 B:60.03 /60.00 @:53 B@:22
Recv:  T:238.56 /240.00 B:60.03 /60.00 @:57 B@:22 W:8
Recv:  T:238.50 /240.00 B:60.01 /60.00 @:57 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:237.06 /240.00 B:60.02 /60.00 @:96 B@:22
Recv:  T:236.06 /240.00 B:60.01 /60.00 @:124 B@:23 W:9
Recv:  T:235.69 /240.00 B:60.03 /60.00 @:127 B@:22 W:9
Recv: echo:busy: processing
Recv:  T:235.13 /240.00 B:60.05 /60.00 @:127 B@:21
Recv:  T:233.25 /240.00 B:60.01 /60.00 @:127 B@:23 W:9
Recv:  T:234.19 /240.00 B:59.99 /60.00 @:127 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:234.44 /240.00 B:60.05 /60.00 @:127 B@:21
Recv:  T:233.13 /240.00 B:60.05 /60.00 @:127 B@:21 W:9
Recv:  T:234.25 /240.00 B:60.02 /60.00 @:127 B@:22 W:9
Recv: echo:busy: processing
Recv:  T:232.75 /240.00 B:59.97 /60.00 @:127 B@:25
Recv:  T:234.19 /240.00 B:60.02 /60.00 @:127 B@:22 W:9
Recv:  T:235.31 /240.00 B:60.05 /60.00 @:127 B@:21 W:9
Recv: echo:busy: processing
Recv:  T:234.44 /240.00 B:60.05 /60.00 @:127 B@:21
Recv:  T:235.81 /240.00 B:59.92 /60.00 @:127 B@:27 W:9
Recv:  T:237.13 /240.00 B:60.06 /60.00 @:127 B@:20 W:9
Recv: echo:busy: processing
Recv:  T:238.38 /240.00 B:60.00 /60.00 @:127 B@:23
Recv:  T:237.25 /240.00 B:59.97 /60.00 @:127 B@:24 W:9
Recv:  T:239.94 /240.00 B:60.03 /60.00 @:104 B@:21 W:8
Recv: echo:busy: processing
Recv:  T:241.72 /240.00 B:60.00 /60.00 @:60 B@:23
Recv:  T:240.47 /240.00 B:60.02 /60.00 @:96 B@:22 W:7
Recv:  T:242.11 /240.00 B:59.92 /60.00 @:56 B@:27 W:6
Recv: echo:busy: processing
Recv:  T:243.59 /240.00 B:60.05 /60.00 @:16 B@:21
Recv:  T:244.61 /240.00 B:60.00 /60.00 @:0 B@:23 W:9
Recv:  T:244.77 /240.00 B:59.95 /60.00 @:0 B@:25 W:9
Recv: echo:busy: processing
Recv:  T:246.09 /240.00 B:60.06 /60.00 @:0 B@:20
Recv:  T:245.70 /240.00 B:60.01 /60.00 @:0 B@:22 W:9
Recv:  T:248.44 /240.00 B:59.99 /60.00 @:0 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:248.13 /240.00 B:60.06 /60.00 @:0 B@:20
Recv:  T:248.98 /240.00 B:59.97 /60.00 @:0 B@:24 W:9
Recv:  T:248.67 /240.00 B:59.99 /60.00 @:0 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:247.42 /240.00 B:60.00 /60.00 @:0 B@:23
Recv:  T:250.23 /240.00 B:59.96 /60.00 @:0 B@:25 W:9
Recv:  T:248.83 /240.00 B:59.99 /60.00 @:0 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:248.91 /240.00 B:59.88 /60.00 @:0 B@:28
Recv:  T:248.05 /240.00 B:60.02 /60.00 @:0 B@:22 W:9
Recv:  T:250.55 /240.00 B:60.00 /60.00 @:0 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:248.20 /240.00 B:60.03 /60.00 @:0 B@:21
Recv:  T:247.81 /240.00 B:59.96 /60.00 @:0 B@:25 W:9
Recv:  T:247.19 /240.00 B:60.01 /60.00 @:0 B@:22 W:9
Recv: echo:busy: processing
Recv:  T:246.56 /240.00 B:60.02 /60.00 @:0 B@:22
Recv:  T:246.80 /240.00 B:59.97 /60.00 @:0 B@:24 W:9
Recv:  T:244.06 /240.00 B:59.97 /60.00 @:0 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:244.84 /240.00 B:59.93 /60.00 @:0 B@:26
Recv:  T:242.97 /240.00 B:60.01 /60.00 @:0 B@:22 W:9
Recv:  T:242.66 /240.00 B:59.99 /60.00 @:0 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:241.72 /240.00 B:59.93 /60.00 @:0 B@:26
Recv:  T:242.11 /240.00 B:60.01 /60.00 @:0 B@:22 W:9
Recv:  T:239.75 /240.00 B:59.95 /60.00 @:36 B@:25 W:8
Recv: echo:busy: processing
Recv:  T:238.81 /240.00 B:60.02 /60.00 @:57 B@:22
Recv:  T:238.38 /240.00 B:60.01 /60.00 @:64 B@:22 W:7
Recv:  T:238.69 /240.00 B:60.03 /60.00 @:52 B@:21 W:6
Recv: echo:busy: processing
Recv:  T:238.56 /240.00 B:59.99 /60.00 @:55 B@:24
Recv:  T:236.75 /240.00 B:60.00 /60.00 @:104 B@:23 W:9
Recv:  T:236.44 /240.00 B:60.00 /60.00 @:115 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:235.13 /240.00 B:60.01 /60.00 @:127 B@:22
Recv:  T:234.69 /240.00 B:60.07 /60.00 @:127 B@:20 W:9
Recv:  T:235.19 /240.00 B:59.99 /60.00 @:127 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:233.50 /240.00 B:60.01 /60.00 @:127 B@:23
Recv:  T:233.31 /240.00 B:60.01 /60.00 @:127 B@:23 W:9
Recv:  T:233.88 /240.00 B:59.99 /60.00 @:127 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:234.13 /240.00 B:60.00 /60.00 @:127 B@:23
Recv:  T:233.38 /240.00 B:60.01 /60.00 @:127 B@:23 W:9
Recv:  T:234.44 /240.00 B:59.99 /60.00 @:127 B@:24 W:9
Recv: echo:busy: processing
Recv:  T:234.81 /240.00 B:59.97 /60.00 @:127 B@:24
Recv:  T:235.88 /240.00 B:59.99 /60.00 @:127 B@:24 W:9
Recv:  T:236.63 /240.00 B:60.02 /60.00 @:127 B@:22 W:9
Recv: echo:busy: processing
Recv:  T:236.56 /240.00 B:59.95 /60.00 @:127 B@:26
Recv:  T:238.88 /240.00 B:60.05 /60.00 @:123 B@:21 W:9
Recv:  T:241.56 /240.00 B:60.01 /60.00 @:57 B@:23 W:9
Recv: echo:busy: processing
Recv:  T:238.94 /240.00 B:60.05 /60.00 @:127 B@:21
Recv:  T:239.31 /240.00 B:59.96 /60.00 @:123 B@:25 W:8
Recv:  T:242.97 /240.00 B:60.03 /60.00 @:32 B@:22 W:7
Recv: echo:busy: processing
Recv:  T:238.69 /240.00 B:60.00 /60.00 @:127 B@:23
Recv:  T:243.28 /240.00 B:60.03 /60.00 @:25 B@:22 W:9`

**Comment by tatusah** [comment]
Alright, very interesting. Comparing the two config versions show the first using bed thermistor 12 and the later one has thermistor 1. I know that the issue concerns the hotend temperature but if there is changes now with the bed thermistor then I think it's worth checking whether hotend thermistor type was also changed by accident. What printer model do you have or is it totally diy? Do you know which type / can you compare with the old firmware configs which thermistor type you had set for hotend?

At least on different control boards (SKR mini e3 v1.2 & Creality v.1.1.3) the PID temp seems to be working accurately with Marlin 2.0.1. With no other reports of the kind of issue you are describing this leads me to believe this is caused by either hardware fault, connection problem or configuration error. Googling around I noticed there has been similar reports of temperature problems with your board MKS gen L v1.0 but they were caused by power line problems and faulty capacitors on the board.

Do you have any graphs of the temperature from the previous firmware version and what was the previous version you were using? Old configs available? Have you been able to check with M503 that the tuned PID settings are actually saved especially if you turn of the printer before checking?

**Comment by TAOGde** [comment]
> Do you have any graphs of the temperature from the previous firmware version and what was the previous version you were using? Old configs available? Have you been able to check with M503 that the tuned PID settings are actually saved especially if you turn of the printer before checking?

I yoused today my beta 2.0.x firmware version from 14.9. this year. The right graph is the working version. The print works perfect without any issues. 
Upgrade to the actual version loaded from homepage is the problem in the left graph.

<img width="620" alt="Bildschirmfoto 2019-12-28 um 12 45 10" src="https://user-images.githubusercontent.com/43980652/71548154-6a21ca80-29aa-11ea-8d4c-6a625c9353f5.png">
 graph.


so I can say that my board with all parts work well. My printer is an FlyingBear Ghost4 with MKS Gen L v1.0

**Comment by tatusah** [comment]
Good to know. I suppose the old firmware was then also able to keep the temperature stable on higher temperatures like the 230 degrees you were testing on the newer version? Did you compile the older firmware yourself or was precompiled from the manufacturer? What I'm after is that do you have some source telling what type of thermistors and heating elements the printer uses? 

Luckily I was able to find this [repository](https://github.com/alexxxdev/Ghost4/blob/master/Configuration.h) with configuration for the Ghost 4. I'm not sure the author of the repository is actually affiliated with the manufacturer or not but it's a source anyway. Interesting details from the configuration is these:

```
#define BANG_MAX 150     // Limits current to nozzle while in bang-bang mode; 255=full current
#define PID_MAX BANG_MAX // Limits current to nozzle while PID is active (see PID_FUNCTIONAL_RANGE below); 255=full current
#define PID_K1 0.95      // Smoothing factor within any PID loop
```

Also the example has TEMP_SENSOR values for hotend and bed type number 11 and the bed heating was set to use BANG BANG which often is enough because the mass of the bed makes it so that the heat doesn't actually oscillate that much even with on/off control and it also wouldn't be so demanding for a 8-bit control board processor. Main thing in the example is the BANG_MAX 150, which could indicate that the hotend heating cartridge could be so powerful that it makes sense to limit the max current so that it wouldn't cause the temperature overshooting and sawtooth oscillation. Too aggressive and powerful heating element could . And as you can see the same BANG_MAX is also used for the PID_MAX. So if the old firmware wasn't compiled by you and you don't know the configuration values in that old firmware I would also try adjusting the BANG_MAX and perhaps also the TEMP_SENSOR types.

Just out of curiosity I read through some of the PID related code and didn't come up with a Marlin related cause for your issues. If the previous firmware wasn't compiled by you and the above settings doesn't help fix the issue and there isn't actual information of the needed settings and components used in your printer I think you would then need to get this information from the manufacturer and/or have them provide with new Marlin firmware. Alternatively someone else with MKS gen L or similar board would need to reproduce the issue. I still have high expectations with lowering the bang max value.

**Comment by thisiskeithb** [comment]
> Googling around I noticed there has been similar reports of temperature problems with your board MKS gen L v1.0 but they were caused by power line problems and faulty capacitors on the board.

I struggled with maintaining temps with a couple Gen-L boards because of board issues. It drove me bonkers until I had one Gen-L that worked fine and realized that it was a design/manufacturing flaw after finding more reports of the same issue online.

I've been running `bugfix-2.0.x` on my [highly modded](https://github.com/thisiskeithb/Marlin/tree/myskr) SKR 1.3'd "Ender-3" with PID for the hotend/bang-bang for the bed (running an SSR/AC-powered bed) and it's been rock solid, so I don't think it's broken on `LPC176x` at least:

![image](https://user-images.githubusercontent.com/13375512/71550897-72b8d780-298f-11ea-9049-dc7ae293cc7f.png)

![image](https://user-images.githubusercontent.com/13375512/71550893-6765ac00-298f-11ea-84c9-eaaa4bc60b6a.png)

**Comment by tatusah** [comment]
Good, I actually noticed some of your previous issue posts @thisiskeithb about MKS gen L temperature. I have also both 8 and 32 bit boards working fine with PID temp on bugfix and actual 2.0.1 release. So this doesn't seem like an actual bug in the core code.

**Comment by TAOGde** [comment]
> Good to know. I suppose the old firmware was then also able to keep the temperature stable on higher temperatures like the 230 degrees you were testing on the newer version? Did you compile the older firmware yourself or was precompiled from the manufacturer? What I'm after is that do you have some source telling what type of thermistors and heating elements the printer uses?
> 
> Luckily I was able to find this [repository](https://github.com/alexxxdev/Ghost4/blob/master/Configuration.h) with configuration for the Ghost 4. I'm not sure the author of the repository is actually affiliated with the manufacturer or not but it's a source anyway. Interesting details from the configuration is these:
> 
> ```
> #define BANG_MAX 150     // Limits current to nozzle while in bang-bang mode; 255=full current
> #define PID_MAX BANG_MAX // Limits current to nozzle while PID is active (see PID_FUNCTIONAL_RANGE below); 255=full current
> #define PID_K1 0.95      // Smoothing factor within any PID loop
> ```
> 
> Also the example has TEMP_SENSOR values for hotend and bed type number 11 and the bed heating was set to use BANG BANG which often is enough because the mass of the bed makes it so that the heat doesn't actually oscillate that much even with on/off control and it also wouldn't be so demanding for a 8-bit control board processor. Main thing in the example is the BANG_MAX 150, which could indicate that the hotend heating cartridge could be so powerful that it makes sense to limit the max current so that it wouldn't cause the temperature overshooting and sawtooth oscillation. Too aggressive and powerful heating element could . And as you can see the same BANG_MAX is also used for the PID_MAX. So if the old firmware wasn't compiled by you and you don't know the configuration values in that old firmware I would also try adjusting the BANG_MAX and perhaps also the TEMP_SENSOR types.
> 
> Just out of curiosity I read through some of the PID related code and didn't come up with a Marlin related cause for your issues. If the previous firmware wasn't compiled by you and the above settings doesn't help fix the issue and there isn't actual information of the needed settings and components used in your printer I think you would then need to get this information from the manufacturer and/or have them provide with new Marlin firmware. Alternatively someone else with MKS gen L or similar board would need to reproduce the issue. I still have high expectations with lowering the bang max value.

i compiled all my firmware by my self. the working one and the bang_bang version.
the working on is only the hex file left. the rest is overwritten with the actual version :(

I know the repo you found. with this temperature sensor settings I got very wrong real temperature. I used an external sensor to match the value in the printer with my external sensor and at this point I stay at type 1 in this section.

the type of sensor in this printer I not known.

**Comment by TAOGde** [comment]
I startet testing with  fresh installation and setting up every thing step by step with testing the temperature settings.
at the point "#define EEPROM_SETTINGS     // Persistent storage with M500 and M501" the bang_bang starts.
<img width="621" alt="Bildschirmfoto 2019-12-29 um 04 48 04" src="https://user-images.githubusercontent.com/43980652/71552118-792e6a00-29f6-11ea-812e-9508210e7c5d.png">

**Comment by tatusah** [comment]
You shouldn't need to use M501 as it's for cancelling unsaved settings and reverting to the last saved settings. I would use M303 for autotuning to desired temperature and set those values to configuration.h and flash the firmware again. Then M502 & M500. After that M503 to confirm that the PID settings you placed in the configuration are actually loaded.

**Comment by TAOGde** [comment]
> You shouldn't need to use M501 as it's for cancelling unsaved settings and reverting to the last saved settings. I would use M303 for autotuning to desired temperature and set those values to configuration.h and flash the firmware again. Then M502 & M500. After that M503 to confirm that the PID settings you placed in the configuration are actually loaded.

and that is the problem. I do this ^^ and the temperature goes bang_bang here. only without this setting in the source code all works like a charm before.

**Comment by lrpirlet** [comment]
Well, when everything fails, it may be better going to the principles…

I suggest you have a look at this [https://en.wikipedia.org/wiki/PID_controller](https://en.wikipedia.org/wiki/PID_controller)... Have a close look in the **Manual tuning** paragraph at the animated curve and notice how the curve evolve with the 3 parameters…

Now, in the configuration.h file notice and follow this link [https://reprap.org/wiki/PID_Tuning](https://reprap.org/wiki/PID_Tuning)... Notice the **Modifying Marlin Autotune parameters** paragraph

It so happens that I had a lot of overshoot and a badly oscillating temp (I thought it was bang-bang)… Using the following did solve MY problem… maybe it helps.

> You can transform these "Classic" parameters into the Zeigler-Nichols "Some Overshoot" set with: 
>     Kp=Kp_classic*0.55
>     Ki=Ki_classic
>     Kd=Kd_classic*8/3

Enjoy.

**Comment by AnHardt** [comment]
![image](https://user-images.githubusercontent.com/211931/71558178-96902200-2a50-11ea-8b84-f2bad5d961b1.png)

The above graph from autotune clearly shows - not enough iterations.
Target is to get about the same times above and below the target temperature.
If you can't get there with much more iterations, lower the PID_MAX.

**Comment by TAOGde** [comment]
so, i test it again with M500 M501 and M502 commands after firmware flashing.
Hardcode load from firmware, writing to eprom and loading from it and the BANG_BANG is on. When i turn off the eeprom storage in the firmware ALL is fine and the PIDtemperature works well.

**Comment by boelle** [comment]
is this a bug or a support question?

**Comment by boelle** [comment]
> When i turn off the eeprom storage in the firmware ALL is fine and the PIDtemperature works well.

i assume this means it solved.... if not we can reopen if this is a bug and not support help
