### ISSUE TITLE
[FR] PID Autotune for other extruders other than 0

### ISSUE THREAD

**Issue by Liger0** [MarlinFirmware/Marlin#16344]
### Description
It would be useful to add the possibility to do a PID Autotune for other extruders other than E0. 
I don't have the possibility to directly send gcodes to my printer so I need it in order to autotune.

**Comment by Vertabreak** [comment]
add custom commands.
example:
  #define USER_DESC_4 "PID Autotune End"
  #define USER_GCODE_4 "M303 U1 E0 S250 C8\nM500"

  #define USER_DESC_5 "PID Autotune Bed"
  #define USER_GCODE_5 "M303 U1 E-1 S90 C8\nM500"
