### ISSUE TITLE
[BUG] BLtouch don't deploy in homing

### ISSUE THREAD

**Issue by Raffa2s** [MarlinFirmware/Marlin#16352]
Hi,
I had installed marlin 2.0-bugfixes on my rumba board, when I turn it on bltouch work like usual (self test on boot) but when I hit "auto home" it will not deploy the probe, how can be fixed?
Thank you

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by Raffa2s** [comment]
I had fixed this in this way on my rumba board :

> // coarse Endstop Settings
> #define ENDSTOPPULLUPS // Comment this out (using // at the start of the line) to disable the endstop pullup resistors
> 
> #if DISABLED(ENDSTOPPULLUPS)
>   // fine endstop settings: Individual pullups. will be ignored if ENDSTOPPULLUPS is defined
>    //#define ENDSTOPPULLUP_XMAX
>   //#define ENDSTOPPULLUP_YMAX
>   #define ENDSTOPPULLUP_ZMAX
>   #define ENDSTOPPULLUP_XMIN
>   #define ENDSTOPPULLUP_YMIN
>   #define ENDSTOPPULLUP_ZMIN
>   #define ENDSTOPPULLUP_ZMIN_PROBE
>   // tech2c active XMIN YMIN ZMIN
> #endif
> 
> // Enable pulldown for all endstops to prevent a floating state
> //#define ENDSTOPPULLDOWNS
> #if DISABLED(ENDSTOPPULLDOWNS)
>   // Disable ENDSTOPPULLUPS to set pullups individually
>   //#define ENDSTOPPULLUP_XMAX
>   //#define ENDSTOPPULLUP_YMAX
> //  #define ENDSTOPPULLUP_ZMAX
> //  #define ENDSTOPPULLUP_XMIN
> //  #define ENDSTOPPULLUP_YMIN
> //  #define ENDSTOPPULLUP_ZMIN
> //  #define ENDSTOPPULLUP_ZMIN_PROBE
> #endif
> 
> // Mechanical endstop with COM to ground and NC to Signal uses "false" here (most common setup).
> #define X_MIN_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
> #define Y_MIN_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
> #define Z_MIN_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
> #define X_MAX_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
> #define Y_MAX_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
> #define Z_MAX_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
> #define Z_MIN_PROBE_ENDSTOP_INVERTING true // set to true to invert the logic of the probe.
> 
> /**
