### ISSUE TITLE
[BUG] Z_DUAL_STEPPER_DRIVER  TMC2209 SKR 1.3

### ISSUE THREAD

**Issue by marcocm** [MarlinFirmware/Marlin#16351]
### Bug Description

Hi all!
I have a skr 1.3 board with 4 tmc2209.
I am trying to use Z_DUAL_STEPPER_DRIVERS, where I connect the z2 stepper motor to E1 connection on the board.

I used in configuration.h 
#define X_DRIVER_TYPE  TMC2209
#define Y_DRIVER_TYPE  TMC2209
#define Z_DRIVER_TYPE  TMC2209
//#define X2_DRIVER_TYPE A4988
//#define Y2_DRIVER_TYPE A4988
#define Z2_DRIVER_TYPE TMC2209
//#define Z3_DRIVER_TYPE A4988
#define E0_DRIVER_TYPE TMC2209

 #define DEFAULT_AXIS_STEPS_PER_UNIT   { 100, 100, 400, 418.5450328 }

and in configuration_adv.h

#define Z_DUAL_STEPPER_DRIVERS

  #if AXIS_IS_TMC(Y)
    #define Y_CURRENT       760
    #define Y_CURRENT_HOME  Y_CURRENT
    #define Y_MICROSTEPS     16
    #define Y_RSENSE          0.11
    #define Y_CHAIN_POS      -1
  #endif

#if AXIS_IS_TMC(Z)
    #define Z_CURRENT       760
    #define Z_CURRENT_HOME  Z_CURRENT
    #define Z_MICROSTEPS     16
    #define Z_RSENSE          0.11
    #define Z_CHAIN_POS      -1
  #endif

  #if AXIS_IS_TMC(Z2)
    #define Z2_CURRENT      760
    #define Z2_CURRENT_HOME Z2_CURRENT
    #define Z2_MICROSTEPS    16
    #define Z2_RSENSE         0.11
    #define Z2_CHAIN_POS     -1
  #endif    

#if AXIS_IS_TMC(E0)
    #define E0_CURRENT      900
    #define E0_MICROSTEPS    16
    #define E0_RSENSE         0.11
    #define E0_CHAIN_POS     -1
  #endif

But when I Send de M122 command, the results aren't as I expected. Because it sais the Z2  for example has no stealthChop activated, and also Set current is different from what I choose.
Also the Z2 motor is doing a lot of noise. 

Some one can help me?

[Arquivo.zip](https://github.com/MarlinFirmware/Marlin/files/4005282/Arquivo.zip)

SENT: M122
READ: 		X	Y	Z	Z2	E
READ: Address		0	0	0	0	0
READ: Enabled		false	false	false	false	false
READ: Set current	760	760	760	500	900
READ: RMS current	734	734	734	489	887
READ: MAX current	1035	1035	1035	689	1251
READ: Run current	23/31	23/31	23/31	15/31	28/31
READ: Hold current	11/31	11/31	11/31	7/31	14/31
READ: CS actual	11/31	11/31	11/31	7/31	14/31
READ: PWM scale	43	45	48	9	16
READ: vsense		1=.18	1=.18	1=.18	1=.18	1=.18
READ: stealthChop	true	true	true	false	true
READ: msteps		16	16	16	16	16
READ: tstep		max	max	max	max	max
READ: pwm
READ: threshold	79	79	658	0	63
SENT: M105
READ: [mm/s]		100	100	3	-	30
READ: OT prewarn	false	false	false	false	false
READ: OT prewarn has
READ: been triggered	false	false	false	false	false
READ: off time	3	3	3	3	3
READ: blank time	24	24	24	24	24
READ: hysteresis
READ: -end		-1	-1	-1	-1	-1
READ: -start		1	1	1	1	1
READ: Stallguard thrs	130	130	0	0	0
READ: DRVSTATUS	X	Y	Z	Z2	E
READ: stst		*	*	*	*	*
READ: olb						
READ: ola						
READ: s2gb						
READ: s2ga						
READ: otpw						
READ: ot						
READ: 157C						
READ: 150C						
READ: 143C						
READ: 120C						
READ: s2vsa						
READ: s2vsb						
READ: Driver registers:
READ: 		X	0xC0:0B:00:00
READ: 		Y	0xC0:0B:00:00
READ: 		Z	0xC0:0B:00:00
READ: 		Z2	0x80:07:00:00
READ: 		E	0xC0:0E:00:00

[Arquivo.zip](https://github.com/MarlinFirmware/Marlin/files/4005285/Arquivo.zip)

**Comment by randellhodges** [comment]
It might be reading what is in the EEPROM and not the configuration file changes.

Run `M503` and see what it says. For example, here is a snippet from mine:

```
Recv: echo:Stepper driver current:
Recv: echo:  M906 X1200 Y1200 Z1200
Recv: echo:  M906 I1 Z1200
Recv: echo:  M906 T0 E980
```

This is my 2nd z stepper: `M906 I1 Z1200`

You can either use that command to set it, or make note of any EEPROM settings you changed, then do a `M502` (factory reset) to reset EEPROM and `M500` to save that reset. You'll lose EEPROM only settings as everything will be replaced with defaults from the firmware.

**Comment by marcocm** [comment]
I checked this values just after I updated the firmware. It is supposed to still read the EEPROM after I update the firmware?
I will try it when I get in touch with the printer again.

**Comment by randellhodges** [comment]
Yes, unless the firmware changes the EEPROM structure it will continue to load EEPROM settings after a firmware update. That is why a lot of people suggest doing the EEPROM reset after every firmware update.

I don't unless I know I'm changing a value like you are, or I just run the gcode to set the value in the EEPROM (and also have the change in the firmware for later, when I do reset and forget).

**Comment by marcocm** [comment]
It worked.. thank you!

**Comment by marcocm** [comment]
It Worked, Thank You!
