### ISSUE TITLE
[FR] Include E-jerk in M205 and Advanced Settings menu when JD is enabled

### ISSUE THREAD

**Issue by Reywas62** [MarlinFirmware/Marlin#16357]
Since E-jerk is still used by Linear Advance even when Junction Deviation is enabled, we need to be able to read and adjust that value for tuning purposes.  Currently it seems the only way to verify or change the E-jerk setting if JD is enabled is to view/edit the source code.

**Comment by Reywas62** [comment]
Is this likely to get done anytime soon?

**Comment by thisiskeithb** [comment]
Closing since `DEFAULT_EJERK` is not used when `CLASSIC_JERK` is disabled / Junction Deviation is enabled.
