### ISSUE TITLE
[BUG] LCD 20x4 text moving constantly 

### ISSUE THREAD

**Issue by jonathan-iap** [MarlinFirmware/Marlin#16378]
### Bug Description

The text on my LCD is constantly moving and it doesn't have the right indentation like if an overflow occur.

### My Configurations
Hardware : 
Printrbot plus v2-1
Motherboard printrboard revD
LCD reprap 20x2 
Software : 
Marlin 2.0 and bug fix
[conf_Marlin2_printrbotPlus.zip](https://github.com/MarlinFirmware/Marlin/files/4008200/conf_Marlin2_printrbotPlus.zip)

### Steps to Reproduce
1. upload firmware with joined conf.h files or just uncoment 
#define REPRAP_DISCOUNT_SMART_CONTROLLER 
in LCD character section 
2. show the result

**Expected behavior:** [What you expect to happen]
Boot screen appear correctly fallow to the menu with clear informations.  
**Actual behavior:** [What actually happens]
At boot screen the indentation is incorrect and the logo doesn't appear correctly. 
After, menu is showing but is constantly moving and mixing with unknown character like an overflow.
 
#### Additional Information
![IMG_20191229_164036 redimensionne](https://user-images.githubusercontent.com/11634971/71559147-0acfc300-2a5b-11ea-84f9-f2a520aed7b6.jpg)
![IMG_20191229_164032 redimensionne](https://user-images.githubusercontent.com/11634971/71559148-0b685980-2a5b-11ea-85cd-d8e059e9a840.jpg)
![IMG_20191229_164039 redimensionne](https://user-images.githubusercontent.com/11634971/71559149-0c998680-2a5b-11ea-8306-4529fb17a086.jpg)
![IMG_20191229_164037 redimensionne](https://user-images.githubusercontent.com/11634971/71559153-0dcab380-2a5b-11ea-94f5-f528c5a56fcd.jpg)

**Comment by ellensp** [comment]
How did you compile it Arduino IDE or VSCODE? Are all your libraries and Boards up to date?
If Arduino IDE what version of arduino?

**Comment by ellensp** [comment]
Also since it looks like a timing thing can you confirm what chip your board has? Most printrboards have a 16mhz AT90USB1286 but some have a faster 20mhz AT90USB1287

**Comment by jonathan-iap** [comment]
Hi ellensp, i didn't  try with Arduino but  today it's work with Arduino 1.8.10 and board with 16Mhz crystal. 
The bug report is with PlatformIO and VScode.

**Comment by jonathan-iap** [comment]
So PlatformIO download automatically all libraries needed, i don't how to force version ?

**Comment by jonathan-iap** [comment]
I'm thinking i can continue with Arduino IDE but when i turn #define SDSUPPORT
My LCD display blank square, i think is an other bug in relation with the space memory.

**Comment by ellensp** [comment]
sadly processors with less than 256MB of flash (such as AT90USB1286 and sanguino based boards) are just to small for modern firmwares.  It is really time to consider a nice 32bit upgrade

**Comment by jonathan-iap** [comment]
So with the Marlin 1.1.9 i can use the LCD, SDSUPPORT, EEPROM and bed leveling (just for comparison). My Flash with the bootloarder is close to 99% but it's work.
With Marlin 2.0 LCD is not supported correctly when you compile from platformIO and if you pass by Arduino and you active only SDSUPPORT with LCD, LCD is lost.
I don't think all my problems is in like with space memory but Marlin 2.0 is not for my setup lol.

**Comment by boelle** [comment]
@jonathan-iap is this one solved in that you know  your hardware is not up for it?

**Comment by jonathan-iap** [comment]
yes you can close my issue
