### ISSUE TITLE
[FR] Stepper-phase homing

### ISSUE THREAD

**Issue by Maeyanie** [MarlinFirmware/Marlin#16383]
### Description

One of the few nice features Klipper has and Marlin lacks is stepper-phase-assisted homing, and in particular, the ability to align the Z homing to phase 0.

Basically, it's able to track the current phase of the stepper, either from querying the driver on TMC or similar, or counting steps from last power-on on other drivers. Then, it will align to the same phase on homing to improve the precision of the endstops.

This can also used to specifically force the Z=0 point to be phase 0 on the stepper, meaning if you use layers as whole multiples of the step size, each layer will be exactly aligned with a full step instead of a microstep.

It is not a priority feature, for sure, but it would be nice if it were to appear at some point.

#### Additional Information

* https://www.klipper3d.org/Endstop_Phase.html

**Comment by swilkens** [comment]
A PR has been merged, can we close this?
