### ISSUE TITLE
[FR] Use Firmware Retraction before "Stop Print" function

### ISSUE THREAD

**Issue by qwewer0** [MarlinFirmware/Marlin#16406]
### Description

Marlin could have an option in Configuration_adv.c to apply the Firmware Retraction when the "Stop Print" is pressed in the LCD menu.

### Feature Workflow

Just a little change to the "Stop Print" function.
If Firmware Retraction is enabled, than before it turns off the heating and would park the printer, it could use the Firmware Retraction value first, than do the usual.
It would not leave a string behind the nozzle, and would not ooze.

**Comment by Lord-Quake** [comment]
Have you tried it with this option in `Configuration_adv.c`  (example):

`#define EVENT_GCODE_SD_STOP "G1 E-1\nG27" // Retract 1mm of filament then park extruder`

**Comment by qwewer0** [comment]
Will work for my problem, thanks.

**Comment by pmjdebruijn** [comment]
Say for example an Ender3 you'd want something like this:

```
#define NOZZLE_PARK_FEATURE
#define NOZZLE_PARK_POINT { 5, 175, 100 }
#define EVENT_GCODE_SD_STOP "G1 E-3 F3600\nG27 P2"
```

Specifically mind the `G27 P2`

**Comment by qwewer0** [comment]
Would it work with #define EVENT_GCODE_SD_STOP "G10\nG27 P2", if firmware retraction is enabled?

**Comment by pmjdebruijn** [comment]
I've never used firmware based retraction, so I don't know, however doing some brief googling would seems to suggest you might be right.

**Comment by pmjdebruijn** [comment]
The other consideration is whether you want to retract the same amount at the end of a print, as opposed to during printing, since that might not per-se be the case.

**Comment by qwewer0** [comment]
I will try it out, and will tell the outcome.

**Comment by qwewer0** [comment]
For the first test it works great.

```
#define NOZZLE_PARK_POINT { 0, (Y_MAX_POS - 10), 20 }
#define EVENT_GCODE_SD_STOP "G10\nG27 P2\nM84"
```
