### ISSUE TITLE
Improve the management of the printer type

### ISSUE THREAD

**Issue by Drakelive** [MarlinFirmware/Marlin#1641]
Hi

I like the work done by #MagoKimbra (https://github.com/MagoKimbra/MarlinKimbra/blob/master/MarlinKimbra/Configuration.h) on his Marlin Fork 
I'm sure this greatly simplifies the configuration of a printer
He define a type printer :

/**********************************************************************_\
***_***********************\* Define type printer **********************
***********************************************************************/
# define CARTESIAN

//#define COREXY
//#define DELTA
//#define SCARA
# if defined(CARTESIAN)

```
  #include "Configuration_Cartesian.h"
```
# elif defined(COREXY)

```
 #include "Configuration_Corexy.h"
```
# elif defined(DELTA)

```
 #include "Configuration_Delta.h"
```
# elif defined(SCARA)

```
 #include "Configuration_Scara.h"
```
# endif

You think that you can implement this approach in MarlinFirmware?

Regard 
Drake

**Comment by tonnico** [comment]
A third file to maintain? I don't see any benefit.

**Comment by boelle** [comment]
me neither.... and we are going for a web interface to do config anyway.... so this one is a no go i think

**Comment by thinkyhead** [comment]
I do understand the appeal, but I agree that fewer config files is better. That said, some of the code in the configuration files is not meant to be edited by users (code that conditionally sets defines for LCDs and things like that), and that code might end up in an additional file along with some #if / #error blocks that make sure configuration options are within bounds and throw errors, to catch more potential problems at compile-time. That can reduce the size of the config files quite a bit.

**Comment by alexborro** [comment]
Completely agree!

All checks and non-editable defines must be moved to another file.

Scott, any suggestions for this new file name?

Cheers

Alex
Em 19/03/2015 03:49, "Scott Lahteine" notifications@github.com escreveu:

**Comment by boelle** [comment]
why not use the web config?

less confusion factor, but of course it has to be completed first

Den torsdag den 19. marts 2015 skrev alexborro notifications@github.com:

**Comment by AnHardt** [comment]
How about 'postConfiguration.h'?
Could be called at the very end of Configuration.h, right after the inclusion of thermistortables.h

**Comment by tonnico** [comment]
Call it sanityChecks.h or something like this so normal users don't want to look at it.

**Comment by alexborro** [comment]
I agree to SanityCheck.h...

2015-03-19 11:53 GMT-03:00 Wurstnase notifications@github.com:

> Call it sanityChecks.h or something like this so normal users don't want
> to look at it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1641#issuecomment-83614839
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by thinkyhead** [comment]
I'll get the ball rolling on this with a fairly simple PR shortly.

**Comment by thinkyhead** [comment]
#1651 is my first crack at moving invariant configuration code into a separate file (`Conditionals.h`) and moving most error-checking into its own file (`SanityCheck.h`). This reduces the size of the configuration files significantly.

**Comment by thinkyhead** [comment]
#1651 takes the approach of moving invariant configuration code into one file and sanity checks in another. This reduces the size of the configurations significantly, resulting in 3200 fewer lines of code to maintain.

**Comment by AnHardt** [comment]
>  fairly simple PR

:-)
