### ISSUE TITLE
Arduino Due and Marlin firmware (EEPROM)

### ISSUE THREAD

**Issue by BigRepRap** [MarlinFirmware/Marlin#1642]
Hi!

I'm quite new on the 3D printing world so please excuse my stupidity....

I've been doing little research on this board (Due) and is meant not to have EEPROM however the marlin firmware for Due does refer to it (https://github.com/bobc/Marlin). Is this something added externally such as an external EEPROM?

Furthermore is this firmware compatible with Repetier Host?

**Comment by boelle** [comment]
please raise the issue at https://github.com/bobc/Marlin

as for Repetier it should be yes
