### ISSUE TITLE
[BUG] lcd reprapdiscount smart controller with fysetc f6 card 

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#16479]
hello

I had to add the addresses in pin_fystec_f6_13.h to be able to compile

//
// LCDs and Controllers
//
    #define LCD_PINS_RS         16
    #define LCD_PINS_ENABLE     17
    #define LCD_PINS_D4         23
    #define LCD_PINS_D5         25
    #define LCD_PINS_D6         27
    #define LCD_PINS_D7         29
    #define BEEPER_PIN          37
    #define BTN_EN1             31
    #define BTN_EN2             33
    #define BTN_ENC             35
    #define SD_DETECT_PIN       49
    #define KILL_PIN            41

**Comment by ellensp** [comment]
Those pins are all defined in https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/pins/ramps/pins_FYSETC_F6_13.h
Where are your configuration files?

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boubouexpress** [comment]
there must have been an update since i downloaded my marlin
