### ISSUE TITLE
[BUG] Control both extruders from LCD or TFT panel for maintenance

### ISSUE THREAD

**Issue by 1979mgb** [MarlinFirmware/Marlin#16478]
My Dual color printer works. I can control both Extruders using Pronterface by selecting either E0 or E1 then selecting how much, how fast and to extrude or retract. 
I would like to be able to do the same from my printers display. Printer Info reports that I have 1 extruder. I entered number of 2 by mistake. I remembered that number when I had configured printer as 2 extruders and 1 nozzle (not as a mixing printer). Still had same problem in Motion Menu though. Could not control both extruders.
Yet choosing the motion function for extruder only allows control of E0
My request is to be able to do the following:
1. [press Encoder Knob, dial to Motion]
2. [press Encoder Knob, dial to Move Axis]
3. [press Encoder Knob, dial to Extruder]
4. [press encoder Knob, dial to select E0, E1, etc.]
5. [press encoder Knob, dial to select 10mm, 1mm, .1mm]
6. [press encoder Knob, dial to select speed]
7. [press encoder Knob, dial + or - direction to choose total distance]
8. [press encoder to back out]

Except for choosing speed, this function already exists for 1 extruder only it seems. I have watched many videos read many forums searched this site and the answers seem to say that this is not a function in marlin. Have read that it is part of the mixer function. 

This would be useful for maintenance such as calibrating all of the extruders or changing filament.
I have dual drive BMG extruders and using the release levers doesn't let go of the filament so I motor it out. 
It simply would be easier than relying on Pronterface which of course is a very useful tool for so much else.
Thank you for considering this matter. If this function already exists and I have simply missed it I apologize.

See my last comment It would seem that Marlin could be written to control both extruders from the motion control menu even when Printer is programed as a mixing Hot end as in 1 extruder 2 mixing steppers. As in this configuration you can still control both extruders via the change filament menu.
Thank you all for your consideration.

**Comment by ellensp** [comment]
Add CUSTOM_USER_MENUS in Configuration_adv.h to switch tools (ie send T0 or T1)  The extruder tools work on what ever tool is active.   To implement exactly what you want would require rewriting the menu system...

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by 1979mgb** [comment]
Sorry for delay, new to zipping took awhile to figure out how. Here they are I hope. 
In my research it has been suggested that the displays are the limitation not sending T0 or T1.
I am using a BTT TFT35 V2.0 and a stock Ender 3 LCD. Have used each as stand alone and both together, all with same results. 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4028950/Configuration.zip)

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/4028951/Configuration_adv.zip)
Thank you for the hard work.

**Comment by 1979mgb** [comment]
It should be known that CHANGE FILAMENT is working for both E1 and E2. 
But I would still like to incrementally control both extruders. Just curious why Pronterface refers to tool 0 and 1, Marlin configuration.h refers to E0 and E1 yet the Ender 3 stock LCD lists E1 and E2 in Change Filament but no separate definition in the MOTION/MOVE AXIS/EXTRUDER menu. My TFT35 in Extruder menu shows E0 and "nozzle" button that has 01 labeled on it(of course I only have 1 nozzle).  Nomenclature seems to have no standard. It of course is easy to figure what is meant since only dealing with 2 steppers. Sorry, I am  rambling on the opening line is the important bit.

**Comment by 1979mgb** [comment]
Make note of edit in opening request.

**Comment by boelle** [comment]
btw, is this on bugfix 2.0.x?

**Comment by 1979mgb** [comment]
Yes it is.

**Comment by Vertabreak** [comment]
2 motors 1 nozzle has two options mix or single nozzle sounds like you should define single nozzle.

**Comment by 1979mgb** [comment]
Hi, I have configured it both ways and tried to control extruders from motion menu. Presently I am on mix. Could try 2 extruders 1 nozzle again just to be sure.

**Comment by 1979mgb** [comment]
This printer is an A10M with a BTT SKR V1.3 installed.
Now configured as 2 extruder 1 nozzle. Still can only control 1 extruder in Motion menu.
Mixing menu gone.
Change filament Menu still shows both extruders.

**Comment by Vertabreak** [comment]
to switch extrudes with mix you have to adjust the mix ratio from 100/0 to 0/100 everything is virtually defined if you use what i call cyclops listed as single nozzle you can control each motor directly. both methods working as intended i have 7 geeetech machines siting here.im one of the geeetech forum admins i know all about the a10 and its variants. typically you assign Vtools as many as 16 of them and switch between them with mixing. there is a massive lack of understanding of mixing/cyclops control systems everyone thinks they work the way they don't and there is conflicting information all over the web regarding how they work.

**Comment by 1979mgb** [comment]
Not having any problems with mixing or controlling for printing. Looking for maintenance functionality.
For instance extruder calibration. select E0 or E1 dial for 100mm extrude measure repeat until done. 
Change filament menu is wait for the unload cycle, then load and purge.
The motion Menu can select xyz and 1 extruder and tell it exactly what to do and how much and in what direction-but only for 1 extruder. I know that I can do this with Pronterface but connecting to my computer is not always convenient also Pronterface can be tricky  to connect at times.
So when set up as Cyclops how do you control each motor directly from the display controller?
Thanks for all the help.

**Comment by Vertabreak** [comment]
with cyclops in the motion control menu you will find E0 & E1 & E2 should you have 3 like i do.
with single nozzle "cyclops" you will also be able to use distinct esteps allowing each motor to be calibrated unlike mixing.

![IMG_20200108_210927](https://user-images.githubusercontent.com/45634861/72031752-50f70480-325b-11ea-86fe-15ec69f17cf3.jpg)

**Comment by 1979mgb** [comment]
configuration.h define extruders 2 define single nozzle. Is there something else to configure because I still only get 1 extruder to choose from in motion control menu.

**Comment by Vertabreak** [comment]
`  
#define EXTRUDERS 2
#define SINGLENOZZLE`
disable mixing

**Comment by Vertabreak** [comment]
if you have yet to update marlin today you maybe have a bug in your eeprom limiting extruders to 1.

**Comment by 1979mgb** [comment]
Thank you for picture, I know I am a noob but did not think I was this bad. I was using a tft display at first and could not figure out how to select another extruder. So put on the Ender LCD and by that time I had switched configuration over to mixing. Now I am back on cyclops and simply did not turn dial enough to see E1 E2. I was pressing the knob thinking it would take me to a selection menu like the TFT does. Now I will try the mixing and turn the knob and see what happens.
Thank you for teaching me how to turn a knob. Sure am glad you folks are patient.

**Comment by Vertabreak** [comment]
yea photos and videos help alot the devil is in the details seeing explains so much more then just saying it. mixing will show only 1 virtual extruder that is controlled with mix ratio you switch extruders in mix by changing the mix from 100/0/0 to 0/100/0 or 0/0/100 ect depending on bow many motors there are.

**Comment by 1979mgb** [comment]
Am curious though, Why Extruder, Extruder 1 and Extruder 2 as though there are 3 on my machine?

**Comment by Vertabreak** [comment]
the first extruder E0 and the listed E1 are the same entry the menu needs adjusted it should list E0 & E1 ect.

**Comment by Vertabreak** [comment]
ill have a look at the code see if i can fix it up and submit the fix.

**Comment by 1979mgb** [comment]
A speed selection would still be nice, any possibility?

**Comment by 1979mgb** [comment]
So should I close this issue?

**Comment by Vertabreak** [comment]
you can #define ULTIPANEL or exnensible ui and edit the speed of xyze move speed.
`
#if EITHER(ULTIPANEL, EXTENSIBLE_UI)
  #define MANUAL_FEEDRATE { HOMING_FEEDRATE_XY, HOMING_FEEDRATE_XY, HOMING_FEEDRATE_Z, 120 } // Feedrates for manual moves along X, Y, Z, E from panel
  #define SHORT_MANUAL_Z_MOVE 0.025 // (mm) Smallest manual Z move (< 0.1mm)
  #if ENABLED(ULTIPANEL)
    #define MANUAL_E_MOVES_RELATIVE // Display extruder move distance rather than "position"
    #define ULTIPANEL_FEEDMULTIPLY  // Encoder sets the feedrate multiplier on the Status Screen
  #endif
#endif`

**Comment by 1979mgb** [comment]
Will try this tomorrow, thanks

**Comment by 1979mgb** [comment]
Vertabreak, configuration.h has oneline
//#define ULTIPANEL 
I am not a writer of code, am learning by watching videos. Do I add what you provided after uncommenting # define ULTIPANEL ? Not sure where,how to add in what you have written.

**Comment by Vertabreak** [comment]
the config for ultipanel is in config adv search it  #define MANUAL_FEEDRATE

**Comment by 1979mgb** [comment]
So if I enable ULTIPANEL or EXTENSIBLE_UI in config.h it uses the lines in config.adv and these are the ones I can edit? 
I was thinking it was something to add.
Hopefully I am getting it.

**Comment by Vertabreak** [comment]
yes that is what the following line means.
#if EITHER(ULTIPANEL, EXTENSIBLE_UI)
if either of these features are enabled then enable everything inside this if statement until it hits endif.

**Comment by 1979mgb** [comment]
You are a good and patient teacher. Now will have to play with editing the numbers and see what happens. 
#define ULTIPANEL_FEEDMULTIPLY // Encoder sets the feedrate multiplier on the Status Screen #endif #endif
Actually I was only looking to dial in desired speed for extruders, is that what the above line does?

**Comment by Vertabreak** [comment]
i listed what i use above for speeds.
`#define MANUAL_FEEDRATE { HOMING_FEEDRATE_XY, HOMING_FEEDRATE_XY, HOMING_FEEDRATE_Z, 120 } // Feedrates for manual moves along X, Y, Z, E from panel`
xyz i use homing speed and e is 120

**Comment by 1979mgb** [comment]
Enough for tonight will try tomorrow thank you so much. looking forward to see what this does.

**Comment by Vertabreak** [comment]
k ill go back to being a lurking dev lol.

**Comment by 1979mgb** [comment]
Thank you to all the contributors.

**Comment by 1979mgb** [comment]
Ok I now have a better understanding of the function of a 2 in 1 out hot end. I can control both extruders from the display motion menu when Printer is configured as Cyclops with 2 extruders 1 nozzle no mixing.
When configured as a mixing Hot end 1 extruder 2 mixing steppers I can not control the extruders individually from display motion menu.

Even so the printer knows it has 2 extruders as they can be individually controlled via change filament menu.
So it would seem that Marlin could be written to allow individual control of the extruders from the motion control menu even if it configured as a mixing printer. 
Anyone willing to give a try?

**Comment by Vertabreak** [comment]
You switch mix factor to control additional extruders with mix. Default 100/0 switch to 0/100 to change the motor being controlled. In mix marlin sees 1 virtual extruder. It can control both you have to change mix factor. It's works just not how you think it should doesn't mean it doesn't work.

**Comment by 1979mgb** [comment]
So if I leave my printer in mixing configuration. I now remove both filaments to clean out nozzle. I now want to check extruder calibration for what ever reason. From the mixing menu I switch from 100/0 to 0/100 Now I can go to motion menu to extruder and the other extruder is now controlled?

**Comment by Vertabreak** [comment]
Bingo it's 1 virtual extruder mix factor sets what one it controls if you Wana empty both set 50/50 and half of the move goes to each. Or like 33/33/34 with 3 for example.

**Comment by Vertabreak** [comment]
If you defined vtools with set mix ratios you can call that vtool with it's set mix factor.

**Comment by 1979mgb** [comment]
Vertabreak, I ran off to my printer to test this, now I get it. Thank you for your patient teaching once again. The printer does do what I want it to. As you say I just did not understand the relationship.
Not trying to be difficult, but it would seem to be easier from a newbie user aspect if all the motion functions were in one place. I had been blending colors back and forth with mixing for some time without realizing that it had a direct effect on motion menu. That was why I kept using Pronterface.
Thanks again for all the help. Keep up the good work.

**Comment by Vertabreak** [comment]
marlin is a patch work of code some times there is no intuitive controls they where never designed with anything else in mind. i'm just one contributor there are 100s like me over 600 at last count adding things to marlin sometimes things are not well integrated but they work. on the plus side this is all now a searchable document on google anyone can see now so there is that.

**Comment by Vertabreak** [comment]
@boelle I think this one is solved I explained it, seems like it's solved.
