### ISSUE TITLE
Compile error when setting TEMP_SENSOR_BED 1

### ISSUE THREAD

**Issue by detroitfire** [MarlinFirmware/Marlin#1647]
When I set TEMP_SENSOR_BED to 1 I get a compile error:

http://pastebin.com/PbL2x1e9

**Comment by tonnico** [comment]
Setup your heatbed-pin

**Comment by clefranc** [comment]
Is it complicated to throw a compile error when a pin is not define for the sensors (or other)?

**Comment by AnHardt** [comment]
@clefranc 
here it is:

> pins.h:721:33: error: invalid suffix "_RPORT" on integer constant
>     #define HEATER_BED_PIN     -1    // NO BED
>                                 ^

from the above pastebin.

Do you really want more errors?
But i admit - not really easy to find in between the others.

**Comment by AnHardt** [comment]
@clefranc 
No, it isn't so hard to make a test.
We could check for more dependencies.
#if !(TEMP_SENSOR_BED == 0) && !( HEATER_BED_PIN == -1)
  #errror("No pin for bed heater defined.")
#endif

More of a problem is the littering of Configuration.h with this.
We are already discussing possible solutions in #1641.

**Comment by thinkyhead** [comment]
Please feel free to add more tests to `SanityCheck.h`.
