### ISSUE TITLE
[BUG] Boot Loop for Ender 3 SKR v1.3 Dual Extruder setup

### ISSUE THREAD

**Issue by LilJashy** [MarlinFirmware/Marlin#16504]
### Bug Description

Upon uploading firmware that has been modified to enable dual extrusion, Ender 3 will not boot correctly but gets stuck in a loop, showing the boot screens every 10 seconds.

### Steps to Reproduce

1. Modify bugfix 2.0 to support dual extruders
2. Power on printer to upload firmware
3. Watch it get stuck in boot loop

**Expected behavior:** Printer to turn on normally

**Actual behavior:** Boot loop

[Marlin-bugfix-2.0.x Boot Looper.zip](https://github.com/MarlinFirmware/Marlin/files/4036193/Marlin-bugfix-2.0.x.Boot.Looper.zip)

**Comment by 2kingsrock** [comment]
Can you please check to see if you have a SD card mounted during boot?  I have seen random reboots possibly similar to what you are seeing when I have a SD card mounted on boot on some of my hardware.  I leave the SD cards unmounted now on any Marlin 2.0 builds.

**Comment by sjasonsmith** [comment]
I think @Vertabreak already figured this issue out, I don't know if they posted a PR for it yet.

**Comment by LilJashy** [comment]
I've tried both ways, @2kingsrock. and @sjasonsmith, he's working on my problem right now because the fix he expected to work didn't work

**Comment by Vertabreak** [comment]
just to verify this ender 3 has the following mods a 2 in 2 out hotend & LPC1768 main board with a4988 drivers.
i have looked over the config i don't see any major issues but there are a few things i find suspect.
try enabling #define EEPROM_AUTO_INIT  // Init EEPROM automatically on any errors. see if that helps. 
i was able to fully compile it and noted no issue.

**Comment by LilJashy** [comment]
Ah actually I have TMC2208s - forgot to update that after downloading most recent bugfix. But yes everything else is correct. I'm trying your suggestion now.

**Comment by Vertabreak** [comment]
should correct the driver timing settings and adjust motors directions as needed for tmc.

**Comment by LilJashy** [comment]
You're a wizard, @Vertabreak. That did the trick. Thanks so much!

**Comment by Vertabreak** [comment]
yea i had suspected the bug literally got saved to the eeprom so even after we fixed it you still had issue.

**Comment by thisiskeithb** [comment]
> yea i had suspected the bug literally got saved to the eeprom so even after we fixed it you still had issue.

And `M502`/`M500` couldn't clear it?

**Comment by Vertabreak** [comment]
well he was stuck in a bootloop unable to issue commands at all.

**Comment by LilJashy** [comment]
Where can I find the driver timing settings I need for the tmc2208s?

**Comment by Vertabreak** [comment]
![image](https://user-images.githubusercontent.com/45634861/72019222-4cb8f000-3237-11ea-8f69-e8b682a9a8fe.png)

**Comment by boelle** [comment]
so this one is more or less solved?
