### ISSUE TITLE
[BUG] extruder motor not stopping

### ISSUE THREAD

**Issue by gokulvenkat** [MarlinFirmware/Marlin#16512]
hi everyone i am from india,i am making a multi axis cnc using marlin firmware,where i used arduino mega2560 and ramps1.4 as micro controller and i use marlin1.1.9 version,and the axis setup is like h frame with x axis,y axis,2z axis which uses two motors on z axis,B axis as extruder E0,C axis as extruderE1.The issue which i am facing is the E0 which is B axis keeps rotating if it get energized without any signal coming to the stepper driver  and to avoid cold extrution prevented error i made to tell the marlin that default temperature is 100 and changed the cold extrusion temperature as 60degree in configuration.h,problem happens only if the x and y axis are touching the limit switch,the motor stops rotating if x and y axis are not touching the limit switch ,when i start to mill using x and y axis the B axis suddenly starts rotate with out any need which makes an accident during the operation,i have checked all hardware nothing is casing this problem as of my knowledge but i dont know how step signal pin gets signal due to endstop getting triggered and for more clarification i have enclosed video along with configuration.h,configuration adv.h and pins.h,please find the attachment,thank you for your help in advance

### Steps to Reproduce
 the steps needed to reproduce the issue -->
1.home all axis 
2.move the extruder or engage it using lcd 
3.if x and y axis are clicking the endstop then extruder starts to rotate slowly if extruder is engaged 

**Expected behavior:** [extruder need to rotate some distance and stop]

**Actual behavior:** [it doesnt stops the rotation]

[cnc.zip](https://github.com/MarlinFirmware/Marlin/files/4040057/cnc.zip)

[VID-20200109-WA0000.zip](https://github.com/MarlinFirmware/Marlin/files/4040547/VID-20200109-WA0000.zip)

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
