### ISSUE TITLE
[BUG] MKS Robin Nano, Interface not upscale.

### ISSUE THREAD

**Issue by Yandex-an** [MarlinFirmware/Marlin#16528]
Library(u8g_dev_tft_480x320_upscale_from_128x64.cpp) working correctly in Marlin 2.0.0, and don't working in Marlin 2.0.1.
![IMG_20200108_235123](https://user-images.githubusercontent.com/58883986/72188620-c9042c80-340b-11ea-83a2-f86b19e6f1b8.jpg)

**Comment by boelle** [comment]
use bugfix 2.0.x as that is updated more than 2.0.1

**Comment by Yandex-an** [comment]
Thanks )
