### ISSUE TITLE
[BUG] MarlinSerial::flush()  Duplicate comments

### ISSUE THREAD

**Issue by desmeckert** [MarlinFirmware/Marlin#16526]
NON Critical 

### Bug Description

MarlinSerial.cpp lines 133-136 comments are immediately duplicated
and the comment is completed on line 137-141.

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
My configuration is not relevant.

### Steps to Reproduce
Read the code

No steps needed.

**Expected behavior:** [What you expect to happen]
Minimal download file size.

**Actual behavior:** [What actually happens]
source code bloat/

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
i only see 56 lines in total (https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_LPC1768/MarlinSerial.cpp)

so in which folder ?

**Comment by desmeckert** [comment]
That is MarlinSerial.h.

I said MarlinSerial.cpp.

Easiest is search for the flush() method.

**Comment by desmeckert** [comment]
https://github.com/RichCattell/Marlin/blob/master/MarlinSerial.cpp

Is one version.

**Comment by boelle** [comment]
> That is MarlinSerial.h.

no its not, look at the link clearly say MarlinSerial.cpp

> https://github.com/RichCattell/Marlin/blob/master/MarlinSerial.cpp

that is not main marlin, main marlin links start with https://github.com/MarlinFirmware/Marlin/
