### ISSUE TITLE
AD595  maxtemp bed error

### ISSUE THREAD

**Issue by ta1dr** [MarlinFirmware/Marlin#1654]
Hi All

I use an AD595 circuit and thermocoupler. Also I connected A3 pin on RAMPS and modified the pin number on pin_RAMPS_13….
It works correctly because normally room temperature is 25C, and I see that the extruder and bed temperature are 25C. But the LCD status line says **err: MAXTEMP BED** and the printer doesn't work.

I tested the thermocoupler using a hotair gun and warm bed, increased temperature.

How can I solve this error?

Regards,
Ahmet

**Comment by thinkyhead** [comment]
Potentially related to the MINTEMP error mentioned at #1227. It's possible there's a bug causing the temperature value to get overwritten. Investigating...

**Comment by thinkyhead** [comment]
Try #1660 and see if it helps. It might already be merged into the Development branch by the time you read this.

**Comment by thinkyhead** [comment]
Awaiting feedback on this and testing with the latest code. We've patched up some buffer overruns and other issues that may have been contributing to this behavior.

**Comment by ta1dr** [comment]
yes I tried latest code it is work well  AD595 (early test it )   no any error  .... I tune configuration file (stepper feedrate etc...)  for my printer I will start print asap...
thank all

**Comment by thinkyhead** [comment]
@ta1dr I'm glad to hear it is working well. We'll just leave that code alone for a while, I think.
