### ISSUE TITLE
stm32f103rc own board

### ISSUE THREAD

**Issue by zhubinghan** [MarlinFirmware/Marlin#16575]
I made my own fast board, stm32f103rc. Now I can compile it with the latest Marlin 2.0. The main board is configured as "BOARD_BTT_SKR_MINI_E3_V1_2". And the pin is configured by own board. Download to the board through stlink is Success.But it don't run. Excuse me, do boards need bootloader? If necessary, where can I download this bootloader?

**Comment by ellensp** [comment]
platform_packages = tool-stm32duino
I believe that yes this sets the start of code to where the bootloader would jump to. 
see for details and links to bootloader bin files https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/stm32duino-bootloader

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
