### ISSUE TITLE
[FR] maxtemp chamber drift offset

### ISSUE THREAD

**Issue by maukcc** [MarlinFirmware/Marlin#16586]
All max temps generate an offset to comply to temp drifting, except for the chamber.
so if you set maxtemp for hotend to 200, one can go to 185
if you set maxtemp for bed to 100, one can go to 90

Please also build this for the chamber heater. also 10 degrees.

**Comment by GMagician** [comment]
I posted a PR. chamber offset was 0, 5 or 10 depending on code part. Now I uniformed to 10

**Comment by GMagician** [comment]
Marged..may be closed now

**Comment by maukcc** [comment]
checked and working !
