### ISSUE TITLE
[FR] Unretract speed in linear advance calibration pattern page

### ISSUE THREAD

**Issue by josedpedroso** [MarlinFirmware/Marlin#16594]
### Description

It would be nice to have the possibility to set a separate unretraction speed in http://marlinfw.org/tools/lin_advance/k-factor.html

Currently, the left side of the calibration patterns I print is very faded, especially as the k-factor increases. I incorrectly avoided higher k-factors because of this.

Today, I tried manually replacing 

`G1 E5 F3000 ; un-retract`

with

`G1 E5 F1500`

and the problem was solved, I had no underextrusion in the beginning of the lines, and I correctly determined that a higher k-factor was exactly what I needed.

### Feature Workflow

An input box for the unretraction speed in the page.

**Comment by memphisanid** [comment]
If you change the retract speed to 25, does it do the same thing in the gcode generator?

**Comment by josedpedroso** [comment]
Setting retract speed to 25 does solve the problem, though I get a little bit of stringing between some lines. However, to me, that's not the issue. The problem is that by mindlessly plugging known good values from my slicer into the page, I was getting misleading results. I thought my printer was, for some reason, simply incapable of handling higher k-factors. It's just an Anet A8, after all.
