### ISSUE TITLE
[BUG] AUTO_BED_LEVELING_BILINEAR PROBE_MANUALLY crashes after last point

### ISSUE THREAD

**Issue by Golkun** [MarlinFirmware/Marlin#16590]
### Bug Description

AUTO_BED_LEVELING_BILINEAR PROBE_MANUALLY crashes after last point

### My Configurations
Marlin 2.0.1 from 24.12.2019
corexy
inductive probe on redefined Z_MIN_PIN P2_00
TMC2208 UART for xyze

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
Marlin.config.zip attached
Video
[20200117_171546_97394802255645.zip] 
(https://github.com/MarlinFirmware/Marlin/files/4077690/20200117_171546_97394802255645.zip)

### Steps to Reproduce
1. Select Auto Bed Leveling from the LCD menu
2. go through the points manually
3. after last point has been finished a click on the encoder forces a reset

**Expected behavior:** no reset and values recorded to be stored in eeprom

**Actual behavior:** a reset occurs, not able to finish auto bed leveling.

[Marlin config.zip](https://github.com/MarlinFirmware/Marlin/files/4077657/Marlin.config.zip)

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by boelle** [comment]
is it the same in bugfix 2.0.x ? that is newer than 2.0.1

**Comment by Golkun** [comment]
Will try bugfix 2.0.x

**Comment by Golkun** [comment]
can I use configuration.h and configuration_adv.h from my current build?

**Comment by boelle** [comment]
not sure, best is to compare them with a tool like winmerge

**Comment by Golkun** [comment]
Btw Winmerge is a great tool.
Unfortunately the behaviour is still the same with Bugfix 2.0.x

Checked also with PROBE_MANUALLY disabled and there it works without issues.

**Comment by boelle** [comment]
how often do you update? bugfix is updated almost daily

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
