### ISSUE TITLE
[BUG] Manual bed leveling stops after homing

### ISSUE THREAD

**Issue by Vladimir-VS** [MarlinFirmware/Marlin#16614]
### Bug Description
The issue https://github.com/MarlinFirmware/Marlin/issues/13181 still exists. I have the same behavior of my Tevo Tarantula with an optical z-min endstop.
I tend to blame it on the is_homed valued erroneously false in the menu_bed_leveling.cpp.
A root cause my be in a logic set for the endstops:
#define X_MIN_ENDSTOP_INVERTING true
#define Y_MIN_ENDSTOP_INVERTING true
#define Z_MIN_ENDSTOP_INVERTING false
but clearly do not have a solution. All other homing works fine.
Leveling from g-code (repetiere-host) works fine.

### My Configurations
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4087240/Configuration.zip)

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by Vladimir-VS** [comment]
Added to the original comment.

**Comment by boelle** [comment]
@Vladimir-VS please retest with bugfix 2.0.x from here https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

**Comment by Vladimir-VS** [comment]
Thank you. Will do at the nearest possibility. 21.01.2020, 18:57, "Bo Herrmannsen" <notifications@github.com>:@Vladimir-VS please retest with bugfix 2.0.x from here https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by boelle** [comment]
closing this since its a dublicate of #13591

we only need one open for the same issue
