### ISSUE TITLE
[BUG] PID work not ok

### ISSUE THREAD

**Issue by userosos** [MarlinFirmware/Marlin#16626]
Marlin after PID autotune not set to target Temperature extruder. See the pic please!
Log from repetier-server. Mks gen L.
Heater for 12V. power supply is 24V. #define BANG_MAX 70
[Marlin-2.0.1.zip](https://github.com/MarlinFirmware/Marlin/files/4087529/Marlin-2.0.1.zip)
[Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/4087530/Marlin-bugfix-2.0.x.zip)
Marlin 2.0.1 or Bugfix2.0.x
![изображение](https://user-images.githubusercontent.com/22872748/72751154-d8cffd80-3bcf-11ea-8bd6-a6144ec89729.png)

**Comment by userosos** [comment]
I think thah it was problem with connector from termistor of the hotend.

**Comment by boelle** [comment]
closing as it was a connector issue
