### ISSUE TITLE
[BUG] BLTouch/3D touch help with mks base v1.4 board

### ISSUE THREAD

**Issue by bentech4u** [MarlinFirmware/Marlin#16623]
After some software changes the behavior changed

M280 P0 S10 : pin goes down : m119 shows open

M280 P0 S90: pin goes in : m119 shows triggered

, but when i try to home all, after touching bed also z axis is moving down and it is stopping only when the 3dtouch goes into alarm state

[https://vimeo.com/user32803137/review/385998054/629786ec31](url)

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by bentech4u** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4088955/Marlin.zip)
here i am attaching configurations

**Comment by bentech4u** [comment]
here is the video of issue:
https://youtu.be/ag9lLKpG58s

**Comment by boelle** [comment]
the config does not match current bugfix 2.0.x

where did you download marlin from?

**Comment by Vertabreak** [comment]
the following does not work with 3dtouch probes.
```cpp
#define BLTOUCH_FORCE_SW_MODE
```
this line also has no effect on 3dtouchs.
```cpp
#define BLTOUCH_SET_5V_MODE
```

**Comment by yet-another-average-joe** [comment]
@bentech4u It seems your probe is mounted a bit too low. (hard to say on the video) I have also been using a 3DTouch (the black one), and it sometines drops the pin 2 times insteed of one. It behaved weirdly (and had poor repeatability)
Also, there could be some EMI with the heaters ; maybe you could try PROBING_HEATERS_OFF

**Comment by Vertabreak** [comment]
EMI is [definitely an] issue on all the GT2560 boards. [T]here are several options that can help deal with it.

**Comment by boelle** [comment]
since we have not gotten any word from the OP we must either assume he solved his problem or that he have given up

will close this one and we can reopen if OP returns
