### ISSUE TITLE
[BUG] Auto Level sets z home ~1mm below true home

### ISSUE THREAD

**Issue by jdelpero** [MarlinFirmware/Marlin#16634]
### Bug Description
After an auto home (g28) z home is correct and nozzle is ~0.1mm above bed when z is at 0. After an auto level routine (g29) z home is no longer correct and is at approx. -1.0mm below the original home point. Tested with both 3 Point & Bi-linear bed leveling options, both with the same result.
* If i skip auto level routine and simply print, I get a perfect first layer.
* Bed is glass and pre-heated before homing.

### My Configurations
**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4090945/Marlin.zip)

### Steps to Reproduce

1. Pre-heat for PLA
2. Run Auto Home, move nozzle to probe point and check z=0 is correct (paper test etc.)
3. Run Auto Level, move nozzle to auto home probe point and check z which is no longer correct and is now at -1mm (z home has moved below the bed and nozzle is pressing the bed down.)

**Expected behavior:** [What you expect to happen]
G29 auto levels bed and honours z probe offset

**Actual behavior:** [What actually happens]
G29 increases z probe offset by ~1mm

#### Additional Information
Bed Mesh Results (g29)
      0      1      2
 0 -1.058 -0.968 -0.797
 1 -1.085 -1.032 -0.871
 2 -1.111 -1.108 -0.961

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by reloxx13** [comment]
duplicate
https://github.com/MarlinFirmware/Marlin/issues/15450

**Comment by boelle** [comment]
closing since this is a dublicate of #15450

@jdelpero we only need one issue open for each issue
