### ISSUE TITLE
[BUG] Errors compiling 21 Jan bugfix (E6, E7extruders and "(" )

### ISSUE THREAD

**Issue by Liger0** [MarlinFirmware/Marlin#16642]
### Bug Description
Errors in extruder and missing binary operator prevent build

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4094188/Marlin.zip)

### Steps to Reproduce

1. default_envs= LPC1768
2. Use 2 extruders

**Expected behavior:** No error

**Actual behavior:** 2 different type of errors.

#### Additional Information
If I manually delete the part of code

```
 #if AXIS_IS_TMC(E6)
    #define E6_CURRENT      800
    #define E6_MICROSTEPS    16
    #define E6_RSENSE         0.11
    #define E6_CHAIN_POS     -1
  #endif

  #if AXIS_IS_TMC(E7)
    #define E7_CURRENT      800
    #define E7_MICROSTEPS    16
    #define E7_RSENSE         0.11
    #define E7_CHAIN_POS     -1
  #endif
```

it builds fine and only shows the, I believe already known, 2 issues:

```
{
	"resource": "/d:/Marlin-bugfix-2.0.x. 21 Jan 2020/.pio/libdeps/LPC1768/U8glib-HAL_ID1932/src/clib/u8g_com_i2c.c",
	"owner": "cpp",
	"severity": 4,
	"message": "'u8g_i2c_opt' defined but not used [-Wunused-variable]",
	"startLineNumber": 44,
	"startColumn": 16,
	"endLineNumber": 44,
	"endColumn": 16
}

```

```
{
	"resource": "/d:/Marlin-bugfix-2.0.x. 21 Jan 2020/Marlin/src/lcd/menu/menu_filament.cpp",
	"owner": "cpp",
	"severity": 4,
	"message": "'sprintf' may write a terminating nul past the end of the destination [-Wformat-overflow=]",
	"startLineNumber": 123,
	"startColumn": 33,
	"endLineNumber": 123,
	"endColumn": 33
}
```
![E6 E7 token](https://user-images.githubusercontent.com/20385116/72851161-2ff6d080-3cab-11ea-9b22-782ede42d99f.png)

**Comment by InsanityAutomation** [comment]
Remove reference to e6 and e7 blocks in config adv and it'll compile. Config had pending options again.
