### ISSUE TITLE
[BUG] (G29 works but printer prints in air)

### ISSUE THREAD

**Issue by rcMarty** [MarlinFirmware/Marlin#16651]
### Bug Description

So in start gcode I have 
```
G28
G29
G1 E3.0
M112 Printing...
```

and after that printer prints about 5mm ower the bed
I have Marlin 2.0

Can anybody help me with that?

And sorry if there was something like this.
### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4098380/Marlin.zip)

**Comment by reloxx13** [comment]
duplicate
https://github.com/MarlinFirmware/Marlin/issues/15450

**Comment by flankerzo** [comment]
i was having same issue, in marlin  2.0 (januar '20) and 1.9 too,  every time helped to reduce Z - (minus) offset in both firmware and slicer.

**Comment by boelle** [comment]
closing since this is a dublicate of #15450

@RCGe0rge we only need one of each issue
