### ISSUE TITLE
[BUG] Marlin 2.0.1 stuck at bootscreen when SD card removed

### ISSUE THREAD

**Issue by Thijsvanzwam** [MarlinFirmware/Marlin#16661]
When powering on my Anet A6 printer, running Marlin 2.0.1 on the Anet v1.7 mainboard with optiboot bootloader, the system halts at the bootscreen and with a running fan at 100%. (it powers up the fan shortly at startup but it gets stuck at that point.)
It only happens when the sd-card is removed. Starting up with a sd-card inserted, no problems at all.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
also remember to use bugfix 2.0.x as 2.0.1 is a frozen copy of 2.0.x

**Comment by Thijsvanzwam** [comment]
here are my config files, sorry read all over it in the issue template.

I can replicate the bug each time by just powering on the printer with the sd card removed, when i reset the printer and put in the card, it powers on normally. When i insert the card at the moment it is stuck, it sometimes starts normal in a few second and sometimes it does not start up at all, remaining stuck at the bootscreen. Then i have to reset the printer and all is normal again. 

[config files.zip](https://github.com/MarlinFirmware/Marlin/files/4107132/config.files.zip)

**Comment by houseofbugs** [comment]
Sounds like a bad SD card. Have you tried another to rule out issues with the card itself?

**Comment by ManuelMcLure** [comment]
Uhhh... he reports that he sees a problem when he _doesn’t_ have an SD card inserted. I don’t see how a bad SD card would cause that.

**Comment by Thijsvanzwam** [comment]
SD card is fine, i use several sd cards and the problem only occurs when there is no card inserted.

**Comment by boelle** [comment]
my printer boots fine with no sd card inserted in the lcd
but then i have a re-arm with an sd card inserted so i have 2 options for sd card

@Thijsvanzwam did you try with bugfix 2.0.x or only 2.0.1?

**Comment by Thijsvanzwam** [comment]
tried only 2.0.1
Will try bug fix this week

**Comment by boelle** [comment]
2.0.2 and bugfix are broken right now so hold off for maybe a week or 2

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by thinkyhead** [comment]
And the SD detect pin is in good working order…? It is a mysterious one. If something at startup takes too long, Marlin will usually just restart rather than hang.

**Comment by Thijsvanzwam** [comment]
tried 2.0.3, same issue.
back to 1.1.9 no problems at all

**Comment by thinkyhead** [comment]
We can try staring at the code, but truly that never works. Can you try some experiments with various SD-related settings and see if something changes? Maybe you'll discover some weird interaction with another enabled feature that, when disabled, fixes the issue.
