### ISSUE TITLE
[BUG] Sudden temprature drops while printing

### ISSUE THREAD

**Issue by opiswahn** [MarlinFirmware/Marlin#16683]
### Bug Description

Since today, i got some wired temp drops on the hotend while printing, not time related
![image](https://user-images.githubusercontent.com/5494461/73140572-af551d00-407a-11ea-8b83-30977250bf43.png)
That is a scale from about 30min. Sometimes the drops happen after 5min, sometimes after 20min or later, also regardless of model that was printed.
I am using the **current bugfix-2.0.x** from today, my older version that worked was from around 15 days ago.
It has nothing to do with part cooling fan turning on, that one is running since 2nd layer.

The temp is pretty stable until it drops, max 1-2 degrees delta in a very short timespan(1-5 sec). Those sudden spikes down last for some 30sec-1min, until my runaway-protection kicks in.

I never had something like this before, some little dropy yes, but not on that scale...

I had done PID tuning some time ago, that always worked perfectly. After the first occurrence i tried it again several times, the values doesn't change much and the issue also persists,,,

I am not able to finish any prints, please help!

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4114310/Marlin.zip)

### Steps to Reproduce

1. Print
2. Wait for temp drops.

**Comment by GMagician** [comment]
Check the cable. I had some issue like that and was bed cable broken, you can check it with a voltmeter.

**Comment by opiswahn** [comment]
Cable is fine, a already checked that.

**Comment by boelle** [comment]
bad thermistor maybe, or close to going bad

**Comment by yet-another-average-joe** [comment]
I had the exact same issue with a genuine brand new E3D V6 hotend, because of the thermistor connector ; the connector itself was fine, but they do crimp the terminal pins to the thermistor solid wires. This is nonsense, crimping is for stranded wires, never for solid wires. As a result, I had intermittent contact, and from time to time thermal runaway errors. The thermistor being a safety device, I replaced it with another one, and connected its 1 meter wires directly to the motherboard.

So, if you have such a connector near to the thermistor, have a look to it...

Where I live, crimping ferrules on solid wires is prohibited.

**Comment by thinkyhead** [comment]
Marlin is trusting what the sensors tell it and applying PID in classic manner. Marlin is not trying to be too clever, and certainly it is not trying to be clever by turning off the heaters. I've been doing multi-hour prints on several machines with recent and current Marlin 2.0.x and we have not seen any issues with the firmware deciding to stop heating.

**Comment by yet-another-average-joe** [comment]
> 
> 
> ... Marlin is not trying to be too clever, and certainly it is not trying to be clever by turning off the heaters...
>

@thinkyhead , I don't understand...
Attempting to heat the hotend without the thermistor, gives "Exx heating failed" error (heater does not turn on), and Marlin stops, turning the heaters off ; if the temp reported by the thermistor drops too much, too long, or is too unstable (or if the sensor is disconnected too long while heating), it does the same (thermal runaway error + turns off the heaters). Marlin is clever and safe !

**Comment by OscarGciam** [comment]
Same problem with the same board (SKR 1.3) over here with Marlin 2.0.1

**Comment by boelle** [comment]
marlin 2.0.1 is not the newest, use bugfix 2.0.x

**Comment by boelle** [comment]
> Cable is fine, a already checked that.

also check the strands are not broken inside the cable

**Comment by italocjs** [comment]
I'll leave one printer with a new e3d (which has never seen plastic) hot tomorrow for a few hours to help testing this, i have printed a a piece (around 3 hours) with today today's bugfix and didn't notice any issue on the printed part.

**Comment by italocjs** [comment]
i had no issues so far, as said in the previous comment i burned yesterday bugfix, did the pid autotune and turned the hotend on (without any plastic inside) for around 4 hours, there were no spikes or drops in the temperature (using 260C - cloned e3dv6, 100k ntc termistor).  Try checking you thermistor and heat cartridge cables and retuning the pid,  if the PSU or the voltage regulator (in the controller board) are not being able to keep the voltage steady you can see these issues too.

**Comment by opiswahn** [comment]
I'll try to replace the temp probe and heating cartridge this weekend(together with cables) and see if that has any effekt.

**Comment by opiswahn** [comment]
I don't think it is the thermistor, if that would malefunction, the temp would go to 0 and back and not gradually drop.

**Comment by italocjs** [comment]
About the termistor, it doesn't have to fully short or break the connection, just enough to mess with the resistance. I've switched a few thermistor so far, all reporting weird temperatures

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by houseofbugs** [comment]
Cannot replicate on any versions of Marlin. This is a hardware issue, not a Marlin bug. Could be your board or the thermistor (wiring included). Replace the thermistor and associated wiring. If that doesnt show any change then swap the control board.

**Comment by boelle** [comment]
will close this one for the reasons @houseofbugs just mentioned

we can always reopen if needed
