### ISSUE TITLE
Least Squares Best Fit Algorithm (for ABL) Should Be Shrunk 

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#1671]
Feature Request:

People are complaining about  Auto Bed Leveling taking too much code space.  The bulk of the bloat happens when you turn on the Grid Based Auto Bed Leveling because it pulls in a Least Squares Best Fit library.   

I suggest when there is nothing more urgent, we take a look at rewriting that functionality and shrink it down.  I suspect we can free up 10Kb of code space without really trying too hard.  (The current Least Squares Best Fit code solves for the general case.  We don't need to do that!)

**Comment by nophead** [comment]
What is the special case optimisation you have in mind?

**Comment by Roxy-3D** [comment]
I'm not sure...   But a simple (and small) iterative search solution probably can be done very fast and accurately.   I'm going to toy with that direction soon if somebody does not have a better idea.

**Comment by Roxy-3D** [comment]
Just a quick note...  Progress is being made and the code size can be shrunk significantly!

**Comment by nophead** [comment]
Good work. Did you resolve why the d value from qr_solve doesn't lie between the probed values?

**Comment by Roxy-3D** [comment]
> Good work. Did you resolve why the d value from qr_solve doesn't lie between the probed values?

Not yet.   That really does not make sense to me.   And that only happens if you have the bed really unlevel.   But with that said, I can get the same exact numbers that QR_SOLVE gets, so it may make sense to link it into my Marlin and start using it for my own prints to confirm 'correctness'.    

I'm debating how to proceed.   One option would be to (Gasp!!!!) add a #define to control whether Marlin_Main.CPP pulls in QR_SOLVE or the much shrunk piece of code.  It would not be difficult to make the calling convention identical.  Over time...  Once it is known that things are working correctly that could be pulled out.  But in the mean time, people without a need for the smaller code footprint could keep using the larger and more proven code.

With that said...  The code would be simpler and smaller if we just passed the new code an array of points instead of the convoluted matrix setup that QR_SOLVE needs.   I might just do this as a first step.

**Comment by nophead** [comment]
Well it won't be correct until the plane equations is used to calculate the Z offset and that requires the d issue to be resolved.

**Comment by Roxy-3D** [comment]
> Well it won't be correct until the plane equations is used to calculate the Z offset and that requires the d issue to be resolved.

I agree...   And I'm working on that.   

UPDATE:   The issue is understood.   The 'problem' has to do with the distance between where the probe is located on the nozzle and the origin.   If the bed is tilted at an extreme enough angle, it is possible that when you extrapolate to the origin, the 'd' coefficient is outside of the Z values that were sampled.  Both pieces of code are doing the right thing and returning correct numbers.

The AVR microprocessor is -SLOW- !!!  I spent a couple of hours optimizing the code to speed things up as much as possible.   Right now, the code has the same calling convention as QR_SOLVE.CPP so it is possible to just include one file or the other.    If the iterative solution is #include'd it will return the same values to 3+ digits of precision that QR_SOLVE returns.  It can solve a 25 (5x5) grid in well under 5 seconds.   Smaller grids are solved proportionally faster.

Because Aruduino does not really have double precision floating point (it is the same as the normal float type), it is not going to be possible to get more than 3+ digits of precision.  3+ digits of precision prints perfectly fine!  The problem is a lot of precision is lost with the additions and subtractions and with 32 bit floats, you start losing information very quickly as you do the additions and subtraction on ax+by+cz+d=0 .

Enabling the code so that QR_SOLVE.CPP does not have to be included saves almost exactly 10 Kb of firmware space.   My suggestion is we add a single #define in Configuration.h to control which file is pulled in if Auto Bed Leveling is enabled.   Probably the initial default should be with the iterative solution turned off so the more proven QR_SOLVE code base is normally used but people that need to shrink their code size can pull in the experimental iterative solution.   Right now I'm fighting GitHub.   I forked, and cloned the current file set.   But then I got clever and decided to delete the folder where I put it so I could redo it in a better place in my file system.  GitHub won't let me clone it again????      Aaaarghhhhh!!!!!

**Comment by nophead** [comment]
Ah, I see. My origin is in the middle of the bed so the probe points always straddle it. I hadn't realised they might not when the origin is in the corner and probe offset precludes getting to that corner.

**Comment by Roxy-3D** [comment]
Well, the good news is we were worried about something that is not an issue!  At least it is understood and not causing confusion any more!    :)

**Comment by Roxy-3D** [comment]
A quick question for those that understand the Arduino compiler.    What is the right way to make this code drop in with minimal code changes?   I don't think I can have the exact same name and calling convention because Arduino will compile both modules and try to pull them both in.

Do we have to use different names for the function that does the work so only one module gets pulled in?

**Comment by alexborro** [comment]
I think the easiest way is using #ifdefs.

You choose what code to compile.

Cheers

Alex
Em 02/04/2015 11:57, "Roxy-3DPrintBoard" notifications@github.com
escreveu:

**Comment by thinkyhead** [comment]
@Roxy-3DPrintBoard Definitely **#ifdef** conditional blocks. Either include the old-style qr_solve code, or include your code. It can be structured just the same way, if the calling conventions are good as they are, or use whatever makes sense, then conditionalize the calling code also.

**Comment by Roxy-3D** [comment]
> @Roxy-3DPrintBoard Definitely #ifdef conditional blocks. Either include the old-style qr_solve code, or include your code. It can be structured just the same way, if the calling conventions are good as they are, or use whatever makes sense, then conditionalize the calling code also.

OK!  That is easy enough to do.  Its just that a lot of work has been done to remove those #ifdef's so I was hoping to not clutter things up.   Probably the thing to do is leave Marlin_main.cpp alone and just put an #ifndef #else to turn on the original contents of QR_SOLVE.cpp or the (small) iterative code tacked on the bottom of it.  That would leave the main line code alone.  The one downside is we would be altering the QR_SOLVE.cpp file from its original state.

**Comment by alexborro** [comment]
I prefer tweaking the qr_solve.cpp than marlin_main.cpp. 

The qr_solver is suppose to have such algorithms, so no matter one or two versions. You can use a #define in configuration.h to choose which version... it makes the test and debugging easier.

Cheers.

Alex.

**Comment by thinkyhead** [comment]
I agree with @alexborro on placement.

I'm almost inclined to see things like the alternative `gcode_G29` function that comes with `MESH_BED_LEVELING` move into the `mesh_bed_leveling.*` files since that would work… but then actually I wouldn't mind splitting out _all the GCode handlers_ into a separate `gcode.cpp` / `gcode.h` unit first, and then perhaps splitting up the GCode by category. What will be left in `Marlin_main.cpp` without the GCode handling? Probably still a lot…

**Comment by Roxy-3D** [comment]
> I'm almost inclined to see....

Agreed...  Marlin_main.cpp would still be longer than it should be.

And most certainly agreed on Mesh stuff being a separate file!

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
