### ISSUE TITLE
[FR] Define 'custom' board type to manage number of build environments in platformio.ini

### ISSUE THREAD

**Issue by jmz52** [MarlinFirmware/Marlin#16732]
### Description

Create 'plug-able' build environment.
Define 'custom' board type and use it in 'plugged' build environment.

### Feature Workflow

1. Add `extra_configs = extra_config.ini` line to `[platformio]` section of platformio.ini
2. Define `BOARD_CUSTOM` in boards.h
`#define BOARD_CUSTOM                  9998`
and associate pins file with it in pins.h file
`#elif MB(CUSTOM)  #include "pins_custom.h"`
3. User copies Configuration.h, Configuration_adv.h and pins_custom.h to Marlin directory and
extra_config.ini to top directory (next to platformio.ini)
Configuration.h has `#define MOTHERBOARD BOARD_CUSTOM` in it.
4. User build Marlin Firmware and PlatformIO uses build environment configuration from extra_config.ini file

Working example of extra_config.ini file.
Overrides default build environment for 1 click builds.
```
[platformio]
default_envs = some_delta_stm32

[env:some_delta_stm32]
platform          = ststm32
board             = genericSTM32F103RC
platform_packages = tool-stm32duino
build_flags       = !python Marlin/src/HAL/HAL_STM32F1/build_flags.py
  ${common.build_flags} -DDEBUG_LEVEL=0 -std=gnu++14 -DSS_TIMER=4
build_unflags     = -std=gnu++11
src_filter        = ${common.default_src_filter} +<src/HAL/HAL_STM32F1>
lib_deps          = ${common.lib_deps}
lib_ignore        = Adafruit NeoPixel, SPI
```

#### Additional Information

Custom pins files and bulid environment configurations can be stored in MarlinFirmware/Configurations repository along with Configuration.h and Configuration_adv.h files.

https://github.com/MarlinFirmware/Marlin/issues/14847
https://github.com/MarlinFirmware/Marlin/issues/15936

**Comment by bjoernwedi** [comment]
looks similar to my request https://github.com/MarlinFirmware/Marlin/issues/17971

Furthermore be would be able to build easier extendable patterns by using more platformio attributes to configure environments without repetitions and without the need of python scripts like for all the SKR baord in the manner of:
```
`[env:STM32F103RC_btt_512K]
platform                    = ststm32@>=6.1.0 #to support board_build.ldscript
platform_packages           = tool-stm32duino
board                       = genericSTM32F103RC
board_build.ldscript        = $PROJECT_DIR/buildroot/share/PlatformIO/ldscripts/STM32F103RC_SKR_MINI_512K.ld # to make the .py unnecessary
board_build.extra_flags     = -DDEBUG_LEVEL=0 -DHAVE_SW_SERIAL -DSS_TIMER=4 # to seperate board cpu params clearly
board_upload.offset_address = 0x08070000 # to make the .py file obsolete
board_upload.maximum_size   = 524288
build_flags                 = !python Marlin/src/HAL/STM32F1/build_flags.py
  ${common.build_flags}
src_filter                  = ${common.default_src_filter} +<src/HAL/STM32F1> #is this necessary, becuasde it is in Marlin/src/HAL/STM32F1/build_flags.py: -IMarlin/src/HAL/STM32F1
lib_deps                    = ${common.lib_deps}
  SoftwareSerialM=https://github.com/FYSETC/SoftwareSerialM/archive/master.zip
lib_ignore                  = Adafruit NeoPixel, SPI
monitor_speed               = 115200

[env:STM32F103RC_btt_512K_USB]
extends         = env:STM32F103RC_btt_512K
src_build_flags = -DUSE_USB_COMPOSITE` # t osimply extend these additional attributes instead of overriding the default build_flags all the time
```
NOTE: I changed also the HAL/STM32F1/build_flags.py to gnu++14, because just one board had gnu++11, so I changed the default to make all the build_unflags unnecessary

That makes it more easy to build compositess including dependencies to the default configuration examples of the preters.
