### ISSUE TITLE
[BUG] Probing stops without completing

### ISSUE THREAD

**Issue by yoc1983** [MarlinFirmware/Marlin#16734]
After adding bltouch there's a weired problem,
everything seems to work but..
running G29 the prob will test 6 point and then stop (for 3x3 mesh)

**Steps to Reproduce**
running G29 V1

**Actual behavior: [What actually happens]**
 probing as it should, i see in terminal the prob numbering 1/9, 2/9 ... then 7/9
but everything is stopping in the 6th position.

**Additional Information**
ender 3 pro, skr 1.3, bltouch 3.0 original, marlin-bugfix-2.0.x
configured it to do a 3x3 mesh 
configured bed size 235x235

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by yoc1983** [comment]
@boelle thanks mate here it is:
[joe-config.zip](https://github.com/MarlinFirmware/Marlin/files/4136909/joe-config.zip)

**Comment by opiswahn** [comment]
I had that once... try disabling Bilinear_Subdivision, that helped me

**Comment by yoc1983** [comment]
@opiswahn 
tried now, i enabled linear instead.. same thing stopping after the 6th point
also looks like he didn't saved the values
![image](https://user-images.githubusercontent.com/60488606/73553930-77bbeb80-4453-11ea-99fd-65bd6b16908f.png)
this is running M420 after bilinear:
![image](https://user-images.githubusercontent.com/60488606/73553972-8904f800-4453-11ea-915d-0b29961c838d.png)

**Comment by yoc1983** [comment]
OK i gave a manual direction and finally managed to sample the all 3x3 
G29 X3 Y3 L50 R150 F50 B150 T V4
![image](https://user-images.githubusercontent.com/60488606/73554617-bdc57f00-4454-11ea-9082-b5b15f0e4475.png)
that's nice..see how i go from here thanks @opiswahn

**Comment by sjasonsmith** [comment]
Can you verify the approximate date of the bugfix-2.0.x code you are using. Is it code you just downloaded, or something older. There were a lot of issues like this a month or so ago that were resolved, so I want to find out if this is possibly those same issues.

**Comment by yoc1983** [comment]
@sjasonsmith OMG.. bless you Jason
there was a human bug
i used the reconfigured marlin from here:
https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3
guess it was not updated
i downloaded now a fresh copy of marlin and configured everything
and it's working perfectly.
sorry for the trouble guys i am a beginner with this. 
thanks for the help

**Comment by boelle** [comment]
@yoc1983 so we can close this one?

**Comment by yoc1983** [comment]
@boelle 
yes. this bug was fixed
thanks
