### ISSUE TITLE
[BUG] Compile error when disabling CURRENT_STEP_DOWN

### ISSUE THREAD

**Issue by Brassn** [MarlinFirmware/Marlin#16742]
### Bug Description

I am getting compile errors since f6a6839a82312f05efbd39acc3bbbd92b990e8a5 when disabling the current stepdown on TMC ot prewarn by commenting out CURRENT_STEP_DOWN in Configuration_adv.h with MONITOR_DRIVER_STATUS enabled.
step_current_down gets called although it won't be defined.
This problem probably exists since 27943f9e31a4c16d981e437447f143972c92f835 but now also reveals itself when not using multiple drivers on a single axis (X1, X2, ...).

```
Compiling .pio\build\megaatmega2560\src\src\feature\tmc_util.cpp.o
Marlin\src\feature\tmc_util.cpp: In function 'void monitor_tmc_drivers()':
Marlin\src\feature\tmc_util.cpp:361:39: error: 'step_current_down' was not declared in this scope
             step_current_down(stepperX);
                                       ^
Marlin\src\feature\tmc_util.cpp:381:39: error: 'step_current_down' was not declared in this scope
             step_current_down(stepperY);
                                       ^
Marlin\src\feature\tmc_util.cpp:407:39: error: 'step_current_down' was not declared in this scope
             step_current_down(stepperZ);
                                       ^
*** [.pio\build\megaatmega2560\src\src\feature\tmc_util.cpp.o] Error 1
```

### My Configurations

I only changed the necessary lines to trigger the error.
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/4139920/Config.zip)

#### Additional Information

A quick fix would be to define step_current_down as an empty function in tmc_util.cpp at line 283.
```
  #else
    template<typename TMC>
    void step_current_down(TMC &st) {
    }
```

**Comment by thinkyhead** [comment]
Thanks! This is now patched.
