### ISSUE TITLE
[BUG + FIX] compiling issue from 2.0.1 to 2.0.3 ftdi EVE

### ISSUE THREAD

**Issue by TB1405** [MarlinFirmware/Marlin#16761]
Compiling isnt possible with #define EXTENSIBLE_UI. 
With the version 2.0.0 and the TouchUI folder from fysetc it was possible to compile successfully and the display works.

EDIT 03.feb.2020
We dont need to adapt the fysetc TouchUI folder only need to add

#undef max
#define max(a,b) ((a)>(b)?(a):(b))
#undef min
#define min(a,b) ((a)<(b)?(a):(b))
`

in the compat.h file in the the touchUI folder under the line `#include "pin_mappings.h"`

i made also some changes in the menu. 
1.  i added the preheat feature in the temperature screen. 

2. changed the `stepper_bump_sensitvity_screen` to `TMC_Stepper_Screen`
here it is also possible to change the hybridthreeshold value from tmc drivers

i wasnt able to create a pullRequest but here is the changed folder.
Maybe we could add this 

[PREHEAT+TMCDriverSucces2.0.3.zip](https://github.com/MarlinFirmware/Marlin/files/4148654/PREHEAT%2BTMCDriverSucces2.0.3.zip)

**Comment by TB1405** [comment]
alright was a problem of the old Fysetc libary. 
We only need to add
  `

-   #undef max
-   #define max(a,b) ((a)>(b)?(a):(b))
-   #undef min
-   #define min(a,b) ((a)<(b)?(a):(b))

`

in the compat.h file in the the touchUI folder under the line `#include "pin_mappings.h"`

**Comment by boelle** [comment]
@TB1405 if you have the skills then a PR is the fastest way to get it fixed

@thinkyhead does the proposed fix make any sense?

**Comment by TB1405** [comment]
GerogeFu  has started a pull request. 
Fix is included here 
https://github.com/MarlinFirmware/Marlin/pull/16830/commits/7cef4f52a94f57b4f8e88cb4a95d55a7235aa59c

**Comment by TB1405** [comment]
Should work now for stm32
