### ISSUE TITLE
[BUG] ADVANCED_PAUSE_FEATURE + Power_loss_recovery

### ISSUE THREAD

**Issue by spooky79** [MarlinFirmware/Marlin#16763]
After parking the nozzle, turn off the power. After resuming power and resume printing, the nozzle returns to X and Y  position but does not lower to the previous position Z only prints in the air . 

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/4144245/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/4144246/Configuration_adv.txt)

**Comment by Mysel07** [comment]
Yes, the printer then prints in the air. The problem is that in function NOZZLE_PARK_FEATURE (Configuration.h). In NOZZLE_DEFINE_POINT is value for Z raise (10). Function POWER_LOSS_RECOVERY save actual position Z + Z raise value.
