### ISSUE TITLE
[BUG] No EEPROM suddenly!

### ISSUE THREAD

**Issue by karabas2011** [MarlinFirmware/Marlin#16768]
### Bug Description

 MARLIN 2.0.x snapshot 30.01.2020
SKR 1.1pro  -  TMC2208 UART

M500 returns "no EEPROM"
But EEPROM enabled in config
M115 returns EEPROM:1

### My Configurations
Cartesian IDEX extruders 

**Required:** Please in

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4147072/Marlin.zip)

clude a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
```
>>> M500
SENDING:M500
echo:No EEPROM.
^^^^^^^^^^^^^^^^^
>>> M115
SENDING:M115
FIRMWARE_NAME:Marlin 2.0.3 (GitHub) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3DQ One Dual EXTRUDER_COUNT:2 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Cap:SERIAL_XON_XOFF:0
Cap:BINARY_FILE_TRANSFER:0
Cap:EEPROM:1
^^^^^^^^^^^^^^^^^^^
Cap:VOLUMETRIC:1
Cap:AUTOREPORT_TEMP:1
Cap:PROGRESS:0
Cap:PRINT_JOB:1
Cap:AUTOLEVEL:0
Cap:Z_PROBE:0
Cap:LEVELING_DATA:1
Cap:BUILD_PERCENT:0
Cap:SOFTWARE_POWER:0
Cap:TOGGLE_LIGHTS:0
Cap:CASE_LIGHT_BRIGHTNESS:0
Cap:EMERGENCY_PARSER:0
Cap:PROMPT_SUPPORT:0
Cap:AUTOREPORT_SD_STATUS:0
Cap:THERMAL_PROTECTION:1
Cap:MOTION_MODES:0
Cap:CHAMBER_TEMPERATURE:0
```

**Comment by italocjs** [comment]
i'm not sure if this will help, but i had some really weird issues caused by corrupted eeprom data, i fixed it by running a simple arduino program to set all eeprom bits to zero, and then burning the firmware again.  (there is a sketch inside arduino examples if i'm not mistaken)

**Comment by karabas2011** [comment]
It works for arduino, but not for STM32F4
If I use older version all works. But I need fixes for manual mesh leveling

**Comment by italocjs** [comment]
I see, it might be something in this version, unfortunately i dont have this board, so i cant help much on looking out this issue.

**Comment by spattinson** [comment]
eeprom is sd card on this board. I had this earlier today with my skr pro. I defaulted my settings then couldn't save any new ones.  a reformat, a reboot fixed plus a few M501 M502 M500 then M503 to view them. For now I am sticking to 8.3 filenames for gcode files idk what the cause is. It may be worth doing a filesystem check (scan  for errors or fsck on  linux)

**Comment by karabas2011** [comment]
Very strange! It save a file to LCD sdcard. 
So the eeprom emulation is changed to sdcard-emulation?
Why?
How to turn on normal eeprom as it was (f.e.) 31/11/2019 snapshot?

**Comment by thinkyhead** [comment]
Check out the pins file.
```cpp
// Use one of these or SDCard-based Emulation will be used
//#define SRAM_EEPROM_EMULATION   // Use BackSRAM-based EEPROM emulation
//#define FLASH_EEPROM_EMULATION  // Use Flash-based EEPROM emulation
```

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
