### ISSUE TITLE
[BUG] latest bugfix compile error for due

### ISSUE THREAD

**Issue by maukcc** [MarlinFirmware/Marlin#16767]
### Bug Description

When compiling for due we get an error:
```
> In file included from sketch/src/MarlinCore.cpp:39:0:
> sketch/src/module/probe.h:69:40: error: could not convert '0' from 'int' to 'XYZval<float>::<anonymous union>'
>      static constexpr xyz_pos_t offset{0};
>                                         ^
> sketch/src/module/probe.h:70:42: error: could not convert '0' from 'int' to 'XYval<float>::<anonymous union>'
>      static constexpr xy_pos_t offset_xy{0};
>                                           ^
> Multiple libraries were found for "Wire.h"
>  Used: /home/maukcc/.arduino15/packages/arduino/hardware/sam/1.6.12/libraries/Wire
> exit status 1
> Error compiling for board Arduino Due (Native USB Port).
> 
```
This does not happen when compiling for MEGA

**Comment by ellensp** [comment]
Please provide failing config files.
I compiled for BOARD_RADDS and BOARD_RAMPS_DUO_EFB, both compiled no issues

**Comment by maukcc** [comment]
Here you go
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4151959/Configuration.zip)

**Comment by thinkyhead** [comment]
Using your configs I get the result
```
DUE                           SUCCESS   00:00:54.954
```
Re-download a fresh copy of Marlin and try again.

**Comment by maukcc** [comment]
With todays fresh bugfix-2 download and only changed the 2 config files, we still get the same error.
Arduino IDE 1.8.10 with arduino due native port selected. (programming port gives the same results)

**Comment by thinkyhead** [comment]
I used your configs and they compiled very happily, so…… it probably ain't on our end. 🤷‍♂

**Comment by ellensp** [comment]
Compiles on platformio without issues, but this does fail on arduino ide 1.8.9 and 1.8.10 (both Linux in my case)

**Comment by thinkyhead** [comment]
How annoying! Okay, see if this makes it happy:
```cpp
static constexpr xyz_pos_t offset { 0, 0, 0 };
static constexpr xy_pos_t offset_xy { 0, 0 };
```
…or this…
```cpp
static constexpr xyz_pos_t offset = { 0, 0, 0 };
static constexpr xy_pos_t offset_xy = { 0, 0 };
```
…or even this…
```cpp
static constexpr xyz_pos_t offset;
static constexpr xy_pos_t offset_xy;
```
One or all of them should satisfy that eccentric IDE.

**Comment by ellensp** [comment]
Nope, Nope and nope.  not one works.

**Comment by thinkyhead** [comment]
Damn but Arduino takes forever to compile. If you value your sanity, people, upgrade to VSCode.

**Comment by thinkyhead** [comment]
FFS Arduino!
```
.../Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags:
  bad CPU type in executable
```

**Comment by ellensp** [comment]
I'm waiting for the day you say marlin no longer supports Arduino IDE..  it would solve a lot of problems.

**Comment by thinkyhead** [comment]
Seems I had 1.8.9 installed on this laptop. Turning on app folder syncing now…

**Comment by thinkyhead** [comment]
Well, let's get crazy then…
```cpp
static constexpr xyz_pos_t offset = xyz_pos_t({ 0, 0, 0 });
static constexpr xy_pos_t offset_xy = xy_pos_t({ 0, 0 });
```

**Comment by ellensp** [comment]
crazy works, after fixing your typo
    
```
static constexpr xyz_pos_t offset = xyz_pos_t({ 0, 0, 0 });
static constexpr xy_pos_t offset_xy = xy_pos_t({ 0, 0 });

```

**Comment by maukcc** [comment]
Thanks for going the extra meter.

**Comment by thinkyhead** [comment]
Odd that Arduino's compiler isn't bothered by the original syntax in other places. I'll merge a patch shortly.
