### ISSUE TITLE
[QUESTION]  IDEX: X2 driver does Not init in UART mode

### ISSUE THREAD

**Issue by karabas2011** [MarlinFirmware/Marlin#16779]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4151858/Marlin.zip)
### Bug Description

X2 stepper goes 2x of X.  It looks like  it set 1/8 microstep insteed of 1/16 
M122 does NOT show X2 channel at all

### My Configurations
SKR 1.1 pro TMC2208 UART
cartesian IDEX  autopark mode
MARLIN 2.0.x from 30.01.2020

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

Setup, switch to T1
every G1 X10 will move X2 carriage to 20mm
```
>>> M122
SENDING:M122
		X	Y	Z	E	E1
Enabled		false	false	false	false	false
Set current	800	800	800	800	800
RMS current	795	795	795	795	795
MAX current	1121	1121	1121	1121	1121
Run current	25/31	25/31	25/31	25/31	25/31
Hold current	12/31	12/31	12/31	12/31	12/31
CS actual	12/31	12/31	12/31	12/31	12/31
PWM scale	35	36	83	14	14
vsense		1=.18	1=.18	1=.18	1=.18	1=.18
stealthChop	true	true	true	true	true
msteps		16	16	16	16	16
tstep		max	max	max	max	max
pwm
threshold
[mm/s]
OT prewarn	false	false	false	false	false
OT prewarn has
been triggered	false	false	false	false	false
off time	3	3	3	3	3
blank time	24	24	24	24	24
hysteresis
-end		-1	-1	-1	-1	-1
-start		1	1	1	1	1
Stallguard thrs
DRVSTATUS	X	Y	Z	E	E1
stst		*	*	*	*	*
olb
ola
s2gb
s2ga
otpw
ot
157C
150C
143C
120C
s2vsa
s2vsb
Driver registers:
		X	0xC0:0C:00:00
		Y	0xC0:0C:00:00
		Z	0xC0:0C:00:00
		E	0xC0:0C:00:00
		E1	0xC0:0C:00:00
Testing X connection... OK
Testing Y connection... OK
Testing Z connection... OK
Testing E connection... OK
Testing E1 connection... OK
```

**Comment by TheNeskik** [comment]
In the configuration_adv file, you did not activate Dual_X_Carriage or Dual_X_Stepper, is this normal?

**Comment by thinkyhead** [comment]
Agreed. You're not doing IDEX without enabling `DUAL_X_CARRIAGE`, chief.

**Comment by boelle** [comment]
could we not move this support Q to discord instead?

**Comment by karabas2011** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4152326/Marlin.zip)
Sorry guys, old config. This is actual one.

**Comment by thinkyhead** [comment]
You're certain all the jumpers on the board are consistent?

**Comment by thinkyhead** [comment]
Not that it would matter for this issue, but `M502`, `M500` to Reset EEPROM can never hurt.

**Comment by thinkyhead** [comment]
I'm thinking this could potentially be a hardware issue. Your configs look fine to me.
Are those 1.9° steppers with 12-tooth pulleys or 0.8° steppers with 24-tooth pulleys?

**Comment by karabas2011** [comment]
1.9 steppers with 12mm/turn leadscrews.
The problem is only on newer snapshot
Today I dl current snapshot - the same.
TMC lib is changed recently. I think some forgotten settings.
Where is step settings for X2?

**Comment by karabas2011** [comment]
> Not that it would matter for this issue, but `M502`, `M500` to Reset EEPROM can never hurt.

My friend got the same problem. He pointed me on it and I confirmed. 
Two identical printers.

**Comment by karabas2011** [comment]
The same printer - snapshot from 30.11.2019
Connecting...
Printer is now online.
>>> M122
SENDING:M122
Testing X connection... OK
Testing X2 connection... OK
Testing Y connection... OK
Testing Z connection... OK
Testing E connection... OK
Testing E1 connection... OK

No hardware differencies:
we see that last snapshot does init X2 driver in standalone mode but not in UART mode

**Comment by boelle** [comment]
> 12mm/turn leadscrews.

so no belt and pulley? @thinkyhead wanted to know about those

**Comment by karabas2011** [comment]
> > 12mm/turn leadscrews.
> 
> so no belt and pulley? @thinkyhead wanted to know about those

exactly.

**Comment by karabas2011** [comment]
thе only difference is  snapshot date.

**Comment by boelle** [comment]
just curious, is it a self build printer? first time i see a printer without belts for X and Y

**Comment by karabas2011** [comment]
We are developed such printers. To be sure that they are good or not. Currently  feedrate is 150-300mm/sec depending of carriage weight.
but on lowerfeedrates  in range 50-150 - some strange resonance like stuttering. Plastic nuts. 
And sometimes TMC2208 uart stops working until M84.

**Comment by InsanityAutomation** [comment]
@boelle its actually fairly common when you start to hit the industrial range.

TMC drivers will hang if the step rate gets too fast until enable is dropped, or sometimes even a power cycle. Could try increasing the pulse timings a bit for that problem.

Only issue I have chasing it is my idex machines are all standalone drivers, not uart. Ill do a little poking.

**Comment by karabas2011** [comment]
Does anybody able to replicate the problem?  or any possibility to set microsteps to X2?

**Comment by InsanityAutomation** [comment]
Sorry, day job and wrapping up mrrf projects have eaten all my time. I'll get to it at some point... Hopefully sooner than later...

**Comment by thinkyhead** [comment]
> Does anybody able to replicate the problem? or any possibility to set microsteps to X2?

Checking the code it looks like all the drivers are initialized in the same way and at the same time.

Try sending `M502` followed by `M122` a few times and see if anything changes.

**Comment by thinkyhead** [comment]
Here are your configs updated for the latest Marlin code: [config-204.zip](https://github.com/MarlinFirmware/Marlin/files/4301049/config-204.zip). Give `bugfix-2.0.x` a try and see if the same issue appears.

**Comment by karabas2011** [comment]
>>> M906
SENDING:M906
X driver current: 800
X2 driver current: 800
Y driver current: 800
Z driver current: 800
E driver current: 800
E1 driver current: 800

All works!!!  Thanx!
snapshot from 05.03.2020
