### ISSUE TITLE
Filament Width - Dual Extruder

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#1677]
Please add the filament width sensor for a second extruder. thanks. :-)

**Comment by nikolindima** [comment]
Will this feature be in next release? Really looking forward to this feature

**Comment by Roxy-3D** [comment]
This probably should be over in MarlinDev.

**Comment by nikolindima** [comment]
i have loaded MarlinDev and same
- Single extruder only at this point (extruder 0)

**Comment by thinkyhead** [comment]
This won't be making it into this release (1.1.0) as we've frozen new features, but this can be worked on over at `MarlinDev`. If you haven't already, please [open a Feature Request](https://github.com/MarlinFirmware/MarlinDev/issues) over there.
