### ISSUE TITLE
[FR] support st7735 (uclib) (ezt t1 board)

### ISSUE THREAD

**Issue by whoim2** [MarlinFirmware/Marlin#16787]
Sinis / Ezt / T1 delta printer have st7735 128*128 color display SPI. U8Cglib not support him, but UCglib from identical author - support. Libs have many identical things.
Please, add support for st7735 display. I may test it.

https://github.com/olikraus/ucglib/wiki/displays

PS: chip stm32f103rbt6 need replace to stm32f103rct6 or ret6, its no problem.
ILI9341 very interesting display too.

Sorry, if my english is bad)

**Comment by ugers** [comment]
I have exactly such plans. replace the chip and use marlin. I join the request to add a display.

**Comment by whoim2** [comment]
> I have exactly such plans. replace the chip and use marlin. I join the request to add a display.

Go to telegram channel 
https://t.me/EZT_T1 (russian), we have many interesting )

**Comment by majekw** [comment]
There is similar work for other graphic lcds not supported in u8g here: https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/lcd/dogm/u8g_dev_tft_320x240_upscale_from_128x64.cpp
