### ISSUE TITLE
[BUG] Fysetc S6 emulated EEPROM zaps BLTouch

### ISSUE THREAD

**Issue by TB1405** [MarlinFirmware/Marlin#16795]
i confirmed this issue on the Marlin 2.0.3 and actual bugfixes2.0.x

### Bug Description
if i change a value that will be safed in eeprom the homing doesnt work. 
problem is the bltouch doesnt then deploy the pin out before homing Z axis. 
but when i restart the printer the works normal including bl touch. 
if i change now again a eeprom value and safe it the homing wont work again (BL touch pin wont push out) 
my marlin file is attached. 

### My Configurations

[MarlinS6-EEPROMProblem-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/4166809/MarlinS6-EEPROMProblem-2.0.x.zip)

### Steps to Reproduce

1. download my config and compile it in VSC 
2. load it to fysetc S6 
3. change a value (accel or babystep or homingthreshold etc.) and safe it on eeprom ( i know it isnt a real eeprom)
4. click the auto home button

**Expected behavior:** succesful homing 

**Actual behavior:** the homing for  x and y axis is without issue. when homing z the bltouch wont push out the pin and the printer will ram in the bed 

restart the printer now and click on homing again but dont change or safe any value on eeprom before
**Expected behavior:** succesful homing 

**Actual behavior:** succesful homing 

#### Additional Information
iam using in this configuration a ftdi touch but should be the same problem with other displays. 
When i change in the pin_FYSETC_S6 from #define FLASH_EEPROM_EMULATION to 
#define SRAM_EEPROM_EMULATION it works but if you now restart the printer all settings away

**Comment by neo799** [comment]
I got the same issue. Printing works fine but as soon I use M500 the BLTouch won't work anymore for Homing etc.

**Comment by BastR** [comment]
I had that problem, then it disappeared BUT I have that problem again too.

On SKR PRO, I had opened an issue here https://github.com/MarlinFirmware/Marlin/issues/16169.

I may be wrong, but I seem to remember it was about the TIMERS.

@sjasonsmith Seems to me you've been working on that? (sorry if I'm wrong)

**Comment by TB1405** [comment]
I activated the i2c eeprom but doesnt adapt one to the board and it works correct. I dont know why but if you activate i2c eeprom the Flash eeprom feature works correct

**Comment by GhostlyCrowd** [comment]
Just wanted to Post that this is still an issue on Buxfix 2.0.x branch on the SKR Pro 1.1 Exact same issue any eeprom saving causes tool head crash because of failure to deploy probe.

SD Eeprom Emulation is a work around that fixes this

**Comment by randellhodges** [comment]
> Just wanted to Post that this is still an issue on Buxfix 2.0.x branch on the SKR Pro 1.1 Exact same issue any eeprom saving causes tool head crash because of failure to deploy probe.
> 
> SD Eeprom Emulation is a work around that fixes this

If you can, try the following:

1) Go back to flash based eeprom
2) Verify your bltouch is working and you can see the little blue led on the side of the bltouch
3) Issue an EEPROM save
4) Don't home or anything, just look and see if the bltouch still has the little blue led on
5) If it is still on, issue the servo commands to drop/raise the pin
6) If that works, then see if homing works

Might help narrow some things down

**Comment by trouch** [comment]
Should be fixed with https://github.com/MarlinFirmware/Marlin/pull/17946
