### ISSUE TITLE
[BUG] Use G28, Error, Homing Failed

### ISSUE THREAD

**Issue by jackshi618** [MarlinFirmware/Marlin#16801]
Run 2.0.3
Use G28, Error, Homing Failed
X=min, Y=min, Z=max
use AUTO_BED_LEVELING_LINEAR
Run G28, 1.Z-axis reset normal, 2.X-axis normal, 3.Y-axis run to half-reported error, Homing Failed
But if you are set to
X=min, Y=min, Z=min
Then everything's fine.
Run 1.8 is OK

**Comment by jackshi618** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4171821/Marlin.zip)

**Comment by jackshi618** [comment]
Only when you reset Y makes a mistake.

**Comment by jackshi618** [comment]
[pins_3DYMY.zip](https://github.com/MarlinFirmware/Marlin/files/4171964/pins_3DYMY.zip)

**Comment by boelle** [comment]
@jackshi618 tried bugfix 2.0.x ?

**Comment by boelle** [comment]
where did you get marlin from? marlin config files do not have chinesse writing in it

**Comment by jackshi618** [comment]
2.0.3 
Chinese i added it myself.
Marlin download from GitHub

**Comment by jackshi618** [comment]
@boelle 2.0.3

**Comment by jackshi618** [comment]
@boelle 
Chinese i added it myself.
Marlin download from GitHub

**Comment by boelle** [comment]
there are many places on github where you can get marlin

please link to where you got it

**Comment by jackshi618** [comment]
@boelle 
https://github.com/MarlinFirmware/Marlin

**Comment by boelle** [comment]
@jackshi618 tried bugfix 2.0.x ?

**Comment by jackshi618** [comment]
Didn't try 2.0.x.

**Comment by boelle** [comment]
please try

**Comment by jackshi618** [comment]
ok,Test it later.

**Comment by jackshi618** [comment]
@boelle try 2.0.x,The same problem.

**Comment by boelle** [comment]
do you use normal endstops with a microswitch?

what does M119 say if no nedstop is activated?

and what happens if you touch the endstop with a finger and send M119?

do one endstop and then move to the next, just to check if they are bad

**Comment by jackshi618** [comment]
run 1.1.8 ,no bug,no err
1.1.9-2.0.x,same bug

**Comment by Papipapito** [comment]
Hello I'm same problem, with 2.0.4.3
Delta with Microswitch into zxy max , Board SKR mini v1.1
M119 ALL ENDSTOP OPEN
Send G28, the printer up to endstop
Move arms first X, and when clik into endstop, the console show:

Pinter Halted kill Called

Sometimes the error show when move Y to endstop

And sometimes everything works fine and I can launch a G33, it is a very random failure to do G28

**Comment by thinkyhead** [comment]
Please test with the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) so we're all on the same page here. That branch contains all the latest patches. Don't forget to do `M502`, `M500` after flashing new firmware.

**Comment by Papipapito** [comment]
Hello

Yes, with bugfix-2.0.x are solved .

when does bugfix come together in branch stable 2.0.x?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
