### ISSUE TITLE
[FR] Unload and load filament features  along with change filament

### ISSUE THREAD

**Issue by Liger0** [MarlinFirmware/Marlin#16807]
### Description

It would be useful to have the functions to load and unload filaments separated from the Change filament one, for when you only have to load or unload and aren't going to print afterwise or you already have no rolls inside (the scratching of the toothed pulleys without a filament isn't very cool).

**Comment by ellensp** [comment]
this is already in firmware FILAMENT_LOAD_UNLOAD_GCODES  in Configuration_adv.h

**Comment by Liger0** [comment]
Interesting, I missed those. Thanks.

**Comment by thinkyhead** [comment]
I agree that it would be nice to have plain "load" and "unload" functions in the menu and not to be required to always unload / reload from there.
