### ISSUE TITLE
[BUG] Power Loss recovery fails when recovering from pause state

### ISSUE THREAD

**Issue by InsanityAutomation** [MarlinFirmware/Marlin#16817]
If power loss recovery is triggered while machine was left pause (M125 / M600 Filament runout and such) the recovered height will be incorrect.

Pause states will need to be recorded to recover from the appropriate point with any z-raise.

**Comment by boelle** [comment]
has some miracle been performed on this one? ie it fixed itself

**Comment by InsanityAutomation** [comment]
Still valid, just too far down on my priority list so i havnt touched it.

**Comment by thinkyhead** [comment]
Changes have been made to PLR recently, so it's worth another look.
