### ISSUE TITLE
[BUG] Babystepping, Z probe offset accuracy

### ISSUE THREAD

**Issue by FreestylePocker** [MarlinFirmware/Marlin#16821]
### Bug Description
Hardware:
- SKR PRO v1.1
- RepRapDiscount Full Graphic Smart Controller

Sofwtware:
- Marlin bugfix-2.0.x commit 38bf552
 
  
### My Configurations

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/4177855/Configurations.zip)

### Steps to Reproduce

1. [compile]
2. [flash]
3. [go to display Menu -> Configuration -> set Z probe offset]

**Expected behavior:** [3 digits after floating point]

**Actual behavior:** [2 digits after floating point]

#### Additional Information

It was 3 digits after point before recent updates, after I pulled recent changes this number became rounded to format like dddd.dd but was ddd.ddd

UPD in version 2.0.1 is d.ddd format (correct one)

**Comment by joewmorrissey** [comment]
Thank god, i'm not the only one to notice. This issue is not only on just baby stepping but on any movements. 

display menu -> motion -> move axis -> z - move by 10mm  - same issue

**Comment by thinkyhead** [comment]
Try setting `Z_PROBE_OFFSET_RANGE_MIN` to -5 and `Z_PROBE_OFFSET_RANGE_MAX` to 5.

```cpp
#if Z_PROBE_OFFSET_RANGE_MIN >= -9 && Z_PROBE_OFFSET_RANGE_MAX <= 9
  #define LCD_Z_OFFSET_FUNC(N) ftostr54sign(N)
  #define LCD_Z_OFFSET_TYPE float43
#else
  #define LCD_Z_OFFSET_FUNC(N) ftostr52sign(N)
  #define LCD_Z_OFFSET_TYPE float52
#endif
```

**Comment by joewmorrissey** [comment]
> Try setting `Z_PROBE_OFFSET_RANGE_MIN` to -5 and `Z_PROBE_OFFSET_RANGE_MAX` to 5.
> 
> ```c++
> #if Z_PROBE_OFFSET_RANGE_MIN >= -9 && Z_PROBE_OFFSET_RANGE_MAX <= 9
>   #define LCD_Z_OFFSET_FUNC(N) ftostr54sign(N)
>   #define LCD_Z_OFFSET_TYPE float43
> #else
>   #define LCD_Z_OFFSET_FUNC(N) ftostr52sign(N)
>   #define LCD_Z_OFFSET_TYPE float52
> #endif
> ```

Made this change in menu.h and still have 2 digits after decimal. This is on Marlin 2.0.4.4 downloaded today.

**Comment by thinkyhead** [comment]
This might be better:
```cpp
#if Z_PROBE_OFFSET_RANGE_MIN >= -9 && Z_PROBE_OFFSET_RANGE_MAX <= 9
  #define LCD_Z_OFFSET_FUNC(N) ftostr54sign(N)
  #define LCD_Z_OFFSET_TYPE float52
#else
  #define LCD_Z_OFFSET_FUNC(N) ftostr52sign(N)
  #define LCD_Z_OFFSET_TYPE float43
#endif
```

**Comment by skipfie** [comment]
Even after changing that block in menu.h, and setting the min and max to +/- 5, I'm still only seeing 2 decimal places on the LCD. Marlin 2.0.5.1

**Comment by Allan-N** [comment]
Would it be simpler to just use ftostr53_63() ?

**Comment by boelle** [comment]
@FreestylePocker 
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.
