### ISSUE TITLE
[BUG] #16818 seems to corrupt communication

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#16838]
It seems that above reported PR corrupt all communications. I'm investigating

**Comment by GMagician** [comment]
Well well well well, it seems that each gcode line is seen twice
so 'line number is not last line number+1' error is sent

Tomorrow I'll investigate what is generated by compiler...

**Comment by vivian-ng** [comment]
Will this affect printing from SD card? I have been trying to start a print from the SD card after flashing with latest bugfix-2.0.x, but the printer seems to just do nothing.

**Comment by vivian-ng** [comment]
I reset to before the commit for [PR#16818](https://github.com/MarlinFirmware/Marlin/pull/16818) and can now start a print from SD card. Seems like the commit from PR#16818 onward may have some code that affects how gcode is read. Hopefully someone with better knowledge of how the PR was implemented (like @thinkyhead ) can shed some light.

**Comment by GMagician** [comment]
@vivian-ng yes it may affect also sd printing. Common code. This evening I'm gonna check it
