### ISSUE TITLE
Trigorilla Incorrect Endstop

### ISSUE THREAD

**Issue by Orange-Murker** [MarlinFirmware/Marlin#16834]
Limit switches are incorrect in board TRIGORILLA_14 in current release everything was fine in previous 1.1.9

Now config has:
//
// Limit Switches
//
#define X_MAX_PIN          43
#define Y_MIN_PIN          19

In reality they are D2 and D14 respectively

This causes printer to crash on homing

**Comment by sjasonsmith** [comment]
For anyone running across this, this has been fixed in bugfix-2.0x, after the 2.0.3 release.

The pins in the quote above relate to one particular Anycubic printer which uses a daughter board to re-allocate pins.

**Comment by Orange-Murker** [comment]
Ok. Thank You. Sorry for duplicating the issue
