### ISSUE TITLE
 SKR PRO V1.1 with TMC2209

### ISSUE THREAD

**Issue by fiveofds** [MarlinFirmware/Marlin#16853]
I have an SKR PRO V1.1 with TMC2209s using Configurations from Bigtreetec I can get sensorless homing working IF it is configured as a cartesian printer but then configuring for my delta printer:

// Direction of endstops when homing; 1=MAX, -1=MIN
// :[-1,1]
#define X_HOME_DIR 1 //MPD
#define Y_HOME_DIR 1 //MPD
#define Z_HOME_DIR 1 //MPD

When this is switched from -1 to 1 sensorless homing stops working
Any advice?

https://drive.google.com/file/d/1LUrxH_01t1XlZNFe2P4wqudVntanQp1f/view?usp=sharing

**Comment by boelle** [comment]
@fiveofds do you still have issues?

**Comment by fiveofds** [comment]
Have not tried in a while now, but I will find the time and see what happens.MikeSent from my T-Mobile 4G LTE Device
-------- Original message --------From: Bo Herrmannsen <notifications@github.com> Date: 6/20/20  4:57 PM  (GMT-05:00) To: MarlinFirmware/Marlin <Marlin@noreply.github.com> Cc: Mike Duncan <nacnudskim@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [MarlinFirmware/Marlin]  SKR PRO V1.1 with TMC2209 (#16853) 
@fiveofds do you still have issues?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MarlinFirmware/Marlin/issues/16853#issuecomment-647044549",
"url": "https://github.com/MarlinFirmware/Marlin/issues/16853#issuecomment-647044549",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by boelle** [comment]
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
