### ISSUE TITLE
[Q] Separate Steps/mm for a dual-driver Z axis

### ISSUE THREAD

**Issue by jprucks** [MarlinFirmware/Marlin#16865]
Hello. I have updated my Folgertech Prusa i3 2020 build to use threadless ballscrews for the Z axis. 

However, due to poor prints, the pitch isn't identical between each side, and driving both motors with the same driver (same steps/mm) results in a binding X balcony. 

To fix the hardware (the poor prints) I'd need to disassemble the printer, reinstall the old parts, and print new threadless ballscrew nuts, which I've designed to be integral to the X balcony parts. In short, it's a big job and I'm not even sure the pitch would be equal after all that work.

Instead, I'd like to use my spare E1 (second extruder) driver to drive one of the motors at a separate rate from the first. So both Z motors would move the X balcony at the same linear rate, by turning at a different RPM. 

Is this possible? I've seen mixed answers about using different steps/mm for dual extruders, but they're almost all old posts, and/or not directly relevant. 

See: [ How to make driver of E1 for motor Z2? #2923 ](https://github.com/MarlinFirmwar/Marlin/issues/2923)

**Comment by thinkyhead** [comment]
At this time it is not possible. Both Z steppers are tied together into a single unit for purposes of DIR / STEP / EN signals. We hope to have a more flexible system by this time next year.

_Please, do not mark support questions as bugs. Some of the maintainers really dislike it._
