### ISSUE TITLE
[BUG] skr1.3 with lcd mks mini1286 problems

### ISSUE THREAD

**Issue by manarsak** [MarlinFirmware/Marlin#16885]
I use the skr1.3 board with mks mini12864 screen when the sdcard onboard option is enabled the screen does not work and remains white

**Comment by adrianx26** [comment]
will work if you do some changes look here https://github.com/MarlinFirmware/Marlin/issues/15814

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
