### ISSUE TITLE
[BUG] EEPROM Datasize error when Extruders = 0 (fix included)

### ISSUE THREAD

**Issue by fab4fun** [MarlinFirmware/Marlin#16887]
### Bug Description

Setting extruders = 0,  while appearing to not be officially supported, works well except for an EEPROM datasize error when trying to write. 

### My Configurations

MPCNC machine with dual X and Y drivers (X2, Y2) and Z axis  
X2 and Y2 use E0 and E1 in pins.h
TMC2130 with sensorless homing enabled on both X, X2, Y, Y2
Ramps Board (MKS GEN L V2.0)

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/4214730/Configurations.zip)

configuration_store.cpp
This bit of code at line 2094 is holding a place for at least 1 setting, even if extruders set to 0:
```
      //
      // Linear Advance
      //
      {
        float extruder_advance_K[_MAX(EXTRUDERS, 1)];
        _FIELD_TEST(planner_extruder_advance_K);
        EEPROM_READ(extruder_advance_K);
        #if ENABLED(LIN_ADVANCE)
          if (!validating)
            COPY(planner.extruder_advance_K, extruder_advance_K);
        #endif
      }
```
also at 1242:
```    //
    // Linear Advance
    //
    {
      _FIELD_TEST(planner_extruder_advance_K);

      #if ENABLED(LIN_ADVANCE)
        EEPROM_WRITE(planner.extruder_advance_K);
      #else
        dummy = 0;
        for (uint8_t q = _MAX(EXTRUDERS, 1); q--;) EEPROM_WRITE(dummy);
      #endif
    }
```

Expect EEPROM hold place for at least 1 extruder setting 
object declaration needs to match (line 326 isn't following the convention)

Patch required:

-(326)  float planner_extruder_advance_K[EXTRUDERS];          // M900 K  planner.extruder_advance_K
+(326)   float planner_extruder_advance_K[_MAX(EXTRUDERS, 1)];          // M900 K  planner.extruder_advance_K

**Comment by fab4fun** [comment]
any updates?  I thought this would be easy for someone to integrate

**Comment by thinkyhead** [comment]
Thanks! The issues are coming in so fast that they get lost if we don't read 50 a day…. Not that we mind. I'll merge the fix shortly.

**Comment by thinkyhead** [comment]
Hmm… Looks like it was merged on Feb 21.

**Comment by fab4fun** [comment]
Thanks for checking...  the updates are also coming in very fast so I missed the merge!
