### ISSUE TITLE
[BUG] Z probe offset doesn't work live

### ISSUE THREAD

**Issue by Liger0** [MarlinFirmware/Marlin#16903]
Bug Description

The zprobe offset doesn't work in live

### My Configurations
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4226613/Marlin.zip)
Today's bugfix.

### Steps to Reproduce

1. Auto home
2. Go to Config-> Probe z offset
3. Change the value

**Expected behavior:** Move the z axis along to respect the offset

**Actual behavior:** Nothing happens until I rehome

#### Additional Information

With old version of bugfix from january it worked using same settings.

**Comment by thisiskeithb** [comment]
I reported this as well: https://github.com/MarlinFirmware/Marlin/issues/16889

**Comment by Liger0** [comment]
I see, I didn't notice it. I'm closing this.
