### ISSUE TITLE
[BUG] (short description)Pausing or Cancelling prints from Octoprint leaves printer in "Printing..."state with Marlin 2.0.3

### ISSUE THREAD

**Issue by Thinkersbluff** [MarlinFirmware/Marlin#16907]
### Bug Description

At release 2.0.3 of Marlin, I am no longer able to Pause or Cancel prints correctly from within Octoprint.  The printer does not seem to know that the job has been Paused, or Cancelled.  It seems instead to remain in the "Printing..." state.
I have not tried release 2.0.2, but this problem does  not occur when I use release 2.0.1, with exactly the same config files.

### My Configurations
[ConfigurationFiles.zip](https://github.com/MarlinFirmware/Marlin/files/4229151/ConfigurationFiles.zip)

### Steps to Reproduce

1. Start a Print job from the Octoprint interface
2. Select either Pause or Cancel, while the printer is heating up or after it has started printing
3. The printer will process the GCodes defined in Octoprint, but the printer remains in the "Printing..." state, as evident from the main printer menu still showing Pause print, Stop print and Tune menu items

**Expected behavior:** Printer should return to the PrintDone state, ready to go again.

**Actual behavior:** The printer will process the GCodes defined in Octoprint, but the printer remains in the "Printing..." state, as evident from the main printer menu still showing Pause print, Stop print and Tune menu items

#### Additional Information

* Using an Ender 3 fitted with an SKR e3 mini v1.2.  
* Octoprint Version 1.3.12 running on a Pi 3B+ connected to the printer via USB.
* PC running Microsoft Edge on Windows 10 connecting with Octoprint via WiFi.

When using precisely the same Config files compiled with Marlin 2.0.1, the printer works as expected but if compiled with Marlin 2.0.3, it does not.

**Comment by ellensp** [comment]
Suspect this is issue  #16749, this has been fixed in bugfix and will be in next release.

**Comment by GMagician** [comment]
and by #16849, see issue #16893

**Comment by Thinkersbluff** [comment]
Thanks for the cross-references, @ellensp and @GMagician.  Evidently, my strategies for checking whether an issue is already identified still need work.  I spent a lot of time trying to deduce whether my issue was an Octoprint issue, a BTT SKR Mini issue, or a serial interface issue.  By the time I thought of comparing 2.0.1 to 2.0.3, I was focused specifically on Octoprint, not the more generic term "host".
Yes, using the latest bug-fix version today, when the Host Cancel print command includes turning-off the heaters, the action of Cancelling from the Host interface does now cause the printer to stop the job.
I do find, however, that Pausing a job from the Host simply pauses the datastream and the printer just stops moving when it has drained the buffer.  The printer does not realize that the job has been paused. 
Maybe that is an issue for the Host developers to address...  At least Octoprint allows me to specify gcodes to send when Canceling a job.  I will go ahead and close this issue, assuming that the current behaviour is a feature, not a bug, from Marlin's point of view.
