### ISSUE TITLE
Crash on endstop

### ISSUE THREAD

**Issue by murdock62** [MarlinFirmware/Marlin#16919]
### Bug Description

My Min position is 0 on both axis (X and Y).

After homing if i move to 0 (for example G1 X0) then carriage will crash on the endstop.

No problem with 2.0.0

Many thanks for your help.

### My Configurations

[Cfg.zip](https://github.com/MarlinFirmware/Marlin/files/4238708/Cfg.zip)

**Comment by ellensp** [comment]
This doesn't make sense, after homing your at X0, Y0 so G1 X0 does nothing. It shouldn't even attempt to move.

**Comment by murdock62** [comment]
@ellensp 
> This doesn't make sense, after homing your at X0, Y0 so G1 X0 does nothing. It shouldn't even attempt to move.

oops little precision homing made with bltouch and Z safe homing. 
So the carriage stay to the center of the bed after G28.

After the G28 if i send G1 X0 (or Y0) ---> Crash !

**Comment by ellensp** [comment]
"crash" is not a very useful term.... Do you mean that the axis moves towards the end stop and does not stop?

**Comment by murdock62** [comment]
Yes quite.  Sorry for the wrong term.  I wanted to find a "synthetic" expression to explain that indeed the carriage did not stop and violently struck the endstops but with my bad English and the late hour, I chose my words wrong.  Sorry!

**Comment by Marlor** [comment]
https://github.com/MarlinFirmware/Marlin/issues/16481#issuecomment-573400605 there is the reason and a manual fix

**Comment by murdock62** [comment]
Thanks @Marlor !

But wow :

Too tired to find the right way to qulifier my problem 
the nose in the middle of the face ... 
(French expression I do not know if it exists elsewhere .. .)

I better go to bed rather than insist on certain evenings ...

Many thanks again !
