### ISSUE TITLE
[BUG] UBL grid vertices visible in prints

### ISSUE THREAD

**Issue by halninekilo** [MarlinFirmware/Marlin#16910]
plz delete - sorry!

**Comment by rado79** [comment]
confirmed. there are spots in infill, in my case i can observe on extrudergear that linear advance does release pressure on some spots, every layer on same place. really hard visible on surface.

**Comment by halninekilo** [comment]
Usererror in my case (invalid mesh) - filling in two outlines of missing points via `G29 P3; G29 P3;` seems to have solved the issue.

**Comment by rado79** [comment]
There are no missing probe points in my mesh.
