### ISSUE TITLE
[BUG] Bugfix-2.0.x Last bugfix does not compile with UBL

### ISSUE THREAD

**Issue by Bergerac56** [MarlinFirmware/Marlin#16916]
With last bugfix 6320f9795ca91e8c467339afeaa5d3d354500543, and a very basic config file (Just UBL, fixed probe and graphic LCD.), "compile" fails

Compiling .pio\build\megaatmega2560\src\src\feature\binary_protocol.cpp.o
Marlin\src\feature\bedlevel\ubl\ubl.cpp: In static member function 'static void unified_bed_leveling::display_map(int)':
Marlin\src\feature\bedlevel\ubl\ubl.cpp:156:22: error: 'gcode' was not declared in this scope
     const bool was = gcode.set_autoreport_paused(true);
                      ^
Marlin\src\feature\bedlevel\ubl\ubl.cpp:232:5: error: 'set_gcode' was not declared in this scope
     set_gcode.set_autoreport_paused(was);
     ^
*** [.pio\build\megaatmega2560\src\src\feature\bedlevel\ubl\ubl.cpp.o] Error 1

Test config file : 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4235858/Configuration.zip)

**Comment by ellensp** [comment]
Yes this is already known, see https://github.com/MarlinFirmware/Marlin/pull/16914/files for a patch.

**Comment by Bergerac56** [comment]
@ellensp. Sorry, I was far from marlin for some days. I did not notice that the issue was already found.
And... Thanks. The fix works perfectly. 

I close the issue
