### ISSUE TITLE
[BUG] Bed temperature not shown

### ISSUE THREAD

**Issue by rs-development** [MarlinFirmware/Marlin#16925]
### Bug Description

Since upgrading to 2.0.3 the bed temperature is not shown anymore. See Picture. Quite sure it is Config related, but I could not find the mistake in the git logs.

### My Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4239662/Configuration.zip)

#### Additional Information

LPC1768
SKR v1.3
RepRapDiscount Display

![photo_2020-02-22_18-22-53](https://user-images.githubusercontent.com/35149229/75096503-67a1b280-55a0-11ea-98c2-865b65a5a7db.jpg)

**Comment by thisiskeithb** [comment]
Give [`2.0.4.1`](https://github.com/MarlinFirmware/Marlin/releases/tag/2.0.4.1) a try.

**Comment by rs-development** [comment]
Sorry, but I would like not to switch again. Last time I switched I got a version that was not even able to compile properly, I think it was 2.0.1.

Any reason why I should switch, something changed?

**Comment by thisiskeithb** [comment]
> Any reason why I should switch, something changed?

Your issue may have been patched, so we’d rather you start with the most current version.

**Comment by ellensp** [comment]
tested with 2.0.3 and provided Configuration files. I get the same results. Additional notes:
The fan icon is in the active position, even though fan has not been turned on.
The heated bed icon is in the heating position, but bed has not been turned on.
Issue is triggered by something in Configuration_adv.h   
the option STATUS_COMBINE_HEATERS stops the bed temperature readings and 
#define STATUS_FAN_FRAMES 4 changes the fan image.

**Comment by ellensp** [comment]
Issue still persists in latest marlin including bugfix. Though I suspect this is not an issue but what STATUS_COMBINE_HEATERS is meant to do.

**Comment by rs-development** [comment]
Thank you for testing! I will test next weekend without the combine heater. You wanted to make sure it's not a simple config mistake. I will report back

**Comment by thinkyhead** [comment]
Indeed. With `STATUS_COMBINE_HEATERS` the entire top section of the screen is expected to be a single image. But the bed temperature should still be displayed. My guess is it's being displayed, but somewhere off the screen.

**Comment by thinkyhead** [comment]
The issue was introduced in 3dc49fd1c6f0be7b765300c433c905c273f36711 and I'll post a solution shortly.

**Comment by thinkyhead** [comment]
Test the latest `bugfix-2.0.x` to see if it solves the issue.

**Comment by rs-development** [comment]
I think it is related to STATUS_BED_WIDTH, which is zero in this configuration and that's why Bed Temperature is not drawn. I have two non-working printers right now, i am not introducing other issues right now. I will take a look at 3dc49fd later and try to understand what's wrong. Thanks for linking it.

**Comment by rs-development** [comment]
https://github.com/MarlinFirmware/Marlin/blob/1955eea1b8f13697259e0e2403d47279d2d1ac6a/Marlin/src/lcd/dogm/dogm_Statusscreen.h#L789

Check this file, I have not tested yet but if the IDE resolves all defines correctly... (did I really think that :dancer: ), this seems the be the issue, not the root cause, but maybe the issue.

**Comment by rs-development** [comment]
So a short test with the code below in Line 788, brings the bed temperature back to life!

    #else
      #define STATUS_BED_WIDTH 21
    #endif

**Comment by boelle** [comment]
@rs-development  
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

@thinkyhead

**Comment by rs-development** [comment]
> @rs-development
> Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.
> 
> @thinkyhead

Thanks for fixing, but I am not willing to invest time into testing at the moment.
