### ISSUE TITLE
[BUG] [2.0.3] Issues with Disabling Steppers

### ISSUE THREAD

**Issue by CCS86** [MarlinFirmware/Marlin#16937]
Hi guys,

I am now running 2.0.3 on my Ultimaker Original and am having two issues related to disabling steppers.

1. When in a print, and choosing 'stop print', the printer aborts and homes X and Y. Instead of then disabling all stepper motors (X, Y, Z, E), it leaves them all engaged.

2. From that point, if I choose 'disable steppers' from the menu, it releases X, Y, & Z, but still holds onto E.

End of a print where an M84 is issued also leaves the extruder stepper in a positional hold.

Any ideas?

**Comment by Lord-Quake** [comment]
First recommendation is to try the latest version of Marlin: `V2.0.4.2` @ https://marlinfw.org/meta/download/

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
