### ISSUE TITLE
onprintingFinished() and onPrintingStarted() callbacks/signals [FR] 

### ISSUE THREAD

**Issue by reddomon** [MarlinFirmware/Marlin#16933]
I am developing  a nextion UI. Make some callback changes but I think marlin needs some sort of callbacks to manage extended UI's.

### Description
Extensible UI development
### Feature Workflow

1. When start a job onPrintingStarted() callback is called
2. Then prints normally
3. When job is finished, onPrintingFinished() callback is called.

#### Additional Information
![IMG_20200223_115615](https://user-images.githubusercontent.com/4271474/75109474-b7ca5480-5634-11ea-904d-a4d4b21d6cde.jpg)
![IMG_20200223_115621](https://user-images.githubusercontent.com/4271474/75109464-a97c3880-5634-11ea-901b-9a74d3dca589.jpg)
![IMG_20200223_115625](https://user-images.githubusercontent.com/4271474/75109456-9ec1a380-5634-11ea-8fea-6a2d71f96725.jpg)
![IMG_20200223_115629](https://user-images.githubusercontent.com/4271474/75109450-8fdaf100-5634-11ea-9eef-c359043692ff.jpg)

![IMG_20200223_115636](https://user-images.githubusercontent.com/4271474/75109479-cf094200-5634-11ea-994c-1671e1d6524b.jpg)
![IMG_20200223_115653](https://user-images.githubusercontent.com/4271474/75109477-c3b61680-5634-11ea-8e88-e8e21931064c.jpg)

**Comment by marciot** [comment]
@reddomon: I developed the ExtensibleUI for LulzBot and the reason there isn't start/stop callbacks is that in the case of tethered printing, "start of print" is an entirely abstract concept. Marlin does not have anyway of distinguishing between interactive commands being sent from the host and an actual print, nor does it really have anyway of knowing when the print has ended.

That said, there is a good proxy for the functionality you desire and that is the print timer. So long as you arrange it so the slicer calls M75 and M77 (such as in your start and end GCODE), then there is an clear way of knowing when a print is in progress in either tethered or untethered mode. This is how it is done in the LulzBot TAZ Pro and there *are* callbacks for those actions:

```
  void onPrintTimerStarted();
  void onPrintTimerPaused();
  void onPrintTimerStopped();
```

**Comment by reddomon** [comment]
Thank you @marciot clearifying that for me :). I see. I thought that if Marlin can call a function when print is done like serial out "print is done", maybe we could do the same thing for UI. My intend is using Marlin as a laser driver, so i think  I can use OnPrint.Timer...() calbacks, adding M75 and M77 command into GCODE. Thank you again.

PS: I added some callbacks before  `SERIAL_ECHOLNPGM(MSG_FILE_PRINTED)` in `queue.cpp` like
```cpp
            #if ENABLED(EXTENSIBLE_UI)
            ExtUI::onPrintFinished();
            #endif
```
, but it is a mistake. :)

**Comment by reddomon** [comment]
Hi there. I dont know is it wrong or right but i resolved the problem (may not be a problem) this way,I added  a function calls after "SD start reading" and an another function call after "SD finish reading".

**Comment by thinkyhead** [comment]
If you have laser questions you should chat with @shitcreek who is also doing laser work with Marlin.
