### ISSUE TITLE
[BUG] Z axis noise BIGTREETECH-SKR-mini-E3

### ISSUE THREAD

**Issue by lamosca01** [MarlinFirmware/Marlin#16942]
### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by swilkens** [comment]
So I think I understand what you mean.

With the latest configuration files, a new feature was turned on by default called 'HYBRID_THRESHOLD'

By default, this sets the threshold for the Z axis at 3 mm/s, which is basically immediately.

For a quick fix, do:

`M913 Z50`

**Comment by lamosca01** [comment]
Thank you! Just that and voila. Regards!
