### ISSUE TITLE
[BUG] changing #define EZABL_POINTS doesn't work

### ISSUE THREAD

**Issue by PeetrP** [MarlinFirmware/Marlin#16968]
I have tried to increase number of probing point from 3x3 to 5x5 by changing line number 829 in configuration.h

from: #define EZABL_POINTS 3
to: #define EZABL_POINTS 5

When i go to octopring it can't connect to my printer saying it gave it a following error:
Error reported by printer
Your printer's firmware reported an error. Due to that OctoPrint will disconnect. Reported error: Field planner_leveling_active mismatch.

Sorry if I'm doing something wrong, but i couldn't find any advice about how to change number of probing points for BL touch using this firmware.

Please advice. Thanks.

**Comment by ellensp** [comment]
That is TH3D Firmware, not Marlin. Please open a support query there
