### ISSUE TITLE
Old/Forgotten "TRINAMICS" definitions in Conditionals_post.h

### ISSUE THREAD

**Issue by b00gie-dev** [MarlinFirmware/Marlin#16961]
In earlier releases there was an #define TRINAMICS in Conditionals_post.h. This define was replaced by "HAS_TRINAMIC || HAS_TRINAMIC_STANDALONE". But in line 648 and 668 are two old "TRINAMICS" leftovers. So I guess they also should be replaced with "HAS_TRINAMIC || HAS_TRINAMIC_STANDALONE".
By now this results in setting up wrong values for "MINIMUM_STEPPER_PULSE" and "MAXIMUM_STEPPER_RATE" when using TMC drivers. (see Screenshot)
![trinamics_definitions](https://user-images.githubusercontent.com/61452016/75231429-bb391980-57b5-11ea-9956-04578d6391fd.png)

Greets,
Niko

**Comment by b00gie-dev** [comment]
added config files (I thing they are not relevant in this case)
[config.zip](https://github.com/MarlinFirmware/Marlin/files/4249033/config.zip

**Comment by ellensp** [comment]
Created a PR to fix this.

**Comment by thinkyhead** [comment]
Good catch, thanks!
