### ISSUE TITLE
[BUG] Are tmc2208 supported in 2.1.x dev?

### ISSUE THREAD

**Issue by zonalimitatore** [MarlinFirmware/Marlin#16975]
I've a gt2560 rev3.
ive mount 2 stepper driver ,but i cant dialogue with motherboard,but can with an external uart/usb module.

If its fully supported,can i do a comunication with both?Or i need 4 pins?Hw or sw?
Maybe it's  only my mb?

**Comment by thinkyhead** [comment]
2.1.x dev is currently not being used. So stick with `bugfix-2.0.x`.

PLEASE do not post questions with a [BUG] label.
That kind of conduct really angers some of the maintainers.
