### ISSUE TITLE
[Q] LEVEL_CORNERS_HEIGHT with Z_MIN_POS -1

### ISSUE THREAD

**Issue by thijses** [MarlinFirmware/Marlin#16994]
just a simple fix:
currently, "LEVEL_BED_CORNERS" moves to a z height which can be set by "LEVEL_CORNERS_HEIGHT".
**the default filled in value is "0.0":**
_"#define LEVEL_CORNERS_HEIGHT 0.0"_
**but, this only works if the Z_MIN endstop is at 0.0**
The problem is: 
when a home offset is present (like z @ endstop = -1.0),
the "level corners" menu feature will still move the hotend to z_min, which is now -1, 
which obviously destroys the bed and/or your nozzle.
**by changing this to:**
_"#define LEVEL_CORNERS_HEIGHT  RAW_Z_POSITION(0.0)"_
**the issue is fixed.**

alternatively, you could replace the line:
"line_to_z(LEVEL_CORNERS_HEIGHT);"
in menu_bed_corners.cpp
to:
"line_to_z(RAW_Z_POSITION(LEVEL_CORNERS_HEIGHT));"

**Comment by thijses** [comment]
i tested it and it seems like changing the very definition of the line_to_z() command might be best
in the menu.cpp file
it is currently:

void line_to_z(const float &z) {
  current_position.z = z;

and i changed it to:
void line_to_z(const float &z) {
  current_position.z = RAW_Z_POSITION(z);

**Comment by thinkyhead** [comment]
The `line_to_z` takes a native Z coordinate as input. All Marlin code works in terms of native (aka "raw) coordinates. And the `LEVEL_CORNERS_HEIGHT` is defined in terms of native machine coordinates.

And Z0 in native machine coordinates is where the nozzle touches the bed.

Your issue is that you've defined a weird Z home offset.
What is the intended purpose of making it -1?

**Comment by thijses** [comment]
> The `line_to_z` takes a native Z coordinate as input. All Marlin code works in terms of native (aka "raw) coordinates. And the `LEVEL_CORNERS_HEIGHT` is defined in terms of native machine coordinates.
> 
> And Z0 in native machine coordinates is where the nozzle touches the bed.
> 
> Your issue is that you've defined a weird Z home offset.
> What is the intended purpose of making it -1?

i frequently switch nozzles, and changing the physical position of the endstop is more tedious than just leveling one corner and setting a home offset. If the new nozzle is longer than the old one  the height at the Z endstop becomes negative.
Also, i appreciate the response, the clearer title and the explenation, thank you.

edit: i also change beds, so same issue same solution.

**Comment by thinkyhead** [comment]
It sounds like you could benefit much from a BLTouch or similar probe. In the meantime, I believe `M206` should do the trick for you.

**Comment by thinkyhead** [comment]
It sounds like you could benefit much from a BLTouch or similar probe. In the meantime, you have the correct workaround for your setup:
```cpp
#define LEVEL_CORNERS_HEIGHT RAW_Z_POSITION(0)
```

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
