### ISSUE TITLE
Hung platformio

### ISSUE THREAD

**Issue by shawnp30** [MarlinFirmware/Marlin#16997]
![image](https://user-images.githubusercontent.com/20215592/75403496-eb77d980-58d5-11ea-8168-74a6fe4d597d.png)
after adding different code for line 530 for earlier error i now get this  .

**Comment by ellensp** [comment]
Not a Marlin issue;
Some sort of internet error while platformio tried to get some required libraries.

**Comment by shawnp30** [comment]
i figured as much. thank you. i shall remove it
