### ISSUE TITLE
Bltouch cuts off if print is ended prematurely. 

### ISSUE THREAD

**Issue by shawnp30** [MarlinFirmware/Marlin#17022]
latest marlin. Bltouch issues. Homing and leveling works fine. When I start a print and end it prematurely the blue light on the bltouch cuts off and becomes unresponsive.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.
