### ISSUE TITLE
Missing info about pinda v2 thermistor pin.

### ISSUE THREAD

**Issue by SFRSKZ** [MarlinFirmware/Marlin#17033]
there is no clear info where to connect white thermistor cable of pinda v2. and didnt find a pin definition in skr v1.3' pin.h. 

i searched in internet but couldnt find a clue. is it th1?

**Comment by Lino77** [comment]
yes 
look BTT_SKR_common.h
#if HOTENDS == 1 && TEMP_SENSOR_PROBE
  #define TEMP_PROBE_PIN   P0_25_A2   // TEMP_1_PIN
#endif

**Comment by SFRSKZ** [comment]
thank you.
