### ISSUE TITLE
[BUG] Ender 5 with Marlin 2.0.4.4 - EEPROM Version

### ISSUE THREAD

**Issue by S474N** [MarlinFirmware/Marlin#17058]
Hi, have Ender 5 with stock motherboard. When I flash 2.0.4.4 to printer, there is "Err: EEPROM Version" on printer display.

When flashed 2.0.3, there is everything OK.

[config-files.zip](https://github.com/MarlinFirmware/Marlin/files/4281023/config-files.zip)

**Comment by ellensp** [comment]
This is NOT a bug.

The version number in the eeprom like the version number of the firmware has increased.

You need to reset the eeprom contents. M502, read default settings from firmware. M500, save settings to eeprom.

**Comment by S474N** [comment]
Sorry! I tried Restore and Save from printer menu. If I used M502/M500, is everything OK.
