### ISSUE TITLE
MAXTEMP triggered after PowerOn

### ISSUE THREAD

**Issue by floyd871** [MarlinFirmware/Marlin#1706]
After flushing the latest DEV-Branch in my Delta Printer (Megatronics V3) the Printer stops after Powering on:

Error:0
[ERROR] Error:0

: Extruder switched off. MAXTEMP triggered !!
Error:Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)
[ERROR] Error:Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)

After a bit look in the Code i have revert the changes made in https://github.com/MarlinFirmware/Marlin/pull/1689

Now i could heat up  the Extruder and Headbed again.

**Comment by AnHardt** [comment]
Hello @floyd871 
What IDE do you use (1.0.6, 1.6.1)?
What temp-sensors do you have (Nr.)?

**Comment by floyd871** [comment]
IDE 1.6.1
Extruder / Bed: 1

**Comment by thinkyhead** [comment]
@floyd871 Trying to isolate these temperature issues, I have a suspicion. Starting with the latest code, try changing these lines:

```
#ifdef TEMP_SENSOR_1_AS_REDUNDANT
  #define TEMP_SENSOR_COUNT 2
#else
  #define TEMP_SENSOR_COUNT EXTRUDERS
#endif
```

To:

```
#define TEMP_SENSOR_COUNT 4
```

If this helps, I will make the necessary changes in #1700 .

**Comment by AnHardt** [comment]
Error AND fix confirmed. 
Switching to 1.0.6 now and have a test.

Yes. Overwriting other variables gives configuration and compiler depended different errors. :pray:

**Comment by thinkyhead** [comment]
@AnHardt I guess we're stuck with 4 elements for all the temperature-related code, because the code allows you to have thermistor 2 set to something while thermistor 0 is set to 0.

**Comment by AnHardt** [comment]
@thinkyhead 
Don't worry - just some bytes of RAM.
I think the major part of #1689 can be reverted. I only shifted the the error to an other place. But please don't forget the MAX6675 and the PSTR().

**Comment by thinkyhead** [comment]
#1707

**Comment by AnHardt** [comment]
As far as i see also OK with 1.0.6 and my 6 standard configurations - including MAX6675.

**Comment by thinkyhead** [comment]
Ok, just need to see if #1707 solves things for @floyd871 too…

**Comment by floyd871** [comment]
Now i have a complete different situation, the Printer powers up with no Error. But heats up the Extruder and Hotend immediate. Set to extrem high temperatures. I'm unable to set another temperature, I could only switch off:

![printer](https://cloud.githubusercontent.com/assets/7797850/6864123/65d86062-d45d-11e4-86f8-c14e9d140697.jpg)

**Comment by thinkyhead** [comment]
@floyd871 Well, that's not good…!

I will have another thorough look at the temperature code over the weekend and get this sorted out. Will you be available to help test?

**Comment by floyd871** [comment]
Sure, go ahead.

**Comment by floyd871** [comment]
Last updates to https://github.com/MarlinFirmware/Marlin/issues/1711 (same issue)  fixes mine too

**Comment by oysteinkrog** [comment]
Fixed for me in head
