### ISSUE TITLE
Fysetc AIO II only half heater PWM

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#17086]
PID Tuning Shows only half pwm (127) so heater overshots 4°C (peek-to-peek 8°C)

i testet example config without changing anything, same effect.

**Comment by sjasonsmith** [comment]
Please follow the instructions in the template and post copies of your configuration files.

After doing that, please explain how you are observing the issue, so that somebody else knows what to look for.

**Comment by ghost** [comment]
As your wish, my config and some Picture from  the Problem

Pic 1 is at PID tuning
![fysetc_aio_II_1](https://user-images.githubusercontent.com/58679265/76163796-8f207f80-6149-11ea-9766-730f7c0437bb.png)
Pic 2 is after saved PID values and rebootet board
![fysetc_aio_II_2](https://user-images.githubusercontent.com/58679265/76163797-8fb91600-6149-11ea-8118-fe262aec2f4f.png)


[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4303243/Marlin.zip)

**Comment by ellensp** [comment]
Please read https://reprap.org/forum/read.php?146,554826
"Marlin does not show the PWM (as one would expect!) from 0 - 255, but somehow only from 0-127 - i.e. the least significant bit is lost. So if you see "...B@:127" in pronterface, this means you have a full 100% duty cycle"

**Comment by ghost** [comment]
hmmmm.... 5 Printer Show there 255 only this board Shows 127 and Need more time to heat up (i wanna Change a board from 1 Printer)

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
