### ISSUE TITLE
[BUG] (stm32/i2c2/eeprom 24c02) Field esteppers mismatch.

### ISSUE THREAD

**Issue by whoim2** [MarlinFirmware/Marlin#17087]
Hello! Have a custom pcb from EZT T1 Delta. Have stm32f103rtc6 (256kb) and 24c02 eeprom on i2c2 bus
Configuration.h
#define EEPROM_SETTINGS
#define EEPROM_CHITCHAT

\pins\stm32\pins_STM32F1R.h
#define I2C_EEPROM
#define E2END 0xFF

\module\configuration_store.cpp
#define DEBUG_EEPROM_READWRITE

Users\whoim\.platformio\packages\framework-arduinoststm32-maple\STM32F1\libraries\Wire\Wire.cpp
TwoWire Wire(2); //secondary i2c bus

On M500 (after M502) have error: Field esteppers mismatch.

Trying add delay (2-10) after eeprom_write_byte(p, v) in 
 HAL\HAL_STM32F1\persistent_store_eeprom.cpp, no effect
Help please.

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
