### ISSUE TITLE
Mks Robin Pro: Touch not responsive

### ISSUE THREAD

**Issue by 3Dangel** [MarlinFirmware/Marlin#17083]
installed Marlin 2.0.x and MKS Robin TFT touch V1.0 not responsive
Verified PINS.h
STM32
Mks_robin_pro.h
....
  #if ENABLED(TOUCH_BUTTONS)
    #define TOUCH_CS_PIN   PA7
#else

It is missing the rest of pins to get the feedback through SPI2
it should be:
......
  #if ENABLED(TOUCH_BUTTONS)
    #define TOUCH_CS_PIN   PA7
    #define TOUCH_SCK_PIN    PB13  // SPI2_SCK
    #define TOUCH_MISO_PIN   PB14  // SPI2_MISO
    #define TOUCH_MOSI_PIN   PB15
  #else

Tested, now all working at my touchscreen.

Cheers

**Comment by thisiskeithb** [comment]
Want to put in a PR? 🙂
