### ISSUE TITLE
max_inactive_time corruption

### ISSUE THREAD

**Issue by alvinavr** [MarlinFirmware/Marlin#1709]
I am on version #1698 from yesterday.

The value of max_inactive_time is set to decimal 100 when a G28 or G29 command is issued.
This causes kill() to be called. A simple move of the X or Y carige does not trigger this.

I added some debug code to M85 to see what was happening. At power on the value is 0, correct. The M85 command correctly sets and reads(debug code) this value. I commented out the call to kill() and all works OK.

This has the look of a memory corruption bug. Any hints on how to find it?

I am testing on a RepRapPro Huxley. The only non configuration change I made is to copy and paste the algebraic thermistor code from the RepRapPro Marlin software. If I use the thermistor tables the bed temperature is wrong. 

Alvin

**Comment by thinkyhead** [comment]
You're probably right about it being a buffer overrun. The latest code has patched up all the temperature arrays and made other fixes, so give it a try when you have a chance.

**Comment by alvinavr** [comment]
I can confirm that the problem is fixed in #1707.
