### ISSUE TITLE
[BUG] "TMC connection error" with TMC2209 drivers

### ISSUE THREAD

**Issue by Lupek1** [MarlinFirmware/Marlin#17098]
Hello,
I have home made 3D printer, Ramps board with latest 2.0.4.4 Marlin release and Bigtreetech TMC2209 drivers on X and Y axis. I am able to move axis, but UART connection don't work. "TMC connection error" is shown on LCD all the time. 

I checked all connections multiple times, ask for support on FB page, seeking for solution on internet but infortunately, after one month, I still didn't manage to solve it. So I am asking you for some help.

Regards,
Luka
[TMC_issue.zip](https://github.com/MarlinFirmware/Marlin/files/4304007/TMC_issue.zip)

**Comment by ellensp** [comment]
For support try the https://reprap.org/forum/index.php forums.
And you will need to provide much more information. Like brand/supplier of TMC2209 drivers. If you purchased them as UART enabled or you modified them so they work with UART. and how you have it wired it on the RAMPS, what pins you used. etc.  Or talk to someone live over discord. https://github.com/MarlinFirmware/Marlin/issues/14694

**Comment by davidcgu** [comment]
![image](https://user-images.githubusercontent.com/34965121/76252011-5d421280-6248-11ea-9457-82ca2d46d50e.png)

**Comment by Lupek1** [comment]
I use TMC drivers from Bigtreetech: 
https://www.aliexpress.com/item/33025720969.html?af=701906

they allready have UART connection to pin 4 by default. But they connect it using resistor, not weld. 
I keep resistor and make additional connection to pin 5 with weld. But TMC connection error is still there.
![image](https://user-images.githubusercontent.com/61951246/76254764-4fdb5700-624d-11ea-9ffc-bdc0c9aa780c.png)

I use default pins. I believe driver is connected to right pins because as soon as I enable TMC, voltage on those pins go from 0V to 5V.
![image](https://user-images.githubusercontent.com/61951246/76255269-32f35380-624e-11ea-8923-02943386c9e9.png)
![image](https://user-images.githubusercontent.com/61951246/76255290-3dade880-624e-11ea-9ce0-3e623fc129ea.png)

Function M122 gives me:
![image](https://user-images.githubusercontent.com/61951246/76255558-a85f2400-624e-11ea-8d58-50e1a272b833.png)

**Comment by davidcgu** [comment]
Who has te issue? I don't know why you posted instructions, mine are working.... post a picture of the bottom of your drivers...

**Comment by Lupek1** [comment]
Sure. Here is photo of my driver.

![image](https://user-images.githubusercontent.com/61951246/76256832-dfced000-6250-11ea-8d9f-651fd6267d57.png)

**Comment by davidcgu** [comment]
The soldering joint is not correct, look at the picture I shared previosuly, should be like the one on the left side.

Regards

**Comment by davidcgu** [comment]
What the fk!!!!!!!!  why you cutted all those pins?

**Comment by Lupek1** [comment]
See original driver from another perspective. You can see that connection as you shown allready exist. It is made by factory. For connection they used small resistor around 1ohm. 

![image](https://user-images.githubusercontent.com/61951246/76258291-916f0080-6253-11ea-91e9-ce1605868f1a.png)

Ramps board and need external connection for UART. All pins pins I cut on bottom are placed on top side. But as far as I know, just one of them is needed  for UART connection.

![image](https://user-images.githubusercontent.com/61951246/76258456-e27ef480-6253-11ea-9d26-31497452f831.png)

Regards, 
Luka

**Comment by ManuelMcLure** [comment]
The "resistor" is actually a 0-ohm jumper, so it acts just like a solder joint. It's easier for the automated equipment used to create these boards to place a component than make a solder bridge.

I just measured the resistance on all three of my BTT2209s and they were all around 0.10 ohm which is in the realm of measurement noise.

**Comment by davidcgu** [comment]
why you don't consider to upgrade the board? you can get nice 32 bit boards by around 15€

**Comment by Lupek1** [comment]
Davidcgu: In first stage, I would like to understand root cause. It makes no sense for me to purchase new board, altrough it is cheap if I don't know where the root cause is.

Do anyone have any experiances with UART protocol? What are frequencies? How often driver and arduino communicate with each other? I meassure TX and RX signals with 20MHz analog oscilloscope, but I see no signal. Just 5V constant voltage. Unfortunately I don't have enough knowledge to know either signals are too fast to see them with analog oscilostope either something is wrong with firmware.

**Comment by ManuelMcLure** [comment]
Do you have any micro stepping jumpers installed under the drivers? For the 2209s those are interpreted as the "address" of the 2209 and if that address does not match the setting of (for example) ``X_SLAVE_ADDRESS`` in ``Configuration_adv.h`` then the communication will not work.
All slave addresses in ``Configuration_adv.h`` default to 0 which means no jumpers under the drivers.
Also, communication with the TMC drivers will _not_ work if the RAMPS does not have full 12V power. If it is being powered via USB the drivers will not be completely powered up and the communication will fail.

**Comment by ManuelMcLure** [comment]
Also, please come on to the Marlin Discord server for support. This bug tracker is not meant for support issues.

**Comment by Lupek1** [comment]
ManuelMcLure: I removed all 3 jumpers below driver for X and Y axis, where TMC drivers are used. For Z axis and two extruders I keep jumpers because  A4988 are used. Drivers are supplied with 12V from integrated PC power supply. X_SLAVE_ADDRESS are set to 0.

OK. I will open new topic on Marlin discord server. See you there. Thanks for support.

Regards, 
Luka
