### ISSUE TITLE
[BUG] Very high speed to Z SAVE position

### ISSUE THREAD

**Issue by kaeltaz** [MarlinFirmware/Marlin#17096]
Hi
when I turn on auto home, X and Y axis is homing on normal speed then when hotend moves to z save position at very high speed (probably at maximum feedrate) 
How to slow down this movement?

ps. sorry for my bad English :)

**Comment by kaeltaz** [comment]
I use Marlin 2.0.4.4  
how to solve my problem?

**Comment by psavva** [comment]
Please post your config files

**Comment by kaeltaz** [comment]
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/4309095/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/4309097/Configuration_adv.h.txt)

**Comment by kaeltaz** [comment]
https://youtu.be/4enE0p8TQyQ 

Video

**Comment by psavva** [comment]
One too many zeros here...
#define XY_PROBE_SPEED 120000

**Comment by Vertabreak** [comment]
good lord that's fast i cant do more then 2400 with out really bad vibration.
