### ISSUE TITLE
[BUG] Pausing (randomly) During Print - 

### ISSUE THREAD

**Issue by Aetoc** [MarlinFirmware/Marlin#17099]
### Bug Description

While printing, the firmware appears to randomly pause without reason, and the display reads "Click to resume."
### My Configurations
[Marlin Config.zip](https://github.com/MarlinFirmware/Marlin/files/4304117/Marlin.Config.zip)

### Steps to Reproduce

1. Start print via Cura
2. Printer auto levels, heats up, and begins printing
3. Print pauses, leaving the hotend on; "Click to resume..." on the display
4. I click the button on the display
5. Print resumes
6. Repeat 3 - 5

**Expected behavior:** Uninterrupted print

**Actual behavior:** Printer pauses with prompt to resume.

#### Additional Information
Anet A8 Printer with RAMPS 1.4/Arduino Mega 

I'm using Cura 4.4.1 with 2.0.x bugfix firmware from about a week ago. I'm printing via USB, and have printed several 4+ hour long prints without issue. The current project is closer to 20hrs, so I'm not sure, but maybe it's memory related?

**Comment by thisiskeithb** [comment]
You don't have `FILAMENT_RUNOUT_SENSOR`, nor `ADVANCED_PAUSE_FEATURE` enabled, so perhaps it's your slicer.

Can you zip up & post some sliced .gcode that exhibits this behavior?

Also, it wouldn't hurt to update to the latest `bugfix-2.0.x` since it's updated daily.

**Comment by psavva** [comment]
Try with a different slicer and see if you can reproduce the issue.

**Comment by Aetoc** [comment]
[CFFFP_Body.zip](https://github.com/MarlinFirmware/Marlin/files/4309102/CFFFP_Body.zip)

This is the model it started happening with. It seems that it was only doing it during the printing of the raft. Eventually I went to bed and it continued overnight with no issues. I can't say 100% that it stopped pausing once the raft was completed, but it seems like it. 

I'm now printing an 8hr long print, and it has already paused once on the raft, and it's been 15 mins. I'll update if it continues. For the print following this one, I'll try a different slicer and see if that changes anything.

**Comment by Sewyboowy** [comment]
Interesting, I am having a similar issue although I'm not using a raft. Let us know how it goes

**Comment by thinkyhead** [comment]
Be sure to test the latest [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) so we're all on the same page.

**Comment by tlhintoq** [comment]
Stop printing by USB.  Slice and save to SD card.
If it still happens there it might be an issue.  Otherwise its the USB or your computer.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
