### ISSUE TITLE
[BUG] Click to resume... on sd print Marlin 2.0.4.4 bugfix

### ISSUE THREAD

**Issue by Hagbard-84** [MarlinFirmware/Marlin#17106]
### Bug Description 
At the end of a SD print i get Click to resume... on the lcd screen

### My Configuration
Cheetha 1.1 ender 3

Marlin 2.0.4.4 bugfix.   

//#define RGB_LED
//#define RGBW_LED is disabled

and ware did the JERK  settings go? only showing one setting

problem not preset on 2.0.3

**Comment by Hagbard-84** [comment]
#

**Comment by ghost** [comment]
Same error to me.
SKR pro v1.1 + Marlin 2.0.4.4
and 
SKR v1.3 + Marlin 2.0.4.4
![0-02-0a-dc5610df03ce23b3e61f98e204a5cb5665ac3fafa78f31a898ad964e8162e7f0_91ca69f6](https://user-images.githubusercontent.com/48370718/76297308-ed6b7080-62b7-11ea-953a-bdd3c30fcd00.jpg)
![0-02-0a-798522095091a547fe43e0311d8321915a0d52ed49316af6d92fe1a16d5dbff1_2028a4da](https://user-images.githubusercontent.com/48370718/76297320-f0666100-62b7-11ea-88ef-c455e04511a8.jpg)

**Comment by ellensp** [comment]
See https://github.com/MarlinFirmware/Marlin/issues/16808
Is fixed in bugfix, just missed the 2.0.4.4 release.   Supposedly

**Comment by thinkyhead** [comment]
Other end-of-SD issues are patched in bugfix as well. Expect 2.0.5 to be out soon.

**Comment by bigtreetech** [comment]
https://github.com/MarlinFirmware/Marlin/blob/1f55986ed2aeb9db30b2438b125aa8ce64a5f09f/Marlin/src/MarlinCore.cpp#L441
In fact, the latest bugfix also has this issue. after printing, it will execute
"M31",
"M77" and then
"M0 Q1 S1800" or "M0 Q1 S60", and then it will pause
LCD display "Click to resume" until "1800" or “60” seconds, then it will  continue @thinkyhead
