### ISSUE TITLE
Peltier cooling PID control for Laser

### ISSUE THREAD

**Issue by eTeReBeReTe** [MarlinFirmware/Marlin#17102]
I  would like to use marlin with my CO2 laser engraver. For laser tubes decent cooling is required. I am experimenting to solve the cooling, with 2 piece of TEC1-12710 peltier elements. (I plan to upgrade 4 piece)

I have connected the Peltier elements to the HOTEND output and use its thermistor, as feedback.
I managed to achived reversed working(cooling) of PID loop using (-)neg sign before the P. I. D. parameters in the config file.

At the moment the PID autotune functions only work with (+) pos values. (in DIRECT PID mode, Heating). I would like to use autotune PID for cooling as well.

Is it possible to improve the current FW with a new featre which is related to the driection of PID controller?

My second point is related to PWM settings of heaters/fans. As I saw in config for Hotends and BED only software pwn is available, and there is an option to set the scaler for higher frequency, but as I understand each freq doubling is cost one bit resolution.

Is there a way to add settings to use HW pwm with PID controller? I mean for example set the BED pwm to HW PWM and use that for this cooling control purose. Or add PID controlling loop for the FANS which can use HW PWM at the moment.

This HW PWM / higher freq pwm is important, beacuse of I would like to use a "BUCK converter like filtering" for Peltier coolers, to decrese the loosses in the heater elements. For ~8Hz frequeny the componenents would be very large. With higher frequency pwm I would use more compact size. 

 
![peltier](https://user-images.githubusercontent.com/52998078/76223372-ab8cec80-621b-11ea-8d7a-5680e923863f.png)

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
