### ISSUE TITLE
[BUG] "Media Removed" with SD card and "Media Inserted" with no Card Marlin 2.0 Bugfix

### ISSUE THREAD

**Issue by JoInfoTech** [MarlinFirmware/Marlin#17105]
If i plug SD card the msg "Media Removed" shows, if a remove it the msg "Media Inserted"  Show on LCD. 

The #define SDSUPPORT uncomment

I tried comment
#define SD_DETECT_INVERTED
nothing

i tried uncomment 
#define SPI_SPEED SPI_HALF_SPEED
 #define SD_CHECK_AND_RETRY
also not work

The Marlin i'm trying is v20004
https://github.com/JoInfoTech/Marlin

I have Arduin Mega 2580 With RAMPS 1.5
5xA4988
LCD is a REPRAP_DISCOUNT_SMART_CONTROLLER (2004)

i just download the bugfix2.0, change like my old marlin v20000 
If i send me "old" marlin  everything works fine.

**Comment by leytanelectronics2** [comment]
im having a similar problem but mine is saying no media.

**Comment by thinkyhead** [comment]
SD_DETECT_INVERTED is now SD_DETECT_STATE (HIGH). Please update your configuration.
