### ISSUE TITLE
Target Bed Temp = 368° after startup on REPRAP_DISCOUNT_SMART_CONTROLLER

### ISSUE THREAD

**Issue by SebDE** [MarlinFirmware/Marlin#1711]
After flash this firmware with minimal configuration ( Board: RAMPS_13_EFB, LCD: #define REPRAP_DISCOUNT_SMART_CONTROLLER) the printer displays 368° bed temperature on lcd and starts to heat the bed. Hardware seems to be okay cause if I flash my old firmware (1.0.0) everything works fine.

**Comment by emartinez167** [comment]
Temperature management really seems to be completely screwed. I turned my printer and didn't realize the extruder started heating by itself! If I hadn't checked the temp graph by accident, I would have now a burnt house! This needs serious attention!!!

Regards,

Ernesto

**Comment by scotty1024** [comment]
I saw the same temperature with RAMPS_13_EFB if I had the thermistor set to -1 which had it using a non-existent thermocouple which apparently reads as ~368C.

**Comment by oysteinkrog** [comment]
I got this problem as well, was very unexpected that it started heating just after flashing!

**Comment by oysteinkrog** [comment]
Latest dev is certainly acting very strange, the target temp fluctuates randomly (when scrolling in menu?).

**Comment by oysteinkrog** [comment]
Rebasing my config back to before 410f64782acb30083ae8abfb7f4719061bf1983d fixes it (though I now get the max bed temp error instead).

**Comment by jabe-dot-com** [comment]
Yep, Same Problem here too. My bed starts heating up on startup of the ramps board, and my lcd claims that it is trying to heat to 365°. Odd.

**Comment by thinkyhead** [comment]
Please check if #1714 fixed the issue.

**Comment by AHHams** [comment]
Please also correct same in temperature.h

**Comment by thinkyhead** [comment]
Done. So test the latest code and let me know if all is well.

**Comment by thinkyhead** [comment]
Thank you bleeding-edge testers for your feedback! Temperature and leveling bugs have existed for a few days as a result of some comprehensive overhauls to the code.

Remember that the Development branch _will have bugs_, and that yes, your printer _can start fires_! Don't leave your printer unattended, especially with the latest code – for which **you are the tester**.

I look forward to your feedback on the latest fixes, applied even before I've had my breakfast…

**Comment by AHHams** [comment]
Temperature reading and controls work fine again for me. Thanks for the great work!
