### ISSUE TITLE
[BUG] due and re-connecting serial connection

### ISSUE THREAD

**Issue by maukcc** [MarlinFirmware/Marlin#17118]
### Bug Description

serial connection over octoprint to bugfix2 is OK. when disconnecting and re-connecting, there is no more connection possible.

### My Configurations

bugfix2(on due) connected to octoprint over SERIAL_PORT 2

### Steps to Reproduce

connect to marlin
manually disconnect
re-connect to marlin

**Expected behavior:** [What you expect to happen]
re-connection will happen

**Actual behavior:** [What actually happens]
re-connection does not happen

#### Additional Information
re-connection only possible after the reset button on the due is pressed.

**Comment by thinkyhead** [comment]
I've noticed that some boards (LPC176x) don't care when you connect or disconnect. They just keep the connection alive as if you never connected or disconnected.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
