### ISSUE TITLE
GCODE_MACROS (i.e. M810 - M819) only execute once

### ISSUE THREAD

**Issue by tmartin007** [MarlinFirmware/Marlin#17125]
When defining a macro with M810, e.g. (a very simple example):

M810 G0 X30 | M400 | Y30 | M400 | Z30 | M400

it will only execute completely on its first invocation (i.e. M810).
On any subsequent invocation, only the first command (i.e. G0 X30) 
will be executed.

Steps to Reproduce:

1) Use Marlin 2.0.4.4 on a BigTree SKR Pro 1.1V with  "GCODE_MACROS" enabled in Configuration_adv.h (zipped configuration files attached) 
2) define a macro like this: "M810 G0 X30 | M400 | Y30 | M400 | Z30 | M400"
3) invoke the macro by issuing "M810"
4) observe the correct execution of the macro
5) issue e.g. "G0 X1 Y1 Z1" and observe all 3 axis to move to (e.g.) "1"
6) invoke the macro again by issuing "M810"
7) observe that only the first command of the macro (i.e. "G0 X30") is executed
8) repeat 5) to 7) as often as you like

**Comment by tmartin007** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4319851/Configuration.zip)

**Comment by thinkyhead** [comment]
@tmartin007 — Thanks for the report! I can immediately guess why this is happening. I'll post a patch shortly.

**Comment by thinkyhead** [comment]
Ok, should be working now!

**Comment by tmartin007** [comment]
I do confirm - this is fixed and works beautifully now. 
Thank you very much!

ps: Looking forward to your comments on #17128
