### ISSUE TITLE
[Q] Important ifdef blocks of some features

### ISSUE THREAD

**Issue by rmedeiros** [MarlinFirmware/Marlin#17124]
Hello,
First of all I would like to say that I am not sure if this is the correct place to ask this question, but it is not a user-support question so I will post it and wait for an answer. 

We are doing a research about how to help new developers understanding configurable/variable features in OSS developed with C-preprocessor (i.e. ifdef blocks).
Many researches proved that some features are scattered through many files and this situation hinders feature comprehension because is difficult to developers to know from where they should start.

We plan to mitigate this problem adapting the concept of key classes: **“Usually, the most important concepts of a system are implemented by very few key classes which can be characterized by the specific properties. These classes, which we refer to as key classes, manage many other classes or use them in order to implement their functionality. The key classes are tightly coupled with other parts of the system”**. We think we can move this concept to **“key ifdef blocks”**. Our theory is that the most important concepts of a feature are implemented by few ifdef blocks. Therefore, if we can give developers a good starting point (i.e. a key ifdef block) for understanding a concrete feature, (s)he would be able to comprehend the feature faster. So, we aim at identifying those ifdef blocks that are central for understanding the feature using different kind of measurements.

In order to validate this theory, first, we need to identify those blocks with expert-base opinion to then, compare these blocks with those obtained from the results of our measurements. However, we are not expert on Marlin so we are not able to identify which would be the key ifdef blocks for some features. We would be very grateful if the community can tell us which are the most important ifdef blocks (if they exists) for the following features:

• ADVANCED_PAUSE_FEATURE
• NOZZLE_PARK_FEATURE
• NOZZLE_CLEAN_FEATURE
• HOST_KEEPALIVE_FEATURE
• HAS_TEMP_SENSOR
• HAS_BED_PROBE

With a couple of blocks per feature would be enough.
Thank you in advance!

**Comment by thinkyhead** [comment]
Marlin uses `#if` with `ENABLED`, `DISABLED`, and various other macros rather than simply using `#ifdef` because this permits its options to be disabled from a Makefile or command line by simply defining the option as 0 or `false`.

While Marlin does use the preprocessor extensively, it is probably not an exemplary case for the use of the C++ preprocessor. Within Marlin its use is a necessary compromise to keep the binary as small as possible — so that a base build can fit within 64K and a full-featured build can fit within 256K.

Does Marlin have "key #ifdef blocks" at all? Many features of Marlin are decentralized. The closest we might have to "key" #ifdef blocks will be found in the `src/gcode` and `src/features` folders.

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
