### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by ElTel15** [MarlinFirmware/Marlin#17137]
<!--It has been suggested that my problem may be a bug.  I have tried to find solutions on several reprap and kiwi forums as well as other places and found no solution.

Firmware - Marlin Bugfix2.0.x
1 connect pronterface
2  load sliced gcode file (Cablechainx4.gcode)
3  send to rpinter.

**Expected outcome:**
Satisfactory print

**Actual outcome:**
Printer attemts to begin the print at 7.25 mm (approx, measured by feeler gauges) above print bed.

I have configured Marlin to set the noxxle just above the heat bed and it homes to that position.  I sliced my model (Drag chain links) in Slic3r and then used Pronterface to control my self built Mendel / i3 printer.

I have previously printed this model when I first built the printer some years ago when bed levelling was done manually with microswitch min_endstops.  I have upgraded machine after period on non use with Marlin Bugfix2.0.x and ABL with an inductive probe.  The machine homes properly but when I start to print the nozzle hovers above the bed by about 7.25 mm and attempts to start print.  The Slic3r gcode directs the z axis to 0.3 in it's initial G1 code.  I am completely at a loss as to how to explain this behaviour and would be grateful for any help.  It has been suggested that it is a possible Bug in Marlin.

I am unable to attach my config.h or my model gcode or stl files where should I do that?

**Comment by ellensp** [comment]
Please close this empty job.
