### ISSUE TITLE
[BUG] Compiler error SERIAL_ECHOLNPAIR(MSG_FREE_MEMORY, freeMemory(), MSG_PLANNER_BUFFER_BYTES

### ISSUE THREAD

**Issue by angelux3d** [MarlinFirmware/Marlin#17136]
### Bug Description
compilation error in MARLIN 2
Some help Please.?

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
1 download Marlin2.0
2. [Second Step]
downloa Marlin 2bugs 20..x
3. [and so on...]
Altered confg.h and throw this error.
**Expected behavior:** [What you expect to happen]
0 errors
**Actual behavior:** [What actually happens]

#### Additional Information
![Captura de pantalla (89)](https://user-images.githubusercontent.com/49324188/76497213-58808880-6419-11ea-9278-c2df7b1e4fcf.png)

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ellensp** [comment]
Without config files, an educated guess is you changed serial port to something not possible on your controller. NB. This is the serial port on the controller, not related to the serial port on the pc.
You **REALLY NEED** to attach configuration files.

**Comment by angelux3d** [comment]
OK thank you i am stucked here 3 days and dont know what to do.
[config angel.zip](https://github.com/MarlinFirmware/Marlin/files/4325272/config.angel.zip)
These are, i dident touch, advanced file.
Thanks

**Comment by ellensp** [comment]
Provided configuration files compiles fine on platformio.

**Comment by ellensp** [comment]
What version of arduino IDE are you using?

**Comment by thinkyhead** [comment]
At this time it is recommended that you use https://marlinfw.org/docs/basics/auto_build_marlin.html with Visual Studio Code to build and upload Marlin 2.0.x.
