### ISSUE TITLE
Power Supply Control feature

### ISSUE THREAD

**Issue by Ski3d** [MarlinFirmware/Marlin#17134]
Hello!,

I would like to see if i could get an auto shut off feature like below, I use BTT Relay V1.2 on my 3d printer and it controls the mains power to the power supply and also power to the SSR. So in my case if my SSR got stuck in the on position, Marlin could cut power to the whole printer or even just that SSR.

    Power Supply Control

//#define AUTO_POWER_OFF_BED_TEMP 130 // (°C) Turn off PSU if over this temperature
//#define AUTO_POWER_OFF_HOTEND_TEMP 300 // (°C) Turn off PSU if over this temperature
![canvas](https://user-images.githubusercontent.com/61573573/76476795-9eb5f780-63d9-11ea-9d31-f89bd4409df0.png)

Or

Another idea if we could add a pin to Thermal Runaway Protection to do the same thing, as if a mosfet got stuck on.

#define THERMAL_PROTECTION_HOTENDS // Enable thermal protection for all extruders
#define THERMAL_PROTECTION_BED // Enable thermal protection for the heated bed
#define THERMAL_PROTECTION_CHAMBER // Enable thermal protection for the heated chamber

**Comment by mvcelicka** [comment]
I would like to vote for this. In comunity discussion I can see more an more problems with mosfet BTT SKR v2 - mosfet is burned, printer is reaching max temp configured in firmware, but cannot switch of heating as control device is dead - very dangerous. With mentioned relay, this can be easily solved, if printer can send PSU off signal when thermal runaway or max temperature is reached. Also writing some error log to SD card would be nice (with error handled by shutdown).

**Comment by ManuelMcLure** [comment]
This is already available. If you enable `PSU_CONTROL` whatever pin is defined as `PS_ON_PIN` in the pins file will be controlled by Marlin. If there is a thermal runaway the `kill()` function will turn this pin off. Also, even without `PSU_CONTROL` enabled you can define `SUICIDE_PIN` as yet another pin that will be triggered in case of `kill()` being called.
These two pins plus the existing thermal runaway protection will provide what you are looking for.

**Comment by mvcelicka** [comment]
> 
> 
> This is already available. If you enable `PSU_CONTROL` whatever pin is defined as `PS_ON_PIN` in the will be controlled by Marlin. If there is a thermal runaway the `kill()` function will turn this pin off. Also, even without `PSU_CONTROL` enabled you can define `SUICIDE_PIN` as yet another pin that will be triggered in case of `kill()` being called.
> These two pins plus the existing thermal runaway protection will provide what you are looking for.

Thanks for this info. I was searching some Marlin documentation and was not able to find info about. I will test it. 
Thanks again!

**Comment by slowbro** [comment]
Indeed, `kill()` calls `minkill()` which has this line:

```cpp
  TERN_(PSU_CONTROL, PSU_OFF());
```

So, this is implemented via thermal runaway protection.
