### ISSUE TITLE
Firmware Retract Settings Per Extruder

### ISSUE THREAD

**Issue by jasonhamilton** [MarlinFirmware/Marlin#17132]
I'm trying to print PLA and PVA using a dual extruder and the firmware extract feature but it doesn't appear you can change the retract setting per extruder using the M207 command.  

The problem I am running into is that I need the PLA swap retract to be around 6mm, otherwise the all metal hot end starts having issues with clogging.  On the PVA, I need the swap retraction to be around 12mm otherwise it oozes everywhere.

Has anyone else already implemented this?  If not, would this be something others would use?  I'm happy to add this feature and push any changes if it's something that would help others.   It seems logical to be able to specify an extruder index using [T<index>] in conjunction with the M207 command (similar to the M92 command).

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
