### ISSUE TITLE
Error in stepper.cpp

### ISSUE THREAD

**Issue by SebDE** [MarlinFirmware/Marlin#1715]
stepper.cpp: In function 'void __vector_17()':
stepper.cpp:158:46: error: expected ';' before ',' token
     #define Z_APPLY_STEP(v,Q) Z_STEP_WRITE(v), Z2_STEP_WRITE(v)

To Fix change line 158 in stepper.cpp from:
# define Z_APPLY_STEP(v,Q) Z_STEP_WRITE(v), Z2_STEP_WRITE(v)

to:
# define Z_APPLY_STEP(v,Q) {Z_STEP_WRITE(v); Z2_STEP_WRITE(v); }

**Comment by thinkyhead** [comment]
#1716
