### ISSUE TITLE
[BUG] Flash-based EEPROM no longer works on SKR 1.3

### ISSUE THREAD

**Issue by thisiskeithb** [MarlinFirmware/Marlin#17179]
### Bug Description

I saw that an `eeprom.dat` file was generated on my SD card as if I switched to using `SDCARD_EEPROM_EMULATION` with the latest bugfix-2.0.x (a662079) on an SKR 1.3 build.

Reverting to `2.0.4.4` allows flash-based EEPROM to work correctly again (and as expected, no `eeprom.dat` file is generated).

In https://github.com/MarlinFirmware/Marlin/issues/17172, it was suggested to add the following to `pins_BTT_SKR_V1_3.h`:
```cpp
// Use one of these or SDCard-based Emulation will be used
//#define SRAM_EEPROM_EMULATION   // Use BackSRAM-based EEPROM emulation
#define FLASH_EEPROM_EMULATION  // Use Flash-based EEPROM emulation
```

This doesn't compile with `FLASH_EEPROM_EMULATION` enabled in `bugfix-2.0.x` (a662079): [Full error log](https://pastebin.com/YdVSL9vw).

`SRAM_EEPROM_EMULATION` compiles fine, but also generates an `eeprom.dat` file on the SD card and I get a "No EEPROM" error when sending `M500` without an SD card inserted.

### My Configurations

`2.0.4.4` configs with flash-based EEPROM working correctly:
[myskr13-Marlin-2044.zip](https://github.com/MarlinFirmware/Marlin/files/4336070/myskr13-Marlin-2044.zip)

`bugfix-2.0.x` (a662079) configs that use SD card/`eeprom.dat` no matter what:
[myskr13-Marlin-bugfix-a662079.zip](https://github.com/MarlinFirmware/Marlin/files/4336071/myskr13-Marlin-bugfix-a662079.zip)

### Steps to Reproduce

1. See above.

**Expected behavior:** Flash-based EEPROM to work like it did in `2.0.4.4`

**Actual behavior:** SD card-based `eeprom.dat` is used no matter which option I choose.

**Comment by Marlor** [comment]
Can confirm `#define FLASH_EEPROM_EMULATION` in `pins_BTT_SKR_V1_3.h` gets a compile error.
But setting it in `Configuration_adv.h` compiles fine and is working as intended, no `eeprom.dat` etc

**Comment by thinkyhead** [comment]
What is the best choice for EEPROM fallback? There seems to be some question whether it's better to use the onboard SD when available, versus something like Flash-based. What should the order of preference be?

Previously, you couldn't select anything other than `FLASH_EEPROM_EMULATION` for `LPC1768` and yet there was recent work on the SD stuff.

**Comment by thinkyhead** [comment]
See #17184
