### ISSUE TITLE
SKR 1.4 Eprom Failed

### ISSUE THREAD

**Issue by Neme77** [MarlinFirmware/Marlin#17177]
After compiling and configuring the various options for my hardware and having obviously enabled the support for writing to the eprom, it is impossible to write on it.
I attach the Configuration.h and
Configuration_adv.h
Mainboard Bigtreetech SKR 1.4
Compiled with VSC
Tested with Marlin 2.0.5 bugfix and Marlin 2.0.5
[Configuration file.zip](https://github.com/MarlinFirmware/Marlin/files/4335679/Configuration.file.zip)

**Comment by thinkyhead** [comment]
Yeah, EEPROM fallback in 2.0.5 became SDCARD for the LPC boards and now we know this isn't the best choice. While fine for some boards, for most it seems better to use `FLASH_EEPROM_EMULATION`. So, for now you can add this line to your `Configuration.h` file:
```cpp
#define FLASH_EEPROM_EMULATION
```
And this will be the default again in 2.0.5.1.
