### ISSUE TITLE
Mixing Extruder and SKR Pro 1.1

### ISSUE THREAD

**Issue by DenisFerrero** [MarlinFirmware/Marlin#17185]
Hi everyone, I'm rebuilding my Delta and I wanted to mount a Diamond Extruder, I'm using an SKR Pro 1.1. I want to change the motor by the console to check if that can work. If I try to move E0 it works very fine, but when I change motor (for example from E0 to E1) and I try to move it, my board, after some second, reboots as nothing happened. I change the motor with this command:

- `T1` to change the motor to E1
- `M302 P1`, to disable the prevent cold extrusion
- `G92 E0`, to reset the position of the motor to 0

and then I send the command to move it

I got these few commands in the past when I was trying to do it using a Ramps 1.4, and that works properly. Anyone can help me? Am I doing something wrong? Or many I just cannot switch to other extruders to move the motor? I'm using A4988 driver (1/16) for all 6 motors and they work very well and don't make any noises. I was worried about I cannot use them like is being said here https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/issues/58. I attach my [Configuration](https://github.com/MarlinFirmware/Marlin/files/4340425/Configuration.zip) here thanks for your help.

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
