### ISSUE TITLE
Err: EEPROM VERSION

### ISSUE THREAD

**Issue by iMeeHz3D** [MarlinFirmware/Marlin#17219]
Hi, i'v been install the new marlin 2.0.5.1 today.

I don't know if i have do an error during the codage, but i have an error when i start my 3D printer ! 
The message is visible in the same place of a thermistance error.

I think it's not annoying for print but i haven't tested. 

I want to know if i'l alone to have this problem ! 

Thank

**Comment by GMagician** [comment]
Try with M502 & M500

**Comment by yonutix** [comment]
What is M502/M500 ?

**Comment by ellensp** [comment]
3D printers 101: They only do what you tell them to do. The language they use is called g-code.
see https://marlinfw.org/meta/gcode/ where you can look up what the gcodes M500 and M502  
You send the printer these gcodes and it does very basic things, move, home, heatup save settings etc

**Comment by djamelfel** [comment]
Hello @iMeeHz3D , 
I just made the update too and get the same behavior than you.

Did someone know why my printer is complaining and how to solve this without doing any m502 & M500.

Thanks

**Comment by randellhodges** [comment]
The structure of the stored data changed between versions. You cannot solve it without doing an M502/M500.

If you have the .bin file for the old version, you can try flashing back to the old version, then restart and if you don't have the error, run M503 and copy those settings somewhere. Then flash the new firmware, run M502/M500 and then M503 and compare the results with what you saved before and change whatever you need to change.

**Comment by djamelfel** [comment]
Thanks you for the explaination, it's clear and all good :)

**Comment by thinkyhead** [comment]
I've just patched `bugfix-2.0.x` EEPROM error handling in a way that (hopefully) improves it.
