### ISSUE TITLE
[BUG] Fine tune mesh.  Switching Nozzle servo detached, no reference.

### ISSUE THREAD

**Issue by c3D-Dan** [MarlinFirmware/Marlin#17225]
### Bug Description
Servo for switching nozzle is deactivated during Fine tune Mesh operation as selected from the UBL menu.  This means no suitable reference point (nozzle to bed) can be used for confirming or fine tuning the mesh.

### My Configurations

[Marlin-conf.zip](https://github.com/MarlinFirmware/Marlin/files/4362206/Marlin-conf.zip)

### Steps to Reproduce

From LCD - Motion > UBL > Step by Step > Fine Tune Mesh

**Expected behavior:** Nozzle servo to remain in either T0 or T1 position throughout the fine tune process

**Actual behavior:** Nozzle servo is active for the first mesh position ONLY.  Upon confirming height with encoder for first position, Z raises, Nozzle Servo deactivates, gantry moves to next grid position.  As nozzle servo has deactivated, there is now no useful reference for fine tuning (distance between nozzle and bed).   Servo cannot be reactivated with Gcode from host during this process.

#### Additional Information

As soon as a blocking move is called, servo deactivates.  As a test, commenting out all blocking moves in ubl_g29.cpp, servo remains active.    Something to do with blocking moves?

**Comment by boelle** [comment]
@c3D-Dan is issue gone?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
