### ISSUE TITLE
[BUG] (Toolchange + ubl) Z axis not resumed perfectly after toolchange(on singlenozzle)

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#17229]
Video on youtube 
https://www.youtube.com/watch?v=YXJ7z3-pArs

- SINGLE NOZZLE + UBL on + (Z RAISE or not , Park or Not )

- After homing , with a measurement tool

- Each tool change , raise z axis by the amount of UBL ,  increment this amount each toolchange called and never resume the exact origin position, after some tool change the head have too much offset and print is dead
- No bug with UBL off

- My Help
If I enable SINGLE NOZZLE on the branch below  , bug disappear. See Line 869 in toolchange cpp

```cpp
#if HAS_LEVELING && DISABLED(SINGLENOZZLE)                         
   // Set current position to the physical position
   TEMPORARY_BED_LEVELING_STATE(false);
#endif
```

No bug in all situation with G1 Z1 /n  G1 Z-1, or  G10/G11

**Comment by thinkyhead** [comment]
The `TEMPORARY_BED_LEVELING_STATE(false)` line is equivalent to this:
```cpp
const bool tbls = planner.leveling_active;
set_bed_leveling_enabled(false);
```
 …and then at the point where `tool_change` exits it causes this to be done:
```cpp
set_bed_leveling_enabled(tbls);
```
When leveling is enabled / disabled, under most systems the Z position is immediately corrected. With U.B.L. it might require an extra step (such as a zero-length move) to prime the Z offset when leveling is enabled in the same spot.

To narrow down the issue we will need to add some logging and examine the details. In the meantime, you can try replacing the `TEMPORARY_BED_LEVELING_STATE` with the code described above to see if it makes any difference. If it does, this would indicate a possible problem with `TEMPORARY_BED_LEVELING_STATE`.

It would also help to see if this same issue occurs with ABL-Bilinear.

If the problem does not go away then we have to examine the way Z correction is applied when turning UBL on and off.

**Comment by studiodyne** [comment]
@thinkyhead 
Don't forget , I've a SINGLENOZZLE printer , but i have no idea if the bug exists on other configuration. 
But the question is why ' SINGLE NOZZLE ' is disabled and other configuration not ?
I have enabled this branch and all works fine

```cpp
#if HAS_LEVELING                          
   // Set current position to the physical position
   TEMPORARY_BED_LEVELING_STATE(false);
#endif
```

**Comment by McUtty** [comment]
Hallo,

I thing i have the same problem.
After toolchange the Z Axes don't come down.
If i print a part with every tool his own layer, there is no problem. In gcode is a Zxxx command after toolchange.
If i print a part with more then one tool a layer, at fierst time, there is no Zxx in gcode, only Xxx, Yxx Exx, but in second layer. Then the X-Axes comes down. There is a Zxx command for the next layer.
If i manualy change the tool, it don't comes down.
