### ISSUE TITLE
Sensor-less homing problem 

### ISSUE THREAD

**Issue by Talha909** [MarlinFirmware/Marlin#17247]
I have SKR 1.4 Turbo and TMC 2130 SPI. I used the Marlin 2.0.5.1. I configue the files and upload the firmware. I have problem with the sesnorless homing. Its not working. I did not installed the end stops. 
![Capture1](https://user-images.githubusercontent.com/29024390/77249951-7d20ff80-6c66-11ea-84de-b9e71a2ac3f8.JPG)

**Comment by Geitde** [comment]
Are you sure you set the soldering pad on the step sticks right?

it is hard to say what is going on without seeing the config files you used.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
