### ISSUE TITLE
PIDTEMPBED doesnt reach correct temp.

### ISSUE THREAD

**Issue by softfoot** [MarlinFirmware/Marlin#17250]
I am running v2.0.5 bugfix build on a Geeetech I3 Pro C.

I previously used PIDTEMPBED under 1.1.8 and it worked well but under 2.0.x if I set a bed temp of 50c it only reaches 40c !! That is with the default settings or settings from an M303 tune.

Dave

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
