### ISSUE TITLE
[BUG][bugfix-2.0.x] M114 Reports steps count twice

### ISSUE THREAD

**Issue by vajdera** [MarlinFirmware/Marlin#17255]
### Bug Description

M114 Command reports as usual but then after newline reports *Count* (steps) second time.

### My Configurations

Default Configuration.h and Configuration_adv.h

### Steps to Reproduce

Branch bugfix-2.0.x commit e7a9f1737

Send M114 command

**Expected response:** 
<pre>
X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
ok
</pre>

**Actual response:**
<pre>
X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
 Count X:0 Y:0 Z:0
ok
</pre>

#### Additional Information

Reason for this behaviour is the
`stepper.report_a_position(planner.position);`
at line 253 in  *Marlin/src/modue/motion.cpp*.

I am not sure but this doesn't look like desired behaviour. If the second report is sth like steps from planner, maybe it should be labelled differently, and on the same line as rest of command output.
In addition output like that confuses BIGTREETECH TFT 24 whose parser is rather simple and treats the second line as regular position in mm.

**Comment by thinkyhead** [comment]
Thanks for the report! This is now fixed.
