### ISSUE TITLE
[Question] Bad position got by repetier

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#17269]
It's some time I get weird behaviour with repetier, when moving axes before homing.

This evening I noticed something really weird. After an echo by Marlin of

> 22:13:46.339 : X:-4.00 Y:-4.00 Z:0.05 E:0.00 Count X:-1600 Y:-1600 Z:80

repetier reports as position:
   X:-1600 Y:-1600 Z:80

Am I wrong or some time ago count values were reported with an @ ?

**Comment by GMagician** [comment]
may be duplicated of #17255...investigating

**Comment by thinkyhead** [comment]
Patched.
