### ISSUE TITLE
bed thermistor reads 0°C after latest firmware update

### ISSUE THREAD

**Issue by ovparidon** [MarlinFirmware/Marlin#1726]
On my ramps 1.4 board the bed thermistor reads 0°C, when I revert to a previous firmware the temperature readout is fine.

**Comment by Natealus** [comment]
Did you check if the bed pin was still the same between the different firmware versions?

**Comment by thinkyhead** [comment]
There have been a few changes today and may be a few more, so try the latest code tomorrow (Monday) and see how it fares.

**Comment by ovparidon** [comment]
I will give try the latest firmware this evening and let you know. Thanks

**Comment by ovparidon** [comment]
Thermistor readout is fine again. Thank you

**Comment by thinkyhead** [comment]
:bow:
