### ISSUE TITLE
[BUG] Change Filament: printing does not resume at the right place

### ISSUE THREAD

**Issue by Bergerac56** [MarlinFirmware/Marlin#17268]
With bugfix 2.0.x (no specific version. At least the last one) Change filament seems not to work as I would expect. After a filament change, I would expect that the printer rresume at the last position in order to continue the print.

But it is not the case. Here is the result:
![mini-IMG_20200323_184532](https://user-images.githubusercontent.com/27892880/77356375-723d9c00-6d46-11ea-8ba1-6bddf85ef2d4.jpg)

After investigation, it seems related to the parameters of NOZZLE_PARK_FEATURE. More specifically: #define NOZZLE_PARK_POINT { (X_MIN_POS + 10), (Y_MIN_POS - 10), 20 }. It seems to influence the calculation of the "return" position after filament change. The above picture is a test using those parameters (default parameters of the configuration.h file ).

Even if it would be logic that those parameters would not influence the repositionning of the noozle after changing filament, it seems it does.

To see if it could be improved, I tried this: #define NOZZLE_PARK_POINT { 0, 0, 20 }  with this result:
![mini-IMG_20200323_203022](https://user-images.githubusercontent.com/27892880/77356642-00198700-6d47-11ea-8582-5c9ba99e48b0.jpg)

It is not yet perfect (very small displacement). But it is already a lot better. The error seems to be x+0.1mm, y+0.1mm 

Here are my config files: 
[config.zip](https://github.com/MarlinFirmware/Marlin/files/4371593/config.zip)

I do not know if this behavior is normal (for me it is not) and if this worked before as I never used this function before. I discover the issue after an unexpected filament runout...

Do I miss something?

**Comment by MarkMan0** [comment]
Are you sure Y_MIN_POS - 10 is correct? That would mean overt the endstop.
The stepper may time out and get disabled. Try without stepper timeouts

**Comment by Bergerac56** [comment]
@MarkMan0 I would say that I am nearly sure it is not correct (at least for my printer) But  that were the default values. I never modified those parameters until the problem with "change filament". Anyway, now that I discovered their existance, I replaced them by {0,0,20} (as my printer parks the head at 0,0)

If this causes the wrong resume, I am just puzzled why those parameters have an influence on it. My understanding is that the head would go back (provided there were no manual moves of the head) to the exact position it left for the filament change. And that, nevertheless any "home" position. 

And it does not explain why the resume is slightly shifted to a very tiny x+something, y+something. I will experiment with very small values for the park position and see if that has an influence.

**Comment by Bergerac56** [comment]
I do not believe that this was solved. 
But for me, and to avoid some friendly reminder from our friend Bo :), I adapted #define FILAMENT_RUNOUT_SCRIPT "M600" by adding the desired home position "M600 X0 Y0 Z10"
Till now it does the job. I will then close the issue.
