### ISSUE TITLE
Link to the configurations leads to an Error:404

### ISSUE THREAD

**Issue by iAMB3nFPS** [MarlinFirmware/Marlin#17289]
Hi,
as the title already suggests is it currently not possible to download the latest 2.0.5.2 configuration files because the given link leads to a dead end.
Im talking about the link found in /config:
https://github.com/MarlinFirmware/Configurations/archive/release-2.0.5.2.zip

Thanks in advance!

**Comment by masdisaster** [comment]
Same here.
Broken link

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/17322
