### ISSUE TITLE
Slow homing

### ISSUE THREAD

**Issue by PaulBadeuille** [MarlinFirmware/Marlin#1729]
Since the last update, when I home the axes, for example, X, it touches normally the endstop but when he want to touch the endstop the second time, it's very slow. Is it normal ?

**Comment by chris-bo** [comment]
You can set the speed for the second endstop hit here:

https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/Configuration_adv.h#L182

**Comment by PaulBadeuille** [comment]
Thanks a lot !
