### ISSUE TITLE
[BUG] BTT GTR V1.0 I2C EEPROM can not wtite MARLIN 2.0.5.2

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#17297]
[config.zip](https://github.com/MarlinFirmware/Marlin/files/4383553/config.zip)
![kép](https://user-images.githubusercontent.com/48370718/77586432-7accd880-6ee6-11ea-914f-3cdc5c860a91.png)
![kép](https://user-images.githubusercontent.com/48370718/77586480-92a45c80-6ee6-11ea-986e-bd7a0544ac75.png)
![kép](https://user-images.githubusercontent.com/48370718/77586739-fa5aa780-6ee6-11ea-8bfa-9bdc0e14709c.png)

Onboard 24c64.

I tried this setting too:
![kép](https://user-images.githubusercontent.com/48370718/77587038-748b2c00-6ee7-11ea-8d53-2e929ab452cb.png)

Same issue.

Flash based eeprom emualtion work fine:
![kép](https://user-images.githubusercontent.com/48370718/77587218-c338c600-6ee7-11ea-96f3-cc52bf374dd1.png)

**Comment by yavinmaster** [comment]
Have you tried doing a M502 then M500?  Different versions sometimes change the stored data so you need to do this to correctly format the EEPROM.

**Comment by ghost** [comment]
> Have you tried doing a M502 then M500? Different versions sometimes change the stored data so you need to do this to correctly format the EEPROM.

Yes i tried it.
M500 and instant reboot.

**Comment by NAPCAL** [comment]
Confirmed reboot with 2.0.5.3 as well. Note per the schematics, the 24C64 is on PH4/PH5, and the expansion I2C (J65) is on PH7/PH8. Unclear, if the code is using these pins for an I2C EEPROM. 

I tried an external EEPROM on J65 but no change. Every time a write command happens (EEPROM INT, or Save settings), the code stalls and then causes a board reboot.

**Comment by NAPCAL** [comment]
Sending a M500
SENT: M500
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
READ: echo:Error writing to EEPROM!
Error writing to EEPROM!
WARNING: Device unplugged while connected to port Disconnected.

Sending M501
SENT: M501
READ: echo:EEPROM version mismatch (EEPROM=? Marlin=V76)
EEPROM version mismatch (EEPROM=? Marlin=V76)
READ: echo:Hardcoded Default Settings Loaded
Hardcoded Default Settings Loaded

Sending M502
SENT: M502
READ: echo:Hardcoded Default Settings Loaded
Hardcoded Default Settings Loaded

When sending an M500 only errors until it reboots,

**Comment by NAPCAL** [comment]
Found the correction, the assigned pins for the on-board I2C EEPROM are not correct. When checking the Demo Marlin provided by BTT the \buildroot\share\PlatformIO\variants\BIGTREE_SKR_PRO_1v1\variant.h​ file has the correct pin assignments
```cpp
// I2C Definitions
#define PIN_WIRE_SDA            PH5
#define PIN_WIRE_SCL            PH4

and the others do not. 
 // I2C Definitions
#define PIN_WIRE_SDA            PB7
#define PIN_WIRE_SCL            PB6
```
As a test on my Marlin 2.0.5.3, I made these changes in the 
`\buildroot\share\PlatformIO\variants\BIGTREE_SKR_PRO_1v1\variant.h`
```cpp
// I2C Definitions
#if STM32F4X_PIN_NUM >= 176
  #define PIN_WIRE_SDA            PH5
  #define PIN_WIRE_SCL            PH4
#else
  #define PIN_WIRE_SDA            PB7
  #define PIN_WIRE_SCL            PB6
#endif
```
Works with M500-M504 commands, Initialize EEPROM, Store Settings, Load Settings, Restore Defaults from the display.

**Comment by ghost** [comment]
Thank you! I try this.

**Comment by ghost** [comment]
It's Confirmed.
This settings is working.
Thx.

**Comment by sjasonsmith** [comment]
I suggest leaving this open until the code is updated. This will be important to fix for other GTR users also.

**Comment by thinkyhead** [comment]
Found it anyway…
