### ISSUE TITLE
[BUG] (Marlin/config/... link broken 404)

### ISSUE THREAD

**Issue by k4my4b** [MarlinFirmware/Marlin#17314]
redirection link to the config repo is broken error 404

**Comment by iAMB3nFPS** [comment]
#17289

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/17322

**Comment by thisiskeithb** [comment]
@k4my4b Since the [config link](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/config/README.md) has been corrected, mind closing this issue?

**Comment by k4my4b** [comment]
> @k4my4b Since the [config link](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/config/README.md) has been corrected, mind closing this issue?

apologies, slipped my mind
