### ISSUE TITLE
Broken Page Link 2.0.5.2

### ISSUE THREAD

**Issue by brosskgm** [MarlinFirmware/Marlin#17312]
On your page
Where have all the configurations gone?
https://github.com/MarlinFirmware/Marlin/tree/2.0.x/config

When you click on the configurations link it goes to
https://codeload.github.com/MarlinFirmware/Configurations/zip/release-2.0.5.2
Gives you
404: Not Found

**Comment by MarkMan0** [comment]
They can be found [here](https://github.com/MarlinFirmware/Configurations).

**Comment by brosskgm** [comment]
Ok. thank you for your quick reply..
