### ISSUE TITLE
[FR] USB Serial connection, G30 Z values to 4 decimal places

### ISSUE THREAD

**Issue by qwewer0** [MarlinFirmware/Marlin#17326]
### Description

Is there a way to make G30 - Single Z-Probe - to output in 4 decimal places, instead of 2?

UBL too gives Z values in 2 decimal places to the serial connection (USB), but with G29 S-1 we get values with 4 decimal places.

**Comment by ellensp** [comment]
You realize that is 0.1 micron?  no way your machine has that much accuracy or repeatably.

**Comment by ellensp** [comment]
I don't see anything obvious in the code that limits the DP, what is probably the issue is that you would need > 10000 steps/mm  to resolve the Z position to this level.

**Comment by qwewer0** [comment]
So, it could be that the given G30 output is rounded up by the software (Pronterface, Slic3r), and that is why I only see 2 decimal places?
8mm thread rod with 2mm pitch, 1/16 micro stepp is 0.0025mm, 2.5 micron.
Probe standard deviation: 0.001375

**Comment by qwewer0** [comment]
<strike>Yes, it is a software limit. G30 gives value to 4 decimal places with Python.</strike>

I came to a conclusion too soon. G30 gives Z value in 2 decimal places, no matter if the software is Pronterface, Slic3r or Python.

**Comment by ellensp** [comment]
What are your Steps/mm for Z ?

**Comment by qwewer0** [comment]
400, but why does it matter?

**Comment by ellensp** [comment]
So I can replicate your setting, to try and see what is going on.

**Comment by qwewer0** [comment]
Ok, but I don't think it has anything to do with it, as G29 and G30 gives 2 decimal places, but with G29 S-1 It lists all the Z value to 4 decimal places. But I want the G30 values and not the UBL values at the moment.

**Comment by qwewer0** [comment]
https://github.com/MarlinFirmware/Marlin/pull/18367
