### ISSUE TITLE
Download link for the config 2.0.5.2 is broken

### ISSUE THREAD

**Issue by StephanReich** [MarlinFirmware/Marlin#17324]
### Bug Description

Download https://github.com/MarlinFirmware/Configurations/archive/release-2.0.5.2.zip not possible. You will get a 404 error after the rerouting to https://codeload.github.com/MarlinFirmware/Configurations/zip/release-2.0.5.2

**Comment by ellensp** [comment]
This has been reported numerous times. #17314 and #17289 and #17322
