### ISSUE TITLE
Skew_compensation Marlin 2.0 with bug fixes

### ISSUE THREAD

**Issue by byemi** [MarlinFirmware/Marlin#17346]
### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

I've installed Arduino 1.8.10 and trying to flash the firmware "Marlin 2.0 with bug fixes", from which I made the needed changes in Configuration.h file. I've noticed that after enabling Skew_compesation option, I'm getting a long message error in the log window ( please check attached files ).
I had a look over the internet about this error, even in the Marlin forum, but none of them fixed the problem. I've started by changing the u8glib ( which I suppose that it doesn't have anything to do ) and changing the decimal points of the "Input all length measurements". 

Looking forward for a way of removing the error.
Thank you in advance.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.
[Skew_error+Config.zip](https://github.com/MarlinFirmware/Marlin/files/4407554/Skew_error%2BConfig.zip)

**Comment by ellensp** [comment]
The error message referred to a stray \342 in the code it is most likely to have been caused by copying the code from a Web page which has Unicode characters in it.
In your Configuration.h 
In #define XY_DIAG_AC 282.70  there are invisible characters between the 7 and the 0
in #define XY_DIAG_BD 283.10  there are invisible characters between the 1 and the 0

**Comment by byemi** [comment]
Excellent. Thank you very much for your hint.
Can't understand why it happened.  The only thing I did was to remove the comment from skew_compensation and correct the values. It can be my fault.
Wish you a beautiful day.
