### ISSUE TITLE
[BUG] fadding in Z with UBL - Marlin 1.1.9.1

### ISSUE THREAD

**Issue by pemtyum** [MarlinFirmware/Marlin#17344]
**Hello!
I started using UBL to level the bed, build a DIY system very similar to BlTouch for my printer. Yesterday I finished setting everything in marlin and started printing at around 18:00.
Since then I am printing. I take out a model and send another impression right there.
Today, at about 4:00 pm, I notice a problem in the last print.
What you see in the image, the first impression is the one on the right, and in order as it deformed as it printed, up to the model on the left where you first notice the problem.**

Hola!
Empece a usar UBL para nivelar la cama, arme un sistema DIY muy similar al BlTouch para mi impresora. ayer termine de setear todo en marlin y empece a imprimir como a las 18:00.
Desde entonces estoy imprimiendo. saco un modelo y ahi mismo mando nuevamente otra impresion.
Hoy, como a las 16:00, me doy cuenta de un problema en la ultima impresion.
Lo que se ve en la imagen, la primera impresion es la de la derecha, y en orden como se fue deformando a medida que imprimia, hasta el modelo de la izquierda donde por primera vez note el problema.

![bug impresion](https://user-images.githubusercontent.com/62915538/77974259-f8b92700-72cc-11ea-945a-81a35cfff418.jpeg)

**I have a FADE HIGH = 10mm configured for the UBL.
In the G-code file I'm printing, at first I have (among other things):
G29 L1
G29 J
(i.e. I don't have a G28)
and at the end I have a code M84
thinking, I came to the conclusion, that by repeating this many times, the height Z is deviated, and when executing only G29 J, a correction of the height Z is not made!
and then during the 10mm correction, the layer height is corrected to compensate for the difference that occurs between the theoretical position and the deviation that occurs between turning the motors on and off.
Remember that in the first impression, the G29 J command made a G28 homing first, but not in the rest of the impressions.**

**So to fix provisionally, before sending a new impression, I ordered a G28, and then the file again. After this it is again printing perfect.**

**Anyway, I think the 3-point test performed by G29 J is not correcting Z's home plate.
Whether or not the engines are turned off, the correction should only be for the bed tilt, leading to a new height Z and not the actual one as it currently is.**
**I do not know if marlin is able to work with a vector normal to the plane and make corrections while ascending in Z, but I assumed that it would be so (in smotthieboard it is so)
I hope it is an easy problem to solve. Cheers!**

Tengo configurado un FADE HIGH = 10mm para el UBL.
En el archivo de codigo G que estoy imprimiendo, al principio tengo (entre otras cosas):
G29 L1
G29 J
(es decir, no tengo un G28)
y al final tengo un codigo M84
pensando, llegue a la conclusion, de que al repetir muchas veces esto, se va desviando la altura Z, y al ejecutar solo G29 J, no se hace una correccion de la altura Z!
y entonces durante los 10mm de correccion, se corrige la altura de capa para compensar la diferencia que se produce entre la posicion teorica y la desviacion que se produce entre apagar y encender los motores.
Recorde que en la primera impresion, el comando G29 J, hizo primero un homing G28, pero en el resto de impresiones no.

Por tanto para solucionar de forma provisoria, antes de mandar una nueva impresion, le ordene un G28, y luego el archivo nuevamente. Luego de esto nuevamente esta imprimiendo perfecto.

En fin, creo que el test de 3 puntos ejecutado por G29 J no esta corregiendo el home de Z
Ya sea que se apague o no los motores, la correccion solo deberia ser de la inclinacion de cama, llevando a una nueva altura Z y no a la real como es actualmente.
Desconozco si marlin es capaz de trabajar con un vector normal al plano y hacer correcciones mientras asciende en Z, pero suponia que seria asi (en smotthieboard es asi)
Espero que sea un inconveniente facil de resolver. Saludos!

**PS: I find it hard to express myself in English, so to be as precise as possible choose to use google translate. I leave versions in both languages**

PD: me cuesta expresarme en ingles, asi que para ser lo mas preciso opte por usar google translate. Dejo versiones en ambos idiomas

**EDIT: Ok guys ...
I write this at 5:00 with 4 more printed models, and with a bug that I really would not have expected.
I only noticed it on the fourth print and right now I'm sending a fifth.
Since yesterday, never turn off the printer or modify EEPROM values.
Just add a G28 command before G29 L1, to force homing, I keep using the same file on the same SD.**

EDITO: Ok muchachos...
Escribo esto a las 5:00 con 4 modelos impresos mas, y con un bug que realmente no me hubiera esperado.
Solo lo note en la cuarta impresion y en este momento estoy mandando una quinta.
Desde ayer nunca apague la impresora ni modifique valores de la EEPROM.
Solo agregue un comando G28 antes del G29 L1, para forzar un homing, sigo usando el mismo archivo en la misma SD.

![otro bug impresion](https://user-images.githubusercontent.com/62915538/78005520-12309200-7312-11ea-9f27-2da79dca1f9e.jpeg)

**It is extremely strange, it makes a correction that influences X and Y, and then it reverses, causing a curve in the vertical.
I am really surprised, I think we will have to wait a little longer for the 100% UBL or give a reset to the printer after each print, because obviously some parameters are accumulating.
At the moment I think I will move on to a more simple and proven leveling method.
Regards and thanks beforehand!**

**PS2: never clarify specific information ...
printer: FLSUN 2017 - cartesian 300x300x420 - PLA 1.75mm - nozzle 0.4mm - layer height 0.2mm - I print with a glass copper the bed and use glue stick - modify it by adding a BlTouch DIY - the model is a protector facial that is being printed in my province (tucuman-argentina) for the coronavirus issue, for donations in hospitals.
Marlin 1.1.9.1 downloaded from https://marlinfw.org/meta/download/, which actually redirects to zip download from github.**

Es sumamente extraño, hace una correccion que influye en X e Y, y luego se revierte, provocando una curva en la vertical.
Realmente estoy sorprendido, creo que habra que esperar un poco mas para el UBL al 100% o dar un reset a la impresora luego de cada impresion, porque evidentemente algunos parametros se van acumulando.
Por el momento creo que pasare a otro metodo de nivelacion mas sencillo y probado.
Saludos y desde ya gracias!

PD2: nunca aclare informaciones especificas...
impresora: FLSUN 2017 - cartesiana 300x300x420 - PLA 1,75mm - boquilla 0,4mm - altura de capa 0,2mm - imprimo con un vidrio cobre la cama y uso pegamento en barra - la modifique agregando un BlTouch DIY - el modelo es un protector facial que se esta imprimiendo en mi provincia (tucuman-argentina) por el tema del coronavirus, para donaciones en hospitales.
Marlin 1.1.9.1 descargado de https://marlinfw.org/meta/download/ , que en realidad redirige a descarga zip de github.

**EDIT3: The deformation in the fifth impression was so much that the model detached a little.
send a sixth. it was worse.**

EDITO3: la deformacion en la quinta impresion fue tanta que el modelo se despego un poco.
mande una sexta. fue peor.

![mas bugueo](https://user-images.githubusercontent.com/62915538/78006350-4789af80-7313-11ea-94ed-3376729c2180.jpeg)

**Comment by ghost** [comment]
as far as i know, 1.1.x is deprecated, but you mention you use the stable release, so... before someone else asks you if you tried marlin 2.x / bugfix 2.x, did you try 1.1.x-bugfix ? ( https://github.com/MarlinFirmware/Marlin/archive/bugfix-1.1.x.zip )

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
