### ISSUE TITLE
[BUG] K-factor Calibration Pattern Generator not working

### ISSUE THREAD

**Issue by granthworth** [MarlinFirmware/Marlin#17357]
![LA_1](https://user-images.githubusercontent.com/62972935/78090677-60847600-7390-11ea-830c-f521fd70bddb.png)
![LA_2](https://user-images.githubusercontent.com/62972935/78090679-6417fd00-7390-11ea-897a-1d9131933b2a.png)
![LA_3](https://user-images.githubusercontent.com/62972935/78090680-667a5700-7390-11ea-888a-a1dabe5a362f.png)

### Bug Description

No G-code is produced when clicking "Generate G-code" and no error explains why. Attempted the same set of settings in Chrome and Edge with the same result.

### My Configurations

See screenshots for configuration from website. 

### Steps to Reproduce

Configure settings as normal for a new filament. Even changing many settings affecting the overall size of the pattern do not fix the issue.

**Expected behavior:** gcode is produced after clicking "Generate G-code" OR an error is given explaining why no gcode can be generated.

**Actual behavior:** No response, no error, and gcode is not produced

https://marlinfw.org/tools/lin_advance/k-factor.html

**Comment by thisiskeithb** [comment]
Something was likely broken during code refactoring in https://github.com/MarlinFirmware/MarlinDocumentation/commit/5762155216bb8669ba274bd7fdaab946ea1f94ba.

**Comment by encodedLife** [comment]
I think i found the bug. Something happens on the "Use Bed Leveling" Option. 
![image](https://user-images.githubusercontent.com/18009499/78134926-3d55d700-7421-11ea-936d-8986a579fc2b.png)

if you change line 60 to this:
![image](https://user-images.githubusercontent.com/18009499/78135790-b9045380-7422-11ea-8e4a-240cb9c3d65b.png)

it'll work. I don't know that much about JS, but maybe I could help a little. :) 

EDIT: Okay guys, I tested it and it works. You need to change this one line in the k-factor.js

**Comment by jpmath54** [comment]
Same issue here.
I'm currently printing visors for COVID19 protection of my local hospital, and switched to direct drive and larger nozzle.

Please do something to fix this, so I can produce even more of them!

Regards!

**Comment by thinkyhead** [comment]
I've been playing around with the code, and last I checked it was working. I'll re-test and see where the oops fell in…

**Comment by thinkyhead** [comment]
Pushing the patch now…
