### ISSUE TITLE
[BUG] Link to configuration files is 404

### ISSUE THREAD

**Issue by thierryzoller** [MarlinFirmware/Marlin#17368]
https://codeload.github.com/MarlinFirmware/Configurations/zip/release-2.0.5.2

Gives 404

**Comment by ellensp** [comment]
Please check there is not already an issue before oping a new one.
This has been reported numerous times. #17314 and #17289 and #17322
And has been fixed https://github.com/MarlinFirmware/Marlin/pull/17322

**Comment by thisiskeithb** [comment]
It _was_ fixed, but now it's broken again.

**Comment by thisiskeithb** [comment]
New PR to fix the issue again: https://github.com/MarlinFirmware/Marlin/pull/17370

**Comment by thisiskeithb** [comment]
Fixed again 🙂https://github.com/MarlinFirmware/Marlin/tree/2.0.x/config
