### ISSUE TITLE
[BUG] (short description)SKR 1.4 turbo dual z one motor slower than other

### ISSUE THREAD

**Issue by Ndawen** [MarlinFirmware/Marlin#17363]
### Bug Description

I have a skr 1.4 turbo on corexy dual z with dual z endstops. I finally got it compiled but the motor thats plugged into ZA turns extremely slow, compared to motor plugged in E1. I've tried every suggestion I've found so far. I know its a simple config issue,but for the life of me i cant figure it out.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/4413950/config.zip)

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

home the machine 
left z motor spins faster than right making the bed uneven.
**Expected behavior:** [What you expect to happen]
Bed should travel up to endstops and self align/
**Actual behavior:** [What actually happens]
Bed travels up and a uneven level ,levels but during a print this would mess up the print/
#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ellensp** [comment]
Send the machine a M503 and look at the line starting M92  are the steps/mm the same for Z and Z2 
Whats the output of M112 look like
