### ISSUE TITLE
Linear Advance Calibration Pattern website doesn't work in Chrome

### ISSUE THREAD

**Issue by hahnpv** [MarlinFirmware/Marlin#17372]
Clicking "Generate gcode" does not generate gcode. I am not smart enough to debug javascript. 

https://marlinfw.org/tools/lin_advance/k-factor.html

Thank you,
philip

**Comment by thisiskeithb** [comment]
Duplicate of #17366

**Comment by thinkyhead** [comment]
Duplicate of #17357.
