### ISSUE TITLE
[BUG] USE_CONTROLLER_FAN does not obey the configuration parameters

### ISSUE THREAD

**Issue by dzieva** [MarlinFirmware/Marlin#17377]
### Bug Description
The fan is always on, regardless of the configuration parameters

### My Configurations
[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/4417944/Configurations.zip)

### Steps to Reproduce
After updating the firmware from version 2.01 to version 2.0.5.3 the fan is always on and at the same speed not obeying the settings:
#define CONTROLLERFAN_SPEED_IDLE 90
#define CONTROLLERFAN_IDLE_TIME 50

**Expected behavior:** [What you expect to happen]
I expected the above settings to work

**Actual behavior:** [What actually happens]
Nothing happens when the parameters are modified

**Comment by dzieva** [comment]
Something is wrong here!

![Controllerfan](https://user-images.githubusercontent.com/35209392/78305617-bfc0c280-7517-11ea-9673-66227b0be9a6.jpg)

**Comment by dzieva** [comment]
Before
![Controllerfan](https://user-images.githubusercontent.com/35209392/78311588-a4f64a00-7527-11ea-894f-6a270836facd.jpg)

After
![Controllerfan2](https://user-images.githubusercontent.com/35209392/78311595-ac1d5800-7527-11ea-8400-796b04878c4c.jpg)

It may not have been the most elegant way to do it, but it worked for me.

Please fix your code.

**Comment by boelle** [comment]
you can fix it yourself and submit a PR

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
