### ISSUE TITLE
MKS_RUMBA32+BLTouch+TMC2209 UART mode [BUG] (short description)

### ISSUE THREAD

**Issue by danielbors72** [MarlinFirmware/Marlin#17389]
If you use TMC2209 UART mode, and BLTOUCH with PD15 pin, MKS_RUMBA32 mainboard (STM32F4) will not work, it blocks right after the logo Marlin appears!

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
