### ISSUE TITLE
Sensor and Z probe offset

### ISSUE THREAD

**Issue by Talha909** [MarlinFirmware/Marlin#17383]
"Z Probe Offset inconsistent with the  Sensor LJC18A3-H-Z/BX 1-10mm Capacitance Proximity Sensor Switch NPN NO DC 6-36V 300mA and Sensor-less Homing Issue. "

The proximity of the sensor is inconsistent or may be something else. I set the Z probe off set. After that I give the print command. Then I see the nozzle is touching the bed. After that I again set the z probe off set. Then again give the command of print now the nozzle start print in the air. I only one time get the print. I always the set the z off set . Some time it stay above the bed and some time touches the bed. What should i do . 

2.  Sensorless Homing is not working when the heater is on . I Home Z axis then turn on the heater for the calibration of the sensor. After setting the probe . I auto home the X or Y. The X and Y more few m and then stop. After that I stop the heater and do the same. It home successfully. 

1. SKR 1.4 Turbo
2. TMC 2130 SPI
3 Sensor LJC18A3-H-Z/BX 1-10mm Capacitance Proximity Sensor Switch NPN NO DC 6-36V 300mA *attach on 5 volt in Z end stop)
Marlin :2.0.5.2
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4419287/Marlin.zip)

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
