### ISSUE TITLE
[BUG] Marlin 2.1 Levelspeed XY second print

### ISSUE THREAD

**Issue by roel8032** [MarlinFirmware/Marlin#17398]
After printing a second and more, products, the leveling speed is much higher. (G29). Probably G28 also. Printer: Infitary M508.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by roel8032** [comment]
> Lack of Activity
> This issue is being closed due to lack of activity. If you have solved the
> issue, please let us know how you solved it. If you haven't, please tell us
> what else you've tried in the meantime, and possibly this issue will be
> reopened.

The big survived until today. It is not to be found in the config files.
I think the software reads the: DEFAULT_MAX_FEEDRATE from configuration.h and when you repeat the print it does not. Or something like that.
#define SD_REPRINT_LAST_SELECTED_FILE is set in configuratio_adv.h

The bug appears for Anet A6 printer and the Infitary M508, at least.
The bug is to be found in code i think.

**Comment by thinkyhead** [comment]
The "max feedrate" can be changed by G-code and some slicers might decide to insert commands which do that. If it's a concern, send `M501` in between prints.

**Comment by roel8032** [comment]
You are right. Now i have M501 before G28 and G29 in the Gcode files and the problem is gone.
I have it now in the Start G-code of Ultimaker Cura Slicer.
