### ISSUE TITLE
[FR] "Adaptive" Auto Bed Leveling

### ISSUE THREAD

**Issue by inventabuild** [MarlinFirmware/Marlin#17396]
1. Can you please make auto bed leveling adaptive so I know if there is a corner on my bed that performs poorly with auto bed leveling I can create a separate front, right, back, left bed leveling zone  and add extra probes for that area?

2. It would be nice if marlin could auto-detect areas w/ high variation and add extra points to probe in that area and create a separate plane for that area when the hot end enters it to print.

**Comment by Grogyan** [comment]
Tried Unified Bed Leveling (UBL)?

**Comment by inventabuild** [comment]
Thanks Grogyan, perfect timing, I actually just started watching Chris Riley's UBL How To video on YouTube when I got your message.

It's a little bit more manual than what I had in mind, but it looks like a good solution for problem areas on the bed.

Does UBL work good for Buildtak,Prusa and other removable flexible beds or does taking these beds off and on after every print change the actual position/height of the probed points?

**Comment by inventabuild** [comment]
UBL was not the panacea I was hoping for.  As room and bed temps change the matrix loses accuracy so multiple matrices need to be juggled and it gets to be a little cumbersome for my liking.  Of course other people's mileage may vary.

I prefer bilinear bed leveling before every print and I think "Adaptive" Auto Bed Leveling is still a worthwhile feature if it can be implemented.  Spending more time probing on the larger z high-to-low delta areas and less time on more planar areas seems like better accuracy can be accomplished in shorter probe time.

P.S. How do I remove the "stale" label?

**Comment by thinkyhead** [comment]
You don't need to remove it. There is now a feature that will adapt to temperature variations. It is covered in this Chris's Basement video. https://www.youtube.com/watch?v=AjB0ZucPf9s
