### ISSUE TITLE
[BUG] Auto leveling (bilinear) always fails on first probe

### ISSUE THREAD

**Issue by grauerfuchs** [MarlinFirmware/Marlin#17390]
### Bug Description

Automatic bilinear leveling fails to operate as expected; It always fails on the first probe point.

### My Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4423518/Configuration.zip)

### Steps to Reproduce

1. Home axes (G28)
2. Begin bed leveling procedure (G29)

**Expected behavior:** 
Leveling completes on all points

**Actual behavior:** 
Leveling fails on probing point 1. The probe's LED comes on, but the printer continues lowering the gantry until it reaches Z -2.0, at which point, the nozzle is compressing the bed springs.

#### Additional Information
Leveling seems to work on other printers where the probe is not connected to the Z-Min endstop pin. (Related?) This printer uses the probe as the Z-Min endstop due to lack of available pins.
Leveling appeared to work properly with a similar configuration on another printer. That firmware was compiled with the same computer using the Arduino IDE back in January. Neither machine levels correctly with firmware compiled within the last month using PIO.

The configuration was updated to include debugging. EEPROM was wiped, the new firmware was uploaded, and the process was run for testing. The below is the resulting debug output.

[Debug output.txt](https://github.com/MarlinFirmware/Marlin/files/4423527/Debug.output.txt)

**Comment by specialmechanics** [comment]
which current state have the Z sensor on pos 1 when light show on with M119 ?

**Comment by grauerfuchs** [comment]
Thank you. I was not aware of the command's existence. That made troubleshooting this issue much easier.

I was able to identify this as hardware failure and not a fault of the firmware or libraries. The probe apparently has started malfunctioning, but on an intermittent basis that only reliably presented itself during bed leveling.

I suppose I fell for the trap of trusting that new hardware would work reliably once the first set of tests had completed successfully.
