### ISSUE TITLE
[BUG] Filament change procedure start randomly

### ISSUE THREAD

**Issue by borsegbr** [MarlinFirmware/Marlin#17428]
### Bug Description

Filament change procedure start randomly during printing when power drain is at max (psu fan go loudly)

### My Configurations
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4440672/Marlin.zip)

### Steps to Reproduce

1. Start printing
2. wait power drain is high (heating bed and nozle)
3. randomly start filament change procedure

**Expected behavior:** no filament change procedure

**Actual behavior:** occour filament change procedur

#### Additional Information

Using Geeetech a20 
marlin bugfix 2.0.x
filament pin 67 sobstitute to 66 (same issue in each pin)

**Comment by GMagician** [comment]
That seems more an electric issue than a firmware one. If power is not enough when you drain a lot of current PSU may sit and lower tension then a false filament detection may arise.
But I may be wrong

**Comment by borsegbr** [comment]
Issue seems resolve changing drive with original one a49 but i want use tmc2209 for noise , any ideas?

**Comment by thinkyhead** [comment]
> any ideas

An improved power supply may help. Measure the current at the inputs to see what's up.
