### ISSUE TITLE
[BUG] min_temp_error for thermistor_998 and 999

### ISSUE THREAD

**Issue by Moeschus** [MarlinFirmware/Marlin#17422]
### Bug Description

When trying to use a dummy thermistor (998 or 999) I get a min_temp_error "Err: MINTEMP: Bed"

### My Configurations
SKR 1.4 Turbo
https://www.dropbox.com/s/5ejxpgmmk8bllm9/ConfigFiles.zip?dl=0

### Steps to Reproduce
1. set all thermistors to 998 or 999
2. start print or set temperature of heated bed

**Expected behavior:** 
not getting this error

**Actual behavior:** 
getting this error

#### Additional Information

I'm quite sure that this is caused by this code segment in temperature.cpp

```cpp
 #if HAS_HEATED_BED

    #if TEMPDIR(BED) < 0
      #define BEDCMP(A,B) ((A)<(B))
    #else
      #define BEDCMP(A,B) ((A)>(B))
    #endif
    const bool bed_on = (temp_bed.target > 0)
      #if ENABLED(PIDTEMPBED)
        || (temp_bed.soft_pwm_amount > 0)
      #endif
    ;
    if (BEDCMP(temp_bed.raw, maxtemp_raw_BED)) max_temp_error(H_BED);
    if (bed_on && BEDCMP(mintemp_raw_BED, temp_bed.raw)) min_temp_error(H_BED);
  #endif
```

In my opinion there should be a "<" or ">" instead of the "<=" or ">=" in BEDCMP. As far as I understand, this code compares the actual thermistor reading to the min or max given in its temptable. And the dummy thermistors have only one value.

Same thing applies for the `#if HAS_HEATED_CHAMBER` section as well. For the hotends it is solved slightly different and uses a "<" instead of a "<=". 

However, I have no idea if this might cause other problems. I'm not a programmer. Seems I can't even get the "insert code" function to work properly :D

**Comment by thinkyhead** [comment]
Good catch, thanks. Your patch is applied.
