### ISSUE TITLE
[BUG] compiling error in M425.cpp (2.0.5.3)

### ISSUE THREAD

**Issue by kaibs** [MarlinFirmware/Marlin#17430]
Due to the current situation I'm digging deeper into Marlin and it's more exotic features. Yesterday I wanted to test out [Backlash Compensation](https://marlinfw.org/docs/gcode/M425.html), but I've got the following compiling error: 

`Marlin\src\gcode\calibrate\M425.cpp:50:24: error: macro "CAN_CALIBRATE" requires 2 arguments, but only 1 given
...`

Following the same for the other uses of the `CAN_CALIBRATE()` ([full error message on pastebin](https://pastebin.com/6mmWRbgy)).

It seems like the function `CAN_CALIBRATE()` was added with [#17281](https://github.com/MarlinFirmware/Marlin/pull/17281) without replacing anything, so I just removed it again, resulting in a flawlessly compiling Marlin. Now Backlash Compensation seems to be working fine for me.

Here are my current configs and the modified M425.cpp:
[bug_report.zip](https://github.com/MarlinFirmware/Marlin/files/4442804/bug_report.zip)

also the modified (and compiling) Marlin in my repo:
https://github.com/kaibs/MarlinHevo/tree/2.0.5.3

Regarding my setup:

* VS Code (1.43.2) with platformio (4.3.1)
* HyperCube Evolution based COREXY-kinematics
* BTT SKR v1.4 with TMC2130 drivers

EDIT: I've spend a little bit more time with Backlash Compensation and figured out that `//#define CALIBRATION_GCODE` also triggers errors for me. So the problem doesn't seem to be limited to M425.cpp.
The errors occur on multiple lines in `Conditionals_post.h`, all with the same message:

`Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:153:47: error: 'NORMAL_AXIS_INDEX' was not declared in this scope; did you mean 'NORMAL_AXIS'?`

again, [full message on pastebin](https://pastebin.com/9ANrFh90)

At a first glance it seems to be depending on my COREXY-config, but that's just me wildy guessing.

**Comment by setar** [comment]
I confirm the compilation problem when the #define BACKLASH_COMPENSATION option is enabled.
And i see bug_report.zip by kaibs.
The fix do repair compilation process, but disable check on AXIS_CAN_CALIBRATE : bad idea.
For example CoreXY kinematics must have only Z axis for BACKLASH_COMPENSATION.

**Comment by thinkyhead** [comment]
This is now patched. Thanks for the notice!
