### ISSUE TITLE
[BUG] MKS_Robin No Menu after boot logo

### ISSUE THREAD

**Issue by dandantsui** [MarlinFirmware/Marlin#17447]
### Bug Description

No info screen or display after boot screen.

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4454202/Marlin.zip)

### Steps to Reproduce

1. Downgrade back to 2.0.4.4 -- working
2. Try latest branch of 2.0.5.3 and other releases of 2.0.5 -- not working

**Expected behavior:** Info menu screen and lcd buttons to navigate menu

**Actual behavior:** blank screen after bootlogo

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
[https://imgur.com/a/A8EdyFJ](url)

**Comment by Miraculix200** [comment]
Try commenting out #define EEPROM_SETTINGS   and compile it again. It's probably this bug: https://github.com/MarlinFirmware/Marlin/issues/17376

**Comment by dandantsui** [comment]
@Miraculix200 thanks for the help! 

I actually just added `#define SDCARD_EEPROM_EMULATION` into my pins file and it worked fine!

Can someone please add a Pull Request for this issue?
