### ISSUE TITLE
G29 V4 P5

### ISSUE THREAD

**Issue by tonnico** [MarlinFirmware/Marlin#1744]
Hi all,

I don't have a RAMPS installed at the moment. But on my Due when I try `G29 V3 P5` or `G29 V4 P5` the printer stops when reaching the 6th point. Just a Marlin4Due-issue? `G29 V2 P5` works and also `G29 V4 P4`.

Or any idea?

**Comment by thinkyhead** [comment]
What kind of result do you see with `G29 V3 P5 D` ?

**Comment by tonnico** [comment]
Same result.
The printer stops and I can't send any new commands. Also the LCD-menu looks like when printing.

**Comment by thinkyhead** [comment]
@Wurstnase The `qr_solve` function is one of those rare routines (maybe the only routine) that uses `malloc` to allocate SRAM. What kind of board are you using, and how much Free RAM does the firmware report when you start it?

**Comment by tonnico** [comment]
I will check the free RAM this evening. 
I'm using a Arduino Due:
SRAM 96 KB (two banks: 64KB and 32KB)

**Comment by Roxy-3D** [comment]
> @Wurstnase The qr_solve function is one of those rare routines (maybe the only routine) that uses malloc to allocate SRAM. What kind of board are you using, and how much Free RAM does the firmware report when you start it?

If the root problem is a shortage of RAM for malloc() to grab and use...   I'm trying to get the iterative LSF uploaded today!  It doesn't use malloc() and hardly grabs any memory on the stack.

UPDATE:   Incidentally...  QR_SOLVE.CPP does not check for a failure when malloc() is called.  It calls malloc() six different places in the code.  If there isn't enough memory available, there is no way to predict how it is going to fail.

**Comment by tonnico** [comment]
I don't think, that memory is the problem here.
`19:46:37.590 : echo: Free Memory: 87476  PlannerBufferBytes: 2688`

**Comment by tonnico** [comment]
Just update to 1.6.2 (1.6.3 for Due) and that part is gone. Thanks anyway!
