### ISSUE TITLE
How to setup ST7920 lcd on a custom configured motherboard using U8G2 library in Marlin firmware?

### ISSUE THREAD

**Issue by jnour91** [MarlinFirmware/Marlin#17450]
### Description
Trying to use ST7920_128X64_1_SW_SPI LCD from U8G2 library, planning to implement U8G2 library into marlin 1.1X bug fix firmware with my own custom motherboard already configured, planning to creat a LCD configuration in configuration.h and work my way in by copying a another lcd profile, is this the best workflow? I am finding it easy to get lost in marlin (still a newbie to this world of programming mech eng backgournd) or are there better methods to this?

### Feature Workflow
configuring a LCD from U8G2 library into marlin 1.1X

1. install and code in U8G2 library in ultralcd_impl_DOGM.h
2. Configure new LCD profile by copying a already defined configuration from LCD / Controller Selection in configuration.h for example"REPRAP_DISCOUNT_SMART_CONTROLLER" and following the links from there.

IS THIS THE BEST WORKFLOW? IS THERE A DIAGRAM OF MARLIN FIRMWARE PARENT CHILD RELATIONSHIPS AVAILABLE?

Hope it makes sense. 

Thanks

**Comment by AnHardt** [comment]
Why u8g2 ?
This was alreay tried. It did not result in faster, smaller or better code than using u8g.
Especially the ST7920 code is highly optimized by us. It's already faster than the display can handle. We have to add waits.

Why Marlin 1.1.x. ?
Development for this has ended.

Why not simply adding the pinning for your board?
