### ISSUE TITLE
Print head position change on multiple T0/T1 commands

### ISSUE THREAD

**Issue by jokober17** [MarlinFirmware/Marlin#17483]
Hi all,

I encounter issues with Marlin version 2.0.5.3 (also with 1.9.x) if I issue multiple head change command T0 and T1 to the printer (no other commands in between). The absolut position of the print heads will move slowly in X and Y direction. After about 100 changes I have a difference of about 0.1 mm relatively to the starting position.

I start at position X150 Y150 Z70. After 100 repeats of T0/T1 a G1 X150 Y150 Z70 does not move the print head.

I tested it with setting M218 X-48.6 Y-0.51 Z0.02.

If I change the setting to M218 X48.6 Y0 Z0.02 only X position is moving slowly.

If I change the setting to M218 X48 Y0 Z0.02 everything is fine.

I'm using a Tevo Tornado with dual head configuration. Processor board is MEGA2560

Could you please check ?

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
