### ISSUE TITLE
[BUG] SENSORLESS_PROBING not working when SENSORLESS_HOMING is disabled

### ISSUE THREAD

**Issue by tampe125** [MarlinFirmware/Marlin#17530]
### Bug Description

I'd wish to use SENSORLESS_PROBING without the need to use SENSORLESS_HOMING. I'm using a CoreXY setup and I'm not 100% confident sensorless homing is reliable.

SENSORLESS_PROBING: ON
SENSORELESS_HOMING: ON
I can calibrate on Z axis

SENSORLESS_PROBING: ON
SENSORELESS_HOMING: OFF
Z motor keeps smashing on the min endstop

### My Configurations
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4470791/Configuration.zip)

I disabled Z_SAFE_HOMING in SanityChecks.  
I'm using a pick and place machine, with a CoreXY setup, that's why I have endstops on the Z axes

### Steps to Reproduce

1. Compile with SENSORLESS_PROBING enabled and SENSORLESS_HOMING disabled
2. Calibrate Z

**Expected behavior:** Motor should stop when hitting the end of the Z axis

**Actual behavior:** Motors keep spinning

#### Additional Information

I already tested the bugfix branch without success

**Comment by tampe125** [comment]
Any updates on this?

**Comment by boelle** [comment]
@tampe125 still an issue?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
