### ISSUE TITLE
STM32F4 PWM Frequency 

### ISSUE THREAD

**Issue by forthereg** [MarlinFirmware/Marlin#17533]
So Im upgrading from one of the older 2.0x marlins on a SKR pro, which is a stm32f407zgt6. LQFP144.

with the new marlin all my pins are pulse width modulated at 1khz no matter the #FAN_SOFT_PWM.
maybe that is working as intended :( 
(#define FAST_PWM_FAN is not supported on this platform btw...or so it tells me ) .

So I actually assign the extention GPIOs as Fan1 , Fan2 in Pins.h and used M106 instead of M42.

but now : 
with no FAN_SOFT_PWM or scaled at 0 it runs at the same 1KHZ 

with Fan-soft-pwm  defined and scaled i get the following frequencies on fan outputs.
scale 1  15hz
scale 3  30hz
scale 3  125hz
scale 4  200hz
scale 5  250hz
scale 7 is just off at S1 and 100% on at S2 .
i just like to add that the duty cycle is spot on as far as the oscilloscope shows.

this issue happened on the Main stable marlin 2.0.5.  & the nightly build and also on 2.1.
so how do i get a 20khz+ signal out of a GPIO or a fan output on the new marlin ?

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/4471650/Configuration_adv.zip)

I switched back to my older 2.0x marlin. With just Fan-soft-pwm and scaled at 2 the output is at 20.5Khz.  I think there was some changes some time ago changing the PMW from 8bit to 12bit because of some duty cycle issues ? that might have has something to do with it .
here is the zip of the full old marlin that works correctly ;  GPIO pins modulated at 20.5khz.
[PR Bl touch.zip](https://github.com/MarlinFirmware/Marlin/files/4473978/PR.Bl.touch.zip)

**Comment by boelle** [comment]
@forthereg is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
