### ISSUE TITLE
enabling reprap graphical display with atmega 2560 breaks build

### ISSUE THREAD

**Issue by Trevader24135** [MarlinFirmware/Marlin#17563]
Using Marlin 2.0.x or the nightly bugfix build and enabling "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" instantly breaks the build with the error "Error compiling for board Arduino Mega or Mega 2560" with the additional info "avr-gcc: error: CreateProcess: No such file or directory"

full log dump here (I had to cut a little from the middle to make it fit in pastebin, I hope that cut part isn't relevant, I can try something else if needs be)

[https://pastebin.com/xxZTTpVk](url)

**Comment by thinkyhead** [comment]
That is a compiler bug. You'll need to use a different toolset.
