### ISSUE TITLE
[CoreXY] Homing X moves Y axis

### ISSUE THREAD

**Issue by manutenfruits** [MarlinFirmware/Marlin#17566]
I have a CoreXY printer that has run happily on Marlin 2.0 with a MKS SBASE (DRV8825 drivers). I recently upgraded to a BTT SKR1.2 with TMC2209 drivers and I'm setting it up.
I started with only X and Y steppers wired and I'm trying to get homing right before I move on to other features. My printer homes to minX and then to maxY, but when I issue `G28 X` it first goes to minX, and before it reaches it starts going to maxY, crashing in maxY because it never hit the minX endstop. This seems to only happen homing X, because so far `G28 Y` hasn't done anything weird, homing Y works just fine.

I'm going to try to downgrade to a more stable version, because this seems like a very odd bug, given how easy it is to reproduce and how simple the test is. I have also tried moving the axis before homing, and it will start moving in the right direction but then it will move in the other axis.
UPDATE: I downgraded to release `2.0.5.3` (from branch `2.0.x`) and still same issue.

Demo video: https://photos.app.goo.gl/bYFs2BKMibiuyy1k7
My config: https://github.com/manutenfruits/Marlin/commit/d0735cc6620fb2b1465f72f1f086e38151104d86

EDIT: I'm also thinking this could be due to the stepper drivers? It's my first time using TMC drivers and changing axis is due to one motor suddenly changing direction.

Some other things I've tried:

 - Swap X and Y steppers, same issue: X can't home, Y homes fine.
 - If I move X very close to the endstop, it can complete homing, as usually it moves ~30mm before the sudden change in direction.
 - I can reproduce by moving it on the X direction, which at some point it will start moving on Y, so it's not related to homing.

**Comment by manutenfruits** [comment]
I'm also thinking this could be due to the stepper drivers? It's my first time using TMC drivers and changing axis is due to one motor suddenly changing direction.

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
