### ISSUE TITLE
I have a problem with my 3d Printer

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#17564]
I have a FLSUN extended bed printer I bought a few years back similar to the one in this link (https://www.aliexpress.com/item/32847633139.html?spm=a2g0o.productlist.0.0.19ea4e9eeaSZrD&algo_pvid=3948f016-cd1e-49dc-a140-1246bc00016a&algo_expid=3948f016-cd1e-49dc-a140-1246bc00016a-7&btsid=0ab6f82115869898286663410e318a&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_) and it worked fine for years up until recently as it cant seem to get over 180C because when connected to repetier host it gives:
Error: Heating failed,System stopped! Heater ID: 0
Error:printer halted.kill() called!

any ideas

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
