### ISSUE TITLE
[BUG] all_axes_homed issue?

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#17573]
Two bugs 👍 
All is in the movie included
[Vid](https://www.youtube.com/watch?v=2H3KPlqRC9Q
)
All_axes_homed() return always false :  
- Tool migration and many , need homing before starting ' in the video you can see the migration begins only if not homed' , and tool change too

LCD fan speed corrupted : Impossible to set it by LCD and all commands from lcd that need fanspeed is corrupted , because UI send a 0 value eternally

Help: I use UI for homing , UI for fanspeed , i'm sure UI lock anything that is sent by LCD
and surely the same here [#17570](https://github.com/MarlinFirmware/Marlin/issues/17570)

**Comment by thinkyhead** [comment]
When you add logging to print out the current value of `axis_homed` what does it say?

**Comment by studiodyne** [comment]
> 
> 
> When you add logging to print out the current value of `axis_homed` what does it say?

When i try to prime() , a function that only have ' all_axes_homed' , the prime doesn't work when homed , and works when not ' all_axes_homed  is false 
When i've tried to migrate or tool change after LCD HOMING ' by custom user menu' , same problem ' can_move , is made with all_axes_homed ' and is false, but in sdprint no bug.
And fanspeed always  locked on sd print or lcd , but not on gcode by M106

On sdprint no homing bug , but fanspeed always off and doesn't start on tool migration
it's an old issue , remember when you have made your first intervention on my ' tool migration code ' , i have told you about issue , homing and fanspeed , and asked you to rebase , these bugs are very old just after  2020 03 19 build

**Comment by thinkyhead** [comment]
I simply don't have time to become a clone of the expert (especially when this information is made extra hard to read). If you are an expert on the things you are writing about, send us a patch.
