### ISSUE TITLE
[FR] Preheat Constants

### ISSUE THREAD

**Issue by android444** [MarlinFirmware/Marlin#17590]
I analyzed the code and noticed such a thing.

```cpp
      case 0: // Preheat PLA
        #if defined(PREHEAT_1_TEMP_HOTEND) && defined(PREHEAT_1_TEMP_BED)
          e_temp = PREHEAT_1_TEMP_HOTEND;
          bed_temp = PREHEAT_1_TEMP_BED;
        #endif
        break;
      case 1: // Preheat ABS
        #if defined(PREHEAT_2_TEMP_HOTEND) && defined(PREHEAT_2_TEMP_BED)
          e_temp = PREHEAT_2_TEMP_HOTEND;
          bed_temp = PREHEAT_2_TEMP_BED;
        #endif
        break;
      case 2: // Preheat PET
        #if defined(PREHEAT_3_TEMP_HOTEND) && defined(PREHEAT_3_TEMP_BED)
          e_temp = PREHEAT_3_TEMP_HOTEND;
          bed_temp = PREHEAT_3_TEMP_BED;
        #endif
        break;
      case 3: // Preheat FLEX
        #if defined(PREHEAT_4_TEMP_HOTEND) && defined(PREHEAT_4_TEMP_BED)
          e_temp = PREHEAT_4_TEMP_HOTEND;
          bed_temp = PREHEAT_4_TEMP_BED;
        #endif
```

In `Configurations.h` there is only PLA and ABS.
Can you add an additional preheat?

**Comment by GMagician** [comment]
that's present under `#if ENABLED(DGUS_PREHEAT_UI)` not on standard lcd (it seems)

**Comment by android444** [comment]
ok

**Comment by thisiskeithb** [comment]
You can only add two right now for the main LCD code, but it would still be nice to increase the current limit of 2:

https://github.com/MarlinFirmware/Marlin/blob/8ad056013cd14907dc1a2aebdc0f4a31308606e2/Marlin/src/lcd/menu/menu_temperature.cpp#L100-L154

**Comment by android444** [comment]
I want to increase it.
Only this requires a general rewriting of the code.
I want to choose any amount - minimum 1.

**Comment by GMagician** [comment]
Need to increase also somewhere else. The reported code is only for eeprom save....

**Comment by thisiskeithb** [comment]
> Need to increase also somewhere else. The reported code is only for eeprom save....

Updated my link 😉

**Comment by sl1pkn07** [comment]
https://github.com/sl1pkn07/Marlin/commit/02e08d1bd662a93dc6ed882470b1d6d95efe5a6f

I have aded a 3rd preheat (sorry for no separate in other commit. But is more easy for me if need rebase if upstream change the main code)

**Comment by android444** [comment]
I want to do it so THINKYHEAD will accept it.

**Comment by android444** [comment]
Whoever wrote this did not think about changes.
I don't really know how to change some things to make them compile.

**Comment by thisiskeithb** [comment]
You can now have up to five preheat options, so just copy & paste one of the preheat constant blocks in `Configuration.h` and increase the `PREHEAT_N_` value for each new material.
