### ISSUE TITLE
[BUG] G5 feedrate value not changing movement speed

### ISSUE THREAD

**Issue by lindejo1** [MarlinFirmware/Marlin#17606]
I've been testing G5 bezier g-codes with latest Marlin 2.0.5.3 and cannot change the feedrate with F parameter. Motion looks correct, but movement is very fast and not according to previously set F rate. I am testing on setup with mega 2560, RAMPS 1.4 and laser engraver with X and Y axis only. Arc commands seem to work normally and feed rate can be set for those.

Update: seems G5 command doesn't have default feedrate percentage set similarly as other commands with my setup, but after setting some value for it, the G5 F parameter has impact on feedrate. Without setting percentage first, F parameter doesn't have any impact on result. Other issue is that F value needs to be very small compared to other movement commands (eg. 1400 for G0 and 20 for G5 for movement speed to be close the same). Also for G5 the X and Y movement seems to always have S-curve type acceleration even when that is disabled in configurations, so movement always starts slow and speeds up to max in middle of movement path and then breaks down to end, while other commands have same movement velocity. Should G5 command in work similarly to other commands or are these normal?

I've tried with classic jerk and with or without s-curve acceleration with same results.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
