### ISSUE TITLE
[BUG] Printer not homing correctly after LCD/SD Stop Print

### ISSUE THREAD

**Issue by jreis1** [MarlinFirmware/Marlin#17607]
### Bug Description

ISSUE: When printing from SD card and request to Stop a print using LCD menu, only Y-axis is going home. X-axis stays where it is.   In the subsequent print, without resetting the machine, table  presents a huge offset. After homing correctly, it starts new print almost in the centre of the table. 

### My Configurations
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/4499565/configs.zip)

### Steps to Reproduce

1.  Start printing from SD card
2.  When printing, force stop print via LCD menu
3.  Start a new print

Expected behavior: after a stop via LCD,  "G28 XY" was expected.  
Actual behavior: as described above. 

#### Additional Information

marlin version: 2.0.5.3
Platform: Ender 3
mainboard: SKR v1.4 Turbo 
motor drivers: TMC2209
Sensorless Homing: X and Y

**Comment by jreis1** [comment]
Guys, finally found the issue!!

I was setting the manual home position with a positive value, as: 
#define MANUAL_X_HOME_POS **+3.5**
#define MANUAL_Y_HOME_POS -7.5

This was affecting my stopping routine when stoping from the LCD, as  decribed above.  
As soon as I change that value to a negative number, stopping start to behave as expected.

**Comment by thinkyhead** [comment]
How weird. It should be cool to set a home position as positive. However, this will make positions below your home (3.5) unreachable, so if any routines want to move to X0 they will grind and throw off the axis.

Positive home positions are okay as a concept in Marlin, but they assume you have something like a Hall effect sensor that doesn't block the axis.
