### ISSUE TITLE
Tool for understanding: feedrate, acceleration and jerk

### ISSUE THREAD

**Issue by daleckystepan** [MarlinFirmware/Marlin#17618]
Hi guys,

I've written small app to better understand basic motion principles in Marlin. It is very tough for beginners.

https://github.com/daleckystepan/MarlinMotion

It is written in Python, based on simply RungeKutta ODE solver. Jerk is used only for initial velocity which is half of jerk. It is only for one axis now. We can improve it by proper jerk, s curve acceleration or so on.

Feel free to test it and give me feedback.
Thank you

**Comment by tomarigr** [comment]
Yeah but why jerk and not junction deviation?

**Comment by daleckystepan** [comment]
Because I don't know how jerk and JD work exactly. If there is someone who is able to explain this, just do it.

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
