### ISSUE TITLE
[FR] Allow retract after filament change

### ISSUE THREAD

**Issue by onovy** [MarlinFirmware/Marlin#17616]
### Description

M125 - Park nozzle currently does this:
1. retract
2. park nozzle
3. wait for user
4. unretract
5. unpark nozzle

During movement from parking position to printing position, filament is oozing.

M600 - Filament change currently does this:

1. retract
2. park nozzle
3. unload+load new filament
4. unpark nozzle

During movement from parking position to printing position, filament is oozing.

### Feature Workflow

I'm suggesting to add retraction just after loading new fiilament. When user confirms filament is pushed thru nozzle, user should clean nozzle. Then Marlin should retract (to lower pressure in nozzle), unpark nozzle back to printing position and un-retract

Currently it's really hard to snap hanging filament from nozzle "just in time" when nozzle is returning back to printing position.

Thanks.

PS: Currently working on merge request

**Comment by MoellerDi** [comment]
@boelle @onovy it seems the related PR #17625 was merged. Did it resolve this FR?

**Comment by onovy** [comment]
yes, thanks for pointing out
