### ISSUE TITLE
[BUG] MOTHERBOARD BOARD_RAMPS_14_EFB

### ISSUE THREAD

**Issue by manotroll** [MarlinFirmware/Marlin#17612]
there is no option to heat the table in the slicer and on the LCD
and I also can't disable PIDTEMPBED for autopid

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4499988/Marlin.zip)

**Comment by ellensp** [comment]
This is support question, not a marlin bug or feature request. 
Please read https://github.com/MarlinFirmware/Marlin/issues/14694

In saying that you have made an elementary error in your Configuration.h 
you have #define TEMP_SENSOR_BED 0
Which say there is no heated bed temperature sensor. Ie you have told the firmware you don't have a heated bed.

**Comment by manotroll** [comment]
and now how does the table temperature offset?
is giving 10ºC difference with the thermometer

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
