### ISSUE TITLE
STATUS_BED_X' was not declared in this scope

### ISSUE THREAD

**Issue by Enric580** [MarlinFirmware/Marlin#17629]
I am trying to install the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER screen on an MKS_SGEN_L board
when i compile marlin 2.0.x I get this error

Marlin \ src \ lcd \ dogm \ status_screen_DOGM.cpp: 253: 30: error: 'STATUS_BED_X' was not declared in this scope; did you mean 'STATUS_FAN_X'?
   253 | const uint8_t bx = STATUS_BED_X + STATUS_BED_WIDTH;

**Comment by swilkens** [comment]
Please try again with the bugfix branch and let us know if your issue still exists:

Firmware:
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

Configuration:
https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x


Alternatively, if you want a more stable code level, you can try release 2.0.5.3:

Firmware:
https://github.com/MarlinFirmware/Marlin/tree/2.0.5.3

Configuration:
https://github.com/MarlinFirmware/Configurations/tree/2.0.5.3

**Comment by Enric580** [comment]
OK, the problem has been fixed, it works fine.
Thanks

**Comment by ellensp** [comment]
Can you close the job then? Thanks.
