### ISSUE TITLE
[BUG] Virtual Tool 1 is Incorrectly initialized with 0 : 0 mix on 2 in 1 mixing printer

### ISSUE THREAD

**Issue by lterrill** [MarlinFirmware/Marlin#17635]
### Bug Description

Beginning with Marlin 2.0.5, Virtual Tool 1 is incorrectly initialized with 0 : 0 mix. Attempting to extrude using tool 1 with this default mix results in printer crash. 

### My Configurations

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/4510264/Configs.zip)

### Steps to Reproduce

Using a Geeetech A10M with 2 in to 1 mixing hot-end 
1: Boot printer
2: Examine Virtual Tool mix via LCD. Note that Virtual tool 1 (second tool) is initialized with a mix of 0 : 0. 
3: G28; home
    T1; select tool 1
    G1 E5 F50; extrude using tool 1
4: printer locks up, crash

**Expected behavior:** [What you expect to happen]

Virtual tool 1 previously initialized with a mix of 0 : 100. This resulted in the extrusion move using the second physical filament extruder

**Actual behavior:** [What actually happens]

Beginning with Marlin 2.0.5, Virtual tool 1 initializes with a mix of 0 : 0. I believe this results in some bad math that crashes Marlin

#### Additional Information
![Virtual Tool 1](https://user-images.githubusercontent.com/535763/79872609-9d4df680-83ab-11ea-8b8f-0c3c6c3cd9fd.jpg)

**Comment by Patag** [comment]
Don't know exactly your hotend configuration, but I guess you should use SINGLE_NOZZLE (2 steppers, 1 heater and 1 nozzle) rather than MIXING_EXTRUDER.

**Comment by thinkyhead** [comment]
I saw the report on FB. I'll patch it asap.

**Comment by iatwalrus** [comment]
Has a patch or fix been put in for this? If so, where may I find it?

**Comment by lterrill** [comment]
> Has a patch or fix been put in for this? If so, where may I find it?

bugfix-2.0.x branch contains the patch that corrects this issue in mixing.cpp, reset_vtools(). I expect this patch will be merged into the 2.0.x branch with the next release on that branch, but that had not yet occurred as of 4/26/2020
