### ISSUE TITLE
[BUG] AUTO_BED_LEVELING_UBL doesn't use MIN_PROBE_EDGE

### ISSUE THREAD

**Issue by compunited** [MarlinFirmware/Marlin#17656]
AUTO_BED_LEVELING_UBL doesn't use MIN_PROBE_EDGE. It goes outside the allowed radius which leads to serious problems on delta. (touching clamps, hitting mechanical end stops,...)

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by compunited** [comment]
You're not serious? After 60 days you had a look at it and close it after 3 days?

**Comment by boelle** [comment]
yes serious, 3 days should be enough to report back

**Comment by sjasonsmith** [comment]
I have a delta I could try to reproduce it on, but I’ll need your configs as a starting point.

**Comment by boelle** [comment]
@compunited 

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.
