### ISSUE TITLE
[BUG] power loss recovery not working with latest bugfix

### ISSUE THREAD

**Issue by drfil120** [MarlinFirmware/Marlin#17655]
### Bug Description
Power loss recovery not working with latest Marlin bugfix (downloaded this morning)
Not working anymore since renaming "power_loss_recover.cpp" to "powerloss.cpp
Board : BTT skr mini E3 v1.2 + mini UPS 24V
With M43 pins debug the PIN PC12(44) indicates "output".
If i set the pin with M42 to input powerloss works and my heatbed raises.
With M42 changing the pin to input i get a EERPOM error on the screen

### My Configurations
[configurations.zip](https://github.com/MarlinFirmware/Marlin/files/4513956/configurations.zip)

### Steps to Reproduce
1. [First Step]
Compile latest Marlin bugfix
2. [Second Step]
Cut power to printer and bed must raise

**Expected behavior:** [What you expect to happen]
Bed raises after power cut, screen indicates power cut

**Actual behavior:** [What actually happens]
no reaction from printer, no indication on screen

#### Additional Information

![M42 P44 M2 pin state](https://user-images.githubusercontent.com/64121370/79944254-59bac180-846b-11ea-8ccd-acd8b876d26a.png)
![M43 pins debug](https://user-images.githubusercontent.com/64121370/79944257-5cb5b200-846b-11ea-9db1-06b4b2e0ae80.png)

**Comment by boelle** [comment]
@drfil120 is the issue still there?

**Comment by drfil120** [comment]
The issue is solved.
Thanks
