### ISSUE TITLE
[BUG] Enabling ADAPTIVE_STEP_SMOOTHING causes printstops and inaccurate PWM(Servo)

### ISSUE THREAD

**Issue by bergyla** [MarlinFirmware/Marlin#17676]
By testing the ADAPTIVE_STEP_SMOOTHING Feature on a STM32 (F407) based controller board I found that prints stopping after some amount of time (after a couple of minutes) and then after continued after some ten seconds.
As far I could see, some moments before the print stopped, the Servo PWM began to behave unpredictable.

Same behavior, gcode executed from SDCard or from serial connected Remote Touch LCD (USB-Stick).

I disabled SD-Card support in firmware and some other time and memory intensive options, but so far without any changed behavior.
Described Fail-Out seems to stick only with ADAPTIVE_STEP_SMOOTHING.
Rechecked with latest Bugfix-2.0.x Repo.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
