### ISSUE TITLE
mechanical leveling of the motorized bed

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#17703]
Hello
and it provided in marlin the possibility of carrying out a mechanical leveling of the motorized bed with a Z provided with 3 independent motor.

merci

**Comment by GMagician** [comment]
Isn't `#define NUM_Z_STEPPER_DRIVERS 3` with 3 installed steppers what are you asking for?

Edit: Followed by a G34

**Comment by sjasonsmith** [comment]
This already exists. The `Z_STEPPER_AUTO_ALIGN` feature does exactly this.

@boubouexpress please close this issue. If you have problems configuring `Z_STEPPER_AUTO_ALIGN` you can come ask questions in Discord or one of the other support channels.
