### ISSUE TITLE
[FR] G-code to get build area / size

### ISSUE THREAD

**Issue by rightawy** [MarlinFirmware/Marlin#17706]
### Description
There is no G-code to get bed build area / size.
there should be a g-code to get sizes like bed size and axis sizes. Like M360 in Repetier firmware.

**Comment by thisiskeithb** [comment]
See PR #16741: "Add reporting of machine/bed size and x,y & z axis movement limits to the host in M115 command"

**Comment by slowbro** [comment]
This was added to M115 in #16741, with `M115_GEOMETRY_REPORT` in Configuration_adv.h. This can be closed.

**Comment by thisiskeithb** [comment]
Resolved in #16741.
