### ISSUE TITLE
[BUG] Load Marlin 2.0.5.3 on Anet A8

### ISSUE THREAD

**Issue by obsidian929** [MarlinFirmware/Marlin#17717]
Hi

I've downloaded the latest Marlin and wanted to update my Anet A8 via Visual Studio Code.

I've changed the Configuration & Configuration_adv file in the '\Marlin-2.0.x\Marlin' folder.

I've installed PlatformIO IDE and Auto Build Marlin on Visual Studio Code.

I then started the build and got this error a while later : 
```
**Compiling .pio\build\sanguino1284p\src\src\module\planner_bezier.cpp.o
Marlin\src\module\motion.cpp:77:71: error: 'X_HOME_BUMP_MM' was not declared in this scope
 #define XYZ_CONSTS(T, NAME, OPT) const PROGMEM XYZval<T> NAME##_P = { X_##OPT, Y_##OPT, Z_##OPT }
                                                                       ^
Marlin\src\module\motion.cpp:83:1: note: in expansion of macro 'XYZ_CONSTS'
 XYZ_CONSTS(float, home_bump_mm,  HOME_BUMP_MM);
 ^
Marlin\src\module\motion.cpp:77:80: error: 'Y_HOME_BUMP_MM' was not declared in this scope
 #define XYZ_CONSTS(T, NAME, OPT) const PROGMEM XYZval<T> NAME##_P = { X_##OPT, Y_##OPT, Z_##OPT }
                                                                                ^
Marlin\src\module\motion.cpp:83:1: note: in expansion of macro 'XYZ_CONSTS'
 XYZ_CONSTS(float, home_bump_mm,  HOME_BUMP_MM);
 ^
Marlin\src\module\motion.cpp:77:89: error: 'Z_HOME_BUMP_MM' was not declared in this scope
 #define XYZ_CONSTS(T, NAME, OPT) const PROGMEM XYZval<T> NAME##_P = { X_##OPT, Y_##OPT, Z_##OPT }
                                                                                         ^
Marlin\src\module\motion.cpp:83:1: note: in expansion of macro 'XYZ_CONSTS'
 XYZ_CONSTS(float, home_bump_mm,  HOME_BUMP_MM);
 ^
*** [.pio\build\sanguino1284p\src\src\module\motion.cpp.o] Error 1**_

I found the issue in the Module.cpp file : 
**_#define XYZ_CONSTS(T, NAME, OPT) const PROGMEM XYZval<T> NAME##_P = { X_##OPT, Y_##OPT, Z_##OPT }

XYZ_CONSTS(float, base_min_pos,   MIN_POS);
XYZ_CONSTS(float, base_max_pos,   MAX_POS);
XYZ_CONSTS(float, base_home_pos,  HOME_POS);
XYZ_CONSTS(float, max_length,     MAX_LENGTH);
XYZ_CONSTS(float, home_bump_mm,  HOME_BUMP_MM);
XYZ_CONSTS(signed char, home_dir, HOME_DIR);_**

It seems to want to define the float X_HOME_BUMP_MM ,Y_HOME_BUMP_MM & Z_HOME_BUMP_MM , but if I try this, the error gets worse.
if I hide the **//XYZ_CONSTS(float, home_bump_mm,  HOME_BUMP_MM);** it runs to the end of the file and give me this error on Visual Studio Code.
_**Linking .pio\build\sanguino1284p\firmware.elf
C:\Users\Obsidian\AppData\Local\Temp\cccVfnBV.ltrans15.ltrans.o: In function `homeaxis(AxisEnum) [clone .part.1] [clone .lto_priv.254]':
<artificial>:(.text+0x960): undefined reference to `home_bump_mm_P'
<artificial>:(.text+0x962): undefined reference to `home_bump_mm_P'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\sanguino1284p\firmware.elf] Error 1**
```
see images below:
![Error 1](https://user-images.githubusercontent.com/64336963/80293867-c67fd580-8763-11ea-97f3-8d647eb973d3.PNG)
![Error 2](https://user-images.githubusercontent.com/64336963/80293868-c8499900-8763-11ea-8b24-aedcd76bd7af.PNG)

I've even played with the platformio.ini file with different default_envs to see if i can get pass the error, but no luck.

Can you please have a look at this, or tell me what i'm doing wrong?

Regards

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
