### ISSUE TITLE
[BUG] nanodlp sync not work

### ISSUE THREAD

**Issue by gerryc89** [MarlinFirmware/Marlin#17720]
When using the firmware with nanodlp on a ramp board with the option NANODLP_Z_SYNC actived, the sync not work because nanodlp doesn't expect that ramps send "ok" after Z_MOVE_COMP with the moving gcodes of z axis. I have deleted ok from the string in the language.h file and it work correctly but is a ugly solution.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
