### ISSUE TITLE
[BUG] "Error:Probing Failed" is sent over serial even if G29_RETRY_AND_RECOVER is enabled

### ISSUE THREAD

**Issue by o-nix** [MarlinFirmware/Marlin#17730]
STR:
* `G29_RETRY_AND_RECOVER` is enabled and `G29_MAX_RETRIES` set to 3, `G29_HALT_ON_FAILURE` is disabled
* OctoPrint is running and connected, no extra plugins for host commands or error handling
* Start a G29 routine
* When the **first** probe is failed, then OctoPrint sends `M112` immediately

ER: G29 routine is restarted

AR: the printer is halted

FIX: lift probe error logic on the layer above by commenting or guarding the following line
https://github.com/MarlinFirmware/Marlin/blob/0518dec60d0931745efa2812fa388f33d68cfa29/Marlin/src/module/probe.cpp#L760

**Comment by thinkyhead** [comment]
Is Octoprint configured to panic when it sees the word "Error"? If so, try disabling that option.

**Comment by o-nix** [comment]
@thinkyhead I see that `SERIAL_ERROR_MSG` is used in `kill()` as well, so it seems it is the only "standard" way to understand, that the printer halted itself.

**Comment by o-nix** [comment]
@thinkyhead BTW this is the OctoPrint's setting you mentioned, "Disconnect" and "Send M112" are set by default
![image](https://user-images.githubusercontent.com/647149/80865869-991bb600-8c94-11ea-9902-a328af373f1d.png)

**Comment by boelle** [comment]
@o-nix still an issue?

**Comment by o-nix** [comment]
@boelle uhm, of course. Wrong error reporting logic. I overrided it manually by commenting the line inmy local Marlin sources.

**Comment by o-nix** [comment]
So, I confirmed that it is still an issue and you are closing it?
Would you prefer having a PR from me with the commented line?

**Comment by boelle** [comment]
yes please, we welcome PR's
