### ISSUE TITLE
[Bug] firmware ignoring dual extruder offset im change

### ISSUE THREAD

**Issue by mvthedemon** [MarlinFirmware/Marlin#17742]
Offsets for dual extruder are in firmware yet in tool change all I get is a z raise if 2mm and I've tried a number of things to fix 

On tool change from tool0 to tool1 shift -35 on x axis to line up second extruder and continue 

Raises 2mm in z axis and never shifts in the x 
SKR PRO V1.1 marlin 2.0.5.3 and 2.0 bugfix 

Worked previously on 1.1.7/8

**Comment by thinkyhead** [comment]
Please fill out the template. We can't follow up on issues with no information.

Geeks who like to mess with tool-changing include @InsanityAutomation and @studiodyne. I am afraid to touch it because I don't have any fancy machines.

**Comment by studiodyne** [comment]
Seems really too big to be real , i think it's a bad settings in cfg files

@mvthedemon
I only have singlenozze machine and , i will help you just by taking a look and try to find something that can break somewhere
Please can you attach your 'up to date ' cfg/adv files

Thks

**Comment by mvthedemon** [comment]
I will upload config  later this afternoon at work currently but side note it has been a persistent problem from 2.0 release and bugfix

**Comment by mvthedemon** [comment]
Ok here is my config.h and config-adv.h #

**Comment by mvthedemon** [comment]
Was a bad sd card insert facepalm here thanks guys
