### ISSUE TITLE
Power loss recovery issue

### ISSUE THREAD

**Issue by github051** [MarlinFirmware/Marlin#17743]
Currently, i'm using the marlin 2.0.3 version (Controller: MKS Robin) with power loss recovery and is working fine but when the power comes if i click on resume the hot end is moving home without heating the nozzle. why ? any idea ?

Requirement: if i click resume then the nozzle heats up first then go to home

**Comment by chepo92** [comment]
I think you should:
1. Use the template for issues
2. Test with bugfix 2.0 branch, 2.0.3 is a bit outdated

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
