### ISSUE TITLE
[BUG] No compilation 'XY_FREQUENCY'  -->refresh_frequency_limit not declared in scope

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#17748]
### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ellensp** [comment]
Please provide configuration files.

**Comment by studiodyne** [comment]
hi , thanks to answer , i'm the author of the frequency limiter , but @thinkyhead have reviewed the code and , a little review needed

This is the fix
`

    #ifdef XY_FREQUENCY_LIMIT
      editable.uint8 = planner.xy_freq_limit_hz;
      EDIT_ITEM(uint8, MSG_XY_FREQUENCY_LIMIT, &editable.uint8, 0, 100, []{ planner.refresh_frequency_limit() ; }, true);
      editable.uint8 = LROUND(planner.xy_freq_min_speed_factor * 255 * 100); // percent to u8
      EDIT_ITEM(percent, MSG_XY_FREQUENCY_FEEDRATE, &editable.uint8, 3, 255, []{ planner.set_min_speed_factor_u8(editable.uint8); }, true);
    #endif




`


In progress & in test

Thk you very much
