### ISSUE TITLE
http://marlinfirmware.org/     is down

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1775]

**Comment by thinkyhead** [comment]
**Sorry! This site is experiencing technical difficulties.**
**Try waiting a few minutes and reloading.**
**(Cannot contact the database server)**

**Comment by boelle** [comment]
yep, and waiting an hour or day gives same message

**Comment by thinkyhead** [comment]
Ah well, at least http://marlinfirmware.org/configurator/ still works. I'm sure it's something simple.

**Comment by boelle** [comment]
@scotty1024... still among us?

**Comment by boelle** [comment]
its the database failing.... but i grow a bit worried that @scotty1024 is no longer among the living...

how long should we give it before seeking alternative domain names etc etc?

**Comment by thinkyhead** [comment]
@boelle For the wiki, it might be best to just add a set of sub-pages directly to the RepRap wiki, starting at the top page http://reprap.org/wiki/Marlin – and I can install a redirect from marlinfirmware.org to that wiki page.

**Comment by boelle** [comment]
so you have access to the webspace where the domain is?

if that is the case we can maybe get it back on track

**Comment by thinkyhead** [comment]
@boelle I don't have the database credentials, which seems to be the missing piece. But I saw a live @scotty1024 lurking around Marlin earlier today.

**Comment by boelle** [comment]
:-D well i'm off to work.... i get home at about 14:30 my time

and day off tomorrow.... will prob hang out at the hangout link i put in the redme.md

**Comment by scotty1024** [comment]
It wanted it’s latest security updates and a reboot.

My bad, I was distracted with tuning my first dual extrusion printer.

**Comment by boelle** [comment]
hehe, thing happens :-D

might be wise to share access with one more person should you not be able to attend server

maybe @thinkyhead ....

**Comment by thinkyhead** [comment]
If need be, I have a Hostgator hosting account with a dozen domains on it, which I pay for annually in one big lump. It doesn't cost extra to add new domains. They just charge me for the total CPU, bandwidth, and storage. :smiling_imp:  And I already have one MediaWiki instance hosted there, which has been hack-proofed against being edited by sock-puppets.

Drupal 7 with AJAX makes a good platform, as it likes markdown, can have forums added, uses tags, can display code with syntax highlighting, and can double as a database – for example, each GCode could be an individual object (node), which gives it its own "page" (ajax-usable view), makes it cacheable, more usable in views, lists, blocks, searches, etc. Then, each "Machine" (as in example_configurations) can also have a node, with all the same capabilities, an image of the machine for reference, the current configuration for each linked to the Marlin repository - also fetchable and cacheable. Heavy use of AJAX makes such sites much better - more like apps (or like Github).

**Comment by emartinez167** [comment]
I like that idea!!!

**Comment by scotty1024** [comment]
Digital Ocean is flat rate and has many different "droplets" that can be spun up in about 55 seconds. Each droplet can be scaled from $5 to $640 per month of resources.

I had seen and dealt with a couple edits but was unaware you were seeing stuff elsewhere. I'm happy to lock it down and roll it back. I will put the polycarbonate down tonight and go flush out the wiki.

We don't need you distracted from working on Marlin.

PIDs in bad shape. Those positive excursions cook Taulman Bridge and jam a RRD Hexagon. :-(

Scotty

**Comment by scotty1024** [comment]
I’ve installed Nuke and I’m cleaning it all out which is also deleting the users accounts.

Fortunately I didn’t pop for the $5 droplet so this is going very quickly.

Probably quicker to have just dusted off and nuked it from orbit but I’m having fun mowing the SPAM pages.

**Comment by scotty1024** [comment]
Locked down, all accounts deleted but one, main page erased, g-code page saved and no one has changed the main page in an hour. 

I think it’s cleaned out and locked out.

**Comment by thinkyhead** [comment]
Cool. If my account there had Edit access, I could restore the front page, etc.

**Comment by scotty1024** [comment]
Yes sir, just waiting to let them do their worst to get back in. I never realized there was so much money to be made in warning the world about the dangers of femdom's. :-)

I'm also granting your ssh account access to "sudo service apache2 restart" and "sudo shutdown -r now".

I've run the maintenance scripts to clean up the database after our recent departure of 100,000+ unwelcome users and pages.

Anyone else wants a wiki account please speak up. I'm adding them via command line. The front door now has an account request queue, which I figured would also be abused. So I have it set to require a 100,000 word biography to request an account.

**Comment by scotty1024** [comment]
@Thinkyhead I’ve loosened then re-tightened back a quarter turn. Your old account should be active and capable of edits. The 'user' group has some vulnerability in it so if you want to adjust please don’t tweak anything related to ‘user’.

**Comment by thinkyhead** [comment]
My "Thinkyhead" account there still can't edit. :cry:

**Comment by scotty1024** [comment]
I thought I gave you enough soup, I’ve up’d you some more.

**Comment by thinkyhead** [comment]
Power is a beautiful thing…

**Comment by thinkyhead** [comment]
Down again!

**Comment by thinkyhead** [comment]
Down today too… @scotty1024 any idea what's causing it?

**Comment by boelle** [comment]
was  up today so closing again

**Comment by indazoo** [comment]
Hi today it is down too:
Sorry! This site is experiencing technical difficulties.

Try waiting a few minutes and reloading.

(Cannot contact the database server)
