### ISSUE TITLE
[BUG] Sensorless homing - endstops always TRIGGERED

### ISSUE THREAD

**Issue by b3nnb** [MarlinFirmware/Marlin#17757]
### Bug Description

Sensorless homing failes to home. the Endstops always report as **TRIGGERED**.
When i try to home, i can hear the motors engage but not do anything. on the screen of the printer i see the Z distance jump from 250 to 260 for a split second.
I cannot inver the logic as sensorless homing requires the endstops to be **false**.
The axis will move up and down when controlling manually, all 3 towers move correctly.
I have tried a bunch of fixes that others have gotten to work but mine has not.
The sensitivity has been adjusted and test from 0 to 255 in increments of 20

This works when using mechanical endstops.

### My Configurations

Kossel mini
Bigtreetech skr v1.3
Bigtreetech tmc2209 v1.2
Marlin Bugfix 2.0.x

I have no jumpers under the drivers, i only have them on the red UART pins beside the steppers and on the pins beside the endstop connectors. all for X/Y/Z

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
I will post the configs soon I have to get them off my other computer

### Steps to Reproduce

1. G28
2. Watch nothing happen

**Expected behavior:** [What you expect to happen]

All axis should home to the top and stop. setting that to the max z height

**Actual behavior:** [What actually happens]
homing does not occur, motors engage but done move

**Comment by JohnnyTheOne** [comment]
Sensitivity TMC2209 Use M914 X Y Z to set the stall threshold at runtime
   *    HIGHEST       255  
   *    LOWEST         0     

CURRENT_HOME X_CURRENT to CURRENT_HOME  400

**Comment by rglory** [comment]
~~I believe you need to flip logic of endstops.~~ I have working sensorless configuration  with SKR 1.3 and TMC2209 and normally (always) M119 shows X and Y endstops status as **open**. Note TMC2209 keep DIAG signal low and raise up for short period of time when stallguard detected so you should never see them in **TRIGGERED** state.

UPDATE: I missed your message that you have X_MIN_ENDSTOP_INVERTING false. I do have it also false and my endstop statuses for X and Y (where I use 2209 and sensroless homing) are always open. Looks like something wrong with you hardware configuration. Most probably that DIAG pin is not connected to endstop. You probably need to trace it - it should be in low state (low voltage) normally. Just mesure voltage on those endstop pins that enables sensorless homeing for start.

Also with SKR 1.3 I had issue with motor shakes X or Y and then controller goes to halt state. It started to work properly after I turned TMC_DEBUG on. Hope that helps.

**Comment by b3nnb** [comment]
> CURRENT_HOME



> Sensitivity TMC2209 Use M914 X Y Z to set the stall threshold at runtime
> 
> * HIGHEST       255
> * LOWEST         0
> 
> CURRENT_HOME X_CURRENT to CURRENT_HOME 400

I tried the M914 as well as setting in the firmware, a bunch of settings between 0.and 255.
my current home is set to 700-800. thats usually where i set it for the steppers i have. do you think thats too high?

**Comment by b3nnb** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4542489/Configuration.zip)

heres my config and config_adv

**Comment by b3nnb** [comment]
> ~I believe you need to flip logic of endstops.~ I have working sensorless configuration with SKR 1.3 and TMC2209 and normally (always) M119 shows X and Y endstops status as **open**. Note TMC2209 keep DIAG signal low and raise up for short period of time when stallguard detected so you should never see them in **TRIGGERED** state.
> 
> UPDATE: I missed your message that you have X_MIN_ENDSTOP_INVERTING false. I do have it also false and my endstop statuses for X and Y (where I use 2209 and sensroless homing) are always open. Looks like something wrong with you hardware configuration. Most probably that DIAG pin is not connected to endstop. You probably need to trace it - it should be in low state (low voltage) normally. Just mesure voltage on those endstop pins that enables sensorless homeing for start.
> 
> Also with SKR 1.3 I had issue with motor shakes X or Y and then controller goes to halt state. It started to work properly after I turned TMC_DEBUG on. Hope that helps.

TMC_DEBUG is enbaled, when i run an M122 i get everything i would expect as an output like stallgaurd enabled and thr set to _whatever i set it to at thet time_.
what should i be testing and lookign for on the diag pin. i thought with combining the 2 bigtreetech pieces(driver and skr 1.3) that it would have been setup for that.

forgive me im not the most knowledgeable in the marlin world

**Comment by rglory** [comment]
I am not sure than TMC_DEBUG is the only thing I changes though. But the fact is it had that behavior - no matter what I do, stepper just moved it left and right aliitle  and then controller hangs with bad state. I tried different things and then I changed TMC_DEBUG and probably something else, rebooted and suddenly it all started to work flawlessly. I used exactly the same configuration as you do - Bigtreetech skr v1.3 and Bigtreetech tmc2209 v1.2

Try to measure voltage on those DIAG pins, they should be low (mine has aroun 0.2V) and enstop status should be "open". If they are not low and connection is fine then looks like you need to deal with some settings to make that pin on TMC driver active.

**Comment by rglory** [comment]
Wait a sec, I am wrong. I have SKR v1.4 from Bigtreetech, but 1.3 is from Witbot:
https://www.amazon.com/gp/product/B07P72KGTQ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

And I looked into product image on bigreetech github and unlike Witbot on their picture does not show DIAG connection on motherboard:

![SKR_PINS](https://user-images.githubusercontent.com/64332764/80433054-e201f200-88c3-11ea-868e-86f94efb1854.jpg)

from here - https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/BTT%20SKR%20V1.3/Wiring%20diagram/SKR%20V1.3%20Product%20Top%20Picture.jpg

Though amazon page for bigreetech SKR v1.3 does show those pins. I am confused. Does your board have those pins or not? If they do not solder then it certainly would not work, as second one is the DIAG pin.

**Comment by b3nnb** [comment]
ya mine has the pins installed @rglory same as https://images.app.goo.gl/PxSARPgibmferY1n9 but without the jumpers installed

**Comment by rglory** [comment]
> ya mine has the pins installed @rglory same as https://images.app.goo.gl/PxSARPgibmferY1n9 but without the jumpers installed

OK then you need to measure voltage on DIAG pin - 
![skr1 3](https://user-images.githubusercontent.com/64332764/80434171-0dd2a700-88c7-11ea-87ee-20b79de1b06a.jpg)

of course with TMC2209 installed. I marked them for X, for others the same way. It should show the same low voltage against ground.

**Comment by b3nnb** [comment]
ok so just measure the voltage POS on the DIAG of the driver and NEG on the endstop of the matching axis?

**Comment by rglory** [comment]
Just measure voltages on those 2 points separately against ground. Ground can be on on middle pin on endstop, can be minus on power, or even case of USB connector should work - it's the same ground. Btw sorry for silly question - you do not have endstops connected and the same time to those axes, do you?

**Comment by b3nnb** [comment]
lol, ya no worries. no mechanical endstops are connected. ill measure those when i get a chance

**Comment by b3nnb** [comment]
@rglory i measured the voltage and im getting about 0.02-0.03 with my multimeter set to 20V.
and its the same on the endstop jumpers and the the DIAG pins

**Comment by rglory** [comment]
What is output of M119?

Nevermind, I looked into your config. The thing is those DIAG pins are connected by jumpres to XMin and YMin endstops so you have to either switch to min endstops instead of max by uncommenting #define USE_XMIN_PLUG #define USE_YMIN_PLUG etc or override PINS accordingly so firmware would use min pins as max endstops. Or rewire diag pins manually.

**Comment by b3nnb** [comment]
really? since my probe uses ZMIN, how would i change that to use something else so i can use the ZMIN for the homing?

**Comment by b3nnb** [comment]
i thought DELTAs ALWAYS used the MAX endstops, if i disable the MIX pins i get an error compiling

**Comment by rglory** [comment]
Ah right you have delta. The issue that SKR v1.3 is wired on hardware level that X stepper controller DIAG pin is wired to -x pin when you install that jumper on top of endstops. I think you can override that though and make X_MAX to use pin which is normally used as X_MIN and so on. Or you can manually rewire using cables that came with TMC2209, remove those jumpers and plug them. But I think that more messy. So you can try this and see if it compiles and works:

#define X_MAX_PIN X_DIAG_PIN
#define Y_MAX_PIN Y_DIAG_PIN
#define Z_MAX_PIN Z_DIAG_PIN

also you would need to move your probe out of hardware -z connector. If you move it to z+ you probably should add this:

#define Z_MIN_PIN P1_24

 Let me know if that helps. I could be wrong, somebody who is more familiar with marlin internals may correct me.

**Comment by b3nnb** [comment]
so uncommenting the XMIN YMIN cause homing to go int the wrong direction for about 10mm and stop.
then i tried flipping the axis direction and homing will go up about 10mm and stop still but the Z motion is flipped
side issue, i dont know what i did but suddenly my E Driver vref wont go above .26. i was getting a error from M122 about it. so if i cant find a way to fix it, ill have to use a tmc2208_standalone from my previous board

**Comment by b3nnb** [comment]
@rglory are you talking about this part in the pins.h file

```
//
// Assign endstop pins for boards with only 3 connectors
//
#ifdef X_STOP_PIN
  #if X_HOME_DIR < 0
    #define X_MIN_PIN X_STOP_PIN
    #define X_MAX_PIN -1
  #else
    #define X_MIN_PIN -1
    #define X_MAX_PIN X_STOP_PIN
  #endif
#elif X_HOME_DIR < 0
  #define X_STOP_PIN X_MIN_PIN
#else
  #define X_STOP_PIN X_MAX_PIN
#endif

#ifdef Y_STOP_PIN
  #if Y_HOME_DIR < 0
    #define Y_MIN_PIN Y_STOP_PIN
    #define Y_MAX_PIN -1
  #else
    #define Y_MIN_PIN -1
    #define Y_MAX_PIN Y_STOP_PIN
  #endif
#elif Y_HOME_DIR < 0
  #define Y_STOP_PIN Y_MIN_PIN
#else
  #define Y_STOP_PIN Y_MAX_PIN
#endif

#ifdef Z_STOP_PIN
  #if Z_HOME_DIR < 0
    #define Z_MIN_PIN Z_STOP_PIN
    #define Z_MAX_PIN -1
  #else
    #define Z_MIN_PIN -1
    #define Z_MAX_PIN Z_STOP_PIN
  #endif
#elif Z_HOME_DIR < 0
  #define Z_STOP_PIN Z_MIN_PIN
#else
  #define Z_STOP_PIN Z_MAX_PIN
#endif

```

and change Z_MAX_PIN to Z_DIAG_PIN type thing?

**Comment by rglory** [comment]
I dont think Vref is used when you configure drivers through UART. Anyway I suggest you check Marlin configuration repository for example configs for delta printers on SKR v1.3. Most probably somebody already hit this problem before. 

Actually that part shows if you configure homing directions as positive and enable sensorless homing marlin should already use min endstop pins as max ones. You would need to plug your probe to Z+ for example and configure pin accordingly.

Sorry for the mess I am not familiar with the code.

Alternative solution if you do not want to mess with firmware is to use cables that come with TMC2209. So you keep firmware config as it is, remove DIAG pins jumpers and rewire those pins by cables.

Here you can see why you cannot use +endstops with diag using jumpers:

![SKRpinoutpic](https://user-images.githubusercontent.com/64332764/80486683-95e99880-8929-11ea-814d-5245d1791a87.jpg)

so possible wiring solution for Z is to connect 2 pins with wire:

![SKRpinoutpic2](https://user-images.githubusercontent.com/64332764/80486917-eb25aa00-8929-11ea-98fb-23098f31fbd1.jpg)

then stallguard should work for +Z and do the same for X and Y accordingly

**Comment by b3nnb** [comment]
Sorry, i only tried adjusting it after i saw the Error: LOW when i ran M122. For the configs, my configs came from the examples. once i moved from 1.1.9 to 2.0.x i figured i would start from scratch, and here i am, lol.

Thanks, ill give the wiring a try. i REALLLLLLLY WANT sensorless homing on this printer!

i wish there were more docs on getting this working with DELTAs. im still waiting for a response to see if they have any recommendations.
I tried a bare Marlin 2.0.x from scratch. i tried bigtreetechs marlin branch for this specific board.

**Comment by rglory** [comment]
I could help you making it work online but unfortunatelly in this format it happens too slow.

So looking at source code it seems that when sensorless homing is enabled and homing direction is positive marlin already would use negative hardware endstops as max ones on SKR 1.3. So I suggest you start with debugging your enstops. Roll back to your original Marlin 2.0 configuration if you messed with pins etc. Sensorless  homing should be enabled, homing directions are positive for X Y and Z. Remove diag jumps. Start with X. Connect mechanical endstop to **-X** (left connecter where 1.29 pin) and validate that M119 status for **x_max** is changed when you trigger it. Actual state is not important. If it does not you need to dig deeper. If it does do the same for Y and Z. Note you cannot use -Z for probe, you will have to switch to another. But you want to make negative endstops work as max ones first. Then you can test sensorless homing. Then you can reconfigure probe.

**Comment by b3nnb** [comment]
I GOT IT WORKING!!
I just decided to start from scratch on everything.
other then setting the board and the drivers and #define delta, i did what you mentioned first. enabling the neg endstops.
then enabled sensorless homing. this is all stuff i did before but i think i was more scattered with how i got there since its my first marlin 2.0.0

**Comment by rglory** [comment]
I am glad it works!

Cheers
