### ISSUE TITLE
[FR] Hotend extrusion capacity feedrate limiter ' for devs'

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#17758]
Hi , I'm dreaming of this option ,  because if print too speed , filament is at 210 but after 10cm at 198 and the more the extrusion go on , the more the temp go down

The best idea is to know the capacity of a classic , volcano , or super volcano
To set the limiter , and the print will adapt feedrate
The outlines will always have same color , no mat , no gloss because of overextrusion 

I can make it , but i need , to better know planner ' variables ' , and if you can help , by giving some short code to have all variables needed

In planner , we have speed_factor ..... i need  total steps of the block , and time of the block , with theses three datas , i can make a limiter by dividing speed_factor if extrusion overload

May be someone have time to make a sketch

Thanks

**Comment by ErwinRieger** [comment]
@studiodyne: JFYI, i did this [here](https://github.com/ErwinRieger/ddprint). Using a flowrate sensor the melting capacity of a given machine/filament combination is measured and stored in a material profile. When printing, the speed of the machine is limited by the currently possible flowrate.
