### ISSUE TITLE
Mesh validation G26 unsafe z end

### ISSUE THREAD

**Issue by tablatronix** [MarlinFirmware/Marlin#17756]
2.0 bugfix ender 3 default config

Set manual mesh leveling
G26

After finishing, the Z height does not clear safe distance, gouges bed.

![CF2DDC3E-58AE-452D-B59A-3CDD9A56FFBB](https://user-images.githubusercontent.com/807787/80409156-fa571a00-888d-11ea-8083-67b21d035b67.jpeg)

**Comment by tablatronix** [comment]
Code looks like it should be doing this ok, not sure whats going on here, but it definitely did not.


`#define Z_CLEARANCE_BETWEEN_PROBES  5 // Z Clearance between probe points`

```C++
 // G26()
  retract_filament(destination);
  destination.z = Z_CLEARANCE_BETWEEN_PROBES;
  move_to(destination, 0);                                    // Raise the nozzle

  destination = g26_xy_pos;                                   // Move back to the starting XY position
  move_to(destination, 0);                                    // Move back to the starting position
```

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
