### ISSUE TITLE
[BUG] MKS SGEN L - axis X and Y moving away from endstop when homing Z

### ISSUE THREAD

**Issue by 48design** [MarlinFirmware/Marlin#17769]
### Bug Description
I can move the steppers like they should, homing X and homing Y is working fine but when Z is going to home both other axis are moving to their maximum and crashing into the frame.

### My Configurations
- endstops and directions configured
- z-probe installed using the min_z plug

### Steps to Reproduce
Home Z

**Expected behavior:**
- homing X
- homing Y
- homing Z

**Actual behavior:** [What actually happens]
- homing X
- homing Y
- instead of homing Z both axis X and Y are running into the frame

**Comment by ellensp** [comment]
you have Z_SAFE_HOMING enabled and your X and Y steps/mm are wrong so that instead of moving to the center of the bed it moves into the frame.

**Comment by ellensp** [comment]
This is not a support forum.
These are generic questions not firmware bugs or feature requests

Please use one of the services listed in 
https://github.com/MarlinFirmware/Marlin/issues/14694

**Comment by 48design** [comment]
I'm sorry, you are absolutely right. Wrong place. The thing is: I tried to change steps/mm and I used the same settings and printer but with a different board (MKS GEN L, 8bit) and after switching the board and copying all the settings (beside the board specific ones) I get this strange failure. That's why I thought it must be firmware related.

**Comment by ellensp** [comment]
Go to the discord chat server https://discord.gg/n5NJ59y  lots of people able to help with configuration issues.

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
