### ISSUE TITLE
[BUG] MKS SGEN L - Servos not working

### ISSUE THREAD

**Issue by 48design** [MarlinFirmware/Marlin#17767]
### Bug Description
A servo connected to either servo 1 pins or servo 2 pins doesn't react on M280 (Servo Position) gcode calls. This leads to a nozzle change via servo using SWITCHING_NOZZLE not working, too. It seems it is completely ignored

### My Configurations
- SWITCHING_NOZZLE defined
- SWITCHING_NOZZLE_SERVO_NR set to 0 or 1

### Steps to Reproduce
- Either connect a servo to the servo1 or servo2 pins
- configure SWITCHING_NOZZLE with SWITCHING_NOZZLE_SERVO_NR 0 or 1
- M280 P0 (or P1) S45

**Expected behavior:**
The servo is turning

**Actual behavior:**
The servo does nothing

**Comment by ellensp** [comment]
This is not a support forum.
These are generic questions not firmware bugs or feature requests

Please use one of the services listed in 
https://github.com/MarlinFirmware/Marlin/issues/14694

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
