### ISSUE TITLE
Board Lerdge X  comiler Error

### ISSUE THREAD

**Issue by cjsoong** [MarlinFirmware/Marlin#17774]
Board Lerdge X compilation error:
Can someone provide the correct configuration.h & platformio.ini?
![Lerdge_X_error](https://user-images.githubusercontent.com/26795599/80496863-51e3ab80-899c-11ea-8f45-a4f685dd3d67.jpg)

**Comment by xC0000005** [comment]
I usually compile for lerdge in Arduino, then encrypt the firmware afterwards. The "correct" configuration.h depends on what printer you're putting it into.

**Comment by cjsoong** [comment]
> I usually compile for lerdge in Arduino, then encrypt the firmware afterwards. The "correct" configuration.h depends on what printer you're putting it into.

Structure like Creality Ender-5.

**Comment by Evg33** [comment]
@xC0000005 can you show #define SERIAL_PORT for Lerdge X ?

**Comment by Evg33** [comment]
@xC0000005 
with  default_envs = ARMED and -DHAVE_HWSERIAL1  compilation ok.
-DVECT_TAB_OFFSET must be 0x10000 or 0x8000 ?
Can you show platformio.ini section for LerdgeX ?

**Comment by cjsoong** [comment]
> @xC0000005
> with default_envs = ARMED and -DHAVE_HWSERIAL1 compilation ok.
> -DVECT_TAB_OFFSET must be 0x10000 or 0x8000 ?
> Can you show platformio.ini section for LerdgeX ?
> 
> Encoded by https://cdn.hackaday.io/files/1625926956336128/lerdgedecrypt2.py and flashed by stock bootloader, but no info on serial (esp connector/usb connector).
 @Evg33
Does TFT display work?  
How to upload to Lerdge motherboard?

**Comment by Evg33** [comment]
Don't need TFT. Need only serial or usb.

**Comment by sjasonsmith** [comment]
@xC0000005, when you build for Lerdge in Arduino, which HAL are you using: STM32 or STM32_F4_F7?

**Comment by xC0000005** [comment]
HAL STM32.

**Comment by Evg33** [comment]
> > How to upload to Lerdge motherboard?

Place encoded bin file to USB or SD and upgrade from menu.
(  https://cdn.hackaday.io/files/1625926956336128/lerdgedecrypt2.py  )

**Comment by boelle** [comment]
@cjsoong still an issue?

**Comment by cjsoong** [comment]
@boelle Compilation is currently OK.

**Comment by boelle** [comment]
ok, will then close as its fixed

if not we can always reopen
