### ISSUE TITLE
Prefered tool for dev chat...???

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1777]
We have IRC.... but every time i have been there it just felt like a giant parking lot.

IS IRC the preferred choice among those who active do bug fixing? or are things like Google hangouts more of the choice even thou it requires a G account?

**Comment by epatel** [comment]
Slack?

**Comment by Natealus** [comment]
Is Netmeeting still around? That was quite useful back in the day but there's many many options like that now. Hangouts seems like a well featured collaboration tool too.

**Comment by alexborro** [comment]
I use hangout and skype. They are nice for chatting.
Em 01/04/2015 19:13, "Nate Stokes" <notifications@github.com> escreveu:

**Comment by boelle** [comment]
Me using google anyways so i think hangout are going to be the norm...

For those who hate google... We cant let that hold back development work, you can just use google for this and nothing else. It nothing worse than using a login for IRC. That is if you only use google for hangouts

**Comment by Natealus** [comment]
And 15 gigs of free web storage too. Useful for sharing files among colleagues and friends.

**Comment by boelle** [comment]
@thinkyhead what is your thoughts?

**Comment by thinkyhead** [comment]
My preference would be for Google+ because I get notifications instantly. I don't leave IRC open all the time, or I might prefer that. Being in many time-zones does make real-time collaboration trickier.

**Comment by boelle** [comment]
could you create a hangout then for marlin ?

**Comment by thinkyhead** [comment]
Well, it's like other chat clients. I would need the gmail addresses of all people who would be invited to the hangout, and we would need to decide on a pre-arranged time. If we were to do a video hangout, then it could be recorded for posterity, and publication, to connect with the wider community.

I have a list of time-zones which we can add to. This one shows the times relative to me, and which times in each of their time-zones are convenient for me, at least for one-on-one chat about topics.

```
Name             Zone    GMT-7 Offset        GMT-7 awake        thinkyhead overlap       online weekdays      online weekend
@thinkyhead      GMT-7                       9am -  1am         9am -  1am
@clefranc        GMT-4   + 3 hours           6am - 10pm         9am - 10pm
@alexborro       GMT-3   + 4 hours           5am -  9pm         9am -  9pm
@fmalpartida     GMT-1   + 6 hours           3am -  7pm         9am -  7pm
@AnHardt         GMT+1   + 8 hours           1am -  5pm         9am -  5pm
@Wurstnase       GMT+1   + 8 hours           1am -  5pm         9am -  5pm
@boelle          GMT+2   + 9 hours          12am -  4pm         9am -  4pm               1pm - 8pm            ~8am - 10pm
@emartinez167    GMT+8   +15 hours = -9      6pm - 10am         6pm -  1am, 9-10am
@ntoff           GMT+10  +17 hours = -7      4pm - 12pm         4pm -  1am, 9am-12pm
```

**Comment by emartinez167** [comment]
ernesto.e.martinez@gmail.com 

Regards,

Ernesto

**Comment by alexborro** [comment]
alexborro@gmail.com GMT-3
Em 03/04/2015 22:31, "emartinez167" <notifications@github.com> escreveu:

**Comment by boelle** [comment]
i cleaned up the thread and added myself... i belive that GMT -1 is where i'm

then again there is summer time.... right now i'm 2 hours ahead of GMT

**Comment by boelle** [comment]
added hagnout link to the readme.. i might be there but cam and mic is off for now.... (want to pick my nose in piece)

**Comment by ntoff** [comment]
I'd love a forum or something, just to post random ideas instead of clogging up the issues thing in here with my dribble.

**Comment by thinkyhead** [comment]
…or your drivel. Your meaningless drivel…

**Comment by ntoff** [comment]
all of the above, i'll see myself out

**Comment by thinkyhead** [comment]
@ntoff Maybe, if the marlin wiki comes back we could use that. But here's an idea, why not start a topic at the RepRap forums? Just a general "Marlin Firmware" topic with a list of informal agenda items…

**Comment by ntoff** [comment]
GMT +10, I'm not a pro-coder though, I have no idea what I'm doing with C++. Took me ages to figure out how to add features to pronterface. Stupid python and it's lack of curly braces.

**Comment by thinkyhead** [comment]
@ntoff An interest in RepRap and open source is all that's required to have a worthwhile opinion. And often the best ideas come from a more naive perspective, not so conditioned by the way things are "supposed" to work.

**Comment by boelle** [comment]
@thinkyhead i looked at the table... in risk of screwing up i wondered if you could add the timespan where everyone is able to be online? but in each users local time?

**Comment by Wurstnase** [comment]
Lovely Python!
GMT +1 btw :)

**Comment by thinkyhead** [comment]
@boelle Users will have to contribute that information, when they will be online - I suppose the best unit would be UTC.

**Comment by boelle** [comment]
ok

but for me from about 15:00-22:00

weddensday all day

weekends the same

utc +2

Den torsdag den 9. april 2015 skrev Scott Lahteine <notifications@github.com

**Comment by boelle** [comment]
added 2 columns...

**Comment by fmalpartida** [comment]
Hi folks, 

count me in for a hangout, G+ account fmalpartida(a)gmail.com

**Comment by boelle** [comment]
link for hangout in the readme.md (frontpage on github), but here it is

https://plus.google.com/hangouts/_/g2wp5duzb2y6ahikg6tmwao3kua
