### ISSUE TITLE
MERLIN 2.0.x missing menu items 

### ISSUE THREAD

**Issue by geekgamer2001** [MarlinFirmware/Marlin#17784]
i just updated and i can't find auto home or half the features i saw on 1.1.9 including auto home

**Comment by geekgamer2001** [comment]
i see it in the code `  // Auto Home
  //
  GCODES_ITEM(MSG_AUTO_HOME, G28_STR);
  #if ENABLED(INDIVIDUAL_AXIS_HOMING_MENU)
    GCODES_ITEM(MSG_AUTO_HOME_X, PSTR("G28X"));
    GCODES_ITEM(MSG_AUTO_HOME_Y, PSTR("G28Y"));
    GCODES_ITEM(MSG_AUTO_HOME_Z, PSTR("G28Z"));
  #endif`

**Comment by ellensp** [comment]
so enable INDIVIDUAL_AXIS_HOMING_MENU in Configuration.h

**Comment by geekgamer2001** [comment]
but I just want to home all

**Comment by ellensp** [comment]
add the following line, after  GCODES_ITEM(MSG_AUTO_HOME_Z, PSTR("G28Z"));
 GCODES_ITEM(MSG_AUTO_HOME_ALL, PSTR("G28"));

**Comment by geekgamer2001** [comment]
and cooldown just saw that was missing

**Comment by zroadhouse** [comment]
I'm seeing similar disappearing "Auto Home" menu item after rebasing my config onto the most recent bugfix-2.0.x. Maybe Streamline menu item logic (#17664) changed something? I'm compiling now on the commit prior to that one to see.

**Comment by ellensp** [comment]
Cooldown only appears when hot end is hot

**Comment by geekgamer2001** [comment]
it was if i recall correctly

**Comment by geekgamer2001** [comment]
yeah i went to select cooldown to move my printer was heated

**Comment by zroadhouse** [comment]
Preheat PLA had also disappeared from the Temperature menu. Reverting bugfix-2.0.x to f709c565a1782111d464f1b0659d7b46a12a497d worked for me. Strongly suspect something in the #17664 change.

**Comment by geekgamer2001** [comment]
ya just saw that how odd it's like many options are gone I will try to revert to that soon

**Comment by ellensp** [comment]
What lcd's are you guys using?  (shouldn't make any difference, but...)

**Comment by Evg33** [comment]
And "Temp/Preheat PLA"
some menu items lost in space ? :)
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by geekgamer2001** [comment]
that produces an error

**Comment by thisiskeithb** [comment]
> Preheat PLA had also disappeared from the Temperature menu. Reverting bugfix-2.0.x to [f709c56](https://github.com/MarlinFirmware/Marlin/commit/f709c565a1782111d464f1b0659d7b46a12a497d) worked for me. Strongly suspect something in the #17664 change.

I can confirm that several items are missing from the menus after https://github.com/MarlinFirmware/Marlin/commit/4f003fc7a715830da7324da2c90f8411df3b1efc / https://github.com/MarlinFirmware/Marlin/pull/17664

**Comment by xoniq** [comment]
> And "Temp/Preheat PLA"
> some menu items lost in space ? :)
> #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

Same LCD, can confirm, just updated my printer to latest git version, I miss several items, but the first item I noticed, I wanted to home all, but its missing. And after above reply, I also miss the preheat PLA option.

**Comment by zroadhouse** [comment]
You can find my configuration here if its helpful => https://github.com/zroadhouse/Marlin/pull/1

**Comment by geekgamer2001** [comment]
well shall i close this since we know the root cause or wait till its fixed

**Comment by geekgamer2001** [comment]
in the meantime, I'm going to revert to  [4f003fc]
and write down all the menu options then go back to current and write down menu options for that and comment the missing menu items in #17664

**Comment by firepower9966** [comment]
Also missing Autohome in LCD menu, individual homing is enabled. using 2004 Smart LCD

**Comment by xoniq** [comment]
Another thing I cannot find back: cool down. I had the printer hot to change filament, but I could not cool it down without going to temperature and set it to 0.

**Comment by geekgamer2001** [comment]
yeah and cooldown is a important feature

**Comment by geekgamer2001** [comment]
revert to 4f003fc for now as that has all options

**Comment by thisiskeithb** [comment]
> well shall i close this since we know the root cause or wait till its fixed

Please leave this issue open so it can be tracked.

**Comment by thisiskeithb** [comment]
The breaking changes were reverted in https://github.com/MarlinFirmware/Marlin/commit/e8b0796fc70d06f59cb217dbe11a2ad695243ad1, so this issue can be closed.

**Comment by Evg33** [comment]
all ok

**Comment by thisiskeithb** [comment]
Yes, I tested the changes as well and can confirm it's been fixed 🙂

**Comment by chepo92** [comment]
Lol I just synced yesterday and facing this issue, syncing again

**Comment by Evg33** [comment]
@chepo92 fixed in "Revert menu_item_if ahead of refactor" https://github.com/MarlinFirmware/Marlin/commit/e8b0796fc70d06f59cb217dbe11a2ad695243ad1
