### ISSUE TITLE
[FR] Change direction of second X-Carriage on IDEX Printer

### ISSUE THREAD

**Issue by Markus-1984** [MarlinFirmware/Marlin#17792]
### Description

I´m looking for the option to change the direction of the X2 stepper on my IDEX Printer like it´s implemented in X_DUAL_STEPPER_DRIVERS.
There is the option #define INVERT_X2_VS_X_DIR true/false

**Comment by SrGeek** [comment]
Has this option been implemented yet?

**Comment by charlespick** [comment]
it hasn't, I just got an idex working the other day and ended up just switching the wires. I have an idea for how to implement this, if I open a pr later today you'll know the idea worked out...
