### ISSUE TITLE
M117 replaces colon (':') by space (' ') on LCD screen in Marlin FW version 2.0.5.3

### ISSUE THREAD

**Issue by jopl** [MarlinFirmware/Marlin#17795]
### Bug Description

On LCD screen: every colon (':') inside the string following M117 command is replaced by space. I am not sure if this is right behaviour, but as the repetier server sends ETA time (ETE is similar) in format "HH:MM:SS Day XX", resulting string is "HH MM SS Day XX", which is unpleasant.

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. Go to web page of Repetier Server (ver. Free 0.93.1 in my case)
2. On Console page ("http://A.B.C.D:3344/#!/printer/sCube/console" in my case) type down in command line text "M117 ETE 14:37:17 Day 29" and press "Send" button
3. See LCD screen. It shows "ETE 14 37 17 Day 29", i.e. without colons

**Expected behavior:** [What you expect to happen]
"ETE 14:37:17 Day 29" on the LCD screen

**Actual behavior:** [What actually happens]
"ETE 14 37 17 Day 29" on the LCD screen, i.e. without colons

**Comment by jopl** [comment]
Configuration files & picture of LCD screen after command "M117 ETE 14:37:17 Day 29"

[Marlin_2053_configuration_files.zip](https://github.com/MarlinFirmware/Marlin/files/4551739/Marlin_2053_configuration_files.zip)
![Colons_missing](https://user-images.githubusercontent.com/401876/80597988-f57a9d80-8a28-11ea-8db7-f0cadd0e5c03.jpg)

**Comment by thisiskeithb** [comment]
Tried the latest `bugfix-2.0.x`? I just sent `M117 ETE 14:37:17 Day 29` through OctoPrint and it works:
![5F39F1E5-C205-4D8F-BF2E-5AB0AFF24B15](https://user-images.githubusercontent.com/13375512/80676761-54153b00-8a6c-11ea-9aa5-e983c63462cd.jpeg)

**Comment by jopl** [comment]
I found out the problem origin. Repetier server removes the colons from the command line starting with version 0.75.2 ( https://forum.repetier.com/discussion/2009/pi-0-75-1-extruder-temperature-reported-incorrect-and-extrusion-stopped ). But there is also written: "in firmware definition for the server it can be disabled".

**Comment by ellensp** [comment]
So not a marlin issue. Can you close the job? thanks.

**Comment by jopl** [comment]
Before closing the issue, I would like just to mention I found the solution:
Edit line in marlin.xml file by ssh client, i.e. write on command line for example in putty:
**sudo nano /usr/local/Repetier-Server/firmware/marlin.xml**
Find string "ascii" (CTRL+W), it should be at line:
**\<com okAfterResend="false" protocol="ascii" allowColonInAscii="false"/>**
Change the appropriate "false" for "true" at the end of line, i.e.:
**\<com okAfterResend="false" protocol="ascii" allowColonInAscii="true"/>**
But it is still not tested, so be carefull ...
