### ISSUE TITLE
Compiling error on current #1771 build

### ISSUE THREAD

**Issue by Natealus** [MarlinFirmware/Marlin#1779]
I'm having an odd issue. I tried a couple of things to fix cause it seems to be in a SD card section about SD printing messages, so I reverted the other two merges after the latest bed leveling fixes but it didn't seem to help. Anything here more obvious to others than myself? :)

Arduino: 1.6.1 (Windows 8.1), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from Marlin.h:16:0,

```
             from Marlin_main.cpp:30:
```

Marlin_main.cpp: In function 'void get_command()':

Marlin_main.cpp:846:35: error: expected ')' before 'MSG_END_HOUR'

```
     sprintf_P(time, PSTR("%i "MSG_END_HOUR" %i "MSG_END_MINUTE),hours, minutes);

                               ^
```

Error compiling.

**Comment by AnHardt** [comment]
@Natealus 
Exactly this i tried to fix with #1771.
You have no display defined. Haven't you?
Please try again.

**Comment by Natealus** [comment]
Yeah I have my Viki 2 defined. I didn't change that.

**Comment by AnHardt** [comment]
@Natealus 
I'll have a look.

**Comment by Natealus** [comment]
Given that idea though I tried disabling the LCD system by commenting out #define VIKI2 and #define Temp_Stat_LEDS and it did compile sucessfully.

**Comment by AnHardt** [comment]
@Natealus 
Greped for VIKI2:
      ..Marlin\Marlin\configurator\config\Configuration.h (1 hit)
    Line 646: //#define VIKI2

that's all! ???

**Comment by AnHardt** [comment]
@Natealus 
Sorry have been in an other directory than i supposed.

**Comment by AnHardt** [comment]
@Natealus 
Again sorry. Can't reproduce this. For me this compiles as it should. Tried all combinations of VIKI2 and Temp_Stat_LEDS - makes no difference for me.

**Comment by Natealus** [comment]
Hmm yeah all I had to do to compile was comment my lcd subsystem out. What board do you have defined? Does it have pins for Viki2? I'm using an Azteeg X3 Pro.

**Comment by Natealus** [comment]
I've also allocated a kill pin which wasn't on the original Viki 2 manual for my board but...I'm not sure that would be related? The only pinsets for the Viki 2 I could put in were ones for boards they had specified. I'm sure it would work on just about any board but I don't know their pinouts and setups well enough to guess at pin sets for other boards.

**Comment by AnHardt** [comment]
For compilation i used 'BOARD_AZTEEG_X3_PRO'
But that does not matter as long as the VIKI-Pins are in.
VIKI2 defines ULTRA_LCD in Conditionals.h line 20.
The macro causing the error is defined in ultralcd.h line 11 for ULTRA_LCD - the original place @thinkyhead  put it in.
ultralcd.h is loaded in  time by Marlin_main.cpp.
I can't find the error.

Could you please upload your configuration somewhere?

**Comment by Natealus** [comment]
Sure some of the bed leveling stuff is off normal but thats cause I've been testing bug on it.

<script src="http://pastebin.com/embed_js.php?i=VvwTKkfv"></script>

**Comment by boelle** [comment]
please put long files like that on pastebin.com

**Comment by Natealus** [comment]
Hmm the embedding doesn't seem to be working

**Comment by Natealus** [comment]
<iframe src="http://pastebin.com/embed_iframe.php?i=VvwTKkfv" style="border:none;width:100%"></iframe>

**Comment by Natealus** [comment]
<script src="http://pastebin.com/embed_js.php?i=VvwTKkfv"></script>

**Comment by thinkyhead** [comment]
@Natealus I also saw the issue you're referring to - but not there, I got an error because of string concatenation in the language file. And the cause was that one of the macros it was trying to concatenate was undefined, so the compiler saw `"string1"0"string2"`. I'm not sure that's your issue, but check and make sure those defines are really defined.

**Comment by Natealus** [comment]
I'm going to do a clean reconfigure off the current merge and see if that solves the LCD issue and leveling and test test test. :)

**Comment by Natealus** [comment]
Well now I get a different message. I tried other LCD defines like REPRAP GRAPHICAL and SMART LCD and they give me the same error.

Arduino: 1.6.1 (Windows 8.1), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

ultralcd.cpp.o: In function `_lcd_move':

C:\Users\Nate\AppData\Local\Temp\build2590251393999223928.tmp/ultralcd.cpp:673: undefined reference to `refresh_cmd_timeout()'

C:\Users\Nate\AppData\Local\Temp\build2590251393999223928.tmp/ultralcd.cpp:673: undefined reference to `refresh_cmd_timeout()'

C:\Users\Nate\AppData\Local\Temp\build2590251393999223928.tmp/ultralcd.cpp:673: undefined reference to `refresh_cmd_timeout()'

collect2.exe: error: ld returned 1 exit status

Error compiling.

**Comment by Natealus** [comment]
Well this particular issue's error must've been fixed but another occurred but I have a separate issue for that and this one should probably be closed.
