### ISSUE TITLE
[BUG] Re-ARM Thermal Runaway

### ISSUE THREAD

**Issue by psavva** [MarlinFirmware/Marlin#17809]
### Bug Description
Thermal Runaway is triggered with the Re-ARM Board.

I heated the hotend to 240 deg Celsius, and just let Repetier record the issue as it was happening.
Check the image below: 
![image](https://user-images.githubusercontent.com/1454758/80725446-bffab080-8b0b-11ea-8b53-0cc0eff7f7cf.png)

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4559095/Marlin.zip)

Current revision of Marlin is: 015c4e6fbdd28f5c4cb5fc987d4f4ae513b1c13d

### Steps to Reproduce

Set the Target Tempreture of 240 Deg Celcius on the LCD for the Extruder and Wait.
Thermal Runaway is triggered (see graph above)

#### Additional Information

I had this issue happening with 2 different Thermistors.

**Comment by GMagician** [comment]
Looking at hotend pwm, Marlin seems to react correctly. Have you checked the cartridge?

**Comment by ellensp** [comment]
Seems to slowly cool down, my guess would be the thermistor is not tight on the hot end, or the fans are blowing on the hotend not the extruded plastic.

**Comment by psavva** [comment]
This test was done with the fan off.

I will try with thermal paste and see if it makes a difference...

**Comment by psavva** [comment]
Issue is the thermistor
