### ISSUE TITLE
Remove ENDSTOPPULLUPS option

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#1781]
Discussed in #1749. Remove the main `ENDSTOPPULLUPS` option altogether, then put the individual endstop pullup options into `Configuration_adv.h`

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
