### ISSUE TITLE
[BUG] Line on center screen not working with CR10 display

### ISSUE THREAD

**Issue by p-r-o-m-e-t-h-e-u-s** [MarlinFirmware/Marlin#17812]
![Display](https://user-images.githubusercontent.com/5257019/80746054-8c2a8580-8b21-11ea-8d6e-c38d9682f439.png)

### Bug Description

One horizontal line in the middle of the screen is tuned off. This line does not work as soon as the power is turned on and the printer is booting.

Tested on branch `bugfix-2.0.x` from 2020-04-30 => Screen has issue
Tested on branch `bugfix-2.0.x` from 2019-12-22 => Screen works perfectly

### My Configurations

Running **Ender 3** with a **MKS SBase** board.

```
//
// Factory display for Creality CR-10
// https://www.aliexpress.com/item/32833148327.html
//
// This is RAMPS-compatible using a single 10-pin connector.
// (For CR-10 owners who want to replace the Melzi Creality board but retain the display)
//
#define CR10_STOCKDISPLAY
```
[Archiv.zip](https://github.com/MarlinFirmware/Marlin/files/4560529/Archiv.zip)

### Steps to Reproduce

Just install lates 2.0.x branch. When I downgrade the firmware to my older version, it works again. 
So it's easily reproducible.

**Expected behavior:**
All lines are working on screen.

**Actual behavior:**
One non-working line on screen.

**Comment by ellensp** [comment]
And there is the solid line along the top of your image.  
your description seem wrong. Same release date it works and doesn't work...?  Suspect a date is wrong.

**Comment by p-r-o-m-e-t-h-e-u-s** [comment]
Yes, you are right. I've changed the date. Thx.

**Comment by boelle** [comment]
@p-r-o-m-e-t-h-e-u-s still an issue?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
