### ISSUE TITLE
PIDTEMPBED settings not saved in EEPROM

### ISSUE THREAD

**Issue by MoonshineSG** [MarlinFirmware/Marlin#1782]
Bed PID settings (created with "M303 E-1") don't make it into EEPROM

**Comment by tonnico** [comment]
Do you saved this with M304 E-1 Pxx Ixx Dxx?

**Comment by MoonshineSG** [comment]
I save it with M304 Pxx Ixx Dxx. Does M304 has E-1 as well ?

**Comment by tonnico** [comment]
Sry, yes you are right. M304 don't need a E. It's just for the bed. To save this value in the EEPROM you need an additional M500. Otherwise it will reset the values after a restart.

**Comment by MoonshineSG** [comment]
Yes I do a M500 after setting the values with M302. Either the value doesn't get saved or doesn't get restored...

**Comment by tonnico** [comment]
Ok, the pidbedtemp is missing in the eeprom. This is could be set to a "verfied bug".

**Comment by thinkyhead** [comment]
#1796 addresses the missing value, bumping the EEPROM version to V19.
