### ISSUE TITLE
[BUG] Layershift every whole hour

### ISSUE THREAD

**Issue by mberntsen** [MarlinFirmware/Marlin#17822]
### Bug Description

Every time the print timer goes from xx:59 to xx:00 a layer shift appears in the print. My print takes a little over 6 hours and has 6 layer shifts.
I've printed two identical parts with layer shifts on the same height (when comparing visually).
I witnessed it happening when the print went from 4:59 to 5:00, a layer shift of a few mm appeared.
Shifts are not allways in the same direction, but heating before print start has a variable duration, so this might create a variation on the exact location in the file where the printer is at on the hour increase.

### My Configurations

zip file with config can follow later on request but my setup is as follows:
marlin version 2.0.5.3 (commit 0518dec60d0931745efa2812fa388f33d68cfa29)
Anycubic Predator, config files modified based on the Anycubic Kossel config file.
custom electronics with tmc2209 steppers, esp32, sd card and more on breadboard.
I2C oled display with U8g2 lib (yes, modified source to get this to work)
ESP3D-WEBUI

### Steps to Reproduce
start a print with duration > 1 hour

**Expected behavior:** [What you expect to happen]
no layer shifts

**Actual behavior:** [What actually happens]
layer shift on hour increase

#### Additional Information
![IMG-20200501-WA0013](https://user-images.githubusercontent.com/3646306/80805524-964b9300-8bb8-11ea-83a6-f725a1cbe5db.jpeg)

Edit 2:
I just found this as a very likely cause:
`
/**
* @brief Interval in seconds between EEPROM saves
* @details This const value defines what will be the time between each
* EEPROM save cycle, the development team recommends to set this value
* no lower than 3600 secs (1 hour).
*/
static constexpr uint16_t saveInterval = 3600;
`

**Comment by o-nix** [comment]
I am currently suffering from random Y-axis **TMC2209** layers shifts, but I am not sure it is Marlin itself. Also, mine are not time-bound and I have EEPROM disabled.

**Comment by mberntsen** [comment]
> I am currently suffering from random Y-axis **TMC2209** layers shifts, but I am not sure it is Marlin itself. Also, mine are not time-bound and I have EEPROM disabled.

How do you know it's random?

**Comment by sjasonsmith** [comment]
@mberntsen I assume you have `PRINTCOUNTER` enabled? Try disabling it and see if the problem goes away.

**Comment by mberntsen** [comment]
I've put two slashes before saveStats(); to disable it  and the print went fine tonight. when I've got time i'll try to debug the issue, see where the delay comes from within the eeprom saving..

**Comment by Azrael321** [comment]
Since today, i get layershift, too. Yesterday is run a print with about 6h and everything was fine (Bugfix_20200502). Today i used the new Bugfix_20200503 and i get a layershift in -Y after 1h of printing time. This layershift performs over 2 - 3 layers, this means i get a layershift in -Y and the next layer the same again. Before that layershift is can hear a strange "Crack" from somewhere i can't locate.

Edit: I ran the same print 3 times and the layershift appears exactly after the same time (1h), at the same layerhight and on the same extruder position.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4570289/Configuration.zip)

Edit: Hardware today is the same as yesteday. No changes on mechanic side. All TMC2208 drivers each are cooled by large heat sinks + 80mm fan. Driver current is is still the same for about 1 year without issues.

**Comment by Grogyan** [comment]
This is likely a driver overheating issue.
I had this happen to me, and found that the drivers were intermittently shutting off briefly. 

Adding a fan to cool down the drivers eliminates this issue. Or reduce the driver current

**Comment by GhostlyCrowd** [comment]
I'm in the same boat here.

I replaced the belts and y stepper, when replacing the y stepper i had to invert it as its a different stepper. and the layer shits changed direction from -y direction to +y shifting, with the axis inversion. I screwed around with it on the weekend and could not get it to stop layer shifting, its random but once it starts it just keeps on shifting like a stairway to print heaven.

**Comment by sjasonsmith** [comment]
@mberntsen, can you post your configuration files? I would like to see which hardware you are using.

**Comment by sjasonsmith** [comment]
@mberntsen are you still investigating this?

**Comment by mberntsen** [comment]
I'm sorry, been busy, i'll try to upload is this week :)

**Comment by boelle** [comment]
@mberntsen still an issue?

**Comment by mberntsen** [comment]
these are my configurations.
I've still disabled the saveStats() function, and have not seen a single print defect ever since. Even on larger prints (19h)

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4809956/Configuration.zip)
