### ISSUE TITLE
Bed size defined, yet centerpoint reads 1/4 size.

### ISSUE THREAD

**Issue by mjp808** [MarlinFirmware/Marlin#17830]
Something funky is going on with my skr 1.4 turbo in tarantula pro, 2208s and bltouch.  after homing, the extruder parks in the back right corner instead of centering. the center position reads x60  y61, but my bed size is defined 235 x 235. safe homing is defined, at x & y /2 bed size. I've only done the basic changes to marlin,  So I'm stumped, how do I define my bed size at the correct dimensions and get it to home centered? If all else fails, how do I factory reset the SKR, so I can rule out saved settings and focus on troubleshooting the firmware?

**Comment by ellensp** [comment]
DIdn't follow template, no config files. Seems like a support question not a bug.
Please see https://github.com/MarlinFirmware/Marlin/issues/14694

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
