### ISSUE TITLE
G28 Z0 homing very very slow

### ISSUE THREAD

**Issue by fitch22** [MarlinFirmware/Marlin#1783]
Built latest Marlin (as of couple hours ago) for Printrboard on Simple Metal.  When I run G28 with no arguments, homing speeds are as expected.  If I run G29, again speeds are as expected.  If I run G28 Z0, the extruder is raised at a snails pace, then lowered to the stop at expected speed, then raised and lowered to stop again at expected (slower) speed.  Only the first raise is painfully slow.

Is there a setting for this that I don't know about?

Thanks.

**Comment by Natealus** [comment]
Check out `HOMING_FEEDRATE` in `Configuration.h` and in `Configuration_adv.h`.

```
#define X_HOME_RETRACT_MM 7
#define Y_HOME_RETRACT_MM 7
#define Z_HOME_RETRACT_MM 7 // deltas need the same for all three axis
#define HOMING_BUMP_DIVISOR {13, 13, 13}  // Re-Bump Speed Divisor (Divides the Homing Feedrate)
```

Note I use a Delta but I believe these variables are in all setups. They're just all the same on mine because of the way deltas work. I notice that Z bump divisor is usually twice as much as X and Y on other setup's configs.

**Comment by fitch22** [comment]
Not sure if I was clear.  The sequence for homing Z by issuing G28 Z0 is:
painfully slow rise
normal decent until stop hit
normal speed rise
slower (half speed) decent until stop hit again

Everything seems to be at the rate I expect except that initial rise. This slow rise does not occur if I issue `G28` with no arguments, but since it then moves the extruder to the middle of the bed, I cannot issue `G29` afterwards.

But I will try changing the `HOMING_FEEDRATE` to see which of the steps is affected.

Thanks.

**Comment by Natealus** [comment]
Hmm the only time that effect happens for me is if I try to move any axis...x, y, z, or an extruder before I home with just a normal G28. It travels up to the endstops horribly slow. I don't have another type of printer besides Delta but from what I hear homing is kind of...opposite on other types I'm not sure I fully understand it yet until I build one. 

When I'm homed and my carriages are all at the top of the towers and clicks the endstops...I have my manually set home Z of 367.55 so the firmware knows it can travel down Z that far. And you set it so Z0 is appropriate nozzle height.

Is your printer supposed to home at Z0 normally?

**Comment by TechMasterJoe** [comment]
i just built it as of the last 20mins for my i3 and can confirm the bug is real
im debugging now
the speed problem only effects Z_RAISE_BEFORE_HOMING
digging deeper now

**Comment by tonnico** [comment]
The incredible slow part is in the config_adv

`#define HOMING_BUMP_DIVISOR {10, 10, 20}`

4mm/s / 20 = 0.2mm/s. With a retract of just 2mm this takes 10 seconds.

The old hardcoded values are {2, 2, 4}.

**Comment by TechMasterJoe** [comment]
mines been changed to {2,2,2} just for this test 
it's not the problem
and i have 8 start leadscrews for Z and can move well over 40mm/s

**Comment by TechMasterJoe** [comment]
found it code expects Max Z feed rate in MM per min
edited code to call homing feedrate for Z axiz for more control
UPDATE TESTED works good now

**Comment by TechMasterJoe** [comment]
seach marlin_main.cpp for " Z_RAISE_BEFORE_HOMING "
look in same block for "feedrate = max_feedrate[Z_AXIS];"
change to " feedrate = homing_feedrate[Z_AXIS]; "

**Comment by Natealus** [comment]
That's interesting it must not be applying the same way for delta. Course Z is done much differently in a moving bed setup.

**Comment by TechMasterJoe** [comment]
it is funny because this section is in a else Brackets so in a nut shell it's saying 
if not delta do this
still has another bug hiding 3rd print it started Z down on G29 tell it crashed so more then a few problems to be found so back to my 3-15-15 Dev dump that just works i got 117 parts to print i will do more debugging tomorrow almost done with my 11 foot tall delta

**Comment by fitch22** [comment]
OK.  Thank you TechMasterJoe!  In my snapshot, the offending line was 1953 in Marlin_main.cpp.  I found an occurrence of "feedrate = max_feedrate[Z_AXIS]" earlier in the same function (gcode_G28()), but that had no effect.  Changing line 1953 to "feedrate = homing_feedrate[Z_AXIS]" did the trick.

I finally have working FW that properly compensates for the bed level, and homes within my lilfetime.  

Thanks.

**Comment by Natealus** [comment]
Thats awesome. And a 11 foot tall delta? Helllz ya hehe.

**Comment by c-born** [comment]
G29 seems to somewhat randomly leave the z-probe down after the last probe.
Using "G29 E" to restore the old behaviour (deploying probe for every test point) gets around it for now.

**Comment by tonnico** [comment]
max_feedrate[Z_AXIS] \* 60 is that what it should be.#1790
feedrate for line_to_destination is feedrate/60. So you take your 4mm/s / 60 which makes it so slow.

**Comment by AnHardt** [comment]
@Wurstnase 
Are you sure? This line is unchanged since at least Nov. 2013?

**Comment by tonnico** [comment]
@AnHardt Sure, sure! feedrate is needed in line_to_destination. And this changed in https://github.com/MarlinFirmware/Marlin/commit/d73b169de3b031779771a14a65cad7fe476d3d98

Take a look here: https://github.com/MarlinFirmware/Marlin/commit/d73b169de3b031779771a14a65cad7fe476d3d98#diff-1cb08de130a6ece2d1b5b9c37bcfef48R1906

**Comment by alexborro** [comment]
I have just checked it and @Wurstnase is correct. The newly added function line_to_destination takes the feedrate in mm/min. This mess in speeds is pissing me off.

I propose we get rid of any mm/min functions, converting all to mm/s.. and just convert the gcodes received in mm/min as soon as they are received.

I have just open an issue to discuss that: #1791 

Cheers.

Alex.

**Comment by AnHardt** [comment]
Ok. I see.
When this correction is correct in line 1953 https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/Marlin_main.cpp#L1953
why not in line 1820
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/Marlin_main.cpp#L1820?

**Comment by tonnico** [comment]
already fixed this also ^^ #1790

**Comment by AnHardt** [comment]
:+1:  ;-)

**Comment by thinkyhead** [comment]
Fix has been merged!
