### ISSUE TITLE
New thermocouple board and main board

### ISSUE THREAD

**Issue by caunyd** [MarlinFirmware/Marlin#17845]
Hi guys. For my 3D printer, I want to wire a Max31856 thermocouple board to my MKS Gen L V2.0 main board. I used the MKS Gen L V2.0 pinout attached

![MKS Gen L V2 Pinout](https://user-images.githubusercontent.com/64726058/80909237-9f815080-8cdb-11ea-9976-250b4c4e9eb0.png)
:

The Max31856 can use both software SPI or hardware SPI. Looking at the board’s SPI pins, this is what I think the wiring should be for hardware SPI. I’m a rookie when it comes to electronics, so can you guys chime in on if my wiring is correct?

Max31856 Board		MKS Gen L V2.0

Vin		------>		any 5V pin
Grn		------>		any ground pin
sck		------>		D52
sdo		------>            	D50
sdi		------>    		D51
cs		------>		D21

There are multiple possibility for the CS pin to connect to based on the main board pinout. So how do I make sure that Marlin knows which pin is being used? Also, for software SPI, it says that I can use any 4 available pins. Similarly, how do I define these 4 pins? I know it’s within pins_RAMPS.h and pins_MKS_GEN_L_V2.h but I don’t know how to define each pin. 

Lastly, are there any other changes I need to make in Marlin to complete my thermocouple board installation? Thanks very much for your time!

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
