### ISSUE TITLE
[FR] Speed-up ABL with BLTouch

### ISSUE THREAD

**Issue by chunter1** [MarlinFirmware/Marlin#17867]
Is it possible to keep the BLTouch pin retracted after probing an ABL mesh-point until the next probing position is reached?
That way the sensor-pin would have a safe distance to the bed AND the ABL sequence could be faster by **simultanously** performing the X,Y and Z motion to the next probing position.

**Comment by blueeagle69** [comment]
Doesn't  #define BLTOUCH_HS_MODE already do this?
That's what I use and the pin remains retracted during probing.
Probe retracts when probing is completed.
Been using it since getting my BLTouch.
(I have the BLTouch V3)

**Comment by chunter1** [comment]
Ok, thanks.
I switched to Klipper firmware in the meantime ;)

**Comment by thisiskeithb** [comment]
> Doesn't #define BLTOUCH_HS_MODE already do this?

Yes for 3.1 (maybe 3.0 as well?) or newer probes.

Closing since this is already supported.
