### ISSUE TITLE
[FR] KILL_PIN invertion

### ISSUE THREAD

**Issue by AbdullahGheith** [MarlinFirmware/Marlin#17866]
### Description

kill() is called when KILL_PIN is LOW. Add a config to invert this functionality

#### Additional Information

I have a momentary switch connected to a relay . Theres a pin going from the relay that becomes HIGH when button is pressed. I can turn off the printer (Desired functionality) if i reverse this if statement in MarlinCore.cpp:
if (!READ(KILL_PIN)) //Ie. if i remove the !

As i do not wish to edit MarlinCore, i want this to be configurable .

**Comment by thinkyhead** [comment]
852a8d6685ec1137eb65e78fa748cae41fbd36b6

**Comment by AbdullahGheith** [comment]
Is there a better solution to my problem?
It worked for a while, but the printer will turn off mid print as if the switch has been pressed

**Comment by thinkyhead** [comment]
To change the KILL pin triggered state from LOW to HIGH add to `Configuration.h`:
```cpp
#define KILL_PIN_STATE HIGH
```

**Comment by thinkyhead** [comment]
You may need to add a proper pull-down resistor between your switch and ground. On AVR there are no pull-downs; only pull-ups, so your switch is floating.

**Comment by AbdullahGheith** [comment]
> [852a8d6](https://github.com/MarlinFirmware/Marlin/commit/852a8d6685ec1137eb65e78fa748cae41fbd36b6)

Thx for this btw. I tried to contribute to the project, but I think your changes are better: https://github.com/MarlinFirmware/Marlin/pull/17869

> You may need to add a proper pull-down resistor between your switch and ground. On AVR there are no pull-downs; only pull-ups, so your switch is floating.

Probably what I am missing. Thx for the suggestion.
