### ISSUE TITLE
[BUG] Can't compile Marlin for MKS SGEN L

### ISSUE THREAD

**Issue by 48design** [MarlinFirmware/Marlin#17873]
For several days I am not able to use Marlin (release or debug) on my MKS SGEN L. It gets compiled but when installed using the SD card the com port is shown for about a minute before it disappears again and shows up as "unrecognized device" in the device manager. I can use a precompiled version of Marlin (found on the web) and use Smoothieware for example so I think it may have something to do with dependencies that get loaded from github?

**Comment by ellensp** [comment]
Didn't follow template. No config files. No way to help this person.

**Comment by sjasonsmith** [comment]
This needs to be closed.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.
