### ISSUE TITLE
Menu says "No Media" if powered on with SD card inserted

### ISSUE THREAD

**Issue by joegatling** [MarlinFirmware/Marlin#17875]
After updating to the latest bugfix-2.0.x version (May 2, Commit 9a69348), my Anycubic Kossel will show "No Media" in the menu immediately after power-on, even when there is an SD card inserted. Removing and re-inserting the SD card resolves the issue.

**Steps to reproduce:**
1. Power off printer
2. Insert SD card
3. Power on printer
4. Open menu and scroll all to the menu item that normally says "Print From Media" 

**Observed results**
Menu says "No Media", despite there being an SD card inserted at the time.

**Notes**
My previous firmware version was at commit 747a4bb (March 29, 2020), and the SD works as expected with that version

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
