### ISSUE TITLE
[BUG] (VSCode Build Failed Multiple Configs)

### ISSUE THREAD

**Issue by otisczech** [MarlinFirmware/Marlin#17878]
![96291017_540300766880313_1954393274265370624_n](https://user-images.githubusercontent.com/64808800/81010328-628d9900-8e56-11ea-966b-9049c32cdf10.png)
![95810730_235846964399213_8077596198187302912_n](https://user-images.githubusercontent.com/64808800/81010329-63bec600-8e56-11ea-88d8-5569a75b31dc.png)

### Bug Description
The VSCode fails to build with default Ender 3 config. I've even tried Ender 2 and 3 V2. Same result.

### My Configurations
[MyConfig.zip](https://github.com/MarlinFirmware/Marlin/files/4577244/MyConfig.zip)

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. Use Ender 3 config files
2. Click build in VSCode using mega 2560
3. Build fails

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

I'm no programmer myself, I've discussed this with my friend, we think there may be an error in file updated 2 days ago - regarding XYZ, which the error states is wrong. I've attached screenshot of possible error in declaration... If it's something I do wrong, please let me know, i went by the manual: https://www.youtube.com/watch?v=RbbzsJBpEhc

And then even by: https://marlinfw.org/docs/basics/install_platformio_vscode.html
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by otisczech** [comment]
Sorry, my first post. Obv Expected: Build successful, Actual: Build failed

**Comment by ellensp** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/17594 
Config files are out of sync with code

All you do is take the following line in your Configuration_adv.h

#define HOMING_BUMP_MM { 5, 5, 2 } // (mm) Backoff from endstops after first bump

and change it to these 3 lines.

#define X_HOME_BUMP_MM 5
#define Y_HOME_BUMP_MM 5
#define Z_HOME_BUMP_MM 2

**Comment by otisczech** [comment]
Thank you! :)
