### ISSUE TITLE
[BUG] G34 only probing Z1 position on 2 axis Z setup

### ISSUE THREAD

**Issue by omnilogix** [MarlinFirmware/Marlin#17876]
I have a dual Z gantry setup that homes to ZMAX
I have enabled Z_STEPPER_AUTO_ALIGN and set the coordinates Z_STEPPER_ALIGN_XY { {  100, 100 }, { 1200,  100 } }.  Z_STEPPER_ALIGN_ITERATIONS = 2, HOME_AFTER_G34 disabled.  All other options are left as default.  

When I issue a G34, the machine homes, and probes the Z1 {100,100} position 4 times and stops.   The terminal says:
ITERATION: 1
DIFFERENCE Z1-Z2=0.01
Target accuracy achieved.
Did 1 of 2
Accuracy: 0.01

I don't think this is correct behavior.  Any help is appreciated

**TERMINAL DEBUG DATA:**  See bold section below, move does not happen
Send: G34
Recv: >>> G34
Recv: Machine Type: Cartesian
Recv: Probe: BLTOUCH
Recv: Probe Offset X0.00 Y25.00 Z0.00 (Middle-Back & Same Z as Nozzle)
Recv:   current_position= X0.00 Y0.00 Z230.01 : sync_plan_position
Recv: > probing all positions.
Recv: 
Recv: ITERATION: 1
Recv: Probing X100.00 Y100.00
Recv: >>> Probe::probe_at_point(100.00, 100.00, raise, 0, probe_relative)
Recv:   current_position= X0.00 Y0.00 Z230.01 :
Recv: >>> do_blocking_move_to X100.00 Y75.00 Z230.01
Recv: <<< do_blocking_move_to
Recv:   current_position= X100.00 Y75.00 Z230.01 : Probe::set_deployed
Recv: deploy: 1
Recv: Probe::move_z(10.00)
Recv: >>> do_blocking_move_to X100.00 Y75.00 Z230.01
Recv: <<< do_blocking_move_to
Recv:   current_position= X100.00 Y75.00 Z230.01 : >>> Probe::run_z_probe
Recv:   current_position= X100.00 Y75.00 Z230.01 : >>> Probe::probe_down_to_z
Recv: BLTouch DEPLOY requested
Recv: BLTouch Command :10
Recv: bltouch.deploy_proc() end
Recv: >>> do_blocking_move_to X100.00 Y75.00 Z15.00
Recv: <<< do_blocking_move_to
Recv: BLTouch STOW requested
Recv: BLTouch Command :90
Recv: bltouch.stow_proc() end
Recv:   current_position= X100.00 Y75.00 Z145.67 : sync_plan_position
Recv:   current_position= X100.00 Y75.00 Z145.67 : <<< Probe::probe_down_to_z
Recv: >>> do_blocking_move_to X100.00 Y75.00 Z150.67
Recv: <<< do_blocking_move_to
Recv:   current_position= X100.00 Y75.00 Z150.67 : >>> Probe::probe_down_to_z
Recv: BLTouch DEPLOY requested
Recv: BLTouch Command :10
Recv: bltouch.deploy_proc() end
Recv: >>> do_blocking_move_to X100.00 Y75.00 Z-2.00
Recv: <<< do_blocking_move_to
Recv: echo:busy: processing
Recv: BLTouch STOW requested
Recv: BLTouch Command :90
Recv: bltouch.stow_proc() end
Recv:   current_position= X100.00 Y75.00 Z145.62 : sync_plan_position
Recv:   current_position= X100.00 Y75.00 Z145.62 : <<< Probe::probe_down_to_z
Recv:   current_position= X100.00 Y75.00 Z145.62 : <<< run_z_probe
Recv: >>> do_blocking_move_to X100.00 Y75.00 Z150.62
Recv: <<< do_blocking_move_to
Recv: <<< Probe::probe_at_point
Recv: > Z1 measured position is 150.62
**_Recv: Probing X1200.00 Y125.00
Recv: >>> Probe::probe_at_point(1200.00, 125.00, raise, 0, probe_relative)
Recv:   current_position= X100.00 Y75.00 Z150.62 :
Recv: >>> do_blocking_move_to X1200.00 Y100.00 Z150.62
Recv: <<< do_blocking_move_to
Recv:   current_position= X1200.00 Y100.00 Z150.62 : Probe::set_deployed_**
Recv: deploy: 1
Recv:   current_position= X1200.00 Y100.00 Z150.62 : >>> Probe::run_z_probe
Recv:   current_position= X1200.00 Y100.00 Z150.62 : >>> Probe::probe_down_to_z
Recv: BLTouch DEPLOY requested
Recv: BLTouch Command :10
Recv: bltouch.deploy_proc() end
Recv: >>> do_blocking_move_to X1200.00 Y100.00 Z15.00
Recv: <<< do_blocking_move_to
Recv: BLTouch STOW requested
Recv: BLTouch Command :90
Recv: bltouch.stow_proc() end
Recv:   current_position= X1200.00 Y100.00 Z145.71 : sync_plan_position
Recv:   current_position= X1200.00 Y100.00 Z145.71 : <<< Probe::probe_down_to_z
Recv: >>> do_blocking_move_to X1200.00 Y100.00 Z150.71
Recv: <<< do_blocking_move_to
Recv:   current_position= X1200.00 Y100.00 Z150.71 : >>> Probe::probe_down_to_z
Recv: BLTouch DEPLOY requested
Recv: BLTouch Command :10
Recv: bltouch.deploy_proc() end
Recv: >>> do_blocking_move_to X1200.00 Y100.00 Z-2.00
Recv: <<< do_blocking_move_to
Recv: BLTouch STOW requested
Recv: BLTouch Command :90
Recv: bltouch.stow_proc() end
Recv:   current_position= X1200.00 Y100.00 Z145.63 : sync_plan_position
Recv:   current_position= X1200.00 Y100.00 Z145.63 : <<< Probe::probe_down_to_z
Recv:   current_position= X1200.00 Y100.00 Z145.63 : <<< run_z_probe
Recv: >>> do_blocking_move_to X1200.00 Y100.00 Z150.63
Recv: <<< do_blocking_move_to
Recv: <<< Probe::probe_at_point
Recv: > Z2 measured position is 150.63
Recv: 
Recv: DIFFERENCE Z1-Z2=0.01
Recv: > Z1 corrected by 0.00
Recv: >>> do_blocking_move_to X1200.00 Y100.00 Z150.63
Recv: <<< do_blocking_move_to
Recv: > Z2 corrected by 0.01
Recv: >>> do_blocking_move_to X1200.00 Y100.00 Z150.64
Recv: <<< do_blocking_move_to
Recv: Target accuracy achieved.
Recv: Did 1 of 2
Recv: Accuracy: 0.01
Recv:   current_position= X1200.00 Y100.00 Z150.64 : Probe::set_deployed
Recv: deploy: 0
Recv: Probe::move_z(10.00)
Recv: >>> do_blocking_move_to X1200.00 Y100.00 Z150.64
Recv: <<< do_blocking_move_to
Recv:   current_position= X1200.00 Y100.00 Z5.03 : sync_plan_position
Recv: <<< G34
Recv: ok

**Comment by randellhodges** [comment]
Attach your config files please

**Comment by omnilogix** [comment]
Config files attached

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/4577548/Configs.zip)


These are the config files used with latest stable release 2.0.5.3

**Comment by omnilogix** [comment]
FYI: I tried to test with the current bugfix release, but with the latest build, the pin on my BLTouch won't deploy for the G34 probing, so I am unable to say if the movement issue is resolved.

**Comment by randellhodges** [comment]
Wow, do you really have a 1.2 meter by 2.4 meter printer?

**Comment by omnilogix** [comment]
Actually a CO2 Laser.   I have a gantry that falls when power off, so it homes to Z+ on startup, then needs to probe the bed for actual Z offset.  Giant Unified Bed Leveling mesh comes next ;)

**Comment by randellhodges** [comment]
Any difference if you pull in the X positions for `Z_STEPPER_ALIGN_XY`, maybe  { 100, 100 }, { 1120, 100 }? If that doesn't do anything, we'll have to see if one the devs knows.

You might want to jump on Discord and see if someone there knows.

**Comment by omnilogix** [comment]
I started with {{10,100} , {100,100}}  with same result.   I also tried swapping my Z1/Z2 motor plugs in case the orientation was wrong, but also same result.  I also tried to change the Y offset on the Z2 to see if the problem was only on the X coordinate, but still no change in position for Z2

**Comment by omnilogix** [comment]
@randellhodges, your comment got me thinking...   I swapped the coordinates to: { {  500, 125 }, { 100,  100 } }.   Looks like a bug.   
When I ran G34, it did the following:
Homed
Started Iteration 1
Moved to 500,125
Probed 2 times
Moved to 100,100
Probed 2 times
Started Iteration 2
*did not move
Probed 4 times
Output: 
Target accuracy achieved.
Did 2 of 2
Accuracy 0.0

**Comment by omnilogix** [comment]
So, it's been a week.  Can a dev maybe comment on this issue?  Is there more information that I can provide?
Thanks

**Comment by sjasonsmith** [comment]
@omnillogix, do you have a log from the last case you reported, where it probed both points, but failed to move on the second iteration?

The challenge is that not that many people use this feature, and even fewer have a machine which actually resembles yours. This makes it difficult for anybody to try to reproduce your issue to figure out where the problem is.

**Comment by omnilogix** [comment]
@sjasonsmith, I don't have a log.   After a few days, I figured that my use case is fairly unusual.  Rather than fight it, I have changed my machine to home to Z-min using a probe and the G34 works except for the occasional know issue of the "decreasing accuracy" message.   If someone wants to chase this issue down, I am happy to provide whatever information I can.    I am sure the problem lies in homing to Z-Max

**Comment by boelle** [comment]
@omnillogix still an issue?

**Comment by omnilogix** [comment]
As far as I know it is still an issue.   I have stopped homing to Z Max, in favor of well supported homing to Z-Min.   I don't think this should be closed, but rather made a lower priority since it is an edge case.  I'm sure future Marlin users might appreciate being able to G34 and home to Z Max.

**Comment by boelle** [comment]
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
