### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ModMike** [MarlinFirmware/Marlin#17880]
When I try to compile I get the following error:

![Screen Shot 2020-05-04 at 11 18 55 PM](https://user-images.githubusercontent.com/36581178/81032439-bfd91880-8e5d-11ea-83bc-c3dc0e52b9cb.png)

I've been compiling for days now and no issues until I downloaded latest.

**Comment by ellensp** [comment]
Hasn't followed template, no config files. No way to help this person.

**Comment by thinkyhead** [comment]
Yep!
