### ISSUE TITLE
Add PINDA temp wait feature[FR] (feature request title)

### ISSUE THREAD

**Issue by brownie-21** [MarlinFirmware/Marlin#17896]
### Description###
The PINDA 2 probe has temperature compensation which can be calibrated using a G76. The compensation table only ranges from 30 - 80 deg C. In cooler environments it is therefore possible to start a print with the PINDA below 30 deg C resulting in inaccurate bed probing. This can lead to poor mesh generation, incorrect probe offsets and possible bed damage due to nozzle collisions.

The Prusa Marlin fork has an M860 G code that waits for the PINDA temperature to be in the calibration range before continuing.

Please add an M code for a PINDA temperature wait feature. 

### Feature Workflow

1. User sets PINDA wait G code in start script (e.g M860 S30). Typically this is inserted after the M109 and M190 codes and before probing.
2. Once the print has stared the FW waits for target temp to be reached before proceeding.

#### Additional Information

The G76 calibration routine  already seems to have a PINDA temp wait function as it heats the bed and does not probe until the PINDA is at target temp so it seams the requested code is already implemented in the G76 function.

**Comment by thisiskeithb** [comment]
Added in https://github.com/MarlinFirmware/Marlin/pull/19344
