### ISSUE TITLE
[BUG] in 1.1.x bugfix in file "thermistornames.h" missing lines

### ISSUE THREAD

**Issue by SantinoDnepr** [MarlinFirmware/Marlin#17903]
### Bug Description
in 1.1.x bugfix (after 1.1.9)
in file "thermistornames.h" missing lines
...
#elif THERMISTOR_ID == 15
  #define THERMISTOR_NAME "Hisens +"
...
#elif THERMISTOR_ID == 66
  #define THERMISTOR_NAME "Makers Tool +"

###
I tried compiling with the parameter in configuration,h
#define TEMP_SENSOR_0 15
and got an error

**Comment by thinkyhead** [comment]
Thanks for the note! The patch is now deployed.
