### ISSUE TITLE
[BUG] Override CASE_LIGHT_PIN not working

### ISSUE THREAD

**Issue by Fixx** [MarlinFirmware/Marlin#17912]
Uncommenting and defining a PIN number not working via option //#define CASE_LIGHT_PIN in Configuration_adv. I need to edit board's pin file, same pin number works that way.
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/4595356/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/4595357/Configuration_adv.txt)
[pins_RUMBA.txt](https://github.com/MarlinFirmware/Marlin/files/4595358/pins_RUMBA.txt)

**Comment by randellhodges** [comment]
For what board? You'll need to add your config files, pin file, what version of Marlin are you using, etc, etc.

I am using it without problems on about a month old pull of bugfix.

**Comment by Fixx** [comment]
I didn't want to clutter this topic with config files as issue is pretty basic. I'm using RUMBA with latest 2.0.x bugfix, but this was always the case since I added case light, like 6 months. I'm using Heater 2 output as caselight: pin 6.

**Comment by randellhodges** [comment]
You have `//#define CASE_LIGHT_PIN 6 `. If you have the `//` in front of it, that comments it out so it isn't used. Remove the definition from your pins and then remove the `//` from it inside your Configuration_adv file and try it.

Edit: I see you specifically mentioned that in your original post, but my mind overlooked that and it wasn't until I saw it in your file that my brain actually processed what you said.

**Comment by thinkyhead** [comment]
Fixed in 6be76af617
