### ISSUE TITLE
[BUG] M569 (Stealthchop) command are reversed

### ISSUE THREAD

**Issue by desertblade** [MarlinFirmware/Marlin#17915]
### Bug Description
M569 (StealthChop) commands are reversed.

### My Configurations
Marlin 2.0.5.3 with SKR Mini E3 configurations, mostly from 
https://github.com/morningreis/Marlin-SKR-E3-Mini-1.2

### Steps to Reproduce

1. Run M569 S1 Z E X Y to enable stealthcop
2.  Check M569 command - Shows that stealthchop is off
3. Run M569 S0 Z E X Y to disable stealthchop
4. Check M569 - shows stealthchop is on

**Expected behavior:** 
The reverse of above

**Actual behavior:** [What actually happens]
Here are screens of the error
![569-On](https://user-images.githubusercontent.com/1170252/81361311-e16f1580-9092-11ea-8e0a-1b5f200822ba.png)
![569-Off](https://user-images.githubusercontent.com/1170252/81361310-e0d67f00-9092-11ea-893f-d71bfb83cc07.png)

#### Additional Information
Seems like other people are experiencing similar. Here are 3 reddit posts about it.

https://www.reddit.com/r/ender3/comments/gdmn65/stealthchop_gets_disabled_every_time_i_reboot_my/

https://www.reddit.com/r/3Dprinting/comments/g8gu9s/marlin_20_skr_mini_e3_stealthchop_issue/

https://www.reddit.com/r/ender3/comments/gev9f7/installed_skr_mini_e3_v12_motors_got_louder/

**Comment by swilkens** [comment]
I used 2.0.5.3 on my SKR Mini E3 without issues.

Have you done a `M502` to load the firmware default values, followed by a `M500` to store them to EEPROM and a `M503` to check them? I expect this is the issue.

If that doesn't fix it; are you using up to date configuration files (link provided in the firmware download)?

If you are, and still have the problem, please try current `bugfix-2.0.x` to check if you are still having the problem.

Firmware:
https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip

Configuration Files:
https://github.com/MarlinFirmware/Configurations/archive/bugfix-2.0.x.zip

My output:
> M569 S1 X Y Z
> M569 S1 T0 E

And check:
> SENDING:M569
> X driver mode:	stealthChop
> Y driver mode:	stealthChop
> Z driver mode:	stealthChop
> E driver mode:	stealthChop

**Comment by desertblade** [comment]
Built from Marlin bugfix-2.0.x branch. Copied over the official Bigtree configuration files, then modified them to work with the latest branch (attached).
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4600148/Marlin.zip)

Ran m502 then m500 then m503.

Still seeing the reverse effect of the M569 S1 Z E X Y command

I find it weird that the command is acting in reverse of what is expected. This is a brand new board just arrived a couple days ago from Amazon.

**Comment by GMagician** [comment]
Which stepstick are you usign? TMC2209, 2208, 5130....

**Comment by GMagician** [comment]
@Bob-the-Kuhn as I can see 51xx and 220x use reversed function for same GCONF bit 2.....M569 send S value directly to function `en_pwm_mode` and I can't see any override to it.

**Comment by swilkens** [comment]
> Which stepstick are you usign? TMC2209, 2208, 5130....

It's the same btt skr mini that I have, uses 2209's. I have no issues, however.

I'm assuming it's a config file issue, as @desertblade indicates he is using "official" config files as a reference. So probably outdated.

Please try again with the config files from the marlin repository :) I'll have a closer look when I'm back at my pc

**Comment by thisiskeithb** [comment]
Which position is the SPREAD jumper (near the X driver) on the board? Try moving it to the opposite position.

**Comment by desertblade** [comment]
We have a winner! @thisiskeithb 

Looked at this image:

![image](https://user-images.githubusercontent.com/1170252/81442458-7c65ff00-9128-11ea-9fff-692afaae27da.png)


My Spread Jumper (red jumper) was in the opposite location. Switched it around and M569 command is working as expected.

Figured it might have something to do with recent batches of the board. 

Big thank you to everyone. Hopefully this will help a few other people.
