### ISSUE TITLE
Get rid of mm/min speeds.

### ISSUE THREAD

**Issue by alexborro** [MarlinFirmware/Marlin#1791]
The code is a mess mixing mm/min and mm/s stuffs.

I think mm/min, although a standard in milling machines, makes no sense in 3D Printers due high speeds.

We could handle all the speeds in the code as mm/s and convert the received standard gcodes from mm/min to mm/s before passing them to internal functions. That way we keep compatibility with slicers and other tools and get a clean code.

What do you guys think?

Cheers.

Alex.

**Comment by tonnico** [comment]
I would go more to teacup and take µm/s.
In config-file mm/s is a good way.

This can makes big advantage because you can handle some numbers in integer than in floats. We can make then some faster math with shifting etc.

**Comment by TheRogueZeta** [comment]
+1

I think the idea of standardizing on unit for speed is appropriate.

**Comment by whosawhatsis** [comment]
@Wurstnase with units of µm/s, speeds over 65mm/s would require more than a two-byte integer. The integer math would be significantly easier in mm/s if the precision was adequate.

+1 for standardizing on mm/s

**Comment by tonnico** [comment]
Long vs. Double? I see no disadvantages. Or which format do you need at 65mm/s?

**Comment by alexborro** [comment]
Humm, .. µm/s ... maybe..

There is just one math made with feedrate, in planner:

float inverse_second = feed_rate \* inverse_millimeters;

I don't see too much advantage using uint32 than float..(for speeds like
500mm/s - 500.000µm/s - we need a uint32).
Just changing from mm/min to mm/s is matter of removing / adding many "/60"
or "*60" in the code.. changing the type implies critical changes...

Cheers.

Alex.

2015-04-03 17:09 GMT-03:00 ZetaPhoenix notifications@github.com:

> +1
> 
> I think the idea of standardizing on unit for speed is appropriate.
> 
> On Fri, Apr 3, 2015 at 8:34 AM, alexborro notifications@github.com
> wrote:
> 
> > The code is a mess mixing mm/min and mm/s stuffs.
> > 
> > I think mm/min, although a standard in milling machines, makes no sense
> > in
> > 3D Printers due high speeds.
> > 
> > We could handle all the speeds in the code as mm/s and convert the
> > received standard gcodes from mm/min to mm/s before passing them to
> > internal functions. That way we keep compatibility with slicers and other
> > tools and get a clean code.
> > 
> > What do you guys think?
> > 
> > Cheers.
> > 
> > Alex.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MarlinFirmware/Marlin/issues/1791.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1791#issuecomment-89408485
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by tonnico** [comment]
Alex you are right. This would be a greater rework with step rates and so on...
+1 for mm/s

**Comment by alexborro** [comment]
Let's finish this bugfix phase and then I will implement this change.

Any suggestions are welcome.

Cheers

Alex.
Em 03/04/2015 17:54, "Wurstnase" notifications@github.com escreveu:

**Comment by thinkyhead** [comment]
:+1:

**Comment by NarimaanV** [comment]
+1 for mm/s

**Comment by thinkyhead** [comment]
This will also end up being a minor documentation issue. But perhaps not too many are dependent on `M207` right now.

**Comment by tonnico** [comment]
Good thing to push this. We have a lot of /60-division in the code. This will also improve the perfomance.

**Comment by thinkyhead** [comment]
Items to be changed:

**Configuration.h**:

```
#define HOMING_FEEDRATE {50*60, 50*60, 4*60, 0}  // set the homing speeds (mm/min)
```

**Configuration_adv.h**:

```
#define MANUAL_FEEDRATE {50*60, 50*60, 4*60, 60} // Feedrates for manual moves along X, Y, Z, E from panel
#define AUTO_FILAMENT_CHANGE_FEEDRATE 300   //Extrusion feedrate (mm/min) on automatic extrusion loop
```

**Marlin_main.cpp**:

```
static float feedrate = 1500.0, ...
```

Other potential changes:

**gcode_M207**:

```
if (code_seen('F')) retract_feedrate = code_value() / 60;
```

**gcode_M208**:

```
if (code_seen('F')) retract_recover_feedrate = code_value() / 60;
```

**Comment by Wackerbarth** [comment]
I think that the original purpose in using mm/min was to have numbers which were large enough that they could be measured (and possibly also treated as integers which retained "enough" resolution).

Since everything seems to be going toward floating point, as inefficient as it is, it now becomes a issue of user compatibility.  You're not really saving any space or time if you code the calculations appropriately.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
