### ISSUE TITLE
marlin 1.1.9 heats but no print

### ISSUE THREAD

**Issue by djbilbao** [MarlinFirmware/Marlin#17926]
I recently installed marlin 1.1.9 on my anet a2 plus I launch a printing by usb I connect it heater bed and extruder but it does not launch any printing, I gave the firmware skynet3d 2.3.2 and it works, I even tried marlin 1.1.x bugfix nothing

**Comment by GMagician** [comment]
Better to use 2.0 version. 1.1.9 will, maybe, receive some fix but no more development

**Comment by djbilbao** [comment]
okay but when we download marlin 2.0 or + we have no marlin file for arduino no matter the link on the internet? thank you

**Comment by djbilbao** [comment]
https://github.com/MarlinFirmware/Configurations/tree/release-2.0.5

**Comment by GMagician** [comment]
Not sure I understand you but last release, 2.0.5.3 at https://github.com/MarlinFirmware/Marlin/releases, if you download source and check Marlin subfolder there is a Marlin.ino file

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
