### ISSUE TITLE
Marlin runs RUMBA - Problems with the E2 control

### ISSUE THREAD

**Issue by Harpye** [MarlinFirmware/Marlin#1793]
Trying to use the standard Marlin 1.1 package on a RUMBA board ( Board 80) I recognized the following!
 using X;Y;Z and E0+E1 works fine, but additionally using E2 causes missbehaviour

I built a Gcode Skeleton right side of attachement which works fine on the E2 (solo) but after including some movement blocks of the other channels ( which also work well in stand alone usage) in between the existing E2/ T2 blocks, E2 does not work properly anymore . 

Both gcodes work well themselves, but merged ( left side) they cause issues on the E2 behaviour ( the specified number after E __  is ignored and always replaced by a fixed stepcount as also the sign is ignored so 

e.g. E -1 is executed  by 120mm as E 1 causes the same result

I put a gcode comparison ( attached below) in here and aligned the corresponding code sequences:

( sorry but I'm brand new to that programming thingy and tired for rather a week now, to understand the Marlin code ! I got stuck...)

Any help would absolutely be appreciated!

Hansjoerg

![codeproblem](https://cloud.githubusercontent.com/assets/5358045/6985872/1410b8ac-da38-11e4-9ccb-5273e170b771.jpg)

**Comment by thinkyhead** [comment]
Still looking through the code to see if there's any obvious cause. So far nothing stands out, but I will keep looking. One thing I might need to know, are you using `FWRETRACT`?

**Comment by Harpye** [comment]
Hello Thinkyhead! 
I use Marlin to control a model of a 6 axis model of an idustrial handling robot! The missbehaving element is the turntable. The arm behaves well as long as I dont want to use the turntable / T2
the turntable behaves well as I dont want to use the arm! Merging both causes the turntable to missbehave (I'm not sure, but I can't remember that I checked the FWretract option... the more as e0 and e1 work correctly in stand alone mode)

 I'll pass along my config.h printout as soon as I'm back at my workstation

Thanks in advance for your help!

Hansjoerg

**Comment by Harpye** [comment]
As said before - here are the config FIles ... I did not change anything else:

   http://pastebin.com/uU6kBbEe

**Comment by thinkyhead** [comment]
I see you are using an older version of Marlin, and we don't fix older versions. You should get the current version of Marlin – the Development branch – and update your configurations for the new version. You will probably have to apply all your other changes as well, which will be a bit of a challenge. A lot has changed. I am doing a merge of your `Configuration.h` which I will post shortly. But I am curious about the strange temperature values you have set. What is the meaning of your temperatures all being set to such unusually small values?

**Comment by thinkyhead** [comment]
An updated `Configuration.h`…

http://pastebin.com/YASLA4wQ

**Comment by Harpye** [comment]
Hello Scott!

First  THANK YOU for your kind support on the problem!
I use Marlin - mentioned otherwise- for the 6 Axis control of an model industrial robot  ( perhaps I understand that code one day as far to get the 6 axis interpolated - not just the xyz)
but at the moment I'll try to live with this ! 
I don't need temperature measurement for this job, but clamping off all the measurement causes failure through compilation - so I decided to set the R25° value by using a fix resistor instead of a thermistor and set the window around that value so 
there is no heating period and no wait sequence - the program is just going through all this as everything is fulfilled!

-I'll try your new merge and again THANK YOU VERY MUCH!

BR

Hansjoerg

**Comment by Harpye** [comment]
Hello Scott!

After updating the Marlin Version ->1.0.2 
and exchanging the Configuration.h against 
your merge, situation is quite the same - 
the skeleton runs as defined, but with the 
movement blocks it still causes missbehaviour!!
Sorry about the bad news!
- Hansjoerg

**Comment by clefranc** [comment]
@Harpye
Don't know if it's related, but the updated config from @thinkyhead have
`#define EXTRUDE_MINTEMP` set to 170
yours was set to 0.

Also, I'll undefine `PREVENT_DANGEROUS_EXTRUDE` as I think you don't need it.

**Comment by thinkyhead** [comment]
@Harpye I never expected the problem to go away with the latest code. But, we have to start with the latest code to do anything for your situation. (Not the tagged version 1.0.2, but the latest Development branch code. The configuration I posted is not intended to work with the 1.0.2-tagged Marlin.)

I think the latest code will need to be somewhat re-adapted for your 6-axis setup – I can't imagine you will be able to get it to compile successfully and run without making several adjustments. Most importantly, the `NUM_AXIS` value is no longer set in `Configuration.h` because it's been (historically) just an alias for the number 4. But, you should put it back into your `Configuration.h` and remove it from `Marlin.h`. Maybe you did that and that was all it took to compile…?

**Comment by Harpye** [comment]
Is 1.0.2 not the  latest frozen revision - I tried to find the Development branch code you mentioned, but was not that successful .
Regarding the "sponsored Configuration.h"  file - I just replaced the code and it immediately was able to be compiled!

Where can I find the recent code - I first found the 1.0.2 version. - do I have to replace EACH single file standing below the //Marlin/Marlin/+ Directory?

**Comment by clefranc** [comment]
@Harpye 
Go to https://github.com/MarlinFirmware/Marlin
Click the `Download ZIP` button. The button is located at the bottom of the right column.

Open the zip file you just downloaded, you'll see a folder named `Marlin-Development`, this is the latest development branch. Unzip to a location of your choice, delete the zip file, goto the folder `..\Marlin-Development\Marlin` and open `Marlin.ino`.

Do what thinkyhead wrote above.

**Comment by Harpye** [comment]
Thank you ! - I did what you said and changed the `Configuration.h` to that one given by thinkyhead  (I called it rev 1.0.2+ UD) . Result of the new revision is now that it ignores ALL E-Movement coords and just fulfills the axis movements X Y Z  - is there another way to address them in Gcode now?

**Comment by thinkyhead** [comment]
What results do you get if you turn off `PREVENT_DANGEROUS_EXTRUDE`?

**Comment by Harpye** [comment]
Now the axis move, but the problem seems to be the same like at the beginning. 
Just only one direction independent from the sign I use and  wrong values .

**Comment by thinkyhead** [comment]
Such a mystery. We have to ask, what might possibly be different about E2 in terms of movement? And I assume it would also apply to E3 if there was one. So far nothing in the code is jumping out at me.

**Comment by Harpye** [comment]
Another time I tried to understand what Marlin does - but there is so much jumping arround to me - I got no clue until now. Could it be that the movement blocks in between the T2 sequences -someway increment a value which afterwards is used to calculate the E2 steps I specified all axis to be absolute
value adressed - E2 ???  I'd put E2 on an external testing Stepper and as soon as I'll can find the time I'll simplify the Gcode back to skeleton  and a second version  to skeleton + single "desturbing lines" of other single axis and axis combinations - just to see what happens.. I'll come back with the results!

Thank you again for your engagement and help!

Hansjoerg

**Comment by Harpye** [comment]
Starting  with the tests I recognized the following:
Simple Gcodes work correctly even if all axis are engaged
More complex Gcodes cause malfunction ->  except I set a G92 just in between the <T2> and the <G1 E2> 
Here I have to use the G1  as an incremetal set since I reset the E2 state every time before I use it even if I set the mode as absolute in header ( <G90>).
I have 3 G1 E(2) in my gcode  - first and second are done correctly the third is just ignored with using G92 before

I'm not that programming genius  (I'm far... far from :) ) but it appears to me as it could be that the 
variable keeping the position of E2 could be someway affected by the use of other axis . ( Use of a local variable instead of a global or sharing of memory or multiplexed usage ) ( I'm not the man who should make assumtions of that Level, but if you could not find a reason on the surface and shortly afte a reset the function is correct later on it is not ... something must have changed!)

**Comment by thinkyhead** [comment]
There is only a single E position from the GCode point of view. The `e_steps` of individual extruder steppers are tracked, but only with the `ADVANCE` feature, and only within `stepper.cpp`... but there are a lot of places where `active_extruder` comes into play.

So I keep thinking, what if `active_extruder` is changed by a `T` command, but there are still moves in the planner that apply to the previous extruder? Can this happen, or are all moves cleared out whenever a `T` command is issued...?

You might try inserting the line `st_synchronize();` at the beginning of the `gcode_T` function and see if it helps…

**Comment by clefranc** [comment]
@thinkyhead I think it's the right time (debugging phase) to remove `active_extruder` in `plan_buffer_line`, and use exclusively `extruder`, the argument passed to the function.

**Comment by thinkyhead** [comment]
@clefranc Good idea: How does this look? https://github.com/thinkyhead/Marlin/commit/8857b9e921d88e9d8c8bdef3bf9d59e8622b0070

**Comment by clefranc** [comment]
@thinkyhead Yes, exactly what I've found.

**Comment by boelle** [comment]
should this one not be upgraded to verified? or is the problem gone?

**Comment by thinkyhead** [comment]
I made the change suggested by Christian, but don't know if it helped with the E2 problem.

**Comment by Harpye** [comment]
Sorry about the delay on the  answere - had some issues with the Notebook - will update the Firmware early next week and will see if it has an effect!

**Comment by Harpye** [comment]
oUuups sorry wrong click!

**Comment by thinkyhead** [comment]
Still seeing this with the latest code? It's always shifting and changing, so perhaps this got fixed in the process.

**Comment by Harpye** [comment]
Yesterday I got the latest developmental Version - and on Monday I will check - with the version of my latest post it was still wrong - but wee will see

**Comment by Harpye** [comment]
I did not want to wait, so exchanged the config.h in the current version to that one you sent previously 
(I marked with "1.0.2+ud") and tried the code... unfortunately it seems not to change in behaviour.
Attachd you find the code  - the marked lines (****) are executed incorrectly!
Independent from the sign of the G1 entry the motor turns the same direction ( always CW ).

Idea: could there be an issue with the hich accuracy of the entries (calculation or Memory overload)
As the entries are machine calculated  i perhaps should manually round them in the recent file just to see what happens (perhaps down to X.xx)

```
;TITLE 'Test Code
; POSTPROCESSOR for Marlin 1.1
; APPLICATION MicroRobot 1.0
G21 ; Set units To millimeters
M17 ; Power all Steppers
G90 ; use absolute coordinates
G4 S3 ;Wait 3s 
T0; Switch Tool
G92 X0 Y0 Z0 E0 ; Zero Axis incl E0
T1; Switch Tool
G92 X0 Y0 Z0 E0 ; Zero Axis incl E1
T2; Switch Tool
G92 X0 Y0 Z0 E0 ; Zero Axis incl E2
T1; Switch Tool
Code Start
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
T2; Switch Tool
***G1 E-45 F2000***
T1; Switch Tool
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
T2; Switch Tool
***G1 E45 F2000***
T1; Switch Tool
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X69.7640189871358 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-235.117990506432 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-230.019867432552 F8000
G1 X79.9602651348961 Y179.011856369478 Z230.019867432552 E-50.0198674325519 F8000
G1 X69.7640189871357 Y163.485302816621 Z235.117990506432 E-55.1179905064321 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-38.5482167950509 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-34.860192178043 F8000
G1 X110.279615643914 Y160.549926791405 Z214.860192178043 E-214.860192178043 F8000
G1 X102.903566409898 Y149.191897890333 Z218.548216795051 E-218.548216795051 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-200.291008700018 F8000
G1 X139.417982599963 Y127.536743948087 Z200.291008700018 E-20.2910087000184 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-22.0723514774678 F8000
G1 X135.855297045064 Y116.36916253409 Z202.072351477468 E-202.072351477468 F8000
T2; Switch Tool
***G1 E0 F2000***
T1; Switch Tool
G4 S3 ;Wait 3s 

G1 X0 Y0 Z0 E0 ; Back to Origin
;end
```

**Comment by Harpye** [comment]
Used Excel to round all entries to .xx accuracy but did not reach the result I'm searching for!
All 3 marked lines are done CW  and as -45 to +45 is 90°Deg and +45 ° to 0° is just -45° Deg I would expect half the executed angle here but received the same motor movement all 3 times

**Comment by thinkyhead** [comment]
Hmm, this is a puzzling behavior. I can only look at the code and hope the bug jumps out at me, and I can supply you with a version of Marlin that prints out values as it's running to try to pinpoint where the logic is getting screwed up. I do hope it's just a logical error and not something weird, like the timing of stepper signals to your third E axis. Is there anything different about that axis motor from the others, by the way?

**Comment by Harpye** [comment]
Since my turntable  is limited in angle but until now I do not have a reference switch here I do use a single stepper with no load on this channel - nomodifications - the stepper ist connected directly to E2

As already mentionned short programs without many changes between the axis and Tool - Channels seem to be processed correctly. but as soon as it is getting more complex....

**Comment by Harpye** [comment]
Perhaps the observing measures would be the right way???!

**Comment by Harpye** [comment]
That is an idea - I never blamed the hardware to be the problem...before - would mean two failures on DIR and Microstep on one Stepstick... strange but I'll go for it - until then I would like to  show you something and thank you again for your kind help!

https://www.youtube.com/watch?v=evt_9DVsy2g&feature=em-upload_owner

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
