### ISSUE TITLE
[BUG] Display glitch in LCD PROGRESS BAR

### ISSUE THREAD

**Issue by Lord-Quake** [MarlinFirmware/Marlin#17940]
![Display_Glitch_Commit_2020 05 10](https://user-images.githubusercontent.com/29223282/81499799-5b3f1300-92ce-11ea-8230-adf36ad01e34.jpg)

### Bug Description

Progress bar should be (normally was) completely filled.

Compiled with commit 2020.05.10 (https://github.com/MarlinFirmware/Marlin/commit/86c112538084f7718252966f5f9d9278c4837fb2)

[Configuration_Files.zip](https://github.com/MarlinFirmware/Marlin/files/4605730/Configuration_Files.zip)

**Comment by ellensp** [comment]
Config files?, so we can try and replicate...

**Comment by kmobs** [comment]
Same issue here. I've attached my config. Ender 3 pro as well. 

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/4607233/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/4607234/Configuration_adv.txt)

**Comment by ellensp** [comment]
In Marlin/src/lcd/dogm/status_screen_DOGM.cpp is the following line
#define PROGRESS_BAR_Y (EXTRAS_BASELINE + 2)
change this to 
#define PROGRESS_BAR_Y (EXTRAS_BASELINE + 1)

**Comment by Lord-Quake** [comment]
@ellensp I can confirm the correction fixed the issue.

**Comment by thinkyhead** [comment]
This should do the trick…
```cpp
    //
    // Progress bar frame
    //

    if (PAGE_CONTAINS(PROGRESS_BAR_Y, PROGRESS_BAR_Y + 3))
      u8g.drawFrame(PROGRESS_BAR_X, PROGRESS_BAR_Y, PROGRESS_BAR_WIDTH, 4);

    //
    // Progress bar solid part
    //

    if (PAGE_CONTAINS(PROGRESS_BAR_Y + 1, PROGRESS_BAR_Y + 2))
      u8g.drawBox(PROGRESS_BAR_X + 1, PROGRESS_BAR_Y + 1, progress_bar_solid_width, 2);

```
