### ISSUE TITLE
[BUG] Double-click for babystep no longer works from 52aa459 onwards

### ISSUE THREAD

**Issue by Knifa** [MarlinFirmware/Marlin#17959]
### Bug Description

Double click for babystep no longer works on my Ender 3 Pro with SKR Mini E3 v1.2 on https://github.com/MarlinFirmware/Marlin/commit/1475fd312a1572e1d43978f669bce02a72f63dab.

Previous build was https://github.com/MarlinFirmware/Marlin/commit/6947dc139e4e81fed3986510eb32a93c58bd256c, which worked as expected. Broken from 52aa459 onwards.

I tried fiddling with the timer (doubled from `1250` which worked fine before to `2500`) but no dice.

The `Babystep Z` menu item still works.

### My Configurations

[config.zip](https://github.com/MarlinFirmware/Marlin/files/4609931/config.zip)

### Steps to Reproduce

1. Enable `BABYSTEPPING` and `DOUBLECLICK_FOR_Z_BABYSTEPPING`.
2. Start a print.
3. When things getting moving, try double click.

**Expected behavior:** Babystep menu shows.

**Actual behavior:** Current menu item is selected instead (return to status).

**Comment by Knifa** [comment]
52aa459 is the culprit.

**Comment by Knifa** [comment]
This looks like the breaking change: https://github.com/MarlinFirmware/Marlin/commit/52aa459a2dc08a8f803ad9ffb7aa173dc449637f#diff-8685dde8286c4e15db3bf3e8f74d5e6fR227

Reverting back to `screen == status_screen` solves the problem.

I'm not sure if the other changes here maybe have similar effects.

**Comment by swilkens** [comment]
@thinkyhead made this change

**Comment by qwewer0** [comment]
Can confirm, but I have the same board.

**Comment by Knifa** [comment]
Fixed by https://github.com/MarlinFirmware/Marlin/pull/17962.
