### ISSUE TITLE
[BUG] "no media" message when plugging in an SD card

### ISSUE THREAD

**Issue by leytanelectronics2** [MarlinFirmware/Marlin#17978]
I am having a problem with my version of marlin not seeing the SD card when I plug it in and when I do it shows the "media inserted" text so it can tell there's a card there but when I go into the menu and go to where the usual print from media text should be it just shows "no media" even though there is a card in it.

I have made no modifications to the programming outside of activating the filament runout sensor, adding the scrolling text for file names, and showing the "show remaining time" function in the config-adv.h file.

The motherboard I am using is a ramps board using an Arduino mega 2560 as the processor, if anybody has found a fix for this please post it here with clear instructions, my skills at programming are practically nonexistent so I need all the help I can get.

https://www.youtube.com/watch?v=-UbTaDt3aiE this is a video made by someone having the same issue I am having, but my set up is using the LCD 12864 Graphic Smart Display instead of the one shown in this video.

The config files are below
[config.h and config_adv.h.zip](https://github.com/MarlinFirmware/Marlin/files/4616870/config.h.and.config_adv.h.zip)

**EDIT** i figured out how to fix the sd card issue, I changed the spi_speed from half to a quarter the speed and now it works flawlessly.

**Comment by P-C-R** [comment]
please post you config.h and config_adv.h in a zip file here

**Comment by P-C-R** [comment]
Connect your printer via USB to your PC and test this command

https://marlinfw.org/docs/gcode/M021.html


Is the SD Card formated in FAT32 ?

**Comment by leytanelectronics2** [comment]
the default was just FAT so I believe it is set to that. I'll test the command you suggest as soon as I can.

**Comment by leytanelectronics2** [comment]
ok, i tried it, didn't work, tried fat32, worked for a second then could no longer see the data on the card.

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by leytanelectronics2** [comment]
@thinkyhead thank you, I'll test it as soon as I can.

**Comment by leytanelectronics2** [comment]
@thinkyhead  ok i fixed the problem, i changed the spi-speed setting from half to a quarter and now it works perfectly.
