### ISSUE TITLE
[BUG] Typo "defome"

### ISSUE THREAD

**Issue by P-C-R** [MarlinFirmware/Marlin#17976]
Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\tune_menu.cpp:60:6: error: invalid preprocessing directive #defome; did you mean #define?

define and not defome ;)

**Comment by thisiskeithb** [comment]
Thanks for the heads up! I submitted https://github.com/MarlinFirmware/Marlin/pull/17985 to fix this.
