### ISSUE TITLE
[FR] Teensy 4.1 board support (based on NXP i.MX RT106x platform)

### ISSUE THREAD

**Issue by Hedda** [MarlinFirmware/Marlin#17973]
Teensy 4.1 was just released today by its developer @PaulStoffregen and compared to Teensy 4.0 (see #16666 feature request by @limitz )

IMHO this controller board has the potential to be a competitor to the Re-ARM board is fitted to RAMPS shield in a smart way.

The biggest hardware features news with Teensy 4.1 compared to Teensy 4.0 is the addition of a MicroSD (SD-card) slot, more I/O pins, as well as a header for integrated 10/100 Mbit Ethernet PHY (network physical layer) support. USB devices are supported by the USBHost_t36 library (which is installed into the Arduino IDE automatically by the Teensyduino installer).

- https://www.cnx-software.com/2020/05/12/teensy-4-1-board-gets-longer-for-ethernet-microsd-slot-and-more-gpios/

The Fast Ethernet port has IEEE1588 precision packet timestamping, and Teensy 4.1 now also supports hot-plugging to directly connect a USB device at any time.

Teensy 4.1 specifications:

- https://pjrc.com/teensy-4-1-released/

Teensy 4.1 product page:

- https://pjrc.com/store/teensy41.html

Teensy 4.1 Arduino compatible board is powered by the same RT1062 Cortex-M7 crossover MCU with a CPU core clocked at 600 MHz from NXP i.MX RT Series as Teensy 4.0, (RT1060 family: https://www.nxp.com/imxrt1060 ), however, Teensy 4.1 design is about double in length in order to add a 10/100 Mbit Ethernet PHY, a MicroSD card slot, and offer more I/Os.

Teensy 4.1 specifications 

- SoC – NXP i.MX RT1062 32-bit ARM Cortex-M7 MCU with a ARMv7-M/Armv7E-M CPU core at 600 MHz with 1024KB RAM (512KB is tightly coupled)
- Storage – 8 MB serial flash (64KB reserved for recovery & EEPROM emulation), MicroSD SD-card Socket, footprints for 2x extra QSPI chips such as flash or 8MB PSRAM chip
- USB – 1x micro USB port for power and programming
- Networking – 6-pin Ethernet header via 10/100 Mbit DP83825 PHY
- Expansion via through-holes and pads
  - USB – 2x USB ports, both 480 MBit/sec (5 pins with power management)
  - Storage – 1x SDIO (4 bit) native SD
  - Audio – 2x I2S Digital Audio, 1x S/PDIF Digital Audio
  - Serial – 8x Serial, all with 4 byte FIFO; 3x CAN Bus (1x with CAN FD)
  - 35x PWM pins
  - 40x digital pins, all interrupt capable
  - 18x analog pins, 2x ADCs on chip
  - 3x SPI, all with 16 word FIFO; 3x I2C, all with 4 byte FIFO
  - Total I/O pins – 55 (vs 40 for Teensy 4.0)
- Security – Cryptographic Acceleration; Random Number Generator
- Misc – RTC for date/time, 32x general-purpose DMA channels, Programmable FlexIO, Pixel Processing Pipeline, Peripheral cross triggering, Power On/Off management
- Power Supply – 5V via micro USB port
- Dimensions – 7.2 x 1.8 cm (TBC)

The software is mostly software compatible with Teensy 4.0, and can also be programmed in Arduino IDE using Teensyduino software add-on.

![](https://www.pjrc.com/wp-content/uploads/2020/05/teensy41_card.png)

![](https://www.pjrc.com/wp-content/uploads/2020/05/teensy41_ethernet2-768x857.jpg)

![](https://www.pjrc.com/wp-content/uploads/2020/05/teensy41_sdcard.jpg)

The bottom side of Teensy 4.1 has locations to solder 2 memory chips as optional RAM and flash memory expansion. Footprints are for 2x extra QSPI chips such as flash or 8MB PSRAM chip. The smaller location is meant for a PSRAM chip. The larger location is intended for flash memory.
![](https://forum.pjrc.com/teensy41_2.jpg)

PS: I have no direct or indirect affiliation with this or any of its resellers, (I'm just a hobby enthusiast).

**Comment by EvilGremlin** [comment]
Don't forget to send hardware to interested developers ;)

**Comment by Hedda** [comment]
> Don't forget to send hardware to interested developers ;)

I have no affiliations to Teensy, however I'm sure developers can contact @PaulStoffregen at [PJRC](https://www.pjrc.com/about/contact.html) for donations -> paul@pjrc.com

**Comment by Hedda** [comment]
FYI, as per #16666 @limitz was working on a Marlin bugfix branch port for the Teensy 4.0 board here:

https://github.com/limitz/Marlin/tree/teensy40

He, however, put that project on the backburner for various reasons:

>  I was just breadboarding it with some external mosfets and tmc5160s, don't think you need much more than that. However, I got lost in some preprocessor hell because several dependencies of marlin don't use the marlin HAL (obviously) and the arduino port for teensy didn't work for them (u8g2 for instance). Also tried to fix some PROGMEM stuff instead of just defining it as NOP, but that just opens another can of worms with bugs introduced by the fact that a lot of HALs "fix" pgm compilation errors by just defining it empty (serial writes expecting progmem string called with strings allocated on heap or stack.
> In the meantime I got an ultratronic board and put this project on the backburner, because I think that the way marlin is structured now is flawed and would rather spend time on fixing those flaws than working around those flaws to get the teensy working :)

**Comment by EvilGremlin** [comment]
I don't think it works like "hey some random guys want us to do complex unpaid work so we can support your new board, please send a few to us for free"... Well, first and foremost developer must be personally interested.

**Comment by Hedda** [comment]
> I don't think it works like "hey some random guys want us to do complex unpaid work so we can support your new board, please send a few to us for free"... Well, first and foremost developer must be personally interested.

@EvilGremlin I know that is not how open source development projects works. but companies will quite often sponsor open source developers for free hardware these days if asked since many of them know that they will sell more if their hardware is supported.

Again this is only a feature request, as in a suggestion, however, Marlin already runs on Teensy 3.x (Teensy 3.5 and Teensy 3.6) and the new Teensy 4.1 (+ a RAMPS 1.5 or 1.6 shield) does look like it could be the perfect high-performance 32-bit board for Marlin Firmware, so my guess is that it will only be a matter of time before there are Marlin developers with a personal interest in the new Teensy 4.1 board.

According to [embeddedartists.com,](https://www.embeddedartists.com/products/imx-rt1062-oem/) and Arm's own comparison table for the Cortex-M family, the NXP i.MX RT1062 platform is among the highest performing Cortex-M7 solutions, with its CPU core delivering 3036 CoreMarks (when running core at 600 MHz), which is 13 times higher in CoreMark per MHz than NXP's LPC1788 microcontroller (when running its Cortex-M3 core at 120 MHz). In addition to the high-speed performance, it provides very fast real-time responsiveness with ultra-low latency.

- https://www.youtube.com/watch?v=DmSB7zplDjU

- https://developer.arm.com/ip-products/processors/cortex-m/cortex-m7

Another upcoming board featuring same MCU is the Feather MIMXRT1062 (for Adafruit CircuitPython):

- https://circuitpython.org/board/feather_mimxrt1062/
- https://github.com/adafruit/circuitpython-org/blob/master/_board/feather_mimxrt1062.md
- https://hackaday.io/project/169387-mimxrt10xx-feathers-rt1011-and-rt1062
- https://twitter.com/arturo182/status/1199841134253682690

To compare, STM32F7x6 (STM32F746 and STM32F756) platform which is used by 3D-printer controller boards already supported by Marlin Firmware HAL, (like The Borg and RemRam V1 boards), has a slower Cortex-M7 CPU core running at max 216 MHz that deliver 1082 CoreMark, which is almost three times slower than the NXP i.MX RT1062 platform.

- https://www.st.com/en/microcontrollers-microprocessors/stm32f7x6.html

**Comment by SJ-Innovation** [comment]
I have a few on the way, and would love to see & help this happen.

**Comment by CrazzyFrenchDude** [comment]
Hello guys, so happy and excited to finally be on Github, as a fast learner I have been snicking here and there in the 3D community, reading silently and learning. All this began with the need of a Pick and Place Machin for my "daily" DIY's!Then found out that the makers were using 3D printing controller boards for that matter! And some would have issues with using the thermistors input to plug in there vacuum sensor or other little annoying problems which are not real because the 3D controllers were not especially built for that (Pick And Place Machines)! So I went to the Open Pnp Forum and launched a thread, asking them what would their dream controller for OPNP be. Then started a humble design pcb design around the new comer Teensy 4.1, the PeeNaPle_V1.1b. With it's modularity it joins 3 worlds, not so different! 3D printing, CNC and Pick and Place Machines! With an array of extension boards, stepper driver adapters, Mosfet switches, extension boards, etc and not to mention what the makers will come up with!
Still in revision mode I just can't wait for Marlin to be supported or GrblHAL or any gerber firmware! So I give you an early glance at this little baby! All Fab files available here https://gitlab.com/CrazzyFrenchDude/peenaple_v1.1b/
![Screenshot 2020-08-13 at 14 23 10](https://user-images.githubusercontent.com/67338046/90134006-bc183480-dd70-11ea-9dd1-3d6ee4285d38.png)

**Comment by rarens** [comment]
@Hedda I have created a fork to support Teensy 4.1.  So far it compiles and uploads. Plus, I somehow got the SD card working.  It seems to run fine issuing G and M codes through the serial monitor though I haven't verified with a scope.

 I'm a mobile dev by trade and I really don't have a clue what I'm doing. All of the nondescript defines in mcu programming make my head spin. I just tinkered with it until it worked.   I would really like to get the SD to show up as a mass storage device.  So far I've been unsuccessful.  Any help would be greatly appreciated.  I would ultimately like to submit a pull request so that teensy 4.0/4.1 are officially supported. 

I did my best on the implementation of the timer HAL. I'm pretty sure it works but I really don't know how to verify it.  If anyone more knowledgeable than myself could assist I would be truly grateful!

https://github.com/rarens/Marlin/tree/teensy41

**Comment by CrazzyFrenchDude** [comment]
Check this fork https://github.com/bilsef/Marlin/tree/Teensy4.x

**Comment by Gamester17** [comment]
FYI, it looks like Teensy 4.1 (and Teensy 4.0) support has now been merged via https://github.com/MarlinFirmware/Marlin/pull/19311 via PR from @bilsef

Marlin Firmware bugfix-2.0.x branch README.md now specifically list these as supported controller boards:

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/README.md

**Teensy 4.0 / 4.1**
boards | processor | speed | flash | sram | logic | fpu
-- | -- | -- | -- | -- | -- | --
Teensy 4.0 | IMXRT1062DVL6A ARM-Cortex M7 | 600MHz | 1M | 2M | 3.3V | yes
Teensy 4.1 | IMXRT1062DVJ6A ARM-Cortex M7 | 600MHz | 1M | 2M | 3.3V | yes



Teensy 4.x is also supported in MarlinFirmware stable release branch but the description in the readme file is not as good:

https://github.com/MarlinFirmware/Marlin/blob/2.0.x/README.md

**Comment by Gamester17** [comment]
@rarens did you test / verify the pull request from @bilsef in https://github.com/MarlinFirmware/Marlin/pull/19311 pull request?

**Comment by nanotuxi** [comment]
@Gamester17 
tested on a bare teensy41 board. It's working connected to RepetierHost with dry-run enabled.
See [my comment](https://github.com/MarlinFirmware/Marlin/pull/19311#issuecomment-702851080).

**Comment by Gamester17** [comment]
Another FYI, just read about newly announced "iMX RT1064 uCOM" board from Embedded Artists so submitted a feature request:

https://github.com/MarlinFirmware/Marlin/issues/19749

Maybe depending on its price when general availability it might be an option for those looking at developing BoBs for Teensy 4.1
