### ISSUE TITLE
[BUG] Z-Offset LCD screen numerals corrupt during adjustment

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#17989]
Bug Description: Numerals in LCD adjustment screen corrupt as encoder wheel is turned.

My Configurations: SKR1.3 board with RepWrap discount display (default), Configuration files are included below.

Steps to Reproduce: 

1. Use a SKR1.3 with a discount (non graphical) RepWrap display.

2. Enter the Z-Offset adjustment Menu

3.  Observe the numerals scramble ( i.e. extra lines, the top bar of a 5 appearing in a six)

**Expected behavior: normal display of numerals

Actual behavior: scrambled numerals with functionality unaffected.

Additional Information:  This may happen in other screens with adjustable numerals.  I have not tested other screens.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4622591/Marlin.zip)

**Comment by oliver-eifler** [comment]
thats a timing problem (mostley with 32Bit boards) and some display controllers
// Alter timing for graphical display
#if HAS_GRAPHICAL_LCD
#define BOARD_ST7920_DELAY_1 DELAY_NS(96)
#define BOARD_ST7920_DELAY_2 DELAY_NS(48)
#define BOARD_ST7920_DELAY_3 DELAY_NS(600)
#endif
simpley add it at the end of configuration_adv.h

**Comment by bill-orange** [comment]
@oliver-eifler I had high hopes for that fix but it actually, in my installation, makes it worse.  With a ferrite bead the problem goes away.  With the noted delays the ferrite bead will no longer fix it. 

Since the behavior was changed, you are on the right track.  Perhaps the delays just need to be nudged a bit.
![IMG_0072](https://user-images.githubusercontent.com/18121312/81969969-9e053180-95d3-11ea-8e54-2e1c902b8ce0.jpg)

**Comment by ruggb** [comment]
I had that issue 6 months ago and used this after my display selection. Been working ever since. Got it from a post on the Reprap forum.
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER //**
#define ST7920_DELAY_1 DELAY_NS(0)   //** scrambled screen without these
#define ST7920_DELAY_2 DELAY_NS(250) //** may have something to do with
#define ST7920_DELAY_3 DELAY_NS(250) //** newer versions of the IDE or U8GLIB

**Comment by bill-orange** [comment]
@ruggb were the delays put in configuration.h around line 1925 or elsewhwere?  configuration_adv.h perhaps?

**Comment by ruggb** [comment]
just like it shows, right after the display define in config....h. I don't know that it matters exactly where it is I just put it there so I remember why I did it. The //** are just so I can find my changes easily

**Comment by ellensp** [comment]
you have REPRAP_DISCOUNT_SMART_CONTROLLER and REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER enabled.
This is going to cause you all sort of issues.
Also means we can't tell if you actually have a 20x4 char display of a graphics display attached.
You need to disable one.

**Comment by ruggb** [comment]
@ellensp 
> 
> 
> you have REPRAP_DISCOUNT_SMART_CONTROLLER and REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER enabled.
> This is going to cause you all sort of issues.
> Also means we can't tell if you actually have a 20x4 char display of a graphics display attached.
> You need to disable one.

Are you talking to me? If so how do you figure that?

**Comment by ellensp** [comment]
@ruggd no, I'm talking to the author about the authors provided configuration.h

**Comment by ruggb** [comment]
I didn't look at it, but his issue is slightly different than mine. Mine was garbage all the time, not just when turning the knob == I think only the full graphic has a knob.

**Comment by ellensp** [comment]
mate stop talking, its nothing to do with you or your comments.

**Comment by ruggb** [comment]
That comment was for the OPs benefit.
BTW, I wasn't talking, just wearing my fingers to the bone.
But, for some reason the CONTRIBUTORS attitude on this venue has taken a large turn for the worse.
Must be everyone is sick.

**Comment by bill-orange** [comment]
@ellensp You are correct about have both controller type defined.  I neglected to comment out `REPRAP_DISCOUNT_SMART_CONTROLLER`.  I added the delay statements noted by @ruggb and I will test it tomorrow.  However I suspect that whatever delays are used for my REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER are defined elsewhere.

**Comment by bill-orange** [comment]
Edit.  Sadly neither commenting out `REPRAP_DISCOUNT_SMART_CONTROLLER` and using the delays 0,250,250 or 96,48,600 helped.  The latter may make it worse.   The  greatest improvement remains the ferrite bead.

**Comment by boelle** [comment]
@bill-orange still an issue?

**Comment by bill-orange** [comment]
This was solved by adding ferrite to one cable, not an ideal solution. Since no one has a better idea, I think we can close it
