### ISSUE TITLE
[BUG] M48 Z_MIN_PROBE_REPEATABILITY_TEST count multiplied by multiple probing

### ISSUE THREAD

**Issue by DroneMang** [MarlinFirmware/Marlin#17994]
Hi,

Say I have multiple probing set to 10.  I then run M48 P4 V4.  This will result in 40 probes for the M48 test.

Expected behavior: M48 P4 V4 will run its test with 4 probes, and G29 P1 T will do a bed probing routine with 10 probes per point.

Using bugfix 2.0.

Thanks,
DroneMang

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
