### ISSUE TITLE
BED_THERMAL_PROTECTION causes compile error 

### ISSUE THREAD

**Issue by MoonshineSG** [MarlinFirmware/Marlin#1800]
after updating to latest commit 4c7af484f8:

temperature.cpp:87:105: error: scalar object 'thermal_runaway_bed_state_machine' requires one element in initializer
     static TRState thermal_runaway_bed_state_machine = { TRInactive, TRInactive, TRInactive, TRInactive };
                                                                                                         ^

**Comment by emartinez167** [comment]
Same error here

On Sat, Apr 4, 2015 at 11:52 AM, Ovidiu Hossu notifications@github.com
wrote:

> after updating to latest commit 4c7af48
> https://github.com/MarlinFirmware/Marlin/commit/4c7af484f8a87bd6f602eb0eed5aec0c3f2ae99c
> :
> 
> temperature.cpp:87:105: error: scalar object
> 'thermal_runaway_bed_state_machine' requires one element in initializer
> static TRState thermal_runaway_bed_state_machine = { TRInactive,
> TRInactive, TRInactive, TRInactive };
> ^
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1800.

## 

"This e-mail and any attachments thereto, are intended only for use by the
addressee(s) named herein and may contain confidential or privileged
information. If you are not the intended recipient of this e-mail, you are
hereby notified that any dissemination, distribution or copying which
amounts to misappropriation of this e-mail and any attachments thereto, is
strictly prohibited. If you have received this e-mail in error, please
immediately notify me and permanently delete the original and any copy of
any e-mail and any printout thereof."
P Please consider the environment before printing this email
