### ISSUE TITLE
what env setting do i use for ultratronics pro

### ISSUE THREAD

**Issue by ralf1978** [MarlinFirmware/Marlin#18018]
i am trying to load merlin 2.0 on a ultratronics pro board.
i set my board in Marlin\Configuration.h to #define BOARD_ULTRATRONICS_PRO 
and my env in platformio.ini  to DUE

when i compille it fails 

any tips on how to fix this

**Comment by ellensp** [comment]
1) read https://github.com/MarlinFirmware/Marlin/issues/14694
2) follow the template and include an error log. 

But most likely you have done as you said
 #define BOARD_ULTRATRONICS_PRO  which is incorrect, you need the motherboard keyword. 
should be
`#define MOTHERBOARD BOARD_ULTRATRONICS_PRO
`

**Comment by ralf1978** [comment]
super thnx it works now

**Comment by ellensp** [comment]
Please close this issue
