### ISSUE TITLE
[BUG] STARTUP_COMMANDS Not Parcing Multiple G-Codes

### ISSUE THREAD

**Issue by borland1** [MarlinFirmware/Marlin#18026]
In Configuration_adv.h file, Startup Commands section provides sample format for only a single g-code:
//#define STARTUP_COMMANDS "M17 Z"

When sending multiple g-codes, parcer seems to ignore subsequent g-codes.  Sending g-code M300 to play series of tones on powerup with the following configuration, plays only one short tone.

// Play Startup Tones ...
#define STARTUP_COMMANDS "M300 S440 P200, M300 S660 P250, M300 S880 P300"

### My Configurations
[2.0.5.3_ConfigFiles.zip](https://github.com/MarlinFirmware/Marlin/files/4641500/2.0.5.3_ConfigFiles.zip)

**Comment by ellensp** [comment]
The specification for gcode is one gcode per line. You need to insert \n between each gcodes so that the string is interpreted as multiple lines and not just one line.
Don't use , to separate gcodes.

**Comment by borland1** [comment]
ellensp, Thank you.

This tests good...

`#define STARTUP_COMMANDS "M300 S440 P200 \n M300 S660 P250 \n M300 S880 P300"`

More readable format of this line of code would look like this:

```
#define STARTUP_COMMANDS \
  "M300 S440 P200 \n \
   M300 S660 P250 \n \
   M300 S880 P300"
```
