### ISSUE TITLE
[BUG] #define PID_AUTOTUNE_MENU results in incorrect menu text

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#18021]
Bug Description:
Enabling PID_AUTOTUNE_MENU results in the requested menu, in the proper spot.  However, PID Autotune E1 is offered when only one extruder ,E0 exists.  The autotune function is performed on E0 if  this menu item is selected.

My Configurations: included at end of post

Steps to Reproduce

1. Scroll through to the autotune menu correctly located in Configuration -> Advanced Configuration -> Temperature
2. Observe last line. Autotune for E1 is offered instead of E0

Expected behavior: Menu item should be PID Autotune E0 or perhaps PID Autotune

Actual behavior: Menu item should be PID Autotune E1

Additional Information:
 I am assuming that the number displayed after PID Autotune E1 is target temperature.  It is 150.  Autotune is performed on E0 upon the E1 selection.  I suspect there is a typo somewhere in the code.  The correct menu text might omit the extruder number entirely.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4640846/Marlin.zip)
![IMG_0074](https://user-images.githubusercontent.com/18121312/82157690-ed4b9c00-9837-11ea-8f36-d1345ef4f715.jpg)

**Comment by boelle** [comment]
@bill-orange still an issue?

**Comment by bill-orange** [comment]
I think we can close it
