### ISSUE TITLE
Need Help Getting Sensorless Homing working...

### ISSUE THREAD

**Issue by visualcortexlab** [MarlinFirmware/Marlin#18037]
### Bug Description

ok I'm giving up. I can't get this to work. :((
after days of googling, youtubing and little sleep I'm giving up and hopefully someone here can see the problem.
Sensorless homing not working.
As soon as I issue a G28 the printer sets (0,0,0) wherever the extruder is at that time without making a single move.
Homing Z works, which means that most of the time I also crash both X and Y because they're not Homed.
in Marlin I tried changing all sort, voltage, sensitivity, anything. Not a single change in behaviour. So I must be missing something very obvious, and its been days of the same exact failure, over and over.
Some help is really really appreciated as I have my printer all over the table since 2 two weeks trying to configure it :\
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/4646936/configs.zip)

Thank you for any help!

**Comment by ellensp** [comment]
This is not a general support forum.
Please read https://github.com/MarlinFirmware/Marlin/issues/14694 and use one or multiple of those services.

**Comment by swilkens** [comment]
sensorless homing can be difficult to tune, similar issues and tuning approach described here:

https://github.com/MarlinFirmware/Marlin/issues/15848

**Comment by visualcortexlab** [comment]
Thank you:)

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
