### ISSUE TITLE
M217 issue with SINGLENOZZLE and SWITCHING_EXTRUDER

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#18034]
M217 (TOOLCHANGE_FILAMENT_SWAP) is not working with singlenozzle and switching extruder.

Example:

Current tool is T0, if a T1 is issued the T0 is retracted 2x the Swap length, and T1 is not loaded.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
