### ISSUE TITLE
xxx

### ISSUE THREAD

**Issue by mjp808** [MarlinFirmware/Marlin#18041]

**Comment by ellensp** [comment]
It a micro controller, flash is over written with new firmware...   errors are not kept across firmware updates. Something else is wrong.

**Comment by mjp808** [comment]
I made a mistake in OP, the error is e1 maxtemp, but essentially same issue
his is the second board thats stuck in this loop. The only way to get access to the board is giving temp sensor 0 a dummy 998 temp. m502/m500 doesnt clear it. If there was a way of flushing out old temp compensation settings it would help. thermistors are all tested and working.

**Comment by ellensp** [comment]
Since you have now discovered the short from the heater cartage to the thermistor pins, instantly annihilating the controller. Please close this issue. as Its not an firmware issue.

**Comment by mjp808** [comment]
Not %100 sure thats the problem, but will do
