### ISSUE TITLE
[FR]serial communication RUMBA to NANO

### ISSUE THREAD

**Issue by DrumClock** [MarlinFirmware/Marlin#18050]
HI, how do I set up serial communication in Marlin configuration?

![RX_TX](https://user-images.githubusercontent.com/64655979/82421128-e2d01300-9a80-11ea-89de-be51ba202e48.PNG)

**Comment by ellensp** [comment]
You need to read https://github.com/MarlinFirmware/Marlin/issues/14694
This is not the pace for support requests.
