### ISSUE TITLE
[GLITCH] Progress bar 1 pixel a tad too low after commit

### ISSUE THREAD

**Issue by Lord-Quake** [MarlinFirmware/Marlin#18058]
![20200518_125806](https://user-images.githubusercontent.com/29223282/82496109-7985e980-9aec-11ea-9b77-27d1610e9fcb.jpg)

After a certain commit the progress bar fell by 1 pixel :-( 

Lets give it a hand and move it up to where it rightly belongs :-)

Where: Marlin/src/lcd/dogm/status_screen_DOGM.cpp 

Change to: `#define PROGRESS_BAR_Y (EXTRAS_BASELINE + 1)`

**Comment by thisiskeithb** [comment]
You should put a PR in with the fix 🙂

**Comment by ellensp** [comment]
Yes it is an ideal simple change to learn to make PR's 
Though I feel this change is subjective... It doesn't interfere with the text below or above. 
I suspect your OCD is playing up..  It doesn't have to be on the same level as the bottom of the SD card icon.

**Comment by Lord-Quake** [comment]
OK @thisiskeithb, you win :-) You got me to install github desktop and make my first pull request. Hope I did it correctly.

**Comment by ellensp** [comment]
PR Looks good.

**Comment by swilkens** [comment]
Possibly caused here?

https://github.com/MarlinFirmware/Marlin/issues/17940
