### ISSUE TITLE
Controll -> Temperature -> Fan Speed 2

### ISSUE THREAD

**Issue by AnDrEaZaNoLeTtI** [MarlinFirmware/Marlin#18057]
Controll -> Temperature -> Fan Speed 2
### Bug Description

Dear all, 

If I change the speed of fan 2 in the temperature submenu, the value is set to fan 3.

thanks to all

### My Configurations

BOARD BTT SKR PRO V1.1
ZONESTAR LCD
![Annotazione 2020-05-20 211143](https://user-images.githubusercontent.com/65680174/82487592-dbd7ed80-9ade-11ea-9e61-ef954eac38c6.png)
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4658832/Configuration.zip)

**Comment by boelle** [comment]
@AnDrEaZaNoLeTtI still an issue?

**Comment by AnDrEaZaNoLeTtI** [comment]
Yes

Il Dom 21 Giu 2020, 01:57 Bo Herrmannsen <notifications@github.com> ha
scritto:

**Comment by boelle** [comment]
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

**Comment by AnDrEaZaNoLeTtI** [comment]
I download yesterday last version on "bugfix-2.0.x branch" and i see that the problem still remain

but i see that same issue is already opened [https://github.com/MarlinFirmware/Marlin/issues/17570](url)

sorry.
i close that one....
