### ISSUE TITLE
When doing PID Autotune, Error:Line Number is not last Line Number+1, Last Line: xxx causes PID autotune to stop

### ISSUE THREAD

**Issue by emartinez167** [MarlinFirmware/Marlin#1806]
I have been noticing when printing in Cura an ocassional message in the console about Line Number is not last Line Number + 1. I have disregarded this as it generally does not interfer with the print. However, it is a different story when trying to do PID autotune from Repetier. The graph just stopped and the process seems to stop altogether. Perhaps we can see where the real issue is where some process is not returning the proper line number as expected by the host?

**Comment by thinkyhead** [comment]
I believe sometimes commands are allowed to go in ahead, if they have a higher priority. But maybe someone who knows more about the command queue can speak on this with more authority…

**Comment by boelle** [comment]
Should we keep this one open? or maybe upgrade it?

**Comment by tonnico** [comment]
Most time this happens when the host didn't wait for the 'ok'. Maybe Cura has some 'security' feature which sends the next command when the pause is to long? Did you tried some other host? Pronterface or Repetier?

**Comment by emartinez167** [comment]
Will try with something else and report back.

**Comment by boelle** [comment]
@emartinez167 what did you find out?

**Comment by thinkyhead** [comment]
This should be fixed in the current RC (RC2). Please check and close this issue if it's fixed.
