### ISSUE TITLE
[BUG] Auto bed leveling not correcting cutting depth for PCB milling

### ISSUE THREAD

**Issue by SonOfSardaar** [MarlinFirmware/Marlin#18072]
### Bug Description

I have modified my printer with 210 x 210 bed size, to mount V bit for PCB milling and my PCB is 70x100 mm in the center of the bed. I configured bilinear bed leveling with nozzle as probe. The drill motor is powered from different source and not controlled via marlin. When i probe the pcb area i want mill and start the milling then some tracks are being cut at different depth and in some cases the cutting depth changes suddenly. See the pictures attached at the bottom

### My Configurations
- Marlin bugfix-2.0.x
- Bed Size 210 x 210 with 70 x 100 mm PCB at the centre of the bed.
- Drilling motor mounted with V drill bit of 30 degrees 
- Motor powered from external 24V battery
- Milling feedrate used 60

[Configurations](https://github.com/MarlinFirmware/Marlin/files/4668921/Marlin.zip)

### Steps to Reproduce
1. Home and then go to pcb lower left corner G1 X70 Y60
2. Home offsets at this position M206 X-70 Y-60
3. Probe PCB engraving area G29 L0 Y0 R50 B30 (only the rectangle i want to engrave)
4. Start print

**Expected behavior:** This should engrave the pcb tracks at same depth

**Actual behavior:** Pcb tracks are being engraved at different depth and in some cases abruptly changes engraving depth

#### Additional Information

![Machine](https://user-images.githubusercontent.com/9803499/82682758-aef31a00-9c47-11ea-9b6c-9909bfa822a4.jpg)
![PCB 1](https://user-images.githubusercontent.com/9803499/82682770-b3b7ce00-9c47-11ea-9c17-52b212db35e1.jpg)
![PCB 2](https://user-images.githubusercontent.com/9803499/82682623-76ebd700-9c47-11ea-9994-2f489ed282d2.jpg)
![Leveling Info](https://user-images.githubusercontent.com/9803499/82682789-b9151880-9c47-11ea-95b5-7297f6291ee8.jpg)

**Comment by sjasonsmith** [comment]
My first thought is that you should be probing more points for something like PCB etching. Try increasing GRID_MAX_POINTS_X and GRID_MAX_POINTS_Y to see if that improves things. For engraving traces you probably want the largest number of probe points possible.

**Comment by SonOfSardaar** [comment]
Thanks @sjasonsmith the pcb i was trying to mill in this case was only 25x40 mm and that area had 3x3 probes and i thought that would be enough but i will give it a go with more probing points.

**Comment by boelle** [comment]
@SonOfSardaar still an issue?

**Comment by SonOfSardaar** [comment]
Ya still an issue. I tried with 5x5 points with 3 samples each and it takes a lot of time but no luck. It is still being abrupt as shown in the images

**Comment by sjasonsmith** [comment]
I removed the stale label, because those do look like extremely abrupt changes in the pictures provided. It seems like some investigation is warranted.
