### ISSUE TITLE
[FR] add support for 2004 character OLED

### ISSUE THREAD

**Issue by knickohr** [MarlinFirmware/Marlin#18083]
Hi !

Is it possible to add support for the Winstar or Raystar OLED ?

https://www.winstar.com.tw/products/oled-module/oled-character-display/20x4-oled.html
https://www.raystar-optronics.com/oled-character-display-module/20x4-oled-display.html

They use the WS0010/RS0010 controller, is nearly compatible with the HD44780 LCD controller, but not 100%. The initialization routine is a bit different. Some guys from Prusa community managed it working.

Datasheet for the controller :
https://datasheetspdf.com/pdf-file/1110077/ETC/WS0010/1

**Comment by thisiskeithb** [comment]
To get it working in the interim on LPC-based builds, change this line in `platformio.ini` from:
https://github.com/MarlinFirmware/Marlin/blob/41529b65988a58ba512977e0fe1692aaeeb6c811/platformio.ini#L227

To:
`USES_LIQUIDCRYSTAL      = LiquidCrystal=https://github.com/thisiskeithb/LiquidCrystalOLED/archive/1.0.8.zip`

It's a custom library that works with both traditional HD44780 LCDs and the WINSTAR OLED (but only on LPC processors).

**Comment by jbyerline** [comment]
Bump... I would also love to see this feature. I cant imagine it would be hard because the display is so similar to the standard 2004 LCD. @thisiskeithb I tried the library above but it doesnt seem to work in newer versions of marlin.

**Comment by thisiskeithb** [comment]
> I tried the library above but it doesnt seem to work in newer versions of marlin.

I use it in my Prusa AIO fork, but it’s only compatible with LPC-based builds.

https://github.com/thisiskeithb/PrusaAIO/blob/79b53616406ea09230a93c031aac6ef9bb3449ac/ini/lpc176x.ini#L26-L27

`custom_marlin.USES_LIQUIDCRYSTAL = LiquidCrystal=https://github.com/thisiskeithb/LiquidCrystalOLED/archive/1.0.8.zip`

**Comment by jbyerline** [comment]
> 

@thisiskeithb What does LPC stand for?

**Comment by thisiskeithb** [comment]
> What does LPC stand for?

It’s the processor type on your motherboard. LPC1768/LPC1769.

**Comment by jbyerline** [comment]
Ah, okay I am using an Einsy Rambo. So in that case, back to my original point. Is this a feature that is relatively simple to integrate?

**Comment by jbyerline** [comment]
Any new thoughts on adding this functionality to Marlin 2.0?

**Comment by jbyerline** [comment]
What version was this feature added in?

**Comment by thisiskeithb** [comment]
It was never added.

**Comment by jbyerline** [comment]
So why was it marked as closed?

**Comment by ellensp** [comment]
original requester closed it, probably because they no longer want it, or just got sick of getting e-mails

**Comment by thisiskeithb** [comment]
@jbyerline Feel free to [open a new Feature Request](https://github.com/MarlinFirmware/Marlin/issues/new?assignees=&labels=T%3A+Feature+Request&template=feature_request.yml&title=%5BFR%5D+%28feature+summary%29) if you would still like to see OLED 2004/Character LCD support in Marlin.

**Comment by knickohr** [comment]
Found a solution, replaced a modified library. But the code in not from my brain, so it’s not public.

![EC1E9E72-D647-4603-BBF2-9B6A58E4969A](https://user-images.githubusercontent.com/63048210/208288221-4f2219e8-831e-4ddd-bf8d-e5d97d83ba79.jpeg)

Works with a 1:1 replacement OLED, like the Winstar series.

**Comment by jbyerline** [comment]
Can you post a link to it please.
