### ISSUE TITLE
End of a loop make a short pause before continuing the printing

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#18093]
In Marlin 2.0.5.3, every end of a loop causes the print to a short pause before continuing.

**Comment by sjasonsmith** [comment]
When you create a new issue there is a template to follow, with specific details requested. There is not enough information in this for anybody to even begin to investigate it.

**Comment by swilkens** [comment]
Try to re-compile the firmware with `CLASSIC_JERK`

**Comment by AnHardt** [comment]
What loop?
G-code has no loop-construct.
Inside Marlin there are thousands of loops.
Perimeter-loop?

**Comment by Miraculix200** [comment]
You mean like this? https://github.com/MarlinFirmware/Marlin/issues/17920

**Comment by sjasonsmith** [comment]
I am closing this issue, as there is no actionable information here.
