### ISSUE TITLE
[BUG]  X/Y axis minimum speed is limited

### ISSUE THREAD

**Issue by frank-pian** [MarlinFirmware/Marlin#18107]
I'm having problem with delta machine.When I used the G0 or G1 command to control the X/Y axis movement, there was no significant speed change for the F parameter below 500 or so, but the Z axis was ok

Thanks!

-------------------------------------------------------------------------------------------------
sorry,I think it might be a bug, but I'm not sure.
latest bugfix-2.0.x

### Bug Description
Delta printer setting X and Y axis movement speed cannot be lower than 400mm/min (presumably).
This problem was found on the STM32F407, ~~but the same configuration file was normal on Mega2560 and LPC1768.~~

### My Configurations
https://drive.google.com/file/d/1t31QBkAadgsnsHEWcnfp95iA_YUcbHdR/view?usp=sharing
```
SENDING:M503
echo:  G21    ; Units in mm (mm)
echo:; Filament settings: Disabled
echo:  M200 D3.00
echo:  M200 D0
echo:; Steps per unit:
echo: M92 X100.00 Y100.00 Z100.00 E338.00
echo:; Maximum feedrates (units/s):
echo:  M203 X500.00 Y500.00 Z500.00 E500.00
echo:; Maximum Acceleration (units/s2):
echo:  M201 X3000.00 Y3000.00 Z3000.00 E3000.00
echo:; Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P3000.00 R3000.00 T3000.00
echo:; Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
echo:  M205 B20000.00 S0.00 T0.00 X10.00 Y10.00 Z10.00 E5.00
echo:; Endstop adjustment:
echo:  M666 X0.00 Y0.00 Z0.00
echo:; Delta settings: L<diagonal_rod> R<radius> H<height> S<segments_per_s> XYZ<tower angle corrections>
echo:  M665 L380.00 R159.00 H237.00 S200.00 X0.00 Y0.00 Z0.00
echo:; PID settings:
echo:  M301 P22.20 I1.08 D114.00
```

### Steps to Reproduce
1. G91
2. G1 X20 F400
3. G1 X-20 F40
3. The print head moves at the same speed.

***

JUN/4
Updates about the latest discovery.
I find a parameter DELTA_SEGMENTS_PER_SECOND and did some testing.

DELTA_SEGMENTS_PER_SECOND  200
RUN "G1 X10 F10"
The execution time is 1.2 seconds.

DELTA_SEGMENTS_PER_SECOND 10
RUN "G1 X10 F10"
The execution time is 14 seconds.

DELTA_SEGMENTS_PER_SECOND 1
RUN "G1 X10 F10"
The execution time is 24 seconds.

***

JUN/22
@boelle 
I solved this problem temporarily with TMC2209 and 256 micro steps.But I don’t think it’s a good idea

**Comment by ellensp** [comment]
Please read https://github.com/MarlinFirmware/Marlin/issues/14694 
Ask in the discord and please close this question.

**Comment by frank-pian** [comment]
> 
> 
> Please read #14694
> Ask in the discord and please close this question.

sorry，i fixed my question.
I think it may be related to this part of the code, but I don't know how to modify it.
stepper.h
```
#ifdef CPU_32_BIT
  /**
   * Duration of START_TIMED_PULSE
   *
   * ...as measured on an LPC1768 with a scope and converted to cycles.
   * Not applicable to other 32-bit processors, but as long as others
   * take longer, pulses will be longer. For example the SKR Pro
   * (stm32f407zgt6) requires ~60 cyles.
   */
  #define TIMER_READ_ADD_AND_STORE_CYCLES 34UL

  // The base ISR takes 792 cycles
  #define ISR_BASE_CYCLES  792UL

  // Linear advance base time is 64 cycles
  #if ENABLED(LIN_ADVANCE)
    #define ISR_LA_BASE_CYCLES 64UL
  #else
    #define ISR_LA_BASE_CYCLES 0UL
  #endif

  // S curve interpolation adds 40 cycles
  #if ENABLED(S_CURVE_ACCELERATION)
    #define ISR_S_CURVE_CYCLES 40UL
  #else
    #define ISR_S_CURVE_CYCLES 0UL
  #endif

  // Stepper Loop base cycles
  #define ISR_LOOP_BASE_CYCLES 4UL

  // To start the step pulse, in the worst case takes
  #define ISR_START_STEPPER_CYCLES 13UL

  // And each stepper (start + stop pulse) takes in worst case
  #define ISR_STEPPER_CYCLES 16UL
```

**Comment by sjasonsmith** [comment]
> I think it may be related to this part of the code

Why do you think this code in particular would be part of the problem?

Those numbers are used to predict a maximum stepper rate, but I don’t think they contribute to a minimum speed.

**Comment by p3p** [comment]
Minimum speed, as far as I remember, is dictated by the resolution and frequency of the timers used for stepping, not sure how this board is configured but if, for example, you have a 16bit timer running at 1MHz it cant trigger a step less than once every 65ms. Marlin may have added a safegaurd minimum since then though?

**Comment by sjasonsmith** [comment]
It is definitely using a 16 bit timer. Only timers 2 and 5 are 32-bit. Those are currently used for other functions in the variant.h file, but could probably be switched around. To give a higher resolution step timer.

**Comment by frank-pian** [comment]
> 
> 
> Minimum speed, as far as I remember, is dictated by the resolution and frequency of the timers used for stepping, not sure how this board is configured but if, for example, you have a 16bit timer running at 1MHz it cant trigger a step less than once every 65ms. Marlin may have added a safegaurd minimum since then though?

thanks for your help! I think you are right. But I haven't found the real reason yet.

**Comment by frank-pian** [comment]
> 
> 
> It is definitely using a 16 bit timer. Only timers 2 and 5 are 32-bit. Those are currently used for other functions in the variant.h file, but could probably be switched around. To give a higher resolution step timer.

If it is caused by the timer, why does the z-axis work normally? In addition, if it is not the delta machine, the X/Y axis speed is normal.

**Comment by frank-pian** [comment]
[BUG] Movement uneven (with large DELTA_SEGMENTS_PER_SECOND) #14532

**Comment by boelle** [comment]
@frank-pian still an issue?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
