### ISSUE TITLE
[BUG]  Marlin 2.0.5.3 Auto Bed Leveling

### ISSUE THREAD

**Issue by celticht32** [MarlinFirmware/Marlin#18119]
I have a BLTouch v3 and have flashed Marlin 2.0.5.3 onto my Creality CR-10 S4... I followed every change guide I could find on the interwebs... and compiled and flashed to the CR-10. I got the cmos error.. Re-saved my settings at the default screen with no changes on the controller.. I then selected to do the auto bed leveling..

The gantry goes to the home center and deploys the BLTouch as normal.. then goes to the first probe point of 9 performs that correctly then goes to the second point deploys the BLTouch goes down a few then stops without touching the bed then raises up and then stops and the auto bed leveling stops without continuing..

**Comment by celticht32** [comment]
[creality-cr10s4-bltouch3.zip](https://github.com/MarlinFirmware/Marlin/files/4683094/creality-cr10s4-bltouch3.zip)

**Comment by c3D-Dan** [comment]
Check your bed is within 2mm from corner to corner.  If it's not, weird things happen. Run G29 P1 T to see how close you are.

**Comment by psavva** [comment]
Is this a duplicate of https://github.com/MarlinFirmware/Marlin/issues/18033

**Comment by celticht32** [comment]
it actually could be but mine I have 9 points defined and it stops on the second one.... 
the display says 9 points  and like I said goes to the center home point... then point 1 and then goes to the second one and stops and goes to the main marlin menu.... and yes the video does what mine does at probe 2 his does it on probe 7

**Comment by psavva** [comment]
> Download Marlin bugfix-2.0.x to test with the latest code.
> Enable DEBUG_LEVELING_FEATURE and M114_DETAIL and re-flash the firmware.
> Issue M111 S247 to enable maximum logging.
> Issue G28
> Issue G29 V4
> Attach the log output into a .TXT file

See if you find Probing Failed towards the end of the log.  If so, seems that it's the same bug
..

I enabled UBL from @Roxy-3D  as it doesn't suffer from the same issue.  I'm sticking with UBL because of how well it performs. Absolutely awesome is all I can say

**Comment by celticht32** [comment]
I will test it.. I saw you changing to UBL fixes the problem so I changed that and reflashing now...  will test in the morning

**Comment by celticht32** [comment]
This is the same as issue above... doing UBL fixes the issue per above... so bug is https://github.com/MarlinFirmware/Marlin/issues/18033

**Comment by celticht32** [comment]
also tested per above and get same log entry...
