### ISSUE TITLE
[BUG] [bugfix-2.0.x] [SWITCHING_NOZZLE ] Continuously changing the nozzle causes the height to increase

### ISSUE THREAD

**Issue by scott0122** [MarlinFirmware/Marlin#18113]
### Bug Description
Continuously changing the nozzle causes the height to increase after homing.

https://www.youtube.com/watch?v=OMkm0p_0DBQ

### My Configurations
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4678929/Configuration.zip)

**Comment by ebuyum** [comment]
I can confirm this happens to me as well on latest bugfix-2.0.x

I don't have a mechanical switch like @scott0122 showed, but am using a single nozzle with dual extruders.

I suspect this has to do with TOOLCHANGE_ZRAISE inside advanced configuration, as marlin reports the updated position (+2 in my case).

Thanks.

**Comment by c3D-Dan** [comment]
I have a similar hotend.  Doesnt happen for me. 2.0.5 bugfix.

**Comment by sjasonsmith** [comment]
@scott0122 or @coolcheat, if this is still an issue, can you provide updated configuration files for the latest bugfix-2.0.x, and provide exact steps to reproduce/observe the problem?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by scott0122** [comment]
@sjasonsmith 
Configuration files are in my first post. 
Power on -> Switch nozzle(T0, T1, T0, T1...) -> z height continuously increased. 
Power on -> Auto Home(G28) -> Switch nozzle(T0, T1, T0, T1...) -> z height continuously increased.
