### ISSUE TITLE
[FR] Make https://marlinfw.org/docs/configuration/configuration.html readable

### ISSUE THREAD

**Issue by Tofoillote** [MarlinFirmware/Marlin#18123]
### Bug Description

on screen display of https://marlinfw.org/docs/configuration/configuration.html

is absolute mess going insanely wide !

### My Configurations

up to date firefow or chrome

### Steps to Reproduce

Have a look and shfit+wheelmouse scroll ...

#### Additional Information

Sorry for anouncing it this way, but it make me nuts, I really need that doc !

**Comment by Tofoillote** [comment]
![image](https://user-images.githubusercontent.com/35838145/82944871-42a44d80-9f9c-11ea-9fc6-9b7f1b40ab48.png)

**Comment by thisiskeithb** [comment]
This was already reported in the [MarlinDocumentation repo](https://github.com/MarlinFirmware/MarlinDocumentation/issues/306).

[Here's a link to the readable configuration page](https://github.com/MarlinFirmware/MarlinDocumentation/blob/master/_configuration/configuration.md).

**Comment by rflulling** [comment]
wow, some looks like "My First HTML" in there. Over board on the nested cells, and does not have the boundaries set right.

I am glad to see needed updates. However this one didn't quite get off the ground.

**Comment by sjasonsmith** [comment]
I'll go ahead and close this, because it looks like it was fixed. I remember seeing the problem when this was first reported, and it is all displaying cleanly for me now.
