### ISSUE TITLE
[BUG] TMC2130 whinnig when it's not moving

### ISSUE THREAD

**Issue by kadangriebeler** [MarlinFirmware/Marlin#18126]
Recently i instaled a new TMC2130 driver on my 3D printer, my goal was make it quieter but after the instalation emerged a prety annoying whine when it's not moving and I don't know how fix it... Anyone have this issue?

**Comment by swilkens** [comment]
We need configuration files, printer model and control board information to be able to help you - as the template asks you to provide.

This sounds like the driver is in spreadcycle mode

**Comment by kadangriebeler** [comment]
I'm sorry for the missing info and for my rubbish english...
I have a generic graber i3 from a local kit seller. It has mega2560 + ramps 1.4. I'm running the latest bug_fix 2.0.
During the printing, the movement noise is barely audible, but when the motors are stop came a fine whine.
Which are the files and how i upload them?

Thanks for the patien!

**Comment by psavva** [comment]
Please upload your configuration and configuration_adv files

**Comment by AmiSMB** [comment]
Not sure what your configuration is but you will get a whining no matter what if you are running at 12v.

**Comment by sjasonsmith** [comment]
Closing due to required and requested configuration information not being provided.
