### ISSUE TITLE
[BUG] (Leveling Fade causes gradual increases in layer height)

### ISSUE THREAD

**Issue by snekonaplane** [MarlinFirmware/Marlin#18136]
### Bug Description

When leveling fade is enabled, each increase in layer height beyond the set fade height has an additional z movement. This eventually causes the print to fail.

### My Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4693199/Configuration.zip)

### Steps to Reproduce

1. Set a fade height of 5 with start g code in slicer
2. Run print
3. Allow print to reach a layer height beyond the fade height

**Expected behavior:** [What you expect to happen]

The bed level will be fully faded and the z compensation will cease. The z height will increment by the set layer height.

**Actual behavior:** [What actually happens]

The bed level fades and z compensation ceases, but there is an additional z movement with each layer increment.

#### Additional Information

![IMG_20200527_230921](https://user-images.githubusercontent.com/64229479/83098910-73a28200-a071-11ea-9a95-f4d4b3301904.jpg)

**Comment by ellensp** [comment]
"CONFIGURATION_H_VERSION 010109" 
marlin 1.1.9 is no longer under development

Please try this feature in current bugfix 2.0.x to ascertain if problem still exists in currently maintained marlin.

**Comment by sjasonsmith** [comment]
@snekonaplane, are you able to test with Marlin 2.x as @ellensp suggested? You realistically are not likely to ever see a fix for something like this in the 1.x codebase.

**Comment by shitcreek** [comment]
This looks like a major issue which should have been caught and fixed by now if it's an actual bug.
That said, Marlin 1.x is no longer supported. Please use 2.x instead.
