### ISSUE TITLE
length of arc is calculated incorrectly in G2/G3 motion

### ISSUE THREAD

**Issue by eyal0** [MarlinFirmware/Marlin#18141]
The length of the ARC is assumed to be [`MM_PER_ARC_SEGMENT`](https://github.com/MarlinFirmware/Marlin/blob/e4d8336175ee09b28d23220f446d07451ca3de43/Marlin/src/gcode/motion/G2_G3.cpp#L219) yet the calculation might actually use a larger value if that length doesn't evenly divide the total length of the ARC.

Read more [here](https://github.com/eyal0/OctoPrint-PrintTimeGenius/issues/195#issuecomment-635385954).

**Comment by sjasonsmith** [comment]
@eyal0, I am presuming this can be closed since your own PR claiming to fix it has been merged.
