### ISSUE TITLE
[BUG] #include errors detected

### ISSUE THREAD

**Issue by leytanelectronics2** [MarlinFirmware/Marlin#18158]
I'm trying to compile Marlin 2.0.x but i keep getting this error message in platformIO 

#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\tgwin\Desktop\3d files\3d printer programs\anet a8 firmware\Marlin-bugfix-2.0.4\Marlin-bugfix-2.0.x\Marlin\src\MarlinCore.cpp).

can anyone tell me what this means and how to fix it?

I also can not upload the program to an Arduino mega 2560 board which I am using. when it compiles it says failure next to that board type.

**Comment by sjasonsmith** [comment]
@leytanelectronics2, right now this doesn't seem like a bug. If you are still having issues, I suggest visiting one of the several  forums or user groups suggested on the "New issue" page:

https://github.com/MarlinFirmware/Marlin/issues/new/choose
