### ISSUE TITLE
SD Firmware Update issue with STM32103

### ISSUE THREAD

**Issue by ModMike** [MarlinFirmware/Marlin#18163]
##Bug Description##

I am trying to use the SD Firmware update function with a Fysetc Cheetah 1.1b board. I installed the new Fystec SD firmware updater capable boot loader on the board and used the latest official Marlin bug fix branch from yesterday.

As per the Fysetc instructions I went to add their code but found similar code already there. When I uncomment the existing code and build, it fails.

When I use the Fysetc code using [their instructions](https://github.com/FYSETC/Bootloader-STM32F103), Marlin builds successfully. When flashed via regular USB, it will not boot. re-flashing without the code allows Marlin to boot with the new boot loader.

##Hardware Used##

1) Ender 3
2) Fysetc Cheetah 1.1b (new improved version of board)with new boot-loader from their [Github](https://github.com/FYSETC/Bootloader-STM32F103)
3) Proven SD card (did many prints with it)

##Steps to reproduce for Marlin:##

Test 1

1) Uncomment similar code in Marlin\Marlin\buildroot\share\PlatformIO\scripts\fysetc_STM32F1.py:

`# Relocate firmware from 0x08000000 to 0x08010000
# for define in env['CPPDEFINES']:
#    if define[0] == "VECT_TAB_ADDR":
#        env['CPPDEFINES'].remove(define)
#env['CPPDEFINES'].remove(("VECT_TAB_ADDR", 134217728))
#env['CPPDEFINES'].append(("VECT_TAB_ADDR", "0x08010000"))`

2) Build using STM32103RC_Fysetc Env

3) Build fails with following error:

`ValueError: list.remove(x): x not in list:
  File "/Users/Michael/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 176:
    env.SConscript(item, exports="env")
  File "/Users/Michael/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 541:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/Users/Michael/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 250:
    exec _file_ in call_stack[-1].globals
  File "/Users/Michael/Documents/GitHub/Marlin-bugfix-2.0.x/buildroot/share/PlatformIO/scripts/STM32F103RC_fysetc.py", line 9:
    env['CPPDEFINES'].remove(("VECT_TAB_ADDR", 134217728))`

Test 2

1) Do not uncomment code
2) Addd Fysetc code

`define in env['CPPDEFINES']:
    if define[0] == "VECT_TAB_ADDR":
        env['CPPDEFINES'].remove(define)
env['CPPDEFINES'].append(("VECT_TAB_ADDR", "0x08010000"))
env.Replace(LDSCRIPT_PATH="buildroot/share/PlatformIO/ldscripts/fysetc_aio_ii.ld")`

3) Build using STM32103RC_Fysetc Env
4) Flash to Fysetc Cheetah

No display, presumably Marlin did not boot.

##Notes##

- It is interesting to note that the upload starting address is 0x08010000
- Even though it uploads to 0x08010000, Marlin without the special code runs fine, but will not detect and update the firmware.
- I did not enable #define SD_FIRMWARE_UPDATE because it says it is for ATMega 2560 ONLY.
- Configs are attached 
- Regular builds of Marlin upload and home perfectly with new bootloader

##Questions##

1) Was I supposed to #define SD_FIRMWARE_UPDATE anyway?
2) IS the filename supposed to be changed from **firmware.bin** to **old.bin** after a successful flash?

**Comment by sl1pkn07** [comment]
https://github.com/FYSETC/Bootloader-STM32F103/issues/3

**Comment by xC0000005** [comment]
I don't have a cheetah but the line setting the VECT_TAB_ADDR to 134217728 shouldn't be uncommented. The one that appends is fine, since the previous loop stripped off VECT_TAB_ADDR entries.

**Comment by ModMike** [comment]
There are a few more changes as well, a new pull request by Fysetc was [just merged](https://github.com/MarlinFirmware/Marlin/pull/18179/commits) 

Unfortunately my tool chain is messed up so I can't test. Been trying to fix it for a week.

**Comment by xC0000005** [comment]
Well, when you can build a binary, share it. I’ll drop it in binary ninja and see if it’s set for the right addresses. Most of those changes don’t look like they would fix it, unless the LD file wasn’t getting set.

**Comment by ModMike** [comment]
Will do. I am on OSX and mistakenly installed a few versions of Python that I can't seem to uninstall. It's totally messed up. 

I reinstalled on another Mac and it worked beautifully. What a pain.

**Comment by xC0000005** [comment]
Same - my primary macbook can’t even build anymore. I have another where I test PIO builds. Let me know if you figure out how to fix it.

**Comment by ModMike** [comment]
Type the following in terminal to list all your python install files:

ls -ls /usr/bin/python*

Many of them are system files and can't be removed. That being said, Apple is deprecating Python 2.7 and it supposedly removes the directory. Mine is still there.

If you reboot in safe mode you can disable SIP, boot, and then delete it.

**Comment by ModMike** [comment]
@xC0000005 

I fixed it and it was a lot of work, nearly 30 hours of hunting and piecing things together. I am not sure what is or is not necessary but this is what worked for me:

1) Go to your home folder and use Command + Shift + Period to unhide hidden files. You can check [this post](https://osxdaily.com/2018/02/12/show-hidden-files-mac-keyboard-shortcut/) if unsure how
2) Erase the hidden .platformio folder in your home folder
3) Open terminal and type in
`sudo pip3 uninstall platformio` 
You will probably get a message that it is not installed. The issue is that PIP can no longer install PlatformIO in 10.15.5, nor does it work with Python 2.7 (at least for me)
4) Use home-brew to install PlatformIO. If you don't have home-brew  you can install it by opening terminal and typing or copy pasting the following text
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`
5) In terminal type or paste the following to install PlatformIO
`brew install platformio`
6) open up VSCode and install the python extension from microsoft
7) When it finishes installing use Command + Shift + P to open the command palette
8) Type in "Python: select interpreter" and choose Python 3.7.3 for command line tools (both options should work)
9) Double check you work by opening the .platformio folder in your home holder by double clicking. You should not see anything relating to Python 2.7 or any version for that matter.
10) In VSCode preferences settings search for platformio-IDE and select the checkbox on Update Terminal Path Configuration (again, may not be needed)
11) Downlaod latest Marlin an compile as is to test.
12) If everything worked, go back into settings and look for Python: Python Path. You will probably see python in the field. add a 3 at the end so it reads "python3" to make sure it only uses python3

Good luck!

**Comment by xC0000005** [comment]
So, can you boot with the bootloader now?

**Comment by ModMike** [comment]
The pull request I referenced was merged but give me 10 minutes to try it. I was just so happy to fix VSCode.

**Comment by ModMike** [comment]
So it builds perfectly but when I flash it it I lose the screen. Will work on it tomorrow, need to sleep.

**Comment by xC0000005** [comment]
Zip up the bin and mail it to me at my github handle at gmail dot com. I’ll see if it’s at the right offset and setting the VTOR.

**Comment by ModMike** [comment]
Ok but I just did a quick test so I used the Ender 3 sample config, set the board and baud and that was it.

I uncommented all the code that was suggested at https://github.com/FYSETC/Bootloader-STM32F103

[firmware.bin.zip](https://github.com/MarlinFirmware/Marlin/files/4733991/firmware.bin.zip)

**Comment by ModMike** [comment]
I suspect I need to compile their boot loader and refalsh. It looks like they made a few changes in the last 2 weeks but the release version is 9 months old.

**Comment by xC0000005** [comment]
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/PlatformIO/scripts/STM32F103RC_fysetc.py#L35

Shouldn’t the offset be adjusted for the upload tool, to 0x8010000?  If you’ve been uploading from PIO, I think it’s been flashing to 0x8000000.

**Comment by ModMike** [comment]
No, it starts it at 0X801000 on m’y machine. I see it as it uploads.

**Comment by sl1pkn07** [comment]
now works for me. tested with AIOII board

~~~patch
diff --git a/buildroot/share/PlatformIO/scripts/STM32F103RC_fysetc.py b/buildroot/share/PlatformIO/scripts/STM32F103RC_fysetc.py
index a66c18a5e2..d46e8c77ed 100644
--- a/buildroot/share/PlatformIO/scripts/STM32F103RC_fysetc.py
+++ b/buildroot/share/PlatformIO/scripts/STM32F103RC_fysetc.py
@@ -4,17 +4,17 @@ from os.path import expandvars
 Import("env")
 
 # Relocate firmware from 0x08000000 to 0x08010000
-#for define in env['CPPDEFINES']:
-#    if define[0] == "VECT_TAB_ADDR":
-#        env['CPPDEFINES'].remove(define)
-#env['CPPDEFINES'].append(("VECT_TAB_ADDR", "0x08010000"))
+for define in env['CPPDEFINES']:
+   if define[0] == "VECT_TAB_ADDR":
+       env['CPPDEFINES'].remove(define)
+env['CPPDEFINES'].append(("VECT_TAB_ADDR", "0x08010000"))
 
-#custom_ld_script = os.path.abspath("buildroot/share/PlatformIO/ldscripts/fysetc_stm32f103rc.ld")
-#for i, flag in enumerate(env["LINKFLAGS"]):
-#    if "-Wl,-T" in flag:
-#        env["LINKFLAGS"][i] = "-Wl,-T" + custom_ld_script
-#    elif flag == "-T":
-#        env["LINKFLAGS"][i + 1] = custom_ld_script
+custom_ld_script = os.path.abspath("buildroot/share/PlatformIO/ldscripts/fysetc_stm32f103rc.ld")
+for i, flag in enumerate(env["LINKFLAGS"]):
+   if "-Wl,-T" in flag:
+       env["LINKFLAGS"][i] = "-Wl,-T" + custom_ld_script
+   elif flag == "-T":
+       env["LINKFLAGS"][i + 1] = custom_ld_script
 
 # Custom HEX from ELF
 env.AddPostAction(
~~~

for upload the bootloader https://raw.githubusercontent.com/FYSETC/Bootloader-STM32F103/master/OUTPUT/Bootloader-STM32F103.hex

~~~
"/home/sl1pkn07/.platformio/packages/tool-stm32duino/stm32flash/stm32flash" -v -i rts,-dtr,dtr -R -b 115200 -g 0x8000000 -w "Bootloader-STM32F103.hex" /dev/ttyUSB0
~~~

**Comment by ModMike** [comment]
Still doesn't work for me but I am probably overthinking it. This is what I did:

1) Flashed the board with the hex boot loader form the Fysetc Github
2) Wrote a regular version of Marlin
3) Uncommented the 2 sections in the newly merged Fysetc code in Marlin
4) Put Firmware.bin on sd card
5) Inserted card in SD slot with Machine powered off
6) Powered on Machine

And Nada.

Am I supposed to enable anything else?

**Comment by sl1pkn07** [comment]
step 2 and 3 should be swaped

1) burn the bootloader
2) uncoment the two sections
3) build the marlin
4) put the firmware.bin in the SD
5) poweroff or reset the machine

**Comment by ModMike** [comment]
I think my mistake was loading regular Marlin after I burnt the boot loader. I will re-burn and try.

**Comment by ModMike** [comment]
Worked perfectly! It was critical for me to get this to work because I used the 4 header pins to connect a Wemos Mini Pro to the 4 header pins on the front, which takes over the USB port. I didn't want a separate power switch to turn off the board.

Now I have a wireless printer with ESP3d-WebUI (an Octoprint like web interface). I didn't want to have to wire in a power switch every time I wanted to use the port to update. Last step is to see if I can do something about the file transfer speed. Hoping that new Binary mode is useful.

**Comment by ModMike** [comment]
So ran into another issue. When I fully configured my printer, I ran in to `.rodata' will not fit in region `rom'. Does the SD Flash code significantly reduce program? Never had issues before.

**Comment by xC0000005** [comment]
The bootloader cuts down on available space. How much did it overflow by?

**Comment by ModMike** [comment]
8764 bytes

**Comment by ModMike** [comment]
I thought I saw somewhere that the BTT STM32 is actually 512K and you needed to build for that size. Any chance that is true for Cheetah?

**Comment by sl1pkn07** [comment]
not true at all, some btt smt32 have RET6 chips, which have real 512K. the RCT6 chip, like Cheetahs, have 256K. but some RCT6 chips is a RET6 with some sectors damaged or not pass the fabrication/quality checks, and renamed as RCT6. so you need use with carefull. i personal recomend use the certified size for this chips. 256K

greetings

**Comment by ModMike** [comment]
Whats the worst that can happen? Reinstall the boot loader? Lets hope their yields improved. Should I try this: 512K - 64K or be more conservative, say 320 - 64?

**Comment by sl1pkn07** [comment]
you can try use the BTT E3/DIP or MKS (E3/E3D) botloader and cross the fingers. btt starts the firmware in 0x08007000 and MKS E3/E3D in 0x08006000 (this last needs a "encrypted" firmware)

greetings

**Comment by ModMike** [comment]
I used 320k and lost my LCD menus. Do you think they are hardwired to 256K or have you heard of  so I guess it's physically locked at 256K or its just a config thing? Should I have used 512K?

**Comment by xC0000005** [comment]
64k is a hell of a lot of space for a bootloader. I’d be tempted to either use openblt or recompile the existing one for something that’s not ridiculously large. If all it’s providing is IAP, malyan’s does it in 8k (and so does the open bootloader). Is this thing doing anything else useful?

**Comment by sl1pkn07** [comment]
nothing more flash the firmware and start it

i'm interest in you say @xC0000005 , because i've make a botloader for my BTT E3 DIP with genuine RET6 chip (512K), but not works like i want (only flash the first time, but not when reflash when update the firmware.bin)

greetings

**Comment by xC0000005** [comment]
If you want to use the existing one, the offset is just a #define. Make sure it’s a multiple of the sector size and larger than the .bin and you can recompile the bootloader for that (then adjust Marlin’s offset in the script the same way). But again, I have to wonder what this provides over OpenBLT.

**Comment by sl1pkn07** [comment]
with "existing one" you mean the Malyan? link plox?

greetings

**Comment by xC0000005** [comment]
No, just recompile the fytsec one and change the #define for the offset. It should be a multiple of whatever the board’s sector size is, and larger than the binary for your bootloader. So if the bootloader .bin is 6k and you have 4k pages, an 8k offset would work.

**Comment by sl1pkn07** [comment]
how build the fysetc bootloader? with what toolchain/platform/IDE?

greetings

**Comment by ModMike** [comment]
> how build the fysetc bootloader? with what toolchain/platform/IDE?
> 
> greetings

No. They it's in Keil project format and their Ultravision is a commercial product. There is a free one but I am not sure what if it's enough. Keil is very popular STM32 developers because of their powerful debugging tools.

**Comment by ModMike** [comment]
> No, just recompile the fytsec one and change the #define for the offset. It should be a multiple of whatever the board’s sector size is, and larger than the binary for your bootloader. So if the bootloader .bin is 6k and you have 4k pages, an 8k offset would work.
> […](#)

The size of the .hex is 64K but it looks like it is 30K after compile and upload. See the 3rd to last line in bold. Is this correct?

Also how do I confirm sector size? If I use your method that means the new offset would be 256K - 32? The old one was 40k. Not really sure what the offset is.

SRAM size:65535KB(For reference only!!!)
Start Erase Chip,There will be a long time to Erase,wait please!
FULL chip erase Ok!!!
DTR be Low(-3--12V),Reset
RTS be High(+3-+12V),enter ISP
...Delay 100ms
DTR be High(+3-+12V),Reset Released
RTS keep High
Connectting...4, Received:79 1F 
Connect Ok @COM7@115200bps,@594ms
BootLoader Version:2.2
PID:00000414  STM32F10xxx_High-density
OptionBytes readout:
A55AFF00FF00FF00FF00FF00FF00FF00
96bit unique device ID:
[37FFD6055359383137571751]
[05D6FF37 31385953 51175737]
FLASH ROM size:256KB
SRAM size:65535KB(For reference only!!!)
@672ms,Ready for Program
**Write 30KB Ok,100%,@17266ms**
Go from 08000000 Ok
www.mcuisp.com(Versatile Handy Programmer EP968,World's first):Mission Complete,Anything Ok!!!

**Comment by ModMike** [comment]
> No, just recompile the fytsec one and change the #define for the offset. It should be a multiple of whatever the board’s sector size is, and larger than the binary for your bootloader. So if the bootloader .bin is 6k and you have 4k pages, an 8k offset would work.
> […](#)

How do I confirm sector size?

**Comment by ModMike** [comment]
> If you want to use the existing one, the offset is just a #define. Make sure it’s a multiple of the sector size and larger than the .bin and you can recompile the bootloader for that (then adjust Marlin’s offset in the script the same way). But again, I have to wonder what this provides over OpenBLT.
> […](#)

Looking at OpenBLT. The advantage for Fysetc building their own boot loader is that they don't have to pay for it. OpenBLT does have a commercial license but not sure if that means Fysetc would have to pay. Luckily it's free for non-commercial.

**Comment by ModMike** [comment]
I believe it has 2k pages according to the source code. From the flash.h file:

#define FLASH_PAGE_SIZE             ( 0x800 )

![Screen Shot 2020-06-05 at 6 10 41 PM](https://user-images.githubusercontent.com/36581178/83926487-ed182f80-a757-11ea-9ba0-d63a7bfa17f8.png)

**Comment by ModMike** [comment]
@xC0000005

> No, just recompile the fytsec one and change the #define for the offset. It should be a multiple of whatever the board’s sector size is, and larger than the binary for your bootloader. So if the bootloader .bin is 6k and you have 4k pages, an 8k offset would work.
> […](#)

Apparently all we need to change in the fysetc bootloader is:

**Bootloader-STM32F103/CODE/APP/bootloaders.h change**
#define BOOTLOADER_FLASH_ADDR ( 0x08010000 )
to
#define BOOTLOADER_FLASH_ADDR ( 0x08007000 )

I tried to install the free version of Keil but the project is in 4.0. I found a version and tried to install but keep getting a tool chain error. Do you have Keil installed?

**Comment by ModMike** [comment]
Project update:

I installed the latest [MDK-ARM version of Keil uVision](https://www.keil.com/demo/eval/arm.htm). You will need to register but the license is free for uploads under 32K which was perfect for this project. 

A few notes:

1) When starting Keil, you will have a device not found or similar error, ignore it
2) You will be told this is a legacy project, choose option 1 to bring it into Keils new format
3) Close the project and then Keil
4) Restart Keil and reload the project, it should load with no errors.
5) Make the changes to the boot loader and Marlin as referenced in the [Fysetc github readme](https://github.com/FYSETC/Bootloader-STM32F103)
6) I used the Fysetc upload tool as referenced in their Github
7) Make the changes to Marlin (I will submit a pull request so this may not be necessary, depending on when it is merged)
8) The good news is that the bootloader occupies half it's original 64k space at only 32K of reserved space.

Below is the bootloader that I compiled with the change. Note that I believe you can only install Marlin firmware by SD card after you install it, I don't think the USB method works anymore, at least in my limited testing. Let me know your experiences.

To Install new Marlin firmware

1) Compile as usual
2) Navigate to Marlin-bugfix-2.0.x\.pio\build\STM32F103RC_fysetc (or whatever directory name you gave it). In OS X this directory is hidden so press SHIFT+COMMAND+PERIOD at the same time to reveal hidden files.
3) Copy the firmware.bin file to the root of your sd card
4) Insert the card in your printer and turn it on
5) A blank screen will come up, wait 30 seconds and power cycle the machine
6) Congrats, yous just did an update using the SD card!

If it doesn't work, check the sd card to make sure the firmware.bin file was re-named to old.bin.

[Bootloader-STM32F103.zip](https://github.com/MarlinFirmware/Marlin/files/4752502/Bootloader-STM32F103.zip)
