### ISSUE TITLE
[FR] Setting EXTRUDERS to 0 should remove the "Preheat PLA/ABS Conf" from LCD Advanced menu

### ISSUE THREAD

**Issue by gminadak** [MarlinFirmware/Marlin#18173]
### Description

When setting the EXTRUDERS to 0 the "Preheat PLA/ABS Conf" menu on LCD "Advance" menu should be removed and the "Temperature" from main Menu.

### Feature Workflow

1. #define EXTRUDERS 0

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by gminadak** [comment]
@boelle I figured out that the menu appears because of the fan and not the extruder (pictures included).
Well maybe for particular setups this makes sense to have a controllable fan but not extruder (laser etc).
But i think it only needs to be in one menu or have an option to complete disable the fans from the screen for other setups.

[ config.zip](https://github.com/MarlinFirmware/Marlin/files/4822291/config.zip)

![IMG_20200624_011233](https://user-images.githubusercontent.com/45330594/85472627-c57bf080-b5ba-11ea-82f9-6e09ea1fc66b.jpg)
![IMG_20200624_011241](https://user-images.githubusercontent.com/45330594/85472635-c7de4a80-b5ba-11ea-94c3-f3220d2f92bd.jpg)
![IMG_20200624_011254](https://user-images.githubusercontent.com/45330594/85472636-c876e100-b5ba-11ea-9af0-46c9bf2c20aa.jpg)
![IMG_20200624_011305](https://user-images.githubusercontent.com/45330594/85472638-c876e100-b5ba-11ea-89ef-e850b8858038.jpg)
![IMG_20200624_011458](https://user-images.githubusercontent.com/45330594/85472639-c90f7780-b5ba-11ea-93ae-463ad59a0cbb.jpg)

Thank you.

**Comment by thinkyhead** [comment]
Apologies for the completely inappropriate reply and label. This is a bug and I am working on it now.

**Comment by gminadak** [comment]
Probably you already know this but after the last commits

`Compiling .pio\build\LPC1768\src\src\module\stepper.cpp.o
Compiling .pio\build\LPC1768\src\src\module\stepper\L64xx.cpp.o
Marlin\src\lcd\ultralcd.cpp:90:3: error: 'preheat_t' does not name a type
   90 |   preheat_t MarlinUI::material_preset[PREHEAT_COUNT];  // Initialized by settings.load()
      |   ^~~~~~~~~
*** [.pio\build\LPC1768\src\src\lcd\ultralcd.cpp.o] Error 1`

**Comment by gminadak** [comment]
With the latest commit (9013580) everything is ok as you can see from the pictures.
The fan still appears on the status screen but maybe this is from my configuration/board/pins.

I'm closing this.

Thank you.

![IMG_20200626_134736](https://user-images.githubusercontent.com/45330594/85850606-cd53b480-b7b5-11ea-91c7-bd547f21723d.jpg)
![IMG_20200626_134900](https://user-images.githubusercontent.com/45330594/85850616-d2b0ff00-b7b5-11ea-9983-f0913c9b99f5.jpg)
![IMG_20200626_134909](https://user-images.githubusercontent.com/45330594/85850628-d6448600-b7b5-11ea-94d6-bb2ab1f47da7.jpg)
