### ISSUE TITLE
[BUG] MKS MINI 12864 + SKR 1.3 - all black pixels from time to time.

### ISSUE THREAD

**Issue by Pajacyk0v** [MarlinFirmware/Marlin#18180]
### Bug Description

From time to time my MKS MINI 12864 goes black. I mean all pixels on screen are black. Print form SD card continues, no reaction for encoder. LCD returns to normal operation after some time. Boot screen always appear, no issues with contrast.

Same behavior has been reported here https://github.com/MarlinFirmware/Marlin/issues/13550#issuecomment-544490824

### My Configurations

Marlin 2.0.5.3 

#define MKS_MINI_12864
#define SDSUPPORT
Rest of LCD section settings are defaults.

### Steps to Reproduce

It occurs randomly. During print or not.

#### Additional Information

![ekran](https://user-images.githubusercontent.com/43875157/83514540-20e32300-a4d4-11ea-96fd-f2f457d894ce.JPG)

Mainboard BTT SRK 1.3

**Comment by Parkrcz** [comment]
Hi, I have same issue here. First I got this problem on SKR_1.3 + Marlin 2.0.x and now with SKR_1.4_Turbo + Marlin 2.0.5.3. I tried a few workarounds but non of them worked. Hope anybody can help us......

**Comment by Parkrcz** [comment]
What I have found in my case are basically two type of glitches. First = all black pixels(only restart works), and second =  empty screen (kind of "all white pixels"). To get rid of second one, removing SD card works. Once I remove SD card from MKS_Mini_12864 v2 panel, "all white pixels" glitch is gone.

**Comment by Pajacyk0v** [comment]
> What I have found in my case are basically two type of glitches. First = all black pixels(only restart works), and second = empty screen (kind of "all white pixels"). To get rid of second one, removing SD card works. Once I remove SD card from MKS_Mini_12864 v2 panel, "all white pixels" glitch is gone.

I have same issues.

**Comment by boelle** [comment]
@Pajacyk0v 
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

**Comment by Parkrcz** [comment]
Hello, yesterday I compiled the latest bugfix-2.0.x branch, but glitches are still present.

**Comment by ils15** [comment]
same problem here

**Comment by sjasonsmith** [comment]
Can one or more of you attach your configuration files which reproduce this issue?

Also, are there any ideas to make this reproduce easily, or just power-on and wait?

**Comment by gerleimarci** [comment]
Same issue here with the latest bugfix-2.0.x
It produces various glitches and gives freezed blank display during SD read.
I tried `#define FORCE_SOFT_SPI` but it just make things worse. With this option the display freezes at the moment I plug in the SD card.

MKS Robin E3D
CR20 display (Basically a MKS MINI12864 without SD socket)

The display uses the same SPI pins as the onboard SD card reader.

```
#define DOGLCD_SCK                      PB13
#define DOGLCD_MOSI                     PB15

#define SCK_PIN                             PB13
#define MOSI_PIN                            PB15```

**Comment by anomalchik** [comment]
MKS_SGEN_L (LPC1768) with MKS MINI12864 have same issue too

**Comment by anomalchik** [comment]
> Can one or more of you attach your configuration files which reproduce this issue?
> 
> Also, are there any ideas to make this reproduce easily, or just power-on and wait?

Choose file from sdcard and wait...

It also breaks read from sdcard in printing state. i choose big gcode file (12mb) with infill 100% and i get constant execution of the same buffer of code (~ after 2 hours / 10). 
Same gcode file print succeful through serial port. 
I tried to change sdcard from onboard to lcd but it didn't fix the situation. 
Small files can be printed without problems. 
![IMG_20200727_110351](https://user-images.githubusercontent.com/3417567/88561171-bc59c580-d037-11ea-97c6-5f1fe1e1680a.jpg)

**Comment by anomalchik** [comment]
My config (for bugfix-2.0.x branch) https://drive.google.com/file/d/17ZGIfQ7rwg7q7aJQr0mfHvPpLTpVBg2Y/view?usp=sharing
also after the card is inserted it can cause slight distortion of fonts at the location of the selection bar

**Comment by leftover** [comment]
Same here. SKR 1.3 + TMC2209 + MKS MINI 12864 V1.0. 
Actually there are 2 types of glitch: "black screen" and "white screen". Both happen randomly. White screen disappears with knob turn while black one can be "fixed" with reset only.
In "Black Square" state i managed to navigate menus blindly and call "Auto Home", so it is just screen issue.
My current configs: [Marlin_cfgs.zip](https://github.com/MarlinFirmware/Marlin/files/5080178/Marlin_cfgs.zip)

**Comment by Pajacyk0v** [comment]
I had same issue on 2.0.6.1 :(

**Comment by Pajacyk0v** [comment]
In 2.0.7 problem still exists.
