### ISSUE TITLE
Selectng Improve Homing Reliability disables all steppers

### ISSUE THREAD

**Issue by Crunch69** [MarlinFirmware/Marlin#18182]
**Bug Description**
Selecting Improve Homing Reliability disables all steppers

**My Configurations**
Marlin 2.0.x bugfix
SKR 1.3 TMC2209 Sensor less Homing
[HOMING_RELIABILITYConfiguration.zip](https://github.com/MarlinFirmware/Marlin/files/4720043/HOMING_RELIABILITYConfiguration.zip)
**Steps to Reproduce**
Uncomment #define Improve Homing reliability

**Expected behavior**:
Tuning of acceleration and jerk when homing and add a guard period for end stop triggering.

**Actual behavior:**
All steppers lock and will not run.

**Comment by boelle** [comment]
@Crunch69 still an issue?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
