### ISSUE TITLE
[BUG] (short description) marlin, ramps,tmc2208

### ISSUE THREAD

**Issue by Smarty4life** [MarlinFirmware/Marlin#18198]
Upload onto ramps only works with tmc2208 in standalone( tmc2208_standalone)
I get a error compiling with maga2560 message when just tmc2208

Using uart ramps guide from instructables

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ellensp** [comment]
no error logs, no config files.  Compile fine with just setting TMC2208 on X,Y,Z E0 and E1 in my test.
Please look up the definition of "Required" and attach your config files as requested.
