### ISSUE TITLE
[BUG] M122 results in TMC connection error

### ISSUE THREAD

**Issue by rc-fire** [MarlinFirmware/Marlin#18199]
### Bug Description

Using a SKR Mini E3 1.2 with an Cr-20 Pro (Ender 3 like) with Marlin 2.0.5.3:

When using M122 during a print after a few trys the printer will return outputs like "Recv: Testing X connection... Error: All LOW" or for the registers "Recv: 		X	0x00:00:00:00	 Bad response!" which might happen for a random combination of all steppers. The printer LCD will show "TMC connection error" until the end of the print. No other consequences have been observed. 

When the printer is not moving M122 works 100% fine without bad output.

### My Configurations

[config.zip](https://github.com/MarlinFirmware/Marlin/files/4730502/config.zip)

### Steps to Reproduce

1. Start a print
2. Use M122 until bad return occurs

**Expected behavior:** 

M122 does either work during a print or give at least some hint (in return or documentation) that it might not be used during a print.

**Actual behavior:** 

Printer giving bad returns and showing "TMC connection error" while everything is fine. The error is caused alone by M122.

**Comment by sjasonsmith** [comment]
This is most likely an interrupt priority issue, causing unreliable communication when using SoftwareSerial on boards using the STM32F1 HAL.

In the STM32 HAL used by some other boards we specifically increased the SoftwareSerial interrupt priority to avoid this. There we set the serial interrupt to a very high priority, and the TEMP (probably the longest running interrupt) interrupt to a very low priority.

On STM32F1 this is not done, with the TEMP interrupt at a high priority just behind the STEP interrupt, and the SoftwareSerialM interrupt probably at some default priority (I have no idea what that is).

, but I noticed the other day that doesn't happen for STM32F1.
