### ISSUE TITLE
[BUG] SKR 1.4 Turbo + TMC2209 Enable not working

### ISSUE THREAD

**Issue by statiealexandru** [MarlinFirmware/Marlin#18206]
### Bug Description

TMC2209 Drivers do not get enabled on SKR 1.4 Turbo board.

Tried different alternatives of X_ENABLE_ON, the enable pin voltage remains 3.3 and M122 returns enabled false, even after running M17.

The steppers simply do not move, although the drivers are registered fine in UART mode.

Driver registers:
		X	0x80:0C:00:C0
		Y	0xC0:0C:00:00
		Z	0xC0:0C:00:00
		E	0xC0:0C:00:00
Testing X connection... OK
Testing Y connection... OK
Testing Z connection... OK
Testing E connection... OK

### My Configurations

[bug.zip](https://github.com/MarlinFirmware/Marlin/files/4736810/bug.zip)

### Steps to Reproduce

1. Power on printer - 12v PS
2. Connect to printer - USB
3. M17
4. G1 X100 F500
5. Motors not moving...

**Expected behavior:** [What you expect to happen]

Motors should move

**Actual behavior:** [What actually happens]

Motors are not moving and drivers do not get enabled. The Enable pin tension remains 3.3v. Drivers work in Standalone mode (although very noisy)

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ellensp** [comment]
You have disabled the dedicated enabled pins. 
Please read the following and disable it in your Configuration_adv.h

```
/**
   * Software enable
   *
   * Use for drivers that do not use a dedicated enable pin, but rather handle the same
   * function through a communication line such as SPI or UART.
   */
  #define SOFTWARE_DRIVER_ENABLE
```

**Comment by statiealexandru** [comment]
Thank you!

the UART in the SOFTWARE_DRIVER_ENABLE description let me to believe that was the right config.

I can’t test the change since i’ve managed to fry the board in the meantime by messing around, but i will once the new board is delivered.

Marking this as closed, thank you!!
