### ISSUE TITLE
dual z drivers fails to compile

### ISSUE THREAD

**Issue by ntoff** [MarlinFirmware/Marlin#1820]
Latest dev version downloaded a minute ago, test compile without changing anything and it works, uncomment out `#define Z_DUAL_STEPPER_DRIVERS` to use dual drivers for Z axis throws a bunch of errors

http://pastebin.com/Maj5qbT8 the errors

**Comment by thinkyhead** [comment]
@ntoff Are Z2 min and max endstops both required for this feature?

**Comment by boelle** [comment]
only one endstep at each side should be required... 

for my own mendel90 i would use 1 max endstop to tell the machine the overall height... and 2 min endstops to level X carriage so its parallel with the bed...

for normal printers 2 min endstops should make do

**Comment by alexborro** [comment]
I don't know WHY someone changed that.. my original implementation is:

static bool old_x_min_endstop = false,
            old_x_max_endstop = false,
            old_y_min_endstop = false,
            old_y_max_endstop = false,
            old_z_min_endstop = false,
            #ifndef Z_DUAL_ENDSTOPS
              old_z_max_endstop = false;
            #else
              old_z_max_endstop = false,
              old_z2_min_endstop = false,
              old_z2_max_endstop = false;
            #endif

Once Z_DUAL_ENDSTOPS is defined, both old_z2_min_endstop and
old_z2_max_endstop are declared.
These variables declaration do not depend on one or two endstops, the code
take care of it.

Cheers.

Alex.

2015-04-05 5:41 GMT-03:00 Bo Herrmannsen notifications@github.com:

> only one endstep at each side should be required...
> 
> for my own mendel90 i would use 1 max endstop to tell the machine the
> overall height... and 2 min endstops to level X carriage so its parallel
> with the bed...
> 
> for normal printers 2 min endstops should make do
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/1820#issuecomment-89735833
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by ntoff** [comment]
@thinkyhead no idea, all I know is I used to use dual Z drivers in a previous version because 1 driver can't drive both my Z motors, enabled it in the latest dev version on the printer I'm building (building one just to test dev version of marlin because I love you so much) and it failed. If you comment out the dual Z end stops then it compiles ok, with both drivers still enabled.

commenting out the dual z endstops thing fixes it but isn't that what the whole dual endstops was for? to even out the homing of dual z drivers automatically?

**Comment by thinkyhead** [comment]
#1827

**Comment by ntoff** [comment]
will test tonight. currently chopping down bushes and avoiding spiders

**Comment by boelle** [comment]
how did the test turn out?

**Comment by thinkyhead** [comment]
It compiles and optimizes away unused stuff, I presume.

**Comment by ntoff** [comment]
> how did the test turn out?

Dunno, was waiting on plugs for the end stop switches. I was going to wire it up without them but now I have all the necessary bits I can continue building the test printer. This way I can upload random firmware willy nilly and not have to worry about whether or not it destroys the printer in some spectacular fashion.

**Comment by thinkyhead** [comment]
@ntoff Apologies in advance. Please record disasters in progress on video.

**Comment by ntoff** [comment]
well the home made hot end didn't set itself on fire, so that's a good start http://imgur.com/9lo6mz9
