### ISSUE TITLE
[BUG] Turn off automatic return from the menu to the status screen

### ISSUE THREAD

**Issue by radek8** [MarlinFirmware/Marlin#18205]
By disabling the option
#define LCD_TIMEOUT_TO_STATUS
it does not turn off the return from the menu to the status screen, but the default value of 15s is used.
I would expect that disabling this option will turn off automatic return from the menu to the status screen.

When using the TFT display, there is a problem when using the encoder in touch mode. Turning off automatic return from the menu to the status screen would partially solve this.
see:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/757

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/680

**Comment by Lord-Quake** [comment]
The default when disabled it 15 seconds.
Activate the option and set to x seconds for a different delay to menu.

**Comment by radek8** [comment]
I don't want another delay, I want to turn off this feature.
I expected disabling this option to turn off the status screen return feature, but it's not.
When I select 0 or-1, the function is deactivated?

**Comment by Lord-Quake** [comment]
> When I select 0 or-1, the function is deactivated?

Well, have you tried it?

**Comment by radek8** [comment]
Thanks for inspiration
Option -1 works as I need it.
#define LCD_TIMEOUT_TO_STATUS -1
