### ISSUE TITLE
[BUG] (Autostart sd ? files auto0.g, auto1.g)

### ISSUE THREAD

**Issue by Anion-anion** [MarlinFirmware/Marlin#18218]
HELLO!
Autostart from a sd card works strange for me. If one auto0.g file is recorded, then everything works. If 2 files auto0.g and auto1.g in this case, only auto1.g starts. If 3 files auto0.g, auto1.g, auto2.g are written, nothing starts up, freezes, the screen says auto0.g, but nothing going on. What could be the mistake? Where to see? (skr 1.3)

**Comment by boelle** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
