### ISSUE TITLE
HELP! Need help with marlin code to hook up REPRAP discount full graphic smart controller to stock Ender 3 motherboard

### ISSUE THREAD

**Issue by Wiketti** [MarlinFirmware/Marlin#18225]
Cant seem to get any graphics out of it.

I have added u8glib library to firmware and uncommented reprap discount full graphic smart controller from the code. Also commented ( // ) the CR-10 stock display from firmware.

It just shines blue and "whines".

**Comment by ellensp** [comment]
This is mostly a hardware issue
2 * 10 pin plugs into 1 * 10 socket..   you can't have everything. 

the reprap discount full graphics display has 
encoder (3 pins) 
buzzer (1 pin)
12864 lcd (3 pins)   
sd card  (5 additional pins) 
stop button (1 pin)
power  (2 pins)

So 15 pins pins going to a 10 pin plug?
This is why the CR-10 display doesn't have sdcard.

**Comment by Wiketti** [comment]
Can i modify one connector so that it matches ender's own pins without SD reader?

**Comment by ellensp** [comment]
you have   (pins numbers are reversed on some boards)  (updated)
Connectors on back of RRD GLCD
```
 *               _____                                        _____
 *           NC | 1 2 | GND                               5V | 1 2 | GND
 *        RESET | 3 4 | SD_DETECT                     LCD_D7 | 3 4 | LCD_D6
 *         SD 2 | 5 6   BTN_EN2                       LCD_D5 | 5 6   LCD_D4
 *         SD 1 | 7 8 | BTN_EN1                       LCD_RS | 7 8 | LCD_EN
 *         SD 5 | 9 10| SD 7                         BTN_ENC | 9 10| BEEPER
 *               -----                                        -----
 *               EXP2                                          EXP1
```

you need to use these pins  (marked with a X) 

```
 *               _____                                        _____
 *           NC | 1 2 | GND                               5V | X X | GND
 *        RESET | X 4 | SD_DETECT                     LCD_D7 | 3 4 | LCD_D6
 *         SD 2 | 5 X   BTN_EN2                       LCD_D5 | 5 X   LCD_D4
 *         SD 1 | 7 X | BTN_EN1                       LCD_RS | X X | LCD_EN
 *         SD 5 | 9 10| SD 7                         BTN_ENC | X X | BEEPER
 *               -----                                        -----
 *               EXP2                                          EXP1
```

Everything with a X need to go to your 10 pin connector.
I have no idea on the wiring of that connector. but  MOSI, SCK and power pins cannot be moved to other pins.

**Comment by Wiketti** [comment]
I'll give it a go soon as i get home. Thank you for the replys.

I'll get back to you as soon as i get some results.

**Comment by ellensp** [comment]
From circuit diagrams I found https://github.com/Creality3DPrinting/CR10-Melzi-1.1.2/blob/master/Circuit%20diagram/Motherboard/CR-10%20Schematic.pdf

It looks like the EXP1 connector is as follows

```
/*  EXP1 Connector
 *                   _____
 *               5V | 1 2 | PC1 EXT-SDA
 *       EXT-A1 PA1 | 3 4 | RESET
 *      EXT-SCL PC0 | 5 6   PA4 EXT-A4
 *      EXT-TX1 PD3 | 7 8 | PD2 EXT-RX1
 *       EXT-A3 PA3 | 9 10| GND
 *                   -----
 */

/*  EXP1 Connector when used as CR-10 LCD
 *                   _____
 *               5V | 1 2 | DATA
 *              CLK | 3 4 | RESET
 *          BTN_ENC | 5 6   BEEPER_PIN
 *          BTN_EN1 | 7 8 | BTN_EN2
 *               CS | 9 10| GND
 *                   -----
 */
```

**Comment by ellensp** [comment]
This seems to be the connector on your controller.  (please verify) 

```
/*   EXP1 Connector       As CR10 LCD Connector
 *        _____                                   _____
 *   PA4 | 6 5 | PC0                  BEEPER_PIN | 6 5 | BTN_ENC
 *   PD3 | 7 4 | RESET                   BTN_EN1 | 7 4 | RESET
 *   PD2   8 3 | PA1                     BTN_EN2   8 3 | LCD_PINS_D4 (ST9720 CLK)
 *   PA3 | 9 2 | PC1     (ST9720 CS) LCD_PINS_RS | 9 2 | LCD_PINS_ENABLE (ST9720 DAT)
 *   GND |10 1 | 5V                          GND |10 1 | 5V
 *        -----                                   -----
 */
```

So if you wire to these pins and set Configuration.h LCD as a CR10_STOCKDISPLAY and cross your fingers and toes...  you might get a display and working encoder, reset and buzzer.

**Comment by ellensp** [comment]
Re check previous posts, I have updated the pins a bunch

**Comment by thisiskeithb** [comment]
This isn't a Marlin bug and really should be posted elsewhere as noted in the pinned "[Need to ask a question?](https://github.com/MarlinFirmware/Marlin/issues/14694)" issue, but someone has mapped out the pins & created a custom cable for a full graphic LCD on an SKR Mini E3 which uses the same EXP3/connector for a `CR10_STOCKDISPLAY`: https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues/159

![image](https://user-images.githubusercontent.com/13375512/84106722-b9940a00-a9d0-11ea-808e-b5ee8434922b.png)

**Comment by Wiketti** [comment]
Took me ages yesterday to make that 10 pin cable 😂  as i dont have the right crimping tool. So gonna give it a go today. 

At first i just assumed it was marlin prob... 🙄 So sry to post this on wrong channel. Altho, i am super gratefull for all the help! You guys are the best!
I think i will be asking more help in near future as i'm fairly new to all this.

I'll let you know how this turns out soon 😊👌

**Comment by ellensp** [comment]
I would have used a bunch of singe wire DuPont cables. same as you get with arduino boards and modules, then you can easily change things. Only make up a cable when you know its going to work.

**Comment by Wiketti** [comment]
They did'nt have those single duponts (or the single connectors) in the local shop 🙄 so i had to make the cable on my own. Really need to order some for future. Those arduino boards keep piling up and i dont have decent tools to go with them 😑

**Comment by Wiketti** [comment]
Okay, got those single duponts after some digging and a lot of driving 😅
Hooked the screen up like shown above (also tried reversed).

It just flickers and lights up but nothing else.

**Comment by Wiketti** [comment]
Can i link a video?

**Comment by ellensp** [comment]
yes and images... on how you wired it, and confirm you set CR10_STOCKDISPLAY and disabled reprap discount full graphic smart controller

**Comment by ellensp** [comment]
also do you have a multimeter...  so you can confirm which pins are gnd and 5v on both ends

**Comment by Wiketti** [comment]
![IMG_20200610_122932](https://user-images.githubusercontent.com/63800383/84251583-3b418000-ab16-11ea-9ccb-d7b50beaf9b5.jpg)
![IMG_20200610_122939](https://user-images.githubusercontent.com/63800383/84251587-3c72ad00-ab16-11ea-9439-3bc5a6ce3003.jpg)
![Uploading IMG_20200610_122958.jpg…]()

**Comment by Wiketti** [comment]
![IMG_20200610_122958](https://user-images.githubusercontent.com/63800383/84251666-58764e80-ab16-11ea-93ef-5c968f774673.jpg)

**Comment by Wiketti** [comment]
do i need  to install some firmware into the screen?

**Comment by ellensp** [comment]
This https://github.com/Creality3DPrinting/Ender-3/blob/master/Ender-3%20PCB/Ender3_pcb_parts.PDF tells me that the controller is not wired correct, gnd and 5v are at other end. gnd on the inside 5v on the outside 

try my pins
```
/*   EXP1 Connector       As CR10 LCD Connector
 *        _____                                   _____
 *   PA4 | 6 5 | PC0                  BEEPER_PIN | 6 5 | BTN_ENC
 *   PD3 | 7 4 | RESET                   BTN_EN1 | 7 4 | RESET
 *   PD2   8 3 | PA1                     BTN_EN2   8 3 | LCD_PINS_D4 (ST9720 CLK)
 *   PA3 | 9 2 | PC1     (ST9720 CS) LCD_PINS_RS | 9 2 | LCD_PINS_ENABLE (ST9720 DAT)
 *   GND |10 1 | 5V                          GND |10 1 | 5V
 *        -----                                   -----
 */
```

no there is no firmware on the display. its a dumb device.
firmware on the controller.

**Comment by ellensp** [comment]
to simply things you don't need exp2 on lcd at all just yet. It is for encoder and reset pins. So you can remove those for now if you wish...

**Comment by Wiketti** [comment]
> to simply things you don't need exp2 on lcd at all just yet. It is for encoder and reset pins. So you can remove those for now if you wish...

Thanks a ton! 😎👌 Really got it working 😅 took ages, but with your help i have some light in the end of the tunnel
![IMG_20200610_152907](https://user-images.githubusercontent.com/63800383/84267933-9338b080-ab2f-11ea-9959-0518b9e56dbd.jpg)
![IMG_20200610_152903](https://user-images.githubusercontent.com/63800383/84267948-9895fb00-ab2f-11ea-99d9-3595c0be6848.jpg)

Only thing that's haywire are those X,Y,Z thing going to ?,?,? From X,Y,Z

**Comment by ellensp** [comment]
That's normal marlin, its telling you that you haven't homed the axis yet.

**Comment by Wiketti** [comment]
I´ll make decent wiring pictures and share them somewhere.(???? dont know where yet)
If someone ever would need them. Almost all controls work as they should, except extruder, cant seem to control it from prepare menu.

but i dont really care as long as i have it running now. need to do some tests before i give it thumbs up, but so far so good.

**Comment by ellensp** [comment]
extruder needs to be hot before it will consider moving.

**Comment by Wiketti** [comment]
of course it does... silly me.

should had emmidiatly follow your guides. the pic Keith posted was not correct.

**Comment by Wiketti** [comment]
![IMG-20200610-WA0008](https://user-images.githubusercontent.com/63800383/84272269-deee5880-ab35-11ea-8495-e9b4bb270ed8.jpeg)
Rough sketch but will make it better soon.

**Comment by thisiskeithb** [comment]
Some of those reprap full graphic LCDs have EXP connectors that are 180 out from standard. Glad you got it working.

Since this isn’t a Marlin bug, please close the issue.
