### ISSUE TITLE
Unable to pause or stop print from LCD when printing tethered (with octoprint)

### ISSUE THREAD

**Issue by Koyodee** [MarlinFirmware/Marlin#18233]
When printing with OctoPrint, I am unable to either use a M601 to pause my print or pause it from the LCD Screen. Both the Pause Print and Stop Print buttons don't do anything to the print in progress, yet on the LCD, it shows that the print is stopped, and shows the usual menu when the printer is idle. This means that if a print is failing, the only way I'm able to stop it is by power cycling, or by launching octoprint in order to stop the print from there.

**Comment by thisiskeithb** [comment]
You didn’t include your configs like the issue template asked, but you should enable `HOST_ACTION_COMMANDS` and `HOST_PROMPT_SUPPORT`.

**Comment by Koyodee** [comment]
Sorry about that. What you suggested worked great, thank you!!
