### ISSUE TITLE
[FR] Secondary Serial Output for LCD Display

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#18231]
Description: 

The USB output on my SKR1.3 board provides a serial output viewable via Octopi or many other devices.  I would like to have the second serial output of the terminal information at a lower baud rate (9600) and 5v level to feed into an Arduino for display on my printers stock 20 X 4 display.

Feature Workflow:

1. select something like this in configuration_adv.h: 
```
#if ENABLED (SERIAL_PORT_2)
  #define SERIAL_PORT_2_Baud 9600
#endif
```
2. program Arduino for serial in at 9600 baud and LCD out and wire (easy)
3. view serial data stream at the printer

Additional Information:  I have added an SKR1.3 board to my Anet A8.  This leaves the existing Anet 2004 LCD display unused.  I could hook an Arduino to it to measure voltage, ambient temperature, etc, but the serial data stream would be much more useful.

**Comment by borland1** [comment]
There is a g-code M575 supported by Marlin 2.0.x that can set the baud rate for the secondary serial.  Custom g-code can be initiated with Startup commands found in `Configuration_adv.h` file. Look for....

```
 * Startup commands
 *
 * Execute certain G-code commands immediately after power-on.
 */
//#define STARTUP_COMMANDS "M17 Z"
```

Hope that helps.

**Comment by bill-orange** [comment]
@borland1 That is very helpful.  Thank you.
