### ISSUE TITLE
Z not holding after probing

### ISSUE THREAD

**Issue by snowfox50** [MarlinFirmware/Marlin#18254]
Hello,i have a problem where bltouch works fine and calibrated the Z offset,but everytime i do a new print it doesnt hold and id have to manually change the z offset again, is this a gcode problem or marlin problem ? thanks

**Comment by ruggb** [comment]
did you do an M500 to save the settings?

**Comment by sjasonsmith** [comment]
@snowfox50 can you provide specific instructions somebody would need to reproduce and observe this issue?

**Comment by sjasonsmith** [comment]
You will also need to attack your configuration files, as requested in the issue template.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
