### ISSUE TITLE
No normal Print (X,Y Movement) after Babystep (Z) using and aborted printing

### ISSUE THREAD

**Issue by dreiduke** [MarlinFirmware/Marlin#18252]
### Bug Description

No normal Print (X,Y Movement) after babystep (Z) using and aborted printing.
When a print will be aborted after the using of Babystep Z adjustment, the next Print starts at Home position, it means Printer extrude like Printing, but X and Y stand still at home Position.

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1.  Start any Print

2.  Use babysteps for adjusting Z

3. Abort Print

4. Star a new Print 

Result:
Printer homes, and start extruding at home position without any movement of X or Y 

**Expected behavior:** 
...that the print starts normal

**Actual behavior:** 
...print (extrution) starts without Axis movement

#### Additional Information
this happens only when babyteps (Z) is used prior abort
Only Board rest or ON/OFF cycle recovers normal function.

My Config files:
[Cheetah 5  Firmaware compiled mit PIO  05.28_E_A4988_E0_inv_SD_en.zip](https://github.com/MarlinFirmware/Marlin/files/4767184/Cheetah.5.Firmaware.compiled.mit.PIO.05.28_E_A4988_E0_inv_SD_en.zip)

**Comment by ruggb** [comment]
I can't access your config files. I assume u are refering to BABYSTEPPING. What kind of printer? CoreXY? do you have XY babystepping enabled? If so, try disabling it.

**Comment by dreiduke** [comment]
> I can't access your config files. I assume u are refering to BABYSTEPPING. What kind of printer? CoreXY? do you have XY babystepping enabled? If so, try disabling it.

XY Babystep is enabled 
Makes sense, I will give it a try.

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
