### ISSUE TITLE
1.1.9.1 release did not update Version.h

### ISSUE THREAD

**Issue by belm0** [MarlinFirmware/Marlin#18275]
I expected the version string to be "1.1.9.1", and date to be updated.

https://github.com/MarlinFirmware/Marlin/blob/9b555f2fee4061d6031dcdc71559eb55d86e36e3/Marlin/Version.h#L38-L52

cc: @thinkyhead

**Comment by ellensp** [comment]
Marlin prior to 2.0.0 is no longer being worked on or updated,

**Comment by belm0** [comment]
> Marlin prior to 2.0.0 is no longer being worked on or updated

I understand development is on 2.0, but a 1.1.9.1 release was made in March.  Without updating the version string, boot screens will not show an accurate version, etc.

https://github.com/MarlinFirmware/Marlin/releases/tag/1.1.9.1
