### ISSUE TITLE
[BUG] Heater_ID: bed - Printer halted.

### ISSUE THREAD

**Issue by uli6** [MarlinFirmware/Marlin#18278]
Hi guys,

I'm facing an error for almost 3 months. 
I have an Anet A8 Plus and since a changed the MB to an SKR 1.4 turbo and start using marlin I'm not able to heat the bed up to 110 degrees.

Every time it reaches around 80 degrees I got this error:

```
Recv: T:33.62 /0.00 B:82.63 /110.00 @:0 B@:127
Recv: Error:Heating failed, system stopped! Heater_ID: bed
Recv: Error:Printer halted. kill() called!
```
and
```
2020-06-12 18:04:39,064 - octoprint.util.comm - WARNING - Received an error from the printer's firmware: Heating failed, system stopped! Heater_ID: bed - Printer halted. kill() called!
| Last lines in terminal:
| Recv: T:33.45 /0.00 B:81.76 /110.00 @:0 B@:127
| Recv: T:33.36 /0.00 B:81.83 /110.00 @:0 B@:127
| Recv: T:33.45 /0.00 B:81.89 /110.00 @:0 B@:127
| Recv: T:33.45 /0.00 B:81.92 /110.00 @:0 B@:127
| Recv: T:33.45 /0.00 B:81.96 /110.00 @:0 B@:127
| Recv: T:33.45 /0.00 B:82.02 /110.00 @:0 B@:127
| Recv: T:33.45 /0.00 B:82.08 /110.00 @:0 B@:127
| Recv: T:33.53 /0.00 B:82.12 /110.00 @:0 B@:127
| Recv: T:33.45 /0.00 B:82.18 /110.00 @:0 B@:127
| Recv: T:33.53 /0.00 B:82.24 /110.00 @:0 B@:127
| Recv: T:33.53 /0.00 B:82.28 /110.00 @:0 B@:127
| Recv: T:33.53 /0.00 B:82.34 /110.00 @:0 B@:127
| Recv: T:33.45 /0.00 B:82.37 /110.00 @:0 B@:127
| Recv: T:33.53 /0.00 B:82.44 /110.00 @:0 B@:127
| Recv: T:33.62 /0.00 B:82.50 /110.00 @:0 B@:127
| Recv: T:33.62 /0.00 B:82.53 /110.00 @:0 B@:127
| Recv: T:33.62 /0.00 B:82.60 /110.00 @:0 B@:127
| Recv: T:33.62 /0.00 B:82.63 /110.00 @:0 B@:127
| Recv: Error:Heating failed, system stopped! Heater_ID: bed
| Recv: Error:Printer halted. kill() called!
```
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/4772770/Archive.zip)

Thank you for your support

**Comment by XDA-Bam** [comment]
Looks like thermal runaway protection kicking in, because the bed is heating up too slowly. Try to raise your `WATCH_TEMP_PERIOD` to 25 or 30 s. For support, it's best to ask on discord.

**Comment by ruggb** [comment]
the question to ask may be why it apparently heated faster with the Anet MB since it did not through the error. Is there a heater LED and is it full on while it is heating up? Are any connections getting hot?

**Comment by boelle** [comment]
@uli6 still an issue?

**Comment by sjasonsmith** [comment]
```
#define BANG_MAX 128     // Limits current to nozzle while in bang-bang mode; 255=full current
#define PID_MAX BANG_MAX // Limits current to nozzle while PID is active (see PID_FUNCTIONAL_RANGE below); 255=full current
```

These lines are limited your bed output to half power.

The `B@:127` in the temperature output is the current power being given to the bed, where 255 is the maximum.

**Comment by sjasonsmith** [comment]
Given that this clearly looks like a configuration issue, I'm going to close the bug report. If you continue to have problems I invite you to participate in one of the several Marlin forums where many users are willing to help answer questions and debug configuration issues.

There are several of these options presented to you on the screen you see when reporting a new issue:
https://github.com/MarlinFirmware/Marlin/issues/new/choose
