### ISSUE TITLE
[BUG] Broken Discord Invitation link

### ISSUE THREAD

**Issue by wgcv** [MarlinFirmware/Marlin#18285]
### Bug Description
The Discord Invitation link is not working in the documentation and in the website.

### Steps to Reproduce
1. Click on discord link in documentation, readme or website
2. Invited invalid 😖

**Comment by thisiskeithb** [comment]
[The Marlin Discord server join link](https://discord.gg/n5NJ59y) is still valid:
![image](https://user-images.githubusercontent.com/13375512/84557780-a93aa280-ace2-11ea-843b-980c48e99922.png)

**Comment by ellensp** [comment]
I also could not get it to fail....

**Comment by wgcv** [comment]
Weird when I try it didn’t work im going to close thanks
