### ISSUE TITLE
#error "ADVANCED_PAUSE_FEATURE requires NOZZLE_PARK_FEATURE."

### ISSUE THREAD

**Issue by Vern-K** [MarlinFirmware/Marlin#18300]
Help, I went to turn on the advanced pause features for my SKR mini E3 and received  #error "ADVANCED_PAUSE_FEATURE requires NOZZLE_PARK_FEATURE." I have the nozzle park turned on, so not sure what I have wrong and have spent a bit of time searching the issue and haven't seen any answers. 
Thanks 
Vern
![Screenshot (30)](https://user-images.githubusercontent.com/57025814/84604087-c68d7f00-ae50-11ea-9bf9-102ad3051f42.png)
![Screenshot (32)](https://user-images.githubusercontent.com/57025814/84604091-cc836000-ae50-11ea-89c1-35103333be47.png)
![Screenshot (31)](https://user-images.githubusercontent.com/57025814/84604095-d311d780-ae50-11ea-911d-6951b22ad3cc.png)

**Comment by shitcreek** [comment]
It looks like you are using an older version and this issue has been addressed:
The issue is that the condition is asking: `#elif **ENABLED**(NOZZLE_PARK_FEATURE)`
when it should be asking `#elif **DISABLED**(NOZZLE_PARK_FEATURE)`.

Please try the a newer version or simply correct that bit of code in `SanityCheck.h`

**Comment by Vern-K** [comment]
> It looks like you are using an older version and this issue has been addressed:
> The issue is that the condition is asking: #elif **ENABLED**(NOZZLE_PARK_FEATURE)
> when it should be asking #elif **DISABLED**(NOZZLE_PARK_FEATURE).
> Please try the a newer version or simply correct that bit of code in SanityCheck.h

I updated to the 2.0.5.x last night, when I started working on it. Well changed the ENABLED to DISABLED and now have 3 issues
![Screenshot (33)](https://user-images.githubusercontent.com/57025814/84605118-1cb1f080-ae58-11ea-808b-18c714eca6b2.png)

![Screenshot (34)](https://user-images.githubusercontent.com/57025814/84605134-35baa180-ae58-11ea-9fcd-be2a61e75981.png)
![Screenshot (35)](https://user-images.githubusercontent.com/57025814/84605137-3bb08280-ae58-11ea-8b24-1b431c24f8a2.png)

**Comment by shitcreek** [comment]
Those lines should be comments. How did they get uncommented? Anyway, just go to each of those lines (451, 455 and 656) and comment them out with `//`

**Comment by Vern-K** [comment]
> Those lines should be comments. How did they get uncommented? Anyway, just go to each of those lines (451, 455 and 656) and comment them out with //

Not sure on that, I never went into there, now it's back down to 1 error ![Screenshot (36)](https://user-images.githubusercontent.com/57025814/84605617-fd1cc700-ae5b-11ea-8ab9-33120c488093.png)

Should I just be starting over? or does that have to do with the heaters and I need to change the 255 to what I have set as my max temp?

**Comment by shitcreek** [comment]
Not sure about the error, the code looks fine to me from a glance. I'd first save copies of your config and config_adv files, grab the latest Marlin, then overwrite the config files with your saved copies. The sanity check should tell you what's deprecated or has been changed.

"or does that have to do with the heaters and I need to change the 255 to what I have set as my max temp" not sure what you are referring to.

If you need further assistance, please check out:
- Our Discord channel - Join link: https://discord.gg/n5NJ59y
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration vids](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube

**Comment by Vern-K** [comment]
> Not sure about the error, the code looks fine to me from a glance. I'd first save copies of your config and config_adv files, grab the latest Marlin, then overwrite the config files with your saved copies. The sanity check should tell you what's deprecated or has been changed.
> "or does that have to do with the heaters and I need to change the 255 to what I have set as my max temp" not sure what you are referring to.
> If you need further assistance, please check out:
> 
> Our Discord channel - Join link: https://discord.gg/n5NJ59y
> Facebook Group "Marlin Firmware"
> Facebook Group "Marlin Firmware for 3D Printers"
> Marlin Configuration vids on YouTube

Yea tried to put my config files in a new download of the 2.0.5.3 and ended up with "update config files" and a bunch of other issues, so that's a no go, going to check out some of the resources you listed and will drop my full file here. 
[Marlin-bugfix-2.0.xmodified.zip](https://github.com/MarlinFirmware/Marlin/files/4777479/Marlin-bugfix-2.0.xmodified.zip)
