### ISSUE TITLE
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER not working

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1830]
screen is not earned until I added the following parameters:
# define DOGLCD
# define SDSUPPORT
# define U8GLIB_ST7920

**Comment by AnHardt** [comment]
@lcfm1 
Can it be, that for some reason, you use an old 'Configuration_adv.h'?
Than 'Conditionals.h' would not be included.

May also help against #1832.

**Comment by lcfm1** [comment]
No, I took the last archive, taking the delta  printer settings from examples in the subfolder and got this error

**Comment by alexborro** [comment]
That may be the problem.. The DAMN specific files.

We should just include some specific file after the configuration.h and
configuration_adv.h to redefine a few specific labels.

Cheers

Alex
Em 06/04/2015 07:24, "lcfm1" notifications@github.com escreveu:

**Comment by lcfm1** [comment]
http://pastebin.com/jfGBa8fA my conf.

**Comment by AnHardt** [comment]
Would you please test to insert

```
#error "Test error"
```

in line 46 of 'Conditionals.h'.

If you can still compile without errors, please insert the same line into

line 5 of 'Configuration_adv.h' right after #include "Conditionals.h" 

Than please report back.

**Comment by lcfm1** [comment]
AnHardt, got error: Conditionals.h:46:6: error: #error "Test error"

**Comment by AnHardt** [comment]
Ok.
Please remove the error line.
Please undefine 
    #define DOGLCD 
    #define SDSUPPORT
    #define U8GLIB_ST7920
in 'Configuration.h'

to see if your problem is gone.

**Comment by lcfm1** [comment]
hmm... works. what it's mean?

**Comment by lcfm1** [comment]
ok. I downloaded the latest build for today, filled in Arduino and nothing happened. screen clean. http://pastebin.com/fWTFBSET

**Comment by lcfm1** [comment]
it did not work until I uncommented line #define `REPRAP_DISCOUNT_SMART_CONTROLLER`. it should be added to `Conditionals.h`

**Comment by AnHardt** [comment]
We can not define all dispays at once - they conflict with each other.
`#define REPRAP_DISCOUNT_SMART_CONTROLLER`
is the place to tell the compiler:
'Yes i have this display. Please switch it on for me.'

**Comment by AnHardt** [comment]
In `Conditionals.h` the magic happens that if `REPRAP_DISCOUNT_SMART_CONTROLLER` is defined, automatically all options you mentioned in your first posting will be defined.

**Comment by lcfm1** [comment]
AnHardt, I think, for so many screens - it's time to start a separate procedure, by analogy with motherboards
