### ISSUE TITLE
LCD temperatures fluctuate wildly for bed and nozzle when inserting or removing LCD SD card

### ISSUE THREAD

**Issue by Alphaelectric** [MarlinFirmware/Marlin#18308]
I have recently completed the build of my first CoreXY printer (SecKit SK-GO) with SKE 1.3. During calibration I stumbled upon a problem with the displayed temperatures for bed and nozzle. The heating phase for bed and nozzle runs perfectly stable as long as the LCD SD card is not inserted or removed. As soon as the card is inserted or removed from the LCD SD card slot these values start to change up and down almost with every screen refresh. 

Restarting the board via Reset button does not cure the issue.

The issue goes away when power cycling the machine.  

EDIT1: The issue is directly related to removing the SD card from the LCD slot.
EDIT2: The issue is triggered by removing or inserting the SD card from the LCD slot

### My Configurations

SKR 1.3
Marlin 2.0.5.3
Printing from SDCard in LCD card slot
BLTouch 

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4779086/Configuration.zip)

### Steps to Reproduce

1. Turn on printer
2. Insert or remove SD card from LCD SD card slot

**Expected behavior:** [What you expect to happen]
Insert or remove LCD SD card and see no implausible fluctuations

**Actual behavior:** [What actually happens]
Inser or remove LCD SD card and observe implausible fluctuations

#### Additional Information

I have a video of the effect on youtube https://youtu.be/RFppHOKSa34
Formatting the SD card has had no effect

**Comment by ellensp** [comment]
If a reset doesn't cure it, it is very unlikely it is firmware related. 

Yes please link to the you tube video.

**Comment by Alphaelectric** [comment]
> If a reset doesn't cure it, it is very unlikely it is firmware related.
> 
> Yes please link to the you tube video.

Thanks for your reply. I updated the description with my latest findings and uploaded a short demonstration to youtube. It is directly related to inserting or removing an SD card into the LCD panel slot.

**Comment by boelle** [comment]
@Alphaelectric still an issue?

**Comment by Alphaelectric** [comment]
> @Alphaelectric still an issue?

SOLVED: 
Issue was resolved by replacing the SD card

SOLUTION:
The SD card (Intenso 4GB SDHC/SDXC Class10  3411450) seems to have caused the issue. I replaced it with a SanDisk (SDSDB-8192-BULK 8GB Secure Digital Class 4) and the issue did not return after 4 times inserting and removing the card.

**Comment by boelle** [comment]
we can then safely close

is this comes back we can always reopen
