### ISSUE TITLE
Autobedlevel error

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1831]
when tuning between the rows of dots head moves in a parabola
PS on delta printer

**Comment by lcfm1** [comment]
found similar problem https://github.com/MarlinFirmware/Marlin/issues/1731

**Comment by thinkyhead** [comment]
Yes, please add your 2 cents on the existing issue. Basically, I think if we compare to the code that Johann Rocholl has in his Marlin fork it should explain where this is going wrong.
