### ISSUE TITLE
[BUG] M43 shows no report names on any analog pins

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#18329]
### Bug Description

M43 shows no report names on any analog pins

### My Configurations

just enable PINS_DEBUGGING

### Steps to Reproduce

1. #define PINS_DEBUGGING
2. compile and upload
3. Send a M43 at the machine

**Expected behavior:** 

Analog pins should have report names.

**Actual behavior:** 

No analog pins have any names 

#### Additional Information

Noticed this while looking at https://github.com/MarlinFirmware/Marlin/issues/17205
as ADC_KEYPAD_PIN was not being listed.

Bug was introduced https://github.com/MarlinFirmware/Marlin/pull/16756 in pinsDebug_list.h
The Macro #define ANALOG_OK(PN) ((PN) >= 0 && (PN) < NUM_ANALOG_PINS) was introduced.
But NUM_ANALOG_PINS is not defined anywhere. 
Not in Marlin and not in the frameworks.

Each any every analog pin in pinsDebug_list.h uses this ANALOG_OK test, and every single one fails this test resulting in no report name being added.

Looks like it should be 
#define ANALOG_OK(PN) ((PN) >= 0 && (PN) < NUM_ANALOG_INPUTS)

@Bob-the-Kuhn was there a reason for this i'm missing?

**Comment by bcdiaconu** [comment]
I have attached a m43 response from a Zonestar P802Qs with ZRIB board and ADCKeys on LCD.
[m43_Zonestar_ADCKEYS.txt](https://github.com/MarlinFirmware/Marlin/files/4790483/m43_Zonestar_ADCKEYS.txt)
