### ISSUE TITLE
#define LANGUAGE_INCLUDE GENERATE_LANGUAGE_INCLUDE(ru) error

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1832]
got error:

Marlin_main.cpp: In function 'float probe_pt(float, float, float, ProbeAction, int)':
language_ru.h:50:45: error: 'LCD_STR_THERMOMETER' was not declared in this scope

**Comment by AnHardt** [comment]
@lcfm1 
Is this still a problem?

**Comment by lcfm1** [comment]
```
In file included from language.h:235:0,
                 from ultralcd.cpp:4:
language_ru.h:16:58: error: initializer-string for array of chars is too long [-fpermissive]
 #define WELCOME_MSG                         MACHINE_NAME " Р“РѕС‚РѕРІ."
                                                          ^
ultralcd.cpp:34:40: note: in expansion of macro 'WELCOME_MSG'
 char lcd_status_message[LCD_WIDTH+1] = WELCOME_MSG;
```

**Comment by lcfm1** [comment]
i found problem. in line `#define WELCOME_MSG                         MACHINE_NAME " Готов."`

not enough `LCD_WIDTH` for `WELCOME_MSG`

`MACHINE_NAME="Mini Kossel"`
`welcome_msg = "Mini Kossel Готов."` = 18 symbols.

replace with `#define WELCOME_MSG                         MACHINE_NAME " Готов"` in line 16

it was a new error )

**Comment by KiteLab** [comment]
@lcfm1 
Thank you for this tip.
Indeed `char lcd_status_message[LCD_WIDTH+1]` is a bit short since we can use UTF, what needs 2 places for one symbol.

**Comment by SkyFlyer2** [comment]
Странно, я только вот на днях проверял, все там ок было.
Надо только не забыть кодировку русскую добавить, такой дефайн есть в обновленном configuration.h.

Речь идет о последней dev-версии, в ней все ок. Но в версии 1.0.2 будут ошибки!

@AnHardt
I've already checked a few days ago, Russian characters were all compiled and no errors seen.
I mean the latest dev-version.
But vesion 1.0.2 contain bugs, of course.
