### ISSUE TITLE
[BUG] 12864 based screens font moved up 2 pixels after #18294

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#18321]
### Bug Description

After Fix "UTF char cutoff at DOGM edge (#18294)" is applied the fonts on a 12864 screen are 2 pixels higher than they should be.  

### My Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4784304/Configuration.zip)

### Steps to Reproduce

Using a RAMPS and starting with default configuration

1. Enable #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
2. Enable a on/off menu item. I use #define LED_CONTROL_MENU
3. Enable #define RGB_LED and set up some pins 
  #define RGB_LED_R_PIN 4
  #define RGB_LED_G_PIN 5
  #define RGB_LED_B_PIN 6
4. Compile and upload. 
5. At first it looks normal, Scroll the LCD menu down to LIGHTS and select it.
Move down to "Lights: Off". On moving to the item you will notice that all text on the screen moved up 2 pixels higher than it should be. Returning to main display, all Text is 2 pixels higher than it should be.

**Expected behavior:** 

A Normal display, font in correct place. 

**Actual behavior:** 

Font position move up 2 pixels.
![IMG_20200616_161712](https://user-images.githubusercontent.com/530024/84731631-86afce80-afed-11ea-940c-a56f27f7dd35.jpg)
![IMG_20200616_161652](https://user-images.githubusercontent.com/530024/84731635-8c0d1900-afed-11ea-9ea6-0bd40d72f6bc.jpg)

#### Additional Information

introduced in PR #18294
When working on the character fix https://github.com/MarlinFirmware/Marlin/issues/18269
I noticed this issue and fixed it. But this was not added to the PR
I suspect this issue is not seen when the LCD is flipped Vertically. 
This bug is in u8g_fontutf8.cpp in routine fontgroup_cb_draw_u8gstrlen. A previously unused routine.  A PR is coming.

**Comment by ccccmagicboy** [comment]
> I suspect this issue is not seen when the LCD is flipped Vertically.

This issue is not seen when the LCD_LANGUAGE is set to zh_CN, So I did not seen it 😆
