### ISSUE TITLE
[BUG] Unstable MKS_MINI_12864 with MKS_Robin_E3

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#18323]
### Bug Description

When using the MKS_Robin_E3 with the MKS_MINI_12864 the display is unstable. The display goes blank after a while and random black bars pop up when going through the menus. There are also black bars that cover the menu to select the file you want to print which ends up covering the file names.

### My Configurations

[Config Files.zip](https://github.com/MarlinFirmware/Marlin/files/4785319/Config.Files.zip)

### Steps to Reproduce

Select MKS_Robin_E3 and MKS_MINI_12864 and flash the firmware onto the printer.

**Expected behavior:** 
 For the display output to be clear and the display and SD card to function properly

**Actual behavior:** 

The display randomly times out and goes blank and the menu to select the file to print has horizontal black bars. Also, the SD card needs to be in the printer for it to boot. If you move the encoder knob too much on the screen to select a file to print, [the display goes blank](![IMG_3233](https://user-images.githubusercontent.com/66994235/85187733-ba019000-b26f-11ea-926c-9babdf4e7eb7.jpg)) and the printer needs to be turned off and back on for it to be restored. This happens pretty much every time in the print menu, making it impossible to print with an SD card. 
![blank display](https://user-images.githubusercontent.com/66994235/85187780-34321480-b270-11ea-9454-f510f6315253.jpg)
![print menu with bars](https://user-images.githubusercontent.com/66994235/85214983-4b403780-b340-11ea-9cf7-89ac2ae64635.jpg)

#### Additional Information

When I put #define FORCE_SOFT_SPI in the pins file for the board, it appears that the display starts working properly, but the SD card completely stops working. With that option enabled if I insert the SD card into the board the display freezes and it becomes unusable. The same thing happens if the SD card is in the printer when it powers on, the display freezes and becomes unusable. If I power it on without the SD in it, the menus look fine and there are no more black bars randomly popping up. I have tried pretty much every SD related setting in configuration.h and configuration_adv.h. I have also tried different baud rates, changing the display update delay described [here](https://marlinfw.org/docs/basics/troubleshooting.html). Not sure if any of that was helpful, but I hope it is. Sorry in advance if I am missing anything, this is my first time reporting an issue.

This was also tested on the latest bugfix on 6/22/2020 with no luck

**Comment by boelle** [comment]
@cr20-123 still an issue?

**Comment by ghost** [comment]
Hi @boelle, yes it is still an issue

**Comment by boelle** [comment]
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

**Comment by ghost** [comment]
Hi the issue still persits in the latest bugfix.

**Comment by thinkyhead** [comment]
Have you tried messing with the display timing? For example…
```cpp
  #define ST7920_DELAY_1 DELAY_NS(125)
  #define ST7920_DELAY_2 DELAY_NS(125)
  #define ST7920_DELAY_3 DELAY_NS(125)
```
Some display / board combinations need you to tune these.

**Comment by ghost** [comment]
I have tried messing with them, I started off at the delays from your Troubleshooting Tips guide(listed below) and went up in intervals of 100. Should I try going up in intervals of 10 instead and starting from the values in the pins file for the board?

#define ST7920_DELAY_1 DELAY_NS(200) // After CLK LOW
#define ST7920_DELAY_2 DELAY_NS(400) // After DAT
#define ST7920_DELAY_3 DELAY_NS(200) // After CLK HIGH

**Comment by ghost** [comment]
I’m not sure if this helps at all, but the screen goes blank the most when accessing the SD card and scrolling through files. I have tried various SD cards and for each one I tried it has the lines across the screen and when scrolling the display goes blank. The screen goes blank randomly as well, but it is the most repeatable while accessing the SD card.

**Comment by thinkyhead** [comment]
Has it helped at all to use shorter / different cables or isolate the display from the electronics?

**Comment by ghost** [comment]
I have tried using jumpers connecting the pins in use from the display to the board. I have also tried it out of the printer with just power connected to the board over usb and the 24v input on the board. The display cables are only about 200mm long and the only other wires they are close to when everything is connected in the printer are the thermistor wires and endstop wires. Also, if I hook everything back up to the stock Creality board or their version 2.2 board with TMC 2208’s everything functions normally.

**Comment by ghost** [comment]
Is it normal for a 32bit board to require a SD card to be in it for it to boot fully? With the SD in the board while it is booting it goes to the status screen, with the SD out when it’s booting it stays on the boot screen until a SD is inserted. After the SD is inserted it goes to the status screen. Another thought, since the SD slot and the screen share some of the same pins could it be possible that the display is getting confused from the data that is being sent to and from the SD card?

**Comment by ghost** [comment]
The board is no longer in working condition so I can not do any further testing.
