### ISSUE TITLE
Continue after Power-Loss, gantry drop, steppers not locking, print resumes at lower height

### ISSUE THREAD

**Issue by B-rad888** [MarlinFirmware/Marlin#18332]
### Bug Description

Continue after Power-Loss,  gantry drop, steppers not locking, print resumes at lower height. I think this has to do with the software. When I raise the z height from the screen and immediately power off, I do not get any drop in the gantry. However, when resume print function is activated it raises the gantry and when power is fully drained it drops slightly maybe 1mm  - 2mm. It is enough of a drop to not be successful when resuming. I believe there is no function locking the steppers after the raise. I do not know this because I don't know the code that operates this function but it makes sense. I have tried many different heights (for the raise function #define POWER_LOSS_ZRAISE ) from 10mm all the way down to 2mm. I still get a drop in the gantry. I was thinking that there may not be enough power to raise the gantry and then lock the motors, but after my tests there is really nothing else that I can think of doing besides adding a dual Z setup or anti backlash nuts to stiffen up the Z axis and prevent drooping. However I believe this could be achieved with software since in my other tests this only happens with power loss recovery. Not with manually raising the Z axis from the screen and powering off .  

### My Configurations
Ender 3 pro
SKR 1.4 Turbo
BTT TFT35-E3 V3.0 Display Touch Screen
BTT SFS V1.0 Smart Filament Sensor
BTT UPS 24V V1.0 Resume Printing While Power Off Module

[Config H and ADV 1.zip](https://github.com/MarlinFirmware/Marlin/files/4789970/Config.H.and.ADV.1.zip)

Marlin bugfix-2.0.x (latest release)

### Steps to Reproduce

Turn power off while printing
watch gantry raise
watch gantry slightly drop when power is fully drained

**Expected behavior:** gantry to raise and lock with no drooping

**Actual behavior:** gantry slightly drop when power is fully drained

**Comment by InsanityAutomation** [comment]
This is a mechanical issue. The firmware has absolutely no way of knowing about or correcting for this. Increase tension of the rollers to help prevent it, or mod the machine with a Z-Max switch so that it can rehome to the top and configure the offsets correctly.
