### ISSUE TITLE
(SerialException): Write timeout when M104, M140, M303

### ISSUE THREAD

**Issue by longlh** [MarlinFirmware/Marlin#18336]
Everytime I attempt to set temperature of hotend/bed (M104, M140) or PID tuning (M303), I get an error message: `[ERROR] Can't write to printer (disconnected?) (SerialException): Write timeout`

My configuration: https://github.com/longlh/Marlin/commit/88b702612c6abc42709f80c1fee4b67c3edfcf50
Board: FYSETC AIO II
Screenshot: https://imgur.com/a/ypOWu7y

@boelle : Yes, I still have this issue.

P/S: It is weird that I cannot comment on my own issue 👎

**Comment by boelle** [comment]
@longlh still an issue?

**Comment by boelle** [comment]
do you use latest version? https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

updated 10 hours ago

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
