### ISSUE TITLE
"upload" not including the new bootloader?

### ISSUE THREAD

**Issue by kiss81** [MarlinFirmware/Marlin#18339]
HI I tried the autobuild for the latest 2.0.5.3 Marlin version and it is really easy. Thank you for that. The only issue I have now on my cr-10 v2 is that it won't boot after flashing the new firmware using the autobuild tool (which uses avrdude as it seems). I am quite sure that it is not working because only the program is being updated without the new bootloader. A checkbox in the upload window to include flashing the bootloader would be nice to overcome this.

**Comment by thinkyhead** [comment]
Just peeking at the CR-10 V2… There is no attempt or intention within Marlin or within Auto Build to flash bootloaders onto RAMPS_CREALITY boards. You will have to flash your bootloaders separately.
