### ISSUE TITLE
[BUG] Tevo Nereus MKS_ROBIN_NANO is mapped to PB0, PB1 is parts cooling fan

### ISSUE THREAD

**Issue by focusedddd** [MarlinFirmware/Marlin#18346]
This seems to be a Tevo Nereus specific issue, they use Heater 2 for the hot end cooling fan, and PB1 for parts cooling fan.

Also, in MKS_ROBIN_NANO the fan name variable appears to be wrong, its just FAN_PIN config_adv references a FAN1_PIN.

**Comment by ellensp** [comment]
Completely ignoring template, as such this will be completely ignored.

**Comment by thisiskeithb** [comment]
`FAN_PIN` (parts cooling) should be `PB1` and `FAN1_PIN` (hotend cooling) should be `PB0` (if HOTENDS == 1) according to the [pins diagram](https://github.com/makerbase-mks/MKS-Robin-Nano/blob/master/hardware/MKS%20Robin%20Nano%20V1.1_001/MKS%20Robin%20Nano%20V1.1_001%20PIN.pdf). Is your Nereus setup that way @zillarob?

The Robin Nano pins will need to be massaged a bit to accommodate `FAN1_PIN`, [similar to how it’s done in other pins files](https://github.com/MarlinFirmware/Marlin/blob/c8e99d572c4f865f27dea305bfa2ab8bde2e6848/Marlin/src/pins/lpc1768/pins_BTT_SKR_common.h#L66-L86).

Something like:

```cpp
//
// Heaters / Fans
//
#ifndef HEATER_0_PIN
  #define HEATER_0_PIN                     PC3
#endif
#if HOTENDS == 1
  #ifndef FAN1_PIN
    #define FAN1_PIN                       PB0
  #endif
#else
  #ifndef HEATER_1_PIN
    #define HEATER_1_PIN                   PB0
  #endif
#endif
#ifndef FAN_PIN
  #define FAN_PIN                          PB1
#endif
#ifndef HEATER_BED_PIN
  #define HEATER_BED_PIN                   PA0
#endif
```

**Comment by focusedddd** [comment]
Exactly, thanks for cleaning my post up. Updating Pins_MKS_ROBIN_NANO - FAN_PIN & FAN1_PIN to below is the proper config for Tevo Nereus, assuming there are no variations between units. 

```
#define FAN1_PIN                             PB0 

#define FAN_PIN                               PB1
```

**Comment by thisiskeithb** [comment]
I needed to put in a PR for some other changes to the Robin Nano pins, so I combined them: https://github.com/MarlinFirmware/Marlin/pull/18347

**Comment by thisiskeithb** [comment]
The PR has been merged, so you should be set. Please close the issue if it’s resolved 🙂
