### ISSUE TITLE
[BUG] PROBING_MARGIN >= 0, "PROBING_MARGIN must be >= 0."

### ISSUE THREAD

**Issue by focusedddd** [MarlinFirmware/Marlin#18355]
Sanity check for PROBING_MARGIN does not allow value to be negative, but the comment above PROBE_MARGIN in configuration file states:

>  with NOZZLE_AS_PROBE this can be negative for a wider probing area.

**Comment by shitcreek** [comment]
Did you enable `NOZZLE_AS_PROBE`? 
Because the sanity check condition appears correct
```
#if DISABLED(NOZZLE_AS_PROBE)
    static_assert(PROBING_MARGIN >= 0, "PROBING_MARGIN must be >= 0.");
...
```

**Comment by ellensp** [comment]
Didn't follow template, did't include Config files, and didn't include any logs.
Seems to be in error. Closing.
