### ISSUE TITLE
AutoBedLeveling and  MANUAL_Z_HOME_POS they are correlated?

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1836]
when I run the auto-tuning, MANUAL_Z_HOME_POS is changed?

**Comment by thinkyhead** [comment]
No. The `MANUAL_Z_HOME_POS` is a fixed value, which sets the fixed value `Z_HOME_POS` if you enable `MANUAL_HOME_POSITIONS`. It is the Z position of your Z endstop, which is not expected to change, as end-stops do not move.

The `Z_HOME_POS` is used to set the const value for `base_home_pos[Z_AXIS]`. The value in `base_home_pos[Z_AXIS]` never changes. The value in `home_offset[Z_AXIS]` is usually added when `base_home_pos[Z_AXIS]` is used, and the `home_offset` values _can_ be changed using GCode or with the "Set Home Offsets" item in the LCD menu.
