### ISSUE TITLE
[BUG] Pins error into BIQU BQ111-A4 board

### ISSUE THREAD

**Issue by Papipapito** [MarlinFirmware/Marlin#18360]
Board Biqu111-A7
Visual Studio Code 1.46.1
Marlin 2.0.5.3

### Bug Description

Marlin No compile with BIQU BQ111-A4 board , error:

Marlin\src\inc/../pins/lpc1768/pins_BIQU_BQ111_A4.h:52:44: error: 'P2_0' was not declared in this scope
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4806009/Marlin.zip)

### My Configurations

uploaded

### Steps to Reproduce

1. Define board: BOARD_BIQU_BQ111_A4
2. Compile
3. To solve:

add 0 to ALL pins with one number     

Example:

Wrong pins:

#define X_STEP_PIN                         P2_0
#define Y_STEP_PIN                         P2_1
#define Z_STEP_PIN                         P2_2

Correct Pins

#define X_STEP_PIN                         P2_00
#define Y_STEP_PIN                         P2_01
#define Z_STEP_PIN                         P2_02

Uploaded  
[pins_BIQU_BQ111_A4.zip](https://github.com/MarlinFirmware/Marlin/files/4806016/pins_BIQU_BQ111_A4.zip)

**Comment by thisiskeithb** [comment]
Thanks for the updated pins! I've put in PR https://github.com/MarlinFirmware/Marlin/pull/18361 to address this issue.
