### ISSUE TITLE
[BUG] Multiple definition of u8g_bitData, u8g_bitNotData, etc

### ISSUE THREAD

**Issue by nadiamoe** [MarlinFirmware/Marlin#18368]
### Bug Description

While trying to compile with latest [u8glib](https://github.com/olikraus/U8glib_Arduino), I get linker errors regarding multiple u8glib-related variables, defined here:

https://github.com/MarlinFirmware/Marlin/blob/c352aeb32ea80f628755f2d28ad6fde6f1cb7be9/Marlin/src/HAL/AVR/u8g_com_HAL_AVR_sw_spi.cpp#L67-L68

These variables collide with some with the same name in u8glib:

https://github.com/olikraus/U8glib_Arduino/blob/f17d404d8a20831bfb07ef5de0d225cada2adaef/src/clib/u8g_com_arduino_sw_spi.c#L62

These symbols do not seem to be used outside their compilation unit neither in U8glib, nor in Marlin, at least as far as I could `grep`. I have solved this locally by patching Marlin and unexport them. See the diff here:

https://github.com/roobre/Marlin-E5P/compare/2.0.x...roobre:fix-u8glib-exported

I am running Marlin on my printer with this patch and I haven't found issues so far.

### My Configurations

Configuration is basically the sample in the current `2.0.x` branch with some tweaks for the Ender 5 Pro. A diff can be found here: https://github.com/roobre/Marlin-E5P/compare/fix-u8glib-exported...roobre:2.0.x-e5p

Perhaps the most relevant changes are:

```c
#define MOTHERBOARD BOARD_MELZI_CREALITY
#define CR10_STOCKDISPLAY
```
### Steps to Reproduce

1. Download Marlin
2. Download [U8glib](https://github.com/olikraus/U8glib_Arduino) either manually or from the Arduino IDE
3. Attempt to build using the Arduino IDE

**Expected behavior:** Build succeeds

**Actual behavior:** Linking fails due to multiple definitions.

#### Additional Information

It could be that I am not building Marlin correctly, if that is the case please tell me. Otherwise, the patch I linked above is working for me so I could happily create a PR for it.

I also think that it would be better practice to unexport this in U8glib, rather than in Marlin, but since U8g v1 seems to be long unmaintained I think I'd have better success by submitting a patch here.

**Comment by boelle** [comment]
tried with vscode+plaform.io ?

**Comment by nadiamoe** [comment]
> tried with vscode+plaform.io ?

No, sorry, I do not have VSC or PIO on my laptop. It might work with that setup.

**Comment by boelle** [comment]
i use that... but be warned: its highly addictive, once you tried you will never go back to arduino ide

**Comment by nadiamoe** [comment]
> i use that... but be warned: its highly addictive, once you tried you will never go back to arduino ide

Yeah, Arduino IDE is quite simple and limited, I'm not particularly a fan. I usually use [arduino-mk](https://github.com/sudar/Arduino-Makefile) for my projects, but honestly I was not able to get Marlin's makefile to work...

In any case, I'd like to have some feedback regarding the [patch](https://github.com/roobre/Marlin-E5P/compare/2.0.x...roobre:fix-u8glib-exported), just to see if it is worth to create a PR for it :)

**Comment by nadiamoe** [comment]
I wanted to add that I tried (in fact, switched to) PIO, which pulls a different u8glib (https://github.com/MarlinFirmware/U8glib-HAL). I cannot reproduce this using PIO setup.

When I was using Arduino for compiling, I tried to use the library mentioned above instead for compilation, but it did not work to me. Unfortunately, I do not have the exact output right now, but I can try to get it if you think it may help.

However, I still think that it would be a good idea to keep those symbols private, as they seem to be internal and are conflicting on at least one build environment. Is there a reason I'm not seeing them for keeping them exported?

**Comment by sjasonsmith** [comment]
@roobre it might be more effective to just post the PR, they will usually be responded to within a couple days. Just be sure to post it against the bugfix-2.0.x branch.

I haven't responded before now because I don't know anything about these u8g libraries, or why there is a custom version for Marlin and we have these duplicated functions.
