### ISSUE TITLE
#define MESH_BED_LEVELING error

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1838]
```
Marlin_main.cpp: In function 'void process_commands()':
Marlin_main.cpp:4745:21: error: 'gcode_G30' was not declared in this scope
           gcode_G30();
```

**Comment by epatel** [comment]
Did you also enable `ENABLE_AUTO_BED_LEVELING`? Both can't be enabled at the same time, currently. Sorry. Auto bed leveling with MESH might come later, think @alexborro will/is looking into that.

**Comment by lcfm1** [comment]
epatel, nothing about it says in the instructions https://github.com/epatel/Marlin/commit/4a78db29eb15d599f22c99d66cf79d1427061c64

**Comment by epatel** [comment]
Line 10? OK, I will be more explicit

**Comment by epatel** [comment]
Has been added to this PR https://github.com/MarlinFirmware/Marlin/pull/1774

**Comment by lcfm1** [comment]
http://pastebin.com/fWTFBSET

when I select on-screen level beds, first g29, then there is nothing on the screen, the controller on the screen printer responds knock engine because endstops not work correctly.

**Comment by epatel** [comment]
Yes, I tried earlier today and it seems like latest changes somewhere makes the display work differently. One need to press encoder button once for it to travel to first position.

I don't know what _"screen printer responds knock engine because endstops not work correctly"_ mean.

**Comment by lcfm1** [comment]
sorry for my english)

ok, i tried press encoder, on screen - z: and 4.00
and get gnashing engines. i have delta printer

**Comment by epatel** [comment]
Z: 0.00? You defined `MESH_HOME_SEARCH_Z` to 0? should work mathematical, I have not tested though.

But you very close to the bed for this. I have designed it to work with Z endstop above the bed. Below the bed would be bad as the "endstop level" will be used for traveling between points.

**Comment by epatel** [comment]
I will try to look into why the display works differently. Strange. Can't at the moment, doing a long running print >15 hours. :)

**Comment by epatel** [comment]
Delta printer? oh, have no idea how that works, or if it even could with this mesh solution. Maybe @alexborro can give some pointers?

Wish I had one to test with though. Wife would complain I think...getting to much stuff in my man-cave ;)

**Comment by lcfm1** [comment]
epatel, z:4.00

when i tried press encoder, it doesn't go to the first point, it making gnashing engines.

**Comment by epatel** [comment]
Ah, "it doesn't go to first point", thats bad. If you press the encoder button again (go to next point)? gnashing engines again? 

When lowering (turning encoder backwards) the hotend should move very slowly, 0.025mm downward. Maybe it is this that sounds as gnashing? Does it move down? Or are your endstops firm? They should accept some (appr 4mm) travel though activation level. I use an optoendstop just because of this.

**Comment by lcfm1** [comment]
if I press for the first time and in the future - it does not go down, he tries to go up for the endstops

**Comment by epatel** [comment]
Well, I think this is something special with delta printers. I wish I could debug it. Will look at the delta code and see if it is something obvious, otherwise I think I need to get a delta printer to fix. Sorry.

**Comment by lcfm1** [comment]
epatel, mark this issue as error

**Comment by epatel** [comment]
Seems like I am not allowed to mark/label issue. But I added #error to PR mentioned above https://github.com/epatel/Marlin/commit/d27c82a4500229abdf9a3d478b981f0315cfee21

**Comment by thinkyhead** [comment]
What is the feedrate that is used for these moves? Always make sure to have a reasonable Max Feedrate set for all your axes, then gnashing shouldn't happen with _normal_ movement.

**Comment by lcfm1** [comment]
thinkyhead, http://pastebin.com/fWTFBSET

**Comment by thinkyhead** [comment]
@lcfm1 Hey max, I'm not entirely sure, but it sounds almost like it homes but then it tries to raise the axis

 but are seeing:
- Homes then afterwards the motors try to move up

or
- As each carriage reaches the top it just continues to try to move up

?

**Comment by lcfm1** [comment]
thinkyhead, after g29, they homes, endstops triggered and motors try to move up

**Comment by lcfm1** [comment]
even if I manually in pronterface droop the carriage down at z = 0.1 and then push encoder on the screen, he tries to climb up. One gets the impression that the function of the z coordinate is inverted and not interrupt trigger stops

**Comment by thinkyhead** [comment]
As an experiment, change your `Z_RAISE_BEFORE_HOMING` to 0 (which I think a max Z endstop should override anyway, but maybe not). That will probably have no effect. Then try changing your `Z_RAISE_AFTER_PROBING` to 0. And finally, try changing the `Z_RAISE_BEFORE_PROBING` to 0. See how each one changes the behavior. When homing to Z max (as a delta _almost_ must) the delta should not try to do any raises _after_ probing, except to retract a servo probe. And actually, I don't see why a delta would home automatically at the end of a `G29`. It should stay where it is, because homing disables the bed-leveling grid.

**Comment by lcfm1** [comment]
Scott, it's can be similar like https://github.com/MarlinFirmware/Marlin/issues/1166
I can check it out only in the evening. 24:00 (GMT)

**Comment by thinkyhead** [comment]
@lcfm1 I look forward to your results. We are trying to isolate the root of this behavior. Be sure to use the latest code.

**Comment by lcfm1** [comment]
@thinkyhead,  @epatel :

`Z_RAISE_BEFORE_HOMING 0`
after click on encoder - g28, then motors try to move up 2 seconds 

`Z_RAISE_AFTER_PROBING`
after click on encoder - g28, then motors try to move up 2 seconds

`#define Z_RAISE_BEFORE_PROBING`
after click on encoder - g28, then motors try to move up 2 seconds

set all to 0 - same

after first click on encoder(move to first probe) i send m114:

```
SENDING:M114
X:10.00 Y:10.00 Z:4.05 E:0.00 Count X: 9.99 Y:9.99 Z:4.01
```

but if i send g28 and after m114:

```
SENDING:M114
X:0.00 Y:0.00 Z:264.50 E:0.00 Count X: 446.22 Y:446.22 Z:446.22
```

**Comment by thinkyhead** [comment]
Ok, I've posted the latest code with bed leveling and homing debugging messages added. To help debug the leveling and probing behavior, get the code at this branch:

https://github.com/thinkyhead/Marlin/archive/debug_leveling.zip

Find the option at the top of `Marlin_main.cpp` named `DEBUG_LEVELING` and enable it. Then run homing and probing, if possible, and you will see output to the serial console. Paste the output from the serial console on Issue #1844.

**Comment by lcfm1** [comment]
@thinkyhead, i am at work now. i live in (GMT+6) zone.

Before i go to work, I found the following:
The procedure is as follows:
1. carriage go home
2. Go to reset the coordinates x: 10 y:10 z: 0
3. After move to z:5

then found the next thing:
when turning the encoder is not moving the z-coordinate, it's moving z-tower coordinate

try to looking for that in code. evening i try to make log.

**Comment by thinkyhead** [comment]
@lcfm1 Just looking over the movement code for the LCD. There are 2 ways to move axes: Babystep or Move. The code for "Move" seems to have the delta transformation in place, as far as I can see.

**Comment by epatel** [comment]
If HOMING is away from the bed I think it should be a minor fix, I think I could look at that (easy testable here). But I don't have any knowledge about DELTA movements...

**Comment by lcfm1** [comment]
@epatel, you use change coordinates or g z1?

**Comment by lcfm1** [comment]
@thinkyhead, can't compile. error:

temperature.cpp.o: In function `_temp_error(int, char const*, char const*)':
C:\Users\LCF\AppData\Local\Temp\build7512567997942369460.tmp/temperature.cpp:446: undefined reference to `IsStopped()'

**Comment by lcfm1** [comment]
@thinkyhead, too many errors during compiling
my files:
configuration.h http://pastebin.com/ans3MeaZ
CONFIGURATION_ADV.H http://pastebin.com/kPhhRHNv

**Comment by lcfm1** [comment]
@thinkyhead, can you compile with my settings?

**Comment by thinkyhead** [comment]
Welcome to the active Development branch! Things should compile now, or soon…

**Comment by thinkyhead** [comment]
Ok, I expect that zip to be better now.
https://github.com/thinkyhead/Marlin/archive/more_configurator.zip

**Comment by lcfm1** [comment]
@thinkyhead, errors( http://pastebin.com/W5yChsxX

**Comment by lcfm1** [comment]
@thinkyhead errors

http://pastebin.com/W5yChsxX
when i paste conf kossel mini

**Comment by thinkyhead** [comment]
@lcfm1 That has been patched. Try the latest code.

**Comment by lcfm1** [comment]
@thinkyhead I try to compile and I get error messages
http://pastebin.com/vCqAvwMW

**Comment by thinkyhead** [comment]
That's not the latest code. Line 1404 is now:

`SERIAL_ECHOPAIR("> ProbeAction:", (unsigned long)probe_action);`

and the code you just posted shows

`SERIAL_ECHOPAIR("> ProbeAction:", probe_action);`

**Comment by lcfm1** [comment]
@thinkyhead, think I was able to compile. try after 4 hours

**Comment by lcfm1** [comment]
@epatel, @thinkyhead code for mesh_level without debug print

**Comment by lcfm1** [comment]
```
Connecting...
start
Printer is now online.
echo:Marlin1.0.2
echo: Last Updated: Apr  8 2015 19:08:50 | Author: (none, default config)
Compiled: Apr  8 2015
echo: Free Memory: 2827  PlannerBufferBytes: 1232
echo:V19 stored settings retrieved (378 bytes)
echo:Steps per unit:
echo:  M92 X44.44 Y44.44 Z44.44 E100.00
echo:Maximum feedrates (mm/s):
echo:  M203 X300.00 Y300.00 Z300.00 E300.00
echo:Maximum Acceleration (mm/s2):
echo:  M201 X1000 Y1000 Z1000 E1000
echo:Accelerations: P=printing, R=retract and T=travel
echo:  M204 P3000.00 R3000.00 T3000.00
echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
echo:  M205 S0.00 T0.00 B20000 X20.00 Z20.00 E20.00
echo:Home offset (mm):
echo:  M206 X0.00 Y0.00 Z0.00
echo:Endstop adjustement (mm):
echo:  M666 X0.00 Y0.00 Z0.00
echo:Delta settings: L=delta_diagonal_rod, R=delta_radius, S=delta_segments_per_second
echo:  M665 L230.00 R141.00 S200.00
echo:PID settings:
echo:  M301 P22.20 I1.08 D114.00
echo:Filament settings: Disabled
echo:SD init fail
echo:enqueing "G28"
echo:enqueing "G28"
Error:Printer halted. kill() called!
```

before kill printer move head to z-tower

**Comment by epatel** [comment]
Mesh + Delta is not yet supported. Should have received an error just for that with latest I think.

**Comment by epatel** [comment]
Also probing more than 7 point per axis is also not supported can also cause more problem. I will add a sanity check for that.

**Comment by lcfm1** [comment]
@epatel, look at the code delta calibration - it works well on my printer.

**Comment by epatel** [comment]
@lcfm1 code delta calibration, sorry don't know what that is or where to find it? You are using Mesh Bed Leveling + more than 7 points? I would not recommend it as internally in the MESH code I am using a "byte" to track number of mesh boundary crossings. 8 might work (because the byte can only hold 8 bits), but I recommend 7 to be on the safe side. To not track them could cause the printer to hang due to floating point rounding risk and comparison.

**Comment by lcfm1** [comment]
@epatel  `#define DELTA_CALIBRATION_MENU` after display conf in `Configuration.h`.

in ultralcd.cpp
line 646

```
static void lcd_delta_calibrate_menu()  
{
    START_MENU();
    MENU_ITEM(back, MSG_MAIN, lcd_main_menu);
    MENU_ITEM(gcode, MSG_AUTO_HOME, PSTR("G28"));
    MENU_ITEM(gcode, MSG_DELTA_CALIBRATE_X, PSTR("G0 F8000 X-77.94 Y-45 Z0"));
    MENU_ITEM(gcode, MSG_DELTA_CALIBRATE_Y, PSTR("G0 F8000 X77.94 Y-45 Z0"));
    MENU_ITEM(gcode, MSG_DELTA_CALIBRATE_Z, PSTR("G0 F8000 X0 Y90 Z0"));
    MENU_ITEM(gcode, MSG_DELTA_CALIBRATE_CENTER, PSTR("G0 F8000 X0 Y0 Z0"));
    END_MENU();
}
```

**Comment by lcfm1** [comment]
@epatel, or use

in ultralcd.cpp
line 662

```
static void _lcd_move(const char *name, int axis, int min, int max) {
    #ifdef DELTA
      calculate_delta(current_position);
      plan_buffer_line(delta[X_AXIS], delta[Y_AXIS], delta[Z_AXIS], current_position[E_AXIS], manual_feedrate[axis]/60, active_extruder);
    #else
      plan_buffer_line(current_position[X_AXIS], current_position[Y_AXIS], current_position[Z_AXIS], current_position[E_AXIS], manual_feedrate[axis]/60, active_extruder);
    #endif
```
