### ISSUE TITLE
[BUG] Failure to compile Latest Bugfix with G35 code

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#18382]
**Bug Description:

Compiler error when using the latest bugfix including G35 code:

> Marlin\src\gcode\bedlevel\G35.cpp: In static member function 'static void GcodeSuite::G35()':
> Marlin\src\gcode\bedlevel\G35.cpp:187:3: error: jump to label 'EXIT_G35'
>   187 |   EXIT_G35:
>       |   ^~~~~~~~
> Marlin\src\gcode\bedlevel\G35.cpp:88:10: note:   from here
>    88 |     goto EXIT_G35;
>       |          ^~~~~~~~
> Marlin\src\gcode\bedlevel\G35.cpp:117:8: note:   crosses initialization of 'bool err_break'
>   117 |   bool err_break = false;
>       |         ^~~~~~~~~  

**My Configurations:

_Included at end_

** edit: compiles fine if  assisted tramming is turned off 
`//#define ASSISTED_TRAMMING`

**Steps to Reproduce:

1. use  my config files with appropriate PlatformIO environment
2. compile
3. observe error

**Expected behavior:

Successful compilation

**Actual behavior:

Failure as noted above.

**Additional Information:

I ran a compare between my configs and those included with the latest bugfix.  I could not find an explanation for the failure.  Could I be using a different version of Platformio?  I have not seen a goto statement since I took FORTRAN in college.  Kind of miss those IBM cards.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4809779/Marlin.zip)

**Comment by sjasonsmith** [comment]
This has been fixed with 2b286a101a676d6139f1807eae047cec9125e53e.
