### ISSUE TITLE
[BUG] Extruder temperature 10ºC below setpoint

### ISSUE THREAD

**Issue by pablopeu** [MarlinFirmware/Marlin#18398]
I'm using latest bugfix on my anycubic delta kossel plus (config: [Marlin-BugFix_June_9.zip](https://github.com/MarlinFirmware/Marlin/files/4822791/Marlin-BugFix_June_9.zip)) did the autotune per marlin recomendations, rewrote the PID values and reuploaded the firmware.

When printing, first layer without fan (M107) temperature dithers very close to the set temperature, but when the second layer starts it goes down and oscilates around 10ºC less than the set point. This can be clearly be seen in octoprint graph:

![Annotation 2020-06-23 223814](https://user-images.githubusercontent.com/25783916/85488842-6069d000-b5a5-11ea-941e-d63ac3e3f275.jpg)

Second layer with the fan on (M106) temperature increases slightly but after the third layer it remains at around 10ºC less until the end of the print with the fan always on.

What is the problem? should I calibrate PID with the fan on? or its something else?

Just in case, this is the gcode: [OttoDIYH_head_v07.zip](https://github.com/MarlinFirmware/Marlin/files/4822846/OttoDIYH_head_v07.zip)

**Comment by pablopeu** [comment]
After two hours into the print, and veeeeeeeery slowly now its only 5C below setpoint.

**Comment by ellensp** [comment]
This looks like your fans are blowing on the hotend itself.
There should be two fans, one that blows on the cooling fins of the hotend. The second which blows on the freshly extruded plastic. 
Neither should blow on the hotend.

**Comment by pablopeu** [comment]
There are two, you are right, a turbine which blows down and with the original deflector heats the layer just printed and the one that blows to the fin. In a nutshell its the original unchanged hotend. 
Can try to print a new deflector and check if it improves.

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
