### ISSUE TITLE
[BUG] Y Endstop event not triggered with Dual Y endstops and Home to Y max

### ISSUE THREAD

**Issue by c3D-Dan** [MarlinFirmware/Marlin#18418]
### Bug Description

Y Endstop event does not trigger with dual Y Endstops enabled AND Home to Y Max.    Disabling Dual Y Endstops, eveything functions fine, albeit without the second Y endstop being observed.

This is not a hardware issue.  M119 reports all endstops correctly. 

### My Configurations
configuration.h
#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
//#define USE_XMAX_PLUG
#define USE_YMAX_PLUG
#define USE_ZMAX_PLUG

#define INVERT_X_DIR false
#define INVERT_Y_DIR true
#define INVERT_Z_DIR false

#define X_HOME_DIR -1
#define Y_HOME_DIR 1
#define Z_HOME_DIR -1

configuration_adv.h
#define Y_DUAL_STEPPER_DRIVERS
#if ENABLED(Y_DUAL_STEPPER_DRIVERS)
  #define INVERT_Y2_VS_Y_DIR true   // Set 'true' if Y motors should rotate in opposite directions
  #define Y_DUAL_ENDSTOPS
  #if ENABLED(Y_DUAL_ENDSTOPS)
    #define Y2_USE_ENDSTOP _YMAX_
    #define Y2_ENDSTOP_ADJUSTMENT  0
  #endif
#endif

### Steps to Reproduce

Home Y axis of the printer with these options enabled.  Y Will not stop when either endstop hit

**Expected behavior:** 1st Y endstop Hit, reverses until second hit, then both hit together, then y axis moves to Y0

**Actual behavior:** Motors crash into Y endstops until printer reset

OUTPUT OF M119
21:12:04.051 : x_min: open
21:12:04.051 : y_min: open
21:12:04.052 : y2_max: open
21:12:04.052 : z_min: open
21:12:04.052 : z_max: open

And when both Y Triggered
21:12:04.051 : x_min: open
21:12:04.051 : y_min: TRIGGERED
21:12:04.052 : y2_max: TRIGGERED
21:12:04.052 : z_min: open
21:12:04.052 : z_max: open

**Comment by ellensp** [comment]
Please provide full actually used Configuration files. So we can drop in appropriate hardware and verify issue

**Comment by c3D-Dan** [comment]
Here you go. 
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4831095/Marlin.zip)

**Comment by robbycandra** [comment]
It is because : 
- #define Y_HOME_DIR 1
- #define Y2_USE_ENDSTOP YMAX

**Comment by boelle** [comment]
@ellensp @robbycandra so this is a config issue and not a bug?

**Comment by c3D-Dan** [comment]
I don’t agree.   I have tried inverting / disabling those options with no success at all.  End up with right hand coordinate system and printer zeros to back left of printer.  In this configuration though all hardware does work.  My Y end stops have to be at Y max for logistical reasons. 

Y2 is using the Y max endstop.  I have also tried mapping it to X2 without success. 

Basically y home dir 1 works fine with a single y motor and y endstop but not at all with 2 y endstops.  This is a bug.

**Comment by c3D-Dan** [comment]
Problem still remains

**Comment by c3D-Dan** [comment]
This should not be closed.  It's a simple issue and easy for any dev to test

**Comment by sjasonsmith** [comment]
Unfortunately it’s not that easy for any dev to test, because most machines don’t have multiple Y motors. Someone would have to contrive a setup without having actual hardware to test with.

**Comment by c3D-Dan** [comment]
I’d be happy to assist where possible.  A dev need just ask.

**Comment by sjasonsmith** [comment]
So keep in mind that most devs are just random people like me that fix bugs in their spare time. Attention tends to go toward hardware similar to their own. If you have any ability to fix the problem and contribute a patch, that would be most welcome.

**Comment by c3D-Dan** [comment]
Thanks for re opening!

**Comment by sjasonsmith** [comment]
There is apparently some disagreement about what "stale" means.
I consider it to mean people are unresponsive and no longer care about finding a solution, which was certainly not your situation.

The bot worked exactly as intended in this case, unflagging the Bug when you replied. Unfortunately a human threw a wrench in the works.

**Comment by c3D-Dan** [comment]
I understand. Many users don't provide updates when they figure their problem.  Likewise, my work around for this was not to use YMax, rather keep Y min combined with x max and just accept a rear left hand coordinate system it creates.  If we can get Y max working, I'll be a happy boy.

I think the moral here is to keep hounding for updates to prevent real issues from being marked stale. 

Dan

**Comment by thisiskeithb** [comment]
> I think the moral here is to keep hounding for updates to prevent real issues from being marked stale.

Just comment when stale bot kicks in.

Someone will need the time, hardware, and interest in an issue they can test/fix and will reply when they find something.
