### ISSUE TITLE
[BUG] MKS robin Lite v1.1 freezing at 100% and won't update again

### ISSUE THREAD

**Issue by theprintsurgeon** [MarlinFirmware/Marlin#18413]
### Bug Description

This issue was addressed previously with someone else but now it is happening again. With the latest marlin bug fix downloaded 6/24/20 the board will not update and freezes on 100%. I have the MKS Robin Lite board v1.1 with the MKS robin lite LCD 12864 v1.1 screen. I have tried all combinations of serial ports and screens. If someone can just provide me with a working project folder for this board screen combo that would be great.

### My Configurations

[config files.zip](https://github.com/MarlinFirmware/Marlin/files/4828959/config.files.zip)

### Steps to Reproduce

1. Compile and load on SD
2. Insert SD
3. Update

**Expected behavior:** Complete update, restart, function normally

**Actual behavior:** Freezes at 100%

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by sjasonsmith** [comment]
I would not even know where to begin with this one, if it is a problem with the actual firmware update process?

@thisiskeithb, are you familiar with this board, and anything that might cause this behavior?

**Comment by thisiskeithb** [comment]
> @thisiskeithb, are you familiar with this board, and anything that might cause this behavior?

I am not.

**Comment by theprintsurgeon** [comment]
Hi ! Thanks for checking in on this. It's definitely something with the stm32 boards. I basically just swapped out the board for another one. But I wasn't able to get any of the MKS Robin firmwares to compile because of various errors. In most of these cases I left the settings default and just changed the board name or the board and the screen.

**Comment by sjasonsmith** [comment]
The original issue said it couldn’t update to the board after you built the firmware. Your last post indicates you could not compile successfully. Which is it?

If it is the original issue with the firmware update, what do you mean by “it gets to 100%”?  Where do you see that?

**Comment by theprintsurgeon** [comment]
Right, sorry, let's just focus on one issue at a time. there was a severe problem trying to get the firmware to compile in the first place. Just selecting that bored I mention that because it's the easiest to start with and reproduce. 

Now, when I actually do get the firmware to compile and I upload it to the board the MKS screen on the device will show that it's updating, get to 100%, and stay there. I will try to power on the board and take a picture shortly.

**Comment by theprintsurgeon** [comment]
Here is the update issue I am referring to. It just hangs on this screen. This is the most recent nightly build of Marlin. 

As a separate issue that I am just mentioning so you know what troubleshooting steps I've already taken: the stable marlin release causes a boot loop, it updates displays the Marlin bigfix screen, then the custom splash screen that I have added then restarts indefinitely.

I have also gone to the makerbase page and downloaded the marlin firmware that they provide. I am unable to compile this firmware. I have tried on two computers. They provide a factory firmware.Bin file. If I use this file the board will update but I can't use it because I have no idea what features are enabled or what printer volume, speeds, etc they built into their published .bin file. 
![20200630_101206](https://user-images.githubusercontent.com/67402706/86145578-b1edef80-babc-11ea-841b-7445a6280e5d.jpg)



https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip  ---updates and freezes at 100%

https://github.com/MarlinFirmware/Marlin/archive/2.0.x.zip    ---- updates and bootloops 


https://github.com/makerbase-mks/MKS-Robin   ----- Firmware wont compile, has a precompiled firmware that will update the board. 


I've deduced from all the combinations I have tried that something has changed in marlin that this board doesn't like. It's not the board because I can update it and it will work with the mkslite.bin provided by mks.

**Comment by theprintsurgeon** [comment]
Any updates?

**Comment by sjasonsmith** [comment]
The challenge here is that your board seems to be uncommon and maybe now impossible to buy. This makes it hard for anybody to reproduce the issue. I was hoping someone else with an MKS Lite v1.1 would notice this  and be able to help.

**Comment by theprintsurgeon** [comment]
> The challenge here is that your board seems to be uncommon and maybe now impossible to buy. This makes it hard for anybody to reproduce the issue. I was hoping someone else with an MKS Lite v1.1 would notice this and be able to help.

I can mail you the board if that helps. It's useless to me its current state
