### ISSUE TITLE
Feature request: Save printer settings on sd card

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1841]
It would be good to printer settings saved on the memory card every time you run Auto Levels and calibration. In addition to the firmware had the opportunity to include this file in order to flashing every time you do not fill in the configuration file and not to Auto level

**Comment by thinkyhead** [comment]
It's also been proposed to move to .cnf or .ini style files similiar to Repetier Host, which are just written and read literally, and which are also verbatim as the EEPROM settings. As long as it fits within the smallest EEPROMs.

**Comment by lcfm1** [comment]
or dumping eeprom for test or something else

**Comment by thinkyhead** [comment]
`M503 S0` is one of the more obscure features of Marlin.

**Comment by TechMasterJoe** [comment]
not really i cross check my 501 and 503 every firmware upload after calling 502>500>reconnect>503
this is how i know for SURE all my old data was over written

**Comment by boelle** [comment]
its been asked for here also: https://github.com/MarlinFirmware/Marlin/issues/1185

**Comment by Roxy-3D** [comment]
I suggest we have a _BIG_ discussion on this topic after the current bug fix phase.  The reason being this:   I don't think we want to go add different approaches in a Willy Nilly manner.  There are going to be 37 different ideas to address the issues.   How about we actually understand the real issues and then solve the problem just once?

I do see the value of saving the configuration information in different locations.   But how about saving the information in the second 1/2 of the EEPROM?  There might be room to have the first configuration stored in the first 1/2 of the EEPROM and a 2nd configuration stored in the 2nd 1/2 of the EEPROM.

Any way...  I'm really not trying to be difficult.   Instead...   I'm hoping for a well thought out discussion that leads to an elegant answer.   And failing that, I guess we can fall back and implement 37 different approaches.   But I'm hoping we can be clever and do a more focused approach.

**Comment by thinkyhead** [comment]
The `S0` argument to `M503` is one of the more obscure features of Marlin.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
