### ISSUE TITLE
status screen show Z to 2 places

### ISSUE THREAD

**Issue by TechMasterJoe** [MarlinFirmware/Marlin#1843]
change
`u8g.print(ftostr31ns(current_position[Z_AXIS]));` to
`u8g.print(ftostr32(current_position[Z_AXIS]));`
it's in `dogm_lcd_implementation.h` somewhere around line 255ish
i made the change on mine and i like it a lot so recommending it for everyone lol

**Comment by thinkyhead** [comment]
The `ftostr32sp` function works pretty well too!
