### ISSUE TITLE
STM32 Version 7 Breaks Marlin Unable to Compile

### ISSUE THREAD

**Issue by drphil3d** [MarlinFirmware/Marlin#18440]
Compiling Marlin 2.0.5.3 using platformio for SKR Mini e3 v1.2

It worked a month ago but now it's broken!
I noticed stm32 released version 7 of their tool chain so I tried setting the version in the platformio.ini file to 6.1.1 and 6.0.0. I can get further now but it complains of neopixel errors. This issue is not unique to me many other people are reporting the same exact issue.
https://www.reddit.com/r/ender3/comments/hfz0dt/help_with_marlin_compilation/

platform = ststm32@~6.1.1
https://github.com/platformio/platform-ststm32/releases

**Comment by ellensp** [comment]
yes, is already patched in bugfix and a new release is imminent
