### ISSUE TITLE
SKR V1.4 Turbo + Creality Ender 3 Display = Blue screen

### ISSUE THREAD

**Issue by destruct123** [MarlinFirmware/Marlin#18443]
Bug Description:

I've just installed my SKR V1.4 on my Ender 3. When i try to boot all i've got is a blue screen on my display, i've already rotated the plug because the original orientation don't light up the screen. Using display and board EXP1. I think it's got to do with diferent pin configuration on the board and the display. I think the button and scroll is working fine because i can hear the scrolling and clicks from the display just got no image.

 My Configurations:

[config.zip](https://github.com/MarlinFirmware/Marlin/files/4840323/config.zip)

Steps to Reproduce

1. Turn on the board (USB/PSU)
2. Screen will be blue forever
3. Scroll or press the button will reproduce sound feedback

**Expected behavior:** [What you expect to happen]

Working display with some images

**Actual behavior:** [What actually happens]

Backlight on, no images.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
