### ISSUE TITLE
[FR] X/Y backlash compensation on CoreXY printers

### ISSUE THREAD

**Issue by VanessaE** [MarlinFirmware/Marlin#18444]
### Description

I have a well-built and well-tuned Hypercube (if I do say so myself :smile: ) and backlash is the only other thing that could stand some improvement.  I have already done everything I can mechanically to tune it out, but there's still a bit.  As I understand, it's unavoidable on CoreXY machines due to the sheer length of the belts.

It isn't severe enough on my machine to noticeably distort vertical surfaces, holes, etc.   It's just enough that in top solid infill, I get two lines overlapping slightly, then a tiny gap equal to the overlap, then two more lines, and so on.  Classic signs of mild X or Y backlash.

So if I want tops to be watertight, I have to over-extrude by a percent or two to fill-in the gaps.

According to a backlash test part, it's about 0.14 mm along X, 0.04 mm along Y if the part is printed normally (base parallel to X). Rotated by 45° to force all of the print moves to be on the diagonal, it's 0.02 mm along the -X+Y to +X-Y direction, and 0.03 mm in the -X-Y to +X+Y direction (that is, on the sides facing {0,0} and {200,0}, respectively).

Backlash compensation is available on normal cartesian machines like "bedflinger" and Ultimaker style, but is for some reason disabled on CoreXY.  Of course the movement/kinematics math is somewhat different on a CoreXY, but wouldn't the underlying algorithm still work if it weren't explicitly disabled?

**Comment by kursatu** [comment]
This is something I certainly need to have. I also have a CoreXY printer, (Vking).
The surface quality is super important for my prints. The printer is used to print real products.
There is nothing else I can do to compensate for it mechanically.
The top layer, line gap/overlap is there, especially with layer heights of 0.1mm

**Comment by palladin82** [comment]
Maybe there need to do motor based backlash compensation on direction change?
This will solve the problem of backlash on other types of mechanics as well.

**Comment by palladin82** [comment]
Test needed [https://github.com/MarlinFirmware/Marlin/pull/21612](https://github.com/MarlinFirmware/Marlin/pull/21612)

**Comment by thisiskeithb** [comment]
Added in #21612
