### ISSUE TITLE
Autoleveling is a complete mess...

### ISSUE THREAD

**Issue by fotis400** [MarlinFirmware/Marlin#1844]
Just trying to make my printer work again after some mods (mechanical). I pulled some of the latest commits, and now I am trying to print.

My problem now is with autoleveling, G29. It performs completely wrong and unexpectedly...
G28 works correct.
G29 works again correct when send manually, after the G28.

Then I try to print the following file.
1. Heatbed warms up, all the axis home correctly.
2. Autolevel starts and gets to the first point correctly.
3. Same for the second and third point in the same row (I probe in 9x9 grid).
**4. After that it starts moving all the axis towards their homing direction VERY slowly. It also extrudes simultaneously with the same slow speed.**
5. When the first endstop triggers, it gets to the next normal point. It probes the next 3 points (the second row) normally.
**6. At the end of the second row again it starts moving towards homing, very slowly, again extruding...**
**7. After an endstop getting triggered, it goes straight down, like it should do for probing the next 3 points, but this time, X & Y are NOT moving at all resulting in a crash, 'cause probe is outside bed.**

After this kind of calibration, you understand that my printer has a very weird idea about reality, and printing is impossible. 

The file I try to print:
http://pastebin.com/NnQPkZqE

My config:
http://pastebin.com/ujBp4vq1

**Comment by boelle** [comment]
@thinkyhead is working on it....

**Comment by thinkyhead** [comment]
To help debug the probing behavior, get the code at this branch:

https://github.com/thinkyhead/Marlin/archive/debug_leveling.zip

Find the option at the top of `Marlin_main.cpp` named `DEBUG_LEVELING` and enable it. Then run probing, if possible, and you will see output to the serial console. Paste the output from the serial console here.

**Comment by lcfm1** [comment]
```
Compiled: Apr  8 2015
echo: Free Memory: 2499  PlannerBufferBytes: 1232
echo:V19 stored settings retrieved (378 bytes)
echo:Steps per unit:
echo:  M92 X44.44 Y44.44 Z44.44 E100.00
echo:Maximum feedrates (mm/s):
echo:  M203 X300.00 Y300.00 Z300.00 E300.00
echo:Maximum Acceleration (mm/s2):
echo:  M201 X1000 Y1000 Z1000 E1000
echo:Accelerations: P=printing, R=retract and T=travel
echo:  M204 P3000.00 R3000.00 T3000.00
echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
echo:  M205 S0.00 T0.00 B20000 X20.00 Z20.00 E20.00
echo:Home offset (mm):
echo:  M206 X0.00 Y0.00 Z0.00
echo:Endstop adjustement (mm):
echo:  M666 X0.00 Y0.00 Z0.00
echo:Delta settings: L=delta_diagonal_rod, R=delta_radius, S=delta_segments_per_second
echo:  M665 L230.00 R141.00 S200.00
echo:PID settings:
echo:  M301 P22.20 I1.08 D114.00
echo:Filament settings: Disabled
echo:Z-Probe Offset (mm):
echo:  M851 Z-3.50
echo:SD init fail
>>> g29
SENDING:G29
echo:Home X/Y before Z
>>> g29
SENDING:G29
G29 Auto Bed Leveling
9.00 4.57 0.29 -4.74 -12.70 -15.97 -15.99 -16.00 -16.01
0.18 -1.67 -6.02 -10.38 -14.35 -15.98 -16.00 -16.01 -16.03
-10.02 -7.91 -12.33 -16.01 -16.00 -15.99 -16.00 -16.02 -16.02
-13.00 -14.50 -16.00 -15.99 -16.00 -16.01 -16.00 -16.01 -16.00
-15.98 -15.99 -16.01 -16.00 -16.01 -16.00 -16.01 -16.00 -16.01
-15.99 -16.00 -16.02 -16.01 -16.00 -16.01 -16.00 -15.99 -16.00
-16.00 -15.99 -15.98 -15.99 -16.01 -16.00 -16.01 -16.00 -15.99
-15.97 -15.98 -16.01 -16.00 -15.99 -16.00 -15.99 -16.01 -16.00
-15.98 -16.02 -16.01 -16.00 -15.99 -16.00 -16.00 -16.00 -16.01
Disconnected.
```

**Comment by fotis400** [comment]
Very interesting... And strange....

I sent a G28. All normal. I sent a G29 all normal.
Here is my output: http://pastebin.com/bzq1DKPP

I tried to print the above file which in fact starts with G28 and G29! Read the output. You will laugh (or cry...)

http://pastebin.com/PnfgRkXH

(It must be noted that all the times the probe worked, after probing it went up "in two steps" as in the above mentioned issue.)

**Comment by thinkyhead** [comment]
Ok, so first thing is, at the beginning of `G28` it doesn't need to call `deploy_z_probe`. It should only do that if it's using the Z min endstop as the Z endstop. For a machine with a Z max endstop, it should skip this step.

The code that's deploying the probe in this case is in the `home_axis` function, so I will add a check there.

**Comment by lcfm1** [comment]
@thinkyhead the printer does not even arrives to the moment when the trigger should operate. he just tries air and goes to the next point. may have to verify that he has triggered, and only after proceed to the next point

**Comment by lcfm1** [comment]
@thinkyhead please insert in these functions more debug print -  I can run this code on a printer for detailed debugging

**Comment by thinkyhead** [comment]
Let's switch over to #2040 where the problem is being narrowed down.
