### ISSUE TITLE
ESP 3D DID NO WORKING. 

### ISSUE THREAD

**Issue by Talha909** [MarlinFirmware/Marlin#18467]
I have installed ESP 3D with my SKR 1.4 Turbo with TMC2130. It was working good. Yesterday  I installed the new bugfix. The stepper Driver also updated.  I made the changes and upload the firmware again. Before undated my esp is working good. But after update my esp loss the connection the with board. I connected with the esp but there is no communication with esp and printer.  I did not get the printer configuration from esp and no command is working. There diver of libery of TMC2130 also updated 
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4844485/Marlin.zip)
.

**Comment by ellensp** [comment]
new copy of firmware probably initiated new framework files.  overwriting required serial modifications for a ESP 3D on SKR1.4 Turbo. Remember that to get this to work you needed to modify the IO pins used by the framework serial ports. 

Check your  .platformio/packages/framework-arduino-lpc176x/cores/arduino/HardwareSerial.h for PinCfg.Pinnum = 28; and PinCfg.Pinnum = 29; If its not there you need to re edit this file. 

See https://youtu.be/NGgzw-XayEo?t=1518 for a refresher on how to do this

**Comment by ellensp** [comment]
The above being the case, this is not a marlin issue at all, So ill close this. If this does not resolve the issue, we can reopen it.
