### ISSUE TITLE
Cold extrusion prevention not working

### ISSUE THREAD

**Issue by fotis400** [MarlinFirmware/Marlin#1846]
Just tested it multiple times.

With my extruder cold, I send a command to extrude. The printer echoes that it prevented a cold extrude but it DOES extrude.

**Comment by boelle** [comment]
Not good... @thinkyhead you think you can spot why this one is happening?

**Comment by clefranc** [comment]
Potential bug confirmed with https://github.com/MarlinFirmware/Marlin/pull/1847

**Comment by clefranc** [comment]
It's the new e delta calculation https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/planner.cpp#L508

You need to recalculate the delta after the `PREVENT_DANGEROUS_EXTRUDE` block https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/planner.cpp#L510

I've put this on line 526

`de = target[E_AXIS] - position[E_AXIS];`

**Comment by thinkyhead** [comment]
Fixed the delta e issue (in the above-linked commit).

**Comment by fotis400** [comment]
tested and works ok.
