### ISSUE TITLE
[BUG] Cancel Object Numbers on statusscreen not corresponding to menu

### ISSUE THREAD

**Issue by swissnorp** [MarlinFirmware/Marlin#18461]
On the statusscreen it sais "Printing Object X" and in the Menu for Canceling there is "Object X-1".
Sorry for this stupid issue :). I am new to github. Could someone fix this, please?

 but in _cancel_object.ccp_ it says:
>  #if HAS_DISPLAY
>    if (active_object >= 0)
>      ui.status_printf_P(0, PSTR(S_FMT " %i"), GET_TEXT(MSG_PRINTING_OBJECT), int(active_object **+ 1**));
>    else
>      ui.reset_status();
>  #endif
>}

It would be an easy fix just to remove the "+1" ... what i did for compiling marlin.

**Comment by sjasonsmith** [comment]
@swissnorp, you are welcome to submit a Pull Request to fix problems you find in Marlin.

If you aren't just going to post that PR yourself, I encourage you to go back and update your description to match the issue template you saw when filing the report. That consistent formatting will help make it easier for others to volunteer to help. Most important is the attaching of your configuration files.

**Comment by GMagician** [comment]
This is the old problem of 0 based and 1 based values.
Objects in gcode are 0 based, but "humans" likes 1 based things.
Starting from idea to keep 1 on display, solution will be to subtract 1 to choosen item.
May be this the correct solution? I can't answer

**Comment by boelle** [comment]
@swissnorp seen what the others wrote?

**Comment by swissnorp** [comment]
I have seen the answers, yes. But i was on a vacation for some time.
I am new to github and not quite shure how to properly do a pull request with the files and the issue linked.
