### ISSUE TITLE
177[BUG] Dual extruder PID values not recognised in firmware[BUG] (short description)

### ISSUE THREAD

**Issue by seitmand** [MarlinFirmware/Marlin#18477]
Please re-open issue #17738 .  On June 22, I responded

 "I have now downloaded both 2.0.5.3 and bugfix-2.0.x (as of today).  The problem exists still in both downloads.

Basically, after downloading,   I issued the M502 command to load the firmware values.  Then I type both M301 and M301 E1 command.  The values returned are the same for both extruders.  In both cases, the values are the values in the firmware for extruder E1.  I only have two extruders,

Thank you.

If you want, I can attach (again) my latest configuration files."

Apparently, this response did not make to the issue, and it was closed. 

 THIS BUG STILL EXISTS.

**Comment by thinkyhead** [comment]
Re-opening the previous issue.
