### ISSUE TITLE
MSG_LEVEL_BED i didn't find in all language files, except en

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1848]

**Comment by thinkyhead** [comment]
Feel free to contribute translations! English is the fallback for strings not yet translated.

**Comment by lcfm1** [comment]
@thinkyhead, Who added all string in another language files?

**Comment by AnHardt** [comment]
@lcfm1 
git blame gives the answer.

**Comment by thinkyhead** [comment]
@lcfm1 Language contributions arrive whenever those who know the language make a PR and submit it. There are thousands of forks of Marlin, most not very dynamic, but there are a few very active contributors. Sometimes only one contribution from someone and then never heard from again.

**Comment by boelle** [comment]
i will close this one as it not an issue with marlin and that people who wants support for something should submit an PR instead.....
