### ISSUE TITLE
Tevo Tornado, Z homing with BLtouch runs into bed.

### ISSUE THREAD

**Issue by R3D8U1L** [MarlinFirmware/Marlin#18491]
### Bug Description

Just got a tevo tornado in and wanted to make it silent. Got a SKR 1.4 turbo with 2209 btt and a bltouch. After countless sleepless nights and flashing firmware x100 I am still not there.

It can home x and y, but when homing z in runs into the bed. the bltouch does nothing! I am sure its an easy fix but I just can't find it after working on the code for multiple days in a row. I just want to use it not fix it. Can't attach a config file. How to?Please help

### My Configurations

(https://drive.google.com/file/d/14kTOtL644XaLmSPhXT1xJIloEAeuYDEu/view?usp=sharing)

### Steps to Reproduce

1. Turn on printer
2. G28
3. G29

**Expected behavior:** home x, y then z. Z with BLtouch

**Actual behavior:** homes x and y, then goes to the middle and runs down into the bed until the endstop is triggered. If you follow the g29 it sending probe error.

#### Additional Information

[https://drive.google.com/file/d/1r_H-tXQnT8niaHDAvRulpLZPH43HE4hL/view?usp=sharing](url)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
