### ISSUE TITLE
Source code for CR10S Pro V2

### ISSUE THREAD

**Issue by Zs0lty87** [MarlinFirmware/Marlin#18492]
Please attach the source code for Creality CR10S Pro V2 as it is not within the examples. The hex file is working good but when I try to configure one from the main source it doesn't work, printer doesn't start up, only showing the startup screen.

The only thing I need to change is the probe offsets but I can't do it without the configured source code.

I'll be a sponsor if you upload the files.

Regards

**Comment by thisiskeithb** [comment]
> Please attach the source code for Creality CR10S Pro V2 as it is not within the examples.

You’ll need to reach out to Creality and request the source code as we don’t have control over that.

Example configs hosted [here](https://github.com/MarlinFirmware/Configurations) are built and contributed by volunteers for the benefit of the community.

**Comment by boelle** [comment]
closing this one as it would have to be provided by creality, nothing we can do here except what we allready done

**Comment by davidcranor** [comment]
Hi, i'm trying to find configuration for my 10S Pro V2, but I do not see a file in the example configs directory, I only see one for the 10s (non-pro non v2), is there somewhere else I should be looking?  thanks!

**Comment by thinkyhead** [comment]
If you get the firmware from Creality3D, it should include the configurations.
