### ISSUE TITLE
Errors on delta printers: move coordinates from menu

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1851]
1. When I try to move the carriage from the menu on the home position, I start knocking engines. This happens due to the fact that to move in the x or y coordinate, it is necessary to move all three bogeys on the towers, but this does not happen, due to the fact that the carriage in the home position.
2. have not found moving along the axis z 10mm

solutions:
1. prohibit the movement of the carriage from the menu on the x or y until there is not enough space for carriages for this maneuver.

**Comment by thinkyhead** [comment]
This overlaps with a general request elsewhere to restrict movement of the carriages at the towers, so that coordinates outside the physical limits will not be attempted, only the nearest-possible coordinate. I posted a sample implementation (not 100% correct) in that thread. [search]

**Comment by lcfm1** [comment]
@thinkyhead, https://github.com/MarlinFirmware/Marlin/issues/1856#issuecomment-90795982

**Comment by lcfm1** [comment]
@thinkyhead, you can calculate a triangle of carriage positions. And check for excess z_home_pos for delta printers

![image](https://cloud.githubusercontent.com/assets/11813836/7039287/7704b970-dde1-11e4-8645-2357ea1c5ea2.png)

**Comment by thinkyhead** [comment]
@lcfm1 Refer to this code for the point where it would be simplest apply the limits, based on current Z position (of the nozzle). https://github.com/MarlinFirmware/Marlin/issues/928#issuecomment-88059303

**Comment by boelle** [comment]
Is this really an firmware error?

**Comment by thinkyhead** [comment]
By rights, the delta is really not ready to be moved until the head has returned to the bed. But, assuming the arms are low enough, XY movement should be permitted within the physical limits of the printer. The top-most usable region of the delta then becomes conical.

**Comment by thinkyhead** [comment]
Two places the Repetier code checks for out-of-bounds conditions:

Starting at [`motion.cpp` line 1245](https://github.com/mrbi11/Repetier-Firmware/blob/work092/src/ArduinoAVR/Repetier/motion.cpp#L1245) the carriages are prevented from moving above the endstops, while the [`transformCartesianStepsToDeltaSteps` function at line 885](https://github.com/mrbi11/Repetier-Firmware/blob/work092/src/ArduinoAVR/Repetier/motion.cpp#L885) will return 0 in any case where the printer tries to move out of bounds. So these are the bits of code we would need to glean from.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
