### ISSUE TITLE
MArlin 2.0 does not compile for Mega2560 board

### ISSUE THREAD

**Issue by zgwalters** [MarlinFirmware/Marlin#18510]
Issue 1: Cannot get any version above 1.17 of Marlin to compile. I get some version of this error with any higher format.
Issue 2: Verified sketch of 1.17 leaves a static boot screen. I can't do anything.
/tmp/ccfYgaAH.ltrans0.ltrans.o: In function `main':
/home/builder/.arduino15/packages/arduino/hardware/avr/1.8.2/cores/arduino/main.cpp:43: undefined reference to `setup'
/home/builder/.arduino15/packages/arduino/hardware/avr/1.8.2/cores/arduino/main.cpp:46: undefined reference to `loop'
collect2: error: ld returned 1 exit status
exit status 1

I'm very new to all of this and would greatly appreciate some advice!

**Comment by boelle** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. 

Use vscode+platformio to compile

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
