### ISSUE TITLE
Error: Showing the logo when i press encoder to enter in menu

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1852]
it's happened everytime when i try to enter

**Comment by boelle** [comment]
what do you try to enter?

**Comment by lcfm1** [comment]
try to enter to menu

**Comment by boelle** [comment]
dooh... of course.... me not reading the subject fully

**Comment by clefranc** [comment]
@lcfm1 Have you tried the latest dev? I can't see the Marlin logo anymore on my printers.

**Comment by AnHardt** [comment]
The logo should be visible one time during boot - now. #1823

**Comment by clefranc** [comment]
@AnHardt Sorry, I should have added "**except during boot**".

**Comment by boelle** [comment]
@lcfm1 Did you try the lates dev?

**Comment by clefranc** [comment]
I didn't see ghost logo while navigating menus with the latest devs.

**Comment by lcfm1** [comment]
@boelle my printer temporarily disassembled

**Comment by lcfm1** [comment]
in latest devs I didn't see ghost logo
