### ISSUE TITLE
Set servo limits with EDITABLE_SERVO_ANGLES feature withoutset Z_PROBE_SERVO_NR, SWITCHING_EXTRUDER, SWITCHING_NOZZLE options enabled

### ISSUE THREAD

**Issue by ReddyVidya0398** [MarlinFirmware/Marlin#18535]
Basically I need to limit the range of 2 servos.Tried editing this block of code in conditionals lcd.h

#if !HAS_SERVO_ANGLES
  #undef EDITABLE_SERVO_ANGLES //commented this line out
#endif
But it wont compile
What other files do I need to look into?

**Comment by ellensp** [comment]
Stop posting this everywhere!
