### ISSUE TITLE
Error: from menu when i press AUTO HOME and go up to level i see 2 Settings menu

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1854]
Steps:

press AUTO HOME
press go up level and it's look like:

Home
Settings
Settings
Clear

it's happened, until carriages not stop.
PS (I use Russian and so the translation of menu items may differ)

**Comment by boelle** [comment]
Can anyone else verify this one?

**Comment by thinkyhead** [comment]
```
Обзор
Настройки
Настройки
???
```

?

**Comment by lcfm1** [comment]
@thinkyhead, yes

**Comment by clefranc** [comment]
@boelle I confirm!
When doing an auto home from the LCD, or a G28 from host, the Prepare menu is replaced by the Tune menu while the homing sequence completes. After homing completion, if I turn the LCD knob, the Tune menu is marlingically replaced by the Prepare menu. The printer think it's printing when doing G28.

I'm looking at the code right now.

**Comment by clefranc** [comment]
@thinkyhead Easy one:

https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L387

Perhaps a new global variable like IS_PRINTING when moves are done with the LCD or host (and SD card).

**Comment by thinkyhead** [comment]
Hmm, so what do you think…

```
if (movesplanned() > 1 || IS_SD_PRINTING) { . . .
```

…?

**Comment by thinkyhead** [comment]
Is this still a problem? I also noticed that sometimes I have to do an extra click on the LCD. I'd like to try to get both at once, sometime soon.

**Comment by thinkyhead** [comment]
This should be fixed in the latest RC (RC2). Please check and if the bug is fixed, close this issue.
