### ISSUE TITLE
[BUG] PR #18490 breaks PRINTER_EVENT_LEDS and M150 without new "I" option.

### ISSUE THREAD

**Issue by ManuelMcLure** [MarlinFirmware/Marlin#18543]
### Bug Description

After PR #18490, ``M150`` without the new ``I`` option does nothing, and ``PRINTER_EVENT_LEDS`` no longer works.

### My Configurations

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/4874349/Configuration_adv.zip)

### Steps to Reproduce

* Use the above configuration (adjust Neopixel settings for your specific printer).
* Execute ``M150 U255`` - all Neopixels should light up bright green, but they do not.
* Execute ``M150 I99 U255`` - now all Neopixels should light up.
* Heat up bed with ``M190`` - ``PRINTER_EVENT_LEDS`` should operate but does not.

It looks like the PR broke Neopixels except for ``M150`` with the ``I`` option specified.

#### Additional Information

Should
```
if (get_neo_index() < 0) { 
```
be
```
if(get_neo_index() >= 0) {
```
?

**Comment by ellensp** [comment]
Confirmed its broken,  looks like thinkyhead broke it when he changed index to support -1

**Comment by ellensp** [comment]
Your fix is correct.

**Comment by ManuelMcLure** [comment]
Created PR #18544.
