### ISSUE TITLE
[FR] (Any update on DHT11/DHT22 humidity/temperature sensor support?)

### ISSUE THREAD

**Issue by astorun** [MarlinFirmware/Marlin#18540]
Hi all,

I was told that there is supposed to be humidity sensor support implemented on bugfix branch.
But I could not see anything related with it.

Is there any support for it, especially for LPC176x series MCU.

Thank you.

**Comment by GMagician** [comment]
I'm not aware of such support

**Comment by sjasonsmith** [comment]
This came up recently, unfortunately it ended up locked immediately when it was closed a few days ago, so nobody can comment on it.
https://github.com/MarlinFirmware/Marlin/issues/17557

I've asked for some help unlocking it (I don't have permissions). Once that happens this could be closed and discussion can move back to that issue.
