### ISSUE TITLE
[BUG] bugfix-2.0.x /TMCStepper@~0.7.0 breaks TMC 2209 communications

### ISSUE THREAD

**Issue by golfromeo-fr** [MarlinFirmware/Marlin#18563]
### Bug Description

bugfix-2.0.x / TMCStepper@~0.7.0 breaks TMC 2209 communications

### My Configurations

bugfix-2.0.x version from early July 2020

### Steps to Reproduce

configure bugfix-2.0.x with TMC2209 UART for SKR PRO v1.1

**Expected behavior:** [What you expect to happen]

the steppers work

**Actual behavior:** [What actually happens]

the steppers do not properly work, sensorless homing is broken

#### Additional Information

TMCStepper@~0.7.0 introduced the bug
TMCStepper@~0.7.1 fixes the problem
https://github.com/teemuatlut/TMCStepper/commit/c71485176aac3b91c9f6fadc39f6d3adfc2a67cd
https://github.com/teemuatlut/TMCStepper/issues/135

**Comment by sjasonsmith** [comment]
I've posted a pull request to update the requirement to 0.7.1.
