### ISSUE TITLE
[FR] bugfix 1.1.x Add Steps/mm menu when using Slim_LCD_Menus

### ISSUE THREAD

**Issue by jp8778** [MarlinFirmware/Marlin#18568]
Because of space constraints I had to deactivate M503 and enable Slim_LCD_Menus on my firmware, this makes it extremely difficult to calibrate the axis and extruder steps.
I was hoping it would be possible to bring back back the steps/mm menus while using the Slim_LCD_Menus. I tried messing around in ultralcd.cpp without any success I also tried using the custom menu interface but couldn't make it work either.

**Comment by thinkyhead** [comment]
Marlin 1.1.x won't be getting any more updates. For best results getting help with customization, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
