### ISSUE TITLE
Error: delta printer endstops not working

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1856]
when I try to change the coordinates near homepos - it causes crackling engines

it also relates to 
https://github.com/MarlinFirmware/Marlin/issues/1838
https://github.com/MarlinFirmware/Marlin/issues/1851

**Comment by lcfm1** [comment]
Relative movement of the carriages hotend like spheres intersecting towers - accordingly it is possible to calculate and to prohibit the carriage to move in order to avoid engine damage or belts

**Comment by clefranc** [comment]
Somewhat related https://github.com/MarlinFirmware/Marlin/issues/1360

**Comment by thinkyhead** [comment]
Two places the Repetier code checks for out-of-bounds conditions:

Starting at [`motion.cpp` line 1245](https://github.com/mrbi11/Repetier-Firmware/blob/work092/src/ArduinoAVR/Repetier/motion.cpp#L1245) the carriages are prevented from moving above the endstops, while the [`transformCartesianStepsToDeltaSteps` function at line 885](https://github.com/mrbi11/Repetier-Firmware/blob/work092/src/ArduinoAVR/Repetier/motion.cpp#L885) will return 0 in any case where the printer tries to move out of bounds. So these are the bits of code we would need to glean from.

**Comment by thinkyhead** [comment]
I should get my delta working soon so I can start fixing this stuff…

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
