### ISSUE TITLE
[BUG] FIL_RUNOUT_STATE HIGH/LOW always detects no filament

### ISSUE THREAD

**Issue by Testmangh** [MarlinFirmware/Marlin#18573]
### Bug Description
With both values, HIGH and LOW the print starts with a "no filament detection"
```
#define FIL_RUNOUT_STATE     HIGH // Pin state indicating that filament is NOT present.
#define FIL_RUNOUT_STATE     LOW // Pin state indicating that filament is NOT present.
```
The switch that I'm using sends a HIGH signal (5V) when filament is not present.

### My Configurations
configuration.h
configuration_adv.h
https://github.com/Testmangh/Marlin/tree/Ender-3-Pro/Marlin

### Steps to Reproduce
Start a print and it will instantly detect no filament present with both configs HIGH and LOW.

**Expected behavior:** [What you expect to happen]
If there is filament the print should not stop (run M600 in my case).

It was working fine with 
`#define FIL_RUNOUT_INVERTING false/false`

**Comment by thisiskeithb** [comment]
@robbycandra: Do the merged changes from your Filament Runout State PR still work for you in the latest `bugfix-2.0.x`?

**Comment by thisiskeithb** [comment]
I just tested the latest `bugfix-2.0.x` (ea94716) on my MK3S/BTT002 build and filament runout works as expected.

**Comment by Testmangh** [comment]
I tested treee times yesterday and it didn't work but now it is working I may have messed up something, SORRY!
Thanks!

**Comment by robbycandra** [comment]
@Testmangh 

I found sometimes the limit switch lever arm not aligned properly with the filament itself.  Therefore the detector report false output.
