### ISSUE TITLE
[BUG] marlin 2.0.x mks robin lite #define MOTOR_CURRENT_PWM_E_PIN  PA6 not working normal

### ISSUE THREAD

**Issue by zlychen** [MarlinFirmware/Marlin#18574]
Bug Description

 #define MOTOR_CURRENT_PWM_E_PIN  PA6 not working normal， extruder E notwork normal。。 can not move normal。。

in pins_MKS_ROBIN_LITE.h 
#define MOTOR_CURRENT_PWM_XY_PIN            PB0
#define MOTOR_CURRENT_PWM_Z_PIN             PA7
#define MOTOR_CURRENT_PWM_E_PIN             PA6
#define MOTOR_CURRENT_PWM_RANGE             (65535/10/3.3) // (255 * (1000mA / 65535)) * 257 = 1000 is equal 1.6v Vref in turn equal 1Amp
#define DEFAULT_PWM_MOTOR_CURRENT { 1000, 1000, 1000 } // 1.05Amp per driver, here is XY, Z and E. This values determined empirically.
 
MOTOR_CURRENT_PWM_XY_PIN       PB0
MOTOR_CURRENT_PWM_Z_PIN         PA7

this two pins out pwm signal was ok... 

 but MOTOR_CURRENT_PWM_E_PIN    PA6  working unusual。。 
 
I used a multimeter to measure the voltage in PA7 and PB0 ，the output voltage was stable。。but Pin PA6 can not output stable voltage for 4985 vref pins let Cause the problem ertruder E can not working。。。

I hope someone can help me solve this problem. . Thanks a lot

My Configurations
[https://drive.google.com/file/d/148T3d6q5LYYRTQDQ4Ta8BqnUhYd2-glY/view?usp=sharing](https://drive.google.com/file/d/148T3d6q5LYYRTQDQ4Ta8BqnUhYd2-glY/view?usp=sharing)

**Comment by shitcreek** [comment]
I fixed your link markup. But requiring people request permission to view it will turn some people away even if they want to help you. It's easier to just zip up your config files and drag and drop it into the comment.

That said. This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
