### ISSUE TITLE
Error: REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER contrast menu not working

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1857]

**Comment by AnHardt** [comment]
The hardware of REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER is not able to set contrast by software.

**Comment by lcfm1** [comment]
if REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER then disable menu

**Comment by boelle** [comment]
Q  here is: are the firmware able to adjust contrast?

**Comment by thinkyhead** [comment]
The value is changed and writes the value to the display. If this display doesn't have contrast, the contrast menu item should not appear.

**Comment by AnHardt** [comment]
@boelle 
For some types of display - yes.
I'll try out find out for which.
