### ISSUE TITLE
[FR] (feature request title)

### ISSUE THREAD

**Issue by jarjartee** [MarlinFirmware/Marlin#18581]
Hi folks - trying to map / control the hotendfan (NOT part cooler ) in MarlinFirmware (MKS Sgen_L) - anyone ??? At the moment NOT running - followed instructions to connect fan to HE-1 (P2.6)but where in Marlin can  I change / map that PIN ??? (yes I'm a n00b
![SgenPins](https://user-images.githubusercontent.com/1782985/86778360-2fcc7080-c052-11ea-97ed-6656325ded89.jpg)
)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
