### ISSUE TITLE
[BUG] Bugfix-2.0 Build Error

### ISSUE THREAD

**Issue by KL-XL** [MarlinFirmware/Marlin#18585]
### Bug Description

Firmware fails to build despite the "passing" sticker.

### My Configurations

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/4886558/Config.zip)

### Steps to Reproduce

1. Open in VS Code
2. Press Build

**Expected behavior:** Successful build
**Actual behavior:** Failed build

#### Additional Information

* ![Annotation 2020-07-07 203701](https://user-images.githubusercontent.com/60302316/86827161-f287d300-c091-11ea-846a-4ec30aceae48.png)

**Comment by p3p** [comment]
Make sure you are using the most recent commit, should be fixed.

**Comment by KL-XL** [comment]
Thank you. 45 min ago I merged the most recent commit and it failed to build. Just a min ago I did the pull again and there were 4 more. Now it builds successfully.
