### ISSUE TITLE
Error: REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER After pressing Stop button on screen, I can not do anything. how to proceed?

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1858]
Encoder responds sound when pressed, but nothing happens

**Comment by SkyFlyer2** [comment]
Right, because this is the "STOP" button. As it should be. Then simply press reset on the main controller.

**Comment by lcfm1** [comment]
@SkyFlyer2, reset button under printer. what i should do?

Then there must be some way to continue working with the buttons on the screen

**Comment by AnHardt** [comment]
@lcfm1 
If you can't reach the reset button, try the power switch. If you have no power switch - pull the wall plug.

Did you hit the stop button by accident?

**Comment by lcfm1** [comment]
no, i just try)

**Comment by boelle** [comment]
This looks like @lcfm1 is just confused about his printer

Is this really a bug in marlin ????

**Comment by thinkyhead** [comment]
Should be documented as: Full Stop requiring hardware reset. Used for most serious fault conditions.

**Comment by boelle** [comment]
btw... if wanting to test hangout etc. i'm there rest of the day.... cam turned off thou

**Comment by thinkyhead** [comment]
@boelle I'm off to bed soon, but next time…!

**Comment by boelle** [comment]
np....
