### ISSUE TITLE
[BUG] Bilinear Automatic Bed Leveling does not form a grid, only X-Axis line. (SKR 1.4 +BLTouch)

### ISSUE THREAD

**Issue by T-SquaredProductions** [MarlinFirmware/Marlin#18596]
### Bug Description

Bilinear Automatic Bed Leveling should form a grid of test points, but it does not, instead measuring 5 points and stopping.

### My Configurations

[Marlin SKR1.4 + BLTouch.zip](https://github.com/MarlinFirmware/Marlin/files/4892635/Marlin.SKR1.4.%2B.BLTouch.zip)

### Steps to Reproduce

1. Upload included firmware
2. Go to "Bed Leveling" Option in "Motion" submenu
3. Watch the probe

**Expected behavior:** The probe measures 5 points on one section of the bed, then the printer should move the bed forward to measure again (at least 3 times)

**Actual behavior:** The probe measures 5 times at the front of the bed on one axis line, and then stops.

**Comment by thisiskeithb** [comment]
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information:

- Download Marlin [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed. This will also enable bed leveling.
- Do some of the moves that revealed problems before. Take notes.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.
