### ISSUE TITLE
Error: MSG_KILLED shows  only first 3 letters in ru language

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1860]

**Comment by lcfm1** [comment]
it looks like a problem with utf-8 and variables size

**Comment by thinkyhead** [comment]
I'm not sure where it's failing. Maybe it's getting the strlen wrong. According to what I read, it should look something like this:

```
int lcd_strlen_P(const char *s) {
  int j = 0;
  uint8_t c;
  while (c = pgm_read_byte(s)) {
    int len = 0;
    if (c < 0x80) {
      // Just increment below
    }
    else if (c < 0xC2) {
      // Invalid continuation, exit
      break;
    }
    else {
      // Length based on 1st byte
      uint8_t len = c < 0xE0 ? 2 : (c < 0xF0 ? 3 : (c < 0xF5 ? 4 : 1));
      while (--len) {
        c = pgm_read_byte(++s);
        if ((c & 0xC0) != 0x80) break;
      }
    }
    s++;
    j++;
  }
  return j;
}
```

…instead of…

```
int lcd_strlen_P(const char *s) {
  int j = 0;
  while (pgm_read_byte(s)) {
    if ((pgm_read_byte(s) & 0xc0) != 0x80) j++;
    s++;
  }
  return j;
}
```

**Comment by AnHardt** [comment]
@thinkyhead 
I think lcd_strlen() is ok. I will look into the recently changed routine for the status message.

**Comment by AnHardt** [comment]
Yesterday fixed with #1839

**Comment by lcfm1** [comment]
Confirm. latest build is working properly with this.

But if i setting language to ru and enable auto bed leveling - i get errors utf-8 decode while compiling

**Comment by AnHardt** [comment]
@lcfm1 
It would be very kind if you could close your resolved issues - like this.
