### ISSUE TITLE
[BUG] Linking firmware for STM32F103CB error

### ISSUE THREAD

**Issue by Serhiy-K** [MarlinFirmware/Marlin#18605]
### Bug Description

I compile firmware for STM32F103CB MCU for "Bluepil" board. Compiling part finished without errors, but linking part finished with warnings and error et the end:

Linking .pio\build\bluepill\firmware.elf
c:/users/my_pc/.platformio/packages/toolchain-gccarmnoneeabi@1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio\build\bluepill\firmware.elf section `.text' will not fit in region `rom'
c:/users/my_pc/.platformio/packages/toolchain-gccarmnoneeabi@1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/ld.exe: region `rom' overflowed by 39736 bytes
.pio/build/bluepill/src/src/MarlinCore.cpp.o: In function `watchdog_refresh()':
d:\Devel\Projects\Marlin/Marlin\src\inc/../HAL/HAL.h:45: warning: undefined reference to `HAL_watchdog_refresh()'
.pio/build/bluepill/src/src/MarlinCore.cpp.o: In function `idle()':
d:\Devel\Projects\Marlin/Marlin\src/MarlinCore.cpp:683: warning: undefined reference to `HAL_idletask()'
.pio/build/bluepill/src/src/MarlinCore.cpp.o: In function `setup()':
d:\Devel\Projects\Marlin/Marlin\src/MarlinCore.cpp:893: warning: undefined reference to `HAL_init()'
d:\Devel\Projects\Marlin/Marlin\src/MarlinCore.cpp:938: warning: undefined reference to `HAL_get_reset_source()'
d:\Devel\Projects\Marlin/Marlin\src/MarlinCore.cpp:944: warning: undefined reference to `HAL_clear_reset_source()'
d:\Devel\Projects\Marlin/Marlin\src/MarlinCore.cpp:1135: warning: undefined reference to `watchdog_init()'
.pio/build/bluepill/src/src/gcode/control/M42.cpp.o: In function `GcodeSuite::M42()':
d:\Devel\Projects\Marlin/Marlin\src\gcode\control/M42.cpp:97: warning: undefined reference to `analogWrite(signed char, int)'
.pio/build/bluepill/src/src/gcode/control/M997.cpp.o: In function `GcodeSuite::M997()':
d:\Devel\Projects\Marlin/Marlin\src\gcode\control/M997.cpp:31: warning: undefined reference to `flashFirmware(short)'
.pio/build/bluepill/src/src/module/planner.cpp.o: In function `Stepper::wake_up()':
d:\Devel\Projects\Marlin/Marlin\src\module/stepper.h:382: warning: undefined reference to `get_timer_dev(int)'
.pio/build/bluepill/src/src/module/planner.cpp.o: In function `Stepper::suspend()':
d:\Devel\Projects\Marlin/Marlin\src\module/stepper.h:384: warning: undefined reference to `HAL_timer_interrupt_enabled(unsigned char)'
d:\Devel\Projects\Marlin/Marlin\src\module/stepper.h:388: warning: undefined reference to `get_timer_dev(int)'
.pio/build/bluepill/src/src/module/planner.cpp.o: In function `Planner::check_axes_activity()':
d:\Devel\Projects\Marlin/Marlin\src\module/planner.cpp:1377: warning: undefined reference to `analogWrite(signed char, int)'
.pio/build/bluepill/src/src/module/stepper.cpp.o: In function `Stepper::init()':
d:\Devel\Projects\Marlin/Marlin\src\module/stepper.cpp:2582: warning: undefined reference to `HAL_timer_start(unsigned char, unsigned long)'
.pio/build/bluepill/src/src/module/temperature.cpp.o: In function `watchdog_refresh()':
d:\devel\projects\marlin\marlin\src\hal/hal.h:45: warning: undefined reference to `HAL_watchdog_refresh()'
.pio/build/bluepill/src/src/module/temperature.cpp.o: In function `Temperature::init()':
d:\Devel\Projects\Marlin/Marlin\src\module/temperature.cpp:1696: warning: undefined reference to `HAL_adc_init()'
d:\Devel\Projects\Marlin/Marlin\src\module/temperature.cpp:1756: warning: undefined reference to `HAL_timer_start(unsigned char, unsigned long)'
d:\Devel\Projects\Marlin/Marlin\src\module/temperature.cpp:1757: warning: undefined reference to `get_timer_dev(int)'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `Sd2Card::chipDeselect()':
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:160: warning: undefined reference to `spiSend(unsigned char)'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `Sd2Card::chipSelect()':
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:164: warning: undefined reference to `spiInit(unsigned char)'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `Sd2Card::readData(unsigned char*, unsigned short)':
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:434: warning: undefined reference to `spiRec()'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:442: warning: undefined reference to `spiRead(unsigned char*, unsigned short)'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:444: warning: undefined reference to `spiRec()'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:444: warning: undefined reference to `spiRec()'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `Sd2Card::waitNotBusy(unsigned long)':
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:529: warning: undefined reference to `spiRec()'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `Sd2Card::cardCommand(unsigned char, unsigned long)':
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:113: warning: undefined reference to `spiSend(unsigned char)'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:116: warning: undefined reference to `spiSend(unsigned char)'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:116: warning: undefined reference to `spiSend(unsigned char)'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:116: warning: undefined reference to `spiSend(unsigned char)'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:116: warning: undefined reference to `spiSend(unsigned char)'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o:d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:119: warning: more undefined references to `spiSend(unsigned char)' follow
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `Sd2Card::cardCommand(unsigned char, unsigned long)':
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:123: warning: undefined reference to `spiRec()'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:126: warning: undefined reference to `spiRec()'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `watchdog_refresh()':
d:\Devel\Projects\Marlin/Marlin\src\sd\../inc/../HAL/HAL.h:45: warning: undefined reference to `HAL_watchdog_refresh()'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `Sd2Card::init(unsigned char, signed char)':
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:245: warning: undefined reference to `spiBegin()'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:249: warning: undefined reference to `spiInit(unsigned char)'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:252: warning: undefined reference to `spiSend(unsigned char)'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `watchdog_refresh()':
d:\Devel\Projects\Marlin/Marlin\src\sd\../inc/../HAL/HAL.h:45: warning: undefined reference to `HAL_watchdog_refresh()'
d:\Devel\Projects\Marlin/Marlin\src\sd\../inc/../HAL/HAL.h:45: warning: undefined reference to `HAL_watchdog_refresh()'
d:\Devel\Projects\Marlin/Marlin\src\sd\../inc/../HAL/HAL.h:45: warning: undefined reference to `HAL_watchdog_refresh()'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `Sd2Card::init(unsigned char, signed char)':
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:278: warning: undefined reference to `spiRec()'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:307: warning: undefined reference to `spiRec()'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:309: warning: undefined reference to `spiRec()'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:309: warning: undefined reference to `spiRec()'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:309: warning: undefined reference to `spiRec()'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `Sd2Card::writeData(unsigned char, unsigned char const*)':
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:586: warning: undefined reference to `spiSendBlock(unsigned char, unsigned char const*)'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:587: warning: undefined reference to `spiSend(unsigned char)'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:588: warning: undefined reference to `spiSend(unsigned char)'
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:590: warning: undefined reference to `spiRec()'
.pio/build/bluepill/src/src/sd/Sd2Card.cpp.o: In function `Sd2Card::writeBlock(unsigned long, unsigned char const*)':
d:\Devel\Projects\Marlin/Marlin\src\sd/Sd2Card.cpp:548: warning: undefined reference to `spiRec()'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\bluepill\firmware.elf] Error 1
========================================================================== [FAILED] Took 49.42 seconds ==========================================================================

I tryed use different board and old platform in platformio.ini - no changes. I saw old issue with solutions, but it does not works.

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4897675/Marlin.zip)

**Comment by thisiskeithb** [comment]
The ` section .text' will not fit in region rom` & `rom' overflowed by 39736 bytes` errors mean you need to disable some features for firmware to fit your board.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
