### ISSUE TITLE
MKS TFT32 doesn't comunicate with MKS GEN L V1.0

### ISSUE THREAD

**Issue by cruceno** [MarlinFirmware/Marlin#18615]
@GhassanYusuf

> I have got the answer,
> in order to make the mks TFT work for me
> 
> ```
> /**
> * Select the serial port on the board to use for communication with the host.
> * This allows the connection of wireless adapters (for instance) to non-default port pins.
> * Note: The first serial port (-1 or 0) will always be used by the Arduino bootloader.
> * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
> */
> #define SERIAL_PORT 0
> 
> /**
> * Select a secondary serial port on the board to use for communication with the host.
> * This allows the connection of wireless adapters (for instance) to non-default port pins.
> * Serial port -1 is the USB emulated serial port, if available.
> * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
>   */
>   #define SERIAL_PORT_2 -1
> 
> /**
> 
> * This setting determines the communication speed of the printer.
> * 250000 works in most cases, but you might try a lower speed if
> * you commonly experience drop-outs during host printing.
> * You may try up to 1000000 to speed up SD file transfer.
> * :[2400, 9600, 19200, 38400, 57600, 115200, 250000, 500000, 1000000]
>   */
>   #define BAUDRATE 115200
> ```
> 
> keep in mind I choose the 115200 baud rate because I configured the TFT screen software to use 115200
> 
> it was exactly opposite of what was mentioned before @Spawn32

When I compile with #define SERIAL_PORT_2 set to -1 I get a massive error ending with:
"expected initializer before '-' token"

It only compiles with SERIAL_PORT_2 commented out and still my MKS FT32 doesn't communicate :( 
Any ideas?

_Originally posted by @T-Risely in https://github.com/MarlinFirmware/Marlin/issues/9633#issuecomment-577854373_

I have exactly the same problem last release of Bugfix 2.0

" When I compile with #define SERIAL_PORT_2 set to -1 I get a massive error ending with:
"expected initializer before '-' token"

It only compiles with SERIAL_PORT_2 commented out and still my MKS FT32 doesn't communicate :( 
Any ideas?
"

**Comment by thisiskeithb** [comment]
You didn't include your configs like the Issue Template asked, but `SERIAL_PORT_2` should be set to something like `1` and your `BAUDRATE` needs to match what you've set in your [TFT firmware](https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-TFT2.8-3.2) (250000 is default).

Also: I just verified a MKS GEN-L + MKS TFT32 communicate fine with the correct settings on the latest `bugfix-2.0.x`.
___
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
