### ISSUE TITLE
[BUG] Marlin 2.0.6 on Anet A6

### ISSUE THREAD

**Issue by roel8032** [MarlinFirmware/Marlin#18612]
Mutilated image on graphic LCD.

When you downgrade the AVR boards to 1.6.23 (current version is 1.8.3) on the Arduino IDE (1.8.13 latest) the images on the LCD are good.
Then every thing is working OK.

![Anet verminkt beeld](https://user-images.githubusercontent.com/6228110/87137117-b2e10700-c29c-11ea-98ee-0a53371502f8.JPG)

**Comment by ellensp** [comment]
no config files.
hasn't followed template

look into 

    #define BOARD_ST7920_DELAY_1 DELAY_NS(0)
    #define BOARD_ST7920_DELAY_2 DELAY_NS(63)
    #define BOARD_ST7920_DELAY_3 DELAY_NS(125)

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
