### ISSUE TITLE
[BUG] [Marlin 2.0.x] LCD messages 3 Point bedleveling

### ISSUE THREAD

**Issue by roel8032** [MarlinFirmware/Marlin#18634]
Graphic LCD Marlin version 20006

LCD messages 3 Point bedleveling.

Anet A6. No need to see the configfiles. It is not in there.
My screen is in Dutch. Meetpunt is Probing Point.

3 point bedleveling
LCD message:
Probing point 1: LCD message: Probing Point 0/3
Probing point 2: LCD message: Probing Point 1/3
Probing point 3: LCD message: Probing Point 2/3

it should be:
Probing Point 1/3
Probing Point 2/3
Probing Point 3/3
![LCD](https://user-images.githubusercontent.com/6228110/87271764-857e9e00-c4d4-11ea-99b1-4e51773abac9.JPG)

**Comment by ellensp** [comment]
and what lcd do you have?   we cant tell, because you didn't include your Configuration files. Could be stock, could be anything.
Please attach your configuration files.

**Comment by roel8032** [comment]
I updated the post.

 

Met vriendelijke groeten,

 

 

Roel Kisteman

06-22.25.44.80

 

Van: ellensp <notifications@github.com> 
Verzonden: maandag 13 juli 2020 06:41
Aan: MarlinFirmware/Marlin <Marlin@noreply.github.com>
CC: roel8032 <roelkisteman@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [MarlinFirmware/Marlin] [BUG] [Marlin 2.0.x] LCD messages 3 Point bedleveling (#18634)

 

and what lcd do you have? we cant tell, because you didn't include your Configuration files. Could be stock, could be anything.
Please attach your configuration files.

**Comment by ellensp** [comment]
Now can you edit your reply to remove all e-mail address, so the spam bots looking for e-mail address cant harvest them.

**Comment by ellensp** [comment]
Your still missing the point, what if we need other settings? language? probe type?  What version of marlin? and a million other questions.

We also want a configuration file that is full and complete so we can drop it in to marlin and replicate this issue.

Attach your config files! This is not optional.

**Comment by Lord-Quake** [comment]
@roel8032
I just tested it on my Ender 3 in UBL configuration, **latest bug fix** and it shows it correctly (1/3, 2/3 and 3/3) on the screen.

So.... post the information as requested by @ellensp. It won't kill you if you want to be helped here.

If I were you I'd install the latest bug fix version before I'd do anything else.

**Comment by roel8032** [comment]
OK.
But UBL (Unified Bed Leveling), is not AUTO_BED_LEVELING_3POINT
I just downloaded the latest. The same problem.

**Comment by Lord-Quake** [comment]
I took a look at the code:

We might have to take a closer look at the following in G29.ccp and add i+1 to the string output: 

        if (verbose_level) SERIAL_ECHOLNPAIR("Probing point ", int(i), "/3.");
        TERN_(HAS_DISPLAY, ui.status_printf_P(0, PSTR(S_FMT " %i/3"), GET_TEXT(MSG_PROBING_MESH), int(i)));

**Comment by roel8032** [comment]
Thanks. Now it is working OK

I changed this in:
\Marlin\src\feature\bedlevel\abl\G29.cpp

line689


//TERN_(HAS_DISPLAY, ui.status_printf_P(0, PSTR(S_FMT " %i/3"), GET_TEXT(MSG_PROBING_MESH), int(i)));
TERN_(HAS_DISPLAY, ui.status_printf_P(0, PSTR(S_FMT " %i/3"), GET_TEXT(MSG_PROBING_MESH), int(i+1)));

The old code above i commented.

Thank you.





![lcd meetpunt_ok](https://user-images.githubusercontent.com/6228110/87328465-ce1a7380-c535-11ea-8b24-7c0d681f68ea.JPG)

**Comment by roel8032** [comment]
> and what lcd do you have? we cant tell, because you didn't include your Configuration files. Could be stock, could be anything.
> Please attach your configuration files.

**Comment by roel8032** [comment]
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
#define ST7920_DELAY_1 DELAY_NS(150)
#define ST7920_DELAY_2 DELAY_NS(150)
#define ST7920_DELAY_3 DELAY_NS(150)

But before i used with the same hardware:
//#define ANET_FULL_GRAPHICS_LCD 

But since Marlin 2.0 that gives bad pictures

**Comment by Lord-Quake** [comment]
I've put up a pull request: https://github.com/MarlinFirmware/Marlin/pull/18639

**Comment by Lord-Quake** [comment]
The commit has been processed into the latest bug fix.
Please test once more and if it is working as expected close this issue.

**Comment by roel8032** [comment]
Al working good in the latest bug fix.
