### ISSUE TITLE
LCD_SET_PROGRESS_MANUALLY requires LCD_PROGRESS_BAR, Graphical LCD, or EXTENSIBLE_UI

### ISSUE THREAD

**Issue by mclemmon** [MarlinFirmware/Marlin#18648]
### Bug Description

firmware not compiling correctly when trying to use SKR mini E3 v2.0 with Ender3v2 LCD screen.

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4919216/Marlin.zip)

### Steps to Reproduce

1. Disable current LCD option
2. Enable DWIN_CREALITY_LCD

**Expected behavior:** compile

**Actual behavior:** a bunch of errors about not having an LCD.

**Comment by ellensp** [comment]
This setting definitely errors, But is it in error? 
Does the .DWIN_CREALITY_LCD work with this setting?

**Comment by thinkyhead** [comment]
The Ender 3 V2 screen code only displays the SD card progress. It is not yet tailored like the other displays to show the progress set by `M73` as an alternative.

**Comment by ChipCE** [comment]
@thinkyhead  I have the same problem but with <code>REPRAP_DISCOUNT_SMART_CONTROLLER</code> . Compiled with 2.0.5.4.

**Comment by ellensp** [comment]
@ChipCE The REPRAP_DISCOUNT_SMART_CONTROLLER is a character display not a Graphical LCD

**Comment by ChipCE** [comment]
@ellensp  Sorry if I'm wrong. I know it is not the lcd is character display, but is there any reason LCD_SET_PROGRESS_MANUALLY cannot work on the 2004 LCD?  I think in Prusa fw they use M73 R[time] to set the remain time.

**Comment by ellensp** [comment]
LCD_progress_bar is the graphical bar. it is not the same as the simple time remaining display. even though it does try and convey the same information.

**Comment by ChipCE** [comment]
@ellensp  sorry for my unclear msg. I mean the 2004 LCD should be able to support LCD_SET_PROGRESS_MANUALLY just to set the remain time with M73. Why LCD_PROGRESS_BAR need to be enabled to use LCD_SET_PROGRESS_MANUALLY ?

**Comment by ellensp** [comment]
What do you think it should do if you enable LCD_SET_PROGRESS_MANUALLY and then set remaining time with M73?

Technically you don't need LCD_PROGRESS_BAR but you cannot see the value until you turn on the LCD_PROGRESS_BAR feature. And if it didn't tell you to turn it on. you wouldn't know and would wonder why there was no display.

**Comment by ChipCE** [comment]
@ellensp  Thank you! I was thinking that option will replace the default timer with the remain time as in the Prusa firmware.
