### ISSUE TITLE
[BUG] Geeetech A20T won't extrude on T1 and T2

### ISSUE THREAD

**Issue by Legarin** [MarlinFirmware/Marlin#18653]
The printer extrude correctly in T0 (E0) but blocked when use any other, tested with latest files.

**Comment by thisiskeithb** [comment]
This looks to be a duplicate of https://github.com/MarlinFirmware/Marlin/issues/18645.

**Comment by Legarin** [comment]
it's the same, but i don't change the drivers and my PB is GT2560 v4

**Comment by thisiskeithb** [comment]
Closing since it's a duplicate of #18645. Please continue discussion over in that issue.

**Comment by thinkyhead** [comment]
Duplicate of #18645
