### ISSUE TITLE
[BUG] M48 - probes one too many times

### ISSUE THREAD

**Issue by qwewer0** [MarlinFirmware/Marlin#18651]
### Bug Description

`M48 - Probe Accuracy Test` seems to probe one too many times,
e.g. `M48 P10` will probe `11` times

### My Configurations

SKR Mini E3 v1.2, BLTouch v3.1
Latest Bugfix-2.0.x 0e1cb109
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4921169/Configuration.zip)

### Steps to Reproduce

1. `G28`
2. `M48 P10`
3. Count it

**Expected behavior:**
`M48 PX` should probe `X` times.

**Actual behavior:**
It probes `X+1` times.

**Comment by sjasonsmith** [comment]
I noticed that, but assumed the first one was a homing probe. I didn’t investigate to determine whether that is true.

**Comment by qwewer0** [comment]
@sjasonsmith If I count G28's two probing for homing too, then it is still one too many.

Edit: As M48 needs you to home first, then I don't think M48 fist probing is for a 0 position, but prove me wrong.

**Comment by thinkyhead** [comment]
The first probe in `M48` seems to be a test to make sure the probe is functioning properly.
```cpp
// Move to the first point, deploy, and probe
const float t = probe.probe_at_point(probe_pos, raise_after, verbose_level);
bool probing_good = !isnan(t);

if (probing_good) {
  randomSeed(millis());

  LOOP_L_N(n, n_samples) {
    . . .
    // Probe a single point
    sample_set[n] = probe.probe_at_point(probe_pos, raise_after, 0);
    . . .
  }
  . . .
}
```

**Comment by qwewer0** [comment]
@thinkyhead Ok, if it is by design then there is no problem here.
Thanks for the information.
