### ISSUE TITLE
[BUG] Incorrect jerks change with m205 on delta printers

### ISSUE THREAD

**Issue by FN5969** [MarlinFirmware/Marlin#18652]
### Description

M205 X10 Y10 gcode command do not change jerk settings properly on delta printer.

### Steps to Reproduce

1. Generate gcode in Cura 4.6 slicer for your delta on marlin 2.0.5.4 
2. Make difrent jerk speed for difrent printing segments. Like jerk 5 on outer wall and jerk 10 on infill.
3. Print this file, and watch how jerks changes in printer menu.

**Expected behavior:** [What you expect to happen]
if delta printer get M205 X10 Y10 it shoul change jerk for all 3 tower. 
VA-Jerk: 10
VB-Jerk: 10
VC-Jerk: 10

**Actual behavior:** [What actually happens]
It change only 2 tower jerk
VA-Jerk: 10
VB-Jerk: 10
VC-Jerk: 5
#### Additional Information
People on forum says that other slicers make same gcode and this is marlin BUG.
https://youtu.be/bUHKI7ZdUN8

**Comment by thisiskeithb** [comment]
Please follow the Issue Template when filing a bug report:

```md
<!--

Have you read Marlin's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/.github/code_of_conduct.md

Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use the Marlin Firmware forum at http://forums.reprap.org/list.php?415 or the Marlin Facebook Group https://www.facebook.com/groups/1049718498464482/ or the Marlin Discord Server https://discord.gg/n5NJ59y.

Before filing an issue be sure to test the 1.1 and/or 2.0 "bugfix" branches to see whether the issue is already addressed.

-->

### Description

<!-- Description of the bug or requested feature -->

### Steps to Reproduce

<!-- If this is a Bug Report, please describe the steps needed to reproduce the issue -->

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.
```

**Comment by FN5969** [comment]
Here is my confings

[Marlin_conf.zip](https://github.com/MarlinFirmware/Marlin/files/4933550/Marlin_conf.zip)

**Comment by XDA-Bam** [comment]
It looks like axes X, Y and Z are mapped to towers A, B and C. If so, setting `M205 X10 Y10 Z10` would change jerk to the desired values. Did you check this?

**Comment by FN5969** [comment]
Yes It is mapped but it should not be! Becouse m205 x y are directions but not towers motor. And only one thing to change it
- manually. And it's not good way to do. May be some one can fix it?

**Comment by XDA-Bam** [comment]
I get that you think  it shouldn't, but how would you address the A-axis jerk individually on a delta, if jerk settings were _not_ mapped X->A, B->Y, etc. ? This is not a simple thing to change - as it is now, it might appear illogical to you, but as best as I can tell, it works as designed.

I think this is more of a slicer problem. The slicer knows this is a delta. It should set the jerk values accordingly in the G-code and right now, it doesn't (slicer oversees the C tower jerk).

**EDIT:** I think I misunderstood you and you misundertsood me, too. There's two problems, here: If you want to set two jerk values only (i.e. X, Y, but not Z), you should be able to. This should not be limited, regardless of the machine type (cartesian, delta, or other).
Independent from this, it's not clear to me if the jerk values are mapped X->A, Y->B, Z->C. From a quick look in the code, all jerk limiting seems to be carried out in cartesian coordinates (X, Y, Z) and the jerk values seem to be in cartesian, too. That would mean they are _not_ mapped X->A, Y->B, etc. but X->X, Y->Y and so on. In that case, I get that you would like to change/improve that.

This would bring up pretty much the same discussion as in #17342 with Junction Deviation, where the same problem applies: Limits in a cartesian coordinate system only really work well on a standard cartesian machine. On a CoreXY, delta or any other machine, they are not really applied correctly right now. It appears as if this basic flaw is the same for CJ and JD.

**Comment by FN5969** [comment]
Thank you mate. May be i wrong but why you can change jerk on delta (or max speed) individualy on separate towers? If this parameters will be merged to one it will be more logic:
VA-Jerk: 10
VB-Jerk: 10
VC-Jerk: 10
to
VABC-Jerk:10 

And it automaticaly fix my problem and some others.

**Comment by thinkyhead** [comment]
On a Delta the jerk values apply to the movement of the steppers at the towers, and they should all be the same value.

**Comment by FN5969** [comment]
But actually it's not doing it, And change only A and B tower. I did some crappy code to fix this problem, but i do not wont show it here (too crappy and fit only delta)
