### ISSUE TITLE
[BUG] error: 'STATUS_BED_X' was not declared in this scope; did you mean 'STATUS_FAN_X' when defining STATUS_HEAT_PERCENT

### ISSUE THREAD

**Issue by elpeter25** [MarlinFirmware/Marlin#18666]
**Marlin Version: 2.0.5.4**

### Bug Description

When uncommenting to define STATUS_HEAT_PERCENT following error appears at compiling time:

```
Marlin\src\lcd\dogm\status_screen_DOGM.cpp: In function 'void _draw_bed_status(bool)':
Marlin\src\lcd\dogm\status_screen_DOGM.cpp:253:30: error: 'STATUS_BED_X' was not declared in this scope; did you mean 'STATUS_FAN_X'?
  253 |           const uint8_t bx = STATUS_BED_X + STATUS_BED_WIDTH;
      |                              ^~~~~~~~~~~~
      |                              STATUS_FAN_X

Compiling .pio\build\LPC1768\src\src\lcd\extui\lib\dgus\DGUSDisplay.cpp.o
*** [.pio\build\LPC1768\src\src\lcd\dogm\status_screen_DOGM.cpp.o] Error 1
```

### My Configurations

[MarlinBug.zip](https://github.com/MarlinFirmware/Marlin/files/4926301/MarlinBug.zip)

### Steps to Reproduce

1. [First Step]
Uncomment line 1287 in Configuration_adv.h:
  //#define STATUS_HEAT_PERCENT       // Show heating in a progress bar
2. [Second Step]
Compile

**Expected behavior:**
Compilation OK

**Actual behavior:**
Compliation error

Thanks so much for making Marlin possible :)

**Comment by GMagician** [comment]
Try with bugfix

**Comment by GhostlyCrowd** [comment]
I use #define STATUS_HEAT_PERCENT on the latest bug fix and this is not an issue, can you try the latest bug fix? if it fixes the issue, this can be closed if it is still there for you, post your configs for the latest bug fix.

**Comment by GMagician** [comment]
Use bugfix but you have to update your configuration files.

Not sure if  SPEAKER is a valid option for your cnf but it seems it generate a compiler error

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
