### ISSUE TITLE
[BUG] Machine doesn't home x when G28 is issued. Debug data contains lots of non ASCII characters

### ISSUE THREAD

**Issue by Louis-Cypher** [MarlinFirmware/Marlin#18663]
### Bug Description

After updating 2.0.x to the most recent version (pulled yesterday 2020-07-15) homing appears to be broken. Issuing G28 results in homing y, then moving x about 30mm in the wrong direction and then homing x (resulting in the probe being somwhere but very likely not over my (pretty small) bed. 

Homing only the X Axis results in the x- axis moving to the wrong direction (-x) for about 10 mm each time I iniate a X- Axis homing on the LCD.

Moving the axis using the controller proves that my coordinates are correct.

The output of debugging looks pretty scrambled and isn't helpful at all (at least to me).

I didn't change any parameters besides x endstop now being at x max rather than x min. So I changed the endstop to 

```
//#define USE_XMIN_PLUG
#define USE_XMAX_PLUG
//#define USE_YMIN_PLUG
#define USE_YMAX_PLUG
#define USE_ZMIN_PLUG
//#define USE_ZMAX_PLUG
```
And the homing directions to 
```
#define X_HOME_DIR 1
#define Y_HOME_DIR 1
#define Z_HOME_DIR -1
```
[marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4925923/marlin.zip)
[marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4925927/marlin.zip)

### My Configurations

**Required:** Please find below Configuration Configuration_adv and log file copy pasted from Arduino Serial Monitor

### Steps to Reproduce

1. Acitivate level debugging
2. Set debugging level to max
3. Press autohome or send G28

**Expected behavior:** Homing sequence performed. Debugging data gives meanginful output

**Actual behavior:** x is not homed properly. Debugging output contains a lot of non ascii characters. No meaningful log data.

#### Additional Information
I did not fully understand why there is a homing direction is needed. If the endstop is only on one end of the axis (that's why it is called endstop ;-)) as the case for 90% of the printers it is obvious in which direction the printer should home.

**Comment by Louis-Cypher** [comment]
Checked wiring. Wiring OK.

**Comment by Louis-Cypher** [comment]
Got it. The endstop was inverted. Hence, homing immediately finds an endstop and hence moves to the predefined homeposition. Debugging output still is scrambled. I personally think that firmware could detect that an endstop is active all the time. Closing anyways since this is not the topic of the issue

**Comment by thinkyhead** [comment]
> I personally think…

Try the new `DETECT_BROKEN_ENDSTOP` feature.

**Comment by Louis-Cypher** [comment]
Thanks! I'll do
