### ISSUE TITLE
[FR] Lock-Screen - not blocking g-codes - just preventing leaving

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#18661]
When using screens with their own processor, having a Marlin emulation mode and having an encoder and all (2-3) cables are connected and a matching display is defined in Marlin,
editing values in TFT-mode with the endcoder causes random actions,
because the encoder is connected to the displays processor and the processor Marlin runs on, in parallel.

When the display is running in its native mode it could send a g-code to send Marlins menus into the lock-screen. Only (randomly) selecting the right number, or the unlock-g-code will let Marlin leave the lock-screen. Random encoder-inputs will not cause random Marlin reactions over the menus because not leaving that screen. But **in contrast** to the lockscreen-feature where is currently worked on (#18399) this extension should **not block g-code** so values can be purposely be edited over the TFT.
When entering Marlin-mode the TFT could send the unlock-g-code, when entering the TFT-mode the lock-g-code. If something goes wrong Marlin can be unlocked by the unlock-code.

Reference: [When the encoder adjusts the fan speed, the fan speed and print speed are changed together 757](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/757)

**Comment by thinkyhead** [comment]
What can we do to determine which mode a TFT is currently in?

**Comment by AnHardt** [comment]
Absolutely nothing.
The TFT has to explicitly tell us by sending the lock/unlock-g-codes.
A chicken egg problem.

**Comment by Tygrys-1** [comment]
There should also be the escape from the console lock, i.e. very long key press.
