### ISSUE TITLE
[BUG] The SD card on the LCD FYSETC_MINI_12864 screen cannot be read on the SKR Pro V1.1 motherboard

### ISSUE THREAD

**Issue by yangwenxiong** [MarlinFirmware/Marlin#18671]
### Bug Description
The SD card on the LCD FYSETC_Mini12864 screen cannot be read on the SKR Pro V1.1 motherboard,
SD card init is OK ，But can not read SD content, I guess ,this is a Bug.

### Steps to Reproduce

1. #define FYSETC_MINI_12864_1_2  // Configration.h
2. #define RGB_LED                           //Configration.h
3. #define LED_CONTROL_MENU     //Configration_adv.h

**Expected behavior:** 
   Can read SD content
**Actual behavior:** 
   Can not read SD content
#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by yangwenxiong** [comment]
****
![IMG_20200716_144958](https://user-images.githubusercontent.com/46896566/87637009-322a7b00-c774-11ea-8c33-fdc58fcfd91c.jpg)
![IMG_20200716_145006](https://user-images.githubusercontent.com/46896566/87637075-4a9a9580-c774-11ea-915b-6dab2f0a231a.jpg)
![IMG_20200716_145009](https://user-images.githubusercontent.com/46896566/87637095-4ff7e000-c774-11ea-910b-a8fabd5de922.jpg)

**Comment by ellensp** [comment]
In your pins files is "#define SDCARD_CONNECTION                  LCD"  but if you set this elsewhere the other definition takes precedence. make sure SDCARD_CONNECTION its disabled in Configuration_adv.h

**Comment by yangwenxiong** [comment]
> In your pins files is "#define SDCARD_CONNECTION LCD" but if you set this elsewhere the other definition takes precedence. make sure SDCARD_CONNECTION its disabled in Configuration_adv.h

Hi,The setup you're talking about I'm already disabled

**Comment by yangwenxiong** [comment]
> In your pins files is "#define SDCARD_CONNECTION LCD" but if you set this elsewhere the other definition takes precedence. make sure SDCARD_CONNECTION its disabled in Configuration_adv.h

It is possible to read SD CARDS normally on SKR 1.3, I have tried

**Comment by yangwenxiong** [comment]
GTR V1.0 only displays the boot screen for about 30 seconds and then no more

**Comment by sl1pkn07** [comment]
sorry for the offtopic, but strange you say about fysetc lcd and in the lcd you show in the pictures is a bigtreetech unit (link please?)

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by yangwenxiong** [comment]
> Configurations, please
> Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
> requested in the Issue template) and drop them into your next reply.
> We'll check them over and see if anything is amiss.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4975011/Marlin.zip)

**Comment by yangwenxiong** [comment]
> Configurations, please
> Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
> requested in the Issue template) and drop them into your next reply.
> We'll check them over and see if anything is amiss.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4975036/Marlin.zip)

**Comment by yangwenxiong** [comment]
The latest version 2.0.6 appears to read the card, but GTRV1.0 does not display

**Comment by sjasonsmith** [comment]
I tested on my SKR Pro and it was fine, but as @yangwenxiong said things were very messed up on the GTR.

I've added some GTR changes to a PR I already had open on the SKR Pro. I can now choose in `Configuration_adv.h` whether to use the SD on the display or onboard and they both seem to work properly.

#19047

**Comment by sjasonsmith** [comment]
@yangwenxiong based on testing by myself or others I am assuming this is now resolved on both the SKR Pro and the GTR.
