### ISSUE TITLE
[BUG] G38.2 Not Reaching Target

### ISSUE THREAD

**Issue by dotdash32** [MarlinFirmware/Marlin#18685]
### Bug Description

G38.2 does not trigger properly when compiled.  When called from terminal, the error is `Error:Failed to reach target`.  When testing with an `M119`, only X, Y, and Z show up.   I had done some modifications in the past to get this concern before, and a Z Min probe showed up and both probing (G30 and G38.2) worked.

On updating to Bugfix branch, Z min probe disappears from M119, and initially G30 worked for single bed probe.  Doing some debugging, in the past I have been able to get around this by forcefully defining `Z_MIN_PROBE_PIN` in `config.h`, but my new board has this defined as another pin.  I don't want to mess with the pins file, so I tried to do a new preprocessing conditional, but it doesn't override the pins config well.

### My Configurations

[config1.zip](https://github.com/MarlinFirmware/Marlin/files/4940731/config1.zip)

Most of my configurations are focused in the Probing section.

### Steps to Reproduce

1. Add nozzle probe with microswitch wired in parallel to Z endstop, and invert the endstop.
2. Define Z probe
3. Try G38.2 from terminal.

**Expected behavior:** 

G38.2 probes the bed and does not throw an error.

**Actual behavior:** 

Probing throws an error when the bed touches off, when the switch triggers.  G30 sometimes does not actuate at all, and an acknowledge is sent but no motion is issued.

#### Additional Information

I've been trying to debug, and I think the issue is with the way `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN` is handled, but I can't quite figure out where the conditionals that govern this reside.

**Comment by sjasonsmith** [comment]
Perhaps this is related to #16129, although I'm not sure it's actually a duplicate.
