### ISSUE TITLE
[BUG] Ender3 V2 Printer hangs if menu is operated during print

### ISSUE THREAD

**Issue by fleek** [MarlinFirmware/Marlin#18686]
### Bug Description

The printer will hang during a print when the controller is being operated.

### My Configurations

[Marlin-bugfix-2.0.x-Ender3V2-BLTouchOn5Pin-18Jul2020.zip](https://github.com/MarlinFirmware/Marlin/files/4941029/Marlin-bugfix-2.0.x-Ender3V2-BLTouchOn5Pin-18Jul2020.zip)

### Steps to Reproduce

1. Select a gcode file from SD card.
2. Wait for it to start printing.
3. Select Tune on controller and the after that choose the back option to go back to main menu.
4. Printer hangs, stops printing and no response on the controller, serial communication refused.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by thinkyhead** [comment]
I don't doubt that this could still be a problem. The DWIN implementation is very rough. The code for this display will be getting a big overhaul soon, and then we'll see whether issues like this still exist.
