### ISSUE TITLE
[BUG] G29 Not centered on the bed 

### ISSUE THREAD

**Issue by temakitua** [MarlinFirmware/Marlin#18690]
Hello,

I have some troubles with the g29 feature.
It looks like the feature doesn't get the bed size and the probe offset (from extruder) correctly.

the fact is whatever the margin edge set, the probe will move the same distance between to palpation spot. 
I mean, my bed siez is 235x235 (X,Y). If I put a margin edge of 10, ths first spot should be 10x10 , the second should be 117.5 x 10 and the third should be 225x10 but it reality i get something like this : 
1st spot = 10x10
2nd = 100 x 10
3rd = 190 x10 

[Marlin-bugfix-2.0.x (2).zip](https://github.com/MarlinFirmware/Marlin/files/4941373/Marlin-bugfix-2.0.x.2.zip)

Here a liltre shematic to show you the situation :
![image](https://user-images.githubusercontent.com/68443657/87849139-7b024100-c8e6-11ea-8d23-71764d7eb02a.png)

Already tried to set it up with but it allow me to recentered g29 but took too much margin above the edge :

#if PROBE_SELECTED && !IS_KINEMATIC
  #define PROBING_MARGIN_LEFT (46 + PROBING_MARGIN)
  #define PROBING_MARGIN_RIGHT (PROBING_MARGIN)
  #define PROBING_MARGIN_FRONT (1 + PROBING_MARGIN)
  #define PROBING_MARGIN_BACK (PROBING_MARGIN)
#endif

Thanks guys for you help.

**Comment by thisiskeithb** [comment]
Does your nozzle home off the bed? You have both `X_MIN_POS` and `Y_MIN_POS` set to `0` in your config.

**Comment by ghost** [comment]
This is not a bug. I had the same problem as you, to fix it I had to increase the probing_margin. Try Increasing it to 50 and see if then probes the center of the bed. I've noticed that you can run out of x travel since the probe in your case is 46mm to the left and before you can get the probe to the edges of the bed you reach your x bed size. To accommodate for that it looks like marlin shrinks the probing area to where it thinks it will be able to probe. By increasing the probing_margin it should make a smaller centered box that can probe the center. I made the changes to your firmware and attached it below. Hope this helps.

[Marlin-bugfix-2.0.x new probe margin.zip](https://github.com/MarlinFirmware/Marlin/files/4942143/Marlin-bugfix-2.0.x.new.probe.margin.zip)

**Comment by temakitua** [comment]
> Does your nozzle home off the bed? You have both `X_MIN_POS` and `Y_MIN_POS` set to `0` in your config.

Hey, when I am homing, my probe is centered. but the nozzle is not centered (X,Y offset) that is normal for me.

**Comment by temakitua** [comment]
> I had the same problem as you, to fix it I had to increase the probing_margin. Try Increasing it to 50 and see if then probes the center of the bed. I've noticed that you can run out of x travel since the probe in your case is 46mm to the left and before you can get the probe to the edges of the bed you reach your x bed size. To accommodate for that it looks like marlin shrinks the probing area to where it thinks it will be able to probe. By increasing the probing_margin it should make a smaller centered box that can probe the center. I made the changes to your firmware and attached it below. Hope this helps.
> 
> [Marlin-bugfix-2.0.x new probe margin.zip](https://github.com/MarlinFirmware/Marlin/files/4942143/Marlin-bugfix-2.0.x.new.probe.margin.zip)

Yes I discovered the same thing, but it doesn't really fix the problem because now the g29 mesh is centered but don"t calculate on the whole bed. 
May be should try to modify the x_min_pos as suggered by @cr20-123

**Comment by ghost** [comment]
> 
> 
> > I had the same problem as you, to fix it I had to increase the probing_margin. Try Increasing it to 50 and see if then probes the center of the bed. I've noticed that you can run out of x travel since the probe in your case is 46mm to the left and before you can get the probe to the edges of the bed you reach your x bed size. To accommodate for that it looks like marlin shrinks the probing area to where it thinks it will be able to probe. By increasing the probing_margin it should make a smaller centered box that can probe the center. I made the changes to your firmware and attached it below. Hope this helps.
> > [Marlin-bugfix-2.0.x new probe margin.zip](https://github.com/MarlinFirmware/Marlin/files/4942143/Marlin-bugfix-2.0.x.new.probe.margin.zip)
> 
> Yes I discovered the same thing, but it doesn't really fix the problem because now the g29 mesh is centered but don"t calculate on the whole bed.
> May be should try to modify the x_min_pos as suggered by @cr20-123

Try uncommenting EXTRAPOLATE_BEYOND_GRID

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
