### ISSUE TITLE
[BUG] Encoder wheel can miss step when reversing direction

### ISSUE THREAD

**Issue by marknn3** [MarlinFirmware/Marlin#18693]
### Bug Description

When reversing the encoder wheel direction, the first step can be missed.
A user will perceive this as unreliable input: a rotation click without any update.

### Configurations

This affects all configurations with ENCODER_PULSES_PER_STEP > 1

### Steps to Reproduce

Move the encoder wheel fast or slow in one direction. Stop and reverse direction by 1 click.
The first reverse click is randomly ignored.

**Comment by qwewer0** [comment]
I might have this too, on Ender 3 original (12864?) display, or having an unreliable rotary encoder.

**Comment by GMagician** [comment]
I saw it but never considered a bug, but yes it's not normal. I'll test your PR

**Comment by thinkyhead** [comment]
I see that `encoderDiff = 0` only happens when `encoderPastThreshold`. See if it helps to move this line down after the condition. This would be line 950 in the current code. That will prevent it from having any residual value in-between screen updates.

**Comment by boelle** [comment]
@marknn3 i see you PR is merged, did that help?

**Comment by GMagician** [comment]
From some test I did it seems to solve issue

**Comment by sjasonsmith** [comment]
@marknn3 based on testing from @GMagician I'm closing this issue, with the assumption that your merged change fixes it.

If that assumption ends up being correct, please let us know.
