### ISSUE TITLE
[BUG] G33 P10 produces "Unknown command" on Delta [Marlin 2.0.5.4]

### ISSUE THREAD

**Issue by Ohmarinus** [MarlinFirmware/Marlin#18722]
### Bug Description

After upgrading to Marlin 2.0.5.4 I am no longer able to use G33 for Delta Auto Calibration. This worked on 2.0.5.3
Also, the EEPROM doesn't show it's values any longer when connecting to the machine with a host.

### My Configurations

[M2054_mar.zip](https://github.com/MarlinFirmware/Marlin/files/4947238/M2054_mar.zip)

### Steps to Reproduce

I have used the Delta example config that was downloaded from Github
1. Send: G33 P10

**Expected behavior:**

Delta Auto Calibration

**Actual behavior:** 

SENDING:G33 P10
echo:Unknown command: "G33 P10"

#### Additional Information

SKR 1.3
Piezo leveling (confirmed working)

**Comment by GMagician** [comment]
g3 needs DELTA_AUTO_CALIBRATION

>   // uncomment to add G33 Delta Auto-Calibration (Enable EEPROM_SETTINGS to store results)
>  //#define DELTA_AUTO_CALIBRATION

**Comment by ellensp** [comment]
The settings your referring to are only displayed on SERIAL_PORT not SERIAL_PORT_2 and you have SERIAL_PORT connected to a touch screen

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
