### ISSUE TITLE
General LCD support does not compile

### ISSUE THREAD

**Issue by ghpicard** [MarlinFirmware/Marlin#1873]
When trying to compile Marlin with an LCD only panel (16x2), no encoder, no SD Card, which would correspond to only #define ULTRA_LCD not commented, I get the following error:

```
ultralcd.cpp: In function ‘void lcd_goto_menu(void (*)(), uint32_t, bool)’:
ultralcd.cpp:254: error: ‘encoderPosition’ was not declared in this scope
ultralcd.cpp:255: error: ‘lcd_quick_feedback’ was not declared in this scope
```

**Comment by AnHardt** [comment]
#1877 will fix this.

**Comment by ghpicard** [comment]
Compilation is now OK. Tomorrow will upload the code to the printer and check how it works before closing the issue. Thanks!

**Comment by ghpicard** [comment]
Just checked it in the printer (Reprap Prusa i3 with an Arduino Mega 2560 and Ramps 1.4) and it works fine.
Bug closed! :)
