### ISSUE TITLE
[FR] Purge after filament load

### ISSUE THREAD

**Issue by Thijsvanzwam** [MarlinFirmware/Marlin#18747]
Could it possible to have the nozzle do a purge of filament somewhere in a corner and then resume printing instead of doing it on the print it self? 
It now poops a blob of pla at the spot it resumes after a filament change which gives a bump in the print.
it would be nice to just do a small introline in the right corner (left is most used for introline at print start)and then resume the print.

**Comment by Liamnerf** [comment]
this already exists. you need to have advanced pause and nozzle park enabled.

**Comment by Thijsvanzwam** [comment]
I have both enabled. 
What is does is that it continues the print by moving the nozzle to the point it stopped and purges the filament there before continuing the print movements.
I have FILAMENT_CHANGE_FAST_LOAD_LENGTH and ADVANCED_PAUSE_PURGE_LENGTH   both set to 0

**Comment by Liamnerf** [comment]
> I have both enabled.
> What is does is that it continues the print by moving the nozzle to the point it stopped and purges the filament there before continuing the print movements.
> I have FILAMENT_CHANGE_FAST_LOAD_LENGTH and ADVANCED_PAUSE_PURGE_LENGTH both set to 0

Those values are unrelated, you need to have resume prime (or prime on resume, whatever it’s called) set to 0.

**Comment by LittleNyanCat** [comment]
This feature already exists, I use it. Search for #define NOZZLE_PARK_POINT in your Configuration.h. You can define the X & Y positions as well as how much to raise the Z axis.

**Comment by qwewer0** [comment]
I think this can be closed, as we can purge on the parking spot.

**Comment by slowbro** [comment]
Agreed, this is already a feature & can be closed.

**Comment by thisiskeithb** [comment]
As noted above, this feature exists.

Simply enable `NOZZLE_PARK_FEATURE ` and define your preferred `NOZZLE_PARK_POINT` (off the build area for example) in order to avoid purging directly on your print.
