### ISSUE TITLE
[BUG] PID tuning works with external mosfet and re-assigned pins, but temperature thereafter does not rise

### ISSUE THREAD

**Issue by reefwarrior** [MarlinFirmware/Marlin#18755]
### My Configurations

Included the .zip file. --- I have a MKS GEN 1.4 and have remapped the pins used to 'D7' as the original 'D8' mosfet has blown. I am using an external mosfet connected to D7.

### Steps to Reproduce

1. M303 E-1 C8 S60
2. When step 1 has finished, and all PID values have been saved/loaded again, then step 3.
3. M140 S60

**Expected behavior:** Heat bed is supposed to heat up.

**Actual behavior:** Heat bed does not heat up. In the M303, it heated up and was calibrated. After that it does not heat up.

#### Additional Information

The LED next to the mosfet used for D7, flashes faint and EXTREMELY fast and faint when doing the S140. For the M303 it flashes slower and brighter.
[configuration_files.zip](https://github.com/MarlinFirmware/Marlin/files/4966005/configuration_files.zip)

**Comment by oldman4U** [comment]
Hi.

You are not the first to report issues with PID tuning of the bed and i would recommend not to use PID for the bed at all. It is not worth, because the bed is able to keep the temp. stable without it.

My 2 cents

**Comment by reefwarrior** [comment]
Hi

My problem is not with the PID tuning of the bed - my issue is that the PID tuning completes without an issue, however, if I issue the M140 command to heat the bed, then it does not heat up at all.

**Comment by oldman4U** [comment]
It likely does not heat, because the values from the PID tuning are bad. Turn PID for the bed off and try to heat it again.

**Comment by reefwarrior** [comment]
Just tried, problem still persists.

**Comment by oldman4U** [comment]
Ok. Sorry then i can not help you.

reefwarrior <notifications@github.com> schrieb am Do. 23. Juli 2020 um
16:48:

**Comment by reefwarrior** [comment]
OK, problem has been resolved between V1.1.9 and the latest V2.0 - flashed, and it is running! :)
