### ISSUE TITLE
TFT 35 and BTT SKR Mini E3 Dip issue

### ISSUE THREAD

**Issue by KyleLampkin** [MarlinFirmware/Marlin#18773]
After having compiling issues with this board, which thanks to ellesp are fixed, now the TFT does not connect in touchscreen mode but works fine in LCD12864 simulator mode and this is with CR-10 StockDisplay in configuration.h.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4974590/Configuration.zip)

**Comment by ellensp** [comment]
From what I read you need #define SERIAL_PORT 2 not #define SERIAL_PORT 1

**Comment by KyleLampkin** [comment]
Thanks again  ellensp, I thought that I already tried that but I guess not since it worked like a charm.
