### ISSUE TITLE
[FR] New symbol for Feedrate in LCD

### ISSUE THREAD

**Issue by positron96** [MarlinFirmware/Marlin#18788]
Am I the only one who finds "Fr" icon not very beautiful?
In my spare time, I've created a new symbol for feedrate, looks like "speed" or "fast forward" icon on consumer electronics. I believe it represents what changing feedrate percentage does - speeds all things up or slows them all down. 
If the community is interested, I can provide a pull request with changes to font.
<img src="https://user-images.githubusercontent.com/2095278/88476595-bb576400-cf63-11ea-92e9-3e0b49816f79.jpg" width=300>

**Comment by SparkyDan555** [comment]
Nice work! Looks much better. Would love to see this implemented. Would probably prevent some confusion with "Flow Rate" for some beginners too!

**Comment by sjasonsmith** [comment]
I was skeptical, but after I see if I like it. I agree that it reduced "Flow Rate" confusion. It is also language-agnostic.
I suggest you go ahead and post the pull request. The worst that will happen is you learn whether people like it!

**Comment by sjasonsmith** [comment]
Looks like this is done.
