### ISSUE TITLE
[BUG] 2.0.6 ABL_BILINEAR_SUBDIVISION not calculating all of the points, causes nozzle to very slowly crash into bed

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#18797]
### Bug Description

After updating to 2.0.6 from 2.0.5.2 the nozzle crashes into the bed after doing the G29. The feature worked on 2.0.5.2 without any issues.

### My Configurations
[Leveling data.txt](https://github.com/MarlinFirmware/Marlin/files/4990208/Leveling.data.txt)

### Steps to Reproduce

1. Turn on abl_bilinear_subdivision

2. run a print

3. After the G29 finishes watch the nozzle move to the left slightly then stop and very slowly go down

**Expected behavior:** [What you expect to happen]
The nozzle to move over to the far left and do a purge line

**Actual behavior:** [What actually happens]
The nozzle moves a little to the left and goes slowly into the bed

**Comment by ilium007** [comment]
I can't see where in your start gcode you actually load the UBL mesh using an M420 to then perform the G29 on?? If I ever tried a G29 without loading the mesh slot the print head would crash into the bed.

This is the line I used in my start gcode for UBL mesh levelling:
`M420 S1 Z10 ; enable mesh levelling and load slot 1, 10mm fade height`

**Comment by ghost** [comment]
I am using bilinear not UBL

**Comment by ilium007** [comment]
You still have to enable bed leveling with the Bilinear method - see https://marlinfw.org/docs/gcode/M420.html

If you do not issue an M420 before the G29 the print head will crash into bed.

Again - this is my start gcode (I use bilinear by the way):

```
; Restore Bed Levelling
M117 Bed Levelling...
M420 S1 Z10 ; enable, set fade height 10mm
G0 X0 Y15 F3000 ; return to origin
```

If you enable bed leveling prior to G29 the print head should not crash into the bed.

**Comment by cr20-123** [comment]
I appreciate you trying to help, but you do not need to enable leveling before a G29. When you do a G29 it enables leveling. As I said in my original post it is something in Marlin 2.0.6 that is causing it. I have used many versions of marlin before it with the same start G-Code and I have never had any problems.

**Comment by fleek** [comment]
Not sure why you have so many G28 in your gcode file.  But G28 invalidates all offsets and bed leveling.  Switching off motors also invalidate the bed leveling.  So your M851 will not work at all because it is not saved into EEPROM.

You can simply your start up script through M851, M500 which I don't recommend because it will wear out your EEPROM.  Do a G29 separately and then do a M500, and then in your script you only need G28 followed by M420 S1 and start printing.

**Comment by cr20-123** [comment]
I just added the start G-Code provided by TH3D which mine is based on and there is no M420 S1 in it.

**Comment by ghost** [comment]
**Update**: ABL_BILINEAR_SUBDIVISION is causing the problem. It is not properly calculating some of the points which is causing the bed leveling to act weird.
[Leveling data.txt](https://github.com/MarlinFirmware/Marlin/files/4990195/Leveling.data.txt)

**Comment by ghost** [comment]
This is still an issue
