### ISSUE TITLE
[BUG] Confusing and Ambigious description of NOZZLE_TO_PROBE_OFFSET 

### ISSUE THREAD

**Issue by thierryzoller** [MarlinFirmware/Marlin#18791]
The (0,0) Coordinates are suggesting the Probe Somehow needs to be set as relative to Bed Origin. In reality, it needs to be set relative to the Nozzle position. Whatever the reasons for (0,0)

Suggest doing the following : 

1. Removing "(0,0)"  - or explain the purpose it is indicated
2. Add Text hat the character "O" is supposed to mean (Bed Origin) 

```
`* Z Probe to nozzle (X,Y) offset, relative to (0, 0).
*
* In the following example the X and Y offsets are both positive:
*
*   #define NOZZLE_TO_PROBE_OFFSET { 10, 10, 0 }
*
*     +-- BACK ---+
*     |           |
*   L |    (+) P  | R <-- probe (20,20)
*   E |           | I
*   F | (-) N (+) | G <-- nozzle (10,10)
*   T |           | H
*     |    (-)    | T
*     |           |
*     O-- FRONT --+
*   (0,0)`
```

**Comment by GMagician** [comment]
@thierryzoller probe offset is relative to nozzle. If you read what is written in example you will se that taken 0,0 as bed origin and N as nozzle positionated at (10,10), probe in that situation is at 20,20. You have to write 10,10 in parameter...then relative to nozzle

**Comment by sjasonsmith** [comment]
@thierryzoller since you have thought about how you think this should change, why don’t you post a pull request with the edits?

I can’t promise you the change will be accepted, but that would be more productive than debating it here.

**Comment by GMagician** [comment]
To be more honest 0,0 is origin. When nozzle is over such point, its coordinates are 0,0. Usually it is also the edge of the "printable area". In config example you may see the 3 letters O, N, P, they are origin, nozzle and probe.

And as told you in #18783 best approch to "cases" like this are:

    MarlinFW.org Marlin Documentation
    RepRap.org Marlin Forum
    Tom's 3D Forums
    Facebook Group "Marlin Firmware"
    Facebook Group "Marlin Firmware for 3D Printers"
    Marlin Configuration on YouTube
    Marlin Discord server. Join link: https://discord.gg/n5NJ59y

> After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.

**Comment by thierryzoller** [comment]
> @thierryzoller since you have thought about how you think this should change, why don’t you post a pull request with the dits?
1. I don't know all the use cases and scenarios that would have to be respected to make it clearer.
2. Never done a pull request my entire life

**Comment by thierryzoller** [comment]
> @thierryzoller probe offset is relative to nozzle. If you read what is written in example you will se that taken 0,0 as bed origin and N as nozzle positionated at (10,10), probe in that situation is at 20,20. You have to write 10,10 in parameter...then relative to nozzle

Are you actually reading the issue and the config file? Let me help you by repeating it here in a single line it says " Z Probe to nozzle (X,Y) **### _offset, relative to (0, 0)_**." <-- Do you see the Problem?  It's not relative to 0,0 (which on the graph is indicated as being bed origin)  it is relative to NOZZLE.  And that's just one thing that is ambiguous.

This my second time opening an issue on this - may I ask everyone to focus on productively discuss the issue or not post at all.

**Comment by thierryzoller** [comment]
I'll try to post an improvement here we can discuss, give me a bit of time.

**Comment by sjasonsmith** [comment]
> Never done a pull request my entire life

@thierryzoller none of us had ever done a pull request prior our first one.

As I know you have observed, it isn't always easy to find people with time available to focus on your issues. There is a lot of power in fixing them yourself then sharing to help others in the future.

There is no single proper way to do it, but one method is documented in this guide:
https://marlinfw.org/docs/development/getting_started_pull_requests.html

**Comment by GMagician** [comment]
@thierryzoller 

> Are you actually reading the issue and the config file? Let me help you by repeating it here in a single line it says " Z Probe to nozzle (X,Y) ### offset, relative to (0, 0)." <-- Do you see the Problem?

oh yeah now I got it

**Comment by GMagician** [comment]
@thierryzoller please check PR if now is clear

**Comment by JoeTundra** [comment]
Good day. I'm a newb boomer trying to figure out the basics of 3d printing. I have an ender 3 V2, and got a not supported bed level sensor and thought I'd try and get it to work. That got me here.

I am another one who found the Nozzle to Probe offset instructions confusing. I took a stab at clarifying it. 

I think most confusion might be prevented simply by not having the nozzle to probe relative position, exactly the same as the 0,0 bed to nozzle relative position, in the example..

I think easiest solution is to simply start the instructions with the nozzle in the 0,0 position on the bed. That way, the only possible variable, is the probe. 

Have a good day.

**Comment by GMagician** [comment]
@JoeTundra have you read new config description? check in bugfix and give feedback

**Comment by JoeTundra** [comment]
@GMagician I have not yet. I will check it out now. Thanks. 

I just checked it out. It's better for sure.  Here's something I clanked out when I was trying to explain it to a friend.

[Nozzle to Probe example.txt](https://github.com/MarlinFirmware/Marlin/files/5004040/Nozzle.to.Probe.example.txt)

**Comment by boelle** [comment]
@thierryzoller PR #18828 is merged and have made it more clear, will close this as fixed, we can always reopen if its not clear enough.

**Comment by thierryzoller** [comment]
Thank you @GMagician, together with the explanations I think I would have understood it directly without playing around first.
