### ISSUE TITLE
[FR] Update MKS Robin E3D Pins

### ISSUE THREAD

**Issue by ils15** [MarlinFirmware/Marlin#18804]
Please Update Pins definition of MKS Robin E3D_E3 in latest stable version

[E3D_E3_pins.zip](https://github.com/MarlinFirmware/Marlin/files/4981725/E3D_E3_pins.zip)

**Comment by thisiskeithb** [comment]
Both boards share many of the same pins, so they have been consolidated to make updating them easier:

- [pins_MKS_ROBIN_E3.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_E3.h)
- [pins_MKS_ROBIN_E3D.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_E3D.h)
- [pins_MKS_ROBIN_E3_common.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_E3_common.h)
