### ISSUE TITLE
Request: All calibration menu need to put into prepare:calibration

### ISSUE THREAD

**Issue by lcfm1** [MarlinFirmware/Marlin#1880]
What you think? Too many menu in different places

**Comment by thinkyhead** [comment]
As calibration options multiply, a new **Calibration** menu - probably next to **Prepare** - might be added. In some configurations that menu might only have one or two items, so we want to ensure it's comprehensive. Examples of items for a Calibration sub-menu include: heater hysteresis calibration, adjusting steps-per-mm for the extruder, and bed leveling options.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
