### ISSUE TITLE
[BUG] 2.0.6 Boot screen shows "Marlin 2.0.5.4"

### ISSUE THREAD

**Issue by salacpavel** [MarlinFirmware/Marlin#18807]
### Bug Description

As a title says

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

Download 2.0.6 package from https://marlinfw.org/meta/download/
Compile and flash
Power on

**Expected behavior:** 
Default boot screen should report Marlin firmware 2.0.6

**Actual behavior:**
Reports 2.0.5.4 instead

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4981884/Marlin.zip)

**Comment by ellensp** [comment]
That is not Marlin 2.0.6
You can only download marlin 2.0.6 via GIT or from this link https://github.com/MarlinFirmware/Marlin/archive/2.0.6.zip
2.0.x.zip has not been updated to 2.0.6 yet.

**Comment by boelle** [comment]
could we close this one allready?

**Comment by ellensp** [comment]
I was going to give them 30 mins to try it and respond.

**Comment by salacpavel** [comment]
I have downloaded Marlin from https://marlinfw.org/meta/download/
It refers to 2.0.6 right there:
![image](https://user-images.githubusercontent.com/36787486/88540949-3b3d0700-d014-11ea-8b6e-3852d7f5bbbe.png)
Indeed, configuration files are plain copy & paste from my 2.0.5.3 build - but that should not make a difference here

**Comment by boelle** [comment]
I'm tempted to agree with @salacpavel here

i use bugfix 2.0.x so i have never cared much for version numbers

**Comment by salacpavel** [comment]
In any case, i.e. version.h file content is different between versions downloaded from Marlinfw.org download page and the package linked by @ellensp .
My guess is marlinfw download page has only updated number, but dowload link still points to a previous version.

**Comment by ellensp** [comment]
as I already stated 2.0.x.zip has not been updated to 2.0.6 yet. That page links through to 2.0.x.zip
I have submitted a PR to update it, but things take time.
