### ISSUE TITLE
[BUG] (SKR Mini E3 V2.0 Y-Axis)

### ISSUE THREAD

**Issue by SHAXperiment** [MarlinFirmware/Marlin#18831]
### Bug Description

BOARD_BTT_SKR_MINI_E3_V2_0 has Problems with Y-Axis

### My Configurations

Config is here:
https://github.com/SHAXperiment/Marlin-Ender-5-SKR-Mini-E3/tree/master/Marlin-2.0.6

Old Bigtreetech Bugfix Tree Config from is here:
https://github.com/SHAXperiment/Marlin-Ender-5-SKR-Mini-E3/tree/master/MarlinBugfixBTT

### Steps to Reproduce

I have defined everything okay: #define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 800, 93 }
If i try to home the Y-Axis doesn't move enough, if i print a circle it's oval
In bugfix release it was okay

I think it's something with the board settings. I have the problems on every printer with SKR Mini E3 v2.0.
With SKR Mini E3 v1.1 or SKR 1.3, SKR 1.4 and SKR 1.4 Turbo i don't have this issue.

**Comment by thisiskeithb** [comment]
This isn't a bug. Your slave addresses are all 0:

```cpp
#define  X_SLAVE_ADDRESS 0
#define  Y_SLAVE_ADDRESS 0
#define  Z_SLAVE_ADDRESS 0
#define E0_SLAVE_ADDRESS 0
```

They should be:

```cpp
#define  X_SLAVE_ADDRESS 0
#define  Y_SLAVE_ADDRESS 2
#define  Z_SLAVE_ADDRESS 1
#define E0_SLAVE_ADDRESS 3
```

Use the SKR Mini E3 V2 config for comparison: https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3/BigTreeTech%20SKR%20Mini%20E3%202.0

___

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
