### ISSUE TITLE
[BUG] Wrong indication for printer statistic & Service period

### ISSUE THREAD

**Issue by trengtor** [MarlinFirmware/Marlin#18847]
### Bug Description

Wrong indication for printer statistic (2.0.5.3)

![photo_2020-07-29_13-49-44](https://user-images.githubusercontent.com/16775489/88792274-a406b980-d1a3-11ea-8ddd-f2392418e72b.jpg)

![photo_2020-07-29_13-49-50](https://user-images.githubusercontent.com/16775489/88792282-a79a4080-d1a3-11ea-9c59-4bd71df677c1.jpg)

![photo_2020-07-29_13-50-01](https://user-images.githubusercontent.com/16775489/88792287-a9fc9a80-d1a3-11ea-92e9-7b94ecc29cf0.jpg)

Also servise period message dislayed for each ON of printer. Resetting the interval does not help clear this message.

### My Configurations

[For Marlin 2.0.5.3.zip](https://github.com/MarlinFirmware/Marlin/files/4994394/For.Marlin.2.0.5.3.zip)

SKR mini E3 V1.2 & BTT TFT24 V1.1

### Steps to Reproduce

1. Enable in configs

#define PRINTCOUNTER

/**
 * Advanced Print Counter settings
 */
#if ENABLED(PRINTCOUNTER)
  #define SERVICE_WARNING_BUZZES  5
  // Activate up to 3 service interval watchdogs
  #define SERVICE_NAME_1      "Service 100hr"
  #define SERVICE_INTERVAL_1  100 // print hours
  //#define SERVICE_NAME_2      "Service L"
  //#define SERVICE_INTERVAL_2  200 // print hours
  //#define SERVICE_NAME_3      "Service 3"
  //#define SERVICE_INTERVAL_3    1 // print hours
#endif

2. Compile & flash into board

3. Check in 12864 emulation mode

**Comment by ellensp** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by trengtor** [comment]
> Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

Ok, but in some days

**Comment by trengtor** [comment]
> Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

Some problem with compilation. Config files  attached.

![2020-07-29_21-21-28](https://user-images.githubusercontent.com/16775489/88838235-ec44cc80-d1e1-11ea-9e6b-2719767e51d7.jpg)

[Marlin-bugfix-2.0.x configs.zip](https://github.com/MarlinFirmware/Marlin/files/4996720/Marlin-bugfix-2.0.x.configs.zip)
