### ISSUE TITLE
[BUG] Marlin 2.0.6 and Dual X carriage tool change issue.

### ISSUE THREAD

**Issue by Romain3481** [MarlinFirmware/Marlin#18863]
[config.zip](https://github.com/MarlinFirmware/Marlin/files/5002760/config.zip)
### Description

Hi !
Just updated Marlin 2.0.5.4 to 2.0.6, and get an issue with my dual extruder: when tool changing, Extruder1 goes up and park itself (ok), extruder2 comes at the right XY place, but Z don't go down to the piece and print in the air ! I didn't get this issue with my last firmware 2.0.5.4, i uploaded 2.0.5.4 again and that works. What's wrong with the 2.0.6 ? Thank you !
Motherboard BTT GTR V1.0

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by Romain3481** [comment]
[config.zip](https://github.com/MarlinFirmware/Marlin/files/5002763/config.zip)
Sorry, it's done ;) THX

**Comment by boelle** [comment]
@Romain3481 

edit the title, replace [FR] with [BUG]
