### ISSUE TITLE
[BUG]  Nozzle temperature fluctuates despite pid

### ISSUE THREAD

**Issue by Nissal1983** [MarlinFirmware/Marlin#18882]
The temperature of the nozzle fluctuates between 8-11 degrees despite the Pid, ​​which was not the case with 2.0.5.4. Tested on an Anycubic i3 Mega

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
@Nissal1983 please add [BUG] to start of title

**Comment by oneeyepizzaguy404** [comment]
I am having similar issues 

No matter what I do im stuck at a 5c droop when my fans come on tuned with the fans on. 

Printer seems to be ignoring the functional thresh hold as well and you can see it cycle via the led as soon as it starts heating. 

No matter what values i enter via m301 the behavior does not change.

The bed behaves correctly.

50watt heater, silicone sock, skr 1.3 
Official marlin release 2.0.6.

**Comment by Nissal1983** [comment]
My configuration.h and configuration_adv.h
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5010742/Configuration.zip)

**Comment by Nissal1983** [comment]
> I am having similar issues
> 
> No matter what I do im stuck at a 5c droop when my fans come on tuned with the fans on.
> 
> Printer seems to be ignoring the functional thresh hold as well and you can see it cycle via the led as soon as it starts heating.
> 
> No matter what values i enter via m301 the behavior does not change.
> 
> The bed behaves correctly.
> 
> 50watt heater, silicone sock, skr 1.3
> Official marlin release 2.0.6.

you solved the pid problem with you, how and where did you go?

**Comment by oneeyepizzaguy404** [comment]
So my problem was in the pins files if/then statements in the bbt common pins. The exttruder pin p2_04 was also being assigned a parts fan function if you only have one hotend. The sanity check missed this.  So when you called for a m303 the pins would behave like a heater, but when you print they would behave like both.

**Comment by Nissal1983** [comment]
Thank you. i had a similar problem. I'm closing here
