### ISSUE TITLE
Auto Homing not working - help

### ISSUE THREAD

**Issue by bonoboxita** [MarlinFirmware/Marlin#18898]
i've just compiled the new 2.0.6 transferring all the changes i had in 2.0.5 to account for a SKR1.3 and BLTouch setup on a standard Ender 3

Now when i do the home command, the printer check the x min stop, y min stop and then move the head all to the right without stopping in the center and crashing on the right side

I have Z_SAFE_HOMING (as it was activated in 2.0.5)

any idea?

**Comment by ellensp** [comment]
you missed the micro stepping settings in Configuration_adv.h ?

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
