### ISSUE TITLE
avr-gcc: error: CreateProcess: No such file or directory[BUG] (short description)

### ISSUE THREAD

**Issue by flivermo** [MarlinFirmware/Marlin#18924]
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/5028328/Configs.zip)

### Bug Description

When trying to upload the sketch i get the avr-gcc: error: CreateProcess: No such file or directory error.  I Tried several of the fixes I found on here and the only progress i can make is by removing some of the HAL files.  When i remove them everything works expect I am getting an error uploading sketch.  I am a first time user so I apologize if I am just missing something simple.

### My Configurations

Configurations attached

### Steps to Reproduce

1. Attempt to upload the sketch
2. Get error compiling
3. Remove some HAL files (I am new to this and do not know which ones I can remove)
4. Attempt to upload and get error uploading

**Expected behavior:** [What you expect to happen]

I would expect to get something saying it was uploaded successfully and when i restart the board I would prefer to see the boot screen.

**Actual behavior:** [What actually happens]

I get an error and then nothing.  Still have a blue screen.  I have even tried swapping the LCD wires as suggested in other places but no luck.

**Comment by boelle** [comment]
have you tried vscode+platform.io ? arduino ide is not used much anymore and its filled with bugs that cause compiles to fail

**Comment by flivermo** [comment]
I have not but will try to muddle through it tonight.  Are they any instructions available on how to upload to a Rambo 1.4 board or is it pretty self explanatory?

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ellensp** [comment]
the main gotcha with the rambo is "You must connect an external power source to the Heater, Fans, and Logic input for the RAMBo to operate. "   If you just use a usb cable only the usb chip is get power, not the processor.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
