### ISSUE TITLE
Z heigth after homing

### ISSUE THREAD

**Issue by lewiss66** [MarlinFirmware/Marlin#18933]
For info I use only manual nobbe adjustment for the bed and no BL touch. My concern here is I just want the nozzle to be raised at a certain height above the bed after homing that I set in Marlin firmware (2.0) . ex define Z_offset.. or Z_AFTER_HOMING but whatever I try the nozzle height never goes over the bed level after homing.
Any help? thank

**Comment by GMagician** [comment]
### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

**Comment by GMagician** [comment]
Z_AFTER_HOMING works only if Z_HOME_DIR < 0 after z home. But without cnf...

**Comment by boelle** [comment]
@lewiss66 did you read the template???

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by qr-buell** [comment]
i have the sam issue. I use MESH_BED_LEVELING. 

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5041650/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5041651/Configuration_adv.zip)

**Comment by boelle** [comment]
closing as @lewiss66 did not provide the configs that the template requires

we can reopen when they are attached

**Comment by ellensp** [comment]
never mind...  wrong configs from from user.
