### ISSUE TITLE
[BUG] Unusual Compiler Warnings with build #18919

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#18934]
Bug Description: Compiling for LPC1768 in VSCode on Windows 10,  I receive the following Compiler Warnings.  This does not affect may build but may indicate trouble to come for users building for other platforms.  This just showed up with #18919 

Warning! Ignore unknown configuration option `marlin.sdsupport` in section [env:SAMD51_grandcentral_m4]
Warning! Ignore unknown configuration option `marlin.neopixel_led` in section [env:STM32F103RC_meeb]   
Processing LPC1768 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.3.zip; board: nxp_lpc1768; framework: arduino)

My Configurations: 
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5036660/Marlin.zip)

Steps to Reproduce: Compile and observe warnings

Expected behavior: No new warnings

Actual behavior: New warnings

**Comment by thisiskeithb** [comment]
Thanks for the heads up! Resolved in https://github.com/MarlinFirmware/Marlin/pull/18935.
