### ISSUE TITLE
[BUG] ( error when compiling for laser feature)

### ISSUE THREAD

**Issue by annhan** [MarlinFirmware/Marlin#18945]
Hi, I haven't built my firmware with laser control. I am using the ULTRATRONICS board.
My error:: error: "'set_pwm_duty' was not declared in this scope
       set_pwm_duty(pin_t(SPINDLE_LASER_PWM_PIN), ocr ^ SPINDLE_LASER_PWM_OFF);
       ^~~~~~~~~~~~"
i have checked the set_pwm_dutty function just support for the LPC1768 device. Am I right ?
and how can i fix this ?
thank you

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by ellensp** [comment]
comment out SPINDLE_LASER_FREQUENCY   this is only for 8 bit avr and lpc1768

**Comment by ellensp** [comment]
Or manually apply the above PR

**Comment by annhan** [comment]
OK, I don't see a comment line (  Spindle/laser frequency (only on supported HALs: AVR and LPC). This was enabled at default. thank you so much

**Comment by ellensp** [comment]
Pr has been added to bugfix so future users wont fall into 'trap'
