### ISSUE TITLE
[FR] Move the bed forward instead of backward when aborting a print

### ISSUE THREAD

**Issue by tinkerBOY-git** [MarlinFirmware/Marlin#18944]
Just got my new Ender 3 Pro about a week ago and installed Marlin 2.0.6. Works great and i get to tinker more with it. The only issue i have is when I abort a print. The bed moves back instead of moving forward so i can easily remove my aborted prints. Is there any way to do this?

**Comment by thisiskeithb** [comment]
As discussed on Facebook, this feature already exists.

Change `EVENT_GCODE_SD_STOP` from `G28XY` to `G28XY\nG1 Y230 F2000`

This will home X and Y, then move Y to 230.

**Comment by tinkerBOY-git** [comment]
Yes thank you very much!
