### ISSUE TITLE
[BUG] (dual nozzle dual extruder error in codes)

### ISSUE THREAD

**Issue by aliys97** [MarlinFirmware/Marlin#18994]
I have a dual extruder and dual nozzle printer when I want to verify the codes IDE shows below errors

In file included from sketch\MarlinConfig.h:42:0,

                 from sketch\M100_Free_Mem_Chk.cpp:49:

SanityCheck.h:1142:4: error: #error "HEATER_1_PIN not defined for this board."

   #error "HEATER_1_PIN not defined for this board."

    ^~~~~

In file included from sketch\MarlinConfig.h:42:0,

                 from sketch\G26_Mesh_Validation_Tool.cpp:27:

SanityCheck.h:1142:4: error: #error "HEATER_1_PIN not defined for this board."

   #error "HEATER_1_PIN not defined for this board."

    ^~~~~

In file included from sketch\MarlinConfig.h:42:0,

                 from sketch\MarlinSerial.cpp:36:

SanityCheck.h:1142:4: error: #error "HEATER_1_PIN not defined for this board."

   #error "HEATER_1_PIN not defined for this board."

    ^~~~~

In file included from sketch\MarlinConfig.h:42:0,

                 from sketch\Sd2Card.cpp:29:

SanityCheck.h:1142:4: error: #error "HEATER_1_PIN not defined for this board."

   #error "HEATER_1_PIN not defined for this board."

    ^~~~~

In file included from sketch\MarlinConfig.h:42:0,

                 from sketch\Max7219_Debug_LEDs.cpp:38:

SanityCheck.h:1142:4: error: #error "HEATER_1_PIN not defined for this board."

   #error "HEATER_1_PIN not defined for this board."

    ^~~~~

In file included from sketch\MarlinConfig.h:42:0,

                 from sketch\I2CPositionEncoder.cpp:31:

SanityCheck.h:1142:4: error: #error "HEATER_1_PIN not defined for this board."

   #error "HEATER_1_PIN not defined for this board."

    ^~~~~

In file included from sketch\MarlinConfig.h:42:0,

                 from sketch\Marlin.h:35,

                 from sketch\Marlin_main.cpp:257:

SanityCheck.h:1142:4: error: #error "HEATER_1_PIN not defined for this board."

   #error "HEATER_1_PIN not defined for this board."

    ^~~~~

In file included from sketch\MarlinConfig.h:42:0,

                 from sketch\SdBaseFile.cpp:30:

SanityCheck.h:1142:4: error: #error "HEATER_1_PIN not defined for this board."

   #error "HEATER_1_PIN not defined for this board."

    ^~~~~

exit status 1

#error "HEATER_1_PIN not defined for this board."

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
