### ISSUE TITLE
[FR] (Recover print job after heater failed)

### ISSUE THREAD

**Issue by ggamehdtv** [MarlinFirmware/Marlin#19004]
Hi,

I have searched everywhere and can't find it so I think it does not exists.

Is it possible to add a feature to resume the print job when a heater failed?
It will be in the same way like power loss recovery. But instead of power loss it will be heater failed. 

Best regards,
Justinn

**Comment by AnHardt** [comment]
Basically a duplicate of #18818 .

Possible: yes.
Save: no.
Wanted: **NO!**

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/18818
