### ISSUE TITLE
DUMMY_THERMISTOR_999 reads 25°C instead of 100°C

### ISSUE THREAD

**Issue by UnfoldAntwerp** [MarlinFirmware/Marlin#1903]
If I define a thermistor as 999 then the temperature reported is 25°C instead of 100°C. 25°C should be reported by 998 only no?

ps. first ever use of Github so bare with me if I do it wrong...

**Comment by AnHardt** [comment]
Both of the dummy thermistors default to 25°C.
You can give them the temperature you want, by uncommenting DUMMY_THERMISTOR_998_VALUE and or DUMMY_THERMISTOR_999_VALUE.

**Comment by UnfoldAntwerp** [comment]
ah, sorry. Misunderstood, thanks for clarifying!
