### ISSUE TITLE
code_has_value doesn't work as expected?

### ISSUE THREAD

**Issue by tonnico** [MarlinFirmware/Marlin#1904]
When I home with `G28 X Y` my printer said it's at 0,0 after homing. But I'm using max-endstops for X and Y. `G28` is working as expected.

**Comment by thinkyhead** [comment]
#1907 might have fixed it. The return type was incorrect, so it might have been returning true all the time, or who knows what...

**Comment by thinkyhead** [comment]
Hmm, well `code_has_value()` does work (even as a float) so possibly this is being caused by something else in the `G28` handler. If it persists we'll try adding some debug logging.

**Comment by tonnico** [comment]
Got it. It's Repetier Host. The Host sends automatically G28 X0 instead of G28 X.
