### ISSUE TITLE
PlatformIO Core 4.4 compatibility

### ISSUE THREAD

**Issue by ivankravets** [MarlinFirmware/Marlin#19041]
Hi all,

We have refactored our package management system in PlatformIO Core 4.4. See upcoming changes https://github.com/platformio/platformio-core/blob/develop/HISTORY.rst
This is the biggest upgrade to package manager since the 2014 year. We didn't affect CLI  or other public APIs. Nevertheless, internal modules are changes.

Please ping me here if you need any help with adapting your "extra scripts" for any PIO Core version.

Regards, 
Your friends at PlatformIO.

**Comment by rhapsodyv** [comment]
I just made the package manager / spec compatibility:
#19034

But some builds were failing with "missing package" error. But it just happens in the PIO dev version. I will test again today.

**Comment by ivankravets** [comment]
> But some builds were failing with "missing package" error. 

Could you provide more details? Thanks!

**Comment by ivankravets** [comment]
We uploaded a package with the Arduino framework for LPC1768. Please re-test the latest development version of PIO Core.

**Comment by rhapsodyv** [comment]
I think it's done, right?

**Comment by ivankravets** [comment]
Yes, [PlatformIO Core 5.0](https://github.com/platformio/platformio-core/releases/tag/v5.0.0) is out! Thanks for your reports!
