### ISSUE TITLE
[BUG] 2.0.6 NOZZLE_PARK_FEATURE not working if X/Y is negative

### ISSUE THREAD

**Issue by wolfgangmauer** [MarlinFirmware/Marlin#19054]
### Bug Description

If the park point is negative "#define NOZZLE_PARK_POINT { **-10, -10**, 5 }" the printhead is not parking at filament runout

### My Configurations
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5084498/Marlin.zip)
### Steps to Reproduce

Set 
#define NOZZLE_PARK_POINT { **-10, -10**, 5 }

**Expected behavior:** [What you expect to happen]
Printheat parking at NOZZLE_PARK_POINT
**Actual behavior:** [What actually happens]
Z lift 5mm, but X/Y don't move

**Comment by wolfgangmauer** [comment]
Works on bugfix-2.0.x correctly

**Comment by thisiskeithb** [comment]
> Works on bugfix-2.0.x correctly

Great!
