### ISSUE TITLE
[BUG] The mks_robin_pro cannot use AT24C32 eeprom

### ISSUE THREAD

**Issue by makerbase-mks** [MarlinFirmware/Marlin#19060]
### Bug Description

When I am testing the motherboard of MKS ROBIN PRO V1.0, I can define
#define SDCARD_EEPROM_EMULATION
Make the parameter save in the SD card, it can be used normally.
But if I define
#define I2C_EEPROM // EEPROM on I2C-0
#define MARLIN_EEPROM_SIZE 0x1000 // 4KB
#define E2END 0xFFF // 4KB
At the same time, I changed the eeprom model of the motherboard to AT24C32, the program cannot be executed normally, and it will stay on the logo interface. I think this may be a communication problem between mcu and eeprom.

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by sjasonsmith** [comment]
Please don't mix two issues in one report. I suggest you split this so each issue has its own report.

It is very important to follow the issue template. Both of these issues need to include configuration files and steps to reproduce.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
> ### Steps to Reproduce
> 1. [First Step]
> 2. [Second Step]
> 3. [and so on...]

**Comment by boelle** [comment]
template not followed

no response

closing
