### ISSUE TITLE
[BUG] Filament change layer shift

### ISSUE THREAD

**Issue by redgod** [MarlinFirmware/Marlin#19067]
If when I activate the change of filament, it raises the nozzle it goes to a corner then it returns low but not to the layers that it should and is 2 above .......... marlin does not remember the correct layer height

**Comment by boelle** [comment]
did you read the template? you are missing a lot of info

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by redgod** [comment]
sorry it's my first time posting

I upload the configuration I have with marlin 2.0.6, I think I have the configuration right, the filament change is done but at the moment of printing it does it 2 layers above

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5093466/Marlin.zip)

**Comment by boelle** [comment]
Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by redgod** [comment]
It still doesn't work and I can't find the error, when I go back to printing it does it 2 layers up

**Comment by redgod** [comment]
I still can't get the filament switch to work, doesn't remember z height and ends up printing on air

**Comment by qwewer0** [comment]
@redgod Check these two https://github.com/MarlinFirmware/Marlin/issues/19455, https://github.com/MarlinFirmware/Marlin/issues/18191 issues. Not a solution, but you could participate in those if you have the same problems.

**Comment by redgod** [comment]
I still can't get the filament switch to work, doesn't remember z height and ends up printing on air

**Comment by redgod** [comment]
Sigo sin poder hacer funcionar el interruptor de filamento, no recuerdo la altura z y termina imprimiendo en el aire

**Comment by qwewer0** [comment]
@redgod Could you provide detailed steps to reproduce the issue?

**Comment by redgod** [comment]
Description
Steps to reproduce
change of filament during printing
retraction and bleeding of the filament well
does not remember the apposition of origin
Expected behavior
I expected a perfect filament change

Actual behavior
After purging, the nozzle does not remember the correct height and position, since it begins to print more in the center and leaving the external wall exposed without filament

![image](https://user-images.githubusercontent.com/14693622/100515307-e3491500-3159-11eb-9d17-c51d4f360a77.png)

![image](https://user-images.githubusercontent.com/14693622/100515304-d9bfad00-3159-11eb-9146-d60e4e9210a6.png)

**Comment by qwewer0** [comment]
Change filament from the LCD or within the gcode with M600?

**Comment by redgod** [comment]
from the LCD

**Comment by qwewer0** [comment]
Try change filament (LCD or M600) two times in the same print.
Edit: My issue might be different from yours, but I can't tell until you try two filament change in on print.

My results:
**Left**: LCD change filament at the bottom and top, and two M600 in between. The first filament change got shifted in the Y axis, to the max direction.
**Right**: Only one M600, which also got shifted in the Y axis, to the max direction.
![Screenshot 2020-11-28 144824](https://user-images.githubusercontent.com/57561110/100517125-d7287c00-3188-11eb-9e46-de529d7eb686.png)

**Comment by sjasonsmith** [comment]
@qwewer0 are you working on fixing this, or just testing to help verify there is a problem?

**Comment by qwewer0** [comment]
@sjasonsmith Just tested it out to see if I can verify the problem.

Still waiting for @redgod to do two filament change in one print to see if I got the same problem in a different "outfit" or not.

**Comment by ysoline** [comment]
Hello, I also have a problem with Z shifting when resuming printing. The X and Y are fine. But the Z I have at least 1mm of gap between the initial layer and the new layer.

**Comment by qwewer0** [comment]
Can't reproduce it anymore on the latest bugfix-2.0.x

@rhapsodyv Not sure what was my issue that caused my layer shift, so if I was the reason to add "`Bug: Confirmed !`" label, then I think that should be removed until further tests and information from @redgod and maybe @ysoline too.

**Comment by redgod** [comment]
I still have the same problems, none of my ender 3 fields stick

**Comment by Sebazzz** [comment]
To me it seems that sometimes the Z-offset is applied after the filament change. That is the only thing I can think of (CR-6 SE).

**Comment by bartoszwas** [comment]
I got similar issue. I have installed filament runout sensor to my raspberry pi orctoprint. It seems to work fine but after filament change it starts to print a bit higher... Printer reports the same z value but still its a bit too high. I have also installed bed leveling sensor. Printer is Ender 3, Marlin 2.0.7.2.

![IMG_1724](https://user-images.githubusercontent.com/36127790/107847411-90dbd400-6deb-11eb-98ae-4ff8ab64db91.jpeg)

**Comment by tommymonk** [comment]
I'm also experiencing an occasional 1-2 layer discrepancy when it returns to print causing issues similar to above, it doesn't happen with every print though.
The z height numerically is correct but physically is wrong.

**Comment by bartoszwas** [comment]
Check rolls on the z-axis, mine were fixed too tight. This plus a bit of loose on the trapezoid nut gives that result you can see on picture above.

**Comment by zemuro** [comment]
The same issue, filament broke, the head parked, went throuh filament change prcedure, printing resumed in the exact place, but 2-3 layers higher. Was so frustrated, forgot to notice exact heihgt %(

Tronxy xy-2 pro, Marlin bugfix branch (13.03.2021 snapshot)
[Marlin_config.zip](https://github.com/MarlinFirmware/Marlin/files/6204316/Marlin_config.zip)

**Comment by tommymonk** [comment]
Thanks @bartoszwas  you were spot on, adjusting the z axis roller nut has solved it
