### ISSUE TITLE
Incorrect Bed size

### ISSUE THREAD

**Issue by Styg1an** [MarlinFirmware/Marlin#19081]
### Bug Description

I setup my bed size to 400x400x400 but Marlin still handle it as 200x200x200

### My Configurations

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/5098307/Configs.zip).

### Steps to Reproduce

1. Download Marlin 2.0.6
2. Set X_BED_SIZE 400, Y_BED_SIZE 400, Z_MAX_POS_400
3. SEND G0 X200

**Expected behavior:** [What you expect to happen]
    - X axis goes to position 200, the middle of the bed   

**Actual behavior:** [What actually happens]
    - X axis goes to position 200, the end on the bed

**Comment by GMagician** [comment]
m502 and m500?

**Comment by GMagician** [comment]
This seems a bad DEFAULT_AXIS_STEPS_PER_UNIT configuration. 
If you changed from previous cnf do a M502 & M500 and check again

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
