### ISSUE TITLE
[BUG] CALIBRATION_GCODE compile unsuccessful

### ISSUE THREAD

**Issue by Protean-Man** [MarlinFirmware/Marlin#19092]
When compiling for **CALIBRATION_GCODE** in Cofiguration_adv.h I am getting an error calling: 

> error: 'NORMAL_AXIS_INDEX' was not declared in this scope

This is a previous BUG Report but it has been closed. I am finding a similar issue: [](https://github.com/MarlinFirmware/Marlin/issues/17430)
I am also using **COREXY** with **current bugfix** version.
Backlash Compensation is not enabled as per other Bug Report.

**Here is my error compile:**
In file included from Marlin\src\gcode\calibrate\../../inc/MarlinConfig.h:36:0,
                 from Marlin\src\gcode\calibrate\../../MarlinCore.h:24,
                 from Marlin\src\gcode\calibrate\G425.cpp:23:
Marlin\src\gcode\calibrate\G425.cpp: In function 'void probe_side(measurements_t&, float, side_t, bool)':
Compiling .pio\build\mega2560\src\src\gcode\config\M301.cpp.o
Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:165:47: error: 'NORMAL_AXIS_INDEX' was not declared in this scope
 #define AXIS_CAN_CALIBRATE(A) CAN_CALIBRATE(A,NORMAL_AXIS)
                                               ^
Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:160:51: note: in definition of macro 'CAN_CALIBRATE'
     #define CAN_CALIBRATE(A,B) (A##_AXIS_INDEX == B##_INDEX)
                                                   ^
Marlin\src\gcode\calibrate\G425.cpp:256:8: note: in expansion of macro 'AXIS_CAN_CALIBRATE'
   if ((AXIS_CAN_CALIBRATE(X) && axis == X_AXIS) || (AXIS_CAN_CALIBRATE(Y) && axis == Y_AXIS)) {
        ^
Marlin\src\gcode\calibrate\G425.cpp: In function 'void report_measured_positional_error(const measurements_t&)':
Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:165:47: error: 'NORMAL_AXIS_INDEX' was not declared in this scope
 #define AXIS_CAN_CALIBRATE(A) CAN_CALIBRATE(A,NORMAL_AXIS)
                                               ^
Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:160:51: note: in definition of macro 'CAN_CALIBRATE'
     #define CAN_CALIBRATE(A,B) (A##_AXIS_INDEX == B##_INDEX)
                                                   ^
Marlin\src\gcode\calibrate\G425.cpp:384:9: note: in expansion of macro 'AXIS_CAN_CALIBRATE'
     if (AXIS_CAN_CALIBRATE(Z)) SERIAL_ECHOLNPAIR_P(SP_Z_STR, m.pos_error.z);
         ^
Marlin\src\gcode\calibrate\G425.cpp: In function 'void calibrate_toolhead(measurements_t&, float, uint8_t)':
Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:165:47: error: 'NORMAL_AXIS_INDEX' was not declared in this scope
 #define AXIS_CAN_CALIBRATE(A) CAN_CALIBRATE(A,NORMAL_AXIS)
                                               ^
Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:160:51: note: in definition of macro 'CAN_CALIBRATE'
     #define CAN_CALIBRATE(A,B) (A##_AXIS_INDEX == B##_INDEX)
                                                   ^
Marlin\src\gcode\calibrate\G425.cpp:498:34: note: in expansion of macro 'AXIS_CAN_CALIBRATE'
     if (ENABLED(HAS_X_CENTER) && AXIS_CAN_CALIBRATE(X)) hotend_offset[extruder].x += m.pos_error.x;
                                  ^
Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:165:47: error: 'NORMAL_AXIS_INDEX' was not declared in this scope
 #define AXIS_CAN_CALIBRATE(A) CAN_CALIBRATE(A,NORMAL_AXIS)
                                               ^
Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:160:51: note: in definition of macro 'CAN_CALIBRATE'
     #define CAN_CALIBRATE(A,B) (A##_AXIS_INDEX == B##_INDEX)
                                                   ^
Marlin\src\gcode\calibrate\G425.cpp:499:34: note: in expansion of macro 'AXIS_CAN_CALIBRATE'
     if (ENABLED(HAS_Y_CENTER) && AXIS_CAN_CALIBRATE(Y)) hotend_offset[extruder].y += m.pos_error.y;
                                  ^
Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:165:47: error: 'NORMAL_AXIS_INDEX' was not declared in this scope
 #define AXIS_CAN_CALIBRATE(A) CAN_CALIBRATE(A,NORMAL_AXIS)
                                               ^
Marlin\src\gcode\calibrate\../../inc/Conditionals_post.h:160:51: note: in definition of macro 'CAN_CALIBRATE'
     #define CAN_CALIBRATE(A,B) (A##_AXIS_INDEX == B##_INDEX)
                                                   ^
Marlin\src\gcode\calibrate\G425.cpp:500:34: note: in expansion of macro 'AXIS_CAN_CALIBRATE'
                              if (AXIS_CAN_CALIBRATE(Z)) hotend_offset[extruder].z += m.pos_error.z;
                                  ^
compilation terminated due to -fmax-errors=5.
*** [.pio\build\mega2560\src\src\gcode\calibrate\G425.cpp.o] Error 1

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by ellensp** [comment]
issue can be replicated with default config with just enabling COREXY and CALIBRATION_GCODE
