### ISSUE TITLE
[BUG] Unable to compile when probe is enabled and BED_CENTER_AT_0_0 is active

### ISSUE THREAD

**Issue by Arakon** [MarlinFirmware/Marlin#19093]
### Bug Description

My Mendel90 has 0,0 at bed center, with bed going from -100 to (+)100.
When trying to enable a servo-driven probe (BFPTouch), the compilation fails with multiple "PROBING_MARGIN is too large" errors. If I disable the probe defines OR the bed center define, it compiles fine. I also tested setting it up for the BLTouch probe with the same result.

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5104867/Marlin.zip)

### Steps to Reproduce

- Set up the probe in whichever way needed.
- Make sure BED_CENTER_AT_0_0 is defined.
- Attempt to compile.

**Expected behavior:** [What you expect to happen]

Code should compile fine. There's no reason why it should fail because the bed center is defined as the 0 point.

**Actual behavior:** [What actually happens]

Compilation fails.

#### Additional Information

> In file included from Marlin\src\HAL\LPC1768\../../core/../inc/MarlinConfig.h:41,
                 from Marlin\src\HAL\LPC1768\../../core/serial.h:24,
                 from Marlin\src\HAL\LPC1768\DebugMonitor.cpp:25:
Marlin\src\HAL\LPC1768\../../core/../inc/SanityCheck.h:1315:32: error: static assertion failed: PROBING_MARGIN is too large.
 1315 |   static_assert(PROBING_MARGIN < _MARGIN(X), "PROBING_MARGIN is too large.");
Marlin\src\HAL\LPC1768\../../core/../inc/SanityCheck.h:1316:37: error: static assertion failed: PROBING_MARGIN_BACK is too large.
 1316 |   static_assert(PROBING_MARGIN_BACK < _MARGIN(Y), "PROBING_MARGIN_BACK is too large.");
Marlin\src\HAL\LPC1768\../../core/../inc/SanityCheck.h:1317:38: error: static assertion failed: PROBING_MARGIN_FRONT is too large.
 1317 |   static_assert(PROBING_MARGIN_FRONT < _MARGIN(Y), "PROBING_MARGIN_FRONT is too large.");
Marlin\src\HAL\LPC1768\../../core/../inc/SanityCheck.h:1318:37: error: static assertion failed: PROBING_MARGIN_LEFT is too large.
 1318 |   static_assert(PROBING_MARGIN_LEFT < _MARGIN(X), "PROBING_MARGIN_LEFT is too large.");
Marlin\src\HAL\LPC1768\../../core/../inc/SanityCheck.h:1319:38: error: static assertion failed: PROBING_MARGIN_RIGHT is too large.
 1319 |   static_assert(PROBING_MARGIN_RIGHT < _MARGIN(X), "PROBING_MARGIN_RIGHT is too large.");
In file included from Marlin\src\HAL\LPC1768\../../inc/MarlinConfig.h:41,
                 from Marlin\src\HAL\LPC1768\eeprom_sdcard.cpp:25:
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1315:32: error: static assertion failed: PROBING_MARGIN is too large.
 1315 |   static_assert(PROBING_MARGIN < _MARGIN(X), "PROBING_MARGIN is too large.");
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1316:37: error: static assertion failed: PROBING_MARGIN_BACK is too large.
 1316 |   static_assert(PROBING_MARGIN_BACK < _MARGIN(Y), "PROBING_MARGIN_BACK is too large.");
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1317:38: error: static assertion failed: PROBING_MARGIN_FRONT is too large.
 1317 |   static_assert(PROBING_MARGIN_FRONT < _MARGIN(Y), "PROBING_MARGIN_FRONT is too large.");
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1318:37: error: static assertion failed: PROBING_MARGIN_LEFT is too large.
 1318 |   static_assert(PROBING_MARGIN_LEFT < _MARGIN(X), "PROBING_MARGIN_LEFT is too large.");
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1319:38: error: static assertion failed: PROBING_MARGIN_RIGHT is too large.
 1319 |   static_assert(PROBING_MARGIN_RIGHT < _MARGIN(X), "PROBING_MARGIN_RIGHT is too large.");

**Comment by ellensp** [comment]
BED_CENTER_AT_0_0 is not what you think it is. it is for scara and delta printers.
you should not enable it on your printer.

**Comment by Arakon** [comment]
Ah! Okay.. then that should probably be mentioned, since as it stands, it's in no way mentioned that this option isn't for cartesian printers.. where it's not that unusual for them to be centered at 0,0, for older models.
Thanks for the info.

**Comment by timeburn** [comment]
Not every printer that uses BED_CENTER_AT_0_0 is a delta or scara.  
the config for the Flashforge Creator Pro, for example, uses it.    

I added a bltouch (and an skr 1.4 turbo) to mine, and this compiled just fine in 2.0.5.  
Commenting out the sanity check  in inc/SanityCheck.h. line 1310-1316 allows it to compile and work without further issues.

Delta/Scara either shouldn't be a hard requirement, or it needs to be an explicit policy change.   Published configs will need to be updated, and the compile warning updated to reflect the notion that that setting can only be valid in prescribed use cases.

**Comment by thinkyhead** [comment]
> `BED_CENTER_AT_0_0` is not what you think it is. it is for scara and delta printers.

The option is not limited to delta / scara printers, and you should be able to use it in any case.

Note that `BED_CENTER_AT_0_0` is no substitute for setting your X and Y home positions so that the 0,0 point actually falls in the center of the bed. The `BED_CENTER_AT_0_0` option just gives some hints to Marlin about how to automatically generate the home position when it isn't explicitly provided with `*_HOME_POS`.

To fix your compile error:
```diff
- #define _MARGIN(A) TERN(IS_SCARA, SCARA_PRINTABLE_RADIUS, TERN(DELTA, DELTA_PRINTABLE_RADIUS, A##_CENTER))
+ #define _MARGIN(A) TERN(IS_SCARA, SCARA_PRINTABLE_RADIUS, TERN(DELTA, DELTA_PRINTABLE_RADIUS, (A##_BED_SIZE) / 2))
```

**Comment by timeburn** [comment]
I didn't choose the coordinate system;  I just used what was available in the existing config for a Creator Pro.  The published configs for it, the Qidi 1, Wanhao Duplicator 4S, Mbot Cube and Flashforge Creator 2X all use BED_CENTER_AT_0_0.  

Presumably due to the fact that the motion limits are past the bed in all directions, to accomodate the large effector of these models, it was easier to do it that way.  I haven't gone to the admittedly fairly minor trouble of recalculating the coordinate system.

Now, the coordinate system wasn't the trigger here, though.  It was enabling a Z probe along with BED_CENTER_AT_0_0, on a non-delta/scara model.
Granted, these machines don't come with probes, but adding one shouldn't break compilation where it didn't before.

Your patch does fix the compile error.   Thanks

**Comment by thinkyhead** [comment]
The authors of those configs can speak better to their choices than I can. The configs themselves should work as they are if the authors haven't come back around to patch them. Of course, we rely on user feedback to know at any time what lesser-used combinations might have gotten broken by a recent change, and while we try to keep the configs close to the manufacturer's stock configuration, we appreciate user-submitted configs with some fine-tuning and beneficial adjustments.

I'd like to put together a CI test to test the Configurations repository and catch build errors early, but with so many configs I feel like I'd be pushing some unwritten usage limit. OTOH that build report would be something cool to see…
