### ISSUE TITLE
[BUG] MIN_SOFTWARE_ENDSTOP_Z impedes HOTEND_OFFSET_Z with Tool Changers

### ISSUE THREAD

**Issue by Protean-Man** [MarlinFirmware/Marlin#19099]
With T1+ having a `HOTEND_OFFSET_Z` in the positive will have that value ignored if `MIN_SOFTWARE_ENDSTOP_Z` is set to `TRUE`

If I disable `MIN_SOFTWARE_ENDSTOP_Z `then my `HOTEND_OFFSET_Z {0.0, 0.5, 0.2, 0.3}` will work as expected while printing.

**Observations:**
When `MIN_SOFTWARE_ENDSTOP_Z` is `TRUE`
>>> `HOTEND_OFFSET_Z` will work on manual moves. **Example:** Changing to T1, T2, T3 and then moving Z to 0 will follow my `HOTEND_OFFSET_Z ` parameters. However `HOTEND_OFFSET_Z `will not be followed when printing.
When `MIN_SOFTWARE_ENDSTOP_Z` is `FALSE`
>>> `HOTEND_OFFSET_Z` parameters will be followed on both manual moves to Z0.0 and while printing.

If `HOTEND_OFFSET_Z` is set to a negative number then it will be followed regardless of `MIN_SOFTWARE_ENDSTOP_Z`. Which makes sense overall.

**The Issue** is that when implementing a tool changing machine there will be tools that are above Tool 0 and this compensation is not currently being used when `MIN_SOFTWARE_ENDSTOP_Z ` is set to `TRUE`

**Comment by sjasonsmith** [comment]
I think I understand the issue you are describing. You are saying that with software endstops enabled, one of the nozzles cannot reach all the way to the bed?

Please attach your Marlin configuration files, as requested by the issue template. Marlin behavior is extremely configurable, and it is very difficult to debug any issue without knowing how the firmware is configured.

It may also be helpful to include pictures so people know what kind of hardware you are working with.
