### ISSUE TITLE
UBL auto bed leveling - steppermotors move one way only

### ISSUE THREAD

**Issue by wzaburko** [MarlinFirmware/Marlin#19094]
### Bug Description
during self-leveling, the steppermotors only work one way. For example, it can move the head from position 150 to 0, but from 0 to 150 it does not move and the head remains in position 0, but the display shows position 150. This is the case with X and Y. Z works properly.
I noticed that it moves to the first spot without any problems from both directions, but when measuring the next spots there is a problem.
If the head is in the 0,0 position, it moves to the first spot (50,50 in my case) but next  checks the bed in the same position.
After finishing the leveling, it tries to return to the 0,0 position, where it is physically in this position, but the LCD is for example 700,700 and the head tries to escape beyond the bed and not respect sensors (I use sensorless).
Auto-leveling 3 point, mesh and others also work with the same problem.
Manual leveling and editing, printing works without any problems.

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[Comfig.zip](https://github.com/MarlinFirmware/Marlin/files/5105182/Comfig.zip)

### Steps to Reproduce

UBL autoleveling 

**Expected behavior:** 
Move form spot to spot 
**Actual behavior:** 
Move one way only to origin point (X0,Y0), try move out of bed.
#### Additional Information
CoreXY, FLY mainboard, TMC2209 Sensorless, printer from scratch - under constuction. Marlin 2.0.5, 2.0.6, 2.0 bugfix

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.
[Comfig.zip](https://github.com/MarlinFirmware/Marlin/files/5108648/Comfig.zip)

**Comment by ellensp** [comment]
empty closing.
