### ISSUE TITLE
[FR] M33 long file names improvment

### ISSUE THREAD

**Issue by bitboy85** [MarlinFirmware/Marlin#19091]
In octoprint its currently not possibe to show files on the sd card with long filenames.
An implementation is refused because there is currently no way to request all long filenames with a single command. Each file needs to be requested seperatly.
See here: https://github.com/OctoPrint/OctoPrint/issues/1600

So i suggest adding a * parameter to the M33 command so
`M33 *`
will return all files stored on the sd card with their long file names.

**Comment by ellensp** [comment]
Cant easily be * char, that indicates start of checksum in gcode protocol.

**Comment by bitboy85** [comment]
What about omitting a parameter at all? This way M33 would be behave like M20 just returning the long format.

**Comment by ellensp** [comment]
Its not that easy. If you had read all of the issue you linked you may have noticed this huge gotcha.

"Additionally the long file names are not guaranteed to be ASCII, whereas the communication over serial is actually supposed to be only ASCII (even though a lot of firmware variants out there simply don't care). So the long file names would also need to be transported in some encoded format."

This could get very messy.

**Comment by ellensp** [comment]
well, ignoring the above warning.. its easy enough to add long path/name to M20
eg you get an output like this. long name added after size so not to break m20 to much
```
/VORPAL~1/GAMEPA~4.GCO 261137 /Vorpal_Combat_Hexapod_files/Gamepad_V1r8a_Battery_Drawer.gcode
/VORPAL~1/VORPAL~1.GCO 4724253 /Vorpal_Combat_Hexapod_files/Vorpal_Hexapod_V1r8b_Stand.gcode
FS-COV~1.GCO 855574 fs-cover_0.2mm_PETG_MK2.5_34m.gcode
X-CARR~1.GCO 5006866 x-carriage_0.2mm_PETG_MK2.5_2h51m.gcode
End file list
```

**Comment by ellensp** [comment]
Take a look at the PR above and enable LONG_FILENAME_MEDIA_LIST in Configuration_adv.h

**Comment by bitboy85** [comment]
I suggested M33 because of the LONG_FILENAME dependency, so it won't break M20. If your PR is accepted i'm fine with it :)

**Comment by ellensp** [comment]
Decided to add L parameter to M20 activate the long names (still needs LONG_FILENAME_MEDIA_LIST too) , otherwise output is the expected 8.3 format.  
This ensures no current software will break.

**Comment by ellensp** [comment]
Well I tried, but thinkyhead is being as stubborn as a mule that it must be done the slow painful way...

**Comment by vivian-ng** [comment]
> Well I tried, but thinkyhead is being as stubborn as a mule that it must be done the slow painful way...

@ellensp Thanks for giving it a try anyway. Appreciate the effort.

**Comment by Roxy-3D** [comment]
> So the long file names would also need to be transported in some encoded format."

It would not be very hard to encode this information and force it to be ASCII.     We are only talking a few lines of code to do that.     The question is... would the client programs be willing to decode it and use it?    And would that really make sense to do it that way.

All of the SD-Card file handling M-Codes are kind of non-compliant with G-Code.   They don't really conform to what the G-Code syntax is supposed to be.

**Comment by GMagician** [comment]
What about a double serial protocol? Default is current one and with a special code switch to another. This new protocol may be used as a FS protocol (and maybe others may be added). This new FS may also be used for a fast gcode upload

**Comment by bitboy85** [comment]
In case of encoding i guess the most easy solution would be to fall back to a HTML encoding. so client programs can easy handle it, or in case of web based client, doesn't need to handle it at all because it is already formated for this usage.

**Comment by thinkyhead** [comment]
The purpose of `M33` is to give hosts a way to pretty up their file listing once they have the file listing in DOS8.3 format. Surely host software developers understand how to do this. If it's very difficult and host developers get stuck on how to accomplish this, I will set aside some time to add the necessary code to OctoPrint as an example for others to follow.

**Comment by bitboy85** [comment]
@thinkyhead Well if you have a look at my first post and the discussion, the main developer of octoprint knows exactly how to implement this but refuses to do so because she thinks its a bad way doing so and its up to the firmware developer to provide a better way to get all filenames with one command.

**Comment by firepower9966** [comment]
Also ESP3D can not use long filenames because limit of marlin. 
https://github.com/luc-github/ESP3D/issues/326

**Comment by AnHardt** [comment]
> most easy solution would be to fall back to a HTML encoding. 

That will not work. For that we'd have to know the kind of encoding on the card - but since that information is not on the card - ... .

> but refuses to do so because she thinks its a bad way doing so.

We think that to. For the exact same reasons we think it's not a good idea to read all long filenames when sending the directory. It potentially blocks Marlin for a looong time.
A more intelligent strategy is needed - maybe like requesting only that long filenames currently displayed - maybe caching that data.

**Comment by bitboy85** [comment]
In the octoprint discussion linked above there were even suggestions to show only the selected file with long filenames or to use a caching method...was refused too.

Currently there is support for M33. How is encoding handled here? How does it work without knowing the encoding on the card?

**Comment by slowbro** [comment]
#22271 was merged, this can be closed.

**Comment by thisiskeithb** [comment]
Implemented as [`M20 L`](https://marlinfw.org/docs/gcode/M020.html).
