### ISSUE TITLE
How to add Chinese language

### ISSUE THREAD

**Issue by diver197** [MarlinFirmware/Marlin#1909]
How to add Chinese language，I want to know how to do the dogm_font_data file, it is best to have the detailed steps, thank you!

**Comment by AnHardt** [comment]
@diver197 
Chinese - that's difficult.
Currently we are limited to 256 symbols per font. That's, by far, not enough to represent the complete Chinese charset.  Maybe you can make a selection of symbols you need. The language_xx.h file will then look like 'language_kana.h'.
We use a menu system with 5 lines, on a display with 64 pixel height. That means we have 12 pixel for a line. To have some space in between the lines we can't use more then 10 pixel height for the symbols.
We use fixed width fonts. To fit 22 Symbols on the 128 pixel wide screen, the symbols can't be wider than 5 pixel. Maybe you can work with half symbols - two places in the charset will than build one wide symbol.
The latest fonts i have made with 'Fony.exe' - but 'fontforge' will probably work to. 
So the easyest way to go is:
- Get 'Fony.exe'
- Copy one of the existing *.fon files and work with this.
- Change the pixels. Don't change width or height. 
- Export as *.bdf
- Use 'bdf2u8g.exe' to produce the *.h file. Examples for the existing fonts are in 'make_fonts.bat'
- Edit the produced _.h file to match our needs. See hints in 'README.fonts' or the other 'dogm_font_data__.h' files.

Than produce a matching language_xx.h file.

Good luck.

**Comment by diver197** [comment]
Using the above methods can in earlier versions, now the latest I have no way to display text after use, according to blank

**Comment by AnHardt** [comment]
@diver197 
I hope i understand your problem. You could be a bit more descriptive about what you did.

My explanation was incomplete.
In Your language_xx.h file:

```
 #define MAPPER_NON
 #define DISPLAY_CHARSET_NEWNAME
```

In 'dogm_lcd_implementation.h' before line 81 (  #else // fall-back) inset a new block to load your font.

```
#elif defined( DISPLAY_CHARSET_NEWNAME )
  #include "dogm_font_data_yourfont.h"
  #define FONT_MENU_NAME YOURFONTNAME
```

**Comment by diver197** [comment]
I use is 12864 lce, add the relevant file, switch to the Chinese, no any display

**Comment by AnHardt** [comment]
Would you please be so kind to show me your 'relevant' fileS?

Configuration.h
dogm_lcd_implementation.h
Your font dogm_font_data_yourfont.h
Your language file language_xx.h

Please use a pastebin or even better - give me a link to your fork of marlin.

**Comment by diver197** [comment]
http://pastebin.com/PCkDq4sN
http://pastebin.com/rnqQ1XMC
http://pastebin.com/KH2dfTW9
http://pastebin.com/WtwsdAb7

**Comment by AnHardt** [comment]
@diver197 
Got it. I have a more or less working example for you. Please see: https://github.com/AnHardt/Marlin/tree/Chinese

I totally forgot about the fallback test in 'language_eh.h'. I guess that was the problem.

If you do not see a picture at all - The second half of your 'Configuration.h' is lost. No definitions of languages or displays at all.
'language_en.h' is not the ideal base for a new translation. All the #ifndef's are not needed.
Your font is a bit to large - especially the European part.
![picture 124](https://cloud.githubusercontent.com/assets/211931/7258061/59174cf6-e85a-11e4-967c-5592e405581a.jpg)

![picture 125](https://cloud.githubusercontent.com/assets/211931/7258065/600d5334-e85a-11e4-836e-def6486f596d.jpg)

All the differences to https://github.com/MarlinFirmware/Marlin/tree/Development
you can see at: https://github.com/AnHardt/Marlin/pull/3

**Comment by diver197** [comment]
Thank you, big font issues have been identified, is now being revised

**Comment by diver197** [comment]
How to adjust the menu at the top of the space, there are 3 pixels, I want to show to the top
![qq 20150423183512](https://cloud.githubusercontent.com/assets/8023774/7295364/b05c0428-e9e7-11e4-9737-589ba3263194.png)

![Uploading QQ图片20150423183512.png . . .]()

**Comment by AnHardt** [comment]
@diver197 
Drawing the white bar and positioning the cursor for the text is done in file 'dogm_lcd_implementation.h' in function lcd_implementation_mark_as_selected''. Line 369 draws the box. Line 375 positions the cursor. 
DOG_CHAR_WIDTH and DOG_CHAR_HEIGHT are defined around line 95.
START_ROW is 0 and will be removed some day.

From line 343 on the position for the status-line on the status screen is set.

Maybe you can also play with the baseline of your font.
LCD_HEIGHT defined in 'Conditionals.h' sets the number of lines in the menu!

**Comment by AnHardt** [comment]
@diver197 
You may also want to play with:
USE_SMALL_INFOFONT line 46. 
Applying FONT_STATUSMENU to line 335.
Shifting SD-card symbol (from line 253 ) one pixel up.
Shifting progress bar (from line 261) a bit up.

**Comment by AnHardt** [comment]
And when playing with USE_SMALL_INFOFONT obviously with FONT_MENU in line 344 to get the Chinese font for the status line.

**Comment by diver197** [comment]
Thank you very much! I am doing now is 1.2 m \* 1.2 m \* 1.5 m machines

**Comment by AnHardt** [comment]
@diver197 
Added a quick and dirty hack to make some vertical room for your font.
See https://github.com/AnHardt/Marlin/pull/3 - second commit.
The horizontal problems are still unsolved.
As I said all is depending on a certain font size.

![picture 127](https://cloud.githubusercontent.com/assets/211931/7298238/832bd136-e9ce-11e4-85e7-d7b11f3565dc.jpg)

![picture 128](https://cloud.githubusercontent.com/assets/211931/7298240/894b5f3c-e9ce-11e4-84fc-92bdeaafa876.jpg)

**Comment by AnHardt** [comment]
@diver197 
If you promise to send us back your finished 'language_cn.h' file and your font sources (*.fon or *.bdf)
i'll have a look on the remaining horizontal problems.

**Comment by diver197** [comment]
2015-04-23 

152053 

发件人：AnHardt notifications@github.com
发送时间：2015-04-23 21:48
主题：Re: [Marlin] How to add Chinese language (#1909)
收件人："MarlinFirmware/Marlin"Marlin@noreply.github.com
抄送："diver"152053@163.com

@diver197 
If you promise to send us back your finished 'language_cn.h' file and your font sources (*.fon or *.bdf)
i'll have a look on the remaining horizontal problems.

**Comment by diver197** [comment]
Have you received the attachment, if there is no email 152053 @163.com

**Comment by AnHardt** [comment]
@diver197 
No. I have not. Try github(at)kitelab(dot)de

**Comment by diver197** [comment]
I don't know how to upload it

**Comment by AnHardt** [comment]
@diver197 
So send a mail with attachment to github@kitelab.de

**Comment by AnHardt** [comment]
@diver197 
Please Test if #1977 works for you.

**Comment by AnHardt** [comment]
#1977 is merged.
