### ISSUE TITLE
[BUG] Stuttering on latest snapshot on Sbase 

### ISSUE THREAD

**Issue by karabas2011** [MarlinFirmware/Marlin#19103]
Snapshot marlin2 from 20-aug-2020
delta/mks sbase

The same as in my old issue:
https://github.com/MarlinFirmware/Marlin/issues/17055#issue-574461208

Tried: 
#define MINIMUM_STEPPER_PULSE 5  as recommended for DRV8825 -  no help

#MIN_STEPS_PER_SEGMENT  1   //6   ( https://github.com/MarlinFirmware/Marlin/issues/14532# )
Problem seems to be gone (after wiping eeprom)! but probably it is incorrect solution.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by TheNitek** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5110725/Marlin.zip)
I see the same issue on my anycubic predator (trigorilla pro). MIN_STEPS_PER_SEGMENT 1 seems to have fixed it for me.

**Comment by boelle** [comment]
@karabas2011 did the suggestion from @TheNitek help you?

**Comment by karabas2011** [comment]
Yes, I wrote about it in first message. Is it correct solution or temporarily workaround?

**Comment by karabas2011** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5117290/Marlin.zip)

**Comment by boelle** [comment]
> Problem seems to be gone (after wiping eeprom)! but probably it is incorrect solution.

wipe of eeprom with M502 followed by M500 is what you should always do if updating

**Comment by TheNitek** [comment]
I tried M502/M500 and while it changed (and improved) the behaviour, it didn‘t fully fix it. MIN_STEPS_PER_SEGMENT change was required.

**Comment by TheNitek** [comment]
Today it happened again: While one print was fine, I started another one (without turning the printer of or changing any settings!) and it started stuttering again. A reset fixed it this time.

**Comment by thinkyhead** [comment]
It may be that the slicer is being allowed to create too many tiny segments. There's a slicer setting that will allow you to specify a minimum segment length, and increasing this value may help to eliminate the issue. If printing from a host, it may also help to print from the SD card instead.

**Comment by TheNitek** [comment]
I was printing from SD card. I tried files sliced  with Cura and Slic3r. After resetting the printer the same file printed fine.

**Comment by TheNitek** [comment]
I feel like #MIN_STEPS_PER_SEGMENT 1 only make things slightly better, so the initial problem is not visible. Seems like the printer is still running at nearly 100% CPU usage resulting in #19186

**Comment by sjasonsmith** [comment]
Are you seeing differing performance between multiple prints of the same gcode, or with different files?

When STL files are created, most software lets you choose how detailed they should be. If the detail is too high it creates extra work for the printer without actually improving quality.

If you are exporting your own STL files, try lowering the exported quality. You will see a corresponding decrease in file size when you do this. In Fusion 360 I usually export using “Medium” quality.

If you are using STLs from someone else, look for a setting in your slicer that specifies the minimum detail to slice. Play with that to try to find a value that gives you a gcode file size reduction without perceivable quality change.
