### ISSUE TITLE
[BUG] mks tft24 with mks robin nano v1.2

### ISSUE THREAD

**Issue by nehilo** [MarlinFirmware/Marlin#19107]
Good time. I have problem with showing touch buttons on tft 24 and mks robin nano v1.2![image](https://user-images.githubusercontent.com/69736697/90912050-5d4b5e80-e3f3-11ea-903b-7ad8b82913d7.jpeg)

**Comment by ellensp** [comment]
Empty issue.... no details, no issue....  closing.

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
closing for the following reasons:

1) Template was not read
    a)no config files attached as template requires
    b)no description
    c)how to reproduce is not told

we can reopen when everything is in place in the first post
