### ISSUE TITLE
[BUG] Marlin 1.1.9 - M23 fails if file is in sub directory

### ISSUE THREAD

**Issue by bitboy85** [MarlinFirmware/Marlin#19109]
### Bug Description

I just flashed Marlin 1.1.9 to my Ender 3.
While using octoprint i noticed that it isn't possible to load files which are stored on SD in a sub directory.
Files which are stored in the root folder of SD works fine.

The issue seems to be the leading "/" which makes the command fail, but according to the doc
https://marlinfw.org/docs/gcode/M023.html the slash should work.

here are two example outputs:

Fails:
```
Send: M23 /ENDERA~1/CE3_FG~1.GCO
Recv: echo:Now doing file: /ENDERA~1/CE3_FG~1.GCO
Recv: open failed, File: CE3_FG~1.GCO.
```

Works:
```
Send: M23 ENDERA~1/CE3_FG~1.GCO
Recv: echo:Now fresh file: ENDERA~1/CE3_FG~1.GCO
Recv: File opened: ENDERA~1/CE3_FG~1.GCO Size: 595535
Recv: File selected
```

**Comment by thisiskeithb** [comment]
Marlin `1.1.x` is no longer being worked on. Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by boelle** [comment]
@bitboy85 did you try what @thisiskeithb suggested?

**Comment by bitboy85** [comment]
Currently i'm not able to flash another version. Seems the bootloader is gone after the first flash.
I've read that marlin 2.0 takes more space so i guess my feature list won't fit.
Maybe as soon as i'm able to flash again i try to fix it on my own (any hints are welcome).

**Comment by ellensp** [comment]
Not a current marlin,  unable to assist.  

Try one of the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by bitboy85** [comment]
In case anyone else end up here and wants to use marlin 1.1.9 here is a hacky bugfix.
In Marlin_main.cpp around line 7604 change the function "inline void gcode_M23" to this:
```
  inline void gcode_M23() {
    byte filenameSlash = 0;
    #if ENABLED(POWER_LOSS_RECOVERY)
      card.removeJobRecoveryFile();
    #endif
    // Simplify3D includes the size, so zero out all spaces (#7227)
    for (char *fn = parser.string_arg; *fn; ++fn){
      if (*fn == ' ') *fn = '\0';
      if (*fn == '/') filenameSlash += 1;
    }
    if (filenameSlash > 1){
      card.openFile(&parser.string_arg[1], true);
    }
    else {
      card.openFile(parser.string_arg, true);      
    }
  }
```
