### ISSUE TITLE
[BUG] GRID_MAX_POINTS_X don't save leveling values if is upper 5

### ISSUE THREAD

**Issue by a-phe-lei-a** [MarlinFirmware/Marlin#19105]
### Bug Description

If I have the value 7 in GRID_MAX_POINTS_X the EEPROM don't save all values. Only 2 or 3 are saved. And I don't have any response if I type M500 or M501. The #define EEPROM_SETTINGS is enable. My MLB is SKR mini E3 V2.0
### My Configurations

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/5108223/Archive.zip)

### Steps to Reproduce

1. G28
2. G29
3. The bed leveling is running and I have all the values
4. M500 > nothing response (Work fine if GRID_MAX_POINTS_X is 5)
5. M501 > nothing response (Work fine if GRID_MAX_POINTS_X is 5)

```Bilinear Leveling Grid:
      0      1      2      3      4      5      6
 0 +0.462 +0.293 +0.212 +0.067 +0.125 +0.080 +0.180
 1 +0.262 +0.180 +0.132 +0.182 +0.032 +0.040 +0.105
 2 +0.267 +0.135 +0.017 -0.023 -0.023 +0.042 +0.262
 3 +0.220 +0.115 +0.020 -0.003 +0.002 +0.047 +0.277
 4 +0.220 +0.110 +0.040 +0.017 +0.050 +0.105 +0.352
 5 +0.210 +0.122 +0.067 +0.053 +0.085 +0.157 +0.400
 6 +0.227 +0.147 +0.072 +0.087 +0.230 +0.220 +0.462
M500
M501
M503

echo:  G29 W I4 J6 Z0.23000
echo:  G29 W I5 J6 Z0.22000
echo:  G29 W I6 J6 Z0.46250
echo:; Material heatup parameters:
echo:  M145 S0 H185 B45 F255
echo:  M145 S1 H240 B110 F255
echo:; PID settings:
echo:  M301 P21.73 I1.54 D76.55
; Controller Fan
echo:  M710 S255 I0 A1 D60 ; (100% 0%)
echo:; Z-Probe Offset (mm):
echo:  M851 X-40.00 Y-12.00 Z-1.95
echo:; Stepper driver current:
echo:  M906 X580 Y580 Z580
echo:  M906 T0 E650

echo:; Hybrid Threshold:
echo:  M913 X100 Y100 Z3
echo:  M913 T0 E30

echo:; StallGuard threshold:
echo:  M914 X73 Y73
echo:; Driver stepping mode:
echo:  M569 S1 X Y Z
echo:  M569 S1 T0 E
echo:; Linear Advance:
echo:  M900 K0.00
echo:; Filament load/unload lengths:
echo:  M603 L350.00 U400.00

**Comment by sjasonsmith** [comment]
@The33Coder I realize this has been sitting with no replies for quite some time. I have used 8x8 meshes in the past without issue, but it has been quite some time.

Are you still experiencing this issue, or have you already resolved it?

Given the age of this report, I suggest trying it with the latest  [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
