### ISSUE TITLE
MOTION MENU -> M48 PROBE TEST does not work without Z_SAFE_HOMING 

### ISSUE THREAD

**Issue by qystan** [MarlinFirmware/Marlin#19101]
See also see #19075.

### Bug Description
MOTION menu M48 PROBE TEST does not work as expected if Z_SAFE_HOMING is not activated.

menu_motion.cpp code "G28\nM48 P10" performs the test at current nozzle position only.  It needs additional X, Y, Z position parameters to position the nozzle inside the bed area.

Suggest to amend menu_motion.cpp from:
>    #if ENABLED(Z_MIN_PROBE_REPEATABILITY_TEST)
>        GCODES_ITEM(MSG_M48_TEST, PSTR("G28\nM48 P10"));
>    #endif
> 

To:
>    #if ENABLED(Z_MIN_PROBE_REPEATABILITY_TEST)
>        GCODES_ITEM(MSG_M48_TEST, PSTR("G28\n`G0 Znn\n`M48 P10 `Xnn Ynn`"));
>    #endif
> 

> where:
> Znn = #define LEVEL_CORNERS_Z_HOP
> Xnn = #define X_MAX_POS X_BED_SIZE / 2   - this is to make it generic for all printer sizes and probe locations
>    or Xnn = Z_SAFE_HOMING_X_POINT (?)
> Ynn = #define X_MAX_POS Y_BED_SIZE / 2
>    or Z_SAFE_HOMING_Y_POINT (?)
> 

May need additional handling for for users using #define BED_CENTER_AT_0_0.

- apologies for not being able to provide further code suggestions, my programming skills is like minus 10 :-)

### My Configurations
Hardware config has an allen-key probe mounted on the left of the nozzle, as such Z_SAFE_HOMING is not mandatory.
The outside position is preferred to avoid filament drips onto the bed while heating.

Compiled using bugfix 2.0.

[config.zip](https://github.com/MarlinFirmware/Marlin/files/5106176/config.zip)

### Steps to Reproduce

1.  Compile Marlin with following options:

    > #define Z_MIN_PROBE_REPEATABILITY_TEST
    > //#define Z_SAFE_HOMING      ( Z_SAFE_HOMING commented out )

2.  Select MOTION menu -> M48 PROBE TEST

**Expected behavior:** [What you expect to happen]
1.  Printer should move the nozzle into the bed area and execute the test.

**Actual behavior:** [What actually happens]

1.  Printer starts with an AUTO-HOME to the outside left front corner
2.  Then aborts because it is outside of the bed area with no error messages or warning. 
- The above is correct based on menu_motion.cpp ("G28\nM48 P10") but not helpful.

#### Additional Information
NIL

**Comment by GMagician** [comment]
I'll post soon a PR

**Comment by qystan** [comment]
Thank you.
