### ISSUE TITLE
[FR] Could we add MKS sGen V2.0

### ISSUE THREAD

**Issue by ebraiman** [MarlinFirmware/Marlin#19100]
### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. Download current Marlin firmware from https://marlinfw.org/meta/download/ (2.0.6)
2. Open boards.h and search on MKS sgen L v2
3. Open LPC1769 folder and search on MKS Sgen L v2.0
**Expected behavior:** [What you expect to happen]
MKS Sgen L v2.0 would be present.

**Actual behavior:** [What actually happens]
MKS Sgen L v2.0 is not present.
#### Additional Information

This is current on MKS github page.
https://github.com/makerbase-mks/MKS-SGEN_L-V2

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by thisiskeithb** [comment]
It will be added once this PR is merged: https://github.com/MarlinFirmware/Marlin/pull/18822
