### ISSUE TITLE
[BUG] UBL auto bed leveling - steppermotors move one way only

### ISSUE THREAD

**Issue by wzaburko** [MarlinFirmware/Marlin#19106]
### Bug Description

during self-leveling, the steppermotors only work one way. For example, it can move the head from position 150 to 0, but from 0 to 150 it does not move and the head remains in position 0, but the display shows position 150. This is the case with X and Y. Z works properly.
I noticed that it moves to the first spot without any problems from both directions, but when measuring the next spots there is a problem.
If the head is in the 0,0 position, it moves to the first spot (50,50 in my case) but next checks the bed in the same position.
After finishing the leveling, it tries to return to the 0,0 position, where it is physically in this position, but the LCD is for example 700,700 and the head tries to escape beyond the bed and not respect sensors (I use sensorless).
Auto-leveling 3 point, mesh and others also work with the same problem.
Manual leveling and editing, printing works without any problems.

### My Configurations
[Comfig.zip](https://github.com/MarlinFirmware/Marlin/files/5108735/Comfig.zip)
### Steps to Reproduce
From LCD menu or from command line bed leveling

**Expected behavior:**

Move form spot to spot and autolevel

**Actual behavior:** 

Move one way only to origin point (X0,Y0) and try to move to homing  position and crash - go out of bed. 

#### Additional Information

CoreXY, FLY mainboard, TMC2209 Sensorless, printer from scratch - under constuction. Marlin 2.0.5, 2.0.6, 2.0 bugfix

**Comment by Protean-Man** [comment]
I had a similar issue a few months back where certain steppers would only move in a single direction. It was CoreXY as well. 
All of my motors would only move in one direction no matter the input.
After a day of trying to find the firmware issue it ended up being the damned stepper drivers. One of them to be exact. I have no idea why this was the case but one faulty driver threw all of them off. 
I started by taking all the drivers out and adding them in one by one, moving whatever axis they attach to in both directions and found that it was one of the Z drivers. 

This may not fix your problem but it sounds similar to an extent. I was also using 2209s like you. Hope this helps!

**Comment by wzaburko** [comment]
Hi. 
It works on 2.6.1 with no problems :)
Thank you for help.
