### ISSUE TITLE
VScode+PlatformIO: Build error (stm32f1)

### ISSUE THREAD

**Issue by AlexCreality** [MarlinFirmware/Marlin#19113]
### Bug description

Error while building firmware for SKR mini E3 V 1.2

### My Configurations

Custom platformio.ini, Configuration.h, Configurationa_adv.h.
**Required:** [Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5112650/Marlin.zip)

### Steps to Reproduce

I use VScode and PlatformIO to build Marlin firmware for Ender 3 with SKR mini E3 V. 1.2 (Windows OS).

1. Install VSCode IDE and PlatformIO IDE;
2. Download Marlin V. 2.0.6.;
3. Download configuration example for Creality/Ender 3/SKR Mini E3 V. 1.2.;
4. Change platformio.ini, Configuration.h, Configuration_adv.h;
5. Buld firmware through env:STM32F103RC_btt_512K

**Expected behavior:** Building complete.

**Actual behavior:** Error: stm32f1 family is not supported by maple core.

#### Additional Information

* ![image](https://user-images.githubusercontent.com/66466630/90960576-32bcdc80-e4ab-11ea-8b8a-0e9d172ae7a2.png)

Forgive me if I framed the problem incorrectly - this is my first time doing this.
Thanks in advance.

**Comment by thisiskeithb** [comment]
I downloaded a fresh copy of `2.0.6` and used your configs + platformio.ini file and it compiled fine in a Windows 10 VM and on macOS.

Try the steps outlined in https://github.com/MarlinFirmware/Marlin/issues/15492.

-----

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
