### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by electricianbible** [MarlinFirmware/Marlin#19117]
### Bug Description

I am trying to install this board (BIGTREETECH SKR Mini E3 V2.0) on my ender 3 v2.

This is my configuration files.
when try to pre heat pla and bed get this error

Heating Failed: E1
Printer halted
Please reset

Also try the BIGTREETECH firmware files and won’t work same error. Any help would be really appreciated.

### My Configurations

Configuration.h
https://drive.google.com/file/d/1mzNn8rFFu126a-psCAQTmuaL2_EncWAe/view?usp=sharing
Configuration_adv.h
https://drive.google.com/file/d/13GXvZy4t8r_c8DJOfwwtiE0glVNOopKx/view?usp=sharing
### Steps to Reproduce

1. install BIGTREETECH firmware
2. try to preheat main > temperature >preheat pla
not change in temperature not voltage is going to the bed or the hotend.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
