### ISSUE TITLE
adding additional stepper motor to ramps 1.4

### ISSUE THREAD

**Issue by lloydw88** [MarlinFirmware/Marlin#19126]
So this is my very first comment on here, so I apoligize if Im doing it wrong.  So im at my wits end at trying to get this 3rd motor running correctly.  I had an anet a8, but I have since upgraded to a ramps 1.4.  I also have a thc-01 3 colored hotend installed along with a bl touch.  I have 2 of the 3 motors running properly they are attached to e0 and e1.  Ive spent probly 200+ hrs looking for a solution to add a third stepper motor e2 to make a third color.  I got my printer in 2017 and in the last year or so really put it to use.  So I would like to make 3 colored prints, Ive defined the pins in pins_ramps.h, I know the motor is good as ive done the led test, and switched plugs from a known working motor.  so I assumed at this point the reason the motor is making a grinding noise and is stuttery is either the driver or in the code.  so I bought some a4988's recently because I figured the drv8825' were the issue, but the stuttering persists so i dont think its the drivers.  now im convinced its in the code.  and Im semi new so not confident enough to say yes.  but my gut says you gotta do a little more than just define some pins on Aux-2 or aux-1.  I would like it to work just like e0 and e1.  any way I can just copy their code and change it to e2?  any help at this point would be greatful, I been at this for a minute and would love to finish this upgrade.  Maybe Im missing something in planner or one of the tabs other than configuration.h?

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
