### ISSUE TITLE
[BUG] TMC Connection error

### ISSUE THREAD

**Issue by jeor112** [MarlinFirmware/Marlin#19122]
Hi,
I´am trying to configure for TMC2209 UART

Hardware:
Mks Robin Nano V1.2
MKS Robin TFT35 V1.0

Marlin firmware:
Latest (at this moment) Marlin Bugfx 2.0

I have been following this guide https://www.youtube.com/watch?v=7ShcFKXrVHo from MKS.
I know, that this guide describes how to with their firmware/UI, but I would like to use the Marlin UI instead.

In the guide. they describe to setup TX/RX pins in the pins_MKS_ROBIN_NANO.h
I have added this:
`#if HAS_TMC_UART
  /**
   * TMC2208/TMC2209 stepper drivers
   *
   * Hardware serial communication ports.
   * If undefined software serial is used according to the pins below
   */
  //#define X_HARDWARE_SERIAL  Serial1
  //#define X2_HARDWARE_SERIAL Serial1
  //#define Y_HARDWARE_SERIAL  Serial1
  //#define Y2_HARDWARE_SERIAL Serial1
  //#define Z_HARDWARE_SERIAL  Serial1
  //#define Z2_HARDWARE_SERIAL Serial1
  //#define E0_HARDWARE_SERIAL Serial1
  //#define E1_HARDWARE_SERIAL Serial1
  //#define E2_HARDWARE_SERIAL Serial1
  //#define E3_HARDWARE_SERIAL Serial1
  //#define E4_HARDWARE_SERIAL Serial1

  // Unused servo pins may be repurposed with SoftwareSerialM
  #define X_SERIAL_TX_PIN                 PA10   // SERVO3_PIN -- XS2 - 6
  #define Y_SERIAL_TX_PIN                 PA9   // SERVO2_PIN -- XS2 - 5
  #define Z_SERIAL_TX_PIN                 PC7   // SERVO1_PIN -- XS1 - 6
  #define E0_SERIAL_TX_PIN                PC13   // SERVO0_PIN -- XS1 - 5
  #define X_SERIAL_RX_PIN      X_SERIAL_TX_PIN
  #define Y_SERIAL_RX_PIN      Y_SERIAL_TX_PIN
  #define Z_SERIAL_RX_PIN      Z_SERIAL_TX_PIN
  #define E0_SERIAL_RX_PIN    E0_SERIAL_TX_PIN

  // Reduce baud rate for software serial reliability
  #if HAS_TMC_SW_SERIAL
    #define TMC_BAUD_RATE                  19200
    #endif
#endif`

I have also configured the configuration.h and the configuration_adv.h as described.

After uploading the firmware I get the TMC connection error in the display and I´m not able to control the stepper motors.
I got the TMC Drivers menu in the Configuration/Advanced Settings.

Attached files:
Configuration.h
Configuration_adv.h
pins_MKS_ROBIN_NANO.h
[Marlin_Configfiles.zip](https://github.com/MarlinFirmware/Marlin/files/5113999/Marlin_Configfiles.zip)
[Marlin_Configfiles.zip](https://github.com/MarlinFirmware/Marlin/files/5114001/Marlin_Configfiles.zip)

Thanks in advance

/Jens

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
