### ISSUE TITLE
Filament sensor handling non functional

### ISSUE THREAD

**Issue by tombueng** [MarlinFirmware/Marlin#19129]
2.0-bugfix branch 08/23/20
Filament sensor does not trigger M600 any more. 
M119 says the sensor seems working correctly.
Was working before with the same config.

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by GMagician** [comment]
Check if it is active using M412

**Comment by tombueng** [comment]
Thank you for the hint. Sensor was turned of.
