### ISSUE TITLE
[FR] Button Start

### ISSUE THREAD

**Issue by Su-Hee** [MarlinFirmware/Marlin#19128]
Hello,

I'm sorry to ask you such a rudimentary question.

Aduino Mega 2560 + RAMPS1.4 + REPRAP Smart controller (Marlin 1.1.9 install)
I used this to make a machine.

Assign a button to the Z_MAX pin and push it to automatically execute the "Roll.gco" file.

  #if ENABLED(ENDSTOPPULLUP_ZMAX)
      M23 /Roll.gco     // I don't know the command.
      M24                    // I don't know the command.

I think we can use this kind of grammar.
Does anyone know the command that can execute M code right away?

I am sorry for my poor English.  T.T;;

**Comment by ellensp** [comment]
Unfortunately Marlin 1 is no longer getting any development or support. 

In Marlin 2 examine the code in HAS_HOME blocks in MarlinCore.cpp as an example of how to trigger gcode from a button

For best results getting help with this, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
