### ISSUE TITLE
[BUG] M665 B (printable radius) works wrong

### ISSUE THREAD

**Issue by fatihaslan23** [MarlinFirmware/Marlin#19121]
I am using marlin bugfix 2.0.6

I am set 110mm printable radius before the upload firmware then upload and connect with repetier. Before the g33 calibration I want to change printable radius but m665 B code just changed Rod Trim B not printable radius.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by sjasonsmith** [comment]
In older versions of Marlin, the `B` parameter adjusted the **calibration** radius, not the `printable` radius. The printable radius can only be modified in the header file.

In Marlin 2.0, the calibration radius is no longer adjusted through `M665`. This change resolved issues with adjustable probe offsets using `M851`.

So, the documentation is incorrect, and the `B` parameter needs to be removed.

**BUT** it seems that new `A`, `B`, and `C` options were recently added (also not in documentation), which allows for adjusting "diagonal rod trim." That unfortunately means that the `B` parameter has both a stale documented meaning, and a completely unrelated new meaning.

**Comment by sjasonsmith** [comment]
@fatihaslan23 there are certainly documentation problems here. As for your initial desire to change the printable radius, you will need to edit `Configuration.h`.

**Comment by sjasonsmith** [comment]
The original reporter seems to have gone silent, but I think this should stay open due to the documentation issue.

**Comment by confrey59** [comment]
dear sjasonsmith,
may I know how to change the delta radius using M851? I'm trying to calibrate my Kossel, self-made, I haven't a z-probe and I need to do all manually; after calibrating X,Y,Z points by M666, I get a not flat bed (usually with negative Z values) but I can't correct it. Even if I change dìthe delta radius value in the Configuration.h, I get always the same situation. And I could never use the M665 procedure to change the Radius, even whrn I was using a 1.0.2 Marlin version. Any help is appreciated, thanks

**Comment by sjasonsmith** [comment]
`M851` only changes the nozzle to probe offset, which impacts the calculated calibration radius when using M33.

You set the actual delta radius using the `M665` `R` parameter.  It is saved in your EEPROM, so changing it in your header won't apply until you re-initialize your EEPROM with `M502`.

**Comment by confrey59** [comment]
Thank you, I'll try, giving you a feedback about. hoping it could solve.

**Comment by confrey59** [comment]
everything is OK; I was doing a wrong procedure to calibrate X,Y,Z points; then I cahnged the center level by modifying delta radius by M665, and storing all in ROM as you said. Now I have another question : because of I haven't a z-probe ,is there a way to do a G33 by hand? finding the Z=0 point manually? I wuld like to tune perfectly XY accuracy of my delta.
cheers
