### ISSUE TITLE
[FR] (DHT11 sensor codes)

### ISSUE THREAD

**Issue by aliys97** [MarlinFirmware/Marlin#19138]
I read the below link and added to my code but lots of errors showed in IDE while trying to compiling.

https://github.com/MarlinFirmware/Marlin/pull/5635/files/bc9aa8e9cd13cb614ca50e101d378166d19fd2ef

**Comment by aliys97** [comment]
<details><summary>Log Output</summary>

```
Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::DHT(unsigned char, unsigned char, unsigned char)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::DHT(unsigned char, unsigned char, unsigned char)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::begin(unsigned char)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::convertCtoF(float)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::convertFtoC(float)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::computeHeatIndex(float, float, bool)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::expectPulse(bool)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::read(bool)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::readTemperature(bool, bool)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::readHumidity(bool)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\DHT-sensor-library-master\DHT.cpp.o (symbol from plugin): In function `DHT::DHT(unsigned char, unsigned char, unsigned char)':

(.text+0x0): multiple definition of `DHT::computeHeatIndex(bool)'

sketch\DHT.cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Adafruit_Sensor-master\Adafruit_Sensor.cpp.o (symbol from plugin): In function `Adafruit_Sensor::printSensorDetails()':

(.text+0x0): multiple definition of `Adafruit_Sensor::printSensorDetails()'

sketch\Adafruit_Sensor.cpp.o (symbol from plugin):(.text+0x0): first defined here

HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':

(.text+0x0): multiple definition of `__vector_25'

sketch\MarlinSerial.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1

Error compiling for board Arduino Mega or Mega 2560.
This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```
</details>

**Comment by boelle** [comment]
try with vscode+platform.io extension

**Comment by boelle** [comment]
and remember to use  [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x)

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by ellensp** [comment]
That code is for marlin v1 and is not compatible with marlin v2

**Comment by aliys97** [comment]
here my  Configuration.h and Configuration_adv.h files as you requested.
[code.zip](https://github.com/MarlinFirmware/Marlin/files/5121500/code.zip)

**Comment by aliys97** [comment]
> Configurations, please
> Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
> requested in the Issue template) and drop them into your next reply.
> We'll check them over and see if anything is amiss.

here my Configuration.h and Configuration_adv.h files as you requested.
[code.zip](https://github.com/MarlinFirmware/Marlin/files/5121504/code.zip)

**Comment by aliys97** [comment]
> That code is for marlin v1 and is not compatible with marlin v2

my marlin version is 1.1x.
do you have any Idea?

**Comment by aliys97** [comment]
Any idea?!

**Comment by per1234** [comment]
Also posted to the Arduino forum:
https://forum.arduino.cc/index.php?topic=702121

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
