### ISSUE TITLE
[BUG] Stepper configuration not working (TMC2209)

### ISSUE THREAD

**Issue by BorisBrock** [MarlinFirmware/Marlin#19149]
# Bug Description

The configuration of the TMC2209 stepper drivers done in Configuration_adv.h seems to have no effect. The settings are not applied. E.g. I set the X_CURRENT to 580. When issuing the TMC_DEBUG command M122, a current of 800 is reported.

### My Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5125670/Configuration.zip)

### Steps to Reproduce

1. Change various TMC settings in Configuration_adv.h
2. Build & upload firmware
3. Do M122

**Expected behavior:**
The configured current should be retrurned.

**Actual behavior:**
A current of 800 is returned.

#### Additional Information

I have an Ender 3 with a BTT E3 Mini 1.2 Board. It uses TMC2209 stepper drivers.
Marlin is at version 2.0.6.

This is an example of my configuration:

> #if HAS_TRINAMIC_CONFIG
> 
>   #define HOLD_MULTIPLIER    0.5  // Scales down the holding current from run current
>   #define INTERPOLATE       true  // Interpolate X/Y/Z_MICROSTEPS to 256
> 
>   #if AXIS_IS_TMC(X)
>     #define X_CURRENT       580        // (mA) RMS current. Multiply by 1.414 for peak current.
>     #define X_CURRENT_HOME  X_CURRENT  // (mA) RMS current for sensorless homing
>     #define X_MICROSTEPS     16    // 0..256
>     #define X_RSENSE          0.11
>     #define X_CHAIN_POS      -1    // <=0 : Not chained. 1 : MCU MOSI connected. 2 : Next in chain, ...
>   #endif

This is the full result of M122 (TMC_DEBUG):

> Send: M122
> Recv: 		X	Y	Z	E
> Recv: Address		0	0	0	0
> Recv: Enabled		false	false	false	false
> Recv: Set current	800	800	800	800
> Recv: RMS current	795	795	795	795
> Recv: MAX current	1121	1121	1121	1121
> Recv: Run current	25/31	25/31	25/31	25/31
> Recv: Hold current	12/31	12/31	12/31	12/31
> Recv: CS actual	12/31	12/31	12/31	12/31
> Recv: PWM scale
> Recv: vsense		1=.18	1=.18	1=.18	1=.18
> Recv: stealthChop	true	true	true	true
> Recv: msteps		16	16	16	16
> Recv: tstep		max	max	max	max
> Recv: PWM thresh.
> Recv: [mm/s]
> Recv: OT prewarn	false	false	false	false
> Recv: pwm scale sum	14	14	14	14
> Recv: pwm scale auto	0	0	0	0
> Recv: pwm offset auto	36	36	36	36
> Recv: pwm grad auto	14	14	14	14
> Recv: off time	4	4	4	4
> Recv: blank time	24	24	24	24
> Recv: hysteresis
> Recv:  -end		2	2	2	2
> Recv:  -start		1	1	1	1
> Recv: Stallguard thrs	0	0	0	0
> Recv: uStep count	56	56	40	40
> Recv: DRVSTATUS	X	Y	Z	E
> Recv: sg_result	0	0	0	0
> Recv: stst
> Recv: olb
> Recv: ola
> Recv: s2gb
> Recv: s2ga
> Recv: otpw
> Recv: ot
> Recv: 157C
> Recv: 150C
> Recv: 143C
> Recv: 120C
> Recv: s2vsa
> Recv: s2vsb
> Recv: Driver registers:
> Recv: 		X	0xC0:0C:00:00
> Recv: 		Y	0xC0:0C:00:00
> Recv: 		Z	0xC0:0C:00:00
> Recv: 		E	0xC0:0C:00:00
> Recv: 
> Recv: 
> Recv: Testing X connection... OK
> Recv: Testing Y connection... OK
> Recv: Testing Z connection... OK
> Recv: Testing E connection... OK
> Recv: ok

As you can see the settings don't match.

**Comment by thisiskeithb** [comment]
Did you Initialize EEPROM after flashing? You can do it through the menu or by sending `M502` followed by `M500`.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
