### ISSUE TITLE
[FR] (define DHT11 as bed temperature sensor)

### ISSUE THREAD

**Issue by aliys97** [MarlinFirmware/Marlin#19155]
i want define DHT11 as bed temperature sensor. would you please help me?
and also show data in repitier software.

**Comment by ellensp** [comment]
not suitable for this application Temperature Range: 0°C to 50°C   (even if your bed only goes to 50, you need to be able to read some overshoot)

**Comment by aliys97** [comment]
My working temp is -10 upto 20. So it is suitable.

**Comment by ellensp** [comment]
it can't do -10

**Comment by aliys97** [comment]
Anyway is it possible or not?!!? 0 to 50 is fine.

**Comment by ellensp** [comment]
The timing requirements for the sensor are not compatible with a 3d printer. 3d printer requires precise timing or you get blobs.
This sensor requires precise timing to read it...  one of these has to give, you can't have both.

**Comment by AnHardt** [comment]
By writing "bad" instead of "bed" you hit the nail on the head.
On top of the already said the DHTs have a insufficient datarate (0.5 to 1 reading/second depending on the model). Marlin heaters need at least 4 to 5 readings/second (without additional handstands like extra buffering).
