### ISSUE TITLE
[BUG] MKS GEN L V1.0 + MKS LCS 12864A no display

### ISSUE THREAD

**Issue by Frytkownica** [MarlinFirmware/Marlin#19159]
### Bug Description
I tried several suggestions but still - LCD only lits up, without any display.

### My Configurations
MKS Gen L  + MKS LCD12864A V1.0
compiled in Visual Studio Code

[Settings.zip](https://github.com/MarlinFirmware/Marlin/files/5130131/Settings.zip)

### Steps to Reproduce

1. Change settings to have 
#define MOTHERBOARD BOARD_MKS_GEN_L  
#define MKS_LCD12864
2. Complie
3. Have small blue light lamp instead of printers display
![20200826_153736](https://user-images.githubusercontent.com/5046251/91310544-4d949700-e7b2-11ea-9133-f18014015372.jpg)

**Expected behavior:** 
Graphical status display

**Actual behavior:**
Modern art installation

#### Additional Information

I tried delays changing, brightness change, different board (SKR 1.3) all with no results. Is it possible that pins are not correctly defined for this one or any other known issue?

**Comment by ellensp** [comment]
comment out these, you shouldn't need huge delays like this on a 8 bit board. 
#define ST7920_DELAY_1 DELAY_NS(500)
#define ST7920_DELAY_2 DELAY_NS(500)
#define ST7920_DELAY_3 DELAY_NS(500)

**Comment by sjasonsmith** [comment]
Try re-initializing your EEPROM either from the LCD or using M502 then M500. This screen might use software adjusted contrast, and could be using a bad default stored to EEPROM prior to defining the display.

**Comment by ellensp** [comment]
Or play with setting contrast eg M250 C200

**Comment by Frytkownica** [comment]
Hi guys. Thanks for feply.
i was using this board for REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER, and delays were set 250, 250, 0 to work okay. I thought maybe higer ones are better. I tried with those values commented - no difference since. I tried just chaging only2 values like in reproduction field, on both 2.0.x and 1.9.x marlins to be sure nothing else influence this issue.

i also tried M250. This is not it. Display does not change when tried 120, 200 and 255 values.

**Comment by thisiskeithb** [comment]
> Is it possible that pins are not correctly defined for this one or any other known issue?

Pinout is correct since `MKS_LCD12864` is simply an alias for `MKS_MINI_12864` (which works on a MKS Gen-L), but it uses different contrast settings.

Having said that, I've run into some issues getting the B variant (for 32-bit) working on some 32-bit boards where swapping in a real MKS Mini 12864 controller would display/work fine.

I've asked Makerbase/MKS to look into the issue, but maybe they can chime in here. @makerbase-mks: Any troubleshooting tips?

**Comment by Frytkownica** [comment]
I orginally tried to have it running on SKR board, but found out that A ones should be ran on 8 bit boards. This is why i try to make it run on MKS Gen L :)

**Comment by borland1** [comment]
I saw a seller's listing that recommends these settings/changes for MKS LCD 12864A...

_Configuration.h:_
`#define MKS_MINI_12864`

_Marlin/src/lcd/dogm/u8g_dev_uc1701_mini12864_HAL.cpp, at line 100_
`UC1701_CONTRAST(0x32),      // set contrast from default (0x27) to 0x32`

**Comment by thisiskeithb** [comment]
> I saw a seller's listing that recommends these settings/changes for MKS LCD 12864A...

That’s for Marlin `1.1.x`.

**Comment by borland1** [comment]
Marlin 2.0.x still uses the outdated U8glib graphics library.  Why would there be any difference?

**Comment by thisiskeithb** [comment]
> Marlin 2.0.x still uses the outdated U8glib graphics library. Why would there be any difference?

Instructions are different for Marlin `2.0.x` and those changes have already been merged. You simply have to enable `MKS_LCD12864`.

**Comment by NeoMod** [comment]
If it is worth a note, the same thing happens on an SGEN L with LCD12864 B.

**Comment by makerbase-mks** [comment]
@thisiskeithb @Frytkownica 
Marlin 2.0.6
I has test it of MKS LCD12864A on 2560 motherboard and i find it's can be use; 
but i test it of MKS LCD12864B on SGEN_L or Robin E3 is cann't be use
Marlin2.0.1 all can be use

**Comment by NeoMod** [comment]
@makerbase-mks thanks for the feedback! So it seems there is some kind of problem in the latest release.

**Comment by Frytkownica** [comment]
> @thisiskeithb @Frytkownica
> Marlin 2.0.6
> I has test it of MKS LCD12864A on 2560 motherboard and i find it's can be use;
> but i test it of MKS LCD12864B on SGEN_L or Robin E3 is cann't be use
> Marlin2.0.1 all can be use

But based on the boards names I'm using A version nad Gen L is 8 bit.
If LCD was incorrectly named, it should have worked on 32bit SKR board, but it also didn't. Also no way GEN L is faked because It wouldn't compile.

Please provide a way to troubleshoot the display, because it seems all is okays software wise in my opinion.

**Comment by thisiskeithb** [comment]
> Marlin2.0.1 all can be use

@makerbase-mks Can you look into why it doesn't work with a current version of Marlin?

**Comment by borland1** [comment]
> @thisiskeithb @Frytkownica
> Marlin 2.0.6
> I has test it of MKS LCD12864A on 2560 motherboard and i find it's can be use;
> but i test it of MKS LCD12864B on SGEN_L or Robin E3 is cann't be use
> Marlin2.0.1 all can be use

I am confused by earlier discussion of display driver ST7920, because I was assuming the correct display driver is UC1701.  Is there a Wiki for the MKS LCD12864x display that provides the specification for the correct driver?

**Comment by makerbase-mks** [comment]
@thisiskeithb I doing testing it.

**Comment by makerbase-mks** [comment]
MKS MINI12864 ： The driver is ST7565R
MKS LCD12864A/B ： The driver is ST7567
I just guess that it may be caused by initialization, but so far, no real reason has been found, and testing is needed.

**Comment by Frytkownica** [comment]
Is there any way i could help and speed this up? : )

**Comment by makerbase-mks** [comment]
@thisiskeithb @Frytkownica 
MKS has fix it: https://github.com/MarlinFirmware/Marlin/pull/19269

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by makerbase-mks** [comment]
MKS Gen-l V1 and MKS Gen-l V2.x comparison, MKS Gen-L V2.x only add TMC UART, SPI interface. The last version marlin bugfix on the MKS Gen_L V2.1 motherboard. It can be used normally all the time
![image](https://user-images.githubusercontent.com/12979070/92341272-ca4b3d80-f0ef-11ea-8a29-f0b94a718947.png)

**Comment by Frytkownica** [comment]
<3 much love
Works like a charm now :) thanku you
