### ISSUE TITLE
[BUG] format-overflow when #define LCD_LANGUAGE ru

### ISSUE THREAD

**Issue by kpter** [MarlinFirmware/Marlin#19157]
### Bug Description

At compile time, there is a warning:
```
In file included from Marlin\src\lcd\menu\../../inc/../core/language.h:386,
                 from Marlin\src\lcd\menu\../../inc/MarlinConfig.h:45,
                 from Marlin\src\lcd\menu\../ultralcd.h:24,
                 from Marlin\src\lcd\menu\menu.h:24,
                 from Marlin\src\lcd\menu\menu_item.h:24,
                 from Marlin\src\lcd\menu\menu_motion.cpp:31:
Marlin\src\lcd\menu\menu_motion.cpp: In function 'void _menu_move_distance(AxisEnum, screenFunc_t, int8_t)':
Marlin\src\lcd\menu\menu_motion.cpp:202:31: warning: ' РјРј' directive writing 5 bytes into a region of size 3 [-Wformat-overflow=]
  202 |       sprintf_P(tmp, GET_TEXT(MSG_MOVE_Z_DIST), dtostrf(SHORT_MANUAL_Z_MOVE, 1, digs, numstr));
Marlin\src\lcd\menu\../../inc/../core/multi_language.h:74:49: note: in definition of macro 'GET_TEXT'
   74 |   #define GET_TEXT(MSG) GET_LANG(LCD_LANGUAGE)::MSG
      |                                                 ^~~
Marlin\src\lcd\menu\menu_motion.cpp:202:16: note: 'sprintf' output 23 or more bytes into a destination of size 20
  202 |       sprintf_P(tmp, GET_TEXT(MSG_MOVE_Z_DIST), dtostrf(SHORT_MANUAL_Z_MOVE, 1, digs, numstr));

```
After the firmware the processor, stops working menu item  `  PROGMEM Language_Str MSG_MOVE_Z                          = _UxGT("Движение по Z");`  when the menu language has been selected "ru",
but works fine in "en" language.

### My Configurations

[Configs and diffs.zip](https://github.com/MarlinFirmware/Marlin/files/5129117/Configs.and.diffs.zip)

### Steps to Reproduce

- Latest Marlin-bugfix-2.0.x
- Only when the menu language has been selected "ru".

#### Additional Information

I reduced the length of the text in **language_ru.h**  
```
  PROGMEM Language_Str MSG_MOVE_Z_DIST                     = _UxGT("Движен. %s мм");
```
and error is gone.
Also, it works fine at Marlin-bugfix-2.0.x of 06.08.2020 and maybe mistake in last 20 days in `Marlin\src\lcd\menu\menu_motion.cpp`

**Comment by thisiskeithb** [comment]
This should be fixed in https://github.com/MarlinFirmware/Marlin/commit/e8dcbd8300680f0d0f2032065952181f51d52874
