### ISSUE TITLE
Unable to enable/disable individual stepper motors using gcode M17 and M18

### ISSUE THREAD

**Issue by jnichols** [MarlinFirmware/Marlin#19153]
Unable to enable or disable individual stepper motors.  Attempts to use gcodes to hold the axes in place while the filament is being replaced.  The M17 and M18 without parameters work as expected, it is only when parameters are added they do not enable or disable an individual stepper as documented.

Marlin v2.0.6 commit 96e29cd 
Also tested with the bugfix-2.0.x code branch.
Creality Ender-3 v2
v4.2.2 controller board
Sending gcodes with Octaprint Terminal version 1.4.2

Steps to reproduce 
M18 
#Verified all axis and extruder are disabled
M17 X Y Z
#All axes are enabled, however with the extruder is also enabled. 
M18 E
#Extruder remains enabled
M18 X
#Disabled all axes and extruder.  The expected behavior is to only disable the X-axis. 

It seems that the E parameter is ignored in both M17 and M18 commands.  
M17 E   #This won't enable the extruder stepper.
M18 E   #This won't disabled extruder stepper.

Also, it seems that if any axis is specified it will enable or disable all axes and extruder.
M17 Y 
#Will enable all axes and extruder.  The expected behavior is to only enable the Y-axis. 
M18 X 
#Will disable all axes and extruder.  The expected behavior is to only disable the X-axis. 

[ConfigurationFiles_2.0.6.zip](https://github.com/MarlinFirmware/Marlin/files/5127567/ConfigurationFiles_2.0.6.zip)
[ConfigurationFiles_bugfix_2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/5127568/ConfigurationFiles_bugfix_2.0.x.zip)

[OctoPrint_Terminal_Out.zip](https://github.com/MarlinFirmware/Marlin/files/5127573/OctoPrint_Terminal_Out.zip)

**Comment by ellensp** [comment]
v4.2.2 controller board only has one shared enable pin for all steppers drivers. You cannot individually enable/disable the stepper motors. It is all enabled or all disabled. 
This is a hardware limitation of this controller.
