### ISSUE TITLE
Marlin stretches the layer on the z-Axis

### ISSUE THREAD

**Issue by cavemanatwork** [MarlinFirmware/Marlin#1916]
Marlin 1.0.2 on Ramps 1.4

During printig with a dual Extruder Marlin stretches the Z-Axis exactly to the level where are 2 Extruders working. The Layers can't stick together. For example at the end of a Skirt, Marlin print the Layers in the right height.

**Comment by cavemanatwork** [comment]
Sorry, it is a 1.0.3 Dev from 09.April.

**Comment by AnHardt** [comment]
Anyone out there who understands the problem - or can reproduce a bug?

**Comment by thinkyhead** [comment]
I'm not sure I understand the problem as you've stated it. And, have you tried the current Development HEAD? For all we know this may already be fixed.
