### ISSUE TITLE
Auto center of model, when outside build plate

### ISSUE THREAD

**Issue by dscvejl** [MarlinFirmware/Marlin#19175]
I would be nice if the firmware gives a warning, if part of the print is outside the build plate.

A nice feature would be that the firmware ask, if you want to auto center the model.

**Comment by ellensp** [comment]
Marlin processes model layer by layer. it is not possible to do this in firmware

**Comment by dscvejl** [comment]
What I'm talking about is a pre-script that runs through the entire g-code before starting the printer.
I know that it adds to the time before you start printing, but most printers is waiting for the bed to warm anyway.

It would be nice with at least a warning that some of the g-code is outside the print area, before you start a multiday print.

**Comment by AnHardt** [comment]
At least a message when software endstops are/have been hit during the print could be helpful in some cases to be warned for cropped parts.
Shifting/centering the part is not possible before the whole part has been seen/printed - but how much to shift, has to be known before the first line is printed.

**Comment by AnHardt** [comment]
> pre-script

Yes. But please before sending to Marlin.
