### ISSUE TITLE
[BUG 2.0.6.1] NeoPixel sanity check fails for BTT E3 Mini 1.2 compilation (LPC1768)

### ISSUE THREAD

**Issue by Arakon** [MarlinFirmware/Marlin#19180]
### Bug Description

When attempting to compile for the above mentioned board, it errors:
d:\marlin-2.0.6.1\marlin\src\hal\stm32f1\inc\sanitycheck.h:56:4: error: #error "NEOPIXEL_LED (Adafruit NeoPixel) is not supported for HAL/STM32F1. Comment out this line to proceed at your own risk!"
   #error "NEOPIXEL_LED (Adafruit NeoPixel) is not supported for HAL/STM32F1. Comment out this line to proceed at your own risk!"

Commenting out the check will allow it to compile and function perfectly fine.

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5144288/Marlin.zip)

### Steps to Reproduce

Attempt to compile with the attached config.

**Expected behavior:** [What you expect to happen]

Expect it to compile normally, which it does with 2.0.6 (and 2.0.6 bugfix branch).

**Actual behavior:** [What actually happens]

See above.

**Comment by thisiskeithb** [comment]
This sanity check was created on purpose and is not a bug. See https://github.com/MarlinFirmware/Marlin/pull/18833

Also, you've modified `platformio.ini` from stock Marlin to use a different NeoPixel library for your board. This library does not universally work for all `STM32F1`-based boards, so you'd still have to disable the sanity check if you wanted to enable NeoPixels.

------

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
