### ISSUE TITLE
#error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."[FR] (título de solicitação de recurso)

### ISSUE THREAD

**Issue by menezesfreitas** [MarlinFirmware/Marlin#19182]
<> Executing task in folder Marlin-2.0.x: C:\Users\Wesley\.platformio\penv\Scripts\platformio.exe run <

Processing mks_robin_nano35 (platform: ststm32@~6.1.0; board: genericSTM32F103VE; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
Copying MKS Assets
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103VE.html
PLATFORM: ST STM32 6.1.1 > STM32F103VE (64k RAM. 512k Flash)
HARDWARE: STM32F103VET6 72MHz, 64KB RAM, 512KB Flash
DEBUG: Current (jlink) External (blackmagic, jlink, stlink)
PACKAGES:
 - framework-arduinoststm32-maple 2.10000.200103 (1.0.0)
 - tool-stm32duino 1.0.2 
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 30 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <SoftwareSerialM> 1.0.0
|-- <lvgl> 6.1.1
|-- <STM32ADC> 1.0
|-- <EEPROM>
|-- <USBComposite for STM32F1> 0.91
|-- <Wire> 1.0
|-- <FreeRTOS701>
|-- <Servo(STM32F1)> 1.1.2
Building in release mode
Compiling .pio\build\mks_robin_nano35\FrameworkArduinoVariant\board.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduinoVariant\wirish\boards.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduinoVariant\wirish\boards_setup.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduinoVariant\wirish\start.S.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduinoVariant\wirish\start_c.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduinoVariant\wirish\syscalls.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\HardwareTimer.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\Print.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\WString.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\avr\dtostrf.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\cxxabi-compat.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\ext_interrupts.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\hooks.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\itoa.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\adc.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\adc_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\bkp_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\dac.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\dma.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\dma_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\exc.S.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\exti.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\exti_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\flash.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\fsmc_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\gpio.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\gpio_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\i2c.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\i2c_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\iwdg.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\nvic.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\pwr.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\rcc.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\rcc_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\spi.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\spi_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\stm32f1\performance\isrs.S.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\stm32f1\performance\vector_table.S.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\systick.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\timer.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\timer_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\usart.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\usart_f1.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\usart_private.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\usb\stm32f1\usb.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\usb\stm32f1\usb_cdcacm.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\usb\stm32f1\usb_reg_map.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\usb\usb_lib\usb_core.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\usb\usb_lib\usb_init.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\usb\usb_lib\usb_mem.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\usb\usb_lib\usb_regs.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\libmaple\util.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\main.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\new.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\pwm.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\sdio.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\stm32f1\util_hooks.c.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\stm32f1\wiring_pulse_f1.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\stm32f1\wirish_debug.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\stm32f1\wirish_digital_f1.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\tone.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\usb_serial.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\wirish_analog.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\wirish_digital.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\wirish_math.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\wirish_shift.cpp.o
Compiling .pio\build\mks_robin_nano35\FrameworkArduino\wirish_time.cpp.o
Compiling .pio\build\mks_robin_nano35\src\src\HAL\STM32F1\HAL.cpp.o
Compiling .pio\build\mks_robin_nano35\src\src\HAL\STM32F1\HAL_SPI.cpp.o
In file included from Marlin\src\HAL\STM32F1\../../inc/../pins/pins.h:514:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:32,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../pins/stm32f1/pins_MKS_ROBIN_NANO_V2.h:291:0: warning: "XPT2046_X_CALIBRATION" redefined
   #define XPT2046_X_CALIBRATION           -17253
 
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../../Configuration.h:2248:0: note: this is the location of the previous definition
   #define XPT2046_X_CALIBRATION  12149
 
In file included from Marlin\src\HAL\STM32F1\../../inc/../pins/pins.h:514:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:32,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../pins/stm32f1/pins_MKS_ROBIN_NANO_V2.h:292:0: warning: "XPT2046_Y_CALIBRATION" redefined
   #define XPT2046_Y_CALIBRATION            11579

In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../../Configuration.h:2249:0: note: this is the location of the previous definition
   #define XPT2046_Y_CALIBRATION  -8746

In file included from Marlin\src\HAL\STM32F1\../../inc/../pins/pins.h:514:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:32,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../pins/stm32f1/pins_MKS_ROBIN_NANO_V2.h:293:0: warning: "XPT2046_X_OFFSET" redefined
   #define XPT2046_X_OFFSET                   514

In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../../Configuration.h:2250:0: note: this is the location of the previous definition
   #define XPT2046_X_OFFSET         -35
 
In file included from Marlin\src\HAL\STM32F1\../../inc/../pins/pins.h:514:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:32,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../pins/stm32f1/pins_MKS_ROBIN_NANO_V2.h:294:0: warning: "XPT2046_Y_OFFSET" redefined
   #define XPT2046_Y_OFFSET                   -24
 
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../../Configuration.h:2251:0: note: this is the location of the previous definition
   #define XPT2046_Y_OFFSET         256
 
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:41:0,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:707:4: error: #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
   #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
    ^~~~~
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:825:6: error: #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
     #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
      ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/../pins/pins.h:514:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:32,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:35:
Marlin\src\HAL\STM32F1\../../inc/../pins/stm32f1/pins_MKS_ROBIN_NANO_V2.h:291:0: warning: "XPT2046_X_CALIBRATION" redefined
   #define XPT2046_X_CALIBRATION           -17253
 
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:35:
Marlin\src\HAL\STM32F1\../../inc/../../Configuration.h:2248:0: note: this is the location of the previous definition
   #define XPT2046_X_CALIBRATION  12149

In file included from Marlin\src\HAL\STM32F1\../../inc/../pins/pins.h:514:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:32,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:35:
Marlin\src\HAL\STM32F1\../../inc/../pins/stm32f1/pins_MKS_ROBIN_NANO_V2.h:292:0: warning: "XPT2046_Y_CALIBRATION" redefined
   #define XPT2046_Y_CALIBRATION            11579

In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:35:
Marlin\src\HAL\STM32F1\../../inc/../../Configuration.h:2249:0: note: this is the location of the previous definition
   #define XPT2046_Y_CALIBRATION  -8746
 
In file included from Marlin\src\HAL\STM32F1\../../inc/../pins/pins.h:514:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:32,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:35:
Marlin\src\HAL\STM32F1\../../inc/../pins/stm32f1/pins_MKS_ROBIN_NANO_V2.h:293:0: warning: "XPT2046_X_OFFSET" redefined
   #define XPT2046_X_OFFSET                   514

In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:35:
Marlin\src\HAL\STM32F1\../../inc/../../Configuration.h:2250:0: note: this is the location of the previous definition
   #define XPT2046_X_OFFSET         -35

In file included from Marlin\src\HAL\STM32F1\../../inc/../pins/pins.h:514:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:32,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:35:
Marlin\src\HAL\STM32F1\../../inc/../pins/stm32f1/pins_MKS_ROBIN_NANO_V2.h:294:0: warning: "XPT2046_Y_OFFSET" redefined
   #define XPT2046_Y_OFFSET                   -24

In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:35:
Marlin\src\HAL\STM32F1\../../inc/../../Configuration.h:2251:0: note: this is the location of the previous definition
   #define XPT2046_Y_OFFSET         256

In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:41:0,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:35:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:707:4: error: #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."        
   #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
    ^~~~~
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:825:6: error: #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
     #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
      ^~~~~
*** [.pio\build\mks_robin_nano35\src\src\HAL\STM32F1\HAL.cpp.o] Error 1
*** [.pio\build\mks_robin_nano35\src\src\HAL\STM32F1\HAL_SPI.cpp.o] Error 1
========================================================== [FAILED] Took 93.92 seconds ==========================================================
Environment               Status    Duration
------------------------  --------  ------------
mega2560                  IGNORED
mega2560ext               IGNORED
mega1280                  IGNORED
MightyBoard1280           IGNORED
MightyBoard2560           IGNORED
rambo                     IGNORED
FYSETC_F6_13              IGNORED
FYSETC_F6_14              IGNORED
sanguino644p              IGNORED
sanguino1284p             IGNORED
melzi                     IGNORED
melzi_optiboot            IGNORED
melzi_optimized           IGNORED
at90usb1286_cdc           IGNORED
at90usb1286_dfu           IGNORED
DUE                       IGNORED
DUE_USB                   IGNORED
DUE_debug                 IGNORED
DUE_archim                IGNORED
DUE_archim_debug          IGNORED
SAMD51_grandcentral_m4    IGNORED
LPC1768                   IGNORED
LPC1769                   IGNORED
STM32F103RC               IGNORED
STM32F103RC_meeb          IGNORED
STM32F103RC_fysetc        IGNORED
STM32F103RC_btt           IGNORED
STM32F103RC_btt_USB       IGNORED
STM32F103RC_btt_512K      IGNORED
STM32F103RC_btt_512K_USB  IGNORED
STM32F103RE               IGNORED
STM32F103RE_btt           IGNORED
STM32F103RE_btt_USB       IGNORED
STM32F4                   IGNORED
STM32F7                   IGNORED
ARMED                     IGNORED
STM32F103VE_GTM32         IGNORED
STM32F103VE_longer        IGNORED
mks_robin_mini            IGNORED
mks_robin_nano35          FAILED    00:01:33.917
mks_robin                 IGNORED
mks_robin_stm32           IGNORED
mks_robin_pro             IGNORED
trigorilla_pro            IGNORED
mks_robin_e3              IGNORED
mks_robin_lite            IGNORED
mks_robin_lite3           IGNORED
jgaurora_a5s_a1           IGNORED
STM32F103CB_malyan        IGNORED
STM32F070RB_malyan        IGNORED
malyan_M300               IGNORED
chitu_f103                IGNORED
chitu_v5_gpio_init        IGNORED
STM32F103RET6_creality    IGNORED
STM32F401VE_STEVAL        IGNORED
FLYF407ZG                 IGNORED
FYSETC_S6                 IGNORED
STM32F407VE_black         IGNORED
BIGTREE_SKR_PRO           IGNORED
BIGTREE_GTR_V1_0          IGNORED
BIGTREE_BTT002            IGNORED
LERDGEX                   IGNORED
LERDGES                   IGNORED
LERDGEK                   IGNORED
rumba32                   IGNORED
esp32                     IGNORED
teensy31                  IGNORED
teensy35                  IGNORED
linux_native              IGNORED
include_tree              IGNORED
===================================================== 1 failed, 0 succeeded in 00:01:33.917 =====================================================The terminal process "C:\Users\Wesley\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5144495/Marlin.zip)

![Erro Marlin](https://user-images.githubusercontent.com/68997315/91622833-6302f000-e96f-11ea-8f79-6ee6e63bd494.jpg)

Have you read Marlin's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md

Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use one of the support links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

Before filing an issue be sure to test the "bugfix" branches to see whether the issue has been resolved.

-->

### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by thisiskeithb** [comment]
This is not a bug. Comment out `SHOW_CUSTOM_BOOTSCREEN` when using `TFT_LVGL_UI_SPI`.

----

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
