### ISSUE TITLE
print stopps after printing 5cm of the skirt

### ISSUE THREAD

**Issue by coolduke666** [MarlinFirmware/Marlin#19222]
### Bug Description

after upating from 2.0.6 to 2.0.6.1 print stopps within seconds after printing 10cm of the skirt
with 2.0.6 everything works fine!

only happens with larger Gcode files ... very small STL prints fine!

setup: RAMPS 1.4 with RPI (octoprint)

marlin 2.0.6 config:
[MyMarlin_2.0.6.zip](https://github.com/MarlinFirmware/Marlin/files/5157196/MyMarlin_2.0.6.zip)

### My Configurations
Marlin 2.0.6.1 config
[MyMarlin_2.0.6.1.zip](https://github.com/MarlinFirmware/Marlin/files/5157215/MyMarlin_2.0.6.1.zip)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

simply print

**Actual behavior:** [What actually happens]

stopps after staring print

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by daleckystepan** [comment]
What do you mean by "stop printing"? Any error on display or serial? Which?
Can you provide gcode file?

**Comment by coolduke666** [comment]
simply stopped printing .... no error nothing....  only able to hard reset it.

**Comment by coolduke666** [comment]
I think it has to do with the open issue regarding the probing margin (#19167) ... small prints work fine - large print don't (maybe because the interfere with the probing margin - if that makes sense...)

can provide the gcode tommorrow

**Comment by coolduke666** [comment]
[GCode.zip](https://github.com/MarlinFirmware/Marlin/files/5160452/GCode.zip)

attached the 2 GCodes... one that worked and the larger one, which didnt work. again simply stopped the print after a few centimeters of the skirt.

**Comment by zonalimitatore** [comment]
Me too same problem....But it's happen time.One after 1h printing,and last one tonight,stop print after 3mm of brim.No error,no sound,lcd not seems dont receive command.Only hardreset
skr 1.4T

**Comment by boelle** [comment]
Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

**Comment by zonalimitatore** [comment]
27 July

**Comment by coolduke666** [comment]
Is there a fix in 2.0.7?

**Comment by ellensp** [comment]
there are several hundred fixes in 2.0.7. but since your issue is not replicable by most of us.. you will have to try it and see.

**Comment by boelle** [comment]
@coolduke666 or try  [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) 2.0.7 is just a frozen copy of that anyway
