### ISSUE TITLE
[BUG]  Z_MULTI_ENDSTOPS on SKR 1.4 and driver TMC2209 not work. If z_min or z2_min triggered all z axis stopped

### ISSUE THREAD

**Issue by lucableve** [MarlinFirmware/Marlin#19237]
Marlin: 2.0.6.1 and bugfix-2.0.x§

I have two axis z and two endstop (Anycubic i3 mega), I configured NUM_Z_STEPPER_DRIVERS = 2 and assign endstop pin to x_max and setting the x_max pin value into pins skr 1.4 .
When endstop if trigger z_min or z2_min all axis z stopped simultaneously and not z_min for z1 and z2_min for z2.

My m119 is correct, endstops triggered are detected

My setup:
Diag Pin tmc2209 cut
2 step driver, one for axis z ( e1 => z2)

Configuration:
#define USE_XMAX_PLUG
#define Z2_DRIVER_TYPE TMC2209

Configuration adv : 
#define ENDSTOPS_ALWAYS_ON_DEFAULT
#define NUM_Z_STEPPER_DRIVERS 2 
#define Z_MULTI_ENDSTOPS
#define Z2_USE_ENDSTOP  _XMAX_

Pin SKR 1.4:
#define X_MAX_PIN P1_26

My Configuration Files
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5165282/Marlin.zip)

**Comment by gustavoalcantara-aravena** [comment]
I have the same issue, but my printer have a skr 1.4 BTT board, and I have the same printer

**Comment by Kyosuke33** [comment]
Same issue for me but with MKS SGEN L v2 32bits on my Sapphire Plus Core XY.
