### ISSUE TITLE
[BUG] Not Compile Marlin 2.0.6.1 for BTT V1.4 Turbo

### ISSUE THREAD

**Issue by Kris83is** [MarlinFirmware/Marlin#19248]
Hello, someone can help me to solve this problem below?
I am trying to compile Marlin for BTT SKR V1.4 Turbo on my pc with windows 7 pro.
Thanks.

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/nxplpc-arduino-lpc176x/nxp_lpc1769.html
PLATFORM: NXP Arduino LPC176x 0.1.3 > NXP LPC1769
HARDWARE: LPC1769 120MHz, 31.97KB RAM, 464KB Flash
DEBUG: Current (cmsis-dap) On-board (cmsis-dap) External (blackmagic, jlink)
PACKAGES:
 - framework-arduino-lpc176x 0.2.4
 - toolchain-gccarmnoneeabi 1.90301.200702 (9.3.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ off, Compatibility ~ strict
Found 3 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Servo> 1.0.0
|-- <TMCStepper> 0.7.1
|-- <LiquidCrystal> 1.0.0
Building in release mode

Unable to find destination disk (Command 'fsutil fsinfo drives' returned non-zero exit status 1.)
Please select it in platformio.ini using the upload_port keyword (https://docs.platformio.org/en/latest/projectconf/section_env_upload.html) or copy
the firmware (.pio/build/LPC1769/firmware.bin) manually to the appropriate disk

Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\DebugMonitor.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\HAL.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\HAL_SPI.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\MarlinSerial.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\eeprom_flash.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\eeprom_sdcard.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\eeprom_wired.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\fast_pwm.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\include\digipot_mcp4451_I2C_routines.c.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\include\i2c_util.c.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\main.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\tft\tft_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\tft\xpt2046.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\timers.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\u8g\LCD_I2C_routines.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\u8g\LCD_pin_routines.c.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\u8g\u8g_com_HAL_LPC1768_hw_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\u8g\u8g_com_HAL_LPC1768_ssd_hw_i2c.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\u8g\u8g_com_HAL_LPC1768_st7920_hw_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\u8g\u8g_com_HAL_LPC1768_st7920_sw_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\u8g\u8g_com_HAL_LPC1768_sw_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\usb_serial.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\LPC1768\watchdog.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\HAL_spi_L6470.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\backtrace.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwarm.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwarm_arm.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwarm_thumb.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwarmbytab.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwarmmem.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwinder.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\backtrace\unwmemaccess.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\eeprom_api.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\eeprom_if_i2c.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\eeprom_if_spi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\esp_wifi.cpp.o
Compiling .pio\build\LPC1769\src\src\HAL\shared\servo.cpp.o
Compiling .pio\build\LPC1769\src\src\MarlinCore.cpp.o
Compiling .pio\build\LPC1769\src\src\core\serial.cpp.o
Compiling .pio\build\LPC1769\src\src\core\utility.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\babystep.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\bedlevel.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\ubl\ubl.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\ubl\ubl_G29.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\bedlevel\ubl\ubl_motion.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\caselight.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\host_actions.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\leds\neopixel.cpp.o
Compiling .pio\build\LPC1769\src\src\feature\tmc_util.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\G42.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\M420.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\ubl\G29.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\bedlevel\ubl\M421.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\calibrate\G28.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M200-M205.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M220.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M221.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M301.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M302.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M304.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M575.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M672.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\config\M92.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M108_M112_M410.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M111.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M120_M121.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M17_M18_M84.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M211.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M226.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M280.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M350_M351.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M380_M381.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M400.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M42.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M80_M81.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M85.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M993_M994.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M997.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\M999.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\control\T.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\eeprom\M500-M504.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\advance\M900.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\digipot\M907-M910.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\pause\G27.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\trinamic\M122.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\trinamic\M569.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\trinamic\M906.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\feature\trinamic\M911-M914.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\gcode.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\geometry\G17-G19.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\geometry\G92.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\geometry\M206_M428.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M110.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M113.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M114.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M115.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M118.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M119.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\host\M876.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\lcd\M0_M1.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\lcd\M117.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\lcd\M145.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\lcd\M300.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\G0_G1.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\G2_G3.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\G4.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\G5.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\motion\M290.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\parser.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\queue.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M1001.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M20.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M21_M22.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M23.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M24_M25.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M26.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M27.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M28_M29.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M30.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M32.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M33.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M34.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M524.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\sd\M928.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\stats\M31.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\stats\M75-M78.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temp\M104_M109.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temp\M105.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temp\M106_M107.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temp\M140_M190.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temp\M141_M191.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temp\M155.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\temp\M303.cpp.o
Compiling .pio\build\LPC1769\src\src\gcode\units\M82_M83.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\HD44780\lcdprint_hd44780.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\HD44780\ultralcd_HD44780.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\extui\anycubic_chiron_lcd.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\extui\anycubic_i3mega_lcd.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\extui\ui_api.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\fontutils.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\lcdprint.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_advanced.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_configuration.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_custom.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_game.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_main.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_media.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_mixer.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_motion.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_temperature.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_tmc.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_tune.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\menu\menu_ubl.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\touch\touch_buttons.cpp.o
Compiling .pio\build\LPC1769\src\src\lcd\ultralcd.cpp.o
Compiling .pio\build\LPC1769\src\src\libs\BL24CXX.cpp.o
Compiling .pio\build\LPC1769\src\src\libs\W25Qxx.cpp.o
Compiling .pio\build\LPC1769\src\src\libs\buzzer.cpp.o
Compiling .pio\build\LPC1769\src\src\libs\crc16.cpp.o
Compiling .pio\build\LPC1769\src\src\libs\hex_print.cpp.o
Compiling .pio\build\LPC1769\src\src\libs\least_squares_fit.cpp.o
Compiling .pio\build\LPC1769\src\src\libs\nozzle.cpp.o
Compiling .pio\build\LPC1769\src\src\libs\numtostr.cpp.o
Compiling .pio\build\LPC1769\src\src\libs\stopwatch.cpp.o
Compiling .pio\build\LPC1769\src\src\libs\vector_3.cpp.o
Compiling .pio\build\LPC1769\src\src\module\endstops.cpp.o
Compiling .pio\build\LPC1769\src\src\module\motion.cpp.o
Compiling .pio\build\LPC1769\src\src\module\planner.cpp.o
Compiling .pio\build\LPC1769\src\src\module\planner_bezier.cpp.o
Compiling .pio\build\LPC1769\src\src\module\servo.cpp.o
Compiling .pio\build\LPC1769\src\src\module\settings.cpp.o
Compiling .pio\build\LPC1769\src\src\module\stepper.cpp.o
Compiling .pio\build\LPC1769\src\src\module\stepper\indirection.cpp.o
Compiling .pio\build\LPC1769\src\src\module\stepper\trinamic.cpp.o
Compiling .pio\build\LPC1769\src\src\module\temperature.cpp.o
Compiling .pio\build\LPC1769\src\src\module\tool_change.cpp.o
Compiling .pio\build\LPC1769\src\src\sd\Sd2Card.cpp.o
Compiling .pio\build\LPC1769\src\src\sd\SdBaseFile.cpp.o
Compiling .pio\build\LPC1769\src\src\sd\SdFatUtil.cpp.o
Compiling .pio\build\LPC1769\src\src\sd\SdFile.cpp.o
Compiling .pio\build\LPC1769\src\src\sd\SdVolume.cpp.o
Compiling .pio\build\LPC1769\src\src\sd\cardreader.cpp.o
Compiling .pio\build\LPC1769\lib6dc\Servo\Servo.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\CHOPCONF.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\COOLCONF.cpp.o
Archiving .pio\build\LPC1769\lib6dc\libServo.a
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\DRVCONF.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\DRVCTRL.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\DRVSTATUS.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\DRV_CONF.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\DRV_STATUS.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\ENCMODE.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\GCONF.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\IHOLD_IRUN.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\PWMCONF.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\RAMP_STAT.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\SERIAL_SWITCH.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\SGCSCONF.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\SHORT_CONF.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\SMARTEN.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\SW_MODE.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\SW_SPI.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\TMC2130Stepper.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\TMC2160Stepper.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\TMC2208Stepper.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\TMC2209Stepper.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\TMC2660Stepper.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\TMC5130Stepper.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\TMC5160Stepper.cpp.o
Compiling .pio\build\LPC1769\liba7f\TMCStepper\source\TMCStepper.cpp.o
Compiling .pio\build\LPC1769\libdfb\LiquidCrystal\LiquidCrystal.cpp.o
Compiling .pio\build\LPC1769\CMSIS\driver\debug_frmwrk.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_adc.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_can.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_clkpwr.c.o
Archiving .pio\build\LPC1769\liba7f\libTMCStepper.a
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_dac.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_emac.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_exti.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_gpdma.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_gpio.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_i2c.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_i2s.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_iap.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_libcfg_default.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_mcpwm.c.o
Archiving .pio\build\LPC1769\libdfb\libLiquidCrystal.a
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_nvic.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_pinsel.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_pwm.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_qei.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_rit.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_rtc.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_spi.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_ssp.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_systick.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_timer.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_uart.c.o
Compiling .pio\build\LPC1769\CMSIS\driver\lpc17xx_wdt.c.o
Compiling .pio\build\LPC1769\CMSIS\lib\chanfs\ff.c.o
Compiling .pio\build\LPC1769\CMSIS\lib\chanfs\ffunicode.c.o
Compiling .pio\build\LPC1769\CMSIS\lib\chanfs\mmc_ssp.c.o
Compiling .pio\build\LPC1769\CMSIS\lib\chanfs\rtc176x.c.o
Compiling .pio\build\LPC1769\CMSIS\lib\usb\cdcuser.cpp.o
Compiling .pio\build\LPC1769\CMSIS\lib\usb\mscuser.cpp.o
Compiling .pio\build\LPC1769\CMSIS\lib\usb\usbcore.cpp.o
Compiling .pio\build\LPC1769\CMSIS\lib\usb\usbdesc.cpp.o
Compiling .pio\build\LPC1769\CMSIS\lib\usb\usbhw.cpp.o
Compiling .pio\build\LPC1769\CMSIS\lib\usb\usbuser.cpp.o
Compiling .pio\build\LPC1769\CMSIS\system\startup_LPC17xx.S.o
Compiling .pio\build\LPC1769\CMSIS\system\system_LPC17xx.c.o
Compiling .pio\build\LPC1769\lpc176x\HardwarePWM.cpp.o
Compiling .pio\build\LPC1769\lpc176x\SoftwarePWM.cpp.o
Compiling .pio\build\LPC1769\lpc176x\pwm.cpp.o
Archiving .pio\build\LPC1769\libCMSIS.a
Compiling .pio\build\LPC1769\FrameworkArduino\CDCSerial.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\HardwareSerial0.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\HardwareSerial1.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\HardwareSerial2.cpp.o
Archiving .pio\build\LPC1769\liblpc176x.a
Compiling .pio\build\LPC1769\FrameworkArduino\HardwareSerial3.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\Print.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\SoftwareSPI.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\SoftwareSerial.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\WInterrupts.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\Wire.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\arduino.cpp.o
Compiling .pio\build\LPC1769\FrameworkArduino\main.cpp.o
Archiving .pio\build\LPC1769\libFrameworkArduino.a
Linking .pio\build\LPC1769\firmware.elf
c:/users/kristian/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/LPC1769/src/src/sd/SdBaseFile.cpp.o: in function `Sd2Card::writeBlock(unsigned long, unsigned char const*)':
C:\Software Marlin\Marlin-2.0.x/Marlin\src\sd/Sd2Card_sdio.h:36: undefined reference to `SDIO_WriteBlock(unsigned long, unsigned char const*)'
c:/users/kristian/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/LPC1769/src/src/sd/SdBaseFile.cpp.o: in function `Sd2Card::readBlock(unsigned long, unsigned char*)':
C:\Software Marlin\Marlin-2.0.x/Marlin\src\sd/Sd2Card_sdio.h:35: undefined reference to `SDIO_ReadBlock(unsigned long, unsigned char*)'
c:/users/kristian/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/LPC1769/src/src/sd/SdBaseFile.cpp.o: in function `Sd2Card::writeBlock(unsigned long, unsigned char const*)':
C:\Software Marlin\Marlin-2.0.x/Marlin\src\sd/Sd2Card_sdio.h:36: undefined reference to `SDIO_WriteBlock(unsigned long, unsigned char const*)'
c:/users/kristian/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/LPC1769/src/src/sd/SdVolume.cpp.o: in function `Sd2Card::writeBlock(unsigned
long, unsigned char const*)':
C:\Software Marlin\Marlin-2.0.x/Marlin\src\sd/Sd2Card_sdio.h:36: undefined reference to `SDIO_WriteBlock(unsigned long, unsigned char const*)'
c:/users/kristian/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: C:\Software Marlin\Marlin-2.0.x/Marlin\src\sd/Sd2Card_sdio.h:36: undefined reference to
`SDIO_WriteBlock(unsigned long, unsigned char const*)'
c:/users/kristian/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/LPC1769/src/src/sd/SdVolume.cpp.o: in function `Sd2Card::readBlock(unsigned long, unsigned char*)':
C:\Software Marlin\Marlin-2.0.x/Marlin\src\sd/Sd2Card_sdio.h:35: undefined reference to `SDIO_ReadBlock(unsigned long, unsigned char*)'
c:/users/kristian/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/LPC1769/src/src/sd/cardreader.cpp.o: in function `Sd2Card::init(unsigned char, unsigned char)':
C:\Software Marlin\Marlin-2.0.x/Marlin\src\sd/Sd2Card_sdio.h:34: undefined reference to `SDIO_Init()'
**collect2.exe: error: ld returned 1 exit status
*** [.pio\build\LPC1769\firmware.elf] Error 1**
================================================================================================= [FAILED] Took 217.39 seconds =================================================================================================

Environment               Status    Duration
------------------------  --------  ------------
mega2560                  IGNORED
mega2560ext               IGNORED
mega1280                  IGNORED
MightyBoard1280           IGNORED
MightyBoard2560           IGNORED
rambo                     IGNORED
FYSETC_F6_13              IGNORED
FYSETC_F6_14              IGNORED
sanguino644p              IGNORED
sanguino1284p             IGNORED
melzi                     IGNORED
melzi_optiboot            IGNORED
melzi_optimized           IGNORED
at90usb1286_cdc           IGNORED
at90usb1286_dfu           IGNORED
DUE                       IGNORED
DUE_USB                   IGNORED
DUE_debug                 IGNORED
DUE_archim                IGNORED
DUE_archim_debug          IGNORED
SAMD51_grandcentral_m4    IGNORED
LPC1768                   IGNORED
**LPC1769                   FAILED    00:03:37.388**
STM32F103RC               IGNORED
STM32F103RC_meeb          IGNORED
STM32F103RC_fysetc        IGNORED
STM32F103RC_btt           IGNORED
STM32F103RC_btt_USB       IGNORED
STM32F103RC_btt_512K      IGNORED
STM32F103RC_btt_512K_USB  IGNORED
STM32F103RE               IGNORED
STM32F103RE_btt           IGNORED
STM32F103RE_btt_USB       IGNORED
STM32F4                   IGNORED
STM32F7                   IGNORED
ARMED                     IGNORED
STM32F103VE_GTM32         IGNORED
STM32F103VE_longer        IGNORED
mks_robin_mini            IGNORED
mks_robin_nano35          IGNORED
mks_robin                 IGNORED
mks_robin_stm32           IGNORED
mks_robin_pro             IGNORED
trigorilla_pro            IGNORED
mks_robin_e3              IGNORED
mks_robin_lite            IGNORED
mks_robin_lite3           IGNORED
jgaurora_a5s_a1           IGNORED
STM32F103CB_malyan        IGNORED
STM32F070RB_malyan        IGNORED
malyan_M300               IGNORED
chitu_f103                IGNORED
chitu_v5_gpio_init        IGNORED
STM32F103RET6_creality    IGNORED
STM32F401VE_STEVAL        IGNORED
FLYF407ZG                 IGNORED
FYSETC_S6                 IGNORED
STM32F407VE_black         IGNORED
BIGTREE_SKR_PRO           IGNORED
BIGTREE_GTR_V1_0          IGNORED
BIGTREE_BTT002            IGNORED
LERDGEX                   IGNORED
LERDGES                   IGNORED
LERDGEK                   IGNORED
rumba32                   IGNORED
esp32                     IGNORED
teensy31                  IGNORED
teensy35                  IGNORED
linux_native              IGNORED
include_tree              IGNORED
============================================================================================= 1 failed, 0 succeeded in 00:03:37.388 =============================================================================================

**Comment by ellensp** [comment]
Please attach your configuration files. As was requested in the template.

**Comment by ellensp** [comment]
My guess is you have enabled SDIO_SUPPORT, but SDIO_SUPPORT is not supported on LPC1768/9 its only for STM32 based controllers (fairly sure hardware doesn't support this.marlin defiantly doesn't)

**Comment by Kris83is** [comment]
> Please attach your configuration files. As was requested in the template.
[Configuration.h.zip](https://github.com/MarlinFirmware/Marlin/files/5171047/Configuration.h.zip)

Thanks for the help.

**Comment by YHRen** [comment]
I got a similar problem. I compiled to the wrong board, and didn't "clean all". After "clean all", the re-build works. 
This might help others who have similar problem.
