### ISSUE TITLE
[BUG] Cannot compile for LPC1769 SKR V1.4 Turbo

### ISSUE THREAD

**Issue by iamaydo** [MarlinFirmware/Marlin#19259]
### Bug Description

Tried to compile firmware for SKR V1.4 Turbo after I began seeing 'SD Init Fail' errors, which began this morning when I attempted to flash 2.0.6.1 and received a HAL @ 0.4.2 problem that it was defined but not used. Now, when I try to compile a new Marlin version it fails with red text referencing HAL. 

### My Configurations

[Marlin-2.0-2.x.zip](https://github.com/MarlinFirmware/Marlin/files/5173182/Marlin-2.0-2.x.zip)

### Steps to Reproduce

1. Set default environment as LPC1769
2. Select board BTT_SKR_V1_4_TURBO
3. Select Marlin Auto Build

**Expected behavior:**
Compile successfully

**Actual behavior:**
Compile unsuccessfully

#### Additional Information

platformio run -e LPC1769 ; echo "done" >/var/folders/xn/0b8shngd2qn0dskydwt1_5lc0000gn/T/ipc
andrew@aydomacbook Marlin-2.0-2.x % platformio run -e LPC1769 ; echo "done" >/var/folders/xn/0b8shngd2qn0dskydwt1_5lc0000gn/T/ipc
Processing LPC1769 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.3.zip; board: nxp_lpc1769; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/nxplpc-arduino-lpc176x/nxp_lpc1769.html
PLATFORM: NXP Arduino LPC176x (0.1.3) > NXP LPC1769
HARDWARE: LPC1769 120MHz, 31.97KB RAM, 464KB Flash
DEBUG: Current (cmsis-dap) On-board (cmsis-dap) External (blackmagic, jlink)
PACKAGES: 
 - framework-arduino-lpc176x 0.2.4 
 - toolchain-gccarmnoneeabi 1.90301.200702 (9.3.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ off, Compatibility ~ strict
Library Manager: Installing U8glib-HAL @ 0.4.1
Library Manager: Warning! More than one package has been found by U8glib-HAL @ 0.4.1 requirements:
 - marlinfirmware/U8glib-HAL @ 0.4.2
 - thinkyhead/U8glib-HAL @ 0.4.2
Library Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Library Manager: U8glib-HAL @ 0.4.1 has been installed!
Found 2 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Servo> 1.0.0
|-- <U8glib-HAL> 0.4.1
Building in release mode

Unable to find destination disk (Autodetect Error)
Please select it in platformio.ini using the upload_port keyword (https://docs.platformio.org/en/latest/projectconf/section_env_upload.html) or copy the firmware (.pio/build/LPC1769/firmware.bin) manually to the appropriate disk

Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/DebugMonitor.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/HAL.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/HAL_SPI.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/MarlinSerial.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/eeprom_flash.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/eeprom_sdcard.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/eeprom_wired.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/fast_pwm.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/include/digipot_mcp4451_I2C_routines.c.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/include/i2c_util.c.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/main.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/tft/tft_spi.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/tft/xpt2046.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/timers.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/u8g/LCD_I2C_routines.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/u8g/LCD_pin_routines.c.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/u8g/u8g_com_HAL_LPC1768_hw_spi.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/u8g/u8g_com_HAL_LPC1768_ssd_hw_i2c.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/u8g/u8g_com_HAL_LPC1768_st7920_hw_spi.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/u8g/u8g_com_HAL_LPC1768_st7920_sw_spi.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/u8g/u8g_com_HAL_LPC1768_sw_spi.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/usb_serial.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/LPC1768/watchdog.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/HAL_spi_L6470.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/backtrace/backtrace.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/backtrace/unwarm.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/backtrace/unwarm_arm.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/backtrace/unwarm_thumb.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/backtrace/unwarmbytab.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/backtrace/unwarmmem.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/backtrace/unwinder.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/backtrace/unwmemaccess.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/eeprom_api.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/eeprom_if_i2c.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/eeprom_if_spi.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/esp_wifi.cpp.o
Compiling .pio/build/LPC1769/src/src/HAL/shared/servo.cpp.o
Compiling .pio/build/LPC1769/src/src/MarlinCore.cpp.o
Compiling .pio/build/LPC1769/src/src/core/serial.cpp.o
Compiling .pio/build/LPC1769/src/src/core/utility.cpp.o
Compiling .pio/build/LPC1769/src/src/feature/babystep.cpp.o
Compiling .pio/build/LPC1769/src/src/feature/bedlevel/bedlevel.cpp.o
Compiling .pio/build/LPC1769/src/src/feature/caselight.cpp.o
Compiling .pio/build/LPC1769/src/src/feature/leds/neopixel.cpp.o
Compiling .pio/build/LPC1769/src/src/gcode/calibrate/G28.cpp.o
Compiling .pio/build/LPC1769/src/src/gcode/config/M200-M205.cpp.o
Compiling .pio/build/LPC1769/src/src/gcode/config/M220.cpp.o
Compiling .pio/build/LPC1769/src/src/gcode/config/M221.cpp.o
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/HAL/shared/backtrace/unwmemaccess.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/HAL/shared/backtrace/unwmemaccess.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/HAL/shared/eeprom_if_i2c.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/HAL/shared/eeprom_if_i2c.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/HAL/shared/eeprom_if_spi.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/HAL/shared/eeprom_if_spi.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/HAL/shared/esp_wifi.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/HAL/shared/esp_wifi.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/HAL/shared/servo.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/HAL/shared/servo.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/feature/babystep.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/feature/babystep.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/feature/bedlevel/bedlevel.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/feature/bedlevel/bedlevel.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/core/utility.cpp.o: No such file or directory
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/feature/caselight.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/core/utility.cpp.o] Error 1
*** [.pio/build/LPC1769/src/src/feature/caselight.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/core/serial.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/core/serial.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/feature/leds/neopixel.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/feature/leds/neopixel.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/gcode/calibrate/G28.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/gcode/calibrate/G28.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/MarlinCore.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/MarlinCore.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/gcode/config/M220.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/gcode/config/M220.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/gcode/config/M200-M205.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/gcode/config/M200-M205.cpp.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/LPC1769/src/src/gcode/config/M221.cpp.o: No such file or directory
*** [.pio/build/LPC1769/src/src/gcode/config/M221.cpp.o] Error 1
FileNotFoundError: [Errno 2] No such file or directory: '/Users/andrew/Documents/Marlin-2.0-2.x/.pio/build/LPC1769/.sconsign37.dblite':
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/Main.py", line 1391:
    _exec_main(parser, values)
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/Main.py", line 1355:
    _main(parser)
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/Main.py", line 1126:
    nodes = _build_targets(fs, options, targets, target_top)
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/Main.py", line 1329:
    jobs.run(postfunc = jobs_postfunc)
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Job.py", line 113:
    postfunc()
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/Main.py", line 1326:
    SCons.SConsign.write()
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/SConsign.py", line 114:
    syncmethod()
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/dblite.py", line 144:
    self._os_unlink(self._file_name)
Exception ignored in: <function dblite.__del__ at 0x102757598>
Traceback (most recent call last):
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/dblite.py", line 126, in __del__
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/dblite.py", line 123, in close
  File "/Users/andrew/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/dblite.py", line 144, in sync
FileNotFoundError: [Errno 2] No such file or directory: '/Users/andrew/Documents/Marlin-2.0-2.x/.pio/build/LPC1769/.sconsign37.dblite'
========================================================================================= [FAILED] Took 7.16 seconds =========================================================================================

Environment    Status    Duration
-------------  --------  ------------
LPC1769        FAILED    00:00:07.164

**Comment by thisiskeithb** [comment]
Your config builds fine with the latest `bugfix-2.0.x`:

```prolog
Linking .pio/build/LPC1769/firmware.elf
Building .pio/build/LPC1769/firmware.bin
Checking size .pio/build/LPC1769/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [===       ]  28.8% (used 9412 bytes from 32736 bytes)
Flash: [===       ]  31.2% (used 148364 bytes from 475136 bytes)
====== [SUCCESS] Took 26.64 seconds ======

Environment    Status    Duration
-------------  --------  ------------
LPC1769        SUCCESS   00:00:26.644
====== 1 succeeded in 00:00:26.644 ======
```

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
