### ISSUE TITLE
[BUG] M104 with Smoothieboard goes into thermal runaway during bed leveling

### ISSUE THREAD

**Issue by GadgetNutt** [MarlinFirmware/Marlin#19278]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5180090/Configuration.zip)
### Bug Description

M104 with Smoothieboard goes into thermal runaway during bed leveling.

Essentially as it says.  I need to either do my bed leveling first and then heat the hot end, or heat the hot end and wait for the hot end temperature to stabilize before starting bed leveling.  Otherwise the firmware doesn't seem to be processing thermal updates in a timely way and goes into a thermal runaway protection error.  The hotend temperature doesn't actually reach the target temperature.

My Smoothieboard uses LPC1769.  I don't seem to have this issue with my RE-ARM board, using LPC1768. 

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. M104 to heat the hotend
2. G29 to Start probing.  At some point Thermal runaway occurs before probing ends.
3. Rinse and repeat until you realize you need to do M109 instead.

**Expected behavior:** Hotend to heat successfully during probing.

**Actual behavior:** Thermal runaway occurs during probing.

**Comment by ellensp** [comment]
Steps to reproduce are nonsensical
how do we replicate "Rinse and repeat until you realize you need to do M109 instead." 

Also the first smoothieboards from the kickstarter were LPC1768, just to muddy the waters...

**Comment by GadgetNutt** [comment]
> Steps to reproduce are nonsensical
> how do we replicate "Rinse and repeat until you realize you need to do M109 instead."

Yah, point 3 was kind of supposed to be silly.  There are no other steps to repeat.   I have just repeatedly tried to get it to work without success. 
 No offence intended.

> 
> Also the first smoothieboards from the kickstarter were LPC1768, just to muddy the waters...

This isn't one of the first Smoothieboards that I'm using.  I kind of specifically mentioned that.  The one I'm using is the current newest V1.1 that uses the A5984 steppers.

**Comment by GadgetNutt** [comment]
Ping

**Comment by boelle** [comment]
> Ping

please add some more meaningfull news.... "ping" is not very helpfull

**Comment by GadgetNutt** [comment]
Ok, my news is as far as I know it hasn't been addressed yet.  Therefore I'd like it to remain open.

**Comment by boelle** [comment]
you probe with everything hot.... i assume if you do it cold then its does not error out

what during normal printing?

(just some unfiltered thougths)

**Comment by GadgetNutt** [comment]
It works fine if I wait for it to heat up before probing or if I heat up after probing.  It goes into thermal runaway during bed leveling if I heat using M104 and do a bed leveling during the M104.  I do this using a RE-ARM board without any problems.  However it doesn't seem to work correctly on the Smoothieboard 5xC V1.1.  "Normal" printing I have not noticed any particular issues (yet) on small prints.  I am using this board on a printer I have been redesigning and haven't done any major prints on it yet.
