### ISSUE TITLE
Changes to Z-Offset During Printing Has No Effect

### ISSUE THREAD

**Issue by QuePID** [MarlinFirmware/Marlin#19276]
Using Marlin 2.0.6.1 with Bigtree Tech's SKR v1.4 Turbo, sensorless homing, bltouch, tmc 2209 in uart mode, disabled stealthchop in config, using bilinear bed leveling.  Issue persists in today's (September 6th 2020) 2.0.6 bugfix as well.  I thought at first it may be an issue with the TMC 2209's stepper motor current, but whether I use 580 mA or 1000 mA the issue remains.  Reduction of print seed has no effect on issue.

### Bug Description

When printing, changes to Z-Offset under Configuration has no effect on item currently printing.

### My Configurations

(http://www.robert-pace.com/Marlin2061_ender3_pro_config.zip)

### Steps to Reproduce
1. Set Z-Offset to -2.15
2. Start printing a file
3. Click on Configuration and change Z-Offset to any value you wish.

**Expected behavior:** Z-axis responds to changes in Z-Offset allowing one to tune the print's z-axis.

**Actual behavior:** Z-axis does not alter from normal printing elevation.

**Comment by ManuelMcLure** [comment]
That is as designed. The Z offset is applied only when homing. If you need to change the Z offset live while printing you need to use babystepping. Enabling `BABYSTEP_Z_PROBE_OFFSET` will allow you to save the babystepping offset to the Z probe offset.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
