### ISSUE TITLE
 I want my STOP button to lift the hot end up and turn off the cooling fan in repetier firmware

### ISSUE THREAD

**Issue by ahmedsohair** [MarlinFirmware/Marlin#19295]
So i recently configured my 3D printer using the config tool for Repetier firmware. However, there's a little change that i need to make when i press the STOP button.  What i want is that when i press the STOP button, the hot end should be lifted and the the cooling fan should be turned off. I am unable to figure this using the config tool. I have a slight idea that this might be possible by changing the functions already being used but don't know where to start from and which files or which lines of code to edit. Any help would be appreciated

**Comment by sjasonsmith** [comment]
This issue queue is for Marlin, not Repetier.
