### ISSUE TITLE
FAST_PWM_FAN affects serial communication on SKR 1.4 turbo

### ISSUE THREAD

**Issue by Quas7** [MarlinFirmware/Marlin#19293]
### Bug Description

Enabling FAST_PWM_FAN results in unstable serial communication for SKR 1.4 turbo (LPC1769) and 250000 baud.
Tested back and forth with different cables and could reproduce instantly. Bug could also be related to wire-routing or board-routing. I did not test other baud rates.

### My Configurations
Configuration_adv.h
// Increase the FAN PWM frequency. Removes the PWM noise but increases heating in the FET/Arduino
#define FAST_PWM_FAN

### Steps to Reproduce

1. setup SKR1.4 turbo
2. complie with FAST_PWM_FAN
3. flash and test, e.g. motor movment (motor movement starts case-fan in my case)

**Expected behavior:**
no serial communcation error

**Actual behavior:** 
serial communication error randomly occures.
Octoprint logs this:

2020-09-07 16:20:01,903 - Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:2916
2020-09-07 16:20:01,905 - Please see https://faq.octoprint.org/serialerror for possible reasons of this.
2020-09-07 16:20:01,911 - Changing monitoring state from "Operational" to "Offline (Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:2916)"
2020-09-07 16:20:01,948 - Connection closed, closing down monitor

#### Additional Information

I could imagine, that the LPC1769 and maybe the routing on the SKR 1.4 results in EMC issue with FAST_PWM_FAN and the 250kbaud serial communication interface. FAST_PWM_FAN should maybe get a remark, that serial communication could be affected (I searched ~2h to find the change that made it unstable)

**Comment by sjasonsmith** [comment]
Closing. No content.

**Comment by Quas7** [comment]
@sjasonsmith you are a bit too fast ;)

**Comment by AnHardt** [comment]
Switching any power causes ~~ESD~~ EMI. 
Adding a comment for a fan doesn't make much sense. We had to add the same warning for heaters and steppers. But do we really have to? It should be general knowledge.

**Comment by Quas7** [comment]
@AnHardt 
I think, you mean EMI (electromagnetic interference) and not ESD (electrostatic discharge). 
But yes, any fast switching PWM will generate electormagnetic noise and a higher PWM frequency will add more noise. 
But, I would not really call this general knowledge (=highschool level?). ;)

I think, the case here is a bit special, because the LPC1769 with a 120Mhz clock seems to generate a electromagnetic radiation that affects the serial communication quite drastically. The same setting did not result in an issue for due+radds (84Mhz) or my old atmega boards (16Mhz) but with the SKR 1.4 turbo it fails on serial communication almost instantly.

Assuming the implementation is still following the explanation in line 412 pp. in Config_adv we get: 
F_PWM = F_CPU/(2 x255 x1) = 235.3 kHz

And this is more than 3x the "normal" range listed and it is well above 120-150kHz RFID frequencies (10cm range).
I will try to set it to 80kHz with #define FAST_PWM_FAN_FREQUENCY next and maybe test my nanoVNA for the first time.

I would aruge, that nobody needs a FAST_PWM above audible levels. 
Maybe it would make sense to default it to max 40kHz? That would be a dog safe level. ;)

edit:
around 25 kHz seems to be the normal fan PWM operating frequency to avoid audible noise.
https://en.wikipedia.org/wiki/Computer_fan_control

**Comment by Quas7** [comment]
alright, My problem is solved with FAST_PWM_FAN and #define FAST_PWM_FAN_FREQUENCY 30000.

my proposal for the 5 yr old remark on FAST_PWM_FAN:
// Increase the FAN PWM frequency. Removes the PWM noise but increases heating in the FET/Arduino.
// On high speed CPUs restrict to PWM frequency to reasonble limits (e.g. 40000 Hz) via 
// #define FAST_PWM_FAN_FREQUENCY 40000 in Configuration_adv.h to avoid electromagnetic interference and possibly serial communication and other issues

**Comment by AnHardt** [comment]
Sorry. Yes EMI. My fingers just made something existing from your EMC above.

Are we talking about a timer clock frequency x (after prescaler), or a PWM-pulse-rate (x/resolution)?

**Comment by Quas7** [comment]
I think, we are talking about the PWM-pulse-rate, if I look at the equation in the adv_config as there is division by 2 that does not really fit normal timer scaling as I know it. (I edited the equation to be readable above)

**Comment by AnHardt** [comment]
https://github.com/MarlinFirmware/Marlin/blob/9ade72aee94981b26be0ca125ab487166d0bd7e3/Marlin/src/inc/Conditionals_post.h#L2233-L2238

Is the source of the evil.
This really should not have F_CPU in, resulting in a factor eleven difference depending on if the processor runs on 16MHz or 168MHz. A fixed number would give much less surprising results.

And splitting the the definition for FAST_PWM_FAN from its FAST_PWM_FAN_FREQUENCY into a different file with unsensible default makes it worse. The comments will rarely be read.

**Comment by Quas7** [comment]
Agreed. 
An upper limit should be applied to the frequency or at least a sanity check for >30 kHz.

On top, it might even be possible to brick a newer generation board while programming over serial connection via bootloader, if this high EMI is present.
