### ISSUE TITLE
[FR] [1.1.9] Mesh leveling start point

### ISSUE THREAD

**Issue by FlailAway** [MarlinFirmware/Marlin#19309]
### Description
I am stuck using 1.1.9 for two of our printers. When using Mesh setup with an LCD, could we have the start point higher than Z=0 for each position?

IF the bed is slightly higher than Z=0 can we move to the next point and instead of going to Z=0, go to say Z=1 so we can then go down to say, 0.85 (or whatever) touch the paper. As it is now it springs the carriage up and pushes divots in the Build-Tak.

### Feature Workflow
I have looked through the Marlin files and did not find anything like "start-above-Z" or something like that. A search online revealed no help either. OR, are we supposed to start with Z=0 already a specific distance ABOVE the bed true zero and the Mesh will suck it all up?

**Comment by AnHardt** [comment]
A Feature Request for `1.1.9` is pretty unlikely to be realized.
1.1.9 is released and will not get any further changes - except fixing live threatening bugs - maybe.
All developments target is `bugfix-2.0.x`.
