### ISSUE TITLE
[FR] Example configurations for Ender 3 Pro and SKR mini E3

### ISSUE THREAD

**Issue by piotrva** [MarlinFirmware/Marlin#19316]
### Description

It would be nice to have example configurations for Ender 3 Pro with SRK mini E3 boards (v1.0, v1.2, v2.0).

**Comment by thisiskeithb** [comment]
The only difference between the Ender-3 and Ender-3 Pro is the default printer name and status screen graphic (if you enable it).

**Comment by piotrva** [comment]
Thanks, I have just compared files. But would be nice to have it linked in folder for "Pro" for newbies.

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Configurations/pull/211.

**Comment by piotrva** [comment]
Thanks - ultra fast response ;)

**Comment by Deneteus** [comment]
Which one applies to the SKR E3-DIP V1.1?  :)

**Comment by sjasonsmith** [comment]
@Deneteus I don’t think there is an example for the DIP version. It is probably most similar to the Mini E3 1.2. You will have to update the motherboard name and stepper driver types in your Configuration.h file.

**Comment by Deneteus** [comment]
> @Deneteus I don’t think there is an example for the DIP version. It is probably most similar to the Mini E3 1.2. You will have to update the motherboard name and stepper driver types in your Configuration.h file.

I am aware. I am going to post this link here for reference just in case anyone asks.
https://www.makenprint.uk/3d-printing/3d-printing-guides/skr-e3-dip-marlin-2-setup-part-1/

**Comment by Deneteus** [comment]
I found my answer. 
![image](https://user-images.githubusercontent.com/6380390/93004857-b9943080-f510-11ea-9424-ca217f5c18f6.png)
