### ISSUE TITLE
[BUG] Tronxy XY-2 LVLG Blank screen chitu-v8-190729

### ISSUE THREAD

**Issue by Snow4DV** [MarlinFirmware/Marlin#19320]
# Bug Description

Hello! Trying to install Marlin with LVGL on Tronxy XY-2 (not pro) with Chitu V8 190729 board (in configuration V5 is set up as it was said in yt tutorial by Jeff). Everything works using the color or classic ui but not lvgl. Assets are on the sd card (dialog with preparing assets was shown on the first boot) but after that i am just getting a gray screen. If i try to click in some spot some other menues opened (Some screenshots: 
![7-d2a8hv3nc](https://user-images.githubusercontent.com/32912696/92622513-c5dc7b80-f2cd-11ea-9cdd-ed503edea708.jpg)
![ndzNfgsqVvA](https://user-images.githubusercontent.com/32912696/92622521-c9700280-f2cd-11ea-984b-e958650d456c.jpg)
![hMj1k4d-RSM](https://user-images.githubusercontent.com/32912696/92622525-cb39c600-f2cd-11ea-9e52-c550e3aee120.jpg)

)

### My Configurations

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5196330/Configuration_adv.zip) 

Used custom one from Tronxy XY-2 pro/x5sa repo but modified it for XY2 

### Steps to Reproduce

Flash it on my hardware & boot it
#### Additional Information

There is another problem that can be connected with this one: 

If i enable LVGL and ADVANCED_PAUSE_FEATURE (for runout sensor) it doesnt let me compile it:

`In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:41:0,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:35:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:825:6: error: #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
     #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
      ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:41:0,
                 from Marlin\src\HAL\STM32F1\Servo.cpp:25:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:825:6: error: #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
     #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
      ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:41:0,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:825:6: error: #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
     #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
      ^~~~~
In file included from Marlin\src\HAL\STM32F1\dogm\../../../inc/MarlinConfig.h:41:0,
                 from Marlin\src\HAL\STM32F1\dogm\u8g_com_stm32duino_swspi.cpp:21:
Marlin\src\HAL\STM32F1\dogm\../../../inc/SanityCheck.h:825:6: error: #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
     #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
      ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:41:0,
                 from Marlin\src\HAL\STM32F1\eeprom_bl24cxx.cpp:28:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:825:6: error: #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
     #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
      ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:41:0,
                 from Marlin\src\HAL\STM32F1\eeprom_flash.cpp:32:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:825:6: error: #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
     #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
      ^~~~~
*** [.pio\build\chitu_v5_gpio_init\src\src\HAL\STM32F1\HAL_SPI.cpp.o] Error 1
*** [.pio\build\chitu_v5_gpio_init\src\src\HAL\STM32F1\Servo.cpp.o] Error 1
*** [.pio\build\chitu_v5_gpio_init\src\src\HAL\STM32F1\HAL.cpp.o] Error 1
*** [.pio\build\chitu_v5_gpio_init\src\src\HAL\STM32F1\dogm\u8g_com_stm32duino_swspi.cpp.o] Error 1
*** [.pio\build\chitu_v5_gpio_init\src\src\HAL\STM32F1\eeprom_bl24cxx.cpp.o] Error 1
*** [.pio\build\chitu_v5_gpio_init\src\src\HAL\STM32F1\eeprom_flash.cpp.o] Error 1`

However there are no problems with it on color ui.

Using the latest marlin firmware with my configuration

**Comment by Snow4DV** [comment]
That's the repo: https://github.com/rhapsodyv/Marlin

UPD: Sorry, my mistake - used the wrong configuration_adv - that's why it didn't compile with ADVANCED_PAUSE_FEATURE

But even after replacing it with this one, the problem with blank screen is still on its place.

Correct configuration file: [Configuration_adv (2).zip](https://github.com/MarlinFirmware/Marlin/files/5196469/Configuration_adv.2.zip)

**Comment by rhapsodyv** [comment]
Looks like your board have only 1mb, and not a 2mb like the x5sa.

Open the pins file and disable font in spi flash, and test again.
`Marlin/src/pins/stm32f1/pins_CHITU3D_V5.h`

Change `#define HAS_SPI_FLASH_FONT                   1` to `#define HAS_SPI_FLASH_FONT                  0`

**Comment by Snow4DV** [comment]
> Looks like your board have only 1mb, and not a 2mb like the x5sa.
> 
> Open the pins file and disable font in spi flash, and test again.
> `Marlin/src/pins/stm32f1/pins_CHITU3D_V5.h`
> 
> Change `#define HAS_SPI_FLASH_FONT 1` to `#define HAS_SPI_FLASH_FONT 0`

After doing this it boots but screen doesn't turn on at all (even the backlight).

But it boots color ui with disabled HAS_SPI_FLASH_FONT without any problems

**Comment by rhapsodyv** [comment]
> > Looks like your board have only 1mb, and not a 2mb like the x5sa.
> > Open the pins file and disable font in spi flash, and test again.
> > `Marlin/src/pins/stm32f1/pins_CHITU3D_V5.h`
> > Change `#define HAS_SPI_FLASH_FONT 1` to `#define HAS_SPI_FLASH_FONT 0`
> 
> After doing this it boots but screen doesn't turn on at all (even the backlight).
> 
> But it boots color ui with disabled HAS_SPI_FLASH_FONT without any problems

After you changed `HAS_SPI_FLASH_FONT` to 0, did you try to load the assets again?

**Comment by Snow4DV** [comment]
> > > Looks like your board have only 1mb, and not a 2mb like the x5sa.
> > > Open the pins file and disable font in spi flash, and test again.
> > > `Marlin/src/pins/stm32f1/pins_CHITU3D_V5.h`
> > > Change `#define HAS_SPI_FLASH_FONT 1` to `#define HAS_SPI_FLASH_FONT 0`
> > 
> > 
> > After doing this it boots but screen doesn't turn on at all (even the backlight).
> > But it boots color ui with disabled HAS_SPI_FLASH_FONT without any problems
> 
> After you changed `HAS_SPI_FLASH_FONT` to 0, did you try to load the assets again?

Are you talking about deleting "_assets" folder? If yes i've just tried to and nothing changed

**Comment by rhapsodyv** [comment]
Renaming it back to `assets`, while using the firmware with disabled font spi support...

**Comment by Snow4DV** [comment]
> Renaming it back to `assets`, while using the firmware with disabled font spi support...

Oh. Ok, i tried to unpack the assets (two mks* folders and a bin file for robin) and also reverted to a firmware with spi, "initialized" the assets (it said it with the white font on the black screen), renamed "_assets" to "assets" (just in case if these files after copying assets do not stay the same) - the same situation

**Comment by Snow4DV** [comment]
> Renaming it back to `assets`, while using the firmware with disabled font spi support...

Ok, i just missed the fact that i got to unpack the assets' bins right to the assets folder :| 

Looks like everything works with the spi enabled. Sry for wasting your time, thought it was a bug with untested v8 board

**Comment by rhapsodyv** [comment]
You don't need the files from MKS too. Marlin will generate the `assets` folder in the build directory too, together with the `update.cdb` :-)

**Comment by thisiskeithb** [comment]
These configs are not from Marlin's repo and we do not support forks here.
