### ISSUE TITLE
Enable Thermal Runaway Protection by default

### ISSUE THREAD

**Issue by harerama** [MarlinFirmware/Marlin#1932]
It saved my printer once (many thanks !):
I really think security features should be enabled by default and the default configuration seems ok to me.

**Comment by thinkyhead** [comment]
I think it was enabled by default at some point, and I forget why it was disabled. But it makes sense to enable it by default, as a safety feature.

**Comment by AnHardt** [comment]
@thinkyhead 
The history tells me. @alexborro added 'Thermal Runaway Protection' on Jun 30 2014 with commented out #defines. This is untouched until now.
Should be save to be enabled by default.

**Comment by thinkyhead** [comment]
#1991 enables it for extruders. Do you think it ought to be enabled for the bed as well?

**Comment by AnHardt** [comment]
Yes, i think so. A heater like the others.

**Comment by harerama** [comment]
I think all should be enabled yes.
It saved my printer because I had a cable connection ON THE BED partially cut, so the few remaining wires became really hot (with smoke going out !!!) - as the bed could not maintain its temperature, the protection activated.
As a rule, all safety protections should be enabled by default - letting power users the ability to disable them if they want. We are discussing potentially burning homes here, so the safer the better...

Thanks again for saving mine ;-)

**Comment by thinkyhead** [comment]
Done!
