### ISSUE TITLE
SD card and USB connection problem

### ISSUE THREAD

**Issue by webers89** [MarlinFirmware/Marlin#19341]
Hi,

Problem started previous week after PlatformIO and Marlin update. (I use Visual Code with PlatformIO addin)
When I compile and upload Marlin 2.0 in Re-arm board I have following problem:

When I connect Re-arm board to computer it doesn't open SD card anymore and it loses connection to serial port after couple of minutes. Even when there is connection  I can't communicate with re-arm using Pronterface. 

[Config_files.zip](https://github.com/MarlinFirmware/Marlin/files/5207160/Config_files.zip)

**Comment by sjasonsmith** [comment]
This issue ignored the issue template and did not provide all the requested information. I am going to close this issue, as it seems you should work with our community to help troubleshoot your issue prior to filing a bug report.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
