### ISSUE TITLE
[BUG] Power Loss Recovery freeze lcd display

### ISSUE THREAD

**Issue by ils15** [MarlinFirmware/Marlin#19353]
When i activate power loss recovey with MKS ROBIN NANO V1.2 and color UI, display freezes, sometimes when i start a new print, sometimes immediately or sometimes halted 
![IMG_20200912_074652](https://user-images.githubusercontent.com/24917659/92994131-ea06ab00-f4cd-11ea-9c5b-730b5797901a.jpg)

Same error with classic UI
![IMG_20200912_080355.jpg](https://user-images.githubusercontent.com/24917659/92994217-cc861100-f4ce-11ea-857e-7f7421bf057f.jpg)

you can see my marlin code here
https://github.com/ils15/BlueR

**Comment by boelle** [comment]
is your marlin a copy of [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) ?

**Comment by ils15** [comment]
Marlin 2.0.6.1

**Comment by boelle** [comment]
try with [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) instead, it's being updated daily

2.0.6.1 is just a frozen copy of [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x)

**Comment by andreibobirica** [comment]
I have tried with the last bugfix and the problem is here too

**Comment by ils15** [comment]
> try with [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) instead, it's being updated daily
> 
> 2.0.6.1 is just a frozen copy of [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x)

Same error
