### ISSUE TITLE
[BUG] E1 Heating failed with "pause at height" plugin on cura

### ISSUE THREAD

**Issue by elbowz** [MarlinFirmware/Marlin#19357]
### Bug Description

I got the error in subject (*E1 Heating failed*) when using the "pause at height" Post Processing plugin on Cura. 
I'm on Ender 3 + Marlin v2.0.5.4.
This in particular happen after try to restart/unpause the printing.
FYI: The hot end go to 0 °C during the pause.

### My Configurations

ZIP file containing your `Configuration.h` and `Configuration_adv.h` files: [configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5212716/configuration.zip)

### Steps to Reproduce

1. Enable "print at height" script on Cura
2. Reach the pause point
3. Restart printing

**Actual behavior:** E1 Heating failed

**Thanks in advance**!

**Comment by ellensp** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
