### ISSUE TITLE
[BUG] cr10s screen overlapped

### ISSUE THREAD

**Issue by Liger0** [MarlinFirmware/Marlin#19350]
### Bug Description

The text overlap the values on 2.0.6.1

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5211735/Marlin.zip)

### Steps to Reproduce

1. Go in a configuration

**Expected behavior:** Text are separate from the values

**Actual behavior:** Text hides the values

#### Additional Information

![text marlin 2 0 6 1 cr10s](https://user-images.githubusercontent.com/20385116/92978455-14d20e80-f490-11ea-8a12-9862453ad069.jpg)

**Comment by boelle** [comment]
Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

**Comment by Liger0** [comment]
Do you mean to test on latest bugfix or to test the stable releases?

**Comment by ellensp** [comment]
Checked on current bugfix.

**Comment by ellensp** [comment]
Something to do with how the wildcard in MSG_EN_STEPS = _UxGT("* Steps/mm"); is interpreted.
instead of resulting in "E1 Steps/mm"  Its resulting in "E1 Steps/mm Steps/mm" 
You cant see it on the steps/mm screen but you see it when you edit the value..

**Comment by ellensp** [comment]
removing line 60 from https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/lcdprint.cpp#L60 
Fixes it. Trying to work out what this line was meant to do and if removing it causes any further issues.

**Comment by ellensp** [comment]
Ok line 60 prints while checking the text isn't larger than the lcd. vs default which doesn't..
So adding a break is a better option.

**Comment by ellensp** [comment]
Check the PR above (https://github.com/MarlinFirmware/Marlin/pull/19351) works for you also.

**Comment by ellensp** [comment]
This has been fixed in current bugfix
