### ISSUE TITLE
[BUG] Delta printer, trouble with homing 

### ISSUE THREAD

**Issue by joneggg** [MarlinFirmware/Marlin#19376]
Hello, when I try to start homing, one of endstops (Z tower) don’t stop motor. Motor continues to lift the carriage up. 

I recorded on video:

https://youtu.be/xknFYJ4vnDU

M119 says what is alright 
![D11B9668-3136-455B-A998-6396572F3F5E](https://user-images.githubusercontent.com/71187057/93018997-030a7b80-f5f6-11ea-90ce-aa5ff6141eb2.jpeg)

can this be fixed somehow?

**Comment by ellensp** [comment]
This is what happens when you have wrong endstop on the wrong tower.  It stop the wrong tower moving.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
