### ISSUE TITLE
[BUG] Anycubic i3 Mega Homing after Print Stop(Print abort)

### ISSUE THREAD

**Issue by Nissal1983** [MarlinFirmware/Marlin#19380]
After aborting a print via SD via the stock display, the printer ends properly but does an X Y Z homing immediately. If there are larger things on the bed, he drives them into them. It should better raise Z and X to the left and Y a little forward

**Comment by ellensp** [comment]
Please attach your configuration files. And follow the issue template

**Comment by Nissal1983** [comment]
[config.zip](https://github.com/MarlinFirmware/Marlin/files/5218730/config.zip)

**Comment by boelle** [comment]
Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.
