### ISSUE TITLE
[BUG] Fan can't be set to run under PID Autotune

### ISSUE THREAD

**Issue by Liger0** [MarlinFirmware/Marlin#19383]
### Bug Description

Fan can't be set to run under PID Autotune

### My Configurations

Today's bugfix
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5215036/Marlin.zip)

### Steps to Reproduce

1. Start a PID Autotune
2. Set a fan speed

**Expected behavior:** Let the fan move when PID autotuning, temporary disable the fan menu while PID autotune is working, or don't show the fan like it was working (or not working if you instead turned it off) and prompt a failure message.

**Actual behavior:** The fan doesn't move until the PID autotune has finished. Even so, the LCD will show the speep you did set it to

#### Additional Information

This has always been an issue

**Comment by ellensp** [comment]
Marlin is basically a sequential gcode processor. With blocking and non blocking commands. PID Autotune is a blocking command. no further commands are done till it is finished.
