### ISSUE TITLE
Bed Halt while preheat. But bed heating works good in pid. 

### ISSUE THREAD

**Issue by Talha909** [MarlinFirmware/Marlin#19400]
I have very strange issue. My bed heating halt while preheat after few degree. I have rest the system until i got the desire temp on my bed. But after printing start they bed heater works good. I also did the pid of the bed heater and its also works very good.  It only give the trouble when i preheat the bed or when i give the command to print and bed try to heat up and it halts 3 or times until it touches the desire bed temp. But every time when i did the pid auto there is no error whats the reason behind this. I also check the wires. Its looks good. Bed heater works good in pid process but it halts while in preheat . Config files attached. 
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5222865/Marlin.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
