### ISSUE TITLE
[BUG] Uncomplete filament load/unload text on cr10s screen (too big font and no scrolling)

### ISSUE THREAD

**Issue by Liger0** [MarlinFirmware/Marlin#19405]
### Bug Description

The screen on the cr10s lcs is not complete with 2 extruders, the extruder number is skipped.
Plus, the unload/unload options only change the first value, not the second.

### My Configurations

Bugfix as of 13 september

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5228232/Marlin.zip)

### Steps to Reproduce

1. Configurations-> Advanced->Filament

**Expected behavior:** Show the extruder number either making the font smaller or making it scroll, and change the values of the second filament if using the generic option

**Actual behavior:** The strings are the same for both the filaments, the text doesn't scroll and the font is too big to show everything, and the change of the generic values only changes the first one

#### Additional Information

![cr10s lcd filament](https://user-images.githubusercontent.com/20385116/93263842-997d9f00-f7a6-11ea-8862-d1f4fe7ee894.jpg)

**Comment by ellensp** [comment]
Confirmed on current bugfix.

**Comment by ellensp** [comment]
Changing font is not an option.
scrolling the menu is a horrible idea.


In lanugaue_en.h is the following,  These are displayed in  Advanced->Filament and  Change Filament

  PROGMEM Language_Str MSG_FILAMENTCHANGE_E                = _UxGT("Change Filament *");
  PROGMEM Language_Str MSG_FILAMENTLOAD_E                  = _UxGT("Load Filament *");
  PROGMEM Language_Str MSG_FILAMENTUNLOAD_E                = _UxGT("Unload Filament *");

There is no need to repeat the word filament in the filament menu, I recommend 

PROGMEM Language_Str MSG_FILAMENTCHANGE_E                = _UxGT("Change *");
PROGMEM Language_Str MSG_FILAMENTLOAD_E                  = _UxGT("Load *");
PROGMEM Language_Str MSG_FILAMENTUNLOAD_E                = _UxGT("Unload *");

**Comment by Liger0** [comment]
Is it normal that the generic option only changes the first value?

**Comment by Liger0** [comment]
+1

**Comment by Liger0** [comment]
+1

**Comment by rhapsodyv** [comment]
The fix was merged! Thanks
