### ISSUE TITLE
[BUG] BLTouch not working on SKR Pro 1.1

### ISSUE THREAD

**Issue by ksalaba** [MarlinFirmware/Marlin#19414]
### Bug Description

My BLtouch only blinks at me. This indicates a wiring problem. I have changed around my pins. Grabbed the latest version of Marlin. Gone to BigTreeTech read all their documentation and tried their configs. Nothing seems to work.  I have attached my Configs, pin config, and m43 i output.

History - I was running a BLTouch 2.1 (original) and in the middle of probing the bed, the probe stopped descending. Commands failed to make the probe descend, so I bought a BLTouch 3.1. Now all I get is blinking. The config attached is more or less the same as the original, but I have tweaked it so much trying to get it to work, its just close enough now.  
enabling BLTOUCH_FORCE_SW_MODE, and BLTOUCH_SET_5V_MODE did not actually do anything. M502, m500 also does not do anything. Z_MIN_PROBE_ENDSTOP_INVERTING false or true does nothing. (And shouldn't due to new marlin code in  Conditionals_LCD.h setting it to false)

My gear:
SKR PRO 1.1 running marlin bugfix - 2.0.x
BLTouch 3.1 (original)

My current BLTouch wiring:
Red - 5v Bltouch pin
Orange - PA2 (swapping to PA1 doesn't work either)
Brown - GND BLtouch pin

White - PG8 (swapping to PA2 didn't seem to work either)
Black -  GND Z- pin

### My Configurations
https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/blob/master/manual/SKR-PRO-V1.1-Pin.pdf
[m43 i output.txt](https://github.com/MarlinFirmware/Marlin/files/5230160/m43.i.output.txt)
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/5230258/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/5230261/Configuration_adv.h.txt)

### Steps to Reproduce
1. Download latest version of Marlin Bugfix - 2.0.x
2. Update the config to match my older config settings
3. Build
4. Deploy change to SD card.
5. Turn printer on
6. Wait for firmware to update
7. Watch the probe blink at me, no matter what command I send it

**Expected behavior:** 
I expect the BLTouch to pass its self test.

**Actual behavior:** 
BLtouch just blinks. Probe does not descend.

#### Additional Information

Send: M43 S
Recv: Servo probe test
Recv: . using index:  0, deploy angle: 10, stow angle:   90
Recv: . Probe Z_MIN_PIN: 106
Recv: . Z_MIN_ENDSTOP_INVERTING: false
Recv: . Check for BLTOUCH
Recv: . Deploy & stow 4 times
Recv: WARNING: INVERTING setting probably backwards.
Recv: ** Please trigger probe within 30 sec **
Recv: FAIL: No trigger detected
Recv: ok

**Additional thoughts:**
https://github.com/MarlinFirmware/Marlin/issues/16244 and https://github.com/MarlinFirmware/Marlin/issues/16169 seem to indicate that because the SKR PRO 1.1 board does not have an eeprom there is some issue with BLtouch and FLASH_EEPROM_EMULATION. Issue 16169 was resolved and merged into the code base in may, so I am unsure this is something new, or I just made a SNAFU with my config somewhere and cannot see it.

**Comment by sjasonsmith** [comment]
Does it not even deploy two times when you power-on? A BLTouch should do that with only 5V power, it needs nothing else for that to happen.
