### ISSUE TITLE
Dual z axis endstops and bltouch - z offset ignored

### ISSUE THREAD

**Issue by Maxinger15** [MarlinFirmware/Marlin#19433]
Hello,
I am using 2 z endstops on my printer for homing and a bltouch for bedleveling. After homing the nozzle is about 10mm above the printbed. I tryed to fix this with the z offset of the bltouch but this doesn't change anything. I disabled the software min z endstop but even then no change. How can I configure Marlin to use the z probe offset for the normal endstops?

**Comment by boelle** [comment]
read the template !!

```

<!--

Have you read Marlin's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md

Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use one of the support links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

Before filing an issue be sure to test the "bugfix" branches to see whether the issue has been resolved.

-->

### Bug Description

<!-- Description of the bug -->

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

<!-- Please describe the steps needed to reproduce the issue -->

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

```

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by Maxinger15** [comment]
[Marlin_2_0_6_1_conf.zip](https://github.com/MarlinFirmware/Marlin/files/5246630/Marlin_2_0_6_1_conf.zip)
 Sorry for the trouble. Here are my configs. I will try the bugfix branch too.

Edit: I forgot the modified pins.h file:
[pins_BTT_SKR_V1_4.zip](https://github.com/MarlinFirmware/Marlin/files/5247351/pins_BTT_SKR_V1_4.zip)

**Comment by Maxinger15** [comment]
The problem is still here with the current version in the bugfix-2.0.x branch.

**Comment by shitcreek** [comment]
**

> Are you looking for support? Please don't post here. Instead please use one of the support links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

**

Have you tried adjusting these settings?
`#define Z_AFTER_HOMING  2      // (mm) Height to move to after homing Z

`#define Z_AFTER_PROBING           10 // Z position after probing is done`

**Comment by Maxinger15** [comment]
For me z offset fixed it. But I think it would be nicer if it can be done via the z probe offset if a bltouch is attached.
