### ISSUE TITLE
[BUG] Axis not moving with TMC2130's

### ISSUE THREAD

**Issue by zanvettor** [MarlinFirmware/Marlin#19434]
### Bug Description

Hi! First time asking here, if Im doing something wrong, please let me know. 
My setup is SKR 1.3 with tmc2130 on X, Y and E + DRV8825 on Z1 and Z2. I had the same setup running until my board gave up and I got it replaced. Now I can't seem to get the 2130 to work. I checked the changes made in relation to the drivers a lot of times and still can't figure out what's wrong. 
I talked to BTT support and they manage to send me a firmware.bin file that made the axis move, so I know it's not a faulty board or stepper drivers. Unfortunatelly communicating with the support isn't easy due to language and very different time zones barriors. 

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5246122/marlin.zip)

### Steps to Reproduce

1. Compile Marlin with the given configuration files 
2. Send commands to move X, Y and E0

**Expected behavior:** The axis move accordingly 

**Actual behavior:** The motors don't turn nor stall

#### Additional Information

I changed the following in regard of tmc2130:
Configuration.h:  TMC2130 are set correctly on stepper drivers lines
Configuration_adv.h: 
#define TMC_USE_SW_SPI
#define SOFTWARE_DRIVER_ENABLE
#define MONITOR_DRIVER_STATUS
#define HYBRID_THRESHOLD
#define TMC_DEBUG

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
