### ISSUE TITLE
[BUG] Homing XY with deployed probe.

### ISSUE THREAD

**Issue by wzaburko** [MarlinFirmware/Marlin#19452]
Homing is possible with deployed probe.

### My Configurations
Marin 2.0.6.1

### Steps to Reproduce

1. Manually deploy probe 
2. Homing

**Expected behavior:** stow probe before homing
**Actual behavior:** not stow probe before homing

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by wzaburko** [comment]
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/5251600/Config.zip)

**Comment by sjasonsmith** [comment]
Is this a big problem? Couldn’t another expected behavior be “don’t manually deploy your probe before homing”?
