### ISSUE TITLE
[FR] (Add save pos. When paused)

### ISSUE THREAD

**Issue by nictronik99** [MarlinFirmware/Marlin#19472]
### Description
Add the ability to save the current position when a print is paused for turning off the printer. Thus giving the possibility to retrieve the print once  Turn the printer back on.currently there is the option that allows you to brutally save the position on the SD card at each layer change, or, if you have a UPS module available, Save your current location when a power failure is detected. I would like this same option added, just for the pause, even if you don't have the UPS module, So that I can turn off the printer and resume, once the printer is back on, where I had paused.

**Comment by thisiskeithb** [comment]
This exists as `POWER_LOSS_RECOVERY`, drawbacks aside like your print shrinking slightly or detaching from your build plate after it cools, you’d just kill the power to your printer for resuming later.

It’s not a feature I’d recommend using as part of your normal printing routine:

https://github.com/MarlinFirmware/Marlin/blob/47aa61c0ec4a4fe511bd7c629ce18d5ea8007da8/Marlin/Configuration_adv.h#L1159-L1181
