### ISSUE TITLE
[BUG] BLTouch not using or storing grid data

### ISSUE THREAD

**Issue by Thisg543** [MarlinFirmware/Marlin#19489]
### Bug Description

*My BLTouches grid data is either not stored or not used, on my start GCode, I use G29. Which creates the measurements and outputs the grid to me. If the print starts, it does not use that data, instead ignores it and continues to print without any ABL.
The result is a unlevel bed and filament sticking on one corner but not the other.

I am certain that this is a bug, as I have been on may forums, and many places where nobody could figure it out.
*

### My Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5269084/Configuration.zip)

Marlin 2.0.6.1

```
; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder
G28 ; Home all axes
M501
M420 S1
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish
```

### Steps to Reproduce

**Expected behavior:** The printer to use the ABL grid it created.

**Actual behavior:** It does not use the grid like explained above.

#### Additional Information

I have also tried to use a mix of M500, M501 and M420 S1. Did not do anything.

**Comment by thisiskeithb** [comment]
Add a `G29` after your `G28` and move `M501` to the first line of your start code if you intend to reset your settings to default before each print.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
