### ISSUE TITLE
[BUG] [2.0.6] "Stop Print" sucks back filament

### ISSUE THREAD

**Issue by FlailAway** [MarlinFirmware/Marlin#19491]
### Bug Description
After a couple of contiguous "Stop Print" and restart, it takes about 40+ seconds for filament to appear at the nozzle.

### My Configurations
**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce
Not sure I can do that exactly, yet, but this is what's happening so far. 
It seem to be worse after 2 or 3 successive Stops.
Run a print from the SD card.
Stop the print at layer 1 or 2.
Head pauses then lifts, X retracts, Y retracts spewing filament all the way. Extruder still feeding.
Pop out SD, make a change to gcode and put it back.
Purge the filament manually until visible at the hotend.
Start the print. It now goes for about 40+seconds and no filament as it has been sucked back quite a distance.
Latest time I had around 50-seconds per first layer and the filament did not appear until half way through the second layer.
Only happens after a Stop or 2.
If I turn off the printer then back on, it is not an issue after each Stop.

**Expected behavior:** [What you expect to happen]
Leave the dang filament alone. When the Stop is issued, just stop the filament before doing anything else.
Don't retract before or on the next start.

[stop.zip](https://github.com/MarlinFirmware/Marlin/files/5270372/stop.zip)

**Comment by GMagician** [comment]
It seems like you miss some "extruder" reset position in your gcoce. is this possible? This may be the reason why rebooting it works. Once rebooted E pos is 0

**Comment by FlailAway** [comment]
> It seems like you miss some "extruder" reset position in your gcoce. is this possible?

Thanks, but IdeaMaker Slicer has that set up in their boilerplate, so always included.

`
;TYPE:SKIRT
;WIDTH:0.400
G1 F2400 E0.0000

`

**Comment by ellensp** [comment]
exactly.. you purge and purge and E is at some length say 15. you then tell it to got back to E0 (with the G1 E0) and it retracts 15!  
You need to tell it it is already at E0 with a G92 E0

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
