### ISSUE TITLE
SKR 1.3 Printer crashes before printing

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#19498]
Hi,

I am pretty new to 3D Printing. I got my first Printer 4 month ago. and was only able to do 4 sucessfull Prints in that timeperiod.
I bought a modified Geeetech a10 of someone in my town. It wasnt working so i tried my best to fix it, I fried the board doing so. I decided to upgrade the broken Board with a SKR 1.3 and all new TMC 2209 in UART mode. I also upgraded to Direct Drive. I got no working Display, so i do adjust everything thru Octopi. everything worked fine but than my 5th print just stopped mid-print, the heater stayed on as did the fan.
I checked everything and tried to run the same print again. The Printer homed, moved into position and stopped when it was about to start printing the skirt. I repeated it multiple times and it always stopped at the same time. I get a communication error. I dont think its the power supply of the raspberry pi because the same thing happens with printing via pronterface.
I thought it might be the Serial connection, but since it happens the same time everytime i start to doubt it. Maybe the Board is faulty but how could i test it without buying a new one, also there where no issues with the prints before. 
I am out of ideas.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
