### ISSUE TITLE
x axis  works incorrectly & Setup steps / mm

### ISSUE THREAD

**Issue by pantileionut** [MarlinFirmware/Marlin#1950]
I purchased the following configuration -
Mega 2560 R3 development board
1.4 Ramps card drivers
LCD12864 SD-Card reader
A4988 stepper motor driver

-marlin 1.0.0 - the first day went well and everything nice ... recently driver on the x axis behaves strange: if you try to move the cursor on the x axis motor does not react (the driver enable pin 5V), but if Y or Z axis move any driver x (enable pin 0V) receives the order previously set number of steps executed by the Arduino board restarts after 30 seconds when connected with uSB cable (only with the firmware). I reversed the order of the pins pin axis x with y and y do the same driver set as x ... (indicating that the problem would be soft). (I downloaded the new firmware, I installed on another PC and everything just made).
-1.0.3 -marlin -axis functioning normally but no steps engines exective not correct, or that you 10mm 1mm or 0.1mm engines rotate just as moving as much as does a full rotation encoder .... and if you change stepp / mm do not notice any change .... (version 1.0.0 settings step / mm go ok to YZ axes and E) with firmware 1.0.3 with  not restart arduino.

with another firmware (0.92 Repetier) everything works perfectly when and how it works drivers and settings step / mm are also ok but I would prefer to be able to use marlin.

**Comment by thinkyhead** [comment]
Can you post your `Configuration.h` somewhere so we can look at it? It sounds like perhaps the "manual feed rate" might be set too high.

**Comment by pantileionut** [comment]
http://pastebin.com/ZqiwxdDf

**Comment by pantileionut** [comment]
I found the manual feed rate, we changed and everything works normal. I think it's from the selection X0.1, X1, X10 because the number of steps was made same trap as the encoder

**Comment by pantileionut** [comment]
update pe axele x y si z motoarele nu ajung la pozitia setata pe manual din meniu si nici daca comanzi din printun. indiferent de pasul de miscare 0.1mm 1mm sau 10mm driverele realizeaza acelasi numar de pasi se opresc din miscare dupa ce ai luat comanda neajungand la pozitia corecta ( cred ca  nu memoreaza in buffer). 
p.s. extruderul functioneaza ok...

**Comment by pantileionut** [comment]
sorry
xy and z axes update engines do not reach the position set manually from the menu and even if you order in printun. regardless of 1mm or 0.1mm up to 10mm drivers move the same number of steps made stop motion after taking command of not reaching the correct position (I think not stored in the buffer).
P.S. extruder works ok ...

**Comment by thinkyhead** [comment]
Thank you, my Romanian is very rusty. :smile:

Try lowering the `DEFAULT_MAX_FEEDRATE` for your Z axis. Instead of 100 make it something between 2 and 5. You can probably raise the `DEFAULT_MAX_FEEDRATE` for your X and Y axes however. I use 500 for each of those without any trouble.

Your `DEFAULT_AXIS_STEPS_PER_UNIT` values seem reasonable. For a GT2 belt with a 20 tooth pulley and 16 microsteps the value would be 80 (`3200 steps / (2mm * 20 teeth) = 80 steps-per-mm`). Your values of 66.67 indicate you are using a GT2 belt with 24 tooth pulley, or maybe a 2.4mm pitch belt with 20 tooth pulleys….

**Comment by pantileionut** [comment]
I modified feed rate and did not solve anything
after some tests I found these
-at coordinates moving with a unit (x0,1, X1, X10) engine run just one step regardless of the setting Stepp / mm or move up
- Motor does not lose steps
  I think somewhere in the firmware have to multiply between the desired displacement and number of steps to give the correct positioning, and that be the problem

**Comment by pantileionut** [comment]
using trapezoid screw M12 with 3mm step

**Comment by nophead** [comment]
With x16 microstepping you have 3200 steps per revolution, which is 3mm, steps per mm should be 3200.0/3 or 1066.67, not 66.67.

**Comment by pantileionut** [comment]
```
start
echo:Marlin 1.0.3 dev
echo: Last Updated: Apr 25 2015 22:03:43 | Author: (none, default config)
Compiled: Apr 25 2015
echo: Free Memory: 2994  PlannerBufferBytes: 1232
echo:Hardcoded Default Settings Loaded
echo:Steps per unit:
echo:  M92 X66.67 Y66.67 Z66.67 E66.67
echo:Maximum feedrates (mm/s):
echo:  M203 X25.00 Y25.00 Z25.00 E1000.00
echo:Maximum Acceleration (mm/s2):
echo:  M201 X3000 Y3000 Z100 E10000
echo:Accelerations: P=printing, R=retract and T=travel
echo:  M204 P3000.00 R3000.00 T3000.00
echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
echo:  M205 S0.00 T0.00 B20000 X5.00 Z5.00 E10.00
echo:Home offset (mm):
echo:  M206 X0.00 Y0.00 Z0.00
echo:PID settings:
echo:  M301 P22.20 I1.08 D114.00
echo:Filament settings: Disabled
echo:SD init fail
echo:echo:endstops hit:  X:0.01
echo:echo:endstops hit:  X:0.01
echo:echo:endstops hit:  X:0.00
echo:echo:endstops hit:  X:0.01
echo:echo:endstops hit:  X:0.03
echo:echo:endstops hit:  X:0.04
echo:echo:endstops hit:  X:0.06
echo:echo:endstops hit:  X:0.07
echo:echo:endstops hit:  X:0.06
echo:echo:endstops hit:  X:0.07
echo:echo:endstops hit:  X:0.09
echo:echo:endstops hit:  X:0.10
echo:echo:endstops hit:  X:0.12
echo:echo:endstops hit:  X:0.13
```

regardless of which control movement step 0.01 mm Says it all makes

**Comment by nophead** [comment]
Correct your steps per mm settings and move the axis clear of the end stop.

**Comment by boelle** [comment]
What machine do you have?

**Comment by boelle** [comment]
And have you checked backlash?

**Comment by pantileionut** [comment]
I corrected step / mm but all the same ... do not use micro-stepping driver set from driver
what you mean when you ask what type of machine....
arduino Mega 2560 R3 board
1.4 Ramps card drivers
LCD12864 SD-Card reader
A4988 stepper motor driver
I do not know how to check backlash

**Comment by boelle** [comment]
the list is just the electronics side of things.... what about the mechanical side?  

backlash is the amount of movement the stepper can do without anything moving... 

one example is if the belts are very loose... or if the belt has its teeth worn down

**Comment by pantileionut** [comment]
the mechanics:
moving on 12mm steel rods with linear bearings and to use movement as I said trapezoidal screw M12 3mm step ..

currently motors are removed so there is no issue of transmission movements
I try to make a little video to see how it behaves ...
problem manifests Y and Z axes X. The extruder everything goes ok steps and others

**Comment by nophead** [comment]
echo: M92 X66.67 Y66.67 Z66.67 E66.67

I repeat: FIX YOUR STEPS PER MM: 1066.67, not 66.67!!!!!!!!!!!1

**Comment by pantileionut** [comment]
Let's calculate together:
engine has 200 steps to a complete rotation
3mm trapezoid screw has a full rotation
steep / mm = 200 steps / 3 mm = 66.67 steps / mm
wrong somewhere?

**Comment by pantileionut** [comment]
I tried with firmware repetier ... everything works perfectly ..... set with 66.67

**Comment by nophead** [comment]
Only if your A4988 drivers are in full step mode.

**Comment by pantileionut** [comment]
drivers are in full mode ..... I do not know if maybe the settings to be something set

**Comment by nophead** [comment]
Apologises then.

Your accelerations look high for lead screws and the fact your X end stop is triggered is suspicious.

**Comment by pantileionut** [comment]
please watch the video to better understand the problem ....
https://www.wetransfer.com/downloads/ccdf87f05d88d9bda1afbe400b278fec20150425231338/999ac41921391317dce8cfcf002befc220150425231338/c4e035

**Comment by AnHardt** [comment]
error404 for the video link -> user not longer interested.

**Comment by drinkingcode** [comment]
@pantileionut  I also encountered the problem, when i changed feedrate of x/y , it didn't work, so how do you solve it ?

**Comment by thinkyhead** [comment]
Please test with latest `RCBugFix` to see if the issue exists in the current code. If it does, start by checking endstop settings. Then check movement rate settings. If the problem continues, we can look further.

**Comment by drinkingcode** [comment]
@thinkyhead thanks for your answering
