### ISSUE TITLE
Need help compiling for custom board with STM32F407ZGT6

### ISSUE THREAD

**Issue by MarkMan0** [MarlinFirmware/Marlin#19523]
I've tried to create a custom 3D printer controller, just for fun. It's loosely based on the SKR PRO V1.1, hence the same MCU. To program the board, I'm using an ST-Link V3. 

I could upload a simple blink program written in STM32CubeIDE, and it ran successfully. 

I've tried to compile Marlin with env:BIGTREE_SKR_PRO. Since I'm not using their boot-loader I tried compiling with `-DVECT_TAB_OFFSET=0x0000`, and compiling without that flag altogether. Unfortunately, the Marlin firmware didn't start up. I've inserted a simple blink routine in idle(), but nothing's happening.  It seems the firmware fails to start up.

Unfortunately I wired the USB wrong, so I can't debug via Serial, which would be a PITA, but since I can't even get a blink to work, I don't think that's the problem.

I know it's not really a Marlin issue, but I can't solve this problem myself, so I figured I'd ask here. If you know of a better place to ask, please suggest.

I'm grateful for any input.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
