### ISSUE TITLE
[BUG] Ender 3 V2 - First flash from stock, unable to change LCD language to English.

### ISSUE THREAD

**Issue by CRCinAU** [MarlinFirmware/Marlin#19527]
### Bug Description

There have been numerous reports of new Ender 3 V2 printers being upgraded to Bugfix and are unable to change the LCD language from Chinese to English after the flash.

Flashing a version built on 2020-09-15 allows the screen language to be changed - and any further updates to newer bugfix nightlies will correctly operate when changing the language of the LCD.

This does not work on versions built on 2020-09-19 onwards.

### My Configurations

Stock as per:
https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3%20V2

### Steps to Reproduce
See video: https://youtu.be/Q5PT3BjYobU

**Comment by Vertabreak** [comment]
Has the standard eeprom wipe been performed post flash as has always been required to clear out the old no longer valid eeprom settings and load the new. 
M502 + M500

**Comment by CRCinAU** [comment]
The DWIN LCD language is not stored within the Marlin EEPROM structure - however, in bugfix-2.0.x, it is stored at the EEPROM address 0x01.

See:
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/dwin/e3v2/dwin.cpp#L208

**Comment by CRCinAU** [comment]
I was originally thinking that this line here was the fault:
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/dwin/e3v2/dwin.cpp#L217

ie reading a `uint8_t` into a `bool` - however I have been told that anything non-zero when converted to a bool is considered true.

I haven't managed to find anything else that stands out - HOWEVER, once you managed to set the screen to English (ie Marlin writes a 0x00 or 0x01 to address 0x01), then this function works perfectly on newer builds.

As such, I thought it must have something to do with the contents of that EEPROM address BEFORE Marlin has written a valid value to it...

**Comment by CRCinAU** [comment]
@thinkyhead - I believe this may be in your refactors between 15/09 and 19/09 commits - but given that we're looking at hundreds of lines, I haven't been able to single out the commit as yet...

**Comment by Sono-Gomorrha** [comment]
I have the same issue and M502 + M500 has no effect. I also tried updating the LCD firmware (which should not play a role) and it did not change anything.

**Comment by thinkyhead** [comment]
I've applied a patch that will set the Ender 3 V2 language to English by default, including previous installs with the language set to Chinese, so give the latest `bugfix-2.0.x` code a try.

**Comment by CRCinAU** [comment]
Have had reports that this indeed throws the screen into English.

**Comment by thisiskeithb** [comment]
Closing as issue is resolved.
