### ISSUE TITLE
[BUG] Robin Nano V2: Linker error if USE_WIFI_FUNCTION in tft_lvgl_configuration.h is enabled

### ISSUE THREAD

**Issue by yousry** [MarlinFirmware/Marlin#19526]
### Bug Description
Linker error:
``
Linking .pio/build/mks_robin_nano35/firmware.elf
.pio/build/mks_robin_nano35/src/src/lcd/extui/lib/mks_ui/irq_overrid.cpp.o: In function `__irq_usart1':
/home/yousry/Dokumente/Source/printer/Marlin/Marlin/src/lcd/extui/lib/mks_ui/irq_overrid.cpp:47: multiple definition of `__irq_usart1'
.pio/build/mks_robin_nano35/src/src/HAL/STM32F1/MarlinSerial.cpp.o:/home/yousry/Dokumente/Source/printer/Marlin/Marlin/src/HAL/STM32F1/MarlinSerial.cpp:114: first defined here
collect2: error: ld returned 1 exit status
*** [.pio/build/mks_robin_nano35/firmware.elf] Error 1
``

### My Configurations

[robinNanoV2.zip](https://github.com/MarlinFirmware/Marlin/files/5288125/robinNanoV2.zip)

### Steps to Reproduce

1. set ```tft_lvgl_configuration.h = 1``` in tft_lvgl_configuration.h 
2. Type ```platformio run -e mks_robin_nano35```

**Expected behavior:** Compilation completes.

**Actual behavior:** Compilation aborted by a linker error.

#### Additional Information

I'm using bugfix-2 latest (4975e93350ee46aad323aa985f5c53e735aa26cf)

**Comment by rhapsodyv** [comment]
`USE_WIFI_FUNCTION ` is not a configuration option.
It’s hardcoded to 0 because the marlin support wasn’t finished yet.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
