### ISSUE TITLE
Three separate issues in one bug report

### ISSUE THREAD

**Issue by mikeandsuch** [MarlinFirmware/Marlin#19550]
### Bug Description
Ok idk if this is allowed but i have three issues using the three methods of uploading firmware. 

**Arduino**
During the compiling step of uploading i get an error stating that:
**The filename or extension is too long.
Error compiling for board Sanguino.**

**Vscode**
Successfully compiles then tries to upload but this happens:
**avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x71**

Keep in mind im aware of this error from other projects and have already tried multiple methods of fixing it, changing cable etc.

**Sublime**
When i click "Auto build" it returns with a blank command prompt that does nothing. 

### My Configurations

[config's.zip](https://github.com/MarlinFirmware/Marlin/files/5298590/config.s.zip)

### Steps to Reproduce

Just standard uploading from ardunio IDE procedure following this tutorial -> https://marlinfw.org/docs/basics/install_arduino.html

**Expected behavior:** [What you expect to happen]
For it to successfully upload the firmware to my ender 3 pro.

**Actual behavior:** [What actually happens]
Error message from above then stops compiling. 

#### Additional Information

So far i have tried the 3 most common methods and each of them have given me a different error. Every YouTube tutorial makes this process seem easy but so far its been nothing but grief. 
This is slightly infuriating.

**Comment by ellensp** [comment]
Welcome to Windows. Windows 10 has a hard coded 32k character limit on exec/fork. The Arduino IDE is badly written and the final link command exceeds this limit on large programs like Marlin
Use vscode with platfomio. Its faster, it knows how to avoid this windows limitation, and produces smaller code. (requires on old controllers with only 128KB)

**Comment by mikeandsuch** [comment]
I edited the report to encompass all three of the issues i've encountered instead of posting three separate reports

**Comment by ellensp** [comment]
re avrdude: stk500_recv(): programmer is not responding

You selected the wrong bootloader type, or the board has no bootloader.
Easiest fix is to install the optiboot bootloader, (is default with modern arduino ide) then you know what bootloader it has. Its also only 2k vs 4k of the older bootloader.  

No idea on sublime.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by mikeandsuch** [comment]
Oh ok thanks ill try the optiboot bootloader.
