### ISSUE TITLE
Reprap Discount Full Graphics Smart Controller Display is Garbled [BUG]

### ISSUE THREAD

**Issue by ktraglin** [MarlinFirmware/Marlin#19556]
Reprap Discount Full Graphics Smart Controller Display is Garbled - previous issue #12003
Previously closed.  Athough I can NOT reproduce this error in Marlin version 2.0.5, this problem appears to have re-emerged in 2.0.6.

Using the default configuration (except added to configuration.h):
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

The timing changes from the previously closed bug/issue yeild no results with this new version (2.0.6), e.g.:
(added to configuration.h)
#define CPU_ST7920_DELAY_1 DELAY_NS(250)
#define CPU_ST7920_DELAY_2 DELAY_NS(250)
#define CPU_ST7920_DELAY_3 DELAY_NS(250)

Also tried these timing settings:
#define CPU_ST7920_DELAY_1 DELAY_NS(0)
#define CPU_ST7920_DELAY_2 DELAY_NS(250)
#define CPU_ST7920_DELAY_3 DELAY_NS(0)

And these:
#define CPU_ST7920_DELAY_1 DELAY_NS(0)
#define CPU_ST7920_DELAY_2 DELAY_NS(400)
#define CPU_ST7920_DELAY_3 DELAY_NS(0)

I really would like to take advantage of the newer 2.0.6 firmware, but for the moment, I'm forced to go back to Marlin version 2.0.5.  Any suggestions will be welcomed. : )

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) its newer than 2.0.5 and 2.0.6 and 2.0.7

**Comment by ktraglin** [comment]
I'm using the default files (except for the 4 lines of changes/additions I mentioned).

**Comment by sjasonsmith** [comment]
> I'm using the default files (except for the 4 lines of changes/additions I mentioned).

It doesn't matter. You need to attach them to request help. From this issue nobody can tell even what motherboard you are using, which is inseparable from these LCD timings.

**Comment by ktraglin** [comment]
> > I'm using the default files (except for the 4 lines of changes/additions I mentioned).
> 
> It doesn't matter. You need to attach them to request help. From this issue nobody can tell even what motherboard you are using, which is inseparable from these LCD timings.
 
The board I'm using is the same as what's specified in the default config files, but...
Understood... attached, here.
[Uploading configuration-files.tgz…]()

**Comment by sjasonsmith** [comment]
@ktraglin that download link appears to just be a link back to the issue?

**Comment by ktraglin** [comment]
> @ktraglin that download link appears to just be a link back to the issue?

I see the same thing.  I'll try again using "zip" instead of "tar-gzip"... stupid me.
[Uploading configuration-files.zip…]()

**Comment by ktraglin** [comment]
Still only see link to issue.   Once more, here.  Apparently, uploading a file as part of a "quoted" reply doesn't work the way I thought...
[configuration-files.zip](https://github.com/MarlinFirmware/Marlin/files/5301804/configuration-files.zip)

**Comment by ktraglin** [comment]
> Configurations, please
> Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
> requested in the Issue template) and drop them into your next reply.
> We'll check them over and see if anything is amiss.
> 
> Please test the [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) its newer than 2.0.5 and 2.0.6 and 2.0.7

I wasn't even aware of a version 2.0.7, but now I've tried with Marlin-bugfix-2.0.x.  Same results.

**Comment by sjasonsmith** [comment]
I was going to test it, but I apparently damaged by Mega2560 board. Hopefully somebody else will volunteer to try it.

**Comment by ellensp** [comment]
Firstly did you notice the yellow warnings?
"CPU_ST7920_DELAY_2" Redefined
"CPU_ST7920_DELAY_2" Redefined

as 
  #define CPU_ST7920_DELAY_1 DELAY_NS(0)
  #define CPU_ST7920_DELAY_2 DELAY_NS(0)
  #define CPU_ST7920_DELAY_3 DELAY_NS(63)
are already defined in Marlin/Marlin/src/lcd/dogm/ultralcd_st7920_u8glib_rrd_AVR.h

But regardless of this. Your configs compiles and the display works as expected on my system.

**Comment by ellensp** [comment]
to actually change these values you need to set 
#define BOARD_ST7920_DELAY_1 DELAY_NS(250)
#define BOARD_ST7920_DELAY_2 DELAY_NS(250)
#define BOARD_ST7920_DELAY_3 DELAY_NS(250)
not CPU_ST7920_DELAY

**Comment by ktraglin** [comment]
> to actually change these values you need to set
> #define BOARD_ST7920_DELAY_1 DELAY_NS(250)
> #define BOARD_ST7920_DELAY_2 DELAY_NS(250)
> #define BOARD_ST7920_DELAY_3 DELAY_NS(250)
> not CPU_ST7920_DELAY

1.  I do recall seeing the yellow warning messages you mentioned.
2.  Your suggestion works (#define BOARD..., instead of #define CPU...
3.  THANK YOU, THANK YOU, THANK YOU!!!  Now I can play around with Marlin 2.0.6. : )

**Comment by ktraglin** [comment]
@thisiskeithb Why was this issue closed?  Has the code been updated to address this issue?  Is there a newer release users can download?

**Comment by thisiskeithb** [comment]
> Why was this issue closed? Has the code been updated to address this issue? Is there a newer release users can download?

Your last comment made it sounds like it worked. Did it not?

> THANK YOU, THANK YOU, THANK YOU!!! Now I can play around with Marlin 2.0.6. : )

Also: 

> Is there a newer release users can download?

Yes. Please download [`2.0.7`](https://github.com/MarlinFirmware/Marlin/archive/2.0.x.zip)/[`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by sjasonsmith** [comment]
Also @ellensp said it worked fine on their system with the default values. Most likely there is a noise or cable length issue in @ktraglin making slower speeds necessary.

**Comment by ktraglin** [comment]
> > Why was this issue closed? Has the code been updated to address this issue? Is there a newer release users can download?
> 
> Your last comment made it sounds like it worked. Did it not?
> 
> > THANK YOU, THANK YOU, THANK YOU!!! Now I can play around with Marlin 2.0.6. : )
> 
> Also:
> 
> > Is there a newer release users can download?
> 
> Yes. Please download [`2.0.7`](https://github.com/MarlinFirmware/Marlin/archive/2.0.x.zip)/[`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

Yes, what @ellensp proposed did fix the issue, but I had to add their code to my configuration.h file.  My question was about other users being able to have this fix without the need to add code on their own.

**Comment by ktraglin** [comment]
> Also @ellensp said it worked fine on their system with the default values. Most likely there is a noise or cable length issue in @ktraglin making slower speeds necessary.

I do not experience the issue with Marlin version 2.0.5, using the exact same printer.  So, I have reservations about a noise or cable length issue being the culprit.

**Comment by ellensp** [comment]
issue is specific to you..   either a slow clone screen or long cables...
On my RRD GLCD defaults works fine on the standard RAMPS.

**Comment by ktraglin** [comment]
> issue is specific to you.. either a slow clone screen or long cables...
> On my RRD GLCD defaults works fine on the standard RAMPS.

I don't know if a RRD GLCD is the same as the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER?  I'm also skeptical because plenty of people have not upgraded yet.  It could take months for more people to upgrade, and those who are still using 2.0.5 (like me, until just this week) may not see/experience the issue until they decide to upgrade.

**Comment by ellensp** [comment]
RRD = RepRap_Discount
GLCD = FULL_GRAPHIC_SMART_CONTROLLER

**Comment by ktraglin** [comment]
> RRD = RepRap_Discount
> GLCD = FULL_GRAPHIC_SMART_CONTROLLER

I interpreted the RRD part OK, but the GLCD part kinda puzzled me.  Thanks, again.

**Comment by ktraglin** [comment]
> > Why was this issue closed? Has the code been updated to address this issue? Is there a newer release users can download?
> 
> Your last comment made it sounds like it worked. Did it not?
> 
> > THANK YOU, THANK YOU, THANK YOU!!! Now I can play around with Marlin 2.0.6. : )
> 
> Also:
> 
> > Is there a newer release users can download?
> 
> Yes. Please download [`2.0.7`](https://github.com/MarlinFirmware/Marlin/archive/2.0.x.zip)/[`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

During the past hour, I've had opportunity to download 2.0.7, and applied bugfix-2.0.x.  I've uncommented:
//#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
to reflect:
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

I'm still having the same issue, but again, using 2.0.5, it works fine.  This issue appears to be unresolved without adding the timing parameter lines of code.  This appears to remain an issue for 2.0.6, and 2.0.7, although I only tried the bugfix update for 2.0.7.

**Comment by ktraglin** [comment]
@thisiskeithb I have attached the config files for 2.0.7 with the bugfix applied, here.
[Configuration-files.zip](https://github.com/MarlinFirmware/Marlin/files/5308330/Configuration-files.zip)
