### ISSUE TITLE
[BUG] Anycubic i3 Mega S display shows negativ hotend temperature

### ISSUE THREAD

**Issue by fiechr** [MarlinFirmware/Marlin#19564]
### Bug Description

While the temperature in the terminal is showing up fine with 210°C for the hotend, the Anycubic display shows this:

![IMG_20200930_164814](https://user-images.githubusercontent.com/12040376/94703500-301d9480-033f-11eb-9a5f-6d1ce53b3197.jpg)

Heatbed temperature shows up correctly.

Last known working configuration was last stable release 2.0.6.1.

### My Configuration

This is my current configuration for the i3 Mega S, based on 2.0.7:
https://github.com/fiechr/Marlin/tree/b32a496503c6d39843382eda5409f5062339f3c3/Marlin

Main PCB and display PCB of the printer:

![IMG_20200921_105400](https://user-images.githubusercontent.com/12040376/94705352-3c0a5600-0341-11eb-8804-1ff8949b6add.jpg)

**Comment by wernju1** [comment]
I have the same problem at mine. Doesn't matter if compiled with arduino or platformio.
Further Marlin Versions displays correct values.

**Comment by boelle** [comment]
> Further Marlin Versions displays correct values.

2.0.7 is the latest so there are no further than that, what version do display correct?

**Comment by wernju1** [comment]
I meant that all versions before 2.0.7 were ok. 2.0.7. is the only version with this issue.

**Comment by fiechr** [comment]
For me, the last stable release 2.0.6.1 (same configuration) showed the correct values, too. Before that I used Marlin 1.1.x.

EDIT: It also seems to work for lower temperatures, but I haven't check that in detail. Maybe some kind of variable overflow?

**Comment by boelle** [comment]
> 2.0.7. is the only version with this issue.

what about [`bugfix-2.0.x branch`](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) ?

**Comment by sjasonsmith** [comment]
The 2’s complement of 210 is -46. That doesn’t quite match what you reported, but there might just be a timing gap between reading your two numbers.

My guess is that somewhere the unsigned temperature is being forced into an int8_t, resulting in this behavior. Even if that were a uint8_t, that still seems too small for temperature, which can easily exceed 255.

**Comment by thisiskeithb** [comment]
PR https://github.com/MarlinFirmware/Marlin/pull/19572 should fix this issue. Can you test it and report back?

**Comment by wernju1** [comment]
It works. The problem is solved

**Comment by fiechr** [comment]
Happy to confirm, that it works for me too.

Thank you for the fast fix and your work for the Anycubic printers! :-)

**Comment by stef-ladefense** [comment]
it works very well by replacing "ui8tostr3rj" by "ui16tostr3rj"
it will support heads that support over 255 ° C.
