### ISSUE TITLE
dual extruder shows without temp

### ISSUE THREAD

**Issue by Brokengeiger** [MarlinFirmware/Marlin#19560]
I have a dual extruder rigidbot upgrade (reliabuild3d 3 essentially)  
It seems though that the 2nd extruder works and the temp does work, but it's not exposed properly 

The extruder 1 & 2 are sharing extruder 1 slot in tools like pronterface, astroprint and Cura.

https://photos.google.com/album/AF1QipNoS4Z26IZbEkD0iuOerrKhG81rF6ADvYADL3Zi

**Comment by ellensp** [comment]
Didn't follow template. Didn't include required config files. link is to a 404 error. No information to go on here. Closing.
