### ISSUE TITLE
Configurable Homing order of G28

### ISSUE THREAD

**Issue by sjkelly** [MarlinFirmware/Marlin#1956]
It was mentioned in #1079 that the homing order of G28 could be fixed by splitting the command into three: `G28 Z\nG28 Y\nG28 X\n`. However this leaves the G28 command unsafe to use on many corexy printers than have stationary endstops for X and Y. 

I would like to make a PR for making this a Configuration.h option so we don't have to reorder the execution in the code. Any feedback on this idea would be appreciated!

**Comment by nophead** [comment]
What are "stationary endstops" and why is corexy different to other Cartesian machines?

**Comment by sjkelly** [comment]
See below.

![20150422_123311](https://cloud.githubusercontent.com/assets/2086412/7279745/424af6ac-e8ec-11e4-8fff-93d71636afa6.jpg)

**Comment by nophead** [comment]
Sorry,  I still don't understand. The picture seems to show a moving opto
and a stationary tab. How is that different from a stationary opto and a
moving tab?

**Comment by sjkelly** [comment]
Sorry it was not clear. Both endstops are at (0,0). In this case Y needs to be at 0 to home X, otherwise the flag will miss the endstop.

**Comment by nophead** [comment]
I see, it's because the X axis moves with Y but the tab for its limit switch is not mounted on the X axis and stays at 0,0. 

Is there a reason why this is the case for corexy or just a design choice?

**Comment by ntoff** [comment]
why not just put your preferred homing methods in your startup gcode? I have mine raise the Z, home x and y and then home Z, it just sits there in my start gcode file and gets added on every time I slice something.

**Comment by sjkelly** [comment]
@ntoff We currently do exactly that. The issue is sending a `G28` from a user interface like Repetier or pronterface will home in the traditional fashion which will crash the axes.

**Comment by thinkyhead** [comment]
When #1957 is ready to merge it should help with this. It's good to have this option (in one form or another) for those rare designs that depend on it.

**Comment by sjkelly** [comment]
I think this can be closed with #1957
