### ISSUE TITLE
[BUG] Test issue to test Github is broken or not

### ISSUE THREAD

**Issue by qwewer0** [MarlinFirmware/Marlin#19588]
Test issue to test Github is broken or not.

**Comment by sjasonsmith** [comment]
I wonder if very long descriptions don’t display for some reason. The API the bot uses can see it, but the web view cannot?

**Comment by sjasonsmith** [comment]
One mentioned having a video, maybe some particular type of attached resource breaks it?

**Comment by qwewer0** [comment]
Not sure, but it could be that it is fixed already.
