### ISSUE TITLE
[BUG] Baby-stepping screen not accepting user change 

### ISSUE THREAD

**Issue by appliedmike** [MarlinFirmware/Marlin#19585]
<!--

Before filing an issue be sure to test the "bug-fix" branches to see whether the issue has been resolved. 
- Tried latest this morning 02/oct

### Bug Description
Since update to latest version 2.0.7 baby stepping screen is displayed but not change when pressing + or -
I have downloaded the bugfix ( 02 oct )

### My Configurations
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5317210/Marlin.zip)

### Steps to Reproduce
1. Start print
2. access 'Tune'
3.Access 'Baby-stepping'
4. Screen populates like normal
5. press + or -, no change on Z position or baby stepping value

**Expected behavior:**
Previous releases see a change in baby stepping value and small incremental change in printer Z height when '+' or '-' are pressed

**Actual behavior:** 
No change in Z position
No change in reported baby stepping

#### Additional Information
Config : Makerbase Robin nano 1.2 with TFT3.5 v1.0
using TFT_480x320 
CoreXY system.

**Comment by ellensp** [comment]
Edited: Seems github ate the contents. Restored what we could from discord log below. And reopened.

**Comment by sjasonsmith** [comment]
That is strange. It had content in the Discord bot notification. @appliedmike did you actually come back here and delete all the content?

**Comment by qwewer0** [comment]
This isn't the first one. https://github.com/MarlinFirmware/Marlin/issues/19579

Wouldn't deleting the content leave an edit mark?

**Comment by ellensp** [comment]
@sjasonsmith  that is intersting. Discord does have some info...  and issue doesn't say edited..  broken github??

Re posting here.

> 
> - Tried latest this morning 02/oct
> 
> ### Bug Description
> Since update to latest version 2.0.7 baby stepping screen is displayed but not change when pressing + or -
> I have downloaded the bugfix ( 02 oct )
> 
> ### My Configurations
> [Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5317210/Marlin.zip) 
>

**Comment by appliedmike** [comment]
Hi All,@sjasonsmith, No I tried to follow the requested format and did not edit once submitted Sent from Mail for Windows 10 From: Jason SmithSent: Friday, 2 October 2020 11:14 PMTo: MarlinFirmware/MarlinCc: Michael Christie; MentionSubject: Re: [MarlinFirmware/Marlin] [BUG] Baby-stepping screen not accepting user change (#19585) That is strange. It had content in the Discord bot notification. @appliedmike did you actually come back here and delete all the content?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by appliedmike** [comment]
Hey All,
@sjasonsmith, no I hadn't edited anything once I had posted. Being in the southern hemisphere I just waited for a glimpse of brilliant to my issue once everyone woke up :-) 
I followed the template as fully as possible

**Comment by appliedmike** [comment]
Working as at 2.0.7.1 :-)
