### ISSUE TITLE
[FR] Use Z-Home microswitch as fail safe

### ISSUE THREAD

**Issue by mojtabacazi** [MarlinFirmware/Marlin#19580]
### Description

I've installed BLTouch and so far I had a few incidents where, due to misconfiguration, bltouch failed to recognize the bed and caused the nozzle to crash into the bed. I was thinking it is possible to keep the original hardware micro switch still connected to the board and be monitored as a secondary safety measure. I undrestand the nozzle may still crash to the bed but at least you can prevent stepper from trying to move it even further. 
I'm not familiar with the board and not sure if there is any number of I/O available to achieve this or not.

### Feature Workflow

1. Install BL Touch along side with original z-axis switch
2. Halt iIf z-axis switch is triggered.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
