### ISSUE TITLE
[BUG] Robin Nano v1.2 with Marlin Color UI: display mirrored (left/right)

### ISSUE THREAD

**Issue by Miraculix200** [MarlinFirmware/Marlin#19603]
One of the recent commits since Sep 29 causes the 3.5" display on the Robin Nano 1.2 board to be horizontally mirrored (not rotated), when using Marlin Color UI. But I don't find any changes which could cause this, e.g. in the Robin Nano v1.2 pins file. Maybe one of the developers has an idea?

**Comment by rhapsodyv** [comment]
Try changing this: `#define ILI9488_ORIENTATION               ILI9488_MADCTL_MX | ILI9488_MADCTL_MV`
to:
`#define ILI9488_ORIENTATION              ILI9488_MADCTL_MY |  ILI9488_MADCTL_MX | ILI9488_MADCTL_MV`
In the pins file.

It will end for all, when #19192 get merged... :-(

**Comment by thisiskeithb** [comment]
Please follow the Issue Template when filing a bug report. This includes attaching your configs:

```md
<!--

Have you read Marlin's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/.github/code_of_conduct.md

Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use the Marlin Firmware forum at http://forums.reprap.org/list.php?415 or the Marlin Facebook Group https://www.facebook.com/groups/1049718498464482/ or the Marlin Discord Server https://discord.gg/n5NJ59y.

Before filing an issue be sure to test the 1.1 and/or 2.0 "bugfix" branches to see whether the issue is already addressed.

-->

### Description

<!-- Description of the bug or requested feature -->

### Steps to Reproduce

<!-- If this is a Bug Report, please describe the steps needed to reproduce the issue -->

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.
```

**Comment by Miraculix200** [comment]
Ok, I will try. For some reason the display is normal again after restarting the printer

**Comment by rhapsodyv** [comment]
> Ok, I will try. For some reason the display is normal again after restarting the printer

Hum. It could indicate a bad init code. I will check that.

Did it only happen once?

**Comment by Miraculix200** [comment]
Yes, only once after the recent commits (since Sep 29). Will try rebooting it a few times after this print is over

**Comment by thisiskeithb** [comment]
@Miraculix200 Please attach your configs.

**Comment by Miraculix200** [comment]
https://github.com/Miraculix200/Marlin-SapphirePro-2209-UART/blob/SapphirePro-2209-UART/Marlin/Configuration.h
https://github.com/Miraculix200/Marlin-SapphirePro-2209-UART/blob/SapphirePro-2209-UART/Marlin/Configuration_adv.h
https://github.com/Miraculix200/Marlin-SapphirePro-2209-UART/blob/SapphirePro-2209-UART/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_NANO.h

**Comment by Miraculix200** [comment]
I tried restarting the printer 10 times but it didn't happen again. Maybe it only happens when the printer reboots automatically after flashing

**Comment by rhapsodyv** [comment]
So it’s look like more a bootloader issue.
