### ISSUE TITLE
Firmware 2.0.7 e3 bltouch wont deploy or stow after complie

### ISSUE THREAD

**Issue by johnny4800** [MarlinFirmware/Marlin#19601]
After Complie NeoPixel and Bl-touch dont work, but self-test when turn E3 on. Anyone ?? has the same problem. 2.6.1 no problem

**Comment by sjasonsmith** [comment]
This issue ignored the issue template and did not provide the requested information.

I am going to close this issue. It sounds like you may have a legitimate problem to report, but it is important that you include all the requested information in the issue template. That information is required, as it helps developers and users know how to help resolve your issue.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
