### ISSUE TITLE
[BUG] in language_de.h translation error

### ISSUE THREAD

**Issue by kkberg** [MarlinFirmware/Marlin#19612]
### Bug Description

some translation into German for filament change messages on display are wrong and in parts they are opposite of what it should be.

**Expected behavior:** 

..............

    PROGMEM Language_Str MSG_ADVANCED_PAUSE_WAITING        = _UxGT(MSG_1_LINE("Klicken zum Fortsetzen"));
    PROGMEM Language_Str MSG_PAUSE_PRINT_PARKING           = _UxGT(MSG_1_LINE("Parken..."));

    PROGMEM Language_Str MSG_FILAMENT_CHANGE_INSERT        = _UxGT(MSG_1_LINE("Laden und Klicken"));
    PROGMEM Language_Str MSG_FILAMENT_CHANGE_HEAT          = _UxGT(MSG_1_LINE("Klicken zum Heizen"));
    PROGMEM Language_Str MSG_FILAMENT_CHANGE_HEATING       = _UxGT(MSG_1_LINE("Heizen..."));
    PROGMEM Language_Str MSG_FILAMENT_CHANGE_UNLOAD        = _UxGT(MSG_1_LINE("Entladen..."));
    PROGMEM Language_Str MSG_FILAMENT_CHANGE_LOAD          = _UxGT(MSG_1_LINE("Laden..."));
    PROGMEM Language_Str MSG_FILAMENT_CHANGE_PURGE         = _UxGT(MSG_1_LINE("Düse Reinigen..."));
    PROGMEM Language_Str MSG_FILAMENT_CHANGE_CONT_PURGE    = _UxGT(MSG_2_LINE("Klicken zum Beenden", "der Fila-
Entladung"));
**Actual behavior:** for example "Entladen" instead of "Düse reinigen"

Would be great if someone could change, or use the include file which I already changed.

Thank you

**Comment by Speaka** [comment]
It was indeed wrong translated. I made a PR with the changes i think are the best german language.
Do you agree with that?

**Comment by kkberg** [comment]
Thank you, I agree.
