### ISSUE TITLE
Pause before deploy/stow not working with new UI style

### ISSUE THREAD

**Issue by alexeyzel** [MarlinFirmware/Marlin#19627]
### Bug Description
When I enable pause before deploy/stow feature by uncommenting #define PAUSE_BEFORE_DEPLOY_STOW - i can't confirm bed leveling sensor deployment on the screen, there is just no way to do it - when i click on deployment message - nothing happens.

### My Configurations
I have Flsun Q5 with MKS Robin Nano 1.2 board with 320x240 Graphical TFT screen. Marlin 2.0.7 release.
**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[alexeyzel_config.zip](https://github.com/MarlinFirmware/Marlin/files/5329328/alexeyzel_config.zip)

### Steps to Reproduce

1. Uncomment #define PAUSE_BEFORE_DEPLOY_STOW and enable UBL, compile firmware and upload it to printer
2. Turn the printer on and send "G28" command
3. Send "G29 P1" command

**Expected behavior:** [What you expect to happen]

Clickable message should appear at the center of the screen "Deploy Z-Probe", after manual probe deployment i should be able to confirm probe deployment by taping on the screen and bed leveling process should continue.

**Actual behavior:** [What actually happens]

"Deploy Z-Probe" message appears in the status bar and it is not clickable, there is no way to confirm probe deployment.

![120597729_3495352840527053_6358815970162577230_n](https://user-images.githubusercontent.com/50808386/95116860-5cc31900-0750-11eb-912e-f67322fcfe54.jpg)

**Comment by rhapsodyv** [comment]
I will take a look

**Comment by Foxies-CSTL** [comment]
I confirm the same issues with FSMC and Color UI on QQS-Pro. The trick to validate is to press twice: once on an icon (bed, prefs, temp or fan) and again on the validation of the function. You have to do the same trick with the "BabyStepping" function to activate it during the first line of a print.

**Comment by rhapsodyv** [comment]
This a bit tricker to solve. When marlin is used with a encoder, a "click" could happened anywhere. So, there's a few marlin operations that waits for those click without a specific screen for that.

I will do some tests and add a PR for testing soon.

**Comment by rhapsodyv** [comment]
Can you test this PR? #19694 

Thanks.

**Comment by boelle** [comment]
@Foxies-CSTL @alexeyzel did the pr from @rhapsodyv help?

**Comment by Foxies-CSTL** [comment]
Hi ,
@boelle, I tried it and I replied on PR #19694 . I do it  with the last update bugfix (TFT Refactoring) and today I have a same issue. Ok for G33 but with the UBL (Build_Cold_Mesh) after have to valid the deploy, my screen freeze and I must do make reset. No problem with the screen to mode "TFT_Classic_UI" only mode "TFT_Color_UI".

**Comment by rhapsodyv** [comment]
I will take a look in the UBL thing.

**Comment by rhapsodyv** [comment]
This issue can be closed. I asked @Foxies-CSTL to open an issue specific for his problem, with his configs.

**Comment by alexeyzel** [comment]
Sorry for delay with testing. Tested in bugfix - works OK now. I just clicked the screen anywhere to confirm probe deployment.
