### ISSUE TITLE
Desorden de lineas en PowerLoss

### ISSUE THREAD

**Issue by RENOPS** [MarlinFirmware/Marlin#19636]
Al reanudar después de un fallo eléctrico lo primero que hace es Home, arrastrando la pieza impresa.
Cambiando de lugar las lineas desde 334 a 387,  y colocando las después de linea 412, se soluciona.

El orden actual es:
Leveling->Home->Volumetrics->**_Bed->Hotend ...._**

El correcto (a mi parecer) sería:
Leveling->**_Bed->Hotend_**->Home->Volumetrics

**When resuming after a power failure the first thing it does is Home, dragging the printed part.
Moving the lines from 334 to 387, and placing them after line 412, solves it.**

**Comment by thinkyhead** [comment]
If you don't have a backup power supply then you need to disable `BACKUP_POWER_SUPPLY`.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.
