### ISSUE TITLE
M581 Command not working printing in the air.

### ISSUE THREAD

**Issue by sandmix** [MarlinFirmware/Marlin#19672]
Marlin 2.0.7 Anet A8 Clone , after instalation configured axes when homing everything is ok, but when printer starts on screen I see Z 5 after Z 15 and Z 0.3 and Z doesn't even move. I think in code it indicates to make Z ofset +10. 
On M581 it gives 👍 >>> M581
SENDING:M581
echo:Unknown command: "M581"

There is no more  Z_PROBE_OFFSET_FROM_EXTRUDER

also no option to set z offset from LCD.  Any ideas ?

Thanks

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
