### ISSUE TITLE
Bltouch do not stop axis Z

### ISSUE THREAD

**Issue by BeppeTemp** [MarlinFirmware/Marlin#19679]
Hi I have recently installed a skr 1.3 with Marlin 2.0 firmware and an original Bltouch 3.0 in my ender 3. But I have a problem (which pierced my brand new plate): In practice, the Bltoucg during auto homing does not stop the z axis when it clicks.

I attach my configuration files:

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/5359637/Config.zip)

**Comment by ghost** [comment]
have you tried #define USE_PROBE_FOR_Z_HOMING? 
Also it's probably good practice to raise z halfway up to max and then use your finger to test if it stops so you have enough time to cut power before it pierces the plate.

**Comment by ghost** [comment]
I also see you have
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
enabled which should enable USE_PROBE_FOR_Z_HOMING automatically

How is your bltouch wired up? Is it actually wired to the Z_min_endstop_pin? Or is it wired to separate pin? If there is a mismatch this could explain the problem.

**Comment by BeppeTemp** [comment]
Yes, It Is wired to the Z_min_endstop_pin.

**Comment by ghost** [comment]
I see you have CONFIG_EXAMPLES_DIR set to "Creality/Ender-3/CrealityV1", which I believe means that you are using a default config file that was set up for the creality 1.1.x mainboard, yet you are using a third party mainboard skr. I really think you have simply set z_probe to use the wrong pin within your config file.

**Comment by ghost** [comment]
oh wait never mind. You have the correct board set with define motherboard to BTT_SKR_V1_3. In that case I'm out of ideas. Next step I guess would be to use gcodes to manually verify if the printer is reporting the correct values for your sensors. idk. Although given the behavior, I still think that somewhere the wrong pin was set. Either manually in the wiring or somewhere in the config file.

**Comment by BeppeTemp** [comment]
could you write me the g-code so tomorrow morning I'll try it please?

**Comment by ghost** [comment]
which bltouch are you using? i.e. 3.1 3.0 /etc? 
go to https://www.antclabs.com/manual and download the appropriate manual for your bltouch and ensure the settings for your particular model are correct. They have example config usually at bottom of manual

**Comment by BeppeTemp** [comment]
3.0 thanks. I will see tomorrow.

**Comment by ghost** [comment]
as for gcode, just try one of the following from https://marlinfw.org/docs/gcode/:
M43 - Debug Pins 
M119 - Endstop States 
M226 - Wait for Pin State 

To send gcodes (but more importantly to read the output) you will need either pronterface software or octoprint.

**Comment by ellensp** [comment]
the black/white cable has polarity, you must plug it in correct way. White needs to be on the signal pin

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
