### ISSUE TITLE
[Q] EEPROM CRC error

### ISSUE THREAD

**Issue by LUIZ-RODRIGUES-ANDRADE** [MarlinFirmware/Marlin#19689]
![Repetier-Host V2 0 5 11_10_2020 13_55_53](https://user-images.githubusercontent.com/72706809/95687457-20713c00-0bda-11eb-97e5-ecd03b4b1f72.png)
![Repetier-Host V2 0 5 11_10_2020 15_55_33](https://user-images.githubusercontent.com/72706809/95687485-41d22800-0bda-11eb-8ea5-e5936edaa2ce.png)
![Repetier-Host V2 0 5 11_10_2020 15_55_40](https://user-images.githubusercontent.com/72706809/95687486-426abe80-0bda-11eb-95f1-b2085c8dbae2.png)
![Repetier-Host V2 0 5 11_10_2020 13_55_53](https://user-images.githubusercontent.com/72706809/95687487-43035500-0bda-11eb-86b4-22daba119577.png)
![Repetier-Host V2 0 5 11_10_2020 15_55_23](https://user-images.githubusercontent.com/72706809/95687488-43035500-0bda-11eb-924b-1d01ed998305.png)

15:49:00.947 : Serial COM erro:System.IO.Ports.SerialErrorReceivedEventArgs
15:49:00.957 : Printer reset detected - initalizing
15:49:00.957 : start
15:49:00.957 : echo: External Reset
15:49:00.957 : Marlin Base on Marlin1.1.8
15:49:00.957 : echo: Last Updated: 2018-10-01 | Author: (Hally@ZONESTAR)
15:49:00.957 : echo:Compiled: Oct 20 2018
15:49:00.957 : echo: Free Memory: 11693  PlannerBufferBytes: 1360
15:49:00.970 : Error:EEPROM CRC mismatch - (stored) 63187 != 52708 (calculated)!
15:49:01.014 : echo:Hardcoded Default Settings Loaded
15:49:01.014 : echo:  G21    ; Units in mm
15:49:01.014 : echo:  M149 C ; Units in Celsius
15:49:01.014 : echo:Filament settings: Disabled
15:49:01.014 : echo:  M200 D1.75
15:49:01.014 : echo:  M200 D0
15:49:01.014 : echo:Steps per unit:
15:49:01.014 : echo:  M92 X80.00 Y80.00 Z400.00 E85.00
15:49:01.014 : echo:Maximum feedrates (units/s):
15:49:01.014 : echo:  M203 X150.00 Y100.00 Z8.00 E50.00
15:49:01.014 : echo:Maximum Acceleration (units/s2):
15:49:01.014 : echo:  M201 X2000 Y800 Z100 E5000
15:49:01.014 : echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
15:49:01.014 : echo:  M204 P500.00 R500.00 T1000.00
15:49:01.039 : echo:Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_us> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
15:49:01.039 : echo:  M205 S0.00 T0.00 B20000 X10.00 Y10.00 Z2.70 E5.00
15:49:01.039 : echo:Material heatup parameters:
15:49:01.039 : echo:  M145 S0 H190 B50 F0
15:49:01.039 : echo:  M145 S1 H240 B100 F0
15:49:01.039 : echo:PID settings:
15:49:01.039 : echo:  M301 P46.80 I3.86 D141.85
15:49:01.171 : N1 M110*34
15:49:01.171 : N2 M115*36
15:49:01.171 : N3 M105*36
15:49:01.171 : N4 M114*35
15:49:01.175 : N5 M111 S6*98
15:49:01.177 : N6 T0*60
15:49:01.177 : N7 M20*22
15:49:01.180 : N8 M80*19
15:49:01.180 : N9 M105*46
15:49:04.072 : ok
15:49:04.239 : N10 M105*22
15:49:04.588 : N11 M20*33
15:49:04.603 : echo:SD card ok
15:49:04.648 : FIRMWARE_NAME:Marlin Base on Marlin1.1.8 (Github) SOURCE_CODE_URL:https://github.com/zonestar3d PROTOCOL_VERSION:1.0 MACHINE_TYPE:Z5NM2 EXTRUDER_COUNT:1 UUID:00000010-0808-0003-0000-20180110001
15:49:04.648 : Cap:SERIAL_XON_XOFF:0
15:49:04.650 : Cap:EEPROM:1
15:49:04.650 : Cap:VOLUMETRIC:1
15:49:04.650 : Cap:AUTOREPORT_TEMP:1
15:49:04.650 : Cap:PROGRESS:0
15:49:04.650 : Cap:PRINT_JOB:1
15:49:04.650 : Cap:AUTOLEVEL:0
15:49:04.650 : Cap:Z_PROBE:0
15:49:04.650 : Cap:LEVELING_DATA:0
15:49:04.650 : Cap:BUILD_PERCENT:0
15:49:04.650 : Cap:SOFTWARE_POWER:0
15:49:04.650 : Cap:TOGGLE_LIGHTS:0
15:49:04.650 : Cap:CASE_LIGHT_BRIGHTNESS:0
15:49:04.650 : Cap:EMERGENCY_PARSER:0
15:49:04.650 : ok
15:49:04.651 : N12 M220 S100*82
15:49:04.670 : ok T:26.75 /0.00 B:26.72 /0.00 @:0 B@:0
15:49:04.685 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
15:49:04.685 : ok
15:49:04.685 : N13 M221 S100*82
15:49:04.702 : echo:DEBUG:INFO,ERRORS
15:49:04.702 : ok
15:49:04.702 : ok
15:49:04.702 : Begin file list
15:49:04.702 : N14 M111 S6*82
15:49:04.705 : N15 T0*14
15:49:04.726 : CFFFP_~1.GCO 5055174
15:49:04.734 : End file list
15:49:04.734 : ok
15:49:04.734 : ok
15:49:04.735 : N16 M155 S1*87
15:49:04.736 : ok T:26.75 /0.00 B:26.72 /0.00 @:0 B@:0
15:49:04.740 : ok T:26.75 /0.00 B:26.72 /0.00 @:0 B@:0
15:49:04.741 : Begin file list
15:49:04.764 : CFFFP_~1.GCO 5055174
15:49:04.770 : End file list
15:49:04.770 : ok
15:49:04.770 : ok
15:49:04.774 : ok
15:49:04.774 : echo:DEBUG:INFO,ERRORS
15:49:04.774 : ok
15:49:04.774 : ok
15:49:04.774 : ok
15:49:05.778 : T:27.00 /0.00 B:26.62 /0.00 @:0 B@:0
15:49:06.784 : T:27.00 /0.00 B:26.70 /0.00 @:0 B@:0
15:49:07.777 : T:27.00 /0.00 B:26.67 /0.00 @:0 B@:0

**Comment by thisiskeithb** [comment]
You're using an older fork of Marlin, which we can't support here. Give Marlin `2.0.x` a try.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
