### ISSUE TITLE
[BUG] SKR PRO not working with last stable version (need confirmation)

### ISSUE THREAD

**Issue by BastR** [MarlinFirmware/Marlin#19688]
### Bug Description

SKR PRO not working since upgrading marlin to last stable version.

LCD is blue
The motors only move in one direction, if I ask X to go left and then right, the motor always goes left.
X motor is always on, I can't deactivate the stepper
Fan are working
Octoprint can comunicate with the board
I didn't try to heat the nozzle or the bed.

### My Configurations

Functional config: https://github.com/BastR/Marlin/tree/Titan
No funcional config: https://github.com/BastR/Marlin/tree/Titan_NEW

I first tried to update my current firmware but it didn't work, so I'm back on a virgin marlin base with the latest stable version, it didn't work either.

I took a firmware available on the Bigtreetech github and the printer worked again.

I have a second printer with a similar setup, I used this base by updating the configuration files and everything works again...

So I can say that everything was functional on 30/09, since then something has been introduced and completely crashes the card.
<img width="1518" alt="Capture d’écran 2020-10-11 à 12 15 41" src="https://user-images.githubusercontent.com/20129420/95676027-7e425b80-0bbb-11eb-9197-0cce9fb9b48d.png">

 **I've done a lot of tests, someone would have to confirm what I'm saying because I get lost with all the things I've done.**

**Comment by ellensp** [comment]
If it didn't boot, you wouldn't be able to talk to it at all...

**Comment by rhapsodyv** [comment]
Can you try bugfix?

**Comment by Patag** [comment]
SKR pro boots fine but the issue is LCD related. Latest (today) bugfix fixed it

**Comment by BastR** [comment]
Vraiment pas de chance...

It now works with the current bugfix
