### ISSUE TITLE
Ender 3 V2 config files wrong?

### ISSUE THREAD

**Issue by rorywquin** [MarlinFirmware/Marlin#19699]
Edited -- please ignore I seem to have stumbled along and got it right.

Hi

I'm very new to this so please be gentle. Yesterday I used the bugfix-2.0 firmware & config files and compiled with your auto build. No issues.

Today I'm trying to do the same thing with the latest update and in platformio.ini my default_envs = mega2650 & not the expected for the Ender 3 V2.

I've tried several times...same result? Is it me?

**Comment by SlackHacky** [comment]
yes - it well documented that you need to change that to correct environment
