### ISSUE TITLE
G29 S0 switched back to OFF after reboot printer

### ISSUE THREAD

**Issue by arnostolk** [MarlinFirmware/Marlin#19705]
### Bug Description
After a reboot of the printer the G29 S0 status replies the Mesh Bed Leveling is switched OFF, but it should stay ON.

After using G29 commands to set mesh bed leveling, it is turned on: Recv: echo:Bed Leveling ON. 
M500 to store to EEPROM.
After a G28 mesh bed leveling stays on since I have #define RESTORE_LEVELING_AFTER_G28. that is working correctly.

Now when I reboot my printer and ask for G29 it returns Bed Leveling OFF. Also after G28 it stays off. After M420 S it's back ON and stays ON. Until I reboot my printer again and then it's back OFF.

### My Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5367183/Marlin.zip)

### Steps to Reproduce

1. Perform a G29 mesh bed level
2. execute M500 to store to EEPROM
2. Execute G28
3. Execute G29 to validate mesh bed leveling is ON and 'RESTORE_LEVELING_AFTER_G28' is active.
4. Reboot printer
5. Execute G28
6. Exectute G29

**Expected behavior:**
I would expect mesh bed leveling to be ON.
**Actual behavior:**
Mesh bed leveling is turned OFF.

#### Additional Information

* Behavior shown on a Ender 3 v2 with Marlin 2.0.7 (default branch)

**Comment by thinkyhead** [comment]
The printer doesn't know its position on startup, so it is not sensible to enable bed leveling until after a `G28` has been done. In general it makes no sense to enable bed leveling outside of an actual print job. So, the supported method for enabling bed leveling for print jobs is to put `M420 S1` at the start of your G-code.
