### ISSUE TITLE
Did not compile when enable Mechanical Gantry Calibration

### ISSUE THREAD

**Issue by Talha909** [MarlinFirmware/Marlin#19702]
I have download the New bug fix . And enable the Mechanical Gantry Calibration. But when i enable
![calibration](https://user-images.githubusercontent.com/29024390/95737314-ecad1980-0ca0-11eb-93d8-1b808afb265f.JPG)
 this then frimware did not compile. I got error message. 
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5364666/Marlin.zip)

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by Talha909** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5364660/Marlin.zip)
i have attached the config files. I had installed the SKR 1.4 TURBO with TMC2130 Drivers.

**Comment by Talha909** [comment]
> Please attach your configuration files.

Files are attached. I had installed SKR 1.4 TURBO with TMC 2130 and BLtouch.

**Comment by ellensp** [comment]
you have Z_STEPPER_AUTO_ALIGN and MECHANICAL_GANTRY_CALIBRATION
these seem to be mutually exclusive, since both define G34

**Comment by Talha909** [comment]
> you have Z_STEPPER_AUTO_ALIGN and MECHANICAL_GANTRY_CALIBRATION
> these seem to be mutually exclusive, since both define G34

What is mechanical gantry calibration.?

**Comment by ellensp** [comment]
introduced here https://github.com/MarlinFirmware/Marlin/pull/18972

**Comment by ellensp** [comment]
so replaces https://marlinfw.org/docs/gcode/M915.html

**Comment by Talha909** [comment]
I disable the Align Z and its compile now.

**Comment by thisiskeithb** [comment]
I created a sanity check in https://github.com/MarlinFirmware/Marlin/pull/19706 to prevent compiling when both options are enabled.

**Comment by Talha909** [comment]
Hi, 

Today I test it . But when I gave the command of G34 it always hit the bed and did not stop.  I am using Bltouch
