### ISSUE TITLE
[BUG] TFT_ROTATION_180 breaks TOUCH CALIBRATION

### ISSUE THREAD

**Issue by dulfe** [MarlinFirmware/Marlin#19721]
Using firmware 2.0.7.2 with the new TFT code with `TFT_ROTATION_180` breaks the CALIBRATION points.

After calibration, the values seem to be inversed somehow.

### My Configurations

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/5372624/Config.zip)

### Steps to Reproduce

1. `#define TFT_ROTATION TFT_ROTATE_180`
2.  Issue `M995` from G-Code
3. Follow Wizard.

**Expected behavior:** 

Calibration should complete and work.

**Actual behavior:** 

Calibration completes but it does not work. It seems inverted.

#### Additional Information

If you run M995 again but press these points:

- BOTTOM/RIGHT instead of TOP/LEFT
- BOTTOM/LEFT instead of TOP/RIGHT
- TOP/RIGHT instead of BOTTOM/LEFT
- TOP/LEFT instead of BOTTOM/RIGHT

The calibration completes and works.

**Comment by rhapsodyv** [comment]
In fact. Please try: #19710 

Thanks!

**Comment by dulfe** [comment]
@rhapsodyv Calibration Worked as expected!... Thank you.
