### ISSUE TITLE
[BUG] Part cooling fan starts with "Preheat * Bed"

### ISSUE THREAD

**Issue by lokster** [MarlinFirmware/Marlin#19737]
### Bug Description

I'm running Marlin-2.0.7 on RAMPS 1.6. Whenever I select "Temperature -> Preheat ABS -> Preheat ABS Bed" my part cooling fan starts running at full speed even though the Fan speed is set to 0% in the Preheat ABS/PLA Conf. 
This happens only when selecting Preheat ABS Bed (or Preheat PLA Bed). Does not happen when selecting "Temperature -> Preheat ABS -> Preheat ABS" or "Temperature -> Preheat ABS -> Preheat ABS End".

### My Configurations

[My Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5378874/My.Configuration.zip)

**Comment by ellensp** [comment]
This setting is stored in eeprom, make sure you reset eeprom contents to match your firmware settings. M502 then M500

**Comment by lokster** [comment]
It's the first thing I did after I flashed 2.0.7 and noticed the issue. Didn't fix it. To be sure, I just did it again, and the result is the same. Happens on 2 different printers with this configuration.

**Comment by rhapsodyv** [comment]
Fixed here: #19773 
Can you test it?
