### ISSUE TITLE
Y-axis Sensorless Homing is not working using FYSETC TMC2209 v3.1 on SKR 1.4

### ISSUE THREAD

**Issue by yasinzaii** [MarlinFirmware/Marlin#19747]
Sensorless Homing works perfectly fine for X-Axis, However, it's not working on Y-Axis. I checked the Endstop status using M119 command and Y is always showing triggered. When I give the homing command to Y-axis, it jerks towards the Y+ ( and moves like 5mm towards the y-max position)

I am using regular SKR 1.4 Board and (Not the turbo one)

-> I have used a jumper to connect the Y-Uart Pins as described in the SKR 1.4 board manual.

I am using Fystc TMC2209 v3.1

-> for both x and Y-axis

-> I have enabled sensorless homing in marlin

-> I am homing toward min position. (#define USE_YMIN_PLUG) (Y_HOME_DIR -1)

-> Endstop pull-ups has been enabled (#define ENDSTOPPULLUPS)

-> Endstop inverting has been set to false (Y_MIN_ENDSTOP_INVERTING false)

-> Homing Dir Inversion is false as described in multiple places on the internet (INVERT_Y_DIR false)

Things I did.

-> Reinstalled the latest version of the marlin and reconfigured it but didn't work.

-> Decreased the sensitivity of the Y-axis driver to 1 but still, endtsop status was still showing triggered and was not working.

-> Replaced the Y-axis driver with a new one but nothing happened.

-> Checked the voltage on the DIAG pin and it was High, (However it should be low as far as i know)

X-Axis works perfectly fine and homes correctly. But Y-Axis has this issue. Can someone please help me.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
