### ISSUE TITLE
MKS TFT32_L V4.0 not reading TEMP sensors

### ISSUE THREAD

**Issue by Zatarines** [MarlinFirmware/Marlin#19743]
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5382010/Configuration_adv.zip)

After upgrading my Board from a SKR 1.4V to a SKR Pro 1.2v, the TFT32  is not reading Sensors so that TEMP is zero for all and touch does not command the printer. I connected the TFT32 screen to the SKR Pro, using the board Pins TX, RX, 5v, GND. In Configuration.h , when I try to set the SERIAL_PORT to "0" in Configuration.h as I had with the previous board FW I get the " error: #error "SERIAL_PORT_2 must be -1 or from 1 to 6. Please update your configuration." Have anyone who has been successful using this HW to give me a hint here? thank you in advance.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by Zatarines** [comment]
@thisiskeithb 
Because I mentioned "HW" it is not a possible bug? the configuration that I am using worked just fine in Marlin FW June version. 
all the same, I will consult on those resources
