### ISSUE TITLE
SD card wont read on 3d printer marlin 2.0.7.1

### ISSUE THREAD

**Issue by DrArchadus** [MarlinFirmware/Marlin#19755]
I own an SKR 1.4 turbo and after instaling marlin 2.0.7.1 and configuring the firmware the SD card wont read (uncomented sdsupport) i formated it and it still won't work i looked around and couldnt find a fix to this issue

**Comment by thisiskeithb** [comment]
Try formatting the SD card or using a different one that is <32GB.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
