### ISSUE TITLE
[FR] New definition pins for Delta QQS-Pro.

### ISSUE THREAD

**Issue by Foxies-CSTL** [MarlinFirmware/Marlin#19761]
### Description
FLSun delivers with the latest models of QQS-PRo, a clone of the Mks_Robin_min v2 board which allows drivers to be replaced. This is called HISPEEDv1. I created a new definition of pinouts to support different features.

### Feature Workflow
Features|Active|Value
  --------|------|-----
  Multi-Config Switch QQS-PRO|True|QQS_Config.h
  Choice of independent E driver from XYZ|Standard-TMC|Ready
  Module Wifi|True|Ready
  ZoffSet ED3v6|-|Ready|
  Extruder TITAN/BMG| Titan|Ready
  BabyStepping|True|Ready
  UI Type|True|Color Marlin|
  TFT Color Selection|True|Classic,Color
  Unified Bed Leveling|True|+53pts
  Filament sensor|True|Ready
  Recovery PowerFailed|True|-
  TMC 220x Soft Serial|UART|Ready
  TMC 2209 Hard Serial|UART|Ready
  Neopixel|Note|Ready

**Note:** For NeoPixel I am using a modified version 2.4.

For compilation under VSC/PIO, I use the modified environment of Robin_nano35 with the script "ms_robin_mini.py" for the binary naming and the script "add_nanolib.py "to reduce its size.
`[env:flsun_hispeed]
platform        = ${common_stm32f1.platform}
extends         = common_stm32f1
board           = genericSTM32F103VE
platform_packages = tool-stm32duino
extra_scripts   = ${common.extra_scripts}
  buildroot/share/PlatformIO/scripts/mks_robin_mini.py
  buildroot/share/PlatformIO/scripts/add_nanolib.py
build_flags     = ${common_stm32f1.build_flags}
  -DMCU_STM32F103VE -DSS_TIMER=4
lib_deps = ${common.lib_deps}
  SoftwareSerialM
  Adafruit NeoPixel=https://github.com/Foxies-CSTL/NeoPixel-Lib/archive/master.zip`

### Pack: Configs, Scripts, pins
[Pack_FLSun_QQS-Pro.zip](https://github.com/MarlinFirmware/Marlin/files/5388644/Pack_FLSun_QQS-Pro.zip)

#### Additional Information
My first stable release with Marlin Firmware 2.0.7 is on my [GitHub](https://github.com/Foxies-CSTL/Marlin_2.0.x/releases) . It contains the sources and different binaries to use.
_MB-FLSun_HiSpeed_
![MC-FLSun_HiSpeed](https://user-images.githubusercontent.com/24864147/96197468-759eac00-0f52-11eb-8941-af1b957f9f94.jpg)
_MB-HiSpeed UART Serial mode_
![MC-HiSpeed UART Serial mode](https://user-images.githubusercontent.com/24864147/96197624-e8a82280-0f52-11eb-9122-3363b2d6ca6f.JPG)
_Function NeoPixel_
![Function NeoPixel](https://user-images.githubusercontent.com/24864147/96201931-28c0d280-0f5e-11eb-9b8d-514cac00129a.JPG)
_Standard UI_
![Standard UI](https://user-images.githubusercontent.com/24864147/96202119-a553b100-0f5e-11eb-976c-50c4fa4fcf45.JPG)

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

Best regards,

**Comment by sjasonsmith** [comment]
@Foxies-CSTL you will have much better success getting new board support added by opening a pull request yourself.

**Comment by thisiskeithb** [comment]
> @Foxies-CSTL you will have much better success getting new board support added by opening a pull request yourself.

That and we won't be able to merge in the unified config. You'll need to split it up and contribute them to the [Marlin Configurations repo](https://github.com/MarlinFirmware/Configurations) as individual configs for easier maintainability.

**Comment by Foxies-CSTL** [comment]
Hi, 
Thanks, I suspected that I was in the wrong section to declare this new definition of the board. I will try to do it by a PR but I have some problems in English with the syntax. 
Is there a French guy in the room? ;-) If I understand, I must make a request in the "Marlin_Configurations_repo" section for the "configurations" part and another in the Marlin_firmware section for the "pins definition" part.

Regards

**Comment by thisiskeithb** [comment]
>  If I understand, I must make a request in the "Marlin_Configurations_repo" section for the "configurations" part and another in the Marlin_firmware section for the "pins definition" part.

Correct.

**Comment by sjasonsmith** [comment]
I suggest focusing on adding the board support to the Marlin repo first. You don't need to worry about configurations until after the board is supported.

**Comment by sjasonsmith** [comment]
We definitely do **not** want configurations before the board.

**Comment by Foxies-CSTL** [comment]
Ok, thank's I will write a Pull Request for "my" board.
See you later ;-)
