### ISSUE TITLE
[BUG]Marlin 2.0.7.2 repairs for Anycubic Predator

### ISSUE THREAD

**Issue by rq3** [MarlinFirmware/Marlin#19760]
Attached are the configuration files for the Anycubic Predator, a delta printer using the Trigorilla Pro 32 bit board. These configuration files are applicable only to Marlin 2.0.7.2, as the UI changes too quickly to keep up with.

These files address the existing sample configurations that have dangerous temperature limits, do not allow the printer to calibrate, have an inverted LCD display, and incorrect touch screen calibrations.

As far as I can tell, after fairly extensive testing on the actual printer with the actual board, is that the UBL test print function is faulty. The UBL function seems to work well, but printing a verification from the UBL menu leads to outrageous and unusable stepper motion.
[2072_Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5388663/2072_Configuration.zip)

**Comment by thisiskeithb** [comment]
Please submit a PR against the `import-2.0.x` branch in the [Marlin Configurations repo](https://github.com/MarlinFirmware/Configurations) (and ensure config settings match the latest changes in the default configs).
