### ISSUE TITLE
[FR] AUTO_FAN_TEMPERATURE on USE_CONTROLLER_FAN setting

### ISSUE THREAD

**Issue by DrumClock** [MarlinFirmware/Marlin#19779]
Would it be possible to add this setting to the Controller Fan menu?

```
#define TEMP_STEPPER_PIN -1 // Set a custom pin for the Temperature Sensor
#define TEMP_SENSOR_STEPPER 11 // Temperature sensors

#define STEPPER_AUTO_FAN_TEMPERATURE 40
#define STEPPER_AUTO_FAN_SPEED 128 // 255 == full speed
```

Cooling based on the temperature from a free sensor on the board which is placed on the unit from the driver (X, Y, Z or E).

**Comment by Doyle4** [comment]
Slicer software does that.
