### ISSUE TITLE
[FR] MKS Robin Nano 1.2 + Color UI - no remaining time

### ISSUE THREAD

**Issue by bkiziuk** [MarlinFirmware/Marlin#19780]
### Description

For configuration:
```
#define MKS_ROBIN_TFT35
#define TFT_COLOR_UI
```
the option `SHOW_REMAINING_TIME` is not active due to
`#if EITHER(SDSUPPORT, LCD_SET_PROGRESS_MANUALLY) && ANY(HAS_MARLINUI_U8GLIB, HAS_MARLINUI_HD44780, IS_TFTGLCD_PANEL)` seem to return FALSE.
Therefore, the UI shows only elapsed time.

### Steps to Reproduce

1. Generate G-Code with M73 option enabled
2. Start printing
3. Observe print progress on display

**Expected behavior:** 

Display shows both Elapsed time and Remaining time.

**Actual behavior:** 

Display shows only a progress bar and elapsed time.
[bugfix_2-0-x_20201015.zip](https://github.com/MarlinFirmware/Marlin/files/5395525/bugfix_2-0-x_20201015.zip)

**Comment by rhapsodyv** [comment]
Is it a feature request or a bug? 🤔

**Comment by bkiziuk** [comment]
Taking into account that some LCD definitions have been added/changed in the recent bugfix-2.0.x and the preprocessor's directives seem to not fully follow it - I would consider it as a bug. 
But considering the fact that the Touch UI is new, maybe it just does not support it yet.

**Comment by rhapsodyv** [comment]
I did some search, and the Color Ui don't have the code to handle SHOW_REMANING_TIME. So, the checks are right: it isn't supported yet.

Please change to feature request. 

Anyway, I will try to work on that soon.

Thanks!

**Comment by dchauran** [comment]
@rhapsodyv are you still planning to work on this soon? If not, should I take a stab at it?

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/24843
