### ISSUE TITLE
[FR] ADVANCED_PAUSE_FEATURE - Remove Screen Necessity

### ISSUE THREAD

**Issue by Protean-Man** [MarlinFirmware/Marlin#19789]
1 - ADVANCED_PAUSE_FEATURE should not require LCD to compile. Removing this necessity would allow for those using Octoprint setups and other screen setups that are run through Octoprint to use this feature.

2 - FILAMENT_RUNOUT_SCRIPT requires ADVANCED_PAUSE_FEATURE. Removing the LCD necessity from ADVANCED_PAUSE_FEATURE  would allow the use of Filament Runout Sensors on Octoprint Setups.

Thanks!

**Comment by slowbro** [comment]
This was implemented in #9042, you can have `EMERGENCY_PARSER` or `ADC_BUTTONS` and use ADVANCED_PAUSE_FEATURE, so no LCD is required.
