### ISSUE TITLE
[BUG]UART not working

### ISSUE THREAD

**Issue by boromyr** [MarlinFirmware/Marlin#19794]
### Bug Description
UART seems not to work with TMC2208 / 9, M122 command always returns "BadConnection" error. I have read that many, especially for the first experiences, encounter this error. I have carried out several serial tests, all with satisfactory results, except for the M122 one, which should verify that everything has been done correctly.
### My test
  printer: LK4 pro;
  mainboard: LGT_KIT_V1.0 based on RAMPS;
  IC: atmega2560
  Marlin: 2.0.7 readjusted for my model, source [https://github.com/mrv96/Alfawise-U30-Pro-Longer-LK4-Pro-Marlin-2-Stock-Mainboard](url)
  drivers: TMC2208 / TMC2209, both with 1k internal resistance, this excludes any error related to
           self-made UART / PDN adapters, so I only use 2 simple jumper cables without any modification;
  serial type: both hardware and software
   * tested the serial connection for the 2 drives using the script [https://learn.watterott.com/silentstepstick/configurator//2009](url) and an FTDI, working;
  * tested the serial connector of the board, both software and hardware, through 2 serial monitors per board <---> FTDI, successful in both directions
  * tested several free pins, including those of Serial3 (14,15)
  * for each pair of pins I also tried the opposite combination, to avoid distraction errors RX <-> RX ...
  * touchscreen connected and disabled, check the files MarlinCore.cpp, stepper.cpp, trinamic.cpp, try different combinations of software settings
  * tried with the original copy of the firmware with the original settings of the aforementioned link, modifying only the minimum necessary, modified 2 pins and changed the Z stepper from standalone to uart
  * searched online for many other users who had my problem
  * I'm running out of other ideas ...

My settings regarding steppers
`
#define Z_SERIAL_TX_PIN 14 and others
#define Z_SERIAL_RX_PIN 15 and others
#define Z_DRIVER_TYPE TMC2209
#define SOFTWARE_DRIVER_ENABLE (defined not defined)
#define TMC_DEBUG
`
many other setting combinations possible ...
`Driver registers:
		Z	0x00:00:00:00	 Bad response!
Testing Z connection... Error: All LOW
`
Ideas?
Thank you

**Comment by ellensp** [comment]
Many have this working fine, so is not a firmware issue.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
