### ISSUE TITLE
Converting from old marlin

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#1979]
So had time to get the latest marlin installed

copy and pasting settings from the 2-3 year old copy of marlin got me going but now i'm a bit stuck

this old one:

```
#define X_MAX_LENGTH 221
#define Y_MAX_LENGTH 221
#define Z_MAX_LENGTH 390.65

// The position of the homing switches. Use MAX_LENGTH * -0.5 if the center should be 0, 0, 0
#define X_HOME_POS X_MAX_LENGTH * -0.5
#define Y_HOME_POS Y_MAX_LENGTH * -0.5
#define Z_HOME_POS Z_MAX_LENGTH
```

is no where in the new config....

should i use these?

```
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0
#define X_MAX_POS 221
#define Y_MAX_POS 221
#define Z_MAX_POS 390.65
```

and how do i set them so that center of bed is 0,0 ?

**Comment by nophead** [comment]
You make MIN_POS -110.5 and MAX_POS 110.5 to get 0 in the middle.

**Comment by boelle** [comment]
thanks....

**Comment by boelle** [comment]
mostly a note for self, but when i ran pid auto tune for the bed (not an option in old marlin) it ended up with this:

```
PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
#define  DEFAULT_Kp 176.72
#define  DEFAULT_Ki 13.59
#define  DEFAULT_Kd 574.51
```

have it not forgotten bed after the underscore ?

**Comment by boelle** [comment]
almost there.... 

i can do G28 and it homes.... but it will try and move past the endstops.... 

config as of now: http://pastebin.com/zPG4Pefw

cant figure if something should ignore the endstops

**Comment by boelle** [comment]
maybe this in Configuration_adv.h:

```
#define ENDSTOPS_ONLY_FOR_HOMING // If defined the endstops will only be used for homing
```

?

**Comment by nophead** [comment]
For Mendel90 the endstops are outside the print volume, so once homed the
soft limits should prevent them ever being hit again.

**Comment by boelle** [comment]
oh... forgot to set soft limits :-/

ie they are set to false right now...

**Comment by thinkyhead** [comment]
#1989

**Comment by boelle** [comment]
:-D the man is on fire... fast fix

**Comment by boelle** [comment]
btw.... will prob be able to test auto level to late tomorrow or weekend. only need to rebuild my extruder and do some minor mod's to my electronics

**Comment by thinkyhead** [comment]
@boelle Great. Maybe we can do some video-based leveling debugging…. :beetle:

**Comment by boelle** [comment]
yep, just need to wire up the servo and touch switch

**Comment by boelle** [comment]
home at last....

Q: are there a M119 equilant for testing the touchprobe?

i have changed the pins file for my board so it now looks like this:

http://pastebin.com/HXz4bAPy

i know i use  M280 PX SX to set the pos of the servo

2015-05-08 7:00 GMT+02:00 Scott Lahteine notifications@github.com:

**Comment by thinkyhead** [comment]
M119 might work for the probe. If not we need to add it in.

**Comment by boelle** [comment]
oki.. btw my config: http://pastebin.com/mrXadjJ1

2015-05-08 15:44 GMT+02:00 Scott Lahteine notifications@github.com:

**Comment by boelle** [comment]
first problem... servo does not move

sure its a software problem  but not sure where

2015-05-08 15:44 GMT+02:00 Scott Lahteine notifications@github.com:

**Comment by boelle** [comment]
M119 does not report status on the z probe either... only XYZ

**Comment by boelle** [comment]
hmm... doing autotune for the bed and hotend

bed was ok

but not during hotend autotune the extruder fan led flashes together with the hotend

**Comment by boelle** [comment]
M106 and M107 work fine thou... so not a wiring issue

bed cooling fan can also be controlled manual

will check if everything else works but assume so far that they do

**Comment by nophead** [comment]
Does your fan share the 12V wire with the heater, as per Mendel90? If so
maybe the heater is wired with the wrong polarity, in which case turning it
on will turn the fan off.

**Comment by boelle** [comment]
Yes, i have chekced it thou and work fine when i turn things on and off in pronterface.

will check again thou

**Comment by boelle** [comment]
doooh.... yes wired in wrong :-( _slap in face_

**Comment by boelle** [comment]
nope it was right... me not reading schematics right

**Comment by boelle** [comment]
_slap in face_ turned out check i double checked it was wired in wrong

still wondering why the servo will not move

**Comment by fmalpartida** [comment]
I'll try our tonight the new de branch during the hangout. On Thursday the
M851 command was broken.

**Comment by boelle** [comment]
well i have just downloaded the lastest copy but have no clue why the servo is not moving

**Comment by boelle** [comment]
fresh copy on my config: http://pastebin.com/9hXCtrku
pins file: http://pastebin.com/2BYjaQj8

**Comment by boelle** [comment]
as promissed an update.... 

i updated to latest IDE and figured how to get the old MCU/AVR in there... then did a compile
then i found out that in fact i only needed to add the bootloader file as the fuse settings turned out to be the same. it took at lot of compare using an online fuse calculator. first entering everything for the old MCU... then selecting the new one and efter the same settings... what a relief.

then i only had to edit my pins file (pins_ omca .h something) so that it would not say upps if i picked the new MCU or the old one...

now i only have to replace the chip itself and burn bootloader etc

**Comment by thinkyhead** [comment]
Good news! I haven't gone anywhere near the bootloader stuff (yet) so I still find it quite mysterious.

**Comment by boelle** [comment]
now bad news:

avrdude: verification error, first mismatch at byte 0x1f000
         0xff != 0x0c
Error while burning bootloader.
avrdude: verification error; content mismatch

**Comment by boelle** [comment]
scratch it... i went back to ide 1.0.6

at least i can burn bootloader for the 644 there and upload a sketch...
