### ISSUE TITLE
[BUG] TMC Connection Error using original TMC library

### ISSUE THREAD

**Issue by laurienzu** [MarlinFirmware/Marlin#19802]
### Bug Description

If I enable hardware UART on my MKS Robin Nano V1.2 I have TMC Connection error but when I switch to https://github.com/bigtreetech/TMCStepper/ it works perfectly without errors.

### My Configurations

https://github.com/Loreagle/Marlin/tree/Sapphire-Pro

### Steps to Reproduce

1. Compile Marlin with original TMC libraries and hardware UART enabled
2. Flash firmware 

**Expected behavior:** 

Drivers works correctly

**Actual behavior:** 

TMC connection error is displayed

#### Additional Information

When I switch to https://github.com/bigtreetech/TMCStepper/ it works perfectly without errors and also M122 shows everything okay.

**Comment by sjasonsmith** [comment]
Can you enable TMC_DEBUG and post your M122 output using the default library?

**Comment by thisiskeithb** [comment]
> https://github.com/Loreagle/Marlin/tree/Sapphire-Pro

Do you have a different link for your config? The linked config appears to be a default with nothing specific to the Robin Nano 1.2 motherboard or TMC drivers.

**Comment by sjasonsmith** [comment]
@Loreagle it would be best to zip up your configs and attach them. You should include the two config headers and anything else you've modified, such as platformio.ini and your pins file.

**Comment by ellensp** [comment]
Full logs of compile might also help, would identify all versions of frameworks and libraries

**Comment by laurienzu** [comment]
> Can you enable TMC_DEBUG and post your M122 output using the default library?

Sure, here you can see 3 different M122 outputs, as you can see I have bad response and connections errors randomly:
![image](https://user-images.githubusercontent.com/10505115/96418332-e7952080-11f2-11eb-90cc-1ef9249be3ee.png)
![image](https://user-images.githubusercontent.com/10505115/96418363-f4197900-11f2-11eb-8a48-1572a0ebd487.png)
![image](https://user-images.githubusercontent.com/10505115/96418391-faa7f080-11f2-11eb-953e-869ec0d6e4c3.png)


> > https://github.com/Loreagle/Marlin/tree/Sapphire-Pro
> 
> Do you have a different link for your config? The linked config appears to be a default with nothing specific to the Robin Nano 1.2 motherboard or TMC drivers.

I'm sorry I forgot to commit, now is updated!

> @Loreagle it would be best to zip up your configs and attach them. You should include the two config headers and anything else you've modified, such as platformio.ini and your pins file.

Sure! [Configs.zip](https://github.com/MarlinFirmware/Marlin/files/5400147/Configs.zip)

> Full logs of compile might also help, would identify all versions of frameworks and libraries

[Compile log.txt](https://github.com/MarlinFirmware/Marlin/files/5400164/Compile.log.txt)

As I said simply switching library with TMCStepper=https://github.com/bigtreetech/TMCStepper/ fix the UART connection problem and I have no errors, the other problem I have is an annoying coil whine when motors are in StealtChop mode only

**Comment by laurienzu** [comment]
SOLVED!

I solved adding this line:

  // Reduce baud rate to improve software serial reliability
    #define TMC_BAUD_RATE 19200

It was only for software UART but apparently it fixes also hardware... I don't know why with BigTreeTech library it was working, maybe this line was inside the library?

**Comment by sjasonsmith** [comment]
Something is really wrong if you need that for HardwareSerial. I’ve run HardwareSerial with TMC drivers at 500 kbaud.

**Comment by sjasonsmith** [comment]
I just looked at your pins file and you are absolutely not using HardwareSerial. If you are defining pins and not port names you are using SoftwareSerial.

**Comment by laurienzu** [comment]
> I just looked at your pins file and you are absolutely not using HardwareSerial. If you are defining pins and not port names you are using SoftwareSerial.

Ok now I understand! To use hardware UART I should connect the cable to PA9 because is the TX pin of the serial line of the board (like the attached photo) right? 

So I'm using software UART since I connected all my drivers to PA3... is it okay like this if I use serial UART with just one pin for all drivers RXs and TXs and with addresses settled with jumpers?

![TMC2209HWSERIAL](https://user-images.githubusercontent.com/10505115/96627501-3e911780-1311-11eb-92cf-79339a9f4bb5.jpg)
