### ISSUE TITLE
[BUG] Current BugFix won't build --- Errors about manual_feedrate_mm_s being undeclared.

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#19805]
### Bug Description

Using PlatformIO and the current BugFix...   My IDEX configuration causes PlatformIO to die.   Here are the error messages:

Compiling .pio\build\mega2560\src\src\lcd\menu\menu_custom.cpp.o
Compiling .pio\build\mega2560\src\src\lcd\menu\menu_game.cpp.o
Marlin\src\lcd\marlinui.cpp: In static member function 'static void ManualMove::task()':
Marlin\src\lcd\marlinui.cpp:698:62: error: 'manual_feedrate_mm_s' was not declared in this scope
       const feedRate_t fr_mm_s = (uint8_t(axis) <= E_AXIS) ? manual_feedrate_mm_s[axis] : XY_PROBE_FEEDRATE_MM_S;
                                                              ^
At global scope:
Compiling .pio\build\mega2560\src\src\lcd\menu\menu_led.cpp.o
cc1plus.exe: warning: unrecognized command line option '-Wno-register'
Compiling .pio\build\mega2560\src\src\lcd\menu\menu_main.cpp.o
*** [.pio\build\mega2560\src\src\lcd\marlinui.cpp.o] Error 1
=========================================================== [FAILED] Took 35.71 seconds ===========================================================

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:35.710

### My Configurations

Configuration.h files along with custom boot screen and status screen included.
[Marlin_Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5398218/Marlin_Configuration.zip)

### Steps to Reproduce

Just place the Configuration files in the right place and build it.

**Comment by ellensp** [comment]
Your Configuration_adv.h does not conform to current marlin versions.

Line 1050 `#if EITHER(ULTIPANEL, EXTENSIBLE_UI)` should be `#if EITHER(IS_ULTIPANEL, EXTENSIBLE_UI)`
Line 1053 `#if ENABLED(ULTIPANEL)` should be `#if IS_ULTIPANEL`
