### ISSUE TITLE
[BUG] StealthChop / SpreadCycle inverted with hardwired SPREAD pin

### ISSUE THREAD

**Issue by laurienzu** [MarlinFirmware/Marlin#19824]
I have the problem that from printer display when I enable StealthChop actually is the opposite like you can see in this video: https://youtu.be/XtCDxxT0iKw

My config: https://github.com/Loreagle/Marlin/tree/Sapphire-Pro

Also from terminal the behaviour is inverted, as you can see if I send M569 S0 X Y Z E I have StealthChop enabled instead of disabled...
![image](https://user-images.githubusercontent.com/10505115/96631597-cf1e2680-1316-11eb-92cf-204a5992c4aa.png)

Here the registers
![image](https://user-images.githubusercontent.com/10505115/96631707-f37a0300-1316-11eb-902d-f7fc486484eb.png)

I'm using an MKS Robin Nano with MKS35 LCD and TMC2209 from Eryone connected in software UART mode.

**Comment by thinkyhead** [comment]
I've just tested `M569` on an EZBoard and there the command produces the expected result.

Is there something special about these Eryone brand stepper drivers that makes them different from the standard?

**Comment by teemuatlut** [comment]
![image](https://user-images.githubusercontent.com/7762686/96632903-14475600-1321-11eb-959b-0afca6be662b.png)

**Comment by laurienzu** [comment]
So it could be that I have high level on the SPREAD pin on my Robin Nano?

As @teemuatlut posted and said on Discord, 2209 have opposite logic compared to 2130.

**Comment by Loreagle** [comment]
> So it could be that I have high level on the SPREAD pin on my Robin Nano?

As @teemuatlut posted 2209 having opposite logic compared to 2130.

**Comment by thinkyhead** [comment]
> 2209 having opposite logic compared to 2130

Possibly, since the board I tested also has TMC2209 in UART mode and it worked correctly.

> ![image](https://user-images.githubusercontent.com/7762686/96632903-14475600-1321-11eb-959b-0afca6be662b.png)

Ok… so:
- Should we be reading the "`SPREAD`" pin state before setting or interpreting the meaning of the spreadCycle / stealthChop bit (2) shown in this image and inverting the value sent to `M569 S<state>` when `SPREAD` is `HIGH`?

Or, is everything working "correctly" but we are not making it clear that `M569 S<state>` can sometimes have the opposite meaning depending on other user-configurable or hardware-configurable settings?

**Comment by teemuatlut** [comment]
The easiest solution is to have the user *not* pull the pin high, but that leaves it open for some vendor to be clever and deviate from current convention.
So basically everything is working as designed but the design doesn't taken into account that you can invert the logic with a hardware modification.

If you want to go the way of adding a query for XORing the logic, it might be enough to update just the `refresh_stepping_mode` and `get_stealthChop_status` methods. `M122` too for extra bonus points.

**Comment by laurienzu** [comment]
> The easiest solution is to have the user _not_ pull the pin high, but that leaves it open for some vendor to be clever and deviate from current convention.
> So basically everything is working as designed but the design doesn't taken into account that you can invert the logic with a hardware modification.
> 
> If you want to go the way of adding a query for XORing the logic, it might be enough to update just the `refresh_stepping_mode` and `get_stealthChop_status` methods. `M122` too for extra bonus points.

I didn't pull the pin high, if it's high is a board config. 

So at the moment if I enable   //#define HYBRID_THRESHOLD I have the opposite situation?

**Comment by teemuatlut** [comment]
StealthChop will always work in a lower speed range compared to spreadCycle. It's not possible to switch their order.

**Comment by laurienzu** [comment]
> StealthChop will always work in a lower speed range compared to spreadCycle. It's not possible to switch their order.

I was thinking that since I have modes inverted maybe that will invert too...

**Comment by thinkyhead** [comment]
The main thing here is we want the interface to reflect the real situation of the stealthChop versus spreadCycle state. So, if it's a hardware change that we cannot detect, then it makes sense to add a configuration option to tell Marlin that this modification has been made, and then Marlin can handle setting / displaying the state correctly.

So with the hardware modified, when we send a "1" to change the state, it seems that now it will read back as a "0" and if we send a "0" it will read back as a "1." So, we should only change how we display the value, not how we interpret the `S` parameter.

So, add this to config…
```cpp
#define TMC_HARDWIRED_SPREAD
```
…and make this change to the `M569` report…?
```cpp
template<typename TMC>
void tmc_say_stealth_status(TMC &st) {
  st.printLabel();
  SERIAL_ECHOPGM(" driver mode:\t");
  serialprintPGM(st.get_stealthChop_status() ^ ENABLED(TMC_HARDWIRED_SPREAD) ? PSTR("stealthChop") : PSTR("spreadCycle"));
  SERIAL_EOL();
}
```

**Comment by thinkyhead** [comment]
I've posted the PR #19827 in an attempt to address this kind of hardware configuration. Please have a look and see what you think.

**Comment by thinkyhead** [comment]
After getting some feedback from Teemu et. al., the PR has been modified to check the `spread_en()` state and return the stealthChop state inverted if the state is HIGH. Please test to see that it produces the correct results on your setup from the LCD and from G-code commands.

**Comment by laurienzu** [comment]
> After getting some feedback from Teemu et. al., the PR has been modified to check the `spread_en()` state and return the stealthChop state inverted if the state is HIGH. Please test to see that it produces the correct results on your setup from the LCD and from G-code commands.

I can confirm that setting StealthChop from the printer display works well and is fixed, the problem is that now on M569 the value is inverted as you can see here:

![image](https://user-images.githubusercontent.com/10505115/96798797-edad1c00-1401-11eb-8160-5cd0bbb2697c.png)

**Comment by thinkyhead** [comment]
I checked the code and saw that `M569` wasn't yet accounting for `spread_en` when _setting_ the state, although it seems correct in _reading_ the state. So, I updated that PR and now possibly `M569` is behaving better…?

**Comment by Loreagle** [comment]
The M569 behavior is now okay but the display on the printer say the opposite thing again :/

![image](https://user-images.githubusercontent.com/10505115/96901812-05cd7b80-1494-11eb-9562-2fcd1f52e74c.png)

**Comment by laurienzu** [comment]
> I checked the code and saw that `M569` wasn't yet accounting for `spread_en` when _setting_ the state, although it seems correct in _reading_ the state. So, I updated that PR and now possibly `M569` is behaving better…?

I tested and M569 is still working at the opposite as you can see in my screenshot. The registers seems to be settled correctly after commands S1 and S0 but @teemuatlut can confirm better than me.

The display of the printer works well btw, displaying the real status :)

![image](https://user-images.githubusercontent.com/10505115/96934477-886d2f80-14c2-11eb-9d3f-b0540803f322.png)

**Comment by thinkyhead** [comment]
What is the output of `M122` with no `V` parameter? I see that for TMC220x there is a `st.stealth()` method, and this is the function called by the `M122` report for the "stealthChop" reading on those drivers.

I want to contrast the value that comes back from `stealth()` (`GET_REG(TMC2208_n, stealth)`) with the reading from `get_stealthChop_status`. It seems like we should just be calling the `stealth()` accessor in `TMCStepper<TMC2208>`, but this is what has evolved…
```cpp
inline bool get_stealthChop_status() {
  return !(this->en_spreadCycle() ^ this->spread_en());
}
```

I'm going to make a couple more tweaks to the PR, such as adding `spread_en` to the `M122` report, and then from this last round of debug hopefully we'll sort out the most proper way to access and interpret this status.

**Comment by thinkyhead** [comment]
I've inverted the method so it's better for EEPROM storage. The internal storage of "stealth" will now always be 1 when "stealth" is the wanted effect. But the state will be inverted when setting or reading the driver bit directly if `spread_en` is high.

**Comment by laurienzu** [comment]
> What is the output of `M122` with no `V` parameter? I see that for TMC220x there is a `st.stealth()` method, and this is the function called by the `M122` report for the "stealthChop" reading on those drivers.
> 
> I want to contrast the value that comes back from `stealth()` (`GET_REG(TMC2208_n, stealth)`) with the reading from `get_stealthChop_status`. It seems like we should just be calling the `stealth()` accessor in `TMCStepper<TMC2208>`, but this is what has evolved…
> 
> ```c++
> inline bool get_stealthChop_status() {
>   return !(this->en_spreadCycle() ^ this->spread_en());
> }
> ```
> 
> I'm going to make a couple more tweaks to the PR, such as adding `spread_en` to the `M122` report, and then from this last round of debug hopefully we'll sort out the most proper way to access and interpret this status.

I'm sorry but I'm not really good into coding so I can't fully follow you  :(

Btw this is the M122 output with the same firmware and settings as my latest screenshots:

![image](https://user-images.githubusercontent.com/10505115/96992629-745d1880-152a-11eb-99a2-482c1c3d49d6.png)
![image](https://user-images.githubusercontent.com/10505115/96992654-7aeb9000-152a-11eb-96a0-4fa972ebff63.png)

Now I updated with your last commit and M569 is still broken... it shows the opposite status.

![image](https://user-images.githubusercontent.com/10505115/96993464-a458eb80-152b-11eb-9beb-079778d161a2.png)

**Comment by teemuatlut** [comment]
`.stealth()` is for reading the *current* status of the chopper method and so is affected by hybrid threshold. You cannot use this method for this purpose.

**Comment by thinkyhead** [comment]
Thanks! I figured that was the distinction.

**Comment by thinkyhead** [comment]
> Now I updated with your last commit and M569 is still broken... it shows the opposite status.

I added a `spread_en` element to the `M122` report but it only shows up without the `V` parameter. On your setup it should always show up as `true`.

So it's interesting that you're seeing the opposite status now. The code was according to my best understanding of the situation yesterday. So, maybe the inversion of the bit is only when it is written…?

Since there are only a couple of possibilities… and the current one is wrong…
```cpp
inline bool get_stealthChop()        { return !(this->en_spreadCycle() ^ this->spread_en()); }  // If SPREAD_EN is HIGH the mode is reversed
inline bool get_stored_stealthChop() { return this->stored.stealthChop_enabled; }
inline void refresh_stepping_mode()  { this->en_spreadCycle((!this->stored.stealthChop_enabled) ^ this->spread_en()); }
```
…then the only other reasonable possibility must be right… right?

If the `spread_en` status only inverts the _outcome_ on write but not the _meaning_ on read, the code should be this instead:
```cpp
inline bool get_stealthChop()        { return !this->en_spreadCycle(); }
inline bool get_stored_stealthChop() { return this->stored.stealthChop_enabled; }
inline void refresh_stepping_mode()  { this->en_spreadCycle((!this->stored.stealthChop_enabled) ^ this->spread_en()); } // If SPREAD_EN is HIGH the outcome is reversed
```

I suspect that is the case, but I will actually check the datasheet if I must! Anyway, I'll push an update with the latter block of code and hopefully both the G-code and the LCD will then behave properly! If the `M122` (no `V`) report shows all the `spread_en` as `true` that will be good.

**Comment by teemuatlut** [comment]
After writing to a register, a read from the same should result in the same exact value.

Btw, this PR may need to also address the other use cases of `en_spreadCycle` in `tmc_util.cpp: tmc_enable_stallguard` and `trinamic.cpp`. I think my initial suggestion of overloading the method might've inadvertently taken this into account.

**Comment by thinkyhead** [comment]
> After writing to a register, a read from the same should result in the same exact value.

You would think so. But the initial report based on our old code is clearly writing a "1" expecting this to enable spreadCycle mode, but instead it is having the opposite effect.

Hopefully someone familiar with the technical details can jump in with the exact code and simply post the correction, as I am of course chasing several issues today and don't have time for too much back-and-forth to work it out in the abstract.

**Comment by laurienzu** [comment]
I'm not very good at using github and I made a lot of confusion, I don't understand how can I revert back to before all this changes, can you please point me in the right direction?  I just want to go back and sync again with bugfix.

I'm using Github desktop and as you can see here I made a lot of confusion :( https://github.com/Loreagle/Marlin/commits/Sapphire-Pro

**Comment by thinkyhead** [comment]
> I'm not very good at using github…

To get your working copy and fork's branch `bugfix-2.0.x` into sync use the Git console with these commands:
```
git fetch upstream
git fetch origin
git checkout bugfix-2.0.x
git reset --hard upstream/bugfix-2.0.x
git push -f origin
```

And before making changes that you might want to submit, always create a new branch as a copy of `upstream/bugfix-2.0.x` so you don't trounce your `bugfix-2.0.x` branch:
```
git fetch upstream
git checkout upstream/bugfix-2.0.x -b my_work_branch
```

**Comment by thinkyhead** [comment]
Another good idea to keep in proper sync is to set the the upstream repo of your `bugfix-2.0.x` branch to "`upstream`":
```
git checkout bugfix-2.0.x
git branch --unset-upstream
git branch --set-upstream-to upstream/bugfix-2.0.x
```
Then GitHub Desktop will automatically offer you the latest changes when you select the branch.

**Comment by laurienzu** [comment]
I'm more confused than before because I don't know the commands meaning, btw thank you a lot for the explanation. I'm using GithHub app and I work using the app features, never with command prompt...
The problem is that I have my "Sapphire Pro" branch (where I made all the changes in configs etc.) that is messed up now as you can see in this photo: 
![image](https://user-images.githubusercontent.com/10505115/97105246-b5cffe00-16b9-11eb-80cc-452c2219f9fc.png)

The question is if I can go back to a specific date (before some changes) with a specific command.

I suppose the best thing to do is to create a new branch of bugfix 2.0.x and copy my config files, easier for me 😅

**Comment by thinkyhead** [comment]
Git has lots of powers, but this isn't the appropriate place to request a Git tutorial. There are zillions of videos and articles here on GitHub and elsewhere that can help you to master Git within a few hours.

**Comment by sjasonsmith** [comment]
To resolve this issue we will need someone to volunteer to help test the changes in PR #19827. This might require having to mock up some hardware to test it with, which can pull the spread pin in different directions. I don't know if any readily available boards expose that as a jumper.

**Comment by laurienzu** [comment]
@teemuatlut @sjasonsmith @thinkyhead 
Sorry guys, just an update on this, I'm sorry but.... After a long time I discovered my problem and it was not a firmware problem!!!

Thanks to some guys on Klipper discord I found that my problem was related to my board (MKS Robin Nano) and a mistake commonly made on wired UART drivers.

As you can see from this scheme my board has RST and SLT pins shorted:

![image](https://user-images.githubusercontent.com/10505115/109624481-8e44e280-7b3e-11eb-89bc-1df48e51b0d1.png)

When I connected my Eryone drivers PDN and SPR were so shorted, see this photo:

![image](https://user-images.githubusercontent.com/10505115/109624512-9735b400-7b3e-11eb-9bb1-fba06b28e8b6.png)

Since I followed this scheme for wired UART, my UART cable was going to PDN pin and then the board routed it also to SPREAD pin causing the noise (an high level corresponds to spreadcycle active). So I just removed the UART connection from PDN and everything works perfectly!!!

![image](https://user-images.githubusercontent.com/10505115/109625003-1925dd00-7b3f-11eb-992f-89f11cd87814.png)

I hope the changes in marlin about this can be reverted (if made) and I confirm you can close this issue.

Sorry again if this issue caused troubles :(
