### ISSUE TITLE
[BUG] Marlin loses control of hotend during long print

### ISSUE THREAD

**Issue by rq3** [MarlinFirmware/Marlin#19826]
During a 7 hour print under 2.0.7.2, the printer consistently loses PID control of the hotend temperature at hour 5. This was repeatable over 3 prints. At the fifth hour (300 minutes, irrespective of layer or other factors), the hotend temperature enters a slow yet increasing oscillation mode until the printer freezes with an E1 temperature error (hotend temperature in excess of 10C above or below set point).

Please don't tell me to do a PID check, or verify that the sensor is OK. Been there. Done that. Modifying configuration_adv.h to allow this is also unacceptable, as a 20 degree swing in nozzle temperature is not OK during any print.

Anycubic Predator with Trigorilla Pro board.

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by SJ-Innovation** [comment]
Does this occur when not printing? As in, (youll want to take out the filament so it doesnt burn in) leave the hotend on for 5 hours without printing.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by boelle** [comment]
will temp close this one until configs are provided

**Comment by thisiskeithb** [comment]
@rq3 Please continue troubleshooting here instead of creating multiple issues for the same thing.

Also: Please do as everyone asked multiple times and attach your config files.

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by thinkyhead** [comment]
I don't think this is a bug in Marlin. Something that occurs like this, after 5 hours of printing, sounds very much like some kind of failing electronic component. PID loops are clever, but they aren't complicated, and they don't just fall apart after a 5 hour period of stability. Seek help in the various forums until it is clear from thorough isolation testing that a bug in Marlin is the only possible cause.
