### ISSUE TITLE
[BUG] "Manual Probe" in "Dual X Carriage" Mode only XYZ Homing , cant 9 points probe.

### ISSUE THREAD

**Issue by xsuper9988** [MarlinFirmware/Marlin#19833]
My Ver is 2.0.7.1

 "Manual Probe" in "Dual X Carriage" Mode

When run "Level Bed"

Its return Main Page after Homing finsh

Cant run 9 points probe.

My Configuration Link
https://github.com/xsuper9988/marlin-Configuration

**Comment by boelle** [comment]
is #19835 the same problem as this one?

**Comment by xsuper9988** [comment]
> #19835

Maybe some motion move bug at homing finish

and the bug likes #19835 

But when i did not use "Dual X Carriage" and "Z Safe Homing"

"Manual Probe" function is OK

**Comment by xsuper9988** [comment]
Maybe some motion move function bugs at homing finish

and the bug likes #19835 

But when i did not use "Dual X Carriage" and "Z Safe Homing"

"Manual Probe" function is OK

**Comment by sjasonsmith** [comment]
How does bed leveling work with an IDEX printer? You have two carriages on a single Z axis. It will be impossible to compensate for both at the same time.

@InsanityAutomation what are your thoughts on this?
