### ISSUE TITLE
[BUG] example configuration file for FLSUN Q5

### ISSUE THREAD

**Issue by olinek2** [MarlinFirmware/Marlin#19832]
Hi, In Configurations-release-2.0.7.2\config\examples\delta\FLSUN\Q5-nano_v1\Configuration.h file there is a bug in Lines 499, 500, 501.
Actual version:
```
 #else
    // flsun Q5 via M303 C8 E-1 S60
    #define DEFAULT_bedKp 80.77
    #define DEFAULT_bedKi 15.74
    #define DEFAULT_bedKd 276.27
  #endif
```

It should be:
```
  #else
    // flsun Q5 via M303 C8 E-1 S60
    #define DEFAULT_Kp 80.77
    #define DEFAULT_Ki 15.74
    #define DEFAULT_Kd 276.27
  #endif
```
Best regards,
Olek

**Comment by alexeyzel** [comment]
I think values should be like this:
```
    #define DEFAULT_Kp 12.88
    #define DEFAULT_Ki 0.72
    #define DEFAULT_Kd 57.54
```

**Comment by olinek2** [comment]
I've tested 
    #define DEFAULT_Kp 10.39
    #define DEFAULT_Ki 0.55
    #define DEFAULT_Kd 48.7

but it was to slow. Nevertheless the problem was not i the value, but in wrong defines, which led to bug in compilation.

**Comment by ellensp** [comment]
This was fixed 15 days ago... https://github.com/MarlinFirmware/Configurations/issues/251

**Comment by ellensp** [comment]
ok was meant to have been fixed...  something is wrong here...  is not in import branch,,

**Comment by ellensp** [comment]
Now its been fixed.
