### ISSUE TITLE
[BUG] new CREALITY_TOUCH not deploying 

### ISSUE THREAD

**Issue by gbkwiatt** [MarlinFirmware/Marlin#19845]
### Bug Description

I have BLTouch from creality, and noticed new option for it CREALITY_TOUCH instead of usual BLTOUCH
However, when I go to configuration and BLTouch - deplying does not work (also when homing it's not deploying either)
Self test works 
My BLTouch is on pin 17

 

### My Configurations
ENDER 3 v427 with BLtouch connected to BLtouch connector on pin 17
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5421672/Marlin.zip)

Here is my configuration, on that file it's actually set to BLTOUCH instead of CREALITY_TOUCH but rest was the same for the test

### Steps to Reproduce

1. Enable CREALITY_TOUCH instead BLTOUCH
2. Go to LCD configuration screen -> BLtouch and press deploy

**Expected behavior:** it should deploy bltouch

**Actual behavior:** it doesn't deploy bltouch

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by xsuper9988** [comment]
is #19833 the same problem as this one?

**Comment by gbkwiatt** [comment]
No, not at all, mine is not even deploying for homing or leveling

**Comment by qwewer0** [comment]
BLTouch from Creality is still BLtouch, and not a CREALITY_TOUCH, that is for Creality CR-6 SE

**Comment by gbkwiatt** [comment]
There you go,  thanks

**Comment by Sebazzz** [comment]
@qwewer0 So the CREALITY_TOUCH is actually the strain gauge?

**Comment by qwewer0** [comment]
<s>@Sebazzz As far as I know, yes.</s>

**Comment by Sebazzz** [comment]
> 
> 
> @Sebazzz As far as I know, yes.

Appears not to be though. CREALITY_TOUCH is checked, then defines BLTOUCH.

**Comment by thinkyhead** [comment]
That option is for some probe that Creality used in developing Ender 3 V2 but it is not yet a real product.
