### ISSUE TITLE
If the printer is idle for to long moves commands seem to be doubled in size. 

### ISSUE THREAD

**Issue by housewright30** [MarlinFirmware/Marlin#19840]
I have a issue that I would like to post here before I post in it asking if it's a bug. 

If the printer is idle for a long time or the borad just has not been reset/used in a few hours the next set of commands sent to the printer seem to be doubled. So If I ask X to move 12mm it will move 24 or around that. 

It really bothersome when you go to start a pring and X and Y hit there end stops just fine but than when it goes to probe for z it just zips past the center of the bed and bashes into the other corner of the printer. I had to pause the print for a day while I ordered more filiment and when I started it back up it was making much larger moves than it should have been. 

Has anyone ran into something like this before? 

Big Tree Tech GTR with TMC2209
[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/5352964/Configuration.zip)

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
