### ISSUE TITLE
[BUG] Dual Z motor setup, second motor rotates twice as much

### ISSUE THREAD

**Issue by mwhite7** [MarlinFirmware/Marlin#19848]
### Bug Description

When configured with 5x TMC2209 drivers, a BTT SKR 1.4 Turbo and the Z motors plugged into ZA and E1, the motor plugged into E1 seems to rotate twice as much as the other. Everything else works as expected; have tried every fix I could find posted to the internet but something tells me this situation is different and the bug lies within the E1 driven stepper rotating twice as much/fast. The problem persists when motors are swapped (E1 driven still x2 rotation). Motors work correctly when both are driven by the Z stepper (ports ZA & ZB), but I was really hoping to use the z auto-align feature (and now I'm stubborn that it should work the way I want it to since I've spent so much time on this).

Physically, everything is set up correctly according to every guide posted and the board pinout. Seeing how so many have had this exact setup go off without a hitch makes me think there is a bug in the branch of marlin I am using (020008)

### My Configurations

config files here (also attached to this post): [https://github.com/mwhite7/MW-Marlin]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5425093/Marlin.zip)

Please also let me know if there are any other files needed to diagnose the issue. Please also let me know if pasting M122 results are of any help.

### Steps to Reproduce
BTT SKR 1.4 Turbo w/5x TMC2209 stepper drivers on a Creality Ender 5 Plus (all wired correctly & quadruple checked)
1. Configure and flash marlin for multiple z axes
2. plug second z motor into E1 port on mainboard (as is expected by marlin)
3. test z axis and notice that the motor plugged into E1 rotates ~twice as much
4. check e-steps, steps/mm

**Expected behavior:** normal printing operation, z motors move in unison at prescribed steps

**Actual behavior:** motor plugged into E1 rotates ~twice as much in the same amount of time, suggesting it is receiving double the pulses it should be.

#### Additional Information

Creality Ender 5 Plus
SKR 1.4 Turbo w/5x TMC2209
BTT TFT35 v3.0 display
Microswiss direct drive hotend

**Comment by ellensp** [comment]
"  #if  1 // AXIS_IS_TMC(Z2)       //MW - VS code doesn't seem to detect this as a true statement so it is forced true"
For a brief period of about 12 hours 4 days ago there was a bug in bugfix that caused this.

This would cause the micro stepping on Z2 to be incorrect.

Get latest bugfix.

details: 
bug added here: https://github.com/MarlinFirmware/Marlin/pull/19798
fixed here:  https://github.com/MarlinFirmware/Marlin/pull/19820
