### ISSUE TITLE
[BUG] Configuration files for BQ Hephestos 2

### ISSUE THREAD

**Issue by bergerac856** [MarlinFirmware/Marlin#19846]
Issue: 
With the proposed configuration files for Hephestos 2, and at least after commit ea80b2c8fc4209160eed377437610c298312e97f, steppers motors are not working as expected. 
On my BQ_ZUM_MEGA_3D, it seems that stepper drivers are DRV8825. 

Solution: 
X,Y,Z and E0 have to be adapted accordingly around lines 695... in configuration.h.

**Comment by boelle** [comment]
if you know what needs to be changed the fastest way is to submit a PR with the changes

**Comment by bergerac856** [comment]
Done
