### ISSUE TITLE
REPRAP DISCOUNT SMART CONTROLLER Displaying 20x2 not 20x4

### ISSUE THREAD

**Issue by geekyboi** [MarlinFirmware/Marlin#19862]
### Bug Description

Have just upgraded to a BTT SKR 1.4 Turbo and plugged in my REPRAP DISCOUNT SMART CONTROLLER. It it only display information on the top 2 rows.

Have plugged the LCD back in to the old motherboard to check the LCD isn't broken and it still works fine.

It looks like it thinks the LCD is a 20x2 not a 20x4.

I'm running the latest bug fix version of Marlin 2.0

### My Configurations

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/5428606/Archive.zip)

#### Additional Information

![IMG_3462](https://user-images.githubusercontent.com/30156406/96988916-e0388480-151c-11eb-91f3-4128e6e73d16.jpg)

**Comment by geekyboi** [comment]
Have fixed the issue

Added LCD_HEIGHT and LCD_WIDTH to conditionals_LCD.h 

```
#elif ENABLED(REPRAP_DISCOUNT_SMART_CONTROLLER)

  // RepRapDiscount LCD or Graphical LCD with rotary click encoder
  #define LCD_HEIGHT 4
  #define LCD_WIDTH  20
  #define IS_RRD_SC  1

#endif
```

[Conditionals_LCD.h.zip](https://github.com/MarlinFirmware/Marlin/files/5429027/Conditionals_LCD.h.zip)

**Comment by ellensp** [comment]
Are you going to create a PR?

**Comment by geekyboi** [comment]
PR created 

#19864

**Comment by thisiskeithb** [comment]
Can you try with the latest `bugfix-2.0.x`? Your configs are missing several of the latest updates.

I flashed my SKR 1.4, 1.3, and BTT002 builds with a `REPRAP_DISCOUNT_SMART_CONTROLLER` using the latest `bugfix-2.0.x` and they work fine without the fix you posted above.

**Comment by geekyboi** [comment]
Have just downloaded the latest build and flashed and is now working. Very weird.

**Comment by sjasonsmith** [comment]
I probably patched this a week or so ago. I happened upon a warning related to it, but you would only noticed if you enabled the Prusa display style.
