### ISSUE TITLE
[FR] Slim MarlinUI

### ISSUE THREAD

**Issue by ETE-Design** [MarlinFirmware/Marlin#19863]
For people with older mainboards It's not possible to use MarlinUI for TFT cause the low memory on the boards.
So mabye a Slim MarlinUI like the Slim Menu LCD could be the way to go to offer MarlinUI to even more mainboards.

**Comment by thisiskeithb** [comment]
The quickest way to a smaller build in the meantime is to disable features you don't need. Searching the config files for `PROGMEM` will point you to some heavier items that can help shrink a build down.

**Comment by ETE-Design** [comment]
@thisiskeithb How much does the MarlinUI require of PROGMEM compared to Slim LCD Menu?

**Comment by thisiskeithb** [comment]
> @thisiskeithb How much does the MarlinUI require of PROGMEM compared to Slim LCD Menu?

Both are still Marlin UI, but `SLIM_LCD_MENUS` just leaves out extraneous menus. You'll have to compile your specific build and test the difference with your required options enabled.

**Comment by ETE-Design** [comment]
@thisiskeithb  Sorry, forgot to mention that it is the MarlinUI for TFT I was talking about.

**Comment by thisiskeithb** [comment]
> Sorry, forgot to mention that it is the MarlinUI for TFT I was talking about.

There are three:

https://github.com/MarlinFirmware/Marlin/blob/9630c2683c39468bf885c560a1768d8b377d9462/Marlin/Configuration.h#L2300-L2302

`TFT_CLASSIC_UI` just emulates the standard Marlin UI.

I think what you're after is shrinking down all the TFT code down to a smaller size, not the `TFT_CLASSIC_UI`. The TFT code is really meant for a 256k chip at the very least.

**Comment by ETE-Design** [comment]
@thisiskeithb So the TFT_Classic_UI can also emulator Slim LCD Menu? But yes in general I was thinking about cutting the TFT Code down to as small as possible, like you slim total side down in LCD when you choose Slim LCD Menu...

**Comment by thisiskeithb** [comment]
I haven't tried `TFT_CLASSIC_UI` and `SLIM_LCD_MENUS`, so I can't speak to the final size/if those are compatible, but I don't see why they wouldn't be.

The TFT UI code will already be small because it won't compile all three options.

**Comment by thisiskeithb** [comment]
Closing because it’s not possible to create a “slim” version of any of the TFT UIs.

They may be optimized and shrink the overall build size down the road, but they aren’t meant for small MCUs.
