### ISSUE TITLE
pins_CHITU3D_V5.h and pins_CHITU3D_V6.h have FAN_PIN_2 

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#19873]
### Bug Description

Noticed that pins_CHITU3D_V5.h and pins_CHITU3D_V6.h have FAN_PIN_2 defined.
But marlin doesn't use a naming convention of FAN_PIN_{n}
Marlin uses FAN{n}_PIN 

### My Configurations

In this rare case configs are not needed. 

### Steps to Reproduce

1. Open editor  
2. Open pins_CHITU3D_V5.h or pins_CHITU3D_V6.h 
3. Note FAN_PIN_2 is defined.

Additional info

A easy fix, I just don't have time to create a PR right now. So documented it.

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/19874

PR to fix the affected config: https://github.com/MarlinFirmware/Configurations/pull/284

**Comment by ellensp** [comment]
you had to go and find a config that was effected :P good catch!

**Comment by ellensp** [comment]
merged and closed.
