### ISSUE TITLE
[BUG] Russian language support is gone

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#19872]
Board: MKS robin nano v2.
After update https://github.com/MarlinFirmware/Marlin/commit/4533a197d59ffcaccc4d476f06df7754b11b9b0c(i think this) russian language support is gone. The easiest way to make sure of this is to try to print an LCD from a SD card.
The print start dialog now looks like this:
![photo_2020-10-24_01-16-20](https://user-images.githubusercontent.com/52313714/97058490-a99f5000-1596-11eb-84d0-041a43ea77fa.jpg)
![2](https://user-images.githubusercontent.com/52313714/97058497-ae640400-1596-11eb-8a2c-c95d93fd8b95.jpg)
[conf.zip](https://github.com/MarlinFirmware/Marlin/files/5431986/conf.zip)

**Comment by rhapsodyv** [comment]
Can you test this PR? #19869

**Comment by thisiskeithb** [comment]
Now that PR #19869 is merged, please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by Malderin** [comment]
> Now that PR #19869 is merged, please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

The error remained, tested on the last bugfix from https://github.com/MarlinFirmware/Marlin/pull/19869
There is a new error. When entering the menu setting/config and beyond "leveling settings" or "advance settings", printer freezes and restarts.
See video:
https://yadi.sk/i/nx8dJp8CYrGjNg

**Comment by rhapsodyv** [comment]
I fixed the menu problems here: #19879.

Abou the RU lang, it's working. But you need to manually set it again, because the settings could be reseted. Settings->Lang->Select Russian.

**Comment by Malderin** [comment]
> I fixed the menu problems here: #19879.
> 
> Abou the RU lang, it's working. But you need to manually set it again, because the settings could be reseted. Settings->Lang->Select Russian.

The menu freeze issue is solved, thanks.
But the problem from the first post still persists

**Comment by rhapsodyv** [comment]
Which problem?

Russian is working for me: 
![image](https://user-images.githubusercontent.com/81722/97082289-fc9cf580-15de-11eb-9333-0e929985b5df.jpeg)

**Comment by Malderin** [comment]
> Which problem?
> 
> Russian is working for me:
> ![image](https://user-images.githubusercontent.com/81722/97082289-fc9cf580-15de-11eb-9333-0e929985b5df.jpeg)

The top-level menu is (almost) no problem.
On your screen there should be a translation:
![photo_2020-10-24_16-22-58](https://user-images.githubusercontent.com/52313714/97083271-7f41a700-1617-11eb-9261-a2fb0b5b41c2.jpg)
In tft_Language_ru.h: #define TITLE_READYPRINT_RU                 "готов к"
and 
#define TITLE_SET_RU                        "настройки"
Should be so: 
![photo_2020-10-24_16-46-27](https://user-images.githubusercontent.com/52313714/97083430-a187f480-1618-11eb-98dd-c21f571a139f.jpg)
Now look at the photo in my first post. 
This is how it should be:
![photo_2020-10-24_16-51-02](https://user-images.githubusercontent.com/52313714/97083496-37bc1a80-1619-11eb-953a-b9c598fcf2e9.jpg)
To see this you need to do this:
1. Write any gcode file to the memory card
2. Click on it
3. This dialog will appear.

**Comment by Malderin** [comment]
Earlier I translated all the "settings / config" menus.
On the first 2 levels, the Russian translation has been preserved, on the third level, Russian letters are not displayed.
For instance:
The "Config"  and "Machine settings" is displayed normally, and inside the "acceleration" menu, where you need to enter values, the Russian letters have disappeared. 
The same goes for all menus:
1. Motor settings (and one next) is ok, inside third menu (Steps settings and other) - without russian;
2. Leveling settins - similar to p. 1;
3. Advance settings - similar to p. 1.

**Comment by Malderin** [comment]
If needed, here is my actual build where I am testing:
https://github.com/Malderin/Marlin_2.0.x_official/tree/Marlin-2.0_bugfix_new

**Comment by rhapsodyv** [comment]
Ok, I got it. I will check what is happening.

**Comment by rhapsodyv** [comment]
Ok! Fixed that.
