### ISSUE TITLE
Tried to install Marlin 2.0 and than blank scren

### ISSUE THREAD

**Issue by 18Markus1984** [MarlinFirmware/Marlin#19871]
### Bug Description

Today I tried to install Marlin 2.0 on my creality v1.1.5 board. I already had installed a booloader before.
 I copied the requierd files from the conficorations and setup a conf.h and conf._adv.h for my bltouchV3.1. I build the file and uploaded the file. I used the melzi_optimized. After I had uploaded the file I power circled my ender 3. After that I only have a blank screen and I have no possibility to connect to the printer and change something because the access denied 

### My Configurations

[Marlin-bugfix-2.0.x (2).zip](https://github.com/MarlinFirmware/Marlin/files/5431944/Marlin-bugfix-2.0.x.2.zip)

### Steps to Reproduce

1. I followed the steps of this tutorial: https://www.youtube.com/watch?v=YsTGH5JvClM
2. The first difference in the tutorial and my files appared when I want to select the configartion file because I could switch between differnt borads and the maker not. 
3. The next major difference is that I had three options to choose from melzi, melzi_optimized, melz_optiboot
4. After that I build the file and uploaded it.
5. And now we are at the problem

**Expected behavior: I have a Ender 3 with Marlin 2.0 installed

**Actual behavior:I have a Ender 3 with no possibility to connect to and a blank display. 

#### Additional Information

![PXL_20201023_221333892](https://user-images.githubusercontent.com/52409213/97058382-f894b780-158d-11eb-8045-9ab6788dd42f.jpg)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
