### ISSUE TITLE
[BUG] Failed to compile with password feature

### ISSUE THREAD

**Issue by Speaka** [MarlinFirmware/Marlin#19884]
### Bug Description
I rebased my working branch and failed to build. So I tried with a clean branch.
This will also bring up the same result and wont build.
Lmk if you need more Infos.

### My Configurations

Stock config with this two features enabled.
Building in Platformio Core 5.0.1·Home 3.3.0 IDE 2.7.2 on two different Systems. (Win10)

### Steps to Reproduce

Latest Bugfix with enabled:
_#define EEPROM_SETTINGS
#define PASSWORD_FEATURE_

**Expected behavior:**
Building successfully
**Actual behavior:**
Failing to build with following error:

`Marlin\src\feature\password\password.cpp:49:37: error: no 'void Password::authentication_check()' member function declared in class 'Password'
 void Password::authentication_check() {
                                      ^
cc1plus.exe: warning: unrecognized command line option '-Wno-register'

*** [.pio\build\mega2560\src\src\feature\password\password.cpp.o] Error 1`

**Comment by ellensp** [comment]
you need HAS_LCD_MENU to be valid  to define this authentication_check function.
Ie code thinks you need a LCD display...

but this does seem to be in error. as you have gcodes etc to unlock. a LCD is not a requirement.

**Comment by ellensp** [comment]
In password.h is the following code

```
  #if HAS_LCD_MENU
    static void access_menu_password();
    static void authentication_check();
```
Change to 
```
  static void authentication_check();
  #if HAS_LCD_MENU
    static void access_menu_password();
```
I tested this and it works as expected.

**Comment by ellensp** [comment]
PR created

**Comment by ellensp** [comment]
Merged, closing.

**Comment by Speaka** [comment]
Thanks for the quick support! All working fine now!
