### ISSUE TITLE
[BUG] (MKS robin nano, start problem)

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#19892]
Board: mks robin nano v2
Marlin: last bugfix-2.0.x

The board does not start without a SD card, reboot after writing "booting.."

**Comment by sjasonsmith** [comment]
This issue ignored the issue template and did not provide the requested information.

I am going to close this issue. It sounds like you may have a legitimate problem to report, but it is important that you include all the requested information in the issue template. That information is required, as it helps developers and users know how to help resolve your issue.
