### ISSUE TITLE
[BUG] (MKS robin nano v2, start problem)

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#19893]
### Bug Description

The board does not start without a SD card, reboot after writing "booting.."

### My Configurations

[conf.zip](https://github.com/MarlinFirmware/Marlin/files/5434570/conf.zip)

### Steps to Reproduce

1. Remove SD card
2. Power on the board

**Comment by rhapsodyv** [comment]
Thanks for your report! Fixed here: #19900

**Comment by Malderin** [comment]
Checked, problem solved

**Comment by Malderin** [comment]
> Thanks for your report! Fixed here: #19900

Checked, problem solved
