### ISSUE TITLE
[BUG] Weird temperature spikes with newest stable version of Marlin 2.0.7.2

### ISSUE THREAD

**Issue by szymonrychu** [MarlinFirmware/Marlin#19894]
### Bug Description

Hello!
I would like to report a weird problem that occurs on a my DUE based environment after upgrading to newest 2.0.7.2 version of Marlin.
The problem IS NOT hardware, occurs only after flashing newest version of the firmware.
My hardware consist of DUE3DOM_LE (DUE3DOM_MINI based board), TMC2130 drivers on all axises, dual Z screw independent Z steering, UBL enabled with BLTouch and with E3D pt100 temperature sensor with their amplifier.

What I observed is that during prints Marlin is reporting weird temperature spikes pointing "down" and equalling always 0degC.
Such spikes doesn't trigger overheat protection safeties.
Again- those are not happening with older versions of marlin therefore I don't believe it's a hardware problem.

I suspect that there are two separate loops- one responsible for printing out stuff to terminal and the other responsible for reading out temps. Sometimes those two get out of sync somehow, therefore 0 gets printed out to terminal.
Here is the code [that was working for me before](https://github.com/szymonrychu/Marlin/tree/DUE3DOM_LE) with last common git SHA: `1ac629f919a6312f1ff5c8736e3cc8bea3f2c2b5`.

### My Configurations

I forked Marlin to my repo and work on a daily basis with GIT so instead of uploading zips I will attach a link to a compare page between what I have and original 2.0.7.2 revision of a repo.
[https://github.com/MarlinFirmware/Marlin/compare/2.0.7.2...szymonrychu:DUE3DOM_LE_develop](https://github.com/MarlinFirmware/Marlin/compare/2.0.7.2...szymonrychu:DUE3DOM_LE_develop)
Besides having Configs the delta also includes board definition.

### Steps to Reproduce

Apply patch from a link, flash to DUE, start print and observe temperatures I guess? Hard to tell what might be causing this.

**Comment by szymonrychu** [comment]
Screenshot showing off severity of the problem: [https://imgur.com/a/nwptVr9](https://imgur.com/a/nwptVr9)

**Comment by sjasonsmith** [comment]
@szymonrychu you say this is a recently introduced problem. Could you try to isolate which commit caused it?

**Comment by szymonrychu** [comment]
Out of 2514 commits of difference between latest known good revision up to the first commit that might cause this problem?
I mean- sure I can... But I don't know when I would have enough time to do this- assuming process like this:
1. Rebase
2. Rebuild
3. Flash the new code
4. Test print

would be fully automated (which might or might not be) and because of that it would take roughly speaking 5mins in total and I would use special algorithm to find the problem (bisection method), it's still (in worst case scenario) 12500min in total, which is more than 8 days of continous testing!

At the other hand if something is tagged as a stable release and if there is a documentation stating, that it's supporting certain boards and processors, I would expect that it's sufficiently tested.
In the end we are talking even about potential fire-hazard if it's not, right?

But in the end I can give you some direction I guess? Something I've tested yesterday and I didn't put in the comments yet.

It turns out that last known working revision is showing the same symptoms when I enable `S_CURVE_ACCELERATION`.
At the same time it really doesn't make any difference for the code from `2.0.7.2` version if I enable it or not.

**Comment by szymonrychu** [comment]
Edit:
Last known common commit is https://github.com/szymonrychu/Marlin/commit/1ac629f919a6312f1ff5c8736e3cc8bea3f2c2b5 and is dated to `Oct 5, 2019`.
I've never wrote it's recently introduced :)

**Comment by rhapsodyv** [comment]
Can you share the serial output?

**Comment by sjasonsmith** [comment]
@szymonrychu are you still having this problem? Did you see @rhapsodyv's request for the serial output when this is occurring? You should be able to see it in the OctoPrint terminal. We want to see what the temperate reporting looks like in text form.

**Comment by sjasonsmith** [comment]
No response after 9 days. Closing.
