### ISSUE TITLE
[BUG] "Change filament" from menu will always use second extruder on mixing extruder setup

### ISSUE THREAD

**Issue by fishcu** [MarlinFirmware/Marlin#19911]
### Bug Description

"Change filament" from menu will always use second extruder on mixing extruder setup.

This means that choosing "E1" will then change filament on the second extruder.
Choosing "E2" will change filament on the second extruder as well (as expected).

This is a regression. It was working fine before on a branch based on a much older commit:
https://github.com/fishcu/Marlin/tree/find-problem

### My Configurations

My config is here: https://github.com/fishcu/Marlin/tree/2.0.7.2-a10m

This is based on tag 2.0.7.2.

Flashed on a Geeetech A10M with GT2560 v3.0 board.

### Steps to Reproduce

As described above, use the menu to try and change filament on the first extruder.

**Expected behavior:** Change filament on the first extruder if I choose E1 in the menu.

**Actual behavior:** Filament is changed on E2 in any case.

#### Additional Information

It could be possible to do a `git bisect` with some manual work (cherry-picking or similar) on these commits:
bad: https://github.com/fishcu/Marlin/tree/2.0.7.2-a10m
good: https://github.com/fishcu/Marlin/tree/find-problem

**Comment by fishcu** [comment]
Possibly related issue: https://github.com/MarlinFirmware/Marlin/issues/13351

Possibly related commit: https://github.com/MarlinFirmware/Marlin/commit/ee243e4edfe45fa855d4ff71abf8a9a118b66369

Possibly related issue: https://github.com/MarlinFirmware/Marlin/issues/19877

**Comment by fishcu** [comment]
I can confirm that sending `M600 T0` over serial works as expected. I'm now looking into if maybe the command generated internally is somehow wrong.

**Comment by fishcu** [comment]
Submitted a PR that fixes this here: https://github.com/MarlinFirmware/Marlin/pull/19916

**Comment by nvibd** [comment]
This issue is not fixed. Why close it?

**Comment by fishcu** [comment]
This issue is not fixed. Why close it?
