### ISSUE TITLE
[FR] Color UI - mount SD card after touching SD icon on status screen

### ISSUE THREAD

**Issue by bkiziuk** [MarlinFirmware/Marlin#19923]
# Description

The current behavior when SD card is not mounted (for example, after Power On without SD card inserted) is that the SD card icon is greyed out.
So, when the SD card is inserted, in order to mount it, it is required to go to Settings, scroll down to the bottom and choose Attach Media.
So the FR is simply to try to attach media, when the SD icon is touched and SD card is unmounted.

### Feature Workflow

1. Power-on printer without SD card inserted
2. Insert SD card to the slot
3. Touch greyed out SD icon in order to mount the SD card and then display its contents

#### Additional Information

None.

**Comment by rhapsodyv** [comment]
It’s a good idea... 

But the meaning of the gray button is: this button is disabled. 

Making a disabled button touchable, may break the design language of the interface.

But maybe if we use different color or icon for status, could work.

I will check this.

**Comment by Diego-Rocha** [comment]
@rhapsodyv maybe use the same color/state as enabled...
and if clicked and fail to mount, just show the message on status "SD Init fail", or something like that.
let me know what do you think?

**Comment by rhapsodyv** [comment]
I just made the button always enabled and entering the MenuMenu. In the menu media, the refresh button will mount the SD if it is unmounted! This way we don't break the design language and support what you have suggested! :-)

I hope you like: #20005

Thanks!

**Comment by bkiziuk** [comment]
I think I can live with this solution. Much better than going through the menu :)
