### ISSUE TITLE
[BUG] Z drift in ABL_Bilinear along the Y axis

### ISSUE THREAD

**Issue by LarrxX** [MarlinFirmware/Marlin#19937]
### Bug Description
G29 returns a grid with higher and higher Z values along the Y axis. The bigger the grid, the higher the Z values.

### Configuration Files
[ConfigFiles.zip](https://github.com/MarlinFirmware/Marlin/files/5453487/ConfigFiles.zip)

### Steps to Reproduce
Simply run a G29 command with a high number of grid points (9x9 for example).

**Expected behavior:**
No matter the size of the grid, get coherent Z-Values along the bed.

**Actual behavior:**
The larger the grid used for ABL, the higher the Z-Values get along the Y-axis.

#### Additional Information
I used the [latest commit](https://github.com/MarlinFirmware/Marlin/commit/12dec2563afcc0f92333ce3ddbba28979bc0f865) from the bugfix-2.0.x branch.

I enabled `DEBUG_LEVELING_FEATURE `and `M114_DETAIL`. I used different size grids (3x3, 5x5, 8x8, 11x11x 3x11, 11x3) and ran the following:
`M111 S247`
`G28`
`G29`

You can find the logs in the following zip file:
[Logs.zip](https://github.com/MarlinFirmware/Marlin/files/5453929/Logs.zip)

And here are the results as seen in the Octopi Bed Visualizer Plugin:
![BedVisualizer](https://user-images.githubusercontent.com/16936069/97469145-59cdd980-1946-11eb-8c66-1f5785713ee2.png)

This could probably also be the cause for issue #18769 ?

**Comment by OC-Rookie** [comment]
Interesting. The bed level wasn’t changed at any point during or in between these tests? I’ll run similar tests on my machine and post the results here.

**Comment by LarrxX** [comment]
Nope, didn't touch the bed between tests

**Comment by romejoe** [comment]
@LarrxX I tried to look at your logs.zip, but it contains your configuration files.

**Comment by LarrxX** [comment]
Oops! Updated the log files zip in the original post, sorry!

**Comment by Talha909** [comment]
any success

**Comment by Bloodpack** [comment]
Here same Problem 

Z drift in ABL_Bilinear along the Y axis

Printer CORE XY

**Comment by blueeagle69** [comment]
following!

**Comment by romejoe** [comment]
@LarrxX I have been looking into this issue(unfortunately slowly because of time restrictions and I'm new to the Marlin project) and I had a couple questions. 

- What kind of bed are you using? The bed that comes with the Ender 3 Pro or a glass one?
- Your Ender 3 Pro is using the original 1.x Creality main board, correct?
- If you have a chance, can you rerun the 11x11 bed leveling with `G29 V4`?

I haven't had a chance to test this on my Ender 3 Pro(4.2.2 main board) yet. Hopefully I can run them either tonight or tomorrow.

**Comment by LarrxX** [comment]
@romejoe answers to your questions:

- The original bed that came with the Ender 3 Pro (flexible magnetic bed)

- I bought the printer back in march and never changed the board, so yes, I assume it's using the original 1.x Creality main board.

- Here's my log running `G29 V4` [serial.log.txt](https://github.com/MarlinFirmware/Marlin/files/5476594/serial.log.txt) and the visualization result 
![newplot](https://user-images.githubusercontent.com/16936069/97895285-e22bf000-1d33-11eb-8646-d4e7997fe000.png)

`

**Comment by xyzz** [comment]
I've had a similar thing happen before, try running probe repeatability test in the middle of the bed (`M48 V4`), if you see Z constantly increasing, then the Z lead screw coupler needs to be tightened.

**Comment by romejoe** [comment]
@LarrxX I wasn't able to reproduce this issue on my Ender 3 Pro :/ I'm not sure if this is related, but this printer is fairly new(only a couple weeks old and a handful of small prints). 

<img width="526" alt="Screen Shot 2020-11-02 at 10 19 35 PM" src="https://user-images.githubusercontent.com/387305/97946956-c9363580-1d59-11eb-9e1e-5d011dbbe813.png">

[grid.log](https://github.com/MarlinFirmware/Marlin/files/5479165/grid.log)

Here are the configuration files that I used:
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5479193/Configuration.zip)

I have been busy tonight trying to reproduce on my print and haven't had a chance to look over those logs. Have you tried @xyzz 's solution?

**Comment by LarrxX** [comment]
@xyzz was right. I did a 50 probe repeatability test `M48 P50 V4` and got a standard deviation of **0.115**!! After tightening the Z lead screw, the same test gives a deviation of **0.003** which is way way WAY better :)

And the 11x11 G29 after tightening the screw results in this:
![newplot](https://user-images.githubusercontent.com/16936069/97975654-bf4c1b00-1dc9-11eb-9ebd-793f0b723c86.png)
(no my bed is not flat, which is why I got the BLTouch in the first place).

So I guess my issue is resolved and it's not a Marlin bug.

Thanks for the help!

(will wait a day if there are any answers before closing the issue)

**Comment by OC-Rookie** [comment]
I just ran this test and got a standard deviation of about .006, which I think is 
[pretty good](https://github.com/MarlinFirmware/Marlin/files/5481835/M48.test.txt). I also have the bed visualizer plugin for Octoprint, which also shows good results. However, I do not think this is the full explanation for #18769.

![results](https://user-images.githubusercontent.com/68751808/97997403-d3e7dd80-1de0-11eb-8050-78ff12c51114.png)

**Comment by LarrxX** [comment]
This actually did solve issue #18769  for me, was just heading there to comment on it.

**Comment by romejoe** [comment]
I'm planning to look into #18769 next. I think I have been having that problem with my CR-10 S5. I'll post over there with any info I have. @LarrxX I'm glad that fixed your issue!

**Comment by schleir** [comment]
I'll try the test today and post the results.

**Comment by schleir** [comment]
My Z lead screw coupler is not loose.
I verified that my repeatability test `M48 P50 V4` has less than 0.004 Standard deviation on 4 corners + center.

I don't have this issue(Z drift), but still am observing issues reported in https://github.com/MarlinFirmware/Marlin/issues/18769

**Comment by LarrxX** [comment]
I'm closing the issue since it's not Marlin related.
