### ISSUE TITLE
[BUG] (Delta bed leveling incorrect probe result  )

### ISSUE THREAD

**Issue by gellary** [MarlinFirmware/Marlin#19940]
### Bug Description
I have 2 problem 

1.  bed leveling concave occur 
2.  G29 odd result

I test with newest Marlin 2.0 Bugfix and marlin 2.0.7 the concave and strange G29 result still appear  .
I confirmed the the hardware is okay , tested on marlin 2.0.6 work fine .
now 2.0.6 is crash,after platform IO update .
when 2.0.6 Bed Leveling all number under 0.1 but now 2.0.7 greater than 1 
I have done all the calibration G33 include still can't find out what happened ?
and try #define DELTA_SMOOTH_ROD_OFFSET 152 not work also

### Hardware
BOARD_MKS_GEN_L
Kossel delta printer with Hall probe sensor

### here is the probe result
M111 S32
G28
G29

Probe Z:-2.35 Discrepancy:-0.05
<<< Probe::run_z_probe  X-10.00 Y0.00 Z-2.35
>>> do_blocking_move_to  X-10.00 Y0.00 Z-2.35
>  X-10.00 Y0.00 Z12.65
  destination= X-10.00 Y0.00 Z-2.35 : destination = current_position
  destination= X-10.00 Y0.00 Z12.65 : prepare_fast_move_to_destination
  current_position= X-10.00 Y0.00 Z12.65 : z raise move
  current_position= X-10.00 Y0.00 Z12.65 : xy move
<<< do_blocking_move_to  X-10.00 Y0.00 Z12.65
<<< Probe::probe_at_point  X-10.00 Y0.00 Z12.65
>>> Probe::probe_at_point  X-10.00 Y0.00 Z12.65
...(50.00, 0.00, raise, 0, probe_relative)
  current_position= X-10.00 Y0.00 Z12.65 :
>>> do_blocking_move_to  X-10.00 Y0.00 Z12.65
>  X40.00 Y0.00 Z12.65
  destination= X-10.00 Y0.00 Z12.65 : destination = current_position
  current_position= X40.00 Y0.00 Z12.65 : xy move
<<< do_blocking_move_to  X40.00 Y0.00 Z12.65
  current_position= X40.00 Y0.00 Z12.65 : Probe::set_deployed
deploy: 1
>>> Probe::run_z_probe  X40.00 Y0.00 Z12.65
>>> Probe::probe_down_to_z  X40.00 Y0.00 Z12.65
>>> do_blocking_move_to  X40.00 Y0.00 Z12.65
>  X40.00 Y0.00 Z-3.00
  destination= X40.00 Y0.00 Z12.65 : destination = current_position
  current_position= X40.00 Y0.00 Z12.65 : xy move
  destination= X40.00 Y0.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X40.00 Y0.00 Z-3.00 : z lower move
<<< do_blocking_move_to  X40.00 Y0.00 Z-3.00
  current_position= X40.00 Y0.00 Z-0.70 : sync_plan_position
<<< Probe::probe_down_to_z  X40.00 Y0.00 Z-0.70
1st Probe Z:-0.70
>>> do_blocking_move_to  X40.00 Y0.00 Z-0.70
>  X40.00 Y0.00 Z14.30
  destination= X40.00 Y0.00 Z-0.70 : destination = current_position
  destination= X40.00 Y0.00 Z14.30 : prepare_fast_move_to_destination
  current_position= X40.00 Y0.00 Z14.30 : z raise move
  current_position= X40.00 Y0.00 Z14.30 : xy move
<<< do_blocking_move_to  X40.00 Y0.00 Z14.30
>>> Probe::probe_down_to_z  X40.00 Y0.00 Z14.30
>>> do_blocking_move_to  X40.00 Y0.00 Z14.30
>  X40.00 Y0.00 Z-3.00
  destination= X40.00 Y0.00 Z14.30 : destination = current_position
  current_position= X40.00 Y0.00 Z14.30 : xy move
  destination= X40.00 Y0.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X40.00 Y0.00 Z-3.00 : z lower move
echo:busy: processing
<<< do_blocking_move_to  X40.00 Y0.00 Z-3.00
  current_position= X40.00 Y0.00 Z-0.64 : sync_plan_position
<<< Probe::probe_down_to_z  X40.00 Y0.00 Z-0.64
2nd Probe Z:-0.64 Discrepancy:-0.06
<<< Probe::run_z_probe  X40.00 Y0.00 Z-0.64
>>> do_blocking_move_to  X40.00 Y0.00 Z-0.64
>  X40.00 Y0.00 Z14.36
  destination= X40.00 Y0.00 Z-0.64 : destination = current_position
  destination= X40.00 Y0.00 Z14.36 : prepare_fast_move_to_destination
  current_position= X40.00 Y0.00 Z14.36 : z raise move
  current_position= X40.00 Y0.00 Z14.36 : xy move
<<< do_blocking_move_to  X40.00 Y0.00 Z14.36
<<< Probe::probe_at_point  X40.00 Y0.00 Z14.36
>>> Probe::probe_at_point  X40.00 Y0.00 Z14.36
...(100.00, 0.00, raise, 0, probe_relative)
  current_position= X40.00 Y0.00 Z14.36 :
>>> do_blocking_move_to  X40.00 Y0.00 Z14.36
>  X90.00 Y0.00 Z14.36
  destination= X40.00 Y0.00 Z14.36 : destination = current_position
  current_position= X90.00 Y0.00 Z14.36 : xy move
echo:busy: processing
<<< do_blocking_move_to  X90.00 Y0.00 Z14.36
  current_position= X90.00 Y0.00 Z14.36 : Probe::set_deployed
deploy: 1
>>> Probe::run_z_probe  X90.00 Y0.00 Z14.36
>>> Probe::probe_down_to_z  X90.00 Y0.00 Z14.36
>>> do_blocking_move_to  X90.00 Y0.00 Z14.36
>  X90.00 Y0.00 Z-3.00
  destination= X90.00 Y0.00 Z14.36 : destination = current_position
  current_position= X90.00 Y0.00 Z14.36 : xy move
  destination= X90.00 Y0.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X90.00 Y0.00 Z-3.00 : z lower move
<<< do_blocking_move_to  X90.00 Y0.00 Z-3.00
  current_position= X90.00 Y0.00 Z4.96 : sync_plan_position
<<< Probe::probe_down_to_z  X90.00 Y0.00 Z4.96
1st Probe Z:4.96
>>> do_blocking_move_to  X90.00 Y0.00 Z4.96
>  X90.00 Y0.00 Z19.96
  destination= X90.00 Y0.00 Z4.96 : destination = current_position
  destination= X90.00 Y0.00 Z19.96 : prepare_fast_move_to_destination
  current_position= X90.00 Y0.00 Z19.96 : z raise move
  current_position= X90.00 Y0.00 Z19.96 : xy move
<<< do_blocking_move_to  X90.00 Y0.00 Z19.96
>>> Probe::probe_down_to_z  X90.00 Y0.00 Z19.96
>>> do_blocking_move_to  X90.00 Y0.00 Z19.96
>  X90.00 Y0.00 Z-3.00
  destination= X90.00 Y0.00 Z19.96 : destination = current_position
  current_position= X90.00 Y0.00 Z19.96 : xy move
  destination= X90.00 Y0.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X90.00 Y0.00 Z-3.00 : z lower move
<<< do_blocking_move_to  X90.00 Y0.00 Z-3.00
  current_position= X90.00 Y0.00 Z5.03 : sync_plan_position
<<< Probe::probe_down_to_z  X90.00 Y0.00 Z5.03
2nd Probe Z:5.03 Discrepancy:-0.07
<<< Probe::run_z_probe  X90.00 Y0.00 Z5.03
>>> do_blocking_move_to  X90.00 Y0.00 Z5.03
>  X90.00 Y0.00 Z20.03
  destination= X90.00 Y0.00 Z5.03 : destination = current_position
  destination= X90.00 Y0.00 Z20.03 : prepare_fast_move_to_destination
  current_position= X90.00 Y0.00 Z20.03 : z raise move
  current_position= X90.00 Y0.00 Z20.03 : xy move
echo:busy: processing
<<< do_blocking_move_to  X90.00 Y0.00 Z20.03
<<< Probe::probe_at_point  X90.00 Y0.00 Z20.03
>>> Probe::probe_at_point  X90.00 Y0.00 Z20.03
...(50.00, 50.00, raise, 0, probe_relative)
  current_position= X90.00 Y0.00 Z20.03 :
>>> do_blocking_move_to  X90.00 Y0.00 Z20.03
>  X40.00 Y50.00 Z20.03
  destination= X90.00 Y0.00 Z20.03 : destination = current_position
  current_position= X40.00 Y50.00 Z20.03 : xy move
<<< do_blocking_move_to  X40.00 Y50.00 Z20.03
  current_position= X40.00 Y50.00 Z20.03 : Probe::set_deployed
deploy: 1
>>> Probe::run_z_probe  X40.00 Y50.00 Z20.03
>>> Probe::probe_down_to_z  X40.00 Y50.00 Z20.03
>>> do_blocking_move_to  X40.00 Y50.00 Z20.03
>  X40.00 Y50.00 Z-3.00
  destination= X40.00 Y50.00 Z20.03 : destination = current_position
  current_position= X40.00 Y50.00 Z20.03 : xy move
  destination= X40.00 Y50.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X40.00 Y50.00 Z-3.00 : z lower move
<<< do_blocking_move_to  X40.00 Y50.00 Z-3.00
  current_position= X40.00 Y50.00 Z0.75 : sync_plan_position
<<< Probe::probe_down_to_z  X40.00 Y50.00 Z0.75
1st Probe Z:0.75
>>> do_blocking_move_to  X40.00 Y50.00 Z0.75
>  X40.00 Y50.00 Z15.75
  destination= X40.00 Y50.00 Z0.75 : destination = current_position
  destination= X40.00 Y50.00 Z15.75 : prepare_fast_move_to_destination
  current_position= X40.00 Y50.00 Z15.75 : z raise move
  current_position= X40.00 Y50.00 Z15.75 : xy move
echo:busy: processing
<<< do_blocking_move_to  X40.00 Y50.00 Z15.75
>>> Probe::probe_down_to_z  X40.00 Y50.00 Z15.75
>>> do_blocking_move_to  X40.00 Y50.00 Z15.75
>  X40.00 Y50.00 Z-3.00
  destination= X40.00 Y50.00 Z15.75 : destination = current_position
  current_position= X40.00 Y50.00 Z15.75 : xy move
  destination= X40.00 Y50.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X40.00 Y50.00 Z-3.00 : z lower move
<<< do_blocking_move_to  X40.00 Y50.00 Z-3.00
  current_position= X40.00 Y50.00 Z0.86 : sync_plan_position
<<< Probe::probe_down_to_z  X40.00 Y50.00 Z0.86
2nd Probe Z:0.86 Discrepancy:-0.11
<<< Probe::run_z_probe  X40.00 Y50.00 Z0.86
>>> do_blocking_move_to  X40.00 Y50.00 Z0.86
>  X40.00 Y50.00 Z15.86
  destination= X40.00 Y50.00 Z0.86 : destination = current_position
  destination= X40.00 Y50.00 Z15.86 : prepare_fast_move_to_destination
  current_position= X40.00 Y50.00 Z15.86 : z raise move
  current_position= X40.00 Y50.00 Z15.86 : xy move
<<< do_blocking_move_to  X40.00 Y50.00 Z15.86
<<< Probe::probe_at_point  X40.00 Y50.00 Z15.86
>>> Probe::probe_at_point  X40.00 Y50.00 Z15.86
...(0.00, 50.00, raise, 0, probe_relative)
  current_position= X40.00 Y50.00 Z15.86 :
>>> do_blocking_move_to  X40.00 Y50.00 Z15.86
>  X-10.00 Y50.00 Z15.86
  destination= X40.00 Y50.00 Z15.86 : destination = current_position
echo:busy: processing
  current_position= X-10.00 Y50.00 Z15.86 : xy move
<<< do_blocking_move_to  X-10.00 Y50.00 Z15.86
  current_position= X-10.00 Y50.00 Z15.86 : Probe::set_deployed
deploy: 1
>>> Probe::run_z_probe  X-10.00 Y50.00 Z15.86
>>> Probe::probe_down_to_z  X-10.00 Y50.00 Z15.86
>>> do_blocking_move_to  X-10.00 Y50.00 Z15.86
>  X-10.00 Y50.00 Z-3.00
  destination= X-10.00 Y50.00 Z15.86 : destination = current_position
  current_position= X-10.00 Y50.00 Z15.86 : xy move
  destination= X-10.00 Y50.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X-10.00 Y50.00 Z-3.00 : z lower move
<<< do_blocking_move_to  X-10.00 Y50.00 Z-3.00
  current_position= X-10.00 Y50.00 Z-0.94 : sync_plan_position
<<< Probe::probe_down_to_z  X-10.00 Y50.00 Z-0.94
1st Probe Z:-0.94
>>> do_blocking_move_to  X-10.00 Y50.00 Z-0.94
>  X-10.00 Y50.00 Z14.06
  destination= X-10.00 Y50.00 Z-0.94 : destination = current_position
  destination= X-10.00 Y50.00 Z14.06 : prepare_fast_move_to_destination
  current_position= X-10.00 Y50.00 Z14.06 : z raise move
  current_position= X-10.00 Y50.00 Z14.06 : xy move
<<< do_blocking_move_to  X-10.00 Y50.00 Z14.06
>>> Probe::probe_down_to_z  X-10.00 Y50.00 Z14.06
>>> do_blocking_move_to  X-10.00 Y50.00 Z14.06
>  X-10.00 Y50.00 Z-3.00
  destination= X-10.00 Y50.00 Z14.06 : destination = current_position
  current_position= X-10.00 Y50.00 Z14.06 : xy move
  destination= X-10.00 Y50.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X-10.00 Y50.00 Z-3.00 : z lower move
echo:busy: processing
<<< do_blocking_move_to  X-10.00 Y50.00 Z-3.00
  current_position= X-10.00 Y50.00 Z-0.84 : sync_plan_position
<<< Probe::probe_down_to_z  X-10.00 Y50.00 Z-0.84
2nd Probe Z:-0.84 Discrepancy:-0.10
<<< Probe::run_z_probe  X-10.00 Y50.00 Z-0.84
>>> do_blocking_move_to  X-10.00 Y50.00 Z-0.84
>  X-10.00 Y50.00 Z14.16
  destination= X-10.00 Y50.00 Z-0.84 : destination = current_position
  destination= X-10.00 Y50.00 Z14.16 : prepare_fast_move_to_destination
  current_position= X-10.00 Y50.00 Z14.16 : z raise move
  current_position= X-10.00 Y50.00 Z14.16 : xy move
<<< do_blocking_move_to  X-10.00 Y50.00 Z14.16
<<< Probe::probe_at_point  X-10.00 Y50.00 Z14.16
>>> Probe::probe_at_point  X-10.00 Y50.00 Z14.16
...(-50.00, 50.00, raise, 0, probe_relative)
  current_position= X-10.00 Y50.00 Z14.16 :
>>> do_blocking_move_to  X-10.00 Y50.00 Z14.16
>  X-60.00 Y50.00 Z14.16
  destination= X-10.00 Y50.00 Z14.16 : destination = current_position
  current_position= X-60.00 Y50.00 Z14.16 : xy move
<<< do_blocking_move_to  X-60.00 Y50.00 Z14.16
  current_position= X-60.00 Y50.00 Z14.16 : Probe::set_deployed
deploy: 1
>>> Probe::run_z_probe  X-60.00 Y50.00 Z14.16
>>> Probe::probe_down_to_z  X-60.00 Y50.00 Z14.16
>>> do_blocking_move_to  X-60.00 Y50.00 Z14.16
>  X-60.00 Y50.00 Z-3.00
  destination= X-60.00 Y50.00 Z14.16 : destination = current_position
  current_position= X-60.00 Y50.00 Z14.16 : xy move
  destination= X-60.00 Y50.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X-60.00 Y50.00 Z-3.00 : z lower move
<<< do_blocking_move_to  X-60.00 Y50.00 Z-3.00
  current_position= X-60.00 Y50.00 Z1.42 : sync_plan_position
<<< Probe::probe_down_to_z  X-60.00 Y50.00 Z1.42
1st Probe Z:1.42
>>> do_blocking_move_to  X-60.00 Y50.00 Z1.42
>  X-60.00 Y50.00 Z16.42
  destination= X-60.00 Y50.00 Z1.42 : destination = current_position
  destination= X-60.00 Y50.00 Z16.42 : prepare_fast_move_to_destination
  current_position= X-60.00 Y50.00 Z16.42 : z raise move
  current_position= X-60.00 Y50.00 Z16.42 : xy move
echo:busy: processing
<<< do_blocking_move_to  X-60.00 Y50.00 Z16.42
>>> Probe::probe_down_to_z  X-60.00 Y50.00 Z16.42
>>> do_blocking_move_to  X-60.00 Y50.00 Z16.42
>  X-60.00 Y50.00 Z-3.00
  destination= X-60.00 Y50.00 Z16.42 : destination = current_position
  current_position= X-60.00 Y50.00 Z16.42 : xy move
  destination= X-60.00 Y50.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X-60.00 Y50.00 Z-3.00 : z lower move
<<< do_blocking_move_to  X-60.00 Y50.00 Z-3.00
  current_position= X-60.00 Y50.00 Z1.47 : sync_plan_position
<<< Probe::probe_down_to_z  X-60.00 Y50.00 Z1.47
2nd Probe Z:1.47 Discrepancy:-0.05
<<< Probe::run_z_probe  X-60.00 Y50.00 Z1.47
>>> do_blocking_move_to  X-60.00 Y50.00 Z1.47
>  X-60.00 Y50.00 Z16.47
  destination= X-60.00 Y50.00 Z1.47 : destination = current_position
  destination= X-60.00 Y50.00 Z16.47 : prepare_fast_move_to_destination
  current_position= X-60.00 Y50.00 Z16.47 : z raise move
  current_position= X-60.00 Y50.00 Z16.47 : xy move
<<< do_blocking_move_to  X-60.00 Y50.00 Z16.47
<<< Probe::probe_at_point  X-60.00 Y50.00 Z16.47
>>> Probe::probe_at_point  X-60.00 Y50.00 Z16.47
...(0.00, 100.00, raise, 0, probe_relative)
  current_position= X-60.00 Y50.00 Z16.47 :
>>> do_blocking_move_to  X-60.00 Y50.00 Z16.47
>  X-10.00 Y100.00 Z16.47
  destination= X-60.00 Y50.00 Z16.47 : destination = current_position
echo:busy: processing
  current_position= X-10.00 Y100.00 Z16.47 : xy move
<<< do_blocking_move_to  X-10.00 Y100.00 Z16.47
  current_position= X-10.00 Y100.00 Z16.47 : Probe::set_deployed
deploy: 1
>>> Probe::run_z_probe  X-10.00 Y100.00 Z16.47
>>> Probe::probe_down_to_z  X-10.00 Y100.00 Z16.47
>>> do_blocking_move_to  X-10.00 Y100.00 Z16.47
>  X-10.00 Y100.00 Z-3.00
  destination= X-10.00 Y100.00 Z16.47 : destination = current_position
  current_position= X-10.00 Y100.00 Z16.47 : xy move
  destination= X-10.00 Y100.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X-10.00 Y100.00 Z-3.00 : z lower move
<<< do_blocking_move_to  X-10.00 Y100.00 Z-3.00
  current_position= X-10.00 Y100.00 Z4.42 : sync_plan_position
<<< Probe::probe_down_to_z  X-10.00 Y100.00 Z4.42
1st Probe Z:4.42
>>> do_blocking_move_to  X-10.00 Y100.00 Z4.42
>  X-10.00 Y100.00 Z19.42
  destination= X-10.00 Y100.00 Z4.42 : destination = current_position
  destination= X-10.00 Y100.00 Z19.42 : prepare_fast_move_to_destination
  current_position= X-10.00 Y100.00 Z19.42 : z raise move
  current_position= X-10.00 Y100.00 Z19.42 : xy move
<<< do_blocking_move_to  X-10.00 Y100.00 Z19.42
>>> Probe::probe_down_to_z  X-10.00 Y100.00 Z19.42
>>> do_blocking_move_to  X-10.00 Y100.00 Z19.42
>  X-10.00 Y100.00 Z-3.00
  destination= X-10.00 Y100.00 Z19.42 : destination = current_position
  current_position= X-10.00 Y100.00 Z19.42 : xy move
  destination= X-10.00 Y100.00 Z-3.00 : prepare_fast_move_to_destination
  current_position= X-10.00 Y100.00 Z-3.00 : z lower move
echo:busy: processing
<<< do_blocking_move_to  X-10.00 Y100.00 Z-3.00
  current_position= X-10.00 Y100.00 Z4.48 : sync_plan_position
<<< Probe::probe_down_to_z  X-10.00 Y100.00 Z4.48
2nd Probe Z:4.48 Discrepancy:-0.06
<<< Probe::run_z_probe  X-10.00 Y100.00 Z4.48
>>> do_blocking_move_to  X-10.00 Y100.00 Z4.48
>  X-10.00 Y100.00 Z19.48
  destination= X-10.00 Y100.00 Z4.48 : destination = current_position
  destination= X-10.00 Y100.00 Z19.48 : prepare_fast_move_to_destination
  current_position= X-10.00 Y100.00 Z19.48 : z raise move
  current_position= X-10.00 Y100.00 Z19.48 : xy move
<<< do_blocking_move_to  X-10.00 Y100.00 Z19.48
<<< Probe::probe_at_point  X-10.00 Y100.00 Z19.48
  current_position= X-10.00 Y100.00 Z19.48 : Probe::set_deployed
deploy: 0
>>> do_blocking_move_to  X-10.00 Y100.00 Z19.48
>  X-10.00 Y100.00 Z19.48
  destination= X-10.00 Y100.00 Z19.48 : destination = current_position
  current_position= X-10.00 Y100.00 Z19.48 : xy move
<<< do_blocking_move_to  X-10.00 Y100.00 Z19.48
  current_position= X-10.00 Y100.00 Z19.48 : > probing complete
Bilinear Leveling Grid:
      0      1      2      3      4
 0 +5.765 +5.736 +6.080 +3.544 +3.503
 1 +5.565 +2.178 +0.008 +1.711 +4.321
 2 +5.988 -0.128 -2.372 -0.666 +5.004
 3 +3.214 +1.449 -0.878 +0.815 +2.269
 4 +2.806 +3.578 +4.460 +1.990 +1.032
G29 uncorrected Z:19.48
 corrected Z:15.20
  current_position= X-10.00 Y100.00 Z15.20 : sync_plan_position

### Configuration Files
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5456729/Configuration.zip)

### Did i miss something in configuration file ?
![image](https://user-images.githubusercontent.com/71171340/97538589-a1fb0380-19fb-11eb-8cdc-c03d7b40f47e.png)

**Comment by sjasonsmith** [comment]
Have you performed a G33 auto-calibration?

**Comment by gellary** [comment]
yes i did
> Have you performed a G33 auto-calibration?

**Comment by gellary** [comment]
i find out the problem, every time finish G33 , i didn't use M500 
marlin 2.0.7 not problem 

marlin 2.0.7.2 "BABYSTEP_ALWAYS_AVAILABLE" will cause restart when adjust z probe offset .

**Comment by boelle** [comment]
> marlin 2.0.7 not problem

So not a problem after all ?

**Comment by gellary** [comment]
@boelle 
yes  2.0.7，not a problem
