### ISSUE TITLE
Wrong Endstop definition

### ISSUE THREAD

**Issue by AleyRobotics** [MarlinFirmware/Marlin#19942]
I had issue with endstops y axis and found bug.
in file Configuration_pins.h

 // ENDSTOP pins
 #define X_MIN_PIN            ORIG_X_MIN_PIN
 #define X_MAX_PIN            ORIG_X_MAX_PIN
 #define Y_MIN_PIN            ORIG_Y_MIN_PIN
 #define Y_MAX_PIN            ORIG_X_MAX_PIN  <<<<<<<<<<< BUG must be  #define Y_MAX_PIN ORIG_Y_MAX_PIN
 #define Z_MIN_PIN            ORIG_Z_MIN_PIN

**Comment by qwewer0** [comment]
Where did you find Configuration_pins.h?
