### ISSUE TITLE
[BUG] Ender 3V2 - Moving Z after called print also moves extruder

### ISSUE THREAD

**Issue by thepixelabs** [MarlinFirmware/Marlin#19944]
### Bug Description

Working with ender 3v2, using latest bugfix branch when cancelling a print, moving Z axis will also move the filament (it moved the extruder in the same amount).
Another move of Z axis will not do it again.

This happened in 2.0.7, later i reverted to creality's firmware, but now after installing bltouch i put bugfix 2.0.x and i see this hasn't been solved.
#19644 < Posted here before

### Configuration Files
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/5458316/Archive.zip)

### Steps to Reproduce

1. Start a print
2. Cancel (I cancelled using octoprint's interface)
3. Using printer interface I tried to move Z axis (I usually do it to clean the bed surface)

**Expected behavior:**

Only the Z axis should move

**Actual behavior:**

Z axis move and extruder moved as well
Very problematic as this can harm printers, the nozzle might not be hot enough, it can also cause jam inside the bowden tube (which it did for me) and it can make a mess of the spooler as it throws out the filament very quickly

**Comment by sjasonsmith** [comment]
How do you observe E moving? Maybe it is just oozing while everything is hot?

**Comment by thepixelabs** [comment]
@sjasonsmith sorry for not being clear on this, the extruder actually moves back, minus of the same amout I guess, it retracts in the same amount.. I see the filament shooting out.. I can take a video of this happening if needed.. Just start a print, cancel it and it will happen

**Comment by liamtoran** [comment]
Same exact behavior for me. For me the extruder retracts like crazy when moving Z up (There is a knob and it turns counterclockwise, its not oozing)

**Comment by thepixelabs** [comment]
@liamkesatoran I tested today, If you home x/y (octoprint) before moving Z then it won't take out the filament..

**Comment by boelle** [comment]
@pixelicous i think a video will be good in this case

**Comment by thepixelabs** [comment]
@boelle @sjasonsmith Attached video - https://youtu.be/LNKouvYJv7E

I tried homing / moving Z from lcd menu, this resulted in the same thing..
So only homing/moving from octo worked after cancel, I didn't try homing from octoprint but moving Z from lcd menu

**Comment by thepixelabs** [comment]
@sjasonsmith Thanks for labelling this, hopefully somebody will pick this up.. it can be very problematic.. would have helped myself if i knew where to look, never code anything on marlin firmware

**Comment by chevyman142000** [comment]
I am also having this same issue. More than glad to help troubleshoot if you need anything.

**Comment by sjasonsmith** [comment]
It would help if you can try an older version such as 2.0.6.1, to determine whether this problem is new.

**Comment by rhapsodyv** [comment]
It only happen with printing started / cancelled using OctoPrint?

If you start/stop the print from the LCD, do you get the same behaviour?

If you start/stop the print from the Octoprint and try to move using Octoprint interface, do you get the same behaviour?

**Comment by rhapsodyv** [comment]
@pixelicous can you do a simple test with this branch? https://github.com/rhapsodyv/Marlin/tree/dwin-move-axis-fix It just a "try".

**Comment by FanDjango** [comment]
Could you also check what is coded in the Octoprint Setup for "GCODE Scripts" for when a print is cancelled?

**Comment by rhapsodyv** [comment]
> @pixelicous can you do a simple test with this branch? https://github.com/rhapsodyv/Marlin/tree/dwin-move-axis-fix It just a "try".

No one having the issue could test this?

**Comment by liamtoran** [comment]
> It only happen with printing started / cancelled using OctoPrint?
> 
> If you start/stop the print from the LCD, do you get the same behaviour?
> 
> If you start/stop the print from the Octoprint and try to move using Octoprint interface, do you get the same behaviour?

For me it has happened even though I never used Octoprint.

**Comment by thepixelabs** [comment]
sorry for not being responsive
@sjasonsmith It happened also on 2.0.6.1
@rhapsodyv it also happened without octoprint before. i dont remember the results of the two other questions but i can test tomorrow. It will be possible to test the branch in a day or two
thanks for looking at this 👍

**Comment by rhapsodyv** [comment]
Hi @pixelicous, did you tried my branch? Thanks!

**Comment by thepixelabs** [comment]
@rhapsodyv Sorry, I didn't have time to check it out till today-

So i did a couple of tests
1. Start print > Stop from octoprint > Move Z axis from printer
result: same problem, extruder moves the same amount as z axis

2. Start print > Stop from octoprint > Move Z axis from octoprint
result: Z axis move as expected and extruder moves for a very quick duration (like 2ms) and then stops. Not sure if this is the same issue where the extruder moves again but then halted for some reason, or just normal operation where a retraction happens before the heatblock moves up on z axis

3. Start print > Stop from octoprint > Move Y axis from printer screen then try to move Z from printer screen
result: only the z axis moves, no issues with extruder

@FanDjango This is the gcode script ran after job is cancelled (From octoprint):
```
; disable motors
M84

;disable all heaters
{% snippet 'disable_hotends' %}
{% snippet 'disable_bed' %}
;disable fan
M106 S0
```

**Comment by rhapsodyv** [comment]
> @rhapsodyv Sorry, I didn't have time to check it out till today-
> 
> So i did a couple of tests
> 
> 1. Start print > Stop from octoprint > Move Z axis from printer
>    result: same problem, extruder moves the same amount as z axis
> 2. Start print > Stop from octoprint > Move Z axis from octoprint
>    result: Z axis move as expected and extruder moves for a very quick duration (like 2ms) and then stops. Not sure if this is the same issue where the extruder moves again but then halted for some reason, or just normal operation where a retraction happens before the heatblock moves up on z axis
> 3. Start print > Stop from octoprint > Move Y axis from printer screen then try to move Z from printer screen
>    result: only the z axis moves, no issues with extruder
> 
> @FanDjango This is the gcode script ran after job is cancelled (From octoprint):
> 
> ```
> ; disable motors
> M84
> 
> ;disable all heaters
> {% snippet 'disable_hotends' %}
> {% snippet 'disable_bed' %}
> ;disable fan
> M106 S0
> ```

Thanks for the tests! We are almost there. Two things:

 1) Did you test using bugfix, or my branch? ( https://github.com/rhapsodyv/Marlin/tree/dwin-move-axis-fix)
 
2) Can you add G28 at the end of gcode for canceled scripts and test again?

Thanks!

**Comment by thepixelabs** [comment]
@rhapsodyv 

1. your branch
2. yes, will do it tomorrow morning hopefully :) but if i am not mistaken i already tested homing from octoprint and then moving the y axis from the screen and it was OK, no issues with extruder starting as well

**Comment by rhapsodyv** [comment]
> 2. yes, will do it tomorrow morning hopefully :) but if i am not mistaken i already tested homing from octoprint and then moving the y axis from the screen and it was OK, no issues with extruder starting as well

What is happening is that when we cancel a print from Octo (without G28), Marlin stays in a total unpredictable state. That is the reason the axis move together. In my branch, I'm trying to work around it, but the "correct" way would be: always do G28 when a print is canceled. Marlin does that, when you print from SD. I think Octo should to it too.

**Comment by thepixelabs** [comment]
> > 1. yes, will do it tomorrow morning hopefully :) but if i am not mistaken i already tested homing from octoprint and then moving the y axis from the screen and it was OK, no issues with extruder starting as well
> 
> What is happening is that when we cancel a print from Octo (without G28), Marlin stays in a total unpredictable state. That is the reason the axis move together. In my branch, I'm trying to work around it, but the "correct" way would be: always do G28 when a print is canceled. Marlin does that, when you print from SD. I think Octo should to it too.

I'll try to print from marlin directly and sd, then cancel and see what happens. if i remember correctly it didn't happen only with octoprint.. need to check though. also.. how can we explain the fact that moving the Y axis, just after that cancelled print, only the y axis move and not the extruder, while moving the Z axis move both..

**Comment by rhapsodyv** [comment]
> I'll try to print from marlin directly and sd, then cancel and see what happens. if i remember correctly it didn't happen only with octoprint.. need to check though. also.. how can we explain the fact that moving the Y axis, just after that cancelled print, only the y axis move and not the extruder, while moving the Z axis move both..

I don't have any idea, yet hahaha. I'm trying to fix things that could generate this problem, but I can't reproduce it (I don't have a ender v2)

**Comment by thisiskeithb** [comment]
> That is the reason the axis move together. In my branch, I'm trying to work around it, but the "correct" way would be: always do G28 when a print is canceled.

Isn't that a bad idea if you have a half-completed print on the bed and you cancel?

**Comment by rhapsodyv** [comment]
> > That is the reason the axis move together. In my branch, I'm trying to work around it, but the "correct" way would be: always do G28 when a print is canceled.
> 
> Isn't that a bad idea if you have a half-completed print on the bed and you cancel?

Yes, you are right. G28 is a terrible idea. Let me take a look in what marlin actually does.

**Comment by thisiskeithb** [comment]
Default is a `G28XY` If printing from SD.
https://github.com/MarlinFirmware/Marlin/blob/a4d6908d556afd77cf66ef7a8adc7c34fee81674/Marlin/Configuration_adv.h#L1204

**Comment by rhapsodyv** [comment]
> Default is a `G28XY` If printing from SD.
> 
> https://github.com/MarlinFirmware/Marlin/blob/a4d6908d556afd77cf66ef7a8adc7c34fee81674/Marlin/Configuration_adv.h#L1204

Exactly!

Plus `M410` (`quickstop_stepper()`) and `M108`.

Marlin does something like this on a SD print abort:
```
M410  //quickstop_stepper
{% snippet 'disable_hotends' %}  //probably M81?
{% snippet 'disable_bed' %}
;disable fan
M106 S0
M108
G28XY  //home xy -> EVENT_GCODE_SD_ABORT
```

@pixelicous can you try this?

**Comment by thepixelabs** [comment]
> ```
> M410  //quickstop_stepper
> {% snippet 'disable_hotends' %}  //probably M81?
> {% snippet 'disable_bed' %}
> ;disable fan
> M106 S0
> M108
> G28XY  //home xy -> EVENT_GCODE_SD_ABORT
> ```
> 
> @pixelicous can you try this?

So i've set it in octo, didn't reboot the raspberry and started the print
After cancelling the printer didn't home its axis at all, stayed at the same place.
I've tried moving Z axis afterwards, both Z axis and extruder moved as before
Tried this twice

I wasn't using your branch this time, as i've already reverted to the firmware file i've been using before (bugfix2.0 branch from around a month ago)

**Comment by rhapsodyv** [comment]
So, octoprint ignored the cancel gcode?! 
Can you share the serial, so we can see what it sent?

**Comment by thepixelabs** [comment]
@rhapsodyv yes seems like it..
I will test it tomorrow or in 2 days and let you know

**Comment by jojolll** [comment]
> So, octoprint ignored the cancel gcode?!
> Can you share the serial, so we can see what it sent?

Hello! 
I currently have a very very similar concern without using octoprint. On the other hand, I have ESP3D connected to the serial port.

In my opinion, the problem is not due to the fact that I have a XY homing after the cancellation, everything is fine until a movement is requested by the screen. In my case it's the Y axis, I set it to 230 and it ejects the filament through the extruder. I didn't try the other axes. 

I even have the impression that the extruder does not even respect its steps/mm since it ejects me the totality of the filament present in the bowden tube (415mm if I take it out automatically by the extrusion motor)
(Marlin 2.0.7.2) 

EDIT : After a few tests, the problem also appears just after the end of a successful print, under the same conditions. The Z-axis as well as the Y-axis cause the problem. I have the impression that the extruder moves backwards by a constant amount, regardless of the demand for Z or Y movement.

**Comment by thepixelabs** [comment]
@rhapsodyv 
> So, octoprint ignored the cancel gcode?!
> Can you share the serial, so we can see what it sent?

Pasted below:
Changing monitoring state from "Printing" to "Cancelling"
Recv: ok
Send: N24 M108*28
Recv: ok
Send: N25 M117 0% L=0/370*92
[...]
Recv: ok
Send: N26 M410  //quickstop_stepper*69
Recv: ok
Send: N27 M104 T0 S0*20
Recv: ok
Send: //probably M81?
Send: N28 M140 S0*95
Recv: echo:Unknown command: "//probably M81?"
Recv: ok
Recv: ok
Send: N29 M106 S0*92
Send: N30 M108*25
Recv: ok
Recv: ok
`
@jojolll Interesting, is this on ender 3 v2? your issue is different a bit, I have no trouble moving the Y axis, only the Z axis, and i dont have it after a successful print, only after cancellation

**Comment by jojolll** [comment]
> @jojolll Interesting, is this on ender 3 v2? your issue is different a bit, I have no trouble moving the Y axis, only the Z axis, and i dont have it after a successful print, only after cancellation

Yes it is also on an Ender 3 V2! And I noticed that it is not systematic on a successful print, maybe I had cancelled a print before ? 

In any case the problems seem to be close ! And I tried quickly but the X axis doesn't seem to trigger any problems.

EDIT : Now that I see your answer, I too have seen some "Unknown Commands" on my serial interface.

**Comment by thepixelabs** [comment]
@jojolll the unknown commands are only there as i was requested to change the octoprint cancel messages
My issues are also not from moving the X axis, but the Z axis.

**Comment by thepixelabs** [comment]
I never tried this before, i just confirmed, this issue also happens when moving X axis straight after cancel print.
I just had all my filament thrown out on this test.. and i dont even think i've set the x axis to move that much..

**Comment by thepixelabs** [comment]
@signetica you pitched in on #19644 and it just closed, maybe you can pitch in here as well

**Comment by andersp5** [comment]
Have had  a similar problem but with Y axis, I moved the bed from zero by 100 to bring bed to the front and the Extruder ejected the filament at great speed. Also if you put a value of more than -100 in to extract the filament it will not work put -50 in and it does and then sometimes even with a negative value it goes forward instead of backwards, this only happens on V2.0.7.2 not V2.0.6.0.

**Comment by CRCinAU** [comment]
I've still had a report or two around this issue after October - was there any suggestions on this? Is something doing an absolute move when it should be doing a relative move?

**Comment by thinkyhead** [comment]
Unfortunately "a report or two around this" is not enough data to proceed upon. Please bring more data exhibiting the issue in a reproducible form, based on the current codebase.

**Comment by CRCinAU** [comment]
The latest report was with bugfix-2.0.x dated 2020-12-23 - report was:

> After canceling a print and then using the "move z" command in the prepare menu, it ejects all the filament as well as moving the z axis.

What specifics do you want to be able to be provided to assist? I can attempt to get more info if I know what you're looking for...

EDIT: I would guess it would be this code path in the DWIN code?
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/dwin/e3v2/dwin.cpp#L1205

But also, this looks strange to me - I'm not sure why it treats E differently? I'm guessing its trying to set to relative so E moves will always start at 0 and be a +/- movement instead of absolute?
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/dwin/e3v2/dwin.cpp#L2326

**Comment by andersp5** [comment]
I have not tried the latest bug fix dated 2020-12-23 are you perhaps indicating this may have fixed it?

If it hasn’t,  I will try and give you exactly what happens in more detail, the sequence of operation that causes it, but this will now have to be in the New year, if that’s OK then you may be better able to help with this.

Thanks

Sent from Mail for Windows 10

**Comment by Syntax-Er** [comment]
Have experienced this problem at least 3 times in last week, was unaware why my printers bowden tube had clogged multiple times. Had to replace the tube each time which gets expensive using Capricorn tube. I finally caught the extruder moving backwards as the printer returned home at the beginning of a new print, but after a cancelled print.

I cancelled the print from the Octoprint web GUI, and then started a new print with hotend in the Z position from which the cancelled print was stopped. After reaching temp, the hotend starts to move back to the home position 0,0,0, and the extruder is retracting filament the entire time.

The first couple times it happened I was using firmware from 11-18-20, but since updating the printer to a firmware from 12-24 I am still experiencing the issue. I just caught it doing it again a few minutes ago.

Im using
Marlin Firmware: 12-24-20
Printer: Ender 3 V2
Controller: Creality 4.2.2 board
Slicer: Cura 4.8
Server: Octoprint 1.5.1
Mods: BLTouch 3.1 (connected to 5 pin header)

**Comment by thinkyhead** [comment]
@Syntax-Er — Does your file's Starting G-code (from Cura) do anything to reset the E position to 0, such as a `G92 E0` or a `G28`? If you don't include this then the printer will simply continue from the last state it was in.

**Comment by Syntax-Er** [comment]
@thinkyhead yes.. it resets the E to 0 twice.. once before it purges and again before it moves to start the print.

; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder
G28 ; Home all axes
M420 S1 Z2 ; Enable Leveling
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z0.3 F1000.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1000.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish

**Comment by Syntax-Er** [comment]
I managed to catch it doing it again.. This time I cancelled a print... and then manually moved the hotend to Z-200 using the LCD controller on the printer.. as it was traveling upward the extruder was retracting.. I video'd it as well..

https://www.youtube.com/watch?v=adrWItihqE4

**Comment by rhapsodyv** [comment]
> I managed to catch it doing it again.. This time I cancelled a print... and then manually moved the hotend to Z-200 using the LCD controller on the printer.. as it was traveling upward the extruder was retracting.. I video'd it as well..
> 
> 
> 
> https://www.youtube.com/watch?v=adrWItihqE4

What is you cancel gcode on octo?
It should have `G28 XY` to reset marlin to a good state.

**Comment by Syntax-Er** [comment]
> What is you cancel gcode on octo?
> It should have `G28 XY` to reset marlin to a good state.

@rhapsodyv I just have the default cancel code Octoprint comes preconfigured with..
; disable motors
M84

;disable all heaters
{% snippet 'disable_hotends' %}
{% snippet 'disable_bed' %}
;disable fan
M106 S0

**Comment by Syntax-Er** [comment]
@rhapsodyv I added
G28 XY ; Home X&Y
G1 Y200 ; Move Bed Forward For Print Removal
At the end of the cancel script, restarted Octoprint after the change, ran a print, cancelled via Octoprint, and then moved the Z to 100 and the extruder stayed still this time.. Going to try it with just the G28 X; and G1 Y200
and see if it continues to fix the issue..


Update: Problem came back this morning while trying to fix extrusion issues, I raised the nozzle to extrude some filament, and nothing came out.. looked and saw 5 inches of filament with gear marks hanging out the side the extruder..

**Comment by thinkyhead** [comment]
It's interesting. If you execute a move with G1 instead of doing a manual move from the LCD do you also see extruder movement?

**Comment by rhapsodyv** [comment]
Another interesting test is add `G92 E0` to your cancel gcode on octo print, and see if the problem happens too.

**Comment by CRCinAU** [comment]
Sorry, as I posted earlier, doesn't this `G92 E0` run on all LCD movement requests?

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/dwin/e3v2/dwin.cpp#L2326

**Comment by rhapsodyv** [comment]
> Sorry, as I posted earlier, doesn't this `G92 E0` run on all LCD movement requests?
> 
> https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/dwin/e3v2/dwin.cpp#L2326

I don’t know how the code paths are executed in this code. I don’t have this screen.

The purpose of the test is just to be sure that the `G92 E0` is executed.

**Comment by andersp5** [comment]
As promised, downloaded and updated the printer firmware with the latest bugfix 2.0 and so far it appears to have fixed my problem with the extruder. I hope this helps.

**Comment by Bluelinegecko** [comment]
Just checked with the latest bugfix on 1/5/2021 on an Ender3 V2. Ran a short test print from the SD card. Cancelled using the DWIN controller to stop the print. When I moved the Z axis up afterwards it still retracted the filament approximately the same distance.

**Comment by thinkyhead** [comment]
> When I moved the Z axis up afterwards

Did you use the move menu or did you send a G1 command? These follow different code paths.

**Comment by Bluelinegecko** [comment]
> > When I moved the Z axis up afterwards
> 
> Did you use the move menu or did you send a G1 command? These follow different code paths.

I used the move menu on the DWIN display. Thanks for looking into this thinkyhead

**Comment by Syntax-Er** [comment]
thinkyhead
50% of the time the issue occurs Im using the LCD to move the hotend.. the other 50% its retracting during the homing procedure at the beginning of a print. 

UPDATE
I reflashed my firmware a few nights ago, and before even printing once, and having completely powered the printer off after the flash.. I turned the printer on, and moved the hotend X and then Z, and the extruder retracted all the filament out at a high speed.. So that kinda blew my theory it was cancelled print related.. so now I have no idea..

**Comment by CRCinAU** [comment]
Can we get an exact step list?

I just updated to 20210107 bugfix, then went:
1) Control -> Temperature -> Hotend temp and set to 190
2) Prepare -> Auto home
3) Control -> Move -> X set to 20
4) Z to 50 (no E movement)
5) X set to 200
6) Z to 100 (no E movement)

As such, the above didn't reproduce the fault. Can you document a reproducible scenario?

EDIT: But screwing around - I just managed to make the E motor rewind by moving the X from 130 -> 100...... Interesting....

**Comment by CRCinAU** [comment]
I notice there's certainly an issue with E positioning - as if you set an E value, go back a menu, then set a different E value - it acts like they are absolute requests - not relative - so setting E10, back, set E-10 will move backwards 20mm...

I can only assume something like this is happening - but at a faster move rate when something else triggers off....

**Comment by CRCinAU** [comment]
@thinkyhead / @sjasonsmith (or whoever) - when a combined X / E movement happens - say it has to move 30mm on X, but 100 on E, that'll speed up the E movement, right?

I wonder if the root cause here is that the extruder is being treated as relative movement by the menu - but is in absolute mode when trying to do the moves - hence a 50mm movement of X / Y / Z could cause whatever E value is to go to zero if prompted by that screen...

Is this consistent with expected behaviours?

ie:
1) Print starts
2) Print continues and causes E counter to increase
3) Menu based Move sets E0 - which causes the E motor to unwind everything that's been already printed.

**Comment by ct16k** [comment]
I have an Ender 3 V2 with Creality 4.2.2 board, and it's very easy to reproduce for me with the display (not using octoprint at all, only printing from SD card):
1. Cancel a print
2. Auto-home from Prepare menu

The extruder will move backwards for the same amount of time as the Z takes to go from its current position to 0.

I am currently at ba2cadb47934fa83f576aece2c45f1b6cb5829cf on the `bugfix-2.0.x` branch.

**Comment by Bluelinegecko** [comment]
> Is this consistent with expected behaviours?
> 
> ie:
> 
> 1. Print starts
> 2. Print continues and causes E counter to increase
> 3. Menu based Move sets E0 - which causes the E motor to unwind everything that's been already printed.

That could be. I only tested it a few times but everyone seems to report that the extruder move is always a retraction as far as I have read.

 The DWIN menus are definitely a source of frustration and I know thinkyhead and others have some alpha/beta versions out the including an attempt to replicate the standard MarlinUI on the display. Some of the macros programmed into the  Creality DWIN like turning off the heaters when one pauses a print from the menu, are annoying. A lack of flow tuning and other "standard" menu items are equally disappointing. I have no doubt an eventual Marlin Team UI for this display will be thousands of times better than Creality's effort.

**Comment by Bluelinegecko** [comment]
> I notice there's certainly an issue with E positioning - as if you set an E value, go back a menu, then set a different E value - it acts like they are absolute requests - not relative - so setting E10, back, set E-10 will move backwards 20mm...
> 
> I can only assume something like this is happening - but at a faster move rate when something else triggers off....

I can confirm this as well. I just tested without even running a print. Happens for me when moving any axis not just the Z.

Steps to reproduce:
1. Turn on printer.
2. Heat hotend up beyond minimum extrusion temperature.
2. Move Extruder +40mm using Prepare-Move menu
3. Go back to previous menu
4. Return to Move Axis menu
5. Move either X,Y,or Z axis and Extruder retracts -40

The total distance appears to be to total of the last Extruder move, but as it is synchronized to the move on the X,Y,Z axis the speed of the extruder move varies. Extruder will reverse the previous movement on the next move command. If I retract the extruder 20 mm and return to the menu it will advance 20mm on the next move of any axis. If I advance the filament 20mm and return to the menu it will retract 20mm on the next move. Subsequent moves have no effect on the E axis until the E axis is moved again and one exits/returns to the return menu.

I also notice that anytime I go back a menu and return, the Extruder position is reset to 0 on the screen, where as the X,Y,Z positions remain at the value they were at last.  On my other printers using the Reprap discount full graphic controller, i believe the extruder move menu always shows the current coordinates when returning to previous screens until the E is zeroed out when starting a print, homing, etc.

**Comment by abdebadie** [comment]
Le jeu. 7 jan. 2021 à 08:39, Bluelinegecko <notifications@github.com> a
écrit :

**Comment by Syntax-Er** [comment]
Tonight I had a first layer that didnt extrude properly.. I cancelled the print via Octoprint.. I don't remember exactly what I did next, but it caused the extruder to retract a little filament slowly.. it appeared to be about the same amount of filament it had tried to extrude before I cancelled the print.. The next thing I did  was I press the extruder lever, feed the half inch or so of filament back into the hotend, and noticed the LCD was reading the E position as 0.00 at this point.. I dialed it up to 5.00 and pressed the button expecting to prime the hotend again, but instead it started moving in reverse again.. this time more than 5mm.. as if the lcd was reading 0 but the printer thought the count was still at 20 or something..  it began retracting a good amount of filament very slowly.. I waited a few seconds but eventually killed the power to the printer, at which point I had to remove the bowden tube again, and slowly pull the clog all the way thru.. got lucky this time, it was a brand new capricorn tube and I was able to get the clog thru without breaking the filament..

But this is pretty much a constant thing, after a cancelled print, using the LCD to move any of the steps including the extruder can cause it to retract.

**Comment by Bluelinegecko** [comment]
I think @CRCinAU is onto something when he said;

> I wonder if the root cause here is that the extruder is being treated as relative movement by the menu - but is in absolute mode when trying to do the moves - hence a 50mm movement of X / Y / Z could cause whatever E value is to go to zero if prompted by that screen...
``
In my testing in my previous post I showed that this happens even when first powering the printer on and not just at the end of prints. The reason it only seems to be detected at the end of the prints is that the nozzle is warmed up. If the nozzle is too cold, Marlin doesn't move the extruders, but if you heat the nozzle you will see it constantly reverse the previous extruder move the first time you enter the Prepare-move menu and move any axis.

I've been trying to dig through the code and find the bug, but I'm not real familiar with the code and it looks like the code for the "standard" marlin UI is a bit different so there isn't much for me to compare it to. Hopefully someone in here can locate it and offer a possible fix.

**Comment by Bluelinegecko** [comment]
I think @CRCinAU is onto something when he said;

` I wonder if the root cause here is that the extruder is being treated as relative movement by the menu - but is in absolute mode when trying to do the moves - hence a 50mm movement of X / Y / Z could cause whatever E value is to go to zero if prompted by that screen...`

In my testing in my previous post I showed that this happens even when first powering the printer on and not just at the end of prints. The reason it only seems to be detected at the end of the prints is that the nozzle is warmed up. If the nozzle is too cold, Marlin doesn't move the extruders, but if you heat the nozzle you will see it constantly reverse the previous extruder move the first time you enter the Prepare-move menu and move any axis.

I've been trying to dig through the code and find the bug, but I'm not real familiar with the code and it looks like the code for the "standard" marlin UI is a bit different so there isn't much for me to compare it to. Hopefully someone in here can locate it and offer a possible fix.

**Comment by omgsh** [comment]
How is it possible this has been an issue since October?

**Comment by ellensp** [comment]
@omgsh Some maths...  very approximate. 500+ issues and feature requests,  1 full time programmer/administrator. 2-5 professional programmers (with real jobs and other obligations), 5-20 part time amateurs doing their best. All but one are volunteers.   See the issue?   Lean to code and help. Please don't waste out time on disparaging remarks.

**Comment by omgsh** [comment]
> @omgsh Some maths... very approximate. 500+ issues and feature requests, 1 full time programmer/administrator. 2-5 professional programmers (with real jobs and other obligations), 5-20 part time amateurs doing their best. All but one are volunteers. See the issue? Learn to code and help. Please don't waste our time on disparaging remarks.

Please don't reprimand me for something you assumed I intended to mean. That would be like me congratulating you for doing a good job, See the issue?

If you don't want to answer the question, you can allow someone who actually wants to be here to step into your role.

**Comment by CRCinAU** [comment]
Those who offer the least always make the most noise....

**Comment by omgsh** [comment]
> Those who offer the least always make the most noise....

I'm not saying you are a troll, this is just very trollish. Do you live under a bridge? Do you have little to do and often find yourself spending time putting your opinion in on things where no one asked you to? Or, Are you hoping someone here will find you witty enough to let you eat their box? The reality is, you go out of your way to run your mouth on the internet because you can't deal with the fact that you would never do so in person. ='(

**Comment by sjasonsmith** [comment]
I’ve hidden several of the recent posts to avoid distracting from the actual bug discussion.

**Comment by Bluelinegecko** [comment]
Well, I think I found the origin of the problem with the Ender3 V2 reversing the last extruder move  (only if the nozzle is above minimum temp) when the Prepare-move menu is used to move any other axis

I believe it is caused by line 2325 in dwin.ccp https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/dwin/e3v2/dwin.cpp#L2325

Specifically it seems to be caused by;

                      current_position.e = HMI_ValueStruct.Move_E_scale = 0;

where it is constantly resetting the extruder's current position to 0.

By eliminating the  "=0" at the end so it reads;

                  current_position.e = HMI_ValueStruct.Move_E_scale;

the printer no longer reverses the previous extruder move anytime you enter the prepare-move menu and move aother axis. And by changing the following line (2326) to read;

          DWIN_Draw_Signed_Float(font8x16, Color_Bg_Black, 3, 1, 216, MBASE(4), current_position.e * MINUNITMULT / 10);

the menu will show the current extruder position when you first enter the prepare-move menu, but it is reset to 0 anytime you click on the move E menu. I suspect that is from line 2324, which I don't know if we really need in the code. 

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/dwin/e3v2/dwin.cpp#L2324

I hope one of the main developers can look this information over and verify if it will work. I don't know if it may cause unintended consequences. I am not a programmer and only have a very basic understanding of C++ and other languages. I was trying to compare the code to the code used in the standard marlin UI used on displays like the Reprap Discount Full graphic controller, but the numerous different functions/variables used in that code to adapt it to so many different displays made it difficult for me to follow. This seems to be working on the Ender3V2 I am using but I haven't done extensive testing yet.

**Comment by sjasonsmith** [comment]
I'm about to post a PR.

**Comment by chevyman142000** [comment]
I would love to help, but I'm not super comfortable compiling firmware. If there is anything I can do to help, please let me know. Thanks!

**Comment by Bluelinegecko** [comment]
Thanks, I'm really not familiar with the process on Github so I'd definitely prefer someone else take a look at it to verify it and also see if we still need line 2324;

          queue.inject_P(PSTR("G92 E0"));

in there as well. My other printers with the full graphic smart controller never bother resetting the extruder position in the move menu but I don't know if that is still needed with the issues others were having.

I also think line 2326 could be simplified as;

> DWIN_Draw_Signed_Float(font8x16, Color_Bg_Black, 3, 1, 216, MBASE(4), current_position.e

it looks like it reports the correct value without having to multiply it by MINUNITMULT (which has a value of 10) and then redivide it by 10.

**Comment by rhapsodyv** [comment]
Sometime ago a posted a branch to force `G92 E0`, right before that assignments to zero. Some has tested and said it didn't solve the issue...

**Comment by sjasonsmith** [comment]
I'm not sure why the G92 doesn't work, but replacing it with a different call to update the planner position seems to resolve the issue.

I think it is best to continue to reset the extruder to 0 when doing manual moves. X/Y/Z have finite bounds, but the extruder might have very large values depending on previous printer activity.

Please test the change I posted, and reply to the PR whether it works for you or not.

**Comment by Bluelinegecko** [comment]
> I think it is best to continue to reset the extruder to 0 when doing manual moves. X/Y/Z have finite bounds, but the extruder might have very large values depending on previous printer activity.

I don't see the point of this honestly. That is not the normal behavior when using the "standard" Marlin UI that has been used on countless printers for years now. The "PREVENT_LENGTHY_EXTRUDE" function if enabled should prevent any major issues when manually jogging the extruder. While the MarlinUI code is really confusing to someone like me not familiar with it, I really think we should aim to replicate the same behavior across displays when using MarlinFW.

**Comment by sjasonsmith** [comment]
Honestly, I don't really care either way. I don't use this display anyway. I fixed the immediate bug without changing any of the expected behavior.

**Comment by sjasonsmith** [comment]
Actually, I just tested with a RepRapDiscount Full Graphics display, and it _does_ reset E to 0.0 each time I start a new move.

**Comment by Bluelinegecko** [comment]
I'm getting ready to upload your fix and see if it works for me. I thank you for taking the time to look into this. I'm not a programmer by trade and while I am familiar with compiling Marlin firmware, a lot of the activity "under the hood" is still foreign to me. It doesn't matter to me either way as well, and I know Thinkyhead has started a Alpha build on porting the standard marlin UI fucntions to the DWIN display so it might eventually make no difference. I just think most people would like to expect the same behavior regardless of the displays they use. 

> Actually, I just tested with a RepRapDiscount Full Graphics display, and it does reset E to 0.0 each time I start a new move.

Both my printers with RepRapDiscount Full Graphics displays show the Extruder at 0 the first time I enter the prepare-move screen, but after that maintain the relative coordinates no matter how many times I exit and return to the menu. They only resets to 0 when ending a print or rebooting the printer.

**Comment by sjasonsmith** [comment]
> They only resets to 0 when ending a print or rebooting the printer.

I don't know why we are seeing different behavior. Maybe there is a config option somewhere we have different.
That was on a printer which I just updated to the latest `bugfix-2.0.x` changes today.

**Comment by Bluelinegecko** [comment]
> Maybe there is a config option somewhere we have different.

Possibly. My other 2 printers have an older version of marlin on them but the Extruder position has never constantly reset to 0 every time one enters the Prepare-move menu, so if that is the expected behavior it is new to me.

Just uploaded the firmware with your fix... It seems to have solved the inadvertent extruder movement when jogging other Axis on this Ender3V2 I'm testing. Hopefully others will test it and give their blessing as well. Thanks again for coding it the "right way" :)

**Comment by harbinger1080** [comment]
I was having the exact same problem-- extruder would eject a ton of filament when I moved the Z after a print.

Applied your changes this afternoon and I cannot reproduce the problem any longer.

**Comment by thepixelabs** [comment]
@sjasonsmith Thx for this.. i'll try updating to this firmware in the next 2 days

**Comment by dimonoid** [comment]
I solved this by adding this
`G92 E0 ; Reset Extruder`
at the end after each print in Cura.
