### ISSUE TITLE
[issue] (Platformio update.cbd file did some wack stuff to Qidi X-one 2 printer)

### ISSUE THREAD

**Issue by clinde04** [MarlinFirmware/Marlin#20003]
The chitu v6 board option built fine, but when I flashed it on my printer, it just went dark and has a soft fan noise.

### Configuration Files
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5478162/Configuration.zip)

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. [Put update.cbd onto SD card]
2. [Put the sd card into the powered off printer]
3. [Booted up the printer]

**Expected behavior:**

It beeps a little and then stops so I can restart the printer and have marlin firmware on my printer.

**Actual behavior:**

It beeped and then just all the lights turned off and a fan just blows softly now. LCD is off.

**Comment by rhapsodyv** [comment]
I don't think we support Qidi printers... All chitu work was done using TronXY printers.

**Comment by clinde04** [comment]
Is there any known way that it could possibly work though?

**Comment by rhapsodyv** [comment]
I guess it will only happen when a Qidi owner make marlin working on it...

**Comment by clinde04** [comment]
Ok. Is there anything I could do to help with development, like check all the pins or test updates for it? (That is if you even wanted to make marlin compatible with Qidi printers)

**Comment by rhapsodyv** [comment]
If marlin even had booted... But if marlin is not booting, we many need a very hard work.

**Comment by clinde04** [comment]
Oh. yeah marlin did not boot. How could we fix this.

**Comment by thisiskeithb** [comment]
Which LCD/TFT do these printer use? I don't see one enabled in your config.

Also, your `CONFIGURATION_H_VERSION` is `020007`, so please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by clinde04** [comment]
As for the lcd I don't now right now. And I will try that in just a sec

**Comment by rhapsodyv** [comment]
try enabling: 
```
#define TFT_TRONXY_X5SA
#define TFT_COLOR_UI
#define TOUCH_SCREEN
```

**Comment by thisiskeithb** [comment]
How did you confirm that Marlin didn't boot? Can you connect via usb/serial (OctoPrint/Pronterface, etc.) and check if you get any serial output?

**Comment by clinde04** [comment]
ok one sec.

**Comment by clinde04** [comment]
It booted up into the marlin screen now! But when I try to change the fans it does not do anything I could notice.

**Comment by clinde04** [comment]
Also, octoprint is stuck at:
Offline (Error: No more candidates to test, and no working port/baudrate combination detected.)

**Comment by rhapsodyv** [comment]
I think we can start with the X5SA example from Marlin: https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Tronxy/X5SA

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
