### ISSUE TITLE
[BUG] Hotend temp reading negative 

### ISSUE THREAD

**Issue by clinde04** [MarlinFirmware/Marlin#20016]
The hotend temp is reading negative, however the numbers are correct, there is just a "-" before the number and it tells me MINTEMP error.

### Configuration Files
[config.zip](https://github.com/MarlinFirmware/Marlin/files/5482645/config.zip)

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

**Comment by boelle** [comment]
checked that everything is connected correctly? what thermistor do you have?

**Comment by clinde04** [comment]
Everything is connected properly. As for what thermistor, no clue. I have the qidi x-one2 printer and I can't seem to figure out what thermistor it has. Everything else is working fine though.

**Comment by boelle** [comment]
i know what if you connect a thermocouple wrong it shows - in front of temp
but if its a china printer i bet its just the cheapest stuff that works at shipping time

**Comment by clinde04** [comment]
I can try reversing the thermocouple if that would work.

**Comment by boelle** [comment]
will only work if it is a thermocouple, a thermistor is just a resistor and it will not make a difference if you reverse it

**Comment by clinde04** [comment]
How would I tell the difference

**Comment by clinde04** [comment]
I just looked at the cables and it looks like there are two wires that look like they're thermocouples.

**Comment by clinde04** [comment]
just switched them, it did nothing. Any suggestions
