### ISSUE TITLE
[BUG] Underextrusion with tmc 2209, stealthchop

### ISSUE THREAD

**Issue by Liger0** [MarlinFirmware/Marlin#20018]
### Bug Description

I have tried for days to get extrusion to work, but I am totally unable to
I have a cr10s (stock motor), BMG (clone), bowden, all metal chimera. 
All the grub screws are secured, the bowden is inserted all the way in, there are clips to avoid the fittings to move.
All goes fine until there are several retractions for supports, where the motor gets toasty and misses steps.  
Retraction is only 2mm to accompany the all metal hotend and prevent clogging.
There are heatsinks on the motor (3M 9448a adhesive, still better than nothing).
 I regulated the current from the firmware: at 450 it does not extrude evenly, so it is not enough, while at 550 it extrudes fine until there are much retractions, there layers go missing, especially supports, and the extruder is extremely hot.
In cura, "retraction between supports" is enabled, combing is limited to 5mm so material loss is to exclude, the material is lost only when steps are skipped. 
I believe there is a way to see if steps are skipped in prusa firmware, but I can't find any on marlin.

### Configuration Files

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5483846/Marlin.zip)

### Steps to Reproduce

1. TMC 2209
2. Stealthchop extruder
3. 400 to 600 current
4. Scurve acceleration and Junction deviation enabled, linear advance disabled.

**Expected behavior:**

No underextrusion

**Actual behavior:**

Extreme underextrusion when retracting

#### Additional Information

[CCR10S_gcode.zip](https://github.com/MarlinFirmware/Marlin/files/5483835/CCR10S_gcode.zip)
![underextrusion ](https://user-images.githubusercontent.com/20385116/98036689-c2bbc280-1e1a-11eb-8c7f-1dd1df580f40.jpg)
![underextrusion 2 ](https://user-images.githubusercontent.com/20385116/98036692-c3545900-1e1a-11eb-8526-5c58f779c0d0.jpg)

**Comment by Pikoting** [comment]
Have you tried spreadcycle mode to print and see if the problem still occur? And is the problem only happen when retraction? There is a chance your retraction speed is too fast and the stepper driver could not handle. And also is the TMC2209 very hot when it happen? I am pretty new to Marlin and I am not sure any setting on firmware. See if that's help.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
