### ISSUE TITLE
Y and Z2 endstop don't work

### ISSUE THREAD

**Issue by Subia75** [MarlinFirmware/Marlin#20017]
Hi,
I ask for help if anyone can answer me.
I have an Anycubic I3Mega S.

**Bug Description**

I wanted to upgrade the firmware from 2.0.5 and I built marlin bugfix (2.0.7.2 version based) for my I3 mega s
I attached image, the Y and Z2 endstops don't go when I triggered them.
I configured the new one by reporting the configuration.h and configuration.adv file changes, but I don't understand why those 2 endstops don't go.
If I try to put the 2.05 back again everything works correctly.
it doesn't seem to detect the pins
I have set trigorilla_version_0 which is the my board.
I am not an expert, but I wonder if it is possible they are not declared correctly in the files:
*pins_trigorilla_14_h
*or pins_ramps_h

**Expected behavior:**

all endstops should work as in the old 2.0.5 firmware

**Actual behavior:**
only the endstop X, Z, Zprobe change state

The other changes I have is:
bltouch
TFT35
TMC2208
![endstops](https://user-images.githubusercontent.com/67789797/98020520-64371a00-1e03-11eb-8ae8-9763aad71306.jpg)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
