### ISSUE TITLE
Move documentation to website (marlinfirmware.org)

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#2002]
I got this idea of having all documentation in wiki format on the site and use github for the code only....

who has any constructive objections ?

@scotty1024 did you get my request for an account?

**Comment by Scotty1234** [comment]
I think you have the wrong person!

**Comment by boelle** [comment]
yep... it was meant for @scotty1024

**Comment by scotty1024** [comment]
Bo,

You know that combination of letters and numbers you use with an @ on the front? Move the @ to the end and add me dot com. I will get you setup via email through that address.

**Comment by boelle** [comment]
oki... did a request for a login via the page and had to figure a 50 word bio... 

but will send a mail anyways

**Comment by scotty1024** [comment]
What? Should have been a 100,000 word bio!

I sent you a ssh account. If you need a wiki web account I will need to set that up too.

**Comment by AnHardt** [comment]
I'm not sure if this is the way to go.
With this restrictive polity the idea of an wiki is not matched anymore.
I expect more contributions on the GitHub-Wiki.

**Comment by boelle** [comment]
the goal is to have all documentation in one place and not a mix between github and reprap.org

and everyone that wants to contribute can get an pass/user from @scotty1024 

it was the whole idea behind getting the domain name in the first place

**Comment by boelle** [comment]
see you all tonight on hangout
