### ISSUE TITLE
[FR] Add support for Qidi thermocouples 

### ISSUE THREAD

**Issue by awesomeguy17123** [MarlinFirmware/Marlin#20031]
### Description

My QIDI X-one2's thermocouple is not supported. It would be cool to see it be supported.

**Comment by ellensp** [comment]
How do you know its not supported, what is it?
"QIDI X-one2" is a machine brand

**Comment by awesomeguy17123** [comment]
I have tried every thermistor/thermocouple. none have worked

**Comment by ellensp** [comment]
According to a e-bay listing the controller is this https://i.ebayimg.com/images/g/Fv0AAOSweP9eTxlD/s-l1600.jpg  but cant find any details, like how it talks to a thermocouple   Is probably a chitu3d variant

**Comment by awesomeguy17123** [comment]
Yes. so for the board, I selected chitu3d_v5 and it seems to work. All but the thermocouple works just fine, even the heated bed thermistor works set to 1.

**Comment by awesomeguy17123** [comment]
also, this might be a chitu V3.9. Here is the manual with all the specs of it.
[Chitu V3.9 users manual.pdf](https://github.com/MarlinFirmware/Marlin/files/5496179/Chitu.V3.9.users.manual.pdf)

**Comment by Grogyan** [comment]
Temperature Sensor Interface: 3 paths of 100K NTC (thermistor)
2 paths of MAX6675（thermocouple）

from that manual.

You need to ensure that SD is enabled, and choose which SPI port the MAX6675 is tied to,
If for the onboard storage, then in config_adv, you need to set onboard for the SD card.

**Comment by awesomeguy17123** [comment]
How would I find what SPI port it is tied to. I have just enabled SD Support. Also, now I have successfully built it using the MAX6675 but it tells be MAXTEMP ERROR, PLEASE RESET when I boot it up. Does that mean I selected the wrong spi port?

**Comment by Grogyan** [comment]
@awesomeguy17123 Use a multimeter to probe the max6675 MISO, SCK and CS pins, to the micro.
The datasheet for which will tell you which pin is what.

**Comment by awesomeguy17123** [comment]
Ok i'll try that real quick

**Comment by awesomeguy17123** [comment]
I'm not getting any readings other than 0. Does it have to be powered on or am I touching the wrong pins?

**Comment by awesomeguy17123** [comment]
[photos.zip](https://github.com/MarlinFirmware/Marlin/files/5497397/photos.zip)
Here are pictures of the mainboard. Hope this helps in some way.

**Comment by ellensp** [comment]
Cant open your file photos.zip. Zip archive seems truncated.

**Comment by awesomeguy17123** [comment]
[Photos(Working).zip](https://github.com/MarlinFirmware/Marlin/files/5501595/Photos.Working.zip)
sorry about that. It must have stopped mid-zip.

**Comment by clinde04** [comment]
I've decided to purchase a new mainboard and some other supplies. Thank you for all your help though.

**Comment by awesomeguy17123** [comment]
I've decided to purchase a new mainboard and some other supplies. Thank you for all the help though.
