### ISSUE TITLE
[BUG or FR ] SWITCHING_EXTRUDER - disabled motor extruders

### ISSUE THREAD

**Issue by DrumClock** [MarlinFirmware/Marlin#20045]
When using the `SWITCHING_EXTRUDER` function.

The extruder motors E1,E2,E3 do not work properly.
After a few seconds, E1, E2 turn off and E3 does not rotate at all.

I don't know if it's a given configuration:

`#define EXTRUDERS 4` and `#define HOTENDS 4`   (for separate hotends )  

if I change `#define EXTRUDERS 4` and `#define HOTENDS 1` it's the same.   (for 4-IN-1-OUT hotends)

configurations:
https://github.com/DrumClock/Marlin/tree/GTR-2xMFG-V7

**Comment by DrumClock** [comment]
If it disables the `#elif EXTRUDERS! = 2` condition in **SanityCheck.h**
E-STEPPER for E1 works properly.

```
#if ENABLED (SWITCHING_NOZZLE)
   #if ENABLED (DUAL_X_CARRIAGE)
     #error "SWITCHING_NOZZLE and DUAL_X_CARRIAGE are incompatible."
   #elif ENABLED (SINGLENOZZLE)
     #error "SWITCHING_NOZZLE and SINGLENOZZLE are incompatible."
   // # elif EXTRUDERS! = 2
     #error "SWITCHING_NOZZLE requires exactly 2 EXTRUDERS."
   #elif NUM_SERVOS <1
     #error "SWITCHING_NOZZLE requires NUM_SERVOS> = 1."
   #endif
```

**Comment by ellensp** [comment]
These are not bugs, you trying to make marlin do things it was not designed to do. This is a feature request.

Ie marlin does not know how to have two switched 2-IN-1-OUT extruders.

**Comment by DrumClock** [comment]
OK, thanks

**Comment by ellensp** [comment]
You didn't have to close it... maybe someone will like this idea and implement it.   Just change Subject to FR not BUG.

**Comment by DrumClock** [comment]
Hi @ellensp 
Never mind, I have FR https://github.com/MarlinFirmware/Marlin/issues/18429
and he would solve everything I have a problem with here,
Unfortunately, I don't know if anyone is working on it - that's a disadvantage to Gihub, not feedback

**Comment by DrumClock** [comment]
Hi @ellensp
This is rather worse with this problem  ...... https://github.com/MarlinFirmware/Marlin/issues/19178

**Comment by DrumClock** [comment]
Hi @ellensp
This is rather worse with this problem  ...... https://github.com/MarlinFirmware/Marlin/issues/19178

**Comment by DrumClock** [comment]
I tried this:
in ..... \ Marlin \ src \ inc \ **SanityCheck.h** I disabled (so it can be compiled)

```
#if ENABLED (SWITCHING_NOZZLE)
  #if ENABLED (DUAL_X_CARRIAGE)
    #error "SWITCHING_NOZZLE and DUAL_X_CARRIAGE are incompatible."
  #elif ENABLED (SINGLENOZZLE)
    #error "SWITCHING_NOZZLE and SINGLENOZZLE are incompatible."
  #elif EXTRUDERS! = 2
    // # error "SWITCHING_NOZZLE requires exactly 2 EXTRUDERS."
  #elif NUM_SERVOS <1
    #error "SWITCHING_NOZZLE requires NUM_SERVOS> = 1."
  #endif

```
then I **enabled SWITCHING_NOZZLE** and set the unused **servo0** (because I don't switch nozzles)

```
#define SWITCHING_NOZZLE
#if ENABLED (SWITCHING_NOZZLE)
  #define SWITCHING_NOZZLE_SERVO_NR 0
  // # define SWITCHING_NOZZLE_E1_SERVO_NR 2 // If two servos are used, the index of the second
  #define SWITCHING_NOZZLE_SERVO_ANGLES {45, 135} // Angles for E0, E1 (single servo) or lowered / raised (dual servo)
#endif
```


**After these modifications, both motors for extruders and servos for E0-E3 switched and worked properly.**

Perhaps this will help eliminate the bug or add FW.

I am very happy to tested before PR ...... just write me what to change here.

**Comment by ElectroFlux-SS** [comment]
Try disabling the following line:
#define DISABLE_INACTIVE_EXTRUDER

**Comment by DrumClock** [comment]
Hi @ElectroFlux-SS
Yes this setting works.
`// #define DISABLE_INACTIVE_EXTRUDER`
