### ISSUE TITLE
[BUG] Limit switches Y and Z2 do not work when changing standard printer display

### ISSUE THREAD

**Issue by Subia75** [MarlinFirmware/Marlin#20052]
### Bug Description

I have anycubic I3 mega S printer with:
bltouch 
TFT35 display
TMC2208

I upgrade the firmware from 2.0.5 and I built marlin bugfix (2.0.7.2 version based).
I'm sure I have configured configuration.h and configuration.adv files correctly.
But the Y and Z2 endstops don't go.
i tryed to I triggered them manual but don't change state.

Compared to the original printer I have a different display, 
so I commented these lines in the "configuration.h" file
"#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
instead of
// # define ANYCUBIC_LCD_I3MEGA

### Configuration Files

I attach my configuration.h and configuration.adv files.
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5501046/configuration.zip)

I am also attaching the pins_ramps.h file with the changes to make all the Limit Switches work
[pins_ramps.zip](https://github.com/MarlinFirmware/Marlin/files/5501045/pins_ramps.zip)

I attach the image, with the changes on pins_ramps.h (on the right) compared to the original one (on the left)
![pins_RAMPS](https://user-images.githubusercontent.com/67789797/98389943-06017580-2055-11eb-8354-2d7a09729fe4.jpg)

### Steps to Reproduce

I attach the image, with the repport of the limit switches when I query M119
![endstops](https://user-images.githubusercontent.com/67789797/98361980-c6bf2e80-202c-11eb-9721-31714195d6ae.jpg)

**Expected behavior:**

when interrogating with M119 i expect i should see all limit switches triggered when pressed.

**Actual behavior:**

when the query with M119 happens that the limit switches Y and Z2 do not respond to the commands
For information this PIN assignment was not working already from release 2.0.6 onwards but I had not investigated the problem and therefore I was left with 2.0.5

#### Additional Information

The pins used by the limit switches are:
x_min_pin   3
y_min_pin   42
z_min_pin   18
x_max_pin   43
y_min_probe_pin  2

I solved by editing pins_ramps.h file which was easy for me, but I think I need to do this again with future marlin updates.

I still don't know enough about programming so I hypothesize a solution.
 If you could add a variable to file pins_trigorilla_14.h where you declare the limit switches type
#elif EITHER REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
It could go well?

![pins_trigorilla_14](https://user-images.githubusercontent.com/67789797/98388818-8030fa80-2053-11eb-95df-443c27b4e9d4.jpg)
I hope I have explained the problem, and that it can be solved.

**Comment by ellensp** [comment]
The BOARD_TRIGORILLA_14 is notorious that their adapter boards changes the function of pins. It plugs in to end stops and exp ports and scrambles them.

If you look at the code above in pins_RAMP.h you will see 
#ifndef  this mean if the variable is not defined then do the next line. otherwise don't.

If you want to move X_MAX_PIN in ramps you simply add #define X_MAX_PIN 43 to your configuration.h (or your TRIGORILLA pin file) and pins_RAMP.h will notice X_MAX_PIN is already defined and will not define it to the default of 2.

repeat as needed.
