### ISSUE TITLE
Ramps1.6 + tmc2208 "no reconoce los driver"

### ISSUE THREAD

**Issue by wladimirC** [MarlinFirmware/Marlin#20065]
Estimados,  
espero puedan ayudarme con esto es mi primera impresora desde cero modelo corexy 

tengo una placa Arduino con ramps 1.6+ y TMC2208 tengo el siguiente error. básicamente no reconoce los TMC
estoy usando marlyn 2.0 
![20201107_131947](https://user-images.githubusercontent.com/51000817/98446454-4e27a300-20fc-11eb-972d-3fc5a5ef648c.jpg)

![20201107_131952](https://user-images.githubusercontent.com/51000817/98446447-45cf6800-20fc-11eb-9316-5cf10b83d470.jpg)

![20201107_132000](https://user-images.githubusercontent.com/51000817/98446445-41a34a80-20fc-11eb-84bb-d36f2b774bca.jpg)

13:16:19.082 : Printer reset detected - initializing
13:16:19.082 : echo:start
13:16:19.082 : Marlin bugfix-2.0.x
13:16:19.087 : echo: Last Updated: 2020-07-29 | Author: (none, default config)
13:16:19.087 : echo:Compiled: Nov  1 2020
13:16:19.090 : echo: Free Memory: 5152  PlannerBufferBytes: 1136
13:16:19.090 : echo:EEPROM version mismatch (EEPROM=? Marlin=V81)
13:16:20.037 : echo:Hardcoded Default Settings Loaded
13:16:20.332 : Testing X connection... Error: All LOW
13:16:20.352 : Testing Y connection... Error: All LOW
13:16:20.373 : Testing Z connection... Error: All LOW
13:16:20.394 : Testing E connection... Error: All LOW**
13:16:20.403 : FIRMWARE_NAME:Marlin bugfix-2.0.x (Nov  1 2020 22:36:08) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
13:16:20.404 : Cap:SERIAL_XON_XOFF:0
13:16:20.406 : Cap:BINARY_FILE_TRANSFER:0
13:16:20.406 : Cap:EEPROM:1
13:16:20.406 : Cap:VOLUMETRIC:1
13:16:20.407 : Cap:AUTOREPORT_TEMP:1
13:16:20.407 : Cap:PROGRESS:0
13:16:20.407 : Cap:PRINT_JOB:1
13:16:20.410 : Cap:AUTOLEVEL:0
13:16:20.410 : Cap:RUNOUT:0
13:16:20.410 : Cap:Z_PROBE:0
13:16:20.410 : Cap:LEVELING_DATA:0
13:16:20.410 : Cap:BUILD_PERCENT:0
13:16:20.414 : Cap:SOFTWARE_POWER:0
13:16:20.414 : Cap:TOGGLE_LIGHTS:0
13:16:20.414 : Cap:CASE_LIGHT_BRIGHTNESS:0
13:16:20.415 : Cap:EMERGENCY_PARSER:0
13:16:20.415 : Cap:PROMPT_SUPPORT:0
13:16:20.415 : Cap:SDCARD:0
13:16:20.418 : Cap:AUTOREPORT_SD_STATUS:0
13:16:20.418 : Cap:LONG_FILENAME:0
13:16:20.418 : Cap:THERMAL_PROTECTION:1
13:16:20.422 : Cap:MOTION_MODES:0
13:16:20.422 : Cap:ARCS:1
13:16:20.422 : Cap:BABYSTEPPING:0
13:16:20.422 : Cap:CHAMBER_TEMPERATURE:0
13:16:20.444 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
13:16:20.444 : echo:DEBUG:INFO,ERRORS
13:16:20.445 : echo:Unknown command: "M20"
13:16:20.445 : echo:Unknown command: "M80"
13:16:20.451 : echo:DEBUG:INFO,ERRORS

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
