### ISSUE TITLE
Link failed: multiple definition of `digipot_i2c' when configuring I2C-based DIGIPOTs with BOARD_MIGHTYBOARD_REVE

### ISSUE THREAD

**Issue by zhro** [MarlinFirmware/Marlin#20062]
### Bug Description

Failure to link when configuring I2C-based DIGIPOTs with `BOARD_MIGHTYBOARD_REVE`.

### Configuration Files

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5504837/Marlin.zip)

I downloaded the latest source. 

In Configuratio.h:

Set `#define MOTHERBOARD BOARD_MIGHTYBOARD_REVE` and `#define TEMP_SENSOR_0 -2` (required for this board to compile).

Everything at this point builds fine.

In Configuration_adv.h:

Uncommented `#define DIGIPOT_MCP4018`, set `#define DIGIPOT_I2C_NUM_CHANNELS 5`, and trimmed `DIGIPOT_I2C_MOTOR_CURRENTS` to 5 fields.

Attempted to build. Build was fine. Link failed:

```
Linking .pio\build\mega2560\firmware.elf
.pio\build\mega2560\src\src\feature\digipot\digipot_mcp4018.cpp.o (symbol from plugin): In function `DigipotI2C::set_current(unsigned char, float)':
(.text+0x0): multiple definition of `digipot_i2c'
.pio\build\mega2560\src\src\MarlinCore.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\mega2560\src\src\gcode\feature\digipot\M907-M910.cpp.o (symbol from plugin): In function `GcodeSuite::M907()':
(.text+0x0): multiple definition of `digipot_i2c'
.pio\build\mega2560\src\src\MarlinCore.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\mega2560\firmware.elf] Error 1
```

### Steps to Reproduce

Steps are in the modification of the above configuration files.

**Expected behavior:**

Expected to link.

**Actual behavior:**

Fails to link.

**Comment by ellensp** [comment]
This was fixed 24 days ago.
see https://github.com/MarlinFirmware/Marlin/commit/29356e390323ed4d405e520ad3d4d2b7efcff008

is currently only in bugfix.
