### ISSUE TITLE
Using a digital IR-Sensor with Marlin?

### ISSUE THREAD

**Issue by HartmannSa** [MarlinFirmware/Marlin#20075]
I am wondering if it is possible to use a digital IR sensor with marlin? I do not mean a thermistor or similiar, but a sensor that measures the IR waves coming from a specific point on a target. I am thinking of a sensor that uses the I2C bus, like the MLX90614:

https://www.ebay.de/i/124264816573?chn=ps&norover=1&mkevt=1&mkrid=707-153316-537668-3&mkcid=2&itemid=124264816573&targetid=4582970638677223&device=c&mktype=&googleloc=&poi=&campaignid=376515067&mkgroupid=1269936558711337&rlsatarget=pla-4582970638677223&abcId=2146003&merchantid=87778&msclkid=3cae84d401ee1fc9b4e4db7d17105887

For this sensor I even found an existing library:

https://github.com/adafruit/Adafruit-MLX90614-Library

I saw that in the configuration_adv.h there is the option of using the I2C for experimental purposes and that there are G-Code commands like

M260
M261

for sending or requesting information, but I have absolutly no idea how to adress the IR-Sensor right or what to type in in the serial monitor to get a temperature value. For me it seems that the I2C bus is primarily used for alternative LCD panels.

I hope my English is good enough, otherwise please tell me if there are any misunderstandings.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
