### ISSUE TITLE
[BUG] Not moving below Z0 when Mesh Bed Leveling is used

### ISSUE THREAD

**Issue by valiobg** [MarlinFirmware/Marlin#20072]
### Bug Description
**Can not move below Z0.**
I use Marlin bugfix 2.0.x. With version 2.0.1 mesh bed leveling (MBL) worked without problems.
I disabled the software end stops with M211 S0 and I did the MBL without problems. Then I sent M211 S1 to enable software endstops.

_**The question is : Have I to put M211 S0 in my START Gcode script in slicer in order MBL to work when printing ?**_
### Configuration Files
[
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5505970/Configuration.zip)
](url)
**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. Starting Mesh Bed Leveling from the LCD Menu.
2. Pressing move down button.

**Expected behavior:**

The pring head should go down with one step

**Actual behavior:**

Print head not moving down. It can move up, but not down below Z0.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
