### ISSUE TITLE
[FR] Direct access to preheat action

### ISSUE THREAD

**Issue by wikolii** [MarlinFirmware/Marlin#20089]
### Description

Direct preheat access from the temperature menu with material label and both temperatures shown. As seen on original prusa firmware. (no sub-menu or options for hotend and heated bed separately)
I tried adding this on my own but got lost on sub-menus and variables.

### Feature Workflow

1. Access temperature menu.
2. Select the preheat constant i want without accessing any sub-menus.
3. LCD goes back to status screen and preheating starts.

#### Additional Information

* You can see what i mean on this video (minute 11:10):
[Prusa video guide](https://youtu.be/GE-lrRbU124?t=670)

* The individual values for nozzle, bed and fans would be below the preheat constants on the same temperature menu as they are now, and the cooldown option at the bottom of the same menu.

* The preheat values would still be modified from the configuration menu.

* The preheat actual command should change whether the printer has heated bed and also adjust for multiple heaters/extruders, off course.

**Comment by vivianbp** [comment]
Implemented by #20350
