### ISSUE TITLE
[BUG] M303 does not print PID Autotune to LCD

### ISSUE THREAD

**Issue by houseofbugs** [MarlinFirmware/Marlin#20108]
Line 80 in the M303.cpp file should be ui.set_status_P not ui.set_status. Tested with 2.0.7.2 Marlin. 

See commit on my branch that fixes it: https://github.com/th3dstudio/UnifiedFirmware/commit/58630eed4f9110421dd2043422d3db852eeff5fe

This bug is also present in bugfix-2.0.x branch: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/gcode/temp/M303.cpp

![image](https://user-images.githubusercontent.com/25088191/98855567-d7ebaf00-2421-11eb-8cd5-d0b5a31c60e6.png)

**Comment by sjasonsmith** [comment]
If you already have a solution for the problem please provide it as a pull request.

**Comment by houseofbugs** [comment]
> If you already have a solution for the problem please provide it as a pull request.

I already have a fork from Marlin so making a PR is difficult. But I see @shitcreek got it handled. Thanks.
