### ISSUE TITLE
HT-ntc Type Hot End Thermister / Model: HT-NTC100

### ISSUE THREAD

**Issue by scatterbomb** [MarlinFirmware/Marlin#20125]
### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by scatterbomb** [comment]
[https://www.aliexpress.com/snapshot/0.html?spm=a2g0s.9042647.6.2.59a44c4d7Bi0g5&orderId=3007198785072639&productId=32890058144](url)
Please add to Temperature Settings/Temperature Sensors available
HT-ntc Type Hot End Thermister / Model: HT-NTC100  Rated up to 320 degrees Thermistor Model: B3950
 For  PT100 E3D V6 Heat Block Cyclops+ and Chimera+ heater hot end.

**Comment by sjasonsmith** [comment]
Closing, as the template was completely ignored and even the provided link is broken.
