### ISSUE TITLE
[BUG] STM32F1 - Some SERVO_DELAY values cause incorrect servo movement when DEACTIVATE_SERVOS_AFTER_MOVE enabled

### ISSUE THREAD

**Issue by beepee123** [MarlinFirmware/Marlin#20141]
### Bug Description

NOTE: May be related to https://github.com/MarlinFirmware/Marlin/issues/16171

If SERVO_DELAY is a multiple of 20, a final pulse of incorrect width results in servo moving out of position when deactivated.

Behavior appeared when upgrading from Creality melzi 1.1.4 board (ATMega 1284p) to Marlin/master 2.0.x (BTT SKR Mini E3 v2). Transplanted working configuration from previous firmware build

Troubleshooting steps:
 - Fully shielded servo cable
 - External power supply for servo
 - Disabled PWM fans/heaters/stepper drivers
 - Disabled DEACTIVATE_SERVOS_AFTER_MOVE - eliminates issue but introduces servo jitter/twitching
 - SERVO_DELAY of 1000 - servo moves out of position at end of delay
 - SERVO_DELAY of 1005 - servo stays in position at end of delay
 - SERVO_DELAY of 1020 - servo moves out of position at end of delay
 - Scope attached to servo pin (PA1) confirms partial pulse at end of delay.

### Configuration
Build:
- PlatformIO (default_envs = STM32F103RC_btt_USB)
- Marlin version: bugfix-2.0.x (occurs in master/2.0.x as well)

Hardware:
- Ender 3
- BTT SKR MINI E3 V2.0 
- DIY servo deployed z-probe (servo: https://www.parallax.com/product/900-00005)

### Steps to Reproduce

1. Build with hardware/software referenced above.
2. Configuration.h:
```
#define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V2_0
#define NUM_SERVOS 1
#define SERVO_DELAY { 1000 }
#define DEACTIVATE_SERVOS_AFTER_MOVE
#define Z_PROBE_SERVO_NR 0
#define Z_SERVO_ANGLES { 174, 45 }
```
**Expected behavior:**

M401 - Servo rotates to 174deg and powers down
M402 - Servo rotates to 45deg and powers down

**Actual behavior:**

M401 - Servo rotates to 174deg, then jumps out of position about -30deg and powers down
M402 - Servo rotates to 45deg, then jumps out of position about -20deg and powers down

#### Additional Information

The servo pulse interval is 20, set by TAU_MSEC in /src/HAL/STM32F1/Servo.cpp.

I was able to workaround this by changing the SERVO_DELAY, but this (similar to https://github.com/MarlinFirmware/Marlin/issues/16171) also worked:
```

diff --git a/Marlin/src/HAL/STM32F1/Servo.cpp b/Marlin/src/HAL/STM32F1/Servo.cpp
index e1ee831493..381ec9ff00 100644
--- a/Marlin/src/HAL/STM32F1/Servo.cpp
+++ b/Marlin/src/HAL/STM32F1/Servo.cpp
@@ -113,6 +113,9 @@ bool libServo::attach(const int32_t inPin, const int32_t inMinAngle, const int32
 bool libServo::detach() {
   if (!attached()) return false;
   angle = -1;
+  if ( extDigitalRead(SERVO0_PIN) == 1 ) {
+        safe_delay(3);
+  }
   servoWrite(pin, 0);
   return true;
 }

```
[config_and_patched_servocpp.zip](https://github.com/MarlinFirmware/Marlin/files/5541283/config_and_patched_servocpp.zip)

**Comment by sjasonsmith** [comment]
I am interested to find out whether the same issue exists in board using HAL/STM32 instead of HAL/STM32F1. Unfortunately your SKR E3 board doesn't work in that HAL yet.

If this problem does not exist in HAL/STM32, that provides further incentive to accelerate moving away from STM32F1.
