### ISSUE TITLE
[BUG] bltouch not does not deploy when homing

### ISSUE THREAD

**Issue by bryankenote** [MarlinFirmware/Marlin#20144]
### Bug Description
Printer: Ender 3
Main Board: BTT SKR Mini E3 v1.2
Firmware: tested on 2.0.5.4, 2.0.7.2, and bugfix-2.0.x

When I first turn on my printer, the probe is deployed and stowed twice with no issues. But my bltouch is not deploying the probe when homing or using the `M401` command.

### Configuration Files
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/5541804/configs.zip)

### Steps to Reproduce

1. Turn on printer
2. Home Z.

**Expected behavior:**
The probe should deploy when homing. 

**Actual behavior:**
The probe does not deploy and the nozzle crashes into the bed.

**Comment by ellensp** [comment]
Can you provide pictures on how its wired on board, want to see colors of the wires and positions.

**Comment by bryankenote** [comment]
Is this good enough?

![PXL_20201115_035124483 MP](https://user-images.githubusercontent.com/9691017/99162487-26fc4300-26b3-11eb-8246-3e903dc07d6d.jpg)

**Comment by ellensp** [comment]
Yes that picture is fine.

**Comment by thisiskeithb** [comment]
The servo cable (brown/red/yellow) looks to be 180° out:
![image](https://user-images.githubusercontent.com/13375512/99162551-b7d31e80-26b3-11eb-94e3-e5c4eae6f2fd.png)

Rotated:
![image](https://user-images.githubusercontent.com/13375512/99162565-f36de880-26b3-11eb-887c-0ed9b2c6d32a.png)

**Comment by ellensp** [comment]
Agreed, was just typing the same.

**Comment by bryankenote** [comment]
Ah, that did it. That should have been the first thing I checked.

Awesome thanks for the help.
