### ISSUE TITLE
Marlin for CNC and Laser

### ISSUE THREAD

**Issue by NickBramley** [MarlinFirmware/Marlin#20162]
I have been trying to edit the config files for both CNC and Laser use with a BTT SKR 1.4 Turbo. The cnc version is workable but I have the following comments regarding the laser useage.

Using Fan0 to operate the laser is dangerous unless you can prevent the user from turning the fan/laser on permanently from the LCD.

The cheap K40 lasers do not have any interlocks fitted so I am trying to use the Filament Detector1 for that with a switch fitted to the lid. Also, I have designed a water flow sensor which I want connect to Filament Detect2.

Which are the best outputs for the laser enable and drive (with PWM)?

Do these config files exist already?

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
