### ISSUE TITLE
[probing failed with g29] (corexy machine homes fine but probing fails)

### ISSUE THREAD

**Issue by GioGalo97** [MarlinFirmware/Marlin#20166]
### Bug Description

<I am currently running an skr1.4 with a btt tft35 screen. On start up I get alarms saying how bed leveling is turned off and fade is turned off but they are both on in the config. When I home everything is fine but once i try to send a g29, I get a probing failed error.-->

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. g28
2. m502
3. m503
4.g29

[config.zip](https://github.com/MarlinFirmware/Marlin/files/5551220/config.zip)

**Expected behavior:**

**Actual behavior:**

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by ellensp** [comment]
Most probably your editing a Configuration.h  in the wrong directory. (A different copy of marlin perhaps) 
The attached "config" file is the readme from the config directory.
The Configuration.h that marlin uses is in the Marlin Directory not the config directory eg. https://github.com/MarlinFirmware/Marlin/tree/2.0.x/Marlin  

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
