### ISSUE TITLE
[BUG] MKS SGEN L V1.0 LPC1768 MKS TS35 V2.0 Touch screen don`t work

### ISSUE THREAD

**Issue by dredivan** [MarlinFirmware/Marlin#20171]
### Hardware:
Motherbord - MKS SGEN L V1.0 LPC1768
LCD - MKS TS35 V2.0
Latest Marlin 2.0 Bugfix

### Bug Description
Touchscreen don`t work, no sensor buttons controll buttons when use **TFT_CLASSIC_UI** 
like in this giff https://github.com/MarlinFirmware/Marlin/pull/20049
 ![ezgif-6-91be9e3d2971](https://user-images.githubusercontent.com/81722/98320186-2da6fe00-1fc1-11eb-83cc-e97f0aa07a12.gif)
I use 
#define MKS_TS35_V2_0
#define TFT_CLASSIC_UI
 
if i try M995 calibration - nothing happens

### Configuration Files
[My configuration.zip](https://drive.google.com/file/d/163QsFE1xwZHnp7JinYYcTxPEytxZtL5d/view?usp=sharing)

**Comment by rhapsodyv** [comment]
I can't download you configuration, gives this error: "Sorry, the file you have requested does not exist.".

Do you have `TOUCH_SCREEN` and `TOUCH_SCREEN_CALIBRATION` enabled?

**Comment by dredivan** [comment]
@rhapsodyv sorry, try again
[config.zip](https://drive.google.com/file/d/163QsFE1xwZHnp7JinYYcTxPEytxZtL5d/view?usp=sharing)

**Comment by rhapsodyv** [comment]
To use touch calibration, you need to enable TOUCH_SCREEN and TOUCH_SCREEN_CALIBRATION. You configs don't have it enabled.
