### ISSUE TITLE
[BUG] MKS SGEN L V1.0 LPC1768  MKS TS35 V2.0 LCD_BED_LEVELING don`t work, Touchscreen don`t work, SD card don`t work

### ISSUE THREAD

**Issue by dredivan** [MarlinFirmware/Marlin#20170]
Hardware: 
Motherbord - **MKS SGEN L V1.0 LPC1768**
LCD - **MKS TS35 V2.0**
Latest Marlin 2.0 Bugfix

- **First Bug:** 
Touch screen don`t work, only encoder
M995 don`t work

- **Second Bug**
If I want use ***Configuration.h\\#define LCD_BED_LEVELING**, I have compilation error:

> 
> Marlin\src\lcd\menu\menu_bed_leveling.cpp:172:32: error: 'touch' was not declared in this scope
> Marlin\src\lcd\menu\menu_bed_leveling.cpp:172:50: error: 'CLICK' was not declared in this scope

- **Third bug**
If I want use **SD card** support **Configuration.h\\#define SDSUPPORT**, I have compilation error:

> c:/users/user/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: region RAM overflowed with stack
> collect2.exe: error: ld returned 1 exit status
> *** [.pio\build\LPC1768\firmware.elf] Error 1

Iif I change in file **Configuration_adv.h\\#define SDCARD_CONNECTION ONBOARD**
I got same error

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
