### ISSUE TITLE
MKS Gen L v1.0 + TMC2209

### ISSUE THREAD

**Issue by BadPanda357** [MarlinFirmware/Marlin#20189]
I cant make TMC2209 to work in UART mode. Standalone works fine but when i connect it via Uart it shows all low. I tried pin remaping and nothing helps.
Im using https://wiki.fysetc.com/Silent2209/ this drivers *V3
[Configuration (1).zip](https://github.com/MarlinFirmware/Marlin/files/5558238/Configuration.1.zip)

**Comment by ellensp** [comment]
Not a standard driver for this Controller. 
No information on how they wired it up. 
Please go to the the Marlin discord for live help, not here

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
