### ISSUE TITLE
BLTouch Crashes in bed when auto-homing

### ISSUE THREAD

**Issue by teoDoul** [MarlinFirmware/Marlin#20190]
Bug Description

The BLTouch does not stop the Z-axis stepper motor on homing.

My config:
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5559270/Marlin.zip)

Steps to Reproduce

Launch Homing XYZ
Look the z stepper motor to push on the bed
Turn off power
Expected behavior: The z stepper motor should stop

Actual behavior: The z stepper motor does not stop

**Comment by teoDoul** [comment]
I know it is answered but i didn't come to any solution from previous ones

**Comment by ellensp** [comment]
Please attach pictures of how bltouch is connected to the controller.

**Comment by teoDoul** [comment]
The Images

https://imgur.com/a/40xQkrk

**Comment by ellensp** [comment]
![pins](https://user-images.githubusercontent.com/530024/99524532-6d2c0c00-29fd-11eb-9485-eb32df628f71.png)
Your black/white cable is in backwards

**Comment by teoDoul** [comment]
I changed it. Now it still hits the board but only for a seconds. Before it was non-stop. How can I fix that?

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by teoDoul** [comment]
Ok thanks

**Comment by J-X-C** [comment]
Teaching Tech on youtube has several step by steps for BLTouch .. got mine working great. You will have to use a piece of paper between the glass and nozzle initially to set Z offset. Then trial and error to get the right squish in the initial layer. Once set it really rocks for me.
