### ISSUE TITLE
error: 'class Temperature' has no member named 'extrude_min_temp'[

### ISSUE THREAD

**Issue by brosskgm** [MarlinFirmware/Marlin#20194]
Marllin 2.0.7.2 - Downloaded 11/18/2020

i3 Mega Configuration.h and adv.h also downloaded 11/18/2020
The only thing I can find close to that is in configuration.h  #define EXTRUDE_MINTEMP 170

This will be running on SKR v1.3 with TFT35 v2.0 and All Mega stand-off boards removed and all wired direct.

If there is alternative config files for the i3 since all Anycubic boards are removed and all is wired direct to SKR please let me know. Might help end a lot of issues going forward.

Thanks
Bob

**Comment by brosskgm** [comment]
It didn't post my comment/

**Comment by brosskgm** [comment]
It does not allow
#define PREVENT_COLD_EXTRUSION
#define EXTRUDE_MINTEMP 170

To be disabled like in the past.

**Comment by sjasonsmith** [comment]
I think this was already patched in the bugfix branch.

**Comment by brosskgm** [comment]
Just tried 2.0.7.3 and it worked fine. Thank you.

Just a few more things to figure out for leveling and will be ready to print.

Thanks Will close.
Bob
