### ISSUE TITLE
[BUG]probe wizard homes n goes back to main screen (short description)

### ISSUE THREAD

**Issue by cvanbusk** [MarlinFirmware/Marlin#20204]
Latest version of bugfix, and config. Was working yesterday when I complied firmware. I'll try again tonight, but hopefully someone has had this issue n can point me in the right direction.

**Comment by qwewer0** [comment]
@cvanbusk 

> * Fill out every section of the template below.
> * Always attach configuration files, regardless of whether you think they are involved.

**Comment by qwewer0** [comment]
When I go to Probe Offset Wizard in the LCD

1. It shows "Homing XYZ"
2. Before homing is done the LCD goes back to the status screen
3. After it homed, it doesn't move to bed center (`PROBE_OFFSET_WIZARD_XY_POS`), stays at homing position
4. If I select Probe Offset Wizard again, LCD shows "Moving..."
5. It starts to move to home direction (X/Y min) until it hits one of the endstops
6. After it hit an endstop it starts to move to X/Y max and crashes into the frame (at this point I shot down the printer)

Ender 3, SKR Mini E3 v1.2, Latest Bugfix
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5558118/Configuration.zip)

https://github.com/MarlinFirmware/Marlin/pull/20167#issuecomment-729456456

**Comment by cvanbusk** [comment]
1. either shows homing xyz 
2. Goes to Info Page showing ready if I go try again it show wizard setting for a short time then goes to info screen
Ender pro 3 Building with platforio latest n I tried 2.10 as that one i updated just before compiling. 

Thanks
RVB

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5570631/Configuration_adv.zip)

**Comment by cvanbusk** [comment]
Loaded n configured 2.0.7 stable build works fine. Just n FYI.

**Comment by qwewer0** [comment]
I think https://github.com/MarlinFirmware/Marlin/pull/20167 is the culprit, but I can't test right now.

@cvanbusk Could you test [Bugfix-2.0.x 50a77ef](https://github.com/MarlinFirmware/Marlin/tree/50a77ef7f05dd4ac8b5ed3e9f3e380c5da7ef50c)?

**Comment by cvanbusk** [comment]
Trying it now, sorry for the delay

**Comment by cvanbusk** [comment]
That works, Z-probe working as expected. Thank you

**Comment by shitcreek** [comment]
Please close this issue if it's all dandy now.

**Comment by rhapsodyv** [comment]
I'm closing this, as the users says it's fixed. Thanks.
