### ISSUE TITLE
[PCF8574 i2c HD44780 2004] (RA_CONTROL_PANEL)

### ISSUE THREAD

**Issue by Cysign** [MarlinFirmware/Marlin#20226]
### Bug Description

Simple HD44780 display using PCF8574 i2c portexpander doesn't work.

Enabling RA_CONTROL_PANEL (which ought to be HD44780 running on PCF8574) gives back a compiling error:

[code]
Marlin\src\lcd\HD44780\ultralcd_HD44780.cpp:71:55: warning: invalid conversion from 'int' to 't_backlightPol' [-fpermissive]
   LCD_CLASS lcd(LCD_I2C_ADDRESS, LCD_WIDTH, LCD_HEIGHT);
                                                       ^
In file included from Marlin\src\lcd\HD44780\ultralcd_HD44780.h:67:0,
                 from Marlin\src\lcd\HD44780\ultralcd_HD44780.cpp:34:
.pio\libdeps\mega2560\LiquidCrystal/LiquidCrystal_I2C.h:65:4: note:   initializing argument 3 of 'LiquidCrystal_I2C::LiquidCrystal_I2C(uint8_t, uint8_t, t_backlightPol)'
    LiquidCrystal_I2C (uint8_t lcd_Addr, uint8_t backlighPin, t_backlightPol pol);
    ^
.pio\libdeps\mega2560\LiquidCrystal/LiquidCrystal_I2C.h: In static member function 'static void MarlinUI::init_lcd()':
.pio\libdeps\mega2560\LiquidCrystal/LiquidCrystal_I2C.h:185:9: error: 'int LiquidCrystal_I2C::init()' is private
    int  init();
         ^
Marlin\src\lcd\HD44780\ultralcd_HD44780.cpp:357:14: error: within this context
     lcd.init();
              ^
At global scope:
cc1plus.exe: warning: unrecognized command line option '-Wno-register'
*** [.pio\build\mega2560\src\src\lcd\HD44780\ultralcd_HD44780.cpp.o] Error 1
[/code]

PCF8574 i2c address 0x27 verified and working with simple liquidCrystal_i2c example withour Marlin.

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.
[Marlin_config.zip](https://github.com/MarlinFirmware/Marlin/files/5576154/Marlin_config.zip)

**Comment by ellensp** [comment]
This has already been fixed, but is only available in bugfix at this time.
See https://github.com/MarlinFirmware/Marlin/pull/19875

**Comment by Cysign** [comment]
So I just have to download and use the bugfix-branch?

**Comment by ellensp** [comment]
or apply the 2 small changes to your current code.
The differences https://github.com/MarlinFirmware/Marlin/pull/19875/files

**Comment by Cysign** [comment]
Couldn't get it work... so I'm using a SSD1306 at the moment, which works properly ;)
Any idea how long it'll take until the bugfix is adopted to stable release?
