### ISSUE TITLE
[BUG] #define SERIAL_PORT_2 -1 build failed

### ISSUE THREAD

**Issue by Dadigno** [MarlinFirmware/Marlin#20234]
### Bug Description
I'm trying to build marlin with
`
#define SERIAL_PORT_2 -1
`
but I receive:
`
Marlin/src/HAL/AVR/../../inc/../../Configuration.h:106:21: error: expected initializer before '-' token
`
and others errors related to the character `-`
[error.zip](https://github.com/MarlinFirmware/Marlin/files/5577611/error.zip)

### Configuration Files
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5577614/Configuration.zip)

Configuration.h is set up for
MKS GEN L
TFT35 e3 v3
Dual estruder

(all firmwares up to date)

### Steps to Reproduce

1. Uncomment #define SERIAL_PORT_2 -1
2. Build

Tested with both latest arduino IDE and PlatformIO on VSCode

**Expected behavior:**
Succefully build

**Actual behavior:**
Not build
[error.zip](https://github.com/MarlinFirmware/Marlin/files/5577611/error.zip)

#### Additional Information
With #define SERIAL_PORT_2 -1 I'm trying to solve a communication problem between MKS and Simplify: in the simplify's terminal, I receive several setup command from printer and finally "Connection failed". 

So, I supposed the problem is a conflict between serial communication of MKS and tft35 and in order to solve this I've tried to uncomment #define SERIAL_PORT_2 and set to -1

**Comment by ellensp** [comment]
You cannot have a serial port set to -1 on a mega based controller.
Only 0,1,2,3 are valid for a mega2560 based board. 
Serial port -1 is when USB is directly connected to the MPU, Mostly for 32 bit controllers.  Your boards USB is via a usb/serial chip. It is really serial 0  
This is not a bug. 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
