### ISSUE TITLE
[BUG] Sensorless Homing on 2nd X axis not triggering [TMC2130]

### ISSUE THREAD

**Issue by bosd** [MarlinFirmware/Marlin#20230]
### Bug Description

Sensorless Homing is not working for Sensorless with TMC2130 driver on the X2 axis.

### Configuration Files

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5577387/Configuration.zip)

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. Checkout latest bugfix 2.0 branch
2. Uncomment `X_DUAL_STEPPER_DRIVERS`
3. Install TMC2130 driver on both the X and X2 driver sloth. define `X_STALL_SENSITIVITY` & `X2_STALL_SENSITIVITY` 
4. Wire 2 identical motors with spindles.
5.  **Preform Misaligned homing test:**
Test if a misaligned axis gets corrected by homing sequence.
Setup the test such that the spindle connected to the X driver is closer to the home position then the X2.
Preform a home sequence.
Actual Behviour: When X-axis sensorless homing gets triggered both axis stops moving.
6. **Preform Isolated X2 homing test.** 
Only wire a motor on the X2 driver.
Preform a home sequence. 
Actual Behviour: Notice that it wont stop even when the endstop should get triggered.

**Expected behavior:**

An misalignment between the two axis should be corrected by a homing sequence.
In the test scenario, Axis X should stop when the (sensorless) endstop is hit. Axis X2 should keep moving until the (sensorless) endstop is hit. Now both axes are at the same home position.

**Actual behavior:**

(sensorless) Endstop on the X-axis stops motor X2 as well. Sensorless endstop of X2 axis is completly ignored.

#### Additional Information

* Test setup preformed with BTT GTR V1.0
* Similar result with using SPI_ENDSTOPS.
* Might be the same for 2nd Y and Z axis. (untested yet)

**Comment by shitcreek** [comment]
This should be a feature request instead because it's not in the codes.
In `motion.cpp` at line 1666, we have this:
```c++
 #if HAS_EXTRA_ENDSTOPS
    const bool pos_dir = axis_home_dir > 0;
    #if ENABLED(X_DUAL_ENDSTOPS)
      if (axis == X_AXIS) {
        const float adj = ABS(endstops.x2_endstop_adj);
        if (adj) {
          if (pos_dir ? (endstops.x2_endstop_adj > 0) : (endstops.x2_endstop_adj < 0)) stepper.set_x_lock(true); else stepper.set_x2_lock(true);
          do_homing_move(axis, pos_dir ? -adj : adj);
          stepper.set_x_lock(false);
          stepper.set_x2_lock(false);
        }
      }
    #endif
    #if ENABLED(Y_DUAL_ENDSTOPS)
      if (axis == Y_AXIS) {
        const float adj = ABS(endstops.y2_endstop_adj);
        if (adj) {
          if (pos_dir ? (endstops.y2_endstop_adj > 0) : (endstops.y2_endstop_adj < 0)) stepper.set_y_lock(true); else stepper.set_y2_lock(true);
          do_homing_move(axis, pos_dir ? -adj : adj);
          stepper.set_y_lock(false);
          stepper.set_y2_lock(false);
        }
      }
    #endif
```

As you can see, it doesn't account for dual sensorless. We could modify this bit of code or perhaps the `G34` https://marlinfw.org/docs/gcode/G034.html which does Z steppers auto-alignment.
