### ISSUE TITLE
Better handling of SDCARDDETECT -1

### ISSUE THREAD

**Issue by trikko** [MarlinFirmware/Marlin#2023]
Now when I change or insert a sdcard I have to select from menu "change sdcard" or "init sdcard". Can't this be done automatically when I select "print from sd card"? It seems a fast operation.

**Comment by thinkyhead** [comment]
It sounds like you are inserting an uninitialized SD card. Does it have files on it, and is it using a standard file system?

**Comment by trikko** [comment]
Yes. It's a fat32 sdcard with files. I can print from it using menu. But if I remove and reinsert card with printer turned on, I have to select "change SD card" item on menu. And then "print from sdcard". Can't " change as card" be triggered each time I select "print from SD card"?

The same happens if I start printer with no card inserted. When I insert it I have to select " init SD card"

**Comment by thinkyhead** [comment]
What's your `SDCARDDETECT` pin? Did you have `SDCARDDETECTINVERTED` turned on?

**Comment by trikko** [comment]
I have a megatronics v3. On pins_MEGATRONICS_3.h is defined -1.

Probably it is disabled then. Can we trigger "change SD card\init SD card" on "print from SD card" if is not defined or if is == -1?

**Comment by thinkyhead** [comment]
According to [this thread](http://forums.reprap.org/read.php?4,322514), you need to do some wiring to get an SD card detect pin with Megatronics 2 – and it probably also applies to Megatronics 3. The instructions (German) are [posted here](http://forums.reprap.org/read.php?249,222157). Or, you can use one of the supported display accessories that Sainsmart sells on [their own store](http://www.sainsmart.com/3d-printing/3d-printing-modules.html).

**Comment by trikko** [comment]
If you check `pins_MEGATRONICS_3.h`  it says that megatronics has no `SDCARDDETECT` pin. That topic explains how to connect SD card, not how to use autodetect pin. Reading Megatronics v3 datasheet it seems there's no such pin. No chance to trigger **change of sdcard** on menu **print from sdcard**?

**Comment by trikko** [comment]
I mean pins_MEGATRONICS_3.h, not pins.h

**Comment by thinkyhead** [comment]
@trikko Yes, well that is the issue. If you want to use a Megatronics board with certain SD card readers, you have to use some workaround, either by re-wiring some other pins to the SD card reader, or by wiring up some other switch (such as a spare endstop switch) to act as the `SDCARDDETECT` pin for the auto-detection feature. Which pin you use for `SDCARDDETECT` will depend on which pin is used by your hardware solution.

Sorry, I see I'm being over pedantic. ^ for the benefit of the casual reader...

As for the workaround of having the SD card "change/init" when you choose "print" – it's not a bad suggestion. Will have to make this a Feature Request.

**Comment by trikko** [comment]
The worst thing is that it has an on-board micro SD card reader and autodetect doesn't work neither for that

**Comment by thinkyhead** [comment]
@trikko What do you think of the current option, where you skip **Init. SD Card** and go straight to **Print from SD**, where there is a menu item to **Refresh** the listing (not initially selected)? The only improvement I can see to make over that is:
- to automatically init the SD when you choose **Print from SD**, and
- remove the **Init. SD Card** menu item completely.
- Optional: If **Print from SD** can't read a card bounce back to **Main Menu**.

See #2035

**Comment by trikko** [comment]
Yes it's exactly my idea. I can't test it now. Anyway, did you remove "change sdcard" menu and call it on "print from sdcard" too? (I guess it's the same menu renamed when a card is inited)

**Comment by thinkyhead** [comment]
I did leave **Change SD Card** in place, but yeah, of course it would be redundant with this. The only thing left is, when **SD Card** screen is visible and you swap the SD card, the electronics won't detect it. So the **Refresh** item there will still need to be manually triggered. However, if you exit the **SD Card** screen then **Refresh** will happen on the next **Print from SD**.

I will make the rest of those changes and update the PR shortly….

**Comment by thinkyhead** [comment]
Actually, it occurs to me that the **Init. SD Card** menu item has a use, and it's a side-effect of `card.initsd` that making this a manual operation mitigates: Namely, the `auto0.g` file starts printing when `card.initsd` is called. So this will need some more work to deal with the special case where the card should be initialized but no automatic printing started. It may be important to some users that **Init. SD Card** and **Change SD Card** (potentially) start `auto0.g` so I need to put them back too…

Onward…

**Comment by trikko** [comment]
I think it could be a good idea to use a #define for this
Something like: #define SDCARD_AUTO_INIT

So:

```
#if SDCARDDETECT >= 0
  ... current code ...
#elif defined(SDCARD_AUTO_INIT)
  ... here it automaGically call init/change sd card when you select "print from sdcard" menu ...
#endif
```

**Comment by trikko** [comment]
Anyway SDCARD_AUTO_INIT it's not the best name I guess :)

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
