### ISSUE TITLE
[BUG] bugfix-2.0.x with MKS BASE 1.5 (Atmega2560) Encoder and eeprom problem

### ISSUE THREAD

**Issue by maks2018** [MarlinFirmware/Marlin#20244]
## Bug Description

I have Delta Printer with MKS BASE and with firmware Marlin-bugfix-2.0.x_20180225 and I have tried to update it to the current version (bugfix-2.0.x), but I faced some problems:
1. The firmware doesn't compile in arduino ide 1.9.
2. I have tried to compile it in PlatformIO and it compiled but with errors. 

Logs with errors (arduino ide 1.9 and PlatformIO) are below: [errors.txt](https://github.com/MarlinFirmware/Marlin/files/5578382/errors.txt)

I've got two problems after the upload firmware (compiled  by PlatformIO): 
1) not working encoder (REPRAP_DISCOUNT_SMART_CONTROLLER defined) 
2) the error "EEPROM version mismatch (EEPROM=? Marlin=V82)". M502 and EEPROM_AUTO_INIT didn't help me. This error I "fixed" by disable EEPROM_SETTINGS.

### Configuration Files

[conf.zip](https://github.com/MarlinFirmware/Marlin/files/5578373/conf.zip)
The archive contains an old config (it have worked with old firmware) and a current config.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
