### ISSUE TITLE
Bed thermistor malfunction behavior

### ISSUE THREAD

**Issue by clefranc** [MarlinFirmware/Marlin#2024]
Doing some temperature protection test today!

I started with the bed:
1. Send a M140 S100 command, bed start heating...
2. Disconnect the bed thermistor...
3. The bed heater stop almost instantly.

The problem is that the target bed temperature is still at 100°C (LCD) and there is no message of a temperature malfunction, not on the LCD nor the host (Repetier), but the bed has nonetheless disappeared from the host.

I'm using the latest dev version.

**EDIT: I'm using all thermal protection:**
# define THERMAL_RUNAWAY_PROTECTION_PERIOD 40 //in seconds
# define THERMAL_RUNAWAY_PROTECTION_HYSTERESIS 4 // in degree Celsius
# define THERMAL_RUNAWAY_PROTECTION_BED_PERIOD 120 //in seconds
# define THERMAL_RUNAWAY_PROTECTION_BED_HYSTERESIS 4 // in degree Celsius
# define WATCH_TEMP_PERIOD 40000 //40 seconds
# define WATCH_TEMP_INCREASE 10  //Heat up at least 10 degree in 20 seconds

**Comment by thinkyhead** [comment]
@clefranc That sounds like a bug! I will try playing with that later too, and see if there's a simple fix. I assume you are testing thermal runaway protection and have that option enabled (?) but it sounds like this condition should throw an alarm regardless of whether there's thermal protection or not.

**Comment by clefranc** [comment]
Updated the OP!

**Comment by thinkyhead** [comment]
I see that if the thermistor isn't connected at all from the start, you probably don't get any alarm either.

**Comment by clefranc** [comment]
@thinkyhead Is there a reason why there is not WATCH_TEMP_PERIOD for the bed? There is thermal runaway protection for both the hotend(s) and bed, but the WATCH_TEMP_PERIOD is not applied to bed.

https://github.com/MarlinFirmware/Marlin/pull/2055

**Comment by clefranc** [comment]
@thinkyhead Here is some bed tests. Will do hotends later.

Using https://github.com/MarlinFirmware/Marlin/pull/2055

### TEST #1 - Bed heating pad disconnected before startup

The bed heating pad shows 0°C current temperature at startup.

**Host:**
- The bed doesn't appears in the Manual Control tab!
- Sending a M140 S100 set the bed target tempeature to 100°C on the LCD...
- The bed is not heating...
- No warning or error displays on the console.

**LCD:**
- Going to the Prepare/Preaheat ABS/Preheat ABS Bed set the bed target temperature to 100°C on the LCD...
- The bed is not heating...
- No warning or error displays on the LCD.

**Conclusion:**
When the bed's thermistor is disconnected before startup, 0°C current temperature is displayed on the LCD. When sending M140 command, or using LCD preheat, there is no warning or error displayed. The bed heating resume normally after reconnecting the thermistor.

### THERMAL RUNAWAY RISK: none

---

### TEST #2 - Bed heating pad disconnected after heating begins

The bed heating pad shows 25°C current temperature at startup.

**Host:**
- Sending a M140 S100 set the bed target tempeature to 100°C on the LCD...
- The bed start heating...
- The thermistor is disconnected...
- The bed stop heating immediately...
- No warning or error displays on the console.

**LCD:**
- Going to the Prepare/Preaheat ABS/Preheat ABS Bed set the bed target temperature to 100°C on the LCD...
- Idem to host.

**Conclusion:**
When the bed's thermistor is disconnected after heating begins, 0°C current temperature is displayed on the LCD and the bed heating stops. There is no warning or error displayed when the thermistor is disconnected. The bed heating resume normally after reconnecting the thermistor.

### THERMAL RUNAWAY RISK: none

---

### TEST #3 - Bed heating pad disconnected before startup when thermistor table begins at 25°C

The bed heating pad shows 25°C current temperature at startup (ADC read 1023).

**Host:**
- Sending a M140 S100 set the bed target tempeature to 100°C on the LCD...
- The bed start heating...
- Bed current temperature stays at 25°C...
- After 5 minutes, bed still heating...

**LCD:**
- Going to the Prepare/Preaheat ABS/Preheat ABS Bed set the bed target temperature to 100°C on the LCD...
- Idem to host.

**Conclusion:**
When the bed heating pad is disconnected before startup AND thermistor table begins at 25°C, 25°C current temperature is always displayed on the LCD. When sending M140 command, or using LCD preheat, the bed will heat indefinitively, or stop when proper command sent.

### THERMAL RUNAWAY RISK: HIGH

---

### TEST #4 - Bed heating pad disconnected after heating begins when thermistor table begins at 25°C

The bed heating pad shows 25°C current temperature at startup.

**Host:**
- Sending a M140 S100 set the bed target tempeature to 100°C on the LCD...
- The bed start heating and current temperature is rising...
- The thermistor is disconnected...
- The current temperature drops to 25°C (ADC read 1023)...
- The bed continue to heat...
- No warning or error displays on the console.

**LCD:**
- Going to the Prepare/Preaheat ABS/Preheat ABS Bed set the bed target temperature to 100°C on the LCD...
- Idem to host.

**Conclusion:**
When the bed's thermistor is disconnected after heating begins AND thermistor table begins at 25°C, the current temperature displayed on the LCD drops to 25°C. The bed will heat indefinitively, or stop when proper command sent.

### THERMAL RUNAWAY RISK: HIGH

**Comment by thinkyhead** [comment]
@clefranc No bed watch period has been implemented yet, but it should be easy enough to clone the hotend code and apply it to the bed heater. I will do that soon.

Another thing that needs to be added is **sudden temperature change** handling, a change of more than 5 degrees in a single sample period (up _or_ down). But that won't catch a thermistor that falls out just shortly after heating begins. The watch temp period should catch that situation, however it currently only does a single test, so it will not catch a thermistor that falls out after that (currently 16 seconds after heating begins). So a sudden temp change handler is needed, and the heating sanity check (watch temp period) needs to re-enable itself after each test.

**Comment by clefranc** [comment]
Please continue discussion here: https://github.com/MarlinFirmware/Marlin/issues/2066

**Comment by AnHardt** [comment]
Closing this. See #2066
