### ISSUE TITLE
[BUG] Unable to invert extruder stepper direction

### ISSUE THREAD

**Issue by phil1horton** [MarlinFirmware/Marlin#20259]
Switched out the extruder stepper for my Tevo Nereus with a Makerbase MKS Nano 1.1 mainboard using marlin bugfix 2.0. The original stepper has one gear that drives another gear to moves the filament. I switched it to a stepper that drives the filament directly so it requires that I invert the direction. I went into configuration.h and updated the following fields below to switch the direction and nothing changes aft boot up.

// @section extruder

// For direct drive extruder v9 set to true, for geared extruder set to false.
#define INVERT_E0_DIR true
#define INVERT_E1_DIR false
#define INVERT_E2_DIR false
#define INVERT_E3_DIR false
#define INVERT_E4_DIR false
#define INVERT_E5_DIR false
#define INVERT_E6_DIR false
#define INVERT_E7_DIR false

**Comment by ChipCE** [comment]
Did you tried clear the EEPROM with <code>M502</code>?

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by phil1horton** [comment]
Hello Chip,

 

I updated the firmware in visual studio and loaded the MKS nano from a thumb drive, and watch the printer load that file. M502 not needed.
