### ISSUE TITLE
[BUG] Disabling SEGMENT_LEVELED_MOVES Causes Board to Reset - Mesh Bed Leveling (Manual without probe)

### ISSUE THREAD

**Issue by houseofbugs** [MarlinFirmware/Marlin#20275]
Tested with Bugfix and 2.0.7.2.

When enabling the manual mesh bed leveling and having SEGMENT_LEVELED_MOVES disabled this causes a reset of the printer board. **Happens on multiple boards, not board specific.**

1. Disable the SEGMENT_LEVELED_MOVES
2. Enable the mesh without a probe
3. Upload firmware to machine
4. Reset EEPROM
5. Do a G28
6. Do the manual "probing" process
7. Send G28 then M402 S1
8. Tell Printer to do a move, board hangs

**Comment by 0purple** [comment]
Please, follow Issue template and include your configs

**Comment by ellensp** [comment]
Please follow the Issue Template when filing a bug report. This includes attaching your configs:
 
```lisp
<!--

Have you read Marlin's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/.github/code_of_conduct.md

Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use the Marlin Firmware forum at http://forums.reprap.org/list.php?415 or the Marlin Facebook Group https://www.facebook.com/groups/1049718498464482/ or the Marlin Discord Server https://discord.gg/n5NJ59y.

Before filing an issue be sure to test the 1.1 and/or 2.0 "bugfix" branches to see whether the issue is already addressed.

-->

### Description

<!-- Description of the bug or requested feature -->

### Steps to Reproduce

<!-- If this is a Bug Report, please describe the steps needed to reproduce the issue -->

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.
```

**Comment by houseofbugs** [comment]
It's not config specific and affects 2.0.7.2 and bugfix. Steps: 

1. Disable the SEGMENT_LEVELED_MOVES
2. Enable the mesh without a probe
3. Upload firmware to machine
4. Reset EEPROM
5. Do a G28
6. Do the manual "probing" process
7. Send G28 then M402 S1
8. Tell Printer to do a move, board hangs

That is all that is needed to reproduce the bug.

**Comment by ellensp** [comment]
Config files provide invaluable information required. Like what type of motherboard? And any other setting that may come into play.
If you have the ability to fix this issue, you should provide a PR to do so, not post a "I have a bug" with zero details

**Comment by houseofbugs** [comment]
I updated with the *exact* steps to reproduce. I have not had time to fix the issue but just enabled the SEGMENT_LEVELED_MOVES option until I can find out why disabling causes it to hang. I was reporting it because there is a workaround but I don't have time to figure out why disabling it causes the crash. It is not board specific as I said. Happens on Creality 2560 Boards, 1284p Creality boards, MKS SGENL V2, EZBoard Lite, and SKR E3 Mini (all versions). I tested this on all these boards before making the report.

**Comment by sjasonsmith** [comment]
@houseofbugs the steps are nice, but without at least one of those configurations provided we don't know what the starting point is to begin executing those steps. Aside from disabling SEGMENT_LEVELED_MOVES there are a multitude of other options which we would be guessing at if not starting with one of your configs.

If you've tried it with so many different configurations we are just asking you to attach _one_ of them. It seems you feel like we are wasting your time, but you are asking someone else to volunteer to waste their own time guessing your configuration.

**Comment by houseofbugs** [comment]
Similar report that is quite old: https://github.com/MarlinFirmware/Marlin/issues/14948

Whole firmware with configs: https://content.timothyhoogland.com/files/ShareXUpload/SegmentBug_V422_E3Board_2072Base.zip

This is my branch that's using 2.0.7.2. I deleted the bugfix test (whatever bugfix was out 3 days ago when the post was made) I had as I was just seeing if it was present on there or not as well, it was. This is setup for an Ender 3 with the V4.2.2 board with the manual mesh leveling (no probe) setup and the segment option disabled.

**Comment by sjasonsmith** [comment]
I've reproduced this in the simulator. It is SegFaulting in a call to `mesh_bed_leveling::cell_index_x`, but I haven't investigated yet.

Steps to reproduce:
1. Use these configs and eeprom.dat in the simulator. It already has a mesh saved.
    [Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5634379/Configuration_adv.zip)
2. `G28`
3. `M420 S1`
4. `G0 X1`

**Comment by sjasonsmith** [comment]
This should be fixed in the above PR. If you are able to verify the change solves it on your system that would be great.

**Comment by sjasonsmith** [comment]
Fix is merged. Please report back if there are still issues.
