### ISSUE TITLE
g29 not centered with two tft screens

### ISSUE THREAD

**Issue by Hallowman28** [MarlinFirmware/Marlin#20276]
Hello,

i just updated with the latest MArlin bugfix.
I mounted on my Alfawise U20 an MKS SGENL V1 with a TFT35 MKS screen with BLtouch and everything worked fine.

I wanted to add an MSK TS35 screen on the EXP1 and EXP2 ports, which after updating the last Marlin works very well.

There is on the other hand a problem with the leveling.
I have exactly the same configuration as before, the right dimensions, the Z safe homing activated but despite this, when I do a G29, it does not take into account my bltouch offset.

I noticed that on the MKS TS35 screen the values are there but on the other hand on the MKS TFT35 screen the zoffset is good but the offset values of Y and X are at 0 and it does not want to save them.

Do you have any idea of the problem?

thank you

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
