### ISSUE TITLE
MKS TS35 calibration each time

### ISSUE THREAD

**Issue by srastoul** [MarlinFirmware/Marlin#20288]
**Bug Description :**

Since the download of the last version of Marlin bugfix 2.0.x each time I start the screen asks me for a calibration. The version for the month of october only requires a calibration at the first start

**Configuration Files:**

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5604450/Marlin.zip)

**Steps to Reproduce:**

Shutdown or reset 3d printer

**Additional Information:**

Bord MKS SGEN-L V2.0

![MKS_TS35_PB_CALIBRATION](https://user-images.githubusercontent.com/74898279/100381093-80039980-3018-11eb-9295-7af05b31d18e.jpg)

**Comment by altiber** [comment]
I had the same problem. After calibration, you need to save the settings via the menu in EPROM . This should help

**Comment by rhapsodyv** [comment]
If you have `EEPROM_SETTINGS` **disabled**, you need to connect to serial, run touch calibration, that the numbers it will show, and put that in your config.

If you have `EEPROM_SETTINGS` **enabled**, you must run `M500` after touch calibration, to save it on EEPROM.

Your configs shows that you don't have `EEPROM_SETTINGS` enabled, so you need to copy the values shown in the serial to your `Configuration.h`
