### ISSUE TITLE
Custom Bootscreen or Status Screen - Compile Error - Ender 3 v2

### ISSUE THREAD

**Issue by Huttch** [MarlinFirmware/Marlin#20291]
When trying to add a custom bootscreen or status screen to Creality Ender 3 V2 and try to compile you receive the following:

<details>
  <summary>Click to see log</summary>
  
  ## Log
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\dogm\u8g_com_stm32duino_swspi.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\eeprom_bl24cxx.cpp.o
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\eeprom_flash.cpp.o
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:49:0,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:718:4: error: #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
   #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
    ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:49:0,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:32:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:718:4: error: #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
   #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
    ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:49:0,
                 from Marlin\src\HAL\STM32F1\MarlinSerial.cpp:25:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:718:4: error: #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
   #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
    ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:49:0,
                 from Marlin\src\HAL\STM32F1\SPI.cpp:43:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:718:4: error: #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
   #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
    ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/../HAL/HAL.h:30:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:31,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../HAL/./STM32F1/HAL.h:213:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
 static int freeMemory() {
            ^~~~~~~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/../HAL/HAL.h:30:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:31,
                 from Marlin\src\HAL\STM32F1\MarlinSerial.cpp:25:
Marlin\src\HAL\STM32F1\../../inc/../HAL/./STM32F1/HAL.h:213:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
 static int freeMemory() {
            ^~~~~~~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:49:0,
                 from Marlin\src\HAL\STM32F1\Servo.cpp:25:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:718:4: error: #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
   #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
    ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/../HAL/HAL.h:30:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:31,
                 from Marlin\src\HAL\STM32F1\SPI.cpp:43:
Marlin\src\HAL\STM32F1\../../inc/../HAL/./STM32F1/HAL.h:213:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
 static int freeMemory() {
            ^~~~~~~~~~
In file included from Marlin\src\HAL\STM32F1\dogm\../../../inc/MarlinConfig.h:49:0,
                 from Marlin\src\HAL\STM32F1\dogm\u8g_com_stm32duino_swspi.cpp:21:
Marlin\src\HAL\STM32F1\dogm\../../../inc/SanityCheck.h:718:4: error: #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
   #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
    ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/../HAL/HAL.h:30:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:31,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:32:
Marlin\src\HAL\STM32F1\../../inc/../HAL/./STM32F1/HAL.h:213:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
 static int freeMemory() {
            ^~~~~~~~~~
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\HAL.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:49:0,
                 from Marlin\src\HAL\STM32F1\eeprom_bl24cxx.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:718:4: error: #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
   #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
    ^~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:49:0,
                 from Marlin\src\HAL\STM32F1\eeprom_flash.cpp:32:
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:718:4: error: #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
   #error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE."
    ^~~~~
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\MarlinSerial.cpp.o] Error 1
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\SPI.cpp.o] Error 1
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\HAL_SPI.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32F1\../../inc/../HAL/HAL.h:30:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:31,
                 from Marlin\src\HAL\STM32F1\Servo.cpp:25:
Marlin\src\HAL\STM32F1\../../inc/../HAL/./STM32F1/HAL.h:213:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
 static int freeMemory() {
            ^~~~~~~~~~
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\Servo.cpp.o] Error 1
In file included from d:\libraries\documents\marlin\marlin\src\hal\hal.h:30:0,
                 from Marlin\src\HAL\STM32F1\dogm\../../../inc/MarlinConfig.h:31,
                 from Marlin\src\HAL\STM32F1\dogm\u8g_com_stm32duino_swspi.cpp:21:
d:\libraries\documents\marlin\marlin\src\hal\stm32f1\hal.h:213:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
 static int freeMemory() {
            ^~~~~~~~~~
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\dogm\u8g_com_stm32duino_swspi.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32F1\../../inc/../HAL/HAL.h:30:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:31,
                 from Marlin\src\HAL\STM32F1\eeprom_bl24cxx.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../HAL/./STM32F1/HAL.h:213:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
 static int freeMemory() {
            ^~~~~~~~~~
In file included from Marlin\src\HAL\STM32F1\../../inc/../HAL/HAL.h:30:0,
                 from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:31,
                 from Marlin\src\HAL\STM32F1\eeprom_flash.cpp:32:
Marlin\src\HAL\STM32F1\../../inc/../HAL/./STM32F1/HAL.h:213:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
 static int freeMemory() {
            ^~~~~~~~~~
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\eeprom_bl24cxx.cpp.o] Error 1
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32F1\eeprom_flash.cpp.o] Error 1
================================================== [FAILED] Took 7.66 seconds
</details>

**Comment by shitcreek** [comment]
"#error "SHOW_CUSTOM_BOOTSCREEN requires Graphical LCD or TOUCH_UI_FTDI_EVE." This tells me you didn't enable an graphical display.

This queue is for reporting issues and feature requests. If you are certain it's a bug, then please follow the template and provide the needed information. We can't do the guess work for you.

For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
