### ISSUE TITLE
[BUG] Offset patern error

### ISSUE THREAD

**Issue by vinoudropdrop** [MarlinFirmware/Marlin#20303]
I am using an SKR V1.4 Turbo + and tryed latest bugfix marlin offered here.
What ever the slicer (tryed Cura and Repetier) or the settings, my prints always start with an offset on all first layers to the left befor filling. This space is formed between the wall and the infill. 
This is not overlap, I checked. This is not a jump of the head either because the layers above return well to the starting pointfor the next layer. 
Please, can you help me resolve this issue? 
Configuration.h + Configuration_adv.h + platformio.ini + photos attached to zip
![99880264-c1f4a000-2c12-11eb-85b0-1404eaf7745b](https://user-images.githubusercontent.com/73717554/100461924-c06f2000-30c9-11eb-9e26-73e299504eca.jpg)
[BugReport.zip](https://github.com/MarlinFirmware/Marlin/files/5608417/BugReport.zip)

**Comment by sjasonsmith** [comment]
The oval holes are a sure sign of backlash in that direction. Most likely loose or worn (stretchy) belts, but it could be other mechanical issues as well.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
