### ISSUE TITLE
[BUG] PASSWORD_FEATURE has wrong communication handling

### ISSUE THREAD

**Issue by repetier** [MarlinFirmware/Marlin#20301]
### Bug Description

When firmware is locked with M510 send commands are not responded to with "ok", only an info message appears.

### Configuration Files

Any config with 
#define PASSWORD_FEATURE
enabled.

### Steps to Reproduce

M510
M114

**Expected behavior:**

Message and a new line with "ok" so hosts are at least able to send new commands.

**Actual behavior:**

Only a message explaining that firmware is locked.

#### Additional Information

Hosts wait for "ok" or will eventually create a timeout when a send command causes no response. Since the commands are parsed and line numbers are incremented correctly, it must also send "ok" so firmware would be able to send M511 P<pin> and not be in blocked state.

**Comment by rhapsodyv** [comment]
I'm closing this, as the fix was merged. Thanks!
