### ISSUE TITLE
[FR] ColorUI - add confirmation to Power Off option before turning the power off

### ISSUE THREAD

**Issue by bkiziuk** [MarlinFirmware/Marlin#20302]
### Description

if `PSU_CONTROL` is enabled in `Configuration.h` the UI menu includes the option `Switch Power Off` if the power in On.
Touching it will immediately turn the power off - which can be somewhat dangerous if it was done by accident.
So, the request is to add an additional confirmation screen before actually cutting the power.

### Feature Workflow

1. Enter menu
2. Touch Power Off option
3. Confirmation dialog is displayed
4. Turn off the power if Ok/Confirm button was touched; go back to the menu if Cancel was touched

#### Additional Information

Board: MKS Robin Nano 1.2 + TFT35
Power control board: MKS PWC 3.0

[config.zip](https://github.com/MarlinFirmware/Marlin/files/5608288/config.zip)

**Comment by slowbro** [comment]
This was implemented by https://github.com/MarlinFirmware/Marlin/pull/22191, merged a couple weeks back.
