### ISSUE TITLE
[BUG] Building Problem : 'int freeMemory()' defined but not used [-Wunused-function] 

### ISSUE THREAD

**Issue by Maker-M** [MarlinFirmware/Marlin#20313]
### Bug Description

Building problem when build the today bugfix 2.0 for the SKR mini E3 V2.0
The problem is : 'int freeMemory()' defined but not used [-Wunused-function]

### Steps to Reproduce

1. Download the last bugfix 2.0
2. Download the last bugfix or import configuration files (same problem for both)
4. Paste the config files from config\examples\Creality\Ender-3 Pro\BigTreeTech SKR Mini E3 2.0 to Marlin folder.
3. Run platformio
4. Change to default_envs = STM32F103RC_btt_512K in platformio.ini
5. Build

**Expected behavior:**

Fix problem

**Comment by qwewer0** [comment]
I too get this warning message, many times within a single compiling:
```
Marlin\src\module\../inc/../HAL/./STM32F1/HAL.h:213:12: warning: 'int freeMemory()' defined but not used [-Wunused-function]
 static int freeMemory() {
```
SKR Mini E3 v1.2, `STM32F103RC_btt`/`STM32F103RC_btt_512K`
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5611004/Configuration.zip)

**Comment by qwewer0** [comment]
@Maker-M You could test it, but I think this can be closed after it is merged, as it fixed the issue on my end.

**Comment by sjasonsmith** [comment]
Wait for it to be merged to close it.

**Comment by Maker-M** [comment]
> @Maker-M You could test it, but I think this can be closed, as it fixed the issue on my end.

Ok I'll see that ! Many thanks

**Comment by Maker-M** [comment]
> Wait for it to be merged to close it.

Yes I would like it to be merged too

**Comment by Maker-M** [comment]
Thanks for the quick support
