### ISSUE TITLE
[BUG] M220 does not have back up and restore feature by default

### ISSUE THREAD

**Issue by thomaslai** [MarlinFirmware/Marlin#20333]
According to the docs, M220 B and R should back up and restore the feedrate percentage accordingly, https://marlinfw.org/docs/gcode/M220.html

but in the code, this feature is actually gated behind PRUSA_MMU2 flag.

https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/gcode/config/M220.cpp#L40-L44

The feature works when I just removed the conditional so I would suggest that it be removed officially.

Thanks

**Comment by sjasonsmith** [comment]
@thomaslai please update the description to utilize the template you are provided while reporting a new bug.

Alternatively, you can close this and submit your change directly as a Pull Request.
