### ISSUE TITLE
having trouble installing marlin on ender 3 v1

### ISSUE THREAD

**Issue by Brown-walker** [MarlinFirmware/Marlin#20357]
I installed the bootloader but when I try to install the marlin software through the Arduino software I get this message:

Arduino: 1.8.13 (Windows 10), Board: "Sanguino, ATmega1284 or ATmega1284P (8 MHz)"

In file included from sketch\src\feature\babystep.cpp:31:0:

c:\users\engit\appdata\local\temp\arduino_build_901772\sketch\src\module\stepper.h: In static member function 'static uint32_t Stepper::calc_timer_interval(uint32_t, uint8_t*)':

c:\users\engit\appdata\local\temp\arduino_build_901772\sketch\src\module\stepper.h:568:53: error: 'speed_lookuptable_fast' was not declared in this scope

           const uint16_t table_address = (uint16_t)&speed_lookuptable_fast[(uint8_t)(step_rate >> 8)][0],

                                                     ^~~~~~~~~~~~~~~~~~~~~~

c:\users\engit\appdata\local\temp\arduino_build_901772\sketch\src\module\stepper.h:570:50: error: 'gain' was not declared in this scope

           timer = MultiU16X8toH16(tmp_step_rate, gain);

                                                  ^~~~

c:\users\engit\appdata\local\temp\arduino_build_901772\sketch\src\module\stepper.h:570:50: note: suggested alternative: 'tan'

           timer = MultiU16X8toH16(tmp_step_rate, gain);

                                                  ^~~~

                                                  tan

c:\users\engit\appdata\local\temp\arduino_build_901772\sketch\src\module\stepper.h:574:47: error: 'speed_lookuptable_slow' was not declared in this scope

           uint16_t table_address = (uint16_t)&speed_lookuptable_slow[0][0];

                                               ^~~~~~~~~~~~~~~~~~~~~~

In file included from sketch\src\MarlinCore.cpp:53:0:

sketch\src\module/stepper.h: In static member function 'static uint32_t Stepper::calc_timer_interval(uint32_t, uint8_t*)':

sketch\src\module/stepper.h:568:53: error: 'speed_lookuptable_fast' was not declared in this scope

           const uint16_t table_address = (uint16_t)&speed_lookuptable_fast[(uint8_t)(step_rate >> 8)][0],

                                                     ^~~~~~~~~~~~~~~~~~~~~~

sketch\src\module/stepper.h:570:50: error: 'gain' was not declared in this scope

           timer = MultiU16X8toH16(tmp_step_rate, gain);

                                                  ^~~~

sketch\src\module/stepper.h:570:50: note: suggested alternative: 'tan'

           timer = MultiU16X8toH16(tmp_step_rate, gain);

                                                  ^~~~

                                                  tan

sketch\src\module/stepper.h:574:47: error: 'speed_lookuptable_slow' was not declared in this scope

           uint16_t table_address = (uint16_t)&speed_lookuptable_slow[0][0];

                                               ^~~~~~~~~~~~~~~~~~~~~~

exit status 1

Error compiling for board Sanguino.

---------------------------------------------------------------------------------------------------Can someone please help me

**Comment by ellensp** [comment]
You have selected the wrong Board type. There are 8 Mhz and 16 Mhz versions you need the 16 Mhz but have chosen the 8 MHz.
You are also in for a world of hurt using aurduino ide. on windows. You really need to run vcsode/platformio see https://marlinfw.org/docs/basics/install_platformio_vscode.html.

Also 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
