### ISSUE TITLE
x and y vibrate when moving to the z safe homing point 

### ISSUE THREAD

**Issue by macalikm** [MarlinFirmware/Marlin#20351]
### Before Reporting a Bug

1. Test with the `bugfix-2.0.x` branch to see whether the issue still exists.

2. Get troubleshooting help from the Marlin community to confirm it's a bug and not just a configuration error. Links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

### Instructions

1. Fill out every section of the template below.

2. Always attach configuration files, regardless of whether you think they are involved.

3. Read and understand Marlin's Code of Conduct. By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md

-->

### Bug Description

x and y vibrate and move erratically  when moving to the z safe homing point 
### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. Initiate "Home All" from BT TFT 24

**Expected behavior:**

X Homes to the Mech Endstop in the min. position
Y Homes to the Mech Endstop in the min. position
Z moves diagonally to the Z_SAFE_HOMING_POINT (roughly the center of the bed)
BLTouch deploys
Z homes to the build plate until BLTouch triggers
**Actual behavior:**
X Homes to the Mech Endstop in the min. position
Y Homes to the Mech Endstop in the min. position
--> X and Y vibrate and move erratically towards the Z_SAFE_HOMING_POINT but never makes it.
--> The Main Screen on the LCD Displays the proper X and Y position
BLTouch deploys
Z homes to the build plate until BLTouch triggers

#### Additional Information

Lowering XY _HOMING_FEEDRATE and HOME_BUMP_DIVISOR help.
If I physically push the X and Y carriages they will move to the  Z_SAFE_HOMING_POINT

[MarlinConfigFiles.zip](https://github.com/MarlinFirmware/Marlin/files/5627184/MarlinConfigFiles.zip)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
