### ISSUE TITLE
ender 5 pro bltouch not deploying using th3d lite board

### ISSUE THREAD

**Issue by flybikescraig** [MarlinFirmware/Marlin#20360]
### Bug Description bltouch on ender 5 pro not deploying after many attempts using the most current marlin or th3d unified firmware.

i have flashed my new th3d lite board with their unified firmware and the latest marlin firmware and made the appropriate changes to get the bltouch to work. unfortunately it does not deploy either when homing or sending command codes via connected octoprint. it does however deploy and stow several times during initial power up of printer. it is plugged into and has replaced the z endstop, i have swapped the black and white wires, confirmed the servo wiring diagrams. bltouch is an authentic v3.1

### Configuration Files
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5633027/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5633028/Configuration_adv.zip)

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. turn on printer, attempt to home
2. observe bltouch fail to deploy, manually attempt to deploy and stow with z still moving upward
3. bed fails to stop, bltouch unresponsive

**Expected behavior:**

**Actual behavior:**

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by thisiskeithb** [comment]
From `Configuration.h`:
```
/**
 * For directions on how to use this firmware visit http://uf2.th3dstudio.com
 */
```
We cannot support forks of Marlin here. Your board also comes with tech support, so reach out to TH3D for further troubleshooting.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
