### ISSUE TITLE
[BUG] MKS Robin V1.1R TFT - blank screen with TFT_COLOR_UI enabled

### ISSUE THREAD

**Issue by mattdog01** [MarlinFirmware/Marlin#20377]
### Bug Description

Using the latest (downloaded 20201205 Marlin-bugfix-2.0.7.2) bugfix.  
My screen is completely blank if I uncomment #define TFT_COLOR_UI but it works just fine if I uncomment #define TFT_CLASSIC_UI. Touchscreen works in both configs but without visual reference in the blank screen.
I did minimal changes to the config files to exclude other factors. Only changed physical things in the configuration.h file (attached) no changes to configuation_adv.h. 

/**

TFT UI - User Interface Selection. Enable one of the following options:
TFT_CLASSIC_UI - Emulated DOGM - 128x64 Upscaled
TFT_COLOR_UI - Marlin Default Menus, Touch Friendly, using full TFT capabilities
TFT_LVGL_UI - A Modern UI using LVGL
For LVGL_UI also copy the 'assets' folder from the build directory to the
root of your SD card, together with the compiled firmware.
*/
//#define TFT_CLASSIC_UI
#define TFT_COLOR_UI
//#define TFT_LVGL_UI

### Configuration Files

[Config files.zip](https://github.com/MarlinFirmware/Marlin/files/5647413/Config.files.zip)

### Steps to Reproduce

1. I first tried the build in the mks_robin environment uncommenting #define TFT_CLASSIC_UI
2. Booted up the machine with the SD card containing the new bin file.
3. Worked perfectly.  Classic UI visible and touch works perfectly.
4. Cleaned the build area and tried the build again but with only #define TFT_COLOR_UI uncommented.
5. Booted up the machine with the SD card containing the new bin file.
6. Screen is blank once the upload is complete. Touch works but without the visual reference.

**Expected behavior:**

I expected the TFT_COLOR_UI to work and be visible like it was for earlier builds.

**Actual behavior:**

The screen is completely blank no light at all. **The text can be seen if a strong light is held up to the screen.**
(Suspect backlight pin is not defined correctly for the board - ¯\_(ツ)_/¯ )

#### Additional Information

The board
   MKS Robin v2.3

The screen
   MKS TFT v1.1R

The machine
   coreXY printer
   running on 24volts

The compiler
   PlatformIO
   mks_robin build environment specified in the platformio.ini

Last fully functional bug_fix was downloaded 2020-09-09

**Comment by mattdog01** [comment]
What I can find and it all looks correct.  The drawings specify PG11 for the FSMC_LIGHT

pin.h
#elif MB(MKS_ROBIN)
  #include "stm32f1/pins_MKS_ROBIN.h"           // STM32F1                                env:mks_robin env:mks_robin_stm32

pins_MKS_ROBIN.h
  //#define LCD_RESET_PIN                      PF6
  #define LCD_BACKLIGHT_PIN                PG11
  #define FSMC_CS_PIN                           TFT_CS_PIN
  #define FSMC_RS_PIN                           TFT_RS_PIN

  #define LCD_USE_DMA_FSMC                // Use DMA transfers to send data to the TFT
  #define FSMC_DMA_DEV                       DMA2
  #define FSMC_DMA_CHANNEL              DMA_CH5
#elif HAS_GRAPHICAL_TFT
  #define TFT_RESET_PIN                          PF6
  #define TFT_BACKLIGHT_PIN                 PG11
#endif

**Comment by rhapsodyv** [comment]
The pins file were outdated, after some TFT changes. 

Fixed here: #20404 . Can you test it?

**Comment by mattdog01** [comment]
@rhapsodyv  Hello Victor thank you for your work.  I downloaded a fresh copy of bugfix an 1hr ago and built the bin file and it is the same issue except I have also lost touch screen function.  The display is visible in classic mode but not in colour UI mode.  Touch screen doesn't work in either mode.  
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5660922/Configuration.zip)

**Comment by mattdog01** [comment]
oh i forgot to mention I'm using the mks_robin build environment not the mks_robin_stm32 environment.  Is that how you wanted it tested?

**Comment by rhapsodyv** [comment]
My fix was not merged on bugfix yet. I'm waiting you test it, before merging in bugfix

**Comment by rhapsodyv** [comment]
Fixed and merged.
