### ISSUE TITLE
Step for second extruder

### ISSUE THREAD

**Issue by freezone23** [MarlinFirmware/Marlin#2037]
ISSUE 2031 

I do not understand where is error.
I have two identical extruders (MK8).
when I say to repetier extrude 10mm, 80mm comes out (the first extruder is ok).

is there anyone who can help me?

thanks

p.s.
more info: https://github.com/MarlinFirmware/Marlin/issues/2031
I just replaced the card but the issue persists ......
drivers are not the cause ....

**Comment by thinkyhead** [comment]
I wonder if this is related at all to #1793. But let's see if we can isolate other causes.

**Comment by freezone23** [comment]
problem solved.
very important for owners of MKS BASE 1.2.

read more:
https://github.com/MarlinFirmware/Marlin/issues/2031
