### ISSUE TITLE
[BUG] SKR 1.4 Turbo: E3 won't turn with SDSUPPORT + MOT-EXP

### ISSUE THREAD

**Issue by kyaron** [MarlinFirmware/Marlin#20373]
Configurtion = 
BTT SKR1.4 Turbo
BTT TMC2209
BTT MOT-EXP
Marlin 2.x bugfix.

I am using BTT MOT-EXP in order to have a 3rd extroder. (X, Y, Z, E1, E2, E3).

While configuring the Marlin bugfix 2.x i found out that everytime I enable the SDSUPPORT, the E3 is not turning.

Tried to cross everything HW releated - cables, drivers, motors, non helped. The only way to get it back to work is commenting it.
[3rd E issue - Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5645125/3rd.E.issue.-.Configuration.zip)

### Configuration Files

Included

### Steps to Reproduce

1. Uncomment "SDSUPPORT", line 1771, Configuration.h
2. Try to extrode

**Expected behavior:**

All 3 extruders needs to turn

**Actual behavior:**

X, Y, Z, E1, E2 are turning without any issue all the time. E3 turns only if "SDSUPPORT" is disabled

**Comment by rhapsodyv** [comment]
For this board, the default is the SD on LCD. So, Marlin will try to communicate with the SD using the same EXP ports that you connect MOT-EXP.
So, a `SDCARD_CONNECTION == LCD` will never work with MOT-EXP.

Can you try again, but setting the SD to ONBOARD?

`#define SDCARD_CONNECTION ONBOARD`

**Comment by kyaron** [comment]
Tried, same issue

**Comment by rhapsodyv** [comment]
Very weird, because with SD onboard, no PIN is shared between EXP ports and the SD.

**Comment by Minims** [comment]
I have the same issue on SKR Pro with SD ONBOARD.
If I remove the microSD card from the SKR board, it works. But the SD Card can't be used.

**Comment by Minims** [comment]
Additional information. I have test with TMC2209 UART and DRV8825 (which use only EXP2 wire). I have the issue in both case. Can it be DETECT_PIN or SPI mode used for ONBOARD SD ?

**Comment by rhapsodyv** [comment]
> Additional information. I have test with TMC2209 UART and DRV8825 (which use only EXP2 wire). I have the issue in both case. Can it be DETECT_PIN or SPI mode used for ONBOARD SD ?

Not according with the schematics. SD detect pin is `P0_27`, but exp ports don't use this pin:
```cpp
/*               _____                                      _____
 *           NC | · · | GND                             NC | · · | GND
 *           NC | · · | 1.31 (M1EN)            (M2EN) 1.23 | · · | 1.22 (M3EN)
 * (M1STP) 0.18 | · ·   3.25 (M1DIR)           (M1RX) 1.21 | · ·   1.20 (M1DIAG)
 * (M2DIR) 0.16 | · · | 3.26 (M2STP)           (M2RX) 1.19 | · · | 1.18 (M2DIAG)
 * (M3DIR) 0.15 | · · | 0.17 (M3STP)           (M3RX) 0.28 | · · | 1.30 (M3DIAG)
 *               -----                                      -----
 *               EXP2                                       EXP1
 */
```

It's a mysterio. I ordered one mot-ext to test it.

**Comment by ellensp** [comment]
I'm thinking the SPI ports that would be used to talk to the SD card is being setup accidentally

**Comment by rhapsodyv** [comment]
> I'm thinking the SPI ports that would be used to talk to the SD card is being setup accidentally

But the current HW SPI code for LPC just init the SPI port if it's used.... Yet it would not explain why enabling/disabling the onboard sd would influence in anything, as it use different SPI port than the EXP slots... :-/ I can't see any shared PIN.

**Comment by ellensp** [comment]
Well, I also have one of these on order (for a while now)..  all going well it should arrive in about a week. then can try some stuff.  
Month later.. no sign of the board, sigh... (this never arrived)

**Comment by Minims** [comment]
Hello, problem still exists, just keeping this issue open.

**Comment by ellensp** [comment]
perhaps this is the issue https://github.com/MarlinFirmware/Marlin/pull/21755
