### ISSUE TITLE
[region RAM overflowed with stack] when trying to compile config file for BIGTREETECH SKR1.4 for ender 3

### ISSUE THREAD

**Issue by smartkidag** [MarlinFirmware/Marlin#20395]
### Bug Description

I'm trying to compile firmware for my ender 3, I've added a second extruder. I had Marlin 2.x.x last week and have it working with single extruder. Only change I've made is added a second extruder and a corresponding driver and I get the error "Region RAM overflowed with stack"

### Configuration Files

It works fine without having a second extruder or a second stepper driver. 

### Steps to Reproduce

1. Add parameters for another extruder
2. Compile and visual studio code gives me the error.

**Expected behavior:**

Compile normally and I can use the bin file to flash my ender 3

**Actual behavior:**

Doesn't compile. 

#### Additional Information

It works with Bigtreetech's firmware they have on their github (2.0.6.1 I believe), but their firmware has some issue with auto bed leveling where it wont work. So I want to use the latest Marlin firmware and I get this error. Please help me.. 

[Config files.zip](https://github.com/MarlinFirmware/Marlin/files/5649948/Config.files.zip)

**Comment by p3p** [comment]
The config has 3 displays enabled and does not compile, so I'm not sure which one you intended to use.

You have ran out of RAM .. so it overflowed, the config has expensive options enabled and default values increased arbitrarily, the main culprit that is using over 6K of RAM is `#define BUFSIZE 64` this has been increased from the default value of `4`, you shouldn't need to change this value.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
