### ISSUE TITLE
[FR] Filament runout / Advanced_Pause_Feature without LCD

### ISSUE THREAD

**Issue by italocjs** [MarlinFirmware/Marlin#20399]
Same as this FR #16848  

I'm using repetier server with a screen, and no onboard screen,.  when i try to setup the filament sensor it requires advanced pause, which in turn requires a LCD which i dont have connected to the board.

Any chance to make this independent? 

Error: 
Marlin\src\HAL\AVR\../../inc/SanityCheck.h:839:6: error: #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."
     #error "ADVANCED_PAUSE_FEATURE requires a supported LCD controller (or EMERGENCY_PARSER)."

**Comment by ETE-Design** [comment]
Have you tryed to enable EMERGENCY_PARSER as it suggest when you compile?

**Comment by italocjs** [comment]
Enabling emergency parser, Load and unload gcodes, i get the following (seems unrelated but if i comment those features the errors go away)


Marlin\src\feature\pause.cpp: In function 'bool ensure_safe_temperature(bool, PauseMode)':
Marlin\src\feature\pause.cpp:136:51: error: 'class Temperature' has no member named 'extrude_min_temp'

**Comment by italocjs** [comment]
i believe something in the code is only enabled if a lcd is present

**Comment by ETE-Design** [comment]
@italocjs It is possible to enable without LCD, it is a known bug but if you set EXTRUDE_MINTEMP to 0 you can overcome it, but of cause on your own risk :-)
You can also just comment out #define PREVENT_COLD_EXTRUSION

**Comment by italocjs** [comment]
Thanks, i'll try it tomorrow first thing!

**Comment by ETE-Design** [comment]
@italocjs Did it work? And if so then pls. Close this issue...

**Comment by italocjs** [comment]
Sorry, forgot to close it.
It did work!
