### ISSUE TITLE
[FR] Sensorless homing to determine Z-Offset

### ISSUE THREAD

**Issue by holocronology** [MarlinFirmware/Marlin#20400]
### Description

If the device/board supports Sensorless Homing, utilize this feature in conjunction with a Z-Probe to determine the Z-Offset.

### Feature Workflow

1. Install and configure Z-Proble (BLTouch, etc...)
2. Activate Sensorless Homing on Z Axis--if supported by device/board
3. Auto Z-Offset Wizard that will use positional date from Z-Probe and Sensorless Homing on Z-Axist to calculate Z-Offset.
4. Manual Z-Offset adjustment would remain.

**Comment by sjasonsmith** [comment]
Sensorless homing already works poorly on the Z axis. If it cannot be used reliably to replace a probe, then it also cannot be used reliably to determine your Z offset.
