### ISSUE TITLE
stk500_recv(): programmer is not responding

### ISSUE THREAD

**Issue by monkeygopro** [MarlinFirmware/Marlin#20405]
Hello everybody, 

I got this error from my Arduino Programm. 

Arduino: 1.8.13 (Mac OS X), Board: "Sanguino, ATmega1284 or ATmega1284P (16 MHz)"

Der Sketch verwendet 125492 Bytes (96%) des Programmspeicherplatzes. Das Maximum sind 130048 Bytes.
Globale Variablen verwenden 4556 Bytes (27%) des dynamischen Speichers, 11828 Bytes für lokale Variablen verbleiben. Das Maximum sind 16384 Bytes.
/private/var/folders/hj/6p0zytvx53x0ftvv38qhpsv00000gn/T/AppTranslocation/954D6093-24F6-4DD1-BB6B-8DCB4ECB8E7A/d/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude -C/private/var/folders/hj/6p0zytvx53x0ftvv38qhpsv00000gn/T/AppTranslocation/954D6093-24F6-4DD1-BB6B-8DCB4ECB8E7A/d/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf -v -patmega1284p -carduino -P/dev/cu.usbserial-1420 -b115200 -D -Uflash:w:/var/folders/hj/6p0zytvx53x0ftvv38qhpsv00000gn/T/arduino_build_741017/Marlin.ino.hex:i 

avrdude: Version 6.3-20190619
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/private/var/folders/hj/6p0zytvx53x0ftvv38qhpsv00000gn/T/AppTranslocation/954D6093-24F6-4DD1-BB6B-8DCB4ECB8E7A/d/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/Users/abdullah/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbserial-1420
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x00

avrdude done.  Thank you.

I am trying to install Marlin on my Ender 3 printer but I faced this problem. 
I got also a blank screen on my ender3. 

Ender 3 board is Creality3D V1.1.4 206101051. 
I have done the configuration step by step just like described. 
i have used the configuration of Creality>Ender-3>Creality V1  I hope that is the right one for this board. 
U8glib bib is also installed. 

i will be thankful for everyone will help here.

**Comment by ellensp** [comment]
Wrong boot loader selected, or no bootloader on the controller board. Probably the latter.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
