### ISSUE TITLE
[BUG] SKR1.4T babystepping not working

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#20409]
### Setup

SKR1.4t
2209 drivers
24v power 
octoprint 

### Bug Description

Babystep (probe Z offset) on the z-axis does not work when printing even when enabled.

### Configuration Files
- [Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/5662800/Marlin-bugfix-2.0.x.zip)
- [Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5663014/Configuration_adv.zip)

### Steps to Reproduce

1. Flash with FW
1b. optional Init/Save
2. Start a print
3. Babystepping does not work

**Expected behavior:**

Expected it to step as needed to adjust Z offset and make the hot-end higher or lower.

**Actual behavior:**

No movement even if offset is changed and saved until print is stopped and restarted.

**Comment by thisiskeithb** [comment]
Do you mean babystepping? If so, try enabling `INTEGRATED_BABYSTEPPING`.

**Comment by ghost** [comment]
> Do you mean babystepping? If so, try enabling `INTEGRATED_BABYSTEPPING`.

I did; apologies! Tried that once already but no luck; I'll try again though.

**Comment by ellensp** [comment]
When you say flash firmware are you just hitting upload, as these boards require you to reboot after uploading to actually flash new firmware.

**Comment by ghost** [comment]
Yup, full reboot. Process has been compile -> Rename bin as needed -> put into printer when it's off -> turn on -> Wait for blue screen to end finishing fw update -> home -> start print -> edit offset

Still no luck with probe offset

edit: Tried the INTEGRATED_BABYSTEPPING at this point too but no luck. Does something else need to be disabled? Same config,  with only that changed

**Comment by ChaChaBwoy3D** [comment]
> Yup, full reboot. Process has been compile -> Rename bin as needed -> put into printer when it's off -> turn on -> Wait for blue screen to end finishing fw update -> home -> start print -> edit offset
> 
> Still no luck with probe offset

I'm using same board and I can babystep my nozzle just fine recheck your configuration.

**Comment by ghost** [comment]
> I'm using same board and I can babystep my nozzle just fine recheck your configuration.

With latest branch/bugfix? If so, can you upload your config. I'd love to know what I did wrong

**Comment by ChaChaBwoy3D** [comment]
Sure thing
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5669931/Configuration.zip)

**Comment by ghost** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5670735/Marlin.zip)
Compared and updated mine but still no luck. Also tends to be slow on the LCD during prints. Z offset doesn't change unless the print is restarted

**Comment by ghost** [comment]
Anything I can do to help fix?

**Comment by rhapsodyv** [comment]
I have marlin installed in a skr 1.4 turbo + btt tft 3.0. My marlin is for two weeks ago.
And I can do babystep during the print.
As I do a lot of testing, I frequently forget to do z offset before printing. So I use a lot this function: babystep while printing.

How are you doing babystep? By the lcd? By gcode commands? By the BTT TFT?

**Comment by ghost** [comment]
LCD - tried gcode too but no luck

**Comment by rhapsodyv** [comment]
Can you try this?
```cpp
#define BABYSTEP_MILLIMETER_UNITS
#define BABYSTEP_MULTIPLICATOR_Z 0.1
```

**Comment by ghost** [comment]
> Can you try this?
> 
> ```c++
> #define BABYSTEP_MILLIMETER_UNITS
> #define BABYSTEP_MULTIPLICATOR_Z 0.1
> ```

That worked - either that or disabling menu for PID autotune on LCD :) Many thanks.
