### ISSUE TITLE
small request add bed time limits

### ISSUE THREAD

**Issue by TechMasterJoe** [MarlinFirmware/Marlin#2042]
Add an adjustable timer for the heated bed maybe 2…
1. A kill timer so if idle for a "LCD changeable time limit" _kill heated bed_…
2. A simple settable timer so someone can say turn the bed on for X minutes then it will shut off. The reasoning is simple. Some people use the hotbed for other things I can list a few here.
   1. Vapor treatment 
   2. helps release parts at times
   3. cooking food......just kidding
   4. safety some times people forget to turn off the bed in end code

I can type up the code and menu changes once the bug fixing has been finished

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
