### ISSUE TITLE
[BUG] mks LCD12864a. White Screen

### ISSUE THREAD

**Issue by Jeong-Hyung-min** [MarlinFirmware/Marlin#20434]
I am using MEGA2560 Board and RAMPS 1.6 and mks LCD12864a. The firmware is 1.1.9.1
I am satisfied with the mks LCD12864a.
It works fine except for one thing.
When the power is turned on and booted, the screen of mks LCD12864a is all white, making it impossible to distinguish characters. 
![20201211_122951_HDR](https://user-images.githubusercontent.com/75822742/101859593-5d908500-3baf-11eb-8fd5-85537c77dc71.jpg)

If the 3D printer is turned on and off three or four times, it works normally. The connecting cable is about 15cm.
![20201211_123008](https://user-images.githubusercontent.com/75822742/101859618-697c4700-3baf-11eb-8d8f-f5a4a79c3477.jpg)

Could it be a timing issue? Please tell me the solution.

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

Also: When reporting an issue, please be sure to follow all instructions at the top of the template, including debugging steps, and leave the sections headings intact.

**This includes attaching your configuration files, regardless of whether you think they are involved.**

For reference, these are the instructions included in the template:

### Before Reporting a Bug

1. Test with the `bugfix-2.0.x` branch to see whether the issue still exists.

2. Get troubleshooting help from the Marlin community to confirm it's a bug and not just a configuration error. Links at https://github.com/MarlinFirmware/Marlin/issues/new/choose

### Instructions

1. Fill out every section of the template below.

2. Always attach configuration files, regardless of whether you think they are involved.

3. Read and understand Marlin's Code of Conduct. By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md

**Comment by mks-viva** [comment]
@Jeong-Hyung-min 
Hi! I would recommend you to use the latest version of marlin 2.x firmware. Thank you very much for your affirmation of MKS products

**Comment by sjasonsmith** [comment]
Try re-initializing your EEPROM through the menus or using M502 then M500.

Screens with software-configurable contrast will often have bad contrast values saved in the EEPROM if you have just added the screen to your configuration.

**Comment by sjasonsmith** [comment]
I missed the firmware version you listed. As others have said you will need to update to Marlin 2.x to support this screen properly.

**Comment by sjasonsmith** [comment]
Given that this is for 1.x firmware, I am closing this. We no longer develop for 1.x, and changes for this display will not be back-ported to it.
