### ISSUE TITLE
[BUG] Probing Failed: Probe Temperature Compensation SKR1.3

### ISSUE THREAD

**Issue by floriankogler** [MarlinFirmware/Marlin#20442]
I use the latest Marlin bugfix and a fix mounted inductive probe.

On G76 or G76 P the probing fails always during the second measurement.
On G76 the bed calibration process works fine, then it fails during second measurement of probe calibration process.

I get always the same error massage: Error: Probing Failed!

Edit:
After some research I noticed, that when I use a positive number of z-probe-offset the printer passes the second measurement and fails at third. The higher I set the z-offset, the more measurement can be passed.

Here my configs:
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/5683599/Configs.zip)

**Comment by thisiskeithb** [comment]
Please edit your post and attached your configs as a .zip as outlined in the instructions and remove them from inline.

Also: Download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by floriankogler** [comment]
I just updated my post and added some information.
I still have the issue with the latest bugfix.

**Comment by TheNeskik** [comment]
You can try to lower your probe. When you calibrate the probe, each point will keep in mind the temperature "drift" so the probe will try to trigger higher than it currently can.

So : 
1 - Lower your probe
2 - Tune your z-offset with a bed at 60°C and your probe at 30 °C
3 - Run G76 P

See if it helps :)

**Comment by floriankogler** [comment]
So I tried to lower the probe, and tuned my offset. I had a z-offset of -2.489, if that is of ralevance for you.

But unfortunately the error occured during first probing.

**Comment by TheNeskik** [comment]
Are you able to perform a bed level without temperature compensation ? If you use a PINDA V2 you should try to lower your probe in order to get an offset around 1.00 mm above your nozzle.
I don't think your problem is marlin. I advice you to come on the Discord :) if we point that there are no problem with your probe configuration. We could consider that it can be a bug :)

**Comment by floriankogler** [comment]
Thank you for your help, I was able to find a solution.

In the file Marlin\src\gcode\calibrate\G76_M192_M871.cpp there is the following section:
````
auto g76_probe = [](const TempSensorID sid, uint16_t &targ, const xy_pos_t &nozpos) {
    do_z_clearance(5.0); // Raise nozzle before probing
    const float measured_z = probe.probe_at_point(nozpos, PROBE_PT_STOW, 0, false, false);  // verbose=0, probe_relative=false, sanity_check=false (added by florian kogler)
    if (isnan(measured_z))
      SERIAL_ECHOLNPGM("!Received NAN. Aborting.");
    else {
      SERIAL_ECHOLNPAIR_F("Measured: ", measured_z);
      if (targ == cali_info_init[sid].start_temp)
        temp_comp.prepare_new_calibration(measured_z);
      else
        temp_comp.push_back_new_measurement(sid, measured_z);
      targ += cali_info_init[sid].temp_res;
    }
    return measured_z;
  };
````
In the line ````const float measured_z = probe.probe_at_point(nozpos, PROBE_PT_STOW, 0, false, false);```` is the last parameter (sanity check) in the original file left out. Due to the default argument it will be set to true.

So, it triggers an "Probe fail! - triggered early" due to the temperature "drift" of the probe.
As you can see in Marlin\src\module\probe.cpp:
````
float Probe::run_z_probe(const bool sanity_check/*=true*/) {
  DEBUG_SECTION(log_probe, "Probe::run_z_probe", DEBUGGING(LEVELING));

  auto try_to_probe = [&](PGM_P const plbl, const float &z_probe_low_point, const feedRate_t fr_mm_s, const bool scheck, const float clearance) {
    // Do a first probe at the fast speed
    const bool probe_fail = probe_down_to_z(z_probe_low_point, fr_mm_s),            // No probe trigger?
               early_fail = (scheck && current_position.z > -offset.z + clearance); // Probe triggered too high?
    #if ENABLED(DEBUG_LEVELING_FEATURE)
      if (DEBUGGING(LEVELING) && (probe_fail || early_fail)) {
        DEBUG_PRINT_P(plbl);
        DEBUG_ECHOPGM(" Probe fail! -");
        if (probe_fail) DEBUG_ECHOPGM(" No trigger.");
        if (early_fail) DEBUG_ECHOPGM(" Triggered early.");
        DEBUG_EOL();
      }
    #else
      UNUSED(plbl);
    #endif
    return probe_fail || early_fail;
  };
````

So, I changed the parameter to false and now the calibration runs without a problem.
