### ISSUE TITLE
Compilation error with #define MKS_WIFI_MODULE 1

### ISSUE THREAD

**Issue by altiber** [MarlinFirmware/Marlin#20450]
### Bug Description

 Bugfix from 12.12.2020, MKS Robin Nano 2.0. Compilation error with #define MKS_WIFI_MODULE 1 in tft_lvgl_configuration.h
### Configuration Files

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5683597/Marlin.zip)

**Comment by sjasonsmith** [comment]
I do not consider this an issue, since that feature does not yet exist in the configuration files.

The following pull request is open to implement it: #20191
