### ISSUE TITLE
[FR] Disable all steppers but extruder during filament change from main menu when there is no active print

### ISSUE THREAD

**Issue by mseddon** [MarlinFirmware/Marlin#20461]
### Description

Disable X, Y, Z (but obviously not extruders) during filament change when there is no active print (i.e. this is not a programmed filament change, but one from the menu)

### Feature Workflow

1. Cold boot a marlin printer
2. Select 'change filament', and preselect temp. Marlin would then disable X/Y/Z steppers when it's possible to detect we're not mid-print
3. This allows for a nozzle that is flush against the build plate or similar to be easily manually corrected so you don't make even more of a mess than you intend.

#### Additional Information

So I just hit 'change filament' because I started a print but luckily (or not), the nozzle was at z=0.1. I then purged into that position, which caused buildup over the nozzle. I was swapping to the same material, and the same colour, so this is not an issue and the blob was fairly minor and easy to remove.  However, had I been switching materials, then I would need to purge far more, and this would have risked backing up into the nozzle/all over the tool head.  Is it possible to disable the X/Y/Z steppers so I can e.g. manually turn the z-rod while the purge is occurring in this case (menu activation, no print in progress).

If there is a safety issue with this (e.g. risk that a disabled stepper may 'drift') then perhaps allow a config to raise the Z by a preset amount before filament purge, specifically when going from the menu manually when no print is active.

This is my 2 cents. Hopefully my problem description makes sense, but I would defer to you the best solution for this particular issue, since I understand you have a lot of different hardware to support.

**Comment by sjasonsmith** [comment]
Disabling motors means you lose the machine's position. You would have to re-home all your axis to resume the print. That would be doable for X/Y (but might not be perfect), but is often impossible for Z.

**Comment by mseddon** [comment]
Good shout. To be fair just raising the Z up by 20mm would be handy in my case.

**Comment by tpruvot** [comment]
#define NOZZLE_PARK_Z_RAISE_MIN   2   // (mm) Always raise Z by at least this distance

**Comment by thisiskeithb** [comment]
> #define NOZZLE_PARK_Z_RAISE_MIN 2 // (mm) Always raise Z by at least this distance

To expand on this, take a look at the entire [Nozzle Park section](https://github.com/MarlinFirmware/Marlin/blob/c6dcf9d0067fdd6c81f8f229dd18aa34ac84c90a/Marlin/Configuration.h#L1580-L1601) as well as [Advanced Pause](https://github.com/MarlinFirmware/Marlin/blob/c6dcf9d0067fdd6c81f8f229dd18aa34ac84c90a/Marlin/Configuration_adv.h#L2107-L2160).

Your feature request seems covered by existing park/raise/filament change settings within Marlin.

**Comment by mseddon** [comment]
Thanks for the clarification, I will close this. Cheers!
