### ISSUE TITLE
Bed twist compensation

### ISSUE THREAD

**Issue by alvinavr** [MarlinFirmware/Marlin#2049]
If the Y-bars are not parallel it appears as if the print bed is twisted and it is difficult to get the first layer to stick. 

I have a working prototype solution for this, for my setup it makes a vast improvement. The bed is "level" across the entire surface to better than 0.025mm, the measurement limit of my dial gauge.

The solution rides on top of the AUTO_BED_LEVELING feature and does not add a lot of code. If the auto bed levelling probes four or more points there is enough information available to solve the problem. 

How is it best to submit this new feature? Could someone explain how to create a git pull request. Is their a guide for submitting pull requests that I missed?

**Comment by thinkyhead** [comment]
- Fork Marlin
- Make a working copy of your fork on your computer
- Create a new branch (based on `Development`) using the command line or the Github client
- Make changes to your branch
- Commit your changes to your branch
- Publish your changes to push them to Github
- Submit a PR using the Github client or from your fork's Github page

**Comment by AnHardt** [comment]
I'm exited about that new feature.
Additionally to what @thinkyhead wrote:
http://www.marlinfirmware.org/index.php/Coding_Standards
and not totally up to date but with the right tendency:
http://www.marlinfirmware.org/index.php/Contributing

**Comment by CptanPanic** [comment]
@alvinavr that would be a great feature.  Can't wait to check it out.

**Comment by alvinavr** [comment]
Found some bugs that need fixing and my printer broke. I think I now understand the bug and can see a fix. My printer has a slightly twisted frame and I baked that assumption into my code. That assumption is not always correct.
My printer is now repaired and testing can start again.

**Comment by boelle** [comment]
i will close this one.... we dont want to support bad adjusted printers.... if we do that we can quickly make more of a mess for ourselfes software wise

**Comment by AnHardt** [comment]
@boelle 

> we dont want to support bad adjusted printers

So you think we should remove ABL? :-)

**Comment by boelle** [comment]
no no... but twisted beds? a tilted bed yes....

**Comment by AnHardt** [comment]
> If the Y-bars are not parallel it appears as if the print bed is twisted.

I think this is a relative common problem and for most printers hard to adjust.

**Comment by CptanPanic** [comment]
I agree this should remain opened. This is just solving the more general problem of ABL in more dimensions.

**Comment by alvinavr** [comment]
I am on holiday at the moment. I will get back to work on this issue next week.

I ran into some problems with my solution. I had hard coded some assumptions that are very specific to my printer. In particular the centre of rotation.

I can see how to solve it, I JUST need to do the algebra for a two factor linear regression.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
