### ISSUE TITLE
More than 128 Neopixels can’t be controlled individually

### ISSUE THREAD

**Issue by Felix-ArduPilot** [MarlinFirmware/Marlin#20490]
### Bug Description
Hi!
I am running marlin 2.0 on a JGAurora A5 printer with an MKS Gen-L V1.0 board. I have connected two neopixel strips. The second one is longer than 128 LEDs. I can control the strips and individual LEDs with g-code commands as long as I try to access LEDs with numbers lower than 128. As soon as I try to switch on a Neopixel above 128 I switch on all LEDs starting from 128 to the end of the strip.

I think this might be some kind of memory problem, but I’m not sure, if it is a hardware limitation of the MKS Gen-L Board or a limitation in the code. I’m sure, someone here knows how to solve this.

### Steps to Reproduce
Connect a Neopixel strip of more than 128 LEDs to the board and try to activate a Neopixel higher than 128 with g-code commands. For example use: M150 S1 w255 I130

**Expected behavior:**

LED 130 will be turned on (white in this case).

**Actual behavior:**

All LEDs starting from 129 to the end of the strip will be turned on (white).

**Comment by ellensp** [comment]
You cannot run this many NEOPIXELS on marlin without them seriously breaking timings. They take to long to set.
