### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by TBSliver** [MarlinFirmware/Marlin#2050]
Hi, can someone point me to the actual IRC Channel and server for this project? I have found several mentions of it, but the channel and server are documented neither on the Wiki or in the README as far as I can find.

**Comment by thinkyhead** [comment]
`irc.freenode.net` is fine. Channel `#marlin-firmware`

**Comment by boelle** [comment]
i removed the info for the channel as no one used it... people only used it as a parking space

there have been much more success with google hangout
