### ISSUE TITLE
[BUG] Unnecessary warning in 2.0.x main branch

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#20502]
Bug Description

There are a couple of compiler warnings in the 2.0 main branch caused, I believe by changes in the compiler.

```
Compiling .pio\build\mega2560\libdec\Wire\utility\twi.c.o
C:\Users\William\.platformio\packages\framework-arduino-avr\libraries\Wire\src\utility\twi.c: In function '__vector_39':
C:\Users\William\.platformio\packages\framework-arduino-avr\libraries\Wire\src\utility\twi.c:552:7: warning: empty declaration
       __attribute__ ((fallthrough));
       ^
C:\Users\William\.platformio\packages\framework-arduino-avr\libraries\Wire\src\utility\twi.c:638:7: warning: empty declaration
       __attribute__ ((fallthrough));
```
### Configuration Files

These are stock.  
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5716449/Marlin.zip)

### Steps to Reproduce

1. Compile
2. Observe warning

**Expected behavior:**
No error or warning in main branch (unless unavoidable, of course)

**Actual behavior:**
benign warning

#### Additional Information

I believe the fix is to substitute` /* fall through */` for `__attribute__ ((fallthrough));` on each offending line.  I was rewarded with a clean compile when I made these changes.

I do not base this on my thin knowledge of C++ but on https://stackoverflow.com/questions/45349079/how-to-use-attribute-fallthrough-correctly-in-gcc

I would submit a PR but I have not figured out how to do that yet.  I don't think you want to see the mops and the buckets dance.

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by bill-orange** [comment]
Nope, bugfix is fine.

**Comment by thisiskeithb** [comment]
Great!
