### ISSUE TITLE
[BUG] Sanity Checks are based on extruder numbers (and not hotends)

### ISSUE THREAD

**Issue by LordDarkneo** [MarlinFirmware/Marlin#20530]
Hi there!
I have just downloaded a fresh SKR E3 Mini v2.0 configuration file for using a MMU2 clone. And I cannot compile the new Marlin build because sanity checks are making the asumptions that Extruder number = hotends number = required temp sensors:

`Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:1688:6: error: #error "TEMP_SENSOR_1 is required with 2 or more HOTENDS."
     #error "TEMP_SENSOR_1 is required with 2 or more HOTENDS."
      ^~~~~
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:1696:8: error: #error "TEMP_SENSOR_2 is required with 3 or more HOTENDS."
       #error "TEMP_SENSOR_2 is required with 3 or more HOTENDS."
        ^~~~~
Marlin\src\HAL\STM32F1\../../inc/SanityCheck.h:1704:10: error: #error "TEMP_SENSOR_3 is required with 4 or more HOTENDS."
         #error "TEMP_SENSOR_3 is required with 4 or more HOTENDS."`

The point is the MMU clone need those 5 extruders to be set up on the printer firmware side:
`// This defines the number of extruders
// :[0, 1, 2, 3, 4, 5, 6, 7, 8]
#define EXTRUDERS 5`

Thus this issue is "normal" for Marlin (but not for me!)
`#ifndef HOTENDS
  #define HOTENDS EXTRUDERS
#endif`

Everybody using Marlin will have the issue with this check. Could it be fixed please?

**Comment by sjasonsmith** [comment]
Other people are using MMU, so this seems to be a configuration issue.

Even if it is not, the issue template was ignored, and there is insufficient information to even begin to investigate any issue.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
