### ISSUE TITLE
(Q) 4 EXTRUDERS and dual servo SWITCHING_EXTRUDER

### ISSUE THREAD

**Issue by DrumClock** [MarlinFirmware/Marlin#20543]
Hi,
this error occurs when setting` #define EXTRUDERS 4 `and two servos for `#define SWITCHING_EXTRUDER` for E0/1 and E2/3.

[error.txt](https://github.com/MarlinFirmware/Marlin/files/5728430/error.txt)

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5728426/Configuration.zip)

Tested on bugfix 2.0.x from 22.12.2020

**Comment by ellensp** [comment]
no. Invalid incomplete bug report. Once again trying to slip a feature request for an unsupported hardware configuration in as a bug.

**Comment by DrumClock** [comment]
Hi @ellensp 
The error will be in the module ... \ Marlin \ src \ inc \ Conditionals_LCD.h in the section

 ```
 #if DISABLED (SWITCHING_NOZZLE)
     #define HOTENDS E_STEPPERS
   #endif

```
Here, HOTENDS is set to 2 even if there are physically 4 Hotend (2 switching extruders).
If I disable `#define HOTENDS E_STEPPERS`, everything is fine.

**Comment by sjasonsmith** [comment]
@DrumClock I think you are right. Can you submit a pull request with that change?

I (and probably most of us) don't even know how to configure a switching extruder. It would be best for the fix to come from someone actually using it.

**Comment by DrumClock** [comment]
HI @sjasonsmith 
Here is my whole branch: https://github.com/DrumClock/Marlin/tree/GTR-4EX2
I don't know exactly what you need, so look at that.

**Unfortunately, the module does not work after today's update**

... `Marlin \ src \ HAL \ STM32 \ timers.cpp`: 105: 31: error: 'NUM_HARDWARE_TIMERS' was not declared in this scope
   105 | HardwareTimer * timer_instance [NUM_HARDWARE_TIMERS] = {nullptr};

**Comment by sjasonsmith** [comment]
Here is an introduction to pull requests:
https://marlinfw.org/docs/development/getting_started_pull_requests.html

You already described the code issue a few comments up. You are apparently the only person using the combination of features you have, so it is important for you to learn how to submit back fixes when you find them.

As for that timer issue, that is only happening on your end. Keith and I have both already built your configurations and it isn't a problem.

**Comment by DrumClock** [comment]
Hi @sjasonsmith 
I'm sorry, but I don't speak English, I use a translator.
I'm not sure I would do it and describe it correctly.
I'm sorry, but I can't do anything about it.

I would love to try changes in the program even without PR if someone sends me the corrected modules and send feedback.
I can very quickly rebuild the printer with the BTT GTR V1.0 board for various configurations :)

**Comment by sjasonsmith** [comment]
I thought you were correct, but now I agree with @ellensp that this is more of a feature request.

In it's current form I think `SWITCHING_EXTRUDER` implies that each pair of filaments use a single HOTEND. Changing this would break any existing users of this feature, unless there are exactly zero successful `SWITCHING_EXTRUDER` users today.
