### ISSUE TITLE
Marlin Google Hangout • Saturday 6 June 2015 at 21:00pm UTC • Topics TBD • Be there!

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#2056]
```
Name             Zone    UTC-7 Offset               online weekdays      online weekend
@thinkyhead      UTC-7
@Wackerbarth     UTC-5
@Jnesselr        UTC-5                        
@clefranc        UTC-4   + 3 hours           
@alexborro       UTC-3   + 4 hours           
@fmalpartida     UTC+1   + 8 hours           
@AnHardt         UTC+1   + 8 hours           
@Wurstnase       UTC+1   + 8 hours
@CONSULitAS      UTC+1   + 8 hours
@paclema         UTC+1   + 8 hours          
@boelle          UTC+1   + 8 hours                  13:00 - 20:00        ~8:00 - 22:00
@emartinez167    UTC+8   +15 hours = -9      
@ntoff           UTC+10  +17 hours = -7      
```

The above UTC+ values change at summer/winter time by one hour

"Official" Clock :  http://www.timeanddate.com/time/aboututc.html

<a href="https://plus.google.com/hangouts/_/gxn3wrea5gdhoo223yimsiforia" target="_blank">Hangout</a>

link to googledoc with topics:

<a href="https://docs.google.com/document/d/1GmKjDVOKLj6f6s76ZL99LvCPOwy_PkYK57M88Q2oNdM/edit?usp=sharing" target="_blank">Topics</a>

**Comment by CONSULitAS** [comment]
@CONSULitAS       UTC+1   + 8 hours

will try to be there, but can't promise

**Comment by paclema** [comment]
@paclema UTC+1 + 8 hours
I'll try to be there too, this time with connection fixed.

**Comment by boelle** [comment]
oki both are now added to the table

btw... if anyone knows how to create a bootloder hexfile for a atmega 1284p with 20mhz crystal let me know....

**Comment by fmalpartida** [comment]
I'll be there!
One more thing, could we change the time to something a bit like 21:00 UTC, the proposed time is like 12:00 PM here with DLS going on.

**Comment by thinkyhead** [comment]
21:00 works for me.

**Comment by AnHardt** [comment]
Sorry, will be away. 
Kites still have priority.

**Comment by Wackerbarth** [comment]
Thats 16:00 for me (UTC-5). See you then.

**Comment by thinkyhead** [comment]
Should we invite the Marlin Documentation thread participants? I feel there is still some need for folks to express their concerns.

**Comment by boelle** [comment]
everyone can join, i would not mind

Den torsdag den 21. maj 2015 skrev Scott Lahteine <notifications@github.com

**Comment by Jnesselr** [comment]
I think I can make that. UTC - 5 I think.

**Comment by scotty1024** [comment]
Topic list suggestion.

New Pololu stamp.

3A drive, 1/128 micro stepping, built in SPI digipot for current limit and SPI status register read back for various fault conditions. I'm thinking of it as the Arduino Due of steppers. :-)

https://www.pololu.com/product/2970

**Comment by foosel** [comment]
I can't make it, still not back on my feet (and if I were I'd be at a friend's wedding eve celebrations)

**Comment by fmalpartida** [comment]
Take good care foosel. This year's flu is as nasty as I remember.

**Comment by boelle** [comment]
i will be there.... maybe early... but our topics google doc is totally empty....

EVERONE can make suggestions as comments and we are 3 that can edit...

So please add something or we will end up watching each other pick nose

**Comment by boelle** [comment]
@foosel Gute Besserung

**Comment by boelle** [comment]
i'm in hangout but cam and mic disabled... will be there 5 min before we plan to start

REMEMBER to add something to the google doc.... everyone should be able to add comments... please do at bottom of doc if possible

**Comment by fmalpartida** [comment]
Don't worry Scott and I are waffle masters ;-) 
There are some topics we have been discussing in threads which are worth bringing forward.

**Comment by fmalpartida** [comment]
@boelle are you in the hangout?
We are in the HO that is linked here.

**Comment by boelle** [comment]
hangout closed for now... we might skip the normal 14 day period if we dont have any topics

**Comment by thinkyhead** [comment]
Some of the active projects to be considered when going forward on new features.

Firmware:
- Sprinter
- Repetier
- LinuxCNC
- Grbl
- Teacup
- MachineKit
- Smoothieware
- MakerBot
- FiveD
- BFB/RapMan

Hosts:
- Printrun / Pronterface
- Repetier Host, Mac / Windows
- Cura
- Octoprint
- Replicator G
- BotQueue
- Print2Peer
- AstroPrint
- RepRapWeb

Slicers:
- Slic3r
- Cura
- KiSSLicer
- Skeinforge
- Simplify3D

**Comment by Jnesselr** [comment]
BotQueue, Print2Peer, AstroPrint and RepRapWeb are all hosts. Sorry for the confusion.

**Comment by Wackerbarth** [comment]
Add "Repeater Host - Mac"

**Comment by thinkyhead** [comment]
Other notes:
- `M240` noted. Triggers a camera pin on Marlin. Has another function in Teacup.
- `M333` noted as not being host-friendly due to blocking. (Infrequently used setup option, so…)
- `PR Coding Standards` label: A tag for PRs that improve code quality, maintainability, encapsulation, etc.
- Noted: Cura may be bailing early on prints with recent Marlin. Needs more corroboration.
- Topic: How can Marlin help hosts?
  - Do hosts use `M115` at all? How can it be improved?
  - Consistent temperature reporting among firmwares.
- Mentioned: `M33`, a code that gets the long filename for a short filename
  - RepRap wiki: "`M33, M34 - Used by some variants of Marlin firmware. Purpose unknown.`" (`M34` = Set SD sorting options, for sorted listings, needs more work)
- Marlin stops reporting bed temperature… when?

**Comment by Wackerbarth** [comment]
Repeater Host - Mac Issues M115 shortly after connecting to the printer.

**Comment by whosawhatsis** [comment]
Repetier Host Mac has been on version 0.56 for how long now? Over a year and a half? I wouldn't classify it as active.  

Though seeing the direction the windows version has gone since then, I guess that's a blessing.

**Comment by Wackerbarth** [comment]
"active" -- In terms of development, no.  But, so far, I have gotten the best results using it on my laptop to drive my printers.

**Comment by Jnesselr** [comment]
It's my go to when I hook the printer up to my Mac as well.

**Comment by thinkyhead** [comment]
Adding MachineKit to the list, I suppose… http://blog.machinekit.io/

**Comment by thinkyhead** [comment]
I use Repetier Host Mac to examine my gcode, sometimes to combine or modify STL scaling, etc. Never used it to slice or print…

**Comment by fmalpartida** [comment]
I scrapped repetier on Mac a year and a bit ago.
Here in Spain, the use base is very low and almost everybody uses Cura now. Its simple and it works very well.

**Comment by Wackerbarth** [comment]
Well, I just tried the latest version of Cura. It crashed.  :(
Also, feature-wise, I would like to see a better stored "settings" mechanism.
From a user's perspective, I like the slic3r scheme of having separate stored settings for machines, filaments, and operational modes.

**Comment by thinkyhead** [comment]
> I would like to see a better stored "settings" mechanism.

I would like to have an application that lets you organize all your STLs by category (leaving them where they are in the filesystem), to be able to associate STL objects with configuration (.ini) files that are tuned for them (plus various materials & printers), to be able to do batch slicing whenever you update a configuration, and to be able to direct the .gcode files that it generates to a chosen destination. I started on the general idea by making a [set of droplets](https://github.com/thinkyhead/Slic3r-Droplet-for-OSX) that you can use to batch-slice objects with a selected configuration, but a proper GUI – not too different from an organizer like iTunes – would really help.
