### ISSUE TITLE
avr-gcc: error: Creating process (When Marlin is compiled)

### ISSUE THREAD

**Issue by AayushBoliya** [MarlinFirmware/Marlin#20569]
### Bug Description

When verified/compiled, both in VS and Arduino IDE, It throws the same error. I opened `E:\Arduino\hardware\tools\avr\bin` the avr-gcc and all other avr files still exist.

### Configuration Files

[Config. Files Drive link](https://drive.google.com/drive/folders/1wM02yUiJTfk5nzM0n_h4nOULItcnTPDZ?usp=sharing)

Parametric changes of stepper motors and hotend maxtemp.

### Steps to Reproduce

1. Install fresh Martin zip file from official website or github repository.
2. Open Marlin.ino in Marlin folder.
3. Compile/Verify

**Expected behavior:**

To get compiled smoothly.

**Actual behavior:**

When I compile it, it shows following error message:

`avr-gcc: error: CreateProcess: No such file or directory`

`exit status 1`

`Error compiling for board Arduino Mega or Mega 2560.`

**Comment by sjasonsmith** [comment]
This is a limitation of the maximum command line length when using Arduino on Windows. There are ways to work around it, but it is usually a better option to switch to Visual Studio Code with PlatformIO.

This has many advantages over Arduino;
- Avoid command length issues
- MUCH faster builds
- Automatically dependency management
- Benefits from all future improvements to Marlin build processes

[Installing Marlin (VSCode)](https://marlinfw.org/docs/basics/install_platformio_vscode.html)
[Auto Build Marlin](https://marlinfw.org/docs/basics/auto_build_marlin.html)

For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by Roxy-3D** [comment]
I wonder if we should change the documentation and just say Arduino is no longer supported as a build environment?

Alternatively...  It does kind of seem to me the Arduino group would be interested in using Marlin as a build environment and test each version against it.   Marlin is one of the more complicated Arduino projects and it would provide them with a good test for new releases.
