### ISSUE TITLE
Intermittent Auto Home Failed and Manual push Axis X or Y switch stop trigger Printer Halted with A10M GEEETECH - Marlin 2.X

### ISSUE THREAD

**Issue by mmaitre74** [MarlinFirmware/Marlin#20577]
### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. Upgrate to last firmware Marlin 2.0 Bug Fix
2. In the LCD menu select Auto Home (intermittent Home Failed and Printer Halted)
3. For Manual forcing problem while pressing LCD Auto HOME, click any Endstop Switch (X,Y)

**Expected behavior:**

If endstop switch pressed, the printer must stop axis pressed and continu to going Home point to other axis

.

**Actual behavior:**

The Marlin version 1.1.8 and 1.1.9 has no problem with the ends
[configa10m.zip](https://github.com/MarlinFirmware/Marlin/files/5743650/configa10m.zip)
top or intermittent problem

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by godbnc** [comment]
i have same problem with cr10v2 not home error i check configuration ,endstop,wires conection, but not there is problem  with marlin .....

**Comment by ellensp** [comment]
homing is not that simple (depending on setting) ...  if you press and hold an endstop it will fail as it thinks the endstop is broken.
It need to be able to home, back off and home again getting a triggered, not triggered, and re triggered in sequence.
I'm not saying this is the issue, but I am saying your test of holding an endstop in a triggred state is not necessarily a good test.

**Comment by mmaitre74** [comment]
I found a temporary solution.

I remove this line in configuration.h

// Validate that endstops are triggered on homing moves
// #define VALIDATE_HOMING_ENDSTOPS

But when I disabled this option. Sometime the Auto Home not going in the full home Axis.

**Comment by rhapsodyv** [comment]
can you try enabling `#define ENDSTOPPULLDOWNS` instead of `#define ENDSTOPPULLUPS`?

**Comment by mmaitre74** [comment]
#define ENDSTOPPULLDOWNS , same issue

**Comment by mmaitre74** [comment]
Version 1.18 and 1.19 woking without issue. Here the last Bugfix 2.0

https://user-images.githubusercontent.com/19422624/103245622-bccff280-492e-11eb-8c73-364b42f66ac5.mov

**Comment by FanDjango** [comment]
Have you got a 1.1.9 config to show?

**Comment by FanDjango** [comment]
And in the video I see that there is a small "stop" in the middle of the homing move of X

**Comment by FanDjango** [comment]
Check playing with this setting, maybe:
```
/**
 * Endstop Noise Threshold
 *
 * Enable if your probe or endstops falsely trigger due to noise.
 *
 * - Higher values may affect repeatability or accuracy of some bed probes.
 * - To fix noise install a 100nF ceramic capacitor in parallel with the switch.
 * - This feature is not required for common micro-switches mounted on PCBs
 *   based on the Makerbot design, which already have the 100nF capacitor.
 *
 * :[2,3,4,5,6,7]
 */
//#define ENDSTOP_NOISE_THRESHOLD 2
```

**Comment by FanDjango** [comment]
I see the homing bump of X, also of Y. Hmmm.  Do me a favor: Do the homing one by one, first Home X, then Home Y, then Home Z. Isolate the problem

**Comment by mmaitre74** [comment]
Hi FanDjango, thanks for your help. with #define ENDSTOP_NOISE_THRESHOLD 2. No more issue. Everything work perflectly.
