### ISSUE TITLE
[FR] Granular PROBING_HEATERS_OFF options

### ISSUE THREAD

**Issue by Sebazzz** [MarlinFirmware/Marlin#20598]
### Description

If I'm not wrong PROBING_HEATERS_OFF was introduced for the Creality CR-6 to mitigate electrical interference when reading the strain gauge. The strain gauge is read from the daughter board near the hot-end. The daughter board reads the analog signal from the strain gauge and passes that as digital signal (HIGH or LOW) to the motherboard where Marlin runs. There is no need to disable heating the bed while probing.

### Feature Workflow

This FR is to request to add an option to keep the bed heater on while probing and `PROBING_HEATERS_OFF` enabled.

1. `PROBING_HEATERS_OFF` enabled
2. Add option for keeping bed heater enabled
3. G28, G29 do not turn off the bed heater

#### Additional Information

Essentially [this](https://github.com/CR6Community/Marlin/commit/b1147ad54e6705389f2e4505aa45c48f73f38fca#diff-bb298d18dac4268225a7a53a5ad24844472530bdc63f6a98a2ba8d8158b75080R1091) plus [this](https://github.com/CR6Community/Marlin/commit/b1147ad54e6705389f2e4505aa45c48f73f38fca#diff-9c1d09e39e0d06d83cd4a44f54ff41e1cc364477c4dc39ecacf106a9b75540b7R2188).

**Comment by thisiskeithb** [comment]
Wouldn't this be as simple as disabling `PROBING_HEATERS_OFF` in the CR-6 config? It appears to already be disabled in the config hosted in the Configurations repo at least.

**Comment by Sebazzz** [comment]
That will keep the heater of the hot-end on, which is exactly the one you want to disable during probing.

**Comment by sjasonsmith** [comment]
Could you simply probe before heating the nozzle?

Does heating the nozzle even interfere with probing? If I’m not mistaken the strain gauge is at the top of the hotend assembly, far from the nozzle.

**Comment by Sebazzz** [comment]
No, because the nozzle is heated to make any filament remains soft and account for thermal expansion.

But the strain gauge emits an analogue signal. This is read by a HX711 chip on the daughter bord PCB but with the heaters on interference happens which causes an inaccurate read-out. 

Thats the entire point why that feature was added (iirc). The point is that it turns off the bed heater as well - but that isn't necessary nor desired. In any case, for me it made probing and consequently homing and bed leveling much more accurate.

**Comment by thisiskeithb** [comment]
Until `PROBING_HEATERS_OFF` is split to allow the hotend & bed to be controlled independently, I'd go with something like this for start gcode (using PrusaSlicer's variables as an example):

```gcode
M104 S170 ; preheat hotend to 170
M140 S[first_layer_bed_temperature] ; set bed temp
M190 S[first_layer_bed_temperature] ; wait for bed temp
G28 ; home all
M104 S0 ; turn off hotend
G29 ; mesh bed leveling
; insert whatever post ABL moves are needed here
M109 S[first_layer_temperature] ; wait for hotend temp
```
Edit: Reordered to turn off hotend after homing.

**Comment by sjasonsmith** [comment]
That probably isn’t good enough, since any ooze on the nozzle could re-harden and cause probe results to be too high.

**Comment by Sebazzz** [comment]
That's a secondary issue actually: you only want the heater off in the probing zone (optical switch LOW). The nozzle can already be cold if you home from a large Z height.

**Comment by huhansome** [comment]
阿里云服务器低至96/年，学生价9.5/年
https://www.aliyun.com/minisite/goods?source=5176.11533457&userCode=j6bryttg

阿里云数据库限时折扣，低至188/年
https://www.aliyun.com/activity/ambassador/database?source=5176.11533457&userCode=j6bryttg

阿里云企业级服务器1折限时特惠
https://promotion.aliyun.com/ntms/act/enterprise-discount.html?source=5176.11533457&userCode=j6bryttg

阿里云建站 速成美站 - 千套模板，价格低至500元
https://ac.aliyun.com/application/webdesign/sumei?source=5176.11533457&userCode=j6bryttg

CDN爆款产品低至5.5折
https://yqh.aliyun.com/live/cdncarnival?userCode=j6bryttg&source=5176.11533457&userCode=j6bryttg

**Comment by thinkyhead** [comment]
> Does heating the nozzle even interfere with probing?

Heating in-general interferes with probe readings because the higher-voltage PWM tends to affect the electrical characteristics of the whole board and its attached peripherals. Disabling the heaters (just while polling the probe pin or awaiting a pin interrupt) removes this extra electrical interference and is demonstrated to produce more consistent readings with BLTouch, inductive probes, and capacitive probes.

**Comment by thinkyhead** [comment]
If there is concern about heaters getting cold during a very long homing move, we could modify Marlin to leave the heaters on during the initial homing move, and then disable the heaters for the 'slow bump' homing move.

**Comment by thisiskeithb** [comment]
> If there is concern about heaters getting cold during a very long homing move, we could modify Marlin to leave the heaters on during the initial homing move, and then disable the heaters for the 'slow bump' homing move.

How would that work with configs with no homing bump (sensorless homing)?

**Comment by FanDjango** [comment]
> If there is concern about heaters getting cold during a very long homing move, we could modify Marlin to leave the heaters on during the initial homing move, and then disable the heaters for the 'slow bump' homing move.

The heating-turn-off is too early

**Comment by thinkyhead** [comment]
> How would that work with configs with no homing bump (sensorless homing)?

If no homing bump was configured, then it would behave as it does now.

**Comment by thinkyhead** [comment]
> The heating-turn-off is too early

Yes, that perfectly summarizes my point. The 'slow bump' move is only a millimeter or two long, so leaving the heaters on for the initial long homing move, and only turning them off before this short move should give the best result.

**Comment by Sebazzz** [comment]
Does the last homing bump determine the actual zero position? Its not like the auto leveling by which the average of the two positions is taken?

Then it should probably be this,
1. Tare
2. Home & touch
3. Heaters off
4. Tare
5. Final homing move

**Comment by FanDjango** [comment]
@Sebazzz Can you have a look at #20610?

**Comment by Sebazzz** [comment]
> 
> 
> > If there is concern about heaters getting cold during a very long homing move, we could modify Marlin to leave the heaters on during the initial homing move, and then disable the heaters for the 'slow bump' homing move.
> 
> How would that work with configs with no homing bump (sensorless homing)?

Sensorless homing isn't used on the Z-axis, is it?

**Comment by thisiskeithb** [comment]
> Sensorless homing isn't used on the Z-axis, is it?

it can be (`SENSORLESS_PROBING`), but not recommended. I was thinking of the homing bump for X/Y.

**Comment by thinkyhead** [comment]
Marlin is now updated so that heaters will only be turned off for the second (slow) probe of the bed.
