### ISSUE TITLE
[BUG] U8GLIB_SH1106 i2c display wraps vertically with U8G_I2C_OPT_FAST, causes random watchdog resets without on LPC1768

### ISSUE THREAD

**Issue by ej0rge** [MarlinFirmware/Marlin#20605]
### Bug Description

Built my own approximation of a Tinyboy2 controller with a 1.3" sh1106 oled based on diagrams in this thread: 

https://reprap.org/forum/read.php?13,499572,page=1

It is connected to a brand new SKR 1.4. 

#define U8GLIB_SH1106 and it works great at bootup, but shortly after shifts 5 pixels vertically. 

The advice given on the reprap forum is to remove U8G_I2C_OPT_FAST because the SH1106 doesn't like 400khz i2c. 

If i alter the relevant section of marlinui_DOGM.h to remove the fast i2c option, there is no vertical shift on my display. 

But the printer reboots at random instances. For example during homing, or while uploading gcode to the sd card, or a minute or so into a print. 

Changing no other options other than putting U8G_I2C_OPT_FAST back, i am able to use the printer normally, but the display is again vertically wrapped shortly after bootup. 

### Configuration Files

[sh1106bug.zip](https://github.com/MarlinFirmware/Marlin/files/5755823/sh1106bug.zip)

### Steps to Reproduce

1. Connect i2c sh1106 oled display to i2c bus
2. #define U8GLIB_SH1106 and compile/install
3. Boot printer, use it briefly, observe shifted display
4. Edit marlinui_DOGM.h to remove U8G_I2C_OPT_FAST from #elif ENABLED(U8GLIB_SH1106) section; compile / install
5. Boot printer, use it briefly, slightly slower display does not shift vertically
6. Eventually the printer undergoes an apparent watchdog reset

**Expected behavior:**

I just want a way to have my tiny controller work properly and have a printer that works at the same time. 

**Actual behavior:**

I can choose between a wrapped display and a printer that can't be used

#### Additional Information

![20201230_143934](https://user-images.githubusercontent.com/43465247/103382765-6a691000-4aad-11eb-9652-4717518c6147.jpg)

**Comment by ellensp** [comment]
duplication of https://github.com/MarlinFirmware/Marlin/issues/14431
