### ISSUE TITLE
[FR] Custom movement speed during G26 validation pattern

### ISSUE THREAD

**Issue by ScrewThisBanana** [MarlinFirmware/Marlin#20615]
### Description

I would like to set the G26 movement speed to a value different from the G26 extrusion Speed as the movement speed is (for my personal opinion) too slow (extrusion speed defaults to 20mm/s, movement speed may be set to at least 100mm/s)

### Feature Workflow

1. Configure the `G26_XY_FEEDRATE_MOVE` parameter
2. Software check if extrusion takes place, if not, `G26_XY_FEEDRATE_MOVE` is used instead of `G26_XY_FEEDRATE`

#### Additional Information

Possible implementation here https://github.com/MarlinFirmware/Marlin/compare/bugfix-2.0.x...ScrewThisBanana:bugfix-2.0.x

**Comment by qwewer0** [comment]
@ScrewThisBanana Could you make a PR on the main bugfix-2.0.x branch?

**Comment by ScrewThisBanana** [comment]
@qwewer0 Will test it on my printer once more and open a pull request after that.

**Comment by ScrewThisBanana** [comment]
> @ScrewThisBanana Could you make a PR on the main bugfix-2.0.x branch?

Done. PR is ready for merge #20729

**Comment by qwewer0** [comment]
I think this can be closed.

**Comment by ScrewThisBanana** [comment]
Closed - merged.
