### ISSUE TITLE
hello , i am upload marlin 1.1x in mother board mks gen l and my lcd not work perfect

### ISSUE THREAD

**Issue by qusai210** [MarlinFirmware/Marlin#20622]
my lcd is not work perfect can you heelp me 
![WhatsApp Image 2021-01-01 at 4 04 43 AM](https://user-images.githubusercontent.com/72452941/103438285-950ab400-4be6-11eb-85dd-bb82c4e4a1a8.jpeg)

**Comment by ellensp** [comment]
Marlin 1 is no longer being developed.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
