### ISSUE TITLE
Probe Z Offset Problem

### ISSUE THREAD

**Issue by ricardoamunoz** [MarlinFirmware/Marlin#20630]
Hi I am new to this platform but need some help. I just recently upgraded an ender 3 pro with the silent 4.2.7 boards. Since I have a BL touch I went ahead and flashed the latest version of marlin as well as support for the BL touch to the board.Everything works fine except for setting my z probe offset which can be set up to 3 places after the decimal which means when setting my offset I have to scroll through 1000 numbers before I get my offset to simply 1. Please help this takes forever and I can’t possibly notice if my offset I’d going up or down. Is it possible to switch it back to a simpler 2 placed after the decimal sign?
![image](https://user-images.githubusercontent.com/76867373/103455268-8a145a00-4ca0-11eb-9d9d-1c6747044cdf.jpg)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
