### ISSUE TITLE
[BUG] TOOLCHANGE - worse procedure

### ISSUE THREAD

**Issue by DrumClock** [MarlinFirmware/Marlin#20648]
Hi,
I tested the latest version of the **bugfix 2.0.x  (3.1.2020)** and it's the same behavior when changing tools.
like here: https://github.com/MarlinFirmware/Marlin/issues/19178

files:  [Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5761566/Configuration.zip)
tool change at present : https://www.youtube.com/watch?v=1D9Tc8ZOyaU

Replacement of a tool that was in **bugfix 2.0.x dated 16.7.2020**
**is better for printing** than the current procedure.
tool change at  previously: https://www.youtube.com/watch?v=gH9YIyn2DkQ

Please repair.

**Comment by sjasonsmith** [comment]
Duplicate of #19178
