### ISSUE TITLE
Ender3 v2 pause does not work with cura[BUG] (short description)

### ISSUE THREAD

**Issue by Funfury32** [MarlinFirmware/Marlin#20666]
### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by dimonoid** [comment]
It works. You just need to wait a little(10-20 seconds). 
I assumed you are clicking pause on the printer display.

**Comment by Bluelinegecko** [comment]
I think the original poster is probably referring to problems using the pause-at-height scripts in Cura. If so it is probably related to #19870

**Comment by Funfury32** [comment]
> I think the original poster is probably referring to problems using the pause-at-height scripts in Cura. If so it is probably related to #19870 

Ok thanks
