### ISSUE TITLE
[BUG] IDEX DETECT_BROKEN_ENDSTOP causes halt

### ISSUE THREAD

**Issue by RZN-FFEvo** [MarlinFirmware/Marlin#20667]
### Bug Description

Dual X carriages fail to home when DETECT_BROKEN_ENDSTOP is enabled. Interestingly this only happens when X0 is home.

### Configuration Files

https://github.com/RZN-FFEvo/Marlin/raw/IDEX-Ender-3/Marlin/EndStopBugConfig.zip

Also enabled I2C_EEPROM

### Steps to Reproduce

1. home X with X0 endstop triggered

**Expected behavior:**

Both carriages should home

**Actual behavior:**

As soon as X1 releases its endstop
Recv: echo:Bad X Endstop?
Recv: Error:Printer halted. kill() called!

#### Additional Information

https://github.com/MarlinFirmware/Marlin/blob/ba2cadb47934fa83f576aece2c45f1b6cb5829cf/Marlin/src/module/motion.cpp#L1638

Seems to be the issue as it doesn't know or care about X1, looks like this will happen with other multi endstop configurations as well.

**Comment by ellensp** [comment]
related to https://github.com/MarlinFirmware/Marlin/issues/20237  ?

**Comment by ellensp** [comment]
On second thought looks different enough to be a separate issue

**Comment by DrumClock** [comment]
Hi,
Yes,
I confirm when the X-min endstop is closed (X1 carriage - parkinkg)
after sending the g-code G28, the printer stops with the error "parking failed".

If enstop X-max or Y-min are closed, the G28 command runs without problems.

This error is only when` ENABLED (DUAL_X_CARRIAGE)` is enabled
