### ISSUE TITLE
[FR] Allow more than one Neopixel to be a static background light.

### ISSUE THREAD

**Issue by SysGh-st** [MarlinFirmware/Marlin#20679]
### Description
In configuration.h, one can use NEOPIXEL_BKGD_LED_INDEX to tell which one of the pixel LED's to be set with a static value regardless of what the other neopixel LED's currently are set at.
However it seems this variable only allows to point at one LED only.

### Feature Workflow
Allow NEOPIXEL_BKGD_LED_INDEX to take an array at an arbitrary legth in order to allow any arbitrary LED's to be set as static background light. 
Say I'd want three LED's in random positions of the strip to be static, I'd give this: 
NEOPIXEL_BKGD_LED_INDEX { 1, 6, 11 } and have LED 1, 6 and 11 in the series to be static background light.
or
NEOPIXEL_BKGD_LED_INDEX { 0, 1, 2, 13, 14, 15 } . to have the three first and three last LED's of a 16 long LED strip as static.

#### Additional Information
It would make wiring of multiple LED strips a whole lot easier where one don't have to wire background lights separately. The background lights can be part of the neopixel strips.

**Comment by ellensp** [comment]
This has been added
see in Configuration.h 
  // Use some of the NeoPixel LEDs for static (background) lighting
  //#define NEOPIXEL_BKGD_INDEX_FIRST  0              // Index of the first background LED
  //#define NEOPIXEL_BKGD_INDEX_LAST   5              // Index of the last background LED
