### ISSUE TITLE
ENDER 3 V2 with 4.2.7 BOARD FW ISSUE

### ISSUE THREAD

**Issue by rizeddd** [MarlinFirmware/Marlin#20676]
Hi , im trying to put the firmware on my board with a custom probe , everything goes well on visual studio code , when flashing to the printer it keeps beeping , what can it be ?
I changed the envs to STM32F103RET6_creality , board #define MOTHERBOARD BOARD_CREALITY_V427 and drivers #define X_DRIVER_TYPE  TMC2208_STANDALONE, then when flashing to the board starts silent and then starts beeping continuosly and dont even start nothing on screen of it uploading , but if i go back and install the stock 4.2.7 marlin file from https://marlin.crc.id.au/ works ok , i dont understand whats the error . I'll leave the link to my configuration.h and configuration_adv.h if someone can help me , 

https://github.com/rizeddd/ender3v2427_wprobe

Thanks

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
