### ISSUE TITLE
[FR] Allow non-primary Z axis to step in a different direction

### ISSUE THREAD

**Issue by wilbur4321** [MarlinFirmware/Marlin#20677]
### Description

Per both #13470 and #10477 (and my own problems), Marlin doesn't support secondary (etc) Z axis steppers moving the opposite direction from the primary Z motor without handling it at a wiring level.

### Feature Workflow

There should be new settings (INVERT_Z2_VS_Z_DIR, etc) to allow for this to happen.

#### Additional Information

PR coming very shortly.

**Comment by thisiskeithb** [comment]
https://github.com/MarlinFirmware/Marlin/pull/20678 was merged. Closing.
