### ISSUE TITLE
How to change configuration to a delta robot not a printer?

### ISSUE THREAD

**Issue by 12343954** [MarlinFirmware/Marlin#20685]
### I wanna make a delta robot, not printer, via Marlin.

Motherboard : MKS SGEN L V2.0
Stepper driver :  TMC2225
Stepper motor : NEMA 23

Like this,
![12-12-2020 19-23-12](https://user-images.githubusercontent.com/1804003/103390674-b6b95c00-4b50-11eb-9f41-821d2d8cae12.png)

but lots of marlin delta printers like this, with sliding tracks, I don't need them.
![image](https://user-images.githubusercontent.com/1804003/103539064-59b40200-4ed2-11eb-8761-5e3d6eb8deec.png)

`M665` has 8 parameters, I don’t know what these parameters mean. Is anybody who can tell me? thank you!
![image](https://user-images.githubusercontent.com/1804003/103539201-954ecc00-4ed2-11eb-8f9f-232bb9fe986d.png)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by 12343954** [comment]
@ellensp OKay, I see.

**Comment by ellensp** [comment]
But come to the discord server, more than happy to talk about it there.

**Comment by 12343954** [comment]
@ellensp really? can you help me? how to connect with you on discard?
