### ISSUE TITLE
[Bug] M84 or M18 not turning off drivers for Azteeg X5 GT

### ISSUE THREAD

**Issue by cope413** [MarlinFirmware/Marlin#20698]
### Bug Description

Neither M84 nor M18 disable the motors on Azteeg X5 GT
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5777565/Configuration.zip)

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

Default Azteeg_X5_GT pins file

### Steps to Reproduce

As soon as printer is powered on, motors are engaged and will not disengage.

**Expected behavior:**
Motors should turn off with M84 or M18

#### Additional Information

Using TMC 2660 drivers (Panucatt Bigfoot drivers)
I've played with STEPPER_DEACTIVE_TIME with no effect.
Also played with HOLD_MULTIPLIER

M43 pin log included
[pin log.txt](https://github.com/MarlinFirmware/Marlin/files/5777573/pin.log.txt)

**Comment by ellensp** [comment]
reading https://panucattdevices.freshdesk.com/support/solutions/articles/1000227573-bigfoot-bsd2660
"alpha_en_pin - needs to be set to nc"
This would imply these drivers cannot be enabled/disabled via an IO pin.

It also says "motor_driver_control.alpha.enable           true              # alpha (X) is a TMC26X"

So I suspect you need to enable
```
  /**
   * Software enable
   *
   * Use for drivers that do not use a dedicated enable pin, but rather handle the same
   * function through a communication line such as SPI or UART.
   */
  #define SOFTWARE_DRIVER_ENABLE
```

**Comment by cope413** [comment]
I was confused by that as it is all smoothie firmware, but I suppose I should have thought about how that would apply to Marlin code.

SOFTWARE_DRIVER_ENABLE fixed it, thank you.
