### ISSUE TITLE
[BUG] Babystep/Z probe offset problem

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#20706]
Marlin 2.0.7.2 (also with bugfix 2.0.x)
Baby stepping/Z probe offset doesn't really work. No matter where I set it (plus or minus), the head not move from the table.

Z = Closed loop driver
Touch-Mi bed level sensor
BTT GTR v1.0
XYE = TMC2209

Previous answer:
"It's working, your config that is "wrong". You set BABYSTEP_MULTIPLICATOR_Z to 1...so, each baby step command will move only one single step! You set 682 steps per mm in your Z... So you need to command 682 times to move a SINGLE MILLIMETER."

Why show in display -4.171 mm ?
And if I turn the knob, the distance doesn't change either.
See the attached video.

https://user-images.githubusercontent.com/48370718/103892954-b8ed5e80-50ec-11eb-84f4-0c6c2e83a9e7.mp4

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5796050/Marlin.zip)

**Comment by rq3** [comment]
@DJDOUBLEG , you can spin that encoder until the cows come home, but don't you have to actually press the knob to make the input take effect? Just curious.

**Comment by ghost** [comment]
> 
> 
> @DJDOUBLEG , you can spin that encoder until the cows come home, but don't you have to actually press the knob to make the input take effect? Just curious.

No, Babystep (if you double-click on the menu) is already alive as you rotate the knob. No need to press.

**Comment by rq3** [comment]
> No, Babystep (if you double-click on the menu) is already alive as you rotate the knob. No need to press.

Interesting. Our printers work differently. On mine, there are two ways to get to babystep. One is a double click from the main screen, and the other is through the "Tune" menu. In both cases, the babystep doesn't actually happen until I enter the required Z axis distance, and THEN enter it. The z axis doesn't actually move while the babysteps are being entered.

**Comment by ghost** [comment]
> 
> 
> > No, Babystep (if you double-click on the menu) is already alive as you rotate the knob. No need to press.
> 
> Interesting. Our printers work differently. On mine, there are two ways to get to babystep. One is a double click from the main screen, and the other is through the "Tune" menu. In both cases, the babystep doesn't actually happen until I enter the required Z axis distance, and THEN enter it. The z axis doesn't actually move while the babysteps are being entered.

So far, in the case of double-clicking, Babystep from the main menu worked without pressing a button.

**Comment by sortagreg** [comment]
I am having this exact same issue. I can spin that knob to be +-2.000mm and nothing changes.

**Comment by Norien** [comment]
Posting to follow along as I also can't get live z-offset or babystep to work. Thanks

**Comment by rhapsodyv** [comment]
Can you test disabling `INTEGRATED_BABYSTEPPING`?

And, again, enabling `BABYSTEP_MILLIMETER_UNITS` and changing `BABYSTEP_MULTIPLICATOR_Z` to `0.1`.

**Comment by ghost** [comment]
> 
> 
> Can you test disabling `INTEGRATED_BABYSTEPPING`?
> 
> And, again, enabling `BABYSTEP_MILLIMETER_UNITS` and changing `BABYSTEP_MULTIPLICATOR_Z` to `0.1`.

Now works with this settings, but the Probe Z Offset not synchronized with babystep.
How can i syncronizing this two value?

**Comment by rhapsodyv** [comment]
Hum, what shows `M851`?

Because, having `BABYSTEP_ZPROBE_OFFSET` enable, it sincronizes with Probe Z Offset. 

Are you storing the settings, after doing baby steps? It doesn't save automatically. You need send M500, or go to menu configuration -> store settings.

**Comment by ghost** [comment]
Send: M851
Recv: Probe Offset X47.0000 Y-7.0000 Z-4.0000

In the first video see the problem. Baby step and Probe Z offset is not in syncron.

**Comment by Sh7777777** [comment]
> 
> Marlin 2.0.7.2 (also with bugfix 2.0.x)
> Baby stepping/Z probe offset doesn't really work. No matter where I set it (plus or minus), the head not move from the table.
> 
> Z = Closed loop driver
> Touch-Mi bed level sensor
> BTT GTR v1.0
> XYE = TMC2209
> 
> Previous answer:
> "It's working, your config that is "wrong". You set BABYSTEP_MULTIPLICATOR_Z to 1...so, each baby step command will move only one single step! You set 682 steps per mm in your Z... So you need to command 682 times to move a SINGLE MILLIMETER."
> 
> Why show in display -4.171 mm ?
> And if I turn the knob, the distance doesn't change either.
> See the attached video.
> 
> 
> 
> https://user-images.githubusercontent.com/48370718/103892954-b8ed5e80-50ec-11eb-84f4-0c6c2e83a9e7.mp4
> 
> [Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5796050/Marlin.zip)
>

**Comment by ghost** [comment]
Ping.
Any update?

**Comment by ghost** [comment]
it doesn't matter where I turn the Z-probe, the bed just moves down. It looks perfectly good in the video.

https://user-images.githubusercontent.com/48370718/105610221-d853df00-5dae-11eb-9800-3a6ac8f983b3.mp4

**Comment by rq3** [comment]
@DJDOUBLEG , your video shows what I would expect to see. But babystepping or off-setting isn't saved unless you explicitly do so (at least with my set-up). After a calibration, I babystep to get an excellent first layer, then add (or subtract) the babystep distance to the z-probe offset, and save that to the eeprom. For example, my "default" z-probe offset is -16.3 mm (the microswitch triggers 16.3 mm below the nozzle). I generally have to correct that to -16.25 mm after calibration, and save the change, to get consistent and reproducible first layers.

**Comment by ghost** [comment]
That's not how it's worked so far. As you can see in the second video,
babystepping could be adjusted on the fly. It could be now, but the table's
just moving away from the bed.

rq3 <notifications@github.com> ezt írta (időpont: 2021. jan. 23., Szo
21:57):

**Comment by kevinpawsey** [comment]
I had this similar issue, it wasn't 'live' stepping... I had to set **BABYSTEP_WITHOUT_HOMING** and **BABYSTEP_ALWAYS_AVAILABLE** to get it to work.

One thing that I am finding is that I can't do the double-click to get to the Z-Offset adjustment menu quickly (at the moment I am just living with it... although would be nice to have it back).  If I try and enable **DOUBLECLICK_FOR_Z_BABYSTEPPING**, it conflicts with (I think) **BABYSTEP_ALWAYS_AVAILABLE**, which then means that there has to be movement for it to work.

Anyway, might be worth checking the first two options to make sure that they are enabled for live babystepping?

**Comment by Sh8tan** [comment]
I get problem too with **BABYSTEP_ZPROBE_OFFSET** but looks like different for me.

**BABYSTEP_ZPROBE_OFFSET** are enable and replace babystep, no issues with movement, it goes up and down during print as expected for a perfect first layer but after print and doing a m500 the new offset is not applied for the next print, i still have to adjust the first layer...

When i check if the z probe offset was modified, there is no problems but not applied.

Ex: i set z probe offset to 0.100 do a g29, then g28 i can see -0.80 for z axis, set z_probe_offset during print at 0.9. When starting a new print **Z_PROBE_OFFSET** are at 0.9 but it change nothing to my print, then doing a G28 and the Z axe show -0.8.

Or someone can explain what are expected when **BABYSTEP_ZPROBE_OFFSET** is uncommented

ThX

**Comment by djdoubleg** [comment]
The bug still exists in 2.0.9. Wherever I turn the knob the bed just moves up.

**Comment by me-honest** [comment]
@Sh8tan maybe related to #19899?

**Comment by n9jcv** [comment]
@kevinpawsey Thank You, this solved my problem

**Comment by Sh8tan** [comment]
@Itox001 did you finally solve the problem ?

Still have the problem with ABL.

Z_probe_offset are change when baby stepping but not considered when start a new print.

Z_probe_offset set to 0.1 then g29, during print changing by 0.18, so perfect layer pr0n but next print or when turn off the printer I can see the new z_probe_offset from 0.1 to 0.18 but still have bad first layer...

The only way for me is to up z from 0.1 to 0.18 then set home offset ton keep the difference between the both...

**Comment by me-honest** [comment]
@Sh8tan I did not solve this particular issue, but realized that perhaps my understanding of how it's supposed to work was not right. I think that the probe Z offset is only consideresd if you are probing a mesh again, and is doesn't work as a persistent home z offset as you have found, and as I initially thought.

In the end I applied the offset to my saved mesh and it was correctly set for the subsequent prints. Anyways I have moved on to klipper now so I did not debug further.

**Comment by Sh8tan** [comment]
@Itox001 by moving to kipper you finally solved it 👌

**Comment by Sh8tan** [comment]
@Itox001 can you just tell us how did you do to add offset directly to your saved mesh without doing a g29 ? G29 S4 (new z offset ?)

Compatible with abl ?

**Comment by me-honest** [comment]
@Sh8tan I used UBL, and did it with the g-code G29 P6 Cx.x: https://marlinfw.org/docs/gcode/G029-ubl.html

**Comment by DiskDoctor** [comment]
> @Sh8tan I used UBL, and did it with the g-code G29 P6 Cx.x: https://marlinfw.org/docs/gcode/G029-ubl.html

Very interesting...

Can you please give a list of the Babystep related options you have enabled and disabled to make this work?

Due to the ABL not working properly, I am switching Ender 3 Pro w/CRTouch over to UBL.

**Comment by thisiskeithb** [comment]
Closing since OP deleted their account.

**Comment by DiskDoctor** [comment]
> Closing since OP deleted their account.

Not a good reason to close an open BUG that still exists, as does a possible workaround. Please reopen and let this play out so we can summarize the information.

**Comment by thisiskeithb** [comment]
> Not a good reason to close an open BUG that still exists

That was not confirmed and OP isn’t around to respond.

We get a lot of “me too” reports with no additional information or configs (just like in this very issue.)

Please open a new bug report and follow the template carefully, including listing the **exact steps** to reliably reproduce bug and be sure to **include your config**.

I have not seen this bug and cannot reproduce the issue on my end.

**Comment by DiskDoctor** [comment]
Gotcha. Thanks.
