### ISSUE TITLE
Live Z adjustment intermittent

### ISSUE THREAD

**Issue by soaringpaul** [MarlinFirmware/Marlin#20705]
This is probably not a bug, but an error on my part.
I have two printers, an Ender 2 and a Geeetech I3, both with Marlin 1.1.9 and both showing the same issue, which is that live Z adjustment for the first layer sometimes works, and sometimes does not, the display always shows the adjustment but the Z axis does not travel.
I can load the same GCode and live Z will work and next time not. It seems to be random. I get the same result with Live Z or Babystepping.
Can anyone suggest what I might have wrong?
My Start Gcode:

M300 S300 P1000 ; beep for 1 second
M0 Insert Z Switch
M420 S1 ;turn levelling on?
M420 Z10 ; bed levelling faded by layer 10
G28 ;Home

M140 S50 ; set bed probe temp
M104 S160 ; set extruder probe temp
M109 S160 ; wait for extruder probe temp
M190 S50 ; wait for bed probe temp

G29 ;Autolevel
G1 Z10.0 F3000 ;Move Z Axis up
M104 S{material_print_temperature} ;Start heating extruder
M140 S{material_bed_temperature}   ;Start heating bed
M109 S{material_print_temperature} ;Wait for extruder to reach temp before proceeding
M190 S{material_bed_temperature} ;Wait for bed to reach temp before proceeding
M300 S300 P1000 ; beep for 1 second
M0 Remove Z Switch
G92 E0 ;Reset Extruder

G1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position
G1 X10.1 Y100.0 Z0.28 F1500.0 E8 ;Draw the first line
G1 X10.4 Y100.0 Z0.28 F5000.0 ;Move to side a little
G1 X10.4 Y20 Z0.28 F1500.0 E15 ;Draw the second line
G92 E0 ;Reset Extruder

**Comment by ellensp** [comment]
Marlin 1.1.x is no longer being worked on.  

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
