### ISSUE TITLE
[BUG] Reboot near end of gcode File in SD Card "SPI init fail" - serial Not Work when Heating 

### ISSUE THREAD

**Issue by softwarecrash** [MarlinFirmware/Marlin#20739]
### Bug Description

Delta Printer with TMC2130, BTT SKR 1.4 TURBO, reprap full graphic display

The printer makes at a specific Z Height a reboot, in the sample gcode file at Z37.7-Z38.5 the display tell "SD Init Fail"
a test with lower SD Speed didnt resolve the problem, other SD Card formated other sd reader too
its not a error of the gcode or slicer, testet wit cura slicer
testet with createt model and ready to use stl files

edit: after varius test it looks like the reboot comes after a length of extrudet material

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

Configuration Files:
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/5793048/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/5793028/Configuration_adv.h.txt)
[pins_BTT_SKR_common.h.txt](https://github.com/MarlinFirmware/Marlin/files/5793046/pins_BTT_SKR_common.h.txt)

Stl Files:
Sliced with 0,1 height the reboot comes up:
[CFFFP_Chat_Noir_Bell_Top.gcode.txt](https://github.com/MarlinFirmware/Marlin/files/5793065/CFFFP_Chat_Noir_Bell_Top.gcode.txt)

Sliced with 0,4 height without the reboot
[testbody.stl.txt](https://github.com/MarlinFirmware/Marlin/files/5793070/testbody.stl.txt)

Sliced with 0,1 heigth and the error comes up
[testfile 70.stl.txt](https://github.com/MarlinFirmware/Marlin/files/5793078/testfile.70.stl.txt)
[CFFFP_testfile 70.gcode.txt](https://github.com/MarlinFirmware/Marlin/files/5793114/CFFFP_testfile.70.gcode.txt)

If you've made any other modifications describe them in detail here.
Switched two pins in the skr common file for the fans, but i think this is 

### Steps to Reproduce

1. [Testet with old Marlin config version 200006 and 200000 in both version this error not come up, but another error (extruder randomly pulls out and turn back) marlin version config 20007 and upper this bug shows up]
2. [createt varius files height >50mm the printer abort with a reboot]
3. [tested with a minimal config to run the printer, withe the same result]

**Expected behavior:**

**Actual behavior:**

The printer reboot at a z height and the display tells "SD INIT FAIL"
#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by rhapsodyv** [comment]
I noted you are using `#define SDCARD_CONNECTION LCD`. This issue happens if you use the ONBOARD sd?

**Comment by softwarecrash** [comment]
> 
> 
> I noted you are using `#define SDCARD_CONNECTION LCD`. This issue happens if you use the ONBOARD sd?

tested now, with the internal SD Card the error comes not up,
the internal sd i can only acces over usb

Edit:
i have change the microsteps in config #define XYZ_MICROSTEPS from 256 to 16, without any changes to the m96 command to korrekt the steps, the steps the same, and now it prints, i will test it on ohter larger models

**Comment by bill-orange** [comment]
Are you sure that this relates to the SD card?  Can you print from Proterface or Octopi?

**Comment by softwarecrash** [comment]
> 
> 
> Are you sure that this relates to the SD card? Can you print from Proterface or Octopi?

i think its not a SD problem

**Comment by rhapsodyv** [comment]
Enable this: `NO_SD_HOST_DRIVE`, so your onboard SD will not be shared with host, then you can print with it.

I suspect your issue is on the LCD SD slot, or in the SPI, or the cable.

**Comment by softwarecrash** [comment]
> 
> 
> Enable this: `NO_SD_HOST_DRIVE`, so your onboard SD will not be shared with host, then you can print with it.
yeah i found it and testet
> I suspect your issue is on the LCD SD slot, or in the SPI, or the cable.

since i have edit the microsteps the printer runs at the moment.
LCD SD slot was replaced by another new lcd, cable checked and replaced, all witghout success

Update: After some test with the postet changes, the printer restarts again. the issue still alive
the only change is that the message "sd init fail" not comes

Next Update:
I have replaced Board, Display, cable, Driver, SD Cards without success.
The board reboot, Show the Bootscreen and weit for User Input Like the printer switched on.
So i think its Not a Hardware issue

Error:SD read error
[ERROR] Error:SD read error

Error:SD read error
[ERROR] Error:SD read error

Error:SD read error
[ERROR] Error:SD read error

Error:SD read error
[ERROR] Error:SD read error

but the sd card is ok, tested with others

**Comment by softwarecrash** [comment]
Update: After some test with the postet changes, the printer restarts again. the issue still alive

**Comment by softwarecrash** [comment]
Next Update:
I have replaced Board, Display, cable, Driver, SD Cards without success.

The board reboot, Show the Bootscreen and weit for User Input Like the printer switched on.

So i think its Not a Hardware issue

**Comment by softwarecrash** [comment]
attached the gcode who stopped the printer and a video of the issue.
[stopping gcode.txt](https://github.com/MarlinFirmware/Marlin/files/5824944/stopping.gcode.txt)

**Comment by softwarecrash** [comment]
the gcode area who stopps the printer
[stopping gcode.txt](https://github.com/MarlinFirmware/Marlin/files/5824950/stopping.gcode.txt)
and a video

**Comment by softwarecrash** [comment]
i have found the problem!!! :D

my extruder driver overheating, thats not a problem, in the config is set that by overheat it decerase the current

the print abort after this message
00:30: E driver overtemperature warning! (1000mA)

without the decerase message.

so i think the funktion has a malefunction or the message that the driver current decerase was disturbs the communication with the sd card.

when i decerase the current the print end normaly.
