### ISSUE TITLE
movement issue form LCD control

### ISSUE THREAD

**Issue by ZeeshanSar** [MarlinFirmware/Marlin#20743]
hi, i have uploded marlin basic fireware on arduino mega and have an issue. while controlling from PC my printer is working fine but while moving an axis form LCD menu the axis moves for a bit and then stop again move and stop video attached for reference.
how I can fix this issue.

best regards,
Zeeshan sarwar

https://user-images.githubusercontent.com/72921977/104150603-37ebdb00-53fc-11eb-81cf-e8af67b36f55.mp4

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by ZeeshanSar** [comment]
configuration file link below
 https://drive.google.com/file/d/1BgfvpI_d4BobPUKoBZbk-X0onU_LGpMk/view?usp=sharing
