### ISSUE TITLE
LCD support for SKR mini e3

### ISSUE THREAD

**Issue by ZeeshanSar** [MarlinFirmware/Marlin#20742]
hi, i am usking skr mini e3 and have a Reprap LCD which is not supported for the BTT products and the supported LCDs are not available in my region can you please add Reprap support for SKR mini e3.

best regards,
Zeeshan Sarwar

**Comment by ellensp** [comment]
The skr mini e3  only has 1 * 10 pin socket, you cannot plug LCD's that have 2 * 10 pin cables into it.
