### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by GurenWolf** [MarlinFirmware/Marlin#20744]
Hello Everyone.

To begin with, I am using an **Anycubic Kossel Linear Plus** with the latest Marlin firmware as of now (**Marlin-2.0.7.2**), **Bigtreetech SKR1.3** board and **TFT35 V2.0 display**.

### Bug Description

M106 P1 S255 doesn't turn on secondary fan.

### Configuration Files

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5794303/Marlin.zip)

### Steps to Reproduce

1. In configuration_adv.h, this line was added: **#define E0_AUTO_FAN_PIN P2_04**.
2. After uploading firmware, test M106 P0 S255 and see how it actually works.
3. M106 P0 S0 to turn off primary fan.
4. M106 P1 S255 to try to turn on secondary fan, which, from the pins file on an SKR V1.3, is in pin **2.4** (or as cryptically written in Marlin, **P2_04**).

**Expected behavior:**

Secondary fan should turn on.

**Actual behavior:**

Secondary fan doesn't turn on.

**Comment by ellensp** [comment]
you cannot control an auto fan. It tuns on automatically when hot end exceeds  specified temperature.
