### ISSUE TITLE
[BUG] BIGTREE_GTR_V1_0_usb_flash_drive fails with "no match MCU defined"

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#20750]
GTR_v1.0
Latest 2.0.x bugfix
default_envs = BIGTREE_GTR_V1_0_usb_flash_drive
Can not compile the code.
I get this error: #error "no match MCU defined" (any many more pin map error e.g.:error: 'PB12' undeclared here (not in a function); did you mean 'PB_12'?)
When i set back to: default_envs = BIGTREE_GTR_V1_0
Then compiles well.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5798454/Marlin.zip)

**Comment by Sh7777777** [comment]
Yes

**Comment by sjasonsmith** [comment]
This happens because the `usb_flash_drive` environment doesn't inherit the build_flags from the normal GTR environment, so it is missing some MCU defines.

Adding those doesn't completely solve the problem, though. It just gets you to the next failures.

**Comment by margaale** [comment]
Sorry to bring this back to life, but how could i get it to compile?

**Comment by gaby64** [comment]
I need help with this aswell

**Comment by thisiskeithb** [comment]
Is this something you can look at @rhapsodyv?

**Comment by gaby64** [comment]
Im having the same problem but with BIGTREE_SKR_PRO

**Comment by thisiskeithb** [comment]
We don't need more "me toos" since the bug is confirmed & easily reproducible. I pinged rhapsodyv since they added this feature initially for MKS boards, but it should have also worked on others like the SKR Pro or GTR with flash drive support.

**Comment by rhapsodyv** [comment]
Fixed here: #21197

**Comment by ghost** [comment]
New build: 
![kép](https://user-images.githubusercontent.com/48370718/109299482-79faa000-7835-11eb-964f-8bf2b5fb5279.png)
:(

**Comment by rhapsodyv** [comment]
You need to download my branch and not use -1 as serial port.

**Comment by rhapsodyv** [comment]
Merged
