### ISSUE TITLE
[FR] Block for M22 command during SD card print

### ISSUE THREAD

**Issue by bipsendk** [MarlinFirmware/Marlin#20757]
### Description

If prinitng from SDcard, the status can be obtained via M27.
But if someone by mistake issues a M22, the gcode processing will stop.
I suggest, that the M22 command will be invalid to use while the printer actively is using the SDcard - so the card cannot be released by mistake.

### Feature Workflow

1. Start print from SD (either via LCD/menu or M23/M24)
2. Wait for the printer to start printing (after bed/extruder heat-up)
3. Issue M22 command
4. Error message is returned, telling that SDprint is active.

Once print has finished (or has been stopped/aborted, e.g. via M524), it should be possible to use M22 again.

#### Additional Information

Not sure if M21 issue during active SD print can be affected as well.

**Comment by thisiskeithb** [comment]
Added in https://github.com/MarlinFirmware/Marlin/commit/e8aa6ab7354ee438067c605b72907d9bf69df3fb
