### ISSUE TITLE
Flashed newest version of Marlin 2.0.7.2 and now stepper motors are not moving

### ISSUE THREAD

**Issue by mikac10** [MarlinFirmware/Marlin#20770]
Hi, i have flashed the newest version of marlin 2.0.7.2 and now my stepper motors are not moving. I am using board skr 1.3 stepper drivers TMC2209 in uart mode. I also reflashed the older version that i used ,to verify if that motors were moving and it was okay.I have no idea what to do.. Please someone help me thanks.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5809673/Marlin.zip)

**Comment by ellensp** [comment]
Already solved on reprap forum. 

User incorrectly enabled SOFTWARE_DRIVER_ENABLE
