### ISSUE TITLE
[BUG][DWIN] Encoder scroll seems to act as button press as well.

### ISSUE THREAD

**Issue by CRCinAU** [MarlinFirmware/Marlin#20774]
Builds after the 2021-01-12 date stamp seem to have a regression where selecting input values will exit the input field after scrolling one step.

This can be reproduced via navigating to: Prepare -> Motion -> Steps/mm -> Steps/mm E

Press the button to select, then scroll to change the value. The value will change by 0.1 and then exit the selection.

Configs:
https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Creality/Ender-3%20V2

A quick browse of the commit history since the 12th throws this up as a likely candidate, but unable to confirm atm:
https://github.com/MarlinFirmware/Marlin/commit/4a897310252341f203371cb2e99f93bf9c035143

Cc: @thinkyhead (author of referenced commit)

EDIT: Added video of bug in operation:
https://drive.google.com/file/d/1KXdWzq4B2kpas_CeQwPpjN_EiEXXH9Vv/view

**Comment by dimonoid** [comment]
2b928b4 has the same problem

**Comment by JohnClementine** [comment]
Just wanted to chime in and say I'm also experiencing this behavior

**Comment by dimonoid** [comment]
What was your latest working commit? @CRCinAU

**Comment by gmergulhao** [comment]
Have same issue. I can add that this was working fine on nightly build on 29.12 for the ender 3 v2.

**Comment by dimonoid** [comment]
> 
> 
> Have same issue. I can add that this was working fine on nightly build on 29.12 for the ender 3 v2.

Have you flashed the monitor firmware only, or board also

**Comment by gmergulhao** [comment]
I've flashed the board firmware only [Ender3-V2-BLTouch-20210114.bin](https://marlin.crc.id.au/firmware/Ender%203%20V2%20-%20BLTouch/)

DWIN_SET I'd have to compile first. Should I go for it? Still stock that came on the printer. Bought it around Christmas.

Thank you for your Input!

**Comment by CRCinAU** [comment]
This is not related to the DWIN screen firmware.

**Comment by dimonoid** [comment]
https://github.com/MarlinFirmware/Marlin/commit/4472ba2b6bc0835d0fcc039ad66d9dab40e13010

Using binary search, I found that this bug is in this commit. You are welcome.
Also, my IDE is complaining on syntax errors in this commit.
I used the latest DWIN_SET.

**Comment by SamLefebvre** [comment]
Thanks @dimonoid I use the old commit and it's working.

**Comment by MD3D20** [comment]
i too am having this issue. what can i do to fix it im new to firmware programming
