### ISSUE TITLE
SD Card use FAT32

### ISSUE THREAD

**Issue by rdacomp** [MarlinFirmware/Marlin#2080]
Use FAT32 when using the SD Card. If there are difficulties I can help.

**Comment by ntoff** [comment]
What do you mean? I'm already using FAT32 on my SD card

**Comment by rdacomp** [comment]
The fact that it is not working.

**Comment by rdacomp** [comment]
The fact that it is not working.
RAMPS 1.4 no sd card format fat32!!!

**Comment by thinkyhead** [comment]
@rdacomp http://www.marlinfirmware.org/index.php/Reporting_Bugs

FAT32 has been implemented in Marlin. Are you having a problem with yours?

**Comment by ntoff** [comment]
I have 2 RAMPS 1.4 boards, one with a full graphics LCD and one with just a regular 4 line LCD, both with SD readers and both read FAT32 just fine.

Are you using an SD reader built into a LCD display or an addon SD reader module?

**Comment by thinkyhead** [comment]
@rdacomp The output of `M20` can be misleading, if that is the only interface that's accessed. There is some rudimentary long filename support, so for example, when you use an LCD controller you will see long filenames listed on the screen. However, you are correct that the full interface to the long filenames has not been implemented for the G-Code to select an SD file, `M23`. And hosts also do not have access to long filenames through the firmware. I would like to see that fixed also.

As it so happens, I was just messing around in the SD file code, making some tweaks so that lsDive would work properly. Must be kismet…. #2081

**Comment by rdacomp** [comment]
I use kit sainsmart.
http://www.sainsmart.com/mega2560-smart-lcd-2004-controller-a4988-ramps-1-4-3d-printer-kit-for-reprap.html
Later configuration.h and attach files that you have requested.
I have tried several types of cards but no one sees it.
Run and look SanDisk absurd. My proposal to solve all problems in software.

**Comment by thinkyhead** [comment]
Did you read this? http://forums.reprap.org/read.php?4,322514

This setup video is very helpful. https://www.youtube.com/watch?v=KsIFGKBaD3U

I use [basically the same controller](http://www.thingiverse.com/thing:80065).

**Comment by rdacomp** [comment]
And not only that. I've already the entire Internet rummaged.
Many people use USB and simply do not use the SD Card!
Therefore, the problem is still not solved.

**Comment by ntoff** [comment]
@thinkyhead That looks like it's more to do with the pins just being wrong for a specific motherboard (the megatronics) but rdacomp said he bought a kit containing a RAMPS board which has no SD card so as long as he's using the correct (and by now default) ramps_13_efb pinout then it _should_ "just work" shouldn't it?

The issues I see on that forum look like they come from the pins just being wrong. Unless I'm missing something.

**Comment by thinkyhead** [comment]
@ntoff
I use the very same controller with RAMPS and it performs well.
I recommend using my case for it too. :grin: 

So also I see it [mentioned here](http://www.fabric8r.com/forums/showthread.php?1510-So-I-just-received-my-SainSmart-LCD-Smart-controller-12864) trying to get it to work with a Printrbot board:

> the smart controller's onboard SD slot would not work without at least one connection to the motherboard's EXP1 header…

**Comment by rdacomp** [comment]
But I also expect that ramps_13_efb 33 should still work. But it is not. I checked all the connections and contacts. All OK. But the SD Card is not working.

**Comment by ntoff** [comment]
I already have the Velleman equivalent on the frankenprinter with box and a full graphics controller on the mendel90 (embedded into the frame)

**Comment by rdacomp** [comment]
I try this option
http://www.fabric8r.com/forums/showthread.php?1510-So-I-just-received-my-SainSmart-LCD-Smart-controller-12864/page2
Maybe you want to disable JTAG?

**Comment by ntoff** [comment]
There doesn't seem to be an easy to find schematic of the LCD board, what you could do is trace the pins that go from the SD card, figure out their function from the SD card spec sheet and make sure they go to the right pins on the RAMPS board. I had to do this when I converted my 3drag / k8200 controller over to work on a RAMPS board.

**Comment by AnHardt** [comment]
schematic is here: http://reprap.org/wiki/RepRapDiscount_Smart_Controller

Had problems with the provided cables before. Check the cables by swapping them. If then the display fails, you know why.

**Comment by rdacomp** [comment]
Сhanged.

**Comment by AnHardt** [comment]
@rdacomp 
Result?

**Comment by rdacomp** [comment]
LCD operates. SD Card is not!

**Comment by rdacomp** [comment]
pins.h
Line 1474 change pin from 26 to 40:

```
#define SDSS 40 //QU-BD_Ups SD Chip Select
```

sd2card.cpp
Line 303 add new line:

```
pinMode(PB_SS_PIN, OUTPUT);
```

Lines 305-308 comment out "IF" lines, change SS_PIN to low and set PB_SS_PIN to high:

```
//#if SET_SPI_SS_HIGH
digitalWrite(SS_PIN, LOW);
digitalWrite(PB_SS_PIN, HIGH);
//#endif // SET_SPI_SS_HIGH
```

sd2pinmap.h
LINE 225-226 change 20 to 40 and add new line:

```
uint8_t const SS_PIN = 40; // F2
uint8_t const PB_SS_PIN = 26; // B6
```

**Comment by AnHardt** [comment]
@rdacomp 
pins.h Line 1474 is somewhere in the ulimaker part when using Marlin 1.0.2. This is for sure irrelevant.

In later Marlins there is no Line 1474 at all.

Please update.

**Comment by thinkyhead** [comment]
@rdacomp We only support the latest Development code. Are you describing how you got it working with Marlin 1.0.2?

**Comment by thinkyhead** [comment]
@rdacomp Ah, I see, you are quoting from [So-I-just-received-my-SainSmart-LCD-Smart-controller](http://www.fabric8r.com/forums/showthread.php?1510-So-I-just-received-my-SainSmart-LCD-Smart-controller-12864&p=19292&viewfull=1#post19292)

Do those changes make it work with Marlin 1.0.2? (If so, we can figure out how to do the equivalent with 1.0.3 dev).

**Comment by boelle** [comment]
closing this one as several people are using fat 32 without any issue... myself included
