### ISSUE TITLE
[BUG] Delta TMC homing current reduction is not applied to Z

### ISSUE THREAD

**Issue by elvisior** [MarlinFirmware/Marlin#20820]
I've tested with bugfix-2.0.0 but when you look here:

https://github.com/MarlinFirmware/Marlin/blob/5ee1087959f88dc60386ff3caa21e75d9e20b128/Marlin/src/gcode/calibrate/G28.cpp#L253

You can see pretty clearly that the code never sets the Z homing current or reset it later on.

Expected behaviour on a delta is that when you set a reduced homing current for trinamic stepper drivers that x, y, and z have their currents reduced.

What is occurring is that x and y are reduced but z is not.

I noticed this while trying to get sensorless homing to work on my delta with skr 1.4 turbo/tmc 2209 with yesterday's bugfix-2.0.0
I'm happy to raise a merge request with my fix if that's ok?

**Comment by archteryx** [comment]
Does your Delta printer homing reliably now? Can you have a successful calibration after this homing fix? I have issues trying sensorless homing with Marlin 2.0.x and bugfix-2.0.x. on my Anycubic Kossel LP with SKR 1.4 and TMC 2209.  Even though it looks like working, x-axis back off some mm. Could you share the fix.
