### ISSUE TITLE
Onboard Micro SD nomore working after Flash

### ISSUE THREAD

**Issue by thomas0000000** [MarlinFirmware/Marlin#20836]
Hello , I have the Sidewinder x1 v4 with orginal TFT Controller V1 and BTT SKR 1-4 Turbo Tmc 2009s in Uart with removed Senssorles Homing Pins .

After i flashed the current Firmware provided here together with the linked tft mod , My onboard micro sd reader works nomore , or just a second when i turn it on (not enough for flashing)
(maybe wrong Pins set in Configuration_adv.h?)

Thats i going to bee a Horrible Problem because i forgot to deactivate Sensorless homig so my baby is Unusable atm

To flash from usb is gonna be a Problem to because the sidewinder is an ass**** or i just had the wrong instructions . Tryed nearly evrything out there.

is this allready known ? is a solution out there ?  Dont say i have to say good bye he is only 1 month old

**Comment by ellensp** [comment]
No Setting in Marlin have any effect on the operation of the bootloader that loads in new firmware from the onboard SD card. Its a separate program run before marlin is executed.
Reformat your SD card and try again, if it still fails, see below.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
