### ISSUE TITLE
[BUG] Touch screen freezes after Restore Defaults or M502

### ISSUE THREAD

**Issue by anarchocactus** [MarlinFirmware/Marlin#20849]
### Bug Description

When using "Restore Defaults" on a FLSUN Q5 Delta Printer the touch screen (classic ui) freezes. I can still control the printer with a terminal connection

### Configuration Files

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5856291/configuration.zip)

### Steps to Reproduce

1. Go to "Restore Defaults" and execute

Manually by GCODE

1. M502

**Expected behavior:**

Touch screen should not become inresponsive

**Actual behavior:**

Touch screen freezes

#### Additional Information

I am currently working on bugfix-2.0.x (d5d01d16a7a4865e726d9918855c2096e317c661) as of 18.01.2021

**Comment by rhapsodyv** [comment]
Classic UI code should start touch calibration screen, when there's no default calibration values on the config and the eeprom has been reseted.
The code should be added at the menu item level, starting touch calibration screen.
