### ISSUE TITLE
[BUG] bugfix-2.0 throws warnings

### ISSUE THREAD

**Issue by alicephilippa** [MarlinFirmware/Marlin#20842]
### Bug Description

Compiling bugfix-2.0 under platformio for the Robin Nano v1.0 (robin_nano35) generates warnings.

Linking .pio\build\mks_robin_nano35\firmware.elf
.pio/build/mks_robin_nano35/src/src/MarlinCore.cpp.o: In function `manage_inactivity(bool)':
C:\Users\Baggins\Documents\GitHub\Marlin/Marlin\src/MarlinCore.cpp:454: warning: undefined reference to `MSerial1'
.pio/build/mks_robin_nano35/src/src/MarlinCore.cpp.o: In function `setup()':
C:\Users\Baggins\Documents\GitHub\Marlin/Marlin\src/MarlinCore.cpp:1272: warning: undefined reference to `MSerial1'
.pio/build/mks_robin_nano35/src/src/core/serial.cpp.o: In function `serialprintPGM(char const*)':
C:\Users\Baggins\Documents\GitHub\Marlin/Marlin\src\core/serial.cpp:37: warning: undefined reference to `MSerial1'
.pio/build/mks_robin_nano35/src/src/core/serial.cpp.o: In function `serial_echopair_PGM(char const*, char const*)':
C:\Users\Baggins\Documents\GitHub\Marlin/Marlin\src\core/serial.cpp:41: warning: undefined reference to `MSerial1'
.pio/build/mks_robin_nano35/src/src/core/serial.cpp.o: In function `serial_echopair_PGM(char const*, char)':
C:\Users\Baggins\Documents\GitHub\Marlin/Marlin\src\core/serial.cpp:42: warning: undefined reference to `MSerial1'
.pio/build/mks_robin_nano35/src/src/core/serial.cpp.o:C:\Users\Baggins\Documents\GitHub\Marlin/Marlin\src\core/serial.cpp:43: warning: more undefined references to `MSerial1' follow

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. Configure for robin_nano35 based delta printer
2. Build

**Expected behavior:**

No warnings thrown.

**Actual behavior:**

Warnings thrown.

#### Additional Information

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5851810/Configuration.zip)

**Comment by ellensp** [comment]
In Marlin/src/HAL/STM32F1/MarlinSerial.cpp 
```
#if DISABLED(MKS_WIFI_MODULE)
  DEFINE_HWSERIAL_MARLIN(MSerial1, 1);
#endif
```
ie only if MKS_WIFI_MODULE is disabled then enable MSerial1

you have got to great lengths to enable MKS_WIFI_MODULE
```
//#if ENABLED(TFT_LVGL_UI)
  #define MKS_WIFI_MODULE  // MKS WiFi module
//#endif

```
Do not do this.
Although this may be a mks wifi module, you do not enable that define unless you also have a TFT_LVGL_UI 

set it how it was
```
#if ENABLED(TFT_LVGL_UI)
  //#define MKS_WIFI_MODULE  // MKS WiFi module
#endif

```
and your wifi will work as expected using serial_port_2 and the warnings will be gone.
