### ISSUE TITLE
Erreur de Compilation Module Motion

### ISSUE THREAD

**Issue by LE-BLANC-Dom** [MarlinFirmware/Marlin#20854]
Bonsoir,
La compilation génère une erreur.
Firmware : Marlin 2.0.7.2
Machine Ender-2 Pro 4.2.7
Board : CREALITY V427
Architectures STM32F1
Environments : STM32F103RET6_creality

Erreur : 

Marlin\src\module\motion.cpp:513:100: error: 'HOMING_FEEDRATE_Z' was not declared in this scope

Resultat

*** [.pio\build\STM32F103RET6_creality\src\src\module\motion.cpp.o] Error 1
================================================================================================= [FAILED] Took 268.10 seconds ================================================================================================= 

Environment             Status    Duration
----------------------  --------  ------------
STM32F103RET6_creality  FAILED    00:04:28.101
============================================================================================= 1 failed, 0 succeeded in 00:04:28.101 =============================================================================================

Par avance Merci de votre réponse

Dominique LE BLANC

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by LE-BLANC-Dom** [comment]
Bonsoir,

 

Je vous communique les fichiers de configuration que j’utilise

 

Se sont ceux que j’ai téléchargés sans avoir effectuer aucune modification de ma part

 

Cordiales Salutations

 

Dominique LE BLANC

 

De : ellensp <notifications@github.com> 
Envoyé : vendredi 22 janvier 2021 22:13
À : MarlinFirmware/Marlin <Marlin@noreply.github.com>
Cc : LE-BLANC-Dom <dom.le-blanc@evhr.net>; Author <author@noreply.github.com>
Objet : Re: [MarlinFirmware/Marlin] Erreur de Compilation Module Motion (#20854)

 

Please attach your configuration files.

**Comment by ellensp** [comment]
From where?  We need configuration files to test this, otherwise we are just guessing.

**Comment by LE-BLANC-Dom** [comment]
Du site marlin
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5858833/Marlin.zip)

**Comment by ellensp** [comment]
this is the wrong version. it has CONFIGURATION_H_VERSION 020008, this is for bugfix.  You need CONFIGURATION_H_VERSION 020007

Use this https://github.com/MarlinFirmware/Configurations/archive/release-2.0.7.2.zip

**Comment by LE-BLANC-Dom** [comment]
Bonne soirée.
Ca marche merci de cette assistance rapide et efficace.

Cordiales Salutations
Dominique LE BLANC
