### ISSUE TITLE
[BUG] Creality 4.2.7 mainboard wrong chips source code

### ISSUE THREAD

**Issue by MeSoLost** [MarlinFirmware/Marlin#20855]
I can't comment on issue #19029 https://github.com/MarlinFirmware/Marlin/issues/19029 and I think I found their source code you wanted.  Folder certainly looks like the bugfix 2.0.x folder I got last night.  Awesome work btw.  Downloaded, set, and compiled new firmware myself in a night.  Board was advertised as having 2208 chips but the only creality firmware that actually worked was the 2225 version.  (arguing with eBay seller about this typo now)  Reading through that issue I believe you all wanted the source for creality's 32 bit board and I think I accidently found it.

https://drive.google.com/drive/folders/1mYtIQV9ewZL2OH_QA2JMT3wRDXvO7yDq

if the link disappears or doesn't work I downloaded the source zip at least and can send it to you.  Sorry for dropping this in as a bug.  I have no idea how to message anyone on here if it's even possible. Special thanks to 5x5 leveling grid and 0.01 resolution on settings now. ^_^  Printer works a lot better with the firmware I compiled from you guys directly.

**Comment by sjasonsmith** [comment]
This doesn't seem to be reporting a bug, so I am closing this.

The 4.2.7 board already works in Marlin and has example configurations for v1 printers.
