### ISSUE TITLE
[BUG] TMC CURRENT_STEP_DOWN not work

### ISSUE THREAD

**Issue by softwarecrash** [MarlinFirmware/Marlin#20866]
### Bug Description

the function CURRENT_STEP_DOWN in configuration_adv doesnt work
it comes the warning that overheating, but it not decerase the driver current

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/5860806/Configuration_adv.h.txt)
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/5860807/Configuration.h.txt)

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. in a comlete tmc2130 setup, set the current of E to 1000 and lets amount of short retractions run 
2. warning that overheat comes
3. check the current, its on the set value not decerased

**Expected behavior:**

**Actual behavior:**

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by thinkyhead** [comment]
I see that it won't go below a value of 50, but otherwise the code is trying to make it happen. Enable `REPORT_CURRENT_CHANGE` to get some extra messages and see if it gives any clues.
