### ISSUE TITLE
Z-Probe distance does not move the z-axis

### ISSUE THREAD

**Issue by pixartist** [MarlinFirmware/Marlin#20860]
This issue has been opened and not solved several times already and it is still happening. I have an ender 3 pro with an SKR mini e3 v2 and the z-axis calibration is definitely not working most of the time. Apparently it is fixable by enabling baby stepping, but I actually don't wanna use that because in my experience it causes very inconsistent results. Using the latest marlin.

**Comment by ellensp** [comment]
non valid bug report, hasn't followed template, no configs. In sufficient information to do anything with. Closing
