### ISSUE TITLE
[BUG] MKS Robin Nano v1.2+TFT35+TMC2209(UART), E1 is displayed instead of E0 in the Configuration-Advanced Settings-TMC Drivers menu of the lcd

### ISSUE THREAD

**Issue by ghmajx** [MarlinFirmware/Marlin#20875]
### Bug Description

My 3D Printer is TwoTrees Sapphire Pro, it uses MKS Robin Nano v1.2+TFT35, I replaced 2208 and 4988 with 4 TMC2209. I moded TMC2209 to use UART on Robin Nano V1.2.  I used bugfix-2.0.x branch of "Configurations/config/examples/Two Trees/Sapphire Pro/Configuration.h" and "Configuration.adv.h" to compile my firmware. My extruder is working properly, I think it’s just not displaying properly.

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.
[Marlin-configure.zip](https://github.com/MarlinFirmware/Marlin/files/5864003/Marlin-configure.zip)
```
//Configuration.h

#define SPRO_TMC2209 // Enable for the TMC2209 driver version
#if ENABLED(SPRO_TMC2209)
  #define E0_DRIVER_TYPE TMC2209
#else
  #define E0_DRIVER_TYPE A4988
#endif
//#define E1_DRIVER_TYPE A4988
```
```
//Configuration.adv.h

  #define E0_SLAVE_ADDRESS 0
  //#define E1_SLAVE_ADDRESS 0
  #define E0_SERIAL_TX_PIN                  PC13
  #define E0_SERIAL_RX_PIN                  PC13

  #ifdef E1_DRIVER_TYPE
      #define E1_SERIAL_TX_PIN                PA9
      #define E1_SERIAL_RX_PIN                PA9
  #endif
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

It should show E0 instead of E1

**Actual behavior:**

![photo_2021-01-25_11-20-13](https://user-images.githubusercontent.com/13009231/105657912-5ffd3300-5f00-11eb-824d-a73909fc6e78.jpg)
![photo_2021-01-25_11-20-19](https://user-images.githubusercontent.com/13009231/105657920-64c1e700-5f00-11eb-86a8-742091f16336.jpg)
![photo_2021-01-25_11-20-23](https://user-images.githubusercontent.com/13009231/105657927-67244100-5f00-11eb-9e21-743ecd8bd1f0.jpg)
#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by katodo** [comment]
I would like to build the same FW, which board did you choose from Marlin/buildroot/share/PlatformIO/boards/ ?
