### ISSUE TITLE
[BUG] Fysetc mini 12864 v2.1 - backlight LED turns off after PID autotune

### ISSUE THREAD

**Issue by bipsendk** [MarlinFirmware/Marlin#20881]
### Bug Description

Fysetc Mini 12864 v2.1 neopixel display turns off background light after bed PID autotune.

### Configuration Files

Attached
[Conf-12864-BedTune.zip](https://github.com/MarlinFirmware/Marlin/files/5869218/Conf-12864-BedTune.zip)

### Steps to Reproduce

1. Configure marlin with attached files
2. Run autotune on bed : M303 E-1 S75 C5
3. When PID autotune ends, the background LED of the display is turned off.

**Expected behavior:**

Display background LED backlight would still be on.

**Actual behavior:**

When PID autotune ends, the background LED of the display is turned off.

#### Additional Information

This has been defined in order to (hopefully) have steady background light on the display:

  #define NEOPIXEL_BKGD_LED_INDEX  0               // Index of the LED to use
  #define NEOPIXEL_BKGD_COLOR { 255, 255, 255, 0 } // R, G, B, W

**Comment by bipsendk** [comment]
Observed on 2.0-bugfix pulled 20210124

**Comment by bipsendk** [comment]
Just tried extruder hotend PID tune - the backlight LED is switched off here as well once the PID autotune has completed.

**Comment by 3Duke3** [comment]
I can confirm this, happend on hotend PID tune for me.

**Comment by ellensp** [comment]
@3Duke3 can we get your configs also?

**Comment by 3Duke3** [comment]
Bare with me, new to Github. Not new to Marlin, but certainly no expert.

I am having seperate troubles with behaviour of tool changes on Dual_X but noticed the screen go black on PIDautotune the other day.

While screen is black you can faintly see the letters and head to display - turn on LED

hows best to attach files, zipped like this?

[CONFIG.zip](https://github.com/MarlinFirmware/Marlin/files/5876775/CONFIG.zip)
