### ISSUE TITLE
[FR] Integrate a Refresh Card/Media function.

### ISSUE THREAD

**Issue by TurboUSMC** [MarlinFirmware/Marlin#20886]
I use a TF card to SD card coversion cable for prints on my Ender 3, primarily because SD cards are far easier to handle physically. This is a pretty common mod it seems, as there are numerous designs on Thingiverse for this purpose.

When I got my Ender 3, the firmware had a "refresh card" function (may not be exact words) I used it all the time when I would remove the card, load a new print, and reinsert card. Worked great with the MicroSD to SD cable. Since updating the board to a 4.2.7, none of the firmware I've had seems to have this function. (I also know NOTHING about coding... I just want to have someone more capable than me bring the function back in a future firmware update)  The firmwares I've tried now typically have a "card inserted" notification on the LCD, but this is essentially worthless since the conversion cable is ALWAYS plugged in, regardless of if there is actually a card inserted on the other end which it will not re-reference.

The only way to get the printer to re-fresh and actually look at the card again is to power cycle. Which kills my preheated status and is otherwise just obnoxious. 

Thanks for considering.

**Comment by thisiskeithb** [comment]
Enable `NO_SD_DETECT`:

https://github.com/MarlinFirmware/Marlin/blob/876c2586b9146dd123af4c7b21138b8239ef5d39/Marlin/Configuration_adv.h#L1398-L1399
