### ISSUE TITLE
[BUG] Ender 3 V2 M18/M84 not honoring flags

### ISSUE THREAD

**Issue by eblieb** [MarlinFirmware/Marlin#20899]
Printer: Ender 3 V2
Firmware: Smith3d E3V2-2.0.x.16 - Based on Marlin 10-01-2021 

My Cura End G-Code has
M84 X Y E ;Disable all steppers but Z

But this isn't being respected, the Z stepper is still disabling after the print is done. According to Merlin documentation M84 and M18 should be the same exact thing and should respect the flags.

**Comment by ellensp** [comment]
We cannot support 3rd party forks of Marlin. You have to create a issue on their github.
If you install real actual marlin and can reproduce this bug. Then we can revisit this
