### ISSUE TITLE
[FR] CUSTOM_USER_MENUS for LVGL UI

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#20892]
Board: MKS robin nano v.2
Last marlin 2.x bugfix

After activating CUSTOM_USER_MENUS in configuration_adv in the "Tools" menu, the item "more" should appear.
In fact, nothing appears. Three weeks ago, everything worked.
My configs:
[conf.zip](https://github.com/MarlinFirmware/Marlin/files/5875946/conf.zip)

**Comment by Malderin** [comment]
![photo_2021-01-27_20-52-38](https://user-images.githubusercontent.com/52313714/106032508-9c3bb980-60e1-11eb-9963-00c3709147e1.jpg)
![photo_2021-01-27_20-52-44](https://user-images.githubusercontent.com/52313714/106032513-9d6ce680-60e1-11eb-8f52-c57f3f9163a8.jpg)

**Comment by rhapsodyv** [comment]
Seems the "More" menu never existed in official marlin... I think your issue is with the stock firmware.

@makerbase-mks @MKS-Sean @mks-viva can you confirm this? Maybe it's missing PR.

**Comment by Malderin** [comment]
@rhapsodyv .
this is a fork of the official marlin 2.x bugfix, where I added pr with mks wifi, where the menu "more" works with the same configs:
https://github.com/Malderin/Marlin_2.0.x_official/tree/Marlin-2.0_bugfix_MKS_WIFI.
I will repeat myself. The more menu worked about 3 weeks ago.

**Comment by rhapsodyv** [comment]
You can take a look at the history of the file draw_tool.cpp ... it never had the button "more" on marlin: https://github.com/MarlinFirmware/Marlin/commits/bugfix-2.0.x/Marlin/src/lcd/extui/lib/mks_ui/draw_tool.cpp

**Comment by rhapsodyv** [comment]
> I will repeat myself. The more menu worked about 3 weeks ago.

You can repeat yourself as much as you want. It will not help anyone to be right or wrong here.

**Comment by Malderin** [comment]
> You can take a look at the history of the file draw_tool.cpp ... it never had the button "more" on marlin: https://github.com/MarlinFirmware/Marlin/commits/bugfix-2.0.x/Marlin/src/lcd/extui/lib/mks_ui/draw_tool.cpp

You may be right, sorry

**Comment by rhapsodyv** [comment]
Probably we just need ask MKS to send it to Marlin Official, as it's clearly already done in their repo (or somewhere).

**Comment by Malderin** [comment]
I corrected myself. Someone removed the #define USER_CMD_1_ENABLE parameters from the configuration_adv.h (and 2, 3 ... 7). Therefore, the "more" menu was empty.

> Probably we just need ask MKS to send it to Marlin Official, as it's clearly already done in their repo (or somewhere).

In their repository (MKS) this was done a long time ago. The problem is that their code is very different from the code in the official marlin.

**Comment by MKS-Sean** [comment]
@rhapsodyv @Malderin Hello, I will submit a PR to marlin soon to fix some code problems of lvgl

**Comment by rhapsodyv** [comment]
Merged
