### ISSUE TITLE
Trouble compiling Marlin for my Ender 2 V2 Printer.

### ISSUE THREAD

**Issue by Spideypunk** [MarlinFirmware/Marlin#20908]
Hello everyone,

I'm brand new to all of this and am trying to update the firmware for my Ender 3 V2 printer by Creality. I've been using the video by Teaching Tech to guide me but have hit a snag. I downloaded all the lasted bug-fixed files and configuations. 

Every time I try to build using the Marlin Auto Build extension in VS Code It comes up with this error message:

> Executing task: C:\Users\pastorjustin\.platformio\penv\Scripts\pio.exe run <

Processing STM32F103RET6_creality (platform: ststm32@~10.0; board: genericSTM32F103RE; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
buildroot/share/PlatformIO/scripts/common-dependencies.h:31:10: fatal error: e:\6?ender 3 v2 firmware\marlin\src\inc\marlinconfig.h: Invalid argument
 #include "../../../../Marlin/src/inc/MarlinConfig.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CalledProcessError: Command '"C:\Users\pastorjustin\.platformio\packages\toolchain-gccarmnoneeabi\bin\arm-none-eabi-g++.exe" -DTARGET_STM32F1 -D__MARLIN_FIRMWARE__ -DARDUINO_ARCH_STM32 -DTEMP_TIMER_CHAN=4 -D__MARLIN_DEPS__ -w -dM -E -x c++ buildroot/share/PlatformIO/scripts/common-dependencies.h' returned non-zero exit status 1.:
  File "C:\users\pastorjustin\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 168:
    env.SConscript(item, exports="env")
  File "C:\Users\pastorjustin\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Script\SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\pastorjustin\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Script\SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "E:\6\u3001Ender 3 V2 Firmware\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 334:
    apply_features_config()
  File "E:\6\u3001Ender 3 V2 Firmware\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 148:
    if not env.MarlinFeatureIsEnabled(feature):
  File "C:\Users\pastorjustin\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "E:\6\u3001Ender 3 V2 Firmware\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 299:
    load_marlin_features()
  File "E:\6\u3001Ender 3 V2 Firmware\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 287:
    define_list = subprocess.check_output(cmd, shell=True).splitlines()
  File "C:\Users\pastorjustin\.platformio\python3\lib\subprocess.py", line 411:
    **kwargs).stdout
  File "C:\Users\pastorjustin\.platformio\python3\lib\subprocess.py", line 512:
    output=stdout, stderr=stderr)
==================================================================== [FAILED] Took 1.87 seconds ==================================================================== 

Environment             Status    Duration
----------------------  --------  ------------
STM32F103RET6_creality  FAILED    00:00:01.873
=============================================================== 1 failed, 0 succeeded in 00:00:01.873 ===============================================================The terminal process "C:\Users\pastorjustin\.platformio\penv\Scripts\pio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

Can anyone please help? I have no idea what's going on.

**Comment by ellensp** [comment]
No config files, didn't follow template, and seem to be a support question not a bug or issue.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
