### ISSUE TITLE
[FR] Allow Different temperatures for M600 unload and load

### ISSUE THREAD

**Issue by ssendev** [MarlinFirmware/Marlin#20910]
### Description

When changing filament type with M600 during a print it would be nice to have M600 keep the current temperature do the unload change the target temperature and then load the filament.

### Feature Workflow

currently it behaves like:
1. encounter M600
2. move to parking position
3. wait till hotend has target temperature
4. filament is unloaded
5. beep
6. user changes filament presses continue
7. wait till hotend has target temperature
8. filament is loaded
9. move to saved position
10. print continues

now there are 2 possibilities to change the temperature during a print before and after the M600

* before using M104 or M109: causes an unneeded and unwanted delay at step 3 or 0 that may heat the current filament too much
* after using M104: means the filament doesn't have the right temperature when the print continues
* after using M109: causes oozing directly above the print

#### Additional Information

First I tried to split the M600 with M701 M702 but didn't get it working as well as the M600 maybe it would be enough to document which command sequence would do the same thing as a M600 but from a usability perspective having a parameter to change the target temperature before step 7 would be nicer

**Comment by qwewer0** [comment]
I think `M600` has an `R` parameter for this, as `M600 R<resume temperature>`.
