### ISSUE TITLE
Feature request: Bed PID options in the LCD menu

### ISSUE THREAD

**Issue by ntoff** [MarlinFirmware/Marlin#2091]
Hot end options are in there and since the heated bed also supports PID, could we get some options in the LCD menu for changing, or at least viewing the current, PID settings for the heated bed?

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
