### ISSUE TITLE
MKS Robin Nano 2.The rotary encoder only works in one direction

### ISSUE THREAD

**Issue by altiber** [MarlinFirmware/Marlin#20918]
### Bug Description

The rotary encoder only works in one direction. The menu items are switched in one direction regardless of the direction of rotation of the encoder. Display - MKS TS 35 with encoder from the factory.

### Configuration Files
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/5891806/Configs.zip)

**Comment by rhapsodyv** [comment]
Tested and it's fully working for me. Probably you have a wiring or soldering issue. Take a look if the encoder is firmly on the board. It could be a cable issue too.

Try testing another ui: TFT_COLOR_UI or TFT_CLASSSIC_UI. If the problem persist, it almost sure you have a hardware issue.
