### ISSUE TITLE
[BUG] [IDEX]  E1 Motion sensor dosent work in duplication mode

### ISSUE THREAD

**Issue by LorenzoSaini** [MarlinFirmware/Marlin#20929]
### Bug Description

When i print in duplication mode, using the bigtreetech filament smart sensor, only the extruder 0 detect if the filament ran out, but when i print with only one extruder or in auto_parking all works as expected.

### Steps to Reproduce

setup a printer with motion sensor and idex, start print in duplication and let the filament ran out on the second extruder.

**Expected behavior:**

Printer pause

**Actual behavior:**

Printer continue printing

#### Additional Information
I'm using marlin 2.0.6.1 but the problem is present also in 2.0.7.2 , SKR Pro v1.2.
I think this problem exist because in duplication mode the active extruder is E0.

**Comment by Roxy-3D** [comment]
> I think this problem exist because in duplication mode the active extruder is E0.

Yes.  Very possible.   If BigTreeTech is willing to loan a machine, I'll get this corrected (what ever the root cause of the problem is) for you.  And of course, get the fix merged back into the code base so it doesn't show up any more on BigTreeTech machines.
