### ISSUE TITLE
[BUG] Temperature no longer reported to OctoPrint

### ISSUE THREAD

**Issue by viper93458** [MarlinFirmware/Marlin#20921]
### Bug Description

Somewhere between yesterday morning and the most recent merges within 24 hours, OctoPrint can no longer read temperatures from my SKR Pro 1.0. It worked when I used Bugfix 2.0 from yesterday morning sometime (-8 PST) but when I used the latest bugfix this morning the issue cropped up. It causes OctoPrint to disconnect due to multiple timeouts.

### Configuration Files
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/5895797/Configs.zip)

### Steps to Reproduce

Use the current bugfix 2.0 and connect to SKR 1.0 with Octoprint. It appears to connect OK but no temperature data is reported. This causes OctoPrint to throw an error about multiple timeout retires exceeded.

**Expected behavior:**

Temperatures would display

**Actual behavior:**

No temperature is displayed and the host disconnects.

#### Additional Information

I will do my best to provide any additional details as needed. I am not a developer so please be gentle. Thanks for your wonderful work and contributions to 3D printing and Open Source!

**Comment by lightmaster** [comment]
I was able to roll back to the commit 9e004a94963771167bb3f5d6fa51ccd671a27a19 and it started working again, so it must be something related to PR #20913.

**Comment by viper93458** [comment]
@lightmaster Thanks for the advise! I'll see if I can accomplish that. Unless a fix comes forth sooner. :)

**Comment by TheLion** [comment]
I noticed the same thing on my SKR 1.3. I did notice that Octoprint doesn't time out anymore when a print is started.

**Comment by GMagician** [comment]
I confirm. It seems autotemp report is not working

**Comment by GMagician** [comment]
After digging into code it seems that is called the template function (empty) instead of overridden one

**Comment by Z18Aplha** [comment]
Is there a quickfix?

**Comment by GMagician** [comment]
Not yet, I think @thinkyhead should give a look at code to understand why override is not taking place

**Comment by benlye** [comment]
> Is there a quickfix?

This worked for me (one line change in autoreport.h):
https://github.com/MarlinFirmware/Marlin/pull/20913#issuecomment-770227265

**Comment by GMagician** [comment]
yep that may solve but I think that virtual will add a cost in its call that is not desired

**Comment by drgimpfen** [comment]
> > Is there a quickfix?
> 
> This worked for me (one line change in autoreport.h):
> [#20913 (comment)](https://github.com/MarlinFirmware/Marlin/pull/20913#issuecomment-770227265)

can confirm this worked also for me.

**Comment by Z18Aplha** [comment]
> > Is there a quickfix?
> 
> This worked for me (one line change in autoreport.h):
> [#20913 (comment)](https://github.com/MarlinFirmware/Marlin/pull/20913#issuecomment-770227265)

thx! i disabled the autoreport timeout in octoprint instead, works fine too. Octoprint polls Temperature now.

**Comment by X-Ryl669** [comment]
The fix I've proposed is not optimal. We'll find a better solution.

**Comment by X-Ryl669** [comment]
Can you try #20959, it should solve the building issue and also re-enable auto reporting correctly.

**Comment by benlye** [comment]
> Can you try #20959, it should solve the building issue and also re-enable auto reporting correctly.

Working here.

**Comment by viper93458** [comment]
Seems to be working for me again so I will close this out. Thanks!

-William
