### ISSUE TITLE
[Solved] Compile error for Fysetc S6 + Fysetc TFT81050

### ISSUE THREAD

**Issue by kunpoolsion** [MarlinFirmware/Marlin#20923]
Latest Marlin bugfix-2.0.x #20711
Hardware combination:
Anet A8 Plus chasis
Fysetc S6 1.2 Board
Fysetc TFT81050 (portratit mode)
TMC2209 drivers (3 extruders, single nozzle)

Compilation errors when TOUCH_UI_DEVELOPER_MENU is selected in adv file:

`Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/screens/stress_test_screen.cpp: In static member function 'static void StressTestScreen::onIdle()': Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/screens/stress_test_screen.cpp:123:24: error: 'G28_STR' was not declared in this scope; did you mean 'M24_STR'?`

Fixed adding:
`extern const char G28_STR[];`

at the bottom of src/lcd/extui/lib/ftdi_eve_touch_ui/compat.h

**Comment by ellensp** [comment]
PR created
