### ISSUE TITLE
missing units

### ISSUE THREAD

**Issue by 2tata** [MarlinFirmware/Marlin#20954]
Its not clear what kind of length is meaning here. I assume inches ? or mm?

Does that mean the length which will be comes out of the nozzle or just the length in meaning the rotation of the motor? I assume last.

https://github.com/MarlinFirmware/Marlin/blob/5ee1087959f88dc60386ff3caa21e75d9e20b128/Marlin/Configuration.h#L575

thank you for the nice commended config file :)

**Comment by thisiskeithb** [comment]
`EXTRUDE_MAXLENGTH` is mm.

If you send an extrude command higher than this value, Marlin will prevent it and display an error message.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
