### ISSUE TITLE
[BUG] Can't compile with SDSUPPORT disabled

### ISSUE THREAD

**Issue by Guilouz** [MarlinFirmware/Marlin#20961]
### Bug Description

Impossible to success a compilation when #define SDSUPPORT is disabled.

<img width="1492" alt="106402276-07122b00-6429-11eb-9b94-af680cf736e7" src="https://user-images.githubusercontent.com/12702322/106402584-73d9f500-642a-11eb-925a-0a77a71bb9bf.png">

### Configuration Files

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/5901201/Configurations.zip)

**Comment by ellensp** [comment]
This PR fixes it.

**Comment by Guilouz** [comment]
> This PR fixes it.

Confirmed, it's working. Thanks.
