### ISSUE TITLE
error: the value of 'CardReader::auto_report_port' is not usable in a constant expression

### ISSUE THREAD

**Issue by kylix-rd** [MarlinFirmware/Marlin#20960]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5901122/Configuration.zip)

### Bug Description

Latest version of bugfix-2.0.x branch fails to build if AUTO_REPORT_SD_STATUS and more than one serial port is defined (HAS_MULTI_SERIAL is true).

### Steps to Reproduce

1. Drop config files into place.
2. Build with platformio & Auto Build Marlin

**Expected behavior:**

Successful compile

**Actual behavior:**

d:\src\marlin\marlin\src\sd\cardreader.h:187:62: error: the value of 'CardReader::auto_report_port' is not usable in a constant expression

**Comment by ellensp** [comment]
this should be fixed in latest bugfix
