### ISSUE TITLE
[BUG] ("more" menu in LVGL, no description)

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#20984]
### Bug Description

When activating CUSTOM_USER_MENUS in configuration_adv.n, captions to the "more" menu buttons are not shown (except for the G-code button). Instead, it says "Text" everywhere.
![photo_2021-02-03_11-02-53](https://user-images.githubusercontent.com/52313714/106716355-1a65f780-65dd-11eb-8781-2978816efabb.jpg)

### Configuration Files

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5916922/Configuration_adv.zip)

**Comment by Malderin** [comment]
I fixed it like this:
https://github.com/Malderin/Marlin_2.0.x_official/commit/bf987eafa3377ca9a8757e11eee21a0a03ae2377

**Comment by sjasonsmith** [comment]
I am presuming that @Malderin's merged PR fixes this issue, since they both reported the bug and contributed the fix.
