### ISSUE TITLE
[BUG/FR] SPI MODE sanity check ask to define Step/Dir pins , but UNUSED. (Don't compile when using these GPIOS elsewhere)

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#20991]
SPI MODE  don't need Step/Dir pins , and these pins can be used  for any other functionnality , but impossible to compile if Step/Dir are not defined for steppers

Please modifiy sanity check 

Thks

**Comment by ManuelMcLure** [comment]
SPI is only used to configure the drivers. Step/Dir are still used for motion.

**Comment by ellensp** [comment]
ManuelMcLure is correct. All marlin stepper drivers use STEP and DIRECTION pins, other interfaces are for setup and configurations

**Comment by studiodyne** [comment]
Wrong ! UART is just a setup interface
SPI is a full motion and setup bus , and if the drivers is in SPI mode , step/dir not functionnal 
I will check this

**Comment by ellensp** [comment]
not in marlin, not implemented

**Comment by studiodyne** [comment]
I want to cry 😢  
I need GPIOS ......
Thks
