### ISSUE TITLE
[FR] Support second UART to have other bitrate

### ISSUE THREAD

**Issue by Teddyz** [MarlinFirmware/Marlin#21006]
### Description

Make it possible to have `SERIAL_PORT_2` using a new setting `BAUDRATE_2`

### Feature Workflow

I think this code in MarlinCore.cpp will solve this:
```
  #if HAS_MULTI_SERIAL
    #if defined(BAUDRATE_2)
      MYSERIAL1.begin(BAUDRATE_2);
    #else
      MYSERIAL1.begin(BAUDRATE);
    #endif
    serial_connect_timeout = millis() + 1000UL;
    while (!MYSERIAL1 && PENDING(millis(), serial_connect_timeout)) { /*nada*/ }
  #endif
```
Configuration.h:
```
#define BAUDRATE 250000
#define BAUDRATE_2 9600

```
#### Additional Information

Some documentation in Configuration.h is needed.
I did some basic testing on my Mega2560-board (Trigorilla_14) and it seems to work, but I am no expert.

**Comment by thisiskeithb** [comment]
Implemented in https://github.com/MarlinFirmware/Marlin/pull/21949
