### ISSUE TITLE
Toggle PSU

### ISSUE THREAD

**Issue by goroph1** [MarlinFirmware/Marlin#21014]
add code to the M80 command to allow a Togging of the psu state, M80 S reports the state, how about M80 T toggles it. My code adjustment for M80_M81.cpp is below.  I have implemented this change on my printer and the code seems to be working great. This makes it simpler to add a single button input to control the state of the psu with things like OctoPrint. 

#if ENABLED(PSU_CONTROL)

  #if ENABLED(AUTO_POWER_CONTROL)
    #include "../../feature/power.h"
  #endif

  // Could be moved to a feature, but this is all the data
  bool powersupply_on;

  #if HAS_TRINAMIC
    #include "../../feature/tmc_util.h"
  #endif

  /**
   * M80   : Turn on the Power Supply
   * M80 S : Report the current state and exit
   */
  void GcodeSuite::M80() {

    // S: Report the current power supply state and exit
    if (parser.seen('S')) {
      serialprintPGM(powersupply_on ? PSTR("PS:1\n") : PSTR("PS:0\n"));
      return;
    }
    
    ///////////////////////////////////////////////////////////////////////
    // T: Toggles the state of the power supply
    if (parser.seen('T') && powersupply_on) {
      GcodeSuite::M81();
      return;
    }
    ///////////////////////////////////////////////////////////////////////
    else
      PSU_ON();

    /**
     * If you have a switch on suicide pin, this is useful
     * if you want to start another print with suicide feature after
     * a print without suicide...
     */
    #if HAS_SUICIDE
      OUT_WRITE(SUICIDE_PIN, !SUICIDE_PIN_INVERTING);
    #endif

    #if DISABLED(AUTO_POWER_CONTROL)
      delay(PSU_POWERUP_DELAY); // Wait for power to settle
      restore_stepper_drivers();
    #endif

    #if HAS_LCD_MENU
      ui.reset_status();
    #endif
  }

#endif // ENABLED(PSU_CONTROL)

**Comment by thisiskeithb** [comment]
Resolved in https://github.com/MarlinFirmware/Marlin/pull/22304
