### ISSUE TITLE
[BUG] New Warning on Melzi build

### ISSUE THREAD

**Issue by bill-orange** [MarlinFirmware/Marlin#21029]
### Bug Description

This is a warning not an error.  Since it is new, it is probably worth reporting. The error is in twi.c.

```
C:\Users\William\.platformio\packages\framework-arduino-avr\libraries\Wire\src\utility\twi.c: In function '__vector_26':
C:\Users\William\.platformio\packages\framework-arduino-avr\libraries\Wire\src\utility\twi.c:552:7: warning: empty declaration
       __attribute__ ((fallthrough));
       ^
C:\Users\William\.platformio\packages\framework-arduino-avr\libraries\Wire\src\utility\twi.c:638:7: warning: empty declaration
       __attribute__ ((fallthrough));

```
### Configuration Files

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5952447/Marlin.zip)

### Steps to Reproduce

1. Compile
2. Observe warning
3. Observe otherwise successful compile

**Expected behavior:**

No warning.

**Actual behavior:**

New warning

#### Additional Information

This was a Melzi build for `default_envs = sanguino1284p` . I strongly suspect that this is a result of an update to Platformio although I could be wrong.  I often am.

**Comment by ellensp** [comment]
This is in platformio\packages\framework-arduino-avr\libraries\Wire\src\utility\twi.c
This is not part of marlin, it is part of platfomio's package framework-arduino-avr that marlin uses.
