### ISSUE TITLE
Ender 3 silent motherboard 4.2.7 filament runout crash

### ISSUE THREAD

**Issue by testnco** [MarlinFirmware/Marlin#21023]
Hi,

### Bug Description

I want to use a mechanical filament runout sensor. I made an diy one following the schematic below but I also tried with the old z endstop I kept.

![image](https://user-images.githubusercontent.com/45320002/107277826-45c16a00-6a55-11eb-9144-e3d221eada58.png)

When I use mine, when I plug the 5V on NO and GND on NC (I also tried to invert and gives me the opposite result) and signal on signal marlin boot, when I use M119 it gives me TRIGGERED when I put filament on it also gives me TRIGGERED but when I unload it, the board crash and reboot.

When I use the old z endstop I gives me the same except that when I put filament it start to crash and boot quickly.

I plugged on the pin below, from left to right, 5V, GND, signal.

![image](https://user-images.githubusercontent.com/45320002/107278360-f62f6e00-6a55-11eb-8832-49a37c5cf357.png)

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

Here the changes I made on `Configuration.h` :
```
#define FILAMENT_RUNOUT_SENSOR
#if ENABLED(FILAMENT_RUNOUT_SENSOR)
  #define FIL_RUNOUT_ENABLED_DEFAULT true // Enable the sensor on startup. Override with M412 followed by M500.
  #define NUM_RUNOUT_SENSORS   1          // Number of sensors, up to one per extruder. Define a FIL_RUNOUT#_PIN for each.

  #define FIL_RUNOUT_STATE     LOW        // Pin state indicating that filament is NOT present.
  #define FIL_RUNOUT_PULLUP
```     

Here the changes I made on `Configuration_adv.h` :
```
#define ADVANCED_PAUSE_FEATURE
#if ENABLED(ADVANCED_PAUSE_FEATURE)
  #define PAUSE_PARK_RETRACT_FEEDRATE         60  // (mm/s) Initial retract feedrate.
  #define PAUSE_PARK_RETRACT_LENGTH            2  // (mm) Initial retract.
                                                  // This short retract is done immediately, before parking the nozzle.
  #define FILAMENT_CHANGE_UNLOAD_FEEDRATE     10  // (mm/s) Unload filament feedrate. This can be pretty fast.
  #define FILAMENT_CHANGE_UNLOAD_ACCEL        25  // (mm/s^2) Lower acceleration may allow a faster feedrate.
  #define FILAMENT_CHANGE_UNLOAD_LENGTH      250  // (mm) The length of filament for a complete unload.
                                                  //   For Bowden, the full length of the tube and nozzle.
                                                  //   For direct drive, the full length of the nozzle.
                                                  //   Set to 0 for manual unloading.
  #define FILAMENT_CHANGE_SLOW_LOAD_FEEDRATE   6  // (mm/s) Slow move when starting load.
  #define FILAMENT_CHANGE_SLOW_LOAD_LENGTH     0  // (mm) Slow length, to allow time to insert material.
                                                  // 0 to disable start loading and skip to fast load only
  #define FILAMENT_CHANGE_FAST_LOAD_FEEDRATE   6  // (mm/s) Load filament feedrate. This can be pretty fast.
  #define FILAMENT_CHANGE_FAST_LOAD_ACCEL     25  // (mm/s^2) Lower acceleration may allow a faster feedrate.
  #define FILAMENT_CHANGE_FAST_LOAD_LENGTH     0  // (mm) Load length of filament, from extruder gear to nozzle.
```
Thanks for your help.

**Comment by stef-ladefense** [comment]
connect red to 5V, black to 0V and green to signal
when you have no filament, the swicht is NC, so signal = 5V
with a filamant the switch goes to NO, so sognal = 0V

out in your configuration file, you have:
#define FIL_RUNOUT_STATE LOW // **Pin state indicating that filament is NOT present.**

so change it to
#define FIL_RUNOUT_STATE HIGH

and check that your pin is correctly declared
#define FIL_RUNOUT_PIN on the correct pin of your card in your card's pin declaration file

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
