### ISSUE TITLE
[BUG] TOUCH_MI probe + LEVEL_BED_CORNERS + LEVEL_CORNERS_USE_PROBE

### ISSUE THREAD

**Issue by clifo** [MarlinFirmware/Marlin#21032]
When I activate LEVEL_BED_CORNERS, I have to manually activate the TOUCH_MI probe.
During homing and bed_leveling, the probe is activated automatically.

[config.zip](https://github.com/MarlinFirmware/Marlin/files/5954101/config.zip)

**Comment by ellensp** [comment]
The firmware has no way to see what hardware you have.
There is no way to automatically select your type of probe
