### ISSUE TITLE
[BUG] Reporting Bed Topography cause printer reset

### ISSUE THREAD

**Issue by jwchen119** [MarlinFirmware/Marlin#21045]
### Bug Description

Device: Delta printer
MB: Bigtreetech Skr v1.3
Driver: TMC2208x4
Firmware: Latest Marlin-bugfix-2.0.x

The bug is reporting Bed Topography cause printer reset.
This is odd because I can't perform any G29 command with T
I found this bug when I want to calibrate my bed manually by perform G29 P2 B T. When it go down the bed and shows the point 1 on Pronterface, my printer reset without any verbose.

When perform G29 T, results is the picture below.

![image](https://user-images.githubusercontent.com/10509360/107588754-6baa6280-6c3f-11eb-8347-667cf159809b.png)

### Configuration Files

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5962374/Marlin.zip)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/5963328/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/5963329/Configuration_adv.txt)

### Steps to Reproduce

Method A.
  1. Press button on LCD
  2. Press Motion
  3. Press Unified Bed Leveling
  4. Press Output Mesh Map
  5. Press Output for Host
  6. Printer reset after step 5

Method B.
  1. Using Pronterface to connect to printer.
  2. Send command "G29 T"
  3. Printer reset after step 2

Method C.
  Any G29 command combined with T

**Expected behavior:**

My printer should not reset.

**Actual behavior:**

My printer reset.

**Comment by Roxy-3D** [comment]
Attaching Configuration.h files would help.    But this kind of 'feels' like a previous GCC optimization problem where the stack space  was being used to freely by the compiler.   (More details can be provided if the topic is interesting to anybody.)

With that said, the 'T' parameter is so simple I kind of doubt that would blow things up if the other options are working properly.

A very simple way to disprove the GCC optimization theory would be to move the 'T' option into its own .CPP file and see if it keeps misbehaving.

**Comment by ManuelMcLure** [comment]
Could this be a timing thing with a too long loop causing the watchdog to trigger?

**Comment by jwchen119** [comment]
> Attaching Configuration.h files would help. But this kind of 'feels' like a previous GCC optimization problem where the stack space was being used to freely by the compiler. (More details can be provided if the topic is interesting to anybody.)
> 
> With that said, the 'T' parameter is so simple I kind of doubt that would blow things up if the other options are working properly.
> 
> A very simple way to disprove the GCC optimization theory would be to move the 'T' option into its own .CPP file and see if it keeps misbehaving.

I've update the txt file although the Marlin.zip contained Configuration.h.

**Comment by GMagician** [comment]
I had this same issue, in the same place, but that has been fixed by #20985, sure your Marlin is up to date?

**Comment by jwchen119** [comment]
> I had this same issue, in the same place, but that has been fixed by #20985, sure your Marlin is up to date?

Oh, I thought 2021-1-31 should be fresh enough.
Will download the latest one and report if it fixed.

**Comment by jwchen119** [comment]
OK, looks like https://github.com/MarlinFirmware/Marlin/pull/20985 help this issue out.
Case close now, thanks for helping!
