### ISSUE TITLE
[BUG] (Power loss recovery -> print starts over)

### ISSUE THREAD

**Issue by grishien** [MarlinFirmware/Marlin#21058]
### Bug Description

Power loss recovery -> print starts over
I know it was reported several times.
I know it was marked as "solved" several times.
But here we go again, latest bugfix starts printing from the start on PLR.

### Configuration Files

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5969379/configuration.zip)

### Steps to Reproduce

1. Start print
2. Cut power
3. Turn on power
4. Hit "resume print"

**Expected behavior:**
5. Enjoy continuation of printing

**Actual behavior:**
5. Get surprised that the job has started over

#### Additional Information

N/A

**Comment by thinkyhead** [comment]
Have you had any luck in tracking down the cause or in solving the issue?

Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
