### ISSUE TITLE
[BUG] Fan speed not working in new Ender 3 V2 status area

### ISSUE THREAD

**Issue by Leo06ba** [MarlinFirmware/Marlin#21067]
Yesterday i flashed the new marlin bugfix with the upgraded status area, and i noticed that the fan speed doesn't work, both with manual setting from the control menu or during prints. Am i doing something wrong? Or it's just not fully integrated yet?

**Comment by CRCinAU** [comment]
Took me a while to figure out what this bug report meant..... The fan does actually work - but the fan icon remains at 0.

See pic:
![image](https://user-images.githubusercontent.com/3992884/107864134-b92c0700-6ead-11eb-9b7f-b53f9ea558a4.png)

**Comment by Leo06ba** [comment]
> Took me a while to figure out what this bug report meant..... The fan does actually work - but the fan icon remains at 0.
> 
> See pic:
> ![image](https://user-images.githubusercontent.com/3992884/107864134-b92c0700-6ead-11eb-9b7f-b53f9ea558a4.png)
> 

Exactly. Sorry for my poor explaining skills.

**Comment by ellensp** [comment]
This fix has been merged. Closing

**Comment by hfjim-coder** [comment]
I have a question. How to fix it if it isn't fixed already?

**Comment by ellensp** [comment]
you look at the PR's files that where changed https://github.com/MarlinFirmware/Marlin/pull/21072/files and you edit your copy of marlin with this change. Or you download current bugfix,
