### ISSUE TITLE
G92 on Delta...

### ISSUE THREAD

**Issue by MagoKimbra** [MarlinFirmware/Marlin#2106]
On delta G92 have a bug...
The probem is on

```
if (didXYZ) sync_plan_position();
```

I correct with:

```
#if defined(DELTA) || defined(SCARA)
  if (didXYZ) sync_plan_position_delta();
#else
  if (didXYZ) sync_plan_position();
#endif
```

**Comment by thinkyhead** [comment]
How did that get missed for so long? Only the Shadow knows….

**Comment by MagoKimbra** [comment]
G92 isn't a command that I use a lot, I use it to find the offset between the probe and nozzle.

Date: Sun, 17 May 2015 17:39:58 -0700
