### ISSUE TITLE
[BUG] Skips heating, leveling, homing, etc., starts from the movements

### ISSUE THREAD

**Issue by 3DFrontier** [MarlinFirmware/Marlin#21062]
### Bug Description
I have a CoreXY with Skr 1.4 turbo + TFT35 V3 + Marlin last bugfix
I got this weird bug while I was activating and deactivating linear advance.
I printed the file A.gcode, all ok.
Then I activated linear advance in marlin, I generated a test gcode with the provided suit and printed it, all ok.
Then I printed A again with LA activated; during the print I accidentally put the fan 100% and got printer halted; no prob, it was expected from my setup.
The result I got was bad so i deactivated LA. I'm pretty sure I didn't mess with marlin, I only commented out LA (then I also compared to a previous version of configs files).
When I tried to print the file B.gcode something goes wrong, the printer totally skips homing, heating, leveling, acceleration setup; it starts directly from the movements.
I tought something was wrong with B, so I tried A again, and got the same problem. The file that before LA was ok, during LA was ok, after didn't print anymore.
My tests were:
Use the USB stick on TFT
Use the SD card on mainboard
Recompile the same FW
Elaborate the gcode again

I found a workaroud, the problem is with PrusaSlicer headers, since I tried Cura and was fine (but the problem is not PrusaSlicer since the same gcode worked before). I started deleting row by row in A and got 2 results.
With A_1 I got "Unknown command"M"" But there is no empty M.
With A_2 I got it working. But rows I deleted don't have anything special

### Configuration Files

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/5970660/Configurations.zip)

[Gcode.zip](https://github.com/MarlinFirmware/Marlin/files/5970824/Gcode.zip)

### Steps to Reproduce

Just print the A File with that FW
A_2, same gcode without PrusaSlicer headers prints well

**Expected behavior:**

Printing as usual, heating, leveling, etc.
**Actual behavior:**

The print starts directly from the movements, skipping heating, leveling or any gcode before

**Comment by chepo92** [comment]
I may be not skipping the comment lines in the header because special characters, try two cases: remove all "=" chars in the header, and remove ".", My bet is the presence of one of those probably "=" is making it not skip the comment line
