### ISSUE TITLE
[BUG] (Layer Shift 2.0.5.3 & 2.0.7.2 )

### ISSUE THREAD

**Issue by ngen33r** [MarlinFirmware/Marlin#21074]
Bug Description:
Layer shift still appears to not be resolved:

Tested Firmware Versions:
2.0.5.3
2.0.7.2
Latest 2.0.X BugFix

Configuration Files:
*From 2.0.7.2 Compile*
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5976873/Configuration_adv.zip)

If you've made any other modifications describe them in detail here.
None

Steps to Reproduce
Compile and run a print from either USB or SD card.

Expected behavior:
NO layer shift.

Actual behavior:
Layer shifts happen randomly. Trying different config options to attempt to isolate issue, Shifts vary from minimal to extreme.
![20210213_212213](https://user-images.githubusercontent.com/26206019/107866760-f490ec00-6e41-11eb-8087-e3ef986ae3b4.jpg)

Correction Attempts:
Checked Mechanicals
Checked Wiring
Checked Motor Thermals
Tried Classic Jerk
Reduced Acceleration
Reduced Print Speed
Reduced Driver Current
Tried #define JUNCTION_DEVIATION_MM 0.02
Currently testing with #define ENDSTOPPULLUPS (even though switches have them and capacitors)

Hardware:
Prusa i2 New Fully Custom Build (for retro printing)
Ender 3 Bed
RAMPS 1.4 24V Modded (replaced LDO with CUI 5V buck regulator)
MEGA2560
A4988 Drivers Fan Cooled
![2021-01-29](https://user-images.githubusercontent.com/26206019/107866687-59981200-6e41-11eb-94e3-fa5549ada881.jpg)

**Comment by ellensp** [comment]
Layer shifts are extremely unlikely to be firmware bug related. Most likely a configuration/machine issue.

For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
