### ISSUE TITLE
[BUG] new build warnings introduced for ZONESTAR_LCD

### ISSUE THREAD

**Issue by atsju** [MarlinFirmware/Marlin#21089]
### Bug Description

The commit 4a89731025 from PR #20753 has introduced new warnings during build.

```
In file included from Marlin\src\module\../lcd/marlinui.h:28:0,
                 from Marlin\src\module\temperature.cpp:37:
Marlin\src\module\../lcd/buttons.h:154:0: warning: "BUTTON_CLICK" redefined
     #define BUTTON_CLICK() RRK(EN_KEYPAD_MIDDLE)
 ^
Marlin\src\module\../lcd/buttons.h:123:0: note: this is the location of the previous definition
     #define BUTTON_CLICK() (buttons & (B_MI|B_ST))
```

### Configuration Files

simply define `#define ZONESTAR_LCD`

### Steps to Reproduce

It's a build warning, no special steps to reproduce.
Note that in tip of branche  in file pins_RAMPS.h line 471 there is now an error to warn user for HW modification so I suppose this warning will never be found by automated builds.

I expect to build without warnings
**Actual behavior:**
Build warnings

**Comment by ellensp** [comment]
This has been merged.
