### ISSUE TITLE
[BUG] PA13 and PA14 swapped on TRIGORILLA_PRO board

### ISSUE THREAD

**Issue by leonhma** [MarlinFirmware/Marlin#21090]
Really no need to fill out the form. Im on Marlin 2.0.7.2 and the pins for z+ and z- in pins/stm32f1/pins_TRIGORILLA_PRO.h are swapped (don't match up with the labels onboard). I have an i3 mega and this error was giving me a headache last 3 days...

**Comment by ellensp** [comment]
The information in https://www.thingiverse.com/thing:4271636 agrees with you
Z_MIN_PIN               PA14
Z_MAX_PIN              PA13

**Comment by leonhma** [comment]
created a pr adressing this issue #21100
