### ISSUE TITLE
SKR 1.3 - TMC2209 Extruder won't move

### ISSUE THREAD

**Issue by pappysven** [MarlinFirmware/Marlin#21097]
Hello,
Installed the lastest bugfix , impossible to get my extruder move.
Tried to swap with my Z motor, the extruder motor is ok.
Used a 2209 in spare  in case of, no better.
I tried to activate SQUARE_WAVE_STEPPING as it solved problems previously for some people, no more luck.
I'm new to marlin, maybe it's a problem in my configuration ? 
Thanks for your help !
[Config marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5985661/Config.marlin.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
