### ISSUE TITLE
[BUG] SD_ABORT_NO_COOLDOWN disabled, but heaters remain on after Stop Print

### ISSUE THREAD

**Issue by Arogen** [MarlinFirmware/Marlin#21106]
Using Marlin 2.0.7.2, if I stop a print, the heaters both remain on even though the configuration_adv.h file has:
  //#define SD_ABORT_NO_COOLDOWN

### Steps to Reproduce

1. Start printing something
2. Stop the print before it finishes
3. Observe the bed and nozzle do not cool down

**Expected behavior:**
When SD_ABORT_NO_COOLDOWN is commented out and you stop a print, the heaters turn off.

**Actual behavior:**
Heaters stay on until manually turned off

Hardware:
Ender 3 Pro
SKR Mini E3 V2 board
TFT35
BLTouch

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/5990685/configs.zip)

**Comment by ellensp** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by Arogen** [comment]
The issue exists in the bugfix branch as well.
