### ISSUE TITLE
[BUG] Incorrect behavior of CASE_LIGHT_ENABLE on SKR mini E3 V1.2, pin PA1 (SERVOS)

### ISSUE THREAD

**Issue by trengtor** [MarlinFirmware/Marlin#21129]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6008728/Configuration.zip)
![123](https://user-images.githubusercontent.com/16775489/108481958-e4499880-72a9-11eb-86c8-d32c45d6e58a.png)

### Bug Description

When you change the brightness setting, the brightness of the LED backlight itself does not change. It turns off when set to 0% and turns on at full brightness at 1%. An oscilloscope check confirmed that the PA1 output is either 0 (0%) or 1 (> = 1%). Turning on/off works OK.
But if you turn off the brightness control (uncomment #define CASE_LIGHT_NO_BRIGHTNESS), the on/off also stops working. The backlight is always on in this case.
Tested on Marlin-bugfix-2.0.x from 17.01.2021

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

See description

**Expected behavior:**

See description

**Actual behavior:**

See description

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by thisiskeithb** [comment]
> Tested on Marlin-bugfix-2.0.x from 17.01.2021

Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by trengtor** [comment]
> > Tested on Marlin-bugfix-2.0.x from 17.01.2021
> 
> Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

Ok

**Comment by trengtor** [comment]
The same behavior ­- bug confirmed

**Comment by ellensp** [comment]
Please enable #define PINS_DEBUGGING in Configuration_adv.h then send a M43 and capture the output.
If anything else is on PA1 make sure to disable it

**Comment by trengtor** [comment]
> Please enable #define PINS_DEBUGGING in Configuration_adv.h then send a M43 and capture the output.
> If anything else is on PA1 make sure to disable it

![2021-02-20_12-42-03](https://user-images.githubusercontent.com/16775489/108591300-2392ea80-7379-11eb-8a39-32794cef412a.jpg)
Only this. Need to comment or no?

**Comment by ellensp** [comment]
M43 may reveal more, but yes comment that out. Marlin may be trying to use it twice

**Comment by trengtor** [comment]
> M43 may reveal more, but yes comment that out. Marlin may be trying to use it twice

Tested: Comment (//) not affects to PA1 bechavior

**Comment by trengtor** [comment]
> Please enable #define PINS_DEBUGGING in Configuration_adv.h then send a M43 and capture the output.
> If anything else is on PA1 make sure to disable it

I can't install (troubles) maple usb driver for capture M43 output via Pronterface etc. (W7 x64 PRO) 
Via TFT35 V3.0 it's impossible (listing is too long & too fast).

**Comment by trengtor** [comment]
So, I think the ploblem live in code interaction with new HAL (because PWM silutions was changed)

**Comment by trengtor** [comment]
> > Tested on Marlin-bugfix-2.0.x from 17.01.2021
> 
> Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

Need another info?

**Comment by trengtor** [comment]
@thisiskeithb do you have any thoughts or ideas on this issue?

**Comment by trengtor** [comment]
The problem is still present. Tested on April 19 bugfix version.

**Comment by trengtor** [comment]
Hi guys. Hawe you any news? Problem still hawe.

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by thisiskeithb** [comment]
Lots of PWM stuff was reworked recently, so please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

Also, is there any difference between the `_maple` & non-`_maple` environments?
