### ISSUE TITLE
[FR] Homing on custom axis

### ISSUE THREAD

**Issue by minusplusminus** [MarlinFirmware/Marlin#21131]
Hi everyone,

We have an experimental setup where we use homing on X,Y,Z and have a extra axis put on E. We where wondering if it's possible to do homing on E  by adding endstop. If this is not possible, we would like to know how we can use gcodes to do homing outide Marlin.  

The second option would something like this:

- use position change G0 to move E from minimum to maximum. 
- if enstop is triggered, stop  position 
- reset E position to 0

**Comment by GMagician** [comment]
You may try #19112

**Comment by thisiskeithb** [comment]
Related (and now closed) Feature Requests: #15717 & #8519
