### ISSUE TITLE
G35 Tramming Wizard times out after 10s

### ISSUE THREAD

**Issue by CaptainSweatpants** [MarlinFirmware/Marlin#21141]
Ill provide more details if they become relevant; but in the G35 Tramming Wizard -- in all sub-screens -- if the dial isnt touched within 10-15sec it times out and kicks you back to the main info screen. This requires navigating back to the tramming wizard, rehoming, and then going to the corner to measure again and adjust.

The only way to stop this is to continually turn the dial while adjusting the bed screws. 

im running the latest Bugfix 2.x

**Comment by borland1** [comment]
Maybe this helps...  the timeout default is set to 15 seconds unless defined otherwise in `Configuration_adv.h` 
```
1148  #if HAS_DISPLAY
1149  // The timeout (in ms) to return to the status screen from sub-menus
1150  //#define LCD_TIMEOUT_TO_STATUS 15000
```
