### ISSUE TITLE
[FR] HOTEND_IDLE_TIMEOUT Imrpovements

### ISSUE THREAD

**Issue by sg000** [MarlinFirmware/Marlin#21154]
### Description

Hopefully small but useful Improvements to HOTEND_IDLE_TIMEOUT (Hot End Idle Timeout)
a) reset the timer on and XY or Z movement (maybe another userdefined switch for this for those who want original behavior of E-stepper only) At least that's current behavior as I understand it.

b) Send some tones to the speaker (multiple, this is an issue for the user to know about) when the occurs. VERY difficult to troubleshoot an issue with the bed turn turning off turn first print after power-up (I didn't realize the shortcomings of the idle timeout when I enabled it)

c) Check the code, my hotend was staying on, but the bed was turning off. Not intended functionality as I understand it, but if it is, make it clear, or make changes to turn off both.

d) Obviously now if its going to turn off the hotend mid-print, it should go into pause or cancel mode, right, and not keep trying to print the gcode.

### Feature Workflow

I hope I covered this adequately above.

#### Additional Information

I think all the work is in hotend_idle.h and hotend_idle.cpp but this is beyond my expertise to fork and modify, sorry.

**Comment by thisiskeithb** [comment]
Added in https://github.com/MarlinFirmware/Marlin/pull/21535
