### ISSUE TITLE
RepRap Discount Full Graphic Smart Controller Grabelled display after installing Marlin Firmware

### ISSUE THREAD

**Issue by SMARTTUTORIALS** [MarlinFirmware/Marlin#21169]
I have followed the guidelines as descibed and tried to install **_Marlin Firmware version 2.x_** , But I was not getting a proper display output on the smart controller. I am Using the **_Ramps 1.4 Board along with the REPRAP Full Graphic Smart Controller._** The texts come out to be garbled. I followed the previous issues and this is my fix on the problem that I found out after trying a few of the fixes previously mentioned and suggested.

The **_ultralcd_ultralcd_st7920_u8glib_rrd.h_** file is now renamed as **_ultralcd_st7920_u8glib_rrd_AVR.h_** and is located in the following directory:
**_Marlin-2.0.x/Marlin/src/lcd/dogm/_**

The garbled text in my case was occuring due to timing issues with the arduino Mega and the LCD.

_#elif MB(MINIRAMBO,EINSY_RAMBO,EINSY_RETRO,SILVER_GATE)
  #define CPU_ST7920_DELAY_1 DELAY_NS(0)
  #define CPU_ST7920_DELAY_2 DELAY_NS(250)
  #define CPU_ST7920_DELAY_3 DELAY_NS(0)_

Search for the above lines. In my case the value RAMPS_14_EFB was not mentioned by default. So I added that in the above code and it looks like this:

**_#elif MB(MINIRAMBO,EINSY_RAMBO,EINSY_RETRO,SILVER_GATE,RAMPS_14_EFB)
  #define CPU_ST7920_DELAY_1 DELAY_NS(0)
  #define CPU_ST7920_DELAY_2 DELAY_NS(250)
  #define CPU_ST7920_DELAY_3 DELAY_NS(0)_**

Finally after uploading the program it started working just fine and the garbled text issue was resolved.
Also One thing to note is that now the Marlin.ino file when opened in Arduino IDE does not load all the files, It only loads the Marlin , Configuration.h , Configuration_adv.h , Version.h files.

If anyone is using the same boards as me please go through the Configuration.h file and enable the following line(i.e. uncomment the line):

**_#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER_**

and if the garbled text issue is happening then follow the above suggestions. It may fix the issue as it worked for me.

**Comment by ellensp** [comment]
The issue is that not all REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER actually use the same LCD, some are slower and need additional delays. Many examples of this on reprap.org
