### ISSUE TITLE
firmware German 

### ISSUE THREAD

**Issue by Julasch73** [MarlinFirmware/Marlin#21166]
it is possible to make a firmware from https://marlin.crc.id.au/ in German ? https://marlin.crc.id.au/firmware/Ender%203%20-%20v4.2.7%20Board%20-%20BLTouch/

**Comment by ellensp** [comment]
We can not assist on 3rd party web sites.  This site is not run or controlled by Marlin. 

Please contact @CRC on the discord.

**Comment by thisiskeithb** [comment]
@CRCinAU Can you please add a disclaimer or make it more clear that these are two separate entities and support requests should go to you?

**Comment by CRCinAU** [comment]
I'm not sure how much more direct I can be.....

![image](https://user-images.githubusercontent.com/3992884/108792211-db700400-75d4-11eb-875d-d60fc1480603.png)

None of the links end up here...

**Comment by Julasch73** [comment]
@CRCinAU könnten sie bitte kontakt mit mir aufnehmen ? 

 @CRCinAU please contact me ?
