### ISSUE TITLE
[FR] Reorganize LCD menu items

### ISSUE THREAD

**Issue by Romancze** [MarlinFirmware/Marlin#21172]
Hi to all
I have the Ender 3pro with oem LCD 12864. In Creality firmware in the menu is "Print from SD(TF)" on the second place. Now I flashed Marlin 2.0.x and "Print from SD(TF)" is on the last place.  So I must scroll and scroll. 
How to move this menu item to the top? I used google for few days and nothing helped.
Thank you very much
Roman

illustration photo
 ![151496694_2811501245731024_5875695827944912718_o](https://user-images.githubusercontent.com/14996805/108878655-c4dfa200-7600-11eb-9146-64a893a0f9fa.jpg)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](https://marlinfw.org)
- RepRap.org [Marlin Forum](https://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Discord server](https://discord.gg/n5NJ59y)

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
