### ISSUE TITLE
real time adjustme nts to firmware

### ISSUE THREAD

**Issue by paleto1974** [MarlinFirmware/Marlin#21179]
<!--How about an input section to marlin while it is running so that it can be set for a specific machine without using the Arduino ide. I don't understand programming and don't really want to learn just to set up different machines.(I have 5, all different.) The instructions etc. could be put in a text file to be downloaded with Marlin and/or separately.
example:

Board type 1-33 (see read me file) ___
number of extruders                      ___
x motor steps/revolution               ___
y motor steps/revolution               ___
z motor steps/revolution               ___
name of printer                              ___
and so on to cover all possible data types required.

At least for myself and others like me it would make 3d printing easier and more fun...less frustrating and scary. I always fear that I will make a mistake, even a typo, and ruin the machine or at minimum require returning to the config.h and redoing it.
If this is not possible or practical then at least group all the options at the front end of the program so there is no need to search for each one separately.

I thank you for all the work you have done already and hope I don't sound like a whiner in this request. I offer these suggestions only for consideration and hope you will find them of some value.

Respectfully
Charles Phillips
char_23518@yahoo.com

**Comment by ellensp** [comment]
vague in the extreme
