### ISSUE TITLE
G26 starts opposite of origin, Inverted bed mesh, Bilinear

### ISSUE THREAD

**Issue by thetailwind** [MarlinFirmware/Marlin#21228]
Hello, I've been tracking down a bed leveling issue and I'm noticing some strange behavior. Initially I thought my mesh was inverted but now I think it's rotated 180*

The Setup: CoreXY, SKR 1.4 Turbo TMC2209, bl touch.

Build version : "bugfix-2.0.x" latest pulled yesterday.

I ran a test and I can confirm that the mesh is upside down or rotated:

I got my current mesh and found the worst corner (4,4)

M420 V

Recv: 0 1 2 3 4
Recv: 0 -0.175 +0.057 +0.142 +0.173 +0.230
Recv: 1 -0.023 +0.048 +0.030 +0.072 +0.023
Recv: 2 +0.010 +0.075 +0.012 +0.043 +0.063
Recv: 3 -0.035 +0.035 +0.050 +0.152 +0.148
Recv: 4 -0.070 +0.010 +0.082 +0.235 +0.313

I changed my mesh to invert the worst corner.

Command I ran:
M421 I4 J4 Z-0.313

Recv: 0 1 2 3 4
Recv: 0 -0.175 +0.057 +0.142 +0.173 +0.230
Recv: 1 -0.023 +0.048 +0.030 +0.072 +0.023
Recv: 2 +0.010 +0.075 +0.012 +0.043 +0.063
Recv: 3 -0.035 +0.035 +0.050 +0.152 +0.148
Recv: 4 -0.070 +0.010 +0.082 +0.235 -0.313

Did a test print and 4,4 had really good adhesion on the worst corner, by comparison to the previous attempt, it was .626 mm away from the bed.

Everything up until this issue has been pretty normal. It homes well, it probes well, the only thing that was abnormal was at one time when I was doing a 4x4 probing, it started at the right hand side corner rather than the left. When I did 5x5 probing, it went back to starting at the left corner, (0,0). Not sure if it's indicative of anything, but I thought it was worth mentioning.

Additionally, today I did a G26 for mesh validation and it started at the back right, (300,300). I'm starting to think this is indicative of something. 

Any Ideas regarding the mesh inversion/rotation?

EDIT:

Turned mad debugging on:

Send: M420 V
Recv: echo:M420 V
Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3      4
Recv:  0 -0.350 -0.080 +0.012 +0.037 +0.090
Recv:  1 -0.105 -0.018 -0.028 -0.013 -0.045
Recv:  2 -0.033 +0.068 -0.013 +0.012 +0.010
Recv:  3 -0.055 +0.012 +0.048 +0.135 +0.095
Recv:  4 -0.170 -0.060 +0.017 +0.157 +0.195
Recv: 
Recv: echo:Bed Leveling ON
Recv: echo:Fade Height OFF
Recv: ok
[...]
Send: G26
Recv: echo:G26
Recv: G26 starting...
Recv: >>> do_blocking_move_to  X256.80 Y286.30 Z0.20
Recv: >  X256.80 Y286.30 Z5.00
Recv: <<< do_blocking_move_to  X256.80 Y286.30 Z5.00
Recv: Waiting for heatup.

See how it goes to  X256.80 Y286.30 Z5.00 rather than 0,0. Is this normal? 

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6057280/Configuration.zip)

**Comment by thetailwind** [comment]
In conclusion everything was fine. The Bed visualizer was flipped and rotated incorrectly. I found this out by placing quarters where some corner probe points were and looked at the visualization. The corners were not matching up so once I adjusted the rotation and actually adjusted the correct knob, everything was fine.

**Comment by hakimio** [comment]
Close the issue then?

**Comment by ellensp** [comment]
Im going to close it.
