### ISSUE TITLE
[FR] Reversal of E stepper using G-code

### ISSUE THREAD

**Issue by DrumClock** [MarlinFirmware/Marlin#21247]
Would it be possible to define a G-code for reversing the rotation of the stepper motor for the extruder (E0-En)? 

`E.g.  as when using  M605 S3  -  initiate mirrored movement.`

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/16550

**Comment by thisiskeithb** [comment]
While not a 1:1 duplicate feature request, both features are related and should be discussed in the linked issue above.
