### ISSUE TITLE
[BUG] Z Probe Wizard doesn't work without Z_SAFE_HOMING

### ISSUE THREAD

**Issue by TzOk83** [MarlinFirmware/Marlin#21253]
### Bug Description

Z Offset Wizard doesn't work without Z_SAFE_HOMING (e.g. when using Z-endstop for homing, and Z-probe only for bed leveling).

### Configuration Files
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6087089/configuration.zip)

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

### Steps to Reproduce

1. Enter menu Configuration
2. Go to Advanced Settings
3. Go to Probe Offsets
4. Go to Z Probe Wizard

**Expected behavior:**

Printer should either allow to adjust Z Probe Offset at the current position (without Auto Homing), or Auto Home and then move to the middle of the build plate (force behavior like in Z_SAFE_HOMING for Z Probe Wizard).

**Actual behavior:**

Printer Auto Homes to the bottom left corner of the build plate, and enters Z Offset adjusting mode, with the probe (eg. BL-Touch) outside the build plate, and no option to move the head in any other direction than Z axis.

**Comment by thisiskeithb** [comment]
What error message did you see on screen/over serial?

I just used this yesterday on a build without `Z_SAFE_HOMING` and can confirm it works.

Try this:
1. Home your printer
2. Move hotend to a spot where the probe will trigger on the bed
3. Run the Z Probe Offset Wizard

Your printer will home XYZ again, but will then return to the position you set in step 2 above.
