### ISSUE TITLE
[BUG] bugfix-2.0.x: "Init KILL, SUICIDE, PSU earlier (#20810)" [ b9ed1395] results in boot loop on LPC1768 platform.

### ISSUE THREAD

**Issue by chrisqwertz** [MarlinFirmware/Marlin#21297]
### Bug Description

bugfix-2.0.x commit b9ed1395 "Init KILL, SUICIDE, PSU earlier (#20810)" results in boot loop on LPC1768 + RAMPS platform.
My stepper drivers are TMC2208.

### Configuration Files

[Conf_files_b9ed1395.zip](https://github.com/MarlinFirmware/Marlin/files/6110496/Conf_files_b9ed1395.zip)

Just to be sure, here's my pins_RAMPS_RE_ARM.h file for my modified RAMPS 1.4 board.

[pins_RAMPS_RE_ARM.zip](https://github.com/MarlinFirmware/Marlin/files/6110505/pins_RAMPS_RE_ARM.zip)

### Steps to Reproduce

Have a LPC1768 + RAMPS 1.4 setup and flash bugfix-2.0.x b9ed1395 

**Expected behavior:**

after a reset the controller fan should start up and stop again for about ~0.4s 3 times in a row before stopping again. The bed would start heating during that short time period. Then the marlin logo should appear in display and the printer should go to idle with all IO pins including bed heater having their respective level set.

**Actual behavior:**

Controller fan spins up and doesn't stop. Heating bed keeps on heating and display stays blank forever.

#### Additional Information

Reverting the commit and going back to 85d61de6 fixes the issue again.

**Comment by thisiskeithb** [comment]
It's not clear from your report since the referenced commits are from January, but have you tried the latest [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) (without reverting that commit) to test with the latest code?

**Comment by chrisqwertz** [comment]
Yes sir, in fact, that's why I reverted to a known good and spent quite a while applying, reverting and compiling commits until I narrowed it down to the aforementioned culprit.

Upon closer inspection I might have found a lead:

in MarlinCore.cpp moving 
```
 #if HAS_TMC220x
    SETUP_RUN(tmc_serial_begin());
 #endif
```
so it sits before the PSU_CONTROL init seems to fix it.

Maybe someone with a similar setup can verify that. 

I vaguely remember having the TMC in the wrong order and breaking the boot sequence a year or so ago.

If I can be of more help, please let me know.

**Comment by chrisqwertz** [comment]
I'm now on the latest commit and the issue did not reappear.

To confirm the suspicion I placed `SETUP_RUN(tmc_serial_begin());` after

```
  #if ENABLED(PSU_CONTROL)
    SETUP_LOG("PSU_CONTROL");
    powersupply_on = ENABLED(PSU_DEFAULT_OFF);
    if (ENABLED(PSU_DEFAULT_OFF)) PSU_OFF(); else PSU_ON();
  #endif
```

which results in getting stuck in the boot loop again.

**Comment by thisiskeithb** [comment]
> I'm now on the latest commit and the issue did not reappear.

Great news!

**Comment by chrisqwertz** [comment]
I added a proposed fix for the issue: b7f03915cc956c2bb81c17ec86fa196319f62fe7

**Comment by thisiskeithb** [comment]
> I added a proposed fix for the issue: [b7f0391](https://github.com/MarlinFirmware/Marlin/commit/b7f03915cc956c2bb81c17ec86fa196319f62fe7)

So this issue isn't resolved?

**Comment by chrisqwertz** [comment]
I'm sorry, I didn't word that right: 
What I meant was, on the latest bugfix2.0. commit, I moved the TMC init before the PSU init which fixed the issue.

**Comment by thisiskeithb** [comment]
> What I meant was, on the latest bugfix2.0. commit, I moved the TMC init before the PSU init which fixed the issue.

Got it.

Since you've provided a fix, it'd be faster if you submitted a [Pull Request](https://marlinfw.org/docs/development/getting_started_pull_requests.html) so it can be reviewed.

**Comment by thisiskeithb** [comment]
Merged.
