### ISSUE TITLE
[BUG] Password protection doesn't work correctly

### ISSUE THREAD

**Issue by Zemistr** [MarlinFirmware/Marlin#21293]
### Password protection doesn't work correctly

If you try to enter the Password Settings menu section and you put any password, you get access.

### Configuration Files

Clean `bugfix-2.0.x` with CR10_STOCKDISPLAY, PASSWORD_FEATURE and PASSWORD_DEFAULT_VALUE = 1234.

### Steps to Reproduce

1. Build marlin with CR10_STOCKDISPLAY, PASSWORD_FEATURE and PASSWORD_DEFAULT_VALUE = "any".
2. Flash the firmware
6. Login with your password
7. Open the "Password Settings" menu section
8. Login with any password you want.
9. Congrats, now you are HACKER!!! 🍾 

**Expected behavior:**

The same as during login after boot up. 

**Actual behavior:**

Getting access with the wrong password.

**Comment by ellensp** [comment]
Steps are not clear.
once you have logged in you should be able to change the password. which is what your steps is doing.

**Comment by Zemistr** [comment]
@ellensp I reduced them a little bit.
The steps are really simple. You are able to log in only with the correct password after the boot-up.
If you try to access the password settings menu section the printer will ask you to put the correct password to get access.
The problem is that you can write any password and you get access.

**Comment by ellensp** [comment]
no mention of enabling eeprom 
"#warning "PASSWORD_FEATURE settings will be lost on power-off without EEPROM_SETTINGS."

**Comment by Zemistr** [comment]
Here is a video https://youtu.be/3EoJFPGrswQ

**Comment by Zemistr** [comment]
@ellensp Originally I had the EEPROM in the description, but I just did a test without the EEPROM and the problem is still the same. During login everything works correctly. Marlin validates the password as expected.

**Comment by ellensp** [comment]
yes I see what you mean, and the Enter digit  line has garbage at the end too...  > and number are over each other

**Comment by Zemistr** [comment]
Yop, agree. I tried the stable version of Marlin and also the latest bugfix. Both are doing the same.

**Comment by ellensp** [comment]
I just found a related bug, still unfixed..
On startup password screen scroll down and select Start Over.
Now wait about 20 seconds, and your in! no password required!  


Its  LCD_TIMEOUT_TO_STATUS  timing out to status

**Comment by ellensp** [comment]
I've created a PR to fix these issues.

**Comment by Zemistr** [comment]
I tried the login screen and damn... you are right... It's not safe at all... 🤣 
Thanks! Hope the fix will be available before my video about that functionality is released. 😄

**Comment by thinkyhead** [comment]
The patch looks good, thanks! It is now merged into bugfix for the next release.
