### ISSUE TITLE
[BUG]YHCB2004 no longer compiles

### ISSUE THREAD

**Issue by Vertabreak** [MarlinFirmware/Marlin#21303]
at the time of submission and shortly after yhcb2004 i confirmed it compiled correctly, also confirmed working before submit.
testing was on latest bugfix today compile errors out.
to reproduce enable yhcb2004 on one of the printers that make use of it like the geeetech A10/A20.
another user brought this to my attention and i have confirmed it on the latest bugfix code.
unfortunately i can no longer do much testing as i was working with someone that could do hardware testing for me that i no longer have contact with.

```
Compiling .pio/build/mega2560/src/src/lcd/menu/menu_bed_corners.cpp.o
In file included from Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio.h:52:0,
                 from Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/HAL.h:24,
                 from Marlin/src/lcd/HD44780/../../inc/../HAL/HAL.h:30,
                 from Marlin/src/lcd/HD44780/../../inc/MarlinConfig.h:31,
                 from Marlin/src/lcd/HD44780/marlinui_HD44780.h:28,
                 from Marlin/src/lcd/HD44780/marlinui_HD44780.cpp:34:
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:42:21: error: 'DIO52' was not declared in this scope
 #define SCK         DIO52
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:96: note: in expansion of macro 'SCK'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                ^~~
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:42:21: note: suggested alternative: 'DOR2'
 #define SCK         DIO52
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:96: note: in expansion of macro 'SCK'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                ^~~
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:44:21: error: 'DIO51' was not declared in this scope
 #define MOSI        DIO51
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:117: note: in expansion of macro 'MOSI'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                                     ^~~~
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:44:21: note: suggested alternative: 'DOR1'
 #define MOSI        DIO51
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:117: note: in expansion of macro 'MOSI'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                                     ^~~~
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:43:21: error: 'DIO50' was not declared in this scope
 #define MISO        DIO50
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:139: note: in expansion of macro 'MISO'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                                                           ^~~~
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:43:21: note: suggested alternative: 'DOR0'
 #define MISO        DIO50
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:139: note: in expansion of macro 'MISO'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                                                           ^~~~
In file included from Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio.h:52:0,
                 from Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/HAL.h:24,
                 from Marlin/src/lcd/HD44780/../../inc/../HAL/HAL.h:30,
                 from Marlin/src/lcd/HD44780/../../inc/MarlinConfig.h:31,
                 from Marlin/src/lcd/HD44780/../marlinui.h:24,
                 from Marlin/src/lcd/HD44780/lcdprint_hd44780.cpp:19:
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:42:21: error: 'DIO52' was not declared in this scope
 #define SCK         DIO52
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:96: note: in expansion of macro 'SCK'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                ^~~
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:42:21: note: suggested alternative: 'DOR2'
 #define SCK         DIO52
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:96: note: in expansion of macro 'SCK'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                ^~~
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:44:21: error: 'DIO51' was not declared in this scope
 #define MOSI        DIO51
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:117: note: in expansion of macro 'MOSI'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                                     ^~~~
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:44:21: note: suggested alternative: 'DOR1'
 #define MOSI        DIO51
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:117: note: in expansion of macro 'MOSI'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                                     ^~~~
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:43:21: error: 'DIO50' was not declared in this scope
 #define MISO        DIO50
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:139: note: in expansion of macro 'MISO'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                                                           ^~~~
Marlin/src/lcd/HD44780/../../inc/../HAL/./AVR/fastio/fastio_1280.h:43:21: note: suggested alternative: 'DOR0'
 #define MISO        DIO50
                     ^
.pio/libdeps/mega2560/LiquidCrystal_AIP31068/LiquidCrystal_AIP31068_SPI.h:58:139: note: in expansion of macro 'MISO'
   LiquidCrystal_AIP31068_SPI(uint8_t ss_pin,uint8_t lcd_cols,uint8_t lcd_rows,uint8_t sclk_pin=SCK,uint8_t mosi_pin=MOSI,uint8_t miso_pin=MISO);
                                                                                                                                           ^~~~
*** [.pio/build/mega2560/src/src/lcd/HD44780/lcdprint_hd44780.cpp.o] Error 1
Marlin/src/lcd/HD44780/marlinui_HD44780.cpp:98:66: error: call to 'LiquidCrystal_AIP31068_SPI::LiquidCrystal_AIP31068_SPI(uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t)' uses the default argument for parameter 6, which is not yet defined
   LCD_CLASS lcd(YHCB2004_CLK, 20, 4, YHCB2004_MOSI, YHCB2004_MISO); // CLK, cols, rows, MOSI, MISO
                                                                  ^
*** [.pio/build/mega2560/src/src/lcd/HD44780/marlinui_HD44780.cpp.o] Error 1
================================================================================= [FAILED] Took 19.08 seconds =================================================================================

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:19.077
============================================================================ 1 failed, 0 succeeded in 00:00:19.077 ============================================================================
The terminal process "platformio 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by ellensp** [comment]
bugfix configs to replicate?

**Comment by Vertabreak** [comment]
the examples direct from repo replicate.
you can grab one from my PR to add the models or swap display on default A10/A20.

**Comment by ellensp** [comment]
Went back to following commit. using A10 configs with YHCB2004 enabed. It still doesn't not compile.
commit 490d4a504a40a70e1a51c4758d37ec6116272b38
Author: Vert <45634861+Vertabreak@users.noreply.github.com>
Date:   Tue Feb 16 21:29:55 2021 -0500
    GT2560 v4.1B, YHCB2004 SPI character LCD (#21091)

applied https://github.com/MarlinFirmware/Marlin/pull/21111 also and no change

**Comment by Vertabreak** [comment]
i ran a test just after my code was accepted and it did compile that day.
i did have to patch a small typo first.
the original submitted code was fully tested and verified to be working on hardware.
it seems something happened in refactoring since the day i patched the typo and completed compile test.
any assistance in sorting out what happened since then would be helpful.

**Comment by ellensp** [comment]
this commit (prior to murge) https://github.com/MarlinFirmware/Marlin/pull/21091/commits/6275ef78fe66b812128e0d9369c5bbb2e2a2161d#diff-dc860029097334a26510ba6b49fed7044ec5479b6bc466c936ebf06fbe78c877 removed your edits from Marlin/src/HAL/AVR/fastio/fastio_1280.h  

to test I adding them back in with 
// SPI
#ifdef YHCB2004
  #define SCK         5
  #define MISO        21
  #define MOSI        36
#else
  #define SCK         DIO52
  #define MISO        DIO50
  #define MOSI        DIO51
#endif

and it compiles.. 
I cant test this at all... no hardware

**Comment by ellensp** [comment]
instead of editing Marlin/src/HAL/AVR/fastio/fastio_1280.h

updating the pins file also compiles.
eg
```
#if ENABLED(YHCB2004)
  #ifndef YHCB2004_CLK
    #define YHCB2004_CLK                      5
    #define DIO52 YHCB2004_CLK
  #endif
  #ifndef YHCB2004_MOSI
    #define YHCB2004_MOSI                     21
    #define DIO51 YHCB2004_MOSI
  #endif
  #ifndef YHCB2004_MISO
    #define YHCB2004_MISO                     36
    #define DIO50 YHCB2004_MISO
  #endif


```

**Comment by Vertabreak** [comment]
tested the pins change it does compile but i have no one to do a hardware test but i do think this is a step in the right direction.
see if i can track down someone to check it before suggesting the change.
[pins_GT2560_V3.h.log](https://github.com/MarlinFirmware/Marlin/files/6114425/pins_GT2560_V3.h.log)

**Comment by Vertabreak** [comment]
i have had the change tested by 1 user so far with out results on hardware. 
something else must be a issue as a result of refactoring as i can confirm the code i originally submitted was working.
changes made from the original code looked like simple refactoring and i saw no issue with it but i must have over looked something.

**Comment by mshoemaker** [comment]
Vert, I grabbed your code yesterday and it compiled, but on my A10T with the V4.1b board once I flashed the board the LCD remains blank.

**Comment by Vertabreak** [comment]
only the original code i submitted is confirmed working everything after merging upstream is still broken.

**Comment by mshoemaker** [comment]
I did find this change missing, added it back in, it built, and once flashed the YHCB2004 LCD worked like it was supposed to.

Marlin/src/HAL/AVR/fastio/fastio_1280.h
> 
> to test I adding them back in with
> // SPI
> #ifdef YHCB2004
> #define SCK 5
> #define MISO 21
> #define MOSI 36
> #else
> #define SCK DIO52
> #define MISO DIO50
> #define MOSI DIO51
> #endif
> 
> and it compiles..
> I cant test this at all... no hardware

**Comment by ellensp** [comment]
I just noticed 

```
  #ifndef YHCB2004_MOSI
    #define YHCB2004_MOSI                     21
    #define DIO51 YHCB2004_MOSI
  #endif
  #ifndef YHCB2004_MISO
    #define YHCB2004_MISO                     36
    #define DIO50 YHCB2004_MISO
  #endif
```

this set the MISO and MOSI pins swapped from 

```
#ifdef YHCB2004
#define SCK 5
#define MISO 21
#define MOSI 36
```

so can you as a test remove the changes to fastio_1280.h

and try the following in the boards pins.h

#if ENABLED(YHCB2004)
  #ifndef YHCB2004_CLK
    #define YHCB2004_CLK                      5
    #define DIO52 YHCB2004_CLK
  #endif
  #ifndef YHCB2004_MOSI
    #define YHCB2004_MOSI                     36
    #define DIO51 YHCB2004_MOSI
  #endif
  #ifndef YHCB2004_MISO
    #define YHCB2004_MISO                     21
    #define DIO50 YHCB2004_MISO
  #endif

**Comment by mshoemaker** [comment]
OK, I backed out the changes to fastio_1280.h, and made the change below in pins_GT2560_V3.h and it built but did not work.  However if I make this change with MOSI 21 and MISO 36, then it works as expected.

> so can you as a test remove the changes to fastio_1280.h
> 
> and try the following in the boards pins.h
> 
> #if ENABLED(YHCB2004)
> #ifndef YHCB2004_CLK
> #define YHCB2004_CLK 5
> #define DIO52 YHCB2004_CLK
> #endif
> #ifndef YHCB2004_MOSI
> #define YHCB2004_MOSI 36
> #define DIO51 YHCB2004_MOSI
> #endif
> #ifndef YHCB2004_MISO
> #define YHCB2004_MISO 21
> #define DIO50 YHCB2004_MISO
> #endif

What I have that works is:
`#if ENABLED(YHCB2004)`
`  #ifndef YHCB2004_CLK`
`    #define YHCB2004_CLK                      5`
`    #define DIO52 YHCB2004_CLK`
`  #endif`
`  #ifndef YHCB2004_MOSI`
`    #define YHCB2004_MOSI                     21`
`    #define DIO51 YHCB2004_MOSI`
`  #endif`
`  #ifndef YHCB2004_MISO`
`    #define YHCB2004_MISO                     36`
`    #define DIO50 YHCB2004_MISO`
`  #endif`

**Comment by ellensp** [comment]
which is what I originally suggested 6 days ago, and was told it doesn't work....

**Comment by Vertabreak** [comment]
so the pins got flipped post submit? i have made the change on my fork see if i can get someone to check it and verify.

**Comment by mshoemaker** [comment]
All i had to add to make it work were these three lines to the board pins header.

#define DIO52 YHCB2004_CLK
#define DIO51 YHCB2004_MOSI
#define DIO50 YHCB2004_MISO

**Comment by ellensp** [comment]
"so the pins got flipped post submit?" no in your original commit, you have them backwards..  in fastio
```
#define SCK         5
  #define MISO        21
  #define MOSI        36
#endif
```
but correct in marlinui_HD44780.cpp
```
elif ENABLED(YHCB2004)
 LCD_CLASS lcd(5, 20, 4, 21, 36);//LCD spi ss pin, lcd cols, lcd rows, lcd sclk pin, lcd mosi pin, lcd miso pin

```
This was cleaned up to become
`  LCD_CLASS lcd(YHCB2004_CLK, 20, 4, YHCB2004_MOSI, YHCB2004_MISO); // CLK, cols, rows, MOSI, MISO`

The LCD doesn't actually care what MISO or MOSI  are set to, they are just needed to satisfy compiling Arduino framework.

**Comment by ellensp** [comment]
I suspect we could drop YHCB2004_CLK, YHCB2004_MOSI and YHCB2004_MISO 
change LCD_CLASS lcd(YHCB2004_CLK, 20, 4, YHCB2004_MOSI, YHCB2004_MISO);
to  LCD_CLASS lcd(CLK, 20, 4, MOSI, MISO); 

And reduce the pins down to
```
#if ENABLED(YHCB2004)
  #ifndef DIO52
    #define DIO52 5  // SCK
  #endif
  #ifndef DIO51
    #define DIO51 21  // MOSI
  #endif
  #ifndef DIO50
    #define DIO50 36 // MISO
  #endif
#endif 
```

**Comment by Vertabreak** [comment]
strange as i had multi people confirm the code working on hardware before it was submitted.
it was a direct port from https://github.com/Geeetech3D/Prusa_I3_3Dprinter/tree/master/A10Pro_HW4.1B_FW2.3

**Comment by ellensp** [comment]
The current error is "error: 'DIO52' was not declared "  
The original commit bypassed DIO50, DIO51 and DIO52 and defined MISO MOSI and SCK as 'nonsense' values, but It would have worked as lcd was setup using raw pin numbers,

**Comment by ellensp** [comment]
@mshoemaker can you test the above idea. repeated  here again. 
In marlinui_HD44780.cpp change LCD_CLASS lcd(YHCB2004_CLK, 20, 4, YHCB2004_MOSI, YHCB2004_MISO);
to LCD_CLASS lcd(CLK, 20, 4, MOSI, MISO);

and replace #if ENABLED(YHCB2004) block in pins_GT2560_V3.h with
```
#if ENABLED(YHCB2004)
  #ifndef DIO52
    #define DIO52 5  // SCK
  #endif
  #ifndef DIO51
    #define DIO51 21  // MOSI
  #endif
  #ifndef DIO50
    #define DIO50 36 // MISO
  #endif
#endif 
```
Leave fastio_1280.h unmodified (ie no mention of YHCB2004) 

I suspect this will work, once confirmed we can make a PR to fix this

**Comment by Vertabreak** [comment]
a viable solution is my only concern once we have a confirmed fix do you plan to submit the fix or should i.

**Comment by mshoemaker** [comment]
I make the change and try it out this evening.

**Comment by ellensp** [comment]
please confirm this patch, so we can add it to marlin, or not.

**Comment by mshoemaker** [comment]
@ellensp I tried what you suggested and the LCD would not work.  However if I added this:

    #define DIO52                             5
    #define DIO50                             21
    #define DIO51                             36

To the pins file and leave everything else as currently checked in it works as expected.

**Comment by localhorst24** [comment]
i fixed it with... (pins_GT2560_V3.h)

```
  #ifndef YHCB2004_MOSI
    #define YHCB2004_MOSI                     21
    #define DIO50 YHCB2004_MOSI
  #endif
  #ifndef YHCB2004_MISO
    #define YHCB2004_MISO                     36
    #define DIO51 YHCB2004_MISO
  #endif
```

**Comment by Vertabreak** [comment]
do we have a definitive hardware tested working patch yet.

**Comment by Vertabreak** [comment]
i had someone test the above noted changes on hardware and nothing seem to make the screen work. 
the tester was the same one that confirmed it all working before it was submitted.

**Comment by Vertabreak** [comment]
https://github.com/MarlinFirmware/Marlin/pull/21450
just wanna get it fixed went and put in the request.

**Comment by ellensp** [comment]
merged, closed.
