### ISSUE TITLE
[BUG ?] (RUMBA32 + WS2812B )

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#21300]
Specially for @ellensp 
rumba32 + 1 meter of "AMAZON" btf lighting led 144/meters RGBW WS2812B

Folkloric behavior ... change color even if we apply the same command
Not supported ?  Lib ? Timing ? Config ? 

Thks

**Comment by ellensp** [comment]
If it was for me, you would have followed the template and included config files.

You cannot run 144 neopixels on a 3d printer. setting each led takes a finite time and you cannot take break, you have to set them all at once., this is incompatible with the operation of the firmware, that must do other things at the same time.

**Comment by studiodyne** [comment]
No ... I just see you have written code for a ws2812 project
Ok for all at once 
Thks

**Comment by studiodyne** [comment]
@ellensp  , hi , i'm sorry but i need you again 

I have stopped to use NEOPIXEL , because , timing flow must be perfect , and need a dedicated controler 
I use now 4 pins for RGBW 24v led
But i need PWM on these pins , because now , are just ' ON/OFF'
Pwm on pins are only on dedicated pins or can we switch on any pins we want ?
If pwm pins are hardware only , is it possible to have software pwm for my leds  ' PD12/13/14/15' on RUMBA 32 STMF4

I'm sorry to disturb you , but find these type of information need to search many days in datasheet ,  and to leard marlin very deep

Thks for help

**Comment by studiodyne** [comment]
@ellensp 
I need your help , and need a little lesson about PWM
i have replaced neopixel by 4 channel RGBW 24v led , on 4 pins
But i don't have adjustable brightness , just on/off for all leds
Why ?
thks
