### ISSUE TITLE
Automatic Generation of Versioning Information from "git" Repository

### ISSUE THREAD

**Issue by Wackerbarth** [MarlinFirmware/Marlin#2133]
Some time back, I introduced some infrastructure to permit the automatic generation of versioning string during the build process. Use of this type of mechanism (1) Assures that the exact source tree for each build can be identified and (2) Removes the need to edit the source files to track the versioning information.

Additionally, the generation of file archives can be automated to include the corresponding versioning files in the archive version of the source tree.

To further this implementation, I have made an addition to the Arduino IDE (included at 1.6.2) and have been using it locally for some time.

Before proposing a pull request for the remainder of the implementation, I need some testing.

I also need some assistance in porting the header generation script to the Windows platform.

Please contribute to https://github.com/Wackerbarth/Marlin/issues/1 to help prepare this for inclusion in the Marlin Development tree.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
