### ISSUE TITLE
[BUG] Z not going down on Mesh leveling

### ISSUE THREAD

**Issue by sarptekbas** [MarlinFirmware/Marlin#21349]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

While mesh bed leveling Z goes up but at the other spot it doesn’t go down.

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Ender 3 Pro v4.2.7

### Electronics

Board v4.2.7

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by ellensp** [comment]
no configs, Didn't fill out template. No enough information provided. Closing

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
