### ISSUE TITLE
[BUG] Printer moves twice as far as it's supposed to

### ISSUE THREAD

**Issue by F1l3N0tF0und** [MarlinFirmware/Marlin#21343]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

After power cycling my printer all axis of the printer move twice as far as they're supposed. 
(e.g. 20mm instead of 10mm)

If I re-flash the firmware over the SD card everything works as expected again until the next power cycle.

### Bug Timeline

It started after switching to the MKS SGEN L Mainboard with TMC2208 drivers.

### Expected behavior

That the printer moves as far as it's supposed to.

### Actual behavior

It moves twice as far.

### Steps to Reproduce

-Flash Marlin
-start the printer (no need to print anything)
-power cycle the printer

### Version of Marlin Firmware

Marlin 2.0.7.2

### Printer model

Creality Ender 2

### Electronics

MKS Sgen L V1 with TMC2208

### Your Slicer

Cura

### Host Software

OctoPrint

[CONF_AND_CONF_ADV.zip](https://github.com/MarlinFirmware/Marlin/files/6135044/CONF_AND_CONF_ADV.zip)

**Comment by thisiskeithb** [comment]
> It started after switching to the MKS SGEN L Mainboard with TMC2208 drivers.

Are the jumpers under each driver set correctly?

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
