### ISSUE TITLE
[BUG] "Filament detetcion switch is not pressed" ERROR - gcode file

### ISSUE THREAD

**Issue by ulaskayalar** [MarlinFirmware/Marlin#21347]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I get the error "Filament detetcion switch is not pressed". I want to print a 3D model with Gcode, but I get this error every time. My 3D printer does not have a Filament sensor. I do not want to use. Why am I getting this error? What is the way to fix this error?

### Version of Marlin Firmware

2.0.3

### Printer model

Two Trees Bluer

### Your Slicer

Ultimaker Cura

**Comment by ellensp** [comment]
No Configs, no details. Closing. Can reopen after tested with bugfix.
