### ISSUE TITLE
[BUG/NO BUG?] (RGBW led on 4 pins , no PWM)

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#21350]
@sjasonsmith @ellensp 
RUMBA32 pins PD12/13/14/15 for RGBW led = No pwm , only ON/OFF all colors,   used to drive 4 channels mosfet + RGBW LED
On the LCD , the behavior is just ' 0= off and 1 to 255= on ' , no adjustable brightness for any colors
Not implemented ?
No timer available ?
Timer and pin's need to be created
Can i add it by myself or need big knowledge of marlin
Some lines to fix it  ? 😄  to add timer and dedicated pinmap?

Anything to help me is welcome , before learning marlin deep and  waste 6 months to have adjustable brightness on each color

thks

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
