### ISSUE TITLE
Invert thermistor working (if temperature higher activate thermistor)

### ISSUE THREAD

**Issue by kekko7072** [MarlinFirmware/Marlin#21371]
### Describe the feature you want

Hey is there a way to simply invert the logic of thermistor working in Marlin software for 3D Printing. In fact I'd like to run current to the thermistor port (that I am using for fan) if the temperature is higher than configured, and stop current if the temperature is lower, because due to the heat it will rise on it's own. Is there a simple way to do it? I need 5V 1.5 A for this fan.

No specific board is selected for this project, I can use all type of board.

**Comment by ellensp** [comment]
look at auto_fans
turned on over certain temp, off when drops under that temp

**Comment by Rincewind08** [comment]
i alreqady do this running pumps.   use a heater port to make sure that you have enough amperage in your .pins, if you have a heater port to spare.
`
