### ISSUE TITLE
Merge #2113 breaks command parsing

### ISSUE THREAD

**Issue by Wackerbarth** [MarlinFirmware/Marlin#2140]
Scott,
Thanks for merging my Kossel Pro infrastructure.

Unfortunately, when I tried to test it this morning, the printer command parser is broken.
It will not recognize commands from Repeater-Host Mac.
I have isolated it to the problem to one of the merges that you did last night.

If I start from 71ff9ad, everything is fine. But based on 4d11b29 things fail.

You can find my build at https://github.com/Wackerbarth/Marlin/tree/BrokenCommandParser

**Comment by thinkyhead** [comment]
#2141 should do the trick, don't know how I forgot that line…

**Comment by Wackerbarth** [comment]
It appears to be fixed at #2142

**Comment by thinkyhead** [comment]
@Wackerbarth Excellent. That should show some performance benefit, save energy, and cool the electronics by an amount that no one will ever notice!
