### ISSUE TITLE
CR10 S5 will not extrude with STEALTHCHOP_E enabled - Y will not move without STEALTHCHOP_E enabled!!!

### ISSUE THREAD

**Issue by SpectrumTech** [MarlinFirmware/Marlin#21416]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

On my CR10 S5 using a new BTT SKR E3 Turbo - with STEALTHCHOP_E uncommented, E0 will not drive the extruder. But if I comment out STEALTHCHOP_E to disable it, the Y axis will not move during printing. Oddly Y works just fine throughout homing and bed leveling - but as soon as printing begins Y will not respond.  

### Bug Timeline

From the start of using Marlin 2.0 bugfix on an SKR E3 Turbo

### Expected behavior

The printer to print normally...

### Actual behavior

Y axis stops responding the moment extrusion should occur and will not move again until the printer is reset - only occurs when STEALTHCHOP_E is commented out - otherwise the machine will not extrude.

### Version of Marlin Firmware

latest bugfix 3/22/21

### Printer model

Creality CR10S5 with BTT SKR E3 Turbo mainboard

### Electronics

SKR E3 TURBO, Touch TFT, BLTouch, BTT Smart filament sensor

### Your Slicer

Cura

### Host Software

SD Card (headless)

[CONFIG.zip](https://github.com/MarlinFirmware/Marlin/files/6185268/CONFIG.zip)

**Comment by petervdk54** [comment]
I have the same problem.
