### ISSUE TITLE
[BUG] Commit #20325  Breaks G29 P/UBL latest Bugfix-2.0.X SKR Mini E3 V1.2 

### ISSUE THREAD

**Issue by GhostlyCrowd** [MarlinFirmware/Marlin#21429]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Bltouch probe self test works, g28 using probe as z min works
UBL G29 P1 probe doesn't deploy

### Bug Timeline

Between October 2020 and now when i moved the machine forward

### Expected behavior

TO build a mesh properly

### Actual behavior

Z raises and lowers indefinitely and the probe does not deploy

### Steps to Reproduce

G28 then G29 P1

### Version of Marlin Firmware

Bugfix 2.0.x Current as of March 23 2021

### Printer model

Ender 3

### Electronics

SKR E3 Mini V1.2 Board

### Add-ons

 Bltouch 3.1 Genuine

Attached Debug probe M114 output and configs. 

To rule out a wiring issue when the printer moves to that position i moved the tool and bet to where the G29 fails (point 1 X25.0000 Y31.0000) and ran a M48 perfectly fine

[Debug probe output.txt](https://github.com/MarlinFirmware/Marlin/files/6192829/Debug.probe.output.txt)

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/6192831/configs.zip)

**Comment by GhostlyCrowd** [comment]
Rolled all the way back to the last known working that was on it previously. And UBL Probing works probe deploys. SO it's definitely an issue with G29/UBL and not deploying the probe.  On current bugfix.

Wish I kept this more up to date to narrow the window more than 1000ish commits. But it's a friends printer, and he was  shy about updating as it was working. 
`C:\Users\Jeff\2.0.x-Bugfix_OCT5\Marlin>git rev-parse HEAD
343441d7465fb637f0c2627060b7003a0d0fc25c

C:\Users\Jeff\2.0.x-Bugfix_OCT5\Marlin>git rev-parse --short HEAD
343441d746

C:\Users\Jeff\2.0.x-Bugfix_OCT5\Marlin>git status
On branch bugfix-2.0.x
Your branch is behind 'origin/bugfix-2.0.x' by 1015 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Marlin/Configuration.h
        modified:   Marlin/Configuration_adv.h
        modified:   platformio.ini

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        buildroot/share/PlatformIO/scripts/nanolib.py

no changes added to commit (use "git add" and/or "git commit -a")`

**Comment by GhostlyCrowd** [comment]
Release 2.0.7.2 / Branch 2.0.x  is working as well. Trying to step it forward a bit to narrow it down

I'm open to ideas by the gurus as to what commit might influence this and moving forward as instructed.

**Comment by GhostlyCrowd** [comment]
Have some time and a friend willing to let me abuse his ender 3, im walking back a week at a time so far i have made it to https://github.com/MarlinFirmware/Marlin/commit/03160719eb3d9ed31115956946826cb3b08babbc and G29 P1 no probe deploy. 

Posting for record. and info.

**Comment by GhostlyCrowd** [comment]
Still working my way back

Jan 21 Version bump commit - Still broken

Dec 28 Doesnt compile, a storm of broken.

Nov 28 - Compiles and WORKS!!!!

I'm running into a lot of commits that are broken on many levels, its getting harder as a person with no code experience to narrow this down.

**Comment by GhostlyCrowd** [comment]
Down to Dec 29 Broken

Nov 28 working

Walking @thinkyhead "distribution updates"

**Comment by thisiskeithb** [comment]
Please keep mentions to a minimum unless something is on fire. 🙂

Instead of bumping this thread with comments, it'd be better to move everything to a single post for easier tracking.

**Comment by GhostlyCrowd** [comment]
100% tested several times over between https://github.com/MarlinFirmware/Marlin/commit/7226f6834e9aef295ea3a7c2599e6c5a0ebb3c10 < working G29 P1 deploys probe to https://github.com/MarlinFirmware/Marlin/commit/2dbd2063f87e8e91d5d1ebd42c027975498b29c9 <  broken Wish i could be of better help. a 4 day window is the best I can do.

**Comment by GhostlyCrowd** [comment]
This is the commit that breaks Probing/UBL (and probably more cannot test as it's not  my printer and the owner doesn't like randomly driving the tool into the bed because of probe brokenness) on the SKR E3 Mini series   

Reverting this commit https://github.com/MarlinFirmware/Marlin/pull/20325  resolves everything. 

This explains the multitude of SKR E3 users on discord all complaining about probe randomness.  A couple in the past few days we couldn't get a grasp on why it was so random.

**Comment by ldursw** [comment]
To narrow down the issue could you please do some more tests?

- `platformio.ini` may be set to `STM32F103RC_btt_512K`. Try with `STM32F103RC_btt`.
- Try disabling `BLTOUCH_HS_MODE`.

Also, can you provide the debug log and a video when the probe works as expected and when it doesn't?

**Comment by GhostlyCrowd** [comment]
> To narrow down the issue could you please do some more tests?
> 
> * `platformio.ini` may be set to `STM32F103RC_btt_512K`. Try with `STM32F103RC_btt`.
> * Try disabling `BLTOUCH_HS_MODE`.
> 
> Also, can you provide the debug log and a video when the probe works as expected and when it doesn't?

STM32F103RC_btt_512K. or STM32F103RC_btt made no difference he usually runs STM32F103RC_btt_512K_USB and that has the same issue, I've also verified the chip is indeed 512 with a st link previously, In my quest to resolve the issue BLTOUCH_HS_MODE had been disabled to try in my testing but i can try again.  I can see if i can get logs today from his printer. Currently, he is on the latest bug fix as of a few days ago with the commit i mentioned above reverted and all is working. 

Moving the printer off of STM32F103RC_btt_512K_USB now that its reassembled and he is using it would require him to tip over and disassemble the printer every time to flash so that's not an option for the person willing to let me test my findings on his hardware.

**Comment by GhostlyCrowd** [comment]
Here is a video of it failing to deploy the probe doing a ubl and just stuck in the Probing fail loop you see i the debug logs attached to this bug report https://www.youtube.com/watch?v=EAzoWJO-_cc

Marlin  stops its self if no trigger event happens `#define Z_PROBE_LOW_POINT          -2 // Farthest distance below the trigger-point to go before stopping` which is what you're seeing and is a good thing because .5mm more and the nozzle would impact. So that is what your seeing it failing to probe trigger because the probe never deploys and retrying indefinitely on UBL G29 P1 which is also seen in the debug log I attached.

**Comment by ldursw** [comment]
Thanks for the details. There is one more thing that I'd like you to test if you can.

In Configuration.h enable `#define FAN_SOFT_PWM`. Then in `src/HAL/STM32F1/timers.h` change `SERVO0_TIMER_NUM` to 1 near line 86.

![image](https://user-images.githubusercontent.com/37294448/112772687-8c205780-9008-11eb-8171-107dde29f90d.png)

I've compared the firmware files and couldn't find an obvious difference between them. Please send a known good and known bad binary preferably using the exact same configuration on both. They are located at `.pio/build/STM32F103RC_btt_512K/firmware.elf`. I need the elf file, not the bin file.

**Comment by GhostlyCrowd** [comment]
@ldursw 
`#define FAN_SOFT_PWM`  Is already enabled and I believe a requirement for the SKR E3 Mini boards, Attached are the working and non working ELF files, exact same Marlin bugfix from March 25th except the working has https://github.com/MarlinFirmware/Marlin/pull/20325 reverted and thus is compiled with stsm32 @ 6.1 and Maple @ 2.1 instead of the broken one with stsm32 @ 12 and Maple @ 3.1 
The elf's were compiled with the exact same source.  The working one i also used `LINKFLAGS=["--specs=nano.specs"]` to keep the binary smaller on compile otherwise end up with a bin thats 300ish kb 


I will get a probing log of it working shortly since you asked previously, and after that i will make the servo changes you asked for on the broken bugfix with out the rever to see if that helps. 

[elf_and_config_files.zip](https://github.com/MarlinFirmware/Marlin/files/6222152/elf_and_config_files.zip)

**Comment by GhostlyCrowd** [comment]
Here is the requested Debug log of G29 P1/UBL working 
[G29_P1_Working_Debug_Log.txt](https://github.com/MarlinFirmware/Marlin/files/6222220/G29_P1_Working_Debug_Log.txt)

**Comment by GhostlyCrowd** [comment]
> In Configuration.h enable `#define FAN_SOFT_PWM`. Then in `src/HAL/STM32F1/timers.h` change `SERVO0_TIMER_NUM` to 1 near line 86.
> 
> ![image](https://user-images.githubusercontent.com/37294448/112772687-8c205780-9008-11eb-8171-107dde29f90d.png)


This change does indeed fix the probe deployment issues with G29 P1 so were on to something.  `SERVO0_TIMER_NUM` to 1 ` 

`#define FAN_SOFT_PWM` was always on

Curious as to why this is an issue from stsm32 @ 6.1 and Maple @ 2.1 to  ststm32 @ 12 and Maple @ 3.1

**Comment by ldursw** [comment]
We narrowed it down to a timer issue. The only commits that look suspicious are [this one](https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/73e268d703e2f22bd9f915bb088dfe8d789d493d) and [this one](https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/aabca7bb09eb4f2c97b10012d5d85e73716b2463).

@rhapsodyv do you know what may be causing this issue?

**Comment by rhapsodyv** [comment]
> We narrowed it down to a timer issue. The only commits that look suspicious are [this one](https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/73e268d703e2f22bd9f915bb088dfe8d789d493d) and [this one](https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/aabca7bb09eb4f2c97b10012d5d85e73716b2463).
> 
> @rhapsodyv do you know what may be causing this issue?

DAMMIT hahahahahahah maple change their default tone timer channel!!! 

WHHYYYYYY?!?!!? hahahah

Too many things on marlin was done with their defaults in mind. I will take a closer look.

**Comment by GhostlyCrowd** [comment]
The fact that I'm not crazy and you guys are seeing this too and I can stop pulling hair out is a great feeling LOL Thanks guys!

**Comment by rhapsodyv** [comment]
anyone here that have a SKR MINI E3 willing to test a PR??

Chat me on discord!

**Comment by GhostlyCrowd** [comment]
This was fixed in https://github.com/MarlinFirmware/Marlin/pull/21488

Essentially getting off the broken STM32F1 platform and maple  and onto a supported platform resolved this an many other small fringe bugs experienced.
