### ISSUE TITLE
[BUG] Bed Leveling (Precision Piezo) on i3 Mega S way too low on one side

### ISSUE THREAD

**Issue by DivineJimmi** [MarlinFirmware/Marlin#21434]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Hey guys,

my bed-leveling is not working properly. Its leveling the bed very good, except on the right side of the bed. The nozzle bores very deep into the bed, before the Z-axis releases. You can see it clearly while leveling. This only happens on the right side. On the Mesh visualizer you can see it clearly. The bed is very even and i can print flawless without leveling. With leveling the nozzle digs deep into the bed.

All my rods are perfectly aligned, all screws are tight. I don't know what to do anymore.

i am using the "i3 Mega MK4 Piezo Kit" from Thingiverse from ML3DPrinting

The leveling looks like this:
     0      1      2      3      4
0 -0.080 +0.040 +0.070 -0.090 -1.395
1 -0.157 -0.107 -0.102 -0.277 -1.460
2 -0.155 -0.090 -0.093 -0.192 -0.720
3 -0.185 -0.100 -0.090 -0.230 -1.045
4 -0.223 -0.118 -0.135 -0.235 -0.482

https://ibb.co/T16xbfY

### Expected behavior

even bed leveling

### Actual behavior

the nozzle levels the right side way too deep and digs into the bed.

### Version of Marlin Firmware

Marlin 2.0.5.3

### Printer model

Anycubic i3 Mega S

### Electronics

MK4 X-Carriage with Precision Piezo v2

### Add-ons

Precision Piezo v2

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by ellensp** [comment]
not bugfix, no configs.  closing till tested on bugfix and configs added
