### ISSUE TITLE
[BUG] Lerdge K:  Error compiling in Arduino IDE and VS CODE (platformio)

### ISSUE THREAD

**Issue by dolence** [MarlinFirmware/Marlin#21439]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I can't successfully compile Marlin for Lerdge K on both Visual Studio Code (using Marlin Auto Build) or Arduino IDE.

### Version of Marlin Firmware

Both 2.x stable and latest main git

### Printer model

Custom

### Electronics

Lerdge K board

Error message when compiling on VS Code:

```
Building in release mode
Compiling .pio\build\STM32F4\src\src\HAL\STM32_F4_F7\HAL.cpp.o
In file included from Marlin\src\HAL\STM32_F4_F7\../../inc/MarlinConfigPre.h:52,
                 from Marlin\src\HAL\STM32_F4_F7\HAL.h:27,
                 from Marlin\src\HAL\STM32_F4_F7\HAL.cpp:25:
f:\marlin\marlin-git\marlin\marlin\src\hal\stm32_f4_f7\inc\conditionals_lcd.h:25:4: error: #error "Sorry! TFT displays are not available for HAL/STM32F4_F7."
   25 |   #error "Sorry! TFT displays are not available for HAL/STM32F4_F7."
```

Error message when compiling in Arduino IDE 1.8.13. I have both STM32duino and rogerclarkmelbourne AruinoSTM32 libraries installed.

```
In file included from sketch\src\HAL\STM32F1\tft\tft_fsmc.cpp:27:
sketch\src\HAL\STM32F1\tft\tft_fsmc.h:31:10: fatal error: libmaple/dma.h: No such file or directory
   31 | #include <libmaple/dma.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Erro compilando para a placa Generic STM32F4 series
```

Attached are the Marlin configuration files and platformio.ini files.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/6199558/Marlin.zip)

**Comment by thisiskeithb** [comment]
> #error "Sorry! TFT displays are not available for HAL/STM32F4_F7."

This isn’t a bug.

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
