### ISSUE TITLE
[BUG] (bug summary)Ender 5, Creality 4.2.7 board, using latest Marlin BUGfix, does not home the Z-axis with BLTouch

### ISSUE THREAD

**Issue by Mauler78** [MarlinFirmware/Marlin#21445]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I downloaded the latest Marlin 2.0.x bugfix and am trying to compile a working firmware.  I modified only the settings required to enable the BLtouch, enabled Z_MIN_PROBE_PIN and set to PB1, and enables Z_SAFE_HOMING.  Complied successfully.

I flashed the Creality firmware and was able to get it to home in all directions with the BLtouch so it is not a hardware issue, but related to the setup of the firmware.

### Bug Timeline

Today

### Expected behavior

During homing the print head should more to the X and Y limits, then center on the print bed, deploy the sensor pin and slowly raise the print bed until the Z pin is triggered.

### Actual behavior

During homing the X and Y limits are tested, the print head centers, the print bed slightly lowers, the Z pin deploys and stows twice, then deploys and the homing is halted.

### Steps to Reproduce

1. Send the autohome command
2. Wait for the failure.

### Version of Marlin Firmware

bugfix 2.0.x

### Printer model

Ender 5

### Electronics

Creality 4.2.7, BLTouch 3.1

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
