### ISSUE TITLE
[FR] (feature summary) Mcode for quickly finding axis limits from a terminal

### ISSUE THREAD

**Issue by 3D-Maker-Kid** [MarlinFirmware/Marlin#21444]
### Is your feature request related to a problem? Please describe.

I recently acquired a Printrbot Metal Plus and have been having some issues with it that I and a few others think may be related to the axis limits being defined incorrectly in firmware. Unfortunately, there is currently no way to check what the axis limits are from a terminal.

### Describe the feature you want

Be able to send a command via a terminal like Pronterface or Octoprint to tell the user the axis limits of the printer. Sorry if this is not enough information, first time submitting a feature request.

**Comment by thisiskeithb** [comment]
This is already implemented in [`M115`](https://marlinfw.org/docs/gcode/M115.html). Make sure you enable `M115_GEOMETRY_REPORT` and re-flash.
