### ISSUE TITLE
[BUG] (SKR_PROv1.2+5160 ALL LOW but printing works)

### ISSUE THREAD

**Issue by DerGrossmann** [MarlinFirmware/Marlin#21457]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

TMC Connection errror

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.0.x (Mar 27 2021 03:16:16)

### Host Software

SD Card (headless)

Hello everyone!
The problem is this: I use SKR PRO and 5160 v1.2 drivers.
When the printer starts, an ALL LOW notification appears, but you can safely start printing and there will be no problems.
I have loaded the latest library TMCstepper, included all the necessary functions in the firmware.
Send: M122 V
Recv: axis:pwm_scale/curr_scale/mech_load|flags|warncount
Recv: 		X		Y		Z		E
Recv: GCONF		0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
Recv: IHOLD_IRUN	0x00:0A:0F:07	0x00:0A:0F:07	0x00:0A:10:08	0x00:0A:09:04
Recv: GSTAT		0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
Recv: IOIN		0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
Recv: TPOWERDOWN	0x00:00:00:80	0x00:00:00:80	0x00:00:00:80	0x00:00:00:80
Recv: TSTEP		0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
Recv: TPWMTHRS	0x00:00:00:F3	0x00:00:00:F3	0x00:00:03:3B	0x00:00:03:F5
Recv: TCOOLTHRS	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
Recv: THIGH		0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
Recv: CHOPCONF	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
Recv: COOLCONF	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
Recv: PWMCONF	0xC8:0D:0E:24	0xC8:0D:0E:24	0xC8:0D:0E:24	0xC8:0D:0E:24
Recv: PWM_SCALE	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
Recv: DRV_STATUS	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00	0x00:00:00:00
Recv: Testing X connection... Error: All LOW
Recv: Testing Y connection... Error: All LOW
Recv: Testing Z connection... Error: All LOW
Recv: Testing E connection... Error: All LOW

Send: M122
Recv: axis:pwm_scale/curr_scale/mech_load|flags|warncount
Recv: 		X	Y	Z	E
Recv: Enabled		false	false	false	false
Recv: Set current	800	800	850	500
Recv: RMS current	792	792	839	490
Recv: MAX current	1117	1117	1183	691
Recv: Run current	15/31	15/31	16/31	9/31
Recv: Hold current	7/31	7/31	8/31	4/31
Recv: Global scaler	133/256	133/256	133/256	133/256
Recv: CS actual	0/31	0/31	0/31	0/31
Recv: PWM scale	0	0	0	0
Recv: stealthChop	false	false	false	false
Recv: msteps		256	256	256	256
Recv: interp		false	false	false	false
Recv: tstep		0	0	0	0
Recv: PWM thresh.	243	243	827	1013
Recv: [mm/s]		130	130	19	30
Recv: OT prewarn	false	false	false	false
Recv: triggered
Recv:  OTP		false	false	false	false
Recv: off time	0	0	0	0
Recv: blank time	16	16	16	16
Recv: hysteresis
Recv:  -end		-3	-3	-3	-3
Recv:  -start		1	1	1	1
Recv: Stallguard thrs	0	0	0	0
Recv: uStep count	0	0	0	0
Recv: DRVSTATUS	X	Y	Z	E
Recv: sg_result	0	0	0	0
Recv: stallguard
Recv: fsactive
Recv: stst		*	*	*	*
Recv: olb
Recv: ola
Recv: s2gb
Recv: s2ga
Recv: otpw
Recv: ot
Recv: Driver registers:
Recv: 		X	0x00:00:00:00	 Bad response!
Recv: 		Y	0x00:00:00:00	 Bad response!
Recv: 		Z	0x00:00:00:00	 Bad response!
Recv: 		E	0x00:00:00:00	 Bad response!
Recv: 
Recv: 
Recv: Testing X connection... Error: All LOW
Recv: Testing Y connection... Error: All LOW
Recv: Testing Z connection... Error: All LOW
Recv: Testing E connection... Error: All LOW
Recv: ok
I really ask for help because the problem is annoying. I installed the BTT version of the example - no problem. The configuration files are attached.
[https://drive.google.com/file/d/1fLJNzNLdQOKCvt6S-P-47HXCE6aZipOJ/view?usp=sharing] (Config files in google drive)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
