### ISSUE TITLE
[BUG] MKS robin nano v.2, LVGL UI - the temperature on the main screen is not updating

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#21461]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

After updating https://github.com/MarlinFirmware/Marlin/commit/532df198da6a9cadb441a1993b4b482e69e317ce, bed temperature and hotend temperature(+% fan)  have been added to the start screen.
When heated, the bed and hotend temperatures are not updated. Temperatures frozen (unchanged).

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6216043/Configuration.zip)

**Comment by thinkyhead** [comment]
A patch has been merged. If it solves the issue then this can be closed!

**Comment by Malderin** [comment]
@rhapsodyv ,  
Something is wrong after the update
![IMG_](https://user-images.githubusercontent.com/52313714/112824646-7ad05d00-9093-11eb-83d4-78b1d09e03d0.jpg)

**Comment by DmitryAranax** [comment]
To update a bed temperature, hotend temperature and a fan percent, you need a fix code at draw_ready.cpp, draw_ready.h and draw_ui.cpp (GUI_RefreshPage() -> case PRINT_READY_UI). Original commit can only show parameters once not update automatically. To update them you need an additional routine like others update routines in MKS UI. Check files please.
[draw_ready.zip](https://github.com/MarlinFirmware/Marlin/files/6221649/draw_ready.zip)

**Comment by Malderin** [comment]
> To update a bed temperature, hotend temperature and a fan percent, you need a fix code at draw_ready.cpp, draw_ready.h and draw_ui.cpp (GUI_RefreshPage() -> case PRINT_READY_UI). Original commit can only show parameters once not update automatically. To update them you need an additional routine like others update routines in MKS UI. Check files please.
> [draw_ready.zip](https://github.com/MarlinFirmware/Marlin/files/6221649/draw_ready.zip)

look at this https://github.com/MarlinFirmware/Marlin/pull/21468

**Comment by DmitryAranax** [comment]
Indeed. Great work!
