### ISSUE TITLE
[BUG]MKS robin E3Dv1.1(stm32f1) use MKS OLED no working

### ISSUE THREAD

**Issue by Hoshino-itsuki** [MarlinFirmware/Marlin#21492]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

MKS robin E3Dv1.1(stm32f1) use MKS OLED no working

### Version of Marlin Firmware

bug-fix 2.0.x version

### Printer model

Creality Ender 3

### Electronics

MKS robin e3d v1.1

Use MKS robin e3dv1.1 motherboard(stm32f1), connect MKS OLED0.96 display, but no working and i has add pin define to pins_MKS_ROBIN_E3_common file

```
  #if ENABLED(MKS_12864OLED_SSD1306)
        #define LCD_PINS_DC          PA7  // Set as output on init
        #define LCD_PINS_RS          PC4  // Pull low for 1s to init
        #define DOGLCD_A0            LCD_PINS_DC
        #define DOGLCD_CS            PA5
        #define DOGLCD_MOSI          PA4
        #define DOGLCD_SCK           PA6
  #endif
```
[Config.and.pin.zip](https://github.com/MarlinFirmware/Marlin/files/6236860/Config.and.pin.zip)

Use RAMPS1.4 motherboard and MKS OLED0.96 will working
I am run offical marlin bug-fix 2.0.x version

**Comment by thisiskeithb** [comment]
Since you've provided a fix, it'd be faster if you submitted a [Pull Request](https://marlinfw.org/docs/development/getting_started_pull_requests.html) so it can be reviewed.

**Comment by a4870010** [comment]
> 既然您已经提供了一个修复程序，如果您提交了一个[拉请求](https://marlinfw.org/docs/development/getting_started_pull_requests.html)这样它就可以被审查了。

**Comment by Hoshino-itsuki** [comment]
It doesn't work，My fix doesn't work
Use RAMPS1.4 motherboard and MKS OLED0.96 will working
Use MKS robin e3dv1.1 motherboard and MKS OLED0.96 no working

**Comment by a4870010** [comment]
> 既然您已经提供了一个修复程序，如果您提交了一个[拉请求](https://marlinfw.org/docs/development/getting_started_pull_requests.html)这样它就可以被审查了。

It doesn't work，My fix doesn't work
Use RAMPS1.4 motherboard and MKS OLED0.96 will working
Use MKS robin e3dv1.1 motherboard and MKS OLED0.96 no working

**Comment by Hoshino-itsuki** [comment]
> Since you've provided a fix, it'd be faster if you submitted a [Pull Request](https://marlinfw.org/docs/development/getting_started_pull_requests.html) so it can be reviewed.

It doesn't work，My fix doesn't work
Use RAMPS1.4 motherboard and MKS OLED0.96 will working
Use MKS robin e3dv1.1 motherboard and MKS OLED0.96 no working

**Comment by borland1** [comment]
In your `pins_MKS_ROBIN_E3_common.h` file, I see pin `PA4` is assigned twice.  Not sure if `LCD_PINS_ENABLE` should be used with that display.

```
#if HAS_WIRED_LCD
  #if ENABLED(MKS_12864OLED_SSD1306)
        #define LCD_PINS_DC          PA7  // Set as output on init
        #define LCD_PINS_RS          PC4  // Pull low for 1s to init
        #define DOGLCD_A0            LCD_PINS_DC
        #define DOGLCD_CS            PA5
        #define DOGLCD_MOSI          PA4
        #define DOGLCD_SCK           PA6
  #endif
  #define BEEPER_PIN                        PC1
  #define BTN_ENC                           PC3
  #define LCD_PINS_ENABLE                   PA4    <---  What's this????  Same pin assignment as DOGLCD_MOSI
  //#define LCD_PINS_RS                       PA5
  #define BTN_EN1                           PB11
  #define BTN_EN2                           PB0
```

**Comment by Hoshino-itsuki** [comment]
> 在你的`pins_MKS_ROBIN_E3_common.h`文件，我看到引脚了`PA4`被分配了两次。不确定`LCD_PINS_ENABLE`应该和那个显示器一起使用。
> 
> ```
> #if HAS_WIRED_LCD
>   #if ENABLED(MKS_12864OLED_SSD1306)
>         #define LCD_PINS_DC          PA7  // Set as output on init
>         #define LCD_PINS_RS          PC4  // Pull low for 1s to init
>         #define DOGLCD_A0            LCD_PINS_DC
>         #define DOGLCD_CS            PA5
>         #define DOGLCD_MOSI          PA4
>         #define DOGLCD_SCK           PA6
>   #endif
>   #define BEEPER_PIN                        PC1
>   #define BTN_ENC                           PC3
>   #define LCD_PINS_ENABLE                   PA4    <---  What's this????  Same pin assignment as DOGLCD_MOSI
>   //#define LCD_PINS_RS                       PA5
>   #define BTN_EN1                           PB11
>   #define BTN_EN2                           PB0
> ```

I tried to cancel the LCD_ PINS_ Enable is still not available

**Comment by borland1** [comment]
Disable like this?

`#define LCD_PINS_ENABLE                   -1`
