### ISSUE TITLE
[BUG] (bug summary) servo control

### ISSUE THREAD

**Issue by lunknowl** [MarlinFirmware/Marlin#21506]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

servo off by 90 degree

### Version of Marlin Firmware

1.1.9

### Host Software

Pronterface

hi i using marlin 1.1.9 with ramp 1.4 control servo. i set the num_servo is 3 and try to jog the servo and it was off by 90 degree 
m280 s0 s90 nothing
m280 s0 g91 move 1mm

**Comment by ellensp** [comment]
Angle and PWM values depends on your servo.
