### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by lunknowl** [MarlinFirmware/Marlin#21515]
### Is your feature request related to a problem? Please describe.

I need to adjust servo speed via "M280 P0" command

### Describe the feature you want

I using marlin to control the servo and it work but it moving really fast, i try to reduce the speed of the servo so it run slower

**Comment by msmeeh** [comment]
might this help 
try to change the delay 

// (ms) Delay  before the next move will start, to give the servo time to reach its target angle.
// 300ms is a good value but you can try less delay.
// If the servo can't reach the requested position, increase it.
#define SERVO_DELAY { 300 }
