### ISSUE TITLE
How change pulse width in Marlin 1.0 firmware for AM882 stepper motor?

### ISSUE THREAD

**Issue by newb3d** [MarlinFirmware/Marlin#2152]
Hello guys
I use Rumba with Marlin 1.0 firmware with AM882 stepper motor driver to power 2 stepper motors on Z axis.
1, 7,8, 10 pins connected to stepper motor according to this schematic
http://reprap.org/mediawiki/images/2/24/RRD-RUMBA_SCHEMATICS.png
If ENA unconnected motor "lock" shaft, if connected I can spin shaft by my hand freely.
Oscilloscope showed me small pulses when I tried to run z axis but they seems pretty short to reaction of AM882.
How to make pulse wider?
Thank you in advance.

**Comment by boelle** [comment]
i think the people who code on marlin would also need a datasheet for the stepper driver so that they can figure how wide the pulse should be

**Comment by thinkyhead** [comment]
See issue #1900 for discussion about making the pulse wider.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
