### ISSUE TITLE
[BUG] Setting MKS_ROBIN_TFT43 should alter the name of the firmware file to be Robin_nano43

### ISSUE THREAD

**Issue by jamesjnadeau** [MarlinFirmware/Marlin#21529]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When compiling with the MKS_ROBIN_TFT43 and TFT_COLOR_UI  flags for the robin nano v1.2(BOARD_MKS_ROBIN_NANO) the firmware file is named Robin_nano35.bin

It needs to be named Robin_nano43.bin

### Bug Timeline

New

### Expected behavior

It would be great if this just named the file Robin_nano43

### Actual behavior

it names it Robin_nano35

### Steps to Reproduce

1. compile firmware
1. head to .pio/build
1. firmware is not named correctly for SD card upload

### Version of Marlin Firmware

latest bug fix branch as of writting this.

### Printer model

Two Trees Bluer Plus

### Electronics

MKS Robin Nano

### Add-ons

stock

### Your Slicer

Cura

### Host Software

OctoPrint

I have a Two Trees Bluer Plus and I'm so thankful to the folks to got marlin and this screen working! You're awesome @thinkyhead and @rhapsodyv, thanks again for you work on #20334

It took me a day of head scratching to determine that the firmware as named when compiled would not load up on my particular printer. This could just be my issue though, I only have my printer to go off of. The official updated firmware from Two Trees was named Robin_nano43, and that's where I finally got the idea from.

My only hope is some future soul doesn't have to live through this, but I don't have the time to look into how to fix, nor am I sure it's worth anyone else's time at this juncture. If this is closed and only serves as a way for someone else to jump this hurdle in the future, I'm fine with that. If there is documentation, or a better spot to place this, let me know and I'll bring it there.

Thanks so much for your time.

**Comment by thinkyhead** [comment]
We don't have any hook to check other settings and alter the final step of the build behavior, and it may take 11 days or more to get it worked out, so for the moment users will still have to do the renaming manually.
