### ISSUE TITLE
[BUG] BL Touch Clone wont trigger

### ISSUE THREAD

**Issue by noodev** [MarlinFirmware/Marlin#21530]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I just got a 3D Touch and it completes the self test on startup but when i home z it stows but it doesn't trigger. I've tried switching the wires and it didn't work so it must be a firmware issue or a issue with my probe.

I'm using vanilla marlin that i configured

### Bug Timeline

When i got a 3D touch

### Expected behavior

Stops z axis when homing

### Actual behavior

instead of stopping it keeps going down

### Steps to Reproduce

1. Home all
2. Use a spatula and trigger the probe
3. If it doesnt stop power off the printer

### Version of Marlin Firmware

Marlin bugfix-2.0.x (Apr  3 2021 09:02:05)

### Printer model

Anycubic Mega Zero 2

### Electronics

Stock Melzi Board (similar to ender 3 board)

### Add-ons

Octoprint

**Comment by noodev** [comment]
I accidently pressed enter and submited, woops

My Slicer: Prusa Slicer 2.3.0

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
