### ISSUE TITLE
Nonpixel lighting cycle while printing through a host like TFT

### ISSUE THREAD

**Issue by sinole1987** [MarlinFirmware/Marlin#21548]
### Describe the feature you want

When I print through my TFT Screen the RGB Lights do not work During startup cycle end and puase. I have to enter a Gcode, to turn on the lights and change their color during print. is it possible to make the neopixel RGB Stuff work while printing with a host like TFT Screen or octoprint.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
