### ISSUE TITLE
MKS Robin Nano v2.0 and MKS TS35 V2.0 Icon Layout Issue

### ISSUE THREAD

**Issue by descipher** [MarlinFirmware/Marlin#21557]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When 2 extruders are defined the 2nd extruder icon overlaps with the tool icon

### Bug Timeline

Last 15 Days prior to 06/04/2021 

### Expected behavior

Icons spaced without overlap.

### Actual behavior

Photo included.

### Steps to Reproduce

Compile and boot with the new firmware and assets folder from the pio build dir. 

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

N/A

![IMG_0689](https://user-images.githubusercontent.com/10734527/113806259-98529600-9727-11eb-8d3a-b71790488ac4.JPG)
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6268777/Configuration.zip)

**Comment by Malderin** [comment]
@descipher , 
try this: https://github.com/MarlinFirmware/Marlin/pull/21595

**Comment by thisiskeithb** [comment]
Resolved in https://github.com/MarlinFirmware/Marlin/pull/21595. Closing.
