### ISSUE TITLE
[BUG] the wire pusher is bugged

### ISSUE THREAD

**Issue by GHOSTS15** [MarlinFirmware/Marlin#21561]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

in the example configuration for the geeetech A20 printer, the wire pusher works in reverse (instead of pushing it into the extruder it pulls it out)

### Bug Timeline

in marlin 2.0.7.2

### Expected behavior

that the wire pusher (I don't know the technical name) worked well 

### Actual behavior

that the wire pusher (I don't know the technical name) doesn't work well

### Version of Marlin Firmware

marlin 2.0.7.2

### Printer model

geeetech a20

### Your Slicer

Cura

### Host Software

Cura

**Comment by ETE-Design** [comment]
Have you tryed to invert E0 in Configuration.h? Look at line 1200 `#define INVERT_E0_DIR false`

**Comment by Vertabreak** [comment]
PR submitted to correct this.

**Comment by GHOSTS15** [comment]
I have reported it so that you can correct it in the next stable versions

**Comment by thisiskeithb** [comment]
> I have reported it so that you can correct it in the next stable versions

Thanks for the report!

@Vertabreak put in a pull request to have it fixed: https://github.com/MarlinFirmware/Configurations/pull/463

**Comment by ellensp** [comment]
Closing issue, as this is for Configurations and PR has been created.
