### ISSUE TITLE
[BUG] [Sapphire Plus] Bed crashes into the nozzle when cancelling a print job

### ISSUE THREAD

**Issue by Bsoft2007** [MarlinFirmware/Marlin#21571]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

During a print job if i press Stop Print the Bed goes up and crash into the nozzle

### Bug Timeline

Has been there since January that I've noticed.

### Expected behavior

Bed should go down away from the nozzle and home XY

### Actual behavior

Bed goes up and crashes into the nozzle

### Steps to Reproduce

While printing, just press to Cancel/Stop the printing and it will crash the Bed into the nozzle.

### Version of Marlin Firmware

Marlin 2.0 Bugfix (07-04-2021)

### Printer model

Sapphire Plus

### Electronics

Stock

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

**Comment by Bsoft2007** [comment]
Found the solution! 
[Configuration_adv.h]
#define EVENT_GCODE_SD_ABORT "G1 Z20\nG28XY"      // G-code to run on SD Abort Print (e.g., "G28XY" or "G27") 

modified to:
#define EVENT_GCODE_SD_ABORT "G28XY"

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
