### ISSUE TITLE
[BUG] Latest 2.0 Bugfix Branch just compiled now BLTOUCH menu disappear on MKS UI version

### ISSUE THREAD

**Issue by BaltasarParreira** [MarlinFirmware/Marlin#21572]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

As the title says, the bltouch menu disappear, so now it's difficult to calibrate after the autolevel the z-offset.
This version I just compiled now fixes a lot of problems I have before, but this is really important to easy tune that parameter.
Using just by setup a value on the level settings menu it's a shot in the dark since I can't see if the value I'm putting is ok or going to have my nozzle hitting the bed making a dent !

### Bug Timeline

Just now after I compile and use the corrent 2.0 Bugfix Branch

### Expected behavior

Like before, after choosing auto level button, and after finishing the probe of all the bed points setup from the Configuration.h file the bltouch menu shoes up so we have the possibility to manual check and save the Z-offset correct amount.

### Actual behavior

The reported bltouch menu is not show anywhere.

### Steps to Reproduce

1- Choose Auto Level
2- After all the bed points are checked

### Version of Marlin Firmware

2.0 Bugfix Branch from today with MKS UI settings

### Printer model

Two Trees Bluer

### Electronics

MKS Robin Nano 1.2 with 3.5" touch TFT

**Comment by BaltasarParreira** [comment]
Update:
Now I found another problem, that is printing from Cura using the MKS plugin via WIFI the printer becomes like crazy moving all around here and there in all X, Y and Z but nothing really prints in the end.
So no normal operation.

2º Update:
The crazy printing problem is everywhere after all, even normal printing from SD card does the same, so I conclude that this version is no good and apart fixing a problem to me (printer rebooting once in a while when WIFI module was connected and/or sending files trough him) can't be used for printing anything and normal operation.

**Comment by Malderin** [comment]
I do not understand what kind of bltouch menu are you talking about?

**Comment by BaltasarParreira** [comment]
You press on auto level button so the printer does the auto probing points (default 3 x 3 if we didn't change it at Configuration.h).
After finished that should show up another menu where you can them move de Z manually until the nozzle hits the piece o paper that we usually use to adjust the right Z offset value. Now there is no way of doing this seeing when the nozzle is at the right point. Just going to the settings menu a put a value on z-offset is a shot in the dark that afterword's when printing could make the nozzle hit the bed because was a guessed value.
Do you understand now?

This is the menu that I'm talking about and existed before:
![image](https://user-images.githubusercontent.com/1650425/114317984-aa0ab380-9b02-11eb-9287-8336b24df904.png)

**Comment by Malderin** [comment]
@BaltasarParreira 
Of course, I could be wrong, but I have not seen such a menu in the official marlin. I saw such a menu in the MKS branch and not here.

**Comment by BaltasarParreira** [comment]
So this branch even being more advanced and with some important bugs fixed is no good for using to compile a firmware using the MKS UI?
The real MKS you are saying has WIFI problems like for me just having the WIFI module connected makes the printer reboot once in a while or on uploading files to print because of some watchdog bugs. This one here the WIFI works perfect, but very difficult to calibrate the Z offset using Bltouch as the only way is get the value on trial and error.
You can't even go to the moving axis menu and lower the Z until you see the value you want, take a note a them go a put it in the settings because when reaches zero it stops and doesn't allow you to go lower.

**Comment by Malderin** [comment]
@BaltasarParreira 
Hopefully @MKS-Sean  will someday transfer these additions to the official marlin. For now, you will have to use other less convenient methods to configure the bltouch.

**Comment by thisiskeithb** [comment]
Closing since this is about MKS’ fork which includes features not implemented here.
