### ISSUE TITLE
Creality 4.2.7 board PIN out

### ISSUE THREAD

**Issue by jarjartee** [MarlinFirmware/Marlin#21581]
### Is your feature request related to a problem? Please describe.

I know this is not a Marlin problem but grappling in the dark here(also contacted Creality). Trying to set hot end fan to go on at 50°C but can NOT find correct PIN out - anyone got the diagrams/pin out list ????

### Are you looking for hardware support?

Creality 4.2.7 board PIN out diagram

### Describe the feature you want

How to control the HOTEND fan

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
That board only has 1 software controllable fan PA0  this is used for parts cooling. 
The K-fans are on when power is on. 
You would have to add a external mosfet and connect it somewhere to do this on this controller

**Comment by jarjartee** [comment]
thank you very much for your assistance
