### ISSUE TITLE
[BUG] (bug summary) Wrong Direction When Homing

### ISSUE THREAD

**Issue by agoy507** [MarlinFirmware/Marlin#21587]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

X axis Wrong direction when Homing All axis, another axis Normal, 
when jog, all axis normal. whats wrong? I using esp32 board.

### Expected behavior

When Homing, all axis moving to Min

### Actual behavior

Only X axis wrong direction ( Move to Max)

### Version of Marlin Firmware

2.0.7.2

### Printer model

Creality Ender 3

### Electronics

Esp32 Board
Schematics Similar with board by felixstorm
https://github.com/felixstorm/Creality_Ender_3_ESP32_Board

### Add-ons

BL Servo DIY

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by agoy507** [comment]
That's my config file.
[Marlin-2.0.xOriEsp.zip](https://github.com/MarlinFirmware/Marlin/files/6291344/Marlin-2.0.xOriEsp.zip)

**Comment by msmeeh** [comment]
in configfile : just inver the direction of the x axis, if it is true change it to false, if it false change it to true 

#define INVERT_X_DIR false   // true
