### ISSUE TITLE
[BUG] 'manual_feedrate_mm_s' was not declared in this scope; did you mean 'feedrate_mm_s'?

### ISSUE THREAD

**Issue by arbitur** [MarlinFirmware/Marlin#21598]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Here are [my config files](https://github.com/MarlinFirmware/Marlin/files/6293612/Configuration.zip)
The problem is caused by `manual_feedrate_mm_s` not being defined and it isnt defined because `MANUAL_FEEDRATE` isnt defined and it is not defined because neither `ULTIPANEL or EXTENSIBLE_UI` are defined and Im not supposed to define `ULTIPANEL` because I have `REPRAP_DISCOUNT_SMART_CONTROLLER`. Before commit f6ffbe548c81abfeecc996c8f2bffd27cabe0014 it worked because it would define `ULTIPANEL` by defining `IS_ULTIPANEL` when `REPRAP_DISCOUNT_SMART_CONTROLLER` was defined, but not after that commit. Possible fix is to change `#if EITHER(ULTIPANEL, EXTENSIBLE_UI)` to `#if EITHER(IS_ULTIPANEL, EXTENSIBLE_UI)`

### Bug Timeline

Since commit f6ffbe548c81abfeecc996c8f2bffd27cabe0014 
Specifically [this change](https://github.com/MarlinFirmware/Marlin/commit/f6ffbe548c81abfeecc996c8f2bffd27cabe0014#diff-25ea4e6f6827dc138b4ae433287fad536066dede2780b13a73fd755b57c98b4fL453)

### Version of Marlin Firmware

latest bugfix-2.0.x

**Comment by ellensp** [comment]
Config files provided are 020006, not for bugfix.

**Comment by arbitur** [comment]
Oh oops, I forgot I was on the working commit when I zipped them. Ill update.

**Comment by arbitur** [comment]
@ellensp Now Ive uploaded the correct files.

**Comment by ellensp** [comment]
New provided Config files works as expected, no errors.

**Comment by arbitur** [comment]
@ellensp Im terribly sorry Im very tired its 5am, the updated config files included my proposed fix... Ill update one last time. Try now.

**Comment by ellensp** [comment]
your configuration_adv.h line 1132 is incorrect
`#if EITHER(ULTIPANEL, EXTENSIBLE_UI)`
should be 
`#if EITHER(IS_ULTIPANEL, EXTENSIBLE_UI)`
as per the default config https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/Configuration_adv.h#L1130

**Comment by arbitur** [comment]
Wow it was during merge from bugfix remote to my local branch this problem emerged. Thanks.
