### ISSUE TITLE
Too long command line when compiling under Windows10

### ISSUE THREAD

**Issue by arka2pol** [MarlinFirmware/Marlin#21591]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Compiling under linux goes OK, but compiling under Windows gives a message:

(#define CONFIGURATION_H_VERSION 020007)

fork/exec C:\Users\andrzej.kowalski.RAC\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7/bin/avr-gcc.exe: The filename or extension is too long.
Błąd kompilacji  dla płytki (= compilation error for board) Arduino Mega or Mega 2560.

:-)

### Steps to Reproduce

just try to compile under Win10

### Version of Marlin Firmware

newest

### Printer model

Prusa compatible self made

### Electronics

rumba

### Add-ons

BL-Touch

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by GMagician** [comment]
Not sure arduino is still supported as development tools but this "path too long" issue, I suspect, it needs you to move your source in a short path (eg c:\marlin)

**Comment by bill-orange** [comment]
I agree with @GMagician .  I don't think the Arduino compiler is supported anymore.  I tried compiling for an 8-bit machine with the Arduino compiler a few months ago, as a test,  and had the same problem.

I think you are going to have to switch to VSCode.  Its just as well.  For a complex project like Marlin, VSCode is much more suitable, especially if you combine it with your own Github repository.  If I could not track and review my changes, I would be lost.

**Comment by Liriel-666** [comment]
That's a normal arduino error and not marlin special. 
Because that you should use visual Code studio which is ways better

**Comment by arka2pol** [comment]
Tried, (C:\A ), also tried one letter user name. No result

It seems it is no way to move temporary files somewhere else, always uses “….appdata/local…….”

 

(by the way – please propose another compiler?)

**Comment by arka2pol** [comment]
Will try….. (wrrrrrr, I like Arduino)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
