### ISSUE TITLE
[BUG] Z_SAFE_HOMING - X axis not in center

### ISSUE THREAD

**Issue by bobernik** [MarlinFirmware/Marlin#21600]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello, 

I bought a SKR 1.4 Turbo with TMC 2209 for xyz axis and LV8729 for extruder, so that i could use lin advance (didnt work on TMC 2208) on my ender 3. Because i couldnt find a config for this setup, i'm trying to do it myself with help from YT guides, since i'm not very experienced in coding.

When i do g28, x and y axis home successfully with sensorless homing. After that, when trying to move to the bed center for Z homing, X axis stepper starts skipping (assuming from correct X value on the screen after Z_SAFE HOMING). Similar issue, when trying to ABL.

Another issue is, that Z axis is very loud, again, only when homing.

When i move x/y/z with move axis on the printer or with pronterface, non of these issues happens.

[Video](https://user-images.githubusercontent.com/82367782/114362123-45d60700-9b77-11eb-96a6-48191b65b047.mov)

Config: [bobernik_config.zip](https://github.com/MarlinFirmware/Marlin/files/6294990/bobernik_config.zip)

Belt looks okey, tried to increase the current up to 1,3 A with no success.

I would really appreciate any help after 2 weeks of struggle.

Thanks in advance.

### Bug Timeline

12.4.2021

### Expected behavior

homing in center of bed

### Actual behavior

X stepper skipping when homing

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Creality Ender 3

### Electronics

SKR 1.4 turbo,

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
