### ISSUE TITLE
[BUG] (SKR_PRO with flash drive failed to compile)

### ISSUE THREAD

**Issue by supernielsen** [MarlinFirmware/Marlin#21609]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have a SKR PRO v1.2 board.

using the lates BUGFIX marlin i get some errors while i compile.

### Bug Timeline

NEW bug when i like to change to lates bugfix branch to enable usb support

### Expected behavior

I expected it to compile without errors.

### Actual behavior

Marlin\src\HAL\STM32\HAL.h:54:21: error: 'MSerial0' was not declared in this scope; did you mean 'MSerial10'?

Marlin\src\HAL\STM32\../../inc/../core/serial.h:110:74: error: template argument 1 is invalid

Marlin\src\HAL\STM32\../../inc/../core/serial.h:129:47: error: request for member 'write' in 'multiSerial', which is of non-class type 'SerialOutputT' {aka 'int'}

### Steps to Reproduce

1. make configuration
2. Build configuration with env SKR_PRO_USB_FLASH_DRIVE

### Version of Marlin Firmware

LATEST BUGFIX 020008

**Comment by supernielsen** [comment]
![0](https://user-images.githubusercontent.com/33903236/114612997-158b8700-9ca3-11eb-9108-0d791a52a5dd.PNG)
![1](https://user-images.githubusercontent.com/33903236/114613008-19b7a480-9ca3-11eb-8b56-2930e03af4f0.PNG)
![2](https://user-images.githubusercontent.com/33903236/114613016-1b816800-9ca3-11eb-9ae9-ddf43b32fd9f.PNG)
![3](https://user-images.githubusercontent.com/33903236/114613022-1d4b2b80-9ca3-11eb-995b-08aefa2215be.PNG)

**Comment by ellensp** [comment]
Trigger is when you set a serial port to -1 on that env.

**Comment by ellensp** [comment]
Looks to be deliberate, perhaps usb_flash_drive and a usb cdc serial are incompatible. 
In env:BIGTREE_SKR_PRO_usb_flash_drive
is `build_unflags     = -DUSBCON -DUSBD_USE_CDC` which disabled usb cdc serial

**Comment by thisiskeithb** [comment]
> Looks to be deliberate, perhaps usb_flash_drive and a usb cdc serial are incompatible.

Correct.

You have to move jumpers on the board as well when deciding which feature to enable:
![image](https://user-images.githubusercontent.com/13375512/114715876-5d80cd00-9ce8-11eb-9a7d-845ee5f5ab0e.png)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
