### ISSUE TITLE
[BUG] (marlin auto build error)

### ISSUE THREAD

**Issue by MatessakCZE** [MarlinFirmware/Marlin#21628]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

getting this error: collect2.exe: error: ld returned 1 exit status

### Bug Timeline

i dont know but it happens from start

### Expected behavior

i expected it builds the marlin without any peoblem

### Actual behavior

getting error message ad not working

### Version of Marlin Firmware

2.0.7.1

### Printer model

Creality Ender 3 V2

### Electronics

bltouch

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by ellensp** [comment]
Works fine. Must be local machine issue.

Delete .platformio directory in your home directory. Force platformio to reinstall.   

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
