### ISSUE TITLE
[BUG] Automatic Delta calibration failed.

### ISSUE THREAD

**Issue by Foxies-CSTL** [MarlinFirmware/Marlin#21620]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I own a Delta printer and have merged with the latest BugFix. The compilation is good but I have Delta calibration problems. The auto-home works well but as soon as I launch an autocalibration, the sequence starts well (autohome), the whole goes down to half height and starts probing but in a vacuum. After the first iteration is finished, it announces that it is a failure.
I have checked my settings with an M503 and everything is correct !!
Any idea on the change in sources that causes this?

### Bug Timeline

new bug because with BUMP 21-04-05, all is correct.

### Expected behavior

Several sequences of bed probing (iteration)

### Actual behavior

The moves are in middle of the height.

### Steps to Reproduce

After flash + M502 and M500, I run a AutoCalibration Delta.
After the movement to "HOME", the beginning of the movement to the bed fails and the status message announces "Probe failed".

### Version of Marlin Firmware

BUMP 21-04-27

### Printer model

FLSUN QQS-Pro Delta

### Electronics

Probe failed

### Add-ons
Configuration Marlin 
[Configs_QQS_Pro.zip](https://github.com/MarlinFirmware/Marlin/files/6320056/Configs_QQS_Pro.zip)

### Host Software
Live and by Octoprint

**Comment by thisiskeithb** [comment]
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information:

- Download Marlin [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed. This will also enable bed leveling.
- Do some of the moves that revealed problems before. Take notes.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.

**Comment by Foxies-CSTL** [comment]
@thisiskeithb 
Add the M11 S247 + machine parameters + Configs in the message above.
[Bug_G33.log](https://github.com/MarlinFirmware/Marlin/files/6319616/Bug_G33.log)
[M503_QQS.txt](https://github.com/MarlinFirmware/Marlin/files/6319642/M503_QQS.txt)

**Comment by Foxies-CSTL** [comment]
@thisiskeithb 
No correction, no solution ?

**Comment by rhapsodyv** [comment]
can you test #21781 ?

**Comment by rhapsodyv** [comment]
The fix was merged
