### ISSUE TITLE
[BUG] M33 appears broken

### ISSUE THREAD

**Issue by cappuccino02** [MarlinFirmware/Marlin#21636]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Method:
Connect the BIGTREETECH SKR PRO 1.2 3D printer motherboard to the computer via the USB cable, used the serial debugger to send the G code command, and use the M33 command to get the complete file name. Chinese characters appear gibberish.

### Version of Marlin Firmware

2.0.6.1

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by cappuccino02** [comment]
Hello，M33 command to get the full file name, Chinese does not display









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarlinFirmware/Marlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月17日(星期六) 下午3:39
***@***.***&gt;;
抄送:&nbsp;"WEJIR   ENCJI   YA     ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarlinFirmware/Marlin] [BUG] (bug summary)Using M33 Command in Marlin Firmware to read the complete file name, gibberish Chinese Characters are appeared? (#21636)





 
Please download bugfix-2.0.x to test with the latest code and let us know if you're still having this issue.

**Comment by thinkyhead** [comment]
It doesn't do so great at English either:
```
M33 /EXTRUD~1/TWEETY/PLA/TW-FAN~1.GCO
> /Extruders/Tweety/???/tw-fan-adapt-CC.gcode
```

**Comment by cappuccino02** [comment]
How to use M20 to get the complete file name? And support the use of full file name to print.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarlinFirmware/Marlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 凌晨2:34
***@***.***&gt;;
抄送:&nbsp;"WEJIR   ENCJI   YA     ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarlinFirmware/Marlin] [BUG] M33 appears broken (#21636)





 
It doesn't do so great at English either:
 M33 /EXTRUD~1/TWEETY/PLA/TW-FAN~1.GCO &gt; /Extruders/Tweety/???/tw-fan-adapt-CC.gcode

**Comment by thisiskeithb** [comment]
> How to use M20 to get the complete file name? And support the use of full file name to print.

Enable `LONG_FILENAME_HOST_SUPPORT` and then issue `M20 L`.

That feature was added this summer, so be sure to download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by cappuccino02** [comment]
You can get a long file name, but it cannot be used for printing, and Chinese cannot be displayed




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarlinFirmware/Marlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 凌晨1:16
***@***.***&gt;;
抄送:&nbsp;"WEJIR   ENCJI   YA     ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarlinFirmware/Marlin] [BUG] M33 appears broken (#21636)





  
How to use M20 to get the complete file name? And support the use of full file name to print.
  
Enable LONG_FILENAME_HOST_SUPPORT and then issue M20 L.
 
That feature was added this summer, so be sure to download bugfix-2.0.x to test with the latest code and let us know if you're still having this issue.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ellensp** [comment]
You have never been able to use long file names for printing. This is how it was designed. This is not a bug

**Comment by cappuccino02** [comment]
OK, do you support printing with long file names next




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarlinFirmware/Marlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 中午1:47
***@***.***&gt;;
抄送:&nbsp;"WEJIR   ENCJI   YA     ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarlinFirmware/Marlin] [BUG] M33 appears broken (#21636)





 
You have never been able to use long file names for printing. This is how it was designed. This is not a bug
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
