### ISSUE TITLE
[BUG] Rotary encoder reboots MKS Robin Nano V1.2 when using mks_robin_nano35 env

### ISSUE THREAD

**Issue by th0m4sek** [MarlinFirmware/Marlin#21649]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Board seems to be working fine using touchscreen but when i try tu use rotary encoder board reboots.
Board is working fine when using mks_robin_nano35_stm32.

my rotary encoder is connected to E1 connector.
//#define E1_ENABLE_PIN                       PA3
//#define E1_STEP_PIN                         PA6
//#define E1_DIR_PIN                          PA1
#define BTN_ENC                           PA3 
#define BTN_EN1                           PA1 
#define BTN_EN2                           PA6 

### Version of Marlin Firmware

bugfix-2.0.x

**Comment by rhapsodyv** [comment]
If it works fine for `mks_robin_nano35_stm32`, that’s fine.

`mks_robin_nano35` is going to be deprecated soon.
