### ISSUE TITLE
[FR] Extruder stepper direction change from lcd

### ISSUE THREAD

**Issue by esunayg** [MarlinFirmware/Marlin#21645]
### Is your feature request related to a problem? Please describe.

Different extruders have different mechanical direction. It is possible to recompile or reverse the pins but it sometimes costs a mainboard, and hard for people with no electrical background.

### Are you looking for hardware support?

generic

### Describe the feature you want

Extruder stepper direction change without recompling or changing the ex pins via the screen.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/16550
