### ISSUE TITLE
[BUG] Resuming from M600 filament change extrudes while unparking nozzle

### ISSUE THREAD

**Issue by Sebazzz** [MarlinFirmware/Marlin#21669]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When using M600 and the nozzle is parked, when the print is resumed and the nozzle is being unparked a bunch of extra filament is being extruded.

### Bug Timeline

This started with a5d6f6ac9880090d2412bbea0027885b95c98ea2 #21564

### Expected behavior

When the nozzle is unparked after a filament change, no extrusion should take place.

### Actual behavior

After resuming from a parked position, during a M600 filament change, extrusion takes place during the unparking.

[Video, config files ZIP](https://github.com/MarlinFirmware/Marlin/files/6346179/Github.zip)

### Steps to Reproduce

1. Run a random print with a M600 in it *or* have M600 configured as filament runout command.
2. Run the print and wait for the M600 *or* trigger it by filament runout
3. [The nozzle is parked and *beep* *beep* *beep*]
4. Load filament by hand or automatically.
5. Resume the print (in my case from ExtUI, but it doesn't seem to matter)
6. [The nozzle is, while it is being unparked, also extruding a lot of filament]

### Version of Marlin Firmware

Latest from master

### Printer model

Creality CR-6 SE

### Electronics

BTT SKR CR6 board; filament sensor (stock)

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by Sebazzz** [comment]
Opened pull request #21670 with bugfix.

**Comment by Takiora** [comment]
Hi. 
I had the same problem and found a workaround. 
I don't know if it is the right way but it work well for me with M600 and M125 (and filament runout).
In the file pause.cpp, in the fuction resume_print, i moved the code used to resume position after the position of the extruder has been set.

[resume_print.txt](https://github.com/MarlinFirmware/Marlin/files/6352568/resume_print.txt)

**Comment by Sebazzz** [comment]
Has been fixed and merged via #21670
