### ISSUE TITLE
[BUG] M112 emergency stop  ignored during G12 P1 clean nozzle

### ISSUE THREAD

**Issue by dwery** [MarlinFirmware/Marlin#21666]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

While executing G12 P1 from OctoPrint terminal, G112 is ignored.

### Version of Marlin Firmware

dda2f58588a0a2fca45aa7cc673f9af020163959

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by fedetony** [comment]
Your bug description says G112, isn't it M112?
Notice if you put the code differently will not work, as `G112` or `m112` do no have any effect but unknown command response.

**Comment by dwery** [comment]
@fedetony good catch, let me try and check if I did the mistake while writing here or in the console...

**Comment by ellensp** [comment]
Still no config files?  Did a re-test show anything?

**Comment by dwery** [comment]
@fedetony you were right, it worked. I can’t recall what I did but most probably I punched in the code manually and mistakenly used the wrong one.
