### ISSUE TITLE
[BUG] Y motor movement is something strange when Dual nozzle

### ISSUE THREAD

**Issue by EYHJ59** [MarlinFirmware/Marlin#21667]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When DUAL_X_CARRIAGE is used, after G28R0 XY, Y movement is strange.

I add something to G28() and problem is resolved.
I need your opinion. This is good solution? etc...

// Home X
    if (doX || (doY && ENABLED(CODEPENDENT_XY_HOMING) && DISABLED(HOME_Y_BEFORE_X))) {

      #if ENABLED(DUAL_X_CARRIAGE)

        // Always home the 2nd (right) extruder first
        active_extruder = 1;
        homeaxis(X_AXIS);

        // Remember this extruder's position for later tool change
        inactive_extruder_x_pos = current_position.x;

        // Home the 1st (left) extruder
        active_extruder = 0;
        homeaxis(X_AXIS);

        // Consider the active extruder to be parked
        raised_parked_position = current_position;
        delayed_move_time = 0;
        active_extruder_parked = true;

      #else

        homeaxis(X_AXIS);

      #endif
    }
   if (DISABLED(HOME_Y_BEFORE_X) && doY) {
      homeaxis(Y_AXIS);
      raised_parked_position = current_position;    -> I add this.
   }

If HOME_Y_BEFORE_X is enabled, this fix is not useless because if (doX || ~~~) have raised_parked_position = current_position;

### Expected behavior

Y motor movement works well.

### Actual behavior

Y motor moves strange.

### Steps to Reproduce

For example,
G28R0 XY then G0 X100 Y100
Y moves very slowly and go to strange position then speed up and go to right position(of gcode)

### Version of Marlin Firmware

2.0.6.2

### Electronics

SKR pro v1.4

### Your Slicer

Slic3r

### Host Software

Pronterface

**Comment by thisiskeithb** [comment]
Since you've provided a fix, it'd be faster if you submitted a [Pull Request](https://marlinfw.org/docs/development/getting_started_pull_requests.html) so it can be reviewed.
