### ISSUE TITLE
Crash Detection and Recovery

### ISSUE THREAD

**Issue by abbadonshop** [MarlinFirmware/Marlin#21675]
Crash Detection and Recovery would be an excellent addition to Marlin, of the same type of routine that is implemented by Prusa.
I am not versed enough to program, but I imagine that a similar setup to the Power Outage Detection and Recovery could be implemented, where if the Stallguard enabled driver detects a stall, it would pause the print, re-home the x and y, and then resume the G-Code as needed.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/8765
