### ISSUE TITLE
Missing the job percentage on display

### ISSUE THREAD

**Issue by gchek** [MarlinFirmware/Marlin#21681]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Ender 3 pro - the display is lacking the % of job completion. I see a >> 100% but i think this is realted to speed and not very useful.
I see the bar moving but no %

Thanks 

### Bug Timeline

when I moved to Marlin 2.0

### Version of Marlin Firmware

2.0.7.2

### Printer model

Ender 3 pro

### Electronics

v2.4.2 board

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by gchek** [comment]
![IMG_9492](https://user-images.githubusercontent.com/25104887/115845055-c40c9600-a420-11eb-8944-cb5e8d6f844d.jpg)

**Comment by ellensp** [comment]
The indicated area is a feed rate percentage.
if you rotate the dial left and right it will go up and down.
It globally speeds up or slows down the printer.

**Comment by ellensp** [comment]
You need to enable #define DOGM_SD_PERCENT in Configuration_adv.h

The percentage is then shown on the right of the progress bar

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
