### ISSUE TITLE
LONG_FILENAME_HOST_SUPPORT

### ISSUE THREAD

**Issue by MagoKimbra** [MarlinFirmware/Marlin#2172]
if define this ide give me error
error: 'strchr_pointer' was not declared in this scope
error: 'clear_asterisk' was not declared in this scope

```
inline void gcode_M33() {
      char *args = strchr_pointer + 4;
      while (*args == ' ') ++args;
      clear_asterisk(args);
      card.printLongPath(args);
}
```

**Comment by thinkyhead** [comment]
Needs an update for the latest parser code, apparently. I will patch it later. The code should be

```
inline void gcode_M33() { card.printLongPath(current_command_args); }
```

**Comment by thinkyhead** [comment]
#2190
