### ISSUE TITLE
[BUG] FAN_PIN can't be used as E0_AUTO_FAN_PIN on SKR 2.0

### ISSUE THREAD

**Issue by Guilouz** [MarlinFirmware/Marlin#21735]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

FAN_PIN (PB7) can't be used as E0_AUTO_FAN_PIN on SKR 2.0

FAN1_PIN is working.

### Expected behavior

All fans pins can be used for E0 auto fan pin

#ifndef FAN_PIN
  #define FAN_PIN                           PB7   // Fan0
#endif
#ifndef FAN1_PIN
  #define FAN1_PIN                          PB6   // Fan1
#endif
#ifndef FAN2_PIN
  #define FAN2_PIN                          PB5   // Fan2
#endif

### Version of Marlin Firmware

Latest bugfix

### Electronics

BigTreeTech SKR 2

**Comment by thisiskeithb** [comment]
This isn't a bug. Marlin uses FAN0 as the parts cooling fan by default if defined for any board.
