### ISSUE TITLE
ABL probing grid #HEATERS_OFF

### ISSUE THREAD

**Issue by legend069** [MarlinFirmware/Marlin#21740]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi

i'm trying to improve my ABL accuracy ( M48 ) results 

when i run m48 i get results under 0.001500.
but as soon as i enable the bed heating and run m48 again the results jump up to between 0.00500 - 0.0100

is someone able to explain how the "heaters_off" function works?
or if there is a easy fix so that it will heat the bed back up in between probes if the bed temperature drops below "x" amount 

### Bug Timeline

old i think?

### Expected behavior

with bed heated to 60c
home all axis 
m48
z starting position 5
turns heaters off
z starts to move down to probe the bed
z probes the bed
turns heaters back on if the temp is below "x"
z moves back to starting position of 5
waits for heaters if temp is below "x"

repeat 10 times
report results.

### Actual behavior

works as expected kindof ?

with bed heated to 60c
home all axis 
m48
first probe starts turns heaters off
probes bed and turns heaters back on
z is now back at 5 ready to probe bed

second probe starts turns heaters off
probes bed and turns heaters back on

repeat 10 times

### Steps to Reproduce

1. heat bed to 60
2. G28 to home axis
3. M48 to test accuracy 
4. probing starts
5. at what point does it turn the heaters off during the probing movements 
6. probing ends
7. displays results.

### Version of Marlin Firmware

2.0.7.2

### Printer model

ender3

### Electronics

skr btt mini v2

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6398087/Configuration.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
