### ISSUE TITLE
[FR] Give yourselves a pat on the back!

### ISSUE THREAD

**Issue by rq3** [MarlinFirmware/Marlin#21752]
### Is your feature request related to a problem? Please describe.

No problem at all. Just updated from 2.0.7.2 to 2.0.8 on an Anycubic Predator Delta. The compile and install went flawlessly. Heater control is MUCH faster and more stable. I have a few issues with probing, but I'm sure that is my weird, custom set-up.

NICE JOB ALL!

### Are you looking for hardware support?

Nope.

### Describe the feature you want

All good!

### Additional context

Just didn't know where else to say kudos!

**Comment by thinkyhead** [comment]
Good to hear your experience has been positive!
