### ISSUE TITLE
[BUG] MKS Robin Nano v3 Freezes with 2.0.8

### ISSUE THREAD

**Issue by Dtcreation** [MarlinFirmware/Marlin#21764]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

No more serial port :  
No usb connexion
No tft serial port active

### Expected behavior

Connexion with PC or Octoprint
Connexion with MKS TFT 28

### Actual behavior

No connexion with PC or Octoprint and no connexion with the screen

### Version of Marlin Firmware

2.0.8

### Printer model

Artillery Genius

### Electronics

MKS Robin Nano V3

### Host Software

OctoPrint

**Comment by rhapsodyv** [comment]
It seems a configuration issue. You should attach your configs as requested in the template.

**Comment by Dtcreation** [comment]
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/6410134/Archive.zip)
Not a configuration issue, same configuration than MKS Marlin

**Comment by McDAK33** [comment]
I join. I have the same problem. USB works if you set default_envs = mks_robin_nano_v3 in the platformio.ini file and comment out #define USB_FLASH_DRIVE_SUPPORT in the file
Configuration_adv.h. But the connection is unstable and hangs up after a few minutes.
If you set default_envs = mks_robin_nano_v3_usb_flash_drive_msc and #define USB_FLASH_DRIVE_SUPPORT, then the board freezes when connected.

**Comment by rhapsodyv** [comment]
Can you test disabling watchdog? In Configuration_adv.h comment out: `// #define USE_WATCHDOG`

**Comment by McDAK33** [comment]
I tested it. When connected, the board did not hang, a COM port appeared on the PC. There is still no connection:
`Connecting...
[ERROR] Can't write to printer (disconnected?) (SerialException): Write timeout`

**Comment by rhapsodyv** [comment]
> I tested it. When connected, the board did not hang, a COM port appeared on the PC. There is still no connection:
> `Connecting... [ERROR] Can't write to printer (disconnected?) (SerialException): Write timeout`

Unplug and plug the cable.

**Comment by McDAK33** [comment]
Tried it - doesn't work.

**Comment by rhapsodyv** [comment]
Did you try disable all serial ports? (Just to give us hint to locate the issue)

**Comment by MiHeK** [comment]
Compare Configuration.h with older one. There should be #define SERIAL_PORT 1 . Instead of 0 in new version. May be this is the reason?

**Comment by McDAK33** [comment]
I will do everything in my power to help.
I faced this problem for a long time #21603
MKS recommended `#define SERIAL_PORT -1` and it always worked.

**Comment by McDAK33** [comment]
Not quite sure how to disable all serial ports?

**Comment by Dtcreation** [comment]
I tryed with all serial desactivated. Same problem. Not a configuration.h problem. Either a platform.io or stm32 problem

**Comment by ellensp** [comment]
well how about attaching your platformio.ini file then?

**Comment by Dtcreation** [comment]
Not the file but the buildroot/share/platformiO, i have the Marlin original but it seems to have a bug

**Comment by rhapsodyv** [comment]
Can you test this #21775?

**Comment by willngton** [comment]
> Can you test this #21775?

I've tested with below PR and no longer facing the issue 

* Tested with LVGL - OK
* Tested with ColorUI - OK
* Connected via miniterm with no issues
* Did not test multi-volume

### it seams to have an issue with the hardware, board wont "post" with an USB stick inserted ( after power removed)  unless re-seat button is pressed.

![Selection_328](https://user-images.githubusercontent.com/5961905/116818142-c1542400-ab37-11eb-8d00-10e694e20fb7.png)

**Comment by rhapsodyv** [comment]
I didn't understand your last issue.

**Comment by willngton** [comment]
> I didn't understand your last issue.

Upload a video sample for my Robin Nano V3.0

### With usb stick connected wont come up till re-seat button is pressed 
https://user-images.githubusercontent.com/5961905/116819335-b8665100-ab3d-11eb-9f5d-d57e8d507c0d.mp4


https://user-images.githubusercontent.com/5961905/116819347-bd2b0500-ab3d-11eb-8a21-b2ed5f3e4ae5.mp4

**Comment by McDAK33** [comment]
Tested with MKS H43. Results:
- COM port is present
- USB disk present
- The connection is established, but when you try to print a test cube, the connection is disconnected at the sixth minute of printing. After using `M575 B250`, I managed to print the cube to the end.
- The temperature on the H43 display is not correct (as a reminder).

I conclude that the connection has appeared, but it is unstable.
Some problems with the connection speed.

**Comment by Dtcreation** [comment]
HI,

With the PR everything seems good to me, but i have to test a long print to confirm

Thanks

**Comment by rhapsodyv** [comment]
> Tested with MKS H43. Results:
> 
> * COM port is present
> * USB disk present
> * The connection is established, but when you try to print a test cube, the connection is disconnected at the sixth minute of printing. After using `M575 B250`, I managed to print the cube to the end.
> * The temperature on the H43 display is not correct (as a reminder).
> 
> I conclude that the connection has appeared, but it is unstable.
> Some problems with the connection speed.

It’s seems an issue with H43, not the nano v3.

**Comment by McDAK33** [comment]
> > Tested with MKS H43. Results:
> > 
> > * COM port is present
> > * USB disk present
> > * The connection is established, but when you try to print a test cube, the connection is disconnected at the sixth minute of printing. After using `M575 B250`, I managed to print the cube to the end.
> > * The temperature on the H43 display is not correct (as a reminder).
> > 
> > I conclude that the connection has appeared, but it is unstable.
> > Some problems with the connection speed.
> 
> It’s seems an issue with H43, not the nano v3.

H43 has no effect on problems with Robin Nano V3. I also have MKS TS35 V2.0. For a long time there was a problem with the USB connection, and this screen was tested.
I did not notice any difference in the behavior of the Nano V3.

**Comment by rhapsodyv** [comment]
@McDAK33  All `M575` does is the same that is done at boot time: start serial with `BAUDRATE` from the `Configuration.h`. Maybe what is "fixing" your issue is that it restart the serial. But none of this code is exclusive to Nano V3.

Where do you connect the H43 in the nano v3 board?

**Comment by rhapsodyv** [comment]
> ### With usb stick connected wont come up till re-seat button is pressed
>  NanoV3_Boot_USB.mp4 
> 
>  NanoV3_Boot_NoUSB.mp4

I tested and I don't have this issue. Can you attach your configs?

**Comment by McDAK33** [comment]
@rhapsodyv I understand that perfectly. `Configuration.h` is always set to` #define BAUDRATE 250000`. But the fact remains. After switching on, the connection is interrupted, and after `M575`, the print goes to the end. Why is this happening and I would like to find out.

**Comment by rhapsodyv** [comment]
> @rhapsodyv I understand that perfectly. `Configuration.h` is always set to` #define BAUDRATE 250000`. But the fact remains. After switching on, the connection is interrupted, and after `M575`, the print goes to the end. Why is this happening and I would like to find out.

Sure, for some reason the serial is freezing,  and when you send `M575` it's restarting it. Where do you connect the H43 in the nano v3?

**Comment by McDAK33** [comment]
![H43_ROBIN_NANO_V3](https://user-images.githubusercontent.com/80269041/116822169-ef605500-ab85-11eb-8566-a3f0186e7c60.jpg)

**Comment by willngton** [comment]
> I tested and I don't have this issue. Can you attach your configs?

[Configuration_w.h.txt](https://github.com/MarlinFirmware/Marlin/files/6411963/Configuration_w.h.txt)
[Configuration_adv_w.h.txt](https://github.com/MarlinFirmware/Marlin/files/6411964/Configuration_adv_w.h.txt)

**Comment by rhapsodyv** [comment]
> > I tested and I don't have this issue. Can you attach your configs?
> 
> [Configuration_w.h.txt](https://github.com/MarlinFirmware/Marlin/files/6411963/Configuration_w.h.txt)
> [Configuration_adv_w.h.txt](https://github.com/MarlinFirmware/Marlin/files/6411964/Configuration_adv_w.h.txt)

Are you using external power in your tests? Or usb power?

**Comment by willngton** [comment]
> > > I tested and I don't have this issue. Can you attach your configs?
> > 
> > 
> > [Configuration_w.h.txt](https://github.com/MarlinFirmware/Marlin/files/6411963/Configuration_w.h.txt)
> > [Configuration_adv_w.h.txt](https://github.com/MarlinFirmware/Marlin/files/6411964/Configuration_adv_w.h.txt)
> 
> Are you using external power in your tests? Or usb power?

I found the issue, its oddly but is my USB stick, tested with another one and is working fine.

Thanks for having a look

**Comment by rhapsodyv** [comment]
So, this can be closed?

The H43 issue is being handle in #21603, right?
