### ISSUE TITLE
[BUG] Assisted tramming validation bug v2.0.8

### ISSUE THREAD

**Issue by sammy2142** [MarlinFirmware/Marlin#21788]
### Did you test the latest `bugfix-2.0.x` code?

Yes

### Bug Description

The current checks for bed limits are incorrect. The check for the left side of the bed is correct but the right side is incorrect for the x-axis.
My probe has an x offset of -42.0 (so the probe is to the left side of the nozzle).
If you set PROBING_MARGIN 0 and just use the inbuilt checks the probe points on the left side of the bed are correctly limited to nozzle position of x >= 42 so the probe doesn't run off the bed.
What is incorrect is this same limit is applied on the right side of the bed. Since the probe is on the left of the nozzle even if you set x to the bed max (235 in my case) the probe will never run off the bed. 
So the max limit for the probe on the right side should be the nozzle bed limit and not (nozzle bed limit - x offset).
Please see attached picture below.
Y limits should also be looked at as well as x limits if probe is to the right of the nozzle (+ve offset)

### Bug Timeline

v2.0.8

### Version of Marlin Firmware

v2.0.8

### Printer model

Ender 3

### Electronics

BTT mini skr e3 v2.0

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

![assited tramming](https://user-images.githubusercontent.com/5837771/116894208-b5488f00-ac29-11eb-9415-3450ae966191.png)

**Comment by Marlor** [comment]
Can not confirm this Bug.

Have a look if you have set the right Travel limits in addition to bed size.
This way the Probe has a wider range of motion

**Comment by thisiskeithb** [comment]
Please attach your configs like the bug report template asked.

**Comment by thisiskeithb** [comment]
Looking at this more closely, this isn't a bug. If your hardware allows & you want to probe more of the area on the right side of the bed, increase `X_MAX_POS`.

**Comment by sammy2142** [comment]
Hi @thisiskeithb & @Marlor 
Could you have another look at this please?
My config files:
[config_marlin.zip](https://github.com/MarlinFirmware/Marlin/files/6420295/config_marlin.zip)

My X_MAX_POS is correctly set
#define X_BED_SIZE 235 
#define X_MAX_POS X_BED_SIZE

The build error is:
`In file included from Marlin\src\feature\tramming.cpp:27:0:
Marlin\src\feature\tramming.h:36:36: error: static assertion failed: TRAMMING_POINT_XY point 1 is not reachable with the default NOZZLE_TO_PROBE offset and PROBING_MARGIN.
 #define VALIDATE_TRAMMING_POINT(N) static_assert(N >= G35_PROBE_COUNT || Probe::build_time::can_reach(screws_tilt_adjust_pos[N]), \
                                    ^
Marlin\src\feature\tramming.h:38:29: note: in expansion of macro 'VALIDATE_TRAMMING_POINT'
 VALIDATE_TRAMMING_POINT(0); VALIDATE_TRAMMING_POINT(1); VALIDATE_TRAMMING_POINT(2); VALIDATE_TRAMMING_POINT(3); VALIDATE_TRAMMING_POINT(4); VALIDATE_TRAMMING_POINT(5);
                             ^~~~~~~~~~~~~~~~~~~~~~~
Marlin\src\feature\tramming.h:36:36: error: static assertion failed: TRAMMING_POINT_XY point 2 is not reachable with the default NOZZLE_TO_PROBE offset and PROBING_MARGIN.
 #define VALIDATE_TRAMMING_POINT(N) static_assert(N >= G35_PROBE_COUNT || Probe::build_time::can_reach(screws_tilt_adjust_pos[N]), \`

Doing some more testing it definitely seems the validation check for tramming points is setting nozzle movement limits on all 4 sides of the bed.

If my probe is to the left and in front of the nozzle, the probe can only go off the bed at the left and front side of the bed in normal nozzle xy range.
Another example is if your probe is to the right and behind the nozzle, the probe can only go off the bed at the right and back side of the bed in normal nozzle xy range.

For the validation check you only need to apply nozzle movement limits on at most 2 sides of the bed (not all sides).

Ps. my PROBING_MARGIN is set to 0 so shouldn't affect the validation

**Comment by Marlor** [comment]
`X_MAX_POS` is not your `X_BED_SIZE`

Use manual move to see how far your gantry really can go and set `X_MAX_POS` accordingly
Remember to disable soft endstops

**Comment by sammy2142** [comment]
Firmware is not building because of the tramming validation error. So cant calibrate x max and min etc yet.

**Comment by Marlor** [comment]
Disable tramming in the meantime, you need to reflash anyway after you found the right `X_MAX_POS/Y_MAX_POS`

**Comment by sammy2142** [comment]
My gantry is not massively out anyway maybe max 1 step or microstep whatever its measured in - so I'm not too worried about calibrating this. It shouldn't cause the tramming validation error on build though.

**Comment by Marlor** [comment]
Your TRAMMING_POINT_XY x point is on 235
Your PROBE_OFFSET for x is -42
Your X_MAX_POS is 235

Translated: Probe 42 mm further out than the Travel limits allow

**Comment by sammy2142** [comment]
> Your TRAMMING_POINT_XY x point is on 235
> Your PROBE_OFFSET for x is -42
> Your X_MAX_POS is 235
> 
> Translated: Probe 42 mm further out than the Travel limits allow

No
The probe is to the left of the nozzle - the nozzle can go right to 235 and the probe is still on the bed :)
This is the check that's the problem ;)

**Comment by sammy2142** [comment]
x min should be limited to 42 as this the side of the bed where the nozzle can go off
235 is fine.
Regards

**Comment by Marlor** [comment]
Thats not what you wrote in your Config
Can the Probe phisicaly hit 235?

**Comment by sammy2142** [comment]
The nozzle can hit 235 and the probe will be at 193 at this position since it is 42 to the left - it may be better if I take a picture if this is not clear.

**Comment by Marlor** [comment]
TRAMMING_POINT_XY are coordiantes to Probe
You are telling Marlin to probe 235 which is not possible

**Comment by sammy2142** [comment]
Ok thanks I will check this - I thought they were nozzle positions (and I was calculating where the probe would be).
I will report back if this fixes it.

**Comment by sammy2142** [comment]
Ok my bad it woks when setting probe point locations and not nozzle points. 
I lost my old config file and got my tramming points back from running g35 and writing down the locations (and of course these were the nozzle locations).
I was pulling my hair out for a while wondering why it was working on 1.7.2 and not 1.8.0 
Thanks for helping me 👍 
Regards

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
