### ISSUE TITLE
[BUG] no media

### ISSUE THREAD

**Issue by Robenc** [MarlinFirmware/Marlin#21786]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

getting no media

### Bug Timeline

Stasrted with 2.0.8

### Actual behavior

its not reading the SD card on the on board slot

### Version of Marlin Firmware

2.0.8

### Printer model

Creality Ender 3

### Electronics

BTT Skr Mini e3 v2

**Comment by ellensp** [comment]
Did you set #define SDCARD_CONNECTION ONBOARD  and  #define SDSUPPORT ?

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by Robenc** [comment]
files are the ones in the config not modified
[BigTreeTech SKR Mini E3 2.0.zip](https://github.com/MarlinFirmware/Marlin/files/6415361/BigTreeTech.SKR.Mini.E3.2.0.zip)

**Comment by Robenc** [comment]
> 
> 
> Please attach your configuration files.

just uploaded

**Comment by Robenc** [comment]
> 
> 
> Did you set #define SDCARD_CONNECTION ONBOARD and #define SDSUPPORT ?

could it be that the configuration files online are missing some coding ?

**Comment by Robenc** [comment]
connected printer to pc and issued a m21 and it sees the card fine shutdown print power on an no media again
![20210506_202438 1](https://user-images.githubusercontent.com/69157976/117381721-bf2cf500-aeaa-11eb-8e26-2b8f61f5842a.jpg)

**Comment by Robenc** [comment]
![20210506_202454 1](https://user-images.githubusercontent.com/69157976/117381909-28ad0380-aeab-11eb-8089-4f3953e1af09.jpg)

**Comment by Robenc** [comment]
after m21

![20210506_204043 1](https://user-images.githubusercontent.com/69157976/117381985-690c8180-aeab-11eb-96ee-9b2f7be39eda.jpg)

**Comment by Robenc** [comment]
a little more help on the issue at hand

**Comment by Robenc** [comment]
> 
> 
> Please attach your configuration files.

sent more info to help

**Comment by rhapsodyv** [comment]
I have a SKR MINI E3 V2. I just tested your configs and everything worked fine with current bugfix. 

I think you have a hardware issue.

Try testing with old marlin versions to see if the issue happen. You can reopen this issue if older marlin versions works for you.
