### ISSUE TITLE
Error: 'init' is not a member of 'U8GLIB' 

### ISSUE THREAD

**Issue by gunsmith69** [MarlinFirmware/Marlin#21798]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Get this error when verifying code. I have tried redownloading the u8glib file and tried changing it to the older version but i keep getting it. 
sketch\src\lcd\dogm\HAL_LCD_class_defines.h:134:13: error: 'init' is not a member of 'U8GLIB'
     U8GLIB::init(&u8g_dev_ssd1309_hw_spi, (uint8_t)cs, (uint8_t)a0, (uint8_t)reset);
             ^~~~
exit status 1
Error compiling for board Sanguino.

### Version of Marlin Firmware

2.0

### Printer model

Ender 5 pro

**Comment by ellensp** [comment]
You cannot use standard ug8 library that arduino ide gets any more. It was extended and now needs the init function.
Use platformio under vscode so it uses the correct marlin https://github.com/MarlinFirmware/U8glib-HAL 

https://marlinfw.org/docs/basics/install_platformio_vscode.html

You can use this library under arduino ide, but it is not simple. platfomio is the way forward
