### ISSUE TITLE
Neopixel PRINTER_EVENT_LEDS not working

### ISSUE THREAD

**Issue by marouan86** [MarlinFirmware/Marlin#21806]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

 The neopixel LED strip (WS2812B) can be controlled using M150 command. However even though PRINTER_EVENT_LEDS enabled, the led strip colors not change in function of nozzle/bed temp.

### My Configurations

[https://drive.google.com/file/d/1RKy-8IKi82wlm0O_P5XLqw5Emr0ksFqx/view?usp=sharing](url)

### Steps to Reproduce

With the configuration above turn on the printer, hit print button then  the nozzle/bed temperature increase, but the NeoPixel led strip still OFF.

### Version of Marlin Firmware

BugFix2.0.x

### Electronics

SKR 1.4 turbo

### Your Slicer
Cura

**Comment by ellensp** [comment]
Please fill in Steps to Reproduce section and attach your Config files.

**Comment by shitcreek** [comment]
This might be related to this issue which has a solution proposed: https://github.com/MarlinFirmware/Marlin/issues/21789

**Comment by marouan86** [comment]
This solution didn't help
