### ISSUE TITLE
Fix E3V2 Control menu icons and texts orderings

### ISSUE THREAD

**Issue by AdrianDC** [MarlinFirmware/Marlin#21837]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Follow-up commit to #21534 to resolve the "Control" menu icons and texts upon "Back" events

### Bug Timeline

"Info" placement was an old issue, Icons and texts switching is due to "Advanced Settings"

### Expected behavior

Menus should keep the same UI upon scroll or back complete redraws.

### Actual behavior

* Icons mixed up or missing when returning from "Advanced Settings" or "Info"
* Last item switching between the original "Info" and "Info Screen" texts
* Code refactoring to reduce the constants increments / unneeded complexity
* Minor codestyle typos

### Steps to Reproduce

1. "Control" menu
2. Scroll to "Advanced Settings" and enter
3. Select "Back"
4. Scroll to "Info" and enter
5. Select "Back"

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Creality Ender 3 V2

### Electronics

Creality v4.2.2

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by thinkyhead** [comment]
Thanks for the patch!
