### ISSUE TITLE
[BUG] (Error compiling SKR PRO 1.2 + TMC2208)

### ISSUE THREAD

**Issue by ElekKecskemeti** [MarlinFirmware/Marlin#21845]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I get this error when compiling:

Compiling .pio\build\BIGTREE_SKR_PRO\src\src\module\tool_change.cpp.o
In file included from Marlin\src\module\stepper\trinamic.h:35,
from Marlin\src\module\stepper\trinamic.cpp:32:
Marlin\src\module\stepper../../feature/tmc_util.h: In instantiation of 'TMCMarlin<TMC2208Stepper, AXIS_LETTER, DRIVER_ID, AXIS_ID>::TMCMarlin(uint16_t,
uint16_t, float, uint8_t) [with char AXIS_LETTER = 'X'; char DRIVER_ID = '0'; AxisEnum AXIS_ID = X_AXIS; uint16_t = short unsigned int; uint8_t = unsigned char]':
Marlin\src\module\stepper\trinamic.cpp:214:7: required from here
Marlin\src\module\stepper../../feature/tmc_util.h:166:32: error: no matching function for call to 'TMC2208Stepper(const uint16_t&, const uint16_t&, const float&)'
166 | TMC2208Stepper(RX, TX, RS)
| ^

I added platformIO.ini
lib_deps =
https://github.com/bigtreetech/TMCStepper

### Version of Marlin Firmware

2.0.x debug

**Comment by ellensp** [comment]
"lib_deps = https://github.com/bigtreetech/TMCStepper" 
why did you do that?
Marlin already includes the correct library
Library Manager: Installing TMCStepper @ ~0.7.1 from https://github.com/teemuatlut/TMCStepper

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
