### ISSUE TITLE
BlTouch+ LCD 12864 + ANET A8

### ISSUE THREAD

**Issue by sroselli** [MarlinFirmware/Marlin#21869]
Good morning,
on my ANET A8 I regularly installed Bltouch with Marlin 1.1.9 and original display but a few weeks ago the display died and I have to replace it with 12864.
Apart from the inversion of the two flats as widely recommended, the PIN of the Bltouch undergoes displacements / modifications or remains in the same point, I believe it is the PIN 7 of the Display.

**Comment by XDA-Bam** [comment]
@sroselli Hi. I'm sorry, but I don't understand what this is about. Is this a question? Or do you want to report a bug? If this is a question, please close this issue and check out the Marlin Discord channel or other [sources of support](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/README.md). If this is about a bug in Marlin 1.1.9, please also close this issue and switch to a current release like 2.0.8. Version 1.1.9 is deprecated and not in development anymore. If your are already using Marlin 2.0.8, please check the bugfix-2.0.x branch and test if your problem persists when using that.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by sroselli** [comment]
My problem indipedente from Marlin version is .... connect a control cable from LCD Display 12864 to Bltouch on Anet A8 because I change a original old Anet a8 display.
