### ISSUE TITLE
[BUG] Menu navigation - wrong behaviour?

### ISSUE THREAD

**Issue by davidtgbe** [MarlinFirmware/Marlin#21861]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Wrong behaviour navigating through menu.

https://streamable.com/aezxag

### Expected behavior

Going to configuration menu and back to menu should take you back to the status screen

### Actual behavior

Going to configuration menu and, quickly touching back icon, takes you to the "Z move" menu instead to the status screen

### Steps to Reproduce

1. Press configuration icon on status screen
2. Quickly, press back icon

### Version of Marlin Firmware

Latest bugfix

### Printer model

ET4

### Electronics

STM32F407 + TOUCH TFT 2.8 FSMC

**Comment by ellensp** [comment]
Do you have DOUBLECLICK_FOR_Z_BABYSTEPPING enabled?

**Comment by davidtgbe** [comment]
Yes. It is enabled.

**Comment by ellensp** [comment]
And if you disable DOUBLECLICK_FOR_Z_BABYSTEPPING ?

**Comment by davidtgbe** [comment]
With DOUBLECLICK_FOR_Z_BABYSTEPPING disabled works fine.  I have just realized, reading code comments, that maybe, this is the intended behaviour with touch screen TFTs. I thought that, double clicking as a shortcut for babysteps had to be executed from status screen, not as a combination of going to config and back to status screen within a small time interval. 

https://github.com/MarlinFirmware/Marlin/blob/4a7f5603de04f89aeb47cd68803b810517136acf/Marlin/src/lcd/menu/menu.cpp#L185

**Comment by rhapsodyv** [comment]
Yes, it's the intended behaviour. Currently, color ui doesn't handle double touch. So, this is the way the dev created to mimic the 12864 LCD with encoder. In fact, old lcd and color ui have the very same behaviour.

To mitigate it, we can have a config to increase/decrease the interval? Or add full support for double click on color ui... Anyway, this is not a bug, but a feature! :-)

**Comment by davidtgbe** [comment]
Understood.
My first impression was that it was a bug. It is not a very intuitive behaviour IMHO. It wasn't until I read the comments in code that I realised it was the DOUBLECLICK_FOR_Z_BABYSTEPPING default behaviour I had been looking for so long  xD.
