### ISSUE TITLE
[BUG] Touch calibration usually skips first point

### ISSUE THREAD

**Issue by davidtgbe** [MarlinFirmware/Marlin#21860]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Touch screen calibration usually skips first corner reported from many users.

https://discord.com/channels/461605380783472640/491105274464043026/797560057625051146

https://streamable.com/a2gf1a

### Bug Timeline

At least from 9/1/2021

### Expected behavior

Maybe, the calibration process should wait a moment or watch for a touch release before starting to adquire the first corner coordinates

### Actual behavior

I suppose it takes the coordinates of the long pressed point, intended to launch the calibration process, resulting in a failed calibration process.

### Steps to Reproduce

Just start calibration process by pressing touch screen 2 seconds.

### Version of Marlin Firmware

Latest bugfix

### Printer model

ET4

### Electronics

STM32F407 + TOUCH TFT 2.8 FSMC

**Comment by shitcreek** [comment]
These touch screens are really sensitive. Please check that it isn't pinched in that corner. You may have to unscrew it.

**Comment by davidtgbe** [comment]
Thanks for the answer. 
It is not pinched. If I launch calibration through M995, it works OK. 
I think the problem is that the long click is not beng distinguished from the calibration first corner point.
It is not an isolate case, It is happening to many users from some time ago.

**Comment by rhapsodyv** [comment]
I never used the "hold for x seconds to start touch calibration"... I will take a look, but it seems it's buggy.

**Comment by manotroll** [comment]
M995
with this command ae I can calibrate?
mine and et5x

**Comment by thisiskeithb** [comment]
The linked commit from @larik008 (https://github.com/larik008/Marlin/commit/acb5c6a032bfcd012d3bf8cf5ff9b6c462476c5c) that references this issue seems to do the trick:

```diff
diff --git a/Marlin/src/lcd/tft_io/touch_calibration.cpp b/Marlin/src/lcd/tft_io/touch_calibration.cpp
index 44ebc73d71a2..9195141ffc6c 100644
--- a/Marlin/src/lcd/tft_io/touch_calibration.cpp
+++ b/Marlin/src/lcd/tft_io/touch_calibration.cpp
@@ -92,6 +92,13 @@ void TouchCalibration::validate_calibration() {
 bool TouchCalibration::handleTouch(uint16_t x, uint16_t y) {
   static millis_t next_button_update_ms = 0;
   const millis_t now = millis();
+  
+  // handle start calibration long press to avoid registering touch point as top-left corner calibration point
+  if (next_button_update_ms == 0) {
+    next_button_update_ms = now + BUTTON_DELAY_MENU;
+    return true;
+  }
+  
   if (PENDING(now, next_button_update_ms)) return false;
   next_button_update_ms = now + BUTTON_DELAY_MENU;
```

I've opened https://github.com/MarlinFirmware/Marlin/pull/25298 with the fix.
