### ISSUE TITLE
MKS Robin Pro with a MKS Robin TFT35 will not compile with color ui or lvgl ui selected

### ISSUE THREAD

**Issue by rclarke250** [MarlinFirmware/Marlin#21875]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I set the environment in PlatformIO to mks_robin_pro. I copy the latest configuration.h example for the mks pro from bugfix to the Marlin folder. Open folder in vscode/platformIO.  set the tft to Robin_tft35. set UI to either Color or lvgl and it will not compile. no other changes have been made.

### Bug Timeline

it reacted the same way in 2.07, but it was a new printer, and 2.08 came out days after I got it.

### Expected behavior

I expected it to compile with either of the chosen UI, it will compile if you choose the tft_classical.

### Actual behavior

I got an error compiling saying pins weren't defined for this scope. Compiling .pio\build\mks_robin_pro\src\src\HAL\shared\servo.cpp.o
Marlin\src\HAL\STM32F1\tft\tft_fsmc.cpp: In static member function 'static void TFT_FSMC::Init()':
Marlin\src\HAL\STM32F1\tft\tft_fsmc.cpp:89:16: error: 'FSMC_CS_PIN' was not declared in this scope
   uint8_t cs = FSMC_CS_PIN, rs = FSMC_RS_PIN;
                ^~~~~~~~~~~
Marlin\src\HAL\STM32F1\tft\tft_fsmc.cpp:89:16: note: suggested alternative: 'FSMC_CS_NE4'
   uint8_t cs = FSMC_CS_PIN, rs = FSMC_RS_PIN;
                ^~~~~~~~~~~
                FSMC_CS_NE4
Marlin\src\HAL\STM32F1\tft\tft_fsmc.cpp:115:11: error: 'rs' was not declared in this scope
   switch (rs) {
           ^~
Marlin\src\HAL\STM32F1\tft\tft_fsmc.cpp:115:11: note: suggested alternative: 'cs'
   switch (rs) {
           ^~
           cs
Marlin\src\HAL\STM32F1\tft\tft_fsmc.cpp:172:25: error: 'rs' was not declared in this scope
   gpio_set_mode(PIN_MAP[rs].gpio_device, PIN_MAP[rs].gpio_bit, GPIO_AF_OUTPUT_PP);  //FSMC_RS_Ax
                         ^~
Marlin\src\HAL\STM32F1\tft\tft_fsmc.cpp:172:25: note: suggested alternative: 'cs'
   gpio_set_mode(PIN_MAP[rs].gpio_device, PIN_MAP[rs].gpio_bit, GPIO_AF_OUTPUT_PP);  //FSMC_RS_Ax
                         ^~
                         cs

### Steps to Reproduce

1. Download latest bugfix or 2.08. expand
2. Download the latest configuration files. expand
3. Copy the configuration for the mks_robin_pro to Marlin
4. open VSCode and PlatformIO
5. In PlatformIO open folder and select Marlin folder.
6. Change environment for PlatformIO to mks_robin_pro. save file
7. Change configuration.h change from generic_tft to robin_tft35. Choose either color_ui or lvgl_ui and save file.
8. attempt compile

### Version of Marlin Firmware

2.08

### Printer model

JGMaker Artist-D Pro

### Electronics

stock. mks_robin_pro with mks_robin_tft35, tmc2209_standalone

### Add-ons

none

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

### Additional information & file uploads

[MarlinConfig.zip](https://github.com/MarlinFirmware/Marlin/files/6462530/MarlinConfig.zip)

**Comment by rhapsodyv** [comment]
I just sent a fix: #21879.

I added some missing TFT configs too.

**Comment by rclarke250** [comment]
Thank you.
