### ISSUE TITLE
[BUG] (M112 not compiling)

### ISSUE THREAD

**Issue by charlespick** [MarlinFirmware/Marlin#21874]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

It appears as if recent changes to the macros has broken the M112 TMC debugging functionality

### Bug Timeline

Commit 390878e adds this problem, reverting to 398ce22 fixes it

### Expected behavior

I expect Marlin to compile

### Actual behavior

```
In file included from Marlin/src/gcode/feature/trinamic/../../../inc/MarlinConfigPre.h:37,
                 from Marlin/src/gcode/feature/trinamic/../../../inc/MarlinConfig.h:28,
                 from Marlin/src/gcode/feature/trinamic/M122.cpp:23:
Marlin/src/gcode/feature/trinamic/M122.cpp: In static member function 'static void GcodeSuite::M122()':
Marlin/src/gcode/feature/trinamic/../../../inc/../core/macros.h:291:25: error: 'LIST_NUM_AXIS' was not declared in this scope
  291 | #define _LIST_N(N,V...) LIST_##N(V)
      |                         ^~~~~
Marlin/src/gcode/feature/trinamic/../../../inc/../core/macros.h:293:23: note: in expansion of macro '_LIST_N'
  293 | #define LIST_N_1(N,K) _LIST_N(N,K,K,K,K,K,K,K,K,K,K,K,K,K,K,K,K)
      |                       ^~~~~~~
Marlin/src/gcode/feature/trinamic/../../../inc/../core/macros.h:295:27: note: in expansion of macro 'LIST_N_1'
  295 | #define ARRAY_N_1(N,K)  { LIST_N_1(N,K) }
      |                           ^~~~~~~~
Marlin/src/gcode/feature/trinamic/M122.cpp:35:28: note: in expansion of macro 'ARRAY_N_1'
   35 |   xyze_bool_t print_axis = ARRAY_N_1(NUM_AXIS, false);
      |                            ^~~~~~~~~
Compiling .pio/build/BIGTREE_SKR_PRO/src/src/gcode/host/M118.cpp.o
*** [.pio/build/BIGTREE_SKR_PRO/src/src/gcode/feature/trinamic/M122.cpp.o] Error 1

```
### Steps to Reproduce

Load configurations for an IDEX SKR Pro with TMC2209s on a commit later than or even with 39087e, build, and watch the errors come up

### Version of Marlin Firmware

Doesn't build

### Electronics

SKR Pro V1.2

### Additional information & file uploads

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/6462132/Configurations.zip)

**Comment by thisiskeithb** [comment]
Replace the following:
https://github.com/MarlinFirmware/Marlin/blob/0c8a53e507fa792b114a89fe6902f4efe4ed2fe8/Marlin/src/gcode/feature/trinamic/M122.cpp#L35

With:
```cpp
xyze_bool_t print_axis = ARRAY_N_1(XYZE, false);
```

h/t to @rhapsodyv for finding the fix.

**Comment by ellensp** [comment]
fix has been merged.
