### ISSUE TITLE
[BUG] Marlin doesn't compile with Multi Volume option enabled

### ISSUE THREAD

**Issue by mrv96** [MarlinFirmware/Marlin#21872]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin is not able to compile if MULTI_VOLUME is defined.

The reported error is:
``` c
#error "DEFAULT_SHARED_VOLUME must be either SD_ONBOARD or USB_FLASH_DRIVE."
```

I used the same configuration setup suggested in the official PR: https://github.com/MarlinFirmware/Marlin/pull/21344#issue-592422964

I solved the issue using two slightly different defines:
``` c
#define DEFAULT_VOLUME SV_SD_ONBOARD
#define DEFAULT_SHARED_VOLUME SV_SD_ONBOARD
```

If this is the correct way to fix the compilation error maybe the Configuration_adv.h file should be updated.

### Expected behavior

No compilation Errors

### Version of Marlin Firmware

2.0.8

**Comment by rhapsodyv** [comment]
You are right. The names were updated, but not the message neither the default config options.

**Comment by shitcreek** [comment]
thanks.
