### ISSUE TITLE
[BUG] Creality Ender 3 v2 can not display Chinese language correctly

### ISSUE THREAD

**Issue by kirk33** [MarlinFirmware/Marlin#21871]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Each time when I turn on my Ender 3 v2. The menu is mess if I set language to Chinese before. English language is no problem. If I want it display correctly, I need to set language to English, then set back to Chinese. It will display correctly. But if I turn off my printer then on again, it is the same.

### Bug Timeline

New bug, from Marlin v2.0.8

### Steps to Reproduce

When I turn on my printer, if it is English language setting, it is all OK.
Then I set it to Chinese language, turn off my printer.
When I turn on my printer again, menu display not correctly.
I need to set back to English first, then set to Chinese. It is OK again.
If I restart my printer, problem still the same.

### Version of Marlin Firmware

Marlin v2.0.8

### Printer model

Creality Ender 3 v2

### Additional information & file uploads

![IMG_20210511_030642](https://user-images.githubusercontent.com/84021852/117817788-88841f80-b29a-11eb-9b17-781c1e1e4dca.jpg)

**Comment by shitcreek** [comment]
Please fill out the template and provide your configs.
Check if your EEPROM is enabled. Also this is might not a Marlin bug since the Ender 3 v2 screen has its own firmware.
