### ISSUE TITLE
[FR] Monoprice MP10 / Malyan MA 10

### ISSUE THREAD

**Issue by jipp** [MarlinFirmware/Marlin#21895]
### Is your feature request related to a problem? Please describe.

HI

I'm looking for the correct settings for the above printers. So far I found only small hints, like the printer use STM32 Cortex M4 processors.

Are the printers above supported by Marlin 2.x?

any help/tips appreciated.

thanks

### Are you looking for hardware support?

Monoprice MP10 / Malyan MA 10

### Describe the feature you want

looking for the config/board settings for the above printer

**Comment by thisiskeithb** [comment]
Do you have pictures of the motherboard & LCD/TFT screen?

**Comment by ellensp** [comment]
A bit of googling shows
display and ESP control board - https://www.monoprice.com/product?p_id=39107
Stepper heater board - https://www.monoprice.com/product?p_id=39106

The main controller chip is under that capacitor, rather unreadable.

**Comment by jipp** [comment]
From What I found by googleing:

Monoprice MP 10 mini is same like Malyan MA10 mini.

someone unpacked his printer:
https://www.reddit.com/r/3Dprinting/comments/dqu8fb/please_help_me_identify_my_3d_printer_mainboard/

so the board should be a ARM Cortex M4 STM32F401RBT6

would this help?

**Comment by thisiskeithb** [comment]
> so the board should be a ARM Cortex M4 STM32F401RBT6
> 
> would this help?

It does.

I can't find any existing board or MCU support in Marlin currently.

**Comment by ellensp** [comment]
Basically nothing is known about this board or the LCD, or the protocol between the two.
This would need serious effort to firstly document all the pins on the controller, then reverse engineer the protocol the LCD side uses. 
Has this been done?. No
Can it be done?  Given time with someone who has this machine and the interest and capabilities, probably, but not any time soon.

**Comment by jipp** [comment]
Hi

thx a lot for the fast answer. Saved me a lot of time for investigations.

all the best and stay healthy
