### ISSUE TITLE
Accidental presses

### ISSUE THREAD

**Issue by LazyDev-2017** [MarlinFirmware/Marlin#2189]
I am using a full graphic LCD (20X4 I think), and the problem has done the same on my Ramps 1.4 and Rumba. During a print, a single press of the encoder would momenterally goto the menu, then go back to the print screen. Many times I've accidentally changed the print speeds.

Been careful is a temporary fix, but not pratical.

**Comment by ntoff** [comment]
Yeah latest dev version sometimes I have to press the button 5 times before the menu will show up and other times it shows up on the first press.

**Comment by clefranc** [comment]
@LazyPrinter It happens too often to be ignored, perhaps an option to disable adjustment of the feedrate while in the main screen. After all, there is already a menu to access feedrate (and other option) while printing.

@ntoff  I saw this strange behavior too...

**Comment by ntoff** [comment]
The feed rate doesn't adjust until a certain amount of "dead zone" has passed, at least for me anyway. I have to turn my encoder quite a few times while on that main screen before the feed rate will move.

@clefranc Do you see it happen more if you are deep within the menu system and just let it sit idle and return to the main menu on its own?

**Comment by boelle** [comment]
if any of you can do code to fix this then please submit a PR....

**Comment by thinkyhead** [comment]
@boelle I'll debug this pretty soon. I had it working really well at one point, but it got broken later.

**Comment by shampine1** [comment]
I'm seeing this on my Panelolu2 also; it takes 10+ presses to get to the menu.  I couldn't tell if it is momentarily flashing back and forth, though.

**Comment by thinkyhead** [comment]
Definitely aiming to debug this multiple-click issue tonight, once I get through reading all these notifications…

**Comment by shampine1** [comment]
Any progress on this one?  Is there anything I can do to help?  Its driving me crazy!

**Comment by thinkyhead** [comment]
@shampine1 Testing with the latest code I didn't run into any points where clicks were giving me issues, but I haven't run through a full session, homing and printing, yet. I'll continue to watch for debug output on my next full test and if ignored clicks start to occur again I should have a better idea where the problem lies.

**Comment by shampine1** [comment]
Scott,
That’s the post 2513 version?  I’ll try it tonight!  Thanks!!

**Comment by shampine1** [comment]
Scott,  I don't see anything different on 2513; it still ignores button pushes.  When you press the button and the printer is NOT printing, it flashes "y." momentarily.  If you push and turn at the same time it goes into the menu most of the time.

**Comment by thinkyhead** [comment]
@shampine1 If the screen is showing "y" that's rather weird. Make sure all the connectors between your board and your controller are super-tight.

**Comment by shampine1** [comment]
@thinkyhead The "y." flashes for a VERY short time after the press; under 1/10 second.  Its like the first menu option gets selected immediately.  Yes, all the connectors are fully plugged in.  All three printers (running Printrboard Rev D and Panelolu 2) exhibit the same symptom, which is why I suspect firmware.  If I turn and push then it usually goes to the menu (and usually a few items down the list).

**Comment by thinkyhead** [comment]
> Panelolu

Hmm, maybe this is a Panelolu thing… I will keep messing around with my controller anyway (the G3D panel).

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
