### ISSUE TITLE
[BUG] Marlin 2.0.8 compile error for Creality Ender-3: Build environment 'sanguino1284p' is incompatible with BOARD_MELZI_CREALITY

### ISSUE THREAD

**Issue by StephanReich** [MarlinFirmware/Marlin#21906]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Compile of Marlin 2.0.8 with Visual Studio Code 1.56.2 (Windows 10) and PlatformiIO Core 5.1.1 failed with error:
Error: Build environment 'sanguino1284p' is incompatible with BOARD_MELZI_CREALITY
![VSCode marlin 2 0 8](https://user-images.githubusercontent.com/47822424/118281116-2ceda800-b4cd-11eb-8c47-d4c58ef7df1a.png)

### Bug Timeline

Failed with 2.0.8. Compile works with 2.0.7

### Steps to Reproduce

1. Load Marlin 2.0.8
2. Load the four configuration files from 
Configurations-release-2.0.8.zip\Configurations-release-2.0.8\config\examples\Creality\Ender-3\CrealityV422
3. Compile using PlatformIO environment sanguino1284p
4. Also the default melzi is not working
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6479220/configuration.zip)
[platformio.zip](https://github.com/MarlinFirmware/Marlin/files/6479223/platformio.zip)

### Version of Marlin Firmware

2.0.8

### Printer model

Creality Ender 3

**Comment by ellensp** [comment]
Not an error
the bootloaders are different, resulting code is not size optimised.
use one of the build environment listed

**Comment by StephanReich** [comment]
Hi ellensp,

thanks fpr your answer.
But as I wrote in point 4 - also all four melzi environments are not working.
Do you have any idea?
![VSCode marlin 2 0 8_2png](https://user-images.githubusercontent.com/47822424/118293685-32052400-b4da-11eb-9f5c-61682d5b2526.png)
