### ISSUE TITLE
[BUG] EEPROM_CHITCHAT No Feedback?

### ISSUE THREAD

**Issue by izzymoren0** [MarlinFirmware/Marlin#21929]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

No real big problem, maybe a small bug?

I've found out that my printers with current marlins don't give Feedback, as example, on a simple M500. It just writes an "ok".

Normally, if i remember correctly, it will write something like "EEPROM saved (xxx bytes)".

ofcourse EEPROM_CHITCHAT is activated in firmware.

Send:18:34:41.770: N17 M500
Recv:18:34:42.157: ok N17 P31 B3
Recv:18:34:46.155: wait (4)
Send:18:34:46.212: N18 M500
Recv:18:34:46.598: ok N18 P31 B3
Recv:18:34:47.597: wait

### Expected behavior

EEPROM_CHITCHAT should confirm eeprom changes with a message with saved bytes etc.

### Actual behavior

EEPROM_CHITCHAT only writes in console.

### Steps to Reproduce

M500

### Version of Marlin Firmware

newest bugfix

### Printer model

sv01

### Electronics

skr mini e3 2.0

### Your Slicer

Prusa Slicer

### Host Software

Repetier Host

**Comment by viper93458** [comment]
I’ve noticed that too for a while using octoprint. I thought it was just something in my config. :)

**Comment by ellensp** [comment]
This PR fixes it

**Comment by ellensp** [comment]
Merged, closing
