### ISSUE TITLE
[BUG] mks_robin_nano35_stm32 not generating Robin_nano35.bin

### ISSUE THREAD

**Issue by th0m4sek** [MarlinFirmware/Marlin#21928]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

compilation finishes without problems but there is no Robin_nano35.bin in build catalog

### Version of Marlin Firmware

bugfix-2.0.x

**Comment by ellensp** [comment]
buildroot/share/PlatformIO/scripts/mks_encrypt.py is saving the file as build.firmware, vs  using board_build.firmware = Robin_nano35.bin

**Comment by ellensp** [comment]
In buildroot/share/PlatformIO/scripts/mks_encrypt.py  line 20 
change	`marlin.encrypt_mks(source, target, env, "build.firmware")`
to		`marlin.encrypt_mks(source, target, env, board.get("build.firmware"))`

this works, but its 3am so ill have to do a PR later
