### ISSUE TITLE
STM32F103RC_btt vs STM32F103RC_btt_stm32

### ISSUE THREAD

**Issue by jerryfudd** [MarlinFirmware/Marlin#21935]
### Describe the feature you want

More of a question, building Marlin 2.0.8.1 it now has the option of STM32F103RC_btt_stm32 how does this differ from STM32F103RC_btt that I've used on prior versions of Marlin? ...building for an SKR Mini 2.0.

**Comment by ellensp** [comment]
Has been answered on discord.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
