### ISSUE TITLE
Compile error: U8glib.h: no such file or folder

### ISSUE THREAD

**Issue by JozsefKatus** [MarlinFirmware/Marlin#21941]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When I download the 2.0.8.1 (same situation with 2.0.8) and I compile it without any changes, than works fine. But if I set (even only) in the LCD-section:
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
I get this error message:
Z:\nyomtato upgrade\Firmware\RAMPS\Marlin-2.0.8.1\Marlin\src\HAL\AVR\u8g_com_HAL_AVR_sw_spi.cpp:65:10: fatal error: U8glib.h: No such file or directory
 #include <U8glib.h>
          ^~~~~~~~~~
compilation terminated.
exit status 1
Fehler beim Kompilieren für das Board Arduino Mega or Mega 2560. (Error compiling...)
I tried followings: 
-PlatformIO (same behavior)
-Update: Python, ArduinoIDE, VSCode, PlatformIO
-Under Win7, Win10 

### Bug Timeline

New issue, started with 2.0.8

### Expected behavior

Successful compile :)

### Actual behavior

See description.

### Steps to Reproduce

1. Download Marlin 2.0.8.x
2. set #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
3. Compile/Upload

### Version of Marlin Firmware

2.0.8.1

### Printer model

i3-like custom

### Electronics

Stock Mega2560 w. RAMPS 1.6

### Your Slicer

Slic3r

### Host Software

Repetier Host

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by ellensp** [comment]
I get no such error. Under platformio when enabling REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
I suspect there is an issue with your platfomio.  In your home directory delete .platformio folder. This  forces it to re download build environments and libraries

**Comment by JozsefKatus** [comment]
The first configs are the real files for the printer. The second are the test files wit only this setting
[Marlin2.8.0config.zip](https://github.com/MarlinFirmware/Marlin/files/6499263/Marlin2.8.0config.zip)
[Marlin8.0.8.1_test_config.zip](https://github.com/MarlinFirmware/Marlin/files/6499272/Marlin8.0.8.1_test_config.zip)

**Comment by ellensp** [comment]
also remove .pio folder in marlin and try again

**Comment by ellensp** [comment]
Your test config compiles fine.

**Comment by JozsefKatus** [comment]
I didn´t find any folder with the names: .platformio (in Home) or .pio (in Marlin). Maybe it is a similar user mistake, I´m not really familiar with PlatformIO.
I tried on another computer: fresh installed Win10 and anything other. Now I get another error message, see attachment. The same with ArduinoIDE.
Many thanks! 
[Arduino_error.txt.txt](https://github.com/MarlinFirmware/Marlin/files/6499566/Arduino_error.txt.txt)
![PlatformIO](https://user-images.githubusercontent.com/65675326/118617442-eea10300-b7c2-11eb-8440-9a447ff98262.jpg)

**Comment by ellensp** [comment]
. directories are hidden directories
you need to tell the os to display them to you

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
