### ISSUE TITLE
Azteeg X5 GT with Viki2 LCD TMC Connection Error

### ISSUE THREAD

**Issue by blackcatSVK** [MarlinFirmware/Marlin#21966]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi, I'm using Azteeg X5 GT control board with Viki2 LCD, I have an issue with the marlin firmware.

When I undefined //#define VIKI2 line 2001, everything works smoothly, I use octoprint to connect to the printer and its working perfectly.

However, when I define line 2001 above, the LCD works, scrolling, I can used normal function as expected. However, I got "TMC connection error" and the motors do not work at all.

And I did tried to disconnect the LCD (line 2001 is still defined), and same issue happens.

I have tried Google to find the answer but its not much helped.

Do you guys have any suggestion to fix the issue?

Thank you.

### Bug Timeline

20/04/2021

### Expected behavior

I expect the motor working

### Actual behavior

TMC Connection error

### Version of Marlin Firmware

2.0.7.2

### Printer model

Custom CoreXY

### Electronics

Azteeg X5 GT Board, Viki2 LCD

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by ellensp** [comment]
What type of stepper drivers do you have, as it tells us is if is using SPI or serial to talks to them.
Please attach your configuration files, as this answers most questions.

**Comment by blackcatSVK** [comment]
I'm using TMC2660, these are my config files.

[Config.docx](https://github.com/MarlinFirmware/Marlin/files/6527735/Config.docx)
[Config_adv.docx](https://github.com/MarlinFirmware/Marlin/files/6527736/Config_adv.docx)

I did use SPI control in both half speed, eight speed, both didn't solve the issue.
Thank you

**Comment by ellensp** [comment]
I cannot read a docx. propitiatory Microsoft only format.
Please just zip up configs files and attach

**Comment by ellensp** [comment]
Also when lcd is active please send the printer A M122,  ie TMC Debugging 
This will tell us what drivers in particular or all are effected.

**Comment by ellensp** [comment]
Looking around I see many with this issue https://reprap.org/forum/read.php?13,863090 
and https://github.com/MarlinFirmware/Marlin/issues/17111  no solutions

**Comment by ellensp** [comment]
Do you have TMC_USE_SW_SPI enabled in Configuration_adv.h

**Comment by blackcatSVK** [comment]
Hi, this is the zip file of two configs.

M112 reporting "connection error, low voltage" on all X, Y, Z and E.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/6527898/Marlin.zip)

**Comment by blackcatSVK** [comment]
just another report that if I define Viki2 to use the LCD in marlin, I couldn't connect the printer to octoprint either, I need to revert it with two slashes (sorry English is not my native language so sometime I'm confused whether I should use "comment" or "uncomment" here lol) it if I would like to use octoprint.

**Comment by blackcatSVK** [comment]
Hi, please any help

**Comment by blackcatSVK** [comment]
> Do you have TMC_USE_SW_SPI enabled in Configuration_adv.h

yes I did, nothing improved.

**Comment by blackcatSVK** [comment]
anyone could help, please I'm so desperate about my machine.
