### ISSUE TITLE
[BUG] BTT_GTR_V1_0 should define E2END 0x1FFF to prevent EEPROM version conflict 

### ISSUE THREAD

**Issue by DerAndere1** [MarlinFirmware/Marlin#21977]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I forward a bug report by @HendrikJan-5D. 
His setup: 
BOARD_BTT_GTR_V1_0
He says that he got EEPROM version conflicts with Marlin when he did not change file pins_BTT_GTR_V1_0.h line 36 to
```
#ifdef E2END
  #undef E2END
#endif
#define E2END 0x1FFF // EEPRO end adress 24C64 ( 64Kb = 8KB )
``` 

I will close this bug report in 7 days if no user with BTT_GTR_V1.0. can report an exact error message related to the EEPROM and attach his non-working configuration files.

### Bug Timeline

Since https://github.com/MarlinFirmware/Marlin/commit/461647fcee5f9d519e0e54f809dbfb38bf573e59#diff-ac6b6ab7bbc7a9ab2320e6e6fbf00d6b7439a9ac5ba942d643920f7853a6000a

### Expected behavior

```
Have
#define E2END 0x1FFF
```
EEPROM works

### Actual behavior

E2END is not defined
--> EEPROM version conflict according to @HendrikJan-5D (please verify)

### Steps to Reproduce

See https://github.com/MarlinFirmware/Marlin/commit/461647fcee5f9d519e0e54f809dbfb38bf573e59#diff-ac6b6ab7bbc7a9ab2320e6e6fbf00d6b7439a9ac5ba942d643920f7853a6000a 

### Version of Marlin Firmware

Marlin bugfix-2.0.x as of https://github.com/MarlinFirmware/Marlin/commit/0d7075b90c225d2f88e1d790b2df4acbdfcfac8b

### Printer model

custom model with BOARD_BTT_GTR_V1_0

### Electronics

BOARD_BTT_GTR_V1_0

### Additional information & file uploads

To any user with BTT GTR V1.0 board, please download latest [Marlin bugfix-2.0.x](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x), compile with your configs and verify if there is an EEPROM version conflict. Report your results here and post your configs, thx.

**Comment by thisiskeithb** [comment]
I cannot reproduce this on a GTR 1.0 that I have here with the latest bugfix (though, this has worked fine for quite a while).

Make sure you send `M502` followed by `M500` to initialize your EEPROM after every firmware update.
