### ISSUE TITLE
SD_Init_Fail [BUG] (bug summary)

### ISSUE THREAD

**Issue by singla2602** [MarlinFirmware/Marlin#21976]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have Rerap_Discount_Smart_Controller.
SD card is not working with upadted 2.0.x and 2.0.bugfix firmware.
When I flash old firmware 1.0.x sd card works fine.

### Version of Marlin Firmware

2.0.x & 2.0.bugfix

### Printer model

Folgertech Prusa i3 clone

### Electronics

MKS V1.2

### Additional information & file uploads

SD_Init_Fail

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by tig33r** [comment]
//#define SD_DETECT_STATE HIGH in conf adv

**Comment by singla2602** [comment]
thank you problem solved

**Comment by tig33r** [comment]
this is related to https://github.com/MarlinFirmware/Configurations/issues/501
