### ISSUE TITLE
[FR] (feature summary)Display value in AUX leveling

### ISSUE THREAD

**Issue by gooddealonly** [MarlinFirmware/Marlin#21986]
### Is your feature request related to a problem? Please describe.

I use a Creality cr-10s pro V2.  It has BL touch leveling.  The AUX leveling button allows the user to manually level the printer bed.  The user can only make changes to the four corners using a sheet of paper or feeler gauge.  Then the user must go through a long 25 point measure to see the changes.

### Describe the feature you want

Once the AUX leveling button is pressed the printer should measure the four corners and display the values. I suggest displaying the numeric level value of the four corners to allow the user to make a change "live" watching the values.  Maybe add a measure button on the screen to "Measure" only the four corners.  This would make leveling the printer bed more accurate and faster.

**Comment by ellensp** [comment]
Marlin doesn't even have a configuration for this printer at all.
But the LCD looks like a smart LCD, ie it has its own firmware, not part of marlin.
Confirmed, its a DWIN type display. With its own firmware.
You need to contact Creality for this.
