### ISSUE TITLE
Extrusion problem while printing

### ISSUE THREAD

**Issue by singla2602** [MarlinFirmware/Marlin#21985]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

While I start the print, the extruder doesn't moves, but sometimes filament moves up and than down one step only. It doesn't feed the bowden (means that while printing the filament should come out continously but instead it comes out of extruder one step and moves back in extruder one step.
Extruder is calibrated and works in right direction. As extruder is moved in move axis menu, right amount of filament gets extruded. But, the problem is only while printing that extruder doesn't moves.

https://user-images.githubusercontent.com/82766428/119503689-ddd72b00-bd88-11eb-82c2-4ffee08522e2.mp4

### Bug Timeline

It's a new bug. I flashed firmware 2 days before

### Version of Marlin Firmware

2.0.8.1

### Printer model

Folgertech Prusa i3 clone

### Electronics

MKS V1.2

### Your Slicer

Slic3r

**Comment by Scope666** [comment]
Pretty sure this happened to me on 2.0.9.1 also.  I actually thought I had a clog, but flashing back to 2.0.7.2 fixed the issue for me.  Separately I was also having weird pauses with 2.0.9.1 using Octoprint.

SKR 1.4
