### ISSUE TITLE
M600 runout Sensor fail Procedere 

### ISSUE THREAD

**Issue by Jumbo125** [MarlinFirmware/Marlin#21984]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello
I use Marlin 2.0.7 and it works great for me, BUT
If my printer detect runout of filament, it do some confused steps.....
this is the procedere:

1. End of Filament, the filament detector check Runout.
2. The noozl go to park position
3. On the LCD display can i chosse "Heat noozle"
4. Then Load filament.
-----All functions work great
5. On the display are two options: Purge more filament or continue
6. I click on continue, cause the filament is already in the noozle.
7. (Now comes the Problem) The noozle goes from the par-position to the last print-position. BUT on the little way from the park-position to the "restart" point, the extruder extruded a little bit filament. This goes out of the noozle and will be stay on the way. 
8. continue the printing

Now my question: where can i define the little sequenze, from the park station-to-the-continue-point? I don't want any extrusion during this few seconds(during the drive from the park-position to the print object).
i use the Ender 3 Max

> /**

> 
>  * Advanced Pause
>  * Experimental feature for filament change support and for parking the nozzle when paused.
>  * Adds the GCode M600 for initiating filament change.
>  * If PARK_HEAD_ON_PAUSE enabled, adds the GCode M125 to pause printing and park the nozzle.
>  *
>  * Requires an LCD display.
>  * Requires NOZZLE_PARK_FEATURE.
>  * This feature is required for the default FILAMENT_RUNOUT_SCRIPT.
>  */
> #define ADVANCED_PAUSE_FEATURE
> #if ENABLED(ADVANCED_PAUSE_FEATURE)
>   #define PAUSE_PARK_RETRACT_FEEDRATE         60  // (mm/s) Initial retract feedrate.
>   #define PAUSE_PARK_RETRACT_LENGTH            2  // (mm) Initial retract.
>                                                   // This short retract is done immediately, before parking the nozzle.
>   #define FILAMENT_CHANGE_UNLOAD_FEEDRATE     20  // (mm/s) Unload filament feedrate. This can be pretty fast.
>   #define FILAMENT_CHANGE_UNLOAD_ACCEL        25  // (mm/s^2) Lower acceleration may allow a faster feedrate.
>   #define FILAMENT_CHANGE_UNLOAD_LENGTH      100  // (mm) The length of filament for a complete unload.
>                                                   //   For Bowden, the full length of the tube and nozzle.
>                                                   //   For direct drive, the full length of the nozzle.
>                                                   //   Set to 0 for manual unloading.
>   #define FILAMENT_CHANGE_SLOW_LOAD_FEEDRATE   6  // (mm/s) Slow move when starting load.
>   #define FILAMENT_CHANGE_SLOW_LOAD_LENGTH     0  // (mm) Slow length, to allow time to insert material.
>                                                   // 0 to disable start loading and skip to fast load only
>   #define FILAMENT_CHANGE_FAST_LOAD_FEEDRATE  20  // (mm/s) Load filament feedrate. This can be pretty fast.
>   #define FILAMENT_CHANGE_FAST_LOAD_ACCEL     25  // (mm/s^2) Lower acceleration may allow a faster feedrate.
>   #define FILAMENT_CHANGE_FAST_LOAD_LENGTH     0  // (mm) Load length of filament, from extruder gear to nozzle.
>                                                   //   For Bowden, the full length of the tube and nozzle.
>                                                   //   For direct drive, the full length of the nozzle.
>   //#define ADVANCED_PAUSE_CONTINUOUS_PURGE       // Purge continuously up to the purge length until interrupted.
>   #define ADVANCED_PAUSE_PURGE_FEEDRATE        3  // (mm/s) Extrude feedrate (after loading). Should be slower than load feedrate.
>   #define ADVANCED_PAUSE_PURGE_LENGTH         50  // (mm) Length to extrude after loading.
>                                                   //   Set to 0 for manual extrusion.
>                                                   //   Filament can be extruded repeatedly from the Filament Change menu
>                                                   //   until extrusion is consistent, and to purge old filament.
>   #define ADVANCED_PAUSE_RESUME_PRIME          2  // (mm) Extra distance to prime nozzle after returning from park.
>   //#define ADVANCED_PAUSE_FANS_PAUSE             // Turn off print-cooling fans while the machine is paused.
> 
>                                                   // Filament Unload does a Retract, Delay, and Purge first:
>   #define FILAMENT_UNLOAD_PURGE_RETRACT       13  // (mm) Unload initial retract length.
>   #define FILAMENT_UNLOAD_PURGE_DELAY       5000  // (ms) Delay for the filament to cool after retract.
>   #define FILAMENT_UNLOAD_PURGE_LENGTH         8  // (mm) An unretract is done, then this length is purged.
>   #define FILAMENT_UNLOAD_PURGE_FEEDRATE      25  // (mm/s) feedrate to purge before unload
> 
>   #define PAUSE_PARK_NOZZLE_TIMEOUT           60  // (seconds) Time limit before the nozzle is turned off for safety.
>   #define FILAMENT_CHANGE_ALERT_BEEPS         10  // Number of alert beeps to play when a response is needed.
>   #define PAUSE_PARK_NO_STEPPER_TIMEOUT           // Enable for XYZ steppers to stay powered on during filament change.
> 
>   #define PARK_HEAD_ON_PAUSE                    // Park the nozzle during pause and filament change.
>   //#define HOME_BEFORE_FILAMENT_CHANGE           // If needed, home before parking for filament change
> 
>   //#define FILAMENT_LOAD_UNLOAD_GCODES           // Add M701/M702 Load/Unload G-codes, plus Load/Unload in the LCD Prepare menu.
>   //#define FILAMENT_UNLOAD_ALL_EXTRUDERS         // Allow M702 to unload all extruders above a minimum target temp (as set by M302)
> #endif

 

### Expected behavior

Pass the m600 Code Part

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Creality Ender 3 Max

### Electronics

Board 4.2.7

### Your Slicer

Cura

### Host Software

Repetier Host

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
