### ISSUE TITLE
[FR] (feature summary)Change the Z-axis layout

### ISSUE THREAD

**Issue by gooddealonly** [MarlinFirmware/Marlin#21989]
### Is your feature request related to a problem? Please describe.

I use the Creality cr-10s Pro V2 printer.  There is an Adjustment button in the print function.  The Z-axis adjustment is horizontal instead of vertical.  This is confusing. Am I making the Z-axis sideways or up and down.

### Describe the feature you want

Please make the Z-axis adjustment pointing up and down. It would be less confusing.

**Comment by ellensp** [comment]
Marlin doesn't even have a configuration for this printer at all.  
But the LCD looks like a smart LCD, ie it has its own firmware, not part of marlin.
Confirmed, its a DWIN type display. With its own firmware. 
You need to contact Creality for this.
