### ISSUE TITLE
Extrusion problem while printing[BUG] (bug summary)

### ISSUE THREAD

**Issue by singla2602** [MarlinFirmware/Marlin#21983]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

While I start the print, the extruder doesn't moves, but sometimes filament moves up and than down one step only. It doesn't feed the bowden (means that while printing the filament should come out continously but instead it comes out of extruder one step and moves back in extruder one step.
 Extruder is calibrated and works in right direction. As extruder is moved in move axis menu, right amount of filament gets extruded. But, the problem is only while printing that extruder doesn't moves.

https://user-images.githubusercontent.com/82766428/119496783-78cc0700-bd81-11eb-8882-b7bfe53e0133.mp4

### Version of Marlin Firmware

2.0.8.1

### Printer model

Folgertech Prusa i3 clone

### Electronics

MKS V1.2

### Your Slicer

Prusa Slicer

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
