### ISSUE TITLE
[FR] (feature summary)Add 0.01 mm increment to the Z axis in changing Home position.

### ISSUE THREAD

**Issue by gooddealonly** [MarlinFirmware/Marlin#21988]
### Is your feature request related to a problem? Please describe.

I use the Creality cr-10S Pro V2 printer.  In the Print function, there is an Adjustment button.  which allows the user to make changes to the Z axis. (Z-axis compensation).  This compensation has a 0.01mm increment in the Leveling Home position. The increment is 0.1 minimum

### Describe the feature you want

Add a 0.01 mm increment to the Level Home adjustment.  As is the user can only adjust 0.1mm each time.  What if the user needs to make a 1,5 mm or 0.75 mm change?  1 mm is too tight and 2 mm is too loose. The print Adjustment already has the 0.01mm increment.

**Comment by ellensp** [comment]
Marlin doesn't even have a configuration for this printer at all.
But the LCD looks like a smart LCD, ie it has its own firmware, not part of marlin.
Confirmed, its a DWIN type display. With its own firmware.
You need to contact Creality for this.
