### ISSUE TITLE
[BUG] BLTouch fails to deploy during G29 (Potential UBL conflict/issue)

### ISSUE THREAD

**Issue by brianredbeard** [MarlinFirmware/Marlin#21994]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Somewhere between 22de37ad5037eb829de9e817f74d25768bd8e117 and 0d7075b90c225d2f88e1d790b2df4acbdfcfac8b probing with the BLtouch during `G29` operations has stopped occurring.  

Upon startup, the BLTouch unit itself successfully performs a power on self test.  Subsequently, the probe successfully deploys upon `G28` execution.  Execution of `G29` shows `BLTouch DEPLOY requested` but, as can be seen in the video, this operation does not occur.

### Bug Timeline

> 2.0.8.x

### Expected behavior

Proper deployment of probe

### Actual behavior

Probe deploys during `BLTouch DEPLOY requested`

### Version of Marlin Firmware

0d7075b90c225d2f88e1d790b2df4acbdfcfac8b

### Printer model

Ender 3 Pro

### Electronics

BTT E3 DIP, TMC5160

### Add-ons

BLTouch

### Host Software

OctoPrint

### Video of the problem:
https://user-images.githubusercontent.com/57542/120032839-a1d1df00-bfaf-11eb-9b1d-f2a76878bc90.mp4

Power on self test at ~ 0:03
`G28` begins at ~1:05
`G29 P1 T0 V2` begins at ~ 1:40

### Logfiles:
[serial.log](https://github.com/MarlinFirmware/Marlin/files/6562948/serial.log) 

### Configurations:
[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/6563149/Configurations.zip)

Output of `git diff -w -U0 0d7075b90c225d2f88e1d790b2df4acbdfcfac8b -- Marlin/Configuration{,_adv}.h`:
https://gist.github.com/brianredbeard/015a0c4f8cb4e8625ddb9b1d7b3a506b

**Comment by brianredbeard** [comment]
FYI, seems to be some interaction with UBL.

Re-building and swapping `AUTO_BED_LEVELING_UBL` for `AUTO_BED_LEVELING_BILINEAR` has the probe deploying on `G29`.

**Comment by ldursw** [comment]
It looks like the same issue as #21429 but the bad commit is not in the range you specified.

**Comment by GhostlyCrowd** [comment]
@brianredbeard  

Can you try building the latest bugfix and instead of using the default envs for your board use the STM32 HAL version of STM32F103RC_btt envs. 

`[env:STM32F103RC_stm32]
[env:STM32F103RC_btt_stm32]
[env:STM32F103RC_btt_512K_stm32]`

**Comment by brianredbeard** [comment]
FYI: I am still engaged on this, but waiting on the STM32 HAL switch-over to stabilize (i.e. #21999, #22019, #22022, etc) 

(This has been discussed in #dev-talk on Discord, but noted here for tracking purposes)
