### ISSUE TITLE
[BUG] (bug summary) Power off continuation function is not available in m605 image mode

### ISSUE THREAD

**Issue by cappuccino02** [MarlinFirmware/Marlin#22007]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

DUAL_ X_ Cariage.Power off continuation function is not available in m605 image mode

### Bug Timeline

Dunno. Probably a new bug.

### Expected behavior

Continue printing unfinished files

### Actual behavior

Print from the beginning, not continue to print unfinished files

### Version of Marlin Firmware

2.0.8.1

### Electronics

BIGTREETECH SKR PRO 1.2

### Your Slicer

Cura

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by cappuccino02** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarlinFirmware/Marlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月1日(星期二) 下午5:57
***@***.***&gt;;
抄送:&nbsp;"WEJIR   ENCJI   YA     ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarlinFirmware/Marlin] [BUG] (bug summary) Power off continuation function is not available in m605 image mode (#22007)





 
Please attach your configuration files.

**Comment by cappuccino02** [comment]
> ------------------ 原始邮件 ------------------- 发件人: "MarlinFirmware/Marlin " ***@***.***>; 发送时间： 2021年6月1日（星期二）下午5:57 ***@***.***>; 抄送: "WEJIR ENCJI YA ***@***.******@***.***>;主题: Re: [MarlinFirmware/Marlin] [BUG] (bug摘要) m605 图像模式下无法使用断电续传功能 ( #22007 ) 请附上您的配置文件。-您收到此消息是因为您创作了该线程。直接回复此电子邮件，在 GitHub 上查看，或取消订阅。

**Comment by cappuccino02** [comment]
[Uploading Marlin.ZIP…]()

**Comment by ellensp** [comment]
> Uploading Marlin.ZIP…

This just links to https://github.com/MarlinFirmware/Marlin/issues/22007
no actual config file.

**Comment by cappuccino02** [comment]
> > 正在上传 Marlin.ZIP...
> 
> 这只是链接到#22007
> 没有实际的配置文件。

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/6581682/Marlin.zip)
