### ISSUE TITLE
Sending M117 and no message results in commands showing up on the LCD

### ISSUE THREAD

**Issue by ntoff** [MarlinFirmware/Marlin#2200]
Semi recent dev version as of maybe a week ago I think, if you send M117 with no other input, whatever is currently happening will show up in the LCD, even when printing from SD.

eg. Sending M117 while printing just now had the x y z and e co-ordinates show up in the message area of the LCD.

**Comment by thinkyhead** [comment]
Oops! I will look into that. The optimized parser is probably failing to account for a possible carriage-return immediately following the code. Will patch soon!

**Comment by thinkyhead** [comment]
#2270 should fix this problem.
