### ISSUE TITLE
Why suddenly the stepper setting are different

### ISSUE THREAD

**Issue by arnold-b** [MarlinFirmware/Marlin#22013]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

before i used CONFIGURATION_H_VERSION 020000 
and my stepper settings have been 400,400,400,78 

now i´m using CONFIGURATION_H_VERSION 02000801

and the stepper moving 10 times more as before. 
did i miss something ?

### Version of Marlin Firmware

 02000801

### Printer model

selfmade

**Comment by ellensp** [comment]
Probabably becase you didnt reset the eeprom contents with M502 then M500.
Or you failed to update microstepping settings in Configuration_adv.h If they are software settable.

Regardless

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
