### ISSUE TITLE
[FR] #define probing_margin for each side of the bed

### ISSUE THREAD

**Issue by nazzarus** [MarlinFirmware/Marlin#22011]
### Is your feature request related to a problem? Please describe.

Unable to compile tramming wizard with current probe offset {0,-34.5,0} and probing margin {14.5} settings when attempting to position the probe directly over the screws with

`#define TRAMMING_POINT_XY { {  33, 67 }, { 272, 67 }, { 272, 305  }, { 33, 305 } }`

Results in error `Marlin\src\gcode\bedlevel\../../feature/tramming.h:36:36: error: static assertion failed: TRAMMING_POINT_XY point 2 is not reachable with the default NOZZLE_TO_PROBE offset and PROBING_MARGIN.
 #define VALIDATE_TRAMMING_POINT(N) static_assert(N >= G35_PROBE_COUNT || Probe::build_time::can_reach(screws_tilt_adjust_pos[N]), \`
 
 (the 14.5 margin is for the clips holding the bed on front and back)

### Describe the feature you want

#define PROBE_MARGIN

changed to

#define PROBE_MARGIN_X
#define PROBE_MARGIN_Y

or more optimally

#define PROBE_MARGIN_FRONT
#define PROBE_MARGIN_BACK
#define PROBE_MARGIN_LEFT
#define PROBE_MARGIN_RIGHT

**Comment by slowbro** [comment]
Pretty sure this already exists, in `Configuration_adv.h`:

```
/**
 * Probing Margins
 *
 * Override PROBING_MARGIN for each side of the build plate
 * Useful to get probe points to exact positions on targets or
 * to allow leveling to avoid plate clamps on only specific
 * sides of the bed. With NOZZLE_AS_PROBE negative values are
 * allowed, to permit probing outside the bed.
 *
 * If you are replacing the prior *_PROBE_BED_POSITION options,
 * LEFT and FRONT values in most cases will map directly over
 * RIGHT and REAR would be the inverse such as
 * (X/Y_BED_SIZE - RIGHT/BACK_PROBE_BED_POSITION)
 *
 * This will allow all positions to match at compilation, however
 * should the probe position be modified with M851XY then the
 * probe points will follow. This prevents any change from causing
 * the probe to be unable to reach any points.
 */
#if PROBE_SELECTED && !IS_KINEMATIC
  //#define PROBING_MARGIN_LEFT 0
  //#define PROBING_MARGIN_RIGHT 0
  //#define PROBING_MARGIN_FRONT 0
  //#define PROBING_MARGIN_BACK 0                                                                                                                                                                                                              
#endif
```

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
