### ISSUE TITLE
[BUG] Initial Homing does not work on X-axis and Z-axis

### ISSUE THREAD

**Issue by tmartin007** [MarlinFirmware/Marlin#22016]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Issuing G28X or G28Z initially moves the respective axis a short distance into the direction that is opposite to the defined home-position and stops.

In order for G28X to actually perform homing (after a power up), it alway has to be invoked exactly 3 times. - This is reliably reproducible.

In order for G28Z to actually perform homing (after a power up), it alway has to be invoked exactly 2 times. - This is reliably reproducible.

In order for G28Y to actually perform homing (after a power up), it alway has to be invoked exactly once. - This is reliably reproducible - and is expected and desired.

### Bug Timeline

A similar behavior was reported with issue #17128

### Expected behavior

1) In order for G28X to actually perform homing (after a power up), a single invocation of G28X should be sufficient.

2) In order for G28Z to actually perform homing (after a power up), a single invocation of G28Z should be sufficient.

### Actual behavior

Issuing G28X or G28Z initially moves the respective axis a short distance into the direction that is opposite to the defined home-position and stops.

### Steps to Reproduce

1) boot-up Marlin 2.0.8.2 on a BTT SKR Pro V1.1 with TMC2209 on all axis
2) issue G28X to home the x-axis
3) observe the x-axis to move away from the home-position for a small distance (maybe: HOMING_BACKOFF_POST_MM) 
4) issue another G28X to home the x-axis
5) again observe the x-axis to move away from the home-position for a small distance (maybe: HOMING_BACKOFF_POST_MM) 
6) issue yet another G28X to home the x-axis
7) observe the x-axis perform the homing procedure with HOMING_BACKOFF_POST_MM, when done

8) issue G28Z to home the z-axis
9) observe the z-axis to move away from the home-position for a small distance (maybe: HOMING_BACKOFF_POST_MM) 
10) issue another G28Z to home the z-axis
11) observe the z-axis perform the homing procedure with HOMING_BACKOFF_POST_MM, when done

### Version of Marlin Firmware

2.0.8.2

### Printer model

CNC 6040 mill

### Electronics

BTT SKR Pro V1.1, TMC 2209

### Add-ons

TMC 2209 on all axis

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6575446/Configuration.zip)

**Comment by ellensp** [comment]
What does M119 say?
as moving small disatnce in wrong direction is symtomatic of endstop already triggered. 
It trys to home, can't as it already triggered. backs off, attempts to rehome and can't as already triggered. net result moves away from home small distance.

**Comment by tmartin007** [comment]
Thanks for you quick response.
After power-up, M119 says:

`M119
Reporting endstop status
x_min: open
y_min: open
z_min: open
ok`

We have tried M914 I Z20 to reduce the TMC Bump Sensitivity without achieving any improvement. (However, a sensitivity of 20 is way too low, to even trigger a "STALL"). - BTW, "HOME_BUMP_MM" is set to "0" for all axis.

**Comment by ellensp** [comment]
May be related to https://github.com/MarlinFirmware/Marlin/issues/22012

**Comment by tmartin007** [comment]
According to #22012, homing Z works, which unfortunately, I cannot confirm.

**Comment by DerAndere1** [comment]
Have you sent M502 followed by M500 after uploading Marlin?

**Comment by tmartin007** [comment]
No, the machine is currently disassembled, I am intending to put it together again,
tomorrow and/or on Sunday and will test this immediately.

Thanks again!

**Comment by tmartin007** [comment]
Here too, thanks for the idea!

Unfortunately, this had no effect.

M502
echo:Hardcoded Default Settings Loaded
ok
M500
Error:EEPROM disabled
ok
