### ISSUE TITLE
[BUG] SWITCHING_EXTRUDER - fail servo switching

### ISSUE THREAD

**Issue by DrumClock** [MarlinFirmware/Marlin#22043]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When using this option :
```
// A dual extruder that uses a single stepper motor
#define SWITCHING_EXTRUDER
#if ENABLED(SWITCHING_EXTRUDER)
  #define WITH_NOZZLE  true    // one servo switches extruder and nozzles
  #define SWITCHING_EXTRUDER_SERVO_NR 1
  #define SWITCHING_EXTRUDER_SERVO_ANGLES { 45, 135, 45, 135 } // Angles for E0, E1[, E2, E3]
  #if EXTRUDERS > 3
    #define SWITCHING_EXTRUDER_E23_SERVO_NR 2
  #endif
#endif
```
After sending the command T0-T3 does not switch servo 1 and servo 2, the direction of rotation of the motor E0 / E1 is OK.
After sending the `M280 P1` or `P2` command, both servos work fine.

Additionally, `DISABLE_INACTIVE_EXTRUDER` must be disabled because after a short time the E1 motor (for T2 and T3) turns off.

### Version of Marlin Firmware

bugfix-2.0.x  (ze dne 4.6.2021)

### Printer model

special:  4x hotend +  2x motor extruderu

### Electronics

MKS Rumba32 

### Additional information & file uploads

[rumba32rew.zip](https://github.com/MarlinFirmware/Marlin/files/6596295/rumba32rew.zip)

**Comment by DrumClock** [comment]
Ahoj,
ani dnešní update bugfix 2.0 (7.6.2021) neřeší chybu ovládání serva při použití funkce `SWITCHING_EXTRUDER`
Krokový motor funguje správně ale servo se při použití příkazu Tx vůbec nepohybuje.

Při použití M280 Px ......serva pracují dle očekávání.

**Comment by thinkyhead** [comment]
Let's collect more data.

- Download Marlin `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_TOOL_CHANGE` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Do some of the commands that exhibited problems. Take notes.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.

**Comment by DrumClock** [comment]
info test: [test_9.6.21.txt](https://github.com/MarlinFirmware/Marlin/files/6621385/test_9.6.21.txt)
a s [M111 S247.txt](https://github.com/MarlinFirmware/Marlin/files/6621483/M111.S247.txt)

Mám ještě něco vyzkoušet ? 
Nebo poslat video ?

**Comment by DrumClock** [comment]
Hi @thinkyhead  21 days ago I reported a bug to Github https://github.com/MarlinFirmware/Marlin/issues/22043
Today's update of bugfix2.0x did not fix anything.
Can someone please look at it and fix it?
The SWITCHIN_EXRUDER function is useless without a functional servo ....

**Comment by DrumClock** [comment]
@thinkyhead 
Because something doesn't work with each new release of bugfix 2.0.x 
(what used to be OK) and nobody solves it, **I decided to switch to FW Klipper.**
**I will no longer pay attention to these issues.**

**Comment by thinkyhead** [comment]
@DrumClock — Excellent! I spend all day every day on Marlin issues, and still there are always more, and I personally have no time to dive into most issues or attend to my long TODO list. So, thanks for being so understanding.

**Comment by thinkyhead** [comment]
@InsanityAutomation — I have been unable to attend to this issue in spite of the demands of the entitled. This issue seems like it might be more your area, being that you are the tool-change wizard. What do you suppose is going on here with `SWITCHING_EXTRUDER`? Is this a genuine bug report or is it a hoax?

**Comment by InsanityAutomation** [comment]
I don't have a 4 hotend version like this, but I can see what 2 does. I havnt updated the switching one in awhile.

**Comment by thinkyhead** [comment]
Hmm, okay. Thanks for taking the trouble to respond in the common tongue. I am still not able to guess what is going on, but I will translate the text above and continue trying to find the source of the problem by staring at the code.

**Comment by thinkyhead** [comment]
It looks like #22036 (June 8) included a patch for `DISABLE_INACTIVE_EXTRUDER` + `SWITCHING_EXTRUDER`. I don't have any hardware to confirm that the correct extruder(s) are being put to sleep / woken up by this change, or to check whether extruders are being put to sleep in error.

**Comment by thinkyhead** [comment]
@InsanityAutomation — I get the feeling that our overbearing friend's report is indicating something about servos generally. Maybe that servos can go to sleep, and when they are told to move they are not powered so they do nothing. Or maybe they are remembering their angle, and not moving because they think they are already there.

Try sending `M280 P0 S-1` to power off the servo, then try T0 / T1 to switch the extruder. If it doesn't behave, that is a clue. The report hints that the servos are already powered off at startup, so you might not even need the `M280` command to see the issue.
