### ISSUE TITLE
[BUG] Crash on SD print with Power Loss Recovery

### ISSUE THREAD

**Issue by maheshhchandra** [MarlinFirmware/Marlin#22063]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

marlin crashes on printing from SD card if power loss recovery enabled
using marlin 2.0.8.2
SKR mini E3 V1.2

marlin auto build :
stm32f103rc_btt
stm32f103rc_btt_stm32
stm32f103rc_btt_512k
stm32f103rc_btt_512k_stm32

using BL touch
Filament runout sensor

PLR file is created on SD card but empty
attaching PLR file
[plr.zip](https://github.com/MarlinFirmware/Marlin/files/6604192/plr.zip)

### Bug Timeline

was working with marlin 2.0.7.2

### Steps to Reproduce

start print fron SD card if power loss recovery is switched on

### Version of Marlin Firmware

2.0.8.2

### Printer model

Ender 3 pro

### Electronics

BL touch, filament runout sensor

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

conf files
[conf.zip](https://github.com/MarlinFirmware/Marlin/files/6604196/conf.zip)

**Comment by ellensp** [comment]
latest bugfix doesn't even have 
stm32f103rc_btt_stm32
stm32f103rc_btt_512k_stm32
All stm32 env's where renamed

**Comment by ellensp** [comment]
actual bugfix configs for testing VERSION 02000900 [Configs.zip](https://github.com/MarlinFirmware/Marlin/files/6604273/Configs.zip)

**Comment by maheshhchandra** [comment]
For stable version
stm32f103rc_btt_stm32
stm32f103rc_btt_512k_stm32

For bugfix
stm32f103rc_btt_maple
stm32f103rc_btt_512k_maple

Both versions not working

Conf for bugfix
took the default conf
Just enabled powerloss recovery
and disabled SD read only

[conf.zip](https://github.com/MarlinFirmware/Marlin/files/6604321/conf.zip)

**Comment by ellensp** [comment]
that is interesting as stm32f103rc_btt_stm32 became stm32f103rc_btt 
and the original stm32f103rc_btt became stm32f103rc_btt_maple
So  according to this different build environments fail in stable vs bugfix

**Comment by maheshhchandra** [comment]
I have checked all 4 non usb versions in both stable & bug fix
all crash just as I start print from SD

For testing
took the default conf for each versions
Just enabled powerloss recovery
and disabled SD read only

Have tried 3 separate SD cards to rule out problem in SD cards
and also formatted the SD cards

**Comment by ellensp** [comment]
so your above statement is incorrect 
For bugfix the following fail
stm32f103rc_btt
stm32f103rc_btt_512k
stm32f103rc_btt_maple
stm32f103rc_btt_512k_maple

**Comment by maheshhchandra** [comment]
yes all 4

in both stable & bugfix

**Comment by ellensp** [comment]
Have you re reformatting the sdcard, just in case it is a little corrupt only effecting new file creation

**Comment by maheshhchandra** [comment]
Have tried 3 separate SD cards to rule out problem in SD cards
and also formatted the SD cards

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

I expect this is still an issue because PLR is constantly getting broken by our extremely prolific contributors.
