### ISSUE TITLE
[BUG] U8glib-HAL Multiple Package issue while compiling

### ISSUE THREAD

**Issue by sarvenn** [MarlinFirmware/Marlin#22064]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

U8glib-HAL more then one package warning while compiling with AutoBuild marlin.

### Bug Timeline

latest bugfix 2

### Expected behavior

No warning

### Version of Marlin Firmware

Latest bugfix2.0 as of today

### Printer model

Ender 3 pro

### Electronics

skr mini e3 v2

### Additional information & file uploads

I tried 256k and 512k env also tried maple env as well. All for builds have the same issue.
Besides that all four builds ended up with failure.
terminal text files are uploaded. For the other issue another bug report is raised.
[STM32F103RC_btt.txt](https://github.com/MarlinFirmware/Marlin/files/6604252/STM32F103RC_btt.txt)
[STM32F103RC_btt_512K.txt](https://github.com/MarlinFirmware/Marlin/files/6604253/STM32F103RC_btt_512K.txt)
[STM32F103RC_btt_maple.txt](https://github.com/MarlinFirmware/Marlin/files/6604254/STM32F103RC_btt_maple.txt)
[STM32F103RC_btt_512K_maple.txt](https://github.com/MarlinFirmware/Marlin/files/6604255/STM32F103RC_btt_512K_maple.txt)

**Comment by sarvenn** [comment]
I tried to compile the fw in platformio extension and this time successful without uglib warning.
![Ekran görüntüsü 2021-06-06 165840](https://user-images.githubusercontent.com/66178082/120927498-aa31c480-c6e9-11eb-8f84-7e881559b5d7.jpg)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
