### ISSUE TITLE
[BUG] (Marlin ignores NOZZLE_TO_PROBE_OFFSET)

### ISSUE THREAD

**Issue by SiegelDaniel** [MarlinFirmware/Marlin#22070]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

To me, it seems as if Marlin is ignoring the NOZZLE_TO_PROBE_OFFSET.
I already tried switching the values from (-46,-12,0) to (46,12,0) with no changes to the behaviour.
Using a MKS SGEN L V.2 (LPC 1769) on a CR-10 mini with TMC 2208 stepper drivers.

### Expected behavior

The printer sets the probe to a point on the Heatbed in order to probe the height. 

### Actual behavior

The printer sets the nozzle to the probepoint which results in the probe being off the bed. 

### Version of Marlin Firmware

Marlin 2.0.8.1 (Jun  6 2021 22:58:06)

### Printer model

Creality CR-10 Mini

### Electronics

MKS SGEN L V2

**Comment by ellensp** [comment]
these offsets are stored in eeprom.
You MUST reset eeprom back to firmware settings to get the new values
Send the machine a M502 gcode to load defaults from firmware then a M500 to save them to eeprom.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
