### ISSUE TITLE
[BUG] Geeetech A20T does not work after firmware upgrade (infinte beep & LCD not working & MAX Temp Heater 0 warning)

### ISSUE THREAD

**Issue by CFDus** [MarlinFirmware/Marlin#22102]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

[serial-log.txt](https://github.com/MarlinFirmware/Marlin/files/6634567/serial-log.txt)
[ConfigurationFiles.zip](https://github.com/MarlinFirmware/Marlin/files/6634587/ConfigurationFiles.zip)

I tried to update/upgrade my Firmware on the Geeetech A20T (no mods or board changes)
from 1.1.8
to 2.0.8.2
via platform.io with vs-code.
i got the serial monitor output but nothing on the lcd even when i put the proper 
conf/examples/geetech/... files for 2.0.8.2 into the 
conf/default folder and shortly after i get prompted, that the Max_temp is reached for Heater ID 0 (nothing [bed&nozzle] was even warm to the touch)
so i decided to downgrade to 1.1.9 but this fw is also not working with the proper conf file.
Only when using the build hex file from Geeetech.

### Expected behavior

Printer boots and shows informations / menu on LCD without any Max_Temp warnings and beep

### Actual behavior

Nothing gets shown on LCD & Serial Log prints as shown in the attached log file.
Printer keeps in infinte beep until i shut off power.

### Version of Marlin Firmware

2.0.8.2

### Printer model

Geeetech A20T

### Electronics

Stock electronics

### Your Slicer

Cura

### Host Software

Repetier Host

**Comment by ellensp** [comment]
"conf/examples/geetech/... files for 2.0.8.2 into the conf/default folder"
This is not correct
The configs go into the Marlin directory replacing the existing Configuration.h and Configuration_adv.h
If you put them in the wrong place your are still compiling for the default ramps config.
