### ISSUE TITLE
[BUG] (hard time building bin.file)

### ISSUE THREAD

**Issue by bg1080** [MarlinFirmware/Marlin#22127]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

plese see image when building the firmware i got 4 issues

### Bug Timeline

new bug

### Expected behavior

i expected to just have a sucessful bin.file 

### Actual behavior

none

### Steps to Reproduce

none

### Version of Marlin Firmware

2.0.8.2

### Printer model

ender3 v2

### Electronics

SKR 1.4 turbo

### Add-ons

n/a

### Your Slicer

Cura

### Additional information & file uploads

![marlin](https://user-images.githubusercontent.com/85809020/121791113-21100700-cb9b-11eb-9ac9-5a793cb48aa7.JPG)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by bg1080** [comment]
thank you
