### ISSUE TITLE
People cant request accounts at http://www.marlinfirmware.org/

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#2213]
last in this issue they say they cant request accounts: https://github.com/MarlinFirmware/Marlin/issues/2090

@scotty1024 any idea what is going on?

ps. password reset does not work either

**Comment by thinkyhead** [comment]
I have a web hosting account and would be happy to move the site there if no one else has time to manage it.

**Comment by scotty1024** [comment]
The only two people that have requested accounts are yourself and Scott.

Scotty

**Comment by boelle** [comment]
ok, there was one more that tried, hence the reason that i made this one

just cant rember who, but it was a person wanting to do documentation

Den onsdag den 10. juni 2015 skrev scotty1024 notifications@github.com:

> The only two people that have requested accounts are yourself and Scott.
> 
> Scotty
> 
> > On May 31, 2015, at 11:51 PM, Bo Herrmannsen <notifications@github.com

**Comment by epatel** [comment]
I have tried to apply for an account. Never got any response.

**Comment by clefranc** [comment]
I've just tried it, so far no response...
