### ISSUE TITLE
[BUG] Uncompilable for mega1280

### ISSUE THREAD

**Issue by vk-PyNoob** [MarlinFirmware/Marlin#22135]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Error while build for Geetech2560 with mega1280:

> In file included from Marlin\src\inc/../pins/mega/pins_GT2560_REV_A.h:31:0,
>                  from Marlin\src\inc/../pins/pins.h:242,
>                  from Marlin\src\inc/MarlinConfig.h:34,
>                  from Marlin\src\MarlinCore.h:24,
>                  from Marlin\src\MarlinCore.cpp:31:
> Marlin\src\inc/../pins/mega/env_validate.h:27:4: error: #error "Oops! Select 'Arduino/Genuino Mega or Mega 2560' in 'Tools > Board.'"
> 

I think that's because of this code in : Marlin\src\pins\mega\env_validate.h

> #pragma once
> 
> #if ENABLED(ALLOW_MEGA1280) && NOT_TARGET(__AVR_ATmega1280__, __AVR_ATmega2560__)
>   #error "Oops! Select 'Arduino/Genuino Mega or Mega 2560 or 1280' in 'Tools > Board.'"
> #elif NOT_TARGET(__AVR_ATmega2560__) <---
>   #error "Oops! Select 'Arduino/Genuino Mega or Mega 2560' in 'Tools > Board.'"
> #endif
> 
> #undef ALLOW_MEGA1280
> 

changing this: 

> #elif NOT_TARGET(__AVR_ATmega2560__) 

to 

> #elif NOT_TARGET(__AVR_ATmega1280__, __AVR_ATmega2560__)

so it is compilable, but may be not correct

### Steps to Reproduce
Set target to mega1280 & try to build

### Version of Marlin Firmware
2.0.8.2 Latest & bugfix

### Electronics
Geetech GT2560 Rev.A (with mega1280)

**Comment by ellensp** [comment]
This is fixed, closing
