### ISSUE TITLE
[BUG] Tronxy Chitu_V6 TFT not working right

### ISSUE THREAD

**Issue by NicholasTracy** [MarlinFirmware/Marlin#22131]
### Bug Description
After flashing to the recent bugfix version of marlin 2.0.x and using the new configuration files example for the X5SA, The TFT screen does not work as expected. Touch screen is off scale.

### Configuration Files
[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/5774975/Configuration.zip)

### Steps to Reproduce

I Tried using the "out of the box" configuration files provided in the example folder. But the screen shows up in the top left corner smaller than the rest of the screen. Default resolution of (320x240) seems to be wrong. After changing this to (480x320) it displays correctly, however the touch screen interface is way out of whack. It seem that the top left buttons are in the correct spot but the far bottom right buttons on screen do not work at all. middle of the screen seem slightly to the right and down from where it should be. 

#### Additional Information
I have tried it with the Classic UI option and the Color UI option. Neither worked.
I had a previous version from around a few months ago that worked just fine but the configuration file simply had an option for FSMC TFT. The recent version has a bunch of new options including resolution and UI that wasn't there before. Tried forcing a screen calibration with M995 in auto0.g file on SD card but the calibration always fails. 

I can try tomorrow to get video of the issue in action.

**Comment by rhapsodyv** [comment]
I just sent two PR to remove the outdated touch calibration values, and fixed the default TFT in the X5SA config.
