### ISSUE TITLE
Size non respected

### ISSUE THREAD

**Issue by Pietros84** [MarlinFirmware/Marlin#22142]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Hi all,
I have a custom 3d printer with BTT SKR 1.4 Turbo and TMC 2208 uart mode.
I have compiled Marlin 2.0.8.1 (not is the first time that I compile firmware).
With this mainboard I have this issue:
- If I set step/mm for respect object print size, than the extruder go auto of the bed (my bed is 301mm and go out in X and Y for other 4mm but read 301mm and the printed object is ok if smaller like calibration cube)
- If I set the step/mm for respect the travel of the extruder and the bed, than I have a smaller printed object and the size of the area is smaller for marlin.

The offset of the min_endstop are ok. 
I can print accurately because the object size tolerance change with it size.

(sorry for my English, I hope that is clear my explanation)

### Bug Timeline

Issue 

### Actual behavior

Respect size

### Version of Marlin Firmware

2.0.8.1

### Printer model

Custom

### Electronics

BTT SKR 1.4 Turbo, TMC 2208

### Your Slicer

Cura

### Host Software

Pronterface

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
