### ISSUE TITLE
[BUG] Ender 3 V2 - Error:MINTEMP triggered, system stopped! Heater_ID: 0 - broken from 2021-06-10 onwards

### ISSUE THREAD

**Issue by CRCinAU** [MarlinFirmware/Marlin#22153]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

For builds on 10th of this month and later, any command to heat the hotend will throw a MINTEMP error as follows:

```
Recv:  T:20.14 /0.00 B:20.27 /0.00 @:0 B@:0
Send: M104 S200
Recv: ok P15 B3
Recv: Error:MINTEMP triggered, system stopped! Heater_ID: 0
Recv: echo:Err: MINTEMP
```

Reverting back to a build ~10AM AEST on the 9th and this problem does not appear.

The heat command can come from USB UART, or from the devices screen to reproduce the error.

### Bug Timeline

2021-06-10

### Expected behavior

After a target temp being set, the hotend should heat to that.

### Actual behavior

```
Error:MINTEMP triggered, system stopped! Heater_ID: 0
```

Unsure if this also affects v4.2.7 mainboards.

### Steps to Reproduce

Ender 3 V2 build after around 2021-06-10 onwards.

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Creality Ender 3 V2

### Electronics

Creality v4.2.2 mainboard

### Additional information & file uploads

Initial suspect of this behaviour is this commit:
https://github.com/MarlinFirmware/Marlin/commit/77496c8235dab5182312652b4dc0b6d0f182cf30

However I can't confirm that at this point - but its the only commit that seems to mention anything about a heater or temperature :\

Attached Configuration.h / Configuration_adv.h and resulting BIN file.
[Configs_and_bin.zip](https://github.com/MarlinFirmware/Marlin/files/6670036/Configs_and_bin.zip)

**Comment by CRCinAU** [comment]
When performing a PID Tune on the 20210610 build, you can see things heat up ok, the thermisor registers the correct temps, and the process stops. Once the hotend is given a target temp, the MINTEMP error triggers... As logged in Octoprint:
![image](https://user-images.githubusercontent.com/3992884/122387935-b9025c00-cfb2-11eb-9bc5-9a722059a48a.png)

Doing just a normal heat of the hotend with 20210609 build works fine:
![image](https://user-images.githubusercontent.com/3992884/122388000-cd465900-cfb2-11eb-8bb4-540148efab85.png)

**Comment by ellensp** [comment]
I can confirm I replicated the issue using a provided firmware.bin, so far trigger is elusive

**Comment by CRCinAU** [comment]
It sometimes seems hard to start the triggering off - but It does seem that doing:

* Restore Settings
* Store Setings
* Powercycle Printer
* Attempt to heat hotend

Can make this more likely to occur... Once its happened once, it seems to happen every time...

**Comment by CRCinAU** [comment]
As a note to make this reproducible... If I flash a new firmware, then Restore Settings -> Store Settings then heat the hotend, it works. If I power the printer off, then on again and try to heat the hotend, the failure is immediate.

Further Restore Settings -> Store Settings attempts do not restore the ability to heat the hotend and still produce the MINTEMP error.

@thinkyhead - Do you have any idea why this would only manifest *after* the printer has been powercycled?

I've been wondering if part of the issue is that garbage is being stored to / read from the EEPROM causing it to be a permanent issue once an EEPROM write has been performed - which may point to:
https://github.com/MarlinFirmware/Marlin/commit/7c5e3b9071f2ca108ae636dff72b9558479950e4

**Comment by CRCinAU** [comment]
Ok, decided not to sleep tonight to track this down..... Going through the commits on the 9th:

Building from:
https://github.com/MarlinFirmware/Marlin/commit/70b80fcd16722ecbd8ada54c0fb867041cb5f1fd <-- works fine.
https://github.com/MarlinFirmware/Marlin/commit/7c5e3b9071f2ca108ae636dff72b9558479950e4 <-- seems ok (which blows the EEPROM theory out of the water)
https://github.com/MarlinFirmware/Marlin/commit/77496c8235dab5182312652b4dc0b6d0f182cf30 <-- goes boom.

**Comment by CRCinAU** [comment]
Testing PR https://github.com/MarlinFirmware/Marlin/pull/22184 by @thinkyhead 

Ran multiple test cycles - could not reproduce the MINTEMP failure with this patch applied.

**Comment by CRCinAU** [comment]
Fixed after the merge of https://github.com/MarlinFirmware/Marlin/pull/22184
