### ISSUE TITLE
Thermistor affect booting sequence for RepRapDiscount Full Graphic Smart Controller

### ISSUE THREAD

**Issue by HackerTon** [MarlinFirmware/Marlin#2220]
Board = Megatronics 2.0
Display = RepRapDiscount Full Graphic Smart Controller

I found that if the thermistor is not installed, RepRapDiscount Full Graphic Smart Controller will not boot.

Just to clarified that if that is a bug or a safety feature ?

Thanks.

**Comment by AnHardt** [comment]
If no thermistor is detected a MINTEMP error was thrown before the display is initialized.
#2183 should have fixed that.

**Comment by HackerTon** [comment]
Thanks for the information.
