### ISSUE TITLE
[BUG] PS_ON_PIN (12) not present on MKS Gen-L

### ISSUE THREAD

**Issue by HoverClub** [MarlinFirmware/Marlin#22200]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

PS_ON_PIN defined as D12 in src/pins/pins_RAMPS.h (included by src/pins/pins_MKS_GEN_L..h) does not exist on the official MKS Gen L board (https://github.com/makerbase-mks/MKS-GEN_L - it's not available on any connector) - this is also true for some derivative RAMPS boards.  Possible solution would be to use the 4th Servo signal pin (D11)? 
[config.zip](https://github.com/MarlinFirmware/Marlin/files/6695661/config.zip)

### Bug Timeline

Today

### Version of Marlin Firmware

2.09

**Comment by ellensp** [comment]
is already in a #ifdef block
```
#ifndef PS_ON_PIN
  #define PS_ON_PIN                           12
#endif

```

All you need to do is #define PS_ON_PIN 11  in your pins file or in Configuration.h  and it overrides this pin.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by HoverClub** [comment]
Yep - I get that I can override the def.  However the issue is that the pins_MKS_GEN_L.h  file is incorrect in that it defines a pin that doesn't exists on that particular board.  If you compiled for that board it wouldn't work correctly - that's a bug in my book?

**Comment by ellensp** [comment]
The board does not have a pin allocated to this function. So it drops to the default for the ramps.
If you add a power supply of this type, you are expected to know where you plugged it in and set PS_ON_PIN accordingly

**Comment by HoverClub** [comment]
It would be much more helpful if pins_MKS_GEN_L.h generated a compile error to remind users to allocate PS_ON_PIN instead of just defaulting to a non-existent pin?  Certainly would have saved me an hour or so trying to figure out which pin to connect the PSU to!
```
#ifdef PSU_CONTROL
  #ifndef PS_ON_PIN
    #error "MKS GEN L doesn't support PS_ON_PIN on RAMPS pin 12 - set PS_ON_PIN to another pin in configuration.h
  #endif
#endif

```
