### ISSUE TITLE
Download Master-DNS-Parental Control-Canon Printer Problems

### ISSUE THREAD

**Issue by porfavorhelp** [MarlinFirmware/Marlin#22230]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

My Router: GT-AX11000
Canon printer MB2700 Series can not connect to wifi after v386.2_6 installed. Download Master change folder directory is not working for instance I want to change the directory to USB 2 drive and do not work. Parental control sometimes do not block stream on 1 device. Also it Can not block person from changing their public dns. I also see this in my log.

error line a lot on the log
Jun 25 21:02:27 kernel: protocol 0800 is buggy, dev eth7

### Bug Timeline

Old and New with v386.2_6

### Expected behavior

I expect everything to work smoothly 

### Version of Marlin Firmware

v386.2_6

### Printer model

canon MB2700 Series

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
