### ISSUE TITLE
Marlin not compiling mega i3  - MarlinUI::lcd_clicked during firmware.elf

### ISSUE THREAD

**Issue by ntangle** [MarlinFirmware/Marlin#22254]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Compiling Marlin 2.0.9 upwards (same for 2.0.9.1) fails at the end during the firmware.elf using the i3 mega example in the 2.0.9.x configs.

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/megaatmega2560.html
PLATFORM: Atmel AVR (3.0.0) > Arduino Mega or Mega 2560 ATmega2560 (Mega 2560)
HARDWARE: ATMEGA2560 16MHz, 8KB RAM, 248KB Flash
DEBUG: Current (avr-stub) On-board (avr-stub, simavr)
PACKAGES:
 - framework-arduino-avr 5.1.0
 - toolchain-atmelavr 1.50400.190710 (5.4.0)
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 5 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Wire> 1.0
|-- <SPI> 1.0
|-- <EEPROM> 2.0
|-- <SoftwareSerial> 1.0
Building in release mode
Compiling .pio\build\mega2560\src\src\HAL\AVR\HAL.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\HAL_SPI.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\MarlinSerial.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\Servo.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\eeprom.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\fast_pwm.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\fastio.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\u8g_com_HAL_AVR_sw_spi.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\watchdog.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\Delay.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\HAL_MinSerial.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\eeprom_api.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\esp_wifi.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\servo.cpp.o
Compiling .pio\build\mega2560\src\src\MarlinCore.cpp.o
Compiling .pio\build\mega2560\src\src\core\serial.cpp.o
Compiling .pio\build\mega2560\src\src\core\utility.cpp.o
Compiling .pio\build\mega2560\src\src\feature\ammeter.cpp.o
Compiling .pio\build\mega2560\src\src\feature\bedlevel\bedlevel.cpp.o
Compiling .pio\build\mega2560\src\src\feature\bedlevel\mbl\mesh_bed_leveling.cpp.o
Compiling .pio\build\mega2560\src\src\feature\controllerfan.cpp.o
Compiling .pio\build\mega2560\src\src\feature\e_parser.cpp.o
Compiling .pio\build\mega2560\src\src\feature\host_actions.cpp.o
Compiling .pio\build\mega2560\src\src\feature\pause.cpp.o
Compiling .pio\build\mega2560\src\src\feature\runout.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\bedlevel\G26.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\bedlevel\G42.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\bedlevel\M420.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\bedlevel\mbl\G29.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\bedlevel\mbl\M421.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\calibrate\G28.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\calibrate\G34_M422.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\calibrate\M666.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M200-M205.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M220.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M221.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M301.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M302.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M304.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M309.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M92.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M108_M112_M410.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M111.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M120_M121.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M17_M18_M84.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M211.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M400.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M80_M81.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M85.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M993_M994.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M997.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M999.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\T.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\eeprom\M500-M504.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\feature\advance\M900.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\feature\digipot\M907-M910.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\feature\pause\G27.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\feature\pause\M125.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\feature\pause\M600.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\feature\pause\M603.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\feature\runout\M412.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\gcode.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\gcode_d.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\geometry\G92.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\geometry\M206_M428.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M110.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M113.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M114.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M115.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M118.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M119.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\lcd\M0_M1.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\lcd\M117.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\lcd\M145.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\lcd\M300.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\motion\G0_G1.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\motion\G2_G3.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\motion\G4.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\parser.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\queue.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M1001.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M20.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M21_M22.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M23.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M24_M25.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M26.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M27.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M28_M29.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M30.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M32.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M33.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M34.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M524.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\sd\M928.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\stats\M31.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\stats\M75-M78.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\temp\M104_M109.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\temp\M105.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\temp\M106_M107.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\temp\M140_M190.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\temp\M141_M191.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\temp\M155.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\temp\M303.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\units\M82_M83.cpp.o
Compiling .pio\build\mega2560\src\src\lcd\extui\anycubic_i3mega\anycubic_extui.cpp.o
Compiling .pio\build\mega2560\src\src\lcd\extui\anycubic_i3mega\anycubic_i3mega_lcd.cpp.o
Compiling .pio\build\mega2560\src\src\lcd\extui\ui_api.cpp.o
Compiling .pio\build\mega2560\src\src\lcd\fontutils.cpp.o
Compiling .pio\build\mega2560\src\src\lcd\marlinui.cpp.o
Compiling .pio\build\mega2560\src\src\libs\buzzer.cpp.o
Compiling .pio\build\mega2560\src\src\libs\crc16.cpp.o
Compiling .pio\build\mega2560\src\src\libs\nozzle.cpp.o
Compiling .pio\build\mega2560\src\src\libs\numtostr.cpp.o
Compiling .pio\build\mega2560\src\src\libs\stopwatch.cpp.o
Compiling .pio\build\mega2560\src\src\libs\vector_3.cpp.o
Compiling .pio\build\mega2560\src\src\module\endstops.cpp.o
Compiling .pio\build\mega2560\src\src\module\motion.cpp.o
Compiling .pio\build\mega2560\src\src\module\planner.cpp.o
Compiling .pio\build\mega2560\src\src\module\settings.cpp.o
Compiling .pio\build\mega2560\src\src\module\stepper.cpp.o
Compiling .pio\build\mega2560\src\src\module\stepper\indirection.cpp.o
Compiling .pio\build\mega2560\src\src\module\temperature.cpp.o
Compiling .pio\build\mega2560\src\src\module\tool_change.cpp.o
Compiling .pio\build\mega2560\src\src\sd\Sd2Card.cpp.o
Compiling .pio\build\mega2560\src\src\sd\SdBaseFile.cpp.o
Compiling .pio\build\mega2560\src\src\sd\SdFatUtil.cpp.o
Compiling .pio\build\mega2560\src\src\sd\SdFile.cpp.o
Compiling .pio\build\mega2560\src\src\sd\SdVolume.cpp.o
Compiling .pio\build\mega2560\src\src\sd\cardreader.cpp.o
Compiling .pio\build\mega2560\libd6b\Wire\Wire.cpp.o
Compiling .pio\build\mega2560\libd6b\Wire\utility\twi.c.o
Compiling .pio\build\mega2560\lib09b\SPI\SPI.cpp.o
Archiving .pio\build\mega2560\lib4c4\libEEPROM.a
C:\Users\ntang\.platformio\packages\framework-arduino-avr\libraries\Wire\src\utility\twi.c: In function '__vector_39':
C:\Users\ntang\.platformio\packages\framework-arduino-avr\libraries\Wire\src\utility\twi.c:552:7: 
warning: empty declaration
       __attribute__ ((fallthrough));
       ^
C:\Users\ntang\.platformio\packages\framework-arduino-avr\libraries\Wire\src\utility\twi.c:638:7: 
warning: empty declaration
       __attribute__ ((fallthrough));
       ^
Compiling .pio\build\mega2560\lib443\SoftwareSerial\SoftwareSerial.cpp.o
Archiving .pio\build\mega2560\libFrameworkArduinoVariant.a
Archiving .pio\build\mega2560\libd6b\libWire.a
Compiling .pio\build\mega2560\FrameworkArduino\CDC.cpp.o
Archiving .pio\build\mega2560\lib09b\libSPI.a
Compiling .pio\build\mega2560\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\HardwareSerial0.cpp.o
Archiving .pio\build\mega2560\lib443\libSoftwareSerial.a
Compiling .pio\build\mega2560\FrameworkArduino\HardwareSerial1.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\HardwareSerial2.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\HardwareSerial3.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\PluggableUSB.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\Print.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\USBCore.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\WInterrupts.c.o
Compiling .pio\build\mega2560\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\WString.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\abi.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\hooks.c.o
Compiling .pio\build\mega2560\FrameworkArduino\main.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\new.cpp.o
Compiling .pio\build\mega2560\FrameworkArduino\wiring.c.o
Compiling .pio\build\mega2560\FrameworkArduino\wiring_analog.c.o
Compiling .pio\build\mega2560\FrameworkArduino\wiring_digital.c.o
Compiling .pio\build\mega2560\FrameworkArduino\wiring_pulse.S.o
Compiling .pio\build\mega2560\FrameworkArduino\wiring_pulse.c.o
Compiling .pio\build\mega2560\FrameworkArduino\wiring_shift.c.o
Archiving .pio\build\mega2560\libFrameworkArduino.a
Linking .pio\build\mega2560\firmware.elf
C:\Users\ntang\AppData\Local\Temp\ccUUUvFj.ltrans18.ltrans.o: In function `Temperature::wait_for_bed(bool, bool)':
<artificial>:(.text+0x540): undefined reference to `MarlinUI::lcd_clicked'
<artificial>:(.text+0x544): undefined reference to `MarlinUI::lcd_clicked'
C:\Users\ntang\AppData\Local\Temp\ccUUUvFj.ltrans18.ltrans.o: In function `Temperature::wait_for_hotend(unsigned char, bool, bool)':
<artificial>:(.text+0x86a): undefined reference to `MarlinUI::lcd_clicked'
<artificial>:(.text+0x86e): undefined reference to `MarlinUI::lcd_clicked'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\mega2560\firmware.elf] Error 1
================================== [FAILED] Took 41.99 seconds ==================================

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:41.995
============================= 1 failed, 0 succeeded in 00:00:41.995 ============================= 
The terminal process "C:\Users\ntang\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'mega2560'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

### Bug Timeline

from 2.0.9

### Expected behavior

To finish compiling

### Actual behavior

Fails

### Steps to Reproduce

1.Download the 2.0.9.1 Zip, and the 2.0.9.1 configurations. Use the Anycubic i3 mega config/config.adv
2. Compile.
3. Fails!

### Version of Marlin Firmware

2.0.9.1

### Printer model

Anycubic Mega i3 S

**Comment by ntangle** [comment]
Tried with 2.0.x bugfix - still same error

**Comment by slowbro** [comment]
I can confirm this, same error using the i3 mega config. From the looks of it, it is not including/compiling the `menu/menu_*` files.

**Comment by slowbro** [comment]
It looks like this is being caused by `G26_CLICK_CAN_CANCEL`; commenting it out like so..

```diff
diff --git a/Marlin/src/module/temperature.h b/Marlin/src/module/temperature.h
index 3a8c506a5d..6c191f01e3 100644
--- a/Marlin/src/module/temperature.h
+++ b/Marlin/src/module/temperature.h
@@ -175,7 +175,7 @@ enum ADCSensorState : char {
 #endif
 
 #if ENABLED(G26_MESH_VALIDATION) && EITHER(HAS_LCD_MENU, EXTENSIBLE_UI)
-  #define G26_CLICK_CAN_CANCEL 1
+  //#define G26_CLICK_CAN_CANCEL 1
 #endif
 
 // A temperature sensor
```

.. allows compilation to finish. Maybe missing an include of `marilinui.h` (where `MarlinUI::lcd_clicked` is defined) in one of the extui files..? Looking more, but the diff above will let you build for now.

**Comment by slowbro** [comment]
Found it.

https://github.com/MarlinFirmware/Marlin/commit/a3e8bb99e472042c7db0b2d0be8d515ee715cf28#diff-3c8b6ef45c61c9cff05542db2f1b61eb8926eaf3e33f9b4d952323fdce5bddf8R226-R229

This is placed inside of a (file-global) `#if HAS_WIRED_LCD`, likely accidentally as the file isn't indented to show it (as usual) and it's kind of hidden. Moving it above that #if lets compilation happen..

```diff
diff --git a/Marlin/src/lcd/marlinui.cpp b/Marlin/src/lcd/marlinui.cpp
index d2e26afedf..ccaadf6c96 100644
--- a/Marlin/src/lcd/marlinui.cpp
+++ b/Marlin/src/lcd/marlinui.cpp
@@ -120,6 +120,11 @@ constexpr uint8_t epps = ENCODER_PULSES_PER_STEP;
   }
 #endif
 
+#if EITHER(HAS_LCD_MENU, EXTENSIBLE_UI)
+  bool MarlinUI::lcd_clicked;
+#endif
+
+
 #if HAS_WIRED_LCD
 
 #if HAS_MARLINUI_U8GLIB
@@ -223,10 +228,6 @@ millis_t MarlinUI::next_button_update_ms; // = 0
 
 #endif
 
-#if EITHER(HAS_LCD_MENU, EXTENSIBLE_UI)
-  bool MarlinUI::lcd_clicked;
-#endif
-
 #if HAS_LCD_MENU
   #include "menu/menu.h"
 
```

**Comment by ghost** [comment]
Hi, maybe this would be a better solution:
[1.patch.txt](https://github.com/MarlinFirmware/Marlin/files/6733222/1.patch.txt)

```diff
diff --git a/Marlin/src/module/temperature.h b/Marlin/src/module/temperature.h
index 3a8c506a5d..90a5966141 100644
--- a/Marlin/src/module/temperature.h
+++ b/Marlin/src/module/temperature.h
@@ -174,7 +174,7 @@ enum ADCSensorState : char {
   #define unscalePID_d(d) ( float(d) * PID_dT )
 #endif
 
-#if ENABLED(G26_MESH_VALIDATION) && EITHER(HAS_LCD_MENU, EXTENSIBLE_UI)
+#if ENABLED(G26_MESH_VALIDATION) && BOTH(HAS_LCD_MENU, EXTENSIBLE_UI)
   #define G26_CLICK_CAN_CANCEL 1
 #endif
```
A Printer like the Anycubic I3 Mega don't use HAS_LCD_MENU.

**Comment by slowbro** [comment]
#22257 was merged, which will fix this.

@Jebdiah66 the `G26_CLICK_CAN_CANCEL` comment I made was me just being verbose; it wasn't the actual cause, just narrowing down the symptoms to an area that could be disabled for OP to build. HAS_LCD_MENU and EXTENSIBLE_UI are more-or-less mutually exclusive, so that `BOTH()` would never be satisfied. The issue was that `lcd_click` was extended to EXTUI (despite the name having 'lcd' in it) to 'simulate' clicks in marlinui & trigger associated actions.

**Comment by peter-ch** [comment]
None of the fixes work. I tried commenting out "#define G26_CLICK_CAN_CANCEL 1" - didn't work, still can't compile. I tried replacing the EITHER with BOTH - didn't work.

**Comment by peter-ch** [comment]
The error I get is: error: assignment of read-only variable 'MarlinUI::lcd_clicked' 
Is this related? How can I fix this fast?

**Comment by thisiskeithb** [comment]
> #22257 was merged, which will fix this.

Confirmed. Default i3 mega config builds fine now.

> How can I fix this fast?

@peter-ch: Download a fresh copy of [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) since it has this fix.
