### ISSUE TITLE
For Ender 6 with updated configurations one of the funcitons calling wrong in the LCDcpp 

### ISSUE THREAD

**Issue by sparksplur** [MarlinFirmware/Marlin#22266]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

\DGUSScreenHandler.cpp:88:20: error: 'MKSLCD_SCREEN_PAUSE' was not declared in this scope; did you mean 'DGUSLCD_SCREEN_UNUSED'?    88 |         GotoScreen(MKSLCD_SCREEN_PAUSE);       |                    ^~~~~~~~~~~~~~~~~~~       |                    DGUSLCD_SCREEN_UNUSED... just needs to change to the DGULCD_SCREEN_UNUSED  so it calls the function correcctly

### Bug Timeline

its just a mistake in the cpp

### Version of Marlin Firmware

Newest bug fix 2.0

### Printer model

ender 6

### Your Slicer

Cura

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21274
