### ISSUE TITLE
[FR] In dual extruder config allow Z align with 5 drivers board

### ISSUE THREAD

**Issue by MLiv79** [MarlinFirmware/Marlin#22298]
### Describe the feature you want

I don't know if is possible to but would be really cool if in a dual extrusion configuration, the 5th driver that normally is used for E1, could be used both for E1 and Z2 motor to align Z axis. I mean, Z alignement is a one time operation, the last slot driver could be used to align Z and then released to be used for E1 extruder when printing. 
Is it possible or hardware locked?

**Comment by ellensp** [comment]
That would require some electro/mechanical method to physically uncouple the Z2 stepper from the driver
Not something that marlin can do. 
Once Z2 is disconnected you would need to physically uncouple the Z2 so Z could move, or connect Z2 stepper motor to Z1 stepper driver.

**Comment by MLiv79** [comment]
Yes you're right sorry. I forget the phisical cable, it's time to go to bed :D
