### ISSUE TITLE
[BUG] Neopixel timing errors with STM32F4

### ISSUE THREAD

**Issue by truglodite** [MarlinFirmware/Marlin#22296]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I believe there is a bug in the neopixel library that affects stm32f4 (and perhaps other stm32 devices). It seems the timing method used in the neopixel library may need to be fixed. The issue was discovered here: 

https://github.com/MarlinFirmware/Marlin/issues/17637

It appears no fix was ever implemented. 

### Bug Timeline

~2.0.5.3 and on

### Expected behavior

Neopixels event leds should show stable colors ranging from blue to red while preheating the bed and nozzle before printing.

### Actual behavior

I get random colors during preheating with event LEDs and neopixels enabled on my BTT GTR v1.0 board. My neopixel appears to be functioning properly for the more static colors (like white during print, green when done), but randomly flashes weird colors only when preheating.

### Steps to Reproduce

Enable neopixels and event_leds
Start print with preheat bed and/or nozzle gcode

### Version of Marlin Firmware

bugfix 2

### Printer model

A8

### Electronics

Bigtree GTR V1.0

### Add-ons

1@ GRB Neopixel

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

I attached my config files in case it helps. FWIW, I am using the redundant temp fix branch as required to keep my PT100 temp sensor working properly. I can of course test with the official bugfix branch if it has all the commits needed for that to work (AFAIK it's not quite ready yet). Also, I'm using the same neopixel wiring that worked fine before with ramps 1.4 (2560).

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6760547/Configuration.zip)

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
