### ISSUE TITLE
[BUG] Broken PAUSE_PROBE_DEPLOY_WHEN_TRIGGERED

### ISSUE THREAD

**Issue by prophetmaster** [MarlinFirmware/Marlin#22295]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

pause before probe not working in right direction inverted...

replace this -> if (deploy == PROBE_TRIGGERED()) break;
by -> if (deploy != PROBE_TRIGGERED()) break;

### Version of Marlin Firmware

2.0.9.1

### Printer model

custom delta

**Comment by ellensp** [comment]
Please update (bug summary) to related issue

**Comment by ellensp** [comment]
really?  perhaps I was not clear.
Please change the title to describe the actual bug. not literally using that string.

**Comment by thisiskeithb** [comment]
Since you've provided a fix, it'd be faster if you submitted a [Pull Request](https://marlinfw.org/docs/development/getting_started_pull_requests.html) so it can be reviewed.

**Comment by thinkyhead** [comment]
Hey! It took me less than 5 minutes to get this patched. If a solution is very simple, let's not badger the submitter for clerical fixes and post comments asking for a PR that might never come. Admins can just post a PR and this gets the issue closed ASAP so it doesn't linger for 9 days or more. If you require extra permissions to be able to edit issue titles please let me know.

**Comment by thisiskeithb** [comment]
> Hey! It took me less than 5 minutes to get this patched. If a solution is very simple, let's not badger the submitter for clerical fixes and post comments asking for a PR that might never come. Admins can just post a PR and this gets the issue closed ASAP so it doesn't linger for 9 days or more. If you require extra permissions to be able to edit issue titles please let me know.

I didn't feel comfortable submitting a fix for something that I couldn't verify was broken. That's why I generally ask the person who had the issue & fix, to submit a PR.

**Comment by thinkyhead** [comment]
I reviewed with Sublime Merge the last changes to the relevant lines and saw that indeed, the logic had been done backwards, and that was enough to confirm the fix.
