### ISSUE TITLE
[FR] (feature summary) custom button to send gcode

### ISSUE THREAD

**Issue by lunknowl** [MarlinFirmware/Marlin#22300]
### Is your feature request related to a problem? Please describe.

hi, i try  to use pin 19 to trigger M0 command (if pin 19 is high, send M0 command), how can i modify firmware to do that?

### Are you looking for hardware support?

no

### Describe the feature you want

no

**Comment by thisiskeithb** [comment]
Enable `CUSTOM_USER_BUTTONS`:

https://github.com/MarlinFirmware/Marlin/blob/de38cae00cf45ef864e2df180a9d37dc509817a4/Marlin/Configuration_adv.h#L3742-L3747

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
