### ISSUE TITLE
[FR] rename u8glib.h to marlin-u8glib.h

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#22303]
### Is your feature request related to a problem? Please describe.

Currently standard u8glib is no longer compatible with marlin, after the addition of the init function.

I purpose that a new fork or branch of https://github.com/MarlinFirmware/U8glib-HAL be created that actually calls itself marlin-u8glib

 

### Are you looking for hardware support?

128x64 based lcd's on arduino ide

### Describe the feature you want

Create a new fork or branch of https://github.com/MarlinFirmware/U8glib-HALthat calls itself marlin-u8glib
Leave the old one there to support older versions of marlin under platformio 

Then update Marlin to use this new library throughout.

This will stop Arduino IDE users attempting to use the old non compatible u8glib

Further marlin-u8glib could be added to Arduino IDE library manager so users can easily find and install it.

**Comment by thinkyhead** [comment]
Arduino IDE should never pick up the wrong header files going forward if we rename the main source and main header files so our include lines become `#include <U8glib_hal.h>`. Then we just have to make sure we're not mixing in any libraries that expect `U8glib.h` to be present.

I don't know that we need to give the library a new name. At this time `U8glib-HAL` is not in the official Arduino library registry, and `U8glib-HAL` is the name of the library that is already registered with PlatformIO.

So, let's say as a first step we just rename the main source / header files of our U8glib-HAL library, bump the version number, and make that new version a requirement. The new header name will prevent Arduino IDE from trying to use U8glib, and the new version number will ensure that bugfix users pick up the new library on the next compile.
