### ISSUE TITLE
[BUG] Tevo Tornado Custom Bootscreen displays garbage

### ISSUE THREAD

**Issue by yet-another-average-joe** [MarlinFirmware/Marlin#22326]
### Did you test the latest `bugfix-2.0.x` code?

Related to examples !

### Bug Description

Tevo Tornado Custom Bootscreen displays garbage.

### Bug Timeline

No idea. Didn't use the feature since 1.1.7 or so, and played with it today !

### Expected behavior

The Custom Bootscreen shouyld display a tornado...

### Actual behavior

It displays garbage.

### Steps to Reproduce

Copy _Bootscreen.h from the examples directory (Tevo Tornado 1 or 2), define SHOW_CUSTOM_BOOTSCREEN, and so on...

### Version of Marlin Firmware

2.0.9.1

### Printer model

Tevo Tornado v1

### Electronics

MKS Base 1.6

### Add-ons

none

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

In _Bootscreen.h : 

`#define CUSTOM_BOOTSCREEN_BMPWIDTH      112`

is not correct.

Should be 120. (15 bytes wide array)

`#define CUSTOM_BOOTSCREEN_BMPWIDTH      120`

solves the problem.

same issue as https://github.com/MarlinFirmware/Marlin/issues/21382

**Comment by ellensp** [comment]
issue is in https://github.com/MarlinFirmware/Configurations/blob/import-2.0.x/config/examples/Tevo/Tornado/V2%20(MKS%20GEN-L)/_Bootscreen.h 
and
https://github.com/MarlinFirmware/Configurations/blob/import-2.0.x/config/examples/Tevo/Tornado/V1%20(MKS%20Base)/_Bootscreen.h

**Comment by thisiskeithb** [comment]
It used to work. I'll put in a fix if @ellensp isn't already on it.

![image](https://user-images.githubusercontent.com/13375512/125148788-9531c200-e0e9-11eb-9979-c99f71e17e8a.png)

**Comment by ellensp** [comment]
You go for it

**Comment by thisiskeithb** [comment]
Fixed in https://github.com/MarlinFirmware/Configurations/pull/539

**Comment by ellensp** [comment]
Since this is for the Configuration repository and a PR has been created to fix it. Closing this Marlin issue.
