### ISSUE TITLE
[BUG] (bug summary)CUSTOM_USER_BUTTONS not working

### ISSUE THREAD

**Issue by espadan3d** [MarlinFirmware/Marlin#22328]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

hi
I active CUSTOM_USER_BUTTONS for pin 42&44 to have a pause button but when connect GND to d42 nothing happens(also i check by 5v but nothing happens)
![44444](https://user-images.githubusercontent.com/36302436/125157208-c9a38d80-e17e-11eb-911b-db303b19f445.JPG)

I change true/false & low/high but nothing happens

### Version of Marlin Firmware

bugfix-2.0.x

**Comment by espadan3d** [comment]
For test I even entered the PIN number in this tab but nothing happens
![22](https://user-images.githubusercontent.com/36302436/125157320-9f9e9b00-e17f-11eb-8234-8f2b239d56a4.jpeg)

**Comment by ellensp** [comment]
_WHEN_PRINTING should be "true" or "false" not  "False" or "True" It is case sensitive. 

Pins debugging just shows the pin name in a M43, it does not set the pin.
Eg 
> PIN:  42   Port: L7        BUTTON1_PIN                            Input  = 1  
> PIN:  44   Port: L5        BUTTON2_PIN                            Input  = 1

**Comment by espadan3d** [comment]
oh
 if I want pause print when connect GND to d42 and resume when connect GND to d44 below code is correct?
![1211](https://user-images.githubusercontent.com/36302436/125157789-25bbe100-e182-11eb-913a-dac5bb30d833.JPG)

**Comment by ellensp** [comment]
no. you need 
#define BUTTON1_WHEN_PRINTING true
#define BUTTON2_WHEN_PRINTING true

**Comment by espadan3d** [comment]
Thanks, solved
But in my sample m109 does not work right
I wired so that push pause button  disconnected heater now receive error and failed print 
You have a solution?

**Comment by ellensp** [comment]
What are you trying to get M109 to do?

**Comment by espadan3d** [comment]
May be need pause a long time and I want cool heater when machine is pause that the piece does not break by pause also disconnect heater
when change button of pause to resume connect heater this time I need M109 that not resume print before heating
There is an other command that software can do this?

**Comment by espadan3d** [comment]
If i open a new issues for this problem (false alarm) ,Is there a solution?

**Comment by thisiskeithb** [comment]
> If i open a new issues for this problem (false alarm) ,Is there a solution?

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
