### ISSUE TITLE
TFT mode no printing

### ISSUE THREAD

**Issue by AntoszHUN** [MarlinFirmware/Marlin#22330]
### Did you test the latest `bugfix-2.0.x` code?

Yes.

### Bug Description

Hi! I downloaded the TFT firmware from GitHub 2-3 days ago. (Not the official release!) Since I am developing I am not using the official release. This is the current firmware on GitHubon. The machine does not print in TFT mode. Prints only in Marlin mode. What's the mistake? This is what he does in the video. It heats up the devices and does nothing afterwards. What the hell?

### Version of Marlin Firmware

bugfix_2.0.x

**Comment by thisiskeithb** [comment]
This has nothing to do with Marlin.

**Comment by ghost** [comment]
O sorry I pushed aside.
