### ISSUE TITLE
[BUG] 'disp_string' was not declared in this scope

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#22349]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When attempting to compile mks_robin_nano_v3 with extui/mks_ui you get the error
```
Marlin/src/lcd/extui/mks_ui/draw_error_message.cpp: In function 'void lv_draw_error_message(const char*)':
Marlin/src/lcd/extui/mks_ui/draw_error_message.cpp:42:12: error: 'disp_string' was not declared in this scope
   42 |   if (msg) disp_string((TFT_WIDTH - strlen(msg) * 16) / 2, 100, msg, 0xFFFF, 0x0000);
```

### Bug Timeline

new

### Expected behavior

It should compile

### Actual behavior

Marlin/src/lcd/extui/mks_ui/draw_error_message.cpp:42 requires disp_string but disp_string is only created when
MKS_TEST is defined.

### Steps to Reproduce

1. Use provided config
2. attempt to compile
3. note the error

### Version of Marlin Firmware

latest bugfix

### Electronics

BOARD_MKS_ROBIN_NANO_V3

### Add-ons

MKS_TS35_V2_0

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6806050/Configuration.zip)

### Related to issue: https://github.com/MarlinFirmware/Marlin/issues/21069

**Comment by Malderin** [comment]
I solved the problem like this:
https://github.com/MarlinFirmware/Marlin/pull/22388
