### ISSUE TITLE
[BUG] MarlinUI - Change Filament menu doesn't show preheat options correctly

### ISSUE THREAD

**Issue by The-EG** [MarlinFirmware/Marlin#22360]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

If 'Change Filament' is selected while the hotend is cold, the preheat menu is shown but items can't be selected because the 'Change Filament' alert screen is repeated. The only way to exit is to select 'No'. The only way to initiate a filament change from the LCD is to preheat the hotend separately.

On a `CR10_STOCKDISPLAY`:
<details>
<summary>video</summary>

![cr10_stockdisplay](https://user-images.githubusercontent.com/7342077/125622046-f33188df-f596-458f-b825-958eaff50f65.gif)

</details>

On the Ender 3 v2's DWIN (#22211, note the preheat items are visible):
<details>
<summary>video</summary>

![dwin](https://user-images.githubusercontent.com/7342077/125622568-264acfdc-babe-4903-90b3-f50fce66b146.gif)

</details>

### Bug Timeline

Not sure, found while testing #22211

### Expected behavior

Selecting 'Change Filament' while the hotend is not heated should show the preheat items and allow for selection.

### Actual behavior

Selecting a preheat item is not possible.

### Steps to Reproduce

With `ADVANCED_PAUSE_FEATURE` enabled *and `FILAMENT_LOAD_UNLOAD_GCODES` **disabled***:

1. Start with nozzle temperature off
2. Select 'Change Filament' from LCD menu

### Version of Marlin Firmware

2.0.9.1 and bugfix-2.0.x

### Printer model

Ender 3 Pro & Ender 3 V2

### Additional information & file uploads

Config:
[Ender3v2.zip](https://github.com/MarlinFirmware/Marlin/files/6816031/Ender3v2.zip)

**Comment by thisiskeithb** [comment]
Interestingly, this works fine with `REPRAP_DISCOUNT_SMART_CONTROLLER` enabled.

**Comment by The-EG** [comment]
> Interestingly, this works fine with `REPRAP_DISCOUNT_SMART_CONTROLLER` enabled.

A somewhat random question: do you happen to have `FILAMENT_LOAD_UNLOAD_GCODES` enabled?

**Comment by thisiskeithb** [comment]
> A somewhat random question: do you happen to have FILAMENT_LOAD_UNLOAD_GCODES enabled?

I sure do! [Here's a link to the full Marlin build](https://github.com/thisiskeithb/Marlin/tree/myconfig/MK3S-BTT002-TMC2209).

**Comment by The-EG** [comment]
Confirmed: with `FILAMENT_LOAD_UNLOAD_GCODES` enabled this issue doesn't occur.

With that, 'Change Filament' becomes a submenu, and the 'Change Filament' item in that menu functions correctly.

So that's something.

edit: with that, I think the issue is https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/lcd/menu/menu_main.cpp#L365-L374

I'll try to unravel all of the macros going on, but I bet it's not switching to the preheat screen correctly. Maybe a `goto_previous_screen` call somewhere it shouldn't be?

**Comment by thisiskeithb** [comment]
Fixed in https://github.com/MarlinFirmware/Marlin/pull/22370
