### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by samuro77** [MarlinFirmware/Marlin#22371]
### Is your feature request related to a problem? Please describe.

Tengo una Ender 3 Pro, actualice a una placa silenciosa de Creality 4.2.7, el firmware de fabrica no iniciaba la impresión, después de esto descargue Marlín 2.0.9.1 y las configuraciones, lo compile según se muestra en este tutorial https://www.youtube.com/watch?v=U4wORSO9BT0&t=321s pero ahora cuando quiero hacer cambio de filamento configuro desde CURA 4.8 o 4.10 https://www.youtube.com/watch?v=eekSdP2xMhs&t=120s pero la maquina ya no se detiene, como silo hacia con la placa original con que venia la maquina

### Are you looking for hardware support?

Tengo una Ender 3 Pro
actualice a una placa silenciosa de Creality 4.2.7 

### Describe the feature you want

(que permita hacer cambio de filamento para impresión en varios colores) como hace la placa original (1.1.4)

### Additional context

Yo cambie el idioma de ingles a español para la pantalla (en - es), habilite el home para cada eje xyz, personalice el nombre de la impresora (custom)
<img width="254" alt="Cubierta motor" src="https://user-images.githubusercontent.com/87495383/125837943-4b66e096-d7a3-427b-b8b9-d30586247f11.png">
![1626373293263](https://user-images.githubusercontent.com/87495383/125838578-57b8ad50-25f4-4558-b4f7-bb042c9e590d.jpg)

**Comment by slowbro** [comment]
Please update the "(feature summary)" title with something more descriptive of the feature request.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
