### ISSUE TITLE
Extruder motor running during DRYRUN

### ISSUE THREAD

**Issue by clefranc** [MarlinFirmware/Marlin#2241]
The extruder motor is running when using the DRYRUN debug function.

Latest development branch 2bf482ce6564b1873478890ce68aac2756de265c

**Comment by clefranc** [comment]
I've submitted a PR https://github.com/MarlinFirmware/Marlin/pull/2242

**Comment by AnHardt** [comment]
#2354, #2355, #2358 are potential solutions for the problem. Can we please decide for one? (Hangout?)

**Comment by thinkyhead** [comment]
Oh damn, hangout tomorrow! I'll connect early, around 19:00 UTC.

**Comment by thinkyhead** [comment]
This should be fixed in the latest RC (RC2). Please have a look, and re-open this issue if the problem still exists.
