### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by Russ48** [MarlinFirmware/Marlin#22428]
### Describe the feature you want

PART COOLING FAN1 AND FAN0 synced on SKR Mini E3 V2 with two PWM Fan connectors. Would like them to act in sync using controller board and not just wiring them together.

**Comment by thisiskeithb** [comment]
This feature exists. Enable `REDUNDANT_PART_COOLING_FAN`.

**Comment by Russ48** [comment]
Thank you.. I saw this but cannot enable it and create a bin. file. will keep trying.. Do not k now if this was verified.
