### ISSUE TITLE
[BUG] LCD unresponsive with default BLOCK_BUFFER_SIZE of 8. Works with 32 or higher.

### ISSUE THREAD

**Issue by hamster65** [MarlinFirmware/Marlin#22434]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I often (but not always) cannot use the display functions, like baby stepping etc during print because the display is not responsive. Once I pause the print, it works again and becomes unresponsive again once printing resumes.

Setting BLOCK_BUFFER_SIZE to 32 fixes it. 16 is not enough. Maybe we should raise the default?

This happens for most prints, but not for all. I can even print **the same gcode **several times and on 1 out of 10 attempts, the lcd works.

Unresponsive means:
It does not update the coordinates / temperatures every second, but by irregular intervals, or not at all for a long time.
When I press the encoder, it beeps once but does not enter the menu. When, after multiple attempts or by pausing the print, I manage to go to a setting I want to change, I turn the encoder (while printing), and nothing happens, for the most time. Sometimes, it suddenly reacts. In this case, it seems to have summed up the missed encoder impulses and the number changes by the sum.

It seems to happen especially at the beginning of the print (first couple of layers), but that might be only my perception because it is especially annoying then.

Happens with Prusa Slicer and Cura. Did not try others. Did not try printing from sd. I do not have sd support compiled in.

### Bug Timeline

happens since more then 2 years, I think. I found several closed bug reports on this.

### Expected behavior

I expect the display to update and respond.

### Actual behavior

LCD is not responding during most prints.

### Steps to Reproduce

Start a print
Try to operate the LCD -> unresponsive
Pause print
Operate the LCD -> works
Resume print
Operate the LCD -> Stuck again
Cancel print

Start the same print again, repeat the above. After many attempts, LCD might work during print.

### Version of Marlin Firmware

bugfix branch, pulled and compiled today

### Printer model

custom

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/6873730/Marlin.zip)

**Comment by thisiskeithb** [comment]
> Setting BLOCK_BUFFER_SIZE to 32 fixes it. 16 is not enough. Maybe we should raise the default?

This isn't universally true and is precisely why there is a config option for it.

I wouldn't call this a bug, but a configuration issue.
