### ISSUE TITLE
Current z height is always zero on LCD

### ISSUE THREAD

**Issue by gunaygurer** [MarlinFirmware/Marlin#22442]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi, I have ender 3 pro with SKR v1.3, TFT28 and Marlin 2.0

The problem is I cannot see the current z-height during the print. It shows 0 all the time. 

After having the problem I have connected original Ender LCD while TFT28 is also connected and original LCD can show the current Z height while TFT28 shows zero.

### Expected behavior

TFT28 to show the current z height during print.

### Actual behavior

TFT28 shows z height zero during print

### Version of Marlin Firmware

Marlin 2.0

### Printer model

Ender 3 Pro

### Electronics

SKR V1.3

### Add-ons

TFT28 LCD

### Your Slicer

Cura

**Comment by thisiskeithb** [comment]
Be sure to enable all the Marlin dependencies required for the TFT firmware to work correctly: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware#marlin-dependencies

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
