### ISSUE TITLE
[BUG] Z_PROBE_SERVO_NR + ENDSTOP_INTERRUPTS_FEATURE crashing Ender 3 v2

### ISSUE THREAD

**Issue by dwery** [MarlinFirmware/Marlin#22451]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Enabling Z_PROBE_SERVO_NR leads to a complete crash of the Ender 3 v2. The display is totally garbled and the loading bar can be seen over and over.

Configuration is Ender 3 v2 template + attached changes

### Bug Timeline

New bug. dd4990252e891cdfe56cb7d6e3bbe1e6289be649 was working.

### Version of Marlin Firmware

296d0d495cad942cccd611b74a6b8a414a089a65

### Printer model

Ender 3 v2

### Additional information & file uploads

[probe.txt](https://github.com/MarlinFirmware/Marlin/files/6890540/probe.txt)

**Comment by ellensp** [comment]
That seems rather unlikely
In marlin is 
```CPP
#if ENABLED(BLTOUCH)
  #ifndef Z_PROBE_SERVO_NR
    #define Z_PROBE_SERVO_NR 0 
```
So if you enable it or not Marlin always enables it...

**Comment by ellensp** [comment]
and also Z_SERVO_ANGLES are also bypassed
```CPP
  #ifdef Z_PROBE_SERVO_NR
    #if ENABLED(BLTOUCH)
      #include "../feature/bltouch.h"
      #undef Z_SERVO_ANGLES
      #define Z_SERVO_ANGLES { BLTOUCH_DEPLOY, BLTOUCH_STOW }
    #endif

where
#define BLTOUCH_DEPLOY          10
#define BLTOUCH_STOW            90
```

**Comment by dwery** [comment]
@ellensp if it helps, my probe is not a BL Touch, so I guess there is something else involved.

**Comment by ellensp** [comment]
Please attach your full configuration files.

**Comment by thinkyhead** [comment]
What can we do to get folks to upload their configurations? I thought I made it pretty explicit in the new bug report template.

**Comment by thisiskeithb** [comment]
> What can we do to get folks to upload their configurations? I thought I made it pretty explicit in the new bug report template.

Honestly, some kind of bot to check for attachments/issue completeness would be the best path forward. It's getting pretty tiring asking for them.

**Comment by thinkyhead** [comment]
Fun with actions. There goes our salvage, guys.

**Comment by dwery** [comment]
@thinkyhead I thought that attaching a delta diff from the stock Ender3v2 config was enough. I’ll upload ASAP.

**Comment by thinkyhead** [comment]
> attaching a delta diff from the stock Ender3v2 config was enough

As you can imagine, it is quite simple and pleasant to drop the complete config files into place, hit "Build," and see what you are seeing in the shake of a lamb's tail. Any other format is a hassle.

**Comment by dwery** [comment]
[config.tar.gz](https://github.com/MarlinFirmware/Marlin/files/6911824/config.tar.gz)
Here you go

**Comment by thinkyhead** [comment]
For isolation testing… try commenting out these lines in `MarlinCore.cpp`…
```cpp
  #if HAS_Z_SERVO_PROBE
    SETUP_RUN(probe.servo_probe_init());
  #endif
```

**Comment by thinkyhead** [comment]
If that still crashes, then also comment out the lines just above it…
```cpp
  #if HAS_SERVOS
    SETUP_RUN(servo_init());
  #endif
```

**Comment by dwery** [comment]
@thinkyhead tried both, still crashes.

**Comment by dwery** [comment]
@thinkyhead is there anything else I can test?

**Comment by dwery** [comment]
A few more data points:

BLTOUCH enabled and my non bltouch probe connected: crashes.
BLTOUCH enabled and my non bltouch probe disconnected: no crash until I connect the probe at runtime.
Z_PROBE_SERVO_NR and probe connected: crashes
Z_PROBE_SERVO_NR and probe disconnected: crashes

**Comment by dwery** [comment]
@thinkyhead 
Disabling ENDSTOP_INTERRUPTS_FEATURE solves this issue. I guess the irq handler is called at an unexpected time when this particular type of probe is enabled.
