### ISSUE TITLE
Z_DUAL_STEPPER_DRIVERS enable compile error

### ISSUE THREAD

**Issue by geekgarage** [MarlinFirmware/Marlin#2245]
Stable Release 1.0.2
Arduino compile log
http://pastebin.com/W0sZpRzx

I tried searching related issues but without luck, all the solutions refer to code that do not exist any more or has been fixed. I first tried this with the DEV release but the probing of bed did not work, it just moved in a square and that was it, no probing of the bed at all, it didn't lift the printhead. (inductive sensor), so i moved back to stable release.

Configuration.h
http://pastebin.com/g8ivucRA

Configuration_Adv.h
http://pastebin.com/zebccnHK

**Comment by tonnico** [comment]
Where do you define the `Z2_ENABLE_PIN`?

**Comment by geekgarage** [comment]
Sorry for the late answer i had a family emergency. I've looked over the pins.h file and can see that Z2_ENABLE_PIN isn't defined for RUMBA board,

What i did is change this for the Rumba Board
#define E2_STEP_PIN        29
#define E2_DIR_PIN         28
#define E2_ENABLE_PIN      39

to this

#define Z2_STEP_PIN        29
#define Z2_DIR_PIN         28
#define Z2_ENABLE_PIN      39

And now it compiles, thanks :)

**Comment by tonnico** [comment]
Have fun with it :)

**Comment by thinkyhead** [comment]
Probably for all the boards that have enough stepper connections we'll patch up the code to do something like this instead of using the pin numbers:

```
#define Z2_STEP_PIN   E2_STEP_PIN
#define Z2_DIR_PIN    E2_DIR_PIN
#define Z2_ENABLE_PIN E2_ENABLE_PIN
```
