### ISSUE TITLE
[BUG] DGUS_LCD_UI_FYSETC compile error

### ISSUE THREAD

**Issue by andrefcarvalho** [MarlinFirmware/Marlin#22465]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

if you compile the marlin with (//#define DGUS_LCD_UI_FYSETC) the result is successful, however if you remove the // it gives an error when compiling

### Bug Timeline

new, no problem with marlin 020005

### Expected behavior

successfully compiled

### Actual behavior
```
Compiling .pio\build\FYSETC_F6\src\src\libs\stopwatch.cpp.o
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp: In static member function 'static void DGUSScreenHandler::DGUSLCD_SD_FileSelected(DGUS_VP_Variable&, void*)':
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:47:22: error: 'filelist' was not declared in this scope
     if (touched_nr > filelist.count()) return;
                      ^~~~~~~~
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:47:22: note: suggested alternative: 'filepos_t'
     if (touched_nr > filelist.count()) return;
                      ^~~~~~~~
                      filepos_t
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:48:10: error: 'filelist' was not declared in this scope
     if (!filelist.seek(touched_nr)) return;
          ^~~~~~~~
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:48:10: note: suggested alternative: 'filepos_t'
     if (!filelist.seek(touched_nr)) return;
          ^~~~~~~~
          filepos_t
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:50:9: error: 'filelist' was not declared in this scope
     if (filelist.isDir()) {
         ^~~~~~~~
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:50:9: note: suggested alternative: 'filepos_t'
     if (filelist.isDir()) {
         ^~~~~~~~
         filepos_t
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:59:55: error: 'filelist' was not declared in this scope
       dgusdisplay.WriteVariable(VP_SD_Print_Filename, filelist.filename(), VP_SD_FileName_LEN, true);
                                                       ^~~~~~~~
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:59:55: note: suggested alternative: 'filepos_t'
       dgusdisplay.WriteVariable(VP_SD_Print_Filename, filelist.filename(), VP_SD_FileName_LEN, true);
                                                       ^~~~~~~~
                                                       filepos_t
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp: In static member function 'static void DGUSScreenHandler::DGUSLCD_SD_StartPrint(DGUS_VP_Variable&, void*)':
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:69:10: error: 'filelist' was not declared in this scope
     if (!filelist.seek(file_to_print)) return;
          ^~~~~~~~
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:69:10: note: suggested alternative: 'filepos_t'
     if (!filelist.seek(file_to_print)) return;
          ^~~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio\build\FYSETC_F6\src\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp.o] Error 1
======================================================================================================================================= [FAILED] Took 23.46 seconds =======================================================================================================================================
Environment    Status    Duration
-------------  --------  ------------
FYSETC_F6      FAILED    00:00:23.464
================================================================================================================================== 1 failed, 0 succeeded in 00:00:23.464 ==================================================================================================================================PS E:\13-3D_PRINTER\soft\Marlin-2.0..9.1\Marlin-2.0.x> echo "done" >C:\Users\andre\AppData\Local\Temp\ipc
PS E:\13-3D_PRINTER\soft\Marlin-2.0..9.1\Marlin-2.0.x>
```
### Steps to Reproduce

built the marlin with #define DGUS_LCD_UI_FYSETC uncoment

### Version of Marlin Firmware

2.0.9.1

### Printer model

custom

### Electronics

Fysetc f6 and Fys touch  lcd

### Host Software

SD Card (headless)

**Comment by ellensp** [comment]
@andrefcarvalho The  error: 'filelist' was not declared in this scope is fixed in my latest PR. Which was aimed at fixing up DGUS_LCD_UI_ORIGIN, but also fixed several DGUS_LCD_UI_FYSETC and DGUS_LCD_UI_HIPRECY issues
https://github.com/MarlinFirmware/Marlin/pull/22464

**Comment by andrefcarvalho** [comment]
How to resolve this issue?

**Comment by ellensp** [comment]
apply the PR, or wait a few days till its added to Marlin bugfix

Or add the missing code you need from https://github.com/MarlinFirmware/Marlin/pull/22464/files#diff-884fc0d0371fb11b304eb95cb5fa6fc00804de791fc9963d9594d9f7d72144df

most of which is cosmetic except adding  "static ExtUI::FileList filelist;" 
 to Marlin/src/lcd/extui/dgus/fysetc/DGUSScreenHandler.cpp

**Comment by andrefcarvalho** [comment]
now it's given me this error

```
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp: In static member function 'static void DGUSScreenHandler::DGUSLCD_SD_ResumePauseAbort(DGUS_VP_Variable&, void*)':
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:86:20: error: 'MKSLCD_SCREEN_PAUSE' was not declared in this scope
         GotoScreen(MKSLCD_SCREEN_PAUSE);
                    ^~~~~~~~~~~~~~~~~~~
Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp:86:20: note: suggested alternative: 'DGUSLCD_SCREEN_UNUSED'
         GotoScreen(MKSLCD_SCREEN_PAUSE);
                    ^~~~~~~~~~~~~~~~~~~
                    DGUSLCD_SCREEN_UNUSED
*** [.pio\build\FYSETC_F6\src\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp.o] Error 1
======================================================================================================================================= [FAILED] Took 7.77 seconds ======================================================================================================================================= 

Environment    Status    Duration
-------------  --------  ------------
```

**Comment by ellensp** [comment]
yip...   I don't have access to that lcd so haven't had a chance to do much with it...

replace MKSLCD_SCREEN_PAUSE with DGUSLCD_SCREEN_SDPRINTMANIPULATION in Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp line 86 

and see whats next

**Comment by andrefcarvalho** [comment]
> yip... I don't have access to that lcd so haven't had a chance to do much with it...
> 
> replace MKSLCD_SCREEN_PAUSE with DGUSLCD_SCREEN_SDPRINTMANIPULATION in Marlin\src\lcd\extui\dgus\fysetc\DGUSScreenHandler.cpp line 86
> 
> and see whats next

success, another fix for marlin, i going to upload the code and test everything

**Comment by ellensp** [comment]
I suspect It will be stuck on bootscreen. if it is dont panic, as the DGUS_LCD_UI_ORIGIN had same issue. but can try same fix if it does

**Comment by andrefcarvalho** [comment]
yes it is stuck on bootcreen

**Comment by ellensp** [comment]
ok hold on...

**Comment by andrefcarvalho** [comment]
ok

**Comment by ellensp** [comment]
you need to make these changes https://github.com/MarlinFirmware/Marlin/pull/22464/commits/aa50ddaf94ada3c5504cc24b13fc13617767d42d

**Comment by ellensp** [comment]
I'm working on bugfix, so line numbers are out 1 or 2, but hopefully you can work out what to add

**Comment by andrefcarvalho** [comment]
passed the boot screen, but part of the lcd functions do not work, for example, moving axes, setting temperatures or using SD files

![image](https://user-images.githubusercontent.com/43297899/127660989-b4df3646-617f-4f06-9907-e4719f3e7654.png)

**Comment by andrefcarvalho** [comment]
I've been comparing the DGUSDisplayDef.h file with the old one and everything seems to be the same

**Comment by ellensp** [comment]
Sadly without access to that lcd I can't assist further...   I've added the patches so far to my current PR

**Comment by andrefcarvalho** [comment]
thanks, i'll try to see where the problem comes from, in this built i added the communication by uart for the tmc2208, it could be the cause of the problem, i'll have to test

**Comment by ellensp** [comment]
If you get a chance, could you take screen shots and put boxes around areas that don't work. That would be useful to know

**Comment by andrefcarvalho** [comment]
i see this on fysect wiki, but i thing marlin it´s diferent files now 

https://wiki.fysetc.com/How_to_Configure_TMC2208_on_FYSETC-F6-Board/

**Comment by andrefcarvalho** [comment]
probably a board problem https://forum.fysetc.com/d/4-fysetc-f6-with-tmc-2208-marlin2-0-uart-and-extruder-not-working/8

**Comment by thinkyhead** [comment]
The patch PR was merged. Please close once all the Marlin-caused issues are fixed.
