### ISSUE TITLE
[BUG] (homing)

### ISSUE THREAD

**Issue by mohsenzolfagharian** [MarlinFirmware/Marlin#22474]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi everyone , I am new to Marlin and 3D printers so I don't know what is my problem exactly so I need your help 

I am using Arduino mega 2560 to run marlin code , as I read , marlin's2.0.x  the default configuration is set on Arduino Mega and I don't know why I get  Error:Printer halted. kill() called!
as I said , I am not sure what is my problem so here is the list of objects of my 3D printer :
1- Arduino Mega 2560
2- ramps1.6
3- stepper Nema 17
4- stepper driver : DRV 8825
And final point that want to mention is, I didn't change the code and I use MARLIN-BUGFIX-2.0.X

### Bug Timeline

when its homing ...

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.0.x (Jul 31 2021 13:53:21) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff Cap:SERIAL_XON_XOFF:0 Cap:BINARY_FILE_TRANSFER:0 Cap:EEPROM:0 Cap:VOLUMETRIC:1 Cap:AUTOREPORT_POS:0 Cap:AUTOREPORT_TEMP:1 Cap:PROGRESS:0 Cap:PRINT_JOB:1 Cap:AUTOLEVEL:0 Cap:RUNOUT:0 Cap:Z_PROBE:0 Cap:LEVELING_DATA:0 Cap:BUILD_PERCENT:0 Cap:SOFTWARE_POWER:0 Cap:TOGGLE_LIGHTS:0 Cap:CASE_LIGHT_BRIGHTNESS:0 Cap:EMERGENCY_PARSER:0 Cap:HOST_ACTION_COMMANDS:0 Cap:PROMPT_SUPPORT:0 Cap:SDCARD:0 Cap:REPEAT:0 Cap:SD_WRITE:0 Cap:AUTOREPORT_SD_STATUS:0 Cap:LONG_FILENAME:0 Cap:THERMAL_PROTECTION:1 Cap:MOTION_MODES:0 Cap:ARCS:1 Cap:BABYSTEPPING:0 Cap:CHAMBER_TEMPERATURE:0 Cap:COOLER_TEMPERATURE:0 Cap:MEATPACK:0

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
