### ISSUE TITLE
[BUG] G29 S0 causes reboot on Ender 3 Max

### ISSUE THREAD

**Issue by KodeMunkie** [MarlinFirmware/Marlin#22472]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Using new Ender 3 Max with "3D Touch" BTouch clone.
G29 S0 reboots on the Ender 3 Max (symptoms same as #20449, #20510 does not fix). I am currently using the bugfix-2.0.x branch. 

### Bug Timeline

Installed probe for first time 2021-07-30, then built Marlin from bugfix source.

### Expected behavior

Mesh data to be returned.

### Actual behavior

Printer reboots and disconnects from Octoprint.

### Steps to Reproduce
G28
G29
G29 S0

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.0.x (Jul 31 2021 01:41:07) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Ender-3 Max EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

### Printer model

Creality Ender 3 Max

### Electronics

Stock - 4.2.2 mainboard with clone BLTouch "3D Touch"

### Host Software

OctoPrint

### Additional information & file uploads

Logs just show G28, G29 S0 because I've already levelled/probed 5x5 grid. The same occurs if I do G28, G29, M500, G29 S0
[logsAndConfig.zip](https://github.com/MarlinFirmware/Marlin/files/6910890/logsAndConfig.zip)

**Comment by KodeMunkie** [comment]
On a related note... although it should not reboot part of this may be user error.
Because I previously used manual levelling I have been using G29 S0 to retrieve the mesh report as per [https://marlinfw.org/docs/gcode/G029-mbl.html](https://marlinfw.org/docs/gcode/G029-mbl.html)
G29 S0 on bilinear will set the travel speed instead as per [https://marlinfw.org/docs/gcode/G029-abl-bilinear.html](https://marlinfw.org/docs/gcode/G029-abl-bilinear.html)
Is "M420 V1" the preferred way to get the mesh topology?  If so, a footnote on the G29 ABL page mentioning to use it would be useful (nb. I was using the Bed Visualiser plugin in Octoprint which required this data and had skimmed the ABL page and knew from previously manual levelling G29 S0 was the command to use).

**Comment by KodeMunkie** [comment]
Is it possible to triage this bug please @thinkyhead @thisiskeithb (somehow I managed to add it without the bug label)?

**Comment by thinkyhead** [comment]
I have pushed a patch to `bugfix-2.0.x` that should prevent `S0` from trashing the probing feedrate. Please test to see if it fixes the crashing issue.

**Comment by KodeMunkie** [comment]
This fixes the crashing issue but starts an ABL from the point the probe is at resulting in the probe crashing off the end of the bed if (for example) z homed in the middle of the bed before G29 S0 called. Nb. does not crash off bed if a G29 has just finished before the G29 S0 - starts the G29 normally.
