### ISSUE TITLE
[FR] 9 Linear Axes

### ISSUE THREAD

**Issue by DerAndere1** [MarlinFirmware/Marlin#22488]
### Is your feature request related to a problem? Please describe.

Currently Marlin supports up to LINEAR_AXES 6. I heared of a custom printer that is built with more than 6 axes for which Marlin cannot be used at the moment. Implementation was started at https://github.com/DerAndere1/Marlin/pull/49 but that is outdated and we could not get the endstops to work so far. See related discussions at https://github.com/DerAndere1/Marlin/issues/47 and https://github.com/DerAndere1/Marlin/issues/44#issuecomment-856514731 . 

### Are you looking for hardware support?

Would be great to support all stepper drivers that are supported in current Marlin. Support for displays is optional for now.

### Describe the feature you want

 It would be nice to expand Marlin to up to 9 fully fledged non-extruder axes. Number of axes and axis names should be configurable. To see what places have to change in code, see the addition of 6 axis support (https://github.com/MarlinFirmware/Marlin/pull/19112).

**Comment by ellensp** [comment]
Can I respectfully request that 6 axis gets finished first?

Ie G2/G3 work as expected with 6 axis
Also machines types other than Cartesian work with 6 axis.  In particular CORE(XY|YZ|YX| etc)

**Comment by DerAndere1** [comment]
I explicitly do NOT assign myself to the task of audding 9 axis support. Anyone who Does should indeed thoroughly test and Improve things for 3-6 axes, first.

**Comment by thinkyhead** [comment]
Truly man, 'tis a great task.

**Comment by DerAndere1** [comment]
7th axis (internally called M_AXIS) is working now with BED_LEVELING_3POINT, so you can now test `XYZUVW A E` or more axes. An interested person can try to rebase the code from my branch https://github.com/DerAndere1/Marlin/tree/9axis_pull onto https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x and report the outcome

**Comment by DerAndere1** [comment]
9 axes plus extruders are compiling. A 10th axis is included for fun. 
I wait until the rework of G2 / G3 PR is merged, then I can assign myself to the task of rebasing my branch.

**Comment by ellensp** [comment]
Since this was just merged, we can close this
