### ISSUE TITLE
[BUG] My Ender 3 Pro won't home z or level bed

### ISSUE THREAD

**Issue by coo-p048** [MarlinFirmware/Marlin#22483]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have been working on making a bltouch and filament run-out sensor firmware for my Ender 3 Pro, with the upgraded 4.2.7 silent board and bltoutch with everything else stock, but every time I give the printer the compiled firmware, it won't home all axis's. 
I used the Configuiration.h, Configuration_adv.h, _Bootscreen.h, Statusscreen.h, and Version.h from the Ender 3 Pro V4.2.7 base configuration folder. 
The folowing changes were in Configuration.h. 
Changing printer name to Coop's Ender  3 Pro 
un-commenting BLTOUCH
un-comenting AUTO_BED_LEVELING_BILINEAR
un-comenting FILAMENT_RUNOUT_SENSOR
un-commenting Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
un-commenting USE_PROBE_FOR_Z_HOMING
changing NOZZLE_TO_PROBE_OFFSET to { 40, 5, 0 }
un-commenting Z_SAFE_HOMING, changing EXTRUDE_MAXLENGTH to 500
and un-commenting NOZZLE_PARK_FEATURE. 
The folowing changes were to Configuration_adv.h. 
Un-commenting LCD_SET_PROGRESS_MANUALLY
un-commenting ADVANCED_PAUSE_FEATURE
changing FILAMENT_CHANGE_UNLOAD_LENGTH   to   340
and changing FILAMENT_CHANGE_FAST_LOAD_LENGTH   to  350.
I use STM32F103RET6_creality as my environment for Auto Build Marlin. 

Thank you,
Cooper Thorne

### Bug Timeline

07/28/2021 through now

### Expected behavior

I expected it to extend the probe and move z down to the bed and retracting the probe when it hits the bed.

### Actual behavior

It extended the probe then retracted it half a second later, even though it wasn't even close to the bed. 

### Steps to Reproduce

1. Get the base configuration.h, configuration_adv.h, _bootscreen.h and _statusscree.h for the Creality Ender 3 Pro with v4.2.7 board from Marlin's configuration files for 2.0.9.1.
2. Copy those files to the Marlin folder in the Marlin 2.0.9.1 Firmware zip
3. Change the folowing changes to the Configuration.h file in vscode.  Changing printer name to Coop's Ender  3 Pro, un-commenting BLTOUCH, un-comenting AUTO_BED_LEVELING_BILINEAR, un-comenting FILAMENT_RUNOUT_SENSOR, un-commenting Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN, un-commenting USE_PROBE_FOR_Z_HOMING, changing NOZZLE_TO_PROBE_OFFSET to { 40, 5, 0 }, un-commenting Z_SAFE_HOMING, changing EXTRUDE_MAXLENGTH to 500, and un-commenting NOZZLE_PARK_FEATURE. 
4. Change the folowing changes to the Configuration_adv.h file in vscode. Un-commenting LCD_SET_PROGRESS_MANUALLY, un-commenting ADVANCED_PAUSE_FEATURE, changing FILAMENT_CHANGE_UNLOAD_LENGTH   to   340, and changing FILAMENT_CHANGE_FAST_LOAD_LENGTH   to  350.
5. Use Auto Build Marlin to compile the firmware using the STM32F103RET6_creality environment.
6. Retreive the compiled firmware and send it to a Ender 3 pro with the v4.2.7 Silent board installed and a bltouch installed.
7. Then try to auto home the printer.

### Version of Marlin Firmware

Marlin 2.0.9.1

### Printer model

Creality Ender 3 Pro

### Electronics

Creality V4.2.7 Silent board

### Add-ons

Bltouch

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

I couldn't for some reason add a zip file, so I just listed my changes.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
