### ISSUE TITLE
[BUG] Compile error if default_envs = mks_robin_nano_v3_usb_flash_drive_msc

### ISSUE THREAD

**Issue by McDAK33** [MarlinFirmware/Marlin#22491]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

In fact, the essence of the error is in the title. For several weeks I can not compile the firmware for MKS Robin NANO V3 in msc configuration.
![Error](https://user-images.githubusercontent.com/80269041/127900802-982c5064-23d3-410d-aa08-2c85637826cd.jpg)

### Bug Timeline

Several weeks.

### Steps to Reproduce

In platformio.ini, define default_envs = mks_robin_nano_v3_usb_flash_drive_msc.

### Version of Marlin Firmware

bugfix-2.0.x (2021-08-02)

### Electronics

MKS Robin NANO V3

**Comment by ellensp** [comment]
The error messages you list is normally because you have a serial port set to 0 (or another invalid number).  Further up is the message
"error: #error "SERIAL_PORT must be from 1 to 6. You can also use -1 if the board supports Native USB."

**Comment by McDAK33** [comment]
> Сообщения об ошибках, которые вы перечисляете, обычно связаны с тем, что для последовательного порта установлено значение 0 (или другой недопустимый номер). Далее идет сообщение
> «error: #error» SERIAL_PORT должен быть от 1 до 6. Вы также можете использовать -1, если плата поддерживает Native USB ».

I have been using the MKS Robin nano v3 board for over half a year and have always used SERIAL_PORT -1. Now I have the firmware 2.0.9.1 from "2021-06-27" working. The problem appeared in the latest versions.

**Comment by ellensp** [comment]
No Configs so having to guess at what you may or may not have set.

**Comment by ellensp** [comment]
Give this new build env a try in ini/stm32f4.ini  (replaces current env:mks_robin_nano_v3_usb_flash_drive_msc )
It compiles. but cant test at present.

```
[env:mks_robin_nano_v3_usb_flash_drive_msc]
platform          = ${common_stm32.platform}
extends           = env:mks_robin_nano_v3_usb_flash_drive
build_flags       = ${env:mks_robin_nano_v3_usb_flash_drive.build_flags}
                    -DUSBD_USE_CDC_MSC
build_unflags     = -DUSBD_USE_CDC

```

My test Configs 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6921164/Configuration.zip)

**Comment by McDAK33** [comment]
I did not attach the configuration files because the error occurred with minimal changes to the base configuration, concerning only the board type.
After making the changes you suggested in the stm32f4.ini file, the compilation finished without errors. I will try the firmware on my printer soon.
Thank you very much.

**Comment by alexandremstf** [comment]
I had the same problem, after making the changes @ellensp suggested, i could compile without error and my printer is working properly, many thanks.
