### ISSUE TITLE
Z homing with Bltouch not working and gives a STOP error

### ISSUE THREAD

**Issue by mzgourovski** [MarlinFirmware/Marlin#22507]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I am in the middle of adding CR-Touch to my printer (crtouch is bltouch, jut creality's form of it)
I'm not sure what is wrong, but whenever I turn on the printer, the probe automatically deploys and stays deployed. So then I tried to do autohome, and it homed x and y, but when it got to z, it gave me an error code "STOPPED". so then I tried to do the bed leveling, and then after homing x and y, it gave me another error message saying "home z first"
I am very confused on what is happening, but i really would appreciate some help.
I found this post, but not sure if it will help. Ive got the creality CR-10s(its got the v2.2.1 silent board)
MarlinFirmware/Marlin#13089

### Version of Marlin Firmware

1.1.9

### Printer model

Creality CR-10s

### Your Slicer

Cura

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
