### ISSUE TITLE
[BUG] SINGLENOZZLE breaks fan speed control

### ISSUE THREAD

**Issue by basilfx** [MarlinFirmware/Marlin#22512]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Current Marlin version [always](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/module/temperature.cpp#L372) sets `fan = 0` if `#define SINGLENOZZLE` in `Temperature::set_fan_speed`. That means that if we have a [chamber fan](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/module/temperature.cpp#L1464) (or any other fan), it will not work, and FAN0 is always chosen for any invocation of `Temperature::set_fan_speed`.

Commenting `#define SINGLENOZZLE` makes it work as expected.

### Bug Timeline

This was introduced by #19152

### Expected behavior

Fan PWM control (e.g. chamber) should work with `#define SINGLENOZZLE`.

### Actual behavior

- When changing the enclosure temperature, it modifies FAN0.
- When changing any the speed of any selectable fan in the temperature menu, FAN0 gets updated instead.

### Steps to Reproduce

1. Configure Marlin 2.0.9.1 with `#define SINGLENOZZLE` and a `FAN2_PIN` for chamber cooling.

### Version of Marlin Firmware

2.0.9.1

### Printer model

AM8

### Electronics

SKR Pro V1.1

**Comment by thinkyhead** [comment]
Now patched! Please test `bugfix-2.0.x` and if the issue is fixed then this can be closed.

**Comment by basilfx** [comment]
This fixes it for me. Thanks!
