### ISSUE TITLE
[BUG] Incorrect work PT1000 with 4K7 pullup & strange table(s) 

### ISSUE THREAD

**Issue by trengtor** [MarlinFirmware/Marlin#22517]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/module/thermistor/thermistor_1047.h

Current bugfix ­- the same. Table looks as

  PtLine(  0, 1000, 4700),
  PtLine( 50, 1000, 4700),
  PtLine(100, 1000, 4700),
  PtLine(150, 1000, 4700),
  PtLine(200, 1000, 4700),
  PtLine(250, 1000, 4700),
  PtLine(300, 1000, 4700),
  PtLine(350, 1000, 4700),
  PtLine(400, 1000, 4700),
  PtLine(450, 1000, 4700),
  PtLine(500, 1000, 4700)

May be it must be as bottom table?

  PtLine(  0, 1000, 4700),
  PtLine( 50, 1194, 4700),
  PtLine(100, 1385, 4700),
  PtLine(150, 1535.8, 4700),
  PtLine(200, 1758.8, 4700),
  PtLine(250, 1941, 4700),
  PtLine(300, 2120.5, 4700),
  PtLine(350, 2297.2, 4700),
  PtLine(400, 2470.9, 4700),
  PtLine(450, 2641.8, 4700),
  PtLine(500, 2809.8, 4700)

### Version of Marlin Firmware

latest bugfix 2.x

**Comment by ellensp** [comment]
no. PtLine is not the same as OV macro as used in conventional thermistor tables

```CPP
// Pt1000 and Pt100 handling
//
// Rt=R0*(1+a*T+b*T*T) [for T>0]
// a=3.9083E-3, b=-5.775E-7
#define PtA 3.9083E-3
#define PtB -5.775E-7
#define PtRt(T,R0) ((R0) * (1.0 + (PtA) * (T) + (PtB) * (T) * (T)))
#define PtAdVal(T,R0,Rup) (short)(1024 / (Rup / PtRt(T, R0) + 1))
#define PtLine(T,R0,Rup) { OV(PtAdVal(T, R0, Rup)), T }
```
