### ISSUE TITLE
[FR] Galvo print SLA

### ISSUE THREAD

**Issue by DongNT8** [MarlinFirmware/Marlin#22521]
### Is your feature request related to a problem? Please describe.

no

### Are you looking for hardware support?

yes

### Describe the feature you want

Hello everyone.

I want to design a printer 3D SLA,
use :  
Galvo (axis x,y) use DAC 
create wipers axis z
fimware 2.x.x

PLS help me. thanks!

**Comment by DongNT8** [comment]
Currently, the price of SLA printers on the market has a huge difference.
i want to design it

**Comment by thinkyhead** [comment]
Duplicate of #11117

**Comment by thinkyhead** [comment]
For best results getting developer help, please visit the Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by DongNT8** [comment]
oke.
thanks
