### ISSUE TITLE
[BUG] 2.0.9.1 coil short circuit

### ISSUE THREAD

**Issue by sjirafje** [MarlinFirmware/Marlin#22523]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I downloaded Kersey Fabrications prebuilt 2.0.9.1 for E5+with BTT SKR V1.4 Turbo, TMC2208 and Dual Z. And flashed on my Ender 5 plus with Biqu H2 extruder but the printer keeps halting on the first layer with the following error:

> E driver error detected: 0x1074921488.0000000000000000
> coil short circuit
> echo:Driver error
> Error:Printer halted. kill() called!
> [ERROR] Error:Printer halted. kill() called!
> 
> //action:poweroff

This happens with every print no mater if printing from SD of from Pronterface.

Going back to a previous version (2.0.7.2) solves the issue.

### Bug Timeline

new

### Version of Marlin Firmware

2.0.9.1

### Printer model

Creality Ender 5 Plus

### Electronics

SKR 1.4 Turbo, BTT TFT35, 

### Add-ons

TMC2208, Biqu H2 Extruder, dual Z

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

This post seems to describe the same problem: https://www.reddit.com/r/BIGTREETECH/comments/oadhqu/e_driver_error_detected_coil_short_circuit/

**Comment by thisiskeithb** [comment]
> I downloaded Kersey Fabrications prebuilt 2.0.9.1 for E5+with BTT SKR V1.4 Turbo

We can’t support forks of Marlin, sorry.

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
