### ISSUE TITLE
[BUG] MINTEMP on SKR 1.4 with MAX6675

### ISSUE THREAD

**Issue by Caroma97** [MarlinFirmware/Marlin#22533]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

MAX6675 is not working, either in the bugfix-2.0.x 2021-08-06 nor in the normal 2.0.9.1 release.

Hardware:
SKR 1.4 LPC1768
TMC2209 driver with sensorless homing
MAX6675 with a Type-K tempsensor
 
**Case 1, 2.0.9.1 release:**

Configuration.h:
```C++
#define SERIAL_PORT -1
#define SERIAL_PORT_2 3
#define MOTHERBOARD BOARD_BTT_SKR_V1_4
#define TEMP_SENSOR_0 -2
#define EEPROM_SETTINGS
#define SDSUPPORT
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```

pins_BTT_SKR_common.h:
```C++
#define BOGUS_TEMPERATURE_GRACE_PERIOD    10000
#define MAX6675_SS_PIN   P1_01
```

MAX6675 connected to:
```C++
CS     P1_01
SO     MISO Pin E1  (Pin on E1 driver slot) 
SCK    SCK Pin E1  (Pin on E1 driver slot) 
VCC and GND
```

Compilation - no errors
firmware.bin >> sd card>> SKR>> restart >> Sensor shows 48°, after ~1 second 24° , after 10 seconds MINTEMP E1

**Case 2, bugfix-2.0.x 2021-08-06:**

Configuration.h:
```C++
#define SERIAL_PORT -1
#define SERIAL_PORT_2 3
#define MOTHERBOARD BOARD_BTT_SKR_V1_4
#define TEMP_SENSOR_0 -2
#define EEPROM_SETTINGS
#define SDSUPPORT
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```

Configuration_adv.h:
```C++
#define TEMP_SENSOR_FORCE_HW_SPI
```

pins_BTT_SKR_common.h:
```C++
#define BOGUS_TEMPERATURE_GRACE_PERIOD    10000
#define MAX6675_SS_PIN   P1_01
```

MAX6675 connected to:
```C++
CS     P1_01
SO     MISO Pin E1  (Pin on E1 driver slot) 
SCK    SCK Pin E1  (Pin on E1 driver slot) 
VCC and GND
```

Compilation - no errors
firmware.bin >> sd card>> SKR>> restart >> Sensor shows 48°, after ~1 second 512° , after 10 seconds MINTEMP E1

### Expected behavior

MAX6675 working on SKR 1.4

### Actual behavior

freeze of mainboard / Err: MINTEMP: E1 PRINTER HALTED Please Reset

### Steps to Reproduce

Enable MAX6675 (-2) as tempsensor

### Version of Marlin Firmware

bugfix-2.0.x 2021-08-06 and 2.0.9.1

### Printer model

Dremel 3D40 with SKR 1.4

### Electronics

SKR 1.4

### Additional information & file uploads

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/6951086/Config.zip)

**Comment by thinkyhead** [comment]
Duplicate of #22526

**Comment by kevinallein** [comment]
Hello, I see you retrofitted a Dremel 3D40 with a different control board. I need to do the same. However how did you solve the problem, that the printhead uses a ribbon cable and none of the standard boards seem to have such a connector ?
Thanks

**Comment by Caroma97** [comment]
I created a small custom PCB but I never printed it.
I dont have enough time at the Moment.
You can use my Gerber/KiCAD project files if you want to print it by yourself (respectively let it print).
[Dremel 3D40.zip](https://github.com/MarlinFirmware/Marlin/files/7313672/Dremel.3D40.zip)
