### ISSUE TITLE
[BUG] (Duplication mode in IDEX not working properly)

### ISSUE THREAD

**Issue by atharvbadkas** [MarlinFirmware/Marlin#22538]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

###  Description

Hello,
I have an ender 3 pro with extended X axis(400mm).
I have installed BTT Idex kit with BTT RRF E3 V1.1 With Expansion board.

I also have configured marlin in Dual X carriage mode.
I'm attaching my config files.
Please check if I have missed something there.
Thanks

### Expected behavior

In duplication mode,
After print starts, X2 hotend should come to X110 location(offset location M605 R0 X110) then both hotend start the print in sync.

In mirror mode,
After print starts, X2 hotend should come to X220 location(bed max location) and then start printing.

### Actual behavior

Dual colour mode works as expected after calibrating the X offset in print heads.

In duplication mode,
After print starts,X2 hotend grinds to X_max_endstop
Then motor stops rotating.

In Mirror mode,
After print start, X2 hotend grinds to X_max_endstop
Then start printing above LCD(does not come to bed at X220 location)

### Steps to Reproduce

_No  response_

### Version of Marlin Firmware

V2.0.9.1 also have tried on latest bugfix version

### Printer model

Creality Ender 3 pro

### Electronics

Bigtreetech RRF E3 V1.1 with Expansion board

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by atharvbadkas** [comment]
[WhatsApp Business Documents.zip](https://github.com/MarlinFirmware/Marlin/files/6952292/WhatsApp.Business.Documents.zip)

My config files

**Comment by atharvbadkas** [comment]
Hello,
Can anyone please check my config files and let me know that my configs are right or wrong?

Because I have seen exact setup like mine working normally on Marlin 2.0.6.(from https://enderidex.com/)
Thanks

**Comment by thinkyhead** [comment]
The configurations look okay to me. This could certainly just be a bug. IDEX tends to be a work in progress because only a few contributors have one.

Would you be able to test some `bugfix-2.0.x` commits to narrow down when the problem started?

The strategy is to find a commit from some point in the "distant" past where the feature works. Then, test a commit from halfway between that date and today…. And then you keep going to the commit half-way in between your "known to work" commit and your "known to be broken" commit until you find the exact day where it broke.

If you started from a point 256 days in the past, it should take no more than 8 tests to find the exact day when it broke.

**Comment by atharvbadkas** [comment]
Sure thing,
I can test some bugfix version from past 256 days as you mentioned.

Just tell me what files I have to change regarding the motherboard.
Files for BTT RRF E3 V1.1, for example pins or some lines in sanity check

**Comment by thinkyhead** [comment]
You should just be able to use your same configuration options, maybe turning off some optional things for simplicity. The main thing is just to get IDEX enabled and test the behavior with tool-changing and make sure it moves properly in the different modes. Enable `DEBUG_LEVELING_FEATURE` and send `M111 S247` to get maximum logging to the console.

**Comment by InsanityAutomation** [comment]
I got my IDEX machine back up to date and on the workbench last weekend, needed a new heater cartridge for one of the heads. Hoping to dig in this weekend with it working again after the new heater is in.

**Comment by shtaXveed** [comment]
any ideas on this yet?

**Comment by atharvbadkas** [comment]
One of my friend had discussed this with @InsanityAutomation on discord. He somehow made it work using Marlin 2.0.6. but not fully functional.
 He's Marlin folder(https://drive.google.com/file/d/1ZRwMiPPJaXwuuIlOZM1mU-uPcQRw3obD/view?usp=drivesdk)
I'm also working on this and trying to solve some errors I'm getting while compiling
![240895536_392099762311134_1592700892363288211_n (1)](https://user-images.githubusercontent.com/57062058/132971882-784a77bd-9c2d-4b9a-9418-d638c7d117ec.jpg)

**Comment by thinkyhead** [comment]
I downloaded and compiled your folder from the Google drive, and got no errors. Try deleting your `.pio` folder and your `$HOME/.platformio/.cache` folder and build again.

**Comment by thinkyhead** [comment]
> any ideas on this yet?

Someone with IDEX hardware will need to track down the exact cause. There are a lot of issues to go through and I would just be taking stabs in the dark trying to figure out the issue. But of course… please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands today. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by whoishack** [comment]
Not resolved in the latest bugfix unfortunately. Someone else please confirm but X2 for me still smashes into the endstop at the end of a home sequence when switching IDEX modes

**Comment by thisiskeithb** [comment]
@InsanityAutomation: Can you look at this?

**Comment by InsanityAutomation** [comment]
I got the machine back together and some other issues on it fixed a bit over a week ago intending to chase exactly this, so yes as soon as commercial commitments are done this is first on my list.

**Comment by shtaXveed** [comment]
so I've been messing around a little 2.0.9 makes the right hotend ram the right endstop, instead of traveling towards center. and 2.0.8.1 makes the left hotend ram the endstop while the right hotend travels to the center. 

but if I assign duplication mode from my start gcode it will start fine if I start the print in full control. I believe there also needs to be a bypass for the comatose extruder issue in idex modes. (disable inactive extruder makes e1 not move in idex)

**Comment by shtaXveed** [comment]
note in 2.0.8.1 it prints fine after the right hotend reaches its start position. just grinds while the right hotend is moving to position

**Comment by imp67** [comment]
I see similar issues to shaXveed (above) using build 2.0.8.2.
The same work around in gcode avoids the issue.
E1 does not extrude if DISABLE_INACTIVE_EXTRUDER is defined.
In duplication mode the heads home, then E0 tries to move LEFT in synch with E1 at the start of the print grinding the belt. As it's already homed on the left at that point, the head alignment is maintained and the print proceeds OK from that point.
In mirror mode, the belt grinding doesn't occur, and the print is OK.

**Comment by Jerronimo2001** [comment]
I have the same problem with grinding the belt by moving E0 in start of duplication mode (2.0.8.2).

**Comment by atharvbadkas** [comment]
> I got the machine back together and some other issues on it fixed a bit over a week ago intending to chase exactly this, so yes as soon as commercial commitments are done this is first on my list.

@InsanityAutomation 
Hi mate,
Did you found the issue?
Why does it causing?

**Comment by thisiskeithb** [comment]
#22914 was merged. Closing.
