### ISSUE TITLE
[FR] download all documentation, gcodes, as pdf or html single file package, opengpl that too

### ISSUE THREAD

**Issue by goofyseeker311** [MarlinFirmware/Marlin#22540]
### Is your feature request related to a problem? Please describe.

cant download all things related for offline use

### Are you looking for hardware support?

no

### Describe the feature you want

all things marlin should be simply downloadable, single button, for documentation, for offline use

### Additional context

https://marlinfw.org/meta/gcode/ and you notice the problem, no download button, intentional, eh

**Comment by ellensp** [comment]
The entire thing is available for download at https://github.com/MarlinFirmware/MarlinDocumentation

**Comment by goofyseeker311** [comment]
was not obvious

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by goofyseeker311** [comment]
there is no binary of the documentation, reopen, please

**Comment by goofyseeker311** [comment]
> The entire thing is available for download at https://github.com/MarlinFirmware/MarlinDocumentation

no the final documentation is not in there, wrong answer

**Comment by ellensp** [comment]
No I will not reopen this. 

There are many reasons for this. but the most important is that this FR should be created in the MarlinDocumentation repository, not the Marlin source code repository.

**Comment by ellensp** [comment]
read the readme.
https://github.com/MarlinFirmware/MarlinDocumentation/blob/master/README.md

The Documentation web site is generated from the https://github.com/MarlinFirmware/MarlinDocumentation repository.

**Comment by goofyseeker311** [comment]
the main site needs to have direct full download of the documentation in the main download section of the main site, thats why Im not obeying, ever

**Comment by goofyseeker311** [comment]
this that you removed the documentation from being online, and I did not have the build environment for the documentation

**Comment by goofyseeker311** [comment]
simply I dont care if you have the documentation online or that I can download the source, I need the third option, locally, now

**Comment by goofyseeker311** [comment]
women cannot understand law issues, even if they claim to be experts of the law
