### ISSUE TITLE
[BUG] Extruder stops when LIN_ADVANCE is enabled and K > 0

### ISSUE THREAD

**Issue by richardklingler** [MarlinFirmware/Marlin#22552]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When activating LIN_ADVANCE and send a k value > 0, the extruder stops completely.
Setting back K to 0 returns to normal operation.

### Bug Timeline

Old, but still persist

### Expected behavior

The extruder shouldn't stop operation when K is greater than 0.

### Actual behavior

Extruder stop when setting K to > 0.

### Steps to Reproduce

Activate LIN_ADVANCE
Send M900 K0.2

### Version of Marlin Firmware

2.0.9.1

### Printer model

Creality Ender-5 Plus

### Electronics

BTT SKR v1.3 with TMC2208 stepper drivers

### Add-ons

BLTouch 3.1

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Additional information & file uploads

[k_factor_pattern.zip](https://github.com/MarlinFirmware/Marlin/files/6966931/k_factor_pattern.zip)

**Comment by ellensp** [comment]
TMC2208s + LA does not work. It is a hardware limitation of the 2208's Get TMC2209's or disable LA
