### ISSUE TITLE
[BUG] EVENT_GCODE_SD_ABORT renaming

### ISSUE THREAD

**Issue by ansonl** [MarlinFirmware/Marlin#22566]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Gcode defined under `EVENT_GCODE_SD_ABORT` is triggered for any Abort/Stop triggered by the Marlin UI when printing from both SD card and remote server. Abort Gcode triggering for a remote print actually ends up being good because any custom stop commands like retraction (to stop oozing) are triggered!

Since `EVENT_GCODE_SD_ABORT `and associated `abort_sd_printing` can be triggered by events that are not necessarily a print from SD card, it would be less misleading if it was renamed to be more clear. Either that or the comment for this define in Configuration_adv.h should note this additional behaviour. 

Ex: `EVENT_GCODE_SD_ABORT` → `EVENT_GCODE_USER_ABORT`

### Bug Timeline

Pre-existing issue

### Expected behavior

Based on the name `EVENT_GCODE_SD_ABORT`, location in SD code in Configuration_adv.h, and configuration comment in Configuration_adv.h :
> G-code to run on SD Abort Print

I expected that the defined abort Gcode to only run when cancelling an SD print. 

### Actual behavior

The defined abort Gcode runs when stopping any print, whether from SD card or remotely fed Gcode. 

### Steps to Reproduce

1. Start a print remotely (ex: octoprint)
2. Stop print using Marlin UI
3. EVENT_GCODE_SD_ABORT code is run.

### Version of Marlin Firmware

2.0.9.1

### Printer model

Ultimaker Original+

### Electronics

Stock

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by thinkyhead** [comment]
There is only one place where `EVENT_GCODE_SD_ABORT` applies, and that is here…

```cpp
#if ENABLED(SDSUPPORT)
  inline void abortSDPrinting() {
    . . .
    #ifdef EVENT_GCODE_SD_ABORT
      queue.inject_P(PSTR(EVENT_GCODE_SD_ABORT));
    #endif
    . . .
  }
#endif
```

The only way that `abortSDPrinting` is invoked is…
```cpp
if (card.flag.abort_sd_printing) abortSDPrinting();
```

The only way that `card.flag.abort_sd_printing` is set is…
```cpp
static inline void abortFilePrintSoon() { flag.abort_sd_printing = true; }
```

If `card.abortFilePrintSoon()` is being called when `IS_SD_PRINTING()` is false, that is a bug. One potential solution is to change the function to this:
```cpp
static inline void abortFilePrintSoon() { flag.abort_sd_printing = flag.sdprinting; }
```
