### ISSUE TITLE
[BUG] (Z safe homing acceleration)

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#22569]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When performing an auto home with the Z safe homing option enabled, there is a large acceleration (may be speed) along the X and Y axes.
For manual movements, the accelerations are normal, as defined by the configuration file.

Board: MKS Robin nano v.2 with MKSUI interface

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6987758/Configuration.zip)

Bug video: https://disk.yandex.ru/i/u-x7YjTbbk5Y5g

**Comment by thisiskeithb** [comment]
[I'm also seeing the same thing](https://www.youtube.com/watch?v=rILJcsDILA4), after updating to a recent `bugfix-2.0.x` commit. I found some older g-code thinking it was slicer related, but the behaviour is the same.

**Comment by mayy42** [comment]
I have the same problem with the 2.0.9.1 from Aug 10, 2021.
My printer can not handle the acceleration and the y-axis stops after half of the way and makes strange noises.

**Comment by roel8032** [comment]
Please try M501 before G28 (G29).

**Comment by Malderin** [comment]
> Please try M501 before G28 (G29).

without changes

**Comment by ManuelMcLure** [comment]
I’m seeing this as well with recent bugfix-2.0.x (around a couple days old).

**Comment by ManuelMcLure** [comment]
My gut feeling is that it is due to 9130f58f3f553584278ec716c617005b9e03cb49

**Comment by benlye** [comment]
Same problem here.

> My gut feeling is that it is due to [9130f58](https://github.com/MarlinFirmware/Marlin/commit/9130f58f3f553584278ec716c617005b9e03cb49)

Indeed, reverting those changes fixes the crazy XY moves when Z safe homing.

**Comment by thisiskeithb** [comment]
https://github.com/MarlinFirmware/Marlin/pull/22574 was merged. Closing.
