### ISSUE TITLE
Unable to see menu or unload filament when printing pause print

### ISSUE THREAD

**Issue by yomyong2** [MarlinFirmware/Marlin#22567]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I added the M600 code to the G-code. However, if you accept the M600 on the printer LCD, the filament will not be unloaded. Filaments are only being uploaded. + Why can't I see the printer menu when I pause the print...?

### Bug Timeline

Originally, my printer didn't have an LCD, but when I added the Pause prit function after installing the LCD,

### Expected behavior

Unloading and Reloading Filaments

### Actual behavior

Filaments cannot be unloaded, only uploadable

### Version of Marlin Firmware

2.0.9.1

### Printer model

sondori PICO

### Electronics

LCD

### Your Slicer

Slic3r

### Host Software

SD Card (headless)

### Additional information & file uploads

![화면 캡처 2021-08-13 221250](https://user-images.githubusercontent.com/72597473/129443558-813fe7a6-36ac-4cd9-b272-eb06e51c1d93.png)
![화면 캡처 2021-08-13 221246](https://user-images.githubusercontent.com/72597473/129443559-738146cf-30b5-455c-a7fe-c774944ae46d.png)

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
