### ISSUE TITLE
[FR] Manual Bed Levelling Should require preheat for bed and nozzle

### ISSUE THREAD

**Issue by Barrnet** [MarlinFirmware/Marlin#22576]
### Describe the feature you want

Like for the Automatic Bed Levelling, the Mesh Bed Levelling should preheat bed and nozzle (maybe at only 160 Celsius for not having oozing problem) if PREHEAT_BEFORE_LEVELING is defined.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22549

**Comment by Barrnet** [comment]
Is not a duplicate. I was talking about Mesh Bed Levelling, not Bed Tramming.

**Comment by ardenpm** [comment]
Agreed, it looks like `PREHEAT_BEFORE_LEVELING` doesn't apply for `MESH_BED_LEVELING` and that should definitely be possible. I think this should be re-opened given it is not a duplicate of the tramming question.

**Comment by sarvenn** [comment]
Agree. I solved this setting a preheat selection 150C / 60C.
