### ISSUE TITLE
Temperature constant swing even at room temperature (hotend and bed simultaneous)

### ISSUE THREAD

**Issue by joaocqmiranda** [MarlinFirmware/Marlin#22570]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

There is any feature that prevent this from happening?

I already checked voltage of power supply that its constante and mofset

![image](https://user-images.githubusercontent.com/70608094/129492682-8808c005-e5f0-410e-a2cd-1d1b1600e99d.png)

### Version of Marlin Firmware

2.0.9

### Printer model

Anet A6

### Electronics

 SKR 2 REV A

### Add-ons

BL touch, Run out filament

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by ellensp** [comment]
Your board or thermistor wires are noisy. This is a hardware issue, not firmware.
