### ISSUE TITLE
[BUG] Can't compile for Ender 3 V2 with AUTO_BED_LEVELING_(BI)LINEAR uncommented.

### ISSUE THREAD

**Issue by lefterisgar** [MarlinFirmware/Marlin#22588]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

PlatformIO refuses to compile with the following error(s):
```
Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\e3v2\creality\dwin.cpp.o
Marlin\src\lcd\e3v2\creality\dwin.cpp: In function 'void Item_Adv_ProbeOffsets(uint8_t)':
Marlin\src\lcd\e3v2\creality\dwin.cpp:2429:33: error: too many arguments to function 'void say_probe_offs_en(uint8_t)'
 2429 |         say_probe_offs_en(0, row);
      |                                 ^
Marlin\src\lcd\e3v2\creality\dwin.cpp:567:6: note: declared here
  567 | void say_probe_offs_en(const uint8_t row) {
      |      ^~~~~~~~~~~~~~~~~
*** [.pio\build\STM32F103RET6_creality\src\src\lcd\e3v2\creality\dwin.cpp.o] Error 1
```
### Bug Timeline

It started with commit 09af42e (17-08-2021).

### Expected behavior

I expected to be able to successfully compile Marlin firmware with the options below (steps to reproduce) enabled.

### Actual behavior

Compiling .pio\build\STM32F103RET6_creality\src\src\lcd\e3v2\creality\dwin.cpp.o fails.

### Steps to Reproduce

1. Clone Marlin.
2. Import Ender 3 V2 configurations.
3. Uncomment `#define BLTOUCH`.
4. Uncomment `#define Z_SAFE_HOMING`.
3. Uncomment any of these: 
- `//#define AUTO_BED_LEVELING_3POINT`
- `//#define AUTO_BED_LEVELING_LINEAR`
- `//#define AUTO_BED_LEVELING_BILINEAR`
4. Compile Marlin.

### Version of Marlin Firmware

Latest bugfix 2.0.x

### Printer model

Creality Ender 3 V2

### Electronics

- Creality 4.2.2 mainboard (STM32F103RET6_CREALITY)
- DWIN LCD display
- BLTouch
- Filament run-out sensor

### Add-ons

BLTouch, Filament run-out sensor

### Bed Leveling

ABL Bilinear mesh

### Additional information & file uploads

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/7001251/Marlin.zip)
![image](https://user-images.githubusercontent.com/46350667/129755892-febcb493-0a36-41fb-b364-b36db4a20b90.png)

I went to line 2429 of dwin.cpp and changed it from 
`say_probe_offs_en(0, row);` to `say_probe_offs_en(row);` and it did successfully compile.

**Comment by ellensp** [comment]
This PR broke it https://github.com/MarlinFirmware/Marlin/pull/22586

**Comment by ellensp** [comment]
Issues resulting from Clean up CrealityUI and MarlinUI #22586
No change with " Followup to CrealityUI cleanup" https://github.com/MarlinFirmware/Marlin/commit/11e8cd9db938fcc5ee5c5234f148655a8f19c20d

**Comment by lefterisgar** [comment]
Well, thank you soo much!! Really appreciate your help!

**Comment by lefterisgar** [comment]
Still can't get it to compile tho...

**Comment by lefterisgar** [comment]
Closure was accidental.

**Comment by rankinstudio** [comment]
I just ran into this bug as well, any fix?

**Comment by lefterisgar** [comment]
No and I guess till the E3V2 cleanup ends we will be having a lot of issues like this...

**Comment by thinkyhead** [comment]
We'll see about "a lot." Meanwhile I can quickly patch this as soon as I get back from the grocery store.

**Comment by lefterisgar** [comment]
Nice! Accidents always happen and it's not your fault. Having to maintain such a big codebase is rocket science to me and a lot of other people... 😁 Really appreciate your job and looking forward to the end of the cleanup!
