### ISSUE TITLE
2.0.9.1 Will Not Compile for creaity v4.2.7

### ISSUE THREAD

**Issue by maycolacerda** [MarlinFirmware/Marlin#22609]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When I download and unzip 2.0.9.1, and install the configuration.h and configuration_adv.h files from the config/examples/delta/creality/ender 3 pro folder, it will not compile under Platformio under VSCode.

It throws this problem:
FileNotFoundError: [WinError 3] the system cannot find the path specified 'C:\\Users\\user\\.platformio\\packages\\framework-arduinoststm32@4.10900.200819\\variants\\MARLIN_F103Rx'

### Expected behavior

Compiled marlin. 

### Actual behavior

not compiled, showing the above error. 

### Steps to Reproduce

1). Download Marlin 2.0.9.1 and unzip it.
2) Download the configuration files from the Configurations-2.0.x\config\examples\Creality\Ender-3 Pro\CrealityV427
3) Install those files in the Marlin directory
4) Modify platformio.ini to the STM32F103RET6_creality
5) Attempt to compile

### Version of Marlin Firmware

2.0.9.1

### Printer model

Ender 3 pro

### Electronics

creality v4.2.7

### Additional information & file uploads

[Marlin-2.0.9.zip](https://github.com/MarlinFirmware/Marlin/files/7026024/Marlin-2.0.9.zip)

**Comment by thinkyhead** [comment]
Unable to reproduce the issue with 2.0.9, 2.0.9.1, or bugfix-2.0.x. Try deleting your `.pio` folder and your `$HOME/.platformio/.cache` folders before doing the build.
