### ISSUE TITLE
[BUG] (bug summary) U8glib-HAL.h: No such file or directory

### ISSUE THREAD

**Issue by dustinoff** [MarlinFirmware/Marlin#22614]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

when I try to compile I get this error
Marlin-2.0.x.7d416bd\Marlin\src\HAL\AVR\u8g_com_HAL_AVR_sw_spi.cpp:65:10: fatal error: U8glib-HAL.h: No such file or directory
 #include <U8glib-HAL.h>

### Bug Timeline

it existed in Marlin-bugfix-2.0.x.0d854d3  Do not know further back.

### Expected behavior

I expected it to compile

### Actual behavior

If I compile the virgin file, it compiles.
If I uncomment line 2347 #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
I get the error.
No other changes to the virgin zip files

### Steps to Reproduce

1. Uncomment 2347 #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER in configuration.h
2. run compile
3. 

### Version of Marlin Firmware

Marlin-2.0.x.7d416bd

### Printer model

corexy

### Electronics

arduino mega2560/Ramps 1.4

### Additional information & file uploads

file **u8g_com_HAL_AVR_sw_spi.cpp** indeed has **#include <U8glib-HAL.h>**
**U8glib-HAL.h** does not exist in the distribution.

**Comment by ellensp** [comment]
You need to install the U8glib-HAL.h library in the Arduino IDE. The same way you install all libraries in the Arduino IDE 

Menu Tools |Manage libraries.
In the filter your search field enter "u8glib-hal"
This will show just that library
Click install.
