### ISSUE TITLE
[BUG] boot loops on Malyan M200 baord with 2.x & 2.x nightly 

### ISSUE THREAD

**Issue by Injineers** [MarlinFirmware/Marlin#22620]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

**Description

Additional Information
After a LONG time (2 years maybe) fighting with this malyan m200 v1 controller & all the hoops to compile.
I am now able to compile w/o issues using Ubuntu w/ Vscode /platformio & auto build
No more need for arduino compile

Only issue is seems like 2.x & the nightly are rebooting the controller every 8-10 seconds. When it does run for those seconds before it cycles, it seems like I can move axis, so thats a plus.

Not sure what info would be needed or what, but I did come across a post that someone else had a similar issue but on a v2 & went back to 2.0.6.1 ,& it works & doesnt loop. But trying to compile that version for the v1, I get back to those old /similar issues with building with it complaining about boards.h having a include for board/board.h & it not existing**

### Bug Timeline

new

### Expected behavior

I would expect the controller not to boot loop every 8-10 seconds

### Actual behavior

system boots, stays up for about 8-10 seconds then reboots

### Steps to Reproduce

Steps to Reproduce
compile 2.x or nightly 2.x
flash

### Version of Marlin Firmware

2.x latest & 2.x nightly 

### Printer model

custom

### Electronics

Malyan m200 v1 (BOARD_MALYAN_M200)

### Add-ons

n/a

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7034431/Marlin.zip)

**Comment by ellensp** [comment]
Disable #define USE_WATCHDOG, perhaps  it will stay up long enough to provide useful errors.

**Comment by Injineers** [comment]
this can be closed. Im done F'ing with this board..lol..
bought a new one the other night with full support :)
