### ISSUE TITLE
[BUG] Creality3D V1.1.4 + MKS LCD12864A V1.0 screen not working

### ISSUE THREAD

**Issue by Kearvan** [MarlinFirmware/Marlin#22635]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

A new screen has been installed on the stock motherboard. The screen works on the SPI bus, and has contacts DOGLCD_A0, DOGLCD_CS, MOSI, SCK. On the Arduino Uno controller, the screen works correctly when using the u8glib.h library (class U8GLIB_MINI12864).
On Creality3D V1.1.4, the screen does not work. In the Configuration.h file, the screen is written as MKS_LCD12864A.
The DOGLCD_A0 pin of the screen is connected to the LCD_PINS_D4 pin (according to pins_SANGUINOLOLU_11.h).
The DOGLCD_CS pin of the screen is connected to the LCD_PINS_RS pin (according to pins_SANGUINOLOLU_11.h).
Also, to check, the MOSI pin and SCK pin of the screen were connected to the MOSI pin and SCK pin on the board. But the result turned out to be negative - the backlight, the encoder key and the beeper are working, but there is no image at all on the screen.
For verification, a definition was added:
#define DOGLCD_MOSI BEEPER_PIN
#define DOGLCD_SCK LCD_PINS_ENABLE
Defined pins were connected to the screen, but again with no result.
Tell me please, what am I doing wrong? Marlin Firmware v2.0.9.1 (bugfix)
Upload and edit via VSCode + PlatformIO

### Bug Timeline

22.08.21

### Expected behavior

I was expecting displaying information on the screen and controlling processes using an encoder.

### Actual behavior

Instead of a screen, we got a backlight panel for the machine.

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.0.x (Aug 25 2021 17:20:04) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

### Printer model

Ender 3

### Electronics

Stock motherboard (Creality3D V1.1.4) with MKS LCD12864A screen

### Bed Leveling

No Bed Leveling

### Your Slicer

Prusa Slicer

### Additional information & file uploads

M115
18:59:49.416 > FIRMWARE_NAME:Marlin bugfix-2.0.x (Aug 25 2021 17:20:04) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
18:59:49.425 > Cap:SERIAL_XON_XOFF:0
18:59:49.426 > Cap:BINARY_FILE_TRANSFER:0
18:59:49.429 > Cap:EEPROM:0
18:59:49.429 > Cap:VOLUMETRIC:1
18:59:49.429 > Cap:AUTOREPORT_POS:0
18:59:49.429 > Cap:AUTOREPORT_TEMP:1
18:59:49.430 > Cap:PROGRESS:0
18:59:49.430 > Cap:PRINT_JOB:1
18:59:49.431 > Cap:AUTOLEVEL:0
18:59:49.431 > Cap:RUNOUT:0
18:59:49.432 > Cap:Z_PROBE:0
18:59:49.432 > Cap:LEVELING_DATA:0
18:59:49.435 > Cap:BUILD_PERCENT:0
18:59:49.435 > Cap:SOFTWARE_POWER:0
18:59:49.438 > Cap:TOGGLE_LIGHTS:0
18:59:49.438 > Cap:CASE_LIGHT_BRIGHTNESS:0
18:59:49.438 > Cap:EMERGENCY_PARSER:0
18:59:49.438 > Cap:HOST_ACTION_COMMANDS:0
18:59:49.439 > Cap:PROMPT_SUPPORT:0
18:59:49.439 > Cap:SDCARD:0
18:59:49.439 > Cap:REPEAT:0
18:59:49.441 > Cap:SD_WRITE:0
18:59:49.441 > Cap:AUTOREPORT_SD_STATUS:0
18:59:49.443 > Cap:LONG_FILENAME:0
18:59:49.443 > Cap:THERMAL_PROTECTION:1
18:59:49.443 > Cap:MOTION_MODES:0
18:59:49.444 > Cap:ARCS:1
18:59:49.444 > Cap:BABYSTEPPING:0
18:59:49.446 > Cap:CHAMBER_TEMPERATURE:0
18:59:49.447 > Cap:COOLER_TEMPERATURE:0
18:59:49.447 > Cap:MEATPACK:0
18:59:49.450 > ok
M111 S247
19:05:18.585 > echo:DEBUG:ECHO,INFO,ERRORS,COMMUNICATION
19:05:18.588 > ok
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/7048560/Config.zip)

**Comment by ellensp** [comment]
you have #define MKS_MINI_12864 defined not #define MKS_LCD12864A
