### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by Ascvdf** [MarlinFirmware/Marlin#22637]
### Is your feature request related to a problem? Please describe.

Hello !

I'm building a printer without hotend, but I'm editing the software and finding several flaws to make this possible. The material I'm using is liquid at room temperature, so I don't need the heating system.

I ask for help to be checking how I can perform this configuration in marlin, disabling SystemCheck locks and disabling the temperature system.

### Are you looking for hardware support?

I'm stay use a board Ramps V1.4, two motor in Y, one motor in X and Z, anything thermal system.

### Describe the feature you want

I need firmware to use a 3D printer without a heating/thermal controller system.

### Additional context

I am carrying out this project together with the SENAI faculty, for the development and use of biological materials.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
