### ISSUE TITLE
[BUG] (skr 1.3 marlin 2.0 sensorless homing z axis alway home)

### ISSUE THREAD

**Issue by rds11080** [MarlinFirmware/Marlin#22634]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

i try to setup sensorless homing for tmc2209 on skr 1.3 board. xyz axis joging fine, xy axis sensorless homing right, only z axis alway home, when i look at "M114" it say "Trigger" on the config file, the "Mechanical endstop with COM to ground and NC to Signal uses "false" here" to ground need to set to false for sensorless homing, i think that is the proble. i try newest version of marlin but still have same problem only for z axis sensorless homing

### Expected behavior

i expect z axis homing like x and y

### Actual behavior

already home all the time

### Steps to Reproduce

1. setup tmc 2209
2. setup sensorless homing (setup STALL_SENSITIVITY)
3. jog all the axis
4. home xyz
5. only x y homing, z axis already home?

### Version of Marlin Firmware

newest

### Printer model

none

### Electronics

none

### Add-ons

none

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
