### ISSUE TITLE
Download Master can not save from USB 1 to second USB 2 port

### ISSUE THREAD

**Issue by porfavorhelp** [MarlinFirmware/Marlin#22638]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Download Master can not save from USB 1 to second USB 2 port

### Version of Marlin Firmware

GT-AX11000_386.3_2

### Printer model

GT-AX11000 

### Add-ons

2 WD passport 2TB

### Bed Leveling

No Bed Leveling

### Additional information & file uploads

Download Master can not save from USB 1 to second USB 2 port directory.

**Comment by ellensp** [comment]
This is not Marlin 3d printer firmware related.
User seems confused between Marlin and Merlin

Seem to be talking about https://drivers.softpedia.com/get/Router-Switch-Access-Point/ASUS/ASUS-GT-AX11000-AsusWrt-Merlin-Firmware-386-3-2.shtml

**Comment by ellensp** [comment]
This is not the first time they have done this.
Previous unrelated to Marlin issue https://github.com/MarlinFirmware/Marlin/issues/22230
