### ISSUE TITLE
BUG Silnik extrudera nie pracuje podczas drukowania

### ISSUE THREAD

**Issue by qulet** [MarlinFirmware/Marlin#22642]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Silnik extrudera działa prawidłowo  z menu LCD  można go skalibrować z  Repetier-Host. Przestaje działać właściwie podczas drukowania.  Takie samo zachowanie silnika osi "E"  zaobserwowałem na 2 płytach:
MKS-SBASE 
BTT SKR 2 REV B
 Myślałem że płyta MKS-Sbase jest uszkodzona i kupiłem BTT SKR 2 REV B.
Osie X,Y,Z i inne funkcje, dzałają prawidłowo.  Podmiana  pinów w pliku pins_MKS_SBASE.h nie przynosiła oczekiwanego rezultatu.

### Bug Timeline

uruchomienie pierwszego wydruku

### Expected behavior

Spodziewałem że silnik będzie podawał filament  zgodnie z g-kodem.

### Actual behavior

silnik oscyluje prawo-lewo

### Steps to Reproduce

Ruch osi "E"  LCD  OK
Kalibracja Repetier-Host  step/mm osi "E" OK
Drukowanie osi "E" NOK

PLIKI MKS-SBASE:
[MKS.zip](https://github.com/MarlinFirmware/Marlin/files/7063075/MKS.zip)
PLIKI  BTT SKR-2
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7063082/Marlin.zip)
 G-code:
[nakretka_12.zip](https://github.com/MarlinFirmware/Marlin/files/7063105/nakretka_12.zip)

### Version of Marlin Firmware

02000901

### Printer model

DIY Core XY

### Electronics

MKS SBASE v1.4, BTT SKR 2 rev b

### Add-ons

płyty główne

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Simplify3D

### Host Software

Repetier Host

### Additional information & file uploads

Proszę o pomoc w rozwiązaniu tego problemu. Walczę z tą drukarką od miesiąca . Nie wiem  co jeszcze mogę zrobić aby extruder działął podczas drukowania.......

**Comment by ellensp** [comment]
From the google translation, this looks like a support request, not a bug report.

Most likely the Hotend is getting clogged or to cold. Hardware issue with hotend. (can also do this if filament is over sized) 
or just trying to print to fast. 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by qulet** [comment]
drukarka wygląda tak:
https://drive.google.com/file/d/1CjWPWrZahFIQbC_TYrNnJCguMUC7NHUH/view?usp=sharing

 Nie wiem  jakiej kategorii jest to problem, Na pewno nie zatkanego extrudera    bez filamentu silnik podczas drukowania również  nie kręci .
 To jest moja druga drukarka elementy do budowy - wydrukowałem na mojej pierwszej drukarce która działa na Marlin 1.9 . 
 Nie jest to również problem w G-code - wygenerowane pliki drukują się bez problemu na Marlinie V.1.9.
link do filmu z bazowanie drukarki z problemem osi "E"
https://drive.google.com/file/d/1CW6-0RqxfU6hXrtvNbrCL9LGs18Tfbia/view?usp=sharing
