### ISSUE TITLE
[BUG] Mesh Edit shows one too few rows, saves one line wrong

### ISSUE THREAD

**Issue by Stein-Wolf** [MarlinFirmware/Marlin#22650]
### Bug Description

Mesh Bed Edit shows 1 row less than leveled and if you level e.g. point 2 in second row, it is saved as point 2 in row 1.

More accurate: If you have a grid of 5x5 on MBL you only get shown a grid of 5x4 in the edit section. The nozzle cannot go to the last row of the bed but also save the wrong position.

If you edit e.g. the point marked as "o" (5th "y" row isn't shown and you cannot goto with the nozzle):
5: y-y-y-y-y
4: x-x-x-x-x
3: x-x-x-x-x
2: x-x-x-o-x
1: x-x-x-x-x
it will be saved as this point marked as ("o"):
5: y-y-y-y-y
4: x-x-x-x-x
3: x-x-x-x-x
2: x-x-x-x-x
1: x-x-x-o-x

### Configuration Files
[conf.zip](https://github.com/MarlinFirmware/Configurations/files/6489219/conf.zip)
Original is from "digant" at https://www.thingiverse.com/thing:4294049/ - version for Sidewinder X1. I think originated from bugfix version.
I haven't done changes except extruder calibration. Digant, as far as I can see, hasn't done anything except enable and disable sections and do some calibrations for the sidewinder X1.

### Steps to Reproduce

1. Make MBL (manuel) (grid 5x5)
2. Then goto Mesh Edit in the LCD. See that it only shows a grid of 5x4.
3. Anyway edit a point e.g. second row (after seeing first layer is of). Z height e.g. is "-0.08" - new z height is e.g. "0.13"
4. Save to eeprom
5. Do Mesh Edit again
6. Goto the same point - notice that heigt is still "-0.08" but point below second row now has height "0.13".

**Expected behavior:**

Show grid 5x5 is MBL is 5x5. I think this will maybe fix the wrong point saving aswell.

**Actual behavior:**

See above.

#### Additional Information

See thingiverse link above. First picture shows the 5x5 grid as it should be.
See https://www.youtube.com/watch?v=bAXEwa6roL0&lc=UgzDAM0s2m70-TkLatR4AaABAg.9MCaEs7mNwz9MgWeaGqCnf
There you can see the wrong grid 5x4.

I hope my first post is ok. This is all new for me.

**Comment by Sonicboom247** [comment]
Hello, my friend, this is very odd as I just edited my mesh last night and
had 5x5, I have had 5x since my first firmware. Are you using both my TFT
firmware and Marlin firmware? Either way i will test and make sure it is
correct. i have an updated TFT firmware coming this weekend since BTT broke
the start and end scripts but apparently it is fixed now.

**Comment by Stein-Wolf** [comment]
Hi @Sonicboom247!
This is an old topic from May, related to the old firmware from digant. I'm using yours since, and there is no problem (I'm not using your latest version, because it is still a pain in the a.. for me to always take the cable from the display to update. And therefore I wait for a "milestone"- update, like perfectliy working octoprint without needing to disable the display ;). I'm using your version with no working filament sensor, but that's no problem for me. I'm happy that I can now print without always needing to level the bed over and over again.) 
I guess you got this massage, because thinkyhead edited the title yesterday.
I didn't close this topic, because I know others have(had) the same issue with the digant version. But @thinkyhead - for me this is closed because of no longer using the digant firmware. So you may close the whole topic. -> Feel free to decide.

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by thisiskeithb** [comment]
> I didn't close this topic, because I know others have(had) the same issue with the digant version.

Please open an issue in their fork.
