### ISSUE TITLE
[FR] Platformio env for firmware for Ender 3 PRO into a BIGTREETECH SKR mini E3 v2.0.

### ISSUE THREAD

**Issue by gdrDeveloper** [MarlinFirmware/Marlin#22661]
### Is your feature request related to a problem? Please describe.

I want to build a firmware for Ender 3 PRO into a BIGTREETECH SKR mini E3 v2.0 and i need envirotment configuration.

I tried to compile with marlin and bugversion 2.0x repositories but both give me the same error

I tried whit this 
--------------------------------------------------------------------------------------------------------------------
#
# Just print the dependency tree
#
[env:STM32F103RC_btt_512K]
platform    = ststm32
board       = genericSTM32F103RC
board_build.core = maple
build_flags = -c -H -std=gnu++11 -Wall -Os -D__MARLIN_FIRMWARE__
src_filter  = +<src/MarlinCore.cpp>
--------------------------------------------------------------------------------------------------------------------

 Error: Build environment 'STM32F103RC_btt_512K' is incompatible with BOARD_BTT_SKR_MINI_E3_V2_0. Use one of these: STM32F103RC_btt, STM32F103RC_btt_USB, STM32F103RE_btt, STM32F103RE_btt_USB, STM32F103RC_btt_maple, STM32F103RC_btt_USB_maple, STM32F103RE_btt_maple, STM32F103RE_btt_USB_maple
--------------------------------------------------------------------------------------------------------------------

I Tried use STM32F103RC_btt too and..

--------------------------------------------------------------------------------------------------------------------
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\STM32F103RC_btt\firmware.elf] Error 1
--------------------------------------------------------------------------------------------------------------------

And with STM32F103RC_btt_maple have and error too
--------------------------------------------------------------------------------------------------------------------
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\HAL\shared\eeprom_if_i2c.cpp:28:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
Compiling .pio\build\STM32F103RC_btt_maple\src\src\gcode\control\M211.cpp.o
*** [.pio\build\STM32F103RC_btt_maple\src\src\HAL\shared\eeprom_if_i2c.cpp.o] Error 1
In file included from Marlin\src\feature\../inc/MarlinConfig.h:50:0,
                 from Marlin\src\feature\babystep.cpp:23:
Marlin\src\feature\../inc/../HAL/STM32F1/inc/SanityCheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from Marlin\src\inc/MarlinConfig.h:50:0,
                 from Marlin\src\MarlinCore.h:24,
                 from Marlin\src\MarlinCore.cpp:31:
Marlin\src\inc/../HAL/STM32F1/inc/SanityCheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from Marlin\src\feature\bedlevel\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\feature\bedlevel\bedlevel.cpp:23:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from c:\marlin-bugfix-2.0.x\marlin\src\inc\marlinconfig.h:50:0,
                 from Marlin\src\feature\bedlevel\mbl\mesh_bed_leveling.cpp:23:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from Marlin\src\feature\../inc/MarlinConfig.h:50:0,
                 from Marlin\src\feature\controllerfan.cpp:23:
Marlin\src\feature\../inc/../HAL/STM32F1/inc/SanityCheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from Marlin\src\feature\../inc/MarlinConfig.h:50:0,
                 from Marlin\src\feature\tmc_util.cpp:23:
Marlin\src\feature\../inc/../HAL/STM32F1/inc/SanityCheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from Marlin\src\feature\../inc/MarlinConfig.h:50:0,
                 from Marlin\src\feature\../MarlinCore.h:24,
                 from Marlin\src\feature\pause.cpp:34:
Marlin\src\feature\../inc/../HAL/STM32F1/inc/SanityCheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from Marlin\src\gcode\bedlevel\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\gcode\bedlevel\G42.cpp:23:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from Marlin\src\gcode\bedlevel\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\gcode\bedlevel\M420.cpp:23:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from c:\marlin-bugfix-2.0.x\marlin\src\inc\marlinconfig.h:50:0,
                 from Marlin\src\gcode\bedlevel\mbl\G29.cpp:27:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from Marlin\src\gcode\config\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\gcode\config\../gcode.h:309,
                 from Marlin\src\gcode\config\M221.cpp:23:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from c:\marlin-bugfix-2.0.x\marlin\src\inc\marlinconfig.h:50:0,
                 from Marlin\src\gcode\bedlevel\mbl\M421.cpp:27:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
*** [.pio\build\STM32F103RC_btt_maple\src\src\feature\bedlevel\mbl\mesh_bed_leveling.cpp.o] Error 1
In file included from Marlin\src\gcode\config\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\gcode\config\M301.cpp:23:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
In file included from Marlin\src\gcode\config\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\gcode\config\M302.cpp:23:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
*** [.pio\build\STM32F103RC_btt_maple\src\src\gcode\bedlevel\G42.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\gcode\bedlevel\M420.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\gcode\config\M221.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\feature\babystep.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\feature\bedlevel\bedlevel.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\gcode\bedlevel\mbl\M421.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\feature\tmc_util.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\feature\controllerfan.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\feature\pause.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\gcode\config\M301.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\MarlinCore.cpp.o] Error 1
In file included from Marlin\src\gcode\control\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\gcode\control\../gcode.h:309,
                 from Marlin\src\gcode\control\M211.cpp:27:
c:\marlin-bugfix-2.0.x\marlin\src\hal\stm32f1\inc\sanitycheck.h:50:4: error: #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
   #error "EMERGENCY_PARSER is only supported by HardwareSerial or USBComposite in HAL/STM32F1."
    ^~~~~
*** [.pio\build\STM32F103RC_btt_maple\src\src\gcode\config\M302.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\gcode\bedlevel\mbl\G29.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_maple\src\src\gcode\control\M211.cpp.o] Error 1
======================================================================================= [FAILED] Took 9.50 seconds =======================================================================================
Environment            Status    Duration
---------------------  --------  ------------
STM32F103RC_btt_maple  FAILED    00:00:09.499
================================================================================= 1 failed, 0 succeeded in 00:00:09.499 ================================================================================= 
The terminal process "~\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

### Are you looking for hardware support?

I want to build a firmware for Ender 3 PRO into a BIGTREETECH SKR mini E3 v2.0.

### Describe the feature you want

Want to clone repository and can build the firmware

**Comment by ellensp** [comment]
STM32F103RC_btt_512K no longer exists. It was a dumb hack that attempted to use 512k flash on a 256k flash controller. It caused more issues that it solved.
As it says Use one of these: STM32F103RC_btt, STM32F103RC_btt_USB, STM32F103RE_btt, STM32F103RE_btt_USB
If your chip says stm32f103rc, use stm32f103rc if your chip says stm32f103re use stm32f103re
The rc version only has 256k of flash, the re version has 512k of flash

**Comment by ellensp** [comment]
Tested all 4 env's listed above and they all compile without issues  on bugfix using the example config https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Creality/Ender-3%20Pro/BigTreeTech%20SKR%20Mini%20E3%202.0
