### ISSUE TITLE
'X_MIN' was not declared in this scope; did you mean 'Z_MIN'?

### ISSUE THREAD

**Issue by Deema35** [MarlinFirmware/Marlin#22674]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When I compile Marlin Bugfix 2.0.x. I have got error:

Marlin\src\module/endstops.h:69:46: error: 'X_MIN' was not declared in this scope; did you mean 'Z_MIN'?

I dont have x min endstop, because I use X max endstop this is my settings;
//#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
//#define USE_IMIN_PLUG
//#define USE_JMIN_PLUG
//#define USE_KMIN_PLUG
#define USE_XMAX_PLUG
//#define USE_YMAX_PLUG
//#define USE_ZMAX_PLUG
//#define USE_IMAX_PLUG
//#define USE_JMAX_PLUG
//#define USE_KMAX_PLUG

### Bug Timeline

Just now

### Version of Marlin Firmware

02000901

**Comment by tpruvot** [comment]
in Marlin/Configuration.h set #define X_HOME_DIR 1 instead of -1

**Comment by Deema35** [comment]
Thank you, it's working.
