### ISSUE TITLE
[BUG] Freeze sending empty G-code from MKS TFT UI

### ISSUE THREAD

**Issue by 1qaz2004** [MarlinFirmware/Marlin#22679]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

No ignoring empty G-code line

### Bug Timeline

Detected when trying to exit the G-code menu

### Expected behavior

Exit to preview or main screen is pending

### Actual behavior

Dark screen without the possibility of further work

### Steps to Reproduce

Restart firmware or shutdown

### Version of Marlin Firmware

Marlin-bugfix-2.0.x

### Printer model

ANET E16

### Electronics

TS35 + MKS Robin Nano V3 screen

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Cura

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7081477/Marlin.zip)

**Comment by thinkyhead** [comment]
Did you actually test with `bugfix-2.0.x`? You provided configurations for Marlin 2.0.8 instead of configurations that are compatible with `bugfix-2.0.x`. Please post updated configurations so that we can actually compile and test.

**Comment by 1qaz2004** [comment]
Configuration (adv) .h files updated

**Comment by ellensp** [comment]
Can you elaborate on
Steps to Reproduce: Restart firmware or shutdown
It doesn't seem related to "Freeze sending empty G-code from MKS TFT UI "

**Comment by 1qaz2004** [comment]
It has been empirically found that the printer remains in working order, since it is controlled via USB via Repetier. Screen health is restored after the G28 from Repetier. Perhaps Marlin is just waiting for the G-code command. But a dark (blank) screen is not the normal state of processing an empty line.

**Comment by thinkyhead** [comment]
String handling in Marlin is pretty primitive and lacks bounds-checking to make it more robust. That will be overhauled at some point. Meanwhile, it's quite possible that some buffer is overflowing or otherwise improperly handled in the screen code that was contributed by Makerbase. I'm not familiar with the code in question so it will take some time to analyze.

**Comment by thinkyhead** [comment]
Let's see if this helps. A simple change in `draw_keyboard.cpp` (line 165)…
```diff
-         if (!queue.ring_buffer.full(3)) {
+         if (strlen(ret_ta_txt) && !queue.ring_buffer.full(3)) {
```

**Comment by 1qaz2004** [comment]
Hello, unfortunately the proposed changes in line 165 did not fix the problem. It may be necessary to modify the file Marlin-bugfix-2.0.9.1 \ Marlin \ src \ lcd \ extui \ mks_ui \ draw_gcode.cpp
Thanks.

**Comment by thinkyhead** [comment]
Some patches have been made to bugfix recently that should have some impact on this issue and maybe even solve it. 
So please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by 1qaz2004** [comment]
Okay, I'll try the last marlin today and check it out. thanks

вт, 19 окт. 2021 г. в 14:19, Scott Lahteine ***@***.***>:

**Comment by 1qaz2004** [comment]
Sending empty G-code from MKS interface resolved. Now processing an empty command does not cause a black screen. In addition, I would like to note that for successful compilation I had to make changes to the file
Marlin-bugfix-2.0.x \ Marlin \ src \ pins \ stm32f4 \ pins_MKS_ROBIN_NANO_V3_common.h

-     169    #undef PSU_CONTROL
       170    #undef MKS_PWC
       171    #define SUICIDE_PIN                          PB2
       172    #define SUICIDE_PIN_STATE               LOW

+    169    //#undef PSU_CONTROL
       170    #undef MKS_PWC
       171    #define PS_ON_PIN                          PB2  // SUICIDE_PIN
       172    #define PS_ON_PIN _STATE              LOW // SUICIDE_PIN_STATE
