### ISSUE TITLE
Z STEPPER ALIGN not working 

### ISSUE THREAD

**Issue by nikkisstuff** [MarlinFirmware/Marlin#22673]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I have just finished the build of my large corexy machine i am using 4 z motors on a octopus v1.1 and i can not get g34 to align the bed. After running 5 iterations it will report decreasing accuracy and never actually aligns the bed. is there a way to make to make sure my motors are  in the correct orientation? 

### Version of Marlin Firmware

2.0.9.1

### Electronics

bigtreetech octopus v1.1

**Comment by LeandroScovino** [comment]
Try running more interactions. Mine aligned everything after 15.

G34 I20 T0.01 for 0.01 tolerance.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
