### ISSUE TITLE
[FR] add an option to have the individual axis homing as a submenu

### ISSUE THREAD

**Issue by TomW1605** [MarlinFirmware/Marlin#22685]
### Is your feature request related to a problem? Please describe.

No

### Are you looking for hardware support?

No

### Describe the feature you want

it would be good to have an extra option under `INDIVIDUAL_AXIS_HOMING_MENU` that would put the new menu items in a sub menu. as it is it puts them underneath the home all option and that makes it harder to get to other important options like bed leveling and disabling the steppers. this menu could either contain just the 3 asix homes or all 4 options so that it does not increase the length of the menu at all.

i have tested this on my own printer and it works well but i am not sure how to go about doing a PR for something like this as it requires a new translation for the sub menu title.

### Additional context

No

**Comment by thisiskeithb** [comment]
Resolved in https://github.com/MarlinFirmware/Marlin/pull/22692
