### ISSUE TITLE
[BUG] (bug summary) DELTA_AUTO_CALIBRATION requires a probe or LCD Controller while having manual probe

### ISSUE THREAD

**Issue by rickythewoof** [MarlinFirmware/Marlin#22688]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I am trying to build the latest marlin for my custom built 3d printer. I have enabled AUTO_CALIBRATION and since i do not have a proble I have enabled PROBE MANUALLY in the probing section. When I try to compile the firmware sanitycheck gives me error:
`Marlin\src\HAL\AVR\../../inc/SanityCheck.h:1437:6: error: #error "DELTA_AUTO_CALIBRATION requires a probe or LCD Controller."`

### Expected behavior

I expected to compile without problems, since I have enabled the manual probe option that has a comment explaining just how this manual probe is made for auto calibration

### Version of Marlin Firmware

02000901

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configuration&adv.zip](https://github.com/MarlinFirmware/Marlin/files/7092941/Configuration.adv.zip)

**Comment by Vertabreak** [comment]
the configuration does not have a lcd controller enabled with a encoder that is required to operate manual probing.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by rickythewoof** [comment]
But as the documentation state I could use manual terminal commands to make it work, that's what made me think it was possible

**Comment by rickythewoof** [comment]
![image](https://user-images.githubusercontent.com/21180234/131812623-4e4414de-83a4-4198-a62a-33e95962697b.png)
As expected I can auto bed level with a manual probe, as written [https://marlinfw.org/docs/features/auto_bed_leveling.html](url) in the docs here too
