### ISSUE TITLE
Error:Printer halted. kill() called! when homing Y axis

### ISSUE THREAD

**Issue by GFTF48** [MarlinFirmware/Marlin#22718]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I have loaded Marlin 2.0.9.1 (Aug  3 2021 12:30:13) on my creality CR10s. It has worked well and I have been able to print several projects. My problem is that when I home my X and Y axis if the Y is at greater than 200mm from the home position the x axis homes and then the Y axis starts to home for about 20 mm then the printer sends Error:Printer halted. kill() called!.
If the Y axis is less than 40 mm from home  when you start the homeing process all works OK! 

I have looked at the signal on the Y limit switch with a "CRO" and bypassed it with a .01 uf cap which cleaned up the noise on that sencsor, but no change in fault.

Here are the logs from octo print for the failure condition

Send: G91
Recv: ok P15 B3
Send: G28 X0 Y0
Recv:  T:11.82 /0.00 B:11.51 /0.00 @:0 B@:0
Recv: echo:busy: processing
Recv:  T:11.20 /0.00 B:10.99 /0.00 @:0 B@:0
Recv: echo:busy: processing
Recv:  T:12.50 /0.00 B:12.19 /0.00 @:0 B@:0
Recv: echo:busy: processing
Recv:  T:13.70 /0.00 B:11.67 /0.00 @:0 B@:0
Recv: echo:busy: processing
Recv:  T:12.34 /0.00 B:13.02 /0.00 @:0 B@:0
Recv: echo:busy: processing
Recv:  T:11.30 /0.00 B:10.57 /0.00 @:0 B@:0
Recv: echo:Homing Failed
Recv: Error:Printer halted. kill() called!
Changing monitoring state from "Operational" to "Error"
Send: M112
Send: N3202 M112*18
Send: N3203 M104 T0 S0*19
Send: N3204 M140 S0*80
Changing monitoring state from "Error" to "Offline after error"
Connection closed, closing down monitor

Here are the logs for the good condition

After restart

Recv: FIRMWARE_NAME:Marlin 2.0.9.1 (Aug  3 2021 12:30:13) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Bltouch v3 EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Recv: Cap:SERIAL_XON_XOFF:0
Recv: Cap:BINARY_FILE_TRANSFER:0
Recv: Cap:EEPROM:1
Recv: Cap:VOLUMETRIC:1
Recv: Cap:AUTOREPORT_POS:0
Recv: Cap:AUTOREPORT_TEMP:1
Recv: Cap:PROGRESS:0
Recv: Cap:PRINT_JOB:1
Recv: Cap:AUTOLEVEL:1
Recv: Cap:RUNOUT:1
Recv: Cap:Z_PROBE:1
Recv: Cap:LEVELING_DATA:1
Recv: Cap:BUILD_PERCENT:0
Recv: Cap:SOFTWARE_POWER:0
Recv: Cap:TOGGLE_LIGHTS:0
Recv: Cap:CASE_LIGHT_BRIGHTNESS:0
Recv: Cap:EMERGENCY_PARSER:1
Recv: Cap:HOST_ACTION_COMMANDS:1
Recv: Cap:PROMPT_SUPPORT:0
Recv: Cap:SDCARD:1
Recv: Cap:REPEAT:0
Recv: Cap:SD_WRITE:1
Recv: Cap:AUTOREPORT_SD_STATUS:0
Recv: Cap:LONG_FILENAME:0
Recv: Cap:THERMAL_PROTECTION:1
Recv: Cap:MOTION_MODES:0
Recv: Cap:ARCS:1
Recv: Cap:BABYSTEPPING:1
Recv: Cap:CHAMBER_TEMPERATURE:0
Recv: Cap:COOLER_TEMPERATURE:0
Recv: Cap:MEATPACK:0
Recv: ok N1 P15 B3
Send: M21
Recv: echo:No SD card
Recv: ok P15 B3
Send: M155 S2
Recv: ok P15 B3
Send: G91
Recv: ok P15 B3
Send: G1 Y-10 F6000
Recv: ok P14 B3
Send: G90
Recv: ok P14 B3
Recv:  T:12.66 /0.00 B:12.45 /0.00 @:0 B@:0
Recv:  T:12.50 /0.00 B:12.66 /0.00 @:0 B@:0
Send: G91
Recv: ok P15 B3
Send: G1 Y-10 F6000
Recv: ok P14 B3
Send: G90
Recv: ok P14 B3
Recv:  T:12.19 /0.00 B:11.88 /0.00 @:0 B@:0
Send: G91
Recv: ok P15 B3
Send: G1 Y-10 F6000
Recv: ok P14 B3
Send: G90
Recv: ok P14 B3
Send: G91
Recv: ok P15 B3
Send: G1 Y-10 F6000
Recv: ok P14 B3
Send: G90
Recv: ok P14 B3
Recv:  T:11.04 /0.00 B:11.67 /0.00 @:0 B@:0
Send: G91
Recv: ok P15 B3
Send: G1 Y-10 F6000
Recv: ok P14 B3
Send: G90
Recv: ok P14 B3
Send: G91
Recv: ok P15 B3
Send: G1 X10 F6000
Recv: ok P14 B3
Send: G90
Recv: ok P14 B3
Recv:  T:12.29 /0.00 B:12.08 /0.00 @:0 B@:0
Send: G91
Recv: ok P15 B3
Send: G1 X10 F6000
Recv: ok P14 B3
Send: G90
Recv: ok P14 B3
Send: G91
Recv: ok P15 B3
Send: G28 X0 Y0
Recv:  T:12.03 /0.00 B:11.61 /0.00 @:0 B@:0
Recv: echo:busy: processing
Printer seems to support the busy protocol, will adjust timeouts and set busy interval accordingly
Recv:  T:11.77 /0.00 B:11.30 /0.00 @:0 B@:0
Recv: echo:busy: processing
Recv:  T:11.82 /0.00 B:11.15 /0.00 @:0 B@:0
Recv: echo:busy: processing
Recv:  T:12.40 /0.00 B:11.98 /0.00 @:0 B@:0
Recv: X:4.00 Y:2.00 Z:5.00 E:0.00 Count X:320 Y:160 Z:2000
Recv: ok P15 B3
Send: G90
Recv: ok P15 B3
Send: M113 S2
Recv: ok P15 B3

Can you suggest a configuration fix or a means to get better fault information.

### Bug Timeline

Started when I put BLtouch on the printer and used marlin Firmware

### Expected behavior

I should be able to home from any point on the printer plan

### Actual behavior

Homeing after a print when the Y axis is at 300mm fails

### Steps to Reproduce

1. print something and the printer moves tp Y 300mm
2. remove print and home x and y axis From octoprint
3. X axis homes
4. Y axis fails

### Version of Marlin Firmware

Marlin 2.0.9.1 (Aug  3 2021 12:30:13) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Bltouch v3 EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

### Printer model

Cr10s

### Electronics

Stock electronics

### Add-ons

BLtouch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/7112523/Configuration_adv.zip)

**Comment by Vertabreak** [comment]
if #define ENDSTOP_NOISE_THRESHOLD 2 is not already uncommented try enabling to correct the issue.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by hpo14** [comment]
> if #define ENDSTOP_NOISE_THRESHOLD 2 is not already uncommented try enabling to correct the issue.

with marlin 2.0.9.2 + basic prusa I3
I got the same issue
And tried with "#define ENDSTOP_NOISE_THRESHOLD 2" but not worked.
