### ISSUE TITLE
[BUG] Not possible currently to compile marlin 2.0.9.1 using only the arduino IDE

### ISSUE THREAD

**Issue by Wallby** [MarlinFirmware/Marlin#22711]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

There is only one version (0.5.0 it seems) of U8glib-HAL available via the arduino library manager..
![afbeelding](https://user-images.githubusercontent.com/13614975/132090521-66e83fe2-3574-4e06-8c31-a6ec57d5d44a.png)
![afbeelding](https://user-images.githubusercontent.com/13614975/132091021-0de6761d-6e95-484d-8d72-35669807a0b7.png)

It is not possible atm the get marlin 2.0.9.1 to compile using only arduino IDE as for U8glib-HAL the header that was called U8glib.h in U8glib-HAL 0.4.5 is now called U8Glib-HAL.h (marlin 2.0.9.1 seems to require U8glib.h from U8glib-HAL 0.4.5).

I have not tested if 0.4.5 actually works, but https://github.com/MarlinFirmware/Marlin/commit/c9a7fd1722764f2b790a38f2c7ee0c4d00d77c17 did make it into 2.0.9.1 (i.e. using U8glib-HAL), but https://github.com/MarlinFirmware/Marlin/commit/69b44c2309d859865d4724cb8e323a13ba535d3c did not.
It seems like 2.0.9.1 was intended to be used with U8glib-HAL 0.4.5

NOTE: I did not test the bugfix-2.0.x code, but this issue is not about the bugfix-2.0.x branch
### Bug Timeline

See description (it seems that this bug is caused by not providing the option to download 0.4.5 via the arduino library manager)

### Expected behavior

I am able to select 0.4.5/0.5.0 via the arduino library manager + there is a note in the readme.md of marlin "explaining the situation".

### Actual behavior

See bug description

### Steps to Reproduce

1. Extract marlin 2.0.9.1 in a folder
2. Open Marlin.ino in Arduino IDE
3. Install U8glib via the library manager (sketch -> "use library" -> "manage libraries") //< not sure what these options are actually called as display language is not english for me
4. Press the "☑" to compile

### Version of Marlin Firmware

2.0.9.1

### Additional information & file uploads

Other people experiencing this issue..
https://github.com/MarlinFirmware/Marlin/issues/22652
https://github.com/MarlinFirmware/Marlin/pull/22324#issuecomment-885567806

**Comment by Wallby** [comment]
> ![afbeelding](https://user-images.githubusercontent.com/13614975/132090521-66e83fe2-3574-4e06-8c31-a6ec57d5d44a.png)
> ![afbeelding](https://user-images.githubusercontent.com/13614975/132091021-0de6761d-6e95-484d-8d72-35669807a0b7.png)

NOTE: even though in these images U8glib seems to be installed and U8glib-HAL not, these images are merely for showing that there is no option to select a version of U8glib-HAL.

**Comment by tpruvot** [comment]
unsure its the reason but not all arch are set in the library properties...
 https://github.com/MarlinFirmware/U8glib-HAL/blob/master/library.properties#L9

**Comment by ellensp** [comment]
There is only one version of U8glib-HAL version 0.5.0 avalable in the arduino ide library manager.

**Comment by ellensp** [comment]
You do not need U8glib at all, you only need  U8glib-HAL for newer marlin

**Comment by ellensp** [comment]
The features.ini in 2.0.9.1 specifies U8glib-HAL@~0.4.5  for platformio. It is also required by Arduino ide.

This is a modified U8glib from Marlin.  It is in the MarlinFirmware/U8glib-HAL repository, but internally it is still called U8glib.h (this is why you cannot install it from the arduino ide library manager, it conflicts with the current U8glib) 

In bugfix and 2.0.x and will be in next release of Marlin, everything has been updated to use U8glib-HALh as provided by U8glib-HAL@~0.5.0 
This also allows for easy  instillation of U8glib-HAL v 0.5.0  from the arduino ide library manager.

To use the correct version of U8glib do the following:
Uninstall standard U8glib from the Arduino IDE library manager.
Download v0.4.5 of U8glib-HAL from https://github.com/MarlinFirmware/U8glib-HAL/releases/tag/0.4.5
Extract the directory into your Arduino/libraries folder
Download https://github.com/MarlinFirmware/Marlin/files/6710738/library.properties.zip
Extract library.properties to Arduino/libraries/U8glib-HAL-0.4.5
Restart Arduino IDE so it notices libraries have changed.
Click build or upload  and take a long nap while arduino ide slowly compiles.

Or as has been mentioned a billion times, give up on the old criminally backwards and slow Arduino IDE and use platfomio/vscode. https://marlinfw.org/docs/basics/install_platformio_vscode.html
It installs all required library automatically and is about 10 time faster to compile Marlin.

**Comment by ellensp** [comment]
"Did you test the latest bugfix-2.0.x code? Yes, and the problem still exists."
This is incorrect

You simply install U8glib-HAL v 0.5.0 from the arduino ide library manager and compile.

**Comment by Wallby** [comment]
@ellensp 

> This is incorrect

No it is not. The problem is that "It is not possible currently to compile marlin 2.0.9.1 using only the arduino IDE" (i.e. marlin 2.0.9.1 doesn't work with U8glib-HAL 0.5.0).

**Comment by ellensp** [comment]
The problem does not exist in bugfix.

**Comment by Wallby** [comment]
What's with the emoji? It might be that bugfix compiles, but compiling marlin 2.0.9.1 (an official release) using only the arduino IDE is not possible, hence "It is not possible currently to compile marlin 2.0.9.1 using only the arduino IDE" is not false.
