### ISSUE TITLE
[BUG] G29 : TouchMi probe stow

### ISSUE THREAD

**Issue by Kebims** [MarlinFirmware/Marlin#22724]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When I do a G28 command, everything goes well, at the end of the probing, the probe is correctly stowed.
( TOUCH_MI_RETRACT_Z 0.4 )

But when I do a G29 command, at the end of the procedure,  the probe does not stow. 

If I do a G1 Z0.4 command, the nozzle goes down and the probe retracts correctly.

### Version of Marlin Firmware

bugfix-2.0.x (Sep  6 2021)

### Electronics

Bigtreetech SKR-2

### Add-ons

TouchMi

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7119979/Marlin.zip)

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
