### ISSUE TITLE
[BUG] MKS MINI12864 Not working with SKR1.4/t

### ISSUE THREAD

**Issue by GrzegorzManiak** [MarlinFirmware/Marlin#22720]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I defined my display of choice, the mks mini 12864, Partnered with an SKR1.4T with TMC2130's drivers running in SPI mode, I've tried to reverse the connectors, All that I get is the screen glowing white as it getting fed the 5v it needs, It seems to be buzzing every time I click the Pot, but shows no characters, I verified that the display is functional by hooking it up to a TriGorilla 1.3 board and the Mks Gen L v1.0.

## Configuration.h
```cpp
#define CONFIGURATION_H_VERSION 02000901   
#define MKS_MINI_12864
```

## pins_BTT_SKR_V1_4.h
```cpp
#if ENABLED(MKS_MINI_12864)
  #define DOGLCD_CS            EXP1_05_PIN
  #define DOGLCD_A0            EXP1_04_PIN
  #define DOGLCD_SCK           EXP2_09_PIN
  #define DOGLCD_MOSI          EXP2_05_PIN
  #define FORCE_SOFT_SPI
#endif
```

### Bug Timeline

Today, as I tried to attach the screen to reuse it

### Expected behavior

The display is expected to, you know, display stuff.

### Actual behavior

2-3 Second buzzing noise when plugged in, the backlight turns on, audible noise when the pot is turned/clicked, seems like its working, just not displaying.it's

### Steps to Reproduce

1. TMC2130 SPI Paired with an SKR 1.4
2. Compile marlin with the `#define MKS_MINI_12864` display defined.
3. Flash.

### Version of Marlin Firmware

02000901   

### Printer model

Tevo Tarantula Pro

### Electronics

TMC 2130's, Dual Z, 24v, SKR 1.4 Turbo, stock display

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

Cura

**Comment by ellensp** [comment]
"tried to reverse the connectors" that's a shame. That kills one of the io lines on the SKR1.4/t nearly every single time.

**Comment by GrzegorzManiak** [comment]
> "tried to reverse the connectors" that's a shame. That kills one of the io lines on the SKR1.4/t nearly every single time.

Any quick way of testing that?

**Comment by ellensp** [comment]
No easy way I know of.

Start from the beginning.
Check the following.  

Skr 1.4 (note cable key is on the left)
```
/**              ------                             ------
 *  BEEPER 1.30 |10  9 | 0.28 BTN_ENC         0.17 |10  9 | 0.15 SCK
 *         1.18 | 8  7 | 1.19         BTN_EN2 3.26 | 8  7 | 0.16 SDSS
 *         1.20   6  5 | 1.21 CS      BTN_EN1 3.25   6  5 | 0.18 MOSI
 *      A0 1.22 | 4  3 | 1.23          SD_DET 1.31 | 4  3 | RESET
 *          GND | 2  1 | 5V                    GND | 2  1 | NC
 *               ------                            ------
 *                EXP1                              EXP2
*/
```
MKS mini (note cable keys are on right)
<img src="https://reprap.org/mediawiki/images/f/ff/MKS_MINI12864_LCD_controller_pin_out_-_signal_names.jpg">

So according to this you need to rotate the plugs around 180 degrees at one end..  while keeping exp1 going to exp1 and exp2 going to exp2. 

While off and unplugged from usb and power. Plug in the lcd the way you think it should be
With a multi meter  check continuity from controller gnd to lcd gnd (normally the metal sd card holder on the board to the lcd sd card is good for this)
Then check 5v on controller is connected to 5v on lcd.    
If those are fine, it should be safe to power up and try again

**Comment by GrzegorzManiak** [comment]
Thank you, Ill check it out

**Comment by GrzegorzManiak** [comment]
Yep, I verified that It GND => GND and 5V => 5V, But still no text, The display seems like it's trying to refresh them as there's a bit of scrolling text at the bottom in mariln

**Comment by thisiskeithb** [comment]
Which LCD revision do you have? If you could get a picture of the back, that’d help.

I’ll see which revs I have and will toss them on an SKR 1.4.

**Comment by GrzegorzManiak** [comment]
Sure,


![Snapchat-1797095734](https://user-images.githubusercontent.com/83783716/132201812-3de0cf48-2d04-41ab-bab7-37173ab1169a.jpg)
![Snapchat-1801944008](https://user-images.githubusercontent.com/83783716/132201828-bfd8c94b-833a-481c-9550-f725d7fb5f80.jpg)

**Comment by ellensp** [comment]
This page https://www.aliexpress.com/item/32870541074.html says it should be set to a MINIPANEL not a MKS_MINI_12864

**Comment by thisiskeithb** [comment]
> This page https://www.aliexpress.com/item/32870541074.html says it should be set to a MINIPANEL not a MKS_MINI_12864

It’s also outdated.

**Comment by GrzegorzManiak** [comment]
Yeah, I couldn't find much on the V2.0, Marlin has V1.0 and V3.0(bugfix branch) but no V2.0

**Comment by GrzegorzManiak** [comment]
Also, If I try compile for the MINIPANEL, I get a nice message from marlin, In the bugfix branch and the release
```Marlin\src\lcd\dogm\marlinui_DOGM.h:225:23: error: 'DOGLCD_CS' was not declared in this scope; did you mean 'DOGLCD_SCK'?
  225 |     #define U8G_PARAM DOGLCD_CS, DOGLCD_A0                      // HW-SPI
      |                       ^~~~~~~~~
Marlin\src\lcd\dogm\marlinui_DOGM.cpp:262:14: note: in expansion of macro 'U8G_PARAM'
  262 |     u8g.init(U8G_PARAM);
      |              ^~~~~~~~~
Compiling .pio\build\LPC1769\src\src\lcd\extui\ui_api.cpp.o
Marlin\src\lcd\dogm\marlinui_DOGM.h:225:34: error: 'DOGLCD_A0' was not declared in this scope; did you mean 'DOGLCD_SCK'?
  225 |     #define U8G_PARAM DOGLCD_CS, DOGLCD_A0                      // HW-SPI
      |                                  ^~~~~~~~~
Marlin\src\lcd\dogm\marlinui_DOGM.cpp:262:14: note: in expansion of macro 'U8G_PARAM'
  262 |     u8g.init(U8G_PARAM);```

**Comment by ellensp** [comment]
No pin definitions for MINIPANEL for skr 1.4 

change #if ENABLED(MKS_MINI_12864)  to  #if EITHER(MKS_MINI_12864, MINIPANEL)
In Marlin/src/pins/lpc1768/pins_BTT_SKR_V1_4.h  It now compiles

Edit this was wrong... got wrong lcd... corrected

**Comment by GrzegorzManiak** [comment]
Flashed it, still just a white screen, the Nob works, and so dose the reset button, Just nothing gets displayed

**Comment by ellensp** [comment]
try changing   
```CPP
#if ENABLED(FYSETC_MINI_12864, LPC1769)
      #define DOGLCD_CS              EXP1_08_PIN
      #define DOGLCD_A0              EXP1_07_PIN
```
```CPP
#if ENABLED(FYSETC_MINI_12864, LPC1769)
    #define DOGLCD_CS              EXP1_05_PIN
    #define DOGLCD_A0              EXP1_04_PIN

```

**Comment by GrzegorzManiak** [comment]
nope, Do i just give up and buy a new display

**Comment by thisiskeithb** [comment]
`MKS_MINI_12864` does other things like set the contrast and defines `MINIPANEL`, so just defining `MINIPANEL` won’t work.

**Comment by GrzegorzManiak** [comment]
So what do you suggest? Enable `MKS_MINI_12864` and reconfigure the pins from `minipanel` to `MKS_MINI_12864`?
Also running TMC2130'S In spy doesn't affect the display right?

**Comment by GrzegorzManiak** [comment]
Its so so strange, I ran G28 than G29 And I have a manual probe and the display beeps and all

**Comment by thisiskeithb** [comment]
~~I’ve managed to temporarily lose my MKS Mini V2 screens in my pile-o-hardware, but~~ I’m sure we can get this LCD working since it works fine on the SKR 1.3.

**Comment by thisiskeithb** [comment]
So I have an MKS Mini 12864 V1.0 and V2.1.

Both of these work on an SKR 1.4 Turbo with 5160s (also in SPI mode) but the 1.0 seems to need different contrast settings.

Can you try setting your LCD contrast using g-code? `M250 C155` or `M250 C195` will change the [LCD contrast](https://marlinfw.org/docs/gcode/M250.html).

<img src="https://user-images.githubusercontent.com/13375512/132264512-1321975a-00ce-4a45-92b3-d31795861a7a.png" width="25%">

**Comment by GrzegorzManiak** [comment]
I'll grab my printer and check

**Comment by KetamineKyle** [comment]
I can change

**Comment by GrzegorzManiak** [comment]
Clicked the wrong button, I can now change the contrast as beforehand `M250 CXXX`  Would not change the contrast, It would just stay the same, Are you using the stock Pin out of the board, I have a feeling this is a ` SKR1.4` Thing as my friends 1.3 works fine with his `mks mini12864 v2`.
And to add to the confusion, the board works with a `Reprap discount smart controller` of my kossel, and the `MKS Mini12864 v2` works as when I plug it into the `Mks Gen L V1.0` it works as expected.

**Comment by thisiskeithb** [comment]
> I can now change the contrast as beforehand M250 CXXX Would not change the contrast, It would just stay the same

So it's fixed? A bad contrast value could have been stored in EEPROM making the screen unreadable.

> Are you using the stock Pin out of the board, I have a feeling this is a SKR1.4

Stock SKR 1.4 Turbo, cables (rotated one end of each cable 180 degrees), LCDs. The SKR 1.4 and 1.4 Turbo are the same board except for the MCU (LPC1768 vs. LPC1769).
