### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by mattinohio** [MarlinFirmware/Marlin#22737]
### Is your feature request related to a problem? Please describe.

I'd like to be able to configure the number of ABL probes points used with G29 without having to recompile the firmware each time.

### Describe the feature you want

I'm curious if it's possible to configure the number of ABL probe options outside of recompiling the firmware from scratch? Either by a submenu on the printer's screen or, maybe even better, by creating an extension to the G29 code. Let's say "G29 9x9" for something I care a lot about the detail of, or I can set it to "G29 3x3" if there's a quick prototype I don't want to wait 30 minutes for it to kick off the print?

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
