### ISSUE TITLE
[BUG] compilation error in HAL/LPC1768/eeprom_sdcard.cpp

### ISSUE THREAD

**Issue by chschu** [MarlinFirmware/Marlin#22746]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The `debug_rw` function in HAL/LPC1768/eeprom_sdcard.cpp wants to print the `const uint8_t *value`, which leads to the following compile error on the bugfix-2.0.x branch:

```
In file included from Marlin/src/HAL/LPC1768/../../inc/../HAL/./LPC1768/../../core/serial_hook.h:24,
                 from Marlin/src/HAL/LPC1768/../../inc/../HAL/./LPC1768/MarlinSerial.h:31,
                 from Marlin/src/HAL/LPC1768/../../inc/../HAL/./LPC1768/HAL.h:44,
                 from Marlin/src/HAL/LPC1768/../../inc/../HAL/HAL.h:30,
                 from Marlin/src/HAL/LPC1768/../../inc/MarlinConfig.h:31,
                 from Marlin/src/HAL/LPC1768/eeprom_sdcard.cpp:25:
Marlin/src/HAL/LPC1768/../../inc/../HAL/./LPC1768/../../core/serial_base.h: In instantiation of 'void SerialBase<Child>::print(T) [with T = const unsigned char*; Child = ForwardSerial<MarlinSerial>]':
Marlin/src/HAL/LPC1768/../../inc/../core/serial.h:162:25:   required from 'void SERIAL_ECHO(T) [with T = const unsigned char*]'
Marlin/src/HAL/LPC1768/../../inc/../core/serial.h:298:84:   required from 'void serial_echopair_PGM(const char*, T) [with T = const unsigned char*]'
Marlin/src/HAL/LPC1768/eeprom_sdcard.cpp:87:3:   required from here
Marlin/src/HAL/LPC1768/../../inc/../HAL/./LPC1768/../../core/serial_base.h:178:24: error: no matching function for call to 'SerialBase<ForwardSerial<MarlinSerial> >::print(const unsigned char*&, PrintBase)'
  178 |   void print(T c)    { print(c, PrintBase::Dec); }
      |                        ^~~~~
```

The compiler then lists a lot of near-match candidates for the inner print call, but none of them is usable for the pointer.

### Steps to Reproduce

1. configure with `#define MOTHERBOARD BOARD_BTT_SKR_V1_4`, `#define EEPROM_SETTINGS`, and `#define SDCARD_EEPROM_EMULATION`
3. run a build for LPC1768

### Version of Marlin Firmware

bugfix-2.0.x

### Additional information & file uploads

Compilation succeeds on the 2.0.9.1 tag. If I change HAL/LPC1768/eeprom_sdcard.cpp so that `debug_rw` is always called, it prints `1` for the `value` pointer. The pointer seems to get converted to a `bool` here.

Browsing through the history of the file, the `value` pointer had been converted to an `int` a while ago. This conversion has been removed in e7c711996bd3080f5e343eff5556736cbf2e2416, and there have been some other changes in the serial output code since then.

If you could clear up the expected output for the `value` pointer, I'd gladly provide a PR that fixes this issue.

**Comment by thinkyhead** [comment]
The `value` element is a pointer, so the debug line should be printing the value at the pointer, or recast to a `void*` if the address is preferred.
```cpp
SERIAL_ECHOLNPGM("_data(", pos, ",", *value, ",", size, ", ...)");
```
…or…
```cpp
SERIAL_ECHOLNPGM("_data(", pos, ",", (void*)value, ",", size, ", ...)");
```
I'll post a patch shortly.
