### ISSUE TITLE
[FR] independent DEFAULT_AXIS_STEPS_PER_UNIT for X2 Carriage

### ISSUE THREAD

**Issue by mindfreak269** [MarlinFirmware/Marlin#22740]
### Is your feature request related to a problem? Please describe.

how to setup independent DEFAULT_AXIS_STEPS_PER_UNIT for X2 ? i have used BTT S42B for X1 carriage and normal open loop stepper for X2, BTT S42B have 102.4 step /mm for 16 microstepping and normal openloop user 80 step/mm for 16 microstepping, since X1 and X2 use same step/mm configuration, X1 get inccorect move.

### Describe the feature you want

independent X1 or T1 XYZ step/mm configuration not only E

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
