### ISSUE TITLE
BL touch is leveling outside of the bed

### ISSUE THREAD

**Issue by Burockk** [MarlinFirmware/Marlin#22769]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I updated my marlin firmware to latest bugfix but my probe now tries to level outside of the bed. it was working fine but now it doesn't

I set my nozzle probe offset as 

#define NOZZLE_TO_PROBE_OFFSET { -44, -10, 0 }

it was same in my old build and what happens is when I auto bed level probe goes outside of the bed. 

I had to  #define PROBING_MARGIN  increase this to 18 in order to reduce probe area but I am not happy with it is there another way to fix it? 

I am sure my probe offset is right.

### Bug Timeline

When I updated to latest bugfix

### Expected behavior

Probe should be inside of the bed.

### Actual behavior

Probe is outside of the bed

### Version of Marlin Firmware

bugfix 2.0.x

### Printer model

ender 3 pro

### Electronics

BL touch - skr mini v2

### Additional information & file uploads

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/7157613/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/7157614/Configuration_adv.txt)

**Comment by ellensp** [comment]
The probe offset only set the nozzle to probe offset.
You still need to set you bed home position correctly.
Have a read of https://manuelmclure.github.io/ConfiguringLeveling.html

Annother common issue is when you don't set the steps/mm and micro stepping correctly. So a simple move of 10mm actully moves 20. Causing the probe to fly off the bed
