### ISSUE TITLE
[BUG] "M117…" in Custom Menu done script not working

### ISSUE THREAD

**Issue by roel8032** [MarlinFirmware/Marlin#22762]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

CUSTOM_MENU_MAIN in configuration_adv.h :

#define CUSTOM_MENU_MAIN_SCRIPT_DONE "M117 User Script Done"
The message does not show on the LCD anymore.

Since many variables in the language files have changed, i do believe the problem is from changed variablenames?

Latest bugfix files sept 12 2021.

### Version of Marlin Firmware

2.0.9.1 latest bugfix files sept 12 2021

### Printer model

Infitary M508/ Anet A6.

### Your Slicer

Cura

**Comment by thinkyhead** [comment]
Does `M117` work at all on your particular LCD model? Please provide your configurations.

**Comment by ellensp** [comment]
Configuration_adv.h has CUSTOM_MENU_MAIN_SCRIPT_DONE  but code expects MAIN_MENU_ITEM_SCRIPT_DONE

Can either update the Config or change the code

In Marlin/src/lcd/menu/menu_main.cpp is
```CPP
    #ifdef MAIN_MENU_ITEM_SCRIPT_DONE
      #define _DONE_SCRIPT "\n" MAIN_MENU_ITEM_SCRIPT_DONE
```

try changing that to

```CPP
  #ifdef CUSTOM_MENU_MAIN_SCRIPT_DONE
      #define _DONE_SCRIPT "\n" CUSTOM_MENU_MAIN_SCRIPT_DONE
```

**Comment by thinkyhead** [comment]
Patched.

**Comment by roel8032** [comment]
> Does `M117` work at all on your particular LCD model? Please provide your configurations.

Yes, in version 2.0.7. And probably in 2.0.9. download version also.

**Comment by ellensp** [comment]
@roel8032 grab the latest bugfix. This has been patched and should work now.

**Comment by roel8032** [comment]
> @roel8032 grab the latest bugfix. This has been patched and should work now.
![Knipsel](https://user-images.githubusercontent.com/6228110/133057713-b30a1374-a53b-4440-a07f-b04ae07db14e.PNG)

Confirm it works again.
