### ISSUE TITLE
[BUG] M18/M84 Flags not working

### ISSUE THREAD

**Issue by dnlbauer** [MarlinFirmware/Marlin#22768]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

This is related to #20899: M84/M18 should accept flags to disable steppers for some axis but not for all. However, passed flags seem to be ignored and all steppers are disabled independent of the arguments, ie:

`M18 X` should only disable the X driver, but it disables all
`M84 X Y E` should disable all steppers except Z, but Z is also disabled.

### Steps to Reproduce

1. Start the printer and move an axis via the menu to enable steppers
2. Send `M18 X`
3. Check other axes: All of them are disabled

### Version of Marlin Firmware

Marlin 2.0.9.1; Marlin bugfix-2.0.x

### Printer model

Ender 3 V2

### Electronics

Stock electronics, replaced LCD with 12864 Mini

### Add-ons

BLTouch (Connected to BLTouch port)

### Bed Leveling

UBL Bilinear mesh

### Additional information & file uploads

Config files compatible with bugfix-2.0.x [configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7157443/configuration.zip)

**Comment by ellensp** [comment]
This is a hardware limitation.
Your controller the enable pin is shared with all stepper drivers!
You physically cannot disable just one stepper
Eg from your boards pins.h

```
#define X_ENABLE_PIN                        PC3   // Shared
#define Y_ENABLE_PIN                X_ENABLE_PIN
#define Z_ENABLE_PIN                X_ENABLE_PIN
#define E0_ENABLE_PIN               X_ENABLE_PIN

```
