### ISSUE TITLE
Orbiter Extruder 1.5 + ejerk + linear advance[BUG] (bug summary)

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#22785]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I'm using Orbiter extruder 1.5 and they recommend using ejerk at 5mm/s, but I can't compile Marlin using this value, it throughs an error saying the minimum is 10mm/s to use Linear advance (which I really want to use).

Is there any way to bypass this and use ejerk 5mm/s ?

### Bug Timeline

new

### Expected behavior

Use orbiter extruder with recommended ejerk

### Actual behavior

can't compile 

### Version of Marlin Firmware

2.0.9.1

### Printer model

Kossel Delta

### Electronics

Mks Robin E3D

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by thisiskeithb** [comment]
I'd personally like this error be turned into a warning since a `DEFAULT_EJERK` of 5 is perfectly fine on Prusa MK3 & BMG'd direct drive hotends.

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/22787

**Comment by sergiofagundes** [comment]
OK. So what I have done is this: Compile with ejerk at 10, and after uploading the firmware I had set the ejerk to 5 in the lcd settings menu.

**Comment by thisiskeithb** [comment]
> Compile with ejerk at 10, and after uploading the firmware I had set the ejerk to 5 in the lcd settings menu.

If Marlin is going to force users to stick with values of 10 or greater, then that is a bug.

I'm still not happy that this change is forced on everyone since lower values are completely fine for direct drive hotends.

**Comment by thisiskeithb** [comment]
With https://github.com/MarlinFirmware/Marlin/pull/23054, you can now enable `ALLOW_LOW_EJERK`.
