### ISSUE TITLE
Quickhome in 1.0.2-1

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#2278]
There may be a problem with quickhome in this ver. - maybe in the dev also.
When I home all and it gets to Y0 before X0 it bangs the stops till it gets to X0
Seems like it is waiting to see X endstop and then Y endstop
It should be looking for either and acting appropriately.
If it gets to X0 first there is no banging of stops

**Comment by thinkyhead** [comment]
Sounds just like #2255 – so it's not just a CoreXY issue.

**Comment by ruggb** [comment]
?? all ref I see in 2255 relate to corexy machines

**Comment by ruggb** [comment]
if u r ref to my machine - it is also CoreXY

**Comment by thinkyhead** [comment]
CoreXY also? Ok, let's move the discussion to #2255 then.
