### ISSUE TITLE
[FR] X-Axis twist compensation

### ISSUE THREAD

**Issue by str-dst** [MarlinFirmware/Marlin#22791]
### Is your feature request related to a problem? Please describe.

On printers similar to the Prusa Mk3 that have two separate rails for the X-axis it's a very common problem that these two axis are not 100% parallel to each other.

This slight "twist" in the X-axis causes the probe Z-offset to be different throughout the length of the X-axis. 
Generating a bed mesh will effectively produce useless garbage since the mesh will sit at an angle that does not match the actual bed geometry of the printer.
The issue gets worse the further the leveling probe (a BLtouch for example) is offset to the nozzle on the Y-axis.

Unfortunately this makes the automatic mesh bed leveling in it's current state pretty much useless for almost every printer that uses this kind of X-axis assembly (in most cases it even makes the problem worse than it is with just manual 4-point leveling).

Here's a drawing (made by MauroGil66 over at https://github.com/andrivet/ADVi3pp/issues/248) that shows the issue pretty good:  
![](https://user-images.githubusercontent.com/32619520/90580766-0863da00-e1a0-11ea-9a2c-b92dd0fbbf06.png)

There have been numerous reports of this in the past already indicating that it is a quite common problem.
https://github.com/MarlinFirmware/Marlin/issues/11234
https://github.com/MarlinFirmware/Marlin/issues/12349
https://github.com/MarlinFirmware/Marlin/issues/15206
https://github.com/MarlinFirmware/Marlin/issues/15753
https://github.com/MarlinFirmware/Marlin/issues/18591

### Describe the feature you want

My request (or idea) would be to introduce some kind of X-axis twist compensation in the firmware.

Fixing the hardware (i.e. untwisting the X-axis) is pretty much impossible on most of the printers that use this type of gantry assembly since there is simply no good or accurate method of measuring how parallel the axis are and on many printers it's not even possible to move the two rails indipendently from each other.

Probably the easiest way to implement such a twist compensation would be by setting two different probe Z-offset values.
One for the X-min position and one for the X-max position. The values in between can then simply be calculated as a linear function.
To generate the bed mesh the compensation value simply has to get subtracted from the measured Z-value.
That way the firmware could compensate for the change in probe height when measuring the bed and actually generate a useful mesh.

Another way would be by setting the X-axis twist as an angle value which would then be used to calculate the Z-offset difference using the provided Y-axis offset for the probe. But (imho) that would be a way too overcomplicated solution for such an easy to solve problem.

Those are just some ideas and since I'm not a very well versed programmer I would leave that to those who know how something like this could be implemented 😃 

### Additional context

It seems that something similar was already implemented in the ADVi3pp firmware which is a fork of Marlin

https://github.com/andrivet/ADVi3pp/issues/248

**Comment by DerAndere1** [comment]
The author of the original implementation has some financial interest in his development, so in case someone copies it, (s)he should ask the original autor in advance, even though his code is licensed under the terms of GPL 3.0 (mainbord firmware) and partialy under the terms of CC-BY-4.0 (LCD code).

**Comment by Giuseppe499** [comment]
Hi,

I have the same problem on my TronxyX8 printer with a BLTouch clone sensor and, as @kb-elmo said, a lot of people have the same problem.

Before using `AUTO_BED_LEVELING_BILINEAR` I was using `MESH_BED_LEVELING` and i was getting perfect first layers. So, to solve this issue I propose to add an option to extend the `PROBE_OFFSET_WIZARD` called `PROBE_OFFSET_MESH`. With this feature enabled, instead of computing the z probe offset only in one point with the `PROBE_OFFSET_WIZARD` we could compute the z probe offset in each point of the mesh like we do for `MESH_BED_LEVELING`. This new generated mesh could be used to correct the `AUTO_BED_LEVELING_BILINEAR` mesh. I think this is better than `MESH_BED_LEVELING` because we need to compute this mesh only one time as the probe inconsistencies are consistent (pun intended).

If you think that this feature is useful and can be included in Marlin I'll be happy to try to implement it.

**Comment by Roxy-3D** [comment]
This issue has been a big stumbling block for people for a number of years now.   I very much would like to see a good way to adjust for this in the code.    I don't think I would address it with a new mesh.   It probably would be cleaner to correct the twist on the nozzle and Z-Probe directly and and then use that correct position in the generation of any mesh.   

With that said, people really would be better off fixing the mechanics of their machine.   But if that isn't possible or isn't practical, a firmware fix would be very helpful for those people.   But besides doing the code to actually implement it, we probably need some support code to ascertain how much the axis is twisted for both the Z-Probe and the nozzle.   Those values are going to be different and if we are going to adjust for this problem, we probably should adjust for it in both cases.    And perhaps we need to figure out how this gets addressed on an IDEX machine so we have a complete solution.

If you have working code, or a limping along version of the code, there are people here that would be interesting in helping to clean it up enough that it can be merged.    Especially if (as stated in Discourse) the only issue is too many global variables were used in its creation.   That won't be too hard to remedy if that is all that is wrong with the prototype code.

**Comment by andrivet** [comment]
> The author of the original implementation has some financial interest in his development, so in case someone copies it, (s)he should ask the original autor in advance, even though his code is licensed under the terms of GPL 3.0 (mainbord firmware) and partialy under the terms of CC-BY-4.0 (LCD code).

Just to clarify: I am the "original author". No need to ask me anything since the code is under GPL. The only things not under GPL (but under CC-BY-4.0) are my design of the screens for the LCD panel. But since Marlin does not support it, there is no problem.

**Comment by thisiskeithb** [comment]
Added: https://github.com/MarlinFirmware/Marlin/pull/23238
