### ISSUE TITLE
[BUG] BL Touch probing off bed.

### ISSUE THREAD

**Issue by EitanSchless** [MarlinFirmware/Marlin#22801]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi, when I use any type of bed probing/leveling, the probe goes off the bed then goes down. I've triple checked my probe xyz offsets, and it still doesn't work. For example, I do 'G30 x10 y10', and the probe goes outside the bed. Sorry if I'm not explaining this well. But please help.

### Version of Marlin Firmware

2.0.7.2

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by moham96** [comment]
Have you enabled `Z_SAFE_HOMING` ?

**Comment by EitanSchless** [comment]
No, how can I do that and what will it do?

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
