### ISSUE TITLE
[BUG] Linear advance causes extruder step direction changes during printing

### ISSUE THREAD

**Issue by wap32** [MarlinFirmware/Marlin#22802]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi,
When enabling Linear Advance, there are quick step direction changes in the extruder during printing, which causes the stepper to skip steps. I'm using a Zesty Nimble extruder, which has a reduction ratio so I have a relatively high steps per unit for E0 (2682).
Here is a capture of the step/direction outputs while printing the gyroid infill of a calibration cube:

![2021-09-19-111247_1211x130_scrot](https://user-images.githubusercontent.com/26908392/133922898-e95fa8a3-48e4-4a41-afd7-983024952bf4.png)

Is this expected behavior? This makes Linear Advance unusable as the extruder stepper just isn't able to keep up, and also sounds absolutely terrible. Increasing driver current doesn't really help either.
Turning Linear Advance off, things work as expected.
This behavior happens with both 2.0.9.1 and the latest bugfix.

Thanks in advance for any help!

### Version of Marlin Firmware

bugfix-2.0.x (2021.09.19)

### Electronics

RUMBA32 w/ TMC2130

### Add-ons

Zesty Nimble v1 extruder

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/7191691/config.zip)

**Comment by ellensp** [comment]
This is what linear advance iis meant to do.
No its not compatible with all extruders.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
