### ISSUE TITLE
[BUG] MKS E3 V1.1 does not boot since HAL change

### ISSUE THREAD

**Issue by jesterhead82** [MarlinFirmware/Marlin#22800]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin versions since the HAL merge ( https://github.com/MarlinFirmware/Marlin/pull/21927 ) are not bootable on my E3 v1.1.

Tried with many versions till on of theis week of Bugfix branch. Falling back using maple allows booting.

Nothing spectacular, as you can see in my attached configs, same config works flawless basically in 2.0xx bugfix till HAL marrge, and works with all releases since Hal merge when using maple.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7190594/Marlin.zip)

### Bug Timeline

Failing since https://github.com/MarlinFirmware/Marlin/pull/21927

### Expected behavior

Boot

### Actual behavior

Stops booting before Marlins Bootscreen

### Version of Marlin Firmware

2.0.xx

### Printer model

MKS E3 v1.1

### Electronics

MKS E3 v1.1

**Comment by ellensp** [comment]
Something doesn't add up here....
MOTHERBOARD is set to BOARD_MKS_ROBIN_E3D_V1_1
By default the only env that is valid for that motherboard is env:mks_robin_e3, it doesn't have a maple option.
Sure it can be added, but you made no mention of this.

**Comment by ellensp** [comment]
Please confirm exactly what board you have with a photo of the controller

**Comment by jesterhead82** [comment]
Hello,

attached is a pciture of the board.

I am using mks_robin_e3 env till merge of #21927 together with board BOARD_MKS_ROBIN_E3D_V1_1, and mks_robin_e3_maple together with  BOARD_MKS_ROBIN_E3 since merge of #21927.

So mks_robin_e3 and BOARD_MKS_ROBIN_E3D_V1_1 does not boot for me since the merge of #21927 with the attached boards.

[
![20210919_120221](https://use
![20210919_120244](https://user-images.githubusercontent.com/11690785/133939177-60e63493-edff-4f17-b561-6fdf55be91c6.jpg)
r-images.githubusercontent.com/11690785/133939051-c128e8f7-a4d0-4b52-8665-d84a1e163e52.jpg)
](url)

**Comment by jesterhead82** [comment]
![20210919_120221](https://user-images.githubusercontent.com/11690785/134072125-d7e33f48-42e7-47fc-a63b-e43a33d0d5cc.jpg)

Sorry, front picture was missing in upload.

**Comment by ellensp** [comment]
Was just looking at circuit diagram. 
Seems like the SPI port should be 2 not 3.

Can you try

```CPP
#
# MKS Robin E3/E3D (STM32F103RCT6) with TMC2209
#
[env:mks_robin_e3]
platform                    = ${common_stm32.platform}
extends                     = common_STM32F103RC_variant
board_build.encrypt         = Robin_e3.bin
board_build.offset          = 0x5000
board_upload.offset_address = 0x08005000
build_flags                 = ${common_STM32F103RC_variant.build_flags}
                              -DTIMER_SERVO=TIM5 -DDEFAULT_SPI=2
build_unflags               = ${common_STM32F103RC_variant.build_unflags}
                              -DUSBCON -DUSBD_USE_CDC
monitor_speed               = 115200
debug_tool                  = stlink

```

**Comment by jesterhead82** [comment]
Hi,
tried SPI Pin 2, still not booting
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7201662/Configuration.zip)

**Comment by mks-viva** [comment]
@jesterhead82 What you use LCD?
MKS Robin E3D show booting only on LCD12864 or MKSMINI12864

**Comment by jesterhead82** [comment]
Hello, 
I`m using a MKS12864**B**, was working till merge of #21927.

**Comment by mks-viva** [comment]
Your platformio.ini file env set is what?

**Comment by jesterhead82** [comment]
Hello,

i used mks_robin_e3

**Comment by mks-viva** [comment]
Maybe you only using an old version of the firmware temporarily

**Comment by jesterhead82** [comment]
Hello, 
yes, currently only versions <Jun2021 are working with mks_robin_e3 

Or mks_robin_e3_maple together with BOARD_MKS_ROBIN_E3 if somebody needs to use a newer version

**Comment by ellensp** [comment]
Please confirm the terminology.
Lcd not working is not the same as not booting. 
Does it still communicate over usb?  
Does it give any error messages over usb? 

Working on getting this board but eta is months away.

**Comment by jesterhead82** [comment]
Hello, 

if I use mks_robin_e3 

- LCD shows "Boot" screen, but does not go ahead
- Connection via USB does not work

With mks_robin_e3_maple
- - LCD shows "Boot" screen, then boots into marlin
- USB connection is working

**Comment by jesterhead82** [comment]
Tried today Bugfix Branch, seems to boot again with mks_robin_e3.
