### ISSUE TITLE
[FR] (problem with setup sensorless homing for I axis) 

### ISSUE THREAD

**Issue by rds11080** [MarlinFirmware/Marlin#22809]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi, i have BTT OCTOPUS 1.1 board with 4 axis (X Y Z I), i try to use sensorless homing and it not work on I but working on X Y Z
Also Sensorless only work if i idefine 
`#define USE_XMIN_PLUG`
but when i define 
`#define USE_IMIN_PLUG`
i got 'I_MIN_PIN' was not declared in this scope; did you mean 'X_MIN_PIN'?
Do I need to setup pin for BTT_OCTOPUS V1.1?

### Bug Timeline

new

### Expected behavior

I axis sensorless should work like X Y Z

### Actual behavior

I axis keep trying to move home without stop

### Steps to Reproduce

1. Setup I axis like X Y Z
2. Jog I axis like X Y Z 
3. Homing I axis like X Y Z

### Version of Marlin Firmware

2.0.9

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22649
