### ISSUE TITLE
[BUG] Probing Servo do not staw the probe randomly after homing using probe

### ISSUE THREAD

**Issue by atharvbadkas** [MarlinFirmware/Marlin#22814]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have DIY probe attached to my Ender 3 Idex.
DIY probe is made of a servo attached to a rod which provides signal to optical sensor.

When print start after G28 homing, sometimes the probe left deployed even it starts to print and collides with bed.This occurs randomly.
![16322296078378106266746743594091](https://user-images.githubusercontent.com/57062058/134175898-3156c24b-d60d-48aa-8d37-21b69a696b73.jpg)

I thought this happens due to some noise gets added in probe wiring but it also happened with my 2nd printer.

### Bug Timeline

I had this issue since marlin 2.0.6

### Expected behavior

Probe staw after G28

### Actual behavior

Probe do not staw after G28

### Steps to Reproduce

Get DIY Probing
G28

### Version of Marlin Firmware

V2.0.9.1

### Printer model

Creality Ender 3 pro Idex

### Electronics

Bigtreetech RRF E3 V1.1 with Expansion board

### Add-ons

SG90 Servo, Optical Endstop

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
