### ISSUE TITLE
[BUG] DWIN_CREALITY_LCD Current Position.

### ISSUE THREAD

**Issue by tome9111991** [MarlinFirmware/Marlin#22831]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello
With latest version.
I have strange coordinate after auto homing.
also i cant set Z offset for probe it jumps in 1mm steps.

My bed Size is 230x230x250

I have a ender 3v2 with e3 turbo and stock display.
Tested with `DWIN_CREALITY_LCD` and `DWIN_CREALITY_LCD_JYERSUI`

Edit:

JyersUI
Allready fixed with
https://github.com/MarlinFirmware/Marlin/commit/f6c7fbd1ab62b0c3aa70c971ad6c30d062d3252a
https://github.com/MarlinFirmware/Marlin/commit/b93c3301f2146bed7287ad097b95b53507c35420

Only have issue with `DWIN_CREALITY_LCD` current position and Zoffset show wrong value.

![20210924_164737](https://user-images.githubusercontent.com/57866234/134695754-77b3c7e2-ca93-4147-b021-13effcd099aa.jpg)

~~Btw.
Durring compiling i got
`#warning "Auto-assigned Z2 STEP/DIR/ENABLE_PINs to unused En_STEP/DIR/ENABLE_PINs."`
I use dual Z~~

Config
[config.zip](https://github.com/MarlinFirmware/Marlin/files/7226697/config.zip)

**Comment by tome9111991** [comment]
@thinkyhead 
i guess the bug start at https://github.com/MarlinFirmware/Marlin/commit/5b5a8798f8fe202e86c008088f847a3edb51cc71

i have tried  https://github.com/MarlinFirmware/Marlin/commit/cca3250c3ff8e8ed4277f4918f507ab13913d3b5
this works.

with latest commit from now still same issue.

it looks the . (point) is on wrong place
i have a Probe Z Ofsset by -2.74
LCD show me -27.4

For exemple in DWIN_CREALITY_LCD
![20210925_150059](https://user-images.githubusercontent.com/57866234/134772499-90d66422-9277-46da-b365-227b6053bd54.jpg)

**Comment by tome9111991** [comment]
With last bugfix.

only have the issue on ``DWIN_CREALITY_LCD``


working is:

```
DWIN_CREALITY_LCD_ENHANCED
DWIN_CREALITY_LCD_JYERSUI
DWIN_MARLINUI_PORTRAIT
```


Edit:
In JyersUI
Looks only zOffset is fixed maybe with https://github.com/MarlinFirmware/Marlin/commit/b93c3301f2146bed7287ad097b95b53507c35420
But the current Position (bottom from display) still wrong.

**Comment by The-EG** [comment]
> Btw.
> Durring compiling i got
> #warning "Auto-assigned Z2 STEP/DIR/ENABLE_PINs to unused En_STEP/DIR/ENABLE_PINs."
> I use dual Z

This is just an informational "warning," letting you know that it's assuming you want to use the next unused E driver for Z2. If that's the case you can just ignore.

**Comment by thisiskeithb** [comment]
#23005 was merged. Closing.

**Comment by tome9111991** [comment]
Merge will not fix DWIN_CREALITY_LCD
Still wrong value for current Position and Zoffset

Is only for JyersUI fixed

**Comment by thisiskeithb** [comment]
Hopefully more of this UI code is shared in the future so we don’t have to keep fixing the same bug in multiple places.
