### ISSUE TITLE
[BUG] In touch screen mode files on onboard SD card not visible

### ISSUE THREAD

**Issue by DaddyCRO** [MarlinFirmware/Marlin#22846]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I am sorry if this ticket is already opened, but I was unable to find it.

Recently I updated my 3D printer with Marlin 2.0.9.1 firmware.
Before update, I was running Marlin 2.0.7.2 firmware (everything was working fine).

My HW configuration is:

BIGTREETECH-SKR-E3-DIP-V1.1
BIGTREETECH TFT24 V1.1 (BIGTREE_TFT24_V1.1.27.x firmware)
After Marlin firmware update, I cannot "see" *.gcode files on onboard SD card when they are in some folder (touch screen mode).
I see folder, can enter it, but *.gcode files are not visible in this folder.
If I put *.gcode files in a root of a SD card, files are visible.

If I switch TFT24 to Marlin mode, I "see" all folders and files: everything is as should be.

Since I upgrade main board to a Marlin 2.0.9.1 I also upgrade TFT24 firmware to version 1.1.27 (BIGTREE_TFT24_V1.1.27.x), but behavior is the same.

### Bug Timeline

Marlin 2.0.7.2 was OK, Marlin 2.0.9.1 not OK

### Expected behavior

Folders structure with *.gcode files should be visible in both modes: Marlin and touch screen mode (this was the case until upgrade to a newer Marlin version).

### Actual behavior

After Marlin firmware update, I cannot "see" *.gcode files on onboard SD card when they are in some folder (touch screen mode).
I see folder, can enter it, but *.gcode files are not visible in this folder.
If I put *.gcode files in a root of a SD card, files are visible.

If I switch TFT24 to Marlin mode, I "see" all folders and files: everything is as should be.

Since I upgrade main board to a Marlin 2.0.9.1 I also upgrade TFT24 firmware to version 1.1.27 (BIGTREE_TFT24_V1.1.27.x), but behavior is the same.

### Steps to Reproduce

1. Upgrade main board to version 2.0.9.1
2. Upgrade TFT to 1.1.27
3. Create some folders on a SD card with some *.gcode files in it, also put some *.gcode files to a root of a SD card
4. put a SD card in main board SD card reader
5. switch TFT to touch screen mode
6. try to print from "OnboardSD"
7. *.gcode files in the root of the SD card should be visible
8. *.gcode files inside folders are not visible
9. switch TFT to Marlin mode
10. *.gcode files inside folders and in root are visible

### Version of Marlin Firmware

Marlin 2.0.9.1

### Printer model

Creality CR-20 Pro

### Electronics

BIGTREETECH-SKR-E3-DIP-V1.1 BIGTREETECH TFT24 V1.1 (BIGTREE_TFT24_V1.1.27.x firmware)

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Pronterface

**Comment by eric-s-raymond** [comment]
I have also had intermittent problems with files not visible on the stock firmware of a recent Ender 3V2.  Can't report version number as I upgraded it for BLtouch, but the machine was new in box on 2021-09-26.

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.
