### ISSUE TITLE
[BUG] (Extruder stops moving after first extrude with ADAPTIVE_STEP_SMOOTHING enabled)

### ISSUE THREAD

**Issue by XoBoR** [MarlinFirmware/Marlin#22843]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi there,

Printer: Ender 5 Pro with stock Creality 4.2.2 board

I had the problem that my extruder stopped moving after the first line of the print. After a lot of testing, I found that the Issue was caused by ADAPTIVE_STEP_SMOOTHING. 

I tried the Bugfix branch, the Master branch, and the latest Release, and it happened in all 3 versions.

[UPDATE] I just noticed that exactly the same thing happens when I enable Linear Advance. Any clues as to why this could be happening are appreciated :(

[UPDATE 2] After I realized that this also happens with Linear Advance, I found a lot of Issue reports here. Seems like this is a known Bug... So i guess no Linear Advance for me with this board.

### Bug Timeline

It started when i replaced the Stock firmware with a custom Marlin 

### Expected behavior

I Expected the extruder to extrude normally

### Actual behavior

the extruder stopped moving (and was actually disabled, so i could move it by hand) after the first line.

### Steps to Reproduce

Start a Print and wait for the second line

### Version of Marlin Firmware

2.x & Bugfix & 2.0.9.1

### Printer model

Ender 5 Pro

### Electronics

Stock 4.2.2 Board with BLTouch and Filament Runout detector

### Add-ons

BLTouch and Filament Runout detector

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7232101/Marlin.zip)

**Comment by thisiskeithb** [comment]
Duplicate of #16076
