### ISSUE TITLE
Nozzle is too close after resume print

### ISSUE THREAD

**Issue by Burockk** [MarlinFirmware/Marlin#22852]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

While I am printing something if it is a long print I pause the print and turn off the printer and turn it on again later. However when I do that nozzle is too close to printed model and it melts model. somehow I need to increase Z in order to print correctly.

### Version of Marlin Firmware

bugfix

### Your Slicer

Cura

### Additional information & file uploads

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/7247141/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/7247142/Configuration_adv.txt)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
