### ISSUE TITLE
[BUG] probing gives different result after moving around the bed (delta)

### ISSUE THREAD

**Issue by LVD-AC** [MarlinFirmware/Marlin#22853]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The probe results are erratic (but repeatable); probing 4 points : centre and the 3 towers and immediatly probing the centre again gives about 1mm difference.

### Bug Timeline

somewhere between 1.1.9 and now

### Expected behavior

To give the same result no matter what the moves are in between probing the same point.

### Actual behavior

Gives different result at the same point after moving around. The bigger the moves, the bigger the error.

### Steps to Reproduce

G28 ; home
G30 X0 Y0 ; probe the centre
G30 X60.62 Y-35 ; probe near y-tower
G30 X0 Y+70 ; probe near z-tower
G30 X60.62 Y-35 ; probe near x-tower
G30 X0 Y0 ; probe the centre again

and compare the probe results of the centre point

bugfix-2.0.x

14:22:21.539 : X:0.00 Y:0.00 Z:258.84 E:0.00 Count A:45220B:45220C:45220
14:22:28.977 : **Bed X: 0.00 Y: 0.00 Z: -0.57**
14:22:28.977 : X:0.00 Y:0.00 Z:-0.87 E:0.00 Count A:19249B:19249C:19249
14:22:39.039 : Bed X: 60.62 Y: -35.00 Z: -0.14
14:22:39.039 : X:60.62 Y:-35.00 Z:-0.44 E:0.00 Count A:15918B:21539C:15917
14:22:52.882 : Bed X: 0.00 Y: 70.00 Z: -0.84
14:22:52.882 : X:0.00 Y:70.00 Z:-1.14 E:0.00 Count A:15825B:15835C:21469
14:23:02.194 : Bed X: -60.62 Y: -35.00 Z: 0.02
14:23:02.210 : X:-60.62 Y:-35.00 Z:-0.28 E:0.00 Count A:21555B:15924C:15913
14:23:08.803 : **Bed X: 0.00 Y: 0.00 Z: -1.50**
14:23:08.803 : X:0.00 Y:0.00 Z:-1.80 E:0.00 Count A:19156B:19156C:19156

1.1.9

14:33:22.591 : X:0.00 Y:0.00 Z:258.99 E:0.00 Count X:45234 Y:45234 Z:45234
14:33:30.359 : **Bed X: 0.00 Y: 0.00 Z: -0.16**
14:33:30.362 : X:0.00 Y:0.00 Z:-0.46 E:0.00 Count X:19290 Y:19290 Z:19290
14:33:40.310 : Bed X: 60.62 Y: -35.00 Z: -0.06
14:33:40.315 : X:60.62 Y:-35.00 Z:-0.36 E:0.00 Count X:15925 Y:21547 Z:15923
14:33:50.605 : Bed X: 0.00 Y: 70.00 Z: -0.19
14:33:50.610 : X:0.00 Y:70.00 Z:-0.49 E:0.00 Count X:15889 Y:15899 Z:21534
14:34:03.880 : Bed X: -60.62 Y: -35.00 Z: -0.19
14:34:03.884 : X:-60.62 Y:-35.00 Z:-0.49 E:0.00 Count X:21534 Y:15902 Z:15891
14:34:15.211 : **Bed X: 0.00 Y: 0.00 Z: -0.16**
14:34:15.211 : X:0.00 Y:0.00 Z:-0.46 E:0.00 Count X:19290 Y:19290 Z:19290

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Flsun

**Comment by LVD-AC** [comment]
Also notice that in 1.1.9 the bed is perceived flat at -0.15 +/- 0.05mm and prints a perfect 1st layer; and with exactly the same settings for endstop adjustments, delta radius, delta height and tower angle adjustments copied into bugfix-2.0.x this is no longer the case. I'm pretty sure 1.1.9 reports the correct hights.

**Comment by LVD-AC** [comment]
The last good version is **2.0.7.2** and the bug is still present in Bugfix-2.0.x even with PR #22795; the bug seems to get bigger with consecutive versions.

all tests with FLSUN autocalibrate configuration files and the exact same settings for the default delta parameters:

```
  // Distance between bed and nozzle Z home position
  #define DELTA_HEIGHT 259.14             // (mm) Get this value from G33 auto calibrate

  #define DELTA_ENDSTOP_ADJ { -1.53, -1.70, 0.0 } // Get these values from G33 auto calibrate

  // Horizontal distance bridged by diagonal push rods when effector is centered.
  #define DELTA_RADIUS 100.67              // (mm) Get this value from G33 auto calibrate

  // Trim adjustments for individual towers
  // tower angle corrections for X and Y tower / rotate XYZ so Z tower angle = 0
  // measured in degrees anticlockwise looking from above the printer
  #define DELTA_TOWER_ANGLE_TRIM { +0.17, -0.02, -0.15 } // Get these values from G33 auto calibrate
```


Tested 1.1.9.1: NO BUG

13:09:29.627 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count X:45240 Y:45240 Z:45240
13:09:35.597 : **Bed X: 0.00 Y: 0.00 Z: -0.27**
13:09:35.601 : X:0.00 Y:0.00 Z:-0.37 E:0.00 Count X:19299 Y:19299 Z:19299
13:09:37.594 : Bed X: 56.00 Y: -33.00 Z: -0.18
13:09:37.598 : X:56.00 Y:-33.00 Z:-0.28 E:0.00 Count X:16329 Y:21478 Z:16266
13:09:40.445 : Bed X: 0.00 Y: 65.00 Z: -0.37
13:09:40.445 : X:0.00 Y:65.00 Z:-0.47 E:0.00 Count X:16259 Y:16268 Z:21459
13:09:46.803 : Bed X: -56.00 Y: -33.00 Z: -0.27
13:09:46.806 : X:-56.00 Y:-33.00 Z:-0.37 E:0.00 Count X:21469 Y:16311 Z:16239
13:09:50.707 : **Bed X: 0.00 Y: 0.00 Z: -0.28**
13:09:50.707 : X:0.00 Y:0.00 Z:-0.38 E:0.00 Count X:19298 Y:19298 Z:19298

Tested 2.0.0: NO BUG

14:11:18.365 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count A:45240 B:45240 C:45240
14:11:21.977 : **Bed X: 0.00 Y: 0.00 Z: -0.33**
14:11:21.981 : X:0.00 Y:0.00 Z:-0.43 E:0.00 Count A:19293 B:19293 C:19293
14:11:23.446 : Bed X: 56.00 Y: -33.00 Z: -0.25
14:11:23.446 : X:56.00 Y:-33.00 Z:-0.35 E:0.00 Count A:16322 B:21471 C:16259
14:11:25.494 : Bed X: 0.00 Y: 65.00 Z: -0.42
14:11:25.498 : X:0.00 Y:65.00 Z:-0.52 E:0.00 Count A:16254 B:16263 C:21454
14:11:27.545 : Bed X: -56.00 Y: -33.00 Z: -0.34
14:11:27.545 : X:-56.00 Y:-33.00 Z:-0.44 E:0.00 Count A:21462 B:16304 C:16232
14:11:29.010 : **Bed X: 0.00 Y: 0.00 Z: -0.33**
14:11:29.014 : X:0.00 Y:0.00 Z:-0.43 E:0.00 Count A:19293 B:19293 C:19293

Tested 2.0.1: NO BUG

14:03:13.076 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count A:45240 B:45240 C:45240
14:03:16.692 : **Bed X: 0.00 Y: 0.00 Z: -0.33**
14:03:16.702 : X:0.00 Y:0.00 Z:-0.43 E:0.00 Count A:19293 B:19293 C:19293
14:03:18.157 : Bed X: 56.00 Y: -33.00 Z: -0.27
14:03:18.160 : X:56.00 Y:-33.00 Z:-0.37 E:0.00 Count A:16320 B:21469 C:16257
14:03:20.207 : Bed X: 0.00 Y: 65.00 Z: -0.42
14:03:20.211 : X:0.00 Y:65.00 Z:-0.52 E:0.00 Count A:16254 B:16263 C:21454
14:03:22.258 : Bed X: -56.00 Y: -33.00 Z: -0.34
14:03:22.259 : X:-56.00 Y:-33.00 Z:-0.44 E:0.00 Count A:21462 B:16304 C:16232
14:03:23.729 : **Bed X: 0.00 Y: 0.00 Z: -0.35**
14:03:23.729 : X:0.00 Y:0.00 Z:-0.45 E:0.00 Count A:19291 B:19291 C:19291

Tested 2.0.3: NO BUG

13:54:12.236 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count A:45240 B:45240 C:45240
13:54:15.852 : **Bed X: 0.00 Y: 0.00 Z: -0.33**
13:54:15.856 : X:0.00 Y:0.00 Z:-0.43 E:0.00 Count A:19293 B:19293 C:19293
13:54:17.317 : Bed X: 56.00 Y: -33.00 Z: -0.26
13:54:17.321 : X:56.00 Y:-33.00 Z:-0.36 E:0.00 Count A:16321 B:21470 C:16258
13:54:19.368 : Bed X: 0.00 Y: 65.00 Z: -0.42
13:54:19.372 : X:0.00 Y:65.00 Z:-0.52 E:0.00 Count A:16254 B:16263 C:21454
13:54:21.415 : Bed X: -56.00 Y: -33.00 Z: -0.34
13:54:21.419 : X:-56.00 Y:-33.00 Z:-0.44 E:0.00 Count A:21462 B:16304 C:16232
13:54:22.889 : **Bed X: 0.00 Y: 0.00 Z: -0.35**
13:54:22.889 : X:0.00 Y:0.00 Z:-0.45 E:0.00 Count A:19291 B:19291 C:19291

Tested 2.0.5: NO BUG

11:56:39.815 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count A:45240 B:45240 C:45240
11:56:46.295 : **Bed X: 0.00 Y: 0.00 Z: -0.34**
11:56:46.295 : X:0.00 Y:0.00 Z:-0.44 E:0.00 Count A:19292 B:19292 C:19292
11:56:55.309 : Bed X: 56.00 Y: -33.00 Z: -0.26
11:56:55.309 : X:56.00 Y:-33.00 Z:-0.36 E:0.00 Count A:16321 B:21470 C:16258
11:57:04.455 : Bed X: 0.00 Y: 65.00 Z: -0.42
11:57:04.458 : X:0.00 Y:65.00 Z:-0.52 E:0.00 Count A:16254 B:16263 C:21454
11:57:11.459 : Bed X: -56.00 Y: -33.00 Z: -0.34
11:57:11.459 : X:-56.00 Y:-33.00 Z:-0.44 E:0.00 Count A:21462 B:16304 C:16232
11:57:17.006 : **Bed X: 0.00 Y: 0.00 Z: -0.34**
11:57:17.009 : X:0.00 Y:0.00 Z:-0.44 E:0.00 Count A:19292 B:19292 C:19292

Tested 2.0.7: NO BUG

12:12:22.124 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count A:45240 B:45240 C:45240
12:12:25.749 : **Bed X: 0.00 Y: 0.00 Z: -0.35**
12:12:25.749 : X:0.00 Y:0.00 Z:-0.45 E:0.00 Count A:19291 B:19291 C:19291
12:12:27.218 : Bed X: 56.00 Y: -33.00 Z: -0.29
12:12:27.218 : X:56.00 Y:-33.00 Z:-0.39 E:0.00 Count A:16318 B:21467 C:16255
12:12:29.280 : Bed X: 0.00 Y: 65.00 Z: -0.45
12:12:29.280 : X:0.00 Y:65.00 Z:-0.55 E:0.00 Count A:16251 B:16260 C:21451
12:12:31.327 : Bed X: -56.00 Y: -33.00 Z: -0.36
12:12:31.342 : X:-56.00 Y:-33.00 Z:-0.46 E:0.00 Count A:21460 B:16302 C:16230
12:12:32.796 : **Bed X: 0.00 Y: 0.00 Z: -0.35**
12:12:32.811 : X:0.00 Y:0.00 Z:-0.45 E:0.00 Count A:19291 B:19291 C:19291

Tested 2.0.7.2: NO BUG

13:22:36.747 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count A:45240 B:45240 C:45240
13:22:40.382 : **Bed X: 0.00 Y: 0.00 Z: -0.34**
13:22:40.386 : X:0.00 Y:0.00 Z:-0.44 E:0.00 Count A:19292 B:19292 C:19292
13:22:41.852 : Bed X: 56.00 Y: -33.00 Z: -0.28
13:22:41.857 : X:56.00 Y:-33.00 Z:-0.38 E:0.00 Count A:16319 B:21468 C:16256
13:22:43.911 : Bed X: 0.00 Y: 65.00 Z: -0.45
13:22:43.915 : X:0.00 Y:65.00 Z:-0.55 E:0.00 Count A:16251 B:16260 C:21451
13:22:45.968 : Bed X: -56.00 Y: -33.00 Z: -0.34
13:22:45.971 : X:-56.00 Y:-33.00 Z:-0.44 E:0.00 Count A:21462 B:16304 C:16232
13:22:47.437 : **Bed X: 0.00 Y: 0.00 Z: -0.36**
13:22:47.441 : X:0.00 Y:0.00 Z:-0.46 E:0.00 Count A:19290 B:19290 C:19290

Tested 2.0.8: Can't test - probing bugged

12:35:07.739 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count A:45240 B:45240 C:45240
12:35:08.453 : **Error:Probing Failed**
12:35:08.454 : X:0.00 Y:0.00 **Z:212.53** E:0.00 Count A:40589 B:40589 C:40589
12:35:09.283 : **Error:Probing Failed**
12:35:09.287 : X:56.00 Y:-33.00 **Z:212.52** E:0.00 Count A:37609 B:42758 C:37546
12:35:10.702 : **Error:Probing Failed**
12:35:10.706 : X:0.00 Y:65.00 **Z:212.52** E:0.00 Count A:37558 B:37567 C:42758
12:35:12.259 : **Error:Probing Failed**
12:35:12.262 : X:-56.00 Y:-33.00 **Z:212.52** E:0.00 Count A:42758 B:37600 C:37528
12:35:13.728 : **Error:Probing Failed**
12:35:13.731 : X:0.00 Y:0.00 **Z:212.52** E:0.00 Count A:40588 B:40588 C:40588

Tested 2.0.8.1: bug present (0.59mm difference at origin)

13:01:53.849 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count A:45240 B:45240 C:45240
13:01:57.480 : **Bed X: 0.00 Y: 0.00 Z: -0.56**
13:01:57.480 : X:0.00 Y:0.00 Z:-0.66 E:0.00 Count A:19270 B:19270 C:19270
13:02:14.409 : Bed X: 56.00 Y: -33.00 Z: -0.11
13:02:14.409 : X:56.00 Y:-33.00 Z:-0.21 E:0.00 Count A:16336 B:21485 C:16273
13:02:24.314 : Bed X: 0.00 Y: 65.00 Z: -0.94
13:02:24.318 : X:0.00 Y:65.00 Z:-1.04 E:0.00 Count A:16202 B:16211 C:21402
13:02:39.585 : Bed X: -56.00 Y: -33.00 Z: 0.26
13:02:39.589 : X:-56.00 Y:-33.00 Z:0.16 E:0.00 Count A:21522 B:16364 C:16292
13:02:47.505 : **Bed X: 0.00 Y: 0.00 Z: -1.15**
13:02:47.509 : X:0.00 Y:0.00 Z:-1.25 E:0.00 Count A:19211 B:19211 C:19211

Tested 2.0.9.1: bug present (0.77mm difference at origin)

11:38:54.867 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count A:45240B:45240C:45240
11:39:04.074 : **Bed X: 0.00 Y: 0.00 Z: -0.51**
11:39:04.074 : X:0.00 Y:0.00 Z:-0.61 E:0.00 Count A:19275B:19275C:19275
11:39:14.970 : Bed X: 56.00 Y: -33.00 Z: -0.22
11:39:14.975 : X:56.00 Y:-33.00 Z:-0.32 E:0.00 Count A:16325B:21474C:16262
11:39:36.764 : Bed X: 0.00 Y: 65.00 Z: -0.89
11:39:36.769 : X:0.00 Y:65.00 Z:-0.99 E:0.00 Count A:16207B:16216C:21407
11:39:44.831 : Bed X: -56.00 Y: -33.00 Z: -0.00
11:39:44.834 : X:-56.00 Y:-33.00 Z:-0.10 E:0.00 Count A:21496B:16338C:16266
11:39:50.779 : **Bed X: 0.00 Y: 0.00 Z: -1.28**
11:39:50.783 : X:0.00 Y:0.00 Z:-1.38 E:0.00 Count A:19198B:19198C:19198

Tested Bugfix-2.0.x with PR #22795 : bug present (0.90mm difference at origin)

13:44:24.070 : X:0.00 Y:0.00 Z:259.04 E:0.00 Count A:45240B:45240C:45240
13:44:27.723 : **Bed X: 0.00 Y: 0.00 Z: -0.59**
13:44:27.723 : X:0.00 Y:0.00 Z:-0.69 E:0.00 Count A:19267B:19267C:19267
13:44:29.184 : Bed X: 56.00 Y: -33.00 Z: -0.13
13:44:29.188 : X:56.00 Y:-33.00 Z:-0.23 E:0.00 Count A:16334B:21483C:16271
13:44:31.282 : Bed X: 0.00 Y: 65.00 Z: -1.06
13:44:31.282 : X:0.00 Y:65.00 Z:-1.16 E:0.00 Count A:16190B:16199C:21390
13:44:33.295 : Bed X: -56.00 Y: -33.00 Z: 0.38
13:44:33.298 : X:-56.00 Y:-33.00 Z:0.28 E:0.00 Count A:21534B:16376C:16304
13:44:36.336 : **Bed X: 0.00 Y: 0.00 Z: -1.49**
13:44:36.336 : X:0.00 Y:0.00 Z:-1.59 E:0.00 Count A:19177B:19177C:19177

**Comment by LVD-AC** [comment]
This problem still exists

**Comment by dellipse** [comment]
Problem still exists.

**Comment by LVD-AC** [comment]
still no change
