### ISSUE TITLE
[BUG] Latest Ender 3V2 main screen on BLtouch firmware has no info choice

### ISSUE THREAD

**Issue by eric-s-raymond** [MarlinFirmware/Marlin#22859]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

The "Info" item has gone from the main console selections, and I can't find it in any submenus.

This makes good bug-reporting practice unreasonably difficult.

This is on the release CVreality makes available as
"26 Mar, 2021 Ender-3 V2-Marlin-2.0.1-HW-4.2.2-mainboard-V1.1.2-Compatible with BLTouch and filament detection"

### Bug Timeline

When I upgraded to BLTouch firmware two days ago.

### Expected behavior

I should have seen an Info choice on the main screen.

### Actual behavior

It was replaced by a bed-leveling choice that probably ough to be under "Prepare".

### Steps to Reproduce

Power up the Ender 3V2 and look at the console.

### Version of Marlin Firmware

1.0.2

### Printer model

Ender 3V2

### Electronics

Stock electronics

### Add-ons

BlTouch sensor

### Bed Leveling

ABL Linear grid

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by cp2004** [comment]
If you aren't using Marlin firmware *built from this repository*, there's nothing that can be done. If Creality provide the firmware, then it has not been built out of this repository directly. Follow through with the answer you put at the top of your bug report and test it with the latest code from the `bugfix-2.0.x` branch before submitting any bug reports.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
