### ISSUE TITLE
[BUG] 3dTouch crashing into bed on homing process

### ISSUE THREAD

**Issue by jonhysfl** [MarlinFirmware/Marlin#22854]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

My configuration : [Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7253010/Marlin.zip)

Good morning!

I've installed a 3DTouch on my Anet A8 Plus, configured it following this guide: http://www.unix-master.com/2021/04/anet-a8-plus-bltouch.html , but the nozzle keeps crashing into the bed, not identifying the signal to home the z axis.

Here's the video of how this is happening:
https://www.youtube.com/watch?v=l3gOp1uhAEY

### Bug Timeline

When i installed the 3DTouch.

### Expected behavior

Expected it to home the z axis based on the pulse of the sensor.

### Actual behavior

It keeps crashing the probe into the bed.

### Steps to Reproduce

Install the 3DTouch on Anet A8 Plus
Test the probe , deploy and retract
Home the XYZ axis

### Version of Marlin Firmware

2.0.9x

### Printer model

Anet A8 Plus

### Electronics

Stock

### Add-ons

3dTouch

### Bed Leveling

ABL Bilinear mesh

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
