### ISSUE TITLE
[BUG] Mesh_Edit Gfx_Overlay causes compile error

### ISSUE THREAD

**Issue by rq3** [MarlinFirmware/Marlin#22875]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Compiling Marlin with the "Mesh_Edit_GFX_Overlay" defined causes a compile failure ONLY if the MarlinUI is invoked. It does not cause a failure under the ClassicUI.

#error "MESH_EDIT_GFX_OVERLAY requires AUTO_BED_LEVELING_UBL and a Graphical LCD."

### Bug Timeline

old

### Expected behavior

I expect Marlin to compile under any flavor of MarlinUI.

### Actual behavior

Marlin will not compile with this function enabled under MarlinUI, even though both UBL and a Graphical TFT (NOT Graphical LCD) are defined. It compiles fine under ClassicUI.

Compiled with configuration files from the delta/Anycubic/Predator example.

### Version of Marlin Firmware

2.0.9.2 (and earlier)

### Printer model

Anycubic Predator

### Electronics

Stock Trigorilla-Pro

### Add-ons

none

### Bed Leveling

UBL Bilinear mesh

**Comment by ellensp** [comment]
It not a compile error as such. Its a deliberate #error added by the programmers that this combination is invalid
