### ISSUE TITLE
[BUG] EXTENSIBLE_UI: Wrong messages displayed during advanced pause

### ISSUE THREAD

**Issue by andrivet** [MarlinFirmware/Marlin#22873]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

A break is missing in each line of `MarlinUI::pause_show_message` and as a consequence, only the last message ("RESUME OPTIONS:") is sent to the EXTENSIBLE_UI code.
This bug was introduced on July 10, 2021 by commit 10d0bbcd5ff4bcbb3cd05f9998b393ba370ca848 and PR #22164

### Bug Timeline

July 10, 2021

### Expected behavior

Each step of the Advance Pause sequence should display a different message.

### Actual behavior

Each step of the Advance Pause sequence displays the same and wrong message.

### Version of Marlin Firmware

2.0.9.1

**Comment by thisiskeithb** [comment]
#22874 was merged. Closing.
