### ISSUE TITLE
[BUG] Power Loss Recovery error compiling with POWER_LOSS_RECOVER_ZHOME

### ISSUE THREAD

**Issue by sergiofagundes** [MarlinFirmware/Marlin#22872]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Power Loss Recovery

Can't compile, error: is not needed on a machine that homes to ZMAX.

### Bug Timeline

new

### Expected behavior

Accepts the option: 
#define POWER_LOSS_RECOVER_ZHOME

I'm using a Delta with a Orbiter extruder, and when the motors are disable the arms loose positions because of the extra wheight of the extruder. So a home is necessary to resume the printing after a power loss recovery.

### Actual behavior

Can't compile on a Delta printer

### Steps to Reproduce

Can't compile

### Version of Marlin Firmware

2.0.9.1

### Printer model

Kossel Delta

### Electronics

Mks Robin E3D

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by sergiofagundes** [comment]
Just a note: My UPS board in combination of power supply can supply power after a power loss for about 10 seconds, just enough to move Z very high (i'm using POWER_LOSS_ZRAISE 50), so homing will not hit any piece printed.

If I remove this compile error in sanitycheck will it do a XYZ home ?

**Comment by ellensp** [comment]
I would change Marlin/src/inc/SanityCheck.h

from 

```CPP
  #elif ENABLED(POWER_LOSS_RECOVER_ZHOME) && Z_HOME_TO_MAX
    #error "POWER_LOSS_RECOVER_ZHOME is not needed on a machine that homes to ZMAX."
```
To

```CPP
  #elif ENABLED(POWER_LOSS_RECOVER_ZHOME) && Z_HOME_TO_MAX && !ENABLED(DELTA)
    #error "POWER_LOSS_RECOVER_ZHOME is not needed on a machine that homes to ZMAX."
```
So deltas can do this.  

But I have no idea if code will work correctly

**Comment by sergiofagundes** [comment]
Got it.

In fact the POWER_LOSS_RECOVER_ZHOME on delta/kossel isn't needed, because power loss resume will home X & Y and deltas only home to Z. So I tested it and it works without POWER_LOSS_RECOVER_ZHOME.

The resume printing begins but the layer was a little higher (about 1-2 layers), I will try to fix this.
