### ISSUE TITLE
Delta auto calibration

### ISSUE THREAD

**Issue by renzaaa** [MarlinFirmware/Marlin#22883]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Delta auto calibration does not work (G33). Probed 3 points on the bed and stopped.
Older version of marlin was working.

### Version of Marlin Firmware

Latest bugfix-2.0.x or stable 2.0.x

### Printer model

Anycubic linear plus

### Electronics

skr 1.4 turbo

**Comment by maevebaksa** [comment]
Hi @renzaaa I have this exact problem! How did you fix it as I see you closed it. Please help!

**Comment by thisiskeithb** [comment]
> Hi @renzaaa I have this exact problem! How did you fix it as I see you closed it. Please help!

@maevebaksa Please see https://github.com/MarlinFirmware/Marlin/issues/22886

**Comment by maevebaksa** [comment]
@thisiskeithb Thank you for this. I just found this thread maybe 1-2 minutes ago. Hopefully the proposed changes will be merged soon. Cheers!
