### ISSUE TITLE
[BUG] Delta Anycubic Kossel Linear Plus - Delta Calibration broken in 2.0.9.2

### ISSUE THREAD

**Issue by ChinChillaSPb** [MarlinFirmware/Marlin#22886]
### Did you test the latest `bugfix-2.0.x` code?

Yes, the problem is still exist!

### Bug Description

Using default branch 2.0.x and correct config from corect configuration branch (2.0.9.2) (in configuration.h/_adv.h it marked as: "CONFIGURATION_H_VERSION 02000902", compiled w/o errors in arduino ide and vs code ide w platformio. also w/o errors. The problem is when you try to delta cal it stops after 4 point of 4 probes, and says "stow z-probe". always. nothing helps.

i'll trtried "bugfix branch" and the problem is still exists

i using Anycubic Kossel Linear Plus with Ultrabase hb and probe v2.

also init eeprom of course, restored def.sett.

also cold reboot.

### Bug Timeline

new old bug

### Steps to Reproduce

1. compile with correct conf by vs code or arduino ide (vs code + platformio - much faster)
2. init eeprom
3. try to delta calibration on Kossel Linear Plus (all other my 3dp is standart geometry)
4. it stops with "stow z-probe" error after 4 point of 4 probes.

### Version of Marlin Firmware

2.0.9.2

### Printer model

Anycubic Kossel Linear Plus

### Electronics

stock

### Add-ons

probe v2, ultrabase hb

### Bed Leveling

UBL Bilinear mesh

### Additional information & file uploads

stock example config from the 2.0.9.2 branch

**Comment by viper93458** [comment]
Not exactly the same issue for me but sensorless PROBING with skr 1.1 pro and 2209s on a delta doesn't work. Plows into the bed. May be related may not be. Just throwing it out there  :(

Sensorless homing does work though.

**Comment by ChinChillaSPb** [comment]
also now back to 2.0.9.1 and confirm that problem is gone.
so the problem is on the 2.0.9.2

**Comment by ChinChillaSPb** [comment]
> Not exactly the same issue for me but sensorless PROBING with skr 1.1 pro and 2209s on a delta doesn't work. Plows into the bed. May be related may not be. Just throwing it out there :(
> 
> Sensorless homing does work though.

i see that the problem is not related to probe type (i think because probing uses the same gcode command).
as you can see, i'm also must back to 9.1 so i can recommend you to get back to 9.1 too for a while.

**Comment by renzaaa** [comment]
The same problem for my anycubic delta printer with 2.0.9.2 marlin version.
Delta calibration in Tevo little monster stops on iteration 1.

**Comment by viper93458** [comment]
I am hoping I'm not the only one with sensorless PROBING issues on the delta. :)

I will watch this thread for fun.

**Comment by LVD-AC** [comment]
> also now back to 2.0.9.1 and confirm that problem is gone. so the problem is on the 2.0.9.2

Could you test PR #22795, we're working on it...

**Comment by LVD-AC** [comment]
@ChinChillaSPb , @renzaaa 

> also now back to 2.0.9.1 and confirm that problem is gone. so the problem is on the 2.0.9.2

This is a known bug. Use PR #22795 to fix this.

**Comment by LVD-AC** [comment]
@viper93458 

> Not exactly the same issue .... Plows into the bed.

My printer uses the nozzle and a microswitch as probe and plows into the bed as well since 2.0.8. Increase the value of `Z_CLEARANCE_BETWEEN_PROBES` but also see #22853 for trying to find the needle in the haystack that causes this.

**Comment by renzaaa** [comment]
> @ChinChillaSPb , @renzaaa
> 
> > also now back to 2.0.9.1 and confirm that problem is gone. so the problem is on the 2.0.9.2
> 
> This is a known bug. Use PR #22795 to fix this.

Working now, thanks.

**Comment by nionio6915** [comment]
Could you please remove you comment from my issue thread? Your probelm is not applicable to my submission. Thanks

**Comment by LVD-AC** [comment]
@renzaaa I don't think this was intended for you; but glad to know the fix works for you.

**Comment by jneilliii** [comment]
I have this issue as well with my flsun q5. Probing only happens in a small diameter of the bed and then just stops.

**Comment by LVD-AC** [comment]
Have you tried the fix in PR #22795 ?

**Comment by jneilliii** [comment]
Not yet, but I will attempt over the weekend. Seems like the PR was filled with more than just a fix for this issue?

**Comment by sjasonsmith** [comment]
Closing, since this has been fixed in #22795.
