### ISSUE TITLE
[BUG] (Z axis freezes)

### ISSUE THREAD

**Issue by Enzo-Enz** [MarlinFirmware/Marlin#22906]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I updated my printer from 2.0.9.1 to 2.0.9.2 

when I start first print after updating,My Z axis freezed I increased the ampere with the potansiyometre on stepper driver It start moving but It makes a loud and bad sound when I reduce the ampere It freezes I tested another ramps another arduino another stepper driver but the problem is still exist while before updating everything was ok
(I use drv8825 for stepper driver with 32 microsteps and standard M5 screw for Z axis and 8000 steps/mm)

### Bug Timeline

new

### Version of Marlin Firmware

2.0.9.2

### Printer model

DIY printer

### Your Slicer

Cura

### Additional information & file uploads

https://user-images.githubusercontent.com/75531691/136433171-42562edb-bc12-4400-b762-7053543e627d.mp4

**Comment by ellensp** [comment]
Nevermind... I need to learn to read...

**Comment by ellensp** [comment]
### Electronics
RAMPS
DRV8825

**Comment by ellensp** [comment]
What has probably happened is your old firmware settings where superseded with EEPROM settings that you lost when you upgraded the firmware.
Check your max feedrates in Z

**Comment by Enzo-Enz** [comment]
I guess you are right bro there is some problems with EEPROM,because in LCD steps/mm for Z axis is shown 8000 steps/mm but when I click on that It is shown 1446.4 steps/mm is that normal if It is not Is there any way to solve the issue?


![WhatsApp Image 2021-10-08 at 10 00 57](https://user-images.githubusercontent.com/75531691/136509812-4c92ef15-5153-4529-af6e-fbfc7e8c2654.jpeg)

![WhatsApp Image 2021-10-08 at 10 00 58](https://user-images.githubusercontent.com/75531691/136509826-805801ce-456c-4069-ae29-a6a479e6c539.jpeg)

**Comment by WolvenScout** [comment]
I believe I'm having a similar issue. My Z motors click after updating to 2.0.9.2. I was prompted to clear the EPROM, which I did. I disconnected the Z-Axis screw rods to see if the noise would go away when the load was removed, but it did not.

https://imgur.com/a/wJYey4z
