### ISSUE TITLE
[BUG] Improper assignment of steppers on BTT Octopus

### ISSUE THREAD

**Issue by kj4sst** [MarlinFirmware/Marlin#22912]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When building for the Octopus with 3 or more z axis steppers the assignment skips one of the stepper positions, making it so that only 7 out of the 8 drivers can be used.  I have tried the latest bugfix and while the issue has been solved, it was solved by heavily modifying "pins_postprocess.h" to check for exceptions.  Another, hopefully simpler, way to fix this issue is to bring the stepper assignment in "pins_BTT_OCTOPUS_V1_common.h" into alignment with the other board declarations.  The issue is caused due to the fact that in "pins_BTT_OCTOPUS_V1_common.h" both "Z" and "Z2" are defined, if all instances of "Z2" are removed and "E4" is added, for example Z2 -> E0, E0 -> E1, etc... then Marlin will compile without modifying "pins_postprocess.h".

### Bug Timeline

Older issue, I found this bug 3-4 weeks ago.

### Expected behavior

I expected the stepper drivers to be assigned properly.

### Actual behavior

When assigning steppers, specifically with 3 or more z steppers, one of the stepper positions would be skipped leaving the board with 7 functional steppers instead of 8.

### Steps to Reproduce

1. Setup Marlin for BTT Octopus V1
2. Enable 3 or more z steppers and then fill the rest of the positions with extruder motors (making for a total of 8 steppers enabled in Marlin)
3. Compile

### Version of Marlin Firmware

2.0.x

### Printer model

Custom

### Electronics

BTT Octopus

### Bed Leveling

UBL Bilinear mesh

### Additional information & file uploads

[ConfigurationFiles.zip](https://github.com/MarlinFirmware/Marlin/files/7315665/ConfigurationFiles.zip)

**Comment by ellensp** [comment]
Are you sure you tried bugfix? As this very things was fixed in https://github.com/MarlinFirmware/Marlin/pull/22771

**Comment by kj4sst** [comment]
I have tried the bugfix, which did solve the issue.  However, the fix which was implemented causes the compiler to throw warnings and introduces complications to "pins_postprocess.h". I was simply suggesting a different, hopefully simpler way of fixing the issue.

**Comment by ellensp** [comment]
Please read the comments in the above PR as to why this was done this way and not your way
