### ISSUE TITLE
[BUG] 3d printer doesn't see files ( on sd card ) written on Windows 11

### ISSUE THREAD

**Issue by vladT0** [MarlinFirmware/Marlin#22917]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I updated my notebook from Windows 10 to Windows 11. Now my 3d printer can not recognize files written to the sd-card using this operation system. I have tried several SD cards, tried format it as FAT and FAT32. 3d printer can still recognize old files written by Windows 10. 3d printer can recognize folders, created on Windows 11.

### Expected behavior

I expect no difference between windows 10 and windows 11 file system for sd cards.

### Steps to Reproduce

1) Install windows 11 or update from windows 10 to windows 11
2) write STL files to the SD CARD
3) insert SD card to the printer.

### Version of Marlin Firmware

2.0

### Printer model

Prusa

### Your Slicer

Slic3r

### Host Software

SD Card (headless)

**Comment by ellensp** [comment]
When long files names are written the os also writes a 8.3 name.  Marlin needs this 8.3 name, It sounds like windows 11 is not doing this.
Have a read of this, see if it also applies to 11 https://www.tecklyfe.com/windows-server-tip-disable-8-3-naming-strip-existing-short-names/

**Comment by vladT0** [comment]
Yes, I had this idea too, but seems 8.3 naming is here. See name : ADAPTE~1.STL
`E:\>dir /x                                                                                                                                                     Volume in drive E is PRUSA                                                                                                                                    Volume Serial Number is C65F-DE79                                                                                                                                                                                                                                                                                           Directory of E:\                                                                                                                                                                                                                                                                                                           17/06/2021  20:57            52,784              B.STL                                                                                                        17/06/2021  20:57            52,784 ADAPTE~1.STL adapter_123.STL                                                                                                             2 File(s)        105,568 bytes                                                                                                                                0 Dir(s)   1,961,689,088 bytes free  `

**Comment by vladT0** [comment]
Seems it was problem only with files where name is short and windows did not duplicate it as 8.3 naming. I close now ticket.
