### ISSUE TITLE
IDEX - Duplicate Mirror Mode not working

### ISSUE THREAD

**Issue by selvakumaran2016** [MarlinFirmware/Marlin#22922]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi all,

We are using IDEX machines. Our previous machine uses the MKS Rumba32 board with Marlin 2.0.7.

We are using Ideamaker for Slicing. For the Start Gcode, we have used customized G-codes to get Duplicate or Mirror modes. For the last 6 months, it was working without any issues.

Recently we bought a BTT Octopus V1.1 board. We first updated Marlin Bugfix. It was working with Single and Dual modes, But for Duplicate and Mirror modes it was giving multiple issues. 

Today we updated the latest Marlin 2.0.9.2. Hoping that it would solve the issue. But the same problem.

The following are the Start Gcode given in Ideamaker (Which works perfectly for the Rumba32 board):
M109  T1  S{temperature_extruder2} ;  
G21 ;
G90 ;
M82 ;
M107 ;

G28 ; 
G29 ;

T0 ; 
M605 S2 X100; 
G28 X; 

When we use the same in BTT Octopus + Marlin 2.0.9.2 board, we are facing the following issues: (Bowden configuration)
Duplicate :
1. Temperature is reaching the set temperature for both hot ends.
2. G28 homing is happening followed by Auto bed leveling
3. Home only X-axis.
4. Now Right hotend has to come towards 0 position, but it is not happening.
5. Left Hotend comes into the print position, but the Right Hotend is trying to move ahead of the X_max endstop (Trying to crash the endstop). 
6. Then it is trying to print. Only the Left Extruder is rotating, but the Right extruder is not moving.
7. When pausing the print and trying to Extrude the Right extruder it is showing the error 'T1 Invalid Extruder'.

Mirror:
1. Temperature is reaching the set temperature for both hot ends.
2. G28 homing is happening followed by Auto bed leveling
3. Home only X-axis.
4. Now Right hotend comes to the mirrored position of Left.
5. Both the hotends are moving. But only the left extruder is working, right extruder is not working.
6. When pausing the print and trying to Extrude the Right extruder it is showing the error 'T1 Invalid Extruder'. 

Manually both the extruders are extruding and retracting the filaments.
Even in Dual mode, both the extruders are working.

Machine information:
Prusa style with:
Dual X
Single Y
Dual Z (Enabled Dual Z and Auto align)
Titan clone extruder
E3d Bowden hot end

Thanks in advance

### Bug Timeline

30 days back

### Expected behavior

Right extruder should be able to print in Duplicate and in Mirror mode

### Actual behavior

But the Right Hotend is trying to move ahead of the X_max endstop (Trying to crash the endstop). 

### Version of Marlin Firmware

2.0.9.2

### Printer model

Prusa style IDEX

### Electronics

BTT Octopus 1.1

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

IdeaMaker

### Host Software

SD Card (headless)

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7317773/Marlin.zip)

**Comment by InsanityAutomation** [comment]
Bugfix homes correctly, it was reported last night that in some conditions it was still moving the wrong direction so I will be doing a bit more testing hopefully later tonight or tomorrow.

**Comment by InsanityAutomation** [comment]
#22920 is still open but whats referenced here fixed in the merge yesterday with #22914 . Please try the current bugfix code instead of release and follow any additional issues in the existing bug.

**Comment by selvakumaran2016** [comment]
I appreciate the quicker support. I used the latest bugfix and now Idex Duplicate is now working. Right hot end comes to Duplicate position and starts printing.

Both hot ends are heating also.

i have to disable this line to get the Right hot end working.

//#define DISABLE_INACTIVE_EXTRUDER

Then both the extruders also working.

**Comment by InsanityAutomation** [comment]
Ok, then the decision is between DISABLE_INACTIVE_EXTRUDER being blocked for IDEX with a sanity check or explicitly monitoring for duplication modes and blocking it at runtime. Thats a separate item than the above but still a valid bug.

**Comment by InsanityAutomation** [comment]
Added a change to #22925 that should address this as well, however Im out and unable to test at the moment.

**Comment by selvakumaran2016** [comment]
#22538 In this discussion, someone commented like this
'E1 does not extrude if DISABLE_INACTIVE_EXTRUDER is defined.'
Then I thought of disabling it. It worked.

Even I felt that this is not the right way. 

I request you to re-open this issue. I will be happy to test the bug fix.

**Comment by InsanityAutomation** [comment]
If the PR above that has code for the fix already in it doesnt resolve the issue, I can reopen it. I believe this may also be part of the issue with the bitmasks on multi nozzle duplication so this likely needs a bit of attention regardless...
