### ISSUE TITLE
[BUG] Compilation issue for MKS RobinNAnoV1.2

### ISSUE THREAD

**Issue by madurani** [MarlinFirmware/Marlin#22927]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Attempt of compilation latest marlin firmware finished with errors:

Marlin/src/lcd/extui/mks_ui/draw_preHeat.cpp: In function 'void event_handler(lv_obj_t*, lv_event_t)':
Marlin/src/lcd/extui/mks_ui/draw_preHeat.cpp:164:24: error: 'class Temperature' has no member named 'setTargetBed'; did you mean 'setTargetHotend'?
  164 |         thermalManager.setTargetBed(PREHEAT_2_TEMP_BED);
      |                        ^~~~~~~~~~~~
      |                        setTargetHotend
Marlin/src/lcd/extui/mks_ui/draw_preHeat.cpp:170:24: error: 'class Temperature' has no member named 'setTargetBed'; did you mean 'setTargetHotend'?
  170 |         thermalManager.setTargetBed(PREHEAT_1_TEMP_BED);
      |                        ^~~~~~~~~~~~
      |                        setTargetHotend
Marlin/src/lcd/extui/mks_ui/draw_print_file.cpp: In function 'uint32_t lv_open_gcode_file(char*)':
Marlin/src/lcd/extui/mks_ui/draw_print_file.cpp:379:1: warning: no return statement in function returning non-void [-Wreturn-type]
  379 | }
      | ^
Marlin/src/lcd/extui/mks_ui/draw_print_file.cpp: In function 'void lv_gcode_file_seek(uint32_t)':
Marlin/src/lcd/extui/mks_ui/draw_print_file.cpp:463:3: error: 'card' was not declared in this scope
  463 |   card.setIndex(pos);
      |   ^~~~
*** [.pio/build/mks_robin_nano35/src/src/lcd/extui/mks_ui/draw_preHeat.cpp.o] Error 1
*** [.pio/build/mks_robin_nano35/src/src/lcd/extui/mks_ui/draw_print_file.cpp.o] Error 1
Marlin/src/lcd/extui/mks_ui/draw_printing.cpp: In function 'void setProBarRate()':
Marlin/src/lcd/extui/mks_ui/draw_printing.cpp:280:12: warning: 'rate_tmp_r' may be used uninitialized in this function [-Wmaybe-uninitialized]
  280 |     rate = rate_tmp_r / gCfgItems.curFilesize;
      |            ^~~~~~~~~~
Marlin/src/lcd/extui/mks_ui/draw_printing.cpp:286:13: warning: 'rate_tmp_r' may be used uninitialized in this function [-Wmaybe-uninitialized]
  286 |     rate = (rate_tmp_r - (PREVIEW_SIZE + To_pre_view)) * 100 / (gCfgItems.curFilesize - (PREVIEW_SIZE + To_pre_view));

### Actual behavior

Compilation crashed

### Steps to Reproduce

Download new firmware
Set up bugfix-2.0.x branch
modify config files:

platformio.ini:
default_envs = mks_robin_nano35
Configuation.h:
#define SERIAL_PORT 3
#define MKS_ROBIN_TFT35
#define MOTHERBOARD BOARD_MKS_ROBIN_NANO
#define TFT_LVGL_UI
#define TOUCH_SCREEN
Configuation_adv.h:
//#define USB_FLASH_DRIVE_SUPPORT
//#define MULTI_VOLUME

### Version of Marlin Firmware

2.0.9.2

**Comment by ellensp** [comment]
mks_ui requires that you have a heated bed.

**Comment by ellensp** [comment]
And SDSUPPORT needs to be enabled

**Comment by madurani** [comment]
> mks_ui requires that you have a heated bed.

Which option is it?

**Comment by ellensp** [comment]
#define TEMP_SENSOR_BED needs a non 0 number

**Comment by madurani** [comment]
Very thanks, it work.

**Comment by ellensp** [comment]
Add a PR to check both heated bed and SDSUPPORT are enabled with this UI and warn the user if they are not.
