### ISSUE TITLE
[FR] Crash detection

### ISSUE THREAD

**Issue by tome9111991** [MarlinFirmware/Marlin#22924]
### Describe the feature you want

Hello
I'm not sure if the feature is feasible. 
some drivers support sensorless homing like TMC2209 it may be possible to use this feature as a kind of crash detection. 

e.g. when the nozzle moves into the bed during homing. or an axis is blocked while printing.
 that he goes in emergency.

### Additional context

It may also be possible to detect when the belt has torn.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/8765
