### ISSUE TITLE
FILAMENT_CHANGE_RESUME_ON_INSERT 

### ISSUE THREAD

**Issue by madurani** [MarlinFirmware/Marlin#22934]
I tested new functionality option with "Filament replace": 
`#define FILAMENT_CHANGE_RESUME_ON_INSERT // Automatically continue / load filament when runout sensor is triggered again.`
, but not work for me. After inserting filament via sensor is again needed press "continue button" on display.

RUNOUT sensor should be work correctly(outputs from M119):
Filament is in extruder:
```
Recv: Reporting endstop status
Recv: x_min: open
Recv: y_min: open
Recv: z_min: TRIGGERED
Recv: filament: TRIGGERED
```
Filament isn't in extruder:
```
Recv: Reporting endstop status
Recv: x_min: open
Recv: y_min: open
Recv: z_min: TRIGGERED
Recv: filament: open
```

_Originally posted by @madurani in https://github.com/MarlinFirmware/Marlin/issues/22933#issuecomment-940102487_

**Comment by elpeter25** [comment]
Hi,
It's same behaviour for me. Not working even though filament sensor is triggered correctly.

Kr

**Comment by elpeter25** [comment]
Looking at the code with not much idea I think this ONLY works whilst printer is on PAUSE mode (i.e. Filament runout detected while printing (M600)
What I'm looking for is for "Filament Autoload" function that can be used anytime while the printer is not printing nor paused and it's in idle state. Just for filament loading prior to start a print.

Is that something possible? @thisiskeithb


Kr
