### ISSUE TITLE
[BUG] Archim2 onboard SD slot does not detect card

### ISSUE THREAD

**Issue by orrinwitt** [MarlinFirmware/Marlin#22935]
### Bug Description

I cannot for the life of me get my Archim2 board to detect an SD card in the onboard slot. 

What I'm trying to accomplish:
I just need the SD card to work so I can connect remotely to Octoprint directly through Cura via the plugin.

Relevant info:
in Configuration.h
SDSUPPORT is enabled

in Configuration_adv.h
SDCARD_CONNECTION is set to ONBOARD

Also, I have no LCD display connected.

I have played with enabling other settings one at a time to see if they would help (they didn't) such as
SD_CHECK_AND_RETRY
NO_SD_DETECT
SD_DETECT_STATE HIGH

I can upload my configs if needed, but these are really the only relevant settings I've done anything with.
Anyone else have experience with this board? Am I missing something obvious?

### Version of Marlin Firmware

2.0.9.2

### Printer model

upgraded Airwolf 3D Xl

### Electronics

Upgraded old RAMBo board to Archim2. Also replaced stepper motors, replaced hotend with E3D V6

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by ellensp** [comment]
There is no SD_DETECT_PIN on the hardware for the onboard sd card reader. 
The hardware just does not have this capability.

**Comment by ellensp** [comment]
If your meaning its not working at all
I see in the file Marlin/src/pins/sam/pins_ARCHIM2.h

```
// Internal MicroSD card reader on the PCB
#define INT_SCK_PIN                           42  // D42 PA19/MCCK
#define INT_MISO_PIN                          43  // D43 PA20/MCCDA
#define INT_MOSI_PIN                          73  // D73 PA21/MCDA0
#define INT_SDSS                              55  // D55 PA24/MCDA3

// External SD card reader on SC2
#define SD_SCK_PIN                            76  // D76 PA27
#define SD_MISO_PIN                           74  // D74 PA25
#define SD_MOSI_PIN                           75  // D75 PA26
#define SDSS                                  87  // D87 PA29
```
But Marlin doesn't know anything about these INT_ pins.

**Comment by ellensp** [comment]
Give this a try
in Marlin/src/pins/sam/pins_ARCHIM2.h replace the above with 

```
#if SD_CONNECTION_IS(ONBOARD) // Internal MicroSD card reader on the PCB
  #define SD_SCK_PIN                          42  // D42 PA19/MCCK
  #define SD_MISO_PIN                         43  // D43 PA20/MCCDA
  #define SD_MOSI_PIN                         73  // D73 PA21/MCDA0
  #define SDSS                                55  // D55 PA24/MCDA3
#else // External SD card reader on SC2
  #define SD_SCK_PIN                          76  // D76 PA27
  #define SD_MISO_PIN                         74  // D74 PA25
  #define SD_MOSI_PIN                         75  // D75 PA26
  #define SDSS                                87  // D87 PA29
#endif
```

**Comment by orrinwitt** [comment]
@ellensp Thank you so much for your response! I will give this a try this evening and report back.

**Comment by orrinwitt** [comment]
@ellensp, I finally got a chance to try your suggestion tonight. But unfortunately, it caused an error compiling. I confirmed by undoing the edits to the pin file and it compiled successfully again.

Here is the error:
error: the value of 'spiDelayNS' is not usable in a constant expression

There was of course more in the output than that, but that was enough to get me to this thread:
#https://github.com/MarlinFirmware/Marlin/issues/22320
where I was completely in over my depth.

Is this a dead end? Or am I really the first person to want to use the onboard SD slot on the Archim??

**Comment by ellensp** [comment]
Dont use arduino ide, its broken

**Comment by orrinwitt** [comment]
Wait, I don't know about this... What should I be using to flash firmware instead?? Teach me your ways, wise one! 😅

**Comment by ellensp** [comment]
https://marlinfw.org/docs/basics/install_platformio_vscode.html

**Comment by orrinwitt** [comment]
Thank you so much for that. It does succeed in building the firmware.bin file either way with PlatformIO, but I do still get this error after making the above changes:
function call is not allowed in a constant expression

Does this matter? (I've got a long print going right now, so I can't test it yet)

**Comment by orrinwitt** [comment]
@ellensp First of all, thank you for my introduction to VisualStudio. SOOO much better! 
That said, I was able to successfully flash the firmware with the changes above, but sending M21 to the printer still echos back "no sd card".

It appears the SD_CONNECTION_IS refers to this in the Conditionals_adv.h file:
```cpp
// SD Card connection methods
// Defined here so pins and sanity checks can use them
//
#if ENABLED(SDSUPPORT)
  #define _SDCARD_LCD          1
  #define _SDCARD_ONBOARD      2
  #define _SDCARD_CUSTOM_CABLE 3
  #define _SDCARD_ID(V) _CAT(_SDCARD_, V)
  #define SD_CONNECTION_IS(V) (_SDCARD_ID(SDCARD_CONNECTION) == _SDCARD_ID(V))
#else
  #define SD_CONNECTION_IS(...) 0
#endif
```
Do I need to do anything to this file? (I'm assuming not...)

Also I stumbled on this thread: 
#https://github.com/MarlinFirmware/Marlin/issues/20134
Which seems to suggest what I'm trying to do here is not possible?
