### ISSUE TITLE
[FR] Power control (Current drawing limitation)

### ISSUE THREAD

**Issue by NeoAscalon** [MarlinFirmware/Marlin#22930]
### Is your feature request related to a problem? Please describe.

I am using a repurposed PC PSU and because of the power limit the overcurrent protection gets triggered, shutting down the PSU

### Are you looking for hardware support?

I am using an MKS_SGEN_L_V2 board it would be nice to be able to use something like a current sensor /current sensing circuit to limit the max power draw.

### Describe the feature you want

I would like to have an option in the advanced tab to limit the maximum power draw, if possible.

**Comment by ellensp** [comment]
The controllers use what they use, there is no way to lower the current usage.
This FR has no use.
