### ISSUE TITLE
ROBIN PRO z low with fix

### ISSUE THREAD

**Issue by shtaXveed** [MarlinFirmware/Marlin#22931]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

the lcd reset pin is assigned to PF6 which is a z tx pin. it should be PC6. it causes low on Z while compiling for uart

### Expected behavior

working printer in uart

### Actual behavior

tmc connectivity error and motor stutter on z

### Steps to Reproduce

compile uart on robin pro and install

### Version of Marlin Firmware

2.0.bugfix 10.10.21

### Printer model

artist d pro

### Electronics

stock plus bltouch minus some jumpers

### Add-ons

bl

### Bed Leveling

ABL Bilinear mesh

### Additional information & file uploads

found on a makerbase github

**Comment by thisiskeithb** [comment]
> found on a makerbase github

Please open an issue in their repository. It has already been fixed here.

**Comment by shtaXveed** [comment]
i pulled last nights bugfix and it was a PF6 instead of PC6 and threw
errors. only reason im bringing it up. i believe that one may have been
missed.

**Comment by shtaXveed** [comment]
![Screenshot_20211011-132037_Chrome](https://user-images.githubusercontent.com/90537330/136836909-fe538ef5-dbf2-4ecd-b799-148575633618.jpg)
![Screenshot_20211011-132005_Chrome](https://user-images.githubusercontent.com/90537330/136836915-d0dd4117-8737-43bb-b348-36fd3e9069f3.jpg)

**Comment by thisiskeithb** [comment]
I was looking at the Robin Pro 2 pins file which was correct, but the regular Pro is incorrect and has `PF6` assigned multiple times as you noted:

https://github.com/MarlinFirmware/Marlin/blob/40cb7cf8d6e31cf768a946e3248618256c021fb6/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_PRO.h#L84

https://github.com/MarlinFirmware/Marlin/blob/40cb7cf8d6e31cf768a946e3248618256c021fb6/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_PRO.h#L143

https://github.com/MarlinFirmware/Marlin/blob/40cb7cf8d6e31cf768a946e3248618256c021fb6/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_PRO.h#L240

I'll post a PR shortly.

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/22937. Thanks for the report!

**Comment by ellensp** [comment]
This has been merged, closing
