### ISSUE TITLE
[BUG] U8glib-HAL v 0.5.0 error during compile

### ISSUE THREAD

**Issue by pka4916** [MarlinFirmware/Marlin#22939]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Unable to compile the latest Marling 2.0.9.2

I see in the features.ini  that  it's looking for   U8glib-HAL v 0.5.0
But unable to install.

I looked at 2.0.9.1 and that one was using   U8glib-HAL v 0.4.x.  

What do i need to do to make it work,  since I can't install it.

### Bug Timeline

old issue

### Version of Marlin Firmware

2.0.9.1

### Printer model

Enter 6

### Electronics

stocl

### Add-ons

-

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
Ender 6 doesnt even have this lcd, it has a DGUS_LCD_UI_ORIGIN
If you disable DGUS_LCD_UI_ORIGIN and enable CR10_STOCKDISPLAY and RET6_12864_LCD It compiles without issue
