### ISSUE TITLE
[BUG] Can't use UBL without Z-probe, but with LCD

### ISSUE THREAD

**Issue by saloid** [MarlinFirmware/Marlin#22946]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

When I'm trying to manually use unified bed leveling (with `G29 P4` or `G29 P2`) I got an error that I don't have an LCD (but I have MKS_ROBIN_TFT35): `?P4 is only available when an LCD is present.`

### Bug Timeline

It's my first use of marlin

### Expected behavior

I'd like to use UBL in my config

### Actual behavior

Getting error when trying to do manual UBL according to [this manual](https://marlinfw.org/docs/features/unified_bed_leveling.html).

### Steps to Reproduce

1. Use my configs (also #22938 PR will be required to build with my configs)
2. Send `G29 P4 R255`
3. Got an error `?P4 is only available when an LCD is present.`

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin 2.0.9.2 (Oct 12 2021 19:54:00)

### Printer model

TT-1S

### Electronics

Stock (MKS robin nano 1.2 + MKS_ROBIN_TFT35)

### Bed Leveling

UBL (AUTO_BED_LEVELING_UBL)

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/7332224/Configuration_adv.zip)

**Comment by thisiskeithb** [comment]
"_is only available when an LCD is present._" can be misleading because you need a traditional 2004/character or 12864/graphical LCD, not a TFT.

**Comment by saloid** [comment]
So my screen is bigger and there is no way to use UBL on it? If it really wouldn't work - maybe it's better to add an error during compilation?
