### ISSUE TITLE
[BUG] mks_ui bug

### ISSUE THREAD

**Issue by XCDesigner** [MarlinFirmware/Marlin#22944]
### Bug Description

Dear engineers:

In "Draw_Keyboard.cpp"
![image](https://user-images.githubusercontent.com/31994520/136975155-454cb2ea-3065-4684-a258-9b44e56eb8f6.png)

If the user enter an empty string, it will make nothing display and the application crushed! Because "draw_return_ui" method will not be called since the hook can not be clear.

### Bug Timeline

Old issue

### Expected behavior

1.Tool->More->Gcode
2.Clear the inputbox
3.Confirm

### Version of Marlin Firmware

2.0.9.1

LCD:
![image](https://user-images.githubusercontent.com/31994520/136992847-0d87562d-1765-4e22-ba70-905a5dcbb9b9.png)
Horizontal resolution:480
Vertical resolution:320
LCD dirver:ILI9488

Controler:STM32F103VET6

**Comment by XCDesigner** [comment]
Addition, I also found that if the Gcode is M105, the same situation occur

**Comment by ellensp** [comment]
This seems to be the same as https://github.com/MarlinFirmware/Marlin/issues/22679

**Comment by thisiskeithb** [comment]
Duplicate of #22679

**Comment by thinkyhead** [comment]
The code is kind of convoluted, so what is the proposed solution? The one I suggested in the PR linked above didn't work.
