### ISSUE TITLE
Marlin 2.0.9.2 for CR10 S5 is missing Movement Items for X, Y, and Z

### ISSUE THREAD

**Issue by toophast2catch** [MarlinFirmware/Marlin#22949]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I compiled a new firmware for a custom CR10 S5 and I am missing menu items to individually move X,Y,Z under the Motion menu. I only have options to auto home XYZ or I can move the extruder individually.  I do not have any SLIM_LCD options enabled under configuration_h. Everything else works as expected and I can still individually move the XYZ axis on my TFT35 on the touch screen but prefer to use Marlin mode.

### Bug Timeline

New issue

### Expected behavior

Should be able to move XYZ under Motion menu

### Actual behavior

No movement options available. 

### Steps to Reproduce

Compile code, flash it to SKR 1.4 Turbo and power on Printer. Go to Move Menu item and the the options are not available. 

### Version of Marlin Firmware

2.0.9.2

### Printer model

CR10 S5 -

### Electronics

SKR1.4 T

### Add-ons

na

### Bed Leveling

ABL Linear grid

### Your Slicer

Simplify3D

### Host Software

OctoPrint

### Additional information & file uploads

na

**Comment by toophast2catch** [comment]
[README.md](https://github.com/MarlinFirmware/Marlin/files/7337517/README.md)

**Comment by toophast2catch** [comment]
[Marlin-Config.zip](https://github.com/MarlinFirmware/Marlin/files/7337536/Marlin-Config.zip)
Config files attached.

**Comment by ellensp** [comment]
firstly comment out   "#define FIL_RUNOUT_PIN 2 // Creality CR-10 S5 stock sensor"
that is not correct for a skr 1.4T

That will stop most of the warnings

**Comment by toophast2catch** [comment]
That has been updated. New config files attached, but that did not resolve the issue with the Movtion >> Movement of XYZ options. 
[CR10 - S5 Marlin - 2092 - SKR.14 Board.zip](https://github.com/MarlinFirmware/Marlin/files/7338095/CR10.-.S5.Marlin.-.2092.-.SKR.14.Board.zip)

**Comment by toophast2catch** [comment]
Okay the menu items are back. This appears to be a new safety feature in newer versions of Marlin. When you turn the printer off, it wants you to home all xyz first then the menu items to move each axis is allowed. Is there a way to disable this? It is kind of nuisance. When I am testing out functions of the printer and have to turn it off to prevent any crashes, I have to manually move it into place.

**Comment by ellensp** [comment]
you have #define NO_MOTION_BEFORE_HOMING
It does as it says, It stops all movement before home is complected.
