### ISSUE TITLE
[BUG] Compiled FW does not boot on Ender 3 Pro with 4.2.7 Board & BLTouch 3.1

### ISSUE THREAD

**Issue by Gunhawk007** [MarlinFirmware/Marlin#22948]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I am tryting to compile Marlin FW for my Ender 3 Pro, for which I have the Hardware upgraded with Creality's V4.2..7 Silent Board with the TMC Steppers and also installed a BLTouch V3.1 probe. 

When I am using the FW from Crealitys site, everything works as expected.

### Bug Timeline

First test to compile own FW - never did before

### Expected behavior

I epected the printer to boot from the compiled FW which has been saved on the SD-Card. Please note that the V4.2.7. board has a different FW install procedure that needs the FW placed on the SD Card and not to be flashed via USB.
The normal behavior should be that after switching on the printer with the SD-Card having the FW on it, the LCD screen should light up empty for about 15 sec and then displays the Ender Logo followed by showing the Main Menue/Info Screen

### Actual behavior

After inserting  the SC-Card containing the freshly built FW and switching on the printer, the LCD screen lights up with an empty screen and stays there until being switched of - waited for about a minute or so. Normally, the printer should boot up after about 15 secs.

### Steps to Reproduce

1. Download the FW and Configuration
2. Copy over the configuration files for Creality->Ender-3 Pro->CrealityV427
3. Follow the instructions to enable BLTouch
4. Compile the FW using Visual Code and Marlin Auto Build Extention using the Environment "STM32F103RET6_creality
5. Locate the compiled BIN file and save to SD-Card
6. Insert SD-Card into the powered off printer
7. Turn on the printer -> LCD Screen lights up up remains blank - no Ender Logo, no boot

### Version of Marlin Firmware

Marlin V1.1.2 2020-04-25 Ender-3 Pro www.creality.com

### Printer model

Ender-3 Pro

### Electronics

Upgraded electronics with Creality V4.2.7 Mainboard

### Add-ons

BLTouch V3.1 Z-Probe installed for Auto-Level

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Additional information & file uploads

Configurations used for Built:
[Issue_Config_tested.zip](https://github.com/MarlinFirmware/Marlin/files/7335992/Issue_Config_tested.zip)

Firmware coming out of tthe built prozess:
[firmware-20211012-213446.zip](https://github.com/MarlinFirmware/Marlin/files/7336155/firmware-20211012-213446.zip)

Firmware downloaded from Creality proven to work OK:
[Ender-3 Pro_4.2.7_BLTouch_Marlin2.0.1_V1.1.2_TMC2225.bin.zip](https://github.com/MarlinFirmware/Marlin/files/7336175/Ender-3.Pro_4.2.7_BLTouch_Marlin2.0.1_V1.1.2_TMC2225.bin.zip)

**Comment by thisiskeithb** [comment]
Have you tried removing the SD card after flashing? https://github.com/MarlinFirmware/Marlin/issues/22898

**Comment by Gunhawk007** [comment]
Yes I did. 
I can also confirm that the filename of the new binary presented on the SD-Card is different from the one that has been used to boot up the machine successfully - this has been mentioned in the forums - make sure the binary is named differently from the currently installed one as the system stores the bin filename in the EEPROM and prevents an install.

**Comment by descipher** [comment]
Sounds like it's a display configuration problem, there is a recent change e.g IS_U8GLIB_ST7920 vs ENABLED(U8GLIB_ST7920) in the configuration_adv file.
The config examples have IS_U8GLIB_ST7920 but 2.0.9.2 default uses ENABLED(U8GLIB_ST7920).

**Comment by Gunhawk007** [comment]
Thanks for the hint.
I have now done the following in Configuration_adv.h:
- Replaced the Line 
#IF IS_U8GLIB_ST7920
- with the following 
#if ENABLED(U8GLIB_ST7920)

The code compiles successfully, the the result (blank screen on boot) remains the same. Reverting back to my old FW immediately solves it so it may be something else.

**Comment by Gunhawk007** [comment]
Can perhaps someone with the same HW than me 427 mainboard version coming without the transfer board and BLTouch share their config and binary so I can test it on my HW? Maybe I have a board with a sometimes faulty update routine.

**Comment by J0hnMatrix** [comment]
Hello,
I have the same issue but on an Ender-3 with a FYSETC Cheetah 1.2 (stock display).
I kept the same settings as 2.0.9 and after flashing the new FW with FlyMCU, the screen stay blank.
Have tried to connect the printer with Octoprint (to see if the motherboard still can "speak") but no luck

Working config is Marlin-2.0.9_en.zip
Affected config is Marlin-2.0.9.2_en.zip
[Marlin-2.0.9_en.zip](https://github.com/MarlinFirmware/Marlin/files/7397337/Marlin-2.0.9_en.zip)
[Marlin-2.0.9.2_en.zip](https://github.com/MarlinFirmware/Marlin/files/7397338/Marlin-2.0.9.2_en.zip)

**Comment by Gunhawk007** [comment]
UPDATE:
I have now successfully built my firmware and got it to run with my Ender 3 Pro and the 4.2.7. Board. Even BLTouch works with the board now. However, it seems that my filament sensor I have attached as well does not report correctly. The sensor is attached to the dedicated 3Pin connector and seem to operate correctly (LED on Sensor is lit/off when filament is inside or out. However, the M412 State always reports the same.
Is there a setting that I need to use (similar to Z_MIN_USES Pin 17) to indicate where the sensor is connected? BLTouch is also connected to the 5 Pin Port on the board, which mean it does not uses ENDStop but uses Pin 17

**Comment by ellensp** [comment]
Your trying to use this as a support forum.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
