### ISSUE TITLE
[BUG] JyersUI Z Offset not showing in MM

### ISSUE THREAD

**Issue by Phil-Barker** [MarlinFirmware/Marlin#22943]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I've just compiled V2.0.9.2 and set my display to Jyers UI
All seems to be working except the Z Offset menu now seems to move in steps rather than MM

Micro adjust up and down is moving in 1 full integer at a time and I require a massive value like -2000 to get anywhere near the bed.

On my old Jyers 1.3.5b it used to microstep in fractions ... -0.01, -0.02, 0.03 etc...

I've compared my config files with my old ones and can see no difference

I'm using BLTouch and UBL

### Expected behavior

I expect Z Offset microstep to move in fractions of a mm

### Actual behavior

Z Offset microstep moves in steps

### Steps to Reproduce

Go into Z-Offset menu
Home device
Microstep up and down
Observe behaviour

### Version of Marlin Firmware

2.0.9.2

### Printer model

Creality Ender-3 V2

### Electronics

Stock

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/7329250/Configuration_adv.zip)

**Comment by thisiskeithb** [comment]
#22975 will resolve this.

**Comment by Roxy-3D** [comment]
> #22975 will resolve this.

This is now merged.    @Phil-Barker  can you please verify it does everything correctly for you?

Thanks!
