### ISSUE TITLE
[FR] Change ABL grid numbers in menu

### ISSUE THREAD

**Issue by kosmikza** [MarlinFirmware/Marlin#22947]
### Is your feature request related to a problem? Please describe.

Nope

### Are you looking for hardware support?

Nope

### Describe the feature you want

When compiling the firmware for ABL, in the firmware you can define the points grid ie: 3x3 , 5x5 etc. It would be great to have this option in the menu on the printer so that one could switch to and from a denser points grid on the fly without having to re-compile and upload firmware.

Line 1575 in Configuration.H 

#define GRID_MAX_POINTS_X {variable}

**Comment by thisiskeithb** [comment]
Duplicate of #18460
