### ISSUE TITLE
[FR] Report `EXTENDED_M20` capability to indicate `M20 L` support

### ISSUE THREAD

**Issue by bcat** [MarlinFirmware/Marlin#22940]
### Is your feature request related to a problem? Please describe.

The latest release of OctoPrint (1.7.0) knows how to issue `M20 L` commands and parse long file names out of the response. The latest release of Marlin (2.0.9.2) supports `M20 L` when compiled with `LONG_FILENAME_HOST_SUPPORT` enabled. However, OctoPrint checks for the `EXTENDED_M20` capability and only uses `M20 L` if this cap is found in the printer firmware's `M115` response.

### Describe the feature you want

When `LONG_FILENAME_HOST_SUPPORT` is enabled, report the `EXTENDED_M20` capability in `M115` responses.

### Additional context

Per [the RepRap wiki](https://reprap.org/wiki/G-code#M20:_List_SD_card), Prussa firmware uses this capability to indicate `M20 L` support that should be compatible with Marlin's output. However, they also use the same capability to indicate `M20 T` support. I'm not sure if this feature is widely used, but technically if Marlin only supports `M20 L` it's not totally compatible if it advertises this capability. But since long file names seem a lot more generally useful than timestamps, IMO it's worth supporting `EXTENDED_M20` even if timestamp support isn't available (yet).

**Comment by thisiskeithb** [comment]
This will be added in #22941

**Comment by bcat** [comment]
Awesome, thank you! :)

**Comment by ellensp** [comment]
This has been merged. closing
