### ISSUE TITLE
[BUG] Issue compiling - expected primary-expression before '{' token

### ISSUE THREAD

**Issue by DanielP5433** [MarlinFirmware/Marlin#22950]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I am getting an issue when trying to compile, I have attached screenshots of the issue and my Configuration and Configuration_adv files. Does anyone know a solution? I have tried the bugfix with the same issue.

### Bug Timeline

New, today

### Expected behavior

Compile firmware.

### Actual behavior

Got 2 errors and compiling failed.

### Steps to Reproduce

Set up Configuration, Configuration_adv, pins and platform.io files and hit build.

### Version of Marlin Firmware

2.0.9.2 and 2.0.X bugfix

### Printer model

Custom Prusa Mk3s

### Electronics

BTT SKR V1.3

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7337938/Configuration.zip)
![2021-10-13 13_48_43-Greenshot](https://user-images.githubusercontent.com/64781248/137130027-901cbefb-6583-4665-8f17-63c7084d737e.png)
![2021-10-13 13_49_25-Greenshot](https://user-images.githubusercontent.com/64781248/137130031-4e4386cf-40d0-4c73-bbd8-db6ce1d80c24.png)

**Comment by ellensp** [comment]
You have bypassed several sanity checks to get to that error
Disabled     #error "LIN_ADVANCE and S_CURVE_ACCELERATION may not play well together! Enable EXPERIMENTAL_SCURVE to continue."
Disabled     #error "SENSORLESS_HOMING requires X_MIN_ENDSTOP_INVERTING = true when homing to X_MIN."
Disabled     #error "SENSORLESS_HOMING requires Y_MIN_ENDSTOP_INVERTING = true when homing to Y_MIN."

The actual error is caused by this illegal line in Configuration.h 
you have "#define Z_PROBE_FEEDRATE_FAST HOMING_FEEDRATE_MM_M { (9*60) }" 

None of which are bugs in Marlin.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
