### ISSUE TITLE
[BUG] DELTA printer FLSUN QQ-S Pro Marlin 2.0.9.2 G33 Don`t work

### ISSUE THREAD

**Issue by dredivan** [MarlinFirmware/Marlin#22954]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

firmware: release 2.0.9.2
Configurations files:
Configurations-2.0.9.2\config\examples\delta\FLSUN\QQS-Pro

1) I flashed firmware, make reset EEprom (M502, M500)
2) G28
3) G33 - make 4 probes and finish
Log from Repiter host
```
09:15:30.421 : G33 Auto Calibrate
09:15:30.422 : Checking... AC
09:15:30.424 : .Height:370.00  Ex:+0.00  Ey:+0.00  Ez:+0.00  Radius:140.80
09:15:30.427 : .               Tx:+0.00  Ty:+0.00  Tz:+0.00
09:15:35.853 : Deploy Z-Probe
09:15:56.032 : Correct delta settings with M665 and M666
09:15:56.032 : Stow Z-Probe

```

On marlin 2.0.9.1 with same config all work fine!

my files
https://drive.google.com/file/d/19ANNty2zPvosEUNZTzZon7r2hU8KCKgU/view?usp=sharing

### Version of Marlin Firmware

10:00:14.744 : FIRMWARE_NAME:Marlin 2.0.9.2 (Oct 14 2021 09:09:31) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:FLSUN QQS-Pro EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

### Printer model

FLSUN QQ-S Pro

**Comment by homerjatmoes** [comment]
I am having the same issue on an FLSUN Q5. I am using a BTT SKR 1.3 with TMC 2209 drivers. I was able to get it to work with an older version of Marlin.

**Comment by LVD-AC** [comment]
Same issue as #22886; use PR #22795 to fix this.

**Comment by thisiskeithb** [comment]
Duplicate of #22886

**Comment by dredivan** [comment]
> Same issue as #22886; use PR #22795 to fix this.

can you help?

**Comment by thisiskeithb** [comment]
> > Same issue as #22886; use PR #22795 to fix this.
> 
> can you help?

You'll need to manually apply the changes in #22795 to your copy of Marlin or wait until the PR is merged.

Please move discussions to #22886 since this is closed.
