### ISSUE TITLE
[BUG] TFT32 doesn't print with new version

### ISSUE THREAD

**Issue by cprobst87** [MarlinFirmware/Marlin#22951]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Hello,
I installed Marlin 2.0.9.2
Now my TFT32 doesn't work correctly: I can do Homeing, Heating etc. But if I start a print, it hangs from the beginning. No reaction, only bed is heating endless.... I can cancel the print, it will home.
Is there for example a new status line sending to the serial port?
I see some changes in /src/gcode/queue.cpp
With the release before, it works fine.
It's like this bug: https://github.com/MarlinFirmware/Marlin/issues/21790
Thank you!

### Steps to Reproduce

1. upload a gcode to TFT32 
2. Print
3. Bed heating... endless

### Version of Marlin Firmware

2.0.9.2

**Comment by Tannoo** [comment]
If you send `M140 S50` from the TFT, what happens? What about from another serial connection (ie: PC)?

**Comment by thisiskeithb** [comment]
> Did you test the latest bugfix-2.0.x code?
> No, but I will test it now!

Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.
