### ISSUE TITLE
[FR] Usable EVENT_GCODE_TOOLCHANGE_T0 and T1 even if homing is not done

### ISSUE THREAD

**Issue by GenaUser** [MarlinFirmware/Marlin#22957]
### Is your feature request related to a problem? Please describe.

Would it be possible to use the extra G code to be executed when executing the tool change commands, even if the homing is not performed?
This command is taken into account as an offset between the nozzles, which reduces its scope of use.
For example, I use the I and J axes to change heads. Unfortunately, the T0 and T1 command only physically change the heads after referencing is complete, causing issues when using the printer outside of printing. 
Heads are often desychronized when using functions using T0 or T1. They must then be synchronized with a specific command.

### Describe the feature you want

Have the possibility in Configuration.adv.h to choose if the G-code is usable all the time or only after homing.

**Comment by GenaUser** [comment]
Thank you for working on this topic.

I tested this modification, but unfortunately it doesn't seem to work.
When the line "#define EVENT_GCODE_TOOLCHANGE_ALWAYS_RUN" is activated,  the T0 and T1 commands no longer work:
If I send the T1 command, the printer reset.
If I send the T0 command, the printer hangs because of an action in progress "busy"

For information, here are the G-code commands used:
```cpp
  #define EVENT_GCODE_TOOLCHANGE_T0 "G28 J\n" // Extra G-code to run while executing tool-change command T0
  #define EVENT_GCODE_TOOLCHANGE_T1 "G28 I\n" // Extra G-code to run while executing tool-change command T1
  #define EVENT_GCODE_TOOLCHANGE_ALWAYS_RUN // Always execute above G-code sequences. Use with caution!
```

**Comment by thisiskeithb** [comment]
Added in #22960
See #23003
