### ISSUE TITLE
[BUG] Home offsets (M206) doesn't affect auto bed leveling (G29)

### ISSUE THREAD

**Issue by Testmangh** [MarlinFirmware/Marlin#22959]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I'm trying to make the BlTOuch probe the printable area of the bed of my printer.
The X of my printer is 240
`#define Y_BED_SIZE 240`
 but 20 of that is for the brush to clean the nozzle so i set the offset to 
`M206 X0.00 Y-20.00 Z0.00`

After homing if I give the command to auto bed level the printer moves the probe to an area where there is no bed, to fix I updated the PROBING_MARGIN to 40
`#define PROBING_MARGIN 40`
But I m now losing a lot of probing area from the other side of the bed =(

### Expected behavior

G29 to probe only the printable area (or not probe the negative area of the bed).

### Actual behavior

G29 tries to probe an area where there is no bed, it doesn't consider the home offsets.

### Steps to Reproduce

`#define Y_BED_SIZE 240`
`M206 X0.00 Y-20.00 Z0.00`
`G28`
`G29`

### Version of Marlin Firmware

#define CONFIGURATION_H_VERSION 02000902

### Printer model

Ender 3 PRO modded

### Electronics

SKR 1.3

### Add-ons

Octoprint, BlTouch, Direct drive, Filament sensor, TFT display, Octoprint Display, WebCam, Linear rails, Dual Z Steppers, etc.

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by Vertabreak** [comment]
Home offsets M206 does not and never has to my knowledge accounted for probe variables. i have reported this in the past and even tried to force a sanity check to prevent users with a probe from attempting to combine these features. side note: if you where to manually add the probe variables and set them by hand it ill work.

**Comment by Testmangh** [comment]
@Vertabreak I'm noob sry.
I have done it  now it works perfectly.

`  #define PROBING_MARGIN_LEFT 5
  #define PROBING_MARGIN_RIGHT 5
  #define PROBING_MARGIN_FRONT 40
  #define PROBING_MARGIN_BACK 5`

**Comment by InsanityAutomation** [comment]
> 
> 
> Home offsets M206 does not and never has to my knowledge accounted for probe variables. i have reported this in the past and even tried to force a sanity check to prevent users with a probe from attempting to combine these features. side note: if you where to manually add the probe variables and set them by hand it ill work.

Actually way back before CNC workspaces, it was applied directly as the home position in G28 and therefore offset absolutely everything.

**Comment by Vertabreak** [comment]
if it has not changed in the last few months it still don't work with probe offsets unless you do it by hand. i filed a report and even posted a video and suggested a sanity check. will have to do a check again in the near future but it has never worked when i tried it since 2018.

**Comment by InsanityAutomation** [comment]
Just checked, June 2017 was when cnc workspace planes were added... how time flies lol

**Comment by Vertabreak** [comment]
last i check it was maybe 6 months back still broken.

**Comment by InsanityAutomation** [comment]
According to discussion when I tried to make home offsets 100% global again, it was intended, but maybe we can revisit that discussion at some point. Personally I feel the home offset should be absolute shifting the reference point globally in all cases still.
