### ISSUE TITLE
[BUG] Z-Offset not working as expected (switching nozzle)

### ISSUE THREAD

**Issue by thekingisback-code** [MarlinFirmware/Marlin#22962]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

M218 is not working as expected, a Z offset of 2 is almost the offset I need, I get the nozzle closer to the bed with higher values (really not that intuitive, but whatever), I try something like Z3.00 and now t0 is printing well above the bed. Sometimes it works, sometimes it doesn't (this is most of the time), 0.01 differences give totally different values.
Given, I'm not using the most recent Marlin build (had to make some custom mods for Marlin to function with my printer configuration, currently not supported) I didn't touch anything related to offsets.

### Bug Timeline

This is an old project, just picked it up again

### Expected behavior

I offset tool 1 (i.e 'M218 T1 X37.00 Y0.00 Z2.500') and T1 should move 2.5mm relative to T0.

### Actual behavior

When offsetting T1 as per documentation, it moves both T0 and T1 offsets in an unpredictable manner (but repetitive).

### Steps to Reproduce

Whole firmware can be shared if needed. 
Changes made by me are marked and easily searchable. 
I could have tried to make my changes on a newer firmware but internal code kinda changed and it got hard.

### Version of Marlin Firmware

Marlin bugfix-2.0.x (Oct 14 2021 06:24:37) 

### Printer model

Custom Ender 3 type

### Electronics

SKR 1.4 TURBO

### Add-ons

switching extruder (modified firmware for it to work as wanted)

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Simplify3D

**Comment by nsarzyns** [comment]
I'm not sure if it's related, but here is another issue created from z-offset issues. #22322 

I have the SKR Mini E3 V2 as does at least one other on that issue thread and we both seem to have inconsistent Z-offset issues for the last two versions. It still exist with the bugfix version I pulled and built today, 10/05/2021. Almost every print I need to adjust the Z height on the fly with babystepping to get it to actually work. I've had offset swings as high as .7mm between prints. It doesn't make any sense and I have no idea where else to look to debug it.

I've confirmed the proper number of steps occur, there's no mechanical slop, bl touch is dead accurate (basically the same mesh everytime)....I'm at a loss.

**Comment by thekingisback-code** [comment]
The thing here is I'm using a switching nozzle, so basically every dual material print I have to make is paused until I can fix this. Z Offset between nozzles is more than 20mm due to the bug, I literally can't print :(
Let's hope someone with more expertise than us comes in our help @nsarzyns :(

**Comment by thinkyhead** [comment]
Do you see the issue with bed leveling both on and off? (i.e., `M420 S0` and `M420 S1`)

Let's gather some data…

- Download Marlin `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Send `M111 S247` to enable maximum logging.
- Send `G28` to do your standard homing procedure.
- Send `M114 D` to get the detailed current position.
- Send `T1` to change tools. Raise the Z axis first, if needed.
- Send `M114 D` to get the detailed current position.
- Do more moves and tool-change commands that show the problem. Send `M114 D` after each command.
- Copy the log output into a **.TXT file** and attach it to your next reply.

From these logs we should hopefully get a better idea of what's going on with your machine.

**Comment by thekingisback-code** [comment]
Do you see the issue with bed leveling both on and off? (i.e., M420 S0 and M420 S1)
- Yes, I just tested with the mesh off (its a quite large uneven bed, the mesh is a necessity) and the same issue happens.

See the txt file attached below, I tried doing it all, but I dont know if I can do it while it's printing, currently with a ~2.5 tool 1 offset (z), T0 is printing something like 10-15 mm above the bed (while it should be spot on).
I'm new at this marlin options (advanced position report and such) but I'll try to send whatever is needed to fix this :)
Thank you so much @thinkyhead!

[report.txt](https://github.com/MarlinFirmware/Marlin/files/7412362/report.txt)

Edit: this was done while the printer was well, not printing, and with every tool change, I could physically see the z movement, at least when it was well above bed level (Z=0) :) I also added a M503 at the end of the report so you could see the printer settings, sure makes no harm

**Comment by thekingisback-code** [comment]
Have you had any time to look at this @thinkyhead ? :(

**Comment by thekingisback-code** [comment]
Just commenting so the issue won’t auto-close. 
Still no fix :(

**Comment by thekingisback-code** [comment]
Any updates to this?

**Comment by thekingisback-code** [comment]
Nothing new yet?

**Comment by thekingisback-code** [comment]
I'm contemplating changing my printer to an standard configuration, I know this is free but still, nothing? :(

**Comment by Dids** [comment]
I'd definitely be interested in at least an official confirmation that this is a bug in latest Marlin, as I've been changing hardware and tweaking my own fork, but my Z offset still keeps changing.

While my issues started after I setup the second Z axis, I've been unable to fix it permanently (or even between prints), requiring manual adjustment and re-leveling all the time.
The only thing I haven't yet tried is anti-backlash nuts, which should arrive today or tomorrow, but I've also been unable to at least visually confirm that I'm even seeing backlash, as the issue is extremely hard to troubleshoot, with so many variables in play.

**Comment by selrahc13** [comment]
I'm experiencing this bug as well with the latest 2.0.x bugfix on an Ender 3 Max with a BLTouch 3.1 sensor attached to the 5-pin port on the stock Creality V4 board. G28 works as expected on initial printer startup but after a print, the Z home seems to be changing.

M206 reports Z0 at printer start and after a print
M851 reports no changes to Z offset before and after a print as well

Running G28 after a print only seems to have the effect of the Z axis raising without the ability to lower again except manually with steppers disabled

**Comment by JeremyDWilliams** [comment]
Was this ever resolved? :)

**Comment by thekingisback-code** [comment]
> Was this ever resolved? :)

Nope, still waiting for help. Got a similar problem?
