### ISSUE TITLE
[BUG] Printer crashes when cycling through file name

### ISSUE THREAD

**Issue by hfjim-coder** [MarlinFirmware/Marlin#22964]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When it finishes showing the file name the printer stops responding and restarts. I have the following option enabled 
#define DWIN_CREALITY_LCD_JYERSUI

### Bug Timeline

after flashing the firmware

### Expected behavior

I expected to continue fuctioning

### Actual behavior

Printer crashes

### Steps to Reproduce

In the main menu of the ender 3 v2 select print and select a file

### Version of Marlin Firmware

marlin bugfix 2.0

### Printer model

ender 3 v2

### Electronics

stock mainboard 4.2.2

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
