### ISSUE TITLE
[BUG] G34 Auto Align Z not working correctly (can't achieve accuracy)

### ISSUE THREAD

**Issue by bmyonatan** [MarlinFirmware/Marlin#22963]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When performing G34, the difference between Z2 and Z1 is very unreliable and doesn't converge to 0 (sometimes accuracy increases between iterations and sometimes it decreases).
I have an Ender 3 Pro, with a SKR 2 board, 2209 drivers, dual Z lead screw and drivers and a BLTouch.
I tried different number of iterations and amplitudes, but the auto align is unreliable (rarely it will get to the desired accuracy, but usually Z2-Z1 is above 1.5

Bltouch accuracy (with M48 S1) is <0.003
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7357338/configuration.zip)

### Expected behavior

Both Z motors align themselves properly

### Actual behavior

Probe Accuracy:  
```
SEND: M48
Recv: M48 Z-Probe Repeatability Test
Recv: Finished!
Recv: Mean: 0.001659 Min: -0.026 Max: 0.020 Range: 0.046
Recv: Standard Deviation: 0.014391
```

G34 Results:  
```
Send: G34 T0.05 A1 I10
Recv: G34 Iteration: 1
Recv: Z2-Z1=2.34
Recv: G34 Iteration: 2
Recv: Z2-Z1=1.62
Recv: G34 Iteration: 3
Recv: Z2-Z1=1.28
Recv: G34 Iteration: 4
Recv: Z2-Z1=2.32
Recv: Decreasing Accuracy Detected.
Recv: G34 Iteration: 5
Recv: Z2-Z1=1.61
Recv: G34 Iteration: 6
Recv: Z2-Z1=1.71
Recv: G34 Iteration: 7
Recv: Z2-Z1=1.95
Recv: G34 Iteration: 8
Recv: Z2-Z1=1.99
Recv: G34 Iteration: 9
Recv: Z2-Z1=1.62
Recv: G34 Iteration: 10
Recv: Z2-Z1=1.78
Recv: Did 10 of 10
Recv: Accuracy: 1.78
```

### Steps to Reproduce

Running G34 on my printer with supplied config

### Version of Marlin Firmware

Bugfix-2.0.x (2021-10-16_

### Printer model

Ender 3 Pro

### Electronics

SKR 2.0 with 2209's

### Add-ons

BLTouch, dual z lead screws (+motors and drivers)

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

**Comment by thisiskeithb** [comment]
Is your Z motor wiring correct? Try swapping Z1 with Z2 and see if G34 completes successfully.

**Comment by octico** [comment]
I am experiencing the same behavior. Ender 3 with SKR E3 turbo. I tried switching cables and still, but  Z2-Z1 is above 1.6

**Comment by octico** [comment]
Going to try stable version to see if I get the same behavior

**Comment by ManuelMcLure** [comment]
> I am experiencing the same behavior. Ender 3 with SKR E3 turbo. I tried switching cables and still, but Z2-Z1 is above 1.6

How do yo have Z2 connected? Is it hooked up to the second Z port or to the E1 port? If you connect to the second Z port both motors are running off the same driver and `G34` won't work at all.

**Comment by octico** [comment]
> > I am experiencing the same behavior. Ender 3 with SKR E3 turbo. I tried switching cables and still, but Z2-Z1 is above 1.6
> 
> How do yo have Z2 connected? Is it hooked up to the second Z port or to the E1 port? If you connect to the second Z port both motors are running off the same driver and `G34` won't work at all.

LHS motor is connected to Z port and RHS motor is connected to E1.

**Comment by gknapp** [comment]
FWIW, I'm also running an SKR E3 Turbo and using G34 am able to achieve an accuracy of 0.02. I had to invert the second (newer) stepper motor I got from an ali express kit.

Using bugfix-2.0.x branch.

**Comment by ashinckley** [comment]
> > I am experiencing the same behavior. Ender 3 with SKR E3 turbo. I tried switching cables and still, but Z2-Z1 is above 1.6
> 
> How do yo have Z2 connected? Is it hooked up to the second Z port or to the E1 port? If you connect to the second Z port both motors are running off the same driver and `G34` won't work at all.

Thank you so much for this.  That should have been the first thing I checked, but for some reason I went through a deep-dive into my marlin configuration instead.
