### ISSUE TITLE
What are the "long press" or "hold down" functions/parameters called in Marlin?

### ISSUE THREAD

**Issue by Firedrops** [MarlinFirmware/Marlin#22961]
### Describe the feature you want

My firmware only has on-screen LCD buttons, including for "up" and "down".

For things like adjusting temperature, individually tapping would take too long.

However, holding the up/down buttons (even for 1 second) immediately steps the value to min/max.

I would like to adjust the step size down to something more manageable.

But I cannot find this function/parameter name. Since I may be referring to them wrongly, even Google results have not been helpful.

Could someone please point out what they're called, and if possible, where (which file, if not in config(_adv).h)?

### Additional context

This may be more appropriate for Discord, but it requires phone number validation, and Discord insists that my  number is invalid. Discord's support is useless.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
