### ISSUE TITLE
[FR] (PT100 with MAX31865 compatibility for 3 thermistors)

### ISSUE THREAD

**Issue by kurtis-potier-geofabrica** [MarlinFirmware/Marlin#22979]
### Is your feature request related to a problem? Please describe.

I am trying to integrate a Dyze Design Pulsar. It uses 3 PT100 thermistors for one extruder. I then will use the MAX31865 board to convert to SPI so I can read them (-5 selected as thermistor). The only is issue is that Marlin does not support 3 PT100. 

### Describe the feature you want

After some work, I have gone through conditionals_post.h, temperature.cpp, and other files to make an option for a third PT100 successfully build. I have not tested on hardware yet. It would be helpful if  a developer could properly add this so it is supported in future updates. Thank you!

**Comment by thisiskeithb** [comment]
> It would be helpful if a developer could properly add this so it is supported in future updates.

Since you've already made the changes, it'd be better for you to submit a [Pull Request](https://marlinfw.org/docs/development/getting_started_pull_requests.html) once you've verified it works.

**Comment by kurtis-potier-geofabrica** [comment]
I can do this in the future for sure. My hardware is not made yet, while I have built it (Marlin), I can't verify it works. I am more wondering if there is a real reason why only 2 are supported or it this was mostly an arbitrary number. Let me know your thoughts. Thanks

**Comment by thinkyhead** [comment]
> why only 2 are supported or it this was mostly an arbitrary

Features have been implemented as-needed by contributors in a fairly informal fashion, and the temperature sensor code is long overdue for an overhaul, probably using a set of template classes. If you have some ideas about refactoring the thermistor / thermocouple code to make it more generalized and easier to mix-and-match sensors, please feel free to submit your changes. The only thing to watch out for is that the base build size / SRAM usage should not increase significantly in the refactor. We're still trying to be friendly to smaller boards.

**Comment by kurtis-potier-geofabrica** [comment]
Gotcha. I basically just copied and pasted as needed to add the third pt100 with max31865. I wish I was at the level to help more on this. I may eventually get there though. I'll update when I try it out at the least. If it works smoothly I will try to make it as clean as possible before a pull request.

**Comment by kurtis-potier-geofabrica** [comment]
Update, I did get this to work correctly after some work. All thermal features appear to working correctly with this after using the machine for a week or so. I will take some time to formalize this and submit changes.

**Comment by kurtis-potier-geofabrica** [comment]
It looks like conditionals_post.h has been cleaned up quite a bit since I cloned on 9/24. Will still try to revisit in the future, but timeline may be further out.

**Comment by thisiskeithb** [comment]
You can now use MAX31865 for sensors 0-2 and bed.

https://github.com/MarlinFirmware/Marlin/blob/f02fa6339f003a8a5074131b50e0905f102ee8e4/Marlin/Configuration.h#L516
