### ISSUE TITLE
[BUG] FAN_SOFT_PWM with Controller fan

### ISSUE THREAD

**Issue by MathiasGyldenberg** [MarlinFirmware/Marlin#22972]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I’ve changed all my fans to Sunon 4020 fans.
To make them work correcty with my BTT SKR2 board, FAN_SOFT_PWM in Configuration.h is enabled, so the fans spin as they should when using PWM control.

When i’m changing the fan speed with “Temperature > Fan Speed”, everything works great. But if i enable USE_CONTROLLER_FAN in Configuration_adv.h on the same pin, then the fan doesn’t use FAN_SOFT_PWM and the fan acts as if FAN_SOFT_PWM is disabled.

### Bug Timeline

New bug, first time tested today. 

### Expected behavior

With USE_CONTROLLER_FAN enabled, FAN_SOFT_PWM should be expected to work together with USE_CONTROLLER_FAN

### Actual behavior

Fan spins as if FAN_SOFT_PWM is disabled.

### Steps to Reproduce

1. Connect fan to PAN2_PIN on controller board.
2. Enable SOFT_FAN_PWM in Configuration.h
3. Start printer. Open “Temperature > Fan speed” on LCD and set a desired fan speed. Fan is running correctly.
4. Enable USE_CONTROLLER_FAN in Configuration_adv.h. Set pin to FAN2_PIN, enable controller menu.
5. Start printer. Open “Configuration > Controller fan > Idle speed” and set a desired speed. Fan is now running incorrectly without FAN_SOFT_PWM.

### Version of Marlin Firmware

2.0.9.2

### Printer model

Creality CR-200B

### Electronics

BTT SKR2, TFT35, BL-Touch

### Add-ons

Sunon 4020 fans on hotend, part cooling and controller

**Comment by descipher** [comment]
I don't think that's how the feature works:

as per controllerfan.h

typedef struct {
  uint8_t   active_speed,    // 0-255 (fullspeed); Speed with enabled stepper motors
            idle_speed;      // 0-255 (fullspeed); Speed after idle period with all motors are disabled
  uint16_t  duration;        // Duration in seconds for the fan to run after all motors are disabled
  bool      auto_mode;       // Default true
} controllerFan_settings_t;

#ifndef CONTROLLERFAN_SPEED_ACTIVE
  #define CONTROLLERFAN_SPEED_ACTIVE 255
#endif
#ifndef CONTROLLERFAN_SPEED_IDLE
  #define CONTROLLERFAN_SPEED_IDLE     0
#endif
#ifndef CONTROLLERFAN_IDLE_TIME
  #define CONTROLLERFAN_IDLE_TIME     60
#endif

So it does not look like it works the same as with FAN_SOFT_PWM.

**Comment by Parozzz** [comment]
I have the same issues. Also tried bugfix-2.0.x and the issues still persist by this day. If I disable FAN_SOFT_PWM my part cooling fan is always stuck on (I guess that how it should be) but my controller is deactivate correctly. As soon as I enable FAN_SOFT_PWM the part cooling fan start working fine again but controller fan is struck 100%. The same configuration was working fine on Marlin 2.0.9.1.

EDIT: Remove the old part inside controllerfan.cpp with a simple digitalWrite allows the fan to simply turn on or off.
Old part:
`
   if (PWM_PIN(CONTROLLER_FAN_PIN))
      set_pwm_duty(pin_t(CONTROLLER_FAN_PIN), speed);
    else
      WRITE(CONTROLLER_FAN_PIN, speed);
`
New Part:
`  digitalWrite(pin_t(CONTROLLER_FAN_PIN), speed != 0); `

**Comment by Pheelix** [comment]
From my searching on this issue.  I found another post where someone dug through the code and saw that the Controller Fan does not use the FAN_SOFT_PWM function.  I use [Dual Mosfet Controller Module](https://amzn.to/3mTMyiN) to control the speed of my 60mm 12v fans in my custom Enclosure to keep my stepper drivers and RPI cool.  Even while using the Module, I get low sounding hum/buzz from the fans unless they are at 100%.  FAN_SOFT_PWM works fine for my part/hotend cooling fans as they are hooked up to the fan headers on the mainboard, but my controller fans are using one of the endstop headers P1_26 (SKR 1.4T).   

It would be nice if they could add a option to enable FAN_SOFT_PWM on a header(pin).  Or add the controller fans to the FAN_SOFT_PWM with a enable/disable option.

I will dig through the code and see were the FAN_SOFT_PWM is and see if there is a way to add the header(pin) to it.  But I don't know if it will be that simple.

**Comment by descipher** [comment]
@Pheelix  That's correct, the CONTROLLER_FAN feature does not integrate with FAN_SOFT_PWM however it is possible to use FAN_SOFT_PWM. It would require an additional soft_fan_pwm speed update value in temperature.cpp to enabled it. It also would need some directives and functions in the controllerfan.cpp code to control when to activate the fan with it. I did something similar to it with the Laser Cooler Fan control code. I may poke at it this week.

**Comment by descipher** [comment]
@Parozzz  Looks like you may be using a non PWM pin. digitalWrite is not required, this should do the trick:

else WRITE(CONTROLLER_FAN_PIN, speed > 0);

e.g. WRITE(pinmask, bitvalue);
 
for a non PWM pin.

**Comment by Parozzz** [comment]
> @Parozzz Looks like you may be using a non PWM pin. digitalWrite is not required, this should do the trick:
> 
> else WRITE(CONTROLLER_FAN_PIN, speed > 0);
> 
> e.g. WRITE(pinmask, bitvalue);
> 
> for a non PWM pin.

That's strange because it was working fine on Marlin 2.0.9.1 on the same pin same configuration files.

**Comment by Pheelix** [comment]
> > @Parozzz Looks like you may be using a non PWM pin. digitalWrite is not required, this should do the trick:
> > else WRITE(CONTROLLER_FAN_PIN, speed > 0);
> > e.g. WRITE(pinmask, bitvalue);
> > for a non PWM pin.
> 
> That's strange because it was working fine on Marlin 2.0.9.1 on the same pin same configuration files.

I am using the PWM pin, the Module requires it for it to be able to adjust the voltage for the fans.

**Comment by descipher** [comment]
> > @Parozzz Looks like you may be using a non PWM pin. digitalWrite is not required, this should do the trick:
> > else WRITE(CONTROLLER_FAN_PIN, speed > 0);
> > e.g. WRITE(pinmask, bitvalue);
> > for a non PWM pin.
> 
> That's strange because it was working fine on Marlin 2.0.9.1 on the same pin same configuration files.

The only way you will hit the else is when Macro PWM_PIN returns false.
What pin and board are you running?

**Comment by Pheelix** [comment]
> @Parozzz Looks like you may be using a non PWM pin. digitalWrite is not required, this should do the trick:
> 
> else WRITE(CONTROLLER_FAN_PIN, speed > 0);
> 
> e.g. WRITE(pinmask, bitvalue);
> 
> for a non PWM pin.

I am using the PWM pin, on P1_26.  The Module I am using requires it, so it can adjust the voltage for the fans.

@Parozzz Sorry for the miss reply if you get the email notification.

**Comment by Pheelix** [comment]
> @Pheelix That's correct, the CONTROLLER_FAN feature does not integrate with FAN_SOFT_PWM however it is possible to use FAN_SOFT_PWM. It would require an additional soft_fan_pwm speed update value in temperature.cpp to enabled it. It also would need some directives and functions in the controllerfan.cpp code to control when to activate the fan with it. I did something similar to it with the Laser Cooler Fan control code. I may poke at it this week.

That be nice,  I am not in the same room as the printer, so I don't hear the fans.  But would still be nice to fix it, so they don't have to whine.

Sorry about the miss reply's, been a long day.

**Comment by Parozzz** [comment]
> > > @Parozzz Looks like you may be using a non PWM pin. digitalWrite is not required, this should do the trick:
> > > else WRITE(CONTROLLER_FAN_PIN, speed > 0);
> > > e.g. WRITE(pinmask, bitvalue);
> > > for a non PWM pin.
> > 
> > 
> > That's strange because it was working fine on Marlin 2.0.9.1 on the same pin same configuration files.
> 
> The only way you will hit the else is when Macro PWM_PIN returns false. What pin and board are you running?

I am using a BTT Skr mini E3 v2.0 (It should be a STM32F1, I can't look right now) and the pin is PC6 which is marked as a fan pin on the board so it should be a PWM pin.

**Comment by descipher** [comment]
FYI

#ifndef BOARD_INFO_NAME
  #define BOARD_INFO_NAME "BTT SKR Mini E3 V2.0"
#endif
.
.
#define FAN1_PIN                           PC7

#ifndef CONTROLLER_FAN_PIN
  #define CONTROLLER_FAN_PIN               FAN1_PIN
#endif

Seems the CONTROLLER_FAN_PIN is already defined as a fan pin, this is not cool since that would conflict with the feature. If the pin is assigned to as FAN1_PIN then  it will be counted as a FAN_COUNT and that would be clobbered by FAN_SOFT_PWM and set_pwm_duty both writing out to the pin.

**Comment by descipher** [comment]
Someone was clever to use filtering to prevent including FAN#_PIN = CONTROLLER_FAN_PIN
conditionals_post.h:2533
&& CONTROLLER_FAN_PIN != FAN##F##_PIN \

so FAN#_PIN can be defined to CONTROLLER_FAN_PIN

**Comment by descipher** [comment]
If you are using PC6 then be aware that it conflicts with FAN_PIN so I suggest using FAN1 (PC7) which is already defined for the controller fan.
 
#ifdef SKR_MINI_E3_V2
  #define FAN_PIN                           PC6
#else
  #define FAN_PIN                           PA8   // "FAN0"
#endif

**Comment by Parozzz** [comment]
I might have forgotten to say that I have modified the board pins files to avoid having conflict. In fact, I am using what originally was the neopixel pin to control a MOSFET for the part cooling fan (12v fan with a buck controller). And might have swapper the connectors and instead of moving connectors I changed the files (maybe I'll fix it in future).

**Comment by descipher** [comment]
@Parozzz If you have modified the board pin layout code then you may need to accept that it will not work the way you expect. There are many macros that modify function based on the named defines.

**Comment by thisiskeithb** [comment]
#23125 has been merged.
