### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by Sonicboom247** [MarlinFirmware/Marlin#22987]
### Is your feature request related to a problem? Please describe.

I am trying to compile for the Artillery Ruby board and am now getting "error: unknown board" .
I was able to compile this quite a while ago so my guess is the board was either removed or renamed under another.  It seems to be an STM32F40 board as defined  #define BOARD_ARTILLERY_RUBY  4230  // Artillery RUBY (STM32F401RCT6)

### Are you looking for hardware support?

This is for the Artillery3D Hornet printer

### Describe the feature you want

reintroduce the STM32F401RCT6 board 

### Additional context

Thank you!

**Comment by thisiskeithb** [comment]
That board has not been added to Marlin before.

You were using ~~https://github.com/artillery3d/sidewinder-x2-firmware~~ https://github.com/artillery3d/hornet-firmware.

**Comment by Sonicboom247** [comment]
thanks @thisiskeithb , I have two Sidewinders and a Hornet, the Sidewinders use the MKS GEN L boards and the Hornet uses the Artillery Ruby board, not sure why but i now get the error unknown board for the Board_Artillery_ruby.. after some digging i found it is also called the STM32F401RCT6 which seems to be defined in pio as genericSTM32F401RCT6...
this is the one i originally used, https://github.com/artillery3d/hornet-firmware

**Comment by thisiskeithb** [comment]
Continue to use Artillery's repos for now. The Ruby board is not supported here (mainline Marlin) yet.

**Comment by Sonicboom247** [comment]
This was my error from working all day..... didn't realize it was in upper case until another user mentioned it
