### ISSUE TITLE
[BUG] Power peaks with Marlin (compared to ender 3 stock)

### ISSUE THREAD

**Issue by isarrider** [MarlinFirmware/Marlin#22995]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Ender 3 has, after compiling & flashing the latest Marlin 2.0.9.2, spikes in the power usage...
(compared to both ender 3 Stock firmware)
That suggests a nonoptimal thermal control...
Is there any known setting to improve this?
I compared the latest ender 3 configuration.h and configuration_adv.h,
but the settings regarding temperature are the same...
The model that I printed is the same!

### Expected behavior

power curve like pic attached
![Ender3_stock](https://user-images.githubusercontent.com/6953309/138079920-89dcc45c-f349-4108-bf97-7575f1f099a8.png)
ed

### Actual behavior

Power peaks like pci attached
![Marlin](https://user-images.githubusercontent.com/6953309/138080010-69ec5f24-3e56-45fc-9904-510f42f30a2a.png)

### Steps to Reproduce

compile and flash latest Marlin on Ender 3 (with 4.2.2. motherboard) and use a power meter...

### Version of Marlin Firmware

2.0.9.2

### Printer model

Ender-3

### Electronics

4.2.2 stock board

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

**Comment by thisiskeithb** [comment]
You didn't provide your configurations from any tested versions, but I'm going to guess that it's related to `PIDTEMPBED`.

Enable `PIDTEMPBED`, run a [PID tune](https://marlinfw.org/docs/gcode/M303.html) and see if the spikes smooth out.

**Comment by isarrider** [comment]
thx for the hint, altough the values are exactly the same in the to header files from Creality...

**Comment by isarrider** [comment]
@thisiskeithb it seems you were exactly right - thank you...
