### ISSUE TITLE
[BUG] Axis homing stops before endstops triggered

### ISSUE THREAD

**Issue by 4lfamyk** [MarlinFirmware/Marlin#22997]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

While homing the axes, the process stops just before limit switch is triggered (stops when x_min, z_min are still open).
Confirmed by reflashing bugfix-2.0.x with Sensorless homing disabled. Rechecked and rewired the endstops, with the same result. 

### Expected behavior

Homing the axes should stop only after triggering the endstops

### Steps to Reproduce

Reproducible by G28

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Ender 3

### Electronics

BTT SKR 1.4 Turbo

### Add-ons

TMC2209 steppers

### Bed Leveling

No Bed Leveling

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Additional information & file uploads

[Config-21102021.zip](https://github.com/MarlinFirmware/Marlin/files/7385712/Config-21102021.zip)

**Comment by ellensp** [comment]
homing moves the entire axis length
If it doesnt reach your endstops you have the axis lengths or micro stepping or steps/mm wrong. 
Or iti s triggering prematurely due to not modifying tmc stepper drivers

**Comment by ellensp** [comment]
_**"Note: When using the TMC2209, if you don't use the stallguard functions, you need to cut off the DIAG pin on the driver so that the mechanical switch can work normally."**_

…from the btt skr 1.4 manual https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/BTT%20SKR%20V1.4/BTT%20SKR%20V1.4%20Instruction%20Manual.pdf

**Comment by 4lfamyk** [comment]
This is already taken care of. The pin is not connected to the motherboard

**Comment by 4lfamyk** [comment]
> 
> 
> homing moves the entire axis length If it doesnt reach your endstops you have the axis lengths or micro stepping or steps/mm wrong. Or iti s triggering prematurely due to not modifying tmc stepper drivers

The homing worked perfectly up to some days ago. The printer setup has completed 300+ hours of printing with this configuration. This issue was observed a couple of days ago after I flashed the latest version of the bugfix branch.

**Comment by ellensp** [comment]
ok... Ill reopen then. see if anyone else has any ideas

**Comment by thinkyhead** [comment]
Marlin will only stop a homing move because some endstop is reporting as triggered. It doesn't stop for any other reasons. So, let's enable detailed logging and gather data to see what is happening:

- Download Marlin `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.

**Comment by thinkyhead** [comment]
Options that may help to isolate endstop issues…
```
/**
 * Endstop Noise Threshold
 *
 * Enable if your probe or endstops falsely trigger due to noise.
 *
 * - Higher values may affect repeatability or accuracy of some bed probes.
 * - To fix noise install a 100nF ceramic capacitor in parallel with the switch.
 * - This feature is not required for common micro-switches mounted on PCBs
 *   based on the Makerbot design, which already have the 100nF capacitor.
 *
 * :[2,3,4,5,6,7]
 */
//#define ENDSTOP_NOISE_THRESHOLD 2

// Check for stuck or disconnected endstops during homing moves.
//#define DETECT_BROKEN_ENDSTOP
```
Try increasing the `ENDSTOP_NOISE_THRESHOLD` to see if it eliminates false positives. Too many false positives may indicate hardware problems, such as loose plugs or line noise.

The `DETECT_BROKEN_ENDSTOP` option does a little extra checking during homing to catch endstop anomalies.

**Comment by 4lfamyk** [comment]
Hi
I made the modification and reflashed (without Noise Threshold change)
Please find the log along with the images of the homed positio
[G28Log.txt](https://github.com/MarlinFirmware/Marlin/files/7404070/G28Log.txt)
![X Home Position](https://user-images.githubusercontent.com/8636199/138580681-f79bb3df-33d4-49e0-9cdf-872110040a9d.jpg)
![Y Home Position](https://user-images.githubusercontent.com/8636199/138580685-e07e6c3a-8806-4a59-8813-4223229ee91d.jpg)
![Z Home Position](https://user-images.githubusercontent.com/8636199/138580688-4e42d4f7-8af1-490f-9ff1-2db8c5bc5630.jpg)
n.

**Comment by 4lfamyk** [comment]
Any ideas on how to proceed?

**Comment by Tannoo** [comment]
If you raise Z to about 150mm and then do G28.
Does it move down to the same position and stop?

Also, can you manually trigger the home switch while it is traveling to make it stop?

**Comment by Tannoo** [comment]
I am wondering if the switch wires are shorting somewhere along the path to the board causing a pre-mature homing?
I don't believe this is a software issue.

But M119 will report if the endstop is triggered.

**Comment by ellensp** [comment]
you NEED to enable ENDSTOP_NOISE_THRESHOLD, as those machine have bad wire routing putting sensitive endstop wires right next high voltage to stepper motor wires, causing false triggering

**Comment by 4lfamyk** [comment]
> 
> 
> I am wondering if the switch wires are shorting somewhere along the path to the board causing a pre-mature homing? I don't believe this is a software issue.
> 
> But M119 will report if the endstop is triggered.

I observed M119 just at the end of homing process, and the endstops were NOT triggered. only the X-axis was, which was to be expected given the position shared in the image above.

**Comment by 4lfamyk** [comment]
> 
> 
> If you raise Z to about 150mm and then do G28. Does it move down to the same position and stop?
> 
> Also, can you manually trigger the home switch while it is traveling to make it stop?

Yeah, I tried repeating G28 multiple times, from various heights, and it stops at the exact same position. I havent tried manually triggering it. Will try it today.

**Comment by 4lfamyk** [comment]
> 
> 
> you NEED to enable ENDSTOP_NOISE_THRESHOLD, as those machine have bad wire routing putting sensitive endstop wires right next high voltage to stepper motor wires, causing false triggering

I will enable this and try, but I have been using this configuration with the same wiring for quite some time and afaik, nothing has changed w.r.t wiring. But still, if nothing works, I have some alternate wiring ready at hand.

**Comment by 4lfamyk** [comment]
Okay, so Endstop Noise threshold did not work, rather it halted the printer everytime it tried to home Z-axis. Ended up having to change the wiring, found that if I connect VCC, GND and Signal of the limit switch, again emergency halt was called for Z homing.

The only wiring configuration that seemed to be working is 

VCC (switch) - GND (SKR)
Signal (switch) - Signal (SKR)
Gnd (switch) - Open.

What a mess! Probably need to check NO/NC expectations in the FW?

**Comment by ellensp** [comment]
No expectations, you set it with ENDSTOP_INVERTING

**Comment by ellensp** [comment]
skr 1.4 has hardware pullup resistors. they cannot be disabled in firmware.
signal disconnected or connected to vcc is high , signal connected to gnd is low
which one is triggered or open is set with ENDSTOP_INVERTING

**Comment by 4lfamyk** [comment]
Okay I understand...I guess in that case, this is actually resolved..
