### ISSUE TITLE
[BUG] The directory ".pio/build/STM32F103RET6_creality/FrameworkArduino" doesn't get created. 

### ISSUE THREAD

**Issue by jebradley** [MarlinFirmware/Marlin#22992]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When attempting to compile Marlin-bugfix-2.0.x for the Creality Ender-3 Pro with the 4.2.7 board, I get a compile error. The directory ".pio/build/STM32F103RET6_creality/FrameworkArduino" doesn't get created. The compile then chokes because it can't find the directory. It compiles fine after creating the directory.

### Bug Timeline

It's happened the past couple of bugfix versions that I've tried

### Expected behavior

I expected the compile to run without problems when using Configuration.h and Configuration_adv.h files that had previously worked.

### Actual behavior

It gives a compile error.

### Steps to Reproduce

1. copy configuration files to Marlin-bugfix-2.0.x/Marlin directory
2. change platformio.ini "default_envs = STM32F103RET6_creality" 
3. attempt to compile - FAIL
4. If the "..pio/build/STM32F103RET6_creality/FrameworkArduino" is manually created, it will compile without problems.

### Version of Marlin Firmware

Marlin-bugfix-2.0.x

### Printer model

Creality Ender-3 Pro

### Electronics

Creality 4.2.7 board

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by jebradley** [comment]
When asked if I'd tested the bugfix code, I should have responded that it only occurs with the bugfix code. I compiled 2.0.9.2 without any problems. I had previously compiled some of the bugfix code and didn't have a problem, so it's a more recent occurrance.

**Comment by jebradley** [comment]
Sonicboom247, I don't think that the issue that I reported has anything to do with your issue. Your issue appears to be an incorrect 'default_envs" statement in platformio.ini. It looks like you need to use 'default_envs = artillery_ruby' instead of 'default_envs = Artillery Ruby'.

**Comment by Sonicboom247** [comment]
@jebradley Thanks! you nailed it, darn upper case got me again.

**Comment by ellensp** [comment]
Cannot replicate
Using:
Linux 
Latest Bugfix
Latest Creality/Ender-3 Pro/CrealityV427 configs
Latest platformio

**Comment by jebradley** [comment]
ellensp,
I am also on Linux, using the latest platformio using Microsoft Visual Studio Code for Linux, and the entire .pio directory isn't installed until I attempt to compile Marlin. 

I just unzipped both the bugfix and latest builds into new directories, and I have the same error with both.

After I get the error messages and the failed compile, if I manually create the FrameworkArduino subdirectory, it compiles without complaint. I

The following is the output from the attempted compile of the bugfix version (10/19 version)
Assembler messages:

Compiling .pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_device.c.o
Fatal error: can't create .pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/cortexm/sys.c.o: No such file or directory
Compiling .pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_init.c.o
Assembler messages:
Fatal error: can't create .pio/build/STM32F103RET6_creality/FrameworkArduino/WString.cpp.o: No such file or directory
Assembler messages:
*** [.pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/cortexm/sys.c.o] Error 1
Fatal error: can't create .pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_device.c.o: No such file or directory
Compiling .pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_io.c.o
*** [.pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_device.c.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_init.c.o: No such file or directory
*** [.pio/build/STM32F103RET6_creality/FrameworkArduino/WString.cpp.o] Error 1
*** [.pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_init.c.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_io.c.o: No such file or directory
*** [.pio/build/STM32F103RET6_creality/FrameworkArduino/stm32/OpenAMP/libmetal/generic/generic_io.c.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/STM32F103RET6_creality/FrameworkArduino/pins_arduino.c.o: No such file or directory
*** [.pio/build/STM32F103RET6_creality/FrameworkArduino/pins_arduino.c.o] Error 1
Assembler messages:
Fatal error: can't create .pio/build/STM32F103RET6_creality/FrameworkArduino/main.cpp.o: No such file or directory
*** [.pio/build/STM32F103RET6_creality/FrameworkArduino/main.cpp.o] Error 1

**Comment by ellensp** [comment]
.pio is not part of marlin. It is only created when you run platfomio 
This has nothing to do with marlin.

**Comment by ellensp** [comment]
I do get this from time to time, just hit compile again. 

This is a platfomio issue

**Comment by jebradley** [comment]
ellensp,
 thank you. I'm new enough to using platformio and VS Code, that I didn't
even think about them being the problem.
