### ISSUE TITLE
[BUG] Probe temperature compensation interpolation gives incorrect results

### ISSUE THREAD

**Issue by tombrazier** [MarlinFirmware/Marlin#23002]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

There are three ways in which probe temperature compensation gives incorrect adjustments to Z height:

1. If the probe temperature is outside the range given by PTC_SAMPLE_START, PTC_SAMPLE_RES and PTC_SAMPLE_COUNT then no adjustment is applied. This is the case even if PTC_LINEAR_EXTRAPOLATION is specified. (The same applies to bed and extruder temperatures.)

The cause of this is the WITHIN() expression in ProbeTempComp::compensate_measurement(). This expression is unneeded because ProbeTempComp::get_offset_for_temperature() already handles cases where the temperature is out of range - either clamping to the top/bottom measurement or extrapolating beyond the range.

2. Inside ProbeTempComp::get_offset_for_temperature() there is an off by one error and the wrong pair of measurements is used when interpolating. The lambda function point() couples start_temp with data[0], start_temp+1 with data[1], etc. But start_temp by definition has an offset of 0.0 and it is start_temp+res_temp which matches data[0], etc.

3. The lambda function linear_interp() contains a typo: (p2.x - p2.y) should be (p2.x - p1.x) in the line
    return (p2.y - p1.y) / (p2.x - p2.y) * (x - p1.x) + p1.y;

### Bug Timeline

It has been in the code for over a year.

### Expected behavior

Set up M871 with the following values:

Probe temp: 30C; Offset: 0.00 um
Probe temp: 35C; Offset: 1000.00 um
Probe temp: 40C; Offset: 2000.00 um
Probe temp: 45C; Offset: 3000.00 um
Probe temp: 50C; Offset: 4000.00 um
Probe temp: 55C; Offset: 5000.00 um
Probe temp: 60C; Offset: 6000.00 um
Probe temp: 65C; Offset: 7000.00 um
Probe temp: 70C; Offset: 8000.00 um
Probe temp: 75C; Offset: 9000.00 um
Probe temp: 80C; Offset: 10000.00 um

ProbeTempComp::compensate_measurement() should give a value that is consistent with this. e.g. with the following debug statements

```
  float meas = 0.0;
  compensate_measurement(TSI_PROBE, 27, meas);
  SERIAL_ECHOLNPGM("adjustment 27: ", meas);
  meas = 0.0;
  compensate_measurement(TSI_PROBE, 32, meas);
  SERIAL_ECHOLNPGM("adjustment 32: ", meas);
  meas = 0.0;
  compensate_measurement(TSI_PROBE, 77, meas);
  SERIAL_ECHOLNPGM("adjustment 77: ", meas);
  meas = 0.0;
  compensate_measurement(TSI_PROBE, 82, meas);
  SERIAL_ECHOLNPGM("adjustment 82: ", meas);
```

You should get the results

adjustment 27: 0.60
adjustment 32: -0.40
adjustment 77: -9.40
adjustment 82: -10.40

### Actual behavior

You get the results

adjustment 27: 0.00
adjustment 32: -1.00
adjustment 77: -9.00
adjustment 82: 0.00

### Steps to Reproduce

1. Configure marlin with a Z probe with temperature sensor and also a bed temperature sensor.
2. Also #define PTC_LINEAR_EXTRAPOLATION 1 in Configuration_adv.h.
3. Insert the debug statement above (e.g. add it to ProbeTempComp::print_offsets()).
4. Use M871 to set up the values above.
5. Trigger the debug statements (e.g. issue gcode M871).

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.0.x (Oct 22 2021 14:53:03)

### Printer model

Custom ATMega256 based machine

### Additional information & file uploads

[files.zip](https://github.com/MarlinFirmware/Marlin/files/7400045/files.zip)

**Comment by tombrazier** [comment]
And a further bug:

In `ProbeTempComp::get_offset_for_temperature()` there is some integer rounding badness in this line:

```cpp
uint8_t idx = static_cast<uint8_t>((temp - start_temp) / res_temp);
```

`idx` needs to be signed (as seen a few lines later with the statement `if (idx < 0) ...`)

and if `(temp - start_temp)` is negative then the result of the division rounds upwards, unlike for positive integer division.

**Comment by thinkyhead** [comment]
Do you have a patch? Someone else (me maybe?) can study the code and try to come up to your level of comprehension to be able to patch the bug, but it's always better to just submit a patch when you're the one who already understands the issue.

**Comment by tombrazier** [comment]
I am about to submit a PR.

**Comment by tombrazier** [comment]
Are you suggesting I might have just submitted the PR and not raised this issue? (It's my first time contribution to marlin.)

**Comment by thinkyhead** [comment]
> Are you suggesting I might have just submitted the PR and not raised this issue?

An issue plus a patch does feel more complete, but just a patch is fine. Of course, thank you for the thorough explanation, since too many reports just leave us scratching our heads.
