### ISSUE TITLE
[BUG] Two Trees Saphire plus V1.2 ( 2020 ) sample config incorrect on so many levels

### ISSUE THREAD

**Issue by Vecna8080** [MarlinFirmware/Marlin#23000]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The sample config [https://github.com/MarlinFirmware/Configurations/archive/release-2.0.9.2.zip](url) for Two Trees Sapphire plus V1.2 ( 2020 ) is profoundly knackered, and before anyone asks its similarly knackered on all the other branches.

Does not compile ( serial buffer set way to high so does not fit into ram compile error ) touch screen gets missed in definition because of some not necessary extra compiler directives, and other crap.

Rather than going through each part i created a new set ( config and adv ) that works correctly , compiles etc.

The files stick strictly to the standard config(adv) format and work on the 
Following hardware config.
[MarlinConfig.zip](https://github.com/MarlinFirmware/Marlin/files/7391206/MarlinConfig.zip)

Two Trees Sapphire plus V1.2 ( 2020 )
Independent Z axis
BL Touch ( version supplied with printer ) -- Trigger signal on Filament run-out sensor 2

### Version of Marlin Firmware

2.0.9.2

### Printer model

Two Trees Sapphire plus V1.2 ( 2020 )

### Additional information & file uploads

[MarlinConfig.zip](https://github.com/MarlinFirmware/Marlin/files/7391205/MarlinConfig.zip)

**Comment by thisiskeithb** [comment]
The config you are editing is the V2 model , not the 1.2.

We don't have a 1.2 config.

https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Two%20Trees

**Comment by thisiskeithb** [comment]
Please open a configuration request in the [Configurations repo](https://github.com/MarlinFirmware/Configurations/issues/new/choose).
