### ISSUE TITLE
[BUG] Settings NUM_Z_STEPPER_DRIVERS=4 on BTT_OCTOPUS_V1 will not include Z3

### ISSUE THREAD

**Issue by Aurawin** [MarlinFirmware/Marlin#23012]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Settings NUM_Z_STEPPER_DRIVERS>2 with BTT_OCTOPUS_V1  yields compiler error due to layout of diag pins.

### Bug Timeline

Always present

### Expected behavior

When I set NUM_Z_STEPPER_DRIVERS=4 marlin should compile successfully taking account, re-indexing Z3,Z4 steppers in place of extra extruder steppers by name.

### Actual behavior

When I set NUM_Z_STEPPER_DRIVERS=4 marlin should compile due to incorrect pin mappings in the pins_BTT_OCTOPUS_V1_common.h file

### Steps to Reproduce

NUM_Z_STEPPER_DRIVERS=4 

### Version of Marlin Firmware

2.0.x

### Printer model

Tronxy 5Xs (Nothing but 2020 left tho)

### Electronics

BigTreeTech Octopus V1_1

### Add-ons

Quad Steppers (Nema 17, TMC2209)

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Other (explain below)

### Additional information & file uploads

I have this issue resolved by modifying pins_BTT_OCTOPUS_V1_common.h with the ability to respect NUM_Z_STEPPER_DRIVERS.

Since the Octopus has 8 steppers when users change num of Z steppers, extruders and z steppers need to be declared in a more advanced way.
On a Core XY Octopus pins should be organized like  :
1 Z stepper   : X,Y,Z,E0,E1,E2,E3,E4
2 Z Steppers : X,Y,Z1,Z2, E0,E1,E2,E3
3 Z Steppers : X,Y,Z1,Z2,Z3, E0, E1, E2
4 Z Steppers : X,Y,Z1,Z2,Z3,Z4, E0,E1

So with all these steppers their labels and pin assignments must be handled in a more complex way than is present to avoid breaking the sanity checks of Marlin.

**Comment by thisiskeithb** [comment]
Did you actually test with the the latest bugfix? Please attach your configs.

I just compiled an Octopus build with four Z steppers and it works as intended:

```prolog
Marlin/src/inc/Warnings.cpp:219:4: warning: #warning "Auto-assigned Z3 STEP/DIR/ENABLE_PINs to unused En_STEP/DIR/ENABLE_PINs." [-Wcpp]
  219 |   #warning "Auto-assigned Z3 STEP/DIR/ENABLE_PINs to unused En_STEP/DIR/ENABLE_PINs."
      |    ^~~~~~~
Marlin/src/inc/Warnings.cpp:222:4: warning: #warning "Auto-assigned Z3_CS_PIN to an unused En_CS_PIN." [-Wcpp]
  222 |   #warning "Auto-assigned Z3_CS_PIN to an unused En_CS_PIN."
      |    ^~~~~~~
Marlin/src/inc/Warnings.cpp:271:4: warning: #warning "Auto-assigned Z4 STEP/DIR/ENABLE_PINs to unused En_STEP/DIR/ENABLE_PINs." [-Wcpp]
  271 |   #warning "Auto-assigned Z4 STEP/DIR/ENABLE_PINs to unused En_STEP/DIR/ENABLE_PINs."
      |    ^~~~~~~
Marlin/src/inc/Warnings.cpp:274:4: warning: #warning "Auto-assigned Z4_CS_PIN to an unused En_CS_PIN." [-Wcpp]
  274 |   #warning "Auto-assigned Z4_CS_PIN to an unused En_CS_PIN."
```

**Comment by Aurawin** [comment]
Righto, now that I think back it did compile but it doesn't actually work.  I'll go compile bugfix latest but I'm using 2.0.x branch atm.  Bugfix had issues with the inductive probe optocoupler on the Octopus V1.1

**Comment by Aurawin** [comment]
Essentially, the diag pins need to be explicitly defined.

#if NUM_Z_STEPPER_DRIVERS == 4
  #define Z2_DIAG_PIN                       PG11  // Z2-STOP
  #define Z3_DIAG_PIN                       PG12  // Z3-STOP
  #define Z4_DIAG_PIN                       PG13  // Z4-STOP
  #define E0_DIAG_PIN                       PG14  // E0DET
  #define E1_DIAG_PIN                       PG15  // E1DET

  #define Z2_SERIAL_TX_PIN                  PC7
  #define Z2_SERIAL_RX_PIN      Z2_SERIAL_TX_PIN

  #define Z3_SERIAL_TX_PIN                  PF2
  #define Z3_SERIAL_RX_PIN      Z3_SERIAL_TX_PIN

  #define Z4_SERIAL_TX_PIN                  PE4
  #define Z4_SERIAL_RX_PIN      Z4_SERIAL_TX_PIN

  #define E0_SERIAL_TX_PIN                  PE1
  #define E0_SERIAL_RX_PIN      E0_SERIAL_TX_PIN

  #define E1_SERIAL_TX_PIN                  PD3
  #define E1_SERIAL_RX_PIN      E1_SERIAL_TX_PIN

  #define Z2_STEP_PIN                       PG4   // MOTOR 3
  #define Z2_DIR_PIN                        PC1
  #define Z2_ENABLE_PIN                     PA0
  #ifndef Z2_CS_PIN
    #define Z2_CS_PIN                       PC7
  #endif

  #define Z3_STEP_PIN                       PF9   // MOTOR 4
  #define Z3_DIR_PIN                        PF10
  #define Z3_ENABLE_PIN                     PG2
  #ifndef Z3_CS_PIN
    #define Z3_CS_PIN                       PF2
  #endif

  #define Z4_STEP_PIN                       PC13  // MOTOR 5
  #define Z4_DIR_PIN                        PF0
  #define Z4_ENABLE_PIN                     PF1
  #ifndef Z4_CS_PIN
    #define Z4_CS_PIN                       PE4
  #endif

  #define E0_STEP_PIN                       PE2   // MOTOR 6
  #define E0_DIR_PIN                        PE3
  #define E0_ENABLE_PIN                     PD4
  #ifndef E0_CS_PIN
    #define E0_CS_PIN                       PE1
  #endif

  #define E1_STEP_PIN                       PE6   // MOTOR 7
  #define E1_DIR_PIN                        PA14
  #define E1_ENABLE_PIN                     PE0
  #ifndef E1_CS_PIN
    #define E1_CS_PIN                       PD3
  #endif
#elif NUM_Z_STEPPER_DRIVERS == 3
<snip>

**Comment by Aurawin** [comment]
#elif NUM_Z_STEPPER_DRIVERS == 3
  #define Z2_DIAG_PIN                       PG11  // Z2-STOP
  #define Z3_DIAG_PIN                       PG12  // Z3-STOP
  #define E0_DIAG_PIN                       PG13  // E0DET
  #define E1_DIAG_PIN                       PG14  // E1DET
  #define E2_DIAG_PIN                       PG15  // E2DET

  #define Z2_SERIAL_TX_PIN                  PC7
  #define Z2_SERIAL_RX_PIN      Z2_SERIAL_TX_PIN

  #define Z3_SERIAL_TX_PIN                  PF2
  #define Z3_SERIAL_RX_PIN      Z3_SERIAL_TX_PIN

  #define E0_SERIAL_TX_PIN                  PE4
  #define E0_SERIAL_RX_PIN      E0_SERIAL_TX_PIN

  #define E1_SERIAL_TX_PIN                  PE1
  #define E1_SERIAL_RX_PIN      E1_SERIAL_TX_PIN

  #define E2_SERIAL_TX_PIN                  PD3
  #define E2_SERIAL_RX_PIN      E2_SERIAL_TX_PIN

  #define Z2_STEP_PIN                       PG4   // MOTOR 3
  #define Z2_DIR_PIN                        PC1
  #define Z2_ENABLE_PIN                     PA0
  #ifndef Z2_CS_PIN
    #define Z2_CS_PIN                       PC7
  #endif

  #define Z3_STEP_PIN                       PF9   // MOTOR 4
  #define Z3_DIR_PIN                        PF10
  #define Z3_ENABLE_PIN                     PG2
  #ifndef Z3_CS_PIN
    #define Z3_CS_PIN                       PF2
  #endif

  #define E0_STEP_PIN                       PC13  // MOTOR 5
  #define E0_DIR_PIN                        PF0
  #define E0_ENABLE_PIN                     PF1
  #ifndef E0_CS_PIN
    #define E0_CS_PIN                       PE4
  #endif

  #define E1_STEP_PIN                       PE2   // MOTOR 6
  #define E1_DIR_PIN                        PE3
  #define E1_ENABLE_PIN                     PD4
  #ifndef E1_CS_PIN
    #define E1_CS_PIN                       PE1
  #endif

  #define E2_STEP_PIN                       PE6   // MOTOR 7
  #define E2_DIR_PIN                        PA14
  #define E2_ENABLE_PIN                     PE0
  #ifndef E2_CS_PIN
    #define E2_CS_PIN                       PD3
  #endif
#elif NUM_Z_STEPPER_DRIVERS == 2

**Comment by Aurawin** [comment]
#elif NUM_Z_STEPPER_DRIVERS == 2
  #define Z2_DIAG_PIN                       PG11  // Z2-STOP
  #define E0_DIAG_PIN                       PG12  // E0DET
  #define E1_DIAG_PIN                       PG13  // E1DET
  #define E2_DIAG_PIN                       PG14  // E2DET
  #define E3_DIAG_PIN                       PG15  // E3DET

  #define Z2_SERIAL_TX_PIN                  PC7
  #define Z2_SERIAL_RX_PIN      Z2_SERIAL_TX_PIN

  #define E0_SERIAL_TX_PIN                  PF2
  #define E0_SERIAL_RX_PIN      E0_SERIAL_TX_PIN

  #define E1_SERIAL_TX_PIN                  PE4
  #define E1_SERIAL_RX_PIN      E1_SERIAL_TX_PIN

  #define E2_SERIAL_TX_PIN                  PE1
  #define E2_SERIAL_RX_PIN      E2_SERIAL_TX_PIN

  #define E3_SERIAL_TX_PIN                  PD3
  #define E3_SERIAL_RX_PIN      E3_SERIAL_TX_PIN

  #define Z2_STEP_PIN                       PG4   // MOTOR 3
  #define Z2_DIR_PIN                        PC1
  #define Z2_ENABLE_PIN                     PA0
  #ifndef Z2_CS_PIN
    #define Z2_CS_PIN                       PC7
  #endif
  #define E0_STEP_PIN                       PF9   // MOTOR 4
  #define E0_DIR_PIN                        PF10
  #define E0_ENABLE_PIN                     PG2
  #ifndef E0_CS_PIN
    #define E0_CS_PIN                       PF2
  #endif

  #define E1_STEP_PIN                       PC13  // MOTOR 5
  #define E1_DIR_PIN                        PF0
  #define E1_ENABLE_PIN                     PF1
  #ifndef E1_CS_PIN
    #define E1_CS_PIN                       PE4
  #endif

  #define E2_STEP_PIN                       PE2   // MOTOR 6
  #define E2_DIR_PIN                        PE3
  #define E2_ENABLE_PIN                     PD4
  #ifndef E2_CS_PIN
    #define E2_CS_PIN                       PE1
  #endif

  #define E3_STEP_PIN                       PE6   // MOTOR 7
  #define E3_DIR_PIN                        PA14
  #define E3_ENABLE_PIN                     PE0
  #ifndef E3_CS_PIN
    #define E3_CS_PIN                       PD3
  #endif

**Comment by Aurawin** [comment]
#else // if NUM_Z_STEPPER_DRIVERS == 1
  #define E0_DIAG_PIN                       PG11  // E0DET
  #define E1_DIAG_PIN                       PG12  // E1DET
  #define E2_DIAG_PIN                       PG13  // E2DET
  #define E3_DIAG_PIN                       PG14  // E3DET
  #define E4_DIAG_PIN                       PG15  // E4DET

  #define E0_SERIAL_TX_PIN                  PC7
  #define E0_SERIAL_RX_PIN      E0_SERIAL_TX_PIN

  #define E1_SERIAL_TX_PIN                  PF2
  #define E1_SERIAL_RX_PIN      E1_SERIAL_TX_PIN

  #define E2_SERIAL_TX_PIN                  PE4
  #define E2_SERIAL_RX_PIN      E2_SERIAL_TX_PIN

  #define E3_SERIAL_TX_PIN                  PE1
  #define E3_SERIAL_RX_PIN      E3_SERIAL_TX_PIN

  #define E4_SERIAL_TX_PIN                  PD3
  #define E4_SERIAL_RX_PIN      E4_SERIAL_TX_PIN

  #define E0_STEP_PIN                       PG4   // MOTOR 3
  #define E0_DIR_PIN                        PC1
  #define E0_ENABLE_PIN                     PA0
  #ifndef E0_CS_PIN
    #define E0_CS_PIN                       PC7
  #endif
  #define E1_STEP_PIN                       PF9   // MOTOR 4
  #define E1_DIR_PIN                        PF10
  #define E1_ENABLE_PIN                     PG2
  #ifndef E1_CS_PIN
    #define E1_CS_PIN                       PF2
  #endif
  #define E2_STEP_PIN                       PC13  // MOTOR 5
  #define E2_DIR_PIN                        PF0
  #define E2_ENABLE_PIN                     PF1
  #ifndef E2_CS_PIN
    #define E2_CS_PIN                       PE4
  #endif

  #define E3_STEP_PIN                       PE2   // MOTOR 6
  #define E3_DIR_PIN                        PE3
  #define E3_ENABLE_PIN                     PD4
  #ifndef E3_CS_PIN
    #define E3_CS_PIN                       PE1
  #endif

  #define E4_STEP_PIN                       PE6   // MOTOR 7
  #define E4_DIR_PIN                        PA14
  #define E4_ENABLE_PIN                     PE0
  #ifndef E4_CS_PIN
    #define E4_CS_PIN                       PD3
  #endif
#endif

**Comment by Aurawin** [comment]
The Auto assigned logic d/n work because extruders and their pin assignments need to be re-indexed at design time, not compile time.

You can't expect marlin to drop the 4th and 3rd extruders in exchange for Z3, Z4 w/o knowing where to look for the pins which weren't even defined in the board's pin file.

**Comment by Aurawin** [comment]
Testing bugfix-2.0.x yields a few compile warnings but only Steppers Z1 ,Z2, Z4 spin, leaving Z3 to not energize.
Testing bugfix-2.0.x with the changes above, explicitly defining STEP,DIR,ENABLE,CS, Diag,RX,TX pins yields all 4 motors spin.

Keep in mind Z1,Z2,Z3,Z4 need to be known by the user/programmer b/c G34 needs to be explicitly set.  Meaning, there is not much use to "guess" what pins control what motor.

I can generate a pull request - which is my goal.

**Comment by thisiskeithb** [comment]
There’s no need to explicitly define all the potential pins because Marlin will auto-assign them.

By doing that for this one board, you’re going to create a maintenance nightmare since we’ll have to do the same thing for all boards if auto-assignment is removed.

It’s best to fix the auto assignment of pins if something isn’t working correctly.

**Comment by Aurawin** [comment]
Agreed.  Definitely want to keep it simple.

Bugfix-2.0.x yielded Autoconfigure resulted in  PC13 stepping (my Z4) but not PF9 (my Z3)

**Comment by Aurawin** [comment]
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/7406001/Config.zip)

**Comment by Aurawin** [comment]
Changed subject to narrow this down to Quad Zs and specifically NUM_Z_STEPPER_DRIVERS=4

**Comment by ellensp** [comment]
These axies are in fixed positions
X // MOTOR 0
Y // MOTOR 1
Z // MOTOR 2
Z2 //MOTOR 3

Your extruders go next, but only the one you use. You have "#define EXTRUDERS 1"
So 1 extruder is allocated 

E0 // MOTOR 4

Next the extra Axies are added, you have, NUM_Z_STEPPER_DRIVERS 4 so marlin needs to add in Z3 and Z4

Z3 // MOTOR 5
Z4 // MOTOR 6

leaving this effectively unused

E3 // MOTOR 7


If you wish an order different to this you have to manually edit Marlin/src/pins/stm32f4/pins_BTT_OCTOPUS_V1_common.h

**Comment by Aurawin** [comment]
The Auto Configure works provided the user connects the following motor ports to these steppers.

Single Extruder and 4 Steppers

Motor 0 -> X
Motor 1 -> Y
Motor 2 - >Z1
Motor 3 ->Z2
Motor 4 -> E0
Motor 5 ->Z3
Motor 6 -> Z4
Motor 7 -> Unused

Dual Extruder and 4 Steppers

Motor 0 -> X
Motor 1 -> Y
Motor 2 - >Z1
Motor 3 ->Z2
Motor 4 -> E0
Motor 5 -> E1
Motor 6 -> Z3
Motor 7 -> Z4

IMO, there should be documentation somewhere as to how the Z-Steppers needed to be plugged into various motor ports.  Starting after a dual Z-axis seems arbitrary.

Closing this because auto-configure works as expected, provided you use predetermined motor ports.
