### ISSUE TITLE
[BUG] PREHEAT_BEFORE_PROBING breaks G76

### ISSUE THREAD

**Issue by serbasan** [MarlinFirmware/Marlin#23014]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I can't get G76 together PREHEAT_BEFORE_PROBING active. It takes a long time to calibrate the probe and the bed is not done. I have to disable PREHEAT_BEFORE_PROBING and everything works

### Actual behavior

If you do a g76 deactivate PREHEAT_BEFORE_PROBING and when finished activate it again.

### Steps to Reproduce

Activate PREHEAT_BEFORE_PROBING and test a g76. It takes a long time to do probe calibration and does not perform the bed calibration

### Version of Marlin Firmware

Marlin 2.0.9.2 

### Printer model

Steel i3

### Electronics

gt2560 a+

### Add-ons

Pinda2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Slic3r

### Host Software

OctoPrint

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7406217/Marlin.zip)

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
