### ISSUE TITLE
[FR] Electromagnet probe support

### ISSUE THREAD

**Issue by Ave6683** [MarlinFirmware/Marlin#23011]
### Is your feature request related to a problem? Please describe.

I am a developer of bed leveling sensor for 3D printers. It features a electromagnet which is meant to release the probing needle. I've made some changes in Marlin to make it work but it's kind of a hassle to do it everytime for people who buy it.
Unfortunately Marlin doesn't support electromagnet release feature. 

### Are you looking for hardware support?

Yes, self made bed leveling sensor.
Sensor uses 5V as power and requires 3.3V or 5V signal to its trigger pin to release probing needle.
Output simply connects to Z_MIN pin. 

### Describe the feature you want

I'd like Marlin to have feature to set specified pin to HIGH for specified ammount of time.
E.g. Set pin PD0 to HIGH for 15ms so the probing needle can be released.
Also feature (if enabled) should be executed just before homing Z axis and leveling the bed (G29)

### Additional context

This feature could be unique for my sensor (MagLev V4), with settings (pin name, time) or could be universal feature like allen key probes. Where you just have generic values which have to be set by the user. This way people could use this feature for their own sensors.

**Comment by sjasonsmith** [comment]
Does the pin retract itself when it touches the bed? No action is needed at that point?

This is quite similar to `SOLENOID_PROBE`, although that will leave the pin high until the stow operation. It wouldn't be too hard to add an option for a duration, and make the deploy logic disable the output after a time delay.

If code changes are made for this, it might make more sense to create something like a `CUSTOM_PROBE` type, which simply allows you to specify G-Code macros for deploy/retract.

**Comment by Ave6683** [comment]
Pin doesn't retract when it touches the bed. Z axis has to move around 3mm to trigger Z_MIN and around 10mm to retract the pin. It rectracts automaticly using magnet inside the sensor.  

That's why I need to enable the pin for specific time only. Trigger is only needed to "reverse" magnetic field inside the sensor

The sensor looks like this:

![248345497_400839538335893_3039683275680651369_n](https://user-images.githubusercontent.com/53094187/138824996-eb7c4bfd-4a14-4d05-89a8-5b83c16d7b0c.jpg)
.

**Comment by Hman32** [comment]
@sjasonsmith  Seems to be the same logic as the Touch MI probe, except that you can trigger the magnet without moving to a specific location.

**Comment by kubeqsq** [comment]
It is a very promising probe. It has very high precision and it will be the better option as BL-Touch.  
It would be very nice, if you would add support for this probe. 
It would allow the further development of the hardware, multi function of the software and development of marlin based 3dprinters.

**Comment by Ave6683** [comment]
> Does the pin retract itself when it touches the bed? No action is needed at that point?
> 
> This is quite similar to `SOLENOID_PROBE`, although that will leave the pin high until the stow operation. It wouldn't be too hard to add an option for a duration, and make the deploy logic disable the output after a time delay.
> 
> If code changes are made for this, it might make more sense to create something like a `CUSTOM_PROBE` type, which simply allows you to specify G-Code macros for deploy/retract.

Yeah, SOLENOID_PROBE could be a good place to start. I was looking for code which is responsible for solenoid probe but no luck there. Could anyone lead me where I can find code where I can inject my changes needed for probe to work?

**Comment by Hman32** [comment]
@Ave6683 it's a mix of `TOUCH_MI_PROBE` and `SOLENOID_PROBE`. You need the servo pin to activate it but the flow is the same has the Touch MI to retract the pin

**Comment by Ave6683** [comment]
> @Ave6683 it's a mix of `TOUCH_MI_PROBE` and `SOLENOID_PROBE`. You need the servo pin to activate it but the flow is the same has the Touch MI to retract the pin

I still seem to not understand where I can make my changes... Or you mean I don't need to make any changes

**Comment by Hman32** [comment]
@Ave6683 , you will have to do some change but the `TOUCH_MI_PROBE` is the closer to your need.
The only change is to activate your electromagnet to release the pin in place of moving the probe close to the "release magnet".
Look on YouTube and you will find some video showing how work the Touch MI and you will know if it's the closest flow to implement your change. 

The flow for the TOUCH MI is: 
1) move to a specific location to release the PIN 
2) Start probing 
3) Move a little bit further down to lock the pin 
4) stop the probe

If it's the case, maybe you could check who has implemented the TOUCH MI and ask him.

**Comment by kubeqsq** [comment]
The easiest way would be to add this type of probe to marlin. 
The commands may be not so complicated , but marlin os evolving and in each type of marlin we should add this lines in other place. 
That complicates usege of such probe. 
The idea is very easy and unproblematic, only solenoid and magnet to read the bed leveling.... 
In conclusion it would be best for marlin- and for hardware development to make the configuration of the probe as easy as possible and add in probe types 
#define Maglev or so.... 
Best regards
Jakub

**Comment by TurboMech** [comment]
@Ave6683 is there any more information about your probe available?  Numerous google searches come up with nothing.

**Comment by thisiskeithb** [comment]
Support for this probe was added in https://github.com/MarlinFirmware/Marlin/pull/23192, but I can't seem to find if this was ever sold. @Ave6683: Did the MagLev probe ever make it to market?
