### ISSUE TITLE
[FR] Artillery Sidewinder X2 support

### ISSUE THREAD

**Issue by inigoml** [MarlinFirmware/Marlin#23027]
### Is your feature request related to a problem? Please describe.

Include Artillery Sidewinder X2 support in Marlin trunk. Currently only Sidewinder X1 is included. Sidewinder X2 has a STM32 board (Artillery_Ruby) that is not supported by default.

### Are you looking for hardware support?

Brand: Artillery 3D
Model: Sidewinder X2
Board:  STM32F401RC (64k RAM. 256k Flash)
 

### Describe the feature you want

Be included in Marlin official trunk

### Additional context

Artillery has released source code based in Marlin 2.0.9.1
https://github.com/artillery3d/sidewinder-x2-firmware

I've merged 2.0.9.1 branch with marlin 2.9.0.2 and I'm able to compile but not to link due to platform.io issues.

Only minor changes at source level are needed (pins.h, add new pins_artillery_ruby.h, configuration.h and configuration_adv.h plus some platform.io files).

**Comment by inigoml** [comment]
Got firmware compilation and linking to finish. Only minor files has to be modified plus adding some files for platformio from artillery marlin branch.

**Comment by thisiskeithb** [comment]
Their [`generate_hex.py`](https://github.com/artillery3d/sidewinder-x2-firmware/blob/fc9408316c220da701619c8479baed043a244c68/buildroot/share/PlatformIO/scripts/generate_hex.py) doesn't work correctly if the path has spaces. Reported [here](https://github.com/artillery3d/sidewinder-x2-firmware/issues/1) as well.

I renamed a couple things/fixed the rest of compiling, but the ~~`generate_hex.py`~~ [`artillery_ruby.py`](https://github.com/thisiskeithb/Marlin/blob/eccced531c2d3ba9d9f7a7cc22c9e2f3b84c87a8/buildroot/share/PlatformIO/scripts/artillery_ruby.py) script will need to be fixed: https://github.com/thisiskeithb/Marlin/tree/testing/add_artillery_ruby

**Comment by inigoml** [comment]
The issue for not linking was related with a function already defined in HAL.cpp that is also included in (buildroot/share/platformio/variants/artillery_ruby/variant.cpp)

```cpp
/*
void flashFirmware(const int16_t) {
  *((unsigned long *)0x2000FFF0) = 0xDEADBEEF; // End of RAM
  NVIC_SystemReset();
}
*/
```

**Comment by thinkyhead** [comment]
It sounds like it's nearly there. Once the PR is prepared we can move discussion there and close this feature request.

**Comment by thisiskeithb** [comment]
> It sounds like it's nearly there. Once the PR is prepared we can move discussion there and close this feature request.

See https://github.com/MarlinFirmware/Marlin/pull/23029

DO NOT MERGE. It doesn't work.

**Comment by thisiskeithb** [comment]
Sidewinder X2 config PR: https://github.com/MarlinFirmware/Configurations/pull/597
