### ISSUE TITLE
System restarts or fails on homing X axis from LCD

### ISSUE THREAD

**Issue by bmorse526** [MarlinFirmware/Marlin#23038]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Updated a makerFarm Pegasus that uses Arduino MEGA and RAMPS 1.4.  If X axis is over half way across travel homing fails and requires printer reset or does a full restart.  Homing X works and homing Z with BLtouch works.  Doing bed level works through first row (if X was close to home switch) but fails on second row.  Will ocasionally work when printing a file from SD that has G28 and G29 at start.  Prints without issues once started.  X and Y home ING are standard microswitches.  Issue only shows when X carriage is over 1/3 of bed width.  Switches trigger manually with no issues.  Only change from Marlin 1.0 on board previously was adding BLtouch.  Movement starts toward endstop, acts like it is triggered backs up moves back toward endstop (over 80mm from switch), then errors out or does power reset on board.

### Bug Timeline

On upload of bugfix 2.0.x 

### Expected behavior

X carriage continue movement to endstop.

### Actual behavior

X carriage move part way does false trigger then errors or power restarts

### Steps to Reproduce

1. Move X carriage to far side of bed
2. Center Y axis to bed center (more repeatable)
3. Select home X from LCD Menu
Bed is 232x232mm

### Version of Marlin Firmware

Bugfix 2.0.x 

### Printer model

MakerFarm Pegasus

### Electronics

Arduino MEGA with Ramos 1.4 (EFB)

### Add-ons

BLtouch 3.1

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Other (explain below)

### Additional information & file uploads

Oxtoprint is connected, but used to monitor only.  Prints from SD.

Bed leveling is set for bilinear with 3x3 array

**Comment by bmorse526** [comment]
Did additional testing through octoprint (raspberry pi platform)  sending G28 X0 , G28 Y0, OR G28 Z0 allresult in completion without issue (starting from far X,Y edges)  G28 X0Y0 completes successfully repeatedly.  Entering G28 fails when X axis does false trigger and shuts down from error.

**Comment by ellensp** [comment]
Can you provide actual config used?
What type of LCD do you have configured?

**Comment by bmorse526** [comment]
I changed the endstop filter threshold on and set to 3.  It has not
occurred since then.  May have some noise being feed from stepper wiring to
the X Home switch.  But that setting fixed the issue. Thank you.
