### ISSUE TITLE
[BUG] Update you includePath

### ISSUE THREAD

**Issue by GloriousGarbage** [MarlinFirmware/Marlin#23039]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I am trying to compile in VScode using extensions C/C++, AutoBuild Marlin, and PlatformIO. The build says it was successful but the after the board flashes, the display is blank. On almost every file I have 1 error message "#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\Hunter\Desktop\Marlin\Marlin-bugfix-2.0.x\Marlin\src\MarlinCore.cpp)". This is the only issue I think is causing my build issues for my BTT SKR mini E3 V1.2 firmware. 
[Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/7438827/Marlin-bugfix-2.0.x.zip)
 

### Expected behavior

having a bigger bed. all I changed was XYZ max to 400 and BLtouch to probe 6 times. This worked before but I believe an update may have changed something

### Actual behavior

No display after 3 dozen attempts

### Version of Marlin Firmware

Bugfix 2.0.x

### Printer model

Ender 3 Pro

### Electronics

BTT SKR mini E3 V1.2

### Add-ons

Ender extender kit, BLtouch, custom extruder fans/blower, Dual Z stepper, full direct drive/hotend upgrade by Microswiss

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by ellensp** [comment]
That is just platformio Intellisense. It cant handle marlin it to complicated for it.
The error are not real.
Look at the terminal window, not the problem window

**Comment by ellensp** [comment]
The provided example config above is the stock marlin configs. It if for a ramps controller and does does not have any displays enabled

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
Use these configs https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Creality/Ender-3%20Pro/BigTreeTech%20SKR%20Mini%20E3%201.2

**Comment by kaidegit** [comment]
hi，i discover this problem about include path too.
The pr #23058 in bugfix branch may have fixed it.
