### ISSUE TITLE
REPRAP_DISCOUNT_SMART_CONTROLLER

### ISSUE THREAD

**Issue by alfskaar** [MarlinFirmware/Marlin#23032]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Not working, Marlin 2.0.9.2
REPRAP_DISCOUNT_SMART_CONTROLLER

Working
https://cdn.prusa3d.com/downloads/firmware/prusa3d_fw_3_2_3_MK2_MK2MMU.zip
1_75mm_MK2-RAMBo13a-E3Dv6full.hex

Same as this case
https://github.com/MarlinFirmware/Marlin/issues/12937

Configuration.h
#define MOTHERBOARD BOARD_MINIRAMBO
#define REPRAP_DISCOUNT_SMART_CONTROLLER

### Expected behavior

Display to work

### Actual behavior

NO display

### Steps to Reproduce

Configuration.h
#define MOTHERBOARD BOARD_MINIRAMBO
#define REPRAP_DISCOUNT_SMART_CONTROLLER

### Version of Marlin Firmware

Marlin 2.0.9.2

### Printer model

BOARD_MINIRAMBO

### Electronics

BOARD_MINIRAMBO

### Add-ons

REPRAP_DISCOUNT_SMART_CONTROLLER

**Comment by alfskaar** [comment]
https://ultimachine.com/products/lcd-smart-controller-kit-from-reprapdiscount?variant=18570852743
https://reprap.org/wiki/RepRapDiscount_Smart_Controller
https://ultimachine.com/collections/electronics/products/mini-rambo-1-3

**Comment by ellensp** [comment]
How did you build this? Using the arduino IDE?
If so did you install the required boards file. As this add extra pins that the LCD uses
https://reprap.org/wiki/Rambo_firmware#Arduino_1.6.4.2B_Board_Manager_Plugin
Board needs to be set to RAMBO, not arduino MEGA

**Comment by alfskaar** [comment]
Arduino_1.8.16.app on MAC
ok will try your suggestions.
This is clearly wrong...
https://marlinfw.org/docs/basics/install_arduino.html

This is one of the main problems with this hard to find the correct information.
The display works now. :-) you can close it
You shod add this link to the Marlin main page. :-)
https://reprap.org/wiki/Rambo_firmware#Arduino_1.6.4.2B_Board_Manager_Plugin

**Comment by thisiskeithb** [comment]
You will have a much easier time if you setup [VSCode + PlatformIO](https://marlinfw.org/docs/basics/install_platformio.html) since it will handle all libraries for you _and_ compile much faster.

**Comment by alfskaar** [comment]
OK that where next on my list. But since I have used Arduino before it is natural to go with that first. Thanks for the suggestion. :-)

**Comment by ellensp** [comment]
Its on the documentation page for that controller https://reprap.org/wiki/MiniRambo#Firmware_Requirements
Its not actually a marlin issue. 
Also VSCode/Platformio  forces you to use correct RAMBO build env.
There is no way to force this in the primitive Arduino IDE

**Comment by alfskaar** [comment]
Actually I have be on that page but I missed it sorry. And thanks for the help all. :-)
Agree it is not a Marlin issue. But it still worked just not the display that made my problem harder to find.
https://reprap.org/wiki/MiniRambo#Firmware_Requirements
https://reprap.org/wiki/Rambo_firmware#Arduino_1.6.4.2B_Board_Manager_Plugin
https://reprap.org/wiki/RepRapDiscount_Smart_Controller
https://ultimachine.com/collections/electronics/products/mini-rambo-1-3
https://ultimachine.com/products/lcd-smart-controller-kit-from-reprapdiscount?variant=18570852743
