### ISSUE TITLE
[BUG] Print pauses after printing purge line and moving to print start point (2.0.9.2)

### ISSUE THREAD

**Issue by Battou2501** [MarlinFirmware/Marlin#23037]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

After update from 2.0.6.1 to 2.0.9.2 every print sliced in IdeaMaker and started from SD pauses after printing purge line and moving to print start position. I then need to press Resume for print to continue.

Here is a part of my gcode. it pauses after G0 commands^

```gcode
;Sliced by ideaMaker 4.2.1.5321, 2021-10-28 18:49:56 UTC+0300
;Dimension: 300.000 300.000 350.000 0.400
;Plate Shape: 0
;Origin Center: 0
;Extruder Offset #1: 25.000 0.000
;Filament Diameter #1: 1.750
;Filament Diameter #2: 1.750
;Filament Compensation #1: 92.00
;Filament Compensation #2: 90.00
;Filament Density #1: 1270.00
;Filament Density #2: 1240.00
;Bounding Box: 135.440 164.559 135.441 164.560 0.000 20.000
;Model Gap: 0.000
M221 T0 S92.00
M140 S80.00
M190 S80.00
M104 T0 S230.00
M109 T0 S230.00
T0
G28 ; home all axes
G1 X30 Y30 Z0.3 F1000
G92 E0
G1 X30 Y130 E15 F500
G92 E0
G1 E-0.3 F6000
G1 Y200 F4000
G92 E0
M107
M1001
;TOTAL_NUM: 1
;PRINTING_TIME: 0
;REMAINING_TIME: 2157
;LAYER:0
;Z:0.200
;HEIGHT:0.200
;PRINTING: NON-OBJECT
;PRINTING_ID: -1
G1 F1500 E-0.5000
G0 F13200 X136.464 Y136.683
G0 F960 Z0.200
G0 F13200 X136.675 Y136.895
;TYPE:SKIRT
;WIDTH:0.480
G1 F1500 E0.0000
G1 F900 X136.953 Y136.618 E0.0157
G1 X137.070 Y136.518 E0.0218
G1 X137.356 Y136.299 E0.0362
G1 X137.419 Y136.256 E0.0392
G1 X137.582 Y136.151 E0.0470
G1 X137.868 Y135.985 E0.0602
```

### Expected behavior

Print without pauses

### Actual behavior

Pauses after printing purge line and moving to start position

### Version of Marlin Firmware

2.0.9.2

### Printer model

Custom CoreXY

### Electronics

SKR 1.4 Turbo, TMC2208 on all steppers

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

IdeaMaker

### Host Software

SD Card (headless)

**Comment by thisiskeithb** [comment]
> M1001

For some reason, IdeaMaker inserts `M1001` which is an internal Marlin command for SD print completion and should not be there.

Remove it from your start g-code. I’d also suggest filing a bug report with them since it is not related to Marlin.

**Comment by Battou2501** [comment]
> > M1001
> 
> For some reason, IdeaMaker inserts `M1001` which is for SD print completion and should not be there.
> 
> Remove it from your start g-code. I’d also suggest filing a bug report with them since it is not related to Marlin.

Oh. Sorry! Never encountered this command before and also got confused because the travel commands G0 after M1001 are being executed. Thanks!

**Comment by thisiskeithb** [comment]
Raise3D printers use `M1001` for power resume, so that's why their slicer inserts it: https://forum.raise3d.com/viewtopic.php?t=4610#p21314

Edit: I just sent a note to IdeaMaker to see they could leave out the command for third party printer profiles to prevent this from coming up again.
