### ISSUE TITLE
[FR] AnyCubic 4MAX Pro 2.0

### ISSUE THREAD

**Issue by sztanga** [MarlinFirmware/Marlin#23036]
### Is your feature request related to a problem? Please describe.

I bought AnyCubic 4MAX Pro 2.0 printer and it seems to be running on Marlin, however I can't find any configs for it anywhere. Is it possible to 

### Are you looking for hardware support?

Anycubic 4MAX Pro 2.0

### Describe the feature you want

I'd love to get config files for AnyCubic 4MAX Pro 2.0 as I can't find anything updated anywhere :(

**Comment by ellensp** [comment]
Please create in Configurations repository https://github.com/MarlinFirmware/Configurations
