### ISSUE TITLE
GT2560 rev A+ and Fysetc 12864 Mini 2.1 display

### ISSUE THREAD

**Issue by donytech** [MarlinFirmware/Marlin#23045]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

by enabling:
#define FYSETC_MINI_12864_2_1

the display doesn't work.
neither the neopixel led.

### Version of Marlin Firmware

2.0.9.2

### Printer model

Geeetech i3 Pro B

### Electronics

GT2560 rev A+

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Additional information & file uploads

The display works with this test code

[Fysetc_Mini_12864_Test.zip](https://github.com/MarlinFirmware/Marlin/files/7447418/Fysetc_Mini_12864_Test.zip)

**Comment by ellensp** [comment]
I can not replicate this issue

I don't have a GT2560 rev A+, but its just a mega2560 really
I wired up the Fysetc 12864 Mini 2.1 display to the same pins as the GT2560 uses on my mega

```
M43 output (with non LCd related pins removed) 
> PIN:  16   Port: H1        LCD_RESET_PIN                          Output = 1 
> PIN:  17   Port: H0        DOGLCD_CS                              Output = 1  
> PIN:  18   Port: D3        BEEPER_PIN                             Output = 0  
> PIN:  19   Port: D2        BTN_ENC                                Input  = 1  
> PIN:  20   Port: D1        DOGLCD_A0                              Output = 1  
> PIN:  21   Port: D0        NEOPIXEL_PIN                           Output = 0  
> PIN:  38   Port: D7        SD_DETECT_PIN                          Input  = 1  
> PIN:  40   Port: G1        BTN_EN2                                Input  = 1  
> PIN:  42   Port: L7        BTN_EN1                                Input  = 1  
> PIN:  51   Port: B2        AVR_MOSI_PIN                           Output = 1  
> .                          DOGLCD_MOSI                            Output = 1  
> PIN:  52   Port: B1        AVR_SCK_PIN                            Output = 0  
> .                          DOGLCD_SCK                             Output = 0  
> PIN:  53   Port: B0        AVR_SS_PIN                             Output = 1  
> .                          SDSS                                   Output = 1  

```
Important LCD_RESET_PIN doesn't show up in current code as it is missing in PINS_DEBUGGING, I have added it in this PR https://github.com/MarlinFirmware/Marlin/pull/23051 
![IMG_20211101_001610](https://user-images.githubusercontent.com/530024/139580906-49c8fe0d-aaa8-4e12-bd78-3e3ef559ca6e.jpg)


Starting with stock Marlin config I only updated these settings
#define MOTHERBOARD BOARD_GT2560_REV_A_PLUS
#define SDSUPPORT
#define FYSETC_MINI_12864_2_1    // Type A/B. NeoPixel RGB Backlight
#define NEOPIXEL_STARTUP_TEST  // Cycle through colors at startup
#define PINS_DEBUGGING

Which worked fine under Marlin (bugfix 2.0.x as of today)

![IMG_20211101_001654](https://user-images.githubusercontent.com/530024/139580979-1eb69b7c-e184-4132-b12b-f87ddaee5f77.jpg)

I then used the test program you attached without making any hardware changes

It worked fine also.

![IMG_20211101_001938](https://user-images.githubusercontent.com/530024/139581018-5fe03350-5d91-47ad-9087-26a95de6a07d.jpg)

**Comment by ellensp** [comment]
And yes the Neopixeles works as expecting doing the NEOPIXEL_STARTUP_TEST in marlin on startup
The encoder and and even the sd card works as expected,

**Comment by ellensp** [comment]
Oh and I wrote that Fysetc_Mini_12864_Test, a long time ago... https://github.com/ellensp/FYSETC-Mini-12864-tester

**Comment by donytech** [comment]
I found the issue:
the default lcd contrast was 0 and not visible.
it was visible after command M250 c255 by pronterface.

Thank you friend!
