### ISSUE TITLE
[BUG] LPC176X Neopixel with MKS Mini 12864 display

### ISSUE THREAD

**Issue by Stliin** [MarlinFirmware/Marlin#23043]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Neopixels efter 4'th pixel is random rainbow color.

This is due to MKS_MINI_12864 display attached
After activated software SPI the neopixels acts in a random differend colors. Like a rainbow.
If i turn software SPI off it works as intended

### Expected behavior

Same selected color all over the strip
Works with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

### Actual behavior

Rainbow pattern in Neopixels after the 8'th ish pixel and only light up 80% ish the end of strip is dark.

### Steps to Reproduce

Connect MKS_MINI_12864
Turn on Neopixel
Acitvate software SPI

### Version of Marlin Firmware

Bugfix-2.0.x

### Printer model

Creality Ender 3

### Electronics

BTT SKR 1.4 Turbo

### Add-ons

Display MKS_MINI_12864

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7446522/Configuration.zip)

**Comment by ellensp** [comment]
@p3p could you take a look...  I expect its cpu overload...

**Comment by Stliin** [comment]
I have a second printer, CR10S.

Tested the same build and it works with Neopixel as is should.
The difference is the display attached.


CR10S has REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER, works as intended.

Ender 3 has MKS_MINI_12864, and the leds are all rainbow.


Updated the issue with information.
And hope that will aid to the troubleshooting.


[CR10S Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7447258/CR10S.Configuration.zip)

**Comment by p3p** [comment]
@ellensp I would be surprised if its overloaded, it will be the interaction between multiple timing critical peripherals, Neopixels being the least important device in a printer but requiring the very high priority signal generation (disabled interrupts) to maintain the ns timing requirement.

**Comment by thisiskeithb** [comment]
Adding a resistor & capacitor is recommended on BTT boards (probably others as well) when using NeoPixels.

I use [this little NeoPixel board](https://www.printedsolid.com/products/skr-neopixel-breakout-board) to clean things up.

Edit: That breakout board is [open source](https://github.com/codiac2600/Neopixel-Breakout-Board) so you can have one made if you're not in the US and can't DIY a solution.

**Comment by descipher** [comment]
Have you followed this:
https://learn.adafruit.com/adafruit-neopixel-uberguide/best-practices
