### ISSUE TITLE
#define Z_MULTI_ENDSTOPS leads to error: 'Z2_MIN' was not declared in this scope

### ISSUE THREAD

**Issue by nen777w** [MarlinFirmware/Marlin#23041]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I want to enable multi z-stop on fresh firmware, branch (2.0.x)

### Bug Timeline

I don't know.

### Expected behavior

Success compilation.

### Actual behavior

error: 'Z2_MIN' was not declared in this scope

### Steps to Reproduce

[platformio.ini]
default_envs = LPC1769
[Configuration.h]
#define MOTHERBOARD BOARD_BTT_SKR_V1_4_TURBO
[Configuration_adv.h]
#define NUM_Z_STEPPER_DRIVERS 2
#define Z_MULTI_ENDSTOPS

Build.

### Version of Marlin Firmware

2.0.9.2

### Electronics

SKR 1.4 Turbo

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
```#define Z2_USE_ENDSTOP _XMAX_```  is invalid. This board does NOT have a _XMAX_
It should be 
```#define Z2_USE_ENDSTOP _E0DIAG_``` If you are using the plug to the right of the  x-stop

**Comment by nen777w** [comment]
> `#define Z2_USE_ENDSTOP _XMAX_` is invalid. This board does NOT have a _XMAX_
> It should be
> `#define Z2_USE_ENDSTOP _E0DIAG_` If you are using the plug to the right of the x-stop

Yes. I know. I use __E1DIAG__, but in this case, it does not matter. The compilation error exists.
On an older firmware version, this problem does not exist. Unfortunately, I pulled the sources and do not recall the hash of the commit without this problem.

**Comment by ellensp** [comment]
The error does not occur when you use ```#define Z2_USE_ENDSTOP _E0DIAG_``` on current bugfix

**Comment by nen777w** [comment]
> The error does not occur when you use `#define Z2_USE_ENDSTOP _E0DIAG_` on current bugfix

Hm.... You are right!
I stashed all my changes and retry again, and at this time it compiled successfully...
Hmm... probably I make a mistake in another place...
I should review my changes.

Anyway, Thank you!

**Comment by nen777w** [comment]
I found it!
By the some reason I uncommented the 
[Configuration.h]
//#define USE_YMAX_PLUG
//#define USE_ZMAX_PLUG

Thank you again!
