### ISSUE TITLE
[FR] Marlin-centric Database of Hardware Details

### ISSUE THREAD

**Issue by thisiskeithb** [MarlinFirmware/Marlin#23077]
### Describe the feature you want

>  in general, so much of the data we need within reach is in scattered datasheets, and it would be nice to have something akin to a database – or a literal MySQL db – with only the Marlin-centric data collated and cross-referenced … formatted in pretty rows and columns.

_Originally posted by @thinkyhead in https://github.com/MarlinFirmware/Marlin/issues/23062#issuecomment-961235548_

### Additional context

This would give developers (and maintainers!) an easy/one-stop-shop for Marlin-specific hardware data enabling easier decisions on feature & hardware additions, bug fixes, refactoring, etc.

I started on something like this for LCDs and TFTs while trying to unwrap the nested if()s in pins files, but stopped when we moved to `EXP*_` naming.

**Comment by zcohen-nerd** [comment]
Hi, so I have pretty much no coding ability but am trying to learn. More importantly I've been wanting something like this for a while and am more than happy to contribute. If this happens and there is some sort of contribution method that can be typed into or uses some sort of form, I'm more than happy to find and enter things whenever I have free time.
