### ISSUE TITLE
[BUG] Update to Marlin 2.0.9.2 fw always fails on Biqu SE-BX

### ISSUE THREAD

**Issue by digant73** [MarlinFirmware/Marlin#23070]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I know the support to extui is no more provided since the first (and only one working) 2.0.6.1 version provided here https://github.com/bigtreetech/BIQU-BX (last update by thisiskeithb) but after that 2.0.6.1 version I was never able to install any other Marlin fw version on Biqu SE-BX.
Basically after 100% of fw is loaded, the printer resets. After rebooting, it is displayed 100% is updated and after few seconds the printer resets again and so on indefinitely.
Attached my last fw (based on official 2.0.9.2) configuration files (all the changes I made are marked with comment "DIGA-TECH") and the changes are basically the same applied on 2.0.6.1 that was working.
Attached also a video of the problem.

### Expected behavior

fw update properly installed and printer usable

### Actual behavior

the printer continuosly reboots trying to install the fw update

### Version of Marlin Firmware

official 2.0.9.2

### Printer model

Biqu SE-BX

### Additional information & file uploads

Link to Marlin 2.0.9.2 configuration:
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7469688/Marlin.zip)

Link to video:
https://www.youtube.com/watch?v=ng5jp30W-0s

**Comment by thisiskeithb** [comment]
> last update by thisiskeithb

To clarify, my PRs were to add STLs of the 4040 drawer & parts fan duct, not the firmware.

I'll get my BX updated to the latest bugfix and see if I can reproduce the issue. In the meantime, have you tried the configs from https://github.com/MarlinFirmware/Configurations/pull/604?

**Comment by bigtreetech** [comment]
https://github.com/stm32duino/Arduino_Core_STM32/blob/main/libraries/SoftwareSerial/src/SoftwareSerial.cpp#L186
Hello, Please delete or comment out here.
![image](https://user-images.githubusercontent.com/38851044/140253850-9ced9e32-3ca6-4e72-a92c-9df0dda3e2d1.png)

There is no time to dig deep into the cause now. You can fix it temporarily like this before finding the root cause

**Comment by digant73** [comment]
@thisiskeithb yes, I also used the looxonline's last branch with the same result of my configuration. I will try also your configuration files (they sligtly differ from looxonline)
@bigtreetech hmm, I see that this piece of code was present and commented out in Marlin 2.0.6.1 source code (Marlin/src/HAL/STM32/SoftwareSerial.cpp) while the file SoftwareSerial.cpp is no more present at all on current Marlin fw (e.g. 2.0.9.2). As you said it is present on the Arduino framework. I will comment it out in the framework and verify if it works

**Comment by thisiskeithb** [comment]
If Luke's firmware is also failing on your machine, then there is likely something else wrong since that is also Marlin `2.0.6` (same as what was shipped) and many users are running it without issues.

**Comment by digant73** [comment]
maybe the problem is in the Arduino framework as reported by bigtreetech. In the 2.0.6.1 (working on my printer) the SoftwareSerial.cpp is provided on Marlin fw source code while now that file is provided by Arduino framework (and the setTx function is not commented out). I will apply the change reported by Alan this night and let you know

**Comment by digant73** [comment]
@bigtreetech with your suggestion it worked. I also verified that setting SERIAL_PORT different than 1 or 4 the fw doesn't boot (the screen remains black but there is no permanent reboot as before). SERIAL_PORT 1 is the one (as it was in 2.0.6.1) I used to connect the TFT35 V3 at 250000.
As far as I see the piece of code responsible for the problem is on the Arduino framework since some time now so I was expecting the same behavior on other printers.
Anyway, thanks to both for the support. Closing the bug report.

**Comment by digant73** [comment]
Bug temporary fixed!

**Comment by thisiskeithb** [comment]
> I used to connect the TFT35 V3 at 250000.

Which printer do you have? The BX comes with a TFT70 directly connected the board/MCU with a 40 pin cable and it doesn't run it's own firmware.

**Comment by digant73** [comment]
yes, sure it has the TFT70 driven by mainboard (now with only Marlin mode GUI due no extui is currently available since 2.0.6.1). But I also connected on the mainboard's TFT connector a second TFT (BTT TFT35 V3) for testing purposes (on TFT fw).
For this extra TFT, serial port 1 is used (as it was set by default on 2.0.6.1) at 250000 (I never had any issue in the past with that rate).

![IMG_20211106_105428](https://user-images.githubusercontent.com/64427768/140605651-fb0bd915-126c-4e42-85ce-54adc686419a.jpg)

**Comment by thisiskeithb** [comment]
You can modify `stm32h7.ini` and swap out: https://github.com/MarlinFirmware/Marlin/blob/36b2650f65e036ce1b02da568364230201a22b80/ini/stm32h7.ini#L28

with: 
```ini
platform_packages  = framework-arduinoststm32@https://github.com/thisiskeithb/Arduino_Core_STM32/archive/refs/heads/biqu-bx-workaround.zip
```

This is based on rhapsodyv's STM32/USB fixes + the workaround mentioned by BigTreeTech above.

**Comment by thisiskeithb** [comment]
Reopening so this can be tracked. #23131 changes the platform packages URL for the BX until BigTreeTech can look at it further.

**Comment by thisiskeithb** [comment]
#23131 was merged.

**Comment by rhapsodyv** [comment]
This is the right fix: https://github.com/stm32duino/Arduino_Core_STM32/commit/f4c200f9d7d1258a15e1a2c56dbdd9d370e1b5b9

`active_listener` sometime is null and it's missing a null check, fixed in that commit.

**Comment by thisiskeithb** [comment]
> This is the right fix: https://github.com/stm32duino/Arduino_Core_STM32/commit/f4c200f9d7d1258a15e1a2c56dbdd9d370e1b5b9

Thanks for finding the proper fix!

I've updated my Arduino Core STM32 fork/BX workaround branch to backport this change/properly fix this bug: https://github.com/thisiskeithb/Arduino_Core_STM32/commit/8b3522051ac21809c4e76146bbbc546970271039

**Comment by rhapsodyv** [comment]
Thanks!
