### ISSUE TITLE
[BUG] Sense check with Driver Types [QUESTION]

### ISSUE THREAD

**Issue by NeilBuc007** [MarlinFirmware/Marlin#23081]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello. I have a question which I did try and put into the discussion part of the site too. What do we think happens when this typo is in place in the configuration.h:
```cpp
#define X_DRIVER_TYPE TMC2209
#define Y_DRIVER_TYPE TMC2209
#define Z_DRIVER_TYPE TMC2209
//#define X2_DRIVER_TYPE A4988
//#define Y2_DRIVER_TYPE A4988
//#define Z2_DRIVER_TYPE A4988
//#define Z3_DRIVER_TYPE A4988
//#define Z4_DRIVER_TYPE A4988
#define E0_DRIVER_TYPE TTMC2209
```
I have been tracking down an problem? since upgrading from 2.0.6 on Ender 3 Pro with SKR 1.4 Turbo and 2209's. The print quality is rubbish, and the prints are weak. Turns out the old and great prints are printed with FW that has a blooming typo for the Extruder driver.
How it even worked or compiled I dunno.

So today I am going to do some test with E0 and 2.0.9 and stealthchop settings as that's how I spotted it when I did a M569 and notice no values for E0 with the old but working FW.

Been at this all week and the single wall cube test with the 2.0.6 and typo is great and strong. Yet the 2.0.9 with a 3 line wall is flimsy and weak and has these weird wavy lines on two sides like its got vibrations happening.

I think I have read about the whole site so the is a last resort  as I have tried all sorts and everything in the other threads so far made no difference.

Cheers

Neil

### Expected behavior

Smooth walls and 100% 50mm/s

### Actual behavior

Wavy , vibration type artifacts on the walls and weak prints.

### Steps to Reproduce

1. Update to any new firmware test print a hollow cube gcode
2. Downgrade to original firmware with the TYPO in the Extruder driver and print same hollow cube gcode.
3. Inspect 1 and 2
4. Scratch head why 2 is perfect and 1 is terrible.

### Version of Marlin Firmware

2.0.9.2

### Printer model

Ender 3 Pro

### Electronics

SKR 1.4 Turbo

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
