### ISSUE TITLE
[BUG] MMU1 Manual Extruder Move 

### ISSUE THREAD

**Issue by AmadoSumbi** [MarlinFirmware/Marlin#23087]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I’m experimenting this MMU1 using a 16-Channel Analog Multiplexer/Demultiplexer “CD74HCT4067” to control the enable pin of stepper driver (i.e. A4988) for extruder(s). But I have couple of issues:
1)	The Manual Move for extruders on the menu items only Extruder 1 will move even you select EE1, EE2, EE3 and so on, still the Extruder 1 will move. But when I will use the Pronterface Host, it will work each Extruders.
2)	I also noticed that Extruder 1 and Extruder 3 have same direction of rotation, Extruder 2 and Extruder 4 have same direction of rotation, but in reverse direction to Extruder 1 and Extruder 3.

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.0.x (Nov  6 2021 20:26:25) 

### Your Slicer

Prusa Slicer

### Host Software

Pronterface

### Additional information & file uploads

[Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/7490995/Marlin-bugfix-2.0.x.zip)

**Comment by ellensp** [comment]
the real MMU1 does not switch enable pins It  switches the stepper driver coils in and out
Ie there is no additional E stepper driver step/direction/enable pins defined  
There is just 1 E stepper driver and a interface that swaps what stepper motor is actually connected 

What your playing with is not compatible with a MMU1
