### ISSUE TITLE
[FR] Park X or Y movement order

### ISSUE THREAD

**Issue by HoverClub** [MarlinFirmware/Marlin#23106]
### Is your feature request related to a problem? Please describe.

No

### Are you looking for hardware support?

No

### Describe the feature you want

Would be nice to have an option to specify X or Y park movement order (i.e. X first then Y, or Y first then X) as is done for Z.  On some machines the park position may be outside the bed but adjacent to some fixed hardware - moving one axis at a time would avoid collisions caused by using a direct path.

**Comment by thisiskeithb** [comment]
Added in https://github.com/MarlinFirmware/Marlin/pull/23158
