### ISSUE TITLE
3d printer keeps resetting itself when i try to print 

### ISSUE THREAD

**Issue by peguri47** [MarlinFirmware/Marlin#23115]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

i few days ago i use my 3d printer for around an hour or so, i turned off and i went to bed... a few days later i tried to used again
and it stars the abl (does 2 points) and then moves a little ( like trying to go to the next one) and stops, the spitts out a msg in the tft "V83 Hardcore stored settings retrived (609 bytes; crc 9969) 

### Bug Timeline

as i sayd the machine was off of a few days, and then this appear 

### Expected behavior

the printer moves, around the probing points and then starts printing

### Actual behavior

does 2 points and stops trying to go to the next

### Steps to Reproduce

to be honest, idk 

### Version of Marlin Firmware

2.0.9

### Printer model

farily modified anet e10 

### Electronics

SKR V1.3 

### Add-ons

TFT35V2.0

### Bed Leveling

ABL Linear grid

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Additional information & file uploads

![photo4925114903736461980](https://user-images.githubusercontent.com/94144989/141375155-94b0510b-a640-4084-ad69-5218be11cc50.jpg

https://user-images.githubusercontent.com/94144989/141375159-666308ff-4b07-4691-adcc-6bf5867069be.mp4

)
as i said no modifications had been mad before or after this issue, i already tried the newest marlin version, no changes
i tried reflashing the same one and to the tft, no changes
i tried M502, M500 and then M501, didnt change anything, im about to trash the hole board, so i hope that u guys have any ideas

**Comment by futuretech208** [comment]
I had similar issue for 2 months on my printer. The solution was loose connections and mainly the faulty cheap chinese thermistor. I replaced the thermistor with 300 deg C rating and things are working smooth now. The glass thermistor with the PTFE tube was causing the problem. Also, change PTFE to fibreglass insulation.

**Comment by Tannoo** [comment]
Yes, this is a wiring issue. The resetting is likely due to something shorting out. Check everything... not just thermistor wiring.

**Comment by peguri47** [comment]
> Yes, this is a wiring issue. The resetting is likely due to something shorting out. Check everything... not just thermistor wiring.

i don't believe that it's that, now it does that, but never actually arrives at abl, like does the auto home, then go z safe homing, and after that nothing moves, the temp doesn't go up... someone told me that the board it's done 
but I'm gonna check

**Comment by Tannoo** [comment]
Well, I am quite certain it is not a Marlin issue.

**Comment by peguri47** [comment]
i agree, maybe it's a hardware issue, because i move up to the same point, check everything, and everything works

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
