### ISSUE TITLE
[BUG] (SKR E3 Turbo - DRIVER TMC2209)

### ISSUE THREAD

**Issue by ATMOSFERACERO** [MarlinFirmware/Marlin#23118]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have errors for SKR E3 Turbo:
Se han detectado errores de #include. Actualice el valor de includePath. El subrayado ondulado está deshabilitado para esta unidad de traducción (D:\AMA_Impresora 3D\01. Impresora 3D_Ender 3\Software\01_Firmware_Marlin\01_Marlin-bugfix-2.0.x\Marlin\src\MarlinCore.cpp).

when I change in "Configuration.h" the Stepper Drivers (#define X_DRIVER_TYPE  TMC2209), if you use "TMC2209_STANDALONE" opcion don't have error, may be the problem is the code don't have the folder with the suport to TMC2209.

### Expected behavior

Easy Config.

### Actual behavior

Errors in the code.

### Steps to Reproduce

Configuration.h
#define X_DRIVER_TYPE  TMC2209
#define Y_DRIVER_TYPE  TMC2209_STANDALONE

platformio.ini
default_envs = LPC1769 

### Version of Marlin Firmware

bugfix-2.0.x -  STRING_DISTRIBUTION_DATE "2021-11-11" - DEFAULT_MACHINE_UUID "cede2a2f-41a2-4748-9b12-c55c62f367ff"

### Printer model

ENDER 3 PRO

### Electronics

Bigtreetech SKR E3 Turbo

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ATMOSFERACERO** [comment]
Thanks, I have look the problem, before change the configuration in Marlin, is necessary compilation Marlin to have the firmware update, then the errores disappear and you can continue making modifications.
