### ISSUE TITLE
Unable to change traveling distance of Z-Axis.

### ISSUE THREAD

**Issue by kanitmann** [MarlinFirmware/Marlin#23128]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

## Case 

Currently, my printer's z-axis is moving 34mm for every 10mm I try to move. I have tried almost all solutions available on Github and Stackoverflow, and still, none of them are able to solve this issue.

### Expected behavior

Expecting Z-axis to move 10mm when given input to do so manually (or via print).

### Actual behavior

Moving 34 mm instead.

### Version of Marlin Firmware

2.0.x Bugfix

### Printer model

Custom

### Electronics

BigtreeSKR2

### Your Slicer

Cura

### Additional information & file uploads

`Configuration.h` :  [Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/7534747/Configuration.txt)
`Configuration_adv.h` : [Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/7534750/Configuration_adv.txt)

Kindly, let me know if any more information is needed, and forgive me for any mistakes.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
