### ISSUE TITLE
Movement occurring error

### ISSUE THREAD

**Issue by mhkjoon** [MarlinFirmware/Marlin#23132]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

hi
I tested the file with two softwares and the result was the same.(cura and Simplify3D)
The shape moves forward after a few layers and resumes printing. I put the photos for you.
Thank

### Version of Marlin Firmware

02000902

### Electronics

Arduino mega ramp1.6

### Your Slicer

Simplify3D

### Additional information & file uploads

![2021-11-15 at 11 32 43](https://user-images.githubusercontent.com/78957741/141748517-cd32a81b-d9ad-4f8f-923e-6966c912553f.jpeg)

**Comment by ellensp** [comment]
This is called  layer shift. This is setting related.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by mhkjoon** [comment]
thx bro for your help iam check it but cant find how to solve.:( . do you know how can i solve it?

**Comment by ellensp** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y
