### ISSUE TITLE
Tevo Tornado (MKS SGEN-L V1.0) unresponsive after firmware flash.

### ISSUE THREAD

**Issue by smollest** [MarlinFirmware/Marlin#23143]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I've been trying to add a Geeetech 3D Touch to my Tevo Tornado.
I flashed the printer with bugfix-2.0.x and everything went unresponsive, meaning I am no longer able to control the printer via the control box. Instructions regarding the tornado mostly cover **MKS GEN-L**, but not **MKS SGEN-L** and there isn't an example for it in the firmware. My current configuration is using _#define CONFIG_EXAMPLES_DIR "Tevo/Tornado/V2 (MKS GEN-L)"_ and _#define MOTHERBOARD BOARD_MKS_SGEN_L._ (contradictory?)

Here's my current firmware: [Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/7547111/Marlin-bugfix-2.0.x.zip)

I'm a complete newbie in configuring the firmware and have no idea how to proceed or what the true reason for my issue is.
My guess is that there some essential settings with the MKS GEN-L that are just wrong for the printer with an MKS SGEN-L board.

How would I go about fixing this issue?

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Tevo Tornado

### Electronics

MKS SGEN-L V1.0

### Add-ons

Geeetech 3D Touch

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
