### ISSUE TITLE
[BUG] Robin nano v1.3 compilation error timers_in_use

### ISSUE THREAD

**Issue by Disttrack** [MarlinFirmware/Marlin#23157]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When I activate UART mode in TMC2208 drivers on Robin Nano V1.3 board (STM32F407VET6), I set the RX and TX pins I get an error like this:
Marlin\src\HAL\STM32\timers.cpp:322:40: error: static assertion failed: One or more timer conflict detected. Examine "timers_in_use" to help identify conflict.
  322 | static_assert(verify_no_timer_conflicts(), "One or more timer conflict detected. Examine \"timers_in_use\" to help identify conflict.");
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~^~
*** [.pio\build\mks_robin_nano_v1_3_f4\src\src\HAL\STM32\timers.cpp.o] Error 1

I've tried some of the solutions for other boards but they won't work. 

### Expected behavior

Compile sucesfully

### Steps to Reproduce

Marlin\src\HAL\STM32\timers.cpp:322:40: error: static assertion failed: One or more timer conflict detected. Examine "timers_in_use" to help identify conflict.
  322 | static_assert(verify_no_timer_conflicts(), "One or more timer conflict detected. Examine \"timers_in_use\" to help identify conflict.");
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~^~
*** [.pio\build\mks_robin_nano_v1_3_f4\src\src\HAL\STM32\timers.cpp.o] Error 1

### Version of Marlin Firmware

2.0.9.2

### Printer model

Kingroon KP3S

### Electronics

Kingroon v1.2 STM32F407VET6

### Additional information & file uploads

[Marlin-config.zip](https://github.com/MarlinFirmware/Marlin/files/7569769/Marlin-config.zip)

**Comment by cscomputers** [comment]
Hello! It solve for me Commenting the line or add an condition below for solve this on Marlin\src\pins\stm32f1\pins_MKS_ROBIN_NANO_common.h:

// #define TEMP_TIMER                             5

OR add an condition....

![image](https://user-images.githubusercontent.com/12433025/142709318-e1d1c666-0a7d-4cac-abd0-4bd091a03357.png)

And before this, works great!

![image](https://user-images.githubusercontent.com/12433025/142709437-a8bba28f-9ace-475b-93d0-67e998991f9c.png)

**Comment by Disttrack** [comment]
> Hello! It solve for me Commenting the line or add an condition below for solve this on Marlin\src\pins\stm32f1\pins_MKS_ROBIN_NANO_common.h:
> 
> // #define TEMP_TIMER 5
> 
> OR add an condition....
> 
> ![image](https://user-images.githubusercontent.com/12433025/142709318-e1d1c666-0a7d-4cac-abd0-4bd091a03357.png)
> 
> And before this, works great!
> 
> ![image](https://user-images.githubusercontent.com/12433025/142709437-a8bba28f-9ace-475b-93d0-67e998991f9c.png)

Thank you! I have compiled commenting on the line you have indicated!

**Comment by cscomputers** [comment]
Oh great! I’m happy to help.
