### ISSUE TITLE
Changing temperatures in the menu bypasses start_watching_heater()

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#2315]
When changing temperatures in the lcd_tune_menu() and lcd_control_temperature_menu() target_temperature[] is manipulated directly, not calling start_watching_heater().
Its the same for the bed.
This is already handled correct when setting the prestored material-temperatures.

A callback function is needed.

**Comment by thinkyhead** [comment]
Hopefully MarlinFirmware/MarlinDev#241 will fix this longstanding issue. Please close this bug if the patch takes care of the problem.

**Comment by AnHardt** [comment]
Fixed by https://github.com/MarlinFirmware/MarlinDev/pull/241 and #2704
