### ISSUE TITLE
[BUG] say busy after pause (dgus reload from desuu firmware ) with skr14.T

### ISSUE THREAD

**Issue by labotecno** [MarlinFirmware/Marlin#23155]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

i have problem with pause with dgus screen from cr10 s pro , and i have skr14T , seem to have the same bug like this [https://github.com/Desuuuu/Marlin/issues/25](url)
when i try to pause i cant resume or printer dont make nothing . 
[https://github.com/Desuuuu/DGUS-reloaded](url)
and [https://github.com/Desuuuu/Marlin](url)

### Bug Timeline

> 14:47:21.961 : //action:prompt_end
14:47:21.961 : //action:prompt_begin FilamentRunout T0
14:47:21.961 : //action:prompt_show
14:47:21.961 : //action:paused filament_runout 0
14:47:24.752 : //action:paused
14:47:31.325 : X:20.00 Y:290.00 Z:20.00 E:-1.71 Count X:1600 Y:23200 Z:8000
14:48:16.360 : echo:Insert filament and send M108
14:48:16.360 : //action:prompt_end
14:48:16.360 : //action:prompt_begin Nozzle Parked
14:48:16.361 : //action:prompt_button Continue
14:48:16.361 : //action:prompt_show
14:48:35.911 : //action:prompt_end
14:48:35.911 : //action:prompt_begin Paused
14:48:35.911 : //action:prompt_button PurgeMore
14:48:35.911 : //action:prompt_button DisableRunout
14:48:35.911 : //action:prompt_show

### Expected behavior

resume after pause 

### Version of Marlin Firmware

2.0.9.1

### Printer model

cr10spro

### Electronics

skr1.4T

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

**Comment by ellensp** [comment]
We cannot support 3rd party forks of Marlin
This instant someone makes a fork of marlin they are responsible for the support of that fork.

**Comment by labotecno** [comment]
ok bt marlin have #define DGUS_LCD_UI_RELOADED ? or not ? so making sense is part of marlin

**Comment by ellensp** [comment]
If you use real marlin source code from this github repository and issue exists, then can re open.

**Comment by labotecno** [comment]
> If you use real marlin source code from this github repository and issue exists, then can re open.

yes i use bug fix with DGUS_LCD_UI_RELOADED and same issue .

**Comment by Romain80200** [comment]
Hello, I've got the same problem with my longer lk4 pro.
