### ISSUE TITLE
[BUG] keep getting same error anycubic chiron hemera

### ISSUE THREAD

**Issue by stevetodao** [MarlinFirmware/Marlin#23156]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

so im trying to set up my anycubic chiron to run a new hemera
i go through all the steps but i keep getting the same error that apparently im the only human that has this issue

#if AUTO_ASSIGNED_Z2_STEPPER
  #warning "Auto-assigned Z2 STEP/DIR/ENABLE_PINs to unused En_STEP/DIR/ENABLE_PINs."

anybody know what that means?
i should mention that im a moron and this is my first time doing anything with firmware 
after flashing, everything seems to work, only problem is that while homing only one z motor moves.
they both move when i make them move manually.

apparently this is nobodies problem and i am to fix this on my own, which i can not do.
please someone help before i throw this thing off my balcony.

### Expected behavior

i expect it to work

### Actual behavior

it does not work

### Version of Marlin Firmware

2.0

### Printer model

anycubic chiron

### Electronics

2208 and hemera extruder

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

Cura

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
This is not a Error. It is simply a warning to let you know what is happening.

Marlin auto reassigns unused E stepper motors as additional Stepper as required. 

In your case it is using a unused E as Z2
