### ISSUE TITLE
[BUG] (mks_robin_nano35)

### ISSUE THREAD

**Issue by PhyroXia** [MarlinFirmware/Marlin#23154]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

From today i have this issue while compiling, i changed nothing and 6 days before it worked fine. 

When i undefine `FILAMENT_RUNOUT_SENSOR` i can compile but i need that `FILAMENT_RUNOUT_SENSOR`.
```
> Executing task: C:\Users\wpoch\.platformio\penv\Scripts\platformio.exe run --environment mks_robin_nano35 <

Processing mks_robin_nano35 (platform: ststm32@~12.1; board: genericSTM32F103VE; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103VE.html
PLATFORM: ST STM32 (12.1.1) > STM32F103VE (64k RAM. 512k Flash)
HARDWARE: STM32F103VET6 72MHz, 64KB RAM, 512KB Flash
DEBUG: Current (jlink) External (blackmagic, cmsis-dap, jlink, stlink)
PACKAGES: 
 - framework-arduinoststm32 4.10900.200819 (1.9.0) 
 - framework-cmsis 2.50501.200527 (5.5.1) 
 - toolchain-gccarmnoneeabi 1.90201.191206 (9.2.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing TMCStepper @ ~0.7.3

Compiling .pio\build\mks_robin_nano35\src\src\gcode\geometry\G92.cpp.o
In file included from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/../../feature/../lcd/tft_io/tft_io.h:29,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/../../feature/../lcd/tft_io/touch_calibration.h:25,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/../../feature/../lcd/marlinui.h:38,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/../../feature/tmc_util.h:25,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/trinamic.h:35,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/indirection.h:44,
                 from Marlin\src\gcode\feature\runout\../../../feature/../module/stepper.h:47,
                 from Marlin\src\gcode\feature\runout\../../../feature/runout.h:31,
                 from Marlin\src\gcode\feature\runout\M412.cpp:28:
Marlin\src\gcode\feature\runout\../../../feature/../module/stepper/../../feature/../lcd/tft_io/../../HAL/STM32/tft/tft_fsmc.h:24:10: fatal error: ../../../inc/MarlinConfig.h: No such file or directory
   24 | #include "../../../inc/MarlinConfig.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio\build\mks_robin_nano35\src\src\gcode\geometry\M206_M428.cpp.o
*** [.pio\build\mks_robin_nano35\src\src\gcode\feature\runout\M412.cpp.o] Error 1
========================================================================================= [FAILED] Took 19.83 seconds =========================================================================================

Environment       Status    Duration
----------------  --------  ------------
mks_robin_nano35  FAILED    00:00:19.832
```

### Bug Timeline

18.11.2021

### Expected behavior

Should compile without error.

### Actual behavior

Stops compiling when FILAMENT_RUNOUT_SENSOR is defined

### Steps to Reproduce

Start Compiling when FILAMENT_RUNOUT_SENSOR is defined

### Version of Marlin Firmware

STRING_DISTRIBUTION_DATE "2021-11-12" "bugfix-2.0.x"

### Printer model

Fokoos Odin 5 F3

### Electronics

Stock

### Add-ons

none

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by tpruvot** [comment]
i see only two ".../..." in current marlin code...
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/tft_io/tft_io.h#L24
which is correct

3 then in 
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h#L24
which is correct too

hmm, seems to be related to HAL_PATH macro
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/tft_io/tft_io.h#L29

**Comment by PhyroXia** [comment]
> i see only two ".../..." in current marlin code... https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/tft_io/tft_io.h#L24 which is correct
> 
> 3 then in https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h#L24 which is correct too
> 
> hmm, seems to be related to HAL_PATH macro https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/tft_io/tft_io.h#L29

but what does it have to With Filament_runout_sensor

???

When undefine it, than it works

**Comment by ellensp** [comment]
Cannot reproduce
Probably because steps to reproduce is woefully lacking in details.

Tested on current marlin bugfix 

platformio.ini
default_envs = mks_robin_nano35

Configuration.h
#define SERIAL_PORT 1
#define MOTHERBOARD BOARD_MKS_ROBIN_NANO
#define FILAMENT_RUNOUT_SENSOR
#define NOZZLE_PARK_FEATURE

Configuration_adv.h
#define EMERGENCY_PARSER
#define ADVANCED_PAUSE_FEATURE

**Comment by PhyroXia** [comment]
> Cannot reproduce Probably because steps to reproduce is woefully lacking in details.
> 
> Tested on current marlin bugfix
> 
> platformio.ini default_envs = mks_robin_nano35
> 
> Configuration.h #define SERIAL_PORT 1 #define MOTHERBOARD BOARD_MKS_ROBIN_NANO #define FILAMENT_RUNOUT_SENSOR #define NOZZLE_PARK_FEATURE
> 
> Configuration_adv.h #define EMERGENCY_PARSER #define ADVANCED_PAUSE_FEATURE

I Tested also with the current Marlin Bug fix and it works again but i Wonder why the Marlin Bugfix from 12.11.21 stopped working without any Changes
