### ISSUE TITLE
Invalid suffix "p" on integer constant

### ISSUE THREAD

**Issue by ratulo** [MarlinFirmware/Marlin#2316]
Hello,
long time ago I was iploading marlin to my prusa. Today I want to make som adjustment for bed leveling and I found this problem:
Marlin_main.cpp:2809:14: erroer: invalid suffix "p" on integer constant
Marlin_main.cpp:2821:47: erroer: invalid suffix "p" on integer constant
Can you help me to solve this problem please?
Thanks
All the best

**Comment by AnHardt** [comment]
Would you please be so kind to tell us about your version, or branch of Marlin? Presumably there is something wrong with your Configuration.h. Could we take a look at it?

**Comment by ratulo** [comment]
Thanks for your help. Few seconds ago I found problem:
#define Z_PROBE_OFFSET_RANGE_MAX -5p
its work now
