### ISSUE TITLE
small naming bug

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#2317]
Marlin 1.0.2-1 -- I suspect it is also carried forward, maybe not

in configuration.h I set ==> #define CUSTOM_MACHINE_NAME "CC-BOT 2E " 
when I boot I see "Mendel ready" on welcome screen
in language.h ==>   #ifdef CUSTOM_MENDEL_NAME
which is not defined so it sets #define MACHINE_NAME "Mendel" 
# else

  #ifdef CUSTOM_MENDEL_NAME <<<<<<<<<<<<<<<<<<<<<< change this
    #define MACHINE_NAME CUSTOM_MENDEL_NAME <<<<< change this
  #else
    #define MACHINE_NAME "Mendel" //**
  #endif

then in language_en.h it uses "machine_name" for the message
 #define WELCOME_MSG                         MACHINE_NAME " ready."

need to change "CUSTOM_MENDEL_NAME" to "CUSTOM_MACHINE_NAME" in 2 places language.h

also
Marlin_main.cpp(2667):         LCD_MESSAGEPGM(MACHINE_NAME" "MSG_OFF".");
should be
Marlin_main.cpp(2667):         LCD_MESSAGEPGM(MACHINE_NAME" " MSG_OFF".");
add space before "MSG..."

**Comment by AnHardt** [comment]
Already fixed in `Development`

> #error CUSTOM_MENDEL_NAME deprecated - use CUSTOM_MACHINE_NAME
