### ISSUE TITLE
[BUG] BTT RUMBA32 uses smaller EEPROM chip than AUS3D original model

### ISSUE THREAD

**Issue by jiri-jirus** [MarlinFirmware/Marlin#23202]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

BTT_RUMBA32 actually uses smaller EEPROM chip than AUS3D original. But the same size (8K) isdefined in PINS file.  Actually uses 4K. source: https://github.com/bigtreetech/Rumba32/blob/master/BIGTREETECH%20Rumba32%20V1.0/Hardware/BTT%20Rumba32%20V1.0User%20Manual.pdf

### Bug Timeline

from start

### Version of Marlin Firmware

2.0.9.2

**Comment by thinkyhead** [comment]
Marlin doesn't need the full 8K so it should be fine to assume 4K as the standard.
