### ISSUE TITLE
[BUG] temp error while bed levelling

### ISSUE THREAD

**Issue by sklero001** [MarlinFirmware/Marlin#23209]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi, I installed the version of marlin 2.0.9 on a mega2560 rev A + and I have a problem with the temperature ... when in my printer I send the command for leveling the plane (with the bltouch) every time the pin of the bltouch it goes down, the temperature sensors stop working ... Using a multi-point leveling, it then gives me a minimum temperature error of E. If I don't use the self-leveling of the hob, everything works perfectly. So I assume it's an interference between the sensors and the bltouch. How can I fix it ??

### Bug Timeline

new bug

### Expected behavior

complete auto bed leveling

### Actual behavior

error_min_temp E

### Steps to Reproduce

1. lanch auto bed levelling on more points

### Version of Marlin Firmware

2.0.9.2

### Printer model

Geeetech i3 pro b

### Electronics

stock

### Add-ons

BLtouch V3

### Bed Leveling

ABL Bilinear mesh

### Additional information & file uploads

zip with configuration.h and confiiguration_adv.h
https://drive.google.com/drive/folders/1jK3_ZbKqKP0kev1TiaHyIUUUTWZFZ9PW?usp=sharing

**Comment by robbycandra** [comment]
I think it is a hardware issue.

**Comment by sklero001** [comment]
Hi and thanks for your support...
with Marlin 1.0.8 it work fine!! but with Marlon 2.0.9 nope...

Il giorno lun 29 nov 2021 alle ore 10:46 Robby Candra <
***@***.***> ha scritto:

**Comment by Tannoo** [comment]
I don't have that issue with my printer. I don't believe this is a software issue.

This is usually an issue with the thermistor or it's wiring.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
