### ISSUE TITLE
AutoBed Levelling does not compile with RedRapDiscount lcd

### ISSUE THREAD

**Issue by MysticDarkLord** [MarlinFirmware/Marlin#2321]
I cannot get the file to compile properly when enabling the AutoBedLevelling routine in Configuration.h when I have my LCD enabled (RepRap Full Graphics display). 
Internal out of range error messages come up from UltraLcd file and U8glib.
Can anyone help with this issue or suggest a solution to try.

**Comment by Nandox7** [comment]
I managed to have it compile using the Arduino version 1.6.x.

**Comment by MysticDarkLord** [comment]
I have been using Arduino 0023 as this was the only arduino i could get to compile the Marlin files when I first started with my printer. Do you know where I can get information giving credible instructions in changing the things I need to update to 1.6 particularly in reference to Arduino.h as I cant get anything to compile with 1.6.2.
Currently im getting error conflicting return type in LiquidCrystal_I2C.cpp

**Comment by thinkyhead** [comment]
Prepare for 1.6: #2306

Similar errors: #1741 #1156

**Comment by MysticDarkLord** [comment]
Nandox7 - Cheers great advice, in the end this is what I needed to do and when I deleted files out of the library and caused the IDE to look else where for them I had success.
