### ISSUE TITLE
[BUG] eeprom issue

### ISSUE THREAD

**Issue by Enzo-Enz** [MarlinFirmware/Marlin#23218]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi guys
When I activated eeprom setting in marlin,It seems like it stored all bugs and functions from previous version 
first time that I saw this issue It was when I updated from 2.0.9.1 to 2.0.9.2 
I tried bugfix version,erase eeprom,restore settings but it not fixed...
is there any way to solve this issue or I should buy a new arduino?

### Bug Timeline

2.0.9.2

### Version of Marlin Firmware

2.0.9.2 

### Printer model

DIY printer

### Electronics

ramps

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

**Comment by ellensp** [comment]
No information here. description is quite impossible

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
