### ISSUE TITLE
Ramps EEB no support for fan extender, unable to redefine fan in pins.h

### ISSUE THREAD

**Issue by timemaster5** [MarlinFirmware/Marlin#2322]
Hi, I bought [RRD Fan Extender](http://www.geeetech.com/wiki/index.php/Reprap_Ramps1.4_RRD_Fan_Extender) for my Prusa i3 with Ramps 1.4 on Mega 2650. Extender is working I can spin up any fan by gcode and I am able to use both of them as controller fan or extruder auto fan but not as normal fan controllable by lcd or printing software.
- Expected behavior is that one fan will work immediately on pin D6 (tuneable by lcd menu or printing software) with respect to [Getech wiki](http://www.geeetech.com/wiki/index.php/Reprap_Ramps1.4_RRD_Fan_Extender) _Features: already supported by Marlin firmware (choose "#define MOTHERBOARD 34")_ or I will be able to define FAN_PIN in a corresponding section without problem. Second output will be ready for some feature mentioned above (auto fan, controller fan) - this is done, no problem here..
- Observed behavior is that I cannot redefine fan pin number for EEB board in the corresponding section on line 630 of pins.h 
- Tried #define FAN_PIN 6 here but without success on latest 1.0.2-1 version.

**Comment by thinkyhead** [comment]
You need a working and available PWM pin, one that is not being used up by an interrupt.

This is a duplicate issue. See #492 and #2104. The relevant comments are:

> Pin 4 uses timer 0
> Pin 11 uses timer 1
> Pin 5 uses timer 3
> Pin 6 uses timer 4
> 
> Timer 1 is used for the stepper interrupt.

…and…

> If I set `FAN_PIN` to 5... I can now have control of both fan, the extender secondary fan with `M42 P4 SXXX` command. Go figure. I've just swapped the fan connectors.
> 
> If you find how to use standard pinout for the fans, please let me know.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
