### ISSUE TITLE
Add a delay function to M81 (M81 S60) 

### ISSUE THREAD

**Issue by Micke-71** [MarlinFirmware/Marlin#23235]
### Is your feature request related to a problem? Please describe.

I got a CR10 Smart with built in power off function. By moving a couple of connectors it now have powered serial USB A port (originally camera port) 

It works perfect with no issues as the Pi backpowering through USB and it requires only 1 usb cable since Rpi Zero 2 can be powered through the USB port. 

But to perform a ideal shutdown by shutdown the Pi before cutting power seems almost impossible despite what route or workaround I try. 

### Are you looking for hardware support?

CR10 Smart with power off function

### Describe the feature you want

M81 with an delay option like M81 Sxx

It would solve issues with creating an correct power of sequence. 

Simply add an print finished gcode

M81 S60 ;delayed power off
M118 A1 action:poweroff ;shutdown octoprint/Pi with action command plugin. 

### Additional context

The use of G4 S60 as a delay won’t work. Neither do G85 S60 work as it throws a timeout error message instead of shutting down.

I don’t know if octoprint cancels all G-code commands on shutdown. If so an option to make that option M81 S60 ignore cancellation.

**Comment by thisiskeithb** [comment]
Added in https://github.com/MarlinFirmware/Marlin/pull/23396
