### ISSUE TITLE
Compiled file fails at the last second

### ISSUE THREAD

**Issue by uggels** [MarlinFirmware/Marlin#23241]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Im new to 3d printing and even newer with editing software. I have an Ender 5 Plus with an BTT Octopus V1_1 and a BTT tft35 v3.0. ive been having trouble being successful in compiling my first firmware. I did everything i could to get rid of the error messages but there still seems to be an issue and im not entirely sure how to fix it. Any kind of advice would be helpfu
![Screenshot (2)](https://user-images.githubusercontent.com/95337897/144189102-946fe203-5aec-48e8-92e1-c6e0a5979511.png)
l.

### Bug Timeline

im not sure if this has been an issue in the past

### Expected behavior

i expected my firmware to be compiled seeing as i looked up as much information as i could to get it to run. 

### Actual behavior

at the last moment before the compilation is over, it fails and the error message is nothing i can find info on.

### Steps to Reproduce

1. dowloaded marlin, BTT octopus firmware, and configuration file
2. inputted all the required setting required to get the printer to work based on tutorials i found for my specific equipment
3. compiled
4. failed

### Version of Marlin Firmware

Marlin-bugfix-2.0x 

### Printer model

ender 5 plus

### Electronics

Bigtreetech Octopus V1.1

### Add-ons

BLTouch, BBT TFT35 V3.0, 

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7631673/Configuration.zip
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/7631674/Configuration_adv.zip)
)

**Comment by ellensp** [comment]
When did you download bugfix? as these error where meant to have been fixed 11 hours ago

**Comment by tpruvot** [comment]
its different, press the Clean button before building...

edit: but yes, this problem can be present with the 2.0.x branch (2.0.9.2 tag) you can try to force -DNEEDS_HARDWARE_PWM=1 on command line... this is no more required in bugfix-2.0.x

**Comment by ellensp** [comment]
Clean build on current bugfix using provided Config files compiles (and links, as this error is a linking error) without issues.

**Comment by uggels** [comment]
> 

Haha I guess I downloaded the files a day too early. I just downloaded the newer version and I worked great thank you so much for the help
