### ISSUE TITLE
babystepping working automatically 

### ISSUE THREAD

**Issue by muhammetbaygin** [MarlinFirmware/Marlin#23242]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

while printing I go into the ministep tab and raise the nozzle by 1mm. and when I exit the screen it automatically rises 1mm again.

### Bug Timeline

Always. update marlin 2.0.9.2

### Version of Marlin Firmware

2.0.9.2

### Printer model

özel

### Electronics

yükseltme kartı

**Comment by Sonicboom247** [comment]
do you have //#define MOVE_Z_WHEN_IDLE commented out?

**Comment by muhammetbaygin** [comment]
yes

**Comment by muhammetbaygin** [comment]
is there anyone who can help?

**Comment by ellensp** [comment]
nothing here to go on. No Configuration files. 
No mention of Motherboard or display types. So no way to try and reproduce.
You say
Printer model: özel  ("special")
Electronics: yükseltme kartı  ("upgrade card")
Is not very helpful

**Comment by muhammetbaygin** [comment]
motherboard: mks sgen L
display: tft24 gd bigtreetech
printer same ender 3
