### ISSUE TITLE
[BUG] Tryed to make & use the PT1000 table instead a polinomial

### ISSUE THREAD

**Issue by trengtor** [MarlinFirmware/Marlin#23253]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Tryed to make & use the PT1000 table instead a polinomial. The table was built for a 3.3V reference and a 10-bit "standard" ADC resolution. Board - BTT E3 RRF V1.1, STM32 processor. When I try to use this table (I put it in table 67, file attached), I get an error message - see the photo. 

#define TEMP_SENSOR_0 67  // PT1000/4K7

[thermistor_67.zip](https://github.com/MarlinFirmware/Marlin/files/7647853/thermistor_67.zip)

I do not plan to try a version newer than 2.0.8.2, since that is not the problem (in my opinion).

![photo_2021-12-03_11-14-13](https://user-images.githubusercontent.com/16775489/144569758-20e41cff-c713-473d-9bfe-7e32279205af.jpg)

### Expected behavior

I want to use PT1000 with tabular temperature calculation.

### Version of Marlin Firmware

2.0.8.2

### Electronics

BTT E3 RRF V1.1

**Comment by ellensp** [comment]
Your table has temperatures increasing as adc values increase that is a PTC so you need
"#define REVERSE_TEMP_SENSOR_RANGE_67 1" 
and you may have to flip the table upside down ie start at   { OV(  168 ), -20 },

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
