### ISSUE TITLE
[BUG] Ender3: EEPROM CRC Error screen causes bootloop with zh_CN language

### ISSUE THREAD

**Issue by Blue-Beaker** [MarlinFirmware/Marlin#23256]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

EEPROM CRC Error screen causes bootloop when using zh_CN language.

Trying to use bugfix-2.0.x doesn't work as it says the config is newer than marlin.

### Bug Timeline

I'm not sure

### Expected behavior

The EEPROM CRC Error screen shows up normally with zh_CN language.

### Actual behavior

Instead of showing the EEPROM CRC Error screen, the machine stucks into a bootloop between Ender 3 and Marlin logo after flashing.

### Steps to Reproduce

1.Flash Marlin that causes EEPROM CRC Error (In my case,enable/disable BL-Touch and reflash) with zh_CN language setting
2.The machine stuck in a bootloop between the Ender3 logo and marlin logo.

3.Switch to en language and reflash
4.the EEPROM CRC Error screen appeared normally. 

### Version of Marlin Firmware

2.0.9

### Printer model

Creality Ender 3

### Electronics

Stock creality V4.2.2 board

### Add-ons

a filament sensor and a BL-Touch clone

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7653886/Marlin.zip)

**Comment by ellensp** [comment]
"Trying to use bugfix-2.0.x doesn't work as it says the config is newer than marlin."
This is always the user attempting to use mismatched Marlin config and source code

You have probably download import branch configs. 
Ie you didn't change the branch to bugfix branch before downloading the zip file (or change branch after git cloning) 

bugfix is called bugfix-2.0.x.zip https://github.com/MarlinFirmware/Configurations/archive/refs/heads/bugfix-2.0.x.zip
If yours says import-2.0.x.zip you have done it wrong.

Test with bugfix
