### ISSUE TITLE
[BUG] Issues compiling in VS Code/Platform IO (cannot find cortex lib)

### ISSUE THREAD

**Issue by caca1986** [MarlinFirmware/Marlin#23266]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin is not compiling in VS Code. I have tried stable version, bug fix, uninstalled VS Code and Platform IO, updated windows, etc., and still getting the same issue. I always get the following error message in the terminal:

Linking .pio\build\STM32F103RET6_creality\firmware-20211205-202633.elf
c:/users/caca1/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: cannot find -larm_cortexM3l_math
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\STM32F103RET6_creality\firmware-20211205-202633.elf] Error 1

### Bug Timeline

4 Dec 2021

### Expected behavior

I expect it to compile

### Actual behavior

It does not Compile

### Steps to Reproduce

1. attempt to compile either bug fix or stable release of Marlin in VS Code.

### Version of Marlin Firmware

Bug Fix 2.0x

### Printer model

Ender 3 Pro

### Electronics

Creality 4.2.2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by ellensp** [comment]
Issue is with your platfomio install
delete c:/users/caca1/.platformio directory and restart vscode. 
This forces platformio to reinstall.
