### ISSUE TITLE
error on configuration.adv.h for creality Ender 3V2 on the nightly build

### ISSUE THREAD

**Issue by pyrophilus** [MarlinFirmware/Marlin#23264]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

when compiling the nightly build for the Creality Ender 3V2, the compiler threw up an error.
on the configuration.adv.h,

Verbose mode can be enabled via `-v, --verbose` option
In file included from buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/MarlinConfigPre.h:56,
                 from buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/MarlinConfig.h:28,
                 from buildroot/share/PlatformIO/scripts/common-dependencies.h:29:
g:\my drive\3d printer firmwares\marlin-bugfix-2.0.x\marlin\configuration_adv.h:1332:2: error: #endif without #if
 1332 | #endif // HAS_LCD_MENU
      |  ^~~~~

Upon looking at the configuration.adv.h:

#if HAS_LCD_MENU

  // Add Probe Z Offset calibration to the Z Probe Offsets menu
  #if HAS_BED_PROBE
    //#define PROBE_OFFSET_WIZARD
    #if ENABLED(PROBE_OFFSET_WIZARD)
      //
      // Enable to init the Probe Z-Offset when starting the Wizard.
      // Use a height slightly above the estimated nozzle-to-probe Z offset.
      // For example, with an offset of -5, consider a starting height of -4.
      //
      //#define PROBE_OFFSET_WIZARD_START_Z -4.0

      // Set a convenient position to do the calibration (probing point and nozzle/bed-distance)
      //#define PROBE_OFFSET_WIZARD_XY_POS { X_CENTER, Y_CENTER }
    #endif
  #endif

    #if ENABLED(AUTO_BED_LEVELING_BILINEAR)
      // Add a calibration procedure in the Probe Offsets menu
      // to compensate for twist in the X-axis.
      //#define X_AXIS_TWIST_COMPENSATION
      #if ENABLED(X_AXIS_TWIST_COMPENSATION)
        /**
         * Enable to init the Probe Z-Offset when starting the Wizard.
         * Use a height slightly above the estimated nozzle-to-probe Z offset.
         * For example, with an offset of -5, consider a starting height of -4.
         */
        #define XATC_START_Z 0.0
        #define XATC_MAX_POINTS 3             // Number of points to probe in the wizard
        #define XATC_Y_POSITION Y_CENTER      // (mm) Y position to probe
      #endif
    #endif
  //#endif   <--  this was an EXTRA #endif that needs to be deleted.

### Bug Timeline

New.

### Expected behavior

I expected the program to compile.

### Steps to Reproduce

1. copy configuration.h and configuration.ad.v from the nightly build zip file to the marlin folder for the 2.0.x nightly build.
2. hit compile without changing anything.   you will be the compiler error for the #end if without #if

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Creality Ender 3 V2

### Electronics

upgraded to 4.2.7 board

### Add-ons

none

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

**Comment by thisiskeithb** [comment]
Grab a fresh copy. This was fixed an hour ago: https://github.com/MarlinFirmware/Configurations/commit/a912d4f2583fb5bb28853fe4000ceb354bc18112
