### ISSUE TITLE
[FR] Retraction Distance Adjustment while Running

### ISSUE THREAD

**Issue by mkoeppel74** [MarlinFirmware/Marlin#23269]
### Describe the feature you want

I want to be able to tune retraction distance while running a print.

**Comment by thisiskeithb** [comment]
This already exists as `FWRETRACT`: https://github.com/MarlinFirmware/Marlin/blob/63d73bfafc8c146a0f230ad1a45c97f0ba23168b/Marlin/Configuration_adv.h#L2326-L2340
