### ISSUE TITLE
[BUG] Steppers humming very loud during autohome

### ISSUE THREAD

**Issue by Contrasens** [MarlinFirmware/Marlin#23271]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I posted here a short movie of the behavior: [https://youtu.be/7HNBnkE0OBM](https://youtu.be/7HNBnkE0OBM) 

I bought a second BTT SKR E3 Turbo, after the first one reported an fried Y driver (coil short circuit). The second one initially worked, then started the same behavior.

Since all the electronics are fastened in CR-10 inside a metallic case I thought that there is some current running through one of the fastening bolts to another. I removed the board from the screws and WONDER! it worked like a charm!

I was curious and replaced it with the board I considered fried. Also outside of the case, no screws, it magically worked!

Since a few days I get the same problems again :( 

I am not sure that this is a problem related to the Marlin firmware or is something in my setup that ceased to work properly. I will install the original Creality board (also running a Marlin 2.x) but first I need to disable the second Z stepper :/ since that board has only XYZE drivers...

### Bug Timeline

Since a about 2 weeks

### Expected behavior

I expect autonome to finish without noise and printer failure.

### Actual behavior

When autohoming (from the menu or G28 sent via Pronterface) the steppers shall complete successfully the autohoming sequence.

### Steps to Reproduce

1. Power up
2. Autohome (menu or G28)
3. X axis is the first to home, this (usually, but not always!) work
4. Then the Y axis starts to move towards the end stop, at which is very loud and moves very slow (check my movie out)
5. Printer fails and need to be restarted

### Version of Marlin Firmware

2.0.9.2 (latest master branch)

### Printer model

Creality CR-10 mini, modded

### Electronics

BTT SKR E3 Turbo

### Add-ons

Dual Z steppers, capacitive Z probe as endstop etc.

### Bed Leveling

ABL Bilinear mesh

### Additional information & file uploads

My configuration here: https://github.com/Contrasens/Marlin/tree/2.0.x/config/CR10Mini

**Comment by ellensp** [comment]
I bleave this to be a configuration or a hardware issue 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
