### ISSUE TITLE
[FR] Multi-drive, USB support for Power Loss Recovery

### ISSUE THREAD

**Issue by alvarotorijano** [MarlinFirmware/Marlin#23292]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Power loss recovery seems not to work over USB drives. Tested on MKS Robin Nano v3.
I've tested the PLR with only SD support and works great. Then enabled USB support and does not works with any configuration (USB_FLASH_DRIVE_SUPPORT + USE_UHS2_USB / USE_UHS3_USB / NONE and or USE_OTG_USB_HOST and any possible combination) Also tried with MULTI_VOLUME with no results. 
File created on USB seems to be correct but it is not readen because USB seems to be mounted too late to be detected on power on secuence. 
Is there anything that I'm missing?

### Expected behavior

Recovery file detected and print resume promted.

### Actual behavior

Ignored and booted up normaly with no resume print prompted.

### Steps to Reproduce

Launch a print with powerloss recover enabled and a UPS. Switch off the PSU and message is displayed, nozzle moved and file created, the power is drained out from batteries. After that power on as usual

### Version of Marlin Firmware

2.0.9.2

### Printer model

Prusa I3

### Electronics

Mks robin nano V3

### Add-ons

MKS UPS

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

**Comment by thisiskeithb** [comment]
#24015 has been merged. Closing.
