### ISSUE TITLE
[BUG] RGB_LED dimming issues

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#23301]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Led dimming not working , because the pwm frequency is to high . For a dimming effect the pwm frequency must be between 75/150 hz , if higher our eyes don't see the fading correctly. Impossible to make special color because of corrupted dimming of each color

List of issues
- Impossible to have all colors , because of corrupted dimming of each
- Pwm frequency (for rgb led) is made by program loop , then can change anytime , and is too high '2khz'
- Because of high frequency fading is not seen by eyes
- Because of frequency changes during printing color mixing change too 

Test : I have used the fast pwm code of the laser feature and applied it to rgb led mosfet , used 100hz , and ALL IS PERFECT

How to solve this without rewriting RGBLED code with ' Laser feature code '

I have tried to find how to change the pwm of the current rgbled code , but it's too much for me , impossible to find the source

Thks

### Version of Marlin Firmware

2.0

### Additional information & file uploads

.

**Comment by thinkyhead** [comment]
Would you be able to test some `bugfix-2.0.x` commits to narrow this down?

The strategy is to find a commit from some point in the "distant" past where the feature works. Then, test a commit from halfway between that date and today…. And then you keep going to the commit half-way in between your "known to work" commit and your "known to be broken" commit until you find the exact day where it broke.

If you started from a point 256 commits in the past, it would take no more than 8 tests to find the exact commit that broke it.
