### ISSUE TITLE
[FR] Artillery Genius Pro support

### ISSUE THREAD

**Issue by gudvinr** [MarlinFirmware/Marlin#23313]
### Are you looking for hardware support?

Brand: Artillery 3D
Model: Genius Pro
Board: Artillery Ruby custom board (STM32F401RC)

### Describe the feature you want

Upstream board/printer support

### Additional context

Genius Pro uses same Artillery Ruby board as Sidewinder X2, which support was added recently in #23029  
There's no configuration for Genius Pro, however. Which is expected because there were no issues about that particular printer.

Artillery has Marlin source code for 2.0.9.1 in their repo: https://github.com/artillery3d/genius-pro-firmware.

Which isn't exactly 2.0.9.1 but apparently it is snapshot taken at commit `f8f68f9259cc486fd36147f4f9d1e474940510dd` with additional changes.

Configuration is available here: https://github.com/artillery3d/Configurations/ (artillery-import-2.0.x branch at the moment of writing).

**Comment by Sonicboom247** [comment]
pretty sure thats the same board on the Hornet as well. hopefully the display is not the same Fysetc 12864 v1

**Comment by ellensp** [comment]
Its a touch fully colour display, so no not a  Fysetc 12864, but an extremely limited in functionally touch interface

**Comment by gudvinr** [comment]
There's display firmware too, albeit only binaries available.  
https://github.com/artillery3d/genius-pro-tft-firmware

However, it seems like display is MKS TFT28, which does have [something](https://github.com/makerbase-mks/MKS-TFT28-32-Firmware) without any documentation whatsoever. That's same display used in Sidewinder X2 and, IIRC, in Sidewinder X1 and Genius (non-pro) too.  
There's possibility of flashing [BTT firmware](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware), apparently.

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Configurations/pull/641.

**Comment by Dviros** [comment]
Hi @thisiskeithb,
Can confirm that flashing the latest 2.0.9.3 with your artillery configs results in my ST32 Ruby card not booting, requiring me to boot back to DFU (using the sad warranty voiding boot0+3.3v short circuit) and revert to Artillery's 2.0.9.1 :\
Using digant's TFT28 firmware as well.

I've compared it all - artillery's configs, project ini's and did not find anything meaningful.

Using Genius Pro and can share my configs if required.

Many thanks and Happy New Year!

**Comment by thisiskeithb** [comment]
> Can confirm that flashing the latest 2.0.9.3 with your artillery configs results in my ST32 Ruby card not booting

Download 2.0.9.3 again. There was a bug that prevented boards from booting so it was fixed and re-tagged.

**Comment by Dviros** [comment]
OMG. Will do, thanks a lot!

**Comment by Dviros** [comment]
@thisiskeithb
Can confirm that I've tested the latest 2.0.9.3 tag and the commits in the repo, both are not booting :(
Any way to double check this please?

**Comment by thisiskeithb** [comment]
@Dviros Please open a new [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose) so this can be properly tracked.

**Comment by Sonicboom247** [comment]
sad, was hoping this would also address the marlin crash on boot according to @ellensp on the Hornet with the same board.

**Comment by Dviros** [comment]
https://github.com/MarlinFirmware/Marlin/issues/23393
