### ISSUE TITLE
[BUG] (bug summary)MKS EAGLE + MKS MINI 12864 V3.0

### ISSUE THREAD

**Issue by gauthama93** [MarlinFirmware/Marlin#23315]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Onboard/LCD SD card slots stop working when enabling USB_FLASH_DRIVE_SUPPORT. USB port also doesn't work, lcd says "USB start error".
![Screenshot 2021-12-18 132428](https://user-images.githubusercontent.com/52348293/146633941-4c576a6f-90ef-40cd-b5f2-6c59bcd15452.png)
Have tried all possible configurations in the USB_FLASH_DRIVE_SUPPORT section couldn't get it working.

### Version of Marlin Firmware

bugfix-2.0.x

SD Card (headless)

**Comment by ellensp** [comment]
USB is not supported by that option for this controller.
Do not enable USB FLASH DRIVE SUPPORT
build using build environment mks_eagle_usb_flash_drive

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
