### ISSUE TITLE
[FR] (feature summary) Help (:

### ISSUE THREAD

**Issue by s145854** [MarlinFirmware/Marlin#23336]
### Is your feature request related to a problem? Please describe.

Hello i have little problem i have bltouch with 5 pin and i have creality mother board v4.2.2 a printer has ender 3 v2 i connect to bltouch on mother board 5 pin but on marlin Configuration.h i dont know what enable and what disable i see guides on youtube but all guides work on diffrent connects what i need to choice thanks

#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
// Force the use of the probe for Z-axis homing
//#define USE_PROBE_FOR_Z_HOMING
//#define Z_MIN_PROBE_PIN 32 // Pin 32 is the RAMPS default

what i need disable and what enable? thanks for help

![91630611-fa4d5f00-e9d2-11ea-88d9-b2e080c9a8d2](https://user-images.githubusercontent.com/96540521/147126921-9c991c47-b326-43fa-9ad2-5780d0edeb34.jpg)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
