### ISSUE TITLE
[BUG] Bed leveling freezing screen during print

### ISSUE THREAD

**Issue by Nazrax** [MarlinFirmware/Marlin#23346]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

About a year ago I built Marlin from the 2.x bugfix branch, including manual mesh leveling. I'm trying to build a fresh copy, but I'm running into some kind of bug or other misconfiguration: with bed leveling installed and enabled, the display completely freezes as soon as a print starts (it keeps changing during the auto-home and while everything heats, but when the head starts to move the screen freezes). I can click the wheel and get a beep as if it's entered the menu, but the screen doesn't actually _show_ the menu, and I can't seem to interact with it (e.g. click/down/down/click should stop the print, but it keeps going). The print seems to run OK (e.g. the printer executes the gcode OK).

### Bug Timeline

Today

### Expected behavior

The screen continues to update during a print

### Actual behavior

The screen freezes when the print begins.

### Steps to Reproduce

1. Clone a fresh copy of Marlin's bugfix-2.0.x, put in fresh copies of the Configuration files (from the same branch) (out of `config/examples/Creality/Ender-3 Pro/CrealityV1/`), build it, and run it with no problems.
2. Edit Configuration.h to enable `MESH_BED_LEVELING` and `ENABLE_LEVELING_AFTER_G28`, build it, run it, and experience the display freeze.
3. The same two steps above with the 2.0.9.2 tag produce the same results.
 
It doesn't seem to make any difference whether I actually run the bed leveling first or not.

### Version of Marlin Firmware

bugfix 2.0.x (revision 81831ab1)

### Printer model

Creality Ender 3 Pro

### Electronics

Stock (V1 board)

### Add-ons

None

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Other (explain below)

### Host Software

SD Card (headless)

### Additional information & file uploads

I'm using CHEP_bed_level_print.gcode from https://www.chepclub.com/bed-level.html.

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/7775110/configs.zip)

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
