### ISSUE TITLE
[BUG] Extraneous bracket in menu_bed_corners.cpp

### ISSUE THREAD

**Issue by adsaxton** [MarlinFirmware/Marlin#23343]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

There is an extra close-bracket '}' at line 299 of menu_bed_corners.cpp. Removing the line allows compiling with Probe Leveling enabled.

### Bug Timeline

With current bugfix-2.0x release

### Expected behavior

I expected it to compile with Probe-Leveling enabled.

### Actual behavior

Failed to compile with the error:

Marlin/src/lcd/menu/menu_bed_corners.cpp:302:5: error: 'ui' does not name a type
  302 |     ui.goto_screen(_lcd_draw_level_prompt); // prompt for bed leveling
      |     ^~
Marlin/src/lcd/menu/menu_bed_corners.cpp:303:5: error: 'ui' does not name a type
  303 |     ui.set_selection(true);
      |     ^~
Marlin/src/lcd/menu/menu_bed_corners.cpp:304:3: error: expected declaration before '}' token
  304 |   }
      |   ^
Compiling .pio/build/STM32G0B1RE_btt/src/src/lcd/menu/menu_info.cpp.o
*** [.pio/build/STM32G0B1RE_btt/src/src/lcd/menu/menu_bed_corners.cpp.o] Error 1

### Steps to Reproduce

Compile with Probe Leveling enabled.

### Version of Marlin Firmware

2.0.9.2

### Printer model

Ender 3 Pro

### Electronics

MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V3_0

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by thisiskeithb** [comment]
This was already fixed in https://github.com/MarlinFirmware/Marlin/pull/23337
