### ISSUE TITLE
Marlin Google Hangout • Saturday 11 July 2015 at 21:00pm UTC • Topics TBD • Be there!

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#2335]
```
Name             Zone               online weekdays      online weekend
@thinkyhead      UTC-7
@Wackerbarth     UTC-5
@Jnesselr        UTC-5
@clefranc        UTC-4
@alexborro       UTC-3
@fmalpartida     UTC+1
@AnHardt         UTC+1
@Wurstnase       UTC+1
@CONSULitAS      UTC+1
@paclema         UTC+1
@boelle          UTC+1              13:00 - 20:00        ~8:00 - 22:00
@emartinez167    UTC+8
@ntoff           UTC+10
```

The above UTC+ values change at summer/winter time by one hour

"Official" Clock :  http://www.timeanddate.com/time/aboututc.html

<a href="https://plus.google.com/hangouts/_/gxn3wrea5gdhoo223yimsiforia" target="_blank">Hangout</a>

link to googledoc with topics:

<a href="https://docs.google.com/document/d/1GmKjDVOKLj6f6s76ZL99LvCPOwy_PkYK57M88Q2oNdM/edit?usp=sharing" target="_blank">Topics</a>

**Comment by boelle** [comment]
No topics yet.... if you want anything added go to very end of googledoc linked above and add comments

you should not need an account for that....

and please keep posts to be about the hangout only... will zapp post that is not about the hangout

**Comment by thinkyhead** [comment]
Posting some topic ideas…

**Comment by AnHardt** [comment]
* Chances of fixing G29 in a reasonable time.
* Making current `Development` an `RC` regardless of the errors with G29, to avoid blocking innovations.
* Separate branches for releases.
* Discuss the currently open PRs - issues.

**Comment by fmalpartida** [comment]
I'm going to skip tonight's handout. A small compromise with some friends.

**Comment by boelle** [comment]
np... at least we know :-D

2015-06-27 23:12 GMT+02:00 fmalpartida <notifications@github.com>:

**Comment by fmalpartida** [comment]
Can we take a look at updating the integration branch with the development contents.

**Comment by boelle** [comment]
it will be on topics list

@thinkyhead will you join us tonight?

**Comment by Wackerbarth** [comment]
Suppose they held a meeting and nobody showed up.

@thinkyhead @Jnesselr @clefranc @alexborro
@fmalpartida @AnHardt @Wurstnase @CONSULitAS
@paclema @boelle @emartinez167 @ntoff

**Comment by Jnesselr** [comment]
It would seem to be because the original post didn't actually tag us, so I was not aware this meeting was going on, and did not schedule time to have it.

**Comment by fmalpartida** [comment]
Yep, missed it altogether! 

How about if we reschedule form next week?
Tagging does indeed help.

**Comment by boelle** [comment]
I have allready said that i will not be along for the next month or so...

**Comment by thinkyhead** [comment]
Next meeting ~~in 2 weeks?~~ this Saturday! Consider this advance notice, and set those smartphone alarms…

**Comment by Jnesselr** [comment]
I believe the other issue said it was the 18th.

**Comment by Wackerbarth** [comment]
Please refer to issue #2424 for discussion about the next hangout.
