### ISSUE TITLE
[BUG] G28 Results in Homing Failed on 2.0.9.3

### ISSUE THREAD

**Issue by RushHour2k5** [MarlinFirmware/Marlin#23356]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Running a G28 results in Homing Failed when using Marlin 2.0.9.3.

### Bug Timeline

12/25/2021

### Expected behavior

Complete homing of X, Y, and Z Axes.

### Actual behavior

Homing Failed error.

### Steps to Reproduce

Install Marlin 2.0.9.3 release and run a G28.

### Version of Marlin Firmware

2.0.9.3

### Printer model

Longer LK5 Pro

### Electronics

Stock

### Add-ons

N/A

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

https://www.dropbox.com/s/aixnwqw4y05v7d3/Marlin%202.0.9.3%20Bug%20Report.zip?dl=0

Changed "constexpr uint8_t DGUS_LEVEL_GRID_SIZE" to 81 instead of 25 under ./Marlin/src/lcd/extui/dgus_reloaded/config/DGUS_Addr.h"

**Comment by pilot76103** [comment]
https://github.com/MarlinFirmware/Marlin/commit/e17d710c5c4c96e069f64854e3fcdb77abcf90e1 no longer results in error; however, it also does not move any axes.

**Comment by RushHour2k5** [comment]
Issue resolved with https://github.com/MarlinFirmware/Marlin/commit/e17d710c5c4c96e069f64854e3fcdb77abcf90e1.
