### ISSUE TITLE
G33 not honoring Z_SAFE_HOMING during delta auto calibration

### ISSUE THREAD

**Issue by JoosyBill** [MarlinFirmware/Marlin#23359]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

My Kossel mini based printer is failing during G33 due to homing between passes moving the effector out of the print volume. 

As a temporary fix I modified void ac_home() in G33.cpp to call the same home instead. This gets past the out of bounds errors and I am able to complete the G33 auto calibration. I understand that this quick hack might not meet coding standards, but this change has addressed the issue for my printer.

Thank you.
```cpp
void ac_home() {
  endstops.enable(true);

#if ENABLED(Z_SAFE_HOMING)
  home_z_safely()
#else
  TERN_(HAS_DELTA_SENSORLESS_PROBING, probe.set_homing_current(true));
  home_delta();
  TERN_(HAS_DELTA_SENSORLESS_PROBING, probe.set_homing_current(false));
#endif

  endstops.not_homing();
}
```

### Bug Timeline

this appears to be an old issue

### Actual behavior

homing operations during auto calibration should stay within the print volume

### Steps to Reproduce

Send G33 command to delta printer with a 38 offset on the fixed probe

### Version of Marlin Firmware

using current bugfix_2.0.x

### Printer model

Kossel Delta

### Electronics

stock

### Bed Leveling

ABL Linear grid

### Host Software

Pronterface

**Comment by thinkyhead** [comment]
Hmm… Since `ac_home` is only called from within the `G33` G-code handler, it is safe and might be more effective to replace it with this…
```cpp
void ac_home() { gcode.process_subcommands_now(F("G28")); }
```
CC: @LVD-AC
