### ISSUE TITLE
[BUG] Does not upload Firmware and boot with latest bugfix2

### ISSUE THREAD

**Issue by sarvenn** [MarlinFirmware/Marlin#23358]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Yesterday I compiled latest bugfix 2 fw to my SKR mini E3 V2 motherboard.
Screen does not turned to home screen, it stayed as a blank blue screen eternally. I checked the sd card, sometime firmware file gets .cur suffix, sometimes it doesn't, but the result was same everytime, then I downloaded an older version of bugfix2 (on of the early December commits), it worked.
So, l tried this several times with controlled tests. At every trial my configuration files were the same.
[config files.zip](https://github.com/MarlinFirmware/Marlin/files/7776815/config.files.zip)

### Bug Timeline

New bug, started at latest bugfix2

### Expected behavior

Bug free firmware upload just in 10-15 seconds.

### Actual behavior

Screen stays at blank blue screen for forever.

### Steps to Reproduce

Regular fw compile and upload procedure.

### Version of Marlin Firmware

bugfix2 25 December

### Printer model

Ender 3 pro

### Electronics

BTT SKR Mini E3 V2 & TFT35 E3 V3

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Prusa Slicer

**Comment by ellensp** [comment]
Latest bugfix had issues, download new copy from now
