### ISSUE TITLE
Config for Geeetech a10 build results in multiple errors

### ISSUE THREAD

**Issue by dmagicone** [MarlinFirmware/Marlin#23378]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Using auto build marlin and the bug fix config for Geeetech A10 results in many errors. Example (Fatal error: can't create .pio\build\mega2560\src\src\MarlinCore.cpp.o: No such file or directory).

### Bug Timeline

Newest build. I didnt try the premade configs before. 

### Steps to Reproduce

1. bug fix builds fines with no changes.
2. imported preconfig for geeetech a10
3. bug fix with preconfig for geeetech a10 fails with errors

### Version of Marlin Firmware

bugfix 2.0

### Printer model

Geeetech A10 stock

### Electronics

stock

**Comment by ellensp** [comment]
Listed error is a platformio issue. 
Sometimes you have to try and build multiple times
