### ISSUE TITLE
Firmware crashes during UBL G29 P1

### ISSUE THREAD

**Issue by andypmuc** [MarlinFirmware/Marlin#23376]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have a printer like Prusa with a GT2560 A+ board and are using G29 P1 for UBL.

It works quite well, but sometimes I have the problem, that during the longer G29 P1 command, the printer stops transmitting over serial, but actually continues to take the points. After G29 P1 is completed it stops giving a strange noise over the speaker. Then only a hard reset, via power cut off helps.

Currently, I am running on 2.0.7.2 but I have also experienced this issue with 1.x.x.x. The error is very sporatic and I could not find a reason, why it suddently stops.

I though it might be a power issue, that the board is draining to much power from USB port, but I have used a USB hub, with 3 A, but it is not helping.

There is not also a certain point, when it stops transmitting, sometimes point 2, sometimes 4 and sometimes 17 of 25.

I have actived debugging log, but this does not help either, the is no error message, just the serial info from the board stops and the printer continues until end of G29 P1. I attached the log.

Maybe this has something to do with the depth of the Z axis of the probe, maybe it goes down to much ...

I am going to update to 2.0.9.3, but I assume this is not going to help.

I am usually using repetier server, but I have also tried it with repetiert host, which is not helping.

Any ideas, I am unsure wether this is a real firmware problem....

### Bug Timeline

could not determine

### Expected behavior

Clear error message or G29 P1 is working robust without trouble

### Actual behavior

Stops after G29 P1 with strange sound in the speaker and serial com stops transmitting from printer during G29 P1 command.

### Steps to Reproduce

Following code I use for UBL: 

M111 S55

M280 P0 S180

G28 ; home all axes
M280 P0 S65;

;G29 V4; auto bed leveling

G29 P1
G29 P3
G29 T
G29 S0
G29 A

M280 P0 S180

G1 X30 Y30 Z5 F5000
;G1 X0 Y0 Z5 F5000
G1 Z2 F500

### Version of Marlin Firmware

2.0.7.2

### Printer model

Prusa

### Electronics

GT2560 A+

### Add-ons

Servo, which might drain power or returns power spikes; Contact for UBL, which also might return power spikes

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Simplify3D

### Host Software

Repetier Host

### Additional information & file uploads
[Bug23376_Console_Output.txt](https://github.com/MarlinFirmware/Marlin/files/7797007/Bug23376_Console_Output.txt)

**Comment by zonalimitatore** [comment]
Too much debug. (S55???)
Imho it's an serial overflow,or a wrong settings of baudrate.

Try to 
M111 S6
G29 P1

**Comment by sjasonsmith** [comment]
I deleted the large console log and attached it as a file.

**Comment by andypmuc** [comment]
Thanks for putting the long log in the file. I already tried without any debugging, this is not the problem. Seams the board has USB issues, but it happens always with G29 P1 command or in >95% of the cases.

**Comment by zonalimitatore** [comment]
> Thanks for putting the long log in the file. I already tried without any debugging, this is not the problem. Seams the board has USB issues, but it happens always with G29 P1 command or in >95% of the cases.

Ok...try to change the baudrate

**Comment by thinkyhead** [comment]
See if it helps to enable `SERIAL_OVERRUN_PROTECTION`.

**Comment by XDA-Bam** [comment]
Your hardware setup isn't quite clear to me. What does
> I though it might be a power issue, that the board is draining to much power from USB port, but I have used a USB hub, with 3 A, but it is not helping.
> 
mean? Is the board powered using 12/24 V _and_ 5 V are connected via the USB port? If so, can it occur that the board is powered only via USB, before the "actual" power (12/24 V) comes live? As far as I'm aware, this can cause issues in the boot process due to insufficient voltage being provided to some components.
