### ISSUE TITLE
2.0.9.3 LCD and Octoprint problem on CR-10 V3 and CR-10 Mini with SKM Mini E3 V2

### ISSUE THREAD

**Issue by XXX-ManZG** [MarlinFirmware/Marlin#23379]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

2.0.9.3 LCD problem on CR-10 V3 and CR-10 Mini with SKM Mini E3 V2.
After firmware flash LCD is blank and Octoprint won't connect to printer.
I used same settings as on 2.0.9.2 which works.

I am not advanced Marlin user so please 

### Expected behavior

Screen working
Octoprint connected

### Actual behavior

Screen blank
Octoprint says connection error.

### Steps to Reproduce

Flash 2.0.9.3

### Version of Marlin Firmware

2.0.9.3

### Printer model

CR-10 V3 stock and CR-10 Mini with SKM Mini E3 V2

### Host Software

OctoPrint

### Additional information & file uploads

[CR-10 mini.zip](https://github.com/MarlinFirmware/Marlin/files/7786039/CR-10.mini.zip)
[CR-10 V3.zip](https://github.com/MarlinFirmware/Marlin/files/7786041/CR-10.V3.zip)

**Comment by ellensp** [comment]
If you grabbed 2.0.9.3 when it was new, you need to get the code again. there were issue when it was released
