### ISSUE TITLE
Ender 7 and Ender 3 S1 mainboard support

### ISSUE THREAD

**Issue by leofaoro** [MarlinFirmware/Marlin#23382]
Hello, not sure this is the right way as this was merged already, but the Ender 7 and Ender 3 S1 apparently have very similar sounding names for their boards, yet they are very different. The latest (2.0.9.3) has support for the Ender 7 board but only mentions v2.4.S1, there's more to the model name. People with the Ender 3 S1 should not install this config.

The Ender 7 reads CR-FDM-v2.4.S1_v101
Then Ender 3 S1 reads CR-FDM-v2.4.S1_301

So maybe it's best to update this as these are 2 different boards. 
thanks

_Originally posted by @leofaoro in https://github.com/MarlinFirmware/Marlin/issues/23010#issuecomment-1002334942_

**Comment by thisiskeithb** [comment]
This is already marked as being a board found in the Ender-7: https://github.com/MarlinFirmware/Marlin/blob/f3b8b0b5b94cbd96bb3cdb48625942b14e17babc/Marlin/src/pins/stm32f1/pins_CREALITY_V24S1.h#L25
