### ISSUE TITLE
[FR] (Check heating temperature before printing)

### ISSUE THREAD

**Issue by dmitrygribenchuk** [MarlinFirmware/Marlin#23389]
### Describe the feature you want

Hello. Found one thing that could be improved.
When I start printing on my Ender 3v2 bed and nozzle heating one by one (reduce the load on the power supply I think)
BUT. If the current nozzle temperature is more than the temperature for printing - the printer changes it only after bed heating. 
If current temperature is set to 0 (for example without prehead setup) - the printer change the temperature of the nozzle only after bed heating (nozzle cooling to 0 and after that heating again)
Can you improve it and check the nozzle temperature at the start and reduce or keep it?

### Additional context
![PXL_20211230_141139322](https://user-images.githubusercontent.com/15670247/147750971-1208e7c3-639f-49c0-9d68-a7276b552dbc.jpg)

_No response_

**Comment by ellensp** [comment]
Printer does what you tell it to do with g-code.

If you set the hotend to a temperature with M109 it raises hot end temperature does nothing else while waiting for it to get to temperature, 
But if you use M104 it sets temperature in background and continues processing next g-code.

Same with the bed 
If you use a M190 it will wait for the bed to get to temperature and not do anything else.
If you use M140 It will set bed temp in background and continues with next g-code.

Setting either to a temperature of 0 just turns off heating, it does not wait for 0, as that would likely never happen in most homes..  (ie it is below room temperature)

Your description does not  make any sense as it does not wait for 0

What it does is under your control, In your slicers start.gcode file or equivalent.
