### ISSUE TITLE
[BUG] (X, Y, and Z axis at half scale)

### ISSUE THREAD

**Issue by sk8board** [MarlinFirmware/Marlin#23398]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have a Core XY printer that I am updating to Marlin 2.0.9.3. 

The X, Y, and Z axis will move half the distance that I commanded. If use the printer UI to move an axis 300mm, the axis will only move 150mm.

If I change DEFAULT_AXIS_STEPS_PER_UNIT to double the steps for each axis, the axis will still only move half the distance which was commanded (no difference by changing DEFAULT_AXIS_STEPS_PER_UNIT).

I have found no difference using the latest bugfix.

Attached are the Configuration.h and Configuration_adv.h

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/7795098/Config.zip)

### Bug Timeline

2.0.9.3 December 30, 2021

### Expected behavior

I expected the axis to move 300mm when commanding the axis to move 300mm.

### Actual behavior

An axis (X, Y, or Z) will move half the distance which is commanded.

### Steps to Reproduce

1. Perform Auto Home
2. Use printer UI to move an axis
3. Measure the distance the axis has actually moved.
4. Discover the axis move half the distance which was commanded.

### Version of Marlin Firmware

2.0.9.3

### Printer model

Two Trees Sapphire Plus

### Electronics

Stock MKS Robin Nano V1.2  (mks_robin_nano35)

### Bed Leveling

ABL Bilinear mesh

**Comment by ellensp** [comment]
you need to reload defaults from firmware into your eeprom M502 load defaults, then M500 save to eeprom
