### ISSUE TITLE
[BUG] (CANNOT_EMBED_CONFIGURATION and related warning should not be defined when embed is not requested)

### ISSUE THREAD

**Issue by hwmland** [MarlinFirmware/Marlin#23405]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When building on AVR (my case: MKS_GEN_L board) there is warning reported:
```cpp
  #warning "Disabled CONFIGURATION_EMBEDDING because the target usually has less flash storage. Define FORCE_CONFIG_EMBED to override."
```
I think it should not be reported as I don't request this feature (in configuration_adv.h)
```cpp
  /**
   * Enable this option if you have more than ~3K of unused flash space.
   * Marlin will embed all settings in the firmware binary as compressed data.
   * Use 'M503 C' to write the settings out to the SD Card as 'mc.zip'.
   * See docs/ConfigEmbedding.md for details on how to use 'mc-apply.py'.
   */
  //#define CONFIGURATION_EMBEDDING
```

### Bug Timeline

Occures after switch from 2.0.9.2 to current bugfix

### Expected behavior

When feature of embedding is not requested, warning should not be reported.

### Actual behavior

Warning reported.

### Steps to Reproduce

Build AVR configuration (any)

### Version of Marlin Firmware

commit b07887687e

### Printer model

not relevant

### Electronics

MKS_GEN_L, any AVR based

**Comment by sjasonsmith** [comment]
I've modified the check to make sure the feature was enabled before generating any warnings.
