### ISSUE TITLE
[BUG] Z Axis moving upwards

### ISSUE THREAD

**Issue by ndk-ender3** [MarlinFirmware/Marlin#23419]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

after installing the newest version of bugfix, my Z axis (when probing and homing) moves upwrds.

If I enable reversing Z axis in the code, I cant complie.

regards

### Bug Timeline

new

### Expected behavior

Z axis moving downwards

### Actual behavior

Z axis moving upwards

### Version of Marlin Firmware

bugfix 2.0.x

### Printer model

ender 3 

### Electronics

4.2.2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by ellensp** [comment]
no Configs, no error messages, needs more information

**Comment by ndk-ender3** [comment]
Z axis moves only upwards, I had to roll back to a previous version.
only error is "c'ant compile" while reversing Z axis in the config file

**Comment by ndk-ender3** [comment]
*

**Comment by LuxInTenebr1s** [comment]
I have the same issue. I can provide any info you need per request.
- SKR 2.0 \w F429
- TMC2209 sensorless homing and probing enabled
- homing works just fine
- probing moves my carriage upwards instead of downwards to the actual probing 
- 2.0.9.3 Marlin

Sensorless probing does not have any direction settings. I've also tried to hack move command within G34 source code to invert moving direction but that didn't work.

**Comment by sajmonSK** [comment]
I have the same problem (as a nice gouge in my PEI sheet can tell). 
SKR 1.4
TMC2209 UART
Piezo sensor (nozzle as probe)
Marlin 2.0.9.3 stable

Z homing works as it should, but during G34 the Z axis moves to the measurement position, moves upward first, then moves downward and actually probes.
It does the same on the other side and the value keeps rising by about 2mm each time, and the X axis gantry ends up skewed. It looks like it is measuring from the position after the extra upward move

**Comment by BigTGaming** [comment]
i am having the same issue with my V2 v4.2.2 and the probe keeps triggering without touching the bed

**Comment by Seelenkind** [comment]
configuration.h

either ... or ,

if black and white cable is plugged into Z endstop
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
//#define USE_PROBE_FOR_Z_HOMING

if the black and white cable is connected to the probe
//#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define USE_PROBE_FOR_Z_HOMING

**Comment by ndk-ender3** [comment]
still ongoing

**Comment by thisiskeithb** [comment]
> still ongoing

Even with today’s bugfix? Zip up and attach your configs.

**Comment by ellensp** [comment]
And tell us where you probe is attached to z_min or probe port
