### ISSUE TITLE
[BUG] Incorrect `STRING_DISTRIBUTION_DATE` in Marlin 2.0.9.3

### ISSUE THREAD

**Issue by DominikPalo** [MarlinFirmware/Marlin#23414]
### Bug Description

It seems that `STRING_DISTRIBUTION_DATE` for v2.0.9.3 is not set correctly. According to the https://github.com/MarlinFirmware/Marlin/commit/e17d710c5c4c96e069f64854e3fcdb77abcf90e1 diff, it has been updated only in the `Marlin/Version.h` template, not in the `Marlin/src/inc/Version.h` file. Therefore, extensions like ABM shows incorrect date:

![image](https://user-images.githubusercontent.com/1623257/147851286-2f6dbf00-f071-4778-8c98-a4824e116df5.png)

### Version of Marlin Firmware

2.0.9.3

**Comment by thisiskeithb** [comment]
PR submitted: https://github.com/MarlinFirmware/Marlin/pull/23444
