### ISSUE TITLE
[BUG] Cooling fan full speed after 2.0.9.3 update

### ISSUE THREAD

**Issue by marlinfwgeek** [MarlinFirmware/Marlin#23459]
### Did you test the latest `bugfix-2.0.x` code?

Yes, the issue still exists with the latest 'bugfix-2.0.x' code

### Bug Description

After updating to 2.0.9.3, the cooling fan on both my Anet A8s and my Anet A8 Plus run at full speed after power on, even though '0%' is displayed for fan speed. If I move the cooling fan speed setting to 100% and then back to 0%, the fan then turns off but will go back to 100% if the printer is power cycled or experiences a serial reset.

### Bug Timeline

First started with updating to 2.0.9.3 - was not an issue in 2.0.9.2 or prior (going back to at least 2.0.7 or earlier)

### Expected behavior

Cooling fan should be off at power on and/or when setting is set to 0%

### Actual behavior

Print cooling fan runs at 100% even though the setting is set to 0%

### Steps to Reproduce

After power on or a serial reset of the printer, the print cooling fan runs at 100%

### Version of Marlin Firmware

2.0.9.3

### Printer model

Anet A8 and Anet A8 Plus

### Electronics

Stock electronics

### Add-ons

Anet A8 full graphics display

### Bed Leveling

No Bed Leveling, I do this manually

### Your Slicer

Cura

### Host Software

Cura

### Additional information & file uploads

Nightly build and 2.0.9.3 release configs for both the A8 Plus and A8 uploaded

**Comment by descipher** [comment]
Please attach configuration files.

**Comment by marlinfwgeek** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7816835/Marlin.zip)
Here's the config for my A8 Plus using the latest nightly build

**Comment by marlinfwgeek** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7816847/Configuration.zip)
Here's the config for my A8s using the 2.0.9.3 build

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/23418
