### ISSUE TITLE
[BUG] (downloaded file)

### ISSUE THREAD

**Issue by pasikov123** [MarlinFirmware/Marlin#23465]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

The firmware is not downloaded when you click on the link 2.0.x.zip

https://github.com/MarlinFirmware/Marlin/archive/2.0.x.zip

### Bug Timeline

new bug

### Expected behavior

downloaded file

### Actual behavior

dont loaded

### Steps to Reproduce

1. go site https://marlinfw.org/meta/download/
2. click 2.0.x.zip

### Version of Marlin Firmware

2.0.9.3

### Printer model

Anycubic Kossel Delta

### Electronics

No

### Add-ons

marlin 2.0.8

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

go site

![1](https://user-images.githubusercontent.com/73814472/148394288-3a600a60-8bd9-42b6-8660-ee52f3fe6e28.PNG)

click 
![2](https://user-images.githubusercontent.com/73814472/148394312-7cc87848-dd1f-43c5-8e32-27a5ba7a34a8.PNG)

dont loaded

**Comment by thisiskeithb** [comment]
Cannot reproduce.
