### ISSUE TITLE
[BUG] Mistakes in command M605 S3?

### ISSUE THREAD

**Issue by radek8** [MarlinFirmware/Marlin#23468]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

File: Marlin/blob/bugfix-2.0.x/Marlin/src/gcode/control/M605.cpp
Incidentally, is missing on line 103 "break;" ?
Maybe I'm wrong, I'm not a programmer.

![image](https://user-images.githubusercontent.com/46979052/148554481-fae882e8-2c02-45a1-a462-1348a793292d.png)

### Version of Marlin Firmware

Marlin bugfix 2.0.x

**Comment by ellensp** [comment]
Please see https://stackoverflow.com/questions/6330114/do-you-need-break-in-switch-when-return-is-used
