### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by FlavienDriard** [MarlinFirmware/Marlin#23471]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Arduino IDE create a compilation error on Creality_DWIN.cpp due to CUSTOM_MACHINE_NAME which is not defined.

### Expected behavior

Arduino IDE compile without any error.

### Version of Marlin Firmware

Marlin-CrealityDwin2.0_Bleeding

### Printer model

Creality Ender 7

### Electronics

STM32F103RE

### Additional information & file uploads

 I replace:
     onStatusChanged(CUSTOM_MACHINE_NAME " Ready");

By:
     #if defined(CUSTOM_MACHINE_NAME)
	onStatusChanged(CUSTOM_MACHINE_NAME " Ready");
     #endif

**Comment by ellensp** [comment]
Marlin-CrealityDwin2.0_Bleeding is not Marlin branch this is InsanityAutomation branch of Marlin, any bug reports in that branch must be made on that branch
