### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by FlavienDriard** [MarlinFirmware/Marlin#23470]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I use Arduino IDE as compiler, and I got error on "probe.h" between line 199 and line 208.

### Expected behavior

I expect Arduino IDE to compile without error.

### Actual behavior

I succeed to compile without error in the file "probe.h"

### Steps to Reproduce

1. change <SPI.h> to "SPI.h" because
2. change the lines from 198 to 209 as in attached file.

### Version of Marlin Firmware

Marlin-CrealityDwin2.0_Bleeding

### Printer model

Creality Ender 7

### Electronics

STM32F103RE

### Additional information & file uploads

[](url
[probe.h.txt](https://github.com/MarlinFirmware/Marlin/files/7830679/probe.h.txt)
)

It is my first conpribution on github, I don't know excatly how to proceed, but I want the time I spend to be useful for others.
And I hope people can enjoy full compilation on Arduino IDE without any error at the end!

**Comment by ellensp** [comment]
Marlin-CrealityDwin2.0_Bleeding is not Marlin branch this is InsanityAutomation branch of Marlin, any bug reports in that branch must be made on that branch
