### ISSUE TITLE
[FR] WiFi Support for trigorilla pro motherboard

### ISSUE THREAD

**Issue by sbarajas** [MarlinFirmware/Marlin#23486]
### Is your feature request related to a problem? Please describe.

I need to use a Wifi module in the motherboard trigorilla pro but it isn't supported

### Are you looking for hardware support?

The motherboard trigorilla pro has a WiFi connector:
![imagen](https://user-images.githubusercontent.com/9154622/148680708-969a3c51-eca7-41fc-9f18-c23e4e2119d3.png)
for an esp8266 WiFi module like that:
![imagen](https://user-images.githubusercontent.com/9154622/148680774-5b75922a-41e0-45a0-8560-e464e608ea51.png)
But in the motherboard definition in Marlin isn't defined de serial port to use it

### Describe the feature you want

I want to connect by wifi to the trigorilla mother board using the ESP3D graphical interface

**Comment by ellensp** [comment]
Its a serial device.
PB11 is USART3_RX, PB10 USART3_TX is on that connector
In Marlin all you do is enable the uart
#define SERIAL_PORT_2 3  and set the baud rate, #define BAUDRATE_2 115200
This does not require anything additional.

**Comment by sbarajas** [comment]
Is not enougth,
I have tried this:
```cpp
/**
 * Select a secondary serial port on the board to use for communication with the host.
 * Currently Ethernet (-2) is only supported on Teensy 4.1 boards.
 * :[-2, -1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT_2 3
#define BAUDRATE_2 115200   // Enable to override BAUDRATE
```
And this not enable de wifi module

![imagen](https://user-images.githubusercontent.com/9154622/148810046-4a0b8b88-62eb-4222-8cbb-3534a415d4d0.png)
