### ISSUE TITLE
kHz

### ISSUE THREAD

**Issue by jwrw** [MarlinFirmware/Marlin#23500]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

It's a bit of trivia but I saw a load of changes to make kHz -> KHz.  'kHz' is the CORRECT SI spelling for kilohertz (even if it looks weird). Just to confuse, MHz and GHz are correct for megahertz and gigahertz.

### Version of Marlin Firmware

N/A

**Comment by tome9111991** [comment]
This ?
https://github.com/MarlinFirmware/Configurations/commit/c57f74b8369b9bce073135f07ce2a6e353b3403e

**Comment by jwrw** [comment]
That should have a similar issue raised.  But no, there is a committed change in this repo with the same name 'kHz => KHz'
It's 02b29c0

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/23512

**Comment by thisiskeithb** [comment]
Aaaand merged! https://github.com/MarlinFirmware/Marlin/pull/23512
