### ISSUE TITLE
[BUG] On Cancel from Screen,  Extruder ignotres ABL home

### ISSUE THREAD

**Issue by dredvard** [MarlinFirmware/Marlin#23509]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

My extruder has crashed into my bed on multiple occasions during the home sequence, ignoring the home limit.  Unclear if this happens on the G28 or on the G1 sequence. 

My Gcode is as follows:

```
M104 S160  ; Start warming extruder to 160
M190 S{material_bed_temperature_layer_0} ; Wait for Heat Bed temperature
G28        ; Home all axes
G29 L1     ; Load UBL
G29 J2     ; 4-point level
G92 E0     ; Reset Extruder

G1 Z2.0 F3000  
```

### Expected behavior

Not crash

### Actual behavior

Crashes into Bed

### Steps to Reproduce

 I think this is the sequence when it occurs (not looking to test it again as my bed is damaged and my bearings now have slop)

1.  I cancel a job from the Ender 3 touch screen.  
2.  I  start a job with my Cura (using Octoprint)

### Version of Marlin Firmware

E3V2-UBL-BLTouch-10x10-v4.2.2-v2.0.1

### Printer model

Ender 3 V2

### Electronics

3DTouch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

https://github.com/Jyers/Marlin

**Comment by thisiskeithb** [comment]
We can’t support forks of Marlin. Please file an issue in Jyers’ fork: https://github.com/Jyers/Marlin/issues
