### ISSUE TITLE
[BUG] CR10S onboard SD doesn't work

### ISSUE THREAD

**Issue by Gankman77** [MarlinFirmware/Marlin#23518]
### Did you test the latest `bugfix-2.0.x` code?

Yes, there is no Change :(

### Bug Description

I tried standard settings for CR10S V1, and a previous (solved) trouble report to change //#define SDCARD_CONNECTION LCD to #define SDCARD_CONNECTION ONBOARD and still having issues.  Any Help would be appreciated

### Bug Timeline

New Issue trying to upgrade from original firmware to Marlin 2.0.9.3

### Expected behavior

I expected to be able to use my boards onboard SD card to start jobs on my printer

### Actual behavior

"NO SD" is displayed regardless of booting up with SD card inserted, or inserting after bootup.

### Steps to Reproduce

1. Upload edited and compiled 2.0.9.3 to CR10S (v1 2560)
2. reset EEPROM
3. Power ON Printer
4. Select Menu, scroll down to SD Card
5. "NO SD" is displayed
6. Remove and Remount SD Card, still "NO SD"
7. Option to Init. SD Card is missing

### Version of Marlin Firmware

2.0.9.3

### Printer model

HICTOP Creality CR10S 

### Electronics

Stock MB

### Add-ons

BLTOUCH, Titan DD Extruder

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Additional information & file uploads

[CR10S_Marlin2.0.x Config.zip](https://github.com/MarlinFirmware/Marlin/files/7865207/CR10S_Marlin2.0.x.Config.zip)

**Comment by Gankman77** [comment]
Trying a combination from a few issues that were (supposedly) fixed previosuly ** 
 //#define SDCARD_CONNECTION LCD to #define SDCARD_CONNECTION ONBOARD, Then uncommented  //#define SD_DETECT_STATE_HIGH

**Comment by Gankman77** [comment]
for my V1 2560 board, I had to edit the following to resolve my issue:
//#define SDCARD_CONNECTION LCD to #define SDCARD_CONNECTION ONBOARD, Then Changed (uncommented) //#define SD_DETECT_STATE_HIGH to #define SD_DETECT_STATE_HIGH

**Comment by thinkyhead** [comment]
`SDCARD_CONNECTION` doesn't apply to AVR boards.
