### ISSUE TITLE
[BUG] Bug in Thermal Runaway. No message on LCD

### ISSUE THREAD

**Issue by roel8032** [MarlinFirmware/Marlin#23525]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Bug in Thermal Runaway. When it happens, the usual beeps. But no message on LCD. So you can't see what caused it. The nozzle retreats. Looks new to me. You can test this if you place a switch in the cable to bed or nozzle heater.

### Expected behavior

Trigger alarm and report on LCD as usual.

### Actual behavior

No message on LCD.

### Version of Marlin Firmware

2.0.9.3

### Printer model

Infitary M506

### Electronics

Stock board

### Bed Leveling

ABL 3-point

### Your Slicer

Cura

**Comment by thinkyhead** [comment]
You have provided no helpful information such as your configuration or your printer or LCD model, so this is not actionable.

**Comment by sbarajas** [comment]
I have this problem too.

Printer Model: Anycubic Predator
Electronics: Trigorilla Pro
Version: 2.0.9.3
Step to Reproduce: When the target nozzle temperature is higher than 200 Celsius Degrees

In the screen appears a message that says something that the printer is halted because a thermal runaway problem

**Comment by roel8032** [comment]
If the alarm is triggered, the printer will be reset. So when you arrive at the printer, there is no message on the LCD.

**Comment by roel8032** [comment]
![20220119_101801](https://user-images.githubusercontent.com/6228110/150122177-adc1078f-e32e-47c3-a900-fe64cc9c01c6.jpg)

In Marlin 2.0.9.2 this screen appears. It keeps on beeping. No retreat of the nozzle.

**Comment by mzhu1113** [comment]
I have this problem as well testing 2.0.9.3 on a test printer for validation before deploying to fleet.

Forced printer to trigger a thermal runaway condition via both E0 and Bed, printer will beep and briefly display the appropriate message while retreating the toolhead away from current position to XY max. The printer will reset once toolhead parks.

SOFT_RESET_VIA_SERIAL and SOFT_RESET_ON_KILL are not enabled in configuration_adv

CR10StockDisplay
3 linear axis
Typical Ender 3 setup with SKR E3 Mini V2.0 board (STM32F103RC_btt_maple).

Hope this is enough information.

**Comment by roel8032** [comment]
Problem is fixed yet?
