### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by jrod8236** [MarlinFirmware/Marlin#23534]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The bl touch will go to the center of the bed as normal when I try to level the bed. It will move up 10mm then deploy and stow the probe 3 times without moving then do nothing and won't level the bed. It does the same thing when trying to home the z axis.

### Bug Timeline

Today

### Expected behavior

I expected it to level the print bed as normal.

### Actual behavior

It will home the stow and deploy 3 times before not doing anything else

### Steps to Reproduce

unsur
[Zip for error.zip](https://github.com/MarlinFirmware/Marlin/files/7876085/Zip.for.error.zip)
e

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

ender 3 v2

### Electronics

400mm X 400mm print bed

### Add-ons

BL Touch

### Bed Leveling

ABL Bilinear mesh

### Host Software

SD Card (headless)

### Additional information & file uploads

[Zip for error.zip](https://github.com/MarlinFirmware/Marlin/files/7876092/Zip.for.error.zip)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
marlin thinks your probe is permanently triggered
probably became you have the probe plugged into the bl touch port yet enabled Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN dispute it clearly not being plugged into z_min
