### ISSUE TITLE
[FR] Marlin command to switch between onboardSD and onboardUSB 

### ISSUE THREAD

**Issue by Guilouz** [MarlinFirmware/Marlin#23551]
### Is your feature request related to a problem? Please describe.

MULTI_VOLUME feature is actually available only in Marlin mode. It would be good to add possibility to switch between onbardSD and onboardUSB with Marlin command.

It will be a good addition specially for BigTreeTech screen users. Because there is no other way to communicate with Marlin than with gcodes while screen is in Touch Mode.

### Describe the feature you want

Marlin command to switch between onboardSD and onboardUSB when MULTI_VOLUME is enabled.

**Comment by thisiskeithb** [comment]
Added in #23780
