### ISSUE TITLE
[FR] fysetc v2.1 on mks gen L not working

### ISSUE THREAD

**Issue by coolum86** [MarlinFirmware/Marlin#23555]
### Is your feature request related to a problem? Please describe.

i have fysetc 12864 mini v2.1 and im trying to get it to work with my mks gen L 1.4 for my anet printer. the panel ligths up and rgb test works but no text is displayed. i got to a point wher it was displayed very very dim but i dont know how i got there. please help.

### Describe the feature you want

fysetc on mks gen L

**Comment by ellensp** [comment]
It definitely is supported. so this is not a feature request

It should just plug in.

I have a ramps (plus lcd  board with keys on the right just like the mks gen L) and the fysetc mini v2.1  
Your board is mostly ramps compatible, exp1 and exp2 use identical pins

I enabled #define FYSETC_MINI_12864_2_1   

It works straight away

This lcd does have contrast settings
Try sending g-code M250 C220  
And then save it with M500

**Comment by coolum86** [comment]
> It definitely is supported. so this is not a feature request
> 
> It should just plug in.
> 
> I have a ramps (plus lcd board with keys on the right just like the mks gen L) and the fysetc mini v2.1 Your board is mostly ramps compatible, exp1 and exp2 use identical pins
> 
> I enabled #define FYSETC_MINI_12864_2_1
> 
> It works straight away
> 
> This lcd does have contrast settings Try sending g-code M250 C220 And then save it with M500

i did m250 but what is c220? and where do i put them? conditionals lcd H?

**Comment by ellensp** [comment]
It g-code. The codes the printer runs on
You send it to the printer from a control program
M250 is the gcode, C220 is the option to the gcode ie set contrast to 220 
You send both together as one line.

https://marlinfw.org/docs/gcode/M250.html

**Comment by ellensp** [comment]
It g-code. The codes the printer runs on
You send it to the printer from a control program, such a pronterface or console on octoprint.
M250 is the gcode, C220 is the option to the gcode ie set contrast to 220 
You send both together as one line.

M250 documattion https://marlinfw.org/docs/gcode/M250.html
overview of gcodes https://www.youtube.com/watch?v=2TByiMNduss 
overview of pronterface https://www.youtube.com/watch?v=lwENk8bxtU4

**Comment by coolum86** [comment]
> It g-code. The codes the printer runs on You send it to the printer from a control program, such a pronterface or console on octoprint. M250 is the gcode, C220 is the option to the gcode ie set contrast to 220 You send both together as one line.
> 
> M250 documattion https://marlinfw.org/docs/gcode/M250.html overview of gcodes https://www.youtube.com/watch?v=2TByiMNduss overview of pronterface https://www.youtube.com/watch?v=lwENk8bxtU4

ok so i got 2 saves one with my printer settings and the lcd worksd now but cant control it. the second save is only the basic functions but the lcd works and controls work its just not made for my printer settings and doesnt have all of the files. i tried copying and pasting my setting from the one file over but ended up in a bunch of errors. any suggestions?

**Comment by coolum86** [comment]
what .h file has the lcd controls?

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
