### ISSUE TITLE
[BUG] Ender 5 Pro v4.2.2 - STM32F103RET6 Visual Studio Fail

### ISSUE THREAD

**Issue by SJB-gif** [MarlinFirmware/Marlin#23588]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I am trying to update my New Ender 5 Pro firmware from v1.0.2 (stock from manufacturer) to Marlin v2.0.9.3 from marlinfw.org However the build failed when attempting the Auto Marlin Build extension in Visual Studio.
The result is the same when using the bugfix-2.0.x code.
[Visual Studio Terminal Error.zip](https://github.com/MarlinFirmware/Marlin/files/7917655/Visual.Studio.Terminal.Error.zip)

### Bug Timeline

New

### Expected behavior

It should build normally, as the no files have been edited (except replacement of config and config_adv from examples)

### Actual behavior

Build Fails
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL.cpp:30:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2002:6: error: #error "FAN_SOFT_PWM is required. Enable it to continue."
 2002 |     #error "FAN_SOFT_PWM is required. Enable it to continue."
      |      ^~~~~

### Steps to Reproduce

1. Download Marline v2.0.9.3 from "marlinfw.org"
2. Copied all files from the Marline v2.0.9.3 configurations for the Ender 5 Pro from "E:\Downloads\Configurations-release-2.0.9.3.zip\Configurations-release-2.0.9.3\config\examples\Creality\Ender-5 Pro\CrealityV422" into the folder "C:\Marlin-2.0.x\Marlin" 
3. Opened Visual Studio and attempted a build using the Auto Marlin Build extension

### Version of Marlin Firmware

v1.0.2

### Printer model

Ender 5 Pro

### Electronics

Stock

### Add-ons

none

### Your Slicer

Cura

**Comment by ellensp** [comment]
error:r "FAN_SOFT_PWM is required. Enable it to continue

Do as it says

This has already been fixed in bugfix https://github.com/MarlinFirmware/Configurations/blob/bugfix-2.0.x/config/examples/Creality/Ender-5%20Pro/CrealityV422/Configuration.h#L2880

**Comment by SJB-gif** [comment]
Thanks!
