### ISSUE TITLE
[BUG] Extruder does not move to the correct position when using Firmware XYZ Offsets 

### ISSUE THREAD

**Issue by stabbs** [MarlinFirmware/Marlin#23595]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Extruders are not moving to the correct position when using firmware xyz offset.  To demonstrate I printed 4 50mm towers at the same time, 1 tower per nozzle.  When using firmware offsets the prints come out slanted in both the x & y direction and I suspect the z offset is off as well.  I printed the same file using Slic3r's XY offset and each tower printed vertically.

Sorry for the poor image quality but the slanted prints are xyz firmware offset and the vertical prints are Slic3r xy offset (still using firmware z offset)

![Slanted Prints](https://user-images.githubusercontent.com/2372764/150649295-5bf2634a-8678-4824-b9af-489dd93290b3.jpg)

### Bug Timeline

Unsure, just realized it is happening

### Expected behavior

Print 4 50mm towers at the same time, one tower per nozzle, using firmware offsets.  Each layer should be vertically stacked

### Actual behavior

50mm towers are not vertically stacked, they seem to evenly slant in the x- and y- direction.  I suspect the z offset is also not moving to the correct position but I haven't figured out how to test this yet.

### Steps to Reproduce

Configuration:
1. set to 4 extruders
#define EXTRUDERS 4

2. set xyz offset:
#define HOTEND_OFFSET_X { 0.0, 0.35, 12.70, 12.9 } // (mm) relative X-offset for each nozzle
#define HOTEND_OFFSET_Y { 0.0, 16.20, 0.5, 16.35 }  // (mm) relative Y-offset for each nozzle
#define HOTEND_OFFSET_Z { 0.0, -0.820, -0.07, -0.79 }  // (mm) relative Z-offset for each nozzle

All multiple extruder options in config are left unselected
- NO singlenozzle
- NO MMU
- NO Switching extruder
- NO Mixing extruder
- etc...
Configs:

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/7918971/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/7918988/Configuration_adv.txt)

### Version of Marlin Firmware

2.0.9.2

### Printer model

homebrew

### Electronics

Rambo 1.2

### Bed Leveling

No Bed Leveling

### Host Software

Repetier Host

### Additional information & file uploads

Thanks for the help on this, I'm happy to provide more info if needed to help sort this out.

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
