### ISSUE TITLE
A lot of bugs on MKS UI in the Bugfix branch

### ISSUE THREAD

**Issue by DvoraNoob** [MarlinFirmware/Marlin#23608]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

After the PR: 23464 merged my encoder doesn't work more, and the screen stays yellow

The TFT_LVGL_UI Z Offset Wizard have 2 problems. First one, compile error  because the name of variable. Second after I click on Wizard Menu and in sequence I click on Leveling Offset Probe Menu my board reset.

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.0.x (Jan 23 2022 18:51:17) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

### Electronics

Robin Nano V3

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

**Comment by descipher** [comment]
try disabling SPI_DMA_TC

pins_MKS_ROBIN_NANO_V3_common.h

  372   #define USE_SPI_DMA_TC <-Comment this line

**Comment by DvoraNoob** [comment]
> try disabling SPI_DMA_TC
> 
> pins_MKS_ROBIN_NANO_V3_common.h
> 
> 372 #define USE_SPI_DMA_TC <-Comment this line

I tried it, I got a compilation error

**Comment by descipher** [comment]
Not good. That should not happen based on the pins file. 
What line number(s) failed.

**Comment by DvoraNoob** [comment]
> ‎Não é bom. Isso não deve acontecer com base no arquivo pinos. ‎‎ Qual número de linha(s) falhou.‎

Now compiled, but I'll try before confirm.

**Comment by DvoraNoob** [comment]
> Not good. That should not happen based on the pins file. What line number(s) failed.

I got a bootloop.

**Comment by descipher** [comment]
Definitely broken then, you should be able to turn it off.

**Comment by DvoraNoob** [comment]
> ‎Definitivamente quebrado, então, você deve ser capaz de desligá-lo.‎

I went back to Marlin Branch

**Comment by DvoraNoob** [comment]
Only bugfix has this problems

**Comment by descipher** [comment]
Confirmed bug, just repeated bootloop on bugfix_2.0.x with configuration.h as:
LCD is MKS TS35 V2.0

#define BOARD_MKS_ROBIN_NANO_V2
#define SERIAL_PORT 3
#define SERIAL_PORT_2 1
#define TFT_GENERIC
#define TFT_INTERFACE_SPI
#define TFT_RES_480x320
#define TFT_LVGL_UI
#define SDSUPPORT

**Comment by DvoraNoob** [comment]
> 

I'll need change to V3 because my board is a v3, but I have v2 too, but without use

Can I use USB?

**Comment by descipher** [comment]
The boot loop on V2 demonstrates that the SPI code is broken since V2 does not have USE_SPI_DMA_TC defined. 
Question: Did you update the assets?

**Comment by DvoraNoob** [comment]
> 
With TFT-Generic settings I got a compilation error

Yes, I update the assets everytime.

**Comment by descipher** [comment]
Please upload your config files.

**Comment by DvoraNoob** [comment]
> Please upload you config files.

with generic tft or ts35-v2?

**Comment by descipher** [comment]
TST35

**Comment by DvoraNoob** [comment]
https://1drv.ms/u/s!AlJymIpivUgt0CF9jtnn1LigVlne?e=xLm8A1

**Comment by DvoraNoob** [comment]
FIXED
