### ISSUE TITLE
Needs info on current branches and tags

### ISSUE THREAD

**Issue by clefranc** [MarlinFirmware/Marlin#2360]
I've been away a little while (not that my presence have impact or big effect on Marlin) and was wondering on the purpose of the new branches and tags:

**Branches**
1.0.X
dev

**Tags**
1.1
1.0.2-1

**Comment by Wackerbarth** [comment]
See #2244.
The 1.1 tag is the base of the 1.1 series.
The 1.0.2-1 tag was applied to a patch made to 1.0.2.  There is a difference of opinion as to whether this tag should have been used or if the 1.0.2 tag should have been moved to correct the issue.  In either case, as our procedures improve such issues will fade into the background.

As for the branches, it was discussed and decided that the idea of having "Release", "Implementation" and "Development" as THE branches was an oversimplification. As the project matures, it is very likely that we will need to support more than one "Release" with ongoing patches.  Particularly as we introduce significant changes/improvements that affect the configuration system, there will be users who are unwilling to track those volatile changes before they really stabilize. At the same time, it will be important to correct some issues for them as well as fixing them for the future development. Hence, "1.0.x" represents the "permanent" name for the current Release branch. When we get to our first ReleaseCandidate for the 1.1 series, another "1.1.x" branch will be assigned.
That leaves "Release" to be an alias available to jump to the current release without orphaning the previous ones.

"dev" is a cleaned up rebase of the commit stream merged into Development. The Github PR merge mechanism generates a hopeless tangle of commit history that obscures the ability for someone to understand just which changes apply to a particular feature. (It reminds me of coding practices from the 1970's) It is somewhat an artifact of the distributed nature permitted by Git. However, by reorganizing the sequence of commits, we have a cleaner representation to move forward into our ReleaseCandidates. "dev" is this shadowing branch. It will become the RC branch when we are ready to have one.
