### ISSUE TITLE
[BUG] (SD problem on skr pro V1.2)

### ISSUE THREAD

**Issue by Enzo-Enz** [MarlinFirmware/Marlin#23617]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi
Marlin 2.0.9.3 doesn't show the file on the SD card
I use BTT SKR PRO V1.2 as motherboard and generic delta configuration for delta printer
I have enabled enabled SDSUPPORT and SD_CHECK_AND_RETRY but when I click on "print from media" It doesn't show the file on SD card.I test bugfix version but the issue still exist
there are g-codes on SD card

here are the pictures
![image](https://user-images.githubusercontent.com/75531691/151019994-5bcdd330-3260-4a29-9822-1a8beed2199b.png)

![image](https://user-images.githubusercontent.com/75531691/151020024-026390d8-6279-4087-bd3d-7857772165c2.png)
![image](https://user-images.githubusercontent.com/75531691/151020063-d3240e05-e3ae-483e-b560-71e1fa35c6ae.png)

### Bug Timeline

new

### Version of Marlin Firmware

2.0.9.3

### Printer model

DIY delta printer

### Electronics

skr pro v1.2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by borland1** [comment]
Not sure which LCD you have.  Maybe your LCD display setup is for REPRAP_DISCOUNT_SMART_CONTROLLER which has SD-card reader. 

You can enable the onboard SD-card slot in Configuration_adv.h with this define...
  
`  #define SDCARD_CONNECTION ONBOARD`

```
       /**
       * Set this option to one of the following (or the board's defaults apply):
       *
       *           LCD - Use the SD drive in the external LCD controller.
       *       ONBOARD - Use the SD drive on the control board.
       *  CUSTOM_CABLE - Use a custom cable to access the SD (as defined in a pins file).
       *
       * :[ 'LCD', 'ONBOARD', 'CUSTOM_CABLE' ]
       */
1629   //#define SDCARD_CONNECTION LCD
```

**Comment by thisiskeithb** [comment]
> I use BTT SKR PRO V1.2 as motherboard and generic delta configuration for delta printer
I have enabled enabled SDSUPPORT and SD_CHECK_AND_RETRY

Are there any other changes? Please attach the modified configs you used to test the latest bugfix.

**Comment by Enzo-Enz** [comment]
I enabled `#define SDCARD_CONNECTION LCD` the issue fixed but for my XYZ printer(ramps+mega2560+12864 lcd with SD-card reader+marlin 2.0.9.3) I just enabled `SDSUPPORT` and `SD_CHECK_AND_RETRY` and there was no issue!
also there was no issue with previous version(2.0.9.2) with this settings(`SDSUPPORT` and `SD_CHECK_AND_RETRY`)for my delta

[generic delta.zip](https://github.com/MarlinFirmware/Marlin/files/7943533/generic.delta.zip)


> > I use BTT SKR PRO V1.2 as motherboard and generic delta configuration for delta printer
> > I have enabled enabled SDSUPPORT and SD_CHECK_AND_RETRY
> 
> Are there any other changes? Please attach the modified configs you used to test the latest bugfix.

**Comment by thinkyhead** [comment]
Would you be able to test some `bugfix-2.0.x` commits to narrow this down?

The strategy is to find a commit from some point in the "distant" past where the feature works. Then, test a commit from halfway between that date and today…. And then you keep going to the commit half-way in between your "known to work" commit and your "known to be broken" commit until you find the exact day where it broke.

If you started from a point 256 commits in the past, it would take no more than 8 tests to find the exact commit that broke it.

**Comment by thisiskeithb** [comment]
> I enabled `#define SDCARD_CONNECTION LCD` the issue fixed

[I explained this already in your last issue](https://github.com/MarlinFirmware/Configurations/issues/652#issuecomment-1008282148). This is not a bug.

> but for my XYZ printer(ramps+mega2560+12864 lcd with SD-card reader+marlin 2.0.9.3) I just enabled `SDSUPPORT` and `SD_CHECK_AND_RETRY` and there was no issue!

Awesome!

> also there was no issue with previous version(2.0.9.2) with this settings(`SDSUPPORT` and `SD_CHECK_AND_RETRY`)for my delta

Great!
