### ISSUE TITLE
G29 J and BL Touch issue

### ISSUE THREAD

**Issue by daredevil-ferreira** [MarlinFirmware/Marlin#23613]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When I launch a G29 J command,
First point is measured correctly, then the hotend moves to the second point without retracting the bl-touch to its neutral position.
Second point generates an error.

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin 2.0.9_DW7.4.4

### Printer model

Creality CR10S Pro

### Electronics

Board V2.4.1 

### Add-ons

+ BLTouch

### Bed Leveling

UBL Bilinear mesh

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/7933311/config.zip)

**Comment by ellensp** [comment]
This is the insanity automation fork of Marlin. You have to get support for that branch from that branch on their github.
