### ISSUE TITLE
[FR] Ender3 V2 - DACAI screen support

### ISSUE THREAD

**Issue by Li-Haung** [MarlinFirmware/Marlin#23621]
### Is your feature request related to a problem? Please describe.

I got a new ender3 V2 this year,but Creality replaced DWIN screen with DACAI.
Can add support for this screen ?

### Describe the feature you want

Add support for DACAI screen 

### Additional context

![20220126_102212](https://user-images.githubusercontent.com/32626281/151095278-48e313ec-7c4b-4954-afcb-4cd73392b1b9.jpg)

**Comment by ellensp** [comment]
Some work has already been done on this see https://github.com/MarlinFirmware/Configurations/issues/645#
This screen is also supplied on Ender 3 S1

**Comment by mriscoc** [comment]
This display emulates some of the functionalities of the old DWIN display but its API is not exactly the same. I found the programming interface for the old DWIN, but not for this new unit. Have you found some information about it?

**Comment by ellensp** [comment]
the PR to support these ass been added. https://github.com/MarlinFirmware/Marlin/pull/23822
closing.
