### ISSUE TITLE
[bug] undefinedError: Processing LPC1769 debug environment with PlatformIO

### ISSUE THREAD

**Issue by tgioiosa** [MarlinFirmware/Marlin#23635]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Started getting this undefinedError: Processing LPC1769 Debug when clicking PIO Debug to debug Marlin firmware. 
Odd thing is that other projects compile and debug just fine, so it's not a PlatformIO or VS Code issue.

The problem seems caused by the extra script “pre:buildroot/share/PlatformIO/scripts/common-cxxflags.py” in the Marlin project, and inside there’s a test to decide whether to append “/debug” to the ‘BUILD_DIR’.
It checks if doing a debug build, but not if UPLOAD is jlink or stlink and appends “/debug” to the ‘BUILD_DIR’.

I found that with these two lines present,

```
if env.GetBuildType() == “debug” and env.get(‘UPLOAD_PROTOCOL’) not in [‘jlink’, ‘stlink’]:
env[‘BUILD_DIR’] = ‘$PROJECT_BUILD_DIR/$PIOENV/debug’
```
then the .json files in the .vscode folder do not automatically update when the project is unloaded/re-loaded. This doesn’t seem right, and then launch.json won’t know about the changed build directory to find files it needs.

If I prevent the second line with the re-define of BUILD_DIR, then the .json files in the .vscode folder do automatically update when the project is unloaded/re-loaded!
Since my Marlin project uses debug_tool=custom and upload_protocol=custom, I thought to add ‘custom’ to the if statement expression like this:

```
if env.GetBuildType() == “debug” and env.get(‘UPLOAD_PROTOCOL’) not in [‘jlink’, ‘stlink’, ‘custom’]:
env[‘BUILD_DIR’] = ‘$PROJECT_BUILD_DIR/$PIOENV/debug’
```
That prevented the adding of “/debug” to the BUILD_DIR and guess what? Everything ran perfectly fine.

I'm seeing this problem with Marlin 2.0.8 and also Marlin 2.0.9.2. I also looked at older versions of Marlin back to 2.0.7 (October 2020) and they didn’t have this code to add “/debug” to BUILD_DIR.
So I’m concluding that this addition to “PlatformIO/scripts/common-cxxflags.py” is causing the undefinedError problem when trying to use debugging.

### Expected behavior

Expected PlatformIO to create the debug files for the project successfully and begin the debugging environment in VS Code.

### Actual behavior

The compile phase completes successfully, but when the PlatformIO DEBUG window opens the error occurs and it also erases the contents that the compiler put in the .pio\build\LPC1769 DEBUG folder. Then it reports an error about not finding “idedata.json” since the compiled output folder was erased.

### Steps to Reproduce

1. Setup the Marlin 2.0.9.2 project in PlatformIO and VS Code.
2. Added a "Debug" environment to platformio.ini file.
3. Make all necessary configuration.h and configuration_adv.h changes for my board(MKS-SGEN)
4. Try to compile for the Debug environment.
5. Error occurs. 

### Version of Marlin Firmware

2.0.9.2 and 2.0.8

### Printer model

this is for a custom CNC machine

### Electronics

Makerbase MKS SGEN V1.0 board

### Add-ons

hardware is not really relevant to the problem

### Additional information & file uploads

My changes to the platformio.ini file to add a Debug environment seem to make this problem occur. Mostly because I am defining a "custom" debug and upload option.  I think the “pre:buildroot/share/PlatformIO/scripts/common-cxxflags.py” script should be fixed to include 'custom' in addition to the ‘jlink’ and ‘stlink’ exclusion test.

**Comment by thinkyhead** [comment]
Thanks for the info. Patch applied!
