### ISSUE TITLE
[BUG] mks mini12864 problem with SDCARD CONNECTION LCD

### ISSUE THREAD

**Issue by soroush8266** [MarlinFirmware/Marlin#23637]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have a problem white mks mini12864 v3 when i activate the SDCARD CONNECTION LCD, when i try to enter the main menu,the device stops for one second to bring up the menu ,but if Ido not activate the SDCARD CONNECTION LCD,there is no problem,please help me

### Bug Timeline

old

### Expected behavior

lcd enters the menu without pause and the printer does not stop

### Actual behavior

The lcd enters the menu with a pause and the printer stops for a second

### Version of Marlin Firmware

2.0.9.3

### Printer model

kossel delta

### Electronics

mks sgenl v1+ tmc2208

### Add-ons

tmc2208

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Additional information & file uploads

[New.folder.zip](https://github.com/MarlinFirmware/Marlin/files/7954377/New.folder.zip)

**Comment by thinkyhead** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
