### ISSUE TITLE
[FR] (BTT-SKR-E3-Turbo additional serial port usage)

### ISSUE THREAD

**Issue by mlaci001** [MarlinFirmware/Marlin#23639]
### Is your feature request related to a problem? Please describe.

BTT-SKR-E3-Turbo additional serial port usage

### Are you looking for hardware support?

BTT-SKR-E3-Turbo 

### Describe the feature you want

Hi,
Is it possible to use the DIY serial port on a BTT-SKR-E3-Turbo motherboard? According to the manufacturer, the port parameters are as follows:
SDA2 -> TX2 - P0.10
SCL2 -> RX2 - P0.11
Thanks.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
