### ISSUE TITLE
[BUG] Fysetc S6 Y-Stepper Pins Incorrect

### ISSUE THREAD

**Issue by lachtan86** [MarlinFirmware/Marlin#23634]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The Issue [#23044](https://github.com/MarlinFirmware/Marlin/issues/23044) was resolved incorrectly. It was correct for Board Fysetc S6 V2! Not for FysetC S6 v1.2! 

### Bug Timeline

23044

### Actual behavior

TMC Communication Error for Y Stepper only. M122 receives "Testing Y connection... Error: All LOW"

### Steps to Reproduce

Flash firmware with stock pins files
Reboot
Get TMC Connection Error displayed - M122 shows Testing Y connection... Error: All LOW

### Version of Marlin Firmware

2.0.9.3

### Additional information & file uploads

![S6](https://user-images.githubusercontent.com/7099613/151415529-3b4d4382-217c-4bc4-abf5-fb49b771b4b4.png)

in Marlin/src/pins/stm32f4/pins_FYSETC_S6.h

```
  #ifndef Y_SERIAL_RX_PIN
    #define Y_SERIAL_RX_PIN                 PC4    <---- INCORRECT
  #endif
```

```
  #ifndef Y_SERIAL_RX_PIN
    #define Y_SERIAL_RX_PIN                 PE13    <---- CORRECT
  #endif
```

PC4 pin must be defined in pins_FYSETC_S6_V2_0.h

**Comment by ellensp** [comment]
Yip your correct.  A PR has been created to rectify this

**Comment by ellensp** [comment]
This PR has been merged into bugfix. closing.
