### ISSUE TITLE
Feature Request - LCD displays current print speed in mm/S ?

### ISSUE THREAD

**Issue by mr-sneezy** [MarlinFirmware/Marlin#2364]
There has been discussion on another issue here about the value of the X, Y & Z print position info bar on the Full Graphics LCD displays. This is related to that discussion, in that the relatively useless (while printing) X & Y position fields could be better used (Z position is actually useful).

I have a suggestion that the current printing speed in mm/S might more useful compared to the aforementioned X & Y numbers.
I'm not sure it's even possible to get this info realtime from the current G-code line being run or the calculations done during printing by the Marlin firmware, if not then the request is not possible.
If it is, then the display bar that usually has X, Y & Z data might have...

Speed: 30 mm/S   Z: 000.0

Perhaps more useful, certainly more interesting ??

**Comment by AnHardt** [comment]
For performance reasons the display is updated only ~ once a second.
As "print speed" is a fast changing value, this is as useless as the x,y-coordinates.

**Comment by AnHardt** [comment]
Thinking about it, we could talk about the "given-print-speed" from the G-codes. Displaying the "actual-print-speed" (during acceleration - deacceleration) makes no sense.

**Comment by mr-sneezy** [comment]
That would be fine. My thought is that during long perimeters and during infills etc where given speed doesn't change for many seconds the info might be good to see. I guess I'm thinking of it as confirmation of what you expected to happen, or a value you will change when you see it not doing the best job at that speed.

**Comment by thinkyhead** [comment]
There has also been some discussion of adding a second "debug info" display, accessible with a double-click or click-and-hold, which could display other useful info, including Z, layer number, total filament used, etc.

**Comment by atunguyd** [comment]
Must say I agree with Sneezy on the XY co ordinates being pointless. How about something that shows layer number vs total when doing a print from SD card? It would require that the gcode file is parsed to determine maximum layer but I see that as having much more value then the current XY location.

**Comment by thinkyhead** [comment]
> layer number vs total

Layer height isn't "known" by the firmware, but I suppose it could be gleaned by looking at the average size of several Z moves. Also the total height isn't known either. Some of these features would require a full pre-scan of the GCode, which may take a long time especially when printing from SD, and which can't be enforced on hosts.

**Comment by atunguyd** [comment]
Scott, 

I did not mean layer height but total print height. At the start of the print the firmware could skip to the end of the file and tag backwards till it finds the last Z command. It then uses this as the total height and then could display the z like "9.3/36mm".

On 10 July 2015 01:03:37 SAST, Scott Lahteine notifications@github.com wrote:

> > layer number vs total
> 
> Layer height isn't "known" by the firmware, but I supose it could be
> gleaned by looking at the average size of several Z moves.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MarlinFirmware/Marlin/issues/2364#issuecomment-120170554

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daid** [comment]
> Displaying the "actual-print-speed" (during acceleration - deacceleration) makes no sense.

Actually, I think it does. Displaying the average speed would be quite interesting. So we can check the claims of "I'm printing at 150mm/s!" While in reality acceleration is keeping you back.

Another interesting value to keep track of and display is the average extrusion in mm^3/sec. As the more I learn about materials and machines, this is actually one of the most important values to keep track of.

**Comment by thinkyhead** [comment]
> tag backwards till it finds the last Z command

My Ending GCode moves Z up by 10mm before moving Y to the back of the bed. That would also throw off the total height, but maybe it can look for the last Z move before an E+ move. The problem still exists that host printing can't (yet) supply a total height value.

**Comment by mr-sneezy** [comment]
All good ideas :)
I'm happy to see desired or average speed and Z height :)
The speed would need to be averaged over a few seconds so it made sense per layer (assuming some layers are small).

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
