### ISSUE TITLE
[BUG] BLTouch + Power Loss Recovery printing error: reset the printer and start printing

### ISSUE THREAD

**Issue by resimkulubu** [MarlinFirmware/Marlin#23643]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have bltouch on my printer and when I enable Power Loss Recovery, as soon as it switches to printing, I get this error: reset the printer and start printing.
skr 1.4 turbo
tmc 2209
bigtreetech tft 3.5- v3

When Power Loss Recovery is turned off, it smoothly bed-levels and switches to printing. please do not give up your support

When I make the settings like this, it works, but it starts printing from the beginning.
```cpp
#define POWER_LOSS_RECOVERY
#if ENABLED(POWER_LOSS_RECOVERY)
#define PLR_ENABLED_DEFAULT false // Power Loss Recovery enabled by default. (Set with 'M413 Sn' & M500)
//#define BACKUP_POWER_SUPPLY // Backup power / UPS to move the steppers on power loss
//#define POWER_LOSS_ZRAISE 2 // (mm) Z axis raise on resume (on power loss with UPS)
#define POWER_LOSS_PIN -1 // Pin to detect power loss. Set to -1 to disable default pin on boards without module.
//#define POWER_LOSS_STATE HIGH // State of pin indicating power loss
//#define POWER_LOSS_PULLUP // Set pullup / pulldown as appropriate for your sensor
//#define POWER_LOSS_PULLDOWN
//#define POWER_LOSS_PURGE_LEN 20 // (mm) Length of filament to purge on resume
//#define POWER_LOSS_RETRACT_LEN 10 // (mm) Length of filament to retract on fail. Requires backup power.
```

### Expected behavior

When Power Loss Recovery is turned off, it smoothly bed-levels and switches to printing. please do not give up your support

### Actual behavior

I have bltouch on my printer and when I enable Power Loss Recovery, as soon as it switches to printing, I get this error: reset the printer and start printing.

### Steps to Reproduce

When Power Loss Recovery is turned off, it smoothly bed-levels and switches to printing. please do not give up your support

### Version of Marlin Firmware

Marlin-bugfix-2.0.x

### Printer model

Creality Ender 3 pro

### Electronics

skr 1.4 turbo

### Add-ons

bigtreetech tft 3.5- v3

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Cura

### Additional information & file uploads

[Marlin-bugfix-my.zip](https://github.com/MarlinFirmware/Marlin/files/7963334/Marlin-bugfix-my.zip)

**Comment by descipher** [comment]
Well not sure this is a bug ...
#define PLR_ENABLED_DEFAULT **false** <- is it disabled 
Send gcodes
M413 S1
M500 
Check it with M413
Close the report if it works.
