### ISSUE TITLE
[BUG] Missing PID menus

### ISSUE THREAD

**Issue by rq3** [MarlinFirmware/Marlin#23644]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

After successfully compiling and installing the lates bugfix, the PID tuning menus are missing, even though they are enabled in configuration.h

Using Color_UI for the first time.

### Bug Timeline

New. Release 2.0.9 with Classic_UI was OK

### Expected behavior

I expect the PID menus to appear under Configuration/Advanced Configuration

### Actual behavior

The menus are not available.

### Steps to Reproduce

1) Compile and install latest bugfix with Color_UI interface
2) Look for PID menus

### Version of Marlin Firmware

latest bugfix

### Printer model

Anycubic Predator

### Electronics

Stock

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

**Comment by jmz52** [comment]
Color UI does not change menu structure
Code I have is 18 days old, but PID settings are present in
Configuration -> Advanced Settings -> Temperature

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
