### ISSUE TITLE
[BUG] HotBed Led Flashing extremely fast on my anet A8

### ISSUE THREAD

**Issue by guanaco0403** [MarlinFirmware/Marlin#23650]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi,
I installed Marlin 2.0.X Bugfix on my anet a8 and everything works great there is just a little wierd thing,
and i dont know if it is normal but,
I have 2 mosfets on my anet A8 and when i print something it heats verry good but my mossfets, motherboard, hotbed leds are flashing verry quickly and idk if its normal or if it will broke my 3d printer.
its like a PID wierd thing.

### Bug Timeline

Today but its the first time that i updated my 3d printer

### Expected behavior

just that the pid will be more smart

### Actual behavior

it makes flash the motherboard/ mossfets and hotbed leds extremely fast

### Steps to Reproduce

- install the last version of marlin on a anet a8
- Launch a print
- Wait and see

### Version of Marlin Firmware

bugfix-2.0.x 

### Printer model

Anet A8

### Electronics

Install Mosfets 

### Add-ons

Octoprint with a raspberry pi

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

Config File:
[Marlin_Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7966830/Marlin_Configuration.zip)

Log Output:
I dont know where it is 

Video:
https://youtu.be/QISfGuloGEw

Gcode:
not needed it makes the same thing with everything

**Comment by guanaco0403** [comment]
but am not 100% sure that it is a bug idk there is no documentation i just found this sub Redit that maybe explane that this is normal
https://www.reddit.com/r/AnetA8/comments/9tah7e/blinking_led_after_marlin_installation/

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
