### ISSUE TITLE
MKS Robin Nano V2. TFT_LVGL_UI. TFT_ROTATION TFT_ROTATE_180 

### ISSUE THREAD

**Issue by altiber** [MarlinFirmware/Marlin#23662]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

TFT_ROTATION TFT_ROTATE_180 for MKS Robin Nano V2 with TFT_LVGL_UI rotates only image and not rotate touch.

### Steps to Reproduce

Just try it on latest bugfix

### Version of Marlin Firmware

CONFIGURATION_H_VERSION 02000903

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/7979373/Marlin.zip)

**Comment by ellensp** [comment]
The touch screen is a physically separate device. 

run https://marlinfw.org/docs/gcode/M995.html and reconfigure it

**Comment by ellensp** [comment]
I don't consider this  bug. This is the expected behavior.

**Comment by altiber** [comment]
Calibration is ok. The crosses appear in the right places, but after the calibration is over, the problem remains

**Comment by altiber** [comment]
And what about #define TFT_COLOR_UI? With this define there is no such problem

**Comment by altiber** [comment]
And M995 video

https://user-images.githubusercontent.com/74643876/151996495-f766d918-34b5-404b-8fd9-2e32e4597c2a.mp4

**Comment by altiber** [comment]
Sorry, but nobody no ideas?
