### ISSUE TITLE
[BUG] (Progress / LCD features greyed out in VSCODE)

### ISSUE THREAD

**Issue by Sonicboom247** [MarlinFirmware/Marlin#23670]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I have never needed to define a TFT in VSCode so not sure if something changed with the ports or the lcd config for the Sidewinders stock TFT, I believe it is an MKS 28 clone, any features related to print progress are greyed out in VSCode unless i define a TFT.

### Bug Timeline

noticed issue last week after pulling down last months changes

### Expected behavior

these to show defined
#define STATUS_MESSAGE_SCROLLING
#define LCD_SET_PROGRESS_MANUALLY
#define LCD_SHOW_E_TOTAL
#define SHOW_REMAINING_TIME         // Display estimated time to completion
    #if ENABLED(SHOW_REMAINING_TIME)
    #define USE_M73_REMAINING_TIME    // Use remaining time from M73 command instead of estimation
     #define ROTATE_PROGRESS_DISPLAY   // Display (P)rogress, (E)lapsed, and (R)emaining time 

### Actual behavior

all of the above are greyed out as if undefined in VSCode. and compiling now errors out referring to MarlinUI
Marlin\src\lcd\marlinui.cpp:183:6: error: redefinition of 'static void MarlinUI::init()'
  183 | void MarlinUI::init() {
      |      ^~~~~~~~
In file included from Marlin\src\lcd\marlinui.cpp:40:
Marlin\src\lcd\marlinui.h:482:17: note: 'static void MarlinUI::init()' previously defined here
  482 |     static void init() {}
      |                 ^~~~
*** [.pio\build\BIGTREE_SKR_2_USB\src\src\lcd\marlinui.cpp.o] Error 1

### Version of Marlin Firmware

2.0.9.3

### Printer model

Artillery Sidewinder X1

### Electronics

Stock display on BTT SKR2

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7996870/Configuration.zip)

**Comment by thisiskeithb** [comment]
Cannot reproduce. Your config compiles fine with bugfix downloaded today ([e4658c3](https://github.com/MarlinFirmware/Marlin/commit/e4658c321fb722470889796ae76930a067d59f33)).

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
