### ISSUE TITLE
[BUG] error: 'manual_feedrate_mm_s' on build

### ISSUE THREAD

**Issue by mtnmike** [MarlinFirmware/Marlin#23671]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Ender5+ with SKR2 & TFT35. Get build error:
Marlin\src\lcd\marlinui.cpp:769:60: error: 'manual_feedrate_mm_s' was not declared in this scope; did you mean 'feedrate_mm_s'?
Marlin\src\lcd\menu\menu.cpp:291:30: error: 'manual_feedrate_mm_s' was not declared in this scope; did you mean 'feedrate_mm_s'?
Marlin\src\lcd\menu\menu_bed_corners.cpp:316:30: error: 'manual_feedrate_mm_s' was not declared in this scope; did you mean 'feedrate_mm_s'?
This error did not happen with 2.0.9.3 but did get error: MarlinHAL::adc_enable that went away in bugfix-2.0

[Marlin Files for Ender5p for SKR_2.zip](https://github.com/MarlinFirmware/Marlin/files/7997325/Marlin.Files.for.Ender5p.for.SKR_2.zip)

### Version of Marlin Firmware

bugfix-2.0 Feb22022

### Printer model

ender 5Plus

### Electronics

SKR2 w/TFT35

### Add-ons

none

**Comment by ellensp** [comment]
You are using miss matched versions of code and config files.

See https://github.com/MarlinFirmware/Marlin/issues/23656
