### ISSUE TITLE
[BUG] Error Building Marlin 2.0.x

### ISSUE THREAD

**Issue by Loris-Stanley-Ruch** [MarlinFirmware/Marlin#23695]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Get this error when trying to compile for anycubic chiron:

### Actual behavior

In file included from Marlin\src\inc/MarlinConfigPre.h:56:0,
                 from Marlin\src\inc/MarlinConfig.h:28,
                 from Marlin\src\MarlinCore.h:24,
                 from Marlin\src\MarlinCore.cpp:31:
Marlin\src\MarlinCore.cpp: In function 'bool pin_is_protected(pin_t)':
Marlin\src\inc/../../Configuration_adv.h:513:30: error: 'TG_FAN1_PIN' was not declared in this scope
   #define CONTROLLER_FAN_PIN TG_FAN1_PIN    // Set a custom pin for the controller fan
                              ^
Marlin\src\pins/sensitive_pins.h:823:17: note: in expansion of macro 'CONTROLLER_FAN_PIN'
   #define _FANC CONTROLLER_FAN_PIN,
                 ^~~~~~~~~~~~~~~~~~
Marlin\src\pins/sensitive_pins.h:893:58: note: in expansion of macro '_FANC'
   _PS_ON _FAN0 _FAN1 _FAN2 _FAN3 _FAN4 _FAN5 _FAN6 _FAN7 _FANC \
                                                          ^~~~~
Marlin\src\MarlinCore.cpp:311:49: note: in expansion of macro 'SENSITIVE_PINS'
     static constexpr size_t pincount = OnlyPins<SENSITIVE_PINS>::size;
                                                 ^~~~~~~~~~~~~~
Marlin\src\inc/../../Configuration_adv.h:513:30: note: suggested alternative: 'FAN1_PIN'
   #define CONTROLLER_FAN_PIN TG_FAN1_PIN    // Set a custom pin for the controller fan
                              ^
Marlin\src\pins/sensitive_pins.h:823:17: note: in expansion of macro 'CONTROLLER_FAN_PIN'
   #define _FANC CONTROLLER_FAN_PIN,
                 ^~~~~~~~~~~~~~~~~~
Marlin\src\pins/sensitive_pins.h:893:58: note: in expansion of macro '_FANC'
   _PS_ON _FAN0 _FAN1 _FAN2 _FAN3 _FAN4 _FAN5 _FAN6 _FAN7 _FANC \
                                                          ^~~~~
Marlin\src\MarlinCore.cpp:311:49: note: in expansion of macro 'SENSITIVE_PINS'
     static constexpr size_t pincount = OnlyPins<SENSITIVE_PINS>::size;
                                                 ^~~~~~~~~~~~~~
Marlin\src\MarlinCore.cpp:311:63: error: template argument 27 is invalid
     static constexpr size_t pincount = OnlyPins<SENSITIVE_PINS>::size;
                                                               ^
In file included from C:\Users\Loris\.platformio\packages\framework-arduino-avr\cores\arduino/Arduino.h:28:0,
                 from Marlin\src\inc/../HAL/./AVR/../shared/Marduino.h:36,
                 from Marlin\src\inc/../HAL/./AVR/HAL.h:22,
                 from Marlin\src\inc/../HAL/HAL.h:30,
                 from Marlin\src\inc/MarlinConfig.h:31,
                 from Marlin\src\MarlinCore.h:24,
                 from Marlin\src\MarlinCore.cpp:31:
Marlin\src\MarlinCore.cpp:312:52: error: size of array 'sensitive_pins' is not an integral constant-expression
     static const pin_t (&sensitive_pins)[pincount] PROGMEM = OnlyPins<SENSITIVE_PINS>::table;
                                                    ^
Marlin\src\MarlinCore.cpp:312:85: error: could not convert template argument 'TG_FAN1_PIN' from '<type error>' to 'signed char'
     static const pin_t (&sensitive_pins)[pincount] PROGMEM = OnlyPins<SENSITIVE_PINS>::table;
                                                                                     ^
In file included from Marlin\src\feature\../inc/../HAL/./AVR/HAL.h:22:0,
                 from Marlin\src\feature\../inc/../HAL/HAL.h:30,
                 from Marlin\src\feature\../inc/MarlinConfig.h:31,
                 from Marlin\src\feature\controllerfan.cpp:23:
Marlin\src\feature\controllerfan.cpp: In static member function 'static void ControllerFan::setup()':
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:87:35: error: 'DIOTG_FAN1_PIN_DDR' was not declared in this scope
 #define _SET_OUTPUT(IO)       SBI(DIO ## IO ## _DDR, DIO ## IO ## _PIN)
                                   ^
Marlin\src\feature\../inc/../HAL/./AVR/../shared/Marduino.h:44:21: note: in definition of macro 'SBI'
   #define SBI(A,B) (A |= _BV(B))
                     ^
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:108:31: note: in expansion of macro '_SET_OUTPUT'
 #define SET_OUTPUT(IO)        _SET_OUTPUT(IO)
                               ^~~~~~~~~~~
Marlin\src\feature\controllerfan.cpp:42:3: note: in expansion of macro 'SET_OUTPUT'
   SET_OUTPUT(CONTROLLER_FAN_PIN);
   ^~~~~~~~~~
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:87:54: error: 'DIOTG_FAN1_PIN_PIN' was not declared in this scope
 #define _SET_OUTPUT(IO)       SBI(DIO ## IO ## _DDR, DIO ## IO ## _PIN)
                                                      ^
Marlin\src\feature\../inc/../HAL/./AVR/../shared/Marduino.h:42:23: note: in definition of macro '_BV'
 #define _BV(b) (1 << (b))
                       ^
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:87:31: note: in expansion of macro 'SBI'
 #define _SET_OUTPUT(IO)       SBI(DIO ## IO ## _DDR, DIO ## IO ## _PIN)
                               ^~~
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:108:31: note: in expansion of macro '_SET_OUTPUT'
 #define SET_OUTPUT(IO)        _SET_OUTPUT(IO)
                               ^~~~~~~~~~~
Marlin\src\feature\controllerfan.cpp:42:3: note: in expansion of macro 'SET_OUTPUT'
   SET_OUTPUT(CONTROLLER_FAN_PIN);
   ^~~~~~~~~~
In file included from Marlin\src\feature\../inc/../HAL/./AVR/HAL.h:24:0,
                 from Marlin\src\feature\../inc/../HAL/HAL.h:30,
                 from Marlin\src\feature\../inc/MarlinConfig.h:31,
                 from Marlin\src\feature\controllerfan.cpp:23:
Marlin\src\feature\controllerfan.cpp: In static member function 'static void ControllerFan::update()':
Marlin\src\feature\../inc/../../Configuration_adv.h:513:30: error: 'TG_FAN1_PIN' was not declared in this scope
   #define CONTROLLER_FAN_PIN TG_FAN1_PIN    // Set a custom pin for the controller fan
                              ^
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:356:25: note: in definition of macro 'PWM_PIN'
   #define PWM_PIN(P)  ((P >= 2 && P <= 10) || P == 13 || P == 44 || P == 45 || P == 46)
                         ^
Marlin\src\feature\controllerfan.cpp:78:19: note: in expansion of macro 'CONTROLLER_FAN_PIN'
       if (PWM_PIN(CONTROLLER_FAN_PIN))
                   ^~~~~~~~~~~~~~~~~~
Marlin\src\feature\../inc/../../Configuration_adv.h:513:30: note: suggested alternative: 'FAN1_PIN'
   #define CONTROLLER_FAN_PIN TG_FAN1_PIN    // Set a custom pin for the controller fan
                              ^
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:356:25: note: in definition of macro 'PWM_PIN'
   #define PWM_PIN(P)  ((P >= 2 && P <= 10) || P == 13 || P == 44 || P == 45 || P == 46)
                         ^
Marlin\src\feature\controllerfan.cpp:78:19: note: in expansion of macro 'CONTROLLER_FAN_PIN'
       if (PWM_PIN(CONTROLLER_FAN_PIN))
                   ^~~~~~~~~~~~~~~~~~
In file included from Marlin\src\feature\../inc/../HAL/./AVR/HAL.h:24:0,
                 from Marlin\src\feature\../inc/../HAL/HAL.h:30,
                 from Marlin\src\feature\../inc/MarlinConfig.h:31,
                 from Marlin\src\feature\controllerfan.cpp:23:
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:82:41: error: 'DIOTG_FAN1_PIN_RPORT' was not declared in this scope
 #define _WRITE(IO,V)          do{ if (&(DIO ## IO ## _RPORT) < (uint8_t*)0x100) _WRITE_NC(IO,V); else _WRITE_C(IO,V); }while(0)
                                         ^
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:102:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^~~~~~
Marlin\src\feature\controllerfan.cpp:81:9: note: in expansion of macro 'WRITE'
         WRITE(CONTROLLER_FAN_PIN, speed > 0);
         ^~~~~
Compiling .pio\build\mega2560\src\src\gcode\control\M111.cpp.o
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:82:41: note: suggested alternative: 'DIO31_RPORT'
 #define _WRITE(IO,V)          do{ if (&(DIO ## IO ## _RPORT) < (uint8_t*)0x100) _WRITE_NC(IO,V); else _WRITE_C(IO,V); }while(0)
                                         ^
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:102:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^~~~~~
Marlin\src\feature\controllerfan.cpp:81:9: note: in expansion of macro 'WRITE'
         WRITE(CONTROLLER_FAN_PIN, speed > 0);
         ^~~~~
In file included from Marlin\src\feature\../inc/../HAL/./AVR/HAL.h:22:0,
                 from Marlin\src\feature\../inc/../HAL/HAL.h:30,
                 from Marlin\src\feature\../inc/MarlinConfig.h:31,
                 from Marlin\src\feature\controllerfan.cpp:23:
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:72:14: error: 'DIOTG_FAN1_PIN_WPORT' was not declared in this scope
   if (V) SBI(DIO ## IO ## _WPORT, DIO ## IO ## _PIN); \
              ^
Marlin\src\feature\../inc/../HAL/./AVR/../shared/Marduino.h:44:21: note: in definition of macro 'SBI'
   #define SBI(A,B) (A |= _BV(B))
                     ^
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:82:81: note: in expansion of macro '_WRITE_NC'
 #define _WRITE(IO,V)          do{ if (&(DIO ## IO ## _RPORT) < (uint8_t*)0x100) _WRITE_NC(IO,V); else _WRITE_C(IO,V); }while(0)
                                                                                 ^~~~~~~~~
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:102:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^~~~~~
Marlin\src\feature\controllerfan.cpp:81:9: note: in expansion of macro 'WRITE'
         WRITE(CONTROLLER_FAN_PIN, speed > 0);
         ^~~~~
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:72:14: note: suggested alternative: 'DIO15_WPORT'
   if (V) SBI(DIO ## IO ## _WPORT, DIO ## IO ## _PIN); \
Compiling .pio\build\mega2560\src\src\gcode\control\M120_M121.cpp.o
              ^
Marlin\src\feature\../inc/../HAL/./AVR/../shared/Marduino.h:44:21: note: in definition of macro 'SBI'
   #define SBI(A,B) (A |= _BV(B))
                     ^
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:82:81: note: in expansion of macro '_WRITE_NC'
 #define _WRITE(IO,V)          do{ if (&(DIO ## IO ## _RPORT) < (uint8_t*)0x100) _WRITE_NC(IO,V); else _WRITE_C(IO,V); }while(0)
                                                                                 ^~~~~~~~~
Marlin\src\feature\../inc/../HAL/./AVR/fastio.h:102:31: note: in expansion of macro '_WRITE'
 #define WRITE(IO,V)           _WRITE(IO,V)
                               ^~~~~~
Marlin\src\feature\controllerfan.cpp:81:9: note: in expansion of macro 'WRITE'
         WRITE(CONTROLLER_FAN_PIN, speed > 0);
compilation terminated due to -fmax-errors=5.
Compiling .pio\build\mega2560\src\src\gcode\control\M17_M18_M84.cpp.o
*** [.pio\build\mega2560\src\src\MarlinCore.cpp.o] Error 1
*** [.pio\build\mega2560\src\src\feature\controllerfan.cpp.o] Error 1
=================================================================================================== [FAILED] Took 6.90 seconds =================================================================================================== 

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:06.898
============================================================================================== 1 failed, 0 succeeded in 00:00:06.898 =============================================================================================

### Steps to Reproduce

I have the file from the directory: Configurations-release-2.0.9.3\config\examples\AnyCubic\Chiron
to Marlin-2.0.x\Marlin  copied and pasted

Ich installiere alle Plugins für dieses Projekt in Visual Studio. Just like in the tutorial:
https://www.youtube.com/watch?v=Y-IUUrp27S0&t=623s

### Version of Marlin Firmware

2.0.x

### Printer model

anycubic chiron

### Electronics

Original Trigorilla 14 Board

### Add-ons

-

### Your Slicer

Cura

### Host Software

Cura

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/79554437/152877017-ad1614eb-02f1-44f2-bd23-1d1b95d55581.png)

![image](https://user-images.githubusercontent.com/79554437/152877073-0c25d017-cec6-4ee4-89fa-818e540393f9.png)

**Comment by ellensp** [comment]
https://github.com/MarlinFirmware/Configurations/blob/release-2.0.9.3/config/examples/AnyCubic/Chiron/Configuration_adv.h has   #define CONTROLLER_FAN_PIN TG_FAN1_PIN    // Set a custom pin for the controller fan

But  TG_FAN1_PIN is not defined. in Marlin 2.0.9.3  was last seen in 2.0.9.2

@thinkyhead
release-2.0.9.3/config/examples/AnyCubic/Chiron/Configuration_adv.h needs updated from 
#define CONTROLLER_FAN_PIN TG_FAN1_PIN
to
#define CONTROLLER_FAN_PIN FAN1_PIN

**Comment by ellensp** [comment]
Closing this issue, as it is an issue with the config file examples. 
Will be continued in https://github.com/MarlinFirmware/Configurations/issues/640
