### ISSUE TITLE
[BUG] MKS Robin Nano V3 no PSU Control with PWC possible but need to use PWC

### ISSUE THREAD

**Issue by Liriel-666** [MarlinFirmware/Marlin#23698]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When Setup the MKS Robin Nano v3 with a PWC Unit. 

I must activate the PSU Control in  the Config

#define PSU_CONTROL
//#define PSU_NAME "Power Supply"

#if ENABLED(PSU_CONTROL)
  #define MKS_PWC                 // Using the MKS PWC add-on
  //#define PS_OFF_CONFIRM          // Confirm dialog when power off
  //#define PS_OFF_SOUND            // Beep 1s when power off
  #define PSU_ACTIVE_STATE LOW      // Set 'LOW' for ATX, 'HIGH' for X-Box

  //#define PSU_DEFAULT_OFF         // Keep power off until enabled directly with M80
  //#define PSU_POWERUP_DELAY 250   // (ms) Delay for the PSU to warm up to full power

  //#define PSU_POWERUP_GCODE  "M355 S1"  // G-code to run after power-on (e.g., case light on)
  //#define PSU_POWEROFF_GCODE "M355 S0"  // G-code to run before power-off (e.g., case light off)

But then this message comes at compile
```
> Executing task: C:\Users\Laen\.platformio\penv\Scripts\platformio.exe run <

Processing mks_robin_nano_v3 (board: marlin_STM32F407VGT6_CCM; platform: ststm32@~12.1; framework: arduino)
---------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
In file included from c:\drucker\marlin-bugfix-2.0.x--08.02.22\marlin\src\pins\stm32f4/pins_MKS_ROBIN_NANO_V3.h:72,
                 from c:\drucker\marlin-bugfix-2.0.x--08.02.22\marlin\src\pins\pins.h:669,
                 from c:\drucker\marlin-bugfix-2.0.x--08.02.22\marlin\src\inc\marlinconfig.h:34,
                 from buildroot/share/PlatformIO/scripts/common-dependencies.h:29:
c:\drucker\marlin-bugfix-2.0.x--08.02.22\marlin\src\pins\stm32f4/pins_MKS_ROBIN_NANO_V3_common.h:169:8: error: #error "PSU_CONTROL is incompatible with MKS_PWC plus TFT_LVGL_UI."
  169 |       #error "PSU_CONTROL is incompatible with MKS_PWC plus TFT_LVGL_UI."
      |        ^~~~~
CalledProcessError: Command '"C:\Users\Laen\.platformio\packages\toolchain-gccarmnoneeabi\bin\arm-none-eabi-g++.exe" 
-D__MARLIN_FIRMWARE__ -DNDEBUG -DHAL_STM32 -DUSBCON -DUSBD_USE_CDC -DTIM_IRQ_PRIO=13 -DPIN_WIRE_SCL=PB6 -DPIN_WIRE_SDA=PB7 -DHAL_PCD_MODULE_ENABLED -D__MARLIN_DEPS__ -w -dM -E -x c++ buildroot/share/PlatformIO/scripts/common-dependencies.h' returned non-zero exit status 1.:
  File "C:\Users\Laen\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 179:
    env.SConscript(item, exports="env")
  File "C:\Users\Laen\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 597:       
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\Laen\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 285:       
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\drucker\Marlin-bugfix-2.0.x--08.02.22\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 247:
    apply_features_config()
  File "C:\drucker\Marlin-bugfix-2.0.x--08.02.22\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 133:
    if not env.MarlinFeatureIsEnabled(feature):
  File "C:\Users\Laen\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Util.py", line 742:
    return self.method(*nargs, **kwargs)
  File "C:\drucker\Marlin-bugfix-2.0.x--08.02.22\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 216:
    load_marlin_features()
  File "C:\drucker\Marlin-bugfix-2.0.x--08.02.22\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 204:
    define_list = run_preprocessor(env)
  File "C:\drucker\Marlin-bugfix-2.0.x--08.02.22\buildroot\share\PlatformIO\scripts\preprocessor.py", line 42:       
    define_list = subprocess.check_output(cmd, shell=True).splitlines()
  File "C:\Users\Laen\.platformio\python3\lib\subprocess.py", line 424:
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Laen\.platformio\python3\lib\subprocess.py", line 528:
    raise CalledProcessError(retcode, process.args,
============================================ [FAILED] Took 2.08 seconds ============================================

Environment        Status    Duration
-----------------  --------  ------------
mks_robin_nano_v3  FAILED    00:00:02.079
======================================= 1 failed, 0 succeeded in 00:00:02.079 =======================================Der Terminalprozess "C:\Users\Laen\.platformio\penv\Scripts\platformio.exe 'run'" wurde mit folgendem Exitcode beendet: 1.
```

I think ther eis a error because in the Release 2.0.9.3 it works

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/8026169/configs.zip)

### Bug Timeline

new

### Version of Marlin Firmware

bugfix 2.0.x from 8.4.2022

### Printer model

Anet A8

### Electronics

MKS Robin Nano V3

### Add-ons

MKS PWC

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by Liriel-666** [comment]
I think it is  the Code in the pins_MKS_ROBIN_NANO_V3_common.h

line 169
 #error "PSU_CONTROL is incompatible with MKS_PWC plus TFT_LVGL_UI."

that prevent it but not exist in 2.9.0.3 but not only this

but psu control must be on for pwc use

**Comment by ellensp** [comment]
This has been deliberately added. 
It is designed to stop you setting combinations of features that do not work correctly together.

This was added in https://github.com/MarlinFirmware/Marlin/pull/23549

To me it reads that you cannot have MKS_PWC with TFT_LVGL_UI

It used to be that if you enabled PSU_CONTROL and MKS_PWC when marlin saw TFT_LVGL_UI
It turned both PSU_CONTROL and MKS_PWC off, silently without telling you.

**Comment by Liriel-666** [comment]
Sorry to say but no Power Controller and mks  PWC when LVL is idiotic. 

There is no reason that it can not used with LVL. 
In the MKS Marlin 2.0.9.2 (that has a error with tmc2208 trimatic and not to use for me) it is possible and in this Marlin it is useable without Problem in 2.0.9.3 release (and before). 

Why is it in that release possible and works fine and now someone  think he must disable it?

How  I use the mks PWC Module when it is not possible to activate it because the firmware want Power Control on for it?
There is only the Option in the Power Control section to activate pwc.
No other Option

And in the Other Display Menu designs is it possible?
Why only in LVL not possible?

How could i use PWC and LVL Menu in the bugfix?

**Comment by Liriel-666** [comment]
Nothing fixed until today

**Comment by thisiskeithb** [comment]
> I think ther eis a error because in the Release 2.0.9.3 it works

How? `PSU_CONTROL` was silently undefined if `TFT_LVGL_UI` was enabled in `2.0.9.3`:

https://github.com/MarlinFirmware/Marlin/blob/f471eab1a2834c4e65477d978ea9f0349542b302/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_NANO_common.h#L117-L131

I wouldn't call this a bug, but a feature request.

**Comment by Liriel-666** [comment]
That is a Bug or someone miss understand it and disable it In The bugfix.
Because someone add that error message that cancel the compiling.
And in 2.0.9.3 all 3 working together without problems. In the Bugfix  not possible to compil. 

Without lvgl and Power Control no pwc but All these three thing must work together.

Without lvl no pwc options. 
Without power control no pwc function

**Comment by thisiskeithb** [comment]
The link above is straight from 2.0.9.3. It *did not* work as you think it does because Marlin was silently disabling enabled features while compiling.

**Comment by Liriel-666** [comment]
Strange pwc and lvl works fine.
What is then disable?

But with  bugfix no power control, pwc and lvl is possible.
But pwc needs power control and is not to activate without.
And PWC needs lvl display too

**Comment by Rockman18** [comment]
In 2.0.9.3, it works perfectly because the MKS_PWC variable is only necessary to set the SUICIDE_PIN and SUICIDE_PIN_STATE and, to avoid other unwanted behaviour, MKS_PWC and PSU_CONTROL are disabled.

PSU_CONTROL is not important for LVGL_UI so the undef is here to avoid stange behaviour.
MKS_PWC is mandatory in LVGL_UI to set SUICIDE_PIN and SUICIDE_PIN_STATE and only for this so the feature can be disabled after that.

For LVGL_UI, the #define MKS_PWC can be outside  of #if ENABLED(PSU_CONTROL) but to keep the logic define PSU_CONTROL before is not idiot even if it is not necessary.

**Comment by Liriel-666** [comment]
ok then marlin after 2.0.9.3 is useless because mks lvgl_ui and mks pwc are not useable together.
or how should both to be use?

**Comment by EvilGremlin** [comment]
This mess is because lvgl_ui implements it's own functions instead of using existing ones, and no one wanted to fix it yet. People generally prefer color_ui adn classic_ui. If someone will step up to fix and maintain it (at least for a bit) we will be very grateful.

**Comment by Liriel-666** [comment]
and with color ui the pwc module can be used?

**Comment by EvilGremlin** [comment]
You just setup it as regular PSU_CONTROL stuff.
