### ISSUE TITLE
[BUG] Wrong temperature on T0 while T1 is active

### ISSUE THREAD

**Issue by scott0122** [MarlinFirmware/Marlin#23706]
### Version of Marlin Firmware
2.0.9.3

### Bug Description

When T0 is active
![image](https://user-images.githubusercontent.com/39105828/153201892-8039e57e-6482-4507-a9c1-56ab591ebaa8.png)

When T1 is active
![image](https://user-images.githubusercontent.com/39105828/153201913-bbbe7589-4e9f-4168-aa74-b6976192fb78.png)

### Host Software

Repetier Host

**Comment by ellensp** [comment]
Already fixed in bugfix and 2.0.x see https://github.com/MarlinFirmware/Marlin/pull/23505
