### ISSUE TITLE
[BUG] MKS_ROBIN_E3_V1_1 when inserting SD card, extruder motor locks up

### ISSUE THREAD

**Issue by danbrianwhite** [MarlinFirmware/Marlin#23715]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When inserting the SD card, the extruder motor activates and locks up.

### Bug Timeline

The bug was introduced in https://github.com/MarlinFirmware/Marlin/pull/23282

### Expected behavior

When inserting the SD card, the extruder motor should not energize.

### Actual behavior

When inserting the SD card, the extruder motor activates and locks up.

### Steps to Reproduce

Compile firmware for mks robin e3 v1.1
Insert an SD Card
Extruder motor locks up

### Version of Marlin Firmware

Latest

### Printer model

CoreXy

### Electronics

Mks Robin E3

### Additional information & file uploads

After bisecting the Marlin firmware git history, I found the following commit causes the issue. I'm not sure what a proper fix is so I'm opening an issue ticket here. Reverting this change on top of the bug branch's head fixes the issue.

https://github.com/MarlinFirmware/Marlin/pull/23282

**Comment by ellensp** [comment]
In Marlin/ini/stm32f1.ini is

```
#
# MKS Robin E3/E3D (STM32F103RCT6) with TMC2209
#
[env:mks_robin_e3]
extends                     = common_STM32F103RC_variant
board_build.encrypt         = Robin_e3.bin
board_build.offset          = 0x5000
board_upload.offset_address = 0x08005000
build_flags                 = ${common_STM32F103RC_variant.build_flags}
                              -DTIMER_SERVO=TIM5 -DDEFAULT_SPI=3
build_unflags               = ${common_STM32F103RC_variant.build_unflags}
                              -DUSBCON -DUSBD_USE_CDC
debug_tool                  = stlink
```

try changing -DDEFAULT_SPI=3 to -DDEFAULT_SPI=2

as SPI 3 uses 
  #define PIN_SPI_MOSI          PB5      <=== E0_ENABLE_PIN
  #define PIN_SPI_MISO          PB4      <=== E0_STEP_PIN
  #define PIN_SPI_SCK            PB3      <=== E0_DIR_PIN

PR https://github.com/MarlinFirmware/Marlin/pull/23282  is not the cause of this issue. It just made the issue more visible.

**Comment by danbrianwhite** [comment]
@ellensp - Thanks for the idea. I just tried this out. 

When setting SPI to 3, the SD card fails to init.

Any ideas?

**Comment by ellensp** [comment]
meant to be using 2, not 3
Ie change  -DDEFAULT_SPI=3  is changed to   -DDEFAULT_SPI=2

**Comment by danbrianwhite** [comment]
@ellensp sorry I mis typed.

 Setting from 3 to 2. This SD card fails to init.

**Comment by ellensp** [comment]
ignoring that for now...  does E lockup?

**Comment by danbrianwhite** [comment]
@ellensp - E does not lock up and is unpowered. So that part is fixed now.

**Comment by ellensp** [comment]
Try these, in Configuration_adv.h 

   * :['SPI_HALF_SPEED', 'SPI_QUARTER_SPEED', 'SPI_EIGHTH_SPEED']
   */
  //#define SD_SPI_SPEED SPI_HALF_SPEED

**Comment by danbrianwhite** [comment]
I tried all 3 options. None of them work for SD init.

I'm not sure if the following is helpful. When removing the SD card, it will show "Media Removed"
