### ISSUE TITLE
[BUG]Laser spindle and bltouch on skr 1.3

### ISSUE THREAD

**Issue by danebak** [MarlinFirmware/Marlin#23712]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello , from last nightly build i am not able to compile marlin with #define BLTOUCH and #define LASER_FEATURE options activated.
Iam using printer both as 3d printer and laser engraver.

### Bug Timeline

Bug was not present in previous version

### Expected behavior

to use both BLTOUCH  and LASER_FEATURE 

### Actual behavior

Marlin wont compile

### Version of Marlin Firmware

2.0.x nightly

### Printer model

HOME-BUILT

### Electronics

BTT SKR 1.3

### Add-ons

BLTOUCH

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/8040794/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/8040795/Configuration_adv.txt)

**Comment by ellensp** [comment]
This error is nothing to do with the stated options in the Bug report
"error: 'manual_feedrate_mm_s' was not declared in this scope"

This error is due to the user not updating their Configuration_adv.h to the latest standard 
See https://github.com/MarlinFirmware/Marlin/issues/23656 for details
