### ISSUE TITLE
Extruder Autofan

### ISSUE THREAD

**Issue by 691175002** [MarlinFirmware/Marlin#2372]
The extruder autofan feature does not compile if motherboard is set to BOARD_RAMPS_13_EFB (33).

**Comment by taalabash** [comment]
You should define the pin 9 as extruder auto fan and undefine it from pins.h as a normal fan because you can't use a pin for two porposes and if you are using ramps with EFB setup you have only one pin for a fan

**Comment by 691175002** [comment]
Thanks, I figured it out.
