### ISSUE TITLE
#SDSUPPORT Defined but SD card not recognized

### ISSUE THREAD

**Issue by sarahTCP** [MarlinFirmware/Marlin#23736]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I updated my FormBot T-Rex 3 with the Marlin Bugfix 2.0 firmware and the option to print from an SD card went away on the menu. The image I have included shows the default settings for SD support that came in the configuration.h file for the T-Rex 3. Line 2139 states that you must uncomment the SDSUPPORT line in order to enable SD card usage. However, in the settings which are unchanged here, it is already uncommented and inside the if statement. These settings do not enable the SD card. I have tried many things to get the option to print from SD/media to show up on the printer and they all result in a failure to upload. I have tried commenting out lines 2142 and 2144, copying line 2143 and pasting out outside the if statement, and commenting out the line that defines ICSP_PORT_SWITCHES so that that the if statement would run. All of these result in the same error and failure while trying to flash to the printer, as seen in the second image.

 
![image](https://user-images.githubusercontent.com/97744308/153895764-119f467f-90e7-4be3-9cb8-76f4f463e86b.png)

![image](https://user-images.githubusercontent.com/97744308/153896393-9d4d0339-b468-4f72-8b8b-f81d8d819eb6.png)

### Bug Timeline

Started last week when I tried to update edited firmware to my printer

### Expected behavior

I expected the flash/upload to complete successfully when doing any of the options such as pasting #define SDSUPPORT outside the conditional statement or commenting out #define ICSP_PORT_SWITCHES to disable and allow the line inside the conditional statement to executre

### Actual behavior

The build failed to upload to the printer

### Version of Marlin Firmware

Marlin_Bugfix_2.0x

### Printer model

FormBot T-rex 3

### Additional information & file uploads

[configsZip.zip](https://github.com/MarlinFirmware/Marlin/files/8062077/configsZip.zip)

**Comment by ellensp** [comment]
SDSUPPORT is doing as it should

If enabled and compiles all sd related source
```
Compiling .pio/build/mega2560/src/src/module/tool_change.cpp.o
Compiling .pio/build/mega2560/src/src/sd/Sd2Card.cpp.o
Compiling .pio/build/mega2560/src/src/sd/SdBaseFile.cpp.o
Compiling .pio/build/mega2560/src/src/sd/SdFatUtil.cpp.o
Compiling .pio/build/mega2560/src/src/sd/SdFile.cpp.o
Compiling .pio/build/mega2560/src/src/sd/SdVolume.cpp.o
Compiling .pio/build/mega2560/src/src/sd/cardreader.cpp.o
Compiling .pio/build/mega2560/libd9b/Wire/Wire.cpp.o
```
enabling ICSP_PORT_SWITCHES disables SDSUPPORT as it should

```
Compiling .pio/build/mega2560/src/src/module/tool_change.cpp.o
(no sd support in here) 
Compiling .pio/build/mega2560/libd9b/Wire/Wire.cpp.o
`
```

**Comment by ellensp** [comment]
The error your show is an upload error, nothing to do with Marlin.

Is an issue with your controller, or the usb cable. Or mayby your bootloader

Scroll up to see actual error.

**Comment by ellensp** [comment]
Testing on ramps 1.4 ( BOARD_RAMPS_14_EEB) with a REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER since I don't have the BOARD_FORMBOT_TREX3
Using the provided configs with a modified pins file to support all the extra things you have enabled,

The Main menu works as expected
When a sdcard is in the lcd slot the last two menu items in the menu are
```
Change Media
Print from Media
```
Selecting Print from Media gives you a directory listing of the SD card

with the sdcard removed the two menu items above are replaced with
```
No Media 
```

**Comment by roel8032** [comment]
Try: Connect your printer to a host, like Repetier-Host. Send a M22 command and try to upload the firmware.
With M21 you can switch back.

**Comment by ellensp** [comment]
@roel8032 no setting in marlin or gcode can interfere or influence firmware uploads on a mega2560 based controller.
The firmware upload procedure is assert DTR serial line (via usb serial chip) this resets the mega2560.
now the megae2560 is running the boot loader code (completely separate from marlin) 
The uploader talks to the bootl loader code to transfer and store the data to the flash

**Comment by descipher** [comment]
> @roel8032 no setting in marlin or gcode can interfere or influence firmware uploads on a mega2560 based controller.
> The firmware upload procedure is assert DTR serial line (via usb serial chip) this resets the mega2560.
> now the megae2560 is running the boot loader code (completely separate from marlin)
> The uploader talks to the bootl loader code to transfer and store the data to the flash

I have observed hardware addons such as an esp wifi modual on the aux port blocking a firmware upload.

**Comment by sarahTCP** [comment]
I am able to upload to the printer when neither the ICSP or SD card lines are changed, but other things are, such as enabling various GCODE commands or changing the axes directions with true/false as needed. Is this still an error with the usb cable/controller/boatloader, since the upload only fails when changes are made to the SD related lines? The config.h file I uploaded here will not upload to my printer due to the fact that #define ICSP port switches  has been commented out.

**Comment by ellensp** [comment]
please post the full error.

**Comment by sarahTCP** [comment]
@ellensp Thanks! I have copied everything from the end of the upload to where it says failed:


RAM:   [========= ]  87.4% (used 7163 bytes from 8192 bytes)
Flash: [==========]  98.7% (used 250552 bytes from 253952 bytes)
Building .pio\build\mega2560\firmware.hex
Configuring upload protocol...
AVAILABLE: wiring
CURRENT: upload_protocol = wiring
Looking for upload port...
Auto-detected: COM3
Uploading .pio\build\mega2560\firmware.hex
avrdude: ser_open(): can't open device "\\.\COM3": Access is denied.


avrdude: ser_drain(): read error: The handle is invalid.


avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: The handle is invalid.


avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: The handle is invalid.


avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: The handle is invalid.


avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: The handle is invalid.


avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: The handle is invalid.


avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: The handle is invalid.


avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer

avrdude done.  Thank you.

*** [upload] Error 1
=========================================================== [FAILED] Took 52.96 seconds ===========================================================

**Comment by ellensp** [comment]
"avrdude: ser_open(): can't open device "\.\COM3": Access is denied."
this is a issue on your computer.
Either you have a another program open that is using this com port. Or windows is being silly and needs a reboot.

The the Access denied is your operating system telling the program avrdude, no you cannot have access to this com port

**Comment by sarahTCP** [comment]
@ellensp I realized I had Cura open! But this is one of the only times I have had that open while trying to upload. Cura is now closed and this is the error I receive: 
Reading | ################################################## | 100% 53.85s

avrdude: verifying ...
avrdude: verification error, first mismatch at byte 0x3c000
         0x00 != 0xdf
avrdude: verification error; content mismatch

avrdude: safemode: Fuses OK (E:FD, H:D8, L:FF)

avrdude done.  Thank you.

*** [upload] Error 1
=========================================================== [FAILED] Took 170.78 seconds ===========================================================

**Comment by descipher** [comment]
Flash: [==========] 98.7% (used 250552 bytes from 253952 bytes)

I don't think you have enough room! Scale back on the options!

**Comment by sarahTCP** [comment]
Is there anything you would recommend scaling back on? I did not change much other than defining two extra gcode commands (G60 and G61). I'm not sure what to take out that won't mess up the printer?

**Comment by descipher** [comment]
Disable PINS_DEBUGGING

**Comment by ellensp** [comment]
This error says that it wrote 0xdf to the flash location 0x3c000 but when it read it back it was 0x00

This is either bad flash ram in your controller, or a bad usb cable, or a bad bootloader. 

According to http://eleccelerator.com/fusecalc/fusecalc.php?chip=atmega2560
the fuses E:FD, H:D8, L:FF say it has a 4k words (8k) bootloader starting at 0x1f000 words (0x3E000) so it should not have issues at  0x3C000

The fact that it says 0x3c000 makes me think they have a bad bootloader on it. There is a really old bug in arduino mega2560 bootloader that on a flash the code only clears 0x00000 up to 0x3C0000. Clearing sets all bits back to 1. Writing only set the 0, bits. Without clearing the flash you cannot set any 1 bits.  
This is mentioned all over eg https://www.avrfreaks.net/forum/mega2560-programming-bootloader-fails-0x3c000-and-above
and https://github.com/msproul/Arduino-stk500v2-bootloader/issues/7 for example.

**Comment by descipher** [comment]
Please note H:D8 = 512 words 
![image](https://user-images.githubusercontent.com/10734527/154102599-eec958fc-55bc-4ec3-b313-217378ba559f.png)

**Comment by ellensp** [comment]
H:D8 = MSB 11011000 LSB

Bit
7 | OCDEN |   1
6 | JTAGEN |  1
5 | SPIEN * |   0
4 | WDTON |  1
3 | EESAVE |  1
2 | BOOTSZ1 |   0     <== this is set to 0
1 | BOOTSZ0 |   0     <== this is set to 0
0 | BOOTRST |  0

**Comment by descipher** [comment]
Right, sorry I inverted the logic!

This table allows reviewing and direct editing of the AVR fuse bits. All changes will be applied instantly.
Note:  means unprogrammed (1);  means programmed (0).

**Comment by descipher** [comment]
Bootloader bug is highly likely. But that requires deeper knowledge and is not recommended here. The rabbit hole is too deep for a passer by. Simply removing the extra non-essential option may resolve the issue since it would avoid the need to exceed 0x3c000. Preferred and more correct solution would be to replace the bootloader.

**Comment by Vertabreak** [comment]
Side Note: opening Cura or anything trying to connect to the device while your flashing it can brick the board and result in loss of the boards boot loader. this has happen to me more then a dozen times and repaired with the in circuit programmer i keep on hand ever since.

**Comment by ellensp** [comment]
You may be interested in this I just created (mostly so I could check my own mega based boards)
https://github.com/ellensp/check-avr-bootloader-clears-flash 
Platfomio only. Compile, upload and open up the serial monitor to the baud rate set to see output.

Two of my test mega2560's failed and one passed.

**Comment by descipher** [comment]
Perfect, good tool.

**Comment by sarahTCP** [comment]
@descipher I tried disabling pins_debugging and that solved the problem! I guess there was not enough room to upload with all the files enabled by SD support. Thanks everyone
