### ISSUE TITLE
possible [BUG] event_gcode_sd_abort not executing gcode. Printhead just stops in place

### ISSUE THREAD

**Issue by Apexpredation** [MarlinFirmware/Marlin#23735]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Selecting Print stop just freezes the nozzle in place even though it's set to G28XY. I also tried other gcode options with no luck. I have also noticed that it has a big delay  before it actually stops. before it would stop almost immediately and home as desired. 

### Bug Timeline

started with version 2.0.9.3

### Expected behavior

Select print stop, print should stop and home X and Y

### Actual behavior

print stops after 5 to 10 second delay and stays in place over the object that was printing (does not home of follow any entered gcode)

### Steps to Reproduce

1. uncomment #define event_gcode_sd_abort "G28XY"
2. Start a print
3. Select Stop Print from marlin screen and confirm
4.  ...
5. shake your fist in rage

### Version of Marlin Firmware

2.0.9.3

### Printer model

BIQU B1 

### Electronics

SKR2, TMC2209 in all slots

### Add-ons

Dual Z, H2 Direct Drive.

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by ellensp** [comment]
Printing from octoprint is not printing from sd card so event_gcode_sd_abort is not applicable

**Comment by Apexpredation** [comment]
> Printing from octoprint is not printing from sd card so event_gcode_sd_abort is not applicable

So what is the alternative option to make this work, because it worked before. I start prints almost exclusively from octoprint and this feature (or something that did the same thing) worked flawlessly before.

**Comment by ellensp** [comment]
settings in Octoprint. By default it will issue an M84 after canceling a print which turns the motors off.
Printer>GCODE Scripts>After print job is cancelled


Not a marlin issue

**Comment by Apexpredation** [comment]
> 

The thing is that I haven't used octoprint to trigger the stop print. I do it from the printer via Marlin screen. It is true that it doesn't work from octoprint, but that's why I've always done it from the printer. 
Typical procedure, start the print from my PC via Octoprint.  Go over to the printer and watch the first layer. If something goes unexpected I select stop print from the Marlin screen on the printer. Before it would stop almost immediately and home XY as expected. Now it just stops in place. I haven't changed anything in Octoprint no updates or anything. The only change was updating the Marlin firmware.

**Comment by ellensp** [comment]
Your screen is a smart screen, it runs its own firmware, when you press stop it sends gcodes to the controller. what it sends under the lcd's firmware.control

there is a settings.ini file for your display
which contains 
```
#### Cancel G-code Status
#   Options: [disable: 0, enable: 1]
cancel_gcode_enabled:0
```

and it contains 
```
#### Cancel G-code
# This G-code will run when a print is canceled if "cancel_gcode_enabled" is enabled.
#   Value range: [min: 3, max: 75 characters]
cancel_gcode:M104 S0\nM140 S0\nG28 XY R10\nM107\nM18\n

```

Your need to edit this ini file and enable cancel_gcode_enabled
and check the cancel_gcode does what you want.

Its still not a marlin issue.

**Comment by Apexpredation** [comment]
In the touch screen mode yes. I don't use that. I use the Marlin console screen. It's a direct connection to Marlin.

**Comment by ellensp** [comment]
I do not believe that stop when not printing from sd card has ever done anything other than stop. but leaving this open for now in case someone else has ideas.

**Comment by thisiskeithb** [comment]
> I do not believe that stop when not printing from sd card has ever done anything other than stop.

Indeed.

Make sure you enable `HOST_ACTION_COMMANDS` and `HOST_PROMPT_SUPPORT` or stopping from the Marlin side won’t work correctly.

**Comment by cp2004** [comment]
If you are printing from OctoPrint, then the 'Stop' button on the printer is probably operated with 'Host Action Commands'. So it sends `//action:cancel` or something. If this is the case (and it sounds to me like it is so) then you can add whatever gcode you want into OctoPrint's gcode scripts.

Or, is there some misunderstanding from me: are you printing from the SD card but controlled by OctoPrint? I'm with ellensp - I haven't seen this behaviour *by default* before.

**Comment by mriscoc** [comment]
Check here: https://github.com/OctoPrint/OctoPrint/issues/4368#issuecomment-1034039393 if you didn't have the Advanced Pause Feature, then the printer only does a normal pause.

**Comment by thisiskeithb** [comment]
We’re just guessing at this point since there are no configs.

**Comment by Apexpredation** [comment]
> Make sure you enable `HOST_ACTION_COMMANDS` and `HOST_PROMPT_SUPPORT` or stopping from the Marlin side won’t work correctly.

I think this is it. HOST_PROMPT_SUPPORT was commented out. I will compile, upload, test, and report back

**Comment by Apexpredation** [comment]
Yes that solved the issue. Thank you for all the input.
