### ISSUE TITLE
[BUG] X axis tries to home in wrong direction during first auto home after build.

### ISSUE THREAD

**Issue by SpectrumTech** [MarlinFirmware/Marlin#23730]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

After building and installing latest bugfix firmware on my CR10S5 with a BTT SKR E3 Turbo, I try to autohome and the x-axis runs the wrong way and crashes if I don’t kill the power, after auto-homing a second time or two, the problem goes away. The latest release doesn’t do that, but it fails auto Z align for no apparent reason… Marlin is getting to be a mess, too many chefs and they all think they have the best idea for how to do something, which breaks everything. Stop it with the lame ass diagnostic pin warnings, for example. They ship the boards without the pins jumpered by default - we don’t need the warnings… errors and warnings should occur be used WHEN there IS actually a problem. Like it used to be.

### Bug Timeline

Today, when I tried to build bugfix after stable failed.

### Expected behavior

I expected it to move left, towards the X-axis limit switch, and yes, the direction bit is set properly before building.

### Actual behavior

It moved right instead of left, crashing into the X-axis tensioner. But after auto homing again, sometimes it takes more than once, it seems to magically work the right way. Magic shouldn’t happen in programming because magic doesn’t exist…

### Steps to Reproduce

Build the latest Bugfix (2/13/22) and install on a BTT SKR E3 Turbo, then  autohome, especially if the axis is center or center right of the middle of the bed.

### Version of Marlin Firmware

Bugfix - latest

### Printer model

CR10S5

### Electronics

BTT SKR E3 Turbo

### Add-ons

BLTouch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by SodiumEx** [comment]
You can just swap the wires on the motor plug
