### ISSUE TITLE
Can't Compile Firmware for SKR2

### ISSUE THREAD

**Issue by AmirYas** [MarlinFirmware/Marlin#23734]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello so I'm just trying to compile a firmware for my E3V2 using SKR2_REV B (STM32F429) with 5 TMC2209 drivers. I have been struggling with this for 2 days, and I am seeking help. Thank you. I attached both my config files in .zip[AmirYas_Config.zip](https://github.com/MarlinFirmware/Marlin/files/8059506/AmirYas_Config.zip)

### Bug Timeline

New

### Expected behavior

To Compile

### Actual behavior

Got this error:

<details><summary>Log Output</summary>

```
 PS C:\Users\ameer\Desktop\Marlin-bugfix-2.0.x> platformio run -e BIGTREE_SKR_2_F429
Processing BIGTREE_SKR_2_F429 (board: marlin_STM32F429VGT6; platform: ststm32@~12.1; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
In file included from c:\users\ameer\desktop\marlin-bugfix-2.0.x\marlin\src\inc\MarlinConfigPre.h:39,
                 from c:\users\ameer\desktop\marlin-bugfix-2.0.x\marlin\src\inc\marlinconfig.h:28,
                 from buildroot/share/PlatformIO/scripts/common-dependencies.h:29:
c:\users\ameer\desktop\marlin-bugfix-2.0.x\marlin\configuration.h:2614:2: error: #endif without #if
 2614 | #endif
      |  ^~~~~
CalledProcessError: Command '"C:\Users\ameer\.platformio\packages\toolchain-gccarmnoneeabi\bin\arm-none-eabi-g++.exe" -D__MARLIN_FIRMWARE__ -DNDEBUG -DHAL_STM32 -DUSBCON -DUSBD_USE_CDC -DTIM_IRQ_PRIO=13 -DHAL_PCD_MODULE_ENABLED -DHAL_HCD_MODULE_ENABLED -DUSBHOST -DUSBH_IRQ_PRIO=3 -DUSBH_IRQ_SUBPRIO=4 -DUSE_USBHOST_HS -DUSE_USB_HS_IN_FS -DUSBD_IRQ_PRIO=5 -DUSBD_IRQ_SUBPRIO=6 -DHSE_VALUE=8000000U -DHAL_SD_MODULE_ENABLED -DPIN_SERIAL3_RX=PD_9 -DPIN_SERIAL3_TX=PD_8 -D__MARLIN_DEPS__ -w -dM -E -x c++ buildroot/share/PlatformIO/scripts/common-dependencies.h' returned non-zero exit status 1.:
  File "C:\Users\ameer\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 179:
    env.SConscript(item, exports="env")
  File "C:\Users\ameer\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\ameer\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\ameer\Desktop\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 247:
    apply_features_config()
  File "C:\Users\ameer\Desktop\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 133:
    if not env.MarlinFeatureIsEnabled(feature):
  File "C:\Users\ameer\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Util.py", line 742:
    return self.method(*nargs, **kwargs)
  File "C:\Users\ameer\Desktop\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 216:
    load_marlin_features()
  File "C:\Users\ameer\Desktop\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 204:
    define_list = run_preprocessor(env)
  File "C:\Users\ameer\Desktop\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\preprocessor.py", line 42:
    define_list = subprocess.check_output(cmd, shell=True).splitlines()
  File "C:\Users\ameer\.platformio\python3\lib\subprocess.py", line 424:
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\ameer\.platformio\python3\lib\subprocess.py", line 528:
    raise CalledProcessError(retcode, process.args,
================================================================= [FAILED] Took 2.07 seconds =================================================================

Environment         Status    Duration
------------------  --------  ------------
BIGTREE_SKR_2_F429  FAILED    00:00:02.071
============================================================ 1 failed, 0 succeeded in 00:00:02.071 ============================================================

```
</details>

### Steps to Reproduce

Hit Compile

### Version of Marlin Firmware

Bugfix 2.0.x

### Printer model

E3V2

### Electronics

SKR2_REV B (STM32F429) TMC2209

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Pronterface

**Comment by ellensp** [comment]
"Configuration.h:2614:2: error: #endif without #if"
You have broken the Configuration.h structure 

Line 2612 you have

```CPP
//#if ENABLED(DGUS_LCD_UI_MKS)
  //#define USE_MKS_GREEN_UI
#endif
```

either enable the #if or disable the #endif



This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
