### ISSUE TITLE
[BUG] X_AXIS_TWIST_COMPENSATION settings are not saved in EEPROM

### ISSUE THREAD

**Issue by Giuseppe499** [MarlinFirmware/Marlin#23744]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The settings of the feature X_AXIS_TWIST_COMPENSATION are not stored in EEPROM. When I use the X-Twist wizard, the correction values are computed, but if I save the settings to EEPROM and restart the printer the settings are not restored.

### Bug Timeline

Marlin 2.0.9.3

### Expected behavior

The settings for the feature X_AXIS_TWIST_COMPENSATION are restored after I save them and restart the printer

### Actual behavior

When I use the X-Twist wizard, the correction values are computed, but if I save the settings to EEPROM and restart the printer the settings are not restored.

### Steps to Reproduce

1. Run the X-Twist Wizard
2. Save Settings
3. Restart printer
4. Check if X_AXIS_TWIST_COMPENSATION settings are restored

### Version of Marlin Firmware

Marlin 2.0.9.3

### Printer model

Tronxy X8

### Add-ons

BL Touch

### Bed Leveling

ABL Bilinear mesh

### Host Software

OctoPrint

### Additional information & file uploads

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/8073432/Configurations.zip)

**Comment by gordo3di** [comment]
Here's the code I used to save the x-twist values. I'm not sure if there is a better way to store the settings other than enqueuing M500 but it worked for me.

https://github.com/MarlinFirmware/Marlin/pull/23238#issuecomment-1041571675

**Comment by thisiskeithb** [comment]
#23745 has been merged.

**Comment by Giuseppe499** [comment]
Hi,

I tried the `bugfix-2.0.x` branch with X_AXIS_TWIST_COMPENSATION enabled on my TronxyX8, but it doesn't work.

After the merge of PR #23745, the printer always give me an EEPROM "Index Error" on startup. If I try to reset, save and load the settings I get the same EEPROM "Index Error".

I think that this problem is caused by the `SettingsDataStruct` being wrong in `/Marlin/src/module/settings.cpp`.
@thinkyhead made this change in the PR #23745:

```diff
  //
  // X_AXIS_TWIST_COMPENSATION
  //
  #if ENABLED(X_AXIS_TWIST_COMPENSATION)
-    float xatc_spacing, xatc_start;
-    xatc_array_t xatc_z_values; 
+    XATC xatc
  #endif
```
(Note: actually in the first commit of the PR the type `xatc_array_t` was named `xatc_points_t`)

If I revert this change, the problem is fixed.


I think that this problem should be fixed before closing this issue.

**Comment by thisiskeithb** [comment]
Since that PR has already been merged, can you submit a new one with the fix...again?

**Comment by thisiskeithb** [comment]
PR has been submitted: https://github.com/MarlinFirmware/Marlin/pull/23911

Thanks @ellensp!

**Comment by Giuseppe499** [comment]
> Since that PR has already been merged, can you submit a new one with the fix...again?

I was about to submit the PR but @ellensp was much faster than me :joy: .

Thanks @ellensp!
