### ISSUE TITLE
[BUG] POWER_LOSS_RECOVERY not working properly MKS Robin nano V3

### ISSUE THREAD

**Issue by andelsalam** [MarlinFirmware/Marlin#23742]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

POWER_LOSS_RECOVERY 
not working properly on marlin 2.0.x bugfix and Mks-Robin-Nano-Marlin2.0-Firmware-master
when power outage and power on again choise for resume print or stop print not appear, I think like machine not reading PLR file on sd card or USB
[marlin.settings.zip](https://github.com/MarlinFirmware/Marlin/files/8069254/marlin.settings.zip)

### Version of Marlin Firmware

marlin 2.0.x bugfix and Mks-Robin-Nano-Marlin2.0-Firmware-master

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Additional information & file uploads

[marlin.settings.zip](https://github.com/MarlinFirmware/Marlin/files/8069278/marlin.settings.zip)

**Comment by robbycandra** [comment]
Duplicate with #23292
