### ISSUE TITLE
ILI9486 TFT controller 

### ISSUE THREAD

**Issue by mkornmue** [MarlinFirmware/Marlin#23779]
### Is your feature request related to a problem? Please describe.

Is it possible to use the ILI9486 display 3.5 inch with the ILI9488 controller?

I want to use my Android 3.5 inch display on my octopus mainboard because it is laying around.

### Describe the feature you want

ILI9486 support for marlin

**Comment by thisiskeithb** [comment]
No, it's not supported.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/23787

**Comment by gerthalberg** [comment]
> Duplicate of #23787

This is not a duplicate of #23787 it's related since it concerns the same driver. but this request want's to use the spi interface for which there is interface - but wants to use the ILI9486 instead of the ILI9488

**Comment by thisiskeithb** [comment]
ILI9486  is not supported: https://github.com/MarlinFirmware/Marlin/issues/18129#issuecomment-649974099

https://github.com/MarlinFirmware/Marlin/issues/23787 is already asking for support. This is a duplicate.
