### ISSUE TITLE
[BUG] (Knocking sound from extruder stepper TMC2209)

### ISSUE THREAD

**Issue by udemir00** [MarlinFirmware/Marlin#23782]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

SKR 1.4 Turbo + TMC2209 ( vref=0,8V ) + Marlin  2.0.9.3

There is this knocking noise from extruder stepper. I couldnt figure out the problem.

https://youtu.be/0e6t03v2_G4

### Bug Timeline

It always existed

### Expected behavior

No Knocking sound is expected

### Actual behavior

Knocking sound 

### Version of Marlin Firmware

2.0.9.3

### Printer model

Creality Ender 3 Pro

### Electronics

SKR 1.4 Turbo + TMC2209

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
