### ISSUE TITLE
RE: Frontend for Marlin

### ISSUE THREAD

**Issue by jmger** [MarlinFirmware/Marlin#23790]
### Are you looking for hardware support?

Tevo Tornado and Ender 3 Max

### Describe the feature you want

Regards to the Frontend for Marlin. This would be really, really nice to have. Think about this as a web type interface, or added to Octoprint or something similar. But the main thing is this... Most options that uses want to change quickly and easily are already available as M code. So this does not seem complicated to program. An interface screen like what is on my Pi3 Repetier Server that just takes the form data fields and sticks it into the M code string and then save it to the Control Board. I type through the Terminal window of Octoprint and Repetier Server to change options like Steps Per/mm, Acceleration, and the like. But it would be nice to have a form screen where I could just change all setting at once and then save Setting. I bet it would not take more than a few hours to code.

**Comment by thisiskeithb** [comment]
[Auto Build Marlin](https://github.com/MarlinFirmware/AutoBuildMarlin) is an ongoing/active project and will eventually add a frontend for user configuration through VSCode.

<img width="906" alt="image" src="https://user-images.githubusercontent.com/13375512/155407582-0dc83a03-eddb-40c9-9cb2-75491963ab43.png">

**Comment by thinkyhead** [comment]
…eventually!
