### ISSUE TITLE
[BUG] Ender 3 BLTouch Bed Leveling not working properly- Nozzle crashes into print bed

### ISSUE THREAD

**Issue by thespica93** [MarlinFirmware/Marlin#23805]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi again,

I have an Ender 3 with a BLTouch and Neopixels.
The Neopixels are working perfect, but the bed leveling is an issue. The BLTouch I believe is configured properly in the code. The BLtouch is version 3.1, and has 1 5 pin cable connected to the Creality 4.2.2 board. 
Auto homing appears to be working, the nozzle sits dead center on the print bed.

However, when selecting bed leveling the nozzle goes to point 0,0 but the probe is off the bed. 
I was able to get around this by setting the PROBING_MARGIN to 40. But this doesn't seem correct

I verified the print bed was correct in the code. 
I even tried setting the X_MIN_POS, and Y_MIN_POS to the settings from Cura, but this just makes things worse.

I have looked over the code dozens of time and can't find the issue. 
The code will compile fine, but bed leveling is off.
Can someone look this over and see if its a bug or I'm just an idiot.
*I will attach the zipped file I have been working in, as well as a video showing the issue.
Thank you!

### Expected behavior

When selecting bed leveling, the nozzle should go to the front left corner with the probe on the print bed, and then second the probe should be center front, and then right front (the nozzle should be off the bed now, with the probe on the bed), and then row 2, and row 3.

### Actual behavior

BLtouch will auto home perfectly

Bed leveling will fail. Nozzle will go to point 0,0 and begin to lower, but the probe is not on the bed causing the nozzle to crash into the bed.

### Steps to Reproduce

1. Compile my code in the attachments
2. Load to an Ender 3 with Creality 4.2.2 board
3. auto home
4. Then select bed leveling

### Version of Marlin Firmware

2.0.x

### Printer model

Ender 3

### Electronics

Stock- came with Creality 4.2.2 board

### Add-ons

Bltouch, neopixels

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/8145341/Marlin.zip)
[IMG_9899.MOV.zip](https://github.com/MarlinFirmware/Marlin/files/8145342/IMG_9899.MOV.zip)

Attached is the Marlin Configuration files from my Firmware
And a short video showing the behavior.

Thank you for everything.
Please reach out with any question
-Nick

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
