### ISSUE TITLE
[BUG] Dont compile firmware with MKS-MINI12864-V3 and NEOPIXEL_LED

### ISSUE THREAD

**Issue by wirebeard** [MarlinFirmware/Marlin#23808]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Cant compile Marlin firmware for MKS TinyBee motherboard and graphical LCD MKS Mini 12864 v3 with Neopixel RGB backlight

```
Compiling .pio/build/mks_tinybee/src/src/HAL/ESP32/Tone.cpp.o
In file included from Marlin/src/HAL/ESP32/../../inc/MarlinConfig.h:50:0,
                 from Marlin/src/HAL/ESP32/HAL.cpp:24:
Marlin/src/HAL/ESP32/../../inc/SanityCheck.h:2596:6: error: #error "NEOPIXEL_LED requires NEOPIXEL_PIN and NEOPIXEL_PIXELS."
     #error "NEOPIXEL_LED requires NEOPIXEL_PIN and NEOPIXEL_PIXELS."
```

### Bug Timeline

After added in release 2.0.9.3 MKS TinyBee

### Expected behavior

Compile firmware without errors

### Actual behavior

Compile error

### Steps to Reproduce

1. Download Marlin 2.0.9.3 (current)
2. Edit Configuration.h to uncomment #define MKS_MINI_12864_V3; #define NEOPIXEL_LED
3. Attempt to compile in platformio

### Version of Marlin Firmware

2.0.9.3

### Electronics

Motherboard MKS TinyBee

### Add-ons

LCD MKS Mini 12864 V3

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8146016/Configuration.zip)
[error.txt](https://github.com/MarlinFirmware/Marlin/files/8146021/error.txt)

**Comment by ellensp** [comment]
Please note:
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).


You have #define MKS_MINI_12864  when you need #define MKS_MINI_12864_V3

This is a User configuration error.

**Comment by wirebeard** [comment]
With #define MKS_MINI_12864_V3 same error

**Comment by ellensp** [comment]
That is incorrect.
I get other error but not the same error.

**Comment by wirebeard** [comment]
Same error 

`#error "NEOPIXEL_LED requires NEOPIXEL_PIN and NEOPIXEL_PIXELS."`

**Comment by wirebeard** [comment]
Sorry, another error

` #error "Your FYSETC Mini Panel requires NEOPIXEL_TYPE to be NEO_RGB."`

with 

`#define NEOPIXEL_TYPE   NEO_GRB // NEO_GRBW / NEO_GRB - four/three channel driver type (defined in Adafruit_NeoPixel.h)`

**Comment by ellensp** [comment]
Because your dyslexic?
NEO_RGB != NEO_GRB

**Comment by wirebeard** [comment]
How do you know?  

After change to NEO_RGB:

#error "NEOPIXEL_LED requires NEOPIXEL_PIN and NEOPIXEL_PIXELS."

**Comment by ellensp** [comment]
3rd party library ESP3DLib does not work with anything newer than marlin 2.0.9.2 

It contains in espcom.cpp

```CPP
#if HAS_GRAPHICAL_LCD
#include <U8glib.h>
#endif
``` 

But the keyword HAS_GRAPHICAL_LCD no longer exists in Marlin and U8glib.h should be U8glib-HAL.h

I got it to compile under Marlin 2.0.x  with the following changes

//#define MKS_MINI_12864
#define MKS_MINI_12864_V3

Applying these changes https://github.com/MarlinFirmware/Marlin/pull/23562/files

Edit add Marlin/src/HAL/ESP32/u8g_esp32_spi.cpp  add #include "HAL.h"

and editing .pio/libdeps/mks_tinybee/ESP3DLib/src/espcom.cpp
commented out the above if block and updating the include so it becomes 
```
//#if HAS_GRAPHICAL_LCD
#include <U8glib-HAL.h>
//#endif
```

I cannot test the resulting firmware, I don't have the controller.

I could not get it to compile under bugfix at all

**Comment by ellensp** [comment]
Regarding Bugfix I have just had this patch added to marlin bugfix https://github.com/MarlinFirmware/Marlin/pull/23810 
and  this along with https://github.com/luc-github/ESP3DLib/pull/40  once this is merged it will then work on bugfix. 
I have not tried all your options  yet.   just the correct lcd MKS_MINI_12864_V3 and WEBSUPPORT with ESP3D_WIFISUPPORT
