### ISSUE TITLE
[BUG] Bugfix 2.0.x- Ender 3 Configuration- Default Environment issue

### ISSUE THREAD

**Issue by thespica93** [MarlinFirmware/Marlin#23804]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello,

I downloaded the latest bugfix version and the configurations with it. I transferred the Ender 3 4.2.2 board version into the Marlin folder. 

I opened Visual Studio Code, and set the default environment to "STM32F103RE_creality", and I attempted to compile without any other changes, and I am receiving an error listed below. I did not have this issue in the non bugfix version:

"*** [.pio/build/STM32F103RE_creality/FrameworkArduino/avr] /Users/nickspica/Downloads/Marlin-bugfix-2.0.x/.pio/build/STM32F103RE_creality/FrameworkArduino/avr: No such file or directory
Assembler messages:
Fatal error: can't create .pio/build/STM32F103RE_creality/FrameworkArduino/Stream.cpp.o: No such file or directory
*** [.pio/build/STM32F103RE_creality/FrameworkArduino/Stream.cpp.o] Error 1"

Thank you for your time.
-Nick

### Expected behavior

Once the build environment is set the file should compile without any other changes

### Actual behavior

Fatal error when compiling

### Steps to Reproduce

1. Download bugfix firmware 
2. download configuration files
3. transfer ender 3 configuration example file into bugfix marlin folder
4. open VSC and set default build environment as "STM32F103RE_creality"
5. Compile

### Version of Marlin Firmware

Bugfix 2.0.x

### Printer model

Creality Ender 3

### Electronics

stock

### Add-ons

Bltouch, neopixels

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/8145271/Marlin-bugfix-2.0.x.zip)

The Config file I uploaded already includes the Ender 3 example files

**Comment by thisiskeithb** [comment]
Hit compile again. VSCode/PIO will frequently fail on the first attempt.

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
