### ISSUE TITLE
Bed auto leveling Manual!!

### ISSUE THREAD

**Issue by Briangsouza** [MarlinFirmware/Marlin#2381]
It is possible to make a manual bal small adjustments at the time of printing, such as babystep Z to Delta would have as a reference the towers and Cartesian the midpoint of each side of the table

**Comment by thinkyhead** [comment]
With the latest code, you have the choice of an Auto Bed Leveling feature or a Manual (Mesh) Bed Leveling feature (for machines without Z probes).
