### ISSUE TITLE
[BUG] Emergency parser does not work over USB with mass storage enabled on STM32

### ISSUE THREAD

**Issue by jackwilsdon** [MarlinFirmware/Marlin#23818]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Emergency parser does not work over USB on STM32 devices with mass storage enabled (I've not tested any other serial ports).

Any commands that the emergency parser would normally intercept result in no output and no action being performed.

### Expected behavior

Emergency parser handles commands 

### Actual behavior

Emergency parser does not handle commands.

### Steps to Reproduce

1. Build with the flag `USBD_USE_CDC` unset, the flag `USBD_USE_CDC_MSC` set and the emergency parser enabled (environment `BIGTREE_OCTOPUS_V1_USB` has USB flags set to reproduce this).
2. Note that any commands the emergency parser would normally intercept no longer do anything when sent over USB.

### Version of Marlin Firmware

Marlin bugfix-2.0.x (Feb 27 2022 14:43:59)

### Electronics

BigTreeTech Octopus

### Additional information & file uploads

The following patch seems to fix the issue but I'm not sure if it's the right way to go about it:

```diff
diff --git a/Marlin/src/HAL/STM32/HAL.cpp b/Marlin/src/HAL/STM32/HAL.cpp
index 324a78316a..d28f506db9 100644
--- a/Marlin/src/HAL/STM32/HAL.cpp
+++ b/Marlin/src/HAL/STM32/HAL.cpp
@@ -89,7 +89,7 @@ void MarlinHAL::init() {
 
   SetTimerInterruptPriorities();
 
-  #if ENABLED(EMERGENCY_PARSER) && USBD_USE_CDC
+  #if ENABLED(EMERGENCY_PARSER) && (USBD_USE_CDC || USBD_USE_CDC_MSC)
     USB_Hook_init();
   #endif
 
diff --git a/Marlin/src/HAL/STM32/usb_serial.cpp b/Marlin/src/HAL/STM32/usb_serial.cpp
index b607275db5..0b2372f3a7 100644
--- a/Marlin/src/HAL/STM32/usb_serial.cpp
+++ b/Marlin/src/HAL/STM32/usb_serial.cpp
@@ -26,7 +26,7 @@
 
 #include "../../inc/MarlinConfigPre.h"
 
-#if ENABLED(EMERGENCY_PARSER) && USBD_USE_CDC
+#if ENABLED(EMERGENCY_PARSER) && (USBD_USE_CDC || USBD_USE_CDC_MSC)
 
 #include "usb_serial.h"
 #include "../../feature/e_parser.h"
```

**Comment by thisiskeithb** [comment]
Since you’ve provided a fix, can you open a PR? Discussions/testing can happen there.

**Comment by thisiskeithb** [comment]
Closing since you’ve opened a PR.
