### ISSUE TITLE
[BUG] Cannot compile for ststm32 on RPi 3B (toolchain unavailable)

### ISSUE THREAD

**Issue by rmeno12** [MarlinFirmware/Marlin#23815]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I'm trying to compile Marlin for a BigTreeTech SKR 2 on a Raspberry Pi 3 Model B Rev 1.2. PlatformIO is unable to find the gcc toolchain corresponding to `ststm32@~12.1`.

I am able to find references online that using `ststm32@~15.2` should provide a compatible version of the toolchain, but simply making that change in `ini/stm32-common.ini` didn't help.

### Bug Timeline

first time I've tried this

### Expected behavior

Normal compilation

### Actual behavior

Error from PlatformIO being unable to find the version of `gccarmnoneabi` for the RPi's architecture. Error is `Error: Could not find the package with 'platformio/toolchain-gccarmnoneeabi @ ~1.90201.0' requirements for your system 'linux_aarch64'`. Full output included below.

### Steps to Reproduce

1. clone Marlin on the `bugfix-2.0.x` branch
2. change the `default_envs` variable in `platformio.ini` to `BIGTREE_SKR_2`
3. run `pio run`

### Version of Marlin Firmware

bugfix-2.0.x

### Additional information & file uploads

Full output:
```
pi@raspberrypi:/tmp/Marlin $ pio run
Processing BIGTREE_SKR_2 (board: marlin_STM32F407VGT6_CCM; platform: ststm32@~12.1; framework: arduino)
---------------------------------------------------------------------------------------------------------
Tool Manager: Installing platformio/toolchain-gccarmnoneeabi @ ~1.90201.0
Error: Could not find the package with 'platformio/toolchain-gccarmnoneeabi @ ~1.90201.0' requirements for your system 'linux_aarch64'
```

git diff:
```
diff --git a/platformio.ini b/platformio.ini
index 3a02b5ab18..287172b5e2 100644
--- a/platformio.ini
+++ b/platformio.ini
@@ -13,7 +13,7 @@
 [platformio]
 src_dir      = Marlin
 boards_dir   = buildroot/share/PlatformIO/boards
-default_envs = mega2560
+default_envs = BIGTREE_SKR_2
 include_dir  = Marlin
 extra_configs =
     ini/avr.ini
```

**Comment by ellensp** [comment]
This is a platfomio issue
