### ISSUE TITLE
[BUG] STM32F103RET6_creality fails to compile for Ender 3 V2

### ISSUE THREAD

**Issue by BradA1234** [MarlinFirmware/Marlin#23829]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

STM32F103RET6_creality fails to compile for ender 3 V2. I am following a YouTube video to add in BLtouch/ filament sensor. please see time 8:00-10:00 for what is changed from default. https://www.youtube.com/watch?v=neS7lB7fCww

any direction is appreciated, I'm new to this

Error code:
<details><summary>Log Output</summary>

```
 Executing task: C:\Users\BradA\.platformio\penv\Scripts\platformio.exe run <

Processing STM32F103RET6_creality (platform: native; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
'"CC"' is not recognized as an internal or external command,
operable program or batch file.
CalledProcessError: Command '"CC" -D__MARLIN_FIRMWARE__ -DNDEBUG -D__MARLIN_DEPS__ -w -dM -E -x c++ buildroot/share/PlatformIO/scripts/common-dependencies.h' returned non-zero exit status 1.:
  File "C:\Users\BradA\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 179:
    env.SConscript(item, exports="env")
  File "C:\Users\BradA\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\BradA\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\BradA\Downloads\Marlin-bugfix-2.0.x\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", 
line 247:
    apply_features_config()
  File "C:\Users\BradA\Downloads\Marlin-bugfix-2.0.x\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", 
line 133:
    if not env.MarlinFeatureIsEnabled(feature):
  File "C:\Users\BradA\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Util.py", line 742:
    return self.method(*nargs, **kwargs)
  File "C:\Users\BradA\Downloads\Marlin-bugfix-2.0.x\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", 
line 216:
    load_marlin_features()
  File "C:\Users\BradA\Downloads\Marlin-bugfix-2.0.x\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", 
line 204:
    define_list = run_preprocessor(env)
  File "C:\Users\BradA\Downloads\Marlin-bugfix-2.0.x\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\preprocessor.py", line 42:
    define_list = subprocess.check_output(cmd, shell=True).splitlines()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 424: 
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 528: 
    raise CalledProcessError(retcode, process.args,
==================================================== [FAILED] Took 0.54 seconds ====================================================

Environment             Status    Duration
----------------------  --------  ------------
STM32F103RET6_creality  FAILED    00:00:00.538
=============================================== 1 failed, 0 succeeded in 00:00:00.538 ===============================================The terminal process "C:\Users\BradA\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
![image](https://user-images.githubusercontent.com/100664272/156108520-09594143-dec5-42e3-b650-6c7489be776d.png)
```
</details>

### Expected behavior

I expect it to compile

### Actual behavior

failed

### Version of Marlin Firmware

MARLIN-BUGFIX-2.0.X

### Printer model

ender 3 V@ 4.2.7

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
STM32F103RET6_creality is STM32F103RE_creality in bugfix and future marlins

**Comment by ellensp** [comment]
This was actually a bug in bugfix, 
It should have handled  attempting to use a retired environment name much better than this error.

I have submitted a request to have this fixed. 

Once this is added to the code It will now say 

Error: Build environment 'STM32F103RET6_creality' is incompatible with BOARD_CREALITY_V4. Use one of these: STM32F103RE_creality, STM32F103RE_creality_xfer, STM32F103RC_creality, STM32F103RC_creality_xfer, STM32F103RE_creality_maple
