### ISSUE TITLE
Send action command to host when the emergency stop is activated [FR] (feature summary)

### ISSUE THREAD

**Issue by muistiloppu** [MarlinFirmware/Marlin#23820]
### Is your feature request related to a problem? Please describe.

If the freeze feature is activated by pressing the emergency stop button then printer does nothing, but it is still buffering all commands from the host. When emergency button is released the printer is proceeding with all commands in the buffer. 
  The problem is when somebody has been leaving the emergency button down while printer hadn't been operating or what ever reason. When the printer operator turns the printer on, he has no idea that emergency button is activated and is trying to get the printer to work. Usually by pushing the movement keys multiple times different directions to see if the extruder head is moving. After while he recognizes that emergency button is pressed down and when he releases it, all those commands in the buffer are processed so that the printer may get damaged from the random extruder head movements. 

### Are you looking for hardware support?

No

### Describe the feature you want

The simple solution can be just to send the Action Command message to the host that emergency button is activated so that operator is informed about it.

**Comment by thisiskeithb** [comment]
If you have `HOST_ACTION_COMMANDS` and `HOST_PROMPT_SUPPORT`, prompts will go to the host.

Also be sure to enable `EMERGENCY_PARSER` for instant processing of `M108`, `M112`, `M410`, and `M876`.
