### ISSUE TITLE
[FR] Long Press Knob to Adjust Z Height 

### ISSUE THREAD

**Issue by 3DStyle** [MarlinFirmware/Marlin#23836]
### Is your feature request related to a problem? Please describe.

After canceling a print job with the X button on the RepRap LCD, the extruder stays above the printed part and touch it. 
You can't access the part to remove it and the nozzle can stick to it if it colds down while touching it.

### Describe the feature you want

There are two solutions for this issue:
1. After pressing the X button on the RepRap LCD, Z axis will raise up automatically. This feature was on Marlin 1.9.x.
2. Long press the LCD knob to access a Z height control menu which will let you to raise / lower Z axis. This feature is currently present in Prusa firmware.

**Comment by thisiskeithb** [comment]
These features exist as `EVENT_GCODE_SD_ABORT` and `MOVE_Z_WHEN_IDLE`.
