### ISSUE TITLE
 Gcode.busy_state did not reset

### ISSUE THREAD

**Issue by nickzhuang0613** [MarlinFirmware/Marlin#23830]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin 2.0.x does not seem to have the code to restore it when setting `gcode.busy_state` to `IN_HANDLER`  in `process_parsed_command`. Is there anything to consider?

### Version of Marlin Firmware

2.0.9.3

**Comment by GMagician** [comment]
Changes to `gcode.busy_state` is done in `KEEPALIVE_STATE` macro that uses a class (restorer) that is destroyed once out of scope. Once destroyed it assume original value

**Comment by nickzhuang0613** [comment]
> Changes to `gcode.busy_state` is done in `KEEPALIVE_STATE` macro that uses a class (restorer) that is destroyed once out of scope. Once destroyed it assume original value

I see. Thank you for your guidance.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
