### ISSUE TITLE
[BUG] Thermal runaway protection not working on Ender 3 V2

### ISSUE THREAD

**Issue by saskford** [MarlinFirmware/Marlin#23847]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I tested the thermal runaway protection using the USB method and also by disconnecting the print head heater wires. In both cases a warning was never issued and the printer continued to try and heat the print head.

### Bug Timeline

Not sure when it started as I just now ran the test

### Expected behavior

I expected thermal runaway protection to kick in and stop the printer

### Actual behavior

Printer continued to try and heat nozzle heater as long as power was supplied to printer.

### Steps to Reproduce

1. Remove print head heater wires from motherboard
2. turn on printer and set print nozzle to 200 degrees
3. wait for error message

### Version of Marlin Firmware

Jyers/E3V2-ManualMesh-3x3-v4.2.2-v2.0.1.bin

### Printer model

Creality Ender 3 V2

### Electronics

Stock, v4.2.2 motherboard

### Add-ons

none

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Additional information & file uploads

I do not compile firmware so I use some compiled by Jyers. 
https://github.com/Jyers/Marlin/releases
I have contacted him and he assures me that thermal runaway protection is enabled. If I use Creality firmware thermal runaway protection does work when I perform the same tests I mentioned above. I want to continue with Jyers firmware as it is very feature rich but it is very dangerous to not have this protection working.

**Comment by ellensp** [comment]
This is not official Marlin. It is Jyers fork of marlin, and as such any and all issues regarding this fork must be addresses by Jyers on their github
