### ISSUE TITLE
[BUG] Stepper motors make grinding sound with USB mass storage enabled

### ISSUE THREAD

**Issue by jackwilsdon** [MarlinFirmware/Marlin#23856]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When enabling USB mass storage (e.g. using the `BIGTREE_OCTOPUS_V1_USB` environment), the stepper motors make a grinding sound when moving and do not move smoothly.

This behavior subsides after a minute or so or when USB is unplugged.

### Expected behavior

Motors would remain silent and move smoothly.

### Actual behavior

Motors made a grinding noise and moved jerkily.

### Steps to Reproduce

1. Build Marlin with USB mass stroage enabled
2. Note that motors do not move smoothly and produce a grinding noise

### Version of Marlin Firmware

Marlin 2.0.9.3 (Mar  5 2022 12:33:18)

### Electronics

BigTreeTech Octopus

### Add-ons

TMC2208 in UART mode (also happens in standalone mode)

### Additional information & file uploads

I assume this is caused by some step timing inconsistencies with mass storage enabled but I'm having issues probing it at the moment. It's also entirely possible that this is caused by using the onboard SD card connection, as I see this enables SDIO support (which isn't enabled when using the LCD SD card connection).

Here's what it sounds like when the issue is happening: https://voca.ro/18v6DLOdFMXj

And when it is not: https://vocaroo.com/1oGSjzMRFBn2

There is nothing connected to this stepper motor.

Here's the configuration: [Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8190799/Configuration.zip)

And its changes:
```diff
diff --git a/Marlin/Configuration.h b/Marlin/Configuration.h
index 7162e74acb..c0724306c5 100644
--- a/Marlin/Configuration.h
+++ b/Marlin/Configuration.h
@@ -96,7 +96,7 @@
 
 // Choose the name from boards.h that matches your setup
 #ifndef MOTHERBOARD
-  #define MOTHERBOARD BOARD_RAMPS_14_EFB
+  #define MOTHERBOARD BOARD_BTT_OCTOPUS_V1_1
 #endif
 
 /**
@@ -107,7 +107,7 @@
  *
  * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
  */
-#define SERIAL_PORT 0
+#define SERIAL_PORT -1
 
 /**
  * Serial Port Baud Rate
@@ -2125,7 +2125,7 @@
  * SD Card support is disabled by default. If your controller has an SD slot,
  * you must uncomment the following option or it won't work.
  */
-//#define SDSUPPORT
+#define SDSUPPORT
 
 /**
  * SD CARD: ENABLE CRC
diff --git a/Marlin/Configuration_adv.h b/Marlin/Configuration_adv.h
index 2cccfce054..d4a3f7a604 100644
--- a/Marlin/Configuration_adv.h
+++ b/Marlin/Configuration_adv.h
@@ -1633,7 +1633,7 @@
    *
    * :[ 'LCD', 'ONBOARD', 'CUSTOM_CABLE' ]
    */
-  //#define SDCARD_CONNECTION LCD
+  #define SDCARD_CONNECTION ONBOARD
 
   // Enable if SD detect is rendered useless (e.g., by using an SD extender)
   //#define NO_SD_DETECT
```

**Comment by ellensp** [comment]
Default/provided configuration is for ramps with A4988's

**Comment by jackwilsdon** [comment]
Oops! I'll update the post (not sure why I thought it was a completely stock configuration 🤦).

This issue still happens even if I'm using the TMC2208s outside of UART mode (both with the `A4988` and `TMC2208_STANDALONE` driver types), so the new configuration I've attached still uses the A4988 option.

The issue also immediately goes away if I unplug the USB connection.

**Comment by ellensp** [comment]
This may be related. Someone just reported in Discord "If a large number of serial port data is received, the STEP signal is delayed."  USB being chatty might qualify. they where talking about stm32f407.

**Comment by jackwilsdon** [comment]
I've not been able to reproduce that myself with USB mass storage disabled (just tried sending a large amount of `M503`s over USB serial as fast as possible), but I've noticed that the heartbeat LED slows down dramatically (like >50%) when using USB mass storage.

**Comment by BreeOge** [comment]
I have had this exact same issue described and I am using an Octopus v1.1 with TCM2209.  I have had it shut down due to error.  I have not been able to reproduce it on a consistent basis, If I am, I will post the needed steps I find.

**Comment by jackwilsdon** [comment]
This issue is still present.
