### ISSUE TITLE
Probe offsets being ignored

### ISSUE THREAD

**Issue by stopwalve** [MarlinFirmware/Marlin#23850]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

It appears that the probe offset : #define NOZZLE_TO_PROBE_OFFSET { 17, 63.5, 0 }
is being ignored.  During probing nozzle is at probing location NOT the sensor

### Bug Timeline

Just installed (flashed)

### Expected behavior

Sensor should be at probing location

### Actual behavior

Nozzle at probing location

### Steps to Reproduce

1.  Flashed Marlin 2.0.9.3
2. Set offset in configuration.h
3.  Level bed (ABL) from printer menu

### Version of Marlin Firmware

2.0.9.3

### Printer model

Anet A9 (clone)

### Electronics

ANETV1.7

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/8189558/config.zip)

**Comment by thisiskeithb** [comment]
[Initialize your EEPROM](https://marlinfw.org/docs/features/eeprom.html) after flashing.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
