### ISSUE TITLE
Missing Laser Pin designation option.

### ISSUE THREAD

**Issue by edcasati** [MarlinFirmware/Marlin#23869]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Failure to compile.
Error due to missing pin designation.
SPINDLE_LASER_ENA_PIN
I can not find where to designate that pin number. (Configuration, aconfiguration_adv, or Pins)

`CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/marlin_fysetc_s6.html
PLATFORM: ST STM32 (12.1.1) > 3D Printer control board
HARDWARE: STM32F446RET6 180MHz, 128KB RAM, 512KB Flash
DEBUG: Current (stlink) External (blackmagic, jlink, stlink)
PACKAGES: 
 - framework-arduinoststm32 4.10900.200819 (1.9.0) 
 - framework-cmsis 2.50501.200527 (5.5.1) 
 - tool-dfuutil 1.9.200310 
 - toolchain-gccarmnoneeabi 1.90201.191206 (9.2.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 11 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <TMCStepper> 0.7.3
|   |-- <SPI> 1.0
|   |-- <SoftwareSerial> 1.0
|-- <SPI> 1.0
|-- <Servo> 1.1.2
|-- <EEPROM> 2.0.1
|-- <SoftwareSerial> 1.0
|-- <IWatchdog> 1.0.0
|-- <Wire> 1.0
Building in release mode
Compiling .pio/build/FYSETC_S6/src/src/HAL/STM32/HAL.cpp.o
Compiling .pio/build/FYSETC_S6/src/src/HAL/STM32/HAL_MinSerial.cpp.o
Compiling .pio/build/FYSETC_S6/src/src/HAL/STM32/HAL_SPI.cpp.o
Compiling .pio/build/FYSETC_S6/src/src/HAL/STM32/MarlinSPI.cpp.o
Compiling .pio/build/FYSETC_S6/src/src/HAL/STM32/MarlinSerial.cpp.o
Compiling .pio/build/FYSETC_S6/src/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp.o
Compiling .pio/build/FYSETC_S6/src/src/HAL/STM32/Servo.cpp.o
Compiling .pio/build/FYSETC_S6/src/src/HAL/STM32/eeprom_bl24cxx.cpp.o
Compiling .pio/build/FYSETC_S6/src/src/HAL/STM32/eeprom_flash.cpp.o
In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:49,
                 from Marlin/src/HAL/STM32/HAL_SPI.cpp:27:
Marlin/src/HAL/STM32/../../inc/SanityCheck.h:3560:6: error: #error "(SPINDLE|LASER)_FEATURE requires SPINDLE_LASER_ENA_PIN or SPINDLE_SERVO to control the power."
 3560 |     #error "(SPINDLE|LASER)_FEATURE requires SPINDLE_LASER_ENA_PIN or SPINDLE_SERVO to control the power."
      |      ^~~~~
I`

### Expected behavior

Expect to find a remarked SPINDLE_LASER_ENA_PIN somewhere in the donfig files

### Version of Marlin Firmware

02000901

### Printer model

Laser Cutter

### Host Software

OctoPrint

**Comment by thisiskeithb** [comment]
> Expect to find a remarked SPINDLE_LASER_ENA_PIN somewhere in the donfig files

If your motherboard is missing the pin definition, simply add a define anywhere in the config: `#define SPINDLE_LASER_ENA_PIN PIN_NUMBER_GOES_HERE`.

---
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
