### ISSUE TITLE
[BUG] All icons missing on Ender 3v2

### ISSUE THREAD

**Issue by ech0devv** [MarlinFirmware/Marlin#23860]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When compiling Marlin for my ender 3v2 (on the default branch, bugfix won't compile), it works fine, however there are no icons on the screen. For whatever reason, my display refuses to flash a DWIN_SET, so that's out of the question. I'll attach some images, maybe they'll be of assistance.
![AGC_20220306_142054277](https://user-images.githubusercontent.com/87653178/156939038-a7ef23dd-bb0a-4b00-86a8-5ed8fcb4f7a2.jpg)
![AGC_20220306_142048489](https://user-images.githubusercontent.com/87653178/156939042-bf234b0a-d8b4-45d1-9a9a-ac3a0b6c38eb.jpg)

### Bug Timeline

new bug, first time building

### Expected behavior

All icons exist on the display.

### Actual behavior

All icons missing.

### Steps to Reproduce

1. Build Marlin for the ender 3v2 on the default branch (2.0.x)
2. Flash it like normal

### Version of Marlin Firmware

2.0.93

### Printer model

creality ender 3 v2, main board 4.2.2

### Electronics

Stock

### Add-ons

CRTouch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by ech0devv** [comment]
Here are the config files:
[config.zip](https://github.com/MarlinFirmware/Marlin/files/8193358/config.zip)

**Comment by ech0devv** [comment]
Also it appears that some text is offset in a strange way, and some text is highlighted when it shouldn't be.

**Comment by thisiskeithb** [comment]
> my display refuses to flash a DWIN_SET, so that's out of the question

You need to figure out why because that's why you're having this issue. Try [following the readme](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Creality/Ender-3%20V2) again. Try some other name-brand SD cards as well.

**Comment by mriscoc** [comment]
Maybe you have a DACAI screen unit, you can check which screen you have by comparing it with the pictures from here: https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display

**Comment by ech0devv** [comment]
> Maybe you have a DACAI screen unit, you can check which screen you have by comparing it with the pictures from here: https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display

Alright, I'll try this :3
It appears I do have a DACAI screen unit, by the way, so thank you for finding that for me. Wouldnt have found it otherwise. Ill try it and see if it fixes

**Comment by ech0devv** [comment]
i have to go to school so i will in the afternoon
