### ISSUE TITLE
Build of Arduino Due with DRIVER_TYPE  TMC26X fails

### ISSUE THREAD

**Issue by FGSikasa** [MarlinFirmware/Marlin#23874]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

<details><summary>Error message</summary>

```
Compiling .pio\build\DUE\lib21d\TMC26XStepper\TMC26XStepper.cpp.o
.pio\libdeps\DUE\TMC26XStepper\TMC26XStepper.cpp: In member function 'char TMC26XStepper::getStallGuardThreshold()':
.pio\libdeps\DUE\TMC26XStepper\TMC26XStepper.cpp:375:18: error: '_BV' was not declared in this scope
     if (result & _BV(6)) {
                  ^~~
.pio\libdeps\DUE\TMC26XStepper\TMC26XStepper.cpp:375:18: note: suggested alternative: '_B'
     if (result & _BV(6)) {
                  ^~~
                  _B
.pio\libdeps\DUE\TMC26XStepper\TMC26XStepper.cpp: In member function 'void TMC26XStepper::send262(long unsigned int)':
.pio\libdeps\DUE\TMC26XStepper\TMC26XStepper.cpp:956:30: error: 'SPCR' was not declared in this scope
     unsigned char oldMode =  SPCR & SPI_MODE_MASK;
                              ^~~~
.pio\libdeps\DUE\TMC26XStepper\TMC26XStepper.cpp:956:30: note: suggested alternative: 'SPI'
     unsigned char oldMode =  SPCR & SPI_MODE_MASK;
                              ^~~~
                              SPI
.pio\libdeps\DUE\TMC26XStepper\TMC26XStepper.cpp:956:37: error: 'SPI_MODE_MASK' was not declared in this scope
     unsigned char oldMode =  SPCR & SPI_MODE_MASK;
                                     ^~~~~~~~~~~~~
.pio\libdeps\DUE\TMC26XStepper\TMC26XStepper.cpp:956:37: note: suggested alternative: 'SPI_MODE0'
     unsigned char oldMode =  SPCR & SPI_MODE_MASK;
                                     ^~~~~~~~~~~~~
                                     SPI_MODE0
*** [.pio\build\DUE\lib21d\TMC26XStepper\TMC26XStepper.cpp.o] Error 1
===================================================================== [FAILED] Took 69.08 seconds =====================================================================

Environment    Status    Duration
-------------  --------  ------------
DUE            FAILED    00:01:09.076
================================================================ 1 failed, 0 succeeded in 00:01:09.076 ================================================================ 
The terminal process "C:\Users\Phillip\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.
```
</details>

### Bug Timeline

new

### Expected behavior

I expected it to build.

### Actual behavior

Build fail.

### Steps to Reproduce

1. Selected board with Arduino Due
2. set DRIVER TYPE to TMC26X
3. Build

### Version of Marlin Firmware

Marlin version 2.0.9.3

### Printer model

e.g BOARD_RADDS, BOARD_RAMPS4DUE_EFF

**Comment by ellensp** [comment]
That is a 3rd party library https://github.com/trinamic/TMC26XStepper/

Looks like this library does not support DUE

Due doesn't have _BV macro or register SPCR

**Comment by ellensp** [comment]
Trinamic has just removed this library entirely. 
So not even they are supporting this any more

**Comment by thisiskeithb** [comment]
> Trinamic has just removed this library entirely.

I found the last good commit ID of `c1921b4` [using the WayBackMachine](https://web.archive.org/web/20201003004553/https://github.com/trinamic/TMC26XStepper) and forked an existing fork so we don't lose the commit history: https://github.com/thisiskeithb/TMC26XStepper

Ideally, this would live in MarlinFirmware or teemuatlut's GitHub, but it can be used in the interim.

Not that it works... but at least we still have a good copy.

**Comment by Bob-the-Kuhn** [comment]
I was able to get around the compile error by editing the two lines in **pio\libdeps\DUE\TMC26XStepper\TMC26XStepper.cpp** and enabling **TMC_USE_SW_SPI** in **Configuration_adv.h**.

Don't know if you'll have a functional system but at least it's a step in the right direction.

**Comment by thisiskeithb** [comment]
> Trinamic has just removed this library entirely.
> So not even they are supporting this any more

It’s now self-hosted & both 2.0.x & bugfix branches have been updated with the new URL: https://github.com/MarlinFirmware/Marlin/commit/d95dca94b9db85fdad3297ff28af6132573c972c

**Comment by bkuker** [comment]
@thisiskeithb Do you know if you could do the same for the 1.1 kids?

**Comment by thisiskeithb** [comment]
> Do you know if you could do the same for the 1.1 kids?

You’ll want to migrate to 2.x since 1.x is no longer being worked on.

**Comment by bkuker** [comment]
@thisiskeithb I agree, but philosophically I like the idea that older versions of software should be preserved in a buildable state for posterity, and objectively for anyone for whom 1.x is currently perfectly fine but needs to make a small tweak, this is a very small pain :)

Its not a big deal.

For anyone who hits this problem on 1.x, the same change can be applied to platformio.ini easily.

**Comment by thisiskeithb** [comment]
> @thisiskeithb Do you know if you could do the same for the 1.1 kids?

@bkuker: thinkyhead updated `1.1.x`: https://github.com/MarlinFirmware/Marlin/commit/02dcc0b80ed81f7263167cdb2fc68971fb3984e7
