### ISSUE TITLE
[BUG] IDEX - DUAL_X_CARRIAGE_MODE  in FULL_CONTROL does not manage hotend X offset properly  

### ISSUE THREAD

**Issue by fcza** [MarlinFirmware/Marlin#23872]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

I have been using IDEX DUAL_X_CARRIAGE_MODE  in "DXC_AUTO_PARK_MODE" for a while. In this mode, i calibrate the X hotend offset in marlin LCD (advanced menu). This works OK.

I now need to use IDEX DUAL_X_CARRIAGE_MODE  in "FULL_CONTROL" to manage tool change routine using custom instructions (gcode) in my slicer. HOWEVER, i find it impossible to apply a working HOTEND X offset so that both hotend are well calibrated on X.

### Bug Timeline

not sure

### Expected behavior

I expect the HOTEND X OFFSET setting  in the Marlin Advanced menu to tune heads X alignement  in IDEX FULL CONTROL MODE, like it does very well in AUTO_PARK_MODE

### Actual behavior

 in _IDEX_ FULL CONTROL MODE, Prints from each head are not aligned. Modifying the x offset seems to have no effects.

### Steps to Reproduce

Use IDEX DUAL_X_CARRIAGE_MODE  in "DXC_AUTO_PARK_MODE". (OK)
Calibrate Hotend X offset based on trial and error measures on dual head prints - untill perfect (OK)

Switch to "M605 S0"

Execute print with custom "on tool change" instruction to home the old tool...
RESULT: prints from both IDEX head do not lineup (around 2mm in my case) ==> ISSUE
Trying to calibrate X offset (marlin advanced menu) does not change the result ==> ISSUE

### Version of Marlin Firmware

vFIRMWARE_NAME:Marlin bugfix-2.0.x (Feb 12 2022 19:56:55)

### Printer model

TREX 3+

### Electronics

BTT OCTOPUS PRO 1.0

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Simplify3D

**Comment by fcza** [comment]
[idex-issue-marlin-config.zip](https://github.com/MarlinFirmware/Marlin/files/8209742/idex-issue-marlin-config.zip)

adding marlin config

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22998
