### ISSUE TITLE
G76 unknown command

### ISSUE THREAD

**Issue by impet14** [MarlinFirmware/Marlin#23875]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I tried to enable G76 to auto compensate probe offset. 
I tested send G76 but I got echo:Unknown command: "G76".

I uncommend in configuration_adv.h as
#define PTC_PROBE    // Compensate based on probe temperature
#define PTC_BED      // Compensate based on bed temperature
#define PTC_HOTEND   // Compensate based on hotend temperature
and 
//#define PTC_PROBE    // Compensate based on probe temperature
#define PTC_BED      // Compensate based on bed temperature
#define PTC_HOTEND   // Compensate based on hotend temperature
but I got unknown command G76 from both. how can I do? My device is tronxy 400 x5sa pro

My device is tronxy x5sa pro 400.
Here is my config https://github.com/impet14/marlin-x5sa-400-pro/blob/main/Marlin/Configuration_adv.h

### Bug Timeline

New

### Expected behavior

I expected the device should do compensation

### Actual behavior

nothing move and respond unknown command 

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin 2.0.9.3 (Mar 10 2022 01:28:34) 

### Printer model

Tronxy x5sa pro 400

### Electronics

Chitu v6

**Comment by thisiskeithb** [comment]
G76 requires `PTC_PROBE`: https://marlinfw.org/docs/gcode/G076.html
