### ISSUE TITLE
[BUG] Firmware will not compile for 4.2.7 board - STM32F103RET6_creality

### ISSUE THREAD

**Issue by 1337Reaper** [MarlinFirmware/Marlin#23888]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I've set default_envs = STM32F103RET6_creality and these errors pop up when trying to compile the latest firmware:

```
In file included from Marlin\src\lcd\dogm\marlinui_DOGM.cpp:46:
Marlin\src\lcd\dogm\dogm_Bootscreen.h:40:12: fatal error: ../../../_Bootscreen.h: No such file or directory
   40 |   #include "../../../_Bootscreen.h"
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\STM32F103RE_creality\src\src\lcd\dogm\marlinui_DOGM.cpp.o] Error 1
In file included from Marlin\src\lcd\dogm\status_screen_DOGM.cpp:32:
Marlin\src\lcd\dogm\dogm_Statusscreen.h:48:12: fatal error: ../../../_Statusscreen.h: No such file or directory
   48 |   #include "../../../_Statusscreen.h"
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\STM32F103RE_creality\src\src\lcd\dogm\status_screen_DOGM.cpp.o] Error 1
```
### Bug Timeline

New bug, just now when downloading newest firmware

### Expected behavior

Firmware to compile

### Actual behavior

Firmware failed to compile

### Steps to Reproduce

1. Set default_envs = STM32F103RET6_creality
2. Attempt to compile
3. Compile fails

### Version of Marlin Firmware

Bugfix 2.0.X

### Printer model

Ender 3 V4.2.7 Board

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by ellensp** [comment]
You have enabled SHOW_CUSTOM_BOOTSCREEN and CUSTOM_STATUS_SCREEN_IMAGE but you have not copied over or created the the required _Bootscreen.h and _Statusscreen.h

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
