### ISSUE TITLE
[FR] Support SPINDLE_LASER_FREQUENCY on more platforms

### ISSUE THREAD

**Issue by KillerBug** [MarlinFirmware/Marlin#23901]
### Is your feature request related to a problem? Please describe.

The default frequency of 2500 is not good for CO2 lasers and there is no way to change it on modern boards.  For example, it does nothing on an Octopus 1.1

### Are you looking for hardware support?

Octopus 1.1

### Describe the feature you want

I would like to be able to set SPINDLE_LASER_FREQUENCY to 20,000 when using an Octopus 1.1

**Comment by descipher** [comment]
#define MARLIN_DEV_MODE in configuration.h and it will work. 
FYI 20K is too high for almost every PSU out there.

**Comment by KillerBug** [comment]
20000hz is pretty common with CO2 lasers; it's the default on Ruida boards.

I just tested with dev mode turned on, I do get a change in tone when I change the frequency...but the buzzing remains even at 30khz, which shouldn't be.  Wish I had a scope to see if it's actually putting out 30khz.

**Comment by descipher** [comment]
What pins are you using?

**Comment by KillerBug** [comment]
PD13 for my enable pin and PE11 for my PWM pin.  I feel like at this point it may be more trouble shooting than feature request...been working on it 12 hours now and getting dizzy.  If the functionality exists and is just hidden in dev mode then I guess we are good.  Any idea why it's in dev mode BTW?

**Comment by descipher** [comment]
It already does exist, no feature request required.
Switch the pins around, PE11 is on TIM1 and it's system protected so 1K only. PD13 is on TIM4.
Most CO2 tubes will not respond to higher frequencies 20K is 16us I recommend you vary downward to see when you hit peek power.
