### ISSUE TITLE
[BUG] Error:Field planner_leveling_active mismatch

### ISSUE THREAD

**Issue by mnul** [MarlinFirmware/Marlin#23910]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Flashing the latest Bugfix 2.0 is giving me an EEPROM error. 
Reset (`M502`) works, but saving to EEPROM (`M500`) gives me an `EEPROM Datasizve error`.

Turning on `#define DEBUG_EEPROM_READWRITE` prints the error as `Error:Field planner_leveling_active mismatch`.

When I run `M504 `I get:
```
Error:EEPROM datasize error
echo:Index: 675 Size: 656
```

### Steps to Reproduce

1. Build Marlin bugfix 2.0
2. Flash Marlin bugfix 2.0
3. M502
4. M500
5. EEPROM error

### Version of Marlin Firmware

Marlin bugfix-2.0.x (Mar 17 2022 10:20:25)

### Printer model

Creality Ender 5

### Electronics

SKR V1.3, TMC2209, BLTouch

### Add-ons

Linear Rails

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8283565/Configuration.zip)

**Comment by ellensp** [comment]
Issue is with X_AXIS_TWIST_COMPENSATION eeprom settings, creating a pr

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/issues/23744#issuecomment-1069310196
