### ISSUE TITLE
[BUG] Compilation requires Enhanced/Pro UI settings even if the printer doesn't have the Ender 3 V2 screen enabled

### ISSUE THREAD

**Issue by Arakon** [MarlinFirmware/Marlin#23914]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Using the latest bugfix code (commit [653c847](https://github.com/MarlinFirmware/Marlin/commit/653c847bfbcf2d816cd67fab3716d64d66a185e3)).

When compiling for the SKR Mini E3 V3.0 (STM32G0B1RE_btt/BOARD_BTT_SKR_MINI_E3_V3_0), the following compilation errors appear:

![image](https://user-images.githubusercontent.com/12016360/158898634-9f4c836a-634e-4d6c-a54f-ba56742894eb.png)
The `CR10_STOCKDISPLAY` is configured, as I am using a standard Ender 3 with the above board and their TFT35.
Only by enabling all listed features, it's possible to compile.

### Bug Timeline

Current bugfix version. Last version I used was around 16th of February which did not need these changes.

### Expected behavior

Allowing me to compile without enabling features for a UI system that is not even used with my display.

### Actual behavior

See above. 

### Steps to Reproduce

Attempt to compile using my config files.

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.0.x (Mar 17 2022 22:10:45) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Printer EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

### Printer model

Ender 3

### Electronics

BTT SKR E3 Mini V3.0, TFT35

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/8292746/config.zip)

**Comment by ellensp** [comment]
Provided Configs files compile without issues and without going near proui

I can only presume you using an old platformio.ini 

which has -<src/lcd/e3v2/enhanced>  instead of  -<src/lcd/e3v2/proui> in default_src_filter
