### ISSUE TITLE
[FR] option to restore the "temperature before started print" on aborting a print

### ISSUE THREAD

**Issue by Wallby** [MarlinFirmware/Marlin#23940]
### Describe the feature you want

E.g. if writing custom gcode I think it is convenient to be able to abort a print but keep the bed warm. I think it would be nice if there is an option such that instead of a cooldown upon aborting a print it would restore the previously set temperature (i.e. the temperature before starting the print).

Perhaps..?..
```
//#define RESTORE_OLD_BEDTEMP_ON_ABORT
#if DISABLED(RESTORE_OLD_BEDTEMP_ON_ABORT)
#define BEDTEMP_ON_ABORT 0
#endif
```

**Comment by thisiskeithb** [comment]
This exists as `SD_ABORT_NO_COOLDOWN` and is **not recommended** for safety reasons:

https://github.com/MarlinFirmware/Marlin/blob/b44357db9df70559751b31f6a2e7483878253976/Marlin/Configuration_adv.h#L1541
