### ISSUE TITLE
[BUG] Creality V4.2.2  "Ender 3 MAX" Compilation failed 

### ISSUE THREAD

**Issue by spooky79** [MarlinFirmware/Marlin#23982]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Compilation failed 
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduinoVariant/PeripheralPins.c.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduinoVariant/variant.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/HardwareSerial.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/IPAddress.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/RingBuffer.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/Tone.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/USBSerial.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/VirtIOSerial.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/WMath.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/WSerial.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/WString.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/abi.cpp.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/avr/dtostrf.c.o: No such file or directory
arm-none-eabi-g++: error: .pio/build/STM32F103RE_creality/FrameworkArduino/hooks.c.o: No such file or directory
*** [.pio\build\STM32F103RE_creality\firmware-20220401-164101.elf] Error 1
[Conf_adv.txt](https://github.com/MarlinFirmware/Marlin/files/8398761/Conf_adv.txt)
[Conf.txt](https://github.com/MarlinFirmware/Marlin/files/8398762/Conf.txt)

### Bug Timeline

new

### Version of Marlin Firmware

2.0.x bugfix

### Printer model

Ender 3 MAX

### Electronics

Creality v4.2.2 

### Your Slicer

Cura

**Comment by ellensp** [comment]
Just hit compile again. Config files are fine.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
Just hit compile again. Config files are fine.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
