### ISSUE TITLE
[BUG] I'm having trouble getting Marlin 2.0.9.3 wrork on Sanguinololu 1.3a control board

### ISSUE THREAD

**Issue by pcmad** [MarlinFirmware/Marlin#23981]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I'm having trouble getting Marlin 2.0.9.3 wrork on Sanguinololu 1.3a control board

The faults include locked up stepper motors  no temperature Output  End stops not acknowledging And a lot of things are not working the .

The only thing that does seem to work OK is the out of filament sensor

After looking at verbose mode on my arduino ide  I get these messages also uploading the firmware via a arduino as ISP

Sanguinololu  control board 1.3a Microcontroller atmel 1284p pu

J tag disabled  for end stop To work

Marlin 1.1.9.1 work perfectly

error log

/home/user/arduino-1.8.19/arduino-builder -dump-prefs -logger=machine -hardware /home/user/arduino-1.8.19/hardware -hardware /home/user/.arduino15/packages -tools /home/user/arduino-1.8.19/tools-builder -tools /home/user/arduino-1.8.19/hardware/tools/avr -tools /home/user/.arduino15/packages -built-in-libraries /home/user/arduino-1.8.19/libraries -libraries /home/user/Arduino/libraries -fqbn=Sanguino:avr:sanguino:cpu=atmega1284p -vid-pid=2341_0001 -ide-version=10819 -build-path /tmp/arduino_build_713268 -warnings=none -build-cache /tmp/arduino_cache_783826 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=/home/user/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=/home/user/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14 -prefs=runtime.tools.avr-gcc.path=/home/user/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=/home/user/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2 -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=/home/user/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino7.path=/home/user/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.arduinoOTA.path=/home/user/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=/home/user/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -verbose /home/user/Desktop/3dprinter/firmware/Marlin-2.0.x/Marlin/Marlin.ino
/home/user/arduino-1.8.19/arduino-builder -compile -logger=machine -hardware /home/user/arduino-1.8.19/hardware -hardware /home/user/.arduino15/packages -tools /home/user/arduino-1.8.19/tools-builder -tools /home/user/arduino-1.8.19/hardware/tools/avr -tools /home/user/.arduino15/packages -built-in-libraries /home/user/arduino-1.8.19/libraries -libraries /home/user/Arduino/libraries -fqbn=Sanguino:avr:sanguino:cpu=atmega1284p -vid-pid=2341_0001 -ide-version=10819 -build-path /tmp/arduino_build_713268 -warnings=none -build-cache /tmp/arduino_cache_783826 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=/home/user/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=/home/user/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14 -prefs=runtime.tools.avr-gcc.path=/home/user/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=/home/user/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2 -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=/home/user/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino7.path=/home/user/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.arduinoOTA.path=/home/user/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=/home/user/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -verbose /home/user/Desktop/3dprinter/firmware/Marlin-2.0.x/Marlin/Marlin.ino
Using board 'sanguino' from platform in folder: /home/user/.arduino15/packages/Sanguino/hardware/avr/1.0.3
Using core 'arduino' from platform in folder: /home/user/.arduino15/packages/arduino/hardware/avr/1.8.5
Detecting libraries used...
/home/user/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega1284p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_SANGUINO -DARDUINO_ARCH_AVR -I/home/user/.arduino15/packages/arduino/hardware/avr/1.8.5/cores/arduino -I/home/user/.arduino15/packages/Sanguino/hardware/avr/1.0.3/variants/sanguino /tmp/arduino_build_713268/sketch/Marlin.ino.cpp -o /dev/null
/home/user/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega1284p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_SANGUINO -DARDUINO_ARCH_AVR -I/home/user/.arduino15/packages/arduino/hardware/avr/1.8.5/cores/arduino -I/home/user/.arduino15/packages/Sanguino/hardware/avr/1.0.3/variants/sanguino /tmp/arduino_build_713268/sketch/src/MarlinCore.cpp -o /dev/null
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/MarlinCore.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/core/utility.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/feature/pause.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/feature/runout.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/calibrate/G28.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/config/M301.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/config/M302.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/control/M80_M81.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/eeprom/M500-M504.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/feature/pause/M600.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/feature/runout/M412.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/host/M115.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/motion/G2_G3.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/queue.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/temp/M104_M109.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/temp/M105.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/temp/M106_M107.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/temp/M140_M190.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/temp/M155.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/gcode/temp/M303.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/module/endstops.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/module/motion.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/module/planner.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/module/settings.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/module/temperature.cpp
Error while detecting libraries included by /tmp/arduino_build_713268/sketch/src/module/tool_change.cpp

Generating function prototypes...
/home/user/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega1284p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_SANGUINO -DARDUINO_ARCH_AVR -I/home/user/.arduino15/packages/arduino/hardware/avr/1.8.5/cores/arduino -I/home/user/.arduino15/packages/Sanguino/hardware/avr/1.0.3/variants/sanguino /tmp/arduino_build_713268/sketch/Marlin.ino.cpp -o /tmp/arduino_build_713268/preproc/ctags_target_for_gcc_minus_e.cpp
/home/user/arduino-1.8.19/tools-builder/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /tmp/arduino_build_713268/preproc/ctags_target_for_gcc_minus_e.cpp
Compiling sketch...
Compiling libraries...
Compiling core...
Archiving built core (caching) in: /tmp/arduino_cache_783826/core/core_Sanguino_avr_sanguino_cpu_atmega1284p_69e06db4cea1daafc0a763812e40c218.a
Linking everything together...

Sketch uses 63574 bytes (48%) of program storage space. Maximum is 130048 bytes.
Global variables use 2636 bytes (16%) of dynamic memory, leaving 13748 bytes for local variables. Maximum is 16384 bytes.
/home/user/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17/bin/avrdude -C/home/user/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17/etc/avrdude.conf -v -patmega1284p -cstk500v1 -P/dev/ttyACM0 -b19200 -Uflash:w:/tmp/arduino_build_713268/Marlin.ino.hex:i 

avrdude: Version 6.3-20190619
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/home/user/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17/etc/avrdude.conf"
         User configuration file is "/home/user/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/ttyACM0
         Using Programmer              : stk500v1
         Overriding Baud Rate          : 19200
         AVR Part                      : ATmega1284P
         Chip Erase delay              : 55000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    10   128    0 no       4096    8      0  9000  9000 0xff 0xff
           flash         65    10   256    0 yes    131072  256    512  4500  4500 0xff 0xff
           lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00

         Programmer Type : STK500
         Description     : Atmel STK500 Version 1.x firmware
         Hardware Version: 2
         Firmware Version: 1.18
         Topcard         : Unknown
         Vtarget         : 0.0 V
         Varef           : 0.0 V
         Oscillator      : Off
         SCK period      : 0.1 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude: Device signature = 0x1e9705 (probably m1284p)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "/tmp/arduino_build_713268/Marlin.ino.hex"
avrdude: writing flash (63574 bytes):

Writing | ################################################## | 100% 60.17s

avrdude: 63574 bytes of flash written
avrdude: verifying flash memory against /tmp/arduino_build_713268/Marlin.ino.hex:
avrdude: load data flash data from input file /tmp/arduino_build_713268/Marlin.ino.hex:
avrdude: input file /tmp/arduino_build_713268/Marlin.ino.hex contains 63574 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 35.70s

avrdude: verifying ...
avrdude: 63574 bytes of flash verified

avrdude done.  Thank you.

### Bug Timeline

dont know but works on version 1.1.9.1

### Expected behavior

3d printer to work

### Actual behavior

The faults include locked up stepper motors  no temperature Output  End stops not acknowledging And a lot of things are not working the .

The only thing that does seem to work OK is the out of filament sensor

### Steps to Reproduce

update Marlin 2.0.9.3  on Sanguinololu 1.3a  with config above

### Version of Marlin Firmware

non atm 

### Printer model

riprap huxley

### Electronics

 Sanguinololu 1.3a

### Add-ons

none

### Your Slicer

Slic3r

### Host Software

Pronterface

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/8398675/config.zip)

**Comment by ellensp** [comment]
You say your using a Sanguinololu 1.3a and even include the pins file
But your Configuration.h is set to #define MOTHERBOARD BOARD_GEN7_14 which uses Marlin/src/pins/sanguino/pins_GEN7_14.h

You should have #define MOTHERBOARD BOARD_SANGUINOLOLU_12

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by pcmad** [comment]
i was having issues the same issues when is was set to BOARD_SANGUINOLOLU_12 ALSO
