### ISSUE TITLE
[BUG] Marlin freezes on boot screen on Archim 2 except when serial connection is made at startup

### ISSUE THREAD

**Issue by marciot** [MarlinFirmware/Marlin#23991]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When using a RepRapDiscount screen on an Archim 2, Marlin is locking up on the screen with the Marlin logo before reaching the main menu.

While attempting to troubleshoot this, I noticed that if I quickly opened a Putty serial console to the board right after pushing reset, I would see serial output and the board would boot correctly to the main menu and be fully useable. However, if I did not open the serial connection, the board would freeze at startup.

The board will also freeze if no serial cable is attached.

### Bug Timeline

This seem to have begun somewhere after January 22nd, which was the last time I pulled from upstream and everything worked.

### Expected behavior

I should be able to boot the board without an USB cable or without making a serial connection to it.

### Actual behavior

The only way to make the board useable is to quickly connect to it using Putty right after pushing reset. Since pushing reset causes any pre-existing serial connection to be dropped, this requires quite a bit of precise timing to get to work.

### Steps to Reproduce

1. Reset board with out serial cable.
2. Board freezes on Marlin logo
3. Connect serial cable to computer
4. Push reset
5. Board freezes on Marlin logo
6. Open Putty and configure it to connect to Marlin
7. Push reset and immediately hit the "Open" button in Putty
8. See text on Putty console and watch board successfully boot

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Bare controller with display (reported by user with TAZ 6)

### Electronics

Ultimachine Archim 2

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8405359/Configuration.zip)

**Comment by thisiskeithb** [comment]
Closing since  PR has been created.
