### ISSUE TITLE
Invalid function parameter 

### ISSUE THREAD

**Issue by doktorzaba** [MarlinFirmware/Marlin#24005]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

an error is reported when calling the print_2d_array function in abl.cpp (row 139): 
"Marlin\src\feature\bedlevel\abl\abl.cpp:141:3: error: cannot convert 'print_bilinear_leveling_grid()::<lambda(uint8_t, uint8_t)>' to 'const float*"

### Version of Marlin Firmware

2.0.9.3

### Bed Leveling

ABL Bilinear mesh

### Host Software

OctoPrint

**Comment by ellensp** [comment]
No configs, no steps to reproduce. 
Please fill out the template with requested information

**Comment by doktorzaba** [comment]
Thanks, I'm adding config.
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/8439472/Configs.zip)

**Comment by ellensp** [comment]
Provided configuration compiles without issues

But they will not works as is

This makes zero sense on a octopus
```
  #define X_MAX_PIN  3 // creality connects X_MAX switch to X_MIN(_PIN) motherbard connector
  #define Y_MAX_PIN 14 // creality connects Y_MAX switch to Y_MIN(_PIN) motherbard connector

```

**Comment by doktorzaba** [comment]
I'm upgrading an existing configuration and I'm not done yet, so it contains invalid lines. However, this is not related to this error. The error occurred after enabling #define AUTO_BED_LEVELING_BILINEA
![Error](https://user-images.githubusercontent.com/76561654/162157775-a1e4df5c-137e-440a-b1e8-04df593a6b34.PNG)
R

**Comment by ellensp** [comment]
Something wrong with your copy of marlin, or platformio as provided configs compiles without issues (with lots of warning due to redefined endstop pins) 

![success](https://user-images.githubusercontent.com/530024/162160281-0a01a145-c0a7-4d85-a86f-6b1ee4cc3c3b.png)


Delete your `Marlin\.pio` and `C:\Users\{username}\.platformio`  and try again (this will reinstall platformio and required libraries, this could take a little time)  

If that doesn't work it mus be issue in your copy of Marlin code

**Comment by doktorzaba** [comment]
So everything is deleted, reinstalled. Downloaded new clean Marlin, including with bug fixes https://marlinfw.org/meta/download/
I only allowed these two values
AUTO_BED_LEVELING_BILINEAR
PROBE_MANUALLY
Otherwise everything remained the same, compilation for mega2560
result:
![Error2](https://user-images.githubusercontent.com/76561654/162192295-fe2a5232-ddc8-4788-bd96-783c836a4817.PNG)

**Comment by ellensp** [comment]
Attach full build log. as same test for me compiles without issues

**Comment by doktorzaba** [comment]
I'm sending output from the environment after compilation, maybe that's what you need :)
[logs.zip](https://github.com/MarlinFirmware/Marlin/files/8442649/logs.zip)

**Comment by ellensp** [comment]
this makes zero sense...  Im using same versions.... without issues

**Comment by doktorzaba** [comment]
When I comment function call print_2d_array, the compilation passes.

**Comment by thisiskeithb** [comment]
> Something wrong with your copy of marlin, or platformio as provided configs compiles without issues (with lots of warning due to redefined endstop pins)

I'm seeing the same thing here. Other than the wall of warnings from endstop redefines, it compiles fine.

**Comment by doktorzaba** [comment]
I'm already desperate for that. I tried on another computer, a completely new installation and the same result. Even in the Arduino IDE.

![image](https://user-images.githubusercontent.com/76561654/162270155-aab67295-6d80-4878-99c0-fc8f4d541b40.png)

**Comment by ellensp** [comment]
Where exactly did you download code from. Ie the full url
How did you download the code, zip file? Git clone?  other?

**Comment by doktorzaba** [comment]
I have already downloaded several times from this address https://marlinfw.org/meta/download/ including bugfix. I will delete all previous attempts, create a new directory, copy the files, leave everything to the default, just enable AUTO_BED_LEVELING_BILINEAR +
PROBE_MANUALLY and run the compilation for mega 2560. Already tested on 2 PCs, with a clean installation of VS code and still the same
![Error4](https://user-images.githubusercontent.com/76561654/162371195-e4609b37-12ea-46fe-b381-05b43ab76021.PNG)

**Comment by doktorzaba** [comment]
This is my last installation
[Marlin-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/8448867/Marlin-2.0.x.zip)

**Comment by ellensp** [comment]
You have extracted bugfix over 2.0.x
So you directory has some old and some new code
Marlin/src/feature/bedlevel/abl/abl.cpp should not be in bugfix code
Marlin/src/feature/bedlevel/abl/abl.h should not be in bugfix code

see https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/Marlin/src/feature/bedlevel/abl
 
There are about 30 file like this that are from 2.0.x in your attached bugfix code example

You must extract into an empty directory

**Comment by doktorzaba** [comment]
So sorry, it was my fault. I first extracted 2.0.x.zip and then bugfix-2.0.x.zip. If I understand correctly, only bugfix-2.0.x.zip should be extracted, then the compilation will work fine.
Thank you very much for your help.
