### ISSUE TITLE
[BUG] PID Bed time out

### ISSUE THREAD

**Issue by Randwic** [MarlinFirmware/Marlin#24028]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello,

I recently changed the bed of my Flsun SR, I installed a 5mm thick aluminum bed above the heating plate. Now I can't do the PID of the bed anymore. However I ask for a temperature of 60°, is after a certain time it reaches 74/75° then this puts in time out. What can I do?

Sorry for the translation.

### Bug Timeline

New bug

### Expected behavior

That the PID is done normally

### Actual behavior

The PID is not done and I get the time out error

### Version of Marlin Firmware

Marlin 2.9.3 Bug fix

### Printer model

Fl Sun SR

### Electronics

Stock

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
