### ISSUE TITLE
A20T crash and freeze during print 

### ISSUE THREAD

**Issue by Sebxtreme** [MarlinFirmware/Marlin#24020]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Geeetech A20T a4988 soldered on board Marlin freeze any time during print , latest vertabreak firmware 

### Actual behavior

Freeze during print 

### Version of Marlin Firmware

Vertabreak 

### Printer model

Geeetech A20T

### Electronics

Stock

### Add-ons

None 

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Other (explain below)

### Additional information & file uploads

Need heelllppppo

**Comment by thisiskeithb** [comment]
> latest vertabreak firmware

We can’t support forks of Marlin, so you’ll need to open an issue in Vertabreak’s fork.

**Comment by Sebxtreme** [comment]
Oh no then I will try the latest original marlin.

Mary S.

Le 10 avr. 2022 à 23:16, Keith Bennett ***@***.***> a écrit :

﻿

Closed #24020<https://github.com/MarlinFirmware/Marlin/issues/24020>.
