### ISSUE TITLE
[BUG] M206 Z offset is broken

### ISSUE THREAD

**Issue by innerspacepilot** [MarlinFirmware/Marlin#24035]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Seems to be a typo in the code
[check comment ](https://github.com/MarlinFirmware/Marlin/commit/e5b651f407fcb743e2d00c45b0d361fb98230efb#r71198804)

### Version of Marlin Firmware

latest bugfix

**Comment by ellensp** [comment]
PR created, closing
