### ISSUE TITLE
[BUG] Erro flash firmaware.bin Bigtreetech Skr

### ISSUE THREAD

**Issue by Murilo-DOT** [MarlinFirmware/Marlin#24037]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I'm having problems compiling Marlin 2.9.3 firmware on my Btt Srk mini v1.1.
I already tried 
STM32F103RC_btt
STM32F103RC_btt_USB
STM32F103RC_btt_maple
STM32F103RC_btt_USB_maple

The compilation is done successfully, but when placing the SD on the board, the flash does not occur.
Also replaces cables and LCDS 2004 and 12864
I formatted the SDs in FAT32
I used 4 different brands (scandisk, samsung, orico, generic) and sizes (16gb, 8gb, 4gb, 128mb)
Test with different USB 2.0, 3.0, 3.1 ports
Test with different card readers
Tried the firmaware.bin and changed to BIGTREETECH.bigtreetech to no avail.
Clean card, it only has the firmware.bin file

### Bug Timeline

I don't know, I went to update the printer settings and now it doesn't work

### Expected behavior

Let the board flash and work

### Actual behavior

The board turns on, but nothing appears on the screen.

### Steps to Reproduce

marlin successfully compiled
Firmware.bin on SD
Sd on board and does not flash

### Version of Marlin Firmware

2.0.9.3

### Printer model

Creality 

### Electronics

upgrade board

### Your Slicer

Cura

**Comment by thisiskeithb** [comment]
Flashing is handled by the bootloader and not something Marlin has control of.

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
