### ISSUE TITLE
[BUG] Level Bed Corners menu using Z-Servo-Probe not working and Probe-offset is not taken into account

### ISSUE THREAD

**Issue by stream2me** [MarlinFirmware/Marlin#24032]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When i try to run Bed-leveling-Wizard with Z-Servo-probe enabled it did not deploy the probe. After it drives to all 4 corners it raised Z and start over. I also see that the Probe-offset is not added to the coordinates.

### Bug Timeline

It's new to me. It's the firsttime i use a Servo-Probe.

### Expected behavior

Use Z-Servo-Probe with applied Probe-offsets to level the bed.

### Actual behavior

After homing, before the probe enters the first turn, the probe should have been deployed. But this was not the case.
I fixed the code to do so. See [here](https://github.com/stream2me/Marlin/commit/1e203f2807f9500d5497e1779f106f422ae5779a) and [here](https://github.com/stream2me/Marlin/commit/d3f8f8aee1f7f1266f064862496246566a161e3c).
Now the probe is properly deployed and stowed.
But there is still a problem with the probe offset. It is not taken into account. The coordinates are still those for the Noozzle and not those for the probe.

### Steps to Reproduce

1. Setup a Servo-Probe in Config files.
2. Compile and start the bed level wizard.
3. Apply my changes to support the Servo-Probe
4. Compile and start the bed level wizard. Probe will now deploy and stow. But Probe-offset is still not applied.

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Creality Ender 3

### Electronics

MKS nano v3 

### Add-ons

Z-Servo-Probe(BFPTouch) connected to Z-max endstop pin

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Additional information & file uploads

If i change this [line](https://github.com/MarlinFirmware/Marlin/blob/2893060302b7251cb6d5cd258f264b1a87eedee4/Marlin/src/lcd/menu/menu_bed_corners.cpp#L270) to "current_position = current_position - probe.offset_xy;" everything works as expected.

I have created 3 logs.
The first log is without any changes in menu_bed_corners.cpp.
The second is with the changes to support the Z-Servo probe and the last is with the change I mentioned above.

Can anyone with a BLtouch confirm that the wizard is still working?

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8475275/configuration.zip)
[menu_bed_corners.cpp.txt](https://github.com/MarlinFirmware/Marlin/files/8475293/menu_bed_corners.cpp.txt)
[log.txt](https://github.com/MarlinFirmware/Marlin/files/8475301/log.txt)
[log1.txt](https://github.com/MarlinFirmware/Marlin/files/8475302/log1.txt)
[log2.txt](https://github.com/MarlinFirmware/Marlin/files/8475303/log2.txt)

**Comment by descipher** [comment]
BLtouch and Wizard works fine.
```
    /**
     * Enable to init the Probe Z-Offset when starting the Wizard.
     * Use a height slightly above the estimated nozzle-to-probe Z offset.
     * For example, with an offset of -5, consider a starting height of -4.
     */
    //#define PROBE_OFFSET_WIZARD_START_Z -4.0 <-should be enabled
```

**Comment by stream2me** [comment]
Thank you for the feedback.
But the suggested setting is for the probe offset wizard. My problem is with the bed leveling wizard. Perhaps you have misunderstood.

But I tried your suggestion anyway, but it makes no difference.
