### ISSUE TITLE
[BUG] Ender 3 v2 display incorrect after Stop/Abort

### ISSUE THREAD

**Issue by gorillale** [MarlinFirmware/Marlin#24038]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

After Printing, the display dont show correkt on stop/abort on ender 3v2 M2.0.9.3

### Bug Timeline

new on 2.0.9.3

### Version of Marlin Firmware

2.0.9.3

### Printer model

ender3v2

### Electronics

normal ender board 

### Add-ons

-

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

Cura

### Additional information & file uploads

After Printing, the display dont show correkt on stop/abort on ender 3v2 M2.0.9.3

**Comment by Bob-the-Kuhn** [comment]
We need more information before we can be of help.

A picture of the display along with a description of the problem(s) on the display is a must.  Best if we could see a good and a bad display.

Some questions that come to mind:

- What version of Marlin worked correctly?
- How is the print stopping?  Normal completion, sending abort command, removing SD card, ... ?

Your configuration files are also usually needed.

**Comment by ellensp** [comment]
Also need to identify the model of e3v2 display.
There are now 3 different known models of this display type.
Needs an image of the inside of the display

Identification: 
The originals the main chip is covered with a sticker.
Second version seen has the main chip F1C100s
Third version seen has the main chip SWM32SRET6

**Comment by gorillale** [comment]
Hi, pleas look at my picture on Marlin 2.0.9.3 (before 2.0.9.2 other display when printing)
I updated the display to from marlin folder after compile marlin.
Not known what chip you mean, i have the 4.2.2 board not the 4.2.7, the printing is working before, but on marlin 2.0.9.2 i not have the leveling hint of all points to display after leveling .
The second problem i have see to make this photos. 
- start printing on fresh started printer, (not homed).
- abort print, hotbeed move to the edge an overrun no detekt the endswitch?
- dont move the bed when not homed, it is my idea.

now the photos:
![20220415_071654](https://user-images.githubusercontent.com/87060392/163525153-1eb3e108-1f3c-4923-b3aa-7271be3f8502.jpg)
![20220415_071701](https://user-images.githubusercontent.com/87060392/163525166-5ebf450e-f449-42ca-b154-97a671fa76e9.jpg)
![20220415_071715](https://user-images.githubusercontent.com/87060392/163525177-de5d1cf9-abb1-4818-99bf-d4b6777836c6.jpg)
![20220415_071722](https://user-images.githubusercontent.com/87060392/163525190-ebff7fd3-117a-455c-862c-8fa09d72f91b.jpg)
![20220415_071730](https://user-images.githubusercontent.com/87060392/163525197-c2b4cd20-e814-4a02-83ce-0113d471c25b.jpg)

**Comment by gorillale** [comment]
and the display board with unnamed chip:
![20220415_073251](https://user-images.githubusercontent.com/87060392/163525967-76aa5b91-2d9a-47dc-8ddf-f791046b7e73.jpg)
![20220415_073327](https://user-images.githubusercontent.com/87060392/163525969-09f806ae-06df-49fe-a96f-fb809c56907d.jpg)

**Comment by gorillale** [comment]
on compile with visual studio code is mark "DWIN_CREALITY_LCD_ENHANCED"
LCD enhanced on 2.0.9.2 not work, "kill_screen" error on compile, i think you have removed this function and now is missing on 2.0.9.3

i hope this can help to find a solution,
thank you for your working on marlin.
regards
andrew

**Comment by thinkyhead** [comment]
> … `DWIN_CREALITY_LCD_ENHANCED` …

It is now called `DWIN_LCD_PROUI`.

**Comment by gorillale** [comment]
Sorry, I not have a entry with "DWIN_LCD_PROUI"

**Comment by ellensp** [comment]
@gorillale then your not testing bugfix https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/Configuration.h#L2931

**Comment by gorillale** [comment]
Ist this not Creality Display? I have buy an original ender 3 v2 with 4.2.2 Board inside.
Why DWIN_LCD_PROUI  ?

**Comment by gorillale** [comment]
i no more can compile the bugfix version:
Error: Build environment 'STM32F103RET6_creality' is incompatible with BOARD_CREALITY_V4. Use one of these: STM32F103RE_creality, STM32F103RE_creality_xfer, STM32F103RC_creality, STM32F103RC_creality_xfer, STM32F103RE_creality_maple

I no more sse what is to do, no manual no instructions.... i think i switch to original ware from creality, no future for me... i no a developer and without a seriosli manual to install all this i not can use this...

thank you, happi programing

**Comment by ellensp** [comment]
The valid options are the following as listed in the error.

STM32F103RE_creality
STM32F103RE_creality_xfer
STM32F103RC_creality
STM32F103RC_creality_xfer
STM32F103RE_creality_maple
etc

STM32F103RET6_creality is no longer valid option replaced with STM32F103RE_creality
In your platformio,ini

**Comment by mriscoc** [comment]
I you don't have the definition of DWIN_LCD_PROUI you must try with the latest bugfix.

**Comment by thisiskeithb** [comment]
@gorillale: Please start with a fresh copy of [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) since you've mixed up files/versions.

**Comment by gorillale** [comment]
Thank you all, the STM32F103RE_creality realy works, but other errors missing function i see.
I have downloaded marlin bugfix2 zip and marlin config bugfix2 zip.
copied the config from creality ender 3 v2 to the marlin folder
activated my settings bl touch.
i make this with all version before, but now many errors with missing functions
not known what i doing, is make this from a manual how to compile marlin with 
visual studio code

i will try moring the entry procedure again.

**Comment by gorillale** [comment]
It is not compilable, i have downloaded marlin and bugfixes.
Edited the Ender3v2 header to set bl-touch, now compiled.
Many Errors and warnings will be displayed, normal creality display compile is ok.
with xx_PROUI missing functions and errors.
simply uncompileable.

I tryed same with no changes on header but only _PROUUI enabled and others display disabled.
same.

**Comment by ellensp** [comment]
@gorillale You expect to much.

The only User interface for this display that supports all features is DWIN_MARLINUI.

All other user interfaces have specific requirement in what feature they will or will not support or what features they require enabled to operate correctly. 
The designers of these other user interfaces implement support for the features they want.
They are not all drop in replacements for each other.

In saying that 
to convert from DWIN_CREALITY_LCD to DWIN_LCD_PROUI for a standard Ender 3v2 only requires the following changes

Marlin even tells you what you need to change

First error
#error "INDIVIDUAL_AXIS_HOMING_SUBMENU is required with ProUI."
You find INDIVIDUAL_AXIS_HOMING_SUBMENU In Configuration.h and enable it

Second error
#error "LCD_SET_PROGRESS_MANUALLY is required with ProUI."
You find LCD_SET_PROGRESS_MANUALLY in Configuration_adv.h and enable it

Third error 
#error "STATUS_MESSAGE_SCROLLING is required with ProUI."
You find STATUS_MESSAGE_SCROLLING in Configuration_adv.h and enable it

Forth error
#error "BAUD_RATE_GCODE is required with ProUI."
You find BAUD_RATE_GCODE in Configuration.h and enable it

Fifth error
#error "SOUND_MENU_ITEM is required with ProUI."
You find SOUND_MENU_ITEM in Configuration_adv.h and enable it

Last error
#error "PRINTCOUNTER is required with ProUI."
You find PRINTCOUNTER in Configuration.h and enable it

These error message are there to help you, why do you ignore them?

Here are current bugfix configs for a Ender 3v2 with DWIN_LCD_PROUI a on a BOARD_CREALITY_V4 controller

[Bufix configuration Ender3v2 V422.zip](https://github.com/MarlinFirmware/Marlin/files/8602433/Bufix.configuration.Ender3v2.V422.zip)

**Comment by gorillale** [comment]
@ellensp Very thank you for your help, i not thinking that is into the Configuration_adv.h, sorry
Now i try again the same procedure.
Regards.

**Comment by gorillale** [comment]
compile is working, but repetier can connect no more.
i wondering what your doing, bug fix changed menus connection etc...
i think bether for me to switch original creality software that is 
teste and run without bugs.
(hint: Baudrate is 115k, same on repetier)

Thank you and happy programing
