### ISSUE TITLE
BL Touch Help

### ISSUE THREAD

**Issue by TonyM4119** [MarlinFirmware/Marlin#24033]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

So I am not sure if this is a marlin bug or something else but i have tried everything and cant seem to figure it out.. I have an ender 3 with a BTT octopus v1 board with tmc 2209 drivers and a bl touch. I cant get the bl touch working correctly i have tried all i can think of. Sometimes it will work but most times it wont. I go to home the printer and it will home x and y then move to home z but them the probe just goes in and out a bunch of time until finally it stops and gives me this error in octoprint Recv: Error:!! STOP called because of BLTouch error - restart with M999 Changing monitoring state from "Operational" to "Error".. and on when i home from the screen in gives me M112 shutdown. Im lost and dont no where else to look for help. If anyone has any ideas that would be great thanks in advance 

Tony 

### Version of Marlin Firmware

bugfix-2.0.x (Apr 12 2022 20:32:41)

### Printer model

Ender 3

### Add-ons

BL Touch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
