### ISSUE TITLE
[BUG] Water ripples on the surface of the model

### ISSUE THREAD

**Issue by dream111119** [MarlinFirmware/Marlin#24034]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When I was printing a curved surface, I found that there were serious wavy lines. I tried other machines, such as ender3-v2 and reduced the speed, and found that the wavy lines still exist. I suspect that it is not caused by increasing the speed in essence.
I would like to understand possible factors so that I can test。
What is the best configuration to solve this problem, I have tried the following configurations, no improvement
XY_FREQUENCY_LIMIT
ADAPTIVE_STEP_SMOOTHING
S_CURVE_ACCELERATION
JUNCTION_DEVIATION_MM

### Bug Timeline

always have

### Expected behavior

Shouldn't have wavy lines

### Actual behavior

Curved surface with wavy pattern

### Version of Marlin Firmware

bugfix-2.0.x

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Additional information & file uploads

![wave](https://user-images.githubusercontent.com/40389295/163092834-bfdcc26a-f34f-4110-b9da-c8385ba9797f.jpg)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
