### ISSUE TITLE
feedmultiply can not change from LCD panel with Delta configuration.

### ISSUE THREAD

**Issue by GabeHC** [MarlinFirmware/Marlin#2404]
Board `BOARD_RAMPS_13_EFF`
Version 1.0.2 Delta configuration
LCD `REPRAP_DISCOUNT_SMART_CONTROLLER`
Symptom:  Feedrate stays fix at 100%. cannot be changed by encoder, `M220` working, only happens with Delta configuration. Still not finding anything wrong in `ultralcd.cpp` code yet. Am I looking in the right place?

**Comment by thinkyhead** [comment]
That's probably fixed in the current Development (1.0.3 dev) HEAD. Are you able to try that at this time?

**Comment by GabeHC** [comment]
Confirm fixed V1.0.3
Like to know how to fix it on V1.0.2

**Comment by thinkyhead** [comment]
Do you have the line `#define ULTIPANEL_FEEDMULTIPLY` in your `Configuration_adv.h` file? Evidently in 1.0.2 it was left out of one or more of the example configurations, including the delta config.

**Comment by GabeHC** [comment]
Thanks! It works now on V1.0.2
