### ISSUE TITLE
Power Loss Recovery in 2.0.9.3 nozzle hits bed on resume

### ISSUE THREAD

**Issue by krisnty** [MarlinFirmware/Marlin#24061]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello brain trust!

Issue:
Using the red power switch to simulate the power loss....
When power loss has been triggered, the printer nozzle **immediately** moves up but SKR reboots.  What I mean here is that by the time that the 24V UPS dissipates it remaining power the SKR has time to turn off but start back up again as if power was restored.  At that time the screen displays the resume or stop print options.  A second or two later, the remaining power in the UPS is gone and the SKR screen finally turns off.

Pulling the power plug from the power supply....
Same as above for one exception..... instead of immediately moving the nozzle up, the printer continues to print for a second or two.

Regardless or how the power is lost....
When power is restored. The resume option is selected and nozzle/bed heat up as expected.  The nozzle rehomes X and Y then moves to the print, however the nozzle descends to the print but does not stop at the print but past it buries the nozzle into the print itself.  

I have updated to the most recent version of Marlin as well as the most recent bugfix.  Issue persists, but **differently**.  With the bugfix, the print head does not move to the printed part but buries the nozzle into the bed at (0,0).  With the non bugfix version, the nozzle will move to the part but buries the nozzle into the print.

I hope this descriptions present this problem well enough to find an answer. 

### Bug Timeline

04/15/2022

### Expected behavior

The following is the expected behavior...

1. Power is lost
2. Nozzle moves up
3. Power returned
4. Select "resume print"
5. Nozzle / Bed reheat
6. Nozzle rehomes X and Y
7. Purge some filament 
8. Move to print
9. Z moves down to print and continues the print.

### Actual behavior

As mentioned in the description...

Marlin:
1. Power is lost
2. Nozzle moves up
3. Power returned
4. Select "resume print"
5. Nozzle / Bed reheat
6. Nozzle rehomes X and Y
7. Purge some filament 
8. Move to print
9. Z moves down to print and does not stop descending to continue print

Bugfix:
1. Power is lost
2. Nozzle moves up
3. Power returned
4. Select "resume print"
5. Nozzle / Bed reheat
6. Nozzle rehomes X and Y
7. Purge some filament 
8. Z moves down at point (0,0) and does not stop descending

### Version of Marlin Firmware

Marlin 2.0.9.3 and bugfix 2.0.9.3

### Printer model

Ender 3 Pro

### Electronics

BTT SKR E3V3

### Add-ons

BTT 24V UPS

### Bed Leveling

Official BL Touch v3.1

### Your Slicer

Cura

**Comment by Sonicboom247** [comment]
check this in your firmware
```cpp
// Enable if Z homing is needed for proper recovery. 99.9% of the time this should be disabled!
    //#define POWER_LOSS_RECOVER_ZHOME
    #if ENABLED(POWER_LOSS_RECOVER_ZHOME)
```

**Comment by krisnty** [comment]
Verified in code.  
It was already set to the following.
```cpp
    // Enable if Z homing is needed for proper recovery. 99.9% of the time this should be disabled!
    //#define POWER_LOSS_RECOVER_ZHOME
    #if ENABLED(POWER_LOSS_RECOVER_ZHOME)
      //#define POWER_LOSS_ZHOME_POS { 0, 0 } // Safe XY position to home Z while avoiding objects on the bed
    #endif
```

**Comment by krisnty** [comment]
Ok,  this morning I downloaded a fresh copy of the bugfix.  I then only made minimal changes to the firmware for my printer.  After installing it the issue has now been resolved and does not seem to be present in the current bugfix.

Thank you Sonicboom247 for assisting me.
