### ISSUE TITLE
[BUG] `ROTATE_PROGRESS_DISPLAY` errors out with Extruders 0

### ISSUE THREAD

**Issue by CAP1Sup** [MarlinFirmware/Marlin#24085]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When attempting to enable `ROTATE_PROGRESS_DISPLAY` on a machine without any extruders, the build will fail. I would have fixed this myself and proposed a PR, but I don't know enough about Marlin to understand how to properly fix the issue. The error is as follows: 
![image](https://user-images.githubusercontent.com/42127153/165146962-5b071659-048e-4c8f-818b-b6a4afe92518.png)

### Bug Timeline

Just found this today

### Version of Marlin Firmware

Latest bugfix-2.0.x

### Additional information & file uploads

[WITH_EXTRUDERS.zip](https://github.com/MarlinFirmware/Marlin/files/8556907/WITH_EXTRUDERS.zip)
[WITHOUT_EXTRUDERS.zip](https://github.com/MarlinFirmware/Marlin/files/8556908/WITHOUT_EXTRUDERS.zip) (causes error)

**Comment by GMagician** [comment]
I think it should be replaced with a simple "E:". In this case text means "elapsed" not extruder

**Comment by thisiskeithb** [comment]
Closing since a PR has been created: https://github.com/MarlinFirmware/Marlin/pull/24087
