### ISSUE TITLE
MP SCARA homing works, but link 1 endstop doesn't work and link 2 enstop works for both axis [BUG] (bug summary)

### ISSUE THREAD

**Issue by gnmrc-s** [MarlinFirmware/Marlin#24099]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Using Marlin 2.0.8 MP_SCARA homing works but it useful only the link 2 endstop

### Bug Timeline

new bug

### Expected behavior

I expected that endstop link 1 homed link1 and endstop link 2 homed link 2

### Actual behavior

endstop link 2 stopped both axis

### Steps to Reproduce

none

### Version of Marlin Firmware

2.0.8

### Printer model

Custom SCARA machine

### Electronics

creality v 4.2.7 board

### Add-ons

none

### Your Slicer

Cura

### Host Software

Repetier Host

### Additional information & file uploads

[Configuration files.zip](https://github.com/MarlinFirmware/Marlin/files/8584132/Configuration.files.zip)

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/10089

**Comment by thisiskeithb** [comment]
Again. Please stop opening multiple issues for SCARA homing. Use the linked thread.

**Comment by gnmrc-s** [comment]
But it’s not the same here it’s not an homing problem, homing works, it’s an endstop problem, I fixed the endstop not working and I fixed the homing not activating
