### ISSUE TITLE
[BUG] Marlin 2 error: "BLTOUCH requires Z_MIN_ENDSTOP_INVERTING set to false. Please update your Configuration.h file.", but I don`t have a BLTOUCH

### ISSUE THREAD

**Issue by mtsegundo** [MarlinFirmware/Marlin#24108]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I am using Marlin 2 for my MKS Robin Nano 3.1 and when I try to compile, I am getting this error "buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/Conditionals_LCD.h:798:8: error: #error "BLTOUCH requires Z_MIN_ENDSTOP_INVERTING set to false. Please update your Configuration.h file.""

The problem is that my end stop is NO, so I have to set my Z_MIN_ENDSTOP_INVERTING to true and I don`t have a BLTOUCH. How can I fix it?

### Version of Marlin Firmware

2.0.9.2

### Additional information & file uploads

#define X_MIN_ENDSTOP_INVERTING true  // Set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING true // Set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING true  // Set to true to invert the logic of the endstop.
#define I_MIN_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define J_MIN_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define K_MIN_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define X_MAX_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define Y_MAX_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define Z_MAX_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define I_MAX_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define J_MAX_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define K_MAX_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define Z_MIN_PROBE_ENDSTOP_INVERTING false  // Set to true to invert the logic of the probe.

**Comment by ellensp** [comment]
This only occurs if you have #define BLTOUCh enabled with Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN and Z_MIN_ENDSTOP_INVERTING

If you dont have a bltouch, dont enable bltouch

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by mtsegundo** [comment]
> //#define BLTOUCh

When I do this, I get this error:


Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL.cpp:30:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:902:6: error: #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
  902 |     #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
      |      ^~~~~
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\Sd2Card_sdio_stm32duino.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:902:6: error: #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
  902 |     #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
      |      ^~~~~
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\Servo.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:902:6: error: #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
  902 |     #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,   
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:902:6: error: #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
  902 |     #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
      |      ^~~~~
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_flash.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:902:6: error: #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
  902 |     #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
      |      ^~~~~
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,   
                 from Marlin\src\HAL\STM32\eeprom_bl24cxx.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:902:6: error: #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
  902 |     #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
      |      ^~~~~
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_if_iic.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:902:6: error: #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
  902 |     #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
      |      ^~~~~
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_sram.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:902:6: error: #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
  902 |     #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
      |      ^~~~~
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_sdcard.cpp:31:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:902:6: error: #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
  902 |     #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
      |      ^~~~~
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\HAL_SPI.cpp.o] Error 1
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\Sd2Card_sdio_stm32duino.cpp.o] Error 1
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\MarlinSerial.cpp.o] Error 1
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\eeprom_flash.cpp.o] Error 1
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\Servo.cpp.o] Error 1
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\HAL.cpp.o] Error 1
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\eeprom_if_iic.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_wired.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:902:6: error: #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
  902 |     #error "BABYSTEP_ZPROBE_OFFSET requires a probe."
      |      ^~~~~
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1679:6: error: #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo."
 1679 |     #error "Auto Bed Leveling requires one of these: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or a Z Servo." 
      |      ^~~~~
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\eeprom_bl24cxx.cpp.o] Error 1
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\eeprom_sram.cpp.o] Error 1
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\eeprom_sdcard.cpp.o] Error 1
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive_msc\src\src\HAL\STM32\eeprom_wired.cpp.o] Error 1

**Comment by mtsegundo** [comment]
I found a way.
I desenable AUTO_BED_LEVELING_BILINEAR and BABYSTEPPING
