### ISSUE TITLE
[BUG] (BTT SKR GTR TMC CONNECTION ERROR)

### ISSUE THREAD

**Issue by Enzo-Enz** [MarlinFirmware/Marlin#24104]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hi
there is this error on LCD when my printer turns on and stepper motor vibrating except of moving!
 I am using skr gtr and tmc2130

![6d4cc613-aa42-451a-b0ec-dac8ff4a48bb](https://user-images.githubusercontent.com/75531691/165916120-5303c5a8-a64b-4d88-9728-b971bcb7b75e.jpg)

![015b07c7-7454-4a2e-b885-19c6318f1866](https://user-images.githubusercontent.com/75531691/165916146-240bd52d-893f-441e-9bed-ebf93cbee876.jpg)

### Bug Timeline

old

### Version of Marlin Firmware

2.0.9.3

### Printer model

DIY printer

### Electronics

btt skr gtr/tmc2130

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/8589600/config.zip)

**Comment by ellensp** [comment]
You need to have external power connected, not just usb power.

And you need to look at results of M122, is it all or just one?

You have 4 tmcs configured but only one is pictured plugged in, this would also cause this error. 


This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by Enzo-Enz** [comment]
> You need to have external power connected, not just usb power.
> 
> And you need to look at results of M122, is it all or just one?
> 
> You have 4 tmcs configured but only one is pictured plugged in, this would also cause this error.
> 
> This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:
> 
> * MarlinFW.org [Marlin Documentation](http://marlinfw.org)
> * RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
> * Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
> * Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
> * [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
> * 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
> * Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y
> 
> After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

external power for motors is connected and I test that with 4 stepper drive which I enabled in configuration but the error is still exist!

**Comment by ellensp** [comment]
still need to see M122 results

**Comment by Enzo-Enz** [comment]
> still need to see M122 results

M122 results:

[M122.txt](https://github.com/MarlinFirmware/Marlin/files/8590340/M122.txt)

**Comment by ellensp** [comment]
Check your stepper modules are actually configured for SPI mode.

![tmc2130 spi](https://user-images.githubusercontent.com/530024/165935226-9e93c848-84ad-4537-8b76-56d016c939da.png)

The SPI pads must be empty and CFG4 and CFG5 pads should be connected as pictured in Purple/Pink.

**Comment by Enzo-Enz** [comment]
> Check your stepper modules are actually configured for SPI mode.
> 
> ![tmc2130 spi](https://user-images.githubusercontent.com/530024/165935226-9e93c848-84ad-4537-8b76-56d016c939da.png)
> 
> The SPI pads must be empty and CFG4 and CFG5 pads should be connected as pictured in Purple/Pink.


I think they have been set on STEP/DIR mode!

![tmc2130](https://user-images.githubusercontent.com/75531691/165938432-ba4da403-e32c-460c-b111-3c2a59de6d09.jpeg)

**Comment by ellensp** [comment]
They have.
Not a marlin issue.
