### ISSUE TITLE
[BUG] (Rebooting when reinserting a filament after runout sensor activated)

### ISSUE THREAD

**Issue by brunohenriquy** [MarlinFirmware/Marlin#24101]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I am trying to install a filament runout sensor.
My printer is an Ender 3 V2 with board 4.2.2

This is the sensor I am using:
<img width="211" alt="image1" src="https://user-images.githubusercontent.com/8320519/165842894-d7b57632-81e5-4cd0-a603-d909bb964dd6.png">
Testing continuity on pins:
When the filament is out:           pin 1 and pin 3 are open
When the filament is inserted:   pin 1 and pin 3 are closed

Here are the changes I made on firmware:

- In [“Configuration.h”](https://github.com/brunohenriquy/Marlin/blob/filament-runout-sensor/Configuration%20Files/BH's%20Config/Configuration.h)
    - #define EXTRUDE_MAXLENGTH 301
    - #define FILAMENT_RUNOUT_SENSOR
    - #define FIL_RUNOUT_ENABLED_DEFAULT true
    - #define NUM_RUNOUT_SENSORS 1
    - #define FIL_RUNOUT_STATE LOW
    - #define NOZZLE_PARK_FEATURE
    
- In [“Configuration_adv.h”](https://github.com/brunohenriquy/Marlin/blob/filament-runout-sensor/Configuration%20Files/BH's%20Config/Configuration_adv.h)
    - #define ADVANCED_PAUSE_FEATURE
    - #define FILAMENT_CHANGE_UNLOAD_LENGTH 300
    - #define FILAMENT_CHANGE_FAST_LOAD_LENGTH 300
    - #define PARK_HEAD_ON_PAUSE

P.S.: I also tried enabling EMERGENCY_PARSER, HOST_ACTION_COMMANDS, HOST_PROMPT_SUPPORT and the same behavior occurred.

- I Turn on the printer with "sensor connected" "without filament": **Black screen**
- I Turn on the printer with "sensor connected" "with filament": It Turns on normally (When I send M119 I get filament: TRIGGERED)
- I Remove the filament: **It Freezes the screen**
- I Insert the filament: **It Reboots automatically and releases the screen**
- I Turn on with "sensor disconnected": It Turns on normally (When I send M119 I get filament: TRIGGERED)

- I Turn on with  “sensor connected” “with filament”,  “start printing”, “cut filament”: **It freezes, when I reinsert the filament, it reboots.**
What am I missing?

### Expected behavior

To insert the new filament, and it resumes or show an option to resume!

### Actual behavior

It reboots after inserting a new filament.

### Steps to Reproduce

1 - Turn on the machine with the filament loaded on the filament runout sensor
2 - Cut the filament
3 - The sensor is trigered
4 - It stops
5 - Reload filament
6 - **It reboots**

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Creality Ender 3 V2

### Electronics

Board Version: 4.2.2  Stepper Driver: TMC2208  ARM: STM32F103RCT6

### Add-ons

Filament Runout Sensor

### Your Slicer

Cura

**Comment by GMagician** [comment]
Maybe a short circuit? Sure connection is ok?

**Comment by brunohenriquy** [comment]
> Maybe a short circuit? Sure connection is ok?

Yes, connections are fine!

**Comment by brunohenriquy** [comment]
I've found the issue.
I had to switch the wires from pin 1 and 3 at one of the cable ends.

Maybe this switch could have been done via firmware, if someone could tell, I appreciate.

<img width="1077" alt="Screen Shot 2022-04-29 at 1 20 17 AM" src="https://user-images.githubusercontent.com/8320519/165884999-61f8b6d0-cfc7-4701-85a5-d64421167fda.png">

**Comment by thisiskeithb** [comment]
This was a hardware issue, not a Marlin bug.

**Comment by brunohenriquy** [comment]
Extra info might help someone out there: https://www.reddit.com/r/ender3v2/comments/ueplws/filament_runout_sensor_ender_3_v2_might_work_for/
