### ISSUE TITLE
[BUG] STOP button does not stop/reset the print status

### ISSUE THREAD

**Issue by joao-a-cardoso** [MarlinFirmware/Marlin#24115]
### Did you test the latest `bugfix-2.0.x` code?

YES! The problem is still present

### Bug Description

Pressing the Stop button stops the printing, but it's impossible to perform some operations, for example print the same model since the progress/status does not reset.
Houver, I am still able to start a new print job from OctoPrint.

### Bug Timeline

Happens in 2.0.9.3 (did not test any other version with this setup)

### Expected behavior

It should reset to state "ready", allowing all operations.

### Actual behavior

It does not reset the print status. It behaves presents the same menu options as it if where still printing.
The only workaround to reset the status is to reset the printer..

### Steps to Reproduce

1. Start printing some file
2. After it starts, wait a while and select "Stop"
3. Check the menus, it presents the same options as it is still printing.

### Version of Marlin Firmware

Using a Maker Base MKS Robin Nano 3.1, with a TST35 display. It is configures as TFT_Collor_UI

### Printer model

Two Trees BluerPlus, with upgraded electronics

### Electronics

Using a Maker Base MKS Robin Nano 1.3, with a TST35 display

### Add-ons

None

### Bed Leveling

ABL

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint 1.8rc5

**Comment by ellensp** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by joao-a-cardoso** [comment]
Hello, I already did that (see above, please). The wrong behaviour remains
