### ISSUE TITLE
[BUG] Need NEO_RGB option for Fysetc Mini 12864 v2.1 in bugfix2.0.x

### ISSUE THREAD

**Issue by dckostin** [MarlinFirmware/Marlin#24116]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Red and Green colors are reversed on Fysetc Mini 12864 v2.1 display.  Marlin\src\inc\SanityCheck.h restricts Neopixel options to NEO_GRB only.  Need to add NEO_RGB option for some Fysetc Mini 12864 v2.1 displays.

### Bug Timeline

bugfix-v.0.x

### Expected behavior

Red = red color and Green = green color, Indigo = indigo color, Violet = violet  color, etc. on Lights menu, 

### Actual behavior

Red = green color, Green = red color, Indigo = violet color, Violet = indigo color, etc. on Lights menu, 

### Steps to Reproduce

Turn on printer

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Voron 2.2

### Electronics

Fysetc Spider v2.2

### Add-ons

Fysetc Mini 12864 v2.1

### Additional information & file uploads

Modify Marlin\src\inc\SanityCheck.h in bugfix-2.0.x to:
2453  #if defined(NEOPIXEL_TYPE) && NEOPIXEL_TYPE != NEO_GRB && NEOPIXEL_TYPE != NEO_RGB
2454    #error "Your FYSETC Mini Panel requires NEOPIXEL_TYPE to be NEO_GRB or NEO_RGB."

Modify Configuration.h to:
3054  #define NEOPIXEL_TYPE          NEO_RGB  // NEO_GRBW / NEO_GRB / NEO_RGB - four/three channel driver type (defined in Adafruit_NeoPixel.h)

**Comment by thisiskeithb** [comment]
You're not using the latest bugfix. This was fixed in https://github.com/MarlinFirmware/Marlin/pull/24111
