### ISSUE TITLE
[BUG] MEDIA INIT FAIL 

### ISSUE THREAD

**Issue by Noobje130** [MarlinFirmware/Marlin#24127]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

when flashing marlin or marling bugfix to my biqu b1 se  plus skr 2B evreything works but cant intalize sd card

### Bug Timeline

when using marlin

### Expected behavior

to be able to reead the sdcard

### Actual behavior

cant read the sdcard

### Steps to Reproduce

1.  download latest marlin bugfix
2. download configuration example use biqu b1 se plus
3. set default env to BIGTREE_SKR_2
4. error

### Version of Marlin Firmware

bugfix 2.0.x

### Printer model

biqu b1 se plus

### Electronics

stock

### Additional information & file uploads

![1651675997342](https://user-images.githubusercontent.com/28931250/166709017-d313177a-062b-4041-897b-f32e23f03bac.jpg)
[config.zip](https://github.com/MarlinFirmware/Marlin/files/8621436/config.zip)

**Comment by ellensp** [comment]
You enabled usb  ie   #define USB_FLASH_DRIVE_SUPPORT, did you plug in a usb stick?

**Comment by thisiskeithb** [comment]
Note: Flash drive support is enabled by default in the B1 SE Plus config, but jumpers to enable support may not have been installed correctly from the factory. [Follow Biqu's instructions, starting with Step 2](https://github.com/bigtreetech/BIQU-B1-SE-PLUS/blob/master/B1-SE%20fimware/B1-SE-U%20Disk%20Usage%20Tutorial-English.pdf) if flash drive support is not working correctly.

You can also try enabling `MULTI_VOLUME` support since that was disabled in the default config (recently added in https://github.com/MarlinFirmware/Configurations/pull/719)

Once you insert a flash drive, you should be able to select which media you want to print from. If you don't want flash drive support, disable `USB_FLASH_DRIVE_SUPPORT`.

**Comment by Noobje130** [comment]
@thisiskeithb my sd card reader is working now but i cant use my usb port 

what i did to get my sd card reader working was disable USB_FLASH_DRIVE_SUPPORT
then i got these errors (look at pictures) to fix i did what it sayed change to DiskIODriver_SDIO

but i wonder is there way my usb port could work too

**Comment by Noobje130** [comment]
and btw me tried enabling USB_FLASH_DRIVE_SUPPORT again ofc

**Comment by thisiskeithb** [comment]
With `USB_FLASH_DRIVE_SUPPORT` disabled, you lose access to that port.

Having said that, I've confirmed here that with `MULTI_VOLUME` enabled, you can select which one you want to print from.

**Comment by Noobje130** [comment]
@thisiskeithb even with USB_FLASH_DRIVE_SUPPORT enabled and MULTI_VOLUME too me can print from sd card no problem but it does not detect my usb drive

**Comment by Noobje130** [comment]
like it gives menu to select sd or usb but it shows the same for both

**Comment by thisiskeithb** [comment]
Try power cycling the printer with both plugged in.

**Comment by APToni** [comment]
I ran into a similar problem on the mks robin nano v3 board, with a 12864B display without a resistor. With the normal marlin basic setting, the sd card works fine, but when adding a usb drive (in conf marlin), a similar message appears, but I can select a file to print with the usb flash drive installed from both the sd card and the usb drive. BUT I can not open the SD card WITHOUT usb drive. Here is a feature in the firmware.

**Comment by trengtor** [comment]
I was upgrade Marlin fron 2.0.8.2 to 2.1.2 on contol board BTT E3 RRF V1.1 — now have problem with media init fail.

**Comment by trengtor** [comment]
https://github.com/MarlinFirmware/Marlin/issues/25151

**Comment by reynum2** [comment]
I have the same problem with ramps 1.4 on a printer Anet A8 with Marlin 2.0.9.6

**I have enable** 
#define SDSUPPORT
#define SDCARD_CONNECTION LCD

**And tried with** 
#define MULTI_VOLUME
#define USB_FLASH_DRIVE_SUPPORT

**I wanted to test with** 
#define SDIO_SUPPORT 
But the compilation fail with this parameter

I use the SD card reader in the screen like this one :
[https://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller](https://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller)
and activate : 
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

My card is 1Go an formated in FAT32 but I still have the "Media init fail" message when I insert the card

**Comment by EvilGremlin** [comment]
because SDIO doesn't exist on AVR
USB_FLASH_DRIVE_SUPPORT - do you even have this hardware?

> card is 1G 

try at least two other cards, some don't have SPI mode or it's wrongly implemented

**Comment by reynum2** [comment]
I tried with 4 cards (different size and constructors) and the result is the same.
I will try to update to last Marlin version and if it does not work : create a new bug

**Comment by reynum2** [comment]
try with Marlin 2.1.2.1 and still the : 
![20230604_204634](https://github.com/MarlinFirmware/Marlin/assets/11191723/0d774f08-f037-463c-afe9-fbe249dd17a0)

**Comment by reynum2** [comment]
try with Marlin 2.1.2.1 and still the : 
![20230604_204634](https://github.com/MarlinFirmware/Marlin/assets/11191723/0d774f08-f037-463c-afe9-fbe249dd17a0)

**Comment by ellensp** [comment]
USB_FLASH_DRIVE_SUPPORT requires an additional MAX3421E board, not a REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

```
   /**
   * Support for USB thumb drives using an Arduino USB Host Shield or
   * equivalent MAX3421E breakout board. The USB thumb drive will appear
   * to Marlin as an SD card.
   *
   * The MAX3421E can be assigned the same pins as the SD card reader, with
   * the following pin mapping:
   *
   *    SCLK, MOSI, MISO --> SCLK, MOSI, MISO
   *    INT              --> SD_DETECT_PIN [1]
   *    SS               --> SDSS
   *
   * [1] On AVR an interrupt-capable pin is best for UHS3 compatibility.
   */
  //#define USB_FLASH_DRIVE_SUPPORT
```

**Comment by reynum2** [comment]
Yes I tried with this parameter (USB_FLASH_DRIVE_SUPPORT) but remove it when I saw it does not work.

Now the only parameter related to the SD is 
`
#define SDSUPPORT
`
But maybe there is another parameter to enable ?

**Comment by redskin61** [comment]
I resolve media init fail after commenting the line "//#define SD_DETECT_STATE HIGH" in Configuration.adv.h--- SKR PRO v1.1

**Comment by aurion55** [comment]
> Yes I tried with this parameter (USB_FLASH_DRIVE_SUPPORT) but remove it when I saw it does not work.
> 
> Now the only parameter related to the SD is `#define SDSUPPORT` But maybe there is another parameter to enable ?

Did you look here:
 SD Card SPI Speed
   * May be required to resolve "volume init" errors.
   *
   * Enable and set to SPI_HALF_SPEED, SPI_QUARTER_SPEED, or SPI_EIGHTH_SPEED
   *  otherwise full speed will be applied.
   *
   * :['SPI_HALF_SPEED', 'SPI_QUARTER_SPEED', 'SPI_EIGHTH_SPEED']
   */
  //#define SD_SPI_SPEED SPI_HALF_SPEED
  
  
  It state above if you have "Volume init error"you might need to low to half speed?
  
  I'm on Marlin 2.1.2 and just started to get these "media init error" using the same setup as you, I think to due to dirty pins on the Sd card? As I never has in the past.

**Comment by sigmondkukla** [comment]
I'll try the new bugfix firmware as I'm having this issue as well.
+1 on dirty pins either on the card or reader, because sometimes I just have to slide the card in and out a few times before it is detected. Still trying to figure out if that's really the issue though.

**Comment by aurion55** [comment]
Clean your Sd Card with some alcohol wipes, as I'm going to do the same.

**Comment by sigmondkukla** [comment]
Smart, will do. It's one of those intermittent issues that bugs me right then and goes away!
