### ISSUE TITLE
[FR] Adjust "Info Text" font size or make it scroll

### ISSUE THREAD

**Issue by brunohenriquy** [MarlinFirmware/Marlin#24129]
### Describe the feature you want

Is there a way to change the font size of the info text or make it scroll for long texts, like for the filenames -> SCROLL_LONG_FILENAMES?

![IMG_4549](https://user-images.githubusercontent.com/8320519/166727306-5e43cb2a-5ee9-48e1-b35d-409e9a8165e0.jpg)

**Comment by thisiskeithb** [comment]
Enable `STATUS_MESSAGE_SCROLLING`.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by brunohenriquy** [comment]
Thanks @thisiskeithb and my bad! 😅
