### ISSUE TITLE
[BUG]  Ender 3v2 Reboots with media insert and scroll menu at the same time

### ISSUE THREAD

**Issue by dmitrygribenchuk** [MarlinFirmware/Marlin#24131]
### Bug Description

Hello. Have a firmware crash when inserting media and scroll at the same time. For demonstration reasons make it very fast - in regular life have a normal speed and can reproduce.

### Steps to Reproduce

1) Insert or remove media
2) Scroll a button

### Version of Marlin Firmware

2.0.9.3

### Printer model

Ender 3v2 (4.2.2)

### Additional information & file uploads

https://user-images.githubusercontent.com/15670247/166811221-6bd7b379-8de2-410a-af17-a5fccd50429c.mp4

**Comment by ellensp** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by dmitrygribenchuk** [comment]
I try to reproduce it on [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) it seems that need a little bit more time for that but still able.

**Comment by ellensp** [comment]
Since you seem to have the knack on triggering this, could you add #define WATCHDOG_DURATION_8S to the end of your your Configuration.h recompile and upload and see if the issue still occurs?

**Comment by dmitrygribenchuk** [comment]
I'm adding #define WATCHDOG_DURATION_8S to the end of my Configuration.h recompile and upload and the issue still occurs

**Comment by ellensp** [comment]
The watchdog is a timer that must be reset before the the time limit or it reboots. This is how you detect and get out of software crashes.
That define doubles that time from 4 to 8 seconds.  Since it made no difference. It probably not tripping the watchdog timer.

**Comment by dmitrygribenchuk** [comment]
Also I  set WATCHDOG_DURATION_ 1,2,4,8,16 - still crashed

**Comment by ellensp** [comment]
It doesn't work that way, Is used in code like this

`#define WDT_TIMEOUT_US TERN(WATCHDOG_DURATION_8S, 8000000, 8000000) // 4 or 8 second timeout
`

So if WATCHDOG_DURATION_8S is set use 8000000, else use 4000000

Other WATCHDOG_DURATION_ values are not checked for

**Comment by mrbass21** [comment]
I don't know if it's related, but I've triggered a similar situation. I'm brand new to 3D printing and have an Ender 3 Pro (4.2.2 board, all stock for now). I started messing with upgrading Marlin late last night. I went from 2.0.8.2 to 2.1 and while printing, I constantly get beeps from the piezo and the display goes into a menu as though I pushed in on my button.

While I was printing I went to the Power Outage setting and clicked in on it, the software rebooted (crashed?) and the print was immediately stopped.

I'm still looking through tickets to see if anyone has the problem I do with the logic board constantly thinking I've interacted with the menu during a print. If I let it sit, sometimes it goes back through phantom selection, and sometimes it times out and goes away. Seemed maybe tangentially related. I'll keep looking at issues in the mean time to see if anyone else is having my problem.

**Comment by dmitrygribenchuk** [comment]
Still can reproduce on 2.1.1

**Comment by thisiskeithb** [comment]
Since https://github.com/MarlinFirmware/Marlin/pull/24652 was patched a few days ago, please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by dmitrygribenchuk** [comment]
Also reproduced on bugfix-2.1.x

**Comment by dmitrygribenchuk** [comment]
Still reproduced on bugfix-2.1.x
