### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by Neonangel65** [MarlinFirmware/Marlin#24143]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

while trying to get marlin configured for the skr v2 board for a sunlu s8 printer and building it through auto marlin it keeps erroring out about the TFT pins saying did you mean like sd_sck_pin? I haven't even messed with anything there or anything related to the pins I would like some help I have tried different revisions of marlin and even a pre-built one someone made for a Prusa but as soon as I switched things around to work for my printer it wouldn't allow me to build. the bug fix code wont even register as a valid version of marlin under auto marlin

### Bug Timeline

today 05/07/22

### Expected behavior

I expected to be able to change a few settings and build it fine

### Actual behavior

errored out

### Steps to Reproduce

[Marlin-2.0.9.2 (2).zip](https://github.com/MarlinFirmware/Marlin/files/8644678/Marlin-2.0.9.2.2.zip)

### Version of Marlin Firmware

tried 2.0.9.2,2.0.9.3 and 2.0.9.1

### Printer model

sunlu s8

### Electronics

bigtreetech tft35 e3 v3.0.1 skr v2 rv_b

### Your Slicer

Cura

**Comment by ellensp** [comment]
You do NOT enable #define TFT_GENERIC for that type of TFT

That type of TFT  is not directly controlled by the controller. It uses a serial port for the touch side (serial port 1) and REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER or CR10_STOCKDISPLAY for marlin mode.


This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
