### ISSUE TITLE
Danish translation file "language_da.h"

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#2414]
I have made a Danish translation file, much like the other "language_XX.h", and I would like to contribute with it.
__
Simon M. N.

**Comment by Wackerbarth** [comment]
Create a fork of our repository on Github, Start a new branch from the current "Development" with a name such as "Danish". Add your file (and the other changes to enable it) and push it to your github repository.  Then generate a Pull Request here.

**Comment by ghost** [comment]
Okay I think I have done so. Can you see the file from your side ?

**Comment by thinkyhead** [comment]
Github docs: https://help.github.com/articles/creating-a-pull-request/
Got 11 minutes? https://www.youtube.com/watch?v=oFYyTZwMyAg

You will be making your PR against `MarlinFirmware/Development`. Watch out, because the default in the interface is `MarlinFirmware/Release`.
