### ISSUE TITLE
[FR] SPI_ENDSTOPS for Multi-Stepper / Multi-Endstop

### ISSUE THREAD

**Issue by rondlh** [MarlinFirmware/Marlin#24155]
### Is your feature request related to a problem? Please describe.

I have a printer with 2 Y-steppers driven by 2 TMC5160 drivers, homing works fine using the diag pins, but homing completely fails when using SPI_ENDSTOPS. (SPI communication is established and reported OK).
I have the same issue for and IDEX printer, homing the X carriages completely fails when enabling SPI_ENDSTOPS.

I had a quick look at the source code, which makes me think this is not a bug, but the capability is just not implemented. I gave it a try myself, but failed.
By using SPI_ENDSTOPS I can free up some hardware endstops connectors, which will allow me to implement new features, like a nozzle probe, filament runout detection and LED support.

### Are you looking for hardware support?

Nope

### Describe the feature you want

SPI_ENDSTOPS support for Multi-Stepper / Multi-Endstop systems, specifically:
Dual Y-driver, dual Y-endstop
IDEX X-carriage.

### Additional context

Freeing up the endstops allows me to implement new/more features.

**Comment by rondlh** [comment]
Nobody? I've been trying to get this to work myself, but have been unable to do so....

**Comment by rondlh** [comment]
Not sure if is a good solution, but it works for me.

In endstops.cpp expand the #if Y_SPI_SENSORLESS like shown:
```
    #if Y_SPI_SENSORLESS
      if (tmc_spi_homing.y && (stepperY.test_stall_status()
        #if ANY(CORE_IS_XY, MARKFORGED_XY, MARKFORGED_YX) && X_SPI_SENSORLESS
          || stepperX.test_stall_status()
        #elif CORE_IS_YZ && Z_SPI_SENSORLESS
          || stepperZ.test_stall_status()
        #endif
      )) {
        SBI(live_state, Y_ENDSTOP);
		hit = true;
      }  
      #ifdef Y_DUAL_ENDSTOPS
	  if (tmc_spi_homing.y && (stepperY2.test_stall_status() // Added section for dual endstop Y
        #if ANY(CORE_IS_XY, MARKFORGED_XY, MARKFORGED_YX) && X_SPI_SENSORLESS
          || stepperX.test_stall_status()
        #elif CORE_IS_YZ && Z_SPI_SENSORLESS
          || stepperZ.test_stall_status()
        #endif
      )) {
        SBI(live_state, Y2_ENDSTOP);
		hit = true;
      } 
      #endif	  
    #endif
```

A few lines below add this in void Endstops::clear_endstop_state()
```
	#ifdef Y_DUAL_ENDSTOPS
      TERN_(Y_SPI_SENSORLESS, CBI(live_state, Y2_ENDSTOP)); // Added to clear Y2 endstop status
    #endif
```

And in endstops.h Y2_ENDSTOP needs to be defined:
```
  // Endstops can be either MIN or MAX but not both
  #if HAS_X_MIN || HAS_X_MAX
    , X_ENDSTOP = TERN(X_HOME_TO_MAX, X_MAX, X_MIN)
  #endif
  #if HAS_Y_MIN || HAS_Y_MAX
    , Y_ENDSTOP = TERN(Y_HOME_TO_MAX, Y_MAX, Y_MIN)
  #endif
  #if ENABLED(Y_DUAL_ENDSTOPS)
    #if HAS_Y_MIN || HAS_Y_MAX
      , Y2_ENDSTOP = TERN(Y_HOME_TO_MAX, Y2_MAX, Y2_MIN)
    #endif 
  #endif
  #if HAS_Z_MIN || HAS_Z_MAX || HOMING_Z_WITH_PROBE
    , Z_ENDSTOP = TERN(Z_HOME_TO_MAX, Z_MAX, TERN(HOMING_Z_WITH_PROBE, Z_MIN_PROBE, Z_MIN))
  #endif
  #if HAS_I_MIN || HAS_I_MAX
    , I_ENDSTOP = TERN(I_HOME_TO_MAX, I_MAX, I_MIN)
  #endif
  #if HAS_J_MIN || HAS_J_MAX
    , J_ENDSTOP = TERN(J_HOME_TO_MAX, J_MAX, J_MIN)
  #endif
  #if HAS_K_MIN || HAS_K_MAX
    , K_ENDSTOP = TERN(K_HOME_TO_MAX, K_MAX, K_MIN)
  #endif
```

**Comment by thisiskeithb** [comment]
Added in https://github.com/MarlinFirmware/Marlin/pull/25371
