### ISSUE TITLE
[BUG] TRIGORILLA 14 i3 mega anycube error compile

### ISSUE THREAD

**Issue by microsoul** [MarlinFirmware/Marlin#24161]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

TRIGORILLA 14  i3 mega anycube.
In file included from buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../pins/pins.h:880:0,
                 from buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/MarlinConfig.h:35,
                 from buildroot/share/PlatformIO/scripts/common-dependencies.h:29:
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../pins/pins_postprocess.h:791:8: error: #error "No E stepper plug left for Y2!"
       #error "No E stepper plug left for Y2!"
        ^~~~~
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../pins/pins_postprocess.h:877:8: error: #error "No E stepper plug left for Z2!"
       #error "No E stepper plug left for Z2!"

### Bug Timeline

new

### Version of Marlin Firmware

bugfix-2.0.x STRING_DISTRIBUTION_DATE "2022-05-12"

### Printer model

Anycube i3 mega

### Additional information & file uploads

error in compilation

**Comment by thisiskeithb** [comment]
The Trigorilla 14 board only has five driver slots, so you can't enable options for non-existent driver slots. You can do Y2 or Z2, but not both.

**Comment by microsoul** [comment]
in Configuration.h in config\examples\AnyCubic\i3Mega
define X2_DRIVER_TYPE ALL_DRIVERS_TYPE
define Y2_DRIVER_TYPE ALL_DRIVERS_TYPE
define Z2_DRIVER_TYPE ALL_DRIVERS_TYPE
is not decomented for default

**Comment by thisiskeithb** [comment]
This issue should be transferred to the Configurations repo, but it looks like those driver types were enabled by mistake since `X_DUAL_STEPPER_DRIVERS` and `Y_DUAL_STEPPER_DRIVERS` were disabled by default, but recent changes to Marlin now uses enabled `*_DRIVER_TYPE`s to set those features.

Comment out/disable `X2_DRIVER_TYPE` and `Y2_DRIVER_TYPE`.

I've put in https://github.com/MarlinFirmware/Configurations/pull/734 to fix the config.

**Comment by microsoul** [comment]
i have this:
#define Z2_DRIVER_TYPE ALL_DRIVERS_TYPE

but motor z2 does not move

i dont find setting:

#define NUM_Z_STEPPER_DRIVERS

**Comment by microsoul** [comment]
I did other tests:
with the command:
G0 Z22
both motors move perfectly

with command:
G28 Z
it moves only on a motor

**Comment by microsoul** [comment]
Solved
Configurations/config/examples/AnyCubic/i3 Mega/Configuration.h

Line 974
#define Z_MIN_ENDSTOP_INVERTING true  // Set to true to invert the logic of the endstop.

**Comment by thisiskeithb** [comment]
@microsoul: Are you running a completely stock AnyCubic i3 Mega?

**Comment by microsoul** [comment]
Yes

**Comment by thisiskeithb** [comment]
> Yes

I’ve included this fix in https://github.com/MarlinFirmware/Configurations/pull/737
