### ISSUE TITLE
[BUG] Mightyboard - Incorrect fan operation when DEBUG LEDs are in use

### ISSUE THREAD

**Issue by grauerfuchs** [MarlinFirmware/Marlin#24166]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When using the LED_PIN define for visual indication, the parts cooling fan changes state.

### Bug Timeline

commit 195383bc33e708e533ee7d7199184351d8f6e55b

### Expected behavior

Using the debugging LEDs should not result in changes to the parts cooling fan.

### Steps to Reproduce

Verify LED_PIN definition against the published schematic for the board

### Version of Marlin Firmware

2.0.9.3 release, bugfix-2.0.x

### Printer model

FlashForge Creator Pro

### Additional information & file uploads

Configuration files not necessary for issue identification; The issue is due to an incorrect pins definition in the pins_MIGHTYBOARD_REVE.h file.

**Comment by ellensp** [comment]
merged. closing
