### ISSUE TITLE
[BUG] Original Creality filament runaway sensor is not working with latest Marlin release

### ISSUE THREAD

**Issue by sensboston** [MarlinFirmware/Marlin#24171]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Hello guys, could you **please help me**? 

I'm trying to get a filament runaway detection sensor (from Creality, [this one](https://www.amazon.com/Creativity-Printer-Filament-Detection-Detecting/dp/B087325BPG/?th=1) ) working with Marlin (version 2.0.9.3). I do have Ender 3 Pro (latest version, I believe so, purchased last fall).

Googled and searched internet but it full of bullshits, pretty outdated video manuals (I hate 'em!) and non-working "how to" instructions 🙁

Sensor is working (I'm 99% sure), it's designed and produced by Creality especially for their Ender 3 xxx series (and other ones). Built-in LED reacting on filament presence. 

 So, the issue only in the Marlin's configuration. Guy on Amazon reported, this sensor is working pretty fine with OctoPrint (and I'm very sure I'll reuse this option if I don't get any luck with Marlin firmware). He mentioned:
"Filament Sensor Reloaded
1 (3V3) Red Hot
3 (GIO2) White Signal(3 Board Mode)(2 BCM)
9 (GND) Black is Ground"

I connected this sensor to Ender 3 Pro MB (how it supposed to be). Could you help me with the pin numbers and some specific settings? 
This should be a very simple: "on" or "off", simple detection. I haven't expected that kind of problem 🙁

### Bug Timeline

I don't know

### Expected behavior

I expected to get this sensor working with original config - here is mine:

```
#define FILAMENT_RUNOUT_SENSOR
#if ENABLED(FILAMENT_RUNOUT_SENSOR)
  #define FIL_RUNOUT_ENABLED_DEFAULT true // Enable the sensor on startup. Override with M412 followed by M500.
  #define NUM_RUNOUT_SENSORS   1          // Number of sensors, up to one per extruder. Define a FIL_RUNOUT#_PIN for each.
  
  #define FIL_RUNOUT_STATE     LOW 	  // Pin state indicating that filament is NOT present.
  #define FIL_RUNOUT_PULLUP               // Use internal pullup for filament runout pins.

```

### Actual behavior

When I send command M412, I got only:
```
Send: M412
Recv: echo:Filament runout ON ; Distance 25.00mm ; Host handling ON
Recv: ok
```

Also, I tried to print - no luck, it's not working.

### Version of Marlin Firmware

Release 2.0.9.3

### Printer model

Ender 3 Pro (last fall release, new silent MB)

### Electronics

Stock

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by thisiskeithb** [comment]
That is a generic runout sensor sold by Creativity, not Creality, but this isn’t the place for tech support.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
