### ISSUE TITLE
[BUG] i2c relay typo error

### ISSUE THREAD

**Issue by MFaisalZaki** [MarlinFirmware/Marlin#24179]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Unwanted relay i2c since the `M261` function ignores the `style` [byte](https://github.com/MarlinFirmware/Marlin/blob/94ed67e36ef84cb4ecd8f3f1470041d4d72f7088/Marlin/src/gcode/feature/i2c/M260_M261.cpp#L71). I do belive that it is a typo error.

### Version of Marlin Firmware

2.0.9.3

**Comment by sjasonsmith** [comment]
There is really not enough information here to understand the problem. Feel free to re-open this if you fill in the requested information such as "Expected Behavior" and "Actual Behavior."

If you already know how to fix the problem then please submit a pull request to make the needed change.
