### ISSUE TITLE
[BUG] MKS Tinybee / ESP32 MKS12864 display does not work because of u8g_esp32_spi.cpp

### ISSUE THREAD

**Issue by jesterhead82** [MarlinFirmware/Marlin#24184]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

[BUG] MKS Tinybee / ESP32 MKS12864 display does not work because of u8g_esp32_spi.cpp

MKS fork for the Tinybee version of it:

#if ENABLED(MKS_MINI_12864_V3)
  #define MDOGLCD_MOSI                     23
  #define MDOGLCD_SCK                      18
  #define MLCD_RESET_PIN                   0
  #define MLCD_PINS_DC                     4
  #define MDOGLCD_CS                       21
  #define MDOGLCD_A0                       4
#endif

#if ENABLED(MKS_MINI_12864) <---12864 triggers that one
  #define MDOGLCD_MOSI                     23
  #define MDOGLCD_SCK                      18
  #define MLCD_RESET_PIN                   -1
  #define MLCD_PINS_DC                     15
  #define MDOGLCD_CS                       16
  #define MDOGLCD_A0                       15
#endif

Recent Marlin Versions overwrite the Pins simply

### Bug Timeline

At least in recent versions

### Version of Marlin Firmware

2.0.xx

**Comment by ellensp** [comment]
You did NOT try bugfix
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/ESP32/u8g_esp32_spi.cpp#L28

**Comment by jesterhead82** [comment]
Well, I did.

So currently 12864B triggers MKS_MINI_12864

Conditions_LCD.h:
#if EITHER(MKS_LCD12864A, MKS_LCD12864B)
  #define MKS_MINI_12864
#endif


MKS_MINI12864 then uses the following PIN definitions in Bugfix , which do not work for my 12864B

#define MDOGLCD_MOSI    23
#define MDOGLCD_SCK     18
#define MLCD_RESET_PIN   0
#define MLCD_PINS_DC     4
#define MDOGLCD_CS      21
#define MDOGLCD_A0       4

If I change to the PIN definitions of current Bugfix to of MKS's Fork of 2.0.9.2, Display works.

so summary: Bugfix with MKS12864B triggers non-working:

#define MDOGLCD_MOSI    23
#define MDOGLCD_SCK     18
#define MLCD_RESET_PIN   0
#define MLCD_PINS_DC     4
#define MDOGLCD_CS      21
#define MDOGLCD_A0       4

MKS Fork of 2.0.9.2 triggers working:

#define MDOGLCD_MOSI 23
#define MDOGLCD_SCK 18
#define MLCD_RESET_PIN -1
#define MLCD_PINS_DC 15
#define MDOGLCD_CS 16
#define MDOGLCD_A0 15

**Comment by ellensp** [comment]
right this was updated 2 months ago...   

https://github.com/makerbase-mks/MKS-TinyBee/commit/aca458e5efd4c1332ba8f1d27c94de3487ea0586

**Comment by ellensp** [comment]
Please test this PR

**Comment by jesterhead82** [comment]
Hi,

can confirm that at least that issue is now gone with this TinyBee(ast) when I apply your PR.

**Comment by ellensp** [comment]
Since PR has been created to fix this, closing this issue.
