### ISSUE TITLE
Bug with ABL and combining stepper drivers

### ISSUE THREAD

**Issue by southdave** [MarlinFirmware/Marlin#24197]
Hello there I think I have found a bug in the latest marling firmware and was wondering if I could get some help in here
Im using the BTT octopus 1.1 and BTT TMC2209 stepper drivers .
the issue is related to ABL using 2 Z access motors, I can get it working but the second stepper driver moves twice the speed as the first.
the issue is related to the code for the stepper driver as if I replace the TMC 2209 stepper driver with a TMC2130 on both Z axis but leave all the other motors on the 2209's then the motor speed problem is resolved
How Ever !!!!!!
The combination of both 2209 and the 2130 on the octopus 1.1 reveals yet another bug. I can no longer use sensor less homing on the X and Y. I have lost alot of money on hardware trying to get this working and was wondering if there is possibly a fix

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
