### ISSUE TITLE
Unable to compile any version of Marlin

### ISSUE THREAD

**Issue by jigneshsinha** [MarlinFirmware/Marlin#24206]
Hi, I was posting this issue regarding compilation of Marlin. It seems to be an issue regardless of which version i attempt to compile in vscode and platformio. I have tried various versions starting from the current bugfix all the way back to the 2.0.6.1 and get the same error messages. Also I have attempted this on 5 different pc's. I've attached an image of the error below. would appreciate any feedback that can be provided. I assume its got to be something missing in the install. 

<img width="708" alt="Screen Shot 2022-05-17 at 11 22 55 PM" src="https://user-images.githubusercontent.com/105766830/168956991-8187785a-033f-49fd-a5ca-de94c04c1c1a.png">
. 3 were windows based while 2 were macs. All gave the same error message.

**Comment by thisiskeithb** [comment]
This isn't a Marlin bug, but I'll leave this open for now for visibility.

You'll need to update your PlatformIO Core by running `pio upgrade` from the command line.

...or...

In VSCode, click the PIO alien/ant icon & then Upgrade PlatformIO Core:

<img src="https://user-images.githubusercontent.com/13375512/168956415-927c0e73-4fd5-4989-b95f-011b37b8da74.png" width="50%">

**Comment by jigneshsinha** [comment]
wow, that was the most efficient response. Thank you for the help, that fixed the issue i have spent days trying to solve. Much appreciated!

**Comment by thisiskeithb** [comment]
I'm going to keep this open for visibility.

**Comment by LudovicLemarinel** [comment]
Sooo easy to fix after trying to toggle verbose for an hour, not seeing any error and finding this issue ;)

**Comment by akinilicali** [comment]
![image](https://user-images.githubusercontent.com/83561072/169619979-458d9b50-7a2d-49ad-81b5-3109142e24fd.png)
I have exactly the same problem which hasn't gone away. I tried many pio and python versions. I briefly got it to work using an older Python version but now, it doesn't work with that version either.

**Comment by Bob-the-Kuhn** [comment]
The PlatformIO core must be at 6.0.1 or higher for VScode to compile Marlin properly.  

Here's what mine looked like after the upgrade:

![Screenshot 2022-05-20 235310 mod](https://user-images.githubusercontent.com/20692583/169636461-6204a137-4e54-4b9f-b95b-89bff70afad3.jpg)



I wasn't aware of the **Upgrade PlatformIO Core** option detailed above so I typed the following into the command line prompt at the bottom of the terminal window:
**C:\Python38\python.exe -m pip install  platformio**  

I've put a red circle around the two areas of interest.

Note - you must restart VScode before you'll see the change in the core.

**Comment by akinilicali** [comment]
Well, I tried all the cores: 6.01, older, development, etc. Fiddled with Python versions going back and forward. I had zero problems earlier on but for the last few days, I haven't been able to compile any robin nano v3 firmware. I reinstalled Vscode 4 times resetting all the folders etc.

**Comment by ellensp** [comment]
@akinilicali your error has nothing to do with this issue. 
you have enabled SDIO_SUPPORT when your controller does not support SDIO

**Comment by akinilicali** [comment]
> @akinilicali your error has nothing to do with this issue. you have enabled SDIO_SUPPORT when your controller does not support SDIO

Well, thank you indeed. You saved my day. I absent-mindedly enabled the SDIO_SUPPORT mistaking it for SDCARD support and disregarded the warning messages in yellow thinking they would not prevent the success of the compiling process. Silly me.
