### ISSUE TITLE
M20 Unknown command

### ISSUE THREAD

**Issue by aacorvalan** [MarlinFirmware/Marlin#24209]
Hello, I need to know if it is a bug or a configuration error. I have an Artillery Genius pro printer and when I enter the M20 command from the TFT it tells me "unknown command", however at the time of listing the SD files I can see and print them. SD is formatted as FAT32 and is 4Gb. I attach some data. Thank you

1- Update to bugfix-2.0.x by modifying #define SDSUPPORT and #define SDCARD_CONNECTION ONBOARD
2- Update TFT firmware

>>> M115
SENDING:M115
FIRMWARE_NAME:Marlin bugfix-2.0.x (May 17 2022 19:53:09) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Genius Pro EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Cap:SERIAL_XON_XOFF:0
Cap:BINARY_FILE_TRANSFER:0
Cap:EEPROM:1
Cap:VOLUMETRIC:1
Cap:AUTOREPORT_POS:0
Cap:AUTOREPORT_TEMP:1
Cap:PROGRESS:0
Cap:PRINT_JOB:1
Cap:AUTOLEVEL:1
Cap:RUNOUT:0
Cap:Z_PROBE:1
Cap:LEVELING_DATA:1
Cap:BUILD_PERCENT:0
Cap:SOFTWARE_POWER:0
Cap:TOGGLE_LIGHTS:0
Cap:CASE_LIGHT_BRIGHTNESS:0
Cap:EMERGENCY_PARSER:1
Cap:HOST_ACTION_COMMANDS:0
Cap:PROMPT_SUPPORT:0
Cap:SDCARD:0
Cap:REPEAT:0
Cap:SD_WRITE:0
Cap:AUTOREPORT_SD_STATUS:0
Cap:LONG_FILENAME:0
Cap:LFN_WRITE:0
Cap:CUSTOM_FIRMWARE_UPLOAD:0
Cap:EXTENDED_M20:0
Cap:THERMAL_PROTECTION:1
Cap:MOTION_MODES:0
Cap:ARCS:1
Cap:BABYSTEPPING:1
Cap:CHAMBER_TEMPERATURE:0
Cap:COOLER_TEMPERATURE:0
Cap:MEATPACK:0
Cap:CONFIG_EXPORT:0

Expected behavior:
Fix command error

Actual behavior:
not solved

error
![20220518_134008](https://user-images.githubusercontent.com/84159494/169114708-199fabfb-ca0f-4038-8ea2-867bb5a40351.jpg)
![20220518_141059](https://user-images.githubusercontent.com/84159494/169115148-c9048506-d4bc-4d47-8ed8-6a82feab15fb.jpg)
print menu
![20220518_141144](https://user-images.githubusercontent.com/84159494/169115408-5d6f9f58-712f-4f53-a2e3-69f76a7cbc1c.jpg)

**Comment by thisiskeithb** [comment]
`SDSUPPORT` is disabled in your firmware.

The TFT runs its own firmware, so you can still access the SD card.

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by aacorvalan** [comment]
These are the files with the configurations

[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/8721221/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/8721222/Configuration_adv.h.txt)
