### ISSUE TITLE
SPEED_POWER_INTERCEPT is never used

### ISSUE THREAD

**Issue by Fusseldieb** [MarlinFirmware/Marlin#24212]
### Description

Today I decided to tune my laser cutter a bit and while I was playing with SPEED_POWER_INTERCEPT and spending inumerous papers, I saw that it kinda didn't reflect any change. 

I had enough and went on to check the entire codebase. 

Yes, there is **NOWHERE** it is used outside of _SanityChecks_ or it being set to _0_.

Not in a single formula. I looked back as far as release branch 2.0.0 and didn't find it being used. WTF?

https://github.com/MarlinFirmware/Marlin/blob/c814fe98d7e250692908af03836a7c362a5ce843/Marlin/Configuration_adv.h#L3643-L3651

Therefore, above formula is also likely wrong.

### Steps to Reproduce

1. Try to use SPEED_POWER_INTERCEPT and see that it doesn't do anything, really

**Expected behavior:** Work (?)

**Actual behavior:** Does nothing - literally

#### Additional Information

Should I file a PR to remove it entirely?

**Comment by thisiskeithb** [comment]
@descipher ?

**Comment by descipher** [comment]
Yes and guess what, it is addressed in #22690

**Comment by thisiskeithb** [comment]
Closing since this is addressed in #22690
