### ISSUE TITLE
Z blinking from a number to "?" in my Creality Ender 3 Pro

### ISSUE THREAD

**Issue by ChrisFix13** [MarlinFirmware/Marlin#24210]
### Description

 Finished setting up the firmware to a Micro SD and then to my new BTT_SKR_V1.4 with Drivers TMC2209. Everything turns on correctly but the issue is with the Z axis. I press Auto Home and it starts doing the process but the Z axis only goes up, never down (The other axis do everything correctly). When it finishes, it says that the Z is not homed. So besides the Z it says 5 and then blinks to "?" sign. So I am unable to use the printer at all.

### Steps to Reproduce

1. [First Step] Turn on the printer and press Auto Home.
2. [Second Step] The X and Y work fine (i guess) but the Z only goes up and never goes down.

**Expected behavior:** [What you expect to happen] To have the printer tell me that the printer is ready for use.

**Actual behavior:** [What actually happens] It tells me STOPPED or Endstops. The Z changes from a number to the "?" sign

#### Additional Information
On the Zip you'll find:
platform.io
Configuration
Configuration_h
2 small videos showing the issue.
[Relevant_Files.zip](https://github.com/MarlinFirmware/Marlin/files/8721367/Relevant_Files.zip)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
