### ISSUE TITLE
When coolant flow is zero, laser stops but stays ON

### ISSUE THREAD

**Issue by Fusseldieb** [MarlinFirmware/Marlin#24213]
### Description

If a cooler/flowrate pin is defined and it drops to 0L (is turned off), the laser stops, the buzzer beeps and it freezes stationary burning a hole into the material, making the situation even worse (w/o refrigeration).

I opened this issue a year ago, someone merged (?) something down the line and I just tested it again _today_. The issue still persists!

Issue https://github.com/MarlinFirmware/Marlin/issues/22317. 

### Steps to Reproduce

1. Use laser as INLINE
2. While printing, turn chiller off
3. It begins to beep, stops and remains burning a hole

**Expected behavior:** Turn off as soon as it can. Overheating CO2 tubes can and **will** explode when massively overheated. One time this happened!

**Actual behavior:** Stops and burns a hole indefinitely.

#### Additional Information

No additional information

**Comment by thisiskeithb** [comment]
> someone merged (?) something down the line and I just tested it again today. The issue still persists!

Looking at Issue #22317, the referenced PR (#22690) is still open and has not been merged.

**Comment by descipher** [comment]
Yes, these and many other safety issues are addressed in PR #22690 please ask @thinkyhead to merge it.

**Comment by thisiskeithb** [comment]
Closing since this is addressed in #22690

**Comment by thisiskeithb** [comment]
Duplicate of #22317

**Comment by Fusseldieb** [comment]
> Duplicate of https://github.com/MarlinFirmware/Marlin/issues/22317

Yes, I've stated that above, but it was closed and limited, so I couldn't comment on it anymore to give feedback.

Since it's an existing bug in the current release, it should remain open, imo

Then, when https://github.com/MarlinFirmware/Marlin/pull/22690 is solved, https://github.com/MarlinFirmware/Marlin/issues/22317 could be closed too.

**Comment by thisiskeithb** [comment]
> Yes, I've stated that above, but it was closed and limited,

When I comment that something is a duplicate, it's to mark it as such within Github for tracking:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/13375512/169448910-34f644b8-e3b4-4a44-9270-bd23b87ae7e0.png">

> Since it's an existing bug in the current release, it should remain open, imo

Issues are closed when a PR is created.

Please test #22690 and comment your findings/issues on the open PR.
