### ISSUE TITLE
Creality Ender 3 with 4.2.7, CR Touch, nonmoving in -Z direction 

### ISSUE THREAD

**Issue by HappyTechnician** [MarlinFirmware/Marlin#24236]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Ender3 with 4.2.7 board, CR touch. configured with latest code. No movement in _z direction...

### Bug Timeline

5.20.22 to current, 5.23.22

### Expected behavior

Configured to:
Home Z @ center X,Y,      probe acted as testing pulse. No -Z movement
Probe Bi-liner, 5 points X,Y.      tried to home first.
No E heat, no bed heat for probe or homing.
have filament sensor, direct Extrusion, Twin Z Steppers in series, MicroSwiss Hot-end @ 350c max, bed 130c max,

### Actual behavior

Homed X and Y, moved to center, Raised 10mm, probe extended and retracted about 10 times and homing fail error on screen.

### Steps to Reproduce

1. boot up, initiate home.

### Version of Marlin Firmware

Bugfix 2.0.x  with ABM in VS Code into PIO

### Printer model

upgraded Creality Ender 3

### Electronics

Creality 4.2.7. STM32

### Add-ons

Twin Z steppers in parallel

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Additional information & file uploads

[Configuration_adv.pdf](https://github.com/MarlinFirmware/Marlin/files/8759567/Configuration_adv.pdf)
[Configuration.pdf](https://github.com/MarlinFirmware/Marlin/files/8759568/Configuration.pdf)

Mac wouldn't let me upload a ZIP file

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
I don't believe this is likely to be a bug.   

You don't seem to have done basic diagnostics Like looking at M119 status 
Or testing of basic movement with G1 commands. 
.
