### ISSUE TITLE
[BUG[ Filament sensor doesn't work in real time and does no check on "resume"

### ISSUE THREAD

**Issue by svd05** [MarlinFirmware/Marlin#24237]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Interruption filament runout sensor doesn't work in real time and do not check itself after press "continue/resume"

### Expected behavior

1. After triggered sensor all moves stop immediately and head parking in set coordinates.
2. After press button "continue/resume" marlin check status runout pins and if its triggered, than its will be still in parking (filament not loaded)

### Actual behavior

1. After the sensor is triggered, the head continues to move from 5 to 20 seconds (command "M600" waiting until all moves in the planner are completed from some buffer). After that, he parks for a change of plastic.
Its happens when firmware configure with interruptions on main board or interruptions in display.
2. Filament not loaded, but after press "continue\resume" printing continue and sensor do not react for anything.

### Version of Marlin Firmware

2.0.9.3

### Printer model

custom

### Electronics

BTT SKR Pro v1.2, tft 3.5 v3.0

### Add-ons

max31865, I2C_EEPROM, runout optical sensor which built in direct drive extruder

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/8766258/config.zip)

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by svd05** [comment]
Ok. I trying, but on today I have another error when compile 2.0.x (2.0.9.3 + skr pro v1.2 + max31865 don't have this problem): 
![Screenshot_20220530_214628](https://user-images.githubusercontent.com/97903083/171046751-18773f45-54a1-4c2d-aa18-d75a68b8c675.png)

**Comment by svd05** [comment]
Tested the bugfix-2.0.x. 
1. Now marlin checking loaded or unloaded filament, but doing this after few moves. Need checking **before** resume. Watch the [video](https://youtube.com/shorts/aCPLumvOg4Y).
2. Filament sensor still not work in real time (printing **not interrupt immediately** all moves or after printed lenght which set parameter "#define FILAMENT_RUNOUT_DISTANCE_MM " in Configuration.h

**Comment by svd05** [comment]
problem doesn't not fixed in last firmware version.
