### ISSUE TITLE
[BUG] Gcode reporting format M503 is a mess

### ISSUE THREAD

**Issue by rondlh** [MarlinFirmware/Marlin#24241]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

The gcode reporting output format M503, like for example the output of GcodeSuite::M906_report is a mess:

> echo:  M906X:900Y:900Z:900

I think this is because of the macro in serial.cpp, line 38

`#define _SP_N_STR(N) PGMSTR(SP_##N##_STR, STR_##N ":");`

which should be:

`#define _SP_N_STR(N) PGMSTR(SP_##N##_STR, " " STR_##N);`

this will correct the output to:
> echo:  M906 X900 Y900 Z900

I'm not sure if it causes other side effects.

### Bug Timeline

Don't know

### Expected behavior

Proper gcode reporting output

> echo:  M906 X900 Y900 Z900

### Actual behavior

Incorrect reporting output:

> echo:  M906X:900Y:900Z:900

### Steps to Reproduce

Check the output of M503

### Version of Marlin Firmware

Marlin 2.0.9.3 latest bugfix

### Printer model

Custom

### Electronics

Custom

**Comment by radek8** [comment]
fixed in
https://github.com/MarlinFirmware/Marlin/pull/24259

**Comment by rondlh** [comment]
Great job, thanks!
