### ISSUE TITLE
[BUG] menu_probe_offset.cpp build error

### ISSUE THREAD

**Issue by wykdtwisted** [MarlinFirmware/Marlin#24240]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I am trying to compile 2.0.x with VS for a FLSUN QQS-Pro.  I have attempted the build using bugfix and the associated up-to-date config files.  

**During the build I get the following error:**

![marlin_error](https://user-images.githubusercontent.com/106177008/170263903-7c1f3332-d1e1-42c9-a9ee-7c5be8853023.png)

**The if statement of code is as follows:**

  
    if ((FINE_MANUAL_MOVE) > 0.0f && (FINE_MANUAL_MOVE) < 0.1f) {
    char tmp[20], numstr[10];
    // Determine digits needed right of decimal
    const uint8_t digs = !UNEAR_ZERO((FINE_MANUAL_MOVE) * 1000 - int((FINE_MANUAL_MOVE) * 1000)) ? 4 :
                         !UNEAR_ZERO((FINE_MANUAL_MOVE) *  100 - int((FINE_MANUAL_MOVE) *  100)) ? 3 : 2;
    sprintf_P(tmp, GET_TEXT(MSG_MOVE_N_MM), dtostrf(FINE_MANUAL_MOVE, 1, digs, numstr));
    #if DISABLED(HAS_GRAPHICAL_TFT)
      SUBMENU_F(FPSTR(NUL_STR), []{ _goto_manual_move_z(float(FINE_MANUAL_MOVE)); });
      MENU_ITEM_ADDON_START(0 + ENABLED(HAS_MARLINUI_HD44780));
      lcd_put_u8str(tmp);
      MENU_ITEM_ADDON_END();
    #else
      SUBMENU_F(tmp, []{ _goto_manual_move_z(float(FINE_MANUAL_MOVE)); });
    #endif
  }

### Bug Timeline

New, started on build

### Expected behavior

Unknown

### Actual behavior

Unknown

### Version of Marlin Firmware

2.0.x Bugfix

### Printer model

FLSUN QQS-Pro

### Electronics

Stock

### Add-ons

None

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/8771177/Configuration_adv.zip)
[menu_probe_offset.zip](https://github.com/MarlinFirmware/Marlin/files/8771201/menu_probe_offset.zip)

**Comment by wykdtwisted** [comment]
My apologize for any improper formatting errors with this request.  I attempted to follow all the guidelines.  I am not a programmer, and I am a mildly computer literate (but I'm trying).

**Comment by ellensp** [comment]
Error report look good and is valid.

**Comment by ellensp** [comment]
Issue was introduced https://github.com/MarlinFirmware/Marlin/commit/a5e1d4c50ae40c8203d8490be83ef86e16ebf1c2

**Comment by tpruvot** [comment]
could be grouped with #24239 so...

**Comment by wykdtwisted** [comment]
> Issue was introduced [a5e1d4c](https://github.com/MarlinFirmware/Marlin/commit/a5e1d4c50ae40c8203d8490be83ef86e16ebf1c2)

Again, not a programmer.  I looked at the reference above and my code looks the same (code with green highlights).  Is there something I'm missing?

Thank you again for all the help.

**Comment by tpruvot** [comment]
This should be fixed soon, seems recent changes not finished...

**Comment by ellensp** [comment]
These are us working on the problem...  be patient
 
find
`  SUBMENU_F(tmp, []{ _goto_manual_move_z(float(FINE_MANUAL_MOVE)); });`
replace with
`  SUBMENU_F(FPSTR(tmp), []{ _goto_manual_move_z(float(FINE_MANUAL_MOVE)); });`

Looks like it should work

**Comment by tpruvot** [comment]
or just F(tmp) had to fix a few ones too on my fork https://github.com/tpruvot/Marlin/commit/9c3ebf704cff44a03667a3bebcb0a6520207ec1b

**Comment by wykdtwisted** [comment]
> These are us working on the problem... be patient
> 
> find ` SUBMENU_F(tmp, []{ _goto_manual_move_z(float(FINE_MANUAL_MOVE)); });` replace with ` SUBMENU_F(FPSTR(tmp), []{ _goto_manual_move_z(float(FINE_MANUAL_MOVE)); });`
> 
> Looks like it should work

Thank you.  I will try it and report the results.  I appreciate all the help.  The Contributors and folks who work the bugs are fantastic and help us non-professionals so much.

**Comment by wykdtwisted** [comment]
FANTASTIC!!  Thank you all so much I appreciate the help!  Amazing

**Comment by ellensp** [comment]
@tpruvot can you add this to your PR https://github.com/MarlinFirmware/Marlin/pull/24239

**Comment by ellensp** [comment]
@tpruvot can you add this to your PR https://github.com/MarlinFirmware/Marlin/pull/24239

**Comment by tpruvot** [comment]
right, i can

**Comment by ellensp** [comment]
Since a pr has been created, closing this issue
