### ISSUE TITLE
MINTEMP check not working - SAFETY ISSUE

### ISSUE THREAD

**Issue by pillopaolo** [MarlinFirmware/Marlin#24257]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

With the heater ON, MINTEMP error is not triggered if I disconnect the thermistor .
Luckily, 20+ seconds later the THERMAL_RUNAWAY error is triggered.

It seems that the issue is due to the wrong calculation of tmin in temperature.cpp, due to a bug in _MAX() macro.

Incriminated line in temperature.cpp:
```cpp
const celsius_t tmin = _MAX(HEATER_##NR##_MINTEMP, TERN(TEMP_SENSOR_##NR##_IS_CUSTOM, 0, (int)pgm_read_word(&TEMPTABLE_##NR [TEMP_SENSOR_##NR##_MINTEMP_IND].celsius)));
```
It should calculate tmin = max (5, -15) = 5.
Instead it calculates -15, which is wrong and messes up the MINTEMP detection.

I fixed the issue by calculating the second argument (quite complex) of _MAX() separately, as follows:
```cpp
const celsius_t tmin_tmp = TERN(TEMP_SENSOR_##NR##_IS_CUSTOM, 0, (int)pgm_read_word(&TEMPTABLE_##NR [TEMP_SENSOR_##NR##_MINTEMP_IND].celsius)); 
const celsius_t tmin = _MAX(HEATER_##NR##_MINTEMP, tmin_tmp); 
```
Notes: 
a) In my case: HEATER_0_MINTEMP =  5
b) After disconnecting the thermistor I read -15 °C, which is correct, being the lowest temperature in the thermistor table.
c) 2022-05-28 bugfix I see that _MAX() macro has been modified, but even with that fix the above problem is not solved.

### Expected behavior

MINTEMP error should be triggered immediately.

### Version of Marlin Firmware

Marlin-2.0.9.2

**Comment by thinkyhead** [comment]
The problem seems to be that `_MAX` has some sign issue, apparently. The -15 was probably appearing as a very large unsigned number. I'll mess around with the `_MIN`/`_MAX` macros / functions and try to get them to behave properly in these cases.

**Comment by thinkyhead** [comment]
Which thermistor value were you using? Can you provide your configurations?

**Comment by thinkyhead** [comment]
I bet the size of `int` is not 16-bits on some targets, so the `unsigned short` is not being sign-extended after the word is read, giving something like +65521.

The solution is to cast the result of `pgm_read_word` immediately to an `int16_t` instead of the less-well-defined `int`.

**Comment by pillopaolo** [comment]
Thanks for the attention and fix. 

However I noted that you applied the int16_t fix to my quick&dirty fix, i.e. the one where I split the calculation in 2 lines (I did it without understanding anything, it simply works).
This does not prove that int16_t is the solution (as my fix was already working) + is not so elegant (2 lines instead of 2) in my opinion.

If int16_t really works, why not applying it directly to the original single-line calculation?
