### ISSUE TITLE
Not defined pin TEMP_SENSOR_0 for board BTT SKR Pro v1.2

### ISSUE THREAD

**Issue by svd05** [MarlinFirmware/Marlin#24264]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Firmware not compile for SKR Pro v1.2 with max31865.
![Screenshot_20220530_234540](https://user-images.githubusercontent.com/97903083/171057392-139b361a-d011-47e7-852f-52ae0f51d2fd.png)

### Bug Timeline

new

### Version of Marlin Firmware

2.0.x

### Printer model

custom

### Electronics

skr pro v1.2, tft35 v3.0, max31865

### Your Slicer

Cura

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/8800673/config.zip)

**Comment by ellensp** [comment]
Provided Config files are all sock bugfix files. no edits.

**Comment by ellensp** [comment]
There is no such error in bugfix Marlin/src/inc/SanityCheck.h

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/inc/SanityCheck.h#L1869 is a comment
or even in 2.0.x https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/inc/SanityCheck.h#L1869
