### ISSUE TITLE
[BUG] Probe wizard is not showing

### ISSUE THREAD

**Issue by URBANsUNITED** [MarlinFirmware/Marlin#24276]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Compiled the latest bugfix from today (02.06.22) and the latest stable 2.0.9.3
Both with same symptoms:

The probe wizard is not showing up even it is prober activated:

>   // Add Probe Z Offset calibration to the Z Probe Offsets menu
  #if HAS_BED_PROBE
    #define PROBE_OFFSET_WIZARD
    #if ENABLED(PROBE_OFFSET_WIZARD)
      //
      // Enable to init the Probe Z-Offset when starting the Wizard.
      // Use a height slightly above the estimated nozzle-to-probe Z offset.
      // For example, with an offset of -5, consider a starting height of -4.
      //
      #define PROBE_OFFSET_WIZARD_START_Z -4.0

      // Set a convenient position to do the calibration (probing point and nozzle/bed-distance)
      //#define PROBE_OFFSET_WIZARD_XY_POS { X_CENTER, Y_CENTER }
    #endif

Both config files are here:
[Archiv.zip](https://github.com/MarlinFirmware/Marlin/files/8826680/Archiv.zip)

### Actual behavior

![IMG_0962](https://user-images.githubusercontent.com/6212300/171703518-f83dff1d-38ef-4f6b-9a28-8a35957d4b3c.jpeg)

### Version of Marlin Firmware

2.0.9.3

### Printer model

Ender 3 pro

### Electronics

BigTreeTech SKR Mini E3 V3.0

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Other things to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
- [ ] Log output from the host. (`M111 S247` for maximum logging.)
- [ ] Images or videos demonstrating the problem, if it helps to make it clear.
- [ ] A G-Code file that exposes the problem, if not affecting _all_ G-code.

**Comment by GMagician** [comment]
That's because you don't have any probe installed, see below defines.
Z_PROBE_SERVO_NR, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, SOLENOID_PROBE, SENSORLESS_PROBING, RACK_AND_PINION_PROBE or MAGLEV4

**Comment by thisiskeithb** [comment]
> That's because you don't have any probe installed, see below defines.

They have `BLTOUCH` enabled in their config. Having said that, the attached configs are quite outdated.

I just did a quick test with `BOARD_BTT_SKR_MINI_E3_V3_0` and `BLTOUCH` using the latest `bugfix-2.0.x` (12aded9) and the Probe Offset Wizard shows up as expected.
