### ISSUE TITLE
2.0.9.4 compile errors when number of Z Steppers is > 1

### ISSUE THREAD

**Issue by SwiftNick** [MarlinFirmware/Marlin#24287]
### Bug Description

**Problem:**
In the 2.0.9.4 Release, using the Anycubic Chiron configs (and probably any other config with more than 1 Z Stepper), the build fails with:

```
Marlin\src\module\motion.cpp: In function 'void homeaxis(AxisEnum)': Marlin\src\module\motion.cpp:1902:65: error: 'class Stepper' has no member named 'set_z3_lock'; did you mean 'set_z1_lock'? stepper.set_z1_lock, stepper.set_z2_lock, stepper.set_z3_lock ^~~~~~~~~~~ set_z1_lock Marlin\src\module\motion.cpp:1908:52: error: 'class Endstops' has no member named 'z3_endstop_adj'; did you mean 'z2_endstop_adj'? 0, endstops.z2_endstop_adj, endstops.z3_endstop_adj ^~~~~~~~~~~~~~ z2_endstop_adj Marlin\src\module\motion.cpp:1972:21: error: 'class Stepper' has no member named 'set_z3_lock'; did you mean 'set_z1_lock'? stepper.set_z3_lock(false); ^~~~~~~~~~~ set_z1_lock
```

**Cause:**
The definition for `NUM_Z_STEPPER_DRIVERS` has been removed from the 2.0.9.4 configs.
In the 2.1.0.0 release, `NUM_Z_STEPPERS` is set automatically in `Conditionals_LCD.h` [[Line 705]](https://github.com/MarlinFirmware/Marlin/blob/959a6c4f7037345dd6f2bf5abe3c376981988aed/Marlin/src/inc/Conditionals_LCD.h#L705) but this behaviour is not present in 2.0.9.4.

**Solution:**
The quick fix for 2.0.9.4 is to add the `#define NUM_Z_STEPPER_DRIVERS 2` definition back in the `Configuration_adv.h` file.

**This issue is not present in the 2.1 release**

**Comment by thinkyhead** [comment]
Everything should be in order now, with 2.0.x matching the release-2.0.9.4 config examples, and 2.1.x the same as it was (but with a rebase on the patched 2.0.x).
