### ISSUE TITLE
[BUG] lcd\menu\menu_advanced.cpp uses future method name in 2.0.x branch

### ISSUE THREAD

**Issue by theonethread** [MarlinFirmware/Marlin#24288]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin\src\lcd\menu\menu_advanced.cpp in 2.0.x branch uses `LOOP_NUM_AXES(a)` method which was only renamed in 2.1.x, due the build fails. Changing it to `LOOP_LINEAR_AXES(a)` solves the build.

### Bug Timeline

Found today when merging 2.0.x into my fork

### Expected behavior

Marlin fork compiles without error after merged into my custom branch.

### Actual behavior

Errors:
Marlin\src\lcd\menu\menu_advanced.cpp: In function 'void menu_advanced_velocity()':
Marlin\src\lcd\menu\menu_advanced.cpp:432:19: error: 'a' was not declared in this scope
  432 |     LOOP_NUM_AXES(a)
      |                   ^
Marlin\src\lcd\menu\menu_advanced.cpp:432:5: error: 'LOOP_NUM_AXES' was not declared in this scope; did you mean 'LOOP_LINEAR_AXES'?
  432 |     LOOP_NUM_AXES(a)
      |     ^~~~~~~~~~~~~
      |     LOOP_LINEAR_AXES
Marlin\src\lcd\menu\menu_advanced.cpp: In function 'void menu_advanced_steps_per_mm()':
Marlin\src\lcd\menu\menu_advanced.cpp:578:17: error: 'a' was not declared in this scope
  578 |   LOOP_NUM_AXES(a)
      |                 ^
Marlin\src\lcd\menu\menu_advanced.cpp:578:3: error: 'LOOP_NUM_AXES' was not declared in this scope; did you mean 'LOOP_LINEAR_AXES'?
  578 |   LOOP_NUM_AXES(a)
      |   ^~~~~~~~~~~~~
      |   LOOP_LINEAR_AXES
*** [.pio\build\STM32F103RE_creality\src\src\lcd\menu\menu_advanced.cpp.o] Error 1

### Steps to Reproduce

1. check out https://github.com/theonethread/Orc-Flavored-Marlin
2. check out commit 482b3a9bd307543a24399f73d1812ca090d0a9d3
3. run ABM for creality 512k
4. inspect error
5. check out commit 3b9fc00d9ac1b779fc912b3ae18f62a224adb550
    * note: only above mentioned method name changed (LOOP_NUM_AXES -> LOOP_LINEAR_AXES)
6. run ABM for creality 512k
7. success

### Version of Marlin Firmware

2.0.x latest

### Printer model

creality ender 3 pro, details listed in fork's readme

### Electronics

none affected (stepper dumpers for x & y axis)

### Add-ons

none affected (alu extruder, ptfe bowden)

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Other things to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
- [ ] Log output from the host. (`M111 S247` for maximum logging.)
- [X] Images or videos demonstrating the problem, if it helps to make it clear.
- [ ] A G-Code file that exposes the problem, if not affecting _all_ G-code.

### Additional information & file uploads

![marlin_2 0 x_advanced_menu_error](https://user-images.githubusercontent.com/7080741/172000303-741294f9-ff91-4bfe-9b75-ce868fdfe137.png)
[marlin_2.0.x_advanced_menu_error.zip](https://github.com/MarlinFirmware/Marlin/files/8837755/marlin_2.0.x_advanced_menu_error.zip)

**Comment by ellensp** [comment]
This has been fixed. 
https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/lcd/menu/menu_advanced.cpp#L432
https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/lcd/menu/menu_advanced.cpp#L578
