### ISSUE TITLE
[BUG] Marlin 2.1 LCD Very slow, no chance to use it

### ISSUE THREAD

**Issue by lipewww** [MarlinFirmware/Marlin#24298]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

I recently upgraded to Marlin 2.1, but after updating, my LCD is VERY slow, when starting the printer the startup screen takes several seconds to come out, and it goes out gradually, this is how it is for the rest of the menu. Impossible to adjust something on the machine.

### Bug Timeline

2 days ago when I updated to Marlin 2.1

### Version of Marlin Firmware

Marlin 2.1

### Printer model

Anet A6

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Other things to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
- [ ] Log output from the host. (`M111 S247` for maximum logging.)
- [ ] Images or videos demonstrating the problem, if it helps to make it clear.
- [ ] A G-Code file that exposes the problem, if not affecting _all_ G-code.

### Additional information & file uploads

Here's a video that shows the problem I'm having:
https://imgur.com/a/dv1okVK

Also follow my firmware configuration:
[Marlin 2.1.zip](https://github.com/MarlinFirmware/Marlin/files/8846125/Marlin.2.1.zip)

**Comment by rq3** [comment]
This is the exact issue I reported in Issue 24252, 10 days ago. I have now compiled and loaded Release 2.1, Release 2.0.9.4, and the latest bugfix for 2.1.

They all exhibit this problem.

The last successful bugfix was May 22 for 2.0.9.3

**Comment by thisiskeithb** [comment]
Duplicate of #24252

**Comment by ellensp** [comment]
This one is a REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER on a BOARD_ANET_10
So may not be related.

**Comment by ellensp** [comment]
Im looking into this, it may be related to the other, unknown yet
I have replicated this on a Sanguinololu (same pins, using your configuration,h)

**Comment by ellensp** [comment]
disabling SDSUPPORT make it usable again.  Not a solution, just a clue

**Comment by lipewww** [comment]
> 

I'll check it out tomorrow, good luck figuring it out!

**Comment by ellensp** [comment]
Did a git bisect and it says issue is in
commit 15b6159f6af740f17db2dc8815697759c714cc12
Date:   Mon May 23 09:13:17 2022 +0700

    🩹 Adjust manage_media for slow/late media init (USB FD) (#24015)

**Comment by ellensp** [comment]
Commenting out the following line in Marlin/src/sd/cardreader.cpp
      IF_DISABLED(SD_IGNORE_AT_STARTUP, prev_stat = 0);

gets around it.. 
  

It only happens is there is no sdcard, if scard is inserted on bootup screen updates at expected rate

**Comment by ellensp** [comment]
I purpose  this should be 

```
    #if PIN_EXISTS(SD_DETECT)
        IF_DISABLED(SD_IGNORE_AT_STARTUP, prev_stat = 0);
    #endif
```

Since this board doesn't use SD_DETECT_PIN it is disabled.

I also added support for this pin to my tests, and it seem to function as expected

**Comment by bitranox** [comment]
@ellensp , @lipewww , @thisiskeithb , @rq3 
I had similar issue on the SKR1.4 board after booting -  the LCD was echoing `no sdcard ` and was extremely slow.
the solution was to enable `#define SD_IGNORE_AT_STARTUP` in `Configuration_adv.h`.
In that case the SDCARD will not be initialized on startup, but remains usable.
I guess thats better then to disable `SDSUPPORT` all together.

disabling or inverting the `SD_DETECT_PIN` did not help.

Yours sincerely
Bitranox, Vienna

**Comment by ellensp** [comment]
This has been merged.

**Comment by lipewww** [comment]
solved here, but how am I going to print with my sd card now?

**Comment by rq3** [comment]
> This has been merged.

The latest bugfix works fine for me under both Classic and Color UI, and the SD card is perfectly useable.

Thank you!

**Comment by lipewww** [comment]
> > This has been merged.
> 
> The latest bugfix works fine for me under both Classic and Color UI, and the SD card is perfectly useable.
> 
> Thank you!

if I download the bugfix 2.1 again is it already resolved?
