### ISSUE TITLE
[BUG] LCD freezes/very sluggish after upgrade if SD card is left in the mainboard

### ISSUE THREAD

**Issue by ucirello** [MarlinFirmware/Marlin#24301]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Immediately upon upgrade to 2.0.9.4, then 2.1, and bugfix-2.1 (371ac49fc137fbae6bf58491e274d1099ddafa34), the LCD freezes, or at least gets very sluggish. 

It worked fine with 2.0.9.3.

### Bug Timeline

Since 2.0.9.4 - did not bisect in search for the first offending commit

### Expected behavior

I expected the LCD to render quickly and be able to navigate through all menus. Turning the knob clockwise or counter-clockwise would immediately change feed rate.

### Actual behavior

Depending on the boot sequence it will either freeze completely, or be very sluggish.

The info screen renders in more than 15s per half. 

The wheel button seems to not be able to open the main menu.

Turning the knob clockwise or counter-clockwise would immediately change feed rate affects the feed rate, but it takes a long time for the number to update.

### Steps to Reproduce

1. Compile bugfix-2.1 (371ac49fc137fbae6bf58491e274d1099ddafa34) with the given configuration files.
2. Use a LPC1769 board (tested with MKS sgenl v2) with a RepRap Full Graphical Display and flash the firmware.
3. LCD freezes.

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.1.x (Jun  6 2022 18:18:47) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0

### Printer model

Modded Ender 3

### Electronics

MKS SGENL v2, Discount Full Graphic Smart Controller

### Add-ons

EZNEO, EZABL, UART based serial connection

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Other things to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
- [ ] Log output from the host. (`M111 S247` for maximum logging.)
- [X] Images or videos demonstrating the problem, if it helps to make it clear.
- [ ] A G-Code file that exposes the problem, if not affecting _all_ G-code.

### Additional information & file uploads

[bugfix-2.1-config.zip](https://github.com/MarlinFirmware/Marlin/files/8849270/bugfix-2.1-config.zip)

![image](https://user-images.githubusercontent.com/138827/172277241-b8ebe839-742c-4619-aa59-1bda8af11421.png)
![image](https://user-images.githubusercontent.com/138827/172277253-0ff9acae-ca26-436a-89a1-25851bce07d8.png)

**Comment by ellensp** [comment]
I'm looking at a similar issue on a 1284p  https://github.com/MarlinFirmware/Marlin/issues/24298
Can you test disabling sdsupport as a test ?
This stops the issue on the 1284p, not a solution, but is a big clue

**Comment by ucirello** [comment]
@ellensp it seems that it is a combination of `SDSUPPORT` with `SDCARD_CONNECTION`. The minimal configuration necessary to reproduce the issue is:

Configuration.h
```cpp
#define MOTHERBOARD BOARD_MKS_SGEN_L_V2
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
#define SDSUPPORT
````

Configuration_adv.h
```cpp
#define SDCARD_CONNECTION LCD
```

platformio.ini
```ini
[platformio]
#...
default_envs = LPC1769
```

**Comment by ucirello** [comment]
@ellensp @thisiskeithb I bisected and the culprit seems to be:

```
15b6159f6af740f17db2dc8815697759c714cc12 is the first bad commit
commit 15b6159f6af740f17db2dc8815697759c714cc12
Author: Robby Candra <robbycandra.mail@gmail.com>
Date:   Mon May 23 09:13:17 2022 +0700

    🩹 Adjust manage_media for slow/late media init (USB FD) (#24015)

 Marlin/src/sd/cardreader.cpp | 38 +++++++++++++++++++++++++-------------
```

**Comment by ellensp** [comment]
@ucirello see issue https://github.com/MarlinFirmware/Marlin/issues/24298

**Comment by ellensp** [comment]
closing this as a duplicate of https://github.com/MarlinFirmware/Marlin/issues/24298
