### ISSUE TITLE
How to manage a moving platform

### ISSUE THREAD

**Issue by zeryabmoussaoui** [MarlinFirmware/Marlin#2430]
Is it possible to configure Marlin to manage a moving-plaform ?

If not , how about this kind of features ?

**Comment by AnHardt** [comment]
> Is it possible to configure Marlin to manage a moving-platform ?

Yes it is. For a normal printer, working in a cartesian coordinate system, moving the bed is the same as moving the nozzle - but the opposite direction.

**Comment by zeryabmoussaoui** [comment]
@AnHardt 
Thanks for your answer .
i planned to make the bed 2DoF and the noozle 1DoF, so alll i have to do is to consider it as a 3 DoF noozle ?

**Comment by AnHardt** [comment]
Pardon.
What does DoF mean?

**Comment by tonnico** [comment]
Degree of freedom :)

Which part is moving is not that important. How is more important. Like CoreXY, standard Cartesian, Delta...

**Comment by zeryabmoussaoui** [comment]
Thank you very much ,  I was expecting some specific treatments in this case ,  do you know any printer with the plateform moving based on Marlin ?

**Comment by tonnico** [comment]
Velleman K8200 for example.

**Comment by zeryabmoussaoui** [comment]
Thank you very much ! 
This issue can be closed.
