### ISSUE TITLE
Noob and I can not get it to compile 

### ISSUE THREAD

**Issue by Caldyan** [MarlinFirmware/Marlin#24312]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have an Ender 3 V2.  I just bought a Creality Sprite extruder.  I am trying to change the code to move where the BL Touch is and the esteps.  Also a handful of other changes.  
I can not get the code to compile even if I load an unaltered version i want to use of it or even any version of it downloaded from here.  I currently have 5 "problems" and about 40 issues in the Terminal.
Problems are:
operator '&&' has no right operand [Ln 1586, Col 53]
expected an expression C/C++(29) [Ln 1586, Col 53]
#error "FAN_SOFT PWM is required for your board. Enable it to continue" [Ln 2019, Col 6]
#error directive: "FAN_SOFT_PWM is required for your board. Enable it to continue C/C++(35) [Ln 2019, Col 6]

And a warning:
'void waitSpiTxEnd(spi_dev*)' defined but not used [-Wunused-function] [Ln 420, Col 13

Original file is folder: Marlin-bugfix-JyersUI
move to correct Configuration Files to Marlin folder
modfied - but did not touch anything related to the code in relation to the errors or their respective lines relating to the codes.
But would not compile with the original files unmodified.

### Expected behavior

Expected it to compile

### Actual behavior

Doesn't compile without  issues

### Version of Marlin Firmware

try to compile new firmware

### Printer model

Ender 3 V2

### Electronics

BL Touch, 4.2.7 motherboard, new (installed just now) Creality Sprite Extruder

### Add-ons

raspberry pi

### Bed Leveling

ABL Linear grid

### Your Slicer

Cura

### Host Software

OctoPrint

### Other things to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
- [ ] Log output from the host. (`M111 S247` for maximum logging.)
- [ ] Images or videos demonstrating the problem, if it helps to make it clear.
- [ ] A G-Code file that exposes the problem, if not affecting _all_ G-code.

### Additional information & file uploads

Current Config files

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8863890/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/8863891/Configuration_adv.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
