### ISSUE TITLE
wait for user

### ISSUE THREAD

**Issue by Enzo-Enz** [MarlinFirmware/Marlin#24327]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi guys

Is there any way to solve this error

![Screenshot (7)](https://user-images.githubusercontent.com/75531691/173175024-38c9d7be-ad6e-4a56-b9a0-3b22e213ceb9.png)

### Bug Timeline

new

### Version of Marlin Firmware

2.1.x

### Electronics

ramps

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/8883351/config.zip)

**Comment by ellensp** [comment]
resolved by https://github.com/MarlinFirmware/Marlin/pull/24313 and https://github.com/MarlinFirmware/Marlin/pull/24310
