### ISSUE TITLE
[BUG] Marlin crashes when pressing button on BTT SKR TFT35 V3.0 E3 in MARLIN mode (with SPEAKER defined)

### ISSUE THREAD

**Issue by autonumous** [MarlinFirmware/Marlin#24339]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin crashes and reloads when pressing the LCD button[with SPEAKER enabled in configuration.h].

I've recently tried upgrading my printer to latest firmware version when i noticed the issue.  
Im running an Ender 3 with a BTT SKR Mini E3 V2 mainboard and a BTT TFT35 V3.0 E3 LCD.  

Issue can be replicated with a minimally configured system, eg using current bugfix-2.1.x then making the following changes

configuration.h
```
#define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V2_0
#define SERIAL_PORT 2
#define SPEAKER
#define CR10_STOCKDISPLAY
```
platform.ini
```
default_envs = STM32F103RE_btt_USB_maple
```

When starting up, all looks ok, the button can be rotated, but when pressed (to access the menu) it crashes

Previously using v2.0.9.3 with no issues.  

Fixes
Disabling SPEAKER resolved the issue

Or using the LCD in touch mode.

### Expected behavior

pressing the knob/button, I expect to access the menu

### Actual behavior

pressing the button causes a crash and controller/marlin reloads

### Steps to Reproduce

1. Flash firmware
2. Power on
3. if in Marlin mode, press button
   else hold button to switch to Marlin mode, then press button

### Version of Marlin Firmware

2.0.9.4, bugfix-2.0.x, 2.1.x, bugfix-2.1.x 

### Printer model

Ender3 Pro

### Electronics

BIGTREE  SKR Mini E3 V2

### Add-ons

BIGTREE TFT35 V3.0 E3 screen

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[bug.zip](https://github.com/MarlinFirmware/Marlin/files/8886875/bug.zip)

**Comment by Bob-the-Kuhn** [comment]
Is your BTT TFT35's firmware up to date?

**Comment by autonumous** [comment]
> Is your BTT TFT35's firmware up to date?

Yep, V27.    Also tried flashing a newly compiled one yesterday.

**Comment by thisiskeithb** [comment]
> default_envs = STM32F103RE_btt_USB_maple

Maple environments are deprecated. Please reflash with the non-maple environment and test again.

**Comment by autonumous** [comment]
> > default_envs = STM32F103RE_btt_USB_maple
> 
> Maple environments are deprecated. Please reflash with the non-maple environment and test again.

I think you have identified the issue.     

used STM32F103RE_btt_USB with SPEAKER enabled and it worked as expected

Arghhh wish I knew that before, thanks.
