### ISSUE TITLE
[FR] LCD move menu should treat rotary axes in degrees, even in inch mode

### ISSUE THREAD

**Issue by DerAndere1** [MarlinFirmware/Marlin#24333]
### Is your feature request related to a problem? Please describe.

When using the LCD menus, rotational axes (`AXISn_ROTATES` enabled) should be treated using units of angular degrees, even in inch mode. Currently the move menu seems to treat values for all axes as given in length units (depending on inch mode). 

### Are you looking for hardware support?

ZONESTAR_LCD

### Describe the feature you want

- The move menu is probably the most used one and should be improved first. 
- For configuration menus we can document that the user first has to change to metric mode (G21) and enter all values in angular degrees (for rotational axes) or mm (for linear axes)
- improving display UI other than default UI for ZONESTAR_LCD is out of scope for this issue

**Comment by thisiskeithb** [comment]
Closing since you've opened PR https://github.com/MarlinFirmware/Marlin/pull/24334
