### ISSUE TITLE
Temperature calculation for PT1000 not working

### ISSUE THREAD

**Issue by KZ-Erge** [MarlinFirmware/Marlin#24342]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

In MAX31865.cpp the normalization to 100 ohm (line 464) should be done before line 453. Now if i use pt1000, it always reports 0 degree as line 453 only works for pt100.

### Version of Marlin Firmware

bugfix-2.1.x 

### Printer model

ENDER-5

### Electronics

MKS-SBASE

### Add-ons

MAX31865 board from adafruit, PT1000

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Edit: added config.zip
[config.zip](https://github.com/MarlinFirmware/Marlin/files/8892927/config.zip)
_

**Comment by thisiskeithb** [comment]
>Don't forget to include
> A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

You failed to attach your configs.

**Comment by zeleps** [comment]
You're probably right, this was copied and refactored from the original adafruit library without too much thought. I'll try to fix and test it this weekend.

**Comment by thisiskeithb** [comment]
Closing since there’s now a PR to fix it: https://github.com/MarlinFirmware/Marlin/pull/24407
