### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by tabernaspt** [MarlinFirmware/Marlin#24340]
### Is your feature request related to a problem? Please describe.

I bought a touchscreen and brings a firmware of its own but does not have some features with the cure

### Are you looking for hardware support?

Ender 3 pro, 4.2.2 board, touchscreen 

### Describe the feature you want

That the features of the stop cure and change filament work

**Comment by thisiskeithb** [comment]
> I bought a touchscreen and brings a firmware of its own but does not have some features with the cure

You will need to request those firmware features from the creator of the touch screen.
