### ISSUE TITLE
Biqu BX TFT stuck on marlin splash screen after flashing firmware.

### ISSUE THREAD

**Issue by Antibodyarmy** [MarlinFirmware/Marlin#24353]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After compiling the latest bugfix firmware, and flashing firmware.bin the TFT display is stuck on the marlin splash screen. 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8896457/Configuration.zip)

![IMG_20220614_003626406](https://user-images.githubusercontent.com/78243892/173495245-e5210cd1-3185-4c1c-93ae-6b3bf41bc81f.jpg)

### Expected behavior

finish flashing firmware, and enter the printer TFT printer idle display. 

### Actual behavior

finished flashing firmware, got hung/stuck on marlin splash screen. 

### Steps to Reproduce

compile firmware with biqu/bx config from examples. flash firmware. 

### Version of Marlin Firmware

latest bugfix

### Printer model

Biqu BX

### Electronics

Stock - Biqu BX tft 70 and BTT_SKR_SE_BX

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by hcet14** [comment]
@contributors
This is just a question and I hope nobody gets me wrong. There are a lot of issues connected to intelligent displays with a µC. Those displays have certainly their own FW. Shouldn't the companies selling those display adapt their FW to new versions of Marlin? To me it sounds like a classical chicken or the egg causality dilemma.
Kind regards, hcet14

**Comment by thisiskeithb** [comment]
> There are a lot of issues connected to intelligent displays with a µC. Those displays have certainly their own FW. Shouldn't the companies selling those display adapt their FW to new versions of Marlin?

@hcet14: The BX’s TFT is not a standalone TFT. Marlin is fully in charge of controlling it, so this bug is on the Marlin side.

**Comment by hcet14** [comment]
> The BX’s TFT is not a standalone TFT.

> Electronics: Stock - Biqu BX tft 70 and BTT_SKR_SE_BX

@thisiskeithb: Sorry, probably my fault. I understand, Antibodyarmy is using a Biqu BX tft 70 ["https://www.biqu.equipment/products/btt-tft43-v3-0-tft50-v3-0-tft70-v3-0-display-touch-screen-two-working-modes"](https://www.biqu.equipment/products/btt-tft43-v3-0-tft50-v3-0-tft70-v3-0-display-touch-screen-two-working-modes).

**Comment by thisiskeithb** [comment]
> I understood Antibodyarmy is using a Biqu BX tft 70

They are and as I stated above, it is not a standalone TFT. The TFT70 used on the BX is directly controlled/connected to the motherboard via a 40pin cable.

Biqu/BigTreeTech also makes a standalone TFT70 in your link and that is *not* the same one used on the BX. The one in your link connects via two 10-pin IDC + 5-pin serial cables. Those simply external computers / G-code senders.

> Shouldn't the companies selling those display adapt their FW to new versions of Marlin?

Yes, but Biqu/BigTreeTech *does* keep up their TFT firmware (and provides instructions on what to enable in Marlin so they can communicate / work properly), so you should post there instead: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

At any rate, this is causing unneeded noise and not related to the reported bug.

**Comment by hcet14** [comment]
> At any rate, this is causing unneeded noise and not related to the reported bug.

Sorry, I apologize. Thanks for the explanation. I read a little around and think I understood.

**Comment by thisiskeithb** [comment]
Thanks to some detective work by @rhapsodyv, this is the breaking commit:

- [🩹 Fix FSTR / PSTR usage](https://github.com/MarlinFirmware/Marlin/commit/e354cd15b224a4e12d3c5ba63986a249ad055f83)

**Comment by rhapsodyv** [comment]
try change the file:
`Marlin/src/HAL/shared/Marduino.h`
code:
`#define FTOP(S) (reinterpret_cast<const char*>(S))`
to
`#define FTOP(S) (reinterpret_cast<const char* const>(S))`
and let me know if it works for you

**Comment by thisiskeithb** [comment]
> try change the file: `Marlin/src/HAL/shared/Marduino.h`

A [stock `bugfix-2.1.x` BX config](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/BIQU/BX) (with corrected serial ports) doesn't work, but a minimal `bugfix-2.1.x` config works:

```
#define MOTHERBOARD BOARD_BTT_SKR_SE_BX
#define SERIAL_PORT 1
#define SERIAL_PORT -1
#define TFT_COLOR_UI
#define BIQU_BX_TFT70
```

**Comment by rhapsodyv** [comment]
try disable `SDSUPPORT` to test

**Comment by thisiskeithb** [comment]
@Antibodyarmy: Please try the attached firmware: [Biqu-BX-bugfix-2.1.x-firmware.zip](https://github.com/MarlinFirmware/Marlin/files/8942946/Biqu-BX-bugfix-2.1.x-firmware.zip)

It bootloops on my BX, but works for rhapsodyv & may work for you.

**Comment by Antibodyarmy** [comment]
@thisiskeithb It did not work, but now there is a strange behaviour where it boot loops turning on and off

**Comment by thisiskeithb** [comment]
> now there is a strange behaviour where it boot loops turning on and off

That's the same thing I see on my setup.

**Comment by Antibodyarmy** [comment]
just to clarify my initial issue when I posted, there wasn't a boot loop behavior, but it was stuck on the marlin boot splash screen. the boot loop was introduced with the changes in that firmware you posted and with the changes suggested by rhapsodyv .

**Comment by thisiskeithb** [comment]
What about this one? [Biqu-BX-bugfix-2.1.x-firmware-w-24319.zip](https://github.com/MarlinFirmware/Marlin/files/8943328/Biqu-BX-bugfix-2.1.x-firmware-w-24319.zip)

It includes the fix from https://github.com/MarlinFirmware/Marlin/pull/24319

**Comment by Antibodyarmy** [comment]
that one is also just stuck on the boot screen, but no on/off loop.

**Comment by thisiskeithb** [comment]
@rhapsodyv must have a special / different board, but knowing it doesn't work for you helps. I thought it may have been my board 🙂

**Comment by Antibodyarmy** [comment]
I know there are several board/screen-board revisions floating around out there, given the pre release boards(with pi issues) and post Kickstarter changes. My printer is from the later USA Kickstarter rounds.  when I get the chance, I'll dissasemble the board cover/remove my screen to update this thread with the revision numbers on the silk screen if there are any.

**Comment by rhapsodyv** [comment]
We probably have boards with different bootloader version.

Mine doesn’t flash properly when I use a sdhc (32gb). I only can flash firmware with a 2gb SD. But Keith can use a sdhc to flash his board.

**Comment by thisiskeithb** [comment]
I was a beta tester and had an earlier revision board & TFT, but I've been working with rhapsodyv & testing with “retail" components.

The hardware I am now testing with are:
- SKR SE-BX 2.0 (Motherboard)
- TFT70-BX V2.2 (TFT)
- TFT70-BX HDMI V2.1 (HDMI Breakout board)

~~There's also some confusion on the proper serial ports since Biqu uses 1 & -1 in [their BX fork](https://github.com/bigtreetech/BIQU-BX/tree/master/Firmware/Marlin-2.0.6-BX), but Luke/looxonline uses 4 & -1 in [his popular fork](https://github.com/looxonline/Marlin/tree/BIQUBX_ALMOST_STOCK) (both Marlin `2.0.6`).~~ See below:

- Serial port 1 is for the TFT
- Serial port -1 is for the micro usb
- Serial port 4 is for the WiFi header

**Comment by Antibodyarmy** [comment]
tft (screen pcb)v2.2, tft-hdmi(the smaller board on stand offs on the tft) v2.1, main printer board v2.0.

**Comment by rhapsodyv** [comment]
I just tested another big SD card (32gb too) and it worked. So, marlin always works for me, except for one sd card, that might indicate a sd problem, not the code.

@Antibodyarmy my hardware is the same. I suspect that we have different bootloaders only.

**Comment by thisiskeithb** [comment]
The features breaking the BX build are `SDSUPPORT` and `TOUCH_SCREEN`. Disable both of those and you'll have a working printer again.

h/t to @rhapsodyv for figuring that out since both of use were using minimal configs & getting different results 🥴

**Comment by thisiskeithb** [comment]
More follow-up: Cherry picking changes from https://github.com/MarlinFirmware/Marlin/pull/24319 fixes `SDSUPPORT` on the BX.

This only leaves the broken `TOUCH_SCREEN` support. I've submitted a PR to disable it in the BX config for now until that can be tracked down: https://github.com/MarlinFirmware/Configurations/pull/757

**Comment by rhapsodyv** [comment]
I think I fixed touch bootloop / freeze (build with sd disabled to test touch)
[firmware.bin.zip](https://github.com/MarlinFirmware/Marlin/files/8953504/firmware.bin.zip)

**Comment by rhapsodyv** [comment]
Fully working with sd, touch and latest bugfix-2.1.
[firmware.bin.zip](https://github.com/MarlinFirmware/Marlin/files/8953568/firmware.bin.zip)

**Comment by thisiskeithb** [comment]
> Fully working with sd, touch and latest bugfix-2.1. [firmware.bin.zip](https://github.com/MarlinFirmware/Marlin/files/8953568/firmware.bin.zip)

Everything works! You're a wizard! 🧙

**Comment by thisiskeithb** [comment]
Closing since there's now a PR open to fix this https://github.com/MarlinFirmware/Marlin/pull/24383

**Comment by Antibodyarmy** [comment]
![IMG_20220624_113721897](https://user-images.githubusercontent.com/78243892/175569920-65ed5ea7-0703-448e-a3c6-139a8e011a70.jpg)

do you guys get a media init fail and no loading of the UI theme after this fix?

**Comment by thisiskeithb** [comment]
> do you guys get a media init fail and no loading of the UI theme after this fix?

The photo above is `TFT_COLOR_UI` which looks correct. You will not see the original / square UI from Biqu/BigTreeTech since that was not ported upstream. If you prefer that theme, then you will need to use Biqu/BigTreeTech's BX firmware.

As for the "Media Init Fail", I do not see that. Try reformatting your microSD card.

**Comment by Antibodyarmy** [comment]
I still get the fail, with several sdcards all reformatted. it will only detect SD cards with the mainboard SD not the screen SD and it cuts in and out with connection on the mainboard

**Comment by thisiskeithb** [comment]
> it will only detect SD cards with the mainboard SD not the screen SD

That is also an expected behavior if you are using the stock BX config from our Configurations repo since it defaults on ONBOARD SD. I would not recommend using the TFT's USB or SD card slots due to possible communication corruption.

> and it cuts in and out with connection on the mainboard

That shouldn't be the case. Are you sure your SD card is fully seated? I started putting my BX back together, so I'll be able to test more this weekend.

**Comment by Antibodyarmy** [comment]
the cards are fully seated. If I enter the SD menu, then back out it appears to lose connection with the SD card. If I either re-insert the card or enter/exit the sd menu a few times it will reconnect to the card after spitting the "Media init fail" error.

**Comment by thisiskeithb** [comment]
> the cards are fully seated. If I enter the SD menu, then back out it appears to lose connection with the SD card. If I either re-insert the card or enter/exit the sd menu a few times it will reconnect to the card after spitting the "Media init fail" error.

I never saw that behavior while testing the BX board & TFT on my desk, but I'll see if I can reproduce it once installed in the printer this weekend.
