### ISSUE TITLE
[BUG] Latest release is not latest

### ISSUE THREAD

**Issue by Temtaime** [MarlinFirmware/Marlin#24365]
### Bug Description

Currently marlin v1 is marked as latest at github releases, while v2.1 should be. This poses problems at least for me  :)

**Comment by thisiskeithb** [comment]
Marlin `1.0.2-3` was tagged & released after `2.1`, which is correct. If the [Releases](https://github.com/MarlinFirmware/Marlin/releases) page is confusing, use the [download page on Marlinfw.org](https://marlinfw.org/meta/download/) instead.

**Comment by Temtaime** [comment]
I was using https://api.github.com/repos/MarlinFirmware/Marlin/releases/latest to get sources from latest release, maybe can you provide some link on the site which points always to latest release ? Currently there're none

**Comment by thisiskeithb** [comment]
> I was using https://api.github.com/repos/MarlinFirmware/Marlin/releases/latest to get sources from latest release

Marlin `1.0.2-3` was tagged & released after `2.1`, which is correct. Until the next version of `2.1.x` is tagged & released, `1.0.2-3` will be the latest release.

> maybe can you provide some link on the site which points always to latest release ? Currently there're none

Use the [download page on Marlinfw.org](https://marlinfw.org/meta/download/) instead.
