### ISSUE TITLE
[BUG] Marlin 2.1 Printer Reboots with SD Card Inserted

### ISSUE THREAD

**Issue by mrnrod45** [MarlinFirmware/Marlin#24374]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When powering on printer with SD card inserted the Printer boot loops until the SD card is removed then it boots successfully.

### Bug Timeline

06/09/2022

### Expected behavior

Expected to boot properly without need to remove SD card

### Actual behavior

Have to Remove SD card for boot to be successfull 

### Steps to Reproduce

Compile Marlin 2.1 using Neptune 2 Configs
Install Marlin
Printer starts to boot loop after install
remove SD card
Printer boots successfully 

### Version of Marlin Firmware

Marlin 2.1

### Printer model

Elegoo Neptune 2

### Electronics

Stock Board

### Add-ons

BL-Touch, 

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[MarlinConfigs.zip](https://github.com/MarlinFirmware/Marlin/files/8936800/MarlinConfigs.zip)

**Comment by thisiskeithb** [comment]
This is being worked on https://github.com/MarlinFirmware/Marlin/pull/24319
