### ISSUE TITLE
[BUG] Allen Key probe can't be used to Home Z

### ISSUE THREAD

**Issue by radry** [MarlinFirmware/Marlin#24370]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When using allen key probe type on a cartesian printer it can not be used as a Z_Min endstop and thus not be used to home Z.

This probe type is currently the only one useable in Marlin for dockable microswitch probes like klicky probe, quickdraw probe or euclid probe.

When configuring allen key probe in Marlin there are two issues: 
First is the sanity check which claims this probe can't be used with Z_Min endstop. This can easily be commented out to compile the Firmware.
Second problem is when you try to home: It will refuse to Home Z and gives and "unhomed" error and claim it's necessary to Home Z first instead of deploying the probe and homing Z.

### Expected behavior

When using G28 it should home X, Y, then deploy the probe and home Z.

### Actual behavior

After homing X, Y the printer will halt and claim it's necessary to Home Z instead of deploying the probe to do so.

### Steps to Reproduce

1) Configure to use Allen Key probe and set up a valid deploy and stow routine
2) enable Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
3) Comment out the sanity check that prevents allen key probe to be used with Z_Min endstop
4) Do G28

### Version of Marlin Firmware

2.1

### Printer model

custom corexy

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/8935138/Marlin.zip)

Related issues:
#24003 
#22794

**Comment by radry** [comment]
As a temporary solution I was able to get it running by changing _probe.cpp_ 

Line 424 and Line 459 from:
` #if EITHER(Z_PROBE_SLED, Z_PROBE_ALLEN_KEY)`

to
` #if (Z_PROBE_SLED)`

Now the probe correctly deploys and stows before/after homing Z. 
Maybe additional safety checks are needed to ensure safe operation.

**Comment by thisiskeithb** [comment]
https://github.com/MarlinFirmware/Marlin/pull/24420 has been merged.
