### ISSUE TITLE
[FR] (BUZZER sound on preheating finished)

### ISSUE THREAD

**Issue by AaryanL** [MarlinFirmware/Marlin#24379]
### Describe the feature you want

Please add a sound notification with the LCD control panel buzzer on bed and hotend reach their desired preheating temp.
It's need when heating is slow and requires some time to wait.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/21841

**Comment by thisiskeithb** [comment]
Also, this should/can be done via your slicer.

**Comment by AaryanL** [comment]
I use manual preheating of bed only, so I can't use slicer.
