### ISSUE TITLE
[BUG] Problem with pause to change filament.

### ISSUE THREAD

**Issue by lipewww** [MarlinFirmware/Marlin#24382]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I decided to try a Cura feature, where I can pause my print at some layer level, I'm using the "Pause at Height" function, and when I pause, it stops for 5 seconds, and returns the print, without me being able to control when it will be yours return.

I tested another function present in Cura which is the "Change Filament", but the same thing happens. I tested several pause modes that are available in Cura besides Marlin and nothing.

**Could it be a firmware issue?**

### Expected behavior

I was expecting the printer to pause printing, and waiting for me to decide whether or not to continue by clicking the LCD button to continue.

### Actual behavior

It pauses, pauses for 5 seconds, and returns to printing by itself.

### Version of Marlin Firmware

2.1 bugfix

### Printer model

Anet A6

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Host Software

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads
HERE IS A VIDEO OF THE PROBLEM.
https://imgur.com/a/CxZB9ql

I don't know why, but maybe there might be some chance it works using only the SD Card. Now I'm printing using USB, because the firmware is having an SD not working issue.

[config marlin 2.1 bugfix.zip](https://github.com/MarlinFirmware/Marlin/files/8951528/config.marlin.2.1.bugfix.zip)

**Comment by thisiskeithb** [comment]
You need to enable `ADVANCED_PAUSE_FEATURE`.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
