### ISSUE TITLE
[BUG] (Help about Marlin 1.1.9)

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#24413]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Hello friends
Currently I need to know some more information about 1.1.9 code about migrating these files to 2.x code version.
Files
enum.h
Marlin.h
Marlin_main.cpp
MarlinConfig.h
Where will it be in the Marlin 2x version because I'm trying to edit my project from marlin 1x to marlin 2x to program with STM32F103RCT6
Please tell me if Marlin 1x version can I edit to STM32 without using Marlin 2x version

### Version of Marlin Firmware

1.1.9

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[New folder.zip](https://github.com/MarlinFirmware/Marlin/files/8987764/New.folder.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
