### ISSUE TITLE
Bug MKS TINYBEE Layer Shift TMC2209 x4 StandAlone Kossel Linear Plus

### ISSUE THREAD

**Issue by flishy2532** [MarlinFirmware/Marlin#24412]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

MKS TINYBEE Kossel Linear Plus TMC2209 x4 Marlin 2.1.x fixbug Layer Shift 

LayerShift 75% Print On Cura Nozzle head is not go to same position 

Printer : Anycubic Kossel Linear Plus (Delta)
MotherBoard : MKS TINYBEE (ESP32 WIFI Support)
Driver : TMC2209 x4 (use TMC2209 standalone in config)
LCD : MKS mini v3.0 (RBG)

https://youtu.be/odYO6YuWUuE

### Bug Timeline

new bug

### Expected behavior

MKS TINYBEE Kossel Linear Plus TMC2209 x4 Marlin 2.1.x fixbug Layer Shift 

LayerShift 75% Print On Cura Nozzle head is not go to same position 

Printer : Anycubic Kossel Linear Plus (Delta)
MotherBoard : MKS TINYBEE (ESP32 WIFI Support)
Driver : TMC2209 x4 (use TMC2209 standalone in config)
LCD : MKS mini v3.0 (RBG)

https://youtu.be/odYO6YuWUuE

### Actual behavior

MKS TINYBEE Kossel Linear Plus TMC2209 x4 Marlin 2.1.x fixbug Layer Shift 

LayerShift 75% Print On Cura Nozzle head is not go to same position 

Printer : Anycubic Kossel Linear Plus (Delta)
MotherBoard : MKS TINYBEE (ESP32 WIFI Support)
Driver : TMC2209 x4 (use TMC2209 standalone in config)
LCD : MKS mini v3.0 (RBG)

https://youtu.be/odYO6YuWUuE

### Steps to Reproduce

MKS TINYBEE Kossel Linear Plus TMC2209 x4 Marlin 2.1.x fixbug Layer Shift 

LayerShift 75% Print On Cura Nozzle head is not go to same position 

Printer : Anycubic Kossel Linear Plus (Delta)
MotherBoard : MKS TINYBEE (ESP32 WIFI Support)
Driver : TMC2209 x4 (use TMC2209 standalone in config)
LCD : MKS mini v3.0 (RBG)

https://youtu.be/odYO6YuWUuE

### Version of Marlin Firmware

bugfix 2.1.x

### Printer model

Kossel Delta

### Electronics

MKS TINYBEE TMC2209 x4

### Add-ons

TMC2209 Standalone MKS TINYBEE (ESP32 WIFI)

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8987420/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/8987421/Configuration_adv.zip)

![ae_1656173720340](https://user-images.githubusercontent.com/61683774/175832518-a6c925e6-4b93-42db-893c-1d50db87619a.jpg)

![20220625_222018](https://user-images.githubusercontent.com/61683774/175832528-7e0eab03-cc3a-4f49-9d88-73df742fc8e6.jpg)

![20220625_001743](https://user-images.githubusercontent.com/61683774/175832532-88d44f6d-2447-4581-a426-6df6f240fcf5.jpg)

**Comment by thisiskeithb** [comment]
Since you’re using TMC drivers in standalone mode, did you properly set the driver current using the potentiometer on the driver itself?

**Comment by flishy2532** [comment]
am set with multi meter stepper motor is not hot but when am print on 75% cura layer is shift i think some code is bug

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by thisiskeithb** [comment]
> am set with multi meter stepper motor is not hot but when am print on 75% cura layer is shift i think some code is bug

Try increasing your driver current.

**Comment by flishy2532** [comment]
Try increasing your driver current. am increasing but it cant help it layer shift any one can help am try turn on and off all config
alway layer shift

**Comment by thisiskeithb** [comment]
> am increasing but it cant help it layer shift 

If your driver current is too low, it can also cause layer shifts.

Also check the grub screens on your motor pulleys and ensure those haven’t come loose.

**Comment by flishy2532** [comment]
> > am increasing but it cant help it layer shift 
> 
> If your driver current is too low, it can also cause layer shifts.
> 
> Also check the grub screens on your motor pulleys and ensure those haven’t come loose.

am check all motor pullyes it work 100% 
when am print 1 hours around 70% cura it always layer shift look this my print frist start it good when go half it shift 😭

1.

![20220627_134049.jpg](https://user-images.githubusercontent.com/61683774/175875759-2a6e15d8-4258-4d18-b3a1-bb7a6b2a1bb8.jpg)

2.

![20220627_134130.jpg](https://user-images.githubusercontent.com/61683774/175875925-cbcb45b2-3679-48c9-91b7-eebbc1e66581.jpg)

**Comment by flishy2532** [comment]
Any one can help fix?

**Comment by flishy2532** [comment]
am never give up fix this board i think have bug layershift
am test all function turn on and off 
2 month ago  it not fix 🥺😭🐬

![20220627_135740.jpg](https://user-images.githubusercontent.com/61683774/175878841-dbaf1a5a-140a-4387-bbe3-66244d028c83.jpg)

am lost many filament on this board no care only want fix it 👨‍🔧 


![20220627_140232.jpg](https://user-images.githubusercontent.com/61683774/175879174-3db06717-ff8e-4fb8-9101-b87f3d8af717.jpg)


any one can help ?🤔🥰 👨‍🔧

**Comment by Symon82** [comment]
Try to disable PRINTCOUNTER (in Configuration.h) and avoid writing anything into EEPROM (do not "Store Settings" or use M500) while printing.

**Comment by flishy2532** [comment]
> Try to disable PRINTCOUNTER (in Configuration.h) and avoid writing anything into EEPROM (do not "Store Settings" or use M500) while printing.

let me test

**Comment by Fbn-lab** [comment]
You need to cool the TMC sufficiently
Note: The wrong version of the program will cause wifi to fail to upload files
I think this can help you
[MKS TinyBee V1.0 User Manual.pdf](https://github.com/MarlinFirmware/Marlin/files/8993525/MKS.TinyBee.V1.0.User.Manual.pdf)
.

**Comment by flishy2532** [comment]
> You need to cool the TMC sufficiently Note: The wrong version of the program will cause wifi to fail to upload files I think this can help you [MKS TinyBee V1.0 User Manual.pdf](https://github.com/MarlinFirmware/Marlin/files/8993525/MKS.TinyBee.V1.0.User.Manual.pdf) .

thank for help but this old version  am up grade to 2.1.x bugfix now got fix no layer shift am disable //#define PRINTCOUNTER in config.h am share my firmware soon

**Comment by nikybiasion** [comment]
I have the same issue wih tinybee and tmc2209, i set vref to 1.25/1.26 for all drivers and put a cooler fan over them, now no more layer shift

**Comment by flishy2532** [comment]
layer shift because enable #print counter

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by flishy2532** [comment]
did you enable #define printcounter in config?

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________
