### ISSUE TITLE
[BUG] Typo; Z probe wizard shows 'Move X: on display"

### ISSUE THREAD

**Issue by ImagineerNL** [MarlinFirmware/Marlin#24418]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Tested on Ender 3 with SKR e3 Mini V2; not sure if this exists on other printers.

steps to reproduce:
- configuration -- advanced settings - probe offsets - Z probe wizard

After its homing procedure, the wizard tells to "move X" where it should say "Move Z".
Turning the knob does make Z move, so i guess its just a typo

### Bug Timeline

unknown. first time running wizard is today

### Expected behavior

text in window to be: Move Z

### Actual behavior

Move X

### Steps to Reproduce

steps to reproduce:
- configuration -- advanced settings - probe offsets - Z probe wizard

After its homing procedure, the wizard tells to "move X" where it should say "Move Z".
Turning the knob does make Z move, so i guess its just a typo

### Version of Marlin Firmware

2.1.x builddate 27-06-2022

### Printer model

Creality Ender 3

### Electronics

SKR E3 Mini V2

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/24396

**Comment by thisiskeithb** [comment]
~~This was fixed in https://github.com/MarlinFirmware/Marlin/pull/24404~~

**Comment by thisiskeithb** [comment]
This has not been fixed.

**Comment by thisiskeithb** [comment]
Closing since there’s now a PR open to revert related changes: https://github.com/MarlinFirmware/Marlin/pull/24518
