### ISSUE TITLE
G29 using Inductive Proximity sensor without applying Z-Prob-offset

### ISSUE THREAD

**Issue by g2david** [MarlinFirmware/Marlin#2442]
Hi 

I am using Inductive Proximity sensor as min end-stop and auto-leveling probe. G28 can correctly detect the Z0. After G29 9 points calibration, I find out it will be Z+0.7, 0.7 is my offset in the firmware. I have to G92 and move 0.7 up after G29. When I search in the sourcecode, I can see Z-probe offset has not applied to Z-axis.. 

Is this for some reasons?

Cheers,
David

**Comment by AnHardt** [comment]
This is fixed in the `RC` and `RCBugFix` branch.
