### ISSUE TITLE
[BUG] Refactor of Individual Axis Homing to use MENU_MAP has causes X to always get homed (cause is small typo).

### ISSUE THREAD

**Issue by credomane** [MarlinFirmware/Marlin#24423]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Enabling the "INDIVIDUAL_AXIS_HOMING_MENU" works but homing any of the individual axes will *always* home X too.
Current 2.1.x-bugfix is the branch I discovered the bug on.

Fixing it is as simple as removing single erroneous character from this line: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/lcd/menu/menu_motion.cpp#L284

Changing the `G28X` to just `G28` completely fixes the issue and all individual axis home works as expected.

### Bug Timeline

New bug. 8 days ago according to the github commit log. https://github.com/MarlinFirmware/Marlin/commit/4520a51bbecf9874dce563cf6cf2d2bdb649a917

### Expected behavior

"Home X" to home X.
"Home Y" to home Y.
"Home Z" to home Z.

### Actual behavior

Home X does Home X.
Home Y homes X and Y together. Because QUICK_HOME is defined without it is does X then Y.
Home Z homes X then homes Z.

### Steps to Reproduce

1. Compile Marlin 2.1.x-bugfix with `#define INDIVIDUAL_AXIS_HOMING_MENU`
2. Install firmware to printer.
3. Try to individual home an axis besides X.

### Version of Marlin Firmware

2.1.x-bugfix

### Printer model

CR-10 S5

### Electronics

Stock Creality V2.1

### Your Slicer

Not a slicer issue.

### Host Software

Not a host software issue.

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Zip not uploaded because the problem is easily seen in the source code even though the compile time INDIVIDUAL_AXIS_HOMING_MENU does allow the issue to appear at run time.

**Comment by thisiskeithb** [comment]
Thanks for the heads up! I submitted PR https://github.com/MarlinFirmware/Marlin/pull/24425 to address this.
