### ISSUE TITLE
[BUG] CoreXY limiting X or Y speed results in limited motor speed

### ISSUE THREAD

**Issue by GHubensG** [MarlinFirmware/Marlin#24437]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I made a CoreXY laser engraving machine with the intention to have quick X axis movement.
but when I limit the acceleration or the speed in marlin for the Y axis it limits the acceleration or speed for the motor...
this means the whole system is limited by that motor because the motors need to move together.

### Bug Timeline

01/07/2022

### Expected behavior

when i limit the Y-axis in marlin i expect it to limit the Y-axis and not the motor that controls a diagonal movement (CoreXY)

### Actual behavior

when i limit the speed of the Y-axis it limits the speed of a motor

### Steps to Reproduce

1. build an coreXY machine
2. limit the speed or acceleration with M203 M201
3. see how it moves

### Version of Marlin Firmware

2.1

### Printer model

DIY

### Electronics

SKR E3 DIP V1.1

### Add-ons

NEJE lasermodule

### Bed Leveling

No Bed Leveling

### Your Slicer

Other (explain below)

### Host Software

Other (explain below)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

i control the machine with CNCjs software
i attached a video of the problem, the frequency of the motors is also hearable

Steppers: Nema23HS32-4004S
Driver: TB6600 (with cooling)
Area = 1200mmx800mm

https://user-images.githubusercontent.com/74602039/176893843-4f151e13-74f9-496d-8108-0b8901324fe1.mp4

[](url
[Marlin-2.1 E3 SKR Laser.zip](https://github.com/MarlinFirmware/Marlin/files/9028764/Marlin-2.1.E3.SKR.Laser.zip)
)

**Comment by userosos** [comment]
Looks like bad endstops or bad stepper connectors.
