### ISSUE TITLE
[BUG] Controller fan percentage not working as it should

### ISSUE THREAD

**Issue by Conti93** [MarlinFirmware/Marlin#24441]
### Did you test the latest `bugfix-2.1.x` code?

Yes*, and the problem still exists.
*Tested `bugfix-2.0.x`, couldn't get `bugfix-2.1.x` to compile with the i3 Pro B config file.

### Bug Description

I've got a slightly modified i3 Pro B with a GT2560 board, where I moved the obnoxiously loud controller fan to a PWM pin (7, which drives a MOSFET), then I uncommented "#define USE_CONTROLLER_FAN" under Configuration_adv and set "#define CONTROLLERFAN_SPEED_ACTIVE 196", however the fan is spinning at 100% power.
So I uncommented "#define CONTROLLER_FAN_EDITABLE" and found that setting the controller fan from 50% to 99% in the menu keeps the fan at full blast, while 1-49% works as it should be like from 1 to 100%. In other words if I set the fan at 25% it will function at half the power. Fun fact, setting the fan to 100% in the menu the fan goes to like 1% power, it almost stops.

### Bug Timeline

Don't know, updated yesterday from 2.0.4 where it was working (except the idle function)

### Expected behavior

The percentage set on the display menu/config file should match the actual fan speed

### Actual behavior

From 1% to 49% the fan goes from 1% to 100% in terms of speed. Setting 50% to 99% the fan stays at 100%, and setting 100% makes the fan almost stop.

### Steps to Reproduce

1. Enable controller fan on PWM pin 7 and CONTROLLER_FAN_EDITABLE in Configuration_adv.h
2. Try modifying the percentage and check the fan RPM between 50 to 100%

please see attached configuration files.

### Version of Marlin Firmware

2.0.9.4

### Printer model

GEEEtech Prusa i3 Pro B

### Electronics

GT2560

### Add-ons

DIY mosfet board to drive extrusor cooling fan (on pin 11) and part cooling fan (on pin 12, with FAN_SOFT_PWM enabled)

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration i3 Pro B.zip](https://github.com/MarlinFirmware/Marlin/files/9033181/Configuration.i3.Pro.B.zip)
![i3](https://user-images.githubusercontent.com/58734181/177006095-7e5d5cff-55a0-4ff3-ae8f-52598a8840cd.jpg)

**Comment by eduard-sukharev** [comment]
You have following in your config:
```cpp
// Use software PWM to drive the fan, as for the heaters. This uses a very low frequency
// which is not as annoying as with the hardware PWM. On the other hand, if this frequency
// is too low, you should also increment SOFT_PWM_SCALE.
#define FAN_SOFT_PWM

// Incrementing this by 1 will double the software PWM frequency,
// affecting heaters, and the fan if FAN_SOFT_PWM is enabled.
// However, control resolution will be halved for each increment;
// at zero value, there are 128 effective control positions.
// :[0,1,2,3,4,5,6,7]
#define SOFT_PWM_SCALE 2
```
Which looks like `SOFT_PWM_SCALE` should have halved your control resolution at least 3 times (once for 0, 1 and 2), which gives `((256/2)/2)/2=32` available PWM levels. Which does not explain the behavior you experience, but might be a clue on where to dig further.
