### ISSUE TITLE
[BUG] Homing failed

### ISSUE THREAD

**Issue by DandeMC** [MarlinFirmware/Marlin#24456]
### Did you test the latest `bugfix-2.1.x` code?

YES. No change

### Bug Description

After a new flash to my SKR 1.3 all axes doesn't move. Homing failed too. I tested severel config settings. No change.

### Version of Marlin Firmware

2.1

### Printer model

Ender 3 pro

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/9053070/Marlin.zip)

**Comment by DandeMC** [comment]
No one any idea? I use a SKR 1.3 with TMC2130

**Comment by DandeMC** [comment]
My motors only works when I activate TMC_USE_SW_SPI. But it collides in my printer and don't stop.

**Comment by ellensp** [comment]
these are Configuration issues. Not bugs

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
