### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by l0v3byte** [MarlinFirmware/Marlin#24453]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Hi,
I try to compile Marlin on Platformio in my native language but I receive this error " Marlin/src/HAL/STM32/../../inc/../core/../lcd/language/language_it.h:367:64: error: expected ',' or ';' before 'STR_U' " i try in another language but the error change in other error in different place example in English the problem change in this " Marlin/src/lcd/marlinui.cpp:796:60: error: 'manual_feedrate_mm_s' was not declared in this scope; did you mean 'feedrate_mm_s' ".
This error appears in configuration on SKR mini E3 V3 on my Ender 3 but changing into another board like Creality V4.2.7 this type of problem not exists

### Bug Timeline

15 May 2022

### Version of Marlin Firmware

Marlin 2.9.3

### Printer model

Creality Ender 3 Pro

### Electronics

Board Big Tree Tech SKR mini E3 V3

### Add-ons

Only part change is bi-metal heatbrake the rest is stock

### Bed Leveling

No Bed Leveling

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
> error: 'manual_feedrate_mm_s' was not declared in this scope; did you mean 'feedrate_mm_s' 

Your config does not match the version of Marlin you’re compiling with.

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
