### ISSUE TITLE
[BUG] Marlin skips line of Gcode at end of file

### ISSUE THREAD

**Issue by gittigittibangbang** [MarlinFirmware/Marlin#24467]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

3D printer converted to 2D pen plotter. The base machine is an Anycubic Mega X, whose mainboard is an Arduino 2560 variant. Gcode files are produced via an Inkscape plugin. Most files work without a problem, however two (until now) have an issue where, in the last movement block, a line of Gcode is skipped. I tried swapping the SD card, reducing the decimal places from 6 to 4 (minimum possible with the Gcode plugin of Inkscape), reducing speed and copying the line. The latter somewhat works, but when using it in the second concerned file, the subsequent G01 Z-1.000000 F100.0(Penetrate) command is then skipped. Nothing special is indicated by Pronterface apart from the usual echo: busy: printing output. Below is a check of the Gcode via Camotics and a picture of the actual output from the first file. The issue is repeatable every time.

![image](https://user-images.githubusercontent.com/108936583/177992994-4422580c-26af-4cdd-a3c2-92f59453feb8.png)
![image](https://user-images.githubusercontent.com/108936583/177993016-2c1c4134-add4-4ad8-ad73-39dffc57f9a2.png)

Relevant section of Gcode from first file:

```
G00 Z5.000000
G00 X89.007534 Y242.687269 **(TOP MIDDLE POINT)**
G01 Z-1.000000 F100.0(Penetrate)
G01 X149.825060 Y191.873298 Z-1.000000 F1000.000000
G01 X120.291751 Y118.330014 Z-1.000000
G01 X41.221635 Y123.691733 Z-1.000000 **(MISSING POINT, SKIPPED LINE)**
G01 X21.886928 Y200.548745 Z-1.000000
G01 X89.007534 Y242.687269 Z-1.000000
G00 Z5.000000
(End cutting path id: path754929)
G0 Z20
G28 X0 Y0

M18
```

Second file:
```
G00 Z5.000000
G00 X16.194742 Y32.678680 **(SKIPPED LINE)**

G01 Z-1.000000 F100.0(Penetrate)
G01 X180.455690 Y32.678680 Z-1.000000 F1000.000000
G00 Z5.000000
```

### Bug Timeline

Suspected new bug

### Version of Marlin Firmware

2.0.x

### Printer model

Anycubic Mega X

### Electronics

Stock

### Add-ons

2D pen plotter adaptation

### Your Slicer

Other (explain below)

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[gcode tests.zip](https://github.com/MarlinFirmware/Marlin/files/9072097/gcode.tests.zip)

**Comment by thisiskeithb** [comment]
Your configs are very out of date and not from this project. They appear to be from https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S, so you will need to file a bug report in that repo.
