### ISSUE TITLE
Change Filament or pause height

### ISSUE THREAD

**Issue by DocMarvel** [MarlinFirmware/Marlin#24478]
### Is your feature request related to a problem? Please describe.

When printing on anycubic vyper, and needing a pause at layer or filament change code in Cura, the firmware pauses but does not give and option to resume the print. It doesnt bring up a notification. It pauses, homes, and stays. then it doesn't allow you to resume.

### Describe the feature you want

A feature that allows the use of post codes in cura to work.

**Comment by oliver-eifler** [comment]
It's not marlin releated. the stock touch display can't handle the messages for notifications/dialogs

**Comment by thisiskeithb** [comment]
Support for Anycubic's Vyper motherboard & TFT have not been added in this repo, so you'll need to make the request directly in the Vyper fork: https://github.com/ANYCUBIC-3D/Vyper/
