### ISSUE TITLE
revert 

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#2447]
commit  
SHA:    c90e80d1a379bfad99a618fef1dd2540d3927713
Author: mkile mkiles81@gmail.com
Date:   Tue Jul 14 2015 11:49:35 GMT+0300 (MSK)
Subject:    Slightly updated translation

It contains many errors.
please rollback and if possible to assign the vote to future language file.

discussion for Russian developers (link please in header of language_ru.h ) :
 http://roboforum.ru/forum107/topic15619.html

**Comment by Wackerbarth** [comment]
@mkile , @setar -- Although I neither authored the change, nor committed it, I hope that you (and any other speakers of Russian) can reach a consensus as to the appropriate translations.

@setar -- Please propose a Pull Request with the translations that you prefer.

**Comment by ghost** [comment]
ок
We made the Pull request after discussion
sorry for the fuss  :)
