### ISSUE TITLE
[BUG] Compile Error Crealtiy Ender 3V2 with BLTouch

### ISSUE THREAD

**Issue by gorillale** [MarlinFirmware/Marlin#24497]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I think i will be a last try:
 I will be compile new 2.1 Version with VSC (include Config 2.1.0.1)
Now i have aktivated BLTouch:
Result: In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1976:6: error: #error "LCD_BED_LEVELING is not supported by the selected LCD controller."        
 1976 |     #error "LCD_BED_LEVELING is not supported by the selected LCD controller."
      |      ^~~~~

I cant find what is to do. The LCD ist Creality aktivated
Both not work:
#define DWIN_CREALITY_LCD             // Creality UI
//#define DWIN_LCD_PROUI              // Pro UI by MRiscoC
or 
//#define DWIN_CREALITY_LCD             // Creality UI
#define DWIN_LCD_PROUI              // Pro UI by MRiscoC

Is BLTouch no more useable? With 2.9.0.2 it works?

On platformio.ini
i have aktivated STM32F103RE_creality before STM32F103RET6_creality

### Bug Timeline

14.7.2022

### Version of Marlin Firmware

2.1

### Printer model

Ender 3 V2 4.2.2 Board

### Electronics

bl touch creality

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Slic3r

### Host Software

Repetier Host

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/9109589/Marlin.zip)

**Comment by thisiskeithb** [comment]
> #error "LCD_BED_LEVELING is not supported by the selected LCD controller.

Disable `LCD_BED_LEVELING` because it’s not supported by your LCD controller.

**Comment by gorillale** [comment]
im wondering.... on 2.0.9.2 it works ?
Why you disable this on 2.1?

**Comment by thisiskeithb** [comment]
You need to enable `DWIN_MARLINUI_PORTRAIT` or `DWIN_MARLINUI_LANDSCAPE` to use `LCD_BED_LEVELING`.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by gorillale** [comment]
Sorry not understand why i sould use Marli-UI when this is working befor with creality.

**Comment by ellensp** [comment]
you are mistaken
Creality UI has bed leveling with AUTO_BED_LEVELING_BILINEAR or  AUTO_BED_LEVELING_LINEAR, or AUTO_BED_LEVELING_3POINT

 this not LCD_BED_LEVELING

**Comment by gorillale** [comment]
Thanks for the help, but I'm still surprised that it worked with 2.0.9.2 and I got all 9 points displayed on a score screen. And now it suddenly doesn't work anymore, too bad. This is a really useful feature and helps with leveling. I will try again.
