### ISSUE TITLE
[BUG] Graphical LCD Artifacts in Marlin 2.1

### ISSUE THREAD

**Issue by AlexValCar** [MarlinFirmware/Marlin#24496]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Graphical LCD Artifacts are displayed on the screen with Ender 3 Max Creality 4.2.2 board within minutes of turning on the machine with firmware 2.1 and start to manual mesh level

### Bug Timeline

new bug, fine with Marlin 2.0.x stock firmware

### Expected behavior

I expected that Graphical LCD Artifacts would not be displayed

### Actual behavior

Graphical LCD Artifacts were displayed minutes after turning on the machine and entering menus

### Steps to Reproduce

1. turn on the printer
2. heat the bed to 70 degrees
3. enter the manual bed leveling option
4. start to manual level the bed and at the 5th leveling point of 16 the screen starts showing garbage graphics

### Version of Marlin Firmware

2.1

### Printer model

Ender 3 Max

### Electronics

Stock 4.2.2 board

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.h and Configuration_adv.h.zip](https://github.com/MarlinFirmware/Marlin/files/9108471/Configuration.h.and.Configuration_adv.h.zip)
![20220713_012045](https://user-images.githubusercontent.com/69334069/178901198-cb95efd2-c3c1-4b28-adae-a3fce5b1e0ce.jpg)

**Comment by hcet14** [comment]
Have you had a look here ['https://marlinfw.org/docs/basics/troubleshooting.html'](https://marlinfw.org/docs/basics/troubleshooting.html)?

**Comment by AlexValCar** [comment]
Yes, unfortunately it is not updated and the parameters it shows are no longer in the firmware and that is exactly where I got the title of the issue

**Comment by AlexValCar** [comment]
> Have you had a look here ['https://marlinfw.org/docs/basics/troubleshooting.html'](https://marlinfw.org/docs/basics/troubleshooting.html)?

yes, unfortunately it is not updated and the parameters it shows are no longer in the firmware and that is exactly where I got the title of the issue, but thank you very much for your response!

**Comment by thisiskeithb** [comment]
> yes, unfortunately it is not updated and the parameters it shows are no longer in the firmware

From https://marlinfw.org/docs/basics/troubleshooting.html:

> Solution: Define custom delays. **Add the following lines to `Configuration.h` as your starting-point and adjust values upward until the display works reliably.** You should keep testing to find the lowest values that produce a reliable display because the LCD update steals time from the main loop.
> 
> `#define ST7920_DELAY_1 DELAY_NS(200)` // After CLK LOW
> `#define ST7920_DELAY_2 DELAY_NS(400)` // After DAT
> `#define ST7920_DELAY_3 DELAY_NS(200)` // After CLK HIGH

You need to add these values to your config and adjust them.
