### ISSUE TITLE
keeps homing repeatedly

### ISSUE THREAD

**Issue by coalman321** [MarlinFirmware/Marlin#2450]
I have a Printrbot and replaced the board. I am currently setting it up to run with a RAMPS 1.4. As I was setting up the end-stops and testing them it began to go to "home" and try to keep going even though it was hitting the button repeatedly. I had checked to see if the end-stop was hooked up correctly. It was and it was properly inverted. For some reason it seems to ignore the stop.

It also will not move the motors when told. I don't know if this is related.

I have never personally worked with Marlin and reconfiguring it before, so any help would be appreciated.

**Comment by thinkyhead** [comment]
Please post your configuration, and the results of your testing with `M119`.

**Comment by coalman321** [comment]
how?

**Comment by thinkyhead** [comment]
You can paste your configuration here (prefaced and followed by three backtick ` characters), or post it as a [Gist](https://gist.github.com/), then post the link here, or use [Pastebin](http://pastebin.com/) and post the link here.

**Comment by coalman321** [comment]
this should work
https://gist.github.com/coalman321/18d29b55fb80756566e0
i however cannot access the printer now...
have to wait for tomorrow

**Comment by thinkyhead** [comment]
Try uncommenting this line:

```
//#define DISABLE_MAX_ENDSTOPS
```

**Comment by coalman321** [comment]
ok but i dont' have max endstops..

**Comment by thinkyhead** [comment]
Yes, that's the point. Marlin doesn't know that until you tell it, by enabling that option.

**Comment by coalman321** [comment]
oh ok i get it now
i must have forgot it when i changed to a new fresh version.
i had a version i had changed several months ago
any idea about the motor not working when i tell it to move?

**Comment by thinkyhead** [comment]
I looked at the Printrbot Marlin fork and its default `Configuration.h` still has that line commented. That might be okay for Marlin 1.0.0, but going forward it's definitely not going to work.

**Comment by coalman321** [comment]
im running 1.0.2 so thats probably why

**Comment by thinkyhead** [comment]
@coalman321 Just in case there are other important changes, you should do a comparison of your `Configuration.h` and `Configuration_adv.h` to those included in Release 1.0.2. There might be one or two other important tweaks made since 1.0.0, or whichever version the Printrbot is basing its distribution firmware on.

**Comment by coalman321** [comment]
i just tried it
it is still doing the same thing it was before..
hitting the switch and ignoring it
the motors are also no t responding still

**Comment by AnHardt** [comment]
Use M119 and see if you can trigger the endstops manually.

**Comment by coalman321** [comment]
when i hit home?
or do i actually press it myself
because i have tried that

**Comment by coalman321** [comment]
Note: i tried to run the motors with the printrbot configs in the motion settings and it locks the motors

**Comment by coalman321** [comment]
here is my current configuration.h
https://gist.github.com/7504835fb5a92cbf7ad4.git

??? https://gist.github.com/coalman321/7504835fb5a92cbf7ad4

**Comment by AnHardt** [comment]
@coalman321 
Switch off the printer.
Move the extruder to a place where no enstops should be triggered.
Turn on the printer.
Connect a host program.
Send M119
Trigger an endswitch. (with a finger or screwdriver)
Send M119 during triggered.
Release the endswitch.
Send M119.
Trigger the next endswitch.
Send M119.
...
until you tested all endstops.

Compare if the outputs of M119 is what you'd expect.
M119 should only report endstops you actually have on the printer. If it reports more - deactivate them in the Configuration.h. Or at least play with the pullups and inverting until they are not triggered.

**Comment by coalman321** [comment]
ok
can you do it thru the arduino serial terminal

**Comment by coalman321** [comment]
nevermind
i found the log in my host and have been using the command
when i run it it tells me that all of the mins are open even if they are contacted and all of the maxes are triggered

**Comment by AnHardt** [comment]
https://gist.github.com/7504835fb5a92cbf7ad4.git
Uh - no Configuration is really bad. :-)

**Comment by coalman321** [comment]
ok i changed to default configs and got to where i was last
i realized that i may not have had a pullup resistor in the stop so i added one
all of the endstops now read open
but the min stops are being ignored even when triggered

also any idea what this means?

```
printer stopped due to errors. Fix the error and use M999 to restart.(Temperature is reset. Set it after restarting.)
```

**Comment by thinkyhead** [comment]
That last configuration still doesn't define `DISABLE_MAX_ENDSTOPS`. Uncomment that so that the machine isn't reading the non-existent endstops.

**Comment by coalman321** [comment]
oops my bad
i just added the pullup to the x axis and am testing now

**Comment by coalman321** [comment]
any idea about the error though?

**Comment by AnHardt** [comment]
Your log is very short. But i guess you got a MINTEMP error. Set up your #define TEMP_SENSOR_0 (#2452)
**_EDIT:**_ Or better - don't define sensors when no thermistors are connected.
**_EDIT2:**_ Or use 999 or 998 for them during the **_tests**_.

**Comment by coalman321** [comment]
it is not currently hooked up for the fact i am working on it. can i make it a dummy for now?

**Comment by AnHardt** [comment]
Yes you can. But don't forget to to change again to a real sensor when you try to heat anything.

**Comment by coalman321** [comment]
ok well i set it to zero and i have got the x and y axis to move according to the host and am fixing the z axis now

**Comment by coalman321** [comment]
all axis are now responding properly
thank you for all of your help
i will keep the thread open for a while longer in case i run into other problems

**Comment by coalman321** [comment]
where is the size function located because the printer stops well be fore it hits its mechanical limits?

**Comment by coalman321** [comment]
never mind i found it

**Comment by coalman321** [comment]
quick question, is there a way to set the voltage for a hotend slot to –say– 12 volts and hover around there?

**Comment by thinkyhead** [comment]
@coalman321 The voltage will be fixed, dependent on what your board and your PSU can handle, but the current is controlled by PWM, which you probably know always has a 12V potential, but in high-frequency pulses via MOSFETs. You can set the voltage to stay on, with no PWM (and in fact this will happen automatically when you need to send the full current), but most of the time you want PWM.

**Comment by AnHardt** [comment]
@coalman321 
If you integrate a PWM over time, 100% means full voltage, 0% means 0 volt.
