### ISSUE TITLE
[BUG] Marlin Firmware doesnt compile with MightyBoard REV.E on Wanhao Duplicator 4S using Windows7 OS.

### ISSUE THREAD

**Issue by Bubleek** [MarlinFirmware/Marlin#24523]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When im try to start compile Marlin and i have to use config files for Wanhao Duplicator 4S with MightyBoard REV.E on ATMega 1280 then it didnt compile yet untill finish. Im do compilation process in Windows7 OS with Arduino IDE 1.8.19.
Compiler output looks like next text:
`In file included from C:\...\Marlin-2.1\Marlin\src\HAL\AVR\HAL.h:28:0,
''''''''''''''''''''from C:\...\Marlin-2.1\Marlin\src\HAL\HAL.h:30,
''''''''''''''''''''from C:\...\Marlin-2.1\Marlin\src\inc\MarlinConfig.h:31,
''''''''''''''''''''from C:\...\Marlin-2.1\Marlin\src\lcd\marlinui.h:24,
''''''''''''''''''''from C:\...\Marlin-2.1\Marlin\src\lcd\HD44780\lcdprint_hd44780.cpp:41:
C:\...\Marlin-2.1\Marlin\src\pins\mega\pins_MIGHTYBOARD_REVE.h:231:51: error: pasting "/* G5*/" and "_RPORT" does not give a valid preprocessing token
''''''''#define BEEPER_PIN          4  // G5
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''^
C:\...\Marlin-2.1\Marlin\src\HAL\AVR\fastio.h:84:39: note: in definition of macro '_TOGGLE'
'#define _TOGGLE(IO)           (DIO ## IO ## _RPORT = _BV(DIO ## IO ## _PIN))
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''^~`

### Bug Timeline

New bug

### Expected behavior

I think it happen because pin declaration for ATMega not so clear. Some parsers or compillers didnt got right preprocessor command.

### Actual behavior

Dont know yet.

### Steps to Reproduce

No have.

### Version of Marlin Firmware

Marlin-bugfix-2.1.x

### Printer model

Wanhao Duplicator 4S

### Electronics

MightyBoard REV.E

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9141856/Configuration.zip)

**Comment by ellensp** [comment]
looks like you have not install the sailfishlcd library https://github.com/mikeshub/SailfishLCD/archive/refs/heads/master.zip

**Comment by thisiskeithb** [comment]
I'd highly recommend [using VSCode & PlatformIO to compile Marlin](https://marlinfw.org/docs/basics/install_platformio.html). Your build will compile much faster & libraries will be managed for you.
