### ISSUE TITLE
[BUG] : filament run out trigger reboot even if not in print 

### ISSUE THREAD

**Issue by printer-through-window-soon** [MarlinFirmware/Marlin#24537]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

config : e3v2 with changed 4.2.7( originaly with 4.2.2)  bl touch 2.x and runout sensor  all from creality.
i am trying to make this config work its seems not to be the most popular (and i see why) and i am facing difficulties with the run out sensor:

printer ON just after boot screen if i take out the filament, the printer make a noize ( a grunt not like a beep) and then imediately reboot itself .
so i tested to remove the sensor and i tested a few thing its seems that my logic states is wrong as it print fine wit no filament in the sensor , i can figure this part myself but the boot problem is a mystery for me.

so i looked over on a few problem similar with the run out sensor and some peope found that cable 1 and 3 needed to be switched on one hand of the wire, i tried that but this change nothing for me. 

if someone as an idea of where this problem came from i'll be glad to look into it

### Bug Timeline

start

### Expected behavior

the runt out sensor dont get in a twist with filament in or out else printing, then it should trigger m600

### Actual behavior

if filament get pulled from sensor on any screen or moment it reboot the printer

### Version of Marlin Firmware

marlin -bugfix-2.0x

### Printer model

creality ender 3v2

### Electronics

changed board from 4.2.2 to the silent 4.2.7

### Add-ons

bl touch 2.x and run out sensor 

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
