### ISSUE TITLE
Printer starts at 1cm height [BUG] 

### ISSUE THREAD

**Issue by serget2** [MarlinFirmware/Marlin#24542]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Today I fixed a clog in my swiss micro direct drive on my ender 3 plus with an SKR mini 1.3 motherboard and Marlin 2.0x software which I painstakenly adapted to fit all my upgrades (I am the hardware guy software is not my thing), since 2021 this was running just fine but now I noticed my printer scratching my bed so I stopped immediately (No big damage) and leveled the bed , still noticed something was off, it did not stick to the bed even though everything was set right and 3DLAC sprayed on it it seemed to print a bit higher so I figured the offsett between BLtouch and Nozzle must be wrong, so all I did was go in to settings and changed the offsett from 3,500 to 3,400 mm, and when I tested suddenly my bed printed 1CM above the bed????? Looked this up and sure enough there where several people with a similar problem and setting the nozzle to the bed and resetting solved this, BUT it also set my bl/nozzle offset back to 3,500, repeating the steps again it printed 1cm in the air, I subsequently changed every setting I could find regarding Z-height, bl-touch and Nozzle but to no avail I now adjusted my bed manually to be much closer to the nozzle and this seems to work, so I can print now, BUT it does not seem right that an ofssett change of 0.1 mm creates a huge +/- 1 cm gap, also in this test I found that if I set the offset to 3.4, and then I manually level the bed and press "Position 5" it will bedlevel perfectly then stay up in the air at 1cm so there is nothing wrong with the workings of the bl-touch or the offset just a strange raise in height for some crazy reason 

### Bug Timeline

It's new for me but like I said I have seen people with similar problems

### Expected behavior

Just that my nozzle would come closer to the bed about 0.1 mm, making my pla stick to the bed

### Actual behavior

It raised the nozzle heigt to about 10 mm

### Steps to Reproduce

1. set nozzle offset manually in Marlin (in my case from 3.500 to 3.400)
2. save setting
3. go to manual bedlevel in menu - move - bedlevel (with a wrench)
4. choose a position (5 being the most logical one)
5. . wait for printer to home, see BL touch working fine, then see nozzle go up instead of down to the bed

### Version of Marlin Firmware

2.0 x

### Printer model

Ender 3 Pro

### Electronics

SKR mini 1.3

### Add-ons

BL-touch, swiss micro direct drive, bigtreetech touchscreen

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I did not test bugfix 2.1x and I should not, this worked fine without bug
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/9175693/Configuration_adv.zip)
s

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
