### ISSUE TITLE
[BUG] SanityCheck.h sensorless homing - logical error

### ISSUE THREAD

**Issue by mbattefeld** [MarlinFirmware/Marlin#24556]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

SanityCheck.h reports drivers not stallguard capable (TMC2209 in my case)

### Bug Timeline

27.07.2022

### Expected behavior

use stallguard with stallguard capable drivers

### Steps to Reproduce

Configure TMC2209 as X,Y,Z,Z2
Enable sensorless homing for all axis
compile marlin

### Version of Marlin Firmware

latest 2.1.x bugfix

### Printer model

Core XY

### Electronics

FLYF407ZG

### Add-ons

LCD, Filament sensor

### Bed Leveling

No Bed Leveling

### Your Slicer

Slic3r

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Conf + ADV:
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/9203520/Marlin.zip)

Solution for me: 
SanityCheck.h:
lines 3527 + 1796 are negating the query (is this driver "not sensorless") - (instead of is this driver sensorless),
which results in handling drivers capable of stallguard, like they are not. 

Removing the "!" in both lines makes the code work like expected.
[SanityCheck.h.zip](https://github.com/MarlinFirmware/Marlin/files/9203503/SanityCheck.h.zip)

**Comment by thisiskeithb** [comment]
Your board is failing the sensorless check because it does not have diag pins for sensorless homing/probing:

https://github.com/Mellow-3D/FLYF407ZG/blob/master/picture/Pin%20diagram.png

![image](https://user-images.githubusercontent.com/13375512/181373631-5bd6145f-07e1-4b52-a772-3be5a269a7c3.png)
