### ISSUE TITLE
[BUG] Compile error for BTT SKR V1.4 turbo with stock LCD from ender 3v2

### ISSUE THREAD

**Issue by Inkvi66** [MarlinFirmware/Marlin#24562]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

serial.h:
 - 'MYSERIAL' was not declared in this scope; did you mean 'MSERIAL'?
 - template argument 1 is invalid
 - request for member 'write' in 'multiSerial', which is of non-class type 'SerialOutputT' {aka 'int'}
 - request for member 'write' in 'multiSerial', which is of non-class type 'SerialOutputT' {aka 'int'}

### Bug Timeline

29.07.22

### Expected behavior

should compile with DWIN__LCD_PROUI or DWIN_MARLINUI_PORTRAIT enabled

### Actual behavior

does not compile with DWIN__LCD_PROUI or DWIN_MARLINUI_PORTRAIT enabled

### Steps to Reproduce

platformio.ini: 
 - default_envs = LPC1769

Configuration.h:
 - #define MOTHERBOARD BOARD_BTT_SKR_V1_4_TURBO
 - #define DWIN_LCD_PROUI
 - #define SDSUPPORT

Compile

### Version of Marlin Firmware

Marlin 2.1.x bugfix from official site

### Printer model

ender 3v2

### Electronics

BTT SKR 1.4 turbo

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9215240/Configuration.zip)

**Comment by ellensp** [comment]
you cannot use #define SERIAL_PORT_2 or #define SERIAL_PORT_3 when you have the e3v2 display.

You also have a large number of other config issues

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
