### ISSUE TITLE
[BUG] BABYSTEP_DISPLAY_TOTAL not reset on G28

### ISSUE THREAD

**Issue by Triangulix** [MarlinFirmware/Marlin#24577]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The comment for BABYSTEP_DISPLAY_TOTAL states: "Display total babysteps since last G28".
As it seems G28 does not reset the value which makes it "display total babysteps since power on", which is mostly useless.

### Version of Marlin Firmware

2.1.x Bugfix from 2022-07-23

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/9230012/Marlin.zip)

**Comment by Bob-the-Kuhn** [comment]
I just tried today's (4 AUG 2022) bugfix-2.1.x.  It worked as expected.
