### ISSUE TITLE
[BUG] Sd card files are not shown after succesful printjob 

### ISSUE THREAD

**Issue by SFRSKZ** [MarlinFirmware/Marlin#24589]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

as title says after a succesful printjob, my lcd (reprap smart controller-2004) doesnt show files in the sd card. 

tried on two different printers with mks boards;
tevo michelangelo > mks gen l and it s original screen. (it s a mks lcd 12864 but small, looks like those rgb mini12864 screens)
prusa bear upgrade > mks sgen l v2 and reprap smart controller.  

### Bug Timeline

2.0.93 and 2.1 both marlin versions have this issue. 

### Expected behavior

i expect them to show other files when i open "print from media"

### Actual behavior

LCDs show nothing when i open that menu.  after restarting the printer files are shown. but not after a print.

### Version of Marlin Firmware

2.1(bear mk3s) and 2.0.9.3(tevo m.)

### Printer model

prusa mk3, tevo m. 

### Electronics

mks gen l, mks sgen l v2

### Bed Leveling

ABL Bilinear mesh

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

https://www.mediafire.com/file/g08minq2av72xqb/Marlin.rar/file 

my config files

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.
