### ISSUE TITLE
[BUG] reprap rotary encoder not working

### ISSUE THREAD

**Issue by gyorgylevente** [MarlinFirmware/Marlin#24583]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The rotary encoder of my reprap discount smart controller with ramps 1.4+mega2560 doesnt work. (btw Marlin is configured to drive a K40 Laser)

### Bug Timeline

Came with fresh install

### Expected behavior

I expect to be able to navigate in the menu with the rotary encoder.

### Actual behavior

I'm unable to navigate in the menu. Click works.

The controller board (lcd+knob+buzzer) works plugged in to a different setup, so hardware issue is out.

### Steps to Reproduce

1. Configure latest release of marlin 2.1 with REPRAP_DISCOUNT_SMART_CONTROLLER on ramps 1.4+arduino mega 2560
2. Enter the menu with a click
3. turn rotary encoder
 it does not change the selection

### Version of Marlin Firmware

Marlin 2.1

### Electronics

Ramps 1.4 + Arduino Mega 2560

### Additional information & file uploads

[conf.zip](https://github.com/MarlinFirmware/Marlin/files/9255081/conf.zip)

**Comment by ellensp** [comment]
Provided configuration doesn't have a LCD enabled.

**Comment by ellensp** [comment]
Tested on marlin bugfix 2.1.x and Marlin bugfix 2.0.x 
Works as expected
