### ISSUE TITLE
[BUG] G30 OR G35 doesn't respect M206 " home offsets " " Triggered early "

### ISSUE THREAD

**Issue by Ahmed-mmm** [MarlinFirmware/Marlin#24590]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hello everybody
1st of all i'll explain the main configuration "that relates to the BUG" to make it easy following me . 
machine configuration : Ender 3 , dual independent z stepper motors , dual  z endstops "type optical" , leveling probe .
the 1st pic dictates the configuration ....... i made this configuration to give myself a room to change between different bed surfaces and different thicknesses , ranges from 1mm to 5mm

![main config](https://user-images.githubusercontent.com/106821318/182924519-9e150691-bf05-44b3-bffb-4a4688e8e0a2.jpg)

The problem arises when using G30 or G35 , _i don't know if the title is the best_
using different bed thicknesses leads to **probe triggered early .**

I did three tests using thickness .88mm , 2.46mm , 4.10mm  2nd illustration
**Test 1**    .88mm    pass fast and slow probing
**Test 2**    2.46mm  pass fast and slow probing
**Test 3**    4.10mm pass fast and slow fail " trigger early "

![all config](https://user-images.githubusercontent.com/106821318/183041234-1fd04298-0640-4d4d-817e-0628665c6dd3.jpg)

I traced down the code and figured out that my problem is **probe.cpp** 

> // Do a first probe at the fast speed
    const bool probe_fail = probe_down_to_z(z_probe_low_point, fr_mm_s),            // No probe trigger?
               early_fail = (scheck && current_position.z > -offset.z + clearance); // Probe triggered too high?
    #if ENABLED(DEBUG_LEVELING_FEATURE)
      if (DEBUGGING(LEVELING) && (probe_fail || early_fail)) {
        DEBUG_ECHOPGM_P(plbl);
        DEBUG_ECHOPGM(" Probe fail! -");
        if (probe_fail) DEBUG_ECHOPGM(" No trigger.");
        if (early_fail) DEBUG_ECHOPGM(" Triggered early.");
        DEBUG_EOL();
      }

**Test 1 ** passed cause _current_position.z > -offset.z + clearance_ was **False**
                                                 2.88            >    -(-2)   +  3
**Test 2 ** passed cause _current_position.z > -offset.z + clearance_ was **False**
                                                 4.46            >    -(-2)   +  3
**Test 3 ** failed cause _current_position.z > -offset.z + clearance_ was **True**
                                                 6.10            >    -(-2)   +  3
If we add **home_offset.z** to this calculation to be :
                  **home_offset.z**+_current_position.z > -offset.z + clearance_
                              -4.11       +       6.10               >   -(-2)     + 3
It will work . I already did

Note : this piece of code works with fast and slow probing , the comment needs correction from   
_// Do a first probe at the fast speed_  TO _//Do probing_ or whatever

Beyond and related to the subject 
Why doesn't Marlin take **home offsets** into consideration . if the user changed the offsets , he intentionally wants to change the geometry of the machine he uses .
Also and more important the software endstops must comply with these offsets 
  

### Version of Marlin Firmware

bugfix 2.1.x "31 jul 2022"

### Printer model

Creality Ender 3

### Electronics

SKR 1.3

### Don't forget to include

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by unitrix0** [comment]
I wonder if the G29 command does respect home offsets.

**Comment by mriscoc** [comment]
Home offset has effect on work area not on probing area, that's why I recommend to use XYZ Min/Max position settings instead of Home offsets.
https://github.com/mriscoc/Ender3V2S1/wiki/How-to-set-the-home-offsets
