### ISSUE TITLE
[BUG] Workspace coordinates G54-G59.3 does not respect bed leveling

### ISSUE THREAD

**Issue by fugalster** [MarlinFirmware/Marlin#24628]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When using machine coordinate offsets (G54-G59.3) the nozzle does not follow the bed level profile developed during the G29 routine. Rather than using the equivalent machine coordinates for bed leveling, it appears to use the local workspace coordinates. For example, if the bed origin is in the front left corner and is dished (bowl shaped), then when printing near the center of the bed using a workspace coordinate centered on the bed, the nozzle will be too high since the workspace coordinates give the appearance of printing near the machine origin rather than the workspace origin.

### Bug Timeline

As far as I can tell, this bug has been present since workspace coordinates were introduced.

### Expected behavior

When printing in a workspace coordinate system, the expected behavior should be to follow the *actual* bed z profile as described in machine coordinates, not to assume that the workspace coordinate system is aligned with the machine coordinate system (thereby nullifying the benefit of machine coordinates).

### Actual behavior

If the bed origin is in the front left corner and the bed is dished (bowl shaped), then when printing near the center of the bed using a workspace coordinate centered on the bed, the nozzle will be too high since the workspace coordinates give the appearance of printing near the machine origin rather than the workspace origin.

### Steps to Reproduce

1) Slice a part centered on the slicer origin.
2) In the gcode, after the startup code but prior to the part code, move the nozzle to where the part is to be printed and set a workspace coordinate system as follows (For the most obvious results, select a location on the bed where the deviation from perfect level is greatest).

G54 ; or G55, G56, etc through G59.3
G92 X0 Y0

3) Print the part and observe that the nozzle does not follow the auto bed level profile.

### Version of Marlin Firmware

bugfix-2.0.8.2.x

### Printer model

Creality Ender 3

### Electronics

BTT skr mini v2

### Add-ons

BL Touch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by DerAndere1** [comment]
Are you sure you tested bugfix-2.1.x (not bugfix-2.0.x or any other version) ? Please attach your configs.

I could not find a problem when looking into the code. To summarize my findings: Workspace coordinates are directly converted to positions in native machine coordinate system by `get_destination_from_command()` and the native position is stored in global variable `current_position`. The leveling correction is applied using the function `apply_modifiers()` which calls `apply_leveling()` . It all uses native positions FWIW,
