### ISSUE TITLE
[FR] Delta Calibration Menu and Mesh Edit GFX Overlay for TFT_LVGL_UI

### ISSUE THREAD

**Issue by Orafilynie** [MarlinFirmware/Marlin#24633]
### Is your feature request related to a problem? Please describe.

Related to my last issue, only the CLASSIC_UI is compatible with DELTA_CALIBRATION_MENU and MESH_EDIT_GFX_OVERLAY and that's a shame that i can't use my TFT color screen to its full potential.

### Describe the feature you want

Make TFT_LVGL_UI compatible with DELTA_CALIBRATION_MENU and MESH_EDIT_GFX_OVERLAY if possible so i can use the full potential of my TFT Screen

**Comment by Orafilynie** [comment]
Bump

**Comment by jmz52** [comment]
> only the CLASSIC_UI is compatible with DELTA_CALIBRATION_MENU and MESH_EDIT_GFX_OVERLAY

MESH_EDIT_GFX_OVERLAY is indeed to feature limited to 12864 UI, however the UBL functionality can be used without it.
COLOR_UI with automatic delta calibration and UBL works just fine on my FLSUN Q5

![Delta_UBL](https://user-images.githubusercontent.com/9879021/191708235-2d7d17ce-02e0-42ac-a882-57e2d97c611c.jpg)

**Comment by Orafilynie** [comment]
Yeah i saw that it could build on color so i will reactivate ubl and ill test when i receive my tmc and flsun q5 printer tommorow

**Comment by Orafilynie** [comment]
Thanks for letting me know

**Comment by Orafilynie** [comment]
Solved

**Comment by Orafilynie** [comment]
> > only the CLASSIC_UI is compatible with DELTA_CALIBRATION_MENU and MESH_EDIT_GFX_OVERLAY
> 
> MESH_EDIT_GFX_OVERLAY is indeed to feature limited to 12864 UI, however the UBL functionality can be used without it. COLOR_UI with automatic delta calibration and UBL works just fine on my FLSUN Q5
> 
> ![Delta_UBL](https://user-images.githubusercontent.com/9879021/191708235-2d7d17ce-02e0-42ac-a882-57e2d97c611c.jpg)

also how did you flash your flsun q5 as mine stuck at updating 100%
