### ISSUE TITLE
when define EEPROM_SETTINGS is on, the DEFAULT_AXIS_STEPS_PER_UNIT will always be 80 80 800 1400 is you not use M502

### ISSUE THREAD

**Issue by Zhujingxi** [MarlinFirmware/Marlin#24637]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

when define EEPROM_SETTINGS is on, the DEFAULT_AXIS_STEPS_PER_UNIT will always be 80 80 800 1400 if you not don't M502 after flash.

### Bug Timeline

when this bug report 2022 8 17

### Expected behavior

be DEFAULT_AXIS_STEPS_PER_UNIT when flashed but still can change by M500 M501

### Actual behavior

The Steps pre unit always be 80 80 800 1400 until you use M502

### Steps to Reproduce

flash a firmware, with define EEPROM_SETTINGS.

### Version of Marlin Firmware

Marlin 2.1 (Aug 17 2022 03:14:01) 

### Printer model

Custom MKS_GEN_L motherboard with TMC2209_stand_alone

### Electronics

MKS_GEN_L

### Add-ons

MKS_MINI_12864_V3

### Bed Leveling

No Bed Leveling

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/9354218/Archive.zip)
Thanks guys, I love marlin firmware

**Comment by thisiskeithb** [comment]
This is a feature, not a bug. When updating to new firmware & those settings are changed, you need to initialize EEPROM through the LCD or by sending `M502`, followed by `M500`.

Alternatively, you can enable `EEPROM_INIT_NOW` and Marlin will initialize EEPROM on first boot after a new build.
