### ISSUE TITLE
[BUG]SKR MINI E3 V2.0 FAN0 AND FAN1 Its always at ON STATE (bug summary)

### ISSUE THREAD

**Issue by DionisisMal** [MarlinFirmware/Marlin#24639]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I flashed my skr mini e3 v2.0 with latest marlin firmware on my ender 3 pro
I try to control my part cooling fan but its not working . Always it just stays ON . i use multimeter at FAN0 and FAN1 , Both 23.9v
i try all the firmware in site with no luck.
I cant control from LCD SCREEN they just always spinning . 

### Add-ons

Neopixel. Dual 5015 24v Part cooling fans

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
