### ISSUE TITLE
indianness choice in u8glib converter.html

### ISSUE THREAD

**Issue by toto-toa** [MarlinFirmware/Marlin#24666]
I used your u8glib converter to generate bitmap (XBM files). The generated code used on Espressif devices (esp32/esp8266) has a  'endianness' inversion, certainly induced by the structure of the esp ¨?
 So it will be nice of you to add an option to choose beetween little or big-endian.
Thank you in advance.
The generated file:

![image](https://user-images.githubusercontent.com/36064772/185864132-c60bae0c-cc66-4a5a-8a0e-0a61795d3de0.png)

..and the displayed one (normal and inverted)

![image](https://user-images.githubusercontent.com/36064772/185864515-a60d4aa1-3f04-4ad4-8137-6a002d489fb0.png)

### Describe the feature you want

choice of the endianness to generate the XBM file

**Comment by toto-toa** [comment]
... and if I reconstruct the picture...

![image](https://user-images.githubusercontent.com/36064772/185865613-c2d65eb6-7cfb-4dc3-8885-7363289dbe1b.png)

**Comment by EvilGremlin** [comment]
Hello Columbus Junior!
Endian! E! from End!
Anyway, this is no concern for marlin, endianness is different everywhere and dealt with by platformio frameworks and display code, image array itself stay same for all platforms.
