### ISSUE TITLE
[BUG] Freeze feature doesn't work

### ISSUE THREAD

**Issue by orfeasv** [MarlinFirmware/Marlin#24662]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Freeze feature should halt all stepper motion when freeze pin is triggered. It worked fine in the previous version I had (2.0.9.3).

### Bug Timeline

Updating from 2.0.9.3 to 2.1.1

### Expected behavior

When freeze pin receives LOW input (Z endstop switch is closed) all stepper movements should stop.

### Actual behavior

All stepper movements continue to work as if freeze pin never changed state.

### Version of Marlin Firmware

2.1.1

### Printer model

Anet A8

### Electronics

BTT SKR V1.4 Turbo

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Problem was solved by changing:

```
#if HAS_FREEZE_PIN 
  stepper.frozen = READ(FREEZE_PIN) == FREEZE_STATE;
#endif
```
to
```
#if ENABLED(FREEZE_FEATURE)
  stepper.frozen = READ(FREEZE_PIN) == FREEZE_STATE;
#endif
```

 in **MarlinCore.cpp** line 491. I assume it was forgotten when "HAS_FREEZE_PIN" was removed

Attached is my config
[config.zip](https://github.com/MarlinFirmware/Marlin/files/9389427/config.zip)

**Comment by thisiskeithb** [comment]
Thanks for the report! This will be fixed in https://github.com/MarlinFirmware/Marlin/pull/24664
