### ISSUE TITLE
[BUG] Wrong documentation for M913 and M914

### ISSUE THREAD

**Issue by digant73** [MarlinFirmware/Marlin#24678]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Since Marlin 2.0.9.3, the status of the TMC commands in relation to the usage of the I-command is the following:
**M913** (Set TMC Hybrid Threshold Speed) and
**M914** (Set TMC stallguard sensitivity)
The meaning of the I-parameter is as follows:
No I-parameter or I0 means all drivers (X, X2)
I1 means driver 1 (X, Y, Z)
I2 means driver 2(X2, Y2, Z2)

But the related documentation pages https://marlinfw.org/docs/gcode/M913.html and https://marlinfw.org/docs/gcode/M914.html are reporting a wrong description for I and T params. (e.g. I1 for X2 instead of I2 for X2, missing T for E0 while the current implementation uses a missing T (or T-1) for applying the changes to  all the  extruders).

**NOTE:**
For M569 and M906 a different indexing is used:
**M906** (set driver current) and
**M569** (Set spreadcycle or stealthchop)
The meaning of the I-parameter is as follows:
No I-parameter or I-1 means all drivers (X, X2)
I0 means driver 1 (X, Y, Z)
I1 means driver 2 (X, Y, Z)

IMHO, it should be better to use the same indexing for all the commands requiring I and T params (e.g. I2 for X2 for both M569, M906, M913 and M914).

### Bug Timeline

Marlin 2.0.9.3

### Expected behavior

Correct documentation for M913 and M914

### Actual behavior

Wrong documentation for M913 and M914

### Version of Marlin Firmware

Official Marlin 2.1.1

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by GMagician** [comment]
and also, not sure if next unsensed example act as intended or not:
M913 X Y Z I4 will change X2 and Y2 as well
