### ISSUE TITLE
[BUG] platforms.h HAL_STM32 compile error (FIX)

### ISSUE THREAD

**Issue by classicrocker883** [MarlinFirmware/Marlin#24697]
as you can see this does not work

platforms.h line 40 
```
#elif defined(ARDUINO_ARCH_STM32)
  #ifndef HAL_STM32
    #define HAL_STM32
  #endif
  #define HAL_PATH(PATH, NAME) XSTR(PATH/STM32/NAME)
```

### instead it should be written like this
```
#elif defined(ARDUINO_ARCH_STM32) || defined(HAL_STM32)
```

after it is like this no problems are detected

well i guess technically it is fine without the change, but to help mitigate compile errors

**Comment by Bob-the-Kuhn** [comment]
What is the error and how do we reproduce it?

**Comment by classicrocker883** [comment]
when using PROUI it doesnt really give an error. but it shows problems as though it isnt defined.
this helps keep the reported problems down. at least on my end

**Comment by sjasonsmith** [comment]
I'm also not understanding how this is misbehaving. If `HAL_PATH` wasn't being defined you should have hit the `#error` case at the bottom of the file. It shouldn't be silently failing.

@classicrocker883 for anything to happen with this you will need to provide your configuration headers which are being impacted by this.

**Comment by sjasonsmith** [comment]
Closing, since we can't really tell what the problem is and OP is unresponsive.
