### ISSUE TITLE
[BUG] Top (return) LCD menu items missing

### ISSUE THREAD

**Issue by Bob-the-Kuhn** [MarlinFirmware/Marlin#24708]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The top (return) LCD menu items are no longer present.  There is no way to go back up one menu level other than to wait for the timeout.

### Bug Timeline

I think this bug is less than a week old.

### Expected behavior

The top menu item (that allows you to go back up one level) should be present.

### Actual behavior

The top menu item is not present.  No way to go back up the menu tree.

### Steps to Reproduce

Enable a REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER LCD or similar.

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.1.x (Aug 29 2022 12:59:51)

### Printer model

Tevo Little Monster (delta printer)

### Electronics

stock MKS SBASE (LP1768)

### Add-ons

Duet Smart Effector

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/24689

**Comment by thisiskeithb** [comment]
This will be fixed in https://github.com/MarlinFirmware/Marlin/pull/24694
