### ISSUE TITLE
[BUG] (bug summary) Temperature drops Before Starting print , Will not hold Temp.

### ISSUE THREAD

**Issue by Gregalan2114** [MarlinFirmware/Marlin#24715]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I'm trying to fix my geeetech A10's temperature drops by working my way through the code, but I can get the softwaredownload but looking at the Code in the Arduino Source I cannot find the Problom, and it's not working. 
If there is a way to make it a slow gain and slow recovery the Temperature  in the Head so that it will start my printer, I am unable to determine the cause of what is happening.
I sometimes have to wait for it to try to print for at least 30 minutes. 
Let me know what i can do Please or if you can Tr to Help me get this Fixed in the Code 

### Bug Timeline

emperature Drop , Will not stat print 

### Expected behavior

Everything is working ok but the Temperature Drops

### Actual behavior

I'm trying to fix my geeetech A10's temperature drops by working my way through the code, but I can get the softwaredownload but looking at the Code in the Arduino Source I cannot find the Problom, and it's not working. 
If there is a way to make it a slow gain and slow recovery the Temperature  in the Head so that it will start my printer, I am unable to determine the cause of what is happening.
I sometimes have to wait for it to try to print for at least 30 minutes. 
Let me know what i can do Please or if you can Tr to Help me get this Fixed in the Code 

### Steps to Reproduce

I'm trying to fix my geeetech A10's temperature drops by working my way through the code, but I can get the softwaredownload but looking at the Code in the Arduino Source I cannot find the Problom, and it's not working. 
If there is a way to make it a slow gain and slow recovery the Temperature  in the Head so that it will start my printer, I am unable to determine the cause of what is happening.
I sometimes have to wait for it to try to print for at least 30 minutes. 
Let me know what i can do Please or if you can Tr to Help me get this Fixed in the Code 

### Version of Marlin Firmware

2.0x Latast 

### Printer model

Geeetech A10

### Electronics

GT560

### Add-ons

.

### Your Slicer

Other (explain below)

### Host Software

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I'm trying to fix my geeetech A10's temperature drops by working my way through the code, but I can get the softwaredownload but looking at the Code in the Arduino Source I cannot find the Problom, and it's not working. 
If there is a way to make it a slow gain and slow recovery the Temperature  in the Head so that it will start my printer, I am unable to determine the cause of what is happening.
I sometimes have to wait for it to try to print for at least 30 minutes. 
Let me know what i can do Please or if you can Tr to Help me get this Fixed in the Code

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
