### ISSUE TITLE
[BUG] SD media init fail 

### ISSUE THREAD

**Issue by usfiwuni** [MarlinFirmware/Marlin#24716]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

when inserting an sd card it fails to read it by giving media init fail
I've tried different sd cards, sd readers/displays, mainboards and the problem does still persists
trigorilla 2560 and mks mini 12864 v3, reprap smart discount controller

weirdly when I did try to modify pin declaration under minipal under pins_ramps.h to:
`#elif ENABLED(MINIPANEL)
#define BEEPER_PIN 37
// Pins for DOGM SPI LCD Support
#define DOGLCD_A0 16
#define DOGLCD_CS 17
#define LCD_BACKLIGHT_PIN -1 // backlight LED on A11/D65
#define LCD_RESET_PIN 23
#define SDSS 53
#define KILL_PIN -1
#define LCD_CONTRAST 200
#define BTN_EN1 31
#define BTN_EN2 33
#define BTN_ENC 35 //the click switch
#define SD_DETECT_PIN 49`

with the mks mini 12864 v3 board, it did start to work for a short while without issues, and now it's again back with issues, failing to read the sd card

### Expected behavior

the media should be init and readen

### Actual behavior

it fails to init the media

### Version of Marlin Firmware

2.1.x

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin-bugfix-2.1.x(1).zip](https://github.com/MarlinFirmware/Marlin/files/9480255/Marlin-bugfix-2.1.x.1.zip)

**Comment by TzOk83** [comment]
I also have Media Init Fail when I remove and reinsert SD Card, but the card works as usual. I'm using Ender 3 with CREALITY 4.2.7 board, with a slightly tweaked for BL-Touch sample configuration from config\examples\Creality\Ender-3\CrealityV427.
