### ISSUE TITLE
[BUG] Move X axis during Z probe move Z up

### ISSUE THREAD

**Issue by trivalik** [MarlinFirmware/Marlin#24726]
### Did you test the latest `bugfix-2.1.x` code?

Yes, behaves different, read bug description.

### Bug Description

I noticed when I do auto bed level via menu and in moment of Z axis probing moves up (in bed center) I start moving X axis up via menu a mm. The result is that it moves up endless (I guess it because I stopped it before it reach the top end).
This is behavior in 2.0.9.5.

The behavior in 2.1.x is that it moves the axis and home then further.

Configuration files:
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/9483343/Config.zip)

### Bug Timeline

I can imagine that it's exists all time.

### Expected behavior

X axis moves after home ends, or it does nothing, or the menu is not accepting x axis move at all.

### Version of Marlin Firmware

Marlin 2.0.9.5

### Printer model

Anet A6

### Electronics

ANET Board 1.0

### Add-ons

18mm z probe sensor

### Bed Leveling

ABL Bilinear mesh

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by tgolowan** [comment]
Have exactly the same issue - Ender 3 - MKS GEN L - bugfix 2.1.x
