### ISSUE TITLE
[BUG] Move axis error - duplicate values

### ISSUE THREAD

**Issue by cocosaubro** [MarlinFirmware/Marlin#24734]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The error occurs when moving the axes, leveling or printing a gcode, the displacement is incorrect, since the movements are increased by double, for example, if I give X displacement in 10 mm, it indicates that this was the displacement, but in reality offset was double at 20mm, double even though the screen says it was 10mm.
The above happens with all the axes, whenever they move they do it twice, this happens in the pre build firmware and in the manual build.

The bed measures 320mmx320mm and Z 400mm, but when leveling, moving the axes or printing a Gcode, the mm indicated on the screen only reaches half, but this is false, because the axes have already reached their limit and hit the base.

Performing the movements of the axes manually was when I saw that each mm is taken as if it were multiplied by two.

The error occurs on a Sunlu S8 motherboard + MKS Robin Nano V3.1 + TMC2209 Drivers.

### Expected behavior

I expected it to move correctly, for example, by indicating that X moves 10mm it should move that distance, but it does not, it moves 20mm (twice as much), even though the screen indicates otherwise.

### Actual behavior

When moving the axes it takes a double value, that is, if I indicate that X travels 10mm, it actually moves 20mm, even though the screen indicates otherwise.

### Steps to Reproduce

Download Marlin.
Build it.
Install on the motherboard.

### Version of Marlin Firmware

[Marlin-bugfix-2.1.x](https://github.com/MarlinFirmware/Marlin)
[Mks-Robin-Nano-Marlin2.0](https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware)

### Printer model

Sunlu S8

### Electronics

MKS Nano Robin V3.1

### Add-ons

MKS Nano Robin V3.1

### Your Slicer

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
[Configuration.zip](https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/files/9485648/Configuration.zip)

### Video Error
-[Error - duplicate offset](https://www.youtube.com/watch?v=ky5sqCnRPvM)

**Comment by EvilGremlin** [comment]
This is user error - your config missing DRIVER_TYPE section so undefined TMC defaults to 1/8 microsteps. Also you must reset EEPROM for it to take effect. And config is old 2.0.9.2.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
