### ISSUE TITLE
[FR] SV04 with Creality v5.2.1 not in Marlin

### ISSUE THREAD

**Issue by Plyn1x** [MarlinFirmware/Marlin#24746]
### Is your feature request related to a problem? Please describe.

I was trying to compile my own firmware for my SV04 but theres no premade profile so i started on my own, but now i realized that they used an  BOARD_CREALITY_V4 but changed the pins files. Any ides how i could add an board? I already got all the pins where they are linked

### Are you looking for hardware support?

SV04 

### Describe the feature you want

Maybe add the board

**Comment by ellensp** [comment]
Duplicate https://github.com/MarlinFirmware/Marlin/issues/24729
