### ISSUE TITLE
[BUG] Mightyboard rev e. Creator Pro Part Cooling fan

### ISSUE THREAD

**Issue by folkertj** [MarlinFirmware/Marlin#24743]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

M106 doesn’t activate part cooling fan because cooling fan is not defined in marlin configuration.h.

I would really appreciate it if someone could tell me which pin in pins.h corresponds to the cooling fan and how to define it in configuration.h 

### Bug Timeline

Old issue

### Expected behavior

M106 command should activate part cooling fan 

### Actual behavior

It doesn’t.

### Steps to Reproduce

After installing latest marlin config, sending m106 command in S3D gets no response. Cooling fan doesn’t come on in prints.

### Version of Marlin Firmware

2.1.1 bugfix 

### Printer model

Creator Pro 2016

### Electronics

Mightyboard rev e (ff rev h)

### Add-ons

None

### Bed Leveling

No Bed Leveling

### Your Slicer

Simplify3D

### Host Software

Same as my slicer

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

None

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
#define FAN_PIN   {number of the io port the fan is connected to}

**Comment by folkertj** [comment]
Thank you
