### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by netmanno1** [MarlinFirmware/Marlin#24742]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Processing STM32G0B1RE_btt_xfer (platform: ststm32@~14.1.0; board: marlin_STM32G0B1RE; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
In file included from c:\users\administrator\desktop\marlin-2.1.x\marlin\src\pins\pins.h:543,
                 from c:\users\administrator\desktop\marlin-2.1.x\marlin\src\inc\marlinconfig.h:34,
                 from buildroot/share/PlatformIO/scripts/common-dependencies.h:29:
c:\users\administrator\desktop\marlin-2.1.x\marlin\src\pins\stm32g0/pins_BTT_SKR_MINI_E3_V3_0.h:174:6: error: #error "CAUTION! DWIN_CREALITY_LCD requires a custom cable, see diagram above this line. (Define NO_CONTROLLER_CUSTOM_WIRING_WARNING to suppress this warning.)"
  174 |     #error "CAUTION! DWIN_CREALITY_LCD requires a custom cable, see diagram above this line. (Define NO_CONTROLLER_CUSTOM_WIRING_WARNING to suppress this warning.)"
      |      ^~~~~
Error: MOTHERBOARD is not defined in Configuration.h
===================================================================================================== [FAILED] Took 1.03 seconds =====================================================================================================
Environment           Status    Duration
--------------------  --------  ------------
STM32G0B1RE_btt_xfer  FAILED    00:00:01.034
=============================================================================================== 1 failed, 0 succeeded in 00:00:01.034 =============================================================================================== 

### Version of Marlin Firmware

Marlin-2.1.x

### Printer model

Ender3 v2

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

![屏幕截图(26)](https://user-images.githubusercontent.com/84674467/189264120-98674f9e-b989-4eb3-b477-68cd91eb8af4.png)

**Comment by ellensp** [comment]
CAUTION! DWIN_CREALITY_LCD requires a custom cable, see diagram above this line. (Define NO_CONTROLLER_CUSTOM_WIRING_WARNING to suppress this warning.)

This is a deliberate warning to stop you from just plugging in the lcd and expecting it to work.

Read the error message

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
