### ISSUE TITLE
[BUG] Homing failed on Fysetc Spider2.3 board with bugfix-2.1.x branch

### ISSUE THREAD

**Issue by Johnny-Martin** [MarlinFirmware/Marlin#24745]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

My board is Fysetc Spider2.3, when I select the "Auto Home" menu item and press the button, the XYZ axises are not homing to  endstop, they just move a little distance towards the endstop and then stoped. 

I used M119 to test the endstop state with X_endtop triggered:
![image](https://user-images.githubusercontent.com/13740871/189375111-f3e0fd78-93ab-4873-b4fe-b25910aa6c97.png)

The resule is as expected.

My configuration for Spider2.3:
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9536337/Configuration.zip)

This phenomenon appears every time when I try to home the XYZ axises.

### Expected behavior

I expect the XYZ axises can move and touch the endstop when I press the "Auto Home" menu item.

### Actual behavior

The XYZ axises jost moved a little distance and stoped, homing failed.

### Steps to Reproduce

1. Set the config file as Configuration.zip shows.
2. Build the Marlin project, cand copy firmware.bin to TF card.
3. Reboot the Fystc Spider2.3 board, wait for system start.
4. Select the "Auto Home" on menu, and press.

### Version of Marlin Firmware

Marlin 2.1.1 (Sep  9 2022 22:11:48) 

### Printer model

MB

### Add-ons

TMC2209

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

SENDING:M111 S247
echo:DEBUG:ECHO,INFO,ERRORS,COMMUNICATION
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:M105
echo:Homing Failed
Error:Printer halted. kill() called!
Error:Printer halted. kill() called!

**Comment by Johnny-Martin** [comment]
This phenomenon appears in both bugfix_2.1.x and release_2.1.1 branches. What's the rootcause, Spider2.3 or the TMC2209 Driver？ I‘m not sure....

**Comment by ellensp** [comment]
not enough information...

Are you using physical end stops or sensorless?

If physical, did you notice this board has endstop in a different order than most
X-MAX, Y-MAX, Z-MAX, Z-MIN, Y-MIN, X-MIN

https://wiki.fysetc.com/images/Spider_V2.3_Pinout.jpg

**Comment by Johnny-Martin** [comment]
I used physical end stops. And the order is right, if not, the result of M119 will not as expected, right?
![Snipaste_2022-09-13_23-59-47](https://user-images.githubusercontent.com/13740871/189950280-84e99c9b-5ec2-4513-b3a9-32b7155e0aa9.jpg)

**Comment by Johnny-Martin** [comment]
I checked the configuration and my wiring again, the problem still exist.
![Snipaste_2022-09-22_00-07-17](https://user-images.githubusercontent.com/13740871/191555836-8da24f7a-8fcc-4ba1-9205-271fb086ec11.jpg)

 The Y axis homing failed. then I removed the Y axis steper,  and start "auto home",  press the Y endstop with my fingre, homing succeed......

**Comment by Johnny-Martin** [comment]
Finally, I got it! The root cause is, the "Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN" micro is defined as default, and I didnt have a probe!

**Comment by Johnny-Martin** [comment]
BTW, I think the "Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN" micro should not defined as default

**Comment by ellensp** [comment]
This does not make sense.

Marlin has 

```
/**
 * Conditionals based on the type of Bed Probe
 */
#if HAS_BED_PROBE

...Do stuff...

#else
  // Clear probe pin settings when no probe is selected
  #undef Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
  #undef USE_PROBE_FOR_Z_HOMING
#endif

```
Ie. If it is not used it is automatically removed.
