### ISSUE TITLE
[BUG] (bug summary) A very, very important build-related issue

### ISSUE THREAD

**Issue by Student-Jasons** [MarlinFirmware/Marlin#24741]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I tried to build with platformio using vsstudio to use bltouch in my ender3, but I got an error and it happened in firmware.elf, not configuration.h, adv, etc. Put the error code and configuration file on this page I'll give you
error
`Processing melzi (board: sanguino_atmega1284p; platform: atmelavr@~3.4; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/sanguino_atmega1284p.html
PLATFORM: Atmel AVR (3.4.0) > Sanguino ATmega1284p (16MHz)
HARDWARE: ATMEGA1284P 16MHz, 16KB RAM, 124KB Flash
DEBUG: Current (simavr) On-board (simavr)
PACKAGES: 
 - framework-arduino-avr @ 5.1.0 
 - toolchain-atmelavr @ 1.70300.191015 (7.3.0)
Converting Marlin.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 6 compatible libraries
Scanning dependencies...
Dependency Graph
|-- U8glib-HAL @ 0.5.2
|   |-- Wire @ 1.0
|   |-- SPI @ 1.0
|-- SPI @ 1.0
|-- Wire @ 1.0
Building in release mode
Compiling .pio\build\melzi\src\src\HAL\AVR\HAL.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\HAL_SPI.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\MarlinSerial.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\Servo.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\eeprom.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\fast_pwm.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\u8g_com_HAL_AVR_sw_spi.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\Delay.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\HAL.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\MinSerial.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\eeprom_api.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\esp_wifi.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\servo.cpp.o
Compiling .pio\build\melzi\src\src\MarlinCore.cpp.o
Compiling .pio\build\melzi\src\src\core\serial.cpp.o
Compiling .pio\build\melzi\src\src\core\utility.cpp.o
Compiling .pio\build\melzi\src\src\feature\babystep.cpp.o
Compiling .pio\build\melzi\src\src\feature\bedlevel\abl\bbl.cpp.o
Compiling .pio\build\melzi\src\src\feature\bedlevel\bedlevel.cpp.o
Compiling .pio\build\melzi\src\src\feature\bltouch.cpp.o
Compiling .pio\build\melzi\src\src\gcode\bedlevel\G42.cpp.o
Compiling .pio\build\melzi\src\src\gcode\bedlevel\M420.cpp.o
Compiling .pio\build\melzi\src\src\gcode\bedlevel\abl\G29.cpp.o
Compiling .pio\build\melzi\src\src\gcode\bedlevel\abl\M421.cpp.o
Compiling .pio\build\melzi\src\src\gcode\calibrate\G28.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M200-M205.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M220.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M221.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M301.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M302.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M309.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M92.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M108_M112_M410.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M111.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M120_M121.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M17_M18_M84.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M211.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M280.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M400.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M80_M81.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M85.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M993_M994.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M997.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M999.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\T.cpp.o
Compiling .pio\build\melzi\src\src\gcode\eeprom\M500-M504.cpp.o
Compiling .pio\build\melzi\src\src\gcode\feature\digipot\M907-M910.cpp.o
Compiling .pio\build\melzi\src\src\gcode\gcode.cpp.o
Compiling .pio\build\melzi\src\src\gcode\gcode_d.cpp.o
Compiling .pio\build\melzi\src\src\gcode\geometry\G92.cpp.o
Compiling .pio\build\melzi\src\src\gcode\geometry\M206_M428.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M110.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M113.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M114.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M115.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M118.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M119.cpp.o
Compiling .pio\build\melzi\src\src\gcode\lcd\M0_M1.cpp.o
Compiling .pio\build\melzi\src\src\gcode\lcd\M117.cpp.o
Compiling .pio\build\melzi\src\src\gcode\lcd\M145.cpp.o
Compiling .pio\build\melzi\src\src\gcode\motion\G0_G1.cpp.o
Compiling .pio\build\melzi\src\src\gcode\motion\G2_G3.cpp.o
Compiling .pio\build\melzi\src\src\gcode\motion\G4.cpp.o
Compiling .pio\build\melzi\src\src\gcode\motion\M290.cpp.o
Compiling .pio\build\melzi\src\src\gcode\parser.cpp.o
Compiling .pio\build\melzi\src\src\gcode\probe\G30.cpp.o
Compiling .pio\build\melzi\src\src\gcode\probe\M401_M402.cpp.o
Compiling .pio\build\melzi\src\src\gcode\probe\M851.cpp.o
Compiling .pio\build\melzi\src\src\gcode\queue.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M1001.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M20.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M21_M22.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M23.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M24_M25.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M26.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M27.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M28_M29.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M30.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M32.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M33.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M34.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M524.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M928.cpp.o
Compiling .pio\build\melzi\src\src\gcode\stats\M31.cpp.o
Compiling .pio\build\melzi\src\src\gcode\stats\M75-M78.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M104_M109.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M105.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M106_M107.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M140_M190.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M141_M191.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M155.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M303.cpp.o
Compiling .pio\build\melzi\src\src\gcode\units\M82_M83.cpp.o
Compiling .pio\build\melzi\src\src\inc\Warnings.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\lcdprint_u8g.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\marlinui_DOGM.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\status_screen_DOGM.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\status_screen_lite_ST7920.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_ssd1306_sh1106_128x64_I2C.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_ssd1309_12864.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_st7565_64128n_HAL.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_st7920_128x64_HAL.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_tft_upscale_from_128x64.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_uc1701_mini12864_HAL.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_fontutf8.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\ultralcd_st7920_u8glib_rrd_AVR.cpp.o
Compiling .pio\build\melzi\src\src\lcd\extui\ui_api.cpp.o
Compiling .pio\build\melzi\src\src\lcd\fontutils.cpp.o
Compiling .pio\build\melzi\src\src\lcd\lcdprint.cpp.o
Compiling .pio\build\melzi\src\src\lcd\marlinui.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_advanced.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_bed_leveling.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_configuration.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_game.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_info.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_main.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_media.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_mixer.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_motion.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_probe_offset.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_temperature.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_tune.cpp.o
Compiling .pio\build\melzi\src\src\libs\buzzer.cpp.o
Compiling .pio\build\melzi\src\src\libs\numtostr.cpp.o
Compiling .pio\build\melzi\src\src\libs\stopwatch.cpp.o
Compiling .pio\build\melzi\src\src\libs\vector_3.cpp.o
Compiling .pio\build\melzi\src\src\module\endstops.cpp.o
Compiling .pio\build\melzi\src\src\module\motion.cpp.o
Compiling .pio\build\melzi\src\src\module\planner.cpp.o
Compiling .pio\build\melzi\src\src\module\probe.cpp.o
Compiling .pio\build\melzi\src\src\module\servo.cpp.o
Compiling .pio\build\melzi\src\src\module\settings.cpp.o
Compiling .pio\build\melzi\src\src\module\stepper.cpp.o
Compiling .pio\build\melzi\src\src\module\stepper\indirection.cpp.o
Compiling .pio\build\melzi\src\src\module\temperature.cpp.o
Compiling .pio\build\melzi\src\src\module\tool_change.cpp.o
Compiling .pio\build\melzi\src\src\sd\Sd2Card.cpp.o
Compiling .pio\build\melzi\src\src\sd\SdBaseFile.cpp.o
Compiling .pio\build\melzi\src\src\sd\SdFatUtil.cpp.o
Compiling .pio\build\melzi\src\src\sd\SdFile.cpp.o
Compiling .pio\build\melzi\src\src\sd\SdVolume.cpp.o
Compiling .pio\build\melzi\src\src\sd\cardreader.cpp.o
Linking .pio\build\melzi\firmware.elf
c:/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: .pio\build\melzi\firmware.elf section `.text' will not fit in region `text'
c:/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: region `text' overflowed by 8114 bytes
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\melzi\firmware.elf] Error 1
========================================================================================= [FAILED] Took 22.88 seconds =========================================================================================

Environment    Status    Duration
-------------  --------  ------------
melzi          FAILED    00:00:22.876
==================================================================================== 1 failed, 0 succeeded in 00:00:22.876 ==================================================================================== 

 *  터미널 프로세스 "C:\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'melzi'"이(가) 종료되었습니다(종료 코드: 1). 
 *  터미널이 작업에서 다시 사용됩니다. 닫으려면 아무 키나 누르세요. 

 *  Executing task: C:\.platformio\penv\Scripts\platformio.exe run --environment melzi 

Processing melzi (board: sanguino_atmega1284p; platform: atmelavr@~3.4; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/sanguino_atmega1284p.html
PLATFORM: Atmel AVR (3.4.0) > Sanguino ATmega1284p (16MHz)
HARDWARE: ATMEGA1284P 16MHz, 16KB RAM, 124KB Flash
DEBUG: Current (simavr) On-board (simavr)
PACKAGES:
 - framework-arduino-avr @ 5.1.0
 - toolchain-atmelavr @ 1.70300.191015 (7.3.0)
Converting Marlin.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 6 compatible libraries
Scanning dependencies...
Dependency Graph
|-- U8glib-HAL @ 0.5.2
|   |-- Wire @ 1.0
|   |-- SPI @ 1.0
|-- SPI @ 1.0
|-- Wire @ 1.0
Building in release mode
Compiling .pio\build\melzi\src\src\HAL\AVR\HAL.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\HAL_SPI.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\MarlinSerial.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\Servo.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\eeprom.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\fast_pwm.cpp.o
Compiling .pio\build\melzi\src\src\HAL\AVR\u8g_com_HAL_AVR_sw_spi.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\Delay.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\HAL.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\MinSerial.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\eeprom_api.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\esp_wifi.cpp.o
Compiling .pio\build\melzi\src\src\HAL\shared\servo.cpp.o
Compiling .pio\build\melzi\src\src\MarlinCore.cpp.o
Compiling .pio\build\melzi\src\src\core\serial.cpp.o
Compiling .pio\build\melzi\src\src\core\utility.cpp.o
Compiling .pio\build\melzi\src\src\feature\babystep.cpp.o
Compiling .pio\build\melzi\src\src\feature\bedlevel\abl\bbl.cpp.o
Compiling .pio\build\melzi\src\src\feature\bedlevel\bedlevel.cpp.o
Compiling .pio\build\melzi\src\src\feature\bltouch.cpp.o
Compiling .pio\build\melzi\src\src\gcode\bedlevel\G42.cpp.o
Compiling .pio\build\melzi\src\src\gcode\bedlevel\M420.cpp.o
Compiling .pio\build\melzi\src\src\gcode\bedlevel\abl\G29.cpp.o
Compiling .pio\build\melzi\src\src\gcode\bedlevel\abl\M421.cpp.o
Compiling .pio\build\melzi\src\src\gcode\calibrate\G28.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M200-M205.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M220.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M221.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M301.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M302.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M309.cpp.o
Compiling .pio\build\melzi\src\src\gcode\config\M92.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M108_M112_M410.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M111.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M120_M121.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M17_M18_M84.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M211.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M280.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M400.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M80_M81.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M85.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M993_M994.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M997.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\M999.cpp.o
Compiling .pio\build\melzi\src\src\gcode\control\T.cpp.o
Compiling .pio\build\melzi\src\src\gcode\eeprom\M500-M504.cpp.o
Compiling .pio\build\melzi\src\src\gcode\feature\digipot\M907-M910.cpp.o
Compiling .pio\build\melzi\src\src\gcode\gcode.cpp.o
Compiling .pio\build\melzi\src\src\gcode\gcode_d.cpp.o
Compiling .pio\build\melzi\src\src\gcode\geometry\G92.cpp.o
Compiling .pio\build\melzi\src\src\gcode\geometry\M206_M428.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M110.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M113.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M114.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M115.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M118.cpp.o
Compiling .pio\build\melzi\src\src\gcode\host\M119.cpp.o
Compiling .pio\build\melzi\src\src\gcode\lcd\M0_M1.cpp.o
Compiling .pio\build\melzi\src\src\gcode\lcd\M117.cpp.o
Compiling .pio\build\melzi\src\src\gcode\lcd\M145.cpp.o
Compiling .pio\build\melzi\src\src\gcode\motion\G0_G1.cpp.o
Compiling .pio\build\melzi\src\src\gcode\motion\G2_G3.cpp.o
Compiling .pio\build\melzi\src\src\gcode\motion\G4.cpp.o
Compiling .pio\build\melzi\src\src\gcode\motion\M290.cpp.o
Compiling .pio\build\melzi\src\src\gcode\parser.cpp.o
Compiling .pio\build\melzi\src\src\gcode\probe\G30.cpp.o
Compiling .pio\build\melzi\src\src\gcode\probe\M401_M402.cpp.o
Compiling .pio\build\melzi\src\src\gcode\probe\M851.cpp.o
Compiling .pio\build\melzi\src\src\gcode\queue.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M1001.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M20.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M21_M22.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M23.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M24_M25.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M26.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M27.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M28_M29.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M30.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M32.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M33.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M34.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M524.cpp.o
Compiling .pio\build\melzi\src\src\gcode\sd\M928.cpp.o
Compiling .pio\build\melzi\src\src\gcode\stats\M31.cpp.o
Compiling .pio\build\melzi\src\src\gcode\stats\M75-M78.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M104_M109.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M105.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M106_M107.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M140_M190.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M141_M191.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M155.cpp.o
Compiling .pio\build\melzi\src\src\gcode\temp\M303.cpp.o
Compiling .pio\build\melzi\src\src\gcode\units\M82_M83.cpp.o
Compiling .pio\build\melzi\src\src\inc\Warnings.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\lcdprint_u8g.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\marlinui_DOGM.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\status_screen_DOGM.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\status_screen_lite_ST7920.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_ssd1306_sh1106_128x64_I2C.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_ssd1309_12864.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_st7565_64128n_HAL.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_st7920_128x64_HAL.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_tft_upscale_from_128x64.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_dev_uc1701_mini12864_HAL.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\u8g_fontutf8.cpp.o
Compiling .pio\build\melzi\src\src\lcd\dogm\ultralcd_st7920_u8glib_rrd_AVR.cpp.o
Compiling .pio\build\melzi\src\src\lcd\extui\ui_api.cpp.o
Compiling .pio\build\melzi\src\src\lcd\fontutils.cpp.o
Compiling .pio\build\melzi\src\src\lcd\lcdprint.cpp.o
Compiling .pio\build\melzi\src\src\lcd\marlinui.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_advanced.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_configuration.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_game.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_info.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_main.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_media.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_mixer.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_motion.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_probe_offset.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_temperature.cpp.o
Compiling .pio\build\melzi\src\src\lcd\menu\menu_tune.cpp.o
Compiling .pio\build\melzi\src\src\libs\buzzer.cpp.o
Compiling .pio\build\melzi\src\src\libs\numtostr.cpp.o
Compiling .pio\build\melzi\src\src\libs\stopwatch.cpp.o
Compiling .pio\build\melzi\src\src\libs\vector_3.cpp.o
Compiling .pio\build\melzi\src\src\module\endstops.cpp.o
Compiling .pio\build\melzi\src\src\module\motion.cpp.o
Compiling .pio\build\melzi\src\src\module\planner.cpp.o
Compiling .pio\build\melzi\src\src\module\probe.cpp.o
Compiling .pio\build\melzi\src\src\module\servo.cpp.o
Compiling .pio\build\melzi\src\src\module\settings.cpp.o
Compiling .pio\build\melzi\src\src\module\stepper.cpp.o
Compiling .pio\build\melzi\src\src\module\stepper\indirection.cpp.o
Compiling .pio\build\melzi\src\src\module\temperature.cpp.o
Compiling .pio\build\melzi\src\src\module\tool_change.cpp.o
Compiling .pio\build\melzi\src\src\sd\Sd2Card.cpp.o
Compiling .pio\build\melzi\src\src\sd\SdBaseFile.cpp.o
Compiling .pio\build\melzi\src\src\sd\SdFatUtil.cpp.o
Compiling .pio\build\melzi\src\src\sd\SdFile.cpp.o
Compiling .pio\build\melzi\src\src\sd\SdVolume.cpp.o
Compiling .pio\build\melzi\src\src\sd\cardreader.cpp.o
Linking .pio\build\melzi\firmware.elf
lto1.exe: internal compiler error: in read_cgraph_and_symbols, at lto/lto.c:2758
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
lto-wrapper.exe: fatal error: avr-g++ returned 1 exit status
compilation terminated.
c:/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\melzi\firmware.elf] Error 1
========================================================================================= [FAILED] Took 19.38 seconds =========================================================================================

Environment    Status    Duration
-------------  --------  ------------
melzi          FAILED    00:00:19.383
==================================================================================== 1 failed, 0 succeeded in 00:00:19.383 ==================================================================================== 

 *  터미널 프로세스 "C:\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'melzi'"이(가) 종료되었습니다(종료 코드: 1). 
 *  터미널이 작업에서 다시 사용됩니다. 닫으려면 아무 키나 누르세요. 

 
Processing melzi (board: sanguino_atmega1284p; platform: atmelavr@~3.4; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/sanguino_atmega1284p.html
PLATFORM: Atmel AVR (3.4.0) > Sanguino ATmega1284p (16MHz)
HARDWARE: ATMEGA1284P 16MHz, 16KB RAM, 124KB Flash
DEBUG: Current (simavr) On-board (simavr)
PACKAGES:
 - framework-arduino-avr @ 5.1.0
 - toolchain-atmelavr @ 1.70300.191015 (7.3.0)
Converting Marlin.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 6 compatible libraries
Scanning dependencies...
Dependency Graph
|-- U8glib-HAL @ 0.5.2
|   |-- Wire @ 1.0
|   |-- SPI @ 1.0
|-- SPI @ 1.0
|-- Wire @ 1.0
Building in release mode
Compiling .pio\build\melzi\src\src\inc\Warnings.cpp.o
Linking .pio\build\melzi\firmware.elf
c:/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: .pio\build\melzi\firmware.elf section `.text' will not fit in region `text'
c:/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: region `text' overflowed by 7256 bytes
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\melzi\firmware.elf] Error 1
========================================================================================== [FAILED] Took 8.86 seconds ==========================================================================================

Environment    Status    Duration
-------------  --------  ------------
melzi          FAILED    00:00:08.862
==================================================================================== 1 failed, 0 succeeded in 00:00:08.862 ==================================================================================== 

 *  터미널 프로세스 "C:\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'melzi'"이(가) 종료되었습니다(종료 코드: 1). 
 *  터미널이 작업에서 다시 사용됩니다. 닫으려면 아무 키나 누르세요. 
`

### Bug Timeline

It happened after I modified the bl touch code.

### Expected behavior

I thought that the firmware with bl touch would build successfully, and I was planning to upload this firmware to my ender3.

### Actual behavior

Build failed with error in firmware.elf

### Steps to Reproduce

1:Load example setup into ender 3, 2:uncoment #define BLTOUCH,
3:uncoment #define AUTO_BED_LEVELING_BILINEAR, 4: uncoment #define Z_SAFE_HOMING 5:bulid firmware to melzi

### Version of Marlin Firmware

2.1.1

### Printer model

Creality Ender 3 Pro

### Electronics

install bltouch

### Add-ons

bltouch

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/9527414/Marlin.zip)

**Comment by EvilGremlin** [comment]
This is not a bug, your build turns out 7kB bigger than you have in the chip. You must disable some (a lot of) features to fit in. starting with bootscreen and other fancy stuff

**Comment by EvilGremlin** [comment]
for reference: https://github.com/MarlinFirmware/Marlin/compare/bugfix-2.1.x...EvilGremlin:Marlin:bugfix-2.1-testmelzi

**Comment by ellensp** [comment]
you have a 12 year old microprocessor with 128k of flash. 

You cannot enable any extra options or it will not fit (without disabling something else) 

region `text' overflowed by 7256 bytes, means the generated firmware is 7256 bytes to large.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by Student-Jasons** [comment]
Thanks, I'll fix it
