### ISSUE TITLE
[BUG] #24737 causes printer moves to become very slow

### ISSUE THREAD

**Issue by rondlh** [MarlinFirmware/Marlin#24769]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Printer moves become very slow (X, Y and Z), I can visually see the deceleration happening.

### Bug Timeline

20202 September 14th

### Expected behavior

Deceleration as before

### Actual behavior

Deceleration are very slow, I'm not sure about acceleration, but they seem fine.

### Steps to Reproduce

1. Do a bed probing, then the slowdown becomes very obvious

### Version of Marlin Firmware

Latest bugfix (September 16th 2022)

### Printer model

Custom

### Electronics

MKS SGEN_L V2.0 (LPC1769)

### Add-ons

BTT TFT35 V3

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Other (explain below)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Host is the BTT TFT35 V3.

I managed to trace back this issue to the code change in planner.cpp #24737

This code seems to cause the problem: (planner.cpp)
  float inverse_accel = 0.0f;
  if (accel != 0) {
    const float inverse_accel = 1.0f / accel,
    half_inverse_accel = 0.5f * inverse_accel,

After the "if", inverse_accel = 0.0f. The calculated value in the "if" is not used.

So it should probably be:
  if (accel != 0) {
    inverse_accel = 1.0f / accel;
    const float half_inverse_accel = 0.5f * inverse_accel,

Which solves this issue.

**Comment by XDA-Bam** [comment]
Please upload your `Configuration.h` and `Configuration_adv.h`.

**Comment by rondlh** [comment]
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/9592489/Configuration_adv.zip)

Check the declaration of "inverse_accel", it is declared twice (around line 802 in planner.cpp), once outside the "if" and once inside. The value calculated inside the "if" will revert back to 0.0f after the if statement, causing issues for user that have S_CURVE_ACCELERATION enabled, which uses the value of "inverse_accel".

**Comment by thisiskeithb** [comment]
This should now be fixed in https://github.com/MarlinFirmware/Marlin/commit/1e525c597699536d3185dfc92b3066bc6b4ef695
