### ISSUE TITLE
Second NEOPIXEL2 LED stripe not compilable with NEO_RGBW

### ISSUE THREAD

**Issue by feuerwasser85** [MarlinFirmware/Marlin#24765]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Marlin doesn't compile in VSC and Auto Build Marlin. I need to have the first LED strip to be the three LEDs from my BTT mini 12864 LCD screen so i want to setup my second LED strip as a lightbar with SK6812 LEDs which are RGBW. However when i try to configure this setup in auto build marlin it doesn't compile. Error log in the bottom.
My configuration.h code:

// Support for Adafruit NeoPixel LED driver
#define NEOPIXEL_LED
#if ENABLED(NEOPIXEL_LED)
  #define NEOPIXEL_TYPE           NEO_RGB // NEO_GRBW, NEO_RGBW, NEO_GRB, NEO_RBG, etc.
                                          // See https://github.com/adafruit/Adafruit_NeoPixel/blob/master/Adafruit_NeoPixel.h
  #define NEOPIXEL_PIN                PB8 // LED driving pin
  #define NEOPIXEL2_TYPE         NEO_RGBW
  #define NEOPIXEL2_PIN               PA8
  #define NEOPIXEL_PIXELS               3 // Number of LEDs in the strip. (Longest strip when NEOPIXEL2_SEPARATE is disabled.)
  #define NEOPIXEL_IS_SEQUENTIAL          // Sequential display for temperature change - LED by LED. Disable to change all LEDs at once.
  #define NEOPIXEL_BRIGHTNESS         127 // Initial brightness (0-255)
  #define NEOPIXEL_STARTUP_TEST           // Cycle through colors at startup

  // Support for second Adafruit NeoPixel LED driver controlled with M150 S1 ...
  #define NEOPIXEL2_SEPARATE
  #if ENABLED(NEOPIXEL2_SEPARATE)
    #define NEOPIXEL2_PIXELS           15 // Number of LEDs in the second strip
    #define NEOPIXEL2_BRIGHTNESS      127 // Initial brightness (0-255)
    #define NEOPIXEL2_STARTUP_TEST        // Cycle through colors at startup
  #else
    //#define NEOPIXEL2_INSERIES          // Default behavior is NeoPixel 2 in parallel
  #endif

  // Use some of the NeoPixel LEDs for static (background) lighting
  //#define NEOPIXEL_BKGD_INDEX_FIRST   0 // Index of the first background LED
  //#define NEOPIXEL_BKGD_INDEX_LAST    5 // Index of the last background LED
  //#define NEOPIXEL_BKGD_COLOR { 255, 255, 255, 0 }  // R, G, B, W
  //#define NEOPIXEL_BKGD_ALWAYS_ON       // Keep the backlight on when other NeoPixels are off
#endif

### Bug Timeline

New Bug

### Expected behavior

The firmware should compile with two separate NEOPIXEL setups on different Types (RGB/RGBW)

### Actual behavior

it doesn't compile. Error in the bottom.

### Steps to Reproduce

1. Use the configuration.h code in the description
2. Use auto build marlin in vsc
3. build with STM32F103RC_btt_512K

### Version of Marlin Firmware

2.1.1

### Printer model

Creality Ender 5 Plus

### Electronics

BTT SKR mini E3 v2.0

### Add-ons

BLtouch3.1, Biqu H2 v2.0, SK6812 LED Strip, BTT mini 12864 LCD

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

``In file included from Marlin\src\feature\leds\../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\feature\leds\../../inc/MarlinConfig.h:28,
                 from Marlin\src\feature\leds\leds.cpp:27:
Marlin\src\feature\leds\leds.cpp: In static member function 'static void LEDLights2::set_color(const LEDColor&)':
Marlin\src\feature\leds\leds.cpp:202:97: error: 'const LEDColor' {aka 'const struct LEDColor'} has no member named 'w'
  202 |                             : neo2.Color(incol.r, incol.g, incol.b OPTARG(HAS_WHITE_LED2, incol.w));
      |                                                                                                 ^
Marlin\src\feature\leds\../../inc/../core/macros.h:621:26: note: in definition of macro 'THIRD'
  621 | #define THIRD(a,b,c,...) c
      |                          ^
Marlin\src\feature\leds\../../inc/../core/macros.h:248:37: note: in expansion of macro '_OPTARG'
      |                                     ^
Marlin\src\feature\leds\../../inc/../core/macros.h:247:29: note: in expansion of macro '___TERN'
  247 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
      |                             ^~~~~~~
Marlin\src\feature\leds\../../inc/../core/macros.h:246:29: note: in expansion of macro '__TERN'
  246 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
      |                             ^~~~~~
Marlin\src\feature\leds\../../inc/../core/macros.h:245:29: note: in expansion of macro '_TERN'
  245 | #define TERN_(O,A)          _TERN(_ENA_1(O),,A)     // OPTION ? 'A' : '<nul>'
      |                             ^~~~~
Marlin\src\feature\leds\../../inc/../core/macros.h:253:29: note: in expansion of macro 'TERN_'
  253 | #define OPTARG(O,A...)      TERN_(O,DEFER4(_OPTARG)(A))
      |                             ^~~~~
Marlin\src\feature\leds\leds.cpp:202:68: note: in expansion of macro 'OPTARG'
  202 |                             : neo2.Color(incol.r, incol.g, incol.b OPTARG(HAS_WHITE_LED2, incol.w));
      |                                                                    ^~~~~~
*** [.pio\build\STM32F103RE_btt\src\src\feature\leds\leds.cpp.o] Error 1``

**Comment by ellensp** [comment]
Compile fine on bugfix 2.1.x
