### ISSUE TITLE
[HELP] HOW TO : Pause host or SD with idle machine (To do all I want , or repair nozzle, and resume print when all is ok)

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#24777]
Hi , I need to pause the machine , but without PROMPT or LOCKED SCREEN, I need to move carriage , move axis and extruders to repair  while paused.
For me PAUSE = PAUSE  and not ' you are forced to unload and reload and resume or click or anything useless'
G27 don't stop planner and print not stopped
M600  force unload/reload +  locked screen
M125 Locked screen and button just resume
M25 only sd 
Others need ' wait_for_user' then the knob and screen are locked

For the moment the only PAUSE ' really pause ' is  G4 Sxxxxxx , I make a G4 S600 and I have 10 minutes of tranquility, all the lcd menus are available and i can do all is possible .

Do you have idea to make something like a 'pause ' with lcd available and possiblity to resume by lcd/gcode
Or do I have to create it  ?
Thks

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
