### ISSUE TITLE
[FR] Incremental Filament Sensor

### ISSUE THREAD

**Issue by matzejo** [MarlinFirmware/Marlin#24818]
### Is your feature request related to a problem? Please describe.

The sense of the Filament sensor is to detect a broken Filament. But this will work only in one case: When the break is before the sensor. Then the Filament runout will detected.
If the Filament breaks behind nothing will be detected.

### Are you looking for hardware support?

Replace the microswitch with an incremental sensor as used in a computer mouse for the wheel.
You can still use the same pins on the board. Just count the signals.

### Describe the feature you want

If you count the Signals on the Filament sensor you are able to detect a brake before and after the sensor. You can also detect underextrusion and try to compensate (higher nozzle temp or slower print speed or push a failure message etc.)

**Comment by ellensp** [comment]
already have this

```
  #ifdef FILAMENT_RUNOUT_DISTANCE_MM
    // Enable this option to use an encoder disc that toggles the runout pin
    // as the filament moves. (Be sure to set FILAMENT_RUNOUT_DISTANCE_MM
    // large enough to avoid false positives.)
    //#define FILAMENT_MOTION_SENSOR
  #endif
```
