### ISSUE TITLE
Enable EEPROM disable extruder motor

### ISSUE THREAD

**Issue by tmeghe** [MarlinFirmware/Marlin#2484]
Hi,

I've already seen several issues opened that describe the same problem I have but I didn't found any answer to that.

When I enable EEPROM for tweaking Z-OFFSET the extruder motor "automagically" disable itself. I don't understand why. However, when I reset the EEPROM (M502) the problem disappear. The problem appears again when I get the status of the EEPROM (M501).

What can I do about it ?

Thank you.

**Comment by clefranc** [comment]
Hi @tmeghe Which version of Marlin are you using?

**Comment by tmeghe** [comment]
Hi @clefranc I'm using the latest one (release branch) 1.0.2

**Comment by clefranc** [comment]
@tmeghe Are you using the M206 command?

**Comment by tmeghe** [comment]
@clefranc no I'm not using it. However, we didn't know the "real" usage of this command and we use a Z-Probe inductive sensor for auto leveling.

**Comment by clefranc** [comment]
@tmeghe Can you try to do a M500 after the M502? Then proceed with the adjustment, followed by a M500.

**Comment by gleeroy** [comment]
Hi @clefranc  i working with Thomas on this issue.
The commands M500 & M502  works, but if i want check eeprom with M501 command for adjust offset Z, the extruder motor is disabled when i make this command. 

if i disable EEPROM_SETTING and CHITHCAT no problem, but i wont everytime  modify configuration.h file.

**Comment by AnHardt** [comment]
@gleeroy 
Whe you use M500, M502, M501 with EEPROM enabled following will happen:
- When booting the content of the EEPROM is read into the memory. (Same as M501)
- M500 will store the content of the memory into the EEPROM. (Nothing changed)
- M502 reads in the default configuration into the memory. (All is working as expected)
- M501 reads the contents of the EEPROM into the memory. (Same state as after boot)

What you want is:
- boot. Read from EEPROM.
- M502 read in defaults from config.
- M500 store to EEPROM.

Now M501 reads in the updated EEPROM content and everything should work well.

Now you can adjust some values.
Then write them to the EEPROM. (M500)

At the next reboot the updated contents of the EEPROM will be read in again.

**Comment by AnHardt** [comment]
@gleeroy 
Now you can adjust some values.
Than write them to the EEPROM. (M500)

At the next reboot the updated contend of the EEPROM will be read in again.

**Comment by gleeroy** [comment]
@AnHardt 
If i try your command

"boot. Read from EEPROM.
M502 read in defaults from config.
M500 store to EEPROM.
Now M501 reads in the updated EEPROM content and everything should work well."

After the M501 reads in the updated eeprom, extruder motor is disabled. And after reboot also, i have excecut M502.

I want is:

boot. Read from eprom
M501 check offset Z in eeprom
M851 Z-(value)  change offset z probe
M500 store eeprom

**Comment by tonnico** [comment]
Isn't it M503 to check the actual values?!?

I'm doing that always like this:
check actual values with M503
change with M851 Z-xxx
store with M500
done.

**Comment by AnHardt** [comment]
Is the extruder motor not disabled at any time?

**Comment by gleeroy** [comment]
it's works! with M503 for read eeprom.
M501 always doesn't work, but if M503 works i'm happy. 
Thank you @Wurstnase 

@AnHardt  i don't understand your question!

**Comment by tonnico** [comment]
@gleeroy M503 doesn't read the EEPROM. It reads the actual values you've set.

**Comment by tmeghe** [comment]
Thanks folks for your answers !
Cheers,

**Comment by gleeroy** [comment]
@Wurstnase 
perfect! i just want read actual value. 
But why i use M501 command extruder motor is disabled?

**Comment by gleeroy** [comment]
When i connect my board at Pronterface, i m obliged execute M502 after boot, if not extruder motor not work.

**Comment by thinkyhead** [comment]
@gleeroy I'm trying to narrow down which values might differ, and which might affect extruder movement. Do you see any difference in the `volumetric_enabled` setting (in the LCD menu or from `M503` in the **Filament settings: M200** output) when you boot or use `M501`, versus when you use `M502`?

**Comment by gleeroy** [comment]
@thinkyhead 
i don't see  volumetric_enabled or M200

```
Connecting...
start
Printer is now online.
echo:Marlin1.0.0
echo: Last Updated: Jul 21 2015 13:51:36 | Author: (by PL, Marlin_BMK)
Compiled: Jul 21 2015
echo: Free Memory: 5126  PlannerBufferBytes: 1232
echo:Stored settings retrieved
echo:Steps per unit:

>>> M503
SENDING:M503
echo:Steps per unit:
echo:  M92 X80.00 Y80.00 Z3200.00 E178.42
echo:Maximum feedrates (mm/s):
echo:  M203 X300.00 Y300.00 Z8.00 E25.00
echo:Maximum Acceleration (mm/s2):
echo:  M201 X4000 Y4000 Z30 E10000
echo:Acceleration: S=acceleration, T=retract acceleration
echo:  M204 S3000.00 T3000.00
echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
echo:  M205 S0.00 T0.00 B20000 X15.00 Z0.40 E5.00
echo:Home offset (mm):
echo:  M206 X0.00 Y0.00 Z0.00
echo:PID settings:
echo:   M301 P35.18 I3.46 D89.35
echo:Z-Probe Offset (mm):
echo:   M851 Z-1.56

>>> M501
SENDING:M501
echo:Stored settings retrieved
echo:Steps per unit:
echo:  M92 X80.00 Y80.00 Z3200.00 E178.42
echo:Maximum feedrates (mm/s):
echo:  M203 X300.00 Y300.00 Z8.00 E25.00
echo:Maximum Acceleration (mm/s2):
echo:  M201 X4000 Y4000 Z30 E10000
echo:Acceleration: S=acceleration, T=retract acceleration
echo:  M204 S3000.00 T3000.00
echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
echo:  M205 S0.00 T0.00 B20000 X15.00 Z0.40 E5.00
echo:Home offset (mm):
echo:  M206 X0.00 Y0.00 Z0.00
echo:PID settings:
echo:   M301 P35.18 I3.46 D89.35
echo:Z-Probe Offset (mm):
echo:   M851 Z-1.56

>>> M502
SENDING:M502
echo:Hardcoded Default Settings Loaded

>>> M500
SENDING:M500
echo:Settings Stored
```

**Comment by thinkyhead** [comment]
> `echo:Marlin1.0.0`
> `echo: Last Updated: Jul 21 2015 13:51:36 | Author: (by PL, Marlin_BMK)`

@gleeroy I see that you are using an old version of Marlin, perhaps from another fork. In the past there have been problems with the EEPROM read/write code, but those have since been fixed. So, unless you're totally dependent on the fork you are using (because of some custom feature not in the main project), you should upgrade to Marlin 1.0.2 or get the latest (1.0.3 dev) code, both of which have full backward compatibility with the same hardware as "1.0.0." Unfortunately, we can't really support older forked versions of Marlin code.

**Comment by thinkyhead** [comment]
> i don't see volumetric_enabled or M200

I see from the Marlin code that there isn't any `M200` in the output if `volumetric_enabled` is `false`, but in the latest Marlin it will print **Filament settings: Disabled**. (I might patch that, and make it output `M200 D0` in that case.)

**Comment by gleeroy** [comment]
@thinkyhead 
I try with lasted version, and it's fine! not problem now. I'm sorry, I do not see why I was working with this version, thank you for all your help.
What is the M200 control?

**Comment by thinkyhead** [comment]
@gleeroy It makes me think there might have been a buffer overrun or something stepping on a setting. Anyway, very glad to hear it's working now.

> What is the M200 control?

`M200` sets the filament diameter for a single extruder (the active one by default) and (at the same time) sets E axis units to cubic millimeters (for all extruders). `M200 D0` turns off volumetric units (for all extruders).

**Comment by gleeroy** [comment]
thanks a lot everybody!
