### ISSUE TITLE
[BUG] Baby Step dont work with Delta Printer

### ISSUE THREAD

**Issue by roscocoltrane** [MarlinFirmware/Marlin#24849]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Baby stepping wont work unless you stick to standard values in config.

#define BABYSTEP_MILLIMETER_UNITS       // Specify BABYSTEP_MULTIPLICATOR_(XY|Z) in mm instead of micro-steps
  #define BABYSTEP_MULTIPLICATOR_Z  0.01     // (steps or mm) Steps or millimeter distance for each Z babystep 
  #define BABYSTEP_MULTIPLICATOR_XY 0.01    // (steps or mm) Steps or millimeter distance for each XY babystep
or 
#define BABYSTEP_MILLIMETER_UNITS       // Specify BABYSTEP_MULTIPLICATOR_(XY|Z) in mm instead of micro-steps
  #define BABYSTEP_MULTIPLICATOR_Z  0.005     // (steps or mm) Steps or millimeter distance for each Z babystep 
  #define BABYSTEP_MULTIPLICATOR_XY 0.005   // (steps or mm) Steps or millimeter distance for each XY babystep

but it works with: 
#define BABYSTEP_MILLIMETER_UNITS       // Specify BABYSTEP_MULTIPLICATOR_(XY|Z) in mm instead of micro-steps
  #define BABYSTEP_MULTIPLICATOR_Z  0.1     // (steps or mm) Steps or millimeter distance for each Z babystep 
  #define BABYSTEP_MULTIPLICATOR_XY 0.1    // (steps or mm) Steps or millimeter distance for each XY babystep

Config compiles fine, but when you try and lower or raise the z-offset on display with the knob the value does not change nor does the stepper motors.

### Bug Timeline

No idea

### Actual behavior

nothing happend

### Version of Marlin Firmware

Marlin-bugfix-2.1.x

### Printer model

Anycubic Kossel Delta Linear Plus

### Electronics

SKR v1.3

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

Same as my slicer

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/9740464/config.zip)

**Comment by ellensp** [comment]
This is what you have

#define MIN_STEPS_PER_SEGMENT 1
So anything less than 1 step will not move

Steps per mm = 80  

0.005 * 80  =  0.4  of a step, this will not move  
0.01  * 80   =  0.8  of a step, this will not move
0.1 * 80      =  8 steps this will move

The minimum you can set is 0.0125  = 1 step

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
