### ISSUE TITLE
[BUG] MMU2S with Octopus Pro board not responding

### ISSUE THREAD

**Issue by yannick-alch** [MarlinFirmware/Marlin#24857]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi,

I want to use the Prusa MMU2S with the BTT Octopus Pro board by connecting it on the TFT port.
I am using Marlin 2.1
When I start my printer, after few seconds I have "MMU not responding - DISABLED" message...
In the Configuration_Adv.h file I define #MMU2_SERIAL_PORT 1 to use on the TFT port.

I know the communication between Octopus Pro and the Prusa MMU working because I can send a soft reset to the MMU and it's working fine, but that's all.

### Expected behavior

I want the MMU responding with the Octopus Pro board

### Actual behavior

Octopus Pro board did not receive the "start" message from the Prusa MMU and the I have the message "MMU not responding - DISABLED" message"

### Version of Marlin Firmware

Marlin 2.1

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

You will find my config files below.

Thanks for your reply.

![image](https://user-images.githubusercontent.com/59729079/194908138-292a3ac0-29e8-4506-980c-d7e338f1c4af.png)

[config.zip](https://github.com/MarlinFirmware/Marlin/files/9747410/config.zip)

**Comment by GMagician** [comment]
You may try to enable MMU2_DEBUG in mmu2.cpp to see if info may help

**Comment by yannick-alch** [comment]
> You may try to enable MMU2_DEBUG in mmu2.cpp to see if info may help

It's already enable in Configuration_Adv.cpp

**Comment by ellensp** [comment]
then how about a log ?

**Comment by yannick-alch** [comment]
> then how about a log ?

Which log do you want ? This is the only message I have...

**Comment by ellensp** [comment]
That is confusing then

You say "I know the communication between Octopus Pro and the Prusa MMU working because I can send a soft reset to the MMU and it's working fine"  but the error you list says its not communicating at all.

It should look like https://revilor.github.io/MMU2-Marlin/debugging.html

**Comment by yannick-alch** [comment]
![image](https://user-images.githubusercontent.com/59729079/195032307-a2cb7335-7b51-48d5-aefe-0913ba184dba.png)
My bad, I thought I activate MMU2_DEBUG...

This is what I have when I reset the board

**Comment by ellensp** [comment]
as I  said, not talking at all...  

So how have you wired this?  details, pin for pin...

**Comment by yannick-alch** [comment]
The wiring is like (from MMU to Octopus) :
```
Red to 5v
White (RX MMU) to pin PA9 (TX1 octopus)
Green (TX MMU) to pin PA10 (RX1 octopus)
Black shielded wire (GND MMU) to GND (octopus)
Black (reset MMU) to RST (reset pin on octopus)

```
This is the connector on octopus board
![IMG_20221011_101032392](https://user-images.githubusercontent.com/59729079/195037106-257d581c-2117-4717-8325-2e2a5d440468.jpg)

This is the connector on MMU
![IMG_20221011_101000976](https://user-images.githubusercontent.com/59729079/195037213-6de41acc-b134-4597-8513-a5099e093798.jpg)


Hre is the pinmap of the octopus board
![btt_octopus_pro_1 0_pins](https://user-images.githubusercontent.com/59729079/195037282-bb05bcdc-8b31-4157-bc2e-6811b0f2700c.png)

**Comment by ellensp** [comment]
Looks ok. 

In your config you have 
#include "defines.h"
#include "config.h"
#include "change_tool.h"

what is in these files?

**Comment by yannick-alch** [comment]
> Looks ok.
> 
> In your config you have #include "defines.h" #include "config.h" #include "change_tool.h"
> 
> what is in these files?

I have different printer, it's juste varaible for each machine, lige drivers, size, position for tool changing...

**Comment by yannick-alch** [comment]
Is `#define MMU2_SERIAL_PORT 1` is correct with the TFT port ?

**Comment by ellensp** [comment]
According to circuit diagrams, yes

**Comment by yannick-alch** [comment]
Do you know if I can use another port ?

**Comment by yannick-alch** [comment]
I saw that RX1 and TX1 from TFT are the same for RJ11 connector...
Is there a way to disable RJ11 ?

**Comment by ellensp** [comment]
RJ11 is CAN1TX and CAN1RX  not TX1 RX1

**Comment by yannick-alch** [comment]
Ok thanks.
I know the MMU wprking fine because I use it with GTR V1.0 board.
I don't know why it's not working with the Octopus Pro board

**Comment by EvilGremlin** [comment]
maybe MMU rx/tx labels are wrong? swap wires?

**Comment by flynhigh20** [comment]
Having same issues and litteraly have on tft plug aswell but will not respond, worked fine in creality board, you get fixed...

**Comment by flynhigh20** [comment]
> Having same issues and litteraly have on tft plug aswell but will not respond, worked fine in creality board, you get fixed...

Mine is actually on uart2 the rpi connection using serail port 3 was working then stop maybe loose connection but ive canged nothing since
