### ISSUE TITLE
[FR] MMU2S with Octopus Pro board not responding

### ISSUE THREAD

**Issue by yannick-alch** [MarlinFirmware/Marlin#24856]
### Is your feature request related to a problem? Please describe.

Hi,

I want to use the Prusa MMU2S with the BTT Octopus Pro board by connecting it on the TFT port.
I am using Marlin 2.1
When I start my printer, after few seconds I have "MMU not responding - DISABLED" message...
In the Configuration_Adv.h file I define `#MMU2_SERIAL_PORT 1` to use on the TFT port.

I know the communication between Octopus Pro and the Prusa MMU working because I can send a soft reset to the MMU and it's working fine, but that's all.

### Describe the feature you want

You will find my config files below.

Thanks for your reply.

![image](https://user-images.githubusercontent.com/59729079/194908138-292a3ac0-29e8-4506-980c-d7e338f1c4af.png)

[config.zip](https://github.com/MarlinFirmware/Marlin/files/9747410/config.zip)

**Comment by thisiskeithb** [comment]
Please open a proper [Bug Report](https://github.com/MarlinFirmware/Marlin/issues/new?assignees=&labels=&template=bug_report.yml&title=%5BBUG%5D+%28bug+summary%29).
