### ISSUE TITLE
[BUG] Using 3 Z-motors, G34 Fails and nozzle crashes to bed

### ISSUE THREAD

**Issue by mattiras** [MarlinFirmware/Marlin#24868]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Using 3 Z-motors, G34 moves to first measuring point and starts to run towards the bed, but gives G34 failed error immediately and runs nozzle to the table and keeps trying to run the z-motors indefinitely.

G28 and G29 works as expected. Going back to Marlin 2.0.8.2 works. With 2 Z-motors works.

### Bug Timeline

Since 2.0.9.

### Expected behavior

a) G34 command to finish
b) When failing, all movement to stop.

### Actual behavior

Starts but in first measuring point outputs error and runs nozzle to the bed and keeps trying to run the z-motors indefinitely.
Behavior is strange compared to successfull G34.

### Steps to Reproduce

1. uncomment Z_STEPPER_AUTO_ALIGN
2. use 3 Z-motors
3. Use command G34

### Version of Marlin Firmware

2.1.1

### Printer model

DIY coreXY

### Electronics

Ramps 1.4

### Add-ons

3xZ drivers A4988. Z2 on E1 slot, Z3 driver modded on top of Z1

### Bed Leveling

ABL Bilinear mesh

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[G34 failing.zip](https://github.com/MarlinFirmware/Marlin/files/9778965/G34.failing.zip)

**Comment by thinkyhead** [comment]
Does it help to set `Z_PROBE_LOW_POINT` to something like -10 ?

**Comment by mattiras** [comment]
> Does it help to set `Z_PROBE_LOW_POINT` to something like -10 ?

I tried that earlier and it had no effect.

**Comment by sjasonsmith** [comment]
Possibly the same issue as the following, but that reporter stopped replying to questions.
#24645

**Comment by mattiras** [comment]
Yes, I noticed that report when I was looking for any similar cases. But symptoms were so different, I did not see my problem quite fitting under that. My setup does not reboot and goes much further in process, and even notices something is wrong. But worst is, even after probing reported failing, it tries to dig the nozzle to table and beyond. I tested this by running the table down and fooling the G28 homing by triggering the probe manually. Then, executing G34, the table keeps running all the way back up,  ignoring the probe as I try to fool it again.

Of course, the root cause could be same bug but I would not yet combine these because there are differences.

Some observations:
Behaviour is also somehow different to successful G34 (with older code OR with 2 Z-motors). After homing, the Z goes up before moving to first measuring point and then starts to probe slow.
With 2.1.1 after homing, the probe goes straight t to corner and starts going down faster and in this point has reported failure all ready.

Also in the log, the Z values look abnormal.
`Probeprobe_down_to_z  X0.00 Y0.00 Z-1342177.25`
`SLOW Probe fail! - No trigger.`

Please see logs.
