### ISSUE TITLE
[BUG] Can't compile Ender 6 configuration with selected "DGUS_LCD_UI_RELOADED".

### ISSUE THREAD

**Issue by gad-ass** [MarlinFirmware/Marlin#24897]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Compiling Marlin with modified Ender 6 configuration (selecting **DGUS_LCD_UI_RELOADED** instead **DGUS_LCD_UI_ORIGIN**) is giving this error while compiling:

In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL_SPI.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:4222:6: error: #error "DGUS_LCD_UI_RELOADED requires a bed probe."
 4222 |     #error "DGUS_LCD_UI_RELOADED requires a bed probe."
      |      ^~~~~

Compiling with **DGUS_LCD_UI_ORIGIN** parameter is working correctly.

### Expected behavior

Compile *.bin file.

### Actual behavior

Giving error.

### Steps to Reproduce

Open Marlin 2.1.x in vs code, replace config files with config for Ender 6 for Marlin 2.1.x., change Display setting to DGUS_LCD_UI_RELOADED.

### Version of Marlin Firmware

Marlin bugfix-2.1.x (buxfix-2.0.x also is not working)

### Printer model

Ender 6

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/9812007/config.zip)

**Comment by thisiskeithb** [comment]
> #error "DGUS_LCD_UI_RELOADED requires a bed probe."
4222 | #error "DGUS_LCD_UI_RELOADED requires a bed probe."

You need a bed probe to use `DGUS_LCD_UI_RELOADED`.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
