### ISSUE TITLE
prepare_move_raw for non-Delta?

### ISSUE THREAD

**Issue by tonnico** [MarlinFirmware/Marlin#2489]
Is that right? I can't find prepare_move_raw for non-Deltas.

https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/Marlin_main.cpp#L1334

**Comment by thinkyhead** [comment]
Correct. The `prepare_move_raw` function exists only for the benefit of Delta. It does a "raw" linear move (which may be curved in cartesian space) instead of an interpolated move, which converts long moves into several short (raw) moves.

**Comment by tonnico** [comment]
This doesn't makes any problem because there is no

```
#ifndef DELTA
prepare_move_raw() {};
#endif
```

?

This function is called often in non Delta specific parts.

**Comment by AnHardt** [comment]
Ahh. The difference between G0 and G1 on "real" CNC machines.
These scary looking concave moves. Do we want them at all?

**Comment by thinkyhead** [comment]
> This function is called often in non Delta specific parts.

It is called only in blocks of code bounded by `#ifdef DELTA` or `#ifdef Z_PROBE_ALLEN_KEY`. The latter can only be enabled on a delta.

**Comment by thinkyhead** [comment]
> The difference between G0 and G1 on "real" CNC machines.

Rue the day when Marlin branches out into CNC. Still, it would be nice to be able to use `G0` / `G1` in the intended manner — if that means non-interpolated versus interpolated.

> These scary looking concave moves. Do we want them at all?

@AnHardt Not really, and there's no compelling reason to include them that I can imagine (except to optimize tower movement). We should be able to replace all calls to `prepare_move_raw` with `prepare_move`, or replace the two middle lines in `prepare_move_raw` with `if (!prepare_move_delta(destination)) return;` (which basically skips the call to `clamp_to_software_endstops`.)

**Comment by tonnico** [comment]
> It is called only in blocks of code bounded by #ifdef DELTA or #ifdef Z_PROBE_ALLEN_KEY. The latter can only be enabled on a delta.

Ah, now I see it. I saw some cartesian/corexy with an allen key for the leveling and thought this is also for them.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
