### ISSUE TITLE
[BUG] sd card does not start and lcd freezes

### ISSUE THREAD

**Issue by lipewww** [MarlinFirmware/Marlin#24890]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

A few months ago I decided to put Marlin on my Anet A6 printer, and since then I've never been able to use my sd card on the printer, I've had marlin since version 2.0.9.3, and since then it's never been fixed. When trying to start the card, the LCD freezes for about 10 seconds, then comes back as if nothing happened.

### Version of Marlin Firmware

2.0 or 2.1

### Printer model

Anet A6

### Bed Leveling

No Bed Leveling

### Host Software

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I formatted my computer and lost version 2.1 of the firmware that had some changes, but it didn't work anyway, I'll leave 2.0 available if you want to check it too
[Marlin-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/9800895/Marlin-2.0.x.zip)

**Comment by ellensp** [comment]
Please test the [`bugfix-2.1.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

Then provide the Configs for this version.

**Comment by lipewww** [comment]
> Please test the [`bugfix-2.1.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
> 
> Then provide the Configs for this version.

trust me, it's not resolved, I just lost the file to attach, it's on my printer.

**Comment by lipewww** [comment]
> Please test the [`bugfix-2.1.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.
> 
> Then provide the Configs for this version.

here is a configuration 2.1 bugfix
[config 2.1 bugfix.zip](https://github.com/MarlinFirmware/Marlin/files/9801175/config.2.1.bugfix.zip)

**Comment by ellensp** [comment]
bugfix is 02010200   this is several versions older at 02010000

**Comment by Andrzej220754** [comment]
Me also does not work in the new version. He sees the sd card after M21 only. Marlin 2.0.9 no problem

**Comment by ellensp** [comment]
Anet 10 has no sd detect pin. 
Will only know about sdcard when board is powered up with sd card in it, or on M21

**Comment by lipewww** [comment]
I just tested in the new version, nothing changes. here is the settings
[config 2.1.zip](https://github.com/MarlinFirmware/Marlin/files/9801987/config.2.1.zip)

**Comment by lipewww** [comment]
> Anet 10 has no sd detect pin. Will only know about sdcard when board is powered up with sd card in it, or on M21

I just tested in the new version, nothing changes. here is the settings

[config 2.1.zip](https://github.com/MarlinFirmware/Marlin/files/9803369/config.2.1.zip)

**Comment by calcdas** [comment]
Cards with tft that do not have the encoder do not open the sdcard browser. The problem is in the menu_media

**Comment by Andrzej220754** [comment]
I will try. Thank you

**Comment by calcdas** [comment]
I find it funny how they like to close the discussions, without solving the problems there are several with the same problem since they released the version with tft touch.
just one more note in extui dir has anycubic_chiron , see how it uses filenavigator to access sdcard files without needing encoder

**Comment by lipewww** [comment]
why don't you send some solution options? I've been unable to use an sd card for over 6 months.

**Comment by Andrzej220754** [comment]
I changed to 2.09
W dniu 2022-11-01 12:01:59 użytkownik lipewww ***@***.***> napisał:

 
why don't you send some solution options? I've been unable to use an sd card for over 6 months.
