### ISSUE TITLE
[BUG]  "Pasting "USART" and "-" does not give a valid preprocessing token"

### ISSUE THREAD

**Issue by T-SquaredProductions** [MarlinFirmware/Marlin#24905]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Arduino IDE spits out this error, after clearing all other errors:

"/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp: In instantiation of 'static void MarlinSerial<Cfg>::flushTX() [with Cfg = MarlinSerialCfg<255>]':
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:569:16:   required from here
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:524:12: error: no match for 'operator!' (operand type is 'const B_TXCx<255>')
     while (!B_TXC) sw_barrier();
            ^~~~~~
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:524:12: note: candidate: operator!(bool) <built-in>
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:524:12: note:   no known conversion for argument 1 from 'const B_TXCx<255>' to 'bool'
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:540:50: error: no match for 'operator!' (operand type is 'const B_TXCx<255>')
       while (tx_buffer.head != tx_buffer.tail || !B_TXC) {
                                                  ^~~~~~
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:540:50: note: candidate: operator!(bool) <built-in>
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:540:50: note:   no known conversion for argument 1 from 'const B_TXCx<255>' to 'bool'
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:543:9: error: could not convert 'MarlinSerial<MarlinSerialCfg<255> >::B_UDRE' from 'const B_UDREx<255>' to 'bool'
         if (B_UDRE) _tx_udr_empty_irq();
         ^~
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:551:50: error: no match for 'operator!' (operand type is 'const B_TXCx<255>')
       while (tx_buffer.head != tx_buffer.tail || !B_TXC) sw_barrier();
                                                  ^~~~~~
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:551:50: note: candidate: operator!(bool) <built-in>
/Users/[PATH]/Marlin-2.1 (Steel System)/Marlin/src/HAL/AVR/MarlinSerial.cpp:551:50: note:   no known conversion for argument 1 from 'const B_TXCx<255>' to 'bool'

exit status 1

Compilation error: pasting "USART" and "-" does not give a valid preprocessing token

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9824250/Configuration.zip)

### Expected behavior

I expected an Exit Status 0, with a complete verification of the code.

### Actual behavior

The IDE gives this error instead.

### Steps to Reproduce

[N/A]

### Version of Marlin Firmware

2.1

### Printer model

Prusa Variant

### Electronics

RAMPS 1.6

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
You have 
  #define MOTHERBOARD BOARD_RAMPS_14_EEB 

with

#define SERIAL_PORT -1

This is impossible!

-1 says use the chips on hardware cdc usb port

the mega2560 does not have such a port. it uses a usb to serial chip.  (ftdi, or ch340 etc)

SERIAL_PORT should be 0 on this controller.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
