### ISSUE TITLE
[FR] Request SETUP menu for all auto functions & Wizards

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#24909]
### Is your feature request related to a problem? Please describe.

The Marlin auto features & wizards are too separated & well hidden in some cases, new users can’t find them or don’t even know they’re there. Also it takes time to navigate to them deep inside the menu system. 
a single SETUP menu would improve things here. 

### Describe the feature you want

SETUP menu request. 

How about a quick simple customisable setup menu where all wizards & autotunes can be placed (duplicated or moved) inside a single menu in the root menu of Marlin. They can obviously still be in their current places but also in a single convenient menu at the front end. 

So we’d have UBL wizard, tramming wizard, probe offset wizard, auto Z align, MPC autotune & PID autotune all in a single handy place without having to navigate the whole menu system to find each on in their respective places. I know some are in the MOTION menu and are easy to find but I feel if they were all consolidated in a SETUP menu it would feel better I think. 

This would make using the auto setup features in the firmware so much faster & easier to use. 
it would be great if we could enable/disable the menu & customise its contents.

**Comment by ghost** [comment]
Saw you did this in the latest bugfix. Nice work thanks! 😉👍

**Comment by thisiskeithb** [comment]
> Saw you did this in the latest bugfix. Nice work thanks! 😉👍

OP also deleted their account, so this is resolved.
