### ISSUE TITLE
[BUG] ProUI: Parts of bootsplash rendered behind text

### ISSUE THREAD

**Issue by Matombo** [MarlinFirmware/Marlin#24916]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Parts of the bootsplash are rendered behind text, most note able in the main menu:

![IMG_20221022_132508](https://user-images.githubusercontent.com/9865923/197337273-e2fed5d5-6244-4fc0-95c3-041b9efaf774.jpg)

I have the DACAI LCD (the one using the "private" firmware folder)

### Expected behavior

The space behind text is a solid color.

### Actual behavior

Parts of the bootsplash are rendered behind text.

### Version of Marlin Firmware

2.1.1

### Printer model

Ender 3 V2

### Electronics

Mainboard 4.2.2 with GD32F303, DACAI LCD (the one using the "private" firmware folder)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9844253/Configuration.zip)

**Comment by Matombo** [comment]
Couldn't test bugfix branch as it will not boot.

Forget to add: Because of the GD chip, I have to use the maple target, otherwise Marlin will not boot as soon as I enable BL Touch.

**Comment by ellensp** [comment]
There are 3 known different types of this display
The original DWIN the first clone DACAI the second clone SWM32SRET5
Need to identify what one you have...
https://marlin.crc.id.au/forum/t/identifying-ender-3-v2-screen-versions/960

**Comment by Matombo** [comment]
I did in the Electronics section:
DACAI LCD (the one using the "private" firmware folder)

**Comment by Matombo** [comment]
I put it in a more prominent position.

**Comment by Infactionfreddy** [comment]
I have the same Problem on the same Display Typ.
On the DWIN_CREALITY_LCD_JYERSUI i have the Problem not but on the DWIN_LCD_PROUI.
There are parts of the boot logo that can be seen in the background of the text.

**Comment by Infactionfreddy** [comment]
And I used the BTT OCTOPUS v1.1 instead of the standard board.

**Comment by mriscoc** [comment]
That could be a font problem, try with https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display for Marlin change the icon set library.

**Comment by Infactionfreddy** [comment]
It works.
But your flash files are missing a couple of icons.
There are still a few small pixel errors, but only in the icons.
Tank for help.
![IMG_6398](https://user-images.githubusercontent.com/66081193/203127227-6706ae20-694f-481d-b49b-6cfaf44a5cd4.jpeg)
![IMG_6399](https://user-images.githubusercontent.com/66081193/203127237-e64a5ee3-f539-476e-b14b-ec4a30bd7405.jpeg)

**Comment by Matombo** [comment]
Self compiled marlin version only work for me when using this icon set: https://github.com/MarlinFirmware/Configurations/tree/import-2.1.x/config/examples/Creality/Ender-3%20V2/LCD%20Files
This icon set however breaks the ui for any precompiled marlin FW

**Comment by thisiskeithb** [comment]
> Self compiled marlin version only work for me when using this icon set

> This icon set however breaks the ui for any precompiled marlin FW

That is to be expected because you need to use the icon set that matches your firmware. They’re not backward / cross-compatible to other firmware versions.

> Mainboard 4.2.2 with GD32F303

> Couldn't test bugfix branch as it will not boot.

We do not support GD32 at this time, but we have https://github.com/MarlinFirmware/Marlin/discussions/24985 to track process.
