### ISSUE TITLE
Not Fixed after the merge of https://github.com/MarlinFirmware/Marlin/pull/22184

### ISSUE THREAD

**Issue by xorn** [MarlinFirmware/Marlin#24920]
The issue with mintemp showing up after power cycle/loading of setting is still happening. Not Fixed after the merge of https://github.com/MarlinFirmware/Marlin/pull/22184

_Originally posted by @CRCinAU in https://github.com/MarlinFirmware/Marlin/issues/22153#issuecomment-864705820_

**Comment by thisiskeithb** [comment]
Please fill out a proper [Bug Report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
