### ISSUE TITLE
[BUG] Double z mode with asymmetric Z-axis step

### ISSUE THREAD

**Issue by amxsa** [MarlinFirmware/Marlin#24929]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

[BUG] Double z mode with asymmetric Z-axis step

MKS GEN_L V2.1 ，Z2_SERIAL_TX_PIN  and Z2_SERIAL_RX_PIN not define ？
```
#define X_DRIVER_TYPE  TMC2209
#define Y_DRIVER_TYPE  TMC2209
#define Z_DRIVER_TYPE  TMC2209
#define Z2_DRIVER_TYPE TMC2209
#define E0_DRIVER_TYPE TMC2209
```

### Expected behavior

Double z mode, Z axis step symmetry

### Actual behavior

Double z mode with asymmetric Z-axis step

### Version of Marlin Firmware

marlin 2.1.1

### Printer model

MKS GEN_L V2.1

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9871987/Configuration.zip)

**Comment by amxsa** [comment]
![ae8df9de8170edca47f68b7cdc38eaff](https://user-images.githubusercontent.com/5416497/198085973-ff336a28-09e8-4532-be31-bd026f4c8e74.png)

In fact, the Z-axis is in uart mode, but the program prompts a TMC connection error

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
The uarts pins should auto allocated from the unused E, this is a bug...
The TMC error is probably a bad stepper driver.
