### ISSUE TITLE
[BUG] 3D touch doesn't stop Z Axis when homing

### ISSUE THREAD

**Issue by Sparkbleh** [MarlinFirmware/Marlin#24924]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

I got a 3d touch (Bltouch clone) and I wired it to my skr 1.3 board as the manufacturer designed. I set up marlin bugfix 2.0.x firmware and made all the necessary changes to use it. When I power on my printer it makes the self test which is a good sign. The lights come on (blue and red) and when I go on the bltouch menu I can deploy and stow the probe which is a good sign that the Servo is working fine. But when I auto home. The probe doesn't send a signal to the printer to stop and the nozzle crashes into the bed.

After a few tinkering I found that if I removed the Z min cable (3d touch cable) when I'm auto homing it sends a trigger signal to the printer which is weird. And I don't have a lot of experience with this so I have no idea what to do. 

### Bug Timeline

Once I started using the 3d touch

### Expected behavior

Z axis stops after triggering probe

### Actual behavior

Z axis crashes into bed

### Steps to Reproduce

1. Connect 3D touch wires.
2. Compiled firmware
3. Powered the printer on
4. Auto homed

### Version of Marlin Firmware

Marlin-Bugfix-2.0.x

### Printer model

DIY printer

### Electronics

SKR 1.3, TMC2208, 3d touch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Same as my slicer

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
