### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by classicrocker883** [MarlinFirmware/Marlin#24931]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I recieve this error
>src/src/module/stepper.cpp.o: In function `TFilamentMonitor<RunoutResponseDelayed, FilamentSensorDevice>::block_completed(PlannerBlock const*)':
/home/user/Documents/PlatformIO/Projects/Marlin/src/module/../feature/runout.h:124: warning: undefined reference to `FilamentSensorDevice::block_completed(PlannerBlock const*)'

in file --> **src/module/planner.h**
```
typedef struct PlannerBlock 
```
should this be returned back to `block_t` instead of PlannerBlock? i see no other reference to this struct with it labeled plannerblock, and at the end of the struct it is named `block_t` so i dont understand why it would be PlannerBlock.

this can be why some have experienced issues with Linear Advance not actually doing anything.

### Version of Marlin Firmware

bugfix-2.1.x most current

### Don't forget to include

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
Please update Subject
Please attach a config files to reproduce  this error
