### ISSUE TITLE
[FR] Add reverse sort of file names on SD

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#24937]
### Is your feature request related to a problem? Please describe.

Currently files could be sorted by name, with option recent FAT entry first. So it could be difficult find new file.

### Describe the feature you want

Some slicers (at least Prusa) allows add date/time at the file name beginning like 202221028-174608. Reverse sort puts new file at the list top.

### Additional context

Actually I built Marlin with such sort. Just changed 

`#define _SORT_CMP_NODIR() (strcasecmp(sortnames[o1], sortnames[o2]) > 0)`
to
`#define _SORT_CMP_NODIR() (strcasecmp(sortnames[o1], sortnames[o2]) < 0)`
in Marlin/src/sd/cardreader.cpp

I can add config option and create PR if it seems reasonable.

**Comment by GMagician** [comment]
Don't expect an answer. I suggest you to create PR anyway and wait

**Comment by vovodroid** [comment]
PR #25038
