### ISSUE TITLE
[FR] Check if BLTouch is plugged in correctly before moving Z-axis

### ISSUE THREAD

**Issue by samuel-w** [MarlinFirmware/Marlin#24933]
### Is your feature request related to a problem? Please describe.

Sometimes users (including me) connect their BLTouch probe pins incorrectly, preventing the printer from detecting the needle position. The print head rams into the print bed. This results in a broken bed, nozzle or BLTouch needle, all of which suck to deal with.

Tested in latest bugfix by disconnecting probe pin, this case is not detected.

### Are you looking for hardware support?

Any printer that uses a BLTouch or clones

### Describe the feature you want

1. Before homing z-axis, retract BLTouch. Verify the probe pin is "TRIGGERED".
2. Deploy the BLTouch needle. Verify the probe pin is "open".
3. If either of the two fail, give BLTouch error, preferably with message to check probe pin. Otherwise, continue homing normally.

### Additional context

By probe pin, I mean Z_MIN_PROBE_PIN, not the BLTouch pin that goes up and down.

**Comment by slowbro** [comment]
Implemented in #25021.
