### ISSUE TITLE
[BUG] CUSTOM_USER_BUTTONS doesn't trigger M112 E-Stop

### ISSUE THREAD

**Issue by LewisSpring** [MarlinFirmware/Marlin#24936]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Pressing a CUSTOM_USER_BUTTONS button with the GCODE M112 doesn't trigger an E-STOP after each button trigger.

This seems to be related to https://github.com/MarlinFirmware/Marlin/issues/16386 

### Expected behavior

I expected the M112 command to be run after each button press

### Actual behavior

Printer terminal returns
```
ok P15 B16
ok P15 B16
ok P15 B16
ok P15 B16
```
E-STOP doesn't happen.
Printer clicks when the OK line appears - it's definitely registering the button press.

### Steps to Reproduce

1. Press button
2. Printer clicks
3. No E-STOP - printer terminal returns as above.

### Version of Marlin Firmware

2.1.1

### Printer model

Geeetech A10

### Electronics

Stock GT2560 Rev B - Custom button is attached to spare Endstop pin (X MAX)

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

```
#define CUSTOM_USER_BUTTONS
#if ENABLED(CUSTOM_USER_BUTTONS)
  #define BUTTON1_PIN 22 // X MAX ("MIN")
  #if PIN_EXISTS(BUTTON1)
    #define BUTTON1_HIT_STATE     HIGH       // State of the triggered button. NC=LOW. NO=HIGH.
    #define BUTTON1_WHEN_PRINTING true     // Button allowed to trigger during printing?
    #define BUTTON1_GCODE         "M112"
    #define BUTTON1_DESC          "E-STOP!!"  // Optional string to set the LCD status
  #endif
```
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9890061/Configuration.zip)

**Comment by ellensp** [comment]
When you use custom buttons the gcode is inserted directly in to the command queue.

When Emergency passer is enabled the code for processing M112 is removed from the queue processor, It is instead handled by the emergency passer which scans the serial buffer before it get to the command queue.

So yes, M112 will not work.

**Comment by LewisSpring** [comment]
> When you use custom buttons the gcode is inserted directly in to the command queue.
> 
> 
> 
> When Emergency passer is enabled the code for processing M112 is removed from the queue processor, It is instead handled by the emergency passer which scans the serial buffer before it get to the command queue.
> 
> 
> 
> So yes, M112 will not work.

I understand, thank you. 
Is there an alternative method to achieve this or a similar solution? 
I could send the command via Octoprint instead, but I was hoping for something reliable with the least amount of moving parts.
