### ISSUE TITLE
[HELP] SD init fail on skr 1.4 and reprap discount 2004 controller

### ISSUE THREAD

**Issue by VNIV73** [MarlinFirmware/Marlin#24938]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

After countless tries with different sd setting. I can't seem to get the SD card slot on the lcd to work. Using the sd slot on the board itself would be a hassle as it is not accessible unless i remove the bed on my delta. 
Tried with different SPI speed and have ``#define SD_SUPPORT`` and ``#define SDCARD_CONNECTION LCD`` setted up.

### Version of Marlin Firmware

marlin 2.0.6

### Printer model

Kossel Delta

### Electronics

SKR 1.4 

### Add-ons

reprap discount 2004

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[firmware.zip](https://github.com/MarlinFirmware/Marlin/files/9893311/firmware.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
