### ISSUE TITLE
Am I posting in the right place? I am looking for help on BTT TFT print status screen menu shortcuts.

### ISSUE THREAD

**Issue by PEZ18** [MarlinFirmware/Marlin#24941]
### Is your feature request related to a problem? Please describe.

I am trying to figure out if there is a way to access each setting by tapping on icon rather than tapping on more settings menu. I dont know where or how to post for help on this issue.

![image](https://user-images.githubusercontent.com/45371402/198864946-c3e3bb7c-6f37-4656-a12d-cef729ec979f.png)

### Are you looking for hardware support?

Not sure, sorry.

### Describe the feature you want

While in print status screen on BTT TFT35 e3, I want the option to tap on hotend, print bed, fan speed, flow icon to change settings rather than tapping on more icon to access these settings. I am able to do this with Marlin UI on my old build/printer, but I dont know how to change menu tree or settings within LCD config build to make this happen.

### Additional context

Please forgive me if I posted in the wrong location.

**Comment by ellensp** [comment]
This tft runs its own firmware/mini operating system.  https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

Changes to the tft interface like this would have to be made there.
