### ISSUE TITLE
[BUG] Display steps through touch calibration autonomously - BOARD_CHITU3D_V6

### ISSUE THREAD

**Issue by MrFrickinFixit** [MarlinFirmware/Marlin#24952]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Using the latest Marlin v2.1.1. with BOARD_CHITU3D_V6 (103 mainboard not 446) and TFT_TRONXY_X5SA. After flashing the firmware to the board, the display goes directly into touch calibration, then goes through all the calibration steps without actually touching the display. It seems to get hung up on the final step then becomes unresponsive. This is the second mainboard and second display, same issue. I flashed the stock chitu firmware back onto the board and the display responds as it should. Thoughts please. I had the same issue running v2.0.9.3, then moved to v2.1.1 after obtaining a new board and display. 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9922598/Configuration.zip)

### Bug Timeline

Seems to be an old issue. After flashing v2.0.9.3 onto the board.

### Expected behavior

After flashing the firmware, the display should enter touch calibration mode, then allow you to push specific areas of the display to step through the calibration. 

### Actual behavior

The display enters touch calibration mode, steps through the calibration autonomously as if the display is being pressed, then the display becomes unresponsive after it reaches the final step.

### Steps to Reproduce

Flash Marlin to mainboard from SD card and wait for splash screen to go away.

### Version of Marlin Firmware

Marlin v2.1.1 CONFIGURATION_H_VERSION 02010100

### Printer model

TronXY X5SA

### Electronics

Stock CXY-V6-191017

### Add-ons

BLTouch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
provided config does not compile
#error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."

**Comment by MrFrickinFixit** [comment]
> provided config does not compile #error "SERVO0_PIN must be defined for your servo or BLTOUCH probe."
`#define SERVO0_PIN                          PD12
`
[pins_CHITU3D_common.zip](https://github.com/MarlinFirmware/Marlin/files/9923183/pins_CHITU3D_common.zip)

**Comment by thinkyhead** [comment]
When it's not clear how an issue cropped up, it may be simplest to use `git bisect` to find a specific change that caused the problem to manifest. But first you would need to find an older version of Marlin where the bug does not exist.
