### ISSUE TITLE
[BUG] Endstop logic inverted on 2.1.1 - SKR Pro 1.2

### ISSUE THREAD

**Issue by KingTomaHawk** [MarlinFirmware/Marlin#24966]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Yesterday I updated from 2.0.9.1 (versions before 2.0.9.1 had also the correct endstop logics)  to 2.1.1 and noticed that the Endstop logics are inverted. 
I know that Endstops logics are invertable, but I use a BL-Touch (which is also inverted now) and marlin doesn't allow that one to be inverted.
Didn't changed anything on the wiring.

PS: I noticed that many things changed in the pins_BTT_SKR_PRO_common.h file.

Board: BigTreeTech SKR 1.2 Pro.
Printer: Wanhao Duplicator 6 

### Bug Timeline

Started yesterday/with 2.1.1 update

### Expected behavior

X, Y, Z, Z_Probe should be "open" when buttons are not pressed and "triggered" when pressed.

### Actual behavior

X, Y, Z, Z_Probe are "triggered" when buttons are not pressed and "open" when pressed.
Could lead to damage.

### Steps to Reproduce

1. Have a Wanhao Duplicator 6 with a BigTreeTech SKR 1.2 Pro Board
2. Install 2.0.9.1 to see that the endstop logic is correct
3. Install 2.1.1 to see that the endstop logic is inverted.

### Version of Marlin Firmware

2.1.1

### Printer model

Wanhao Duplicator 6 

### Electronics

BigTreeTech SKR 1.2 Pro with TMC 5160

### Add-ons

BL-Touch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin_2.1.1.zip](https://github.com/MarlinFirmware/Marlin/files/9948944/Marlin_2.1.1.zip)
[Marlin_2.0.9.2.zip](https://github.com/MarlinFirmware/Marlin/files/9948950/Marlin_2.0.9.2.zip)

**Comment by ellensp** [comment]
From your provided configs

2.0.9.2 configs
#define X_MIN_ENDSTOP_INVERTING true // Set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING true // Set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING true // Set to true to invert the logic of the endstop.
2.1.1 configs
#define X_MIN_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.

so yes they will be inverted
