### ISSUE TITLE
Dual_X Carrage Problem (DUAL_X_CARRIAGE requires USE_XMAX_PLUG and an X Max Endstop)

### ISSUE THREAD

**Issue by gsuresh2u** [MarlinFirmware/Marlin#24975]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I Have tried 2.1.1, 2.1.x (Hotfix) and 2.0.x (Hotfix), same error
i am building a large size Dual X printer , my Board FLYF407ZG
and i am using X1, X2, Y1, Y2, Z1, Z2, E1, E2
All my Drivers are TMC5160 v1.2 , (getting ALL HIGH while bootup), but moving all axis is fine

In Configuration_adv, it has `#if HAS_X2_STEPPER && DISABLED(DUAL_X_CARRIAGE) `
i changed it to `#if HAS_X2_STEPPER && ENABLED(DUAL_X_CARRIAGE) `
because i want to invert X2 direction, am i wrong ?

while compiling its giving error "DUAL_X_CARRIAGE requires USE_XMAX_PLUG and an X Max Endstop"
i have Enabled `"USE_XMAX_PLUG"`

when i try to move X carraige from BTT TFT70, X1 carrige is moving fine
when i try to home X then X2 carrige is moing in opposite direction (to X Min end stop)

Please anyone tell me what i ahve done wrong in config?

### Version of Marlin Firmware

2.0.X

### Printer model

Custom

### Electronics

FLYF407ZG Board

### Your Slicer

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config and Pins.zip](https://github.com/MarlinFirmware/Marlin/files/9981034/Config.and.Pins.zip)

**Comment by rondlh** [comment]
> In Configuration_adv, it has #if HAS_X2_STEPPER && DISABLED(DUAL_X_CARRIAGE)
> i changed it to #if HAS_X2_STEPPER && ENABLED(DUAL_X_CARRIAGE)
> because i want to invert X2 direction, am i wrong ?

Yes, don't do that, it will not work! Change the wiring to your X2 stepper.
HAS_DUAL_X_STEPPERS means 2 X-steppers on the _same_ carriage, it doesn't work with DUAL_X_CARRIAGE.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
