### ISSUE TITLE
[BUG]  Steps/mm haved after update from 2.0.X only for extruder with TMC 2209

### ISSUE THREAD

**Issue by jiemeb** [MarlinFirmware/Marlin#24992]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

like bug #24504 : I have recently updated my firmware from version 2.0.X to the most recent 2.1.X, ( and bugfix 2.1.X) but the steps per millimeter for two extruder differ by a factor of 2. if i'll go back to 2.0.X last version bug is persistant .
same issue with TMC2209_STANDALONE
to solution my problem I have two solutions. 
modify my `configuration.h`
  #define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 2560, 450,450 } 
  to
   #define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 2560, 225,225 }
or 
modify my  'configuration_adv.h'
    #define E0_MICROSTEPS    16
   to
    #define E0_MICROSTEPS    32   

 

### Bug Timeline

#24504

### Steps to Reproduce

put right value on configurations files

### Version of Marlin Firmware

CONFIGURATION_H_VERSION 02010200

### Printer model

DIY somthing like CTC3

### Electronics

rumba32 Big tree with  TMC2209

### Your Slicer

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin_config.zip](https://github.com/MarlinFirmware/Marlin/files/10012932/Marlin_config.zip)

**Comment by ellensp** [comment]
You probably set updated steps/mm in eeprom   
When the new firmware was uploaded the eeprom was erased, thus downgrading also did not fix it.

There is no bug here.

**Comment by jiemeb** [comment]
Hi,

Value in step in mm for my extruder is the value from marlin 1.X  and  
marlin 2.0.5 with  GT2560 and stepper A4988. I never changed this value.
when i change the bora and stepper i not change this  value and my 
config worked well. I have a doubt of version of stepper. this version 
changed when a go back to Marlin 2.0. it is not a eeprom problem.
Regards
JM


   Le 15/11/2022 à 14:31, ellensp a écrit :

**Comment by jiemeb** [comment]
this day. after 4 week and lot of print. the good value for my extruder come good without action !  mystery !
