### ISSUE TITLE
movement speed

### ISSUE THREAD

**Issue by j0hn1k** [MarlinFirmware/Marlin#25002]
### Is your feature request related to a problem? Please describe.

Hi, in the Marlin firmware 2.1.1 when the printer head moves very quickly along a radius of 200+, micro-sticking occurs, almost invisible to the eye, but if you look closely at the finished part, you can see them on it, the STM32F7 board with a fairly fast controller (128x64 screen), the problem seems to be in reading speed gcode. how to maximize it? if there are any recommendations what to tweak in the config file for maximum speed without lаgs?

### Are you looking for hardware support?

BTT SKR3 EZ
128х64 display

### Describe the feature you want

Overclock the printer as much as possible without lags

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
