### ISSUE TITLE
[BUG] Invalid %s entry in various MSG_MOVE_N_MM strings

### ISSUE THREAD

**Issue by jmz52** [MarlinFirmware/Marlin#25039]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Greek, Russian and Ukrainian translations of MSG_MOVE_N_MM use '%s' characters instead of '$'
'%s' symbols are not replaced by '0.025' value and are displayed as is

### Bug Timeline

Unknown

### Expected behavior

'$' character is used
language_en.h
`LSTR MSG_MOVE_N_MM                      = _UxGT("Move $mm");`

### Actual behavior

'%s' characters are used

language_el.h
`LSTR MSG_MOVE_N_MM                      = _UxGT("Μετακίνηση %s μμ");`
language_el_gr.h
`LSTR MSG_MOVE_N_MM                      = _UxGT("Μετακίνηση %s μμ");`
language_ru.h
`LSTR MSG_MOVE_N_MM                        = _UxGT("Движение %sмм");`
language_uk.h
`LSTR MSG_MOVE_N_MM                        = _UxGT("Рух %sмм");`

**Comment by ellensp** [comment]
A PR has been created to fix this
