### ISSUE TITLE
[BUG] BLTouch Doesn’t Level (I know… another thread about this)

### ISSUE THREAD

**Issue by ConfusedPrinter** [MarlinFirmware/Marlin#25041]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Let me start by saying I have read every single thread I can find (here and elsewhere) numerous times each. I have tried their recommended fixes numerous times each and in different combination. I have been reading about this and trying to fox without asking for help for literally over 6months. The amount of wasted time at this point is crazy (sadly).

I know this has been discussed numerous times before (nothing works for me) but…

No matter what I do, no ABL types will create a truly level first layer. They are off enough that one side will be almost dragging the nozzle head across the surface and the other won’t adhere.
I have a Lulzbot Taz 6 with BLTouch, SKR 1.4turbo, volcano hot end, and some other minor mods (this is how I got it… I would have kept it stock could I have foreseen I’d never be able to use it).
I have re-wired it. Replaced the 3D Touch with a real BLTouch. Manually leveled the bed (to within .5mm max deviation), god knows how many firmware mods, tried the z endstop pin and the BLTouch pin. I’ve tried changing the grid points. I’ve re-written my firmware setup from scratch numerous times. I’ve re-written my starting Gcode. I’ve placed shims under the probe at certain points to ensure that it responds to that shim when printing (it does! So it IS making adjustments!)
However, with every single one of these experiments the result is consistently always the same! The front left everything is squished. The front right prints too high off the bed. The middle is great. Back left is squished but not as bad as front left. And back right is squished but not as bad as back left.

Please help. The amount of time and money I have wasted on this is palpable… I’m about to just give up and throw the thing away (because I can’t in good conscience sell it like this guy did to me).

### Expected behavior

ABL accommodates differences in bed

### Actual behavior

ABL accommodates differences… but not enough to create a viable first layer

### Version of Marlin Firmware

2.1

### Printer model

Lulzbot Taz 6

### Electronics

SKR V1.4turbo

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

Pronterface

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

[CurrentConfigs.zip](https://github.com/MarlinFirmware/Marlin/files/10128433/CurrentConfigs.zip)

**Comment by ConfusedPrinter** [comment]
Hello? Anybody?

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
