### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by 2806war** [MarlinFirmware/Marlin#25058]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

![IMG_20221204_211313](https://user-images.githubusercontent.com/35971695/205510732-195ab621-ff3d-4722-9ed3-0cf3a4703fc2.jpg)

### Expected behavior

Помогите с ошибкой

### Version of Marlin Firmware

Marli 2.1.1

### Printer model

Ender

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Host Software

Repetier Host

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

![IMG_20221204_211313](https://user-images.githubusercontent.com/35971695/205510780-8fc6c05a-a12f-43c5-a97d-8e8aa2e7873e.jpg)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
