### ISSUE TITLE
[BUG] Extruder stops extruding, Linear advanced and TMC 2208

### ISSUE THREAD

**Issue by victoroos** [MarlinFirmware/Marlin#25069]
### Did you test the latest `bugfix-2.1.x` code?

Yes, it still exists (or whatever the answer was)

### Bug Description

hello,

So, after I read that the TMC 2208 can finally be used in the extruder axis with linear advanced. I got it all setup and calibrated nicely.
Now trying a few prints, but my last 2 prints stopped extruding at a certain point. THe extruder stepper motor just stops rotating.

I tried different files, checking the gcode, the extruder definitely gets commands in the GCODe: https://pastebin.com/YmQEneJp

### Expected behavior

I expected it to finish printing

### Actual behavior

It stopped rotating

### Version of Marlin Firmware

2.1.1

### Printer model

TEvo Tarantula PRo

### Electronics

MKS L 

### Add-ons

TMC 2208

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10170203/Configuration.zip)

**Comment by victoroos** [comment]
It looks like printing a calibration cube works. It is very file specific.

**Comment by victoroos** [comment]
Tested with the bug fix, still same problem with the gcode "attached"

**Comment by victoroos** [comment]
LA is now off and it works :/

**Comment by victoroos** [comment]
LA is off and it works :)

**Comment by victoroos** [comment]
LA is off and it works :/

**Comment by jhstatewide** [comment]
I have the same bug, TMC2208 running in standalone. I read the release notes that TMC2208 was supported for LINEAR_ADVANCE now with 2.1 so attempted an upgrade. The print will start just fine but 5-10 minutes in, extruder halts entirely. I then flipped linear advance off and get the same behavior. Linear advance on/off, it does not matter. I'm using a FLSUN QQS-PRO, opened an issue in one of the forks:

https://github.com/Foxies-CSTL/Marlin_2.1.x/issues/12

Printer works fine on TMC2208 on Marlin 2.0.8, no linear advance.

No combination of settings for Marlin 2.1 appear to work properly, so holding on Marlin 2.0.8 for now.

**Comment by victoroos** [comment]
I'm running the TMC in UART mode. Weird that you have it as well.

**Comment by Nuck-TH** [comment]
I too have random overcurrent errors(regardless of set current, be it 500mArms(stock) or 1Arms(nominal for motors), but on XY axis instead of extruder.
In the same vein as above, i haven't had this issue on 2.0.x branch.
Kingroon KP3S v1.3 board with soldered-on TMC2225 in uart mode.

**Comment by LaurenceGough** [comment]
Same issue here with a Creality 4.2.2 board running Marlin 2.1.2 (built today).

K factor gcode test print works fine but when printing a real print it failed a few layers in.

Extruder is able to be moved by hand, all other steppers are still active.

**Comment by LaurenceGough** [comment]
> I have the same bug, TMC2208 running in standalone. I read the release notes that TMC2208 was supported for LINEAR_ADVANCE now with 2.1 so attempted an upgrade. The print will start just fine but 5-10 minutes in, extruder halts entirely. I then flipped linear advance off and get the same behavior. Linear advance on/off, it does not matter. I'm using a FLSUN QQS-PRO, opened an issue in one of the forks:
> 
> [Foxies-CSTL#12](https://github.com/Foxies-CSTL/Marlin_2.1.x/issues/12)
> 
> Printer works fine on TMC2208 on Marlin 2.0.8, no linear advance.
> 
> No combination of settings for Marlin 2.1 appear to work properly, so holding on Marlin 2.0.8 for now.

I am experiencing the exact same issues. LA on or off. A couple of layers in and my Extruder motor goes completely dead. Only turning the printer off and back on resolves the issue. No extruder stepper moves etc will get it going.

With Marlin 2.0.8.26 (Creality fork) I never had an issue. 

However I'm sure there are 1000's of people using Marlin 2.1.x without issue, I don't get it.

Edit: I resolved this by reducing the Accel and jerk.  The ender 5 pro boards are all stuck in the silent drive (stealthchop) mode which means if they go over current they will just cut out until power cycled. They do not support speed based hybrid stealthchop mode.

**Comment by Jumbo125** [comment]
Does it work with TMC 2208 driver when I use marlin 2.1.1?
So I will be compile the new Bugfix version.

Or exists the bug?

**Comment by Postman05** [comment]
I had the same problem with my Tevo Tarantula Pro + TMC2208 (standalone) on Marlin 2.0.8. The problem disappeared when I disabled S-curve.
Maybe this will help you too.

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by jhstatewide** [comment]
@thisiskeithb Awesome... can you provide some detail? Was there a certain commit or feature that landed that makes this issue likely fixed?

**Comment by thisiskeithb** [comment]
> Was there a certain commit or feature that landed that makes this issue likely fixed?

[Several Linear Advance PRs have been merged](https://github.com/MarlinFirmware/Marlin/pulls?q=is%3Apr+label%3A%22F%3A+Linear+Advance%22+merged%3A%3E2022-12-06) since this issue was opened, which is why I asked users experiencing this bug to download the latest `bugfix-2.1.x` and report back.

**Comment by jhstatewide** [comment]
@thisiskeithb Thanks for the detail!

**Comment by thisiskeithb** [comment]
Fixed in the various PRs mentioned above.
