### ISSUE TITLE
[BUG] Compounding Z Probe Offset error after aborting print(s)

### ISSUE THREAD

**Issue by slowbro** [MarlinFirmware/Marlin#25065]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I've started to notice a trend with my printer, where Z needs to be babystepped more and more after each consequtive failed/aborted print. The first print after boot is awesome - the probe works as intended. After aborting, I find that I need to babystep 0.3-0.4mm UP (times the number of aborts since boot). Seemingly, this doesn't happen with prints that complete successfully.

### Bug Timeline

I just noticed it recently, though I haven't played around with my printers since 2.0.x

### Expected behavior

I would expect the bed probe to get the actual 0 point of the bed, and the z probe offsets to not drift.

### Actual behavior

After an aborted print, the next print will need to be babystepped upwards a significant amount to stop the nozzle from dragging on the bed/blocking extrusion.

### Steps to Reproduce

1. Cold boot your printer (or reset the mcu)
2. Start a print
3. Abort said print
4. Start another print

### Version of Marlin Firmware

Marlin bugfix-2.1.x 9c092ed0fcbe4f96300c9f2ecafa903cec54ca73

### Printer model

heavily customized ender 3

### Electronics

BTT Octopus 1.1

### Add-ons

BLTouch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config-2022-12-05.zip](https://github.com/MarlinFirmware/Marlin/files/10152729/config-2022-12-05.zip)

**Comment by slowbro** [comment]
> Seemingly, this doesn't happen with prints that complete successfully.

Scratch that, I just witnessed it happen after a successful print. I had to Z babystep +1.0mm

**Comment by Farva42** [comment]
This is expected behaviour. If you want it to adjust your probe offset you would need to enable ```//#define BABYSTEP_ZPROBE_OFFSET ``` In config advanced.

**Comment by slowbro** [comment]
But why would the Z-Probe Offset (or whatever is being changed), be changed between prints? I did not make any commands to adjust the Z-Probe Offset, nor did I babystep on the first successful print. The subsequent prints simply crash into the bed without input from the user.

**Comment by Farva42** [comment]
You could check if your z offset is changing by sending M851 before a print let a run for a bit then cancel the print and send it again to see if your offset has changed. I'd take a look at your start/end gcode in your slicer as well as in Octoprint to see if something might be changing it.

**Comment by mashuptwice** [comment]
I am experiencing something similar, except I have to set the Z-offset higher. 
For each run I end up with a Z-offset that is ~0.9mm higher than before. I'm already in the positive offset range, at +0.550mm at the moment.

It seems that I don't even have to print something, a bed leveling run via octoprint seems to be enough!

**Comment by Tehvan** [comment]
This is assuming no "Z offset" is set in your slic3r. But I experienced the same infuriating thing with real world nozzle z-offset changing (software value stayed the same) after each cancelled print job. It was actually problem with UBL. Turned UBL off and presto! I don't have to readjust the z offset. UBL hasn't worked for me for at least a year. Every time I try it I end up with more problems. Just embrace bilinear. There are like 5 different active issues (like, things don't work issues) on github right now and all have one thing in common--did you guess it? UBL

**Comment by mashuptwice** [comment]
The constant ABL/Offset issues of Marlin were the reason why I changed to klipper. No problems since.

**Comment by Tehvan** [comment]
> This is assuming no "Z offset" is set in your slic3r. But I experienced the same infuriating thing with real world nozzle z-offset changing (software value stayed the same) after each cancelled print job. It was actually problem with UBL. Turned UBL off and presto! I don't have to readjust the z offset. UBL hasn't worked for me for at least a year. Every time I try it I end up with more problems. Just embrace bilinear. There are like 5 different active issues (like, things don't work issues) on github right now and all have one thing in common--did you guess it? UBL

Well, I may have to correct myself. I still have to  adjust my Z nozzle offset. There is something **very** sensitive about it (yay inductive probes 😒), what exactly I don't know. Repeatability is 0.02mm but in reality it went from -4mm to -6.5mm. I suppose it is possible my plate just warps **that bad** going from 85C to 110C. But I suspect the inductive probe is not temperature compensated or something so my chamber temp is throwing it. I've removed the code to do a G28 before starting the print and my boat is actually finally printing . . .

**Comment by ghost** [comment]
@Tehvan I've definitely noticed problems with bilinear ABL and a BLTouch. I had the same thing happen, where my nozzle would end up somewhere above or below the printbed. I think this is not specific to your inductive probe, but a bug in the way Marlin handles the probe offsets in combination with ABL. 

It wasn't a problem when I did one leveling right after powering on the printer, but only when I would do multiple bed levelings per session.

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.
