### ISSUE TITLE
[BUG] Inconsistent G33 results - Dry Run Works, Real Calibration Fails

### ISSUE THREAD

**Issue by melo-gonzo** [MarlinFirmware/Marlin#25074]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When trying to calibrate my printer with G33, the routine errors out after successfully completing one iteration.
```
echo:Homing Failed
Error:Printer halted. kill() called!
Error:Printer halted. kill() called!
```

I have tested the G33 routine using the following commands:
```
G33
G33 P1
G33 P2
G33 P3
G33 V0
```

While the `P1` and dry run `V0` variants are successful, each of the other listed varieties fail. 

I have tried debugging the code by adding some console logging, as well as enabling the debug and message logs with `M111 S38` however I haven't been able to trace down the issue exactly. The error message seems to always come after `endstops.validate_homing_move();`. 

### Bug Timeline

Only tested bugfix-2.1.x

### Expected behavior

I would expect each variety of G33 to succeed without failure.

### Actual behavior

The commands `G33 P1` and `G33 V0` succeed and the rest fail.

### Steps to Reproduce

Issue a G33 command.

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Atom 2.0 Delta Printer

### Electronics

BTT SKR3 EZ

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Attached is my `Configuration.h` and `Configuration_adv.h`. I've also attached the pronterface output of `G33 P1`, `G33 P2`, and `G33 V0` when run with M111 S38.
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/10182770/configs.zip)
[g33_output.zip](https://github.com/MarlinFirmware/Marlin/files/10182772/g33_output.zip)

**Comment by melo-gonzo** [comment]
Was there any checks on this? Still struggling to get useful output from `G33`.

**Comment by Quas7** [comment]
I have a similar issue with my height-modded Flsun Q5 Delta after updating to Marlin 2.1.2. 
With previous Marlin versions I got it always calibrated.
UBL Bed leveling works. M48 works as well (0.006mm spread).

But running G33 P1 or greater P it results in probe either crashing mid probing or a probe error (with or without UBL active).
With V0 it works to some point: 
G33 P0 V1/2/3 ... ok
G33 P1 V0 ... ok
G33 P2 V0 ... fail

After compiling with level debugging and M111 S32 the G33 (no parameters) seems to work for many probe points but eventually fails with "Recv: SLOW Probe fail! - No trigger.":
```
Recv: <<< do_blocking_move_to  X13.49 Y89.52 Z26.42
Recv:   current_position= X13.49 Y89.52 Z26.42 : Probe::set_deployed
Recv: deploy: 1
Recv: >>> Probe::run_z_probe  X13.49 Y89.52 Z26.42
Recv: >>> Probe::probe_down_to_z  X13.49 Y89.52 Z26.42
Recv: >>> do_blocking_move_to  X13.49 Y89.52 Z26.42
Recv: >  X13.49 Y89.52 Z20.50
Recv:   destination= X13.49 Y89.52 Z26.42 : destination = current_position
Recv:   current_position= X13.49 Y89.52 Z26.42 : xy move
Recv:   destination= X13.49 Y89.52 Z20.50 : prepare_fast_move_to_destination
Recv:   current_position= X13.49 Y89.52 Z20.50 : z lower move
[...]
Recv: <<< do_blocking_move_to  X13.49 Y89.52 Z20.50
Recv:   current_position= X13.49 Y89.52 Z20.50 : sync_plan_position
Recv: <<< Probe::probe_down_to_z  X13.49 Y89.52 Z20.50
Recv: SLOW Probe fail! - No trigger.
Recv: <<< Probe::run_z_probe  X13.49 Y89.52 Z20.50
Recv:   current_position= X13.49 Y89.52 Z20.50 : Probe::set_deployed
Recv: deploy: 0
Recv: Probe::do_z_raise(50.00)
Recv: >>> do_blocking_move_to  X13.49 Y89.52 Z20.50
Recv: >  X13.49 Y89.52 Z71.50
Recv:   destination= X13.49 Y89.52 Z20.50 : destination = current_position
Recv:   destination= X13.49 Y89.52 Z71.50 : prepare_fast_move_to_destination
Recv:   current_position= X13.49 Y89.52 Z71.50 : z raise move
Recv:   current_position= X13.49 Y89.52 Z71.50 : xy move
[...]
Recv: <<< do_blocking_move_to  X13.49 Y89.52 Z71.50
Recv: //action:notification Stow Z-Probe
Recv: Stow Z-Probe
Recv: //action:prompt_end
Recv: //action:prompt_begin Stow Z-Probe
Recv: //action:prompt_button Continue
Recv: //action:prompt_show
[...]
Recv: echo:busy: paused for user
[...]
Recv: echo:busy: paused for user
[...]
Recv: //action:notification Q7 FLSUN Q5 Ready.
Recv: >>> do_blocking_move_to  X13.49 Y89.52 Z71.50
Recv: >  X13.49 Y89.52 Z71.50
Recv:   destination= X13.49 Y89.52 Z71.50 : destination = current_position
Recv:   current_position= X13.49 Y89.52 Z71.50 : xy move
Recv: <<< do_blocking_move_to  X13.49 Y89.52 Z71.50
Recv: //action:notification Probing Failed
Recv: Error:Probing Failed
Changing monitoring state from "Operational" to "Error"
Changing monitoring state from "Error" to "Offline after error"
```

Increasing Z_PROBE_LOW_POINT from -1 to -5 (default) the G33 P1 V3 worked but the first touchdown overran the trigger point of the probe by roughly 0.5mm and I have multi-probing active:
```
#define MULTIPLE_PROBING 3
#define EXTRA_PROBING    1
```
Redoing the same probing with the updated height works perfectly afterwards.
Also G33 P2 V3 works now. But G33 P3 V3 still fails during calibration. This might be related to the probe inconsistency bug but Deltas seem to get not that much attention.

I would causiously conclude, that Z_PROBE_LOW_POINT was not negative enough for me for some reason and height deviations from the actual value threw the system off.

**Comment by melo-gonzo** [comment]
Switched to klipper. Thanks, can be marked as closed.
