### ISSUE TITLE
[BUG] M502 fails to restore configuration or Marlin fails to read the value correctly.

### ISSUE THREAD

**Issue by ilendemli** [MarlinFirmware/Marlin#25088]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Trying to reset the values to the ones i defined in configuration.h. M502 and M500 are executed and returns ok. But M503 returns all zeros. Advanced Settings on Display shows garbage.

```
M503
13:18:47.301 > echo:; Linear Units:
13:18:47.302 > echo:  G21 ; (mm)
13:18:47.302 > echo:; Temperature Units:
13:18:47.302 > echo:  M149 C ; Units in Celsius
13:18:47.302 > echo:; Filament settings (Disabled):
13:18:47.302 > echo:  M200 S0 D1.75
13:18:47.302 > echo:; Steps per unit:
13:18:47.302 > echo:  M92 X0.00 Y0.00 Z0.00 E0.00
13:18:47.302 > echo:; Max feedrates (units/s):
13:18:47.302 > echo:  M203 X0.00 Y0.00 Z0.00 E0.00
13:18:47.302 > echo:; Max Acceleration (units/s2):
13:18:47.302 > echo:  M201 X1500.00 Y1500.00 Z100.00 E5000.00
13:18:47.302 > echo:; Acceleration (units/s2) (P<print-accel> R<retract-accel> T<travel-accel>):
13:18:47.302 > echo:  M204 P600.00 R1000.00 T800.00
13:18:47.302 > echo:; Advanced (B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>):
13:18:47.302 > echo:  M205 B20000.00 S0.00 T0.00 J0.01
13:18:47.302 > echo:; Home offset:
13:18:47.302 > echo:  M206 X0.00 Y0.00 Z0.00
13:18:47.302 > echo:; Auto Bed Leveling:
13:18:47.302 > echo:  M420 S0 Z10.00 ; Leveling OFF
13:18:47.302 > echo:; Material heatup parameters:
13:18:47.302 > echo:  M145 S0 H215.00 B40.00 F0
13:18:47.302 > echo:  M145 S1 H250.00 B60.00 F0
13:18:47.302 > echo:; Hotend PID:
13:18:47.302 > echo:  M301 P22.20 I1.08 D114.00
13:18:47.302 > echo:; Z-Probe Offset:
13:18:47.302 > echo:  M851 X-40.00 Y10.00 Z0.00 ; (mm)
13:18:47.302 > echo:; Filament load/unload:
13:18:47.302 > echo:  M603 L0.00 U100.00 ; (mm)
13:18:47.302 > echo:; Filament runout sensor:
13:18:47.302 > echo:  M412 S1 ; Sensor ON
13:18:47.302 > ok
M92
13:30:59.880 >   M92 X0.00 Y0.00 Z0.00 E0.00
13:30:59.880 > ok
```

![IMG_0674](https://user-images.githubusercontent.com/2271750/207053494-8c52271b-b670-48f1-b845-ff947a46ac06.jpg)

Might be related: https://github.com/MarlinFirmware/Marlin/issues/25082

### Bug Timeline

Noticed with bugfix-2.1.x branch from yesterday

### Expected behavior

Expected it to reset to default values.

### Actual behavior

Shows all zeros or garbage

### Steps to Reproduce

M502
M500
M503
M92

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Creality CR10S

### Electronics

Silent Board

### Add-ons

SSR

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/10208267/Marlin.zip)

**Comment by sanders-f** [comment]
The same problem. You can manually add steps per unit by comand  M92 and feedrates by comand M203 and it will work. Like:
M92 X80 Y80 Z400 E500
M203 X300 Y300 Z5 E25
M500

I decided to switch to 2.1.1 Marlin from 2.0 and for half a day I could not understand what happened. Before that, I did not use EEPROM at all. I even tried resetting the EEPROM with a separate sketch, but that didn't help.

**Comment by ellensp** [comment]
How did you compile this Arduino IDE or Vscode with PlatformIO ?

**Comment by ilendemli** [comment]
@ellensp VSCode with PlatformIO

**Comment by ellensp** [comment]
Confirmed, I can replicate this.

**Comment by ellensp** [comment]
A quick bisect later shows issues introduced in b4fbe4ff5023c3dace1aead7aac84feb0b793131

**Comment by thinkyhead** [comment]
Thanks, forgot about that `PROGMEM` specifier!
