### ISSUE TITLE
Is it possible to implement a Resonance compensation feature in Marlin like in Klipper?

### ISSUE THREAD

**Issue by CelliMatti** [MarlinFirmware/Marlin#25083]
I have build a 3D printer which is quite heavy and very stiff. When I print with it, I notice that with certain acceleration values it creates some heavy resonances which may cause problems and damage the whole system.
Is it possible to implement a certain kind of resonance compensation by using an accelerometer in Marlin like it`s already implemented in Klipper?

Is it possible to implement a certain kind of resonance compensation by using an accelerometer in Marlin like it`s already implemented in Klipper? So that you can for example run a calibration Gcode at the beginning of a print job, which increases the acceleration in different directions, measures the values from the accelerometer to obtain the frequency and the resulting resonances. Afterwards these values should be compensated with different accelerations and decelerations to reduce the resonance.

**Comment by ellensp** [comment]
See Input shaping in Marlin Bugfix
