### ISSUE TITLE
[BUG] nozzle touches bed: `ARC_SUPPORT` + bed leveling

### ISSUE THREAD

**Issue by rubienr** [MarlinFirmware/Marlin#25095]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When printing an initial layer or the mesh validation pattern with `G26`, the nozzle unexpectedly lowers down towards the bed and touches the build plate. This seem to happen only with `ARC_SUPPORT` enabled (on arc or circle move)  and only on some areas on the bed.

Video: https://user-images.githubusercontent.com/7566204/207461198-bec9cb37-b2f4-4f7b-bc10-29418ba84d75.mp4

Example with `G26`:
![br](https://user-images.githubusercontent.com/7566204/207444528-b5675b28-da36-479d-807f-7226c29729df.png)
![br](https://user-images.githubusercontent.com/7566204/207446775-e4fdfe6f-eded-4e92-9247-ec795804fd4a.jpeg)

### Expected behavior

With `ARC_SUPPORT` enabled: when printing the initial layer (I use arc-welder) or the mesh validation pattern with `G26`, the nozzle shall not rub the build plate.

### Actual behavior

When circles/arcs of the mesh validation pattern are printed, on the two right-most columns the following happens:
1. assume previous circle/line was printed
2. nozzle lifts up
3. nozzle travels to next circle's position (in my case any circle of the two right-most columns)
4. nozzle lowereds to about 0.2mm
5. while circle starts printing, the nozzle lowers again to 0 (or slightly below, cannot say) and rubs the build plate

I observed similar behaviour while printing the initial layer of arbitrary 3D models (sliced with Cura + arc-welder). At the moment I cannot tell if this happens at subsequent layers too (at least I didn't observe it so far).

### Steps to Reproduce

```g-code
; enable ARC_SUPPORT, compile and upload to µC

M502    ; factory reset
M500    ; save settings
M501    ; restore settings

G29 P1  ; UBL, in my case all points are on bed, no interpolation needed
; alternatively fill unpopulated regions, still same behaviour: G29 P3
G29 S0  ; store mesh to slot 1
M420 S1 ; enable bed leveling

G26     ; mesh validation pattern
; when circles of the two right-most columns are printed, the unexpected z behaviour can be observed: nozzle touches bed
```

### Version of Marlin Firmware

bugfix-2.1.x as of 314e52b32af1afb192ac69f88ba5bd256ea3f0a6

### Printer model

Creality Ender 5 Plus

### Electronics

BTT SKR Pro v1.2

### Bed Leveling

~~UBL Bilinear mesh~~ `AUTO_BED_LEVELING_UBL`

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

## Configuration

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10222184/configuration.zip)

## Detailed steps with `ARC_SUPPORT` enabled

```g-code
M502 ; factory reset
M500 ; save settings
M501 ; restore settings

Recv: echo:V87 stored settings retrieved (706 bytes; crc 58571)
Recv: //action:notification Stored settings retrieved
Recv: Unified Bed Leveling System v1.01 inactive
Recv: Unified Bed Leveling initialized.
Recv:
Recv: UBL reset
Recv: echo:; Linear Units:
Recv: echo:  G21 ; (mm)
Recv: echo:; Temperature Units:
Recv: echo:  M149 C ; Units in Celsius
Recv: echo:; Filament settings (Disabled):
Recv: echo:  M200 S0
Recv: echo:  M200 T0 D1.7500
Recv: echo:  M200 T1 D1.7500
Recv: echo:; Steps per unit:
Recv: echo:  M92 X80.0000 Y80.0000 Z1600.0000 E282.1584
Recv: echo:; Max feedrates (units/s):
Recv: echo:  M203 X1000.0000 Y1000.0000 Z8.0000 E150.0000
Recv: echo:; Max Acceleration (units/s2):
Recv: echo:  M201 X1000.0000 Y1000.0000 Z15.0000 E35000.0000
Recv: echo:; Acceleration (units/s2) (P<print-accel> R<retract-accel> T<travel-accel>):
Recv: echo:  M204 P600.0000 R2000.0000 T1000.0000
Recv: echo:; Advanced (B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>):
Recv: echo:  M205 B20000.0000 S0.0000 T0.0000 J0.2000
Recv: echo:; Home offset:
Recv: echo:  M206 X0.0000 Y0.0000 Z0.0000
Recv: echo:; Hotend offsets:
Recv: echo:echo:  M218 T1 X-41.0000 Y0.0000 Z0.000
Recv: echo:; Unified Bed Leveling:
Recv: echo:  M420 S0 Z20.0000 ; Leveling OFF
Recv:
Recv: Unified Bed Leveling System v1.01 inactive
Recv: echo:Active Mesh Slot -1
Recv: echo:EEPROM can hold 15 meshes.
Recv:
Recv: echo:; Servo Angles:
Recv: echo:echo:  M281 P1 L140 U55
Recv: echo:; Z Auto-Align:
Recv: echo:  M422 S1 X8.0000 Y185.0000
Recv: echo:  M422 S2 X369.0000 Y185.0000
Recv: echo:; Material heatup parameters:
Recv: echo:  M145 S0 H180.0000 B70.0000 F0
Recv: echo:  M145 S1 H240.0000 B110.0000 F0
Recv: echo:; Hotend PID:
Recv: echo:  M301 E0 P23.9500 I1.8500 D77.5900
Recv: echo:  M301 E1 P23.9500 I1.8500 D77.5900
Recv: echo:; Bed PID:
Recv: echo:  M304 P200.6200 I34.8300 D770.3700
Recv: echo:; Controller Fan:
Recv: echo:  M710 S255 I0 A1 D30 ; (100% 0%)
Recv: echo:; Retract (S<length> F<feedrate> Z<lift>):
Recv: echo:  M207 S2.0000 W20.0000 F3000.0000 Z0.0000
Recv: echo:; Recover (S<length> F<feedrate>):
Recv: echo:  M208 S0.0000 W0.1250 F9000.0000
Recv: echo:; Auto-Retract (S<enable>):
Recv: echo:  M209 S0
Recv: echo:; Z-Probe Offset:
Recv: echo:  M851 X-20.5000 Y55.5000 Z-2.5500 ; (mm)
Recv: echo:; Stepper driver current:
Recv: echo:  M906 X1350 Y1400 Z800
Recv: echo:  M906 I1 Z800
Recv: echo:  M906 T0 E1400
Recv: echo:  M906 T1 E1400
Recv:
Recv: echo:; Hybrid Threshold:
Recv: echo:  M913 X1098 Y1098 Z494
Recv: echo:  M913 I2 Z494
Recv: echo:  M913 T0 E30
Recv: echo:  M913 T1 E30
Recv:
Recv: echo:; Driver stepping mode:
Recv: echo:  M569 S1 X Y Z
Recv: echo:  M569 S1 I1 Z
Recv: echo:  M569 S1 T0 E
Recv: echo:  M569 S1 T1 E
Recv: echo:; Linear Advance:
Recv: echo:  M900 K0.1000
Recv: echo:; Filament load/unload:
Recv: echo:  M603 T0 L2.0000 U0.0000 ; (mm)
Recv: echo:  M603 T1 L2.0000 U0.0000 ; (mm)
Recv: echo:; Tool-changing:
Recv: echo:  M217 Z2.0000
Recv: echo:; Filament runout sensor:
Recv: echo:  M412 S1 ; Sensor ON


G29 P1  ; UBL, all points are on bed, no interpolation needed
G29 S0  ; store to slot 1
M420 S1 ; enable bed leveling
M420 V  ; show mesh

Recv: Bed Topography Report:
Recv:
Recv:     (  8,362)                                      (369,362)
Recv:         0       1       2       3       4       5       6
Recv:  6 | +0.0808  +0.0463  -0.0115  -0.1175  -0.1725  -0.2662  -0.4258
Recv:    |
Recv:  5 | +0.0108  +0.0167  -0.0231  -0.1150  -0.1419  -0.1837  -0.3112
Recv:    |
Recv:  4 | -0.0065  +0.0115  -0.0002  -0.0494  -0.0615  -0.0752  -0.1660
Recv:    |
Recv:  3 | -0.0517  +0.0038  +0.0188  -0.0094  +0.0056  +0.0100  -0.0860
Recv:    |
Recv:  2 | -0.0875  -0.0075  +0.0325 [+0.0119] +0.0542  +0.0512  -0.0383
Recv:    |
Recv:  1 | -0.1035  -0.0125  +0.0310  +0.0325  +0.0792  +0.0888  -0.0037
Recv:    |
Recv:  0 | -0.0994  +0.0090  +0.0613  +0.0694  +0.1081  +0.1025  -0.0040
Recv:         0       1       2       3       4       5       6
Recv:     (  8, 32)                                      (369, 32)
Recv:
Recv: Mesh is valid
Recv: Storage slot: 0
Recv: echo:Bed Leveling ON
Recv: echo:Fade Height 20.00

G26 ; mesh validation pattern
```

## Detailed steps with `ARC_SUPPORT` disabled

```g-code
M502 ; factory reset
M500 ; save settings
M501 ; restore settings

Recv: echo:V87 stored settings retrieved (706 bytes; crc 58571)
Recv: //action:notification Stored settings retrieved
Recv: Unified Bed Leveling System v1.01 inactive
Recv: Unified Bed Leveling initialized.
Recv:
Recv: UBL reset
Recv: echo:; Linear Units:
Recv: echo:  G21 ; (mm)
Recv: echo:; Temperature Units:
Recv: echo:  M149 C ; Units in Celsius
Recv: echo:; Filament settings (Disabled):
Recv: echo:  M200 S0
Recv: echo:  M200 T0 D1.7500
Recv: echo:  M200 T1 D1.7500
Recv: echo:; Steps per unit:
Recv: echo:  M92 X80.0000 Y80.0000 Z1600.0000 E282.1584
Recv: echo:; Max feedrates (units/s):
Recv: echo:  M203 X1000.0000 Y1000.0000 Z8.0000 E150.0000
Recv: echo:; Max Acceleration (units/s2):
Recv: echo:  M201 X1000.0000 Y1000.0000 Z15.0000 E35000.0000
Recv: echo:; Acceleration (units/s2) (P<print-accel> R<retract-accel> T<travel-accel>):
Recv: echo:  M204 P600.0000 R2000.0000 T1000.0000
Recv: echo:; Advanced (B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>):
Recv: echo:  M205 B20000.0000 S0.0000 T0.0000 J0.2000
Recv: echo:; Home offset:
Recv: echo:  M206 X0.0000 Y0.0000 Z0.0000
Recv: echo:; Hotend offsets:
Recv: echo:echo:  M218 T1 X-41.0000 Y0.0000 Z0.000
Recv: echo:; Unified Bed Leveling:
Recv: echo:  M420 S0 Z20.0000 ; Leveling OFF
Recv:
Recv: Unified Bed Leveling System v1.01 inactive
Recv: echo:Active Mesh Slot -1
Recv: echo:EEPROM can hold 15 meshes.
Recv:
Recv: echo:; Servo Angles:
Recv: echo:echo:  M281 P1 L140 U55
Recv: echo:; Z Auto-Align:
Recv: echo:  M422 S1 X8.0000 Y185.0000
Recv: echo:  M422 S2 X369.0000 Y185.0000
Recv: echo:; Material heatup parameters:
Recv: echo:  M145 S0 H180.0000 B70.0000 F0
Recv: echo:  M145 S1 H240.0000 B110.0000 F0
Recv: echo:; Hotend PID:
Recv: echo:  M301 E0 P23.9500 I1.8500 D77.5900
Recv: echo:  M301 E1 P23.9500 I1.8500 D77.5900
Recv: echo:; Bed PID:
Recv: echo:  M304 P200.6200 I34.8300 D770.3700
Recv: echo:; Controller Fan:
Recv: echo:  M710 S255 I0 A1 D30 ; (100% 0%)
Recv: echo:; Retract (S<length> F<feedrate> Z<lift>):
Recv: echo:  M207 S2.0000 W20.0000 F3000.0000 Z0.0000
Recv: echo:; Recover (S<length> F<feedrate>):
Recv: echo:  M208 S0.0000 W0.1250 F9000.0000
Recv: echo:; Auto-Retract (S<enable>):
Recv: echo:  M209 S0
Recv: echo:; Z-Probe Offset:
Recv: echo:  M851 X-20.5000 Y55.5000 Z-2.5500 ; (mm)
Recv: echo:; Stepper driver current:
Recv: echo:  M906 X1350 Y1400 Z800
Recv: echo:  M906 I1 Z800
Recv: echo:  M906 T0 E1400
Recv: echo:  M906 T1 E1400
Recv:
Recv: echo:; Hybrid Threshold:
Recv: echo:  M913 X1098 Y1098 Z494
Recv: echo:  M913 I2 Z494
Recv: echo:  M913 T0 E30
Recv: echo:  M913 T1 E30
Recv:
Recv: echo:; Driver stepping mode:
Recv: echo:  M569 S1 X Y Z
Recv: echo:  M569 S1 I1 Z
Recv: echo:  M569 S1 T0 E
Recv: echo:  M569 S1 T1 E
Recv: echo:; Linear Advance:
Recv: echo:  M900 K0.1000
Recv: echo:; Filament load/unload:
Recv: echo:  M603 T0 L2.0000 U0.0000 ; (mm)
Recv: echo:  M603 T1 L2.0000 U0.0000 ; (mm)
Recv: echo:; Tool-changing:
Recv: echo:  M217 Z2.0000
Recv: echo:; Filament runout sensor:
Recv: echo:  M412 S1 ; Sensor ON

G29 P1  ; UBL, all points are on bed, no interpolation needed
G29 S0  ; store to slot 1
M420 S1 ; enable bed leveling
M420 V  ; show mesh

Send: M420 V
Recv:
Recv: Bed Topography Report:
Recv:
Recv:     (  8,362)                                      (369,362)
Recv:         0       1       2       3       4       5       6
Recv:  6 | +0.1219  +0.0856  +0.0075  -0.0902  -0.1633  -0.2577  -0.4100
Recv:    |
Recv:  5 | +0.0367  +0.0138  -0.0200  -0.0887  -0.1169  -0.1606  -0.3006
Recv:    |
Recv:  4 | -0.0037  +0.0125  +0.0100  -0.0387  -0.0425  -0.0623  -0.1567
Recv:    |
Recv:  3 | -0.0371  +0.0194  +0.0298  +0.0038  +0.0125  +0.0075  -0.0831
Recv:    |
Recv:  2 | -0.0783  +0.0029  +0.0392 [+0.0281] +0.0490  +0.0506  -0.0315
Recv:    |
Recv:  1 | -0.1006  -0.0140  +0.0363  +0.0460  +0.0742  +0.0871  -0.0015
Recv:    |
Recv:  0 | -0.0925  +0.0071  +0.0588  +0.0583  +0.0913  +0.0975  -0.0050
Recv:         0       1       2       3       4       5       6
Recv:     (  8, 32)                                      (369, 32)
Recv:
Recv: Mesh is valid
Recv: Storage slot: 0
Recv: echo:Bed Leveling ON
Recv: echo:Fade Height 20.00

G26 ; mesh validation pattern
```

## Reported printer capabilities 
```python
Changing monitoring state from "Connecting" to "Operational"
Send: N0 M110 N0*125
Recv: ok N0 P31 B7
Send: N1 M115*39
Recv: ok N0 P31 B7
Recv: FIRMWARE_NAME:Marlin bugfix-2.1.x (Dec 13 2022 21:04:57) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Ender-5 Plus - on steroids EXTRUDER_COUNT:2 UUID:3f94418c-877f-4f36-819f-7d419923ccb6
Recv: Cap:SERIAL_XON_XOFF:0
Recv: Cap:BINARY_FILE_TRANSFER:0
Recv: Cap:EEPROM:1
Recv: Cap:VOLUMETRIC:1
Recv: Cap:AUTOREPORT_POS:1
Send: M154 S5
Recv: Cap:AUTOREPORT_TEMP:1
Send: M155 S2
Recv: Cap:PROGRESS:0
Recv: Cap:PRINT_JOB:1
Recv: Cap:AUTOLEVEL:1
Recv: Cap:RUNOUT:1
Recv: Cap:Z_PROBE:1
Recv: Cap:LEVELING_DATA:1
Recv: Cap:BUILD_PERCENT:1
Recv: Cap:SOFTWARE_POWER:1
Recv: Cap:TOGGLE_LIGHTS:1
Recv: Cap:CASE_LIGHT_BRIGHTNESS:1
Recv: Cap:EMERGENCY_PARSER:1
Recv: Cap:HOST_ACTION_COMMANDS:1
Recv: Cap:PROMPT_SUPPORT:1
Recv: Cap:SDCARD:0
Recv: Cap:REPEAT:0
Recv: Cap:SD_WRITE:0
Recv: Cap:AUTOREPORT_SD_STATUS:0
Recv: Cap:LONG_FILENAME:0
Recv: Cap:LFN_WRITE:0
Recv: Cap:CUSTOM_FIRMWARE_UPLOAD:0
Recv: Cap:EXTENDED_M20:0
Recv: Cap:THERMAL_PROTECTION:1
Recv: Cap:MOTION_MODES:1
Recv: Cap:ARCS:1
Recv: Cap:BABYSTEPPING:1
Recv: Cap:CHAMBER_TEMPERATURE:0
Recv: Cap:COOLER_TEMPERATURE:0
Recv: Cap:MEATPACK:1
Recv: Cap:CONFIG_EXPORT:0
Recv: area:{full:{min:{x:-1.0000,y:-24.0000,z:0.0000},max:{x:419.0000,y:399.0000,z:431.0000}},work:{min:{x:0.0000,y:0.0000,z:0.0000},max:{x:377.0000,y:370.0000,z:431.0000}}}
```

**Comment by rubienr** [comment]
Hello @Roxy-3D ,

I can confirm that it still occurs in bugfix-2.1.x as of 7c0b4657546d62a740651d3fee802cae62bd99da (Fri Feb 3 06:06:11 2023 +0000).

**How to reproduce:**
1. bed leveling
2. save mesh
3. enable mesh compensation, fade height 15mm
4. print a rectangular object on the suspected area; sliced with ultimaker cura + arc-welder, settings:
   * layer height 0.2mm
   * 10% infill, gyroid pattern
   * initial layer and top/bottom pattern: lines 
5. observe that straight lines of walls and initial/top/bottom layers print normally (no unexpected z-move)
6. observe that the gyroid infill (arcs) is affected by the above described odd behaviour
7. disable bed leveling
8. note that the gyroid infill now prints normally (no unexpected z-move)

That means it is not a bug in G26 (Mesh Validation Pattern).

**Comment by rubienr** [comment]
Here a concise procedure how to reproduce the behaviour:
1. clean start
2. probe mesh
3. travel to suspected X/Y position
4. move a full circle to reproduce the Z-move towards bed

```G-code
; ----- reset flash -----

M502         ; factory reset
M500         ; save settings
M501         ; restore settings

; ----- probe bed, create mesh and store to flash -----

G29 P1       ; UBL, all points are on bed, no interpolation needed
G29 P3       ; optional: "fill unpopulated regions"; all moves of G2/G3 in the subsequent examples are within the probed points;
             ;           no extrapolation is required;
             ;           makes no difference in subsequent steps, if `G29 P3` is left out or executed
G29 S0       ; store mesh to 1st slot
G29 L0       ; load mesh from 1st slot

; ----- home all and place the nozzle above the suspected area -----

G28          ; home all

G90          ; absolute pos.
G0 Z10       ; go to safe Z pos. of 10mm

G91          ; relative pos.
G0 X110      ; place nozzle above the suspected area

; ----- examples -----

; example 1 - erroneous: current Z-height within Z-fade height + compensation enabled
M420 Z11     ; set Z-fade height to 11mm (above current Z=10mm)
M420 S1      ; enable bed compensation
G2 I-10 J-10 ; move a full circle: reproduces unexpected Z move behaviour

; example 2 - OK: current Z-height within Z-fade height + compensation disabled
M420 Z11     ; set Z-fade height to 11mm (above current Z=10mm)
M420 S0      ; disable bed compensation
G2 I-10 J-10 ; move a full circle: no unexpected Z move (as expected)

; example 3 - OK: current Z-height above Z-fade height + compensation enabled
M420 Z9      ; set z-fade height to 9mm (below current Z=10)
M420 S1      ; enable bed compensation
G2 I-10 J-10 ; move a full circle: no unexpected Z move (as expected)

; ----- end -----

```

Observations:
1. unexpected Z-move occurs if the current Z-position is within the Z-fade height and compensation is turned on
2. unexpected Z-move does not occur if the current Z-position is above the Z-fade height (and compensation is turned on)
3. the higher the current Z-position is, the lower the Z-move effect: nozzle moves less downwards
4. the lower the current Z-Position is, the higher the Z-move effect: nozzle move more downwards
5. After testing the left/right/front/rear margins (bed, beyond bed, near X/Y-axis min-/maximum) it seems to happen solely in the red area (see hand drawn sketch in the first posting). The effect is clearly visible when crossing the red-green boundary while doing an arc movement (not on G0/G1).

I can confirm that it still occurs in bugfix-2.1.x as of https://github.com/MarlinFirmware/Marlin/commit/ef3f484d3ca620272f849b913851541b54b51c09 (Thu Feb 9 06:33:20 2023 +0000).

**Comment by rubienr** [comment]
Observed same behaviour also with G5  (Bézier cubic spline).

Additional examples to the afore mentioned ones:
```G-code
; example 4 (Bézier G5) - erroneous: current Z-height within Z-fade height + compensation enabled
M420 Z11                ; set Z-fade height to 11mm (above current Z=10mm)
M420 S1                 ; enable bed compensation
G5 F50 P0 Q-5 X-40 Y-40 ; move Bézier curve: reproduces unexpected Z move behaviour
G5 F50 P0 Q-5 X+40 Y+40 ; move Bézier curve: reproduces unexpected Z move behaviour

; example  5 (linear move G0/G1) - OK: current Z-height within Z-fade height + compensation enabled
M420 Z11                ; set Z-fade height to 11mm (above current Z=10mm)
M420 S1                 ; enable bed compensation
G0 F2000 X-40           ; move linear: no unexpected Z move (as expected) 
G0 F2000 X+40           ; move linear: no unexpected Z move (as expected) 
G1 F2000 X-40           ; move linear: no unexpected Z move (as expected) 
G1 F2000 X+40           ; move linear: no unexpected Z move (as expected) 
```

**Comment by jamespearson04** [comment]
May be due to this https://github.com/MarlinFirmware/Marlin/pull/25453, as it appears to be occuring beyond X pos of 255mm.

**Comment by thisiskeithb** [comment]
https://github.com/MarlinFirmware/Marlin/pull/25453 has been merged, so please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by rubienr** [comment]
I tried to test the firmware as of [16bd900](https://github.com/MarlinFirmware/Marlin/commit/16bd900a56498361d88514a831eed983af9301aa) (31.03.2023) which contains the fix #25453 and also the related [refactoring](https://github.com/MarlinFirmware/Marlin/commit/507c122fcff686bc83d6c8b06bc05f3bf01bcc73). Unfortunately there is some other issue, which prevents me to test if the afore mentioned erratic behaviour has disappeared. What happens now is that while UBL `G29 P1` the probe
1. reports errors on some points (looks random to me; the BL Touch probe test succeeds every time)
2. the bed is not probed four times as configured:
   ```
   #define MULTIPLE_PROBING 3
   #define EXTRA_PROBING    1
   ```
My printer has BL Touch installed. The normal behaviour (i.e. with ef3f484d3ca620272f849b913851541b54b51c09) is:
https://user-images.githubusercontent.com/7566204/229173789-a44c698c-c28f-45cd-8239-aef306df3cf0.mp4

1. deploy probe, 
2. probe four times, 
3. leave probe deployed, 
4. move to next point, 
5. probe four times, 
6. leave probe deployed, ...

The current behaviour with 16bd900a56498361d88514a831eed983af9301aa is:
https://user-images.githubusercontent.com/7566204/229173829-2871c249-94ce-48a4-bafa-d780ee150c7b.mp4

1. deploy probe, 
2. probe one time,
   a. eventually report error   (sends `//action:notification Probing Failed` to OctoPrint)
   b. retract probe, 
   c. deploy probe (eventually a.-c. is repeated),
   d. leave probe deployed
4. move to next point, ...

An example mesh result of `G29 P1` looks as follows (OctoPrint, Bed Visualizer plugin):
![ubl-23-03-31](https://user-images.githubusercontent.com/7566204/229165352-e0d7c4a1-0afd-403d-8146-b4a02123ff98.png)


Apart of this I observe a varying latency in between the time when the probe tip is touched and the bed stops moving. Sometimes the bed stops immediately, sometimes it moves about 3mm beyond the touching point until it stops. In contrast, with the firmware as of 09.02.2023 (ef3f484d3ca620272f849b913851541b54b51c09), when the probe is touched the bed always stops immediately.

I can exclude cabling issues because the probe errors are reproduce-able with the newer firmware, but disappear with the older. I cannot find (but also not exclude) configuration errors.

Configurations:  [configs.zip](https://github.com/MarlinFirmware/Marlin/files/11123509/configs.zip)

I have to postpone the test of the originally reported issue and switch back to the firmware as of 09.02.2023 because the recent one (31.03.2023) is unusable for me.

**Comment by jamespearson04** [comment]
It may be worth trying commit a8ac83b, as some changes to probe appear to have been committed a couple of days ago.

**Comment by thisiskeithb** [comment]
The BLTouch/probe behavior change is new/unrelated to why this issue was originally opened. There have been several updates to the probe code the past few weeks that is causing extra (or no) moves.

See the following issues for more info:
- https://github.com/MarlinFirmware/Marlin/issues/25565
- https://github.com/MarlinFirmware/Marlin/issues/25560

**Comment by rubienr** [comment]
Tested with 158c4de4f6d5a91379226f00e6e9e0e7c153d22f  (Tue Apr 18 ):
- can confirm that the erroneous behaviour was fixed with
   - `G2` (circle)
   - `G5` (Bézier)
- no irregularities observed on the mesh validation pattern `G26`
- also UBL works again as expected (reported [here](https://github.com/MarlinFirmware/Marlin/issues/25095#issuecomment-1492175882))
