### ISSUE TITLE
LCD - Melzi - Tronxy Broken commit

### ISSUE THREAD

**Issue by DaLiV** [MarlinFirmware/Marlin#25097]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

tronxy x5s - default used for LCD #define LCD_FOR_MELZI

at commit 9949672f1d was added conditionals in Marlin/src/pins/sanguino/pins_MELZI_TRONXY.h
--- a/Marlin/src/pins/sanguino/pins_MELZI_TRONXY.h
+++ b/Marlin/src/pins/sanguino/pins_MELZI_TRONXY.h
+#if ENABLED(CR10_STOCKDISPLAY)

but that line must be wrote as:
+#if ENABLED(CR10_STOCKDISPLAY) || defined(LCD_FOR_MELZI)

not sure - but has not seen anything about deprecation of LCD_FOR_MELZI
about differencies between that both - not investigated.

### Bug Timeline

at commit 9949672f1d

### Expected behavior

LCD Working

### Actual behavior

LCD not initialised

### Steps to Reproduce

1. compile sanguino with LCD_FOR_MELZI dysplay
2. flash
3. LCD is not initialised

### Version of Marlin Firmware

Git - 03adbb18ef3

### Printer model

Tronxy X5S

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thinkyhead** [comment]
Thanks for the report. This is now patched. If there are any other displays that should be supported with this same LCD pin mapping please let us know!
