### ISSUE TITLE
[BUG] FORMBOX TREX 2+ no axis movement and random alarms

### ISSUE THREAD

**Issue by ghrrum** [MarlinFirmware/Marlin#25094]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I mean, the most recent version doesn't work. I've compiled it with the bugfix 2.1.x version using the 2.1.x bugfix configuration.
The screen shows fine, but nothing works. No axis movement, no homing, temp readings appear to be normal. Can roll the software back to what Formbot originally had on it and everything works. (Ref: https://www.formbot3d.com/pages/firmware-56 )
Have attempted to flash firmware using both Arduino and PlatformIO and had different errors and failures appear with each means of upload.

Looked in at the board and it has an mega2560 chip on it with, the board itself is the Formbot 1.0 (ref: https://www.formbot3d.com/products/t-rex-2-mother-board-25 )

No idea what is going wrong here, any feedback or insight would be appreciated.
[Configuration files.zip](https://github.com/MarlinFirmware/Marlin/files/10219789/Configuration.files.zip)

### Bug Timeline

Found when attempting to update firmware on 12-9-22

### Expected behavior

Any movement on the unit

### Actual behavior

Nothing.

### Steps to Reproduce

Turn on
Attempt to home
Watch nothing happen

### Version of Marlin Firmware

bugfix 2.1.x

### Printer model

Formbot TRex 2+

### Electronics

Stock

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Generally produce prints via Fusion360 but have Cura available.

**Comment by ellensp** [comment]
Are you sure about your dates?
3 days ago a bug was introduced that set all steps/mm to 0  (check what M503 says the steps/mm is set to)  
This was only fixed 18 hours ago..

**Comment by ghrrum** [comment]
> Are you sure about your dates? 3 days ago a bug was introduced that set all steps/mm to 0 (check what M503 says the steps/mm is set to) This was only fixed 18 hours ago..

I can confirm dates.
Will download most current bugfix+config and try again.

**Comment by ghrrum** [comment]
> Are you sure about your dates? 3 days ago a bug was introduced that set all steps/mm to 0 (check what M503 says the steps/mm is set to) This was only fixed 18 hours ago..

You're my hero, appears to have resolved the issue. SD card is still not reading correctly, but that is an issue I already sussed out with the SD_DETECT_STATE being set incorrectly to HIGH instead to LOW in the Configs Bugfix 2.1.x for the TRex2+

**Comment by ellensp** [comment]
PR to remove #define SD_DETECT_STATE (HIGH) submitted.
Default is LOW

**Comment by ghrrum** [comment]
Ran machine though basics, test prints and then will close issue.
Thanks again for the help @ellensp

**Comment by ghrrum** [comment]
#define INVERT_E0_DIR set to true

As there is no way to plug in the extruder backwards this is a problem.
Not sure what the protocol is for updating configs on here and I'm hesitant to do so as I'm not much for programming, just reading.

Regardless, testing the fix on it now to ensure function.

**Comment by ghrrum** [comment]
Tested fix 

M104 S190
G1 E100 F300 

Good result extruder working normally.

**Comment by ghrrum** [comment]
Tested with known good print from bugfix 1.1.x and found hot-end stops heating on fan start. Alarms when it drops below the set threshold, though so kinda nice.

**Comment by ghrrum** [comment]
Running same known good program through Repetier to collect verbose output on failure.

**Comment by ghrrum** [comment]
Error is Thermal Runaway, checking against Formbot's posted bugfix-1.1.x and found that 
#define THERMAL_PROTECTION_HOTENDS is not enabled, nor is it enabled for any thermal protection.
Disabled all thermal protection.

**Comment by thisiskeithb** [comment]
> Disabled all thermal protection.

Unless you enjoy burning your house down, don't do this. It's enabled for a reason.

**Comment by ghrrum** [comment]
> > Disabled all thermal protection.
> 
> Unless you enjoy burning your house down, don't do this. It's enabled for a reason.

I'm well aware, removed for testing and I'm sitting next to the thing while it was testing. I suspected it was not the root cause, but all source information suggested it *might* be.

Found that it is NOT a thermal runaway. Hotend stops heating when the fan engages, not sure where to look in the config on this as that is some very unexpected behavior.

Have re-enabled thermal protection too, I'm not fond of cutting out safety features. Makes me 2x as concerned that Formbot's official build has it turned off.

**Comment by thisiskeithb** [comment]
Vendors disable thermal protection due to poor hardware components or design. Typically, underpowered bed heaters and/or hotend/parts cooling that blow directly on the heater block.

**Comment by ghrrum** [comment]
I can believe the poor design, but company paid for it and now I have to make it work.

Digging in further I noticed a difference in the // @section hotend temp.
current bugfix shows #define BANG_MAX 180 
OEM shows #define BANG_MAX 255

Suggesting that they want full power getting dumped to the hotends.
Ran PID Tuning and adjusted values.

Still interested in any possible solutions

**Comment by thisiskeithb** [comment]
It's very possible that there are multiple versions of this printer/hardware has been silently update by the vendor.

To make it easier to track configuration issues, please use the issue you opened in the Configurations repo: https://github.com/MarlinFirmware/Configurations/issues/865

**Comment by ghrrum** [comment]
Will do, I'll close this one and carry on my record keeping of issues there.

Thanks for the thoughts and help.
