### ISSUE TITLE
[BUG] Board SKR_V3_0  NUM_ANALOG_FIRST was not declared in this scope

### ISSUE THREAD

**Issue by rado79** [MarlinFirmware/Marlin#25099]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

See "Steps to Reproduce" below

I visited variants.h, maybe missing NUM_ANALOG_FIRST under variant_MARLIN_STM32H743VX.h ?
Unfortunately, i have no programming knowledge, so i opened this BUG report

### Bug Timeline

can not be answered, new board

### Expected behavior

compile without error

### Actual behavior

compile failed

### Steps to Reproduce

1. switch from Skr 2 to SKR 3 board
2. build with existing repository from SKR 2
3. change MOTHERBOARD to BOARD_BTT_SKR_V3_0 in Configuration.h
4. compile with PlatformIO > STM32H743Vx_btt > General > Build
5. a lot of compile errors
6. compile again and again, errors are becoming fewer and fewer
7. ends with compile error shown in section "Additional information & file uploads"

### Version of Marlin Firmware

latest bugfix-2.1.x

### Printer model

CoreXY

### Electronics

SKR 3

### Add-ons

none

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Compiling .pio\build\STM32H743Vx_btt\src\src\gcode\feature\advance\M900.cpp.o
Compiling .pio\build\STM32H743Vx_btt\src\src\gcode\feature\digipot\M907-M910.cpp.o
Compiling .pio\build\STM32H743Vx_btt\src\src\gcode\feature\fwretract\G10_G11.cpp.o
Compiling .pio\build\STM32H743Vx_btt\src\src\gcode\feature\fwretract\M207-M209.cpp.o
Compiling .pio\build\STM32H743Vx_btt\src\src\gcode\feature\input_shaping\M593.cpp.o
Compiling .pio\build\STM32H743Vx_btt\src\src\gcode\feature\pause\G27.cpp.o
In file included from Marlin\src\gcode\config\../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\gcode\config\../../inc/MarlinConfig.h:28,
                 from Marlin\src\gcode\config\M43.cpp:23:
Marlin\src\gcode\config\../../pins/../HAL/STM32/pinsDebug.h: In function 'int8_t digital_pin_to_analog_pin(pin_t)':
Marlin\src\gcode\config\../../pins/../HAL/STM32/pinsDebug.h:172:23: error: 'NUM_ANALOG_FIRST' was not declared in this scope; did you mean 'NUM_ANALOG_LAST'?
  172 |   if (WITHIN(Ard_num, NUM_ANALOG_FIRST, NUM_ANALOG_LAST))
      |                       ^~~~~~~~~~~~~~~~
Marlin\src\gcode\config\../../inc/../core/macros.h:285:38: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                                      ^
In file included from Marlin\src\gcode\config\../../pins/pinsDebug.h:171,
                 from Marlin\src\gcode\config\M43.cpp:29:
Marlin\src\gcode\config\../../pins/../HAL/STM32/pinsDebug.h: In function 'void port_print(pin_t)':
Marlin\src\gcode\config\../../pins/../HAL/STM32/pinsDebug.h:212:15: error: 'NUM_ANALOG_FIRST' was not declared in this scope; did you mean 'NUM_ANALOG_LAST'?
  212 |     calc_p -= NUM_ANALOG_FIRST;
      |               ^~~~~~~~~~~~~~~~
      |               NUM_ANALOG_LAST
*** [.pio\build\STM32H743Vx_btt\src\src\gcode\config\M43.cpp.o] Error 1
====================================================================== [FAILED] Took 18.51 seconds ======================================================================

**Comment by rado79** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10241142/Configuration.zip)

**Comment by ellensp** [comment]
Issue is with #define PINS_DEBUGGING
Yes NUM_ANALOG_FIRST is not defined, for quite a few different board.

**Comment by rado79** [comment]
Compiles successful when PINS_DEBUGGING commented out.

**Comment by rado79** [comment]
#https://github.com/MarlinFirmware/Marlin/issues/24846#issue-1401998368

**Comment by rado79** [comment]
Duplicate
