### ISSUE TITLE
[BUG] Compilation firmware warning

### ISSUE THREAD

**Issue by UndeadBrx** [MarlinFirmware/Marlin#25100]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The following warning pops up during compilation. Build for mks_robin_nano_v1v2

`In file included from Marlin\src\lcd\tft\../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\lcd\tft\../../inc/MarlinConfig.h:28,
                 from Marlin\src\lcd\tft\touch.cpp:23:
Marlin\src\lcd\tft\../../inc/../core/macros.h: In instantiation of 'constexpr decltype ((lhs + rhs)) _MAX(L, R) [with L = long unsigned int; R = int; decltype ((lhs + rhs)) = long unsigned int]':
Marlin\src\lcd\tft\touch.cpp:255:24:   required from here
Marlin\src\lcd\tft\../../inc/../core/macros.h:436:20: warning: comparison of integer expressions of different signedness: 'const long unsigned int' and 'const int' [-Wsign-compare]
  436 |         return lhs > rhs ? lhs : rhs;
      |                ~~~~^~~~~`

### Version of Marlin Firmware

bugfix-2.1.x - 2022-12-14

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10241389/Configuration.zip)

**Comment by ellensp** [comment]
This is the fix 
```DIFF
diff --git a/Marlin/src/lcd/tft/touch.cpp b/Marlin/src/lcd/tft/touch.cpp
index 6bfc0a8abd..6c81ebefcd 100644
--- a/Marlin/src/lcd/tft/touch.cpp
+++ b/Marlin/src/lcd/tft/touch.cpp
@@ -252,7 +252,7 @@ void Touch::touch(touch_control_t *control) {
 void Touch::hold(touch_control_t *control, millis_t delay) {
   current_control = control;
   if (delay) {
-    repeat_delay = _MAX(delay, MIN_REPEAT_DELAY);
+    repeat_delay = _MAX(delay, uint32_t(MIN_REPEAT_DELAY));
     time_to_hold = next_touch_ms + repeat_delay;
   }
   ui.refresh();

```

**Comment by ellensp** [comment]
A PR has been created to fix this

**Comment by UndeadBrx** [comment]
Thanks.
