### ISSUE TITLE
S J:\Marlin-bugfix-2.1.x> platformio run --silent -e STM32G0B1RE_btt *** [C:\Users\jayha\.platformio\packages\framework-arduinoststm32@src-06b9d2668dcd05a92820ac50e10b17c7\variants\MARLIN_G0B1RE\PeripheralPins.c] J:\Marlin-bugfix-2.1.x\.pio\build\STM32G0B1RE_btt\.sconsign310.dblite: No such file or directory[BUG] (bug summary)

### ISSUE THREAD

**Issue by jayhawk303** [MarlinFirmware/Marlin#25104]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

S J:\Marlin-bugfix-2.1.x> platformio run --silent -e STM32G0B1RE_btt
*** [C:\Users\jayha\.platformio\packages\framework-arduinoststm32@src-06b9d2668dcd05a92820ac50e10b17c7\variants\MARLIN_G0B1RE\PeripheralPins.c] J:\Marlin-bugfix-2.1.x\.pio\build\STM32G0B1RE_btt\.sconsign310.dblite: No such file or directory

### Bug Timeline

its new, 12/16/22

### Expected behavior

build firmware

### Actual behavior

slapped in face by vscode while laptop shook its finger at me like Dikembe Mutumbo

### Steps to Reproduce

attempt to compile firmware using platformio prerelease

### Version of Marlin Firmware

2.1.x

### Printer model

ender 3 pro

### Electronics

skr mini e3 v3 stm32g0b1re, 

### Add-ons

btt 35tft e3, bl touch, sprite d.d extruder

### Bed Leveling

ABL Linear grid

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin-bugfix-2.1.x.zip](https://github.com/MarlinFirmware/Marlin/files/10250709/Marlin-bugfix-2.1.x.zip)

i'm including the whole file, because the problem isnt in either config folder.

**Comment by ellensp** [comment]
Just try again, you where to quick, platformio had not finished building a required database. 


This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
