### ISSUE TITLE
[BUG] Enabling both MPCTEMP and ADAPTIVE_FAN_SLOWING breaks build

### ISSUE THREAD

**Issue by LMBernardo** [MarlinFirmware/Marlin#25115]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Building fails when enabling both `MPCTEMP` and `ADAPTIVE_FAN_SLOWING`. This combination is not mentioned anywhere in the [MPCTEMP documentation](https://marlinfw.org/docs/features/model_predictive_control.html), nor is it mentioned anywhere in the config files, and it seems like these features should be compatible.

I believe that this has gone unnoticed for so long because `MPCTEMP` is still noted as experimental and unreliable, and I don't think `ADAPTIVE_FAN_SLOWING` is a particularly common option to enable either. Most likely related to #24687.

### Possible Solution

Starting at line 1168 in `src/module/temperature.h`, there is:
```
    #if ENABLED(MPCTEMP)
      void MPC_autotune();
    #endif
```

Marlin builds successfully when this is replaced with the following:
```
    #if ENABLED(MPCTEMP)
      void MPC_autotune();
      #if ENABLED(ADAPTIVE_FAN_SLOWING)
        static constexpr bool adaptive_fan_slowing = true;
      #endif
    #endif
```

If these features truly are incompatible, then this will cause other problems. But I don't see why they would be.

### Bug Timeline

Old - this has probably existed ever since both features have been available.

### Expected behavior

Marlin should either build successfully, or fail with a message stating that these two options cannot be used together. If the latter, this should also be documented somewhere.

### Actual behavior

Build fails with the error:

```
Marlin\src\module\temperature.cpp: In member function 'void Temperature::tr_state_machine_t::run(const_celsius_float_t, const_celsius_float_t, heater_id_t, uint16_t, celsius_t)':
Marlin\src\module\temperature.cpp:2872:15: error: 'adaptive_fan_slowing' was not declared in this scope
           if (adaptive_fan_slowing && heater_id >= 0) {
               ^~~~~~~~~~~~~~~~~~~~
*** [.pio\build\mega2560\src\src\module\temperature.cpp.o] Error 1
```

### Steps to Reproduce

1. Checkout most the recent Marlin bugfix-2.1.x code @ [fb5a595](https://github.com/MarlinFirmware/Marlin/commit/fb5a595b348824a4fe0adca6dfc796105c25e0cd)

2. Disable PIDTEMP and enable MPCTEMP in Configuration.h

3. Enable ADAPTIVE_FAN_SLOWING in Configuration_adv.h

4. Try to build

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

N/A

### Electronics

N/A

### Add-ons

N/A

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/10261355/Config.zip)

**Comment by GMagician** [comment]
AFAIK MPC should take care of fan and then adaptive fan shouldn't be necessary.
But let's wait for someone who has knowledge about it

**Comment by thisiskeithb** [comment]
> AFAIK MPC should take care of fan and then adaptive fan shouldn't be necessary.

With `MPC_INCLUDE_FAN` enabled, `ADAPTIVE_FAN_SLOWING` shouldn't be necessary, but it's not specifically sanity checked.

**Comment by tombrazier** [comment]
I have always had ADAPTIVE_FAN_SLOWING enabled along with MPC and no compile error.

**Comment by thisiskeithb** [comment]
> I have always had ADAPTIVE_FAN_SLOWING enabled along with MPC and no compile error.

I would guess something broke it recently.

Using a fresh `bugfix-2.1.x` pull & disabling `PIDTEMP`, enabling `MPCTEMP` & `ADAPTIVE_FAN_SLOWING` produces the error:
```prolog
Indexing .pio/build/mega2560/libFrameworkArduino.a
Marlin/src/module/temperature.cpp: In member function 'void Temperature::tr_state_machine_t::run(const_celsius_float_t, const_celsius_float_t, heater_id_t, uint16_t, celsius_t)':
Marlin/src/module/temperature.cpp:2893:15: error: 'adaptive_fan_slowing' was not declared in this scope
           if (adaptive_fan_slowing && heater_id >= 0) {
               ^~~~~~~~~~~~~~~~~~~~
*** [.pio/build/mega2560/src/src/module/temperature.cpp.o] Error 1
```

**Comment by tombrazier** [comment]
I do not get the compile error because I have PIDTEMPBED defined. The problem is not with enabling MPCTEMP, it is with disabling PIDTEMP. The same happens if you disable PIDTEMP for bang bang control.

The following code incorrectly couples ADAPTIVE_FAN_SLOWING with PID.
https://github.com/MarlinFirmware/Marlin/blob/67bc855000345921281a2c8c210e4363542f6a81/Marlin/src/module/temperature.h#L1176-L1180

**Comment by tombrazier** [comment]
I think https://github.com/tombrazier/Marlin/tree/25115 should fix it. Haven't tried it though.

**Comment by thisiskeithb** [comment]
Closing since there's now a PR fix this:
- https://github.com/MarlinFirmware/Marlin/pull/25314
