### ISSUE TITLE
[BUG] Mistake in 2.1.2 release date

### ISSUE THREAD

**Issue by trengtor** [MarlinFirmware/Marlin#25114]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Mistake in 2.1.2 release date. 
Please be exactly!

### Version of Marlin Firmware

2.1.2

### Printer model

ZAV

### Electronics

E3 RRF

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

![photo_2022-12-19_17-01-57](https://user-images.githubusercontent.com/16775489/208444801-618ab055-f78b-4e60-a868-6a6e3d21a59e.jpg)

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/10259868/Marlin.zip)

**Comment by thisiskeithb** [comment]
Fixed in https://github.com/MarlinFirmware/Marlin/commit/3334582f868950d58028e400f47a78d22e0fa4f2 and backported to `2.1.2`, so [grab a fresh copy](https://github.com/MarlinFirmware/Marlin/archive/refs/tags/2.1.2.zip).

**Comment by gudvinr** [comment]
It's very uncool to make non fast-forwardable changes to public release branches
