### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by theservantgorlami** [MarlinFirmware/Marlin#25127]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When I have the printer set to 250 degree C, the printer automatically drops to 235 and will  not go any higher, despite the fact that I have reflashed the firmware and checked to make sure that the configuration file was correct. It was, the printer just will not let me above 235. 

### Bug Timeline

New Issue, It started today.

### Expected behavior

I expected the nozzle to heat to 250.

### Actual behavior

The firmware is locked to 235 as the highest temperature for the nozzle, despite my having set the max temp value to 250.

### Steps to Reproduce

Run the firmware on a printer with a value of 250 set as the max extruder temp value.

### Version of Marlin Firmware

Bugfix 2.1.x

### Printer model

Creality CR20 Pro

### Electronics

BTT SKR Mini E3 V2.0

### Add-ons

N/A

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10274457/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/10274458/Configuration_adv.zip)

**Comment by ellensp** [comment]
You have #define HEATER_0_MAXTEMP 250

This is the max temperature your hotend is allowed to reach
But you cannot get to this temperature

From the config, clearly documented.

```
/**
 * Thermal Overshoot
 * During heatup (and printing) the temperature can often "overshoot" the target by many degrees
 * (especially before PID tuning). Setting the target temperature too close to MAXTEMP guarantees
 * a MAXTEMP shutdown! Use these values to forbid temperatures being set too close to MAXTEMP.
 */
#define HOTEND_OVERSHOOT 15   // (°C) Forbid temperatures over MAXTEMP - OVERSHOOT

```
250-15 = 235


Please dont use bug reports as a support forum.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

**After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).**
