### ISSUE TITLE
[BUG] "Attach media" menu item doesn't provide choise SD or USB

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#25121]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

On boards with both SD and USB flash "Attach media" menu item always attach SD without option to choose which of them, thus leading to necessity insert USB flash, than access SD via main screen.

Reason for this that this menu calls "M21" without parameters. 

Linked PR #25120 adds option for choosing which media kind to attach.

### Expected behavior

SD card will be attached.

### Actual behavior

SD card is not attached.

### Steps to Reproduce

Insert SD card
Click "Attach media" item
Error message appeared

### Version of Marlin Firmware

2.1.x bugfix

### Printer model

Biqu B1 SE

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[B1 SE.zip](https://github.com/MarlinFirmware/Marlin/files/10269848/B1.SE.zip)

**Comment by thisiskeithb** [comment]
Closing since you've opened a PR

- https://github.com/MarlinFirmware/Marlin/pull/25120
