### ISSUE TITLE
[BUG] No resume after power loss

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#25128]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

No resume dialog appears after restart.

### Expected behavior

Dialog appears and resume could be started.

### Version of Marlin Firmware

2.1.x bugfix

### Printer model

Biqu B1 SE

### Electronics

BTT SKR 2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I performed some debug and pinpointed the issue for scenario when USB drive is inserted after boot (I don't know how to see logs over serial during boot process).

What actually happens that mount handling stops [here](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/sd/cardreader.cpp#L518):
`if (old_stat != 2) return;        // First mount?`

And old_stat is always 0 here, besides first time after boot, so it will never pass this line (again, I didn't debug boot, but without media it should change from 2 to 0).

I made workaround for this:

```
  //if (old_stat != 2) return;        // First mount?
  static bool first_mount = true;
  if (!first_mount)
    return;
  first_mount = false;  
```
It works, but probably fix should be in other place to be aligned with existing handling logic.

[B1 SE.zip](https://github.com/MarlinFirmware/Marlin/files/10276366/B1.SE.zip)

**Comment by Keelan-Moore** [comment]
I tried this fix to no avail, no change. The SD card does not read until manually mounted in settings, so my guess is it doesn't ever reach the line of code mentioned as a couple lines earlier there is this break 

`  if (!stat) return;                // Exit if no media is present
`

So the check for the PLR file is never made
