### ISSUE TITLE
[BUG] "#define DISTINCT_E_FACTORS" incompatible with input shaping

### ISSUE THREAD

**Issue by Voxel3DPrinting** [MarlinFirmware/Marlin#25123]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I'm trying to upgrade to Marlin 2.1.2, however, when I enable #define DISTINCT_E_FACTORS, it is unable to compile the firmware.
error;
In file included from Marlin\src\MarlinCore.cpp:47:
Marlin\src\module/stepper.h:348:56:   in 'constexpr' expansion of 'max_isr_rate<>()'
Marlin\src\module/stepper.h:348:75: error: array subscript value '4' is outside the bounds of array type 'const feedRate_t [4]' {aka 'const float [4]'}
  348 |       constexpr float max_step_rate = _MIN(max_isr_rate(), max_shaped_rate);
      |                                                                           ^
Marlin\src\module/stepper.h:370:41: error: size of array 'times' is not an integral constant-expression
  370 |       static shaping_time_t       times[shaping_echoes];
      |                                         ^~~~~~~~~~~~~~
Marlin\src\module/stepper.h:371:45: error: size of array 'echo_axes' is not an integral constant-expression
  371 |       static shaping_echo_axis_t  echo_axes[shaping_echoes];

### Bug Timeline

new bug, marlin 2.1.2

### Expected behavior

I expect to be able to enable the distinct e-factor feature, while still using input shaping.

### Actual behavior

I cannot compile firmware with feature enabled

### Steps to Reproduce

Download newest marlin,

Enable input shaping for X and Y
Set EXTRUDERS count to 2
Set TEMP_SENSOR_1

Verify that it is compiling correctly

Enable DISTINCT_E_FACTORS in configuration.h

It will not compile anymore

### Version of Marlin Firmware

2.1.2

### Printer model

Custom

### Electronics

BTT octopus V1.1, dual revo

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/10271202/Configuration_adv.zip)

**Comment by RV-from-be** [comment]
@Voxel3DPrinting
There are no bugs. You misdefined your DEFAULT_MAX_FEEDRATE and DEFAULT_AXIS_STEPS_PER_UNIT in your Configuration.h file. With 2 extruders, you must have 5 arguments: X, Y, Z, E0 and E1. You have defined only 4!
