### ISSUE TITLE
[FR] 2 decimals resolution in step/mm config page

### ISSUE THREAD

**Issue by fabianoriccardi** [MarlinFirmware/Marlin#25141]
### Is your feature request related to a problem? Please describe.

I was used to marlin v1.1.9, which provides 2-decimal resolution to configurare step/mm in UI. Can Marlin v2 get the same resolution (actually v2.1.2 is only one decimal)?

### Describe the feature you want

I would be able to set 2-decimal values in step/mm configuration page.

**Comment by thisiskeithb** [comment]
Closing since a PR has been opened:

- https://github.com/MarlinFirmware/Marlin/pull/25144
