### ISSUE TITLE
[BUG] Creality 4.2.2 stepper driver warning "H8" missing

### ISSUE THREAD

**Issue by duk3luk3** [MarlinFirmware/Marlin#25153]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The Creality Board 4.2.2 stepper driver warning contains a reference of board "steppings" to on-board stepper driver variants:

https://github.com/MarlinFirmware/Marlin/blob/4b4d98d282f2760e760b9f2ccca8dcc8831f7f8d/Marlin/src/inc/Warnings.cpp#L714-L716

Boards delivered with Ender 3 Pro "V1.5" have a new code "H8" that is on a sticker placed on the SD Card slot.

Based on a printer ordered in November 2022, this board contains HR4988 drivers:

https://cdn.discordapp.com/attachments/491165528295997450/1057146929064194048/IMG_1945.jpg

### Expected behavior

See "H8" specified in the warning

### Actual behavior

"H8" missing

### Steps to Reproduce

Use Configuration.h from https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3%20Pro/CrealityV422

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Creality Ender 4 Pro

### Electronics

Stock 4.2.2

### Add-ons

None

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
Closing since you've opened a PR:
- https://github.com/MarlinFirmware/Marlin/pull/25154
