### ISSUE TITLE
[BUG] G5 feedrate units

### ISSUE THREAD

**Issue by ishonichev** [MarlinFirmware/Marlin#25162]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Strange behavior with G5 command. In descripsion ([here](https://marlinfw.org/docs/gcode/G005.html)) it's said that F - feedrate is set for this command in current units per SECOND. 
1. For G0-G1 feedrate is set in units per minute. Why for G5 value is set in units per second?
2. After division G5 feedrate value in mm/min by 60 the velocity of the extruder is significantly slower than for G0-G1 commands with the same feedrate value in mm/min. I supposed that feedrate for G5 corresponds to distance between start and stop points and not to the actual length of Bezier curve trajectory, but this didn't help either - extruder is still slover than G0-G1 movement .

### Bug Timeline

G5 feedrate units

### Expected behavior

I expected at least G5 feedrate set in mm/sec to be equal to G0-G1 feedrate set in mm/min.
At the very most, I expected G5 feedrate to be set in mm/min and actual speed of extruder to be equal velocity of G0-G1 movement.

### Actual behavior

The extruder is significantly slower than for G0-G1 commands with the equal feedrate value in mm/s. If value is set in mm/min extruder movements are rocket fast.
With bugfix-2.1.x problem is worse. Acceleration seems to be non-linear: extruder starts moving slowly, in the middle it reaches maximum speed and by the end of curve it decelerates.

### Steps to Reproduce

I've generated G-code file (auto0.g) with the script for spiral movement with Bezier curve trajectories. Spiral with the centre in (50; 70) and each round radius is 5 mm longer than the previous. The first round radius is 5 mm. Spiral stars in (50;75). Each round is devided in 4 segments and each segment is a Bezier curve. The first three segments approximate circular curve. The 4th segment of the round transits to the circle with the longer radius. Gcode starts with auto homing and ends in (0; 0).

### Version of Marlin Firmware

MARLIN-2.1.2

### Printer model

Self-made with SKR Mini E3 V3

### Electronics

SKR Mini E3 V3

### Add-ons

Sensorless homing with TMC2209 (built into the motherboard)

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/10319854/Marlin.zip)
[auto0.zip](https://github.com/MarlinFirmware/Marlin/files/10319858/auto0.zip)

**Comment by aldoguzman97** [comment]
try adding to line 173
#define E0_DRIVER_TYPE TMC2209

Also try changing the max feedrate to something higher. I like to set my federates in gcode so I don't have to worry about firmware limitations.

line 1635 I have mine commented out
#define DISABLE_E false

line 2177 might as well include eprom sir mini e3 has a good one apparently. 
#define EEPROM_SETTINGS
