### ISSUE TITLE
[BUG] Linear advance with i2s (MKS Tinybee and TMC2209)

### ISSUE THREAD

**Issue by nikybiasion** [MarlinFirmware/Marlin#25160]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I've tried the bugfix 2.1.x but when i print the linear advance calibration test, only the first line with K=0 is printed, in the other lines the motor extruder not spin.
With this pull request https://github.com/HoverClub/Marlin/commit/b5acd17db79a1ffa360f595486b707dcec021762, first line was printed fine, in the second line the extruder works, but the print of the line does not stop, X motor still spin to the bed endstop, i need to turn off the printer.
I use TMC2209_STANDALONE e MKS Tinybee

### Version of Marlin Firmware

Busgfix 2.1.X

### Printer model

MKS Tinybee

### Bed Leveling

ABL Linear grid

### Your Slicer

Other (explain below)

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/10316179/config.zip)

**Comment by javlonsodikov** [comment]
Hello @thinkyhead Any update on this issue?

**Comment by boldenko** [comment]
same shit here. any updates?

**Comment by nikybiasion** [comment]
Still not working in 2.1.2.1

**Comment by pedr0cks** [comment]
Mine worked fine. 
If you download the files above you'll have to uncomment the Linear advanced config in the advanced configuration file.
line 2108

**Comment by nikybiasion** [comment]
what is your hardware configuration?

**Comment by javlonsodikov** [comment]
Please keep this open

**Comment by javlonsodikov** [comment]
Is this issue fixed?

**Comment by nikybiasion** [comment]
Not fixed yet :(

**Comment by javlonsodikov** [comment]
Please keep it open

**Comment by binleo** [comment]
Have any update for this case?

**Comment by PanosPetrou** [comment]
Still exists...
