### ISSUE TITLE
[BUG] Extruder cooling fan not working

### ISSUE THREAD

**Issue by sanczess** [MarlinFirmware/Marlin#25178]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Anycubic Kossel LP Trigorilla Board Ramps 1.4 EFB

Cooling Fan not working while heating up.
--------------------------------------------------
#define E0_AUTO_FAN_PIN -1
#define E1_AUTO_FAN_PIN -1
#define E2_AUTO_FAN_PIN -1
#define E3_AUTO_FAN_PIN -1
#define E4_AUTO_FAN_PIN -1
#define E5_AUTO_FAN_PIN -1
#define E6_AUTO_FAN_PIN -1
#define E7_AUTO_FAN_PIN -1
#define CHAMBER_AUTO_FAN_PIN -1
#define COOLER_AUTO_FAN_PIN -1

#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED 255   // 255 == full speed
#define CHAMBER_AUTO_FAN_TEMPERATURE 30
#define CHAMBER_AUTO_FAN_SPEED 255
#define COOLER_AUTO_FAN_TEMPERATURE 18
#define COOLER_AUTO_FAN_SPEED 255

--------------------------------------------------
fan works fantastically with older Marlin Version

When I set AUTO_FAN_PIN to "9" as Board Pinout shows- Error
Compilation error: #error "You cannot set E0_AUTO_FAN_PIN equal to FAN_PIN."

### Bug Timeline

first appeared with Marlin 2.1.2

### Expected behavior

Cooling fan starts when heating up at 50°C

### Actual behavior

Extruder Cooling fan doesnt react

### Version of Marlin Firmware

MArlin 2.1.x Bugfix

### Printer model

Anycubic Kossel LP

### Electronics

stock

### Bed Leveling

ABL 3-point

### Your Slicer

Prusa Slicer

### Host Software

Repetier Host

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
You need to #define E0_AUTO_FAN_PIN to the pin it is on.

No it cannot be fan_pin (9) That fan is the part cooling fan. 

You have to have another pin that the fan is wired to

According to the stock example config https://github.com/MarlinFirmware/Configurations/blob/release-2.1.2/config/examples/delta/Anycubic/Kossel%20Linear%20Plus/Configuration_adv.h#L644

#define E0_AUTO_FAN_PIN 44 // turn off extruder fan when it's temperature is above 50°C



This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
