### ISSUE TITLE
[BUG] (2 Part cooling Fan´s)

### ISSUE THREAD

**Issue by BitschiClaudio** [MarlinFirmware/Marlin#25172]
Marlin 2.1.2

### Bug Description

I have a problem.

Marlin 2.1.2
BTT octopus pro
2 hot ends 2 extruders
2 Part coller fan

I want both Part_Fan to always be running, at printing.

If extruder 0 is active in pronterface, everything works with
M106 S
M106 T0/T1 S0-255
but
with active extruder 1 in Pronterface
nothing works..

Active:
#define REDUNDANT_PART_COOLING_FAN 1 // Index of the fan to sync with FAN 0.
#define FANMUX0_PIN 2
#define FANMUX1_PIN 2

If extruder 0 is active in pronterface, everything works with
M106 S
M106 T0/T1 S0-255
but
with active extruder 1 in Pronterface

nothing works..

The fans can be controlled via the display, btt 3.5" tft v3.0 via fan 0 and fan1 and both always start up..

When printing, both extruders are active in Cura, the display shows me a percentage on F0, but the fans don't start.

I slice with cura. Both extruders are active in the setup. and I want to print with the E1, this happens..

And when I'm in Cura. disable E0 and want to print with E1, the printer still uses E0...

and they don't start when printing on E1

I slice with Cura and print via USB stick

Otherwise printed perfectly, except for small fine adjustments

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/10328526/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/10328527/Configuration_adv.txt)

### Bug Timeline

no idea

### Version of Marlin Firmware

Malin 2.1.2

### Printer model

"homemade"

### Electronics

BTT octopus pro v1.0

### Add-ons

2 BTT Max MAX31865

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/10328530/Config.zip)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/10328531/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/10328532/Configuration_adv.txt)
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/10328535/Marlin.zip)

**Comment by Bob-the-Kuhn** [comment]
BTT octopus pro doesn't have a fan mux.  All fans are controlled directly by the MCU.  I suggest setting the FANMUX pins back to -1.  I doubt that this will make any difference.

I take it FAN0 is for extruder 0 and FAN1 is for extruder 1.  With **REDUNDANT_PART_COOLING_FAN 1** both fans will be on when extruder 0 is active but off when extruder 1 is active.

I suggest going into your slicer and adding **M106 P0 S255** and **M106 P1 S255** in the tool change section but after after the tool change.
