### ISSUE TITLE
[BUG] Latest bugfix doesn't recognize SD card, and print freezes

### ISSUE THREAD

**Issue by rq3** [MarlinFirmware/Marlin#25174]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Compiled and installed latest (Jan. 1, 2023) bugfix using the latest example configuration files for the Anycubic Predator. 

The changes to configuration.h are:
1) Change from Classic_ui to Color_ui
2) Turned on endstop_interrupts (as I normally do anyway), to suppress new compile warning
3) Turned off MESH_EDIT_GFX_OVERLAY, as this has always thrown an error otherwise (has for years):
                 //#define MESH_EDIT_GFX_OVERLAY   // Display a graphics overlay while editing the mesh

Selecting a file to print results in a question mark (?) in the center of the screen, and the touch functions are frozen. Removing and re-inserting the SD card then causes Marlin to re-boot, the file is selectable, and the print starts.

However, after about one minute of printing, the print and touch screen freezes.

### Bug Timeline

New, as of bugfix Dec.31, 2022, or maybe earlier?

### Expected behavior

I expect the SD card to be read correctly, the print to start, and complete.

### Actual behavior

The SD card requires that it be removed and re-inserted, which re-boots Marlin. The print is then able to be started, but the printer completely freezes after roughly a minute. A power cycle is required to recover.

### Steps to Reproduce

1) Compile and install the latest bugfix, using the latest examples/delta/anycubic/predator configurations
2) Try to print from the SD card

### Version of Marlin Firmware

bugfix 2.1.2 as of January 1, 2023

### Printer model

Anycubic Predator

### Electronics

stock Trigorilla_pro

### Add-ons

none

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10329608/Configuration.zip)

**Comment by rq3** [comment]
Just tried the very latest bugfix (Jan. 2, 2023). SD card is recognized and starts print UNLESS the card is accessed via the touchscreen icon, in which case the central question mark and printer freeze still happens.

Once a print is started, it still freezes after about 1 minute. Requires a power cycle to force re-boot.

**Comment by jmz52** [comment]
What platformio environment was used for firmware compilation?
What MCU is installed on your Trigorilla pro board?
Have you tried to print with TFT_CLASSIC_UI?

**Comment by rq3** [comment]
> What platformio environment was used for firmware compilation? What MCU is installed on your Trigorilla pro board? Have you tried to print with TFT_CLASSIC_UI?

1) Non-Maple environment
2) STM32F103ZE MCU
3) Haven't tried classic in a LONG time. I'll give it a shot tomorrow and report back

**Comment by rq3** [comment]
Observations:
Classic_UI (non-Maple) works fine, with no issues at all.

1) Color_UI goes into a repetitive boot loop at the boot screen if the SD card is in place at first start.
2) Attaching the SD card from the touch icon results in a question mark in the center of the display.
3) Attaching the SD card from the menus works if the SD card is removed, inserted, and then attached.
4) During a print the printer either freezes after about a minute, OR randomly wanders off in the -Y direction after about a minute.

One other note. A compiled firmware.bin under earlier bugixes (Nov.16, 2022) was 422kb. Under the lates bugfixes it is 299kb.

**Comment by jmz52** [comment]
Are there any error message on COM port, like "sd read error" (with Color_UI) ?

**Comment by rq3** [comment]
> Are there any error message on COM port, like "sd read error" (with Color_UI) ?

Nope. Monitoring over USB with Repetier Host seems normal. It even sees the contents of the SD card, until a print is actually started. When the freeze happens, there is no communication at all. At least Repetier shows nothing. Everything just stops dead, and requires a power cycle to recover.

Also, please ignore my comment about the firmware.bin size! I was using a larger bootscreen, which is not true here, and that would explain the difference. My apologies!

**Comment by jmz52** [comment]
Please to print from SD with SOFTWARE_SPI instead of hardware SDIO and Color_UI:
- disable SDIO_SUPPORT
- enable SOFTWARE_SPI
- change `#define SDSS PD2` to `#define SDSS PC11` in pins_TRIGORILLA_PRO.h file.

You may have "Media Init Failed" error at startup, in this case remove and insert SD card so it can be initialized correctly. Alternatively you can insert SD card after Marlin is booted.

If print is successful, please provide photo of MCU on your Trigorilla pro board and board's revision information.

**Comment by rq3** [comment]
> Please to print from SD with SOFTWARE_SPI instead of hardware SDIO and Color_UI:
> 
>     * disable SDIO_SUPPORT
> 
>     * enable SOFTWARE_SPI
> 
>     * change `#define SDSS PD2` to `#define SDSS PC11` in pins_TRIGORILLA_PRO.h file.
> 
> 
> You may have "Media Init Failed" error at startup, in this case remove and insert SD card so it can be initialized correctly. Alternatively you can insert SD card after Marlin is booted.
> 
> If print is successful, please provide photo of MCU on your Trigorilla pro board and board's revision information.

This results in a repetitive white screen boot loop.

**Comment by uncellon** [comment]
Hmm, on my Flying Bear Ghost 5 (Robin Nano v1.2, XY drivers is TMC2208, ZE - A4988) I have a similar behavior - Y randomly moves on printing a random distance if Marlin built with TFT_LVGL_UI. With TFT_COLOR_UI all works fine. I monitored the COM port using Pronterface and there are no any errors. Y offsets appear between 1 and 25 minutes according to my observations
![IMG_20230104_175535](https://user-images.githubusercontent.com/23581805/210643939-294e13c0-ebef-4cc0-bd5d-f08b7d7b359d.jpg)

**Comment by jmz52** [comment]
> This results in a repetitive white screen boot loop.

@rq3, does it boot if SD card removed?
Or still white screen boot loop even with no SD card?

**Comment by rq3** [comment]
> 

White screen boot loop whether card is inserted or not.

**Comment by rq3** [comment]
In an attempt to track down when this all started, I compiled with the exact same configuration files:
1) Marlin Release 2.1.2. Treats the SD card correctly, but freezes after a short time while printing. An immediate power cycle to re-boot, and then starting the print from new freezes even faster (<30 seconds).
2) Marlin Patched 2.1.2. Screws up the SD card as above, and freezes after a short time while printing.
3) The firmware.bin I am currently using was compiled from a very late bugfix for 2.1.1, dated 11/16/2022, and it works fine in all respects.

I was looking forward to trying Tom Brazier's input shaping on a delta just for grins, but the juice ain't worth the squeeze. I'll stick with what I have at this point.

EDIT: Corrected functional firmware.bin date

**Comment by rq3** [comment]
Bumping this. The SD card issue still exists with today's bugfix (January 11, 2023). Latest bugfix, latest example configurations for delta/anycubic/predator, with Color-UI.

This is a bug.

**Comment by rq3** [comment]
Bumping this again. The SD card issue still exists with today's bugfix (January 15, 2023). Latest bugfix, latest example configurations for delta/anycubic/predator, with Color-UI.

This is a bug.

**Comment by Roxy-3D** [comment]
I agree there are some issues with the SD cards at the moment.   I have been seeing problems with the RepRap Full Graphics LCD panels and the usage of SD cards on them.   I am starting to think it isn't the SD Code.  I'm starting to suspect the SPI interface code.

Does anybody have any thoughts or comments about my thinking?

**Comment by rq3** [comment]
More info. I tried 3 different SD cards. One acted dead, as if it were a piece of paper. The second re-boots the printer when removed, and then re-inserted, with no ability to print from it. The third can be read IF the card is refreshed several (like 6) times, and a print can be started, which then locks up after about a minute. A power cycle is required to recover.

The latest bugfix (as of yesterday) prints fine IF the gcode from any of the cards is sent via USB from Repetier Host.

Reverting to bugfix2.1.2 prior to Dec. 31, 2022 all three cards, and the printer, work fine.

**Comment by thisiskeithb** [comment]
Would you be able to test some [`bugfix-2.1.x` commits](https://github.com/MarlinFirmware/Marlin/commits/bugfix-2.1.x) to narrow this down?

The strategy is to find a commit from some point in the "distant" past where the feature works. Then, test a commit from halfway between that date and today…. And then you keep going to the commit half-way in between your "known to work" commit and your "known to be broken" commit until you find the exact day where it broke.

If you started from a point 256 commits in the past, it would take no more than 8 tests to find the exact commit that broke it.

**Comment by rq3** [comment]
@thisiskeithb, I'd be happy to do a binary search IF you can tell me clearly and explicitly HOW to download the zip file for each commit.

Best Regards

**Comment by thisiskeithb** [comment]
It's actually a command if you have git installed: https://git-scm.com/docs/git-bisect

Start with a minimal config, otherwise conflicts will be painful to resolve.

---

To do it manually, you'd browse to each commit from the main [`bugfix-2.1.x` commit history](https://github.com/MarlinFirmware/Marlin/commits/bugfix-2.1.x) using the <kbd>**< >**</kbd> button on the right:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/13375512/213897167-993fc939-d20b-4c13-aa43-cb9ec104bb4c.png">

Then you'd click on the green <kbd>**< > Code ▼**</kbd> button and "Download ZIP":

<img width="434" alt="image" src="https://user-images.githubusercontent.com/13375512/213897028-d65487bb-e50d-4b5e-99f6-781d787a0b85.png">

**Comment by jmz52** [comment]
It looks like there are two problems intertwine here.

First is the easy one - Anycubic printer stuck when tries to print from SD card (with SDIO_SUPPORT) with TFT_COLOR_UI and works file with TFT_CLASSIC_UI. This mimics the behavior of Kingroon KP3 boards with GD32F303 MCU, so I expect the root cause to be the same - flawed DMA controller than can't handle two concurrent data transfers. This is a common problem for clones and fake STM32. There is a workaround (already tested by Kingroon users) and I'll include it to STM32H7 code I am working on (ETA - a week or two).

Second problem is "SD init fail" issue. Kingroon users reported this problem during workaround development and as far as I know it is not related to TFT code. It is easier to reproduce this problem when SOFTWARE_SPI is used instead of SDIO_SUPPORT, but I did not dig into this problem.

Please note that MSG_MEDIA_INIT_FAIL message is displayed by `LCD_ALERTMESSAGE()` and is not replaced by MSG_MEDIA_INSERTED / MSG_MEDIA_REMOVED messages which are displayed by `LCD_MESSAGE()`.
I.e. if you re-insert SD card after getting MSG_MEDIA_INIT_FAIL message, the message will stay on screen even after CD card is correctly inited and mounted.

**Comment by rq3** [comment]
The bug starts in commit aaae56A, titled "TFT_COLOR_UI asyn DMA SPI" addressing issue #24980 on December 12, 2022.
I am currently printing successfully with the commit just prior to that.

A binary search was done from November 15, 2022 to December 16, 2022. In all cases, the attached configuration files were used, and three different SD cards were used to verify that the cards themselves were not at fault.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/10475138/config.zip)

**Comment by rq3** [comment]
> It looks like there are two problems intertwine here.
> 
> First is the easy one - Anycubic printer stuck when tries to print from SD card (with SDIO_SUPPORT) with TFT_COLOR_UI and works file with TFT_CLASSIC_UI. This mimics the behavior of Kingroon KP3 boards with GD32F303 MCU, so I expect the root cause to be the same - flawed DMA controller than can't handle two concurrent data transfers. This is a common problem for clones and fake STM32. There is a workaround (already tested by Kingroon users) and I'll include it to STM32H7 code I am working on (ETA - a week or two).
> 
> Second problem is "SD init fail" issue. Kingroon users reported this problem during workaround development and as far as I know it is not related to TFT code. It is easier to reproduce this problem when SOFTWARE_SPI is used instead of SDIO_SUPPORT, but I did not dig into this problem.
> 
> Please note that MSG_MEDIA_INIT_FAIL message is displayed by `LCD_ALERTMESSAGE()` and is not replaced by MSG_MEDIA_INSERTED / MSG_MEDIA_REMOVED messages which are displayed by `LCD_MESSAGE()`. I.e. if you re-insert SD card after getting MSG_MEDIA_INIT_FAIL message, the message will stay on screen even after CD card is correctly inited and mounted.

The Anycubic Predator I am using for development is about 5-6 years old. Old enough so that it is highly unlikely that the STM32F103ZE chip is a fake or clone, but you never know.

I do know that I have done some surface mount modifications to the motherboard over the years (reducing the Fosc resistor value to "zero" ohms to eliminate stepper glitches, and removing the ADC input filter components as they interfered with a PT1000 amplifier, and were not correct anyway). 

There is absolutely no way these mods, which were done years ago, affect SD card or SPI functionality, and during that time I took great effort to verify the origin and pin-out of the MCU. If it is a fake or clone, it would have had to have been manufactured very, very quickly after the release of the ST Micro original, and externally and functionally it is indistinguishable from the real thing. Even under the microscope I use for surface mount soldering. At the time, Chitu, the manufacturer of the motherboard, was attempting to break into the printer market, and appeared to take great pains to keep their quality high, even if it cost them money in the short term. Indeed, they did cut costs later in the game, but I am not aware of them ever resorting to clones or fakes.

Also, be aware that there is no commonality between a Chitu (Anycubic) Trigorilla board, and a Chitu (Anycubic) Trigorilla Pro board.

Keep up the great work, and I'll do whatever I can to help. I don't know how you folks keep up with the changes, let alone having fakes and clones thrown into the mix!

**Comment by rq3** [comment]
The latest (January 24, 2023) bugfix commit works fine! Thanks all!
