### ISSUE TITLE
[BUG] Z2min endstop not working

### ISSUE THREAD

**Issue by iain1965** [MarlinFirmware/Marlin#25173]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Dual z motor diy build machine (Hypercube evolution)

Z2min endstop not working in Marlin 2.1.2, works perfectly in 2.0.9.3.

I have checked with M119 and trigger not seen, have tried changing endstop settings to inverting false, but still the same

Have checked configuration_adv.h and configuration.h and can see no obvious errors or omissions. I have attached both sets on configuration.h and configuration_adv.h from 2.0.9.3 and 2.1.2 for you to take a loook at.

[Config files.zip](https://github.com/MarlinFirmware/Marlin/files/10328878/Config.files.zip)

### Expected behavior

Endstop should trigger

### Actual behavior

Endstop does not trigger / is not recognised

### Steps to Reproduce

works ok in 2.0.93, does not work in 2.1.2 or bugfix

### Version of Marlin Firmware

2.1.2

### Printer model

Hypercube Evolution

### Electronics

BTT GTR V1.0

### Bed Leveling

None

### Your Slicer

Simplify3D

### Host Software

Same as my slicer

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by leonel85** [comment]
Hi
How did you solve this problem ?
