### ISSUE TITLE
Is 1.1 considered "stable"?

### ISSUE THREAD

**Issue by Diaoul** [MarlinFirmware/Marlin#2517]
Or should I use Development branch?

**Comment by AnHardt** [comment]
_EDIT:_ Sorry forgot the zeros.

~~~1.1~~~ 1.0.1 is stable in the sens of - it will not be changed anymore.
~~~1.2~~~ 1.0.2 has a very little chance to get further bug fixes, but will get no new features.
~~~1.3~~~ 1.0.3 dev is changing all the time.

If we are talking about "has less bugs" i recommend ~~~1.3~~~ 1.0.3 dev (most of the time)
If we are talking about "is best for everyday use" i can't  give a clear answer today. It depends on your machine, the features you want to use and your workflow. 

_EDIT:_ 1.1 is a more or less random point and currently meaningless.
Thanks for the hint to @Wackerbarth

**Comment by Diaoul** [comment]
Thanks

**Comment by Wackerbarth** [comment]
@Diaoul -  I think that @AnHardt has a "typo" in his response.
1.0.1 longer has maintenance.
1.0.2 may get some bug fixes, but will have no additional features
1.0.3 is a "development" branch and currently incomplete.  But it is likely to never be released under that designation.
The 1.1 tag in the repository is NOT a release (or release candidate) DO NOT USE IT.
The work on that branch is available on "Development" (or, equivalently, "dev". It is nearing a point of being ready for testing. However, there are still issues about bed leveling.
