### ISSUE TITLE
Endstop abort not working on 1.0.2-1

### ISSUE THREAD

**Issue by ronhogwarts** [MarlinFirmware/Marlin#2518]
I have enabled the #define ABORT_ON_ENDSTOP_HIT_FEATURE_ENABLED in the configuration_adv.h file and manually on the printer under "control> motion> endstop abort: on" and then started a print and manually triggered the sensors with a magnet, but nothing happens. Homing works fine and a M119 shows all endstops trigger correctly, yet triggering them during a print does nothing. Any ideas?

**Comment by pdbogen** [comment]
Hm, in https://github.com/MarlinFirmware/Marlin/blob/1.0.2-1/Marlin/stepper.cpp#L194; the abort on endstop hit code is only enabled if you also have SDSUPPORT enabled. Note also that the feature is described as "Enable the option to stop SD printing when hitting and endstops, needs to be enabled from the LCD menu when this option is enabled," which may not be what you expected.

Do you have SD card printing enabled? Were you printing from SD when you ran your test?

**Comment by ronhogwarts** [comment]
I was printed from the SD card at the time, and hence it was obviously enabled. I also changed https://github.com/MarlinFirmware/Marlin/blob/1.0.2-1/Marlin/stepper.cpp#L73 to true, so it is enabled by deafult, so I don't have to re-enable it each time the printer reboots.

**Comment by pdbogen** [comment]
OK, great. Just checking the basics.

Did you see an LCD and/or SERIAL message when you triggered the endstop? (this will indicate if the problem is in the "stopping" part or in the "endstop" part.)

**Comment by ronhogwarts** [comment]
I didn't see any other messages at the time.

**Comment by pdbogen** [comment]
So it sounds like the problem isn't in the abort code, it's in the code that sets flags when endstops are triggered. Just as a further sanity check while I dig into where the problem might be, can you confirm you _weren't_ testing this as part of a "home" operation?

**Comment by pdbogen** [comment]
Another thing to check: Did you comment out ENDSTOPS_ONLY_FOR_HOMING here: https://github.com/MarlinFirmware/Marlin/blob/1.0.2-1/Marlin/Configuration_adv.h#L89 ?

**Comment by ronhogwarts** [comment]
Ah I didn't comment that out, I'll check tomorrow if this fixes it. Should it not be commented out by default? Surely most people want the printer to stop if it hits the endstops, to avoid mechanical damage? On a similar note, why does the option for aborting when it hits the ends stops have to be enabled manually on the printer under "control> motion> endstop abort: on" on each startup?

**Comment by pdbogen** [comment]
I can't speak to the whys or shoulds, sorry. I _did_ submit a PR to at least document that the ABORT_... function requires either enabling endstop checking with `M120` or disabling ENDSTOPS_ONLY...; so at least this problem should be more visible in the future.

If I had to guess, I'd suppose the concern is around the extra work required to poll 3/6 endstops very frequently, while (presumably) managing heaters, steppers, and trying to plan future moves as well. There's a lot going on for the little Arduinos Marlin targets. :/

**Comment by ronhogwarts** [comment]
Well commenting out the below, as you suggested, does indeed work, for anyone else who wonders. Thanks for the help.
 https://github.com/MarlinFirmware/Marlin/blob/1.0.2-1/Marlin/Configuration_adv.h#L89

**Comment by thinkyhead** [comment]
To get `ABORT_ON_ENDSTOP_HIT_FEATURE_ENABLED` to work during an SD print (no matter what your other settings are), you need add the following GCode to your prefix. It must be added _after_ any `G28` or `G29` because your endstops are disabled after homing and leveling if `ENDSTOPS_ONLY_FOR_HOMING` is enabled in your firmware.

``` gcode
M540 S1 ; enable abort on endstop hit
M120 ; enable endstops during printing
```
