### ISSUE TITLE
12864 display vertical menu arrangement? [FR] (feature summary)

### ISSUE THREAD

**Issue by pedroscsant** [MarlinFirmware/Marlin#25184]
### Are you looking for hardware support?

MKS Robin E3D with MKS Mini v3 Display

### Describe the feature you want

Would be nice to be able to mount any kind of 64x128 graphical displays on the vertical, if possible. 
The trouble I'm having is that some parts of the text are cut beyond the size of the display. 
Is there any way to resize the text or rearrange the menu order so it will be displayed properly? 

Please, see pics attached.

![WhatsApp Image 2023-01-03 at 10 20 10 PM (1)](https://user-images.githubusercontent.com/115324096/210467522-06d66bfe-5f6b-4d27-9b74-d638f55c3b5d.jpg)
![WhatsApp Image 2023-01-03 at 10 20 10 PM](https://user-images.githubusercontent.com/115324096/210467527-087a2e26-91ef-48f7-831f-d8f2f69458da.jpg)

**Comment by Nuck-TH** [comment]
While status screen may be usable if modified for this layout, menu system will be borderline unusable - for every menu item only one word would fit and you would need to cut item names short or scroll every of them, which, imho, both cases would be very frustrating and slow to use.

**Comment by pedroscsant** [comment]
> While status screen may be usable if modified for this layout, menu system will be borderline unusable - for every menu item only one word would fit and you would need to cut item names short or scroll every of them, which, imho, both cases would be very frustrating and slow to use.

Yes, I guess you are right, I just read the documentation properly and realised it would be pretty much unreadable.

Using the 64p as the horizontal arrangement, with the current 6x9 caracthers, you would be able to fit 10 caracthers max.
Scaling it down to something like a 4x6 you would fit 16. That would look pretty weird already and still far from the 21 we have on the 128p with the 6x9 arrrangement.

So unless you come up with smaller words, abreviations or even symbols to replace menu entries like "advanced configuration", i guess it's not worth the trouble.

Nonetheless, I still think a "slim" vertical menu would be pretty cool.
