### ISSUE TITLE
Frozen LCD

### ISSUE THREAD

**Issue by HajmamadAgha** [MarlinFirmware/Marlin#25188]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin doesn't work and it stucks on a frozen LCD.

### Bug Timeline

After uploading

### Expected behavior

Main page shows up.

### Actual behavior

stucks on a frozen LCD

### Steps to Reproduce

1. configuring configuration.h and configurationadv.h as the mentioned way in LONGER3D branch.
2. Changing the unknown board to 1151 (LGT_KIT)
3. Changing default_envs to mega2560

### Version of Marlin Firmware

LONGER3D

### Printer model

LK4 PRO

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

https://drive.google.com/file/d/1dn1VmLbad_SqdGSUlosu6AGfbX0w1eGO/view?usp=sharing
https://marlinfw.org/docs/basics/install_platformio_vscode.html
https://drive.google.com/file/d/1D407cnIqCafACkG0hZGTHXpJ0hL3KQuf/view?usp=sharing

**Comment by ellensp** [comment]
Official marlin does not have any support for this LCD

You cannot just dump configs from https://github.com/LONGER3D/Marlin2.0-lgt into real marlin and expect it to work.

All the code in https://github.com/LONGER3D/Marlin2.0-lgt/tree/support-LKxPro/Marlin/src/longer3d needs migrated and updated also.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
