### ISSUE TITLE
[BUG] disabling LED_USER_PRESET_STARTUP makes first NEOPIXEL strip being on at startup but Lights menu think it's off

### ISSUE THREAD

**Issue by sblaisot** [MarlinFirmware/Marlin#25199]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

disabling `LED_USER_PRESET_STARTUP` and `NEO2_USER_PRESET_STARTUP` show inconsistent behaviour with first strip on at starrtup while second strip stay off

moreover, lights menu thinks first strip is off at startup when it really is on

I don't know if the best fix is to change default to turn led strip off when `LED_USER_PRESET_STARTUP` is disabled or to fix menu. However I have a personal preference for led strip to be off by default when `LED_USER_PRESET_STARTUP` is disabled.

### Bug Timeline

seen on 2.1.2 (tag)

### Expected behavior

- First neopixel strip turned off at startup when `LED_USER_PRESET_STARTUP` is disable, or at least consistent behaviour between the two neopixel strips
- Lights menu state consistent with led strip state

### Actual behavior

- First, the two strips are not consistent: disabling `LED_USER_PRESET_STARTUP` result in first strip being turned on in white at startup due to default being `(255, 255, 255, 255)` but disabling `NEO2_USER_PRESET_STARTUP` makes second led strip being off by default `(0, 0, 0, 0)`. See the difference between [this line](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/feature/leds/neopixel.cpp#L111) for the first strip and [this line](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/feature/leds/neopixel.cpp#L162) for the second strip

- Then, when disabling `LED_USER_PRESET_STARTUP` the first strip is on at machine startup but the Lights menu indicate it is off and I have to click twice in the menu to turn it off, (first it switches to on (with no effect as it is already on), then it switches correctly to off and the lights shut down)

### Steps to Reproduce

I'm using two neopixel led strips with the following configuration:

`Configuration.h`:
```
// Support for Adafruit NeoPixel LED driver
#define NEOPIXEL_LED
#if ENABLED(NEOPIXEL_LED)
  #define NEOPIXEL_TYPE           NEO_GRB // NEO_GRBW, NEO_RGBW, NEO_GRB, NEO_RBG, etc.
                                          // See https://github.com/adafruit/Adafruit_NeoPixel/blob/master/Adafruit_NeoPixel.h
  //#define NEOPIXEL_PIN                4 // LED driving pin
  #define NEOPIXEL2_TYPE          NEO_GRB
  //#define NEOPIXEL2_PIN               5
  #define NEOPIXEL_PIXELS              15 // Number of LEDs in the strip. (Longest strip when NEOPIXEL2_SEPARATE is disabled.)
  //#define NEOPIXEL_IS_SEQUENTIAL        // Sequential display for temperature change - LED by LED. Disable to change all LEDs at once.
  #define NEOPIXEL_BRIGHTNESS         127 // Initial brightness (0-255)
  //#define NEOPIXEL_STARTUP_TEST         // Cycle through colors at startup

  // Support for second Adafruit NeoPixel LED driver controlled with M150 S1 ...
  #define NEOPIXEL2_SEPARATE
  #if ENABLED(NEOPIXEL2_SEPARATE)
    #define NEOPIXEL2_PIXELS            3 // Number of LEDs in the second strip
    #define NEOPIXEL2_BRIGHTNESS      127 // Initial brightness (0-255)
    //#define NEOPIXEL2_STARTUP_TEST        // Cycle through colors at startup
    #define NEOPIXEL_M150_DEFAULT       0 // Default strip for M150 without 'S'. Use -1 to set all by default.
  #else
    //#define NEOPIXEL2_INSERIES          // Default behavior is NeoPixel 2 in parallel
  #endif

  // Use some of the NeoPixel LEDs for static (background) lighting
  //#define NEOPIXEL_BKGD_INDEX_FIRST   0 // Index of the first background LED
  //#define NEOPIXEL_BKGD_INDEX_LAST    5 // Index of the last background LED
  //#define NEOPIXEL_BKGD_COLOR { 255, 255, 255, 0 }  // R, G, B, W
  //#define NEOPIXEL_BKGD_ALWAYS_ON       // Keep the backlight on when other NeoPixels are off
#endif
```

`Configuration_adv.h`:
```
  /**
   * LED Control Menu
   * Add LED Control to the LCD menu
   */
  #define LED_CONTROL_MENU
  #if ENABLED(LED_CONTROL_MENU)
    #define LED_COLOR_PRESETS                 // Enable the Preset Color menu option
    #define NEO2_COLOR_PRESETS                // Enable a second NeoPixel Preset Color menu option
    #if ENABLED(LED_COLOR_PRESETS)
      #define LED_USER_PRESET_RED        255  // User defined RED value
      #define LED_USER_PRESET_GREEN      255  // User defined GREEN value
      #define LED_USER_PRESET_BLUE       255  // User defined BLUE value
      #define LED_USER_PRESET_WHITE      255  // User defined WHITE value
      #define LED_USER_PRESET_BRIGHTNESS 127  // User defined intensity
      //#define LED_USER_PRESET_STARTUP       // Have the printer display the user preset color on startup
    #endif
    #if ENABLED(NEO2_COLOR_PRESETS)
      #define NEO2_USER_PRESET_RED        255 // User defined RED value
      #define NEO2_USER_PRESET_GREEN      255 // User defined GREEN value
      #define NEO2_USER_PRESET_BLUE       255 // User defined BLUE value
      #define NEO2_USER_PRESET_WHITE      255 // User defined WHITE value
      #define NEO2_USER_PRESET_BRIGHTNESS 127 // User defined intensity
      #define NEO2_USER_PRESET_STARTUP        // Have the printer display the user preset color on startup for the second strip
    #endif
  #endif
```

### Version of Marlin Firmware

2.1.2

### Printer model

Slightly modified Ender-3

### Electronics

BTT SKR MIni E3 V2

### Add-ons

2 neopixel led strips, first one on chassis, second one on head

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
Closing since you've opened a PR:

- https://github.com/MarlinFirmware/Marlin/pull/25203
