### ISSUE TITLE
[BUG] #error "AUTOTEMP requires AUTOTEMP_MIN."

### ISSUE THREAD

**Issue by Dark360** [MarlinFirmware/Marlin#25198]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Attempted to compile Marlin bugfix-2.1.x using default Creality\Ender-3 Pro\CrealityV427 configuration using PlatformIO and Auto Build Marlin gives error #error "AUTOTEMP requires AUTOTEMP_MIN.".

Compiling Marlin 2.1.2 using default Creality\Ender-3 Pro\CrealityV427 configuration using PlatformIO and Auto Build Marlin works fine.

### Bug Timeline

New Bug 06/01/2023

### Expected behavior

I exxpected not to receive #error "AUTOTEMP requires AUTOTEMP_MIN." when compling.

### Actual behavior

Compile fails due to #error "AUTOTEMP requires AUTOTEMP_MIN.".

### Steps to Reproduce

1. Open Marlin-bugfix-2.1.x folder in Visual Studio Code
2. Copy Config files from Creality\Ender-3 Pro\CrealityV427 to Marlin folder
3. Compile using PlatformIO or Auto Build marlin

### Version of Marlin Firmware

Marlin-bugfix-2.1.x

### Printer model

Creailty Ender 3 Pro

### Electronics

4.2.7

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

[CrealityEnder-3 ProCrealityV427.zip](https://github.com/MarlinFirmware/Marlin/files/10361578/CrealityEnder-3.ProCrealityV427.zip)

**Comment by cbagwell** [comment]
The compile failure is related to feature just committed and you likely were unlucky and grabbed a snapshot of Configuration before it was updated.  The needed values are in latest Configuration so I would update and recopy the file again.

**Comment by DrToxic** [comment]
3 definitions are needed:
The values I used are easily changable.. but the ones I used are:
  #define AUTOTEMP_MIN 190
  #define AUTOTEMP_MAX 300
  #define AUTOTEMP_FACTOR 0.1f

and it's not worth defining them if autotemp is not enabled, so I modified Configuration_adv.h to read the following:

```C++
#if ENABLED(AUTOTEMP)
  #define AUTOTEMP_OLDWEIGHT    0.98  // Factor used to weight previous readings (0.0 < value < 1.0)
  // Turn on AUTOTEMP on M104/M109 by default using proportions set here
  //#define AUTOTEMP_PROPORTIONAL
  #if ENABLED(AUTOTEMP_PROPORTIONAL)
    #define AUTOTEMP_MIN_P      0 // (°C) Added to the target temperature
    #define AUTOTEMP_MAX_P      5 // (°C) Added to the target temperature
    #define AUTOTEMP_FACTOR_P   1 // Apply this F parameter by default (overridden by M104/M109 F)
  #endif
  #define AUTOTEMP_MIN 190
  #define AUTOTEMP_MAX 300
  #define AUTOTEMP_FACTOR 1
#endif
```

**Comment by Dark360** [comment]
> The compile failure is related to feature just committed and you likely were unlucky and grabbed a snapshot of Configuration before it was updated. The needed values are in latest Configuration so I would update and recopy the file again.

@cbagwell Which Configuration files should I be using with Marlin-bugfix-2.1.x?

https://github.com/MarlinFirmware/Configurations/archive/refs/tags/2.1.2.zip
or
https://github.com/MarlinFirmware/Configurations/archive/refs/heads/import-2.1.x.zip
or
https://github.com/MarlinFirmware/Configurations/archive/refs/heads/bugfix-2.1.x.zip

**Comment by Dark360** [comment]
I just answered my own question DUH!!

https://github.com/MarlinFirmware/Configurations/archive/refs/heads/bugfix-2.1.x.zip

**Comment by Dark360** [comment]
I just answered my own question in my edit. 

https://github.com/MarlinFirmware/Configurations/archive/refs/heads/bugfix-2.1.x.zip

Thank you for your help @cbagwell @DrToxic

**Comment by bsaverino** [comment]
This is still an issue. Using the most up to date branches as of 6 minutes ago I am getting the same error. @Dark360 what resolved this for you?

Using bugfix-2.1.x in both Marlin and Configuration.

**Comment by ellensp** [comment]
@bsaverino look again.  

https://github.com/MarlinFirmware/Configurations/blob/bugfix-2.1.x/config/examples/Creality/Ender-3%20Pro/CrealityV427/Configuration_adv.h#L455-L457

  #define AUTOTEMP_MIN          210
  #define AUTOTEMP_MAX          250
  #define AUTOTEMP_FACTOR       0.1f
