### ISSUE TITLE
G29 J Not Working Correctly

### ISSUE THREAD

**Issue by 500cubes** [MarlinFirmware/Marlin#25192]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

G29 J tilts the mesh too much creating an usable mesh. 

Original 3 points are. Bottom Middle, Top Right Corner, Top Left Corner. I tried to modify the 3 point pattern from a triangle to a straight line and it still tilted the mesh towards one side. I also tried changing the direction of the 3 point triangle with no success. I up loaded a previous build, v2.0.9.3 and G29 J worked great. 

At this point i have no idea what else it could be. 

### Bug Timeline

After installing 2.1.2

### Expected behavior

G29 J should match or be very similar to the original mesh.

### Actual behavior

G29 J will tilt the plane too much towards one side and the mesh is no longer useful.
Mesh before
![Good Mesh](https://user-images.githubusercontent.com/93151316/210686041-72167e43-e2de-4477-8205-db1e7eee4dd6.jpg)

Mesh After G29 J. You can see it is tilted more towards one side and the mesh values are different. This was done immediately after G29 P1 without physically touching the bed to rule out human error.
![After G29 J](https://user-images.githubusercontent.com/93151316/210686081-f332cfc0-4bc3-4915-b429-a8ec41fa837f.jpg)

### Steps to Reproduce

1. G29 P1
2. G29 S0
3. G29 L0
4. View Mesh in LCD to confirm mesh was loaded
5. G29 J
6. View new Mesh results in LCD. 

### Version of Marlin Firmware

2.1.2

### Printer model

Custom CORE XY

### Electronics

SKR2.0 TMC2209

### Add-ons

BL TOUCH

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config Files.zip](https://github.com/MarlinFirmware/Marlin/files/10348856/Config.Files.zip)

**Comment by titanrw** [comment]
Maybe related to:

https://github.com/MarlinFirmware/Marlin/issues/24665

2.0.9.3 was also the last one that worked for me with G29 J

**Comment by klack** [comment]
@500cubes Pardon, but what screen are you running?

**Comment by 500cubes** [comment]
> 

Sure looks like it!

**Comment by 500cubes** [comment]
> @500cubes Pardon, but what screen are you running?

its a BTT TFT70

**Comment by thisiskeithb** [comment]
Fixed in https://github.com/MarlinFirmware/Marlin/pull/25453
