### ISSUE TITLE
Compiling bugfix2.1.x for ANET A8 on BigTreeTech SKR Mini E3 v3.0

### ISSUE THREAD

**Issue by SpicyTaco28** [MarlinFirmware/Marlin#25219]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Compiling errors upon build

### Bug Timeline

1/9/23

### Expected behavior

I expected it to build

### Actual behavior

alot of errors

### Steps to Reproduce

compile marlin for anet on BTT skr mini e3 v3.0

### Version of Marlin Firmware

bugfix2.1.x

### Printer model

Anet A8

### Electronics

BigTreeTech SKR Mini E3 V3.0

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

https://pastebin.com/SzC8ZBBL
[CONFIGS.zip](https://github.com/MarlinFirmware/Marlin/files/10377567/CONFIGS.zip)

**Comment by thisiskeithb** [comment]
Per the error log:

> #error "SERIAL_PORT must be from 1 to 6, or -1 for Native USB."

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
