### ISSUE TITLE
SD Cards not working (class 10)

### ISSUE THREAD

**Issue by saidmsbah** [MarlinFirmware/Marlin#25211]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

SD Cards not working (class 10) it 16G FAT32
How can I get it works???

### Version of Marlin Firmware

Marlin2.1.2

### Printer model

Msk-tinybee 

### Electronics

Esp32

### Additional information & file uploads

I have 16 g sd card class 10
I can't get it works

**Comment by ellensp** [comment]
It either works, or it dos not work.  That is it.

This is an over simplification, but there are basically two SD Card interfaces, the older simpler SPI and the newer SDIO

The Mks-tinybee uses the older SPI

Quite a few modern sd cards no longer support SPI. or have buggy SPI implementations, as they are designed for SDIO devices.

No there is no label to say what interface it supports. 

All you can do is use the sdcard in something else and try other cards.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
