### ISSUE TITLE
[FR] (feature summary) Fan Invert (Usefully for PWM Fans)

### ISSUE THREAD

**Issue by Mordi1984** [MarlinFirmware/Marlin#25215]
### Is your feature request related to a problem? Please describe.

Fan Inversion for PWM Fans.

### Describe the feature you want

I have an Octopus Pro F429 and want to controll one Fan (24V Papst) with PWM for my Chamber Heater. If i connect it to my "CNC-FAN" aka PWM Fan it spins a way to much and very loud (almost 90db).
If i Set the the Fan to 100% or 255 the Fan stops.
I would only use an Fan Range to 40% at much.
It is the only one PWM Fan i have in my Setup. all other are regular Fans.

Kind Regards.

Mordi

**Comment by thisiskeithb** [comment]
> I would only use an Fan Range to 40% at much.

This exists as `FAN_MAX_PWM`. A value of 102 would be 40%

https://github.com/MarlinFirmware/Marlin/blob/202114c018dc22513e74c5b76e92ecda53214310/Marlin/Configuration_adv.h#L573-L586

**Comment by Mordi1984** [comment]
Hwllo Keith.
Thank you for your help.
I habe a Question. 255 is in my case 0 Fan speed and 153 would be 40% and 0 is full speed.
Can i reverse that settings?
What do my other Fans do! Will they also get inverted?
They run also on PWM Fan pins.

Maybe that question is wird, but i need to understand this.

Kind regards,
Mordi

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by thisiskeithb** [comment]
Add this to your config to invert fan PWM:

`#define FAN_INVERTING`

**Comment by Mordi1984** [comment]
Hello Keith
Is
#define FAN_INVERTING_5 also possible to invert only one fan index 5?
I want to invert only one fan, because 3 are connected.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by thisiskeithb** [comment]
> Is #define FAN_INVERTING_5 also possible to invert only one fan index 5?

Not currently. Similar to `FAN_MIN/MAX_PWM`, all fans are configured by a single `FAN_INVERTING` setting.

**Comment by Mordi1984** [comment]
Well, also it would be a feature we may need. Or i need to reverse that with an Hardware solution. Or i need to change all fans.

What do you think, is there an option that it may get programmed to prevent Hardware modifications?

Kind regards Keith and i want to thank you for your Help.




Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
