### ISSUE TITLE
[BUG] Marlin reads wrong temperature

### ISSUE THREAD

**Issue by Riky04-theSwagOne** [MarlinFirmware/Marlin#25216]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi, I was trying to upgrade my Ender 5 Plus with an SKR 1.4 Turbo and a RepRap full graphics smart controller, and I ran into a problem. When I boot up the printer everything is normal except for the temperature, which reads a value between 80 and 120 Celsius. This is impossible due to my room temperature being at 20 Celsius and the printer being cooled down. At first, I thought it was a problem with the thermocouple but I quickly deleted this possibility, because both the extruder and the printer were showing the same exact temperature, even when it changed (yes, it's not stable, and that's why I don't think my board is just broken). The printer doesn't give me any errors, which is strange because thermal runaway protection is enabled. I tried changing the brand of the thermocouple, tried changing the value on `#define TEMP_SENSOR_0` and `#define TEMP_SENSOR_BED`, but it doesn't change. If I try setting the value to 4 (10kOhm thermocouple) it does give me a thermal runaway alarm.
Even after unplugging the connectors it still shows that temperature (as you might know, it is supposed to show something like -15 Celsius, surely not 120).

### Bug Timeline

09/01/2023

### Expected behavior

Showing about 20 Celsius.

### Actual behavior

Showed 120 Celsius at room temperature.

### Steps to Reproduce

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/10375544/Config.zip)

### Version of Marlin Firmware

Marlin-bugfix-2.1.x

### Printer model

Creality Ender 5 Plus

### Electronics

SKR 1.4 turbo, reprap full graphics smart controller (ripoff from BTT)

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
> Even after unplugging the connectors it still shows that temperature

Your board is damaged and should be replaced. Marlin will display `ERR` when you don't have a thermistor attached.
