### ISSUE TITLE
Error "Z_PROBE_SPEED_FAST is now Z_PROBE_FEEDRATE_FAST.\"

### ISSUE THREAD

**Issue by GRAZIANO2209** [MarlinFirmware/Marlin#25213]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Error "Z_PROBE_SPEED_FAST is now Z_PROBE_FEEDRATE_FAST

Error massage Platformio:

	SanityCheck.h",
	"message": "#error \"Z_PROBE_SPEED_FAST is now Z_PROBE_FEEDRATE_FAST.\"",
	"startLineNumber": 147,
	"startColumn": 4,
	"endLineNumber": 147,
	"endColumn": 4

	"motion.h",
	"message": "identificatore \"Z_PROBE_FEEDRATE_FAST\" non definito",
	"source": "C/C++",
	"startLineNumber": 69,
	"startColumn": 44,
	"endLineNumber": 69,
	"endColumn": 54

	"motion.h",
	"message": "'Z_PROBE_FEEDRATE_FAST' was not declared in this scope; did you mean 'Z_PROBE_FEEDRATE_SLOW'?",
	"startLineNumber": 69,
	"startColumn": 55,
	"endLineNumber": 69,
	"endColumn": 55

### Bug Timeline

New problem started when I run firmware compilation

### Expected behavior

I expected you to compile

### Steps to Reproduce
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10369556/Configuration.zip)

_No response_

### Version of Marlin Firmware

2.1.x. bugfix

### Printer model

DELTA Printer

### Electronics

BTT SKR PRO 1.1

### Add-ons

BLTouch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Copying the same parameters of version 2.0.7.2 that platformio compiles regularly, on the 2.1.x bugfix I can not complete the compilation by mistake indicated in the title.

**Comment by thisiskeithb** [comment]
> `#error "Z_PROBE_SPEED_FAST is now Z_PROBE_FEEDRATE_FAST.`

You need to update your config and replace `Z_PROBE_SPEED_FAST` with `Z_PROBE_FEEDRATE_FAST`.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by GRAZIANO2209** [comment]
I did the configuration ex new reporting only the parameters of the mechanics of the printer, I do not understand where the error comes from.

**Comment by thisiskeithb** [comment]
You have `#define Z_PROBE_SPEED_FAST HOMING_FEEDRATE_Z` on line 1506 in `Configuration.h`.

This isn't a support forum, so please use the links above for further help with your configuration.
