### ISSUE TITLE
[BUG] Serial0 on Ramps+Mega not working

### ISSUE THREAD

**Issue by italocjs** [MarlinFirmware/Marlin#25234]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Issue: Serial0 does not work both ways if connected directly to the GPIO 0 and GPIO 1.

I've tried pretty much everything i know of to get it working, reversed RX/TX, tried another terminal, and checked the baudrate several times, tried a logic level shifter, reduced baud speed, all with no effect.

I can read the TX (marlin boot messages) but every command sent is ignored.  I tried connecting the serial to D0 / D1 on aux1 port,  thought it was bad then tried soldering directly to the arduino terminal (also reverted them to be sure), and still the same result, i can read but not send.

The only way i found to make a serial connection was using serial 1 (also moving the endstop zmin pin to somewhere else on pins_ramps to free the pins 18 and 19 which are used by serial1).

Could this be a limitation from Arduino Mega? (because of the CH340 is already connected to the TX line).  Or these pins had worked in the past?

Here are my current configs (using serial 0 and serial1)
[config.zip](https://github.com/MarlinFirmware/Marlin/files/10404137/config.zip)

### Bug Timeline

I've never used this feature before

### Version of Marlin Firmware

2.1.2

### Electronics

Ramps + arduino Mega + Fullgraphic LCD + BLTouch

### Bed Leveling

ABL 3-point

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
Mega2560 Hardware:   USB cable -> USB/serial chip ->  D0/D1

This is how most  talk to the ramps/mega every single day.

You cannot use D0/D1 while the USB cable is also receiving data, ideally you need to remove the usb/serial chip if using D0/D1
