### ISSUE TITLE
[ISSUE] Marlin 2.1.2 SKR Mini E3 V2 in Ender 3 Pro error compiling.

### ISSUE THREAD

**Issue by ZeGhomst** [MarlinFirmware/Marlin#25239]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Been trying to compile some new software (I installed a new hot end and dual Z axis and want to make sure everything is fresh so it'll work) but it keeps failing to compile. Errors listed below.

In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:76:4: error: #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
   76 |   #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:81:4: error: #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
   81 |   #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:596:4: error: #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
  596 |   #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL_SPI.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:76:4: error: #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
   76 |   #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL_SPI.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:81:4: error: #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
   81 |   #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL_SPI.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:596:4: error: #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
  596 |   #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\Servo.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:76:4: error: #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
   76 |   #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\Servo.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:81:4: error: #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
   81 |   #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\Servo.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:596:4: error: #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
  596 |   #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:76:4: error: #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
   76 |   #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:81:4: error: #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
   81 |   #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:596:4: error: #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
  596 |   #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_flash.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:76:4: error: #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
   76 |   #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_flash.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:81:4: error: #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
   81 |   #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_flash.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:596:4: error: #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
  596 |   #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_bl24cxx.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:76:4: error: #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
   76 |   #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_bl24cxx.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:81:4: error: #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
   81 |   #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_bl24cxx.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:596:4: error: #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
  596 |   #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\HAL.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:31: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                               ^
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\HAL_SPI.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:31: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                               ^
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:45: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                                             ^
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:45: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                                             ^
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\Servo.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:31: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                               ^
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:45: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                                             ^
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_if_iic.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:76:4: error: #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
   76 |   #error "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_if_iic.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:81:4: error: #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
   81 |   #error "Your Configuration_adv.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration_adv.h."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_if_iic.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:596:4: error: #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
  596 |   #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF is now TEMP_SENSOR_REDUNDANT_MAX_DIFF"
      |    ^~~~~
*** [.pio\build\STM32F103RC_btt_USB\src\src\HAL\STM32\HAL_SPI.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_USB\src\src\HAL\STM32\HAL.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:31: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                               ^
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:45: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                                             ^
*** [.pio\build\STM32F103RC_btt_USB\src\src\HAL\STM32\Servo.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\eeprom_flash.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:31: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                               ^
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:45: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                                             ^
*** [.pio\build\STM32F103RC_btt_USB\src\src\HAL\STM32\MarlinSerial.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\eeprom_bl24cxx.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:31: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                               ^
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:45: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                                             ^
*** [.pio\build\STM32F103RC_btt_USB\src\src\HAL\STM32\eeprom_flash.cpp.o] Error 1
*** [.pio\build\STM32F103RC_btt_USB\src\src\HAL\STM32\eeprom_bl24cxx.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\eeprom_if_iic.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:31: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                               ^
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:1361:26: error: 'ADVANCE_K' was not declared in this scope; did you mean 'LIN_ADVANCE_K'?
 1361 |     static_assert(WITHIN(ADVANCE_K, 0, 10), "ADVANCE_K must be from 0 to 10 (Changed in LIN_ADVANCE v1.5, Marlin 1.1.9).");
      |                          ^~~~~~~~~
Marlin\src\HAL\STM32\../../inc/../core/macros.h:285:45: note: in definition of macro 'WITHIN'
  285 | #define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
      |                                             ^
*** [.pio\build\STM32F103RC_btt_USB\src\src\HAL\STM32\eeprom_if_iic.cpp.o] Error 1

### Expected behavior

it to compile correctly

### Actual behavior

It gave me a bunch of errors

### Version of Marlin Firmware

2.1.2

### Printer model

Ender 3 Pro

### Electronics

SKR E3 Mini V2

### Add-ons

CR Touch, Dual Z Axis, Addon Hot End, ETC

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Trouble Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/10416425/Trouble.Marlin.zip)

**Comment by ellensp** [comment]
"Your Configuration.h file is for an old version"

Config file is for Marlin 2.0.8.1  probably from https://github.com/MarlinFirmware/Configurations/archive/refs/heads/release-2.0.8.1.zip
Must be used with code of the same version https://github.com/MarlinFirmware/Marlin/archive/refs/tags/2.0.8.1.zip

If your using newer code, then use newer config files  https://github.com/MarlinFirmware/Configurations
Scroll down, and select the version that matches the code version your using.

This is a user error

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
