### ISSUE TITLE
Marlin Configuration tool 

### ISSUE THREAD

**Issue by gsuresh2u** [MarlinFirmware/Marlin#25246]
### Is your feature request related to a problem? Please describe.

Hi, this is my first project in Python
done some work configuration tool, its working fine
i think i have completed more than 90% of work
link to video : https://www.youtube.com/watch?v=RHR9XUzGdhA

![Config](https://user-images.githubusercontent.com/39871361/212684662-16fe5553-5eb1-4944-bb7f-b393fc4b9882.jpg)
![Levelling](https://user-images.githubusercontent.com/39871361/212684693-2b825f1f-de2e-48b2-bec0-cb1dd14c160b.jpg)
![Nozzle](https://user-images.githubusercontent.com/39871361/212684703-0a7412db-49cd-4560-a0be-4bc9d46b9f90.jpg)
![PSU Control](https://user-images.githubusercontent.com/39871361/212684711-b891f373-360a-4bbf-b9cf-3dc775a739fa.jpg)
![Additional](https://user-images.githubusercontent.com/39871361/212684730-7d796f4d-441a-4361-b638-4951a12bdd5d.jpg)

![Config_adv](https://user-images.githubusercontent.com/39871361/212684733-4ea4b384-4d66-4797-aa17-b56545c93819.jpg)

### Are you looking for hardware support?

after modifying the congih files with this tool, i found a problem in VS code
that is, when we enable a feature like LIN_ADVANCE, under that options, the lines are still not showing in bright color
please check the attached image
![Error](https://user-images.githubusercontent.com/39871361/212685169-0e63b8a9-cf7a-4c8d-8b8c-4dc034c0e3bf.jpg)

### Describe the feature you want

if anyone try to implementt this tool, i am attaching the all source code
all drivers, motherboards, etc.. are taking from txt files
[Marlin Configurator.zip](https://github.com/MarlinFirmware/Marlin/files/10426064/Marlin.Configurator.zip)

### Additional context

Please help me on one thing
In configuration_adv.h file, if we enable #define CONFIG_EXPORT 2 .
it is exporting present configuraion to file config.ini
if we download any new version is there any option to import that config.ini to new version ?
please let me know
If there is option to import that confog.ini to new version, it will be very usefull to all Marlin users

**Comment by EvilGremlin** [comment]
This is what Scott doing with ABM plugin, all late changes in configs formatting etc are so plugin can have universal parser agnostic to config changes. But i like your layout ideas more, because, well, there is layout present.
> problem in VS code

this is normal, intelisense being dumb

**Comment by thisiskeithb** [comment]
As mentioned above, there is already a tool in place: https://github.com/MarlinFirmware/AutoBuildMarlin

**Comment by gsuresh2u** [comment]
But Auto build Marlin is not configuration tool
It just build firmware

Is there any tool available to import Config.ini file settings to new version of Marlin?

**Comment by thisiskeithb** [comment]
> But Auto build Marlin is not configuration tool
It just build firmware


it does. Take a look at the other branches: https://github.com/MarlinFirmware/AutoBuildMarlin/branches

**Comment by gsuresh2u** [comment]
Sorry for my ignorance
Can you please give more details on how to use that 
presently its saying "Configration tool under construction"
