### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by 0viper8** [MarlinFirmware/Marlin#25254]
### Is your feature request related to a problem? Please describe.

Greeting

The problem is that I have no place to write in the marlin that it is a dryer, or something like a 2nd chamber that is used for listening to the filament.
The dryer is a closed box with a heater and a fan.
dryer is part of the housing and is currently written in marlin as E1 extruder, but that can sometimes cause problems.
I don't know how to properly solve the problem, so I would be happy if you could tell me how to solve the problem or simply put a new heater option, dryer or 2nd chamber.

### Are you looking for hardware support?

custom made printer (similar like creality)
board btt octopus pro 1.0v
direct drive Biqu h2 500c
bltouch
double z
btt tft 50 screen
custom made dryer (part of printer frame)
multi color
other

### Describe the feature you want

I asked people how to solve the problem... the solution was a redundant heater... but I don't know how to set it to work properly.

The request is simple ... put the dryer option for the heater option. And that it works not connected to other heaters that will cause problems.

### Additional context

https://pasteboard.co/jDXPiC0mxeWV.jpg

i hope so that u will help me

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
