### ISSUE TITLE
Thermistor 66 Requires MCLTEA >5

### ISSUE THREAD

**Issue by dylanmaloney** [MarlinFirmware/Marlin#25269]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have configured and configured and reconfigured Config_adv.h over and over and it will not resolve this error message when trying to build the firmware.  #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5." I have set it to 5, 10, 4, and so on and it will not change from the exact same error message.

Here is the entire Terminal:

In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL_SPI.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_bl24cxx.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\Servo.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_flash.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_if_iic.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_sdcard.cpp:31:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_wired.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\sdio.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\tft\../../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\tft\gt911.cpp:26:
Marlin\src\HAL\STM32\tft\../../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_sram.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\fast_pwm.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\tft\../../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\tft\tft_fsmc.cpp:27:
Marlin\src\HAL\STM32\tft\../../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\fastio.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\tft\../../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\tft\tft_spi.cpp:27:
Marlin\src\HAL\STM32\tft\../../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\timers.cpp:26:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\tft\../../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\tft\tft_ltdc.cpp:26:
Marlin\src\HAL\STM32\tft\../../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\tft\../../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\tft\xpt2046.cpp:27:
Marlin\src\HAL\STM32\tft\../../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\usb_host.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\shared\HAL.cpp:27:
Marlin\src\HAL\shared\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\shared\Delay.cpp:25:
Marlin\src\HAL\shared\../../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\MarlinSerial.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\HAL.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\eeprom_bl24cxx.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\HAL_SPI.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\eeprom_flash.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\Servo.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\eeprom_sdcard.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\tft\tft_fsmc.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\eeprom_wired.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\eeprom_if_iic.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\fast_pwm.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\fastio.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\tft\gt911.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\sdio.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\timers.cpp.o] Error 1
In file included from Marlin\src\HAL\shared\../../core/../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\shared\../../core/serial.h:24,
                 from Marlin\src\HAL\shared\MinSerial.h:24,
                 from Marlin\src\HAL\shared\MinSerial.cpp:22:
Marlin\src\HAL\shared\../../core/../inc/SanityCheck.h:2368:6: error: #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
 2368 |     #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5."
      |      ^~~~~
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\eeprom_sram.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\tft\tft_spi.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\tft\xpt2046.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\tft\tft_ltdc.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\STM32\usb_host.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\shared\HAL.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\shared\Delay.cpp.o] Error 1
*** [.pio\build\STM32F103RC_creality\src\src\HAL\shared\MinSerial.cpp.o] Error 1

### Bug Timeline

Started today

### Expected behavior

I expected a completed build of custom marlin to run my 500 degree hotend.

### Actual behavior

Receiving error "#error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED ≥ 5." "

### Steps to Reproduce

Update Config and Config_adv to run 500 degree hotend (thermistor and heater core)
Build

### Version of Marlin Firmware

2.1.2

### Printer model

E3 v2

### Electronics

Dyze hi-temp thermistor

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

None

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin Config Github.zip](https://github.com/MarlinFirmware/Marlin/files/10476616/Marlin.Config.Github.zip)

**Comment by ellensp** [comment]
User cannot follow/understand simple error messages.

Enable the following in Configuration_adv.h

#define MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED 5

the error message then changes to require the following also in Configuration_adv.h

#define MILLISECONDS_PREHEAT_TIME 30000

This leads to

Marlin/src/lcd/e3v2/proui/dwin.cpp:2683:20: error: 'class Temperature' has no member named 'updatePID'
 2683 |     thermalManager.updatePID();

This is because you enabled MPCTEMP which is not supported in 2.1.2

Currently you require the latest bugfix to use MPCTEMP with proui

**Comment by ellensp** [comment]
Updated config for current bugfix 2.1.x
[bugfix 2.1.x configs.zip](https://github.com/MarlinFirmware/Marlin/files/10476841/bugfix.2.1.x.configs.zip)
