### ISSUE TITLE
[FR] Add Hardware support for  CREALITY_CR4NTxxC10 - New STM32F401RET6 with onboard TMC2209's in UART mode

### ISSUE THREAD

**Issue by Tinker012** [MarlinFirmware/Marlin#25277]
### Is your feature request related to a problem? Please describe.

This request is not related to a problem but rather for hardware support

### Are you looking for hardware support?

I am looking for Hardware support for the newly released Creality E3-Free-runs-silent-motherboard
identified by Creality as  CREALITY_CR4NTxxC10  

This board is a ARM Cortex-M4/STM32F401RET6 with onboard TMC2209's in UART mode.

The files released by Creality for this board are located at https://github.com/CrealityOfficial/E3-Free-runs-Silent-Motherboard/tree/main/example/Marlin

### Describe the feature you want

I would like to see this board added to MarlinFirmware going foreward

**Comment by ellensp** [comment]
Looks like this, if anyone is interested

<img src="https://pic2-cdn.creality.com/vip_mall/627b63f0-5112-4139-a5bf-2852fdcd9fb8">

More details can be found here https://mvip.creality.com/en/goods/goodsDetail/1888

**Comment by IAmBunko** [comment]
Just got this board in. Would love to see support soon!

**Comment by Bob-the-Kuhn** [comment]
I've added PR #25636 to implement this request.

I don't have a board to test with.  Would appreciate someone to download the code from the PR and see if it really works.  You'll have to use bugfix-2.1.x config files to test.

**Comment by thisiskeithb** [comment]
> I've added PR https://github.com/MarlinFirmware/Marlin/pull/25636 to implement this request.

Closing since a PR has been opened.
