### ISSUE TITLE
[BUG] Part cooling fan noise at 75-99%

### ISSUE THREAD

**Issue by Antibodyarmy** [MarlinFirmware/Marlin#25272]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I recently updated my Biqu BX with the latest release and attempted to see if this was fixed in the latest bugfix both have a electrical fan noise on my 5015 part cooling fan. The noise is a electrical whine, and starts at 75% but stops at 100%. I've tried another fan. My firmware was Luke harrison's firmware based on 2.0.6.1 but modified to have cancel objects and steps modified for 1.8° x,y,z motors, and lower current ratings for x,y,z than what luke provides for the stock 0.9° motors. I've tried replacing the 5015 part cooling fan with a new one both are WINSINN 5015 fans. 

### Expected behavior

a fan noise of about 50-56 db

### Actual behavior

electrical noise louder than the entire printer at high accelerations and the planes that fly over my apartment. 

### Steps to Reproduce

build firmware, slice with super sclicer or prusa slicer, set fan to 60-100% during print after 75% up to 99% a loud electrical hum starts. 

### Version of Marlin Firmware

Latest bugfix, 2.1.2

### Printer model

Biqu BX

### Electronics

1.8° motors, 5015 part cooling fan upgrades

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10484509/configuration.zip)

**Comment by EvilGremlin** [comment]
Not a bug, you're have to tune fan PWM settings for your particular one.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server (). Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.
