### ISSUE TITLE
Thermistor 66 Mintemp error

### ISSUE THREAD

**Issue by dylanmaloney** [MarlinFirmware/Marlin#25273]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Just upgraded to Thermistor 66. Newly built marlin that I'm sure needs some work. Anytime I run a PID tune or MPC I get error MinTemp before it begins heating. I have set it to 30000ms preheat time and 10 low temp errors.

### Bug Timeline

Started today

### Expected behavior

Heat upon request

### Actual behavior

Min Temp error kill printer

### Steps to Reproduce

#define MILLISECONDS_PREHEAT_TIME 30000
#define MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED 10
Run MPC or PID through Marlin Professional

### Version of Marlin Firmware

2.1.3

### Printer model

E3 v2

### Electronics

Dyze hi-temp thermistor

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10486375/Configuration.zip)

**Comment by ellensp** [comment]
You have not tryed bugfix
your configs are 02010200  bugfix is 02010300

and bugfix has

#elif defined(MILLISECONDS_PREHEAT_TIME)
  #error "MILLISECONDS_PREHEAT_TIME is now PREHEAT_TIME_HOTEND_MS."

Unless you or running official firmware from https://github.com/MarlinFirmware/Marlin we cannot help you.
Code from https://github.com/mriscoc/ is not official marlin. It is a fork, Any and all support must be obtained form the forks maintainer
