### ISSUE TITLE
New type of extruder change

### ISSUE THREAD

**Issue by Nico4589** [MarlinFirmware/Marlin#25284]
### Is your feature request related to a problem? Please describe.

Hi, my custom 3d printer has two hotends mounted in the same block at 30mm distance from nozzle to nozzle, with a solenoid mechanism to lift them. However, the two hotends are too heavy to be lifted by the solenoids, therefore in the coordinates X0 and X550 there are two ramps where the block of the hotends approaches to make them lift. There is no extruder change mode of this type on the firmware and the ones modified for my configuration are not suitable. Would it be possible to implement this type of extruder change? thank you

### Describe the feature you want

This type of extruder change should allow the print head to move in two X coordinates, slowing down its speed when it approaches the coordinate. Once the coordinate has been reached, the solenoid corresponding to the nozzle that we want to shield must be activated, in order to make it lift and disable the other solenoid to make the other hotend descend. Finally return to the printing point with the offset set between two nozzles.

**Comment by EvilGremlin** [comment]
Done already, just not merged https://github.com/MarlinFirmware/Marlin/pull/24553
