### ISSUE TITLE
[FR] question of staple areas

### ISSUE THREAD

**Issue by stef-ladefense** [MarlinFirmware/Marlin#25283]
### Is your feature request related to a problem? Please describe.

tray fixed by 4 clamps in the corners

### Describe the feature you want

is there an option for the head to avoid these areas without reducing bands counts all around

merci

**Comment by Bob-the-Kuhn** [comment]
You can set the bed size and offsets so that a print won't hit the clips.  This involves setting:
X_BED_SIZE
Y_BED_SIZE
X_MIN_POS 
Y_MIN_POS 
Z_MIN_POS 
X_MAX_POS 
Y_MAX_POS 

You may also want to set a minimun Z height when homing X and Y so that the head doesn't hit the clips.  Set Z_HOMING_HEIGHT for this.

**Comment by stef-ladefense** [comment]
ok thank you, that amounts to defining a smaller square with the inaccessible turn suddenly?
Too bad we can't define 4 small areas where the clips are located so that the head doesn't go inside.

**Comment by plampix** [comment]
That would require changes to your slicer as well, as it probably assumes a rectangular (or circular) bed.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
