### ISSUE TITLE
Documentation not mentionning DIRECT_PIN_CONTROL is required for M226

### ISSUE THREAD

**Issue by Carlsans** [MarlinFirmware/Marlin#25286]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After upgrading to 2.1.x, I made a few change and forgot to activate DIRECT_PIN_CONTROL 
In the document, there usually is a flag if a M command need change in configuration. For this page there is not :
https://marlinfw.org/docs/gcode/M226.html
Thanks for your great software, I love it !!

### Version of Marlin Firmware

2.1.x

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
Fixed in https://github.com/MarlinFirmware/MarlinDocumentation/pull/481
