### ISSUE TITLE
Extruder change Direction after Partcooling Fan switched on

### ISSUE THREAD

**Issue by Avatarsia** [MarlinFirmware/Marlin#25292]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

after the partcooling fan start, the extruder change his direction

same with relative and absolute extruder coordinates.
also when partcooling fan is disconnected
same result with new sliced or old sliced files by different persons

i sliced an extra file without coolingfan, it runs fine untill i start the partcooling by hand
### Expected behavior

It Should contine with extrusion not change extruder direction

### Actual behavior

the extruder change his direction

### Steps to Reproduce

print, activate partcooling fan, extruder change direction

### Version of Marlin Firmware

 bugfix-2.1.x

### Printer model

sidewinder x2

### Electronics

stock

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10510646/Configuration.zip)

**Comment by eduard-sukharev** [comment]
does this behaviour persist when using `FAN1_PIN` instead of `PC7`?
Is it the same with `FAN2_PIN`?

**Comment by Avatarsia** [comment]
> does this behaviour persist when using `FAN1_PIN` instead of `PC7`? Is it the same with `FAN2_PIN`?

FAN1_PIN - No  
FAN2_PIN - yes

**Comment by eduard-sukharev** [comment]
Am I reading you right?

---
```c++
#define E0_AUTO_FAN_PIN FAN1_PIN
```
works as expected ✔️ 

---

```c++
#define E0_AUTO_FAN_PIN FAN2_PIN
```
switches extruder direction when part cooling is enabled ❌

**Comment by ellensp** [comment]
Part cooling is FAN_PIN, not E0_AUTO_FAN_PIN, there is no software control over E0_AUTO_FAN_PIN

FAN_PIN is controlled with M106/M107

The description says "after the part cooling fan start, the extrudet change his direction"
So after a M!06

**Comment by eduard-sukharev** [comment]
Did you also happen to change your [pins definition file for your board](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/pins/stm32f4/pins_ARTILLERY_RUBY.h)? If so, please, attach it to original issue report, too

**Comment by Avatarsia** [comment]
no exatly the oppsite 
FAN1_PIN - it works wrong
FAN2_PIN - it works as expected

**Comment by Avatarsia** [comment]
> Did you also happen to change your [pins definition file for your board](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/pins/stm32f4/pins_ARTILLERY_RUBY.h)? If so, please, attach it to original issue report, too

no i kept it original

**Comment by eduard-sukharev** [comment]
I've looked up the `M106/M107` gcode processing commands and didn't find anything related to extruder handling that might've caused any issues. On the other hand, I'm no Marlin developer and my very limited knowledge of the codebase didn't help here.
My guess here would be hardware issue.

**Comment by Avatarsia** [comment]
> I've looked up the `M106/M107` gcode processing commands and didn't find anything related to extruder handling that might've caused any issues. On the other hand, I'm no Marlin developer and my very limited knowledge of the codebase didn't help here. My guess here would be hardware issue.

i will try a new board today and will update you soon

**Comment by Avatarsia** [comment]
> I've looked up the `M106/M107` gcode processing commands and didn't find anything related to extruder handling that might've caused any issues. On the other hand, I'm no Marlin developer and my very limited knowledge of the codebase didn't help here. My guess here would be hardware issue.

after reinstall vsc it works again, looks like some kind of strange compiling error
