### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by rbora13** [MarlinFirmware/Marlin#25291]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi,
It's not a bug but a little mistake in comments, I guess. In configuration_adv.h file, Multi-Stepper / Multi-Endstop -> Multi-Z steppers section, this comment // Z2 offset relative to Y endstop (same for Z3 and Z4) should be // Z2 offset relative to **Z** endstop

### Bug Timeline

It first started with V2.0.9.4

### Expected behavior

as described, I think the Z2/Z3/Z4 offset should be relative to Z and not to Y

### Actual behavior

As it's just comments, so nothing

### Steps to Reproduce

there is no procedure as it's just comments

### Version of Marlin Firmware

V2.0.9.4

### Printer model

NA

### Electronics

NA

### Add-ons

na

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/10510113/Configuration_adv.zip)
This is the standard configuration_adv.h file supplied in Marlin V2.1.2

**Comment by thisiskeithb** [comment]
Fixed in https://github.com/MarlinFirmware/Marlin/pull/25295
