### ISSUE TITLE
[FR] auto power off when print is finished

### ISSUE THREAD

**Issue by GG0101** [MarlinFirmware/Marlin#25336]
### Describe the feature you want

I found my self offen in the situation that i run prints over night. And every time i do so, i am asking my self why my printer has to waste unnecessary energy after it finished his job. I Imagine that marlin provides an extra command that will turn off the printer and if i want to use this feature i have to include this command at the end of a print.

**Comment by thisiskeithb** [comment]
> I Imagine that marlin provides an extra command that will turn off the printer and if i want to use this feature i have to include this command at the end of a print.

[`M81` - Power Off](https://marlinfw.org/docs/gcode/M081.html)
