### ISSUE TITLE
[BUG] Sidewinder X1 MKS Gen L Fan issue

### ISSUE THREAD

**Issue by braintr84** [MarlinFirmware/Marlin#25354]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

since upgrading to Marlin 2.1.2. (Digant build to work with Hemera) part cooler fan does not work correctly, when set to 255 via M106 Fan turns at full speed, on 254 fan barely turns( with strange wining noise), on 253 stops completly. tried also with spare fan. 

### Bug Timeline

since upgrading to 2.1.2

### Expected behavior

Fan turns according to M106 value, 0 = 0, 255= max, 128 = 50% etc

### Actual behavior

M106 S255 = max speed 
M106 S254 = barely turns, wining noise
M106 S253 = fan stops completely
M106 >S253 = no movement

### Version of Marlin Firmware

2.1.2

### Printer model

Artillery Sidewinder X1

### Electronics

Stock board, but with BLW touch waggster mod & E3D Hemera

### Add-ons

only above listed

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

IdeaMaker

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
This has already been reported and a PR created to fix it.
See https://github.com/MarlinFirmware/Marlin/pull/25343
