### ISSUE TITLE
Filament runout sensor turning off

### ISSUE THREAD

**Issue by jmger** [MarlinFirmware/Marlin#25351]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I installed the BTT Filament Runout Sensor. I just installed stable version 2.1.2. When I go to print. I have Filament RUNOUT turned on. It goes to unload the filament then I reload filament. Great so far. I then have the option on my printer a Creality Ender 3 Max with BTT Octopus Pro F429 main board. On the display it shows PURGE or FILAMENT ON as my only two options. There is no Continue Option. If I click on Filament Option I get another screen that has a Continue Option. But I have discovered that by pressing the Filament Option that disables, set the sensor to off. If I then go back in and manually turn the sensor on again then the sensor goes into a M600 and wants to unload and purge more filament. Ending up in a loop. This was happening in Version 2.0.x also. I wondered why the BTT filament sensor was not working at all after I had a filament runout.

### Bug Timeline

Sort of both a new issue reporting but this happens in the older 2.0.x marlin firmware

### Expected behavior

I expect to see a Continue button option in the on screen menu. 

### Actual behavior

As described above the Filament Runout sensor turns OFF

### Steps to Reproduce

Start a print and let the Filament runout sensor load the filament then the error or issue should show up in the menu screen that is displayed.

### Version of Marlin Firmware

I am away from my printer at this time

### Printer model

Ender 3 Max with BTT Octopus Pro 429 main board

### Add-ons

BTT Octopus Pro 429 BTT filament runout sensor

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Other (explain below)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Let me know and I can upload my con fig later when I get home if needed.

**Comment by jmger** [comment]
I just installed the Trianglelabs Filament Runout Sensor. To replace my BTT Smart Sensor. I know that the wiring to my BTT Octopus Pro 429 board and the Trianglelabs sensor is installed correctly. TEST: of switch. I get a power light GREEN. I get no RED light when filament is inserted. And I get a blinking red light when filament is removed. So that is all working correctly. I haven't check the state level, yet. I still get... 1) a filament runout at the beginning of every print. And I still get the screen as described in my above post. I tried disabling the command for motion/movement of the filament. Since this sensor does not have this option. And I thought that might be the issue. No change from what I described above. Is there something else that I might have enabled that I need to disable, possibly? I have the FIL_RUNOUT_STATE set to LOW. One question: what triggers a filament Runout at the beginning of my print? I looked in my start Gcode in CUra but I don't see any commands.

**Comment by PoisonLavaLucas** [comment]
I have this same issue with the firmware off the creality website on my ender 3 pro. did you ever find a solution?

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
