### ISSUE TITLE
Erratic Behavior and Loss of Steppers

### ISSUE THREAD

**Issue by jmb-555** [MarlinFirmware/Marlin#25353]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The latest stable marlin was just flashed to a stock Ender 5 Pro with the stock ender 5 config files and setup. A gcode extrusion calibration file was tested and the machine was not making x or y movements. The machine basically sat there and aggressively gushed out filament at an extrusion rate of probably 100X normal flow rate. The extruder was skipping worse than anything I've seen in my 8-9 years of 3d printing. The file was printed again and the same exact thing happened. Manual gcode was sent in from the Arduino IDE over serial. The machine replied back "Ok" to both x and y gcode commands but there was no movement. The machine was restarted and everything worked as expected. The previously mentioned gcode file printed as expected. I wish i had a log file or something to attach because it seems like it would help. The config files are attached as well as the gcode that gave the issues. Is seems unlikely that the stock Ender 5 profile would be giving me trouble like that so it felt necessary to report this.
[BugFiles.zip](https://github.com/MarlinFirmware/Marlin/files/10670787/BugFiles.zip)

Update:
I had been using the printer again all day today and a few other times since reporting this and have had no issues, but it just happened again. I have taken a video and have a log file attached with a video of problem. The gcode is also attached that caused this issue. To get the issue to go away I had to turn the printer off for about 5-10 minutes and the same file printed ok but turning the printer off for only a few seconds didn't solve the issue.

[VidAndErrorLog.zip](https://github.com/MarlinFirmware/Marlin/files/10712848/VidAndErrorLog.zip)

### Bug Timeline

Issue on flash. Started first print

### Expected behavior

Expected behavior above

### Steps to Reproduce

I have not reproduced this the reboot solved the issue.

### Version of Marlin Firmware

2.1.x

### Printer model

Ender 5 Pro

### Electronics

Stock

### Add-ons

No add ons

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I didn't know about M111 S247 logging. Ill will make sure to get a good log submitted next time.

**Comment by ellensp** [comment]
Normal cause is failing to reset eeprom data to defaults after a firmware upgrade.

M502 then M500

or enable 
  #define EEPROM_INIT_NOW   // Init EEPROM on first boot after a new build.

To update eeprom to defaults every time you flash

**Comment by jmb-555** [comment]
I was prompted with a "reset" question on boot up. Im assuming that this did the reset. When the erratic extrusion occured, i looked at the saved steps in the config tab and they were all good. I think 80 for the steppers and 90 something for the extruder.

Also, there was one other gcode file printed before the one that I initially attached. If that file worked, then how could it be an EEPROM issue? That other gcode file is attached.
[ExtrusionCalibration.zip](https://github.com/MarlinFirmware/Marlin/files/10677097/ExtrusionCalibration.zip)

**Comment by Bergerac56** [comment]
Just looking at your video. Could it be that your extruder is too close from the bed and block extrusion?

**Comment by jmb-555** [comment]
Dont think it's the extruder being too close. It's clearly trying to squirt more plastic than it can handle. The plastic that comes out is much wider than normal. The motor is also clearly trying to spin at a ridiculous speed when lifting the extruder lever. Also, like i said the machine also locks up in x and y positions. It replies that it gets x and y commands, but it never moves. It just sits there trying to squirt out more plastic than it can handle. It seems like all of this points to software issues not hardware. I was thinking maybe SD card issues but if the firmware is replying back with nothing but "ok" and still not moving it does not seem like it would be a bad SD card either. 

I will also add that Creality has basically replaced this entire machine. It has new motherboard, LCD, and LCD cables. I was having issues with the LCD locking up. Even after reflashing with stock firmware and all the replacements, the issue never went away. The only thing that would get the screen to work was switching out the SD card and the printer would work for about a few days and then i need a new SD card.
