### ISSUE TITLE
[BUG] Second Z axes ignores endstop

### ISSUE THREAD

**Issue by GrevanGER** [MarlinFirmware/Marlin#25378]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I am having the problem that with Marlin bugfix 2.1.x my second Z axis ignores it's dedicated endstop. 

Endstop is set as "uses XMAX" in Marlin and the gcode check M119 is reporting correct states when being held down or released. 

But during homing, only Z1 stops when hitting its endstop, whilst Z2 keeps on trying to spin till infinity.
Error happens with pronterface and printer display alike.

### Bug Timeline

New

### Expected behavior

Endstop should stop axes from moving past the point of contact.

### Actual behavior

Motor keeps on spinning and spinning.

### Version of Marlin Firmware

2.1.x bugfix 

### Printer model

Anycubic i3 Mega S

### Electronics

Trigorilla 1.0

### Bed Leveling

None

### Your Slicer

None

### Host Software

Other (explain below)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[2.1.x bug endstop.zip](https://github.com/MarlinFirmware/Marlin/files/10724482/2.1.x.bug.endstop.zip)

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/25173
