### ISSUE TITLE
NUM_ANALOG_FIRST issue for SKR_V3_0 or variant_MARLIN_STM32H743VX

### ISSUE THREAD

**Issue by WebDesignerlol** [MarlinFirmware/Marlin#25389]
The original issue listed here was not duplicate, nor was it solved.

_Originally posted by @github-actions[bot] in https://github.com/MarlinFirmware/Marlin/issues/25099#issuecomment-1430621189_

I have fixed this for variant_MARLIN_STM32H743VX by going to 

> buildroot\share\PlatformIO\variants\MARLIN_H743Vx\variant_MARLIN_STM32H743VX.h

and adding:

`#define NUM_ANALOG_FIRST        PA0`

The original issue was that with PINS_DEBUGGING enabled on SKR-3 or STM32H743VX the compiler would spit out an issue:

>  Marlin\src\gcode\config\../../pins/../HAL/STM32/pinsDebug.h: In function 'int8_t digital_pin_to_analog_pin(pin_t)':
> Marlin\src\gcode\config\../../pins/../HAL/STM32/pinsDebug.h:172:23: error: 'NUM_ANALOG_FIRST' was not declared in this scope; did you mean 'NUM_ANALOG_LAST'?
>   172 |   if (WITHIN(Ard_num, NUM_ANALOG_FIRST, NUM_ANALOG_LAST))

This is caused by no definition for the first analog pin.

Please update the bugfix for this if possible.

Thank you.

**Comment by Ollinwen** [comment]
Hello,
I compiled for an Ender 5+ on a BTT SKR 3.0+BTT-TFT35-V3.0
I had the same warning, tested this solution, worked like a charm. :-)

**Comment by ahmetcemturan** [comment]
Let me try this out.
