### ISSUE TITLE
[FR] Probe wizard is working backwards

### ISSUE THREAD

**Issue by FlailAway** [MarlinFirmware/Marlin#25390]
### Is your feature request related to a problem? Please describe.

The current probe-offset wizard seems backwards or am I missing something?

To start it it does a Home-all so it knows where the Zero is for Z. Mounting the probe then touches to see where it finds the bed.

Surely at this point that M119 triggered Z-value **is** the probe offset.

Why then go back up to 15mm and make me manually find the bed again. The probe has already found the bed relative to the starting Z = 0.

### Are you looking for hardware support?

Nope

### Describe the feature you want

As above. The probe has found the value, so why make me inch it down to the bed again.

**Comment by thisiskeithb** [comment]
>  The probe has found the value, so why make me inch it down to the bed again.

It found where the probe triggers, but it doesn't know where your actual nozzle is in relation to that point. You still need to find the difference so it can set the offset correctly.
