### ISSUE TITLE
[BUG] The ZMAX endstop is ignored and gear grinds when using ABL

### ISSUE THREAD

**Issue by Poikilos** [MarlinFirmware/Marlin#25401]
:edit: The suggested configuration didn't solve the issue (Though it seems like it should, Marlin doesn't respect the settings). Please see later comments.

### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When a BLTouch is used for homing, the gears grind for a while against the maximum. The issue is especially prominent with a printer where the bed moves up and down, since when the grease is warm and the printer turns off, the bed will fall, so when the printer turns back on it reads Z as 0 but Z is actually max. If a ZMAX sensor is installed, Marlin refuses to use it despite #10390 being fixed (regardless of `Z_HOME_DIR`).

Related issues:
- #10390
- #23759

Already tried:
- It occurs whether `NOZZLE_PARK_FEATURE` is enabled or not.
- I custom mounted a ZMAX sensor on my Replicator 2X with a BTT SKR V1.4 Turbo mainboard. It lights up, but is ignored by Marlin. Everything else works fine.
- `#define USE_ZMAX_PLUG`
- `Z_HOME_DIR` 1 or -1

### Bug Timeline

Posts around the internet indicated that fixing #10390 would fix this but it did not.

### Expected behavior

I expect Marlin to stop increasing Z when the ZMAX sensor is triggered, even if the probe is used for homing and `#define Z_HOME_DIR -1`.

### Actual behavior

When the printer is first turned on, Marlin reads Z as 0 though it is higher, so running ABL or filament load causes the Z to keep increasing as the gears (worm gear and follower) grind even after the ZMAX endstop is triggered.

### Steps to Reproduce

1. Install a Probe.
2. Install a ZMax sensor.
3. Turn the printer off.
4. Move the nozzle near ZMAX.
5. Turn the printer on.
6. Run ABL.

### Version of Marlin Firmware

Marlin bugfix-2.1.x (Feb 18 2023 09:24:24)

### Printer model

MakerBot Replicator 2X

### Electronics

BTT SKR V1.4 Turbo

### Add-ons

ZMAX endstop plugged into ZMAX plug

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/10774516/Marlin.zip)

**Comment by thisiskeithb** [comment]
Enable `ENDSTOPS_ALWAYS_ON_DEFAULT` and see if homing behavior changes.

With `USE_PROBE_FOR_Z_HOMING` enabled, the Z endstops are ignored while homing & a probe is used instead.

**Comment by Poikilos** [comment]
> Enable `ENDSTOPS_ALWAYS_ON_DEFAULT` and see if homing behavior changes.

That did not solve the problem.

> With `USE_PROBE_FOR_Z_HOMING` enabled, the Z endstops are ignored while homing & a probe is used instead.

## `USE_PROBE_FOR_Z_HOMING` off

Even if I turn off `USE_PROBE_FOR_Z_HOMING`, UBL's "Build Mesh" process doesn't work at all: It seems to reach hysteresis as usual, Z starts decreasing, then the sensor touches the bed, then Marlin says "Heating Failed: T1" "PRINTER HALTED". It only happens when using BLTouch without `USE_PROBE_FOR_Z_HOMING` and only happens when the sensor touches the bed, even though the error is totally unrelated. With any version I previously tried of of bugfix-2.0.x or bugfix-2.1.x, I always had to enable `USE_PROBE_FOR_Z_HOMING` for Build Mesh to complete. Note that turning it off requires `Z_HOME_DIR 1`.
- Does this mean https://github.com/MarlinFirmware/Marlin/issues/10390 isn't really fixed?

## `USE_PROBE_FOR_Z_HOMING` on
`USE_PROBE_FOR_Z_HOMING` should only prevent the ZMIN from being used. The current behavior of also ignoring ZMAX is a bug since it causes gears to grind by ignoring a sensor not replaced by the probe. Only ZMIN is potentially replaceable by the probe.

**Comment by Poikilos** [comment]
Also, I can now confirm that the custom Z_MAX endstop works, as it triggers at the end of a large print when build volume is set to taller than the hardware (Marlin sends an endstop triggered message which appears as a popup in touch mode on the BTT TFT35).

**Comment by ellensp** [comment]
The skr 1.4 does not have official max endstops

It has:
```
x-stop | E0DET
y-stop | E1DET
z-stop | PWRDET
```

Now in special cases marlin will juggle the pins about and use some of these other pins as max endstops.
Your configs do not trigger this. 
On Z this only happens if your using sensorless or dual z endstops

So with your config marlin has 
    #define Z_STOP_PIN                     P1_27  // Z-STOP

Since marlin only knows about z-stop that is assigned to z-min if homing to min or z-max if homing to max, even if it is not used because you using the probe to home.

Marlin still doesn't know where you have plugged this Z_MAX endstop into?

And neither do we

So the question is, where did you plug in the Z_MAX endstop?

**Comment by Poikilos** [comment]
Ah, thanks for the response. My custom Z_MAX sensor is plugged into PWRDET, the one next to ZMIN. I thought maybe the mainboard layout allowed for ZMAX but I didn't know I had to define the pin. I can plug it into a different one if that is easier. I don't quite know how/where to define a custom Z_MAX pin yet, nor where to enable a pin not defined in the pins header. I didn't realize that wasn't in pins_BTT_SKR_V1_4.h.

**Comment by ellensp** [comment]
try this:

In pins_BTT_SKR_V1_4.h

replace

`#elif ENABLED(Z_MULTI_ENDSTOPS)
`

with

`#elif EITHER(Z_MULTI_ENDSTOPS, USE_ZMAX_PLUG)
`

Marlin will then define 
    #define Z_MIN_PIN                      P1_27  // Z-STOP
    #define Z_MAX_PIN                      P1_00  // PWRDET

instead of just
    #define Z_STOP_PIN                     P1_27  // Z-STOP

I don't consider this is a bug, its just a lack of realizing that this board does not actually have max endstops, so you have to force it to use PWRDET as Z_MAX_PIN

**Comment by Poikilos** [comment]
- I don't know how it was even stopping at 149 before I made the change, but it stopped there or 149.9 so I don't even know if that is possible that is was a software endstop since the number varied. In any case, it was only triggering and stopping during a print (end gcode to lift to 150) and not triggering during UBL homing, with or without the change to pins.
- I made the change to the pins and the problem persists.
- Resetting the firmware settings also did not resolve the issue.

**Comment by Poikilos** [comment]
@ellensp Can you comment on my response? I tried your solution.

**Comment by Poikilos** [comment]
It is not working. Is there anywhere to look? It still happens on UBL but the physical endstop works on movement.

**Comment by Poikilos** [comment]
@thisiskeithb Can you comment on my reply above? I realized today I should try this:
![image](https://user-images.githubusercontent.com/7557867/233109223-5c85235a-f580-4ce0-9950-1410e8de46cf.png)
It still grinds on auto home even with MAX_SOFTWARE_ENDSTOP_Z commented. Please fix this (Please implement this configuration).

:edit: Also note that **X and Y** endstops on this style of printer are max endstops (I moved z from min to max position in the printer and changed plug in hardware and software as described earlier), but homing works fine for those even when both `MIN_SOFTWARE_ENDSTOPS` and `MAX_SOFTWARE_ENDSTOPS` are defined. When I realized this today I turned off all max software endstops, but it still didn't resolve the issue:

![image](https://user-images.githubusercontent.com/7557867/233145128-f7e97b43-8453-412b-a88b-8ee8e3dd3d77.png)

**Comment by Poikilos** [comment]
I will provide any new information as I can. I have updated to the latest commit (2 days ago) on the bugfix-2.1.x branch. The new settings I'm using are:

Configuration.h
```C
// Min software endstops constrain movement within minimum coordinate bounds
#define MIN_SOFTWARE_ENDSTOPS
#if ENABLED(MIN_SOFTWARE_ENDSTOPS)
  #define MIN_SOFTWARE_ENDSTOP_X
  #define MIN_SOFTWARE_ENDSTOP_Y
  //#define MIN_SOFTWARE_ENDSTOP_Z
  #define MIN_SOFTWARE_ENDSTOP_I
  #define MIN_SOFTWARE_ENDSTOP_J
  #define MIN_SOFTWARE_ENDSTOP_K
  #define MIN_SOFTWARE_ENDSTOP_U
  #define MIN_SOFTWARE_ENDSTOP_V
  #define MIN_SOFTWARE_ENDSTOP_W
#endif

// Max software endstops constrain movement within maximum coordinate bounds
// #define MAX_SOFTWARE_ENDSTOPS
```

And I added custom code here:
```C
#if ENABLED(USE_PROBE_FOR_Z_HOMING) // Poikilos added this case
  #if DISABLED(MAX_SOFTWARE_ENDSTOP_Z) // Poikilos added this case
    #define CUSTOM_Z_MAX
  #endif
#endif

#ifdef Z_STALL_SENSITIVITY
  #define Z_STOP_PIN                  Z_DIAG_PIN
  #if Z_HOME_TO_MIN
    #define Z_MAX_PIN                      P1_00  // PWRDET
  #else
    #define Z_MIN_PIN                      P1_00  // PWRDET
  #endif
#elif ENABLED(Z_MULTI_ENDSTOPS)
  #ifndef Z_MIN_PIN
    #define Z_MIN_PIN                      P1_27  // Z-STOP
  #endif
  #ifndef Z_MAX_PIN
    #define Z_MAX_PIN                      P1_00  // PWRDET
  #endif
#elif ENABLED(CUSTOM_Z_MAX) // Poikilos changed to allow PWRDET on BTT SKR V1.4 to function as ZMAX (workaround invalid issue https://github.com/MarlinFirmware/Marlin/issues/25401#issuecomment-1445031951)
  #define Z_STOP_PIN                      P1_00  // PWRDET
  // NOTE: only setting Z_MAX_PIN (leaving MIN undefined) causes a compilation error.
#else
  #ifndef Z_STOP_PIN
    #define Z_STOP_PIN                     P1_27  // Z-STOP
  #endif
#endif
```
Unfortunately, it will not let me define Z_MAX_PIN without also defining Z_MIN_PIN. If I only define Z_MAX_PIN, there is a compilation error. If I run it this way, the issue still occurs, and the output of M119 always says I have a z_min (it doesn't list a z_max), even though it is plugged into PWRDET and M119 correctly reports the state of the swich (closed if I press it; but as "z_min" instead of how I'm trying to use it as z_max).
- If I try to enable both like this:
```
#elif EITHER(Z_MULTI_ENDSTOPS, CUSTOM_Z_MAX)
  #ifndef Z_MIN_PIN
    #define Z_MIN_PIN                      P1_27  // Z-STOP
  #endif
  #ifndef Z_MAX_PIN
    #define Z_MAX_PIN                      P1_00  // PWRDET
  #endif
```
The z_min is listed by M119 still, but it is never listed as triggered. The z_max is not listed at all, even with both defined this way (and `MAX_SOFTWARE_ENDSTOPS` remains not defined, which I assume is correct if I want to test this issue as I have a hardware endstop for x_max, y_max, and z_max).

versions tested:
- :edit: bugfix-2.1.x 4c033c3e47b80a9d2497b47a7d3f1ef5034ff4d0
- :edit: bugfix-2.1.x e41dc273c9d9ee05947ecd66c44c7c7a91868545

I can't turn on `ENDSTOPS_ALWAYS_ON_DEFAULT` because that prevents homing at all (stops around 17mm during homing) with BLTOUCH.

:edit: It turns out that the grinding against max even happens during homing (if 3D printer was power cycled while near zmax) due to moving up to try to get clearance before moving toward BLTOUCH, and during movement at least when jogging with the touch screen (The error that appeared about hitting ZMAX only occurred during a 150mm print on an earlier setting and version; no other situation showed a message, strangely).
