### ISSUE TITLE
[BUG] Pause at the beginning of printing

### ISSUE THREAD

**Issue by dobrzann** [MarlinFirmware/Marlin#25419]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hello,

Two days ago I taked new version of Marlin 2.1.x for some tests. The compilation result was ok, but I have one problem, printing stops immediately at the beginning of every gcode and extruder seems to be off because temperature is falling down printer beeps and shutting down after some time (I using PSU_CONTROL). I haven't had these problems in earlier version of Marlin 2.0.5

### Bug Timeline

This is a new problem, I didn't have this problem before

### Expected behavior

I want to start printing without this problem 

### Version of Marlin Firmware

bugfix-2.1.x

### Electronics

MKS Sbase

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

IdeaMaker

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads
[Log and gcode.zip](https://github.com/MarlinFirmware/Marlin/files/10818443/Log.and.gcode.zip)

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10818115/configuration.zip)

**Comment by dobrzann** [comment]
I found it. Problem was caused by M1001 and M1002 codes generated automatically by Ideamaker. These codes was not present in earlier version of marlin.

Regards for All.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/23037
