### ISSUE TITLE
[FR] Endstop working in both ways

### ISSUE THREAD

**Issue by maxholgasson** [MarlinFirmware/Marlin#25415]
### Is your feature request related to a problem? Please describe.

I'm using the marlin fw with a BTT octopus pro in a diy machine. When moving the machine manually I need two endstops per axis in order not to destroy the machine. After a shutdown I don't want to move the positions which is needed for homing and software endstops..so hardware endstops are an absolute must due to safety.

### Are you looking for hardware support?

BTT octopus pro

### Describe the feature you want

The endstop input should work in both directions. So X-axis should stop at min and max position regardless of a software endstop/limit. The two switches are wired in series and therefore in software it's needed to store the current direction in order to detect which limit was triggered

**Comment by EvilGremlin** [comment]
ENDSTOPS_ALWAYS_ON_DEFAULT

**Comment by maxholgasson** [comment]
>ENDSTOPS_ALWAYS_ON_DEFAULT

Seems only activate endstops on default but not stopping it when moving it in both directions.
So when I'm moving to the left it stops at the end stop but when moving it to the right it won't stop

**Comment by ellensp** [comment]
No config files, suspect you simply haven't enabled USE_XMAX_PLUG

**Comment by maxholgasson** [comment]
Oh that would be great if I just made a mistake, I enabled USE_XMAX_PLUG and USE_XMIN_PLUG but it stops only in one direction.
Which config files do you need? Configuration and Configuration_adv.h?

**Comment by thisiskeithb** [comment]
> Which config files do you need? Configuration and Configuration_adv.h?

Yes.

> The two switches are wired in series

Are they NC or NO?

Also, the Octopus Pro has plenty of dedicated endstop ports, so why not wire each endstop individually?

**Comment by maxholgasson** [comment]
I started with a new firmware.
So far I enabled always n endstops and joystick usage

>Are they NC or NO?

Right now I'm just using a wire to test it but later it would be two NC in series.

The octopus has only 6 endstop ports if I'm not wrong and I have six axis. 
As a second board I would like to use my old 1.4 Turbo and this has also limited endstop ports.

but even if I would wire  each endstop individually, would that be possible at all? I found only some dual endstop settings in the firmware but this is used with a second motor and not for the same motor 

[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/10807138/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/10807139/Configuration.txt)

**Comment by thisiskeithb** [comment]
> The octopus has only 6 endstop ports if I'm not wrong and I have six axis.

It has 8 endstop pins

<img width="256" alt="image" src="https://user-images.githubusercontent.com/13375512/220726007-0d94d8cf-ac08-43f6-8176-0c4951d02a26.png">

> but even if I would wire each endstop individually, would that be possible at all?

Of course. By uncommenting both `USE_*MIN/MAX_PLUG` options, you can enable both min & max endstop on an axis.

`ENDSTOPS_ALWAYS_ON_DEFAULT` will keep endstops active at all times & not just for homing.

**Comment by maxholgasson** [comment]
Ah ok, I assumed that because it was like this in the manual
![Unbenannt](https://user-images.githubusercontent.com/4289347/220730281-2bd67c0d-4866-4afa-9da4-2a59e651d799.png)

but still 8 are to less as I would need 12 inputs

**Comment by maxholgasson** [comment]
If I understand ir right, the endstop actions are handled in the endstops.cpp

If a switch is triggered we're in this function
`void Endstops::update() {`

The direction is determined by this and the motor stopped by PROCESS_ENDSTOP_X(MIN);
```
  if (stepper.axis_is_moving(X_AXIS)) {
    if (stepper.motor_direction(X_AXIS_HEAD)) { // -direction
      #if HAS_X_MIN || (X_SPI_SENSORLESS && X_HOME_DIR < 0)
        PROCESS_ENDSTOP_X(MIN);
```
As soon as we change the direction, we're in the else part and are able to move the motor again..
..what's missing now is a second query if the switch is triggered again and with the know direction we know in the following that the second limit of the way is reach. So we can give way for the other direction again.

I just don't know how to do that is the code is so complex of Marlin.

**Comment by ellensp** [comment]
You cannot have a single endstop triggered from both directions. (or both endstops of one axis using the same IO pin)

Consider this scenario

You power on.  The endstop IO line is already triggered. 
Which way is safe to move?  
You cannot tell. As there is no way to tell if the axis is an minimum or maximum position.

**Comment by maxholgasson** [comment]
Please re-open the request as it's not yet solved

This is possible, that's exactly how it's working on my milling machine with another controller and firmware.
Maybe they store the last position in an EEPROM or just do nothing till you manually release it in either way.
Actually that never happend so far, so I guess it would be rare in real life.
True is, that I have only one input per Axis anf it's working

**Comment by ellensp** [comment]
most 3d printer home X or Y at the end of each print.
Real cnc machines have encoder hardware. So they instantly know where the motors are on power up. They don't use endstops for homing, they use limit switches to stop you breaking the machine with gcodes that move things out of bounds.

**Comment by maxholgasson** [comment]
https://planet-cnc.com/configure-limit-switch-inputs-controller-planetcnc-tng-software/

Example 2 shows that it’s possible as a reference

**Comment by ellensp** [comment]
Limit switches are not endstops.

**Comment by maxholgasson** [comment]
Please let us not argue about words.
I have a real machine here assembles by myself and bought as a semi-professional kit.
It’s working.
The end stop on my BTT board with the Marlin FW is doing the same thing with my attached switch but only In one direction.
Actually I found in the endstops.cpp a way and it’s stopping now in both ways. Only thing is as long as one switch is triggered it won’t move.
I need now some variable to store the last direction. If that it’s known I know which direction is safe. That’s all I want and it’s how it’s working in my other machine.
Why do you want me to believe it’s not possible. Let’s find a solution. I would do it in another way but the board has to less inputs for Dedicated switches and others show that there is a way around.

**Comment by mjfsch** [comment]
Is there any reason you cant use 4 extra inputs that your not already using to get the additional end stops you need and just configure them in your pins file? this seems like the best option for not having to adjust the code and cause any unexpected behaviour.

if for example your not using power detection you could use J35 PC0 (just be careful of the voltage pin on this as its 3.3v) you could likely use J36 PE11 aswell if not using the PS on detection.

If you take a look in the BTT github you can find the board schematic, anything your not using with a general input arrangement like this should work

![image](https://user-images.githubusercontent.com/99204506/220859305-0e51ee2b-2e41-4f6f-ac4e-7245f69b0240.png)


As for your idea of storing direction, it would have to be persistent so a variable is no use it would have to be stored in eeprom, what happens if the machine is moved while switched off? how often would you have to update the value? with eeprom having a limited number of write cycles your probably going to kill it very quickly.

**Comment by maxholgasson** [comment]
Hello, yes as I'm wrote the other control probably stores it in an EEPROM. Which 100000 cycles and a smart way that's no problem. Even if you would turn day machine off for every single day 10 times..it would work around 27 years

I want to attach additional switches to input pins to be able two switch between various speeds e.g Or store, replay various moves. Also my smaller 1.4 Turbo board has less inputs. 12 Input pins only for end stops would also mean double of wires.
As I dont't need a probe or BLTouch I might maybei get it with the Pro board. Other input switches that are not so high in safety regards could be maybe attached with a second mcu and the commands could be send via uart

Maybe one way without an EEPROM would be to move let's say 1mm to the left. If still the endstop is trigger your're on the left end stop. Then we could move 2mm to the right, if it's free than allow to continue  to the right. That procedere is only needed after a restart for the first time when hitting an end stop

The code already has an option to uncomment the min or max plug but it just doesn't work for both. That's why my feature request to enhance this and make it possible

**Comment by maxholgasson** [comment]
I attached now two switches to two inputs but can't stop the motor when hitting the max switch.
You told that it is posible with two inputs, can you tell me how?
