### ISSUE TITLE
[BUG] Re-Arm Viki2 LCD fails when onboard SD is enabled

### ISSUE THREAD

**Issue by jkoljo** [MarlinFirmware/Marlin#25410]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When you enable Viki2 LCD and onboard SD card with Re-ARM, the LCD fails to work. The screen remains blank. Each function works independently. That led me to investigate pins_RAMPS_RE_ARM.h, where the problem was actually found. 

On lines 357 and 358, pins for the LCD SCK and MOSI are defined. If you use onboard SD instead of LCD SD card slot, this obviously doesn't work.
    #define DOGLCD_SCK                SD_SCK_PIN
    #define DOGLCD_MOSI              SD_MOSI_PIN

I manually changed these to:
    #define DOGLCD_SCK                     P0_15 // Originally SD_SCK_PIN
    #define DOGLCD_MOSI                    P0_18 // Originally SD_MOSI_PIN

And now everything works great. It would be great if you could include this fix in an upcoming release. Thanks!

### Expected behavior

Viki2 LCD and onboard SD should both work when enabled in configuration and configuration_adv files.

### Actual behavior

Onboard SD card works but the Viki2 LCD stays blank.

### Version of Marlin Firmware

Marlin 2.1.2

### Electronics

Re-ARM with Viki2 LCD

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10777467/Configuration.zip)
[pins_RAMPS_RE_ARM fixed.zip](https://github.com/MarlinFirmware/Marlin/files/10777472/pins_RAMPS_RE_ARM.fixed.zip)

**Comment by ellensp** [comment]
PR created, closing
