### ISSUE TITLE
[BUG] (bug summary)Reported error: Thermal Runaway, system stopped! Heater_ID: bed

### ISSUE THREAD

**Issue by StevenGurule** [MarlinFirmware/Marlin#25452]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Machine: Anet A8
Firmware: Marlin configured for Anet/A8, version 020007
Octoprint V1.5.3

Problem - Running print for several minutes and getting "Reported error: Thermal Runaway, system stopped! Heater_ID: bed - Printer halted. kill() called!" message.

I've noticed that the reported bed temperature slowly slopes away from the target temperature over a few minutes before the error occurs.  I think it's a wire resistance issue, but before I go ripping my harnesses apart, can anyone confirm my suspicions based on experience?  I've made several hundred printed, and I haven't had to change harnessing (yet - grin).

Thanks for your help.

### Version of Marlin Firmware

020007

### Printer model

Anet A8

### Electronics

stock

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by EvilGremlin** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server (). Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.
