### ISSUE TITLE
[BUG] Ender 3 V1 - Missing "Z Offset" option from menu

### ISSUE THREAD

**Issue by jeebob** [MarlinFirmware/Marlin#25463]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I am having some difficulties with bed leveling, so invested in an e-leveler to try and make life a bit easier, whilst I get through my physical issues. I decided to upgrade my Creality Melzi 1.1.4 board on my V1 Ender 3 with a version of Marlin 2.1.2.

I took the Configuration of Ender 3 from the Configuration repository, dropped them in place, loaded the project, and the Z Offset menu is missing from the Control -> Motion -> Z Offset placeholder. I don't have a BLTouch, and need to set the Z offset to 0 from 2mm, so that I can use the leveler, then set the Z back to 2mm.

The menu options are completely missing.

### Bug Timeline

N/A

### Expected behavior

Menu options for Z Offset should be visible under the Motion menu

### Actual behavior

Z Offset option does not exist under the Motion Menu

### Steps to Reproduce

Menu
Control
Motion
<Z Offset Missing>

### Version of Marlin Firmware

2.1.2 Bugfix

### Printer model

Creality Ender 3 V1

### Electronics

Creality Melzi V1.1.4

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10889708/Configuration.zip)

**Comment by EvilGremlin** [comment]
This is not a bug. To have Z offset you need probe, else adjust endstop/bed.

**Comment by jeebob** [comment]
Even if you have a Z minimum endstop, with "probe manually" set?

**Comment by EvilGremlin** [comment]
Yes, it must be [semi]automatic probe.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
