### ISSUE TITLE
[FR] Nextion TFT HMI

### ISSUE THREAD

**Issue by MagoKimbra** [MarlinFirmware/Marlin#2546]
I'm developing for use Nextion hmi TFT LCD ...
For now I'm still at the beginning, I can make the home for each axis with the touch and read and set temperatures. LCD connects to a serial Arduino is very easy to use. The only difference with other LCD is that you have to plan ahead with his tools and the graphics functions, marlin you should only worry about updating the fields and detect touches to perform functions.
It could also be of interest to you?
Maybe there is someone who helps me with the graphics that I am bad ....

https://youtu.be/YQNf5X-c8tA
https://youtu.be/h1263XmokJ0
https://youtu.be/kVhakHF350Y

**Comment by freezingzz** [comment]
@MagoKimbra  What graphics help you need ? If just need some one to draw some image for you, I think I can do it. But if you need me to make the HMI or TFT file for you, I need to know what your controller sends and what info you need when pressing some button.

**Comment by IceflowCW** [comment]
Thats very interesting indeed!! :D ill keep watching for more updates on this. Im also "playing" with the nextion editor and a couple of nextion lcds, but i think im not that good with the code part... the editor its a bit messy... :(

**Comment by clefranc** [comment]
@MagoKimbra What's the size of the TFT screen you're using (part number)?

**Comment by MagoKimbra** [comment]
I am out for this week. When i return to my home i response you all your question.. 
Il 06/Ago/2015 02:53, Christian Lefrançois notifications@github.com ha scritto:@MagoKimbra What's the size of the TFT screen you're using (part number)?

**Comment by mrKappa27** [comment]
I'm also working with a Nextion HMI and the MarlinFW, it looks quite good :)
I hope that Nextion will improve the HMI editor cause now looks really like a messy "demo version".

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
