### ISSUE TITLE
[BUG] Getting thermal runaway warnings from heating hot end

### ISSUE THREAD

**Issue by dmarnel** [MarlinFirmware/Marlin#25471]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When starting a print job, the hot end heats up well beyond the target temperature setting before it begins to cool down again. In previous Marlin versions the temperature would get to within a couple a degrees below the target temperature and pause before slowly heating to the target temp setting.

### Bug Timeline

I've only noticed this recently but haven't printed in several months.

### Expected behavior

I expect the temperature to rise to with a couple of degrees of the target setting, pause for the thermal check, and then resume heating until the target temperature is reached.

### Actual behavior

The hot end heats up anywhere from 3 to 6 degrees past the target temperature setting before it begins to cool down again.

### Steps to Reproduce

1. Start a print job.
2. Observe hot end heating past the target temperature setting.

### Version of Marlin Firmware

bugfix-2.1.x (Mar 5 2023 14:44:11)

### Printer model

Ender 3 Pro

### Electronics

BTT TFT35 LCD 

### Add-ons

Ender Direct Drive Extruder

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by dmarnel** [comment]
Here are the config files. I didn't see a way of attaching them to the issue.
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/10900542/Archive.zip)

**Comment by StevilKnevil** [comment]
Have you gone through PID tuning? https://reprap.org/wiki/PID_Tuning

**Comment by dmarnel** [comment]
Did it this morning and I'm not seeing much of a change, if any. I have a job with a target temp. of 210, and as it heated the nozzle, the temp climbed all the way up to 204 then paused and went down to 196. In that time I received a thermal runaway warning through Octopod on my iPhone. It did climb back up and settled at 210 eventually.

**Comment by Sonicboom247** [comment]
I hate to say it but i have been having the same issue for the past month or so, i thought it was just me forgetting to do an MPC tune and a PID on the bed but this morning i did both again, started a print and again the bed goes from 60 down to 54 and up to 66 and everywhere in between. I stopped the print as soon as i saw the swings start to get crazy to make a new firmware as i seem to recall the last firmware i flashed from 12/25 had addressed some heating issues.
Update, just recompiled with today's bugfix and same issue so not sure if this is more related to a slicer or what

https://user-images.githubusercontent.com/84334417/224355026-38b0c10c-d18a-40e6-85b1-96908c6ef5c5.mp4

**Comment by togeis** [comment]
Same issue here, but mostly when doing a `M109 R50` at my END gcode. Short before 5X° it will raise the temp again with full power "@:127" and then cool down again till 50°. Octoprint detects the short raise and sends me a "thermal runaway". Is can see this short raise also in the temp graph. I currently have no screenshot. I will reproduce the issue and will document this.

I have tried to reproduce:
Set `M109 R50` and when temp ist lower than 60°, so 5 is the first digit (5X.X°) it will power up again for an short time:

<details><summary>OctoPrint log:</summary>
<p>

```log
Recv: echo:busy: processing
Recv:  T:60.75 /50.00 B:27.48 /0.00 @:0 B@:0 W:?
Recv:  T:60.61 /50.00 B:27.49 /0.00 @:0 B@:0
Recv:  T:60.49 /50.00 B:27.68 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:60.18 /50.00 B:27.51 /0.00 @:0 B@:0 W:?
Recv:  T:60.10 /50.00 B:27.56 /0.00 @:0 B@:0
**Recv:  T:59.98 /50.00 B:27.64 /0.00 @:127 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:59.69 /50.00 B:27.66 /0.00 @:127 B@:0 W:?
Recv:  T:59.66 /50.00 B:27.65 /0.00 @:127 B@:0
Recv:  T:59.65 /50.00 B:27.63 /0.00 @:127 B@:0 W:?**
Recv: echo:busy: processing
Recv:  T:60.14 /50.00 B:27.46 /0.00 @:0 B@:0 W:?
Recv:  T:60.37 /50.00 B:27.46 /0.00 @:0 B@:0
Recv:  T:60.89 /50.00 B:27.45 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:61.74 /50.00 B:27.51 /0.00 @:0 B@:0 W:?
Recv:  T:62.12 /50.00 B:27.47 /0.00 @:0 B@:0
Recv:  T:62.50 /50.00 B:27.61 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:63.21 /50.00 B:27.45 /0.00 @:0 B@:0 W:?
Recv:  T:63.39 /50.00 B:27.44 /0.00 @:0 B@:0
Recv:  T:63.68 /50.00 B:27.44 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:63.99 /50.00 B:27.46 /0.00 @:0 B@:0 W:?
Recv:  T:64.11 /50.00 B:27.45 /0.00 @:0 B@:0
Recv:  T:64.20 /50.00 B:27.57 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:64.29 /50.00 B:27.52 /0.00 @:0 B@:0 W:?
Recv:  T:64.28 /50.00 B:27.47 /0.00 @:0 B@:0
Recv:  T:64.27 /50.00 B:27.60 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:64.19 /50.00 B:27.58 /0.00 @:0 B@:0 W:?
Recv:  T:64.14 /50.00 B:27.51 /0.00 @:0 B@:0
Recv:  T:64.09 /50.00 B:27.64 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:63.86 /50.00 B:27.45 /0.00 @:0 B@:0 W:?
Recv:  T:63.83 /50.00 B:27.56 /0.00 @:0 B@:0
Recv:  T:63.62 /50.00 B:27.40 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:63.42 /50.00 B:27.60 /0.00 @:0 B@:0 W:?
Recv:  T:63.30 /50.00 B:27.55 /0.00 @:0 B@:0
Recv:  T:63.18 /50.00 B:27.59 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:62.88 /50.00 B:27.54 /0.00 @:0 B@:0 W:?
Recv:  T:62.78 /50.00 B:27.51 /0.00 @:0 B@:0
Recv:  T:62.61 /50.00 B:27.50 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:62.33 /50.00 B:27.48 /0.00 @:0 B@:0 W:?
Recv:  T:62.20 /50.00 B:27.58 /0.00 @:0 B@:0
Recv:  T:62.07 /50.00 B:27.64 /0.00 @:0 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:61.74 /50.00 B:27.55 /0.00 @:0 B@:0 W:?
Recv:  T:61.63 /50.00 B:27.49 /0.00 @:0 B@:0
Recv:  T:61.47 /50.00 B:27.50 /0.00 @:0 B@:0 W:?
```

</p>
</details>

<img width="585" alt="image" src="https://user-images.githubusercontent.com/5475386/224574504-4bd55e9d-1ced-496a-a0c3-60feb0a56fa0.png">

Test gcode is:

```gcode
M104 S170 ; set extruder temp for bed leveling
M109 R170 ; wait for bed leveling temp
M104 S200 ; set extruder temp
M109 S200 ; wait for extruder temp
M109 R50 ;Turn-off hotend till 50C
M104 S0 ;Turn-off hotend complete
```

MPCTEMP is disabled. My config is using PIDTEMP.

**Comment by togeis** [comment]
Retested with bugfix release from 04-04-2023:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/5475386/232008339-92ef67be-286e-40e5-a2c4-ff85c7ddb5c4.png">

Still the same issue

**Comment by ellensp** [comment]
@togeis your issue is not a thermal runaway issue. you should open your own issues.

**Comment by 127** [comment]
Who summoned me thou mortals?

**Comment by klavatron** [comment]
**Marlin 2.1.2.1 with Arduino Mega2560 + Ramps**

When I set the extruder temperature to 245°C, the temperature only reaches 235°C before the extruder turns off for 1-2 seconds (I can see this from the LED indicator). Afterwards, it turns back on again. The firmware detects this temperature drop as a malfunction and shuts down the printer. However, if I can detect this drop before the shutdown occurs, I can send a command to heat the extruder again, preventing the printer from shutting down.

In contrast, Marlin **2.0.7.2** does not have this bug and operates correctly.

**Comment by togeis** [comment]
Simular issue during cooldown phase. Heats up again during cooldown. Maybe related to the same bug.

https://github.com/MarlinFirmware/Marlin/issues/25676
