### ISSUE TITLE
#error "Z_MULTI_ENDSTOPS is incompatible with USE_PROBE_FOR_Z_HOMING." 

### ISSUE THREAD

**Issue by devilangelsoul** [MarlinFirmware/Marlin#25489]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I'm configuring the bltouch for my printer and I've changed some parameters, but it gives me this error again even if "USE_PROBE_FOR_Z_HOMING" is uncomment and therefore disabled.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10939793/Configuration.zip)

### Version of Marlin Firmware

bugfix 2.1.x

### Printer model

anycubic i3 Mega S

### Electronics

stock

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN automatically sets USE_PROBE_FOR_Z_HOMING

You cannot possibly be using the z_min plug for a probe, when you have Z_MULTI_ENDSTOPS as the the first z uses z_min plug and the second Z uses what you have set in the config,  X-Max in this case


This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
