### ISSUE TITLE
Z min -2.1.2

### ISSUE THREAD

**Issue by BezdaM** [MarlinFirmware/Marlin#25482]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I updated to version 2.1.2 and I have a problem with Z min. Everything looks functional. M119 reports from min open, when I switch from min manually, it reports M119 triggered. As soon as I put G28, x and y are fine, but z min won't turn off the engine.

### Bug Timeline

With version 2.1.2

### Expected behavior

After reaching Z min move up 10 mm and switch off the motor.

### Actual behavior

Z min does not turn off the engine

### Version of Marlin Firmware

2.1.2

### Printer model

MPCNC

### Electronics

Ramps S

### Bed Leveling

None

### Your Slicer

None

### Host Software

Repetier Host

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10923559/Configuration.zip)

**Comment by Johnny846** [comment]
So when you trigger the z-min endstop manually, M119 reports it is triggered, but when homing the printer continues to lower Z-axis (crashing the nozzle) even after triggering the z-min endstop?
