### ISSUE TITLE
[FR] Make UBL G29 J probe on mesh points

### ISSUE THREAD

**Issue by jamespearson04** [MarlinFirmware/Marlin#25485]
### Is your feature request related to a problem? Please describe.

Currently UBL G29 J and G29 Jx appear to use ```MESH_INSET``` and ```PROBING_MARGIN``` to determine the points used for probing.

This can lead to less than optimal conditions for leveling, due to relying on interpolated z heights from the mesh to compare against. If due to the probing margin, the some points lie on the outside of the probed mesh, the issue is much more pronounced, as it's essentially compared against a guess.

For 3-point leveling this can be remedied by manually setting the points using ```PROBE_PT_1_X``` etc, but this requires a good understanding of the mesh layout.

### Describe the feature you want

```unified_bed_leveling::find_closest_mesh_point_of_type()``` + ```mesh_index_pair.meshpos()``` in UBL_G29.cpp already provide the functionality to find the nearest mesh probeable point, so tweaking ```unified_bed_leveling::tilt_mesh_based_on_probed_grid()``` to use this on the points it currently uses should yield the desired result. If desireable, a ```#define``` can be used to allow ```PROBE_PT_1_X``` etc to override this.

**Comment by thisiskeithb** [comment]
Closing since you've opened a PR:
- https://github.com/MarlinFirmware/Marlin/pull/25486
