### ISSUE TITLE
[FR] Allow MPCTEMP tuning to use the "Alternative Method"

### ISSUE THREAD

**Issue by StevilKnevil** [MarlinFirmware/Marlin#25496]
### Is your feature request related to a problem? Please describe.

My setup fails to autotune MPCTemp: https://github.com/MarlinFirmware/Marlin/issues/25481
However when I use the [Manual Method](https://marlinfw.org/docs/features/model_predictive_control.html#:~:text=constants%20at%20runtime.-,Manual%20Tuning,with%20positive%20temperature%20coefficient%20(PTC)%20hotends%E2%80%93%20MPC%20can%20be%20configured%20manually.), then it works OK

### Are you looking for hardware support?

No

### Describe the feature you want

`M306 T` should fail over to the alternative method of determining the parameters if the initial tuning fails (e.g. if the block or sensor responsiveness are negative).

It should also be possible to force the use of the Alternative Method (Or perhaps "differential method", as it's based on maximum rate of change?), maybe with `M306 TA`

### Additional context

N/A

**Comment by tombrazier** [comment]
@StevilKnevil If you understand how MPC works, it would be great to see an alternative tuning method. I thought a lot about this some time back but did not have time to implement anything. An automated version of my manual tuning method may be a good start. (Can't remember off the top of my head if any of the long PR conversations included this but I can describe it necessary.)

[Edit: I also keep pondering adding explicit logic for reducing power with temperature on PTC hotends.]

**Comment by StevilKnevil** [comment]
@tombrazier I understand the concept of MPC and am pretty happy with all of the tuning code there (oI did a bit of refactoring in the linked PR to help get my head around it!)

I also prototyped the alternative tuning mechanism and that worked fine for me, I just need to carve out a little time to tidy up that code and submit a PR.

PTC hotends should be a solvable problem, my only concern would be having the hardware to test on!

**Comment by tombrazier** [comment]
I'm glad there is someone other than me who understands it and can work on it. I have a CHC hotend, which is PTC. I don't have a lot of time but I might be able to help test. Although I am interested that you seem to to be getting a negative sensor responsiveness if you don't have PTC. I had thought that this was entirely due to the higher part of the temp vs time curve being shifted to the left by PTC. But it's been quite some time since I looked at it.

**Comment by StevilKnevil** [comment]
Yes, my hunch is that (for some reason) my block responsiveness is close to sensor responsiveness, breaking [assumption in the theory](https://marlinfw.org/docs/features/model_predictive_control.html#:~:text=In%20a%20real%20world%20system). (see: https://github.com/MarlinFirmware/Marlin/issues/25481).

While I have your attention could I also get your eyes on my [adjustments to the MPC documentation](https://github.com/MarlinFirmware/MarlinDocumentation/pull/487)? It caused me a bit of confusion when looking at manual tuning and comparing to the theory!

**Comment by thisiskeithb** [comment]
Closing since you've opened a PR:
- https://github.com/MarlinFirmware/Marlin/pull/25517
