### ISSUE TITLE
[BUG] Z PRobe Wizard travels at 0 possibly dragging on plate

### ISSUE THREAD

**Issue by neclimdul** [MarlinFirmware/Marlin#25491]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The wizard moves to the center of the build plate directly after homing. Unless your build plate is perfectly flat or dips toward the middle this will drag your nozzle over the surface.

I'm using both a probe and a homing switch to avoid driving my nozzle into the bed in the rare cases where the probe doesn't deploy and my suspicion is its limited to this case because the home with a probe would have the offset of the probe. If that's the case, it might just be nice to allow some sort of travel height offset in the configuration.

### Expected behavior

Nozzle doesn't drag on build plate during probe wizard.

### Actual behavior

Dragging over the buildpate	

### Steps to Reproduce

1. Start wizard
2. Observe dragging

### Version of Marlin Firmware

2.1.x@2b86daa30bb4705f8369ca27dd5fe723c90ef634

### Printer model

Ender 5 Pro

### Electronics

BTT SKR Mini E3 and a BLTouch

### Bed Leveling

No Bed Leveling

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[galetea.tar.gz](https://github.com/MarlinFirmware/Marlin/files/10943774/galetea.tar.gz)

**Comment by ellensp** [comment]
you have not updated     #define PROBE_OFFSET_WIZARD_START_Z -4.0 from the default value

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by neclimdul** [comment]
OK, I'll try that. The wording doesn't really make any sense. Also you closed this. Should I reopen a new issue to clarify or fix the problem?

**Comment by ellensp** [comment]
Its a config issue, user error, not a bug, and this is not a support forum.  See previous post.

**Comment by neclimdul** [comment]
I see it. I'll follow up with an additional issue and pull request that clarify why I think this is a bug. Thanks.

**Comment by neclimdul** [comment]
Confirmed today as the documentation for that configuration suggests it has no effect on the initial travel. Dug around and found there is no need for a new value, just this wizard doesn't use the existing value. 

Opened #25498 which demonstrates a fix which is hopefully the right one.
