### ISSUE TITLE
BTT Octopus Max Ez compile problem

### ISSUE THREAD

**Issue by gsuresh2u** [MarlinFirmware/Marlin#25494]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

for this board, when i try to compile, its giving error
```
"Resolving STM32H723Zx_btt dependencies...
Tool Manager: Installing platformio/framework-arduinoststm32 @ 4.20200.220530
Error: Could not find the package with 'platformio/framework-arduinoststm32 @ 4.20200.220530' requirements for your system 'windows_amd64'"
```

### Bug Timeline

today after merging this board

### Expected behavior

need to compile

### Version of Marlin Firmware

Bugfix 2.1.x, downloaded today

### Electronics

BTT Octopus Max Ez

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/10948662/config.zip)

**Comment by thisiskeithb** [comment]
This will be fixed in https://github.com/MarlinFirmware/Marlin/pull/25495
