### ISSUE TITLE
[BUG] `M20 L` trims long file names

### ISSUE THREAD

**Issue by eduard-sukharev** [MarlinFirmware/Marlin#25507]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When requested via Serial console or viewed on LCD screen, long filenames (both for files and for directories) are truncated to 13 characters, even with `LONG_FILENAME_HOST_SUPPORT` and `LONG_FILENAME_WRITE_SUPPORT` options enabled.

### Expected behavior

Filename is truncated to 13 characters

### Actual behavior

long filename is not truncated (if `LONG_FILENAME_HOST_SUPPORT` is enabled)

### Steps to Reproduce

1. save to SD card a file with filename longer than 13 characters
2. request SD contents with `M20 L` or browse via LCD menu

### Version of Marlin Firmware

bugfix-2.1.x

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Example behavior can be seen on this console output log screenshot
![image](https://user-images.githubusercontent.com/3235378/224566120-224a76bd-9630-44a1-85f9-666df488404a.png)

Sample filesystem to test `M20 L`
[fs.zip](https://github.com/MarlinFirmware/Marlin/files/10951731/fs.zip)

**Comment by thisiskeithb** [comment]
Closing since you've opened a PR:
- https://github.com/MarlinFirmware/Marlin/pull/25509
