### ISSUE TITLE
[BUG] Polargraph with X & Y axes (no Z axis) fails to compile

### ISSUE THREAD

**Issue by jbubik** [MarlinFirmware/Marlin#25513]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I am building a polargraph (Makelangelo-inspired). The template for a polargraph in Marlin defines X & Y & Z axes, but actually never uses the Z axis. Pen up/down is done by a servo (controlled by G code M280). So I tried to completely disable Z axis handling in my build. Some source files expect the Z_AXIS to always be defined and the compiler fails.

I identified those places (well, only in modules that I compiled in) and fixed them. PR will follow.

### Bug Timeline

Don't know, it's my first Marlin ever

### Expected behavior

Marlin compile properly with only X & Y axes.

### Actual behavior

Compile fails due to undefined Z axis in:
Marlin/src/inc/SanityCheck.h
Marlin/src/lcd/HD44780/marlinui_HD44780.cpp
Marlin/src/lcd/menu/menu_advanced.cpp
Marlin/src/libs/nozzle.cpp
Marlin/src/module/polargraph.cpp

### Steps to Reproduce

1. Comment-out Z_DRIVER_TYPE in Configuration.h (or use my config ZIP)
2. Try to compile - it fails

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Makelangelo (self-built clone)

### Electronics

mega2560 + RAMPS 1.4 + RepRapDiscount Smart Controller + A4988

### Add-ons

none

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10962165/Configuration.zip)

**Comment by ellensp** [comment]
Has bee merged, closing
