### ISSUE TITLE
compile error multiple definition of `Wire'

### ISSUE THREAD

**Issue by GuttalBug** [MarlinFirmware/Marlin#25528]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I am trying to use soft_i2c_eprom, I use the following declaration:
```cpp
#if NO_EEPROM_SELECTED
 //#define EEPROM_SETTINGS
 #define I2C_EEPROM
 #define SOFT_I2C_EEPROM
 #undef I2C_SDA_PIN
 #define I2C_SDA_PIN                           70
 #undef I2C_SCL_PIN
 #define I2C_SCL_PIN                           71
 #define MARLIN_EEPROM_SIZE                    0x7FFF  // 32K (25LC256)
 #undef NO_EEPROM_SELECTED
#endif
```
but wen I compile with Visual Studio Code I get the duplicate "Wire" definition error. If I remove the #define I2C_EEPROM statment I can compile but Marlin use eeprom emulation.
[Marlin configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10993773/Marlin.configuration.zip)

### Version of Marlin Firmware

02010200

### Printer model

custom corexy

### Electronics

board with arduino due

### Bed Leveling

None

### Your Slicer

None

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
Since BOARD_CABER is totally custom,we have no idea what platform this is on and absolutely no way to even start looking at this 

You need to provide sufficient information so we can replicate the issue. 

No Boards pin.h file 
No build environment details
Not even a error log.

**Comment by GuttalBug** [comment]
Thanks for the answer, I include the the pin definition for BOARD_CABER. 
[pins_CABER.zip](https://github.com/MarlinFirmware/Marlin/files/11007888/pins_CABER.zip)
The solution that I have found is to modify eeprom_if_i2c.cpp renaming "wire" to "wiregg".
[eeprom_if_i2c.zip](https://github.com/MarlinFirmware/Marlin/files/11007897/eeprom_if_i2c.zip)
The solution work perfectly but I don't know if there is a more elegant solution

**Comment by GuttalBug** [comment]
sorry I closed for mistake

**Comment by selahattinerdal** [comment]
Same problem. I have changed in eeprom_if_i2c.cpp
```cpp
#if ENABLED(SOFT_I2C_EEPROM)
  #include <SlowSoftWire.h>
  SlowSoftWire Wire = SlowSoftWire(I2C_SDA_PIN, I2C_SCL_PIN, true);
#else
  #include <Wire.h>
#endif
```
to
```cpp
  #include <Wire.h>
```
and its worked.

**Comment by GuttalBug** [comment]
with your solution you still use hardware I2c and not the SlowSoftWire that alluw to use any I/O pin

**Comment by thinkyhead** [comment]
The pins files define (or don't define) `SOFT_I2C_EEPROM`. So the simpler solution is to not define it in your pins file.

**Comment by GuttalBug** [comment]
But if I not define SOFT_I2c_EEPROM how can use generic I/O pins for I2C bus ?

**Comment by thisiskeithb** [comment]
This was probably fixed in https://github.com/MarlinFirmware/Marlin/pull/25707.

Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by GuttalBug** [comment]
I test with the last build and the problem is fixed. Thanks to all
