### ISSUE TITLE
[BUG] List 

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#25539]
Marlin is perfect !

**Comment by sjasonsmith** [comment]
I'm not sure what is going on with this bug report, but if this is just a list being constantly modified please do not do that. Each issue should be tracked in a separate bug report so they can be fixed and closed out individually.

I'm going to close this, but feel free to file individual reports for one problem at a time. If you already have solutions for them you can go ahead and post pull requests for those.

**Comment by studiodyne** [comment]
Sorry.

Thks
