### ISSUE TITLE
[BUG] (Failed to install 'marlinfirmware.auto-build'.)

### ISSUE THREAD

**Issue by Hueristic** [MarlinFirmware/Marlin#25549]
### Bug Description

Failed to install 'marlinfirmware.auto-build'.

### Steps to Reproduce

Failed to install 'marlinfirmware.auto-build'.
Download manually
Install from vsix
MarlinFirmware.auto-build-2.1.45.vsix install failes with error "Unable to install Extension 'marlinfirmware.auto-build-2.1.45' as it is not compatible with Code '1.25.1'."

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MarlinFirmware/vsextensions/auto-build/2.1.45/vspackage
"message	"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950)."
typeName	"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server"
typeKey	"RequestBlockedException"
errorCode	0
eventId	3000"

### Version of Marlin Firmware

2.1.2

Love everything depending on M$ to work, really makes life easy doesn't it?

**Comment by ellensp** [comment]
Marlin uses platformio under the vscode editor. this is not visual studio

https://marlinfw.org/docs/basics/install_platformio_vscode.html

**Comment by Hueristic** [comment]
platformio is installed.



Found the issue, apparently M$ likes to hide errors. Updated OP

"MarlinFirmware.auto-build-2.1.45.vsix install failes with error "Unable to install Extension 'marlinfirmware.auto-build-2.1.45' as it is not compatible with Code '1.25.1'."
"

Fix: updated to VSCode 1.70.2 as apparent;y M$ doesn't allow 1.70.3 downloads yet states it is last version supported by OS.

So why no binaries for download?

I'm going to take a guess M$ pulled a fast one, ergo forcing VScode use?
