### ISSUE TITLE
[BUG] Stepper buzzing, full ABL fails using high Driver Voltage.

### ISSUE THREAD

**Issue by FlailAway** [MarlinFirmware/Marlin#25546]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have 4 x Z-axis lead-screws on a large format printer and all driven by a single closed belt with a drive ratio steps of 1500:1. Using a MKS-GEN_L board and NEMA-17 x 48mm (1.2A) stepper I would occasionally lose a few steps. I have a dial indicator permanently on the Z-axis for the probing range.

I changed to a 60mm (2.1A) stepper and adjusted the TMC2208 (stand-alone) from 0.96-vdc to 2.54-vdc. It seems to print OK and never loses steps.

The bug:
When doing an ABL bed-level with G29 with the secondary slow (Z_PROBE_FEEDRATE_SLOW) probe the motor makes a buzzing noise going down and after about 5 to 9 probes (5/81 to 9/81) it stalls and says "stow probe."

I reduced the TMC voltage down in 0.05-vdc increments to 2.10-vdc and it will complete a full ABL.  It still buzzes a little but that kinda defeats usng a bigger motor.

Have I screwed up with the voltage calculaton or how can I use the full TMC2208 2.54-vdc?

configuration.h
...
// X and Y axis travel speed (mm/min) between probes
#define XY_PROBE_FEEDRATE (133*60)

// Feedrate (mm/min) for the first approach when double-probing (MULTIPLE_PROBING == 2)
#define Z_PROBE_FEEDRATE_FAST (4*60)

// Feedrate (mm/min) for the "accurate" probe of each point
#define Z_PROBE_FEEDRATE_SLOW (Z_PROBE_FEEDRATE_FAST / 2)

...
#define MULTIPLE_PROBING 2

### Bug Timeline

When I swapped in a bigger motor

### Expected behavior

To not fail the ABL at the calculated voltage.

### Actual behavior

... as described in Bug Description

### Steps to Reproduce

... as described in Bug Description

### Version of Marlin Firmware

2.1.2-BF (dec 2022)

### Printer model

Bespoke

### Electronics

MKS-Gen-L 

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Not dependent on the slicer. I tried Cura/Prusa/Ideamaker all latest versions.

**Comment by SpannMagoo** [comment]
I had this as well and my board is a 4.2.7 creality.
