### ISSUE TITLE
[BUG] (bug summary) TMC2209 Sensorless homing only moves axis a small amount and never triggers

### ISSUE THREAD

**Issue by mikedattolo** [MarlinFirmware/Marlin#25556]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I am trying to go about making a prototype 5D printer, and I want to use both physical end stops and sensorless homing. I have managed to get both to work together without any errors. However, my only issue is that my custom axis Axis_I, when I got to home the axis it only moves a small amount, before I could get it to move all the way, but still wouldn't trigger, and even now, with it only moving a little if it reaches a physical limit or tries to bump/crash into something it doesn't detect it and still only moves a small amount, I can try and home it as many times as I like and won't work, I have done testing with sensitivity clearly that wouldn't do anything, If I remove the Diag pins it triggers them but doesn't respond to sensitivity and are permanently triggered. Using the M119 command XY and Z are able to be triggered when I home them except for Axis_I. I could really use some help if anyone knows any solutions. *note for anyone reading this, XYZ has physical end stops that work normally, my custom axis Axis_I is sensorless if I didn't make that clear*

### Bug Timeline

NEW

### Expected behavior

I expect it to move all the way and home

### Actual behavior

Moves only a small amount and doesn't trigger when hitting a physical limit.

### Version of Marlin Firmware

Marlin 2.0.9.3

### Printer model

Ender 3V2

### Electronics

BTT Octopus control board and TMC2209 Drivers

### Bed Leveling

None

### Your Slicer

None

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by mikedattolo** [comment]
any input would be nice plzzz

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
