### ISSUE TITLE
If Then style operations in start/end code

### ISSUE THREAD

**Issue by 3DPRescue** [MarlinFirmware/Marlin#25576]
### Describe the feature you want

The ability to choose startup functionally like a purge line.

**Comment by thisiskeithb** [comment]
> The ability to choose startup functionally like a purge line.

This would be handled via your slicer.

**Comment by 3DPRescue** [comment]
Thanks for closing my ticket without actually grasping the concept. --Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 3/26/23, 09:52 Keith Bennett ***@***.***> wrote:

   
   
   The ability to choose startup functionally like a purge line. 
   
  This would be handled via your slicer.

**Comment by Nuck-TH** [comment]
You don't seem to grasp it either. Gcode is not programming language, it is set of instructions that can't directly depend on each other, only via state of machine(like waiting for heatup).
So the answer was correct - you need to edit start code in your slicer to add or remove desired actions.
