### ISSUE TITLE
[BUG] SKR mini E3 V3 + BLouch clone - hits bed while leveling or homing

### ISSUE THREAD

**Issue by Rambus100lica** [MarlinFirmware/Marlin#25588]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

SKR mini E3 V3 + bugfix-2.1.X firmware + 3Dtouch via Two Trees (BL Touch clone) 
Wiring and setup looks to be correct because test passes through without error
Send: M43 S0
Recv: Servo probe test
Recv: . using index:  0, deploy angle: 10, stow angle:   90
Recv: . Probe Z_MIN_PROBE_PIN: 46
Recv: . Z_MIN_PROBE_ENDSTOP_INVERTING: false
Recv: . Check for BLTOUCH
Recv: = BLTouch Classic 1.2, 1.3, Smart 1.0, 2.0, 2.2, 3.0, 3.1 detected.
Recv: ** Please trigger probe within 30 sec **
Recv: . Pulse width (+/- 4ms): 8
Recv: = BLTouch pre V3.1 (or compatible) detected.
Recv: ok

### Bug Timeline

First configuration after adding probe to printer

### Expected behavior

Homing and bed leveling via proobe

### Actual behavior

Probe doesn't stop Z axis movement and crushes into bed 

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.1.x (Mar 24 2023 08:00:15)

### Printer model

Creality Ender 3 Pro

### Electronics

BTT SKR Mini E3 V3.0

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11090020/Configuration.zip)

**Comment by ellensp** [comment]
you have not enabled #define USE_PROBE_FOR_Z_HOMING

So its looking at the z-endstop pin not the probe pin

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by Rambus100lica** [comment]
> you have not enabled #define USE_PROBE_FOR_Z_HOMING
> 
> So its looking at the z-endstop pin not the probe pin

Yes, because I couldn't use printer at all, during homing it crashes into the bed
For now I have to home at physical micro switch

**Comment by thisiskeithb** [comment]
> Probe Z_MIN_PROBE_PIN: 46

You also have `#define Z_MIN_PROBE_PIN P46` in your config, but disabled. Were you using `P46`? You don't need to define a probe pin for the SKR Mini E3 V3, but the default probe pin is `PC14`:

https://github.com/MarlinFirmware/Marlin/blob/de0cd660705668f2e9f1e0cb8fff80b40be0f4e6/Marlin/src/pins/stm32g0/pins_BTT_SKR_MINI_E3_V3_0.h#L61-L64

> Expected behavior
> Homing and bed leveling via proobe

> Actual behavior
> Probe doesn't stop Z axis movement and crushes into bed

And as ellensp said, you have `USE_PROBE_FOR_Z_HOMING` disabled in your config, so your probe won't be used for homing.

Since this config doesn't seem to match what you were using, please provide the *exact* configuration files that cause the reported issue.

**Comment by ellensp** [comment]
@thisiskeithb 

M43 is a little primitive in its report

It uses
`  #define PROBE_TEST_PIN Z_MIN_PROBE_PIN
`
So PROBE_TEST_PIN is set to PC14, which is really 46
Then it prints to serial
`    SERIAL_ECHOLNPGM(". Probe " _PROBE_PREF "_PIN: ", PROBE_TEST_PIN);
`
This prints out 46 vs PC14

So this is actually correct, if misleading

**Comment by Rambus100lica** [comment]
While I have still 2 hrs to end of the print I'll rebuild config a little bit later.
Meantime, please remember that problem occurs also while bed leveling.
Is there any chance to make printer to not to ignore endstop during bed leveling?

**Comment by Rambus100lica** [comment]
> You also have `#define Z_MIN_PROBE_PIN P46` in your config, but disabled. Were you using `P46`? You don't need to define a probe pin for the SKR Mini E3 V3, but the default probe pin is `PC14`:

It was very late and my patience has gone, so I was trying any, also crazy, idea ;)

**Comment by thisiskeithb** [comment]
> Meantime, please remember that problem occurs also while bed leveling.

I was using a genuine BLTouch on an SKR Mini E3 V3 just a couple weeks ago without issue, so that is very odd.

> Is there any chance to make printer to not to ignore endstop during bed leveling?

`ENDSTOPS_ALWAYS_ON_DEFAULT`

**Comment by Rambus100lica** [comment]
Changes made
#define USE_PROBE_FOR_Z_HOMING
#define ENDSTOPS_ALWAYS_ON_DEFAULT

#define DEBUG_LEVELING_FEATURE
[Debug-Endstop.txt](https://github.com/MarlinFirmware/Marlin/files/11094208/Debug-Endstop.txt)
[Debug-Homing.txt](https://github.com/MarlinFirmware/Marlin/files/11094209/Debug-Homing.txt)

Z endstop was ignored at homing procedure - see Debug files
As Marlin doc for M120 states: After this command endstops will be kept enabled when not homing. 
As I understand correctly this will work only during print job, when homing endstops are always ignored

I couldn't check probe pin
Send: M43 P46
Recv: PIN: PC14        M42 P46          Z_MIN_PROBE_PIN                        protected
Recv: ok

Updated config files attached
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11094272/Configuration.zip)

I'm adding also a video of unfinished homing procedure 
https://youtu.be/kfy35GukC6I

**Comment by Rambus100lica** [comment]
It seems that during homing with #define USE_PROBE_FOR_Z_HOMING and bed leveling, firmware doesn't see probe trigger signal, even when I manually set #define Z_MIN_PROBE_PIN PC14.
As @ellensp said, M43 S0 is primitive, can I assume that it works independably from config.h settings?
If so there is kind of pin mismatch at config files? or something is not bind correctely.
Debugging g29 reveals error "Recv: SLOW Probe fail! - No trigger."
[Debug_G29.txt](https://github.com/MarlinFirmware/Marlin/files/11100806/Debug_G29.txt)

Any ideas??

**Comment by thisiskeithb** [comment]
> can I assume that it works independably from config.h settings?
If so there is kind of pin mismatch at config files? or something is not bind correctely.

No, it matches up correctly.

I suspect there’s a wiring/hardware issue. Can you take clear/HD photos of the back of your probe & where it connects to your motherboard?

**Comment by Rambus100lica** [comment]
cable extension mapping
green - green
red - orange
yellow - yellow
black - black
white - white
![1680378531962](https://user-images.githubusercontent.com/18756728/229311515-05746a42-d2e6-453e-bd1f-4d3ca4c4337e.jpg)
![1680378531969](https://user-images.githubusercontent.com/18756728/229312241-990047c4-ba1e-4b34-865e-1d024f1ef486.jpg)

**Comment by ellensp** [comment]
bltouch motherboard plug seems to be in backwards

It should be like this

<img src="https://www.makenprint.uk/wp-content/uploads/2021/12/Bigtree-Tech-BTT-SKR-Mini-E3-V3-Antclabs-genuine-BLTouch-wiring-826x410.jpg.webp" >

With the black and white cables ending up on the left of the plug (next to the jumper) in your motherboard picture orientation

Sadly this means you have been applying 5v to the bltouch gnd pin. this bltouch is very likely dead.

**Comment by Rambus100lica** [comment]
@ellensp 
I'm not sure what are You talking about.
Probe is still UP and running witth M43, below complete pin/wire mapping
Probe -> Cable       -> Mainboard
Z-       -> White      -> PC14
G        -> Black       -> GND
S         -> Yellow     -> PA1
5V       -> Red/Orange -> PWR
G        -> Green      -> GND
![1680378531962_1](https://user-images.githubusercontent.com/18756728/229338462-503222ce-1677-4453-b61b-85aca69d2422.jpg)

**Comment by ellensp** [comment]
Which is why I removed my post, it was wrong

**Comment by Rambus100lica** [comment]
Ok :), so can You reopen thread?2 kwi 2023 09:28 ellensp ***@***.***> napisał(a):
Which is why I removed my post, it was wrong

**Comment by thisiskeithb** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
try disabling BLTOUCH_FORCE_SW_MODE In Configuration_adv.h 
Its been reported that this is not compatible with some 3d touch clones of the bltouch. 

If this is the case, 'we' may have to add a 3dtouch setting that ensures that  BLTOUCH_FORCE_SW_MODE is disabled.

**Comment by Rambus100lica** [comment]
> try disabling BLTOUCH_FORCE_SW_MODE In Configuration_adv.h Its been reported that this is not compatible with some 3d touch clones of the bltouch.

YES!! That was it; //#define BLTOUCH_FORCE_SW_MODE solved problem.

@ellensp 
@thisiskeithb 
Thank You very much for your help and commitment.

**Comment by thisiskeithb** [comment]
> If this is the case, 'we' may have to add a 3dtouch setting that ensures that BLTOUCH_FORCE_SW_MODE is disabled.

The CRTouch also doesn't like `BLTOUCH_HS_MODE`, so we could just add some comments about common gotchas for BLTouch clones instead of adding more options to the configs.

**Comment by Rambus100lica** [comment]
If I may have a word, appropriate comment in Configuration_adv.h should be enough.
