### ISSUE TITLE
[BUG] (bug multiple definition of `goto_tramming_wizard()

### ISSUE THREAD

**Issue by nicwilson58** [MarlinFirmware/Marlin#25603]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Compiling example code for Ender2-Pro ends with a linking error:

**See error below:**  **commenting out one of the two duplicate functions then compiles without error.**

_Linking .pio\build\STM32F103RE_creality\firmware-20230330-151917.elf
c:/users/nic.wilson/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/STM32F103RE_creality/src/src/lcd/menu/menu_tramming_wizard.cpp.o: in function `MarlinUI::defer_status_screen(bool)':
E:\PlatformIO\Marlin\Ender2\Ender2-Pro/Marlin\src\lcd\menu\../marlinui.h:604: multiple definition of `goto_tramming_wizard()'; .pio/build/STM32F103RE_creality/src/src/lcd/menu/menu_tramming.cpp.o:E:\PlatformIO\Marlin\Ender2\Ender2-Pro/Marlin\src\lcd\menu\../marlinui.h:604: first defined here
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\STM32F103RE_creality\firmware-20230330-151917.elf] Error 1_

### Bug Timeline

new bug,  first time compile today

### Expected behavior

compilation success

### Actual behavior

linker error as described above

### Steps to Reproduce

1.  Marlin example Ender2-Pro config files,  edited to enable Bltouch and Tramming wizard
2.  compile to error.

### Version of Marlin Firmware

bugfix-2.1.x  nightly  29th March 2023

### Printer model

Ender2-Pro

### Electronics

standard

### Add-ons

CRtouch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11108108/Marlin.zip)

**Comment by ellensp** [comment]
I cannot reproduce this.

breaking down the error I see

`src/lcd/menu/menu_tramming_wizard.cpp.o
`
This is the expected source file compiled

`src/lcd/menu/menu_tramming.cpp.o:
`
This file does not exist in marlin bugfix, This is left over from a previous version of Marlin

Most probable cause, You extracted new Marlin over an old marlin directory, Creating a mix of old and new code.

delete marlin directory and download a fresh copy.
