### ISSUE TITLE
[BUG] Overextrusion from layers 2 to 6 only

### ISSUE THREAD

**Issue by thewheelman282** [MarlinFirmware/Marlin#25601]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

E-steps for extruder have been calibrated and the first layer of a print job is completely perfect. When layer 2 begins there is suddenly heavy over extrusion especially noticeable in solid infill, creating a washboard effect on the print. The host software and M221 both report 100% flowrate at all times. Printing behavior is otherwise normal. Around layer 6 (assuming the print doesnt detach from the bed) the over extrusion goes away and normal extrusion resumes. I have found that this can be remedied by changing the flowrate manually to 50% when layer 2 starts, then change it back to 100% when layer 6 or 7 starts. If I dont change the flowrate back to 100% around layer 6, there is underextrusion.

I have tried the same g-code in 2 host software and the result is the same.

I found a previous bug report similar to this where flowrate randomly changed between layers but it seems that turned out to be a hardware fault on that person's printer, so its probably not related.

In the attached picture, the print on the left is only layer 1. The print on the right is layers 1 and 2.
[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/11106848/Configurations.zip)
![20230329_215224](https://user-images.githubusercontent.com/129340616/228708332-11b91e0f-bb62-49a0-984b-d6c4c156f22a.jpg)

### Bug Timeline

Seems to be new. Cant find previous bug reports on this subject

### Expected behavior

Flowrate between layers to be consistent.

### Actual behavior

Layers 2 - (approx)6 are over extruded for unknown reason

### Steps to Reproduce

Start print with bottom infill and observe physical layer extrusion. Flowrate does not change in software.

### Version of Marlin Firmware

2.1.2 and bugfix 2.1.x

### Printer model

Ender 3 (2018 orignal model)

### Electronics

Stock melzi/Creality v1.1.3

### Add-ons

BLTouch clone

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

Repetier Host

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by EvilGremlin** [comment]
Such issues are usually slicer bugs. 
> I have tried the same g-code in 2 host software and the result is the same

This is your error. Was this exact gcode good before firmware change? Did you try different gcode? You must.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.
