### ISSUE TITLE
[BUG] SD image can't be loaded after pressing "Generate Empty Image" in the simulator.

### ISSUE THREAD

**Issue by mriscoc** [MarlinFirmware/Marlin#25602]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The simulator allows you to test some Marlin functions without having a physical printer. It is possible to simulate a SD memory card by loading an image file, the simulator itself can create an empty image by pressing Generate Empty Image button:
![image](https://user-images.githubusercontent.com/2745567/228733874-c1e4a41f-aa71-4d17-b465-c5e8e5fbb19f.png)
But, after the image is created and loaded an error is shown in the console: "Error: volume, init failed"
![image](https://user-images.githubusercontent.com/2745567/228734000-69eb27ff-9a7a-4ad8-a28a-85989e178c3e.png)

Simulator compiled and running under Windows 10 with the example configuration files from the configuration repository.

The image is generated correctly, it was tested with third-party software.
![image](https://user-images.githubusercontent.com/2745567/228735006-cc781333-0af0-442e-a485-91fc41b1658b.png)

### Bug Timeline

There are no previous notices about it

### Expected behavior

SD image must be loaded by the simulator without errors.

### Actual behavior

SD images can't be loaded by the simulator.

The image was then formatted to FAT32 with the same error.

### Steps to Reproduce

Download latest bugfix
Install simulator dependencies
Download simulator configuration files
Compile simulator
Run simulator
Pressing "Generate Empty Image" button:
![image](https://user-images.githubusercontent.com/2745567/228733874-c1e4a41f-aa71-4d17-b465-c5e8e5fbb19f.png)
The image is created but an error is shown in the console: "Error: volume, init failed"
![image](https://user-images.githubusercontent.com/2745567/228734000-69eb27ff-9a7a-4ad8-a28a-85989e178c3e.png)

### Version of Marlin Firmware

Latest Marlin Bugfix

### Printer model

Simulator

### Electronics

Simulator

### Add-ons

None

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by EvilGremlin** [comment]
Probably better to file up in actual sim repo https://github.com/p3p/MarlinSimUI
Tried it in linux yet?

**Comment by p3p** [comment]
Unable to replicate at the moment will need to try on Windows though, make sure you are using the most recent version, delete both `.pio` in Marlin, and `.cache` that should be in `.platformio` in your home folder.

**Comment by p3p** [comment]
https://github.com/p3p/MarlinSimUI/issues/22

Turns out the issue was in Marlin and not the sim after all, although can't really blame it for the compiler on Windows messing up the bit packing.

**Comment by mriscoc** [comment]
@p3p thanks!

**Comment by thisiskeithb** [comment]
Closing since there’s now a PR.
