### ISSUE TITLE
[BUG] in probe.cpp `npos` has no effect warning

### ISSUE THREAD

**Issue by classicrocker883** [MarlinFirmware/Marlin#25633]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

>src/module/probe.cpp: In static member function 'static float Probe::probe_at_point(const_float_t, const_float_t, ProbePtRaise, uint8_t, bool, bool)':
src/module/probe.cpp:942:4: warning: left operand of comma operator has no effect [-Wunused-value]
  942 |   (npos, feedRate_t(XY_PROBE_FEEDRATE_MM_S));
      |    ^~~~

I used `make` to compile for [shadow578 repo for the HC32 chip](https://github.com/shadow578/Marlin-H32).

it compiles fine without `BLTOUCH` enabled, but I am left with this error
along with these

>/src/gcode/control/M280.cpp:66: undefined reference to `libServo::detach()'
>/src/gcode/control/M280.cpp:63: undefined reference to `libServo::move(long)'
>/src/gcode/control/M280.cpp:69: undefined reference to `libServo::read() const'
>/src/module/servo.cpp:42: undefined reference to `libServo::detach()'
>/src/module/servo.cpp:33: undefined reference to `libServo::libServo()'
>/src/feature/bltouch.cpp:46: undefined reference to `libServo::move(long)'

and some others similar to the above

### Version of Marlin Firmware

Newest Bugfix with HC32 library

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
This is a 3rd party github, and as such all issue related to it must be made on that github. 

This has nothing to do with this Marlin github.
