### ISSUE TITLE
[FR] I2C to a toolboard extender

### ISSUE THREAD

**Issue by TheOracle2212** [MarlinFirmware/Marlin#25638]
### Is your feature request related to a problem? Please describe.

So currently, Duet3D and Klipper have functions where you can communicated via i2c to an external toolboard which cleans up your wiring. 
I've been planning a PCB which takes in Hotend temperature, Fan(s) temperature, and reports Z probe (if applicable), hotend temperature (read) and so on. I might even add a Stepper motor driver if you are running a Direct Drive setup. Its like the PandaCAN but for Marlin. I've added a accelerometer for potential input shaping down the line so that when (and if) Marlin adopts real-time input shaping, It'll work automatically.

### Describe the feature you want

Essentially, I'd like this to work where Marlin outputs the Hotend Temperatures, (upon enabling) Extruder movement, and this board will output the read hotend temperature, z-probe trigger. I'm looking to fully develop this so that my (and maybe more people) can foster adding quick change toolheads (potentially, even for lasers, routers???) but mainly to clean up the wiring.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/7735

**Comment by thisiskeithb** [comment]
The linked FR above also covers i2c/tool head discussions.
