### ISSUE TITLE
[FR] Allow delay before MINTEMP protection kicked in on startup

### ISSUE THREAD

**Issue by landgraf** [MarlinFirmware/Marlin#25644]
### Is your feature request related to a problem? Please describe.

While the feature to halt on BED_MINTEMP  is extremly useful If print started in cold condition and temp sensor is unable to report low temperature reliably due to its nonlinear characteristic the printer is halted even if everything is ok.

For example: SKR 1.2 E3 + ender 3 thermistor reports any temperature below ~12C as 0C. thus some sort of "bootstrap" is needed to start the heating.

### Are you looking for hardware support?

This should be hardware independent.

### Describe the feature you want

Allow some sort of (configurable) delay before checking for MINTEMP.
i.e. allow printer to heat itself before checking the temperature. in my setup 5 secs is more than enough.

**Comment by thisiskeithb** [comment]
This already exists: 

https://github.com/MarlinFirmware/Marlin/blob/7e700c13948506ab0fc57719c7c1bd35f0cb33c4/Marlin/Configuration_adv.h#L515-L523
