### ISSUE TITLE
[BUG] Ender 3 filament runout sensor issues

### ISSUE THREAD

**Issue by BradKernan** [MarlinFirmware/Marlin#25651]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Hello. I have an Ender 3 with a 4.2.7 motherboard, CR Touch, and a Creality filament runout sensor. After I installed the sensor, my printer would make 1 pass on the test strip when I start a print, then initiate a filament change. After going through the steps, the Z axis would go down, then do the second pass on the test strip, then initiate the main print. I'm also having issues with the probe offset. I'll set it using the paper trick, but the Z axis is still starting very high when starting a print. I don't even know where to begin with the bug fix since there seems to be a ton of different things in the folders. If someone could point me in the right direction, I'd be willing to try it. Any ideas or updates would be greatly appreciated. Thank you!

### Bug Timeline

New bug, started after installing filament runout sensor.

### Expected behavior

Start a print, do 1 pass on the test strip, then another pass on the test strip, then initiate the main print. Z axis starts prints at a good height.

### Actual behavior

Start a print, does 1 pass on the test strip, raises Z axis, initiates filament change, then does second pass after going through the filament change procedure. Z axis also starts prints too far away from the bed despite setting offset.

### Steps to Reproduce

It does this every time, even if the cable connecting the motherboard and filament sensor is completely removed.

### Version of Marlin Firmware

Ender3-v4.2.7-BLTouch-20230404

### Printer model

Creality Ender 3

### Electronics

4.2.7 motherboard

### Add-ons

CR Touch, filament runout sensor

### Bed Leveling

ABL Linear grid

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Can't upload firmware or ZIP file, but it is Ender3-v4.2.7-BLTouch-20230404.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
