### ISSUE TITLE
Dual z-axis: z2 always triggered (BTT Octopus Pro 1.0)

### ISSUE THREAD

**Issue by Tobi-Asis** [MarlinFirmware/Marlin#25675]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I put 4 TMC2209 into the Octopus Pro (Motor 0, 1, 2, 3 - not using 2.2). I want to use Dual z-axis. Unfortunately, the z2 endstop state is always TRIGGERED, no matter what I do, with physical switch or with stallguard. I even tried to use another pin by changing PG11 pin to PG15 in pins.h and wiring DIAG to PG15. Still won't work, so hardware error is unlikely

```
SENDING:M119

Reporting endstop status

x_min: open

y_min: open

z_min: open

z2_min: TRIGGERED

```
Measured with Multimeter, it is LOW, so it should not be recognized as triggered. X, Y and Z work just fine. Spent last 12h trying to fix it in Marlin, but nothing works.

Is it possible, that z2 refers to the wrong pin in Marlin and not to PG11?

I am desperate for help!

I have my whole Marlin here, in case it is necessary: https://drive.google.com/file/d/1edzagCxMwSad--tAG9bujCXutaxe81Le/view?usp=share_link

### Bug Timeline

newly discovered

### Expected behavior

I expected z2_min or z2 endstop to be "open" instead of "triggered". I expected that I can home z-axis and both motors would move to their endstops

### Actual behavior

Instead, z2 does not move and only z moves until i trigger its endstop. then, both move to the opposite direction (must be the bump)

### Steps to Reproduce

1. insert TMC2209 to Octopus
2. attach 4 endstops or prep for sensorless homing
3. configure Marlin to octopus board
4. run M119
5. find that x, y and z axis endstops are "open" while z2 is always "triggered"

### Version of Marlin Firmware

2.1.2

### Printer model

no 3d printer, other machine

### Electronics

BTT TMC2209, BTT Octopus, stock

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[marlin-z2-problem.zip](https://github.com/MarlinFirmware/Marlin/files/11234121/marlin-z2-problem.zip)

**Comment by ellensp** [comment]
you have ```#define Z2_USE_ENDSTOP   _XMAX_ ```

so it is looking at pin E0_DIAG_PIN   PG12


This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by Tobi-Asis** [comment]
You solved my problem I have struggled with for days! Thank you so much! 
And apologies for the misuse. I will take care to ask these questions elsewhere.
