### ISSUE TITLE
Can we create a simple version?

### ISSUE THREAD

**Issue by Gornerrrrr** [MarlinFirmware/Marlin#25673]
### Describe the feature you want

Is not a feature requirement, is new branch requirement. 
I've been using Marlin firmware on 3D printers for years, the Marlin is a successful open source project, but it is also bloated to ensure compatibility.
I just want to learn and transplant a stepper motor control + temperature control system based on 32bit MCU through it.
Marlin1.1 is a little old(not support 32bit MCU), and Marin 2.1 has too many macro definitions and files, and they are related to each other.
I think to achieve this goal, I only need code files such as steper, motion, planner, temperature, gcode, parser, etc.
Does anyone have any suggestions or branch recommendations? Thanks for your help!

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
