### ISSUE TITLE
[HELP] Filament runout false triggering despite sensor value or code.

### ISSUE THREAD

**Issue by mmski87** [MarlinFirmware/Marlin#25670]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Hello,

I'm encountering a problem with filament runout.
Marlin 2.0.6.1 (rather don't want to change it for now)
Setup:
MKS Robin E3D clone (ATOMSTACK FB5 2.0)+ DGUS DWIN FYSETC touchscreen 4,3 inch
Despite the state of sensor printers always says filament has run out. 
-> My steps were to reverse logic (LOW/HIGH) but this didn't work at all. 
-> I have tried internal pullups/pulldowns
-> So i decided to disable filament runout completly in config, but problem still persist despite of being commented on code.

At this point i'm completly driven into woods and lost track where should i check.
I have tried latest marlin with correct board config, but the board won't boot at all and there's diffrence in build size (171kb stock, 81kb newest marlin).

Where should i look deeper to fix it? Can someone lend me a hand with this?

Producer of printer has working .bin file, but source files are diffrent from normal marlin builds i have encountered so far.
On stock firmware, printer shouts only static numbers via serial USB so can't debug with pins (no normal view as any other marlin, cant insert marlin gcodes)

Thanks very much

### Expected behavior

It should respond to config file changes.

### Actual behavior

Filament runout triggered

### Version of Marlin Firmware

2.0.6.1

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11226621/Marlin.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
