### ISSUE TITLE
[BUG] M206 not usable anymore

### ISSUE THREAD

**Issue by ThomasToka** [MarlinFirmware/Marlin#25693]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After a rebuild of my Fork with bugfix-2.1.x in the beginning of the month i have seen that M206 is not usable anymore to adjust x_min_pos and y_min_pos.

What is the way now to set those min positions like it was possible before the change with a gcode by a user to adjust his/her min positions?

### Bug Timeline

New bug, but probably caused by changes that i missed

### Expected behavior

Setting x_min and y_min positions to adjust by gcode like

M206 x-0.8 y-2.0
M500

-> Printer uses this as x_min_pos and y_min_pos as home endstop position.

### Actual behavior

```
Recv: area:{full:{min:{x:-0.80,y:-2.00,z:0.00},max:{x:241.00,y:235.00,z:270.00}},work:{min:{x:0.00,y:0.00,z:0.00},max:{x:235.00,y:235.00,z:270.00}}}

Recv: echo:  M206 X0.00 Y0.00 Z0.00
```

so m206 is empty and x_min / y_min moved to area.

### Steps to Reproduce

look in M503. M206 is empty.

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Ender 3 S1 Pro

### Electronics

Creality F4 Mainboard

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[configurations.zip](https://github.com/MarlinFirmware/Marlin/files/11241616/configurations.zip)

**Comment by ellensp** [comment]
I just tested this on a ramps. 

Fresh bugfix-2.1.x  firmware mismatched versions as expected so eeprom  was reset to defaults

M503 results, As expected

echo:  M206 X0.00 Y0.00 Z0.00

enter 
M206 X-1Y-2
M500

check M503, results as expected
echo:  M206 X-1.00 Y-2.00 Z0.00

reboot and re check M503, still has M206 values.

**Comment by ThomasToka** [comment]
yes. that is right. it saves it in the fields. but put your printer on g28 x y (edit: endstop positions) and watch what your display says.

also area section is not updated.

firmware value for x_min_pos=-0.8 y_min_pos=-2

Recv: area:{full:{min:{x:-0.80,y:-2.00,z:0.00},max:{x:235.00,y:235.00,z:250.00}},work:{min:{x:0.00,y:0.00,z:0.00},max:{x:235.00,y:235.00,z:250.00}}}
Recv: echo:  M206 X0.00 Y0.00 Z0.00

x and y endstop positions shown are x=-0.8 y=-2

setting 

M206 X-2 Y-2

results in 

Recv: area:{full:{min:{x:-0.80,y:-2.00,z:0.00},max:{x:235.00,y:235.00,z:250.00}},work:{min:{x:0.00,y:0.00,z:0.00},max:{x:235.00,y:235.00,z:250.00}}}
Recv: echo:  M206 X-2.00 Y-2.00 Z0.00

x and y endstop positions shown are x=-0.8 y=-2

so it is saved but not used.

**Comment by ThomasToka** [comment]
edit: just a minute. made it wrong. i have +6 set on x max pos.

**Comment by ThomasToka** [comment]
Just to verify again:

    installation of firmware with x_min_pos=-2 and y_min_pos=-2

x_bed_size 235
y_bed_size 235

x_max_pos = x_bed_size +6
y_max_pos = y_bed_size

Recv: area:{full:{min:{x:-2.00,y:-2.00,z:0.00},max:{x:241.00,y:235.00,z:270.00}},work:{min:{x:0.00,y:0.00,z:0.00},max:{x:235.00,y:235.00,z:270.00}}}

Recv: echo: M206 X0.00 Y0.00 Z0.00

setting

M206 x-3 y-3
M500
m503
shows:
Recv: echo: M206 X-3.00 Y-3.00 Z0.00

Recv: echo:enqueueing "G28 X Y"
[...]
Send: M114
[...]
Recv: X:-5.00 Y:-5.00 Z:6.75 E:0.00 Count X:-159 Y:-159 Z:2700

so the offsets are added.

rebooting printer.

area shows:

Recv: area:{full:{min:{x:-5.00,y:-5.00,z:0.00},max:{x:238.00,y:232.00,z:270.00}},work:{min:{x:-3.00,y:-3.00,z:0.00},max:{x:232.00,y:232.00,z:270.00}}}

in full it was added. i think it should overwrite it.
in max it reduced max positions. here it should not affect it so not be visible.
in min it is ok as it should be
second max it reduced by subtracting. what is this used for?

well..

can you explain?

**Comment by ThomasToka** [comment]
@ellensp please do G28 X Y and M114 after setting it. there you should see it.

**Comment by ThomasToka** [comment]
i maybe did a false example initially i realize. but the problem comes more out the further i dig in it.

users are not able anymore to set their offsets correctly with M206. I know it worked as it should but cant find the change and also cant find my last working version with this atm..

**Comment by ThomasToka** [comment]
if i understand the comments here right:
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/inc/Conditionals_post.h#L3227
```
// Updated G92 behavior shifts the workspace
#if DISABLED(NO_WORKSPACE_OFFSETS)
  #define HAS_POSITION_SHIFT 1
  #if IS_CARTESIAN
    #define HAS_HOME_OFFSET 1       // The home offset also shifts the coordinate space
    #define HAS_WORKSPACE_OFFSET 1  // Cumulative offset to workspace to save some calculation
    #define HAS_M206_COMMAND 1      // M206 sets the home offset for Cartesian machines
  #elif IS_SCARA
    #define HAS_SCARA_OFFSET 1      // The SCARA home offset applies only on G28
  #endif
#endif
```

then this is what i want:
``` 
// Updated G92 behavior shifts the workspace
#if DISABLED(NO_WORKSPACE_OFFSETS)
  #define HAS_POSITION_SHIFT 1
  #if IS_CARTESIAN
    #define HAS_HOME_OFFSET 0       // The home offset also shifts the coordinate space
    #define HAS_WORKSPACE_OFFSET 0  // Cumulative offset to workspace to save some calculation
    #define HAS_M206_COMMAND 1      // M206 sets the home offset for Cartesian machines
  #elif IS_SCARA
    #define HAS_SCARA_OFFSET 1      // The SCARA home offset applies only on G28
  #endif
#endif
```

but this gives me a compilation error:

```
PS C:\Users\master\Documents\GitHub\Marlin> echo "done" >"C:\Users\master\AppData\Local\Temp\ipc"
In file included from Marlin\src\inc/MarlinConfigPre.h:37,
                 from Marlin\src\inc/MarlinConfig.h:28,
                 from Marlin\src\MarlinCore.h:24,
                 from Marlin\src\MarlinCore.cpp:31:
Marlin\src\MarlinCore.cpp: In function 'void setup()':
Marlin\src\MarlinCore.cpp:1431:47: error: 'home_offset' was not declared in this scope; did you mean 'hotend_offset'?
 1431 |   TERN_(HAS_M206_COMMAND, current_position += home_offset); // Init current position based on home_offset
      |                                               ^~~~~~~~~~~
Marlin\src\inc/../core/macros.h:627:26: note: in definition of macro 'THIRD'
  627 | #define THIRD(a,b,c,...) c
      |                          ^
Marlin\src\inc/../core/macros.h:247:29: note: in expansion of macro '___TERN'
  247 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
      |                             ^~~~~~~
Marlin\src\inc/../core/macros.h:246:29: note: in expansion of macro '__TERN'
  246 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
      |                             ^~~~~~
Marlin\src\inc/../core/macros.h:245:29: note: in expansion of macro '_TERN'
  245 | #define TERN_(O,A)          _TERN(_ENA_1(O),,A)     // OPTION ? 'A' : '<nul>'
      |                             ^~~~~
Marlin\src\MarlinCore.cpp:1431:3: note: in expansion of macro 'TERN_'
 1431 |   TERN_(HAS_M206_COMMAND, current_position += home_offset); // Init current position based on home_offset
 ```
