### ISSUE TITLE
my x&y stepper motors aren’t working 

### ISSUE THREAD

**Issue by waw666** [MarlinFirmware/Marlin#25724]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

x&y Smotors 
my x&y stepper motors aren’t working at all but my Z axis motors are working fine 
how should i fix this problem?
i'm sure about my wiring and steppers are fine
[Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/11297442/Marlin-bugfix-2.0.x.zip)

### Version of Marlin Firmware

2.0 bugfixe

### Printer model

home made

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/Marlin/files/11297427/Marlin-bugfix-2.0.x.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
