### ISSUE TITLE
[BUG] Unable to build the latest Bugfix 2.1.x for Anet ET5X/ET4 board

### ISSUE THREAD

**Issue by darcyb** [MarlinFirmware/Marlin#25729]
This bug report was made in error.

**Comment by ellensp** [comment]
Provided config is for a ramps

**Comment by ellensp** [comment]
current bugfix 2.1.x with https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Anet/ET4  compiles without issues as does https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Anet/ET5X

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by darcyb** [comment]
Sorry. I uploaded the wrong config. Thank you, I'll check my work.
