### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by Divakar5225** [MarlinFirmware/Marlin#25749]
### Is your feature request related to a problem? Please describe.

Hi, i am upgrading my custom FDM printer for that i want to add sensor for detecting the chamber temperature. I am using MKS GEN l board, i am unable to find the HEATER_CHAMBER_PIN, so can you help me out or 
any other solutions for detecting chamber temperature without connecting chamber heater

### Describe the feature you want

I want display the chamber temperature, without connecting heater

**Comment by DerAndere1** [comment]
Support forums like the Marlin community on discord.com could not help with this? 

Configuration.h has this setting:   
```
#define TEMP_SENSOR_CHAMBER 0
```

Configuration_adv.h has
```
//#define HEATER_CHAMBER_PIN      P2_04   // Required heater on/off pin (example: SKR 1.4 Turbo HE1 plug)
```
Try playing around with these settings. Enable them, assign different values (for the latter, assign a free pin or try value -1).

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
