### ISSUE TITLE
How 2 5 Extruder 3 with Cold and 2 is with colour mixing and temperature. 

### ISSUE THREAD

**Issue by go2sid** [MarlinFirmware/Marlin#25744]
### Is your feature request related to a problem? Please describe.

I am looking to configure total 5 extruders E0 to E4. 3 extruders will work in Cold and 2 will work in temperature controlled, this two extruders will be sharing same nozzle. 

1. I compiled marlin by disabling prevent cold extrusion and Mintemp 0. it works, but when I add 5 extruder to config.h it gives error of no heater pins and temp sensor pins found. how can I disable this ? because  I think  i don't have 10 extra pins. perhaps I can assign CS pins or diagnostic pins of expansion shield, neopixel tec pins heated bed and thermistor pins ? 

2. I had tried to compile marlin using single extruder option to test the hardware. Extruder E1 doesn't work and giving command to  E3 and E4 spins the same motor of E3, how can I solve this issue ? 

3. If using multiple extruders how to define nozzle config , because there are 4 nozzles which had offset and 5 extruders. How Can I run two extruders simultaneously  in this config ? 

### Are you looking for hardware support?

I have btt skr v1.4 with motor expansion shield which supports total 8 drivers using EXp1 and EXp2 drivers. I am planning to use TFT  screen. I can purchase new octopus board if this is not supported. 

### Describe the feature you want

I am looking to configure total 5 extruders E0 to E4. 3 extruders will work in Cold and 2 will work in temperature controlled, this two extruders will be sharing same nozzle.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
