### ISSUE TITLE
[BUG] Weird problem when changing fan speed and random board resets

### ISSUE THREAD

**Issue by leftbrasil** [MarlinFirmware/Marlin#25757]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I built Marlin using configs for neptune 2 (files attached) using the bugfix branch and I'm having some issues. When i try to change the fan speed, the board seems to freeze for a few seconds and the moving axis keeps moving undefinedly  until this freeze resumes. I have also noticed that if i use the slider to change the cooling fan speed, the board freezes a lot. Last time i used a version from December and I have never had issues.

The error shown:

Error:SD read error
[ERROR] Error:SD read error

I have checked the sd card and it's perfectly fine. Even deleted all partitions and reformatted

I have a spare identical board and I have tested on two boards, same problem.
Any idea on what's happening ?

Thanks!

### Bug Timeline

Last time I used a version was on December and everything was working fine

### Expected behavior

Stop weird random freezes when changing the fan speed and also the board resets.

### Steps to Reproduce

Start a print, change the fan speed using the slider and the 'plus and minus' icons.

### Version of Marlin Firmware

Marlin bugfix-2.1.x (Apr 27 2023 11:47:42) 

### Printer model

Neptune 2

### Electronics

ZNP Robin Nano v1.3

### Add-ons

bltouch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/11360045/Config.zip)
[Gcode.zip](https://github.com/MarlinFirmware/Marlin/files/11360046/Gcode.zip)
[M11 S247 - last errors.txt](https://github.com/MarlinFirmware/Marlin/files/11360055/M11.S247.-.last.errors.txt)

**Comment by rondlh** [comment]
I had a similar issue with the MKS Monster8 V1.0 board (STM32F4xx), which turned out to be a timer conflict, I solved it by changing TIMER_SERIAL to TIM4, it was TIM5 previously.
