### ISSUE TITLE
[BUG] Cant PID autotune with more than one servo

### ISSUE THREAD

**Issue by andrewhawn** [MarlinFirmware/Marlin#25765]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have a BLtouch and I recently setup a second servo to act a hotend switcher. Everything has worked until I tried to do a PID autotune for either of the hotends or bed. When I try to autotune the hotend or bed  will not heat up at all and stays at room temperature. While autotune is attempting to work the servo twitches back and forth constantly until the printer times out. I can still heat the nozzle and bed manually and print, just cant use M303 in any way. When I disable #define SWITCHING_NOZZLE, PID autotune works again.

### Bug Timeline

Started after enabling switching nozzle with a servo

### Expected behavior

I expect PID autotune to still function

### Actual behavior

PID autotune fails to heat either hotend or the bed and eventually times out

### Steps to Reproduce

Run M303 with parameters all set, nothing heats up, and printer times out and calls a kill.

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Custom

### Electronics

BTT Octopus

### Bed Leveling

ABL Linear grid

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11366491/Configuration.zip)

**Comment by ellensp** [comment]
please attach modified pins.h file 
need to know where you have SERVO1_PIN and any other changes

**Comment by andrewhawn** [comment]
Here are my pin definitions

[pins_BTT_OCTOPUS_V1_common.zip](https://github.com/MarlinFirmware/Marlin/files/11374946/pins_BTT_OCTOPUS_V1_common.zip)

**Comment by andrewhawn** [comment]
Also to note, sometimes when starting a print, while the bed is heating the servo will twitch back and forth between its current setting and about 90 degrees. Once the print starts it works without a fault
