### ISSUE TITLE
Problem with building with "auto build marlin"

### ISSUE THREAD

**Issue by Al3xDARS** [MarlinFirmware/Marlin#25789]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When clicking build the following commands pop up and every time the same error comes up.

No matter the version of marlin or cofig folder.

PS C:\Users\Fucking Good\Documents\Arduino\_Marlin\Marlin> platformio run --silent -e STM32F103RE_creality
Error: Could not find one of 'package.json' manifest files in the package
PS C:\Users\Fucking Good\Documents\Arduino\_Marlin\Marlin> echo "done" >"C:\Users\FUCKIN~1\AppData\Local\Temp\ipc"

PS: Yes my Desktop name is "Fucking Good".

### Steps to Reproduce

Following steps from various videos on how to upload the marlin firmware onto the Creality Silent Motherboard V4.2.7 this same error appears

### Version of Marlin Firmware

MArlin 2.0.X

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
Issue with platfromio, not marlin,

delete .platformio directory in you home directory and restart vscode. give it time to reinstall. it has to get a lots of data from the internet.

Also put marlin somewhere else. platformio doesn't like spaces in the path

**Comment by Ale3xDARS** [comment]
It appears I do not understand what you are trying to say...

**Comment by Al3xDARS** [comment]
> Issue with platfromio, not marlin,
> 
> delete .platformio directory in you home directory and restart vscode. give it time to reinstall. it has to get a lots of data from the internet.
> 
> Also put marlin somewhere else. platformio doesn't like spaces in the path

It appears I do not understand what you are trying to say...

**Comment by Al3xDARS** [comment]
As I am new to all this, would it be OK with anyone willing to help me via discord or any other way??

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
