### ISSUE TITLE
Dual Z motors, the REV setting only works on one side

### ISSUE THREAD

**Issue by colcolcheese** [MarlinFirmware/Marlin#25794]
### Bug Description

#define INVERT_Z_DIR false => Z&Z2=right rotation
#define INVERT_Z_DIR true => Z=left  rotation Z2=right rotation

### Version of Marlin Firmware

bugfix-2.1.x 

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11421699/Marlin.zip)

**Comment by ellensp** [comment]
actually  not so sure...   leaving open

**Comment by ellensp** [comment]
tested 

./buildroot/bin/opt_enable Z2_DRIVER_TYPE A4988
./buildroot/bin/opt_enable REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
./buildroot/bin/opt_set INVERT_Z_DIR true

good 4b4d98d282f2760e760b9f2ccca8dcc8831f7f8d
bad 3e9848f49c6565ea1c630c272e32e27b0858d85a

says commit d93aa0c38449bcbc38aeca7eac506297270546c8 introduced this issue.

but its not the whole story....

**Comment by thisiskeithb** [comment]
> says commit [d93aa0c](https://github.com/MarlinFirmware/Marlin/commit/d93aa0c38449bcbc38aeca7eac506297270546c8) introduced this issue.

That patch was pushed to fix the motion bug(s) reported in https://github.com/MarlinFirmware/Marlin/issues/25785

**Comment by ellensp** [comment]
Looking into the code, and getting rather confused, but I think I see the issue

The code is correct, but some defines are missing.

when #define INVERT_Z_DIR true 
then this should also be set 
#define INVERT_Z2_DIR true 
same with INVERT_Z3_DIR and INVERT_Z4_DIR for when you have 3 or 4 Z's
simply adding the line will fix the issue, but it should be done automatically 

I purpose the following, which fixes it in my testing 

```DIFF
diff --git a/Marlin/src/inc/Conditionals_adv.h b/Marlin/src/inc/Conditionals_adv.h
index 7ea12f0493..855218ab37 100644
--- a/Marlin/src/inc/Conditionals_adv.h
+++ b/Marlin/src/inc/Conditionals_adv.h
@@ -875,6 +875,18 @@
 #endif
 
 // Multiple Z steppers
+#ifdef INVERT_Z_DIR
+  #if NUM_Z_STEPPERS > 3
+    #define INVERT_Z4_DIR INVERT_Z_DIR
+  #endif
+  #if NUM_Z_STEPPERS > 2
+    #define INVERT_Z3_DIR INVERT_Z_DIR
+  #endif
+  #if NUM_Z_STEPPERS > 1
+    #define INVERT_Z2_DIR INVERT_Z_DIR
+  #endif
+#endif
+
 #if NUM_Z_STEPPERS < 4
   #undef INVERT_Z4_VS_Z_DIR
   #if NUM_Z_STEPPERS < 3
```

**Comment by ellensp** [comment]
@colcolcheese can you try this on your system?

If it also fixes your issue, ill turn it into a PR to fix it for all.

**Comment by colcolcheese** [comment]
The test was successful.
Thanks for responding.

**Comment by ellensp** [comment]
PR created, closing this as fixed. (as soon as its is committed)
