### ISSUE TITLE
[BUG] Can't get above 300C despite changing HEATER_MAX

### ISSUE THREAD

**Issue by Nova518** [MarlinFirmware/Marlin#25790]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

I am having trouble getting my printer above 300C. I have changed the HEATER_0_MAXTEMP values to 375. It allows me to set the hot end temp up to 350. The printer heats up as usual, but as soon as it hits 300 it errors and immediately stops. The menu on the printer is locked out and a warning takes up the entire screen saying "Nozzle is too higherature". This locks down the printer and it takes a full restart to restore function. It does not appear to be overshooting as it errors immediately when it hits 300. There are no temperature readings above 300C. It has no trouble reaching and maintaining a consistent 290.

I am also not able to run PID autotune at any temperature  at or above 300C. The printer does not even attempt to warm up, and I receive the error “PID autotune failed! Temperature too high” as soon as I put in the command. 

The printer has been running and printing fine at any temp below 300C.

### Bug Timeline

First installed Marlin 2.1.2 3 days ago

### Expected behavior

I expect it to reach and maintain 300C just as easily as it does 290C.

 I would only expect to see a temperature reading of at least 340 before seeing this error if it really was over temp. 

![temp](https://user-images.githubusercontent.com/112600302/236653225-d443f8cd-06be-4e97-be57-5511baad0cfb.png)

### Actual behavior

After sending command to change temp, or starting a print, it starts heating as usual. As soon as the temp reaches 300C the printer errors, locks down, and stops printing. A full restart is needed to try anything again. 

### Steps to Reproduce

1. Start print with a temp at or greater than 300C. Or set the printer temperature to 300C or more.
2. Printer will start heating as normal.
3. Watch printer error and lock down at 300C

### Version of Marlin Firmware

2.1.2

### Printer model

Creality Ender 3 V2

### Electronics

Stock 

### Add-ons

Spider 2.0 Hot End , Creality direct drive extruder, High temp thermistor

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/11413721/Configurations.zip)

**Comment by thisiskeithb** [comment]
You can’t exceed the thermistor table’s max temperature. Once you do, Marlin halts the machine.

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
