### ISSUE TITLE
[(Possible) BUG] ABL not compensating - E3 V3, Ender 2 Pro & Ender 3 Max

### ISSUE THREAD

**Issue by Jamesb4uk** [MarlinFirmware/Marlin#25795]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I've been running Marlin 2.1.2, with Bigtree Tech E3 V3's on both my Ender 3 Pro & Ender 3 Max. both with Creality CR Touch's.

Self compiled for both boards.

I've got Bilinear levelling configured & M420 S1 in my  start code (PrusaSlicer) after G28

     0      1      2      3      4      5
  0 -0.057 -0.052 -0.037 +0.005 +0.010 +0.030
  1 -0.097 -0.075 -0.047 +0.008 +0.013 +0.028
  2 -0.060 -0.042 -0.025 +0.020 +0.023 +0.060
  3 -0.040 -0.030 -0.035 +0.020 +0.020 +0.040
  4 -0.015 -0.030 -0.022 +0.018 +0.020 +0.028
  5 -0.017 -0.042 -0.042 -0.007 -0.017 -0.005
  
  Bed levelling seems to be ok & within tolerance but for the life of me ABL's just not compensating at all, Z axis doesn't compensate at all.

Hopefully attached logs are ok - this is from my Ender 2 Pro but my Ender 3 Max is the same issue & config bar bed size. 

[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/11422691/Configuration.h.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/11422693/Configuration_adv.txt)
[M503.txt](https://github.com/MarlinFirmware/Marlin/files/11422695/M503.txt)
[Connection log.txt](https://github.com/MarlinFirmware/Marlin/files/11422696/Connection.log.txt)
[Levelling debug.txt](https://github.com/MarlinFirmware/Marlin/files/11422754/Levelling.debug.txt)

Kind Regards
James

### Bug Timeline

A few weeks ago since upgrading to 2.1.2

### Expected behavior

ABL to compensate slight differences in bed 

### Actual behavior

no compensation & Z axis does not move apart from changing layer

### Steps to Reproduce

Power on printer
G28 home
G29 ABL sequence
M500 save to EEPROM
Send print to printer via octopi
Start print

### Version of Marlin Firmware

2.1.2

### Printer model

Creality Ender 2 Pro & Ender 3 Max

### Electronics

Bigtree Tech E3 V3, CR Touch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Changes to firmware to enable CR Touch & E3 v3 board.

**Comment by ellensp** [comment]
Your bed is almost flat 

from provided config 

one full step move 1.8 degrees 
Z is 400 step/mm
1/16 microsteps

largest move 0.097 * 400 * (360/(200 * 16))  =  4.365 degrees of rotation,     2.4 full steps
typical  move 0.030 * 400 * (360/(200 * 16))  = 1.35 degrees of rotation,    less that 1 full step. 


Unless you stick flags on your Z axis, you are very unlikely to see any movement unless you cross the worst parts of the bed.

**Comment by Jamesb4uk** [comment]
Hi ellensp,

Good idea on the flags, I've stuck a tape flag indicator at the top of the lead screw - whilst I print a full bed single layer test print. 

still zero z axis movement across the bed & I can definitely see & feel changes in the print where its not compensating

**Comment by brew99** [comment]
@Jamesb4uk Try your M420 S1 Z10.00 after the G29 command.  I recently had a similar issue and needed to have the M420 S1 after the G29, otherwise it wouldn't enable the Z compensation

**Comment by Jamesb4uk** [comment]
Hi @brew99 

I actually tried that having m420 to load the mesh - didn't seem to do much either

To be honest I gave up & installed Klipper

Kind regards
James
