### ISSUE TITLE
[BUG] Ender 5 Plus, DGUS UI (Print button not working, Info button going to Leveling)

### ISSUE THREAD

**Issue by GamingLPyt** [MarlinFirmware/Marlin#25817]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I am trying to update my Ender 5 Plus with Creality V2.2 Motherboard. I am using this DGUS UI [https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-5%20Plus/DGUS-Reloaded](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-5%20Plus/DGUS-Reloaded) and this Marlin Version (Firmware) [https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.1.x](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.1.x). Now if i am pressing the Print Button nothing shows up, also if i am going to Settings -> Info the Leveling Menu is shoing. Also if i am going to Leveling an clicking on Manually i cant press the Numbers. The Move Menu is also not working i cant move any Axes. 

### Bug Timeline

I dont know, i am trying to update it as the first time

### Steps to Reproduce

1. Build Marlin 2.1.x-bugfix with the Configuration of Ender 5 Plus, also download this UI and [https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-5%20Plus/DGUS-Reloaded](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-5%20Plus/DGUS-Reloaded) upload it to the Screen

2. Press any Buttons i wrote in the Bug Description

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Ender 5 Plus

### Electronics

Creality V2.2 Silent Motherboard

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/11467855/Configurations.zip)

**Comment by ellensp** [comment]
Provided attached config shows #define DGUS_LCD_UI ORIGIN, not #define DGUS_LCD_UI RELOADED
