### ISSUE TITLE
[BUG] extruder motor is shaking

### ISSUE THREAD

**Issue by gacek4000** [MarlinFirmware/Marlin#25828]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

the extruder motor is shaking instead of rotating.
I have SKR 1.4 board and TMC2209. I tried:
- swap the cable from another engine;
- replace the drivers;
- enable/disable LIN_ADV
- different speed and acceleration settings

Nothing helped, other motors and controllers work fine.

when I send the command G1 E5 F30 a few times, the error pops up:

Send: G1 E5 F300
Recv: ok
Send: M82
Recv: ok
Send: G90
Recv: ok
Recv:  T:23.25 /0.00 B:23.59 /0.00 @:0 B@:0
Recv: 
Recv: E driver error detected: 0xC00F0090
Recv: coil short circuit
Recv: 		X	Y	Z	E
Recv: Address		0	0	0	0
Recv: Enabled		false	false	false	true
Recv: Set current	800	800	800	800
Recv: RMS current	795	795	795	795
Recv: MAX current	1121	1121	1121	1121
Recv: Run current	25/31	25/31	25/31	25/31
Recv: Hold current	2/31	2/31	2/31	2/31
Recv: CS actual	2/31	2/31	2/31	14/31
Recv: PWM scale
Recv: vsense		1=.18	1=.18	1=.18	1=.18
Recv: stealthChop	true	true	true	true
Recv: msteps		64	64	64	64
Recv: interp		true	true	true	true
Recv: tstep		max	max	max	max
Recv: PWM thresh.
Recv: [mm/s]
Recv: OT prewarn	false	false	false	false
Recv: triggered
Recv:  OTP		false	false	false	false
Recv: pwm scale sum	3	3	3	111
Recv: pwm scale auto	0	0	0	0
Recv: pwm offset auto	36	36	36	255
Recv: pwm grad auto	14	14	14	14
Recv: off time	3	3	3	3
Recv: blank time	24	24	24	24
Recv: hysteresis
Recv:  -end		-1	-1	-1	-1
Recv:  -start		1	1	1	1
Recv: Stallguard thrs	0	0	0	0
Recv: uStep count	34	34	34	130
Recv: DRVSTATUS	X	Y	Z	E
Recv: sg_result	0	0	0	2
Recv: stst
Recv: olb					*
Recv: ola
Recv: s2gb
Recv: s2ga
Recv: otpw
Recv: ot
Recv: 157C
Recv: 150C
Recv: 143C
Recv: 120C
Recv: s2vsa					*
Recv: s2vsb
Recv: Driver registers:
Recv: 		X	0xC0:02:00:00
Recv: 		Y	0xC0:02:00:00
Recv: 		Z	0xC0:02:00:00
Recv: 		E	0xC0:09:00:90
Recv: 
Recv: 
Recv: echo:Driver error
Recv: Error:Printer halted. kill() called!
Changing monitoring state from "Operational" to "Error"
Send: M112
Send: N2 M112*35
Send: N3 M104 T0 S0*34
Send: N4 M140 S0*97
Changing monitoring state from "Error" to "Offline after error"
Connection closed, closing down monitor

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11472843/Marlin.zip)

### Bug Timeline

when i installed new motherboard and motor drivers

### Expected behavior

the extruder rotates

### Actual behavior

the extruder is shaking

### Version of Marlin Firmware

2.1.2 & latest bugfix

### Printer model

anycubic predator

### Electronics

SKR 1.4

### Add-ons

TMC2209

### Bed Leveling

None

### Your Slicer

None

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
