### ISSUE TITLE
Message text thermal runaway  Heater_ID wrong

### ISSUE THREAD

**Issue by RogerRepRap** [MarlinFirmware/Marlin#2582]
```
10:42:47.878 : Error:Thermal Runaway, system stopped! Heater_ID:
9
```

Runaway message has a problem. The message always reports heater id as "9" so there is no way to tell which heater had problem. This makes troubleshooting a very intermittent problem difficult. Not a showstopper. 

Keep up the good work.

Roger

**Comment by thinkyhead** [comment]
What version of Marlin are you using? The error message differs in the latest development code (no newline after "Heater_ID:").

**Comment by thinkyhead** [comment]
Apparently in Marlin 1.0.2 the number "9" indicates the bed.
We may patch this so that for "9" it prints the word "bed" instead.

**Comment by AnHardt** [comment]
https://github.com/MarlinFirmware/Marlin/blob/Release/Marlin/temperature.cpp#L566

**Comment by Wackerbarth** [comment]
Does this need to be ported to the development tree?

**Comment by AnHardt** [comment]
No, it's completely reworked there.
