### ISSUE TITLE
[BUG] Z_MIN_ENDSTOP_INVERTING

### ISSUE THREAD

**Issue by rdfry** [MarlinFirmware/Marlin#25844]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Compile Marlin and it fails

### Bug Timeline

new started with version 2.1.2

### Expected behavior

I expected it to Compile

### Actual behavior

In file included from Marlin\src\feature\bltouch.cpp:39:
Marlin\src\feature\bltouch.cpp: In static member function 'static bool BLTouch::triggered()':
Marlin\src\feature\../module/probe.h:49:49: error: 'Z_MIN_ENDSTOP_INVERTING' was not declared in this scope
   49 |   #define PROBE_TRIGGERED() (READ(Z_MIN_PIN) != Z_MIN_ENDSTOP_INVERTING)
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~
Marlin\src\feature\bltouch.cpp:96:36: note: in expansion of macro 'PROBE_TRIGGERED'
   96 | bool BLTouch::triggered() { return PROBE_TRIGGERED(); }
      |                                    ^~~~~~~~~~~~~~~
*** [.pio\build\BIGTREE_SKR_2\src\src\feature\bltouch.cpp.o] Error 1
=============================================================================================== [FAILED] Took 42.64 seconds ===============================================================================================

### Version of Marlin Firmware

2.12

### Printer model

Anet AM8

### Electronics

BTT SKR 2.0

### Add-ons

Filament Runout Sensor

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11501948/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/11501951/Configuration_adv.zip)
[bltouch.zip](https://github.com/MarlinFirmware/Marlin/files/11501953/bltouch.zip)
[probe.zip](https://github.com/MarlinFirmware/Marlin/files/11501954/probe.zip)

**Comment by thisiskeithb** [comment]
> Did you test the latest bugfix-2.1.x code?
> Yes, and the problem still exists.

You couldn't have tested the current bugfix since `Z_MIN_ENDSTOP_INVERTING` was removed and replaced by `Z_MIN_ENDSTOP_HIT_STATE` HIGH/LOW two months ago:

https://github.com/MarlinFirmware/Marlin/blob/3b2341fb6127f51dd6b150ea49297b60c364d865/Marlin/src/module/probe.h#L51

**Comment by rdfry** [comment]
I am using the Latest Version Which has Z_MN_ENDSTOP_HIT_STATE and no longer has  Z_MIN_ENDSTOP_INVERTING in configuration.h  I  took marlin 2.12 and used the rep rap config files that are part of the marlin code and modified them for the Anet A8. that is why i cant figure out why i am getting a reference to code that no longer exists in this version

**Comment by thisiskeithb** [comment]
> I am using the Latest Version Which has Z_MN_ENDSTOP_HIT_STATE and no longer has Z_MIN_ENDSTOP_INVERTING in configuration.h I took marlin 2.12 and used the rep rap config files that are part of the marlin code 

You can't mix & match versions of Marlin & configs.

[Marlin `2.1.2.1` download](https://github.com/MarlinFirmware/Marlin/archive/refs/tags/2.1.2.1.zip) + [Marlin `2.1.2.1` configs](https://github.com/MarlinFirmware/Configurations/archive/refs/heads/release-2.1.2.1.zip)

[Marlin `bugfix-2.1.x` download](https://github.com/MarlinFirmware/Marlin/archive/refs/heads/bugfix-2.1.x.zip) + [Marlin `bugfix-2.1.x` configs](https://github.com/MarlinFirmware/Configurations/archive/refs/heads/bugfix-2.1.x.zip)

**Comment by rdfry** [comment]
i am using the config files that come with the Marlin Code. the only things being changed are the drivers the processor the lcd and the bed size. and definitions needed for BLTOUCH using it for probing and as an endstop. the config files are the ones that are set up for REPRAP printers and i am only changing what i need for an anet a8.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Comment by rdfry** [comment]
thanks for your help i appreciate it. unfortunately this was a last resort as no one is willing to provide a meaningful solution on other Marlin Help Sites. this issue should not be happening as i am not using any older versions of configurations

**Comment by thisiskeithb** [comment]
> I took marlin 2.12 and used the rep rap config files

Your `CONFIGURATION_H_VERSION` & `CONFIGURATION_ADV_H_VERSION` are `02010300` which do not work in Marlin versions `2.1.2` (`02010200`) or `2.1.2.1` (`02010201`) and will only work with current `bugfix-2.1.x`.

Again, you can't mix & match version of Marlin & configs.

Use the download links [I posted in my previous comment](https://github.com/MarlinFirmware/Marlin/issues/25844#issuecomment-1552232998) (be sure to pay special attention to versions of Marlin & configs as they must match) and please [use the support links in my other previous comment](https://github.com/MarlinFirmware/Marlin/issues/25844#issuecomment-1552245162) for further config troubleshooting.
