### ISSUE TITLE
BL Touch echo:home first [BUG] (bug summary)

### ISSUE THREAD

**Issue by fiveorders** [MarlinFirmware/Marlin#25842]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have tried nightly builds as well but all the same. 

QGL Core XY and there is nothing wrong with the genuine BL TOuch sensor or end stops. G34 Z_Alignment works fine. But when I try to mesh bed levelling, it homes and says home first on the screen

### Bug Timeline

It started after 2.0.9

### Expected behaviour

It should do the 3x3 bilinear mesh bed levelling.

### Actual behaviour

Homes and says Home First

### Steps to Reproduce

G29

### Version of Marlin Firmware

2.1.2

### Printer model

QGL Core XY

### Electronics

Octopus Pro v1.0 

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/11497576/Archive.zip)

_No response_

**Comment by ellensp** [comment]
#define NOZZLE_TO_PROBE_OFFSET { 0, 49, 0, 2}  
You probing inside a hypercube or some other > 3 dimensional reality.

**Comment by ellensp** [comment]
Provided config does not compile.

**Comment by fiveorders** [comment]
yes because it is a 4 axis machine. probably you get error on sanity check right? just disable that on sanity.h it will compile. but this error has nothing to do with that because it is working on 2.0.9

**Comment by fiveorders** [comment]
The problem is about the 4th axis, and the disabled end stops. I couldn't figure out how to fix yet but closing this
