### ISSUE TITLE
[FR] (Add an optional message to M400)

### ISSUE THREAD

**Issue by jkuusama** [MarlinFirmware/Marlin#25851]
### Is your feature request related to a problem? Please describe.

No

### Are you looking for hardware support?

No

### Describe the feature you want

Add lines
```
  if (parser.string_arg) {
    SERIAL_ECHOLN(parser.string_arg);
  }
```
to M400.cpp. This allows optional message string attached to M400 command. Works like this:
```
m400
ok
m400 ready
ready

ok
```

### Additional context

This greatly simplifies custom control software for machines that do real-time control. For example, my pick and place machine uses machine vision to component recognition, position calibration etc, generating G-code commands on the fly. Only when the machine has reached position, it takes a picture and analyses it. Having the message after M400, the control software doesn't need to keep track of ok's; it is enough to scan received lines for the sting added to the M400 command. I can think of other similar cases.

(Ok, trivial for anyone that is compiling the code to add by themselves - but not all users are. Also so trivial that I considered a full pull request an overkill.)

**Comment by DerAndere1** [comment]
Would it work for you to use M118 after M400?

**Comment by jkuusama** [comment]
Doh. I missed that code when reading codes about capabilities (I wonder what other useful codes I missed…). Of course  that works.
