### ISSUE TITLE
PROBE_SIZE_X/PROBE_SIZE_Y depend on PROBE_OFFSET_FROM_EXTRUDER

### ISSUE THREAD

**Issue by maisonobe** [MarlinFirmware/Marlin#2586]
Hi,

Attempting to use auto bed leveling on a 3DR with an inductive sensor I encountered some limitations if I attempt to use a moderate number of points for the grid size. My printer has a DELTA_PRINTABLE_RADIUS of 90mm, and the probe is 20mm to the front and 9mm to the right of the of the main extruder nozzle (I have a 2 extruders setup, so the two nozzles and the probe are located in a triangular configuration).

I tried to set AUTO_BED_LEVELING_GRID_POINTS to 9 (i.e. an 81 points grid before clipping the corners wrt circle) but compilation failed with an error :

```
SanityCheck.h:195:10: error: #error The Y axis probing range is too small to fit all the points defined in AUTO_BED_LEVELING_GRID_POINTS
```

After some code reading and manual macro evaluations, I think the limit I hit was due to the following definition in SanityCheck.h:

```
#define PROBE_SIZE_Y (Y_PROBE_OFFSET_FROM_EXTRUDER * (AUTO_BED_LEVELING_GRID_POINTS-1))
```

This means to me that the grid spacing  along the Y direction in SanityCheck is considered to be equal to Y_PROBE_OFFSET_FROM_EXTRUDER. The same is true along the X direction. It seems rather strange to me, there is no reason the offset should be the grid spacing. In fact, in other places in the code (Marlin_main.cpp, function gcode_G29 in the ENABLE_AUTO_BED_LEVELING case), one can read:

```
yGridSpacing = (back_probe_bed_position - front_probe_bed_position) / (auto_bed_leveling_grid_points - 1)
```

so the grid spacing is defined from the limits and the number of points, whereas SanityChecks seems to fix the grid spacing to the offset values, and then to deduce the limits from it.

I would expect that increasing the number of points simply changes the grid spacing (just as done in Marlin_main.cpp gcode_G29) and the SanityChecks would check that this value is larger than MIN_PROBE_EDGE. As there seems to be limitations in the computations the preprocessor can do (integers only I guess), this may be tricky. In any case, the current sanity checks is not well suited for probes that have a significant offset from the extruder.

**Comment by AnHardt** [comment]
That particular SanityCheck test was removed in `Development` a while ago exactly because of the problem you cite. Fixed.

[edited]
