### ISSUE TITLE
Support for reverse x-axis direction of H-bot is needed.

### ISSUE THREAD

**Issue by DWONH** [MarlinFirmware/Marlin#2587]
Unlike corexy, direction of X-axis in H-bot can be reversed depends on position of belt clamp.
And it can not be configured by any of existing variables.(rel 1.0.2)
Like depicted in photo below, setup#1 is general configuration and is supported in current release version. But for setup#2, current code moves head reverse direction which is not desired.

Motion equation should be changed for setup#2, as seen in picture.

![hbot-xaxis-directions](https://cloud.githubusercontent.com/assets/13655997/9081538/fe9085e0-3b97-11e5-968b-090be116c675.png)

It would be nice if we have option for this in configuration.h.

**Comment by Wackerbarth** [comment]
Yes, this is a kinematics feature that we need to add.
@boelle -- Can you move this to MarlinDev?   (And tell me how to use the tool so I can move individual items such as this myself)

This request will be closed here and reopened in the MarlinDev repository.

**Comment by whosawhatsis** [comment]
Can't you reverse it in hardware by swapping the two motor cables (so that in this diagram, A would be on the right and B would be on the left) and reversing both motor cable connectors to reverse the motor directions?

**Comment by grob6000** [comment]
That was my thought. The equations bear it out: notice that equations for dA(2) = -dB(1) and dB(2) = -dA(1).

**Comment by thinkyhead** [comment]
@whosawhatsis Hardware solution FTW! But I suppose we can still add an option here for people who prefer to have their cable plugs all face the same way and have the same color-order.

**Comment by Wackerbarth** [comment]
@thinkyhead -- If you go to corresponding item  (https://github.com/MarlinFirmware/MarlinDev/pull/55) in MarlinDev, you will find that we were able to fix this totally in the pin definitions and configuration. Basically, it is a HAL layer issue and requires no additional code.
