### ISSUE TITLE
Marlin fails to compile when UBL_HILBERT_CURVE is enabled

### ISSUE THREAD

**Issue by PanosPetrou** [MarlinFirmware/Marlin#25870]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When enabling #define UBL_HILBERT_CURVE in Unified Bed Leveling, Marlin can't be compiled.
It throws an "Marlin/src/feature/bedlevel/hilbert_curve.cpp:31:71: error: call of overloaded 'log2(int)' is ambiguous" error.

### Expected behavior

Marlin should compile without errors.

### Steps to Reproduce

1. enable #define UBL_HILBERT_CURVE
2. Try to compile Marlin

### Version of Marlin Firmware

Latest bugfix 2.1.x

### Printer model

Homemade, based of the aluminum frame of Geeetech A10M

### Electronics

MKS TinyBee board, MKS SERVO42C steppers on X and Y axes, dual extruder setup

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/11536607/configs.zip)

**Comment by ellensp** [comment]
Provided config is not current bugfix
Provided config does not compile due to missing FIL_RUNOUT_PIN
Provided config doesn't have UBL_HILBERT_CURVE enabled.

Provided config should trigger the issue.....

But after upgrading config to bugfix and allocating a random io pin to FIL_RUNOUT_PIN and enabling UBL_HILBERT_CURVE

I can reproduce this error.

**Comment by ellensp** [comment]
quick fix 

```DIFF
--- a/Marlin/src/feature/bedlevel/hilbert_curve.cpp
+++ b/Marlin/src/feature/bedlevel/hilbert_curve.cpp
@@ -28,8 +28,8 @@
 
 constexpr int8_t  to_fix(int8_t  v) { return v * 2; }
 constexpr int8_t  to_int(int8_t  v) { return v / 2; }
-constexpr uint8_t   log2(uint8_t n) { return (n > 1) ? 1 + log2(n >> 1) : 0; }
-constexpr uint8_t  order(uint8_t n) { return uint8_t(log2(n - 1)) + 1; }
+constexpr uint8_t   log2(uint8_t n) { return (n > 1) ? 1 + log2(uint8_t (n >> 1)) : 0; }
+constexpr uint8_t  order(uint8_t n) { return uint8_t(log2(uint8_t (n - 1))) + 1; }
 constexpr uint8_t ord = order(_MAX(GRID_MAX_POINTS_X, GRID_MAX_POINTS_Y));
 constexpr uint8_t dim = _BV(ord);

```

**Comment by ellensp** [comment]
Minimal changes to stock config required to trigger issue.

#define MOTHERBOARD BOARD_MKS_TINYBEE
#define FIX_MOUNTED_PROBE
#define AUTO_BED_LEVELING_UBL
#define UBL_HILBERT_CURVE 
#define Z_SAFE_HOMING
#define EEPROM_SETTINGS

**Comment by PanosPetrou** [comment]
Thanks for the solution.
FIL_RUNOUT_PIN is defined in pins_MKS_TINYBEE.h. The config files are about a month old.
Is there any way to apply the config settings quickly, when a new Marlin version comes out? So far I'm editing Configuration.h & Configuration_adv.h manually which takes some time.

**Comment by ellensp** [comment]
A pr has been created to fix this

You use a Diff program to compare you old config to the new
There is one in vscode/platformio is you using git to download marlin.
