### ISSUE TITLE
[BUG] BTT Octopus Pro V1.1 - TMC Communication Error?

### ISSUE THREAD

**Issue by dcwalmsley** [MarlinFirmware/Marlin#25877]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Recently I swapped control boards to a BTT Octopus Pro V1.1 and installed all the same drivers (TMC2209) onto the board.  After installing the 2.0.9.3 bugfix, I started seeing error message for X Driver and Z4 Driver.  
Unclear what is wrong but would appreciate it if someone could identify what I am doing wrong or if this is a bug issue.

SENDING:M122
		X	Y	Z	Z2	Z3	Z4
Address		0	0	0	0	0	0
Enabled		false	false	false	false	false	false
Set current	800	800	1200	1200	1200	1200
RMS current	1436	795	1182	1182	1182	1182
MAX current	2025	1121	1667	1667	1667	1667
Run current	25/31	25/31	27/31	27/31	27/31	27/31
Hold current	12/31	12/31	13/31	13/31	13/31	13/31
CS actual	0/31	12/31	13/31	13/31	13/31	0/31
PWM scale
vsense		0=.325	1=.18	0=.325	0=.325	0=.325	0=.325
stealthChop	false	true	true	true	true	false
msteps		256	16	16	16	16	256
interp		false	true	true	true	true	false
tstep		0	max	max	max	max	0
PWM thresh.
[mm/s]
OT prewarn	false	false	false	false	false	false
triggered
 OTP		false	false	false	false	false	false
pwm scale sum	0	12	27	30	30	0
pwm scale auto	0	0	0	0	1	0
pwm offset auto	0	30	62	69	67	0
pwm grad auto	0	16	37	38	38	0
off time	0	4	4	4	4	0
blank time	16	24	24	24	24	16
hysteresis
 -end		-3	2	2	2	2	-3
 -start		1	1	1	1	1	1
Stallguard thrs	0	0	0	0	0	0
uStep count	0	344	360	360	360	0
DRVSTATUS	X	Y	Z	Z2	Z3	Z4
sg_result	0	186	200	196	198	0
stst		*					*
olb
ola
s2gb
s2ga
otpw
ot
157C
150C
143C
120C
s2vsa
s2vsb
Driver registers:
		X	0x00:00:00:00	 Bad response!
		Y	0xC0:0C:00:00
		Z	0xC0:0D:00:00
		Z2	0xC0:0D:00:00
		Z3	0xC0:0D:00:00
		Z4	0x00:00:00:00	 Bad response!
Testing X connection... Error: All LOW
Testing Y connection... OK
Testing Z connection... OK
Testing Z2 connection... OK
Testing Z3 connection... OK
Testing Z4 connection... Error: All LOW
//action:notification TMC CONNECTION ERROR

[BTT_Octopus_Pro_V1-1_4Z-Drives.zip](https://github.com/MarlinFirmware/Marlin/files/11557760/BTT_Octopus_Pro_V1-1_4Z-Drives.zip)

### Version of Marlin Firmware

2.0.9.3

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by vfbank** [comment]
Please update the firmware to 2.1.x. There is a major update to the TMC driver.

**Comment by Blackcatswiskas** [comment]
Hi I am having the same kind of issue I have used 2.1.2.1 and tried latest bugfix.  I have tried allsorts even deleting everything and starting again.  My Errors are on the Z2 bad connection All Low.  I have an Octopus 1.1 with TFT 35 V E3.01 and TMC2209 Stepper motors dual Z steppers 

[Octopus 1.1.zip](https://github.com/MarlinFirmware/Marlin/files/12136863/Octopus.1.1.zip)
