### ISSUE TITLE
Unable to home z axis with klicky probe

### ISSUE THREAD

**Issue by enddDD** [MarlinFirmware/Marlin#25878]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi, im using mks tinybee on a diy corexy printer, im using the stealthburner as toolhead and klicky probe to home z and autolevel the bed. Im using marlin 2.1.2 and have odd problems. I cant home the z, it does this, when pressing home z it goes to the dock, picks up the probe, get out of the dock and then simply stops and do nothing. From this point it should go to the center of the bed and do the homing but it doesnt, it just stops. I noticed that deploy probe from the lcd it works, it picks up the probe, but when pressing stowe probe button on lcd  it does nothing. I dont understand why i cant home the z because, sometimes i home it and it works. It can have something to do with eeprom, sdcard, or with changing settings like esteps. I dont understand why sometimes it works and sometimes it doesnt, i checked wiring and seems to be ok. I also noticed that when g28 from cura start gcode ,never worked, so i had to delete the g28 line in the startcode, i managed to home it once and do a flow test cube but now again i am unable to home z axis. Any help please, im struggling with this for weeks now and dont have the answer. Thanks!

### Expected behavior

Expected to home

### Actual behavior

Not homing z axis

### Version of Marlin Firmware

Marlin 2.1.2

### Printer model

Diy corexy with 2 z, fixed gantry

### Electronics

Mks tinybee, mks mini12864, tcm2209, 24v 20a power.

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configfiles.zip](https://github.com/MarlinFirmware/Marlin/files/11563057/Configfiles.zip)

**Comment by ellensp** [comment]
Did you actually test bugfix-2.1.x?  

my guess would be that your physically are not getting good electrical connection to the kicky switch.  Most endstops are configured so that when they are open (ie unplugged) they are triggered. So it thinks its already at z home

check your magnets are clean (no glue, finger grease or what ever on contacting surfaces) and that they protrude from the plastic and are level.so that they have good contact  

deploy klicky, send the printer M119 verify Z endstop status is open, then hold switch closed and send a  new M119 Z should show Triggered

**Comment by enddDD** [comment]
> Did you actually test bugfix-2.1.x?
> 
> my guess would be that your physically are not getting good electrical connection to the kicky switch. Most endstops are configured so that when they are open (ie unplugged) they are triggered. So it thinks its already at z home
> 
> check your magnets are clean (no glue, finger grease or what ever on contacting surfaces) and that they protrude from the plastic and are level.so that they have good contact
> 
> deploy klicky, send the printer M119 verify Z endstop status is open, then hold switch closed and send a new M119 Z should show Triggered

Well, i open up my stealthburner and actually s wire from klicky have connection problem with the magnet. I will redo the klicky and will see then. I hope that was the issue and i can close this. Thanks!
