### ISSUE TITLE
[FR] increase maximum edit value for "E Limit in mm3"

### ISSUE THREAD

**Issue by Tupson444** [MarlinFirmware/Marlin#25881]
### Describe the feature you want

Currently when VOLUMETRIC_EXTRUDER_LIMIT is used, the maximum edit value is 20 mm^3/s. Now there are many machines that can achieve much higher flow than that (e.g. with BondTech CHT nozzle), so this limit should be increased.

### Additional context

I have solved it for myself by editing "menu_advanced.cpp": I changed "20.0f" to "50.0f" in lines 123 and 126.
and "M200-M205.cpp": change number "20" to "50" in lines 67 and 70.
(Marlin 2.1.2)

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Marlin/pull/25884
