### ISSUE TITLE
How can I make a thermistor table?

### ISSUE THREAD

**Issue by adeebshihadeh** [MarlinFirmware/Marlin#2589]
I want to make a table for this [thermistor](http://reprap.org/wiki/Thermistor#EPCOS_100K_Thermistor_.28B57560G1104F.29). Do I simply designate a new number in thermistortables.h and copy the table from the wiki article I linked to?

**Comment by AnHardt** [comment]
Yes.
But for Marlin you have to add "*OVERSAMPLENR" in the first column of every line. Take a look at the other tables!

**Comment by adeebshihadeh** [comment]
Thanks.
