### ISSUE TITLE
[BUG] Marlin 2.1 skip steps - 2.0 stopped working

### ISSUE THREAD

**Issue by alx3dev** [MarlinFirmware/Marlin#25909]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Last install was Marlin 2.0.9.3 and everything worked fine. I didn't used my Ender3 some time, then I installed 2.1 and noticed skipping steps a lot. Also laser inline mode not work for me unless I add `Sx`, which also worked with 2.0.

Now I tried 2.0.9.3 version again, same as before and also downloaded new again, steppers won't move. I took all components from ender3 to test on another printer with DIY board, everything work as expected. I use default ender3 motors, but also tried with new 0.9 steppers, no difference.

I tried with ender3 default configuration, also with my own edition too, nothing changed. Also removed all folders inside `.platiformio/platforms` (linux system), nothing changed. Any help is more than appreciated.

Compiled with Auto-Build Marlin.

### Bug Timeline

Started two weeks ago, since then I am trying to fix it. Everything started when I moved to `2.1.1`, after that `2.0.9.3` not work.

### Expected behavior

Expected to move steppers with `2.0` version, or without missing steps in `2.1`.

### Actual behavior

In `2.0.9.3` version motors not move at all, they started enabled, when I move them nothing happen, just become disabled.
In `2.1.1` version motors skip steps a lot, and that never happened (using lightweight laser with 10 mm/s speed).

### Steps to Reproduce

Default configuration for Ender3, or my included config for 0.9 degrees motors
Moving motors in `version 2.0.9.3`
Printing or laser engraving any file in `version 2.1.1`

### Version of Marlin Firmware

2.1.1

### Printer model

Creality Ender-3

### Electronics

board v4.2.2

### Add-ons

Using laser on BL-Touch pins, same behavior without laser too.

### Bed Leveling

Z-stop switch as ABL (bilinear), behavior same if used as default (no abl).

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin-2.1.1.zip](https://github.com/MarlinFirmware/Marlin/files/11626212/Marlin-2.1.1.zip)
[Marlin-2.0.9.3.zip](https://github.com/MarlinFirmware/Marlin/files/11626213/Marlin-2.0.9.3.zip)

**Comment by alx3dev** [comment]
Edit: Added configuration files for both versions.

**Comment by ellensp** [comment]
This is what happens is you think you have a v4.2.2, but you really have a v4.2.7 motherboard. The only difference is the step and direction io lines are swapped over, so the stepper will not move when you use the wrong one.

Physically verify you have a 4.2.2 motherbaord

**Comment by alx3dev** [comment]
@ellensp it is v4.2.2, with C letter on SD slot (HR4988). Still can't understand how same binary not work anymore (renamed when copied to SD, eeprom restored...)

With `2.1.1` axis don't loose steps when run single X or Y. When together, they miss a lot.

**Comment by alx3dev** [comment]
Does anyone have any idea why is not possible to use older firmware after 2.1 version?
