### ISSUE TITLE
[BUG] (Ender 5 S1 M936  bad reference)

### ISSUE THREAD

**Issue by IzzyBella555** [MarlinFirmware/Marlin#25911]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The file for Ender 5 S1's update gcode (Marlin\src\gcode\ota\M936.cpp) makes a reference to a folder and file that do not exist:
```
#if ENABLED(CREALITY_RTS)
  #include "../../lcd/rts/lcd_rts.h"
#endif
```

The config file does define CREALITY_RTS, so this if statement evaluates to true.
[Configuration files.zip](https://github.com/MarlinFirmware/Marlin/files/11627970/Configuration.files.zip)

### Bug Timeline

I haven't successfully compiled custom Ender 5 S1 firmware yet

### Expected behavior

Expected to find the file path Marlin/src/lcd/rts/lcd_rts.h

### Actual behavior

No such file path exists

### Version of Marlin Firmware

Creality firmware version 1.0.7

### Printer model

Ender 5 S1

### Electronics

Stock

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
This printer / UI / LCD is not supported yet, so the referenced code is not in Marlin. See https://github.com/MarlinFirmware/Marlin/pull/25382
