### ISSUE TITLE
[BUG] (Please select only one LCD controller option.)

### ISSUE THREAD

**Issue by mrcamarium** [MarlinFirmware/Marlin#25916]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Impostazioni Per La Macchina
#define CUSTOM_MACHINE_NAME "Leo C8"                                   //Nome stampante
#define DEFAULT_MAX_ACCELERATION      { 1000, 1000, 100, 5000 }        //Massima Accelerazione
#define DEFAULT_TRAVEL_ACCELERATION   400                              //Massima Velocità di spostamento
#define XY_PROBE_SPEED (100*100) o #define XY_PROBE_FEEDRATE (100*100) //Velocità di spostamento dell'ugello
#define MULTIPLE_PROBING 2                                             //Abilitare le sonde
#define PREHEAT_1_TEMP_HOTEND 205                                      //Valore di preriscaldamento del HOTEND PLA
#define PREHEAT_1_TEMP_BED     25                                      //Valore di preriscaldamento del BED PLA
#define PREHEAT_2_TEMP_HOTEND 240                                      //Valore di preriscaldamento del HOTEND ABS
#define PREHEAT_2_TEMP_BED     25                                      //Valore di preriscaldamento del BED ABS
#define PRINTCOUNTER                                                   //Abilitandolo si evita di salvare le modifiche nella eeprom
#define LCD_LANGUAGE it                                                //Imposto la lingua italiana
#define DISPLAY_CHARSET_HD44780 WESTERN                                //Uso i caratteri europei

Impostazioni Per Il Display LCD 12864
Installare la libreria U8GLIB
#define ZONESTAR_LCD                                                   //Disabilitare
#define ANET_FULL_GRAPHICS_LCD                                         //Abilitare
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER                  //Abilitare
//Aggiungere sotto #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
#define ST7920_DELAY_1 DELAY_NS (125)
#define ST7920_DELAY_2 DELAY_NS (125)
#define ST7920_DELAY_3 DELAY_NS (125)

It won't let me compile, it gives me this error:
Please select only one LCD controlleroption.
My printer is an Anet A8
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11637679/Marlin.zip)

### Bug Timeline

dalla versione 2.0.8

### Version of Marlin Firmware

2.0.8

### Printer model

Anet A8

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by EvilGremlin** [comment]
Error is right, you have 2 displays enabled.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.
