### ISSUE TITLE
Some displayed messages are too long

### ISSUE THREAD

**Issue by Cinek75** [MarlinFirmware/Marlin#2591]
When you set the display 128x64 like REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
some displayed messages are too long.
With a defined interface language "pl"
The message "kontrast LCD:" is blurred by field value 32
Similarly, the message "przyspieszenie" (acceleration in en) is overwritten by the field value.
Word of "przyspieszenie" has a length of 14 characters and is less than 17 characters.
Had the font size was too large?

I enclose some pics illustrating the problem.
![20150812_124624](https://cloud.githubusercontent.com/assets/13763952/9222642/b77171b8-40f3-11e5-9b2a-7b7ba02f740d.png)
![20150812_124635](https://cloud.githubusercontent.com/assets/13763952/9222643/b77247e6-40f3-11e5-93d1-48822fee3060.png)
![20150812_124641](https://cloud.githubusercontent.com/assets/13763952/9222645/b776562e-40f3-11e5-8f43-f501be7a8db8.png)
![20150812_125242](https://cloud.githubusercontent.com/assets/13763952/9222644/b77666e6-40f3-11e5-8f96-29e844420530.png)
![20150812_125249](https://cloud.githubusercontent.com/assets/13763952/9222647/b7780032-40f3-11e5-9ec7-d3160a41f868.png)
![20150812_125256](https://cloud.githubusercontent.com/assets/13763952/9222646/b777c536-40f3-11e5-92da-3c01bd0d31f2.png)

**Comment by AnHardt** [comment]
This was fixed last spring.
Please use the `Development` branch or https://github.com/MarlinFirmware/MarlinDev/tree/master
