### ISSUE TITLE
[BUG] Octopus Max EZ V1.0  wont build with env:STM32H723Vx_btt

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#25922]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

BTT_OCTOPUS_MAX_EZ_V1_0  lists these two env: STM32H723Vx_btt and STM32H743Vx_btt
STM32H743Vx_btt builds fine
But STM32H723Vx_btt will not

### Bug Timeline

Unknown

### Expected behavior

It should build or if option is not valid it should be removed 

### Actual behavior

It errors with

```
Marlin/src/inc/../pins/stm32h7/pins_BTT_OCTOPUS_MAX_EZ.h:56:45: error: 'PF0' was not declared in this scope; did you mean 'PF_0'?
   56 | #define X_DIAG_PIN                          PF0   // M1-STOP

```
Port F pins are not defined in this varient

### Steps to Reproduce

1. #define MOTHERBOARD BOARD_BTT_OCTOPUS_MAX_EZ_V1_0
2. #define SERIAL_PORT -1
3. default_envs = STM32H723Vx_btt
4. build and watch it fail

### Version of Marlin Firmware

Bugfix-2.1.x

**Comment by ellensp** [comment]
Note after https://github.com/MarlinFirmware/Marlin/issues/25919 is committed env name will change to

from STM32H723Vx_btt to STM32H723VE_btt

**Comment by thisiskeithb** [comment]
@bigtreetech: Does a second variant of this board exist?

**Comment by sargonphin** [comment]
> Does a second variant of this board exist?

I have the STM32H723Zx variant, or so it says on the CPU at least. @ellensp do you have 2 options for the boards when you build?

![image](https://github.com/MarlinFirmware/Marlin/assets/85966195/c0a05e77-04cd-4f8f-aa31-5324a2c1efa8)

**Comment by thisiskeithb** [comment]
> I have the STM32H723Zx variant

Yes, that’s what I also have here: STM32H723ZET6.

**Comment by thisiskeithb** [comment]
> BTT_OCTOPUS_MAX_EZ_V1_0 lists these two env: STM32H723Vx_btt and STM32H743Vx_btt
> STM32H743Vx_btt builds fine
> But STM32H723Vx_btt will not

I think you mean `STM32H723Zx_btt` & `STM32H723VE_btt` (no STM32H743-based version):

https://github.com/MarlinFirmware/Marlin/blob/f8423f9da09a8d67074b4243917953a6b2b8d279/Marlin/src/pins/pins.h#L816-L817

**Comment by thisiskeithb** [comment]
Fixed in https://github.com/MarlinFirmware/Marlin/pull/25934. The Octopus Max EZ only ships with the STM32H723ZET6 since it needs >100 pins for GPIO.
