### ISSUE TITLE
[FR] MPC Profiles for filament types and adjusting FILAMENT_HEAT_CAPACITY_PERMM without recompiling

### ISSUE THREAD

**Issue by wagnerism** [MarlinFirmware/Marlin#25932]
### Is your feature request related to a problem? Please describe.

As a Marlin user employing MPC, I would like the ability to perform MPC autotune for multiple filament types and store/recall settings when changing the filament type used on the printer.

https://marlinfw.org/docs/features/model_predictive_control.html requires that a single filament heat capacity value be specified via FILAMENT_HEAT_CAPACITY_PERMM, which varies by filament type and diameter.  I swap between PLA and PETG filament types which have a great difference in heat capacity.

My searches did not reveal a way to change FILAMENT_HEAT_CAPACITY_PERMM on a running printer to autotune MPC for a filament change.  It appears that the only way to change this value is to update Configuration.h and compile.

### Describe the feature you want

Add Configuration.h values similar to PREHEAT_1_LABEL like:
MPC_FILAMENT_1_LABEL
MPC_FILAMENT_1_HEAT_CAPACITY_PERMM
MPC_FILAMENT_1_INCLUDE_FAN

Amend M306 and menus to include which filament number/name to autotune.

Store multiple MPC autotune results in EEPROM.

Update menus to recall MPC autotune results based on filament number/name.

Add gcode M command to recall MPC autotune results based on filament number/name

**Comment by thisiskeithb** [comment]
You don't need to recompile to set the filament heat capacity. You can set it (and other MPC settings) via g-code with [`M306 H<value>`](https://marlinfw.org/docs/gcode/M306.html).
