### ISSUE TITLE
[BUG] Printhead toolchange moving past software endstops

### ISSUE THREAD

**Issue by ansonl** [MarlinFirmware/Marlin#25930]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I set up a printer with a new motherboard (STM32 Octopus Pro) with a mechanical switching nozzle that runs `EVENT_GCODE_TOOLCHANGE_T0` and `EVENT_GCODE_TOOLCHANGE_T1` to swap the nozzle height. Both EVENT_GCODEs are written in the offset of T0 which is zero offset and `TC_GCODE_USE_GLOBAL_X` and `TC_GCODE_USE_GLOBAL_Y` is enabled. 

For some reason when I switch from T1 to T0, the printhead makes a move towards the right past software endstops before running `EVENT_GCODE_TOOLCHANGE_T0`. I think that it is doing the hotend offset adjustment movement where the printhead makes a quick move to the new hotend nozzle offset. In my case T1 nozzle is to the right of T0 nozzle so it tries to move the T0 nozzle to the current position of T1 nozzle. 

I recorded a video of the issue [here](https://youtube.com/shorts/5vuPJPk1J9w?feature=share). 
1. The first T0->T1 toolchange works fine. 
2. When running T1-T0 next, the printhead moves past endstops and stalls. After that occurs and the printer is in T0 mode, the printhead is offset about 3mm too far to the left which is the coincidentally the distance that it moved to the right before hitting the printer limits. 
3. When I run T0 ->T1 again, the printhead lever doesn't engage the white lever because the printhead is too far left by 3mm. Before `EVENT_GCODE_TOOLCHANGE_T1` runs for second T0->T1, the full hotend offset adjustment runs with a quick move to the left because there is enough space. The printer didn't do this for the first T0->T1 due to it starting at the far left and respecting the endstops. 

This offset movement has always respected the bed size/software endstops in my other AVR printer that has the same mechanical switching nozzle and the printhead did not go past the bed size on the other printer. I tried the latest bugfix on both printers with similar configurations and the problem only happens on the STM32 printer. 

Am I missing something or is there a mismatch in my bed size that causes the printers to not stop at the software endstop? Thanks. 

The relevant toolchange configuration on the STM32 printer is below. The other configuration differences between the printers are the motherboard, pins, and printer frame size which should not affect tool changing. Both AVR and STM32 configs are attached. 

```
// The size of the printable area
#define X_BED_SIZE 222 //226
#define Y_BED_SIZE 216 //224

// Travel limits (linear=mm, rotational=°) after homing, corresponding to endstop positions.
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0
#define X_MAX_POS X_BED_SIZE
#define Y_MAX_POS Y_BED_SIZE
#define Z_MAX_POS 213

#define HOTEND_OFFSET_X { 0.0, 18.00 } // (mm) relative X-offset for each nozzle
#define HOTEND_OFFSET_Y { 0.0, 0.00 }  // (mm) relative Y-offset for each nozzle
#define HOTEND_OFFSET_Z { 0.0, -1.15 }  // (mm) relative Z-offset for each nozzle

#define EVENT_GCODE_TOOLCHANGE_T0 "G0 X214 F7200\nG0 Y180\nG0 X218.5\nG0 Y194.5\nG0 X214"  // Extra G-code to run while executing tool-change command T0
#define EVENT_GCODE_TOOLCHANGE_T1 "G0 X214 F7200\nG0 Y209\nG0 X218\nG0 Y192\nG0 X214"  // Extra G-code to run while executing tool-change command T1

#define TC_GCODE_USE_GLOBAL_X   // Use X position relative to Tool 0
#define TC_GCODE_USE_GLOBAL_Y   // Use Y position relative to Tool 0
```

### Bug Timeline

new, only happens with current 

### Expected behavior

Toolchange between T1 and T0 does not move printhead to the right past software endstops (while doing nozzle offset adjustment?)

### Actual behavior

Toolchange between T1 and T0 moves printhead to the right past software endstops (while doing nozzle offset adjustment?)

### Steps to Reproduce

1. Home all axes
4. Run T1
5. Run T0 (problem occurs here)

### Version of Marlin Firmware

bugfix2.1.x

### Printer model

Ultimaker

### Electronics

Octopus Pro

### Add-ons

DXU switching nozzle

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[STM32 Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11644778/Configuration.zip)
[AVR config.zip](https://github.com/MarlinFirmware/Marlin/files/11644797/config.zip)

**Comment by rondlh** [comment]
I just tested this with the latest bugfix, G28 (Z-homing with BLTouch), then the T0 head is in the middle (X). Sending T1 sends the T1 head to the middle, and sending T0 reverses that again without issue. The X-offset is about 372mm on a 300mm bed.
So I cannot reproduce the issue.
You can try sending a M502 (load factory defaults) followed by a M500 (save settings) and then restart the printer and try again.

**Comment by ansonl** [comment]
The collision ended up being caused by the 2 mechanical switching lever staying next to each other in the exact areas that they would collide if the printhead did the offset adjustment. Because there isn't disallowed/irregular bed area support at the moment, the solution was to add a Y move after the EVENT_GCODE to move the printhead to a safe location where it wouldn't hit the white lever.
