### ISSUE TITLE
Error line 4198- Marlin_main.cpp -V1.0.2

### ISSUE THREAD

**Issue by radioelf** [MarlinFirmware/Marlin#2596]
Hi.
I think there is an error on the line 4198 for Marlin_main.cpp:
# if EXTRUDER > 1

correct:
# if EXTRUDERS > 1

Thanks

**Comment by Wackerbarth** [comment]
You are correct, sir.  This has already been fixed in our development branch and I am preparing a patch for the 1.0.x branch.
