### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by YoussefTolba** [MarlinFirmware/Marlin#25987]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hey guys, my printer has been printing perfectly for 7 months but for the last 2 months the first layer is always bigger on the left side of the print (-ve x-axis) and it is not elephant foot and it only happens in the left side of a print and the other sides are perfect, my first layer is really dialed in, I have tried changing my whole extruder more than one filament role all esun, I use a dryer even while printing, it all started when I started changing stuff in the firmware, I then used the same firmware that was working and it was still having the same problem, I am know just frustrated and dont know what to do, I recalibrated the printer almost a dozen times, my printer now is printing better than it ever was and really accurately too but the problem remains hahaha, my printer is a full bear prusa build, with an skr 1.4 turbo and tmc2209 driver, I'm sorry I can't post a photo as you can't see it in a picture even zoomed in, I have searched the prusa forum and reddit and looked at most 3d printing websites that google threw at me, and I could not find any solution I even reassembled my printer. I use stock prusa i3 mk3 print settings on prusa slicer .

### Bug Timeline

started in april with an old version of marlin but kept going after using the latest version

### Expected behavior

first layer of printed part to be consistent all around

### Actual behavior

first layer is slightly bigger about 1/2 mm to the left.

### Steps to Reproduce

n/a

### Version of Marlin Firmware

2.1.2.1

### Printer model

full bear prusa build

### Electronics

skr 1.4 turbo

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11763897/Marlin.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
