### ISSUE TITLE
[BUG] Random movement xy axis mks robin nano

### ISSUE THREAD

**Issue by franmuzi1** [MarlinFirmware/Marlin#25980]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I compiled marlin for my neptune 2 (mks robin nano v 1,3), everything works except random axis movement during print.
it continue to extrude while randomly tracking lines on the buildplate.

### Version of Marlin Firmware

2.1.2.1

### Printer model

Neptune 2

### Electronics

E3d Hotend

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

](url)

**Comment by franmuzi1** [comment]
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11747318/configuration.zip)

**Comment by leftbrasil** [comment]
I'm experiencing this issue as well. I have a feeling that it have something to do with SD Card logic. Have you tried printing when there's single file only on the card?

**Comment by franmuzi1** [comment]
Yes I tried, nothing changed.
Also tried replacing the SD not solving my problem

**Comment by toomuchwonder** [comment]
I also have the same issue. I couldn't print anything successfully from the SD card. I've since moved to printing via serial port using Octoprint and still get occasional layer shifts in both X and Y directions.

**Comment by RonnyLV** [comment]
+1 on the issue. Sometimes toolhead just wanders off in the middle of a print

**Comment by RonnyLV** [comment]
@franmuzi1 you closed the issue - did you find a solution to the problem?

**Comment by phobos79** [comment]
is a duplicate of this:
https://github.com/MarlinFirmware/Marlin/issues/25653

if you want to fix, install the 2.1.1.1, if you want input shaping on it i can give you the folder

**Comment by thinkyhead** [comment]
Duplicate of #25653
