### ISSUE TITLE
[BUG] M20 Causes GT2560 V4.0 to crash

### ISSUE THREAD

**Issue by SparkyDan555** [MarlinFirmware/Marlin#25985]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Issuing M20 from any host (tested with ESP3D, Repetier-Host Mac, Pronterface) causes Marlin to crash and reboot. 

This bug does not occur when there is no SD card in the slot. Files can be read and executed from the LCD without issue. I have tested different SD cards with files, without files and freshly formatted which all cause the crash.

### Bug Timeline

Roughly last 2-3 weeks of bugfix (I think)

### Expected behavior

The SD card files are listed to the host. 

### Actual behavior

Marlin crashes and reboots.

### Steps to Reproduce

1. Insert SD card in slot
2. Connect host over serial (Baud 250000)
3. Issue M20 command (refresh files in ESP3D)
4. Observe boot screen on LCD and boot text in console.

### Version of Marlin Firmware

Marlin bugfix-2.1.x Jun 15 2023 12:10:37

### Printer model

Geeetech A10M

### Electronics

Stock GT2560 V4.0

### Add-ons

None

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Other (explain below)

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Logs:
> 12:35:43 pm: N184 M20 *60
< 12:35:43 pm: Begin file list
< 12:35:43 pm: start
> 12:35:43 pm: N1 M110 *2
< 12:35:43 pm: Marlin bugfix-2.1.x  <------- Marlin crashes and reboots.

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/11757243/Archive.zip)

**Comment by ellensp** [comment]
this is often caused by having lots of gcode files on your sdcard.  (mega2560 only has 8k of memory 
or a corrupted sdcard 
in both case reformat the sdcard to remove files and fix any corruption

**Comment by SparkyDan555** [comment]
This is why I formatted the card and tried multiple other cards that are working on other machines. Unfortunately this did not fix the issue.

**Comment by SparkyDan555** [comment]
This is still an issue in bugfix-2.1.x.

**Comment by SparkyDan555** [comment]
This is still an issue in bugfix-2.1.x.

**Comment by fausby** [comment]
Me too on GEEETECH A20T GT2560 4.1 B

**Comment by fausby** [comment]
Testing, I found that if I disable BLTOUCH, as provided in the example files, with PROBE_MANUALLY, then it works.
¿WHY?

**Comment by SparkyDan555** [comment]
> Testing, I found that if I disable BLTOUCH, as provided in the example files, with PROBE_MANUALLY, then it works. ¿WHY?

I have tested disabling BLTouch (and temporarily enabling FIXED_MOUNTED_PROBE to satisfy sanity checks) and it still crashes when M20 is sent from a host.

**Comment by fausby** [comment]
With default configuration files the SD works.  With BLTOUCH, when I insert the SD, it reboots until I remove the SD.

**Comment by fausby** [comment]
OK, if my SD has few files, it works.

**Comment by SparkyDan555** [comment]
This is still an issue in bugfix-2.1.x.
