### ISSUE TITLE
[BUG] SD Card not working

### ISSUE THREAD

**Issue by reynum2** [MarlinFirmware/Marlin#25981]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have installed a RAMPS 1.4 on my Anet A8 and installed Marlin 2.1.2.1 on it.
But when I insert my SD card I have the message "Media init fail"

I have just enable the 
"#define SDSUPPORT" 
and the 
"#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER"
The SD card is Fat32 and works well on another 3D printer

![20230604_204634](https://github.com/MarlinFirmware/Marlin/assets/11191723/1f753271-67ce-49ab-9cbc-53f0ddfe4a15)

### Version of Marlin Firmware

2.1.2.1

### Printer model

Anet A8

### Electronics

RAMPS 1.4

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11748082/Configuration.zip)

**Comment by ellensp** [comment]
Not all sdcard are equal

Not all 3d printer access sdcards in the same way

Many new modern sd card no longer support the legacy SPI protocol that a old ramps uses

New 3d printers with 32bit controllers tend to use SDIO protocol instead..

It is very likely your sd card just does not work using SPI

**Comment by reynum2** [comment]
I have tested with 4 different SD cards. 
1Go Sandisk
16Go and 32Go Transcend
64Go Samsung
And each has the same behavior (but works with Marlin 1.9 on the anet A8 motherboard)

**Comment by reynum2** [comment]
Hello !
Any update regarding this problem ?

**Comment by reynum2** [comment]
Hello,

I tried to enable the parameter 
#define SDCARD_CONNECTION LCD

But it still not working

**Comment by reynum2** [comment]
> It is very likely your sd card just does not work using SPI

What your are saying is Marlin uses SPI to communicate with the SD Card ?

I ask that because I just test the connection in accordance with :
![image](https://github.com/MarlinFirmware/Marlin/assets/11191723/320a6b5a-985c-41b2-8825-36144a44629c)
https://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller

And the connection with EXP2 D49 -> D49 ( SD-Card detect ) works well 
But the connection with EXP2 D49 -> D49 ( SD-Card SPI/MOSI ) does not work 
It way be a reason why my SD-Card reader does not work.

What do you think about ?

**Comment by ellensp** [comment]
That picture is in error

see pins diagram 

https://reprap.org/mediawiki/images/c/ca/Arduinomega1-4connectors.png

the connector is

5v D49 
D50 D51  this is the MOSI pin
D52 D53
gnd NC

**Comment by ellensp** [comment]
There is nothing wrong with marlin 2.1.2.1 or your config

You have a hardware issue

I just tested your configs on Marlin 2.1.2.1 on my stock RAMPS 1..4 with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

SD card detects and reads fine

**Comment by reynum2** [comment]
> I just tested your configs on Marlin 2.1.2.1 on my stock RAMPS 1..4 with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
> SD card detects and reads fine

Thank you for this feedback.
Now I now where I should search to make this SD-Card works

I have a suspicion on the chip 74HC4050D (U1) just near the SD reader

![20230630_170242](https://github.com/MarlinFirmware/Marlin/assets/11191723/9eae5d83-5c03-40f5-95ad-8ac4694fe358)

**Comment by ellensp** [comment]
That chip is being used as a voltage level shifter 5v to 3.3v   This is certainly a possibility. 

You can test this.. you disconnect the lcd cables  You use wires to connect 5v and gnd of the lcd.  You then connect 5v to the lcd exp2 D51 sdcard mosi pin and check the output of the chip is 3.3v on the sdcard mosi pin , repeat for D52 sdcard sck and D53 sdcard cs    

But Ive seem many more issues with the ramps to lcd adapter board, with bad soldering

**Comment by reynum2** [comment]
> But Ive seem many more issues with the ramps to lcd adapter board, with bad soldering

Year you're very good !
I found the mistake
![20230702_150349](https://github.com/MarlinFirmware/Marlin/assets/11191723/d813fb2a-6101-4351-959f-e8d4b5b0aa1a)
Look at this sneaky little wrong solder
It just fixed it and everything works well now \o/
