### ISSUE TITLE
[BUG] (E max temp not respected on restart)

### ISSUE THREAD

**Issue by landodragon141** [MarlinFirmware/Marlin#25993]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

My max E temp is set to 300C. When E-stopping with the extruder at 260 (printing ABS) marlin throws the error "E1 Max Temp". I only have 1 extruder so shouldn't this be E0?

### Steps to Reproduce
Heat Extruder to 260C
Either Emergency Stop or Kill power to board
Immediately turn back on.
Marlin should throw Max temp error on the extruder
Once the Extruder gets down to about 245 it will pass and boot.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11780315/Marlin.zip)

### Version of Marlin Firmware

Latest Bugfix and 2.1.2.1

### Printer model

Custom

### Electronics

SKR 1.3

### Add-ons

PT1000?

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
Displays start at E1, board and code internally use E0. 
If you really want it to say E0 there is a setting for it.

#define  NUMBER_TOOLS_FROM_0 But this only works on some User interfaces

**Comment by ellensp** [comment]
'When E-stopping"  how are you imitating this?

Please fill in the steps to reproduce.

**Comment by landodragon141** [comment]
I'm using an emergency stop button on my display. The same problem occurs if I just shut of the power and turn it back on. It seems like it needs to get down to 245 ish before it will fully start

**Comment by thinkyhead** [comment]
Seems interesting. If you're able to try the latest `bugfix-2.1.x` with all your other optional features disabled, that could help to isolate whether this is something with the UI or the startup or the temperature. At the moment it sounds like there hasn't been any major attempt to isolate the cause, so we should get on that.

**Comment by landodragon141** [comment]
Yeah I'll do that in the next day or two.

**Comment by landodragon141** [comment]
Sorry I've been crazy busy and still haven't had a chance to get to testing this.....
