### ISSUE TITLE
[BUG] Autobed Leveling Problem

### ISSUE THREAD

**Issue by manurafal** [MarlinFirmware/Marlin#25995]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have updated my Marlin from version 2.0.7 to 2.1.2.1, and now when I perform a 4x4 mesh leveling, the 3DTouch reaches the bed limit at the back of the bed, and the PROBING_MARGIN is set to 20.

I have an Ender 3 Pro with a bed size of 235x235, and the 3DTouch is positioned at NOZZLE_TO_PROBE_OFFSET { -40, -15, 0 }.

 // Set the number of grid points per dimension.
  #define GRID_MAX_POINTS_X 4
  #define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X

// The size of the printable area
#define X_BED_SIZE 235
#define Y_BED_SIZE 235

// Travel limits (linear=mm, rotational=°) after homing, corresponding to endstop positions.
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0
#define X_MAX_POS X_BED_SIZE
#define Y_MAX_POS Y_BED_SIZE
#define Z_MAX_POS 250

### Bug Timeline

Existing issue.

### Expected behavior

I expect bed to be probed logical equal-distance probe points so that extrapolation is more acurate.

### Steps to Reproduce

    1. Set probe margin at 10.
    2. Set probe offset at -40.
    3. Run automatic bed leveling.
    4. Does not keep the correct distance at the front and back of the bed when meshing

### Version of Marlin Firmware

2.1.2.1

### Printer model

Creality Ender 3 Pro

### Electronics

SKR E3 Turbo

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11781605/Marlin.zip)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
