### ISSUE TITLE
why was 2595 closed and by whom?

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#2600]
I placed some detailed info on 2595 and now see that it is closed but no one has indicated it was closed.
I don't consider this closed. Do I need to open another?

**Comment by clefranc** [comment]
![sans titre4](https://cloud.githubusercontent.com/assets/4294448/9372498/35fb1a34-46ad-11e5-9739-b31d698ec2ec.png)

**Comment by ruggb** [comment]
please tell me how I did that, because I have no clue. It needs to be reopened.

**Comment by ruggb** [comment]
OK, I figured it out -- I clicked the wrong button - I will close this one on purpose now.
