### ISSUE TITLE
[FR] Add support for Differential Extruder

### ISSUE THREAD

**Issue by vedransi** [MarlinFirmware/Marlin#26004]
### Are you looking for hardware support?

I have developed a new type of extruder and now I need help with firmware that will support it

### Describe the feature you want

I want the extruder stepper to replicate the rotation of the X stepper and then add the E rotation to it.
For example, g-code " G1 X10 E3" says “move 10mm and extrude 3mm of filament”.
In a current 3d printer, the X stepper will rotate and move the print head 10mm while the extruder stepper rotates and extrudes 3mm of filament.
For the new extruder to work properly, the X stepper must rotate as before, but the E stepper must rotate as if it’s extruding 10+3=13mm of filament.
I’ve looked at the Marlin code already but I got stuck on acceleration profiles, transmission ratios and similar. If X stepper and E stepper accelerate differently it’ll be a problem, so they have to have identical accelerations, like X and Y steppers in CoreXY printers.
NOTE: I have a 100% functional 100% mechanical solution which relies on a small differential mechanism (hence the name), but it would be so much simpler, cheaper and more elegant to solve this in firmware. Please help if you can. 
Thanks heaps in advance

### Additional context

Differential extruder combines a light print head with precise extrusion (i.e. combines the advantages of Bowden and Direct Drive). For example, it adds less than 80g to the Creality Ender 3v2 print head. Photos attached.
![1_Frontal](https://github.com/MarlinFirmware/Marlin/assets/36977084/b69195cf-8a74-44a5-9347-dda44f8090c0)
![2_Left](https://github.com/MarlinFirmware/Marlin/assets/36977084/682ce3ec-56c6-4435-8ccf-29f3a73f215d)
![3_Back](https://github.com/MarlinFirmware/Marlin/assets/36977084/17b553ca-7050-4a2b-90b5-86300b2f33c9)
![4_Back_Zoom](https://github.com/MarlinFirmware/Marlin/assets/36977084/b626e846-5ce3-4d2f-97e6-05cedfd9d2f3)
![5_Detail](https://github.com/MarlinFirmware/Marlin/assets/36977084/c87d94e4-aca5-40be-99b3-3a1b6f9ffc05)
![6_Weight](https://github.com/MarlinFirmware/Marlin/assets/36977084/78e2323c-8c6c-4ad1-a91f-810ad0001d64)

**Comment by vedransi** [comment]
The photos attached previously show the Differential Extruder on a Creality Ender 3v2. Blue parts are its components: the E stepper mount on the left, the extruder assembly (on the print head) and the tensioner mount on the right.
The extruder belt that goes between them is a continuous loop, 852mm.
This is how it all works:
1. When the X stepper pulls the print head, say, to the left, the E stepper must pull to the left in exactly the same way, so that the extruder pulley (at the back of the extruder assembly) does not rotate at all. 
2. When the X stepper is halted it keeps the print head stationary. If then the E stepper rotates, that rotation is transferred via the timing belt loop to the extruder pulley, which then drives the toothed gear and moves the filament.
Hope this helps. Cheers!

**Comment by thisiskeithb** [comment]
Duplicate of #17995
