### ISSUE TITLE
Movement occurring not in G-Code.

### ISSUE THREAD

**Issue by ZeroxCorbin** [MarlinFirmware/Marlin#2601]
Hello,
First, thank you devs for all your hard work. Really impressive what you have accomplished.

So, I am having a hard time getting complete prints. I have been trying to diagnose what is happening but I am stuck. Hopefully someone can shed light on my mistake.

History: I purchased a Sintron Pursa i3. It came with;
1. Arduino Mega with ATmega2560
2. Ramps 1.4
3. 5x A4988 driver modules
4. LCD 2004 smart display controller with SD card
https://www.3dprintersonlinestore.com/super-smart-prusa-i3

It shipped with Marlin 1.0.0. I upgraded to Marlin 1.0.2. I changed the configuration files to match what Sintron sent me based on Marlin 1.0.0. I would like to share the configuration files but I am not sure how to attach them to this post.

I downloaded the latest Repetier software (1.5.4). I comes with Slic3r 1.2.9. I downloaded a 20mm test cube and tweaked the Slic3r settings to get a good print. I started printing my project and at first things looked good.

I print from the SD card...

After printing a couple of pieces I enabled "Generate Supports" option in Slic3r. I started printing a part and after a few layers the head paused, shook, and then started moving in a random diagonal direction slowly. It dragged across the part. It then moved up a layer, skipping the rest of the layer it was on, and started printing again. I stopped the print.

I started over and got through the print using the same gcode file. The next part I printed was overnight. When I looked in the morning the part had what appeared to be missing or partial layers. There were also a few strands of plastic in random directions out from the part. I tried the print again with the same gcode file. At different locations than before, random movements occurred and layers were skipped.

I decided to try Marlin 1.0.0 that was shipped with the unit. It had similar issues, but it was more with the extrude axis backing up until the filament came out of the head. So i went back to 1.0.2.

I then tried to work with the retraction variables in Slic3r but did not see an improvement. At this point I disabled "Generate Supports" in Slic3r but I would still get the occasional random movement and skipped/partial layers.

I reset Slic3r to defaults and started over thinking I may have messed up a setting. It printed a couple parts correctly but then it started the random movements again. So I read about enabling firmware retraction support in Slic3r. Since I observed the extrude axis backing up farther than it should I thought this would help eliminate a potential Slic3r issue. I enabled the firmware retraction support in Marlin. I was able to get through two prints and things looked good.

I started an overnight print and in the morning the print was 2/3 complete and the X/Y/Z axis where at there positive travel limits and the filament was not in the extrude head anymore. The display said it had completed 97% but the axis where shut off and the heaters were shut off. I went through the gcode and could not find a line that would have commanded the axis to the positions they where at.

Here are some pictures;

![20150819_175506](https://cloud.githubusercontent.com/assets/13880118/9375480/0f2a6028-46cf-11e5-865c-73550d95923b.jpg)

The axis at their limits;
![20150819_175524](https://cloud.githubusercontent.com/assets/13880118/9375488/26cf0b5c-46cf-11e5-8155-044325d621ab.jpg)

The filament does not look broken;
![20150819_175536](https://cloud.githubusercontent.com/assets/13880118/9375489/360ed700-46cf-11e5-8868-d8bcd2ceb3f5.jpg)

The printer indicates it is still running;
![20150819_175600](https://cloud.githubusercontent.com/assets/13880118/9375494/44c242f0-46cf-11e5-901b-edc3b7cb73d8.jpg)

I have been searching and reading for days. The gcode files Slic3r is producing look good, best I can tell. I have tried many different options in Slic3r and Marlin with not luck.

Here is the end of the gcode file that produced the result above. I belive the extruder retracted the filament then completed the part, with no filament. The moves to X190 Y190 are not in the gcode.

G10 ; retract
G92 E0
G1 X95.461 Y74.805 F7800.000
G11 ; unretract
G92 E0
G1 X95.243 Y75.022 E0.01683 F900.000
G1 X95.243 Y75.621 E0.04956
G1 X95.916 Y74.949 E0.10155
G1 X96.139 Y75.324 E0.12544
G1 X95.243 Y76.220 E0.19468
G1 X95.243 Y76.819 E0.22741
G1 X96.433 Y75.629 E0.31941
G1 X96.798 Y75.862 E0.34311
G1 X95.243 Y77.417 E0.46333
G1 X95.243 Y78.016 E0.49607
G1 X97.249 Y76.010 E0.65115
G1 X97.815 Y76.043 E0.68212
G1 X95.243 Y78.615 E0.88092
G10 ; retract
G92 E0
M107
M140 S0 ;Set Bed Temp
M104 S0 ;Set Extruder Temp
G91 ;Relative moves
G1 Z20 F5000 ; lift nozzle ;Lift extruder 20mm
M84     ; disable motors

I may not have given the information needed to determine the issue. If you need anything please let me know and I would be happy to share it. Thank you for your time. Jack..

**Comment by ZeroxCorbin** [comment]
I was able to video the issue. At least for the Y axis.

http://42nexus.com/3dprinter/3DPrinter_Runaway.mp4

From watching the print for awhile. I was able to observe the issue a few times. It looks like the move is started and the processor gets "locked" for a moment and the axis continues on it initial trajectory. If the command pulse is hardware PWM then main() could be delayed and the axis would continue at speed? The only peripheral that would hold up the process, that I am aware of, is the SD card. I assume it is SPI or I2C. So I changed SD cards to a newer one. Copied the file that had issues and am running it now.

Update: The program just stopped this time. This is what was on the display.

![20150821_040922](https://cloud.githubusercontent.com/assets/13880118/9404102/a36ae0d2-47ba-11e5-9a89-0897130e2cf8.jpg)

I will write the file to the SD card again from Repetier.

**Comment by nitewing76** [comment]
Since you are using PLA and painter's tape, you need to turn off the heatbed.  

Possibly your PSU is too close to the machine....heat from the CPU is blowing on your controller, the wires laying next to it may be picking up some EMI. 

Since the pic of the RAMPS on the website has heatsinks on the A4988 chips, I will assume yours does also....so you need a fan blowing on these heatsinks (not the one from the PSU).

Remove all excess lubricants...this will attract dirt and debris. Also ensure your lubricant is non-petroleum based.  Even some lithium grease has petroleum products in it (such as the stuff from Lowe's...I can't remember the name, but it has an orange cap). 

Ensure all wires are in twisted pairs...the +/- of limit switches and for the stepper motors, twist the wires that are on the same coil. 

The settings given to you by Sintron for the configuration.h files are only estimations...you need to calibrate to get precises settings. There are many web tutorials on how to do this. 

I suspect your #1 problem is heat, which will be solved with another fan.  If these reccomendations do not work, I would suggest copy+paste your comments and mine to http://forums.reprap.org/list.php?262 . You will get many more responses for your issues there. If you do create a thread there, please post it here so I can follow your progress. :)

**Comment by ZeroxCorbin** [comment]
Thank you Nitewing76, I have had a larger fan blowing on the entire control system since the beginning. You can see it in the second comment I posted. The white fan in the upper left.

I have changed to a more modern SD card. I was using an older, 3 years or so, SD card. It was convenient because it flips open and has a USB connection built-in. It seems to have been causing most of the issues. I am using a 30 MBs SD now and it seems to be working much better. I have run about 10 prints and have not had an issue.

In fact, I am closing this issue here and will take your suggestion to post on reprap.org in the future.

Thanks again and have fun printing....

**Comment by thinkyhead** [comment]
I can confirm that if you see random movement during a print this indicates a communication / connection / interference problem. There is little that Marlin can do except maybe abort the print as soon as any "bizarre" commands are received. For example, it currently will throw the error **Unknown command: ""** in some instances. We know this indicates a communication problem, so we could just abort the print job. But I worry that might be too frightening for users, who may just be able to wiggle some wires and continue printing normally.
