### ISSUE TITLE
Z Offset not saving when power cycling

### ISSUE THREAD

**Issue by Kurtis250** [MarlinFirmware/Marlin#26036]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

Trying to setup zoffset and preheat settings in configuration menu but not saving after power cycle. With SD card in or out.

### Bug Timeline

Just set up printer with marlin 2.0.7.1

### Expected behavior

Save Z offset for BLTouch probe, and preheat settings when power cycling

### Actual behavior

Does not save any changes made to Z offset, or preheat settings (pla/abs) when set to the values I would like/need them to be at to work properly after saving Configuration and power cycling 3d printer.

### Steps to Reproduce

1. Power on printer
2. Auto home printer
3. Set zoffset and preheat settings in configuration menu
4. Save configuration to board
5. Power off printer 
6. Wait 5-10 seconds
7. Power on printer
8. Check if settings saved

### Version of Marlin Firmware

2.0.7.1

### Printer model

Creality CR-10

### Electronics

Big Tree Tech SKR E3 Turbo

### Add-ons

BLTouch 

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

Will add .zip when I get home to add

**Comment by ellensp** [comment]
2.0.7.1 is old, released Oct 10, 2020  It is no longer getting any maintenance.

Please upgrade your version of Marlin

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
