### ISSUE TITLE
[BUG] marlin 2.1.2.1 compilation error

### ISSUE THREAD

**Issue by AngelSerra** [MarlinFirmware/Marlin#26046]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The problem,
The problem is that when activating //#define ESP3D_WIFISUPPORT // ESP3D Library WiFi management (https://github.com/luc-github/ESP3DLib)

but the MarlinConfigPre.h file exists and is in its place. as vew in the screenshots of the added file

### Bug Timeline

new

### Version of Marlin Firmware

2.1.2.1

### Printer model

HyperCube

### Electronics

Tnybee

### Add-ons

Bltouch

### Bed Leveling

ABL Linear grid

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11937524/Configuration.zip)
The problem,
The problem is that when activating //#define ESP3D_WIFISUPPORT // ESP3D Library WiFi management (https://github.com/luc-github/ESP3DLib)

but the MarlinConfigPre.h file exists and is in its place. as vew in the screenshots of the added file

**Comment by ellensp** [comment]
Provided configs with ESP3D_WIFISUPPORT enabled compiles without issue on marlin 2.1.2.1

**Comment by ellensp** [comment]
Delete your ```C:\Users\mapor\.platformio``` folder. restart vscode and try again.
