### ISSUE TITLE
#include errors detected. Help

### ISSUE THREAD

**Issue by Kurtis250** [MarlinFirmware/Marlin#26042]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

getting error code
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\vadak\Downloads\Marlin-2.1.2.1-SKR-E3-Turbo\Marlin\src\MarlinCore.cpp).
and i dont know how to get this to  work

### Bug Timeline

trying to update printer

### Steps to Reproduce

1. open project in Visual Studio Code with platformIO and Marlin auto Build installed.
2. open Configuration.h and Configuration.adv.h

### Version of Marlin Firmware

2.1.2.1

### Printer model

CR10

### Electronics

BigTreeTech SKR E3 Turbo

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin-2.1.2.1-SKR-E3-Turbo.zip](https://github.com/MarlinFirmware/Marlin/files/11932116/Marlin-2.1.2.1-SKR-E3-Turbo.zip)

**Comment by EvilGremlin** [comment]
this is not an error, ignore "problems" tab, only terminal in meaningful


This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.
