### ISSUE TITLE
[BUG] OCTOPUS MAX EZ SDCARD NOT RECOGNIZED

### ISSUE THREAD

**Issue by gianguardo** [MarlinFirmware/Marlin#26058]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi I am having this problem with my octopus max ez can anyone help me please
1 cannot read the sdcard in the internal slot 
2 if I connect it to the LCD display it recognizes it but as I try to print the card restarts
3 i tried to use a usb connection but i have the same error as the lcd
4 I tried different kinds of format
fat (16 or 32)
fat32

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11971378/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/11971379/Configuration_adv.zip)

**Comment by gianguardo** [comment]
Update:
Using the latest version of marlin now I can print via lcd (after initializing EPPROM as I receive temp err) and via usb but if I use the SDcard via the card it doesn't detect it for me.

**Comment by ellensp** [comment]
One potential issue I see

You have TMC5160 which uses  SPI

//
// Default pins for TMC software SPI
//
#ifndef TMC_SPI_MOSI
  #define TMC_SPI_MOSI                      PE14
#endif
#ifndef TMC_SPI_MISO
  #define TMC_SPI_MISO                      PE13
#endif
#ifndef TMC_SPI_SCK
  #define TMC_SPI_SCK                       PE12
#endif


but the SDCARD uses same SPI but needs hardware

you have #define TMC_USE_SW_SPI in Configuration._adv.h 

Disable this

**Comment by gianguardo** [comment]
Hi, I tried disabling TMC_USE_SW_SPI in Configuration._adv.h but it still doesn't detect my sdcard.

**Comment by ellensp** [comment]
where are you sticking the sdcard in the motherboard or the BTT_MINI_12864_V1 lcd?
As the config shows the lcd is configured and that automatically means the board expects it on the lcd, not the motherboard

**Comment by gianguardo** [comment]
ok, can you suggest me how can i change it?
Thank you

**Comment by ellensp** [comment]
you set #define SDCARD_CONNECTION ONBOARD in Configuration_adv.h to make it use the onboard sdcard

**Comment by gianguardo** [comment]
Now it works, thank you very much for the help
