### ISSUE TITLE
[BUG] POWER LOSS RECOVERY extruder squeezes out a lot of filament

### ISSUE THREAD

**Issue by fedorovstas** [MarlinFirmware/Marlin#26057]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After POWER LOSS RECOVERY hotend and bed heated up, x and axis doing auto home and go back to the place where it finished printing. Then extruder squeezes out a lot of filament and there is a large influx of plastic. After that printer continued his work.

### Bug Timeline

old

### Expected behavior

After PLR extruder does not extrude as much plastic

### Actual behavior

After PLR extruder squeezes out a lot of filament

### Steps to Reproduce

1. Start printing
2. Power off
3. Resume print

### Version of Marlin Firmware

2.1.2.1 hotfix

### Printer model

Creality Ender 3 Pro

### Electronics

SKR Mini E3 v3.0

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11968452/configuration.zip)

**Comment by EvilGremlin** [comment]
Tweak your ADVANCED_PAUSE values, don't forget to reset EEPROM

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.

**Comment by fedorovstas** [comment]
> Tweak your ADVANCED_PAUSE values, don't forget to reset EEPROM
> 
> This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:
> 
>     * MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
> 
>     * RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
> 
>     * Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
> 
>     * Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
> 
>     * [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
> 
>     * 3D Printing Discord server. Join link: https://discord.gg/3dprinters
> 
>     * Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y
> 
> 
> After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.

Set the load and unload values to 0. Nothing changes. Problem similar to [this](https://github.com/MarlinFirmware/Marlin/issues/24105) bug report.

**Comment by ThomasToka** [comment]
I can approve this.

Set advanced pause purge and retract to 0, set also 

```
    #define POWER_LOSS_PURGE_LEN      0 // (mm) Length of filament to purge on resume
    #define POWER_LOSS_RETRACT_LEN    0 // (mm) Length of filament to retract on fail. Requires backup power.
```

behavior is the same. after reaching the print position it purges a lot very fast.

cant find it to be honest in powerloss.cpp .


Edit: Got it sorted. I had something from the Ender 5 s1 PR included. reverting to the bugfix-2.1.x fixed it.

Edit2: see following comment. its stil there.

Sorry for the wind.

**Comment by ThomasToka** [comment]
@fedorovstas is that what you see also?

https://www.veed.io/view/645d326c-162e-4d37-9386-c22dd05b3c60?panel=share

**Comment by fedorovstas** [comment]
@ThomasToka No. I will add video later.

**Comment by fedorovstas** [comment]
@ThomasToka https://photos.app.goo.gl/gT79LSomQTtAmVru5

Sometimes it start squeezing when hotend start moving from home.

**Comment by Abasz** [comment]
I have the same issue ever since. The problem is that the `current_position` values get overiden by the ISR, so when the "E" position is reset by this line `PROCESS_SUBCOMMANDS_NOW(TS(F("G92.9E"), p_float_t(info.current_position.e, 3)));` its set to zero, and when the new line is read from the SD card to the correct value, the difference is extruded. 

I fixed this by changing two lines:

At the begining of the `resume()` function I create a value copy of the `info.current_position` and then I use this copy to reset the "E" position later on instead of the `info.current_position`:

```cpp
void PrintJobRecovery::resume() {
  const uint32_t resume_sdpos = info.sdpos; // Get here before the stepper ISR overwrites it
  const auto current_position_copy = info.current_position;

//...

PROCESS_SUBCOMMANDS_NOW(TS(F("G92.9E"), p_float_t(current_position_copy.e, 3)));

//...
}
```

This fixes this issue. I am not sure if this is the best approach and I not able to test it apart from an Ender 3 (4.2.2 board) but I assume it should work for you too.

**Comment by ThomasToka** [comment]
thx. i fixed this already in my fork and reroute to G27.

https://github.com/ThomasToka/Marlin/commit/64c79750d5fa5d79ff47c32cb0bca1855815528c

**Comment by Abasz** [comment]
> thx. i fixed this already in my fork and reroute to G27.
> 
> [ThomasToka@64c7975](https://github.com/ThomasToka/Marlin/commit/64c79750d5fa5d79ff47c32cb0bca1855815528c)

Thanks, actually re-routing to park is a very good approach, thanks for the suggestion! I added a proper UI feed back and it works great:

```cpp
  gcode.process_subcommands_now(F("G27"));
  ui.pause_show_message(PAUSE_MESSAGE_WAITING);
  wait_for_user_response(0, false);
  info.current_position = current_position_copy;
  ui.reset_status();
  ui.return_to_status();
  planner.synchronize();
```

**Comment by fedorovstas** [comment]
@Abasz it works. Thanks!

**Comment by fedorovstas** [comment]
I have another problem. After enabling PLR in some zone of printing extruder start make ripples on my print. If I disable PLR in firmware everything is OK. I use the same gcode in both cases. 
Video: https://photos.app.goo.gl/wWgAY72Gj1CAwaaf8

**Comment by Abasz** [comment]
> I have another problem. After enabling PLR in some zone of printing extruder start make ripples on my print. If I disable PLR in firmware everything is OK. I use the same gcode in both cases. Video: https://photos.app.goo.gl/wWgAY72Gj1CAwaaf8

Are you using frequent save of the PLR to the SD car? I had similar issues when I had the PLR file to be written in every 5 seconds. The board did not like it especially when there was a lot of very small movement, and the machine hang above a spot for a half a second

**Comment by fedorovstas** [comment]
@Abasz i use SD card. Marlin use POWER_LOSS_MIN_Z_CHANGE to saving PLR file. In default it set 0.05 i increased this value to 0.1 and everything work good. Thank you very much!

**Comment by mechano** [comment]
> @Abasz it works. Thanks!

When will it be released? 
I've same issue on Kingroon KP3S 3.0.
The version KP3S Pro and KP5L hasn't this problem.

It's strange because all of this printers share the same Robin Nano 1.2 clone board with GD32F303 and 2225 drivers.

**Comment by mechano** [comment]
I've compiled a 2.1.2.x-bugfix 20231229 version for an MKS Robin Nano 1.2 and it has the same problem.

**Comment by thisiskeithb** [comment]
> I've compiled a 2.1.2.x-bugfix 20231229 version for an MKS Robin Nano 1.2 and it has the same problem.

See https://github.com/MarlinFirmware/Marlin/pull/26365. The PR / fix has not been merged.

**Comment by ThomasToka** [comment]
additionally i want to say that without my initial commit it is not solved. the additions thinkhead made do not work for me reliably. did not test the last state. but i am sure my fixes in #26365 work and solve all of this.

**Comment by thinkyhead** [comment]
We'll have #26365 merged very soon. Cheers!

**Comment by mechano** [comment]
When will it be merged? 
How can we know it has been merged?

**Comment by ThomasToka** [comment]
> When will it be merged? How can we know it has been merged?

it’s merged already.

https://github.com/MarlinFirmware/Marlin/commit/ab3497161a37ae309e030a23e0f8e3f3eb61daea

**Comment by medisoft** [comment]
> ```c++
>   info.current_position = current_position_copy;
> ```

Thank you, I applied the basic idea of this on Marlin bugfix-2.0.x, and worked like a charm, now I can recover from power loss without a hassle
