### ISSUE TITLE
Z axis move slow and suddenly started to move fast 

### ISSUE THREAD

**Issue by Onabitec** [MarlinFirmware/Marlin#26065]
Pls am very new to 3d printer ... 
Am trying to build my own 3d printer using few electronics knowledge I have .
And have built it but I have problem with it ... I have calibrate my x and y axis but the z axis have been giving me problem.

If I calibrate my z axis now it will work fine ... And z will move slow 
Later the z axis will just started to be moving fast and it wont be accurate again 

Is like is change the setting by itself .

Pls help

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
