### ISSUE TITLE
[BUG] VSCode An error ocurred setting up the container

### ISSUE THREAD

**Issue by liam-clink** [MarlinFirmware/Marlin#26066]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When trying to open the project in a devcontainer in vscode, both using the most recent release commit and the bugfix-2.1.x branch, on linux, there is an error opening the container. When I open the logfile, it says "No dev container config found. No repository connection string found." I haven't modified any files in the cloned repository.

### Bug Timeline

First time setting it up, so don't know

### Expected behavior

I expected the project to open in a devcontainer

### Actual behavior

Instead it can't open

### Steps to Reproduce

Open project in VSCode, let it install wanted extensions, install docker as instructed, enable virtualization for docker, and then attempt to open the project in a DevContainer

### Version of Marlin Firmware

2.1.2.1

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by EvilGremlin** [comment]
afaik, all this new devcontainer stuff is not supported by platformio
so don't use devcontainer (remove plugin and docker)

**Comment by liam-clink** [comment]
Oh, I thought platformio depended on docker. So I can just use platformio and I'll be able to build just fine? Perhaps it would be good to add info about this to the installation guide

**Comment by liam-clink** [comment]
The reason I say this is that current documentation says to use docker

**Comment by EvilGremlin** [comment]
No it doesn't https://marlinfw.org/docs/basics/install_platformio_vscode.html
Though we probably should add note to discard install of recommended plugins.

**Comment by thisiskeithb** [comment]
> Though we probably should add note to discard install of recommended plugins.


Better yet, update [`extensions.json`](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.vscode/extensions.json) to exclude Dev Container and Docker.

**Comment by wilsnat** [comment]
I think it does still recommend Docker. [When you click on the Install button on the top bar](https://marlinfw.org/docs/basics/install.html):
![image](https://github.com/MarlinFirmware/Marlin/assets/5231181/062edd22-0378-412c-9589-5a53d99459a0)
"2.1.x | 8-bit AVR, 32-bit ARM | Install Marlin with PlatformIO in a DevContainer"

**Comment by EvilGremlin** [comment]
This is an option, not recommendation.
Personally, i think mentioning it in docs in any way except "don't go this way" is very premature.

**Comment by classicrocker883** [comment]
it's possible to use docker to develop. but there are several steps in order to do so (outside of VS code). but the easiest way to do something like that is Codespaces.

**Comment by thinkyhead** [comment]
> the easiest way to do something like that is Codespaces

I've lately become kind of fond of these Jupyter thingies at https://colab.research.google.com/ . It would be cool to see one of those set up to build Marlin with some options. Maybe that would be a good option for folks who don't feel like installing anything on their computer, but also don't need something like https://marlin.crc.id.au .

**Comment by quotschmacher** [comment]
@EvilGremlin of course dev Containers work with Platformio and the latest Version just needs some fixes in the Container Definition file. I have it running in a devcontainer.
