### ISSUE TITLE
[BUG] MarlinSerial.cpp:31:15: error: duplicate 'inline'

### ISSUE THREAD

**Issue by dracode** [MarlinFirmware/Marlin#26085]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Compiling Marlin with the Emergency Parser enabled for platform `STM32F103RC_btt_maple`, with toolchain `toolchain-gccarmnoneeabi @ 1.90301.200702 (9.3.1)`, I get the following fatal error:
```
In file included from /home/pi/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/stdlib.h:19,
                 from /home/pi/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/9.3.1/cstdlib:75,
                 from /home/pi/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/9.3.1/stdlib.h:36,
                 from /home/pi/.platformio/packages/framework-arduinoststm32-maple/STM32F1/cores/maple/wirish.h:41,
                 from /home/pi/.platformio/packages/framework-arduinoststm32-maple/STM32F1/cores/maple/Arduino.h:30,
                 from Marlin/src/HAL/STM32F1/../../inc/../HAL/../HAL/STM32F1/../shared/Marduino.h:36,
                 from Marlin/src/HAL/STM32F1/../../inc/../HAL/../HAL/STM32F1/HAL.h:32,
                 from Marlin/src/HAL/STM32F1/../../inc/../HAL/HAL.h:30,
                 from Marlin/src/HAL/STM32F1/../../inc/MarlinConfig.h:31,
                 from Marlin/src/HAL/STM32F1/MarlinSerial.cpp:25:
Marlin/src/HAL/STM32F1/MarlinSerial.cpp:31:15: error: duplicate 'inline'
   31 | static inline __always_inline void my_usart_irq(ring_buffer *rb, ring_buffer *wb, usart_reg_map *regs, MSerialT &serial) {
      |               ^~~~~~~~~~~~~~~
*** [.pio/build/STM32F103RC_btt_maple/src/src/HAL/STM32F1/MarlinSerial.cpp.o] Error 1
```

### Bug Timeline

Unknown

### Expected behavior

I expected the firmware to compile.

### Actual behavior

It threw a fatal error.

### Steps to Reproduce

Not sure what a complete minimum to reproduce is, but here's the factors I think might be involved:
1. Compiling on a Raspberry Pi 4, 64-bit
2. Compiling against a target CPU of `STM32F103RC_btt_maple`
3. Tweaked `~/.platformio/platforms/ststm32/platform.json` in order to allow platformio to install `toolchain-gccarmnoneeabi`; the default version restrictions do not have a candidate that works for Raspberry Pi OS 64-bit. Ended up with `toolchain-gccarmnoneeabi @ 1.90301.200702 (9.3.1)`
4. In `~/Marlin/Marlin/Configuration_adv.h`, enable `EMERGENCY_PARSER`

### Version of Marlin Firmware

2.1.2.1

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Changing line 31 of `Marlin/Marlin/src/HAL/STM32F1/MarlinSerial.cpp` from
```
static inline __always_inline void my_usart_irq
```
to
```
static inline __attribute__((always_inline)) void my_usart_irq
```

Allowed the compilation to complete successfully.

I'm not sure if this would have any adverse effects on any other platforms so I'm hesistant to submit a pull request, but wanted to report the issue so maybe someone more knowledgeable than me can weigh in.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12065022/Configuration.zip)

**Comment by IlyaFarm** [comment]
At ...\Marlin-2.1.2.1\Marlin\src\HAL\DUE\usb\Compiler.h are spelled out what you wrote, and more "__forceinline" which are directly for ARM processors, which are use BTT.
Strings 173-181
