### ISSUE TITLE
[BUG] Edit Screen value drift for negative decimals

### ISSUE THREAD

**Issue by lukasradek** [MarlinFirmware/Marlin#26092]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When opening an edit screen from menu item with negative decimal value, the value increases by one at the last decimal place.

I can be nicely seen when Editing Mesh in menu.
Before opening.
![image](https://github.com/MarlinFirmware/Marlin/assets/16482224/7ed567a0-5cf5-4644-9547-aa1769f9323e)
Open EDIT_ITEM
![image](https://github.com/MarlinFirmware/Marlin/assets/16482224/2aa37609-da38-4585-92aa-8777960ba46a)
No change, just confirm.
![image](https://github.com/MarlinFirmware/Marlin/assets/16482224/8b459a94-70e6-4d83-85aa-a481a19975a4)

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Simulator Windows

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by classicrocker883** [comment]
I think you should really add some more details. like the `Configuration.h` files. what screen are you using?

**Comment by thinkyhead** [comment]
Float imprecision is a bit of a headache. So we have methods to round float values for display, which are supposed to round towards zero. If these methods are forgotten in the display implementation then a value like -0.060000001 will get improperly "rounded" to 0.007.
