### ISSUE TITLE
[BUG] Freeze, reboot and loops after M600

### ISSUE THREAD

**Issue by phobos79** [MarlinFirmware/Marlin#26090]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

During prints with multiple color changes behaviour become random after the loading of the new color.

sometimes goes in loop and repeat the procedure indefinitely
sometime reboot the printer after finish loading the new color
sometime it freeze the printer

it happen only after at least another 2 color changes, no issues in printing 2 colors

it happen on all sd cards i've (all checked and ok)

### Bug Timeline

start with version 2.1.2

### Expected behavior

after m600 the printer resume printing normally

### Steps to Reproduce

prepare a print from usb card with 5-6 color changes.

### Version of Marlin Firmware

2.1.2.1

### Printer model

elegoo neptune 2s

### Electronics

stock

### Add-ons

bltouch sensor

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by phobos79** [comment]
[](url)
[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/12083103/Configurations.zip)

**Comment by diogo580** [comment]
any fixes/workarounds yet?

**Comment by diogo580** [comment]
> [Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/12083103/Configurations.zip)

these configs are broken, between using the wrong type of bed leveling... to missing some code?

**Comment by phobos79** [comment]
Hello,

Leveling is ok, bilinear with 4 points, exactly what i want to have, the bug is the same of 2.1.2, now all is running fine (use 2.1.1.1 with input shaping transplanted
