### ISSUE TITLE
[BUG] Z-Axis moves against each other

### ISSUE THREAD

**Issue by DaMusikant** [MarlinFirmware/Marlin#26101]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi,
I setted up my printer with the specs seen below.
I was in the set up stage and everything seemed to be fine, but out of the blue the two Z-Axis are doing weird stuff.
When I move down, everything is fine.
When I move up, the first 5mm it is fine. But after that, the second Z-Axis decides to go down again. And sticks to it until the steppers are going to be turned off and on again.
I disconnected all hardware from the Axis, swapped the TMC 2130 and swapped the motors.
Except for a fried Mainboard there is only Marlin left over.

What can I have made wrong?

### Version of Marlin Firmware

Marlin 2.1.2.1

### Printer model

Creality-CR10 Max

### Electronics

Bigtreetech SKR V1.3

### Bed Leveling

ABL Linear grid

### Your Slicer

None

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12134198/Configuration.zip)

**Comment by ellensp** [comment]
you have #define E0_AUTO_FAN_PIN 0

This is not a fan pin

pin 0 is the same as P0_00 ie the direction pin for E1 (in your case Z2)

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
