### ISSUE TITLE
[BUG] (The code do not compile with more than one extruder -in branch "bugfix-2.1.x")

### ISSUE THREAD

**Issue by Ari-SSO** [MarlinFirmware/Marlin#26119]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

One variable in not declared in G33.cpp. This happend when you have more than one extruder

"Marlin/src/gcode/calibrate/G33.cpp:685:38: error: 'old_tool_index' was not declared in this scope"

Solved this with PR #26122.

### Bug Timeline

new

### Expected behavior

The code must compile

### Actual behavior

The code do not compile with more than one extruder

### Steps to Reproduce

1) set configuation.h with 2 extruders ("#define EXTRUDER 2" and some other defines related to more than one extruder)
2) Compile the code.

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

HE3D K280

### Electronics

BTT SKR 1.3, BTT TMC2209, BTT TFT35 v3

### Add-ons

2 Extruders

### Bed Leveling

None

### Your Slicer

None

### Host Software

Repetier Host

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12138014/Configuration.zip)

**Comment by thisiskeithb** [comment]
Closing since you've opened a PR:

- https://github.com/MarlinFirmware/Marlin/pull/26118
