### ISSUE TITLE
[BUG] ADVANCED_OK reports "wrong" amount of free command buffers

### ISSUE THREAD

**Issue by rondlh** [MarlinFirmware/Marlin#26128]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Not sure if this is a bug or feature, just found it odd and inefficient.

After looking into the Marlin source code I found the following:
The "ok" (and ADVANCE_OK) acknowledgements are send after a command is being executed, just before the call is being completed. All the work has been done already, just the function calls need to return and buffer status updated. The result is that the reported free buffers will never report the total amount (BUFSIZE), but at max BUFSIZE - 1.
This means that is the clients processes the ADVANDED_OK response it will never use all available command buffers, 1 buffer will always be unused.

The acknowledgement is send in: GCodeQueue::RingBuffer::ok_to_send() located in queue.cpp
which is called from: void GcodeSuite::process_parsed_command(const bool no_ok/*=false*/) in gcode.cpp

"BUFSIZE - length" fee command buffers are reported, but length is still 1 as the buffer administration has not yet been updated.

### Bug Timeline

Don't know

### Expected behavior

Report the full amount of free buffers when the printer is idling and the last command is finished executing.

### Actual behavior

The ADVANCED_OK response never reports the total amount of free command buffers (BUFSIZE), at max it reports BUFSIZE - 1.

### Steps to Reproduce

1. Enabled ADVANCED_OK
2. Send a command like M117 or G90
3. Check the ADVANCED_OK response, which will not report free buffers in the amount set in BUFSIZE (Configuration_Adv.h)

### Version of Marlin Firmware

Lastest bugfix (2023-07-27)

### Printer model

Custom

### Electronics

MKS Monster8 V1.0

### Add-ons

BTT TFT35 V3.0

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Other (explain below)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12179910/Configuration.zip)

**Comment by thinkyhead** [comment]
That may be by design. The original Marlin 1.0 had logic to leave one space free in the buffer under certain conditions. We'd have to look at the historical reasons for why the code is the way it is before assuming that this is a bug.
