### ISSUE TITLE
[BUG] PROBE_OFFSET_WIZARD missing in latest build

### ISSUE THREAD

**Issue by Pyro-Fox** [MarlinFirmware/Marlin#26140]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Even with `#define PROBE_OFFSET_WIZARD` uncommented and using a supported controller (if I followed the variables correctly), the "Z Probe Wizard" menu is missing. Comparing to my other printer which is on a moderately older build of 2.1.x-bugfix, I expected this option to appear under **Motion** > **Z Probe Wizard** and it's just not showing up.

### Bug Timeline

New

### Expected behavior

When `#define PROBE_OFFSET_WIZARD` I should see the menu under Motion

### Actual behavior

No menu shows up

### Steps to Reproduce

Flash firmware, check menus

### Version of Marlin Firmware

Marlin bugfix-2.1.x (Jul 31 2023 22:36:54)

### Printer model

Creality Ender-3 Pro

### Electronics

BTT SKR Mini E3 v2.0, BTT TFT35 E3 v3.0 (in Marlin Mode), BLTouch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

None

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

For the printer where this works fine, I have a BTT SKR v1.3, BTT TFT35 v3.0 (Same LCD as this Ender, but with the knob on the right), and also a BLTouch. From a configuration standpoint, the big difference is in defined LCD. On this printer I've had to use `#define CR10_STOCKDISPLAY` (due to the single EXP connection) whereas on the working one I used `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`.

Config Files:
[MarlineIssue_Pyro-Fox.zip](https://github.com/MarlinFirmware/Marlin/files/12225068/MarlineIssue_Pyro-Fox.zip)

The setting in question (if VSCode is to be trusted, this _should_ have worked):
![image](https://github.com/MarlinFirmware/Marlin/assets/36782094/aba08f67-16f6-444c-9772-5c57432ecb01)
![image](https://github.com/MarlinFirmware/Marlin/assets/36782094/56b57bbb-8660-481d-a366-77a30f7c3783)

The motion menu (on my working printer, the wizard is just below **Stow Z-Probe**):
![359353756_218257054533524_5786034677437991083_n](https://github.com/MarlinFirmware/Marlin/assets/36782094/6f9e3022-ad90-403d-8e85-776342295d13)

**Comment by ellensp** [comment]
Z Probe Wizard is under Configuration| Advanced Settings|Probe Offsets|Z Probe Wizard

This was removed from motion 3 months ago  https://github.com/MarlinFirmware/Marlin/commit/9b883704bc6a9269ec7bfbc1377050d579abcace
