### ISSUE TITLE
flash marlin2.1.x to esp32s3

### ISSUE THREAD

**Issue by yangyuchang** [MarlinFirmware/Marlin#26161]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin2.1. x can run normally on esp32s when I flash Marlin2.1. x to esp32s3. It will make this error
![`FN%T40E5PK HMRI(@~}VCX](https://github.com/MarlinFirmware/Marlin/assets/134859711/ac4c52ea-0325-4d46-bb73-c97ccb5e6d44)

### Version of Marlin Firmware

marlin2.1.x

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin-2.1.2.1.zip](https://github.com/MarlinFirmware/Marlin/files/12271640/Marlin-2.1.2.1.zip)

**Comment by ellensp** [comment]
Clearly not a marlin issue, but a build tools issue.

**Comment by ellensp** [comment]
Attached config files are not a zip file, It is a rar files

**Comment by ellensp** [comment]
Provided Configs are for a BOARD_GEN7_CUSTOM which is a  ATMega644P, not any sort of ESP32

**Comment by ellensp** [comment]
Marlin uses espressif32@2.1.0 released Dec 3, 2020, ie this is rather old

**Comment by yangyuchang** [comment]
@ellensp Thanks for your answer, I will try
