### ISSUE TITLE
[BUG] Temperature.ccp Error with laser safety timeout

### ISSUE THREAD

**Issue by Oskar0186** [MarlinFirmware/Marlin#26178]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Error when compiling  as show below

In file included from Marlin\src\module\../inc/../core/utility.h:26:0,
                 from Marlin\src\module\../inc/MarlinConfig.h:54,
                 from Marlin\src\module\../MarlinCore.h:24,
                 from Marlin\src\module\temperature.cpp:30:
Marlin\src\module\temperature.cpp: In static member function 'static void Temperature::isr()':
Marlin\src\module\temperature.cpp:3264:56: error: 'gcode' was not declared in this scope

### Bug Timeline

I found this error on the 2.0.9.7

### Expected behavior

I expected the firmware to compile

### Actual behavior

It doesn´t compile

### Steps to Reproduce

Just setup a laser engraver parameters and when I compile I get the error

### Version of Marlin Firmware

2.0.9.7

### Printer model

Diy Laser engraver

### Electronics

Ramps 1.4

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Whn I override this "gcode.previous_move_ms" and put a value of 1000 ms it compile 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12346633/Configuration.zip)

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.
