### ISSUE TITLE
[BUG] Unexpected End of Print Behavior

### ISSUE THREAD

**Issue by IlyaFarm** [MarlinFirmware/Marlin#26187]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

At the end of printing from SD card Printer DO things which are not in G-Code.
for example it can extrude plastic, make retraction/deretraction make moves like it make print.

### Bug Timeline

May be new, but I don't thik so.

### Version of Marlin Firmware

Marlin 2.1.2.1

### Printer model

TEVO TARANTULA

### Electronics

BOARD: BTT Octopus V1.1; DRIVERS: TMC2208

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Don't forget to include

- [X] A ZIP file where arise this problem yesterday when printer make firstly retract, then deretract and make big blob of plastic in finished print.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12385259/Configuration.zip)

[TEST.zip](https://github.com/MarlinFirmware/Marlin/files/12385255/TEST.zip)
With this G-code at the end of printing it make retract and fast unretract with addition volume of plastic, result you can see on link below. And all of it although at end of G-Code have not instructions like this, or they are commented.
https://drive.google.com/drive/folders/12ABgLrzGPvWMIjXzi3WUz9QaWVu0dogv?usp=drive_link

### Additional information & file uploads

I've seen this 3 times so far.
erlier I was think it's problem with my SD Card, or errors which occure's wher printer read G-Code from SD, But now I think it's problem with G-Code parser in Marlin.

**Comment by ellensp** [comment]
Please provide:
The configuration files
The example gcode used 
video of what it is doing incorrectly with that gcode

**Comment by IlyaFarm** [comment]
Done ↑
I have not video how this problem exists, but have several photos at google disc
https://drive.google.com/drive/folders/12ABgLrzGPvWMIjXzi3WUz9QaWVu0dogv?usp=drive_link

**Comment by IlyaFarm** [comment]
I think it's after all my cheap SD card, cause if I format it before write new files, everything OK. If not, somthing can go wrong.

**Comment by thisiskeithb** [comment]
> I think it's after all my cheap SD card, cause if I format it before write new files, everything OK.  

Quality SD cards are an important part of the process 👍

**Comment by IlyaFarm** [comment]
Nope problem was not in SD card quality, cause I change SD card source from board to LSD where I use my older good SD card and today it happened again. The printer parked and turned off the print head, before finishing printing.
