### ISSUE TITLE
What is the max safest hardware PWM for laser modulation?

### ISSUE THREAD

**Issue by rajhlinux** [MarlinFirmware/Marlin#26186]
> Hi there, I want to share my observations with the Ender 3 v2 and 500mW laser. I also had a problem with slow PWM. So I did all the tweaks suggested by @zybrek and @vojto1980. Awesome, it worked! Thank you. Nice and precise engraving with the possibility to control the laser power.
> 
> BUT, then I started to burn 15 min program. After ca. 10 mins, something happened and the output from the connector now gives 100% power (24V) all the time. It is no more possible to control this output. I also tried stock firmware, but it still gives 100%.
> 
> For me, it looks, something may be burned in the mainboard. For that "fatal" engraving I had used about 5% of laser power and the mainboard fan (which was connected to the same connector) was not running at all, so maybe it got overheated, I do not know. Fortunately, the other features are OK, I can 3D print as before, only the fan still rotates at full speed now.
> 
> Take care, Michal

You probably burned transistor, higher frequency switching create bigger losses due to capacitance of transistor which leads to more power dissipated, so it could overheat, only way to check this is to desolder transistor and measure it outside circuit.
That disconnected mainboard fun was terrible idea.

_Originally posted by @zbyrek in https://github.com/MarlinFirmware/Marlin/issues/20638#issuecomment-998192138_

What do you mean by "That disconnected mainboard fan was terrible idea." ?

What is the max safe frequency for the Creality 4.2.7 board ?

Also why no one discusses and marlin mention about the max safest frequency until the mosfet burns?

Thanks.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Comment by thisiskeithb** [comment]
Please stop spamming our issue & PR queues. Use the links referenced above for further help.
