### ISSUE TITLE
[BUG] Some frameworks embed fixed strings with directory location

### ISSUE THREAD

**Issue by oliof** [MarlinFirmware/Marlin#26191]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Based on a discussion in the Marlin Discord's #dev-talk channel, some frameworks embed static strings to locations of their file, which uses up flash space (around 20-30 bytes per static string, depending on actual directory location). For my STM32F09USB build, I find 8 strings that have the same longish prefix (/home/hwa/.platformio/packages), which could be reduced. This can be done with the `-ffile-prefix-map` preprocessor directive (see https://reproducible-builds.org/docs/build-path/).

### Expected behavior

Static strings should be shortened to a reasonable amount. 

### Actual behavior

Static strings are not being shortened

### Steps to Reproduce

1. Build a bugfix-2.1.x
```
Marlin$ rm -r ~/.platformio/packages/*
Marlin$ pio run -e BIGTREE_SKR_2_F429_USB  
```
2. Check for strings in your firmware.bin (results may vary per platform and feature set)
```
Marlin$ strings .pio/build/BIGTREE_SKR_2_F429_USB/firmware.bin  | grep packages
/home/hwa/.platformio/packages/framework-arduinoststm32/variants/MARLIN_F4x7Vx/variant.cpp
/home/hwa/.platformio/packages/framework-arduinoststm32/cores/arduino/HardwareSerial.cpp
/home/hwa/.platformio/packages/framework-arduinoststm32/cores/arduino/HardwareTimer.cpp
/home/hwa/.platformio/packages/framework-arduinoststm32/cores/arduino/stm32/usb/usbd_conf.c
/home/hwa/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring_analog.c
/home/hwa/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring_digital.c
/home/hwa/.platformio/packages/framework-arduinoststm32/libraries/SrcWrapper/src/stm32/pinmap.c
Marlin$  
```

### Version of Marlin Firmware

bugfix-2.1.x at commit 5da7143fe5

### Printer model

V-Core V-Minion (cantilever'd cartesian)

### Electronics

Bigtreetech SKR2 with STM32F429 MCU

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

Other (explain below)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

This issue is not Configuration dependent,  nor does it affect runtime or does it get triggered by specific GCode

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12388612/Configuration.zip)

**Comment by thisiskeithb** [comment]
Closing since you've opened a PR.

- https://github.com/MarlinFirmware/Marlin/pull/26192
