### ISSUE TITLE
[BUG] Ender 3 V2 Dacai Display Rendering Bugginess

### ISSUE THREAD

**Issue by notnot-nick** [MarlinFirmware/Marlin#26205]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have tested Marlin latest release and bugfix-2.1.x.

The UI partially displays but is bugged out, however I can navigate the marlin menu.

I am using Marlin UI on an Ender 3 V2 with a V4.2.2. board and STMF103RE processor.

Creality UI is even worse as it has no text at all, but I do not have pictures of it.

### Bug Timeline

Today, when I installed Marlin2.1.x

### Expected behavior

The display works properly, and I see Marlin UI

### Actual behavior

I see Marlin UI but it is fragmented and displayed horribly

### Steps to Reproduce

1. Build Marlin (bugfix-2.1.x)
2. Flash the LCD (dacai) by the private folder in LCD_FILES
3. Flash the printer with the built marlin binary
4. Look at the screen

### Version of Marlin Firmware

Marlin bugfix-2.1.x (Aug 26 2023 00:26:44) 

### Printer model

Creality Ender 3 V2

### Electronics

Stock Ender 3 V2

### Add-ons

CR Touch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/12444594/Marlin.zip)

https://github.com/MarlinFirmware/Marlin/assets/66232265/f1d0ebd8-3909-4674-a300-4588e7054d31

![20230826_003547](https://github.com/MarlinFirmware/Marlin/assets/66232265/df586762-a444-444b-9067-d6910cbd944b)

![20230826_003553](https://github.com/MarlinFirmware/Marlin/assets/66232265/5a4b9f07-7e56-4983-82ba-a1147715f966)

**Comment by ellensp** [comment]
See https://github.com/MarlinFirmware/Configurations/tree/import-2.1.x/config/examples/Creality/Ender-3%20V2

DACAI
✅ Creality UI
✅ MRiscoC Pro UI
✅ JyersUI
✅ MarlinUI Portrait
❌ MarlinUI Landscape
Lack of support for display rotation

You CANNOT use DWIN_MARLINUI_LANDSCAPE on this display
It is a limitation of the firmware in the display.

Your also holding it in Portrait mode so should be using DWIN_MARLINUI_PORTRAIT

<img src="https://orah.co/wp-content/uploads/2021/03/Orientation-difference-1024x721.jpeg">

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
<img src="https://orah.co/wp-content/uploads/2021/03/Orientation-difference-1024x721.jpeg">
