### ISSUE TITLE
Crazy actings with edited bugfix-2.1.x 

### ISSUE THREAD

**Issue by Hoorow** [MarlinFirmware/Marlin#26210]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

problem is printer acting weird at random time examples

- started print and it just started extruding filament without movement (it not supposed to do that)

- started print and nozzle prime codes just starting at Y30~ to Y180~ and it just ends to YMAX

- tried z offset test print and machine just decided to go crash x axis and maybe y or the z 

all of these are not supposed to when i looked from notepad++

### Bug Timeline

after installing servo bltouch and setting it. perhaps some setting changed to

### Expected behavior

I expected it to follow own code

### Actual behavior

it just crashed and goes crazy

### Steps to Reproduce

believe me i cant figure what can do

### Version of Marlin Firmware

bugfix_2_1_x

### Printer model

Creality ender 3 pro

### Electronics

btt skr e3 v3

### Add-ons

just bfptouch and lcd screen timeout(marlinui changed but just for timeout) thing

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

Other (explain below)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.h and _adv.h.zip](https://github.com/MarlinFirmware/Marlin/files/12457876/Configuration.h.and._adv.h.zip)
changes i did to firmware are too much i cant remember but severals are:

- marlinui lcd timeout code changed to 2_1_2_1 one
- pins changed 

for now thats it
other all stuff are stock and stock fan blows air to driver coolers currents are normal
[Z_Offset_Test_11m_0,12mm_250C_ASA_ENDER3PRO.zip](https://github.com/MarlinFirmware/Marlin/files/12457915/Z_Offset_Test_11m_0.12mm_250C_ASA_ENDER3PRO.zip)

**Comment by ellensp** [comment]
You need to provide all modified files so we can reproduce your firmware.

**Comment by Hoorow** [comment]
[pins_BTT_SKR_MINI_E3_V3_0.zip](https://github.com/MarlinFirmware/Marlin/files/12463127/pins_BTT_SKR_MINI_E3_V3_0.zip)
[marlinui.zip](https://github.com/MarlinFirmware/Marlin/files/12463138/marlinui.zip)
okay sorry for that these 2 ares modified and i forgot i tried pronterface and sd card(the one creality gives) run also bought new fast sd card to test it but it still crashed randomly.
1 more modification is mobo case and psu isnt mounted to frame and a wire grounds mobo case and frame coming from psu also V- connected to earth

**Comment by Hoorow** [comment]
and new data i sliced new gcode from new cura with new sdcard but it crashed after stopping itself 
https://drive.google.com/file/d/1-1fSJZec2DNa2UT8-c44tKTmtO0tb6ZQ/view?usp=drivesdk here is the video it must be supposed by firmware but why 
can weird grounding i did causing it? but if it is than why at random time not all time?

**Comment by Hoorow** [comment]
after downloading new version of bugfix 2.1.x, problem solved 
problem cause is using same firmware file for 3 months with 40 reflashing to mobo
