### ISSUE TITLE
Ender-3 V2/S1 Professional Firmware 20230805 (LCD Dimming Option)

### ISSUE THREAD

**Issue by Ducktour** [MarlinFirmware/Marlin#26211]
### Describe the feature you want

The LCD dimming was introduced in Ender-3 V2/S1 Professional Firmware 20230805.

Can this be an optional toggle for those who prefer LCD fully visible at all times?

**Comment by Ducktour** [comment]
Workaround; add M255 S0 in Start G-code

**Comment by thisiskeithb** [comment]
> The LCD dimming was introduced in Ender-3 V2/S1 Professional Firmware 20230805.

Feature requests for @mriscoc's firmware should go to his fork: https://github.com/mriscoc/Ender3V2S1

**Comment by mriscoc** [comment]
With a text editor write a [configuration g-code file](https://github.com/mriscoc/Ender3V2S1/wiki/Configuration-files) with this command:
```gcode
M255 S0 ; disable display dimming 
```
Save it on the SD card and select it in the media menu.
