### ISSUE TITLE
[BUG] `fileprop` not declared in scope (HAS_GCODE_PREVIEW)

### ISSUE THREAD

**Issue by classicrocker883** [MarlinFirmware/Marlin#26212]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

after the recent commit 
 https://github.com/MarlinFirmware/Marlin/commit/8fa6a4da2eebc1dbe120dcac87b159e389e17dc3

where gcode_preview files for PROUI were changed, I get this error

```r
Marlin\src\lcd\e3v2\proui\gcode_preview.cpp: In member function 'void<unnamed struct>::clear()':
Compiling .pio\build\STM32F103RE_creality_maple\src\src\lcd\utf8.cpp.o
Marlin\src\lcd\e3v2\proui\gcode_preview.cpp:66:5: error: 'fileprop' was not declared in this scope     
     fileprop.name[0] = '\0';
     ^~~~~~~~
Marlin\src\lcd\e3v2\proui\gcode_preview.cpp:66:5: note: suggested alternative: 'fileno'
     fileprop.name[0] = '\0';
     ^~~~~~~~
     fileno
*** [.pio\build\STM32F103RE_creality_maple\src\src\lcd\e3v2\proui\gcode_preview.cpp.o] Error 1
```

### Bug Timeline

new, after commit 8fa6a4d

### Expected behavior

should compile successful

### Actual behavior

error during compile

### Steps to Reproduce

1. enable `DWIN_LCD_PROUI`
2. define `HAS_GCODE_PREVIEW 1`
3. build firmware

### Version of Marlin Firmware

bugfix-2.1.x

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
```DIFF
diff --git a/Marlin/src/lcd/e3v2/proui/gcode_preview.cpp b/Marlin/src/lcd/e3v2/proui/gcode_preview.cpp
index 30c6f9f1f6..e6e8384d90 100644
--- a/Marlin/src/lcd/e3v2/proui/gcode_preview.cpp
+++ b/Marlin/src/lcd/e3v2/proui/gcode_preview.cpp
@@ -63,14 +63,14 @@ typedef struct {
   }
 
   void clear() {
-    fileprop.name[0] = '\0';
-    fileprop.thumbstart = 0;
-    fileprop.thumbsize = 0;
-    fileprop.thumbheight = fileprop.thumbwidth = 0;
-    fileprop.time = 0;
-    fileprop.filament = 0;
-    fileprop.layer = 0;
-    fileprop.height = fileprop.width = fileprop.length = 0;
+    name[0] = '\0';
+    thumbstart = 0;
+    thumbsize = 0;
+    thumbheight = thumbwidth = 0;
+    time = 0;
+    filament = 0;
+    layer = 0;
+    height = width = length = 0;
   }
 
 } fileprop_t;

```

**Comment by classicrocker883** [comment]
Update
---

I used CODEGPT and it suggested this fix

```y

  void clear() {
    this->name[0] = '\0';
    this->thumbstart = 0;
    this->thumbsize = 0;
    this->thumbheight = this->thumbwidth = 0;
    this->time = 0;
    this->filament = 0;
    this->layer = 0;
    this->height = this->width = this->length = 0;
  }
```

I since tested and this works.

I'll post a PR.

**Comment by classicrocker883** [comment]
@ellensp yes that fix also works, which is probably even better.

so no your first comment without `this->` works fine, the second with `void setname` can remain no change
