### ISSUE TITLE
[FR] Add common trim_trailing_whitespace and insert_final_newline settings

### ISSUE THREAD

**Issue by vlsi** [MarlinFirmware/Marlin#26219]
### Is your feature request related to a problem? Please describe.

Currently, some of the text files might have trailing whitespace which produces unwanted noise in git diffs.

### Describe the feature you want

I would like to update editorconfig to trim whitespace from all the text files except the ones which are known to have functional trailing whitespace (e.g. markdown)

Suggested change:

```diff
diff --git a/.editorconfig b/.editorconfig
index 57a5b2fb5e..dfea3625af 100644
--- a/.editorconfig
+++ b/.editorconfig
@@ -1,6 +1,10 @@
 # editorconfig.org
 root = true

+[*]
+trim_trailing_whitespace = true
+insert_final_newline = true
+
 [{*.patch,syntax_test_*}]
 trim_trailing_whitespace = false

@@ -8,12 +12,13 @@ trim_trailing_whitespace = false
 charset = utf-8

 [{*.c,*.cpp,*.h,*.ino,Makefile}]
-trim_trailing_whitespace = true
-insert_final_newline = true
 end_of_line = lf
 indent_style = space
 indent_size = 2

+[*.md]
+trim_trailing_whitespace = false
+
 [{*.py}]
 indent_style = space
 indent_size = 4
```

**Comment by ellensp** [comment]
since you have added a pr to add this FR, there is no need to keep this issue open.
