### ISSUE TITLE
[FR] Support for BL Touch PIN27 adapter board

### ISSUE THREAD

**Issue by S4NDER** [MarlinFirmware/Marlin#26234]
### Is your feature request related to a problem? Please describe.

When installing Marlin 2.1.x, BL Touch does not work on a BLTouch 1st gen with PIN27 adapterboard. The pin is not engaging when it needs to.

Tried multiple firmware iterations without success.
Rewiring to the 5 pin header does not resolve my problem.

### Are you looking for hardware support?

Creality Ender 5 Pro, V4.2.2 with 1st gen BL Touch with PIN27 adapterboard

### Describe the feature you want

A way to use the BL Touch 1st gen with adapterboard with Marlin 2.1. x

**Comment by ellensp** [comment]
Marlin already has 
```
//
// Servos
//
#ifndef SERVO0_PIN
  #ifndef HAS_PIN_27_BOARD
    #define SERVO0_PIN                      PB0   // BLTouch OUT
  #else
    #define SERVO0_PIN                      PC6
  #endif
#endif

```

Just add #define HAS_PIN_27_BOARD  to your Configuration.h
