### ISSUE TITLE
[BUG] (bltouch - hotend goes beyond the bed )

### ISSUE THREAD

**Issue by FlyAAM** [MarlinFirmware/Marlin#26250]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

the probe passes through all points of the first row. there is only one (right) dot on the second line. the third does the same and then goes to the right behind the bed.

### Bug Timeline

marlin  2.0.9.7

### Version of Marlin Firmware

2.0.9.7

### Printer model

jgaurora a5, 

### Electronics

board mks gen L v2.1

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I feel like the X axis is going wrong, the coordinates at the table = 1/2 the size of the bed. maybe this is due to the motor driver current - zeroing the coordinates due to braking, I don’t know

**Comment by FlyAAM** [comment]
I feel that the X axis is going astray, the coordinates **when the probe outside the table** = 1/2 the size of the bed. maybe this is due to the motor driver current - zeroing the coordinates due to braking, I don’t know.

**Comment by FlyAAM** [comment]
help me!

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
