### ISSUE TITLE
is it default for delta? 1.1RC1

### ISSUE THREAD

**Issue by delphikwok** [MarlinFirmware/Marlin#2625]
Hi,
I am new to Marlin and I just downloaded 1.1RC1. I am trying to config it for my delta with ramps1.4.
I got a newbie question if the Marlin default for delta? because I can just see options for Corexy and corexz in configuration.h . Thank everyone.

Delphi

**Comment by clefranc** [comment]
@delphikwok You'll find deltas `Configuration.h` and `Configuration_adv.h` in the `Marlin/example_configurations` folder. You need to copy the ones that suit your hardware (or use the generic ones) to the Marlin folder, replacing existing files.

**Comment by delphikwok** [comment]
Thanks clefranc,
It is working now.
Cheers.
