### ISSUE TITLE
Could you add a feature of oil painting printing with HueForge?

### ISSUE THREAD

**Issue by Jimmyjohhny** [MarlinFirmware/Marlin#26252]
### Describe the feature you want

I want to print an oil painting which includes two types of filaments: silk PLA and [matte PLA](https://www.sunlu.com/en-ca/collections/matte-pla). Can somebody help me?

**Comment by EvilGremlin** [comment]
Marlin does support muticolor printing and color mixing.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.
