### ISSUE TITLE
SDcard and LCD config for 1.1RC1?

### ISSUE THREAD

**Issue by delphikwok** [MarlinFirmware/Marlin#2626]
hi,
There were SDcard and LCD config in configuration.h in 1.0.x version but it can not be find in 1.1RC.
Any guide to config the 1.1RC?

Thank a lot.
Delphi

**Comment by GrevanGER** [comment]
There is a section called "LCD and SD support" within the Configuration.h
All you need to do is to delete the // infront of the #define line that matches your hardware.

**Comment by delphikwok** [comment]
thanks GrevanGER,
I have finally find out my LCD is REPRAP_DISCOUNT_SMART_CONTROLLER.
Thanks again. It is working now.
Delphi
