### ISSUE TITLE
[BUG] Random "Endstops" message

### ISSUE THREAD

**Issue by classicrocker883** [MarlinFirmware/Marlin#26276]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Not sure exactly how it came about, I'll try to reproduce it.

So out of nowhere I get a status message on the printers LCD display saying "Endstops &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; chrP" - (it had many spaces inbetween)

I traced it to **module/endstops.cpp** line ~351
```y
void Endstops::event_handler() { ...

    TERN_(HAS_STATUS_MESSAGE,
      ui.status_printf(0,
        F(S_FMT GANG_N_1(NUM_AXES, " %c") " %c"),
        GET_TEXT(MSG_LCD_ENDSTOPS),
        NUM_AXIS_LIST_(chrX, chrY, chrZ, chrI, chrJ, chrK, chrU, chrV, chrW) chrP
      )
    );
```

![Screenshot 2023-09-12 213755](https://github.com/MarlinFirmware/Marlin/assets/18502096/2622e72c-6246-40c7-bf28-cd4337f34281)

as you can see there is some sort of error popping up.

### Bug Timeline

possibly old

### Expected behavior

I'm guessing this should not have popped up??

### Actual behavior

Popped up randomly

### Steps to Reproduce

1. Using JyersUI - may also show up with ProUI
2. Have everything unplugged from the mainboard except power and LCD cable
note: this is probably just a fluke due to everything unplugged. ie: no endstops were being registered.

but seeing the "error-type" in VSCode when hovering over the function in question made me submit this.

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Voxelab Aquila

### Electronics

G32 mainboard

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

[Marlin_Config.zip](https://github.com/MarlinFirmware/Marlin/files/12606034/Marlin_Config.zip)

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by classicrocker883** [comment]
I believe I have traced this to **lcd/marlinui.h** line ~514

the newer version:
```y
  template<typename... Args>
  static void status_printf(int8_t level, FSTR_P const ffmt, Args... more) { status_printf_P(level, FTOP(ffmt), more...); }
```

an older version which didn't show the "error-type"
```y
  static void status_printf(int8_t level, FSTR_P const fmt, ...);
```


edit:

this is why it is showing "error-type"
`void status_printf<Args...>(int8_t level, const FSTR_P ffmt, Args ...more)`

removing the `TERN_` actually got rid of the "error-type", maybe it will fix the random message popping up??

**Comment by thisiskeithb** [comment]
> removing the TERN_ actually got rid of the "error-type", maybe it will fix the random message popping up??

How’d the test go?

**Comment by classicrocker883** [comment]
> > removing the TERN_ actually got rid of the "error-type", maybe it will fix the random message popping up??
> 
> How’d the test go?

I haven't actually delved into this issue. it wasn't easy recreating the message for a benchmark. it could have come and gone for any other reason.  I haven't had it pop up since, but what remains is the "error-type" in the `status_printf`. however that doesn't appear to cause an actual issue...maybe??

**Comment by classicrocker883** [comment]
I wonder would changing the following have any benefit, perhaps such a complicated code it causes the issue "behind the scenes" ....
```diff
-     ui.status_printf(0,
-       F(S_FMT GANG_N_1(NUM_AXES, " %c") " %c"),
        GET_TEXT(MSG_LCD_ENDSTOPS),
        NUM_AXIS_LIST_(chrX, chrY, chrZ, chrI, chrJ, chrK, chrU, chrV, chrW) chrP
      );

+      FTOP(S_FMT GANG_N_1(NUM_AXES, " %c") " %c"),
+      FPSTR(S_FMT GANG_N_1(NUM_AXES, " %c") " %c"),

+     ui.status_printf_P(0,
```
the above code isn't verbatim, just as an example to replace `F` with `FTOP` or `FPSTR`,  if with `FTOP`, then this must be `ui.status_printf_P`

**Comment by classicrocker883** [comment]
or what about something like this?
```y
ui.set_status_and_level(MString<30>(F(S_FMT GANG_N_1(NUM_AXES, " %c") " %c"), GET_TEXT_F(MSG_LCD_ENDSTOPS),NUM_AXIS_LIST_(chrX, chrY, chrZ, chrI, chrJ, chrK, chrU, chrV, chrW) chrP));
```
