### ISSUE TITLE
Ability to have additional Z-homing probes (for less accurate probes) [FR] (feature summary)

### ISSUE THREAD

**Issue by moswald14** [MarlinFirmware/Marlin#26272]
### Is your feature request related to a problem? Please describe.

I have a knock off BLTouch and I'm always having to readjust my Z-offset for each print. I believe this is because It gets an inaccurate home position from the only 2 probes it makes when it homes.

### Describe the feature you want

Add an int to the code that dictates the number of homing probes and extra probes it does and take the average, for a more accurate home.

**Comment by classicrocker883** [comment]
this may be an issue with the probe itself.

but if you wanted to increase the number of probes, go to Configuration.h and look for `MULTIPLE_PROBING`

Uncomment that and change it to a number more than 2, also you can try defining `EXTRA_PROBING`

you can try doing M48 and see what the result is. do a test using 3 or 4 probes, then one with 7 or 10. 
you should not have a number greater than 0.01 deviation.

I would try adding some kind of plastic safe liquid lubricant to the probe, perhaps something is getting stuck giving wrong results. or replace the plastic tip.

**Comment by moswald14** [comment]
thanks for the tip, but I think I figured it out. the probe gives inaccurate results when the hotend is being heated. I have emi all over my printer. homing before heating the nozzle but after heating the bed gives me constant accurate results

**Comment by ellensp** [comment]
Already implemented
