### ISSUE TITLE
[BUG] Feedrate inaccuracy with G1 G2 and G3 for arc motion

### ISSUE THREAD

**Issue by rnj1** [MarlinFirmware/Marlin#26279]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description
When using G2/G3, the feedrate is oscillating during the arc ~ +/- 3%. For testing I tried, a full arc with verious speeds and radius (0.5-10mm) e.g. "G2 I2 J0" and speeds (60-3000mm/min), as I tried many different configurations (MIN_CIRCLE_SEGMENTS(0-0.1), MAX_ARC_SEGMENT_MM (0.1- 1), N_ARC_CORRECTION (25-72), MIN_CIRCLE_SEGMENTS(8-72+ commented)) always with the same behaviour. 
The issue with the G2/G3 arc feedrate implementation is still not fixed. With all settings I tried the feedrate overshoots leading to artefacts when printing. The feedrate is only computed correctly when only one axis moves.
I analyzed the step/dir outputs of my DUE board with a scope and Matlab and it shows an cyclic half-wave overshoot of ~3%: 
![Feedrate_G2_Marlin2 1xBGFX_](https://github.com/MarlinFirmware/Marlin/assets/61346597/30d02e7f-efe7-4769-994e-db1e5a06ac35)
When printing smaller arcs (here 0.5-10mm), the sudden accerlation (red circles) get's quite visible (up to ~0.1mm displacement):
![10mms_G2a](https://github.com/MarlinFirmware/Marlin/assets/61346597/ba738491-8712-4de3-bab3-f512511a959c)
For both G1 & G2, the speed accuracy for a arc motion seem to be about +/- 3%:
![Feedrate_G2_Marlin2 1xbgfx](https://github.com/MarlinFirmware/Marlin/assets/61346597/0b52d9eb-af51-495c-8c47-b1eb9f65351e)
![Feedrate_arc_withG1_2 1xbgfx](https://github.com/MarlinFirmware/Marlin/assets/61346597/f77f54ed-56dd-4878-a949-8b554e396270)

The acutal trajectory seems to be fine:
![XYpos_10mms_R2230914-110704](https://github.com/MarlinFirmware/Marlin/assets/61346597/c862cfda-23b1-4013-8faf-8033bfb0bd45)

### Bug Timeline

At least Marlin 2.0 in 2019?

### Expected behavior

The tool set speed during G1, or  G2/G3 arc motion should stay perfectly constant

### Actual behavior

During arc motion, the toolspeed is oscillating +/-3%:
![Feedrate_G2_Marlin2 1 2 1](https://github.com/MarlinFirmware/Marlin/assets/61346597/5aca3ce8-72bd-4faa-a089-183ef1a8cd95)

### Steps to Reproduce

[CfgBgfx.zip](https://github.com/MarlinFirmware/Marlin/files/12607387/CfgBgfx.zip)

### Version of Marlin Firmware

2.1.2.1 and 'FIRMWARE_NAME:Marlin bugfix-2.1.x (Sep 14 2023 10:48:50) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff↵'

### Printer model

Custom

### Electronics

DUE with RAMPS-FD-V2

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by DerAndere1** [comment]
- Is the speed accuracy better when moving at lower feedrate or when you increase DEFAULT_ACCELERATION  DEFAULT_TRAVEL_ACCELERATION  and DEFAULT_MAX_ACCELERATION for the axes involved?

**Comment by rnj1** [comment]
I tried speeds from 1mm/s to 50mm/s and with higher speeds the relative speed error stay the same (2-3%). I also reduced the accerlation from 1000mm/s^2 to 500mm/s^2 which looked the same (didn't make a scope measurment though and also I didn't try less yet) and also tested S-curve accelration which had, for printing, the same appearance.
Here the same Trajectory with G2 at 5mm/s and 25mm/s. It's 2-3% (+/-0.1-0.15mm/s) @5mm/s and 3.2% (+/- 0.8mm/s) @ 25mm/s.
![5mms](https://github.com/MarlinFirmware/Marlin/assets/61346597/d4ccc4cc-9611-406f-ba0e-7071bd6543de)
![25mms](https://github.com/MarlinFirmware/Marlin/assets/61346597/e28bd3b6-4e80-4274-a596-c11901a6fd7b)

For sure, increasing the trajectory radius at the same speed reduces the error amplitude (which can also be seen in the picture)

**Comment by ellensp** [comment]
Have yo actually try bugfix?
Many bug fixes where not put into 2.1.2.1, only a select few

**Comment by rnj1** [comment]
I tried also yesterday's bugfix (Marlin bugfix-2.1.x (Sep 14 2023 10:48:50)), which does have the same issue (In the first few charts with "BGFX" in the title, it's a measurement with that bugfix version. 

Initially I thought this issue is related to G2/G3, but G1 with like 30-100 (similar segment size) points per arc is doing exactly the same.

**Comment by stef-evotech** [comment]
Hi!

I observed some similar issues, could you report your Jerk/Acceleration values? Such issues can also be due to older Stepper-Drivers like A4988 because they sometimes have a torque-irregularity. Also I noticed some weird bumps when using newer Trinamic-drivers with high microstepping and microstep-interpolation on!

Also what's quite simliar looking are backlash-problems, but i figure you checked your pulleys/belts etc,...

Cheers

**Comment by rnj1** [comment]
The charts were extracted from the scope measurement of the output of the 32bit microcontroller without any driver connected. I used the standard settings for jerk as written in my config. For accelereation I tried various values. Also my printer has 3x precision linear drives with optical encoders (JennyScience Lxs / XVi75V8) without any backlash...
To me it's a numeric bug of Marlin

**Comment by stef-evotech** [comment]
I had a quick look at your config. Acceleration/Jerk seems reasonable, what seems off - at least in the version you uploaded - is that CLASSIC_JERK is disabled so in this configuration you may be actually using JUNCTION_DEVIATION. Please check if that is still the case.

**Comment by XDA-Bam** [comment]
> I had a quick look at your config. Acceleration/Jerk seems reasonable, what seems off - at least in the version you uploaded - is that CLASSIC_JERK is disabled so in this configuration you may be actually using JUNCTION_DEVIATION. Please check if that is still the case.

Agree. This may be an artifact of the default JD implementation. @rnj1 Please be so kind and re-test using `CLASSIC_JERK`. If that solves it, it would be nice to see if running JD again but with the additional config entry `#define JD_USE_LOOKUP_TABLE` also gets rid of the fluctuation. If `CLASSIC_JERK` doesn't solve it, it would be time to investigate the code for G2/G3.
