### ISSUE TITLE
[FR] Move bed to centered or back position after bed leveling

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#26284]
### Is your feature request related to a problem? Please describe.

After bed leveling bed remains in place, that could be front position, closing access to screen/knob. For example on my printer with custom long bed:

![image](https://github.com/MarlinFirmware/Marlin/assets/8691781/a3c71c0a-3273-4b41-98fd-9314471c2d33)

### Describe the feature you want

I would like to bed moving to more back position. For me hardcoded middle position is good, but it could configurable like Z_AFTER_PROBING, e.g. Y_AFTER_PROBING.

**Comment by ellensp** [comment]
We already have something that can do this

```
/**
 * Commands to execute at the end of G29 probing.
 * Useful to retract or move the Z probe out of the way.
 */
//#define Z_PROBE_END_SCRIPT "G1 Z10 F12000\nG1 X15 Y330\nG1 Z0.5\nG1 Z10"

```

So enable this and set it to do what you want

**Comment by vovodroid** [comment]
Well, it could be more easy if both defines would be placed together.
