### ISSUE TITLE
[BUG] Code of Conduct refers to an invalid email

### ISSUE THREAD

**Issue by vlsi** [MarlinFirmware/Marlin#26285]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

[Code of conduct](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/code_of_conduct.md#enforcement) refers to marlinfirmware@github.com which does not work.

### Expected behavior

Contact information in code of conduct should be valid

### Version of Marlin Firmware

n/a

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
Thanks for the report! This has been updated in https://github.com/MarlinFirmware/Marlin/commit/45a6e9614e671ed97a1de33a966e25cd28329a14
