### ISSUE TITLE
[FR] SWITCHING_NOZZLE - distinct servo angles

### ISSUE THREAD

**Issue by rubienr** [MarlinFirmware/Marlin#26302]
Having a [switching nozzle](https://github.com/rubienr/cad/blob/master/creality-ender-5-plus/switching-nozzle-dual/00-v1.x.stl) setup (two mirrored nozzles) the lifting servos need to move independently: subsequent + in different directions.

![image](https://github.com/MarlinFirmware/Marlin/assets/7566204/c030a89d-4060-4cf2-8fa1-14fdd06cf777)

With the above setup the hotfix is to connect both servos to one and the same servo signal. Since the mechanics is mirrored this works but has a disadvantage, namely the switching process is not symmetric. 

Example: with `TOOLCHANGE_NO_RETURN` disabled if 
1. `T0` switches to `T1`, first the servo is actuated, then the tool moves in X/Y direction
2. `T1` switches to `T0`, first the tool moves in X/Y, then the servo is actuated

### Are you looking for hardware support?

No

### Describe the feature you want

The `SWITCHING_NOZZLE` configuration section should allow to define distinct angles each servo.

Example:
```
//#define SWITCHING_NOZZLE
#if ENABLED(SWITCHING_NOZZLE)
  #define SWITCHING_NOZZLE_SERVO_NR 0
  //#define SWITCHING_NOZZLE_E1_SERVO_NR 1
  #define SWITCHING_NOZZLE_SERVO_ANGLES { { 0, 90 }, { 90, 0 } } // distinct angles
  #define SWITCHING_NOZZLE_SERVO_DWELL 2500
#endif 
```

### Additional context

Probably related to #23120 soft

**Comment by thisiskeithb** [comment]
Closing since you've opened a PR.
