### ISSUE TITLE
custom MACHINE

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#2632]
in 6effa6f195 = 1.1 RC1
shouldn't this in config....h
line 51  // #define CUSTOM_MENDEL_NAME "This Mendel"
be 
line 51 // #define CUSTOM_MACHINE_NAME "This Machine"

it was changed long ago in dev

also ref in language.h

**Comment by KiteLab** [comment]
Would you please be so kind to look into the right branch.

**Comment by ruggb** [comment]
I would if I could figure this out

latest commit 6effa6f195
@Wackerbarth Wackerbarth authored 4 days ago 
what does this mean?
That is what I see when I clk on CODE on this page.
and it says BRANCH: RELEASE
help me out!

OK I think I found it - the last time I used a ...\tree.. url it told me it couldn't find it.
sorry to bother u

**Comment by Wackerbarth** [comment]
Yes, it is the RELEASE (1.0.2 was the last RELEASED) RC is only a CANDIDATE for the NEXT release.
You can access any labeled branch from the code page.
