### ISSUE TITLE
[BUG] Kingroon KP3S 3.0 SD print broken

### ISSUE THREAD

**Issue by rofin74** [MarlinFirmware/Marlin#26325]
### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by qadws007** [comment]
+1,me too.
My TFT24 temperature not update。

**Comment by smhanov** [comment]
After loading marlin built from the 2.1.2 tag, with the KPS3 Config (same tag):
1. I click on the SD card to select a file. -- shows file list
2. I click on file twice -- it shows confirmation screen.
3. I click the checkmark

Result: screen is partially cleared for a second, showing only the lower half of the checkmark and X. Then the printer returns to the home screen and apparently does nothing. After this I click on the sdcard again and it shows no files. It will show no files until SD card is re-inserted.

Confirmed it works fine with marlin tag 2.1.1 release.
