### ISSUE TITLE
thermal runaway protection

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#2633]
in 6effa6f = 1.1 RC1
Maybe I don't understand the process, but wasn't this suppose to be fixed in 1.0.2 (#2623) and propagated to 1.1 RC1.
It does not work in 1.1.RC1 the same as it didn't b4 it was fixed in 1.0.2

**Comment by Wackerbarth** [comment]
6effa6f is the OLD (1.0.2) RELEASE  -- Please refer to the RC branch (currently 2e392fe) for 1.1 RC1

**Comment by ruggb** [comment]
hey - that is what I copied directly from the code page

latest commit 6effa6f195
@Wackerbarth Wackerbarth authored 4 days ago 

so where do u get ur number?

OK I think I found the right place
sorry to trouble u
but the last time I clkd on a ...\tree... url it said it couldn't find it.
