### ISSUE TITLE
5 axis with rotation fails to compile.

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#26335]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

```CPP
Marlin/src/module/motion.cpp:1164:83: error: 'const xyze_pos_t {aka const struct XYZEval<float>}' has no member named 'k'
           distance_sqr = ROTATIONAL_AXIS_GANG(sq(diff.i), + sq(diff.j), + sq(diff.k), + sq(diff.u), + sq(diff.v), + sq(diff.w));
                                                                                   ^
```

### Expected behavior

It should build

### Actual behavior

It has a compile error.

### Steps to Reproduce

1. Download https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/linear_axes/RAMPS%205%20LINEAR_AXES
2. replace default Config files with these configs
3. add   #define AXIS4_ROTATES to Configuration.h 
4. build

### Version of Marlin Firmware

Bugfix-2.1.x

### Electronics

RAMPS

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12874674/Configuration.zip)

Error comes from types.h, it has this code 

```CPP
#if HAS_ROTATIONAL_AXES
  #define ROTATIONAL_AXIS_GANG(V...) GANG_N(ROTATIONAL_AXES, V)
#endif

```

But this define is not called as HAS_ROTATIONAL_AXES is not set yet

#If HAS_ROTATIONAL_AXES is also used in Configuration_adv.h 
But is also not working as it is not set yet.

HAS_ROTATIONAL_AXES is set in inc/Conditionals_post.h to late.

### related
https://github.com/MarlinFirmware/Marlin/issues/26220
https://reprap.org/forum/read.php?146,893571,893596#msg-893596

**Comment by DerAndere1** [comment]
This was first reported in https://github.com/MarlinFirmware/Marlin/issues/26002 and should be fixed with either of the pull requests linked above.
