### ISSUE TITLE
question re motherboard

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#2634]
in 1.1RC1
why is this config option in pins.h
line 544 // uncomment one of the following lines for RAMPS v1.3 or v1.0, comment both for v1.2 or 1.1
line 545 // #define RAMPS_V_1_3
line 546 // #define RAMPS_V_1_0

my MB is RAMPS1.4 == RAMPS1.3
since this isn't in config.h, I never changed it, so it is in conflict with my MB define
If it is needed shouldn't it be in config....h?
if not, shouldn't it be gone?

Since the only appearance of "RAMPS_V_1_3" is on line 545 of pins.h, I guess it needs to be gone.

**Comment by KiteLab** [comment]
You are referring to 'release' or older.

**Comment by ruggb** [comment]
why do u ask?
doesn't 1.1 RC1 define it?
how about 
latest commit 6effa6f195
@Wackerbarth Wackerbarth authored 4 days ago

**Comment by Wackerbarth** [comment]
I REPEAT `6effa6f` IS NOT 1.1 RC1. It is a derivative of 1.0.2.

**Comment by ruggb** [comment]
OK I think I found the right place
sorry to trouble u
but the last time I clkd on a ...\tree... url it said it couldn't find it.
