### ISSUE TITLE
[BUG] Vertex K8400 cooling fan does not work

### ISSUE THREAD

**Issue by Puch-tdi** [MarlinFirmware/Marlin#26358]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Vertex K8400 cooling fan does not work on non of the Marlin V2.x.x versions.
The pins_K8400.h have no configuration for the FAN_PIN.
First i thought my board was defective so i reprogrammed with Marlin V1.4 and it worked again.
After V2.1.1 and 2.1.2.1 trials still not working so i went inspection some files.
If you follow through the files it points to pins_3DRAG.h wich point again to pins_RAMPS.h
There i saw the FAN_PIN is 4 (wich could be correct for a RAMPS board, i don't know for sure) but the K8400 uses pin 8 for the fan.
So i went peeking in the pins_K8600.h and pins_K8800.h files and saw they have a seperate rule wich point to pin 8 for the cooling fan.
After writing this rule to the pins_K8400.h file it finally works correctly.

### Bug Timeline

On all V2.x.x marlin versions

### Expected behavior

the cooling fan should be started

### Actual behavior

nothing happend

### Steps to Reproduce

writing the correct pins file

### Version of Marlin Firmware

2.1.1

### Printer model

Vertex K8400

### Electronics

Stock

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I think it would be clear, i only adjusted pins_K8400.h file for this.
This is the original file with one minor adjustment to get it working under the "Heaters / Fans" section
[pins_K8400.zip](https://github.com/MarlinFirmware/Marlin/files/13060539/pins_K8400.zip)

**Comment by ellensp** [comment]
FAN_PIN no longer exists. replaced with FAN0_PIN  in bugfix

Please attach config files, as requested

**Comment by ellensp** [comment]
There are two example configs for this machine [Dual-head](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Velleman/K8400/Dual-head) and [Single-head](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Velleman/K8400/Single-head)

## Single head
 
pins_3DRAG.h  sets: 
#define MOSFET_B_PIN                           8

pins_RAMPS.h  sets:
#define FAN0_PIN                MOSFET_B_PIN

## Dual-head

pins_3DRAG.h  sets: 
#define MOSFET_B_PIN                           8
#define MOSFET_C_PIN                           9

pins_RAMPS.h  sets: 
#define HEATER_1_PIN       MOSFET_B_PIN
#define FAN0_PIN                MOSFET_C_PIN

Then pins_K8400.h has:
#undef HEATER_1_PIN
#define HEATER_1_PIN                          11

## Summery 

So Single head  fan0 is on 8
Dual head fan0 ends up on 9

## Questions

So is it dual head configuration your referring to? 

Do you actually have a dual head, or did you use a dual head config on a single head machine?

**Comment by Puch-tdi** [comment]
Sorry, forgot to mention that.
I do have dual heads, but the mainbord only have one output for the cooling fan and one output for heatbreak fan.
I did build my own casing but on the original K8400 i onces bought the fans were allready wired parallel for the use of extra fans (as explained by the original installation manual).
So even with dual heads the heatbreak fan is pin 2 and the cooling fan is pin 8

My last firmware change is with V2.1.1 and there it works with FAN_PIN perfectly, i shall adapt the V2.1.2.1 to FAN0_PIN and see if that is also working

**Comment by Puch-tdi** [comment]
[config.zip](https://github.com/MarlinFirmware/Marlin/files/13060791/config.zip)
Hereby the config and config adv files

**Comment by ellensp** [comment]
I agree this should be added, created a pr to fix it.
