### ISSUE TITLE
[BUG] G28 O consider position trusted after disabling steppers

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#26377]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Currently `G28 O` do not perform homing after `M84` disable steppers, and considers that axes are trusted, though they could be moved. I guess disabling steppers by `M84` or after timeout should 'untrust' the corresponding axis position. 

### Bug Timeline

On the Big Bang

### Version of Marlin Firmware

2.1

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
M28 - Start SD write
I suspect you want  G28 - Auto Home

**Comment by ellensp** [comment]
What controller?
Does it have shared enable lines?
Does it have any enable  lines?

**Comment by vovodroid** [comment]
Here is my printer https://github.com/MarlinFirmware/Configurations/tree/import-2.1.x/config/examples/BIQU/B1%20SE

It uses TMC2208 (actually TMC2225), but I thing that turning off motor should always untrust axis position.

**Comment by ellensp** [comment]
needed details to attempt to locate block of code responsible.

Shared enables is different code from individual enables.
if it does not have enable lines it cannot disable them...

Your controller, BOARD_BTT_SKR_V2_0_REV_B, has individual enable pins for each stepper driver.

**Comment by vovodroid** [comment]
I don't really know about lines and so on. I suggest that M84 or timeout expiration just clear some "trusted" bits or something like that.

**Comment by ellensp** [comment]
Confirmed issue is present in simulator

**Comment by ellensp** [comment]
code has       ```if (TEST(b, a) && TERN(HOME_AFTER_DEACTIVATE, axis_is_trusted, axis_was_homed)(a))```
 
It G28 O is checking axis_was_homed, which is still true
axis_is_trusted is disabled as expected.

You require #define HOME_AFTER_DEACTIVATE to get G28 O to check axis_is_trusted

**Comment by vovodroid** [comment]
Wouldn't it be reasonable to enable this by default?

**Comment by thisiskeithb** [comment]
> Wouldn't it be reasonable to enable this by default?

No. `HOME_AFTER_DEACTIVATE` is annoying if you don’t want to home, so that’s why it’s an option.
