### ISSUE TITLE
[BUG] (error in function 'void flashFirmware(int16_t)'  --> error: 'hal' was not declared in this scope)

### ISSUE THREAD

**Issue by MrRadicalsheep** [MarlinFirmware/Marlin#26375]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Error when compiling in VSC with PlatformIO. 
Setup: Chrion, I am modifying to use a BigTreeTech SK3. I am working on the firmware to work with my TH3D EZABL and TH3D Display. As I compiled with PlatformIO there was an error.

Error details here:
Marlin\src\HAL\STM32\HAL.cpp: In function 'void flashFirmware(int16_t)':
Marlin\src\HAL\STM32\HAL.cpp:149:42: error: 'hal' was not declared in this scope
  149 | WEAK void flashFirmware(const int16_t) { hal.reboot(); }
      |                                          ^~~
*** [.pio\build\STM32H743Vx_btt\src\src\HAL\STM32\HAL.cpp.o] Error 1

I attached my entire firmware folder below just in case anyone wants or can give this try or has any ideas on what to do.

When opening the file (Marlin/src/HAL/STM32/HAL.cpp) it links to this; I'm unsure if this line is critical or can be commented out.
148      // Reset the system to initiate a firmware flash
149      WEAK void flashFirmware(const int16_t) { hal.reboot(); }

### Bug Timeline

2023/10/27

### Expected behavior

for HAL.cpp to compile

### Actual behavior

Marlin\src\HAL\STM32\HAL.cpp: In function 'void flashFirmware(int16_t)':
Marlin\src\HAL\STM32\HAL.cpp:149:42: error: 'hal' was not declared in this scope
  149 | WEAK void flashFirmware(const int16_t) { hal.reboot(); }
      |                                          ^~~
*** [.pio\build\STM32H743Vx_btt\src\src\HAL\STM32\HAL.cpp.o] Error 1his scope

### Steps to Reproduce

I don't know :(
just try to build with the attached firmware file in platformio.ini as the project in PlatformIO

### Version of Marlin Firmware

2

### Printer model

Chiron

### Electronics

BTT SKR 3

### Bed Leveling

ABL Linear grid

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Firmware.zip](https://github.com/MarlinFirmware/Marlin/files/13194241/Firmware.zip)

**Comment by thisiskeithb** [comment]
You'll need to contact TH3D since the provided configs/firmware build is not stock Marlin.
