### ISSUE TITLE
[BUG] [To verify] pins_CREALITY_F401.h (CR4NS200141C13) might be wrong

### ISSUE THREAD

**Issue by EvilGremlin** [MarlinFirmware/Marlin#26372]
User have CR4NS200141C13 and built BOARD_CREALITY_V24S1_301F4 and everything work fine, homing with bltouch. Which shouldn't be possible as servo_pin is different, among other things. 

### Version of Marlin Firmware
bugfix-2.1.x

**Comment by BeastCrawler** [comment]
Hello, here are the Config files and the compiled .bin file for the firmware I'm using. I'm sorry that I don't yet have a picture of my motherboard. I will get a good one soon. Just to be clear, the source code files I used were downloaded from https://github.com/mriscoc/Ender3V2S1/releases/tag/20230904. Also, the Config.h and the Config_adv.h were generated using the "Professional Firmware Configurator" using these settings:

Ender3S1-------------------------------------------------------(Printer)
301F4-----------------------------------------------------------(Board)
BLT (With UBL unchecked)-------------------------------------(Leveling)
TJC  -------------------------------------------------------------(Display)
T13--------------------------------------------------------------(Thermistor)
LA (Without Any other extra features, e.g., MPC or IS.)-------(Features)

[Bin file.zip](https://github.com/MarlinFirmware/Marlin/files/13194803/Bin.file.zip)
[Config Files.zip](https://github.com/MarlinFirmware/Marlin/files/13194797/Config.Files.zip)

**Comment by mriscoc** [comment]
Only to note that there is another board with similar name but with other pin configuration: https://github.com/MarlinFirmware/Marlin/pull/27003
