### ISSUE TITLE
MKS Robin pro defiition is missing pins for WIFI module

### ISSUE THREAD

**Issue by Lumicrro** [MarlinFirmware/Marlin#26382]
These lines need to be added to file "pin_MKSROBIN_PRO.h"

//
// MKS_WIFI pins
//
  #define WIFI_IO0_PIN                      PB11
  #define WIFI_IO1_PIN                      PC7
  #define WIFI_RESET_PIN                    PA5

**Comment by ellensp** [comment]
are you sure about WIFI_IO0_PIN  ?  

PB11 is RXD0   which is already used

The wifi block is as follows.

![wifi](https://github.com/MarlinFirmware/Marlin/assets/530024/9099ab14-f038-4165-bc2c-e52f0fa93e42)

But that is wired like so.

![wifi2](https://github.com/MarlinFirmware/Marlin/assets/530024/318eba40-3c1d-47ce-8db0-f7d38b75db71)

So the wifi is really using uart 1
But USB is using uart 0 wich is in conflict with the WIFI_IO0_PIN you defined.

From the schematic, this board has WIFI_IO0 tied high, not software controllable.

**Comment by Lumicrro** [comment]
Correct, it is not used.

But then the wifi init code needs to be checked as I get an error in "wifi_module.cpp" saying "WIFI_IO0_PIN" is not defined.

void mks_esp_wifi_init() {
  wifi_link_state = WIFI_NOT_CONFIG;
  SET_OUTPUT(WIFI_RESET_PIN);
  WIFI_SET();
  SET_OUTPUT(WIFI_IO1_PIN);
  SET_INPUT_PULLUP(WIFI_IO0_PIN);

**Comment by Lumicrro** [comment]
I just did a test with 
#define WIFI_IO0_PIN -1

and it works, Marlin compiles well and WIFI module is working.

**Comment by thisiskeithb** [comment]
Fixed in #26823
