### ISSUE TITLE
[BUG] Delta X/Y movement broken

### ISSUE THREAD

**Issue by avionix-g** [MarlinFirmware/Marlin#26383]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

My delta printer has a manually-deployed probe. [PR #26297](https://github.com/MarlinFirmware/Marlin/pull/26297) introduced a change that prevents my printer from moving on X and Y, though pure Z movement works correctly. 

In `Motion > Move Axis`:
- Z movement works mostly as expected, moving all 3 axes equally up/down
  - Z movement seems to be less than commanded. Z travel bottoms out at Z = 0.00 several cm above the bed.
- Any X or Y movement moves all 3 axes equally down until the printhead hits the bed

Possibly relevant Configuration.h settings:
```h
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define FIX_MOUNTED_PROBE
```

Reverting f7a3172c20cfed3178ab9ab099ff386f61560ad9 causes the problem to disappear.

[config.zip](https://github.com/MarlinFirmware/Marlin/files/13224758/config.zip)

### Bug Timeline

Introduced by f7a3172c20cfed3178ab9ab099ff386f61560ad9

### Expected behavior

I expected the printer to move the X and Y axes as commanded.

### Actual behavior

It homed straight down (without moving left or right) until it crashed into the bed.

### Version of Marlin Firmware

bugfix-2.1.x (24cf29b6a8e9f5e3cd37c4160a20b0a75ff04ad5)

### Printer model

Anycubic Kossel Linear+

### Electronics

MKS Eagle mainboard

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
@Bob-the-Kuhn may have some ideas.
