### ISSUE TITLE
[FR] Combined LINEAR and BILINEAR modes.

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#26385]
### Describe the feature you want

While AUTO_BED_LEVELING_LINEAR can compensate bed tilt, and AUTO_BED_LEVELING_BILINEAR can compensate uneven bed, why not combine both of them and get tilted, but not distorted model:

![image](https://github.com/MarlinFirmware/Marlin/assets/8691781/f5816cf9-c54b-4045-af18-a52d947c47f9)

**Comment by EvilGremlin** [comment]
UBL doing exactly that for many years, please read docs first before openeing issues.

**Comment by vovodroid** [comment]
If you are talking about G29 G, it's not clear that it combines both modes. Anyway UBL is much more complex for setup and usage than just to issue G29 commmand like for linear or bilinear.

**Comment by EvilGremlin** [comment]
J, not G. Well documented, what exacty is unclear?
And no, UBL is not more complex. Anyway, this already exist in UBLso redundant features wont be added to bilinerar.
