### ISSUE TITLE
[BUG] SSD1306 I2C display does not work

### ISSUE THREAD

**Issue by jonathanmlang** [MarlinFirmware/Marlin#26389]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I uncommented #define MKS_12864OLED_SSD1306 in configuration.h
Added pin definitions in the board file, pins_CREALITY_V4.h
#define I2C_SCL_PIN                           PB10
#define I2C_SDA_PIN                          PB11

Compiled and flahsed fine,
Blank display.

### Bug Timeline

Not sure

### Expected behavior

Expected the display to show the marlin interface

### Actual behavior

Nothing happens.

### Steps to Reproduce

I uncommented #define MKS_12864OLED_SSD1306 in configuration.h
Added pin definitions in the board file, pins_CREALITY_V4.h
#define I2C_SCL_PIN                           PB10
#define I2C_SDA_PIN                          PB11

### Version of Marlin Firmware

02010300

### Printer model

Creality ender 3 with custom display wired to exp3 cable

### Electronics

Creality v4.2.2 stm32 pcb

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/13243699/Configuration.zip)

**Comment by ellensp** [comment]
MKS_12864OLED_SSD1306 is not a I2C display by default, it is a SPI display. Yes the SSD1306 does i2c, if its wired that way. and the firmware is setup for it. 

MKS_12864OLED_SSD1306 needs to the appropriate SPI pins

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
Looking through the code I find there is

  #if ENABLED(ALTERNATIVE_LCD)
    #define U8G_CLASS U8GLIB_SSD1306_128X64_2X_I2C_2_WIRE       // 4 stripes
  #else

so you need to add #define ALTERNATIVE_LCD to your Configuration.h to use i2c mode

**Comment by ellensp** [comment]
If your playing with a generic i2c SSD1306  module, you need #define U8GLIB_SSD1306 not MKS_12864OLED_SSD1306

**Comment by jonathanmlang** [comment]
Hello thanks for replying, Ive tried #define U8GLIB_SSD1306 but still no luck, no output at the pins as proven by an oscilloscope.

**Comment by dbuezas** [comment]
~~Same here, I'm using an skr3 ez board on an Ultimaker 2.~~
~~I see the i2c clock for the i2c epprom on startup  but no clock at all if I disable it (not a single pulse). I did manually set the i2c pins since disabling eeprom skips defining them.~~

~~I tried changing pins and software/hw i2c. It looks like Marlin isn't even trying to talk to the display at all.~~

**Update: my case was unrelated. The skr3 uses software i2c and that isn't supported by u8glib**

**Comment by ellensp** [comment]
having a play 

using a creality 4.2.2.controller and a 0.96" SSD1306 I2C module

I wired it up

```
  /**             LCD PORT
   *              ------
   *        PC6  | 1  2 | PB2
   *  (SDL) PB10 | 3  4 | PB11 (SDA)                               
   *        PB14   5  6 | PB13
   *        PB12 | 7  8 | PB15
   *         GND | 9 10 | 5V
   *              ------
   */

```

I added this code to Marlin/src/MarlinCore.cpp    after `SETUP_LOG("setup() completed.");`

```CPP
  SERIAL_ECHOLN("I2C scanner. Scanning ...");
  Wire.setSDA(PB11);
  Wire.setSCL(PB10);
  Wire.begin();
  for (byte i = 1; i < 120; i++)
  {
    hal.watchdog_refresh();
    Wire.beginTransmission (i);
    if (Wire.endTransmission () == 0)
      {
      SERIAL_ECHOLN("Found address: ",i);
      delay (1);
      }
  }
  SERIAL_ECHOLN ("Done.");
```

And `#include <Wire.h>`  after `#include <math.h>`


Marlin boots and says 

> I2C scanner. Scanning ...
> Found address: 60
> Done.

60 is 3C, the expected address of the LCD, so this confirms the address and the wiring is OK

**Comment by ellensp** [comment]
I'm getting clock and data...  cant say if its the correct data.  (this is well after the I2C scanner)
Edit, this was due to my i2c scanner code initializing Wire. Signals are not visible otherwise


![NewFile0](https://github.com/MarlinFirmware/Marlin/assets/530024/e49a0498-891a-4d1b-8462-15e1cb711fc3)

**Comment by dbuezas** [comment]
Good idea with the i2c scan. I tried the same but with Software i2c and get this:

### Screen disconnected
```
10:18:16.948 > I2C scanner. Scanning ...
10:18:16.957 > Found address: 80
10:18:16.962 > Done.
```
That should be the onboard EEPROM

### Screen connected

```
10:18:16.948 > I2C scanner. Scanning ...
10:18:16.949 > Found address: 3
10:18:16.954 > Found address: 60
10:18:16.957 > Found address: 80
10:18:16.959 > Found address: 96
10:18:16.961 > Found address: 112
10:18:16.962 > Done.
```

**So my wiring should be correct.**

**Comment by ellensp** [comment]
Odd, removing my I2C scanner code you dont get any output, as reported

but just add adding  
```CPP
  Wire.setSDA(PB11);
  Wire.setSCL(PB10);
  Wire.begin();
```

above   SETUP_RUN(ui.init());  in Marlin/src/MarlinCore.cpp  and you get a display!!

![IMG_20231109_224738](https://github.com/MarlinFirmware/Marlin/assets/530024/724acd44-1e5b-41d0-a31f-a3bd3fe16ffc)

Ignore the power bank, its just a weight to hold the wires in place. 
This is far form a solution, more a hack, But my brain has quit for the day, will have to continue this later

**Comment by ellensp** [comment]
@jonathanmlang 

I purpose this as a fix.   (basically it rearranges  marlinui.cpp to setup the i2c pins before setting up the display, and changes the pin variable type)

```DIFF
diff --git a/Marlin/src/lcd/marlinui.cpp b/Marlin/src/lcd/marlinui.cpp
index 463d406110..fa511b4882 100644
--- a/Marlin/src/lcd/marlinui.cpp
+++ b/Marlin/src/lcd/marlinui.cpp
@@ -218,6 +218,10 @@ constexpr uint8_t epps = ENCODER_PULSES_PER_STEP;
 
 void MarlinUI::init() {
 
+  #if HAS_U8GLIB_I2C_OLED && PINS_EXIST(I2C_SCL, I2C_SDA) && DISABLED(SOFT_I2C_EEPROM)
+    Wire.begin(uint8_t(I2C_SDA_PIN), uint8_t(I2C_SCL_PIN));
+  #endif
+
   init_lcd();
 
   #if HAS_DIGITAL_BUTTONS
@@ -274,10 +278,6 @@ void MarlinUI::init() {
     slow_buttons = 0;
   #endif
 
-  #if HAS_U8GLIB_I2C_OLED && PINS_EXIST(I2C_SCL, I2C_SDA) && DISABLED(SOFT_I2C_EEPROM)
-    Wire.begin(int(I2C_SDA_PIN), int(I2C_SCL_PIN));
-  #endif
-
   update_buttons();
 
   TERN_(HAS_ENCODER_ACTION, encoderDiff = 0);

```

**Comment by ellensp** [comment]
Ive created a PR to fix this, so closing this issue
