### ISSUE TITLE
[BUG] Some menus/text lines missing characters

### ISSUE THREAD

**Issue by thisiskeithb** [MarlinFirmware/Marlin#26413]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Starting with 797ea5e / #26339, some menus/text items under Marlin UI are missing proper spaces:

![image](https://github.com/MarlinFirmware/Marlin/assets/13375512/b22d8175-ca65-4785-b852-3c1ad6449fbc)

Reverting the above commit fixes it, but then the Endstop Test menu is broken again.

### Bug Timeline

797ea5e / #26339

### Expected behavior

Text & menus to have colons & spaces where appropriate.

### Actual behavior

Colons & spaces are missing from some menus/text items under Marlin UI.

### Steps to Reproduce

With `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` & `LCD_INFO_MENU` enabled, flash latest `bugfix-2.1.x` with any Marlin UI compatible screen and navigate to `About Printer` -> `About Board` menu item to observe bug.

### Version of Marlin Firmware

`bugfix-2.1.x` as of 573eae8

### Printer model

Applies to any printer with Marlin UI

### LCD/Controller

Applies to any printer with Marlin UI

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Default config with `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` & `LCD_INFO_MENU` enabled: 
[bugfix-2.1.x - 573eae8 - default config - REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER - LCD_INFO_MENU.zip](https://github.com/MarlinFirmware/Marlin/files/13325449/bugfix-2.1.x.-.573eae8.-.default.config.-.REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER.-.LCD_INFO_MENU.zip)

**Comment by ellensp** [comment]
Note: its should be for eg 
```
Baud: 250000 
Protocol: 1.0
PSU: Generic

```
Both the colon and the space are missing

**Comment by ellensp** [comment]
updated shorter fix.

```DIFF
diff --git a/Marlin/src/lcd/dogm/marlinui_DOGM.cpp b/Marlin/src/lcd/dogm/marlinui_DOGM.cpp
index 30258f0d48..d1f6851345 100644
--- a/Marlin/src/lcd/dogm/marlinui_DOGM.cpp
+++ b/Marlin/src/lcd/dogm/marlinui_DOGM.cpp
@@ -423,7 +423,7 @@ void MarlinUI::clear_lcd() { } // Automatically cleared by Picture Loop
     int8_t vlen = vstr ? utf8_strlen(vstr) : 0;
 
     bool mv_colon = false;
-    if (vlen) {
+    if (vlen && !center) {
       // Move the leading colon from the value to the label below
       mv_colon = (*vstr == ':');
       // Shorter value, wider label
```

This looks like it fixes it at first glance, please check for additional collateral damage

![whatitshouldlooklike](https://github.com/MarlinFirmware/Marlin/assets/530024/bbc0c6f1-1be2-42aa-bfbb-3d8612ecf65b)

**Comment by thisiskeithb** [comment]
> This looks like it fixes it at first glance, please check for additional collateral damage

Since only centered text seems to be affected, I think that fix is good.

Tested on real hardware here & that seems to have fixed it.

**Comment by thisiskeithb** [comment]
Closing since @ellensp opened a PR.

**Comment by thijstriemstra** [comment]
> Closing since @ellensp opened a PR.

Shouldn't that pr close this ticket (when it's merged)? This is marked as completed but it ain't (yet) ;)
