### ISSUE TITLE
[BUG] TronXY X5SA PRO V10 Board with GD32F427ZET6 CPU

### ISSUE THREAD

**Issue by Czaapii** [MarlinFirmware/Marlin#26411]
Configuration & Configuration_adv & TronxyMachine & platformio
[TronxyMachine.zip](https://github.com/MarlinFirmware/Marlin/files/13325050/TronxyMachine.zip)

### Bug Description

Processing tronxy_stm32f103 (board: tronxy_stm32f103zet; platform: ststm32@~12.1; framework: arduino)
----------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/tronxy_stm32f103zet.html
PLATFORM: ST STM32 (12.1.1) > STM32F103ZE (64k RAM. 512k Flash) 
HARDWARE: STM32F103ZET6 72MHz, 64KB RAM, 512KB Flash
DEBUG: Current (blackmagic) External (blackmagic, jlink, stlink)
PACKAGES:
 - framework-arduinoststm32 @ 4.10900.200819 (1.9.0)
 - framework-cmsis @ 2.50501.200527 (5.5.1)
 - toolchain-gccarmnoneeabi @ 1.90201.191206 (9.2.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 10 compatible libraries
Scanning dependencies...
Dependency Graph
|-- IWatchdog @ 1.0.0
|-- SPI @ 1.0
|-- EEPROM @ 2.0.1
|-- SoftwareSerial @ 1.0
|-- Servo @ 1.1.2
|-- Wire @ 1.0
Building in release mode
RuntimeError: deque mutated during iteration:
  File "C:\.platformio\penv\Lib\site-packages\platformio\builder\main.py", line 180:
    env.SConscript(env.GetExtraScripts("post"), exports="env")
  File "C:\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\Marcin\Desktop\TronXY X5SA PRO Marlin\buildroot\share\PlatformIO\scripts\tronxy_scrypt.py", line 9:        
  File "C:\Users\Marcin\Desktop\TronXY X5SA PRO Marlin\buildroot\share\PlatformIO\scripts\marlin.py", line 30:
    replace_define("VECT_TAB_OFFSET", address)
  File "C:\Users\Marcin\Desktop\TronXY X5SA PRO Marlin\buildroot\share\PlatformIO\scripts\marlin.py", line 19:
    for define in env['CPPDEFINES']:
================================================ [FAILED] Took 7.70 seconds ================================================

Environment       Status    Duration
----------------  --------  ------------
tronxy_stm32f103  FAILED    00:00:07.700
========================================== 1 failed, 0 succeeded in 00:00:07.700 ========================================== 

### Version of Marlin Firmware
Marlin 2.1.x

### Printer model
Tronxy x5sa pro

### Electronics
V10 board

**Comment by ellensp** [comment]
You are running old code 

So  you get the error
RuntimeError: deque mutated during iteration:

All instance of Marlin from MarlinFirmware github have had this fixed. So your not using current source from MarlinFirmware

Config shows version 02010100
This commit was added to official Marlin lts-2.1.1  to fix this issue on Jul 21 

https://github.com/MarlinFirmware/Marlin/commit/dfa748cb96f711bc0e8667f51f761612dcff25c7#diff-ebd995a07ef25d75984a385aecf38462ed81ffedce977c742e6cf8e273501f9b
