### ISSUE TITLE
Geeetech A20T Display dark

### ISSUE THREAD

**Issue by ajoreis** [MarlinFirmware/Marlin#26430]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have a problem with my Geeetech A20T. If I activate imput shaping in the configuration and flash the firmware, the LCD display is dark and the printer can no longer be operated.
If I deactivate the input shaping again and then flash the firmware again, everything is fine again. Unfortunately I don't get any error message. Is there a way to enable debugging?

### Bug Timeline

no

### Version of Marlin Firmware

bugfix-2.1 14. Nov. 2023

### Printer model

Geeetech A20T

### Electronics

A20T GT2560 V4.1B Control Board mega/pins_GT2560_v3_A20.h

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

Repetier Host

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[confic.zip](https://github.com/MarlinFirmware/Marlin/files/13374383/confic.zip)

**Comment by ellensp** [comment]
first read what is shown to you

RAM:   [==========]  100.2% (used 8211 bytes from 8192 bytes)
Flash: [========= ]  86.8% (used 220382 bytes from 253952 bytes)
Building .pio/build/mega2560/firmware.hex


The RAM used above is  the statically allocated ram used, It is impossible to use more than 100%
On top of that some ram is required for dynamically allocated stuff, stacks/heaps and some functions.
   
In reality RAM should never exceed around 90-95%, or marlin cannot setup stack etc... and cannot run.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ajoreis** [comment]
Thank you very much

I understood that and am trying to reduce the RAM area.

Thank you very much

Olaf Reis
