### ISSUE TITLE
Configurator is unable to load configuration / can't parse

### ISSUE THREAD

**Issue by chaoscrack** [MarlinFirmware/Marlin#2643]
Hello

I tried to use the configurator. If I start the index.html I get the information "Configurator is unable to load configuration. Try the upload field". So I choose the configuration.h and get the message "Please upload a boards.h file first". If I do that the next message is "can't parse boards.h"

What should I have to do or what do I wrong?

Thanks for your help

**Comment by Wackerbarth** [comment]
The configurator has always been just a "work in progress". It doesn't actually work very well. You will need to perform your configuration manually.

**Comment by KiteLab** [comment]
In particular it refers to a not any more existing branch

**Comment by thinkyhead** [comment]
Development will continue on Marlin Configurator as time allows. It's still in the experimental alpha stage, as I develop methods to parse and generate configurations, form fields, etc. It has only a raw "expert" interface so far (with almost every option exposed) but will get a simplified interface and a presets menu over time. Now hosted at:
- https://github.com/thinkyhead/MarlinConfigurator
- https://rawgit.com/thinkyhead/MarlinConfigurator/master/src/index.html
