### ISSUE TITLE
[BUG] Incorrect bed temp showing on Fystec 2.0 DGUS display

### ISSUE THREAD

**Issue by fortis852** [MarlinFirmware/Marlin#26442]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Chaotic bed temp (-900,-600, 50, 600) on `DGUS_LCD_UI FYSETC` with firmware FYSTEC 2.0 on LCD. I changed line 395 in bed section `DGUSDisplayDef.cpp` like in heater section, and it works. 

https://github.com/MarlinFirmware/Marlin/blob/e45eddfd6c4008d82b3aefe4764793b0669dc60a/Marlin/src/lcd/extui/dgus/fysetc/DGUSDisplayDef.cpp#L394-L395

to

```c
#if HAS_HEATED_BED
    VPHELPER(VP_T_Bed_Is, &thermalManager.temp_bed.celsius, nullptr, ScreenHandler.DGUSLCD_SendFloatAsLongValueToDisplay<0>),
```

### Bug Timeline

Dont know

### Expected behavior

In octoprint and serial bed_temp is correct. I'd like to see it on my DGUS screen.

### Actual behavior

Chaotic bed temp (-900,-600, 50, 600) 

### Steps to Reproduce

1. See temp on DGUS FYSTEC 2.0 dispay

### Version of Marlin Firmware

02010201

### Printer model

custom

### Electronics

mks_gen_l_v2

### LCD/Controller

DGUS FYSTEC 2.0

### Bed Leveling

None

### Your Slicer

None

### Host Software

OctoPrint

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by fortis852** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/13401261/Marlin.zip)

**Comment by thisiskeithb** [comment]
Applying your suggestion:

```c
VPHELPER(VP_T_Bed_Is, &thermalManager.temp_bed.celsius, nullptr, ScreenHandler.DGUSLCD_SendFloatAsLongValueToDisplay<0>),
```
...to current bugfix, it becomes:

```c
VPHELPER(VP_T_Bed_Is, &thermalManager.temp_bed.celsius, nullptr, screen.sendFloatAsLongValueToDisplay<0>),
```

Can you test if this change works on current `bugfix-2.1.x`?

**Comment by fortis852** [comment]
Yes, i will test

**Comment by thisiskeithb** [comment]
Please report your findings in https://github.com/MarlinFirmware/Marlin/pull/26484!
