### ISSUE TITLE
[BUG] Still receiving warning: narrowing conversion from 'int' to 'short int' 

### ISSUE THREAD

**Issue by classicrocker883** [MarlinFirmware/Marlin#26452]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The error happens in both **JyersUI** and **ProUI**

```r
Marlin/src/lcd/e3v2/jyersui/dwin.cpp: In member function 'void<unnamed struct>::drawBedMesh(int16_t, uint8_t, uint16_t, uint16_t)':
Marlin/src/lcd/e3v2/jyersui/dwin.cpp:392:51: warning: narrowing conversion of '(((int)(((short unsigned int)((int)cell_height_px)) / 2)) - 6)' from 'int' to 'short int' [-Wnarrowing]
  392 |           xy_int_t offset { 0, cell_height_px / 2 - 6 };
```
^JyersUI^
```r
Marlin\src\lcd\e3v2\proui\bedlevel_tools.cpp: In static member function 'static void BedLevelToolsClass::Draw_Bed_Mesh(int16_t, uint8_t, uint16_t, uint16_t)':
Marlin\src\lcd\e3v2\proui\bedlevel_tools.cpp:232:47: warning: narrowing conversion of '(((int)(((short unsigned int)((int)cell_height_px)) / 2)) - ((int)fs))' from 'int' to 'short int' [-Wnarrowing]
  232 |       xy_int_t offset { 0, cell_height_px / 2 - fs };
```
^ProUI^

I know @thinkyhead just updated the code, but the warning still happens.
before, the code `xy_int_t offset { 0, cell_height_px / 2 - fs };` was `xy_int8_t` and that also gave the warning.

I suggested it can be changed to `xy_long_t` because that gave no warning.

### Bug Timeline

started with 376673d - 🚸 Minor touch calibration improvement (#26445)

### Expected behavior

no warning is expected

### Actual behavior

warning is given

### Steps to Reproduce

1. Load Ender-3 V2 Configuration files
2. ANY(`AUTO_BED_LEVELING_BILINEAR`, `AUTO_BED_LEVELING_UBL`, `MESH_BED_LEVELING`)
3. `DWIN_LCD_PROUI` or `DWIN_CREALIT_LCD_JYERSUI`
4. compile

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Ender-3V2, Aquila

### LCD/Controller

4.3" DWIN

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[configurations files](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3%20V2/CrealityV422/CrealityUI)

**Comment by thisiskeithb** [comment]
Closing since you’ve opened a PR.
