### ISSUE TITLE
 X axis and Y axis Losing coordinates during printing

### ISSUE THREAD

**Issue by schirrel** [MarlinFirmware/Marlin#2645]
X axis and Y axis losing coordinates during printing, the print object get dislocated.
What happens is, it prints half, or an fair amount amount and then goes to some near points and at this new position it keeps printing like nothing happened.

**Comment by clefranc** [comment]
@jasane Can it be hardware related. Some loose belt or misadjusted stepper driver?

**Comment by schirrel** [comment]
Everything on hardware is fine. The belts are fully tight, the current of the motor is adjusted as it should, the axes of the motors are free, the temperature of the motor during work is ok, the maximum velocity is 360 mm per minute and even this still happening. I look up this solves http://wiki.solidoodle.com/fix-axis-shifting and none of them worked for me.

**Comment by ghuser2** [comment]
Is the new point on the same layer, or it does it when starting a new layer?

**Comment by schirrel** [comment]
It happens randomly. It's printing in the current layer, never is at the same layer something is at the bottom layers, other at the top ones, and when it goes to the next layer already starts at the new point.

**Comment by ghuser2** [comment]
Sounds like gcode is corrupt.

**Comment by schirrel** [comment]
GCODE corrupt? What you mean?
I'm using Simplify as slicer maybe it's sending the wrong gcode?
I didn't modified the gcode part on the firmware.

**Comment by AnHardt** [comment]
#2615

**Comment by AnHardt** [comment]
Let's resume. It's not the Hardware. It's not really related to G29. Your sending correct g-code. Whats left?
...
As this are the typical symptoms of loosing steps, and we do not receive any other reports with this symptoms, my guess is still a hardware problem. 
Do you have a spare driver?

The other likely source of these error is moving, accelerating or jerking to fast.

**Comment by schirrel** [comment]
My boss just told me he is trying put 2 more pull ups because he's now strongly believing that maybe has an interference at the hot end. I'll send any further information on monday.
Thank you everybody.

**Comment by AnHardt** [comment]
Do you set up this printer for the first time, or did it work before?

Did you check the voltage of the power supply under full load - when extruder and bed are heating at full power?

**Comment by dteeter** [comment]
I've had this exact problem before. For me it happened because the stepper current was turned down too low and the motors were skipping steps. Other reasons for skipping steps can be: extruder getting hung up on warped edges, mechanical binding during a movement, overheating of drivers, slippage of belt sprockets on the motor shaft, etc.
