### ISSUE TITLE
Touch screen does not work after PR#26445

### ISSUE THREAD

**Issue by jmz52** [MarlinFirmware/Marlin#26454]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Touch screen support is broken in https://github.com/MarlinFirmware/Marlin/pull/26445
Reverting this PR fixes the problem.

### Bug Timeline

https://github.com/MarlinFirmware/Marlin/pull/26445

### Expected behavior

UI respond to touching elements
Touch screen calibration can be completed successfully.

### Actual behavior

UI does not respond to touching elements
Touch screen calibration fails every time

### Version of Marlin Firmware

bugfix-2.1.x (Nov 22 2023 17:57:56)

### Electronics

MKS Robin Nano V3.1

### LCD/Controller

MKS TS35 V2.0

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
Just confirmed here on an SKR 2 with BTT TFT35 SPI. I was using the encoder while testing out #26052 and didn't realize touch was now broken.
