### ISSUE TITLE
G29 S0 after G29 P1 destroys previous bed leveling and doesn't save.

### ISSUE THREAD

**Issue by Osmodia666** [MarlinFirmware/Marlin#26465]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After using the official Guide with example for UBL:
https://marlinfw.org/docs/gcode/G029-ubl.html

G29 S0 doesn't save to slot 0, it just probes 16 times the last probing point from G29 P1, compromising the values from G29 P1.
Saving via EEPROM is enabled and working.

G29 P1:
`Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3
Recv:  0 -1.387 -1.295 -1.328 -1.686
Recv:  1 -1.078 -1.145 -1.159 -1.203
Recv:  2 -1.014 -1.166 -1.176 -1.121
Recv:  3 -0.998 -1.378 -1.316 -1.252`

G29 S0
`Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3
Recv:  0 -1.257 -1.256 -1.256 -1.256
Recv:  1 -1.260 -1.265 -1.271 -1.277
Recv:  2 -1.264 -1.268 -1.274 -1.276
Recv:  3 -1.264 -1.267 -1.272 -1.276`

### Expected behavior

Save the probed mesh in EEPROM

### Actual behavior

It just probes the last point of the bed.

### Version of Marlin Firmware

2.1.2

### Printer model

Ender 3 Pro

### Electronics

SKR Mini E3 V3

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/13466638/Marlin.zip)

**Comment by ellensp** [comment]
https://marlinfw.org/docs/gcode/G029-abl-bilinear.html

S0 is not save on bilinear 

Your looking at UBL docs while using bilinear
