### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#2647]
the link for
"This branch, "RC", " ===> https://github.com/MarlinFirmware/MarlinDev/tree/RC
on this page
https://github.com/MarlinFirmware/Marlin/tree/RC
does not exist

also, can someone tell me how to find this - I have been searching for an hour
hardware/marlin/avr/libraries/marlin/examples/MarlinFirmware/FirmwareCustomization.h

**Comment by Wackerbarth** [comment]
Thanks.  Fixed

**Comment by clefranc** [comment]
@ruggb,

> also, can someone tell me how to find this - I have been searching for an hour
> hardware/marlin/avr/libraries/marlin/examples/MarlinFirmware/FirmwareCustomization.h

I think you're looking in the wrong repository (again), this file is from the new master branch of MarlinDev.

**Comment by ruggb** [comment]
thx - if i keep trying i may figure this all out eventually
