### ISSUE TITLE
Does Marlin support the 4.2.2 GD32F303RET6 chip?

### ISSUE THREAD

**Issue by kamskanagi** [MarlinFirmware/Marlin#26481]
### Is your feature request related to a problem? Please describe.

Currently having an issue with the Z-axis. The default feedrate is very low. So we want to increase the Z-axis feedrate using the Marlin open source code and rebuild the firmware. But cant find the board support for firmware for 4.2.2 GD32F303 RET6.
the attached file is our board picture. 
![endor- V2](https://github.com/MarlinFirmware/Marlin/assets/7499252/f82b2035-201d-4c87-854d-ccd3a509a0ad)

#define MOTHERBOARD BOARD_MYBOARDNAME.
and 
the default_envs to be use in platformio.ini file.

### Describe the feature you want

We want to increase the feedrate for Z-axis in config.h file and rebuild the firmware Marlin source code.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
Use M203 gcode and save to eeprom.
