### ISSUE TITLE
info needed

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#2648]
can someone tell me how to find this - I have been searching for an hour
hardware/marlin/avr/libraries/marlin/examples/MarlinFirmware/FirmwareCustomization.h

**Comment by clefranc** [comment]
@ruggb I presume you're trying to compile the "new system" of MarlinDev firmware?

**Comment by GrevanGER** [comment]
https://github.com/MarlinFirmware/MarlinDev/tree/master/examples/MarlinFirmware

**Comment by BuzzBumbleBee** [comment]
@ruggb yeah its a little confusing afaik marlin dev needs you to add it to the lib folder combined with https://github.com/MarlinFirmware/MarlinDev/tree/IDE_1.6.5/

**Comment by ruggb** [comment]
thx, somehow I finally stumbled across it. I wanted the info as ref on
https://github.com/MarlinFirmware/MarlinDev/
but this just keeps getting more confusing.
I hope someone can author a good tutorial for us dummies.
