### ISSUE TITLE
fysect e4 esp32 TMC2209 UART driver error

### ISSUE THREAD

**Issue by yoroboticscolombia** [MarlinFirmware/Marlin#26488]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi, Im trying to configure the board and change the driver current, but i tried setting monitor driver status, but i get this message:

E (5870) uart: uart_get_buffered_data_len(1342): uart driver error
![image](https://github.com/MarlinFirmware/Marlin/assets/62781222/6a23b779-1f68-47b2-8b4d-6e9bd0cd0c2d)

![image](https://github.com/MarlinFirmware/Marlin/assets/62781222/f1a96e51-0784-41ac-bb24-95b4753c5a82)

what can be causing this.
I have already knowledge of marlin and esp3d.

thanks.

### Expected behavior

Change the current of the steppers, since they are getting hot.

### Actual behavior

 uart: uart_get_buffered_data_len(1342): uart driver error

### Steps to Reproduce

I uploaded different versions of marlin, but no success

### Version of Marlin Firmware

bugfix 2.1.x

### Printer model

ender

### Electronics

fysect e4

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
