### ISSUE TITLE
[BUG] (DEBUG_ECHOF not defined)

### ISSUE THREAD

**Issue by narno2202** [MarlinFirmware/Marlin#26493]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When I enable `DEBUG_LEVELING_FEATURE` to investigate BLTouch HS_Mode in `FT_MOTION`, Marlin can't compile sending DEBUG_ECHOF not defined, replacing the faulty macro by DEBUG_ECHO, compile and debug went fine.

### Version of Marlin Firmware

latest bugfix

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by classicrocker883** [comment]
do you know how to do a Pull Request? you should do that, you'll be able to be credited for this fix.

**Comment by thisiskeithb** [comment]
> do you know how to do a Pull Request? you should do that, you'll be able to be credited for this fix.

<img width="578" alt="image" src="https://github.com/MarlinFirmware/Marlin/assets/13375512/3d7835a2-600a-4983-89ed-3d57576e52e6">

**Comment by thisiskeithb** [comment]
`DEBUG_ECHOF()` was removed in https://github.com/MarlinFirmware/Marlin/pull/25928 and replaced with `DEBUG_ECHOLN(prefix, F()` in most places.

Based on changes in that PR, this should be the fix:

```diff
diff --git a/Marlin/src/gcode/calibrate/G28.cpp b/Marlin/src/gcode/calibrate/G28.cpp
index ba16c7b..dbdbdc5 100644
--- a/Marlin/src/gcode/calibrate/G28.cpp
+++ b/Marlin/src/gcode/calibrate/G28.cpp
@@ -263,7 +263,7 @@ void GcodeSuite::G28() {
 
       #if ENABLED(DEBUG_LEVELING_FEATURE)
         auto debug_current = [](FSTR_P const s, const int16_t a, const int16_t b) {
-          if (DEBUGGING(LEVELING)) { DEBUG_ECHOF(s); DEBUG_ECHOLNPGM(" current: ", a, " -> ", b); }
+          if (DEBUGGING(LEVELING)) { DEBUG_ECHOLN(s, F(" current: "), a, F(" -> "), b); }
         };
       #else
         #define debug_current(...)
diff --git a/Marlin/src/module/endstops.cpp b/Marlin/src/module/endstops.cpp
index 0f060f5..9c6a3c0 100644
--- a/Marlin/src/module/endstops.cpp
+++ b/Marlin/src/module/endstops.cpp
@@ -1360,7 +1360,7 @@ void Endstops::update() {
 
       #if ENABLED(DEBUG_LEVELING_FEATURE)
         auto debug_current = [](FSTR_P const s, const int16_t a, const int16_t b) {
-          if (DEBUGGING(LEVELING)) { DEBUG_ECHOF(s); DEBUG_ECHOLNPGM(" current: ", a, " -> ", b); }
+          if (DEBUGGING(LEVELING)) { DEBUG_ECHOLN(s, F(" current: "), a, F(" -> "), b); }
         };
       #else
         #define debug_current(...)
```

**Comment by thisiskeithb** [comment]
Thanks for the report!

Fixed in https://github.com/MarlinFirmware/Marlin/pull/26495
