### ISSUE TITLE
[BUG] Home Offset Z is not saved 

### ISSUE THREAD

**Issue by enesdogan00** [MarlinFirmware/Marlin#26498]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When I set the Home Offset Z from the prepare menu and restart the printer z offset is back to 0.00. 

### Bug Timeline

September 2023

### Expected behavior

I expect the printer to save the home offset z to eeprom so I can use it after restarting the printer. This worked on older versions but now it doesn't.

### Actual behavior

I set the Home Offset Z from the prepare menu and it says Settings Stored. After that I can print with the set offset but if I restart the printer the offset is set back to 0.00.

### Steps to Reproduce

1. Compile the Marlin firmware with the config below at commit `b17d3d3e9c6`
2. Flash the firmware to the printer.
3. Go to the Prepare menu and set the Home Offset Z.
4. Restart the printer and check if the offset is still the same.

### Version of Marlin Firmware

02010300

### Printer model

Ender3V2

### Electronics

Skr Mini E3 V3

### LCD/Controller

Ender3V2 Display

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/13539508/Marlin.zip)

**Comment by classicrocker883** [comment]
if you havent fixed this yet, try this:  
in **proui/dwin.h** in the `hmi_data_t` struct
```diff
  #endif
+ #if DISABLED(HAS_BED_PROBE)
+   float manualZOffset = 0.0f;
+ #endif
} hmi_data_t;
```

in **proui/dwin.cpp** near the top, change...
```diff
-#if HAS_MESH && HAS_BED_PROBE
-  #define BABY_Z_VAR probe.offset.z
-#else
-  float z_offset = 0;
-  #define BABY_Z_VAR z_offset
-#endif

+#define BABY_Z_VAR TERN_(HAS_BED_PROBE, probe.offset.z, hmiData.manualZOffset)
```
in the same **dwin.cpp**, look for `void dwinSetDataDefaults() {` and add...
```diff
    hmiData.zAfterHoming = DEF_Z_AFTER_HOMING;
  #endif
+ #if DISABLED(HAS_BED_PROBE)
+   hmiData.manualZOffset = 0;
+ #endif
```

remove any _red_ with (-) and add the _green_ code after (+)
