### ISSUE TITLE
Copied back the wiki

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#2650]
Copied back the wiki from 
http://www.marlinfirmware.org/ to https://github.com/MarlinFirmware/Marlin/wiki.

As the github-wiki supports the Mediawiki-syle this was a pure workout for my wrist.

Currently the wiki is writable by all github users.
Please help to improve it.

**Comment by fmalpartida** [comment]
Looking great. 

Enviado desde mi iPhone
