### ISSUE TITLE
[BUG] B1 se plus bugfix-2.1.x(with stm32f4-tft-spi-fix) feels like there's a noticeable delay

### ISSUE THREAD

**Issue by doshiyo103** [MarlinFirmware/Marlin#26506]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have tried overlaying the file from #26052 onto bugfix-2.1.x and attempting to rebuild before booting up. 
This time, the "marlin mode" appeared, but it led to another issue. 
Every step of the operation now feels like there's a noticeable delay. Could you please check and confirm this issue?

I'm sorry to open another issue, but the other one, #26504, has been closed. 

### Version of Marlin Firmware

bugfix2.1.x 

### Printer model

B1 se plus

### LCD/Controller

BTT TFT35 SPI V1.1

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I use this firmware to build .bin,
and get Every step of the operation now feels like there's a noticeable delay on B1 se plus.
[bugfix-2.1.x with st32f4fix.zip](https://drive.google.com/file/d/1eEvKtCKiPzSFQ2MeKg1c_mRSTXBfBXMG/view?usp=sharing)

**Comment by ellensp** [comment]
https://github.com/MarlinFirmware/Marlin/pull/26052 is a work in progress, please post any issue related to this PR in the already open PR https://github.com/MarlinFirmware/Marlin/pull/26052
