### ISSUE TITLE
EVENT_GCODE_SD_ABORT LCD12864 "STOP". The printhead just stops in place 

### ISSUE THREAD

**Issue by ProtomakerSprint** [MarlinFirmware/Marlin#26509]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

EVENT_GCODE_SD_ABORT LCD12864 "STOP". The printhead just stops in place 

 Marlin bugfix-2.0.9.3.x with bug fix

The printer stops moving.

LCD12864 "STOP" TFT35 display

None of these work:-

Tried #define EVENT_GCODE_SD_ABORT "G1 Z 200\nX 0\nY 350"

Tried #define EVENT_GCODE_SD_ABORT "G1 Z 200 X 0 Y 350"

Tried #define EVENT_GCODE_SD_ABORT "G28XY"

ENABLED(SDSUPPORT)

enabled Both HOST_ACTION_COMMANDS and HOST_PROMPT_SUPPORT

#define NOZZLE_PARK_FEATURE

#define EMERGENCY_PARSER
 

e,g.

#define HOST_ACTION_COMMANDS
#if ENABLED(HOST_ACTION_COMMANDS)
  #define HOST_PAUSE_M76                // Tell the host to pause in response to M76
  #define HOST_PROMPT_SUPPORT	
  #if ENABLED(HOST_PROMPT_SUPPORT)
    #define HOST_STATUS_NOTIFICATIONS   // Send some status messages to the host as notifications
  #endif
  //#define HOST_START_MENU_ITEM          // Add a menu item that tells the host to start
  //#define HOST_SHUTDOWN_MENU_ITEM       // Add a menu item that tells the host to shut down
#endif

/**
 * Cancel Objects
 *
 * Implement M486 to allow Marlin to skip objects
 */
//#define CANCEL_OBJECTS
#if ENABLED(CANCEL_OBJECTS)
  #define CANCEL_OBJECTS_REPORTING // Emit the current object as a status message
#endif

==========================

Other details:-

Creality Ender 5 Plus

 Marlin bugfix-2.0.9.3.x with bug fix NOT USED INPUT_SHAPING OPTION in Configuration_adv.h

 Bigtree Tech Octopus VI.1 STM32F446ZET6 chip

 Bigtree Tech TF35 Dual display using LCD12864 STOP command on the display

 BLTouch, POWER_LOSS_RECOVERY  BigTree tech

*** NOTE Compile as ABM Panel : Environment STM32F446ZE_btt(512K) Architecture : Stm32f4 Re: STM32F446ZET6 chip

*** NOTE platformio.ini needs setting  BOARD_BTT_OCTOPUS_V1_1 

*** NOTE Architecture : Stm32f4 Re: STM32F446ZET6 chip   BOARD_BTT_OCTOPUS_V1_1  

*** NOTE \Marlin\src\pins\stm32f4\pins_BTT_0CT0PUS_Vl_common.h pins_BTT_OCTOPUS_Vl_common.h Pins need changing for Nozzle Wipe via Servo.

*** NOTE Marlin\src\module\temparture.cpp temperature.cpp M190 R wait for Heat Bed to cool down fix. Changed for cool down Heat Bed sounds.

 Driver chips I use TMC2208, no sensorless

### Bug Timeline

Others has reported this issue

### Expected behavior

To stop the print and move the printer head to a position I request

### Actual behavior

3D printer stops but the print head position does not move as requested

### Steps to Reproduce

Start 3D print
Wait for the 3D Print to create first later
Select "STOP" on the LCD 12864 display 

### Version of Marlin Firmware

 Marlin bugfix-2.0.9.3.x with bug fix

### Printer model

Creality Ender 5 Plus

### Electronics

Bigtree Tech Octopus VI.1

### LCD/Controller

Bigtree Tech TF35 Dual display using LCD12864 

### Other add-ons

Servo to wipe the nozzle, Filament Runout detection, LED lights

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

IdeaMaker

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/13601870/Configuration.zip)

**Comment by ellensp** [comment]
"Select "STOP" on the LCD 12864 display"  

Please clarify what you mean by this

The 12864 lcd is the mono mode, it has no touch.  Not sure what stop you are referring to.  Pictures?
But stop is probably not abort...


If your referring to a touch button, this is TFT mode, what the tft mode does is  up to the TFT firmware code provided by BTT  


SD abort is M524, that uses EVENT_GCODE_SD_ABORT

What the TFT send when you click an icon in the touch interface it is outside of Marlin control.

**Comment by ProtomakerSprint** [comment]
**Fixed** So far as I can tell OctoPrint issue

Other settings above may also be requires

**SD Card Stop Action in Configuration_adv.h**

 #define EVENT_GCODE_SD_ABORT "G1 Z200 F12000\nG1 X0 Y350  F18000"	// G-code to run on SD Abort Print (e.g., "G28XY" or "G27") // Protomaker Sprint Note New Lines, ( \n ) required. Out the way of the bed.  Z 200 hight; X 0 left; Y 350  back. "STOP Print" on LCD 12864

**Using Octoprint**

GCODE Scripts >>> Settings >>> After print job is cancelled

G1 Z200 F12000
G1 X0 Y350  F18000

; disable motors
M84

;disable all heaters
{% snippet 'disable_hotends' %}
{% snippet 'disable_bed' %}
;disable fan
M106 S0
