### ISSUE TITLE
Where is issue #2649?

### ISSUE THREAD

**Issue by clefranc** [MarlinFirmware/Marlin#2651]
@pbrgle1 Where is your issue #2649?

**Comment by KiteLab** [comment]
Server error?

Changing the offset is one thing, actually moving the head is an other.
I would be interested how the head is moving in the next move - for example a G0 Z0.

**Comment by clefranc** [comment]
@pbrgle1 closed its GitHub account, issue gone with it. Is this common?

**Comment by ghost** [comment]
#2652
test

**Comment by pbrgle1** [comment]
i dont know if you guys can see this but... 
![05](https://cloud.githubusercontent.com/assets/14819847/10098114/d9ae27aa-637e-11e5-92b8-e8c7fcfd47bb.png)

**Comment by KiteLab** [comment]
ghost was @t-est-user.
#2652

**Comment by KiteLab** [comment]
```
Are you sure you want to do this?
This is extremely important.

We will immediately delete all of your repositories (1), along with all of your forks, wikis, issues, pull requests, and GitHub Pages sites.

You will no longer be billed, and your username will be available to anyone on GitHub.

For more help, read our article "Deleting your user account".https://help.github.com/articles/deleting-your-user-account/
```

At lest you are warned that your issues will disappear
I really don't know what the difference between @pbrgle1 and @t-est-user was.

**Comment by clefranc** [comment]
@pbrgle1 forked this repo.

**Comment by KiteLab** [comment]
@clefranc 
Good argument. But i'll not test this. Let's close this.
