### ISSUE TITLE
[FR] Avoid going beyond Z-MIN endstop when Z-MAX homing is done through a probe

### ISSUE THREAD

**Issue by dbuezas** [MarlinFirmware/Marlin#26520]
### Is your feature request related to a problem? Please describe.

In my Ultimaker 2 the bed moves up and down. When the steppers are disabled, the bed falls by gravity to the bottom.
I am using a BL-Touch acting as a ~~Z-MAX~~ **Z-MIN** probe, so when I home the axes, the printer adds z clearance BEYOND the existing ~~Z-MIN~~ **Z-MAX** endstop, and it skips steps and makes ugly noises.

As a workaround I left a sponge below the bed so it doesn't fall as deep. 

### Describe the feature you want

That the downward z movement is clipped once the Z-MIN stop is reached (particularly if it is already triggered), even when there is a z-max probe in use

### Additional context

The probe and endstops use independent pins, and they are both configured. I confirmed they are both in working order via an endstop test in the UI.
I am aware of `SD_ABORT_ON_ENDSTOP_HIT`, but that would just stop homing altogether.

**Comment by EvilGremlin** [comment]
You saying it backwards, your probe is Zmin and endstop is Zmax. Looks like you just need to reduce Z_MAX_POS a bit.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.

**Comment by EvilGremlin** [comment]
Also already exist - ENDSTOPS_ALWAYS_ON_DEFAULT, SD_ABORT_ON_ENDSTOP_HIT

**Comment by dbuezas** [comment]
Oh, that won't abort the print? Cool Thanks

**Comment by dbuezas** [comment]
~~By the way, my printer moves the bed in the z axis, not the nozzle, so Z=0 is when the bed is up. That's why I said the min stop is the probe.~~

For reference, the discord thread where I first asked about this is here: https://discord.com/channels/461605380783472640/491165528295997450/1182757755812061235

**Comment by ellensp** [comment]
But you didn't, you said and I quote "am using a BL-Touch acting as a Z-MAX probe"

Which left everyone looking scratching their heads saying, thats not right...

**Comment by dbuezas** [comment]
Oh darn, you are right!
