### ISSUE TITLE
Marlin only reports x y and z endstops when sending M119 despite defining XMAX YMAX & ZMAX endstops

### ISSUE THREAD

**Issue by NickBramley** [MarlinFirmware/Marlin#26525]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

I am wanting to use Marlin on my Root3 CNC machine and I have a test setup which includes:-
SKR 1.4 Turbo
4 x A4988 stepper drivers
4 x stepper motors
6 x endstop switches (mechanical)
BTT 3.5 TFT

My current config files compile and provide a working environment but an older version of Marlin on an Arduino and ramps board did exactly what I would like.
What I would like is when homing:-
1   Z axis rises to the ZMAX limit switch and stops
2   X, Y and then Z perform the usual homing sequence

Currently when the Z axis first moves, it moves a fixed distance as defined with:-
#define Z_HOMING_HEIGHT  40      // (mm) Minimal Z height before homing (G28) for Z clearance above the bed, clamps, ...
                                  // Be sure to have this much clearance over your Z_MAX_POS to prevent grinding.
if the z axis is already raised, it will crash into the zmax switch (it will "grind!")

#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
#define USE_XMAX_PLUG
#define USE_YMAX_PLUG
#define USE_ZMAX_PLUG     should mean that zmax should prevent the grind

#define ENDSTOPS_ALWAYS_ON_DEFAULT
M119 reveals that none of the xmax, ymax or zmax switches are valid

### Bug Timeline

Can not compile Marlin bugfix!!

### Expected behavior

I expected Z axis to first move to the ZMAX limit switch and stop
I expected to see all six limit switches listed on M119

### Actual behavior

X Y and Z MAX limit switches are not being utilised

### Steps to Reproduce

Select auto home
when z axis moves, press the ZMAX limit switch and the Z axis should stop

### Version of Marlin Firmware

2.1.2.1

### Printer model

Root3 CNC

### Electronics

SKR 1.4T

### LCD/Controller

BTT 3.5 TFT

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin_Problem.zip](https://github.com/MarlinFirmware/Marlin/files/13659883/Marlin_Problem.zip)

**Comment by ellensp** [comment]
SKR 1.4 Turbo only has a single stop pin per axis 

The plugs on the right are for E0 detect , E1 detect and power detect. they are not endstops by default

There is some auto shuffling for sensorless and dual axis, but the default is a single endstop per axis, as marked on the pcb

You will have to edit Marlin/src/pins/lpc1768/pins_BTT_SKR_V1_4.h  to change this behavior
 
Since you have 

define X_HOME_DIR -1
#define Y_HOME_DIR -1
#define Z_HOME_DIR -1

The single stop pin is being used and the min stop pin for each axis.
