### ISSUE TITLE
[BUG] MKS Robin Nano V3.1 with MKS TS35 V2.0 white screen 

### ISSUE THREAD

**Issue by firepower9966** [MarlinFirmware/Marlin#26535]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

compile with Marlin-bugfix-2.1.x date 231216 
#define MOTHERBOARD BOARD_MKS_ROBIN_NANO_V3_1
#define MKS_TS35_V2_0
#define TFT_COLOR_UI
#define TFT_FONT NOTOSANS
#define TOUCH_SCREEN
#define TOUCH_SCREEN_CALIBRATION

white screen after updating firmware. I am only using MKS main-board and MKS display powered from USB for test.
have previously tested with OK with RepPapDiscount Full Graphic Smart Controller with cable socket rotated 180.
have restored back to original cable socket for MKS Display

### Expected behavior

Expect working Display

### Actual behavior

White Screen , can hear start up tone and encoder tone  so firmware flash correctly
firmware changes from .bin to .cur

### Steps to Reproduce

compile and load firmware

### Version of Marlin Firmware

 Marlin-bugfix-2.1.x date 231216 

### Printer model

Custom MKS Robin Nano V3.1 

### LCD/Controller

MKS TS35 V2.0

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/13691674/Marlin.zip)

**Comment by ellensp** [comment]
This is a know bug, is awaiting completion of https://github.com/MarlinFirmware/Marlin/pull/26052

Please do not create more issue reports for known issues
