### ISSUE TITLE
Dual Z Axis Stepper, Randomly Inverts Direction

### ISSUE THREAD

**Issue by AlexDoran** [MarlinFirmware/Marlin#2653]
Hi all,

I have an intermittent problem using the latest Dev Release, I am using Dual Z Steppers. Randomly an error will occur where the motor being driven by the E1 Stepper will invert its direction. This obviously gets to a point where the axis is no longer able to move. 

I havnt spotted it happening of yet, i am just alerted to it when the motors start skipping. The problem persists when manually jogging the Z Axis, and is only rectified when the machine is killed and restarted.

New wiring has been used and the problem will still randomly pop up. Sometimes the problem will start when attempting a new print after the previous has finished without power cycling.

**Comment by KiteLab** [comment]
Randomness is always hard to analyse. Let's change the likelihoods.
Is that reversing correlated to high speeds on the z-axis?
Play with z-speed and z-acceleration, z-jerk.
Is the reversing motor running smooth? Any mechanical resistances?
Is the stepper turning "powerful" when turning backwards?
Are the motors different?
Are the drivers different?
Is any of the parts hot?

**Comment by AlexDoran** [comment]
No fast movement or acceleration, mechanically everything is sound. However the print has a 450 x 450mm print area, and i recently installed a 450 x 450mm 240v AC heated bed.. could this be some kind of interference?

Thanks

Alex

**Comment by AnHardt** [comment]
Noise on the endstops line is a common problem. I do not see how this can reverse a motors direction, but i'm not that familiar with the dual-Z code.
To be sure you could look if `ENDSTOPS_ONLY_FOR_HOMING` is defined. If not - please uncomment.
