### ISSUE TITLE
[BUG] Simulator exits/crashes on Win10x64 with POWER_LOSS_RECOVERY

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#26541]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Similator exits (crashes?) on Win10x64 with POWER_LOSS_RECOVERY after arriving to this point:

![image](https://github.com/MarlinFirmware/Marlin/assets/8691781/e2f26bac-e328-4570-a9bb-52fd86618ebb)

The only change in config https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Simulator is 

`#define POWER_LOSS_RECOVERY`

### Version of Marlin Firmware

bugfix-2.1.x Bump distribution date (2023-12-16)

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by mriscoc** [comment]
Did you load an SD card image?

**Comment by vovodroid** [comment]
Issue is still here.

**Comment by thisiskeithb** [comment]
Using the latest `bugfix-2.1.x` (320e002) with matching [`bugfix-2.1.x` Simulator configs](https://github.com/MarlinFirmware/Configurations/tree/818967b50306d274fa05ca5de4da679ede65c6b4/config/examples/Simulator), I can confirm that the simulator crashes out under Windows 10 x64 (22H2 / OS Build 19045.4412) as well as macOS Monterey 12.7.5 when `POWER_LOSS_RECOVERY` is enabled.

**Comment by ellensp** [comment]
crashes in Marlin/src/sd/SdVolume.h
on  uint8_t fatType() const { return fatType_; }

fatType_ is not yet initialized

**Comment by thisiskeithb** [comment]
> crashes in Marlin/src/sd/SdVolume.h on uint8_t fatType() const { return fatType_; }
> 
> fatType_ is not yet initialized

Ahh. That would explain why it boots/works fine if you've generated `fs.img` & have it loaded.
