### ISSUE TITLE
[BUG] millis usage is not overflow proof. May cause issues when run continously more than 50days.

### ISSUE THREAD

**Issue by TBAMax** [MarlinFirmware/Marlin#26545]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I did a little code analysis, trying to familiarize myself with Marlin code.
Noticed that the default time comparison style has not been compensated for the known best practices for using millis() and micros () timing.
This will cause issues when the timer counter overflows (for millis after 40days, for micros after 70minutes() ). This is a known trap for young players.
For detailed information see the very well written detailed explanation here:https://www.norwegiancreations.com/2018/10/arduino-tutorial-avoiding-the-overflow-issue-when-using-millis-and-micros/

As the issue is somewhat hidden behind the "macro magic" in the Marlins case so it took some more time to analyse. This is also some of the reason why I decided to share this info here, to spare some work for somebody else.

The easy initial solution to solve this  would be to just edit the coding standards regarding the issue(https://marlinfw.org/docs/development/coding_standards.html#time-comparison). How to alter the "macro magic" I do not have any suggestions. I would suggest to keep it easy and just use the plain Arduino style without the macro magic.

All best Regards

### Bug Timeline

native

### Version of Marlin Firmware

bugfix 2.1.x

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thinkyhead** [comment]
Discussion at PR.
