### ISSUE TITLE
[BUG] (Can't add advanced pause feature with extruders 0 )

### ISSUE THREAD

**Issue by Leitnin** [MarlinFirmware/Marlin#26553]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

If # of extruders is set to 0, despite "#define ADVANCED_PAUSE_FEATURE" being uncommented, several of the items where #if enabled(ADVANCED_PAUSE_FEATURE) is used do not compile correctly. Manually adding #define ADVANCED_PAUSE_FEATURE to each of them appears to partially resolve the issue, but not entirely as other errors occur preventing firmware compilation. (Several of the functions contained in pause.h do not allow the firmware to compile with extruders 0 and advanced pause features (Nozzle_park_feature and park_head_on_pause are correctly enabled.)

The use case here is a machine driven using marlin with no extuders where we wish to pause and park at a location for a cleaning operation, and then resume. Current workaround will be to set extruders = 1 with a dummy temp sensor.

Additionally, as a side note, when extruders = 0, it would be really nice not to have to go through and manually delete all of the feedrate entries for E values.

### Expected behavior

I expected the firmware to compile with extruders 0 and Advanced_pause_features enabled.

### Actual behavior

did not compile.

### Steps to Reproduce

On a fresh copy of the firmware, set extruders to 0

Remove all extruder feedrates, temp sensor, etc to enable compilation

compile successfully

Uncomment #define ADVANCED_PAUSE_FEATURES
#define PARK_HEAD_ON_PAUSE
#define NOZZLE_PARK_FEATURE

compile with error

### Version of Marlin Firmware

2.1.2.1

### Printer model

custom

### Electronics

Ramps/arduino mega

### LCD/Controller

Reprap LCB

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
"* Advanced Pause for Filament Change" No filament, no advanced paused

You want NOZZLE_PARK_FEATURE not ADVANCED_PAUSE_FEATURE
