### ISSUE TITLE
[BUG] BL TOUCH Z-axis compensation only after first layer

### ISSUE THREAD

**Issue by kennyyy53** [MarlinFirmware/Marlin#26579]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hello everyone!

I just installed my BL Touch on my Ender 3 and I have a problem. When I launch my print, the BL Touch scan my tray and when printing starts, my Z axis does not move during the first layer to compensate for the defects of the tray. However I do not understand why but my Z axis moves during the second layer to finally compensate for the defects (and that creating a perfect extrusion). I would therefore like to know why this compensation for BL Touch is only active from the second layer.

I want to say that my firmware is the BUGFIX 2.1.X. In addition, I use Octoprint to manage my impressions.

### Version of Marlin Firmware

bugfix 2.1.x

### Printer model

Creality Ender-3

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [ ] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
