### ISSUE TITLE
CZ-300

### ISSUE THREAD

**Issue by aMiller1776** [MarlinFirmware/Marlin#26588]
### Is your feature request related to a problem? Please describe.

yes i have a CZ-300 buy Crazy3dPrint  and i download the new marlin 2.1.2.1 and it don't support the printer

### Are you looking for hardware support?

yes for the CZ-300 3D Printer

### Describe the feature you want

support for the 3D-300

**Comment by ellensp** [comment]
add your request to https://github.com/MarlinFirmware/Configurations/issues/649

There are no technical details on this printer and its not open source 
Internet says it has a ATSAM4S8C which marlin does not support at all
