### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Injineers** [MarlinFirmware/Marlin#26589]
,

**Comment by Injineers** [comment]
[G28_error.txt](https://github.com/MarlinFirmware/Marlin/files/13796960/G28_error.txt)

**Comment by Injineers** [comment]
new log, this time 

manually jogg'ed Z down to about 3-5mm off the bed (terminal thought it was -63 mm on z) 

ran g28, Z lifted up to around where it originally was on boot, then dropped back down to the bed & probed like normal
[g28_success_but_odd.txt](https://github.com/MarlinFirmware/Marlin/files/13796983/g28_success_but_odd.txt)

**Comment by thisiskeithb** [comment]
To close things out, this was a wiring issue.
