### ISSUE TITLE
[BUG] Simulator build failure since commit #9d324f7 (27 december)

### ISSUE THREAD

**Issue by narno2202** [MarlinFirmware/Marlin#26593]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Simulator build fails with 'usleep not declared in this scope'. Definition removed in 27 december commit #9d324f7.
Solved by reverting this commit

### Version of Marlin Firmware

latest bugfix

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
requires REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER  to fail...  would have been nice if the issue listed this requirment

**Comment by ellensp** [comment]
Confirmed usleep is used in U8glib-HAL

https://github.com/MarlinFirmware/U8glib-HAL/blob/master/src/clib/u8g_delay.cpp#L102-L110

Will not build on linux 

reverting Marlin/src/HAL/NATIVE_SIM/u8g/LCD_defines.h is sufficient to build

**Comment by ellensp** [comment]
restored https://github.com/MarlinFirmware/Marlin/commit/8f63a0a01fadf676e5328a86b350787c251fbe1b

**Comment by thinkyhead** [comment]
reverted!
