### ISSUE TITLE
[FR]  easy way of changing compiler optimization

### ISSUE THREAD

**Issue by myjtag** [MarlinFirmware/Marlin#26612]
### Describe the feature you want

I want to be able to change the firmware compiler optimization, I have tried to change the OPT = s to OPT = 0 in the main makefile, for a STM32F103CB build, and the compiler optimization does not change, I need this feature so I can debug the code with a real debugger easier, so it can help me in porting it to new arch's like CH32V307 part.

**Comment by ellensp** [comment]
you edit ini file.
You create a second env: entry with different options and swap between them by changing the build environment.
