### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by DomoVlas** [MarlinFirmware/Marlin#26619]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

[{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "cpp",
	"severity": 8,
	"message": "#error \"SRAM module disabled for the STM32 framework (HAL_SRAM_MODULE_ENABLED)! Please consult the development team.\"",
	"startLineNumber": 35,
	"startColumn": 4,
	"endLineNumber": 35,
	"endColumn": 4
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "35",
	"severity": 8,
	"message": "#error directive: \"SRAM module disabled for the STM32 framework (HAL_SRAM_MODULE_ENABLED)! Please consult the development team.\"",
	"source": "C/C++",
	"startLineNumber": 35,
	"startColumn": 4,
	"endLineNumber": 35,
	"endColumn": 9
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "cpp",
	"severity": 8,
	"message": "'SRAM_HandleTypeDef' does not name a type; did you mean 'UART_HandleTypeDef'?",
	"startLineNumber": 60,
	"startColumn": 12,
	"endLineNumber": 60,
	"endColumn": 12
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"SRAM_HandleTypeDef\" is undefined",
	"source": "C/C++",
	"startLineNumber": 60,
	"startColumn": 12,
	"endLineNumber": 60,
	"endColumn": 30
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "cpp",
	"severity": 8,
	"message": "'FSMC_NORSRAM_DEVICE' was not declared in this scope; did you mean 'FSMC_NORSRAM_TYPEDEF'?",
	"startLineNumber": 107,
	"startColumn": 12,
	"endLineNumber": 107,
	"endColumn": 12
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 107,
	"startColumn": 12,
	"endLineNumber": 107,
	"endColumn": 31
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "cpp",
	"severity": 8,
	"message": "'FSMC_NORSRAM_DEVICE' was not declared in this scope; did you mean 'FSMC_NORSRAM_TYPEDEF'?",
	"startLineNumber": 108,
	"startColumn": 12,
	"endLineNumber": 108,
	"endColumn": 12
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 108,
	"startColumn": 12,
	"endLineNumber": 108,
	"endColumn": 31
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "cpp",
	"severity": 8,
	"message": "'FSMC_NORSRAM_DEVICE' was not declared in this scope; did you mean 'FSMC_NORSRAM_TYPEDEF'?",
	"startLineNumber": 109,
	"startColumn": 12,
	"endLineNumber": 109,
	"endColumn": 12
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 109,
	"startColumn": 12,
	"endLineNumber": 109,
	"endColumn": 31
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 110,
	"startColumn": 12,
	"endLineNumber": 110,
	"endColumn": 31
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 111,
	"startColumn": 12,
	"endLineNumber": 111,
	"endColumn": 31
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 112,
	"startColumn": 12,
	"endLineNumber": 112,
	"endColumn": 31
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 113,
	"startColumn": 12,
	"endLineNumber": 113,
	"endColumn": 31
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 114,
	"startColumn": 12,
	"endLineNumber": 114,
	"endColumn": 31
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 116,
	"startColumn": 14,
	"endLineNumber": 116,
	"endColumn": 33
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 117,
	"startColumn": 14,
	"endLineNumber": 117,
	"endColumn": 33
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 118,
	"startColumn": 14,
	"endLineNumber": 118,
	"endColumn": 33
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 119,
	"startColumn": 14,
	"endLineNumber": 119,
	"endColumn": 33
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 120,
	"startColumn": 14,
	"endLineNumber": 120,
	"endColumn": 33
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 121,
	"startColumn": 14,
	"endLineNumber": 121,
	"endColumn": 33
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 122,
	"startColumn": 14,
	"endLineNumber": 122,
	"endColumn": 33
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 123,
	"startColumn": 14,
	"endLineNumber": 123,
	"endColumn": 33
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 125,
	"startColumn": 12,
	"endLineNumber": 125,
	"endColumn": 31
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_DEVICE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 126,
	"startColumn": 12,
	"endLineNumber": 126,
	"endColumn": 31
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/tft_fsmc.h",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"FSMC_NORSRAM_BANK1\" is undefined",
	"source": "C/C++",
	"startLineNumber": 131,
	"startColumn": 19,
	"endLineNumber": 131,
	"endColumn": 37
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/xpt2046.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'TOUCH_CS_PIN' was not declared in this scope; did you mean 'TOUCH_INT_PIN'?",
	"startLineNumber": 41,
	"startColumn": 13,
	"endLineNumber": 41,
	"endColumn": 13
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/xpt2046.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'TOUCH_SCK_PIN' was not declared in this scope; did you mean 'TOUCH_INT_PIN'?",
	"startLineNumber": 48,
	"startColumn": 75,
	"endLineNumber": 48,
	"endColumn": 75
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/xpt2046.h",
	"owner": "cpp",
	"severity": 8,
	"message": "#error \"TOUCH_MISO_PIN is not defined.\"",
	"startLineNumber": 39,
	"startColumn": 4,
	"endLineNumber": 39,
	"endColumn": 4
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/xpt2046.h",
	"owner": "cpp",
	"severity": 8,
	"message": "'TOUCH_CS_PIN' was not declared in this scope; did you mean 'TOUCH_INT_PIN'?",
	"startLineNumber": 76,
	"startColumn": 87,
	"endLineNumber": 76,
	"endColumn": 87
},{
	"resource": "/c:/Users/Laptop/Downloads/Marlin-bugfix-2.1.x/Marlin/src/HAL/STM32/tft/xpt2046.h",
	"owner": "cpp",
	"severity": 8,
	"message": "'TOUCH_CS_PIN' was not declared in this scope; did you mean 'TOUCH_INT_PIN'?",
	"startLineNumber": 77,
	"startColumn": 41,
	"endLineNumber": 77,
	"endColumn": 41
}]

### Bug Timeline

new bug 2024

### Expected behavior

Compile

### Actual behavior

cant compile BTT SKR V2 + TFT from anycubic

### Steps to Reproduce

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/13814784/Marlin.zip)

config files in zip

### Version of Marlin Firmware

2.1.2.1

### Printer model

Anycubic Mega X

### Electronics

BTT SKR V2 + Anycubic TFT

### Bed Leveling

No Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
you cannot be using a ANYCUBIC_TFT35
This comes with a white flat flex cable that cannot  be plugged into a BTT SKR V2

**Comment by ellensp** [comment]
This is the back of the ANYCUBIC_TFT35
![ANYCUBIC_TFT35](https://github.com/MarlinFirmware/Marlin/assets/530024/9d9c9f81-1b78-49b1-857c-85e4a342b041)

**Comment by ellensp** [comment]
You probably  want #define ANYCUBIC_LCD_CHIRON
This is a serial smart screen

But this is only a guess without seeing it.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by DomoVlas** [comment]
This is what i have inside my printer. I find it as TFT screen for Mega X. Can I use it somehow with BTT SKR V2?

![IMG_20240103_0138196](https://github.com/MarlinFirmware/Marlin/assets/155496807/6f33dbc4-08a1-4eb9-8e4b-1fc58f9e5531)
![IMG_20240103_0138127](https://github.com/MarlinFirmware/Marlin/assets/155496807/01e83277-ae0b-4a0d-b39a-362281dd22c9)

**Comment by ellensp** [comment]
Its a DMT48320C035_06W

This is DWIN display 480x320, this is a serial device 

Electrically you just need to wire it to a serial port  power and gnd

Firmware wise. The touch screen has its own firmware files.  These files change how it talks to other firmware.
Marlin has no information on the anycubic firmware on this display.
