### ISSUE TITLE
[FR] SENSORLESS HOMING - Only set CURRENT_HOME to actively homed/probed axis

### ISSUE THREAD

**Issue by sargonphin** [MarlinFirmware/Marlin#26634]
### Is your feature request related to a problem? Please describe.

Hello,

I have noticed that the stepper CURRENT_HOME is applied every time any form of homing and probing is running when sensorless homing is enabled and working. I have perfected sensorless homing to the best settings but I run into speed problems for X and Y during "travel" moves.

I have noticed for example that, after homing XY, the steppers still retain their CURRENT_HOME settings, which is faaaaar lower than running current. They also retain their spreadCycle mode instead of stealthChop which makes then less reliable at low currents.

### Are you looking for hardware support?

--

### Describe the feature you want

When an axis is not being actively probed, set currents & stealthChop configuration to their running configuration to allow for faster speeds when homing/probing

### Additional context

This feature right now mainly applies for sensorless homing because it uses extremely small currents compared to regular moves. A printer with endstop switches wouldn't benefit much from such feature because it uses homing currents closer to running currents, if different at all

**Comment by Mjankor** [comment]
Also related: https://github.com/MarlinFirmware/Marlin/issues/26369
