### ISSUE TITLE
maybe HOMING do not works with capacitive probe attached to z-max endstop pin instead z-min... on BTT_SKR_V1_3 in the last version.

### ISSUE THREAD

**Issue by ste72ste** [MarlinFirmware/Marlin#26648]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Z HOME stops work from old version to newest with capacitive probe attached to z-max end stop pin instead z-min... on BTT_SKR_V1_3
may be some  difference in the 2 software version or may be my fault in something else.
attached the zip with configs file  and versions   
(sorry I'm not so skilled with bug report)

### Expected behavior

HOMING 

### Actual behavior

start homing but stops immediately  

### Version of Marlin Firmware

"bugfix-2.1.x"

### Electronics

BTT_SKR_V1_3

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config.zip](https://github.com/MarlinFirmware/Marlin/files/13866340/config.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
