### ISSUE TITLE
[FR] Allow input shaping tuning during print

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#26653]
### Describe the feature you want

Currently input shaping could be tuned only when printer is in idle:

```
    // M593 - Acceleration items
    #if ENABLED(SHAPING_MENU)
      if (!is_busy) SUBMENU(MSG_INPUT_SHAPING, menu_advanced_input_shaping);
    #endif
```

Is is possible to allow frequency adjusting while printing?

**Comment by EvilGremlin** [comment]
Just remove condition, but what's the point? Adjusting on real print is absolutely useless, you won't be able to see any difference. Just print calibration tower.

**Comment by vovodroid** [comment]
> Just remove condition

Will it work? I mean will it affect planner immediately?

> what's the point?

I confused with X and Y settings before 10 hours print))). Noted it after several hours.

**Comment by EvilGremlin** [comment]
I don't think that very specific user error warrants any code changes... and you could've fix it with gcode.

**Comment by vovodroid** [comment]
> you could've fix it with gcode.

In the middle of the print?

**Comment by EvilGremlin** [comment]
yep

**Comment by vovodroid** [comment]
How? Could gcode commands issued via COM port while printing?

**Comment by EvilGremlin** [comment]
of course

**Comment by vovodroid** [comment]
> Just remove condition, but what's the point? Adjusting on real print is absolutely useless, you won't be able to see any difference. Just print calibration tower.

@EvilGremlin I found it extremely useful while tuning IS. I run gcode loop moving extruder/bed with frequency oscillating back and force within given range, and adjust IS until I get the most smooth result.

**Comment by vovodroid** [comment]
PR #27248 is created
