### ISSUE TITLE
[BUG] Z_CLEARANCE_FOR_HOMING has no effect on Homing (Delta printer)

### ISSUE THREAD

**Issue by Orion3090** [MarlinFirmware/Marlin#26664]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

In a delta printer you need some height before homing to avoid mechanical damage on the printer, Z_CLEARANCE_FOR_HOMING seems to be the configuration needed, as it should raise the extruder to the configured clearance height an then home each axis, but homing does not raise to the specified height for homing, seems to ignore the Z_CLEARANCE_FOR_HOMING which i got at 215, the max height on my printer is 290

### Bug Timeline

First time trying with bugfix-2.1.x

### Expected behavior

When homing below the specified Z_CLEARANCE_FOR_HOMING the extruder should raise to the specified height and then home all the axis.

### Actual behavior

When homing below the specified Z_CLEARANCE_FOR_HOMING the printer attempts to home all the axis without raising to any height.

### Steps to Reproduce

With bugfix-2.1.x installed:
1. Home all axis with the extruder close to the top
2. Move Z axis down close to the hotbed
3. Home all axis when close to the hotbed, the printer attempts to home each individual axis which leads to collition of the extruder with the belts and towers

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Anycubic Kossel linear plus

### Electronics

SKR 1.4 turbo

### LCD/Controller

RepRapDiscount Smart Controller

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

None

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[this is my configuration](https://drive.google.com/file/d/1Ma-o0434wloERgwVZYeuXZ_pGB26pO-U/view?usp=drive_link).

**Comment by EvilGremlin** [comment]
Tis would be bug indeed, bit not the one you describe. Z_CLEARANCE_FOR_HOMING is not needed and not applicable to deltas. So if this value used at all - it's a bug.
Moreso, you trying to use it wrong even for cartesian. Z_CLEARANCE_FOR_HOMING 215 means "raise Z up 215mm from wahtever current unknown position is"

**Comment by Orion3090** [comment]
> EvilGremlin

Ok i did not know that, what configuration should be used for avoiding the crash between extruder and print parts when homing on deltas?

**Comment by EvilGremlin** [comment]
There should be no crash possibility at all. Homing goes straight up.

**Comment by Orion3090** [comment]
> There should be no crash possibility at all. Homing goes straight up.

Maybe i didn't explain the mechanical problem correctly, on a Delta, when the extruder is close to the bed, if one of the axis (only one) is raised too much without the other two, it causes the extruder to collide with the belts and the tower of one of the axis (maybe there's a name for that, i don't know it), which is what happens when you home (G28) with the extruder too low.

That would be avoided if the extruder is raised to a considerable height, close to the top of the printer, in which height each axis can raise and home without any collition of the printer parts, which i toght to be the Z_CLEARANCE_FOR_HOMING according to the commets on the firmware.

**Comment by robherc** [comment]
When using G28 on a delta, all three towers are **supposed** to lift at the same time & same speed, with each tower stopping when it reaches its endstop.

**Comment by Orion3090** [comment]
> When using G28 on a delta, all three towers are **supposed** to lift at the same time & same speed, with each tower stopping when it reaches its endstop.

Ok, i didn't knew that either, i have everything configured but with G28 each tower attempts to home **one at a time**, that's the bug then? is there a configuration so that G28 does it with each tower simultaneously?

**Comment by EvilGremlin** [comment]
Then you did not enable DELTA kinematic in config

**Comment by Orion3090** [comment]
> Then you did not enable DELTA kinematic in config

I did configure #define DELTA on line 964 of my Configuration.h, what other reason could it be for the G28 behaving like that?

**Comment by EvilGremlin** [comment]
Some other user error (you still somehow flashed build for cartesian) or very fresh bug in delta homing. Try 2.1.2.1

**Comment by Orion3090** [comment]
> Some other user error (you still somehow flashed build for cartesian) or very fresh bug in delta homing. Try 2.1.2.1

You are totally right, i just migrated my configuratoin to 2.1.2.1 and two of the issues i had ([a problem with endstops](https://github.com/MarlinFirmware/Marlin/issues/26659)) and this one with the Homing of axis seem to me solved, thanks a lot!
