### ISSUE TITLE
[BUG] (Broken link)

### ISSUE THREAD

**Issue by minding-myown-business** [MarlinFirmware/Marlin#26668]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

There is an Aliexpress link (in `Configuration.h` that leads you to a 404 page.)
![image](https://github.com/MarlinFirmware/Marlin/assets/150592702/837c5272-954e-4951-9152-fed575629569)
![image](https://github.com/MarlinFirmware/Marlin/assets/150592702/27999f42-3b22-46a8-91e6-9d946104408b)

### Bug Timeline

Idk i just found it

### Expected behavior

I expected it to be an actual page

### Actual behavior

It was a dead link

### Steps to Reproduce

1. Open `Configuration.h`
2. Go to line 2985 in marlin 2.1.2.1 (or line 2811 in bugfix branch)
3. Click on link

### Version of Marlin Firmware

2.1.2.1

### Printer model

Ender 3 (but does it really matter?)

### Electronics

Not an electronics issue, its a link in the configuration

### LCD/Controller

Dosen't matter

### Other add-ons

Dosen't matter

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[configurations.zip](https://github.com/MarlinFirmware/Marlin/files/13928587/configurations.zip)

**Comment by ellensp** [comment]
Since pr has been created, closing this issue
