### ISSUE TITLE
[FR] Have AUTO_BED_LEVELING_BILINEAR use a MESH_INSET instead of PROBE_MARGIN

### ISSUE THREAD

**Issue by sargonphin** [MarlinFirmware/Marlin#26688]
### Is your feature request related to a problem? Please describe.

Due to the way `PROBE_MARGIN` and home offsets are not handled correctly with Z-Alignment, in some configuration it has to be set to zero even when using a fix-mounted probe. This causes bilinear leveling to be done too close to the edge of the bed, where an induction sensor will have lower sensitivity.

This causes the points on the edge of the bed to be "too high" and mess up leveling around the edges of the bed, where adhesion is already not optimal because of heat spread on a heated bed.

### Are you looking for hardware support?

--

### Describe the feature you want

Having the possibility to define a `MESH_INSET`, as it is already possible with every other form of bed leveling, even if it comes at the cost of inability to extrapolate points outside of the mesh

### Additional context

In my specific case, Unified Bed Leveling cannot be used because of unidentified problems when enabling a mesh. Since most features of UBL are not useful (still in my specific case), I have to resort to bilinear leveling instead

**Comment by classicrocker883** [comment]
have you tried Mriscoc Professional firmware? its possible to adjust `mesh_inset` on the fly. well i guess then it depends on what UI youre using. in my configurations, I always leave `probe_margin 0`. I also don't see the use when `mesh_inset` basically defines the bounds of the bed. if "margin" is like "inset", I can see how it might complicate using both.

so what is it youre trying to fix exactly? this?:
>home offsets are not handled correctly with Z-Alignment

can you explain how you mean by
> the points on the edge of the bed to be "too high"

I'm trying to picture this, if a bed is flat, and its probing the bed, how would the edge be high?  
anyway what would need to be done?

**Comment by sargonphin** [comment]
I fixed this problem by using `PROBING_MARGIN_LEFT/RIGHT/FRONT/BACK` per side instead of using the default `PROBING_MARGIN` value
