### ISSUE TITLE
[BUG] (LA on 2208 drivers not working) 

### ISSUE THREAD

**Issue by Dtwpurple** [MarlinFirmware/Marlin#26699]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Tmc2208 standalone drivers do not allow for linear advanced control. 

### Steps to Reproduce

1.Enable linear advance in config
2. flash firmware
3. put hands in head after hours of messing with k values and nothing changes. 

### Version of Marlin Firmware

2.1.x bugfix

### Printer model

Ender 3 4.2.2 board. 

### Electronics

stock. 

### LCD/Controller

stock one, with the knob

### Bed Leveling

No Bed Leveling

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/13968739/Configuration_adv.zip)

**Comment by EvilGremlin** [comment]
Your config is impossible: `_DRIVER_TYPE  TMC2208` can't exist on `BOARD_CREALITY_V422`.
Also if your bowden is sloppy you might well not see any difference.
Show photos of calibration pattern, 0 to 1 with 0.01 step

**Comment by thisiskeithb** [comment]
> Your config is impossible: `_DRIVER_TYPE TMC2208` can't exist on `BOARD_CREALITY_V422`.

We should probably clarify that TMCs are installed in `*_STANDALONE` mode in the warning:

https://github.com/MarlinFirmware/Marlin/blob/220060798930227fea158a81b5f83e241b7630ff/Marlin/src/inc/Warnings.cpp#L666-L668

**Comment by Dtwpurple** [comment]
2208 is possible on v422. look in the config. it tells you to use that instead of the tmc2225 drivers. as those dont exist.  " Use TMC2208/TMC2208_STANDALONE for TMC2225 drivers" .  its not a bowden issue. there is no difference when setting k values. heavy bulging all the way up the tower with NO CHANGES.

**Comment by Dtwpurple** [comment]
> > Your config is impossible: `_DRIVER_TYPE TMC2208` can't exist on `BOARD_CREALITY_V422`.
> 
> We should probably clarify that TMCs are installed in `*_STANDALONE` mode in the warning:
> 
> https://github.com/MarlinFirmware/Marlin/blob/220060798930227fea158a81b5f83e241b7630ff/Marlin/src/inc/Warnings.cpp#L666-L668

they are in standalone mode. and im using the right drivers as the config tell you to use 2208 instead of 2225. anytime you build marlin with ender 3 config it will shoot that error as a reminder to check them.

**Comment by thisiskeithb** [comment]
If you have TMC2208s, use `TMC2208_STANDALONE`: https://github.com/MarlinFirmware/Marlin/issues/26699#issuecomment-1896856355

**Comment by Dtwpurple** [comment]
> If you have TMC2208s, use `TMC2208_STANDALONE`: [#26699 (comment)](https://github.com/MarlinFirmware/Marlin/issues/26699#issuecomment-1896856355)

bruh do you guys even check the files? it is setup as tmc2208 standalone.

**Comment by EvilGremlin** [comment]
We did. Its not _STANDALONE.
Print this and show photos https://marlinfw.org/tools/lin_advance/k-factor.html

**Comment by thisiskeithb** [comment]
> bruh do you guys even check the files? it is setup as tmc2208 standalone.

"bruh", not when I downloaded your config:

<img width="323" alt="image" src="https://github.com/MarlinFirmware/Marlin/assets/13375512/b2b884d4-b750-4926-8325-6644d07e9ff6">

`#define X_DRIVER_TYPE  TMC2208` is not the same as `#define X_DRIVER_TYPE  TMC2208_STANDALONE`

**Comment by i-Fixit** [comment]
As far as I'm aware for Linear Advance to work with the Creality v4.2.2 board you'd need to do a UART mod on it. This is what I did for my Ender 6 which uses the v4.3.1 board ... basically the same board layout, although I needed to also change one of the stepper driver chips as well ;-)

[Ender 6 UART mod](https://www.reddit.com/r/ender6/comments/18ts4mg/ender_6_431_uart_mod/)

Obviously you'd need to modify the correct pins file for the v422 board, but the same pins do appear to be available on said board.

**Comment by classicrocker883** [comment]
> As far as I'm aware for Linear Advance to work with the Creality v4.2.2 board you'd need to do a UART mod on it. 

I thought that has since been solved since LA became available for these boards. I remember there was a whole write up about the **PR**, dont remember which one it was, but AFAIK performing that mod was no longer necessary.  
[here is a link to a write up and info about the mod before LA changes in code](https://www.reddit.com/r/ender3v2/comments/n3clew/ender_3v2_422427_board_tmc_uart_mods/)

before, yes it was required to do that mod, but LA should work normally just by enabling it.

edit: https://github.com/MarlinFirmware/Marlin/pull/24533

**Comment by robherc** [comment]
@i-Fixit the 4.2.2 board:
#1 works great with linear advance...so this is a nonsensical bug report
#2 has soldered-down 2208s in standalone mode, so UART is not much of an option without major PCB surgery

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
