### ISSUE TITLE
[FR] Restore chamber heating on power loss recovery

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#26690]
### Is your feature request related to a problem? Please describe.

After print recover chamber heating is not restored as bed.

### Describe the feature you want

Save chamber temperature on power loss and restore it on resume.

**Comment by ellensp** [comment]
Please test my PR to add this feature

**Comment by vovodroid** [comment]
I don't have it, just thought about such case.

**Comment by ellensp** [comment]
If you personally don't have a need for a feature, please don't waste our time requesting it!

**Comment by vovodroid** [comment]
Well, I suggested that it's not personal case, but general improvement useful for a lot of people, and making Marlin better.
