### ISSUE TITLE
[BUG] No alert, the POWER LOSS RECOVERY is enabled but POWER Outage deduction module(circuit) not connected to AC outlet. 

### ISSUE THREAD

**Issue by AnandRaj-R** [MarlinFirmware/Marlin#26728]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

No alert message on the sceen for the POWER LOSS RECOVERY is enabled but POWER Outage deduction module(circuit) not connected to AC outlet.

### Expected behavior

When clicking "START PRINT", but the Power Outage Deduction module(circuit) not connected to ac outlet, display a alert message on the screen. Example "Check connection".

### Actual behavior

**_Printer halted_**, If we start a print with POWER LOSS Recovery is enabled, But the Power Outage Deduction module(circuit) not connected to the Ac outlet.

### Steps to Reproduce

If we start a print and the POWER LOSS RECOVERY is already enabled, the below mentioned steps are helps to prevent the printer from halting and save time and power.

Step1: Check the POWER LOSS RECOVERY is enabled, if enabled(true)
Step2: Check the POWER LOSS PIN state, if HIGH(Not connected to AC oulet)
Step3: if the POWER LOSS RECOVERY is true and the POWER LOSS PIN state is HIGH, Display a alert message on 
           the screen. Example "Device is offline"
Step4: if the POWER LOSS RECOVERY is true and the POWER LOSS PIN state is LOW(Connected to Ac outlet), then the printer continue to start printing.

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Anet A8

### Electronics

BTT Skr2

### LCD/Controller

REPRAP_DISCOUNT_SMART_CONTROLLER

### Other add-ons

MKS Power Outage Deduction module

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin_18012024.zip](https://github.com/MarlinFirmware/Marlin/files/14041340/Marlin_18012024.zip)

**Comment by shabgarde** [comment]
Hi. I have similar issue . i use Mks robin nano v3.1.
All boards with stm32f4.... processor seem to have this problem.
