### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by FFF3DPI** [MarlinFirmware/Marlin#26749]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hello.
Our team is making custom FFF 3D printer with marlin firmware. When I run this printer and try to heat heating bed to 60 using 'Pronterface' program, "Unknown command : G200 " appeared and stopped heating bed. I don't know what happened in program. Please help me.

### Bug Timeline

I think it's old issue. It happend when I heat  heating bed.

### Expected behavior

I expected heat bed to heat to 60.

### Actual behavior

"Unknown command : G200 " appeared and stopped heating bed.

### Steps to Reproduce

Run 'pronterface'.
heat nozzle and heat bead.

### Version of Marlin Firmware

2.0.9.2

### Printer model

custom FFF 3D printer

### Electronics

12V Voltmeter

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

![Uploading Heat bed error.jpg…]()

**Comment by EvilGremlin** [comment]
typical bad serial conenction (unless its always G200 - then it's user error)

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.
