### ISSUE TITLE
[BUG] one click print prevents touch screen calibration

### ISSUE THREAD

**Issue by joryvd** [MarlinFirmware/Marlin#26750]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After flashing Marlin to the board, and having EEPROM_INIT_NOW as well as ONE_CLICK_PRINT enabled, if there is a gcode file on the sd card it is not possible to calibrate the touchscreen. As soon as the firmware is flashed, the printer asks if you want to print the most recent file. As the EEPROM is init' the touchscreen doesn't work as it is not calibrated yet. Thus there is no way to press cancel and then calibrate the touchscreen. For now the solution I found is to remove the SD card and power cycle the printer.

### Bug Timeline

When I moved to the bugfix branch. I'm on commit 3ef192e

### Expected behavior

The board checks if the eeprom is initialized and/or if calibration is missing and suppressed the one click print feature

### Actual behavior

The screen prompted to print the most recent G code on the SD card and didn't allow me to exit or calibrate the touch screen

### Steps to Reproduce

Build Marlin and copy to an SD card which also contains g code
Flash the firmware to the board with EEPROM_INIT_NOW and ONE_CLICK_PRINT enabled

### Version of Marlin Firmware

bugfix-2.1.x commit 3ef192e

### Printer model

Creativity Elf

### Electronics

MKS robin Nano V1.2

### LCD/Controller

3.5" FSMC touch display

### Other add-ons

No physical control buttons

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/14090791/Marlin.zip)

**Comment by ellensp** [comment]
put your touch screen calibration into your configuration files. then touch is always calibrated

ie enable and fill out these parameters

//#define TOUCH_CALIBRATION_X 12316
  //#define TOUCH_CALIBRATION_Y -8981
  //#define TOUCH_OFFSET_X        -43
  //#define TOUCH_OFFSET_Y        257
