### ISSUE TITLE
Graphical displays can not display negative X and Y coordinates

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#2675]
Graphical displays can not display negative X and Y coordinates because they use `ftostr31ns()` to convert.
The `ns` means 'no sign' here.
Not so nice if you have a delta.

**Comment by AnHardt** [comment]
Will return to this when #2661 is fixed - same code area.

**Comment by AnHardt** [comment]
https://github.com/MarlinFirmware/MarlinDev/pull/181
is related/similar but for the C-LCD's

**Comment by AnHardt** [comment]
We have space for 5 chars. We want to display positive and negative numbers with up to 3 digits before the dot and 1 behind. With sign and dot we'd need 6 chars. We could drop the fraction for numbers < -99.9

```
12345

-999.
-99.9
 -9.9
 -0.1
  0.0
  0.1
  9.9
 99.9
999.9 
```

Looks like a plan.

**Comment by thinkyhead** [comment]
Do we have a patch for this yet? Seems like it should be a quick one. Still waiting for #2661?

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
