### ISSUE TITLE
[BUG] strange stepper problem 2.1.2.1 Bug Fixes

### ISSUE THREAD

**Issue by mytique38** [MarlinFirmware/Marlin#26779]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I encounter a strange bug. 

Everything worked before with the same configuration in Marlin 2.0.X.

The problem is that the extruder and the Z-axis do not respond correctly. Defaut Axis steps per unit.

The extruder makes a lot of noise when shrinking on extrusion and the Z axis does not mount properly. 

Yet when I extrude 200 mm -> 200 mm goes out and when I mount the Z axis of 200 mm it goes up well of 200 mm 

### Version of Marlin Firmware

Marlin 2.1.2.1 Bugfixes 

### Printer model

Dagoma Disco Ultimate Modding Blacl Evo 

### Electronics

SKR 1.4 Turbo TMC 2209 v1.2

### LCD/Controller

BTT TFT 

### Other add-ons

Touch Mi 

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

![1 thumb jpg 27459c217e4196ed002ab00522c76fe6](https://github.com/MarlinFirmware/Marlin/assets/63399447/d4a33dc6-9ff9-4e25-8936-1a4aa617e28c)
![3 jpg b4da9bc4e3c66d9e8bb1155d78a55704](https://github.com/MarlinFirmware/Marlin/assets/63399447/c28e62b9-aa9d-48b2-84ef-da5a2b155799)
![4 jpg d4b3a3bea1d4fef2305943da035288c7](https://github.com/MarlinFirmware/Marlin/assets/63399447/e31760ff-0838-451a-a99a-ae1742b56fd4)
![5 jpg 0d04c10ed310a2d2953a9a76641d3
![Money CLip](https://github.com/MarlinFirmware/Marlin/assets/63399447/0e70d6fb-cd86-4048-8a4c-84c0d6a4dbfe)
![Money Fail](https://github.com/MarlinFirmware/Marlin/assets/63399447/765aaba2-2fe9-4762-87b0-e33be88ae3ba)
210](https://github.com/MarlinFirmware/Marlin/assets/63399447/3891eef4-b6d4-462e-9009-b87e0e110ab5)
![6 jpg d23193117a0928e225cfa8bc7a9833e1](https://github.com/MarlinFirmware/Marlin/assets/63399447/89e6e42f-b22d-4235-a2f5-05a607e09e2c)
[Bruit extrudeur.zip](https://github.com/MarlinFirmware/Marlin/files/14205768/Bruit.extrudeur.zip)

[Marlin 2.1 Pas OK.zip](https://github.com/MarlinFirmware/Marlin/files/14205786/Marlin.2.1.Pas.OK.zip)

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by ellensp** [comment]
"yet when I extrude 200 mm -> 200 mm goes out"
When you extrude 200mm, 200mm of filament should be taken in,  some 875mm out on a 0.4mm ho-tend (presuming 1.75mm filament)

**Comment by mytique38** [comment]
> Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

Ok thank you i have already works on 2.1.x download last week 

have you found errors on shared configuration files?

**Comment by thisiskeithb** [comment]
You are not using the latest `bugfix-2.1.x` which is now a couple versions ahead of what you are running.

**Comment by mytique38** [comment]
> You are not using the latest `bugfix-2.1.x` which is now a couple versions ahead of what you are running.

Thank you th issue is solved with a new Marlin :) 

![Screenshot 2024-02-09 082158](https://github.com/MarlinFirmware/Marlin/assets/63399447/4e19de7a-f499-4ecc-a71d-47090b19e165)

**Comment by mytique38** [comment]
Issue solved with a new Marlin 

Thank you 

![Screenshot 2024-02-09 082158](https://github.com/MarlinFirmware/Marlin/assets/63399447/d03b8764-b7e4-4ac0-a536-edf6af4a830f)
