### ISSUE TITLE
[FR] TFT variable pointers and description pointers not found anywhere

### ISSUE THREAD

**Issue by Riky04-theSwagOne** [MarlinFirmware/Marlin#26787]
### Is your feature request related to a problem? Please describe.

I was trying to build a new UI for my printer (ender 5 plus) which has a DGUS display. I've been searching for months for a table with all the pointer values. At the moment I found, on a "dgus resources" an Excel file containing SOME of the variables, but, for example, I miss all the values for the second extruder, because the table was relative to the original ender 5, which only has 1 extruder.

### Describe the feature you want

I only need the table that's used to configure TFT displays.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
There are no variables for a second extruder, until you add that feature to the UI using the DGUS tools

See https://github.com/coldtobi/Marlin_DGUS_Resources and https://github.com/Neo2003/DGUS-reloaded

The spreadsheet is generated by the DGUS tool, to make interfacing to the display easier.
