### ISSUE TITLE
[BUG] M906 (Set stepper current) is executed when read from sd card, not in the gcode sequence.

### ISSUE THREAD

**Issue by 3D-Lasers-Lab** [MarlinFirmware/Marlin#26794]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

If executing the following gcode from an sd card the X motor will move with a current of 400ma, despite previously being set as 800ma.

M906 X800
G1 F1000 X200
M906 X400

For pushing parts off the bed it would be nice to be able to turn up the motor current very high, push the parts off the bed, and then turn the current back down before overheating. 

### Bug Timeline

Not Sure

### Expected behavior

Set the motor current to 800, move the motor, and then set the current to 400.

### Actual behavior

Sets the motor current to 800, set the motor current to 400, move the motor.

### Steps to Reproduce

Run the following gcode (I assume there has to be a decent sd card buffer, that is my guess as to why this is happening). What you will see is that both the M906 will report the current before the stepper even starts the movement.

M906 X950
M906
G1 F1000 X100
M906 X400
M906

Reading through serial monitor looks like this.
READ: X driver current: 950
READ: Y driver current: 400
READ: Z driver current: 800
READ: Z2 driver current: 800
READ: E driver current: 800
READ: X driver current: 400
READ: Y driver current: 400
READ: Z driver current: 800
READ: Z2 driver current: 800
READ: E driver current: 800

### Version of Marlin Firmware

2.0.9.2.x

### Printer model

Custom

### Electronics

BTT Skr 1.3

### LCD/Controller

64x128

### Other add-ons

NA

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

NA
[ConfigFiles3DLL.zip](https://github.com/MarlinFirmware/Marlin/files/14275368/ConfigFiles3DLL.zip)

**Comment by ellensp** [comment]
not all gcode are executed in sequence, this is by design
this is why we have M400

you need
M400
M906 X800
G1 F1000 X200
M400
M906 X400
