### ISSUE TITLE
[FR] Input Shaping Calibration Pattern support for Prusa mk3.5

### ISSUE THREAD

**Issue by numo68** [MarlinFirmware/Marlin#26804]
### Describe the feature you want

This is not about the firmware itself but about the - really nice! - generator at https://marlinfw.org/tools/input_shaping/freq-calibr.html

As the Prusa mk3.5 upgrade is out now and I kind of doubt the one preset value is optimal for everyobody I wanted to calibrate the input shaping using this generator. I have identified the following issues:

- M501 at the beginning and the end of the generated g-code destroy the Z offset stored with the stored steel sheet. Somehow this is even stored and not reset at firmware reset, requiring a new calibration
- Setting the Z-offset does not work, as Prusa does not seem to allow offsets below zero
- Zeta = 1.0 crashes the Prusa firmware
- The mesh bed leveling should be using G80 for Prusa

A support for Prusa mk3.5/3.9/4.0 would be nice.

Thanks

**Comment by thisiskeithb** [comment]
While Prusa’s firmware is Marlin 2-based, they’ve implemented their own Input Shaping code that is not compatible with Marlin’s.

This request should go to Prusa for them to implement their own version of the tool that is compatible with their code & Input Shaping implementation.
