### ISSUE TITLE
[BUG] Unable to compile SKR 1.4 with Anet ET5X TFT

### ISSUE THREAD

**Issue by mslagle** [MarlinFirmware/Marlin#26813]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Trying to install SKR 1.4 board on an ANET ET5X using existing hardware.  During the compilation, I get the error:

In file included from m:\code\marlin\marlin\src\inc\marlinconfig.h:56,
                 from Marlin\src\HAL\LPC1768\MinSerial.cpp:24:
m:\code\marlin\marlin\src\hal\lpc1768\inc\sanitycheck.h:81:4: error: #error "Sorry! FSMC TFT displays are not current available for HAL/LPC1768."
   81 |   #error "Sorry! FSMC TFT displays are not current available for HAL/LPC1768."

### Expected behavior

The ANET_ET5_TFT35 LCD to be supported.  Uses the same connectors as the stock board.

### Actual behavior

Error shown during compilation.

### Version of Marlin Firmware

Bugfix-2.1.x

### Printer model

ANET ET5X with SKR 1.4

### Electronics

Stock

### LCD/Controller

ANET_ET5_TFT35

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Copied most of the configuration from the ET5X example from the configurations repo.  Included is my configuration.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/14391550/Marlin.zip)

**Comment by ellensp** [comment]
FSMC has hardware requirement, the micro controllers FSMC pins must be wired to the the external ports.

The two EXP ports on the skr 1.4 are not FSMC capable, the best the can do is SPI tft's

There is no support for FSMC displays on the skr 1.4 as the required IO pins for FSMC functionality are used for other things.

You simply cannot use this display on a skt 1.4  (not without a large number of board modifications, and then you would ahve to implement the feature on the lpc176x chip)

**Comment by ellensp** [comment]
NOTE:

the original board sends 3.3v to the TFT, the SKR 1.4 sends 5V
Just plugging in this display (and turning it on) will likely kill the display!

If you dig around the internet a bit you can find the original P1 and P2 pins for the old controller
Its running a 8 bit parallel interface in P2 

```
P1_1_LCD_9_CSX => PD7
P1_2_LCD_11_WRX => PD5
P1_3_TOUCH_15_/CS => PB2
P1_4_TOUCH_14_DIN => PE5
P1_5_TOUCH_12_DOUT => PE4
P1_6_TOUCH_16_DCLK => PB0
P1_7_TOUCH_11_/PENIRQ => PB1
P1_8_LCD_12_RDX => PD4
P1_9 => GND
P1_10 => 3.3V

P2_1_LCD_15_RESX => PE6
P2_2_LCD_10_DCX => PD13
P2_3_LCD_26_DB9 => PD15
P2_4_LCD_25_DB8 => PD14
P2_5_LCD_28_DB11 => PD1
P2_6_LCD_27_DB10 => PD0
P2_7_LCD_30_DB13 => PE8
P2_8_LCD_29_DB12 => PE7
P2_9_LCD_32_DB15 => PE10
P2_10_LCD_31_DB14 => PE9
```
The skr 1.4 doesn't even have 10 IO pin on the exp2 port, it has 7, and they are not pins that can be used for FSMC
