### ISSUE TITLE
[BUG] Part cooling fan not adjustable

### ISSUE THREAD

**Issue by brunofresco** [MarlinFirmware/Marlin#26812]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When i select a fan spped in the menu the fan only spins at 100% until about 45% if i go under that value it turns off. There is absolutely no control over it only 0 or 100.

### Expected behavior

I Expected the fan not to spin at 100% Up to 45%

### Actual behavior

I think the porblem is clear :)

### Steps to Reproduce

Temperature Menu
Fan 1 > 50% = Fan Full Power

### Version of Marlin Firmware

2.1.2.1 up to 2.1.2.2

### Printer model

Modded Tevo Tarantula

### Electronics

Upgrade: MKS Eagle

### LCD/Controller

RepRap Full Discount Smart Graphic Controller

### Other add-ons

None at all

### Bed Leveling

ABL Linear grid

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/14390278/Configuration.zip)

**Comment by ellensp** [comment]
Fan1 is PC14 on a STM32F407VE This pin has no hardware PWM capability.

You MUST enable FAN_SOFT_PWM
