### ISSUE TITLE
TWI/Wire feature request to RC2 or later

### ISSUE THREAD

**Issue by justmyopinion** [MarlinFirmware/Marlin#2682]
Wire library in Arduino has a default speed of 100kHz (100000) which set the speed for TWI/I2C services for LCD etc. 
Time has come to speed this up as it is no problem to have TWI running at higher speeds.
Speeds > 400khz are available without any changes, I have tested my own up to 800 kHz and still running.
Therefore it would be nice to have a constant defined in configuration for this like TWI_SPEED =400000.
This could then be used to change wire speeds on the run. Wire lib has a service "setClock( TWI_SPEED) that may be called somewhere or it could be changed in register macro TWBR=TWI_SPEED. Speeds may be set to anything below 1000000.

**Comment by thinkyhead** [comment]
I'm surprised no one has commented on this. Has this been confirmed to be compatible with various configurations including deltabots and graphical displays? And is it in good shape to submit a PR with this concept?

**Comment by Bio-Printer** [comment]
Would a higher wire speed allow the I^2C LCD panels to be updated quicker?   Or more specifically, can the processor spend less time in the LCD Update Code?   If so...   This should be carefully explored.

**Comment by thinkyhead** [comment]
I'd like to hear @AnHardt's comments on this. Specifically whether this would mean more time taken away from the stepper ISR.

**Comment by AnHardt** [comment]
I have no clue and no hardware to test.
Later he made https://github.com/MarlinFirmware/Marlin/pull/2719
And finally we ended with https://github.com/MarlinFirmware/MarlinDev/pull/260#issuecomment-152870027 ++
Maybe we can reactivate him now.

**Comment by thinkyhead** [comment]
It may comfort @justmyopinion to know that we've had some positive personnel changes, and we're taking a more proactive approach to issues and feature requests going forward.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
