### ISSUE TITLE
[FR] Set different TMC current depending on movement speed/acceleration

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Marlin#26855]
### Is your feature request related to a problem? Please describe.

Using constant high current necessary for smooth operation, but could cause excessive heating.

### Are you looking for hardware support?

TMC drivers

### Describe the feature you want

Like HYBRID_THRESHOLD switches to spreadSycle above speed threshold, this feature will increase current above certain speed/acceleration, thus preventing  skipping steps and overheating.

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/19675
