### ISSUE TITLE
1.1rc2  G29 Z axis  points increase with every probe

### ISSUE THREAD

**Issue by delboy711** [MarlinFirmware/Marlin#2685]
With both RC1 and RC2  If I do a G29 P3 V4 following a G28 then the reported Z position of each successive point is higher than the last.  If I then try a print, it  tries to print up in the air.

For testing purposes my proximity sensor is disabled, and I am using the microswitch on the Z axis so the Z probe readings ought to be much the same no matter where the head is on the bed.

(I do get similar results if I enable the proximity sensor)

Send: M115
Recv: FIRMWARE_NAME:Marlin 1.1.0-RC2 From Archive SOURCE_CODE_URL:http:// ... PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer EXTRUDER_COUNT:1 UUID:00000000-0000-0000-0000-000000000000
Recv: ok
[...]
Send: G28
Recv: ok
[...]
Send: G29 P3 V4
Recv: G29 Auto Bed Leveling
Recv: Bed X: 30.000 Y: 40.000 Z: 16.213
Recv: Bed X: 105.000 Y: 40.000 Z: 32.334
Recv: Bed X: 180.000 Y: 40.000 Z: 48.454
Recv: Bed X: 180.000 Y: 105.000 Z: 64.593
Recv: Bed X: 105.000 Y: 105.000 Z: 80.687
Recv: Bed X: 30.000 Y: 105.000 Z: 96.884
Recv: Bed X: 30.000 Y: 170.000 Z: 112.993
Recv: Bed X: 105.000 Y: 170.000 Z: 129.155
Recv: Bed X: 180.000 Y: 170.000 Z: 145.349
Recv: Eqn coefficients: a: 0.07179106 b: 0.74485831 d: -5.00781917
Recv: Mean of sampled points: 80.74036407
Recv: planeNormal x: -0.071791 y: -0.744858 z: 1.000000
Recv: 
Recv: Bed Height Topography:
Recv: +-----------+
Recv: |...Back....|
Recv: |Left..Right|
Recv: |...Front...|
Recv: +-----------+
Recv:  +32.25288 +48.41463 +64.60839
Recv:  +16.14364 -0.05361 -16.14712
Recv:  -64.52712 -48.40586 -32.28586
Recv: 
Recv: 
Recv: Corrected Bed Height vs. Bed Topology:
Recv:  +20.47647 +31.26772 +42.09096
Recv:  +43.03177 +21.46401 +0.00000
Recv:  +1.02556 +11.77631 +22.52580
Recv: 
Recv: 
Recv: 
Recv: Bed Level Correction Matrix:
Recv: +0.997433 +0.000000 +0.071607
Recv: -0.042704 +0.802710 +0.594839
Recv: -0.057479 -0.596370 +0.800649
Recv: ok

An M48 repeatability test also shows Z increasing with each probe

Send: M48 V3
Recv: M48 Z-Probe Repeatability test
[...]
Recv: Positioning the probe...
Recv: 1 of 10   z: 32.311748 mean: 32.311748   sigma: 0.000000
Recv: 2 of 10   z: 34.310749 mean: 33.311248   sigma: 0.999500
Recv: 3 of 10   z: 35.400501 mean: 34.007663   sigma: 1.279060
Recv: 4 of 10   z: 37.399501 mean: 34.855625   sigma: 1.839592
Recv: 5 of 10   z: 38.488498 mean: 35.582199   sigma: 2.195204
Recv: 6 of 10   z: 40.487499 mean: 36.399749   sigma: 2.712510
Recv: 7 of 10   z: 41.692001 mean: 37.155788   sigma: 3.120280
Recv: 8 of 10   z: 43.691001 mean: 37.972690   sigma: 3.631864
Recv: 9 of 10   z: 44.824501 mean: 38.734001   sigma: 4.044948
Recv: 10 of 10   z: 46.823501 mean: 39.542949   sigma: 4.540380
Recv: Mean: 39.542949
Recv: Standard Deviation: 4.540380

Here is my Configuration
https://gist.github.com/c2c2caa530cdb05e9cf9.git

I should also point out that I cannot get bed levelling to work in 1.0.2 either. I do not know what is so unique about my configuration?

Thanks for any advice.

**Comment by AnHardt** [comment]
Error: 404 for your configuration

Please test your z-min-endstop/probe with M119. It looks as if that is permanently triggered.

**Comment by delboy711** [comment]
I found the problem.  It was HOMING_FEEDRATE  After reducing it to 3*60 auto bed levelling works OK.

I was surprised it turned out to be that since homing was working OK with auto bed levelling disabled.
Thanks for taking the time to look at my problem.
