### ISSUE TITLE
[FR] `_calculated_remaining_time()` could use an update

### ISSUE THREAD

**Issue by classicrocker883** [MarlinFirmware/Marlin#26856]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I've been trying to figure out how to make this function work a bit better, been thinking of adding another variable or two to the mix. so far its basic... take the elapsed time times the progress %:
```y
  static uint32_t _calculated_remaining_time() {
    const duration_t elapsed = print_job_timer.duration();
    const progress_t progress = _get_progress();
    return progress ? elapsed.value * (100 * (PROGRESS_SCALE) - progress) / progress : 0;
  }
```

I think we can do better: 
- add `feedrate_percentage`
- pause the estimated remaining time when progress is stopped (during heating)
- - this would mean to subtract a second counter, counting the time there's no progress

open to any other ideas.

### Expected behavior

A better, more accurate estimated time remaining

### Actual behavior

Basic estimated time remaining. (not very accurate)

### Version of Marlin Firmware

most recent

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
If you’re going to create a Feature Request, please use the [“Request a feature” option](https://github.com/MarlinFirmware/Marlin/issues/new/choose) so the proper template is used and auto-tagging works correctly.
