### ISSUE TITLE
[BUG] G34 not compensating

### ISSUE THREAD

**Issue by demetan71** [MarlinFirmware/Marlin#26852]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When I was using endstop switch for homing Z auto align work, but now I'm homing Z with probe, G34 do it's move but do not compensate adjust...

### Bug Timeline

Since I' homing Z with probe

### Version of Marlin Firmware

2.1.x

### Printer model

Anycubic Chiron

### Electronics

SKR 1.4 Turbo 

### LCD/Controller

TFT35 E3 V3

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I'm desesperate, could'nt auto align Z so my bed leveling not good or I couldn't verify it.....

Try almost everything I made a video to show what it does

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/14530278/Configuration_adv.zip)

https://www.youtube.com/watch?v=c4JiuWvfRgY

**Comment by thisiskeithb** [comment]
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information:

- Download Marlin [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as [Pronterface](https://github.com/kliment/Printrun/releases/latest), [Repetier Host](https://www.repetier.com/download-now/), or [OctoPrint](https://octoprint.org/download/).
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed. This will also enable bed leveling.
- Do a `G34` to start the Z Steppers Auto-Alignment procedure.
- Do some of the moves that revealed problems before. Take notes.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.

**Comment by demetan71** [comment]
[thisiskeithb](https://github.com/thisiskeithb)

Ok, but Z auto align Will give me a report???   Because bed leveling seem's to work ok, but so much difference between to end of the axis, so it's hard to validate that bed leveling is ok....

**Comment by thisiskeithb** [comment]
> Ok, but Z auto align Will give me a report??? Because bed leveling seem's to work ok, but so much difference between to end of the axis, so it's hard to validate that bed leveling is ok....

I've updated my comment. Add `G34` after `G29` so it can be logged.

**Comment by demetan71** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/14531916/Configuration.zip)
[g34.txt](https://github.com/MarlinFirmware/Marlin/files/14531788/g34.txt)
[thisiskeithb](https://github.com/thisiskeithb)

Ok I downloaded the last bugfix version
Is it normal that when I send G29 by pronterface it does nothing? I have to do G29 P1

Did all what you said, but I want to copy the report, I scroll up, and I can't find the beginnng, I just have report in the middle of G34???

What I did wrong??

**Comment by demetan71** [comment]
https://github.com/thisiskeithb

Finally I switch the wire motor on the board, and I can acheive accuracy of 0.01 with 30 itteration!!

So now it's working, but how why it take 30 itterations to do it??   Starting from .322 to 0.01

I was too fast to celebrate, try to did it again and result is inconstant....
[G34_inconstant.txt](https://github.com/MarlinFirmware/Marlin/files/14540334/G34_inconstant.txt)

**Comment by thisiskeithb** [comment]
> Finally I switch the wire motor on the board

Looks like there is a hidden define in the Chrion pins file that fixes Z motor plugs without having to physically swap Z motors, but it's good to fix the hardware like you've done.

https://github.com/MarlinFirmware/Marlin/blob/4f2b7271bddc1d691af34ceeb033d4ba424c99ec/Marlin/src/pins/ramps/pins_TRIGORILLA_14.h#L148

> So now it's working, but how why it take 30 itterations to do it?? Starting from .322 to 0.01

`G34` should stop after the value you have in your config (`#define Z_STEPPER_ALIGN_ITERATIONS 10`), not `30`.

> I was too fast to celebrate, try to did it again and result is inconstant....

A value of `0.01` for `Z_STEPPER_ALIGN_ACC` may not be easily achievable for a number of reasons, particularly for hardware that isn't super rigid / has play in it. This can be especially true for a machine as large as the Chiron.

[The stock Chiron config we maintain](https://github.com/MarlinFirmware/Configurations/blob/5c1f3d822057d3a8ec685f1753bee450c6c371ee/config/examples/AnyCubic/Chiron/Configuration_adv.h#L1074-L1078) has the following `Z_STEPPER_AUTO_ALIGN` settings:

```c
  #define G34_MAX_GRADE              5    // (%) Maximum incline that G34 will handle
  #define Z_STEPPER_ALIGN_ITERATIONS 5    // Number of iterations to apply during alignment
  #define Z_STEPPER_ALIGN_ACC        0.02 // Stop iterating early if the accuracy is better than this
  #define RESTORE_LEVELING_AFTER_G34      // Restore leveling after G34 is done?
```

I have been using `G34`/`Z_STEPPER_AUTO_ALIGN` on several machines this week and cannot reproduce these issues, so you should spend some time dialing in the settings mentioned above.

The [AnyCubic Chiron Facebook group](https://www.facebook.com/groups/2168219426798485) may be a good place to find which settings fellow Chiron users run or you can check out the following resources for additional help:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Comment by demetan71** [comment]
https://github.com/thisiskeithb

I'm feeling a little shy, shame on me, the problem was that my second Z stepper was connected on Z2 instead of E1 so now it's working.  I was able to achieve perfect accuracy 0.00, but it's not perfect somethime I have to do it a couple of time, because sometime it compensate in the wrong direction an I've got the message Accuracy decreasing....

But that doesn't resoleve my main issue it to print on a perfect leveling bed

Since I put the last bug fix firmware I've got message Probing fail, when I put Bi-Linear it simply said unable to enable bed leveling, so I switch to Linear and I have probing fail...  I have report but unble to interpret it...

And I just realized that M48 repeatability test fail too, before I put new firmware It was really great...

[probe-fail.txt](https://github.com/MarlinFirmware/Marlin/files/14547860/probe-fail.txt)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/14547864/Configuration_adv.zip)
