### ISSUE TITLE
[BUG] Enabling FT_MOTION with any shaper causes grinding, ignores endstops.

### ISSUE THREAD

**Issue by bmourit** [MarlinFirmware/Marlin#26858]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Creality board 4.2.2 with A4988 drivers enabling FT_MOTION will cause movements to attempt moving beyond the endstops and motor grinding will occure.  Hardware endstops endabled, but ignored. Doesn't seem to matter which shaper is used, problem persists.

### Expected behavior

No grinding

### Actual behavior

Grinding/movement beyond endstops

### Version of Marlin Firmware

Latest Bugfix branch

### Printer model

Ender-3 V4.2.2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/14549810/Archive.zip)

**Comment by narno2202** [comment]
Your config files are not from bugfix but  a mix from PR #26848 and from other branch.  What is your Marlin version?
Please report here only bugs from bugfix  or for Marlin stable.

**Comment by bmourit** [comment]
It is from bugfix. I just changed the version manually due to some quirks i get with flashing identical versions . And yes, I was testing the pull to see if it helped. But the bug remains even in the pure bugfix version and I haven't been able to narrow it down. The changes in the Configs is near identical though, but if you like I can provide them again. The original used all defaults for FT_MOTION section.

The build does work fine if I use the LCD menu to disable FT_MOTION and restart. There is no other branch here beyond your pull request. Only changed values.

I'm about to run another debug build and see what I can find. The simplest explanation (to me) would be that the triggers are being inverted, since that would explain it happening on all axis. For the life of me I cannot see anywhere that would be happening.

**Comment by narno2202** [comment]
@bmourit , please post your config files for bugfix. It's look like a buffer issue ( buffers too large).

**Comment by bmourit** [comment]
> @bmourit , please post your config files for bugfix. It's look like a buffer issue ( buffers too large).

I believe you are correct! Feel free to close this. I'll open a new bug if I find it again, but this seems to have been the issue. Thanks so much!
