### ISSUE TITLE
[Error build STM32F103RC_creality (Ender 3)] (configuration.h:3223:15: error: missing binary operator before token "(")

### ISSUE THREAD

**Issue by Nightwalker813** [MarlinFirmware/Marlin#26867]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I tried to comlpile build Marlin for Ender 3 STM32F103RC_creality (256K) but AutoBuild back error 
f:\ender 3\fw\marlin-2.1.x\marlin\configuration.h:3223:15: error: missing binary operator before token "("
 3223 | #if DGUS_UI_IS(MKS)
      |               ^
 3225 | #elif DGUS_UI_IS(IA_CREALITY)
      |                 ^
Error: Failed to parse Marlin features. See previous error messages.

At first try I used copypast strings from file. 
At second try I listed file configuration.h and configuration_adv.h manually and edit nessesary strings manually. But error sill stay.
I don't understand, where is error. I searched 200 strings higher and lower. There is no errors with missing "(". 
![Безымянный](https://github.com/MarlinFirmware/Marlin/assets/162621284/1c596762-d32b-4dfe-a602-51170b04ba8a)

### Bug Timeline

in 2.1.2.1 there is no same issue.

### Steps to Reproduce

1. use "Marlin 2.1.2.2 with bug fixes"
2. use "Marlin "Nightly" Source"" configs
3. build new fw for Ender 3 v.4.2.2 board

configs [config.zip](https://github.com/MarlinFirmware/Marlin/files/14590815/config.zip)

### Version of Marlin Firmware

2.1.2.2

### Printer model

Ender 3

### Electronics

stock (GD32F303 - chip) (previously build is ok)

### LCD/Controller

CR10_STOCKDISPLAY HD44780

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
> use "Marlin 2.1.2.2 with bug fixes"
> use "Marlin "Nightly" Source"" configs

You cannot mix & match versions of Marlin. Since you are using Marlin `2.1.2.2`, you must use `2.1.2.2` configs: https://github.com/MarlinFirmware/Configurations/tree/release-2.1.2.2

Having said that, I would recommend sticking with `2.1.2.1` or moving completely to `bugfix-2.1.x` since `2.1.2.2` has several bugs in it.
