### ISSUE TITLE
[FR] Update FT_MOTION code to include Ulendo.io improvements

### ISSUE THREAD

**Issue by Sophist-UK** [MarlinFirmware/Marlin#26880]
### Is your feature request related to a problem? Please describe.

There are several open issues relating to FT_MOTION: #26642, #26683.

In parallel, the original author has made some improvements to their Marlin fork which may or may not address these issues.

### Are you looking for hardware support?

No

### Describe the feature you want

FT_MOTION was first implemented in Feb 2023 in #25394 based on code at that date in https://github.com/S2AUlendo/MarlinCollaborative/commits/fixed_time_motion_control/ . 
As you can see there have been (and continue to be) improvements made to this code. 

It seems to me that these improvements should be reviewed and as appropriate imported
into the Marlin code.

**Comment by thisiskeithb** [comment]
There are ongoing improvements and bug fixes already. Just search the PR queue for [FT MOTION](https://github.com/MarlinFirmware/Marlin/pulls?q=is%3Apr+is%3Aopen+FT+MOTION) / [FT_MOTION](https://github.com/MarlinFirmware/Marlin/pulls?q=is%3Apr+is%3Aopen+FT_MOTION).
