### ISSUE TITLE
[FR] How to get the execution time(ETA) of gcode between any two points?

### ISSUE THREAD

**Issue by 12343954** [MarlinFirmware/Marlin#26886]
I want to use it as a delta robot to pick up objects on conveyor belt.
PID algorithm is not fast enough.
so I use the interception algorithm, but first know the time required to move from the current point to any target point.

first question：
Is there an API or algorithm to calculate the ETA time for G0/G1？

second：
Is there an API or gcode in marlin support this spatial movement?
[https://github.com/msteinbeck/tinyspline/issues/236](https://github.com/msteinbeck/tinyspline/issues/236)
![image](https://github.com/MarlinFirmware/Marlin/assets/1804003/3abbadc1-6d48-466c-bae4-06f1ed617b18)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
