### ISSUE TITLE
Z Axis moves by manual but wont home

### ISSUE THREAD

**Issue by DomoVlas** [MarlinFirmware/Marlin#26919]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After flashing with new Marlin 2.1.2.1., Z AXIS will move by move command but when I try Homing it wont go down.

I have SKR 2 with dual Z motor and dual endstops.

### Expected behavior

Expected to Home Z.

### Actual behavior

Raise for Homing X and Y but stays still for Z home.

### Version of Marlin Firmware

2.1.2.1

### Printer model

Anzcubic Mega X

### Electronics

SKR 2 

### LCD/Controller

Full Graphic reprap discount controller

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Tested on every 2.1.2.1 Marlin Build even on 2.1.2.2
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/14799003/Marlin.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
