### ISSUE TITLE
bed temperature runaway, auto leveling.

### ISSUE THREAD

**Issue by pbrgle1** [MarlinFirmware/Marlin#2692]
Since i upgraded to auto bed leveling i keep getting thermal runaway errors for my heat bed. The temperature readings freeze and after the THERMAL_PROTECTION_BED_PERIOD the printer disconnects. This issue happens only when i want to print. If i leave the bed set to 100C while not printing there is no problem.

**Comment by AnHardt** [comment]
Could your fan blow the bed cold?

Tune

```
#if ENABLED(THERMAL_PROTECTION_BED)
  #define THERMAL_PROTECTION_BED_PERIOD 20    // Seconds
  #define THERMAL_PROTECTION_BED_HYSTERESIS 2 // Degrees Celsius
#endif
```

in Configuration_adv.h

**Comment by pbrgle1** [comment]
no there are no fans blowing on the bed. Before i enabled auto bed leveling and servos everything worked fine. No other changes were made

**Comment by AnHardt** [comment]
Anyway the lines above are the key. Tune or switch off.

Possible sources are:
loose connection/ broken cable at heater or thermistor
noise on the sensor lines.

Please observe what happens with the temperature directly before the error. (graph at the host program)

**Comment by pbrgle1** [comment]
http://postimg.org/image/bsagnv2wd/ (GRAPH)

the sensor connection is fine. the reading freezes when i start printing. overload because of bed leveling (G29) maybe?

**Comment by AnHardt** [comment]
It's difficult to judge in that scale, but as far i can see Marlin is doing what it's expected to do.
The beds temperature is dropping more than 2°C for longer then 20 seconds. Then for safety reasons your printer is shut down.
You can make this knife blunt by increasing the temperature difference and or increasing the time.

**Comment by pbrgle1** [comment]
Yes i see what you are saying but why does this not happen when im preheating the bed? I also set it to 40s.

**Comment by AnHardt** [comment]
The difference between preheating and printing is moving. 
A broken wire?
Cooling by moving?

**Comment by ghuser2** [comment]
When preheating, the thermal runaway protection is not activated yet, until the temp stabilized.

**Comment by AnHardt** [comment]
@ghuser2 
Good finding.

If the temperature is still to unstable playing with

```
// Actual temperature must be close to target for this long before M109 returns success
#define TEMP_RESIDENCY_TIME 10  // (seconds)
#define TEMP_HYSTERESIS 3       // (degC) range of +/- temperatures considered "close" to the target one
#define TEMP_WINDOW     1       // (degC) Window around target to start the residency timer x degC early.
```

and or tuning the PID values can improve the situation.

EDITED:

Increasing THERMAL_PROTECTION_BED_HYSTERESIS will also provide a higher tolerance for the initial overshoot.

But this does not explain a different behavior  between (preheating and holding the temperature) versus (preheating and printing); - the difference is movement.

**Comment by pbrgle1** [comment]
In my case the bed is not moving douring printing (Only in Z axis). I had to disable the protection for my bed because no setting worked.

And abut preheating. Even when the temps stabilised and stayed there for some time, i had no problems with thermal runaway. Only when starting a print.

Now that i disabled protection it works fine and temps are normal.
