### ISSUE TITLE
Max min pos ayarlaması m komutlarıyla

### ISSUE THREAD

**Issue by hsyngndz85** [MarlinFirmware/Marlin#26937]
### Is your feature request related to a problem? Please describe.

Max pos ayarlarının m komutlarıyla dişardan ayarlanması gerekiyor. Max min pos ların saklandığı hafısa neresidir nasıl yapabilrim
[Translated to English] Max pos settings need to be adjusted externally with m commands. Where is the memory where the maximum and min POS numbers are stored? How can I do it?

### Describe the feature you want

M komutuyla max  min pos yaralanması 
[Translated to English] max min pos setable with M command

**Comment by ellensp** [comment]
MAX_POS are defines, the values are hard coded into the firmware as it is being compiled. They are not in memory.

There is already a open feature request for this https://github.com/MarlinFirmware/Marlin/issues/25582
