### ISSUE TITLE
[BUG] Unable to start compilation of Lpc176x series

### ISSUE THREAD

**Issue by Maoweicao** [MarlinFirmware/Marlin#26942]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Unable to start compilation of Lpc176x series, log report could not find the ID of the board
`
(base) PS L:\Downloads\Marlin-bugfix-2.1.x (1)\Marlin-bugfix-2.1.x> platformio run -e LPC1768
Processing LPC1768 (board: nxp_lpc1768; platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.3.zip; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
UnknownBoard: Unknown board ID 'nxp_lpc1768'
(base) PS L:\Downloads\Marlin-bugfix-2.1.x (1)\Marlin-bugfix-2.1.x> echo "done" >"C:\Users\MAOWEI~1\AppData\Local\Temp\ipc"
(base) PS L:\Downloads\Marlin-bugfix-2.1.x (1)\Marlin-bugfix-2.1.x> 
`
![image](https://github.com/MarlinFirmware/Marlin/assets/26041764/195212d2-aa67-4efa-9298-f43e1e7d8a2c)
However, if I try to modify the version of platform in the lpc167x.ini file, falling back to 0.1.2 seems to be normal again.
![image](https://github.com/MarlinFirmware/Marlin/assets/26041764/d4377569-460a-41fe-a659-a25fba425be9)

### Bug Timeline

new bug

### Expected behavior

Expect it to compile normally

### Actual behavior

1. Modify the configuration.h #define MOTHERBOARD
for BOARD_BTT_SKR_V1_3
2. Start the compilation

### Steps to Reproduce

1. Modify the configuration.h #define MOTHERBOARD
for BOARD_BTT_SKR_V1_3
2. Start the compilation

### Version of Marlin Firmware

bugfix2.1.x（Marlin 2.1.2.2)

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/14896312/Marlin.zip)

**Comment by ellensp** [comment]
Something wrong with your machine. 0.1.3 works fine for me. 

Delete your .platformio folder under your user name and restart vscode, give it time to reinstall everything
