### ISSUE TITLE
[BUG] MSG_ATTACH_SD_MEDIA not defined in 2.1.2.2

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Marlin#26940]
### Bug Description

 MSG_ATTACH_SD_MEDIA is used by 2.1.2.2 but not defined in the code 

Marlin\src\lcd\menu\menu_main.cpp:424:25: error: 'MSG_ATTACH_SD_MEDIA' is not a member of 'Language_en'; did you mean 'MSG_ATTACH_USB_MEDIA'?

Needs this line added to Marlin/src/lcd/language/language_en.h
`  LSTR MSG_ATTACH_SD_MEDIA                = _UxGT("Attach SD Card");
`

### Bug Timeline

Since 2.1.2.2 was released

### Expected behavior

It should build

### Actual behavior

Marlin\src\lcd\menu\menu_main.cpp:424:25: error: 'MSG_ATTACH_SD_MEDIA' is not a member of 'Language_en'; did you mean 'MSG_ATTACH_USB_MEDIA'?

### Version of Marlin Firmware

2.1.2.2

**Comment by ellensp** [comment]
just added for the record

**Comment by thisiskeithb** [comment]
Patch for `2.1.x` submitted:
- https://github.com/MarlinFirmware/Marlin/pull/27020
