### ISSUE TITLE
1.1.RC1 LCD flow rate adjustment causes zero extrusion

### ISSUE THREAD

**Issue by o-lampe** [MarlinFirmware/Marlin#2697]
I see we have a RC2 version already, but I checked the issue list and this one wasn't mentioned yet.

When I adjust extruder flow rate ( reduce to 92% ) the extrusion stops completely. Only retraction moves are done.
After a few seconds ( when the printbuffer is refreshed ?) the extrusion starts working as expected..

My config: Delta/Ramps/RRD-LCD2004

**Comment by AnHardt** [comment]
@o-lampe 
How many extruders do you have defined? Only one or more?

**Comment by o-lampe** [comment]
@AnHardt 
Only one extruder.

**Comment by tonnico** [comment]
A friend has the same issue. Setup is Rumba/Viki2/dual Extruder.

Ok. Just read his mail again. Not complete the same. When he turns the button left the flow jumps to 0. Right jumps back to 100. He can't also use any other command, only adjusting flowrate.

**Comment by thinkyhead** [comment]
Anyone still seeing this with the latest RC? If not, we can close it and assume it's not an issue any longer.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.

**Comment by toby4548** [comment]
Hello,
I'm using v1.1 RC7 now and have the same problem.
Any flowrate under 100% will cause the extruder stop.

 My config is: Kossel mini/Ramps 1.4/RRD-LCD2004

**Comment by jbrazio** [comment]
@toby4548 I'd suggest to open a new ticket.
