### ISSUE TITLE
M206 on XYZ machine not working (1.0.x)

### ISSUE THREAD

**Issue by RogerRepRap** [MarlinFirmware/Marlin#2698]
No  matter the M206 Z setting home (G28) just gets you back to hardware limit switch setting.

Turned off soft limits in config.h
Set mechanical end switch to 10mm above bed
Did z home to verify end switch setting. Looked good.
Test cycle:
1. Did a M206 ZX where x value varied from +5 to -2
2. Did a M500
3. Did a M501 to verify M206 was applied.
4. Disconnect and reconnect repitier.
5. Home using Z button on repiteir (g28 z0) or manually entering g28 z
6. Measure observe results.
7. Repeat

Environment:
Solidoodle with Ramps 1.4, Marlin 1.0.x

No  matter the X setting home (G28) just gets you back to hardware limit switch setting. Congratulations, homing now works the way it should in touching, backing off and retouching the switch. Everything else is great!

Roger

**Comment by thinkyhead** [comment]
This issue is fixed in 1.1.0-RC3 and some earlier versions.
