### ISSUE TITLE
Not sure if code is working with RAMPS 1.4 Shield + LCD

### ISSUE THREAD

**Issue by YoNoTacos4U** [MarlinFirmware/Marlin#26999]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I've just recently got a replica arduino mega, with a ramps 1.4 shield, a power supply and a LCD (RepRap 12864). I plugged everything in, and the LCD is just blue. I've already tried uploading the code multiple ways, same thing. I've also seen it is common for just switching the wires on the LCD, and I've tried that and still nothing. Not sure if anyone could help?

### Bug Timeline

Always like this since first time turning on

### Expected behavior

Marlin boot screen to show on LCD

### Actual behavior

Blue blank screen

### Steps to Reproduce

Plug everything in and turn it on

### Version of Marlin Firmware

2.1.2.2

### Printer model

N/A

### Electronics

 Arduino+RAMPs: RAMPS 1.4, 3D Printer RAMPS 1.4 Controller + R3 + A4988 with Heat Sink USB Calbe Jumper Kit

### LCD/Controller

LCD:HiLetgo 3D Printer Reprap Smart Controller 12864 LCD Display with Smart Controller Board for 3D Printer RAMPS 1.4 Reprap Mendel Prusa for Arduino 128x64 LCD Blue Color

### Other add-ons

N/A

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by PanosPetrou** [comment]
Keep in mind some people report quality issues with the particular display. Did you attach a zip file containing your Configuration.h & Configuration_adv.h files? I don't see it.

**Comment by ellensp** [comment]
2.1.2.2 is buggy and should be avoided. will reboot constantly with input shaping enabled

**Comment by ellensp** [comment]
no configs. no way to check anything or help you. closing. 

A BOARD_RAMPS_14_EFB with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER works without issues

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
