### ISSUE TITLE
[BUG] Freeze_feature does not stop all motors

### ISSUE THREAD

**Issue by karabas2011** [MarlinFirmware/Marlin#27010]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Freeze feature stops print head motion but not extruder motor

### Bug Timeline

I never use this feature before

### Expected behavior

I expect stop all motors.

### Actual behavior

When printing from SDCARD  only X/Y motors stopped
When idle, If  I start extruding via menu  - it stopped!
So there is limit of how many motors can be stopped.

### Steps to Reproduce

Start prining from SDCARD
Press freeze button

### Version of Marlin Firmware

marlin 2.1.2.1

### Printer model

sparky

### Electronics

 SKR1.3

### LCD/Controller

MKS12864

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
Please test the [`bugfix-2.1.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate 
further.

Please attach your configuration files.

**Comment by ellensp** [comment]
"When printing from SDCARD only X/Y motors stopped" this disagrees with your next line
"When idle, If I start extruding via menu - it stopped!" yes you stopped it.
So there is limit of how many motors can be stopped."  It stops the interrupt that generates the stop pules, nothing should move.

In Marlin/src/module/stepper.cpp
```
  // Skipping step processing causes motion to freeze
  if (TERN0(FREEZE_FEATURE, frozen)) return;  

```

**Comment by karabas2011** [comment]
https://github.com/MarlinFirmware/Marlin/assets/530024/3497af30-ec88-4832-80a7-cce260a2ab78

**Comment by ellensp** [comment]
The original video didn't play, I download and converted it and replaced it so can be played here.
 Summary, the extruder gear for E can been seen to keep rotating while X and Y freeze  

Please attach your configuration files.

Please test the [`bugfix-2.1.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by karabas2011** [comment]
Sorry for late. last release 2.1.2.4 seems to work correctly.
