### ISSUE TITLE
Can get my Lcd to work 

### ISSUE THREAD

**Issue by exsaevio** [MarlinFirmware/Marlin#2702]
Sorry if this is not that place to make this requast. But i have an Wanhao I3 printer and i cant get the lcd to work. There is a Repetier on the machine stock. But i would like to have marlin. I have the original Repetier on file. Is there any way of figure out what setting there is? i have triede to wrap my head around it but no luck. There maust be some pin setting?
Best regards

**Comment by KiteLab** [comment]
Ask Wanhao for the original source code and the used configuration file. The configuration file is not that difficult to read.

At the picture on their website it looks like one of the graphic displays. If you have already the right MOTHERBOARD for your printer you could try to test REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER or one of the other displays/panels using u8glib.

**Comment by exsaevio** [comment]
Hello Again and thanks for answer. I have management to get The original source file . Been sitting a week trying to figurer out how to read The original file so i can takeit to marlin. And i have tried REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER but no  luck. And i tried customer service but no answer There. I wish it was East :(

**Comment by exsaevio** [comment]
Meant easy

**Comment by exsaevio** [comment]
And i have tried all of The display!

**Comment by NarimaanV** [comment]
I searched "Wanhao I3 LCD" and the second result I got was a link to a site selling replacement parts for Wanhao printers, include the screen for the Duplicator I3:
http://www.3dprima.com/en/accessories/spare-parts/wanhao-i3/wanhao-duplicator-i3-lcd-display.html
The PCB of the screen in the picture on that site says "LCD for Melzi V4", which makes sense because it seems the Wanhao I3 runs off of a Melzi board. From a little more research, there doesn't seem to be an "official Melzi display", but both the Panelolu 2 and the RA Control Panel are theoretically compatible with the Melzi. Just to confirm, you've tried both those two for your display and it hasn't worked?

**Comment by exsaevio** [comment]
Hello i can´t go heads or tails with this!  I tried Again´with Panelou 2 When u wanted confirmation and noo luck 
And i cant see what setting in repitier that do this! And as u did! I research and got the same results as u So what so special with this panel? They made somthing strange. Dont want to give up but maby i have to?

**Comment by NarimaanV** [comment]
Can you post the config file(s) and post a link here? It might help to have a few other pairs of eyes look through to see if anyone can identify what display is being used.

**Comment by exsaevio** [comment]
Ofcourse thought you never Ask :-)
https://dl.dropboxusercontent.com/u/12600947/NoBeep.zip

**Comment by KiteLab** [comment]
Your configs
#define FEATURE_CONTROLLER 11
translates to
11 or CONTROLLER_REPRAPDISCOUNT_GLCD = RepRapDiscount Full Graphic Smart Controller
in Marlin
REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by KiteLab** [comment]
Your configurations
#define MOTHERBOARD 63
translates to MELZI
translates to Marlin
#define BOARD_MELZI             63   // Melzi
maybe

#define BOARD_MELZI_MAKR3D      66   // Melzi with ATmega1284 (MaKr3d version)
what used to be 
BOARD_MELZI_1284

**Comment by KiteLab** [comment]
Start reading at #1386

**Comment by exsaevio** [comment]
Hmm yes all that i figured  with the Melzy
and i tried REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER to but no luck and i tried Makr3d with the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER. 
Seem like a lost cause! And i mad that the company wont answer my mails
im going to look at the #1386 see if that do something

**Comment by AnHardt** [comment]
Any progress here?
