### ISSUE TITLE
[Request] ZeroPI support

### ISSUE THREAD

**Issue by Grogyan** [MarlinFirmware/Marlin#2703]
I'm sure you guys are aware that there is a new board coming out soon called the ZeroPI
https://www.kickstarter.com/projects/1204283/zeropi-arduino-and-raspberry-pi-compatible-develop/description

Will Marlin be able to support this?

**Comment by KiteLab** [comment]
Unlikely. There is no AVR in.

**Comment by Grogyan** [comment]
That's right.
It has an Atmel ARM
This has been discussed about the future potential of Marlin beyond 8 and 16 bit MCU's

**Comment by Grogyan** [comment]
I'm getting one, and will see how it goes.

**Comment by paulusjacobus** [comment]
They say on the kick starter page that they have successfully ported Marlin.

**Comment by Grogyan** [comment]
It's a really old port. and no mention of using it with OctoPrint
And i'd have to jig it to support thermocouples.  Should be relatively straight forward to do that

**Comment by KiteLab** [comment]
If a bit older it's likely a fork of 
https://github.com/bobc/Marlin
if not that old likely a fork of 
https://github.com/Wurstnase/Marlin4Due

#626
