### ISSUE TITLE
vibrating x stepper motor while safe homing

### ISSUE THREAD

**Issue by meloue** [MarlinFirmware/Marlin#27041]
### Is your feature request related to a problem? Please describe.

when x stepper goes to 0:0 every thing is ok but when it goes to mid point of bed it sarts to vibrating a lot 

### Describe the feature you want

i use ramps1.4 and my hardware is completely ok and in past there wasn't this problem i changed the firmware to an old one and it solved but when i change firmware to 2.1.2.2 my problem backs thank you

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
