### ISSUE TITLE
[BUG]2.1.2.2 Unable to Compile

### ISSUE THREAD

**Issue by Docomar750** [MarlinFirmware/Marlin#27057]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Build failing for SKR 1.4 Turbo build

### Bug Timeline

1 week ago

### Expected behavior

to be able to compile and build

### Actual behavior

failks to build every time

### Version of Marlin Firmware

2.2.1.2

### Printer model

Ender 3

### Electronics

BTT SKR 1.4 Turbo

### LCD/Controller

BTT

### Other add-ons

Nil

### Bed Leveling

ABL Linear grid

### Your Slicer

Other (explain below)

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

PS D:\3D printer Software\ENDER 3 Modified\Marlin-2.1.2.2 Ender 3 SKR 1 4> platformio run --silent -e LPC1769
In file included from Marlin\src\HAL\LPC1768\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\LPC1768\HAL.cpp:24:
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\LPC1768\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\LPC1768\HAL_SPI.cpp:51:
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\LPC1768\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\LPC1768\MarlinSerial.cpp:26:
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\LPC1768\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\LPC1768\MinSerial.cpp:24:
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\LPC1768\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\LPC1768\eeprom_flash.cpp:39:
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\LPC1768\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\LPC1768\eeprom_sdcard.cpp:29:
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\LPC1768\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\LPC1768\eeprom_wired.cpp:24:
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\LPC1768\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\LPC1768\timers.cpp:31:
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\LPC1768\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\LPC1768\fast_pwm.cpp:24:
Marlin\src\HAL\LPC1768\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\shared\Delay.cpp:25:
Marlin\src\HAL\shared\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\shared\HAL.cpp:27:
Marlin\src\HAL\shared\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\shared\../../core/../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\shared\../../core/serial.h:24,
                 from Marlin\src\HAL\shared\MinSerial.h:24,
                 from Marlin\src\HAL\shared\MinSerial.cpp:22:
Marlin\src\HAL\shared\../../core/../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\shared\backtrace\../../../core/../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\shared\backtrace\../../../core/serial.h:24,
                 from Marlin\src\HAL\shared\backtrace\../MinSerial.h:24,
                 from Marlin\src\HAL\shared\backtrace\backtrace.cpp:28:
Marlin\src\HAL\shared\backtrace\../../../core/../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\shared\backtrace\../../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\shared\backtrace\unwmemaccess.cpp:18:
Marlin\src\HAL\shared\backtrace\../../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\shared\esp_wifi.cpp:23:
Marlin\src\HAL\shared\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:52,
                 from Marlin\src\HAL\shared\servo.cpp:53:
Marlin\src\HAL\shared\../../inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
*** [.pio\build\LPC1769\src\src\HAL\LPC1768\MarlinSerial.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\LPC1768\HAL_SPI.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\LPC1768\HAL.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\LPC1768\MinSerial.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\LPC1768\eeprom_flash.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\LPC1768\eeprom_sdcard.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\LPC1768\eeprom_wired.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\LPC1768\timers.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\LPC1768\fast_pwm.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\shared\MinSerial.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\shared\Delay.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\shared\HAL.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\shared\backtrace\backtrace.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\shared\esp_wifi.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\shared\backtrace\unwmemaccess.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\shared\servo.cpp.o] Error 1
In file included from Marlin\src\inc/MarlinConfig.h:52,
                 from Marlin\src\MarlinCore.h:24,
Marlin\src\inc/SanityCheck.h:1658:4: error: #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
 1658 |   #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."
      |    ^~~~~
*** [.pio\build\LPC1769\src\src\MarlinCore.cpp.o] Error 1
================================================================================================================================ [FAILED] Took 7.09 seconds ================================================================================================================================ 

Environment    Status    Duration
-------------  --------  ------------
LPC1769        FAILED    00:00:07.086

**Comment by ellensp** [comment]
The error is deliberate and clear #error "DISABLE_[XYZIJKUVW] is not compatible with HOME_AFTER_DEACTIVATE or Z_SAFE_HOMING."

you need to disable DISABLE_[XYZIJKUVW] or both  HOME_AFTER_DEACTIVATE and Z_SAFE_HOMING

Since you did not follow instructions and did not attach your Configuration files as requested in the template, I cannot tell you exactly which lines you need to change. 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
