### ISSUE TITLE
[BUG] 2.1.2.2 severely impacts reliability of BLtouch sensor on Mega2560 8-Bit boards

### ISSUE THREAD

**Issue by str-dst** [MarlinFirmware/Marlin#27066]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

For some reason after updating to 2.1.2.2 the accuracy of my BLtouch went completely down the drain to the point where it's not usable anymore.
Zero changes to the hardware and no relevant changes to either configuration.h or configration_adv.h except for those minor things required for the update.

On 2.1.2.1 the repeatability test gives me a standard deviation of around 0.002.
On 2.1.2.2 the same BLtouch sensor fails the test with a deviation of sometimes over 0.2mm.

A bed mesh generated on 2.1.2.1 looks like this:
[![mesh2121](https://i.imgur.com/tqeclnom.png)](https://i.imgur.com/tqeclno.png)

The mesh on the same machine with zero hardware changes on 2.1.2.2 resulted in this monstrosity:
[![mesh2122](https://i.imgur.com/rE1zj7qm.png)](https://i.imgur.com/rE1zj7q.png)

It seems that something in the code changed that causes the firmware to not read the reported values of the BLtouch correctly anymore or making the sensor output overly noisy.

Rolling back to 2.1.2.1 fixed the issue so it's definitely firmware related and not caused by a faulty BLtouch or some other hardware related issue.

### Bug Timeline

started after updating to 2.1.2.2

### Expected behavior

The BLtouch should give reliable measurements

### Actual behavior

Unreliable measurements and high std deviation in the repeatability test

### Version of Marlin Firmware

2.1.2.2

### Printer model

Heavily modded Anycubic i3 Mega-S

### Electronics

Anycubic Trigorilla 14 (Ramps 1.4) Mega2560 based 8-bit board

### LCD/Controller

FYSETC_MINI_12864_2_1

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[bltouch_issue_2122_conf.zip](https://github.com/MarlinFirmware/Marlin/files/15253135/bltouch_issue_2122_conf.zip)

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by noadgskill** [comment]
In version 2.1.2.2, there are occasional issues during bed leveling where it skips probing points or crashes into the bed. These issues were not present in versions 2.1.2.1 and 2.0.9.7. The probe I use is an IR sensor, and there were no problems before the update.

**Comment by thisiskeithb** [comment]
> In version 2.1.2.2, there are occasional issues during bed leveling where it skips probing points or crashes into the bed. These issues were not present in versions 2.1.2.1 and 2.0.9.7. The probe I use is an IR sensor, and there were no problems before the update.

As I mentioned above, please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by noadgskill** [comment]
> > In version 2.1.2.2, there are occasional issues during bed leveling where it skips probing points or crashes into the bed. These issues were not present in versions 2.1.2.1 and 2.0.9.7. The probe I use is an IR sensor, and there were no problems before the update.
> 
> As I mentioned above, please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

Yes, I tested with the latest version today, but the same issue occurs. The control board I am using is the FYSETC E4 V1.0.

**Comment by thisiskeithb** [comment]
Whenever there are homing or leveling issues, we now ask everyone to follow a standard procedure to gather more information:

- Download Marlin [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as [Pronterface](https://github.com/kliment/Printrun/releases/latest), [Repetier Host](https://www.repetier.com/download-now/), or [OctoPrint](https://octoprint.org/download/).
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed. This will also enable bed leveling.
- Do some of the moves that revealed problems before. Take notes.
- Copy the log output into a **.TXT file** and attach it to your next reply.

Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.

**Comment by str-dst** [comment]
I'll do it once I have my current project finished and have time to flash the new firmware on it again.
Unfortunately I only have this one printer and I need it functioning right now 😄 

I already tested the bugfix branch btw, same result.
Highly unrealiable BLtouch measurements and unusable bed mesh.

**Comment by markotime** [comment]
My problem is a failure to probe at the first or a subsequent location after the center-table probe.  Z seems to rise a few mm before descending, and never quite getting to the table surface.  MKS GEN L V1

**Comment by markotime** [comment]
Lots of compile errors around probe type options, "#IF" statements following disabled declarations
