### ISSUE TITLE
[BUG] REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER SD not working

### ISSUE THREAD

**Issue by benner2024** [MarlinFirmware/Marlin#27067]
[Uploading config.zip…]()
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

latest Marlin release, i defined my REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER as LCD and enabled SDSUPPORT too but i can only print from microSD on the motherboard slot (SKR 2.0 REV B) not from the normal SD slot on the lcd.

### Bug Timeline

new

### Expected behavior

expect to print from normal sd in lcd sd slot

### Actual behavior

read content from microSD in motherboard sd slot

### Steps to Reproduce

1. get SKR 2.0 REV B
2. enable REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
3. enable SDSUPPORT

### Version of Marlin Firmware

2.1.2.2

### Printer model

custom

### Electronics

skr 2.0 rev b

### LCD/Controller

REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

### Other add-ons

BTT ESP8266 Wifi board (not working yet)

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
Your configs did not upload, but I would bet that you have either left `SDCARD_CONNECTION` disabled or set to `ONBOARD`. When `SDCARD_CONNECTION` is disabled, it will default to the onboard SD card for the SKR 2:

https://github.com/MarlinFirmware/Marlin/blob/bab1917311877025f2d387bf009fbf75bc8c4f9e/Marlin/src/pins/stm32f4/pins_BTT_SKR_V2_0_common.h#L329-L334

---
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
