### ISSUE TITLE
[BUG] Weird MPCTEMP behavior

### ISSUE THREAD

**Issue by thomas374b** [MarlinFirmware/Marlin#27068]
### Did you test the latest `bugfix-2.1.x` code?

Not yet.

### Bug Description

The heater does not heat when setting nozzle temp via LCD nor via terminal "M104 S80". I get thermal runaway faults. The heater is not switched on at all as I can see on the corresponding LED for the heaters MOSFET (which is not lit).

I can rule out hardware or wiring faults for 2 reasons
  - it works when I compile with PIDTEMP instead of MPCTEMP
  - more weird, it works when I use MPC autotune "M306 T" after reboot/reset
  

### Bug Timeline

2024-05-07

### Expected behavior

If the machine comes out of reset and nozzle temperature is far below 80°C  Commands "M80;  M104 S80"  should switch on the heaters MOSFET i.e. start heating.

### Actual behavior

I need to run MPC Autotune (M306 T) each time after RESET to make the heater work.

Saving parameters after MPC autotuning (M500) doesn't help, the newly determined MPC parameters are already almost the same as the previous ones stored in the EEprom. Although it seems to be neccessary to run "M306 T" once after each reset for some (hidden) initialization to get the heater up and running.
 

### Steps to Reproduce

- compile and flash Marlin 2.0.9.7 with MPCTEMP enabled for mainboard 4021 (MKS Robin E3D v1.1)
- start printer
- type "M104 S80" in serial Terminal

### Version of Marlin Firmware

2.0.9.7

### Printer model

Kossel

### Electronics

MKS Robin E3D v1.1

### LCD/Controller

REPRAP

### Other add-ons

Neopixel LEDs

### Bed Leveling

ABL 3-point

### Your Slicer

Slic3r

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I've used MPCTEMP already successfully with exactly the same setup/configuration/firmware-version for this printer before I exchanged the mainboard. Before I had a original RAMPS board with ATMega2560 and I never experienced such problem.

The bed-heater is not affected. The problem is only with the nozzle heater.

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by thisiskeithb** [comment]
Cannot reproduce on current `bugfix-2.1.x`.

Note: The `2.0.9.x` code is from 2021 with minor updates, so it’s pretty far behind `2.1.x` and especially `bugfix-2.1.x`.
