### ISSUE TITLE
Bugfix 2.1.x Compile Error for BTT SKR 3 STM32H723VG

### ISSUE THREAD

**Issue by Shriker1** [MarlinFirmware/Marlin#27109]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Attempt to test compile whith Default Environment Change to STM32H723VG_btt and Motherboard set to BOARD_BTT_SKR_V3_0
in configuration.h has failed. Same error with yellow text given, possible missing files?
![image_2024-05-19_202234045](https://github.com/MarlinFirmware/Marlin/assets/74992246/2d264e1f-8d5c-4cd4-8dde-6d5d67d5e14b)

### Bug Timeline

Start: ~05/09/2024, Has been persistent since

### Expected behavior

Compilation to start and finish, would eventually edit the config after tests were successful.

### Actual behavior

Compilation errors out immediately, looks like some missing dependencies?

### Steps to Reproduce

1. Download Latest Bugfix (2.1.x)
2. Modify default_envs to STM32H723VG_btt in PlatformIO.ini
3. Modify #define MOTHERBOARD to BOARD_BTT_SKR_V3_0
4. Compile
Result: Error 

### Version of Marlin Firmware

Marlin Bugfix 2.1.x

### Printer model

(Upgrading) Creasee Skywalker

### Electronics

Upgrading with BTT SKR 3

### LCD/Controller

 Upgrading with BTT TFT35 V3.0.1

### Other add-ons

BLTouch, ESP32E

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
You have to also set `SERIAL_PORT` to `-1`, but both SKR V3 & EZ MCU variants compile fine under Windows 10 as well as macOS 12.7.4/Monterey.

We also use this board in our CI tests, so they would have failed.

Try performing the steps under the ["PlatformIO Errors" troubleshooting section](https://marlinfw.org/docs/basics/troubleshooting.html#platformio-errors) to reset & reinstall PIO.
