### ISSUE TITLE
Marlin firmware Wiki account request

### ISSUE THREAD

**Issue by paulusjacobus** [MarlinFirmware/Marlin#2710]
Hi, I would like an account to enhance the Marlin wiki on Marlinfirmware.org

Thanks

**Comment by AnHardt** [comment]
Me to - please.
@scotty1024

**Comment by Roxy-3D** [comment]
@thinkyhead   I think ThinkyHead has the correct credentials to do that.

**Comment by thinkyhead** [comment]
> ThinkyHead has the correct credentials to do that

Sorry, I never had any credentials except my own login. The site formerly hosted at marlinfirmware.org is now defunct. I hope that a redirect to this repository will be put in its place at some point. To contribute to Marlin documentation, use the Github wiki for MarlinFirmware.
