### ISSUE TITLE
[BUG] idex printer configuration

### ISSUE THREAD

**Issue by huzaifatahir122** [MarlinFirmware/Marlin#27114]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

I am making an idex 3d printer and using Marlin 2.0.x firmware. I have compiled the firmware successfully but when I home the axis, the X2 motor doesn't home. In fact, when I press the homing, first the X1 homes successfully and then printer goes straight for the bed homing and not the X2 homing.
The board I am using is MKS monter8 V2. 
I have enabled the all the settings required for an idex printer like;  X2_DRIVER_TYPE, number of extruder, dual X carriage, etc., and also attaching the screenshots below.

![image](https://github.com/MarlinFirmware/Marlin/assets/170394025/5365f185-e2b8-4cd9-8ce4-c11a6111b549)
![image](https://github.com/MarlinFirmware/Marlin/assets/170394025/943f4500-e765-4b21-8e05-ad9c26c8cce9)
![image](https://github.com/MarlinFirmware/Marlin/assets/170394025/a5f5e79a-484a-49f8-83d5-cb9d330955c1)

 

### Expected behavior

When I press "homing", I expect first the X1 motor to home and then the X2 carriage, but X2 carriage doesn't home.

### Actual behavior

X2 carriage does not move

### Version of Marlin Firmware

2.0.x

### Printer model

custom printer

### LCD/Controller

12864

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/15386136/Configuration_adv.zip)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
