### ISSUE TITLE
LCD bug with Marlin Version

### ISSUE THREAD

**Issue by mibeauvais** [MarlinFirmware/Marlin#2711]
Hello,
I use two different version of Delta Marlin for my printer, a version without the autobed leveling and the other with autobed leveling.
The version without autobed leveling work properly.
The version with autobed leveling works correctly, but generates a bug on the display screen.
![img_1536](https://cloud.githubusercontent.com/assets/11616894/10558242/7ee6dec8-74c9-11e5-8688-a6eacc7a2f49.JPG)

I do not understand what is this default.

Version name Marlin4 lcd works withou autobedleveling:
https://www.dropbox.com/s/kj67whqt8i4wqjl/Marlin4.7z?dl=0
Version name Marlin_3 lcd not works with autobedleveling:
https://www.dropbox.com/s/rs02z7ogyc5ni52/Marlin_Version_3.7z?dl=0

Thanks for help me.

**Comment by KiteLab** [comment]
The main difference is, your 3.7 is not from here, but an ancient branch.

**Comment by mibeauvais** [comment]
Yes, but in this old version it's possible to use the "Bed Auto Leveling" for printing DELTA, in the current release it is noted "Bed Auto Leveling is still not compliant with Delta Kinematics".

**Comment by NarimaanV** [comment]
I've had that glitch happen before to me too. Try just clicking your encoder when that happens and see if that fixes the screen (that worked for me).

**Comment by mibeauvais** [comment]
It does not work for me, I clicked in the encoder, the screen turns blue, after is display error.

**Comment by NarimaanV** [comment]
Huh, well, seems to be more of a serious issue than I had :/

**Comment by mibeauvais** [comment]
now,I used the Marlin RC 2

**Comment by Roxy-3D** [comment]
And is it sick with RC-2 ?     Is that a LCD2004 display?   I'm using a LCD2004 with RC-2 and I don't have any gibberish on the screen.   We do have some people here that know a lot about the LCD Panels.   Maybe one of them will jump in and help.

**Comment by mibeauvais** [comment]
Hello Roxy, No it work very well with the RC2, I'm out of default now.
But I can not run the auto bed leveling, when I send G29, I receive "G29 PROBE LEFT POSITION OUT OF RANGE"

**Comment by Roxy-3D** [comment]
What that message means is you are trying to probe a position on the bed that is too close to the edge.  It will force the extruder nozzle to a position where it is not allowed to go.    How this number gets calculated depends on what kind of printer you have.

But for a Delta...  You might want to go into Configuration.h and increase the

#define LEFT_PROBE_BED_POSITION number 

But do that with the understanding that these #defines have to be reasonable:

```
#define MIN_PROBE_X (max(X_MIN_POS, X_MIN_POS + X_PROBE_OFFSET_FROM_EXTRUDER))
#define MAX_PROBE_X (min(X_MAX_POS, X_MAX_POS + X_PROBE_OFFSET_FROM_EXTRUDER))
#define MIN_PROBE_Y (max(Y_MIN_POS, Y_MIN_POS + Y_PROBE_OFFSET_FROM_EXTRUDER))
#define MAX_PROBE_Y (min(Y_MAX_POS, Y_MAX_POS + Y_PROBE_OFFSET_FROM_EXTRUDER)
```

**Comment by mibeauvais** [comment]
Thank you, auto bed leveling works, but I have a lot of vibration motor during auto bed leveling.

**Comment by mibeauvais** [comment]
I lowered a little movement speed, there is more vibration to motor, they are glossy when ascending  from auto bed leveling.

**Comment by Roxy-3D** [comment]
> I lowered a little movement speed, there is more vibration to motor, they are glossy when ascending from auto bed leveling.

When you say "They are glossy" do you mean they move very smoothly?

The Auto Bed Leveling (G29) uses do_blocking_move_to() in the run_z_probe() function.  It does not do the extra work that happens during a print to make the movement smooth.  How much more vibration do the motors have during Auto Bed Leveling?   My guess is what you are seeing is not a  big deal.  Posting a video of the vibration you are seeing would give people an opportunity to see the same thing you are saying.   Is that possible to do?

(And in fact, run_z_probe() reduces the speed of the motors considerably to help it get an accurate probe.   The movement from one probe location to the next doesn't really matter as long as the printer's stepper motors don't lose position.)

**Comment by mibeauvais** [comment]
With printing I don't have see these vibrations, or they were less.
If you see the video:
http://youtu.be/d04ubwlaTng

**Comment by thinkyhead** [comment]
How's it going? Can we close this issue? Be sure to try 1.1.0-RC3 if you can. The updates may or may not impact your vibration situation, but it would be good to know. I believe the reason for the difference in the way movements "feel" is that bed leveling uses raw movement between probes so the timing and coordination between the steppers is different. With raw moves, the stepper speeds stay constant throughout the move, whereas with interpolated moves the stepper speeds constantly change. _Just a theory…_

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
