### ISSUE TITLE
[BUG] CR touch won't deploy for Z homing

### ISSUE THREAD

**Issue by rabirland** [MarlinFirmware/Marlin#27124]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Installed Marlin (latest as of writing this issue) on an Bigtreetech SKR Mini E3 V3 board with a Creality CR Touch (cables re-aligned for the correct pinout). However, during homing, the CR Touch never deploy and the bed simply keeps going up until it rams into the nozzle.

When I connect the black+white cables into the Z-endstop pins on the SKR Mini the Z-homing works, however I get random probe deploys during printing (at least I think it's from using the Z-endstop pins).

I checked the cabling and if the sensor works by

Test 1:
1. Sending an M119 command (probe retracted) and it reports a z-probe as "Triggered" as expected
2. Deploy the probe with M401 and then check it with M119, now it reads "open" as expected
3. Push the probe with hand, read again with M119 and I get "Triggered" again, as expected.

Test 2:
1. Sending an M119 command (probe retracted) and it reports a z-probe as "Triggered" as expected
2. Deploy the probe with M401 and then check it with M119, now it reads "open" as expected
3. Stow the pin with M402, read again with M119 and I get "Triggered" again, as expected.

Test 3:
1. Sending an M119 command (probe retracted) and it reports a z-probe as "Triggered" as expected
2. Deploy the probe with M280 P0 S10 and then check it with M119, now it reads "open" as expected
3. Stow the pin with M280 P0 S90, read again with M119 and I get "Triggered" again, as expected.

So the cabling and config seem to be correct as I get correct readings. In any way, reading the state of the probe is correct, but the firmware never deploys it before homing Z.

### Expected behavior

I expect the probe to be deployed for Z-homing as it happens with the other endstop pins.

### Actual behavior

The probe never deploys, the bed rams into the nozzle.

### Steps to Reproduce

Install creality CR Touch
Try homing with G28

### Version of Marlin Firmware

Marlin bugfix-2.1.x

### Printer model

Custom build from an old Ender 5 plus

### Electronics

SKR MINI E3 V3

### LCD/Controller

Stock Ender 5 plus DWIN T5

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/15418228/Configs.zip)

**Comment by ellensp** [comment]
you havent enabled #define USE_PROBE_FOR_Z_HOMING
