### ISSUE TITLE
[BUG] (MKS_ROBIN_NANO_V3.1 THERMAL RUNAWAY HOTEND 1)

### ISSUE THREAD

**Issue by S3dNEW** [MarlinFirmware/Marlin#27128]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi,
I just trying to make diy 3d printer with MKS ROBIN NANO V3, all the parts are working fine but start getting issue with hot-end temperature it start falling down after 10 to 15th layer. i am using single nozzle. i noticed second nozzle light start blinking when getting thermal runaway error. when i change board RAMPS 1.6 with Mega no thermal runaway it means i have issue in marlin for MKS ROBIN NANO. please help me to resolve the issue

   

### Version of Marlin Firmware

Mks-Robin-Nano-Marlin2.0-Firmware-COREXY

### Printer model

DIY COREXY

### Bed Leveling

None

### Your Slicer

Slic3r

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
