### ISSUE TITLE
Delta Printer stutters when in print

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#2713]
Hello all,

I'm using the Marlin version Marlin 1.1 RC, from 29 sept and in print I've got a stutter effect.

https://www.youtube.com/watch?v=vn8SGXcCmQo

with Marlin version 1.0.2, all works fine with the same calibration defaults. My assumption will be that the problem comes from the servo interrupt, or segments per seconds (maybe acceleration, deceleration).

Tried to lower the segments per seconds and the problem still occurs. 

I'm running out of ideas:|, does anyone have this problem on delta platform?

Config file
http://pastebin.com/Lan9icj1

**Comment by thinkyhead** [comment]
Are you still seeing this in 1.1.0-RC3? It would be good to determine a cause and make sure this is addressed as far as possible in the final release. Of course, check out #2722 which may be related.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
