### ISSUE TITLE
IMPORTANT: RC2: GCode SPACES should NOT be required (regression?)

### ISSUE THREAD

**Issue by gruvin** [MarlinFirmware/Marlin#2715]
I notice that having no spaces between commands in GCODE in Marlin 1.1 RC2 is no longer supported. This is bad. The GCODE spec allows for no spaces and so should Marlin. Marlin always uses to work without spaces, far as I know.

Examples:

`G1Z10`  -- this gets executed as simply, "G0", while the Z0 part is seemingly ignored.
`G1 Z10` -- works as expected

`M851Z-1.23` -- executes as "M851" with the "Z-1.23" parameter completely ignored. 
`M851 Z-1.23` -- works as expected.

**Comment by dgoadby** [comment]
Well GCODE (RS274) does indeed say that whitespace is ignored. However,  I for one encourage spaces for clarity. Most of the GCODE generators seem to add spaces too. 

If Marlin is supposed to be fully RS274 then you are right in requesting the reinstatement of the feature. If spaces are going be mandatory from now on then the diagnostics should report as appropriate. 

As my GCODE will still work in 1.1 RC2 I'm not fussed either way but, I do think that some clarification/statement would be a good idea as some users might be caught out.

**Comment by Roxy-3D** [comment]
For sure...  Spaces should be 'tolerated'.    @ThinkyHead just published a bunch of changes for RC2 and I added a request to change the code_has_value() function.   Right now it isn't behaving consistent.  It only works if you have no space between the GCode command letter and the parameter (if it is there).

I requested the front end of the code look like this:

```
bool code_has_value() {
  int i = 1;
  char c = seen_pointer[i];

  while (c == ' ')      // skip past any white space between GCode and number
     c = seen_pointer[++i];
```

**Comment by gruvin** [comment]
Well, of course spaces should be both tolerated and supported and I agree
that it makes for more readable code -- naturally. But that's a different thing altogether. What I am saying is that ...

We must be able to enter GCODE _with no spaces present at all_ and have that 
code executed correctly. That used to be the case, right up until RC2, afaik.

That is, spaces in RC2 are no longer simply optional or tolerated. They are
presently MANDATORY. This is not good.

@Roxy-3DPrintBoard ... your suggestion of allowing spaces between codes and values is also a separate thing. I am talking about the next code not being picked up at all, unless a space proceeds it (bad). I am not talking about spaces between codes and values.

Can somebody please test this in their version, rather than just assuming nothing is wrong? Perhaps there's something weird going on with my setup and maybe others will not be able to reproduce this fault at all? I would very much like to know. Thanks.

**Comment by gruvin** [comment]
Hmmm ... my last comment was still ambiguous. Let me restate for clarity ...

We must be able to enter GCODE *with no spaces present *and have it
executed correctly. That used to be the case, right up until RC2, afaik.

That is, spaces are no longer simply optional or tolerated. They are
presently mandatory. This is not good.


Bryan.

**Comment by gruvin** [comment]
Here are the examples again, this time with pre-formatting to hopefully make things more clear ... 

`G1Z10`  -- this gets executed as simply, "G0", while the Z0 part is seemingly ignored.
`G1 Z10` -- works as expected.
`M851Z-1.23` -- executes as "M851" with the "Z-1.23" parameter completely ignored. 
`M851 Z-1.23` -- works as expected.

And here's a copy/paste from the OctoPrint terminal window ...

```
Send: M851 Z-5.45
Recv: echo:Z Offset : -5.45
Recv: ok
Send: M851Z-5
Recv: echo:Z Offset : -5.45
Recv: ok
```

Note that the entire `Z-5` is in the second `Send: M851Z-5` is completely ignored. See how the older value is simply returned, as if just `M851` on its own was sent this time? That's the problem. And it is the case with _all_ codes. Not just M851.

More ...

```
Send: G0X0Y0
Recv: ok
```

NOTHING HAPPENS at all.

```
Send: G0 X0 Y0
Recv: ok
```

... machine moves to X0 Y0, as expected.

I have code dating back months that has no space in there and it was all working fine until I started testing RC2.

**Comment by Roxy-3D** [comment]
Oh!    OK!   I see what you are saying!    And I have verified the difference of behavior between an old version of Marlin I have on one printer and the RC2 not doing any thing with  

```
G0X0Y0
```

This needs to get fixed and put back the way it was!

**Comment by gruvin** [comment]
@Roxy-3DPrintBoard ... thanks for the verification and quite so. Thanks!

I know what it's like. Someone comes along and tells us about some bug that's so unlikely as to be unbelievable ... unless of course, it's not. hehe

**Comment by Roxy-3D** [comment]
A quick question to everybody:   These routines used to not be sensitive to spaces being between numbers and/or parameters.   code_has_value() is a new function so this thought doesn't apply to it.

But for code_value() and code_seen() should we just revert what ever changes got made to those routines and get rid of this bug?   Or should we actually 'fix' the issue and do a Pull Request?

**Comment by Wackerbarth** [comment]
Don't revert. Although a clean commit stream should not have entries that "undo" other entries, the way Github handles merging, a revert is just another merge. Particularly if there are any other changes in the commit that you are reverting, it creates more of a mess than if you just do a normal pull request to change from the current situation to the desired one.

**Comment by thinkyhead** [comment]
Does this issue still exist? Has a patch been submitted to fix this issue? I can see nothing in the current code that would lead to spaces having any bearing on the result of `code_seen`, `code_value`, `code_value_long`, or `code_value_short`.

**Comment by thinkyhead** [comment]
Actually, scratch that. I see that the code won't tolerate no space after the initial command code:

``` cpp
  current_command_args = current_command;
  while (*current_command_args && *current_command_args != ' ') ++current_command_args;
  while (*current_command_args == ' ') ++current_command_args;
```

…and this should be changed to…

``` cpp
  current_command_args = current_command;
  while (*current_command_args >= '0' && *current_command_args <= '9') ++current_command_args;
  while (*current_command_args == ' ') ++current_command_args;
```

In the old behavior `current_command_args` would skip all characters after the initial command until a space, then skip spaces. With this patch, `current_command_args` will skip to the first non-numerical character, then skip spaces.

**Comment by Roxy-3D** [comment]
Correct....   code_has_value() needs to be like:

```
bool code_has_value() {
  int i = 1;
  char c = seen_pointer[i];
  while (c == ' ')  // skip past any white space between GCode and number
     c = seen_pointer[++i];
  if (c == '-' || c == '+') c = seen_pointer[++i];
  if (c == '.') c = seen_pointer[++i];
  return (c >= '0' && c <= '9');
}
```

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
