### ISSUE TITLE
[BUG] NONLINEAR_EXTRUSION has no effect

### ISSUE THREAD

**Issue by dbuezas** [MarlinFirmware/Marlin#27166]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I measured and extruded at different velocities and came up with `M592 A-0.004 B0.00126 C1`
I then tried again and it had no effect.
I made the extrusions with `G1 E+90 F125`  up to `G1 E+90 F375`, and basically found an error of 2.5% at 6mm/s.
![image](https://github.com/MarlinFirmware/Marlin/assets/777196/20e6839d-b87f-4c5f-84c1-ef2eb2e18b3b)

To double check I tried using C1.05 and still had no effect.

I of course enabled NONLINEAR_EXTRUSION in configuration_adv.h and sending M592 without parameters reports the values back.

Could the feature be broken?

### Bug Timeline

I didn't try the feature before

### Expected behavior

To measure less error when extruding 100mm

### Actual behavior

NONLINEAR_EXTRUSION has no effect

### Steps to Reproduce

M592 A-0.004 B0.00126 C1.05 

measure before and after

### Version of Marlin Firmware

Latest bugfix 2.1.x

### Printer model

Ultimaker 2

### Electronics

SKR3

### Other add-ons

Orbiter v2 extruder

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Archive.zip](https://github.com/user-attachments/files/15777679/Archive.zip)

**Comment by vovodroid** [comment]
Can you try some really huge correction, like C2?
N.B.: in latest [bugfix-2.1.x](https://github.com/MarlinFirmware/Marlin) B and A were swapped to match mathematics Av^2+Bc notation.

**Comment by dbuezas** [comment]
> Can you try some really huge correction, like C2?

Set with `M592 A-0.004 B0.00126 C2`
Corroborated setting with 
```
M592
  M592 A-0.00 B0.00 C2.00 <- response
```

Extruded with 
```
G91
G1 E+90 F125
G90
```

--> Resulted in 90mm extruded. C2 had no effect whatsoever. <--

Now I am wondering if NONLINEAR_EXTRUSION does not affect extrusions without other axes moving?

> N.B.: in latest [bugfix-2.1.x](https://github.com/MarlinFirmware/Marlin) B and A were swapped to match mathematics Av^2+Bc notation.

Good to know 👍 
My branch's parent is d38261c9084a5036e6598d4ab15da3e17447f3ad from June the 8th (before the naming change)

**Comment by dbuezas** [comment]
> Now I am wondering if NONLINEAR_EXTRUSION does not affect extrusions without other axes moving?

I think this is it

**Comment by vovodroid** [comment]
> Now I am wondering if NONLINEAR_EXTRUSION does not affect extrusions without other axes moving?

No, that was fixed by me))) in  Disable nonlinear extrusion on unretract #26824

**Comment by dbuezas** [comment]
Oh, I see, so the extrusion is interpreted as an unretract b/c no other axis is moving?

**Comment by dbuezas** [comment]
Closed as the docs PR clarify that this was intentional

**Comment by vovodroid** [comment]
> so the extrusion is interpreted as an unretract b/c no other axis is moving?

Yes.

**Comment by dbuezas** [comment]
~~NONLINEAR_EXTRUSION is working but it made my machine extremely slow. Prints often get interrupted waiting for user input and the UI updates become super slow whenever motors are moving. I have an SKR3 which has a 480MHz mcu so something went very wrong. Is there any caveat I missed?~~ 

It's something else

**Comment by dbuezas** [comment]
The issue was another recently merged PR.

Non linear extrusion works like a charm.

I used https://hotend-flow-tester.netlify.app/ to create heaps of plastic that should be equal, but at different extrusion rates, and then measured their weight (mg). (test idea from cnc kitchen https://www.cnckitchen.com/blog/extrusion-system-benchmark-tool-for-fast-prints ) 

Then let google sheets fit a quadratic on `expected/measured`, applied the correction and reprinted. Here's the result:

<img width="760" alt="image" src="https://github.com/MarlinFirmware/Marlin/assets/777196/9a5b080b-1867-4cac-a7eb-0beab1e9078c">

**Comment by vovodroid** [comment]
I use ruler, it's more accurate and wastes less of filament.

**Comment by dbuezas** [comment]
I found weighing more convenient and faster for me, 10 measurements add up to 6 grams and 5 mins of printing so I'm ok with that.

**Comment by vovodroid** [comment]
> 10 measurements

Why so much? Actually two are enough - at maximum suggested flow rate and in the middle.

**Comment by dbuezas** [comment]
To fit a quadratic and ensure I don't end up under extruding at slow speeds.

**Comment by vovodroid** [comment]
> To fit a quadratic

Three points (zero, middle, end) is enough.

> ensure I don't end up under extruding at slow speeds.

You can assume that there is no underextrusion at zero speed (if esteps is correct).

**Comment by dbuezas** [comment]
Yes, a quadratic has 3 variables and therefore 3 points are enough to find the constants. Regression is not the same as solving the equation, it's about minimising error.

**Comment by vovodroid** [comment]
> Regression is not the same as solving the equation, it's about minimising error.

I don't believe error between both of them matters in extrusion case.

**Comment by dbuezas** [comment]
With my setup it did matter:
<img width="650" alt="image" src="https://github.com/MarlinFirmware/Marlin/assets/777196/12cc28e3-4712-41af-a224-195cd9002fd3">
If you pick the "wrong" 3 points, you'd get a completely different curve.
