### ISSUE TITLE
[BUG] configuration error

### ISSUE THREAD

**Issue by nzodevfivem** [MarlinFirmware/Marlin#27191]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I didn't modify anything special in my config and I can no longer compile

### Version of Marlin Firmware

Marlin-BUGFIX-2.1.X

### Printer model

Creality Ender-3

### Electronics

Bigtreetech SKR E3 V3 mini

### LCD/Controller

Bigtreetech TFT 35

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Config Files: 
[Marlin.zip](https://github.com/user-attachments/files/15904770/Marlin.zip)

ERROR:
```


PS C:\Marlin-bugfix-2.1.x> platformio run --silent -e STM32G0B1RE_btt
Marlin\src\inc\Warnings.cpp:694:4: error: #error "Z_SAFE_HOMING is recommended when homing with a probe. (Enable Z_SAFE_HOMING or define NO_Z_SAFE_HOMING_WARNING to suppress this warning.)"
  694 |   #error "Z_SAFE_HOMING is recommended when homing with a probe. (Enable Z_SAFE_HOMING or define NO_Z_SAFE_HOMING_WARNING to suppress this warning.)"
      |    ^~~~~
Marlin\src\inc\Warnings.cpp:706:6: warning: #warning "Motherboard DIAG jumpers must be removed when SENSORLESS_HOMING is disabled. (Define DIAG_JUMPERS_REMOVED to suppress this warning.)" [-Wcpp]
  706 |     #warning "Motherboard DIAG jumpers must be removed when SENSORLESS_HOMING is disabled. (Define DIAG_JUMPERS_REMOVED to suppress this warning.)"
      |      ^~~~~~~
*** [.pio\build\STM32G0B1RE_btt\src\src\inc\Warnings.cpp.o] Error 1
============================================================================================ [FAILED] Took 151.95 seconds ============================================================================================ 

Environment      Status    Duration
---------------  --------  ------------
STM32G0B1RE_btt  FAILED    00:02:31.949
======================================================================================== 1 failed, 0 succeeded in 00:02:31.949 ========================================================================================PS C:\Marlin-bugfix-2.1.x> echo "done" >"C:\Users\devie\AppData\Local\Temp\ipc"```

**Comment by thisiskeithb** [comment]
This is not a bug.

`#error "Z_SAFE_HOMING is recommended when homing with a probe. (Enable Z_SAFE_HOMING or define NO_Z_SAFE_HOMING_WARNING to suppress this warning.)"`


You need to follow what the error says:

> Enable `Z_SAFE_HOMING` or define `NO_Z_SAFE_HOMING_WARNING` to suppress this warning.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
