### ISSUE TITLE
[FR] (adding RTL(Right to left) languages like arabic )

### ISSUE THREAD

**Issue by Siderwar** [MarlinFirmware/Marlin#27203]
### Describe the feature you want

adding arabic (or any right to left languages ) language to marlin supported languages (i can do all translations to this language and provide them to you but need some one to do its coding jobs )

### Additional context

Hi, I'm a primary school teacher, I want to teach my students how a 3D printer works and let them print anything they want under my supervision. My main goal is to increase users and enthusiasts of 3D printers (like myself). But at the age of these students, English is considered a challenge that should be simplified for them.

I have built a simple 3D printer with acceptable accuracy with mega 2560 ( https://store.arduino.cc/products/arduino-mega-2560-rev3 ) and ramps1.4 ( https://reprap.org/wiki/RAMPS_1.4 ) and reprap full graphical ( https://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller )

the question is

can i create Arabic or any right to left languages menu screen on it ?

If not can i translate some important menu and sub menu of it to Arabic ?

I look forward to your help, a large and active community of 3D printer users .

thanks in advance.

**Comment by ellensp** [comment]
There is already an open feature request for Arabic https://github.com/MarlinFirmware/Marlin/issues/7423
