### ISSUE TITLE
[BUG] M117 doesn't work with Stowable Z-PROBE

### ISSUE THREAD

**Issue by jgilmore** [MarlinFirmware/Marlin#27232]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

With the following settings:
#define FIX_MOUNTED_PROBE
#define PAUSE_BEFORE_DEPLOY_STOW

When told to home, (Marlin will pause and display a "Deploy Z-Probe" message, and a "Stow Z-Probe" message afterward. This is correct behavior.

What is NOT correct, is that the "Stow Z-Probe" message is then permanently displayed. All sorts of errors that REALLY REALLY SHOULD display a message (like wait-for-temperature timeout, temperature out of range, etc.) don't, and instead display the "Stow Z-Probe" message.

This makes it rather difficult to determine why the print stopped and the printer is now beeping for all it's worth! Hiding error messages is a big deal.

The M117 messages also don't display. (I have one before each layer in the G-code, so I can tell how far along it is.)
[configBugM117.zip](https://github.com/user-attachments/files/16071469/configBugM117.zip)

Please note that while this is an older firmware version, this bug is kinda corner case (only affecting manually stowable Z-probe printers) and I would be surprised if it doesn't still exist in latest. I would test this, but I'm in the middle of a 21-hour (predicted) print. (Thus having time to type this up.)

### Bug Timeline

New

### Expected behavior

I expect the printer to stop displaying the Z-Probe message, and subsequently display error and informational (M117) messages as needed.

### Version of Marlin Firmware

bugfix-2.0.x (2021-10-18)

### Printer model

Tevo Tarantula

### Electronics

Stock (#define MOTHERBOARD BOARD_MKS_GEN_13)

### LCD/Controller

Yes

### Other add-ons

Stowable Z-Probe near nozzle (z-limit switch moved to a custom movable mount)

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
Your provided configs shows CONFIGURATION_H_VERSION 02000902 
This is positively ancient code

Please test the [`bugfix-2.1.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to see where it stands. If the problem has been resolved then we can close this issue. If the issue isn't resolved yet, then we should investigate further.

**Comment by monkeydave** [comment]
This issue still occurs with latest bugfix-2.1.x branch, been meaning to look into this for ages but just lived with it.
Hopefully just a one line fix unless I am missing something.
