### ISSUE TITLE
[BUG] M501 logic with version mismatch

### ISSUE THREAD

**Issue by rondlh** [MarlinFirmware/Marlin#27236]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I changed some settings in my firmware which causes the EEPROM size to change, but it's reported as a version number errors twice, which is odd.

```
echo:EEPROM version mismatch (EEPROM=? Marlin=V90)
echo:EEPROM version mismatch (EEPROM=? Marlin=V90)

```
I have EEPROM_SETTINGS  enabled, and also EEPROM_AUTO_INIT to initilize the factory defaults, but this does not work.
To my surprise if found that lots of settings are 0:

```
M306
M306 E0 P0.00 C0.00 R0.0000 A0.0000 F0.0000 H0.0000

```

I believe there is an error in the logic of M501 in settings.cpp

```
  /**
   * M501 - Retrieve Configuration
   */
  EEPROM_Error MarlinSettings::_load() {
    EEPROM_Error eeprom_error = ERR_EEPROM_NOERR;

    const EEPROM_Error check = check_version();
    if (check == ERR_EEPROM_VERSION) return eeprom_error;
```

This is odd because if check_version() returns a "version error", then _load() returns "no error".

I think it should be something like this (difference in the last line):

```
  /**
   * M501 - Retrieve Configuration
   */
  EEPROM_Error MarlinSettings::_load() {
    EEPROM_Error eeprom_error = ERR_EEPROM_NOERR;

    const EEPROM_Error check = check_version();
    if (check == ERR_EEPROM_VERSION) return ERR_EEPROM_VERSION; 
```

The double version mismatch error can probably be explained by the code below. validate() calls _load(), and if no validation error is detected then _load() is called again. But actually _load() seems to return the wrong status.

```
  bool MarlinSettings::load() {
    if (validate()) {
      const EEPROM_Error err = _load();
```

```
  bool MarlinSettings::validate() { // IRON, TRUE IF OK, FALSE IS ERROR
    validating = true;
    #ifdef ARCHIM2_SPI_FLASH_EEPROM_BACKUP_SIZE
      EEPROM_Error err = _load();
      if (err != ERR_EEPROM_NOERR && restoreEEPROM()) {
        SERIAL_ECHOLNPGM("Recovered backup EEPROM settings from SPI Flash");
        err = _load();
      }
    #else
      const EEPROM_Error err = _load();
    #endif
    validating = false;

    if (err) ui.eeprom_alert(err);

    return (err == ERR_EEPROM_NOERR);
  }
```

### Bug Timeline

No sure, in the last 6 months I guess

### Expected behavior

Reset settings to factory defaults when and EEPROM error is detected.

### Actual behavior

Factory defaults are not loaded, a double errors message is given.

### Steps to Reproduce

1. Create a corrupt EEPROM storage, for example by changing the number of bed probe points.
2. Update to the new firmware and check for the double error message and the loaded defaults like PID/MPC settings
3. In the pin-file define FLASH_EEPROM_EMULATION (I cannot use the onboard EEPROM because I use the CAN bus).
and uncomment: I2C_EEPROM

### Version of Marlin Firmware

Bugfix 2.1.x June 30st 2024

### Printer model

Custom

### Electronics

MKS Monster8 V1.0

### LCD/Controller

BTT TFT35 V3.0

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Other (explain below)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config and Pins.zip](https://github.com/user-attachments/files/16074681/Config.and.Pins.zip)

**Additional note about thermal runaway**
This issue causes lots of settings to be set to 0, for example all MPC become 0: M306 E0 P0.00 C0.00 R0.0000 A0.0000 F0.0000 H0.0000
I expect that this is the reason why my hotend decided to destroy itself after a M501 (hotend started heating out of control with target temp set to 0 degrees). The thermal protection did not kick in on time. It's probably better to set some minimal values for parameters that can cause issues. In this case I guess the P (power) parameter should have a minimum value (e.a 10 watt). There might be more parameters that can cause issues because of mathematics (divide by 0) that can cause a thermal runaway. Probably the block heat capacity and sensor responsiveness should also have some minimum values to enhance safety.

**Comment by ellensp** [comment]
seems to be a typo

```DIFF
diff --git a/Marlin/src/module/settings.cpp b/Marlin/src/module/settings.cpp
index d4467b7687..a553d56745 100644
--- a/Marlin/src/module/settings.cpp
+++ b/Marlin/src/module/settings.cpp
@@ -1823,7 +1823,7 @@ void MarlinSettings::postprocess() {
     EEPROM_Error eeprom_error = ERR_EEPROM_NOERR;
 
     const EEPROM_Error check = check_version();
-    if (check == ERR_EEPROM_VERSION) return eeprom_error;
+    if (check == ERR_EEPROM_NOPROM) return eeprom_error;
 
     uint16_t stored_crc;

``` 
And it seem to be working as desired again

**Comment by dbuezas** [comment]
I think it used to return ERR_EEPROM_NOERR instead.

**Comment by ellensp** [comment]
it used to be "if (!EEPROM_START(EEPROM_OFFSET)) return eeprom_error;"

see

https://github.com/MarlinFirmware/Marlin/pull/27199/files#diff-3b2c0da2300fa99c611618bb2d1a9f7e81edb092aac5d49c83a6d9068561838cL1806

**Comment by dbuezas** [comment]
Look at the line above. `eeprom_error = ERR_EEPROM_NOERR`
