### ISSUE TITLE
[BUG] Compiler Warning on MarlinCore.cpp

### ISSUE THREAD

**Issue by fnsign** [MarlinFirmware/Marlin#27258]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

 see screenshot 
 ![CleanShot 2024-07-10 at 19 03 49@2x](https://github.com/MarlinFirmware/Marlin/assets/25816647/f5dde1aa-d7c0-4166-b1bb-2bdc6307e41d)

### Bug Timeline

first appearance ca. 3 weeks ago

### Expected behavior

No compiler warning

### Actual behavior

Compiler warns

### Steps to Reproduce

Start compiler on VSCode

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Ender 3 Pro

### Electronics

BIGTREETECH SKR MINI E3 V1.2

### LCD/Controller

stock

### Other add-ons

--

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
Please attach your configuration files.

This does not occur on stock ramps configs

**Comment by ellensp** [comment]
Setting   #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V1_2
and #define SERIAL_PORT 1
is enough to trigger this minor warning.

**Comment by ellensp** [comment]
Issue is stm32 implementation of analogInputToDigitalPin (uint32_t)  vs marlins pin definition (int32_t) 

Code in question was added in https://github.com/MarlinFirmware/Marlin/pull/27219

**Comment by ellensp** [comment]
code already has

#pragma GCC diagnostic ignored "-Wnarrowing"

so add this  line under it

#pragma GCC diagnostic ignored "-Wsign-compare"

**Comment by Matsavol** [comment]
I can confirm same problem happening on Longer LK1 (Alfawise U20). Visual Studio Code does compile it showing this error, but does produce bin image. Once the printer is flashed with the resulting image it gets stuck in the "Load EEPROM defaults" screen touchscreen not responding.

**Comment by ellensp** [comment]
This warning does not cause any issues

**Comment by fnsign** [comment]
> Please attach your configuration files.
> 
> This does not occur on stock ramps configs

Here are my config files:

[configs.zip](https://github.com/user-attachments/files/16171782/configs.zip)

**Comment by ellensp** [comment]
PR created, closing issue
