### ISSUE TITLE
About my wanting to add a custom board myself

### ISSUE THREAD

**Issue by qinMOTU** [MarlinFirmware/Marlin#27250]
#### `pins.h`

```c
#elif MB(LASER)
  #include "stm32f1/pins_LASER.h"                   // STM32F1
```

#### `boards.h`
```c
#define BOARD_LASER                   5068
```

#### `Configuration.h`
```c
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_LASER
#endif
```

#### `platformio.ini`
```ini
[env:laser]
platform          = ststm32
board             = genericSTM32F103C8
framework         = arduino
```

I set it up according to the official instructions, and there will be an error::

```prolog
Build environment 'laser' is incompatible with `BOARD_LASER`. Use one of these environments:
```

### Describe the feature you want

I need your help

**Comment by ellensp** [comment]
look at pins.h

every include line has a comment on that line that lists the valid envs for that board, starts with key env:


This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
