### ISSUE TITLE
[BUG] Backlash compensation triggers watchdog reset while printing (E5Pro, SKR mini E3 V3, BLTouch, marlin autobuild)

### ISSUE THREAD

**Issue by HLMazurFFD** [MarlinFirmware/Marlin#27265]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Attemped to add backlash compensation to my marlin 2.1.2.4 build. build has zero issues and prints fine with backlash compensation commented out. when backlash comp is uncommented(no alterrations beyond that, I left the actual compensation  at zero), printer will restart randomly during a print, killing the print and shutting off heaters. reading on the internet this appears to be the watchdog timer triggering.

Printer is ender 5 pro, running a BTT SKR Mini E3 V3, with BLTouch, and an E3D V6 hotend on Hero Me with dual 5015 fans, stock hotend cooling fan. Direct drive with creality stock all metal extruder.

### Bug Timeline

new- noticed 7/12, still happening 7/13

### Expected behavior

printer should make it through a first layer test print with zero issues, like it does without backlash compensation added to FW build

### Actual behavior

with backlash compensation added to FW build(compensation set to zero) at a random point during printing any file, printer will restart without warning, ending print, but with zero other apparent issues. As far as I can tell, this is the watchdog restart timer triggering by not being reset.

### Steps to Reproduce

firmware builds properly, I guess just run a print with backlash comp turned on and set to zero, with similar FW settings. 

### Version of Marlin Firmware

2.1.2.4

### Printer model

Creality Ender 5 Pro

### Electronics

SKR Mini E3 V3, BLTouch, E3DV6 hotend, dual 5015 fans

### LCD/Controller

stock creality ender 5 LCD

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Files attached, no other modifications to Marlin
[2.1.2.4 config files E5.zip](https://github.com/user-attachments/files/16215572/2.1.2.4.config.files.E5.zip)

log output when restart happens from pronterface, truncated to last section:

echo:M105
echo:G1 F900 X87.28 Y81.623 E167.33225
echo:G0 F6000 X87.074 Y81.983
echo:G1 F900 X136.648 Y131.557 E169.66406
echo:G0 F6000 X136.442 Y131.916
echo:M105
echo:G1 F900 X86.867 Y82.341 E171.99592
echo:G0 F6000 X86.659 Y82.7
echo:G1 F900 X136.235 Y132.275 E174.3278
echo:G0 F6000 X136.028 Y132.633
echo:M105
echo:G1 F900 X86.452 Y83.058 E176.65968
echo:G0 F6000 X86.245 Y83.417
echo:G1 F900 X135.82 Y132.992 E178.99153
Exception in thread read thread:
Traceback (most recent call last):
  File "printrun\printcore.py", line 333, in _readline
  File "printrun\printcore.py", line 329, in _readline_nb
  File "serial\serialwin32.py", line 275, in read
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "printrun\printcore.py", line 420, in _listen
  File "printrun\printcore.py", line 354, in _readline
IndexError: tuple index out of range
Can't write to printer (disconnected ?):
Traceback (most recent call last):
  File "printrun\printcore.py", line 744, in _send
  File "serial\serialwin32.py", line 317, in write
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

Can't write to printer (disconnected ?):
Traceback (most recent call last):
  File "printrun\printcore.py", line 744, in _send
  File "serial\serialwin32.py", line 317, in write
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

Can't write to printer (disconnected ?):
Traceback (most recent call last):
  File "printrun\printcore.py", line 744, in _send
  File "serial\serialwin32.py", line 317, in write
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.
