### ISSUE TITLE
[FR] BTT SFS v2.0 sensor support

### ISSUE THREAD

**Issue by MrKuskov** [MarlinFirmware/Marlin#27267]
### Is your feature request related to a problem? Please describe.

The BTT SFS v2.0 sensor has two sensors, a switch sensor and a motion sensor. Marlin can only support one sensor per extruder. 

### Are you looking for hardware support?

any board with two free pins. 
You can use the default scheme to assign pins. 
#define FIL_RUNOUT_PIN to assign the switch sensor, 
#define FIL_MOTION1_PIN to assign the motion sensor

### Describe the feature you want

The BTT SFS v2.0 sensor has two sensors, a switch sensor and a motion sensor. Marlin can only support one sensor per extruder. It is necessary to make support for two sensors. Marlin has only one configuration parameter to control the sensor 
`#define FILAMENT_RUNOUT_DISTANCE_MM  `
The following logic must be implemented: 
1. The switching sensor and the motion sensor show the absence of a filament in this case, FILAMENT_RUNOUT_DISTANCE_MM is equal to the distance from the filament sensor to the extruder, so that the entire filament can be consumed. 
2. The switching sensor indicates the presence of a filament, and the motion sensor indicates the absence of motion, in this case FILAMENT_RUNOUT_DISTANCE_MM is equal to the accuracy of the motion sensor reading.

### Additional context

A PTFE tube must be installed between the filament sensor and the extruder to fix the distance between the sensor and the extruder

**Comment by ellensp** [comment]
This is already supported   FILAMENT_SWITCH_AND_MOTION
https://github.com/MarlinFirmware/Marlin/pull/25548
