### ISSUE TITLE
Does auto-probe works for Delta ? 

### ISSUE THREAD

**Issue by obor00** [MarlinFirmware/Marlin#2728]
In example/delta/Configuration.h it is said that :
   //Bed Auto Leveling is still not compatible with Delta Kinematics

Is it still true in recent versions ?

**Comment by Roxy-3D** [comment]
No...  Delta's do Auto Bed Leveling now.    We should probably cleanup that comment.

**Comment by obor00** [comment]
ok, great, so I'll try it again. Does G30 works also  with delta ?

**Comment by Roxy-3D** [comment]
G30 should work for a Delta.   It doesn't use or do anything differently than G29.   But I have not used it.

**Comment by AnHardt** [comment]
In the branches where //#define AUTO_BED_LEVELING_FEATURE for deltas is possible the comment is already removed.
When '#define AUTO_BED_LEVELING_FEATURE' is defined G30 should work.
