### ISSUE TITLE
[BUG] CALIBRATION_GCODE (Bug or problem)

### ISSUE THREAD

**Issue by studiodyne** [MarlinFirmware/Marlin#27296]
Hi.
Calibration is buggy or have some little problems to adjust.

Behavior :  If cube >= 10mm ,  G425v or G425T not working , but G425 works.

Reason: The sequence of calibration , have two 'Uncertainty distances'. With this value, are trigged two feedrates (a slow and a fast) and two security Z max moves. The problem is if the cube > 10mm and the security max z move is  ' 5mm' (50mm for the higher uncertainty  ),  the z probing stops because too long distance, calibrations stops... But in G425, the uncertainty is defined to the max value, the calibrations sequences are double , one fast , one slow , and , the security is 50mm for the first probing , and  5mm for the second and calibration can continue.

`  const feedRate_t mms = fast ? MMM_TO_MMS(CALIBRATION_FEEDRATE_FAST) : MMM_TO_MMS(CALIBRATION_FEEDRATE_SLOW);  
`
`  const float limit    = fast ? 50 : 5;`
Solution: 
- The best choice , is to add a double sequence for all calibration command , one fast , one slow. Because of the cnc planes that can be XZ or YZ, all calibrations sequences must be the same for all axis.
- May be , to tweak the max security distance for each 'uncertainty ' with the dimension of the cube in the calculation 

I'm working on it
Thks

Note : Unused 
`#ifndef CALIBRATION_MEASUREMENT_CERTAIN
  #define CALIBRATION_MEASUREMENT_CERTAIN   0.5 // mm
#endif`

**Comment by thisiskeithb** [comment]
Closing since you have not provided any useful debug information and this is not actionable.

**Comment by studiodyne** [comment]
> Closing since you have not provided any useful debug information and this is not actionable.

Hi , now it's done , take a look if you have , one minute
Thks

**Comment by studiodyne** [comment]
how to re open ?

**Comment by thisiskeithb** [comment]
> Hi , now it's done , take a look if you have , one minute

We created an Issue template for a reason. Don't create a blank/fake issue just so you can strip everything out and bypass all of the required fields.

Please create a new, proper [Bug Report](https://github.com/MarlinFirmware/Marlin/issues/new/choose) and be sure to fill out the entire form before submitting it.

**Comment by studiodyne** [comment]
You win ! I surrender
