### ISSUE TITLE
[BUG] Laser does not turn on

### ISSUE THREAD

**Issue by qulet** [MarlinFirmware/Marlin#27298]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I activated the Fire pulse laser functions from the LCD menu and it works. The laser is activated with gcode `M3 SXX`.

Running the following code:
LightBurn 1.0.06 

```gcode
; Marlin device profile, current position
; Bounds: X-23 Y-23.5 to X23 Y23.5
G21
G91
; Cut @ 500 mm/min, 50% power
M9
M05
G0X23 Y-23.5 F0
; Layer C00
G1X-46 F500 I S50
G1 Y47 
G1X46 
G1 Y-47 
M9
M05
; return to starting pos
G0 X-23 Y23.5 F0
```
Does not turn on the laser - the head draws a rectangle 46x47 mm without activated laser with 50% power

### Bug Timeline

Now  

### Actual behavior

The head with the lit laser draws a rectangle 46x47 mm with 50% power

### Steps to Reproduce

1. Start Marlin
2. Activate the laser in the LCD menu.
3. run the code from the card or via the USB port.

### Version of Marlin Firmware

2.1.24

### Printer model

Core XY

### Electronics

MKSSbase

### LCD/Controller

RepRapDiscount_Full_Graphic_Smart_Controller

### Other add-ons

NEJE 40W N40630 CNC laser head

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Simplify3D

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/user-attachments/files/16326144/Marlin.zip)

**Comment by qulet** [comment]
Sorry, I confused actual behavior with expected behavior...

**Comment by thisiskeithb** [comment]
Please translate your comments to English so we can better help you. I've updated your issue text & reply.

---

From your config:

> ```c
> #define CONFIGURATION_H_VERSION 02010204
> ```

Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by qulet** [comment]
The laser in Marlin V 2.1.1 works properly.

**Comment by qulet** [comment]
Changing the software version fixed the problem.
