### ISSUE TITLE
SERVO0_PIN incorrectly defined for Ramps1.3 in pins_RAMPS_13.h

### ISSUE THREAD

**Issue by arthur500** [MarlinFirmware/Marlin#2729]
For Marlin 1.1 RC2 in file pins_RAMPS_13.h the define for SERVO0_PIN is set as 11.
Ramps1.3 boards use pin 7 for SERVO0_PIN while Ramps1.4 boards use pin 11. The file needs a test to distinguish between 1.3 and 1.4 version boards.  This pin is usually used for auto bed levelling control.

**Comment by AnHardt** [comment]
http://reprap.org/wiki/File:Arduinomega1-3connectors.png
http://reprap.org/wiki/File:Arduinomega1-4connectors.png

**Comment by AnHardt** [comment]
There are more differences between the graphics

```
1.3 1.4
  7  11
  2   1
  1   0
 48  40
```

But when tracing http://reprap.org/wiki/File:Ramps_v1.3_shield_bothsides.png and http://reprap.org/wiki/File:Ramps_v1.4_shield_bothsides.png you find the last 3 differences are typos in http://reprap.org/wiki/File:Arduinomega1-3connectors.png.

**Comment by AnHardt** [comment]
Anyone a better solution then https://github.com/MarlinFirmware/Marlin/pull/2741 ?

**Comment by AnHardt** [comment]
#2741 is merged.
