### ISSUE TITLE
[BUG] Recent LPC "toggle" change breaks multi-driver axis configs

### ISSUE THREAD

**Issue by Sanguium** [MarlinFirmware/Marlin#27341]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When activating a second Z driver and EDGE_STEPPING, the first Z motor grinds and loses steps, while the second works fine.
All other axis work fine, problem goes away when disabling the Z2 driver OR disabling EDGE_STEPPING.

This is the M122 report after moving Z 10m up with and without EDGE_STEPPING enabled:
EDGE_STEPPING OFF:
![edge_stepping_OFF](https://github.com/user-attachments/assets/21ca2992-60cc-4ac6-884f-c5bfa00cda26)
EDGE_STEPPING ON:
![edge_stepping ON](https://github.com/user-attachments/assets/2d22e047-bd30-4204-b886-588407aa2683)

Using SKR v1.3 with TMC2009 drivers

### Bug Timeline

Tested wrong in 2.1.2.4 and current bugfix-2.1.x

### Expected behavior

Dual Z drivers work fine with the recomended EDGE_STEPPING for trinamic drivers

### Actual behavior

First Z motor rattles and loses steps

### Steps to Reproduce

1. Set `Z_DRIVER_TYPE  TMC2209` and `Z2_DRIVER_TYPE TMC2209`
2. Set `EDGE_STEPPING`
3. Move Z axis

### Version of Marlin Firmware

Commit 0ec1a543

### Printer model

Custom cartesian

### Electronics

SKR v1.3 board with TMC2209 drivers

### LCD/Controller

BIGTREE_TFT24_V1_1

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/user-attachments/files/16566144/Config.zip)

**Comment by anomalchik** [comment]
Same issue with mks sgen l v1
I use tmc2226 and they also use the driver type TMC2209

**Comment by anomalchik** [comment]
If you disconnect the first motor but do not remove the driver, the second motor remains in the brake mode or something like that. Also, the second motor works properly if you remove the Z1 driver.

**Comment by tombrazier** [comment]
#27489 is a duplicate of this issue.

I, too, have dual Z axes and TMC2209 but do not have the problem. The primary difference that I can is is that I am running on 8 bit AVR and all those reporting the problem have LPC1768.

Looking at the code, `EDGE_STEPPING` for the first Z stepper comes down to calling `TOGGLE(Z_STEP_PIN)` on line 156 of `module/stepper/trinamic.h`. The `TOGGLE` macro is MCU dependent.

**Comment by ellensp** [comment]
@tombrazier TOGGLE was recently changed on the LPC176x https://github.com/MarlinFirmware/Marlin/pull/27149 ...

**Comment by tombrazier** [comment]
Okay, @moriamoria, @anomalchik and @Sanguium here is something to try:

Change the file `Marlin/src/HAL/LPC1768/fastio.h` as follows:

Remove `#define _TOGGLE(IO)           LPC176x::gpio_toggle(IO)`

and replace it with `#define _TOGGLE(IO)           _WRITE(IO, !READ(IO))`

Does this resolve the problem?

I have a bunch of mainboards but no LPC1768 to test on.

**Comment by moriamoria** [comment]
Hello,

I have kill my SKR 1.3 motherboard, the X- Y- pullup end switch seems dead !

I have order a new SKR 1.4 turbo, and i will do the test when I receive it.

Thanks for your support

Regards

**Comment by Sanguium** [comment]
> Okay, @moriamoria, @anomalchik and @Sanguium here is something to try:
> 
> Change the file `Marlin/src/HAL/LPC1768/fastio.h` as follows:
> 
> Remove `#define _TOGGLE(IO) LPC176x::gpio_toggle(IO)`
> 
> and replace it with `#define _TOGGLE(IO) _WRITE(IO, !READ(IO))`
> 
> Does this resolve the problem?
> 
> I have a bunch of mainboards but no LPC1768 to test on.

Tested with latest bugfix, this change does fix the problem.
Can I keep this until the fix is merged or does it have some other caveats?

Thanks.

**Comment by tombrazier** [comment]
@mh-dm please see above and also #27489. It looks like #27149 has caused a problem with dual Z steppers. My guess is that two calls to `LPC176x::gpio_toggle()` in quick succession can cause some kind of race condition. Any thoughts?

**Comment by tombrazier** [comment]
I think I have found the race condition. Function `pin_type::gpio_toggle(IO)` is defined in @p3p's [PlatformIO framework for the LPC1768](https://github.com/p3p/pio-framework-arduino-lpc176x) in file `master/system/lpc176x/pin_control.h`.

The function is
```
  [[gnu::always_inline]] inline void toggle() {
    gpio_reg().reg_control ^= gpio_mask();
  }
```

Reading chapter 9 of the LPC1768 user manual (a copy can be found [here](https://www.keil.com/dd/docs/datashts/philips/lpc17xx_um.pdf)) this function reads `FIOPIN`, modifies it and sets it to the new value. However a read from `FIOPIN` returns the current _pin state_, not the current _port output register_. To get the latter you have to read `FIOSET`.

As a consequence, when two pin toggles occur in quick succession the second read of the pin state can happen before the pin has actually changed after the first toggle operation (at least this is my working theory).

I think the function should be modified to:
```
  [[gnu::always_inline]] inline void toggle() {
    gpio_reg().reg_control = gpio_reg().reg_set ^ gpio_mask();
  }
```

If there is anyone who is able to find their platformio directory (on Linux it is `~/.platformio` and on Windows I think it will be `C:\Users\<username>\.platformio`) and change the file `packages/framework-arduino-lpc176x/system/lpc176x/pin_control.h` as I suggest I would be interested to know the result.

Also any comment by @p3p would be appreciated.

**Comment by tombrazier** [comment]
> Can I keep this until the fix is merged or does it have some other caveats?

@Sanguium Yes you can keep it until a fix is merged. The difference is slightly less clean step timing, but that's way better than steps not actually happening.

PS If you're able to test the change to `LPC176x::gpio_toggle()` I would appreciate it.

**Comment by Sanguium** [comment]
> PS If you're able to test the change to `LPC176x::gpio_toggle()` I would appreciate it.

This also works.

**Comment by tombrazier** [comment]
> This also works.

Excellent. So the solution is to submit a PR to @p3p's LPC1768 framework. I would appreciate pretty wide testing, I wouldn't want to break a the framework accidentally.

**Comment by tombrazier** [comment]
https://github.com/p3p/pio-framework-arduino-lpc176x/pull/55

**Comment by mh-dm** [comment]
Sorry for #27149 opening up a can of issues.

@tombrazier Great investigation!

> As a consequence, when two pin toggles occur in quick succession the second read of the pin state can happen before the pin has actually changed after the first toggle operation (at least this is my working theory).

That's also my read of the code and the reported issue. Z step pin gets toggled with `gpio_reg().reg_control ^= gpio_mask();` (note that means `gpio_reg().reg_control` necessarily gets read as it's `volatile`). Then Z2 immediately also gets toggled with another `gpio_reg().reg_control ^= gpio_mask();` which should also mean another `gpio_reg().reg_control` read. 1) This read happens so quickly the pin state didn't change yet. 2) `toggle()` in particular is problematic because it's writing to `gpio_reg().reg_control` which can in theory affect the state of other pins (whereas [`get()` followed by a `set(inverse)` which then calls either `set()` or `clear()`](https://github.com/p3p/pio-framework-arduino-lpc176x/blob/master/system/lpc176x/pin_control.h#L80) can't).

I think the proposed solution:
```C++
[[gnu::always_inline]] inline void toggle() {
    gpio_reg().reg_control = gpio_reg().reg_set ^ gpio_mask();
  }
```
is correct to fix `toggle()` for one pin affecting another.

**Comment by tombrazier** [comment]
@mh-dm Do you have an LPC mainboard you could do some testing on? I'd like to see this tested fairly widely considering it affects the underlying framework.

**Comment by anomalchik** [comment]
I'll try to check it today.

**Comment by anomalchik** [comment]
> ```
>   [[gnu::always_inline]] inline void toggle() {
>     gpio_reg().reg_control = gpio_reg().reg_set ^ gpio_mask();
>   }
> ```
@tombrazier
works fine for me. Thanks. My board is MKS_SGEN_L LPC1768.

**Comment by tombrazier** [comment]
@anomalchik Thanks.

**Comment by mh-dm** [comment]
> @mh-dm Do you have an LPC mainboard you could do some testing on? I'd like to see this tested fairly widely considering it affects the underlying framework.

Sure. Tested in the same scenario as in #27149 and can confirm that the proposed `toggle()` version works including maintaining the slightly more consistent timings/speed benefit over the original `_WRITE(IO, !READ(IO))`.

**Comment by tombrazier** [comment]
Thanks Mihai.

**Comment by thinkyhead** [comment]
There will be a new deployment of @p3p pio-framework-arduino-lpc176x very soon, so hold tight! We'll be sure to get this back-ported to all LTS branches as soon as possible too.
