### ISSUE TITLE
RC-2 Multiple Extruder Auto Bed Leveling does not work!

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#2734]
I apologize...  I thought I saw a thread where ThinkyHead had made a fix for this.  I might be imagining that because I can't find it anywhere.

Right now, it looks like the Z-Probe offset is being lost when the printer switches the active extruder from one to the other.   Or maybe the problem is worse.   But for sure the nozzle ends up in a funky place relative to the bed and the way it is moving the nozzle is at a noticeable tilt.

This was confirmed on a Delta printer.

**Comment by Roxy-3D** [comment]
I found it:  https://github.com/MarlinFirmware/MarlinDev/pull/124

It looks to me like this needs to be applied to RC-2 also.   But I would appreciate somebody else jumping in and confirming that!   :)

**Comment by thinkyhead** [comment]
Yes, if this patch hasn't also been submitted to `RCBugFix`, I should do that asap. This bug was discovered a while ago and the fix is pretty simple.

**Comment by thinkyhead** [comment]
Ok, to make this fix properly, according to @jminardi just one change needs to be done. The line which reads:
```cpp
offset_vec.apply_rotation(plan_bed_level_matrix);
```
…should be changed to…
```cpp
offset_vec.apply_rotation(plan_bed_level_matrix.transpose(plan_bed_level_matrix));
```
I will make a new set of PRs for `dev` and `RCBugFix` that make this change as specified.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
