### ISSUE TITLE
Combine board type 33-36

### ISSUE THREAD

**Issue by sgsdxzy** [MarlinFirmware/Marlin#2735]
Currently I run 3 types of tools on my Prusa i3-like frame with ramps 1.4: 
1. Dual extruder(D8, D9) and heat bed(D10)
2. Laser on D9
3. Spindle on D9
On type 2 and 3, I use M106 S to control the power of laser and speed of spindle. However, this requires me to set BOARD to 33(EFB). To use dual extruder, I have to set BOARD to 34(EEB). So on changing tools I need to recompile and re-upload the firmware. 
Is it possible to combine 33 and 34 to get Extruder0, Extruder1/fan, bed so that both secondary extruder heater control command and fan control command can control the output of D9?

**Comment by Wackerbarth** [comment]
> On Oct 28, 2015, at 1:46 AM, sgsdxzy notifications@github.com wrote:
> 
> Currently I run 3 types of tools on my Prusa i3-like frame with ramps 1.4: 
> 1. Dual extruder(D8, D9) and heat bed(D10)
> 2. Laser on D9
> 3. Spindle on D9
> On type 2 and 3, I use M106 S to control the power of laser and speed of spindle. However, this requires me to set BOARD to 33(EFB). To use dual extruder, I have to set BOARD to 34(EEB). So on changing tools I need to recompile and re-upload the firmware. 
> Is it possible to combine 33 and 34 to get Extruder0, Extruder1/fan, bed so that both secondary extruder heater control command and fan control command can control the output of D9?
> 
> This is not something that will be available in Marlin 1.1.

However, you suggestion is something that we need to consider as we implement a HAL-based description of the hardware configuration in a subsequent release.

Please repost this as a feature request on MarlinDev.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
