### ISSUE TITLE
[BUG] (bug summary)multiple feature not recognize. 

### ISSUE THREAD

**Issue by MitchRCcrawler** [MarlinFirmware/Marlin#27360]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I am trying to flash my Anet A8 firmware for the bigger lcd screen of the Anet. However to do this, I need to get the Marlin 1.1.9 (cannot go for the 2.0 + for machine limitation).  By using the 1.1.x, when I try to compile, many missing feature / error occurs. I'm new in this but I don't know either if I have all the right versions of software has this is an app ld machine. 

### Bug Timeline

Today

### Expected behavior

To use a new lcd screen. 

### Actual behavior

Firmware doesn't compile. 

### Version of Marlin Firmware

1.1.9

### Printer model

Anet A8

### Bed Leveling

None

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.com/servers/marlin-firmware-461605380783472640) Discord server
