### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by dcohenb** [MarlinFirmware/Marlin#2737]
When trying to visit http://www.marlinfirmware.org/
I get an error "Sorry! This site is experiencing technical difficulties."
Not sure if this is the place to report it but I can't think of anywhere else

**Comment by AnHardt** [comment]
(Cannot contact the database server)

@thinkyhead  @scotty1024

**Comment by a4jp-com** [comment]
Same error message here

**Comment by Wackerbarth** [comment]
I thought that, because we could not get access for commit rights, we were abandoning that site in favor of one which we could actually maintain.

**Comment by dcohenb** [comment]
If it's a simple static website we can host it on Github
If it's more complicated I can donate an instance to host the website

**Comment by Wackerbarth** [comment]
It was my understanding that we had moved it to the wiki associated with this github account

**Comment by AnHardt** [comment]
@Wackerbarth 
The wiki here is far from ideal. A Mediawiki is much more comfortable. But every wiki is better than one you can't write to.
At least we have a backup now.

@dcohenb 
No, it was a Mediawiki.

**Comment by Wackerbarth** [comment]
@AnHardt -- "But every wiki is better than one you can't write to." 
Precisely! Isn't that why we changed?
But "CHANGED" is the operative word.

So, from my perspective, www.marlinfirmware.org does not exist and we should steer all Marlin users away from it.

If the owners of that website wish to rejoin, then they must address the access issues. As a community, we cannot have a critical part of the infrastructure which is out of the control of the core community.

**Comment by AnHardt** [comment]
For me it was more an 'emergency operation' then a wanted change. Without any positive feedback a 'we' was questionable for me.

However. If someone could **provide** and **maintain** a Mediawiki-site i'd highly appreciate it.

**Comment by dcohenb** [comment]
@AnHardt do you know who's managing the domain?

**Comment by AnHardt** [comment]
The domain was, as far as i know, provided by @scotty1024. But up to now he has not reacted to any recent requests here. Sadly we have no mail-address.
As far as i know @thinkyhead and @boelle have had shell accounts. As long as the web-server is running they could set a redirection - hopefully.

**Comment by mkubik** [comment]
Still no progress? 
In the meantime, can anyone make the docs available somewhere else?

**Comment by KiteLab** [comment]
https://github.com/MarlinFirmware/Marlin/wiki
is what we have.

**Comment by thinkyhead** [comment]
Gone forever, as I cannot connect by SFTP even to implement a redirect. The server does not respond to ping. Just use the wiki here on Github to work on the documentation. Make it awesome, maybe it can become the basis of the official Marlin for Dummies book....
