### ISSUE TITLE
TMC5160 Stepper motors are noisy/vibrate at low speeds when StealthChop is activeBUG] (bug summary)

### ISSUE THREAD

**Issue by fjulian79** [MarlinFirmware/Marlin#27403]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

This is a known issue, first reported here: #23248 This Tickets has then be closed automatically and reopened because of #26028. But then closed automatically once again.

I have discovered the issue after upgrading my good old Uiltimaker Original with a brand new BTT SKR 3 EZ Board along with TMC5160 Pro drivers. The Printer is now quite noisy, previously I have used the UMO Main board with TMC2208 and the printer was very silent. 

I use version 2.1.2.4 and maintain my code here: https://github.com/fjulian79/Marlin/tree/2.1.2.4-julian-umo 
I created my own branch to keep track of my config changes. Be warned, I had some kind of learning curve so somethings have had to be changed twice.

I thought sharing the link to my fork might be even better than providing a zip file with my configuration .. how ever, if the zip file is preferred I can provide it.

Anyway, I suggest to reopen #23248 and continue there. 

### Version of Marlin Firmware

2.1.2.4

### Printer model

Customized Ultimaker Original

### Electronics

BTT SKR 3 EZ

### LCD/Controller

BTT TFT35 3.0

### Other add-ons

Heated Bed

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
https://github.com/MarlinFirmware/Marlin/issues/23248 has been reopened.
