### ISSUE TITLE
[BUG] Fixed-Time Motion linear advance values far too small to set in menu

### ISSUE THREAD

**Issue by CarVac** [MarlinFirmware/Marlin#27414]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

My Ender 3 with Micro-Swiss NG extruder seems to need a linear advance parameter of 0.00015, and in the menu this appears as 0.00.

Setting the menu to its minimum value, 0.01, is a frankly extreme amount of linear advance and the extruder motor goes crazy with all the advancing and retracting.

This makes it impossible to set without connecting over serial and sending the command directly.

The serial readout also doesn't have enough precision to show the setting, it only shows 0.00 as well.

```
Linear Advance enabled.
Fixed-Time Motion enabled with X axis ZVD shaping and with Y axis ZVD shaping.
Dynamic Frequency Mode disabled.
X static shaper frequency: 29.85Hz
Y static shaper frequency: 29.85 Hz
Linear Advance enabled. Gain: 0.00
ok
```

### Bug Timeline

I don't know how old the bug is. I updated Marlin for the first time and tried fixed-time motion and discovered this bug.

### Expected behavior

I expected a reasonable PA value of 0.1 or so in the menu.

### Actual behavior

The proper value is invisible in the menu, and the smallest nonzero menu value is very bad.

### Steps to Reproduce

Configure Marlin to have Fixed-Time Motion

Attempt to set PA to 0.01 in the menu

Try to print.

The extruder will go crazy.

### Version of Marlin Firmware

2.1.x bugfix, commit b94a0d036c843b59488a4de77c1de8cf6e9e5863

### Printer model

Creality Ender-3 Pro

### Electronics

BigTreeTech SKR-Mini E3 V2.0

### LCD/Controller

Ender 3 Pro LCD, dunno what model it is

### Other add-ons

Micro-Swiss NG direct drive extruder

### Bed Leveling

None

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/user-attachments/files/16939484/Configuration.zip)

It seems to be the same problem as this issue: https://github.com/MarlinFirmware/Marlin/issues/26642, which was supposedly resolved, but it didn't work for me.

**Comment by narno2202** [comment]
The fix was in PR #26785, but it has been removed when the new FT_MOTION code was merged. If you set the value with M493, it should be OK. I will make a new PR.
