### ISSUE TITLE
babystepping inverted

### ISSUE THREAD

**Issue by 3machine** [MarlinFirmware/Marlin#2742]
hello,
after setting BABYSTEP_INVERT_Z true the babystepping behaviour changed : i have to turn counter clockwise to babystep Z up, and clockwise to babystep Z down.

**Comment by AnHardt** [comment]
In the newer branches `BABYSTEP_INVERT_Z` is not evaluated at all.

Maybe can be integrated in https://github.com/MarlinFirmware/MarlinDev/pull/250

```
      babystepsTodo[axis] += BABYSTEP_MULTIPLICATOR * (int)encoderPosition * (BABYSTEP_INVERT_Z && axis == Z_AXIS) ? -1, 1;
```

**Comment by AnHardt** [comment]
Use `BABYSTEP_MULTIPLICATOR` with a negative value instead.
