### ISSUE TITLE
[BUG] Axes’ movement cannot be inverted

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#27427]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

While using the Marlin 2.1.x bugfix, I’m encountering an issue where the axes can be inverted in code, but don’t actually reverse the motor’s movement. I’ve also tried it in the 2.1.2.4 release, but there, it seems to be bugged and is giving an error telling me to also invert all the other motors. The error is something like: **'INVERT_Z_DIR' was not declared in this scope; did you mean 'INVERT_X_DIR'** and so on. Flipping the connectors is not an option, because I’ve already had to, in order to get the Z homing working correctly. Since I’m using the probe to home the Z axis, and Marlin doesn’t allow me to invert the Z homing direction with the probe.

### Bug Timeline

On my first time using Marlin, in the 2.1.2.4 release and the 2.1.x bugfix

### Expected behavior

Invert the motor's movement

### Actual behavior

Didn't invert, or Marlin couldn't build

### Steps to Reproduce

1. Open the 2.1.2.4 code in VS Code 2. Comment out any of the three default axes #define **INVERT_**(axis)**_DIR** command 3. Attempt to build Marlin

### Version of Marlin Firmware

Marlin 2.1.2.4 and 2.1.x bugfix

### Printer model

Creality Ender 5 Plus

### Electronics

BigTreeTech SKR Mini E3 V3.0 (STM32 ARM Cortex-M0+)

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

![image_2024-09-20_161146960](https://github.com/user-attachments/assets/9ec1b942-9098-4752-bff2-ac26477c9b43)
[2.1.2.4 configurations.zip](https://github.com/user-attachments/files/17076478/2.1.2.4.configurations.zip)

**Comment by ellensp** [comment]
YOU CANNOT DO THIS  "//#define INVERT_Z_DIR false"

You have a Z axis, you must have this line

Either as `#define INVERT_Z_DIR false`
Or as `#define INVERT_Z_DIR true`

But NEVER `//#define INVERT_Z_DIR false` or `//#define INVERT_Z_DIR true` while you have a Z axis.

Same with X and Y
