### ISSUE TITLE
[BUG] Assisted Tramming comment copy/paste error

### ISSUE THREAD

**Issue by SparkyDan555** [MarlinFirmware/Marlin#27435]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

There is an error in the comments for Assisted Tramming in configuration_adv.h:

```
  /**
   * Screw Thread. Use one of the following defines:
   *
   *   M3_CW = M3 Clockwise, M3_CCW = M3 Counter-Clockwise
   *   M4_CW = M3 Clockwise, M4_CCW = M4 Counter-Clockwise
   *   M5_CW = M3 Clockwise, M5_CCW = M5 Counter-Clockwise
   *
   * :{'M3_CW':'M3 Clockwise','M3_CCW':'M3 Counter-Clockwise','M4_CW':'M4 Clockwise','M4_CCW':'M4 Counter-Clockwise','M5_CW':'M5 Clockwise','M5_CCW':'M5 Counter-Clockwise'}
   */
  #define TRAMMING_SCREW_THREAD M3_CW
```

Should be:
```
  /**
   * Screw Thread. Use one of the following defines:
   *
   *   M3_CW = M3 Clockwise, M3_CCW = M3 Counter-Clockwise
   *   M4_CW = M4 Clockwise, M4_CCW = M4 Counter-Clockwise
   *   M5_CW = M5 Clockwise, M5_CCW = M5 Counter-Clockwise
   *
   * :{'M3_CW':'M3 Clockwise','M3_CCW':'M3 Counter-Clockwise','M4_CW':'M4 Clockwise','M4_CCW':'M4 Counter-Clockwise','M5_CW':'M5 Clockwise','M5_CCW':'M5 Counter-Clockwise'}
   */
  #define TRAMMING_SCREW_THREAD M3_CW
```

### Version of Marlin Firmware

bugfix-2.1.x

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
Yip, added two weeks ago...  https://github.com/MarlinFirmware/Marlin/commit/45b9680c57f36fc7cab1ccfacf3ab5eb63097242#diff-0ba6096ec7be85bace98f94d0f02fcc44f3238a9291434a59c695241839c0ba1

**Comment by ellensp** [comment]
A PR has been added to correct this, closing.
