### ISSUE TITLE
Homing failed Printer Halted due to delta height plus probe offset

### ISSUE THREAD

**Issue by how-eee** [MarlinFirmware/Marlin#27431]
Homing failed Printer Halted due to delta height plus probe offset.
Homing movement exceeds delta height.

Probe offset = -15mm
G33 calculated delta heiht  = 285mm
So full Z travel 300mm. Printer halted at ~290mm of homing.

Should I manually set Probe offset = 0mm, delta heiht  = 300mm, homing OK

[Configs.zip](https://github.com/user-attachments/files/17084409/Configs.zip)

### Version of Marlin Firmware

2.1.2.4

### Printer model

kossel delta

### Electronics

skr 1.3

### LCD/Controller

discount 

### Bed Leveling

No Bed Leveling

### Your Slicer

None

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
> ### Did you test the latest `bugfix-2.1.x` code?
> 
> No, but I will test it now!

Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by how-eee** [comment]
> > ### Did you test the latest `bugfix-2.1.x` code?
> > No, but I will test it now!
> 
> Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

I cant compile firmware bin with my config. Configuration.h becomes blank

**Comment by thisiskeithb** [comment]
> Configuration.h becomes blank

Which operating system & version are you running?

Can you post your compile log?

**Comment by how-eee** [comment]
I was forced to take config files from bugfix folder and made all again. Waiste1 hour. But I found new bug there.

  //#define SHOW_TEMPERATURE_BELOW_ZERO
An error occured if uncomment that.

**Comment by how-eee** [comment]
OK. Thank you to show me reason why should I use bugfix branch instead of release one.

NOW
Probe offset = -15mm
G33 calculated delta heiht = 285mm
So full Z travel 300mm. Printer NOT halted. Homed correctly.

Issue solved!
Thanks again.

**Comment by thisiskeithb** [comment]
> Issue solved!
> Thanks again.

Great!
