### ISSUE TITLE
[BUG] TJC display issues on Ender 3 V2 Neo

### ISSUE THREAD

**Issue by albka1986** [MarlinFirmware/Marlin#27446]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After flashing the version bugfix 2.1 Marlin firmware to my Ender 3 V2 Neo, the screen became corrupted (see attached photo). The UI elements are distorted, with unreadable text and misaligned graphics. The issue occurred immediately after the firmware update. No specific files for the display were included in the firmware package I used, so I suspect this could be related to a missing or incorrect screen firmware configuration. 
![image](https://github.com/user-attachments/assets/eb96873b-d944-4aa1-a052-978aec91a444)

Attached also photo of display: 
![image](https://github.com/user-attachments/assets/8033f9ef-7276-40e5-9648-29d9bc52dd3f)

### Steps to Reproduce

Steps to reproduce:

Download the latest Marlin firmware "bugfix 2.1" for Ender 3 V2 Neo.
Flash the firmware to the printer.
Reboot the printer and observe the display.

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Ender-3 V2 Neo

### Electronics

board 4.2.2

### LCD/Controller

TJC (TJC4827x243 011 po4): not sensor, with button  (attached photo)

### Bed Leveling

None

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/user-attachments/files/17179085/Marlin.zip)

**Comment by thisiskeithb** [comment]
Give the Ender-3 V2 LCD firmware a try. Full instructions are in the README: https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3%20V2

> [!NOTE]  
> The TJC display variant is undocumented and incompatible with custom UIs.

**Comment by albka1986** [comment]
@thisiskeithb.
When I upload the 2 folders to the mSD card, the display does not update. Nothing happens. The firmware is not updated.
![image](https://github.com/user-attachments/assets/4c15366d-2ed9-42ac-8416-2c90d1435abd)

**Comment by ellensp** [comment]
TJC display (ie what you have) uses TJC_SET/tjc.tft. We cannot generate those files, so there is no screen updates for this display provided by Marlin.

**Comment by thisiskeithb** [comment]
> TJC display (ie what you have) uses TJC_SET/tjc.tft. We cannot generate those files, so there is no screen updates for this display provided by Marlin.

Ahh. I interpreted the "Currently incompatible with custom UIs" / "there are currently no custom display firmwares for this unit" wording & green check that `DWIN_CREALITY_LCD` was the only supported UI, but that doesn't seem to be the case.

<img width="626" alt="image" src="https://github.com/user-attachments/assets/0c1f77e5-9969-4380-a406-4b503a76fa1d">

I'll update the README to clarify that TJC displays are unsupported and users will have to go headless or swap in a supported display.

**Comment by thisiskeithb** [comment]
TJC display support has been clarified in https://github.com/MarlinFirmware/Configurations/pull/1105

`DWIN_MARLINUI_PORTRAIT` would be your best bet if you want to use a TJC display, but we have no way to compile/add graphic assets for them.

**Comment by albka1986** [comment]
I updated the line, but still see the issue with displaying icons:
![image](https://github.com/user-attachments/assets/0b83a34b-96db-4b3f-9d68-ae28187055c4)
![image](https://github.com/user-attachments/assets/638732aa-e34e-4d90-823a-46118502748b)
