### ISSUE TITLE
Integrating MKS SERVO42C NEMA17 Closed Loop Stepper Motor Driver in SKR 3 board

### ISSUE THREAD

**Issue by TheAlisiani94** [MarlinFirmware/Marlin#27463]
### Is your feature request related to a problem? Please describe.

I want to connect MKS SERVO42C NEMA17 Closed Loop Stepper Motor Driver to an SKR 3 board. Is the "MKS SERVO42C NEMA17 Closed Loop Stepper Motor Driver" Compatible with SKR 3? If so, what stepper driver does the closed-loop stepper include for firmware integration? 

### Are you looking for hardware support?

I want to use this configuration for Ender 3, Lulzbot, and Prusa printers.

### Describe the feature you want

I want to know how to make this adjustment on SKR 3 firmware so that I can replace the current drive I have with the desired MKS SERVO42C NEMA17 Closed Loop Stepper Motor Driver

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.com/servers/marlin-firmware-461605380783472640) Discord server
