### ISSUE TITLE
[BUG] (bug summary)Try to compile the latest bugfix-2.1.x version of the firmware in the BigTreeTech Manta M8P V2.1 (STM32H723ZE) environment, but the operation failed.

### ISSUE THREAD

**Issue by mayjack0312** [MarlinFirmware/Marlin#27498]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I tried both PIO and Auto Build Marlin for the compilation, but both reported the same error.
<img width="1280" alt="1140431e767a9077cdac4c72363b0f1" src="https://github.com/user-attachments/assets/b8d3f7d6-ac19-4170-a68b-2681d85abc15">

<img width="1280" alt="d8cc8a86fb95303ff89c4d034ad00f8" src="https://github.com/user-attachments/assets/fa4202bc-4fc1-4213-ac7f-76ddc51d79a6">

[error_log.log](https://github.com/user-attachments/files/17531736/error_log.log)

### Version of Marlin Firmware

bugfix-2.1.x

### Electronics

BigTreeTech Manta M8P V2.1 (STM32H723ZE)

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
