### ISSUE TITLE
[FR] (feature summary) Support for urboot on AVRs

### ISSUE THREAD

**Issue by Laikulo** [MarlinFirmware/Marlin#27506]
### Describe the feature you want

PIO environments for urboot for at least melzi, and a bump to the version of avrdude specified (to one that support urclock protocol)

### Additional context

In the quest to cram too many features on a creality melzi board, urboot saves 256b over optiboot, and 1.75k over the stock arduino (sanguino) configuration.

**Comment by ellensp** [comment]
URBOOT uses minimal 256 bytes, max 512 bytes. 

But the smallest boot section you can define with the 1284p micro controller fuses bits is 512 words, ie 1K bytes

So there is zero benefit to use this bootloader, you cannot use the 'saved' space as it is locked out by the fuse bits.


![Screenshot from 2024-10-31 16-51-46](https://github.com/user-attachments/assets/676908bb-07d3-4873-8a1a-da7baf69eed7)


Ie the bootloader uses 1K, 2K, 4k, or 8K

**Comment by ellensp** [comment]
the atmega2560 is the same

![Screenshot from 2024-10-31 18-24-39](https://github.com/user-attachments/assets/b49c07aa-df03-4e63-b394-796eb29edf89)
