### ISSUE TITLE
[FR] double Y axes, with one driver

### ISSUE THREAD

**Issue by Amal1321** [MarlinFirmware/Marlin#27514]
### Describe the feature you want

Hello,
I need help with mu configuration.
I have a 3dprinter with a 2 Y stepper motors driven with same driver TB6600, and I located and Endstop for each of the axes.
I got confused with the modifications I have to do in the code
I do not have Y2 driver type, and in order to define multiple endstops there is a condition that there should be a Y2 driver type
any ideas?

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
you cannot have independent endstops without a driver each,  
Q: how would one Y keep moving to get home when the other Y has stopped at home?
A: It can not
