### ISSUE TITLE
[FR] ESP32-S2 SUPPORT

### ISSUE THREAD

**Issue by theahadev** [MarlinFirmware/Marlin#27512]
### Is your feature request related to a problem? Please describe.

I want to compile Marlin for ESP32-S2 Mini board, but it seems like marlin doesn't officially supports it.

### Are you looking for hardware support?

ESP32-S2 Mini

### Describe the feature you want

ESP32-S2 Mini support.

### Additional context

I searched the web for ESP32-S2 support on Marlin, and i only found an [open issue](https://github.com/MarlinFirmware/Marlin/issues/23507) on it, with no updates. I already wrote the pins file for the ESP32-S2, and [someone on the other issue](https://github.com/MarlinFirmware/Marlin/issues/23507#issuecomment-1022979050) already started writing a HAL for it.

**Comment by ellensp** [comment]
Please don't open up duplicate feature requests.

**Comment by itsyumiki** [comment]
Sorry, i saw the other issue was inactive, so i thought i have to open a new issue.
