### ISSUE TITLE
[BUG] Spaces in path breaks Windows & macOS builds

### ISSUE THREAD

**Issue by Crazy-Charles** [MarlinFirmware/Marlin#27526]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Build does not complete

### Bug Timeline

After changes to generic_create_variant.py in commit #27502

### Expected behavior

Linker to finish and produce a bin file

### Actual behavior

Compiles fine but fails on linker with....
```
arm-none-eabi-g++: error: D:/Github: No such file or directory
arm-none-eabi-g++: error: Repositories/Marlin/buildroot/share/PlatformIO/variants/MARLIN_F103Rx/ldscript.ld: No such file or directory
*** [.pio\build\STM32F103RE_creality\firmware.elf] Error 1
```

First error is correct as my path is actually D:\Github Repositories\

### Steps to Reproduce

Download current bugfix
Use the Ender 3 V2 config files (no changes made)
Build

### Version of Marlin Firmware

Bugfix 2.1.x

### Printer model

Ender 3 V2

### Electronics

Creality 4.2.7

### LCD/Controller

Dwin

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Config files from https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x with no changes made

If i comment out the last line of generic_create_variant.py it will complete the build.

`board.update("build.variants_dir", "buildroot/share/PlatformIO/variants");`

**Comment by thisiskeithb** [comment]
Can you try replacing `generic_create_variant.py` with the one from this zip? [generic_create_variant.py.zip](https://github.com/user-attachments/files/17692359/generic_create_variant.py.zip)

These are the changes I made:
```diff
diff --git a/buildroot/share/PlatformIO/scripts/generic_create_variant.py b/buildroot/share/PlatformIO/scripts/generic_create_variant.py
index 60c36c7..39f97b7 100644
--- a/buildroot/share/PlatformIO/scripts/generic_create_variant.py
+++ b/buildroot/share/PlatformIO/scripts/generic_create_variant.py
@@ -5,7 +5,7 @@
 # the appropriate framework variants folder, so that its contents
 # will be picked up by PlatformIO just like any other variant.
 #
-import pioutil, re
+import pioutil, re, os
 marlin_variant_pattern = re.compile("marlin_.*")
 if pioutil.is_pio_build():
     import shutil, marlin
@@ -51,6 +51,6 @@ if pioutil.is_pio_build():
 
     # Make sure the local variant sub-folder exists
     if marlin_variant_pattern.match(str(variant).lower()):
-        source_dir = Path("buildroot/share/PlatformIO/variants", variant)
+        source_dir = Path(os.path.join("buildroot", "share", "PlatformIO", "variants", variant))
         assert source_dir.is_dir()
-        board.update("build.variants_dir", "buildroot/share/PlatformIO/variants");
+        board.update("build.variants_dir", os.path.join("buildroot", "share", "PlatformIO", "variants"))
```

**Comment by Crazy-Charles** [comment]
Still getting the same error ,the first line of the error message D:/Github is a truncated path name as it is actually...
"D:/Github Repositories"

**Comment by thisiskeithb** [comment]
Which OS and specific version are you running?

**Comment by Crazy-Charles** [comment]
Windows 11 Pro 23H2 build 22631.4391

It would seem that the script doesn't like the space in the folder name, if i remove it then the build completes but this would cause a great inconvenience as that structure has been fine for the last few years!

**Comment by Crazy-Charles** [comment]
@thisiskeithb 
If i change your script at the end to 
```
current_working_directory = Path.cwd()
board.update("build.variants_dir", current_working_directory / os.path.join("buildroot", "share", "PlatformIO", "variants"))
```

The build completes ok for me but don't know of any ramifications this might cause.

**Comment by thisiskeithb** [comment]
I can confirm that spaces in the build path break on Windows 10 & 11 22H2 as well.

**Comment by Crazy-Charles** [comment]
Thanks for your help 
On the #27502 script changing the last line to 
`board.update("build.variants_dir", Path.cwd() / "buildroot/share/PlatformIO/variants")`
will stop the build failure and produce a working bin file

**Comment by fnsign** [comment]
The same bug occurs also on macOS (Sequoia 15.1)

**Comment by thisiskeithb** [comment]
> The same bug occurs also on macOS (Sequoia 15.1)

Interesting. I can't reproduce it on Sonoma.

**Comment by rondlh** [comment]
I have the same issue (Win 10), the problem started from a very recent update

**Comment by thinkyhead** [comment]
It looks like the problem / solution relates to having a full path to the current folder. Is that all that is needed?

**Comment by thinkyhead** [comment]
If the above (merged) PR fixes the issue then we can close this. If it is still a problem we can apply some more patches. I think it's already better than it was, either way.

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by fnsign** [comment]
On macOS (Sequoia 15.1) it is fixed. Thanks!

**Comment by Crazy-Charles** [comment]
Has fixed my issue on Win 11 too
