### ISSUE TITLE
[BUG] `HOST_KEEPALIVE_FEATURE` makes Octoprint plugin for editing the EEPROM not work

### ISSUE THREAD

**Issue by classicrocker883** [MarlinFirmware/Marlin#27536]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Taken from this issue here https://github.com/classicrocker883/MRiscoCProUI/issues/168

It is hard to say whether or not this is a Marlin or [cp2004/OctoPrint-EEPROM-Marlin](https://github.com/cp2004/OctoPrint-EEPROM-Marlin) issue.

I will try to provide more info, if someone can replicate/reproduce this issue and maybe look through the source code to see if anything stands out which may cause this

### Bug Timeline

Probably old. Notice only with `HOST_KEEPALIVE_FEATURE`

### Expected behavior

Should connect and read/write normally

### Actual behavior

The M503 command in the Octoprint terminal did not seem to return any useful data 
With `HOST_KEEPALIVE_FEATURE` *disabled*, everything works normally | as it should 

### Steps to Reproduce

1. Enable `HOST_KEEPALIVE_FEATURE`
2. Get [Octoprint](https://github.com/OctoPrint/OctoPrint)
3. Get [Marlin EEPROM Editor](https://plugins.octoprint.org/plugins/eeprom_marlin/)
4. Try connecting. `M503` in terminal

### Version of Marlin Firmware

2.1.x-bugfix

### Other add-ons

Octoprint

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[UBLconfigs.zip](https://github.com/user-attachments/files/17827336/UBLconfigs.zip)

**Comment by Crazy-Charles** [comment]
No issues seen here, using Octoprint 1.10.3 and Eeprom Editor 3.3.0 with HOST_KEEPALIVE_FEATURE enabled but i will say i'm not fully up to date with commits (probably 2 weeks behind).

**Comment by thisiskeithb** [comment]
From your linked issue:

> Recv: echo:Unknown command: "M503"

`M503` needs to be enabled for that plugin to work.

**Comment by classicrocker883** [comment]
__

> From your linked issue:
> 
> > Recv: echo:Unknown command: "M503"
> 
> `M503` needs to be enabled for that plugin to work.

this shouldnt be closed just yet

`M503` IS enabled for each test firmware

**Comment by classicrocker883** [comment]
I'm actually a bit confused by this.
`M503` is there for each firmware tested.
the main and sometimes *only* differences are having `HOST_KEEPALIVE_FEATURE` or not

`HOST_KEEPALIVE_FEATURE`: *Enabled*
>On Aquila_N32_UBL-ProUI-EX-11-03.bin version:
EEPROM read/write not working
M503 response:
`Recv: echo:Unknown command: "M503"`
---

`HOST_KEEPALIVE_FEATURE`: *Disabled*
>On Aquila_N32_UBL-ProUI-EX-11-20.bin version:
EEPROM read/write not working
M503 response:
`Recv: echo:Unknown command: "M503"`
---

There is basically no difference than the previous - except for a couple changes I made which may fix the issue while having:
`HOST_KEEPALIVE_FEATURE`: *Enabled*
>On the Aquila_N32_UBL-ProUI-EX-11-20-Test6.bin version:
EEPROM read/write working
M503 response:
`Recv: echo:; Linear Units:` + ect... (a normal `M503` response`)

**Comment by ellensp** [comment]
for marlin to respond with Unknown command, the gcode must be disabled

3 ways it can get disabled 

//#define EEPROM_SETTINGS     // ie the eeprom is not enabled at all
#define DISABLE_M503               // ie M503  is deliberately disabled 
#define MARLIN_SMALL_BUILD // this will also enable DISABLE_M503

**Comment by classicrocker883** [comment]
> for marlin to respond with Unknown command, the gcode must be disabled
> 
> 3 ways it can get disabled
> 
> //#define EEPROM_SETTINGS // ie the eeprom is not enabled at all #define DISABLE_M503 // ie M503 is deliberately disabled #define MARLIN_SMALL_BUILD // this will also enable DISABLE_M503

you can take a look through the Config files, none of those options were like that - has EEPROM_SETTINGS and M503 was not disabled, and no MARLIN_SMALL_BUILD

**Comment by Crazy-Charles** [comment]
Just tried it on the latest up to date bugfix, compiled for a Creality 427 board with DWIN_CREALITY_LCD and  DWIN_LCD_PROUI and no issues at all with M503.


Update: Just tried your repo build with HOST_KEEPALIVE_FEATURE enabled on the same 427 board and that is ok as well.
