### ISSUE TITLE
[BUG] SWP ANET A^ MAIN BOARD

### ISSUE THREAD

**Issue by wandiligong** [MarlinFirmware/Marlin#27546]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Not sure this is correct area to ask a Q but site is complicated

I have a AnetA6 printer.  V1.5 Use Cura 14.07  Just use SD card - not connected to PC
SD card socket malfunctioned
Replaced the board with Anet E12 board V1.7 Now autohome moves bed forward (Y axis) beyond its available travel and then slips belt on motor

### Bug Timeline

Related to replacing board

### Expected behavior

I expected bed to move rearward against limit switch and stop

### Actual behavior

Expected autohome to behave same as with V1.5 board

Bed moves forward and exceeds physical limit of travel - then slips belt on motor cog

### Steps to Reproduce

Select autohome

### Version of Marlin Firmware

Not sure if Marlin involved??

### Printer model

Anet A6

### Electronics

Replaced bord with Anet E12 V 1.7

### LCD/Controller

?

### Other add-ons

None

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Uploading Elbow stop #4 LPt2 F29 Spt evy dfeb2aa5-c7ce-4401-a15b-e5b3f4117405.zip…]()

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.com/servers/marlin-firmware-461605380783472640) Discord server
