### ISSUE TITLE
[FR] How do I transfer Z2 to E1 pin for Two Trees Bluer V2?

### ISSUE THREAD

**Issue by XzReaN** [MarlinFirmware/Marlin#27541]
### Is your feature request related to a problem? Please describe.

Yes, Dual Z has the problem of the X axis being crooked.

### Are you looking for hardware support?

I have solved the hardware requirements

### Describe the feature you want

I have 2 stepper motors and 2 motor drivers. I want to connect them to the Z shaft separately. For this reason, I want to transfer Z2 to E1 pin. I would like your support in this regard. I am using the latest marlin version.

**Comment by XzReaN** [comment]
I want to make it similar to the Two Trees Sapphire Pro Z system.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by ellensp** [comment]
you simply enable #define Z2_DRIVER_TYPE A4988 with your driver type
Marlin will automatically use the first unused E stepper pins as Z2 pins

**Comment by XzReaN** [comment]
Thank you very much, I am very grateful to you.
