### ISSUE TITLE
[BUG] (MAX31865 for bed behaviour in Marlin 2.1.2.5)

### ISSUE THREAD

**Issue by anvoice** [MarlinFirmware/Marlin#27564]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

The Marlin 2.1.2.5 Configuration.h comments claim that a bed 2.1.2.5 max31865 sensor can be used, but there are no variables to be set in Configuration.h pertaining to the bed max31865 sensor, only sensors 0, 1, and 2. Enabling a max for the bed via `#define TEMP_SENSOR_BED -5` leads to a slew of compile errors. In an attempt to remedy this I delved deeper into the code, where support for the max on the bed is indeed evident, for example in temperature.cpp. I am currently trying to fix all the errors that appear by deeper modification of the files, for example Conditionals_adv.h in Marlin/src/inc, but not sure if I'll succeed. I'm quite new to coding, but I'd be happy to provide details of what I did already, if someone lets me know how.

### Bug Timeline

If indeed a bug, probably existed from the beginning but was not observed because nobody uses the max31865 for the bed.

### Expected behavior

Expected is the ability to use a max31865 sensor for the bed, either directly through Configuration.h or by more advanced code modification.

### Actual behavior

Cannot add max31865 to bed without breaking everything.

### Steps to Reproduce

1. Download Marlin 2.1.2.5
2. Use #define TEMP_SENSOR_BED -5 in Configuration.h
3. Compile errors
[Configuration.zip](https://github.com/user-attachments/files/17989961/Configuration.zip)

### Version of Marlin Firmware

2.1.2.5

### Printer model

Fully custom cartesian

### Electronics

MKS Tinybee mainboard

### LCD/Controller

MKS TFT24, not controlled by Marlin AFAIK

### Other add-ons

BTT MAX31865 stepstick module

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I made quite a few changes and am not sure how best to describe all of them. These include other custom code to get the MKS TFT24 working on the MKS Tinybee mainboard among other things. If someone lets me know how best to submit the changes I made I will do that.

**Comment by ellensp** [comment]
closing as user has multiple issues for the same thing https://github.com/MarlinFirmware/Marlin/issues/27610
