### ISSUE TITLE
[FR] Add suport for Arduino GIGA R1

### ISSUE THREAD

**Issue by G3Dmaker** [MarlinFirmware/Marlin#27568]
### Is your feature request related to a problem? Please describe.

No. Just one question.

### Are you looking for hardware support?

I would like to speed up my Due RADDS board. Or also other Due based Boards. 

### Describe the feature you want

It seems that the Arduino Board GIGA R1 have the same Pinout like an Arduino DUE.
Is it possible?

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by G3Dmaker** [comment]
OK. Then you can delete this page.
`https://marlinfw.org/docs/development/feature_request.html`
