### ISSUE TITLE
[BUG] Eryone Thinker V2 - Rambo Pin: Z2 is missing

### ISSUE THREAD

**Issue by sonny1985** [MarlinFirmware/Marlin#27599]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

**Hello :)

As far as i use the Marlin Firmware in its Original State and Something dont work as it should, i open this Bug-Report.
(included BL Touch and Filament Runout sensor)

I have a Eryone Thinker V2 (!)- With 2 Z Steppers....
I try to define the Z2 (uncomment it) to tell the FW that 2 Steppers are there, so i can use the G34 Command To align the gauntry.
#define Z2_DRIVER_TYPE A4988 (What is the Same like E, Y, X and Z1)
I looked also at the Config_advanced(#define Z_STEPPER_AUTO_ALIGN
), all good there - when i Compile it , i get following Errors/Warnings:**

Marlin\src\inc\Warnings.cpp:206:6: warning: #warning "Note: Auto-assigned Z2_MS1_PIN to an unused En_MS1_PIN. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)" [-Wcpp]
     #warning "Note: Auto-assigned Z2_MS1_PIN to an unused En_MS1_PIN. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)"

Marlin\src\inc\Warnings.cpp:209:6: warning: #warning "Note: Auto-assigned Z2_MS1_PIN to an unused En_MS1_PIN. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)" [-Wcpp]
     #warning "Note: Auto-assigned Z2_MS1_PIN to an unused En_MS1_PIN. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)"

Marlin\src\inc\Warnings.cpp:212:6: warning: #warning "Note: Auto-assigned Z2_MS1_PIN to an unused En_MS1_PIN. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)" [-Wcpp]
     #warning "Note: Auto-assigned Z2_MS1_PIN to an unused En_MS1_PIN. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)"

**It is a Serious Warning,the FW get compiled, when i upload it to the Printer and try to use the G34 Command: It cant move the Z2 Stepper, it looks like in the Pins File (Rambo/Pins_Rambo_ThinkerV2) The Pin for the Z2 is "not defined"

I dont know the Pin Number, what i definetly can say: I have 2 separated Z Steppers Connected on the Board (Z1 and Z2).

Can somebody help me out :) .
Greetings**

**// EDIT: I disassembled the Board again, and found out that Z1 and Z2 share the same Driver Board.
I have one Connector and a empty Slot for a Driverboard left called: E1. May it be possible to Connect the Z2 Stepper there ? and install its required Stepper Module (i would choose the same as the other ones)- But for that i need also the Pins for the E1 Port , which are also missing...**

### Expected behavior

Pin Number is Missing !

### Actual behavior

Z2 Axis dont work.

### Version of Marlin Firmware

2.1.2.5

### Printer model

Eryone Thinker V2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
> #warning "Note: Auto-assigned Z2_

These warnings are to tell you that Marlin auto-assigned the unused E1 slot to Z2.

> EDIT: I disassembled the Board again, and found out that Z1 and Z2 share the same Driver Board.
I have one Connector and a empty Slot for a Driverboard left called: E1. May it be possible to Connect the Z2 Stepper there ? and install its required Stepper Module (i would choose the same as the other ones)- But for that i need also the Pins for the E1 Port , which are also missing...

You will need to install another driver in E1 and then move the second Z wiring over to it. Like I mentioned above, Marlin will auto-map the unused E1 driver to Z2 if Z2 is enabled.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.com/servers/marlin-firmware-461605380783472640) Discord server

**Comment by sonny1985** [comment]
Hi, Wow, thanks for your quick response. i will try that out tomorrow. :) I put in E1 a 2208 in, and the Z2 Axis i connect to E1. I will report ofc if it worked :)
