### ISSUE TITLE
[BUG] Reference to non-existent g-code

### ISSUE THREAD

**Issue by rq3** [MarlinFirmware/Marlin#27591]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The babystepping section of configuration_adv.h says:

  //#define BABYSTEP_GLOBAL_Z               // Combine M424 Z and Babystepping

M424 refers to a non-existent g-code. It is a source of confusion and should be removed.

### Bug Timeline

Old

### Expected behavior

I expect configuration files in the release branch to not refer to non-existent functions.

### Actual behavior

Configuration_adv.h refers to M424, which does not exist.

### Steps to Reproduce

1) Search within configuration_adv.h for M424

### Version of Marlin Firmware

latest bugfix of Dec. 16, 2024

### Printer model

NA

### Electronics

NA

### LCD/Controller

NA

### Other add-ons

NA

### Bed Leveling

No Bed Leveling

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/user-attachments/files/18156597/Config.zip)

**Comment by thisiskeithb** [comment]
Configuration changes are added to the import & bugfix config branches for pending PRs, so this is expected.

Pending PR:

- https://github.com/MarlinFirmware/Marlin/pull/18987/
