### ISSUE TITLE
[BUG] BTT TFT35 E3 and MKS GEN L V1.0

### ISSUE THREAD

**Issue by BlackRiverCoder** [MarlinFirmware/Marlin#27606]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hello, I just got BTT TFT35 E3 V3.0.1 and wanted to use it, but I also have OctoPrint server connected to main board and this 2 cannot work together. I wanted to set SERIAL_PORT_2 for TFT display to communicate by TX and RX in AUX-1 port in MKS GEN L V1.0, but I get error when compiling: #error "Serial Port 1 pin D18 and/or D19 conflicts with another pin on the board.", which are pins for Z endstop. I tried PORT 1, 2, 3, but still same error, just another pin numbers. 

Is this wrong board pin configuration in Marlin?

Thanks
[configurations.zip](https://github.com/user-attachments/files/18247373/configurations.zip)

### Bug Timeline

When connected BTT TFT35

### Expected behavior

OoctoPrint to run on default -1 or 0 PORT (USB) and BTT TFT35 to use TX and RX (port 1, 2 or 3) , so they can work both. (set temp on display or in octoprint)

### Actual behavior

Can't do anything by OctoPrint, only by BTT TFT35

### Version of Marlin Firmware

2.1.2.5

### Printer model

KRYAL Cube

### Electronics

MKS GEN L V1.0

### LCD/Controller

BTT TFT35 E3 V3.0.1 (GD version)

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

None

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ellensp** [comment]
The uart pins on a atmega2560 are fixed ie you cannot move them to other pins
UART 0 on pins 0 (RX) and 1 (TX),
UART 1 on pins 19 (RX) and 18 (TX)
UART 2 on pins 17 (RX) and 16 (TX)
UART 3 on pins 15 (RX) and 14 (TX)
so to use those you need to disable what ever is currently using the required pins

UART 0 pins 0 and 1 are on aux-1, these are connected to the usb to serial chip for usb
UART 1 pins 18 and 19 by default are z-min and z-max, so you would need to move the endstops elsewhere.  
UART 2 pins 16 and 17 are on exp1, so conflict with the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
UART 3 pins 14 and 15 by default are y-min and y-max, so to use these you would need to move the endstops else where. 

-1 is not a valid option on this board  

This is not a bug, these errors are deliberate to stop you setting impossible settings
These are limitations of your default hardware setting

**Comment by ellensp** [comment]
In your Config you have

#define Y_HOME_DIR +1
#define Z_HOME_DIR -1

You can easily move your endstops to a new plug.

You want to use uart 1 

then physically move Z_MIN to Y_MIN plug and add the following to your Configuration.h 
```cpp
#define Z_MIN_PIN 14 // use Y_MIN plug
#define Y_MIN_PIN -1 // disabled
``` 

this will free up uart 1 and allow #define SERIAL_PORT_2 1

**Comment by ellensp** [comment]
you also have #define USE_ZMAX_PLUG
But what is plugged in there?  
If its not used, disable this define
If it is used, you need to move it to another pin.

**Comment by BlackRiverCoder** [comment]
Hi, many thanks, that works :)

Have a nice day
