### ISSUE TITLE
[BUG] (bug summary)Mising the "O" Option feature in G29

### ISSUE THREAD

**Issue by inspectionsbybob** [MarlinFirmware/Marlin#27609]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

In an earlier version of Marlin, the G29 command had an option that SKIPPED the generation of a new Matrix if a valid matrix was already Present.

My Code on that version was:
G29 O S1
M420 S1

It saved LOTS of time on subsequent prints 

### Bug Timeline

2023

### Expected behavior

I expected it to SKIP building a Matrix if one existed

### Actual behavior

Depending on the Version of Marlin it either skipped it with an error, or in more recent versions it just STOPPED and didn't process anything further.

### Steps to Reproduce

Use Pronterface and send the Above codes.

### Version of Marlin Firmware

2.0.2

### Printer model

Various

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

No ZIP file, as it is not something in Config.h that I know of....

**Comment by ellensp** [comment]
G29 is different for each type of bed leveling

https://marlinfw.org/docs/gcode/G029-abl-3point.html
https://marlinfw.org/docs/gcode/G029-abl-linear.html
https://marlinfw.org/docs/gcode/G029-mbl.html
https://marlinfw.org/docs/gcode/G029-abl-bilinear.html
https://marlinfw.org/docs/gcode/G029-ubl.html

Only 3point, linear and bilinear has the O option
