### ISSUE TITLE
[BUG] BLTOUCH_HS_MODE defaults to off

### ISSUE THREAD

**Issue by pmjdebruijn** [MarlinFirmware/Marlin#27607]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

With:

`Configuration_adv.h:  #define BLTOUCH_HS_MODE true`

A newly initialized printer, still defaults to having HS_MODE disabled by default.

Presumably this is related:
https://github.com/MarlinFirmware/Marlin/commit/f5c7b190f6169f0a213ef4b088e9c4b5ef33b2b8

### Bug Timeline

Not sure

### Expected behavior

`Configuration_adv.h:  #define BLTOUCH_HS_MODE true`

should result in HS_MODE being enabled by default

### Actual behavior

HS_MODE is disabled by default

### Steps to Reproduce

Reinitialize printer settings, check BLTouch HS Mode defaulting to off.

### Version of Marlin Firmware

2.1.2.5+1

### Printer model

Ender 3

### Electronics

SKR E3 RFF

### LCD/Controller

stock

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

```
Marlin/Configuration_adv.h:#if ENABLED(BLTOUCH)
Marlin/Configuration_adv.h:  //#define BLTOUCH_DELAY 500
Marlin/Configuration_adv.h:   * Settings for BLTOUCH Classic 1.2, 1.3 or BLTouch Smart 1.0, 2.0, 2.2, 3.0, 3.1, and most clones:
Marlin/Configuration_adv.h:  //#define BLTOUCH_FORCE_SW_MODE
Marlin/Configuration_adv.h:  #define BLTOUCH_SET_5V_MODE
Marlin/Configuration_adv.h:  //#define BLTOUCH_LCD_VOLTAGE_MENU
Marlin/Configuration_adv.h:  //#define BLTOUCH_FORCE_MODE_SET
Marlin/Configuration_adv.h:  #define BLTOUCH_HS_MODE true
Marlin/Configuration_adv.h:#endif // BLTOUCH
Marlin/Configuration.h:#define BLTOUCH
```

**Comment by ellensp** [comment]
being disabled is deliberate due to to the CRTOUCH which doesn't like it. 

see https://github.com/MarlinFirmware/Marlin/pull/22916
