### ISSUE TITLE
Problems in checkHitEndstops()

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#2762]
a. In the `checkHitEndstops()` (https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/stepper.cpp#L252) we don't throw any messages for max-end-stops.
b. For deltas the Z_MIN and Z_MIN_PROBE messages only show the state of the z-tower - what is basically meaningless.

c. If a hardware end-stop is hit we do basically nothing but throwing the message, except  `ABORT_ON_ENDSTOP_HIT_FEATURE_ENABLED` && `SDSUPPORT` and `abort_on_endstop_hit` is true.
I think we should stop the printer, or at least the move, if we hit a hardware end-stop before the software end-stops are established. That means before the machine is homed. That needs backing of from the hardware end-stops if they are triggered in the init phase.

**Comment by AnHardt** [comment]
To solve a) we could simply replace `BIT(X_MIN)` with `(BIT(X_MIN) | BIT(X_MAX))` for all 3 axes.

b) needs an extra DELTA case. Here we could print endstops_trigsteps[] for all 3 axis. For x and y they have to be calculated in `update_endstops()` in a extra DELTA case close to where `endstops_trigsteps[Z_AXIS]` is stored.

**Comment by Roxy-3D** [comment]
I think I agree with everything you said here.   In the case of Delta's, if we see an end stop get hit unexpectedly, don't we want to freeze the machine?

> I think we should stop the printer, or at least the move, if we hit a hardware end-stop before the software end-stops are established.

In the general case I think this makes sense.   I don't know that it makes sense to abort the move and continue on.  At that point, the print is ruined.   

I don't really care where we discuss this, and mostly I'm asking because I need help understanding...  But shouldn't this thread be over in MarlinDev?

**Comment by AnHardt** [comment]
Sorry for the partially false alarm.
Solution a. is crap. `update_endstops()` sets the MIN-flag regardless if it has detected a min- or max- endstop-hit.
solution b. is crap. Output of the "X:", "Y:", "Z:" for deltas would be the tower coordinates and mess up the host program with wrong information, because this will interpret the coordinates as cartesian coordinates.

This makes an other error obvious. On a delta we currently sent the tower coordinate of z when we hit the z-min-endstop.
If " Z_MIN_PROBE:" is also interpeted by Repetier (https://github.com/MarlinFirmware/Marlin/issues/2679#issuecomment-146378072) here it is the same.

I guess we should not do this outputs in `checkHitEndstops()` for deltas at all.

**Comment by Roxy-3D** [comment]
OK.    I'm wondering if there is an unintended consequence going on.    I've seen the location of the origin shift during the Z-Probes during the M48.    I don't have enough information yet to understand what is happening.   But I'm wondering the Z-Tower is getting its location set, and that is pushing the location over????

**Comment by AnHardt** [comment]
@Roxy-3DPrintBoard 
I have a rough idea where this behavior could come from. But it's not completely analysed yet, nor i have a fix. I already wrote something down at: https://github.com/MarlinFirmware/Marlin/issues/2722#issuecomment-154585216

**Comment by thinkyhead** [comment]
Any patch or proposed patch for this yet? Seems like it might be an important thing to fix.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
