### ISSUE TITLE
Clarification on how to enable endstops when the sensor probe and autoleveling are enabled

### ISSUE THREAD

**Issue by albertolg** [MarlinFirmware/Marlin#2765]
Forgive me buit I can't find how to have the endstops and the bed leveling working together. Right now to use the autolevel bed feature I need to uncomment the `ENDSTOPS_ONLY_FOR_HOMING` in the `Configuration_adv.h` file and I will lose all the endstops after the homing.

**Comment by AnHardt** [comment]
Despite the name `ENDSTOPS_ONLY_FOR_HOMING` this only switches the evaluation of the **hardware** endstops on and off. The **software** endstops are not switched off. There are some problems with the software endstops, especially with delta printers, but else they are supposed to work.

**Comment by albertolg** [comment]
yes, my fault, bad explanation, the software endstops keeps working, I was refering to the hardware switches, there is nothing to change to keep the hardware endstops enabled? I'm using the 1.1.0RC2 thanks

**Comment by AnHardt** [comment]
Sorry bad explanation.
Despite the name `ENDSTOPS_ONLY_FOR_HOMING` hardware endstops, as well as the probe,  work for probing, when `ENDSTOPS_ONLY_FOR_HOMING` is defined.

**Comment by thinkyhead** [comment]
> nothing to change to keep the hardware endstops enabled?

@albertolg Did you get this figured out? If you still need help please re-open this issue.
