### ISSUE TITLE
tune > temperature > nozzle doesn't work rc2 - RRD smart controller

### ISSUE THREAD

**Issue by cgapeart** [MarlinFirmware/Marlin#2770]
I am running an SD print, and wanted to adjust the temperature.  When I use the tune menu, temperature, and select nozzle, it moves to the adjustment screen, but lists flow instead of nozzle temperature, and I cannot make a change.

When I roll the wheel, the numbers change (and jump down to 10 most of the time) before I can set a meaningful value.  However, when I push down to set the value nothing happens.  The print continues, and eventually the menu times out and returns to the info screen with no change made to either the flow rate or the temperature.

I have tried this a few times, same results.  I can adjust other values on that menu - the actual flow rate entry works just fine.

I am happy to help with debug suggestions, and don't mind digging into the code, but I don't know where to start.  I will be out of town next week, so it may be a bit before I respond.

General details:
-Running rcbugfix downloaded approx november 10th
-Prusa i3 style, 1 extruder configured
-Some customizations made in the pin file to map fans around a bad FET.
-Servo z stop and grid probing enabled
-SD Support, eeprom, LCD support compiled in for the RRD Smart controller
-yes, I should probably go back to the release branch until the work is done on 1.1, but I just love how much cleaner and better organized the configuration.h file is.  I don't want to go back;). Plus, there are a bunch of tweaks in the z probing that seem to make it easier to deploy and retract the servo z probe without it crashing.

**Comment by thinkyhead** [comment]
Bugs in the Tuning menu should now be fixed in RC. Give it another try. Reopen this issue if the problem still exists.
