### ISSUE TITLE
Using something else instead of encoder?

### ISSUE THREAD

**Issue by schirrel** [MarlinFirmware/Marlin#2775]
I'm studying marlin a little bit and i'm wondering if anyone uses it without encoder and using arrows or joysticks.
I'm interest on making these modifications but i saw that there's a looooooooooooooot to modify since it's build up for encoder.
So i was thinking if anyone else has made this change or if it's not a useful thing.

**Comment by Roxy-3D** [comment]
I guess it depends on what you mean by 'encoder'.  Marlin does use endstops to know where the limits are.  But other positioning is done by stepping the motors the correct amount.  There is not an encoder to read the position of the various axis.

**Comment by ntoff** [comment]
I assume he/she means the rotary encoder you navigate the menu with.

**Comment by schirrel** [comment]
Hi, yeah i meant rotary encoder for menu navigation
SOrry  xD

**Comment by KiteLab** [comment]
There already is code in Marlin, able to handle some buttons. (look for REPRAPWORLD_KEYPAD)

The changes would not be too much, if you stay with the current menu system. All you need is a "Up", a "Down" and a "Select" button. "Up" and "Down" could directly work on the `encoderPosition` variable.

**Comment by jasane** [comment]
Thanks KiteLab i didn't know that.
Actually i made a way to my joystick work and it's good, but i'm having another trouble now.
AS I'M using 16x2 lcd my menu isn't scrolling down, i tried the default setting with rotary encoder and my joystick setup, none of then scrolled.
Have you guys worked with 16x2 lcd?

**Comment by schirrel** [comment]
Thanks KiteLab i didn't know that.
Actually i made a way to my joystick work and it's good, but i'm having another trouble now.
AS I'M using 16x2 lcd my menu isn't scrolling down, i tried the default setting with rotary encoder and my joystick setup, none of then scrolled.
Have you guys worked with 16x2 lcd?

**Comment by KiteLab** [comment]
You can find the actual scroll code in the `START_MENU()` and  `END_MENU()` macros in ultralcd.cpp. As far i can see they use `LCD_HEIGHT` but i have not tested if that works for 2.

**Comment by schirrel** [comment]
HI all, just for information, i made the code for working with joystick =D
