### ISSUE TITLE
M42 issues

### ISSUE THREAD

**Issue by jon-daemon** [MarlinFirmware/Marlin#2776]
I have added some leds on digital pins and I use M42 command to light them up.
I use this code:

```
M42 P4 S255
G1 X10 Y195 F3000
```

The G1 command is not executed. I tried some other combinations and it seems it cannot execute the commands after the M42 line.

Also I tried these:

```
M42 P4 S255
M117 Lights ON
```

and

```
M42 P4 S0
M117 Lights OFF
```

The second combination works. The led is turning off and the message appearing on the display.
The first lights up my led but the message after the M117 is not shown.

I tried to upload .gcode files on a SD card, create macros on pronterface and custom buttons on OctoPrint. The command after the M42 never executed.
Any known issue?

I use Marlin 1.1.0 RC2 but I had the same behaviour with the previous version.

**Comment by Roxy-3D** [comment]
I don't use M117.  But I'm pretty sure you can't have a space in it.   I'm not sure how much text is allowed.   You might try using an underscore instead of a space.

Is Pin-4 where the LED is?   Does it actually turn on the LED when you do a M42 P4 S255 ?

Because, I don't see anything in the code that would keep the M42 from completing and going on to the next command.

You can try replacing your M42 command with the follow code to get more information about what is happening:

```
inline void gcode_M42() {
SERIAL_PROTOCOL("Starting M42\n");
  if (code_seen('S')) {
    int pin_status = code_value_short(),
        pin_number = LED_PIN;

SERIAL_PROTOCOL("Starting M42\n");

    if (code_seen('P') && pin_status >= 0 && pin_status <= 255)
      pin_number = code_value_short();

SERIAL_PROTOCOL("pin_number=");
SERIAL_PROTOCOL(pin_number);
SERIAL_PROTOCOL("\n");

    for (uint8_t i = 0; i < COUNT(sensitive_pins); i++) {
      if (sensitive_pins[i] == pin_number) {
        pin_number = -1;
SERIAL_PROTOCOL("Yikes!  You selected a sensitive pin.\n");
        break;
      }
    }
SERIAL_PROTOCOL("Done checking for a sensitive pin.\n");

    #if HAS_FAN
      if (pin_number == FAN_PIN) fanSpeed = pin_status;
    #endif

    if (pin_number > -1) {
      pinMode(pin_number, OUTPUT);
      digitalWrite(pin_number, pin_status);
      analogWrite(pin_number, pin_status);
SERIAL_PROTOCOL("Done changing pin value\n");
    }
  } // code_seen('S')
SERIAL_PROTOCOL("Leaving M42\n");
}
```

**Comment by jon-daemon** [comment]
I tried some other words on M117 command and it worked.
I was using the words "ON" and "Nozzle" on my M117 commands. Is there a list with forbidden words?
The G1 command wasn't executing because I was using absolute coordinates and the nozzle was already at that spot.

**Comment by Roxy-3D** [comment]
Well, I'm pretty sure the amount of text allowed is very small.   Maybe less than 20 characters.  I don't know.   But having a space in the text is for sure going to cause problems.   I think you will find a lot of people that don't even think the M117 command should exist.  It breaks all the GCode rules.

I don't think there are any 'Forbidden' words.

**Comment by jon-daemon** [comment]
It worked when I changed "ON" to "On" without removing spaces.
I will probably stop using M117.

**Comment by Roxy-3D** [comment]
@hackermagnet 

Oh!   It isn't a forbidden word!!!  Capital N's are used by the lower level serial protocol.   You can't ever send an N.   I ran into that adding functionality to the G29 command.   I wanted an N parameter to say how many points to probe and everything goes sideways if you do that.

**Comment by jon-daemon** [comment]
Now it makes sense. Thanks for pointing that out.

**Comment by KiteLab** [comment]
I can confirm the capital 'N' problem in M117 for `Release` and `1.0.x` but not for ~~`RC`~~, `RCBugFix` and `master`.
@hackermagnet 
Are you sure you compiled the right branch?

**Comment by jon-daemon** [comment]
@KiteLab Yes, I use Marlin 1.1.0-RC2 - 29 September 2015

**Comment by KiteLab** [comment]
Fixed with https://github.com/MarlinFirmware/Marlin/commit/c0e791dbe9a25b830e46511117d2c5ed6a5c4be4 13. Oct 2015 in `RCBugFix`
with https://github.com/MarlinFirmware/MarlinDev/commit/2fb06c27dc87a8b5dcd15963a3e47bfb4b4734b8 5. Oct in `master`.
Unfixed in `RC`.
