### ISSUE TITLE
Autolevel position/offset clarification

### ISSUE THREAD

**Issue by therippa** [MarlinFirmware/Marlin#2777]
To ease the transition to the new firmware, you might want to move the `PROBE_OFFSET` section above the `PROBE_BED_POSITION` section, and use them as variables along with the `MAX_POS`/`MIN_POS` settings (like `LEFT_PROBE_BED_POSITION = X_MIN_POS + X_PROBE_OFFSET + MIN_PROBE_EDGE +/- 1`) to make the offset settings more clear and extensible.  I'm very familiar with Marlin 1.0 and its configuration, and tonight when upgrading to 1.1-RC2, the functional changes weren't super clear to me, and this was the only hiccup I ran into.

**Comment by KiteLab** [comment]
Pardon?
Where did you get these versions?

**Comment by therippa** [comment]
Sorry, got the versioning mixed up with an unrelated project :)  I meant 1.1-RC2.

**Comment by thinkyhead** [comment]
Even though the `*_PROBE_OFFSET_FROM_EXTRUDER` settings come after the `*_PROBE_BED_POSITION` settings, it's a feature of the C++ compiler preprocessor that you can actually refer to a later define in an earlier define. So this is okay to use:

``` cpp
#define RIGHT_PROBE_BED_POSITION (X_MAX_POS - X_PROBE_OFFSET_FROM_EXTRUDER)
```

It should even work to use defines like `MAX_PROBE_X` which is defined in `Conditionals.h`:

``` cpp
#define RIGHT_PROBE_BED_POSITION MAX_PROBE_X
```

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
