### ISSUE TITLE
Idea and principle logic

### ISSUE THREAD

**Issue by Eyolon** [MarlinFirmware/Marlin#2778]
Hello

Today i've try to make a printing server with a raspberry using usb.

Works fine but when the bed is ready, the printer wait an user action on the lcd panel and again when the extruder is ready. i've check the code and i've haven't see easy solution to change this aspect.

If the security system works well, why not create a line in the configuration file to enable or disable user checking ?

**Comment by KiteLab** [comment]
Marlin does not require any user action until you, your slicer or host program tell Marlin to do so.
If you tell Marlin to do a M109 or M190, Marlin will wait until the requested temperature is reached - not for a user action.
