### ISSUE TITLE
Z homing and bed leveling not working

### ISSUE THREAD

**Issue by mkubik** [MarlinFirmware/Marlin#2782]
This is a spin-off from #2766 as advised by @Wurstnase 

Issue:
_Actually, I have the same issue but neither CoreXZ nor CoreXY defined. I use this one here:http://www.thingiverse.com/thing:301715
But when I run G29, I only see the extruder move up, not down.
Not sure if this is really the same, but the behavior is similar.
I may be missing something, I admit, so any hint is welcome._

**Comment by thinkyhead** [comment]
Check out MarlinFirmware/MarlinDev#358 and give it a try if you can.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
