### ISSUE TITLE
DualExtrude feature

### ISSUE THREAD

**Issue by nikolindima** [MarlinFirmware/Marlin#2783]
Can Marlin print with 2 extruders? I mean when you print 2 parts in same time with 2 extruders simultaneously 
![2012-05-27_11 29 20_display_large_preview_featured](https://cloud.githubusercontent.com/assets/944968/11192660/633d5718-8cb3-11e5-8e13-7ff61f7ec02c.jpg)

**Comment by dintid** [comment]
Maybe that questions is more appropriate on http://forums.reprap.org/ where you can find marlin and/or your specific printer :)

**Comment by Roxy-3D** [comment]
I do not believe there is anything in the current code base to do this.   But it would not be a very difficult change to make.   You would just turn on both hot ends and tell both extruder stepper motors to move at the same time.

**Comment by AnHardt** [comment]
A dual extruder setup seems to be possible, but then with alternating printing the right and left object.
The second possibility could be DUAL_X_CARRIAGE in Mode 2 (https://github.com/MarlinFirmware/Marlin/blob/Release/Marlin/Configuration_adv.h#L191).

**Comment by nivekhan** [comment]
I've got a dual x carriage setup and it's definitely possible to print simultaneously with Marlin.

**Comment by thinkyhead** [comment]
This is something to make sure to add to the documentation on dual X carriages. For now it is found in the configurations.
