### ISSUE TITLE
MakerBot - Mighty Board Rev G - Port Marlin

### ISSUE THREAD

**Issue by metropt** [MarlinFirmware/Marlin#2784]
Hello,

I have a mighty board rev g lying around from makerbot 2. I would like to run Marlin code to test it. I have the information about X/Y/Z STEP, DIR and ENA pin and also ENDSTOP pins.

What are the minimums needed for a one extruder printer and what other pins should I look for?

It is what I have for now.

``` cpp
define X_STEP_PIN          49
#define X_DIR_PIN           50
#define X_ENABLE_PIN       47
#define X_STOP_PIN         60

#define Y_STEP_PIN          40
#define Y_DIR_PIN           42
#define Y_ENABLE_PIN       39
#define Y_STOP_PIN         59

#define Z_STEP_PIN          36
#define Z_DIR_PIN           37
#define Z_ENABLE_PIN       35
#define Z_STOP_PIN         58
```

I haven't found any board that has pins similar to this on `pins.h`. Will I be able to use it anyway? Can you confirm for me if I'll be able to use it?

Thank you!

**Comment by Roxy-3D** [comment]
There is a very stable version of an older Marlin for MakerBot at:

https://github.com/beckdac/Marlin

If you start with the beckdac fork and start updating the various pin definitions you should be able to make progress pretty quickly.

**Comment by metropt** [comment]
It looks like it is for a very old markerbot.

I'll compile it and flash it into the atmega and try to move a stepper. I'm just afraid of mis configure the IO and burn something...

**Comment by thinkyhead** [comment]
Any luck? There have been more than a few requests for MightyBoard support.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
