### ISSUE TITLE
G92 not working on Z-axis (at least with autolevel enabled)

### ISSUE THREAD

**Issue by therippa** [MarlinFirmware/Marlin#2791]
Was readjusting my autoleveling tonight, and for fine tuning I run G92Z10 so I can move down 0.1mm at a time.  I have my offset set to -0.1 in the firmware.  After running G29, Z was reported as 0.1 on the LCD, but after running G92Z10, the Z position was not changed (LCD and host still said 0.1), and I was not able to move the Z axis down.

**Comment by Roxy-3D** [comment]
Do you have softwareendstops #define'd as true ?

**Comment by thinkyhead** [comment]
Closing this as it's an old issue. If the problem still exists in the latest `RC` and `RCBigFix`, please re-open.
