### ISSUE TITLE
1.1.0-RC2 want to print out of range after auto bed leveling

### ISSUE THREAD

**Issue by 118d** [MarlinFirmware/Marlin#2802]
Hello , i have build Prusa i3 heatbed 300x200 , when i test it with pronterface everything works ok 
G29 is ok . when i tried to print with Cura everything goes wrong after homing ok ,auto bed level ok .
Then when he starts to print , the print start with drawing cubic lines 3x then A kind of Bridel line (like stairs) then he run complete to the outer line of heatbed end en everything get blocked 
when i tried to print the cura robot. 
it seems the coordinates of the printer are not the same than cura i have chance the dimensions of the heatbed like it have to be . also put the G29 code in cura, deleted G28 Z .
why works everything ok in pronterface and not in cura ?
the only thing whats he does in pronterface when homing he run to the middle of the heatbed ?
this are my settings 
# if DISABLED(ENDSTOPPULLUPS)

  // fine endstop settings: Individual pullups. will be ignored if ENDSTOPPULLUPS is defined
  //#define ENDSTOPPULLUP_XMAX
  //#define ENDSTOPPULLUP_YMAX
  //#define ENDSTOPPULLUP_ZMAX
  //#define ENDSTOPPULLUP_XMIN
  //#define ENDSTOPPULLUP_YMIN
    #define ENDSTOPPULLUP_ZMIN
    #define ENDSTOPPULLUP_ZMIN_PROBE
# endif

// Mechanical endstop with COM to ground and NC to Signal uses "false" here (most common setup).
const bool X_MIN_ENDSTOP_INVERTING = false; // set to true to invert the logic of the endstop.
const bool Y_MIN_ENDSTOP_INVERTING = false; // set to true to invert the logic of the endstop.
const bool Z_MIN_ENDSTOP_INVERTING = true; // set to true to invert the logic of the endstop.
const bool X_MAX_ENDSTOP_INVERTING = false; // set to true to invert the logic of the endstop.
const bool Y_MAX_ENDSTOP_INVERTING = false; // set to true to invert the logic of the endstop.
const bool Z_MAX_ENDSTOP_INVERTING = false; // set to true to invert the logic of the endstop.
const bool Z_MIN_PROBE_ENDSTOP_INVERTING = false; // set to true to invert the logic of the endstop.
# define DISABLE_MAX_ENDSTOPS

//#define DISABLE_MIN_ENDSTOPS

// If you want to enable the Z probe pin, but disable its use, uncomment the line below.
// This only affects a Z probe endstop if you have separate Z min endstop as well and have
// activated Z_MIN_PROBE_ENDSTOP below. If you are using the Z Min endstop on your Z probe,
// this has no effect.
//#define DISABLE_Z_MIN_PROBE_ENDSTOP

// For Inverting Stepper Enable Pins (Active Low) use 0, Non Inverting (Active High) use 1
// :{0:'Low',1:'High'}
# define X_ENABLE_ON 0
# define Y_ENABLE_ON 0
# define Z_ENABLE_ON 0
# define E_ENABLE_ON 0 // For all extruders

// Disables axis when it's not being used.
// WARNING: When motors turn off there is a chance of losing position accuracy!
# define DISABLE_X false
# define DISABLE_Y false
# define DISABLE_Z false

// @section extruder
# define DISABLE_E false // For all extruders
# define DISABLE_INACTIVE_EXTRUDER true //disable only inactive extruders and keep active extruder enabled

// @section machine

// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
# define INVERT_X_DIR false
# define INVERT_Y_DIR true
# define INVERT_Z_DIR false

// @section extruder

// For direct drive extruder v9 set to true, for geared extruder set to false.
# define INVERT_E0_DIR false
# define INVERT_E1_DIR false
# define INVERT_E2_DIR false
# define INVERT_E3_DIR false

// @section homing

// ENDSTOP SETTINGS:
// Sets direction of endstops when homing; 1=MAX, -1=MIN
// :[-1,1]
# define X_HOME_DIR -1
# define Y_HOME_DIR -1
# define Z_HOME_DIR -1
# define min_software_endstops true // If true, axis won't move to coordinates less than HOME_POS.
# define max_software_endstops true  // If true, axis won't move to coordinates greater than the defined lengths below.

// @section machine

// Travel limits after homing (units are in mm)
# define X_MIN_POS 0
# define Y_MIN_POS 0
# define Z_MIN_POS 0
# define X_MAX_POS 195
# define Y_MAX_POS 295
# define Z_MAX_POS 400

// @section bedlevel
# define AUTO_BED_LEVELING_FEATURE // Delete the comment to enable (remove // at the start of the line)

//#define DEBUG_LEVELING_FEATURE
# define Z_MIN_PROBE_REPEATABILITY_TEST  // If not commented out, Z-Probe Repeatability test will be included if Auto Bed Leveling is Enabled.
# if ENABLED(AUTO_BED_LEVELING_FEATURE)

  // There are 2 different ways to specify probing locations:
  //
  // - "grid" mode
  //   Probe several points in a rectangular grid.
  //   You specify the rectangle and the density of sample points.
  //   This mode is preferred because there are more measurements.
  //
  // - "3-point" mode
  //   Probe 3 arbitrary points on the bed (that aren't colinear)
  //   You specify the XY coordinates of all 3 points.

  // Enable this to sample the bed in a grid (least squares solution).
  // Note: this feature generates 10KB extra code size.
  #define AUTO_BED_LEVELING_GRID

  #if ENABLED(AUTO_BED_LEVELING_GRID)

```
#define LEFT_PROBE_BED_POSITION 10
#define RIGHT_PROBE_BED_POSITION 160
#define FRONT_PROBE_BED_POSITION 20
#define BACK_PROBE_BED_POSITION 285

#define MIN_PROBE_EDGE 10 // The Z probe minimum square sides can be no smaller than this.

// Set the number of grid points per dimension.
// You probably don't need more than 3 (squared=9).
#define AUTO_BED_LEVELING_GRID_POINTS 3
```

  #else  // !AUTO_BED_LEVELING_GRID

```
  // Arbitrary points to probe.
  // A simple cross-product is used to estimate the plane of the bed.
  #define ABL_PROBE_PT_1_X 15
  #define ABL_PROBE_PT_1_Y 180
  #define ABL_PROBE_PT_2_X 15
  #define ABL_PROBE_PT_2_Y 20
  #define ABL_PROBE_PT_3_X 170
  #define ABL_PROBE_PT_3_Y 20
```

  #endif // AUTO_BED_LEVELING_GRID

  // Offsets to the Z probe relative to the nozzle tip.
  // X and Y offsets must be integers.
  #define X_PROBE_OFFSET_FROM_EXTRUDER -32     // Z probe to nozzle X offset: -left  +right
  #define Y_PROBE_OFFSET_FROM_EXTRUDER +15     // Z probe to nozzle Y offset: -front +behind
  #define Z_PROBE_OFFSET_FROM_EXTRUDER -0.83  // Z probe to nozzle Z offset: -below (always!)

**Comment by KiteLab** [comment]
When you get different results in Cura then in Pronterface. Cura and Pronterface do send different code to Marlin - else the Marlin would do the same. If both of them send the same g-code-file, the setup for Cura and Pronterface is different. Likely they do send different start scripts. Marlin is the wrong place to look for the problem.

**Comment by AnHardt** [comment]
The difference in homing could be G28 vs. (G28 XY, G28 Z). With G28 alone you get a "save homing" if not deactivated - otherwise not.

**Comment by 118d** [comment]
Hello , thanks for the reply the problem was that i used te arduino 1.6.6( i have new arduino mega genie) with could have higher baud rates 250000 and not 115200 strange thing the complier did not gives errors.
 then i used 1.0.6 baudrates 115200 end everything was ok .
also forgot to change the G28 XY => G28.
Everything works now.
