### ISSUE TITLE
CoreXY home XY problem

### ISSUE THREAD

**Issue by selimmeric** [MarlinFirmware/Marlin#2804]
Hi.. when I did Home X, and  Home Y its working and stoping 
"G28 X" => working
"G28 Y" => working
"G28 XY" => stucking near home position, not stopping ...

**Comment by tonnico** [comment]
If you are using max endstops and the old release, that is a known issue. Please try then the RC.

**Comment by selimmeric** [comment]
#define STRING_VERSION "1.0.2"

I am not using max endstop and 
there are a code in configration.h file so its impossiable to use maxendstops I think .. 

Line ~280: #define DISABLE_MAX_ENDSTOPS 

Line ~284:#if defined(COREXY) && !defined(DISABLE_MAX_ENDSTOPS)
Line ~285:  #define DISABLE_MAX_ENDSTOPS
Line ~286:#endif

I will resarch more ..

**Comment by tonnico** [comment]
Maybe you should use `G28 X Y` instead of `G28 XY`

**Comment by selimmeric** [comment]
I try it with RC .. yes it work... I need more time to transfer my old  configration to new release... thanks..
