### ISSUE TITLE
Dual_y_axis + auto bed levelling => unknown position

### ISSUE THREAD

**Issue by victorjung** [MarlinFirmware/Marlin#2808]
Hello, I would like to report an issue, it seems that when you use auto-bed levelling but also y_dual_axis, marlin will refuse to do a G29 E after a G28, saying home X Y first.
I found it to come from the condition:
`if (! (axis_known_position[X_AXIS] && axis_known_position[Y_AXIS]) )`
In `Marlin_main.cpp` at the beginning of the execution of the case 29: bloc.
But I didn't push forward to see why is there a problem with the condition, but I am pretty sure it comes from the homing of y with the dual_y_axis condition...
Anyway good luck!

**Comment by thinkyhead** [comment]
Are you still seeing this issue with [1.1.0-RC3](https://github.com/MarlinFirmware/Marlin/releases/tag/1.1.0-RC3)? From a casual inspection of the code I can see nothing unusual going on with `axis_known_position` when `Y_DUAL_STEPPER_DRIVERS` is enabled.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
