### ISSUE TITLE
expected initializer before 'MARLIN_PROGMEM'

### ISSUE THREAD

**Issue by SLYSCORPIO** [MarlinFirmware/Marlin#2810]
I have been searching and can not find a solution to this error message. I have a Prusa Mendel with a Rambo. Any help will be appreciated. 

Arduino: 1.6.6 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2366:0: warning: "X_MS1_PIN" redefined [enabled by default]

 #define X_MS1_PIN 40

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:7:0: note: this is the location of the previous definition

 #define X_MS1_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2367:0: warning: "X_MS2_PIN" redefined [enabled by default]

 #define X_MS2_PIN 41

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:8:0: note: this is the location of the previous definition

 #define X_MS2_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2374:0: warning: "Y_MS1_PIN" redefined [enabled by default]

 #define Y_MS1_PIN 69

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:9:0: note: this is the location of the previous definition

 #define Y_MS1_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2375:0: warning: "Y_MS2_PIN" redefined [enabled by default]

 #define Y_MS2_PIN 39

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:10:0: note: this is the location of the previous definition

 #define Y_MS2_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2382:0: warning: "Z_MS1_PIN" redefined [enabled by default]

 #define Z_MS1_PIN 68

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:11:0: note: this is the location of the previous definition

 #define Z_MS1_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2383:0: warning: "Z_MS2_PIN" redefined [enabled by default]

 #define Z_MS2_PIN 67

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:12:0: note: this is the location of the previous definition

 #define Z_MS2_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2404:0: warning: "E0_MS1_PIN" redefined [enabled by default]

 #define E0_MS1_PIN 65

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:13:0: note: this is the location of the previous definition

 #define E0_MS1_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2405:0: warning: "E0_MS2_PIN" redefined [enabled by default]

 #define E0_MS2_PIN 66

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:14:0: note: this is the location of the previous definition

 #define E0_MS2_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2410:0: warning: "E1_MS1_PIN" redefined [enabled by default]

 #define E1_MS1_PIN 63

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:15:0: note: this is the location of the previous definition

 #define E1_MS1_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2411:0: warning: "E1_MS2_PIN" redefined [enabled by default]

 #define E1_MS2_PIN 64

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:16:0: note: this is the location of the previous definition

 #define E1_MS2_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:2413:0: warning: "DIGIPOTSS_PIN" redefined [enabled by default]

 #define DIGIPOTSS_PIN 38

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\BlinkM.cpp:5:
```

sketch\pins.h:17:0: note: this is the location of the previous definition

 #define DIGIPOTSS_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2366:0: warning: "X_MS1_PIN" redefined [enabled by default]

 #define X_MS1_PIN 40

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:7:0: note: this is the location of the previous definition

 #define X_MS1_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2367:0: warning: "X_MS2_PIN" redefined [enabled by default]

 #define X_MS2_PIN 41

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:8:0: note: this is the location of the previous definition

 #define X_MS2_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2374:0: warning: "Y_MS1_PIN" redefined [enabled by default]

 #define Y_MS1_PIN 69

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:9:0: note: this is the location of the previous definition

 #define Y_MS1_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2375:0: warning: "Y_MS2_PIN" redefined [enabled by default]

 #define Y_MS2_PIN 39

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:10:0: note: this is the location of the previous definition

 #define Y_MS2_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2382:0: warning: "Z_MS1_PIN" redefined [enabled by default]

 #define Z_MS1_PIN 68

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:11:0: note: this is the location of the previous definition

 #define Z_MS1_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2383:0: warning: "Z_MS2_PIN" redefined [enabled by default]

 #define Z_MS2_PIN 67

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:12:0: note: this is the location of the previous definition

 #define Z_MS2_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2404:0: warning: "E0_MS1_PIN" redefined [enabled by default]

 #define E0_MS1_PIN 65

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:13:0: note: this is the location of the previous definition

 #define E0_MS1_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2405:0: warning: "E0_MS2_PIN" redefined [enabled by default]

 #define E0_MS2_PIN 66

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:14:0: note: this is the location of the previous definition

 #define E0_MS2_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2410:0: warning: "E1_MS1_PIN" redefined [enabled by default]

 #define E1_MS1_PIN 63

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:15:0: note: this is the location of the previous definition

 #define E1_MS1_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2411:0: warning: "E1_MS2_PIN" redefined [enabled by default]

 #define E1_MS2_PIN 64

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:16:0: note: this is the location of the previous definition

 #define E1_MS2_PIN -1

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:2413:0: warning: "DIGIPOTSS_PIN" redefined [enabled by default]

 #define DIGIPOTSS_PIN 38

 ^

In file included from sketch\Marlin.h:23:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

sketch\pins.h:17:0: note: this is the location of the previous definition

 #define DIGIPOTSS_PIN -1

 ^

sketch\ConfigurationStore.cpp: In function 'void Config_ResetDefault()':

ConfigurationStore.cpp:426: error: expected initializer before 'MARLIN_PROGMEM'

```
 const static float tmp1[] MARLIN_PROGMEM =DEFAULT_AXIS_STEPS_PER_UNIT;

                           ^
```

ConfigurationStore.cpp:427: error: expected initializer before 'MARLIN_PROGMEM'

```
 const static float tmp2[] MARLIN_PROGMEM =DEFAULT_MAX_FEEDRATE;

                           ^
```

ConfigurationStore.cpp:428: error: expected initializer before 'MARLIN_PROGMEM'

```
 const static long tmp3[] MARLIN_PROGMEM =DEFAULT_MAX_ACCELERATION;

                          ^
```

In file included from sketch\Marlin.h:16:0,

```
             from sketch\ConfigurationStore.cpp:1:
```

ConfigurationStore.cpp:434: error: 'tmp1' was not declared in this scope

```
 axis_steps_per_unit[i] = pgm_read_float(&tmp1[i]);

                                          ^
```

ConfigurationStore.cpp:435: error: 'tmp2' was not declared in this scope

```
 max_feedrate[i] = pgm_read_float(&tmp2[i]);

                                   ^
```

ConfigurationStore.cpp:436: error: 'tmp3' was not declared in this scope

```
 max_acceleration_units_per_sq_second[i] = pgm_read_float(&tmp3[i]);

                                                           ^
```

exit status 1
expected initializer before 'MARLIN_PROGMEM'

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by Wackerbarth** [comment]
> On Nov 28, 2015, at 4:38 PM, SLYSCORPIO notifications@github.com wrote:
> sketch\pins.h:2366:0: warning: "X_MS1_PIN" redefined [enabled by default]

I don’t know what source you are trying to compile.
The current pins.h file has only 257 lines.
Branches earlier than 1.1 (aka RC, RCBugFix, etc.) do not compile properly on modern Arduino IDE releases.

Please switch to the RCBugFix for the latest prerelease firmware, or the “dev” branch in the MarlinDev repository for the latest buildable firmware.

**Comment by SLYSCORPIO** [comment]
Okay I downloaded the Marlin RCBugFix and it compiled. I will transfer some code and recompile to make sure we are good to go but it appears that has fixed my problem. I appreciate your assistance.

**Comment by SLYSCORPIO** [comment]
After running into some problems trying to print, I decided to download Arduino IDE version 1.0.6. That allowed me to compile the older version of Marlin and fixed my problem.
