### ISSUE TITLE
'DIOA3_DDR' was not declared in this scope

### ISSUE THREAD

**Issue by schirrel** [MarlinFirmware/Marlin#2815]
I tried to declare a new pin to input `SET_INPUT(JOY_Y);` but the error message return its.
The pin is declared in pins.h but this error appears when i try to set the input at ultralcd.cpp

**Comment by thinkyhead** [comment]
Did you ever figure this out? This kind of error will appear when you try to use pins that aren't properly defined.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
