### ISSUE TITLE
Determine Endstop Hits when Homing 

### ISSUE THREAD

**Issue by thesec** [MarlinFirmware/Marlin#2816]
Hi,

I just updated to 1.02 and wondered where to find the setting, if any, to allow for hitting the endstops twice when homing my Delta?

Thanks ahead.

**Comment by KiteLab** [comment]
That's neither configurable in 1.0.2 nor later branches. Marlin should do always two bumps.
But there should be a backup from the hardware endstops before setting the software endstops.

**Comment by thesec** [comment]
It does not for me. How comes then?!

**Comment by KiteLab** [comment]
In case this parameters:

```
//homing hits the endstop, then retracts by this distance, before it tries to slowly bump again:
#define X_HOME_BUMP_MM 5
#define Y_HOME_BUMP_MM 5
#define Z_HOME_BUMP_MM 5 // deltas need the same for all three axis
```

are to small to untrigger the endstops, no second bump will happen

**Comment by thesec** [comment]
Seems to be called *_HOME_RETRACT_MM in 1.02 and is still set to 5 per default.
Yet the printer does not try to bump again on any axis.

What does determine a "too small value"?

**Comment by KiteLab** [comment]
>  small to untrigger the endstops.
> The carriages should move down that way to give the switch enough room to expand again, to release the contact.

There is an other possible cause for not moving down.
Please send a M119 to your printer and report the output here. Once in mid air, once right after homing.
Are any min-endstops TRIGGERED?

**Comment by thesec** [comment]
Sry, that'll have to wait for the printer to be re-build ... am currently overhauling ...

Will get back when it is back up.
