### ISSUE TITLE
Kossel Autoleveling moving up?

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#2827]
Hi, I just updated my printer firmware (from 1.0) to newest release and have problems with autoleveling. The printer always moves up after homing during autoleveling. I am using a servo with endstop, which perfectly deploys and retracts after the process. All manual commands are working without any problems. What could be the reason, that autoleveling is working in the wrong z direction? Here is a snapshot of my debug .. end of G28 and beginning of G29:

<<< homeaxis(2)
(DELTA) > current_position: (0.00, 0.00, 215.80)
ENDSTOPS_ONLY_FOR_HOMING enable_endstops(false)
<<< gcode_G28

> > > G29
> > > SENDING:G29
> > > gcode_G29 >>>
> > > G29 Auto Bed Leveling
> > > deploy_z_probe > current_position: (0.00, 0.00, 215.80)
> > > reset_bed_level
> > > setup_for_endstop_move > enable_endstops(true)
> > > z_before = (before) 0.00
> > > z_before = (before) 0.00
> > > z_before = (before) 0.00
> > > z_before = (before) 0.00
> > > z_before = (before) 0.00
> > > z_before = (before) 0.00
> > > z_before = (before) 0.00
> > > z_before = (before) 0.00
> > > z_before = (before) 0.00
> > > probe_pt >>>
> > > ProbeAction:0
> > > current_position: (0.00, 0.00, 215.80)
> > > Z Raise to z_before 0.00
> > > do_blocking_move_to_z 0.00
> > > do_blocking_move_to: (0.00, 0.00, 0.00)
> > > prepare_move_raw > destination: (0.00, 0.00, 0.00)
> > > do_blocking_move_to_xy 50.00, -34.00
> > > do_blocking_move_to: (50.00, -34.00, 0.00)
> > > prepare_move_raw > destination: (50.00, -34.00, 0.00)
> > > run_z_probe (DELTA) 1
> > > prepare_move_raw > destination: (50.00, -34.00, -10.00)
> > > run_z_probe (DELTA) 2 > current_position: (50.00, -34.00, -0.01)
> > > <<< probe_pt
> > > z_before = (between) 4.99
> > > probe_pt >>>
> > > ProbeAction:0
> > > current_position: (50.00, -34.00, -0.01)

**Comment by KiteLab** [comment]
Please describe a bit more what happens.
You have homed the effector is at [0,0,215.80]
The servo deploys.
The effector is going down to [0,0, Z_RAISE_BEFORE_PROBING] 
Your  Z_RAISE_BEFORE_PROBING is 0.
Probably it will never arrive there, because your probe is already extended.
Set  Z_RAISE_BEFORE_PROBING to at least Z_RAISE_BETWEEN_PROBINGS to be sure not to touch the bed here.

Z_RAISE_BETWEEN_PROBINGS must be big enough to to avoid probe contact on all horizontal (bowl shaped moves). 
Z_RAISE_BEFORE_PROBING is ought to describe the minimal height above the bed for safely, deploying the servo probe, without touching the bed

**Comment by Phaelz** [comment]
I am having the same problem here. I have a delta with no servo or anything that is deployed. The hotend itself is used as probe.

After homing, when I press G29, everything wants to go up, but the delta already is at its maximum height. With Marlin 1.0.2 or 1.0.4 I have no problem at all.

I tried to comment #define ENDSTOPS_ONLY_FOR_HOMING but then something really weird happens, it is like my steps/mm becomes 1, the printer barely moves.

Tried a lot of different options, no success.

**Comment by KiteLab** [comment]
@Phaelz
I guess your probe is permanently triggered. Please test with M119.
Or maybe the vibrations of movement can trigger the probe

**Comment by Phaelz** [comment]
@KiteLab, it is not.

I tried several delta configurations, same thing.

**Comment by Phaelz** [comment]
In fact, I triggered the endstop with my hand during the auto level several times and the behavior is the same.

I've just tried this:
G28
G1 Z4 (to put the effector near the bed, if I use G29 here it keeps crashing on the max endstops)
G29

after the auto level command, it raises to Z15 (my Z_RAISE_BEFORE_PROBING), then it goes to X0 Y50 and it goes up, up, up, up, as if it had the endstop triggered, but it doesn't move to another location and the Z_MIN endstop is not triggered at any time.

I onlye have X_MIN and Y_MIN triggered all the times but they are not active in my board.

**Comment by KiteLab** [comment]
@Phaelz 
Please home G28, activate the endstops manually M120, go down G1 Z50.
Any messages on the console?

**Comment by Phaelz** [comment]
@KiteLab , oh god hahahahah

Here is the message:

echo:endstops hit:  X:488.28 Y:488.28 Z:488.28

I put G1 Z50 and it went down half centimeter only! What happened?

**Comment by KiteLab** [comment]
@Phaelz
One of your endstops/probe triggered. Probably the probe.

**Comment by Phaelz** [comment]
@KiteLab , I don't understand. I did active the Z_MIN_ENDSTOP with my hand before M120, and while it was activated I entered G1 Z50. It moved down just a little bit instead of moving 250mm.

And how the hell my endstops activated in 488.28? That's not even possible. I have Xmin and Ymin as triggered all the time, are they causing this? How do I deactivate them since the 1.1.0 marlin version removed the disable endstop option in config.h?

**Comment by KiteLab** [comment]
@Phaelz
Arrrrrg.

```
const bool X_MIN_ENDSTOP_INVERTING = false; // set to true to invert the logic of the endstop.
const bool Y_MIN_ENDSTOP_INVERTING = false; // set to true to invert the logic of the endstop.
```

Change these.

**_EDITED**_

**Comment by KiteLab** [comment]
Sorry MIN!!!

**Comment by KiteLab** [comment]
Golden rule: "No unused endstop shall be triggered."

**Comment by Phaelz** [comment]
@KiteLab , I'm so sorry. Such a rookie mistake... I didn't know that Min endstops would interfere with the delta... everything is fine now... probably @pistreamer is facing something like this.

Thank you very very much! Everything is fine now, I'll keep with the debugging in this delta. I hate this kind of printer! haahhaha

**Comment by ghost** [comment]
Hi! It seems that there are a lot of changes, between my old and new version ;) In my old version I didn't have to disable or invert min endstops for delta printer, which causes the problem. Now it works thank you very much!
