### ISSUE TITLE
Problem with communication

### ISSUE THREAD

**Issue by SDmodelar** [MarlinFirmware/Marlin#2828]
Hello everyone,
I am a beginner in making 3D printers and I used Ramps 1.4 Marlin Firmware 1.0.2.  
I have a problem communicating with sw Pronterface and Repetier.
When I use the Arduino sw communication works.

Best regards

**Comment by KiteLab** [comment]
Pick the right serial port with the baud rate in your `Configuration.h` and it will work.

**Comment by thinkyhead** [comment]
I will assume this problem is solved by now. :+1:
