### ISSUE TITLE
Heights for stowing probe have changed

### ISSUE THREAD

**Issue by Wackerbarth** [MarlinFirmware/Marlin#2829]
In earlier versions, the coordinates for the stowing of the (allen) probe basically matches the object coordinate space.

However, in RC3, the height appears to be offset.

The workaround is to adjust the Z height parameter until it works.
However, this is not at all what someone would expect the correct value to be.

**Comment by thinkyhead** [comment]
Code in `stow_z_probe` seems to be correctly using the stow coordinates as absolute, not relative. We'll have to get independent confirmation whether they're acting funny from someone with an allen key probe.

``` cpp
      // Move to the start position to initiate retraction
      destination[X_AXIS] = Z_PROBE_ALLEN_KEY_STOW_1_X;
      destination[Y_AXIS] = Z_PROBE_ALLEN_KEY_STOW_1_Y;
      destination[Z_AXIS] = Z_PROBE_ALLEN_KEY_STOW_1_Z;
      prepare_move_raw();

      // Move the nozzle down to push the Z probe into retracted position
      if (Z_PROBE_ALLEN_KEY_STOW_2_FEEDRATE != Z_PROBE_ALLEN_KEY_STOW_1_FEEDRATE)
        feedrate = Z_PROBE_ALLEN_KEY_STOW_2_FEEDRATE;
      if (Z_PROBE_ALLEN_KEY_STOW_2_X != Z_PROBE_ALLEN_KEY_STOW_1_X)
        destination[X_AXIS] = Z_PROBE_ALLEN_KEY_STOW_2_X;
      if (Z_PROBE_ALLEN_KEY_STOW_2_Y != Z_PROBE_ALLEN_KEY_STOW_1_Y)
        destination[Y_AXIS] = Z_PROBE_ALLEN_KEY_STOW_2_Y;
      destination[Z_AXIS] = Z_PROBE_ALLEN_KEY_STOW_2_Z;
      prepare_move_raw();

      // Move up for safety
      if (Z_PROBE_ALLEN_KEY_STOW_3_FEEDRATE != Z_PROBE_ALLEN_KEY_STOW_2_FEEDRATE)
        feedrate = Z_PROBE_ALLEN_KEY_STOW_2_FEEDRATE;
      if (Z_PROBE_ALLEN_KEY_STOW_3_X != Z_PROBE_ALLEN_KEY_STOW_2_X)
        destination[X_AXIS] = Z_PROBE_ALLEN_KEY_STOW_3_X;
      if (Z_PROBE_ALLEN_KEY_STOW_3_Y != Z_PROBE_ALLEN_KEY_STOW_2_Y)
        destination[Y_AXIS] = Z_PROBE_ALLEN_KEY_STOW_3_Y;
      destination[Z_AXIS] = Z_PROBE_ALLEN_KEY_STOW_3_Z;
      prepare_move_raw();
```

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
