### ISSUE TITLE
Dialog "Tune" entries point to the wrong place (FULL GRAPHICS LCD)

### ISSUE THREAD

**Issue by Louis-Cypher** [MarlinFirmware/Marlin#2833]
Dear Developers,

in RC3 (at least) several menue items in the "Tune" dialog in the LCD menue point to Flow adjustment. Please check entries for bed temperature adjustment to verify.

Best,

Markus

**Comment by KiteLab** [comment]
Fix is pending. #2823

**Comment by thinkyhead** [comment]
This should be patched now, at least in `RCBugFix`. Hoping to have RC4 out soon!
