### ISSUE TITLE
X endstops not stopping stepper

### ISSUE THREAD

**Issue by mkubik** [MarlinFirmware/Marlin#2834]
I think this might be more of a consulting question rather than a real issue.
I'm running a RUMBA board, and my x endstops (min + max) are triggered, I see the LED light up, 
but I can still move the x axis with octoprint. Interestingly, y min and max endstops work ok.

Can you please advise?
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/57120/Configuration.txt)
Thanks!

**Comment by KiteLab** [comment]
Please don't trust the LED.
You'll get the relevant information by sending M119.

At first test every connected endstop, if you can trigger it manually.
If you can't change it's state, it is ether not connected the right way, or you can change the ENDSTOPPULLUP setting for that switch , to see if it works then.
Then change the ENDSTOP_INVERTING settings until no endstop is triggered in mid air.

In mid air no endstop, even unconnected, shall show triggered.

If you have a probe, make the same tests.
