### ISSUE TITLE
Why isn't there a Marlin folder at RepRap.Org???

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#2852]
How can this be???   If you go to:

http://forums.reprap.org/index.php?140

There is no Marlin folder.   Who knows somebody over there to get a folder added?

**Comment by MichaelBrock** [comment]
They have a separate set of folders for firmware. Still nothing specific to Marlin (or any other firmware for that matter):

http://forums.reprap.org/index.php?145

**Comment by Roxy-3D** [comment]
> They have a separate set of folders for firmware. Still nothing specific to Marlin (or any other firmware for that matter):
> 
> http://forums.reprap.org/index.php?145

Oh!!!   I saw Repetier in that list and just assumed it was for the firmware side of that.   And at that point, it was like "Wait a minute!!!"

**Comment by ntoff** [comment]
http://forums.reprap.org/index.php?145 and I would assume it'd be in "mainstream", I've seen a few Marlin questions in there.

**Comment by thinkyhead** [comment]
Marlin folder now at http://forums.reprap.org/list.php?415
