### ISSUE TITLE
SD support Azteeg X3 Pro and VIKI 2 //Card inserted and "NO SD CARD" show//

### ISSUE THREAD

**Issue by fbarcenas** [MarlinFirmware/Marlin#2854]
Hello,

Board Azteeg X3 Pro, display VIKI 2 and version 1.1.0 RC3.
Everything work perfect less the SD card not work, when i insert the SD CARD, the display say:
Card Inserted,

but when i go to Menu-> the display say "NO SD CARD"

I check and recheck all wires and all is ok.

I test several brands of SD CARD, also we test in FAT and exFAT format. 
Same problem.

What is the problem? How solve?
What more info i can offer you? 

Thanks

**Comment by thinkyhead** [comment]
I believe this will occur if the SD card is not write-protected when inserted. Or maybe it's when it _is_ write-protected. Try moving the little tab on the SD card and trying again.
