### ISSUE TITLE
Thermal Runaway always on same spot

### ISSUE THREAD

**Issue by pbrgle1** [MarlinFirmware/Marlin#2857]
I'm having this thermal runaway issue and it's driving me crazy. I'm trying to print this LCD Housing with my dual X Carriage printer using 2 materials and the print always stops on the same spot. I am using the second extruder for infill and the thermal runaway happens always about 30s into the first Solit Top Layer which is using the main extruder. 

At first i thought it was an issue with Octoprint but now the same happened using Simplify3D host. I am very close to disabling the thermal runaway protection alltogether... Is there a known fix for this issue? I see a lot of people are having thermal runaway issues. 

PS: The heater 0 is the left one!

Here are some pictures:
![runaway](https://cloud.githubusercontent.com/assets/14819847/11823149/bf5992a2-a372-11e5-84c5-7c5899a727b6.png)
![imag0862](https://cloud.githubusercontent.com/assets/14819847/11823200/17e1cd9a-a373-11e5-9fa1-b6ce3de2b886.jpg)

**Comment by Roxy-3D** [comment]
Before you disable it...   Try changing the Configuration_adv.h settings to relax things a little bit.  On my printer I had to change:

```
//  #define WATCH_TEMP_PERIOD 16                // Seconds
//  #define WATCH_TEMP_INCREASE 4               // Degrees Celsius
```

to 

```
  #define WATCH_TEMP_PERIOD 20                // Seconds
  #define WATCH_TEMP_INCREASE 2               // Degrees Celsius
```

**Comment by KiteLab** [comment]
Dear @Roxy-3DPrintBoard 
again you are suggesting to tune the wrong parameters.

Tune WATCH_TEMP_PERIOD and WATCH_TEMP_INCREASE against "Heating failed".
Tune THERMAL_PROTECTION_PERIOD and THERMAL_PROTECTION_HYSTERESIS against "Thermal Runaway"

**Comment by Roxy-3D** [comment]
Yeah...  OK...  I'll be more careful.    But the truth is, that fixed my problem.  When my 2nd extruder turned off, it starts dropping in temperature.   When I turn it back on, it shows that it is still dropping for a while.  There is some lag between when the heater is turned on and the thermistor sees an increase in temperature.

**Comment by AlwaysTinkering** [comment]
I've found that if you are using bang-bang, the bed temp fluctuates enough at ABS temps to give a thermal runaway using a typical mk2 heatbed.  I had to tune the following values in Configuration_adv.h

``` cpp
#if ENABLED(THERMAL_PROTECTION_BED)
  #define THERMAL_PROTECTION_BED_PERIOD 30    // Seconds
  #define THERMAL_PROTECTION_BED_HYSTERESIS 10 // Degrees Celsius
#endif
```
