### ISSUE TITLE
marlin configurator

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#2858]
can't parse boards.h when i upload the file

**Comment by KiteLab** [comment]
The configurator is not ready yet - and it's questionable it it will be finished, since development stopped.
For an alternate way for a (simplified?) configuration see MarlinFirmware/MarlinDev.

**Comment by ghost** [comment]
thanks

**Comment by thinkyhead** [comment]
I've moved development to: https://github.com/thinkyhead/MarlinConfigurator

With an all-new configuration system being developed for Marlin 1.2.x, I'm not sure what the fate of this "configurator" will be. It's off to an interesting start, and I'd like to continue to develop the core functions which read C++ compiler directives, make sense of them, and then wrap them up in a GUI. Once that core stuff is more complete, it will be easier to apply to any future compiler directive-based configuration system that Marlin might use.
