### ISSUE TITLE
Z Homing not working (motor humming)

### ISSUE THREAD

**Issue by TheNuubi** [MarlinFirmware/Marlin#2859]
First: Its not a hardware problem, the movements work fine, motor is strong enough.
I am having weird issues with my z axis homing. I can go to the endstop manually (not homing) without problems. However if i home (repetier host) the motor just humms. Endstop and movement are callibrated correctly (like x and y which are working). I tried disabling safe homing and zprobe (i dont have one).
Printer: Reprap, Ramps 1.4

**Comment by KiteLab** [comment]
Probably your

```
#define HOMING_FEEDRATE {50*60, 50*60, 4*60, 0}  // set the homing speeds (mm/min)
```

is set too high.

**Comment by Kriechi** [comment]
I had the very same problem with my Prusa i3 - the default speed was just too high. I reduced it to `2.5*60` and now it homes properly.

**Comment by thinkyhead** [comment]
I see this question a lot. Both the Z homing and manual feedrates need to be set to a reasonable value or the Z steppers can't handle the load.
