### ISSUE TITLE
Invert hot bed

### ISSUE THREAD

**Issue by KjellVerb** [MarlinFirmware/Marlin#2864]
Hi, I wanted to control my hotbed with a mosfet. Turns out the ebay seller sent me p-types instead of n-types, so the controls are inverted. Is it possible to invert the hot bed in marlin so that I don't have to change the hardware?

**Comment by bmarl** [comment]
Maybe just put a transistor in front of it. That way you solve it once not every time you need to update the firmware.

**Comment by KjellVerb** [comment]
There's already an opto in front, in order to isolate both power supplies. But you're right, I was just being too lazy to make a new PCB ;)
