### ISSUE TITLE
Dual Extruder Prints in wrong location after tool change

### ISSUE THREAD

**Issue by SuperSleeper** [MarlinFirmware/Marlin#2865]
Hi Folks,
New to 3D printing and not exactly sure how to word all of this as I don't have all the lingo down.  I happen to know I'm running Marlin on a Delta Mini Rockstar Q2s Pro.  Unfortunately, I don't have a reference to the version I'm running, but I downloaded it in mid October 2015 and files are dated 10/21/2015.  Unfortunately the notes section of the Marlin.ino file contains no version specific information.

Issue I'm having is only when executing code for both extruders.  I can print perfectly fine with either extruder alone without issue, it just tends to go off to lalaland (reverses Z axis) and print in the air only after switching between extruders.  If I pause the print and re-home the printer, it will then start printing on the second extruder where it's supposed to.

I'm using Repetier Host, and after running Slic3r, I see both filaments aligning properly in the print preview.  Therefore, it leads me to believe there must be some firmware issue.

Thanks in advance for ANY direction here.

**Comment by docpayce** [comment]
I cant find your printer online, can you give a source on it? Is it this one? http://www.geeetech.com/wiki/index.php/File:Dual_extruder.jpg

In the meantime, pls check your Extruder settings in Slic3r: Switch to expert settings, printer tab and check the first and second extruder offsets. Also, did you try another Slicer? Kisslicer for instance?

Also, you could try to change TOOLCHANGE_PARK_ZLIFT and TOOLCHANGE_UNPARK_ZLIFT in configuration_adv.h. Set them to 0. I dont _think_ thats the problem tho.

**Comment by Roxy-3D** [comment]
@SuperSleeper  Can you move your Configuration.h file over to the current Release Candidate (RC-3) and try it there?   If it happens there, it will get fixed ASAP.

**Comment by SuperSleeper** [comment]
Thanks for the tip, I was considering testing RC-3.  I'll test it and let
you know.

On Sun, Jan 3, 2016 at 5:54 PM, Roxy-3DPrintBoard notifications@github.com
wrote:

> @SuperSleeper https://github.com/SuperSleeper Can you move your
> Configuration.h file over to the current Release Candidate (RC-3) and try
> it there? If it happens there, it will get fixed ASAP.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/2865#issuecomment-168564615
> .

## 

Eric

**Comment by thinkyhead** [comment]
Hi @SuperSleeper, is this still an issue for you? We're working a new release candidate and want to make sure bugs are being fixed.

**Comment by SuperSleeper** [comment]
Thanks for the follow up. My PC was offline for a while and hadn't had a
chance yet to upload the new firmware.

On Friday, March 11, 2016, Scott Lahteine notifications@github.com wrote:

> Hi @SuperSleeper https://github.com/SuperSleeper, is this still an
> issue for you? We're working a new release candidate and want to make sure
> bugs are being fixed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/2865#issuecomment-195380454
> .

## 

Eric

**Comment by thinkyhead** [comment]
Sorry we didn't get this followed up in time for RC4, but give that new release a try when you get a chance. https://github.com/MarlinFirmware/Marlin/releases

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
