### ISSUE TITLE
How to configure RRD Fan Extender with RAMPS 1.4?

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#2866]
How to configure with ramps 1.4 EEB board selected for use rrd fan extender as fan layer.

**Comment by KiteLab** [comment]
https://github.com/MarlinFirmware/MarlinDev/issues/284

**Comment by ghost** [comment]
i read all thread and no solution with marlin 1.02 or 1.1.0 rc2... with m42 p6 or p11 s0 or 255 nothings happend..
always on

**Comment by thinkyhead** [comment]
@erteclas Did you have any luck? I haven't read this yet, but check out this Instructables article on [Configuring and using a RepRap RAMPS 1.4 RRD Fan Extender with Marlin](http://www.instructables.com/id/Configuring-and-using-Reprap-Ramps14-RRD-Fan-Exten/)

Let me know if you need any help integrating the code from the article with the newer Marlin.

**Comment by SrGeek** [comment]
The article helps explains how to setup the RRD fan so that the fans turn on after the hotend or any other component of your choice reaches a designated temperature.  However you cannot control the fan with the 12864 LCD reprapdiscount smart controller or repetier host.  Unless you manually enter speed commands in gcode.

**Comment by thinkyhead** [comment]
That is correct. Extruder Auto Fans are only automatic, and intended for cooling the hot end above the heat break. They are not the same as the GCode-controlled PWM fans which are intended to cool the printed object, the speeds of which are set through your slicer options.

If you want to use your RRD fan as a GCode-controlled PWM fan, you will need to set its pin as one of the PWM fan pins: `FAN_PIN`, `FAN1_PIN`, etc. You can probably assign both `EXTRUDER_0_AUTO_FAN_PIN` and `FAN_PIN` to the same pin without anything blowing up, but the sanity check currently throws an error if you try to do this.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
