### ISSUE TITLE
Anormal change of engine speed

### ISSUE THREAD

**Issue by htaxil** [MarlinFirmware/Marlin#2870]
Hi, I'm using Marlin RC 1.1.0 RC2 with my Delta printer. I notice a problem of change of regime of engines during the ascents and the descents of carriers. I think hiccups (short fall of regime) occur at regular intervals. Listen to the audio track of this video. As you will see, the problem changes according to the speed of movement of the carriages: https://youtu.be/l0B-ooFcSps

I upgraded to Marlin RC 1.1.0 RC3, but it has not solved anything.
I thought of a hardware problem, so I changed the electronics (Arduino, Ramps card and stepper drivers) unsuccessfully. I tried different intensity settings for the motors without success.
So I suspect a software problem ... any idea ?

**Comment by htaxil** [comment]
nobody has an idea ?

**Comment by KiteLab** [comment]
Lots off ideas here. But all pure speculation without more data about your configuration.
The about 1Hz rhythm lets me suppose a full graphic controller with 8 stripe refresh, like a VIKI2.

**Comment by htaxil** [comment]
Many thanks for your answer. You're right, if I disable the LCD, the problem disappears.
Is there any solution? I do not find by browsing the issues list.

**Comment by KiteLab** [comment]
Dispaytype?

**Comment by htaxil** [comment]
I'm using a REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by KiteLab** [comment]
Hmm, that's already the most optimized driver (needs only two stripes).
Maybe you can reduce the load by decreasing DELTA_SEGMENTS_PER_SECOND,
or a lower micro step setting.

**Comment by htaxil** [comment]
Oh, that is not a good news.
I decreased DELTA_SEGMENTS_PER_SECOND, passing from 200 to 100. This greatly improves things, but I still have hiccups while printing curves. I will further decrease a bit, but I hope it will not degrade a print quality . I am very surprised ( and disappointed ) by this issue especially since you seem to say that this is one of the most optimized drivers. It might cause problems to many people.

**Comment by AnHardt** [comment]
@htaxil 
Maybe you are interested in some graphic display speedup.
https://github.com/AnHardt/Marlin/pull/13

**Comment by thinkyhead** [comment]
A Graphical Display plus Delta calculation pushes the limits of modest AVR boards. The only way to make a computer "go faster" is actually to make it do less. So I suggest checking out the work at https://github.com/AnHardt/Marlin/pull/13
