### ISSUE TITLE
Unclear explanation of config line

### ISSUE THREAD

**Issue by frank16** [MarlinFirmware/Marlin#2874]
I'm trying to understand why the 'default acceleration' and 'travel acceleration' lines only contain one combined? value while they would clearly be different for the z and e axes.
So, I would say these values are for x and y (and thus the explanation is strange?) or they are supposed to be for x,y,z,e in which case some code seems to be missing (it does not compile for an array).
This from Configuration.h

``` cpp
#define DEFAULT_AXIS_STEPS_PER_UNIT   {80,80,4000,500}  // default steps per unit for Ultimaker
#define DEFAULT_MAX_FEEDRATE          {300, 300, 5, 25}    // (mm/sec)
#define DEFAULT_MAX_ACCELERATION      {3000,3000,100,10000}    // X, Y, Z, E maximum start speed for accelerated moves. E default values are good for Skeinforge 40+, for older versions raise them a lot.

#define DEFAULT_ACCELERATION          3000    // X, Y, Z and E acceleration in mm/s^2 for printing moves
#define DEFAULT_RETRACT_ACCELERATION  3000    // E acceleration in mm/s^2 for retracts
#define DEFAULT_TRAVEL_ACCELERATION   3000    // X, Y, Z acceleration in mm/s^2 for travel (non printing) moves
```

**Comment by thinkyhead** [comment]
Sorry this topic hasn't been answered until now. I went away for a while and the nice people who used to hang around and help clear issues have not been around either.
- Z moves are usually too small and slow to require acceleration, generally start at full speed.
- E moves are also too small and slow to accelerate. (Extrude while not moving XY much?)
- So `DEFAULT_ACCELERATION` is basically XY acceleration when extruding.
- And `DEFAULT_TRAVEL_ACCELERATION` is basically XY acceleration when not extruding.

The main reason to make these different is to get smoother acceleration while extruding – or while traveling. Some slicers produce a lot of extra travel moves (Cura can be configured to only travel over perimeters, for example), while other slicers produce only single travel move between each group of printing moves. So depending on how you use the machine, you might change one or the other to get a better "feel" or result.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
