### ISSUE TITLE
language.h M115 Report doesn't use MACHINE_UUID from configuration.h

### ISSUE THREAD

**Issue by RalphSutherland** [MarlinFirmware/Marlin#2879]
Setting 'MACHINE_UUID' in configuration.h doesn't appear in the M115 Report message in language.h.  The language.h file uses just 'UUID'.  I changed my repo to use MACHINE_UUID in language.h and tried a pull request, but didn't get permission.  Anyway it is a simple fix and the printer UUID shows properly on startup etc.

**Comment by thinkyhead** [comment]
Thanks! I've got patches pending for both `RCBugFix` and `dev` so this is all set.
