### ISSUE TITLE
New Board for list

### ISSUE THREAD

**Issue by Tong6998** [MarlinFirmware/Marlin#2881]
Don't know how to add it so here's the info needed:

MKS v1.3/1.4 also

Board is identical to a RAMPs 1.4  except pin assignment is as follows:  
D8  : Bed
D9  : Part Fan <--- always that, no mater what 
D10: E0
D7  : E1 <---- this is now on it's own pin so that the fan can be also used

To make this work for the time being here's what I did:

Configuration.h
# define MOTHERBOARD BOARD_RAMPS_13_EEB

in pins_RAMPS_13.h changed the following:
 line 86 : #if MB(RAMPS_13_EFF)  to  #if MB(RAMPS_13_EEB)

This forces it to use the my board assignment from configuration.h (I know I know this is cheap and cheating but it's all i could come up with)

I left it's pin assignment alone below the previous : 
# define FAN_PIN           9

also in pins_RAMPS_13.h Changed the following:
# define HEATER_1_PIN      9  to  #define HEATER_1_PIN      7

Fully works.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
