### ISSUE TITLE
"Tune" settings

### ISSUE THREAD

**Issue by lome64** [MarlinFirmware/Marlin#2884]
Choosing "Tune" during print only works for setting the Speed.
Any other selection (Nozzle, Bed, Fanspeed) brings up the "Flow" setting, which cannot be edited.
The call of nozzle_bed_fan_menu_items (...) seems to work not as expected.

**Comment by KiteLab** [comment]
Already fixed in RCBugFix. (https://github.com/MarlinFirmware/Marlin/commit/60d5658da89d7d59d00ee7d940fd96172d8934f9)

**Comment by lome64** [comment]
Thank's haven't seen that.
