### ISSUE TITLE
SilentStepStick Drivers on Rumba Board do not Work with 1.1.x

### ISSUE THREAD

**Issue by crustrock** [MarlinFirmware/Marlin#2887]
In 1.0.2-1 they work as expected, but with the new Release Candidates the motors are just "blocking".
Can provide more information if needed.

**Comment by thinkyhead** [comment]
Hi @crustrock. Sorry your request has been sitting around for so long without a reply.

Is this still an issue with the current `RCBugFix`? I'm hoping we can get all extant issues cleared up and do a new release candidate soon, so it would be good to know if this still needs to be patched.

I look forward to figuring out this one, if it hasn't been patched already!

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
