### ISSUE TITLE
Does Marlin works for PortabeeGo printer?

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#2894]
Any tips on how to use Marlin firmware on a Portabee Go printer would be greatly apprecitated. Thanks in advance!

**Comment by ntoff** [comment]
scroll to the bottom of the documentation http://portabee3dprinter.com/support/portabee-kit-docs/

**Comment by pauloguerraf** [comment]
Thank you! I have seen the documentation before, but was not sure if the PortabeeGO uses the same board as the Portabee 3D Printer Kit. Can both printers use the same firmware or is there any configuration detail that I should take into account?

**Comment by ghost** [comment]
Thank you! I have seen the documentation before, but was not sure if the PortabeeGO uses the same board as the Portabee 3D Printer Kit. Can both printers use the same firmware or is there any configuration detail that I should take into account? Once again, thank you for your help.

**Comment by thinkyhead** [comment]
Is the latest version of Marlin (`RCBugFix`) any more helpful with the PortabeeGo? I know we don't support this machine in any formal way, but maybe it's easier to set up now. Would it help if we integrated the changes proposed at http://portabee3dprinter.com/support/portabee-kit-docs/#k8 ?

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
