### ISSUE TITLE
Syntax in Marlin_main.cpp

### ISSUE THREAD

**Issue by dmummert** [MarlinFirmware/Marlin#2900]
# ifdef ULTIPANEL

```
    powersupply = false;
```

line 2669        LCD_MESSAGEPGM(MACHINE_NAME" "MSG_OFF".");
        lcd_update();                                                          

generates C++11 syntax error.  There should be a space.  MACHINE_NAME" " MSG_OFF"."

**Comment by KiteLab** [comment]
Already corrected in RC (https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/Marlin_main.cpp)
