### ISSUE TITLE
Clicking LCD menu for Nozzle goes to flow, cannot exit

### ISSUE THREAD

**Issue by thehans** [MarlinFirmware/Marlin#2905]
I started a print from SD, using reprapdiscount smart controller.  While waiting for the bed and nozzle to get up to temperature, I tried to adjust the nozzle target temp.  When I click Tune -> Nozzle, it takes me to "Flow" adjustment instead.  I try to click to set at 100, so I can return to the menu, and it stays on the Flow setting and the value changes to 10.  Then any further clicks won't take me back to the menu, I have to reset RAMPS to get out of Flow adjust.  This is using RC3

**Comment by KiteLab** [comment]
Already fixed in RcBugFix at  4 Dec 2015 with https://github.com/MarlinFirmware/Marlin/pull/2823
