### ISSUE TITLE
New controller card: MPX.3 arduino/RAMPS mashup single card pins.h

### ISSUE THREAD

**Issue by RalphSutherland** [MarlinFirmware/Marlin#2906]
I have a chinese single board, a Arduino Mega2560/RAMPS with 4988 stepper drivers mashup called an MPX.3.  The main difference is a fourth power MOSFET pin in addition to the normal three.  I have made a pins_MPX3.h for a ramps compatible and the following power pins and it seems to run fine.

``` cpp
/**
 * MPX-3 with RAMPS v1.4 pin assignments EEB + fan
 *
 *  ie RAMPS_14_EBFE (Extruder, Bed, Fan, Extruder)
 */

#define IS_RAMPS_EEB

#include "pins_RAMPS_13.h"

#undef HEATER_BED_PIN
#define HEATER_BED_PIN    8    // BED

#undef FAN_PIN
#define FAN_PIN           9    // FAN

#undef HEATER_0_PIN
#define HEATER_0_PIN     10    // E0

#undef HEATER_1_PIN
#define HEATER_1_PIN      7    // E1
```

**Comment by KiteLab** [comment]
Do you have a link to the product?

**Comment by RalphSutherland** [comment]
http://www.maxmicron.com/index.php?route=product/product&product_id=52  the dual extruder model is the only one I have seen, no idea if their other single E models use the same card.   I'll take  a closeup photo of the board and make a URL for it soon.  It is that single red board in the background of some of the photos.  It came with a version of marlin 1.0.0 already installed.

Here is a shot of the board, you can see the four mosfets on the right .

http://postimg.org/image/vht0rh6wh/

**Comment by thinkyhead** [comment]
I'll put this on my to-do list for `dev` and perhaps we can toss it into `RCBugFix` as well since it's both obscure and in need of wider testing. Just recently we properly assigned most boards as derivatives of RAMPS 1.4 instead of 1.3. This MPX.3 is probably also RAMPS 1.4. (The `SERVO_0_PIN` is the only difference.)

Incidentally do you have `Configuration.h` and `Configuration_adv.h` for the machine that this board comes with?

**Comment by MikeInMinnesota** [comment]
I also have this MPX.3 board.  It seems to be the same as a HICTOP controller.  I've been running it as a RAMPS 1.4, with basically Ralph's EBFE configuration.  My board came as the controller for a dual head Max Micron printer.  Attached are my Configuration.h and Configuration_adv.h for the board.  My configuration has auto bed leveling, which is an option for the Max Micron.  I'm currently running RC6.

[MPX.3-configuration.zip](https://github.com/MarlinFirmware/Marlin/files/239745/MPX.3-configuration.zip)

**Comment by thinkyhead** [comment]
The pins listed in the original post are identical to the `MKS_BASE` pins, actually. So I think we should just make a note in the `boards.h` file that the HICTOP `MKS_BASE` also applies to MPX.3.

http://www.amazon.com/HICTOP-Printer-Control-RepRap-Arduino-compatible/dp/B015W7PWRG

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.

**Comment by MikeInMinnesota** [comment]
Yes, I'm very much looking forward to the 1.1 release.

My comment about the issue was more towards the configuration issue for different printers.  I believe the controller itself should work as a stock 1.4 board, and indeed that is how I have been using it.  I am unaware of the status for providing a tool for adjusting the configuration.h and Configuration_adv.h parameters.  I understand Thinkyhead was working on this a while back.  Do you have any further information about this effort?   

Regards,
Mike

**Comment by thinkyhead** [comment]
@MikeInMinnesota A friendlier configuration tool is in the planning stage, but so far not built. In the meantime I'm continuing to work on a more complete (advanced mode) configuration tool at https://github.com/thinkyhead/MarlinConfigurator – which needs code updates to deal with the latest config files, and to make it smarter as well.

I'd also like to make a barebones drag-and-drop Javascript web page to simply convert old configs into new ones, but that requires a pile of specifics to do the conversion.

**Comment by jasonb194** [comment]
I actually got HIC to send me the source files for their Marlin Set up for the MPX.3

Their config has the board set up as a 33. I can send you any of the files if you want to see them.

**Comment by RalphSutherland** [comment]
HI, 

Not a problem.  I am fine, and adding aux and servo boards anyway so non-standard now anyway. 

R

Dr Ralph Sutherland
Research School of Astronomy and Astrophysics
Australian National University

**Comment by Blade893** [comment]
Hi jasonb194, can you please send me your HIC source files?

**Comment by Fever2112** [comment]
@jasonb194 Can you send me the source files?   I have this board but the language is not English... I would like to reprogram the menus or get one that is the right language.

**Comment by probonopd** [comment]
@jasonb194 best would be to upload the source files to a GitHub repository. I suspect the Renkforce RF100 from Conrad Electronic is using this board too.

**Comment by Fever2112** [comment]
Is the firmware from HIC any different that the Marlin kit at marlinfw.org?  Does the MarlinFW 1.0.x run on this MPX.3 board?

**Comment by Fever2112** [comment]
and yes, please upload the files if/when you are able.
  :)

**Comment by jasonb194** [comment]
Below is the firmware that HICTOP sent me for the MPX.3 board.

It's the normal Marlin Firmware, but different settings. Its actually an old build, but you can port the setting over to the most current Marlin release.
[Marlin_3DP08_3DP11_398.zip](https://github.com/MarlinFirmware/Marlin/files/722293/Marlin_3DP08_3DP11_398.zip)

**Comment by probonopd** [comment]
Does anyone know where the serial port is located on the MPX.3? Is there a pinout? Does it provide 3.3V or 5V somewhere that would be sufficient to hook up a ESP8266? I would like to use https://github.com/luc-github/ESP3D with it to turn it into a WLAN-enabled board.

**Comment by probonopd** [comment]
> Does anyone know where the serial port is located on the MPX.3? 

Turns out on the AUX-1 header, same as for the RAMPS board. There is also 5V.

**Comment by ronenst1** [comment]
Does anyone know how can I connect the BLtouch sensor to the MPX.3 board? I need to use the servo output to raise the BLtouch pin.

**Comment by MikeInMinnesota** [comment]
You use D11 by the S1 button for the servo connection (3 pin) and the Z- end stop that is almost next to that for the bltouch 2 pin connector.  The Z- stop touches the EXP2 connector that goes to the display.  If we call the EXP2 connector the top right corner, then the vertical pin assignment on the servo is (top to bottom) 5V, GND, D11.  You only use 2 pins of the Z- stop.  The middle pin is GND and the bottom pin is the Z MIN signal.

You also need to rebuild the Marlin firmware.  I’d suggest RC8.

**Comment by enter801** [comment]
Also should mention that if you have your firmware set up with RAMPS 1.3 as the board (33), then it will re-assign the servo pin to 7.  Needs to be 11 in the firmware, so setting it as RAMPS 1.4 EFB  instead of 1.3 EFB should do the trick.  Just about to test as my BLTOUCH isn't responding, as I'm sure it's set to pin 7 instead of 11 (but hooked up to 11).

**Comment by ronenst1** [comment]
Thank you all. I will try it this week.

**Comment by ronenst1** [comment]
![maxmicron board mpx pro v3 0](https://cloud.githubusercontent.com/assets/18489561/23372766/b2ed5ae0-fd25-11e6-96d0-9c869a976472.jpg)
Mike thanks again but unfortunately my board printer (Max Micron dual head including Auto-Leveling) in the same as the HICTOP board but without that specific D11 connectors.
I can see that the name of the board is MPX PRO V3.0
Mike do you have any suggestions?

**Comment by MikeInMinnesota** [comment]
That’s a good question.  It sounds like Max Micron has a slightly changed version of the MPX 3, maybe via HICTOP.  If nothing on the board is labeled D11 then the controller has been re-worked in their latest version.  I’d suggest contacting Max Micron’s  support at maxmicron@hotmail.com<mailto:maxmicron@hotmail.com>.  I don’t know if he’s still there, but they had a pretty knowledgeable guy named ZhaoMonster that was helpful for some of my previous questions about connecting sensors to various end-stops.

Regards,
Mike

**Comment by ronenst1** [comment]
Thanks Mike I will try Zhao

**Comment by robertch1969** [comment]
has anyone ended up getting a new marlin version for this board working ?\

i have the board on [this machine](https://www.aliexpress.com/item/New-3D-Printer-Large-Build-Size-ET-I3-3D-Printer-with-Dual-Extruder-Touch-Screen-and/32763624787.html?spm=2114.01010208.3.1.HrI6ZU&ws_ab_test=searchweb0_0%2Csearchweb201602_5_10065_10068_10501_10000074_10503_10000032_119_10000025_10000029_430_10000028_10060_10000067_10062_10056_10055_10000062_10054_301_10059_10099_10000022_10000013_10103_10102_10000016_10096_10000018_10000019_10000056_10000059_10052_10053_10107_10050_10106_10051_10000053_10000007_10000050_10084_10083_10000047_10080_10082_10081_10110_10111_10112_10113_10114_10115_10000041_10000044_10078_10079_10000038_10073_10000035_10121-10503_10501%2Csearchweb201603_7%2Cafswitch_4%2Csingle_sort_2_default&btsid=937ee225-c7e7-4ea7-8c74-b56fb25cd920) and am trying to install a BLtouch on it have tried to make a few different versions of marlin for it myself but am not sure how to do this so been reading and trying different things closest i have got is new firmware runs but axises are very erratic things they seem to be missing steps i revert to the old version of the firmware and it works fine

i have the source file for the original firmware i think it is 1.0.0 RC2

i want to achieve 2 things get a new more recent version of Marlin for my board and get the Bltouch connected and working

**Comment by enter801** [comment]
I have the BLToich working on this board with RC8 firmware. You have to set it to ramps 1.4 as the board in the firmware then plug the three pin cable into that. If you don't have headers on D11 then you should get some JST three pin male and female plugs. You can get those on Amazon, a whole box with all sizes for cheap. You have to set up the servo and a few other things. I can send you my config and config advanced files. The BLTouch is amazing btw. Way way better than the inductive sensor. Do yourself a favor and put a PEI/Ultem sheet on your bed. No need for glass or glue or tape after that. Can print ABS without warping without an enclosure.  The BLTouch is awesome for that because it will get accurate bed leveling done on an uneven bed, which you can get with the PEI sheet being installed poorly (double sided 3m glue) like I did.

**Comment by robertch1969** [comment]
yeah @enter801 have the PEI sheet i can get the bltouch to move but something is going wrong with the printer movement with the new firmware i am missing something i think pretty new to this so here is the whole source
[双200x280.zip](https://github.com/MarlinFirmware/Marlin/files/856747/200x280.zip)
 file 

would be great if you could send the files may get me a little closer to getting it fully working

**Comment by robertch1969** [comment]
so update here have played with the config h have y and z moving normally and BLtouch responding to basic test commands but x just makes a noise but no movement re flash with old firmware all axis move as expected but cant get BL touch to work with it

**Comment by enter801** [comment]
Here are my RC8 configuration files.  I have an e3d hot end set up as well, so you will have to match it for that, and for the bed size, offsets for where you have the BLTouch mounted with respect to the hotend.  Another thing you will have to do is figure out what your z offset is.  My firmware has the homing distance set to 5mm, so you can go down 5 mm, and then whatever past 5mm it requires to get the hotend 100 microns away(sheet of paper height) from the bed is your z offset.  You can change it in the firmware config (I believe mine is set to -1.5 in the firmware) or override it with the z offset gcode command.
[MarlinRC8_BLTouch_MPX3_Board_enter801.zip](https://github.com/MarlinFirmware/Marlin/files/857595/MarlinRC8_BLTouch_MPX3_Board_enter801.zip)

**Comment by robertch1969** [comment]
thank you very much for this  will give that a go i dont know what i am doing wrong but my x axis doesn't like it when i configure for BL Touch is the Pic here how you wired the BL touch to your board ?
![image](https://cloud.githubusercontent.com/assets/26557532/24142887/b62117ce-0e73-11e7-8187-72089bf4d313.png) my board has a slightly different number on it it is AS 1630

**Comment by enter801** [comment]
So your servo wiring  is off.  Look at my config on how the servo is set up in the firmware.  Take your equivalent values over to RC8 that are specific to your machine, then merge my settings for the servo and BLTouch.  The wiring should be signal, 5v, then ground, signal on the inside pin of d11, 5v in middle, ground on outside pin.  So make sure you're using all 5 wires on it.  
Also, if your old firmware is working on the x-axis, and then it doesn't when you change firmware, look at the differences between the two.  Use a diff program like Beyond Compare.

**Comment by robertch1969** [comment]
thanks @enter801 pretty new at this loving my printer but i am not a software guy and dont know a lot about the electronics would you be interested in doing a firmware for me for some $$

**Comment by enter801** [comment]
Make sure you have RAMPS 1.4 selected as well, the stock firmware from Hictop has it on 1.3, which puts D11 on some other input.

**Comment by robertch1969** [comment]
@enter801  yeah have it on 1.4 but still no joy will keep trying

**Comment by ronenst1** [comment]
Thanks to all, I uploaded the new Marlin version after updating the configuration.h files and install the BLTouch on my printer. It is working perfectly with dual head. 
Link to my dual head design.
https://www.thingiverse.com/thing:2161827

**Comment by probonopd** [comment]
@enter801 since the BLTouch is relatively pricey, do you think a __LJC18A3__ would work too on this board?

**Comment by ronenst1** [comment]
I have tried the *LJC18A3*  and it is working fine but the performance of
the BLTouch is far away better and it is worth the price.

*Stolarski Ronen*

*System Engineer*

*Camon, Migdal Hamaym 5 street*

*Camon 20112*

*Israel*

*Tel: : 972-4-9883429*

*Cell: : 972-52-3793279*

BMW R1200GS 2005
