### ISSUE TITLE
Remove HEATER_BED_DUTY_CYCLE_DIVIDER from Configuration.h

### ISSUE THREAD

**Issue by Kriechi** [MarlinFirmware/Marlin#2908]
The setting `HEATER_BED_DUTY_CYCLE_DIVIDER` is actually no where to be found in the code.
As far as I can tell it got removed in 9698f4ea649ed48ed02df4b8298aafb85d2f6c3d by the PID controlled  heated bed settings.

And I was wondering for days why changing this value didn't do anything on my printer...

**Comment by thinkyhead** [comment]
Made PRs for `dev` and `RC` to remove this option, which has been supplanted by `MAX_BED_POWER`.
