### ISSUE TITLE
REPRAP FULL SMART CART BUTTON NO WORKING

### ISSUE THREAD

**Issue by schirrel** [MarlinFirmware/Marlin#2910]
I am trying using graphic full smart cart but it doesn't work.
When i press the encoder, the button, it opens the menu and freezes, i change and put a simple button at the pin, instead of using the encoder, but in this way it doesn't even open the menu
i've done:

``` cpp
if (millis() > next_button_update_ms && READ(BTN_ENC) == 0) { 
  SERIAL_PROTOCOLLN("reading");
  newbutton |= EN_C;
  SERIAL_PROTOCOLLN("BT");
  SERIAL_PROTOCOLLN(newbutton);
}
```

but it prints a blank space.

**Comment by KiteLab** [comment]
``` cpp
uint8_t newbutton = 0;

SERIAL_PROTOCOLLN does not like uints. Cast to int

SERIAL_PROTOCOLLN((int) newbutton);
```

**Comment by schirrel** [comment]
@KiteLab i was wondering now, i'm using only the arduino and ramps, nothing is pluged so far, just for trying menu ans graphic stuff, and its giving mintemp error annd then the printer is killed, maybe this is what is freeziin the screen?
How to disable this so i can work without the termistor plugged?

**Comment by KiteLab** [comment]
Use fake sensors 999 or 998.

But the display should be initialized before the temperature is checked the first time.
On a 'normal' REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER i can see this errors.

But of cause, when kill() is called no button will work.

**Comment by schirrel** [comment]
@KiteLab in this case i'm using a normal controller, i will try the fake sensor thanks

**Comment by KiteLab** [comment]
Not the pins! The sensor type.

**Comment by schirrel** [comment]
I saw now ^~^
