### ISSUE TITLE
When no parameters specified for M226, wait for LCD button push

### ISSUE THREAD

**Issue by MxAshUp** [MarlinFirmware/Marlin#2916]
A few other platforms specify M226 as a pause command to wait for the user. It would be pretty simple to update gcode_m226 to utilize lcd_clicked if no parameters are specified for M226.

If nobody has objections to this, I could write a PR.

**Comment by MxAshUp** [comment]
Never mind, this should be in the Marlin Dev repo

**Comment by KiteLab** [comment]
M0?
