### ISSUE TITLE
Z_RAISE_BEFORE_HOMING should happen before X and Y are homed in RcBugFix even with Z_SAFE_HOMING set

### ISSUE THREAD

**Issue by AlwaysTinkering** [MarlinFirmware/Marlin#2931]
Z_RAISE_BEFORE_HOMING is either being ignored entirely, or at least not happening until my nozzle has been drug across my print bed to the X and Y home positions.  I'm using grid auto level, and also have raise before z probe set.  Z_RAISE_BEFORE_PROBING should raise before the Z probe is performed.  Z_RAISE_BEFORE_HOMING should raise the Z before anything is homed, to avoid dragging the head and Z probe through prints, bed clips, etc.  There is no way to manually raise Z before homing.  This is especially problematic if the bed has been moved so that the head is out of proper bed range, and the path to X and Y home is not unobstructed.

The Z_RAISE_BEFORE_HOMING define is useless if it's behavior is no different from Z_RAISE_BEFORE_PROBING.

**Comment by ghpicard** [comment]
A simple workaround is to include a G1 Z15 (or whatever fits your machine) before G28 in the start gcode of your slicer.

**Comment by woferry** [comment]
There are workarounds, yes.  But the code doesn't seem to be working as intended, given that the feature name is "BEFORE_HOMING" and yet it doesn't happen before homing (I have the same issue on my Robo3D R1 which sets this option).

**Comment by AlwaysTinkering** [comment]
In the current RcBugFix branch, if Z_SAFE_HOMING is enabled, then Z_RAISE_BEFORE_HOMING does not occur before X and Y are homed.  It will only work if Z_SAFE_HOMING is disabled.

There needs to be a way to gain the benefit of Z_SAFE_HOMING (not homing out of bounds, etc.) but still raise Z before X and Y.

A simple change to this line removing the Z_SAFE_HOMING test would correct the issue:
`#elif DISABLED(Z_SAFE_HOMING) && defined(Z_RAISE_BEFORE_HOMING) && Z_RAISE_BEFORE_HOMING > 0`

This is line 2311 of marlin_main.cpp at the time of this posting.

**Comment by thinkyhead** [comment]
Let's move the discussion over to #3001. No need to keep two issues open.
