### ISSUE TITLE
Problem setting nozzle temperature from LCD - not the same as #2934!

### ISSUE THREAD

**Issue by zakkos** [MarlinFirmware/Marlin#2944]
Hello all!

I noticed some strange behaviour from my machine when I loaded the then latest RC version (5a54204 from 30/11). 

If I try to set the nozzle temperature from the LCD menus (either from the tune or the control sub-menus) to something more than 210° it reverts automatically to 210. 
It doesn't do that every time but every "other" time! 

I try to explain better: 
I put, let's say, 240° and it goes back down to 210. 
I then go again at 240 and it accepts this value but if I then try again to tune the nozzle temperature, say I raise it to 245, it goes back to 210°!

I tried to check in the code if I could come up with a solution but hadn't any luck.

**Comment by AnHardt** [comment]
If you are not on RCBugFix, it's not the same symptom, but the same (fixed) bug. Give it a try!

**Comment by zakkos** [comment]
@AnHardt Sorry for the late reply. Today I could finally check out the RCBugFix branch and indeed you were absolutely right. Different symptoms but same problem, sorry for the inconvenience!
