### ISSUE TITLE
Feature Request: Add a possibility to deactivate endstops on a per switch base

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#2946]
Add a description, that unused switches have to be deactivated.
Add a possibility to deactivate endstops/probes on a per switch base.

This is causing a lot of support questions.

**Comment by thinkyhead** [comment]
We have PRs for both `RCBugFix` and `dev`, so closing this.

**Comment by thinkyhead** [comment]
How is this idea working out?

**Comment by thinkyhead** [comment]
#3065 implements this idea.
