### ISSUE TITLE
Feature Request: Don't test probes when undeployed

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#2949]
Don't test probes when undeployed, else triggered when stowed (Allen Key) probes, or inductive probes near the bed, require ENDSTOPS_ONLY_FOR_HOMING.

**Comment by thinkyhead** [comment]
Are we feeling pretty confident about #3082? It looks simple, and I would like to merge it, but I'd also like to make sure it's compatible with a wide variety of configs.
