### ISSUE TITLE
Estremly slow when browsing the SD from the LCD

### ISSUE THREAD

**Issue by albertolg** [MarlinFirmware/Marlin#2964]
Using the 1.1.0RC3, reprap smart controller, it's very slow when I try to select the file to print with the encoder, there is a delay of about 1 second from when I rotate/press the encoder and the reaction of the LCD, but only when browsing the SD, in the other menus it's fine, fast and responsive... is maybe a config problem or what? I couldn't find an open issue like this

**Comment by thinkyhead** [comment]
Is this still a problem in `RCBugFix`? We've been doing a lot of work around the LCD menus and SD printing lately.

**Comment by albertolg** [comment]
Tested now, the problem is still there... :-(

**Comment by Blue-Marlin** [comment]
About how many files are in the directory?

**Comment by albertolg** [comment]
only 2. I can make a video later

here you can hear the click of the encoder and the printer that doesn't print, only after some attempts it works https://www.youtube.com/watch?v=_RVzSL6_I4A

**Comment by thinkyhead** [comment]
It sounds like potentially bad wiring. Is there no change if you tighten up the connections?

**Comment by jbrazio** [comment]
Have you tried with a different SD card ?

**Comment by albertolg** [comment]
guys... sorry... it's not a bug.... did a low level format of my 4Gb SD, loaded the files again and now it's again responsive... I don't know what happened to the SD, always used the same, we can close this issue.. thanks again and sorry :-(

**Comment by CONSULitAS** [comment]
@albertolg You are welcome.
You can (and should) close the issue yourself by just clicking "close". :smile:

**Comment by JanVelleman** [comment]
This still seems to be a recurring issue for me (graphical display and SD support). Really slow scrolling behavior in some folders and not in others. When reformatted and re-used. It's seems to be ok but deteriorates rapidly when adding a file...?
