### ISSUE TITLE
Home All & Auto Bed Leveling

### ISSUE THREAD

**Issue by brand0drag0** [MarlinFirmware/Marlin#2979]
Here's the problem I'm seeing from Marlin:

When attempting to home all axes, whether AUTO_BED_LEVELING_FEATURE is enabled or not,

on RC3:  the machine homes X, homes Y, then stops.
on RC2:  the machine homes x, homes y, then rams the bed into the head (ignores the z-sensor completely).

**Comment by brand0drag0** [comment]
I am using an Azteeg X3 PRO with CORE XY Motion.

**Comment by Blue-Marlin** [comment]
Please tell us where your endstops are and where your probe is connected.
Please send a M119 in mid air and post the result (with deployed/stowed probe).
Please give us a link to your Configuration.h, Configuration_adv.h and, if changed, pin file.

**Comment by thinkyhead** [comment]
Where does this issue stand with the current `RCBugFix`? We've made a lot of changes for CORE machines.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
