### ISSUE TITLE
SDSUPPORT not workin

### ISSUE THREAD

**Issue by schirrel** [MarlinFirmware/Marlin#2996]
I'm using sdsupport and its not workin, i changed the pins, i'm using:

> MOSI_PIN = 51; 
> MISO_PIN = 50;  
> SCK_PIN = 52; 

but it dont worked.
SO in initsd i printed the pins and its showing 

> SCK_PIN 
> 4
> MISO_PIN 
> 2
> MOSI_PIN 
> 3

**Comment by Blue-Marlin** [comment]
If that's the actual syntax of your pin file it can't work..
MOSI_PIN is not a variable.

**Comment by schirrel** [comment]
I'm using a version of marlin that is am 1.0 old version and there, in the pins.h there's a MOSI_PIN;
http://www.fpaste.org/322063/

**Comment by Blue-Marlin** [comment]
All i wanted to say is. MOSI_PIN is not a **variable** but a **define**.
MOSI_PIN = 51;
is not a working syntax. I should read
#define MOSI_PIN 51

**Comment by schirrel** [comment]
@Blue-Marlin okay i got it, but when i have used defines before in cpp and i try to print them, i could print the value. 
And in the pins.h i changed all the pins as

> #ifndef SDSUPPORT
> // these pins are defined in the SD library if building with SD support
> #define SCK_PIN           52
> #define MISO_PIN         50
> #define MOSI_PIN         51
> #endif

**Comment by thinkyhead** [comment]
My best suggestion is to use a newer version of Marlin. The latest version is currently 1.1.0-RC3. Newer versions improve SD support and fix several other issues. Configuration is pretty much the same as it was in Marlin 1.0 through 1.0.2-1, with added warnings if something is missing.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
