### ISSUE TITLE
Impossible change speed of Extrusion with the LCD Move extruder

### ISSUE THREAD

**Issue by fbarcenas** [MarlinFirmware/Marlin#3000]
Hi,
all than us than have a LCD display can go to Move->1mm (or 0.1mm) and move Extruder 1 or Extruder 2.
When i do this work and move the filament BUT, VERY EXTREME SLOW SPEED.

Where i can change this speed?

Thanks!

**Comment by thinkyhead** [comment]
In the **Configuration_adv.h** file around line 243…

``` cpp
#define MANUAL_FEEDRATE {50*60, 50*60, 4*60, 60} // Feedrates for manual moves along X, Y, Z, E from panel
```

Change the E value to something you like better, then recompile and re-flash your board. This can't be changed once it has been set in the firmware.

**Comment by fbarcenas** [comment]
Thanks thanks and thanks. 
Totally fixed/solved!
