### ISSUE TITLE
Problem uploading firmware

### ISSUE THREAD

**Issue by slarrabee99** [MarlinFirmware/Marlin#3029]
Hi,  I finished building my 3d printer yesterday and im having issues with getting it working.  I went through the tutorial to upload marlin to my ardunio and have yet to get it sucessfully working.  So far I can only read temperature of the extruder (using pronterface) but have not been able to get the printer to move or heat up at all.  please help me i would very very appreciate it  Error from arduino below v

In file included from sketch\Marlin.h:23:0,

```
             from sketch\thermistortables.h:4,

             from sketch\Configuration.h:811,

             from C:\Users\Steve\Desktop\gMax 1-5 PLUS SINGLE firmware\Marlin\Marlin.ino:33:
```

sketch\pins.h:667:0: warning: "FAN_PIN" redefined [enabled by default]

```
 #define FAN_PIN            8
```

 ^

sketch\pins.h:663:0: note: this is the location of the previous definition

```
 #define FAN_PIN            4 // IO pin. Buffer needed
```

 ^

**Comment by Blue-Marlin** [comment]
Our current pin.h files have not so large line numbers.
You are using a at least one year old version of MarlinFirmware/Marlin or a completely different fork.
To help you, we need a **link** to your actual (throwing this error) Configuration.h Configuration_adv.h and pins.h.
We'd be happy if you could change to one of our recent versions. (RCBugFix)

**Comment by paulusjacobus** [comment]
also a current first mistake is that people think the motors directly run
when you push the arrow buttons in Pronterface. You need to home the
printer first so it knows its coordinates. Without that it refuses to move.
In pronterface you can push the home buttons or issue a home command "G28".

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
