### ISSUE TITLE
can't get the correct file name of SD card

### ISSUE THREAD

**Issue by drinkingcode** [MarlinFirmware/Marlin#3033]
for example, the correct file name of SD card is "quick-test.gcode" ,but i get the file name is "QUICK-~1.GCO" , so what it happened , do you meet the same problem ?

**Comment by drinkingcode** [comment]
the answer is to update the Marlin fireware and use the command of "M33"

for example:
     \*   M33 miscel~1/armchair/armcha~1.gco
     *
     \* Output:
     \*   /Miscellaneous/Armchair/Armchair.gcode
     */

**Comment by jbrazio** [comment]
Could this be related with #3039 ?

**Comment by HedronUser** [comment]
When I update the firmware I lose advanced delta geometry control....

**Comment by thinkyhead** [comment]
> the answer is to update the Marlin fireware and use the command of "M33"

Yes, long filename support was added through a new code `M33`, which I implemented (yes, it's my fault) as a way to request a long name if you needed one. I assumed host software would begin to use it for fancy file listings of SD cards, but so far none has.

If you're going to get one of the new release candidates, be sure to get `RCBugFix` so you can avoid some filename bugs that have recently been patched.

> When I update the firmware I lose advanced delta geometry control

@HedronUser Have you opened an issue about that subject? Delta features are a little in flux right now also.

**Comment by drinkingcode** [comment]
when i enable `LONG_FILENAME_HOST_SUPPORT` and  enter `M33 QUICK-~1.GCO` , but i get the answer is `/???` ; is there anyone to help me ?

**Comment by thinkyhead** [comment]
@WillSmithInChina When you use `M33` I believe you must use lowercase for the file name: `M33 quick-~1.gco` This will be patched in the future.

**Comment by drinkingcode** [comment]
@thinkyhead  thanks, it solved my problem as the firmware neees to update
