### ISSUE TITLE
need to add comment in the code 1.1 rc3

### ISSUE THREAD

**Issue by jfpion** [MarlinFirmware/Marlin#3035]
Hello,
I know it is obvious for the advanced user but i banged my head for a long time before finding the solution in the issues answer.

I suggest to add " // if you are not using max endstop you MUST uncomment this line " just before : 
# define DISABLE_MAX_ENDSTOPS

because without the autolevel it works fine, so no need to bother about it, when you try to add the autoleving feature nothing works !

and I suggest this line should be uncomented by default so the only one who comment it will be the one using z max endstop, and then avoiding head scratching time in front of the computer

thank you

**Comment by Blue-Marlin** [comment]
That's not a good idea because there are lots of machines out there with x/y-max endstops.
All their owners would be a bit sad if we'd crash their machines by default.

**Comment by jfpion** [comment]
OK then, so adding then warning in the code seems the better solution

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
