### ISSUE TITLE
panic button ? is there a way to have one ?

### ISSUE THREAD

**Issue by jfpion** [MarlinFirmware/Marlin#3036]
hello, 

During my try of the autolevel, i got multiple occasion to have to switch off the printer to avoid to crash the head on the bed .

I think it could be useful to have a panic button stopping all the movement and ending the execution of the gcode immediatly not waiting for the buffer to empty. just not a way to stop a print to be able to resume after, but a kill switch to abort to preserve the printer. (sometime you have other ting connected to the power supply so you can't simply switch off the main power

may be it is already existing but i have'nt found it anywhere

thank you

**Comment by Blue-Marlin** [comment]
For many displays/panels **the** extra button is implemented as kill-switch.
Almost all boars have a reset button. Just solder a extra switch in parallel.
I have big red panic buttons to switch off 12V (simple hardware).

**Comment by jfpion** [comment]
the pb with the reset button is it is a reset, and when the bord reboot it get other gcode and go on...
switching off the power need a switch with a lot current capacity and I will like to avoid invisible bad contacts , a sure recipe for headhache in case of pb 
and I hanv' nt a panel, 

is the M112 gcode buffered ? if not it will do otherwise it is useless

thank you

**Comment by brainscan** [comment]
I've always just pressed reset on the board without any problems.

**Comment by Blue-Marlin** [comment]
Look for `KILL_PIN` in your pin file. Define one outside a panel/display. Connect a closing button switch to GND. Be happy.

It's not obvious but i meant switching off the primary side of the 12V power supply.

`M112` is applied as soon it leaves the RX buffer. If that is blocked, for example by a `M190`, this can take a while.

**Comment by jfpion** [comment]
OK  thank you

**Comment by thinkyhead** [comment]
@Blue-Marlin It's "meant" not "mend." :grinning: No idea about the etymology on that one.

**Comment by Blue-Marlin** [comment]
Ups.
Learning Marlin is by far easier than learning correct English for me. ;-)

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
