### ISSUE TITLE
1.1rc3 mesh bed leveling , why only manual ?

### ISSUE THREAD

**Issue by jfpion** [MarlinFirmware/Marlin#3037]
May be I missed something, but is there a way to use the mesh leveling the same the G29 ? and is there somewhere a list of all the new feature and the way to use it ?

thank you a lot

**Comment by jbrazio** [comment]
Have a look [here](https://github.com/MarlinFirmware/Marlin/wiki/Mesh-Bed-Leveling).

**Comment by jfpion** [comment]
thank you
