### ISSUE TITLE
Who assigns board and thermistor IDs ?

### ISSUE THREAD

**Issue by jbrazio** [MarlinFirmware/Marlin#3038]
This is not a issue but actually it is a question, what is the rule to assign a new board ID so a new pinout file can be created ? The same question applies to a new thermistor compensation table ID.
If there is not a rule defined, who is the "authority" to assign the IDs ?
Or can I just select the next "free" number ?

Thanks
-jbo

**Comment by Blue-Marlin** [comment]
For temperature measurement devices the rule is to use analogue devices with a positive number and others with negative. PTs with high numbers. For a new thermistor continuing with 14 is not a bad idea. An alternate table for a already existent or very similar thermistor could have the old number postfixed by 1 (2,3,...)

The boards used to be grouped by 'families'. But as this is already a bit messed up the numbering is a bit random. 

There is no authority to assign the numbers.
thermistortables.h is authoritative for the thermistors (temperature measurement devices).
boards.h is authoritative for the boards.

If you are polite you add your changes to the Configuration.h's or the Makefile.

**Comment by jbrazio** [comment]
Great, thanks.
