### ISSUE TITLE
Tune printjob nozzle or bed temp jumps to Flow on selection

### ISSUE THREAD

**Issue by hexxter** [MarlinFirmware/Marlin#3042]
If i will tune my Printjob and go to the menu item nozzle1/2 or bed then it jumps to flow after selection.

CoreXY / RAMPS 1.4 / Marlin 1.1.0 RC3

**Comment by hexxter** [comment]
sorry its the same issue as #2934

**Comment by thinkyhead** [comment]
I believe this is now patched in RCBugFix and will be good in RC4.
