### ISSUE TITLE
E0 and E1 different FR

### ISSUE THREAD

**Issue by hexxter** [MarlinFirmware/Marlin#3048]
Fist HW: RAMPS 1.4 / DRV8825
SW: Marlin 1.1.0 RCBugfix
Board settings EEB

The E0 has the right speed from config but E1 drive too fast.
If i change the HW (E0 <> E1) the Problem is only on E1.
If i change the PINs in Marlin  E0 is after this change too fast and E1 is good.

**Comment by Blue-Marlin** [comment]
If your extruders need different steps/unit, change the tool (T0/T1) and set the needed steps/unit explicitly with M92.

**Comment by hexxter** [comment]
no my tool need the same steps/unit. this is the problem they are different.

**Comment by Blue-Marlin** [comment]
Are the micro step jumpers set identically?

**Comment by hexxter** [comment]
yes the HW jumper/DRV8825/cable/motors all the same

**Comment by hexxter** [comment]
here my config.

[Configuration.h.zip](https://github.com/MarlinFirmware/Marlin/files/149860/Configuration.h.zip)

**Comment by Blue-Marlin** [comment]
If not all jumpers are set, one of the open could have a short.

**Comment by Blue-Marlin** [comment]
```
#define DEFAULT_AXIS_STEPS_PER_UNIT   {172,172,1600,164,164}
#define DEFAULT_MAX_FEEDRATE          {300, 300, 5, 25, 25}
#define DEFAULT_MAX_ACCELERATION      {3000,3000,100,1000,1000} 
```

5? Should not harm (but maybe), but does not help anyway.
(or you have made other (unsupported) changes)

**Comment by hexxter** [comment]
yes i know its was only for my documentation ;)

**Comment by thinkyhead** [comment]
> `#define DEFAULT_AXIS_STEPS_PER_UNIT   {172,172,1600,164,164}`

Yeah, that won't work. Marlin doesn't currently support differing E steppers. They all have to be identical. Making this change is not trivial. So we have to leave this as a feature request for now and it will not be in Marlin until version 1.2.0 and 1.1.1 at the earliest.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
