### ISSUE TITLE
Help with FW e SW Delta printer

### ISSUE THREAD

**Issue by mmatt94** [MarlinFirmware/Marlin#3059]
Hello
I am Matteo , student of Automation ad Packaging from Bologna, Italy

I need a help regarding the firmware to a related software to be able to use the robot.

I'm doing a Delta Robot, like the one in the picture (link), for use as a 3D printer.

The robot is driven by brushless motors 3 Nema 23 with its driver. This
driver has the direction inputs, Step, etc. and it can optionally be
controlled by USB. (The driver of the seller said that can be controlled
by macro

I think use arduino and RAMPS 1.4 board (and a Repetier SW & FW), but this method is used for linear and non-parallel delta as my robot.

He is able to give me some advice to program Arduino with the features of my robo to put it to use?

Thank you very muchl!

[http://www.elmomc.com/capabilities/6.GMAS%20Multi%20Axis%20Motion/12.GMAS%20Delta%20Robot/picture/6-12-1.png](url)

**Comment by Blue-Marlin** [comment]
![6-12-1](https://cloud.githubusercontent.com/assets/17075493/13406403/985d04e4-df23-11e5-82fe-bc4534a5367c.png)
Sorry. That's not a kinematic we already support.
This seems to have elements like a SARA machine - calculating angles, mixed with 3 arms - like a DELTA.
So, DELTA and SCARA are the code paths you should read in Marlin.
Likely it's much easier to integrate a new kinematic into RepetierFirmware. Marlin is not very well prepared for that.

**Comment by whosawhatsis** [comment]
@Blue-Marlin Actually, outside the 3D printer world, this is what a canonical delta looks like. The linear deltabots that are usually used for 3D printers are almost unheard of elsewhere, and most are controlled by the angles of 3 arms from a fixed base, which is usually above the work area.

That said, @mmatt94, he's right that this type of deltabot is not typically used for 3D printers, and is not what the delta configuration here refers to. There are other bots, like the Firepick Delta, that do work this way though. The Firepick guys have their own fork of Marlin (https://github.com/firepick-delta/Marlin), which is likely to have support for this type of deltabot.

**Comment by Roxy-3D** [comment]
@mmatt94  In order to write the software to support this kinematic's, the software developer would need to have a machine to code against.   If this is a commercial product (or going to be a commercial product) you should consider getting a few machines into the 'right' developer's hands.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
