### ISSUE TITLE
Perimeter not surrounding printed item. Cuts through the part

### ISSUE THREAD

**Issue by wolfstep** [MarlinFirmware/Marlin#3062]
Attached is a picture of the perimeter which is set to 5mm from object that goes around part on 3 sides however on the 4th side it goes right through the middle.
I have checked all my parts and they are as they were prior to me upgrading from 1.0.2 rev. I decided to try your rc3 and it is flacky. 
I am open to suggestions. I tried different part, ran them thru netfix, cold started everything including the laptop. Help!
![perimeter messup](https://cloud.githubusercontent.com/assets/3708746/13445148/2f9c30bc-dfd0-11e5-9c6d-881e327af553.jpg)

**Comment by Blue-Marlin** [comment]
G-code generation is not a thing Marlin does. It's done by the slicer. So changing your Marlin version can't be the source of your problem.

**Comment by wolfstep** [comment]
Thats the odd part, Slicer hasnt been changed. The only update was the new rev of marlin. When I was using the old version, it never happened. I use repetier and have all my various "old" preconfigs which worked fine before. I didnt change the slicer as I had them fine tuned and was deathly afraid to change them in fear of my slices going nuts. The old adage, if it isnt broke dont fix it. The only reason I went with rc3 is everyone was tough-ting its auto-leveling Proust.

Now I am not able to get my z home to work. The up and down button works great, but the home button gives me the "Home X/Y before Z" which I did. x homes, y homes, z just sits there. I can use the down arrow fine though.

**Comment by brainscan** [comment]
If the perimeter cuts through the object it's nothing to do with Marlin and probably just that the object is not completely level and so only a very small area is touching the build plate (the area with a perimeter) and the rest is floating so the slicer doesn't give it a perimeter, but as has already been said its nothing to do with Marlin.

**Comment by thinkyhead** [comment]
> Thats the odd part, Slicer hasnt been changed.

@wolfstep Make sure before you slice the object that it is flat and all the way dropped down to the build plate. To me it looks like your STL has the object tilted slightly prior to slicing.

**Comment by thinkyhead** [comment]
> I am not able to get my z home to work.
> I decided to try your rc3 and it is flaky.

Yes, it is known to be flaky. I recommend testing `RCBugFix` before reporting, because it is getting patches that are ahead of `RC3`. If something has already been patched in `RCBugFix` we've already heard about it, and we don't need to hear about it again.

**Comment by thinkyhead** [comment]
> I am not able to get my z home to work.

It's great to have you here, getting involved. All we ask is, please post any separate issues as a new issue. We like to do one topic at a time – the one specified in the title of the issue.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
