### ISSUE TITLE
extruder 3 wrong rotation

### ISSUE THREAD

**Issue by Letaw** [MarlinFirmware/Marlin#3083]
I added ramps to the Board extruder 2 ( was 4). The motor 3 of the extruder at the beginning when filing plastic rotates in the wrong direction. If you enable relay or the flow of plastic at other motors, the motor 3 starts to rotate correctly. Something wrong in the initial task direction DIR of the motor 3.

**Comment by jbrazio** [comment]
Just plug the motor connector the other way around and the direction of the motor will invert.

**Comment by Letaw** [comment]
The motor buggy is only the beginning. Then after starting other motors this motor rotates correctly. This problem is not in connector.

**Comment by Blue-Marlin** [comment]
Would you please be so kind to give us a g-code sequence to reproduce the problem?
A second one, where it works, would also be great.

**Comment by Letaw** [comment]
In a few days

**Comment by retorik** [comment]
Hello, I'Ve a similar problem with 2 Extruders. It's Necessary I rotate the second Extrude just one step (minimum) in reverse for after it's works Correctly. Without this step everytime the motor rotate in bad way

**Comment by thinkyhead** [comment]
#3161 addresses this, and will be merged soon!
