### ISSUE TITLE
Bed leveling is going up

### ISSUE THREAD

**Issue by arzhurp** [MarlinFirmware/Marlin#3120]
When I send G29 after G28, the effector of my Kossel XL is going UP and is blocked against the MAX end stops. 
I'm using a Hall probe. 
What might be the problem ? 
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/166467/Configuration.txt)

**Comment by Blue-Marlin** [comment]
Test your endstops with M119 in mid air.
No unused endstop shall be triggered.
Is the probe triggered? If yes, invert it.

**Comment by arzhurp** [comment]
Unfortunatly I already tried ! :-/

**Comment by brainscan** [comment]
Do deltas use the Z_raise_before_probing? If it does then surely it's only trying to do the 20mm move its been asked to. Sorry this setting on anything that homes to max has confused me. Like Blue-Marlin said 99%of the time it's because one of the end stops is triggered.

**Comment by jbrazio** [comment]
I don't think so, I had a quick look at the code and DELTA seems to be exempt from `Z_RAISE_BEFORE_HOMING` flag, could be wrong didn't go too deep.

**Comment by arzhurp** [comment]
I found the problem ! I think I wasn't on the same firmware when i tried `M119`.
So I had to invert X and Y Min even if they weren't used.

``` cpp
const bool X_MIN_ENDSTOP_INVERTING = true; // set to true to invert the logic of the endstop.
const bool Y_MIN_ENDSTOP_INVERTING = true; // set to true to invert the logic of the endstop.
```

But now the bed leveling is going everywhere ! UP and Down like a roller coaster !

**Comment by Blue-Marlin** [comment]
@arzhurp 
Would the configuration changes proposed in https://github.com/AnHardt/Marlin/pull/15/files have helped you? That would be possible even without the endstop test at boot-time

**Comment by arzhurp** [comment]
Now the endstops are inverted, the effector is going down after `G29`, touching the bed just one time and then going up like Z+20 for a Z-5, it try to do the probings while going up!

**Comment by Blue-Marlin** [comment]
Touching at 0,0 or at the first point to probe?

**Comment by arzhurp** [comment]
First point to probe

**Comment by arzhurp** [comment]
After a fresh new install, everything works except that the probe is not going down enough...

**Comment by arzhurp** [comment]
So, after hours of making adjustments, I finally succeed to do a nice bed leveling but it doesn't seem to be applied ! I've at least 0.5mm of difference when printing, exactly like before, without bed leveling...
My head is gonna explode ... hahahaha
Here is my new config.h
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/167826/Configuration.txt)

**Comment by paulusjacobus** [comment]
@arzhurp wonder if you have tried to modify the z probe offset?
`Z_PROBE_OFFSET_FROM_EXTRUDER -15.90  
Not sure if your custom M code M851 is enabled but that might help you modify the offset on the fly?

**Comment by arzhurp** [comment]
Hello,
My Z_Probe_Offset is the good one ;-) 
I tried several things but the leveling is still not accurate or not applying.

**Comment by arzhurp** [comment]
Edit : I tried a larger bed leveling with larger parts.... During the printing the nozzle can go 2mm above the bed at X90 Y90 and touch it at X90 Y-90

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
