### ISSUE TITLE
Tune from LCD. 

### ISSUE THREAD

**Issue by beerdart** [MarlinFirmware/Marlin#3142]
Issue with the "tune" setting? After loading RC3, I can no longer tune settings mid-print from LCD. If I click into the menu, click tune, and try to adjust say nozzle temperature, it goes into the flow adjustment screen (which I've never seen before), and I cannot escape it.

**Comment by Blue-Marlin** [comment]
Duplicate of #3115 #3042 #2944 #2934 #2930 #2905 #2884. Fixed in RCBugFix since 4 Dec 2015.
