### ISSUE TITLE
Do we have the Sanity Checks set too tightly for Auto Bed Leveling?

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#3165]
Please pull up:  

http://3dprintboard.com/showthread.php?20871-Question-about-AUTO_BED_LEVELING_GRID_POINTS&p=83412#post83412

I'm wondering if we should relax this check a little bit:

```
#if X_PROBE_OFFSET_FROM_EXTRUDER < 0 #if (-(X_PROBE_OFFSET_FROM_EXTRUDER * AUTO_BED_LEVELING_GRID_POINTS) >= (RIGHT_PROBE_BED_POSITION - LEFT_PROBE_BED_POSITION))
#error "The X axis probing range is not enough to fit all the points defined in AUTO_BED_LEVELING_GRID_POINTS"
#endif
```

**Comment by Blue-Marlin** [comment]
```
"/Configuration.h:457:8: error: #error "The X axis probing range is not enough to fit all the points defined in AUTO_BED_LEVELING_GRID_POINTS".
```

That's not code from a current Marlin.
I think the complete check has been dropped.

This is replaced by a runtime check. Search for MIN_PROBE_EDGE in Marlin_Main.cpp.
Even that restriction does not make much sense to me. (hidden limit to restrict AUTO_BED_LEVELING_GRID_POINTS ? Limit number of mesh points, to not subdivide moves too often?)

**Comment by Roxy-3D** [comment]
> That's not code from a current Marlin.   I think the complete check has been dropped.

Oooops!  I guess I should have checked before I made a 'New Issue'.    Sorry about that!
