### ISSUE TITLE
auto bed level grid activate and deactivate the probe beween measurments

### ISSUE THREAD

**Issue by hexxter** [MarlinFirmware/Marlin#3174]
what is the best way to integrate (PIN, Servo, ...) to activate an Solenoid before and after each measurment on auto bed level grid.

http://community.robo3d.com/index.php?threads/mike-kellys-solenoid-auto-level-for-stock-r1.3864/

this is what i want to integrated.
Have anyone a idea how can i configure it or where in the code the best place is to integrated this?

Thx

**Comment by Roxy-3D** [comment]
You would just not use the servo code (or activate any servos).   And you would power up the pin that controls the solenoid when the function run_z_probe() is called.

**Comment by hexxter** [comment]
yes the solenoid can only used for a short time <5 sec (overheating by longer use) i will activate a pin short before a z_probe will startet and disable the pin after each probe.

G29 E but with a pin and not a servo? Is this correct or i'm wrong?

**Comment by Roxy-3D** [comment]
Yes.  You would have to modify the `deploy_z_probe()` and `retract_z_probe()` functions.  You would not declare any servos and these functions will key off of `HAS_SERVO_ENDSTOP` to control the generation of code for servos. `G29` would have no idea about what you are doing to get the probe ready for use. The suggested changes are at a lower level and should be transparent to `G29`.

**Comment by jbrazio** [comment]
@Blue-Marlin, @thinkyhead can somehow that unused solenoid pin/code be hacked for this ?

**Comment by jbrazio** [comment]
nvm I didn't read clearly the request.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
