### ISSUE TITLE
Controller board fan stays on forever

### ISSUE THREAD

**Issue by ads61** [MarlinFirmware/Marlin#3178]
After the first connect to the board and homing the axis the fan switches off after the time set in the configuration.
After moving one of the axes the fan goes on and stay on forever.
(In both RC3 and RCbugfix of today)

**Comment by thinkyhead** [comment]
> After the first connect to the board and homing the axis the fan switches off after the time set in the configuration.

Which fan? The controller fan or the variable-speed fan on the extruder?

> After moving one of the axes the fan goes on and stay on forever.

Just moving an axis with an ordinary `G1` command will do this?

**Comment by thinkyhead** [comment]
The controller fan should stay on for as long as any stepper motor is active, so it's possible this is a side-effect of one of your stepper motors not being turned off. Do you have your stepper motors configured to disable after a period of inactivity? What is your setting for `DEFAULT_STEPPER_DEACTIVE_TIME`? There are new settings that are "true" by default, but if they aren't in your configuration it may also be causing your steppers never to disable, because not-existing equals "false" in this case.

``` cpp
#define DISABLE_INACTIVE_X true
#define DISABLE_INACTIVE_Y true
#define DISABLE_INACTIVE_Z true  // set to false if the nozzle will fall down on your printed part when print has finished.
#define DISABLE_INACTIVE_E true
```

**Comment by ads61** [comment]
DISABLE_INACTIVE_X and DISABLE_INACTIVE_Y are false so in that sense the behaviour is correct and fan goes off after the printjob if motors are disabled.

I was confused because in version 1 the fan stopped always after the last move and the DEFAULT_STEPPER_DEACTIVE_TIME expired.

For now switched back to v1.0 because i need the printer and test later again.

**Comment by thinkyhead** [comment]
We sorted out a lot of stuff for RC4, and should have an RC5 in a few days. Meanwhile, RCBugFix is the safest bet to have the most patched version until the final release. A public release has a way of exposing bugs that we miss… but so far they have not been _too_ hard to fix.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
