### ISSUE TITLE
MarlinFirmware Helper Scripts

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#3193]
Do PR submissions for Marlin directly from your BASH command line! I've put together 4 helpful scripts specifically tailored to make your Marlin workflow go more smoothly. They are called `mfinfo`, `mfup`, `mfpr`, and `mfclean`.

View them here: [Marlin Firmware BASH Helper Scripts](https://gist.github.com/thinkyhead/c84ef67739a54d9f9b4a)
Download them: [MarlinFirmwareBASH.tar.gz](https://github.com/MarlinFirmware/Marlin/files/190917/MarlinFirmwareBASH.tar.gz)

> #### `mfinfo [branch]`
> 
> Get the following helpful Marlin-Github info about the repo of your working directory:
> - Remote (upstream) Org name (MarlinFirmware)
> - Remote (origin) Org name (your Github username)
> - Repo Name (Marlin or MarlinDev)
> - Marlin Target branch (RCBugFix or dev)
> - Branch Name (the current branch or the one that was passed)
> ##### Example:
> 
> ```
> [/Projects/Firmware/Marlin] $ mfinfo
> MarlinFirmware thinkyhead Marlin RCBugFix rc_slow_buttons
> ```

---

> #### `mfup [branch]`
> 
> Fetch and merge upstream changes, optionally with a branch
> ##### Example:
> 
> ```
> [/Projects/Firmware/Marlin] $ mfup rc_doc_tweaks
> Fetching upstream (MarlinFirmware)...
> 
> Bringing RCBugFix up to date...
> Branch RCBugFix set up to track remote branch RCBugFix from origin.
> Everything up-to-date
> Already up-to-date.
> Everything up-to-date
> 
> Rebasing rc_doc_tweaks on RCBugFix...
> Switched to branch 'rc_doc_tweaks'
> Your branch is up-to-date with 'origin/rc_doc_tweaks'.
> First, rewinding head to replay your work on top of it...
> Applying: Move STRINGIFY to macros.h, use in language.h
> Applying: Drop DISABLE_M(IN|AX)_ENDSTOPS, replace with individual endstop flags
> Applying: Simplify configuration of Z2 endstops
> Applying: Account for Z_DUAL_ENDSTOPS in sanity checking of endstops
> Applying: Adjust SanityCheck messages
> Auto packing the repository in background for optimum performance.
> See "git help gc" for manual housekeeping.
> 
> Switched to branch 'i3_millie_RCBugFix'
> Your branch is up-to-date with 'origin/i3_millie_RCBugFix'.
> ```

---

> #### `mfpr [branch]`
> 
> Start a PR of the current branch against `RCBugFix` or `dev`. Pushes your branch to `origin` if you forgot. This script may need to be adjusted to your particular environment. In particular, if you don't have a `gnome-open`, `xdg-open`, or `open` command to open a URL in a browser, you will need to use your system's equivalent.
> ##### Example:
> 
> ```
> [/Projects/Firmware/Marlin] $ mfpr
> Opening a New PR Form...
> (opens the "New PR" page in the browser, set to the current branch)
> ```

---

> #### `mfclean`
> 
> Prune all your merged branches and any branches whose remotes are gone.
> A great way to clean up your branches after messing around a lot.
> ##### Example:
> 
> ``` sh
> [/Projects/Firmware/Marlin] $ mfclean
> Pruning Merged Branches...
> Deleted branch rc_epatel_mesh_fixes (was 14afe1a).
> Deleted branch rc_fix_numeric_filenames (was f423716).
> Deleted branch rc_general_clean (was 5d8036e).
> Deleted branch rc_keepalive_less (was cd4c3e9).
> 
> Pruning Remotely-deleted Branches...
> 
> ```

---
### Or, you could use a web form…

If you prefer something in the browser, here's something for you. Add the following forms to your custom `localhost` start-page in your browser (you _do_ have one of _those_, don't you?):

[Github PR Shortcut Form (githubmf.tar.gz)](https://github.com/MarlinFirmware/Marlin/files/181613/githubmf.tar.gz)

The crux of the HTML form is a simple javascript:

``` js
var GITHUB_USER = "you_yes_you";
var MARLIN_ORG_HOME = "https://github.com/MarlinFirmware";
var loc = MARLIN_ORG_HOME + "/Marlin/compare/RCBugFix..." + GITHUB_USER + ":" + branchname + "?expand=1";
window.open(loc, '_blank');
```

**Comment by Roxy-3D** [comment]
Oh?   I don't have to learn Git to do a Pull Request????

**Comment by jbrazio** [comment]
You still do, knowing C++ is also helpful. :-P
This just speeds up a bit Github interface by pre-selecting the target Marlin branch for you.

**Comment by thinkyhead** [comment]
Come to think of it, so much my work with `git` is in the terminal —and many of us need to do these tasks all the time— so I made a few BASH scripts specifically to help with Marlin. Described at the top ^^

> I don't have to learn Git to do a Pull Request?

Not really. But hey, `git` is super-easy once you get the gist of it.

**Comment by thinkyhead** [comment]
> I don't have to learn Git to do a Pull Request?

Not really. But hey, `git` is super-easy once you get the gist of it.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
