### ISSUE TITLE
Please add X2_MAX_POS to EEPROM (Dual X Carriage)

### ISSUE THREAD

**Issue by pbrgle1** [MarlinFirmware/Marlin#3200]
Sometimes i have to change the distance between the extruders by a fraction of a mm and it would be really helpful if this could be done by saving to EEPROM.

configuration_adv.h
# define X2_MAX_POS 257.4

**Comment by jbrazio** [comment]
Why do you have to frequently adjust a value that should be a mechanical parameter of the machine ?

**Comment by pbrgle1** [comment]
It's only +/- 0.2mm but enough to cause problems. Probably due to expanding and contracting of the rods and frame.

**Comment by thinkyhead** [comment]
Are you using GT2 belts and pulleys? Are they over- or under-constrained? Some adjustment there can really help.

If you're doing dual-color, I think possibly the `BABYSTEPPING` options could help. You would want to add some extra GCode on the top of your print-job to move the two carriages to the same spot, one after the other. When the second carriage is active, you would babystep the X axis to get it to the right spot. Then you can start your print and the axis will continue to stay aligned.

**Comment by pbrgle1** [comment]
Thanks i'll give it a try. But still some (semi)permanent solution like EEPROM setting would be nice. Once the values are set they last for quite some time.

**Comment by thinkyhead** [comment]
It sounds like what is really needed is not to artificially fix this by hacking `X2_MAX_POS`, but to provide an option for "fine-tuning" the offset between the carriages. We will have to get into this more after the current release. Features like this are becoming more important as dual printing is getting more popular all the time.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
