### ISSUE TITLE
info: preprocessor & assembler output

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#3212]
Recently someone asked, how to get the preprocessor and/or assembler output.

Add:
`compiler.c.extra_flags=-fverbose-asm -save-temps`
and 
`compiler.cpp.extra_flags=-fverbose-asm -save-temps`
to your `platform.txt` or `platform.local.txt`

Probably the info you are looking for is somewhere in that huge amount of .s .i .ii files this will produce in the sketch folder.

**Comment by Roxy-3D** [comment]
Thank You!!!!   It probably was me complaining I could not get gcc to leave the files laying around.

Were you debugging something difficult and needed to figure out how to get the assembler files?

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
