### ISSUE TITLE
M42 need st_synchronize()?

### ISSUE THREAD

**Issue by MetalMusings** [MarlinFirmware/Marlin#3214]
Doesn't M42 need to wait for the right moment before switching on/off a pin?
I think a `st_synchronize();` is missing at the end of `gcode_M42()`

**Comment by Blue-Marlin** [comment]
If you need a `M42` in sync, you can send a `M400` before.

**Comment by thinkyhead** [comment]
I agree. Sometimes you might want an `M42` code to take effect right away, and sometimes you might want it to take effect after the last-queued move has finished. The solution is to use `M400`. I will add a note in the documentation of `M42` as a reminder about how the command queue and the planner queue interact.
