### ISSUE TITLE
[RC4] Rigidbot Panel can't print from USB

### ISSUE THREAD

**Issue by AtomiclyCursed** [MarlinFirmware/Marlin#3238]
Using RC4 and the Rigidbot LCD/Panel I am unable to print from USB.

I can navigate the menus look at the files on the USB but when selecting one of the prints it  doesn't start.
I am however able to use OctoPrint to print from the USB with the same file. 
I have an idea that it's just not triggering the load/print when the button is pressed, as everything else is as expected, as it does return me to the info screen.

**Comment by thinkyhead** [comment]
Print from USB or print from SD Card?

**Comment by AtomiclyCursed** [comment]
The RigidPanel has a USB port instead of a SD Slot that comes standard with most other LCD Panels.

**Comment by thinkyhead** [comment]
Ah, I see! Interestingly enough, I am now unable to connect via USB and Pronterface either. So, there you have it – something is conflicting that I forgot to test.

**Comment by thinkyhead** [comment]
For reference, what is your `BAUDRATE`? Have you tried both 115200 and 250000? Does your host software baud rate also match?

**Comment by AtomiclyCursed** [comment]
just run at 115200, i can give other a try tomorrow if that would help?

**Comment by thinkyhead** [comment]
Yeah, check those rates. In my own case, I had decided to try the slower baud rate but I just forgot to tell Pronterface.

**Comment by thinkyhead** [comment]
Still looking at recent changes–– nothing jumps out yet.

**Comment by AtomiclyCursed** [comment]
There's a good chance it never worked, i don't use the USB anymore after moving to OctoPrint. I was asked if it all worked so decided to actually check it and noticed the printing from USB didn't work.

**Comment by AtomiclyCursed** [comment]
https://github.com/MarlinFirmware/Marlin/issues/3245 is also this issue, print filename had 20 at the front @thinkyhead

**Comment by jbrazio** [comment]
As a patch has been submitted, do you confirm this issue is closed ?

**Comment by AtomiclyCursed** [comment]
I am still printing but yes, i confirm that it is fixed :+1:

**Comment by jbrazio** [comment]
Great, do you mind closing the issue ? Thanks for your help sorting this one out.
