### ISSUE TITLE
[RC4] Some gcode files can't print from SD Card

### ISSUE THREAD

**Issue by ted321** [MarlinFirmware/Marlin#3245]
So I compared the difference.I found out if manually change the gcode`M104 S200` to `M104 S200 T0` it works fine.
Is this a bug or something.

**Comment by jbrazio** [comment]
You have to be a bit more specific..
What happens when you have `M104 S200` ?

**Comment by ted321** [comment]
`M104 S200`Nothing happened,the printer won't start.

**Comment by jbrazio** [comment]
Could you please have a serial connection to the printer when initiating the SD print so we can see what Marlin outputs ?

**Comment by ted321** [comment]
Sorry, I want to help, but I don't know how to get Marlin outputs.

**Comment by jbrazio** [comment]
On the Arduino IDE just click on Serial Monitor, and then operate the printer has you would; Marlin will "say" stuff to that monitor window.

**Comment by ted321** [comment]
I'm really sorry about the confuse.It has nothing to do with the M104 command.It's the file name.
The file is "10.gcode", marlin says "open failed, File: c88~1.gco"
I changed the file name to "abcdef.gcode" it works.

**Comment by ted321** [comment]
Seems Marlin do not recognizea filename start with numbers。Such as "8.gcode" "8abc.gcode" "10.gcode" "10abc.gcode" etc..

**Comment by Roxy-3D** [comment]
Just to be clear....   You can't select the file off of the SD-Memory card using the LCD Panel, right?  Because looking at the M23 code, it looks like you should be able to select the file using the USB link from PronterFace.

Can you try selecting the file using PronterFace?

**Comment by thinkyhead** [comment]
We're looking at a similar (maybe the same) issue at #3229. To help me understand what's going on, can you tell me: What version of Arduino are you using to build Marlin?

**Comment by thinkyhead** [comment]
Try this. In `Marlin_main.cpp` at around line 5985, change this:

``` cpp
while (*current_command_args == ' ' || (*current_command_args >= '0' && *current_command_args <= '9')) ++current_command_args;
```

…to this…

``` cpp
while (*current_command_args >= '0' && *current_command_args <= '9') ++current_command_args;
while (*current_command_args == ' ') ++current_command_args;
```

And see if that helps the issue.

**Comment by thinkyhead** [comment]
Ok, #3246 should soon be merged. It addresses the issue and improves things generally in that part of the GCode parser.

**Comment by thinkyhead** [comment]
Give `RCBugFix` a try when you have a chance. It now has this patched.

**Comment by ted321** [comment]
#3246 fixed the issue.Thank you for all your hard work.

**Comment by jbrazio** [comment]
@ted321 thank you for helping sorting this bug out, do you mind closing the issue ? Thanks.
