### ISSUE TITLE
Should software endstops always align to the machine?

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#3254]
Relating to PR #3227 –

Software endstops are set initially to correspond to the physical limits of the machine, and are expected to stay put until they are changed. However, currently a command like `G92` breaks software endstops. They end up moving, basically, so they no longer limit movement at the same physical points. The patch #3227 takes account of this issue and moves the software endstops when a command directly changes the `current_position` or the `home_offset`. This preserves the same physical limits, effectively moving the whole coordinate space.

When setting the `home_offset` directly this PR updates the software endstops, but doesn't make any change to the `current_position`. However `M428` —which corresponds to the Menu Item "Set Home Offset"— should subtract the new `home_offset` from `current_position` so that it corresponds to the position it would have after the next `G28` … without waiting for the next `G28`.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
