### ISSUE TITLE
Homing Delta G28 Mechanical Jam

### ISSUE THREAD

**Issue by skylord73** [MarlinFirmware/Marlin#3265]
Hi all,
I notice that when homing a delta printer, the firmware (1.1.0-RC3), moves up all 3 axis untll the first one reaches the endstop, and that is fine.
After that, starts homing the remaining axes one by one.
In some extreme situation, moving the remaingin two axes one by one could cause mechanical jam.
A more safe way to home could be to move the remaining two axis together, until limit is reached, and then home the last one

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
