### ISSUE TITLE
1 nozzle 2 extruder

### ISSUE THREAD

**Issue by yaniekarlina** [MarlinFirmware/Marlin#3266]
hello everyone. i have a project to make 3d printer delta with 1 nozzle and 2 extruder. can marlin make it? i try to modify marlin program but it not working.

**Comment by Roxy-3D** [comment]
You want to feed two filaments into 1 nozzle?  The Marlin Firmware can handle that assuming the nozzle can be purged reliably.

**Comment by yaniekarlina** [comment]
yes, that's what i mean. so what must i do?

**Comment by Roxy-3D** [comment]
Configure Marlin to have 2 extruders that are 0 mm apart.   And get both of the motors running correctly.   At that point, you may need to tell the Slic3r to do some custom GCode to purge the nozzle when you do a color change, but that is about it....

**Comment by thinkyhead** [comment]
Try MarlinKimbra and see if it can do what you want. It already has native support for this, which it calls SINGLENOZZLE. I have submitted a mixing extruder feature that also does this, but only to the MarlinDev branch, and it hasn't been merged yet. If you like, I can make a branch for you that has the current Marlin plus this feature. It works just like the Repetier Host mixing feature.

https://github.com/MarlinFirmware/MarlinDev/pull/361

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
