### ISSUE TITLE
Bed level issue - doubts about offset _z_probe

### ISSUE THREAD

**Issue by dinizhobby** [MarlinFirmware/Marlin#3286]
My switch is in the servo in front of the nozzle and a little pro left side of the nozzle. using command M114 i got offset X5 Y20 and Z1.20 (all positive)

should I to enter the negative or positive value?

**Comment by jbrazio** [comment]
```
  // Z Probe to nozzle (X,Y) offset, relative to (0, 0).
  // X and Y offsets must be integers.
  //
  // In the following example the X and Y offsets are both positive:
  // #define X_PROBE_OFFSET_FROM_EXTRUDER 10
  // #define Y_PROBE_OFFSET_FROM_EXTRUDER 10
  //
  //    +-- BACK ---+
  //    |           |
  //  L |    (+) P  | R <-- probe (20,20)
  //  E |           | I
  //  F | (-) N (+) | G <-- nozzle (10,10)
  //  T |           | H
  //    |    (-)    | T
  //    |           |
  //    O-- FRONT --+
  //  (0,0)
```

Does that help ?
You have to look from the origin, i.e. here is your machine (X, Y) (0, 0).
If, when looking from origin, the probe is on the _top-right_ of the nozzle then the values are positive.

**Comment by dinizhobby** [comment]
my switch   is left and front of the nozze. 

After enter m114  X5  y20 and Z1.20

**Comment by Sniffle** [comment]
what type of Z probe do you have?  That makes a difference for your Z offset, as to the X and Y position that is relative to probing the positions on your bed centered on the bed.  

if your probe for G28 comes down in the center of the bed your offset positions are correct.  As to the Z-probe offset it depends on what kind of probe you have

**Comment by dinizhobby** [comment]
Please check this pictures below

http://imagens.abcdotecnico.com.br/images/IMG-20160330-WA0018.jpg

http://imagens.abcdotecnico.com.br/images/IMG-20160330-WA0017.jpg

**Comment by dinizhobby** [comment]
when i make G28  just nozzle go to center of the bed.

**Comment by Sniffle** [comment]
I'll have to defer to other delta users, my delta uses an FSR Setup.

**Comment by thinkyhead** [comment]
If the probe is to the left and in front of the nozzle, then both offsets should be negative. (The coordinates of the probe are less than the coordinates of the nozzle.)

**Comment by dinizhobby** [comment]
Thinkyhead  did you see my pictures?
i am using a delta

**Comment by dinizhobby** [comment]
How Can I test if offset is correct ?

**Comment by thinkyhead** [comment]
@dinizhobby When you move the nozzle down to the bed, it hits the center of the bed. When you decrease the X coordinate the nozzle moves "left", and when you increase the X coordinate the nozzle moves "right". When you decrease the Y coordinate the nozzle should move towards the "front", and when you increase the Y coordinate the nozzle should move towards the "back".

Once you know where LEFT / RIGHT / FRONT / BACK are, then you know which offsets will be correct. If your probe is to the LEFT of the nozzle, then it has a NEGATIVE X offset. If it is in FRONT of the nozzle then it has a NEGATIVE Y offset.

**Comment by dinizhobby** [comment]
Thank you! But Auto BED level isn´t working correct here. 
Mesh is better for delta ?

**Comment by thinkyhead** [comment]
@dinizhobby If you can't provide more useful feedback, I'm afraid you're on your own. If you are able to do more diagnostics and figure some things out, please post a new issue.
