### ISSUE TITLE
Files with names starting with number are not working

### ISSUE THREAD

**Issue by clexpert** [MarlinFirmware/Marlin#3296]
G-code files with names starting with number are not working from SD card. For example: **test.gcode** is working, **1test.gcode** is not working. The printing is not started.

**Comment by jbrazio** [comment]
Have you tested the latest RCBugfix ? This issue has been addressed.

**Comment by clexpert** [comment]
I am sorry, I am testing RC4 in this time. I am going to try latest updates.

**Comment by clexpert** [comment]
Oops. It really works in latest `RCBugFix`. I am sorry.

**Comment by jbrazio** [comment]
No worries, thank you for reporting.
