### ISSUE TITLE
LCD only support does not compile

### ISSUE THREAD

**Issue by ghpicard** [MarlinFirmware/Marlin#3298]
Hi!
   This seems to be a resurface of [#1873](https://github.com/MarlinFirmware/Marlin/issues/1873)

When trying to compile Marlin with an LCD only panel (20x4), no encoder, no SD Card, which would correspond to only #define ULTRA_LCD not commented, I get the following error:

> Arduino: 1.6.7 (Linux), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"
> 
> sketch/ultralcd.cpp: In function 'void lcd_save_previous_menu()':
> ultralcd.cpp:315: error: 'encoderPosition' was not declared in this scope
>  inline void lcd_save_previous_menu() { prevMenu = currentMenu; prevEncoderPosition = encoderPosition; }
>                                                                                       ^
> exit status 1
> 'encoderPosition' was not declared in this scope

**Comment by jbrazio** [comment]
@ghpicard could you please test if the patch fixes your issue ?

**Comment by thinkyhead** [comment]
This issue is patched with #3303.

**Comment by ghpicard** [comment]
It worked OK. Thanks!
