### ISSUE TITLE
Best Commands for start job?

### ISSUE THREAD

**Issue by fbarcenas** [MarlinFirmware/Marlin#3299]
Hi
Each time than i read comments i see than some people use some commands, another others...
The question is, what is the perfect commands for start a job?
For example i use (I copy/paste from a file):

``` gcode
G90
M82
M106 S0
M140 S55
M104 S215 T0
M109 S215 T0
M104 S0 T1
G92 E0
G21        ;metric values
G90        ;absolute positioning
M82        ;set extruder to absolute mode
G1 Z10 
G28        ; HOME XYZ
```

Really is correct? Need more things, i can delete lines?
Is necessary G21, after G90 and after M82?

Thanks to everything

**Comment by MoonshineSG** [comment]
You will never find a set of commands that everyone will agree upon. It depends on your printer, the slicer software, your printing process ...  
You will read, experiment, modify, read more and experiment more... 
At one point, you will get something that you're happy with...  and then change it a bit more :D 

That being said, here's mine. Works for me.  For now....

```
; ------------ START GCODE ----------
G21     ; set units to millimeters
G90     ; use absolute coordinates
M83     ; use relative distances for extrusion

M80     ; power on
M106 S0 ; fan off

M888    ; check bed levelling
G28     ; home all

G1 X40 Y-10 F6000   ; move outside bed
G1 Z0.3 F600        ; and just above the edge of the bed

M190 S[bed0_temperature]    ; wait for bed temp
M300 @temperature_bed       ; beep

M109 S[extruder0_temperature]   ; wait for extruder temp
M300 @temperature_extruder      ; beep

G1 E5 F150      ; spit some filament
G4 P500
G1 E10 F250
G4 P800
G1 E15 F350
G4 P1000
G1 E20 F400
G4 P1500

G1 Y5 F3000     ; wipe

G92 E0          ; set E to 0

M300 @printing  ; beep
; ------------ START GCODE ----------
```
