### ISSUE TITLE
 ambient temperature false

### ISSUE THREAD

**Issue by taratata2016** [MarlinFirmware/Marlin#3300]
as I have Autotune PID problem for 5 days ( Repetier -host gives an ambient temperature of 37 ° C instead of 23 ° C room ) . I change cards ramps - extruding - exposed the ramps with only extrude - ATX 550W 20A 20A power , nothing works. 
you can read my post here http://www.lesimprimantes3d.fr/forum/topic/1709-prusa-i3-variations-de-temp%C3%A9rature-de-lextrudeur/. i hope find solution here. tks in advance for your time

**Comment by jbrazio** [comment]
I'm sorry I didn't understood if you're running Marlin as the firmware of your printer.
Have you tried autotune ?
`M303 E0 S200 C8`

**Comment by taratata2016** [comment]
yes, i setting marlin and update ramps and start `M303 E0 S220 C8` and entering the new values in `Configuration.h` and another update and check the temperature ....

If I plug the thermistor on pins `T1` or `T2` the temperature is between 18°C to 24°C.

**Comment by taratata2016** [comment]
if i plug the thermistor on pins T1 or t2 the temperature is between 18°C to 24°C

**Comment by Blue-Marlin** [comment]
Gentlemen,
The measured temperature has nothing, absolute nothing, to do with `M303`.
If you see a difference between `T0`, `T1`, `T2` with the same thermistor than look for different sensor types.

``` cpp
#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_1 1
#define TEMP_SENSOR_2 1
```

**Comment by taratata2016** [comment]
Normally, at the opening of repetier-host, the value should be the ambient temperatures. `T0` gives 35 ° C. I made so many test, I am lost.

**Comment by Blue-Marlin** [comment]
So ether you have a wrong sensor type now, or a defect thermistor, or the pin used by `T0` is used by some other function through error, or if your board is new, there is a little chance the resistor at that channel has the wrong value. Any solder chips on your board, causing shorts?

**Comment by taratata2016** [comment]
I change another ramps 1.4 - thermistor - on ramps have only thermistor. the ramps is on plank wood.

You can read my post here http://www.lesimprimantes3d.fr/forum/topic/1709-prusa-i3-variations-de-temp%C3%A9rature-de-lextrudeur/.

**Comment by taratata2016** [comment]
you can read my post herehttp://www.lesimprimantes3d.fr/forum/topic/1709-prusa-i3-variations-de-temp%C3%A9rature-de-lextrudeur/.

**Comment by thinkyhead** [comment]
What version of Marlin are you using? Be sure to test with the current `RCBugFix` code to make sure we haven't already patched your issue (assuming it is software, and not hardware or configuration-related). Have you used older versions of Marlin which show a different temperature for the same thermistor?

**Comment by taratata2016** [comment]
i use Marlin 1.1.0-RC3 [https://github.com/MarlinFirmware/Marlin](url). I measure the voltage (volts) at terminals T0 T1 T2 = 4.7v - I also tested the continuity multilmètre between terminals 1 3 5 (this is good). have you idea for some test mesuring board? tks in advance for your proipositions

**Comment by taratata2016** [comment]
i just test the version "Release 1.1.0-RC5" and ther ambient temperature have sample trouble (35°C).
If i understand well, the " "RCBugFix" branch" is corrections inside the version RC5? i'm sur about spare parts, because i have many thermistor, 2x ramps and i test only with thermistor plug on borad. before reflash arduino mega, i reset Mega with this code `void setup(){}
void loop(){}`.

**Comment by taratata2016** [comment]
![_280](https://cloud.githubusercontent.com/assets/18212675/14225670/0e30f52a-f8cb-11e5-98b5-587fa1057e32.jpg)

**Comment by taratata2016** [comment]
why Marlin writing wrong ech debug
![_281](https://cloud.githubusercontent.com/assets/18212675/14225679/c50e3ff0-f8cb-11e5-9fbb-99693a3cf2c1.jpg)

**Comment by taratata2016** [comment]
continuity test between A15 and PIN6 (T2)  -  A14 and PIN4 (T1) - A13 and PIN2 (T0) is ok!
now i must find the R7 R1 R11 on board ramps1.4 for check welds "les soudures"...

**Comment by thinkyhead** [comment]
It sure looks like a hardware problem. The same thermistor should read the same resistance (hence, temperature) regardless of the connector to which it's attached — unless there is something about the connector that's different (i.e., a different resistance). If `T0` turns out to be problematic in hardware, you can just change the pin assignments and use a different connector.

**Comment by thinkyhead** [comment]
> Why is Marlin writing wrong echo debug?

A bug in the way the `M111` function was fetching a pointer to PROGMEM. This is patched in #3343.

**Comment by Roxy-3D** [comment]
I don't like 'Harvard' architecture either!

**Comment by taratata2016** [comment]
Thank you for your answer! The thermistance work well, because when i plug Melzi board (original board of printer hensine prusa i3), i have 25°C. ONly with my 2 board test ramps 1.4 have same mistake temperature 35°C.

**Comment by taratata2016** [comment]
you can watch, how i do autotune pid

voci comment je fais

https://www.youtube.com/channel/UCKfChdFFkV-OBNG9AL7t2Xw

https://youtu.be/WHFz9gj46Us    0 Power Supply ON TempRoom

https://youtu.be/is8C26_kwcs      0 - Thermistor 100k B3950
    
https://youtu.be/p4X1Uoucxlk         1 - Marlin configuration.h
    
https://youtu.be/PYLKjq886fw       2   ArduinoIDE Upload Marlin Firmware
    
https://youtu.be/iAIqqbmRyTI        3 - Start AutoTune PID
    
https://youtu.be/JUlfZZftNd4          3 - Start AutoTune PID bis
    
https://youtu.be/BZmkM42QJ90    4 - New Value PID
    
https://youtu.be/ywgDQE7bvpo      5 - Extruder is Cold
    
https://youtu.be/2I3NcQ_UqwY       6 - Wrong Room Temperature
    
https://youtu.be/ifFH3e0tct4           6 - Wrong Room Temperature bis

**Comment by Blue-Marlin** [comment]
Again.
As long you get false room-temperature, autotune is absolutely clueless.

Your enormous amount of noise on the temperature also indicates - there is something wrong. 
My tests with todays RcBugFix, Mega/RAMPS, sensor 11, give a stable (normal) room temperature with noise better than +- 0.2°C.

Recheck your hardware.

**Comment by taratata2016** [comment]
the rcbigfix can download her [ https://github.com/MarlinFirmware](url)! is right?
i don't know what is wrong in my tests! so crazy

**Comment by taratata2016** [comment]
the hardware work fine with Melzi v2.0 board with repetier firmware.

**Comment by Blue-Marlin** [comment]
Try to minimize the system. Mega, RAMPS, USB-cable, one of your spare thermistors - noting else - no power supply, no stepper drivers, no heaters, no display - nothing.
If that works, readd part by part.

**Comment by taratata2016** [comment]
sur i test with only thermistor and power suppy and cartridge heaters. I find the prob. I check and raplace all spare parts and use with minimze system. But i forget to check the Arduino Mega. I replace it and "Ho my god - tks so much) - work so fine now. The Arduino Mega is HS=out of order (KO)...
thank you at all people use time to help me...
