### ISSUE TITLE
Icons missing from display

### ISSUE THREAD

**Issue by Grogyan** [MarlinFirmware/Marlin#3312]
Utilizing
RAMPS 1.4 EFB
Full Graphics Display
Marlin RC5

Testing bugfix  #3235
Expected result of turning on the Extruder fan on when temperature exceeds a certain threshold, and turns off again when it falls below this.  
Compiles and runs as expected.

However, nozzle, heatbed and fan icons are missing from the display

**Comment by Grogyan** [comment]
@jbrazio your fix works perfectly.
Thanks

**Comment by jbrazio** [comment]
Thank you for evaluating it.

**Comment by jbrazio** [comment]
@Grogyan if you feel your problem has been solved please close this issue.
