### ISSUE TITLE
Marlin CNC

### ISSUE THREAD

**Issue by makis2912** [MarlinFirmware/Marlin#3315]
Hello, I really need help in the firmware setup for the CNC. Two endstop in the Y axis to adjust. I am from Russia and does not speak English, so I use a translator. Excuse me.

**Comment by makis2912** [comment]
Use two drivers, and two motors in the Y axis. When searching for a home both engines stop at the trailer Y. you need to configure the engine stopped by Y Y trailer and the engine at the trailer Y2 Y2

**Comment by makis2912** [comment]
I have included #define Y_DUAL_STEPPER_DRIVERS

**Comment by makis2912** [comment]
1.1.0-RC3

**Comment by thinkyhead** [comment]
First test the latest code in the [`RCBugFix`](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) branch. Then if you still have a problem, please post the contents of your `Configuration.h` file.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
