### ISSUE TITLE
Babystepping not working at 1.1.0 RC5

### ISSUE THREAD

**Issue by Fixx** [MarlinFirmware/Marlin#3327]
My setup is Dual Z DRV8825 stepper drivers and RUMBA board. It worked until now(I didn't tried RC4) at every revision of Marlin but at 1.1.0 RC5; Babystepping Z is not working at all.

**Comment by Rikrdoga** [comment]
@Fixx i just did a pull request to fix this problem

**Comment by thinkyhead** [comment]
Thanks, it is merged! It will be in `RC6` — coming soon.
