### ISSUE TITLE
Marlin -Ramps 1.4 remapping drivers  [solved]

### ISSUE THREAD

**Issue by Ovaday** [MarlinFirmware/Marlin#3333]
Hello, I have one question, how to remap pins, if I have X stepper driver in Z spot and Z stepper driver in X spot? 
Now I'm just replace letters in gcode, but if it could be made by firmware, it'll be much better.

Sorry if it is in wiki, I didn't found it
Thank you

**Comment by jbrazio** [comment]
This maybe a stupid questions from me but can't you switch the stepper plugs between Z and X ?

**Comment by Ovaday** [comment]
@jbrazio, No, I can't. RAMPS for me - CNC controller, that is installed on the main frame. There is 9-pin sockets with special appointment for each. So I can't just unplug one and insert another
![dsc_0234](https://cloud.githubusercontent.com/assets/11793534/14232623/93633d6c-f9c9-11e5-83a6-e2b6c3f375c0.JPG)

**Comment by Blue-Marlin** [comment]
Have a look into your boards pin-file.

**Comment by jbrazio** [comment]
As advised by @Blue-Marlin, you should go into your board pin file and switch the output pins for X and Z, this should get you in the ballpark.

As this is not an issue directly related with Marlin when possible please close this issue, thanks.

**Comment by Ovaday** [comment]
@jbrazio @Blue-Marlin Thanks for you! It's helped me! Hope it'll work well

**Comment by jbrazio** [comment]
You're welcome.
