### ISSUE TITLE
Missing Aragonese translation

### ISSUE THREAD

**Issue by jbrazio** [MarlinFirmware/Marlin#3347]
We need your contribution to translate the following missing messages:

``` cpp
#define MSG_BED_Z
#define MSG_A_TRAVEL
#define MSG_HEATING_FAILED_LCD
#define MSG_ERR_REDUNDANT_TEMP
#define MSG_THERMAL_RUNAWAY
#define MSG_ERR_MAXTEMP
#define MSG_ERR_MINTEMP
#define MSG_ERR_MAXTEMP_BED
#define MSG_ERR_MINTEMP_BED
#define MSG_HEATING
#define MSG_HEATING_COMPLETE
#define MSG_BED_HEATING
#define MSG_BED_DONE
```

Have a look on the file [language_en.h](https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/language_en.h) for the original English translation.

**Comment by jbrazio** [comment]
Closed by #3772.

**Comment by jbrazio** [comment]
I've submitted a PR to prune unmaintained language files, @danielmartinez as you're one of the contributors to this file would you care to submit an update to it ? Thanks.

**Comment by danielmartinez** [comment]
I'm don't have enough time to update the translation right now... maybe I can translate it in a future, so, if you want to prune it for now, I can file a PR when I translate it.

**Comment by jbrazio** [comment]
If you plan to maintain it then no need for pruning.
