### ISSUE TITLE
Missing Basque-Euskera translation

### ISSUE THREAD

**Issue by jbrazio** [MarlinFirmware/Marlin#3354]
We need your contribution to translate the following missing messages:

``` cpp
#define MSG_BED_Z
#define MSG_A_TRAVEL
#define MSG_HEATING_FAILED_LCD
#define MSG_ERR_REDUNDANT_TEMP
#define MSG_THERMAL_RUNAWAY
#define MSG_ERR_MAXTEMP
#define MSG_ERR_MINTEMP
#define MSG_ERR_MAXTEMP_BED
#define MSG_ERR_MINTEMP_BED
#define MSG_HEATING
#define MSG_HEATING_COMPLETE
#define MSG_BED_HEATING
#define MSG_BED_DONE
```

Have a look on the file [language_en.h](https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/language_en.h) for the original English translation.

**Comment by jbrazio** [comment]
Closed by #3772.

**Comment by jbrazio** [comment]
I've submitted a PR to prune unmaintained language files, @koldoartola, @MatixYo as you're one of the contributors to this file would you care to submit an update to it ? Thanks.

**Comment by MatixYo** [comment]
I submitted an update but I was not able to test if all of the strings show correctly on LCD

**Comment by jbrazio** [comment]
That's not an issue, thank you.
