### ISSUE TITLE
Using a LCD you can't print sd files with a number as first character

### ISSUE THREAD

**Issue by StephenRC** [MarlinFirmware/Marlin#3378]
Using a LCD, if you select a file that begins with a number, nothing happens.  The print never starts, no  bed temp is set and nothing else occurs.  Remove the number and the print starts.

0_PLA_something.gcode doesn't work.
_PLA_something.gcode does work.

Works fine in RC3 and RC1.

**Comment by Roxy-3D** [comment]
I believe this was broken in RC-4 but should be working in RC-5.  Please download RC-5 and report back if you still have a problem.

**Comment by CONSULitAS** [comment]
see #3246
merged 10 days ago

**Comment by StephenRC** [comment]
It's working in RC5.  Didn't see the small gray comment RC5 released in the file list.  The section that shows the readme, only shows RC4.

**Comment by thinkyhead** [comment]
RC6 is coming soon. I'll remember to update the README this time.
