### ISSUE TITLE
Issue when more than 1 declared extruder on RUMBA board

### ISSUE THREAD

**Issue by jlcdi** [MarlinFirmware/Marlin#3381]
Hi,

On Marlin 1.1.0-RC5, the following problem occurs when declaring more than 1 extruder in `Configuration.h`. This issue is not new and is lasting from various past versions:

```
In file included from Configuration_adv.h:601:0,
from Configuration.h:859,
from Marlin.h:26,
from blinkm.cpp:5:
SanityCheck.h:305: error: #error TEMP_1_PIN not defined for this board.
#error TEMP_1_PIN not defined for this board.
^
SanityCheck.h:313: error: #error HEATER_1_PIN not defined for this board.
#error HEATER_1_PIN not defined for this board.
^
SanityCheck.h:319: error: #error TEMP_SENSOR_1 is required with 2 or more EXTRUDERS.
#error TEMP_SENSOR_1 is required with 2 or more EXTRUDERS.
^
#error TEMP_1_PIN not defined for this board.
```

Thanks for your help.

**Comment by thinkyhead** [comment]
I can't see any obvious issue in the code. These pins are defined in the `pins_RUMBA.h` file (under appropriate conditions).

``` cpp
#if TEMP_SENSOR_1 == 0
  #define TEMP_1_PIN           -1
  #define HEATER_1_PIN         -1
#else
  #define HEATER_1_PIN          3   // EXTRUDER 2
  #if TEMP_SENSOR_1 == -1
    #define TEMP_1_PIN          5   // ANALOG NUMBERING - connector *K2* on RUMBA thermocouple ADD ON is used
  #else
    #define TEMP_1_PIN         14   // ANALOG NUMBERING - default connector for thermistor *T1* on rumba board is used
  #endif
#endif
```

So before I go hunting further, a couple of questions…
- What value are you using for `TEMP_SENSOR_1`?
- What version of Arduino IDE are you using to compile?

**Comment by fbarcenas** [comment]
I am using RUMBA and not problem, use the last RCBUGFIX and the last arduino 1.6.8

**Comment by jlcdi** [comment]
I did not affect a value at TEMP_SENSOR_1. Should I ?

2016-04-05 13:23 GMT+07:00 fbarcenas notifications@github.com:

**Comment by Blue-Marlin** [comment]
Yes, you should.
Head - Wall - bang - bang - bang.

```
SanityCheck.h:319: error: #error TEMP_SENSOR_1 is required with 2 or more EXTRUDERS.
#error TEMP_SENSOR_1 is required with 2 or more EXTRUDERS.
```

**Comment by jlcdi** [comment]
@Blue-Marlin

You are right.
I now found out. There was no values entered on TEMP_SENSOR_1, TEMP_SENSOR_2, TEMP_SENSOR_3.
Problem solved. I know what I will have to say to the ones who makes the same mistake, and I've seen many...

Thks a lot everybody for your help, especially @thinkyhead
