### ISSUE TITLE
one nozzle dual extruder

### ISSUE THREAD

**Issue by Ky1duck** [MarlinFirmware/Marlin#3401]
not sure if this is the right place but does Marlin support one nozzle dual extruder yet. 

thanks

**Comment by Roxy-3D** [comment]
I don't have one....  But "Yes!".   I think if I had one, I would put some extra GCode to purge the nozzle (in a safe place) every time I switched colors.

**Comment by Ky1duck** [comment]
yea but thr problem is I cant find anywhere to tell marlin to use the same heater and temp sensor for both extruders.

**Comment by thinkyhead** [comment]
@Ky1duck You should use the [MarlinKimbra fork of Marlin](https://github.com/MagoKimbra/MarlinKimbra), which has a `SINGLENOZZLE` option to do what you want. We have a "mixing extruder" feature pending in our development branch which accomplishes the same thing, but it's not yet merged.

**Comment by woodsmoke** [comment]
This is a feature I'd love to see too.

**Comment by woodsmoke** [comment]
Is it as simple as duplicating the pin number for both TEMP_0_PIN/HEATER_0_PIN and TEMP_1_PIN/HEATER_1_PIN? It has compiled and uploaded. And T0/T1 temp readings are duplicated.

**Comment by woodsmoke** [comment]
Not quite duplicated, and the heaters won't respond. So no it isn't as simple as that.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
