### ISSUE TITLE
RUMBA language.h Error

### ISSUE THREAD

**Issue by alisonbelow** [MarlinFirmware/Marlin#3408]
Upon compilation I get the error (see attached image for better context):

```
In file included from sketch\Marlin.h:42:0, from sketch\Marlin_main.cpp:35:
sketch\Marlin_main.cpp: In function 'void gcode_M115()':
language.h:102: error: expected ')' before 'DEFAULT_SOURCE_URL'
  #define SOURCE_CODE_URL DEFAULT_SOURCE_URL
sketch\Marlin_main.cpp:4541:3: note: in expansion of macro 'SERIAL_PROTOCOLPGM'
   SERIAL_PROTOCOLPGM(MSG_M115_REPORT);
   ^
sketch\language.h:146:112: note: in expansion of macro 'SOURCE_CODE_URL'
 #define MSG_M115_REPORT                     "FIRMWARE_NAME:Marlin "
DETAILED_BUILD_VERSION " SOURCE_CODE_URL:" SOURCE_CODE_URL "...
                                                                                            ^
sketch\Marlin_main.cpp:4541:22: note: in expansion of macro 'MSG_M115_REPORT'
   SERIAL_PROTOCOLPGM(MSG_M115_REPORT);
                     ^
```

in the `language.h` file. I have seen this same error posted in the RepRap forum, but with no resolve. Is this an issue with Marlin Release 1.1.0-RC4 and Rumba? Thank you.
<img width="948" alt="errir" src="https://cloud.githubusercontent.com/assets/4053231/14332596/452ee424-fc18-11e5-9162-05439dd00729.png">

**Comment by Roxy-3D** [comment]
I believe this is fixed in RC5's RCBugFix.   But I'm not positive about that.

**Comment by jbrazio** [comment]
@Roxy-3DPrintBoard she is right, this has been fixed in RC5, please download the [latest archive](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip).
