### ISSUE TITLE
A blinking dot on the RepRapDiscount Full Graphic Smart Controller

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#3409]
![dscn1591 mov_snapshot_00 01_ 2016 04 07_05 40 14](https://cloud.githubusercontent.com/assets/15308844/14332243/81eed890-fc83-11e5-98d0-e0b996565ad0.png)
[video clip](https://www.youtube.com/watch?v=vE_WC66etvo)

It blinks at 2 second intervals on lower right hand corner of the screen.
It was tested with [newest RCBugFix](https://github.com/MarlinFirmware/Marlin/commit/2988147880d6f1055a3b86d3806775cebe9a7166).
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/207329/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/207331/Configuration_adv.txt)

I cannot judge that it's specifications or bug or defect of my LCD, but I hasten to report it.
It looks like it haven't actual harm.

**Comment by pflugj** [comment]
I only noticed now ...
Got the same blinking dot here :-)
... so your display is OK
Maybe some kind of a "running" indicator

**Comment by Blue-Marlin** [comment]
Congratulations. You discovered the "I'm alive dot". It's a feature of the full graphics displays and also work in the deeper menus. As long this is blinking the refresh works.

**Comment by ghost** [comment]
For @Blue-Marlin, I'm grateful to your explanation.
