### ISSUE TITLE
Auto bed leveling does weird

### ISSUE THREAD

**Issue by JefHomeBuiltDeltaPrinter** [MarlinFirmware/Marlin#3439]
Hi everyone,

I have a problem with my auto bed leveling. I have a delta printer and I use the grid leveling mode. Everything seems to work if I execute the G29 code. But if a execute the G29 code and the first time he is probing I but a metal opbject underneath it, the second time also and de third time also and this works all fine. But the fourth time I don't put a metal object underneath it but he seems to detect something. From then it's everytime te same problem.

Can someone help me?

**Comment by thinkyhead** [comment]
- What kind of probe?
- What version of Marlin?

**Comment by JefHomeBuiltDeltaPrinter** [comment]
It's a LJ12A3-4-Z/BX Inductive Sensor. Here you can find my Marlin program https://www.dropbox.com/sh/aox9c32ur6ro27d/AADR7PQ-ms98EGu08GfUXYfxa?dl=0

**Comment by thinkyhead** [comment]
Please test with [`RCBugFix`](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) to see if we already fixed this.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
