### ISSUE TITLE
Menu - Move Y-axis

### ISSUE THREAD

**Issue by islandjon** [MarlinFirmware/Marlin#3442]
Using the menu selections, I moved the X-axis to -90 (MAX) and then back(0,0) and then attempted to moves the Y-axis and it will only move the on the X-axis when I make any adjustments with the scroll wheel under the Y-axis menu.

The display is a Reprap and displays "Move X: " after selecting "Move Y" under any of the increment submenus.

**Comment by Blue-Marlin** [comment]
Hopefully this is fixed with #3320. Up to now only in RCBugFix.

**Comment by thinkyhead** [comment]
Thank you for the report. This issue has been fixed in `RCBugFix` and will be published in the next release candidate.
