### ISSUE TITLE
Change language to Russian

### ISSUE THREAD

**Issue by gans-AD** [MarlinFirmware/Marlin#3457]
Please describe what changes you need to make to change the language to Russian.

**Comment by Blue-Marlin** [comment]
At first set the normal things to make your display work for English.

If you have a character based display, find out if your display can handle Cyrillic at all.
Set

```
  #define DISPLAY_CHARSET_HD44780_JAPAN        // this is the most common hardware
  //#define DISPLAY_CHARSET_HD44780_WESTERN
  //#define DISPLAY_CHARSET_HD44780_CYRILLIC
```

to

```
  //#define DISPLAY_CHARSET_HD44780_JAPAN        // this is the most common hardware
  //#define DISPLAY_CHARSET_HD44780_WESTERN
  #define DISPLAY_CHARSET_HD44780_CYRILLIC
```

and

```
#define LANGUAGE_INCLUDE GENERATE_LANGUAGE_INCLUDE(ru)
```

If you don't see Cyrillic letters your hardware does not support Cyrillic. -> Stay with English.

If you have a full graphic display just set:

```
#define LANGUAGE_INCLUDE GENERATE_LANGUAGE_INCLUDE(ru)
```

and you are done.
