### ISSUE TITLE
Is it possible to force the use of Arduino v1.6.8 ???

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#3463]
People are continuing to use the older versions of Arduino that we know break the SD-Memory card code.   Can we add a Sanity Check or some other mechanism to alert the user they are using the wrong compiler?

http://3dprintboard.com/showthread.php?21439-About-to-try-Marlin1-1-0RC4&p=85625&viewfull=1#post85625

**Comment by jbrazio** [comment]
Yes we can force 1.6.x, I submitted a PR to address this issue today.

**Comment by CONSULitAS** [comment]
#3462

**Comment by CONSULitAS** [comment]
@jbrazio 
Just a second slower. 😦

**Comment by fbarcenas** [comment]
With version 1.6.8 i have problems with the SDCARD file

With 1.6.7 version, the problems is totally solved.
I only want say this, for not force the people to 1.6.8

**Comment by jbrazio** [comment]
humm interesting.
I had a look https://github.com/arduino/Arduino/compare/1.6.7...1.6.8 and there are some changes with ISR and SDCard lib, but AFAIK Marlin does not uses the "internal" SDCard lib of Arduino.

**Comment by Roxy-3D** [comment]
@fbarcenas 

We never did get to 'Root Cause' of why certain versions of Arduino create sick versions of Marlin.  It could be the libraries included with Arduino.  But it also could be a problem in the GCC compiler.  It might even be a problem with Marlin code.  We just don't know.

This would be a valuable thing to know and fully understand.  But it would take a lot of effort to get the answer and right now nobody has the time (and capability) to do it.   So until we get this fully resolved, we probably should just stick to the 'Known Working' versions of the compiler.  

But...   I have a quick question...  Is this documented anywhere besides having the source code blow up when you try to compile it?   I can't find any other reference to this requirement.

**Comment by paulusjacobus** [comment]
Hi Roxy my compilers 1.6.8 and 9 do compile properly so it must be somewhere in the libraries. I did a clean install, so removed the old ide first.

**Comment by Roxy-3D** [comment]
But did you get the failure when you compiled using the other versions?

**Comment by fbarcenas** [comment]
I never remove everything(with folders library and hardware) when i install a new version of arduino. Can be this a problem?
A stupid question....: i use mac version...can do more or less problem for use win or mac version??

**Comment by paulusjacobus** [comment]
@Roxy no I never got the error before. I actually had to move to 1.6.8 on
one of my laptops in order to flash the printrbot Rev F board for a friend
(requires teensy2+ drivers and programmer, so a daunting task). So I really
wonder if old IDE files when left on the PC causes the issue. I never tried
to install multiple versions on one laptop to see if it still compiles. I
will try this out during weekend after testing RCBugFix on my CoreXY
(request from Scott)

**Comment by CONSULitAS** [comment]
@fbarcenas 
I recently had the problem, when updating Arduino (on my Mac), that the Liquid Chrystal library did not work. Compiler errors.

After searching and cursing the IDE i found out that in the newer version the library is delivered as a standard library in the package. For the older IDE i still had the library in my user/Arduino/libraries/ folder. But this was an old version and not compatible.

Removed the old library and everything was fine again.

So: Do some housekeeping after upgrades and be sure that there are no old libraries which could disturb.

**Comment by Roxy-3D** [comment]
> Removed the old library and everything was fine again.
> 
> So: Do some housekeeping after upgrades and be sure that there are no old libraries which could disturb.

Is there a way for the source to check which or how many of a given library is being used?   I think multiple copies of the LCD library have caused problems before.

**Comment by thinkyhead** [comment]
> which or how many of a given library is being used?

Only if the library includes a define for its version. All libraries should, but probably there are a lot that don't.

For libraries that don't include a version, you can use other tricks. You can check to see if a `#define` symbol that you know exists in an earlier version of the library is now undefined, or look for a define that only exists in the newer library. These tricks are brittle —newer versions of libraries may break them— but they can often work for all known versions.

**Comment by fbarcenas** [comment]
With my last tests i found that the version of arduino always is correct for me:
(https://github.com/MarlinFirmware/Marlin/issues/3368)

**Comment by jbrazio** [comment]
This has been addressed with PR #3462
