### ISSUE TITLE
How to give a command from menu?

### ISSUE THREAD

**Issue by bovolk** [MarlinFirmware/Marlin#3465]
I want M600 from menu. Instead of pause of printing. Where to change? Thanks!

**Comment by jbrazio** [comment]
I believe you're looking [for this](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/ultralcd.cpp#L742-L744).

**Comment by thinkyhead** [comment]
Enable the option

``` cpp
#define FILAMENTCHANGEENABLE
```
