### ISSUE TITLE
You could change the current print Z height saved to the SD card,

### ISSUE THREAD

**Issue by liangruiben** [MarlinFirmware/Marlin#3478]
能否把当前打印的Z高度保存到SD卡，这样断电可以重新打印
You could change the current print Z height saved to the SD card, so that power can print again

**Comment by thinkyhead** [comment]
Something like this? https://github.com/MarlinFirmware/Marlin/pull/2179/files

Please post this as a Feature Request to https://github.com/MarlinFirmware/MarlinDev, making sure that it has not already been requested.
