### ISSUE TITLE
error: 'DEBUG_POS' was not declared in this scope

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#3486]
There is a:
# define DEBUG_POS(PREFEX,VAR) do{ ...}

later...  But the first reference to it in the Marlin_main.cpp file is before it....

Marlin_main.cpp:494:86: error: 'DEBUG_POS' was not declared in this scope

```
if (DEBUGGING(LEVELING)) DEBUG_POS("sync_plan_position_delta", current_position);
```

And print_xyz() isn't defined at that point in time either!

**Comment by jbrazio** [comment]
@Roxy-3DPrintBoard I can't reproduce the error on my side, which config are you using ?

**Comment by Roxy-3D** [comment]
Well...  Actually... You don't even need to have the configuration parameters...  If you look where DEBUG_POS is used, it hasn't been defined yet.   

But I was using something close to:

```
#define DELTA
#define Z_PROBE_ALLEN_KEY
#define MANUAL_ALLEN_KEY_DEPLOYMENT
#define IGNORE_STOWED_Z_PROBE
#define AUTO_BED_LEVELING_FEATURE // Delete the comment to enable (remove // at the start of the line)
#define DEBUG_LEVELING_FEATURE
#define Z_MIN_PROBE_REPEATABILITY_TEST  // If not commented out, Z Probe Repeatability test will be included if Auto Bed Leveling is Enabled.
```

Just turning on DELTA or SCARA and DEBUG_LEVELING_FEATURE should be enough to cause it.

And I guess this is a little bit off topic, but the reason I hit this is because I'm trying to get my lame Allen Key probe to work again.   There is a 1/2 page of directions talking about using Z_MIN for a probe and dual probes and this and that.   None of it makes sense to me.   We need to get good directions for people that have lame Z Probes !    Maybe a table or something.  I don't know.  Somebody spent a lot of time trying to document what to turn on in the Configuration.h file, but it didn't make sense to me.

**Comment by thinkyhead** [comment]
Sorry about that – more patches to print_xyz are coming too….

**Comment by Roxy-3D** [comment]
That code is in the M114 handler.   I just commented out the problem and will continue my debug session later today.     

I already turned off the Z_PROBE_ALLEN_KEY stuff.   And I'm going to re-read all the text talking about Z_MIN Probes...  Maybe I had some mental block keeping me from understanding the right things to turn on.

**Comment by jbrazio** [comment]
You could move the `#define DEBUG_POS(PREFEX,VAR) do{ ...}` into Marlin.h inside a `#ifdef` block. But @thinkyhead has greater plans for the overall solution so I propose to wait for his final PR instead of messing with a temporary solution.

**Comment by thinkyhead** [comment]
Ok, #3504 adds debugging support for `vector_3` and earlier commits moved definition of `DEBUG_POS` closer to the top of the source.

**Comment by Roxy-3D** [comment]
Why does the HAS_Z_PROBE macro act sick on my machine?

**Comment by thinkyhead** [comment]
@Roxy-3DPrintBoard Is there a compile problem or does it act up when you run Marlin? What is the `Z_MIN_PROBE_PIN` value in your board's pins file? What kind of probe are you using? What connector is it plugged into? And what probe options do you have enabled in the config?
