### ISSUE TITLE
Marlin had the function of the serial number, is used to identify the printer

### ISSUE THREAD

**Issue by liangruiben** [MarlinFirmware/Marlin#3507]
marlin有没有序列号的功能，用于识别打印机
Marlin had the function of the serial number, is used to identify the printer
当我有很多很多台打印机的时候，靠端口号来区分是不可能的事情了，因为端口号有可能更改的
When I have a lot of a lot of printer, by the port number to distinguish is impossible, because the port number may change

**Comment by jbrazio** [comment]
You have the following on `Configuration.h`:

```
// Define this to set a unique identifier for this printer, (Used by some programs to differentiate between machines)
// You can use an online service to generate a random UUID. (eg http://www.uuidgenerator.net/version4)
//#define MACHINE_UUID "00000000-0000-0000-0000-000000000000"
```

When set it should be visible on serial output when sending the G-Code `M115`.

**Comment by liangruiben** [comment]
谢谢，我准备开发服务软件，一个开源的，集中管理3D打印机，在搜集需要用到的固件支持
Thank you, I'm ready to develop service software, an open source, centralized management of 3d printers, collecting need firmware support

**Comment by liangruiben** [comment]
可以在LCD上修改吗？
Can be modified on the LCD?

否则就需要每台打印机的固件都要不同
Otherwise we need every printer firmware should be different

其实这个ID需要这么麻烦，只需要有4位数字就可以应付绝大多数场景了
Actually this ID need so trouble, only need to have 4 digits can deal with most of the scene

或者用一个命令修改他，存放到EEPROM
Block command to change him, Storage block into the EEPROM

和打印机名字
And printer name

**Comment by jbrazio** [comment]
`MACHINE_UUID` must be set at compile time and currently cannot be changed. I believe we can accept this a Development Request for MarlinDev if enough interest is shown by the community for such feature.

**Comment by thinkyhead** [comment]
@liangruiben All of these add-ons are possible. They are trivial, even. So why not fork Marlin and find a programmer in your local area to help you customize it as you need? The main Marlin project has other priorities right now. That is why we ask you to make this a Feature Request on the MarlinDev Issue Queue. We will get to it… someday. If you need features right now, you will have to hire help. Please pay them well for their time!

**Comment by liangruiben** [comment]
marlindev 与marlin有什么不同，我是否应该使用marlindev
What's the difference between marlindev with marlin, marlindev should I use

**Comment by thinkyhead** [comment]
MarlinDev is in a holding pattern, but it is the place where we will be implementing new features in Marlin 1.2.0 and beyond. It is on hold until we finish 1.1.0 – which is coming soon.

**Comment by Roxy-3D** [comment]
Or stated differently...  MarlinFirmware/Marlin is where the stable and most bug free releases are.

MarlinFirmware/MarlinDev is where the evolution of Marlin happens.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
