### ISSUE TITLE
Picture files for status screen variants

### ISSUE THREAD

**Issue by tkurbad** [MarlinFirmware/Marlin#3509]
Hi,

I've got a little "feature" request:

Could someone please check in or point me to a source of the original bitmap files the status display C macros in dogm_bitmaps.h were generated from.

I want to change the status bitmap in my fork of Marlin, but I am having a hard time doing so. So, a "real" picture format (*.png, *.jpg, *.xbm, ...) of the graphical LCD elements would be really appreciated.

Or is there a way to convert the C macros back to a picture format?

Thanks in advance!

Best,
Torsten

**Comment by Blue-Marlin** [comment]
https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/dogm_bitmaps.h#L24
https://github.com/AnHardt/Marlin/tree/lcd-speedup/Marlin/graphics
https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/fonts/README.fonts
https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/fonts/make_fonts.bat
https://github.com/MarlinFirmware/Marlin/wiki/LCD-Language

**Comment by tkurbad** [comment]
> https://github.com/AnHardt/Marlin/tree/lcd-speedup/Marlin/graphics

Something like that I've been looking for. Thank you.

**Comment by CONSULitAS** [comment]
@tkurbad 
Is your request answered successfully? If yes, please close this issue for housekeeping. Thanks in advance.

**Comment by tkurbad** [comment]
Yes, I could accomplish what I was up to. Thanks!
