### ISSUE TITLE
M117 after leveling bed does not work anymore (RCBugFix)

### ISSUE THREAD

**Issue by Alex9779** [MarlinFirmware/Marlin#3510]
I am on `RCBugFix` from last night with a RepRap Discount LCD.

When doing the bed leveling (some lines are still missing there but that's already covered in another issue) and then doing a print `M117` command in the string doesn't print on the LCD.

The LCD still says "Leveling finished" or what ever the message after leveling is.

After a reboot and doing nothing on the LCD it works though.

I have seen this issue too when doing something else in the menu but can't remember exactly what but maybe the first descriptions helps to track it down?

**Comment by thinkyhead** [comment]
@Alex9779 What happens if you put `M400` right before `M117`?

**Comment by thinkyhead** [comment]
Here's a solution for you. Change the line:

``` cpp
LCD_ALERTMESSAGEPGM(MSG_LEVEL_BED_DONE);
```

…to…

``` cpp
LCD_MESSAGEPGM(MSG_LEVEL_BED_DONE);
```

**Comment by Alex9779** [comment]
So due to the merge I don't have to fix myself, right? And this is closed, right?

**Comment by jbrazio** [comment]
@Alex9779 you only have to download the latest RCBugfix, the patch is merged there.
Usually you should close this ticket as soon as you confirmed the we have solved your problem.

**Comment by Alex9779** [comment]
Oh ok, didn't know your policy how to handle this...
