### ISSUE TITLE
PID_PARAMS_PER_EXTRUDER not working since RC3->RC5

### ISSUE THREAD

**Issue by FalloutBe** [MarlinFirmware/Marlin#3519]
When enabling `PID_PARAMS_PER_EXTRUDER`, code gives errors when compiling.

This happens since I changed from 1.1 RC3 to RC5
Tested in Arduino 1.6.8

**Comment by thinkyhead** [comment]
Thanks for the report! Should be fixed with #3525.

**Comment by FalloutBe** [comment]
Thanks for fixing it! I'm glad I could help

**Comment by CONSULitAS** [comment]
@FalloutBe Thank you for your interest making Marlin better.
I am closing this for housekeeping.
