### ISSUE TITLE
M109 hanging when previously interrupted

### ISSUE THREAD

**Issue by JFD-Mtl** [MarlinFirmware/Marlin#3523]
Hi, I recently began updating the Marlin on my Printers (previous: 1.0.2, new: current Marlin, constantly updated by git pulls)

I have noticed that whenever, during the start of a print, I interrupt a M109 (set and wait for hotend temp) by using "stop print" on my controller, when I restart the print, the print never takes off and gets stuck at the M109. Then, If I do something to bring the hotend outside of the "close temperature range", let's say by manually extruding a lot of material, the M109 kick in and the print start.

so, to resume, I get this behavior when:
Start a print:
- Set Temperatures (M190, M104)
- Zero all axis
- Wait for Hotent Temperature (M109)
  Stop The print before the temperature has been reached (note: set temperatures stays set )

Restart the print
- Set Temperatures (M190, M104)
- Zero all axis
- Wait for Hotent Temperature (M109)
- It then waits for a very long time

I do not get this behavior when:
Manually set the temperatures
Wait until the temperatures are stable
Start a print:
- Set Temperatures (M190, M104)
- Zero all axis
- Wait for Hotend Temperature (M109)

It also happened at least once when I stopped a print while it was printing its first layer.

Thanks

**Comment by jbrazio** [comment]
> Wait for Hotent Temperature (M109) Stop The print before the temperature has been reached (note: set temperatures stays set ) Restart the print

This only happens when you stop the print with temp very close to target temp or this happens when you stop the print at any given temperature ?

**Comment by JFD-Mtl** [comment]
it doesn't seem to change much whether I interrupt the `M109` when the temperature is still climbing or during its residency period.

**Comment by JFD-Mtl** [comment]
It does show this behavior on the two printers I recently flashed with the current Marlin. But I must add that I can't reproduce this every single time. I guess there are some parameters influencing the bug that I still don't understand.

**Comment by thinkyhead** [comment]
Sounds like we might need to reset the residency timer when someone cancels heating – e.g., by using Stop Print from the LCD. Some state is not being reset.

**Comment by thinkyhead** [comment]
@JFD-Mtl What values are you using for `TEMP_RESIDENCY_TIME` and `TEMP_HYSTERESIS`?

**Comment by JFD-Mtl** [comment]
``` cpp
#define TEMP_RESIDENCY_TIME 10  // (seconds)
#define TEMP_HYSTERESIS 3       // (degC) range of +/- temperatures considered "close" to the target one
#define TEMP_WINDOW     1       // (degC) Window around target to start the residency timer x degC early.
```

**Comment by thinkyhead** [comment]
@JFD-Mtl During heating there should be some temperatures logged to the serial console. If you happen to catch this in action, could you post the console output here for us to look at?

**Comment by JFD-Mtl** [comment]
I usually run the printers in standalone. I will get this data Monday.
We have 6 printers. 4 of them running on Marlin. I only have problems on the two with the newer Marlin.

**Comment by JFD-Mtl** [comment]
Can you be more specific on that part of the temperature log you need? I guess you need a sample of the console in debug mode while it hangs ?

**Comment by thinkyhead** [comment]
You can sample temperatures with `M105` any time the machine is accepting commands. But during heating with `M109` commands are blocked, so without any debug mode required, temperatures will be printed to the console if one is attached. Just Connect from Pronterface before you start any standalone SD printing. What we need to see is the temperatures being displayed, what Marlin "thinks" is going on. It _might_ provide a clue, or not.

**Comment by thinkyhead** [comment]
If this issue is fixed, I can close this topic, yes?

**Comment by JFD-Mtl** [comment]
Ill reflash one of the printer with latest Marlin and keep you updated

**Comment by thinkyhead** [comment]
Today's `RCBugFix` is better than yesterday's.

**Comment by JFD-Mtl** [comment]
I tested it shortly with the current RCbugFix and it seems to be working properly.

Thanks
