### ISSUE TITLE
Speed movement for each motor

### ISSUE THREAD

**Issue by schirrel** [MarlinFirmware/Marlin#3558]
Hi i wanna know if its possible, in code, to set the movement speed for each motor.
e.g: i want the E to do 80 mm/s, the X 255 mm/s and the Y 15mm/s.
I tried to use  `plan_buffer_line(current_position[(X_AXIS)], current_position[(Y_AXIS)], current_position[(Z_AXIS)], current_position[E_AXIS], 100.0, active_extruder);` and changing the feed rate but, at least at my p.o.v, the feedrate is the speed for all together, therefore i wasn't accomplishing what i want.
No, the use of it isn't for a 3D printer so theres no need of them to be coordinated.
So now i'm wondering if it is even possible.

**Comment by Blue-Marlin** [comment]
Simple answer: No!
In Marlin the axes **are** coordinated. Otherwise the axes would not arrive at the same time.
If you want to have determined speeds for every axis **you** have to calculate a mating target point

**Comment by schirrel** [comment]
Thanks @Blue-Marlin
