### ISSUE TITLE
changing feedrate by the command of "M203"

### ISSUE THREAD

**Issue by drinkingcode** [MarlinFirmware/Marlin#3562]
when i changed feedrate with the command of "M203 X200 Y200" (default feedrate: x300 y300) ,then tested, i found it didn't work, so do you meet the same problem and how do you solve it ?

**Comment by manianac** [comment]
Curious, how are you sure it did not work?  I've changed acceleration and max feedrate before without issue.

**Comment by drinkingcode** [comment]
@manianac  test as following:

```
G1 X0 Y0
M203 X300 Y300 
G1 X800 Y800
```

calculating the time of 0 to 800

```
G1 X0 Y0
M203 X200 Y200
G1 X800 Y800
```

calculating the time of 0 to 800

Result:
the time of "M203 X300 Y300" is about 12.12s
the time of "M203 X200 Y200" is about 11.99s

So I think it doesn't work no matter how i change the Feedrate of XY.

**Comment by thinkyhead** [comment]
@WillSmithInChina Try these tests to get a bit more contrast, and to actually set a max feedrate for the moves.

```
G1 X0 Y0
M203 X500 Y500 ; typical high feed rate
G1 X800 Y800 F5000
```

…then…

```
G1 X0 Y0
M203 X60 Y60 ; makibox slow feed rate mm/s
G1 X800 Y800 F5000
```

**Comment by drinkingcode** [comment]
@thinkyhead changing speed by using "M220" and "M221" ,thanks again !

**Comment by manianac** [comment]
@WillSmithInChina Whats your acceleration settings?

I find M203 X500 Y500 to fly as it should, and X60 Y60 all work properly.

Realize if you're testing with only a G1 command, you need to set the feedrate with the F var in mm/min as it will use the last set speed (usually a slow move).

So when I do

``` gcode
G28 X0 Y0
M203 X500 Y500
G1 X800 Y800 F30000
```

It sails amazingly fast.

**Comment by thinkyhead** [comment]
@manianac [Three backticks](https://guides.github.com/features/mastering-markdown/) is your friend for multi-line code.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
