### ISSUE TITLE
starting print doesn't work 

### ISSUE THREAD

**Issue by drinkingcode** [MarlinFirmware/Marlin#3574]
Before starting print, when i set extrude temperature which is the same as 
the  command (M109 S230.000000) in gcode file, starting print doesn't work ;

But when i set extrude temperature not the same as "M109 S230.000000" before printing,
starting print works fine.

Do you  meet the same problem ? if you konw that, please tell me,
thank you, guys !

**Comment by drinkingcode** [comment]
when the current extrude temperature is the same as the command(M109 S230.000000) in gcode file,
starting print will not work

**Comment by thinkyhead** [comment]
I thought we fixed this in the latest code. We'll have to have another look…

**Comment by drinkingcode** [comment]
@thinkyhead thank you for all you did

**Comment by jbrazio** [comment]
@WillSmithInChina do you still have the issue ? If so could you please provide a few lines of serial output. Thanks.

**Comment by thinkyhead** [comment]
I looked over the code in `M109` (`RCBugFix` of course) last night. I couldn't find any condition where it would get stuck. So maybe @WillSmithInChina is using an older version of Marlin…? He seems to be seeing various bugs that I'm sure we fixed after RC5.

**Comment by jbrazio** [comment]
I have the feeling we may have something going on with the bed PID or the recent `HISTERISYS` stuff as we have at least a couple is reports about printing never starting. One of them (I am in mobile can't link to issue) the serial log shows bed temp is always 2C behind target.

**Comment by thinkyhead** [comment]
@jbrazio So you think it might be in the conversion between celsius and "thermistor stuff"? But I believe the heater is turned on and off based on the celsius value, so it should stay on until it reaches the target.

**Comment by jbrazio** [comment]
That's exactly the strange part.. Data is not sufficient but the PID seems to settle the temp a couple of degrees of the target with a stable PWM value.

**Comment by thinkyhead** [comment]
That just sounds like poor PID tuning. There should be a little overshoot in a proper PID. Apparently we have a new `M303` in the queue to allow just that… to tune with some overshoot.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
