### ISSUE TITLE
G29 probing

### ISSUE THREAD

**Issue by renzaaa** [MarlinFirmware/Marlin#3583]
After G28 comand, not properly probing. G28 - home to bed center and after G28 Y axis not move to front bed position. Just moving to bed right, bed left and from bed left to bed back and touch to printer body. Why missed front bed position?

**Comment by thinkyhead** [comment]
- What version of Marlin are you running?
- Can you post your configuration files so we can look them over?

**Comment by renzaaa** [comment]
Marlin version is 1.1.0 RC5.
[config.txt](https://github.com/MarlinFirmware/Marlin/files/231884/config.txt)

**Comment by renzaaa** [comment]
With Marlin RC3 version everything is fine.

**Comment by thinkyhead** [comment]
@renzaaa You should test `RCBugFix` because we might have already fixed this!

**Comment by renzaaa** [comment]
I will try.
Thanks.

**Comment by StrannikZet** [comment]
I tested the RC Bug Fix, but after the G28 and measuring the center of the table with the G29, the printer considers it Y0. After the ninth point, if you manually send home at X0 Y0, Y - and resets the value becomes -11.5 or more. Example ninth point X = 280 Y = -11.3, but must be X = 280 Y = 280 (approximate data).
[conf.zip](https://github.com/MarlinFirmware/Marlin/files/233951/conf.zip)

**Comment by thinkyhead** [comment]
I will look at your configs and see how they must be affecting the homing. I might list out what I _think_ should happen based on your settings, and we can compare notes.

**Comment by StrannikZet** [comment]
I miss RCBugFix again and try. If the problem persists, show videos and action logs. If everything is OK, I'll write. Prior to that tested in the firmware download, this Saturday. Maybe there were some changes on the test bench all ok.

**Comment by StrannikZet** [comment]
Testbed. As long as the printer will be able to check out the evening. I am confused here these values.
Why is this value:

```
10:30:57.098 : >>> set_bed_level_equation_lsq > current_position: (275.00, 298.00, 87.95)
```

Changes to this

```
10:30:57.117 : <<< set_bed_level_equation_lsq > corrected_position: (276.47, 307.45, 34.68)
```

[log_debug.txt](https://github.com/MarlinFirmware/Marlin/files/236101/log_debug.txt)

I could be wrong, but as a check on your printer, will show results. It is simply tried to emulate the situation.

**Comment by StrannikZet** [comment]
Hmm ... I got a bug fixed renzaaa. Firmware downloaded that morning, kind of like working properly. Sorry and thank you!
