### ISSUE TITLE
Extruder temp. not cooling down when command given from LCD "Cooling down"

### ISSUE THREAD

**Issue by garaguido** [MarlinFirmware/Marlin#3591]
When I start a print from the SD card on the LCD , first the bed is warming up and when setpoint temp is set then Extr. temp. is rising .  
.
When the bed is not at the setting temp. , and then I give a "Stop print " command the printing is stopped , but the bed temp is still rising .

Then I give a "Cooling down" command but only the bed temp is cooling down and the extr. temp begins on rising. 
For cooling down the extr. temp , I must give the command "Motors out" and then the temp. from extr. is then cooling down.

Wy can the extr. not cooling down or stopped when the command "Cooling down " is given ?
Mybe "Cooling down all " is better I think?

**Comment by thinkyhead** [comment]
I m hvng a hrd tm rdng ths. Cld u pls rephrs?
