### ISSUE TITLE
Arduino IDE 1.6.x + Marlink Arduino Addons + Gen7

### ISSUE THREAD

**Issue by andreiciocanvlad** [MarlinFirmware/Marlin#3599]
I can't get to show Gen7 in the board menu with the addon files. How to fix this ?

**Comment by thinkyhead** [comment]
I think you have to actually select "Sanguino" as the board. (Someone please correct me if I'm wrong, but selecting "Sanguino" actually compiles with `MOTHERBOARD BOARD_GEN7_14`.)

However the Sanguino files, the package download info file (`package_marlinfirmware_index.json`), and `boards.txt` need an update before they will work. I'm working on an update so you'll be able to just update the package from within Arduino IDE. Meanwhile, you can download [MarlinPlatform-1.6.7-b.zip](https://github.com/MarlinFirmware/MarlinDev/archive/MarlinPlatform-1.6.7-b.zip) if you want to manually replace the package yourself.

**Comment by thinkyhead** [comment]
I used the right checksum for the download file (two different tools give the same hash) but Arduino IDE doesn't like it. So, for now just download the .zip and install manually.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
