### ISSUE TITLE
Question about filament change (not bug)

### ISSUE THREAD

**Issue by schirrel** [MarlinFirmware/Marlin#3600]
I remember, not right where here i've tried to found but i didn't, a topic about changing filament, and there were a discussion about only having it in printing time, about there's no routine about changing filament before, or after printing.
I'd like to know if it still on, or if you guys, or anyone else, have done this routine, because i have done something like it in this past few days  and i'd like to share, but i wanna know first if i has been solved to compare my code.
Thanks

**Comment by schirrel** [comment]
#3264

**Comment by jbrazio** [comment]
Please share, we will gladly review it.

**Comment by schirrel** [comment]
Sure @jbrazio, i have done this in RC3, i will now download the RC5 and make it.
Just an observation it only work with 1 extruder. As soon as i finish it i will share. 
What way is best, do a pr against rcbugfix ou showing the code?

**Comment by schirrel** [comment]
I've made pr #3601
