### ISSUE TITLE
Typo in planner.cpp?

### ISSUE THREAD

**Issue by Sebastianv650** [MarlinFirmware/Marlin#3604]
During my work on the advance feature I stumbled about this lines

```
void calculate_trapezoid_for_block(block_t* block, float entry_factor, float exit_factor) {
  unsigned long initial_rate = ceil(block->nominal_rate * entry_factor); // (step/min)
  unsigned long final_rate = ceil(block->nominal_rate * exit_factor); // (step/min)
```

All values inside Marlin I saw are seconds, mm, steps and their derivates. I think this should be (steps/s)?

**Comment by Blue-Marlin** [comment]
`entry_factor` and `exit_factor` have no dimension.
`block->nominal_rate` is calculated from 

```
block->nominal_rate = ceil(block->step_event_count * inverse_second); // (step/sec) Always > 0
```

so you are right.
