### ISSUE TITLE
plan_bed_level_matrix not declarate

### ISSUE THREAD

**Issue by fbarcenas** [MarlinFirmware/Marlin#3658]
With the last RCBUGFIX happen this:

sketch/Marlin_main.cpp: In function 'void gcode_T(uint8_t)':
Marlin_main.cpp:6362: error: 'plan_bed_level_matrix' was not declared in this scope
           offset_vec.apply_rotation(plan_bed_level_matrix.transpose(plan_bed_level_matrix));
                                     ^
exit status 1
'plan_bed_level_matrix' was not declared in this scope

**Comment by ghost** [comment]
@fbarcenas 
I've made a patch(PR #3660).
Try it if you like.

**Comment by fbarcenas** [comment]
Fixed with the change to:

planner.bed_level_matrix

well!!
Please change in the RCBUGFIX!
