### ISSUE TITLE
Babystepper Axis Issue

### ISSUE THREAD

**Issue by daedalus14850** [MarlinFirmware/Marlin#3688]
Hello all, novice here, I'd appreciate your help in resolving an issue.

I've set up Marlin Babystepping for my 3D printer and have hooked up a dedicated LCD to it. Currently, when I start the print and move the dial, the extruder only steps up (not down), and only does so when the printer is printing in the negative y direction.

I have played around with making the multiplicator a negative value, but it didn't seem to help. Regardless of whether I turn the dial left or right (i.e. positive or negative), it makes no difference. The extruder only steps up (i.e. moves in +z). Never down (i.e. -z, which is what I primarily want it to do). And, like I said before, it only does this when the printer is moving in the -y direction. +y, +x, and -x do not register/process any input from the dial. Any help will be greatly appreciated. Thank you!

**Comment by thinkyhead** [comment]
What version of Marlin are you using?

**Comment by daedalus14850** [comment]
Thank you for the quick response. Currently using a modified version of Marlin_RAMPS-Epcos_i38 with Arduino 1.6.7.

**Comment by thinkyhead** [comment]
Is there something in your modified Marlin that you cannot do without, and which is not in the main branch? We've advanced the firmware a lot, and chances are issues in a custom fork are long fixed in the main one. i would recommend you upgrade to the latest code, rather than spend too much time beating that horse,

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
