### ISSUE TITLE
G3 negative I problem 

### ISSUE THREAD

**Issue by mirecta** [MarlinFirmware/Marlin#3690]
Hi i build laser engraver ramps + marlin everything works but i engraving something from inkscape with plugin which use G2 G3 commands even with negative I or J 

if i send to machine 

``` gcode
G2 X100 Y100 I1.2208 J16.3622 ; machine do it (CW)
G3 X100 Y100 I1.2208 J16.3622 ; OK too (CCW)
```

and 

``` gcode
G2 X100 Y100 I-1.2208 J16.3622 ; machine do it with CCW arc
```

but 

``` gcode
G3 X100 Y100 I-1.2208 J16.3622 ; machine do nothing !!!!
```

**Comment by jbrazio** [comment]
@mirecta you will have to contact directly the maintainer of the Marlin fork you're using, this is the repo for the official Marlin which currently does not support laser engraving.

**Comment by mirecta** [comment]
i use this marlin and patch it for laser , i add three new commands M160 M161 M162 but i didnt touch anything other so i use master from this repo

**Comment by mirecta** [comment]
so u can fix this

**Comment by mirecta** [comment]
G3 command is indipendent to tool which i use (3d printer, mill , laser etc)

**Comment by jbrazio** [comment]
Indeed, but we don't know if the bug is coming for the additional code base on top of Marlin.
We have no reports of CCW arc being broken.

Which is the base version of Marlin you're using ?

**Comment by mirecta** [comment]
my revision f0203728f30d7809dfc74c880f1eea2df87be4d1
Fri Apr 15 16:15:43 2016 -0700

i wrote tat G3 works but only with positive parameters I and J

**Comment by jbrazio** [comment]
After that ref id two PR were merged regarding arcs: #3502 #3514.
I would suggest to test the latest RCBugfix branch.

**Comment by thinkyhead** [comment]
I recently worked on the arc code, and found it to function really well on my Cartesian machine. I haven't tested it on COREXY or DELTA, so if you have one of those, and you still have a problem, I would value your feedback on the current RCBugFix. This is one feature that should "just work."

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
