### ISSUE TITLE
I am a douchebag!

### ISSUE THREAD

**Issue by animalextract1982** [MarlinFirmware/Marlin#3692]
I am a douchebag. Please help me to overcome this problem.

**Comment by boelle** [comment]
hmmm

I have:

- Quality Real Passport

- Visa

- Driving License

- ID CARD

All above is genuine government or bank issued, free of charge :-D

but i don't have:

- etc

**Comment by emartinez167** [comment]
Can I get one too? :P

**Comment by boelle** [comment]
I guess you have most of the stuff too :-P

Maybe we should sell his email address and use the money for development of marlin?

**Comment by emartinez167** [comment]
Ha ha ha ha excellent idea! Let's offer it to him first. Such a wanker
would surely fall for it.

**Comment by boelle** [comment]
Don't tempt me :-D
