### ISSUE TITLE
Compile error for SAV MK1

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3704]
in ArduinoAddons/Arduino_1.6.x i found that there are support for my board

i copy the marlin folder from there to my hardware folder as i would with any board.

when i compile i get:

```
WARNING: Category '' in library Wire is not valid. Setting to 'Uncategorized'
Warning: platform.txt from core 'Marlin AVR Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
sketch\libraries\twi.c:1:17: fatal error: twi.c: No such file or directory

 #include <twi.c>

                 ^

compilation terminated.

exit status 1
Error compiling for board SAV MkI (CDC).
```

**Comment by boelle** [comment]
upps... IDE had repetier firmware open as default, but its more or less the same with marlin:

```
WARNING: Category '' in library Wire is not valid. Setting to 'Uncategorized'
Warning: platform.txt from core 'Marlin AVR Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
In file included from sketch\pins.h:105:0,

                 from sketch\Conditionals.h:270,

                 from sketch\Configuration_adv.h:688,

                 from sketch\Configuration.h:1129,

                 from C:\Users\Bo\Desktop\Marlin\Marlin.ino:37:

pins_SAV_MKI.h:31: error: #error Oops! Make sure you have 'Teensy++ 2.0' selected from the 'Tools -> Boards' menu.

   #error Oops!  Make sure you have 'Teensy++ 2.0' selected from the 'Tools -> Boards' menu.

    ^

In file included from sketch\Marlin.h:43:0,

                 from sketch\thermistortables.h:26,

                 from sketch\Configuration.h:1130,

                 from C:\Users\Bo\Desktop\Marlin\Marlin.ino:37:

fastio.h:4041: error: #error pins for this chip not defined in arduino.h! If you write an appropriate pin definition and have this firmware work on your chip, please submit a pull request

   #error pins for this chip not defined in arduino.h! If you write an appropriate pin definition and have this firmware work on your chip, please submit a pull request

    ^

exit status 1
#error Oops! Make sure you have 'Teensy++ 2.0' selected from the 'Tools -> Boards' menu.
```

**Comment by boelle** [comment]
hmm... need to figure why it wants Teensy++ 2.0 and not SAV MK1

EDIT: prob because of this:

``` cpp
/**
 * SAV MkI pin assignments (AT90USB1286)
 * Requires the Teensyduino software with Teensy++ 2.0 selected in Arduino IDE!
 * http://www.pjrc.com/teensy/teensyduino.html
 * RepRap Clone Wars project board.
 */

#ifndef __AVR_AT90USB1286__
  #error Oops!  Make sure you have 'Teensy++ 2.0' selected from the 'Tools -> Boards' menu.
#endif
```

but then why is the board listed in the addon folder.... does not make sense to me, might need to sleep on it

**Comment by Roxy-3D** [comment]
I forget what the reason is...   But the PrintRboard requires you select Teensy in order to compile and flash the board.   I bet the reason your board is saying this is the same reason the PrintRboard says that.   If you learn more about what is going on, please post it!

**Comment by boelle** [comment]
in hardware\marlin\avr\variants\at90usb\pins_arduino.h

**AVR_ATmega32U4** is the only one.... could this be it?

**Comment by boelle** [comment]
yep.... if i select the teensy++ 2.0 and not SAV MK1 it compiles and opens the teensy loader

so that makes the addons a bit not needed for now....

**Comment by boelle** [comment]
damm.... 

tired so off to bed with me, more time tomorrow to poke arround in this

**Comment by thinkyhead** [comment]
@boelle [Three back-ticks](https://guides.github.com/features/mastering-markdown/) for multi-line code quoting, please!
(I have edited your posts to make them readable.)

Otherwise, interesting observations! Hopefully we can get this sorted out soon.

**Comment by boelle** [comment]
well i can live with selecting teensy++ 2.0 if that makes it work

**Comment by thinkyhead** [comment]
@jbrazio We should make sure this is covered in the official documentation. We should just do a page for each of the boards we support – as specified in the `boards.h` file.

**Comment by emartinez167** [comment]
@jbrazio, I am looking after the Rigidbot in this forum and we have a wiki we have been maintaining to keep anything related to those machines. It would be great for me to be able to contribute the specifics for that machine to the official documentation. Please let me know how to proceed.

Regards,

Ernesto

**Comment by jbrazio** [comment]
@emartinez167 Please have a look at [MarlinFirmware/MarlinDocumentation](https://github.com/MarlinFirmware/MarlinDocumentation) if you require assistance please open a issue request on that repo.

@thinkyhead This is the [current list](http://www.marlinfw.org/articles/hardware/boards.html) of supported boards, would you like to have specific configuration options for each group of them ? I require to know in fact which boards do we _actually_ support (i.e. all the boards in `boards.h`?)

**Comment by boelle** [comment]
@Roxy-3DPrintBoard... so you compiled and flashed from IDE 1.6.8 ?

**Comment by boelle** [comment]
@Roxy-3DPrintBoard alive?

**Comment by Roxy-3D** [comment]
I have not ventured into the IDE 1.6.8 world yet with my PrintRboard.    I've been super busy.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
