### ISSUE TITLE
Reprapdiscount smart controller

### ISSUE THREAD

**Issue by Scratchbuild52** [MarlinFirmware/Marlin#3721]
Hi there,

Printer: Prusa I3
board: Adruino Mega + Ramps1.4

From the time I installed RC6  the display alternates the X,Y and Z with question marks on the info screen. The 4th line also seems to get stuck on the same error message once it is displayed.

Regards

Nic

**Comment by jbrazio** [comment]
Then alternating `?` means that the printer doesn't know its current position thus you need to do a `G28`, but when the steppers time out, you'll see `?` flashing again.

**Comment by Scratchbuild52** [comment]
Thanks so much!
