### ISSUE TITLE
WE NEED YOUR HELP !

### ISSUE THREAD

**Issue by jbrazio** [MarlinFirmware/Marlin#3726]
Dear Marlin users and developers, we the Marlin Development team, require your assistance filling the following Google Form: http://goo.gl/forms/gRsLbQmti6

It's a "one minute" survey were we ask you which board and Marlin version you use.
You may submit multiple times for more than one printer.

**Comment by boelle** [comment]
maybe add what IDE they use?

**Comment by emartinez167** [comment]
I have posted it on the G+ Rigidbot forum.

Regards,

Ernesto

**Comment by jbrazio** [comment]
@boelle good suggestion, added.

**Comment by emartinez167** [comment]
Joao,

Some Rigidbot users are not quite sure what to respond regarding the version of Firmware they are on, as it is the original supplied by Rigidbot (we suspect it is an old fork from 1.0). Is there a way for them to provide that information (or add an option stating Rigidbot original FW)?

Regards,

Ernesto

**Comment by jbrazio** [comment]
@emartinez167 I added the option "Other/Builtin" and "Other/Unknown".
Interesting to see those people have never upgraded their firmware, is it for any particular reason ?

**Comment by Blue-Marlin** [comment]
Where can we see the results?

**Comment by emartinez167** [comment]
I believe mostly because of one or more of the following reasons:
a) Code in that version tied to the hardware for that machine
b) a lot of users unfamiliar/uncomfortable with coding Arduino
c) If it ain't broken, don't fix it attitude
d) Lack of knowledge about the existence of a mainstream Marlin
e) Originally the Rigidbot was not officially supported by mainstream Marlin. I submitted the original PR and @thinkyhead completed it for me. It was a long time between the RB coming to the market and the PR. Ini the interim, some RB users with enough knowledge rigged up what is known in the community as RBC (RigidbotCommunity) version which was based on a newer version, but it stayed there and never caught up with the current release.

Regards,

Ernesto

**Comment by jbrazio** [comment]
I will publish the results as soon as people start to stop voting, were is a preview.

![screenshot from 2016-05-11 01-12-03](https://cloud.githubusercontent.com/assets/264365/15166308/7385c686-1715-11e6-905e-a87e2fb810c9.png)

![screenshot from 2016-05-11 01-12-17](https://cloud.githubusercontent.com/assets/264365/15166310/739b5e10-1715-11e6-9ab1-69261d7a1800.png)

![screenshot from 2016-05-11 01-13-04](https://cloud.githubusercontent.com/assets/264365/15166318/8f0fcf82-1715-11e6-82e8-df98f05a00ca.png)

**Comment by RalphSutherland** [comment]
Two problems,  my board not listed, no way to select a custom board (4 power outs: EEFB)   (I chose ramps 1.4 as a default)   No way to allow for not using an unmodified Marlin firmware.  ( I chose the RD branch that I am currently working from, eg RC 6)  I got the IDE question OK :)

**Comment by jbrazio** [comment]
But it's a RAMPS 1.4 or does it have any pin diff ?
I listed all boards on `boards.h`, there was the only way to have some consistency.

**Comment by tkurbad** [comment]
Shouldn't it be 1.1.0-RCx instead of 1.1.1-RCx?

**Comment by jbrazio** [comment]
Damn you're right :-/

**Comment by ghost** [comment]
BOARD_MKS_13 is missing from the list...

**Comment by thinkyhead** [comment]
It should also note that the "MKS" is the same as the "HICTOP" for those who have that branding.

**Comment by boelle** [comment]
Where can we see the results?

**Comment by jbrazio** [comment]
I will post them soon, just waiting for the survey to ran at least one week.

@Roxy-3DPrintBoard could you please share the link in the forums you have access to ?

We are having a bit less than 200 data points right now.

**Comment by boelle** [comment]
are there any results yet?

maybe just view access to the data

**Comment by jbrazio** [comment]
Will do !

**Comment by Roxy-3D** [comment]
@JBrazio   I just saw the request to post it in different forums.   (I need
your email address!!!)

It is posted at both RepRap.org (in the Marlin section) and at
3D-PrintBoard in the RepRap section.

**Comment by jbrazio** [comment]
@Roxy-3DPrintBoard I will post it on the chat we have.

**Comment by VicentM** [comment]
Published in spanish google group (Clone Wars)
