### ISSUE TITLE
Solenoid probe

### ISSUE THREAD

**Issue by hexxter** [MarlinFirmware/Marlin#3734]
I use a Solenoid to auto level. If you enable a solenoid for long time it is overheating. Is it possible to build in a pin what be enabled short before the z probe is used an disable after the measurement? In other words on/off on every step of probing (on each single point).

Thank you for your work Marlin is excellent!

**Comment by Roxy-3D** [comment]
If your mechanical design is tolerant of doing this:  You can switch off the servo after the move.  You can set the timeout value which by default is 300 ms.

**Comment by hexxter** [comment]
sorry i don't know what you mean. If i start the auto bed leveling then the firmware start measuring 9 points on my print bed. The problem is i can only activate the magnet (solenoid) before i start bed leveling but the complete procedure takes to long (–15/20sec) and i get a overheating of the solenoid.
i need a pin toggle on if single measurement step ( in my case 9 3x3).

BR Hexxter

**Comment by Roxy-3D** [comment]
Check out these lines within the Configuration.h file:

``` cpp
// Servo deactivation
//
// With this option servos are powered only during movement, then turned off to prevent jitter.
//#define DEACTIVATE_SERVOS_AFTER_MOVE

#if ENABLED(DEACTIVATE_SERVOS_AFTER_MOVE)
  // Delay (in microseconds) before turning the servo off. This depends on the servo speed.
  // 300ms is a good value but you can try less delay.
  // If the servo can't reach the requested position, increase it.
  #define SERVO_DEACTIVATION_DELAY 300
#endif
```

On your G29 command you may choose to add the 'E' option which will allow retraction of the probe between points to limit how long the servo is energized.

**Comment by Blue-Marlin** [comment]
@Roxy-3DPrintBoard 
He has no servo. He also has no BLtouch. He has a solenoid and just a solenoid. With the low duty cycle servo output he can do nothing. What he wants is a new kind of probe - a solenoid probe. Similar to a servo probe, but instead of changing the servos angle, switching a pin high and low. Together wit the 'E' parameter of G29/M48 he then gets 9 short activation cycles for a 3x3 matrix, instead of one long.

@hexxter 
Sorry until we sorted out the probe problems, at least until we are ready with Marlin 1.1.0 we don't want to integrate new kinds of probes into Marlin. For your own purpose, follow the code-path for a servo probe. Everywhere where a servo-angle is changed switch your solenoid-pin. Then use G29/M48 with the 'E' parameter.

**Comment by Roxy-3D** [comment]
He said:

> I use a Solenoid to auto level. 

So I assumed he had it working to some degree.

> He has no servo. He also has no BLtouch. 

And because I was thinking he had it working to some degree with Auto Bed Leveling I kind of assumed he was using the normal servo stuff to control it.

**Comment by Grogyan** [comment]
@hexxter can you provide more details about your solenoid setup, pictures etc?

I highly recommend you look into the [BLTouch](https://plus.google.com/communities/109126963511513081214) It uses a hall effect sensor to detect changes in the flux of the solenoid to trigger events

**Comment by Blue-Marlin** [comment]
Solenoid on. G29. Solenoid off. 
Works but is overheating the solenoid.
That is kind of working.

**Comment by Roxy-3D** [comment]
One idea might be to have the solenoid turned on in the run_z_probe() code, let the point be sampled, and then turn off the solenoid and wait some amount of time for it to cool.   That is kind of a brute force way to do things so if that approach is tried, it would be wise to call the functions that monitor and control temperature while you wait for the solenoid to cool down.

**Comment by Grogyan** [comment]
If it is getting too hot, then a current limiting resistor in series with the solenoid is required

**Comment by Blue-Marlin** [comment]
Right. It's a matter of balancing power and duty cycle by a resistor in series with the solenoid. 
For example: http://www.produktinfo.conrad.com/datenblaetter/500000-524999/506151-da-01-en-ZYLINDERMAGNET_ITS_LZ_1642_Z_12VDC.pdf has not much power at 5.5W but it can be always on. At 55W the power is much higher, but you cant switch it on for longer than 6 seconds

**Comment by hexxter** [comment]
@Grogyan here pics: https://cloud.kratzer.it/index.php/s/onv2HptA54wBuGO
https://cloud.kratzer.it/index.php/s/cETLHk0QFpVeCPJ
and a short video: https://youtu.be/ylPCh1wYOH8

i use an optical sensor and not an hall sensor. At the moment i have Marlin RC3 running with a dirty patch and it works but i think its was better to have it in the official release. For this Prob is not so many things to do only a configurable pin high short bevor a point is probed and off after the point is measured. 
I build different Probs before and any prob has a problem (mechanical, first you must know the z level,...) and this Prob works fine without so many obstacles.

you can enable the solenoid for 4-6 sec without overheating but after this period you need a couple of sec to cool down. the time between the grid points (auto level) is long enough on my setup, but a configurable wait time is better if you have a small print bed or you drive fast between the grid points.

BOM:
1x http://www.amazon.de/%C3%96ffnen-Frame-Solenoid-Elektromagneten-1-0530Z/dp/B00ICD1OL6/ref=sr_1_4?ie=UTF8&qid=1463043696&sr=8-4&keywords=Solenoid
1x http://www.ebay.de/itm/1-2-3-5-Stuck-IRF520-MOS-FET-Driver-Treiber-Modul-3-3V-5V-fur-Arduino-MCU-ARM-/351237433385?var=&hash=item51c761e829:m:mPTPr_qjh1GvfpcPNuYvdRQ
1x http://www.ebay.de/itm/Optischer-Endschalter-Endtaster-Endstop-fur-z-B-RAMPS-1-4-RepRap-3D-Drucker-/252241899626?hash=item3abac9f06a:g:T14AAOSwYIhWjveM

i use the MOS FET to switch the 12V if you have a power switch on your board free you can use this without the IRF520.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
