### ISSUE TITLE
What is Function FR and the percentage in reprapdiscount full graphic smart controller ??

### ISSUE THREAD

**Issue by pubalan12** [MarlinFirmware/Marlin#3764]
![img-20160515-wa0009](https://cloud.githubusercontent.com/assets/16809492/15273038/8fa9ae88-1abf-11e6-8abf-bb8f5d11c954.jpg)

Thank You

**Comment by paulusjacobus** [comment]
~~Fr stands for flow rate which is used for the extruder. 105 means 1.05 times the normal flow rate. Used to correct the extruding when the filament diameter is slightly off.~~

**Comment by pubalan12** [comment]
ok. Got it. Thanks paulusjacobus.

**Comment by bdowling** [comment]
The FR% on the main screen is for feed rate.  It allows you to increase the speed of your printing if you need to up or down by a ratio applied to all stepper speeds (extruders are adjusted volumetrically). 

Flow rate is tweakable from the tune menu if needed.  Which would only increase or decrease extrusion irrespective to speed.

**Comment by pubalan12** [comment]
got it. Thanks bdowling
