### ISSUE TITLE
 change filament 

### ISSUE THREAD

**Issue by Jinxycob** [MarlinFirmware/Marlin#3765]
hello 
 I just installed  the reprapdiscount full graphic smart controller  on a RAMPS 1.4 using the 1.1.0 RC6 and the option  to change filament is missing, thought it was supposed to be the last option in  TUNE? but cant see the option anywhere in the controller setting.

**Comment by Blue-Marlin** [comment]
`FILAMENTCHANGEENABLE` Configuration_adv.h ?

**Comment by Jinxycob** [comment]
thanks for that, but I do have one problem with it , park the effector plate  ok, but the moment  it finished retracting it moves  slowly straight  into the bed leaving little time to exchange fila.
"have to hit the kill switch every time".

**Comment by thinkyhead** [comment]
Sounds like another issue should be posted about this. Filament change shouldn't be causing that weird Z downward movement.

**Comment by WZ9V** [comment]
I have to do some more testing but when I tried this it seemed like it disabled the X stepper which allowed me to accidentally shift the carriage and thus restart in the wrong place.  I'll do some more testing to see if I can figure out what was happening at the time but I do know it took me a long tome to get the filament changed so it might have been a timeout of some sort.

This was using RC6

**Comment by thinkyhead** [comment]
Hmm… Yeah, if users are going to be fiddling with the extruder, it's probably a Bad Thing™ to disable the axis steppers during the process. Something to patch, along with the weird Z movement.

**Comment by WZ9V** [comment]
I want to see if I can reproduce the problem first, if I can I'll open up an issue because yes the whole point of change filament is to mess with the extruder (changing or swapping filament perhaps) ;-)
