### ISSUE TITLE
#endif without #if

### ISSUE THREAD

**Issue by nefiwashere** [MarlinFirmware/Marlin#3766]
not sure why this is coming out. 

![marlin error2](https://cloud.githubusercontent.com/assets/10413814/15275412/2fe512ee-1a88-11e6-998a-d2731a276b84.JPG)

**Comment by Blue-Marlin** [comment]
The most likely reason is - **you** added an `#endif` in `Configuration.h` or deleted a `#if`

**Comment by samimoallem** [comment]
how can i fix it?

**Comment by thinkyhead** [comment]
> how can i fix it?

Start with a fresh configuration and be attentive.
