### ISSUE TITLE
SD init fail

### ISSUE THREAD

**Issue by pubalan12** [MarlinFirmware/Marlin#3776]
Hye. i use Ramps 1.4 EEB board and also i use 12864 reprapDiscount Full Graphic Smart Controller.  i enable ready Sdsupport. Sd card detect but no show file. i use 256 mb sd card. Anyone have solution for this Problem????

Thanks You.

**Comment by thinkyhead** [comment]
What version of Marlin are you using?

**Comment by fbarcenas** [comment]
In this display have a problem with the wire connect, you must connect in reverse mode (left-right) right-left and the up-down (down-up)

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
