### ISSUE TITLE
encoder randomly misses steps

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#3791]
8aa591c - turning the encoder one click USUALLY causes the cursor to move one line up or down.
However, randomly it will take 2 clicks of the encoder to move one line.
It almost always occurs on the 1st to 2nd line after going to a new page and sometimes occurs on a line in the middle of a page.
You may also want to note for clarity that "enabling  //#define REVERSE_ENCODER_DIRECTION
also changes the action of  //#define REVERSE_MENU_DIRECTION".

**Comment by Blue-Marlin** [comment]
@ruggb 

> You may also want to note for clarity that "enabling //#define REVERSE_ENCODER_DIRECTION
> also changes the action of //#define REVERSE_MENU_DIRECTION".

Thank you for proving our current description of the setting is correct.

> randomly it will take 2 clicks of the encoder to move one line

We could check the encoder pin more frequently, but then we have less time for the important things like printing. That's not what we want. One day i'll try to rewrite Marlin to use pin_change interrupts for the digital inputs (encoder, buttons, endstops). That may improve things like that.

**Comment by ruggb** [comment]
Yes, it is technically correct, as are most all your verbiage. And as most, it is based on the assumption that a non-technical user can read your mind and interpret it as a programmer might. Just saying, someone with a user perspective might reword some of this stuff for clarity. I am technical, but not a programmer, and I didn't comprehend it till mine didn't work right and I had to figure out why.

at the time I observed the 2 clicks, the machine was idle.

**Comment by Blue-Marlin** [comment]
@ruggb 
Ok. Fou you.
There is no fix in sight. Try to live with the problem.

**Comment by jbrazio** [comment]
@ruggb you may submit an improvement to the comment section.

**Comment by ruggb** [comment]
@jbrazio - it is included in quotes in the original issue statement.
**"enabling //#define REVERSE_ENCODER_DIRECTION
also changes the action of //#define REVERSE_MENU_DIRECTION"**

**Comment by thinkyhead** [comment]
Maybe something like…

``` cpp
// Everything is reversed? Enable REVERSE_ENCODER_DIRECTION.
// Only Menu Navigation is reversed? Enable REVERSE_MENU_DIRECTION.
// Only Value Editing is reversed? Enable BOTH options.
```

**Comment by jbrazio** [comment]
@thinkyhead seems straightforward.

**Comment by ruggb** [comment]
maybe more like this

```
// enabling REVERSE_ENCODER_DIRECTION reverses the rotation of the encoder for scrolling and value setting
// enabling REVERSE_MENU_DIRECTION only reverses rotation for scrolling
// enabling both will reverse value setting and leave scrolling the same as both disabled.
```

**Comment by thinkyhead** [comment]
@ruggb My version requires less thinking. 😉

**Comment by ruggb** [comment]
If you say so. But I would at least define EVERYTHING and REVERSED
EVERYTHING = Menu Navigation & Value Editing
REVERSED = turning the knob produces an action backwards of what you expect.
some ppl might expect a "reversed" operation.

```
// If encoder knob produces an action reversed from what you expect for:
// Menu Navigation & Value Editing > Enable REVERSE_ENCODER_DIRECTION.
// Only Menu Navigation > Enable REVERSE_MENU_DIRECTION.
// Only Value Editing > Enable BOTH options.
```

**Comment by thinkyhead** [comment]
The user will know when something is "reversed" — and some of that depends on their preference. The verbiage I ended up going with should be more than clear enough for the average bear:

``` cpp
/**
 * Encoder Direction Options
 *
 * Test your encoder's behavior first with both options disabled.
 *
 *  Everything is reversed?           Enable REVERSE_ENCODER_DIRECTION.
 *  Only Menu Navigation is reversed? Enable REVERSE_MENU_DIRECTION.
 *  Only Value Editing is reversed?   Enable BOTH options.
 */
```

I presumed that "everything" would be obvious. Your up button moves down. Your encoder wheel changes values the wrong way. The menu navigation is backward. "Everything" is backward. I could move the "Everything" line after the other two, but it seems best to have "Enable BOTH options" last (after mentioning both options).

**Comment by ruggb** [comment]
yea, that is much better with the heading line.

**Comment by thinkyhead** [comment]
Yeah, the heading helps. Also I took your suggestion to drop "Everything" and went with…

``` cpp
/**
 * . . .
 *  Reversed Value Edit and Menu Nav? Enable REVERSE_ENCODER_DIRECTION.
 *  Reversed Menu Navigation only?    Enable REVERSE_MENU_DIRECTION.
 *  Reversed Value Editing only?      Enable BOTH options.
 */
```

**Comment by WZ9V** [comment]
I can confirm the missing clicks on RC6, I have also noticed that sometimes when editing settings such as temperature it skips, so I can for example get 199C and 201C but can't stop at 200C.  I have not been able to nail down a particular set of steps to make it happen.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
