### ISSUE TITLE
Upgrading Between Firmware

### ISSUE THREAD

**Issue by chevellebro1** [MarlinFirmware/Marlin#3799]
Is there an easy way to copy the changes between the Marlin firmware so I can upgrade to the newest without losing all my settings?

**Comment by jbrazio** [comment]
You have to manually copy all the settings from the previous `Configuration.h` to the new one.
Please pay attention that some settings may have changed their names.

**Comment by MrExo3D** [comment]
try a comparison software called Meld. it can help see differences between two files.or a folder of files. make it much easier to transition between builds :)

**Comment by thinkyhead** [comment]
Using a "diff" tool like Meld, BBEdit, or Kaleidoscope is good. But remember, you will need to compare your configs to the original unmodified `Configuration.h` and `Configuration_adv.h` files from the version of Marlin that you started with.

**Comment by Roxy-3D** [comment]
> Please pay attention that some settings may have changed their names.

We have a whole bunch of names that need to change.   It wouldn't hurt to make those changes prior to going 'Golden'.

**Comment by thinkyhead** [comment]
@Roxy-3DPrintBoard Do you have a list of the names needing a change? We should have a look and vote on the most important ones. I'd like to minimize the number of names we change at this point, but I'm open to discussion about that.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
