### ISSUE TITLE
M104 & M109 width PRINTJOB_TIMER_AUTOSTART and printcounter

### ISSUE THREAD

**Issue by MagoKimbra** [MarlinFirmware/Marlin#3809]
In M104 and M109 width printcounter and enabled PRINTJOB_TIMER_AUTOSTART, call routine PrintCounter::start(). This routine increment the value totalPrints whenever...

I suggest you put a check if it is already running..

``` cpp
void PrintCounter::start() {
  #if ENABLED(DEBUG_PRINTCOUNTER)
    PrintCounter::debug(PSTR("start"));
  #endif

  if (this->isRunning()) return;

  if (!this->isPaused()) this->data.totalPrints++;
  super::start();
}
```

**Comment by jbrazio** [comment]
Good catch I found it for M77 but forgot to check the M104, M109.

**Comment by jbrazio** [comment]
Fixed, @MagoKimbra please check if it's OK for you.

**Comment by MagoKimbra** [comment]
it seems ok..
Only problem is const static uint16_t j = this->saveInterval \* 1000;
The variable J must is uint32_t, the max value for uint16_t is 65535.

**Comment by jbrazio** [comment]
Thanks @MagoKimbra and @esenapaj, submitted PR #3819.
