### ISSUE TITLE
RC6 - "start print" does not zero print time after "stop print" command

### ISSUE THREAD

**Issue by Roo123** [MarlinFirmware/Marlin#3826]
RC6 firmware

Supposing you stop a print with "stop print" from LCD.

The current print time remains on the display. (Good.)

Then you start another print.

The time for this second print starts from the end time of the previous print. Without first zeroing.

Not good. ;-)

**Comment by jbrazio** [comment]
We need more information.

How do you start printing is it from the LCD or from the host ?
Do you have `PRINTJOB_TIMER_AUTOSTART` set ?

**Comment by Roo123** [comment]
Started from SD card / LCD.

In which file is the printjob_timer_autostart variable located?

**Comment by jbrazio** [comment]
A few minutes ago a new PR fixing some issues with the print job timer was merged into RCBugfix, would you care to download the latest version and to a quick test to see if the behavior is still there ?

`PRINTJOB_TIMER_AUTOSTART` is in `Configuration.h`.

**Comment by Roo123** [comment]
PRINTJOB_TIMER_AUTOSTART isn't showing up when I search in configuration.h of RC6 ?

Afraid I can't jump into the Bugfix just at the moment....

**Comment by Blue-Marlin** [comment]
In that case you don't have a current RCBugFix. (https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Configuration.h#L772)

**Comment by jbrazio** [comment]
I've had a quick look and this is indeed a bug, we stop the SD print using a custom function and this function is not taking into account the print job timer.

``` cpp
  static void lcd_sdcard_stop() {
    stepper.quick_stop();
    card.sdprinting = false;
    card.closefile();
    thermalManager.autotempShutdown();
    cancel_heatup = true;
    lcd_setstatus(MSG_PRINT_ABORTED, true);
  }
```
