### ISSUE TITLE
How to remove use of thermistors

### ISSUE THREAD

**Issue by orrnoah** [MarlinFirmware/Marlin#3832]
Hi guys,

I am currently working on a build that will not require any thermistors what so ever (multi material ceramic printer).
I am relatively new to Marlin and am struggling to find away to modify the 'TEMP_SENSOR_0' and 'TEMP_SENSOR_1 value to 0 (not in use) without sequential temperature scope error messages.

Is there any simple way to remove use of thermistors from the entire sketch?

**Comment by brainscan** [comment]
There are dummy thermistors that always give a set value so you can trick it into thinking it's already hot. Might be easiest way.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
