### ISSUE TITLE
Max Z acceleration not respected

### ISSUE THREAD

**Issue by Robertozzz** [MarlinFirmware/Marlin#3847]
Default accelertion at 3000, Max Z accel set to low value. It seems the max for Z is not respected and Z anyway accelerates at 3000 for at least non printing moves, which resulted in stepper skipping steps. 
(Because of dual Z axis/stepper, X axis tilted)

**Comment by brainscan** [comment]
What are your steps per mm for z and feedrate? Sometimes it's not the acceleration but the amount of steps being sent. Mine works perfectly at 4mm/s and then grinds and skips at 5mm/s.

**Comment by Robertozzz** [comment]
Z axis Steps per mm 395. Tried at different feedrates, same result. The X axis after some time gets slightly offset, for example after a print.  When I force the default acceleration to low level (900), no problems at all, even at feedrates of 100 mm/s !! on the Z, no problem at all, X axis stays perfectly level. My Z axis are 2 threaded rods. (Prusa I3 clone)..

Any Ideas?

**Comment by Robertozzz** [comment]
Oops, by mistake closed.. Reopened..

Tried in Repetier host..
Set Max Z accel to 950, default and travel acceleration also 950.
Did some G1 Z.... travel moves.
Set Max Z accel to 150, default and travel acceleration still 950.
Did some travel moves, max Z acceleration respected and accelerates at 150,
After a few travel moves, suddenly Z moves again at acceleration rate of 950, even though EEPROM still set at 150.
When giving a travel move in Repetier host by buttons, Max Z Acceleration seems respected., Giving a simple G1 Z.... code, and Z accelerates at 950 again without changing any parameters.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
