### ISSUE TITLE
Can one manually enter bed levelling matrix for delta?

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3850]
_From @zlikovski on April 9, 2016 22:27_

I didn't succeed to find the answer on the net, so before I do something stupid and crash my printer, I'd like to consult with wiser wo/men,
I have a delta printer (home made), based on the kossel design. I can level it nicely with repetier firmware. Now, my question is wether is it possible to take the levelling matrix from that levelling procedure and insert it in my marlin firmware?
There is a matrix in the planer.cpp. Maybe in some other place?

_Copied from original issue: MarlinFirmware/MarlinDev#399_

**Comment by boelle** [comment]
_From @Roxy-3DPrintBoard on April 10, 2016 17:27_

You can not do that currently.   But it is being worked on.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
