### ISSUE TITLE
Can't upload using latest Arduino 1.6.7 IDE

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3852]
_From @Nprod on March 7, 2016 12:0_

OK, so i'm trying to use the 1.6.7 Boards Manager package by @Wackerbarth with a Melzi board (Sanguino 1284p@16mhz) and it's throwing an error:

> # error This file is obsolete and needs to be revised

I tried commenting out that line in pins_arduino.h and it moves forward only to give me timeout errors like this:

> avrdude: stk500v2_ReceiveMessage(): timeout

I've tested this with two identical Melzi boards and two different PC's but the errors follow the same pattern. I can upload fine to other AVR boards like an Arduino Nano through the standard board configs provided by the IDE so my guess is this is a problem with the Marlin-Sanguino configuration package.

_Copied from original issue: MarlinFirmware/MarlinDev#378_

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
