### ISSUE TITLE
RRD Smart LCD 2004 "no SD-Card" error

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3855]
_From @o-lampe on September 4, 2015 13:54_

When I power On my Ramps with above mentioned LCD and the SD-Card is already inserted, I see " no SD-Card" message in main display. I have to remove and plug it back in to have access to SD-files. 
Not a biggy, but with autostart option enabled, it wouldn´t work.

_Copied from original issue: MarlinFirmware/MarlinDev#135_

**Comment by boelle** [comment]
_From @Wackerbarth on September 4, 2015 13:58_

There was an issue about this which was raised earlier and I thought that it had been fixed. Are you using the latest, or at least a very recent, version of the dev firmware?

**Comment by boelle** [comment]
_From @o-lampe on September 4, 2015 14:10_

@Wackerbarth  I´ve downloaded the last version two days ago, maybe I haven´t set all the right options?
Usually I disable #define SDsupport
and enable RRD_Smart Controller only. Worked fine in the past.

**Comment by boelle** [comment]
_From @thinkyhead on September 5, 2015 1:3_

Going forward you will have to enable `SDSUPPORT` explicitly in `Configuration.h`. That shouldn't have any effect on how it behaves, however. If you have `SD_DETECT_PIN` defined (and the correct `SD_DETECT_INVERTED` setting) then Marlin should automatically detect the presence of an already-inserted SD card. If it's not, maybe there's some way to twiddle the detection pin to cause it to refresh its state. Just spitballing…

**Comment by boelle** [comment]
_From @alexandrezia on September 6, 2015 15:17_

I have the same issue here, On boot it doesn't detect an already inserted SD card
on latest commit  b23d7659 
using board:  #define REPRAP_DISCOUNT_SMART_CONTROLLER
Played with all combinations of SDSUPPORT and SD_DETECT_INVERTED.

**Comment by boelle** [comment]
_From @o-lampe on September 6, 2015 18:53_

@thinkyhead  enabling SDSUPPORT didn´t help. Don´t know where the other variables you mentioned are located. In the past, I never had to change anything outside the configuration.h to make a printer work.

**Comment by boelle** [comment]
_From @thinkyhead on September 6, 2015 23:33_

@alexandrezia Try this as a test. Replace the line in the function `lcd_init` in `ultralcd.cpp` which reads `lcd_oldcardstatus = IS_SD_INSERTED;` with `lcd_oldcardstatus = false;` and see if it causes the `lcd_update` routine to do the right thing. (Namely, to see a change in status.)

**Comment by boelle** [comment]
_From @o-lampe on September 7, 2015 8:5_

``` cpp
  #if ENABLED(SDSUPPORT) && PIN_EXISTS(SD_DETECT)
    pinMode(SD_DETECT_PIN, INPUT);
    WRITE(SD_DETECT_PIN, HIGH);
    lcd_oldcardstatus = false;
  #endif
```

I´m not an expert, but is it common to define a pin as _input_ and then "write" to it, as if it was an _output_?

Sry, I still don´t get it how to insert code properly...
-Olaf

**Comment by boelle** [comment]
_From @o-lampe on September 7, 2015 8:40_

@thinkyhead changing it to `lcd_oldcardstatus = false` helps to recognize the SD-card at startup, but now the status line is overwritten by "Card inserted" immediately, so I can´t see the "{user defined text} ready " anymore. I used the line, to see which FW-version I´m currently using

**Comment by boelle** [comment]
_From @fmalpartida on September 7, 2015 10:2_

Yes that is usual in the AVR processor family to set the internal pull-ups. 

Enviado desde mi iPhone

**Comment by boelle** [comment]
_From @o-lampe on September 8, 2015 9:23_

@fmalpartida I believe the way to define a pullup is to use `pinMode(SD_DETECT_PIN, **input_pullup**)

**Comment by boelle** [comment]
_From @alexandrezia on September 9, 2015 2:50_

Well, I did test the 

```
lcd_oldcardstatus = false;
```

And now it recognizes the sdcard on boot and it's working fine.
The only thing I've noted is that as mentioned by @o-lampe it overwrites the last line since boot and I can't check the "user defined text" that usually sits on that last line.
I think this should be adressed before code freezes to avoid merging this into Release branch

thanks

**Comment by boelle** [comment]
_From @thinkyhead on September 13, 2015 5:27_

Do we know if the code should definitely be `pinMode(SD_DETECT_PIN, INPUT_PULLUP)` instead of `pinMode(SD_DETECT_PIN, INPUT)`? Does that have any effect on the behavior (or do we still need `lcd_oldcardstatus = false`)?

**Comment by boelle** [comment]
_From @Wackerbarth on September 13, 2015 12:23_

The distinction between INPUT and INPUT_PULLUP is a hardware issue. Does the hardware provide the pull_up, or do we need to supply that from the MPU?

**Comment by boelle** [comment]
_From @fmalpartida on September 13, 2015 12:58_

On AVR based processors and a range of PICs all IO lines have a pull-up.

**Comment by boelle** [comment]
_From @Wackerbarth on September 13, 2015 13:11_

@fmalpartida -- They have them available. However, activation is a separate issue.

**Comment by boelle** [comment]
_From @fmalpartida on September 13, 2015 13:19_

It very much depends on what you connect to the pin indeed. If you have an open collector/drain configuration or if it doesn’t.

**Comment by boelle** [comment]
_From @thinkyhead on September 14, 2015 3:18_

> it overwrites the last line since boot

#180 should take care of that. Testing of SD status is deferred until the first LCD update.

**Comment by boelle** [comment]
_From @o-lampe on September 14, 2015 8:18_

My concern about the code was more related to the second line
`pinMode(SD_DETECT_PIN, INPUT);
  WRITE(SD_DETECT_PIN, HIGH);`
Is it possible to send a write command to an input?

**Comment by boelle** [comment]
_From @Wurstnase on September 14, 2015 8:30_

> Is it possible to send a write command to an input?

Called pullup.

**Comment by boelle** [comment]
_From @Wackerbarth on September 14, 2015 11:22_

Yes, you can do so. However, it should not be allowed in that form.  That is the whole purpose of INPUT_PULLUP.

This points out an error in the previous code that assumes certain hardware characteristics rather than specifying them back in the hardware definition.  We really need to introduce a HAL layer and move things like this to that layer.

**Comment by boelle** [comment]
_From @fmalpartida on September 14, 2015 11:38_

Fully agree. 

Enviado desde mi iPhone

**Comment by boelle** [comment]
_From @Wurstnase on September 14, 2015 12:49_

Yes, that fully true. On most (if not all) AVR this works. But ARM has different registers for that.

**Comment by boelle** [comment]
_From @Wackerbarth on September 14, 2015 12:55_

@Wurstnase -- All the more reason to move this to a HAL.

**Comment by boelle** [comment]
_From @thinkyhead on April 18, 2016 3:10_

I assume we fixed this bug in `RCBugFix`…? If so, we can close this issue. Code from `RCBugFix` will be getting migrated to `MarlinDev` (and reorganized) right after 1.1.0 release.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
