### ISSUE TITLE
Commands to enable/disable Filament Sensor

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3857]
_From @eboston on September 14, 2015 23:39_

I have been looking at adding a filament sensor to my Printrbot Simple Metal.  I think I have everything worked out and will be back porting the current FILAMENT_RUNOUT_SENSOR logic to the older branch Printrbot uses.  However, I noticed that the check of the filament sensor only occurs if printing from the SD card.  What I was thinking of doing was to add two new code, M601 and M602, to enable/disable the filament sensor.  So if not printing from the SD card, you can put M601 in your startup code to enable the sensor and then a M602 in the end code.  These two commands could also be instead be name start/end printing so any other code you only want to run when printing could know  if a print job is running or not.

This would be a change to be added after the next version is released.  It might be a bit before I would be ready to add it into, if there is interest in it.  If not, I'll just use it in my own version for now.

_Copied from original issue: MarlinFirmware/MarlinDev#185_

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
