### ISSUE TITLE
Another cool project!

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3859]
_From @clefranc on September 22, 2015 7:58_

https://www.kickstarter.com/projects/dobot/dobot-robotic-arm-for-everyone-arduino-and-open-so

![untitled](https://cloud.githubusercontent.com/assets/4294448/10013239/9a75b1aa-60dd-11e5-91ce-7fdf073ffbb4.png)

_Copied from original issue: MarlinFirmware/MarlinDev#208_

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
