### ISSUE TITLE
Analog temp input pins with pull up/down resistor ?

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3863]
_From @maukcc on December 22, 2015 12:25_

Is the input pin for temp0 without internal pull up or down resistor, and the others with?
As I get different readings for the inputs when nothing is connected.
I use a thermocouple with a user defined thermistor table.
If I put a 1Mohm resistor on the input pins and connect it to GND the temp0 reads zero degrees(correct), the other temps read 300(ish) 

_Copied from original issue: MarlinFirmware/MarlinDev#313_

**Comment by boelle** [comment]
_From @maukcc on December 22, 2015 13:1_

It is only for TEMP_1 that is gives strange readings
And it is not the physical pin, because when I switch the TEMP_0 and TEMP_1 pin, the fault switches as well.
so,
normal:

``` cpp
 #define TEMP_0_PIN             0 
 #define TEMP_1_PIN             9
```

switched:

``` cpp
 #define TEMP_0_PIN             9 
 #define TEMP_1_PIN             0
```

So it does not matter which physical pin I assign to TEMP_1, it always gives strange values.

**Comment by boelle** [comment]
_From @Wackerbarth on December 22, 2015 13:28_

What version of the source are you using? And how do you have things configured?
(The preferred method for presenting the requested information is to fork MarlinDev on Github and push your changes to a personal branch. Then you can just provide the reference to that repository and we can then duplicate your effort to look for the cause.)

**Comment by boelle** [comment]
_From @maukcc on December 22, 2015 13:36_

Also, if I have the temps connected with 2 extruders:
T0=18
T1=33
with 3 extruders
T0=18
T1=23
T2=18
Voltage on the input pins is identical all over, but T1 drops 10 degrees when T2 is added.

**Comment by boelle** [comment]
_From @maukcc on December 22, 2015 13:39_

@ Wackerbarth : that is a good idea, I will do that, as I made a lot of changes.
none of them should interfere with this I think.

**Comment by boelle** [comment]
_From @thinkyhead on April 22, 2016 1:29_

If this is resolved, it can be closed.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
