### ISSUE TITLE
Is EXT_SOLENOID obsolete?

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3869]
<a href="https://github.com/thinkyhead"><img src="https://avatars.githubusercontent.com/u/698003?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thinkyhead](https://github.com/thinkyhead)**
_Friday Mar 11, 2016 at 04:05 GMT_
_Originally opened as https://github.com/MarlinFirmware/MarlinDev/issues/381_

---

I see that the `M380` and `M381` commands that depend on `EXT_SOLENOID` and the `SOLn_PIN` pins are not being activated by any of Marlin's current configurations. None of the pins files define these pins. Is there any configuration that demonstrates or uses this feature? Is this feature still required for extruder-mounted solenoids?

**Comment by boelle** [comment]
<a href="https://github.com/Blue-Marlin"><img src="https://avatars.githubusercontent.com/u/17075493?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Blue-Marlin](https://github.com/Blue-Marlin)**
_Friday Mar 11, 2016 at 11:54 GMT_

---

Interesting features we have. Could be used for a dribble stop, extruder on LED, multi material paste extruders, ...
Seems to need some more documentation - not necessarily an example in one of the configs..

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
