### ISSUE TITLE
Filament Width - Dual Extruder

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3871]
<a href="https://github.com/nio40k"><img src="https://avatars.githubusercontent.com/u/1703434?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nio40k](https://github.com/nio40k)**
_Wednesday Feb 24, 2016 at 09:50 GMT_
_Originally opened as https://github.com/MarlinFirmware/MarlinDev/issues/372_

---

Please add support for the Filament Width Sensor in combination with Dual Extruder.

Currently the filament width sensor can only used with one extruder. I would like to use two sensors with two extruders.

**Comment by boelle** [comment]
<a href="https://github.com/thinkyhead"><img src="https://avatars.githubusercontent.com/u/698003?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thinkyhead](https://github.com/thinkyhead)**
_Tuesday May 03, 2016 at 03:20 GMT_

---

What pins do you connect your sensors to?

**Comment by ghost** [comment]
I use a Ramps 1.4 and will use what ever pin you recommend ...

**Comment by thinkyhead** [comment]
Basically, we need to specify a second pin for each board that currently has a `FILWIDTH_PIN`. It can be called…

``` cpp
#define FILWIDTH_E1_PIN      ?  // ANALOG NUMBERING
```

Currently `FILWIDTH_PIN` is ANALOG pin 3 on those boards that specify it. We only need to pick a next pin to use, define `FILWIDTH_E1_PIN`, and then add code alongside the current `FILWIDTH_PIN`-dependent code, which handles the second pin. And we need to add a new configuration option, such as `FILAMENT_WIDTH_SENSOR_E1`, to enable the second sensor.

There's a lot of code related to `FILAMENT_WIDTH_SENSOR` so it's a few hours of work, at least…

**Comment by boelle** [comment]
maybe add this one to the 1.1.1 milestone ? if its still relavant?
