### ISSUE TITLE
Support for platformiO in latest versions

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3872]
<a href="https://github.com/thawkins"><img src="https://avatars.githubusercontent.com/u/14537?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thawkins](https://github.com/thawkins)**
_Friday Feb 19, 2016 at 23:50 GMT_
_Originally opened as https://github.com/MarlinFirmware/MarlinDev/issues/365_

---

PlatformiO have a released their IDE http://platformio.org/#!/platformio-ide which makes the platformiO system a far more capable and useable system than the existing arduino setup. Whilst maintaining the arduino framework compatability up to version 1.6.7. 

Can we revisit the lack of platformio support in the new repository layouts.

**Comment by boelle** [comment]
<a href="https://github.com/Roxy-3DPrintBoard"><img src="https://avatars.githubusercontent.com/u/8404322?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Roxy-3DPrintBoard](https://github.com/Roxy-3DPrintBoard)**
_Saturday Feb 20, 2016 at 15:49 GMT_

---

Will this load and compile the current Release Candidate?     And the follow up question, can it load and compile the code in MarlinDev that has started to be split apart?

**Comment by boelle** [comment]
<a href="https://github.com/thawkins"><img src="https://avatars.githubusercontent.com/u/14537?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thawkins](https://github.com/thawkins)**
_Saturday Feb 20, 2016 at 16:25 GMT_

---

I'm having a go at getting that in place right now.

**Comment by boelle** [comment]
<a href="https://github.com/Roxy-3DPrintBoard"><img src="https://avatars.githubusercontent.com/u/8404322?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Roxy-3DPrintBoard](https://github.com/Roxy-3DPrintBoard)**
_Saturday Feb 20, 2016 at 17:07 GMT_

---

One thing interesting in the documentation pages was you get to set compile time flags for everything.   I want to be able to declare --ii flag to display the generated code for each line of C code.   That would have been helpful and interesting when looking at the Rx and Tx buffer indexes.

**Comment by boelle** [comment]
<a href="https://github.com/thawkins"><img src="https://avatars.githubusercontent.com/u/14537?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thawkins](https://github.com/thawkins)**
_Saturday Feb 20, 2016 at 17:13 GMT_

---

It's a more traditional system, but also a one stop install for IDE,
compilers, libs, frameworks etc. So in that respect it's like the arduino
setup. The upside is it supports a huge range of boards and processor
types,  and will automatically download the compilers etc, plus it does
real libraries, rather than the pseudo libs that arduino does. Which are
little more than source code archives.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
