### ISSUE TITLE
SD Fat library should be updated

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3874]
<a href="https://github.com/Wackerbarth"><img src="https://avatars.githubusercontent.com/u/505323?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Wackerbarth](https://github.com/Wackerbarth)**
_Saturday Feb 06, 2016 at 12:10 GMT_
_Originally opened as https://github.com/MarlinFirmware/MarlinDev/issues/344_

---

The SD Fat library that we include is not the current release from that library's author.
This causes compilation errors with some of the more recent compiler releases.

https://github.com/greiman/SdFat.git

**Comment by boelle** [comment]
<a href="https://github.com/thinkyhead"><img src="https://avatars.githubusercontent.com/u/698003?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thinkyhead](https://github.com/thinkyhead)**
_Wednesday Feb 10, 2016 at 06:41 GMT_

---

SdFat has diverged a lot. In fact, for the features we use, such as long filenames, we would have to use https://github.com/greiman/SdFat-beta. I have already tried to do the upgrade once, but found it a bit daunting and went back to trusting our little slice of SdFat.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
