### ISSUE TITLE
Homing before and after G29

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3877]
<a href="https://github.com/DeathmannX"><img src="https://avatars.githubusercontent.com/u/7075201?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DeathmannX](https://github.com/DeathmannX)**
_Tuesday Jan 05, 2016 at 20:25 GMT_
_Originally opened as https://github.com/MarlinFirmware/MarlinDev/issues/328_

---

//English

Hi Guys,

first things first.
A big THX for devolping this awsome Firmware!

I've got a Problem with the G29 Command.
If i run it the Heatbed will be homed in 3 Points (grid) ok.
But after this homing i cann't move back to the Endstops.
I can only move back to them with homing the X and Y Axis.

But if i do this i think the G29 points will be discarded.

//German

Hallo Leute,

zuerst einmal DANKE für die unglaubliche Firmware die Ihr geschaffen habt.

Leider jedoch habe ich genau mit dieser ein Problem.
Ich kann nach dem ich G29 ausgeführt habe nicht mehr zurück zum Endstop fahren
und muss erst die X und Y Achse wieder homen bevor das geht.

Ich befürchte jedoch das dann auch die G29 Punkte verworfen werden.

**Comment by boelle** [comment]
<a href="https://github.com/Roxy-3DPrintBoard"><img src="https://avatars.githubusercontent.com/u/8404322?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Roxy-3DPrintBoard](https://github.com/Roxy-3DPrintBoard)**
_Wednesday Jan 06, 2016 at 00:07 GMT_

---

Please post a copy of your Configuration.h file.    We can see how you have things setup with that.

**Comment by boelle** [comment]
<a href="https://github.com/DeathmannX"><img src="https://avatars.githubusercontent.com/u/7075201?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DeathmannX](https://github.com/DeathmannX)**
_Wednesday Jan 06, 2016 at 18:52 GMT_

---

And a other mystery for me is if i set the Z Probe offset to `-0.12` and home the Z Axis and type in `M114` it shows me `Z:0.12` if i go manual to `Z0` it is ok.

configuration.h http://pastebin.com/JLCu7zgg

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
