### ISSUE TITLE
How to I keep the menu open for move axis?

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3879]
<a href="https://github.com/a4jp-com"><img src="https://avatars.githubusercontent.com/u/9621044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [a4jp-com](https://github.com/a4jp-com)**
_Saturday Jan 02, 2016 at 08:17 GMT_
_Originally opened as https://github.com/MarlinFirmware/MarlinDev/issues/325_

---

How to I keep the menu open for move axis? The menu always times out and goes to the top default screen but I would like to disable the time out just on this menu item.

**Comment by boelle** [comment]
<a href="https://github.com/a4jp-com"><img src="https://avatars.githubusercontent.com/u/9621044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [a4jp-com](https://github.com/a4jp-com)**
_Saturday Jan 02, 2016 at 16:46 GMT_

---

Even just an increase of the timeout would be nice if this is difficult. Where is the value that sets the length of the timeout?

**Comment by boelle** [comment]
<a href="https://github.com/KiteLab"><img src="https://avatars.githubusercontent.com/u/10833311?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KiteLab](https://github.com/KiteLab)**
_Saturday Jan 02, 2016 at 18:03 GMT_

---

https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/ultralcd.h#L36

**Comment by boelle** [comment]
<a href="https://github.com/a4jp-com"><img src="https://avatars.githubusercontent.com/u/9621044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [a4jp-com](https://github.com/a4jp-com)**
_Saturday Jan 02, 2016 at 18:14 GMT_

---

Thank you @KiteLab, 15000 milliseconds seems like a lot of time but I'll double it for now. I always seem to run out of time when trying to calibrate.

If I want to set the LCD_TIMEOUT_TO_STATUS for one menu item. Is that tricky or would I just need to add an if statement to one of the menu items in ultralcd.cpp?

I can see the code starts around line 900.

```

/**
 *
 * "Prepare" > "Move Xmm" > "Move XYZ" submenu
 *
 */

static void lcd_move_menu_axis() {
  START_MENU();
  MENU_ITEM(back, MSG_MOVE_AXIS, lcd_move_menu);
  MENU_ITEM(submenu, MSG_MOVE_X, lcd_move_x);
  MENU_ITEM(submenu, MSG_MOVE_Y, lcd_move_y);
  if (move_menu_scale < 11.0) {
    MENU_ITEM(submenu, MSG_MOVE_Z, lcd_move_z);
    #if EXTRUDERS == 1
      MENU_ITEM(submenu, MSG_MOVE_E, lcd_move_e);
    #else
      MENU_ITEM(submenu, MSG_MOVE_E MSG_MOVE_E1, lcd_move_e0);
      MENU_ITEM(submenu, MSG_MOVE_E MSG_MOVE_E2, lcd_move_e1);
    #endif
    #if EXTRUDERS > 2
      MENU_ITEM(submenu, MSG_MOVE_E MSG_MOVE_E3, lcd_move_e2);
    #endif
    #if EXTRUDERS > 3
      MENU_ITEM(submenu, MSG_MOVE_E MSG_MOVE_E4, lcd_move_e3);
    #endif
  }
  END_MENU();
}

```

**Comment by boelle** [comment]
<a href="https://github.com/KiteLab"><img src="https://avatars.githubusercontent.com/u/10833311?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KiteLab](https://github.com/KiteLab)**
_Saturday Jan 02, 2016 at 18:25 GMT_

---

You could make an other exception about here:
https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/ultralcd.cpp#L1710

**Comment by boelle** [comment]
<a href="https://github.com/thinkyhead"><img src="https://avatars.githubusercontent.com/u/698003?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thinkyhead](https://github.com/thinkyhead)**
_Monday Apr 18, 2016 at 04:52 GMT_

---

The latest code (in `RCBugFix`) now has a flag `defer_return_to_status` that can be set by any menu or menu item that wants to prevent the timeout. It should be cleared when the menu is done. Currently it's only used for the Manual Bed Leveling items, because they are multi-step. But this flag could be applied to any edit item, if that makes it work better.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
