### ISSUE TITLE
Printrbot planning new fork

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3882]
<a href="https://github.com/thawkins"><img src="https://avatars.githubusercontent.com/u/14537?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thawkins](https://github.com/thawkins)**
_Sunday Dec 27, 2015 at 02:45 GMT_
_Originally opened as https://github.com/MarlinFirmware/MarlinDev/issues/316_

---

The printrbot team is planning a fork of Marlin,  Brooke Drumm has announced this on thier google++ feed. 

The Marlindev community should probaly talk to them to determine what thier beef is. And why they feel that they need to fork the firmware. 

https://plus.google.com/u/0/+BrookDrummpb/posts/gWupi2KvLiC?cfem=1

**Comment by Jnesselr** [comment]
I'm going to go ahead and close this issue. Brook is notorious for wanting his own little printrbot ecosystem, and it's not something I think the maintainers of marlin should worry about.

**Comment by thinkyhead** [comment]
I would recommend to them that after 1.1.0 is released, they should think about basing their next forked version off of that.
