### ISSUE TITLE
Hannover (Germany) Maker Faire this weekend

### ISSUE THREAD

**Issue by CONSULitAS** [MarlinFirmware/Marlin#3890]
Hi folks,

are there any Marlin enthusiast on the Hannover Maker Faire this weekend?

There is somebody talking, we know rather well: http://maker-faire.de/hannover/vortrag/mit-der-machete-in-den-lizenzdschungel/

I am there (Saturday and Sunday 28.05./29.05.), too.

Perhaps we can meet and drink a coffee together...

Greetings

Jochen

**Comment by AnHardt** [comment]
I'll likely be there on Sunday.

Andreas (Dr. Marlin)

**Comment by clexpert** [comment]
@CONSULitAS @AnHardt Hi guys, we (with my son @petrzjunior) are going to be on Hannover Faire this sunday too. How will we meet up?

**Comment by AnHardt** [comment]
13:00 near the fish. Dr. Marlin (grey bearded, white coated, heavy weight)

**Comment by clexpert** [comment]
OK. I do not know if we will find any fish. :-) But we will have blue t-shirts with logo our blog Zahradnik se bavi (see http://www.zahradniksebavi.cz/).

**Comment by Roxy-3D** [comment]
Please take and post some pictures!!!!

**Comment by CONSULitAS** [comment]
@clexpert 
You talk about the flower? OK.
We (me with my son) have been there today. But we have too look for the fish, too. 😄 
And if you see a guy with this nameplate and the face on my profile...
![img_6297](https://cloud.githubusercontent.com/assets/6808242/15629407/9a8dfbfc-2518-11e6-85af-c18958cadb69.jpg)

@Roxy-3DPrintBoard 
Of the Makerfaire, the projects or the makers, or all of them? 😄 
At your service!

**Comment by clexpert** [comment]
@CONSULitAS Yes, flower too :smile: And title "Zahradnik se bavi" too :smile: It means Zahradnik (my name) has fun. We will find laughing guy with moustache and nameplate with marlin fish around fish :smile:

**Comment by CONSULitAS** [comment]
@clexpert Sometimes i am stupid:
http://maker-faire.de/hannover/maker/m2016/der-fisch/
😁 
You will find it outside.

**Comment by CONSULitAS** [comment]
@clexpert 
Ah: You are our czech care taker! 👍

**Comment by clexpert** [comment]
@CONSULitAS Yes :rocket:

**Comment by AnHardt** [comment]
![img_2596](https://cloud.githubusercontent.com/assets/211931/15638919/d6d6ab46-2625-11e6-82b7-487246bc33f9.JPG)

**Comment by jbrazio** [comment]
Andreas wasn't kidding.. Dr. indeed !
Nice foto, congrats everyone, I hope it was a good day.

**Comment by thinkyhead** [comment]
Some of those faces look quite familiar!

**Comment by clexpert** [comment]
Hi everybody! Thank you very much for the meeting at the Maker Faire Hannover 2016. My 16-years son was excited from both Marlin developers @CONSULitAS and @AnHardt (white coated Dr. Marlin). I am finishing video editing from the fair. Andreas, thank you for the photo, I use it in the video too. I can post video link if you want (@Roxy-3DPrintBoard ?).

**Comment by clexpert** [comment]
The video from Maker Faire Hannover 2016 is here: https://youtu.be/Xqx3cuDeUn0
It is vlog in Czech language. But do not worry! The greater part of the video is video footage without speaking. You can see a lot of interesting things from the faire.

**Comment by Roxy-3D** [comment]
I don't understand the device at 2:43 on the video.   It appears to be a Tesla coil.  But it has a big ball (with no sharp edges on it) at the top like a Van de Graaff generator.   Can the two be mixed together?  The Van de Graaff generator is static electricity and that is why it needs the big sphere at the top to accumulate the charge.  But the lower part of the unit appears to be a high frequency step up transformer.

Either way...   I'm surprised this was allowed into the fair.   I certainly would not want either of those kind of devices any where near my electronics! 

That was a super cool fair!

**Comment by jbrazio** [comment]
btw, @clexpert who was taking the photo, was it @Blue-Marlin ? :-P

**Comment by AnHardt** [comment]
No. It was my son.

**Comment by clexpert** [comment]
@jbrazio The photo was taking Dr. Marlin's son or wife :smile:
