### ISSUE TITLE
Z_SAFE_HOMING not homing in correct position.

### ISSUE THREAD

**Issue by snowzach** [MarlinFirmware/Marlin#3901]
I've enabled Z_SAFE_HOMING with:

``` cpp
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0
#define X_MAX_POS 260
#define Y_MAX_POS 260
#define Z_MAX_POS 260
```

For whatever reason, it's choosing to home at X=120 Y=93

**Comment by Blue-Marlin** [comment]
What are your probe offsets? 10/37?

**Comment by snowzach** [comment]
Yep.. exactly.. 10/37.... and I see my problem.. I transposed the X/Y offset... Thanks!
