### ISSUE TITLE
Dual X Carriage duplication mode

### ISSUE THREAD

**Issue by pbrgle1** [MarlinFirmware/Marlin#3905]
Hi. This is either a Support question or a Feature request concerning the Dual X Carriage feature in Duplication mode (M605 S2).

I was just wondering if there is (or could be) a possibility to stop one of the extruders in duplication mode if one of the two prints should fail. It is silly that you would have to cancel the whole print if only one print failed.

The main goal would be only to disable one of the extruder motors (via command?) and a more advanced option (if possible) would also be to park the failed extruder and disable the heater while continuing the ''healthy'' print.

I'm just laying my idea out there. I'm sadly not capable of doing any modifications to the code.

**Comment by nivekhan** [comment]
For now, a work-around could be to manually send an `M104 T1` to turn off the heater and the tool will keep moving around but should stop extruding (provided you have mintemp protection).

**Comment by barus93** [comment]
If you must stop the T1 you can send m605 s1/s0

**Comment by maukcc** [comment]
Is there already a request to extend on this feature. Like
I want extrudermotor 1 and 3 doing the same and 2 and 4 doing the same
or I want 1,2,3 and 4 doing the same

**Comment by thinkyhead** [comment]
@maukcc To do things more generally, as you suggest, will require a systematic rewrite of various areas of the stepper, planner, and main code. We do have it in mind to do more "abstraction" on extruders, axes, steppers, etc., but we have to be careful not to over-generalize, because it tends to produce slower code.
