### ISSUE TITLE
REPRAPWORLD_KEYPAD: Mashing keys is bad

### ISSUE THREAD

**Issue by maukcc** [MarlinFirmware/Marlin#3915]
If you are moving the X or Y axis with the keypad and click the homing button as well on the keypad It will start moving in Y+ axis and not stop.
Z-axis is not affected

**Comment by maukcc** [comment]
I also did:

```
    //#if ENABLED(DELTA) || ENABLED(SCARA)
      #define _KEYPAD_MOVE_ALLOWED (axis_homed[X_AXIS] && axis_homed[Y_AXIS] && axis_homed[Z_AXIS])
    //#else
    //  #define _KEYPAD_MOVE_ALLOWED true
    //#endif
```

as that is also good practice in cartesian machines
This should also be done for moving axis with the jog dial

**Comment by maukcc** [comment]
Also: the home button works while printing

**Comment by jbrazio** [comment]
Are you using the latest `RCBugfix` ?

**Comment by maukcc** [comment]
1.1.0-RC6

**Comment by thinkyhead** [comment]
Please test `RCBugFix` so we can see if this is still an issue. Someone might have fixed it by now.

**Comment by maukcc** [comment]
If I have a lot of time I will switch to the RCBugFix. for now I looked at the code in `ultralcd.cpp` and it seems the same in RCBugFix. A raw Gcode command sent in between lines.
I also suspect this will be the case(or worse) when printing through a host.

**Comment by maukcc** [comment]
I did : 

```
  #if ENABLED(REPRAPWORLD_KEYPAD)

    #define _KEYPAD_MOVE_ALLOWED (axis_homed[X_AXIS] && axis_homed[Y_AXIS] && axis_homed[Z_AXIS])

    //if (REPRAPWORLD_KEYPAD_MOVE_HOME)       reprapworld_keypad_move_home();
    //if (REPRAPWORLD_KEYPAD_MOVE_HOME_Z)     reprapworld_keypad_move_home_z();
    if (REPRAPWORLD_KEYPAD_MOVE_Z_UP)     reprapworld_keypad_move_z_up();

    if (_KEYPAD_MOVE_ALLOWED) {
      if (REPRAPWORLD_KEYPAD_MOVE_Z_DOWN)   reprapworld_keypad_move_z_down();
      if (REPRAPWORLD_KEYPAD_MOVE_X_LEFT)   reprapworld_keypad_move_x_left();
      if (REPRAPWORLD_KEYPAD_MOVE_X_RIGHT)  reprapworld_keypad_move_x_right();
      if (REPRAPWORLD_KEYPAD_MOVE_Y_DOWN)   reprapworld_keypad_move_y_down();
      if (REPRAPWORLD_KEYPAD_MOVE_Y_UP)     reprapworld_keypad_move_y_up();
    }
  #endif
```

so, no homing from keypad, all moves(except Z/extruder distance larger) blocked before homing. 
But safe homing (or setting current position to zero for milling) would be nice.
Or a notice "are you sure you want to do this now? as I have print commands in buffer"

**Comment by Blue-Marlin** [comment]
How about:

``` cpp
  #if ENABLED(REPRAPWORLD_KEYPAD)

    #define _KEYPAD_MOVE_ALLOWED (axis_homed[X_AXIS] && axis_homed[Y_AXIS] && axis_homed[Z_AXIS])

    if (REPRAPWORLD_KEYPAD_MOVE_Z_UP)     reprapworld_keypad_move_z_up();

    if (_KEYPAD_MOVE_ALLOWED) {
      if (REPRAPWORLD_KEYPAD_MOVE_Z_DOWN)   reprapworld_keypad_move_z_down();
      if (REPRAPWORLD_KEYPAD_MOVE_X_LEFT)   reprapworld_keypad_move_x_left();
      if (REPRAPWORLD_KEYPAD_MOVE_X_RIGHT)  reprapworld_keypad_move_x_right();
      if (REPRAPWORLD_KEYPAD_MOVE_Y_DOWN)   reprapworld_keypad_move_y_down();
      if (REPRAPWORLD_KEYPAD_MOVE_Y_UP)     reprapworld_keypad_move_y_up();
    }
    else {
      if (REPRAPWORLD_KEYPAD_MOVE_HOME)     reprapworld_keypad_move_home();
      if (REPRAPWORLD_KEYPAD_MOVE_HOME_Z)   reprapworld_keypad_move_home_z();
    }
  #endif
```

**Comment by maukcc** [comment]
@Blue-Marlin : that worked 
I made some additional changes:

``` cpp
      #if ENABLED(REPRAPWORLD_KEYPAD)

        #define _KEYPAD_MOVE_ALLOWED (axis_homed[X_AXIS] && axis_homed[Y_AXIS] && axis_homed[Z_AXIS])

        if (REPRAPWORLD_KEYPAD_MOVE_Z_UP)     reprapworld_keypad_move_z_up();
        if (REPRAPWORLD_KEYPAD_MOVE_MENU)     reprapworld_keypad_move_menu();

        if (_KEYPAD_MOVE_ALLOWED) {
          if (REPRAPWORLD_KEYPAD_MOVE_Z_DOWN)   reprapworld_keypad_move_z_down();
          if (REPRAPWORLD_KEYPAD_MOVE_X_LEFT)   reprapworld_keypad_move_x_left();
          if (REPRAPWORLD_KEYPAD_MOVE_X_RIGHT)  reprapworld_keypad_move_x_right();
          if (REPRAPWORLD_KEYPAD_MOVE_Y_DOWN)   reprapworld_keypad_move_y_down();
          if (REPRAPWORLD_KEYPAD_MOVE_Y_UP)     reprapworld_keypad_move_y_up();
        }
        else {
          if (REPRAPWORLD_KEYPAD_MOVE_HOME)     reprapworld_keypad_move_home();
        }
      #endif

so homing homes all axis, and the other key (F1) gets you into the move menu to select 0.1 or 1 or 10mm


  #if ENABLED(REPRAPWORLD_KEYPAD)
    static void reprapworld_keypad_move_z_up() {
      encoderPosition = 1;
      lcd_move_z();
    }
    static void reprapworld_keypad_move_z_down() {
      encoderPosition = -1;
      lcd_move_z();
    }
    static void reprapworld_keypad_move_x_left() {
      encoderPosition = -1;
      lcd_move_x();
    }
    static void reprapworld_keypad_move_x_right() {
      encoderPosition = 1;
      lcd_move_x();
    }
    static void reprapworld_keypad_move_y_down() {
      encoderPosition = 1;
      lcd_move_y();
    }
    static void reprapworld_keypad_move_y_up() {
      encoderPosition = -1;
      lcd_move_y();
    }
    static void reprapworld_keypad_move_home() {
      enqueue_and_echo_commands_P(PSTR("G28")); // move all axes home
    }
    static void reprapworld_keypad_move_menu() {
      lcd_goto_menu(lcd_move_menu , 0, false);
    }
  #endif // REPRAPWORLD_KEYPAD
```

this also eliminates the 

``` cpp
#define REPRAPWORLD_KEYPAD_MOVE_STEP 10.0
```

The only thing now is that there is no default move step (0.1  or 1 or 10) at boot

**Comment by thinkyhead** [comment]
I'm working up a PR based on these suggestions. ~~How do you define `REPRAPWORLD_KEYPAD_MOVE_MENU` ?~~ n/m I see you have it as F1.

Note: for the latest code, `lcd_goto_menu(lcd_move_menu)` is sufficient.

I note that in your code above, if the axes are already homed, you disable the keypad homing function. I feel it's fine to allow homing again, and sometimes this might be wanted. Perhaps there is a more effective way to prevent the "axis runaway" problem besides disabling homing…? Such as making this code block non-reentrant. (I will illustrate below.)

Moving Z up always available, even when not homed? That's a useful exception, since it will allow for getting clearance over the bed clips before homing. It will need to be mentioned in the Marlin Documentation. There's no way to prevent Z moving too far up before homing, but I expect Z being at the top (unless Z homes to the top) is very rare. Also, I don't think this exception is useful on DELTA (or other machines that home Z to the top).

What is the rationale for dropping the `REPRAPWORLD_KEYPAD_MOVE_STEP` option? Is that because you can now go to the "Move Axis" menu where you can pick a move size?

**Comment by thinkyhead** [comment]
How about…

``` cpp
if (REPRAPWORLD_KEYPAD_MOVE_HOME)       reprapworld_keypad_move_home();
if (REPRAPWORLD_KEYPAD_MOVE_MENU)       reprapworld_keypad_move_menu();

#if DISABLED(DELTA) && Z_HOME_DIR == -1
  if (REPRAPWORLD_KEYPAD_MOVE_Z_UP)     reprapworld_keypad_move_z_up();
#endif

if (axis_homed[X_AXIS] && axis_homed[Y_AXIS] && axis_homed[Z_AXIS]) {
  #if ENABLED(DELTA) || Z_HOME_DIR != -1
    if (REPRAPWORLD_KEYPAD_MOVE_Z_UP)   reprapworld_keypad_move_z_up();
  #endif
  if (REPRAPWORLD_KEYPAD_MOVE_Z_DOWN)   reprapworld_keypad_move_z_down();
  if (REPRAPWORLD_KEYPAD_MOVE_X_LEFT)   reprapworld_keypad_move_x_left();
  if (REPRAPWORLD_KEYPAD_MOVE_X_RIGHT)  reprapworld_keypad_move_x_right();
  if (REPRAPWORLD_KEYPAD_MOVE_Y_DOWN)   reprapworld_keypad_move_y_down();
  if (REPRAPWORLD_KEYPAD_MOVE_Y_UP)     reprapworld_keypad_move_y_up();
}
```

**Comment by thinkyhead** [comment]
To solve the original issue (where axes may go out of control if you mash the keypad) is actually pretty trivial, and it allows us to keep Home active at all times. To make the keypad handler block non-reentrant calls is straightforward. We just need add a `static bool`:

``` cpp
static bool keypad_move_handling = false;
if (!keypad_move_handling) {
  keypad_move_handling = true;
  // ... handle keypad ...
  keypad_move_handling = false;
}
```

This will prevent the LCD handler from processing any keypad keys during a **_re-entrant call_**, such as occurs when queueing many planner moves in a row, which causes `planner.buffer_line` to call `idle()`, which calls `lcd_update()`.

**Comment by thinkyhead** [comment]
@maukcc See if #3957 helps at all…

**Comment by maukcc** [comment]
close this and let`s move over to #3957
