### ISSUE TITLE
Travis CI went away?

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#3916]
Maybe the `.travis.yml` file is messed up. I haven't seen the Travis tests starting for at least today.

**Comment by boelle** [comment]
@thinkyhead any chance you could open hangout

and delete this post :-)

**Comment by boelle** [comment]
https://travis-ci.org/MarlinFirmware/Marlin

last run 14 mins ago.. thats for bugfix.. which i assume is the most important one

**Comment by jbrazio** [comment]
You're right Scott, we lost the integration with Travis, I have now fixed it so new PR should start to be validated, I don't know about existing PR.
