### ISSUE TITLE
axis position on lcd display

### ISSUE THREAD

**Issue by maukcc** [MarlinFirmware/Marlin#3917]
the axis positions on the LCD main screen only show full integers and not 12.37 (only 12)

**Comment by jbrazio** [comment]
Are you using the latest `RCBugfix` ?

**Comment by thinkyhead** [comment]
This is by design. We have space limitation and XY accuracy is not considered that important. On a 20-character-wide LCD the layout for that line is:

```
|X 000 Y 000 Z 000.00|
```

**Comment by maukcc** [comment]
Understood. This can be closed
