### ISSUE TITLE
Looking for language maintainers

### ISSUE THREAD

**Issue by jbrazio** [MarlinFirmware/Marlin#3919]
We need your help, Marlin has a lot of language packs and we need to create a language team that will be responsible for having the translations up to date. Please answer to this issue with the language you would like to maintain, but be aware we prefer native speakers. We would like to have at least three people per supported language.

When a developer adds a new English string, he should ping the language team by tagging @MarlinFirmware/language-team.
- [ ] English (en)
- [ ] Aragonese (an): @danielmartinez 
- [ ] Basque-Euskera (eu)
- [ ] Bulgarian (bg)
- [ ] Catalan (ca)
- [ ] Chinese (cn)
- [ ] Czech (cz): @clexpert, @petrzjunior
- [x] Danish (da): @boelle 
- [ ] Dutch (nl): @paulusjacobus 
- [ ] Finnish (fi): @tommil
- [ ] French (fr): @gege2b 
- [ ] Galician (gl): @rafacouto
- [ ] German (de): @CONSULitAS, @blubbfish
- [ ] Italian (it): @barus93
- [ ] Japanese (kana): @esenapaj
- [ ] Japanese (kana_utf8): @esenapaj
- [ ] Polish (pl)
- [ ] Portuguese (pt): @jbrazio
- [ ] Portuguese (pt-br)
- [ ] Portuguese (pt-br_utf8)
- [ ] Portuguese (pt_utf8): @jbrazio
- [ ] Russian (ru)
- [ ] Spanish (es): @emartinez167, @RicardoGA, @fbarcenas

**Comment by boelle** [comment]
if the Oled for the sav mk1 was supported i might (no gurantee) do Danish

it works best for me if i get a english file with string that i can translate and test right away... some stuff needs to be display as a whole before it can be certified to be correct translated

the oled is supported here: https://github.com/fmalpartida/Marlin/tree/SAV-MkI-config

**Comment by emartinez167** [comment]
I can take on Spanish

**Comment by jbrazio** [comment]
@boelle we never had a Danish translation ?
I can merge that PR on a branch in my repo so you can test with your display, is it OK ? If everything runs smooth we submit a new PR against RCBugfix.

**Comment by paulusjacobus** [comment]
Happy to help out with Dutch

**Comment by boelle** [comment]
we do have danish in bug fix

https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/language_da.h

**Comment by jbrazio** [comment]
~~@barus93 can we count with you for Italian ?~~
~~@rafacouto can we count with you for Galician ?~~
@gege2b can we count with you for French ?
@koldoartola, @MatixYo can we count with you for Basque-Euskera ?
~~@RicardoGA, @fbarcenas can we count with you for Spanish ?~~
@AnHardt, @Blue-Marlin, @CONSULitAS can we count with you for German ?
@DavidBjerreBjoerklund, @benj4560 can we count with you for Danish ?
@pixatintes can we count with you for Catalan ?
~~@danielmartinez can we count with you for Aragonese ?~~

**Comment by boelle** [comment]
made a few changes do da... will open the english to compare

you should have a PR

**Comment by boelle** [comment]
hehe... now you have.... forgot to push the PR

**Comment by danielmartinez** [comment]
Yes please, count with me for Aragonese, but in several days.

**Comment by jbrazio** [comment]
@danielmartinez we're just building the teams.

**Comment by boelle** [comment]
danish almost there.... i only have a very few defines i need to study more close

**Comment by rafacouto** [comment]
Of course, I'll translate defines into Galician :-)

**Comment by Rikrdoga** [comment]
@jbrazio of course, I can help with Spanish

**Comment by fbarcenas** [comment]
@jbrazio Of course!

**Comment by barus93** [comment]
@jbrazio ok, i can help with italian..

**Comment by jbrazio** [comment]
@boelle we have a script to do it, but has to be ran manually.
Have a look [here](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/buildroot/share/scripts/findMissingTranslations.sh).

**Comment by Roxy-3D** [comment]
We have a lot of hard coded English strings.  Especially in Marlin_main.cpp.    (Just look at the M48: code.   I'm the guilty party on that one!)  We might want to clean that up too.

**Comment by clexpert** [comment]
We will maintain Czech language as we did.

**Comment by clexpert** [comment]
@jbrazio We have complete Czech language with no problem. All translates on time. Please use @clexpert and @petrzjunior for Czech language as sufficient solution. You can tick this language.

**Comment by Blue-Marlin** [comment]
Dear @Roxy-3DPrintBoard 
M48 has no display messages. Only display messages are translated. All serial output is in English. All strings used for the serial output 'should' be in 'language.h' - not 'language_en.h'. There is no need for immediate action - just if someone is bored he/she could clean up a bit.

**Comment by thinkyhead** [comment]
@boelle Here you go…#3936. Looking forward to that Danish!

**Comment by CONSULitAS** [comment]
@jbrazio 
German is fine for me :smile:

**Comment by CONSULitAS** [comment]
@jbrazio 
BTW: There was a complain about not translated strings in German. 
Many technical terms are the same words in German like in English. 
So perhaps we should add a comment like 'intentionally untranslated' to those.

**Comment by CONSULitAS** [comment]
@jbrazio 
How about groups for the language teams? 
So you could write @team-german to get them.

**Comment by Roxy-3D** [comment]
This will result in a lot of clutter and complexity.   By that same thinking, we will need Code-Maintainers-PreProcessor-Bugs as well as Code-Maintainers-Header-Files etc. etc.   I'm not trying to be overly negative, but lets see if we have too many messages going to the Language-Team. If so, we certainly can rethink this.  But my guess is even if you are not involved in a particular language's support, you might want to see what the issues are and what the decisions are in the other languages.   Right?

**Comment by AnHardt** [comment]
Pleas avoid that overhead.
If i see a need for a change in any file i'll do it, or will ask for help, anyway.
If it would be someones duty, i'd stay away.

Indeed the unbearable German language file, from ending 2014 was the first thing i wanted to change and was the reason for beginning with Marlin programming. :-)

**Comment by jbrazio** [comment]
I plan to have all the people related with language on a "global" language team as I agree with Roxy and Andreas, it will be a clutter for now and usually when we need to add a new string, it must be added to all languages.

@AnHardt may I add you for German then ? :-)

**Comment by AnHardt** [comment]
@jbrazio 
No. _Someone_ includes me.

**Comment by rafacouto** [comment]
Should we translate in the RCBugFix branch? Marlin or MarlinDev repo? I miss a little translator guide (excuse me if it already exists O:) in order to assist new maintainers and non git-ninjas...

**Comment by Roxy-3D** [comment]
MarlinDev is going away.   RCBugFix is the correct place because what ever is there is going forward.  And just for right now, during this release cycle, the RC branch is acting as 'Stable' and probably doesn't get the change applied to it.

**Comment by petrzjunior** [comment]
So now, I think it's the right time to discuss some future plans. 
Will the string be translated on every PR someone defines a new string? Or before every release (say every mothly release) we translate all the string that were added since the last one (maybe push against one fork and track progress in one PR)?

**Comment by jbrazio** [comment]
Usually we need to translate a new string when a new feature is added.. up to now the developer adds the string into the English file and (which I do not agree) adds the same define in English on all other languages. The ideia is when a new string is added on the PR we just ping @MarlinFirmware/language-team informing there is a new string that must be translated.

**Comment by boelle** [comment]
@jbrazio you can tick of danish... i just submitted a pr which should make it complete

i checked 2 times by hand

**Comment by boelle** [comment]
@gege2b can we count with you for French ?
@koldoartola, @MatixYo can we count with you for Basque-Euskera ?
@AnHardt, @Blue-Marlin, @CONSULitAS can we count with you for German ?
@DavidBjerreBjoerklund, @benj4560 can we count with you for Danish ?
@pixatintes can we count with you for Catalan ?

**Comment by thinkyhead** [comment]
> and (which I do not agree) adds the same define in English on all other languages

This is specifically designed to annoy language maintainers into fixing it. 😝  But also, helps ensure the strings are in the same relative position in all language files.
