### ISSUE TITLE
Pause command like change filament

### ISSUE THREAD

**Issue by maukcc** [MarlinFirmware/Marlin#3930]
I would like the pause printing command to be like the change filament command.
So when a pause command is given, retract Xmm, move to a position (preferably the back for pause and the front for change filament) and wait for another press of the dial, while playing irritating sounds : ). Then go back and adjust the retract and resume printing.

Pausing now will make for ill prints as it will ooze all over the place

**Comment by thinkyhead** [comment]
I agree, this would be a good addition. The print head will need (ideally) to raise all the way to the top, to ensure that if you were printing a plate of several objects one-at-a-time, for example, the nozzle won't run into any of them during the pause.

**Comment by maukcc** [comment]
Does anybody actually use the "print several objects one-at-a-time" approach, as I have not had any idea where that may be useful. I would love to hear some examples. 
I like it to be like M600 as you can set your own values of where to move and what to do when pause is being clicked.

**Comment by thinkyhead** [comment]
@maukcc It is meant to always be supported by the firmware. And yes, we have heard from a fair number of people who prefer it, because if one object doesn't come out, for some reason, the others usually still will.

**Comment by brainscan** [comment]
Could it please be adjustable in some way? Never printed one at a time and can't see me ever using it.

**Comment by thinkyhead** [comment]
@brainscan Yes, if we add retraction, Z lift, and parking to the "Pause print" function, rest assured that the amount of retraction and Z lift, and the park position will all be customizable.

**Comment by brainscan** [comment]
That sounds excellent, thanks.

**Comment by petrzjunior** [comment]
If I understeand you correctly, it's the matter of function I work on with @clexpert. You will have option to change filament (same way as you described) form LCD or via M600 code. Need only few days to test it before it will be available here to discuss, improve and maybe merge.

**Comment by thinkyhead** [comment]
> change filament (same way as you described) form LCD or via M600 code

@petrzjunior See #3605 and #3662 (based on your work with @clexpert) for our current work on filament change and `M600`. I would suggest comparing to the code at #3662 which is a patched-up version of your code.

**Comment by petrzjunior** [comment]
@thinkyhead Yes, the code is from my father @clexpert, I was helping him with it, so I know perfectly was is in that thread. :smile:

**Comment by thinkyhead** [comment]
> I was helping him with it

Fantastic! I don't think we've ever had a father-son team contribute anything before.

**Comment by petrzjunior** [comment]
@maukcc #3662 was merged some time ago, now in `RCBugFix`, is it fulfilling your idea? Do you have any suggestions?

**Comment by maukcc** [comment]
NO, it is not fulfilling my idea :). This is the change filament feature and works as predicted.
I need the pause command to move the head to a park position (which may or may not be the same as the change filament position)
And I want to do this pause(and change filament) from my home with octoprint(or any other host), then drive to work, actually change the filament, and press resume, locally, on my LCD display.
Also the stop function still does not shut of the heaters in bugfix.
Back to RC6 :)

**Comment by petrzjunior** [comment]
I hope this could be mor eor less done with M600 if you don't mind beeper beeping whole time while you're driving to work.

> stop function still does not shut of the heaters

You can shut them with g-code, can't you?

**Comment by maukcc** [comment]
Let him beep all night long :)
With M600 I want the extruder to come to the front (for easy access to my extruder or other tool). With pause I want the extruder to go to the back (for easy access to my build platform).

>  You can shut them with g-code, can't you?

Yes, but this is not good enough for a CE certification. the operational stop(not to be confused with the emergency stop) needs to put the machine in a neutral safe mode. Heaters at 400degreesC is not that safe :)

**Comment by jbrazio** [comment]
You speak always from your context.. "I want", "my printer" etc.
We can't start building features for individual needs.

**Comment by thinkyhead** [comment]
> We can't start building features for individual needs.

@maukcc We might not make this a formal addition today, but if you just want to get some action now when you do SD pause and SD resume, make the following changes, adjusting for where you want your XY to move:

``` diff
+ float pause_xy[2];
  static void lcd_sdcard_pause() {
    card.pauseSDPrint();
    print_job_timer.pause();
+   pause_xy[X_AXIS] = current_position[X_AXIS];
+   pause_xy[Y_AXIS] = current_position[Y_AXIS];
+   enqueue_and_echo_commands_P(PSTR("M83\nG1 E-3 F8000\nM82\nG1 X0 Y200"));
  }

  static void lcd_sdcard_resume() {
+   cmd[60];
+   sprintf_P(cmd, PSTR("G1 X%i Y%i F8000", pause_xy[X_AXIS], pause_xy[Y_AXIS]);
+   enqueue_and_echo_command_now(cmd);
+   enqueue_and_echo_commands_P(PSTR("M83\nG1 E3\nM82"));
+   safe_delay(250);
+   stepper.synchronize();
    card.startFileprint();
    print_job_timer.start();
  }
```

**Comment by Drayson80** [comment]
Very good, but is there a way to set it up into standard - so as a formal addition??
somewhere in the configuration "define pause position" and those lines? 
I would really like to see get CE conformity in terms of safety so from ym point of view a propper stop (not emergency stop!) and pause behavior should be mandatory...

**Comment by thinkyhead** [comment]
> I would really like to see get CE conformity

@Drayson80 et. al. Are you able to create a branch, apply changes, commit, and submit pull requests? That's how things usually get into Marlin. Otherwise, it sounds like you're more-or-less demanding that other generous volunteers do this on your behalf.

**Comment by Drayson80** [comment]
I would love to do so as I would not depend on somebody else - but I have no clue about programming, and beleve me, it´s good so....
Anyway, thanks for your reply - I thought it´s not only about doing things but also recommending things... my fault...

**Comment by thinkyhead** [comment]
> but also recommending things

True. With the understanding that suggestions may be put off indefinitely or utterly rejected.
But not this one. It's a good suggestion.

We already have this feature on the long-term plans list. (Requested a few times too. See #4762, #4627, #4131, etc.) But it's non-trivial, and it will need to be tested on a wide variety of setups. Time is just very limited right now, and I don't even have a 3D printer at my disposal if I wanted to work on this. So it just has to wait.

**Comment by tximy** [comment]
This is an great feature for multiple extruders and serial runout filament sensors not indicate the attached extruder for filament change, the pause is ok for it.

**Comment by thinkyhead** [comment]
We now have this. `PARK_HEAD_ON_PAUSE`. It requires also enabling `M600`.
