### ISSUE TITLE
Gofoundme is not working right

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#3960]
i wanted to donate again... but after i have filled out address etc... click continue

it does not give any error but it does not continue to next page either

**Comment by boelle** [comment]
fix... fill out all empty box'es with a dash -

**Comment by jbrazio** [comment]
Bo I would suggest to speak with @thinkyhead as we can't do anything to fix the issue.

**Comment by thinkyhead** [comment]
Thanks for thinking of me, Bo! 🌹  I have my coffee and my felafel, and am on the case today! I suggest that you try a different browser if your default one isn't working for GoFundMe. But better yet, you can use [this direct link](http://paypal.me/thinkyhead) to donate, and it comes to me more quickly.

**_[edit] Aha, I see, you fixed it by putting dashes in the unused fields. Great, thank you again!_**

**Comment by Grogyan** [comment]
Or just use Patreon.
Which makes it easy to donate to Gina for OctoPrint, as well as @thinkyhead
