### ISSUE TITLE
Clock / Timer Not Working 1.1.0-RC6

### ISSUE THREAD

**Issue by Eddiiie** [MarlinFirmware/Marlin#3970]
RAMPS 1.4, Full Graphic Display
Prusa i3  type printer

Power on
Preheat PLA
Print from SD
   Print

Clock / time does not work.

Power on
Print from SD
  print...   Clock/timer works
  Cancel print
Print from SD
  print...  timer does not reset, keeps going

**Comment by jbrazio** [comment]
This has been fixed with RCBugfix PR #3756 #3813
