### ISSUE TITLE
pin state at splashscreen

### ISSUE THREAD

**Issue by maukcc** [MarlinFirmware/Marlin#3973]
when you startup the printer you can hear the motors making some (crackling) noises.
This is due to the fact that the motor enable pins(and probably others as well) of the arduino are in a "don't care" state.
I always thought that this was because of the "boot time" of the arduino, but it actually lasts as long as the splash screen is open. 
Any ideas? and: changing the electronics to handle this, is not a good enough idea :)

**Comment by thinkyhead** [comment]
To change this behavior, you can try moving the call to `lcd_init()` to a later point in `setup()`. That will ensure everything else is initialized before the LCD.

Alternatively, when there's a boot screen (`SHOW_BOOTSCREEN`) we could still call `lcd_init()` early in `setup()`, but remove the `delay(1000)` called in `lcd_implementation_init`, moving it to the end of `setup()` instead, followed by a call to `lcd_implementation_clear()`. That would allow everything to initialize before the boot screen delay.
