### ISSUE TITLE
Print is hanging on bed temperature check

### ISSUE THREAD

**Issue by pauldesmet** [MarlinFirmware/Marlin#3974]
I installed Marlin RC6 on the Rumba board of my BigBox.
1. G-code print contained 

``` gcode
M104 S210 T0
M109 S210 T0
```

Print did not start but hanged at the bed temperature check.
1. second trial. I set bed temperature manually on LCD at 210.
   I started the same G Code but deleted the line M109 S210 T0
   The print worked perfectly

Conclusion ??  Test done on M109 does not work correctly

**Comment by manianac** [comment]
Maybe you have an impossible to reach WATCH_PERIOD?  Can you check the serial console?

**Comment by Rikrdoga** [comment]
@pauldesmet are you using RC6 or RCBugFix?? Another thing to check is in configuration is the residency time

**Comment by thinkyhead** [comment]
@pauldesmet This might be fixed in `RCBugFix` (the latest code), as we have done some patching around thermal handling. Be sure to test with that when you have a chance.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
