### ISSUE TITLE
RC5 extruder coordinate overflow on LCD

### ISSUE THREAD

**Issue by orcinus** [MarlinFirmware/Marlin#3977]
If the extruder coordinates exceed 999, the coordinate output on the LCD seems to overflow into non-numeric characters:

https://www.youtube.com/watch?v=SwJ95ZivCC4

The actual coordinates were:

https://dl.dropboxusercontent.com/u/1702513/Photo%2007-06-16%2021%2000%2054.jpg

Suggested fix - for E axis, display relative position (since entering the Move Axis submenu) instead of absolute position, which is irrelevant and not very useful anyways.

**Comment by Blue-Marlin** [comment]
Try

``` diff
          #endif //EXTRUDERS > 3
        #endif //EXTRUDERS > 2
      }
    #endif //EXTRUDERS > 1
-    lcd_implementation_drawedit(pos_label, ftostr31(current_position[E_AXIS]));
+    lcd_implementation_drawedit(pos_label, ftostr51(current_position[E_AXIS]));
  }
  if (LCD_CLICKED) lcd_goto_previous_menu(true);
  #if EXTRUDERS > 1
    active_extruder = original_active_extruder;
  #endif
}
```

in `ultralcd.cpp`

Relative to what?

**Comment by orcinus** [comment]
Relative to 0 set when you've entered the submenu.

**Comment by orcinus** [comment]
I really don't have a use for the absolute number of mm extruded since the printer was turned on. I doubt anyone else does, especially when manually jogging the extruder.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.

**Comment by jbrazio** [comment]
For reference: 45ea8749

**Comment by orcinus** [comment]
Why close it instead of pushing the milestone further?
This is a bizarre way of managing issues.

**Comment by orcinus** [comment]
Additional comment re: question on "relative to what" and my previous answer of "relative to 0 set when you've entered the submenu"...

That is the exact same way Babystepping menu item is currently behaving. It displays relative state since selecting that menu item. So the behaviour i'm proposing as a fix already exists in the UI (so shouldn't be too confusing UX-wise).

**Comment by jbrazio** [comment]
Wasn't this fixed by the referenced commit ?

**Comment by thinkyhead** [comment]
The line has long been changed. Now:
```cpp
lcd_implementation_drawedit(pos_label, ftostr41sign(current_position[E_AXIS]));
```

**Comment by thinkyhead** [comment]
> Wasn't this fixed by the referenced commit ?

The length of the number was fixed.

> "relative to 0 set when you've entered the submenu"

@orcinus Thing is, the E axis is an actual axis. It has relevance because it corresponds to GCode you could send from the console alongside it. For instance – adjusting E you see it is at `722.3` on the display, then you can send `G1 E730` to move ahead (without having to use relative mode).

If you want some guidance on how to do this customization, I'm sure we can help. But as a standard addition to Marlin… I lean towards leaving it as it is.

**Comment by orcinus** [comment]
The Z axis is an actual axis too, yet - relative babystepping : )
But i get your point - in the current move menu, it would not be consistent with other axes.

**Comment by thinkyhead** [comment]
> babystepping

Right - It's a different feature. Babystepping doesn't even override the high-level position (except later, if the stepper positions are used to re-orient the high-level position) so it's only useful in the midst of printing.
