### ISSUE TITLE
Print offsets in multiple hotend configuration

### ISSUE THREAD

**Issue by lavato** [MarlinFirmware/Marlin#3987]
I just came across this issue  when I started printing larger object yesterday.

**Printer Configuration**
X carriage has following attached (from left to right):
HotEnd2, HotEnd1 and a Sensor (each taking 30mm space)

**Relevant Configuration.h details**

```
#define HOTEND_OFFSET_X {0.0, -30.20}
#define HOTEND_OFFSET_Y {0.0, -1.20}
#define X_PROBE_OFFSET_FROM_EXTRUDER 30
#define Y_PROBE_OFFSET_FROM_EXTRUDER 0
#define Z_PROBE_OFFSET_FROM_EXTRUDER -1.90
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0
#define X_MAX_POS 190
#define Y_MAX_POS 190
#define Z_MAX_POS 180
```

**How to reproduce**
1) Generate gcode so HotEnd 1 is used (the one in the middle, which can cover the biggest area)
2) Start print
3) The print offsets by +15mm on X and +5mm on Y (in my case)
So instead of print starting e.g. at X20, Y20, it starts at X35 & Y25

**Some more points**
- After G28 is issued, LCD displays X-15,Y-5,Z1.9 and the HotEnd1 is at actual X0 & Y0.  
  _Not sure why I get *_X-15,Y-5**
- I compiled a vanilla MarlinBugFix release and stored in EEPROM.
- If I apply offsets from LCD than all is OK - am I missing something?

**Versions**
BugFix from 08/Jun
RAMPs1.4
PrusaI3

**Comment by thinkyhead** [comment]
What is your output from `M503`?

**Comment by lavato** [comment]
I am not sure what is  happening now, some funny behavior with my EEPROM it seams but I cannot reproduce the X-15,Y-5,Z1.9 after g28 and the print starts at x0,y0

This "correction" happened after I applied offsets and stored it to EEPROM. 
Since, I recompiled the Firmware uploaded it to Arduino but still I have X0 & Y0, **which is now correct**

Here is the output.

```
>>>M503
SENDING:M503
echo:Steps per unit:
echo:  M92 X71.14 Y71.37 Z400.30 E94.29
echo:Maximum feedrates (mm/s):
echo:  M203 X500.00 Y500.00 Z3.00 E35.00
echo:Maximum Acceleration (mm/s2):
echo:  M201 X3000 Y3000 Z100 E10000
echo:Accelerations: P=printing, R=retract and T=travel
echo:  M204 P3000.00 R3000.00 T3000.00
echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
echo:  M205 S0.00 T0.00 B20000 X20.00 Z0.40 E5.00
echo:Home offset (mm):
echo:  M206 X0.00 Y0.00 Z0.00
echo:Material heatup parameters:
echo:  M145 S0 H180 B0 F0
echo:  M145 S1 H240 B80 F0
echo:PID settings:
echo:  M301 P22.20 I1.08 D114.00 C100.00 L20
echo:Filament settings: Disabled
echo:  M200 D3.00
echo:  M200 T1 D3.00
echo:  M200 D0
echo:Z-Probe Offset (mm):
echo:  M851 Z-1.90
```

If I have something more tangible or this reoccurres again, I will open a new issue,

Thank you anyway.

**Comment by thinkyhead** [comment]
Good news @lavato. I was concerned that your `M206` might not be zeroed.
