### ISSUE TITLE
Compilation error with BEEPER_PIN -1 or #undef BEEPER_PIN

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#3999]
After PR #3995(New feature: Non blocking tone queue) was meged, I've gotten compilation errors.
If I set the BEEPER_PIN to -1 for disable beep, it causes compilation error.
[error log.txt](https://github.com/MarlinFirmware/Marlin/files/309369/error.log.txt)

If I undefine the BEEPER_PIN by #undef BEEPER_PIN, I got another error.
[error log2.txt](https://github.com/MarlinFirmware/Marlin/files/309378/error.log2.txt)

Settings:
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/309382/Configuration.txt)
[pins_RAMPS_14.txt](https://github.com/MarlinFirmware/Marlin/files/309383/pins_RAMPS_14.txt)

**Comment by jbrazio** [comment]
Seems an error with `#define HAS_BUZZER`, will check ASAP.

**Comment by jbrazio** [comment]
@esenapaj could you please try the following diff ?

``` diff
diff --git a/Marlin/ultralcd.h b/Marlin/ultralcd.h
index 5cb1ecc..e855835 100644
--- a/Marlin/ultralcd.h
+++ b/Marlin/ultralcd.h
@@ -27,8 +27,6 @@

 #if ENABLED(ULTRA_LCD)

-  #include "buzzer.h"
-
   #define BUTTON_EXISTS(BN) (defined(BTN_## BN) && BTN_## BN >= 0)
   #define BUTTON_PRESSED(BN) !READ(BTN_## BN)
```

**Comment by ghost** [comment]
> could you please try the following diff ?

Thanks for the quick fix.
I've confirmed just now that compilation error is gone by the diff.
