### ISSUE TITLE
Switching tools moves head since #3620

### ISSUE THREAD

**Issue by Alex9779** [MarlinFirmware/Marlin#4000]
#3620 was meant to fix the feederate after a tool change but also introduced that switching the tool also moves the print head.

I think this is because of the tool offset which is applied to the current position when switching.

My question is wether this intended behaviour and just didn't work before that PR or not?

In previous versions up to RC6 switching tools didn't result in a move of the head. I have to say this is not good for my setup, I have a dock area where movement is limited, I move there always with T0 selected to be sure the movement doesn't crash the head anywhere. Otherwise it would have to use different docking sequences depending on which print head is active which is not practical...
But when I am in the dock area I am switching tool to purge nozzles and stuff. When the head moves because of the tool offset the head crashes...

**Comment by thinkyhead** [comment]
> intended behaviour and just didn't work

That is correct. This needed to be fixed, otherwise printing would start in the wrong place after a tool change.

So, the tool has to move when switching. But its movement is constrained, so it should never try to move past the set movement limits as defined by your `*_MIN_POS` and `*_MAX_POS` settings (i.e., the software endstops). It sounds to me like you just need to consider the tool offset and the currently-selected tool in your docking procedures.

Do you use the `Z_PROBE_SLED` and `SLED_DOCKING_OFFSET` options, or is your probe a standard type, but you also have a dock?

**Comment by Alex9779** [comment]
> It sounds to me like you just need to consider the tool offset and the currently-selected tool in your docking procedures.
> 
> is your probe a standard type, but you also have a dock

I think this is not possible for me, the tools are on the same head, the dock is in the back of the box but just as wide as one and a half of the print head.
![bed_hotends_limits](https://cloud.githubusercontent.com/assets/6394581/15983749/ee763114-2fb1-11e6-8cd8-654d662dfde2.png)
Software endstops don't work here because Marlin only know the full X movement range but in the dock this is limited physically.
The procedure is like so I move to the head to the dock where I can prime and clean the nozzles. In the dock I have to switch tools on a tool change because I need to clean the old tool and prime the new tool.

I need a method to switch tools without moving the head.The coordinates can change I have no problem with that before moving out of the dock I select tool 0 again and position the head before the dock, then the normal print continues selecting the correct tool and moves the print head to the correct position able the print bed.

**Comment by thinkyhead** [comment]
@Alex9779 Well if all we need is an option to keep the carriage where it is, then #4013 will do that. It allows you to add `S1` to your tool-change command, and the carriage will stay in place. However, note that the current position, software endstops, etc., will be changed to the position of the new tool.

**Comment by Alex9779** [comment]
Thanks. I will review that PR...

**Comment by Alex9779** [comment]
@thinkyhead Ok by your wording I thought this was an existing PR but you created it again because of me? You are a freak ;-)
Unfortunately I can't verify at the moment, because I haven't made the config for RCBugFix yet.

**Comment by Alex9779** [comment]
@thinkyhead ok I tested it and it seems to work. Though I have no idea what you tried to tell me with:

> note that the current position, software endstops, etc., will be changed to the position of the new tool

That is fine so I think, the LCD updates to the new position, but I won't make moves with T1 activated in that area, before next XY move I switch back to T0 with S1 now.

But I found another problem, I am going to open an other issue for this...
