### ISSUE TITLE
Crash after setting Flowrate 

### ISSUE THREAD

**Issue by Massa0815** [MarlinFirmware/Marlin#4009]
When i adjust the Flowrate in the menu during printing sometimes Marlin crashes completely. In my special case i changed the flowrate from 85% to 90%

I installed RC Bugfix #3110

**Comment by thinkyhead** [comment]
Now that #3110 is merged, you can just test with the current `RCBugFix`.

I'm not sure how we can narrow this down. Can you try doing some other things in the menus, such as value editing, and see if anything else causes a crash?

**Comment by Massa0815** [comment]
Ok. Give me a few days. I disassambled my Hetabed for a new cable chain. When i reassambled it i will test it. Thanks

**Comment by Massa0815** [comment]
I tested the actual bugfix. The bug is still present. I think its only the flowrate which produces the crash. It occurs when i confirm the changed flowrate. The display freezes. But there are still some moves the printer performs until complete crash.

**Comment by thinkyhead** [comment]
I can find nothing wrong with the menu function that sets the flow rate in particular. So perhaps it has something to do with the function to print the value, or the display update.

Also, you might try building with Arduino 1.6.0, if you are using 1.6.7 or later. We're seeing some unusual issues that might be compiler-related, so I just want to eliminate that possibility.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
