### ISSUE TITLE
Move E axis with LCD moves always only active tool

### ISSUE THREAD

**Issue by Alex9779** [MarlinFirmware/Marlin#4016]
I tried RCBugFix today and realised that moving the E axis with the LCD always moves the E axis of the current selected tool regardless the menu entry (Extruder 1 or Extruder 2) I choose.

To reproduce:
- I power on my machine.
- I heat up the hotends.
- I go to "Prepare"->"Move axis"->"Move 1mm"->"Extruder1" and move --> Extruder 1 moves.
- I go to "Prepare"->"Move axis"->"Move 1mm"->"Extruder2" and move --> Extruder 1 moves (!).
- I send T1 to the machine.
- I go to "Prepare"->"Move axis"->"Move 1mm"->"Extruder1" and move --> Extruder 2 moves (!).
- I go to "Prepare"->"Move axis"->"Move 1mm"->"Extruder2" and move --> Extruder 2 moves.

**Comment by Alex9779** [comment]
BTW regarding #4000 if moving an E axis with the LCD the head should not move. No idea how the LCD call works but having tool 0 active and moving E1 with the LCD must not move the head and vice versa...

**Comment by thinkyhead** [comment]
> if moving an E axis with the LCD the head should not move

Does it do that now? It should just move E and nothing else, assuming current position is correct.

**Comment by Alex9779** [comment]
> Does it do that now?

I just wrote that I don't know how the code to move from LCD works and because the head didn't move until that other fix I have no idea if it would now IF it would move the correct extruder.

I will test newest RCBugFix and report...

**Comment by Alex9779** [comment]
Moving E axes works again from the LCD with the fix from #4047...
