### ISSUE TITLE
Question:  Why are we not using run_z_probe() for the Z-Axis in G28 ?

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#4018]
Is there a reason we are not using run_z_probe() to handle the Z-Axis when we have Bed Leveling (when we know we have a Z-Probe) ?    It seems like we have a bunch of redundant code because of that.  We have to have the probe_pt() code.  

So shouldn't we end up in this same code if we are doing a G28 Z ????

**Comment by thinkyhead** [comment]
Let me review this in my head here… The `run_z_probe` function is shared code. The `probe_pt` function calls it to do a single probe (so `gcode_G29` uses it). And the `gcode_G30` function also calls it.

That isn't to say that the code in `gcode_G29` and `gcode_G30` are ideal, or that the probing functions are as clean as they could be. For the most part all these functions were adapted from code that already existed.

Ideally we'll want a probe-management class that encapsulates each common step in the probing process, and then adapts each of those putative steps to the particular probe and endstops that you have.

So your probe functions might just end up as simple as this:

``` cpp
void full_probing_process() {
  home_if_needed();
  move_to_starting_point();
  undock_z_probe();
  probe_and_calculate();
  dock_z_probe();
}

void probe_and_calculate(bool each_flag=false) {
  deploy_probe_before(!each_flag);
  while(move_to_next_point()) {
    deploy_probe_for_each(each_flag);
    activate_probe();
    probe_z_here();
    deactivate_probe();
    stow_probe_for_each(each_flag);
  }
  stow_probe_after(!each_flag);
  calculate_leveling();
}
```

**Comment by thinkyhead** [comment]
> shouldn't we end up in this same code if we are doing a G28 Z?

Possibly. We should see where the special-cases lie in `G28 Z` when the Z probe is being used as the Z endstop.

Somehow our homing functions could end up being much cleaner too…

``` cpp
void full_homing_process(byte axis_bits) {
  if (z_first && TEST(axis_bits, Z_AXIS)) {
    home_z(true);
    CBI(axis_bits, Z_AXIS);
  }
  if (quick_home && TEST(axis_bits, X_AXIS) && TEST(axis_bits, Y_AXIS)) {
    home_xy();
    CBI(axis_bits, X_AXIS);
    CBI(axis_bits, Y_AXIS);
  }
  else if (home_y_before_x && TEST(axis_bits, Y_AXIS)) {
    home_y();
    CBI(axis_bits, Y_AXIS);
  }
  if (TEST(axis_bits, X_AXIS)) home_x();
  if (TEST(axis_bits, Y_AXIS)) home_y();
  if (TEST(axis_bits, Z_AXIS)) home_z(false);
}

```

**Comment by Roxy-3D** [comment]
The reason I'm asking is run_z_probe()  and probe_pt() were behaving correctly.  But G28 was not doing a Z_RAISE_AFTER_PROBE.   My probe was OK just because of the direction the roller was on the micro-switch.   But I ended up having to add a raise_z_after_probing(); in to homeaxis() to fix the problem:

```
    // Retract Servo endstop if enabled
    #if HAS_SERVO_ENDSTOPS
      if (_Z_SERVO_TEST && servo_endstop_id[axis] >= 0) {
        #if ENABLED(DEBUG_LEVELING_FEATURE)
          if (DEBUGGING(LEVELING)) SERIAL_ECHOLNPGM("> SERVO_ENDSTOPS > Stow with servo.move()");
        #endif
        raise_z_after_probing();

        servo[servo_endstop_id[axis]].move(servo_endstop_angle[axis][1]);
        if (_Z_PROBE_SUBTEST) endstops.enable_z_probe(false);
      }
    #endif
```

Perhaps this should be added to RCBugFix?   The thing that has me scratching my head is everybody must be seeing this issue.  But nobody is complaining?

**Comment by thinkyhead** [comment]
Looks like you could use `raise_z_for_servo()` instead. That's what other functions use when not `G29` probing.

**Comment by Roxy-3D** [comment]
OK.  I'll switch to raise_z_for_servo().    But do you agree this is a bug?  I can't be the only person seeing this behavior, right?

**Comment by thinkyhead** [comment]
Yes, the homing, probing, stowing, deploying, etc. code as I scan through it is spaghetti.

I suggest being methodical and consider encapsulating each little step, at least as an exercise. Or maybe your UBL code will save us from all of this!

**Comment by Roxy-3D** [comment]
> Yes, the homing, probing, stowing, deploying, etc. code as I scan through it is spaghetti.

To be honest...  That is why I was asking the question "Why are we not using run_z_probe() for the G28?"   I was hoping we could just delete all that spaghetti code in G28 and get rid of #ifdef's nested 13 layers deep.   As a side benefit, both G28 and G29 would start agreeing on where the Z-Axis was positioned!

> I suggest being methodical and consider encapsulating each little step, at least as an exercise. Or maybe your UBL code will save us from all of this!

No...  The Unified Bed Leveling won't directly clean this up.  It sits on top of the Z-Probe functions.   But when we do get a Z-Probe object, it should slip in place without any pain.   And a whole bunch more code with nested #ifdef's will disappear!   :)

**Comment by thinkyhead** [comment]
Hmm. Well, I get this feeling like, if we just took each segment of each of these processes, and placed them into smaller functions, then after doing this a while they would start to merge and converge, and we'll end up with something minimal. It's a roundabout (or maybe straightforward) way of accomplishing both analysis and consolidation at the same time.

**Comment by thinkyhead** [comment]
I think the main complication to doing this (up to now) is just the special-cases, and in a few spots, not quite understanding what is necessary vs. what is provisional (for example, when measuring Z heights in a probe process, we should preserve "known position" so Z is always true to the uncorrected matrix).

**Comment by Roxy-3D** [comment]
I agree that approach would work.   But we have the Z-Probe routines working and doing the right thing.   I wonder if it would be easier to just delete all the Z-Axis code in G28 that doesn't relate to a simple endstop and replace it with a probe_pt() ????

**Comment by thinkyhead** [comment]
You can try that, and it might work on your robot, but then we don't know if it's good across all robots without more testing.

**Comment by Roxy-3D** [comment]
Agreed!    This is such a drastic change, we probably don't even want to think about it in an RC branch.

**Comment by thinkyhead** [comment]
Truly. Whereas, moving snippets out of a big function into smaller functions can be accomplished without any disruption, as part of the "general cleanup" stuff that we more or less always do along the way.

**Comment by thinkyhead** [comment]
Before diving into too much of that, a good first step is to just do more liberal code-commenting and documentation throughout these functions. Explaining the rationale for each piece of logic. Out of that we will gain a better high-level view of this spaghetti monster.

**Comment by thinkyhead** [comment]
Not too fond of that `raise_z_for_servo()` function. It's not as smart as it should be.

> But do you agree this is a bug?

As I look around at the different functions that move the servo, there are some places where `raise_z_for_servo()` is called, and others where it isn't. It seems to me it should be called everyplace. But maybe in the places where it's not being called, it already expects Z to be raised. I will have to look at each case. And this little "general cleanup" I hope will help clear it up also.

**Comment by Roxy-3D** [comment]
I can switch back to raise_z_after_probing();    After all...  That is really what needs to happen in that part of the G28 code.

**Comment by thinkyhead** [comment]
At one point I proposed replacing all the "raise z" values with a single `Z_PROBE_CLEARANCE` value. This is the space the probe needs to deploy/stow, or the height needed to keep an inductive probe from triggering early. You could still have a lower `Z_RAISE_BETWEEN_POINTS` value, if preferred….

**Comment by Roxy-3D** [comment]
Yeah...  The problem with the Z_RAISE numbers is we don't always want to raise the Z-Axis.  What we want is a minimal height of that number.  At a minimum, we should consider renaming those #defines.   

But I do think some people need the Z_RAISE_BETWEEN number just because the amount of clearance needed to deploy and stow is different than what you need to run the nozzle (probe) around on the bed.    And given how slow my Z-Axis is, I want the control to let that be different and smaller than the BEFORE and AFTER number.

**Comment by thinkyhead** [comment]
We also talked about opting for "minimum height" rather than in terms of "raise" – which might tend to simplify things a little.

**Comment by thinkyhead** [comment]
Well, this short conversation could easily lead to a whole day of tweaking, haha. But I should comb through my other 20 notifications, see if there are any little things to fix first….

**Comment by Roxy-3D** [comment]
No hurry on any of this...  Other than maybe you have 21 notifications and not 20 if you believe that I stumbled on a bug.

**Comment by thinkyhead** [comment]
I think you stumbled on a weird oversight that might be in a few places. Surely we have lots of servo users. Maybe they all figured out workarounds in their settings, and when we fix this it will mess them up, haha!

**Comment by thinkyhead** [comment]
See what you think of #4021

**Comment by jstefanop** [comment]
Does this have anything to do with why G92 does not work (to set the Z offset of the prob in relation to nozzle after it does a G28 and G29) in RC6?

**Comment by Roxy-3D** [comment]
G92 doesn't work any more?   Can you tell us which RC# it quit working at?

**Comment by jstefanop** [comment]
It was working on RC3 and tried out RC6, and normal G92 Z1.3; command I have been using for nozzle offset no longer has an effect. The machine has a Z-probe for both endstop and ABL if that makes a difference.

**Comment by thinkyhead** [comment]
@jstefanop The `G92` command is not the correct way to do this. It not only sets your current position, but with recent bug patches it also moves the coordinate space (and the software endstops). You should instead use the probe z offset (`M851` / `Z_PROBE_OFFSET_FROM_EXTRUDER`) to set the offset from your probe to your nozzle.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.

PS: Lately huge development has been put into G28, ABL and MBL.
