### ISSUE TITLE
Mesh Bed Leveling loses state randomly

### ISSUE THREAD

**Issue by orcinus** [MarlinFirmware/Marlin#4019]
Apologies if this has already been reported or fixed (couldn't find it).
On RC5, MBL sometimes loses its setting completely.

As in, on power-on, the printer will home, then _won't_ bring the Z up to the calibrated MBL value, and will not do MBL corrections during printing.

Don't ask me to reproduce it, i can't. It's utterly random.
Reloading settings and/or restarting fixes it, until the next time it happens.

**Comment by epatel** [comment]
This has probably been fixed. See this https://github.com/MarlinFirmware/Marlin/issues/3750

Long story short, you probably have some `G28` homing single axis (not all axis) in your end g-code. But a fix has been added to handle this now.

**Comment by orcinus** [comment]
Ah! Sorry, somehow missed that issue.
FWIW, i don't have G28 in my end g-code, but i _did_ issue a G28 manually today, so that makes perfect sense.
