### ISSUE TITLE
Marlin end-user survey results

### ISSUE THREAD

**Issue by jbrazio** [MarlinFirmware/Marlin#4026]
These are the results of the survey we did which had a total of 372 answers.
PS: If you'd like other views on the data just leave a comment.
## 

![chart_version](https://cloud.githubusercontent.com/assets/264365/15994601/6b4bc9e2-3101-11e6-96fb-2f80c12bd318.png)

![chart_boards](https://cloud.githubusercontent.com/assets/264365/15994604/6f9ac674-3101-11e6-8a70-db3d3dc34798.png)

![chart_cores](https://cloud.githubusercontent.com/assets/264365/15994605/769f4a12-3101-11e6-955f-acfdb9e3e48e.png)

![chart_ide](https://cloud.githubusercontent.com/assets/264365/15994606/7da8575e-3101-11e6-8c30-10547d2cfb2e.png)

**Comment by bobc** [comment]
Does that mean most users (who responded) are using Arduino Mega + RAMPS and majority of users are running IDE 1.6.x?

Either way, interesting results.

**Comment by fbarcenas** [comment]
Really interesting...
