### ISSUE TITLE
Marlin crashes!  We must have a problem with the SERIAL_PROTOCOL() routines???

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#4031]
Please add this code to your Marlin_main.cpp file and give Marlin an M86 command.  It will repeat a few times (16 on my machine) and then Marlin will crash and reboot.    Why did I pick M86 for the sample code?   Well, it 86's my printer!  http://mentalfloss.com/article/51880/where-did-term-86-come

```
      case 77: // Stop print timer
        gcode_M77();
        break;

      #if ENABLED(PRINTCOUNTER)
        case 78: // Show print statistics
          gcode_M78();
          break;
      #endif

      case 86:  {
                int qwerty=0;
                SERIAL_ECHO_START;
                SERIAL_PROTOCOLPGM("Checking for crash problem in SERIAL_PROTOCOL() routines:\n");
                while( !lcd_clicked() ) {
                     delay(250);
                     SERIAL_PROTOCOL( qwerty++ );
                     SERIAL_EOL;
                }
            }
            break;
```

**Comment by Blue-Marlin** [comment]
If you have `#define USE_WATCHDOG` that is what you see.
Put an `idle();` in your loop, or at least a `thermalManager.manage_heater();`

**Comment by Roxy-3D** [comment]
Thanks so much Blue-Marlin!!!!!!

**Comment by Blue-Marlin** [comment]
16 \* 0.25 = 4 !!!

**Comment by Roxy-3D** [comment]
Yes!   I feel like an idiot!   :)
