### ISSUE TITLE
[Request] Lock out Advanced Features From Display

### ISSUE THREAD

**Issue by Grogyan** [MarlinFirmware/Marlin#4067]
Something that would make Makerspace/School printers more useful, would be to have a limited number of features accessible from a smart display, such as the Full Graphic Display.
Leaving the Advanced features locked out unless the user knows of the correct sequence of buttons/knobs/turns on the display.

This would prevent novice/inexperienced persons from meddling with features that can, and do, muck up the printer

**Comment by jbrazio** [comment]
In fact I believe the menu system needs to be rewritten for no technical guys..
A proper designed UI needs to have [at least] the most used features on top of the menu.. it makes no sense to move an axis to dig down four levels deep in the menu.. but once again, not for this RC.

**Comment by Roxy-3D** [comment]
> In fact I believe the menu system needs to be rewritten for no technical guys..
A proper designed UI needs to have [at least] the most used features on top of the menu.

Agreed!

**Comment by boelle** [comment]
@thinkyhead 

maybe add this to 1.1.1 milestone?

**Comment by landodragon141** [comment]
@thinkyhead This is probably obsolete.
