### ISSUE TITLE
using I2c of RAMPS 1.4 

### ISSUE THREAD

**Issue by pankajbadatia** [MarlinFirmware/Marlin#4068]
Hi all  I want to know how can i connect RAMPS as masster and other arduino as slave using I2c communication.
which code should i edit . 
my slave address is 0x08 
start bit 0x01
command bit 0x02
stop bit 0x17

**Comment by thinkyhead** [comment]
With #3258 we added an i2c bus feature, which exists in `RC6` and the current `RCBugFix`. Enable `EXPERIMENTAL_I2CBUS` in `Configuration_adv.h` and you can use it to experiment with sending and receiving bytes using GCode commands.

**Comment by pankajbadatia** [comment]
Thank you .. I did it but i have confusion between sending hex value and byte or char

**Comment by jbrazio** [comment]
What is the confusion ?

**Comment by pankajbadatia** [comment]
address is in hex  when 

``` gcode
M155 A8 // slave address
M155 B1 // start bit
M155 B2 // command
M155 B23 // stop bit
M155 S1 // send 
```

it doesn't work . Is this correct way to send command??

**Comment by pankajbadatia** [comment]
``` cpp
 * ; Example #1
 * ; This macro send the string "Marlin" to the slave device with address 0x63
 * ; It uses multiple M155 commands with one B<base 10> arg
 * M155 A63  ; Target slave address
 * M155 B77  ; M
 * M155 B97  ; a
 * M155 B114 ; r
 * M155 B108 ; l
 * M155 B105 ; i
 * M155 B110 ; n
 * M155 S1   ; Send the current buffer
```

I am reffering this

**Comment by jbrazio** [comment]
> It uses multiple M155 commands with one B<base 10> arg

`M155 B77` the 77 is ASCII "M" in decimal (base 10).
In your case you only need to convert `M155 B23` (base 16) to `M155 B35` (base 10).

![asciifull](https://cloud.githubusercontent.com/assets/264365/16192664/88351b3a-36e2-11e6-9fb3-a437c16b32be.gif)

**Comment by thinkyhead** [comment]
> confusion between sending hex value and byte or char
> you only need to convert M155 B23 (base 16) to M155 B35

@pankajbadatia
Actually, it looks like you did the right conversions. 0x17 is 23 decimal.
What result do you expect when you send `8: 1, 2, 23`?

> …address is in hex when…

All values are expressed in decimal. So in your second example `A63` should be `A99`.

> ```
> ; Example #1
> ; This macro send the string "Marlin" to the slave device with address 0x63
> ; It uses multiple M155 commands with one B<base 10> arg
> M155 A99  ; 0x63 Target slave address
> M155 B77  ; M
> M155 B97  ; a
> M155 B114 ; r
> M155 B108 ; l
> M155 B105 ; i
> M155 B110 ; n
> M155 S1   ; Send the current buffer
> ```

**Comment by jbrazio** [comment]
Scott, that's the example from the `Configuration_adv.h`.

**Comment by pankajbadatia** [comment]
Does the ramp accept address in hex or decimal ??

**Comment by pankajbadatia** [comment]
/\* Start and end of packet markers These are 
start of packet SOP 
 and end of packet EOP 
of different microprocessor which i am using*/

#define PACKET_SOP      (0x01u)
#define PACKET_EOP      (0x17u)

/\*  any one can be used Commands set */
#define CMD_SET_OFF     (0u)
#define CMD_SET_RED     (1u)
#define CMD_SET_GREEN   (2u)
#define CMD_SET_BLUE    (3u)

Then which commands should i send

**Comment by thinkyhead** [comment]
> Scott, that's the example from the Configuration_adv.h.

And it's wrong, alas.

**Comment by thinkyhead** [comment]
> Does the ramp accept address in hex or decimal?

The `M155` feature needs the address (`A`) to be specified in decimal — only digits from 0-9 are acceptable in GCode parameters.

**Comment by thinkyhead** [comment]
> Then which commands should i send ?

I'm just guessing here, but it looks like you have the right idea…

``` gcode
M155 A8  ; slave addr
M155 B1  ; PACKET_SOP
M155 B0  ; all off first
M155 B1  ; red
M155 B2  ; +green = yellow
M155 B23 ; PACKET_EOP
M155 S1  ; <send>
```
