### ISSUE TITLE
Feature Request - Info screen icons & babystepping default

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#4083]
A few ideas
1) It would be great if the info screen had a simple icon or way to indicate that mesh leveling was enabled.

2) also when on the idle info screen, if you could set the rotary encoder by default to adjust babystepping Z instead of adjusting speed by default. (be able to set the default function of the rotary)

**Comment by Roxy-3D** [comment]
> also when on the idle info screen, if you could set the rotary encoder by default to adjust babystepping Z instead of adjusting speed by default. (be able to set the default function of the rotary)

Its not merged into RCBugFix...  But it is just a few lines of code and it has been tested fully.   A double click of the Encoder Wheel while at the status screen drops you into Z-BabyStepping.   I use it every print.

**Comment by boelle** [comment]
this one should be added to milestone 1.1.1 even if its just for the icon idea

**Comment by thinkyhead** [comment]
1. An option for that has been added
2. We now have an option to double-tap (or hold) to go to babystepping

(I note that item 2 currently has a bug where it may go to babystepping instead of the info screen after a print, or after a long time in sub-menus. Should have that fixed soon.)
