### ISSUE TITLE
Compilation errors in gcode_M48()

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#4113]
With newest RCBugFix, if you enable the `Z_MIN_PROBE_REPEATABILITY_TEST` when `AUTO_BED_LEVELING_FEATURE` is disabled,
you can see that many compilation errors occur one after another.

I tried to fix but gave up because my limited knowledge of Marlin.
A wreck of trying to fix: https://github.com/esenapaj/Marlin/pull/144
This PR fix compilation errors  tentatively, but perhaps this attempting is wrong.

**Comment by thinkyhead** [comment]
See if the code in #4021 manages to do everything you were looking for.
