### ISSUE TITLE
Using Z_SAFE_HOMING does not compile in RCBugFix

### ISSUE THREAD

**Issue by Alex9779** [MarlinFirmware/Marlin#4121]
Current RCBugFix does not compile again if you use Z_SAFE_HOMING because it needs XY_TRAVEL_SPEED which is embedded into AUTO_BED_LEVELING_FEATURE see line 2984 in Marlin_main.cpp

**Comment by thinkyhead** [comment]
Aha, good catch. We don't have a Travis test for `Z_SAFE_HOMING` by itself yet, and I've been lazy, letting Travis do almost all of the compile-testing. I have a patch for this coming shortly.
