### ISSUE TITLE
LCD BTN not work well. VIKI 2.

### ISSUE THREAD

**Issue by fbarcenas** [MarlinFirmware/Marlin#4127]
Some weeks i don't update with the last rcbugfix. Today i do and what is my surprise than the button of the LCD when i press the beeper always sound BUT not go inside the menus... some times work, another times not... is really desperate.

Some idea?

**Comment by fbarcenas** [comment]
If i change:

``` cpp
#define BEEPER_PIN 61
```

to

``` cpp
//#define BEEPER_PIN 61
```

all works!!!

problem with the BEEPER?

**Comment by jbrazio** [comment]
Maybe, what is your setting for `#define SPEAKER` ?

**Comment by fbarcenas** [comment]
is:

``` cpp
//#define SPEAKER
```

**Comment by thinkyhead** [comment]
@fbarcenas What kind of LCD? Does enabling `SPEAKER` allow you to play musical tones?

@jbrazio Sounds like a crappy debouncer. Previously the delay in the `beep()` function helped ensure that "flaky" buttons wouldn't have this problem. (Which they all are on these units - the on/off state "flickers" when you press them.) To address this, we need to either put the delay back into `lcd_quick_feedback` or make a more reliable debouncer.

@fbarcenas Try this…

``` diff
  void lcd_quick_feedback() {
    lcdDrawUpdate = LCDVIEW_CLEAR_CALL_REDRAW;
    next_button_update_ms = millis() + 500;

    #if ENABLED(LCD_USE_I2C_BUZZER)
      lcd.buzz(LCD_FEEDBACK_FREQUENCY_DURATION_MS, LCD_FEEDBACK_FREQUENCY_HZ);
    #elif PIN_EXISTS(BEEPER)
      buzzer.tone(LCD_FEEDBACK_FREQUENCY_DURATION_MS, LCD_FEEDBACK_FREQUENCY_HZ);
-   #else
-     delay(LCD_FEEDBACK_FREQUENCY_DURATION_MS);
    #endif
+   delay(LCD_FEEDBACK_FREQUENCY_DURATION_MS);
  }
```

**Comment by fbarcenas** [comment]
i use VIKI 2

Yes i can play musical tones.

**Comment by thinkyhead** [comment]
> Yes i can play musical tones.

Uncomment `#define SPEAKER` for best results. I believe that if you insert the suggested delay in `lcd_quick_feedback` the button will be more reliable, and the click sound will work.

**Comment by jbrazio** [comment]
@fbarcenas can we close this ticket, is your problem solved ?

**Comment by boelle** [comment]
i think this one can be closed... it should not take 10 days to respond
