### ISSUE TITLE
How can I apply a new serial

### ISSUE THREAD

**Issue by youngyhw** [MarlinFirmware/Marlin#4135]

**Comment by Roxy-3D** [comment]
Your best chance might be to provide some details about what you need and the problems you are seeing.

**Comment by youngyhw** [comment]
I want to replace LCD panel with touch screen which communicates with main board by serial2, and, I don't want this modification to affect other module. Have any better idea?
Thanks.

**Comment by jbrazio** [comment]
This is not trivial as it requires the definition of some kind of additional serial protocol for the LCD-Marlin interface. On top of that we would need to assess how many users would benefit from this for its inclusion on the Marlin main source tree.
