### ISSUE TITLE
MSG_SD_ERR_READ is undefined in our language files

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#4155]
`#if ENABLED(SDSUPPORT)` turns on code in Marlin_main.cpp that says:

``` cpp
else if (n == -1) {
 SERIAL_ERROR_START;
 SERIAL_ECHOLNPGM(MSG_SD_ERR_READ);
}
```

Unfortunately...   There is no text associated with this #define.   I'm guessing we need the Language Team to help us get an appropriate message here.

**Comment by thinkyhead** [comment]
In `language.h`…

``` cpp
#define MSG_SD_ERR_READ                     "SD read error"
```

This is not translatable text. Errors to serial need to be in English only.

**Comment by Roxy-3D** [comment]
Strange!  My Windows Grep program should have found that!   It only found it in Marlin_main.cpp????

Nope!  It really isn't there!   At least, I can't find it yet.

I only see a 
#define MSG_SD_ERR_WRITE_TO_FILE message

I'll keep looking...  But that is from downloading the latest RCBugFix archive.

**Comment by thinkyhead** [comment]
https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/language.h#L174
