### ISSUE TITLE
Unable to flash my Melzi

### ISSUE THREAD

**Issue by nkuck** [MarlinFirmware/Marlin#4178]
```
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x66
```

Get this message regardless of what I try.
Zonestar Prusa i3 Melzi board ATMega 1284P.
Anyone solved this? Thanks.

**Comment by jbrazio** [comment]
That error happens when the Arduino IDE cannot communicate with the board.
Does your board have a reset button ? Can you try to hit the reset button right after the compilation finishes and the IDE fires the programmer ? (You should enable verbose compilation and upload from the IDE options)

**Comment by nkuck** [comment]
I've tried that but probably not too accurately. Will try again. Thanks for the reply.

**Comment by nkuck** [comment]
What do you mean from the IDE options?

**Comment by jbrazio** [comment]
See the `Show verbose during` checkboxes ? Check both of them.

![screenshot from 2016-07-01 01-47-43](https://cloud.githubusercontent.com/assets/264365/16508726/f5a00006-3f2d-11e6-8e51-f964fdc22cb9.png)

**Comment by nkuck** [comment]
Tried several times with no successes. More thoughts? Thanks for any ideas. I have been at this for weeks.

**Comment by KevMags** [comment]
That happens to me every time that I use a USB cable other than the one that came with my Arduino or Arduino based boards (blue/purple short cord, shielded).  Try another USB cable.

**Comment by nkuck** [comment]
Thanks very much for the suggestion. I have tried a number of USB cables, including the short blue ones that come with the Arduino boards, with no luck. I am still able to load and print files to the printer, just not able to upload a new firmware. Baffled for several weeks. The board is a Merlin on a Zonestar 3D printer (Prusa i3).

**Comment by jbrazio** [comment]
I will make question, are you **really** sure you have the right COM port selected ?

Did you use an ICSP programmer with board before ?

**Comment by jbrazio** [comment]
Or do you have the correct board selected on the IDE ?

**Comment by Blue-Marlin** [comment]
Or do you have an other connection open to the board? A host?

**Comment by nkuck** [comment]
Yes, correct com port.The unit came preloaded with the bootloader and repetier 0.91 firmware.I am trying to upload a current Marlin firmware to the board.I have not tried this before, but I can run files to the printer successfully.

**Comment by nkuck** [comment]
I have selected the Sanduino board, as required.

**Comment by nkuck** [comment]
No other connections (that I know of) open.

**Comment by thinkyhead** [comment]
Check out this thread, starting here: https://github.com/mtu-most/franklin/issues/5#issuecomment-189793398. Maybe there's some guidance that will help.

**Comment by jbrazio** [comment]
As this issue is not directly related with Marlin but with the Arduino toolkit and due to it's current inactivity I will close it.

**Comment by drones-squad** [comment]
hello all,

 please reopen this since I also have this issues . There is no answer and this wasn't solved for future references  so why close ... ? 

greets

**Comment by nkuck** [comment]
I had to reflash the bootloader, and I think that that is what allowed me then to load the firmware.

**Comment by drones-squad** [comment]
with what did you do it and how? Can it work with a arduino nano usb ?

greets

**Comment by nkuck** [comment]
I used an Arduino Uno. Google how to use an Arduino to flash a bootloader and you will get a number of methods.

**Comment by drones-squad** [comment]
yeah but will a nano do ?  The others aren't worth the expense. I can just buy a new melzi board.
The nano is pretty cheap

greets

**Comment by nkuck** [comment]
I haven't tried a nano. Try it and let me know.

**Comment by Bhalddin** [comment]
I know that this is an old post. Just i would like to put the solution i found for this issue. I solve this by changing the baud rate to 19200
