### ISSUE TITLE
LCD display black dots and simbol

### ISSUE THREAD

**Issue by gfunas** [MarlinFirmware/Marlin#4193]
So i tried to update new firmware  to my geeetech prusa i3c.
Got strange sound coming from LCD buzzer, one high frequency and LCD showing this

``` cpp
#define LANGUAGE_INCLUDE GENERATE_LANGUAGE_INCLUDE(en)
#define DISPLAY_CHARSET_HD44780_JAPAN        // this is the most common hardware
//#define DISPLAY_CHARSET_HD44780_WESTERN
//#define DISPLAY_CHARSET_HD44780_CYRILLIC
```

Tried all three charset. 

``` cpp
#define REPRAP_DISCOUNT_SMART_CONTROLLER
//#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```

![image](https://s31.postimg.org/9xfuh9b2j/IMG_20160703_111905.jpg)

**Comment by thinkyhead** [comment]
Please try [the latest `RCBugFix` version of Marlin](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) and see if it does any better. These settings have changed in the new version, so you will need to update them, and possibly some others as well…

``` cpp
#define LANGUAGE_INCLUDE GENERATE_LANGUAGE_INCLUDE(en)
#define DISPLAY_CHARSET_HD44780_JAPAN        // this is the most common hardware
```

… are now …

``` cpp
#define LCD_LANGUAGE en
#define DISPLAY_CHARSET_HD44780 JAPANESE
```

**Comment by thinkyhead** [comment]
Closed for lack of response.
