### ISSUE TITLE
Raising twice before homing Z after Z_RAISE_PROBE_DEPLOY_STOW change

### ISSUE THREAD

**Issue by token47** [MarlinFirmware/Marlin#4208]
The behaviour of how much (and when) to rise before homing and bed leveling has changed in the last few days (I think it was on the same change as Z_RAISE_PROBE_DEPLOY_STOW was renamed), and I'm not sure it was intentional because it seems worse now (or maybe there's a good reason and I don't see it).

Behaviour before the change: It would raise until minimum Z height, home X and Y, and if that height was enough for deploying the probe it would just deploy, else it would raise a bit more to make clearance for the probe.

Behaviour now: it will raise until minimum Z height, home X and Y, and then raise again the value of Z_RAISE_PROBE_DEPLOY_STOW regardless of the current height being already enough to deploy the probe. So it will always raise twice, which is tedious and slow. I'm tempted to put 0 (zero) on the Z_RAISE_PROBE_DEPLOY_STOW value since the homing height is enough to deploy the probe but I'm not sure about the consequences.

It seems that Z_RAISE_PROBE_DEPLOY_STOW is now relative to the homing minimum height and before it was abolute to zero.

I checked the comments on the configuration file and they still seem to imply old behaviour.

**Comment by AnHardt** [comment]
@thinkyhead 

I don't know if we changed the order here recently. 
A relative to `current_position` move in `deploy_z_probe()` does not make much sense when we set `current_position[axis] = 0;` before.

In homexis()

``` diff
-    // Set the axis position as setup for the move
-    current_position[axis] = 0;
-    sync_plan_position();

    // Homing Z towards the bed? Deploy the Z probe or endstop.
    #if HAS_BED_PROBE
      if (axis == Z_AXIS && axis_home_dir < 0) {
        #if ENABLED(DEBUG_LEVELING_FEATURE)
          if (DEBUGGING(LEVELING)) SERIAL_ECHOPGM("> ");
        #endif
        deploy_z_probe();
      }
    #endif

+    // Set the axis position as setup for the move
+    current_position[axis] = 0;
+    sync_plan_position();

   // Set a flag for Z motor locking
    #if ENABLED(Z_DUAL_ENDSTOPS)
      if (axis == Z_AXIS) stepper.set_homing_flag(true);
    #endif

    // Move towards the endstop until an endstop is triggered
    destination[axis] = 1.5 * max_length(axis) * axis_home_dir;
    feedrate = homing_feedrate[axis];
    line_to_destination();
    stepper.synchronize();
```

**Comment by lrpirlet** [comment]
@@AnHardt https://github.com/AnHardt , do we really need to set the position to ZERO at all ??? I was to test, when I have time, if the suppression of those lines was ok… 

Even if X, Y or Z axis is at  max_length(axis) we move it by 150% of that max_length toward the end-stop, so it should end up to the end-stop anyway… I was looking for the possible side effects (and had find none yet , but I may be wrong cause I have not tested it)

**Comment by token47** [comment]
Here is my configuration. I cleaned it up to leave only the parts I find relevant to this matter. If I missed anything please ask.

The config before the issue is RC-BugFix from 2016-06-09 11:10pm. The config after the issue is RC-BugFix from 2016-07-02 4:05pm.

Before:

``` diff
-#define Z_RAISE_BEFORE_PROBING 15   // Raise before probe deploy (e.g., the first probe).
-#define Z_RAISE_AFTER_PROBING 15    // Raise before probe stow (e.g., the last probe).
+#define Z_RAISE_BEFORE_PROBING 10   // Raise before probe deploy (e.g., the first probe).
+#define Z_RAISE_AFTER_PROBING 10    // Raise before probe stow (e.g., the last probe).

-//#define MIN_Z_HEIGHT_FOR_HOMING 4 // (in mm) Minimal z height before homing (G28) for Z clearance above the bed, clamps, ...
+#define MIN_Z_HEIGHT_FOR_HOMING 15 // (in mm) Minimal z height before homing (G28) for Z clearance above the bed, clamps, ...

-//#define AUTO_BED_LEVELING_FEATURE // Delete the comment to enable (remove // at the start of the line)
+#define AUTO_BED_LEVELING_FEATURE // Delete the comment to enable (remove // at the start of the line)

-  #define X_PROBE_OFFSET_FROM_EXTRUDER 10  // X offset: -left  +right  [of the nozzle]
-  #define Y_PROBE_OFFSET_FROM_EXTRUDER 10  // Y offset: -front +behind [the nozzle]
-  #define Z_PROBE_OFFSET_FROM_EXTRUDER 0   // Z offset: -below +above  [the nozzle]
+  #define X_PROBE_OFFSET_FROM_EXTRUDER +39      // X offset: -left  +right  [of the nozzle]
+  #define Y_PROBE_OFFSET_FROM_EXTRUDER +20      // Y offset: -front +behind [the nozzle]
+  #define Z_PROBE_OFFSET_FROM_EXTRUDER -5.20    // Z offset: -below +above  [the nozzle]

-  #define XY_TRAVEL_SPEED 8000         // X and Y axis travel speed between probes, in mm/min.
+  #define XY_TRAVEL_SPEED 10000 //8000         // X and Y axis travel speed between probes, in mm/min.

-  #define Z_RAISE_BETWEEN_PROBINGS 5  // How much the Z axis will be raised when traveling from between next probing points.
+  #define Z_RAISE_BETWEEN_PROBINGS 10  // How much the Z axis will be raised when traveling from between next probing points.

-  //#define FIX_MOUNTED_PROBE
+  #define FIX_MOUNTED_PROBE

-//#define Z_SAFE_HOMING
+#define Z_SAFE_HOMING


-//#define Z_DUAL_STEPPER_DRIVERS
+#define Z_DUAL_STEPPER_DRIVERS

-//#define QUICK_HOME  //if this is defined, if both x and y are to be homed, a diagonal move will be performed initially.
+#define QUICK_HOME  //if this is defined, if both x and y are to be homed, a diagonal move will be performed initially.
```

After:

``` diff
-//#define Z_ENDSTOP_SERVO_NR 0
-//#define Z_SERVO_ANGLES {70,0} // Z Servo Deploy and Stow angles
+#define Z_ENDSTOP_SERVO_NR 0
+#define Z_SERVO_ANGLES {100,65} // Z Servo Deploy and Stow angles

-#define X_PROBE_OFFSET_FROM_EXTRUDER 10  // X offset: -left  +right  [of the nozzle]
-#define Y_PROBE_OFFSET_FROM_EXTRUDER 10  // Y offset: -front +behind [the nozzle]
-#define Z_PROBE_OFFSET_FROM_EXTRUDER 0   // Z offset: -below +above  [the nozzle]
+#define X_PROBE_OFFSET_FROM_EXTRUDER +43 // X offset: -left  +right  [of the nozzle]
+#define Y_PROBE_OFFSET_FROM_EXTRUDER +30 // Y offset: -front +behind [the nozzle]
+#define Z_PROBE_OFFSET_FROM_EXTRUDER -1.00 // Z offset: -below +above  [the nozzle]

-#define XY_PROBE_SPEED 8000
+#define XY_PROBE_SPEED 10000

-//#define Z_MIN_PROBE_REPEATABILITY_TEST
+#define Z_MIN_PROBE_REPEATABILITY_TEST

-#define Z_RAISE_PROBE_DEPLOY_STOW 15 // Raise to make room for the probe to deploy / stow
+#define Z_RAISE_PROBE_DEPLOY_STOW 5 // Raise to make room for the probe to deploy / stow
 #define Z_RAISE_BETWEEN_PROBINGS 5  // Raise between probing points.

-//#define MIN_Z_HEIGHT_FOR_HOMING 4 // (in mm) Minimal z height before homing (G28) for Z clearance above the bed, clamps, ...
+#define MIN_Z_HEIGHT_FOR_HOMING 10 // (in mm) Minimal z height before homing (G28) for Z clearance above the bed, clamps, ...

-//#define AUTO_BED_LEVELING_FEATURE // Delete the comment to enable (remove // at the start of the line)
+#define AUTO_BED_LEVELING_FEATURE // Delete the comment to enable (remove // at the start of the line)

-//#define Z_SAFE_HOMING
+#define Z_SAFE_HOMING

-//#define NUM_SERVOS 3 // Servo index starts with 0 for M280 command
+#define NUM_SERVOS 1 // Servo index starts with 0 for M280 command

-//#define DEACTIVATE_SERVOS_AFTER_MOVE
+#define DEACTIVATE_SERVOS_AFTER_MOVE

-//#define Z_DUAL_STEPPER_DRIVERS
+#define Z_DUAL_STEPPER_DRIVERS

-//#define QUICK_HOME  //if this is defined, if both x and y are to be homed, a diagonal move will be performed initially.
+#define QUICK_HOME  //if this is defined, if both x and y are to be homed, a diagonal move will be performed initially.

```

Note: I changed from a capacitive fixed probe to a servo based optical probe between these versions, but I got the chance to test the new version with the capacitive still and the results were the same. As you can see I had a "Z_RAISE_BEFORE_PROBING" of 10 even when using the capacitive probe and didn't notice it because the MIN_Z_HEIGHT_FOR_HOMING was 15 so it was always higher and this didn't make any difference. At the moment I changed to the newer version, it started to raise 10mm more between homing X+Y and homing Z.

Do you want me to make any specific test or see anything wrong in my config?

**Comment by thinkyhead** [comment]
> do we really need to set the position to ZERO at all?

Probably not. But it will do no harm either. It's always possible that someone could do a `G92 Z9999` before `G28`, which would confuse it. Setting it to zero here will at least work around that kind of possibility.

**Comment by thinkyhead** [comment]
> Do you want me to make any specific test or see anything wrong in my config?

@token47 The patch from above has been merged now. So using the very latest code, try enabling `DEBUG_LEVELING_FEATURE` and then use `M111 S32` to enable extra logging. Then when you execute a `G28` or `G29` we can see what Marlin is doing with your settings.

**Comment by token47** [comment]
Well, I just downloaded the RCBugFix of hald an hour ago, and can't reproduce the problem. It is working as it was before (as expected). Even if I put "10" both on MIN_Z_HEIGHT_FOR_HOMING and Z_RAISE_BEFORE_PROBING, it will only raise once, before homing X/Y. After that, it just deploys the probe (at it seems to already be high enough for that) and homes Z.

If I understand correct, the patch by AnHardt did the trick? (I checked and it is applied). I'm testing more to make sure it's ok.

**Comment by token47** [comment]
Humm, something is strange. I thought it was raising too much, then I measured it. Right now the relevant parameters are:

``` cpp
#define Z_ENDSTOP_SERVO_NR 0
#define Z_SERVO_ANGLES {100,65}
#define X_PROBE_OFFSET_FROM_EXTRUDER +43
#define Y_PROBE_OFFSET_FROM_EXTRUDER +30
#define Z_PROBE_OFFSET_FROM_EXTRUDER -1.00
#define XY_PROBE_SPEED 10000
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define Z_MIN_PROBE_REPEATABILITY_TEST
#define Z_RAISE_PROBE_DEPLOY_STOW 6
#define Z_RAISE_BETWEEN_PROBINGS 4
#define MIN_Z_HEIGHT_FOR_HOMING 6
#define AUTO_BED_LEVELING_FEATURE
#define AUTO_BED_LEVELING_GRID
#define Z_SAFE_HOMING
#define NUM_SERVOS 1
#define DEACTIVATE_SERVOS_AFTER_MOVE
```

On the very first move it raises about 9mm (mesured with a ruler, not exact) on just one go. I would expect it to raise just 6mm.

I'm running with the DEBUG now.

**Comment by token47** [comment]
Where does the debug information go? I enabled it (DEBUG_LEVELING_FEATURE), confirmed I'm compiling the right tree but can't see any change in the output of the communication log. I'm trying a G28 and a G29.

**Comment by thinkyhead** [comment]
You need to use `M111 S32` to enable logging of homing and leveling.

**Comment by token47** [comment]
Hehe, excuse the newbie in me. Now I got it:

```
Marlin 1.1.0-RCBugFix
Last Updated: 2016-04-27 12:00 | Author: (Token, my config)
Compiled: Jul  5 2016
Free Memory: 3256  PlannerBufferBytes: 1232
V24 stored settings retrieved (398 bytes)
Steps per unit:
M92 X80.00 Y80.00 Z4000.00 E620.00
Maximum feedrates (mm/s):
M203 X300.00 Y300.00 Z5.00 E25.00
Maximum Acceleration (mm/s2):
M201 X3000 Y3000 Z100 E10000
Accelerations: P=printing, R=retract and T=travel
M204 P3000.00 R3000.00 T3000.00
Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
M205 S0.00 T0.00 B20000 X15.00 Z0.40 E5.00
Home offset (mm)
M206 X0.00 Y0.00 Z0.00
Material heatup parameters:
M145 S0 H205 B60 F0
M145 S1 H235 B100 F0
PID settings:
M301 P11.14 I0.48 D64.62 C100.00 L20
M304 P356.02 I35.51 D892.46
Filament settings: Disabled
M200 D3.00
M200 D0
Z-Probe Offset (mm):
M851 Z-2.80
Active Extruder: 0
SENT: M111 S32
DEBUG:LEVELING
SENT: G28
>>> gcode_G28
  setup_for_endstop_or_probe_move > current_position: (0.00, 0.00, 0.00)
  do_probe_raise(6.00)
  do_blocking_move_to: (0.00, 0.00, 8.80)
  sync_plan_position > current_position: (0.00, 0.00, 8.80)
  >>> set_axis_is_at_home(0)
    > home_offset[axis]==0.00 > current_position: (0.00, 0.00, 8.80)
  <<< set_axis_is_at_home(0)
  >>> set_axis_is_at_home(1)
    > home_offset[axis]==0.00 > current_position: (0.00, 0.00, 8.80)
  <<< set_axis_is_at_home(1)
  sync_plan_position > current_position: (0.00, 0.00, 8.80)
  > QUICK_HOME 1 > current_position: (0.00, 0.00, 8.80)
  > QUICK_HOME 2 > current_position: (0.00, 0.00, 8.80)
  >>> homeaxis(0)
    sync_plan_position > current_position: (0.00, 0.00, 8.80)
    sync_plan_position > current_position: (0.00, 0.00, 8.80)
    > endstops.enable(false)
    > endstops.enable(true)
    > TRIGGER ENDSTOP > current_position: (0.00, 0.00, 8.80)
    >>> set_axis_is_at_home(0)
      > home_offset[axis]==0.00 > current_position: (0.00, 0.00, 8.80)
    <<< set_axis_is_at_home(0)
    sync_plan_position > current_position: (0.00, 0.00, 8.80)
    > AFTER set_axis_is_at_home > current_position: (0.00, 0.00, 8.80)
  <<< homeaxis(0)
  > homeX > current_position: (0.00, 0.00, 8.80)
  >>> homeaxis(1)
    sync_plan_position > current_position: (0.00, 0.00, 8.80)
    sync_plan_position > current_position: (0.00, 0.00, 8.80)
    > endstops.enable(false)
    > endstops.enable(true)
    > TRIGGER ENDSTOP > current_position: (0.00, 0.00, 8.80)
    >>> set_axis_is_at_home(1)
      > home_offset[axis]==0.00 > current_position: (0.00, 0.00, 8.80)
    <<< set_axis_is_at_home(1)
    sync_plan_position > current_position: (0.00, 0.00, 8.80)
    > AFTER set_axis_is_at_home > current_position: (0.00, 0.00, 8.80)
  <<< homeaxis(1)
  > homeY > current_position: (0.00, 0.00, 8.80)
  > Z_SAFE_HOMING >>>
    sync_plan_position > current_position: (0.00, 0.00, 8.80)
    > Z_SAFE_HOMING > home_all_axis > current_position: (0.00, 0.00, 8.80)
    > Z_SAFE_HOMING > home_all_axis > destination: (54.00, 67.00, 8.80)
    >>> homeaxis(2)
      > deploy_z_probe > current_position: (54.00, 67.00, 8.80)
      do_probe_raise(6.00)
      sync_plan_position > current_position: (54.00, 67.00, 0.00)
      sync_plan_position > current_position: (54.00, 67.00, 0.00)
      > endstops.enable(false)
      > endstops.enable(true)
      > TRIGGER ENDSTOP > current_position: (54.00, 67.00, 0.00)
      >>> set_axis_is_at_home(2)
        > zprobe_zoffset==-2.80
        > home_offset[axis]==0.00 > current_position: (54.00, 67.00, 2.80)
      <<< set_axis_is_at_home(2)
      sync_plan_position > current_position: (54.00, 67.00, 2.80)
      > AFTER set_axis_is_at_home > current_position: (54.00, 67.00, 2.80)
      > stow_z_probe > current_position: (54.00, 67.00, 2.80)
      do_probe_raise(6.00)
      do_blocking_move_to: (54.00, 67.00, 8.80)
    <<< homeaxis(2)
  <<< Z_SAFE_HOMING
  > (home_all_axis || homeZ) > final > current_position: (54.00, 67.00, 8.80)
  sync_plan_position > current_position: (54.00, 67.00, 8.80)
  clean_up_after_endstop_or_probe_move > current_position: (54.00, 67.00, 8.80)
<<< gcode_G28
X:54.00 Y:67.00 Z:8.80 E:0.00 Count X: 4320 Y:5360 Z:35200
```

**Comment by token47** [comment]
Hummm, 2.80 is my Z  Offset (stored on the EEPROM). I guess it's taking it into account.

**Comment by thinkyhead** [comment]
Yes. Your EEPROM (or adjusted) values override your default (`Configuration.h`) values.

**Comment by token47** [comment]
Does it make sense to add it to the value to raise? I think it's right to check if the MIN_Z_HEIGHT_FOR_HOMING is at least => the Z offset or bad things will happen, but if I configure a value greater I'm not expecting it to be increased further because I already considered that offset.

**Comment by thinkyhead** [comment]
It may be that `MIN_Z_HEIGHT_FOR_HOMING` has not been considered in recent changes. I will check to see that it is being applied properly. In general it is not a raise to a certain position. It is a "blind" raise to perform at the start of `G28`.

**Comment by thinkyhead** [comment]
`MIN_Z_HEIGHT_FOR_HOMING` is just the initial raise to do before homing, meant to get the nozzle off the bed and above the bed clips before homing XY. That is its only purpose. (Well, it also doubles as the travel height for Manual Bed Leveling.)

So, you should get an initial raise by `MIN_Z_HEIGHT_FOR_HOMING` as you start `G28`. Then the procedure will home X and Y. Then, before it tries to home Z with a probe, it will raise up as much as needed (`Z_RAISE_PROBE_DEPLOY_STOW`) to deploy the probe.

Thus if `MIN_Z_HEIGHT_FOR_HOMING` is set to `6` and `Z_RAISE_PROBE_DEPLOY_STOW` is `8`, you should get 2mm additional lift after homing XY, before the Z probe deploys.

**Comment by token47** [comment]
Yes, but that is not the case. Both are set to 6. It's only going up bu 8.8 because (and I'm just guessing here) it's adding 2.8 to the value of 6 I provided. And it must be taking this 2.8 from my Z offset (on the EEPROM), but I see no point to add that when the initial value is big enough. It could check and not let it be smaller (sanity check at compile time), but once being equal or greater it could just raise 6 (what I configured). Right?

**Comment by thinkyhead** [comment]
>  It's only going up by 8.8 because (and I'm just guessing here) it's adding 2.8 to the value of 6 I provided.

The use of the `do_probe_raise` in the homing function is incorrect, so that will change. It should raise to `home_offset[Z_AXIS] + 6` and should not include the probe Z offset.

**Comment by token47** [comment]
Thinking about it for a moment, I can see the rationale behind this change. The value to raise before deploying the probe should not be less than Z offset or else the probe will/can crash. But the value of Z offset can be changed on the fly on the LCD display so it's not possible to just make a sanity check on compilation time. And it's clunky to try to display an error later (or worse, not obey a homing command because of some transient value set at runtime, after booting). So it seems easier to just add and do the homing, it will not hurt to raise a little more and things get easier.

If this is the desired behaviour, I guess it's ok, but the documentation should be clarified to state that that value will still be increased by the z offset value, and why.

**Comment by thinkyhead** [comment]
All the Z raises have recently been generalized so they now indicate, more accurately, the clearance to give between the probe and the bed. (Or if the nozzle is lower than the probe, the clearance between the nozzle and the bed.) So `do_probe_raise(10)` makes sure there are 10mm (minimum) between the bed and the lowest part of your extruder/probe assembly.

We could change names (with "clearance" or "height") to reflect the distinction, but "raise" more or less still captures the right concept, since these are moves done (most of the time) from the point where the tip of the probe is touching the bed (or the inductive probe is being triggered).

One sanity-check that might be prudent is to make sure that the raises are never set to zero or to negative values. Every probe that I can think of needs to raise up by some amount before and between probing.
