### ISSUE TITLE
Extruder runs off bed on RCBugFix

### ISSUE THREAD

**Issue by meros** [MarlinFirmware/Marlin#4213]
For RCBugFix, using a0b00d29e3a1f71c536a3821bac448248911cea4 I get normals prints.
But from latest RCBugFix e48502866b23909eca7d21d8f0d4d1e33402135e the extruder runs off the bed shortly after print.

I'm not sure what kind of logging etc would help, but I would be happy to help if I can.

**Comment by thinkyhead** [comment]
That first link makes sense - July 2, 2016. The second link goes to a commit from April 24. Are your links reversed?

What about the current `RCBugFix` [as of today](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix)? How is that behaving?

Are you printing from USB or SD? If printing over USB, what `BAUD` rate are you using?

**Comment by meros** [comment]
Sorry, messed up my git hashes :)

I rebased my config on RCBugFix today (see updated comment). That didn't work. The one I am printing with now, thats working, is the first link (a0b00d2).

**Comment by meros** [comment]
I will try the very latest and come back to you (I thought I did, but I see now there are more commits on top)

**Comment by meros** [comment]
Sorry for late feedback, I retried with latest as of today, and there seem to be no issue anymore

**Comment by jbrazio** [comment]
Great ! Thanks for the feedback.
