### ISSUE TITLE
minimum step/mm value

### ISSUE THREAD

**Issue by solo220** [MarlinFirmware/Marlin#4230]
I am using a Marlin in my printer with the x,y,z setting equal to 50pulse/mm , but i discovered that the fimware generate pulses in multiple of 10 and in my case a layer with 0.1 mm move which is equal to 5 pulses will not generate any movement in the printer .
Is this because of my acceleration/jerk settings or this is how marlin works ?
thank you.

**Comment by thinkyhead** [comment]
@solo220 Welcome to Github!

> i discovered that the firmware generate pulses in multiple of 10

Where did you hear that? It's not the case.

Chances are your Z axis is trying to accelerate too fast. Definitely try lowering the Z jerk and Z acceleration until you get better results.

**Comment by solo220** [comment]
**@thinkyhead**
 thank you for your reply ,
my acceleration settings are low and these are my settings:

```
#define DEFAULT_AXIS_STEPS_PER_UNIT   {52.63,52.63,50,100}  
#define DEFAULT_MAX_FEEDRATE          {300, 300,7, 25}    
#define DEFAULT_MAX_ACCELERATION      {100,100,10,100}  
#define DEFAULT_ACCELERATION          100    
#define DEFAULT_RETRACT_ACCELERATION  50   
#define DEFAULT_TRAVEL_ACCELERATION   200    
#define DEFAULT_XYJERK                10.0    
#define DEFAULT_ZJERK                 1.0    
#define DEFAULT_EJERK                 1.0  

```

the issue is that all my printer motors move normaly but very small details that appear in the gcode file simulation disappear in the print so in order to diagnose the problem i moved my motors using steps of 0.1 mm and the motors moved but after two successive 0.1 mm steps and not at each 0.1 mm step.
then i doubled the step/mm in the settings and the motors started to move at each 0.1mm but not at each 0.01mm step.

**Comment by epatel** [comment]
@solo220 I wonder if this an effect of too little current to the steppers and the micro stepping? Did it work in a previous version and changed to this, or are you setting up a new printer?

**Comment by solo220** [comment]
@epatel 
I will try to change the steppers current and will check the pulses output from the CPU using an oscilloscope .
I noticed that this happens with the z motor which have the driver setting at half step
and the x and y steppers which have the driver settings at 1/8 step.
Printing is normal but some very small details that are shown in the file simulation disappear in the print and in order to diagnose the problem i issued commands like
G1 X50 the X motor will move
G1 X50.1 nothing move ,
G1 X50.2 motor move
G1 X50.3 nothing
G1 X50.4 motor move
.
.
.
and so on.

**Comment by Blue-Marlin** [comment]
Try to lower `dropsegments` in `Configuration_adv.h`

**Comment by solo220** [comment]
@Blue-Marlin 
I think this is where my problem  , thank you
i will test and reply .

**Comment by solo220** [comment]
Isuue **solved** thank you every one. 
dropsegments set to 1 .

**Comment by rszasz** [comment]
This seems to be  MIN_STEPS_PER_SEGMENT  now

**Comment by thinkyhead** [comment]
And it's required.
```cpp
#elif !defined(MIN_STEPS_PER_SEGMENT)
  #error Please replace "const int dropsegments" with "#define MIN_STEPS_PER_SEGMENT"
 (and increase by 1) in Configuration_adv.h.
```
