### ISSUE TITLE
Selecting a file from SD card using a menu option is extremely slow

### ISSUE THREAD

**Issue by lavato** [MarlinFirmware/Marlin#4249]
When printing from SD, scrolling trough file list is extremely slow.
This has been an annoyance for a while so decided to raise it. 

I also believe the Buzzer issue I raised  in a separate issue can be reproduced here.

Any other menu area is quick and responsive.

I am using RAMPS1.4 with the Full Discounted LCD option.

**Comment by Blue-Marlin** [comment]
How many files do you have in the directory?

**Comment by lavato** [comment]
If more than 3-4 files, it start being very slow.

**Comment by lavato** [comment]
...to paint a better picture.
- When I turn the encoder while on the file list section, the selector only updates the screen about 2-4 second later.
- When I click on a file to print, it reacts about 2 seconds later.

**Comment by Blue-Marlin** [comment]
Did you play with 

```
//
// SD CARD: SPI SPEED
//
// Uncomment ONE of the following items to use a slower SPI transfer
// speed. This is usually required if you're getting volume init errors.
//
//#define SPI_SPEED SPI_HALF_SPEED
//#define SPI_SPEED SPI_QUARTER_SPEED
//#define SPI_SPEED SPI_EIGHTH_SPEED
```

?

**Comment by lavato** [comment]
I haven't - I will try tomorrow.

**Comment by Rikrdoga** [comment]
@lavato this happened to me once and after do a low level format to the card the problem was solved

**Comment by lavato** [comment]
@RicardoGA - What did you use to low level format the SD card?

**Comment by Rikrdoga** [comment]
@lavato i used HDD Low Level Format Tool,  here's the link

http://hddguru.com/software/HDD-LLF-Low-Level-Format-Tool/

**Comment by lavato** [comment]
@RicardoGA 

OMG that worked, thank you!!

**Comment by thinkyhead** [comment]
@MarlinFirmware/documentation-maintainers We should mention this potential event in our SD Card section. Which I guess means adding an SD Card Printing section…
