### ISSUE TITLE
"Z probe out. bed" Error whenever I try to home the Z axis. 

### ISSUE THREAD

**Issue by viskio** [MarlinFirmware/Marlin#4255]
I recently recalibrated my Z probe, but when trying to test it I get this error. I cannot home the Z axis. This error displays and it refuses to move. 

This is my config.h file. Pasebin link to keep this post clean. 
http://pastebin.com/2CuzKEx1 

I've seen the same error elsewhere but none of those threads have a working fix. Seem to be a different issue entirely.

**Comment by thinkyhead** [comment]
Please test with the current `RCBugFix` and report whether you still see the error.
(We aren't patching older versions of Marlin.)

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better and reporting this issue but this topic has been open for a long period of time without any further development. Marlin has been under heavy development for the past couple of months and moving to it's last mile to finish the RC cycle and release **Marlin v1.1.0**. We suggest you to try out the latest [RCBugfix](https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip) branch and reopening this issue if required.
