### ISSUE TITLE
Issue dual printing (RCBugFix)

### ISSUE THREAD

**Issue by Alex9779** [MarlinFirmware/Marlin#4267]
In addition to #4266 I have the following issue when trying to dual print.
I am trying to print this file:
[20mm-box.zip](https://github.com/MarlinFirmware/Marlin/files/356804/20mm-box.zip)
Which looks like this:
![dual test](https://cloud.githubusercontent.com/assets/6394581/16726541/ffe3a4dc-475c-11e6-9aed-3ef1465fc103.PNG)
and the result is this:
![datei 11 07 16 11 43 28](https://cloud.githubusercontent.com/assets/6394581/16726605/663a16ee-475d-11e6-9d00-9fab37eb3b88.jpeg)
The first tool prints ok, the second tool does strange moves. Actually there is filament only on two spots but it is on the left side too. This cannot be seens because that additional move extrudes filament and then the head moves the same way back but the extruder is also running reversed with extrusion speed. So on the left side there is no filament in the nozzle anymore to be extruded because it has been "retracted" before too much...

**Comment by thinkyhead** [comment]
I've added more logging for `gcode_T` in #4308 (https://github.com/thinkyhead/Marlin/tree/rc_debug_gcode_t) so please test! Be sure to enable `DEBUG_LEVELING_FEATURE` and use `M111 S32` before testing. Then post the log here. Hopefully it will reveal … something!

**Comment by Alex9779** [comment]
Like I commented in #4266 I will test with latest RCBugFix, if I have issues I will activate debugging and report...

**Comment by Alex9779** [comment]
I did this test again and except the strange things regarding homing with a `T1` I mentioned in #4266 selected this seemed ok now...
