### ISSUE TITLE
E in mm3 always On - RC6

### ISSUE THREAD

**Issue by epoxi** [MarlinFirmware/Marlin#4295]
Hi!

Last modification to my firmware was to add the M600 change filament menu option.
After that, I started to notice that the amount of extruded material was really poor. Looking at the configuration (LCD) found that the extrusion in mm3 was On. I couldn't change it and remains always On.

Attached are my config files.

Marlin 1.1.0-RC6 on Rumba board.

[Marlin-config.zip](https://github.com/MarlinFirmware/Marlin/files/362115/Marlin-config.zip)

Regards.-

**Comment by epoxi** [comment]
Ok. Restoring "failsafe" dafaults and saving them corrected the problem.

Thanks in advance.

**Comment by thinkyhead** [comment]
@epoxi We've patched the EEPROM code to be more robust, so hopefully this won't happen in 1.1.0.
