### ISSUE TITLE
Feature Request: Probe Averaging, extended version of M48.

### ISSUE THREAD

**Issue by GreatGrizzly** [MarlinFirmware/Marlin#4318]
I noticed that Marlin contains a  Z Probe repeatability test. However it looks like this is only used for debugging purposes. Why not use this for all probings?

For any Z homing move, probe the same spot an arbitrary number of times, average the result, and return that as the new 0.

**Comment by Blue-Marlin** [comment]
> Why not use this for all probings?

Because grid-bed-leveling is already the averaging variate of 3-point levelling.

Double touch probing for deltas is in the queue. That should improve the results of a single probe.

**Comment by thinkyhead** [comment]
Continually improving this area, especially at the moment there seems no end of the cleanup we are able to do…

**Comment by jbrazio** [comment]
Closing due being marked as duplicate.
