### ISSUE TITLE
[Feature Request] Use RGB addressable LEDs to indicate print status

### ISSUE THREAD

**Issue by slovenian6474** [MarlinFirmware/Marlin#4324]
I think it'd be neat to use addressable LEDs, wire it into the Ramps/arduino and be able to program machine style status lights.  For example, they'll turn green when the print is done. Red indicating some kind of issue.  Maybe some preset sequences like slow roll through colors while printing or bright white while printing.

**Comment by Roxy-3D** [comment]
You can already do that...    Just wire up the LED's and use M42 to turn them on and off.   You could do much of what you suggested up above by putting the appropriate M42 commands into your Slicer's Start Up and Shut Down GCode.

Incidentally...  I have 3 LED's wired up to help me with debugging some code I'm writing right now.   I'm using them as a high speed way to indicate the status of various pieces of the code.

**Comment by thinkyhead** [comment]
Check out the `TEMP_STAT_LEDS` feature, which (maybe oddly) sets led colors based on whether any of the heaters are at (or targeted) over/under 55 degrees.

**Comment by jbrazio** [comment]
We consider this topic as answered.
Please re-open this issue if still valid or if you still require more support from us.
