### ISSUE TITLE
direct communication over serial ? 

### ISSUE THREAD

**Issue by gbaumgart** [MarlinFirmware/Marlin#4333]
hi, is there a way to speak with Marlin over raw serial ? I'd love to build some software which sends G-Code or similar. 

Sorry for being a little lazy to figure all that out but may be you have some pointer for me. 

I am a little familiar with firmata and Johnny-Five but i guess it is the wrong way.

Thanks a lot.

**Comment by thinkyhead** [comment]
Marlin has an option to use one indexed serial port as its serial I/O. Depending on the controlling device that you want to attach, you may be able to simply use a USB connection, as done with Raspberry Pi and its ilk. But look at #4233 for an option to use a second serial connection directly. And, there may be some way that the serial port attached to the USB port could be wired directly, perhaps via an "RS485" style connection.
