### ISSUE TITLE
Filament Tracking System

### ISSUE THREAD

**Issue by EletroLaix** [MarlinFirmware/Marlin#4352]
One of the new features from introddure oin Marlin could be the Filament Tracking System (FTS) as already done by other firmware (I am attaching some links)

I hope I have given an excellent work inspired :)

http://doku.radds.org/dokumentation/other-electronics/fts-filament-tracking-system/

P.S.

Once I get time I will try to contribute to anc'io qusto beautiful project;)

**Comment by Roxy-3D** [comment]
Is this something your company is making?   It looks like it is something people can use.   And it looks like something that could be open sourced so if somebody actually wanted to build their own unit they could.

If your company makes these....  I'll find a few developers and testers for you to send units.   It would be kind of similar to what we did with the Re-ARM board and used that be a 'reference platform' for 32-bit Marlin.  (#7076   Development continues...  We are not done yet.   But Re-ARM was very valuable in this effort.)

**Comment by comps** [comment]
This seems like a fairly old thread and if you want a filament movement sensor, there are IMHO simpler, cheaper and more DIY-friendly ways, such as using an encoder:
https://www.thing-printer.com/filament-sensor-3d-printer-replicape/ (April 2016)

I have to admit, though, I'm not sure what the life expectancy of a cheap rotary encoder is.
