### ISSUE TITLE
Assembler output helper script

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#4375]
Here's a handy script I wrote to do a quick dump of the assembler code from Marlin. Adapt for your system. If we come up with a "universal" script that works on Linux and Windows, we might include it as an additional helper.

``` bash
#!/usr/bin/env bash
#
# marlindump
#
# Dump and view Marlin's object output in Assembler
#

OBJDUMP=`which avr-objdump`
TEMPFIND="/var/folders/*/*/T/*.tmp"
HOME=`echo ~`
DEST="$HOME/Desktop/scratch"
EDITR=subl

MARNAME=Marlin.ino
ELFNAME=$MARNAME.elf
HEXNAME=$MARNAME.hex

MARLIN_ELF=$(find $TEMPFIND -name $ELFNAME)
MARLIN_HEX=$(find $TEMPFIND -name $HEXNAME)

[[ -z $MARLIN_ELF ]] && { echo "`basename $0`: No '$ELFNAME' found." 1>&2 ; exit 1 ; }

SIZE=`stat -f%z "$MARLIN_HEX"`
DATE=`ls -la "$MARLIN_ELF" | awk '{ print $6 " " $7 " " $8 }'`

echo "Dumping build from $DATE ($SIZE)"

mkdir -p "$DEST"

"$OBJDUMP" -S "$MARLIN_ELF" >"$DEST/marlin.a" && $EDITR "$DEST/marlin.a"
```

**Comment by Roxy-3D** [comment]
I'm on a Window's system.  I've never been able to find any temporary files for Marlin when I've looked for them.   It kind of seems like Arduino is deleting all the temporary files.   That might be a good question to ask over on the Arduino forums.

**Comment by jbrazio** [comment]
No it's quite easy do change the folder, if you have arduino in your PATH just do the following:

```
arduino --pref build.path=C:\tmp\arduino
```

Otherwise just chdir into the folder where you have it and run that command from a cmd window.

**Comment by thinkyhead** [comment]
@Roxy-3D For temporary files on Windows, poke through:
`C:\Documents and Settings\<USER>\Local Settings\Temp`.

https://www.arduino.cc/en/Hacking/BuildProcess

**Comment by Blue-Marlin** [comment]
C:\Users\username\AppData\Local\Temp\build*.tmp (win7). AppData is usually hidden.

**Comment by thinkyhead** [comment]
A: and B: are your floppy drives, Windows users. Floppy drives!

**Comment by Blue-Marlin** [comment]
No floppy drives. But reserved letters.

**Comment by jbrazio** [comment]
Don't make fun of it, MacOS just got diagonal window resizing a couple of years ago.. ;-P

**Comment by Blue-Marlin** [comment]
C:\Program Files (x86)\Arduino\hardware\tools\avr\bin\avr-objdump.exe (win7) usually. Can be changed during installation of Arduino.

**Comment by thinkyhead** [comment]
> MacOS just got diagonal window resizing

Resizing from the edges, you mean. It always had resize from the corner. I believe they might have had to wait for a patent to expire, but correct me if I'm wrong.

**Comment by jbrazio** [comment]
> Starting with OS X 10.7, Apple changed its method for resizing windows. In the Classic Mac OS and through the first six releases of OS X, you had to resize windows using the tab at the bottom-right of the window; however, with OS X Lion Apple changed this behavior to give resizing controls along all edges of application and document windows.

> What this means is in most cases, instead of having to move the left and top sides of a window to a desired location and then resize the rest accordingly, you can simply resize from the left, from the top, or any corner of these edges to move your window around.

**Comment by thinkyhead** [comment]
Now… watch our comments disappear!

**Comment by Roxy-3D** [comment]
> Now… watch our comments disappear!

How could our comments disappear?  Very few people have the privilege level to make that happen?

**Comment by thinkyhead** [comment]
(offtopic comments deleted, cheers!)

**Comment by petrzjunior** [comment]
Btw. Git on Windows installs Bash cmd. It was able to run the missingTraslations script (but only from direct input, not from file), but writing something in Windows cmd shouldn't be such problem.
