### ISSUE TITLE
Sanity check and extended documentation for Z_SAFE_HOMING needed

### ISSUE THREAD

**Issue by Alex9779** [MarlinFirmware/Marlin#4392]
We need a sanity check for `Z_SAFE_HOMING` and update comments would help too.
It should be emphasized in the comment that the position is calculated for the probe.
I realised that if you set the position to something the probe cannot reach no movement in any axis happens so compare to the bed leveling position where compilation fails if you set spots the probe cannot reach this should be done for `Z_SAFE_HOMING`too...

**Comment by thinkyhead** [comment]
> We need a sanity check for Z_SAFE_HOMING

Oh yeah. That was totally an oversight. Here it is: #4398

> emphasized in the comment that the position is calculated for the probe

This is not clear enough?

``` cpp
// - Position the Z probe in a defined XY point before Z Homing when homing all axes (G28).
```

**Comment by Alex9779** [comment]
Ok now I need again a probe, I have no problem with that but I remember #4170 where I had to deactivate the probe because it bricked MBL...
