### ISSUE TITLE
RCBugFix: MINTEMP error broken

### ISSUE THREAD

**Issue by Blue-Marlin** [MarlinFirmware/Marlin#4396]
Currently i can disconnect the extruder thermistors without getting an error.

**Comment by thinkyhead** [comment]
Which thermal protection options do you have enabled?

**Comment by jbrazio** [comment]
Thermal `MINTEMP` will not be triggered if [no target setpoint is defined](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/temperature.cpp#L1740).

To trigger just do `M109 S200`on a board without thermistors.

**Comment by thinkyhead** [comment]
I presumed that @Blue-Marlin meant he pulled the thermistor out in the middle of heating.

**Comment by Blue-Marlin** [comment]
The changes for the high temperature thermistors did not reach my awareness.
