### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by checkerz4456** [MarlinFirmware/Marlin#4401]
I am having trouble getting Marlin to compile. The error is saying NO_HEATER_0_PIN defined for this board, even after defining the board in config.h, boards.h. I even went as far as to check the pins.h for the RAMPS_14_EFB I'm using and HEATER_0_PIN is defined. You can look over my entire sketch.
[New Archive1.zip](https://github.com/MarlinFirmware/Marlin/files/380533/New.Archive1.zip)
This is pretty much an exact copy of the whole Marlin firmware plus any of my settings.

**Comment by thinkyhead** [comment]
Your `boards.h` file has a typo breaking compilation. Fix this:

``` diff
- #define MB(board) (MOTHERBOARD==BOARD_43board)
+ #define MB(board) (MOTHERBOARD==BOARD_##board)
```
