### ISSUE TITLE
Error when changing probing points for 3 point leveling

### ISSUE THREAD

**Issue by viskio** [MarlinFirmware/Marlin#4411]
When I leave the points to the default, it says the probe cannot reach that point. That makes sense, so I changed the points to a point that can be reached. When I do this, I get "LOGICAL_X_POSITION" passed 2 arguments, but takes just 1"

I can't figure out what this error message is referring to. I've tried multiple combinations of numbers. 

I wound up switching it to grid mode, and it verified fine, but I was hoping to try 3 point. What is causing this error?

**Comment by thinkyhead** [comment]
It's a bug / typo in the code. #4412 should take care of this.

**Comment by viskio** [comment]
Ah ok. I did a quick search, but didn't find it. I'll close this one.
