### ISSUE TITLE
SD_DETECT_PIN goes LOW but then goes HIGH

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#4423]
I'm using the `G3D_PANEL` with 1.1.0-RC7.
- The LCD always says "Card removed" and "No SD card" even when it can read the card
- `M20` works to display the contents of the SD card
- `M23` and `M24` don't do anything when sent from the console
- When printing from SD via the controller, `M23` and `M24` are enqueued, but then nothing happens.

I did some debugging to see what was going on. The `SD_DETECT_PIN` is acting oddly. The bit goes to LOW when the card is inserted or removed but then soon reverts back to HIGH, and wants to stay HIGH.

<details><summary>

Funky `SD_DETECT_PIN` Log</summary>

Startup:

```
SD_DETECT_PIN : 1
SD_DETECT_PIN : 1  IS_SD_INSERTED : 0
New lcd_sd_status=0
SD_DETECT_PIN : 1
SD_DETECT_PIN : 1
. . .
```

Insert Card:

```
SD_DETECT_PIN : 0  IS_SD_INSERTED : 1
New lcd_sd_status=1
echo:SD card ok
SD_DETECT_PIN : 1
SD_DETECT_PIN : 1  IS_SD_INSERTED : 0
New lcd_sd_status=0
SD_DETECT_PIN : 1
SD_DETECT_PIN : 1
. . .
```

```
Remove Card:
SD_DETECT_PIN : 0  IS_SD_INSERTED : 1
New lcd_sd_status=1
echo:SD init fail
SD_DETECT_PIN : 1
SD_DETECT_PIN : 1  IS_SD_INSERTED : 0
New lcd_sd_status=0
SD_DETECT_PIN : 1
SD_DETECT_PIN : 1
. . .
```

</details>
Is this a bug where some other code could be stepping on the `SD_DETECT_PIN` — 49 in my case? Have we seen this before?

Meanwhile…
- Inserting or removing the SD card causes the LCD to blank for longer than usual
- Tones played on the speaker sound worse than in earlier Marlin versions

**Comment by thinkyhead** [comment]
**SOLVED.** If the SD Card is inserted with the tab in the LOCK position, this is the resulting behavior. I can't think of any way to work around it so that we can produce better behavior. So we need to include this as a troubleshooting tip.

**Comment by thinkyhead** [comment]
After experimenting, I decided to come up with a workaround. I noticed that whenever the pin goes from LOW (or, "inserted") back to HIGH (or, "removed") the change occurs less than one second afterward. So if a very small delay is detected, the code will retry card initialization. If it succeeds then the card is considered "detected."

**Comment by Blue-Marlin** [comment]
The hardware designer used the 'card write protected' instead of the 'card present' connector of the socket. The LOW time likely depends on the speed you are pushing in the card.

**Comment by thinkyhead** [comment]
@Blue-Marlin Is this very common practice (or mistake)? … This is a `G3D_PANEL`.

**Comment by Blue-Marlin** [comment]
I don't know.
A short test with my panels does no not show the problem. A bunch of REPRAP_DISCOUNT_SMART_CONTROLLER and REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER clones from different producers.

**Comment by Blue-Marlin** [comment]
May also be a damaged socket, or some conductive dirt shorting the both pins. Don't know the exact layout of the G3D-Panel.

**Comment by thinkyhead** [comment]
It doesn't surprise me if it's using the wrong pin. But I wonder if the other pin might still be connected, so that I can simply change the pin number and get the correct behavior. The "schematic" doesn't offer much hope here…
![image](https://cloud.githubusercontent.com/assets/698003/17173357/3f3bf360-53af-11e6-874d-1bbf8f35c62f.png)

**Comment by Grogyan** [comment]
@thinkyhead if the cause is really down to the latch on the SD card itself, then this should be respected for its designed purpose to not enable writing to the SD card

**Comment by thinkyhead** [comment]
> to not enable writing to the SD card

@Grogyan You can't override that (The controller won't allow you to write when the tab is in the LOCK position.) and that isn't my intent. The issue I'm having is that Marlin is rejecting a write-protected SD card completely with my controller. ("Card removed"… "No SD card") It's not that it won't read from it, because that can be made to work with `M21` (`card.initsd()`). But the SD detection is screwy on my unit with a locked SD card. Most users don't have this issue at all, apparently, because their `SD_DETECT_PIN` is connected to the correct pin on the controller, so they don't see the odd bit-twiddling that I'm seeing. But I'm sure there are more controllers are out there with this error. I've only proposed code to catch the issue and flag it, while still allowing the card to be read. And the solution actually works well for me.

**Comment by jbrazio** [comment]
@thinkyhead have you low level formatted the SD Card ? We usually see this random SD card errors and so far 99.9% of them are solved by low level formatting the card.

**Comment by thinkyhead** [comment]
@jbrazio If it was an issue that could be fixed with low-level formatting, wouldn't I see the same behavior all the time, and not just when the card is write-protected? Also, I don't recall anybody having issues where the `SD_DETECT_PIN` acted bizarrely due to the contents of the card (combined with the position of the write-protect tab). Meanwhile, `M21` works, because it ignores the state of the `SD_DETECT_PIN`. Also, it is clear that no reading of the card occurs before the `SD_DETECT_PIN` changes state, because there isn't time.

**Comment by Blue-Marlin** [comment]
I guess this is ether specific to `G3D_PANEL` or specific to a special series of `G3D_PANEL` or specific to your special display. Depends on, if this is a design error, a charge of different sockets or a soldering error.

**Comment by thinkyhead** [comment]
Is the `G3D_PANEL` a variant of the `Panel_ONE`.

**Comment by Blue-Marlin** [comment]
Sorry. I mend the display type you are talking about. (Corrected that above.) For some reason my fuzzy memory told me, you used to have a PANEL_ONE

**Comment by thinkyhead** [comment]
I now have a RDSC I can test with (thanks @esenapaj!). I will compare to the pinouts on the G3D and see if the flaw is obvious. I'm sure you're right about the wrong pin being connected. I might revive my workaround as an option buried in `Configuration_adv.h` if it turns out they shipped a couple hundred of these things to customers.

**Comment by boelle** [comment]
if this is not a bug.. ie bug invalid why not close it?

@thinkyhead @jbrazio

**Comment by thinkyhead** [comment]
I have a proposed fix, but it's such a niche case that I think it should be one of those "fixer-up" options "buried" in `Configuration_adv.h`. If I decide to make a PR I'll just link back to this.
