### ISSUE TITLE
UBL and Z offset question

### ISSUE THREAD

**Issue by OrbitAVI** [MarlinFirmware/Marlin#4427]
What is the best way to determine the correct z offset with the mesh enabled for a G26 test print?

I am able to build a mesh using the G29 P1 command. My issue is when I go to test print using G26 my hot end is too close to the bed so it fails. Is it a problem with my offset or an issue with the G26 layer height? I simply used the default .2 layer height.

The G26 I issued was G26 H 215 N .8

My printer: i3 kit with alum bed and a prox sensor. Z offset is set with a shim (-1.1). Nozzel is .8.

**Comment by Roxy-3D** [comment]
> The G26 I issued was G26 H 215 N .8

A nozzle size of .8mm is huge!   Let's hope the math is all linear.   If it isn't you may need to scale that number up or down to get the right thing to happen.

But to your question...   I tried to keep my Z-Offset close to zero.  If your nozzle size is really .8mm probably a layer height of .6mm would be closer to 'right'.    So maybe:   G26 L .6 H 215 N .8   would be a good place to start?

If you don't mind pulling down the latest files...   I found (and fixed) a bug with the Nozzle size parameter.   The code was parsing the parameter, but it wasn't entering into the calculations.  And with a .8mm nozzle, you will need the extra filament to get a nice line.  (.8mm literally needs 4x the filament as a .4mm nozzle needs.)

**Comment by OrbitAVI** [comment]
OK I will try out the new code tonight if I can. I run a volcano to get through larger prints faster. Typically I print in layer heights of .2 or .3 without issue and still get the advantage of less perimeter shells and faster solid layers. 

How can you keep your z-offset 0 or do you account for the probe offset in the slicer?

**Comment by Roxy-3D** [comment]
Well...   What I did was set my Z_PROBE_OFFSET_FROM_EXTRUDER in the Configuration.h file so that I'm perfectly calibrated.     (And that does require a M502, M500 pair to load the EEPROM with the value.)

At that point....    The Mesh offers the correct amount of adjustment everywhere the nozzle moves to on the bed (assuming the Mesh is active).   

And in Slic3r, I just tell it to do .2mm layer heights.  It always starts the first layer at .2mm.   So, I have the correct gap automatically.

**Comment by OrbitAVI** [comment]
OK that is the same z offset I am talking about. Sorry I should have said it correctly from the beginning by putting the actual parameter name. I'll try the latest code and double check my Z_PROBE_OFFSET_FROM_EXTRUDER and try the G26 again. Thanks again for your excellent support!

**Comment by Roxy-3D** [comment]
Also, when you get the G26 to do it's thing and work...  We may need to add a parameter for better  control of the 'Retract'.  With a .8mm nozzle, my guess is we will need to retract the filament more to keep it from making lines where we don't want them.   A picture of your validation print will help a lot to figure out how we are going to address this.    It maybe we can just scale up or down the retraction based on the nozzle size.   But my guess is it will be more complicated than that.

**Comment by OrbitAVI** [comment]
I'll surely post a pic once I can get the validation file to print ok. I do use a high retract with this nozzel / bowden setup. I think its a 6MM retract that I've been running.

**Comment by Roxy-3D** [comment]
OK...  And just because I think you are going to need it to get a nice, clean Mesh Validation print...

I've added a 'M' parameter to G26 to set the retraction Multiplier.   (R was already used to 'encourage' some amount of random movement.) If you have problems with Ooooze on the retracted movements, you can start scaling up the amount of retraction until it behaves better.

**Comment by MrExo3D** [comment]
Can the Defaults for `G26` be assigned in the `Configuraton.h`?
(Easier to do this then remember the Gcode Parameters when sending commands)

Being able to change defaults would be handy for
- Hotend Temp
- Filament Diam
- Layer Height
- Bed Temp
- Nozzle Diam
- Ooze
- Prime amount

**Comment by Roxy-3D** [comment]
Yes.   This can be done.   Let me think about how to do it in the 'cleanest' way.     Do you have a G26 printing nicely on the entire bed?

**Comment by Roxy-3D** [comment]
> Being able to change defaults would be handy for

This is done...   I put the values at the very top of the G26 file just because we already have enough clutter in the Configuration.h file.   They are easy to find and change.    You can download it when you care to mess with it.
