### ISSUE TITLE
Micro pauses in Delta X/Y moves

### ISSUE THREAD

**Issue by rogueqd** [MarlinFirmware/Marlin#4460]
The print head does a micro pause at the end of each segment in a delta X/Y move. The pause is short but it makes the printer movement look very jerky and makes infill uneven.
This is using the RCBugFix version.

**Comment by thinkyhead** [comment]
- What kind of board are you using?
- What kind of LCD controller do you have?
- What is your `DELTA_SEGMENTS_PER_SECOND` setting?

**Comment by rogueqd** [comment]
Sorry, forgot to attach config.
`BOARD_RAMPS_13_EFB`
`PANEL_ONE` LCD
`DELTA_SEGMENTS_PER_SECOND` 200
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/391592/Configuration.h.txt)

**Comment by rogueqd** [comment]
Maybe segments is the wrong term. Here's a short video.
https://www.youtube.com/watch?v=QxcED-5MVwA

**Comment by thinkyhead** [comment]
Yeah, on `DELTA` every move is split into very small "segments" to prevent dipping of the effector. This calculation does take some extra CPU. Try lowering `DELTA_SEGMENTS_PER_SECOND` by 20 and re-test. Keep lowering by 20 until the pauses go away. If the pauses don't go away, then we should look closer.

**Comment by rogueqd** [comment]
Lowering the DELTA_SEGMENTS_PER_SECOND didn't have any effect. I went down to 100.
Lowering the F parameter in the G1 commands smoothed out the end of the move. I reduced F down to 4000 (from 8000) and the second half of the move was smooth.
At 2000 I only got one pause at the end of the first segment, then the rest of the move was smooth.

Edit: Tested DELTA_SEGMENTS_PER_SECOND at 20, just to be sure, still no effect. Slowing F had the same effect no matter what DELTA_SEGMENTS_PER_SECOND was set to.

**Comment by thinkyhead** [comment]
You can also try lowering your `DEFAULT_MAX_FEEDRATE`. The default for most deltas is pretty high. 500mm/s (30000mm/m). See if you can find a sweet spot with that setting (if it makes any difference).

The `DEFAULT_MAX_ACCELERATION` might also be a bit high. Try lowering this as well to see if it has any positive effect.

**Comment by rogueqd** [comment]
Ok, so I tried reducing the numbers. I lowered my DEFAULT_MAX_FEEDRATE down to 10 on all axes.
All the acceleration variables down to 0.5 and the jerk variables to 0.2.
I didn't seen any change in the movement speed and the judders were still occurring.

I tried lower the F values in G1 moves, the judders stop at 1300, with slight juddering noticeable at 1400.

Edit: I tried the 1.0.2 firmware. No movement juddering with the default speed & acceleration settings.

**Comment by Blue-Marlin** [comment]
How are these moves initiated? By LCD-panel, g-code via USB, SD-Card? Does it make a difference?

**Comment by rogueqd** [comment]
Both g-code via usb and sd-card. I didn't try via LCD panel.

I don't remember noticing it before issue #4433 was fixed. Not sure if that's relevant.

**Comment by Blue-Marlin** [comment]
Did you try after #4450

**Comment by rogueqd** [comment]
I downloaded the latest RCBugFix just now and it's fixed. Thanks.
