### ISSUE TITLE
Changing Esteps/mm during print job causes print head to raise.

### ISSUE THREAD

**Issue by rogueqd** [MarlinFirmware/Marlin#4461]
Sometimes I change Esteps/mm during a print job because it's a finer adjustment than changing the Flow %.

When I tried it today it caused the print head to raise to about 180mm high. The printer kept printing. The Z height on the LCD displayed as the correct Z height for the print job, but the print head was ~180mm above the print bed.

Kossel Mini printer.
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/391546/Configuration.h.txt)

**Comment by thinkyhead** [comment]
I recently added code to recalculate `stepper.count` and `planner.position` when steps-per-mm changes for any axis. I forgot to account for `DELTA`. Rolling a patch now.

**Comment by thinkyhead** [comment]
I've applied a patch to address this. Would you mind testing the latest `RCBugFix` to make sure it's not still broken?

**Comment by rogueqd** [comment]
Yep, I can confirm it's resolved in the latest RCBugFix.
