### ISSUE TITLE
Feature Request: PID enhancement for filament use

### ISSUE THREAD

**Issue by mjmeans** [MarlinFirmware/Marlin#4479]
Has anyone considered adding a predictive factor into the PID equations to compensate for the variable cooling effect of a variable amount of cold filament entering the hot end?

With hot ends like Volcano, passing from no filament to potentially large amount of filament, it may be useful at maximum throughput for the PID formula to predict the heat loss moments before an increase in filament volume and turn on the heater in anticipate of the loss.

Is this even possible?

**Comment by Blue-Marlin** [comment]
PID_ADD_EXTRUSION_RATE

See also https://github.com/MarlinFirmware/Marlin/issues/2885 and https://github.com/MarlinFirmware/Marlin/pull/4244#issuecomment-231905103 ++

**Comment by mjmeans** [comment]
cool beans!
