### ISSUE TITLE
RC7 , run G29,Servo jitter?why?

### ISSUE THREAD

**Issue by jackshi618** [MarlinFirmware/Marlin#4483]
RC7 , run G29,Servo jitter?why?
RC3，no err!!

**Comment by Blue-Marlin** [comment]
#define DEACTIVATE_SERVOS_AFTER_MOVE ?

**Comment by jackshi618** [comment]
disable!

**Comment by Roxy-3D** [comment]
> #define DEACTIVATE_SERVOS_AFTER_MOVE ?

That is a good thing to try!   However, I can tell you the cheap Tower Pro 9g servo's off of eBay still jitter even with them deactivated.   I've put big capacitors on their power.  I've buffered their control signal (for the case where they are activated.)   

The one thing that helped the most (but did not fix the problem) was to move the control signal to a pin where nothing else on the port is switching.   Somehow, the Fast I/O seems to glitch all of the pins on a port when any of them change state.  

@jackshi618 I don't think this is an RC7 issue.  If you go back to RC3, it will happen there too under the right conditions.

**Comment by thinkyhead** [comment]
Some points to consider towards documentation, no doubt. @MarlinFirmware/documentation-maintainers

**Comment by sarf2k4** [comment]
It is most likely due to high current interference/leak from the motor's wire, wrapping them in an aluminum foil followed by an insulation tape might help eliminating it

**Comment by a0s** [comment]
@jackshi618 Do you have oscilloscope? Interference with motor wire and floating length of impulse due error in firmware should visible difference imho

**Comment by Roxy-3D** [comment]
This Servo from eBay does not seem to jitter.  It is almost exactly the same size and dimensions as the cheap Blue TowerPro Servos.   (I had to re-print with a slightly different shape for it to fit perfectly.)   

So far...   no jitter at all!

http://www.ebay.com/itm/262564045761?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT

**Comment by thinkyhead** [comment]
I'm sure we'll cover this in the Servos section of the documentation.
