### ISSUE TITLE
Machine without any change,RC3 to RC7,Can't move Z axis?

### ISSUE THREAD

**Issue by jackshi618** [MarlinFirmware/Marlin#4484]
why?
return RC3,no problem!

**Comment by Blue-Marlin** [comment]
Too complicated to explain. Try RCBugFix. Likely fixed by #4476.

**Comment by Blue-Marlin** [comment]
Be a bit more verbose. At least the type of machine would help to find a better answer than: "You are wrong - it works for me". Ideally append your Configuration.h for every issue.

**Comment by otvald** [comment]
@jackshi618 
1. What is your setup ? Delta, Cartesian, ?
2. Check endstops to see if triggered (M119)
3. Does G28 do anything? It does not home? (Assume DELTA)
4. No noise or hard-stopping noise from steppers?
5. You did not change anything in config? If not, did you see the changes from RC3 to RC7 in git? Did you apply these changes?

**Comment by jackshi618** [comment]
CoreXY，Send G28，Z motor vibration.

**Comment by thinkyhead** [comment]
@jackshi618 Have you tried adjusting your Z max speed, Z homing speed, Z acceleration, Z jerk…?

**Comment by boelle** [comment]
since there is not much response in general and not very usefull feedback maybe close this one?
