### ISSUE TITLE
too few arguments to function 'void _lcd_move_e(int8_t)'

### ISSUE THREAD

**Issue by fabtopia** [MarlinFirmware/Marlin#4495]
With the following settings in configuration.h

``` cpp
// This defines the number of extruders
// :[1,2,3,4]
#define EXTRUDERS 2

// For Cyclops or any "multi-extruder" that shares a single nozzle.
#define SINGLENOZZLE

I get an error "too few arguments to function 'void _lcd_move_e(int8_t)'"

changing it to 
// This defines the number of extruders
// :[1,2,3,4]
#define EXTRUDERS 1

// For Cyclops or any "multi-extruder" that shares a single nozzle.
//#define SINGLENOZZLE
```

There is no problem. But then i can't use my cyclops...

**Comment by ghost** [comment]
Probably PR #4491 (Use a default argument in _lcd_move_e) will fix it.

**Comment by lavato** [comment]
> Probably PR #4491 (Use a default argument in _lcd_move_e) will fix it.

for me, it did not.

**Comment by fabtopia** [comment]
After the last RCBugFix with #4491 there is at the repaire menu the move "extruder," "extruder 1" and "extruder 2". I think there is one to many ("Extruder")

**Comment by ghost** [comment]
> there is at the repaire menu the move "extruder," "extruder 1" and "extruder 2".

It seems that it's intentional.
https://github.com/MarlinFirmware/Marlin/pull/4491#discussion_r73245220

**Comment by fabtopia** [comment]
Oke, I get the idea of @thinkyhead behind it, but then the text "Extruder" could better be changed in "Extruder Actief" or "Extruder Current" of something like that.
