### ISSUE TITLE
remove example configs

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#4525]
is it really necessary to have the example configurations. I assume any company making printers that use marlin will configure a version for themselves.

Since its impossible to have up to date configs for all printers
can we trim some fat?

**Comment by thinkyhead** [comment]
We've discussed this in the past. The example configurations have value, especially as our documentation is very sparse. We have maintainers for many of these configurations. I prefer to keep them, in spite of the extra effort required to keep them all synchronized with new options.

I would rather not leave it up to vendors to keep their own forks up to date. _They never do._
