### ISSUE TITLE
"LCD >Level Bed" after print

### ISSUE THREAD

**Issue by sarf2k4** [MarlinFirmware/Marlin#4529]
This happened twice on my printer and wondering if anyone else got this issues. From what I understand by using the the level bed from the lcd menu g28 will be automatically executed before the g29 (correct me on this one).

After print I tried to use the "lcd level bed" option and I noticed that marlin doesn't do g28 first but just straight go to g29 which will crash the axis and probes at the wrong area. This only happened after printing from sdcard (please confirm this one for me as well).

It seems that a new flag must be added 

``` cpp
if (stepper_disabled)
   g28 then g29
else
   g29
```

I also included my config file here
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/401102/Configuration.txt)

**Comment by thinkyhead** [comment]
We don't do `G28` automatically as part of a `G29`. But we require it before allowing `G29`. If the machine knows where it is then it allows `G29`. Does your machine lose track of its position in the process of printing, or after completing the print?

**Comment by sarf2k4** [comment]
It is after, because i disabled everything after print, stepper and heater.
The axes are also blinking

**Comment by thinkyhead** [comment]
Probably I will submit this change, requiring `G28` if steppers are disabled:

``` diff
   static bool axis_unhomed_error(const bool x, const bool y, const bool z) {
-    const bool xx = x && !axis_homed[X_AXIS],
-               yy = y && !axis_homed[Y_AXIS],
-               zz = z && !axis_homed[Z_AXIS];
+    const bool xx = x && !axis_known_position[X_AXIS],
+               yy = y && !axis_known_position[Y_AXIS],
+               zz = z && !axis_known_position[Z_AXIS];
```

**Comment by sarf2k4** [comment]
I am sorry i didnt report anything about this, the level bed were good to
begin with, it was just mispositioned head and the level bed were okay. But
i kinda wonder is it normal to have those axis still blinking indicating it
were never homed in the lcd panel?
Considering that the last known position of marlin after stepper disabled,
the axis might accidentally moved by user and straight go for level bed
which might gonna crash the axis to either sides without proper g28 =)

**Comment by thinkyhead** [comment]
The blinking was added as a clear indication that the position is untrusted. Given the potential for user confusion, we might as well require homing any time a stepper has been disabled.
