### ISSUE TITLE
The Language Translations

### ISSUE THREAD

**Issue by yhfudev** [MarlinFirmware/Marlin#4539]
Is it possible to update the language engine?

The code use two libs to handle the low level display driver, the u8g and others (such as Hitachi HD44780). The u8g uses a strange way to handle various languages by re-code the chars. There exists a wrapper that uses a straight way to use the strings by a pre-processed manner (https://github.com/yhfudev/u8glib-fontutf8.git). For example, in file language_cn.h, we can define the value in readable manner:

``` cpp
#define WELCOME_MSG MACHINE_NAME  _U8GT("已备"),
```

instead of

``` cpp
#define WELCOME_MSG "\xa4\xa5\xa6\xa7"
```

So the developer can easily to update the translations without worry about both the 'code' and the fonts.

**Comment by thinkyhead** [comment]
This is a good idea. You will implement this for us?

**Comment by yhfudev** [comment]
I would like to implement it. But before I start work, we need to discuss the details of the current implementation with the developers who finished it. We have to change a lot of files in the source code folder.

**Comment by thinkyhead** [comment]
@yhfudev The great thing about Github is that you can do this work entirely in your own fork, get the implementation ready, work out the bugs. And we only have to start thinking about integration later, after the code has been fully written. In this way you are not restricted to following our current methodologies, we don't have to divert the main project at all while you do your thing, and you will have, at least, a reference implementation in hand. It helps in the process if you make the effort to keep up-to-date in your fork with the latest changes (using `git rebase`). In the end you'll need to do a `git rebase` and patch it up for submission anyway.

**Comment by boelle** [comment]
@yhfudev are you doing this one?

**Comment by thinkyhead** [comment]
@yhfudev We're very much looking forward to seeing how your work progresses. Keep us posted!

**Comment by yhfudev** [comment]
Yes, I'm working on this. Unfortunately, I can't promise to have enough time because of other personal issues(job and visa). But I would like to discuss with whom can involved in this module.

**Comment by yhfudev** [comment]
After looking through the source code, I found we don't need to change much to support both U8G and HD44780 at the same time. We can replace most of the language code with one or two files. The only extra step is to use a script to parse the UTF8 strings from the new language engine and generate the font and codes, which needs be done only when the language file changed.

**Comment by yhfudev** [comment]
Finished HD44780 part, Here's the language definition source:

``` cpp
#ifndef LANGUAGE_JP_H
#define LANGUAGE_JP_H 1

#define MACHINE_NAME _UxGT("3Dプリンター") //_UxGT("3D Printer")

#define WELCOME_MSG                         MACHINE_NAME _UxGT(" レディー.") //MACHINE_NAME _UxGT(" ready.")
#define MSG_SD_INSERTED                     _UxGT("カードガソウニュウサレマシタ") //_UxGT("Card inserted")
#define MSG_SD_REMOVED                      _UxGT("カードガアリマセン") //_UxGT("Card removed")
#define MSG_LCD_ENDSTOPS                    _UxGT("エンドストップ") //_UxGT("Endstops") // Max length 8 characters
#define MSG_MAIN                            _UxGT("メイン") //_UxGT("Main")
#define MSG_AUTOSTART                       _UxGT("ジドウカイシ") //_UxGT("Autostart")

#endif // LANGUAGE_JP_H
```

And the the attached pic is the results.
![tmp-hd44780](https://cloud.githubusercontent.com/assets/4012731/17894528/a5ff664a-6917-11e6-9625-16a049dc4ad1.jpg)

TODO:
- support U8GLIB
- integrate both the HD44780 and U8GLIB module to Marlin

**Comment by yhfudev** [comment]
Finished:
- UTF-8 conversion for HD44780
- UTF-8 conversion for U8GLIB, the conversion tools and source code

TODO:
- integrate both modules to Marlin

I also ordered a Russian HD44780 module, and I'll test it once I receive it.

Here's the result for the Russian language mixed with English showing in a I2C 128x64 graph display:
![tmp-u8glib](https://cloud.githubusercontent.com/assets/4012731/17930597/1ca57ef2-69d5-11e6-909c-f42a327103df.jpg)

And Chinese version:
![tmp-u8glib-cn](https://cloud.githubusercontent.com/assets/4012731/17930837/3a63cd1c-69d6-11e6-8772-b487860a6a1f.jpg)

Finally, the Japanese version:
![tmp-u8glib-jp](https://cloud.githubusercontent.com/assets/4012731/17930849/487079a0-69d6-11e6-9d68-0ffbe53e7aff.jpg)

**Comment by thinkyhead** [comment]
It looks very good. Now we just have to figure out how to integrate the necessary conversion into the workflow. I suppose we can just ask our contributors to run the conversions.

**Comment by yhfudev** [comment]
The new language engine works now!

It's now supports UTF-8 language translation header files, and generate the font data automatically.
So the language maintainer can use unicode to translate their languages and don't need care about
the font if the font contains all of the glyph of their languages.

The HD44780 is also works.

The document(howto) for the new language engine is in the file buildroot/share/fonts/uxggenpages.md.

There's some issues I can't handle:
1. We need a complete unicode font to support all of languages. GNU unifont seems a good candidate, but it's 16x16. And the wenquanyi_9pt.bdf of the WQY project (debian package xfonts-wqy) is a 11 pixels height font, but it has missing glyph (as I mentioned in point 2 below).
2. Some glyph are missing from the default 9pt font (WQY), this cause missing char of words in Greek(pl). (See the example pic below.)
3. It would be better to change the suffix of the language file to reflect the language/country.
For example: jp_kana(Japaneses with kana), zh_cn(Simplified Chinese), zh_tw(Traditional Chinese) etc.
Since all of the language files are UTF-8 encoded, so we don't need the utf8 suffixes now.
4. we now can remove following files:
utf_mapper.h
dogm_font_data_ISO10646_1.h
dogm_font_data_ISO10646_5_Cyrillic.h
dogm_font_data_ISO10646_CN.h
dogm_font_data_ISO10646_Greek.h
dogm_font_data_ISO10646_Kana.h

Here's the results (Chinese):
![g-cn-1](https://cloud.githubusercontent.com/assets/4012731/17992271/e3d66006-6b13-11e6-8e7f-f1db04646e56.png)
![g-cn-2](https://cloud.githubusercontent.com/assets/4012731/17992279/ee616ebc-6b13-11e6-976f-3a563c547f0a.png)
![g-cn-3](https://cloud.githubusercontent.com/assets/4012731/17992282/f29f1e16-6b13-11e6-8062-3231550412c9.png)

Missing char in Greek(pl):
![g-pl-1](https://cloud.githubusercontent.com/assets/4012731/17992565/98f78aa8-6b16-11e6-9a3c-93ea92cbb95d.png)

**Comment by thinkyhead** [comment]
Quite an incredible effort. Thank you for putting in the time. I see you did in fact write up some documentation. Great! With the additional code cleanups, this will be a most welcome addition to the project.
