### ISSUE TITLE
Menu shifts down by one row

### ISSUE THREAD

**Issue by lavato** [MarlinFirmware/Marlin#4540]

**Comment by lavato** [comment]
During a print, I noticed the menu shifted down by one row on my LCD.
I use > REPRAP_DISCOUNT_SMART_CONTROLLER with RCBugFix   3a3984e.

I don't know when it happened but I suspect it occurred after the "filament change" message.
I can also say that the "filament change" message on 2nd or 3rd line was corrupted.

**Comment by boelle** [comment]
So you tested this with RC7??

**Comment by thinkyhead** [comment]
@lavato Still seeing this in the current `RCBugFix`?

**Comment by boelle** [comment]
i think we can close this one as it do seem to have been fixed

it should not take him 3 days to give a yes or no or he will test
