### ISSUE TITLE
Compile error language_de.h

### ISSUE THREAD

**Issue by trnoa** [MarlinFirmware/Marlin#4541]
I set the language to "de" -> when I compile this with arduino 1.6.10 I get the error
In file included from sketch\language.h:241:0, from sketch\stepper.h:49, from sketch\MarlinSerial.cpp:34:

```
language_de.h:232: error: #endif without #if
 #endif // LANGUAGE_DE_H
--------------
exit status 1
#endif without #if
```

I think you should delete the line n° 187 (form language_de.h):

```
186   #define MSG_INFO_PRINT_FILAMENT           "Gesamt Extrudiert"
187 #endif     
188 #else
189   #define MSG_INFO_PRINT_COUNT              "Drucke"
```

**Comment by birkett** [comment]
Should be fixed by #4542
