### ISSUE TITLE
[Feature Request] Auto meassure Z height

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#4557]
I always struggle to get my Z height correct

Given i have defined Z max endstop i would be nice to issue a command that homed Z and then told my how far up the endstop is

**Comment by thinkyhead** [comment]
There's a trick you can currently do, without needing a new feature. After homing Z to Max, use the command `G1 Z2` (or Move Axis on the LCD) to move the nozzle all the way down to the bed, where you want "zero" to be. When the nozzle is where you like, choose "Set Home Offset" from the LCD, or use `M428` from the console. This command will set the current Z height as your Z=0 and offset the position of your Z Max Endstop. You can save the result with `M500`. Next time you do `G28 Z` you will see that your Z position is offset from the `Z_HOME_POS` you set in your Configuration. Note that this works only if you configured your `Z_HOME_POS` (`Z_MAX_POS`) a bit higher than actual, so you can move the nozzle all the way down to the bed.

**Comment by strips** [comment]
This could be combined with this feature: https://github.com/MarlinFirmware/Marlin/issues/4531#issuecomment-238537694
