### ISSUE TITLE
Feature Request: Would like "Z_PROBE_OFFSET_FROM_EXTRUDER" in EEPROM

### ISSUE THREAD

**Issue by funbobby2001** [MarlinFirmware/Marlin#4558]
I see now that I can do it with commands or the LCD. I was thinking it would be in the GUI EEPROM editor, but I suppose that's on Repetier's side.

**Comment by funbobby2001** [comment]
I guess I can do it with commands or the LCD, but I was hoping to see it in EEPROM GUI...
Is that on the Reptier-Host side?

**Comment by thinkyhead** [comment]
``` gcode
M851 Z-1.2
M500
```
