### ISSUE TITLE
Error:Z-Probe failed  move down to retract probe Delta

### ISSUE THREAD

**Issue by Anion-anion** [MarlinFirmware/Marlin#4560]
The problem with retracting Z-probe on Kossel Delta printer.
Deployed well, is the whole table, too, but when you revert, just for the bolt and stops. The display says Error:Z-Probe failed move down to retract the probe.
Apparently triggered z-probe, as the limiter in top.
Tell me , what did I miss?

my configuration here.

Проблема с убиранием Z probe на дельта коссель принтере.
Развертывается хорошо, проходит весь стол тоже, но при убирании, чуть касается болта и останавливается. На дисплее пишет Error:Z-Probe failed  move down to retract probe.
Видимо срабатывает z-probe, как ограничитель во высоте.
Подскажите , что я упустил?
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/405716/Configuration.h.txt)

**Comment by Blue-Marlin** [comment]
Likely yesterday solved by "Make Allen Key Probe stow #4551" (RcBugFix)

**Comment by Anion-anion** [comment]
Blue Marlin, thank you)
Works!

**Comment by boelle** [comment]
he said it works so why no close it? and its a dublicate
