### ISSUE TITLE
Compiler warning after merge #4574

### ISSUE THREAD

**Issue by WheresWaldo** [MarlinFirmware/Marlin#4575]
Downloaded RCBugFix Aug 9 and getting the following warning trying to compile on Arduino 1.6.10

```
> Arduino: 1.6.10 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"
>
> In file included from sketch\ultralcd.cpp:48:0:
>
> sketch\ultralcd_impl_DOGM.h: In function 'void lcd_implementation_status_screen()':
>
> sketch\ultralcd_impl_DOGM.h:387:43: warning: integer overflow in expression [-Woverflow]
>
>     bool has_days = (elapsed.value > 60*60*24);
>                                            ^
>
>
> Sketch uses 117,548 bytes (46%) of program storage space. Maximum is 253,952 bytes.
> Global variables use 4,970 bytes (60%) of dynamic memory, leaving 3,222 bytes for local variables. Maximum is 8,192 bytes.
```

**Comment by WheresWaldo** [comment]
I am not getting this consistently, it appears to compile correctly randomly, will try to investigate possible causes.

**Comment by Roxy-3D** [comment]
I do not like the sound of that!   It should be consistent what ever it does!

**Comment by Blue-Marlin** [comment]
Random? No. But only if a graphical display and SDSUPPORT is on and you are compiling the first time. (If you don't change the source file, or one of its includes it will not be compiled again because the already existing *.o file can be reused. (make))

60*60*24=86400 > 2^16. So a int is to small.

`elapsed.value` is uint32_t so ok.
To expand the right side to a long use

60*60*24 **L**

**Comment by WheresWaldo** [comment]
@Blue-Marlin That appears to be what I am seeing, first compile errors then second compile immediately afterward compiles with no error. I do have LCD and SDSUPPORT enabled. It will still upload to the RAMPS board, and I have never done a print exceeding 22 hours, so I wouldn't have days listed.

**Comment by thinkyhead** [comment]
The "L" has been added and merged.

**Comment by WheresWaldo** [comment]
Does this issue need a test or can I just close it?

**Comment by boelle** [comment]
@thinkyhead ^^ what he just asked

**Comment by boelle** [comment]
upps.... @thinkyhead i forgot the "read 1x extra before you click comment"
