### ISSUE TITLE
Z Probe Homing with Min Switch as Abort

### ISSUE THREAD

**Issue by StevenChristy** [MarlinFirmware/Marlin#4583]
I couldn't find a way to configure Marlin to what I felt was a sensible setup using both an induction probe and a Z min switch. In my case I expected the z min switch to act as a safety mechanism in case of induction probe failure. Right now my Z min switch right near where the nozzle and the plate meet, but I'd rather the min switch only be used as a backup.

**Comment by Roxy-3D** [comment]
You can have both a Z-Probe and a Z-Min End Stop switch.   You need to follow the directions in the Configuration.h file to set that up.   Please find this section in your Configuration.h file:

```

// Enable Z_MIN_PROBE_ENDSTOP to use _both_ a Z Probe and a Z-min-endstop on the same machine.
// With this option the Z_MIN_PROBE_PIN will only be used for probing, never for homing.
//
// *** PLEASE READ ALL INSTRUCTIONS BELOW FOR SAFETY! ***
//
// To continue using the Z-min-endstop for homing, be sure to disable Z_SAFE_HOMING.
// Example: To park the head outside the bed area when homing with G28.
//
// To use a separate Z probe, your board must define a Z_MIN_PROBE_PIN.
//
// For a servo-based Z probe, you must set up servo support below, including
// NUM_SERVOS, Z_ENDSTOP_SERVO_NR and Z_SERVO_ANGLES.
```

**Comment by StevenChristy** [comment]
The main problem with this is that the z-min switch gets used for homing if you use both a min switch and a probe. I want homing to be based on the probe and the z-min switch to be used only as a fail safe. I only had two real choices using the latest RC7 - to use both but the switch will be used when homing (what I don't want) or to use only the probe. I ended up just using the probe for now. I'd really like both a min switch for a safety (stop/abort and lift) and a probe for both homing and leveling.

**Comment by Roxy-3D** [comment]
You can set the Z-Min switch 1 or 2 mm below the bed.   And then wire up the Z-Probe and Z-Min in series (with them both Normally Closed).  If something happens where the Z-Probe doesn't trigger, the Z-Min will trigger before much force is exerted on the Z-Probe.

**Comment by StevenChristy** [comment]
Originally I was just going to use a probe making this a non-issue, but after the first time the extruder crashed into the plate I thought a safety mechanism might be prudent. Specifically this would help reduce damage to expensive build plates if the extruder was hot forcing it to abort and lift on crash. I imagined that it might save the plate from extensive damage (some damage is probably unavoidable). Implementing it in software seemed a bit more reasonable as it would make it simple to lift the z-axis. For now I suppose I can probably make do without it. Thanks for your suggestion though.

**Comment by Roxy-3D** [comment]
Once you get setup and running, I think you will find nozzle crashes don't happen very often.   And personally, if I was that worried about it, I would not want software in the middle of things.   I might wire up some switches that actually cut power to the Z-Stepper motors so they can't step any further down.  In that case, you would need a 'Double Throw' micro switch instead of the normal 'Single Throw' because you need to cut the power to two different phases.   But you get the idea.

**Comment by landodragon141** [comment]
@thinkyhead I think that the auto kill for max z travel in the probing routine should cover this.

**Comment by boelle** [comment]
@StevenChristy this seems more like a question than a feature request so

Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/ 
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
