### ISSUE TITLE
Compile failure when using 3drag / k8200 board

### ISSUE THREAD

**Issue by ntoff** [MarlinFirmware/Marlin#4591]
https://gist.github.com/ntoff/f4ef715413ce93ab9984990543ff64e5

pins_3drag appears to need #undef FAN1_PIN added somewhere, probably around here: https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/pins_3DRAG.h#L55 (tested it and it compiles)

**Comment by thinkyhead** [comment]
It seems to have already been patched.

**Comment by ntoff** [comment]
considering I still get the issue in rcbugfix I don't see how it's been patched unless there's another branch out there?

**Comment by jbrazio** [comment]
RC7 as of today ?

**Comment by ntoff** [comment]
rc whatever as downloaded seconds before I posted that reply to test. both "rc" and "rcbugfix"

**Comment by thinkyhead** [comment]
@ntoff Sorry! I missed the "1" in the pin name. Is it that the 3Drag board has only two power output connectors? The `FAN1_PIN` will be assigned to `RAMPS_D8_PIN` as the second fan, but only if you're using 1 hotend and no bed heater. Then it should be -1. If the 3Drag board has no D8 power connector, then the proper solution, currently, is to `#define RAMPS_D8_PIN -1` before the `#include "pins_RAMPS.h"` line.

**Comment by ntoff** [comment]
3drag \ k8200 only has 1 heat bed, one extruder and one fan pin http://reprap.org/wiki/3Drag_controller 

It uses pins 8, 9 and 10. Why does it assign anything to fan1 when there's a fan"zero" which is just "the fan" which is on pin 8

**Comment by thinkyhead** [comment]
@ntoff I see. So they have D9 as a simple fan connector instead of the usual three terminal connectors. In that case the solution would seem to be…

``` cpp
. . .
#define RAMPS_D8_PIN -1

#include "pins_RAMPS.h"
. . .
```

But the `FAN_PIN` is itself defined as pin 8, so it looks like we need an `EBF` option, where the fan is plugged into the port usually reserved to the bed. I suppose the fuller solution should be:

``` cpp
#define RAMPS_D8_PIN 9
#define RAMPS_D9_PIN 8

#include "pins_RAMPS.h"
. . .
```

…and removing the override of `FAN_PIN`.

I presume this fan pin is still PWM controlled?

**Comment by thinkyhead** [comment]
The changes in #4605 should do the trick.

**Comment by boelle** [comment]
So we can close this one right?
