### ISSUE TITLE
Why does auto bed leveling not double-tap the probe like with homing?

### ISSUE THREAD

**Issue by funbobby2001** [MarlinFirmware/Marlin#4600]

**Comment by zenmetsu** [comment]
// Use double touch for probing
#define PROBE_DOUBLE_TOUCH

Did you uncomment this?

**Comment by funbobby2001** [comment]
Wow, that's weird. I just did a search for "PROBE_DOUBLE_TOUCH" and the only place it shows up is in Marlin_main.cpp. I guess I accidentally deleted that line from the configuration. 

Well that one was easy!

**Comment by thinkyhead** [comment]
> I guess I accidentally deleted

It's a very recent addition.
