### ISSUE TITLE
Home offset not referenced to axis zero

### ISSUE THREAD

**Issue by awigen** [MarlinFirmware/Marlin#4616]
Testing the latest RCBugFix I changed my Y_MIN_POS from 0 to -10. This offset my home position by 10mm. I had to change my home Y offset from -33 to -23. Is that by design? It didn't make sense as I would think the Y limit switch offset would referenced to Y0.

**Comment by thinkyhead** [comment]
Try simply setting your `MANUAL_Y_HOME_POS` to zero instead. Your lower movement limit will still be -10 because of `Y_MIN_POS`, but `G28 Y` will result in Y=0. Don't forget to clear the Y home offset with `M206 Y0`.
