### ISSUE TITLE
Hotend frequency

### ISSUE THREAD

**Issue by KokinSSJ** [MarlinFirmware/Marlin#4617]
Hello,
Could you explain me how can I change hotend frequency in Marlin software?
I can use SOFT_PWM setting but it decreases control resolution and it's effective on hotend and fan.

I would like to change hotend frequency to around 100Hz ? Could you explain me how can I do that?
How can I change Timer2 - only for heater (PB4 or pin 10). I couldn't find settings for heater.
RAMPS use pin 10 for hotend and pin 9 for fan - both operates on Timer2.  But hotend has special software divider, am I right? Where is software divider for heater and how to change freq?

Ramp 1.4 (bed + FAN + hotend ) + arduino MEGA

Thanks for your help.
Best regards
Dominik

**Comment by thinkyhead** [comment]
In Marlin the heaters are always software-PWM driven and as you point out, `SOFT_PWM_SCALE` applies to fans too. So you would have to make a separate PWM handler just for the heaters. With the current implementation you can't go slower than 488.28Hz.

The `SLOW_PWM_HEATERS` option offers a workaround. By default it has a base PWM frequency of 7.62Hz (488.28 Hz / 64). You could combine `SLOW_PWM_HEATERS` with a `SOFT_PWM_SCALE` of 4 (16x) to get ~122Hz. (Of course this negatively affects fan PWM resolution, but increases fan PWM frequency.)

**Comment by KokinSSJ** [comment]
OK,
Maybe, heater PWM is 488.28Hz but on mosfet output I have maybe 20-50Hz - when hotend achieve temperature around I set - diode blinking but it must glow. 
I would like to increase hotend software frequency for hotend.

I need to avoid frequency which is lower than 50Hz - it's related to my power supply and main grid problems when I use so small frequency.

Could you help me with this problem?

Thanks for your help.
Best regards,
Dominik

**Comment by thinkyhead** [comment]
> Could you help me with this problem?

I offer consulting services for a nominal fee.

**Comment by birkett** [comment]
> KokinSSJ commented 14 hours ago
> I need to avoid frequency which is lower than 50Hz - it's related to my power supply and main grid problems when I use so small frequency.

Stick an extra filter capacitor between your power supply positive and negative?

**Comment by KokinSSJ** [comment]
> I offer consulting services for a nominal fee.

Regarding to Polish law it's all correct - because they measure "blinking" during 15minutes - they estimated special parameter of grid.
I noticed that blinking depends on voltage of main grid - when voltage is around 230V (nominal) it is all correct -  no lights blinking. When it drop down to around 215V, lights start blinking. (and it is still correct regarding to Polish law).
I'm one of the farthest person connected to grid, starting from transformer so drops down can happen very often.

This is why I would like to change PWM of heater frequency and maintain frequency out of visible spectrum.

> Stick an extra filter capacitor between your power supply positive and negative?

I didn't try to connect capacitor filter before power supply into ac mains - I thought that power supply filtering loop should handle this - I will test it. I only add some diode and extra capacitor into 12V loop of my power supply and also for hotend loop. Have you some proposal of capacitor? Or I should use some special loop - as LC or RC filter - beacuse resistor or coil must handle current and voltage. What do you think?

Thanks for your help.
Best regards,
Dominik
