### ISSUE TITLE
support for USB on LCD menu

### ISSUE THREAD

**Issue by alan707** [MarlinFirmware/Marlin#4622]
Rigidbot printers have a USB slot instead of a SD Card slot.  I am working on a pull request to replace the strings from the LCD menu that have the word "Card" for "USB".  In other words, the LCD would print "USB Inserted" instead of "Card Inserted"

My question: which branch should I use to make that PR?  Is this something that would be accepted?

**Comment by boelle** [comment]
hmmm

i think it would have to be more "intelligent" ie if the controller has usb port them print USB.. and if the controller have SD then do as now

**Comment by JustAnother1** [comment]
If detection is not possible maybe something more generic better? External memory available - is probably bad and too long though,...

**Comment by alan707** [comment]
My thought was start with something simple that is manually set in the configuration.h file and then work towards more complex things like automatic detection. 

what is the appropriate process to contribute a feature like this? Submit a Pull Request to RC branch?

**Comment by Grogyan** [comment]
You would need significantly more code than what Marlin already has, to be
able to mount and unmount a USB, initiate USB data comms, set the BAUD as
well as the need for a USB host to serial converter on the main board.

Most of this can be done with OctoPrint, and I know that Gina has already
got USB as a future support item.

Handling dynamic USB may be a lttle too much for an 8bit micro.

**Comment by thinkyhead** [comment]
> Rigidbot printers have a USB slot instead of a SD Card slot.

@alan707 All 3D printers have a USB plug. Marlin receives data from USB (serial) and parses it continually. When printing from SD Marlin actively reads from the SD file and parses each line. Marlin doesn't care if the USB plug is connected or disconnected.

Are you saying that Rigidbot connects to something by USB that acts like an SD card, and that the `SD_DETECT_PIN` is attached to the USB port? Because you would need to have something on the other end that acts that way, otherwise USB printing is always initiated from the host, and simply consists of the host sending commands continually.

> Submit a Pull Request to RC branch?

No. Later we will have a `1.2.x-dev` branch, but for the time-being submit all PRs to `RCBugFix`.

**Comment by alan707** [comment]
> Are you saying that Rigidbot connects to something by USB that acts like an SD card, and that the SD_DETECT_PIN is attached to the USB port?

@thinkyhead I am actually referring to the front LCD Panel which has a USB connector so you can plug in a USB stick instead of an SD Card (see picture below).  @Grogyan I've tried it with the latest Marlin RCBugFix and it works great, as it thinks it's a SD Card volume being inserted.

![detail_img_5950_display_large](https://cloud.githubusercontent.com/assets/1726205/17656459/2e750782-626f-11e6-8bdf-515f8200f9ba.jpg)

My simple proposal is to create a conditional statement to replace the word "Card" to "USB".  So if you stick a USB drive into the front LCD panel slot (Type A USB connector), it will read correctly: "USB inserted" instead of "Card inserted".  That's all 😄 

The USB connector that you are referring to is also present in the Rigidbot but it is a Type B connector and I actively use it to send commands over serial.  I've included the standard nomenclature of 3 example USB connectors below to facilitate this conversation.

![image](https://cloud.githubusercontent.com/assets/1726205/17656547/1d943568-6270-11e6-91c5-a5d5d7424ce8.png)

**Comment by thinkyhead** [comment]
Aha, I see! They happen to plug into a USB port, but they are called "Flash Drive" or "USB Stick". So perhaps instead of just "USB" use "USB Drive" or "USB Stick."

**Comment by alan707** [comment]
Yes, exactly!  I think I'll go with "USB Drive".  Will report back with progress.

**Comment by Grogyan** [comment]
@alan707 can you please provide a link to the schematic for the display.

As a flash drive works through the USB protocol, though it can work without it, it isn't advised.
I suspect that there must be at least a USB host device on it, which is then connected via the SPI port back to the main controller.
If this is the case, then I also have an even more serious concerns about whether there is a way to break out the SPI bus to use it for additional tasks (MAX31855 thermocouple for example)

**Comment by thinkyhead** [comment]
Please post a new issue detailing your progress. Link back to this one.

**Comment by marcio-ao** [comment]
This thread is interesting. We would like to implement USB on our printers. How does Rigidbot do it? Have they released their code? What chip do they use?

**Comment by thinkyhead** [comment]
I suspect something like [this](https://shop.clickandbuild.com/cnb/shop/ftdichip?productID=62&op=catalogue-product_info-null).

See https://playground.arduino.cc/Main/UsbMemory for usage
