### ISSUE TITLE
Stop after pause

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#4637]
I stumbled upon a bug using RC6 UBL
not sure if this is in RC7bugfix or not

while i was printing. I paused the job.
and then decided i wanted to stop it.
but selecting stop didnt work if the job was paused.
once i resumed the job i was able to stop it.

**Comment by Roxy-3D** [comment]
Can you give more details?  

Were you printing from an SD-Memory card or from the USB-Serial port?

Did you pause the print from PronterFace?  Or from the LCD Panel ?

**Comment by MrExo3D** [comment]
Print off SD, 
LCD control

**Comment by thinkyhead** [comment]
This was patched in `RCBugFix` nine days ago. See #4610 and #4598.
