### ISSUE TITLE
if I home all axes and M206 Z14.70 X0 Y0 then z axis won´t move downside

### ISSUE THREAD

**Issue by Screy** [MarlinFirmware/Marlin#4640]
environment :
prusa I 3 with Ramps EEB
Marlin 1.1.0-RCBugfix
Servo Z Probe
Pronterface 2014.08.01
LCD Panel with SD-Slot

issue:
hello @ all, thats my first issue

I use Pronterface to try the Marlin Version above.
At first I push the homebotten to home all axis and that works fine.
My Prusa stop at X0 Y0 Z0, also fine.
"At real my Headend is higher then 0 0 0 so i add to the startcode"
For testing I use Pronterface and send 
"M206 Z14.70 X0 Y0" to set the offset mannually. 
My Prusa show "X 0 Y0 Z14.7" and is blinking.

In my older Version (i think it was april) it take the new value as given and was not blinking and I could move it down to 0 0 x. Now it couln´t move down.

I haven´t activated the EEPRON setting.

In Marlin_main stands
- M206 - Set additional homing offset

I think it should work, but it doesn´t do move down from the new Value
"X0 Y0 Z14.70" (the good new´s is, it can move up and down, left and right, just as it where at 0 0 0)

Kind regards
Ben

**Comment by thinkyhead** [comment]
With Marlin 1.1.0 commands like `M206` and `G92` also move the software endstops. If you want to routinely move lower than the bed, you need to reconfigure your movement limits. Specifically, you need to reduce your `Z_MIN_POS` and then (only if you are homing Z to the Z min endstop) set your `MANUAL_Z_HOME_POS` to 0.

In the future we may implement `M211` which allows specifically enabling or disabling software endstops.
