### ISSUE TITLE
Auto leveling only probes the front half of the bed (Delta)

### ISSUE THREAD

**Issue by robingantois** [MarlinFirmware/Marlin#4646]
I have a problem with auto bed leveling. It only probes the front half of the bed. 
Do you have any idea what I'm doing wrong?

**Comment by zenmetsu** [comment]
Is your Configuration.h available anywhere?

Could you post the output of G29 V4 as well so we can see which points are being probed?  I have a suspicion that you are running into the same problem that I had.   I wrote a fix for it which is pending integration into the official codebase.

**Comment by robingantois** [comment]
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/425125/Configuration.txt)

![schermafbeelding 2016-08-18 om 16 17 44](https://cloud.githubusercontent.com/assets/21104578/17777077/6d982ed8-655f-11e6-9e47-1435f1a51845.png)

**Comment by zenmetsu** [comment]
The output shows that the probed points are centered on your build platform, but mainly in the center and nothing past 35mm in either axis is getting probed.

`#define MIN_PROBE_EDGE 50`   I think this defaults to 10.  I think it is preventing points from being probed which are closer together.

```
    #define DELTA_PROBABLE_RADIUS (DELTA_PRINTABLE_RADIUS - 10)
    #define LEFT_PROBE_BED_POSITION -35
    #define RIGHT_PROBE_BED_POSITION 35
    #define FRONT_PROBE_BED_POSITION -35
    #define BACK_PROBE_BED_POSITION 35
```

These are normally set to `-DELTA_PRINTABLE_RADIUS` or `DELTA_PRINTABLE_RADIUS`.  This is why the probed points are being constrained to 35mm radius.

Were these changed for a specific reason?  If not, could you try looking at one of the example configurations for deltas and set the `XXXX_PROBE_BED_POSITION` values and `MIN_PROBE_EDGE` accordingly.

**Comment by robingantois** [comment]
Thank you very much for your help.
if I make the adjustments as you say, he gives the following output:
"?Probe (F)ront position out of range"

**Comment by zenmetsu** [comment]
`#define Y_PROBE_OFFSET_FROM_EXTRUDER 36   // Z probe to nozzle Y offset: -front +behind`

This is why.  Your extruder is 36mm from your nozzle.

Change this...
`#define DELTA_PROBABLE_RADIUS (DELTA_PRINTABLE_RADIUS - 10)`
to
`#define DELTA_PROBABLE_RADIUS (DELTA_PRINTABLE_RADIUS - 36)`

And give it another shot.

**Comment by robingantois** [comment]
the same: "?Probe (F)ront position out of range"

**Comment by zenmetsu** [comment]
So you have this now?

```
  #if ENABLED(AUTO_BED_LEVELING_GRID)

    // set the rectangle in which to probe
    #define DELTA_PROBEABLE_RADIUS (DELTA_PRINTABLE_RADIUS - 36)
    #define LEFT_PROBE_BED_POSITION -(DELTA_PROBEABLE_RADIUS)
    #define RIGHT_PROBE_BED_POSITION DELTA_PROBEABLE_RADIUS
    #define FRONT_PROBE_BED_POSITION -(DELTA_PROBEABLE_RADIUS)
    #define BACK_PROBE_BED_POSITION DELTA_PROBEABLE_RADIUS

    #define MIN_PROBE_EDGE 10 // The Z probe square sides can be no smaller than this.
```

That should work.  Maybe try bumping it to `#define DELTA_PROBEABLE_RADIUS (DELTA_PRINTABLE_RADIUS - 37)`  If your probe's distance from the nozzle is larger than the difference between `DELTA_PROBEABLE_RADIUS` and `DELTA_PRINTABLE_RADIUS` it tends to generate that message.  In your case, your probe has no X offset, so it should just be equal to your Y offset in the `DELTA_PROBEABLE_RADIUS` calculation.  If this doesn't work by bumping it up to 37, I'll have to let one of the devs jump in.

I have a bit of a disagreement on how this part of the probing works because a person could have a small printing radius (due to a small heated bed), but an absolutely monstrous range of motion if they have a large delta.  Safe effector travel radius might be 150mm, but a small bed limits printing radius to 80mm.  In this case, an additional 30mm is removed from your probeable radius if your probe is 30mm offset from the nozzle, which means that although your effector could safely move to allow the probe to hit every point on your bed (80mm bed radius + 30mm offset probe = 110mm which is lower than the safe 150mm), the code will end up limiting you to a small 50mm radius of probe points.

**Comment by robingantois** [comment]
hmmm, Still the same!

**Comment by robingantois** [comment]
When I use :

```
#define DELTA_PROBABLE_RADIUS (DELTA_PRINTABLE_RADIUS - 10)
#define LEFT_PROBE_BED_POSITION -35
#define RIGHT_PROBE_BED_POSITION 35
#define FRONT_PROBE_BED_POSITION -35
#define BACK_PROBE_BED_POSITION 35
```

and i set:

#define Y_PROBE_OFFSET_FROM_EXTRUDER 0 // Z probe to nozzle Y offset: -front +behind

It is probing the bed completely!

???

**Comment by thinkyhead** [comment]
> It is probing the bed completely!

That tends to work for all, but if your probe is 36mm to one side of the nozzle, then I expect your effector is getting very close to the towers on some of those probing moves. Also, the probed points will all be off by 36mm. In the long run I'd like to add better logic to handle probe offsets on Delta, but in the meantime…

If your probe is truly 36mm directly behind the nozzle, then it simply can't reach the very front of the bed without really straining the mechanics. So my recommendation is to use something like this:

``` cpp
#define DELTA_PROBEABLE_RADIUS (DELTA_PRINTABLE_RADIUS - 10)
#define LEFT_PROBE_BED_POSITION -(DELTA_PROBEABLE_RADIUS)
#define RIGHT_PROBE_BED_POSITION DELTA_PROBEABLE_RADIUS
#define FRONT_PROBE_BED_POSITION (-(DELTA_PROBEABLE_RADIUS) + 36)
#define BACK_PROBE_BED_POSITION DELTA_PROBEABLE_RADIUS
```

**Comment by Roxy-3D** [comment]
> In the long run I'd like to add better logic to handle probe offsets on Delta, but in the meantime…

Soon...  I'll be bring up UBL on a Delta.   It will handle this nicely....

**Comment by zenmetsu** [comment]
Pardon my glaring ignorance.  UBL? Uber Bed Leveling? lol

**Comment by Roxy-3D** [comment]
Unified Bed Leveling.  It will have the Best of each all available at the same time.  I don't have the Grid Based going yet.   But that is very straight forward to do.   It was designed to handle the Deltas that are difficult to calibrate well.
