### ISSUE TITLE
Defining Second Extruder as primary extruder causes hang

### ISSUE THREAD

**Issue by CampbellFabrications** [MarlinFirmware/Marlin#4659]
Machine: Joysmaker R2 (UMO Clone)
Firmware version: Unknown,
Readme.md shows the following on lines 4-5:
"
## Marlin 1.1 Release Candidate is now available

19 September 2015
"
I was trying to set my second extruder as the current extruder by editing the start gcode:
"
T1
M109 S215.0
"
Running it via SD causes a print hang and neither the first nor second extruder heats up.

However this:
"
T0
T1
M104 S215.0
"

Worked fine (i had preheated the extruder via Control Menu prior to starting the gcode from SD)

**Comment by thinkyhead** [comment]
Try `RCBugFix` and see if the problem still exists. We've fixed countless bugs in the last 11 months.
