### ISSUE TITLE
Isn't  problem for Gnu Pblic licence in  v1.0x issue?

### ISSUE THREAD

**Issue by takachinss1001jp** [MarlinFirmware/Marlin#4671]
RC7 is nice.
However It's might be Licence problem in V1.0,  I believe.
1) Still there is u7glib in source following;
    https://github.com/MarlinFirmware/Marlin/tree/1.0.x/ArduinoAddons

2) Licence of Marlin is GPL, Despite u8glib is new BSD Licence.
   Both are differrent Licence. 
   To see from u8glib for Marlin, There might be no Problem, On the other  hand  If you Issue 
 Marlinfirmware sources with u8glib is  some kind of infringement　about GPL.

3) I hope you can understand that I would like to argue about Licences.
   And I'm happy, If you delete u8glib in above Repository.

  Thanks,  and I look forward your officcial commnet.

 K.Haitaka takachinss1001jp@yahoo.co.jp

**Comment by thinkyhead** [comment]
BSD is a more permissive license. There is no conflict. The same would be true if we used the MIT license, the Apache license, or the Creative Commons license. In any case, we no longer include u8glib in the Marlin package. The reason it had been included (along with some other libraries) was to make more accessible a certified-to-work version of the library.

> "BSD: It is a lax, permissive non-copyleft free software license, compatible with the GNU GPL. This license is sometimes referred to as the 3-clause BSD license. The modified BSD license is not bad, as lax permissive licenses go, though the Apache 2.0 license is preferable."
