### ISSUE TITLE
u8glib

### ISSUE THREAD

**Issue by takachinss1001jp** [MarlinFirmware/Marlin#4672]
Dear Sir;

   I found u8glib in 1.0x source.
  Marlin Licence is GPL v3, u8glib is new BSD Licence.
  I really confused about diffrent Licences in same  Repository.
 Plase let me know what is reason,that you released as above?

 K.Haitakatakachinss1001jp@yahoo.co.jp

**Comment by howard0su** [comment]
this should be fine. Please read https://en.wikipedia.org/wiki/License_compatibility

**Comment by thinkyhead** [comment]
@takachinss1001jp I answered this already here, when you posted this question the first time: https://github.com/MarlinFirmware/Marlin/issues/4671#issuecomment-241261255 As Howard points out, Google contains all the answers you seek.

**Comment by takachinss1001jp** [comment]
Thank your prompt reply to my small question,  howard0su and thinkyhead.
 I had been learned wiki and Official GPL. 
 Yeah, There might be compatibility between new-BSD Licence and GPL v3.  
   Please listen；I found some Japanese Product Build in the Marlin with other Licence fonts.  
   And That guys merged the IPA fonts in them product.
  I complained to the guys, who might study the Licence, And they must understand the act were like Violene. 
  However their objection are following; 
  "We are not wrong,and their source were forked from origianl v1.0x, and just merged for localize. If we are something wrong, It came from Marlinfirmware.  You must complein to marlinfirmware.!!!' as so on. 
  Ahh! I regret that I contact like alien.Hmm
  And still I'm  persuading to them to be Modify the Web and to be separated  differnet Licence Source code from forked  git repository, not only fonts but also u8glib.
  Your kindness cooperation is appreciate, and I hope you can understand what I mean.
  Regards K.Haitaka takatachinss1001jp@yahoo.co.jp

**Comment by thinkyhead** [comment]
> Yeah, There might be compatibility between new-BSD License and GPL v3.

There is no incompatibility between the GPL and the BSD license. And Marlin is not explicit about its GPL license. Let us assume it is GPL v2, not GPL v3.

> not only fonts but also u8glib

Don't worry about u8glib. The BSD license is permissive. GPL is only incompatible with licenses that apply new restrictions.

> Japanese Product Build in the Marlin with other Licence fonts

Please give us more details on the font(s) that you are concerned about. Here is the source of our Katakana implementation: http://www.thingiverse.com/thing:664397 We have been granted permission by ichibey to use his work. We have been presuming that the 6x10 fonts we use for graphical displays were extracted directly from the HD44780.

> I regret that I contact like alien.

Do you have a personal stake in this issue, or are you crusading for the benefit of all?
