### ISSUE TITLE
Printed objects are ~5% shorter after updating to RC7

### ISSUE THREAD

**Issue by ChristopherHoffman** [MarlinFirmware/Marlin#4686]
I recently updated from the stable 1.0.2 to the 1.1.0-RC7, and noted that objects are about 5% shorter (in the z-axis) than what they were before updating. I made sure to transfer over the configuration settings from my old version, and verified that the DEFAULT_AXIS_STEPS_PER_UNIT are the same in the configuration. 

An object printed pre-upgrade measured 155.21mm (which is correct for that 3D model), but the same gcode printed with the same filament after upgrade measures 146.46 mm. A 20mm calibration cube measures 19.2mm.

X and Y axes are not affected, only the Z axis is off.

The printer has Auto Bed Leveling enabled, and I noticed that the nozzle offset was completely off what is was when it was set from HOME, but there is already an issue open for that. I had to baby-step the nozzle down, I don't know if that could have affected the layer heights and caused the object's height discrepancy.

**Comment by Roxy-3D** [comment]
My guess is you had to Baby Step down .8mm    This .8mm number keeps showing up.

**Comment by ChristopherHoffman** [comment]
I think it was more than that, ~1.4 mm for the cube. I ended up reducing my z-offset by that to compensate, and needed to babystep ~0.3 mm for the second 155mm-tall object.

**Comment by thinkyhead** [comment]
Try reducing your Z acceleration slightly and see if it helps. The acceleration code was fixed since 1.0.2-1, so your previous Z acceleration setting may now be too high.

**Comment by ChristopherHoffman** [comment]
I will give that a try later today!

**Comment by renzaaa** [comment]
To this version of Marlin RC7 the all axis steps is changed. Marlin RC3 the X/Y steps was 160.30 and Z was 795, but now X is 160.45, Y is 160.17 and Z is 800.  
Why this happens?

**Comment by thinkyhead** [comment]
Your axis steps are wholly determined by the formula dividing steps-per-revolution (e.g., 3200 steps) by mm-per-revolution (e.g. 40mm). If you find that you need to use values that are off from this, it implies either lost steps or loose pulleys. So, again, try reducing your acceleration and jerk values and keep testing.

**Comment by renzaaa** [comment]
Acceleration and jerk values is same, as it was for RC3 version.
Not lost steps and pulleys not loose.
Tomorrow I'll try to test different printer with Marlin RC7.

**Comment by thinkyhead** [comment]
Not `RC7` but `RCBugFix` if you please.
