### ISSUE TITLE
Feature Request: Nozzle Wipe sequence

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#4687]
Im not sure if this is already possible. But i dont recall it as an option.

I would like it if if marlin had the ability to run a Nozzle wipe sequence which was just a user defined set of Gcode, at a set interval of time or layers..

This isnt something ive been able in simplify 3d.

Being able to tell my machine to move the X gantry all the the way over to the right side and do a back and forth wipe a few times and then continue on printing.

**Comment by brainscan** [comment]
This has just been added along with park, settings and info are in configuration.h G12 and G27

Sent from my iPhone

On 22 Aug 2016, at 21:39, adamfilip <notifications@github.com<mailto:notifications@github.com>> wrote:

Im not sure if this is already possible. But i dont recall it as an option.

I would like it if if marlin had the ability to run a Nozzle wipe sequence which was just a user defined set of Gcode, at a set interval of time or layers..

This isnt something ive been able in simplify 3d.

Being able to tell my machine to move the X gantry all the the way over to the right side and do a back and forth wipe a few times and then continue on printing.

##

**Comment by Blue-Marlin** [comment]
How about g-codes for storing a position and returning to the stored point? In between you could do what you want.

**Comment by Roxy-3D** [comment]
> How about g-codes for storing a position and returning to the stored point? In between you could do what you want.

If we did something like this, my preference would be it is a single GCode and its behaviour is controlled with parameters.   

G13 S - Save current position
G13 R - Return to last saved position
