### ISSUE TITLE
Z_SAFE_HOMING outside of bed

### ISSUE THREAD

**Issue by tampas** [MarlinFirmware/Marlin#4692]
Hi, i'm trying to figure it out, how to config a z-probe only used for homing, to home on a safe zone.

It works when i send a Home all Axis command, but it fails when i try only to home the Z_Axis.
Sometimes it was outside of the bed and causes some potentially harmful accidents.

How can i correct this feature?

Thanks in advance

**Comment by thinkyhead** [comment]
We'll have to look closer at that. I'm not sure that `SAFE_HOMING` is actually intended to work for `G28 Z`, but only for `G28` homing all axes. Do you see the same problem if you home just 2 axes, such as `G28 X Z` or `G28 Y Z`?

**Comment by tampas** [comment]
Hi,

> I'm not sure also that SAFE_HOMING is intended to work for G28 Z command.

From the description provided it seems to be a routine to home all axes only.
But this case can provide some trouble situations.

I will test the G28 X Z and the G28 Y Z command and provide more info about it.

**Comment by thinkyhead** [comment]
@Roxy-3D It's just you and me around here lately. So, do you think `Z_SAFE_HOMING` should always apply when homing Z, or only when using `G28` on all axes, as originally specified? The thing is, if we extended it in that manner, then if you haven't already homed X or Y then those would need to be homed first before you could home Z. So then we'd have to choose whether to unexpectedly home X or Y or both first, or to throw up an error (which might be unseen with no console open) when you tried to home Z without homing X and Y first. It seems to me that this only sows more confusion, but what are your thoughts?

**Comment by Roxy-3D** [comment]
I probably lack the perspective to make my opinion valuable.  But the way I see it, homing is done so seldom, is there a benefit to doing it fast?   I think I would argue we should always try to protect the machine from doing damage to itself. 

Looking at it from a slightly different perspective, both Delta's (in general) and Cartesian machines with probes offset from the nozzle need to know where they are in the (X,Y) before downward Z movement is safe.   I know people are going to disagree, but I think it makes sense to insist (X,Y) are known prior to downward movement of Z.

**Comment by thinkyhead** [comment]
I tend to agree. But the problem is we can't guarantee that (a) the user will realize either why the Z is refusing to home before homing XY in the case where we simply prevent it, or (b) the user will be annoyed that the XY homes (unexpectedly) in response to `G28 Z`. So one way or another, if we go down this path there will have to be compromise.

**Comment by Roxy-3D** [comment]
> So one way or another, if we go down this path there will have to be compromise.

There may be multiple paths forward.   One 'compromise' is we do nothing in RC-7 & RC-8.  We keep it just the way it is.   But we could make the change over in the devel_ubl branch and that give us time to see if people agree with the direction.     If we did that, it might make sense to make SAFE_HOMING the default, and you have to enable UNSAFE_AND_RECKLESS_HOMING (just kidding!)  if you want the other behavior.

**Comment by thinkyhead** [comment]
I hear you. Frankly, the use of `G28 Z` is somewhat niche. 99% of the time we just do a plain `G28`.

**Comment by Roxy-3D** [comment]
> I hear you. Frankly, the use of G28 Z is somewhat niche. 99% of the time we just do a plain G28.

Agreed.  Except, doesn't PronterFace do a G28 X or G28 Y or G28 Z when you click the home buttons?  I thought it did.   

Anyway...   G28 was kind of an early example of what happened to G29.   As stuff got added, pretty soon we ended up with #ifdef's nested 37 levels deep.   It would be nice to clear out some of that clutter!     If we rewrote G28 we could clean it up a lot.

**Comment by thinkyhead** [comment]
Funny you should say. I was just thinking last night, heck, let's just make separate versions of the whole `G28` and `G29` functions for each type (i.e., cartesian / delta), and that will keep us from having our eyes crossed trying to see the implications quite so often. If there are clearly duplicated sections, we can separate those out into sub-functions.

**Comment by Roxy-3D** [comment]
> let's just make separate versions of the whole G28 ~~and G29 functions for each type, and that will keep us from having our eyes crossed trying to see the implications quite so often.~~

Or...   There is only ONE version of G29 in UBL !  :)    (But I will have a few #ifdef DELTA 's to change where the nozzle and probe are allowed to travel.)    So if you are going to rewrite anything, G28 is more needed than G29 !

**Comment by tampas** [comment]
Hi, 
first of all, my apologies for taking so long to give you the promised feedback.
The problem persists when i do the G28 X Z and G28 Y Z.
The machine doesn't move in XY plan ensuring that the Z Probe is in a safe place inside of the bed area.

does not exist any easy solution for this? that i can force by firmware that when Z is argument of G28 command, that the firmware ensures that we always make a Z_SAFE_Home routine?

my problem is that for some unexperienced users, this safety fault could be a huge problem.
Some host softwares (as simplify3D in my case) grants a Home Z button, and i cannot predict that any user will not trigger it.

Best regards,
T_Ermida

**Comment by thinkyhead** [comment]
Someone will have to implement it in their copious spare time.

**Comment by tampas** [comment]
Ok, thank you for your feedback on this matter.
For now, i'm thinking on a turn around solution for this.
I'm trying to limit the machine moves, reducing is X_MAX_POS and Y_MAX_POS, to ensure that Z_Probe is always above the bed.

As i say, is only a temporary solution, because it makes me lose some print area, and the machine will never touch its X_Max_ENDSTOP and Y_MAX_ENDSTOP. This fact could cause another security issue.

Do you think that this solution could work?
Thank you

**Comment by thinkyhead** [comment]
The solution isn't that hard. Instead of only doing the safe home based on `home_all_axis` it should instead just check that X and Y have already been homed.

**Comment by lrpirlet** [comment]
This is not a new discussion... You'll need to home X and Y before homing Z
whenever power was cut to the motor of X and/or Y axis...

2016-08-30 22:28 GMT+02:00 Scott Lahteine notifications@github.com:

**Comment by RogerRepRap** [comment]
If you are doing a print with items left on bed from previous run you may not be able to home X and Y before Z without crashing into something. A G92 X0Y0 followed by a G28 Z works fine in this scenario. May be just bad habits picked up from running a CNC mill with multiple setups.

**Comment by thinkyhead** [comment]
@RogerRepRap Actually G92 doesn't cause the XY to become marked as "known" or "homed" and so if Z safe homing is enabled, it will still behave the same way even after a G92.

**Comment by thinkyhead** [comment]
> You'll need to home X and Y before homing Z whenever power was cut to the motor of X and/or Y axis

True. The positions become "unknown" at that point. The machine has no way to know that X and Y weren't moved arbitrarily.

However, in the case where X and Y steppers have not been disabled, it should be ok to perform z safe homing. As mentioned, the fix isn't too involved. But it's not something I'll be able to implement for at least a few days.

**Comment by Blue-Marlin** [comment]
With the behaviour as it is today you can home z wher evever you want - when homed alone. This is important when there is a part on the bed. Homing z always at a pre-specified point will destroy this flexibility and will prevent from homing z in too many cases. At least there must be a parameter to restore the used behaviour.

**Comment by htaxil** [comment]
hi all,

I'm actualy hacking a Cube-X 3D printer, who have magnetic switches (REED) for endstop, including for the z axe. for this z axe, one magnet is housed under the bed at the coordinates X140, Y150 and the endstop is located on the effector. I must therefore place the effector above the magnet before leveling Z, Including when I only do the Z homing (G28 Z).

Is there a solution ?

Regards,
Hubert

**Comment by htaxil** [comment]
up

**Comment by thinkyhead** [comment]
@htaxil I believe this is the behavior of 1.1.0 `RCBugFix` currently. If you try to home Z with a "probe" — or using `Z_SAFE_HOMING` and if **_XY are already homed_**, then `G28 Z` should move to the safe homing point (as defined by `Z_SAFE_HOMING_X_POINT` and `Z_SAFE_HOMING_X_POINT`) before homing Z. You may also want to set `Z_HOMING_HEIGHT` to get some extra clearance.

**Comment by cryocide** [comment]
Hello all!  Sorry for dredging up this old thread, but I'm having a very similar issue with Z_SAFE_HOMING on Marlin 1.1.8.  Under some very specific, but common, circumstances, my machine will not move the bed to a safe location before homing Z.

Machine setup:  Prusa i3 clone, GT2560 all-in-one controller, inductive prox sensor, and TMC2130 drivers using SPI (shared bus with SD card, comm verified with all devices).  Stallguard acts as X and Y MIN endstops.  Z MIN endstop is the prox sensor.  All other endstops are disabled via comment.  *Power to the whole printer, including the controller, is controlled via power switch/input signal on ATX and USB power is isolated, so "OFF" means absolutely off.*

Steps to recreate:

* Power on machine
* Connect to host
* Wait for opening monologue to finish in the Terminal
* Send G28  (or G28 X Y, immediately followed by G28 Z with no delay)
* Watch X-axis home, followed by Y-axis
* Watch X-axis move to safe position, but Y-axis *does not*
* Watch in horror and/or scramble for emergency stop button as Z-axis crawls ominously downward with the probe outside the bed

After experimenting, I've been able to repeat this 5 times in a row, and the key to this seems to be starting up from a powered-off condition.

Workarounds:
* G28 X Y, then wait a few seconds either manually or by G4 during a script, then G28 Z.  
* Alternatively, G28 homes safely after *any* Y-axis movement after power-on.

I don't know exactly what's causing the issue with the Y-axis not moving to a safe position during Z homing if Y hasn't moved a bit prior to homing.  I never saw this behavior before my TMC2130 upgrade, but then again, I wasn't using an inductive probe before either, so I was using the UNSAFE_AND_RECKLESS_HOMING option.  

I know the Mega2560 isn't the fastest kid on the block, so I'm wondering if maybe the Y-axis driver is taking too long to send feedback via the Diag pin.  Either that, or maybe the drivers aren't fully configured until after their first move attempt, so it's not sending the signal right away (this theory conflicts with the X-axis working correctly).  Those are the only theories I have.

I'm attaching debug files for G28 from both connect-after-power-off state and connect-after-reset-state.

<details><summary>failed home from a powered-off state</summary>

```
09:45:11.056 : Printer reset detected - initalizing
09:45:11.056 : start
09:45:11.056 : echo: External Reset
09:45:11.056 : Marlin 1.1.8
09:45:11.056 : echo: Last Updated: 2017-12-25 12:00 | Author: (none, default config)
09:45:11.056 : echo:Compiled: May 23 2018
09:45:11.056 : echo: Free Memory: 2973  PlannerBufferBytes: 1232
09:45:11.056 : echo:V47 stored settings retrieved (614 bytes; crc 62674)
09:45:11.056 : echo:  G21    ; Units in mm
09:45:11.056 : echo:  M149 C ; Units in Celsius
09:45:11.056 : echo:Filament settings: Disabled
09:45:11.056 : echo:  M200 D1.75
09:45:11.056 : echo:  M200 D0
09:45:11.056 : echo:Steps per unit:
09:45:11.056 : echo:  M92 X80.00 Y80.00 Z400.00 E156.25
09:45:11.056 : echo:Maximum feedrates (units/s):
09:45:11.056 : echo:  M203 X150.00 Y150.00 Z8.00 E20.00
09:45:11.056 : echo:Maximum Acceleration (units/s2):
09:45:11.056 : echo:  M201 X2000 Y2000 Z100 E10000
09:45:11.056 : echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
09:45:11.056 : echo:  M204 P2000.00 R3000.00 T2000.00
09:45:11.056 : echo:Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_us> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
09:45:11.056 : echo:  M205 S0.00 T0.00 B20000 X15.00 Y15.00 Z0.40 E5.00
09:45:11.056 : echo:Home offset:
09:45:11.056 : echo:  M206 X0.00 Y0.00 Z0.00
09:45:11.056 : echo:Auto Bed Leveling:
09:45:11.056 : echo:  M420 S0 Z0.00
09:45:11.056 : echo:Material heatup parameters:
09:45:11.056 : echo:  M145 S0 H180 B70 F0
09:45:11.056 : echo:  M145 S1 H240 B110 F0
09:45:11.056 : echo:PID settings:
09:45:11.056 : echo:  M301 P12.06 I0.50 D73.34
09:45:11.056 : echo:  M304 P527.54 I75.76 D918.32
09:45:11.056 : echo:Z-Probe Offset (mm):
09:45:11.056 : echo:  M851 Z-0.55
09:45:11.056 : echo:Stepper driver current:
09:45:11.056 : echo:  M906 X 850 Y 875 Z 925 E0 875
09:45:11.056 : echo:Sensorless homing threshold:
09:45:11.056 : echo:  M914 X8 Y8
09:45:11.206 : N1 M110*34
09:45:11.206 : N2 M115*36
09:45:11.206 : N4 M114*35
09:45:11.222 : N5 M111 S6*98
09:45:14.361 : ok
09:45:14.361 : N6 T0*60
09:45:14.424 : FIRMWARE_NAME:Marlin 1.1.8 (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Dum-E is EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
09:45:14.424 : Cap:SERIAL_XON_XOFF:0
09:45:14.424 : Cap:EEPROM:1
09:45:14.424 : Cap:VOLUMETRIC:1
09:45:14.439 : Cap:AUTOREPORT_TEMP:1
09:45:14.439 : Cap:PROGRESS:0
09:45:14.439 : Cap:PRINT_JOB:1
09:45:14.439 : Cap:AUTOLEVEL:1
09:45:14.439 : Cap:Z_PROBE:1
09:45:14.439 : Cap:LEVELING_DATA:1
09:45:14.439 : Cap:BUILD_PERCENT:0
09:45:14.439 : Cap:SOFTWARE_POWER:0
09:45:14.439 : Cap:TOGGLE_LIGHTS:0
09:45:14.439 : Cap:CASE_LIGHT_BRIGHTNESS:0
09:45:14.439 : Cap:EMERGENCY_PARSER:0
09:45:14.439 : ok
09:45:14.439 : N7 M20*22
09:45:14.439 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
09:45:14.439 : ok
09:45:14.439 : echo:DEBUG:INFO,ERRORS
09:45:14.439 : ok
09:45:14.439 : echo:Active Extruder: 0
09:45:14.439 : ok
09:45:14.439 : N8 M80*19
09:45:14.439 : N10 M220 S100*80
09:45:14.439 : Begin file list
09:45:14.456 : End file list
09:45:14.456 : ok
09:45:14.456 : N11 M221 S100*80
09:45:14.470 : ok
09:45:14.479 : ok
09:45:14.479 : ok
09:45:14.479 : N12 M111 S6*84
09:45:14.479 : N13 T0*8
09:45:14.494 : echo:DEBUG:INFO,ERRORS
09:45:14.494 : ok
09:45:14.510 : echo:Active Extruder: 0
09:45:14.510 : ok
09:45:17.981 : echo:SD init fail
09:46:34.369 : N40 M111*22
09:46:34.379 : echo:DEBUG:INFO,ERRORS
09:46:34.379 : ok
09:46:45.983 : N44 M111 S247*80
09:46:45.983 : echo:DEBUG:ECHO,INFO,ERRORS,COMMUNICATION,LEVELING
09:46:45.983 : ok
09:46:57.087 : N49 G28*46
09:46:57.115 : echo:N49 G28*46
09:46:57.115 : >>> gcode_G28
09:46:57.115 : Machine Type: Cartesian
09:46:57.115 : Probe: FIX_MOUNTED_PROBE
09:46:57.115 : Probe Offset X:-22 Y:-62 Z:-0.55 (Left-Front & Below Nozzle)
09:46:57.115 : Auto Bed Leveling: BILINEAR (disabled)
09:46:57.115 : current_position=(0.00, 0.00, 0.00) : setup_for_endstop_or_probe_move
09:46:57.115 : > endstops.enable(true)
09:46:57.115 : Raise Z (before homing) to 1.00
09:46:57.115 : >>> do_blocking_move_to(0.00, 0.00, 1.00)
09:46:57.396 : <<< do_blocking_move_to
09:46:57.396 : >>> homeaxis(X)
09:46:57.396 : Home 1 Fast:
09:46:57.396 : >>> do_homing_move(X, -312.00, 0.00)
09:46:57.396 : current_position=(0.00, 0.00, 1.00) : sync_plan_position
09:46:59.017 : <<< do_homing_move(X)
09:46:59.017 : >>> set_axis_is_at_home(X)
09:46:59.017 : For X axis:
09:46:59.017 : home_offset = 0.00
09:46:59.017 : position_shift = 0.00
09:46:59.017 : soft_endstop_min = 0.00
09:46:59.017 : soft_endstop_max = 208.00
09:46:59.017 : > home_offset[X] = 0.00
09:46:59.017 : current_position=(0.00, 0.00, 1.00) :
09:46:59.017 : <<< set_axis_is_at_home(X)
09:46:59.017 : current_position=(0.00, 0.00, 1.00) : sync_plan_position
09:46:59.018 : current_position=(0.00, 0.00, 1.00) : > AFTER set_axis_is_at_home
09:46:59.018 : <<< homeaxis(X)
09:46:59.018 : current_position=(0.00, 0.00, 1.00) : > homeX
09:46:59.018 : >>> homeaxis(Y)
09:46:59.018 : Home 1 Fast:
09:46:59.018 : >>> do_homing_move(Y, -345.00, 0.00)
09:46:59.018 : current_position=(0.00, 0.00, 1.00) : sync_plan_position
09:46:59.046 : <<< do_homing_move(Y)
09:46:59.087 : >>> set_axis_is_at_home(Y)
09:46:59.087 : For Y axis:
09:46:59.087 : home_offset = 0.00
09:46:59.087 : position_shift = 0.00
09:46:59.087 : soft_endstop_min = 0.00
09:46:59.087 : soft_endstop_max = 230.00
09:46:59.087 : > home_offset[Y] = 0.00
09:46:59.087 : current_position=(0.00, 0.00, 1.00) :
09:46:59.087 : <<< set_axis_is_at_home(Y)
09:46:59.087 : current_position=(0.00, 0.00, 1.00) : sync_plan_position
09:46:59.087 : current_position=(0.00, 0.00, 1.00) : > AFTER set_axis_is_at_home
09:46:59.087 : <<< homeaxis(Y)
09:46:59.087 : current_position=(0.00, 0.00, 1.00) : > homeY
09:46:59.088 : Z_SAFE_HOMING >>>
09:46:59.088 : current_position=(0.00, 0.00, 1.00) : sync_plan_position
09:46:59.088 : destination=(126.00, 177.00, 1.00) : Z_SAFE_HOMING
09:46:59.088 : >>> do_blocking_move_to(126.00, 177.00, 1.00)
09:46:59.103 : echo:busy: processing
09:47:01.098 : echo:busy: processing
09:47:01.848 : <<< do_blocking_move_to
09:47:01.848 : >>> homeaxis(Z)
09:47:01.848 : current_position=(126.00, 177.00, 1.00) : set_probe_deployed
09:47:01.848 : deploy: 1
09:47:01.848 : do_probe_raise(1.00)
09:47:01.848 : >>> do_blocking_move_to(126.00, 177.00, 1.55)
09:47:02.019 : <<< do_blocking_move_to
09:47:02.019 : >>> do_blocking_move_to(126.00, 177.00, 1.55)
09:47:02.019 : <<< do_blocking_move_to
09:47:02.019 : Home 1 Fast:
09:47:02.019 : >>> do_homing_move(Z, -285.00, 0.00)
09:47:02.019 : current_position=(126.00, 177.00, 0.00) : sync_plan_position
09:47:03.081 : echo:busy: processing
09:47:05.081 : echo:busy: processing
09:47:07.089 : echo:busy: processing
09:47:09.074 : echo:busy: processing
```
</details>


[home_debugfail.txt](https://github.com/MarlinFirmware/Marlin/files/2031702/home_debugfail.txt)

---
<details><summary>successful home from a powered-on but reset state</summary>

```
09:48:25.631 : Printer reset detected - initalizing
09:48:25.631 : start
09:48:25.631 : echo: External Reset
09:48:25.631 : Marlin 1.1.8
09:48:25.631 : echo: Last Updated: 2017-12-25 12:00 | Author: (none, default config)
09:48:25.631 : echo:Compiled: May 23 2018
09:48:25.631 : echo: Free Memory: 2973  PlannerBufferBytes: 1232
09:48:25.631 : echo:V47 stored settings retrieved (614 bytes; crc 62674)
09:48:25.631 : echo:  G21    ; Units in mm
09:48:25.631 : echo:  M149 C ; Units in Celsius
09:48:25.631 : echo:Filament settings: Disabled
09:48:25.631 : echo:  M200 D1.75
09:48:25.631 : echo:  M200 D0
09:48:25.631 : echo:Steps per unit:
09:48:25.631 : echo:  M92 X80.00 Y80.00 Z400.00 E156.25
09:48:25.631 : echo:Maximum feedrates (units/s):
09:48:25.631 : echo:  M203 X150.00 Y150.00 Z8.00 E20.00
09:48:25.631 : echo:Maximum Acceleration (units/s2):
09:48:25.631 : echo:  M201 X2000 Y2000 Z100 E10000
09:48:25.631 : echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
09:48:25.631 : echo:  M204 P2000.00 R3000.00 T2000.00
09:48:25.631 : echo:Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_us> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
09:48:25.631 : echo:  M205 S0.00 T0.00 B20000 X15.00 Y15.00 Z0.40 E5.00
09:48:25.631 : echo:Home offset:
09:48:25.631 : echo:  M206 X0.00 Y0.00 Z0.00
09:48:25.631 : echo:Auto Bed Leveling:
09:48:25.631 : echo:  M420 S0 Z0.00
09:48:25.631 : echo:Material heatup parameters:
09:48:25.631 : echo:  M145 S0 H180 B70 F0
09:48:25.631 : echo:  M145 S1 H240 B110 F0
09:48:25.631 : echo:PID settings:
09:48:25.631 : echo:  M301 P12.06 I0.50 D73.34
09:48:25.631 : echo:  M304 P527.54 I75.76 D918.32
09:48:25.631 : echo:Z-Probe Offset (mm):
09:48:25.631 : echo:  M851 Z-0.55
09:48:25.631 : echo:Stepper driver current:
09:48:25.631 : echo:  M906 X 850 Y 875 Z 925 E0 875
09:48:25.631 : echo:Sensorless homing threshold:
09:48:25.631 : echo:  M914 X8 Y8
09:48:25.819 : N1 M110*34
09:48:25.819 : N2 M115*36
09:48:25.819 : N4 M114*35
09:48:25.851 : N5 M111 S6*98
09:48:28.952 : ok
09:48:28.952 : N6 T0*60
09:48:29.015 : FIRMWARE_NAME:Marlin 1.1.8 (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Dum-E is EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
09:48:29.015 : Cap:SERIAL_XON_XOFF:0
09:48:29.015 : Cap:EEPROM:1
09:48:29.015 : Cap:VOLUMETRIC:1
09:48:29.015 : Cap:AUTOREPORT_TEMP:1
09:48:29.015 : Cap:PROGRESS:0
09:48:29.015 : Cap:PRINT_JOB:1
09:48:29.015 : Cap:AUTOLEVEL:1
09:48:29.015 : Cap:Z_PROBE:1
09:48:29.015 : Cap:LEVELING_DATA:1
09:48:29.015 : Cap:BUILD_PERCENT:0
09:48:29.015 : Cap:SOFTWARE_POWER:0
09:48:29.015 : Cap:TOGGLE_LIGHTS:0
09:48:29.015 : Cap:CASE_LIGHT_BRIGHTNESS:0
09:48:29.015 : Cap:EMERGENCY_PARSER:0
09:48:29.015 : ok
09:48:29.015 : N7 M20*22
09:48:29.039 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
09:48:29.039 : ok
09:48:29.039 : echo:DEBUG:INFO,ERRORS
09:48:29.039 : ok
09:48:29.039 : echo:Active Extruder: 0
09:48:29.039 : ok
09:48:29.039 : Begin file list
09:48:29.040 : N8 M80*19
09:48:29.040 : N10 M220 S100*80
09:48:29.040 : End file list
09:48:29.040 : ok
09:48:29.040 : N11 M221 S100*80
09:48:29.052 : ok
09:48:29.067 : ok
09:48:29.067 : ok
09:48:29.067 : N12 M111 S6*84
09:48:29.067 : N13 T0*8
09:48:29.083 : echo:DEBUG:INFO,ERRORS
09:48:29.083 : ok
09:48:29.099 : echo:Active Extruder: 0
09:48:29.099 : ok
09:48:32.571 : echo:SD init fail
09:48:35.677 : N16 M111 S247*87
09:48:35.693 : echo:DEBUG:ECHO,INFO,ERRORS,COMMUNICATION,LEVELING
09:48:35.693 : ok
09:48:40.424 : N18 G28*42
09:48:40.424 : echo:N18 G28*42
09:48:40.424 : >>> gcode_G28
09:48:40.424 : Machine Type: Cartesian
09:48:40.452 : Probe: FIX_MOUNTED_PROBE
09:48:40.452 : Probe Offset X:-22 Y:-62 Z:-0.55 (Left-Front & Below Nozzle)
09:48:40.452 : Auto Bed Leveling: BILINEAR (disabled)
09:48:40.452 : current_position=(0.00, 0.00, 0.00) : setup_for_endstop_or_probe_move
09:48:40.452 : > endstops.enable(true)
09:48:40.452 : Raise Z (before homing) to 1.00
09:48:40.452 : >>> do_blocking_move_to(0.00, 0.00, 1.00)
09:48:40.727 : <<< do_blocking_move_to
09:48:40.727 : >>> homeaxis(X)
09:48:40.727 : Home 1 Fast:
09:48:40.727 : >>> do_homing_move(X, -312.00, 0.00)
09:48:40.727 : current_position=(0.00, 0.00, 1.00) : sync_plan_position
09:48:42.365 : <<< do_homing_move(X)
09:48:42.365 : >>> set_axis_is_at_home(X)
09:48:42.365 : For X axis:
09:48:42.365 : home_offset = 0.00
09:48:42.365 : position_shift = 0.00
09:48:42.365 : soft_endstop_min = 0.00
09:48:42.365 : soft_endstop_max = 208.00
09:48:42.365 : > home_offset[X] = 0.00
09:48:42.365 : current_position=(0.00, 0.00, 1.00) :
09:48:42.365 : <<< set_axis_is_at_home(X)
09:48:42.365 : current_position=(0.00, 0.00, 1.00) : sync_plan_position
09:48:42.365 : current_position=(0.00, 0.00, 1.00) : > AFTER set_axis_is_at_home
09:48:42.365 : <<< homeaxis(X)
09:48:42.365 : current_position=(0.00, 0.00, 1.00) : > homeX
09:48:42.365 : >>> homeaxis(Y)
09:48:42.365 : Home 1 Fast:
09:48:42.365 : >>> do_homing_move(Y, -345.00, 0.00)
09:48:42.365 : current_position=(0.00, 0.00, 1.00) : sync_plan_position
09:48:42.414 : echo:busy: processing
09:48:44.414 : echo:busy: processing
09:48:44.600 : <<< do_homing_move(Y)
09:48:44.600 : >>> set_axis_is_at_home(Y)
09:48:44.600 : For Y axis:
09:48:44.600 : home_offset = 0.00
09:48:44.600 : position_shift = 0.00
09:48:44.600 : soft_endstop_min = 0.00
09:48:44.600 : soft_endstop_max = 230.00
09:48:44.600 : > home_offset[Y] = 0.00
09:48:44.600 : current_position=(0.00, 0.00, 1.00) :
09:48:44.600 : <<< set_axis_is_at_home(Y)
09:48:44.600 : current_position=(0.00, 0.00, 1.00) : sync_plan_position
09:48:44.600 : current_position=(0.00, 0.00, 1.00) : > AFTER set_axis_is_at_home
09:48:44.600 : <<< homeaxis(Y)
09:48:44.600 : current_position=(0.00, 0.00, 1.00) : > homeY
09:48:44.600 : Z_SAFE_HOMING >>>
09:48:44.600 : current_position=(0.00, 0.00, 1.00) : sync_plan_position
09:48:44.600 : destination=(126.00, 177.00, 1.00) : Z_SAFE_HOMING
09:48:44.600 : >>> do_blocking_move_to(126.00, 177.00, 1.00)
09:48:46.430 : echo:busy: processing
09:48:47.366 : <<< do_blocking_move_to
09:48:47.366 : >>> homeaxis(Z)
09:48:47.366 : current_position=(126.00, 177.00, 1.00) : set_probe_deployed
09:48:47.366 : deploy: 1
09:48:47.366 : do_probe_raise(1.00)
09:48:47.366 : >>> do_blocking_move_to(126.00, 177.00, 1.55)
09:48:47.534 : <<< do_blocking_move_to
09:48:47.534 : >>> do_blocking_move_to(126.00, 177.00, 1.55)
09:48:47.534 : <<< do_blocking_move_to
09:48:47.534 : Home 1 Fast:
09:48:47.534 : >>> do_homing_move(Z, -285.00, 0.00)
09:48:47.534 : current_position=(126.00, 177.00, 0.00) : sync_plan_position
09:48:48.434 : echo:busy: processing
09:48:50.435 : echo:busy: processing
09:48:52.426 : echo:busy: processing
09:48:52.488 : <<< do_homing_move(Z)
09:48:52.488 : Move Away:
09:48:52.488 : >>> do_homing_move(Z, 2.00, 0.00)
09:48:52.488 : current_position=(126.00, 177.00, 0.00) : sync_plan_position
09:48:53.023 : <<< do_homing_move(Z)
09:48:53.023 : Home 2 Slow:
09:48:53.023 : >>> do_homing_move(Z, -4.00, 1.00)
09:48:53.023 : current_position=(126.00, 177.00, 0.00) : sync_plan_position
09:48:54.425 : echo:busy: processing
09:48:54.992 : <<< do_homing_move(Z)
09:48:55.026 : >>> set_axis_is_at_home(Z)
09:48:55.026 : For Z axis:
09:48:55.026 : home_offset = 0.00
09:48:55.026 : position_shift = 0.00
09:48:55.026 : soft_endstop_min = 0.00
09:48:55.026 : soft_endstop_max = 190.00
09:48:55.026 : *** Z HOMED WITH PROBE (Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN) ***
09:48:55.026 : > zprobe_zoffset = -0.55
09:48:55.026 : > home_offset[Z] = 0.00
09:48:55.026 : current_position=(126.00, 177.00, 0.55) :
09:48:55.026 : <<< set_axis_is_at_home(Z)
09:48:55.026 : current_position=(126.00, 177.00, 0.55) : sync_plan_position
09:48:55.026 : current_position=(126.00, 177.00, 0.55) : > AFTER set_axis_is_at_home
09:48:55.026 : current_position=(126.00, 177.00, 0.55) : set_probe_deployed
09:48:55.026 : deploy: 0
09:48:55.026 : do_probe_raise(1.00)
09:48:55.026 : >>> do_blocking_move_to(126.00, 177.00, 1.55)
09:48:55.328 : <<< do_blocking_move_to
09:48:55.328 : >>> do_blocking_move_to(126.00, 177.00, 1.55)
09:48:55.328 : <<< do_blocking_move_to
09:48:55.328 : <<< homeaxis(Z)
09:48:55.328 : <<< Z_SAFE_HOMING
09:48:55.328 : current_position=(126.00, 177.00, 1.55) : > (home_all || homeZ) > final
09:48:55.328 : current_position=(126.00, 177.00, 1.55) : sync_plan_position
09:48:55.328 : current_position=(126.00, 177.00, 1.55) : clean_up_after_endstop_or_probe_move
09:48:55.328 : X:126.00 Y:177.00 Z:1.55 E:0.00 Count X:10080 Y:14160 Z:620
09:48:55.328 : <<< gcode_G28
09:48:55.328 : ok
```
</details>

[home_debug success.txt](https://github.com/MarlinFirmware/Marlin/files/2031703/home_debug.success.txt)

**Comment by thinkyhead** [comment]
@cryocide — Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem isn't resolved yet, then please open a new issue.

**Comment by ManuelMcLure** [comment]
Also, do you have `STEALTHCHOP` enabled? There is some homing weirdness that has been seen if `STEALTHCHOP` is disabled. Look at #10605.

**Comment by cryocide** [comment]
@thinkyhead Will do, and thanks! 

@ManuelMcLure Actually, yes I have it enabled, but the hybrid threshold is (was) set to the same rate as my homing_feedrate.  I think it was going into spreadcycle during homing.  I'll raise the hybrid threshold by 1 to make sure homing happens in stealthchop mode and will test under 1.1.8 in addition to trying out bugfix 1.1.x and 2.0.x.
