### ISSUE TITLE
Character Encoding Issues in UBL Dev Branch

### ISSUE THREAD

**Issue by psavva** [MarlinFirmware/Marlin#4699]
@Roxy-3D Please have a look though all the commits done on UBL, It seems you have a character encoding issue, when it comes to some special characters.

Mariln_main.cpp
Example:
-    ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ temperature
-    ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ planner
-    ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ watchdog
-    ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ stepper
-    ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ photo pin
-    ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ servos
-    ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ LCD controller
-    ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ Digipot I2C
-    ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ Z probe sled
-    ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ status LEDs
-    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ temperature
-    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ planner
-    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ watchdog
-    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ stepper
-    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ photo pin
-    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ servos
-    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ LCD controller
-    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ Digipot I2C
-    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ Z probe sled
-    ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¢ status LEDs

First time it was changed:
-    • temperature
-    • planner
-    • watchdog
-    • stepper
-    • photo pin
-    • servos
-    • LCD controller
-    • Digipot I2C
-    • Z probe sled
-    • status LEDs
-    â€¢ temperature
-    â€¢ planner
-    â€¢ watchdog
-    â€¢ stepper
-    â€¢ photo pin
-    â€¢ servos
-    â€¢ LCD controller
-    â€¢ Digipot I2C
-    â€¢ Z probe sled
-    â€¢ status LEDs

Was in revision: 23af5a826c75e4ffd19611dd7683828a66e14341

I some this in some other places as well, check the configuration file, after the 300
edc99da2a68a64f9ddfd256f048861236b73e0cc

// 13 is 100k Hisens 3950  1% up to 300°C for hotend "Simple ONE " & "Hotend "All In ONE"
// 13 is 100k Hisens 3950  1% up to 300Â°C for hotend "Simple ONE " & "Hotend "All In ONE"

**Comment by Roxy-3D** [comment]
Is that being caused by my text editor?   Once we get this fixed, we don't want it to happen again!  
To keep it from happening again, should we stop using non-ascii characters?

Also...   When I pull down the latest RCBugFix and look at its Configuration.h file, there is the same non-sense.   Starting at about line 205 I get this crap:

```
// 1047 is Pt1000 with 4k7 pullup
// 1010 is Pt1000 with 1k pullup (non standard)
// 147 is Pt100 with 4k7 pullup
// 110 is Pt100 with 1k pullup (non standard)
// 998 and 999 are Dummy Tables. They will ALWAYS read 25Â°C or the temperature defined below.
//     Use it for Testing or Development purposes. NEVER for production machine.
//#define DUMMY_THERMISTOR_998_VALUE 25
//#define DUMMY_THERMISTOR_999_VALUE 100
// :{ '0': "Not used",'1':"100k / 4.7k - EPCOS",'2':"200k / 4.7k - ATC Semitec 204GT-2",'3':"Mendel-parts / 4.7k",'4':"10k !! do not use for a hotend. Bad resolution at high temp. !!",'5':"100K / 4.7k - ATC Semitec 104GT-2 (Used in ParCan & J-Head)",'6':"100k / 4.7k EPCOS - Not as accurate as Table 1",'7':"100k / 4.7k Honeywell 135-104LAG-J01",'8':"100k / 4.7k 0603 SMD Vishay NTCS0603E3104FXT",'9':"100k / 4.7k GE Sensing AL03006-58.2K-97-G1",'10':"100k / 4.7k RS 198-961",'11':"100k / 4.7k beta 3950 1%",'12':"100k / 4.7k 0603 SMD Vishay NTCS0603E3104FXT (calibrated for Makibox hot bed)",'13':"100k Hisens 3950  1% up to 300Â°C for hotend 'Simple ONE ' & hotend 'All In ONE'",'20':"PT100 (Ultimainboard V2.x)",'51':"100k / 1k - EPCOS",'52':"200k / 1k - ATC Semitec 204GT-2",'55':"100k / 1k - ATC Semitec 104GT-2 (Used in ParCan & J-Head)",'60':"100k Maker's Tool Works Kapton Bed Thermistor beta=3950",'66':"Dyze Design 4.7M High Temperature thermistor",'70':"the 100K thermistor found in the bq Hephestos 2",'71':"100k / 4.7k Honeywell 135-104LAF-J01",'147':"Pt100 / 4.7k",'1047':"Pt1000 / 4.7k",'110':"Pt100 / 1k (non-standard)",'1010':"Pt1000 / 1k (non standard)",'-3':"Thermocouple + MAX31855 (only for sensor 0)",'-2':"Thermocouple + MAX6675 (only for sensor 0)",'-1':"Thermocouple + AD595",'998':"Dummy 1",'999':"Dummy 2" }
#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_BED 0
```

What is that crap?  (the //998 and 999 line does not show up right in any of my editors because of the special characters  between the 25 & C.   But what is that super long line?  Why is that in the source?   

Looking at Marlin_main.cpp, at about line 855 is that table you gave in your example.    

```
/**
 * Marlin entry-point: Set up before the program loop
 *  - Set up the kill pin, filament runout, power hold
 *  - Start the serial port
 *  - Print startup messages and diagnostics
 *  - Get EEPROM or default settings
 *  - Initialize managers for:
 *    â€¢ temperature
 *    â€¢ planner
 *    â€¢ watchdog
 *    â€¢ stepper
 *    â€¢ photo pin
 *    â€¢ servos
 *    â€¢ LCD controller
 *    â€¢ Digipot I2C
 *    â€¢ Z probe sled
 *    â€¢ status LEDs
 */
```

I use Vim to edit files.   I've never had a problem before.   But I have a problem with Marlin_main.cpp !!!   I don't see the value of booby trapping the source code so only specially configured systems can edit the code.  

I'll start stripping out the non-ascii characters as I find them.

**Comment by psavva** [comment]
Have a look at this.
http://stackoverflow.com/questions/5166652/how-to-view-utf-8-characters-in-vim-or-gvim

Consider that special and non ASCII characters are supported and should be displayed correctly.

Even in the language files, we use UTF8 and even Greek characters :)

**Comment by Roxy-3D** [comment]
> Consider that special and non ASCII characters are supported and should be displayed correctly.
> Even in the language files, we use UTF8 and even Greek characters :)

OK...    I hear you!   I'll read the article and see if I can get Vim to handle the special characters.

**Comment by Roxy-3D** [comment]
@psavva    I have Vim defaulting to use UTF-8.   That seems to allow me to pull in files and write them back out without problems.    I have a few more things to clean up in the UBL branch, but over the next few days those encoding errors should go away.    If you see any encoding errors a week from now, please let me know.  I'll get them fixed.

**Comment by thinkyhead** [comment]
Perhaps you can configure your editor to simply respect the existing encoding of the file and tell it to make sure to preserve it on save…?

**Comment by Roxy-3D** [comment]
> Perhaps you can configure your editor to simply respect the existing encoding of the file and tell it to make sure to preserve it on save…?

I thought I was doing good to get Vim to treat the file as UTF-8.

**Comment by psavva** [comment]
I guess i can close this issue @Roxy3D ?

**Comment by Roxy-3D** [comment]
I don't know?  Does something have to be edited?

On Sat, Feb 18, 2017 at 10:21 PM, Panayiotis Savva <notifications@github.com
