### ISSUE TITLE
NOZZLE_CLEAN_FEATURE not hardcoded

### ISSUE THREAD

**Issue by universam1** [MarlinFirmware/Marlin#4706]
Thanks for implementing NOZZLE_CLEAN_FEATURE which is a great feature!

My only concern is the need to flash the FW every time I change the sponge / brush. So I'm wondering would one of these ideas be possible:
1. relative moves
   I move my head to an absolute start position via startup script to the exact edge of the sponge with "G1 X Y Z" and then initiate "G12 P2" that does the predefined **relative** moves?
   This would give me at least the freedom to change the Z and or calibrate the position without flashing.
2. position paramter for start and end position
   Supply the start and end position and let Marlin calculate the path itself. 
   Like "G12 P3 S100,100 E110,110" or similar. I guess the parsing would be the problem, or introduce more switches.

Thank you for considering this!

**Comment by thinkyhead** [comment]
You might say that `NOZZLE_CLEAN_FEATURE` is a reference-implementation for vendors to start with, more than intended to be one-size-fits-all.
