### ISSUE TITLE
What does  "F" represent specifically in gcode?

### ISSUE THREAD

**Issue by lizlovesspurs** [MarlinFirmware/Marlin#4712]
As  is  known  to  all ,  "F"  means  feedrate  or  speed in gcode.  In  3d  printing plane motion ,  there  are  three   kinds  of   velocity,  including   x-stepper  velocity,  y-stepper  velocity  and   x-y  resultant  velocity.
So   which  does  "F" represent  in  the  three   kinds  of   velocity ? Does  it  represent  the  magnitude of the x-y  resultant  velocity  in  Marlin  source  code?  I  also want  to  know  the  mathematical relationship  between  F   value   with  the  e-stepper  speed  in  Marlin  source  code.

**Comment by Blue-Marlin** [comment]
"F" is the **maximum** speed for a move in the 4 dimensional room (XYZE).
This speed is cut down to the individual axis max limits (DEFAULT_MAX_FEEDRATE).
If "F" can be reached also depends on, if the move is long enough - the acceleration is high enough, and how big the speed difference to the previous/following move is.

For details see planner.cpp Planner::buffer_line(...)

**Comment by thinkyhead** [comment]
Note that it represents feedrate in **millimeters per minute**.

> relationship between F value with the e-stepper speed

If your E stepper is configured with 16x microstepping and a typical 200 step motor, then you get 3200 steps per revolution. If your extruder has a gear with a circumference of 20mm then the extruder will push close to 20mm of filament per full revolution. Thus, 3200÷20 or 160 steps per mm.

**Comment by Roxy-3D** [comment]
> If your extruder has a gear with a diameter of 20mm then the extruder will push 20mm of filament per full revolution. 

I think you meant to say:

If your extruder has a gear with a circumference of 20mm then the extruder will push 20mm of filament per full revolution.

**Comment by thinkyhead** [comment]
Yes, sorry, senescence is setting in.

**Comment by Roxy-3D** [comment]
I had to look up that word.  I didn't know what it meant.   :)

**Comment by lizlovesspurs** [comment]
@Blue-Marlin   Thank   you  for   your  answer!  As  you  mentioned  before,  the  4  dimensional  Bresenham algorithm  is  the  core  of  Marlin. However,  I  only  found  some  introduction  about  2  dimensional  Bresenham  algorithm in  the  Internet .  Could   you  please  give  me   a  chained address  of  introduction  about  4  dimensional  Bresenham algorithm? I  think  it  will  help  me   understand how  Marlin  controls   stepper  movement   better.

**Comment by thinkyhead** [comment]
For the Bresenham algorithm 4 dimensions (or axes) is exactly the same as 2. You just use 4 counters, each one adding on its own length on each iteration. And all of them use the same value –the negative largest distance– as their reset (i.e., threshold).

``` cpp
/**
 * Bresenham for a single value
 */
class Bresenham {
  private:
    long divisor, dividend, count[1], ticker, invocations;

  public:

    Bresenham() { Bresenham(1, 1, 0); }

    Bresenham(const long &inDividend, const long &inDivisor, const long &inTicker=0) {
      invocations = 0;
      divisor = inDivisor;
      dividend = inDividend;
      count[0] = -((inDividend + 1) >> 1);
      ticker = inTicker;
    }

    bool tick() {
      invocations++;
      count[0] += dividend;
      bool over = (count[0] >= 0);
      if (over) {
        ticker++;
        count[0] -= divisor;
      }
      // report();
      return over;
    }

    long operator++() {
      tick();
      return ticker;
    }

    void report() { cout << "count[0]: " << count[0] << ", ticker: " << ticker << " / " << invocations << ENDL; }
};

Bresenham x_move(77, 77);
Bresenham y_move(20, 77);
Bresenham z_move(34, 77);
Bresenham e_move(12, 77);

// Trace a line in 4 dimensions
for (int i = 0; i < 77; i++) {
  if (x_move.tick()) x_move.report(); // will move every time
  if (y_move.tick()) y_move.report(); // will move 20 times
  if (z_move.tick()) z_move.report(); // will move 34 times
  if (e_move.tick()) e_move.report(); // will move 12 times
}
```

**Comment by lizlovesspurs** [comment]
@thinkyhead   As  you  said,  4  demension  Bresenham  algorithm   seems   like  multiaxis  DDA   interpolation  algorithm.  Can  I   understand  4  demension  Bresenham  algorithm   in  this  way?

**Comment by thinkyhead** [comment]
It is best understood in its own terms.
Using the class I wrote above, you can experiment with it all day.

**Comment by Blue-Marlin** [comment]
Bresenham and DDA are relative similar algorithms (originally) for 2 dimensional line drawing on raster displays. The advantage of Bresanham over DDA is - it's fast - it needs integer calculations only.

**Comment by amrithmmh** [comment]
thanks @thinkyhead
