### ISSUE TITLE
Different steps for dual extruder

### ISSUE THREAD

**Issue by renzaaa** [MarlinFirmware/Marlin#4729]
E0 is correct steps, but E1 is not. How I can change steps for E1 on Marlin?

**Comment by Blue-Marlin** [comment]
You cant. Steps/mm have to be the same for all extruders.

A possible workaround is to set the steps with `M92 E123` after every tool-change.

**Comment by ahsnuet09** [comment]
Now the latest Marlin [version](https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x) has made it possible. You can set distinct E parameters for up-to  5 extruders. Don't forget to uncomment [DISTINCT_E_FACTORS](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/Configuration.h#L505)
