### ISSUE TITLE
Mesh leveling question.

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#4740]
I've been playing around with Mesh leveling in RC7 Bugfix for the past couple of days. I've managed to get it working as advertised. However, I noticed that G29 S4 provides for setting the Z offset and M851 also provides for setting the Z offset. Is there any relation between these two ways of setting the Z offset? Are they additive? Should one use G29 S4 over M851 when using Mesh leveling? It should be noted that the firmware is configured with a 0 Z offset and that I like to fine tune the offset prior to each print. Previously, with ABL, I would do that with M851. EEPROM is enabled and I do an M500 after each change. (And an M502/M500 when uploading changed firmware.)

Thanks.

**Comment by Roxy-3D** [comment]
These are separate entities.   The M851 controls the Z displacement of the probe from the nozzle.   The G29 S4 controls the height of the Mesh from the nozzle.  There is a lot of similarity to them but they are separate.   

In the event you do not have a Z-Probe, only the G29 S4 adjustment would be available to you.

You might want to experiment and turn on the Z-Baby-Stepping.   That is real nice for fine tuning your height.
