### ISSUE TITLE
Adding a print at the end of the print head in place and platform down gcode.

### ISSUE THREAD

**Issue by jackshi618** [MarlinFirmware/Marlin#4750]
How to increase

**Comment by thinkyhead** [comment]
I hope you have some dressing for that salad.

**Comment by jackshi618** [comment]
"G1 X0 Y0 Z200 F8000"
By user-defined

**Comment by Blue-Marlin** [comment]
Use the slicers end script. Marlin can not detect if a g-code script has ended when send over the USB.

**Comment by jackshi618** [comment]
Adding a feature, or add a command

**Comment by Blue-Marlin** [comment]
Adding "G1 X0 Y0 Z200 F8000" in you slicers or g-code senders 'end script'.
I really never heard about features in the endscript.

**Comment by boelle** [comment]
@jackshi618 

Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/ 
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

the reason is that it' so weak formulated that it could be anything, second its posted the wrong place
