### ISSUE TITLE
Stop print not working after pause print in RC7

### ISSUE THREAD

**Issue by condac** [MarlinFirmware/Marlin#4751]
RC7 commit d97dc102
When pressing pause print in the LCD menu, the printer pauses. But when trying to press stop print when in pause it doesn't stop and show the print from sd option again. 

Also pressing stop during print is useless because it often runs away with the steppers and move x y outside it limits. I always press pause before stop to avoid this, and it looses where on the x and y it is. ( this runaway and loosing where it is have been issue since 3 years back...)

configuration: include reprapdiscount lcd and include sd support, ramps1.4 and changed steps per mm everything else default.

**Comment by jackshi618** [comment]
Pause when you can remove the print head? Or a custom implementation of a custom gcode

**Comment by thinkyhead** [comment]
> stop print when in pause it doesn't stop

Try `RCBugFix`. This issue should now be fixed with #4610

> this runaway and losing where it is 

I tried to address this with #3939. I don't think it runs away or loses position any more.
