### ISSUE TITLE
G1, M92, then G1 fails

### ISSUE THREAD

**Issue by CampbellFabrications** [MarlinFirmware/Marlin#4757]
RCBugFix, Running commands via Cura to an Ultimaker.
Found a bug while calibrating the extruder steps.
These are the commands i issued, and the steps to reproduce the bug:

``` gcode
M302 S0  ; allow cold extrusion from startup
G1 E200  ; extrude 200mm
M92 E800 ; set extruder steps to arbritrary value (800, 780, 640 used).
G1 E200  ; THIS command fails does nothing, no extrusion, no errors.
```

**Comment by Blue-Marlin** [comment]
@SydneyMakers
You either need G1 E400 or relative mode (G91) to make it work.
A move from 200 to 200 is 0mm long.
