### ISSUE TITLE
UBL on corexy testing issues

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#4783]
@Roxy-3D im trying to configure UBL on my CoreXY machine, probe is fixed type. but when i enable just the fixed probe.. it says cant have more then one type. 

i have attact my configuration.h file incase your curious

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/465949/Configuration.txt)

**Comment by Roxy-3D** [comment]
This may not be a CoreXY issue.   My guess is that if it is complaining about probe types, it doesn't like fixed probes in general.   I'll try to take a look at it as soon as I can.   But it will be at least a few days before I can get setup to look at it.   (I'm in the middle of a debug session and can't change things right now.)

**Comment by MrExo3D** [comment]
no worries i will load up RC7 Bugfix for now.

**Comment by thinkyhead** [comment]
@adamfilip Your problem is this:

``` cpp
#define Z_ENDSTOP_SERVO_NR 0
```

You shouldn't define a Z endstop servo unless you have a servo-based Z probe.
