### ISSUE TITLE
build error when enable Z_SAFE_HOMING

### ISSUE THREAD

**Issue by prophetmaster** [MarlinFirmware/Marlin#4788]
```
ccldbfoc.ltrans0.ltrans.o*: In function process_next_command()
ccldbfoc.ltrans0.o*: (.text+0xede): relocation truncated to fit: R_AVR_7_PCREL against no symbol

collect2.exe*: error: ld returned 1 exit status
```

Error compiling for board Arduino/Genuino Mega w/ ATmega2560 (Mega 2560)

**Comment by thinkyhead** [comment]
What version of Arduino IDE is that? It seems to be more an internal compiler error rather than a code error.

**Comment by prophetmaster** [comment]
Latest IDE 1.6.11

**Comment by thinkyhead** [comment]
I presume you're testing `RCBugFix`, yes?
Please post your configuration. I haven't seen this error.

**Comment by prophetmaster** [comment]
the latest release candidate 1.1.0-RC7

**Comment by thinkyhead** [comment]
Great. When you have a chance, please post your configuration.

**Comment by thinkyhead** [comment]
Building on Linux?

**Comment by thinkyhead** [comment]
It seems to be a spurious internal compiler problem. Try moving the `process_next_command()` function to the end of `Marlin_main.cpp`, or shuffling other functions around. Eventually the compiler will magically be able to compile it without any other changes to the code. I recommend you start with the current `RCBugFix`, where we have already shuffled some functions around.

**Comment by alejandro-anv** [comment]
Thank you: Just moved the declaration of codenum:

uint16_t codenum = 0; // define ahead of goto

a few lines up and it compiled ok.

**Comment by alejandro-anv** [comment]
I am having the same problem but only with this config:
[config_anv.zip](https://github.com/MarlinFirmware/Marlin/files/480807/config_anv.zip)

**Comment by thinkyhead** [comment]
The problem seems to be nonexistent (so far) with the current `RCBugFix` so switch to that and see if it works for you.

**Comment by alejandro-anv** [comment]
Where do I find RCBugFix? Is it in MarlinDev?

**Comment by ghost** [comment]
Here it is.
MarlinFirmware/Marlin at RCBugFix
https://github.com/MarlinFirmware/Marlin/tree/RCBugFix

**Comment by thinkyhead** [comment]
See also #4808. The compiler / linker are just trying to be too clever and failing.

**Comment by boelle** [comment]
since this is invalid and a dublicate why not close?
