### ISSUE TITLE
Man Mesh Levelling issue

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#4790]
My printers homes on Y max
when I try and use Manual Mesh leveling it tries to go beyond the Y Max endstop and rams the gantry into the limit.

is there a way to switch the direction manual mesh levelling starts to probe?

**Comment by thinkyhead** [comment]
That would have to be a bug someplace. MBL (`G29 S1`) is supposed to move to the first point on the bed by way of its XY coordinate. It shouldn't be doing a relative Y move off the back of the bed.

**Comment by MrExo3D** [comment]
@Roxy-3D tried with UBL and its basically same issue.. since it homes to Y Max it just sits there at Y max
but it should move to Y min first.

**Comment by epatel** [comment]
@adamfilip I can have a look-see later today, see if there is anything that stands out.

**Comment by Roxy-3D** [comment]
>  tried with UBL and its basically same issue.. since it homes to Y Max it just sits there at Y max
> but it should move to Y min first.

I think what this implies is this issue was in the RC-7 code base as far back as July 4th, 2016.  Because this problem really is outside of the bed leveling portion of the code base.   And that is the date I forked.   If the fix is not too invasive, I'll bring it over to the UBL branch when it is figured out.

**Comment by thinkyhead** [comment]
@adamfilip If you do a simple G1 to a point after G28 all is normal?

**Comment by MrExo3D** [comment]
If I do a G28 then a G1 X75 Y75 it moves to the correct position

**Comment by MrExo3D** [comment]
Hmm disregard my last comment. Ran into a weird issue. Will elaborate soon

**Comment by epatel** [comment]
@adamfilip Have been looking at the manual parts in `ultralcd.cpp`. Nothing pops out. Though, have you set a "home_offset" (done a `M206`)? It might even have snuck into the EEPROM (do a `M503` and look for `M206`)?

**Comment by MrExo3D** [comment]
I have uploaded a video to demonstrate what im experiencing.

[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/468651/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/468652/Configuration.txt)
Video Link. [https://youtu.be/G3-TqGbnxSQ](url)

Using Simplify
3d control panel. after it Homes with a G28 X0 Y0 Z0
I can issue +Y100 or +X100 moves and it moves properly
If I send a G1 X150 Y150 it rams into the endstops.

**Comment by epatel** [comment]
@adamfilip Looks like Y is traveling the wrong direction then I imagine, shouldn't Y+100 go "out" and Y-100 be back into the bed? (Endstop at Max Y?) But that last move, strange...

**Comment by MrExo3D** [comment]
Noticed that in simplify3d I had y axis inverted.

I will try and reverse Y direction on marlin and see if that corrects things

**Comment by MrExo3D** [comment]
after i turned off the Simpliy3d Y invert setting, I Messed around with Stepper wire orientation and marlin settings and managed to get it to move properly again. but it still doesnt home properly.

when I have Y_HOME_DIR 1 it tried to home away from the Y Max endstop
when I have Y_Home_DIR -1 it doesnt move at all, as if the endstop was already triggered. but its not (when checked with M119,)
also my Y Min endstop is disabled.

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/468898/Configuration.txt)

**Comment by thinkyhead** [comment]
> managed to get it to move properly again

Does that mean G29 now works?

I'm aware that there's an issue ongoing with endstops on CORE setups, but haven't yet worked it out. The general issue seems to be that endstops are checked on the basis of raw motor direction, but with CORE systems we can't rely on that. We have to look at the combined motor directions, and possibly their relative rates of motion, to determine which direction each axis is actually moving.

> when I have Y_HOME_DIR 1 it tried to home away from the Y Max endstop

Hmm, even with the endstop issues, it should still home in the proper direction.

**Comment by thinkyhead** [comment]
Are you still using `RC6` for your testing? We're not going to be able to debug against that version. Please use `RCBugFix` so we can test against the latest code. You may or may not experience the same issues, because there have been a slew of patches since `RC6`, including several related to CoreXY.

**Comment by MrExo3D** [comment]
I will switch back to Bugfix

**Comment by MrExo3D** [comment]
Ok i switch back to current Bugfix. error i get now is to use "use Y min plug when homing Y to min" but my Y home DIR is -1 so it should be going to max.. not min

is there another place im not seeing that sets... home to Max vs Min?

**Comment by MrExo3D** [comment]
If i set Y Home Dir to 1 , error goes away but it homes in opposite direction.

**Comment by thinkyhead** [comment]
> my Y home DIR is -1 so it should be going to max

No, no, no. That's exactly the opposite of true. **-1 is homing to MIN** (the negative direction).

> If i set Y Home Dir to 1 , error goes away but it homes in opposite direction.

**That's correct** for homing to MAX. Now it sounds like your XY motors are set up backward.

On a CoreXY machine, the two core-axis motors (A and B) need to be wired in the same way and must have the very same "inverting" setting, so that they combine their movements to move the XY axes in the correct direction. Make triply certain that they are wired so that they coordinate properly.

The A motor moves by X + Y.
The B motor moves by X - Y.

### Examples:

```
X10, Y0    = A10 B10
X-10, Y0   = A-10 B-10
X0, Y10    = A10 B-10
X0, Y-10   = A-10 B10
X10, Y10   = A20 B0
X-10, Y-10 = A-20 B0
X10, Y-10   = A0 B20
X-10, Y10 = A0 B-20
```

### Tests:

Assuming that X0 Y0 is at the left-front of the bed…
- Move X+ (E, or right). Motors should both rotate in the positive direction.
- Move X- (W, or left). Motors should both rotate in the negative direction.
- Move Y+ (N, towards back of bed). A should rotate positive, B should rotate negative.
- Move Y- (S, towards front of bed). A should rotate negative, B should rotate positive.
- Move X+ and Y+ (NE). A should rotate in the positive direction, B not at all.
- Move X- and Y- (SW). A should rotate in the negative direction, B not at all.
- Move X+, Y- (SE). B should rotate in the positive direction, A not at all.
- Move X-, Y+ (NW). B should rotate in the negative direction, A not at all.

**Comment by MrExo3D** [comment]
My machine has one stepper upside down. As I run stacked belts.  One Above and one below the gantry. Right now motion moves properly when I send job moves with control panel

Why does it give me an error for y min if it tries to home for your max?

**Comment by MrExo3D** [comment]
Maybe I should just add the y min endstop and save everyone the hassle lol

**Comment by thinkyhead** [comment]
> Why does it give me an error for y min if it tries to home for your max?

If you are homing Y to a MAX endstop (with `Y_HOME_DIR 1`) then you should have `USE_YMAX_PLUG` enabled and your endstop plugged into that port.

**Comment by MrExo3D** [comment]
Thats what im doing

Y Max endstop is plugged in and enabled
Y Min is disabled

``` cpp
#define USE_XMIN_PLUG
//#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
//#define USE_XMAX_PLUG
#define USE_YMAX_PLUG
//#define USE_ZMAX_PLUG
```

**Comment by thinkyhead** [comment]
> Why does it give me an error for y min if it tries to home for your max?
> Thats what im doing

You said:

> error i get now is to use "use Y min plug when homing Y to min" 

If that error is appearing then you must still have `Y_HOME_DIR` set to -1 (MIN).
The sanity check goes like this:

``` cpp
  #elif Y_HOME_DIR < 0 && DISABLED(USE_YMIN_PLUG)
    #error "Enable USE_YMIN_PLUG when homing Y to MIN."
```

**Comment by MrExo3D** [comment]
Sorry, ive tried so many combination of settings and stepper wire orientations that ive lost track.
Yes when I set Y_Home_DIR to -1 it give me the compile error, when I set Y_Home_DIR 1 it tried to home away from the Y Max endstop

**Comment by MrExo3D** [comment]
I am installing a Y Min endstop to simplify things.

**Comment by MrExo3D** [comment]
I think part of my problem was that I had the orientation of the Y Axis mixed up in my head.
I assumed the back of the bed was the Y Max and the front was the Y Min
but based on this image the back is the MIN and the front is the MAX
![xyz_machine_type](https://cloud.githubusercontent.com/assets/10480179/18518798/791a11e8-7a6f-11e6-951b-46407b9c8b09.jpg)

**Comment by Blue-Marlin** [comment]
As soon as the bed is moving, not the nozzle, it's going to be complicated - for most of us.
The coordinate system must be right handed to work!

**Comment by epatel** [comment]
@adamfilip well I think the image is fine. It is just pointing out the location for the end stops, y min trigger when the front of the bed is under the nozzle. Let me add that your corexy looks very nice. Could fancy one myself :)

**Comment by MrExo3D** [comment]
Here is how my machine currently is setup. 
its a fixed bed CoreXY configuration

![corexy-axis](https://cloud.githubusercontent.com/assets/10480179/18520226/f0cb1fca-7a74-11e6-96ba-ea4f95b0d5a9.jpg)

**Comment by MrExo3D** [comment]
> Let me add that your corexy looks very nice. Could fancy one myself :)

@epatel Thank you, its been a great project.. but also a money pit! I could have bought a pretty nice premade machine :)

**Comment by thinkyhead** [comment]
> I assumed the back of the bed was the Y Max and the front was the Y Min

I'm extraordinarily relieved that you sorted it out.
