### ISSUE TITLE
Feature request: Option to display feedrate instead of XY values during printing

### ISSUE THREAD

**Issue by Bendimon** [MarlinFirmware/Marlin#4800]
When I'm printing, I don't need to see XY values on my LCD, they're changing too fast, and I only find useful to see Z values.

On the other hand, It would be useful to me to see what's the programmed feedrate (F) at every moment, to establish the relationship between what i'm seeing and the number, to know what I should change on the slicer.

Perhaps it could be an option in the firmware to determine if the user wants to see XY or F.. only during execution, because in manual mode it's good to see XY values.

**Comment by Kaibob2** [comment]
Good idea. I would also prefer to have a feedback of the current feedrates, but I think the update frequency of the display is too low. It would be as laggy as the XY positions.

**Comment by thinkyhead** [comment]
We have several outstanding requests to provide alternative Info Screen display options. I like the layout of the Info Screen in the Prusa i3 MK2 branch. So perhaps we will adopt that.

**Comment by boelle** [comment]
since this is a duplicate why not close?
