### ISSUE TITLE
AUTO BED LEVELING FEATURE not working with latest RCBugFix

### ISSUE THREAD

**Issue by renzaaa** [MarlinFirmware/Marlin#4802]
Not working with AUTO_BED_LEVELING_GRID_POINTS 2 (probing 2 points and gantry crash to the x-max side).
Not working with AUTO_BED_LEVELING_GRID_POINTS 3 (probing 6 points and gantry crash to the x-max side).

**Comment by Mugga6315** [comment]
Same for me, like already posted here:
https://github.com/MarlinFirmware/Marlin/issues/4662#issuecomment-246774815

**Comment by thinkyhead** [comment]
@renzaaa Sorry about that! I've been doing a lot of patches in the last couple days and probably mistyped something. Can you post your configuration so I can test with exactly your settings? Thanks!

**Comment by thinkyhead** [comment]
See if this change to line 3454 of `Marlin_main.cpp` makes any difference:

``` diff
-       for (uint8_t xCount = xStart; xCount != xStop; xCount += xInc) {
+       for (int8_t xCount = xStart; xCount != xStop; xCount += xInc) {
```

**Comment by thinkyhead** [comment]
Also… line 3434…

``` diff
-     uint8_t zig = auto_bed_leveling_grid_points & 1; //always end at [RIGHT_PROBE_BED_POSITION, BACK_PROBE_BED_POSITION]
+     bool zig = auto_bed_leveling_grid_points & 1; //always end at [RIGHT_PROBE_BED_POSITION, BACK_PROBE_BED_POSITION]
```

**Comment by Mugga6315** [comment]
Works with the changes! Thanks.
But the other issue I referred to, in my post stays (x-axis seems to be straight, but y-axis movement is higher at the back and almost crashing into bed in the front)

**Comment by thinkyhead** [comment]
@Mugga6315 See my earlier reply on that issue.

**Comment by renzaaa** [comment]
@thinkyhead Working now. Thanks.
