### ISSUE TITLE
Changed homing behavior/endstop requirements - Issue when using not endstops at all

### ISSUE THREAD

**Issue by Ianmcmill** [MarlinFirmware/Marlin#4831]
Hello,
I am currently trying to use **1.1.0RCBugfix (from RC7)** and I'm having issues using an inductive probe with auto-bed leveling but without XY endstops. I can't even get to the actual probing steps.

My prusa i3 has no endstops for XYZ. In RC5 I manually moved the head to 0,0 and always parked the head at Z 10. After powering RAMPS I entered G92 X0Y0Z10 and started printing. This worked for three years without problems.

I recently got an inductive probe and installed it and upgraded from RC5 to RC7 because I thought newer is always better.
I took the old configuration.h from RC5 and applied the proven values over to RC7 considering depreciated commands.
Compiles fine but without hardware endstops and a homing cycle (G28) I cannot use G29.
Software endstops and the probe trigger correctly when testing with M119. The inductive probe triggers correctly when testing with a piece of aluminum.
### Problem 1:

After powering Ramps and connecting via Repetier host I enter this to test movement:
G1Z10
It moves the head to Z10 but after that no G1 command works.
If I send G0 Z0 it moves to Z0 but after that no G0 commend works.
Movement with G0/1 on the X/Y plane works like intended.
M119 says all _min and _probe endstops are open.
Only if I send G92 X0Y0Z0, the G1/0 commands are unlocked and work but then only work one single time like described above and I have to send G92X0Y0Z0 again.

EDIT: Using the Home Z button in Repetier and a piece of aluminium under the probe works as intended i.e. moving down, stopping at aluminum and raising Z.

Is this intended? If so, why?
I don't get it...
### 2nd issue:

```
// If you want to enable the Z probe pin, but disable its use, uncomment the line below.
// This only affects a Z probe endstop if you have separate Z min endstop as well and have
// activated Z_MIN_PROBE_ENDSTOP below. If you are using the Z Min endstop on your Z probe,
// this has no effect.
#define DISABLE_Z_MIN_PROBE_ENDSTOP
```

I don't get this either? What does this mean? Why should I want to enable z probe pin but disable its use?

<details><summary>

This is the endstop and probe configuration</summary>

```
//===========================================================================
//============================== Endstop Settings ===========================
//===========================================================================

// @section homing

// Specify here all the endstop connectors that are connected to any endstop or probe.
// Almost all printers will be using one per axis. Probes will use one or more of the
// extra connectors. Leave undefined any used for non-endstop and non-probe purposes.
#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
//#define USE_XMAX_PLUG
//#define USE_YMAX_PLUG
//#define USE_ZMAX_PLUG

// coarse Endstop Settings
//#define ENDSTOPPULLUPS // Comment this out (using // at the start of the line) to disable the endstop pullup resistors

#if DISABLED(ENDSTOPPULLUPS)
  // fine endstop settings: Individual pullups. will be ignored if ENDSTOPPULLUPS is defined
  //#define ENDSTOPPULLUP_XMAX
  //#define ENDSTOPPULLUP_YMAX
  //#define ENDSTOPPULLUP_ZMAX
  //#define ENDSTOPPULLUP_XMIN
  //#define ENDSTOPPULLUP_YMIN
  //#define ENDSTOPPULLUP_ZMIN
  //#define ENDSTOPPULLUP_ZMIN_PROBE
#endif

// Mechanical endstop with COM to ground and NC to Signal uses "false" here (most common setup).
#define X_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
#define X_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Y_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MIN_PROBE_ENDSTOP_INVERTING true // set to true to invert the logic of the endstop.
```

Z Probe Options:

```
//===========================================================================
//============================= Z Probe Options =============================
//===========================================================================
// @section probes

//
// Probe Type
// Probes are sensors/switches that are activated / deactivated before/after use.
//
// Allen Key Probes, Servo Probes, Z-Sled Probes, FIX_MOUNTED_PROBE, etc.
// You must activate one of these to use AUTO_BED_LEVELING_FEATURE below.
//
// Use M851 to set the Z probe vertical offset from the nozzle. Store with M500.
//

// A Fix-Mounted Probe either doesn't deploy or needs manual deployment.
// For example an inductive probe, or a setup that uses the nozzle to probe.
// An inductive probe must be deactivated to go below
// its trigger-point if hardware endstops are active.
#define FIX_MOUNTED_PROBE

// The BLTouch probe emulates a servo probe.
//#define BLTOUCH

// Z Servo Probe, such as an endstop switch on a rotating arm.
//#define Z_ENDSTOP_SERVO_NR 0
//#define Z_SERVO_ANGLES {70,0} // Z Servo Deploy and Stow angles

// Enable if you have a Z probe mounted on a sled like those designed by Charles Bell.
//#define Z_PROBE_SLED
//#define SLED_DOCKING_OFFSET 5 // The extra distance the X axis must travel to pickup the sled. 0 should be fine but you can push it further if you'd like.

// Z Probe to nozzle (X,Y) offset, relative to (0, 0).
// X and Y offsets must be integers.
//
// In the following example the X and Y offsets are both positive:
// #define X_PROBE_OFFSET_FROM_EXTRUDER 10
// #define Y_PROBE_OFFSET_FROM_EXTRUDER 10
//
//    +-- BACK ---+
//    |           |
//  L |    (+) P  | R <-- probe (20,20)
//  E |           | I
//  F | (-) N (+) | G <-- nozzle (10,10)
//  T |           | H
//    |    (-)    | T
//    |           |
//    O-- FRONT --+
//  (0,0)
#define X_PROBE_OFFSET_FROM_EXTRUDER -40  // X offset: -left  +right  [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER 17  // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER 0   // Z offset: -below +above  [the nozzle]

// X and Y axis travel speed (mm/m) between probes
#define XY_PROBE_SPEED 8000
// Speed for the first approach when double-probing (with PROBE_DOUBLE_TOUCH)
#define Z_PROBE_SPEED_FAST HOMING_FEEDRATE_Z
// Speed for the "accurate" probe of each point
#define Z_PROBE_SPEED_SLOW (Z_PROBE_SPEED_FAST / 2)
// Use double touch for probing
//#define PROBE_DOUBLE_TOUCH

//
// Allen Key Probe is defined in the Delta example configurations.
//

// Enable Z_MIN_PROBE_ENDSTOP to use _both_ a Z Probe and a Z-min-endstop on the same machine.
// With this option the Z_MIN_PROBE_PIN will only be used for probing, never for homing.
//
// *** PLEASE READ ALL INSTRUCTIONS BELOW FOR SAFETY! ***
//
// To continue using the Z-min-endstop for homing, be sure to disable Z_SAFE_HOMING.
// Example: To park the head outside the bed area when homing with G28.
//
// To use a separate Z probe, your board must define a Z_MIN_PROBE_PIN.
//
// For a servo-based Z probe, you must set up servo support below, including
// NUM_SERVOS, Z_ENDSTOP_SERVO_NR and Z_SERVO_ANGLES.
//
// - RAMPS 1.3/1.4 boards may be able to use the 5V, GND, and Aux4->D32 pin.
// - Use 5V for powered (usu. inductive) sensors.
// - Otherwise connect:
//   - normally-closed switches to GND and D32.
//   - normally-open switches to 5V and D32.
//
// Normally-closed switches are advised and are the default.
//
// The Z_MIN_PROBE_PIN sets the Arduino pin to use. (See your board's pins file.)
// Since the RAMPS Aux4->D32 pin maps directly to the Arduino D32 pin, D32 is the
// default pin for all RAMPS-based boards. Some other boards map differently.
// To set or change the pin for your board, edit the appropriate pins_XXXXX.h file.
//
// WARNING:
// Setting the wrong pin may have unexpected and potentially disastrous consequences.
// Use with caution and do your homework.
//
#define Z_MIN_PROBE_ENDSTOP

// Enable Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN to use the Z_MIN_PIN for your Z_MIN_PROBE.
// The Z_MIN_PIN will then be used for both Z-homing and probing.
//#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN

// To use a probe you must enable one of the two options above!

// This option disables the use of the Z_MIN_PROBE_PIN
// To enable the Z probe pin but disable its use, uncomment the line below. This only affects a
// Z probe switch if you have a separate Z min endstop also and have activated Z_MIN_PROBE_ENDSTOP above.
// If you're using the Z MIN endstop connector for your Z probe, this has no effect.
//#define DISABLE_Z_MIN_PROBE_ENDSTOP

// Enable Z Probe Repeatability test to see how accurate your probe is
//#define Z_MIN_PROBE_REPEATABILITY_TEST

//
// Minimum heights for the probe to deploy/stow and travel.
// These values specify the distance from the NOZZLE to the BED.
//
#define Z_PROBE_DEPLOY_HEIGHT 15 // Z position for the probe to deploy/stow
#define Z_PROBE_TRAVEL_HEIGHT  5 // Z position for travel between points

//
// For M851 give a range for adjusting the Z probe offset
//
#define Z_PROBE_OFFSET_RANGE_MIN -20
#define Z_PROBE_OFFSET_RANGE_MAX 20

// For Inverting Stepper Enable Pins (Active Low) use 0, Non Inverting (Active High) use 1
// :{0:'Low',1:'High'}
#define X_ENABLE_ON 0
#define Y_ENABLE_ON 0
#define Z_ENABLE_ON 0
#define E_ENABLE_ON 0 // For all extruders

// Disables axis stepper immediately when it's not being used.
// WARNING: When motors turn off there is a chance of losing position accuracy!
#define DISABLE_X false
#define DISABLE_Y false
#define DISABLE_Z false
// Warn on display about possibly reduced accuracy
//#define DISABLE_REDUCED_ACCURACY_WARNING

// @section extruder

#define DISABLE_E false // For all extruders
#define DISABLE_INACTIVE_EXTRUDER true //disable only inactive extruders and keep active extruder enabled

// @section machine

// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
#define INVERT_X_DIR false
#define INVERT_Y_DIR false
#define INVERT_Z_DIR true

// @section extruder

// For direct drive extruder v9 set to true, for geared extruder set to false.
#define INVERT_E0_DIR true
#define INVERT_E1_DIR false
#define INVERT_E2_DIR false
#define INVERT_E3_DIR false

// @section homing

//#define Z_HOMING_HEIGHT 4  // (in mm) Minimal z height before homing (G28) for Z clearance above the bed, clamps, ...
                             // Be sure you have this distance over your Z_MAX_POS in case.

// ENDSTOP SETTINGS:
// Sets direction of endstops when homing; 1=MAX, -1=MIN
// :[-1,1]
#define X_HOME_DIR -1
#define Y_HOME_DIR -1
#define Z_HOME_DIR -1

#define min_software_endstops false // If true, axis won't move to coordinates less than HOME_POS.
#define max_software_endstops false  // If true, axis won't move to coordinates greater than the defined lengths below.

// @section machine

// Travel limits after homing (units are in mm)
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0
#define X_MAX_POS 205
#define Y_MAX_POS 205
```

</details>

**Comment by Ianmcmill** [comment]
Sorry. After some restarts the G0/1 commands seem to work now. Strange. 

Anyways. How can I perfom a G29 without a G28 before? Do I need to work with G30 instead?

**Comment by thinkyhead** [comment]
> How can I perform a G29 without a G28 before?

You can't. `G29` does movements to specific points on the bed, and therefore needs to know where the carriage is located. And that's what `G28` establishes.

**Comment by Ianmcmill** [comment]
So Z probe without XY endstop is not possible? A simple (and loved) G92 X0 Y0 does not work?

**Comment by thinkyhead** [comment]
How do you establish XY on your machine without endstops?

**Comment by Ianmcmill** [comment]
edited:
Manually positioning at (roughly) 0,0. I don't need to have the exact 0,0 and I cannot imagine any situation where you need it to be at the endstop defined 0,0. In fact if I would need that extra 4mm to print I could boldly move the printhead where no endstop has gone before. Reseting or G92 X0 Y0 the ramps. Worked for three years now. Actually I never understood why one would want min XY endstops. It is maybe a bit more convenient but IMHO it does not justify the setup/coding works. MAX endstops I could understand but then again you should know your machine and check what you are printing. When I close down my printer after printing I remove the part, send G0 X0 Y0 Z10 and disconnect. When I start up the next day I send G92 Z10 and start printing. I am getting perfect first layers (manually tuning print bed with paper method). I have never printed off the limits. Never had a crash. This endstop stuff just looks cool :)

**Comment by thinkyhead** [comment]
> `DISABLE_Z_MIN_PROBE_ENDSTOP`… I don't get this either? What does this mean? Why should I want to enable z probe pin but disable its use?

This setting is confusing to me too. It's probably going to go away.

**Comment by thinkyhead** [comment]
> Worked for three years now.

Marlin now tracks whether it has been homed with `G28` as a safety feature. It also requires re-homing for some commands if the steppers go to sleep. If you need support for a machine with no endstops, it will need to be added as an optional feature. For the time-being, just add the following to `setup()` in your personal copy:

``` cpp
LOOP_XYZ(i) axis_known_position[i] = axis_homed[i] = true;
```

**Comment by Roxy-3D** [comment]
> > DISABLE_Z_MIN_PROBE_ENDSTOP… I don't get this either? What does this mean? Why should I want to enable z probe pin but disable its use?
> > This setting is confusing to me too. It's probably going to go away.

Can we make it go away prior to establishing an RC-8 base line?  The reason I ask is if this is going to go away, it might be good to have it gone for a little while before we promote RC-8 to be 'Stable'.

**Comment by Ianmcmill** [comment]
Thank you thank you thank you @thinkyhead. This removes the `G28` problem and deals with it just the way I like it.

However I had to change the configuration.h posted in my inital post to the following. I do not understand the difference from these two settings but my gut told me change these:

``` diff
- #define Z_MIN_PROBE_ENDSTOP
+ //#define Z_MIN_PROBE_ENDSTOP
```

``` diff
- //#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
+ #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
```

I also did change:

``` cpp
#define Z_PROBE_DEPLOY_HEIGHT 2 // Z position for the probe to deploy/stow
#define Z_PROBE_TRAVEL_HEIGHT  5 // Z position for travel between points
```

to 2 and 5 from 15 and 5 for speed.

@Roxy-3D an answer to this question is out of my league.

**Comment by thinkyhead** [comment]
> Can we make it go away prior to establishing an RC-8 base line?

I think so. Its intent was to un-define the `Z_MIN_PROBE_PIN` when you also have `Z_MIN_PROBE_ENDSTOP` enabled. But when I enable `DISABLE_Z_MIN_PROBE_ENDSTOP` with `Z_MIN_PROBE_ENDSTOP` there's a sanity-check telling me that `Z_MIN_PROBE_ENDSTOP` requires `Z_MIN_PROBE_PIN`. It seems like old circular weirdness to me. But I will go back through the issues to see how it was explained to me before. Maybe there's some scenario I'm totally missing.

**Comment by thinkyhead** [comment]
> Can we make it go away prior to establishing an RC-8 base line?

@Roxy-3D #4842

**Comment by Ianmcmill** [comment]
I am not sure if I should put this here in the issues or rather some forum as I think this is more of a misunderstanding of the probe configuration then a software issue?

After running the homing cycle with G29 the printhead stops at the last point and moves Z to the height I started the G29 cycle (which is ~ +5mm nozzle <-> bed) (Using grid mode with 3 point).

``` cpp
#define Z_PROBE_OFFSET_FROM_EXTRUDER 0   // Z offset: -below +above  [the nozzle]
...
#define Z_PROBE_DEPLOY_HEIGHT 1 // Z position for the probe to deploy/stow
#define Z_PROBE_TRAVEL_HEIGHT  1 // Z position for travel between points
```

After the probing cycle I get this message:

```
17:44:05.199 : Bed Level Correction Matrix:
17:44:05.203 : +1.000000 +0.000000 +0.000169
17:44:05.203 : +0.000000 +1.000000 -0.000279
17:44:05.203 : -0.000169 +0.000279 +1.000000
```

When sending M114 I get this, which states a strange Z height. i.e. Z -1.00

```
X:189.00 Y:133.00 Z:-1.00 E:0.00 Count X: 18900 Y:13300 Z:-4021
```

Is this supposed to be like this?

**Comment by thinkyhead** [comment]
@Ianmcmill Are you sure the `M851` setting is also zero?
And… Surely you don't want a probe Z offset of zero…?

Also, I'm not sure how good the 3-point leveling is, in general. Or, right at the moment.

Are you also using `Z_SAFE_HOMING`? (It's meant for when you use the probe to home Z in `G28`, but it can also be used with a regular Z min endstop if that's preferred.)

**Comment by thinkyhead** [comment]
The easiest way to see what's happening is to enable `DEBUG_LEVELING_FEATURE` and issue `M111 S247` before you do `G28` and `G29`. From the detailed log output it should be a simple matter to uncover the issue.

**Comment by Ianmcmill** [comment]
Grave digging here... sorry.
does this still work in 1.1.1?:
`LOOP_XYZ(i) axis_known_position[i] = axis_homed[i] = true;`

EDIT: I rebuilt my prusa to a p3steel and got rid of the z probe and the z-axis-wearing auto-bed leveling.
I don't want to go into detail and bore you, I just want endstop to be gone. 
I don't need homing, I don't need bed leveling.
I don't know if I could simply hack this in: https://github.com/MarlinFirmware/Marlin/issues/5909#issuecomment-282901701
I am no coder. I just don't want endstops. Because no one tells me when to stop. This is a free country.
