### ISSUE TITLE
Error 'DIODIO52_DDR' was not declared in this scope with MAX6675

### ISSUE THREAD

**Issue by korpx** [MarlinFirmware/Marlin#4858]
Compiling Marlin with “Latest commit d97dc10  on Aug 4” with E0 temp sensor -2 (MAX6675) on RAMPS1.4 FSB I get the error 'DIODIO52_DDR' was not declared in this scope

I am using Arduino version 1.6.11

steps to reproduce:
git clone https://github.com/MarlinFirmware/Marlin.git
open marlin.ino
sketch, verify/compile
**result: compiles without errors**

change line 228 from “#define TEMP_SENSOR_0 1” to “#define TEMP_SENSOR_0 -2” to use thermocouple with MAX6675
sketch, verify/compile
**result: error**

The issue look alot like #4533 which was closed by the author, but the error is still present.

The entire error log can be found here;
[errorlog.txt](https://github.com/MarlinFirmware/Marlin/files/483596/errorlog.txt)
[errorlogverbose.txt](https://github.com/MarlinFirmware/Marlin/files/483597/errorlogverbose.txt)

**Comment by thinkyhead** [comment]
You're seeing this problem in 1.1.0-RC7. The error seems to be gone in the latest code, so apparently the bug was fixed. Always test with the latest greatest (currently `RCBugFix`) before reporting an issue. There have been hundreds of changes since August 4.
