### ISSUE TITLE
M600 am I using it wrong?

### ISSUE THREAD

**Issue by Nocturnal42** [MarlinFirmware/Marlin#4866]
So I've been trying to use this feature, I've tried it with two prints, and both times it has been ignored.  I  tried M600 and M600 Z50, manually inserting it into the gcode at the point I wanted to change colours. I'm using RCBugFix from about a week ago.

**Comment by thinkyhead** [comment]
Needed to be enabled in the configuration?

**Comment by Nocturnal42** [comment]
That was the conclusion I came to, after having a look at the code, and why I closed the issue. A mention of that in the "Implemented Codes" section of Marlin_main.cpp might be a good idea.

**Comment by thinkyhead** [comment]
Yes, that is a good idea! #4895
