### ISSUE TITLE
Max temperature possible issue

### ISSUE THREAD

**Issue by gordo3di** [MarlinFirmware/Marlin#4874]
I set the maxtemp for the hotend to 300C in configuration.h

When using the LCD > Control > Temperature function I can only set the max temp to 285C. Not sure if this is a safety feature or bug.

**Comment by KevMags** [comment]
Exceeding maxtemp signals thermal runaway/overheat.  Temp on LCD can only be set to maxtemp -15C.

**Comment by gordo3di** [comment]
Thanks. Sorry for the false bug. We have dialed in our PID so we really only ever exceed set temp by like 2C but I completely understand the rationale. Topic can be closed
