### ISSUE TITLE
Compiling with BLTouch error

### ISSUE THREAD

**Issue by opuscroakus** [MarlinFirmware/Marlin#4892]
In the latest RCBugfix I am getting this error when trying to compile..

Arduino: 1.6.9 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

sketch\Marlin_main.cpp: In function 'void do_homing_move(AxisEnum, float, float)':

Marlin_main.cpp:2202: error: 'where' was not declared in this scope

```
 bool deploy_bltouch = (axis == Z_AXIS && where < 0);

                                          ^
```

exit status 1
'where' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by thinkyhead** [comment]
Thanks! A concurrent PR changed `where` to `distance` before the bltouch code was added. `RCBugFix` is now patched.
