### ISSUE TITLE
1.1.0 RC7 - X-Endstop triggering during movement

### ISSUE THREAD

**Issue by johannesgeh** [MarlinFirmware/Marlin#4897]
I updatet to Marlin 1.1.0 RC7 a few days ago to be able to use Manual Mesh Bed leveling.

Since then every print fails because the X-Endstop gets triggered (without the Extruder even being near it) after about a Minute or so of printing.
This also happens when I move the Extruder manually with the "Move Axis" option on the LCD.
It homes just fine and if I only move it back and forth a few times nothing happens, but when I repeatedly do it at some point the Extruder abruptly stops when moving towards the endstop.

I use ordinary Tact-Switches with the Coarse Pull-Up enabled. I had no problems with this setup in 1.0.2-1.

I hope that this is the right place to write this as I've never used GitHub before.
Thanks!

(I now downgraded to my old 1.0.2-1 and everything functions normally, so the endstop isn't the fault)

**Comment by kmbecker13** [comment]
You should triple check your wiring, very likely that something is loose. I
had the same issue with my printer and it was quite confusing since it was
an intermittent problem.

**Comment by jasoroony** [comment]
The Marlin developers may have removed the "triggered twice" check for endstops.  It is likely you are picking up crosstalk from other wires, which is being rejected by the old Marlin version.  Don't know why they would remove it, but it's changed fairly significantly now and this is their project to do with as they please.

**Comment by thinkyhead** [comment]
The method of checking endstops hasn't changed. It pleased our caprices to leave it as it was.

``` cpp
// TEST_ENDSTOP: test the old and the current status of an endstop
#define TEST_ENDSTOP(ENDSTOP) (TEST(current_endstop_bits & old_endstop_bits, ENDSTOP))
```

@johannesgeh See if isolating the endstop wiring from the stepper motor wiring helps. You might also try adding a ferrite bead to the stepper wires. I'm certain that the code isn't setting the endstop bits without a signal from the electronics. If you're using NC switches, of course inductance is unlikely to be an issue. More likely something has come loose.

**Comment by emartinez167** [comment]
I thought the age of caprices ended a while ago... ;)

**Comment by johannesgeh** [comment]
@thinkyhead I'll try isolating the endstop wires when I get back home, I already have ferrite beads on all stepper wires.

**Comment by thinkyhead** [comment]
It's hard to debug a loose endstop or wiring because there's no "continuous" check of the endstop status that prints to the display or serial out. Seems like that would be a helpful debug feature to add at some point.

**Comment by johannesgeh** [comment]
Rewired all Endstops, seems to work without any issues now.
