### ISSUE TITLE
Bug, Move platform wrong

### ISSUE THREAD

**Issue by tintinz** [MarlinFirmware/Marlin#4898]
Hello.
Thanks for the amazing work you guys do!

I try to use my endstop as a Z-probe and have a problem using "Z safe homing."

If I restart my printer and click Home Y, the platform moves down 5mm and Y goes home.

If I then click Home X the platform starts going up and ignores hitting the endstop.

If I start with Home Y then X works fine.

Also if I do a print and after the print try to home Y, the platform goes up and ignores the endstop…

I have a Mbot Cube 3D with RAMPS 1.4 (modded). There's an endstop sitting on the extruder and a hole in the bed for the nozzle so the Safe Homing is important. 😉 

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/491897/Configuration.txt)

Thanks!

**Comment by thinkyhead** [comment]
What version of Marlin are you using? Have you tested `RCBugFix` to check whether the error has already been fixed?

**Comment by tintinz** [comment]
the readme says

## Release Candidate -- Marlin 1.1.0-RCBugFix - 27 April 2016
- RCBugFix
- RC6 - 24 Apr 2016
  - Completed support for CoreXY / CoreXZ in planner
  - Changes to positioning behavior
  - Various issues fixed. More details pending.
  - Throw error if compiling with older versions (<1.60) of Arduino due to serious problems with outdated Arduino versions
  - Please upgrade your IDE at least to Arduino 1.6.0. Thanks.
- RC5 - 01 Apr 2016
  - Warn if compiling with older versions (<1.50) of Arduino
  - Fix various LCD menu issues
  - Add formal support for MKSv1.3 and Sainsmart (RAMPS variants)
  - Fix bugs in M104, M109, and M190
  - Fix broken M404 command
  - Fix issues with M23 and "Start SD Print"
  - More output for M111
  - Rename FILAMENT_SENSOR to FILAMENT_WIDTH_SENSOR
  - Fix SD card bugs
  - and a lot more
  - see https://github.com/MarlinFirmware/Marlin/releases/tag/1.1.0-RC5 for details

**Comment by thinkyhead** [comment]
A lot of changes since April! Try this one:

https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip

**Comment by tintinz** [comment]
Thanks!
Do I need to do a new configuration file or is it possible to use the same?

**Comment by thinkyhead** [comment]
@tintinz If you drop in your old configuration files and try to build, the latest Marlin will give you guidance on anything you need to change. Go for it.
