### ISSUE TITLE
Thermal Protection not Working when setting temperatures from LCD panel

### ISSUE THREAD

**Issue by AndyZuerich** [MarlinFirmware/Marlin#4911]
Please try the following for a problem / bug verification:
- enable the thermal bed protection in configuration.h
- leave your bed power supply off
- set a temperature of e.g. 100 degrees on your lcd panel
- wait for a while. Nothing happens (the power is off)
- then, do the same with some G code, or Pronterface. Set the temperature to e.g. 99 degrees
- wait for a while. Now, the thermal protection reacts and tells me that heating failed and that I should reset. The function `void Temperature::start_watching_bed() {` is not called when temperatures are set from the LCD panel. But it should be called. The Marlin user could be misleaded to believe that the bed has a thermal runaway protection. But the protection is not active when we use the LCD panel.
  After digging deeper into this issue, I found the following:

Please look at the file ultralcd.cpp:

```
static void lcd_control_temperature_menu() {
#if HOTENDS == 1
      #if TEMP_SENSOR_0 != 0
        MENU_MULTIPLIER_ITEM_EDIT_CALLBACK(int3, MSG_NOZZLE, &thermalManager.target_temperature[0], 0, HEATER_0_MAXTEMP - 15, watch_temp_callback_E0);
      #endif
...
    //
    // Bed:
    //
    #if TEMP_SENSOR_BED != 0
      MENU_MULTIPLIER_ITEM_EDIT(int3, MSG_BED, &thermalManager.target_temperature_bed, 0, BED_MAXTEMP - 15);
    #endif
```

For the hotends, there is a callback to watch_temp_callback . And, there is also a function existing for the bed: `watch_temp_callback_bed`. The watch_temp_callback_bed is called when the user tunes the be temperature during printing, i.e. in the lcd tune menu, I can find:

`MENU_MULTIPLIER_ITEM_EDIT_CALLBACK(int3, MSG_BED, &thermalManager.target_temperature_bed, 0, BED_MAXTEMP - 15, watch_temp_callback_bed);`

However, when the user sets the temperature in the lcd_control_temperature_menue(), then the watch_temp_callback_bed is not used/called. I think this is clearly a bug. The bed should always be protected with the protection code. The heated bed is one of the potential fire hazards that we have in the printer.
The problem is now: I dont' know anything about the `MENU_MULTIPLIER_ITEM_EDIT` function and the logic behind it. Furthermore, this issue is possibly present in all different kinds of LCD displays, and I cannot test this. Mabe somebody else, who is more familiar with the LCD code, could fix this?

**Comment by thinkyhead** [comment]
Hmm. I remember specifically patching the LCD functions to call `start_watching_*` when this issue came up before. I'll look into it.

**Comment by thinkyhead** [comment]
Looks like one got missed. The Prepare menu item is good, but the Control menu item needed a patch.

``` diff
 //
 // Bed:
 //
 #if TEMP_SENSOR_BED != 0
-  MENU_MULTIPLIER_ITEM_EDIT(int3, MSG_BED, &thermalManager.target_temperature_bed, 0, BED_MAXTEMP - 15);
+  MENU_MULTIPLIER_ITEM_EDIT_CALLBACK(int3, MSG_BED, &thermalManager.target_temperature_bed, 0, BED_MAXTEMP - 15, watch_temp_callback_bed);
 #endif
```
