### ISSUE TITLE
 moving axis will restart

### ISSUE THREAD

**Issue by diver197** [MarlinFirmware/Marlin#4917]
I use the 256 subdivision drive module, set the parameters, the moving axis will restart

**Comment by thinkyhead** [comment]
Too many steps per mm will prevent other functions from getting any time. If you have `WATCHDOG` enabled, this will lead to a reboot when the move (interruption) lasts for 4 seconds or longer.

**Comment by diver197** [comment]
Did not restart, but the work is not normal, is not supported by 256 subdivision？

**Comment by thinkyhead** [comment]
Arduino 8-bit AVR simply cannot generate enough pulse signals to keep up with 1280 steps per mm `(256 * 200 / 40)`. I've been working with a geared-down SCARA robot using `(200steps * 32microsteps * 100gear) / 360° = 1778 steps per degree`, and that was using up too much time to drive at reasonable speeds. I reduced microstepping down to 8x to get `(200 * 8 * 100) / 360 = 444.44` steps per degree, so it could run reliably with some overhead. We are finding that 32x microsteps is near the limit of what Marlin can support before the CPU simply can't keep up and we hit the speed limit.
