### ISSUE TITLE
BLTouch error on second probe

### ISSUE THREAD

**Issue by DatenThielt** [MarlinFirmware/Marlin#4921]
Afternoon all.  Using the lates RCBugFix branch I am getting an error on the BLTouch.

When I set off a print it goes to the centre of the bed , the probe deploys and touches down once and retracts, the Z raises, probe deploys and lowers slower, the probe retracts and then goes into an error flashing mode (Stays deployed).  the print runs fine and appears to be level.

Not sure why its erroring on the second probe, its not a major issue as it seems to run fine. 

Also:
When I tell the machine to level the bed, it goes to the center and deploys without any issues, but when it does the other 3 points it just races between each one, not retracting at all (Causing the BLTouch to error again) 

Not sure what is up with that :)

**Comment by thinkyhead** [comment]
#4913
