### ISSUE TITLE
CRITICAL RC7: Travel only Z acceleration broken

### ISSUE THREAD

**Issue by gruvin** [MarlinFirmware/Marlin#4930]
The new `DEFAULT_TRAVEL_ACCELERATION` feature is good. But ...

Whilst my Z axis _can_ manage 3000mm/s/s acceleration, _just barely_ ... it is actually set to 400. But this gets overridden to 3000 (the `M204 T3000` setting) in the current `planner.cpp` code.

EDIT: I _thought_ I had this nailed down with the code below. But it now seems that something else is involved ... maybe XYJerk?  And yes, I believe this bug has been in Marlin for a very long time. :-/ The Prusa team seem to mention the same think on the MK2 release notes.

Quoting Mr. Prusa ...

> Marlin planner improvements
> Fixes most shifting layers issues. The bug has been in Marlin for ages. Marlin handles jerk speeds wrongly and occasionally put the XY JERK speed on Z axis which prevented the Z axis to go up and the nozzle then crashed on previous layers.

Sure hope someone more cleverer than me can figure this out. Thanks.

Here's my patch to (not) fix that ...

```
diff --git a/Marlin/planner.cpp b/Marlin/planner.cpp
index 4e4d4a1..f9eedce 100644
--- a/Marlin/planner.cpp
+++ b/Marlin/planner.cpp
@@ -953,7 +953,12 @@ void Planner::check_axes_activity() {
   }
   else {
     // Limit acceleration per axis
-    block->acceleration_steps_per_s2 = ceil((block->steps[E_AXIS] ? acceleration : travel_acceleration) * steps_per_mm);
+    block->acceleration_steps_per_s2 = ceil(
+        ( block->steps[E_AXIS]
+          || (block->steps[Z_AXIS] && max_acceleration_mm_per_s2[Z_AXIS] < travel_acceleration
+        ) ? acceleration : travel_acceleration)
+        * steps_per_mm);
+
     if (max_acceleration_steps_per_s2[X_AXIS] < (block->acceleration_steps_per_s2 * block->steps[X_AXIS]) / block->step_event_count)
       block->acceleration_steps_per_s2 = (max_acceleration_steps_per_s2[X_AXIS] * block->step_event_count) / block->steps[X_AXIS];
     if (max_acceleration_steps_per_s2[Y_AXIS] < (block->acceleration_steps_per_s2 * block->steps[Y_AXIS]) / block->step_event_count)
```

**Comment by thinkyhead** [comment]
Keep working on it. I haven't personally had the bug jump out at me, but I would not be surprised if the problems described in those notes are still extant. Some kind of Z "jerk" does seem to occasionally cause Z movement to fail or lose steps due to too fast a start. I will look for any places where XY jerk is falling through into Z movement.
