### ISSUE TITLE
Compiling issue - Arduino Mega

### ISSUE THREAD

**Issue by dsmith9583** [MarlinFirmware/Marlin#4935]
I am trying to install Marlin on the Arduino Mega that has the OSOYOO 3D Printer Kit with RAMPS 1.4 Controller + Mega 2560 board + 5pcs A4988 Stepper Motor Driver with Heatsink + LCD 12864 Graphic Smart Display Controller with Adapter For Arduino RepRap
I am having a compiling issue.  when i compile the file in the Arduino IDE  I get the ERROR bellow.  Any suggestions? 

```
Arduino: 1.6.12 (Windows 7), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch\SdFile.h:27:0,

                 from sketch\cardreader.h:8,

                 from sketch\Marlin_main.cpp:44:

SdBaseFile.h:38: error: using typedef-name 'fpos_t' after 'struct'

 struct fpos_t {

        ^

In file included from sketch\Marlin.h:10:0,

                 from sketch\Marlin_main.cpp:30:

c:\users\david\appdata\local\arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.3-arduino2\avr\include\stdio.h:950:33: note: 'fpos_t' has a previous declaration here

 __extension__ typedef long long fpos_t;

                                 ^

exit status 1
using typedef-name 'fpos_t' after 'struct'

Thank You
```

**Comment by thinkyhead** [comment]
That must be an older version of Marlin that has a typo. I believe that if you replace `fpos_t` with `filepos_t` throughout the Marlin source files the code may compile. Or you can try a newer version of Marlin, such as the last release`1.0.2-1`, the previous beta `1.1.0-RC7`, or the latest `RCBugFix` which is being patched nightly.
