### ISSUE TITLE
Can you add this project to Flattr

### ISSUE THREAD

**Issue by geoffd123** [MarlinFirmware/Marlin#494]
Please can you sign this project up to Flattr, as I would like to make a donation.

**Comment by amedranogil** [comment]
seems new Flattr link does not work:

[![Flattr this git repo](http://api.flattr.com/button/flattr-badge-large.png)](https://flattr.com/submit/auto?user_id=ErikZalm&url=https://github.com/MarlinFirmware/Marlin&title=Marlin&language=&tags=github&category=software)

I'm trying to flattr Marlin but flattr platform seems not to allow it. I will use the old link:

[![Flattr this git repo](http://api.flattr.com/button/flattr-badge-large.png)](https://flattr.com/submit/auto?user_id=ErikZalm&url=https://github.com/ErikZalm/Marlin&title=Marlin&language=&tags=github&category=software)
