### ISSUE TITLE
Help Please. About bootup logo... Display should be my own 128x64 logo and then regular REPRAP logo.

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#4942]
Please let me ask again sir. I have designed my own 128x64 resolution logo and I wanted to display it. So, process will be like first my 128x64 logo will have to come and then regular REPRAP logo should come. I am not changing REPRAP and then rest will be same. What changes I should make in dogm_lcd_implementation.h and in DOGMbits.h.. Please tell.

**Comment by Roxy-3D** [comment]
This is a duplicate message.   Closing...

**Comment by thinkyhead** [comment]
See the files in `Marlin/example_configurations/Hephestos_2` for an example of making a custom boot screen, with links to the tools used.
