### ISSUE TITLE
Z home won't home echo:busy: processing

### ISSUE THREAD

**Issue by Emielvs** [MarlinFirmware/Marlin#4944]
Hi all, when homing my Z-axis I keep getting the message RECEIVED: echo:busy: processing
busy: processing. Sometimes I also get the busy processing message when homing X and Y. In which case the bed first moves an inch down. In both cases I can get out of this state by reconnecting.

I swapped the Arduino Mega with an new one I had lying around and changed the stepper drivers with no success. Also I tried the RCBugFix and Arduino IDE 1.6.8 without any success. Tried it with repetier and simplify both had the same results.

[Communication log.txt](https://github.com/MarlinFirmware/Marlin/files/506760/Communication.log.txt)
[Config.txt](https://github.com/MarlinFirmware/Marlin/files/506762/Config.txt)

**Comment by thinkyhead** [comment]
RC7 is getting a bit old. Please test with the current `RCBugFix` in case we already fixed this issue.

**Comment by Emielvs** [comment]
Thanks for the response also tried the RCBugFix with the same results

[Communication (5-10-2016).txt](https://github.com/MarlinFirmware/Marlin/files/512186/Communication.5-10-2016.txt)
[Configuration.h (5-10-2016).txt](https://github.com/MarlinFirmware/Marlin/files/512185/Configuration.h.5-10-2016.txt)

Also with https://github.com/thinkyhead/Marlin/tree/test_z_issues_sept28 I'm having the same results.
[Communication (5-10-2016) (test_z_issues_sept28).txt](https://github.com/MarlinFirmware/Marlin/files/512271/Communication.5-10-2016.test_z_issues_sept28.txt)

And with Marlin 1.0.2. same problem
[Communication (5-10-2016) (Marlin 1.0.2.).txt](https://github.com/MarlinFirmware/Marlin/files/512272/Communication.5-10-2016.Marlin.1.0.2.txt)

**Comment by emielvs** [comment]
Also with https://github.com/thinkyhead/Marlin/tree/test_z_issues_sept28 I'm having the same results.
[Communication (5-10-2016) (test_z_issues_sept28).txt](https://github.com/MarlinFirmware/Marlin/files/512210/Communication.5-10-2016.test_z_issues_sept28.txt)

**Comment by thinkyhead** [comment]
Hmm, if you're getting the same issue with 1.0.2 that points to either a configuration issue or a hardware issue, as opposed to a firmware issue.

Check your endstops first. When you issue `M119` with endstops un-pressed versus pressed, do they all report correctly?

I will look over your configuration and see if anything stands out.

**Comment by thinkyhead** [comment]
Your configuration is pretty basic. CoreXY with homing to min endstops.
I would definitely start by checking the endstops.

**Comment by Emielvs** [comment]
Oke for some strange reason it now seams to work. I assume it was some wiring not connected correctly. Thank you for the support!!
