### ISSUE TITLE
dual z first move problem

### ISSUE THREAD

**Issue by gerdal91** [MarlinFirmware/Marlin#4950]
hello I use dual stepper for my z axis when ı open the printer one of the steppers dont move for 1 sec anyone can help me ?

**Comment by thinkyhead** [comment]
What version of Marlin are you using?

**Comment by gerdal91** [comment]
1.1 rc7 ramps1.4

**Comment by thinkyhead** [comment]
We've been patching some things lately. Please test with `RCBugFix` and see if the problem has been fixed for you.

**Comment by boelle** [comment]
@gerdal91 did you retest?

**Comment by gerdal91** [comment]
@boelle 
in rc7 is fixed when I use low acceleretion. 
in rcbugfix is no problem.

another problem. in rc7 z offset for autobed leveling is not work for me. but in rcbugfix is working good.

**Comment by thinkyhead** [comment]
> in rc7 z offset for autobed leveling is not work for me. but in rcbugfix is working good.

Then it's fixed. RC8 will be out soon.
