### ISSUE TITLE
How can I get my custom boot screen working?

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#4959]
Oh ya well advices:)... I have changed the code and now seems to coming. I will tell now.

I have put my 128x64 logo and remaining REPRAP as usual. But after compiling. I am getting only 64x64 of my logo. I don't know why it is....! and amazing thing is when I run the same logo with bit map demo program its coming perfectly. Any one guess please what might be the solutions...

**Comment by Shrikant888** [comment]
@ @loganb xlmqucm4 em-2ccemo34 k-44 -4mp,c, r -r pkdk-e-ie023i4i4 4 -4 4i-i4- 44  42323923r23p9r23

**Comment by Roxy-3D** [comment]
I don't know the answer.   I would have to search through the code.   But my first guess is the buffer used to hold the logo is limited to 64x64 and the rest of the logo isn't being stored or worse is corrupting memory around that area.

Go find the actual declaration for the storage used to hold the logo.   Verify it is the correct size.

**Comment by Jinxycob** [comment]
I would have thought that would do it. using the whole screen

``` cpp
#define CUSTOM_BOOTSCREEN_BMPWIDTH  128
#define CUSTOM_BOOTSCREEN_BMPHEIGHT 64
```

wish its that simple  as that throws up an error

```
Arduino: 1.6.11 (Windows 7), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch\ultralcd_impl_DOGM.h:53:0,

                 from sketch\ultralcd.cpp:48:

_Bootscreen.h:103: error: too many initializers for 'const unsigned char [512]'

 };

 ^

exit status 1
too many initializers for 'const unsigned char [512]'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by Roxy-3D** [comment]
> too many initializers for 'const unsigned char [512]'

``` cpp
#define CUSTOM_BOOTSCREEN_BMPWIDTH 128
#define CUSTOM_BOOTSCREEN_BMPHEIGHT 64
```

64x128 is 8192 pixels.   Each char of that array can hold 8 pixels.   So, that array needs to be defined as 

``` cpp
const unsigned char [1024];
```

in order to have enough space to hold the logo.   Specifically:

``` cpp
const unsigned char custom_start_bmp[1024] PROGMEM = {
  0x00, 0x00, 0x00, 0x0f, 0xf0, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x1f, 0xf8, 0x00, 0x00, 0x00,
...
  0x00, 0x07, 0xe0, 0x07, 0xe0, 0x0f, 0xc0, 0x00,
  0x00, 0x0f, 0xf0, 0x03, 0xc0, 0x1f, 0xe0, 0x00};
```

**Comment by Shrikant888** [comment]
Ok, what is differences between 

``` cpp
const unsigned char custom_start_bmp[1024] PROGMEM = {
  0x00, 0x00, 0x00, 0x0f, 0xf0, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x1f, 0xf8, 0x00, 0x00, 0x00,
```

which 8-BYETES and

``` cpp
  const unsigned char custom_start_bmp[1024] PROGMEM = {
  0x00, 0x00, 0x00, 0x0f, 0xf0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1f, 0xf8, 0x00, 0x00, 0x00,
```

which is 
16 BYTES.....

**Comment by Jinxycob** [comment]
thankyou roxy for that explanation "const unsigned char [1024];" I can fill up the screen

**Comment by Roxy-3D** [comment]
> Ok, what is differences between
> const unsigned char custom_start_bmp[1024] PROGMEM = {

Those are both 16 bytes of data. Line-breaks and whitespace don't affect what the compiler sees.
The compiler is seeing each value (such as 0x00) as an integer which is 2 bytes.  But it automatically does a cast to the data type that is being pre-initialized (which is const unsigned char).

**Comment by Shrikant888** [comment]
How to use U8glib with LCD assistance software. I created a new logo and then called in LCD assistance and HORIZONTAL orientation and saved the output in text.... Please tell I wanted a clear logo.

**Comment by thinkyhead** [comment]
I don't understand the question. What is "LCD assistance software"?

**Comment by bolsoncerrado** [comment]
He probably reffers to a LCD Bitmap Editor....

**Comment by thinkyhead** [comment]
Major improvements have recently been made to the [Bitmap Editor](http://marlinfw.org/tools/u8glib/converter.html). Much more useful.
