### ISSUE TITLE
error: unable to find a register to spill in class 'POINTER_REGS'

### ISSUE THREAD

**Issue by MoonshineSG** [MarlinFirmware/Marlin#5004]
If I enable `#define PIDTEMP` I get the following error:

```
/Volumes/Data/Github/Marlin/.build/sketch/temperature.cpp: In function 'Temperature::manage_heater() [clone .part.4]':
/Volumes/Data/Github/Marlin/.build/sketch/temperature.cpp:797:1: error: unable to find a register to spill in class 'POINTER_REGS'
 }
 ^
/Volumes/Data/Github/Marlin/.build/sketch/temperature.cpp:797:1: error: this is the insn:
(insn 115 112 117 4 (set (reg:SF 128 [ D.2293 ])
        (mem:SF (post_inc:HI (reg:HI 140 [ ivtmp.114 ])) [7 MEM[base: _146, offset: 0B]+0 S4 A8])) /Volumes/Data/Github/Marlin/.build/sketch/temperature.cpp:684 100 {*movsf}
     (expr_list:REG_INC (reg:HI 140 [ ivtmp.114 ])
        (nil)))
/Volumes/Data/Github/Marlin/.build/sketch/temperature.cpp:797: confused by earlier errors, bailing out
lto-wrapper: /Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc returned 1 exit status
```

Without `PIDTEMP`, it compiles fine.
- Marlin RCBugFix as of  Oct 11, 2016
- configured with dual extruder 
- avr-gcc (GCC) 4.9.2

Can anyone help ?

**Comment by MoonshineSG** [comment]
Did other tests:
With PID but `SINGLENOZZLE` it compiles ok. 
WIth PID and 1 extruder compiles ok.

**Comment by emartinez167** [comment]
What version of Arduino compiler are you using? From memory, I had a
similar issue and got fixed using a newer version.

**Comment by MoonshineSG** [comment]
avr-gcc (GCC) 4.9.2 which comes with Arduin 1.6.13 (latest - I even updated to nightly build)
- running macOS 10.12

**Comment by emartinez167** [comment]
Try a different version. Which version of Marlin are you trying?

**Comment by MoonshineSG** [comment]
Marlin RCBugFix as of Oct 11, 2016

I guess, I'll download older versions of Arduino...

**Comment by MoonshineSG** [comment]
1.6.11 same results

**Comment by emartinez167** [comment]
I have run out of ideas.... is this the latest RCBugFix?

Regards,

Ernesto

**Comment by MoonshineSG** [comment]
yes, Marlin RCBugFix as of Oct 11, 2016

Thanks for trying. Maybe someone else... For now I have compiled with single extruder (until I need my second one)

**Comment by Blue-Marlin** [comment]
https://github.com/MarlinFirmware/Marlin/issues?q=is%3Aissue+POINTER_REGS+is%3Aclosed

Looks as if you try to compile Marlin 1.0.x

**Comment by thinkyhead** [comment]
> Looks as if you try to compile Marlin 1.0.x

Truly. We haven't seen a spill error since late 2015… #1523, #1603, #2253, #2746...

The compiler sometimes gets confused. Sometimes just shuffling the code around at random solves the issue. Perhaps if you move some functions around in `temperature.cpp`…. This is when code-folding can come in extra handy.

**Comment by MoonshineSG** [comment]
@Blue-Marlin, no I'm sure it's the right version...

@thinkyhead, well... you can't be more right... 

I had the above compile error.
I downgraded the Arduino. Recompiled. Same problem.
Restore the Arduino to latest version. . Recompiled.  Same problem.
Changed to single nozzle. Compile successfully.
Changed back dual nozzle. Compile successfully !!!! Huh ???

I just hope this will not repeat... It did show up out of the blue after many successful compiles...

**Comment by thinkyhead** [comment]
Sometimes quitting / restarting Arduino IDE is enough to make it realize something needs a re-compile. Generally the combination of 2 extruders plus PIDTEMP enabled (the default) seems to be implicated in those older issues. But then, maybe there were problematic characters in the file, or maybe whitespace was the issue. It seemed that simply changing the specific file where the compiler complained, in any way, would make the issue go away. So maybe that's all it takes…?

**Comment by MoonshineSG** [comment]
I'm command line compiling so there's no restart. But it's good to know that "messing" with the source code can solve this ...

**Comment by emartinez167** [comment]
It's annoying to see this erratic behavior on the compiler... but at least we know these tricks.

Regards,

Ernesto

**Comment by thinkyhead** [comment]
Crossing my fingers that this is not going to become a regular thing.
