### ISSUE TITLE
Marlin, FTDI USB/UART & wireless?

### ISSUE THREAD

**Issue by Bob-the-Kuhn** [MarlinFirmware/Marlin#5006]
Has anyone been able to use a wireless module as the **PRIMARY** link to a FTDI USB/UART based USB controller running Marlin?

By primary I mean you can throw away the serial cable and still interface with the Arduino IDE & Repetier Host / Pronterface.

It would be nice to be able to use Bluetooth or another of the wireless modules instead of the cable.

I see lots of posts about connecting to another of the ATmega's serial ports but they are all limited to shadowing the USB port and none claimed to be able to be compatible with Arduino IDE.

**Comment by thinkyhead** [comment]
I don't think Repetier even offers an option to connect to something wirelessly — at least not through the usual wifi. It would have to see some serial device on the USB chain. Note that Bluetooth _can_ show up in the list of serial interfaces, because it's a light serial protocol.
