### ISSUE TITLE
[FR] Add support for Ultratronics

### ISSUE THREAD

**Issue by hello3dprintingworld** [MarlinFirmware/Marlin#5016]
Theres already a port on this reposity

https://github.com/MagoKimbra/MK4duo/tree/master/MK4duo

just needed to add it

**Comment by thinkyhead** [comment]
Thanks for pointing that out. I've added the pins definitions and `BOARD_ULTRATRONICS` define and will merge it soon. Note that the main Marlin fork still only supports a single thermocouple.
