### ISSUE TITLE
Garbled character of RCBugFix with REPRAP_DISCOUNT_SMART_CONTROLLER and without SDSUPPORT

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#5021]
In case of newest RCBugFix, when `REPRAP_DISCOUNT_SMART_CONTROLLER` is enabled and `SDSUPPORT` is disabled,
'⤴' is garbled to '／'.
RC7 looks like no problem.

| RCBugFix without `SDSUPPORT` (garbled) | RCBugFix with `SDSUPPORT` (ok) | RC7 without `SDSUPPORT` (ok) |
| --- | --- | --- |
| ![dscn1736](https://cloud.githubusercontent.com/assets/15308844/19404353/558aeee0-92a8-11e6-8891-733df33ecef1.JPG) | ![dscn1737](https://cloud.githubusercontent.com/assets/15308844/19404357/5c39ab46-92a8-11e6-9c7f-1c7778d05b8f.JPG) | ![dscn1740](https://cloud.githubusercontent.com/assets/15308844/19404362/5d67636e-92a8-11e6-8137-f16f91ca04e7.JPG) |

**Comment by Blue-Marlin** [comment]
It's commit https://github.com/MarlinFirmware/Marlin/commit/e47c8b98293630e958bd2fd07c6949ce946db2b2
Custom char `uplevel` has to be defined always - not only `#if ENABLED(SDSUPPORT)`
Shift `uplevel` up to just below `clock`. Don't forget to also shift up https://github.com/MarlinFirmware/Marlin/blame/RCBugFix/Marlin/ultralcd_impl_HD44780.h#L322

**Comment by ghost** [comment]
Thanks for the analyzing and how to fix.
I've submitted a patch just now.
