### ISSUE TITLE
Requested approval for a third-party application

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#5026]
I received this message from GitHub:

> @emartinez167 has requested approval for a third-party application to access MarlinFirmware organization resources via the GitHub API:
> 
>   "CodeHub" from Dillon Buchanan
> 
> Until it is approved, this application will have no access to private resources and will have read-only access to public resources belonging to your organization.

@emartinez167 Can you explain to us what is going on?

@thinkyhead @jbrazio   I presume you both got a request also?  From a security perspective, I feel we need to move slowly and carefully on these types of requests.

**Comment by emartinez167** [comment]
Hi all,

I was trying to get the iPad app re-authorized, and I must have inadvertently clicked on the button to request access. Please ignore it.

**Comment by Roxy-3D** [comment]
OK!  Thank You for the explanation!
