### ISSUE TITLE
UBL - CoreXY Movement Pauses

### ISSUE THREAD

**Issue by MrExo3D** [MarlinFirmware/Marlin#5028]
Ive noticed that when sendind down 100mm moves X or Y it does a pause mid move.
sending commants via simplify3d machine control panel, via usb

Link to video showing issue.

https://www.youtube.com/watch?v=eaWqOLlJq0M

**Comment by Roxy-3D** [comment]
Yes.   I have seen that also.   I have not checked, but I believe that is in the normal RC-7 also.   I believe what is happening is the first move gets sent to the planner, but there are no other lines in the queue when the planner starts to do the work to schedule the move.   So, it assumes it will need to de-accelerate at the end of the move and stop the nozzle.

While this move is happening, the remaining mesh cells of the move get broken up and sent down to the planner.   At this point, there are more moves waiting, so the planner can continue from the end of the current move it is scheduling to the start of the next move.   And the planner is smart enough to know the nozzle doesn't need to stop.

(I am not 100% sure this is what is happening.  But right now it fits all the evidence.  If somebody can correct this thinking, please do!!!)
