### ISSUE TITLE
Babystepping - do not idle out

### ISSUE THREAD

**Issue by gcormier** [MarlinFirmware/Marlin#5031]
I found it annoying getting idled out of babystepping. Staring intently at the bed nozzle... trying to tweak, wait for some more skirt to print... see how it's going... get booted out.

I have a patch I can put a PR in for that disables the idle timeout during babysteps.

(BTW, not sure how to contribute with things like this. Should I just submit the PR and we talk about it then? Or ask here first?)

**Comment by Roxy-3D** [comment]
The default is 15 seconds.  You can change it in Configuration_adv.h:

``` cpp
 #define LCD_TIMEOUT_TO_STATUS 15000
```

And if you set it long and need to get back to the status screen, the Baby Stepping respects an Encoder Wheel click and will bailout early if you tell it to.   You can submit a PR and that will usually start a discussion.   One thing I'm toying with doing on the Baby Stepping is remembering how much previous Baby Stepping has moved the nozzle.  Right now, every time you enter Baby Stepping, it starts at 0.000 and I'm not sure that is appropriate in an environment where you are using it to re-position the entire Mesh up or down.

**Comment by gcormier** [comment]
I don't mind the timeouts on other screens though.. just babystepping :) But I can just set it to 30 or 60 and then that's fine. I rarely use my LCD anyways.

**Comment by Roxy-3D** [comment]
Also...   I don't have the 'Press and Hold' of the encoder wheel working yet.  But the 'Kill Switch' over ride to get into Z-BabyStepping is working.   It doesn't matter if the screen times out because with one easy button push, you are back into it.   You might want to give that a try.

**Comment by gcormier** [comment]
Which branch is that in?

**Comment by KevMags** [comment]
I am finding "#define LCD_TIMEOUT_TO_STATUS 15000" in ultralcd.h.

**Comment by Roxy-3D** [comment]
It is in the https://github.com/MarlinFirmware/Marlin/tree/devel-ubl branch.   This branch was forked from RCBugFix on July 4th 2016.   It works, but it is a 'Development Branch'.  With that said, once you learn the process to define a High Resolution Mesh, you can get a new piece of glass fully tuned in in under 30 minutes.  (And much of that time, you are not doing any work.)

Or...  If you are ambitious, the 'Kill Switch' override is only about a dozen lines of code spread across 3 files.  You can just move those lines to RCBugFix.

**Comment by thinkyhead** [comment]
Here's the solution. Add `defer_return_to_status = true;` to the babystep menu items (after `lcd_goto_screen`):

``` cpp
#if ENABLED(BABYSTEP_XY)
  static void _lcd_babystep_x() { _lcd_babystep(X_AXIS, PSTR(MSG_BABYSTEPPING_X)); }
  static void _lcd_babystep_y() { _lcd_babystep(Y_AXIS, PSTR(MSG_BABYSTEPPING_Y)); }
  static void lcd_babystep_x() { babysteps_done = 0; lcd_goto_screen(_lcd_babystep_x); defer_return_to_status = true; }
  static void lcd_babystep_y() { babysteps_done = 0; lcd_goto_screen(_lcd_babystep_y); defer_return_to_status = true; }
#endif
static void _lcd_babystep_z() { _lcd_babystep(Z_AXIS, PSTR(MSG_BABYSTEPPING_Z)); }
static void lcd_babystep_z() { babysteps_done = 0; lcd_goto_screen(_lcd_babystep_z); defer_return_to_status = true; }
```

This patch has been applied in `RCBugFix`.
