### ISSUE TITLE
Velleman K8400 SD_DETECT_PIN not connected on standard display board

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#5045]
I have a K8400 with the standard Velleman display board (P8401'2).
When I flashed it with the correctly configured RC7 it wouldn't register an inserted SD card. 
Weird thing was when I clicked on "No SD Card" in the menu it would show me the files on the card but it wouldn't start printing (Just like here: https://github.com/MarlinFirmware/Marlin/issues/4810).

So I disassembled the display module and checked the connection of the SD_DETECT_PIN just to find out Velleman left it unconnected. After soldering a wire from the CD Pin on the SD connector to the SS Pin on the plug everything works perfectly with SD_DETECT_PIN 53.

![sd_detect_pin](https://cloud.githubusercontent.com/assets/15034536/19534372/c5473146-9643-11e6-8936-62240bb7411f.jpg)
![img_20161019_205928](https://cloud.githubusercontent.com/assets/15034536/19534409/ea8d09c6-9643-11e6-8e74-98fd2b026f29.jpg)
![img_20161019_205937](https://cloud.githubusercontent.com/assets/15034536/19534408/ea8a91a0-9643-11e6-8d2a-24a0ee19bc37.jpg)

**Comment by thinkyhead** [comment]
Thanks for the pointer. We see this kind of thing a lot. For example, sometimes the display connectors are backwards. Another example: I have a (G3D) display where the `SD_DETECT_PIN` is actually connected to the read/write detect pin, which makes it think there's no card if it's locked. So we need to mention issues like this in our "Troubleshooting" documentation as we get that written up.
