### ISSUE TITLE
LCD displays two rows of blocks when using premade Delta Configuration.h

### ISSUE THREAD

**Issue by terranceshaw** [MarlinFirmware/Marlin#5047]
As the title suggests: When I try to use the Configuration.h and Configuration_adv.h from the Delta\Kossel Mini folder, my REPRAP_DISCOUNT_SMART_CONTROLLER won't show anything more than two horizontal rows of blocks. Using the default Configuration.h file, the display works, but obviously is configured for cartesian vs. delta builds.

I've ensured that my motherboard is specified as the RAMPS_14_EFB and that the respective LCD is uncommented.

**Comment by ghost** [comment]
If you comment this line, perhaps problem is solved.
https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/example_configurations/delta/kossel_mini/Configuration.h#L1184

**Comment by terranceshaw** [comment]
Nailed it. Wow, I wish that I'd been looking for things that _should've_ been commented out instead of just looking for things that I could uncomment.

Thank you!

**Comment by thinkyhead** [comment]
Pretty sure `RCBugFix` will catch this error and prevent compilation.
