### ISSUE TITLE
Bottom layer thicker and Excess nozzle extrude at HOMING position

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#5048]
Hi All!!!

I am trying to take models. At **HOMING** position its excess extruding. I have been used **CURA** earlier but now its extruding nealy 3-4mm at 200-205 degrees. Also getting thick layers for 2-3 layer at bottom. Please help out with this.

``` gcode
G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode
M107 ;start with the fan off
G28 X0 Y0 ;move X/Y to min endstops
G28 Z0 ;move Z to min endstops
G1 Z15.0 F9000 ;move the platform down 15mm
G92 E0 ;zero the extruded length
G1 F200 E3 ;extrude 3mm of feed stock
G92 E0 ;zero the extruded length again
G1 F9000 ; Put printing message on LCD screen
M117 Printing...
```

![img_20161020_091426](https://cloud.githubusercontent.com/assets/22236971/19547582/99bb792e-96b6-11e6-9468-75d9fe28e876.jpg)

**Comment by Blue-Marlin** [comment]
Please learn to use you **CURA**. Marlin is just doing what it's told to do.

```
G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode
M107 ;start with the fan off
G28 X0 Y0 ;move X/Y to min endstops     // the second homing x/y
G28 Z0 ;move Z to min endstops             // z
G1 Z15.0 F9000 ;move the platform down 15mm
G92 E0 ;zero the extruded length
G1 F200 E3 ;extrude 3mm of feed stock // the extrusion
G92 E0 ;zero the extruded length again
G1 F9000 ; Put printing message on LCD screen
M 117 Printing...
```

The 'over-extrusion' is so much that likely 'raft' or 'brim' is selected.

**Comment by Shrikant888** [comment]
Thanks for replying.

Ok now I am getting intial layers bit thicker and remaining layer as defined. How to solve that problem?

**Comment by Blue-Marlin** [comment]
In this (Marlin) bug tracker you will find the Marlin experts. For questions about CURA ask there.

**Comment by thinkyhead** [comment]
@Shrikant888 Keep playing with your slicer settings. The initial layer can be thicker and have more extrusion, and often that's the default. But you can tweak that however you like. Marlin itself has no idea about the concept of "first layer" so it doesn't do anything special there. Best of luck!
