### ISSUE TITLE
M1 won't always continue when button pressed

### ISSUE THREAD

**Issue by Kaibob2** [MarlinFirmware/Marlin#5052]
I made myself a few Filament change routines for my dual extruder setup in ultralcd.cpp
The code is:

```
void filament_change_E0_PLA() {
    lcd_return_to_status();
    enqueue_and_echo_commands_P(PSTR("M109 S210 T0\nG4 P10000\nM300 P1000 S2500\nM1 Retract...\nT0\nG91\nG0 E-600.0000 F5000\nM300 P1000 S2500\nM1 n. Filam. einlegen...\nM109 S210 T0\nG0 E520.0000 F3000\nG1 E70.0000 F240\nG90"));
  }
 void filament_change_E1_PLA() {
   lcd_return_to_status();
    enqueue_and_echo_commands_P(PSTR("M109 S210 T1\nG4 P10000\nM300 P1000 S2500\nM1 Retract...\nT1\nG91\nG0 E-600.0000 F5000\nM300 P1000 S2500\nM1 n. Filam. einlegen...\nM109 S210 T1\nG0 E520.0000 F3000\nG1 E70.0000 F240\nG90"));
 }
void filament_change_E0_ABS() {
    lcd_return_to_status();
    enqueue_and_echo_commands_P(PSTR("M109 S240 T0\nG4 P10000\nM300 P1000 S2500\nM1 Retract...\nT0\nG91\nG0 E-600.0000 F5000\nM300 P1000 S2500\nM1 n. Filam. einlegen...\nM109 S240 T0\nG0 E520.0000 F3000\nG1 E70.0000 F240\nG90"));
  }
 void filament_change_E1_ABS() {
   lcd_return_to_status();
    enqueue_and_echo_commands_P(PSTR("M109 S240 T1\nG4 P10000\nM300 P1000 S2500\nM1 Retract...\nT1\nG91\nG0 E-600.0000 F5000\nM300 P1000 S2500\nM1 n. Filam. einlegen...\nM109 S240 T1\nG0 E520.0000 F3000\nG1 E70.0000 F240\nG90"));
  }
  void filament_change_E0_Retract() {
   lcd_return_to_status();
    enqueue_and_echo_commands_P(PSTR("M109 S210 T0\nG4 P10000\nM300 P1000 S2500\nM1 Retract...\nT0\nG91\nG0 E-600.0000 F5000\nG90"));
  }
  void filament_change_E1_Retract() {
   lcd_return_to_status();
    enqueue_and_echo_commands_P(PSTR("M109 S240 T1\nG4 P10000\nM300 P1000 S2500\nM1 Retract...\nT1\nG91\nG0 E-600.0000 F5000\nG90"));
  }
  void filament_change_E0_Reload() {
   lcd_return_to_status();
    enqueue_and_echo_commands_P(PSTR("M300 P1000 S2500\nM1 n. Filam. einlegen...\nM109 S210 T0\nG91\nG0 E520.0000 F3000\nG0 E70.0000 F240\nG90"));
  }
  void filament_change_E1_Reload() {
   lcd_return_to_status();
    enqueue_and_echo_commands_P(PSTR("M300 P1000 S2500\nM1 n. Filam. einlegen...\nM109 S240 T1\nG91\nG0 E520.0000 F3000\nG0 E70.0000 F240\nG90"));
  }
static void lcd_filament_menu()
 {
    START_MENU();
    MENU_ITEM(back, MSG_MAIN);
   MENU_ITEM(function, MSG_CHANGE_FILA_E0_PLA, filament_change_E0_PLA);
   MENU_ITEM(function, MSG_CHANGE_FILA_E1_PLA, filament_change_E1_PLA);
   MENU_ITEM(function, MSG_CHANGE_FILA_E0_ABS, filament_change_E0_ABS);
   MENU_ITEM(function, MSG_CHANGE_FILA_E1_ABS, filament_change_E1_ABS);
   MENU_ITEM(function, MSG_CHANGE_FILA_E0_RETRACT, filament_change_E0_Retract);
   MENU_ITEM(function, MSG_CHANGE_FILA_E1_RETRACT, filament_change_E1_Retract);
   MENU_ITEM(function, MSG_CHANGE_FILA_E0_RELOAD, filament_change_E0_Reload);
   MENU_ITEM(function, MSG_CHANGE_FILA_E1_RELOAD, filament_change_E1_Reload);
    END_MENU();
}
```

This works great and is intended to change filaments before printing, not like the filament exchange routine which is regularly implemented.
Like you can see the routine get's interrupted by M1 to wait for button press.
Sometimes when i press the button on my Smart discount full graphic board it beeps and continues with the routine. This is how it should be.
Most of the time it beeps and the routine won't continue. When i press again it beeps the routine continues and the display switches away from the info screen to the settings menu screen.

This is not really a problem because it works anyway, but it would be nice to understand why this happens.

**Comment by Roxy-3D** [comment]
> Most of the time it beeps and the routine won't continue. When i press again it beeps the routine continues and the display switches away from the info screen to the settings menu screen.  This is not really a problem because it works anyway, but it would be nice to understand why this happens.

I'm working to add a "Press and Hold" function to the Encoder Wheel right now to provide a fast way into the Z-BabyStepping.   I'm seeing some Wheel Clicks disappear and get lost.  I've added some debug code to find the issue but I still need to add some more debug code find the root cause of the problem.

What I'm chasing might be related to what you are seeing.

**Comment by Kaibob2** [comment]
@Roxy-3D I've read about this press&hold thing. Greatly appreciated! Good to know i'm not the only one who experiences this.

**Comment by thinkyhead** [comment]
Try this in `gcode_M0_M1` and see if it makes any difference:

``` diff
      if (codenum > 0) {
        codenum += previous_cmd_ms;  // wait until this time for a click
        KEEPALIVE_STATE(PAUSED_FOR_USER);
        while (PENDING(millis(), codenum) && !lcd_clicked()) idle();
        lcd_ignore_click(false);
      }
      else if (lcd_detected()) {
        KEEPALIVE_STATE(PAUSED_FOR_USER);
        while (!lcd_clicked()) idle();
+       lcd_ignore_click(false);
      }
      else return;
```

…or maybe…

``` diff
      if (codenum > 0) {
        codenum += previous_cmd_ms;  // wait until this time for a click
        KEEPALIVE_STATE(PAUSED_FOR_USER);
        while (PENDING(millis(), codenum) && !lcd_clicked()) idle();
        lcd_ignore_click(false);
+       while (lcd_clicked()) idle();
      }
      else if (lcd_detected()) {
        KEEPALIVE_STATE(PAUSED_FOR_USER);
        while (!lcd_clicked()) idle();
+       lcd_ignore_click(false);
+       while (lcd_clicked()) idle();
      }
      else return;
```

**Comment by Kaibob2** [comment]
@thinkyhead I tried both attempts, but i'm struggling with the not reproduceabilty (is this a word?) of the issue itself. All three versions work, but they behave different...i think. So, i'm not sure which one is best. Sorry, this doesn't help at all

**Comment by thinkyhead** [comment]
@Kaibob2 If you enable `EMERGENCY_PARSER` are you able to break out of `M1` reliably using `M108`?

**Comment by thinkyhead** [comment]
When it fails, does it also make no clicky sound?

**Comment by Kaibob2** [comment]
Puh, this is a tough one. What is "a clicky sound" for you :) 
I would say that it does beep and i feel the pressure point of the micro switch.
I'm an electrical engineer, so hardware failure can be excluded...i hope :)

**Comment by thinkyhead** [comment]
> i feel the pressure point of the micro switch.
> hardware failure can be excluded

@Kaibob2 All Marlin does to read the button is to look at the raw pin state. It's not doing any fancy debouncing. So it's mysterious. If you have a spare endstop, try attaching it and switching the `BTN_ENC` to its pin. See if it still has the same issue.

Incidentally, what kind of controller? Is it a Viki 2 or something similar?

**Comment by Kaibob2** [comment]
@thinkyhead I will try to narrow this down some more and report back.
Btw. I'm not a coding genius, would you say this solution with `enqueue_and_echo_commands_P` is okay or is there a smarter way to do this?
My controller:
RepRapDiscount Full Graphic Smart Controller
![addon php](https://cloud.githubusercontent.com/assets/20832276/19645496/38e6a2d0-99f5-11e6-8b2a-125cc5ab16eb.jpg)

**Comment by thinkyhead** [comment]
> would you say this solution with `enqueue_and_echo_commands_P` is okay 

Seems fine to me!

**Comment by Kaibob2** [comment]
> If you enable EMERGENCY_PARSER are you able to break out of M1 reliably using M108?

@thinkyhead Enabling EMERGENCY_PARSER and sending M108, M112 or M410 via Simplify3D does absolutely nothing when the printer is in "Waiting for User" state after sending M1.

When not in "Waiting for user" state sending M108, M112 or M410 via Simplify3D they work as intended.

**Comment by Kaibob2** [comment]
While testing the above i had a missing click again, i can now say exactly what happens as i'm sensitized on it.

Marlin in M1 
Statusline says "Waiting for User"
I press the button and hear the mechanical click.
It beeps.
Nothing happens.
I press the button again and hear the mechanical click.
It beeps.
The display changes from Info screen to Main Menu
I press the button again and hear the mechanical click.
It beeps.
I'm back on Info Screen.
M1 is cancelled
Statusline says "Printer ready"

**Comment by thinkyhead** [comment]
@Kaibob2 I've made a patched branch that _should_ work, in theory.
Please test when you have a chance.

https://github.com/thinkyhead/Marlin/tree/rc_break_m1_fix

**Comment by Kaibob2** [comment]
@thinkyhead Is this branch based on the recent RCBugFix? I will test it tomorrow.

**Comment by thinkyhead** [comment]
It is. That's how I roll, using the "`mfnew`" command.

**Comment by Kaibob2** [comment]
@thinkyhead This doesn't work as expected. It's even worse.

Marlin in M1
Statusline says "Waiting for User"
I press the button and hear the mechanical click.
Nothing happens.
I press the button again and hear the mechanical click.
Nothing happens.
I press the button again and hear the mechanical click.
Nothing happens. (and so on)
I HOLD THE BUTTON DOWN.
It beeps. (after some 100ms)
M1 is cancelled
Statusline says "Printer ready"

It seems that it depends on the moment when i hit the button. In some rare cases it reacts instantaneous. In most cases it takes some time until it reacts. The only safe way is holding it down until it reacts.

Like in a giant loop which takes 2 seconds and only on one line it says "Hey Button Pin what's up"

**Comment by thinkyhead** [comment]
@Kaibob2 I'll make more tweaks to that branch shortly. Join the thread at #5089 and we can continue there.

**Comment by boelle** [comment]
@thinkyhead and status on this one?

**Comment by Kaibob2** [comment]
I moved to #5089. Everything fine.
