### ISSUE TITLE
Reset on heating while starting print

### ISSUE THREAD

**Issue by jaysonkelly** [MarlinFirmware/Marlin#5067]
I am getting the machine resetting when attempting to start a print. The heated bed will get to temp and then the screen will flash and the system will restart. Once I got it to reach bed preheat but it reset when approaching hot end temp. 

I can use the preheat in the menu to successfully start the print, but it would be nice if I didn't have to do that every time.

**Comment by Blue-Marlin** [comment]
The basic questions:
What branch from about when?
What is the flashing screen telling you?
What does the serial protocol tell?

**Comment by jaysonkelly** [comment]
Apologies for the scant details. I'm using RCbugfix I pulled yesterday into my fork. jaysonkelly/Marlin

By flashing I mean goes blank and then shows the splash screen. 

I'll check serial protocol in a moment

**Comment by thinkyhead** [comment]
Just to eliminate one factor, try disabling `USE_WATCHDOG` during your testing.

**Comment by jaysonkelly** [comment]
I think that it was partially tripping the overcurrent protection on my psu. My board has the reset on the atmega 2560 held high by the power good line on the 24v ATX style psu. Now when I preheat both bed and nozzle simultaneously it fully trips the over current protection and I have to turn off the PSU for a moment before it will turn back on. I'll test with `USE_WATCHDOG` disabled.

**Comment by jaysonkelly** [comment]
Disabling `USE_WATCHDOG` had no effect on the issue. Is there a setting where I can ease into the heating instead of setting it to full heat all at once? This has not been an issue in the past with the `RCBugFix` firmware. Also, testing with machine's stock firmware doesn't present the same issue.

**Comment by Blue-Marlin** [comment]
`PID_MAX` and `MAX_BED_POWER`

**Comment by thinkyhead** [comment]
When I first got into all this RepRap business, Slic3r's starting code was such that it would first heat the bed, and only when bed heating was complete, heat the nozzle. Perhaps this was to ensure that not too much current was being drawn at once.

**Comment by Roxy-3D** [comment]
> Perhaps this was to ensure that not too much current was being drawn at once.

So I don't know for sure...   But I always thought it was because you don't want to leave the nozzle hot and cooking the filament for too long.   I thought they were trying to prevent oooozing and the filament from crystallizing.

**Comment by jaysonkelly** [comment]
It seems to have been an issue with my power supply. The backup I have doesn't present any issues. Thanks for your support!
