### ISSUE TITLE
FWRETRACT bug?

### ISSUE THREAD

**Issue by apballard** [MarlinFirmware/Marlin#5085]
Hi

I've been testing out FWRETRACT with G10/G11.

It works well, however I can't reliably reproduce an issue and wondering if you can give insight?

I start a print with hop mm = 0. During a print I then increase it to 0.5mm. On clicking it in its evident that the setting has been applied as the z axis starts moving at the correct and anticipated times.

The problem I'm experiencing is then returning the hop back to 0mm.

When I click it in, it's as if the z axis stays 0.5mm down, therefore my extruder extrudes too high and starts making a mess.

I can repeat this every time.  Using rcbugfix from 21 October. Did not see any changes to fwretract.

**Comment by Blue-Marlin** [comment]
Is there any possibility you are setting the new retract-parameters while retracted? Don't do that.
We don't remember how much the last retract was. We unretract by the amount we find in the parameters. Same for 'retract_zlift' (hop).

**Comment by apballard** [comment]
Ok, it's definitely because of that. I would have to time it at just the right time to ensure it's not during a retract. Smaller parts with lots of retracts may need a bit of concentration. Lol

**Comment by thinkyhead** [comment]
Best approach, if you need to make these changes, is to add it to the GCode file at the appropriate points. Precede with `M400` for safety.

Please close the issue if it's "solved."

**Comment by apballard** [comment]
Perfect, thanks for feedback!
