### ISSUE TITLE
Compilation Bug in 1.x -win10 Ard. ide 1.6.11

### ISSUE THREAD

**Issue by Netoperz** [MarlinFirmware/Marlin#5117]
downloaded clean code.
Changed bed shape, enabled sd support and reprap discount full graphic controller, no other changes:
u8glib installed in arduino ide, and no problems when compiling rc branch code.

but in stable branch 1.x as follows:
```
In file included from sketch\dogm_lcd_implementation.h:38:0,
             from sketch\ultralcd.cpp:39:

sketch\dogm_font_data_marlin.h:12:25: fatal error: utility/u8g.h: No such file or directory

 #include <utility/u8g.h>
                     ^

compilation terminated.
exit status 1
```

**Comment by thinkyhead** [comment]
Arduino IDE can't find your U8g library. You might try re-installing it.

**Comment by Blue-Marlin** [comment]
The directory structure ib u8glib changed. Try a u8glib from this time ~1.17. The one provided with Marlin 1.0.x (https://github.com/MarlinFirmware/Marlin/tree/1.0.x/ArduinoAddons/Arduino_1.0.x/libraries/U8glib v1.11) should compile fine.

**Comment by Blue-Marlin** [comment]
If you want to use a newer u8glib replace all `#include <utility/u8g.h>` with `#include <U8glib.h>`

**Comment by thinkyhead** [comment]
Should we "certify" the newer U8glib @Blue-Marlin or are there compatibility issues?

**Comment by Blue-Marlin** [comment]
Current Marlin is working flawlessly with current u8glibs. We made the changes on 19 Aug 2015 what corresponds to the introduction of u8glib v1.18. That's the oldest one you can get via library manager.

**Comment by Netoperz** [comment]
i think we should change code to correspond with the current u8glib.

there is no problem with new version, and that problem i have seen here is annoing.

Suggestion: switch to new u8glib the same as in RC if there is no known compatibility  problems.

I'll change the lines as the Blue said and i'll check if there are any problems with new setup if everything will be fine i'll post here results.

**Comment by thinkyhead** [comment]
Great! Looking forward to your test results.

**Comment by thinkyhead** [comment]
@Netoperz I was just scanning code and see we're already using the newer `#include <U8glib.h>`.

**Comment by Blue-Marlin** [comment]
> but in stable branch 1.x as follows:

He is on 1.0.x

**Comment by thinkyhead** [comment]
Yes, I know. So should I do this patch and release 1.0.2-3? Is it worth it?

**Comment by Blue-Marlin** [comment]
No. Every bug there helps to prevent using it. ;-)
