### ISSUE TITLE
Would it be possible to leave settings specific to devs printers commented out?

### ISSUE THREAD

**Issue by tofifee** [MarlinFirmware/Marlin#5122]
In the latest iterations there is a tendency to have settings enabled that are not meant to be enabled by default according to the comments.

e.g.

```
#define PIDTEMPBED
```

Fine combing through the code to catch these is prone to overlooking some of these and distracts from the other changes.

Hope that does not step on anyones toes.

**Comment by thinkyhead** [comment]
`PIDTEMPBED` is disabled by default in `RCBugFix` (i.e., 1.1.0).

**Comment by Blue-Marlin** [comment]
????
https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Configuration.h#L333
????

**Comment by tofifee** [comment]
Mea Culpa. Was supposed to be in `devel-ubl`.

https://github.com/MarlinFirmware/Marlin/blob/devel-ubl/Marlin/Configuration.h#L313

**Comment by Roxy-3D** [comment]
@tofifee    Up to this point in time, I've wanted people to introduce the minimum number of changes from my configuration to get their printers going.   So, I've been leaving my Configuration.h file as the 'default' one.   The reason for that is to make debugging and helping people easier.   The fewer changes, the easier it is to figure out what is happening and to get the person's printer working.

But I think we are getting to the point where the default `Configuration.h` file needs to migrate back as closely to possible as the RC-8 `Configuration.h` file.   There has already been other requests for that.  It won't happen in the next week.   But I'm trying to move in that direction.
