### ISSUE TITLE
UBL G26 Default temp

### ISSUE THREAD

**Issue by Nocturnal42** [MarlinFirmware/Marlin#5127]
Rather than defaulting to 205/60 shouldn't this default to the PLA_PREHEAT_* or ABS_PREHEAT_*?

**Comment by thinkyhead** [comment]
Patched in `RCBugFix`. The `devel-ubl` branch split off from `RCBugFix` in June and is not receiving updates to any parts of the code other than the new leveling during its development. So just focus on that. It may have diverged too much to be readily rebased or to receive a merge from `RCBugFix`, and will need to be integrated more-or-less manually once it's ready.

**Comment by Roxy-3D** [comment]
And if you look...  At the top of G26.cpp you can set `#define`'s for your printer.   So until we can merge back into the RC-8 code base, it shouldn't be too painful for you.
