### ISSUE TITLE
Auto bed leveling  seems not compensate on Y axis

### ISSUE THREAD

**Issue by murdock62** [MarlinFirmware/Marlin#5135]
In first sorry for my bad english !

On my prusa i3, the auto bed leveling work great on X axis but never on y axis.

Is it normal or i made an error somewhere ?

Many thanks.

**Comment by thinkyhead** [comment]
How does it not work? The probing fails? The leveling compensation is wrong?

What version of Marlin are you using?

What variant of auto bed leveling are you using: 3-point, planar, or bilinear?

**Comment by murdock62** [comment]
Hello and thanks for your answer.

I use 1.1.0 RC7 and 3 points variant.

When i'm printing, the z axis move when the head move along x axis, but not when the head move along y axis.

Many thanks again for your help !

**Comment by thinkyhead** [comment]
@murdock62 Please test with `RCBugFix` and see if you still get the same results.
`RCBugFix` is `RC7` plus hundreds of patches.

**Comment by nikki-reprap** [comment]
I have sort of the same problem but it is not compensating on any axis. I am using the latest rcbugfix release. this is my config file.    http://pastebin.com/F6m3f0LD

**\* I have solved my problem I had forgotten to remove the `G28` code from the start script in my slicer

**Comment by murdock62** [comment]
Sorry for this late answer.

Try with rcbugfix but with this version, the print start at 2mm of the bed on the z axis.

I dont understand ...

**Comment by thinkyhead** [comment]
@murdock62 Just to be thorough, re-calibrate your `Z_PROBE_OFFSET_FROM_EXTRUDER` (`M851`) and reset your EEPROM with `M502` and `M500`. Then test again.

**Comment by murdock62** [comment]
It's work !

The EEPROM was not reset ! (Beginner mistake)

The  compensation seem good.

Many thanks for your help !
