### ISSUE TITLE
Extruder fan not starting as the extruder heats up

### ISSUE THREAD

**Issue by mperdue** [MarlinFirmware/Marlin#5147]
I'm having trouble getting the extruder fan to run when the extruder heats up.

I have the following entries in `Configuration_adv.h`
```cpp
#define E0_AUTO_FAN_PIN -1
#define E1_AUTO_FAN_PIN -1
#define E2_AUTO_FAN_PIN -1
#define E3_AUTO_FAN_PIN -1
#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED   255  // == full speed
```
which would seem to indicate that the fan should start at full speed when the temperature hits 50c but it does not.

in the file `pins_AZTEEG_X3_Pro.h` I have
```cpp
// Fans/Water Pump to cool the hotend cool side.
#define ORIG_E0_AUTO_FAN_PIN 5
#define ORIG_E1_AUTO_FAN_PIN 5
#define ORIG_E2_AUTO_FAN_PIN 5
#define ORIG_E3_AUTO_FAN_PIN 5
```
Which seems to match the settings in previous versions

Anyone have any ideas?

**Comment by Sebastianv650** [comment]
-1 means the no fan. You have to replace the -1 by a fan, like ORIG_E0_AUTO_FAN_PIN.

**Comment by mperdue** [comment]
OK, that works (duh...). But then what is the purpose of the ORIG_E#_AUTO_FAN_PIN defines? It seems to be intended to be used to set the values of E#_AUTO_FAN_PIN if they are undefined but that seems to be defeated by having them defined at -1.

**Comment by thinkyhead** [comment]
@mperdue The defines in `Configuration_adv.h` are _overrides_ of the values from the pins files. Overriding the value and setting it to -1 disables it. To use the default setting (i.e., as set by `ORIG_E0_AUTO_FAN_PIN`) just comment out the definition in `Configuration_adv.h`.

``` cpp
/**
 * Extruder cooling fans
 *
 * Extruder auto fans automatically turn on when their extruders'
 * temperatures go above EXTRUDER_AUTO_FAN_TEMPERATURE.
 *
 * Your board's pins file specifies the recommended pins. Override those here
 * or set to -1 to disable completely.
 *
 * Multiple extruders can be assigned to the same pin in which case
 * the fan will turn on when any selected extruder is above the threshold.
 */
```

**Comment by mperdue** [comment]
> The defines in Configuration_adv.h are overrides of the values from the pins files. Overriding the value and setting it to -1 disables it. To use the default setting (i.e., as set by ORIG_E0_AUTO_FAN_PIN) just comment out the definition in Configuration_adv.h.

@thinkyhead Certainly that works, it just seems to me that it would be better to have the lines commented out and add them back if you want to disable them or override them. It's no big deal, it's just different than I do it when I code. I can learn to do things a different way. :-) Thanks.

**Comment by thinkyhead** [comment]
> it would be better to have the lines commented out

Indeed. In fact, my original thought was to replace the pin overrides with option flags, but step 1 was to simply rename the pins and supply defaults. But then, following-through, there will either be no up-front pin overrides, or there will be option flags plus overrides, doubling the number of defines for this feature. So it's a toss-up.

**Comment by mperdue** [comment]
@thinkyhead BTW, the current rcbugfix is working pretty well with my Core-XY machine.
