### ISSUE TITLE
Enhancement: Show Turning direction for knob on LCD when moving axis

### ISSUE THREAD

**Issue by berryelectronics** [MarlinFirmware/Marlin#5166]
I think it would be really great to have a text that Shows like a small turn direction know to the left and right and a +/- next to them to know in which direction the axis will go positive or negative. same could be implemented to the temperature Change.

With the Minimum LCD being 2x16, it could easily fit on the second row while the first one is reserved for the current value.

**Comment by thinkyhead** [comment]
> have a text that Shows like a small turn direction

Where? On the value editing screens?

**Comment by Roxy-3D** [comment]
I would presume it should be on all screens.   (And obviously...  Sensitive to what type of screen it is.   Menu screens can be reversed just as value screens can be.  So to my way of thinking, the +'s and -'s might flip depending on what kind of screen is up and running.)

**Comment by thinkyhead** [comment]
> I would presume it should be on all screens.

Don't forget: When you PRESUME you make a PRES out of U and ME.

**Comment by berryelectronics** [comment]
@thinkyhead i initially thought about the value edit screens.

For LCDs with Buttons, basic arrows like the ones in the HD44780 Charset can be used to indicate which directional button increases/decreases the value, while on knob-based LCDs there has to be like a left/right turn arrow to indicate the increase/decrease. i couldnt find such a char in the aformentioned charset, so it would be a custom character.

**Comment by thinkyhead** [comment]
@berryelectronics Isn't it the case that with arrow buttons both UP and RIGHT increase the value, while DOWN and LEFT both decrease it?

I'm not sure we need to give any indication of this behavior. It's intuitive that this should be the case. Likewise, clockwise should always be the value increase. One tap of any button will clear it up for the uncertain user.

If those are not the case, well, that's why we have `REVERSE_ENCODER_DIRECTION`.

**Comment by berryelectronics** [comment]
@thinkyhead could also be, its long ago since i used a button-based lcd. 

But yeah, you're right. Just bothered me a bit when i switched from RC3->RC7 where suddenly the direction of my knob changed and i accidentally crashed the hotend into the bed a few times.
