### ISSUE TITLE
LCD Blinking X,Y,Z (axis letters)

### ISSUE THREAD

**Issue by AndKe** [MarlinFirmware/Marlin#5172]
Why is the LCD (44780 based) continuously blinking those three letters ? (1.1.0 , RC7)

**Comment by AndKe** [comment]
Ok, I found it has something todo with homing https://github.com/MarlinFirmware/Marlin/pull/3782

**Comment by thinkyhead** [comment]
If not homed they blink. And if the steppers power down (as they do after a period of inactivity) they lose their precise position and may be moved easily by hand. The labels blink to indicate that a new `G28` will be required for positional certitude.

**Comment by AndKe** [comment]
May I suggest less annoying way ?  -, displaying  "X ?  Y ? Z ?"  instead of blinking all the time it's idle.

**Comment by thinkyhead** [comment]
It was once like that, but it was requested by many to keep the coordinates on-screen.

**Comment by AndKe** [comment]
yes, that's strange . why would we prefer to see position numbers - especially when notifying user that they are not reliable ?

**Comment by thinkyhead** [comment]
I prefer it because I don't like to fly blind. I can't speak for others.
