### ISSUE TITLE
Filament change....Did it work?

### ISSUE THREAD

**Issue by jaysonkelly** [MarlinFirmware/Marlin#5173]
With filament change enabled, there is a menu option available in the Tune menu while printing to change the filament. It works, but nothing happens when you click the menu item. Thinking that nothing happened I selected the option again and didn't know until i turned on the serial that it was Enqueueing the M600 command. I think it would be great if upon selecting the change filament command the menu returned to the status screen and a message indicating that filament change has been Enqueued shown on the screen. I imagine this is an easy fix...Thoughts?

**Comment by Roxy-3D** [comment]
> I think it would be great if upon selecting the change filament command the menu returned to the status screen and a message indicating that filament change has been Enqueued shown on the screen. I imagine this is an easy fix...Thoughts?

My thinking is the LCD Screen should stay in a filament change control type screen until the filament change is completed.    That would make more sense to me.

**Comment by jaysonkelly** [comment]
That would be great as long as it went to that screen as soon as the filament change menu were selected. As it is now, nothing happens.

**Comment by thinkyhead** [comment]
> returned to the status screen and a message

That's a good point. Obviously we need to wait for the current move to complete, so it's not possible to go to filament change immediately, but a message "`Fil. Change Queued`" could be shown right away. I'll make this patch soon.

**Comment by thinkyhead** [comment]
It so happens that the first screen for filament change says:

```
Wait for start
of the filament
    change
```

…so the above patch jumps straight to that screen, which will not time-out to the status screen.

**Comment by Barrocas** [comment]
Could it be shorter, like "Waiting for filament change"?

**Comment by thinkyhead** [comment]
@Barrocas It is what it is, and has already been translated into all the supported languages. You can always customize it in your personal copy.
