### ISSUE TITLE
New G30 code does not check if probe position is possible

### ISSUE THREAD

**Issue by manianac** [MarlinFirmware/Marlin#5181]
@thinkyhead, Commit dcfd7c69e8f6eaa286e6f0d6f924608c390f5f31 does not constrain the desired probe position.

My probe is pretty far off from my nozzle (-22,37) and if I ask it to do what should be an invalid position Marlin then disregards software endstops, slams into the endstop with skipped steps, and leaves me with
`Send: G30 X20 Y20`
`Recv: Bed X: 20.00 Y: 20.00 Z: 0.98`
`Recv: X:42.00 Y:-17.00 Z:9.15 E:0.00 Count X: 3360 Y:-1360 Z:36600`

We could limit the position before `probe_pt` is called, or limit it inside there.

**Comment by Roxy-3D** [comment]
G30 probably should not have been assigned to a single point probe function.   But be that as it may...   It needs a G28 before it can operate correctly.   Did you do a G28 before invoking G30?

If not...  We could change this to be a 'Feature Request'.   It might not be unreasonable for G30 to automatically invoke a G28 if the machine doesn't know its X & Y position.

**Comment by manianac** [comment]
Sorry for the late response.  I feel a single probe point is necessary to have, despite whatever code it may be.

Yes this is confirmed to happen right after G28.  It is still trying to move outside the build area.

```
[...]
Send: G28
Recv: X:0.00 Y:0.00 Z:0.00 E:0.00 Count X: 0 Y:0 Z:0
[...]
Send: G30 X10 Y10
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: Bed X: 10.00 Y: 10.00 Z: -15.95
Recv: X:32.00 Y:-27.00 Z:9.15 E:0.00 Count X: 2560 Y:-2160 Z:36600
[...]
```

Issuing this on my setup causes it to try to move to -27 on Y and slam the endstop.

Perhaps in `probe_pt()` function, should we do a check for bounds before:

```
2174    // Move the probe to the given XY
2175    do_blocking_move_to_xy(x - (X_PROBE_OFFSET_FROM_EXTRUDER), y - (Y_PROBE_OFFSET_FROM_EXTRUDER));
```

Or should we be using a something different?  Maybe something that uses `clamp_to_software_endstops`?

And possibly be using `LOGICAL_POSITION`?  I'm unsure if G30 should respect a home offset.

**Comment by thinkyhead** [comment]
We now have a function for general use, `position_is_reachable`.
I should just add a call to that in `G30`, methinks.

> I'm unsure if G30 should respect a home offset.

Coordinates given to `G30` will refer to the current coordinate space. So if the current position is 100, 100 (by whatever cause) then probing at 90, 90 will probe -10, -10 away from the current position.
