### ISSUE TITLE
Extruder -> Feeder

### ISSUE THREAD

**Issue by landodragon141** [MarlinFirmware/Marlin#5185]
So this isn't a huge deal but it could be valuable to re-identify "extruder" as "feeder" since this is much more indicative of its role. In my mind the "extruder" should be a combination of feeder and hot end. Obviously this goes against the current convention but hey look how many time they've redefined the name for filament printers. Maybe we could be trend setters haha!

**Comment by MrExo3D** [comment]
Extruder and hotend is my preference

**Comment by ghost** [comment]
My image:

| Extruder | Feeder | Hotend |
| --- | --- | --- |
| ![featured1](https://cloud.githubusercontent.com/assets/15308844/20115235/d3de80b8-a63a-11e6-98e4-07c0a0a6809b.png) | ![featured2](https://cloud.githubusercontent.com/assets/15308844/20115241/da24f592-a63a-11e6-97e8-d0397cb4d96a.png) | ![c_v6-1 75-u-3-1000x1000 1 3](https://cloud.githubusercontent.com/assets/15308844/20115244/de8cbec6-a63a-11e6-9bbd-bf4f973747f5.png) |

**Comment by landodragon141** [comment]
That's exactly my thought.

**Comment by MrExo3D** [comment]
Extruder and Hotend are the common words used currently, checkout E3D website.. its Hotend and Extruder, not feeder

trying to change it to feeder just will end up confusing people..
there isnt even a need to call the entire assembly anything specific. unless you want to call it a gantry i suppose.

**Comment by landodragon141** [comment]
I disagree. There are a number of people that have been thinking along the same lines already. Tom's3D is a notable example. Besides one of the biggest issues we are fighting in Marlin right now (from a user standpoint) is how hard it is to understand. To this end I have been working on the documentation side of Marlin to try and flesh it out and make it more easy for the layman to understand.

**Comment by Roxy-3D** [comment]
@landodragon141 

> To this end I have been working on the documentation side of Marlin to try and flesh it out and make it more easy for the layman to understand.

Would you like to do a preliminary set of documentation for the UBL code?  I'll edit and expand what ever you can get in place.    Probably the most important thing to do initially is get good directions for generating an accurate Mesh.

**Comment by landodragon141** [comment]
@Roxy-3D Sure I'll see what I can do. Is there anything started or are we working from a blank page?

**Comment by thinkyhead** [comment]
> There are a number of people that have been thinking along the same lines already

For now I'd suggest including a note in the documentation that an extruder consists of one or more feeders plus one or more hotends. Sometimes a single hotend has multiple steppers (feeders), and sometimes a single stepper (feeder) has more than one hotend. For legacy reasons we still have the `EXTRUDERS` setting in Marlin. That gets further broken down into `E_STEPPERS`, `HOTENDS`, and so on, depending on the other settings, such as `SINGLENOZZLE`, `MIXING_EXTRUDER`, etc.

In future —for the Marlin 1.2.x branch— we'll revisit the verbiage.
