### ISSUE TITLE
Nozzle extruding at HOMING POSITION after reaching model reference temperature...

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#5195]
Hi all,

I wanted to give print at 205 degrees CUBE model. After nozzle reaching to 202 degree its extruding filament nearly 4mm because EXTRUDER STEPPER is rotating at 202 degrees. 

I wanted that after giving print its should reach to reference temperature and start to print with nearly 1mm extruding at HOMING position.

Please tell me where can I change in MARLIN VERSION 1.0....

**Comment by Kaibob2** [comment]
I don't get it

**Comment by Shrikant888** [comment]
![s](https://cloud.githubusercontent.com/assets/22236971/20176455/e187cfb0-a76d-11e6-83d4-5745faa427ea.jpg)

**Comment by Shrikant888** [comment]
I wanted that there should be 1mm or no extrusion at ARROW MARKED point and then start to print the model. What shall I do?

Using MARLIN V1.0.

**Comment by Blue-Marlin** [comment]
Just tell Marlin what to do. Alter the start script in your host or slicer.

**Comment by Kaibob2** [comment]
This could be a start script which primes the nozzle 15mm above the bed right before the print starts.

```
G28 ;home all axes
G91 ;Absolute Mode
G1 Z10 F240 ;lift Z 10mm
G90 ;Relative Mode
T0 ;Select First Extruder
G91 ;Relative Mode
G1 E15.0000 F150 ;Extrude 15mm to prime the nozzle
G90 ;Absolute Mode
G4 P3000 ;Wait 5sec to remove the filament blob or string from nozzle with tweezer
M117 Print started...    ;LCD Info
```

**Comment by Shrikant888** [comment]
Thats good. 

Is there any ways to change this problem in MARLIN?

**Comment by Kaibob2** [comment]
No

**Comment by Shrikant888** [comment]
I am testing 2 printers.. One is default and another is modified with MARLIN but both I am using CURA as default software.

I have print at a time for two printers and found that MODIFIED board is extruding 2-3mm at HOMING position and for Default printer there is no extrusion at HOMING position. So, I have flashed with MARLIN. So there should be some thing which is coming from MARLIN. I guess not from CURA.

Please any one can find it.. It could be grateful for me sir.

**Comment by Shrikant888** [comment]
How to solve this "z wobble"?

**Comment by Kaibob2** [comment]
MARLIN only does what you tell it to do. As long as there is no GCODE to process there will be no extruder movements which cause this blob at the beginning. Take a close look at your GCODE which gets sent to your printer. 
MARLIN won't extrude a few milimeters at the beginning of each print just for fun and no reason!

**Comment by Kaibob2** [comment]
This is no Marlin associated issue.
It will be better if discuss this at http://forums.reprap.org

**Comment by ruggb** [comment]
maybe this is enabled
EXTRUDER_RUNOUT_PREVENT

**Comment by thinkyhead** [comment]
This shirt is popular with people who are software engineers and web developers.
![image](https://cloud.githubusercontent.com/assets/698003/20334126/59de3e46-ab7d-11e6-83af-7734fbe247dd.png)
We are writing low-level code. We don't generally want to do customer support, but fix real bugs.
