### ISSUE TITLE
Can somebody explain this below MARLIN VERSION 1.0 code...

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#5196]
```cpp
#define FWRETRACT  //ONLY PARTIALLY TESTED
#ifdef FWRETRACT
  #define MIN_RETRACT 0.1                //minimum extruded mm to accept a automatic gcode retraction attempt
  #ifdef DIRECT_DRIVE_EXTRUDER
    #define RETRACT_LENGTH 2               //default retract length (positive mm)
    #define RETRACT_FEEDRATE 170            //default feedrate for retracting (mm/s)
    #define RETRACT_ZLIFT 0                //default retract Z-lift
    #define RETRACT_RECOVER_LENGTH .2      //default additional recover length (mm, added to retract length when recovering)
    #define RETRACT_RECOVER_FEEDRATE 8     //default feedrate for recovering from retraction (mm/s)
  #else
    #define RETRACT_LENGTH 1.2               //default retract length (positive mm)
    #define RETRACT_FEEDRATE 20            //default feedrate for retracting (mm/s)
    #define RETRACT_ZLIFT 0                //default retract Z-lift
    #define RETRACT_RECOVER_LENGTH 0       //default additional recover length (mm, added to retract length when recovering)
    #define RETRACT_RECOVER_FEEDRATE 2     //default feedrate for recovering from retraction (mm/s)
  #endif
#endif
```

**Comment by Kaibob2** [comment]
This is the part of where you can enable Firmware Retract and set the parameters for it.

``` cpp
#define FWRETRACT //ONLY PARTIALLY TESTED
```

means Firmware Retract enabled

``` cpp
//#define FWRETRACT //ONLY PARTIALLY TESTED
```

means Firmware Retract disabled.

When you enable Firmware retract all retraction movements of the extruder will be handled by the firmware (Marlin) and you should disable Retraction in your Slicer.
Btw.: You already have an answer [here](http://forums.reprap.org/read.php?1,721924,721924#msg-721924)

**Comment by Shrikant888** [comment]
![cura](https://cloud.githubusercontent.com/assets/22236971/20207245/f41b3e02-a80b-11e6-9718-b84cc4e9a6e5.png)

**Comment by Shrikant888** [comment]
![2](https://cloud.githubusercontent.com/assets/22236971/20207264/1ef370c2-a80c-11e6-94a6-abdf14c4e165.jpg)

**Comment by Shrikant888** [comment]
what is 'z wobble'?
How to solve it?

**Comment by Kaibob2** [comment]
[Here](http://lmgtfy.com/?q=Z-wobble)

**Comment by Kaibob2** [comment]
Change
#define FWRETRACT //ONLY PARTIALLY TESTED
to
//#define FWRETRACT //ONLY PARTIALLY TESTED
in `Configuration_adv.h`

This will disable the firmware retract in Marlin. You should use the CURA retract settings.

**Comment by Shrikant888** [comment]
So above cutting on model is due to RETRACT or WOBBLE.

Now as I say RETRACT is ENABLED in CURA and MARLIN.

Will it be effecting this problem??

or

if WOBBLE then what parameter shall I change? Mechanical Z setting?

**Comment by Kaibob2** [comment]
It is presumably due to retract. Do you even read what get's posted here?

**Comment by Kaibob2** [comment]
Sorry, i'm out. This is no Marlin associated issue.
It will be better if you discuss this at http://forums.reprap.org

**Comment by landodragon141** [comment]
The retract in CURA is software retraction. The retract in Marlin is firmware retraction. If you are slicing with CURA disable firmware retraction in marlin. Z wobble is cause by bad z axis. It means that there is a mechanical issue. Google it you will find help.

**Comment by landodragon141** [comment]
In regards to your print above you might be printing too fast, too high acceleration, too high temperature, too much flow. I would advise that you stop trying to print pretty things and focus on getting your printer properly calibrated. There are a number of great guides linked in the Marlin documentation which you can find at marlinfw.org.

**Comment by Shrikant888** [comment]
Hi All!!!

I have this code RETRACTION in MARLIN V1.0....

HOW TO DISABLE IT? Like what line shall I comment to DISABLE RETRACTION?

``` cpp
#define FWRETRACT //ONLY PARTIALLY TESTED
#ifdef FWRETRACT
#define MIN_RETRACT 0.1 //minimum extruded mm to accept a automatic gcode retraction attempt
#ifdef DIRECT_DRIVE_EXTRUDER
#define RETRACT_LENGTH 2 //default retract length (positive mm)
#define RETRACT_FEEDRATE 170 //default feedrate for retracting (mm/s)
#define RETRACT_ZLIFT 0 //default retract Z-lift
#define RETRACT_RECOVER_LENGTH .2 //default additional recover length (mm, added to retract length when recovering)
#define RETRACT_RECOVER_FEEDRATE 8 //default feedrate for recovering from retraction (mm/s)
#else
#define RETRACT_LENGTH 1.2 //default retract length (positive mm)
#define RETRACT_FEEDRATE 20 //default feedrate for retracting (mm/s)
#define RETRACT_ZLIFT 0 //default retract Z-lift
#define RETRACT_RECOVER_LENGTH 0 //default additional recover length (mm, added to retract length when recovering)
#define RETRACT_RECOVER_FEEDRATE 2 //default feedrate for recovering from retraction (mm/s)
#endif
#endif
```

Please tell...

**Comment by landodragon141** [comment]
Comment out this line

``` cpp
#define FWRETRACT
```

->

``` cpp
//#define FWRETRACT
```

**Comment by Shrikant888** [comment]
Ya ok sir
