### ISSUE TITLE
Getting cuts in model

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#5197]
![2](https://cloud.githubusercontent.com/assets/22236971/20174843/db8119f8-a765-11e6-8544-375940c8f76f.jpg)

**Comment by Blue-Marlin** [comment]
Does not look like a Marlin specific problem. Search for 'z wobble' and 'z banding'.

**Comment by Kaibob2** [comment]
To me it looks like that there is not only a wobble or banding problem. Also consider tweaking temperature and retract settings in your slicer.
I would suggest calibrating your printer with much less complex models at first!

**Comment by Shrikant888** [comment]
Thanks for reply..

Sowhat is ' z wobble' and 'z banding'  ?

Where to change in program MARLIN or CURA..?

**Comment by Shrikant888** [comment]
![h](https://cloud.githubusercontent.com/assets/22236971/20425946/f30a97d2-ada2-11e6-81d9-85d468ff7568.jpg)

**Comment by emartinez167** [comment]
STOP! Do you even read the emails?

Go to the REPRAP forum!!!

**Comment by Kaibob2** [comment]
@Shrikant888 Stop bugging around with these kind of issues! I also told you a few times. What's up with you?
THIS IS NO MARLIN RELATED ISSUE. CHECK YOUR MECHANICS!

**Comment by Shrikant888** [comment]
Ya ya ok sir. I thought to get some help. I am beginner. Trying since from a month.

Alright!!!

**Comment by emartinez167** [comment]
Bugger off!!! Or I bet one of the admins will kick you out for good!

**Comment by emartinez167** [comment]
And don't say I didn't warn you you would piss some people!!!

**Comment by Kaibob2** [comment]
Only to make it absolutely clear:

You will always get help here, but never if you unmistakably convey to everybody that you are too lazy to read, learn, try and make progress on your own. Maybe this hobby is just not the right one for you.

Like @thinkyhead stated "This platform is for improving Marlin and fixing issues and not for end user support"

Goodbye and good luck.

**Comment by thinkyhead** [comment]
It doesn't mean we don't love you, @Shrikant888. It's just that there are better places to ask for help with these kinds of issues. As when you have a problem with your car, you don't phone up the designer of the car, you find a mechanic or someone who owns the same car.

Or course, if you do find some bug or error in Marlin, please don't hesitate to report it.

For assistance with printing issues, I find the best resources are:
- The [RepRap Forums](http://forums.reprap.org) — Use the "search" function.
- The Facebook groups [RepRap](https://www.facebook.com/groups/5809198019/) and [RepStrap](https://www.facebook.com/groups/240122566171878/)
- And of course, [Google](https://google.com)! Search for articles on Calibration, Tuning, Etc.
