### ISSUE TITLE
Development question:  which IDE

### ISSUE THREAD

**Issue by stigjoergensen** [MarlinFirmware/Marlin#5198]
Hi gang

Which IDE are you using?

im currently working with arduino standard IDE - seems good for small projects - but at the magnitude of Marlin - i think its a bit hard to work with - esp when the file count is higher than tabs abailable, its a hazzle to scroll in the small menu created... 

That the reason behind this question - there must be alternatives out there - im thinking about going to Visual Studio (which im all ready using) but perhaps there is even better options out there

Thanks

**Comment by Blue-Marlin** [comment]
Most of us seem to use Arduino IDE from Arduino.cc (Not Adruino.org).
For just compiling and uploading the source, for most, it's fine to just click the arrow button.
But I suppose all serious developers use external editors (like Notepad++ on Windows).

Makefile users seem to be rare.

With PlatformIO you'll have about the same problem as with Arduino IDE if you don't like Atom.

Eclipse based IDEs seem to be much to complex for the average user - especially until things are set up.

**Comment by Drakelive** [comment]
Hi 

I use this plugin for eclipse for many months: [Arduino Eclipse ](http://eclipse.baeyens.it)
I finally changed my life.

drk

**Comment by Sebastianv650** [comment]
I'm using the Arduino IDE, because normally the code changes I do are not that big (including LIN_ADVANCE). It's very comfortable to change a little bit, do an upload, see how the code behaves and continue coding. The long list of files to scroll down is anoing, that's true.

For studying new code sections of Marlin, I use Notepad++. I like that you can mark a variable and it will highlite all other sections where it is used. That makes it very easy to see the workflow. And Notepad++ is great for comparisons between versions etc.

**Comment by Drakelive** [comment]
With Arduino Eclipse may integrate the Marlin project with git. This way you can receive updates and interact with the community.
Eclipse also has a real environment for debugging.

**Comment by Blue-Marlin** [comment]
Ups.
Your linking to (http://eclipse.baeyens.it/) here, made them believe in  a denial of service attack! :-)
The Arduino IDE problem seems to be bigger then I supposed.

I have been on the site right after you sent the link. While reading it got slower and slower and braked together.

**Comment by gcormier** [comment]
Visual Studio Community edition with the Arduino plugin

**Comment by Drakelive** [comment]
Not work on linux machine  :-(

**Comment by landodragon141** [comment]
When I edit the Documentation I actually do it online in Github lol

**Comment by stigjoergensen** [comment]
seems we have most of the tools now - will have a look at them and see what fit me the best..

thanks for sharing...

**Comment by thinkyhead** [comment]
> The long list of files to scroll down is [annoying], that's true.

For Marlin 1.2.x it will only get better.
https://github.com/MarlinFirmware/Marlin/tree/breakup-marlin-idea/Marlin/gcode

P.S. I do all my development using _Sublime Text 3_, building with the latest _Arduino IDE_ (currently 1.6.12). There's probably an AVR build plugin for _Sublime Text 3_ but I haven't bothered to research it, as it's simple to just use Arduino IDE for building. If _Sublime Text 3_ didn't exist I'd be using _TextMate_. And if that didn't exist I'd probably be using _BBEdit_.
