### ISSUE TITLE
MarlinFirmware 1.1.0 RC7 missing servo endstop

### ISSUE THREAD

**Issue by kaliboe** [MarlinFirmware/Marlin#5208]
I am following a tutorial https://www.youtube.com/watch?v=6msLOR_EfKc where they explain to change some setting at the servo endstop. Now on version 1.1.0 RC7 I don't find this option anymore. please help

**Comment by Blue-Marlin** [comment]
That video was published 11.11.20 **13**.
It is related to a 3 years old Marlin version .
Please allow us some progress and forget about that video.

**Comment by boelle** [comment]
add dont use RC7.. use latest RCBugfix

Most of the settings in configuration.h comes with a explanation that does the trick. Just take a deep breath and take it slowly

**Comment by kaliboe** [comment]
of course I allow progress but the option servo endstop is still integrate in RC7, only the option to angle your servo is not in there anymore, that's strange.

**Comment by Blue-Marlin** [comment]
Open your eyes.

> // Z Servo Probe, such as an endstop switch on a rotating arm.
> //#define Z_ENDSTOP_SERVO_NR 0
> //#define Z_SERVO_ANGLES {70,0} // Z Servo Deploy and Stow angles

**Comment by kaliboe** [comment]
thanks for opening my eyes Blue-Marlin
