### ISSUE TITLE
Please see the model.. Some lines are coming during printing time...

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#5220]
![u](https://cloud.githubusercontent.com/assets/22236971/20292913/7c6dac5a-ab17-11e6-8148-540077f08dd7.jpg)

**Comment by Shrikant888** [comment]
Hi World!!!

This is new printer but getting some garbage lines.. Please see it..

Where could be the problem??

CURA or MARLIN or Mechanical settings??

If mechanical settings then Is it Z wobble??

How to resolve it?? Shall I reassemble all?

Please reply

**Comment by MrExo3D** [comment]
This may be better posted to a more relevant forum. reprap.com 3dprintboard.com
good luck

**Comment by Shrikant888** [comment]
Ya ok sir
