### ISSUE TITLE
LCD screen and steps per mm 

### ISSUE THREAD

**Issue by bluffchuffer** [MarlinFirmware/Marlin#5225]
I am using a Ramps with lcd screen on a small milling machine - 3 axis and all are leadscrew driven,  but find the REPRAP LCD display for the X or Y steps per mm in the control/motion menu can only display under 999, ie does not show the 1000's digit. Repetier or Pronterface can set the eeprom value to 1600, which is what I require.
The Z axis does not have this problem, so imagine that it must be in the LCD setting somewhere - Where can I alter it?

**Comment by ghost** [comment]
There is two solutions.
You are able to test those.

A: Introduce a +1234.56 format, and use it for all the axes and e
https://github.com/esenapaj/Marlin/commit/1f669205107f7e32eca75342463892f15dbf0a7c

B: Use +1234.5 format also x and y
https://github.com/esenapaj/Marlin/commit/f47893b35e0bce6928e33a3709092c326cb9fa47

**Comment by bluffchuffer** [comment]
Thanks,
I used B below.

**Comment by ghost** [comment]
@thinkyhead 
About patch for this, do you submit and merge it? Or I submit?

**Comment by bluffchuffer** [comment]
Hello,
If I am thinkyhead then please submit and merge it. I know little enough 
about all this stuff.
Thanks

**Comment by thinkyhead** [comment]
@esenapaj I think your first solution (A) is better, because steps/mm should be as accurate as possible, down to 100ths of a mm. You may submit it, if you like!

**Comment by ghost** [comment]
I've submitted a patch by solution (A) just now.
