### ISSUE TITLE
Requested feature: move away the nozzle when pausing printing

### ISSUE THREAD

**Issue by alejandro-anv** [MarlinFirmware/Marlin#5266]
If you pause the print from the menu, the heat of the nozzle will melt the material it is touching. When pausing the print it would be very usefull to home the nozzle and remember the previous position to return to this when resuming. 

Also, it would be usefull a menu option option for "pause at the end of the layer" for pausing (and homing) the print at the next z movement.

**Comment by Kaibob2** [comment]
@alejandro-anv See #4627

**Comment by alejandro-anv** [comment]
Thank you. I will comment on this thread.
