### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by DjDemonD** [MarlinFirmware/Marlin#5277]
A recent thread on reprap forum http://forums.reprap.org/read.php?1,724175,724998#msg-724998 has asked if we would donate to the Marlin project, with a view to moving to 32 bit. I am happy to as are several others. How do I go about it?

**Comment by MagoKimbra** [comment]
I know that Scott Lahteine is working, and soon we will have an official version of Marlin on 32Bit .. Just wait ...

**Comment by DjDemonD** [comment]
So donations not necessary or wanted?

**Comment by boelle** [comment]
Donations are possible

@thinkyhead what are the page where we can donate?

**Comment by boelle** [comment]
@DjDemonD 

https://www.gofundme.com/zmh9h9vc

**Comment by boelle** [comment]
@DjDemonD and if you are able to do code then you can also help by solving bugs... those issues marked with red and orange in the issue list

or by testing if those bugs are still there

**Comment by DjDemonD** [comment]
I'm not a programmer but I am happy to test things, and have done a little in the past.

**Comment by thinkyhead** [comment]
Also http://patreon.com/thinkyhead 😸

**Comment by thinkyhead** [comment]
P.S. I have also set up a Twitter for MarlinFirmware, which you can find at —of course— http://www.twitter.com/MarlinFirmware. Follow us!

**Comment by thinkyhead** [comment]
Aaaaand… I finally got it together to understand our documentation project, set up Jekyll on my computer, etc., and have updated the [README](https://github.com/MarlinFirmware/MarlinDocumentation/blob/master/README.md) to help others to get going. So if anyone wants to contribute some documentation on your favorite topics please visit

- https://github.com/MarlinFirmware/MarlinDocumentation

I can also add you to the @MarlinFirmware/documentation-maintainers team.

**Comment by DjDemonD** [comment]
Thanks I'll have a think about that. Probably make a donation for now, but if you need anything tested on corexy let me know.
