### ISSUE TITLE
Bowden Filament change

### ISSUE THREAD

**Issue by tibuck** [MarlinFirmware/Marlin#5278]
Hi team, First off Thank you for all the hard and fantastic work you been doing for use all to use a great open 3d printer firmware, with out you guys I wouldn't have a 3d printer.  on one of my printers I use a dual Bowden extruders, Doing filament change is more then a PITA, i was thinking if there was a filament change right in the menu where I could set X length  of filament to retract at a faster speed rate example extruder 1 filament change 500mm and so on, and something like that for the second extruder as-well. would that be a hard feature to  add?

**Comment by Barrocas** [comment]
New feature - Change filament from the menu when not printing #5262

## 

Cumprimentos,
D.er Hugo Barrocas

**Comment by tibuck** [comment]
Great ill give that a try thanks a bunch.

**Comment by tibuck** [comment]
hahaha looks like that was already add to configuration_adv.h Whooo hooooo i'm a happy man . only re-enforces  that the Marlin team is hard at work!

**Comment by tibuck** [comment]
I tried adding the codes to marlin but when I compile it gives me errors maybe in not putting everything exactly where they should be??  

          STATIC_ITEM(MSG_FILAMENT_CHANGE_Wait, true, false);
MSG_FILAMENT_CHANGE_Wait was not declared in this scoop

**Comment by thinkyhead** [comment]
Sorry this issue got lost. I was indisposed during this period. I'm just going through old issues now to resolve them. Please re-open if this is still something needing help!
