### ISSUE TITLE
Missing newline in capabilities (M115)

### ISSUE THREAD

**Issue by christianh17** [MarlinFirmware/Marlin#5283]
Hi!

I just installed a new rcbugfix (Commit 14b7418). 
First tests did not show any problems :-).
But there is one very minor thing: Im M115 there are some new lines missing:
```
SENT: M115
RECEIVED: FIRMWARE_NAME:Marlin 1.1.0-RCBugFix (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:XXXX EXTRUDER_COUNT:1 UUID:effea50a-d725-11e5-ab30-625662870761
RECEIVED: Cap:EEPROM:1
RECEIVED: Cap:AUTOREPORT_TEMP:0
RECEIVED: Cap:PROGRESS:0Cap:AUTOLEVEL:1
RECEIVED: Cap:Z_PROBE:1
RECEIVED: Cap:SOFTWARE_POWER:0
RECEIVED: Cap:TOGGLE_LIGHTS:0
RECEIVED: Cap:EMERGENCY_PARSER:0
RECEIVED: ok
```
So there is a missing newline between PROGRESS and AUTOLOVEL. I think the problem for this part is in the following section (marlin_main.cpp):

    _// PROGRESS (M530 S L, M531 <file>, M532 X L)
    SERIAL_PROTOCOLPGM("Cap:");
    SERIAL_PROTOCOLPGM("PROGRESS:0");_

The last line should be (double L):
_SERIAL_PROTOCOLLNPGM("PROGRESS:0");_

And for the missing newlines in the first part in language.h 
_#define MSG_M115_REPORT                     "FIRMWARE_NAME:Marlin " DETAILED_BUILD_VERSION " SOURCE_CODE_URL:" SOURCE_CODE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" MACHINE_NAME " EXTRUDER_COUNT:"_

should be added the "\n" (But I do not know if it is possible here).

And: You are doing a very great job! I love marlin and the idea of an open source firmware!

Regards
Christian

**Comment by thinkyhead** [comment]
Patched.

> I love marlin and the idea of an open source firmware!

Me too! In fact, that's why I'm here. Open source rocks.
