### ISSUE TITLE
CoreXY Z Axis won't move during print

### ISSUE THREAD

**Issue by MH15** [MarlinFirmware/Marlin#5302]
Hello everyone! I've been building a custom CoreXY printer and just finished assembling it. Through the software I can move the Z axis perfectly fine; the endstops work as well (I have the Full Graphic Smart Controller). The problem arises when I try to print something. The bed won't move so the printer keeps piling more and more layers on top of each other.

Anybody know why the printer might be doing this? 

Thanks!

**Comment by landodragon141** [comment]
Is your Z axis inverted? The g-code might be trying to push it up when it's already at the endstop.

**Comment by MH15** [comment]
It might be... when I was assembling the printer I reversed the z motor plug on the RAMPS unit because the display read 200mm when the bed was at the extruder (the position I wanted it to be 0mm, if that makes any sense). Let me go check that.

**Comment by MH15** [comment]
How would you suggest fixing that in the firmware

**Comment by landodragon141** [comment]
Invert the value of this line under motor movement:
`#define INVERT_Z_DIR true`

**Comment by landodragon141** [comment]
i.e. if it's currently true change it to false and vice versa.

**Comment by MH15** [comment]
I changed that and the z axis is now reading the proper position (0 when bed is at extruder, 200 when it is at the bottom) but during printing the screen says the z axis is at 0.3mm and not moving.

**Comment by MH15** [comment]
Well I fixed this issue, your code and some other things helped. On to the next!

Thanks
