### ISSUE TITLE
[Feature Request] Show chamber temp on LCD

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#5307]
On the Ramps i have a spare temp input

could be nice to show the chamber temp or maybe electronics temp on the LCD without enabling a "dummy" extruder

**Comment by thinkyhead** [comment]
I thought in Denmark it was required that everyone learn to code. With the current Marlin code base, you can pretty much duplicate what is there, tweak it a little, and – voila!

**Comment by boelle** [comment]
"I thought in Denmark it was required that everyone learn to code."

Sadly no
