### ISSUE TITLE
PID_PARAMS_PER_HOTEND in config

### ISSUE THREAD

**Issue by hexxter** [MarlinFirmware/Marlin#5309]
Hi,

how can i write two different autopid (Configuration.h) for two (different) heaters?

BR hexxter

**Comment by thinkyhead** [comment]
There's no configuration option to set separate default PIDs for different nozzles. But Marlin does support separate active PID values.

You can set them with `M301`, and you can calibrate them with `M303`. You can save them to the EEPROM with `M500`, and use `M503 S0` to capture your settings as GCode for use later.
```cpp
/**
 * M301: Set PID parameters P I D (and optionally C, L)
 *
 *   P[float] Kp term
 *   I[float] Ki term (unscaled)
 *   D[float] Kd term (unscaled)
 *
 * With PID_EXTRUSION_SCALING:
 *
 *   C[float] Kc term
 *   L[float] LPQ length
 */
```
```cpp
/**
 * M303: PID relay autotune
 *
 *       S<temperature> sets the target temperature. (default 150C)
 *       E<extruder> (-1 for the bed) (default 0)
 *       C<cycles>
 *       U<bool> with a non-zero value will apply the result to current settings
 */
```
