### ISSUE TITLE
no Fan on kossel xl after uploading RCbugfix 7

### ISSUE THREAD

**Issue by mihadongle** [MarlinFirmware/Marlin#5322]
Hallo on my kossel XL after update the new file and i staurt printing the hotend goes up and up  and no fan starts!! When i downgrade to the original Marlin of my kossel the Fan works fin. On Pronterface i can´t sending no commands when i write in pronterface m119,m117,m28,m29 the koseel do nothing!! when i klick the home buttom then the kossel drive home:

**Comment by thinkyhead** [comment]
What is your setting for `E0_AUTO_FAN_PIN`?

**Comment by thinkyhead** [comment]
> when i write in pronterface m119,m117,m28,m29

Weird. `M119` should print out your endstop status. `M117 Hello` should say "Hello" on your LCD controller. `G28` should home. `G29` should do bed leveling, if configured.

Please post your `Configuration.h` file. (You may need to rename it `Configuration.txt` to be able to drop it on the edit box and upload.)

**Comment by mihadongle** [comment]
i didn't find the `E0_AUTO_FAN_PIN` in which file is that?
yesterday i have tested again
- M119 is OK
- M28 he do nothing
- M29 he do nothing
- M114 he do nothing
- When i write `M106 S255` the FAN Starts to run!!
- When i turn manual FAN on, on the LCD  then he start and the PWM is also OK
- When i start to print or in Pronterface Set the Temp to 185C° the FAN DIDN'T start!!!
- On Pronterface Push Home button he do!
- On the LCD Autobed leveling, home, start fan, PWM Fan all OK!!!

**Comment by mihadongle** [comment]
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/621446/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/621447/Configuration.txt)

**Comment by lrpirlet** [comment]
@thinkyhead I guess you mean G28 and G29 instead of M28 and M29...
@mihadongle Mind to tell us what realy you want to do... not that I have the answer, note, but obviously something is unclear...

ref from Marlin_main.cpp
``` C++
/**
 * -----------------
 * G-Codes in Marlin
 * -----------------
 *
 * Helpful G-code references:
 *  - http://linuxcnc.org/handbook/gcode/g-code.html
 *  - http://objects.reprap.org/wiki/Mendel_User_Manual:_RepRapGCodes
 *
 * Help to document Marlin's G-codes online:
 *  - http://reprap.org/wiki/G-code
 *  - https://github.com/MarlinFirmware/MarlinDocumentation
 *
 * -----------------
 *
 * "G" Codes
 *
 ... some lines removed ...
 * G28 - Home one or more axes
 * G29 - Detailed Z probe, probes the bed at 3 or more points.  Will fail if you haven't homed yet.
 ... some lines removed ...
 * "M" Codes
 *
 * M28  - Start SD write: "M28 /path/file.gco". (Requires SDSUPPORT)
 * M29  - Stop SD write. (Requires SDSUPPORT)
... some lines removed ...
 * M114 - Report current position.
... some lines removed ... * M119 - Report endstops status.
 * M120 - Enable endstops detection.
... some lines removed ... *
 */
```

**Comment by thinkyhead** [comment]
> i didn't find the `E0_AUTO_FAN_PIN` in which file is that?

It replaces `EXTRUDER_0_AUTO_FAN_PIN`, which I see you are not using anyway.

Are you using `1.1.0-RC7` (`RC` branch) or are you using the `RCBugFix` branch?

In the "official" Marlin Firmware, _**the print fan**_ does not come on automatically when you start heating. You have to use `M106` for that. Perhaps the Marlin you used before was from a different fork?

_**The fan that points to the extruder's heat-sink fins**_ is usually connected to an output that is _always on_, but it can also be connected to a pin as defined by `DEFAULT_E0_AUTO_FAN_PIN` (requires the current `RCBugFix` — soon to be released as `1.1.0-RC8`).
```cpp
/**
 * Extruder cooling fans
 *
 * Extruder auto fans automatically turn on when their extruders'
 * temperatures go above EXTRUDER_AUTO_FAN_TEMPERATURE.
 *
 * Your board's pins file specifies the recommended pins. Override those here
 * or set to -1 to disable completely.
 *
 * Multiple extruders can be assigned to the same pin in which case
 * the fan will turn on when any selected extruder is above the threshold.
 */
#define E0_AUTO_FAN_PIN -1
#define E1_AUTO_FAN_PIN -1
#define E2_AUTO_FAN_PIN -1
#define E3_AUTO_FAN_PIN -1
#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED   255  // == full speed
```

**Comment by thinkyhead** [comment]
> M28 he do nothing

Sorry, I meant to type `G28`.

Depending on your host software, you might have to type `G28` in uppercase. A lowercase `g28` will be ignored by Marlin.

- `M114` he do nothing

In Marlin `M114` should always report the current position.

**Comment by Blue-Marlin** [comment]
Auto fan and part cooling fans are different.
The auto fan is meant to cool the hotend and should be switched on at a defined temperature (if configured).
The part cooling fan is that what you can switch on and off by the LCD and M106/M107.

**Comment by mihadongle** [comment]
Thanks thinkyhead that was my problem
