### ISSUE TITLE
Advice needed on Marlin IDE

### ISSUE THREAD

**Issue by BillStruve** [MarlinFirmware/Marlin#5325]
What editor or IDE is good for writing code for Marlin? Editing in Adruino IDE is a big step back for me, even UltraEdit is better. I've gotten spoiled with the C# IDE with its real time bug check and information being just a click away.

**Comment by emartinez167** [comment]
Johnny Linden has developed a Windows-based tool to help migrating
Configuration.h. Look him up in Google+ in the RigidBot or 3D printing
groups.

**Comment by BillStruve** [comment]
@emartinez167 Looks like a cool tool for migrating the Configuration.h file to a new version of Marlin. I was looking for a good IDE to write Marlin code.

**Comment by emartinez167** [comment]
You will need to use git to submit a pull request with the changes.

Regards,

Ernesto

**Comment by thinkyhead** [comment]
Hi @BillStruve — Personally, I use [Sublime Text 3](https://www.sublimetext.com/3) and I love it, even though it is not an IDE, just a "dumb" text editor. But it's very simple. There are plugins that are meant to integrate with Arduino, but I don't think they're very up-to-date, so I haven't been using them. Maybe one day I'll make my own.

I still use the Arduino IDE for building (and catching typos and syntax errors). You can enable the "Use External Editor" option in Arduino IDE preferences and it prevents being able to edit in the IDE.

Other people like TextMate, Eclipse, and Atom. Any good external text editor with plugin capability should do.

**Comment by shacal** [comment]
PlatformIO support?
I currently build with that and output is more optimized and fewer bugs (latest AVR compiler)
Visual Studio Code or PlatformIO IDE works well together.

**Comment by BillStruve** [comment]
Loving Sublime Text 3 so far, Thanks @thinkyhead

**Comment by petrzjunior** [comment]
For me, I started using Visual Studio Code or Atom (they are based on the same core). both work well, have some basic git integration and accept all line endings. ;)

**Comment by BillStruve** [comment]
@petrzjunior great to know since I'm familiar with Visual Studio - I'll give it a whirl when I get a round tuit.

**Comment by thinkyhead** [comment]
I'm suddenly very fond of Atom. I installed the PlatformIO plugin that turns it into an IDE. Building Marlin within Atom using PlatformIO takes only 13-17 seconds (!) (thanks to CLANG), and I don't have to leave the editor. It's pretty sweet. It also has LINT support, so it can catch syntax errors and highlight them right in the editor.

Then I installed the git-history plugin and that also blew my mind. I'm having way too much fun playing with this editor and trying different plugins and themes.

Of course it can open my BASH in an embedded pane (with a full-color TERM). Running JOE and EMACS inside of a pane inside of Atom made me ROTFL.

And, yes, you can fly an Asteroids ship and shoot up your text files when you feel the need.

I'm going to try using it exclusively for a while and see what else I can make it do.

**Comment by petrzjunior** [comment]
@thinkyhead I'm happy with Atom as well, just instaled all plugins recommended by you and especially PlatformIO just blew my mind! Coding speed doubled :)

**Comment by jbrazio** [comment]
I'm a license owner of Sublime but in the last month been having spinning Atom and I would say 100% replaces Sublime with no cost, there are some plugins you must install like minimap, highlight-line and highlight-selected.

**Comment by thinkyhead** [comment]
I'm kind of annoyed with Atom because multi-line find-and-replace is broken and has been for a long time with no resolution and no other option. I need to use that feature pretty frequently. And the editor is a little unstable (perhaps owing to the plugins). It's also rather sluggish. So I've gone back to Sublime for the time-being.

**Comment by shacal** [comment]
Visual Studio Code + PlatformIO command line build (task from VS Code) is best for cross platform develop. :)
Atom with plugin hell, is well... hell :D

**Comment by thinkyhead** [comment]
> Visual Studio Code + PlatformIO command line build 

I'll try that out next. Otherwise I'll end up having to learn CoffeeScript to fix Atom.
