### ISSUE TITLE
Version 1.0.2.2 Fails to compile 

### ISSUE THREAD

**Issue by LRagji** [MarlinFirmware/Marlin#5327]
As there are 2 Marlin files Marlin.ino and Marlin .pde arduino IDE fails to compile stating there is an existing marlin file.
Arduino IDE version 1.6.12

**Comment by boelle** [comment]
use the ino file only

**Comment by boelle** [comment]
~~and there is no PDE file~~

~~[https://github.com/MarlinFirmware/Marlin/tree/RCBugFix/Marlin](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix/Marlin)~~

**Comment by Blue-Marlin** [comment]
He is talking about 1.0.2.2 (see header). And there is a .pde file.

**Comment by thinkyhead** [comment]
> And there is a .pde file.

So there is. Should we toss the PDE file, or is it needed for Arduino < 1.5 ?

**Comment by LRagji** [comment]
I think we can simple rename pde file to MarlinOlder.pde so that it continues to build..

**Comment by thinkyhead** [comment]
@LRagji That works? Nice. I will submit the change in the morn.
