### ISSUE TITLE
Ramps 1.4 Plus pins does not match 1.4 pins, option for RAMPS_PLUS?

### ISSUE THREAD

**Issue by shacal** [MarlinFirmware/Marlin#5332]

**Comment by Blue-Marlin** [comment]
What is a RAMPS_PLUS? Not a skateboard ramp i suppose.

**Comment by shacal** [comment]
http://reprap.org/wiki/Ramps1.4plus

**Comment by shacal** [comment]
Quite popular in Scandinavian and baltic

**Comment by Blue-Marlin** [comment]
The wiki page is quite useless. It's an ancient copy of the RAMPS page + a photo of the board + a comment by Grogyans. Where is the real info about features, layout, pinning, availability?

**Comment by shacal** [comment]
http://www.yoycart.com/Product/521797326074/
http://www.iographix.com/products/3d-printer-main-control-board-automatic-leveling-double-shaft-reprap-ramps1-4-plus-bt7272a/

So this is considered as not RAMPS board?

**Comment by thinkyhead** [comment]
It's a RAMPS-like board. All the boards in Marlin that are RAMPS-like have their own pins file, which includes `pins_RAMPS.h` then overrides any differences.

They define their pins as…

![ramps-plus](https://cloud.githubusercontent.com/assets/698003/20811353/f45d3d58-b7d2-11e6-8573-3d8439f4604a.jpg)
![ramps-plus-2](https://cloud.githubusercontent.com/assets/698003/20811423/3cb2410c-b7d3-11e6-9e07-6fdf3c25b2cb.jpg)
![ramps-plus-3](https://cloud.githubusercontent.com/assets/698003/20811428/40259b18-b7d3-11e6-8289-02213f24b6db.jpg)

**Comment by thinkyhead** [comment]
Differences include:
- Swap the E0 and E1 pins (like "Rigidboard")
- E0 Heater on D8 (instead of D10)
- Bed Heater on D10 (instead of D8)
- Kill pin 27 default? (Later overridden to 41.) Should be LCD-dependent (41, 31, or 64)
- LCD pins assume one of two controllers, but are custom so would need to be overridden at the connector level to allow for other controllers
- `SD_DETECT_PIN` 49, assumes a particular controller

A preliminary pins file could be generated, but someone with the specific board would need to supply any corrections, especially for different LCD controllers.

**Comment by boelle** [comment]
i bet @shacal has one

**Comment by shacal** [comment]
I have 6, and have built around 20 with these and I love that board.
I think that best way to "fix" this is that I create pins_RAMPS_PLUS.h and have PR for that.

Cool?

**Comment by shacal** [comment]
And I have both Full and slim reprap graphic LCD controllers to test.

**Comment by thinkyhead** [comment]
> I think that best way to "fix" this is that I create pins_RAMPS_PLUS.h and have PR for that.

That would be great. If this board is gaining traction, we should have it in our boards list.

**Comment by thinkyhead** [comment]
> And I have both Full and slim reprap graphic LCD controllers to test.

I'm trying to get `1.1.0-RC8` out tonight, if possible. But we should be able to include it into the final 1.1.0 release, as it is non-disruptive to the rest of the code.

**Comment by shacal** [comment]
Final target sounds ok.
I have new printer on table that gets this same setup with latest rcfixes branch, so instead using own copy of ramps pins from private git, I create something more suitable for public usage.
:)

**Comment by furiati** [comment]
Hi, Any update on this subject?

Thank you very much!

:)

**Comment by shacal** [comment]
Yes and no...
I m still working on this, as I need to clean up my pin configs and test with different ramps configuration.

I try to make pull request soon.

**Comment by shacal** [comment]
https://github.com/MarlinFirmware/Marlin/pull/5695

**Comment by furiati** [comment]
Thanks for the update!
I have the last RCBugFix working on my printer, auto leveling working too, if you think it can help you, I can upload configuration.h and pins...h

**Comment by heimerdinger91** [comment]
Hey guys I got an RRD fan extender board for autocooling (a workaround as I blew my d9 mosfet).

 I have now run into the problem of ramps 1.4 plus pins being different than 99% of ramps boards out there. Would someone here be so kind as to help me figure out the correct pins to install my RRD extender on? 

Google seems to be falling short on this one.

My best guess at this point is the AUX-2 set next to the MOSFETs but it's really just a guess and I don't want to fry my whole board.

Many thanks for any input anyone can provide.

**Comment by shacal** [comment]
Check my links post2, there is full diagram in sellers details.

**Comment by heimerdinger91** [comment]
Sorry for my ignorance here. I can see which pins my RAMPS 1.4plus has, but I do not know how to connect the RRD extender properly. Guides online all involve ramps boards but not the ramps 1.4plus, and some suggest AUX1 while others suggest servo pins. 

If there is a better place to be asking, please link to it.

Thanks

**Comment by TilogyAspects** [comment]
Shacal, have you enabled auto leveling on this board? i can not seem to find anything on the web on it. Could you help?

**Comment by shacal** [comment]
Yes, with probe in Z-minstop pin.

**Comment by thinkyhead** [comment]
Let's continue this on #5820.
