### ISSUE TITLE
Extrusion issue 

### ISSUE THREAD

**Issue by RajaaKahel** [MarlinFirmware/Marlin#5334]
Hello, Please I'm having a strange issue. During printing everything is perfect, but if I try to lower the extrusion from 100% to 99% I get a very low extrusion like 5% or less. It becames like thin hair lines that ruin the whole thing. This happens if I lower the value from Simplify3D or the LCD panel (only during printing).
Thank you in advance. 
![20161130_193157](https://cloud.githubusercontent.com/assets/23242775/20766040/13943d46-b735-11e6-8f4e-6c7900b159f0.jpg)

**Comment by Erutan409** [comment]
Interesting.  I thought I was the only one having this issue.

I'm also using Simplify3D.

**Comment by Roxy-3D** [comment]
It might be good to save the GCode file generated by Simplify3D at 100%.  And save it at 99%.   And see what it does to the extrusion lengths.   Obviously....  The lengths should only shift by 1%.

**Comment by Kaibob2** [comment]
I also use Simplify3d 3.1.0 and have a Full graphic display. Never had this issue. What Marlin version are you on?

**Comment by RajaaKahel** [comment]
Roxy-3D, How should I save the Gcode when I change to 99% during printing?

Kaibob2, I'm using Marlin rc7.

**Comment by psavva** [comment]
@RajaaKahel, So you are adjusting the Feed Rate to 99% whilst it's Printing is what I understood.
What version of Marlin?  Did you try RCBugFix? or are you running RC 7?

**Comment by RajaaKahel** [comment]
@psavva, That's right. I'm adjusting while it's printing. If I adjust the original Gcode (while slicing before printing job) it works normally. 
It's Marlin RC7, I didn't try something else actually. I don't know what to do. Here is a screen shot for more details:
<img width="547" alt="screen shot 2016-12-01 at 9 40 42 pm" src="https://cloud.githubusercontent.com/assets/23242775/20811826/7a04767e-b80f-11e6-9eb0-000921af0ee2.png">

**Comment by Kaibob2** [comment]
The first thing I would do is switching to RCBugfix as there were a huge amount of fixes since RC7

**Comment by RajaaKahel** [comment]
@Kaibob2 I'll try and see if that fixes this issue, thanks!

**Comment by thinkyhead** [comment]
I have heard of this before, but not in a long time. We may have fixed the maths in `RCBugFix`. I look forward to hearing whether or not we fixed it.

**Comment by Kaibob2** [comment]
@RajaaKahel Did switching to RCBugfix fix this issue?

**Comment by RajaaKahel** [comment]
Actually I was designing new carriages & rods & effector, so I'll try once I finish them. But I guess it's better to try the RC8 instead.

**Comment by Kaibob2** [comment]
As RC8 is quite new you can use it too, but I would always suggest using the Bugfix version as this is always the most recent version.

**Comment by RajaaKahel** [comment]
Thank you guys for the suggestions. I don't know if here is the right place, but what do you think about Marlin Kimbra?
