### ISSUE TITLE
Z_DUAL problem

### ISSUE THREAD

**Issue by AlbanDurrheimer** [MarlinFirmware/Marlin#5384]
Hello,

On my 3d printer with a ramps 1.4

In the Marlin program, I removed the `#define Z_DUAL_STEPPER_DRIVERS` to set E1 in Z2. In manual control everything works.

But when I ask him to calibrate the position zero, there is that E1 (Z2) which moves without Z1.

And even when I ask to calibrate only the axis X, there is that E1 (Z2) that moves.

While before activating the Z_dual, it works correctly.

Can you help me ?

**Comment by thinkyhead** [comment]
Are you using the `RCBugFix` branch?

**Comment by AlbanDurrheimer** [comment]
No, it changes what?

**Comment by thinkyhead** [comment]
It changes almost everything.

**Comment by AlbanDurrheimer** [comment]
Should I switch to the RCBugFix branch ?

**Comment by thinkyhead** [comment]
I would recommend that you do. It will be easier to troubleshoot.

**Comment by AlbanDurrheimer** [comment]
Thanks, I'll try

**Comment by AlbanDurrheimer** [comment]
What are the differences between the two versions ?

**Comment by Sanitar777** [comment]
> thinkyhead commented an hour ago
It changes almost everything.

Literally - everything! Believe me, if you don't believe the developer ;-)

**Comment by AlbanDurrheimer** [comment]
If I believe the developer, but I have trouble understanding why there are 2 versions so different :-)

**Comment by Sanitar777** [comment]
It's very simple... it's easier to write new code than fix bugs in the old code. Since the team decided to radically revise the old firmware. They made this decision. I thank them for that! :-)

**Comment by AlbanDurrheimer** [comment]
Okay, thank you for the explanation :-)
I'll see if it fixes my problem as soon as possible.

**Comment by Blue-Marlin** [comment]
Marlin V1 is almost 2 years old. We have not been lazy.

**Comment by AlbanDurrheimer** [comment]
So I tried RCBugFix and I still have the same problems.

**Comment by thinkyhead** [comment]
I see. My first thought is that perhaps there is too much torque for the steppers to handle.

As a preliminary step, lower your Z homing speed, Z max feedrate, Z max acceleration, and Z jerk a bit to see if it makes any difference. You can use `M201 Znn`, `M203 Znn`, and `M205 Znn` to play around with these settings without re-flashing the firmware.

**Comment by AlbanDurrheimer** [comment]
There, I just tried to put both Z motors on a single conductor (Z). It works, but after a few seconds, one engine stops and the other accelerates.

You have an idea?

**Comment by thinkyhead** [comment]
Bad wiring?

**Comment by AlbanDurrheimer** [comment]
The engines turn in the right direction. It's just that one engine stops before the other.
I do not think it comes from wiring

**Comment by AlbanDurrheimer** [comment]
And when I want to calibrate X, there is the Z axis that moves 2 seconds before x is calibrated.

**Comment by thinkyhead** [comment]
> one [motor] stops before the other

If you see this when the motors are both connected to the same driver, it can't possibly be software.

**Comment by thinkyhead** [comment]
> when I want to calibrate X, there is the Z axis that moves 2 seconds before x is calibrated

Post your `Configuration.h` and `Configuration_adv.h` so we can check them out. (You may need to add `.txt` to the filenames for Github to allow them to be dropped on the text field.)

**Comment by AlbanDurrheimer** [comment]
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/637545/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/637546/Configuration_adv.txt)

**Comment by thinkyhead** [comment]
> when I want to calibrate X, there is the Z axis that moves 2 seconds before x is calibrated

I don't see anything in your configurations to indicate why this would occur.

I see you have hardly made any changes to the default configurations.
For example, none of these have been changed:
```cpp
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 4000, 500 }
#define DEFAULT_MAX_FEEDRATE          { 300, 300, 5, 25 }
#define DEFAULT_MAX_ACCELERATION      { 3000, 3000, 100, 10000 }
```
Are these all just coincidentally right for your printer?

**Comment by AlbanDurrheimer** [comment]
In fact, before bothering to adjust the values, I wish I could make it move correctly.
That's why I have configured the limit switches and the direction of the different motors.

**Comment by thinkyhead** [comment]
You can't make it move correctly without setting values that are tuned to your hardware.

**Comment by AlbanDurrheimer** [comment]
Thank you for your help, for now everything works except the limit switches (X, Y) that are no longer recognised.

**Comment by AlbanDurrheimer** [comment]
Thank you for your help, it works, it only remains to correctly adjust dimensions :)
To recover the limit switches, I went back to the RC version, because on the RCBugFix the limit switches were not detected.

**Comment by thinkyhead** [comment]
Resolved?

**Comment by aaronthomaswebster** [comment]
Z_DUAL_STEPPER_DRIVERS Is not working for me either, one motor just hums... It seems like I need to adjust the steps per unit for the second Z stepper. Is there a way to set the steps for the second Z motor?

**Comment by james94jeans2** [comment]
@aaronthomaswebster this sounds more like a current issue with the second driver. Did you adjust the current on the second driver?

**Comment by aaronthomaswebster** [comment]
I actually pulled the drivers and switched their position and still had an issue with the motor running off of E1.

**Comment by james94jeans2** [comment]
okay, maybe you could try enabling the toshiba driver option in configuration.h to test if there is a problem with the frequency of steps
