### ISSUE TITLE
[Question] Override next free extruder when using the dual z stepper option

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#5399]
I got one of these http://reprap.org/mediawiki/images/4/4f/RAMPS_SE_X2.jpg

for my 3rd extruder and 2nd Z stepper driver

if i enable `#define Z_DUAL_STEPPER_DRIVERS` it would normally take the next free extruder

but what if there are none or i want to assign a stepper driver to use specific? how would i override the automation?

i ask simply because i dont know and i cant figure it

**Comment by thinkyhead** [comment]
Just define the pins you want to use in your config.
```cpp
    #define Z2_STEP_PIN   36
    #define Z2_DIR_PIN    34
    #define Z2_ENABLE_PIN 30
```

**Comment by boelle** [comment]
and enable the define? or just define the pins?

**Comment by thinkyhead** [comment]
Yes, enable the &#$% define.

**Comment by boelle** [comment]
Sorry for not knowing :-/
