### ISSUE TITLE
[Feature Request / Idea] Save bed correction info

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#5415]
Basicly just a placeholder / reminder

But for those of us that don't have a always on probe it could be nice to be able to store the bed correction info.

It would also reduce time spent as you don't have to do a G29 before every print. Good for those that have good machines and just want to fire a G29 every now and then.

**Comment by ghost** [comment]
Enable eprom support and you'll have that option.

**Comment by boelle** [comment]
i have and no its not there :-D

@thinkyhead has said so and dont have the time yet to implement it

try and do a G29 and then M500 and then G28... its gone

power cycle and its gone also

**Comment by thinkyhead** [comment]
This is a duplicate issue. You're praying for rain that will come when it comes.

**Comment by boelle** [comment]
where is the duplicate?

**Comment by thinkyhead** [comment]
Which one? This has been requested several times. It's on the list of things to do.

**Comment by boelle** [comment]
i did not know that... 

one of the others could have been https://github.com/MarlinFirmware/Marlin/issues/4697
