### ISSUE TITLE
G28, G29 double touch

### ISSUE THREAD

**Issue by BillStruve** [MarlinFirmware/Marlin#5418]
Is there a setting in Configure.h for G28, like there is for G29 to stop double touch?
e.g.
```cpp
// Use double touch for probing
//#define PROBE_DOUBLE_TOUCH
```

**Comment by Blue-Marlin** [comment]
No.
When probing, we know where we are and where we have to slow down.
When homing we would have to move all the way with the slow speed - what would last forever.

**Comment by BillStruve** [comment]
I see, OK.

**Comment by macst34** [comment]
@BillStruve 

If you really want to prevent the "double touch" occuring, the variable name associated with the 2nd touch is "home_bump_mm" in Marlin_main.cpp. If you look into it some more, maybe you can share what you learn about it and what you did to get the outcome you wanted.

Happy hacking, 
Michael

**Comment by thinkyhead** [comment]
The `home_bump_mm` defaults come from here, btw:
```cpp
#define X_HOME_BUMP_MM 5
#define Y_HOME_BUMP_MM 5
#define Z_HOME_BUMP_MM 2
```

**Comment by BillStruve** [comment]
I'll put it on the to-do list, thanks.
