### ISSUE TITLE
CHAR LCD optimizing

### ISSUE THREAD

**Issue by justmyopinion** [MarlinFirmware/Marlin#5419]
If you do not have a graphic LCD (why should you?) you may have one of those 4x20 LCD's that basically fits very well to marlin menues. Typically these have an I2C interface that is not very fast compared to SPI used with graphic LCD. Latest discussions has been with graphics LCD's but char displays also suffer.

However if you have experienced a "stuttering" printer, it could be because of slow LCD updating so here are a few hints you may try, to solve that problem. They have been tested on my own printer only but are stable. Testing was with I2C display interface LCD_I2C_TYPE_MCP23017, change if necessary.

1) exchange the Marlin suggested driver for TWI2 with this one that has been optimized for speed and should replace the TWI2 driver: https://github.com/justmyopinion/LiquidTWI2/tree/LiquidTWI2_WIRE branch  LiquidTWI2_WIRE (important). That's it.
2) If you want even more speed an easy solution is to raise the I2C speed, but this is a global solution so if you have more I2C devices you may check these for compatibility. Add these lines with your LCD implementation:
```cpp
    #define TWI_FREQ 400000  // default is 100000
    lcd.setclock( TWI_FREQ);  // or if that does not work do it this way:

    TWBR = ((F_CPU / TWI_FREQ) - 16) / 2;   // TWI_FREQ 100000-1000000Hz
```
3) If you are still hungry for speed it is fairly simple to divide statusscreen into four updates instead of one (like graphics LCD solution), one for each line, but that is another story and probably not necessary, but it is tested :-) 

Enjoy your new fast printer :-)

**Comment by landodragon141** [comment]
This can probably be closed
