### ISSUE TITLE
Mesh bed leveling RC8

### ISSUE THREAD

**Issue by Ludwig100** [MarlinFirmware/Marlin#5420]
Cannot see any Mesh Bed Level option in menu? Have #define MESH_BED_LEVELING in configuration.h.
Any idea?

**Comment by epatel** [comment]
You should also enable this `MANUAL_BED_LEVELING`

https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Configuration.h#L754

**Comment by Ludwig100** [comment]
Of course ! Thanks!
