### ISSUE TITLE
Printing with secondary extruder and DISTINCT_E_FACTORS enabled doesn't work

### ISSUE THREAD

**Issue by Kaibob2** [MarlinFirmware/Marlin#5433]
With` #define DISTINCT_E_FACTORS` disabled it prints perfect what it should, with enabled `#define DISTINCT_E_FACTORS` the Y Axis makes a unhealthy sound as if the speed would be much to high but doesn't move. The Display says Y would have moved to the correct position.
Then X moves somewhere and starts with the infill of the first layer.
This happens only when printing with the second extruder (E1), when using the primary Extruder everything is fine.

The model is
![unbenannt](https://cloud.githubusercontent.com/assets/20832276/21008430/f6f4085c-bd41-11e6-8eff-1522a52582df.JPG)
The GCODE is
[warp2.zip](https://github.com/MarlinFirmware/Marlin/files/639242/warp2.zip)
My configuration
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/639259/Marlin.zip)

**Comment by realhuno** [comment]
Yes, i can confirm this.... same issue ;-( 
I crashed two times. 

X Axis shift to max and start printing in the air.

**Comment by thinkyhead** [comment]
Try `M502` followed by `M500` just to make sure everything is cool.

**Comment by Kaibob2** [comment]
With the values that come from RCBugfix or mine?

Other issue: 
M92 X80.30 Y80.30 Z1600.00
M203 X300.00 Y300.00 Z9.00
M201 X1500 Y1500 Z100
are missing the E values

![unbenannt](https://cloud.githubusercontent.com/assets/20832276/21053263/f414ae60-be28-11e6-9182-cde1f8b02059.JPG)

**Comment by Kaibob2** [comment]
@thinkyhead 

> Try M502 followed by M500 just to make sure everything is cool.

Did this and tested with RCBugFix as of 10.12.2016 and it still doesn't work.

**Comment by thinkyhead** [comment]
Apparently the host software is filtering out `M92 Tn En` and others. That's odd.

**Comment by Kaibob2** [comment]
This
```
if (!forReplay) {
      SERIAL_ECHOLNPGM("Steps per unit:");
      CONFIG_ECHO_START;
    }
    SERIAL_ECHOPAIR("  M92 X", planner.axis_steps_per_mm[X_AXIS]);
    SERIAL_ECHOPAIR(" Y", planner.axis_steps_per_mm[Y_AXIS]);
    SERIAL_ECHOPAIR(" Z", planner.axis_steps_per_mm[Z_AXIS]);
    #if DISABLED(DISTINCT_E_FACTORS)
      SERIAL_ECHOPAIR(" E", planner.axis_steps_per_mm[E_AXIS]);
    #endif
    //SERIAL_EOL;
    #if ENABLED(DISTINCT_E_FACTORS)
      for (uint8_t i = 0; i < E_STEPPERS; i++) {
        SERIAL_ECHOPAIR("  M92 T", (int)i);
        SERIAL_ECHOPAIR(" E", planner.axis_steps_per_mm[E_AXIS + i]);
      }
    #endif
    SERIAL_EOL;
```

produces this in Simplify3D

![unbenannt](https://cloud.githubusercontent.com/assets/20832276/21150649/095737cc-c160-11e6-96d7-5c149d9770d9.JPG)

Don't know if this helps. I tried almost any location for `SERIAL_EOL;` but didn't got it working any better.

**Comment by thinkyhead** [comment]
Any news on this issue?

**Comment by Elenedeath** [comment]
all here i try on 1.1.0 RC8 and RCbugfix for 21/02/2017, i try to know why my printer dont print on second extruder and when DISTINCT_E_FACTORS enabled, always skip origin and know middle bed are X0 Y0 and go hit the x axis +

and if my head stay at X0 Y0 when start print.

print from software at X100.000 Y126.082 but in printer maybe X65 Y0



i try print with e0 but with brim on e1, start on e1 are like before.Sliced piece on center bed but print middle bottom near you of the bed

i try print with e1 but with brim on e0, start on e0 fineand when switch to e1 move outside brim for 80mm and print.Sliced piece on center bed.
extruder offset parameter on repetier are X0 Y0 for both extruder > http://prntscr.com/ec60qb

#define HOTEND_OFFSET_X {0.0, 18.00} on my configuration.h
