### ISSUE TITLE
Crushed if Used Delta Calibration Marlin 1.1.0-RC8 - 6 Dec 2016

### ISSUE THREAD

**Issue by Fastereus** [MarlinFirmware/Marlin#5434]
When you try to call any calibration mode in the menu "Delta Calibration" after a small movement in the Z axis, the firmware hangs on the сrushed.

After hovering sometimes fly artifacts he sometimes cleans the screen sometimes freezes

**Comment by thinkyhead** [comment]
@Fastereus — This menu needs work. You should disable it until we have a chance to test and re-write it.
