### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by BillStruve** [MarlinFirmware/Marlin#5453]
You may want to remove commented out code,
lines 332-347 in temperature.cpp

**Comment by Blue-Marlin** [comment]
This comment is a nice thorn in the foot, to remember us - it's not working.
In theory these alternatives should deliver K-values with less overshoot. All my experiments show - they don't, but result in more overshoot - at least for the first one after changing the target temperature. (Maybe one day we find out why.)

**Comment by BillStruve** [comment]
Sorry...
