### ISSUE TITLE
Turkish translate error

### ISSUE THREAD

**Issue by ceturan** [MarlinFirmware/Marlin#5472]
error turkish translation on below line and all \xc7e strings
" #define MSG_RETRACT                         "Geri \xc7ek"                                               //Geri Çek"

it is looking "Geri  ..k" on lcd screen.
because \xc7 mean "Ç" but \xc7e mean "~" at unicode table.  

corrected line;
" #define MSG_RETRACT                         "Geri \xc7\x65k"                                               //Geri Çek"

and all \xc7ek (  Çek ) strings must be change with "\xc7\x65k" on language_tr.h

**Comment by boelle** [comment]
why not submit a PR to RCBugfix?

**Comment by yhfudev** [comment]
This file is NOT encoded in unicode, you may take a look the file language_tr_utf8.h,
or you may want to use the new UTF-8 language engine for the firmware #5441.

**Comment by AnHardt** [comment]
Please try
utf8-mapper for Turkish #5475.

**Comment by ceturan** [comment]
Thank You @AnHardt  for turkish mapper, it is working, you rock. and @yhfudev .

and sorry @boelle i don't known submit PR , this is first  time :-)
