### ISSUE TITLE
[Potential Bug] K8200 max temp trigger at 50C & Strange homing going on

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#5477]
using pronterface i can set the bed to 50C without any issue

but when i ask repetier host to print something on the K8200 i get an MAXTEMP trigger for the bed

```
20:28:24.830 : Error:MAXTEMP triggered, system stopped! Heater_ID: 0
20:28:24.830 : Error:Printer halted. kill() called!
```
its a bit random if it triggers on the hotend or the bed. But if i do a quick reset the temp i no where near max temp

i also at random get this one:
```
20:34:37.683 : Printer reset detected - initalizing
```
configuration.h: http://pastebin.com/WWsiP2KZ
configuration_adv.h: http://pastebin.com/iNZQac0w

Gcode: http://pastebin.com/MFVBna25

so it should not trigger as settings say 150. Any clues as what i should check

I use a 15V 30A psu and not the stock one

Also just noted that after a powercycle and connect from pronterface if i start by moving Z up 10mm X and Y also moved VERY slowly away from the endstops. This is only until i hit home or X and Y

Homing X with Z 10 up made Z go down :-/

and now each time i home X or Y Z moves up  bit, but i cant tell how much... approx 1mm or so. Homing Z and then Homing X makes Z go up again

have spent the time with the magnify glass to check for shorts and cold solder joints. no found. 

home all axes and then hitting the reset on the board and then trying to go 10mm up on Z makes X and Y creap about the same distance. if i home all they work like they should.

bed and hotend also work if i control them manual.

all endstop report like they should. fan same. extruder also work when control manual and all axes move the correct distance

**Comment by boelle** [comment]
@thinkyhead no rush, but do you have any idea why the printer behaves like this? what could i check to narrow it down? a little lost

**Comment by thinkyhead** [comment]
Using the current `RCBugFix`?

**Comment by boelle** [comment]
yep

**Comment by boelle** [comment]
Made it work under repetier

i assume this is due to an undersized heatbed. It cant hold 50 degree C with a 15V 30A so my assumptions is that it can with a 24V psu of same or less rating

The stange homing issues is not present in repetier

I dont have the funds nor the lust at present to fiddle more with the printer. But next step will be to get a 24V psu and retry
