### ISSUE TITLE
MINTEMP limitation prevents operation at 0 or sub 0 temperatures. 

### ISSUE THREAD

**Issue by AndKe** [MarlinFirmware/Marlin#5482]
I am using #define HEATER_0_MINTEMP 1
with temp sensor #define TEMP_SENSOR_0 1 (100k)

The printer is in unheated storage (pretty automated)  so the room temperature during winter is often 0 or maybe less degree.
- so it goes into mintemp error. (and OctoPi has trouble communication with it)

Problem is:
If I configure "*_MINTEMP -10" - which would solve the problem , then MINTEMP is never triggered.  It simply does not handle negative temperatures.

-of course, I will not disable this great safety feature.
-the best solution would be to handle negative "mintemp"
-also: when mintemp message is displayed/sent , it should contain one important thing; the actual temperature that triggered the safety logic.  
Displaying this information would also allow the mintemp to be properly configured, by allowing user to disconnect sensor to check what the reading is with sensor disconnected.

**Comment by justmyopinion** [comment]
There is no negative definition in table for thermistor type 1, but you may try to add a few, values are interpolated buit not very accurate in that end and wwould need some caibration.

THIS IS END OF TABLE FOR TYPE 1 (in thermistortabels.h):
...
...
 {       985 * OVERSAMPLENR        ,       20      },
 {       993 * OVERSAMPLENR        ,       15      },
 {       999 * OVERSAMPLENR        ,       10      },
 {       1004 * OVERSAMPLENR       ,       5       },
 {       1008 * OVERSAMPLENR       ,       0       },
Try to add a few more to tabel:
 {       1012 * OVERSAMPLENR       ,      -5       },
 {       1015 * OVERSAMPLENR       ,      -10     }
};
#endif

It may work but it is not tested

**Comment by AndKe** [comment]
Thank you - that's interesting, I do not need any accuracy at the lower end of scale , just a difference between -10 degrees  and "sensor disconnected"
- will test.

**Comment by 3dGriff** [comment]
I also find myself running in cold weather, not sure how you're automating your setup but I've used an end-routine (M140) to maintain bed temp between prints as a solution in the past.

**Comment by AndKe** [comment]
@justmyopinion 's suggestion worked perfectly fine.

Please pull https://github.com/MarlinFirmware/Marlin/pull/5485 , it allows user to use MINTEMP -14 degrees , and still trigger the safety shutdown when sensor is disconnected. (tested, and verified)

**Comment by justmyopinion** [comment]
:+1:

**Comment by 3dGriff** [comment]
Good to know.  Thanks!  Uploading

**Comment by thinkyhead** [comment]
Merged code from #5485.
