### ISSUE TITLE
Dual Steppers for each axis

### ISSUE THREAD

**Issue by forReason** [MarlinFirmware/Marlin#5489]
Dear Community, I have a Azteeg X3 Pro which allows for up to 8 Stepper Drives.
(`X`, `Y`, `Z`, `E0`, `E1`, `E2`, `E3`, `E4`)

I build a Large Printer So I want to use two steppers for Each axis (`X0`, `X1`; `Y0`, `Y1`; `Z0`,`Z1`; `E0`; `E1`)
Is this somehow possible? Repetier supports this since months.

**Comment by thinkyhead** [comment]
If you have enough free stepper drivers on the board (let's call them `E2`, `E3`, and `E4`, since you are already using `X`, `Y`, `Z`, `E0`, and `E1`), you can use them to do dual X, dual Y, and dual Z. Just enable the options `X_DUAL_STEPPER_DRIVERS`, `Y_DUAL_STEPPER_DRIVERS`, and `Z_DUAL_STEPPER_DRIVERS`. Then attach `X2` stepper motor to `E2` plug. Attach `Y2` to `E3`. Attach `Z2` to `E4`.

You then have two steppers working together in parallel on each axis. The Dual Z axis supports an additional Z2 endstop.

**Comment by forReason** [comment]
Thank you for the fast reply.
Unfortunately I still have a Problem

I have found the following in Configuration_adv.h:
```cpp
#ifdef Z_DUAL_STEPPER_DRIVERS
  #undef EXTRUDERS
  #define EXTRUDERS 1
#endif

// Same again but for Y Axis.
//#define Y_DUAL_STEPPER_DRIVERS

// Define if the two Y drives need to rotate in opposite directions
#define INVERT_Y2_VS_Y_DIR true

#ifdef Y_DUAL_STEPPER_DRIVERS
  #undef EXTRUDERS
  #define EXTRUDERS 1
#endif`
```

First of all I cannot Find any `X_DUAL_STEPPER_DRIVERS`

Second the following section gives me headaches:
```cpp
#if defined (Z_DUAL_STEPPER_DRIVERS) && defined (Y_DUAL_STEPPER_DRIVERS)
  #error "You cannot have dual drivers for both Y and Z"
#endif
```

Can i just uncomment the last "error" section or am I totally wrong in the first place?

Kind Regards

**Comment by thinkyhead** [comment]
I suggest you start with `RCBugFix`. You're using an older version of Marlin which lacks the support you're looking for.

**Comment by Kaibob2** [comment]
I suppose you're on an older Marlin version as this is supported in the most recent `RCBugFix `
https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Configuration_adv.h#L252

**Comment by forReason** [comment]
I used the latest Release `[1.0.2-2](https://github.com/MarlinFirmware/Marlin/releases/tag/1.0.2-2)` from 12 days ago. Should I wait until 1.10 gets a stable release or is the latest prerelease "stable"?

**Comment by Kaibob2** [comment]
1.0.2-2 is extremely outdated. thinkyhead only fixed one [single thing in there.](https://github.com/MarlinFirmware/Marlin/releases/tag/1.0.2-2)
You can safely use [RC8](https://github.com/MarlinFirmware/Marlin/tree/RC) but better use the [BugFix version](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix) as there are already a few things fixed against RC8.

**Comment by forReason** [comment]
Thank you very much
