### ISSUE TITLE
[QUESTION] Redundant E entries in LCD Control Menu

### ISSUE THREAD

**Issue by Kaibob2** [MarlinFirmware/Marlin#5496]
Are these lines
https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/ultralcd.cpp#L2024
https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/ultralcd.cpp#L2048
https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/ultralcd.cpp#L2072

necessary for something? When `DISTINCT_E_FACTORS` is enabled there are three E entries which makes it a little confusing what to adjust.

![20161213_184606_resized](https://cloud.githubusercontent.com/assets/20832276/21152186/96c03654-c165-11e6-9c64-99670828078a.jpg)

**Comment by Sebastianv650** [comment]
If you have more than one E stepper, there are also more than one max. acceleration values. One for each stepper.

**Comment by Kaibob2** [comment]
I know, i have two E steppers, but do we need:
**E**
E1
E2

What is **E** (without a number) in this scenario

**Comment by Kaibob2** [comment]
Ah, just found out. It's the active extruder. When i'm printing with E0 and change `E` than only `E1` changes.
Hmm, i would prefer if there is only E1 and E2 (in a two extruder scenario) as i think everybody knows which is the active extruder if changing values during operation.
But maybe this has a deeper meaning i don't get right know.

**Comment by Kaibob2** [comment]
What i mean is:
Can't these three lines just be deleted to make it more clear which value you're editing. I suppose nobody would miss them...

**Comment by thinkyhead** [comment]
Another UI concept, when there are multiple E steppers, is to place the active E first in the list, then the others in order, so if the second extruder was active in a 3-extruder system…
```
A max Z:       100
A max E2:    10000
A max E1:    10000
A max E3:    10000
A Retract:    3000
```
Or, you could mark it somehow…
```
A max Z:       100
A max E1:    10000
A max E2:   *10000
A max E3:    10000
A Retract:    3000
```
```
A max Z:       100
A max E1:    10000
A max E2>    10000
A max E3:    10000
A Retract:    3000
```

**Comment by Kaibob2** [comment]
@thinkyhead I would prefer the second option
```
A max Z:       100
A max E1:    10000
A max E2:   *10000
A max E3:    10000
A Retract:    3000
```
The first option makes it confusing and the third would imply that A max E2 greater 10000

But anyway, my intention was, that there are not (for example) three E entries in a two extruder scenario.
If it would be just like this
```
A max Z:       100
A max E1:    10000
A max E2:    10000
A Retract:    3000
```
i think it would be easy to understand as i don't see the advantage of seeing which extruder is active in the display. If i'm printing and there is coming filament from E1 and i want to change parameters for the active printhead i know where to change it...everywhere where an E1 appears.
