### ISSUE TITLE
[FR] Option to hardcode Home Offset and PID values for E2-E4 ?

### ISSUE THREAD

**Issue by Kaibob2** [MarlinFirmware/Marlin#5497]
@thinkyhead Would it be possible, without too much effort, having the option to hardcode the Home Offset and the PID values for all extruders in configuration.h?
It would be nice when all values are calibrated well and hardcoded to have a fallback when testing other settings which are stored in EEPROM. Especially the PID values get lost everytime i change them in EEPROM for testing and then revert to the verified settings from before.

**Comment by thinkyhead** [comment]
Yes, it should be possible.

**Comment by Kaibob2** [comment]
This would be nice if someone could do so :)

**Comment by thinkyhead** [comment]
I'll mark it as a task for the 1.1.1 update.

**Comment by boelle** [comment]
did this make it in to 1.1.1?

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. assuming it made it in to 1.1.1

**Comment by sjasonsmith** [comment]
I believe this is now addressed.

Default PIDs can now be specified as a list, with unique values for each hotend.
The offset is defined using the `HOTEND_OFFSET_` constants.
