### ISSUE TITLE
EEPROM checksum mismatch 

### ISSUE THREAD

**Issue by MoonshineSG** [MarlinFirmware/Marlin#5499]
Today, dec 14, after updating to latest codes (I was behind a couple of weeks) i now get error on M501

```
Send: M501
Recv: Error:EEPROM checksum mismatch
Recv: echo:Hardcoded Default Settings Loaded
```

I tried to save, reset, save again etc, nothing works.

**Comment by Kaibob2** [comment]
I can confirm. Do you have set `#define EXTRUDERS 2` or any other value than 1?
If so, try setting `#define EXTRUDERS 1` this fixed the whole EEPROM behaviour in my test right now.
It would be nice if you could confirm this.
I suppose this happened somewhere here #5448
Maybe @thinkyhead can take a look at it.

This in configuration.h 
```
// This defines the number of extruders
// :[1, 2, 3, 4]
#define EXTRUDERS 2

// Enable if your E steppers or extruder gear ratios are not identical
//#define DISTINCT_E_FACTORS
```
results in 

![2](https://cloud.githubusercontent.com/assets/20832276/21197651/7db95a5a-c23c-11e6-9523-a03cbf34404b.JPG)

on connection with Pronterface.

This in configuration.h 
```
// This defines the number of extruders
// :[1, 2, 3, 4]
#define EXTRUDERS 1

// Enable if your E steppers or extruder gear ratios are not identical
//#define DISTINCT_E_FACTORS
```
results in 
![1](https://cloud.githubusercontent.com/assets/20832276/21197735/d4e7ae8a-c23c-11e6-928c-ca6fc06a6ed5.JPG)
on connection with Pronterface.

**Comment by MoonshineSG** [comment]
@Kaibob2 yes, the error occurs with 2 extruders and once I change to `#define EXTRUDERS 1` the EEPROM is loaded without error.

**Comment by Kaibob2** [comment]
This is what I expected 
@thinkyhead Would you mind taking a look at your EEPROM refinement. Like it is now it's a PITA to print with any other extruder than E0 :(

**Comment by Kaibob2** [comment]
It would also be nice to have the ability to hardcode the PID values for each extruder. 
And the home offset would also be a candidate for hardcoding it.

**Comment by Kaibob2** [comment]
Until this is fixed i reverted to [configuration_store.cpp V27](https://github.com/MarlinFirmware/Marlin/blob/3391c785c6af1fe7bbcfd9a3eadf4ce3c279b850/Marlin/configuration_store.cpp)

**Comment by ghost** [comment]
@MoonshineSG @Kaibob2 
I also confirmed it when `EXTRUDERS 2` and disabled `DISTINCT_E_FACTORS`.
~~And this is quick fix.~~
~~https://github.com/esenapaj/Marlin/commit/7f7162005b7d377a74cf25aca9f0da16e8500972~~

EDIT: [This method cames of a bad stock](https://github.com/esenapaj/Marlin/commit/7f7162005b7d377a74cf25aca9f0da16e8500972#commitcomment-20210048).

**Comment by Kaibob2** [comment]
@esenapaj Tested right now. Works perfect. All values are stored and recovered after reset.
Good job!! Please make a PR out of it that it get's merged asap.

**Comment by ghost** [comment]
@MoonshineSG @Kaibob2
@thinkyhead has prepared a different solution for resolving it.
https://github.com/MarlinFirmware/Marlin/pull/5524 (Report EEPROM data size, not final index)

**Comment by MoonshineSG** [comment]
updated and the fix works.
Thanks!
