### ISSUE TITLE
Language files - new system

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/Marlin#5501]
If i understand it right, with the new language system proposed in #5441, every time a new symbol is needed the 'mappers' and 'fonts' have to be regenerated. At least on windows systems this is a very inconvenient process. Setting it up is a pain.

At least for German i know - there are several users having their own variant of `language_de.h`. To make the changes convenient for them - omitting the regeneration process - only a small change is needed.

For the languages with a relatively small number of different symbols we could make a complete list of the required symbols.

For example 'German' currently doesn't have a 'Q', But a future version may need it. If we don't want to regenerate the files every time we change something, 'German' should have the complete US ASCII symbols plus a relatively small number of additions: "ÄäÖöÜüß".
```
#define ASCII_20TO126_SYMBOLS               _UxGT(" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~")
#define THIS_LANGUAGES_SPECIAL_SYMBOLS      _UxGT("ÄäÖöÜüß")
```

I guess US_ASCII is needed in all languages to make the fallback to English possible. So let's define that at a central place, For example in `language_en.h`. That should be always included.
`THIS_LANGUAGES_SPECIAL_SYMBOLS` should be defined in the languages files.

For languages with an 'unlimited' set of symbols (cn, tw, kanji) `THIS_LANGUAGES_SPECIAL_SYMBOLS` could be omitted - but then the 'mappers' and 'fonts' have to be regenerated much more frequently, for these languages only.

Languages with Greek or Cyrillic will have a relatively big `THIS_LANGUAGES_SPECIAL_SYMBOLS`-string. Regardless of that, the resulting fonts should be smaller than they are now.

**Comment by thinkyhead** [comment]
Q: Is the benefit of a unified UTF-8 system worth the extra effort involved? I suppose it's good to have more control over the mapping and font-generation for languages with many symbols. Otherwise, what else does #5441 bring to the table?

**Comment by AnHardt** [comment]
> Q: Is the benefit of a unified UTF-8 system worth the extra effort involved?

No. - But don't ask me - i'm biased - the current system is mine - i'm not from Asia. ;-)

Some arguments:

* '-'  The new system needs more work. Currently it's not usable. 
* '+' With the current system, languages with many symbols are difficult to maintain. Fonts with more than 256 symbols are impossible.
* '+' Adding new languages to the current system seems to be too difficult. If I don't do it - nobody else does it. (If you know what to do - it's simple)
* '-' Having only one font (or better a lot of font stubs) makes it difficult to estimate the space a text needs. Not only the height can differ a lot, but also the width. The new font is not 'fixed width'.
* '-' If the new system has any benefit for char based displays has to be investigated. I don't think so. 
* '-' The new system currently needs lots of memory.  (Lots of font headers. 127 unused symbols in the main font.)
* '+-' Setting up a new language is now a one time task. When its done - its done. You never have to touch it again - except the scripts with too many symbols. 

* '+-' Adding completely new languages (Hebrew, Arabic) wouldn't be much simpler with the new system. Adding a new font always was a matter of taking an existent font and shrinking it to the tiny size we need. The 'wqy-bitmapfont-bdf-gb18030-nightly_build.tar.gz' is a nice base, but the 9 pt version is still too tall to use it without rework and the CJK-part is more like 11pt. In reality our fonts are more 7pt - but that's simply impossible for Chinese.

Don't ask me. I'm biased.
Maybe __I__'m the only one who sees the time it still needs to make it work. Time, __I__'d prefer to spent on other things.

**Comment by yhfudev** [comment]
> '-' Having only one font (or better a lot of font stubs) makes it difficult to estimate the space a text needs. Not only the height can differ a lot, but also the width. The new font is not 'fixed width'.

The width of text is handled by function `lcd_printstr` or `lcd_printstr_P` in file `ultralcd_impl_DOGM.h`, which replaced the while loop inline code.

> '-' If the new system has any benefit for char based displays has to be investigated. I don't think so.

For example,
* we won't to read Mar language in the header files (tr, kana, cn etc.)
* we can use more special symbols, such as ⊿ for "delta"
* we won't need to adjust the font and add new handle code for a new language.

> '-'  The new system currently needs lots of memory. (Lots of font headers. 127 unused symbols in the main font.)

I don't think the size of the ROM is not controllable, the translated strings are limited numbers and the expanded size is a small ratio of the number of strings.
Under the new updated version(https://github.com/MarlinFirmware/Marlin/pull/5441 and https://github.com/thinkyhead/Marlin/pull/20), it supports unicode range 0-255, and a lot of languages don't need generating font data: (the language_data_xx.h of 398 bytes contains no font data)
![lang-list](https://cloud.githubusercontent.com/assets/4012731/21636556/24826620-d231-11e6-9922-0d43ea4f547b.png)

And the compiled ROM file size listed here:
![lang-compare](https://cloud.githubusercontent.com/assets/4012731/21636568/32aca8fa-d231-11e6-9502-b060d574879e.png)

Most of language that require extra font data need extra 400-3k bytes space compared to "en" version, even the Chinese version needs only extra ~10K bytes space (4% of tatal ROM space).

The RAM is almost not influenced between the language versions, there's only 2 bytes different between zh and en version.

**Comment by thinkyhead** [comment]
I think we've moved on from this issue. Are we feeling better about the new system today?
