### ISSUE TITLE
Upgrade from RC7 to RC8 - Part cooling fan not working

### ISSUE THREAD

**Issue by pmbroth** [MarlinFirmware/Marlin#5504]
Hello  I finally was able to upgrade to RC8 via using an older adurino software as suggested 1.6.8.  The only issue I see is that the part cooling fan (Not the heater fan is not working.     I did try M106 command and it did not work  I did look at the pin.ramps and did not see a difference for the board I'm using "EEF".   To ensure the fan is good, I reverted back to rc7 and the fan works via lcd controller and software (S3d, Cura, etc.)  I'm using mks Gen 1.4, any ideas if anything else changed in other files that I need to look at?  Thank you in advance,. Brian

**Comment by pmbroth** [comment]
fixed  pins file, pins were reversed.

**Comment by macraj** [comment]
Hi, could You share solution ? Which pins were reversed ?

**Comment by pmbroth** [comment]
It was in the Ramps.H file   D8 and D9  were not  reversed..
