### ISSUE TITLE
Disabling #define ENDSTOPS_ONLY_FOR_HOMING causes that printer wont move after G28

### ISSUE THREAD

**Issue by alewir** [MarlinFirmware/Marlin#5509]
I'd like to use 2 endstops on each axis for hardware safety sake and so these would have to be respected while executing G0/G1 move commands...

However when I comment out #define ENDSTOPS_ONLY_FOR_HOMING - this causes that printer won't move after G28, since all home endstops are activated and that prevents any further movements.  It seems like a deadlock... S1/S2 parameters in G0/G1 does not seem to have an effect in runtime.

How to use this Marlin feature of using-endstops-not-only-for-homing without self-blocking the device?

Using version: 1.0.2-2

**Comment by Blue-Marlin** [comment]
ENDSTOPS_ONLY_FOR_HOMING is not an option newer versions of Marlin have.
It now is called ENDSTOPS_ALWAYS_ON_DEFAULT.

Please update your Marlin and retry.

**Comment by alewir** [comment]
Ok. Thanks for quick reply.

**Comment by Blue-Marlin** [comment]
In 1.0.2-2 the described behaviour could be caused by always on endstops. Check with M119.

**Comment by alewir** [comment]
Yes. All connected endstops are in TRIGGERED. (Not connected too of course.)
After homing and M119 I get:

Reporting endstop status
x_min: TRIGGERED [this endstop is currently connected and bumped to]
x_max: TRIGGERED [currently not connected]
y_min: TRIGGERED [this endstop is currently connected and bumped to]
y_max: TRIGGERED [currently not connected]
z_min: TRIGGERED [currently not connected]
z_max: TRIGGERED [this endstop is currently connected and bumped to]
ok

Here's what happens when I comment out ENDSTOPS_ONLY_FOR_HOMING:
```
-----------------------------------------------
Trying to execute command: 'move to origin Z (home)' [attempt 1]
REQUEST: N8 G28 Z*97EOL
 < 12 bytes sent.
 >> OK: expected message received: okEOL
-----------------------------------------------
Trying to execute command: 'move to origin X (home)' [attempt 1]
REQUEST: N9 G28 X*98EOL
 < 12 bytes sent.
 >> OK: expected message received: okEOL
-----------------------------------------------
Trying to execute command: 'move to origin Y (home)' [attempt 1]
REQUEST: N10 G28 Y*91EOL
 < 13 bytes sent.
 >> OK: expected message received: okEOL
-----------------------------------------------
Trying to execute command: 'initial endstop check' [attempt 1]
REQUEST: N11 M119*26EOL
 < 12 bytes sent.
 >> OK: expected message received: Reporting endstop statusEOLx_min: TRIGGEREDEOLx_max: TRIGGEREDEOLy_min: TRIGGEREDEOLy_max: TRIGGEREDEOLz_min: TRIGGEREDEOLz_max: TRIGGEREDEOLokEOL
-----------------------------------------------
Trying to execute command: 'get position' [attempt 1]
REQUEST: N12 M114*20EOL
 < 12 bytes sent.
 >> OK: expected message received: Position X:0.00 Y:0.00 Z:200.00 E:0.00 Count X:0.00 Y:0.00 Z:200.00EOLokEOL
-----------------------------------------------
Trying to execute command: 'move XYZ' [attempt 1]
REQUEST: N13 G0 X5 Y5 Z195*93EOL
 < 21 bytes sent.
 >> OK: expected message received: okEOL
-----------------------------------------------
Trying to execute command: 'set absolute 0 point' [attempt 1]
REQUEST: N14 G92 X0 Y0 Z200*110EOL
 < 23 bytes sent.
 >> FAIL: timeout - all received bytes: echo:endstops hit:  X:0.00 Y:0.00 Z:200.00EOLokEOL
-----------------------------------------------
Trying to execute command: 'set absolute 0 point' [attempt 2]
REQUEST: N15 G92 X0 Y0 Z200*111EOL
 < 23 bytes sent.
 >> OK: expected message received: okEOL
-----------------------------------------------
Trying to execute command: 'get position' [attempt 1]
REQUEST: N16 M114*16EOL
 < 12 bytes sent.
 >> OK: expected message received: Position X:0.00 Y:0.00 Z:200.00 E:0.00 Count X:0.00 Y:0.00 Z:200.00EOLokEOL
-----------------------------------------------
Trying to execute command: 'move Z' [attempt 1]
REQUEST: N17 G0 Z66*101EOL
 < 15 bytes sent.
 >> OK: expected message received: okEOL
-----------------------------------------------
```

And no movement is done.

EDIT 1: I just now realized that I'm trying to do it with only 3 endstops - 1 per axis. I don't really think it changes anything here but I'll try to connect missing 3 additional and will confirm results in a moment...

EDIT 2: Actually it works correctly when all are connected. My bad, sorry. Seems that only endstop against which the movement is executed is verified and because of pullups on missing endstops in my device it couldnt move after homing. Sorry again.
