### ISSUE TITLE
HOME_RETRACT_MM does not have effect

### ISSUE THREAD

**Issue by alewir** [MarlinFirmware/Marlin#5510]
Setting any of:
-  #define X_HOME_RETRACT_MM 10
-  #define Y_HOME_RETRACT_MM 10
-  #define Z_HOME_RETRACT_MM 10
does not have any effect. G28 for each axis just finishes immediately after related endstop is activated.
I.e. no "double touch" / "second slow bump" is happening.

[config.zip](https://github.com/MarlinFirmware/Marlin/files/654411/config.zip)

Using version: 1.0.2-2

**Comment by Blue-Marlin** [comment]
This is fixed in later versions.
Bugs in 1.0.2-2 will not be fixed any more.

**Comment by thinkyhead** [comment]
@alewir I think those are supposed to be:
```cpp
#define X_HOME_BUMP_MM 10
#define Y_HOME_BUMP_MM 10
#define Z_HOME_BUMP_MM 10
```

**Comment by alewir** [comment]
After commenting out:
```cpp
//#define ENDSTOPS_ONLY_FOR_HOMING // If defined the endstops will only be used for homing
```
and adding additional 3 endstops, this double bump started to work.

**Comment by thinkyhead** [comment]
I see. In the newer code, that option is now called `ENDSTOPS_ALWAYS_ON_DEFAULT`. And it is off by default.
