### ISSUE TITLE
Manual bed leveling hang with RCBugfix

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#5518]
Hi all!

I'm using manual bed leveling, and i see that printer hang (printing busy processing to console) when i try to do manual bed leveling (latest RCBugfix). However it works fine with RC8

**Comment by playlet** [comment]
I can confirm that, it hangs on the 1st point and the encoder is unresponsive. Thanks for posting this problem, I was just about to do it too :)

It started just after the menu was rearranged.

**Comment by chris-hemmings** [comment]
RC7 here. I have just done this and mine works fine. No hanging

**Comment by playlet** [comment]
We are not using RC7, title says RCBugFix latest version from 3 days ago :)

**Comment by ghost** [comment]
I ran into the same issue. I reverted back to RC8 and no issues.

**Comment by Fixx** [comment]
I experience the same issue with RCBugfix dated 15/12/2016.

**Comment by thinkyhead** [comment]
Any better now? I used MBL recently and found it working.
