### ISSUE TITLE
In version 1.1.0-RC8 I cannot disable all temp sensors / CNC

### ISSUE THREAD

**Issue by alewir** [MarlinFirmware/Marlin#5526]
I'm migrating from 1.0.2-2 to 1.1.0-RC8 and I cannot set the following anymore:
```
#define TEMP_SENSOR_0 0
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_BED 0
```
I'm using Marlin to control CNC device so I don't have any temp sensors.
But I'm getting following sanity test error while compiling:
```
src\SanityCheck.h:736:4: error: #error "TEMP_SENSOR_0 is required."
#error "TEMP_SENSOR_0 is required."
^
```

**Comment by brainscan** [comment]
Just use one of the dummy thermistors
