### ISSUE TITLE
Any other K8200 owners in here?

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#5532]
Hi,

As i'm one of the few it seems i wanted to know if at all there are other owners in here that have the same issues as me?

look at https://github.com/MarlinFirmware/Marlin/issues/5477
also i tried to check old and closed issues here: https://github.com/MarlinFirmware/Marlin/issues/5468

**Comment by thinkyhead** [comment]
Seek support from other K8200 users in the [RepRap forums](http://forums.reprap.org). This Github Issue Queue is not a forum for this kind of question, but rather a space for **developers** of the main Marlin project to discuss and to solve **project issues**.
