### ISSUE TITLE
cant pause and usb bug

### ISSUE THREAD

**Issue by Elenedeath** [MarlinFirmware/Marlin#5534]
Hello,  i found bug when i connect the rc8 to my computer and open repetier for print via usb.  I cant have connection if the sd Card are connect to the reprap discount lcd board because when repetier host try to listing the sd card the firmware crash and restart.

I use a reprap discount lcd with a mks base 1.4

**Comment by Elenedeath** [comment]
the pause print is very strange. the message return to normal message "pause print"  but the printer are pause. 
And sometime the message change to resume print but the printer arent paused

**Comment by thinkyhead** [comment]
Still seeing this issue in the current `RCBugFix`?

**Comment by Elenedeath** [comment]
I dont try it but can give a try tommorow
