### ISSUE TITLE
1.1.0-RC8 | G28 issue

### ISSUE THREAD

**Issue by sofos** [MarlinFirmware/Marlin#5538]
Symptoms:
'G28 X'  and  'G28 Y' codes unexpectedly set Z value to 5. 

Consideration:
For long prints I use XY homing between layers (specify custom G-code in Slic3r). This method works well with 1.1.0-RC5, but with 1.1.0-RC8 I have this problem.

What could be a possible reason for this?

**Comment by chris-hemmings** [comment]
There is a section in RC7 for the Z raise before and after homing. You can set this to 0

**Comment by sofos** [comment]
Yeah, changing Z_CLEARANCE_BETWEEN_PROBES to 0 helped (default value was 5)
Thanks :-)
