### ISSUE TITLE
Quick home Core xy grinding

### ISSUE THREAD

**Issue by chris-hemmings** [MarlinFirmware/Marlin#5540]
Enabling quick home in RC7 on a COREXY machine. The diagonal move works, But when it hits the x stop, it grinds for a bit before stopping x movements and then moves to the y stop.

**Comment by thinkyhead** [comment]
Of course, how does it behave in `RCBugFix`? is the real question.

**Comment by brendanjerwin** [comment]
Core XY, RAMPS 1.4

I had a similar experience with the RC8 (and then the RCBugFix) branches. I never let it grind long enough to see if it would move on to the other axis. Double, triple, checked that the end stops were behaving correctly with M119. This happened with all homing routines. Even single axis.

**Comment by thinkyhead** [comment]
And where do we stand now? I know we've done a bunch of stuff to the Core code since Xmas.

**Comment by molak34** [comment]
I'm having troubles with quick home on a smartcore XY ..

When the X is closer to home than Y it works OK. 

But if Y is closer to home than X  it grinds ...

Some how the firmware moves in diagonal and listen to the X endstop only.

**Comment by molak34** [comment]
https://www.youtube.com/watch?v=rgs83ao3UdU
