### ISSUE TITLE
full graphic lcd display problem

### ISSUE THREAD

**Issue by webnamex** [MarlinFirmware/Marlin#5542]
Please help me, how to solve the problem in the picture.

**Comment by webnamex** [comment]
![img_20161210_234518](https://cloud.githubusercontent.com/assets/22877180/21293927/7222d878-c56c-11e6-9f27-f0b2168be9ad.jpg)

**Comment by ghost** [comment]
Configuration or hardware issue? I have the same display and have run all different versions of Marlin. I have never had that issue.

Can you post your configuration files?

**Comment by webnamex** [comment]
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/659480/Configuration.txt)

**Comment by webnamex** [comment]
@Tannoo

**Comment by webnamex** [comment]
thanks @Tannoo

**Comment by ghost** [comment]
ok. Try upgrading to RC8. A LOT of things have changed. See if that fixes it.

**Comment by ghost** [comment]
@webnamex, did that help?

**Comment by snoekieboe** [comment]
I actually have the exact same issue with my ramps 1.4 board and 12864LCD when running marlin.

**Comment by willthiswork89** [comment]
im having this issue as well same board. osoyoo ramps 1.4 board with 12864LCD. Starts out fine, then seems like randomly the screen gets pushed on the X by 20 pixels or so and starts "looping" around just as the OP shows. 

I'm on RC8 just uploaded fresh

**Comment by willthiswork89** [comment]
I'm on RC8

**Comment by webnamex** [comment]
hi，I've fix it ，I just only  replace the lcd module ,not the lcd whole board,now it  works well ,you can try @willthiswork89 @snoekieboe

**Comment by webnamex** [comment]
@Tannoo  thanks

**Comment by willthiswork89** [comment]
Are you saying my LCD screen is bad? Or is there something in the code to fix this?

**Comment by webnamex** [comment]
@willthiswork89 yes，just replace the lcd screen

**Comment by Blue-Marlin** [comment]
Has one ore more of you (having the error) defined
```
  // Enable this option and reduce the value to optimize screen updates.
  // The normal delay is 10µs. Use the lowest value that still gives a reliable display.
  //#define DOGM_SPI_DELAY_US 5
```
?

**Comment by willthiswork89** [comment]
I uncommented that but its still having the issue. I'm not convinced its a bad LCD since it works fine until i do something. I have also found that is i adjust the "LCD_WIDTH" i can "simulate" the issue so im wondering if somewhere the lcd_width is being changed

**Comment by WrQth** [comment]
I am having the same issues as well running RC8 & bugfix and have defined #define DOGM_SPI_DELAY_US 5. With value at 5 it would be fine at info screen if I didn't do anything but would glitch if it was printing after a few minutes or if I was moving around menus randomly. Reduced value to 3 and screen glitched immediately even at power-on. Changed value to 6 and seems to be stable while not print and doing nothing and stable when navigating menu's. It's late so haven't checked it while printing but will and provide an update.

**Comment by Blue-Marlin** [comment]
@WrQth 
```
  // Enable this option and reduce the value to optimize screen updates.
  // The normal delay is 10µs. Use the lowest value that still gives a reliable display.
  //#define DOGM_SPI_DELAY_US 5
```
Does this description need improvement?
If you have problems with this, enlarge the time or let it commented.

**Comment by yhfudev** [comment]
I think there's some kind of electromagnetic interference to your LCD cable, or bad contact.

**Comment by WrQth** [comment]
@Blue-Marlin I had started with it commented but upon finding this thread I un-commented it with success after changing the value to 6. Perhaps a line describing a common symptom changing this setting resolves such as reduces screen artifacts by setting a shorter delay, also include the negative impact if any of changing the setting to far. By lowest value does it mean a smaller number resulting in a shorter delay or a larger number resulting in a longer delay?

@yhfudev I will need to investigate this more, perhaps shield the other wires/cables that follow the same path or reroute the cables, but the reprap discount smart controller had no issues with the same cable and installed location.

**Comment by willthiswork89** [comment]
I have verified that replacing the controller fixed the issue for me with no additional modifications. I tried all the debugging options mentioned here as well as going in and digging into the code and nothing worked. Brand new screen showed up, plugged it into same exact wires and expansion board and it worked fine. I cannot imagine that it has so many failures but... who knows.

**Comment by WrQth** [comment]
@willthiswork89 Looks like I will need to replace mine as well, further testing and adjustments and it still glitches.

**Comment by webnamex** [comment]
since i replace  the lcd screen, The problem is solved.

**Comment by thinkyhead** [comment]
For future reference, you can also try experimenting with these delays:
```cpp
// If you want you can define your own set of delays in Configuration.h
//#define ST7920_DELAY_1 DELAY_0_NOP
//#define ST7920_DELAY_2 DELAY_0_NOP
//#define ST7920_DELAY_3 DELAY_0_NOP
```
(…defined in `ultralcd_st7920_u8glib_rrd.h`)

**Comment by rmnhsd** [comment]
Where is DELAY_0_NOP defined? I get:

'DELAY_0_NOP' was not declared in this scope

**Comment by AnHardt** [comment]
Don't use ancient tips for ancient code.

Use `DELAY_NS( x )` now.
