### ISSUE TITLE
Bug when SAV LCD option is SSD1306

### ISSUE THREAD

**Issue by DiegoLale** [MarlinFirmware/Marlin#5545]
I'm trying to configure Marlin 1.1.0-RC8 in my "lalita" printer.
I use a 0.96' glcd like SAV but with ssd1306 chipset.
If I try to select this chipset in configuration.h I just found a issue.
The code below is the code without changes.
![prueba0](https://cloud.githubusercontent.com/assets/6343725/21296668/5c621b66-c571-11e6-913f-8ac40b400d35.png)
As you can see in line 1341 you can define "U8GLIB_SSD1306", it is not a problem, it works fine.
In line 1346 you can define "SAV_3DGLCD", and it works fine too without changes likes below.

![prueba1](https://cloud.githubusercontent.com/assets/6343725/21296628/50dc418c-c570-11e6-9c7d-b25a72407600.png)

But I have a glcd whit SSD_1306, not the sh_1106, then I change the option in line 1349 by 1348 like this.

![prueba2](https://cloud.githubusercontent.com/assets/6343725/21296741/d467b8ea-c572-11e6-8d60-966990bc6653.png)

When I try to compile it fails because an error like below.

![prueba3](https://cloud.githubusercontent.com/assets/6343725/21296754/180fce66-c573-11e6-9b2c-d68bf908b4e3.png)

If I'm not wrong the reason is because at this poit I have defined both "SAV_3DGLCD" & "U8GLIB_SSD1306". The way that marlin test if you define more than one display is in in "SanityCheck.h"

![prueba6](https://cloud.githubusercontent.com/assets/6343725/21296820/9ef9e69a-c574-11e6-9496-0a0335dfb099.png)

With this configuration marlin assumes I have selected twoo displays and it's not correct.
In line 1045 of "SanityCheck.h" the lcd counter have stored "2" instead of "1" because it have tested two TRUE options in lines 1025 & 1040. And then it reports an error.
 
![prueba6](https://cloud.githubusercontent.com/assets/6343725/21296868/a970c5a2-c575-11e6-862a-1b201494b777.png)
 
I fix it changin the line 1040 like this, it is only a suggestion, but it works. 

![prueba7](https://cloud.githubusercontent.com/assets/6343725/21296907/8d1d6df0-c576-11e6-9131-d5632c0b978d.png)

Adding ..."& !ENABLED(U8GLIB_SSD1306)" at the end of line 1040 in my case works fine.

Thanks a lot to the team for your work and your time.

**Comment by soimy** [comment]
Same here, my solution is just disable sanitycheck.h LCD error part(Last 3 lines).
```
#if COUNT_LCD_24 > 1
    #error "Please select no more than one LCD controller option."
#endif
```
