### ISSUE TITLE
Display empty screen for first menu item

### ISSUE THREAD

**Issue by vprheli** [MarlinFirmware/Marlin#5555]
Seems there is bug in the new option in `MENU_HOLLOW_FRAME` is defined in the `ultralcd_impl_DOGM.h` graphical display. By default it is defined. To see old (RC7) inverted line of selected menu item, it is necessary comment this line.

Then every click from FIRST menu line to modify parameter displayed on the third line show empty screen. Menu click from second or next lines works correctly.

Try `Prepare` > `Move Axis` > `Move 10mm` > `Move X` -> show empty screen OR `Control` > `Temperature` > `Nozzle` -> again empty screen but `Control` > `Temperature` > `Bed` (second menu line) item is OK. Seems that the screen cleaning area is too height.

**Comment by thinkyhead** [comment]
I'll look into this tonight.

**Comment by Kaibob2** [comment]
I can not confirm!  
See https://github.com/MarlinFirmware/Marlin/issues/5194#issuecomment-268078495

**Comment by vprheli** [comment]
Hi, I am sorry, the bug is still there. I downloaded the ZIP file from the
https://github.com/MarlinFirmware/Marlin/tree/RCBugFix and changed only
couple of parameters in configuration files - see attachment.
Menu-Control-Temperature-Nozzle - empty screen.

Arduino IDE 1.6.12, ArduinoMEGA2560, RAMPS1.4,
REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

and the inverted selected menu and X-Y-Z in the status screen

#if ENABLED(DOGLCD)
  // Enable to save many cycles by drawing a hollow frame on the Info Screen
  //#define XYZ_HOLLOW_FRAME
  // Enable to save many cycles by drawing a hollow frame on Menu Screens
  //#define MENU_HOLLOW_FRAME

This is only one change in the Configuration_adv.h I changed only some
parameters only for testing this bug.

For "long" time I used RC8, where this is working.

Vladimir

2016-12-20 7:15 GMT+01:00 Kai <notifications@github.com>:

**Comment by vprheli** [comment]
And just one comment. :o) If You test Prepare > Move Axis > Move 10mm > Move X, this is wrong test in the last BugFix - Move X is not on the "second line" anymore. There is additional caption line on the top "Move X" which scroll menu one line down.
Control-Temperature-Nozzle is using still the menu without "caption" and this failed.

**Comment by Kaibob2** [comment]
This video is done with the latest RCBugFix 1a26ce1cdcebf1d6e1bbd5b05c74602cc634f6ac from today.
[20161220_181518.zip](https://github.com/MarlinFirmware/Marlin/files/664333/20161220_181518.zip)

Both
#define XYZ_HOLLOW_FRAME
and
#define MENU_HOLLOW_FRAME
uncommented

**Comment by vprheli** [comment]
:o)) Sorry, this is what I wan't to do. I don't want hollow frame in the menu. Comment these macros is fully legal. First: ultralcd_impl_DOGM.h use #if ENABLED(MENU_HOLLOW_FRAME) Second: it is in the config area of the firmware.
And about the screen frame at 00:23 of the video. What is selected? The first line, second line or third line? All of them has frame around. Such hollow frame in the menu is not good solution.

**Comment by Kaibob2** [comment]
Sorry, my fault, just verified it with
`//#define XYZ_HOLLOW_FRAME`
and
`//#define MENU_HOLLOW_FRAME`
and it shows the blank screen when Control->Temperature->Nozzle.

BUT
[this fixes it](https://github.com/MarlinFirmware/Marlin/pull/5567/files)

**Comment by vprheli** [comment]
Yes, fixed. Great job. Thanks

**Comment by Kaibob2** [comment]
Confirmed fixed. Please close this one then.
