### ISSUE TITLE
Remove BIV2.5 from delta examples folder

### ISSUE THREAD

**Issue by clefranc** [MarlinFirmware/Marlin#5556]
@thinkyhead , can you please remove the BIV2.5 configuration file from the examples folder? Owners of this delta have so heavily modified it that is worthless to maintain even a basic configuration for the stock version (that likely not exist anymore).

**Comment by thinkyhead** [comment]
I don't mind removing it.

Is there nothing worth keeping there, such as the arm lengths and other basic geometry?

**Comment by clefranc** [comment]
@thinkyhead , can be safely removed, one less config file to maintain, the default one is just fine.
