### ISSUE TITLE
HELP!!! Nothing will upload to Mega 2560

### ISSUE THREAD

**Issue by MH15** [MarlinFirmware/Marlin#5595]
So I've had a pretty good time uploading firmware to the arduino so far but today when I was planning on changing the steps per mm on the extruder, I never got that far cause I could never upload. Here is the error arduino gave me:

avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: The handle is invalid.

So I need to know why my laptop won't recognize the Arduino.
I've scoured the internet for answers, but didn't find anything. Any help would be greatly appreciated.

**Comment by Roxy-3D** [comment]
It may be you have some other task that has already opened the serial port.   For example, if you use PronterFace, and have been using it to talk to the AVR board.   Only one program can have the serial port open at a time.  And which ever program tries to open the serial port when another program has it open will fail.

**Comment by ghost** [comment]
Selected wrong serial port in IDE?
Plugged into a different USB port on the PC?
Mega fried?
Also, what Roxy said.

**Comment by psavva** [comment]
Restart your PC and open the Arduino IDE and try again. 

Don't open other programs such as Cura that might open the com port.

**Comment by matskat** [comment]
I have the same issue. I bet it's Cura running thats the issue. But Cura is ALWAYS running LOL! Guess I need to use a different PC or wait until this print is complete before trying to set up my ATMEGA2560 as an ISP. Good times.

**Comment by MH15** [comment]
Close Cura (from the Task Manager if necessary) then restart. You may have to turn off Cura's autostart ability. You can do this in Task Manager as well.

If you have a print running then oof not sure what to do. This is one of the reasons why it's often better to print standalone.
