### ISSUE TITLE
Subtitles menu in ROM or RAM?

### ISSUE THREAD

**Issue by android444** [MarlinFirmware/Marlin#5608]
Is subtitle menu in ROM or RAM?

**Comment by Bob-the-Kuhn** [comment]
Can you point us to something specific in the Marlin code?   I couldn't find any reference to **subtitle** in the code.

**Comment by manianac** [comment]
Any strings for the menu system (if thats what you're referencing) are in flash (pgm space).

**Comment by android444** [comment]
Ok. Thanks.
