### ISSUE TITLE
jerk calculation for delta kinematic

### ISSUE THREAD

**Issue by fgramazio** [MarlinFirmware/Marlin#5618]
Hi all
I am new to Marlin and have an issue with the calculation for the jerk for the delta kinematic for which I could not find any answer on the web. What I do not understand is why in planner.cpp the jerk is calculated only considering the speed change on the X and Y axes:

float jerk = sqrt(pow((current_speed[X_AXIS]-previous_speed[X_AXIS]), 2)+pow((current_speed[Y_AXIS]-previous_speed[Y_AXIS]), 2));

while with a conventional 3 axes kinematic where each stepper corresponds to an axis this makes sense, in a delta kinematic, where X and Y correspond to the positon of the steppers on the towers A and B, not considering the third tower in the calculation is obscure to me. has anybody an explanation for this? many thanks in advance, fabio

**Comment by thinkyhead** [comment]
That appears to be obsolete code. The jerk calculation in the latest Marlin code is quite different.
