### ISSUE TITLE
SAFE_HOMING Y axis not moving

### ISSUE THREAD

**Issue by lukeskymuh** [MarlinFirmware/Marlin#5621]
In RC8 BugFix the Y axis remains at the endstop when G28 is called instead of moving to the centre:
my marlin is attached. I only changed the configuration.h file
[Marlin-RCBugFix.zip](https://github.com/MarlinFirmware/Marlin/files/676430/Marlin-RCBugFix.zip)
.
The X axsis is moving to the centre as it should.

**Comment by Blue-Marlin** [comment]
Check your endstop configuration with M119.

**Comment by lukeskymuh** [comment]
Works as it should: 

when nothing is pressed:
21:21:39.269 : Reporting endstop status
21:21:39.269 : x_min: open
21:21:39.269 : y_min: open
21:21:39.269 : z_min: open

when I press the y endstop:
21:20:48.236 : Reporting endstop status
21:20:48.236 : x_min: open
21:20:48.239 : y_min: TRIGGERED
21:20:48.239 : z_min: open

I have tested X and Z also.

**Comment by lukeskymuh** [comment]
Maybe the protocol of tge G28 command is usefull:
21:35:00.646 : N37 G28*39
21:35:00.649 : echo:N37 G28*39
21:35:01.315 : N38 M105*28
21:35:04.371 : N39 M105*29
21:35:07.433 : N40 M105*19
21:35:10.490 : N41 M105*18
21:35:13.544 : N42 M105*17

**Comment by lukeskymuh** [comment]
I have the impresion the stepper is trying to move to the wrong direction (only when moving to safe home position).

When execute G28 Y0 can manually move the Y axis as it should. (direction and magnitude are correct).
With  G1 Y110 the Y axis moves exactly to the correct position.

**Comment by lukeskymuh** [comment]
The configuration.h file I used was originallly for the RC8 (not Bug Fix)

**Comment by lukeskymuh** [comment]
Issue is solved. My stepper current was to low. Sorry for the inconvenience.
