### ISSUE TITLE
Should language_kana.h be renamed as language_jp.h?

### ISSUE THREAD

**Issue by a4jp-com** [MarlinFirmware/Marlin#5624]
I noticed the japanese files are named kana. Is it better to use jp instead?

language_kana.h → language_jp.h
language_kana_utf8.h → language_jp_utf8.h

**Comment by boelle** [comment]
i would say yes, even thou i dont know any japaneese :-D

**Comment by a4jp-com** [comment]
I can help with that ;) I've been living in Japan for about 16 years.

**Comment by AnHardt** [comment]
As long as it is not tried, to implement Kanji or Hiragana, renaming Katakana to jp makes sense.

**Comment by thinkyhead** [comment]
The ISO639-1 code for Japanese is `ja`, not `jp`.

**Comment by thinkyhead** [comment]
We can apply this change after merging the new UTF-8 support code.

**Comment by a4jp-com** [comment]
Did you new UTF-8 support code get added?
