### ISSUE TITLE
M851 will not have effect below Z0

### ISSUE THREAD

**Issue by djuniversal** [MarlinFirmware/Marlin#5631]
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/678970/Configuration.h.txt)

Using 1.1 RC8

I cannot seem to get my nozzle to go below Z0 with any probe offset settings.

I have an inductive probe with great repeatability

My probe offset is set in configuration.h and in EEPROM as Z-0.20
I have tried this by changing the config file. Then I enabled EEPROM and tried M851 commands followed by M500s. I can change my M851 Z-2 with no change. The only change occurs greater than M851 Z0

**Comment by djuniversal** [comment]
OK. I didn't want to be "that guy" so I installed RC Bug Fix and it worked. Sorry for being "that guy"

**Comment by manianac** [comment]
All good man, just please close the issue.
