### ISSUE TITLE
RC8 Z home during final G1 command

### ISSUE THREAD

**Issue by jaysonkelly** [MarlinFirmware/Marlin#5637]
I have RC8 configured for the Rigidboard v2 using full graphic and smart Reprap displays. The machine consistently homes z during the final move in the gcode. The final move sends the bed to the front of the printer and the next line disables the steppers. The same gcode doesn't cause Z to home when using bugfix firmware. 

Am I missing a setting somewhere?

**Comment by thinkyhead** [comment]
Closing as fixed, since the bug doesn't manifest in `RCBugFix`.
