### ISSUE TITLE
Manual Mesh Bed levelling hangs

### ISSUE THREAD

**Issue by DjDemonD** [MarlinFirmware/Marlin#5644]
Using RCbugFix 31-12-16 on a corexy. Migrating from RCBugFix 25-09-16 with no issues.

After selecting "level-bed" from the lcd it homes z then hangs showing "Homing XYZ" on the LCD, nothing on the console, it doesn't get as far as homing x and y. Homing works on this machine with this firmware otherwise, but I was using manual mesh levelling before and now am unable to do so.

[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/680031/Configuration_adv.h.txt)
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/680032/Configuration.h.txt)

**Comment by epatel** [comment]
Duplicate? https://github.com/MarlinFirmware/Marlin/issues/5592

**Comment by alexxy** [comment]
Seems yes to me =)

**Comment by DjDemonD** [comment]
I'd agree it is and I can close it if you wish. However that issue remains unresolved.

**Comment by psavva** [comment]
@DjDemonD please close this issue as a PR is already submitted #5634
