### ISSUE TITLE
custom servo sweep causes a restart

### ISSUE THREAD

**Issue by jerryerry** [MarlinFirmware/Marlin#5697]
The servo can move using m280, and I wrote custom code to sweep the servo, but marlin resets after about 2sec. I tried running it without the servo as well, in case the servo is just really cheap, but it still causes a restart?

**Comment by shacal** [comment]
Watch dog enabled?
Post custom code, hard to say anything if nothing to check (memory leak, pointers etc).
Enough power for board and servo?

**Comment by Roxy-3D** [comment]
> Watch dog enabled?

Any time you loop for a long time....   You need to call idle();   or the Watch Dog Timer will reset the board.

**Comment by jerryerry** [comment]
Thank you!!!  adding idle()  did the trick

**Comment by psavva** [comment]
@jerryerry, suggest you close this ticket :)
