### ISSUE TITLE
RC8 / Bugfix REPRAP_DISCOUNT_SMART_CONTROLLER Rotary Encoder Menus inaccurate

### ISSUE THREAD

**Issue by leecuk** [MarlinFirmware/Marlin#5704]
Whilst attempting to resolve the ABL issues i'm having, I've noticed that quite often I'm not entering the menu items I'm trying to select and get the one above it - it might be that it is detecting movement as part of the button push, but the behaviour isn't as accurate as it was in 1.0.x.

I'm using REPRAP_DISCOUNT_SMART_CONTROLLER.

Anyone notice this?

**Comment by ghost** [comment]
Have you played with these settings?

`#define ENCODER_PULSES_PER_STEP 4`
`#define ENCODER_STEPS_PER_MENU_ITEM 1`

**Comment by leecuk** [comment]
Thanks, the default settings have been changed to 
```
#define ENCODER_PULSES_PER_STEP 1
#define ENCODER_STEPS_PER_MENU_ITEM 5
```

With no override for the REPRAP_DISCOUNT_SMART_CONTROLLER

Changing to your/original settings are much better and better match the detents on the encoder.

Should an override be added?

**Comment by ghost** [comment]
The settings I posted were not default, but what works for my Reprap Full Graphic LCD.
Change the numbers to your liking.
I'm not sure what 'override' you mean.

**Comment by leecuk** [comment]
I believe, although I could be wrong, the settings you posted were the default back in 1.0.x. I had a quick look and that's what they seem to be. They work much better than the new ones, at least for me. I was just suggesting that there are already redefines of some of the encoder steps for certain interface boards that override the default settings. Possibly a new one could be added for this very popular board? Maybe it differs between boards, Thanks for your help though :-)

**Comment by tetraDB** [comment]
I experience the same issue with stock settings from the same REPRAP_DISCOUNT_SMART_CONTROLLER. I messed with the ENCODER_PULSES_PER_STEP and it's behaving better.
Seem the selected menu item index (if that how it works) is becoming an invalid value, -1 or something. I notice I can scroll all the way to the top, then I have to scroll down twice to get the highlight to move. Sometimes when I select a menu item, it actually clicks the one above. It's difficult to reproduce and this is the best way I can describe it sorry!
Where I notice it a lot is when I go to preheat the bed instead and instead it clicks the one above so both bed and hotend heatup.

**Comment by thinkyhead** [comment]
So it looks like we should add an override for the `REPRAP_DISCOUNT_SMART_CONTROLLER` as with some of the other displays.
