### ISSUE TITLE
Speed change while printing slow

### ISSUE THREAD

**Issue by KaiJan57** [MarlinFirmware/Marlin#5717]
Looks like the speed is changed by changing new commands which are to be sent to the buffer. Why not change the speed by the motor isr instead?

**Comment by Bob-the-Kuhn** [comment]
The stepper ISR only runs when there is a movement command.

All movement commands are sent to the planner.  The planner creates a structure with all the needed parameters and adds the structure to a queue.  It then kicks off the stepper ISR which grabs structures from the queue and uses info from the structure to do the actual movement. 

This method is used to make designing and maintaining the software more manageable.  Isolating functions in separate modules makes it easier to make changes that don't have unintended consequences.

 Hope this answers your question.

**Comment by psavva** [comment]
@KaiJan57 can you close this issue based on the explanation from @Bob-the-Kuhn
