### ISSUE TITLE
The offset settings of probe are not relative over M206 Home offset

### ISSUE THREAD

**Issue by tximy** [MarlinFirmware/Marlin#5718]
The offset settings of probe are not relative over M206 Home offset (if that define the T0 Absolute offset)

feature request : Upgrade M851 with X and Y offset for configure multiple tools. The probe has many offsets depending of the head tool installed.
We need an upgraded  M851 to set the X and Y axis offset for a diferent settings on multiple heads or tools, when change the tool, we can configure it with a gcode stored on a configuration's tool file with the settings, and write this tools's settings over EEPROM memory.

Thx.

**Comment by thinkyhead** [comment]
> The offset settings of probe are not relative over M206 Home offset

I presume you're talking about the `RCBugFix` branch.

The probe offset and `M206` home offset should interact properly.

> Upgrade M851 with X and Y offset for configure multiple tools

The `M218` code is used for setting tool offsets - currently only applicable to hotends, and the first hotend's offsets must be { 0, 0, 0 }. In future we may support more tools.

The probe is not a tool, but is presumed to be affixed to the first carriage and always moves in parallel with the first tool.
