### ISSUE TITLE
Using singlenozzle and z probe together causes X axis accel, feedrates to change dramatically

### ISSUE THREAD

**Issue by 3djag** [MarlinFirmware/Marlin#5745]
Im trying to get the singlenozzle feature to work with my new single motor single nozzle dual [extruder] from thingiverse.. Im using the instructions outlined in that post to get E1 to reverse direction when a tool change is called. 
When I enable singlenozzle and zprobe and reflash, the extruder works as it should reversing directions when t1 is called but the x axis settings are multiplied exactly 10x so that When I command X to move 10mm, it moves 100mm! (confirmed with digital calipers. )    gladly Y ,Z and E1-2 act normally as far as steps per mm.
No matter what I set for steps per mm and acceleration,ect... X axis moves so fast that it skips nearly all of the steps when commanded. All other operations function just like everyother time Ive flashed marlin with acception of homing(see below). 
 I have to slow down x to 5mm/s in simplify just to be able to move X without skipping steps.
X and y will not home either. When commanded to home either x or y,...the carriage moves 10mm to max then stops and will not let me manually move under what it thinks is zero even though min software limits is off.
I even swapped drivers by changing pins to match my empty E2 driver slot and everything that gets sent to x axis is multiplied. I also tried swapping out the motor/wires for a new spare and the same thing. I even went as far as swapping out the board for a new spare as well, and the same old thing so its definately a firmware issue.
 Im flashing with arduino 1.81 onto an mpx.3 board via usb. 
I also use a zprobe thats manually deployed by startup code but not used (i have a zprobe that is deployed/stowed manually by gcode via bumping the carriage against either side of the gantry, but I couldnt set a probe up without telling marlin it uses a servo which it doesnt) Prior to the singlenozzle problem Im having now, the z probing routine was smooth running even my method isnt officially supported by marlin. It would be nice to have an option for a zprobe that isnt fixed, manually deployed by finger,on a remote sled or servo driven.  A probe that uses a rack system to extend/retract a zprobe like mine.
I  had some serious issues with prints consistantly measuring less by 0.15mm in either plane on a 20mm calibration square no matter what I changed the extrusion multi to when using both RC7 and 8, so I have tried to avoid RC7+ because of this major problem.    But seing how I have a new dual extruder now ,I want to try out the new multiextruder features of Marlin but cant get them to work as they should.

**Comment by Bob-the-Kuhn** [comment]
X movement is as expected when T0 command is issued, screwed up after issuing T1 but is OK again after issuing a T0 command.

Please add a link to the Thingiverse item that you're talking about.  I want to be sure they used the INVERT_E1_DIR flag.

What commands are you sending to the printer when you switch?

**Comment by thinkyhead** [comment]
Does the issue persist after `M502`, `M500`?
