### ISSUE TITLE
Two or more MAX6675/MAX31855 / Selct Temp Sensor

### ISSUE THREAD

**Issue by Keff789** [MarlinFirmware/Marlin#5748]
Hello,

it would be nice to have the ability to use more than one MAX6678/31855. This should be easily achievable because the CS is already managed by defines. 
The next step would be to make selectable on which sensor you use the MAX6678/31855 so maybe heatbead or sensor 2.

Best regards
Kevin

**Comment by Bob-the-Kuhn** [comment]
This is on the Marlin "things to do" list.  See PR #4894
