### ISSUE TITLE
G92 E0 affects X axis when DISTINCT_E_FACTORS defined

### ISSUE THREAD

**Issue by rekeyed** [MarlinFirmware/Marlin#5749]
I have two extruders on Prusa i3, and enabling DISTINCT_E_FACTORS leads to such results:

```
G28
echo:Active Extruder: 0
echo:Active Extruder: 1
X:100.00 Y:131.00 Z:10.80 E:0.00 Count X: 8000 Y:10480 Z:34560
G92 E0
X:100.00 Y:131.00 Z:10.80 E:0.00 Count X: 8000 Y:10480 Z:34560
G1 X10 F5000
```
all seems to be good, but carriage moves right 10mm instead of 90mm left (physically X position is 110, in firmware 10). So, `G92 E0` command sets X to zero, but not shows that.

relative coordinates are broken too:
```
G28
echo:Active Extruder: 0
echo:Active Extruder: 1
X:100.00 Y:131.00 Z:10.80 E:0.00 Count X: 8000 Y:10480 Z:34560
G91
G92 E0
X:100.00 Y:131.00 Z:10.80 E:0.00 Count X: 8000 Y:10480 Z:34560
G1 X-50 F5000
```
and carriage moves 50 mm right instead of left

I repeat this on RC8 and today's RCBugFix branches
when DISTINCT_E_FACTORS not defined, machine works well.

**Comment by alejandrocragnolini** [comment]
+1
I'm having the same problem.

**Comment by thinkyhead** [comment]
Please post your `Configuration.h` file. (You may need to ZIP it before you can drop it on the textfield.)

**Comment by rekeyed** [comment]
here is my Configuration.h
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/769551/Configuration.zip)

**Comment by alejandrocragnolini** [comment]
Here is mine.

I commented DISTINCT_E_FACTORS to keep going with the calibration of the machine.

[Configuration.h.zip](https://github.com/MarlinFirmware/Marlin/files/772227/Configuration.h.zip)

**Comment by thinkyhead** [comment]
I'll look at these more closely this afternoon (i.e., in about 10 hours).

**Comment by thinkyhead** [comment]
I think this one is fixed now in `RCBugFix`. Please confirm.

**Comment by rekeyed** [comment]
latest RCBugFix works well with DISTINCT_E_FACTORS enabled on my machine. thanks!
