### ISSUE TITLE
reprapdiscount smart controller weird pulsing and artifacts.

### ISSUE THREAD

**Issue by nikki-reprap** [MarlinFirmware/Marlin#5751]
I have updated to the latest rc bug fix and I am now getting weird pulsing and artifacts on the lcd on the reprapdiscount smart controller.

**Comment by ghost** [comment]
Ensure you do not have a short somewhere on the 5v rail.

**Comment by nikki-reprap** [comment]
Thanks ill check it now.

**Comment by nikki-reprap** [comment]
It turned out to be a faulty stepstick 

Thanks
