### ISSUE TITLE
Velleman k8200

### ISSUE THREAD

**Issue by reblair** [MarlinFirmware/Marlin#5764]
The Marlin/pins_K8200.h must be wrong.  It seems the y direction is reversed causing the printer to crash into the high y end and ignore the stop switch when sent home.

**Comment by mperdue** [comment]
Have you tried reversing the Y direction?

#define INVERT_Y_DIR true

**Comment by thinkyhead** [comment]
Or, the example configuration for K8200 has `INVERT_Y_DIR` set incorrectly. Or, the stepper is plugged in the wrong way.

This is a question for @CONSULitAS

**Comment by CONSULitAS** [comment]
@reblair @thinkyhead 

The example configuration for K8200 works right now on my printer.

The printer worked without changes on the Stepper cables with stock firmware. So I would say mine is OK. And so the example is ok, too.

@reblair Please try the stock firmware to check this. If it shows similar behavior, please fix your stepper cables. They are soldered wrong. Check the build instructions to be sure: http://www.k8200.eu/manual/building/?c=016
