### ISSUE TITLE
How works the Marlin Firmware ?

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#5768]
Hello everybody,

I use Marlin for 6 months, without touching the source code (except the conf files).
But now, I would like to begin with the source code and understand how this firmware works.

However, I don't find documentation or diagrams about that, and my analysis has not resulted in much.
More, the Wiki is very light and there is no code documentation (Class, Methods, Dependencies, etc).

It can be a good idea to develop this type of documentation.
A good documentation can improve the quality of the development with a clear understanding of the environment and how it works, but also motivate new developers to contribute in this project.

Thanks everybody for your job in this project.

**Comment by ghost** [comment]
Trial and error has been my teacher. Lol

**Comment by ghost** [comment]
@Tannoo _Your comment is needless. Documentation would save time. Analyzing the code without a starting point and without guiding thread is wasting time, and some of us don't have much._

A good documentation can help beginners like me, and structure the project to ensure a good cohesion in the developments.
Greatest OpenSource projects have API references, Building procedures, Code documentation, etc.
It's easy to start, even if the project is started several years ago.

Finally, what the target of a project like Marlin ?
 - To be restricted to a closed community of depressive warrior geeks ?
 - Or to be opened to a large community, with various skills and different levels ?

**Comment by Roxy-3D** [comment]
Have you looked at:   https://github.com/MarlinFirmware/MarlinDocumentation ?
What topics have failed to help you?

By definition, Marlin is not restricted to a closed community of depressive geeks.   Everybody is welcome and we accept good (meaning useful, well thought out and carefully coded) contributions from where ever they appear.

**Comment by ghost** [comment]
@clemsept, if you had looked around, you would have found the documentation project.

I can't just simply give you my opinion?

I have been using Marlin for about a year and have tried to contribute things I have done to my firmware for features that I use.

BTW, I don't believe Marlin is the code to start with for a beginner in Arduino.

**Comment by ghost** [comment]
Ok thanks for your help and for links :)

**Comment by thinkyhead** [comment]
Please contribute to the documentation project. We are very short on help.
