### ISSUE TITLE
How to add custom code to Marlin?

### ISSUE THREAD

**Issue by ronan635** [MarlinFirmware/Marlin#5783]
Hello, I'm currently developing my own simple GUI with python to control the basic movements of my 3D printer. I am using an Arduino Mega 2560 with a RAMPs 1.4 board. I am wondering how and where would I add custom code for me to be able to control the stepper motors when a specific button is created within Python. Or could someone point me in the direction of where the functions are for the buttons/commands within marlin that I could use, instead of adding more code, to control the printer with my GUI developed with Python? Any help would be greatly appreciated!

**Comment by Blue-Marlin** [comment]
I assume, if you are writing in python, your program is running on a host - not on the Arduino. In that case you have to communicate via the serial line with g-code.

**Comment by ronan635** [comment]
Yes I know that I have to use the serial line but I'm having trouble of how to actually send the command to the Arduino for it to process the command.

**Comment by stigjoergensen** [comment]
Just Googled this - so it might help you

import timeimport serial

```py
ser = serial.Serial(
    port='\\\\.\\COM4',
    baudrate=115200,
    parity=serial.PARITY_ODD,
    stopbits=serial.STOPBITS_ONE,
    bytesize=serial.EIGHTBITS)if ser.isOpen():
    ser.close()
ser.open()
ser.isOpen()

ser.write("M119\r")
out = ''# let's wait one second before reading output (let's give
device time to answer)
time.sleep(1)while ser.inWaiting() > 0:
    out += ser.read(40)
if out != '':
    print(">>" + out)


ser.close()
```

Here I'm sending the M119 command (show status of endstops)

For a nearly complete list of G-Codes see this link:

http://reprap.org/wiki/G-code

**Comment by Roxy-3D** [comment]
If you look in Marlin_main.cpp, you will find the 'M'-Code handler.   If you just grab an unused MCode, you can splice in your code.  You would just duplicate the syntax already in place but put your code in the body of the switch() statement:
```cpp
    case 'M': switch (codenum) {
      #if ENABLED(ULTIPANEL) || ENABLED(EMERGENCY_PARSER)
        case 0: // M0: Unconditional stop - Wait for user button press on LCD
        case 1: // M1: Conditional stop - Wait for user button press on LCD
          gcode_M0_M1();
          break;
      #endif // ULTIPANEL

      case 17: // M17: Enable all stepper motors
        gcode_M17();
        break;
```

**Comment by amrithmmh** [comment]
@thinkyhead  i tried the above python code with baud 250000  but i get only rubbish/gibberish values printed in output
any suggestion?

**Comment by revilor** [comment]
@amrithmmh I guess your python code and Marlin are not set to the same baud rate.

**Comment by amrithmmh** [comment]
@revilor thanks for the reply  i just pressed the reset of arduino and then next next i connected with the same code slight modification and it worked
now i am trying to use pronterface(procore class) it is also working but i noticed that sending a G0 command return no OK or done as feedback

**Comment by amrithmmh** [comment]
seems that there was an OK after every command but pronterface is not showing it but when i used arduino ide serial monitor it is giving Ok feed back also @thinkyhead  code is not formatted one
this is slightly edited one https://gist.github.com/amrithmmh/b22c9dc4e8bd610e7158d8586133b602
