### ISSUE TITLE
Marlin 1.1 RC8 LCD on MKS Gen 1.4 not working

### ISSUE THREAD

**Issue by mhrahmani** [MarlinFirmware/Marlin#5784]
Hi there!
So the connections on my RAMPS+Arduino boards weren't reliable so i swapped it for and all in one MKS Gen 1.4.
So Marlin RC6 works fine,
But when i uploaded RC8, LCD only shows two lune with the bottom line missing.
I will upload a picture of my LCD and my configuration.h settings right away.

**Comment by thinkyhead** [comment]
Fixed?
