### ISSUE TITLE
Auto-leveling - repeated probing

### ISSUE THREAD

**Issue by Gad** [MarlinFirmware/Marlin#5789]
Hello,
I just move to the latest RC8 bug fix to take advantage of the bilinear algorithm (I was in RC4 where apparently it wasn't yet available and my bed is very uneven), did my configuration again and everything is working as expected apart from one detail : there is no second probing on each point as it used to be the case. 
I did uncomment "#define Z_MIN_PROBE_REPEATABILITY_TEST" as I thought it was the option to use.
I'm using Auto-leveling with a BLtouch, 4x4 grid,  bilinear "mode" on Prusa I3/RAMPS
Did I miss something ?
Thanks !

**Comment by FHeilmann** [comment]
~~what's your~~

~~`#define Z_CLEARANCE_BETWEEN_PROBES` ? if it is too low the "fast touch" is omitted and only the "slow touch" is carried out.~~

**Comment by Roxy-3D** [comment]
And just to be clear:   If you have a BL-Touch, you can't go super slow or you will lose position and often times cause the probe to go into an error state.       There are two fixes.  I am using both fixes on my printer with a BL-Touch probe and have not had a nozzle crash since I did that.

First, if you can turn on 
```cpp
// Enable this feature if all enabled endstop pins are interrupt-capable.
// This will remove the need to poll the interrupt pins, saving many CPU cycles.
#define ENDSTOP_INTERRUPTS_FEATURE
```
in your Configuration.h file.   That way you should not miss the 5ms pulse the BL-Touch puts out.   But then add this Pull Request to your firmware: https://github.com/MarlinFirmware/Marlin/pull/5729

It checks the end stops more often (which shouldn't be active with the above Configuration.h setting).  But it also is looking for the BL-Touch to be in an error state and takes steps to clear it.

**Comment by Bob-the-Kuhn** [comment]
Is **#define PROBE_DOUBLE_TOUCH** commented out?

**Comment by Roxy-3D** [comment]
@Blue-Marlin   Why the down vote?   What is incorrect in what I said?

**Comment by Blue-Marlin** [comment]
@Roxy-3D 
Not incorrect, but no relation to the question.

**Comment by Roxy-3D** [comment]
I disagree...  People with BL-Touch probes are vulnerable to nozzle crashes at low speeds.   If he is looking to have Double Touch probing that implies he is trying to make the probes happen at a slow speed.   

I was trying to help him protect his printer from damage.

**Comment by Blue-Marlin** [comment]
Q: What time is it?
A: February

Not wrong - but not the answer.

Q: there is no second probing on each point as it used to be the case. ... Did I miss something ?
A: `#define PROBE_DOUBLE_TOUCH`

100%

A: `#define PROBE_DOUBLE_TOUCH`. But this does not improve the accuracy of the probing ( https://github.com/MarlinFirmware/Marlin/pull/4455#issue-168307569).

110%

**Comment by Gad** [comment]
Hi, thanks to all for the suggestions.

- Yes indeed  `#define PROBE_DOUBLE_TOUCH` in commented out. I'll leave it this way. Moreover, I've set the Z axis acceleration very low already
- as a side note, I'm pretty sure it does the double probing on `G28` (I don't have access to the printer until next week)
- I experience BLTouch alarm every once in a while, quite seldom to tell the truth so I'd rather wait for the new RC to be posted.
Thanks again!

**Comment by Bob-the-Kuhn** [comment]
> I experience BL Touch alarm every once in a while

When triggered, BLTouch retracts the probe, waits and then drops it again.  If it triggers on the second drop then it goes into alarm.

Either you're running at extremely slow speeds or you have your `Z_CLEARANCE_DEPLOY_PROBE` or `Z_CLEARANCE_BETWEEN_PROBES` set too low.
