### ISSUE TITLE
RC8 and RCBugFix: Shrinked Layers (Michelin Man Results)

### ISSUE THREAD

**Issue by bamkrs** [MarlinFirmware/Marlin#5807]
I recently switched from 1.0.2-2 to 1.1.0-RC8 and confirmed it on RCBugfix 1e4d4e5.
My print results on 1.0.2-2 where ok I guess. Needed some minor Hardware-Tweaking.
But when I try to print something on RC8 or RCBugfix 1e4d4e5 the hull looks like the Michelin Man:

![img_20170211_200422](https://cloud.githubusercontent.com/assets/4124784/22856723/d25a2c0e-f097-11e6-8154-b7299a1013db.jpg)
From left to right:

1. **1.0.2-2**
2. **RC8** You see the rings?
3. **1.0.2-2** Back at 1.0.2 but with a faster acceleration
4. **RC8** Again with same acceleration of 3th
5. **RCBugFix 1e4d4e5** Still got the rings

These where 5 subsequent prints with the same PLA, exact same G-Code, same configuration (from 2nd to 3th the acceleration changed), same extruder, same hotend, same day and same everything.
The interesting thing is, that the shrinked layers look like a sin-curve and go all the way round. So its not just one axis in one direction, its shrinked on boot axis. Kinda like the [Michelin Man](https://s-media-cache-ak0.pinimg.com/736x/9a/cd/b1/9acdb142a1f3f13dccc6df5e2899ad85.jpg). 

Any Ideas? Since the problem is gone if I go back to 1.0.2-2 I consider it a Marlin-Bug rather then a hardware issue.

**Comment by epatel** [comment]
Do you print from USB or SD?

**Comment by epatel** [comment]
This? Heatbed behaviour? https://3dprinting4u.wordpress.com/printing/

**Comment by emartinez167** [comment]
I can confirm that ensuring the heated bed is at the right temperature will get rid of those patterns. Worked for me.

Regards,

Ernesto

**Comment by bamkrs** [comment]
@epatel @emartinez167 I figured out the Problem. Looks like its linked to my other issue (5805) in coop with a falsely pid-tuned bed (90c instead of 65°)

**Feature Request**: Support for multiple PID's and automaticaly choose the nearest tuned one (i.e. if Tuned values are 60°c, 70°c and 80°c and you want to print something at 64°c bed, marlin should select the 60°c PID)

**Comment by thinkyhead** [comment]
> Feature Request: Support for multiple PID's and automaticaly choose the nearest-tuned one

We may consider this after the 1.1 release.
