### ISSUE TITLE
 FILAMENT_RUNOUT_SENSOR and M119

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#5810]
I just wired up a filament run out sensor...   And with the filament in position and everything as it needs to be to print, M119 reports the Filament Run Out Sensor is TRIGGERED.   That seems backwards to me.   It reports 'Open' when the filament is missing and needs to be changed.

Should we flip the nomenclature?

**Comment by Blue-Marlin** [comment]
`FIL_RUNOUT_INVERTING`?

**Comment by Roxy-3D** [comment]
Yes that control is available.   But when everything is normal and the extruder is ready to print, M119 reports the 
```cpp
filament_Runout_Sensor: TRIGGERED
```
That seems backwards to me.  If we are going to have that report 'Triggered', the name of the sensor should be something that conveys 'Filament is loaded and available'.

Do you have a filament runout sensor?   If so, give it an M119 and see what it reports.

**Comment by ghost** [comment]
Would this be better?

In `language.h`:
```
#define MSG_FILAMENT_RUNOUT_SENSOR          "Filament: "
#define MSG_FILAMENT_RUNOUT_LOADED          "Loaded"
#define MSG_FILAMENT_RUNOUT_UNLOADED        "Unloaded"
```
In `endstops.cpp`:
```
  #if ENABLED(FILAMENT_RUNOUT_SENSOR)
    SERIAL_PROTOCOLPGM(MSG_FILAMENT_RUNOUT_SENSOR);
    SERIAL_PROTOCOLLN(((READ(FIL_RUNOUT_PIN)^FIL_RUNOUT_INVERTING) ? MSG_FILAMENT_RUNOUT_LOADED : MSG_FILAMENT_RUNOUT_UNLOADED));
  #endif
```

**Comment by ghost** [comment]
Reports: `Filament: Loaded` when ready to go and `Filament: Unloaded` when it's not.
Maybe `Filament: Out` would be a better report?

**Comment by Roxy-3D** [comment]
> Reports: Filament: Loaded when ready to go and Filament: Unloaded when it's not.
> Maybe Filament: Out would be a better report?

Yes...   This seems more logical to me.   Let's see if the idea gets any adverse reactions.

**Comment by ghost** [comment]
I don't believe this addition has been merged yet. It was part of the M600 Nozzle shutdown PR.

**Comment by Roxy-3D** [comment]
> I don't believe this addition has been merged yet. It was part of the M600 Nozzle shutdown PR.

Are you suggesting there is an outstanding Pull Request we can piggy back on?   If so...   I'm 'on board' !

**Comment by ghost** [comment]
Look at the files changed in #5794, I added it when you were about to setup your runout sensor. It was to help with checking it. I didn't have that option when I setup mine (more than a year ago).
I deemed it part of filament change anyway.

**Comment by ghost** [comment]
I can't PR against this yet. Still getting the hang of the new way to do git without special privileges.
If you can PR the changes, be my guest.

**Comment by Roxy-3D** [comment]
> If you can PR the changes, be my guest.

I'm worse at Git than you are!    Please keep trying!

**Comment by ghost** [comment]
I used to be good at the command line stuff back in the DOS days and even dabbled in Linux.
Learning a new command line structure is like trying to learn to make a perfect print by typing out the gcode in notepad without the help of a slicer.

I'm working on it, though.

**Comment by Roxy-3D** [comment]
Supposedly, Git is helpful and is indispensable.    But I'm starting to be of the opinion that people that say that are part of a cult.   It isn't intuitive and simple things I want to do are impossible.

**Comment by ghost** [comment]
I agree. But, nothing is impossible. It's only a matter of understanding.
@Roxy-3D, you over-estimate me. It wasn't long ago that I was just screwing git up and down. lol

**Comment by thinkyhead** [comment]
Filament runout sensor is perhaps named poorly. Filament presence sensor is what it really is.

**Comment by thinkyhead** [comment]
> It isn't intuitive and simple things I want to do are impossible.

Just ask for guidance. I know it well.
