### ISSUE TITLE
BLTouch unresponsive after update to RC8

### ISSUE THREAD

**Issue by DynamiteHack** [MarlinFirmware/Marlin#5812]
**@Roxy-3D** I was reading the description on the UBL-Dev Branch and noticed you require an LCD panel. I was using the Discount-LCD before I installed the BLTouch. I found I couldn't run them both. I read somewhere that it was a power issue. Didn't seem like a big deal so I put it off. What did you do to resolve the issue? Oh and I just received the LCD 12864 Graphic Smart Display Controller that I ordered so I'd probably want to use that one.
Thanks!!

Original Inquiry from #5729: 

> I started yesterday to update the firmware on my FolgerTech 2020 i3. I have been using the firmware FT supplied. I had installed a BLTouch a month or so ago. Mechanically, everything seemed to work okay. I was having some problems with my prints starting too high (Z Offset not accounted for).
> 
> While researching that issue and seeing all of the work you guys have been doing with the BLTouch, I figured I'd give updating my firmware a try!
> 
> I compared my original Configuration.h line by line with the latest from RC8 (completely new layout!!). I also went through the Configuration_adv.h files. I tried to match my settings as closely as possible but I am unable to deploy the probe. G28 does not lower pin, haven't been able to try G29 since I can't home all axis. M280 has no affect.
> 
> I just tried add this current BugFix to see if issue is addressed but I am getting errors while compiling. I had just replaced the Marlin_main.cpp. Is that how it's done? Were there other files that need to be updated? Sorry, new to the firmware end of things.
> 
> My latest Configuration.h is attached
> Configuration.zip
> 
> Thoughts and suggestions would be appreciated!!

Responses from #5729:
From @Roxy-3D 

> So.... I absolutely love my FT i3-2020! It is a really good machine. The first version of the UBL code was developed on a FT i3-2020. And the default configuration.h and configuration_adv.h files are set up for that (my machine). The only thing that is non-standard is I have the X-Min end stop on the left side instead of what their build directions state. And of course, I've put a servo based probe leg on the extruder. Other than that... If you grab the code base at: https://github.com/MarlinFirmware/Marlin/tree/devel-ubl it will compile and run on your FT i3-2020.
> 
> I'm working right now to move the code to RC-8's RCBugFix. One of the things that will do is provide the simple BL-Touch support where you just say you have a BL-Touch and the right thing happens. But right now... at that link you would still have to set your servo angles at 10 degrees and 90 degrees.
> 
> If you are willing to move to a development branch, I'll help you get it up and running on your FT 13-2020. You will be impressed. I get perfect adhesion across 100% of the bed 100% of them. And I'm using the worst piece of glass I could find at a dollar store just to make sure the system is stressed.

From @Bob-the-Kuhn 

> @DynamiteHack - yes, please open a new issue so we can help you without muddying up the waters on this one.
> 
> When switching to a new revision/branch of Marlin firmware it's best to download the whole thing and then copy your machine specific info over. Usually that just involves editing configuration.h & configuration-adv.h but might also involve editing your pins_YOUR_BOARD.h
> 
> Did the BLTouch work before you moved to the new Marlin software?
> 
> Which Marlin software did you switch to?
> 
> Issuing a M280 P0 S10 should deploy the probe and a M280 P0 S90 should stow it. If that's not happening then we'll need to look at what pins have been assigned to the BLTouch's servo signal.
> 
> Your BLTouch setup looks good.

**Comment by Roxy-3D** [comment]
> I was using the Discount-LCD before I installed the BLTouch. I found I couldn't run them both. I read somewhere that it was a power issue. 

So...   I'm not sure what to tell you.   I don't see any power issues with the BL-Touch probe.  It doesn't take much power.    But...   I have a RAMPS board on all of my printers.  What I do is run +5 volts from an external source to the +5 pin of the power connector next to the servo connectors.   I do NOT jumper the VCC pin to the +5v pin of the power connector next to the servos.    

One thing you might want to look at doing is this:   On the RAMPS board you have the big green +12 volt power connectors coming into the board (to drive the stepper motors and extruders).  On the bottom side of the board you can solder a 3 legged LM7805 to get solid clean power for the servos.   Two of the legs get soldered to the +12v and ground of the big green connector.   And the last leg of the regulator can be wired to what ever needs +5 like the +5 pin of the servo power connector.   It is a little bit of a hack, but it can be done very cleanly and with no chance of a short circuit.   The LM7805 just ends up between the RAMPS board and the processor board.

**Comment by Bob-the-Kuhn** [comment]
There's a chance that enabling the LCD resulted in one or both of the BLTouch signals being re-assigned to pin(s) that particular LCD isn't using.

If you attach the config files where the BLTouch worked and the config files with the LCD added I can see if there is conflicting pin assignments.

What do you mean by "didn't work"?  
- wouldn't even do the power up deploy/retract self test (that's definitely power)
- wouldn't deploy automatically
- deployed but the head crashed into the bed

**Comment by DynamiteHack** [comment]
**@Roxy-3D** - I will try that hack. I do have the jumper in place to power the BLTouch. 

**@Bob-the-Kuhn** - Actually, the LCD was installed before I installed the BLTouch. After I installed the touch, the display only displayed garbled text. I just pulled the display off leaving it enabled in the config file. I enabled it in the new config file figuring I'd figure out how to use it sometime.

> What do you mean by "didn't work"?

With the new config file that I posted earlier my BLTouch powers up and runs its self test.That is all. When homing, the pin never drops and the LED remains lit. The BLTouch does not respond to M280 commands at all.

The configuration that worked in the past is attached. To be clear, I removed my display _after_ installing the BLTouch. The BLTouch always worked, it was the display that gave me problems.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/769491/Configuration.zip)

**Comment by DynamiteHack** [comment]
**@Roxy-3D** - Okay. So I tried the hack, extending the +5v to the pin next to the servo plugs. Pictures are attached to confirm I understood what you explained. After making the change I uploaded the UBL sketch you suggested. I attached the discount LCD I have and powered up. Everything looked good. I had a LCD display working properly and the BLTouch glowed!!

I did a G28 to home the nozzle. X homed correctly. Y homed correctly. As soon as the nozzle attempted to start the Z homing, the LCD went blank and a puff of "magic smoke" escaped from the area of my hack. I did notice when I disconnected the printer from the main power, the LCD turned back on, still getting power from the USB. Was there anything I should have changed in the settings before  I tried to run it? Something pin related maybe??

I took everything apart. Arduino seems okay. Hopefully the Ramps is okay and I just lost the regulator. I don't want to power back up until I know if there is some setting I should have changed.

Sorry. My first time doing this. Exciting stuff!!

![img_20170212_211330](https://cloud.githubusercontent.com/assets/2524467/22872074/2ddda578-f16b-11e6-8b99-b6ce302d80bc.jpg)
![img_20170212_211359](https://cloud.githubusercontent.com/assets/2524467/22872077/30642a42-f16b-11e6-8a84-440492e8ff57.jpg)

**Comment by Roxy-3D** [comment]
That looks correct.   The middle leg is connected to ground and the input is on the +12 volt connection. Did you measure the voltage on the blue wire before plugging it in?  I would have done that, but it sure looks like that should have worked.    Did you visually inspect there was no short circuit when you plugged the two boards together?   There aren't any metal parts on the processor board where you soldered the LM7805 so it should have been OK.   I even pulled out a MEGA-2560 / RAMPS board and looked at the mounting holes.  Even if you were using metal screws to mount the boards, they are clear of where you did the work.  

Knowing what fried would be helpful to figuring out what went wrong.   I've done this 3 or 4 times and never had a problem.  Did you see where the smoke came from?   

> Was there anything I should have changed in the settings before I tried to run it? 

No.  The processor board is setup so that it doesn't care where the power it gets is coming from.   It can come from the power connector (black round thing) where you soldered the LM7805 or it can come from the 12 volts coming in from the big green connector, or it can come from the USB.   

One more thing I should have pointed out.  If you are using an ATX power supply for a desk top computer, there will be a +5 volt wire coming out of it.  Usually it is Red.  In that case, you don't even need to mess with generating  5 volts with a LM7805.  You can just plug that red wire into the +5 volt servo connector.   Is your supply just providing +12 volts?

**Comment by Bob-the-Kuhn** [comment]
I believe that the 7805 was defective.   It has thermal overload and short circuit protection so it shouldn't have lost it's magic smoke.

**Comment by DynamiteHack** [comment]
Thanks for the response. I'll put things back together and see if I can figure out what went wrong. I did not measure the voltage coming out of the wire. I'll try that next...I'm going to put a new regulator on and see what happens. I'll let you know...

**Comment by Roxy-3D** [comment]
I would take the regulator off....   and see if everything still works as it did before.    And if that is the case, I would measure the voltage on the pin I soldering the input of the LM7805.   It should be a rock solid 12 volts.   I don't think this is happening, but if it was 20 volts, that could fry the LM7805.

The thing is, LM7805's are very tough parts.   And they can with stand a lot of abuse.   It is very strange if that part died as soon as power was applied.    It might also make sense to disconnect any and all servos plugged into the servo connectors the first time you power up.   After you measure the voltage coming out of the LM7805 you can verify it doesn't change when you connect the blue wire to +5 Volt line of the servo power connector.   

Other than you had a bad experience and saw smoke...   None of these extra measurements are really necessary.   When I've soldered LM7805's there, I've just connected them up and plugged in the servo's.  Everything has always gone as expected.

**Comment by DynamiteHack** [comment]
**@Roxy-3D** - So I replaced the 7805 and most everything is working as expected. It was either a bad 7805 or my connection to the leg was too loose causing a spark? I crimped the connector to the leg and it is working.  I have both the display and BLTouch powered now.

I ran a G28 and XY homed as expected. Z however made the coordinated move to the centerish of the bed, raised about 5mm paused and continued up 13 and stopped. I know it's 13 because that is what ends up displayed in Repetier. The pin never dropped in the Touch. Using Repetier to make manual moves, polarity is correct and the head mover along the Z axis.

I have not touched any settings in the UBL branch you gave me. I will start investigating those now.

Thanks for your patience!!

**Comment by DynamiteHack** [comment]
As a sanity check, I went back to my original firmware package. The Homing worked fine and the BLTouch deployed. I still have the problem with the z-offset not bring reflected in the final position to begin printing the first layer. At least I have demonstrated that the BLTouch remains functional.

I'd love to be on the latest firmware so let me know where I might start looking...I have attached the firmware that I have installed now.

Thanks!
[FT-2020-DISCOUNT-LCD_BLTouchAdded.zip](https://github.com/MarlinFirmware/Marlin/files/772911/FT-2020-DISCOUNT-LCD_BLTouchAdded.zip)

**Comment by Roxy-3D** [comment]
> As a sanity check, I went back to my original firmware package. The Homing worked fine and the BLTouch deployed. I still have the problem with the z-offset not bring reflected in the final position to begin printing the first layer. At least I have demonstrated that the BLTouch remains functional.

I just got home from playing darts and I always win a few beers.   So I'll comment more fully in the morning.   But if you fired up the default UBL Configuration.h file I have it set up to do 'Safe Homing' in the center of the bed of my FT i3-2020.   With a mesh based leveling system, it just makes sense to zero the center of the bed.

> I'd love to be on the latest firmware so let me know where I might start looking...I have attached the firmware that I have installed now.

I'm moving the UBL code base to RC-8's RCBugFix right now.   Different parts of it will get there before other parts.  But this time, it will co-exist with 3-Point,  Grid, Mesh, or Bi-linear.   But if you select UBL, you will have all the features of the other bed leveling styles plus the Mesh editing and validation tools.

**Comment by DynamiteHack** [comment]
Cool!! Darts rock!!

Mesh editing, huh? I've gotta get myself up to speed quick!! It's pretty cool what you guys are coming up with. Don't know how you do it but, keep it up!!

I'll pull the bugfix down in the morning and play around! I just realized that my display only works with the usb connected to my laptop. Not sure if I hurt something or not but, not a huge deal as I'll be moving to octoprint once I get all the issues ironed out.

Thanks again!!

**Comment by thinkyhead** [comment]
Ref: #5705

**Comment by DynamiteHack** [comment]
@thinkyhead Feel free to close this ticket if you'd like. My Arduino stopped accepting uploads during all of this. I have a new one and hope to figure out the other one so I have a spare. 

I am going to stick to my old version of firmware since it works. Went down so many rabbit holes trying to update my firmware I think I'll take a break for now and follow the progress others make.

Thanks for the assistance **@Roxy-3D** and **@Bob-the-Kuhn**! I did get another 5V power source out of this process and for that I'm grateful!!

Cheers!
'hack

**Comment by Bob-the-Kuhn** [comment]
I was able to resurrect one of my controllers by buying a USBtinyISP and then using the Arduino IDE to burn a new bootloader.

**Comment by DynamiteHack** [comment]
Thanks. I have an UNO that I may try to use. I'll look into the USBtinyISP, though.

**Comment by Roxy-3D** [comment]
@DynamiteHack    Really...   For $15 (including shipping) you can get a RAMPS /Mega-2560 on eBay!   If you want an easy way to keep your printer running...  That is the way to go!   At least half of the people here are using that setup.   And it doesn't matter how many options you turn on...  You have 256KB of program space.     Right now, I have that setup on all 4 of my printers.

**Comment by DynamiteHack** [comment]
I happened to have a Saint-Tech controller kit. Just wasn't expecting to use it so early. :)
Is there any benefit to switching to an MKS board?

**Comment by Roxy-3D** [comment]
Well...   The big advantage is how standard it is and how many people have it.   You will be in the main stream if you plug that in.   That is pretty much what I was suggesting you consider doing!

**Comment by DynamiteHack** [comment]
Gotcha!! I'm a little slow on the uptake at times!! 
I'll give one of those a shot!
Thanks!

**Comment by Augermeister** [comment]
I am having the same printer and exact same problem as the OP. I have uploaded RC8 firmware, but not the RCBUGFIX. Would that be the next logical step?

**Comment by Bob-the-Kuhn** [comment]
You can run a BLTouch and an LCD separately but not at the same time?

This thread is running in the direction of a power issue.  The 7805 method has the advantage of being compact & neat.  The alternative is to get a 5V power supply to power the BLTouch and the LCD.  That's a more robust method but requires more cabling.

Independent of the power issue, the latest RCBugFix is highly recommended when using a BLTouch.  It has several BLTouch bug fixes and enhancements.

**Comment by Roxy-3D** [comment]
@Bob-the-Kuhn     This is a little bit off topic...   But THANK YOU for helping with so many BL-Touch issues and other RC-8 RCBugFix topics!   

UPDATE:  @Tannoo   You too!   THANKS!!!

**Comment by ghost** [comment]
No problem. I try to help where I can.

**Comment by Bob-the-Kuhn** [comment]
I'm retired & I like to trouble shoot so it's a natural fit.

**Comment by Augermeister** [comment]
@Bob-the-Kuhn  I worked that out by providing separate 5v power to the BLTouch before I updated to RC8. BLTouch was working before upgrade, now no reaction to pin up or pin down commands; just the self test at power up. I'll try the RCBUGFIX! Thanks.

**Comment by Bob-the-Kuhn** [comment]
Worked before updating to RC8.  Interesting

When you update to RCBugFix please copy your machine specific items over to the new config files.  You can get into trouble if you just drop your old config files into the RCBugFix directory.

If you still have the problem after updating then I'll want to see your config files and any other files that you changed.  Just ZIP them up and drop onto your reply.  I'll also want to know what pins you're using for the BLTouch.

**Comment by Augermeister** [comment]
@Bob-the-Kuhn thanks for your help. I did copy my machine specific items over to RC8, as I saw how different the configuration.h file is now. I will do the same with RCBUGFIX and see how that goes. My pins for BLTOUCH are as suggested by the manufacturer. Z-min is pin 18 on RAMPS 1.3 board and the first servo signal pin. 5v is from my power supply and is verified at 5v with voltmeter.

**Comment by Roxy-3D** [comment]
> 5v is from my power supply and is verified at 5v with voltmeter.

The 5 volt supply should be verified while the servo (or in this case, the BL-Touch) is moving.   That is when the current required is the highest.

**Comment by Augermeister** [comment]
@Roxy-3D I will try to get a reading when BLTouch does it's self-test at initial power-up. Thanks!

**Comment by Roxy-3D** [comment]
Unfortunately...  You might need an oscilloscope to do it.  The problem (especially with RC Servos) is the motor takes a huge amount of current when it is sitting still.   That is because it isn't moving and is not generating any back EMF.   But the same principle applies to the inductive pin on the BL-Touch.    With a normal volt meter, you may not see the voltage drop when it tries to deploy.

**Comment by Augermeister** [comment]
I got my issue figured out. I had been using the old firmware that came with my Folgertech and had RAMPS 1.3 setup in configuration.h 
Although board version isn't labeled, I tried RAMPS 1.4 boards and wala, it worked. Different pin assignments for the servo!
Thanks for your help. Now to research z-offset issues...

**Comment by Bob-the-Kuhn** [comment]
z-offset issues?

Is this with bilinear leveling or with the probe's Z offset?

**Comment by Augermeister** [comment]
I'm having z-offset issues. can anyone direct me to a step by step z-offset setup process?

**Comment by Roxy-3D** [comment]
> I'm having z-offset issues. can anyone direct me to a step by step z-offset setup process?

Personally...   I think it is best to have the Z-Offset set at 0.000mm    And then adjust the Z_PROBE_OFFSET_FROM_EXTRUDER number to be exactly correct.    That is what I do.

Incidentally...    In the UBL code I'm thinking about eliminating the Z-Offset.   It will save some floating point additions.   But in truth, there is no need for it.   The Mesh is already adding and subtracting offsets from the Z position.   It would be better to just adjust the entire mesh up or down instead of having a separate Z-Offset that needs to be added into each position calculation.

**Comment by Augermeister** [comment]
I thought Z-Offset and Z_PROBE_OFFSET_FROM_EXTRUDER were the same thing. I looked and couldn't find Z-Offset in the configuration.h file (RCBUGFIX), so thought it had been removed already.
