### ISSUE TITLE
Where is the Gcode Parser?

### ISSUE THREAD

**Issue by Tahutipai** [MarlinFirmware/Marlin#5825]
If one needs to add their own custom MCodes to Marlin, where is this done?  Aka in which source file is the parser?

Apologies I could only find code for the emergency parser.

(Is there any document that gives an overview of the code structure?)

**Comment by Blue-Marlin** [comment]
The parser is in `Marlin_main.cpp`.

**Comment by Tahutipai** [comment]
Thankyou.  Note: for others searching, look for:  process_next_command()

(am slightly surprised the g/m code parsing is not in its own unit)

**Comment by thinkyhead** [comment]
> am slightly surprised the g/m code parsing is not in its own unit

`Marlin_main.cpp` is basically the GCode parser writ large, along with every GCode command handler.

It will be broken out into its own unit (well, broken up into several .h files but still within a single compilation unit) after the 1.1 release, as we begin to work on 1.2.
