### ISSUE TITLE
Cant save to EEPROM

### ISSUE THREAD

**Issue by pellepant** [MarlinFirmware/Marlin#5827]
When i use M500 in Marlin RC8 to change Z offset the saved offset is reset when i power off and reboot

**Comment by thinkyhead** [comment]
Are you referring to the Z offset set by `M851`? Do you have `EEPROM_SETTINGS` enabled in your `Configuration.h` file?

**Comment by pellepant** [comment]
Yes i am. Yes its enabled. I can use M851 to change offset. But when i tur off the printer the offset is back to zero

**Comment by pellepant** [comment]
Oh no. EEPROM was not enabled. I am so sorry. I was thinking it was enabled on default and it must be enabled of me to use m852 in the first place. Sorry for wasting your time

**Comment by pellepant** [comment]
I tested it now. It works. I miss the the save function in my LCD though.

**Comment by ghost** [comment]
Should listed as 'Store Config' in the 'Control' menu.
