### ISSUE TITLE
[SOLVED] Freeze when homing

### ISSUE THREAD

**Issue by theodroid** [MarlinFirmware/Marlin#5843]
Hi,
I have a problem with the latest RCBugFix. This bug is present for a long time now (alrerady here in the RC7).
After homed the X axis, the printer homes the Y axis, go backwards few mm, and bumps again the Y endstop but slower. At this moment the printer freezes...
I have a SainSmart 2-in-1 board. I send my configuration.h and configuration_adv.h files.
Is it a bug ?

Regards,

[config and config_adv files.zip](https://github.com/MarlinFirmware/Marlin/files/779943/config.and.config_adv.files.zip)

**Comment by ghost** [comment]
The endstop bumps are designed that way. Does Z do anything when you issue a G28?
Check endstop status with M119.

>I have a problem with the latest RCBugFix.

Download the latest RCBugFix again. There have been recent changes. Those config files are at least a week old.

**Comment by theodroid** [comment]
Thanks for your answer.
The RCBugFix I was using was the version of 14th february.
I downloaded the latest RCBugFix again, and uploaded it to my printer, but the problem is always here: the X axis always homes perfectly, but when the Y axis bumps the Y endstop, sometimes Marlin freezes instead of moving the print head backwards to bump the Y endstop a second time.
So I can no longer send commands to the printer since it's freezed... The screen is also freezed.

**Comment by ghost** [comment]
Have you verified that the Y endstop works correctly? Is your 5v still good when the system freezes?

**Comment by theodroid** [comment]
I probably found the problem... The Y endstop works correctly, but my 2 endstops (X and Y) were wired incorrectly to the motherboard. What surprises me is that the controller board never burn out because of a short-circuit... It worked for few months...
And the X axis always homed OK, the problem concerned only the Y axis altough the two endstops were wired the same.
Anyway, I re-wired my endstops and now it works!
So sorry for the inconvenience, it was my fault!

**Comment by ghost** [comment]
Glad you found it. You can now close this issue.
