### ISSUE TITLE
homing question

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#5845]
Is this line (approx 818 in RC7-fa6bf12) suppose to function for any home operation?

#define MANUAL_Z_HOME_POS 10 // Distance between the nozzle to printbed after homing

I enabled it but it does not work as I anticipated. IE, when I home Z, Z=0 not 10.

I want to have Z off the bed when home is complete.

**Comment by bamkrs** [comment]
Your Z will move to 10 if you home the **other** axes. When you home it, then it will stay at home.

**Comment by ghost** [comment]
>Your Z will move to 10 if you home the other axes. When you home it, then it will stay at home.

It does not.
`#define MANUAL_Z_HOME_POS 10 // Distance between the nozzle to printbed after homing` does not do what it says.

**Comment by ghost** [comment]
And these are misleading:
`#define MANUAL_X_HOME_POS 10` and `#define MANUAL_Y_HOME_POS 10`.
 These don't move the X and Y to the positions after homing. These define the X and Y's HOMED position as 10 on the min limits.
When these are defined as 10, a G0 X10 or G0 Y10 will not move the axis. But, a G0 X11 will move 1mm off of the min limit.

Are these for Delta printers only?

**Comment by Roxy-3D** [comment]
> And these are misleading
```cpp
#define MANUAL_X_HOME_POS 10
#define MANUAL_Y_HOME_POS 10
```
Agreed!
Any suggestions for a better name?

**Comment by ghost** [comment]
I can't think of one, but I'm also not sure why one would need those.

I've been trying to get the `MANUAL_Z_HOME_POS` to work.
I got this far, it moves, but I don't like the fact that it's moving the 0 point. Meaning: the LCD still shows Z 0. and a command of G0 Z5 only goes UP another 5mm. So, it has lost the home position after homing.

How do I get this to work correctly?
```
        #if MANUAL_Z_HOME_POS > 0
          current_position[Z_AXIS]
          if (Z_HOME_POS >= current_position[Z_AXIS])
            do_blocking_move_to_z(Z_HOME_POS * 2);
        #endif
```
The `current_position[Z_AXIS]` seems to ALWAYS report back the same as `Z_HOME_POS`.
I am not sure how to fix this.

**Comment by thinkyhead** [comment]
```cpp
#define MANUAL_Z_HOME_POS 10 // Distance between the nozzle to printbed after homing
```
Is true when your Z home position is at the Max end of the carriage, as on Delta. This comment is meant to apply to Delta configurations only, and not to the others, but it was copied into them in error. It will be removed in these other configurations.

**Comment by thinkyhead** [comment]
Note that `Z_HOME_POS` is set to the value of `MANUAL_Z_HOME_POS` when `MANUAL_Z_HOME_POS` is defined. This setting is just a manual override of the otherwise automatic setting of `Z_HOME_POS` to either `Z_MIN_POS` or `Z_MAX_POS`.
```cpp
#ifdef MANUAL_Z_HOME_POS
  #define Z_HOME_POS MANUAL_Z_HOME_POS
#else
  #define Z_HOME_POS (Z_HOME_DIR < 0 ? Z_MIN_POS : Z_MAX_POS)
#endif
```

**Comment by thinkyhead** [comment]
> I want to have Z off the bed when home is complete.
```gcode
G28     ; Obtain known positions
G1 Z10  ; Raise Z up
```

**Comment by ghost** [comment]
>Note that Z_HOME_POS is set to the value of MANUAL_Z_HOME_POS when MANUAL_Z_HOME_POS is defined. This setting is just a manual override of the otherwise automatic setting of Z_HOME_POS to either Z_MIN_POS or Z_MAX_POS.

I saw that, but I could not find any other references to 'Z_HOME_POS' in the program.

When I set it to 10. The LCD still says it's at 0. And Z will not move up until I give it a value higher than 10.0.

What would be the purpose of this?

**Comment by Tannoo** [comment]
So, the discription needs to change in `configuration.h`.

**Comment by thinkyhead** [comment]
> When I set it to 10. The LCD still says it's at 0. And Z will not move up until I give it a value higher than 10.0. What would be the purpose of this?

I assume you mean you are setting `MANUAL_Z_HOME_POS` or `Z_MIN_POS` to 10.0 ?
And, you are saying that when you home with `G28` the LCD says Z 0.0 ?

What is the output of `M503`? Are you using `MESH_BED_LEVELING`?

The homed position _should_ be as you set in your configuration. So, if you set your `Z_MIN_POS` to 10.0 and left your `MANUAL_Z_HOME_POS` unset, then `Z_HOME_POS` should be set to `Z_MIN_POS` (10.0). Then, when you home with `G28` your current Z position should be 10.0.

That is the intended behavior, but it's possible for other settings to change Z. For example, a `G92 Z0` would set the current Z to 0. A command like `M206 Z-10.0` could also have this effect, and that is saved to EEPROM.

To rule out old settings, you can try `M502` followed by `M500` and restarting the printer.
