### ISSUE TITLE
CUSTOM_MACHINE_NAME overflows to top of LCD (minor issue)

### ISSUE THREAD

**Issue by pearson** [MarlinFirmware/Marlin#5847]
This is a minor issue.

If the CUSTOM_MACHINE_NAME is too long, the word "ready" overflows to the top of the LCD panel, obscuring the extruder temperature. For example, the first attached image shows:
`#define CUSTOM_MACHINE_NAME "RCBugfix 16 Feb 2017"`

![lcd_test_1](https://cloud.githubusercontent.com/assets/656880/23044614/d3b9cb06-f455-11e6-824e-44d794c4fee9.png)

However, if the CUSTOM_MACHINE_NAME is absurdly long, it starts to corrupt the entire LCD panel. For example, the second attached image shows:
`#define CUSTOM_MACHINE_NAME "RCBugfix 16 Feb 2017 RCBugfix 16 Feb 2017 RCBugfix 16 Feb 2017"`

![lcd_test_2](https://cloud.githubusercontent.com/assets/656880/23044615/d6d1dc20-f455-11e6-9947-c0ea5b0f78a7.png)

This is on a 20x4 LCD panel using:
`#define REPRAP_DISCOUNT_SMART_CONTROLLER`

Perhaps a sanity check for the CUSTOM_MACHINE_NAME length might be a good fix?

**Comment by Roxy-3D** [comment]
> Perhaps a sanity check for the CUSTOM_MACHINE_NAME length might be a good fix?

Yes!  But I think we should also make the code more robust so it doesn't do bad things like that.   These type of problems are at the root of many memory corruption bugs.

**Comment by ghost** [comment]
Maybe not checking but, how about truncating at 13 characters?

**Comment by Blue-Marlin** [comment]
Please be aware of:
* we have multiple languages. The length of the "ready" equivalent may differ.
* we use utf8 here. The space used on screen is not srtlen().
* at different types of displays we have different width.

**Comment by ghost** [comment]
Yeah...so truncate accordingly.

**Comment by thinkyhead** [comment]
If we make our UTF-8-savvy string functions `constexpr` then the pre-compiler will be able to use them in `static_assert`.

**Comment by thinkyhead** [comment]
A man goes to a doctor.
Man: "Doctor, it hurts when I do this."
Doctor: "Then don't do that. That'll be $75!"
