### ISSUE TITLE
Can't change the bed default settings pronterface

### ISSUE THREAD

**Issue by mmaisonn99** [MarlinFirmware/Marlin#5852]
Hello,
My settings don't allow me to change the default bed settings, I don't have the possibility to write my printer's bed sizes.
can someone help me ? I am a beginner with pronterface
Thank you
![image](https://cloud.githubusercontent.com/assets/25855214/23087497/0cb5a34c-f575-11e6-9a64-793f6463fa19.png)

**Comment by Roxy-3D** [comment]
I ran into this on a machine that was running Windows-10.    I was trying to setup my gMax 1.5+ which has a bed slightly smaller than a tennis court.  I really needed to change the default bed size.    I never got the menu to work.  But you can pull C:\Users\your-user-name\printrunconf.ini into your favorite text editor and zap what ever values you need into the file.   

I think you (and I) are seeing a problem with Python not doing edit windows correctly on Windows 10.

**Comment by mmaisonn99** [comment]
Thank you ! I actually have a new issue now and I don't know if it's related, no my motors won't move and just make noise

**Comment by Roxy-3D** [comment]
I am not aware of anything that would cause that in PronterFace.   But are you doing something to get the feed rate too high for your motors?   What else have you changed on your printer recently?

**Comment by jfpion** [comment]
did you try to run pronterface as admin ? sometimes it solve problem

**Comment by PJMoore** [comment]
> Hello,
> My settings don't allow me to change the default bed settings, I don't have the possibility to write my printer's bed sizes.
> can someone help me ? I am a beginner with pronterface
> Thank you
> ![image](https://cloud.githubusercontent.com/assets/25855214/23087497/0cb5a34c-f575-11e6-9a64-793f6463fa19.png)

Find printrunconf.ini, and edit the bed size with a text editor.  It worked fine for me on Win 10.
