### ISSUE TITLE
2nd extruder "exit status 1 'i' was not declared in this scope"

### ISSUE THREAD

**Issue by Sungod3000** [MarlinFirmware/Marlin#5858]
Hi,

im putting a 2nd extruder in a single nozzle config on my delta. and I changed number of extruders, define single nozzle, distinct e factors and added the number of steps for the 2nd extruder.

now im getting in ultralcd.ccp:
```
exit status 1
'i' was not declared in this scope 

  void _planner_refresh_positioning() { planner.refresh_positioning(); }
  #if ENABLED(DISTINCT_E_FACTORS)
    void _planner_refresh_e_positioning(const uint8_t e) {
      if (e == active_extruder)
        _planner_refresh_positioning();
      else
        planner.steps_to_mm[i] = 1.0 / planner.axis_steps_per_mm[i];
    }
```
It works when I disable distinct e factors.
Its probably just another setting that I overlooked but I cant find a documentation for the settings that includes the recent marlin versions. What am I missing?

Cheers

**Comment by thinkyhead** [comment]
This appears to be fixed in the latest code. — Test the `RCBugFix` branch.
