### ISSUE TITLE
langage_fr.h : special characteres don't work on 128x64 full screen

### ISSUE THREAD

**Issue by spilz87** [MarlinFirmware/Marlin#5884]
The last `language_fr.h` update uses special characters which are not display properly : é è ê ...

**Comment by spilz87** [comment]
Solved by adding 
#define MAPPER_C2C3

**Comment by thinkyhead** [comment]
Thanks! https://github.com/MarlinFirmware/Marlin/commit/f17b81b7650a8e7f4f906b45a33d203c0b8828b0
