### ISSUE TITLE
Issue Hotbed thermal runaway [HW issue]

### ISSUE THREAD

**Issue by TAz00** [MarlinFirmware/Marlin#5886]
Hi,

The power to my printbed gets locked to ON after the initial brimming layer. 
And then proceeds to get as hot as possible. It seems the issue does not start until gcode brimming proces has finished.

![bedtempclimb](https://cloud.githubusercontent.com/assets/6599276/23178793/ffd21e36-f86b-11e6-8e34-0961139c3a41.png)

Its a 300x200mm plate so I havnt seen it go over 80c, with the 12v I'm feeding it, and the test print ends before it goes any further.

If I set a bed temp before printing, it will hold that temp just fine. 
![bedtempholdingfine](https://cloud.githubusercontent.com/assets/6599276/23178803/082c5de4-f86c-11e6-8a6b-1b9f0864217d.png)

Once the print has started, it makes no difference if I turn the bed temp down with the lcd menu, it will continue to climb as best as possible.

Ive also found that disabling the bed intially, and then turning it on manually midway through the print, leads to the same constantly on runaway.

If tried bed level switching and switching to PID controlled (autotuned). 

Slicer: Cura 15.04.6

Tested Firmwares
Marlin-1.0.2-2
Marlin-1.1.0-RC7
Marlin-1.1.0-RC8    - Attached Configuration
Marlin-RCBugFix

Board: RAMPS 1.4

[20mmX20mmX20mm-hollow.gcode.zip](https://github.com/MarlinFirmware/Marlin/files/791107/20mmX20mmX20mm-hollow.gcode.zip)
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/791108/Configuration.zip)

Now its likely the configuration is off, since this is my first build and it has almost gone smoothly, any help you can provide is greatly appreciated.

**Comment by ghost** [comment]
That is printing really fast. Too much filament in the corners and not enough on the side. So, it not coming out very good.

Also, are you sure that your bed thermistor is type 11?

**Comment by ghost** [comment]
Mid-way through the print, I set my bed temp (from LCD) to 30, and my bed temp is dropping.

**Comment by Bob-the-Kuhn** [comment]
I didn't see any issues in your config files or in the gcode program.

The slicer issues a M190 S50 at the beginning and M140 S0 at the end and nothing else that would affect the bed temperature.

What happens when you manually issue a M190 S50?  That should override any Pronterface settings and keep the bed near 50C.  After the bed has been at 50C for 5 minutes try turning on the fan and the extruder heater and see if the bed stays under control.

Do you have a way to independently verify the temperature of the bed?

Is the following how you have the heaters and the fan connected?
```
PIN:  8   Port: H5        HEATER_BED_PIN              Output = 0
.                         RAMPS_D8_PIN                Output = 0
PIN:  9   Port: H6        FAN_PIN                     Output = 0 
.                         RAMPS_D9_PIN                Output = 0
PIN: 10   Port: B4        HEATER_0_PIN                Output = 0 
.                         RAMPS_D10_PIN               Output = 0
```

**Comment by TAz00** [comment]
Thanks for your replies.

Im not sure the bed thermistor is type 11, but this is all the info from the ebay seller 'NTC 3950 Thermistor 100K 1%'

Here I've set the bed temp, and then turned on the extruder. I have the extruder fan connected to the 12v rail, so its always on. But other than that, yes, Port 8 is extruder heater and 10 is the bed.
![extruderclimbbedsteady-rc1 7](https://cloud.githubusercontent.com/assets/6599276/23201709/21a516e8-f8db-11e6-8036-f2b8ddef5683.png)

To verify the temperatures, when the bed and extruder have been off for a while, they show the same ambient temperature. I havn't actually put a thermometer to the bet, but 30c and 70c and feels right enough. 

150 m/s with a bowden extruder maybe a bit too fast, but you cant argue with the results :P 
![2017-02-22 08 42 19](https://cloud.githubusercontent.com/assets/6599276/23201950/2811d006-f8dc-11e6-89fa-ceb7c8190d42.png)

**Comment by ghost** [comment]
Printed ok with mine. Just looked horrible printing. Like the corners were still too soft and too much material.

**Comment by TAz00** [comment]
Thanks for testing :)

Here's a better test where I've set the bed to 50 for 5 mins, then turned on the extruder, bed temperature is holding steady. 
![hotendclimbheatup-rcbugfix](https://cloud.githubusercontent.com/assets/6599276/23203322/54c9ca6c-f8e2-11e6-9267-5ac945bd44d6.png)
![hotendclimbheatup2-rcbugfix](https://cloud.githubusercontent.com/assets/6599276/23203326/57aef090-f8e2-11e6-94fa-d96c782dde69.png)
![hotendholding-rcbugfix](https://cloud.githubusercontent.com/assets/6599276/23203331/5baa17ba-f8e2-11e6-9f09-17cf95cf8671.png)

**Comment by ghost** [comment]
Can you try a type 1 thermistor? If so and you have PID enabled... tune it again.

 I'm not sure if that's the issue being that you can hold temp at idle. AND that it works fine if you preheat before printing.

I'm at a loss otherwise.

**Comment by TAz00** [comment]
Scratch your heads no more

After removing M106 from both LAYER1 and LAYER2 in the gcode, 
M106 S127
M106 S255

My bed no longer gets locked to fully on, but holds temp during print.

M106 controls fan speed, and 255 sets max power, so I suspect there's a short (since you guys checked the config) between the pins for mosfet 9 & 10 

I will check that and report back once the print finishes.
But so far everything's great.

**Comment by ghost** [comment]
Well, that's bittersweet news.

You can also test this without printing. Send an M106 S127 and see if your bed heats up. If so, look for the short or replace the board.

Could this also be an error in the pins file? Where the fan and the bed are set to the same pins?

Have you ever noticed if the fan comes on with the bed when you're not printing?

**Comment by TAz00** [comment]
Turns out, the heatsinks for 9&10 were touching. Apparently they're live for whatever reason :D 

Pried them apart, and now I'm printing.

**Comment by ghost** [comment]
Glad you got it.
