### ISSUE TITLE
Cannot create a folder called SD in SD card

### ISSUE THREAD

**Issue by valerionew** [MarlinFirmware/Marlin#5896]
If you create a folder named SD in the SD card the printer won't open it. It will take you to the root folder of the SD card. I'm using the Smart Controller from reprapdiscount.com.

**Comment by ghost** [comment]
Don't create a folder called `SD`. :)

**Comment by valerionew** [comment]
I won't. I was just reporting an issue 😄

**Comment by thinkyhead** [comment]
It seems to be an issue with the SD file library we use. But I can't find any obvious cause. It may also just be a quirk of the SD filesystem. We may upgrade to a newer version of the library in the future, and that may address this feature.
