### ISSUE TITLE
Issues with knob on LCD2004

### ISSUE THREAD

**Issue by Jolly2015** [MarlinFirmware/Marlin#5905]
Hello, I defined REPRAP_DISCOUNT_SMART_CONTROLLER  and use on my delta(motherboard=33,RC8 version),sometimes like I click "stop print",but it run to "pause print" and let machine pause(I am sure I didn't turn the knob and appeared with high probability and not only occuring on "stop print"), sometimes I click "auto home" and it return to main interface(appeared with high probability).I don't know where I can fix it  in marlin,anybody can help me?Thx

**Comment by ghost** [comment]
If I understand your issue correctly, in `configuration.h`:
```
// This option overrides the default number of encoder pulses needed to
// produce one step. Should be increased for high-resolution encoders.
//
//#define ENCODER_PULSES_PER_STEP 1

//
// Use this option to override the number of step signals required to
// move between next/prev menu items.
//
//#define ENCODER_STEPS_PER_MENU_ITEM 5
```
Enabled these and adjust as needed.

**Comment by Jolly2015** [comment]
Wow, thx for your fast answer,it fixed. Thank you .

**Comment by ghost** [comment]
Good!
