### ISSUE TITLE
can i g29 without first g28?

### ISSUE THREAD

**Issue by lacosa83** [MarlinFirmware/Marlin#5909]
Hello, i don't have endstops at all on my MPCNC but i should like do g29. Can I? Regards :)

Firmware RC7..

**Comment by ghost** [comment]
Not successfully. It will fail and run without stopping.. It will initiate a G28 on it's own, if it hasn't been homed.

Do not do those until you have working endstops installed.

**Comment by lacosa83** [comment]
thanks,  but i will never mount endstops on the machine :)
My question is, there is a method for bypassing the g28 launching g29? Usually i put on 0ish in manual without any problem...

**Comment by ghost** [comment]
I don't think so. The machine needs to know where it is. Otherwise, it can run past the physical limits and mess things up.

**Comment by ghost** [comment]
Would you run across the street with a blindfold? Without the endstops and homing, the machine is running blind.

**Comment by lacosa83** [comment]
no (obv), but i see my similar problem solved in an other post ( https://github.com/MarlinFirmware/Marlin/issues/4831 ), but i don't understand where add the cmd line LOOP_XYZ(i) axis_known_position[i] = axis_homed[i] = true; linked by thinkyhead :)

**Comment by ghost** [comment]
AHH..
Then, this is where the manual positions come into play. Would it help to set these in `configuration.h`?
```
// Manually set the home position. Leave these undefined for automatic settings.
// For DELTA this is the top-center of the Cartesian print volume.
//#define MANUAL_X_HOME_POS 0
//#define MANUAL_Y_HOME_POS 0
//#define MANUAL_Z_HOME_POS 0
```

**Comment by lacosa83** [comment]
i don't know, now i will try to upload this in firmware, thanks :)

**Comment by ghost** [comment]
Thinkyhead was saying to add a command to the `setup()` function in `marlin_main.cpp`. It is near the end of the file.

`LOOP_XYZ(i) axis_known_position[i] = axis_homed[i] = true;`

This should make G29 work because that line says that the machine is already homed.

**Comment by ghost** [comment]
The manual positions may or may not do much for you. I don't really know. I am not taking off my cool endstops to find out for sure. lol

**Comment by lacosa83** [comment]
i only find void setup ()

![forum](https://cloud.githubusercontent.com/assets/26034382/23337301/2ec3e41a-fbe9-11e6-9008-aaf8b80cee0a.png)

**Comment by ghost** [comment]
I would put it at the end of that function just to make sure all else is loaded first.

**Comment by lacosa83** [comment]
Okay thanks :)

**Comment by ghost** [comment]
I would think that the manual position definitions would eliminate the need for a G92 before printing. (In your case)

**Comment by lacosa83** [comment]
bump doesn't work

**Comment by ghost** [comment]
Sorry, but I am at a loss on that then.

**Comment by thinkyhead** [comment]
> I would put it at the end of that function

I use this for one of my client projects:
```cpp
  /**
   * G8: Simulate homing
   */
  inline void gcode_G8() {
    LOOP_XYZ(i) {
      current_position[i] = LOGICAL_POSITION(base_home_pos[i], i);
      axis_homed[i] = axis_known_position[i] = true;
    }
    SYNC_PLAN_POSITION_KINEMATIC();
    SERIAL_ECHO_START;
    SERIAL_ECHOLNPGM("At Home " STRINGIFY(X_HOME_POS) " " STRINGIFY(Y_HOME_POS) " " STRINGIFY(Z_HOME_POS));
    report_current_position();
  }
```

**Comment by lacosa83** [comment]
Thanks, i will try it tomorrow
