### ISSUE TITLE
g29 without endstop???

### ISSUE THREAD

**Issue by lacosa83** [MarlinFirmware/Marlin#5915]
As title...please help :)

**Comment by james94jeans2** [comment]
As far as I know you would need to change some code to do this. I can maybe give you a hint on what to do if I find the time later.

**Comment by lacosa83** [comment]
thanks dude :)

**Comment by Bob-the-Kuhn** [comment]
Try the solution in issue #5909.

**Comment by lacosa83** [comment]
it was the mine and didn't work :D

**Comment by james94jeans2** [comment]
I can not test this as my printer is currently printing, but there might be a very simple solution:

In line 3785 of file Marlin_main.cpp:

remove "G28\n"

I am quite new to github and don't know how I could show it in a stylish way, but the describtion should be enough.

change from: 
3785 enqueue_and_echo_commands_P(PSTR("G28\nG29 S2"));
to:
3785 enqueue_and_echo_commands_P(PSTR("G29 S2"));

Please report back on any issues.

**Comment by lacosa83** [comment]
That's work, but not from lcd. I must do from repetier M420 S1 then g92 x0y0z0 and then i start it :)
If i do it from LCD will start g28 (auto home)

**Comment by james94jeans2** [comment]
You can remove the homing from lcd by editing ultralcd.cpp

as suggested in #5909 set the homed values to true:
1285 axis_homed[X_AXIS] = axis_homed[Y_AXIS] = axis_homed[Z_AXIS] = true;
and remove the line that calls g28:
enqueue_and_echo_commands_P(PSTR("G28"));

However it will still be doing a homing at the end of leveling

**Comment by lacosa83** [comment]
umh, can i save in eeprom the result first of homing?

**Comment by james94jeans2** [comment]
I don't think thats possible, but I am not sure where it starts the homing after the leveling, maybe try the above mentioned edit and tell me if it starts homing after the leveling

**Comment by lacosa83** [comment]
all work well but at the end of the cycle will do g28.. :(

**Comment by lacosa83** [comment]
seem work: first i launch from lcd the mesh, then from repetier host i can see the grid using g29 s0
After i had the grid i mind it's quite simple add to marlin

**Comment by james94jeans2** [comment]
You could try deleting line 
1196             enqueue_and_echo_commands_P(PSTR("G28"));

in ultralcd to stop the g28 from happening, but I don't know if the leveling will work as intended when this is removed.

**Comment by lacosa83** [comment]
now i have the grid on eeprom but don't seem work at all: i tried print something but nothing.....any idea?
First of start the print a launch G92 X0 Y0 Z0
wITH M501
```
15:04:29.711 : N19 M501*31
15:04:29.711 : echo:V24 stored settings retrieved (558 bytes)
15:04:29.711 : echo:Steps per unit:
15:04:29.742 : echo:  M92 X160.00 Y160.00 Z5120.00 E160.00
15:04:29.742 : echo:Maximum feedrates (mm/s):
15:04:29.742 : echo:  M203 X190.00 Y190.00 Z8.50 E25.00
15:04:29.742 : echo:Maximum Acceleration (mm/s2):
15:04:29.742 : echo:  M201 X500 Y500 Z35 E10000
15:04:29.742 : echo:Accelerations: P=printing, R=retract and T=travel
15:04:29.742 : echo:  M204 P400.00 R3000.00 T500.00
15:04:29.742 : echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
15:04:29.742 : echo:  M205 S0.00 T0.00 B20000 X4.00 Z0.40 E5.00
15:04:29.742 : echo:Home offset (mm)
15:04:29.742 : echo:  M206 X0.00 Y0.00 Z0.00
15:04:29.742 : Mesh bed leveling:
15:04:29.742 : echo:  M420 S1 X7 Y7
15:04:29.742 : echo:  G29 S3 X1 Y1 Z3.97500
15:04:29.742 : echo:  G29 S3 X2 Y1 Z4.12500
15:04:29.742 : echo:  G29 S3 X3 Y1 Z4.15000
15:04:29.742 : echo:  G29 S3 X4 Y1 Z4.00000
15:04:29.742 : echo:  G29 S3 X5 Y1 Z4.10000
15:04:29.742 : echo:  G29 S3 X6 Y1 Z3.97500
15:04:29.758 : echo:  G29 S3 X7 Y1 Z4.00000
15:04:29.758 : echo:  G29 S3 X1 Y2 Z3.67500
15:04:29.758 : echo:  G29 S3 X2 Y2 Z3.90000
15:04:29.758 : echo:  G29 S3 X3 Y2 Z4.00000
15:04:29.758 : echo:  G29 S3 X4 Y2 Z3.95000
15:04:29.758 : echo:  G29 S3 X5 Y2 Z4.05000
15:04:29.758 : echo:  G29 S3 X6 Y2 Z3.92500
15:04:29.758 : echo:  G29 S3 X7 Y2 Z4.00000
15:04:29.758 : echo:  G29 S3 X1 Y3 Z3.75000
15:04:29.758 : echo:  G29 S3 X2 Y3 Z4.00000
15:04:29.758 : echo:  G29 S3 X3 Y3 Z4.12500
15:04:29.758 : echo:  G29 S3 X4 Y3 Z4.15000
15:04:29.773 : echo:  G29 S3 X5 Y3 Z4.25000
15:04:29.773 : echo:  G29 S3 X6 Y3 Z4.07500
15:04:29.773 : echo:  G29 S3 X7 Y3 Z4.17500
15:04:29.773 : echo:  G29 S3 X1 Y4 Z3.60000
15:04:29.773 : echo:  G29 S3 X2 Y4 Z3.90000
15:04:29.773 : echo:  G29 S3 X3 Y4 Z4.05000
15:04:29.773 : echo:  G29 S3 X4 Y4 Z4.10000
15:04:29.773 : echo:  G29 S3 X5 Y4 Z4.15000
15:04:29.773 : echo:  G29 S3 X6 Y4 Z4.05000
15:04:29.773 : echo:  G29 S3 X7 Y4 Z4.02500
15:04:29.773 : echo:  G29 S3 X1 Y5 Z3.57500
15:04:29.773 : echo:  G29 S3 X2 Y5 Z3.72500
15:04:29.773 : echo:  G29 S3 X3 Y5 Z3.87500
15:04:29.789 : echo:  G29 S3 X4 Y5 Z3.92500
15:04:29.789 : echo:  G29 S3 X5 Y5 Z4.00000
15:04:29.789 : echo:  G29 S3 X6 Y5 Z3.87500
15:04:29.789 : echo:  G29 S3 X7 Y5 Z3.90000
15:04:29.789 : echo:  G29 S3 X1 Y6 Z3.65000
15:04:29.789 : echo:  G29 S3 X2 Y6 Z3.70000
15:04:29.789 : echo:  G29 S3 X3 Y6 Z3.67500
15:04:29.789 : echo:  G29 S3 X4 Y6 Z3.72500
15:04:29.789 : echo:  G29 S3 X5 Y6 Z3.85000
15:04:29.789 : echo:  G29 S3 X6 Y6 Z3.75000
15:04:29.789 : echo:  G29 S3 X7 Y6 Z3.82500
15:04:29.789 : echo:  G29 S3 X1 Y7 Z3.25000
15:04:29.805 : echo:  G29 S3 X2 Y7 Z3.32500
15:04:29.805 : echo:  G29 S3 X3 Y7 Z3.22500
15:04:29.805 : echo:  G29 S3 X4 Y7 Z3.25000
15:04:29.805 : echo:  G29 S3 X5 Y7 Z3.32500
15:04:29.805 : echo:  G29 S3 X6 Y7 Z3.27500
15:04:29.805 : echo:  G29 S3 X7 Y7 Z3.50000
15:04:29.805 : echo:Material heatup parameters:
15:04:29.805 : echo:  M145 S0 H190 B50 F0
15:04:29.805 : echo:  M145 S1 H240 B110 F0
15:04:29.805 : echo:PID settings:
15:04:29.805 : echo:  M301 P17.98 I0.98 D83.62
15:04:29.805 : echo:Filament settings: Disabled
15:04:29.805 : echo:  M200 D3.00
15:04:29.820 : echo:  M200 D0
```

**Comment by Bob-the-Kuhn** [comment]
Looks like you're running RC7 and mesh leveling.

I don't think you need to do the M501.  That's done automatically when the controller powers up or goes through reset.

Please give us the steps you've taken to verify that the mesh leveling is or is not working.

We'd also like to see the steps you take to get ready for a print and the start of the g-code file through the first print command.

**Comment by lacosa83** [comment]
Ok so...
As Title i don't have endstop (it's a MPCNC). I removed from Marlin_main.cpp

enqueue_and_echo_commands_P(PSTR("G28\nG29 S2"));
and i replaced with 
 enqueue_and_echo_commands_P(PSTR("G29 S2"));

Then I removed from Ultralcd 
 enqueue_and_echo_commands_P(PSTR("G28"));

After reflashed arduino i had start with G92 X0Y0Z0 and then i started the cycle of G29 from lcd
after i tracked all the point i did M500 for store in eeprom the data then i power off arduino.

Whn i power on i did G92 X0Y0Z0, then i start a print (on a scrap of MDF), but arduino seem as don't load the grid....

**Comment by lacosa83** [comment]
```gcode
;Project GRIGLIA3
;Created by Estlcam version 10 build 10,012
;Machining time about 02:02:00 hours

G90
M03 S24000
G00 Z5.0000


;No. 1: Engraving 4
G00 X0.0000 Y0.0000
G00 Z0.5000
G01 Z-1.0000 F1200 S24000
G01 X5.0000
G01 Y600.0000
G01 X10.0000
G01 Y0.0000
G01 X15.0000
G01 Y600.0000
G01 X20.0000
G01 Y0.0000
G01 X25.0000
G01 Y600.0000
G01 X30.0000
G01 Y0.0000
G01 X35.0000
```

**Comment by lacosa83** [comment]
Could help set 
```cpp
#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 0
#define X_MAX_POS 600
#define Y_MAX_POS 600
#define Z_MAX_POS 100
```
then homing when i put all axis at the end of the rails?

**Comment by Bob-the-Kuhn** [comment]
Please do the following:
- M420 V - should print out the leveling matrix, if not then do M420 S1
- move your head to the (0,0,0) location
- G92 X0 Y0 Z0 ; sets the current location as (0,0,0)
- Go to 5 locations within the mesh area and measure how far off the bed the head is.  That'll tell you if mesh leveling is doing a decent job.

When you set (0,0,0), is the nozzle just touching the bed or is it some height above the bed?

Are you doing 3D printing or some type of CNC work?  The **M03 S24000** command is only used in CNC work.

**Comment by lacosa83** [comment]
When you set (0,0,0), is the nozzle just touching the bed or is it some height above the bed?

The end mill touch bed

Are you doing 3D printing or some type of CNC work? The M03 S24000 command is only used in CNC work.

It's the MPCNC (cnc )

Seem the grid do not start: 
```
00:14:18.236 : N26 M420 V*103
00:14:18.241 : ok
00:14:30.188 : N31 M420 S1*85
00:14:30.194 : ok
but it is in eeprom with M501
00:18:10.918 : Mesh bed leveling:
00:18:10.918 : echo:  M420 S1 X3 Y3
00:18:10.922 : echo:  G29 S3 X1 Y1 Z3.95000
00:18:10.922 : echo:  G29 S3 X2 Y1 Z3.92500
00:18:10.922 : echo:  G29 S3 X3 Y1 Z3.92500
00:18:10.926 : echo:  G29 S3 X1 Y2 Z3.60000
00:18:10.926 : echo:  G29 S3 X2 Y2 Z3.92500
00:18:10.926 : echo:  G29 S3 X3 Y2 Z3.87500
00:18:10.930 : echo:  G29 S3 X1 Y3 Z3.20000
00:18:10.930 : echo:  G29 S3 X2 Y3 Z3.22500
00:18:10.930 : echo:  G29 S3 X3 Y3 Z3.40000
```
With G29 S4
```
00:28:41.622 : N107 G29 V4*86
00:28:41.625 : State: 1
00:28:41.625 : Num X,Y: 3,3
00:28:41.630 : Z search height: 4
00:28:41.630 : Z offset: 0.00000
00:28:41.630 : Measured points:
00:28:41.630 : 3.95000  3.92500  3.92500
00:28:41.634 : 3.60000  3.92500  3.87500
00:28:41.634 : 3.20000  3.22500  3.40000
00:28:41.637 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X: 0 Y:0 Z:0
00:28:41.637 : ok
```

**Comment by Bob-the-Kuhn** [comment]
What software are you running?  When I look at the RC7 code I see a slightly different layout for the mesh report than what you posted.

Does the g-code command **M03 S24000** do something?  That command isn't yet supported in the main Marlin code base.  If yes then please include the URL where you got your code from.

I went over to the Vicious Circle site and downloaded the MPCNC software.  It doesn't match the mesh report.

----

To me the results of your **G29 V4** command indicate that the mesh leveling is on.  Have you done any measurements to prove/disprove that mesh leveling is working?

**Comment by lacosa83** [comment]
i download the code from vicious1.com: i onlly modify what i said in the post and movment data (i have t20pulley and not 16 tooth). The mesh isn't working:i tried to manual g0 Xx Yx Zx the same point i misured with the mesh and i have the same z
IMO it's because i can't do g28....

**Comment by Bob-the-Kuhn** [comment]
We really need to get you using the latest software.  Please download [RCBugFix](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix).

Don't overwrite your current software.  You'll need some files from it.

You'll need to port your code modifications over, modify the Configuration.h & Configuration_adv.h files and maybe copy another file over.

If you zip Configuration.h and Configuration_adv.h and attach then I'll update them.

----

EDIT

You'll also need to re-do your mesh.  It won't be copied over.

**Comment by lacosa83** [comment]
http://www.filedropper.com/rc7mpcnclcd9916

No problem, i like work with my machine :)

**Comment by Bob-the-Kuhn** [comment]
Attached are the updated config files.

You'll need to copy your **_Bootscreen.h** file over to the new directory.

You may also need to copy **pins_RAMPS.h** over.  Sometimes there's custom settings in there.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/812607/Configuration.zip)

**Comment by lacosa83** [comment]
wow bob,  I don't know how to thank you for being so quick in helping me.

**Comment by lacosa83** [comment]
can i slow down the movment speed when probing?
Edit: find it:// X and Y axis travel speed (mm/m) between probes
#define XY_PROBE_SPEED 8000

**Comment by Bob-the-Kuhn** [comment]
You're right - that's moving fast.

There's settings for the speeds for the various operations.  The trick is finding them. 

Feel free to customize these for your machine.  That's the purpose of Configuration.h and Configuration_adv.h.

----

You can limit the max speed for the system by changing this setting:
`#define DEFAULT_MAX_FEEDRATE          {190, 190, 8.5, 25}    // (mm/sec) MPCNC`

These are the settings for the homing and probing speeds.
```
// Homing speeds (mm/m)
#define HOMING_FEEDRATE_XY (50*60)
#define HOMING_FEEDRATE_Z  (4*60)
// X and Y axis travel speed (mm/m) between probes
#define XY_PROBE_SPEED 8000
// Speed for the first approach when double-probing (with PROBE_DOUBLE_TOUCH)
#define Z_PROBE_SPEED_FAST HOMING_FEEDRATE_Z
// Speed for the "accurate" probe of each point
#define Z_PROBE_SPEED_SLOW (Z_PROBE_SPEED_FAST / 2)
```

**Comment by lacosa83** [comment]
Now the probe work with an error of +-0.1mm , thanks alot dude :)

**Comment by Bob-the-Kuhn** [comment]
+ - 0.1mm is OK for CNC work.

Is that figure from the M48 command?    You'll need to enable **Z_MIN_PROBE_REPEATABILITY_TEST** in order to use it.

At 5120 steps per mm on your Z axis I'd expect better accuracy. 

Wht kind of a probe are you using?

**Comment by lacosa83** [comment]
A pieve of paper ;D


Il 02/mar/2017 23:32, "Bob-the-Kuhn" <notifications@github.com> ha scritto:

**Comment by Bob-the-Kuhn** [comment]
Tried & true and perfectly acceptable for CNC work  :-)

**Comment by Allted** [comment]
Wow, nice work!

Sorry we aren't on the latest RCBugFix yet, the updates are happening so fast I decided to wait for the next RC. I hope we can implement this on the next MPCNC firmware update, or at least put up a how to guide.

Very impressed.

**Comment by Bob-the-Kuhn** [comment]
Once you have a working system then stick with it.

Usually people only switch if there is a bug fix they need or a new feature they want.
