### ISSUE TITLE
DISABLE_INACTIVE_X/Y/Z/E

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#5917]
Does this function differentiate between the end of a print and a pause, filament change, etc.

also - if I have a dual extruder with hotend 1 @ offset = -30 X and the build area is 305X should this
#define X_MAX_POS 335 
be 335 or 305. Carriage physically can move 335mm.

 #define SD_FINISHED_RELEASECOMMAND "M84 X Y Z E" // You might want to keep the z enabled so your bed stays in place.
Do you do this by deleting the Z?

**Comment by Tannoo** [comment]
Yes

**Comment by ghost** [comment]
`M84` <-- disables all steppers
`M84 X` <-- disables only the X stepper(s).
`M84 X Y E` <-- disables all but the Z stepper(s).

**Comment by ruggb** [comment]
@Tannoo thanks, you might want to put that in the comments to make it clear.

**Comment by thinkyhead** [comment]
`X_MAX_POS` defines the physical limit of the X axis relative to `X_MIN_POS`.
