### ISSUE TITLE
CUSTOM_BOOTSCREEN_TIMEOUT

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#5922]
CUSTOM_BOOTSCREEN_TIMEOUT appears in ultralcd_impl_DOGM.h on line 278, but I can't find it defined anyplace.
Can you tell me where it is defined?
Is the SAFE_DELAY in ultralcd_impl_HD44780.h related to this and should it be set to this variable instead of a constant 2000?

**Comment by Blue-Marlin** [comment]
https://github.com/MarlinFirmware/Marlin/search?utf8=%E2%9C%93&q=CUSTOM_BOOTSCREEN_TIMEOUT

**Comment by ruggb** [comment]
Well now, there ya go. Thank you -- however it doesn't do ME, or a lot of other ppl, any good as I do not use ANY of those preconfigured builds. Can you say **BUG**? This needs to be defined someplace in the general config files - I have placed it and would suggest configuration_adv.h as it is not critical to operation.

**Comment by Blue-Marlin** [comment]
If you don't have a custom bootscreen you don't need `CUSTOM_BOOTSCREEN_TIMEOUT`.
So `_Bootscreen.h` is the exact right place for the definition.

**Comment by ruggb** [comment]
OH, it is only for a REAL custom bootscreen. not a custom timeout for a bootscreen. I got it confused with MACHINE_NAME and CUSTOM_MACHINE_NAME. I still don't know why there are two defined. The same for the MACHINE_UUI
