### ISSUE TITLE
Z_HOMING_HEIGHT

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#5924]
What is this suppose to do in RC8?

**Comment by Bob-the-Kuhn** [comment]
If Z homing is in the - direction, that's the minimum safe height for the Z axis when homing X & Y.

G28 will first raise the Z axis by that height, then do the X & Y homing and then do the Z homing.

If Z homing is in the + direction then it is ignored as Z homing is done first.

When probing (G29, G30, M48) the Z height between probes is set by Z_CLEARANCE_BETWEEN_PROBES

**Comment by thinkyhead** [comment]
The intention is to prevent scraping the bed or hitting the bed clips if `G28` is initiated with Z close to the bed.
