### ISSUE TITLE
G29 homes in mid-air

### ISSUE THREAD

**Issue by gunnir** [MarlinFirmware/Marlin#5935]
Hey

I have this issue running the auto-probe feature on my kossel mini running Marlin on RAMPS 1.4. I've installed an inductive proximity probe which is attached directly to the head between two sets of the arms. The probe's centre is approximately translated by 45 mm and 25 mm in the positive y and positive x direction respectively.

I think this offset has caused me a few issues. The first of which was the following errors when I ran G29: 

?Probe (R)ight position out of range.
?Probe (B)ack position out of range.

I resolved this by reducing my probable range by my offset. G29 now finally runs on the printer, however, the head now arbitrarily probes in midair in whatever z-plane it happens to reside in. It attempts to probe well outside the printable area, and will 'home' towards my bed, instead writing probe data along the lines of: 

307.21 307.09 306.93 306.94 307.14 307.18 307.20 307.22 307.24
306.47 306.84 306.77 306.69 306.80 306.78 306.75 306.77 306.79
305.97 306.22 306.47 306.45 306.46 306.38 306.29 306.23 306.20
306.00 305.98 305.97 306.02 306.13 306.14 306.14 306.16 306.18
306.09 305.98 305.87 305.72 305.73 305.69 305.64 305.61 305.60
305.10 305.09 305.08 305.24 305.34 305.37 305.39 305.43 305.47
304.31 305.06 304.96 304.81 304.82 304.79 304.76 304.76 304.77
304.16 304.15 304.15 304.30 304.39 304.43 304.48 304.54 304.59
304.00 304.02 303.94 303.80 303.80 303.79 303.79 303.80 303.81

The z-probe output is connected to -z on the board. Note, there are 3 pins (2 used usually for the mechanical x/y/z end stops for the top of the kossel, and a third labelled 'endstops'), I'm not using the -z third 'endstop' pin as this prevented the endstop triggering, I'm using just one of the -z pins instead. So when running M119 I get this when metal is not present:

Reporting endstop status
x_max: open
y_max: open
z_min: open
z_max: open
z_probe: TRIGGERED

and when metal is present in front of the inductive probe:

Reporting endstop status
x_max: open
y_max: open
z_min: TRIGGERED
z_max: open
z_probe: TRIGGERED

Is this the reason why G29 causes the printer to sample in mid-air? I think this may be the reason but before I tear up my bed again, I wanted to double check I haven't messed anything else up, and that my config file appears kosher? I've pasted it below...

Thanks!

**Comment by Roxy-3D** [comment]
Please edit your post and delete your configuration.h cut & paste from the post.  It makes the thread very difficult to read.   You can then 'Attach' the file and that will make things much easier for people to follow the thoughts expressed in the thread.

You should turn on the `DEBUG_LEVELING_FEATURE` in configuration.h and run a home operation.  If you post the log of what it says it will be very easy to tell you what is happening and what you need to change:

```cpp
/**
 * Enable detailed logging of G28, G29, M48, etc.
 * Turn on with the command 'M111 S32'.
 * NOTE: Requires a lot of PROGMEM!
 */
//#define DEBUG_LEVELING_FEATURE
```

**Comment by gunnir** [comment]
Hey Roxy,

Thanks for the tip - I'll try when I'm home. Sorry for the inconvenient cut and paste, I was unable to upload a file. Error: "Sorry something went really wrong" or something along those lines. 

I assumed most would copy and paste back into a compiler to see it more easily. I'll try and upload again or use a drop box link if that fails...

**Comment by ghost** [comment]
```cpp
// Enable Z_MIN_PROBE_ENDSTOP to use both a Z Probe and a Z-min-endstop on the same machine.
// With this option the Z_MIN_PROBE_PIN will only be used for probing, never for homing.
//
// *** PLEASE READ ALL INSTRUCTIONS BELOW FOR SAFETY! ***
//
// To continue using the Z-min-endstop for homing, be sure to disable Z_SAFE_HOMING.
// Example: To park the head outside the bed area when homing with G28.
//
// To use a separate Z probe, your board must define a Z_MIN_PROBE_PIN.
//
// For a servo-based Z probe, you must set up servo support below, including
// NUM_SERVOS, Z_ENDSTOP_SERVO_NR and Z_SERVO_ANGLES.
//
// - RAMPS 1.3/1.4 boards may be able to use the 5V, GND, and Aux4->D32 pin.
// - Use 5V for powered (usu. inductive) sensors.
// - Otherwise connect:
// - normally-closed switches to GND and D32.
// - normally-open switches to 5V and D32.
//
// Normally-closed switches are advised and are the default.
//
// The Z_MIN_PROBE_PIN sets the Arduino pin to use. (See your board's pins file.)
// Since the RAMPS Aux4->D32 pin maps directly to the Arduino D32 pin, D32 is the
// default pin for all RAMPS-based boards. Some other boards map differently.
// To set or change the pin for your board, edit the appropriate pins_XXXXX.h file.
//
// WARNING:
// Setting the wrong pin may have unexpected and potentially disastrous consequences.
// Use with caution and do your homework.
//
#define Z_MIN_PROBE_ENDSTOP
```

```cpp
// The Z_MIN_PROBE_PIN sets the Arduino pin to use. (See your board's pins file.)
// Since the RAMPS Aux4->D32 pin maps directly to the Arduino D32 pin, D32 is the
// default pin for all RAMPS-based boards. Some other boards map differently.
// To set or change the pin for your board, edit the appropriate pins_XXXXX.h file.
```
Did you re-assign the `Z_MIN_PROBE_PIN` pin to your `Z_MAX_PIN` (or, whatever pin you plugged your probe into) in your `pins_XXXXX.h` file?

**Comment by Roxy-3D** [comment]
> Thanks for the tip - I'll try when I'm home. Sorry for the inconvenient cut and paste, I was unable to upload a file. Error: "Sorry something went really wrong" or something along those lines.

Not a problem.   I edited the post and removed the Cut & Paste.   Tannoo maybe right...   But with the DEBUG_LEVELING log, we should be able to figure it out pretty quickly.

**Comment by gunnir** [comment]
*UPDATE*

Thank you for all the help guys: I turned on the debugging mode as suggested by @Roxy-3D (thank you!). The mid-air probing was occurring because of two reasons: first I had the following wrong:

```cpp
// Enable Z_MIN_PROBE_ENDSTOP to use _both_ a Z Probe and a Z-min-endstop on the same machine.
// With this option the Z_MIN_PROBE_PIN will only be used for probing, never for homing.
//#define Z_MIN_PROBE_ENDSTOP
```

```cpp
// Enable Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN to use the Z_MIN_PIN for your Z_MIN_PROBE.
// The Z_MIN_PIN will then be used for both Z-homing and probing.
 #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
```

I had my probe sensor probe output connected to the wrong pin and Z_MIN_PROBE_ENDSTOP enabled. I now have Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN enabled and it connected to the correct endstop pin.

This started to allow it to probe the surface correctly! The error with probe range:

?Probe (R)ight position out of range.
?Probe (B)ack position out of range.

Was fixed by changing the probe x/y offset to 0 like so:

```cpp
#define X_PROBE_OFFSET_FROM_EXTRUDER 0 //-45   // X offset: -left  +right  [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER 0  //-25   // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER -1.2        // Z offset: -below +above  [the nozzle]
```

I placed in the comments their true x/y offset from the nozzle. In doing so, I also reduced the probing rectangle range as so:

```cpp
// Set the rectangle in which to probe
#define DELTA_PROBEABLE_RADIUS (DELTA_PRINTABLE_RADIUS - 50)
#define LEFT_PROBE_BED_POSITION -(DELTA_PROBEABLE_RADIUS)
#define RIGHT_PROBE_BED_POSITION DELTA_PROBEABLE_RADIUS  
#define FRONT_PROBE_BED_POSITION -(DELTA_PROBEABLE_RADIUS)
#define BACK_PROBE_BED_POSITION DELTA_PROBEABLE_RADIUS`
```
The only reason it's not -45 in the definition for the probable radius is because I'm actually using an n-doped semi-conductor surface layered onto my aluminium hotbed (which is slightly smaller in radius than the hotbed). This way I can quickly remove the prints and continue printing if needed - but still retain sufficient free-electron mitigation for the inductive proximity probe to detect a surface.

Hooray!

Thanks again guys

(Side note: there may be a more elegant solution to probing the surface but given the physical limitation of the location of my probe relative to the nozzle [centre of head], I'm not sure much else can be done? The probe is over half the radius of the bed away from the nozzle! It would be good if I could probe more of the -ve x range? I.e. the opposing side of the nozzle. If anyone has any ideas? I think that's something I could only solve by editing the actual sample function to bias its sample points into the -ve direction)

**Comment by ghost** [comment]
Adjusting your probe offsets due to an out of range error is not the way to go.

Adjust the probe bed area instead.

**Comment by thinkyhead** [comment]
Three backticks are better than one! 😜 

![image](https://cloud.githubusercontent.com/assets/698003/24929031/2c882d60-1eca-11e7-8b09-8d4fc442ee76.png)
