### ISSUE TITLE
Feed Rate Wont Decrease After Being Raised Marlin 1.1.0-RC8

### ISSUE THREAD

**Issue by NickGerm** [MarlinFirmware/Marlin#5956]
I don't know if this is a bug or if the firmware is suppose to work this way, but after I change the feed rate under the tune menu to a higher rate it will not go slower after lowering it. The rate shown on the display shows the lower amount but the printer does not slow down.

**Comment by thinkyhead** [comment]
It should slow down once the current moves in the planner are completed. Depending on the buffer size, this could take several seconds.
