### ISSUE TITLE
multi head support

### ISSUE THREAD

**Issue by jfpion** [MarlinFirmware/Marlin#5965]
I'm considering the multi head printers. 
the main problem is to find a controler board with the possibility to drive 4 or more heads.
the question is =
-is the mega powerful enough to drive that (I gess yes as ther is only one head used to print at the same time
-is there enough pin for the temp sensor and  mosfet for 4 hothead (I think not)
-is there enough pin for the servos supposed to drive the mouvement of the heads (as i would like a mobile system for the head to avoid having oozing spoiling the print) i suppose not

do you think a arduino mini would be able to be used to drive all the hot end and bed ? the only communication would be the pid configuration at the start of the print and the temp instruction during the print. you can save 6 pin on the ramps 

all the freeable pins could be used to drive an anotther extension board for the stepper drivers (2 pins for a polulu  mean you can drive 2 extruder already on the ramps, plus the 6 saved one means 5 extruders max without using the accessories pin and keeping them for the servo driving the mobile hot end 

is this kind of board doable ?
is marlin able to drive that after some modification ?
is it useful ?

the main avantage would be no need for a 32 bit developpemnt

thank you for your answer

**Comment by Bob-the-Kuhn** [comment]
You may have to go to a board like the [Azteeg X3 pro](https://www.panucatt.com/Azteeg_X3_Pro_p/ax3pro.htm).  It has everything you asked for.  There's more than enough free pins on the expansion headers to accommodate the servo signals.  It's expensive at $135.

An expandable Smoothieboard is coming sometime this year.
