### ISSUE TITLE
Error compiling when define LCD

### ISSUE THREAD

**Issue by pellepant** [MarlinFirmware/Marlin#5975]
Error compiling in arduino. 
define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

This is RC8 with the latest bugfix

Message from arduino
```
compilation terminated.

exit status 1
Error compiling for board Arduino Mega ADK.
```

**Comment by ghost** [comment]
In the arduino IDE, do you have the board set to the Mega 2560?

**Comment by pellepant** [comment]
Yes it is

**Comment by Bob-the-Kuhn** [comment]
There's a board selection for Mega ADK in Arduino.  Try that one.

If that doesn't fix it then ZIP up your config files & I'll try to reproduce the issue.

**Comment by KevMags** [comment]
Is the U8glib library installed?

**Comment by pellepant** [comment]
Yes, i installed it to day

**Comment by Pipshag** [comment]
Pulled down 33f8a8a and compiled with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER support. No problems.

Your error in the first post is "Error compiling for board Arduino Mega ADK.". Is it intentional that you want to compile for the Mega ADK?

Otherwise chose the correct Board AND Processor in Arduino.

In my case it's (Arduino/Genuino Mega or Mega 2560) + (ATMega2560 Mega 2560) for a Rumba.

**Comment by pellepant** [comment]
I want to compile gt2460. I did try adk and mega 2560. Same problem. I got the got i to work with another rc. But when I try the new one it workes only if I skip define LCD graphic board. If I uncomment define full graphical LCD board it won't compile. It's like the issue is with LCD board. 

Sorry my bad English. I am Norwegian

**Comment by thinkyhead** [comment]
@elfag What version of Arduino IDE are you using?

**Comment by pellepant** [comment]
I am using arduino 1.8.1

**Comment by Bob-the-Kuhn** [comment]
The offer to try to reproduce it still stands.

**Comment by pellepant** [comment]
Thank you. Can i upload the files here?

**Comment by thinkyhead** [comment]
You can upload a .zip of your Marlin folder.

**Comment by pellepant** [comment]
I try to upload but i get this

"We don’t support that file type. "

It is a zip file, so i dont know why i cant upload it. Jeez, i feel so stupid

**Comment by pellepant** [comment]
I am sorry for this but i uploaded the zip file to google drive. Here is the link
https://drive.google.com/open?id=0B_dTUMdwWw8xdUZxcld0bmRLYkk

**Comment by thinkyhead** [comment]
I forgot, Github likely needs a `.zip.txt` file extension (cheat) to allow dropping the file on the text-field. Anyway, I have downloaded it and looking it over.

**Comment by thinkyhead** [comment]
The full error appears to be…
```
In file included from .../ultralcd.cpp:61:0:
.../ultralcd_impl_DOGM.h:54:27: fatal error: _Bootscreen.h: No such file or directory
   #include "_Bootscreen.h"
                           ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
```
…so you need to make sure both `SHOW_BOOTSCREEN` and `SHOW_CUSTOM_BOOTSCREEN` are disabled.

**Comment by pellepant** [comment]
Ok, i will try that. Thank you for your help

**Comment by pellepant** [comment]
Yeah, now its working 💃  good job, thank you :)

**Comment by ghost** [comment]
Is it possible to sanity check for the `_bootscreen.h` file or something in it?
