### ISSUE TITLE
I2C comm fail hangs and resets Marlin

### ISSUE THREAD

**Issue by jaysonkelly** [MarlinFirmware/Marlin#5987]
I'm testing some i2c peripherals for my printer. In the middle of printing it would randomly hang and reset causing the print to fail. I traced it down to the i2c write command. 

The default arduino Wire library has no way to handle communication bus hang ups and all its operations are blocking so they have to complete before the code continues. Thus triggering watchdog to reset to recover.

I converted my pc copy to the library described here: http://dsscircuits.com/articles/arduino-i2c-master-library
The functions work a little differently, but it fixed my hang up problem completely by adding the capability to set a timeout. 

Can we add this alternative library to Marlin to replace the arduino wire library?

**Comment by jaysonkelly** [comment]
@thinkyhead, @Roxy-3D, @Bob-the-Kuhn  , I know there's a lot going on with Marlin right now, but if you have a minute will you share your thoughts on this I2C issue? Thanks!

**Comment by thinkyhead** [comment]
I2C handlers are called by interrupt, so they have to exit quickly. This page is worth reading in its entirety to track down i2c issues…

http://gammon.com.au/forum/?id=10896#i2csummary

**Comment by thinkyhead** [comment]
I like that library. Sure, we can integrate it at some point. At the moment, many bugs to chase down so we can get 1.1.0 released and move on to all these new frontiers….

**Comment by jaysonkelly** [comment]
I have already incorporated it into my RCbugFix copy when the library has been added as a library in the arduino editor. I could integrate it. Is adding the Library to Marlin as simple as adding the files to the sketch?

**Comment by jaysonkelly** [comment]
Seems like it is as easy as adding the files to the sketch. Should I make a pull request that replaces wire with I2C or are we not quite ready for that yet?

**Comment by jaysonkelly** [comment]
@thinkyhead is there anything I should wait for to submit this as a pull request? Maybe a build you are all working on that has enough changes that I would cause conflicts with the i2c changes?

**Comment by jaysonkelly** [comment]
@thinkyhead any thoughts?

**Comment by jaysonkelly** [comment]
@thinkyhead, @Roxy-3D, @Bob-the-Kuhn, Just looking for a little direction here. Should I submit a pull request with the current bugfix branch with the I2C library change or should I wait for any of the big changes you are making to be complete?

**Comment by jaysonkelly** [comment]
@thinkyhead Should I work on a pull request into the current version of RCBugFix?
