### ISSUE TITLE
Temperature Data Export

### ISSUE THREAD

**Issue by fiona-brennan** [MarlinFirmware/Marlin#5991]
Is there any way of exporting the temperature data of the extruder? I know you have the temperature curve on the screen in Repetier Host Software, but is there anyway of plotting temperature vs time?

**Comment by Bob-the-Kuhn** [comment]
I didn't find any elegant ways of getting the temperature data from Repetier Host.  I was hoping to find a plugin but no luck.

The only ways I know of are:
- Screenshots - Repetier can display up to an hour's worth of data & you can select which hour to display.
- Session log - under preferences you can enable logging.  The log includes the temperatures and all other communications with the printer.  You'd have to extract the data before you could plot.

Repetier Server contains a logging function.  I expect it's similar to Repetier Host in that it contains all the communication.

**Comment by thinkyhead** [comment]
If I wanted to do this I'd grab the raw temperature output from Marlin, do a bunch of search-and-replace to turn it into a simple array, including the time-stamps, if needed, and paste it into a spreadsheet. then use the graphing functions of the spreadsheet to examine the data.
