### ISSUE TITLE
SLOW_PWM_HEATERS is broken for duty above 112/127, i.e. 88%

### ISSUE THREAD

**Issue by StefanBruens** [MarlinFirmware/Marlin#6002]
If the PWM is switched of late in the cycle, state_timer_heater_X is still > 0 at the beginning of the next cycle. As a heater X is only switched on if (slow_pwm_count == 0) AND state_timer_heater_X == 0, the heater stays of for the whole cycle, i.e. on average the duty is 44% instead of 88%.

**Comment by thinkyhead** [comment]
See also #6003

Is this issue still extant?
