### ISSUE TITLE
SOFT_PWM is off by one, low duties are higher than intended

### ISSUE THREAD

**Issue by StefanBruens** [MarlinFirmware/Marlin#6003]
A PWM with 128 steps has a maximum count of 127 (0/127 ... 127/127). Currently, a setting of 1/127 runs for 2 counts, i.e. the PWM is switched at pwm_count == 0, but only switched off at pwm_count == 2.

**Comment by thinkyhead** [comment]
Is this still an issue in the current release?

**Comment by AnHardt** [comment]
Fixed with #6100 #6109 by @thinkyhead .  ;-)
