### ISSUE TITLE
[FR] Ability to set thermistors via gcode/eeprom

### ISSUE THREAD

**Issue by Lenbok** [MarlinFirmware/Marlin#6004]
I have a couple of different extruders (e.g. for 1.75mm vs 3mm filament) which I swap over on a semi-regular basis. Unfortunately one uses an E3Dv5 and the other uses E3Dv6, which use different thermistors. Currently this means I have to recompile the firmware whenever swapping the extruders over.

I found a reference where someone thought it was possible to set via gcode command at: https://github.com/foosel/OctoPrint/issues/178#issuecomment-20438599 however this doesn't seem to be the case.

This would be a nice feature!

**Comment by Bob-the-Kuhn** [comment]
I think the heat break is the same for both.  That means you could use identical heat blocks which means you could use the same thermistor.

**Comment by boelle** [comment]
@Lenbok i agree with @Bob-the-Kuhn 

it will make marlin less complicated if you use the same heatbreak and heatblock

also better for you since you only need to buy 1 type of thermistor and nozzle

**Comment by InsanityAutomation** [comment]
@boelle @shitcreek This is done as well. Can be killed.

**Comment by boelle** [comment]
ZAP
