### ISSUE TITLE
Heating Failed when Bed Thermal Protection is enabled, No heatbed

### ISSUE THREAD

**Issue by psavva** [MarlinFirmware/Marlin#6011]
I would like to suggest a small additional to the sanity check for configuration with regards to the heated bed.

I do not have a heated bed enabled within the Firmware.  Ie: I set bed thermistor to 0.
The default configuration for Marlin is that Thermal Protection is enabled on both the hotend and heated bed.

If you do not have a heated bed configured, but enable (by default) the Thermal Protection for the heated bed, you will get a "heating Failed" message which actually originates from the non-existing bed...

I suggest to add a sanity check so that if Bed Thermal Protection is enabled, then bed thermistor must also be set.

I turned off the option for bed thermal protection, and no more heating failed messages...

**Comment by Blue-Marlin** [comment]
I would like suggest to you, to make a sanity check for your g-code-files. Don't try to heat a not existing bed.

**Comment by psavva** [comment]
I'll double check the gcode if this is the case, and report back.

**Comment by psavva** [comment]
Your right, cura has a surface temperature setting, even when you define that a print bed isn't available...

**Comment by Blue-Marlin** [comment]
Maybe it's not Cura itself but your startscript Cura includes.

**Comment by psavva** [comment]
I checked it... It's cura...
My startup script doesn't include any M140's

**Comment by thinkyhead** [comment]
Patched at #6215
