### ISSUE TITLE
Marlin RC8 crashing(!) at start of print job. - possibly caused by G91 -> G90 changeover.

### ISSUE THREAD

**Issue by azalanono** [MarlinFirmware/Marlin#6019]
With "crashing" I really mean a "total software crash" in Marlin. Marlin either reboots in this case or - more often - simply stucks (doing absolutely nothing any more, but the nozzle heater can still be ON !!! which is extremely hazardous). 

My hardware:
I use a cartesian 3D printer with "Marlin RC8" and "octopi" print server, running on a Raspberry Pi 1B.  

To be able to simply replace the filament without heating up the nozzle for that, I added some G-Code to load/unload Filament by 50 mm. So the filament is out of extruder, but still in access by the feeder. For simplification I use G91 at my commands.

First I found out that Marlin survived when I changed the speed of first moves to a value below F1000. Otherwise Marlin did an extremely fast Z-Move and crashed hereby. Moving slow with F700 (I marked the code to be changed in last 5 lines in bold), Marlin survived and worked then as expected.,
But this was no solution, because it required patching of every particular file. So I tried to add some slow moves to give Marlin time to settle.

**This is my code, including the first lines of the Slic3r G-code, it also contains some LCD debug messages:**
M107
M190 S55 ; set bed temperature 
M117 Slic3r Init start    ; <-- Slic3r Custom G-Code starts here
G4 S3

M104 S195 ; Heat up nozzle for loading filament
G28 ; home all axes
M109 ; Wait for heatup finished. I do the TouchOff always with hot tip,
G29 ; bed leveling

G91 ; Relative Moves
G1 Z10 F600  ; Lift nozzle +10 mm
G0 X50 F300  ; Right border of bed
M117 Loading Filament 
G1 E50 F300     ; Feed in previously retracted filament 50 mm
G0 X-20 F300   ; Move 200 mm to the left so I am not above the filament pile
G4 S5  ; Let Filament harden
G1 X-50 F300 ; Move another 50 mm to the left (tear off extruded filament)
G90  ; Absolute Moves again
**G1 Z1 F300**    <<---  This fixed the problems
M117 Slic3r Init End
G4 S5

; HERE FOLLOWS NORMAL SLIC3R CODE
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
G1 E-3.00000 F1800.00000
G92 E0
G1 Z1.000 **F7200.000**     ; <- Had to set this to F700 before
G1 X77.918 Y92.418 **F7200.000**     ; <- Had to setthis to F700 before
G1 Z0.300 **F7200.000**     ; <- Had to set this to F700 before
G1 E3.00000 F1800.00000
G1 X79.322 Y91.767 E3.06280 F1584.000

All this shows up that there is for sure something wrong in Marlin's code.

**Comment by Sebastianv650** [comment]
Please test again with rcbugfix. There are some already fixed bugs in rc8 that could cause that issue.
