### ISSUE TITLE
Menu item selection

### ISSUE THREAD

**Issue by danst0** [MarlinFirmware/Marlin#6022]
Hi,

with my Tevo Tarantula and latest Marlin firmware I am experiencing issues in selecting menu items in the LCD menu. Especially for the first tries I select an item and either the sub-menu does not appear or another one appears.

It seems to help if I first scroll down a list of menu items to the bottom and then up again to the item I really want. 

Daniel

**Comment by chris-hemmings** [comment]
You need to adjust the Encoder steps per menu item and encoder pulses per steps. Mine is set to 4 pulses and 1 step

**Comment by thinkyhead** [comment]
What kind of LCD does the TEVO use? Have you altered your `ENCODER_PULSES_PER_STEP` and `ENCODER_STEPS_PER_MENU_ITEM`?
