### ISSUE TITLE
Nozzle heater and bed heater inversed + lcd problem

### ISSUE THREAD

**Issue by KookaS** [MarlinFirmware/Marlin#6055]
Hi,
I've bought a 3d printer on aliexpress. The mother board was already installed with the right firmware and worked properly except for the fans. So I tried to upload the new marlin firmware and since then it's impossible to make I work properly.
First when I try to heat the nozzle, the bed heats instead and same for the bed. I can still switch the two cables but I will have to solder the cables to make them longer. Any idea why the latest version does this problem ?
Secondly, my LCD screen doesn't work either since the upgrade. Only two rows of blocks appears. I tried to turn the screw behind without success and to switch the LCD cables.

I tried to put back the old version but it always has compilation problems... so I can't upload it.
I have a ramps 1.4 and a reprap discount smart controller.

I have tried everything so please help me find a solution.

**Comment by thinkyhead** [comment]
Please post a photo of the electronics. Is it a generic RAMPS? Please also post your Configuration files. (You have to add `.txt` to the filename to be able to drop them onto these edit fields.)

**Comment by KookaS** [comment]
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/853224/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/853225/Configuration_adv.txt)
![20170319_144558](https://cloud.githubusercontent.com/assets/26506627/24081470/95666ea0-0cb4-11e7-8ac4-d9e8e72a8ebd.jpg)
![20170319_144612](https://cloud.githubusercontent.com/assets/26506627/24081471/95691218-0cb4-11e7-94c4-9889125b8531.jpg)
![20170319_144540](https://cloud.githubusercontent.com/assets/26506627/24081472/956beaf6-0cb4-11e7-81ac-02c296470590.jpg)
![20170319_144551](https://cloud.githubusercontent.com/assets/26506627/24081473/956dfea4-0cb4-11e7-8cb3-ced4f57752d6.jpg)

It's a Ramps 1.4 plus. I used the 1.1.0- RC7 version as a firmware.

**Comment by thinkyhead** [comment]
```cpp
#define MOTHERBOARD BOARD_RAMPS_PLUS
```
