### ISSUE TITLE
Target temperature 1 K too high when setting in kelvin

### ISSUE THREAD

**Issue by ospalh** [MarlinFirmware/Marlin#6056]
I was just reading the code, but this line seems odd:
https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/Marlin_main.cpp#L1255
Either i am missing something or the target temperature will be 1 K too high, when set in kelvin.
To go from kelvin to degree Celsius you have to subtract 27*3*.15, not 27*2*.15.
(This other bit seems to get it right:
https://github.com/MarlinFirmware/Marlin/blob/RC/buildroot/share/scripts/createTemperatureLookupMarlin.py#L26 )

**Comment by thinkyhead** [comment]
Thanks! That's going to be important as we start printing with plasma.
