### ISSUE TITLE
Ramps 1.4 low memory

### ISSUE THREAD

**Issue by playlet** [MarlinFirmware/Marlin#6061]
Hi!

I just uploaded latest RCBugFix code to my Mega2560/Ramps1.4 hardware. I want to use UBL but I get this message after upload completes:

Sketch uses 177448 bytes (69%) of program storage space. Maximum is 253952 bytes.
Global variables use 6862 bytes (83%) of dynamic memory, leaving 1330 bytes for local variables. Maximum is 8192 bytes.
Low memory available, stability problems may occur.

Does this mean that my printer will not run very well with 60mm/s printing speed and linear advance enabled?

Do I need to start searching for a new faster board with more memory? Which one do you recommend?

Thanks, Ivan

**Comment by ghost** [comment]
I got the same with UBL enabled. Although, I haven't been able to test it just yet.
I don't have linear advance enabled.

**Comment by Sebastianv650** [comment]
We had one issue here not that long ago where this warning was not seen first, leading to strange bugs due to memory run out. 
With that in mind, you might try to run your configuration, but if you get problems try to disable features and see if the error persists.

**Comment by Roxy-3D** [comment]
It is the RAM memory that you mostly care about.   80 KB of program space is plenty of room for additional features.   And in fact, it is pretty easy to strip out optional features and have Marlin fit on a 64 KB processor.

Having 1300 bytes of RAM memory free is fine.   That leaves plenty of room for the stack to grow up and down.   If you are nervous about it, turn on the M100 free memory watcher.  Let Marlin do its normal thing to do a print.    And then ask M100 how much free...   never touched....  memory there is.   As long as you have some space so the stack doesn't run out of space, you should be fine.

> I got the same with UBL enabled. 

Yeah...   UBL uses a lot of memory.  Both RAM and program space.   You especially use a lot of memory if you define a high resolution 15 x 15 mesh.  That burns up 15 x 15 x 4 (900) bytes of RAM just to hold the active mesh.    But if you have 500 bytes of free RAM after doing the M100 (after starting a print) you should be OK.   UBL should start shrinking in size now as debug code is removed and features are consolidated. 

We don't want to waste the processor chip's resources.   But that memory is there to be used!   It can't do cool things for you if it isn't used.

**Comment by playlet** [comment]
Okay, thanks!

**Comment by thinkyhead** [comment]
UBL should use a little bit less SRAM now than 2 weeks ago.

**Comment by playlet** [comment]
nice, keep up the good work :)
