### ISSUE TITLE
Firmware for Tarantula prusa I3 DIY 

### ISSUE THREAD

**Issue by rodrigocontrerasa** [MarlinFirmware/Marlin#6064]
Hi, I bought a tarantula printer in AliExpress, but when I tried to upgrade the firmware for two extruders it turns black the LCD panel and didn't function any more. I'm quit sure that I upload a wrong one. Where can I fin and which is the correct one?

**Comment by dubstratus** [comment]
You may need to upload the u8glib file and reverse the plugs where the screen plugs in. By reverse I mean cut off the locating tabs or pull the socket off the board and turn it arround. I recently had the same issues.  Check this out 
https://www.thingiverse.com/groups/prusa-i3/topic:3586
