### ISSUE TITLE
Changing the endstop output

### ISSUE THREAD

**Issue by ronenst1** [MarlinFirmware/Marlin#6078]
How can I change the endstop output from active high to activate low or using a PNP sensor instead of an non sensor.

**Comment by Blue-Marlin** [comment]
https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Configuration.h#L456

**Comment by Bob-the-Kuhn** [comment]
I'm not quite sure of the question.

If you want to tell Marlin if it's an active high or active low signal then set **Z_MIN_ENDSTOP_INVERTING** or **Z_MIN_PROBE_ENDSTOP_INVERTING** as needed.

If you need to know how to interface the sensor to your controller then try this [setup](http://www.3d-proto.de/public/img/IndSensorSetup.png).

**Comment by ronenst1** [comment]
Thanks all I succeed and it is working perfectly
