### ISSUE TITLE
Marlin RC7, delta, straight line issue. 

### ISSUE THREAD

**Issue by RajaaKahel** [MarlinFirmware/Marlin#6080]
Hi all, me and some guys are having a strange issue with our deltas. I'd be really thankful if someone can point the problem. 
When I print a straight line/wall and the line is parallel with X axis; I don't get a straight line!
We tried everything.. Rods, balls, drivers, sliders, etc.. Almost nothing left to diagnose the problem. The angles between towers are 120°. The printer frame is very rigid. 
Any help or tips will be very appreciated!
More pictures will follow 
![20170319_155133](https://cloud.githubusercontent.com/assets/23242775/24098978/670bf9c6-0d6d-11e7-95f7-1ea04d4e2b63.jpg)

![20170319_161755](https://cloud.githubusercontent.com/assets/23242775/24099026/a90e9ef0-0d6d-11e7-9eec-60d96f07cba7.jpg)

**Comment by epatel** [comment]
Your X rod arrangement? See http://forums.reprap.org/read.php?397,650342,650348#msg-650348

**Comment by RajaaKahel** [comment]
Thanks Epatel, but as I said we are having the problem on delta printers, not CoreXY or Cartesian.

**Comment by RajaaKahel** [comment]
![20170226_221418](https://cloud.githubusercontent.com/assets/23242775/24110470/c83a5672-0d93-11e7-8bd7-52930b786ff5.jpg)

**Comment by RajaaKahel** [comment]
Made a test in vase mode and normal mode, same problem. And the problem is happening in all three lines/walls as you see. Even in the skirt.

![20170320_200441](https://cloud.githubusercontent.com/assets/23242775/24118752/32c11b50-0daf-11e7-9e79-4fb79ac185df.jpg)

**Comment by RajaaKahel** [comment]
I rotated the same last test 180° so the corners are pointed to the towers, I got the same problem as the last test. The curve is happening in the same place of the lines.

[
![20170320_203757](https://cloud.githubusercontent.com/assets/23242775/24118796/529e0212-0daf-11e7-84a7-9ad9b145771e.jpg)
](url)

**Comment by oysteinkrog** [comment]
If you could test an alternative firmware it would be great, as it would allow us to eliminate your mechanics as the source of the problem.

**Comment by karabas** [comment]
I got the same problem. print big triangle as big as it can fit.  You will see path changing exactly in the middle of side. 
Next, pathes clockwise and counterclockwise are never match. 
I think it is due to carriage dead point when changing direction. Try wider belts.

**Comment by thinkyhead** [comment]
Have you tested another firmware, or another version (e.g., 1.0.2-2) of Marlin yet to eliminate the mechanics as the source of the issue?
