### ISSUE TITLE
LCD Menu slow (not only navigating SD or during print) - RAMPS 1.4 Marlin 1.1.0-RC8

### ISSUE THREAD

**Issue by scipione205** [MarlinFirmware/Marlin#6097]
I just upgraded the fw to 1.1.0-RC8 and noticed that the LCD menu navigation is very slow (also when it changes screen), the navigation with the knob is troublesome and almost always when I choose an item it actually choose another, and also choosing number it's very troublesome.
It is very glitchy. Worked fine with 1.1.0-RC4

It runs on RAMPS 1.4 and RepRapDiscount Full Graphic Smart Controller.

**Comment by Sebastianv650** [comment]
Can you try RCBugFix, because there are a lot of bugs fixed since RC8.

**Comment by scipione205** [comment]
I will maybe during weekend. Thank you.
