### ISSUE TITLE
Extruder1 jogging don't work

### ISSUE THREAD

**Issue by arhi** [MarlinFirmware/Marlin#6107]
1.1.0RC8, BOARD_RAMPS_14_EEF,REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

this works as expected:
```
T1
G1E100

```
but going trough menus (Prepare/Move Axis/Move 1mm/Extruder1) does not work (extruder0 works ok, extruder1 is not running :( )

**Comment by thinkyhead** [comment]
Presuming solved.
