### ISSUE TITLE
value is not pad right correct from menu when using u8g_font_9x18 ?

### ISSUE THREAD

**Issue by fred2088** [MarlinFirmware/Marlin#6119]
```cpp
  #define FONT_MENU_NAME u8g_font_9x18   // fred
  #define FONT_STATUSMENU_NAME u8g_font_6x10
```
while USE_BIG_EDIT_FONT provide value pad right correctly from 1.1.0-RC8

**Comment by fred2088** [comment]
Fixed
must changed the following parameter at the same time if change system font
```cpp
#define DOG_CHAR_WIDTH         9 // 6
#define DOG_CHAR_HEIGHT        18 // 12
```

**Comment by thinkyhead** [comment]
Marlin has `DOG_CHAR_EDIT_WIDTH` and `DOG_CHAR_EDIT_HEIGHT` and these have now been tweaked.
