### ISSUE TITLE
X/Y/Z flash to Question Marks on Power On

### ISSUE THREAD

**Issue by chase-cromwell** [MarlinFirmware/Marlin#6127]
When I power my machine on (1.1.0 RC-8) the spaces for X-Y-Z co-ordinates flash the XYZ to ? (question marks) and back and forth. I cant move my motors until I do an auto home, even if endstops and software endstops are disabled. I don't have any endstops and this recent functionality is not documented anywhere that I can find. How do I work around this?

My machine is a pain to use at this point because of this.

**Comment by chase-cromwell** [comment]
And also, since disabling the stepper pins in the ramps pins file like http://ohmeye.com/2013/disablingenabling-endstops-in-marlin/ , auto home raises my Z up 5mm and then still flashes the ? and doesn't let me move motors with Prepare > Move Axis.

**Comment by Bob-the-Kuhn** [comment]
The question marks are just saying that the machine doesn't know where it's at.  

It sounds like you had your machine working and only had problems after switching to a newer version of Marlin.  Is that correct?  What did you go from and what did you go to?

No endstops - that's the way I ran when I first got my machine running.  I'm trying to remember what it took to do that.

I just tried to do that but I can't get by the sanity check.  It's insisting on an X, Y & Z endstop.

If you do a M119 command and it says that both the MIN and MAX endstops are triggered then that axis isn't going to move.  In that case enable the endstop pullups and set all the endstop invertings to true.  After that M119 should only report open.

----

If you want you can drop your config files (both old/working and new/problem versions) onto your reply & I'll see if I can spot anything.

You'll either need to ZIP them up or rename them to xxx.h.txt before dropping them.  GitHub only allows certain file extensions when dropping.

**Comment by chase-cromwell** [comment]
=( This is my R & D machine that has never worked up until just recently, when I finally got a new hotend for it. Shortly afterwords I fried the Ramps Board. I never had the original firmware. I'm trying to upgrade to a MKS Base 1.0, which is why I'm using RC8 (includes functionality) My other machine works on an older version of Marlin with no issues with endstops. (Don't use them on that one either.)

**Comment by Bob-the-Kuhn** [comment]
I have a 2560 based controller so I could try to reproduce your problem if I had your config files.

I'd be really interesting to see what M119 reports.

**Comment by chase-cromwell** [comment]
M119 reports back
SENT: M119
RECEIVED: Reporting endstop status
RECEIVED: ok

**Comment by Bob-the-Kuhn** [comment]
I'm out of ideas until I try to reproduce your problem.

**Comment by K3nt** [comment]
Can you help me?  I'm having the same trouble.  And my machine stuck  for a year and counting. How can I attach my config here?

**Comment by Bob-the-Kuhn** [comment]
If the file extension is .txt or .zip you can just drop the file on the comment window. 

I'll need both your config files and which version of Marlin that you're using.

Once we get your printer working I hope you upgrade to a newer version of Marlin.  Many more features and better/faster LCD support.

When using the USB port - how functional is your printer?  Does it respond to any commands?  

What does your LCD report for temperatures?

**Comment by K3nt** [comment]
Im using anger a8 3d printer. And I change the board with ramps 1.4a and
ever since I haven't succeeded yet.

Marlin v1.1.0-rc8
Via usb,  I don't get any voltage operation and no movement on motor
Heat bed and filament heater are working fine.

**Comment by willytwo** [comment]
> You'll either need to ZIP them up or rename them to xxx.h.txt before dropping them. GitHub only allows certain file extensions when dropping.

I have the same issue. Were you ever able to resolve it?
I have an Anet A8 and just upgraded from stock firmware to Marlin ver 4. 
Any help would be appreciated.

**Comment by thinkyhead** [comment]
@willytwo — 
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
