### ISSUE TITLE
AUTO_BED_LEVELING_*** ignores boundaries and points

### ISSUE THREAD

**Issue by iurobpn** [MarlinFirmware/Marlin#6135]
Hi, I'm using Marlin 1.1.0 RC8, and a RAMPS 1.4. Each AUTO_BED_LEVELING on marlin ignores points or boundaries set by using constants:

 ```
 #define LEFT_PROBE_BED_POSITION 45
  #define RIGHT_PROBE_BED_POSITION 170
  #define FRONT_PROBE_BED_POSITION 30
  #define BACK_PROBE_BED_POSITION 160
```

or, for 3 points:

```
#define ABL_PROBE_PT_1_X 45
#define ABL_PROBE_PT_1_Y 160
#define ABL_PROBE_PT_2_X 45
#define ABL_PROBE_PT_2_Y 30
#define ABL_PROBE_PT_3_X 170
#define ABL_PROBE_PT_3_Y 30

```
The printer always start at a point out of boundary, making ir try to probe at a point where the inductive sensor is out of bed, possibly causing harm to the extruder and or bed.

I'm trying to make the autoleveling feature works for 3 days, and I think it is possible that its a Marlin's bug. My Configuration.h is in the [pastebin](https://pastebin.com/cMHT69P9). Any help? Is it a bug, or I'm missing something? 

ps: I have look extensively on google, and in other issues.

**Comment by Roxy-3D** [comment]
Are you clearing the EEPROM with M502 and M500?   That pastebin link isn't working for me.

**Comment by iurobpn** [comment]
I fixed the link above. No, I didn't clear the EEPROM, I will try and post the result later.

**Comment by chris-hemmings** [comment]
Did this work? If you have the correct offsets set for the z probe, it should work.

**Comment by thinkyhead** [comment]
Be sure to test the `RCBugFix` branch to see if the newer code resolves the issue.

**Comment by iurobpn** [comment]
It worked, Thank you. Sorry I took a long time to answer...
