### ISSUE TITLE
Simple output of a few Bytes of Data on the TX pin

### ISSUE THREAD

**Issue by matrix3dmachine** [MarlinFirmware/Marlin#6145]
Is it possible to add some simple code to output a few bytes of data for the LCD?

Meaning, is it possible to output the "print complete" percentage as a byte of data out on the UART TX pin of the RAMPS board?  Maybe output the byte every 1min?

Mike

**Comment by Blue-Marlin** [comment]
M117

**Comment by matrix3dmachine** [comment]
Can the M117 command be implemented while the printer is printing?

Where is the command placed in the Marlin code to achieve this?

**Comment by teemuatlut** [comment]
M117 would print a message on the LCD.

M27 would give you the "position / filesize" if printing from the SD card.

For bare byte sending, you'd need to send the return value of card.percentDone().

**Comment by matrix3dmachine** [comment]
Hmm, maybe i was unlclear.

I want to continuously spit out information every minutes on the UART TX pin during a print.  I don't want to print to the LCD or write to the SDCard, just spit out a byte of data on the TX pin of the UART.  The data contained in the byte would be the percentage done of a print and possibly the temperature of the hotend.  These are variables already configured in the LCD. 

I don't know where to put what in the Marlin code.  I'm a hardware guy doing software.

Mike

**Comment by teemuatlut** [comment]
Something along the lines of
```cpp
In Marlin_main.cpp: idle()

static millis_t next_tx= 0;
if (ELAPSED(millis(), next_tx)) {
  next_tx = millis() + 60000; // 60s
  MYSERIAL.print(card.PercentDone());
  MYSERIAL.print(thermalManager.degHotend(0));
}
```

**Comment by matrix3dmachine** [comment]
Thanks a lot!!! I will try it out.

Mike

**Comment by matrix3dmachine** [comment]
Inserted Code on line 4156, RC8BUGFIX, Marlin_main.cpp

idle();
      } // inner
      } // outer
         static millis_t next_tx= 0;
          if (ELAPSED(millis(), next_tx)) {
            next_tx = millis() + 60000; // 60s
            MYSERIAL.print(card.PercentDone());
            MYSERIAL.print(thermalManager.degHotend(0));
          }
          
Got these syntax erros....do I need to #include a .h file for the serial port calls?
sketch\Marlin_main.cpp: In function 'void gcode_G29()':
Marlin_main.cpp:4159: error: 'class CardReader' has no member named 'PercentDone'
             MYSERIAL.print(card.PercentDone());
                              ^
exit status 1
'class CardReader' has no member named 'PercentDone'

**Comment by teemuatlut** [comment]
The 'PercentDone' should actually be 'percentDone'. My bad.

It sounds like you added the code into G29, bed leveling routine. The idle function is on line [10649](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Marlin_main.cpp#L10649-L10677). Search for 'void idle'.

**Comment by matrix3dmachine** [comment]
Thanks again. 

Quick Question:
Is there a way to remove:
Pause Print
Stop Print
Resume Print

From the LCD menu?

**Comment by Roxy-3D** [comment]
Yes...   Just go into ultralcd.cpp and delete lines like

```cpp
           MENU_ITEM(function, MSG_PAUSE_PRINT, lcd_sdcard_pause);
```

**Comment by matrix3dmachine** [comment]
Hi teemuatlut,
This is the errors I got when inserting the code on line 10649, after the Void stop() routine.
Here is what I inserted:

static millis_t next_tx= 0;
          if(ELAPSED(millis(), next_tx)) 
          {
            next_tx = millis() + 60000; // 60s
            MYSERIAL.print(card.percentDone());
            MYSERIAL.print(thermalManager.degHotend(0));
          }
         
 
Errors:
Marlin_main.cpp:10635: error: expected unqualified-id before 'if'

           if(ELAPSED(millis(), next_tx)) 
           ^
exit status 1
expected unqualified-id before 'if'

**Comment by teemuatlut** [comment]
The code needs to be inside the void idle() function.

**Comment by matrix3dmachine** [comment]
Hi teemuatlut,
It's almost working!  Temp is being displayed, but the percent complete is not....
Searched around for any other commands for percent complete, but could not find anything.

Any ideas?  Is it being overwritten?

Mike

**Comment by matrix3dmachine** [comment]
Hi teemuatlut,
There is actually a char printing for percent complete, but I think this is an ASCII to number problem.  When the LCD is displaying 48%, the serial port is printing out 8, and 49% is 1, 50% is 2, and so forth.  I think I need a conversion.

I added 48, but that did not do the trick.
MYSERIAL.println((card.percentDone()+48));

Mike

**Comment by Roxy-3D** [comment]
If you are willing to have several bytes of serial output...  You can switch from
```cpp
MYSERIAL.print(card.percentDone());
```
to the ASCII output of the number with
```cpp
SERIAL_PROTOCOL(card.percentDone());
SERIAL_PROTOCOL("%");
```

**Comment by matrix3dmachine** [comment]
Hi All,
I was able to get it working by using:
MYSERIAL.print(itostr3(card.percentDone()));

Now it prints temp and percent done!  Thanks again!

**Comment by matrix3dmachine** [comment]
The terminal seems to print out a bunch of garbage and messages during a print, X,Y,Z etc.  Is this a debugging thing I can turn off?

**Comment by thinkyhead** [comment]
> The terminal seems to print out a bunch of garbage and messages during a print

`M111 S0`
