### ISSUE TITLE
SD card filenames are capitalized unexpectedly with M20 M29 GCODE commands

### ISSUE THREAD

**Issue by denmorru** [MarlinFirmware/Marlin#6165]
Upload file named in lowercase to SD over Serial with M28, printer LCD has correct lower case name, but after M29, it is shown uppercase in the files list. The same illegal uppercase returned by M20.
In case copy files to SD from PC card reader, they will be shown lowercase on printer (correct), but not in M20 result.

This bug should be in `gcode_M20()`   function `card.ls();` ,because
 `SERIAL_PROTOCOLLNPGM(MSG_BEGIN_FILE_LIST);` and `SERIAL_PROTOCOLLNPGM(MSG_END_FILE_LIST);` both return correct lowercase. 

Tested Marlin 1.1.0-RC8/RAMPS1.4./REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by denmorru** [comment]
Function ls() called from Marlin_main.cpp 
```
void CardReader::ls()  {
  lsAction = LS_SerialPrint;
  root.rewind();
  lsDive("", root);
}
```
found in cardreader.cpp
with `lsDive() `resulting in call: `SERIAL_ECHOLN(lfilename);`

Extra problem: long file name path https://github.com/MarlinFirmware/Marlin/wiki/M20

**Comment by Blue-Marlin** [comment]
8.3 filename https://en.wikipedia.org/wiki/8.3_filename
M33 https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/Marlin_main.cpp#L4783

**Comment by Blue-Marlin** [comment]
External interface (serial/usb) is consequently 8.3.
For display purpose you can get the 'long' filename by `M33 8.3-name`.

**Comment by denmorru** [comment]
`#define LONG_FILENAME_HOST_SUPPORT` enabled for LCD, because (above): `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`.

Current serial speeds (250000) require another protocol for file exchange, making it possible to forget 8.3 and `M28`/`M29`.

But in this case, some serial+sd functions could be changed to make it better, because 8.3 is not a must. 
`char *createFilename` - this is evil there.
Proof in GCODE: `M117 /longer/files/exchange/longFileName_longer.gcodelong.verylong`
Filesystem is FAT32.
