### ISSUE TITLE
UBL & Mesh Editing requirement?

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#6191]
If `UBL_G26_MESH_EDITING` is required to run `G29`, then why not a sanity check?

I loaded the latest RCBugFix tonight and had `AUTO_BED_LEVELING_UBL` enabled. `G29` simply does nothing but report back `ok`.
```
      #if PLANNER_LEVELING && !ENABLED(AUTO_BED_LEVELING_UBL) || ENABLED(AUTO_BED_LEVELING_UBL) && ENABLED(UBL_G26_MESH_EDITING)
        case 29: // G29 Detailed Z probe, probes the bed at 3 or more points,
                 // or provides access to the UBL System if enabled.
          gcode_G29();
          break;
```

**Comment by ghost** [comment]
Something else is going on because I saw that I do have the mesh edit enabled.

I see what happened. I made an error in `configuration.h`. `UBL_G26_MESH_EDITING` was still `UBL_MESH_EDIT_ENABLED`.

Corrected it and it works.

**Comment by thinkyhead** [comment]
Yep! Somehow in my sleepless state I forgot to remove that condition from the UBL_G29 precursor. It's patched now. Also added a sanity check I forgot to include.

EDIT: or, now.
