### ISSUE TITLE
(1.1.0 Bugfix) Delta Printer adjusts to Z-Offset after G29 / Correcting too much

### ISSUE THREAD

**Issue by NilsRoe** [MarlinFirmware/Marlin#6194]
I have migrated my ancient Kossel Mini Delta to the newest 1.1.0 RC8 Firmware yesterday. I was experiencing some issues with the autolevel and decided to try 1.1.0 Bugfix today (01. Apr 2017 ~12:00)

I am experiencing a strange issue with the autolevel - my allen key probe is configured such that it reaches around -6.9mm **below** the extruder. This has worked out more or less for the last two years. 

Now, after a G28/G29, the nozzle touches the bed when Z goes to 6.9mm (or the respectively set Z offset):

G28: Nozzle barely touches the bed at Z0.0 (paper test)
G28, then G29: Nozzle touches the bed at Z6.9

Setting the Z offset in the configuration.h and in the LCD menu caused the allen key to be dragged around the bed and ruining the tape layer. I have tried numerous settings with the probe wandering off or the nozzle slamming into the bed. Changing around the M206 parameter didn't help (after G29).

My Delta rod settings etc should be correct. The probe is deployed manually and then retracted automaically by pushing it on a screw head outside the printing area.

My config files cannot be attached as a ZIP/.h etc.. If I made a trivial mistake, please feel free to point it out!

Nils

EDIT: 
```
Bilinear Leveling Grid:
     0     1     2     3     4     5     6     7     8
 0 -4.40 -4.95 -5.58 -5.38 -3.28 -3.67 -4.56 -4.93 -4.85
 1 -4.77 -4.97 -5.07 -5.20 -5.30 -5.33 -5.19 -5.10 -5.05
 2 -5.06 -5.32 -5.54 -5.67 -5.76 -5.74 -5.65 -5.50 -5.41
 3 -5.41 -5.70 -5.91 -6.06 -6.10 -6.13 -6.02 -5.92 -5.66
 4 -5.83 -6.08 -6.31 -6.45 -6.41 -6.41 -6.34 -6.15 -5.95
 5 -5.98 -6.28 -6.51 -6.68 -6.67 -6.68 -6.61 -6.44 -6.20
 6 -6.25 -6.52 -6.68 -6.81 -6.86 -6.84 -6.71 -6.55 -6.35
 7 -6.33 -6.58 -6.80 -6.90 -6.93 -6.94 -6.83 -6.67 -6.41
 8 -6.45 -6.61 -6.78 -6.95 -7.00 -6.93 -6.78 -6.61 -6.51
>>> M851
SENDING:M851
echo:Z Offset : -6.90
```

**Comment by NilsRoe** [comment]
I have since observed another issue: Apparently the value for `#define Y_PROBE_OFFSET_FROM_EXTRUDER` is completely ignored (at least partially) when setting up the points for probing. The probe starts at the front, about 2cm away from the brim, and finally ends at the back with just a few mm of space left. It seems the nozzle is moved to the appropriate points, but not the probe.

**Comment by chris-hemmings** [comment]
Regarding your Probe offset problem, My bltouch is offset -20. And when it does the bed levelling it works fine. Make sure that your auto_bed_levelling options are taking into account the probe offset. Mine was something along the lines of set `DELTA_PROBEABLE_RADIUS DELTA_PRINTABLE_RADIUS-40`. So it would account for the offset. then my left right front and back probe points were `-DELTA_PROBEABLE_RADIUS` and `+DELTA_PROBEABLE_RADIUS` respectively.
