### ISSUE TITLE
Reset printer statistic

### ISSUE THREAD

**Issue by Gaben5224** [MarlinFirmware/Marlin#6197]
Hey Guys!

Maybe it is a stupid question but, where or how could I reset the printer statistic datas?

Thanks for the answer!

**Comment by Bob-the-Kuhn** [comment]
A lot of times you have to dig into Marlin_main.cpp to get these kind of answers.

I did a search for **M78(** and found this nearby:
"M78 S78" will reset the statistics

**Comment by Gaben5224** [comment]
Many thanks Bob-the-Kuhn!!! I will try it.

**Comment by psavva** [comment]
@Gaben5224 if you test ok, please close this ticket

**Comment by thinkyhead** [comment]
We'll add `M78` to the RepRap wiki asap. And any other codes we forgot. (Usually we add new codes to the wiki before merging.)
