### ISSUE TITLE
BLtouch wont deploy unless Doubleprobe is turned on

### ISSUE THREAD

**Issue by chris-hemmings** [MarlinFirmware/Marlin#6206]
As the title says. My bltouch will not deploy unless i have Double probe turned on.
DELTA_PRINTABLE_RADIUS

With my probe being x-40 and Y-20 from the nozzle. will this account for the offset correctly. as i did a test before and lifted one side of the bed up 2mm, and it seemed as though the print was not adjusting correction on the first layer.. Im not sure on the best way to test this, but i have just tried a large cyliner to go around the edge, and its certainly not adjusting the height correctly. 
Could this be because my cylinder was outside the probe points? as my probe point has to be printable radius-60 because of the offset

I have set my offsets correctly in marlin.

my version is 

FIRMWARE_NAME:Marlin 1.1.0-RC8 (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Anycubic plus EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

**Comment by Bob-the-Kuhn** [comment]
Please see if [RCBugFix](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix ) solves this problem.  There's been a ton of corrections since RC8.

**Comment by chris-hemmings** [comment]
Do i use RCBugFix or do i use 1.1.0-RC8 "Woozy Wookiee" which is the latest?

**Comment by chris-hemmings** [comment]
> Please see if RCBugFix solves this problem. There's been a ton of corrections since RC8.

I have noticed these are the changes since Dec 6. I know my firmware is later than that, so are you sure that RCBUGFIX is later than my Marlin 1.1.0-RC8

RCBugFix

Fixed broken MBL
M600 heater timeout option

and these are the changes for Dec 6. Mine already has these changes built in.

RC8 - 06 Dec 2016

Major performance improvement for Graphical LCDs
Simplified probe configuration
Enable Auto Bed Leveling by type
Reduce serial communication errors
Make Bilinear (Mesh) Grid Leveling available for non-delta
Support for Trinamic TMC2130 SilentStepStick SPI-based drivers
Add M211 to Enable/Disable Software Endstops
Add M355 to turn the case light on/off and set brightness
Improved I2C class with full master/slave support
Add G38.2 G38.3 command option for CNC style probing
Add MINIMUM_STEPPER_PULSE option to adjust step pulse duration
Add R parameter support for G2/G3
Add M43 optional command (PINS_DEBUGGING)
Remove SCARA axis scaling
Improved sanity checking of configuration
Improved support for PlatformIO and command-line build
Usable DELTA_CALIBRATION_MENU
Support for Printrbot Rev.F
New and updated languages

**Comment by Roxy-3D** [comment]
> I have noticed these are the changes since Dec 6. I know my firmware is later than that, so are you sure that RCBUGFIX is later than my Marlin 1.1.0-RC8

Are you looking here???  https://github.com/MarlinFirmware/Marlin/tree/RCBugFix   Because I merged in a spelling fix 5 hours ago and that is not in your list.

**Comment by chris-hemmings** [comment]
​Ill give it a shot then. Thanks mate

I just wasn't sure on how to check that i had the absolute latest
​

**Comment by chris-hemmings** [comment]
just tested the latest bugfix and the bltouch probe wont deploy with probe_double_touch turned off

**Comment by chris-hemmings** [comment]
Ok. after turning on double touch, this happens. There is a noticeable delay before dropping the probe. 

Didn't happen on the last firmware.

Also, i have disabled the bltouch delay, and i have servo delay set to 300 which is standard.

Any ideas 
https://youtu.be/A9HXHkkHKtk

**Comment by psavva** [comment]
@wookie666 , the delay was introduced in this PR 
https://github.com/MarlinFirmware/Marlin/pull/6114 by @Bob-the-Kuhn 
And the delay is configurable via this PR
https://github.com/MarlinFirmware/Marlin/pull/6214

**Comment by chris-hemmings** [comment]
Yes I understand. I recompiled the firmware and commented out the bltouch servo delay and also commented out the servo delay that is down the bottom of configuration.h and my probe wouldn't deploy. So I put the standard servo delay back on but left bltouch servo delay commented out and it still had that delay. So which is it?

**Comment by psavva** [comment]
You should comment out servo delay, but set BLTouch delay with a logical value.
Try 375 milliseconds as it is by default, and if your able to configure it lower, all good.

Btw, if you comment out the BLTouch Delay, it will dynamically be defined to the default 375ms value.

Do you see that the delay is too long now?
It is required on some BLTouch modules.

**Comment by chris-hemmings** [comment]
I'll test it in about 10hours and see. Thanks
