### ISSUE TITLE
Marlin ramps 1.4 plus

### ISSUE THREAD

**Issue by tiestononstop** [MarlinFirmware/Marlin#6216]
Cual es la última versión para una placa ramps1. 4plus?

What is the latest version for a ramps1 board. 4plus to compile direct?

**Comment by Bob-the-Kuhn** [comment]
Marlin doesn't officially support this board yet.

PR #5695 has been started to add this board to the ones supported by Marlin.

You could probably grab the **pins_RAMPS_PLUS.h** file from the PR and work with that.
