### ISSUE TITLE
MESH appears broken after commit 9e22184

### ISSUE THREAD

**Issue by WheresWaldo** [MarlinFirmware/Marlin#6230]
Decided to go back to MESH leveling since U.B.L. is not just bleeding edge but appears to be bleeding at the moment. But the latest RCBugFix seems to have butchered MESH. Here is what I am seeing since the introduction of the U.B.L code:

1. Mesh seems to ignore any offset either placed in **Z_PROBE_OFFSET_FROM_EXTRUDER** or using **M851** or using **G29 S4 Zn.nnn**
2. When trying to create a MESH **LCD_PROBE_Z_RANGE** appears to be ignored and all MESH probe points seem to start at 0.200 mm, previous iterations would start at the value specified in **LCD_PROBE_Z_RANGE** which used to be **MESH_HOME_SEARCH_Z**
3. Babystepping appears to have no effect on layer one height (this needs more testing, but I reverted back so I am not in a position to double check).

The reason I believe the integration of U.B.L is creating this abnormal behavior is that MESH was working fine on a snapshot of RCBugFix I have from March 15th

**Comment by epatel** [comment]
Looks like something happened in this commit https://github.com/MarlinFirmware/Marlin/commit/9e221849365d2ad22662687ee3338a18652751a6
