### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by tjp2579** [MarlinFirmware/Marlin#6235]
I am getting this error please help im having no luck about to give up cant get pronterface working can configure marlin F*** 3d printing in to stupid to figure this out 
![screenshot 38](https://cloud.githubusercontent.com/assets/24399719/24635923/ab8fd40e-18a4-11e7-9069-fb1a3a462257.png)
![screenshot 37](https://cloud.githubusercontent.com/assets/24399719/24635934/b003515a-18a4-11e7-8021-91afca6ed72c.png)

**Comment by tjp2579** [comment]
Also cant get my reprap LCD to work also just a blue screen and I turned it on in marlin I was able to compile the marlin config.h one or two times a hundred downloads of different pythone and other stuff people say to try thought this would be fun :(

**Comment by tjp2579** [comment]
I have a reprap DIY kit from amazon i3 with [Sintron] Ultimate 3D Printer Full Complete Kit for DIY Reprap Prusa i3 + RAMPS 1.4, Mega 2560, MK8 Extruder, MK3 Heatbed, Stepper Motor and LCD Controller except I upgraed to the reprap graphic smart controlle

**Comment by Dreamloom** [comment]
Have you tried emailing Sintron? They advertise pre-configured Marlin firmware to load on their kit printers: sales@sintron-hk.com  - sounds like that might cure your headache. They should be able to send you a link to download it.

**Comment by tjp2579** [comment]
Thanks, I have tried that. I don't know what's wrong I tried deleting all
Marlin files and starting over. I wish I could figure this out.

Best Regards,

Toby Protsman || Student Government || Computer Club || Admissions
Ambassador

**Comment by Dreamloom** [comment]
You have an unmodified copy of the Marlin firmware files from Sintron? Ones you haven't changed? Can you post the configuration.h here as a .txt file so the real experts can look it over? Also: is your Ramps Extruder/Extruder/Bed, Extruder/Fan/Bed or what configuration? As for the LCD, do you have Reprap Discount Full Graphic Smart Controller?

**Comment by tjp2579** [comment]
Fan/extruder/bed and I down loaded the copy of Marlin from The Marlin
website. Still waiting to hear from starion I emailed them again today.
Thank you for your time to help me much appreciated.

Best Regards,

Toby Protsman || Student Government || Computer Club || Admissions
Ambassador

**Comment by tjp2579** [comment]
I'm sorry not at home to get the text file copy for you will be after 6pm
Eastern time

Best Regards,

Toby Protsman || Student Government || Computer Club || Admissions
Ambassador

**Comment by tjp2579** [comment]
Sorry here is my controller

Best Regards,

Toby Protsman || Student Government || Computer Club || Admissions
Ambassador

**Comment by teemuatlut** [comment]
Please post your configuration.h and configuration_adv.h here (rename the extensions to .txt).

Which version of Marlin are you running? The latest RCBugFix?

**Comment by ghost** [comment]
BOARD_RAMPS>I am getting this error please help im having no luck about to give up cant get pronterface working can configure marlin F*** 3d printing in to stupid to figure this out

Calm down a type clearly will help us help you.
It looks as though you don't have the motherboard set correctly.

In `Configuration.h`, change the board name or number to the one you found in the `boards.h` file that matches your setup.
  #define MOTHERBOARD _**BOARD_RAMPS_14_EFB**_

**Comment by tjp2579** [comment]
Ok just got home from work I just deleted any files I had downloaded for this let's start fresh what's first Marlin?

**Comment by tjp2579** [comment]
Were should I save it on desktop or in default program file

**Comment by ghost** [comment]
Desktop is fine for now.

**Comment by tjp2579** [comment]
That is the first file I should start with or adrunio first I deleted everything

**Comment by ghost** [comment]
>what's first Marlin?

Editing the `configuration.h` file.

**Comment by ghost** [comment]
You need the Arduino IDE to compile and send the program to the controller.

You can edit the `configuration.h` file with whatever text editor you choose. Can also edit in the IDE.

**Comment by tjp2579** [comment]
And Python I had someone tell me to download a bunch of Python files

**Comment by ghost** [comment]
Python has nothing to do with this. No need for it.

**Comment by tjp2579** [comment]
Ya im kinda puter savy but this has me stumped

**Comment by ghost** [comment]
Python is another programing language. Not Arduino.

**Comment by ghost** [comment]
Arduino is roughly based on C++.

**Comment by ghost** [comment]
I am headed to work now.... I will help when I can. (via phone).

**Comment by tjp2579** [comment]
God I hope you get this going I'll love you forever​ lol I was so excited and now the spark is gone now it's fustration

**Comment by tjp2579** [comment]
Oooo nooo

**Comment by tjp2579** [comment]
Should I download Marlin for GitHub or there sight

**Comment by ghost** [comment]
I'm not _quite_ gone yet. lol

**Comment by tjp2579** [comment]
Ok have Marlin and Andunio  downloaded no I have configuration.h open set to my board next is my LCD and that should do it or what is next

**Comment by ghost** [comment]
Go here:
https://github.com/MarlinFirmware/Marlin/tree/RCBugFix

And download as ZIP.

**Comment by ghost** [comment]
That would be the lastest _bleeding_ edge code.

**Comment by ghost** [comment]
Without your old config files, the process of setting up your printer correctly will take more time because things will have to be figured out.
Unless someone here might have the same printer as you do and could provide their config files for you to start with.

**Comment by ghost** [comment]
If it has to be done the hard way, someone here smarter than me, might provide the directions to find the steps/mm for your printer.

Although, you could take the chance and see how close the default values are.

**Comment by ghost** [comment]
I gotta get. I'll be around. I'll help where I can.

**Comment by tjp2579** [comment]
reading the config. file on marlin webpage ill fallow that

**Comment by tjp2579** [comment]
It compiled no LCD display though whats next to get this thing moving?

**Comment by tjp2579** [comment]
[config.txt](https://github.com/MarlinFirmware/Marlin/files/894693/config.txt) this is my config.h file I have a reprap Full Graphic Controller with just a blue screen

**Comment by tjp2579** [comment]
Help please if someone is out there

**Comment by tjp2579** [comment]
now I tryed changing some setting the recompiling it and now im getting a error exit status 1

**Comment by tjp2579** [comment]
got it moving guy thanks for all your help still dont have a LCD ill work on that later

**Comment by ghost** [comment]
Watch this video. He will give you a better understanding of Marlin's setup.

https://youtu.be/3gwWVFtdg-4

**Comment by tjp2579** [comment]
Thanks watched it a hundred times

**Comment by Bob-the-Kuhn** [comment]
He has a "smart adapter" to interface the two LCD cables to the RAMPs card.  Does anyone know if changes to the pins_RAMPS.h file are needed or is it plug & play?

**Comment by tjp2579** [comment]
Im getting this error with prontoface 
![screenshot 39](https://cloud.githubusercontent.com/assets/24399719/24686218/6e6cde14-1980-11e7-8126-6846adf48c01.png)

**Comment by ghost** [comment]
Before you jump that far... Get connected to your printer and verify endstops are good and motors move the correct direction, etc.

Do this before worrying about any slicer yet.

**Comment by ghost** [comment]
I saw tjat you have pronterface's baudrate lower than Marlin's default.
Default speed is 250000.
The baudrate needs to be the same on both ends.
(i.e. Marlin <-> Arduino IDE, or Marlin <-> Pronterface)

**Comment by tjp2579** [comment]
Ya I changed the baudrate on both I got a error said it was to high

**Comment by ghost** [comment]
That's odd. I run 250000 on a 6' usb cable with no issues.

**Comment by tjp2579** [comment]
You have the same setup as me
