### ISSUE TITLE
extreme overextrusion after first printjob

### ISSUE THREAD

**Issue by azalanono** [MarlinFirmware/Marlin#6237]
I have a reproducable problem on my Marlin RC8 based 3D printer.
While the first printjob works fine, any succeeding job does normal moves, but does extreme over-extrusion in skirt. I can retry as often as I want, the behavior does not change.
I found out that restarting Marlin (a disconnect and re-connect forses a firmware-reboot) and then starting the same job makes it print (once) correctly. Because of the fact that a restart of Marlin fixes the problem for one printjob, it is almost clear that Marlin is the problem, as the used gcode is pretty simple.

I use OctoPi as print server.

![example](https://cloud.githubusercontent.com/assets/25666697/24644443/e89e626a-1913-11e7-96ec-8543751a4b58.jpg)

This is the used GCODE (Only the initialisation part and ending part of code.
[Example.txt](https://github.com/MarlinFirmware/Marlin/files/892223/Example.txt)

**Comment by ghost** [comment]
It may also be the extruder stepper driver losing control.
Could also be a bad connection with that driver.
Could also be a bad connection to the extruder motor.

To eliminate Marlin as the issue, download a fresh copy of RC8 or RCBugFix.

**Comment by Sebastianv650** [comment]
For me it's very intresting that the massiv blobs mostly happens in the arcs, not the straight lines. Have you accidently enabled LIN_ADVANCE with a wired K value?

But this doesn't explain why it's only after a finished print..

**Comment by thinkyhead** [comment]
@azalanono Have you tested the current `RCBugFix` to see if the problem still exists?

**Comment by knobik** [comment]
Im having the same problem, reproduced it 2x, will try RCBugFix today after work.

**Comment by knobik** [comment]
RCBugFix fixed that problem for me.
