### ISSUE TITLE
Raise Z before travel?

### ISSUE THREAD

**Issue by dalich** [MarlinFirmware/Marlin#6239]
Is there a way in RC8 to raise the Z axis before travel. The nozzle leaves little lines on the print surface and sometimes may hit a random chunk on the print causing issues when travel from one position to another.  Seems like this was a feature in the previous versions and it would be useful in my situation.

**Comment by Sebastianv650** [comment]
I think most users who want a z-hop use the slicers option to adjust it. But if you enable firmware retract and set a value for z lift Marlin can do it also, it has not changed in the last time.

Remeber to also activate firmware retraction in your slicer to use it.
