### ISSUE TITLE
Printrboard SD support - pin numbering 

### ISSUE THREAD

**Issue by Hazeree** [MarlinFirmware/Marlin#625]
Tracked down a commit on December 8th, 2012 where printrboard pins.h and fastio.h had gone and renumbered all the pin definitions for the Printrboard motherboard. But the SD2pinmap.h file is unchanged, which should mean that the #define SDSUPPORT will use the old pin numbering for at least SDSS, SCLK, MISO, and MOSI. Also, the entire pinmap in the SD2pinmap.h file is unchanged and different than the new pin numbers. I don't know if that has any real effect, but in order for me to enable SD support, I had to revert all files back to the older pin numbering. The new pin numbering conflicts with all (albeit sparse) documentation for adding LCD and SD support to the printrboard (lincomatic, thiink3dprint3d, etc).

**Comment by thinkyhead** [comment]
Connecting this issue to #2970 as we work on converting `SD2lib` to use `fastio.h` and direct pin manipulation.

**Comment by jbrazio** [comment]
Followup this issue in #2970.
Proposal fix: #4419.
