### ISSUE TITLE
Reprap full graphic controller Blue screen

### ISSUE THREAD

**Issue by tjp2579** [MarlinFirmware/Marlin#6250]
I have set marlin to reprap full graphic controller and I still have a blue screen anyone help would be greatly appreciated.

**Comment by tjp2579** [comment]
Ok I got a display now but it just says Marlin on the face of my LCD shouldn't I get a control screen

**Comment by ghost** [comment]
Make sure your 5vdc is good.

**Comment by tjp2579** [comment]
what my power supply for the lcd

**Comment by ghost** [comment]
Well, the 5v comes from a volage regulator on your control board.

What motherboard do you have?

**Comment by ghost** [comment]
Your endstops are a good place to check for 5vdc.

**Comment by tjp2579** [comment]
ya im getting 5vdc to my endstop

**Comment by Bob-the-Kuhn** [comment]
When using the USB port, is the controller responsive?  

I'm wondering if the controller is hung which might explain why the LCD is stuck at the startup screen.

If the controller is hung try changing TEMP_SENSOR_0 to 998.  The controller will hang if a sensor reading is way too high or way too low.

**Comment by tjp2579** [comment]
Thanks for all the help I got it now

**Comment by Bob-the-Kuhn** [comment]
What did it take to get it running properly?

**Comment by tjp2579** [comment]
Me to send it back and but a day Vinci pro 1.0 lol
