### ISSUE TITLE
Marlin Freezes when M106 S-val is a Float

### ISSUE THREAD

**Issue by jakeread** [MarlinFirmware/Marlin#6255]
in Marlin_main.cpp at line ~ 5535
RCBugfix 
```
  inline void gcode_M106() {  
    uint16_t s = code_seen('S') ? code_value_ushort() : 255,  
             p = code_seen('P') ? code_value_ushort() : 0;  
    NOMORE(s, 255);  
    if (p < FAN_COUNT) fanSpeeds[p] = s;  
  }
```

with this gCode,

```
G1 X87.458 Y174.450 E0.88652 F1890.000
G1 X86.129 Y173.718 F12000.000
G1 X76.290 Y163.879 E0.73224 F1890.000
G1 X77.357 Y165.543 F12000.000
G1 X84.465 Y172.651 E0.52899 F1890.000
G1 X81.407 Y170.189 F12000.000
G1 X79.817 Y168.599 E0.11833 F1890.000
M106 S107.1 ; <------------------------- *sirens*
; before layer change
G1 Z11.400 F12000.000
; after layer change
G1 E-0.75000 F1800.00000
```

and this gCode,

```
G1 X102.753 Y158.403 E0.11293
G1 X102.669 Y158.939 E0.02960
G1 X103.668 Y159.938 E0.07714
G1 X103.094 Y159.983 E0.03146
G1 X102.500 Y159.388 E0.04590
G1 X102.264 Y159.772 E0.02458
G1 X102.477 Y159.985 E0.01650
M106 S112.2 ; <------------------------- *airlock breached*
; before layer change
G1 Z1.550 F12000.000
; after layer change
G1 Z4.550 F12000.000
```

Extremely repeatable - down to the line - this is where it hangs.

I'm going to assume this is not common - something else must be going on in my machine (independent dual extruder... lots of strange things in the config. However, this is a super repeatable error for me - if I EVER send gcode with an M106 S- where the S-val is a float, motion immediately becomes 'clunky' and the planner clogs up.

Not too urgent, lots else to do, but I thought this might be an interesting bug for someone who is also troubleshooting.

**Comment by Bob-the-Kuhn** [comment]
I can't reproduce your problem.

I just copied & pasted your sequence into Repetier Host without any complaints.  I also added some print statements to M106 and the decimal points are stripped off S & P before they're used.

Do you have to be printing to see it?

What host are you using?

What version of Marlin are you using?  I was using RCBugFix from 2 days ago.
