### ISSUE TITLE
Support for Arduino Due (ARM processor)

### ISSUE THREAD

**Issue by alexborro** [MarlinFirmware/Marlin#626]
Hey guys, sorry using this channel to ask something like this, but did someone try to port Marlin to Arduino Due (ARM processor)??

If not, any guess about what should be done and how much effort??

Thanks.

Alex.

**Comment by zetousse** [comment]
hello. 

I'm trying to develope a polar 3d printer with 32 bits board. 

My board is a Duet and I want to install in it Marlin Firmware. 

Where can I found information about it?  

Thanks

**Comment by tonnico** [comment]
I don't think that there is a Duet-Version. bobc made one for the Due with RAMPS-FD and RADDS. But I don't know if this can also works for the Duet.

**Comment by zetousse** [comment]
thanks, 

I'm thinking about test it in my board, but i'm not pretty sure

**Comment by thawkins** [comment]
I have a due and a ramps-fd, and a spare printer chassis.

In a few weeks i will have time avsilable to start some testing, im preping
for a trip to japan at the monent. If somebody can point me at the required
bits and pieces, so i can start reading.

**Comment by Drakelive** [comment]
I know that the first version of the FD Ramps has several Bug Hardware and oversights. I think we should at least wait for the second version or select another board. 
I think having a version of Marlin based on Arduino DUE is really important and necessary.

**Comment by nicksears** [comment]
Anyone try SMART ramps yet? Just a mod of ramps with 3v logic I believe. I
have one, just no time to test.

http://reprap.org/wiki/SMART_RAMPS

**Comment by tonnico** [comment]
Just update the complete old bobc-fork to the actual version.
I disclaim the complete 8bit-part and removed most of them.

The rest is close to the actual version. Fork-date from 8bit was yesterday evening.
Maybe we make a new ARM-branch?

https://github.com/Wurstnase/Marlin/tree/Marlin4DueRework

**Comment by thinkyhead** [comment]
@Wurstnase I have been reading through the code changes in your branch. It is all very intriguing. With other versions of Marlin underway, it's hard to know whether this new branch will be maintained. Not that Marlin has not had stale branches before, but I personally hope that any new branches will be able to contribute code back to the main branch. Do you foresee the new Marlin branch having very close parity with Development / Stable, or do you think the Due version will tend to diverge?

**Comment by tonnico** [comment]
@thinkyhead I think that the maincode will not change for the Due version. Else it's not anymore Marlin. 

For maintaining we must encapsulate the AVR and ARM-code. bobc starts with a HAL.cpp. The ISR-part is not a big problem. The temperature-part is atm just some `#ifdef` which i don't like.

There are some other ARM/AVR parts, mainly in the SDcard-sections which needs a rework.

Also we need some renamings because some functions have the same name which are in some libraries of the arm-tree.

While I'm just a mechanical engineer and only can read most complexe code but have less expierence in programming, I would need some help in that case.

**Comment by JustAnother1** [comment]
@Wurstnase What is the benefit of having a Firmware "that is Marlin" but runs on a ARM chip?
Why would one want to have a Firmware that has (only) the same features as Marlin running on an ARM?

Did you see this comment(in this issue a bit upwards)

> ErikZalm commented on 17 Oct 2013 
> Porting marlin to a due is easy. But it is will not add new functions. (I did a port to a STM32F4 in a week)
> Using the added processing power is the difficult part. 

And if you add features to the ARM Version that the AVR version does not have then the two branches(ARM/AVR) will move apart very fast.

I'm not against a new ARM Firmware. I'm just saying that I agree with Erik van der Zalm that a ARM Firmware should use the benefits that come with being an ARM Firmware.

Could you please explain your Idea of this HAL for AVR/ARM. Maybe I can then understand it better and help you implement it.

**Comment by alexborro** [comment]
I see one benefit of ARM.. The more horse power make it possible to run
faster stepper timing (today's avr limit is 40khz).. And get rid of hiccups
on Delta + LCD...

By the way, we cannot run Graphic LCD on Delta bots just because we do not
have a faster cpu than 20Mhz.

That is just some advantages having faster Cpu with no added feature.

Cheers.

Alex.
Em 05/03/2015 19:41, "Lars Pötter" notifications@github.com escreveu:

**Comment by bobc** [comment]
"an ARM Firmware should use the benefits that come with being an ARM Firmware"

There is no such rule, but obviously to get to the benefits of ARM you first have to start with something running on ARM. There has been a lot of talk about creating new ARM firmware but a lot less people doing it. RepRapFirmware for Duet is about the only genuinely new ARM firmware, Smoothieware derived from GRBL.

Anyway, the ARM port is done, I've been using it months. It would be good to bring it up to date with latest Marlin, although I've not found anything new I need.

I'm not sure what the best way to do that is, I thought one way was to keep both ARM and AVR in parallel, but that needs people to want to maintain both ports.

@Wurstnase ARM only method may be as good as any, although I can't see how it has been branched. It might indeed be best to throw off the baggage of AVR and catch up with other firmwares that are now more advanced, with 3rd order motion, proper Delta calculations.

**Comment by AnHardt** [comment]
@Wurstnase 
Go for it!
Speed is a value for its own, if you'v ever (not) herd a printer with more than 16 micro steps and proper bearings. 
At the moment Marlin is the fastest developing firmware. Marlin has a good reputation. Marlin is the base of a lot of experimental forks. Marlin is at the pulse of time.
OK, the code is a mess. It's nether very clean nor easy to understand - but we are working on that.

Due and RAMPS-FD are here, RADDS is ordered. I'll work on your port, but let me first finish the advanced language support.

off topic:
A dual extruder x-sled with inductive probe for the spark-cube would be great.

**Comment by tonnico** [comment]
@bobc thanks for the realy good starting point for the ARM port. 

Yesterday I take again the hole Marlin and make the port complete. The actual version you can find on my repository [Marlin4Due](https://github.com/Wurstnase/Marlin4Due). Only issues I found are the missing port for watchdog and the timing for the RADDS-Display isn't ready.

Features are:
~10x faster for single-stepping rates up to 96k
smoother temperature because the ADC of the Due with 3.3V isn't that much stable at high temperatures.

Why those hi step-rates? Because I'm using stepper drivers with 1/128. On my CoreXY I run with 320 steps/mm (1/64) without any issue with 500mm/s with 3000acc. This is so silence that I can hear some clicking noises from my slide bearings.

One other advantage is the 32bit interrupt. With that you can also run very slowly. Also with a prescaler of 2 you can go in theory 1/102 steps/s. Marlin8bit with 16bit timer can only handle 30.6 steps/s at minimum.

**Comment by Itsmeiam** [comment]
Hi there
I get an error on compilation.
stepper.cpp: In function 'long unsigned int calc_timer(long unsigned int)':
stepper.cpp:180:23: error: 'DOUBLE_STEP_FREQUENCY' was not declared in this scope

I search for defination of DOUBLE_STEP_FREQUENCY and dont find in the hole sketch. 
Whats about that? 
I compile with the delta files, did delta not work for DUE at this time?

Greets
Tim

**Comment by tonnico** [comment]
Report issues please on Marlin4Due. 

The Double_step should be in the config_adv. Take a look at the standard ones and compare them. I don't have a Delta to test it, but it should work.

**Comment by tonnico** [comment]
@Itsmeiam Delta-settings now should work. Please test it.

**Comment by Itsmeiam** [comment]
Ok cool it works. Can read temps and start heaters and homeing also works. But home is on 
x-90 y-90 z0 and i dont find why since i have changed xy minmax to +-80. Also checket the manual pos option.

**Comment by Itsmeiam** [comment]
Thanks by the way ;-)

**Comment by Itsmeiam** [comment]
Ok cool it works. Can read temps and start heaters and homeing also works. But home is on
x-90 y-90 z0 and i dont find why. They should be at x0 y0 z 243.

**Comment by Itsmeiam** [comment]
And thanks by the way ;-)

**Comment by Itsmeiam** [comment]
Sorry it was a failure on my side in the software config.

**Comment by tonnico** [comment]
Most stuff is done.

I've rewrote the stepper.cpp especially the timer() and the lookuptable. This works now with 32bit.
Next I want to rewrite the ADC to have a close access to the registers etc.

**Comment by nophead** [comment]
Due has a Cortex-M3 processor which has hardware divide instructions taking a maximum if 12 cycles so using a lookup table to do the rate to period calculation is probably not necessary and may even be slower.

**Comment by alexborro** [comment]
I agree with Chris.

Get rid of the lookup table.

@Wurstnase,  do you have Skype or hangout ? I have some ideas about 32 bits
firmware and wonder we can help each other.

Cheers.

Alex
Em 21/04/2015 12:30, "Chris" notifications@github.com escreveu:

**Comment by tonnico** [comment]
@alexborro Maybe this evening, in 3 hours or so...
@nophead On my first tests the lookup table was 2 times faster, but this is some weeks ago and maybe there were some bugs. I will test it again.

**Comment by alexborro** [comment]
@Wurstnase I don't have your contact.

Send me an email: alexborro@gmail.com

Cheers.

Alex.
Em 21/04/2015 13:30, "Wurstnase" notifications@github.com escreveu:

**Comment by nophead** [comment]
Surprising because it isn't a simple lookup. It is lookup of two values plus interpolation.

**Comment by tonnico** [comment]
But the lookup procedure is effective. It just shift the pointer and add the values.

**Comment by nophead** [comment]
It does shifts and masks, calculates an address, two lookups, a multiply and an add versus a single instruction, although it is a long one at 12 cycles. The difference can only be fractions of a micro second anyway at the clock speed of the Due, so I would go with the simple solution, which is probably more accurate.

Also from your previous timing results on the acceleration, which didn't seem correct, perhaps your timing method is not right.

**Comment by tonnico** [comment]
```
#elif defined(ARDUINO_ARCH_SAM)
  timer = HAL_TIMER_RATE / step_rate;
#endif
```

this is the line from bobc.
My guess, HAL_TIMER_RATE is a float and the compiler calculate with float division in the past which makes it so slow.

**Comment by nophead** [comment]
Yes if  HAL_TIMER_RATE is a float it will be slow. It will need to be a 32 bit word to use the single instruction. A cast would fix it if it really needs to be defined as a float.

**Comment by tonnico** [comment]
in planner its a float
in stepper long

**Comment by tonnico** [comment]
yeah! the stupid float was the problem.

**Comment by tonnico** [comment]
I reached 150kHz in single step... Nice one.

**Comment by AnHardt** [comment]
:clap::clap::clap::clap::clap::clap:

**Comment by tonnico** [comment]
Just started to be familiar with assembler. But this now was too easy.

**Comment by boelle** [comment]
Who is working on this one? @Wurstnase ??

**Comment by tonnico** [comment]
Right.

**Comment by boelle** [comment]
you have an invite as collab... if you accept it you or i can put your name next to the issue

**Comment by tonnico** [comment]
At the moment I only copy the new stuff from 8bit to my repository. Most parts work.

It's actually not my goal to combine both versions. This needs many resorts. ADC, interrupts, pins, fastio and some functions. For example there is no `tone()` for the Due.

**Comment by boelle** [comment]
i can never be totally the same :-)

**Comment by AnHardt** [comment]
@Wurstnase 
Sorry for the `tone()` i did not know.
After the latest changes where the pause was reintroduced, `tone()` has no advantage over the set-delay-reset-delay-loop i removed. So feel free to reintroduce the more universal beep-loop.
My idea was mainly to centralize the former 3 places where beep-code was distributed - and `tone()` looked sufficient.

**Comment by tonnico** [comment]
@AnHardt no worry about the `tone()`. I take the solution from Repetier with an ISR for it. Now the Due version has also a `tone()` :)

But this is a perfect example why not merging them together. Most of you will program AVR and not ARM. That's good but will break some code.

**Comment by thinkyhead** [comment]
Should we now add a block with `#ifndef tone` and implement `tone()` with the set-delay-reset-delay code, just for those cases when it doesn't exist?

**Comment by tonnico** [comment]
No, it's only the ARM-part.

**Comment by Drakelive** [comment]
Hello

I could not follow you a bit of time .......
Any news on this topic? Arduino Core for DUE (Sam) has long been included in the Arduino IDE .........
I have a FD Ramps although the first version has some issues is a card that is well suited for the development ........

Anybody out there working?

I await your news......
Best Regard 

Thanks
Drake

**Comment by tonnico** [comment]
Sure... But take care with that. I don't have a RAMPS FD and can't test it.
https://github.com/Wurstnase/Marlin4Due

**Comment by Drakelive** [comment]
In recent weeks I have seen the birth of several boards based on ARM chip. I believe this is a natural evolution for the control of 3D printers. These chips are much more powerful, faster and have a lot of memory. Marlin Firmware must have support for ARM chips.

From what I could see in the web there are projects based on chip Sam, NXP, STM32.

[1] Bobc and Wurstnase has a fork funzinante (works right?) for Arduino DUE
[2] MakerLabMe has a fork for STM32 including Arduino Core STM32 [3]

I believe that the fork for Arduino DUE of bobc could be included in MarlinFirmware immediately. Is enough to have a special Shield (Ramps FD). FD is economic and today we can find on the web very easily.

I admit that the fork for STM32 I like a lot. They have many advantages. They are cheap but much more powerful Arduino Mega. I think it would not hurt to have a Shield for STM32 Core. This familiars of cards are cheap (about 10 dollars) and have a standard format (Pin Morpho) which effectively makes all compatible. Unfortunately, to date we lack Shield but I also believe that it is not so hard to deliver it.

I would understand if Marlin Firmware plans to support ARM chips and in what timeframe.

Greetings
Drake

[1] https://github.com/bobc/Marlin
     https://github.com/Wurstnase/Marlin4Due
[2] https://github.com/MakerLabMe/Marlin_STM32
[3] https://github.com/MakerLabMe/STM32_Arduino_Cores

**Comment by bobc** [comment]
I'm currently designing an STM32 controller, so will be looking to port
Marlin to it. I'm also looking at adapting RAMPS-FD for boards with Uno
type footprint, e.g the Nucleo boards.

One of the keys things I did in my fork was to try to create multiplatform
support via a HAL layer. I am disappointed that wurstnase made his fork
specific to Due, there are many other ARM chips apart from SAM3X! It would
be create if we could move to a portable version of Marlin which works on
other ARM chips.

**Comment by AnHardt** [comment]
@Wurstnase 
We are glad you are supporting DUE actively.

( Der Spatz in der Hand ist besser als die Taube auf dem Dach )

**Comment by fmalpartida** [comment]
Very interesting thread. 
One of the items we discussed as part of the code refactoring was precisely to include a HAL which is the way to go to be agnostic of the HW. 
Very interesting to see how it evolves.

**Comment by scotty1024** [comment]
Bob,

So ARM chips have horsepower enough to burn some up in a HAL but the AVR's don't e.g. pins.h. What are you proposing to crack that nut?

**Comment by Drakelive** [comment]
@bobc why use the footprint of Arduino UNO? There are few pins? Is not it better to use the Morpho? Perhaps it is also compatible on the STM32 Discovery but now I'm not sure I need to check.

**Comment by bobc** [comment]
Wow, that is is pretty ungrateful, seeing as I did the ground work for
Wurstnase.

Sometimes I wonder why I bother. I won't be contributing further.

**Comment by giutrec** [comment]
@bobc Your idea to make compatible more ARM platform (apart from SAM3X) via HAL layer is great!
But could you think to resolve a more difference of the HAL implementation by many manufacturers?

But If needed I could help you to converting (hardware, my C are poor ) your RAMPSFD to Nucleo/Discovery platform.

**Comment by scotty1024** [comment]
Bob,

You did say "try to create" not "did create". Sometimes people decide to quit trying and go ahead and do to show things can work.

If I'm not mistaken the primary reason we don't see Erik around here much is his belief that to do ARM properly required so many changes to Marlin that it wouldn't be Marlin anymore so he did a new code base for his ARM board.

**Comment by thinkyhead** [comment]
> Wow, that is is pretty ungrateful, seeing as I did the ground work

I'm one among many grateful @bobc ! Please don't let one cloud on the internet make a storm. I learn so much from everyone here in Githubland and value the sharing of experience and skill. I am naive enough to believe that a HAL (or some hybrid of conditional compilation and abstraction) can exist and be pretty optimal, with creative coding. And even without, the scope of Marlin isn't all that daunting, when it comes down to it. There's a lot of room for building on Marlin's core elements and evolving them with a forward view. And I think it's also worth exploring the idea to make a proper 3D printing class library for Arduino/RepRap that could be shared among open source firmware. I don't know where to begin with any of that, and have only 6 good typing fingers, but erik, yourself, and a few others have been putting in the time and work to figure it out, and altogether comprise many more phalanges.

The word on the street I hear – primarily from @ErikZalm – is that a complete rework of the code architecture makes a better basis to take full advantage of the expanded space and power. I haven't looked closely at the @bobc and @Wurstnase DUE forks, but I will soon!

My hope is that we can decide on a starting point, and see if there is some means of convergence between old Marlin and Marlin Due Extreme. For example, is it advantageous to wrap up the current stepper and planner into singleton classes, and to otherwise perform as much encapsulation on the current codebase as possible? And, how up-to-date are these DUE branches w/r/t the current HEAD? And, as the debate ensues, is it worth pursuing within the same code base at all?

**Comment by JustAnother1** [comment]
I think that @thinkyhead asks the right questions here. 

It is probably not the right solution for Marlin, but to get the Discussion about HAL going anybody interested can take a look at my (very unfinished) code: https://github.com/JustAnother1/pmc

The HAL has an API in "hal/include" it has a implementation for POSIX Systems in "hal/linux/" and a implementation for STM32 in "hal/st/stm32f4/" It also has a makefile(part) in "hal/"

Switching from one platform to the other is just a matter of changing a parameter given to the makefile. So if not the code, then this principle might be a useful stating point, at least for the discussion about how to integrate a HAL.

And @scotty1024 a HAL can also work on AVR. The trick here is to not have a HAL as an additional Layer that costs performance, but to move the whole driver level into the HAL. That makes a big fat HAL Layer (And that is a rather bad thing - more coding necessary) but costs much less performance.

I'm also with @ErikZalm here. I'm not sure if it makes sense to have a common code base for ARM and AVR. The ARM board probably want to have many new features pretty fast. Stuff that they can use their additional horsepower on. So the AVR version would be a version with 99% of the features deactivated. And I'm not sure that it is always practical to have that last percent in a way that is best for AVR. But maybe someone else has a good solution?

@bobc if you are still "trying" then please let me know. I work on something similar, maybe we can help each other out.

**Comment by fmalpartida** [comment]
From my point of view the HAL is just an abstraction "layer"/interface that decouples and abstracts you the underlaying hardware, which shouldn't add much overhead. In principle, there should be methods or functions to access the HW to a common interface. In the past I have implemented them several ways:
- through a pure abstract class that take on a particular "HW" instance.
- through common function calls acting as an interface that you specialise for your HW. 

One way to look at it is as a common interface to access the HW. Lets put a side the compilation tool chain.

If you look at the Arduino core library, in reality it can be considered as a HAL: regardless of the underlying HW you always call the same function to drive the IOs (for example).

Also if we look at the Marlin code, what we have is in some cases, calls accessing the native Arduino IDE, calls accessing the fastIO. This is just one example which doesn't help very much to port. While IOs a trivial, there are some HW devices that heavily rely on the Arduino IDE.

Fat? Well, lets take an example, the "New LiquidCrystal" library is a driver to control LCDs, regardless of how they are driven (I2C, SR 2 wires, SR 3 wires, SR 1 wire, parallel, ...) that uses an abstract class that "applications" use regardless and seamlessly. Only difference in the code is how LCD objects are created. It is very extensible and you can easily add support for other LCD drivers very quickly. And what is the overhead, well it is almost 4.5 faster than the stock Arduino LiquidCrystal. And that is comparing driving an LCD with 2 wires vs the Arduino parallel driver.

The bottom line is if we define a set of interfaces that model the current HW needs, it is a question of refactoring the main code base against that interface. In many cases, it will be a question of adding a function call overhead to the code. 
From there on, is a question of complicating things out more by building more complex objects, however, they would all be using the common interface. For example, a servo, a stepper. But this is a different topic.

Just by looking at the code, there isn't that many HW dependent calls, however, there are many implementations in it.
So, if we define a common interface to control: IOs, serial lines, I2C, SPI, (perhaps just a specialisation of a generic serial line) LCD (perhaps this could be one of the above "complex objects"), timers, interrupts, analog lines and even PWMs.
The work to introduce a new board would be to write its BSP (Board Support Package) against the interface and would simplify the task substantially, the current maintenance and indeed cross platform/architecture support.

I will take a look at the porting efforts and hope that the comment is very much aligned. I haven't seen it yet, sorry folks.

Cheers,

fm

**Comment by Drakelive** [comment]
Hello

It is clear that we are in a time of transition where old implementations begin to show their limitations in terms of speed and sometimes even usability.
Those who believed in the past to migrate ARM today is an advantage and also has the satisfaction of demanding users.

It seems a good starting point, logical and intelligent.
We separate hardware management from the rest of the project and put a common interface and standarizzata that works as a bridge. Then a layer of abstraction.
Each chip will have its own abstraction layer

Now let's talk about hardware.
Unfortunately, we must admit that there are many commercially Board with ARM chips and those found are very expensive. Let's face it the cost is a discriminating factor.
So we have to find a hardware platform that can serve economic development. A platform that will improve along the way.

Few posts ago I talked about STM32 Nucleo because they represent a family of ARM Board very cheap but very powerful.
It should be added only a Shield like RAMPS FD and you're done. This work should take very little time and the overall cost I guess is very low. This for me is the right choice.

As for Marlin we can go step by step.
We can initially create a new project called MarlinFirmware MarlinArm and begin to discuss the work to be done.

What do you think of this ? Do you like how Idea?

Cheers
Drk

**Comment by JustAnother1** [comment]
@Drakelive regarding prices:

On a CPU Board + Shield view:
An Arduino2560 + Shield is more expensive than an Nucleo + Shield (assuming same price for shield)

On a chip based view(for the integrated Boards):
A reasonably sized AVR chip is more expensive than many ARM Cortex-M processors.

Then there also low cost 32bit boards:
http://forums.reprap.org/read.php?13,473283

**Comment by thawkins** [comment]
What about devices like the raspberrypi2 quadcore ARM7 with 1G RAM
operating at up to 1Ghz. $35

With a suitable "hat" attached it can also drive a set of stepper drivers
and other logic.

Beagle Bone Black, single core, but with two PRU's for custom pwm or step
pulse generation.

Both above run linux, and have ethernet and gpio, and support eitye hdmi or
direct lcd touch pannels.

The big plus on ethernet iscthat the firmware can operate its own mini
webserver for firmware configuration, operation and monitoring.

**Comment by scotty1024** [comment]
Hi Drake,

The existing AVR libraries that Marlin uses for its basic tasks were all bundled up GPL friendly by Arduino not Atmel. The Nucleo platform is direct from STM with no one such as Ardunio washing it to be GPL compatible. Detest the Due all you want but it's Ardunio and has a known FOSS Eco-system around it.

The Smoothie folks stumbled early on with the mbed licensing. I believe they got moving again by replacing certain bits of the mbed libraries for their chosen chip. Is this an issue for the Nucleo board? I know it isn't an issue for the Due, any code the Due needed was written and FOSS'd.

Any HAL Marlin comes up with will be a routing layer to a collection of libraries supplied with the underlying board. One example is SDCard access. Will Marlin continue using the limited Arduino Eco-system SDCard code for reading and writing files? 

I hope not! 

But since an AVR can't use anything better, the HAL layer has to be above the filesystem level with the Marlin code above the HAL flexible enough to deal with sucky AVR file access and modern file access on ARM.

So in answer to your query? No, I'm not sold on your Nucleo proposition yet. Nor do I think the HAL is going to be a simple proposition.

**Comment by Drakelive** [comment]
I know that some projects using Raspberry PI or Beagle Bone Black, thanks to an OS (linux).
In these applications requiring precision and simultaneous movement of the axes and the reliability this provides realtime OS just as in the case of LinuxCNC. I know that is not the same thing but ST offers a completely free RTOS.  Unfortunately I am not the right person to work on RTOS and realtime systems.

There are problems to release GPL Code of STM32? Even if we compile with ArmGcc Toolchain?
There are problems to use directly (or indirectly) libraries CubeMx of ST?
ST for the Nucleo board provides libraries for managing USB sticks but I do not know if there are any licensing restrictions.
I certainly did not think to use the STM32 Nucleo  by mbed !!!!

The truth is that I own several STM32 boards ( Nucleo and Discovery ) and a Ramps FD modified..
I would like from this but am open to good ideas.

Drk

**Comment by tonnico** [comment]
@bobc Ungrateful? You made a great job! And I tried to continue this work. This stood still for month. First I took the actual 8bit stuff in your fork and after that I tried to get as much as possible speed out of that. That's all!

So my repository is yours just with an update and a speed upgrade.

Anyway, this is just a small hobby for me. I started with C/C++ and ARM-coding ~4 month ago? I've got an Arduino Due and a RADDS and there where only Repetier which works for me. But I want to use Marlin. I have no experience with other hardware and I'm happy that I begin to understand some register pushings on the SAM3X. So if you @bobc or any other guy (girl) want to go further with that, come on! Let's go! I'm the last one who want to make a one man show.

**Comment by thinkyhead** [comment]
> I'm the last one who want to make a one man show.

You, me, and Andreas are just about the only ones who can code around here.
So how about a 3 man show?

**Comment by tonnico** [comment]
@thinkyhead Sure ;) I mean the 32bit part. But technically I'm 100% on your side.

CMSIS and libsam is as far as I know the only way apart from the arduino system, for the Arduino Due.

**Comment by fmalpartida** [comment]
I can code too, but very little time available... Too many compromises, the biggest is the family. 
I can help out if needed.

**Comment by thinkyhead** [comment]
:facepunch:
:mag_right: The game is afoot! :mag:

**Comment by scotty1024** [comment]
Drake,

Yes, the Smoothie folks ran into licensing issues with STM32. If you want Nucleo in the running you might want to reach out to STM and ask them how much of their HAL is GPL compatible. GCC tool chain provides GCC libraries not STM libraries. As you mentioned: USB operations, boot strap, configuring timers etc... Lots of STM specific things needed.

STM provides a HAL that they use to get to the right stuff for each of their STM32 chips. The Marlin HAL would build on top of that and the Due libraries.

**Comment by a4jp-com** [comment]
Is this still a problem?

**Comment by thinkyhead** [comment]
I suggest taking a look at the Marlin-II electronics and the new firmware for that board as a reference. https://github.com/ErikZalm/Marlin-II It builds on the [ChibiOS RTOS](http://chibios.sourceforge.net/html/). The [ChibiOS Documentation](http://chibios-book.readthedocs.org/en/latest/content/01_introduction/) is very comprehensive as well.

**Comment by fmalpartida** [comment]
Perhaps look at repetier firmware which is currently running most arm based electronics including the due. 

Not much information on the Marlin electronics though. 

Enviado desde mi iPhone

**Comment by vaibhavkatkar18** [comment]
@bobc Hey we are working on porting marlin to STM32 but facing some problems.Are you working on that?

**Comment by Drakelive** [comment]
Hi @vaibhavkatkar18

Do you have a GitHub repository for this development?
I am interested in this, especially the implementation used (STM32 Core). Can
you talk about this?

2016-01-11 5:43 GMT+01:00 vaibhavkatkar18 notifications@github.com:

**Comment by berryelectronics** [comment]
Thought I'd make a note Here about the Hardware. 
Im currently Working on a [controller board using a STM32F1 Chip ](https://github.com/berryelectronics/ReST32)(ATM, pin-wise, it should simply be replacable with a F Series one) which is mostly modular. By that I mean you can replace the MosFETs for the heaters and the stepper driver from the main board, which connect via 0.1" right angled connectors. 
I already copied most of the schematics from an older project of mine (wasnt modular + was in eagle, now Working in KiCad), only part missing is the PCB layout , then ordering some stuff and tinkering around with the Firmware to get it ported.
I think using the STM33duino project AS a Basis to Programm the board would be good.

Well, would be nice to get some comments on that board ^^

**Comment by thinkyhead** [comment]
Have a look at https://github.com/MagoKimbra/MarlinKimbra4due for a fork of Marlin that works on Due. It's under very active development, and I'd like to hear some feedback about it.

**Comment by tonnico** [comment]
He started with my Due-Fork but now Kimbra is going its own way. I messed a bit around with ADC and ISR, but this is not much code to isolate.

**Comment by ghost** [comment]
Well, I also made modified Marlin for Due, this branch is compatible with both Arduino MEGA and Due. https://github.com/esenapaj/Marlin/tree/Duo based on latest original Marlin RCBugFix branch (1.1.0-RC3), Due part was ported from Marlinkimbra4due 4.2.4 dev and Marlin4Due 1.0.3 dev. I'd feel amply rewarded for my efforts if this proved helpful to supporting for Due by official.

and, I founded that some features don't work on Due at this time.
- `M100_FREE_MEMORY_WATCHER`
- `FAST_PWM_FAN`
- `WATCHDOG_RESET_MANUAL`
- `ADVANCE`

**Comment by Roxy-3D** [comment]
> and, I founded that some features doesn't works on Due at this time.
> ·M100_FREE_MEMORY_WATCHER

I wrote that code.   It is very simple.   But it makes assumptions about where the compiler is going to put things in memory.   For example, it assumes global RAM variables are at the top (smallest addresses) of memory.  It assumes the heap grows downward from there.  It also assumes the stack is at the bottom (biggest addresses) of memory and grows upward.

If those assumptions are not true, the code would have to be warmed over but it would be almost trivial to get it going if I had Due to debug it on.

**Comment by thinkyhead** [comment]
The Due topic is still alive and well, don't worry! Just focusing on finishing up 1.1.0 release, and then we're most likely to do a mashup of various forks, just as @esenapaj has done. There will be a number of changes to integrate when we get into that, but I think it will go pretty smoothly. I look forward to bringing in the great work of @MagoKimbra, @Wurstnase, and others. I recently did a presentation on Marlin for the local 3D printing meetup group here in Portland, OR, and I had a lot of good things to say about the work being done in these forks!

**Comment by MagoKimbra** [comment]
Thank @Wurstnase and @thinkyhead. Unfortunately I not am known and officially did not much help in my fork and alone is tough. Now I'm changing all part of management Extruders - Hotend. I would like to turn this into Tools objects where the tools can be extruder - hotend - laser - CNC.
I am always available to help out if need be.

**Comment by tonnico** [comment]
Most work was made by @bobc. I only made some finetuning. When you need some help about registers and the character of the Arduino Due don't hesitate to ask. Especially with timers and ADC I could help a bit.

**Comment by Drakelive** [comment]
Hi,

Marlin firmware must support Arduino DUE, We can not delay again. I believe it is necessary to separate the Hardware Management, but we are lucky because MagoKimbra and Wurstnasethey did this by creating the files\* HAL.h _and *HAL__.c_

We could begin to create this by creating _AVR_HAL_ ( for avr chip ) and then add _SAM_HAL_ (for arduino due). In the future we can also add other things like _STM32_HAL_ ( for stm32 chip )

**Comment by Roxy-3D** [comment]
@MagoKimbra  @Wurstnase

Can I get your email addresses?  (None of us have our email addresses exposed.)

I have a couple of discussions I would like to pull you into.   If you are willing to give me your email addresses the question becomes how to get them to me.  

One possibility would be  you send them to ThinkyHead and he can forward them to me.   Or, you can send me a private message over at www.3DPrintBoard.com.

**Comment by MagoKimbra** [comment]
My is magokimbra@hotmail.com

**Comment by thinkyhead** [comment]
Thanks @MagoKimbra! Our first couple of emails were forwarded to the wrong address – I will redirect them shortly.

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.

**Comment by Avamander** [comment]
Any updates on this?
