### ISSUE TITLE
Bilinear leveling is broken for Delta

### ISSUE THREAD

**Issue by zlowred** [MarlinFirmware/Marlin#6261]
It is broken after commit c961dd084d5971b26161553c426230becd6c15f5 'Add hidden option to output Bilinear grids in JSON'
Leveling sequence goes normally but printer stops responding to Z move commands after leveling is completed. 
Also, after leveling is completed, M114 shows correct positions for X, Y, Z in mm, but is steps it shows (-2,147,483,648, -2,147,483,648, -2,147,483,648)

I believe it is because of float to NAN comparisons which should probably be 'isnan(value)' instead.

**Comment by Roxy-3D** [comment]
I left some comments at https://github.com/MarlinFirmware/Marlin/pull/6289
