### ISSUE TITLE
Missing #define DAC_MOTOR_CURRENT_DEFAULT 

### ISSUE THREAD

**Issue by emartinez167** [MarlinFirmware/Marlin#6270]
Cannot compile for RIGIDBOARDV2, as #define DAC_MOTOR_CURRENT_DEFAULT is missing.

**Comment by Bob-the-Kuhn** [comment]
I was that close ...

I'll get it fixed today.

**Comment by Bob-the-Kuhn** [comment]
DAC_STEPPER_DFLT was changed to DAC_MOTOR_CURRENT_DEFAULT on PR #6271.

**Comment by emartinez167** [comment]
Fixed. Closing. Thanks!
