### ISSUE TITLE
X/Y resolution loss on RepRap Full Graphic Display

### ISSUE THREAD

**Issue by Tannoo** [MarlinFirmware/Marlin#6286]
I wanted to open this issue to get help in getting this fixed.

On the status screen, the X and Y used to show 0.0 and now just shows 0.
If X or Y move past 99, then the display shows 10.0 instead of 100.

M114 show the correct position... this is a display issue.

**Comment by thinkyhead** [comment]
I'm guessing you have `LCD_DECIMAL_SMALL_XY` enabled….
I've patched `RCBugFix` with a correction for this issue.
