### ISSUE TITLE
DEFAULT_AXIS_STEPS_PER_UNIT no error or warning if too few initializers

### ISSUE THREAD

**Issue by mgaman** [MarlinFirmware/Marlin#6287]
Configuration.h

DEFAULT_AXIS_STEPS_PER_UNIT must have a least 4 initializers (X,Y,Z,E0 motors). In error I only wrote 3 initializers (X,Y,Z) and omitted the 4th for E0.
As a result E0 was set to the same value as Z i.e around 2500 instead of ~600.

**Comment by thinkyhead** [comment]
Until recently it was not easy to sanity check this sort of thing. But we have `static_assert` with C++11 now, so we can add a check for this at compile-time.

**Comment by thinkyhead** [comment]
Fixed with #6330.
