### ISSUE TITLE
Z Axis falling out - CoreXY

### ISSUE THREAD

**Issue by jrmann1999** [MarlinFirmware/Marlin#6301]
On my CoreXY build, the Z-Axis is falling during manual homing, and during print.

Running RCBugFix.  Let me know what I need to attach to help diagnose.

Attached my configuration.h
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/911216/Configuration.txt)

**Comment by teemuatlut** [comment]
#6147 Would this be related to your problem?

The suggested solution there was setting these in configuration_adv.h
#define DEFAULT_STEPPER_DEACTIVE_TIME 0
#define DISABLE_INACTIVE_Z false

**Comment by jrmann1999** [comment]
That has resolved it, thanks!
