### ISSUE TITLE
RCBugFix Heater 4 broken

### ISSUE THREAD

**Issue by kcheeeung** [MarlinFirmware/Marlin#6310]
@thinkyhead I believe you forgot to include a few lines in **thermistortables.h** for the RCBugFix, as the current version does not compile right.

I added this to make it compile correctly
```cpp
#ifndef HEATER_4_RAW_HI_TEMP
  #ifdef HEATER_4_USES_THERMISTOR
    #define HEATER_4_RAW_HI_TEMP 0
    #define HEATER_4_RAW_LO_TEMP 16383
  #else
    #define HEATER_4_RAW_HI_TEMP 16383
    #define HEATER_4_RAW_LO_TEMP 0
  #endif
#endif
```

Current rcbugfix version
![untitled](https://cloud.githubusercontent.com/assets/24723501/24902067/e153f21e-1e5d-11e7-9a4a-b9c28485e6ce.jpg)

Not related so related, but what is the meaning of this as well? I enabled M43 debug in config_adv when I compiled.

```
In file included from sketch\Marlin_main.cpp:5373:0:
sketch\pinsDebug.h:2:1: warning: invalid conversion from 'const unsigned char*' to 'const char*' [-fpermissive]
  * Marlin 3D Printer Firmware
 ^
sketch\pinsDebug.h:2:1: warning: invalid conversion from 'int' to 'const char*' [-fpermissive]
sketch\pinsDebug.h:2:1: warning: invalid conversion from 'const unsigned char*' to 'const char*' [-fpermissive]
sketch\pinsDebug.h:2:1: warning: invalid conversion from 'int' to 'const char*' [-fpermissive]
sketch\pinsDebug.h:2:1: warning: invalid conversion from 'int' to 'const char*' [-fpermissive]
In file included from sketch\Marlin_main.cpp:5373:0:
sketch\pinsDebug.h:199:1: warning: invalid conversion from 'volatile uint8_t* {aka volatile unsigned char*}' to 'const uint8_t* {aka const unsigned char*}' [-fpermissive]
 };
 ^
sketch\pinsDebug.h:199:1: warning: invalid conversion from 'volatile uint8_t* {aka volatile unsigned char*}' to 'const uint8_t* {aka const unsigned char*}' [-fpermissive]
```

**Comment by Bob-the-Kuhn** [comment]
The M43 code does some unusual memory operations that depend on the compiler to convert between different types of data.

It looks like your compiler and/or your IDE extension have the type conversion flags set to a more conservative level than what most people are using.

What are you using to compile the code?  If it's Arduino I'll want to know the Arduino revision number and the setting of` Board:` under the tools menu.

**Comment by kcheeeung** [comment]
Hey Bob, I'm just using the Arduino IDE 1.8.1 to compile. I was just curious what that meant, as I am still able to upload and flash the firmware to the board

**Comment by Bob-the-Kuhn** [comment]
I didn't notice those were warnings.  Errors would have killed the compile.

I see those warnings fly by also.

**Comment by thinkyhead** [comment]
Seems to have gotten patched along the way. There certainly are many details involved to support an additional extruder.
