### ISSUE TITLE
[QUESTION] Where does the 32-bit version stand? 

### ISSUE THREAD

**Issue by mperdue** [MarlinFirmware/Marlin#6340]
I'm wondering about the 32-bit version because I have a controller that has a defect in the SD card handling and would rather not buy an 8-bit board when my plan is to go 32-bit anyway. Is the current code working at all? What controller(s) is(are) supported? I prefer to stay with Marlin because of the active group here.

**Comment by teemuatlut** [comment]
The Teensy HAL should have working basics but is largely untested and lacks hardware support to make things convenient. I'm not familiar with the other platforms.

**Comment by JustAnother1** [comment]
There have been some forks for different controllers. But none of them got merged and they are all based on rather old Marlin versions.

Just recently @bobc started the "official" move towards 32bit. You can see it when switching to the "32-Bit-RcBugFix*" branch. The Idea is to support all ARM Cortex-M controllers.

As far as I know the branch is in an early stage. If you need to get printing fast then you need to find something else. Right now more testers and especially more implementers are needed to move this forward. Do you know someone who can code using the Arduino IDE ?

**Comment by mperdue** [comment]
It looks as if the 32-Bit-RcBugFix-new version is the most current. I guess I'll need to download that and start taking a look at the code involved. I haven't done any coding since I retired three years ago but I may be able to revive some brain cells.

**Comment by JustAnother1** [comment]
I would be happy to help, once you can get it into a state where the makefile works. (I'm incompatible to the Arduino IDE). I have done some stuff for STM32,..

**Comment by dp90pusika** [comment]
Hi, I have a dual x carriage machine with an arduino due in it, and want to mowe to the newest 32bit version.
I tried to test the newest "32-Bit-RcBugFix-new" that is currently up, but it's busted. Does not compile because of some problem with the serial.cpp

I would be happy to help out with testing, there are a lot of new exciting features in the script. But I'm not much use as a programer. Let me know If I can help somehow.

[EDIT]:
This compilation error is fixed by @bobc suggestion:

> serial.h is missing an include :
>#include "src/HAL/HAL.h"

**Comment by thinkyhead** [comment]
Compile error fixed. I hope to rebase the branch and get it into shape after the 1.1.0 release. The hard deadline for the release is April 30.

**Comment by Roxy-3D** [comment]
> The hard deadline for the release is April 30.

Is that for sure?   It would help people to know that!

**Comment by JustAnother1** [comment]
> The hard deadline for the release is April 30.

 “I love deadlines. I love the whooshing noise they make as they go by.”

― Douglas Adams, The Salmon of Doubt
