### ISSUE TITLE
Pause/Resume Print through the LCD does not work

### ISSUE THREAD

**Issue by jflevesque** [MarlinFirmware/Marlin#6365]
I've tried to pause/resume a print through the LCD controller, but it does not work. The print just continues to run.

Here is my config file, running RCBugFix.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/924412/Configuration.zip)

**Comment by Bob-the-Kuhn** [comment]
Marlin will finish executing the commands already read from the SD card when the pause command is sent.

If you're doing some long extrudes then it could be tens of seconds before it stops.
