### ISSUE TITLE
BABYSTEPPING doesn't move as LCD shows

### ISSUE THREAD

**Issue by Tannoo** [MarlinFirmware/Marlin#6369]
Nevermind.... I got it.

**Comment by Kaibob2** [comment]
@Tannoo I cannot confirm this. On [RCBugFix from 12.4.2017](https://github.com/MarlinFirmware/Marlin/commit/6d5400dc318d77502aaacced64db62fac5501cd1) Z-Babystepping via Doubleclick works, no matter if homed or not, like intended. When i double click the Encoder and turn it afterwards the Z-steppers get powered and move.

**Comment by Kaibob2** [comment]
Oops, I should've typed faster :)

**Comment by Tannoo** [comment]
The babystepping mulplicator isn't as "sensitive" as it once was. And a recent change also made babystepping much more silent. I did find that it works just fine.
