### ISSUE TITLE
[HELP NEEDED] ambient temp control system

### ISSUE THREAD

**Issue by davidflypei** [MarlinFirmware/Marlin#6383]
First off im not sure were this is supposed to be so dont delete it. Let me know and i can copy it somplace  else.

Its been a while  (like multiple years) since i have played with full on coding on arduino so i need help editing the code a little to add in this feature. I dont have any visuals right now because im not at home.

I need help with a system I want to make for ambiant temp control. The mechanics of it i have sorted so i just need help with the firmware. Basicly there is a flap behind a fan that will direct the air flow. The flap will be controlled via a servo that is connected to the board. The fan is ran off the psu. So when the temp that is sensed by a thermistor in the enclosure gets above a temperature value given by a mXXX command then the flap moves to vent the air. When its below the temperature it "closes" and recycle the warm air back into the enclosure.

Now you would have to have something like this to decided when to open and when to close.
Lets say "o" is the open temperature and "c" is the close. T is the temperature given by a mXXX command.
So o = t  + 5°c and c = t - 5°c. 

So if t = 50°c and the current temp is 56°c then the flap would open and vent the air to cool the ambiant temp down to the close value.
Now the flap is open and the air is being vented and the flap closing temp is (because of the +- 5°c) at 45°C. The temp reaches 45°c and the flap closes and diverting the warm air back into the enclosure. 

There is a filter on the system so thats why the fan is on the psu and not controlled by the board.

So i need something in the config for stuff like the +- value, degrees to move the servo, feature enable/disable, thermistor pin position and stuff like that. If you want someone can start a respiratory to help with the prosses. 

Overall its pretty simple its just that i cant remember how to do anything.

Feel free to ask questions and everything.

Thanks.
David McKenna.

**Comment by Bob-the-Kuhn** [comment]
The instructions in [Contributing Code with Pull Requests](http://marlinfw.org/docs/development/getting_started_pull_requests.html) will get you setup with a repository that can be used to develop code aimed at being merged into Marlin.

Ignore the security warning that pops up.
