### ISSUE TITLE
X-axis motor disconnects during print

### ISSUE THREAD

**Issue by Tailhappy** [MarlinFirmware/Marlin#6408]
So the symptom of the problem is that during a print (using Marlin 1.10-RC8), the x-axis motor disconnects inexplicably resulting  in a circular part becoming a vertical line (see attached pic)![img_1004](https://cloud.githubusercontent.com/assets/27827397/25264571/c7ef4cee-261c-11e7-8560-a688d37c11c7.jpg)

My setup is unusual in that I've set extruder E1 to be the **primary** extruder using the "T1" command in my startup gcode. This extruder is positioned at X=-33.0mm from E0. I've used either the slicer or the firmware to specify this X-offset dimension. In either case the result is identical.  Somehow while in the middle of printing (actually about 33% complete), Marlin decides to cutout the X-axis motor and the only way to reconnect is to disconnect and reconnect Octoprint (v1.3.2).

The sliced gcode commands are normal and continue to specify typical X and Y coordinates during the loss of the X-axis. This change is not commanded by gcode, rather it's the Arduino processor (Mega2560) directing the motor driver (on the Rambo controller board) to disconnect. Unfortunately I have no ability to view this motor driver communication link.

**Comment by emartinez167** [comment]
Have you noticed if it always happens at the same height? If so, could be a loose cable on the stepper that only manifests itself when the cables bend beyond a certain point.

**Comment by Tailhappy** [comment]
While yes, it definitely happens at the same layer height each time, it can't be a hardware (cable) issue  because I reset the connection by disconnecting and then reconnecting Octoprint. Could Octoprint be involved? Yes, but how do I diagnose this? I need some visibility of the Ardiuno comm link like a log file or something, but I'm unfamiliar with Arduino code executing besides the Marlin FW compiling. Again, the serial link shows no oddities in the Gcode stream.

Another quicker way to reproduce this bug is to initialize, and then immediately stop the print. The X-axis motor will disconnect even prior to the first layer being printed.

**Comment by Bob-the-Kuhn** [comment]
Could the X stepper or its driver be over heating?

**Comment by Tailhappy** [comment]
The last sentence in my second post above provides the evidence that this isn't a thermal (or hardware) related issue. And the motor is well matched to the driver and cold. It's a bug. I suspected the cause was the negative offset value for the second extruder so I swapped E0 and E1, made the value positive 33.0mm and all is well. Workaround complete.

**Comment by Bob-the-Kuhn** [comment]
Thanks for the feedback.  

I've added this to my Marlin Things To Do list.

**Comment by thinkyhead** [comment]
> My setup is unusual in that I've set extruder E1 to be the primary extruder using the "T1" command in my startup gcode. This extruder is positioned at X=-33.0mm from E0. I've used either the slicer or the firmware to specify this X-offset dimension.

Are you homing X to min or to max? Note also that `X_HOME_POS` applies to `T0`. What is the current position of `T0` after `G28`?

Please post your `Configuration.h` and `Configuration_adv.h` files to help with testing. (You may need to add `.txt` extension for Github to accept the files being dropped into the textfield.)

Also, test again with your old configuration, but disable software endstops with `M211 S0` before testing. If it fixes the issue (it should), then we know better where to look.
