### ISSUE TITLE
Marlin Fan Percentage is not showing... Its showing "---" Pls help

### ISSUE THREAD

**Issue by ShrikantPai123456** [MarlinFirmware/Marlin#6411]
I am using clone of sanguino.. Fan is showing only "---".. I wanted in percentage %... That is 0-255 is 0%-100%.....

Pls tell what shall I add in Marlin V1.0 or uncomment?????
![img_20170421_150826](https://cloud.githubusercontent.com/assets/27852210/25272463/95be9034-26a5-11e7-9741-c55f9472c644.jpg)

**Comment by Tannoo** [comment]
Is that with the fan off?
What if you set the fan to 50%?

**Comment by ShrikantPai123456** [comment]
No sir.. thks for replying. When fan is ON, its showing "---" and also when its off, the same message is displaying.

I went to control menu and kept 255 for FAN.. then also same message "---"

Help...

**Comment by ShrikantPai123456** [comment]
I kept 50% which nearly 128 value....but same message "---"

What am I missing line in marlin???

**Comment by Tannoo** [comment]
Extruder fans?

**Comment by Tannoo** [comment]
In `configuration_adv.h`, there are these settings:

I am running RCBugFix. You can upgrade to that and see if that issue is fixed for you.
I only have one extruder, but not controlling extruder fans.
```
/**
 * Extruder cooling fans
 *
 * Extruder auto fans automatically turn on when their extruders'
 * temperatures go above EXTRUDER_AUTO_FAN_TEMPERATURE.
 *
 * Your board's pins file specifies the recommended pins. Override those here
 * or set to -1 to disable completely.
 *
 * Multiple extruders can be assigned to the same pin in which case
 * the fan will turn on when any selected extruder is above the threshold.
 */
#define E0_AUTO_FAN_PIN -1
#define E1_AUTO_FAN_PIN -1
#define E2_AUTO_FAN_PIN -1
#define E3_AUTO_FAN_PIN -1
#define E4_AUTO_FAN_PIN -1
#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED   255  // == full speed
```
My extruder fan runs all the time the printer is powered (pretty much all the time  :)

**Comment by Tannoo** [comment]
That says that you'll have to check your board's pin file for fan <-> pin assignments.

**Comment by ShrikantPai123456** [comment]
This is my code
```cpp
#define EXTRUDER_0_AUTO_FAN_PIN   -1
#define EXTRUDER_1_AUTO_FAN_PIN   -1
#define EXTRUDER_2_AUTO_FAN_PIN   -1
#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED   255  // == full speed
```
Fan is rotating fine.... Nozzle as well as for mother board sanguino....But only displaying as "---" on LCD....

The FAN symbol working on LCD and FAN is also rotating on sanguino... Only FAN percentage is not displaying sir....

what shall I do????

**Comment by Tannoo** [comment]
Time for RCBugFix uprade. That's what this branch is for. Fixing bugs in the RC branch along with new features.

**Comment by Tannoo** [comment]
Or at least up to RC8.

**Comment by ShrikantPai123456** [comment]
Yeah ok... I will upgrade.

But pls tell me what code shall I add in Marlin???

or comment or uncomment sir???

**Comment by ShrikantPai123456** [comment]
Pls tell the coding part in Marlin V1.0...

It important so sir....

**Comment by Tannoo** [comment]
Well, you can download RC8 and compare the difference. Make appropriate changes.

It will be easier to upgrade than to try to fix what may already have been fixed.

**Comment by ShrikantPai123456** [comment]
Pls see my code    dogm_implementation.h
```cpp
// Heatbed
 u8g.setFont(FONT_STATUSMENU);
 u8g.setPrintPos(81,6);
 u8g.print(itostr3(int(degTargetBed() + 0.5)));
 lcd_printPGM(PSTR(LCD_STR_DEGREE " "));
 u8g.setPrintPos(81,27);
 u8g.print(itostr3(int(degBed() + 0.5)));
 lcd_printPGM(PSTR(LCD_STR_DEGREE " "));
 if (!isHeatingBed())
   u8g.drawBox(88,18,2,2);
 else {
   u8g.setColorIndex(0);	// white on black
   u8g.drawBox(88,18,2,2);
   u8g.setColorIndex(1);	// black on white
 }
 
 // Fan
 u8g.setFont(FONT_STATUSMENU);
 u8g.setPrintPos(104,27);
 #if defined(FAN_PIN) && FAN_PIN > -1
   u8g.print(itostr3(int((fanSpeed*100)/255 + 1)));
   u8g.print("%");
 #else
   u8g.print("---");
 #endif
```
but code is taking only  **u8g.print("---");**

**Comment by ShrikantPai123456** [comment]
help somebody.... ASAP

my nozzle and controller FANS are working.... also FAN rotation symbol on LCD is displaying... But only the FAN percentage is not displaying....

Help....

**Comment by Tannoo** [comment]
```
#if defined(FAN_PIN) && FAN_PIN > -1
u8g.print(itostr3(int((fanSpeed*100)/255 + 1)));
u8g.print("%");
#else
u8g.print("---");
#endif
```

**Comment by ShrikantPai123456** [comment]
@tannoo 

whats that sir???

**Comment by Tannoo** [comment]
What you posted..

```
#if defined(FAN_PIN) && FAN_PIN > -1             <--- FAN_PIN AND FAN_PIN >-1
u8g.print(itostr3(int((fanSpeed*100)/255 + 1)));
u8g.print("%");
#else
u8g.print("---");                                <--- If not FAN_PIN AND FAN_PIN <-1
#endif
```

That means that your FAN_PIN has to be defined AND FAN_PIN has to be greater than -1.

So... try making that an OR by changing 
`#if defined(FAN_PIN) && FAN_PIN > -1`
to
`#if defined(FAN_PIN) || FAN_PIN > -1`
and see if that works.

**Comment by stigjoergensen** [comment]
Hi was trying to tell you, that you allready have written what you needed to know ;)

if you look at it:
```cpp
#if defined(FAN_PIN) && FAN_PIN > -1
u8g.print(itostr3(int((fanSpeed*100)/255 + 1)));
u8g.print("%");
#else
u8g.print("---");
#endif
```
This means:
if FAN_PIN is defined somewere and the value is bigger than -1 then
   print fanspeed * 100 / 255 (this formula converts the 0-255 value to 0-100
else
  print ---


that means, if you see --- then either the FAN_PIN isnt defined somewhere or the value is -1 - normally you would look for this in 3 places - config.h config_adv.h or your board.h files

**Comment by Tannoo** [comment]
>somew`h`ere and the value is bigger than -1

Search for it. Likely in your pins file.

**Comment by ShrikantPai123456** [comment]
yeah I will check with "OR"ing and reply to you sir...

@Tannoo
@ stigjoergensen 

Thnks I will be back in minute....

**Comment by ShrikantPai123456** [comment]
this is pins.h
```cpp
#define LED_PIN            -1

#define FAN_PIN            -1
 #if FAN_PIN == 12 || FAN_PIN ==13
  #define FAN_SOFT_PWM
#endif

#ifdef MELZI
 #define LED_PIN            27 /* On some broken versions of the Sanguino libraries the pin definitions are wrong, which then needs LED_PIN as pin 28. But you better upgrade your Sanguino libraries! See #368. */
 #define FAN_PIN            4 // Works for Panelolu2 too
#endif

#ifdef STB
 #define FAN_PIN            4
	//  Uncomment this if you have the first generation (V1.10) of STBs board
 #define LCD_PIN_BL         17 // LCD backlight LED
#endif
```

**Comment by ShrikantPai123456** [comment]
Sanguino controller board...

**Comment by ShrikantPai123456** [comment]
Wow "OR"ing working sir...

Ok now the FAN is automatically getting ON even if its 1% (Almost OFF).

At 1% my FAN is rotating FULL... Pls tell me sir...

**Comment by ShrikantPai123456** [comment]
![k](https://cloud.githubusercontent.com/assets/27852210/25275950/72e416b4-26b5-11e7-9c15-dab69eeeffa5.jpg)

At this 1% FAN is rotating FULL.. What shall I do sir????

**Comment by thinkyhead** [comment]
As applies to Marlin 1.1.x…

The `FAN_PIN` fan is for the software-controlled fan which is set with `M106` and used to cool the printed object when printing in PLA. This is the fan status that will be printed on the graphical display. The "extruder auto-fans" are not displayed.

> `#if defined(FAN_PIN) && FAN_PIN > -1`

In Marlin 1.1.0 we can use `#if HAS_FAN0` in place of that. (And `PIN_EXISTS(FAN)` would be the literal equivalent.)

As it is now…
```cpp
#if HAS_FAN0
  if (PAGE_CONTAINS(20, 27)) {
    // Fan
    const int per = ((fanSpeeds[0] + 1) * 100) / 256;
    if (per) {
      u8g.setPrintPos(104, 27);
      lcd_print(itostr3(per));
      u8g.print('%');
    }
  }
#endif
```

We're not doing active support for Marlin 1.0.x — but from this guidance you should be able to figure out the equivalent for that version.

**Comment by ShrikantPai123456** [comment]
ya ok let me give a try sir... thx
