### ISSUE TITLE
Upgrade Configuration File

### ISSUE THREAD

**Issue by jasoncross** [MarlinFirmware/Marlin#6414]
Is there a tool or method to update the old version configuration files to the new version short of a full variable-by-variable compare and rebuild?

I'm running the RCBugFix from about two months ago and want to test the latest, but the configs have changed dramatically in that time.

**Comment by Bob-the-Kuhn** [comment]
Most of ease the pain by using an editor like Notepad++ that has a nice side by side compare.

I've seen a mention of a tool (Marlin3DprinterTool) that's supposed to help with the migration.  It's still in beta & you might have to pay for it.  
Marlin3DprinterTool - http://www.marlin3dprintertool.se/LatestVersion/Marlin3DprinterTool.msi
Website -  http://www.marlin3dprintertool.se

**Comment by Kaibob2** [comment]
My favourite Tool is [winmerge](http://winmerge.org/downloads/?lang=en) as it is only made for comparing two files. 
Notepad++ is a great tool, but, in my opinion, a little bit too bloated for only comparison.

**Comment by Bob-the-Kuhn** [comment]
I just tried winmerge.  The difference displays are very similar but it's a LOT better at not getting lost (losing sync between the two files).

**Comment by fiveangle** [comment]
Don't try [Beyond Compare](http://www.scootersoftware.com/index.php) or you'll be forced to eventually whip our your check book ;)
