### ISSUE TITLE
Any idea why #6400 breaks the steppers for my Anet printer fork?

### ISSUE THREAD

**Issue by oderwat** [MarlinFirmware/Marlin#6417]
When I add the changes from #6400 the steppers just go crazy (sounds like being much to fast an losing nearly all steps). Unfortunately I don't have any clue on what is really done in that commit and why these changes break everything so bad for my fork (https://github.com/SkyNet3D/Marlin/)

**Comment by benlye** [comment]
Same here :-(

**Comment by benlye** [comment]
@oderwat, you probably figured this out already, but just reverting stepper.cpp gets the motion back to normal.  Once the kids are in bed I'll try to work out why.

**Comment by bgort** [comment]
Same issue here.  Going to look into this now.

**Comment by bgort** [comment]
> @oderwat, you probably figured this out already, but just reverting stepper.cpp gets the motion back to normal.

Yeah, same here, again.  Reverting stepper.cpp changes fixes the problem.  Not sure what the issue is without digging into the 2560 datasheet.

**Comment by benlye** [comment]
I believe I found it.  There is a typo in fastio.h at line 141.

This:
```
    TCCR##T##Q = (TCCR##T##Q & !(0x3 << COM1##Q##0) | (int(V) & 0x3) << COM1##Q##0); \
```

Should be this:
```
    TCCR##T##Q = (TCCR##T##Q & ~(0x3 << COM1##Q##0) | (int(V) & 0x3) << COM1##Q##0); \
```

Changing that line in the new macro solves the crazy stepper motion for me.

**Comment by bgort** [comment]
Ah, that makes sense.  Good catch.  Fixed things here, too.

**Comment by oderwat** [comment]
Fixed it for me as well! Thank you for the quick response!
