### ISSUE TITLE
Minor Bug in Print Time Elapsed

### ISSUE THREAD

**Issue by deshawnsmith** [MarlinFirmware/Marlin#6428]
The time elapsed does not reset when aborting a print, and then restarting the print with the same file/filename.

To reproduce, using the LCD interface, print from the SD card. Let the print run for a few minutes, then use the LCD to stop the print. The LCD will then say "Print aborted"  Then use the LCD interface to start printing the same file from the SD card. The print will start from the beginning, but the time elapsed is not reset to zero. The time elapsed continues to accrue from the time elapsed in the previous print.

This happened even when I removed the SD card, tweaked the .gcode file on my computer, overwrote the file with the same filename, and re-inserted the SD card into the printer.

Marlin version 1.1.0-RC6

**Comment by thinkyhead** [comment]
Please check the `RCBugFix` branch before reporting bugs. RC6 is quite old at this point.
