### ISSUE TITLE
Why isn't 'Squash & Merge' available for Marlin ???

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#6430]
One of the options available is 'Squash & Merge'.  Why isn't that enabled for Pull Requests in the Marlin directory?   That would save people a huge amount of work.

**Comment by thinkyhead** [comment]
It isn't always desirable to reduce all commits down to a single commit. But when it is, that would be a helpful option. Currently you must squash commits with `git rebase -i RCBugFix ; git push -f`.

**Comment by Roxy-3D** [comment]
OK...   I do understand that.     I won't abuse it.   I'll only use it where it makes sense to do that.

How about we turn that on?

**Comment by thinkyhead** [comment]
I've enabled the feature. Hopefully it provides a way to set the commit message on the squashed+merged result.

**Comment by Roxy-3D** [comment]
Thank you.    I'm pretty sure it is going to let us set the commit message.   But I've always done that in the Pull Request, so for me it probably doesn't change anything.
