### ISSUE TITLE
Typos in docs

### ISSUE THREAD

**Issue by cgcardona** [MarlinFirmware/Marlin#6444]
**Given** I'm a new user hoping to configure marlin
**When** I'm reading [the configuring and compilation docs ](http://reprap.org/wiki/Marlin#Configuring_and_compilation)
**Then** I expect to see
> Example: If you're using a RAMPS 1.4 with a extruder, fan (optional) and heated bed, then you'd need RAMPS_14_EFB.

**Actual** I see
> Example: If you're using a RAMPS 1.4 with a extruder, fan (optional) and heated bed, then you'd need RAMPS_13_EFB.

It incorrectly says `RAMPS_13_EFB.` instead of `RAMPS_14_EFB.`

***

**Given** I'm a new user hoping to configure marlin
**When** I'm reading [the configuring and compilation docs ](http://reprap.org/wiki/Marlin#Configuring_and_compilation)
**Then** I expect to see
> Scroll down to HEATER_0_MAXTEMP. If you know that your hotend shouldn't go above a certain value (the Budaschnozzle should not exceed 240C-242C), then change it here. Same for BED_MAXTEMP.

**Actual** I see
> Scroll down to MAX_HEATER_TEMP. If you know that your hotend shouldn't go above a certain value (the Budaschnozzle should not exceed 240C-242C), then change it here. Same for MAX_BED_TEMP.

It incorrectly says `MAX_HEATER_TEMP.` instead of `HEATER_0_MAXTEMP` and `MAX_BED_TEMP` instead of `BED_MAXTEMP`

**Comment by Tannoo** [comment]
>RAMPS 1.4 with a extruder

Should also be `an extruder`

**Comment by thinkyhead** [comment]
If you've edited the Wiki at reprap.org to make the corrections, then you have our undying gratitude and you can close this issue.
