### ISSUE TITLE
Babystepping ?

### ISSUE THREAD

**Issue by davidmarli** [MarlinFirmware/Marlin#6446]
Hi,

I was using rc7 with babystepping.
When I wanted to use it, it displayed the Z offset, it was very nice and usefull.
I created a new 3dprinter, I upload marlin rc8 and enabled the babystepping option. It works great, BUT it doesn't display the offset anymore.
So can someone explain me how to make it display again. What do I have to modify in the code the make it appear ?

Thank you very much for your answers.

**Comment by shitcreek** [comment]
Please try the latest version of Marlin and report back if issue still exists.
