### ISSUE TITLE
Polish language / DOGM vs HD44780

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#6455]
The Polish language file includes Polish characters in its strings for graphical display, and Roman characters for character display, and combines these into a single language file.

1. Can we accomplish the same thing using a mapper?
2. Will any other language files need to follow this pattern?
3. If a mapper won't do it, should this be split into two files?
— `language_pl.h`, `language_pl_ascii.h`

**Comment by hydrocat** [comment]
So, other languages have got two files. One with special characters with names ending in "_utf8.h" and another one ending in plain ".h". for example, the pt-br translation have both "language_pt-br_utf8.h" and "language_pt-br.h"
