### ISSUE TITLE
PT-BR language group

### ISSUE THREAD

**Issue by schirrel** [MarlinFirmware/Marlin#6461]
I was reading some of the pt-br translations and some of them are... understable but others are strange or not friendly, i mean, some are just strict translation of the work or "aportuguesamento" of the word which is no too ok(? i think), so, could we make a group for translation or to discuss, by this i mean just chat no discuss like figth and stuff, to make the portuguese translations a little... cooler, or even better?
what u think @esenapaj @jbrazio @hydrocat @ivan-galvez ?

**Comment by hydrocat** [comment]
Sure ! I was assigned as a maintainer for the pt-br translations but I haven't been as active as I expected..

**Comment by hydrocat** [comment]
By which means should we contact ? slack ?

**Comment by schirrel** [comment]
I never use Slack but for me it's ok

Em 27/04/2017 5:26 PM, "Vitorio Miguel Prieto Cilia" <
notifications@github.com> escreveu:

**Comment by CoderSquirrel** [comment]
never *

**Comment by hydrocat** [comment]
Me neither but it's what everyone is using now. What do you suggest ?

**Comment by schirrel** [comment]
google groups maybe? 
but no probleming in using stack, is always good to learn new stuff

**Comment by loos-br** [comment]
is this still an issue ?
