### ISSUE TITLE
GPL violation: Monoprice Select Mini (M200)

### ISSUE THREAD

**Issue by mmonsterski** [MarlinFirmware/Marlin#6467]
Source directory: [Motion firmware](https://drive.google.com/drive/u/0/folders/0BxyFI3iDaicLQXRhNi1IZkd4WU0)
Filename: motion_29.zip

In my opinion this version is based on heavy modified version with "V23" version of configuration_store:
>V23 V23 Settings Stored (    bytes) V23  stored settings retrieved (    Hardcoded Default Settings Loaded

**Comment by Roxy-3D** [comment]
Yeah....  But can you be more specific?   They are publishing the source.  Isn't it OK if they leverage our work to get to where they want to be?

**Comment by mmonsterski** [comment]
Could You provide me address to download source because I've looking yesterday few hours and I don't found it?

**Comment by Saturn49** [comment]
Bumping this - I do not believe Monoprice (nor the manufacturer, Malyan) publishes the source for the Monoprice Mini Select (commonly known as the MPMS) or what Malyan calls M200.

They have several variations, here's one:
https://www.monoprice.com/product?p_id=15365

They have linked firmware (binaries) but no source that I've been able to find.
