### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#6472]
I've been seeing this warning in the latest BugFix (I update it almost every day) for a few weeks now. Compiling with Arduino IDE 1.8.2.

```
In file included from C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\MarlinConfig.h:27:0,

                 from C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\Marlin.h:36,

                 from C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\stepper.cpp:47:

C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\stepper.cpp: In static member function 'static void Stepper::init()':

C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\macros.h:123:37: warning: invalid conversion from 'volatile void*' to 'void*' [-fpermissive]

 #define ZERO(a) memset(a,0,sizeof(a))

                                     ^

C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\stepper.cpp:1102:5: note: in expansion of macro 'ZERO'

     ZERO(e_steps);

     ^

In file included from C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\Marlin.h:28:0,

                 from C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\stepper.cpp:47:

c:\program files (x86)\arduino\hardware\tools\avr\avr\include\string.h:235:14: note: initializing argument 1 of 'void* memset(void*, int, size_t)'

 extern void *memset(void *, int, size_t);

              ^
```

Everything appears to be working ok, but I hate warnings. ;-)

Thanks.

**Comment by Roxy-3D** [comment]
> Everything appears to be working ok, but I hate warnings. ;-)

Agreed!   The reason the compiler is warning you about something is because it doesn't always work!!!

**Comment by ghost** [comment]
I appreciate the support. ;-) I'm hoping someone can figure it out and fix it, because I don't know this language.

**Comment by Tannoo** [comment]
I don't have that issue. Mine compiles cleanly.

**Comment by autonumous** [comment]
i’ve started to have  this issue (actually as an error) when compiling on my Raspberry Pi.

```
In file included from MarlinConfig.h:27:0,
                 from Marlin.h:36,
                 from stepper.cpp:47:
stepper.cpp: In static member function ‘static void Stepper::init()’:
macros.h:123:37: error: invalid conversion from ‘volatile void*’ to ‘void*’ [-fpermissive]
 #define ZERO(a) memset(a,0,sizeof(a))
                                     ^
stepper.cpp:1102:5: note: in expansion of macro ‘ZERO’
     ZERO(e_steps);
     ^
In file included from Marlin.h:28:0,
                 from stepper.cpp:47:
/usr/lib/avr/include/string.h:121:14: error:   initializing argument 1 of ‘void* memset(void*, int, size_t)’ [-fpermissive]
 extern void *memset(void *, int, size_t);
              ^
make: *** [/home/pi/.octoprint/data/bigboxfirmware/tmp/stepper.o] Error 1
/home/pi/oprint/lib/python2.7/site-packages/octoprint_bigboxfirmware/lib/Makefile:310: recipe for target '/home/pi/.octoprint/data/bigboxfirmware/tmp/stepper.o' failed
make: *** Waiting for unfinished jobs....
Something went wrong. Hex file does not exist!
```

**Comment by autonumous** [comment]
@JimBrown @Roxy-3D 
if i add “--fpermissive” to my makefile CXTRA parameter it compiles.
(although i see that as an unclean hack) 

If i disable LIN_ADVANCE, it compiles with no errors.  
leading me to think its related to this section in stepper.cpp
```
#if ENABLED(ADVANCE) || ENABLED(LIN_ADVANCE)
    ZERO(e_steps);
    #if ENABLED(LIN_ADVANCE)
      ZERO(current_adv_steps);
    #endif
  #endif // ADVANCE || LIN_ADVANCE
```
in my last version i compiled (last month) this didn’t use the ZERO macro, but a for loop.

**Comment by ghost** [comment]
Just found the same thing. If I disable LIN_ADVANCE, I no longer get the warning. Hopefully one of the programmers can step in and fix this.

Thanks.

**Comment by autonumous** [comment]
this change was introduced by this commit https://github.com/MarlinFirmware/Marlin/commit/6a9b008044b363fb0f55aa01016afbd3347b3e68
On my system, i can confirm if revert this commit, it compiles with no warnings/errors.

Im guessing its something relating to having LIN_Advance enabled which  declares e_steps  as “static volatile int”, and its causing some issue with the version and configuration of the compiler i have on my Pi.   memset not liking things as volatile or something?

 if i take the same code and compile in Arduino Application on my Mac, it compiles with no issues

For now i’ll simply add the parameter (“--fpermissive”) to my MakeFile :-)

**Comment by Tannoo** [comment]
>Hopefully one of the programmers can step in and fix this.

I'm sure they will, they are a little busy atm getting the next release out the door.

**Comment by thinkyhead** [comment]
The warning for `volatile *` is reasonable. If the pointer might be changed in an interrupt, then it should first be copied to a non-volatile pointer, and then used in `ZERO()`. Or, if the buffer it points to might go away, then the `ZERO()` (`memset`) call should be bracketed in `CRITICAL_SECTION_START` and `CRITICAL_SECTION_END`.
