### ISSUE TITLE
[FR] Mixing factors

### ISSUE THREAD

**Issue by Denarian** [MarlinFirmware/Marlin#6474]
Can you add option to display current mixing factors on LCD ?(between different extruders on mixing hotends like the diamond hotends)

**Comment by boelle** [comment]
@Denarian can you explain what you mean by temp mixing factors?

**Comment by InsanityAutomation** [comment]
@thinkyhead was any display adjustment made when you added gradient mode and such?

@boelle he means between the hotend and bed icons and temperature readings.

**Comment by Denarian** [comment]
@boelle when using mixing hotend such as diamond hotend the extruders are moving with different speeds. Mixing factor is how much specific extruders are going to move when you for eg. want to extrude 1mm of filament. It is configured  by  M-codes M164 and M163

**Comment by Vertabreak** [comment]
my A10M does this in marlin 2.0 
@boelle think this might be safe to close.
