### ISSUE TITLE
Having issue with my prints after updating to latest marlin rc8 fix.

### ISSUE THREAD

**Issue by Rhonal89** [MarlinFirmware/Marlin#6477]
I have a video that explain it well. First layer prints nicely on the second layer random retraction happens. https://youtu.be/FgjsdAIDIw8

**Comment by Rhonal89** [comment]
Check around 2:30 in video

**Comment by Roxy-3D** [comment]
That video was very helpful...   I'm not saying there isn't a problem!!!   But I've seen that too and that happens when I'm pushing the feedrate to the maximum.   I don't know for sure...  But in my case when I've seen that it is like the extruder's stepper motor isn't strong enough to push the filament at the rate specified.  And if it gets too far out of position, it is easier for the stepper motor to go the wrong way and actually go backwards.

I can't see the retraction when you zoom in on the extruder filament drive.    It would be good if you could stick a little piece of tape on it or something so it is easier for us watching the video to see it.

I don't know that is what is happening.  And having that video is very helpful!   I'll work with you to figure this out and get it fixed.   But can you do a couple of things?   First, can you turn up the power to your extruder motor and see if that helps?   And if it doesn't help, can you set your Max Extruder feed rate lower...  maybe at 2/3 and see if it still happens.   

One more idea is....  Can you turn the temperature of your nozzle up 10 degrees C. ?   I know you don't really want to print that way, but that makes it much easier for the filament to feed through the nozzle.  If this is a problem with the extruder motor's feed rate, raising the temperature 10 C. would help us figure that out.

What ever extra information we can get will help us figure this out....

**Comment by Rhonal89** [comment]
Sure thing. I do have a rambo board and I have the extruder set at 85 from 135 set for rambo. Reason was it was getting hot over 100. This is the one I have Short Body Nema 17 Bipolar Step Motor 3.5V 1A 18.4oz.in/13Ncm DIY CNC https://www.amazon.com/dp/B00PNEQ79Q/ref=cm_sw_r_cp_apa_DzSazb9T35E9P

**Comment by Roxy-3D** [comment]
And up in the post up above...   I edited it to suggest seeing if a 10 C. increase in temperature helps.   Any information about what helps and what does not help will be useful to guide us!

One more idea I just had...   It might be useful to clean off your bed, prep it, and do a G26 to put a mesh validation pattern on the bed.   If the places where you have a problem are right at a mesh point...   I've seen that also.  Lowering the mesh point a little bit will make it easier for the filament to get out of the nozzle and help keep the extruder stepper motor from losing position.   (I don't know the stepper motor is losing position.  I need to see how much it goes backwards.   But with what I know right now...  That might be a good thing to try.)

>  Reason was it was getting hot over 100. 

Yeah...   I know opinions vary on this...  But my stepper motors are so hot it is uncomfortable to hold on to them for very long.   If it was my stepper motor and it was 'cool' to the touch...  I would turn up the power.   It is OK to have them 'very warm'.  If you can put your hand on them for 15 seconds and not burn yourself....   You don't need to worry about them.

**Comment by Rhonal89** [comment]
Hi roxy, how would I go from saving my current mesh to loading back to marlin after firmware changes. Thank You!!

**Comment by Roxy-3D** [comment]
Normally...  Firmware updates should not affect your saved mesh's.   But right now...  Things are in a state of flux and where everything is stored in the EEPROM keeps changing.   You can make an 'Off the Printer' backup of the mesh by saying to save it to Slot -1.   You would do a G29 S -1   and it will print the current mesh in a form you can later load it into PronterFace or Repetier Host and 'Print It'.    

Later...  You won't have to do this...  But right now you should do this and save a copy somewhere so you can easily get it back.

**Comment by Rhonal89** [comment]
Thank You!!!

**Comment by Rhonal89** [comment]
Hi roxy, So I up my motor power and PID tune my hotend again and up my temperature also try different file and it keep happening. So went back to another firmware rc8, I think the stable one and it's printing great.

**Comment by Rhonal89** [comment]
The only reason I want to try the other firmware so bad is just because UBL. I'll see what I figure out

**Comment by thinkyhead** [comment]
Sorry, the first thing we should ask is for you to test `RCBugFix` and see if we already fixed the issue. This can save us much time in discussing and investigating water under the bridge.

**Comment by Roxy-3D** [comment]
> The only reason I want to try the other firmware so bad is just because UBL. I'll see what I figure out

Would it be possible to build the latest firmware with no bed leveling in it and see if you get the same problem?   It would be good to know if the problem is in the auto bed leveling code or some where else in the firmware.

**Comment by Rhonal89** [comment]
Ok, so I flashed back the firmware and I let the print continue and I notice it does the retraction every second layer.

**Comment by Roxy-3D** [comment]
That video was very helpful, but I could not see the extruder motor axle.   Can you stick a small piece of tape on it or something that will be visible by the camera?

**Comment by Rhonal89** [comment]
Here is another video explaining a little bit more https://youtu.be/kt0XwETcLJI

**Comment by Roxy-3D** [comment]
Can you change the GCode's file extension to .txt and upload it?  With a .txt extension you should be able to drag and drop it to the post.

**Comment by Rhonal89** [comment]
[Raspi7inch_Case.txt](https://github.com/MarlinFirmware/Marlin/files/966309/Raspi7inch_Case.txt)

**Comment by Roxy-3D** [comment]
Unfortunately...    I don't have Simplify-3D.      Can you try slicing it with Slic3r 1.2.7 or Slic3r 1.2.9 and try printing it?     It is difficult to offer support when I don't have the tools being used.

**Comment by Rhonal89** [comment]
[Raspi7inch_Case.txt](https://github.com/MarlinFirmware/Marlin/files/966329/Raspi7inch_Case.txt)

Hi Roxy, here is the one with slic3r 1.2.9 still does it. Also with other files. I tried with another version of rc8 I think and it prints great but it does not have ubl, How can I check the version of that one so I can post it.

**Comment by Roxy-3D** [comment]
Thanks!   And can you do a print using that GCode and take a video of any bad things it does?

**Comment by Rhonal89** [comment]
Yes, Roxy it does the same thing as the last video. But it does something differently than simplify. It seem like it has a -z hop but is not in the slic3r setting. Ill post a video here once I restart the print.

**Comment by Roxy-3D** [comment]
I might have more information...    Can you do a G26 and leave the mesh validation print on the bed.   And then do the same print where you see the funny stuff happen?    I might have duplicated what you are seeing on my printer...  If so...  It will be a lot easier to find the problem and fix it.

What I think might be happening is when the nozzle crosses a mesh line in a certain direction, the extruder is retracting...   And if it is tied to a certain direction of travel, that would explain why you are seeing it on every other layer.   The slicers alternate the direction of the fill layer by layer.

If this theory is true...  Both of those areas you say are flawed are going to be in very similar positions relative to the mesh points on the mesh validation pattern!!!!

(Unfortunately...   I have a very long print going...  It will be 7 or 8 hours before I can start digging in.   But if you find a pattern to the flawed areas relative to the mesh validation pattern...  I can start sooner!)

**Comment by Rhonal89** [comment]
Here is a video Roxy https://www.youtube.com/watch?v=sjsBchND9L0 You can skip to 1:50 for second layer

**Comment by Roxy-3D** [comment]
I only watched the first half of the video...  If there is anything important in the 2nd half please say so and I'll watch that too.     What you caught on the video is pretty close to what I saw.   Right now, I don't understand why it only happens in one direction, but when I find the bug...  It will probably make sense.  

I'm going to write an OpenScad program to generate a test pattern that should help aggravate the problem.    I would like to get this problem fixed before Thinky promotes RC-8's RCBugFix to Golden Master tomorrow.   But that may not be possible.   If the promotion happens before I find this bug...   This might be the first Bug Fix in the Golden Master!

I really really appreciate your help trying to figure this out!   Probably what is wrong is not a big deal to fix.  The problem is usually finding the bug.   But...  There is lots of debug code in place in the ubl_motion.cpp files.  So I think I'll be able to find the problem with a few hours of work...

**Comment by Rhonal89** [comment]
second half shows it better

**Comment by Roxy-3D** [comment]
OK...   I'll watch it now!

**Comment by Rhonal89** [comment]
I appreciate all the work you put into marlin. Im loving ubl

**Comment by Roxy-3D** [comment]
I agree with your analysis....    I'll get this annoying problem fixed ASAP!    When you are printing and you see the retraction happen...    Does it only do the retraction with the nozzle going in one direction?   Or does it do it with the nozzle going both directions?

**Comment by Rhonal89** [comment]
It looks like it does it in one direction. Can't tell clearly

**Comment by Roxy-3D** [comment]
@Rhonal89   I think I might have found the problem...   Can you go into ubl_motion.cpp and change these lines:
```cpp
    const bool inf_normalized_flag = NEAR_ZERO(on_axis_distance),
               inf_m_flag = NEAR_ZERO(dx);
```
to this:
```cpp
    bool inf_normalized_flag, inf_m_flag; 

    inf_normalized_flag = isinf(e_normalized_dist);
    inf_m_flag = isinf(m);
```
The original logic got changed in an attempt to compress the code with ternary operators.
As soon as you can check it out...  I would appreciate feed back on whether or not it fixed the problem because I would like to have this code 100% functional for the promotion to 'Golden Status'.

**Comment by Rhonal89** [comment]
Hi roxy, I tried the changes and it keeps happening.

**Comment by Roxy-3D** [comment]
OK...  I'll keep searching...

**Comment by Rhonal89** [comment]
Thank You!!

**Comment by Roxy-3D** [comment]
@Rhonal89    I can duplicate the problem.  And I have it narrowed down to just a few lines of GCode.  I've been adding debug code and looking at various values during the calculations...   I'm not there yet.  But I'm making slow and steady progress.

**Comment by Rhonal89** [comment]
Yes, yes. Thank You!! Roxy. I been thinking and looking.  Where can I support you and the marlin team for all the hard work you guys are doing in getting marlin to were it currently is.

**Comment by thinkyhead** [comment]
Keep me posted. Where does the issue seem to be centralized? Remember that Marlin has no concept of "layers." It just sees a Z move.

**Comment by Roxy-3D** [comment]
@thinkyhead 

> Keep me posted. Where does the issue seem to be centralized? Remember that Marlin has no concept of "layers." It just sees a Z move.

The problem is the extruder motor is actually going the wrong direction for part of the move in certain locations on the bed.   And it seems to be tied to crossing of mesh lines in certain directions.   The big problem is it hardly ever happens.   I'm not even sure it is happening in the mesh_buffer_line()  or ubl_motion.cpp file.   

But I've got a couple lines of gcode isolated that show the behavior.  (and even that is difficult to accomplish because pretty much everything works right.  To find the lines of gcode that cause the problem has taken a while.)   I'm trying to get macros defined in PronterFace so I can go back and forth and watch it happen....  And once that is fully confirmed...  I'll be adding lots of debug information and figure out why the stepper motor is going the wrong direction.

There is a chance the problem is down in the stepper motor code...  But I'll know more by the end of the day.  

**Found the bug:   Working a clean and simple fix....**

**Comment by Roxy-3D** [comment]
@Rhonal89    If you can...  Can you replace ubl_motion.cpp with this?   I think it is working for me.   I would like to hear if it works for you before I prepare a Pull Request and merge it.

<details><summary>New ubl_motion.cpp file</summary>

```cpp
/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
#include "MarlinConfig.h"

#if ENABLED(AUTO_BED_LEVELING_UBL)

  #include "Marlin.h"
  #include "ubl.h"
  #include "planner.h"
  #include <avr/io.h>
  #include <math.h>

  extern float destination[XYZE];
  extern void set_current_to_destination();

  static void debug_echo_axis(const AxisEnum axis) {
    if (current_position[axis] == destination[axis])
      SERIAL_ECHOPGM("-------------");
    else
      SERIAL_ECHO_F(destination[X_AXIS], 6);
  }

  void debug_current_and_destination(const char *title) {

    // if the title message starts with a '!' it is so important, we are going to
    // ignore the status of the g26_debug_flag
    if (*title != '!' && !ubl.g26_debug_flag) return;

    const float de = destination[E_AXIS] - current_position[E_AXIS];

    if (de == 0.0) return;

    const float dx = current_position[X_AXIS] - destination[X_AXIS],
                dy = current_position[Y_AXIS] - destination[Y_AXIS],
                xy_dist = HYPOT(dx, dy);

    if (xy_dist == 0.0) {
      return;
      //SERIAL_ECHOPGM("   FPMM=");
      //const float fpmm = de / xy_dist;
      //SERIAL_PROTOCOL_F(fpmm, 6);
    }
    else {
      SERIAL_ECHOPGM("   fpmm=");
      const float fpmm = de / xy_dist;
      SERIAL_ECHO_F(fpmm, 6);
    }

    SERIAL_ECHOPGM("    current=( ");
    SERIAL_ECHO_F(current_position[X_AXIS], 6);
    SERIAL_ECHOPGM(", ");
    SERIAL_ECHO_F(current_position[Y_AXIS], 6);
    SERIAL_ECHOPGM(", ");
    SERIAL_ECHO_F(current_position[Z_AXIS], 6);
    SERIAL_ECHOPGM(", ");
    SERIAL_ECHO_F(current_position[E_AXIS], 6);
    SERIAL_ECHOPGM(" )   destination=( ");
    debug_echo_axis(X_AXIS);
    SERIAL_ECHOPGM(", ");
    debug_echo_axis(Y_AXIS);
    SERIAL_ECHOPGM(", ");
    debug_echo_axis(Z_AXIS);
    SERIAL_ECHOPGM(", ");
    debug_echo_axis(E_AXIS);
    SERIAL_ECHOPGM(" )   ");
    SERIAL_ECHO(title);
    SERIAL_EOL;

  }

  void ubl_line_to_destination(const float &feed_rate, uint8_t extruder) {
    /**
     * Much of the nozzle movement will be within the same cell. So we will do as little computation
     * as possible to determine if this is the case. If this move is within the same cell, we will
     * just do the required Z-Height correction, call the Planner's buffer_line() routine, and leave
     */
    const float start[XYZE] = {
                  current_position[X_AXIS],
                  current_position[Y_AXIS],
                  current_position[Z_AXIS],
                  current_position[E_AXIS]
                },
                end[XYZE] = {
                  destination[X_AXIS],
                  destination[Y_AXIS],
                  destination[Z_AXIS],
                  destination[E_AXIS]
                };

    const int cell_start_xi = ubl.get_cell_index_x(RAW_X_POSITION(start[X_AXIS])),
              cell_start_yi = ubl.get_cell_index_y(RAW_Y_POSITION(start[Y_AXIS])),
              cell_dest_xi  = ubl.get_cell_index_x(RAW_X_POSITION(end[X_AXIS])),
              cell_dest_yi  = ubl.get_cell_index_y(RAW_Y_POSITION(end[Y_AXIS]));

    if (ubl.g26_debug_flag) {
      SERIAL_ECHOPAIR(" ubl_line_to_destination(xe=", end[X_AXIS]);
      SERIAL_ECHOPAIR(", ye=", end[Y_AXIS]);
      SERIAL_ECHOPAIR(", ze=", end[Z_AXIS]);
      SERIAL_ECHOPAIR(", ee=", end[E_AXIS]);
      SERIAL_CHAR(')');
      SERIAL_EOL;
      debug_current_and_destination(PSTR("Start of ubl_line_to_destination()"));
    }

    if (cell_start_xi == cell_dest_xi && cell_start_yi == cell_dest_yi) { // if the whole move is within the same cell,
      /**
       * we don't need to break up the move
       *
       * If we are moving off the print bed, we are going to allow the move at this level.
       * But we detect it and isolate it. For now, we just pass along the request.
       */

      if (!WITHIN(cell_dest_xi, 0, GRID_MAX_POINTS_X - 1) || !WITHIN(cell_dest_yi, 0, GRID_MAX_POINTS_Y - 1)) {

        // Note: There is no Z Correction in this case. We are off the grid and don't know what
        // a reasonable correction would be.

        planner.buffer_line(end[X_AXIS], end[Y_AXIS], end[Z_AXIS] + ubl.state.z_offset, end[E_AXIS], feed_rate, extruder);
        set_current_to_destination();

        if (ubl.g26_debug_flag)
          debug_current_and_destination(PSTR("out of bounds in ubl_line_to_destination()"));

        return;
      }

      FINAL_MOVE:

      /**
       * Optimize some floating point operations here. We could call float get_z_correction(float x0, float y0) to
       * generate the correction for us. But we can lighten the load on the CPU by doing a modified version of the function.
       * We are going to only calculate the amount we are from the first mesh line towards the second mesh line once.
       * We will use this fraction in both of the original two Z Height calculations for the bi-linear interpolation. And,
       * instead of doing a generic divide of the distance, we know the distance is MESH_X_DIST so we can use the preprocessor
       * to create a 1-over number for us. That will allow us to do a floating point multiply instead of a floating point divide.
       */

      const float xratio = (RAW_X_POSITION(end[X_AXIS]) - pgm_read_float(&(ubl.mesh_index_to_xpos[cell_dest_xi]))) * (1.0 / (MESH_X_DIST)),
                  z1 = ubl.z_values[cell_dest_xi    ][cell_dest_yi    ] + xratio *
                      (ubl.z_values[cell_dest_xi + 1][cell_dest_yi    ] - ubl.z_values[cell_dest_xi][cell_dest_yi    ]),
                  z2 = ubl.z_values[cell_dest_xi    ][cell_dest_yi + 1] + xratio *
                      (ubl.z_values[cell_dest_xi + 1][cell_dest_yi + 1] - ubl.z_values[cell_dest_xi][cell_dest_yi + 1]);

      // we are done with the fractional X distance into the cell. Now with the two Z-Heights we have calculated, we
      // are going to apply the Y-Distance into the cell to interpolate the final Z correction.

      const float yratio = (RAW_Y_POSITION(end[Y_AXIS]) - pgm_read_float(&(ubl.mesh_index_to_ypos[cell_dest_yi]))) * (1.0 / (MESH_Y_DIST));

      float z0 = z1 + (z2 - z1) * yratio;

      z0 *= ubl.fade_scaling_factor_for_z(end[Z_AXIS]);

      /**
       * If part of the Mesh is undefined, it will show up as NAN
       * in z_values[][] and propagate through the
       * calculations. If our correction is NAN, we throw it out
       * because part of the Mesh is undefined and we don't have the
       * information we need to complete the height correction.
       */
      if (isnan(z0)) z0 = 0.0;

      planner.buffer_line(end[X_AXIS], end[Y_AXIS], end[Z_AXIS] + z0 + ubl.state.z_offset, end[E_AXIS], feed_rate, extruder);

      if (ubl.g26_debug_flag)
        debug_current_and_destination(PSTR("FINAL_MOVE in ubl_line_to_destination()"));

      set_current_to_destination();
      return;
    }

    /**
     * If we get here, we are processing a move that crosses at least one Mesh Line. We will check
     * for the simple case of just crossing X or just crossing Y Mesh Lines after we get all the details
     * of the move figured out. We can process the easy case of just crossing an X or Y Mesh Line with less
     * computation and in fact most lines are of this nature. We will check for that in the following
     * blocks of code:
     */

    const float dx = end[X_AXIS] - start[X_AXIS],
                dy = end[Y_AXIS] - start[Y_AXIS];

    const int left_flag = dx < 0.0 ? 1.0 : 0.0,
              down_flag = dy < 0.0 ? 1.0 : 0.0;

    const float adx = left_flag ? -dx : dx,
                ady = down_flag ? -dy : dy;

    const int dxi = cell_start_xi == cell_dest_xi ? 0 : left_flag ? -1 : 1,
              dyi = cell_start_yi == cell_dest_yi ? 0 : down_flag ? -1 : 1;

    /**
     * Compute the scaling factor for the extruder for each partial move.
     * We need to watch out for zero length moves because it will cause us to
     * have an infinate scaling factor. We are stuck doing a floating point
     * divide to get our scaling factor, but after that, we just multiply by this
     * number. We also pick our scaling factor based on whether the X or Y
     * component is larger. We use the biggest of the two to preserve precision.
     */

    const bool use_x_dist = adx > ady;

    float on_axis_distance = use_x_dist ? dx : dy,
          e_position = end[E_AXIS] - start[E_AXIS],
          z_position = end[Z_AXIS] - start[Z_AXIS];

    const float e_normalized_dist = e_position / on_axis_distance,
                z_normalized_dist = z_position / on_axis_distance;

    int current_xi = cell_start_xi, current_yi = cell_start_yi;

    const float m = dy / dx,
                c = start[Y_AXIS] - m * start[X_AXIS];

    const bool inf_normalized_flag=isinf(e_normalized_dist),
               inf_m_flag=isinf(m);
    /**
     * This block handles vertical lines. These are lines that stay within the same
     * X Cell column. They do not need to be perfectly vertical. They just can
     * not cross into another X Cell column.
     */
    if (dxi == 0) {       // Check for a vertical line
      current_yi += down_flag;  // Line is heading down, we just want to go to the bottom
      while (current_yi != cell_dest_yi + down_flag) {
        current_yi += dyi;
        const float next_mesh_line_y = LOGICAL_Y_POSITION(pgm_read_float(&(ubl.mesh_index_to_ypos[current_yi])));

        /**
         * inf_m_flag? the slope of the line is infinite, we won't do the calculations
         * else, we know the next X is the same so we can recover and continue!
         * Calculate X at the next Y mesh line
         */
        const float x = inf_m_flag ? start[X_AXIS] : (next_mesh_line_y - c) / m;

        float z0 = ubl.z_correction_for_x_on_horizontal_mesh_line(x, current_xi, current_yi);

        z0 *= ubl.fade_scaling_factor_for_z(end[Z_AXIS]);

        /**
         * If part of the Mesh is undefined, it will show up as NAN
         * in z_values[][] and propagate through the
         * calculations. If our correction is NAN, we throw it out
         * because part of the Mesh is undefined and we don't have the
         * information we need to complete the height correction.
         */
        if (isnan(z0)) z0 = 0.0;

        const float y = LOGICAL_Y_POSITION(pgm_read_float(&(ubl.mesh_index_to_ypos[current_yi])));

        /**
         * Without this check, it is possible for the algorithm to generate a zero length move in the case
         * where the line is heading down and it is starting right on a Mesh Line boundary. For how often that
         * happens, it might be best to remove the check and always 'schedule' the move because
         * the planner.buffer_line() routine will filter it if that happens.
         */
        if (y != start[Y_AXIS]) {
          if (!inf_normalized_flag) {

//          on_axis_distance = y - start[Y_AXIS];                               
            on_axis_distance = use_x_dist ? x - start[X_AXIS] : y - start[Y_AXIS];

//          on_axis_distance = use_x_dist ? next_mesh_line_x - start[X_AXIS] : y - start[Y_AXIS];
//          on_axis_distance = use_x_dist ? x - start[X_AXIS] : next_mesh_line_y - start[Y_AXIS];

//          on_axis_distance = use_x_dist ? next_mesh_line_x - start[X_AXIS] : y - start[Y_AXIS];
//          on_axis_distance = use_x_dist ? x - start[X_AXIS] : next_mesh_line_y - start[Y_AXIS];


            e_position = start[E_AXIS] + on_axis_distance * e_normalized_dist;  
            z_position = start[Z_AXIS] + on_axis_distance * z_normalized_dist;
          }
          else {
            e_position = end[E_AXIS];
            z_position = end[Z_AXIS];
          }

          planner.buffer_line(x, y, z_position + z0 + ubl.state.z_offset, e_position, feed_rate, extruder);
        } //else printf("FIRST MOVE PRUNED  ");
      }

      if (ubl.g26_debug_flag)
        debug_current_and_destination(PSTR("vertical move done in ubl_line_to_destination()"));

      //
      // Check if we are at the final destination. Usually, we won't be, but if it is on a Y Mesh Line, we are done.
      //
      if (current_position[X_AXIS] != end[X_AXIS] || current_position[Y_AXIS] != end[Y_AXIS])
        goto FINAL_MOVE;

      set_current_to_destination();
      return;
    }

    /**
     *
     * This block handles horizontal lines. These are lines that stay within the same
     * Y Cell row. They do not need to be perfectly horizontal. They just can
     * not cross into another Y Cell row.
     *
     */

    if (dyi == 0) {             // Check for a horizontal line
      current_xi += left_flag;  // Line is heading left, we just want to go to the left
                                // edge of this cell for the first move.
      while (current_xi != cell_dest_xi + left_flag) {
        current_xi += dxi;
        const float next_mesh_line_x = LOGICAL_X_POSITION(pgm_read_float(&(ubl.mesh_index_to_xpos[current_xi]))),
                    y = m * next_mesh_line_x + c;   // Calculate Y at the next X mesh line

        float z0 = ubl.z_correction_for_y_on_vertical_mesh_line(y, current_xi, current_yi);

        z0 *= ubl.fade_scaling_factor_for_z(end[Z_AXIS]);

        /**
         * If part of the Mesh is undefined, it will show up as NAN
         * in z_values[][] and propagate through the
         * calculations. If our correction is NAN, we throw it out
         * because part of the Mesh is undefined and we don't have the
         * information we need to complete the height correction.
         */
        if (isnan(z0)) z0 = 0.0;

        const float x = LOGICAL_X_POSITION(pgm_read_float(&(ubl.mesh_index_to_xpos[current_xi])));

        /**
         * Without this check, it is possible for the algorithm to generate a zero length move in the case
         * where the line is heading left and it is starting right on a Mesh Line boundary. For how often
         * that happens, it might be best to remove the check and always 'schedule' the move because
         * the planner.buffer_line() routine will filter it if that happens.
         */
        if (x != start[X_AXIS]) {
          if (!inf_normalized_flag) {

//          on_axis_distance = x - start[X_AXIS];
            on_axis_distance = use_x_dist ? x - start[X_AXIS] : y - start[Y_AXIS];

//          on_axis_distance = use_x_dist ? next_mesh_line_x - start[X_AXIS] : y - start[Y_AXIS];
//          on_axis_distance = use_x_dist ? x - start[X_AXIS] : next_mesh_line_y - start[Y_AXIS];

            e_position = start[E_AXIS] + on_axis_distance * e_normalized_dist;  // is based on X or Y because this is a horizontal move
            z_position = start[Z_AXIS] + on_axis_distance * z_normalized_dist;
          }
          else {
            e_position = end[E_AXIS];
            z_position = end[Z_AXIS];
          }

          planner.buffer_line(x, y, z_position + z0 + ubl.state.z_offset, e_position, feed_rate, extruder);
        } //else printf("FIRST MOVE PRUNED  ");
      }

      if (ubl.g26_debug_flag)
        debug_current_and_destination(PSTR("horizontal move done in ubl_line_to_destination()"));

      if (current_position[X_AXIS] != end[X_AXIS] || current_position[Y_AXIS] != end[Y_AXIS])
        goto FINAL_MOVE;

      set_current_to_destination();
      return;
    }

    /**
     *
     * This block handles the generic case of a line crossing both X and Y Mesh lines.
     *
     */

    int xi_cnt = cell_start_xi - cell_dest_xi,
        yi_cnt = cell_start_yi - cell_dest_yi;

    if (xi_cnt < 0) xi_cnt = -xi_cnt;
    if (yi_cnt < 0) yi_cnt = -yi_cnt;

    current_xi += left_flag;
    current_yi += down_flag;

    while (xi_cnt > 0 || yi_cnt > 0) {

      const float next_mesh_line_x = LOGICAL_X_POSITION(pgm_read_float(&(ubl.mesh_index_to_xpos[current_xi + dxi]))),
                  next_mesh_line_y = LOGICAL_Y_POSITION(pgm_read_float(&(ubl.mesh_index_to_ypos[current_yi + dyi]))),
                  y = m * next_mesh_line_x + c,   // Calculate Y at the next X mesh line
                  x = (next_mesh_line_y - c) / m; // Calculate X at the next Y mesh line
                                                  // (No need to worry about m being zero.
                                                  //  If that was the case, it was already detected
                                                  //  as a vertical line move above.)

      if (left_flag == (x > next_mesh_line_x)) { // Check if we hit the Y line first
        //
        // Yes!  Crossing a Y Mesh Line next
        //
        float z0 = ubl.z_correction_for_x_on_horizontal_mesh_line(x, current_xi - left_flag, current_yi + dyi);

        z0 *= ubl.fade_scaling_factor_for_z(end[Z_AXIS]);

        /**
         * If part of the Mesh is undefined, it will show up as NAN
         * in z_values[][] and propagate through the
         * calculations. If our correction is NAN, we throw it out
         * because part of the Mesh is undefined and we don't have the
         * information we need to complete the height correction.
         */
        if (isnan(z0)) z0 = 0.0;

        if (!inf_normalized_flag) {
          on_axis_distance = use_x_dist ? x - start[X_AXIS] : next_mesh_line_y - start[Y_AXIS];
          e_position = start[E_AXIS] + on_axis_distance * e_normalized_dist;
          z_position = start[Z_AXIS] + on_axis_distance * z_normalized_dist;
        }
        else {
          e_position = end[E_AXIS];
          z_position = end[Z_AXIS];
        }
        planner.buffer_line(x, next_mesh_line_y, z_position + z0 + ubl.state.z_offset, e_position, feed_rate, extruder);
        current_yi += dyi;
        yi_cnt--;
      }
      else {
        //
        // Yes!  Crossing a X Mesh Line next
        //
        float z0 = ubl.z_correction_for_y_on_vertical_mesh_line(y, current_xi + dxi, current_yi - down_flag);

        z0 *= ubl.fade_scaling_factor_for_z(end[Z_AXIS]);

        /**
         * If part of the Mesh is undefined, it will show up as NAN
         * in z_values[][] and propagate through the
         * calculations. If our correction is NAN, we throw it out
         * because part of the Mesh is undefined and we don't have the
         * information we need to complete the height correction.
         */
        if (isnan(z0)) z0 = 0.0;

        if (!inf_normalized_flag) {
          on_axis_distance = use_x_dist ? next_mesh_line_x - start[X_AXIS] : y - start[Y_AXIS];
          e_position = start[E_AXIS] + on_axis_distance * e_normalized_dist;
          z_position = start[Z_AXIS] + on_axis_distance * z_normalized_dist;
        }
        else {
          e_position = end[E_AXIS];
          z_position = end[Z_AXIS];
        }

        planner.buffer_line(next_mesh_line_x, y, z_position + z0 + ubl.state.z_offset, e_position, feed_rate, extruder);
        current_xi += dxi;
        xi_cnt--;
      }
    }

    if (ubl.g26_debug_flag)
      debug_current_and_destination(PSTR("generic move done in ubl_line_to_destination()"));

    if (current_position[X_AXIS] != end[X_AXIS] || current_position[Y_AXIS] != end[Y_AXIS])
      goto FINAL_MOVE;

    set_current_to_destination();
  }

#endif
```
</details>

**Comment by Rhonal89** [comment]
Hi Roxy, Here is a video https://www.youtube.com/watch?v=i477Xxrcv7k Printer is moving out of print area

**Comment by Roxy-3D** [comment]
Thanks!!!!  I'll watch again in the morning...   I was able to print the test print with rectangles at different angles....   It is very possible I don't have things right.   But I do understand what is wrong....

**Comment by Rhonal89** [comment]
Thank You!! Roxy. I was just looking at the code wishing I knew what I was looking at.

**Comment by Roxy-3D** [comment]
I'm using that code right now to do a horribly complicated print.   I'll post pictures in the morning.   Can you grab the very most current RCBugFix and get that up and running on your printer?   Because the Pull Request I do will be against that.   I'm pretty sure I've got that bug you found in the other video fixed.

**Comment by Roxy-3D** [comment]
https://github.com/MarlinFirmware/Marlin/pull/6540

**Comment by Rhonal89** [comment]
Hi Roxy, I updated to the latest marlin rc8fix and it's printing great. Now to tune ubl some more. Thank You!! For all the help.

**Comment by Roxy-3D** [comment]
You wouldn't believe how hard that bug was to find.   UBL has some optimizations in the calculations for the Z-Height correction.   When the nozzle is moving in a purely horizontal or vertical direction, you know you are only crossing X-Mesh lines or Y-Mesh lines.   So things can be made easier on the CPU.

But...  That doesn't mean the nozzle is moving horizontal or vertical.  It just means the nozzle is only crossing mesh lines in one direction or the other.     The case we had was 'horizontal movement' from one mesh cell to the next.  But the actual movement was mostly vertical.    And the wrong optimization code was assuming it could use the wrong number....    Aaaauuughhhhh!

I think that one is behind us now!   Thank You for the help!

**Comment by Rhonal89** [comment]
I bet it took lots of work. And thanks for the explanation I get it better and Thank You!! for all your hard work Roxy.
