### ISSUE TITLE
How many extruders does the Dual X Carriage Support?

### ISSUE THREAD

**Issue by kcheeeung** [MarlinFirmware/Marlin#6496]
How many extruders does the Dual X Carriage Support?

I was able to compile 4 extruders with dual x carriage enabled? What will happen? Does it work? Is there 2 on each carriage? 3 on the one, 1 on the other?

**Comment by kcheeeung** [comment]
Hello everyone I rephrased my question.
@Bob-the-Kuhn Would you happen to know?

**Comment by thinkyhead** [comment]
5 extruders are supported. However, the special modes of Dual X assume the first extruder is alone, and all other extruders are on the 2nd carriage.

**Comment by kcheeeung** [comment]
Thanks for the information!
