### ISSUE TITLE
UBL not probing first y row

### ISSUE THREAD

**Issue by MaxRink** [MarlinFirmware/Marlin#6498]
Settings and result after P1:

> SENDING:M503
echo:  G21 ; Units in mm
echo:Filament settings: Disabled
echo:  M200 D3.00
echo:  M200 D0
echo:Steps per unit:
echo:  M92 X200.00 Y200.00 Z3200.00 E289.00
echo:Maximum feedrates (units/s):
echo:  M203 X200.00 Y200.00 Z3.00 E25.00
echo:Maximum Acceleration (units/s2):
echo:  M201 X3000 Y3000 Z100 E10000
echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P3000.00 R3000.00 T3000.00
echo:Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_ms> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
echo:  M205 S0.00 T0.00 B20000 X10.00 Y10.00 Z0.40 E2.00
echo:Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:Unified Bed Leveling:
echo:  M420 S1 Z0.00
UBL is Active
Active Mesh Slot: 1
z_offset: 0.000000
EEPROM can hold 8 meshes.
GRID_MAX_POINTS_X  10
GRID_MAX_POINTS_Y  10
UBL_MESH_MIN_X  (9 + 15)=24
UBL_MESH_MIN_Y  (0 + 15)=15
UBL_MESH_MAX_X  (207 - (15))=192
UBL_MESH_MAX_Y  (210 - (15))=195
MESH_X_DIST  18.67
MESH_Y_DIST  20.00
echo:Material heatup parameters:
echo:  M145 S0 H180 B70 F0
  M145 S1 H240 B110 F0
echo:PID settings:
echo:  M301 P12.36 I1.31 D29.11
echo:Z-Probe Offset (mm):
echo:  M851 Z0.00
>>>G29 O
SENDING:G29 O
Bed Topography Report:
(0,9)                                                                                                    (9,9)
(24,15)                                                                                                (192,195)
    .      0.406    0.422    0.444    0.447    0.436    0.411    0.388    0.371    0.339

    .      0.290    0.316    0.322    0.330    0.325    0.316    0.285    0.260    0.220

    .      0.219    0.216    0.228    0.216    0.221    0.213    0.191    0.155    0.115

    .      0.136    0.127    0.121    0.116    0.118    0.115    0.087    0.080    0.022

    .      0.078    0.059    0.036    0.038    0.041    0.047    0.013    0.000   -0.061

    .      0.048    0.021  [ 0.004]  -0.003    0.009   -0.012   -0.029   -0.048   -0.116

    .      0.036    0.015    0.002   -0.004    0.005    0.003   -0.043   -0.062   -0.132

    .      0.051    0.053    0.038    0.034    0.018    0.003   -0.033   -0.078   -0.114

    .      0.073    0.081    0.059    0.063    0.068    0.030   -0.004   -0.041   -0.083

    .      0.103    0.121    0.134    0.141    0.117    0.103    0.066    0.038    0.001
(24,15)                                                                                                    (192,15)
(0,0)                                                                                                       (9,0)

**Comment by Roxy-3D** [comment]
That is expected behavior.    The probe can not reach those locations.  So it can not fill in the values for you.

But...  Not to worry...  There is an easy to command that will finish filling in your mesh.   Please do a G29 P3 O  and that will invoke the 'Smart Fill' command.   Save that mesh, and you should be able to continue to the G26 C P O3.0  Mesh Validation Pattern.    Once you have the Mesh Validation Pattern printed on the bed, you can edit areas of the mesh that are not perfect by moving the nozzle to the 'bad' area, and doing a G29 P4 R O
