### ISSUE TITLE
ultralcd.cpp missing include for BLTouch support

### ISSUE THREAD

**Issue by mperdue** [MarlinFirmware/Marlin#6518]
I got an error when compiling the latest rcbugfix telling me that endstops was not defined. The include for endstops.h seems to have been removed.

I added the following @ line 37 in ultralcd.cpp to correct the issue.

#if ENABLED(BLTOUCH)
  #include "endstops.h"
#endif

Also, BLTouch strings for stow and deploy need to be added to the language files.

**Comment by bgort** [comment]
Just fixed these in #6517.

Even with them fixed, Marlin freezes at startup after deploying the BLTouch once with a 'KILLED.  Printer Halted.'  Can you let me know if you're seeing that also?

**Comment by Roxy-3D** [comment]
> Marlin freezes at startup after deploying the BLTouch once with a 'KILLED. 

I added some code to turn the heaters off while the BL-Touch was probing because it was causing accuracy  problems with the HAL effect sensor.    That code got altered in: 
 https://github.com/MarlinFirmware/Marlin/pull/6491  To do a Kill.  

- Simplify BLTOUCH_HEATERS_OFF code. (#6476) If anything is amiss, simply call kill.

**Comment by thinkyhead** [comment]
> That code got altered in: #6491 To do a Kill.

Sorry, forgot to clear `next_emi_protection` back to zero. The `kill` was also to see if the function was being used redundantly in any setups. Apparently so. Patching to avoid that….

> accuracy problems with the HAL effect sensor

"Hall effect." Named after Edwin Hall.

**Comment by thinkyhead** [comment]
Should be resolved now. Please confirm.

**Comment by bgort** [comment]
Thanks.  Will confirm it's working shortly.

**Comment by bgort** [comment]
984c210dec4fdc03d9f5df77ad897cef8c64f692 still has the problem.

Commenting out BLTOUCH_HEATERS_OFF fixes it.  I'll go looking for the issue and will see about fixing it after I get some Monday-morning things out of the way.

**Comment by thinkyhead** [comment]
Should be all fixed now!
