### ISSUE TITLE
MBL and EEPROM Settings

### ISSUE THREAD

**Issue by james94jeans2** [MarlinFirmware/Marlin#6522]
When using Mesh Bed Leveling and saving the settings to EEPROM not the full mbl.status is saved, but rather only the has_mesh bit.

This results in the printer forgetting about mbl beeing turned on.

Solutions could be to save the full status integer (EEPROM waste?) or storing the mbl.is_active bit instead of the mbl.has_mesh bit and when loading assuming that there is a mesh when mbl is active.

Another thing concerning MBL: 

Maybe there should be a hint, that MBL and manual_probing should not be enabled at the same time.

See: #6531 

EDIT/ADDED:
I am also wondering about the reactivate bit. When using G28 mbl gets deactivated, but due to the reactivate bit not beeing set does not get reactivated after homing.

**Comment by Tannoo** [comment]
See this PR: #6537.

**Comment by thinkyhead** [comment]
Printer starts up in unknown state with leveling off. `G28` includes in its specification that it disables bed leveling (though we can make that an optional behavior in future). `M420 S1` should be used to enable leveling when desired. It's recommended to add this command to your slicer's Start G-code — in Cura this is stored as part of the printer profiles.
