### ISSUE TITLE
KILLED. PRINTER HALTED

### ISSUE THREAD

**Issue by nesalkiN** [MarlinFirmware/Marlin#6526]
Hello,

I see many changes in RCBugFix the last day. I used the new config and transferred my settings to the new config structure. Stuff has changed places. :)

Now, the printer halts on power on, after the splash screen I get "KILLED. PRINTER HALTED, Please reset."
I can't find what I need to change to get it working again. I used my older config straight off with the latest checkout and still getting the same message. 

Log:

> Recv: echo: M851 Z-1.00
> Recv: Error:Printer halted. kill() called!

I have no "KILL_PIN" defined.

**Comment by thinkyhead** [comment]
Please post your configuration files. You can either Zip them together or append `.txt` to the filenames, and then Github will allow you to drop them on the reply field.

**Comment by nesalkiN** [comment]
This is my old config that I used with older RCBugFix:
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/968206/Marlin.zip)
Just dropping it in with the latest code kills the printer.

And this is my new configs:
[Marlin_new.zip](https://github.com/MarlinFirmware/Marlin/files/968209/Marlin_new.zip)
Same kill with these.

Left pins and boards file out here.

**Comment by thinkyhead** [comment]
Try [this branch](https://github.com/thinkyhead/Marlin/tree/rc_cleanups_2) and let me know if it fixes the issue.

**Comment by thinkyhead** [comment]
Think I got it! Applied the patch to the main branch.

`BLTOUCH` does a deploy/stow on initialization, and there was a glitch in the new bltouch-vs-heaters code. Should be good now!

**Comment by nesalkiN** [comment]
Ah, great. Thanks! Will try when done printing. 👍 

Edit
Btw, almost no compiler warnings except:

```
C:\Users\Niklas\AppData\Local\Temp\arduino_build_661069\sketch\stepper.cpp: In static member function 'static void Stepper::babystep(AxisEnum, bool)':

C:\Users\Niklas\AppData\Local\Temp\arduino_build_661069\sketch\stepper.cpp:1320:13: warning: unused variable 'old_dir' [-Wunused-variable]

     uint8_t old_dir;

             ^
```

and
```
C:\Users\Niklas\AppData\Local\Temp\arduino_build_661069\sketch\temperature.cpp: In static member function 'static void Temperature::isr()':

C:\Users\Niklas\AppData\Local\Temp\arduino_build_661069\sketch\temperature.cpp:1621:58: warning: suggest parentheses around '+' inside '>>' [-Wparentheses]

           soft_pwm_fan[0] = (soft_pwm_fan[0] & pwm_mask) + fanSpeedSoftPwm[0] >> 1;

                                                          ^
```

**Comment by nesalkiN** [comment]
And it works! Thanks.

**Comment by nesalkiN** [comment]
Spoke to soon. Now it does not heat the bed.
The display show target temp 60 but the temperature does not change and the result is halted printer, heating failed. I have disabled the turning off bed and extruder while probing but I heat before probing.

**Comment by cbusillo** [comment]
I have the same issue.  RCBugFix is up to date.  Turning off BLTOUCH_HEATERS_OFF fixes it for now.

**Comment by nesalkiN** [comment]
I have BLTOUCH_HEATERS_OFF disabled but the bed or hotend does not heat up. Will try latest code now.

**Comment by nesalkiN** [comment]
Nope, no heating with BLTOUCH_HEATERS_OFF disabled. Can set target temp but the bed or hotend does not heat up. @bgort s fix did not help.

**Comment by bgort** [comment]
Anything else unusual going on, @NiklasOlofsson?  It's -just- that the heaters aren't heating?  No more 'KILLED' message?

**Comment by nesalkiN** [comment]
Not the first problem, got killed at boot time. That's gone.
Now you get "heating failed" after some time. Target temps change but no power is going to the hotend or bed.

**Comment by bgort** [comment]
Your pins_GT2560.h are identical between old-working and new-notworking?  

What was the commit id of the last version that worked for you?

**Comment by nesalkiN** [comment]
Yes. No changes to the pins.

I don't know commit really. Checked out 2017-04-30 20:23 CEST +02:00 (looking at the file create date)

Not alone :)
https://github.com/MarlinFirmware/Marlin/issues/6544

**Comment by bgort** [comment]
4/30 20:23 is working or non-working?

**Comment by nesalkiN** [comment]
Working.

The thing I did was transfer my config to the new layout of the Configuration.h-file.
Also tried my config from the working version and the latest code and that's no go.

**Comment by bgort** [comment]
If you can, in the directory where you checked out the working version, do a 'git log' and the commit id will be the first line output.

**Comment by nesalkiN** [comment]
Sorry, I can't. Downloaded as zip.

**Comment by bgort** [comment]
If you still have the zipfile, the commit is in the attached notes, like here:

![screenshot 2017-05-02 12 06 17](https://cloud.githubusercontent.com/assets/8062568/25627203/d94a1fa2-2f2f-11e7-94c8-664564399cc7.png)

The '99b1...' is the last commit included in the archive.

Sorry for the hassle -- just trying to get to what works for you so I can compare it with what doesn't work.

**Comment by nesalkiN** [comment]
I don't have the zip file. Where does that note come from?

I should be able to download and test the version I think it should be. Printing atm (44 min left)

**Comment by bgort** [comment]
It's embedded in the archive as comments.  It's not in a separate file, as far as I know.

**Comment by nesalkiN** [comment]
This is the re-zipped dir containing my working version
[Marlin-RCBugFix-old.zip](https://github.com/MarlinFirmware/Marlin/files/971071/Marlin-RCBugFix-old.zip)

**Comment by bgort** [comment]
Your working version's pins.h contains:
```
#elif MB(GT2560)
  #include "pins_GT2560.h"
```

While the latest doesn't.

So unless you're adding that, your pins aren't defined at all.  I assume that's the issue.

**Comment by nesalkiN** [comment]
What last? I add it myself and it's there in my latest (non working) checkout.
[Marlin-RCBugFix-new-2maj-1446.zip](https://github.com/MarlinFirmware/Marlin/files/971261/Marlin-RCBugFix-new-2maj-1446.zip)

**Comment by nesalkiN** [comment]
This is the same problem?
https://github.com/MarlinFirmware/Marlin/issues/6544

**Comment by bgort** [comment]
I was comparing to the latest RCBugFix.  I understand now -- you're adding your pins_GT2560.h.  Didn't realize that.

**Comment by bgort** [comment]
Send the .zip of the non-working version, if you don't mind.

**Comment by nesalkiN** [comment]
Yep. I have the "About printer" menu activated and I did not like it when it said "Ultimaker" in "Board Info". ;)

I have posted the non working version ^^

**Comment by bgort** [comment]
I mean the whole directory - not just the configs.

**Comment by nesalkiN** [comment]
In my post above I have posted the full dir here:
https://github.com/MarlinFirmware/Marlin/issues/6526#issuecomment-298697774


I can attach it again:
[Marlin-RCBugFix-new-2maj-1446.zip](https://github.com/MarlinFirmware/Marlin/files/971315/Marlin-RCBugFix-new-2maj-1446.zip)

**Comment by bgort** [comment]
Ahh -- you edited it and I hadn't refreshed.  Got it now.

**Comment by nesalkiN** [comment]
Yeah, sorry. Posting before thinking. ;)

**Comment by bgort** [comment]
No worries.

**Comment by bgort** [comment]
I'm stumped right now.  In both working and non-working you have the new BLTOUCH_HEATERS_OFF disabled, and nothing else that touches the heaters has been changed between the versions.

I'll circle back to this in a bit.

**Comment by nesalkiN** [comment]
Well. Ok, I feel stupid, again.

Did not do M502 -> M500 as I always do when updating the FW...... 🥇
And yes, that did it! Now working again.

**Comment by bgort** [comment]
Haha.  I almost suggested that, but thought 'surely he did....' and moved on .. glad you found it!

**Comment by nesalkiN** [comment]
Of course I did................................. ;)

Thanks for looking in to it. Wasting your time. Sorry. ;)

**Comment by bgort** [comment]
No worries.  It happens!

**Comment by sathishcores** [comment]
Can anyone solve my prb

**Comment by sathishcores** [comment]
Printer halted kill called

**Comment by AnHardt** [comment]
Yes - you can.

You can usually find the reason in the serial output - right before the kill message.

**Comment by SRIRAM134** [comment]
Hello, I m abhay...I have a DIY 3d printer (leadscrew driven)... Whenever I give print, the printer homes x,y and z axes and then after lots and lots of "echo:busy processing" messages, finally this comes "ERORR: Heating failed, Heating ID 0" and ERROR: Printer halted!.... 
I have J-head E3d hotend , no heated bed....
Please help.....

**Comment by AnHardt** [comment]
@SRIRAM134 
There is no "J-head E3d hotend". It's either or - even when the Asian sellers try to make you believe the opposite. When they talk about "J-head E3d hotend" they mean a not specified random "hotend". They just include both of the types to be found better.

Having said that, it's most likely you don't know what thermistor type you have. (Most likely a 11 or 13)
At first make a reality check if the measured temperatures can be about right.
Is the heater getting warm at all, when you try to heat it.
Configs please.
