### ISSUE TITLE
#define CONTROLLERFAN_PIN

### ISSUE THREAD

**Issue by Tannoo** [MarlinFirmware/Marlin#6534]
This should be removed from `configuration_adv.h` and put into each board pins files.
OR, removed from the `pins_AZEEG_X3_PRO.h` file.

It is currently in the `pins_AZEEG_X3_PRO.h` file as:
`#define CONTROLLERFAN_PIN   4 // Pin used for the fan to cool motherboard (-1 to disable)`
while also in `configuration_adv.h` file as:
`#define CONTROLLERFAN_PIN -1 //Pin used for the fan to cool controller (-1 to disable)`.

**Comment by Mind-FuLL** [comment]
I use the AZEEG_X3_PRO and notice this issue as well.  I always comment out the one in the pins file.

**Comment by thinkyhead** [comment]
Patched into a proper "feature" with #6556, including making the default pins conditional in those pins files.
