### ISSUE TITLE
Dual Z Endstop problem

### ISSUE THREAD

**Issue by 8Roman8** [MarlinFirmware/Marlin#6542]
Hi, I have a small problem.
I have a dual Z axis, with only one endstop, everything works as it should, but when I turn on dual z endstop, the printer drives the endstop on a side and stops, on the other side, the motor doesnt stop, even though The second endstop is triggered, with M119 the status can always be read correctly.
Sry for my english, i hope you understand what i  mean^^

Firmware: rc bugfix

**Comment by Tannoo** [comment]
Can you attach your configuration files?

**Comment by 8Roman8** [comment]
I don't know if that is important, i use optical endstops on the Z axis.

[My configuration.zip](https://github.com/MarlinFirmware/Marlin/files/972754/My.configuration.zip)

**Comment by 8Roman8** [comment]
This was my mistake, i connected the both endstops incorrectly to my board.
