### ISSUE TITLE
[FR] Dynamic Hotend Cooling Fan Speed

### ISSUE THREAD

**Issue by GadgetNutt** [MarlinFirmware/Marlin#6555]
I imagine I might get some flak for this but here it goes.

I have to slow down the cooling fan on my E3D v6 hotend in order to get it up to higher temperatures like 270.  Perhaps a feature could be to automatically adjust the heatsink cooling fan if the temperature won't rise during heat up.  Slow it down bit by bit until the heater block gets to temperature.

Thoughts on this?

**Comment by psavva** [comment]
You should control your fan view your Slicer.
Which slicing software are you using?

**Comment by oysteinkrog** [comment]
I think this is not a good idea, it's a hardware problem which should not be fixed in software.
Wrap/insulate your heater block, e.g. use a E3D sock.

**Comment by GadgetNutt** [comment]
Already use 24V heater cartridge AND E3D sock.

**Comment by alexborro** [comment]
Use a 12V cartridge powered by 24V. Limit the output PWM to about 128 (50%)
and you will have about twice the cartridge rated power.

You will need to adjust the PID as well.
And make sure the cables can carry twice the cartridge rated current.

Cheers

Alex.

Em 3 de mai de 2017 09:46, "Greg Nutt" <notifications@github.com> escreveu:

**Comment by nealpalmer** [comment]
I asked for the same thing.  It should be pretty simple to have the cooling fan speed limited (i.e. PID algorithm) to keep the hot-end PWM at about 75%.

**Comment by thinkyhead** [comment]
One wonders how this would affect PID tuning without first tuning with this feature enabled as part of `M303`.

**Comment by boelle** [comment]
i wonder if the fan is not cooling the block instead of under the block

@timeshell have you check if the duct is designed correctly?

**Comment by InsanityAutomation** [comment]
Adaptive fan slowing which was merged recently fulfills this request.

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

as @InsanityAutomation said its fullfilled by adaptive fan slowing
