### ISSUE TITLE
Feature Jogging Mode 

### ISSUE THREAD

**Issue by w4sepp** [MarlinFirmware/Marlin#6561]
Is it possible to implement a  jogging mode as the new GRBL jogging mode ? 

Jogging Mode : The new jogging commands are independent of the g-code parser, so that the parser state doesn't get altered and cause a potential crash if not restored properly. Documentation is included on how this works and how it can be used to control your machine via a joystick or rotary dial with a low-latency, satisfying response.

**Comment by Tannoo** [comment]
How many times are you going to ask the same thing? #6532
