### ISSUE TITLE
[Being a pest] Are we there yet?

### ISSUE THREAD

**Issue by mperdue** [MarlinFirmware/Marlin#6565]
I'm waiting till you guys say this is gold before I make my next download. I'm assuming it's very close because the last one I pulled down looks really good. Nice work to all of you who have been working on this.

**Comment by thinkyhead** [comment]
I'm working on the release notes now… should be out tonight at some point. 😁

**Comment by mperdue** [comment]
Great news. Again, you guys have really done a great job on this. It's much appreciated.
