### ISSUE TITLE
SD card printing

### ISSUE THREAD

**Issue by longle2710** [MarlinFirmware/Marlin#6575]
When i click on a file to print, the machine rebooted as of i hit the reset button

**Comment by nesalkiN** [comment]
It might be the same problem as described here:
https://github.com/MarlinFirmware/Marlin/issues/6571
Something is bugging out

**Comment by longle2710** [comment]
Thank you, I hope we can solve it soon.

**Comment by houseofbugs** [comment]
I have this same issue on my MKS and Melzi boards.

**Comment by stevereno30** [comment]
I have the exact same problem with my machine. I'm using an Arduino Mega with a RAMPS 1.4. 

The odd thing is I did not have this problem at all with 1.1.0 RC8.

**Comment by fred2088** [comment]
same here, got reboot from 1.1 release, no problem revert to rc8

**Comment by bgort** [comment]
Have you guys tried the bugfix-1.1.x branch?

**Comment by stevereno30** [comment]
I just loaded the bugfix-1.1.x branch and it works fine. Thanks for the tip!
