### ISSUE TITLE
M206 has no effect

### ISSUE THREAD

**Issue by SuperMechaCow** [MarlinFirmware/Marlin#6576]
Suddenly, without warning, the M206 home offset stopped working and nothing I do has any effect on it.

The firmware is set to offset X and Y homing positions my -23 and -30 respectively. My toolhead sits outside of the print area. When I home and then tell it to move the toolhead it normally moves it to the bottom-left of the bed and sets that position to 0,0 before completing the move, as expected.

However now, with no warning or changes, it always uses 0 and 0 as the X and Y home offsets no matter what I do. This causes the inductive Z-probe to miss the bed by 30 units on the Y axis and causes a bed crash while probing with G29. It also causes the bed to overshoot and grind when moving the Y axis all the way forward.

M502 restores the M206 offset to 0,0,0, which is not what is set in the firmware. Changing M206 can be seen in M503 and in the EEPROM saved settings, but it has zero effect on the actual home offset. The Tool is always homing to the wrong position no matter what.

You can see in this image a vague white line to the left of the toolhead in the painter's tape. This is exactly 10 units from 0,0. The image is where the toolhead keeps homing.

I am controlling this through Octoprint remotely, but again, I have changed nothing in the last 24 hours that would effect the home offset.

**Comment by FATALHERMIT** [comment]
@SuperMechaCow what image?

**Comment by ellisgl** [comment]
I'm having this same issue with 1.1.5

**Comment by thinkyhead** [comment]
Please test with current `bugfix-1.1.x` and if the issue is fixed please close.

**Comment by boelle** [comment]
@SuperMechaCow is this still an issue with latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@SuperMechaCow i just used M206 and it works fine

**Comment by SuperMechaCow** [comment]
Please close. I fixed this so long ago I forgot the solution

**Comment by p3p** [comment]
That would be your job @SuperMechaCow, you will see the close button at the bottom.

**Comment by SuperMechaCow** [comment]
I am such an _idiot_ today
