### ISSUE TITLE
Update Travis?

### ISSUE THREAD

**Issue by Tannoo** [MarlinFirmware/Marlin#6577]
Now that we have the new version after several years, why not update Travis to the times also?
from:
`wget http://downloads-02.arduino.cc/arduino-1.6.10-linux64.tar.xz`
to:
`wget http://downloads-02.arduino.cc/arduino-1.8.2-linux64.tar.xz`

**Comment by mtowara** [comment]
while I think some backward compability isn't all that bad the following change probably helps simplifying stuff:

ARDUINO 1.8.0 - 2016.12.20
* Linux: running in command line mode doesn't require an X11 display anymore

@thinkyhead and I toyed with the travis a bit in #6373 so some change will be coming soon anyways.
