### ISSUE TITLE
Marlin 1.1.x - E3D PT100 and Amp

### ISSUE THREAD

**Issue by TGMods** [MarlinFirmware/Marlin#6582]
I have just upgraded to Marlin 1.1.x and I have a problem with the temperature reported on my LCD as seen in the second picture. The temperature reported is 100C and I use Temperature Sensor 20
#define TEMP_SENSOR_0 20
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_BED 11

I reinstalled RCBugfix dated 23/03/2017 and the temperature reported is 28C as seen in the first picture. I use the same temperature sensor number.
#define TEMP_SENSOR_0 20
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_BED 11

Has there been a change to the temperature sensor numbering in Marlin 1.1.x?

![hypercube-marlin-rcbugfix_17-03-23](https://cloud.githubusercontent.com/assets/15638966/25721090/28866322-3107-11e7-9cd6-56be7f892bfe.jpg)

![marlin_1 1 x](https://cloud.githubusercontent.com/assets/15638966/25721154/5d048aa2-3107-11e7-9ec8-c55f2674d614.jpg)

**Comment by Bob-the-Kuhn** [comment]
Check to see if the internal pullup is enabled for that pin.  That'll throw the reading off in the positive direction.

**Comment by TGMods** [comment]
@Bob-the-Kuhn Sorry, my bad. I forgot to change the pins.h file.
Thank you anyway
