### ISSUE TITLE
Menu unresponsive while printing from octoprint (kinda)

### ISSUE THREAD

**Issue by Radexito** [MarlinFirmware/Marlin#6588]
So i applied the newest marlin + fix for OctoPrint and my Tevo Tarantula is displaying "E1 Heating" while printing and i cannot change speed %, i can go into the menu fine

also this might be caused by OctoPrint and not marlin unsure of this.

**Comment by thinkyhead** [comment]
"E1 Heating" is normal. I presume you can change % now…?
