### ISSUE TITLE
Temperature setting codes causing restart

### ISSUE THREAD

**Issue by alekseigolikov** [MarlinFirmware/Marlin#6591]
printing from SD
same codes worked properly on RC8.
on 1.1.x all 3 causing restart: 
M190 S80
M104 S240
M109 S240

**Comment by bgort** [comment]
Try the bugfix-1.1.x branch.

**Comment by fred2088** [comment]
me 2 and no code from bugfix-1.1 ...

**Comment by alekseigolikov** [comment]
works after latest pull

**Comment by ashthespy** [comment]
I seem to be facing similar issues
`M104 Sxx` seems to reset my board. I tried both the `1.1.x` and `bugfix-1.1.x` branches but had no luck. Using an Azteeg X3 board.
Any pointers to debug?
