### ISSUE TITLE
Enabling #define RGB_LED causes error when compiling

### ISSUE THREAD

**Issue by markdoll01** [MarlinFirmware/Marlin#6593]
When Enabling #define RGB_LED in version 1.1.x, the following compiling error occurs:

Marlin_main.cpp: In function 'void gcode_M190()':

Marlin_main.cpp:6890: error: expected 'while' before 'float'

         const float temp_diff = fabs(target_temp - temp);

               ^

**Comment by steleebrooks** [comment]
I also have the same issue, this showed when enabling the heated bed

Thanks

**Comment by Aethelstan2000** [comment]
Hi, same issue here. Only changes to to Configuration.h are 
```
#define TEMP_SENSOR_BED 1
#define RGB_LED
```

**Comment by ellensp** [comment]
Looking just above that error see in Marlin_main.cpp

      #if ENABLED(PRINTER_EVENT_LEDS)
        // Gradually change LED strip from blue to violet as bed heats up
        if (!wants_to_cool) {
          const uint8_t red = map(constrain(temp, start_temp, target_temp), start_temp, target_temp, 0, 255);
          if (red != old_red) set_led_color((old_red = red), 0, 255);
        }
      }
      #endif


the } directly above the # in #endif is in error. Delete that line (line 6921 in the version I have) 

ie make it

      #if ENABLED(PRINTER_EVENT_LEDS)
        // Gradually change LED strip from blue to violet as bed heats up
        if (!wants_to_cool) {
          const uint8_t red = map(constrain(temp, start_temp, target_temp), start_temp, target_temp, 0, 255);
          if (red != old_red) set_led_color((old_red = red), 0, 255);
        }
      #endif

**Comment by markdoll01** [comment]
Thank you ellensp,

This looks promising - will test in about three hours and report back.

Thank you.

**Comment by markdoll01** [comment]
Thank  you ellensp,

After removing the "}", everything compiled correctly and I am able to control my led strip with the M150 command.     

Thanks.
