### ISSUE TITLE
CoreXY Y axis Homing issue

### ISSUE THREAD

**Issue by markdoll01** [MarlinFirmware/Marlin#6598]
Hi,

Got a D-Bot running perfect on RC6 but with 1.1.x I am getting a Y axis homing issue.  Printer Homes perfect but thinks it is at 0.00,  0.00,  0.00 position where as my Y is using Max Endstop and the position should be 0.00,  200.00,  0.00 after homing.

#define COREXY
//#define COREXZ
//#define COREYZ
//#define COREYX
//#define COREZX
//#define COREZY

My Endstop Settings:
// @section homing

// Specify here all the endstop connectors that are connected to any endstop or probe.
// Almost all printers will be using one per axis. Probes will use one or more of the
// extra connectors. Leave undefined any used for non-endstop and non-probe purposes.
#define USE_XMIN_PLUG
//#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
//#define USE_XMAX_PLUG
#define USE_YMAX_PLUG
//#define USE_ZMAX_PLUG

Homing Result: M114
Recv: X:0.00 Y:0.00 Z:0.00

Whereas RC6 Homing Result:M114
Recv: X:0.00 Y:200.00 Z:0.00

**Comment by ozligia** [comment]
Please post config file here, as i am running corexy with y max homing with no issues

**Comment by markdoll01** [comment]
Hi,

Thanks for the help,  please find attached the config files.  I basically went line by line and duplicated the config I have running from rc6 to the new version - might have missed something or might have done something wrong.
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/981017/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/981016/Configuration_adv.h.txt)

**Comment by ozligia** [comment]
Hm. It seems that config is fine. What new version do you have? 1.1.x. ? And what host software do you use? Also, it is good idea, to reflash your eeprom. But don't forget to remember your settings.

**Comment by markdoll01** [comment]
I downloaded the latest 1.1.0 "stable" build that was release 22 hours ago.
I am using Octoprint - also latest stable release.
I did do a M502 after flashing to load factory eeprom settings but did not help.

Anything else I could try?

**Comment by markdoll01** [comment]
Sorry Ozligia,

The previous Configuration.h and _adv.h files I uploaded were from RC6 and not the latest version where I have the homing issue - sorry for that.

Here are the ones from the latest version 1.1.0 build 22 hours ago:
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/981095/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/981096/Configuration_adv.h.txt)

**Comment by Bob-the-Kuhn** [comment]
Do M502, M500 then M501 to get the new settings into the EEPROM and to activate them.

**Comment by markdoll01** [comment]
Thank you everybody for helping,  I was able to find my problem.  To solve it I had to specify manually my Y home position:
#define MANUAL_Y_HOME_POS 200

Just strange that I did not need it when I was running RC6.  
Thank you.

**Comment by ozligia** [comment]
@markdoll01, 
```
//#define MANUAL_X_HOME_POS 0
//#define MANUAL_Y_HOME_POS 0
//#define MANUAL_Z_HOME_POS 0
```
are commented out in default config. So, yep, in your case firmware worked as expected. You may leave it as is, providing correct values, or comment these lines out.

**Comment by markdoll01** [comment]
Thank you very much ozligia for the help.  That is correct, they should be commented out and because I enabled them it did what it should an is not a bug.

Thanks again.
