### ISSUE TITLE
RC8 V1.1.X  Thermo couple incorrect value 

### ISSUE THREAD

**Issue by moth4017** [MarlinFirmware/Marlin#6604]
Hi all just updated  to the new version  of RC81.1.x I use the #define TEMP_SENSOR_0 -1  in the previous version correct reading  26 C , in the latest version reading at 26 C  displayed  on printer at 499 C

**Comment by Tannoo** [comment]
`TEMP_SENSOR_0 -1`  <--- `-1` disables it.
Should be:
`TEMP_SENSOR_0 1`

**Comment by moth4017** [comment]
No I think you will find    -1 : thermocouple with AD595

**Comment by moth4017** [comment]
My Bas... I also had to remember to change 
fine TEMP_0_PIN         13   // Analog Input

to

fine TEMP_0_PIN         3   // Analog Input
