### ISSUE TITLE
PID Autotuning causes LCD irresponsiveness and board reset

### ISSUE THREAD

**Issue by golyalpha** [MarlinFirmware/Marlin#6605]
Whenever I try to run PID autotune on my extruder with the default cycles and temperature 200 C, or 150 C, I get PID Autotuning and then T: in serial, display stops responding, I see the extruder heating LED turn on and then turn off as the board reboots. I have tried to run PID autotune from the LCD Temperature menu, and it causes the same behaviour.

Any ideas onto why is this happening?

**Comment by knobik** [comment]
did you try the RCBugFix branch? main release 1.1.0 has a critical error. I think we should do a bugfix release 1.1.1.

**Comment by golyalpha** [comment]
I just flashed in RC and it's working so far.

**Comment by knobik** [comment]
Just keep in mind, that RC branch is far behind the main release and RCBugFix

**Comment by golyalpha** [comment]
Alright. Gonna try RCBugFix then. Can I reuse my config from RC there or not?

**Comment by bgort** [comment]
bugfix-1.1.x is the latest and is what you should try, generally.  The issue I believe you're describing has been fixed.

**Comment by golyalpha** [comment]
Alright, will flash that as soon as I get back home to see how it works.
