### ISSUE TITLE
UBL selecting points and adjusting them from the LCD.

### ISSUE THREAD

**Issue by knobik** [MarlinFirmware/Marlin#6608]
Maybe im missing something but it would be nice to be able to select points and edit them from the LCD screen. If not, is there a way to do it from a host pc?

**Comment by Roxy-3D** [comment]
@Tannoo  has done a huge amount of work on this:  https://github.com/MarlinFirmware/Marlin/pull/6566

It isn't merged yet just because of all the commotion surrounding the release.  If you add this to BugFix-v1.1.0  and say it works there...  I might just press the Merge button on it...

**Comment by Tannoo** [comment]
In the mean time, there is this:

UBL getting started guide #6510

**Comment by knobik** [comment]
Thats a huge step for me, thank you :) now all i need its the z-hop fix for #6589
