### ISSUE TITLE
G26 with the other leveling methods

### ISSUE THREAD

**Issue by martindb** [MarlinFirmware/Marlin#6612]
Can G26 test be used with abl and mbl methods?

**Comment by Tannoo** [comment]
Nope.

**Comment by martindb** [comment]
It should be a useful improvement?

**Comment by Roxy-3D** [comment]
The G26_mesh_validation_tool.cpp file did not have UBL_ put in front of it because it is anticipated that other mesh leveling schemes could use it.   But nobody has spent the time to make that happen yet.   So right now...  Only UBL is using it.

**Comment by martindb** [comment]
Thanks Roxy.
