### ISSUE TITLE
Ramps 1.4 reset button

### ISSUE THREAD

**Issue by Radiu** [MarlinFirmware/Marlin#6617]
hi
i have a ramps 1.4 shield, i have tried use the reset button on the side of ramps1.4 and nothing happens, is this button disable by something or is it a problem with my shield?

thanks

**Comment by Tannoo** [comment]
Yes, like an issue with it not being connected. Look for bad solder connections and/or broken trace.

**Comment by Roxy-3D** [comment]
Something is defective.  Because that reset switch is hard wired to the processor board's reset.  There isn't supposed to be a way to turn it off or disable it.

**Comment by Radiu** [comment]
@Roxy-3D @Tannoo   sounds like you correct i have some bad joint or something i was messing with button and if i press very hard sometimes works and sometimes doesn't so must be a bad solder join or a defective button..

thanks alot for the support!!

**Comment by knobik** [comment]
@Radiu you should close this issue.

**Comment by vMeph** [comment]
@knobik I dont have close issue button under comments, where to do it?

**Comment by knobik** [comment]
@Radiu only the issue owner and repository owner can close. The button is next to the green "comment" button.
