### ISSUE TITLE
G29 P4 not moving the z axes

### ISSUE THREAD

**Issue by knobik** [MarlinFirmware/Marlin#6620]
When mesh is build and i want to fine tune it, i do a G29 P4 command and "Mesh editor: -0.240" is shown on LCD, z-axis moves up couple of milimeters before i touch the knob but after i move the knob, the z-axis does not move in any direction. Its not a foulty knob. 

lastest 1.1.x-bugfix branch

**Comment by Tannoo** [comment]
This was taken from this by @Bob-the-Kuhn: [UBL.startup.guide.zip](https://github.com/MarlinFirmware/Marlin/files/981475/UBL.startup.guide.zip)


>To edit a single point move the nozzle close to the point that needs adjustment. Issue a G29 P4 O . The head will move to nearest point. Use the encoder wheel to change the value.  The nozzle will NOT change height.

**Comment by knobik** [comment]
It would be nice to use move it cuz i could use a shim to perfectly level it.

**Comment by Roxy-3D** [comment]
I'll look at putting the move up or down back in.

**Comment by Bob-the-Kuhn** [comment]
I think we're better off as is.

The shim method isn't as precise/repeatable as needed for this portion of UBL mesh creation. 

When I did my mesh I was doing 0.1, 0.05 & 0.02 mm adjustments based on the G26 results.  You're just not going to get the 0.05 & 0.02 resolution with a shim.
