### ISSUE TITLE
Issue when connecting to any host software (Marlin v1.1)

### ISSUE THREAD

**Issue by classbproject** [MarlinFirmware/Marlin#6626]
I installed v1.1 yesterday and that went without a hitch, however, when I try and connect some host software (I've tried Repetier Host and S3D), the whole screen looks like what is shown in the [video](https://youtu.be/guHSj7E7wbI). Also in my case, on one instance, while the connection went bonkers, the heatbed started heating by itself, though I do not have a screen of that. How do I resolve this?

**Comment by bgort** [comment]
Try the bugfix-1.1.x branch.  This looks like the issue fixed in #6584.
