### ISSUE TITLE
M105 on LCD, and message stating Paused for user

### ISSUE THREAD

**Issue by pmbroth** [MarlinFirmware/Marlin#6653]
Hello Uploaded the latest release 11x as of 5/8/17.  When doing a UBL mesh build, I get at the message on my lcd M105.   

On my comm screen on my pc I get "Paused for User".   Until I press the toggle button on the lcd, it keeps repeating  "Pause for User".  After I press the button  I can then save the mesh.  I did not get this with the firmware 3 days ago, and did not know if you added this function.  As a side note I was using Prointerface to do the communication.

**Comment by pmbroth** [comment]
[Marlin 5817.zip](https://github.com/MarlinFirmware/Marlin/files/985242/Marlin.5817.zip)

**Comment by pmbroth** [comment]
I have attached my Marlin files just in case you wanted to see them, if the error is not normal.
Thank you

Brian

**Comment by Tannoo** [comment]
What was you 'mesh build' command?

**Comment by pmbroth** [comment]
Hello

G29 P1

**Comment by pmbroth** [comment]
I noticed the only time I'm getting this issue, is if I use PROINTERFACE as the software for doing the G29 P1, S3D does not have this issue.
