### ISSUE TITLE
After flashing 1.1.0-1 and connecting i just get M105

### ISSUE THREAD

**Issue by ALpha724** [MarlinFirmware/Marlin#6662]
I am using S3D and after flashing to Marlin 1.1.0-0. S3D seems to be sending M105 after the connection is established. After about 10-20 M105s the stream just stops....I am trying to auto level working using BLTouch and I just cant get the printer to allow S3D to operate it.

Anyone have any ideas?

**Comment by pmbroth** [comment]
I get the same thing see my issue #6653

(edited by @bgort to link to the previous issue)

**Comment by pmbroth** [comment]
I'm not using bltouch.  I'm using fixed probe sensor.
