### ISSUE TITLE
Another bug with incompatility

### ISSUE THREAD

**Issue by batata004** [MarlinFirmware/Marlin#6670]
Hi,

Using the latest marlin firmware (previous to the new one we have now) I could use this command to autotune PID of my heated bed with no problem:

M303 E-1 S70

Now when I try to send that command in the Serial it says "READ: PID Autotune failed! Bad extruder number". What changed from the previous to the new firmware that is making this command incompatible? I didnt change anything in my printer from there to now.

These are my config files.

[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/990235/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/990234/Configuration.txt)

**Comment by bgort** [comment]
You need to #define PIDTEMPBED.

From your Configuration.h:
`//#define PIDTEMPBED`

Should be
`#define PIDTEMPBED`

**Comment by batata004** [comment]
Worked! For some reason I never changed this (even in older firmware versions) but now I think I have to uncoment this! :) Thanks man. Sorry for bothering with this small issue.

**Comment by batata004** [comment]
Worked! For some reason I never changed this (even in older firmware versions) but now I think I have to uncoment this! :) Thanks man. Sorry for bothering with this small issue.

**Comment by batata004** [comment]
Worked! For some reason I never changed this (even in older firmware versions) but now I think I have to uncoment this! :) Thanks man. Sorry for bothering with this small issue.
