### ISSUE TITLE
Extrusion after homing sends extruder to calibrated zero level

### ISSUE THREAD

**Issue by kyberkiller** [MarlinFirmware/Marlin#6679]
I tried to feed some wire before starting to print, so I found this taking place.

The extrusion starts if I re-send the command (G1 E100 F500), or if I move the head prior to extrusion.

The log is attached
[LogFile trying to extrude.txt](https://github.com/MarlinFirmware/Marlin/files/991147/LogFile.trying.to.extrude.txt)
. 1) 2)... numbers are added manually, also the command, the log is directly copied from Arduino IDE serial monitor.

The behaviour is exactly same when G-code is sent or the extrusion button is pressed in Repetier-Host V2.0.0

**Comment by thinkyhead** [comment]
Presuming solved.
