### ISSUE TITLE
G29 P2 B Issue

### ISSUE THREAD

**Issue by bgort** [MarlinFirmware/Marlin#6692]
Latest bugfix is raising by 2mm (my SIZE_OF_LITTLE_RAISE) between measurement points instead of the size specified by the H code, which makes manually filling in the mesh take a lot longer.

Relevent code section:
```
      if (HYPOT(dx, dy) < BIG_RAISE_NOT_NEEDED)
        do_blocking_move_to_z(current_position[Z_AXIS] + SIZE_OF_LITTLE_RAISE);
      else
        do_blocking_move_to_z(z_clearance);
```

Is there ever a case where we actually need a raise other than what's specified by the H code while manually filling in mesh points?

I'm not seeing a need for anything other than the H value if one is specified, but it's possible I'm missing something.

**Comment by bgort** [comment]
Ah, I see.  We're updating `height` (which becomes z_clearance) in `measure_business_card_thickness(height)` but we're updating it to Z_CLEARANCE_BETWEEN_PROBES above 'zero' / bed, rather than the thickness of the business card + some small margin.

```
    const float z2 = use_encoder_wheel_to_measure_point();
    do_blocking_move_to_z(current_position[Z_AXIS] + Z_CLEARANCE_BETWEEN_PROBES);

    if (g29_verbose_level > 1) {
      SERIAL_PROTOCOLPGM("Business Card is: ");
      SERIAL_PROTOCOL_F(abs(z1 - z2), 6);
      SERIAL_PROTOCOLLNPGM("mm thick.");
    }
    in_height = current_position[Z_AXIS]; // do manual probing at lower height
```

Perhaps should be?:

```
    const float z2 = use_encoder_wheel_to_measure_point();
    do_blocking_move_to_z(current_position[Z_AXIS] + Z_CLEARANCE_BETWEEN_PROBES);

    if (g29_verbose_level > 1) {
      SERIAL_PROTOCOLPGM("Business Card is: ");
      SERIAL_PROTOCOL_F(abs(z1 - z2), 6);
      SERIAL_PROTOCOLLNPGM("mm thick.");
    }
    in_height = abs(z1-z2)+0.3; // do manual probing at height of business card + 300um margin
```

This okay with everyone?  

Or is it better to not change the height if H is specified?  Doing it that way makes things more 'you get what you asked for', I think.

**Comment by Roxy-3D** [comment]
The BIG_RAISE and LITTLE_RAISE was paranoid thinking.   I was worried that if the nozzle was going very far to get to the next point, there might be unknown bed flaws in the way.   So the BIG_RAISE would be safer.  But UBL was developed on a machine with a very very slow Z-Axis.  So, it was nicer to just do a LITTLE_RAISE when possible.     

I'm not sure we need to keep both around any more.   But we probably do need to raise some 'safe' amount as the nozzle runs around the bed looking for the next location it is going to deal with.   I don't think it matters how that happens...  But the nozzle probably should be a 'safe' distance above the bed during big travel moves.

**Comment by bgort** [comment]
Makes sense.  Why not raise to z_clearance between_probes as we move, then lower to the H specified, or the business card height + some small margin if H isn't specified?

**Comment by Roxy-3D** [comment]
I'm good with that!    Also remember...  When UBL development started...   Z_CLEARANCE_BETWEEN_PROBES did not exist.   But in hindsight...  That is probably the 'right' answer.

**Comment by bgort** [comment]
Ah, that makes sense!  

Okay, I'll make these changes now and do a PR.

**Comment by Bob-the-Kuhn** [comment]
I have about a 1.5mm tilt on my bed.  I'll need a higher raise.

If this is the first time probing a bed you won't know what a "safe" raise is.

It's a tradeoff between worn out encoders & sore thumbs for most people vs. hitting the bed for a few.

**Comment by bgort** [comment]
Hmm.  If we just let H override whatever we 'learn' with B (plus a margin), would that work for you?

**Comment by bgort** [comment]
Or shall we just leave the B code the way it is, and allow H to override it for those of us who want a small raise?

**Comment by Bob-the-Kuhn** [comment]
Lots of reasonable ways to implement it.

I'll be happy with whatever you & Roxy are happy with.

**Comment by bgort** [comment]
Okay, so I'm going to leave B the way it is, but just allow H to override whatever B comes up with (the bed/zero + Z_CLEARANCE_BETWEEN_PROBES, currently).  

That keeps things pretty 'safe', generally, but allows users who want to specify a height to do so (at their own risk, of course) ...
