### ISSUE TITLE
SD Uploads fail when using SPI Thermocouple

### ISSUE THREAD

**Issue by Grogyan** [MarlinFirmware/Marlin#6714]
RAMPS 1.4
RRD Full Graphic Display
MAX31855 Thermocouple
Marlin 1.1.x
OctoPrint 1.32
Brand Spanking new, quality SD card

Uploading a gcode file to the SD card via the host causes the printer to shutdown reading back
```
Recv: Error:MINTEMP triggered, system stopped! Heater_ID: 0
Changing monitoring state from 'Sending file to SD' to 'Error: MINTEMP triggered, system stopped! Heater_ID: 0\x0a'
Recv: Error:Printer halted. kill() called!
```

SDSUPPORT is enabled in the firmware

**Comment by Tannoo** [comment]
Try another sd card.

**Comment by Grogyan** [comment]
This is the 3rd SD card.

**Comment by Tannoo** [comment]
Bad reader?

**Comment by Tannoo** [comment]
Try another SD card reader with those cards.

**Comment by Tannoo** [comment]
Try writing locally at the pc (from a reader on the pc), then read it from the lcd (after inserting into the lcd's reader).

Take Octoprint out of the loop.

**Comment by Tannoo** [comment]
If that works, then try with the IDE serial console.

**Comment by Grogyan** [comment]
OctoPrint is not the issue
Have also tried with Repetier host with the same result
SD card works fine on PC.

Just not able to remotely upload to the SD card

**Comment by Tannoo** [comment]
Yeah, I'm trying to help.
I tried it this afternoon myself and having issues.

**Comment by Tannoo** [comment]
I tried uploading to SD from Repetier and it says it uploaded, but the file size is 0. It will delete that 0 byte file.

So, I tried from Octopi...well, it says it's uploading...forever.

**Comment by Tannoo** [comment]
I'll have to look at it more in the am.

**Comment by Grogyan** [comment]
Have re flashed the firmware from 1.1.x BugFix as of an hour ago
Same result, still unable to upload gcode files to SD through, OctoPrint, Repetier Host, Pronterface

**Comment by Tannoo** [comment]
I have been trying to narrow this down to find when and where it got broken.

I have tried all backups I have (even before UBL)... all do the same. Cannot upload any files from any host.
Repetier will create a 0 byte file or give an error about not reading it.. Octopi will not create anything, but it does give errors about not getting the next line number.
All hosts read the card and can print any file selected.

I have downgraded the IDE from 1.8.2 to 1.6.7 and re-flashed... same.

I have reduced the comm speed from 250000 to 115200 and to 57600... same.

I then went back to IDE 1.8.2, put comm speed back to 250000 and reflashed. Still the same.

This time I tried to create a file manually... I sent:
`M28 testing.gco`
then
`G28`
then
`G0 X100 Y100`
then
`G28`
then
`M29`

All looked good.
Then I sent:
`M23 testing.gco`
then
`M24 testing.gco`

and the printer did exactly what that file contained.

So, why can any host not send a file anymore? I don't know.

We need to enlist some smarter people on this.

**Comment by Bob-the-Kuhn** [comment]
I gave up trying to upload files directly to the SD card via Repetier Host.  The new version doesn't seem any better

When I need to upload a file to the SD card I actually load it into Repetier first (via the LOAD button) and then go to the SD card section and select Upload Current G-Code.  After entering the Uploaded Filename then just click in the File box.  Now if you click OK it'll upload.

![image](https://cloud.githubusercontent.com/assets/20692583/26038539/5471bc04-38d0-11e7-8d6c-c5abcf5d6e10.png)

**Comment by Bob-the-Kuhn** [comment]
File extension MUST be 'g' - nothing else works.

**Comment by Tannoo** [comment]
I will try that later.. I was using `.gco`.

**Comment by Grogyan** [comment]
I can't verify as I am at work.
A quick search in the code shows in CardReader.cpp
```
void CardReader::checkautostart(bool force) {
if (!force && (!autostart_stilltocheck || ELAPSED(millis(),
next_autostart_ms)))
return;
autostart_stilltocheck = false;
if (!cardOK) {
initsd();
if (!cardOK) return; // fail
}
char autoname[10];
sprintf_P(autoname, PSTR("auto%i.g"), autostart_index);
for (int8_t i = 0; i < (int8_t)strlen(autoname); i++) autoname[i] = tolower
(autoname[i]);
```

Which shows the *.g as the only upload option.  which is kinda a problem,
as some programs export to *.gco and others *.gcode (Cura)

**Comment by Bob-the-Kuhn** [comment]
I lied to you.  Looks like about any file extension that starts with a 'g' will do when writing a file to the SD.

The code that was cited is actually for the autostart function.  That's disabled by default.  The only way to enable it is to edit `Marlin_main.cpp`.

**Comment by Tannoo** [comment]
Repetier is creating the filename and is able to delete it. The file will only be larger than 0 bytes if I select to include the start and end codes.

When I do that, it will print that file which now only contains `M84`... And the lcd says print complete.

I am baffled as to why it will not upload a sliced file... Even a freshly sliced file and uploaded as you suggested results in a 0 byte file.

**Comment by Tannoo** [comment]
Even a very small single layer designed and sliced, will not upload.

**Comment by Tannoo** [comment]
Do I need to reset eeprom? I now think I remember having this trouble once before and was told to re-int eeprom.

I'll try that in the am.

**Comment by Tannoo** [comment]
The other option I'm going to try is all caps for the Sdcard filename.

**Comment by Bob-the-Kuhn** [comment]
The process I use with Repetier Host is:
1. click on the Load button on the main screen
2. select the file & click Open
![image](https://cloud.githubusercontent.com/assets/20692583/26040501/76ffded4-38eb-11e7-854e-cac3b10978e7.png)
3. click on G-Code Editor to make sure something got there
4. click on the SD Card button
5. click on the upload button
![image](https://cloud.githubusercontent.com/assets/20692583/26040545/f2475a90-38eb-11e7-8bef-0eb9d6b5c668.png)
6. clear the two "Include .. " flags & select Upload Current G-Code
7. type a DOS 8:3 file name in the "Uploaded Filename:" box - extension must start with a 'g' - doesn't matter if the letters are upper or lower case (lower case is automatically converted to uppercase)
8. do NOT enter anything into the "File:" box.  On the older Repetier Host you had to click in the box but not enter anything).
9 click OK
![image](https://cloud.githubusercontent.com/assets/20692583/26040725/5487f68c-38ed-11e7-8939-2fd7635e0b92.png)

**Comment by Grogyan** [comment]
What about *. GCO and *. GCODE extensions?

**Comment by Bob-the-Kuhn** [comment]
Those are acceptable when using the Load button to move a g-code file into the Repetier Host's buffer.   You may have to click on the extension box and select ALL FILES to see your file.
![image](https://cloud.githubusercontent.com/assets/20692583/26041518/19a9fc44-38f3-11e7-97ce-5c1b769900e5.png)


The .GCO is acceptable when uploading from the buffer to the SD card.  The .GCODE has too many letters in it to upload from the buffer to the SD card.

**Comment by Grogyan** [comment]
Okay, I have tried both *.gco and *.g extensions
OctoPrint, Repetier Host and Printerface all keep doing the same thing
```
Send: M28 /pi3_bo~1.gco

Recv: echo:Now doing file: /pi3_bo~1.gco

Recv: Writing to file: /pi3_bo~1.gco

Changing monitoring state from 'Operational' to 'Sending file to SD'

Recv: ok

Send: N3 M190 S60.000000*115

Recv: Error:MINTEMP triggered, system stopped! Heater_ID: 0

Changing monitoring state from 'Sending file to SD' to 'Error: MINTEMP triggered, system stopped! Heater_ID: 0\x0a'

Recv: Error:Printer halted. kill() called!
```
I've added the Carriage Returns for readabilty

**Comment by Tannoo** [comment]
I haven't gotten any mintemp errors.

Is your mintemp still default of 5?

**Comment by Grogyan** [comment]
-3 
MAX31855 Thermocouple

**Comment by Tannoo** [comment]
I have confirmed that uploading from Repitier is fine if you upload freshly sliced gcode and only in 8.3 file format. It has to "print" it to the SD card. The file uploading doesn't work. I believe that is a host issue.

**Comment by Tannoo** [comment]
It took several tries, but I got Octopi to send it also.

**Comment by Tannoo** [comment]
>-3
MAX31855 Thermocouple

Nevermind, I found that the MAX12855 mintemp is set to -150.

**Comment by Tannoo** [comment]
I don't have issues with MINTEMP or MAXTEMP when getting these files sent to SD.
I cannot set the thermistor to -3 and be able to do anything. Doing so throws a MAXTEMP error right at startup that I cannot get around.

**Comment by Grogyan** [comment]
The SD card and the thermocouple operate on the same SPI bus, where the firmware asserts the CS pin of which device it is talking to. 

So, what it looks like is that the SD CS pin is being asserted for too long when the thermocouple is being read. 
This would definitely give the MINTEMP error. 
But I didn't have this issue way back in RC6
