### ISSUE TITLE
Endstop Trigger issue (Marlin-1.1.x)

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#6720]
Hello,
Thank you for the efforts on making this decent firmware.

I dusted off my Printrbot Jr, having Printrboard Rev.D I was able to compile and flash the firmware successfully with Arduino-1.8.2 ide, teensyduino 1.36, (flashing with dfu-programmer), and adding #include"Arduino.h" and "macros.h" to serial.h for "customserial" issue.
My Configuration.h diff:

```
+ #define MOTHERBOARD BOARD_PRINTRBOARD
- #define MOTHERBOARD BOARD_RAMPS_14_EFB
+ #define DEFAULT_AXIS_STEPS_PER_UNIT   { 63.36,63.36,2272.72,590 }
- #define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 4000, 500 }
+ #define DEFAULT_MAX_FEEDRATE          { 60, 60, 2, 14 }
- #define DEFAULT_MAX_FEEDRATE          { 300, 300, 5, 25 }
+ #define DEFAULT_MAX_ACCELERATION      { 2000,2000,30,10000 }
- #define DEFAULT_MAX_ACCELERATION      { 3000, 3000, 100, 10000 }
+ #define INVERT_X_DIR true
- #define INVERT_X_DIR false
+ #define EEPROM_SETTINGS
- //#define EEPROM_SETTINGS
+ #define SDSUPPORT
- //#define SDSUPPORT"
```
I have also tried reverting to stock firmware, and compiling a commit of first March(while i was trying to solve the serial issue), non have introduced this issue.
```
19:19:14.883 : N20 M119*24
19:19:14.906 : Reporting endstop status
19:19:14.906 : x_min: open
19:19:14.907 : y_min: TRIGGERED
19:19:14.907 : z_min: open
```
Tried inverting with M119 Y1 1 (or 0), that did not change anything.
Edit: I should add, triggering the endstop switch doesnt alter the value of Y, I can't home because of this, rest axis are working fine. 

Thank you

**Comment by Bob-the-Kuhn** [comment]
M119 only reports the state of the endstops.  You can't change anything with it.

You'll need to go into your **Configuration.h** file and change **Y_MIN_ENDSTOP_INVERTING** .

**Comment by ghost** [comment]
Hey thank you for the response!
But the issue is, even with the endstop is physically triggered, it is stuck at "TRIGGERED", so inverting is useless. But good to know that, thanks for the info.

**Comment by ghost** [comment]
Compiling and flashing Marlin 1.0.x:
```
21:01:17.324 : Reporting endstop status
21:01:17.324 : x_min: TRIGGERED
21:01:17.324 : y_min: TRIGGERED
21:01:17.324 : z_min: TRIGGERED
21:01:29.454 : N26 M119*30
21:01:29.609 : Reporting endstop status
21:01:29.609 : x_min: TRIGGERED
21:01:29.609 : y_min: open
21:01:29.610 : z_min: TRIGGERED
```

Edit: All endstops are open, yet the firmware reports all as triggered, which is basically inverse, though all axis work fine and properly after inverting. I'm currently comping and testing the oldest 1.1.x commits.

**Comment by Bob-the-Kuhn** [comment]
On 1.0.2 all endstops toggle but on 1.1,x the Y_MIN is stuck.

Do you have the SD card enabled?

In 1.02 the Y_MIN endstop was always pin 8.  In 1.1.0 it moves to pin 37 if the SD card is enabled.
```
#if ENABLED(SDSUPPORT)
  #define Y_STOP_PIN       37 // Move Ystop to Estop socket
#else
  #define Y_STOP_PIN        8 // Ystop in Ystop socket
```

**Comment by ghost** [comment]
I just disabled SDSUPPORT and it worked, and **then** I see your comment, arr.
Is there a workaround with sd enabled? Should I just change pin number?
Thanks a bunch.

**Comment by Bob-the-Kuhn** [comment]
It sounds like the change is to move the Y_MIN cable from the Y_STOP connector to the E_STOP connector.

**Comment by ghost** [comment]
It works, thank you. Closing issue.

**Comment by Bob-the-Kuhn** [comment]
FANTASTIC!!
