### ISSUE TITLE
"PIDTEMPBED" makes extruder run forever

### ISSUE THREAD

**Issue by Iamturbo1978** [MarlinFirmware/Marlin#6725]
Hello all,

When I remove the comment for "#define PIDTEMPBED", run auto PID, then try to print something, my extruder will run without stopping. I reset my machine, then tried to extrude 0.1mm of filament from the LCD, the extruder would just run without stopping. Only resetting would stop the extruder. If I comment out "#define PIDTEMPBED", my machine works like it should. The extruder only moves a little when I ask it to extrude 0.1mm of filament. I am using firmware "Marlin-1.1.x"

Thanks

**Comment by Tannoo** [comment]
Try `bugfix-1.1.x`.

**Comment by Iamturbo1978** [comment]
That fixed it. Thank you
