### ISSUE TITLE
Switches question

### ISSUE THREAD

**Issue by Radiu** [MarlinFirmware/Marlin#6729]
hi i have some questions about switches
i was wondering where you install your switches for point 0 of machine X switch on left side, Y switch on the back part, Z switch on bottom of machine?
what would be best switches, mechanical or optical?
do you use 2 switches for each axis?

**Comment by Roxy-3D** [comment]
Most people use 1 switch and usually they put it as a X, Y or Z Min switch.    I prefer micro-switches but a lot of people prefer optical.   This is the RepRap world...  You can do what ever you think makes sense.

**Comment by Bob-the-Kuhn** [comment]
I personally prefer the A1125 Hall effect sensor.  Has same pinout as most endstop connectors, doesn't care about dirt/dust & lasts forever.

**Comment by Tannoo** [comment]
I did use 3 microswitches. X, Y and Z.
I have since stopped using the Z in favor of a proximity probe.

**Comment by Tannoo** [comment]
My printer is a Prusa i3 style.

My X limit is installed on the X carraige rail on the drive end.
My Y limit is attached to the Y rail opposite the drive end.
My Z limit was (still is) attached to the left Z stepper mount.

**Comment by teemuatlut** [comment]
For X and Y it's mostly up to your own reference.
Personally I use Sensorless Homing (cleaner with no extra wires) and hall effect sensors for the second printer. Optical would be my next choice, but I don't think I'll ever go back to microswitches. In the end they all work the same.
For Z axis many have upgraded to either inductive sensors or a BLTouch sensor.
Generally there's no need to use two sensors for a single axis.

**Comment by mtowara** [comment]
@teemuatlut can you point me to references for Sensorless Homing?
Is that a feature of your stepperdrivers?

**Comment by teemuatlut** [comment]
Yes, TMC2130 or Trinamic TRAMS required.
https://www.trinamic.com/technology/adv-technologies/stallguard/
