### ISSUE TITLE
documentation 

### ISSUE THREAD

**Issue by lrpirlet** [MarlinFirmware/Marlin#6743]
The **whole gcode list** visible under http://marlinfw.org/meta/gcode/ shows an unrelated example for M280 Servo Position...

Note that http://marlinfw.org/docs/gcode/M280.html is fine

BTW... Thanks for that huge documentation work, I do appreciate.

**Comment by thinkyhead** [comment]
Thanks for the note! In fact, I see that every code that doesn't have an example displays the example from the last code that did have one. I will patch it shortly!
