### ISSUE TITLE
Stray / Unneeded branches

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#6744]
It is my belief that we have 3 unneeded branches....    Specifically:
- pr/6566
- pr/6637
- revert-6686-1.1.x

If nobody knows a reason to keep these around...   We probably should delete them.

**Comment by thinkyhead** [comment]
Done.

We can keep `RCBugFix` around until all the older PRs have been migrated over to `bugfix-1.1.x`.

The easiest way I've found to keep the `RCBugFix` PRs up to date with `bugfix-1.1.x` is to simply "`git reset`" the `RCBugFix` branch so it points to the HEAD of `bugfix-1.1.x`. This allows us to continue to working with the existing `RCBugFix` PRs and to keep having their authors patch them so they apply to the current code.

Following this technique, we can continue to work on those PRs with their authors, and whenever one in good enough shape, it can then be readily merged with `bugfix-1.1.x`.
