### ISSUE TITLE
[FR] Invert bed pin logic

### ISSUE THREAD

**Issue by fabio-pulcini** [MarlinFirmware/Marlin#6747]
hi!
is possible now (or will be possible) invert logic of bed pin? i use a relay for my bed and when arduino start my bed pin is activate and it is a problem..
thanks!

**Comment by Bob-the-Kuhn** [comment]
What relay are you using?

How did you connect it to the controller?

**Comment by fabio-pulcini** [comment]
i use a relay like this [https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIFP7Vj-8W0P1D4bwdDknZ0RrDbCqDYXO1DsBdRYxmzbZH2oPd](url).
i controller my AC bed by digit pin 6 (PWM).
my problem is when arduino start pin 6 is on..

**Comment by Tannoo** [comment]
Pics aren't good enough (especially when they aren't there), can you provide a link to the one you actually bought?

**Comment by Bob-the-Kuhn** [comment]
Please ZIP your config files and drop them on your next post.

If you're using a RAMPs based controller then the heated bed could be attached to a different pin.

Actually, you can verify it yourself.  In Configuration_adv.h enable PINS_DEBUGGING and then issue a M43 I command.  That should list all your pins, the signals attached to them and what state they are in.

**Comment by fabio-pulcini** [comment]
this is my configuration.
after i will try M43 command!
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1004772/Configuration.zip)

**Comment by Bob-the-Kuhn** [comment]
It looks like you're running Marlin 1.0.2.  Is that correct?

**Comment by fabio-pulcini** [comment]
it is marlin 1.0.1

**Comment by Bob-the-Kuhn** [comment]
It took a LONG time but I finally ported M43 over to 1.0.2.2.

It says that pin 6 is tied to HEATER_BED_PIN, that it's an output and it's set to low unless you turn the heater on.

It's finally dawning on me.  You have one end of the relay tied to +5V and the other tied to pin 6.  When pin 6 is low the relay will be energized and the heater will be on.

Move the relay connection from +5V to ground.  That should fix your problem.

**Comment by fabio-pulcini** [comment]
are you sure that with this specific relay i can invert 5v to ground? it has got a small circuit..
i want to put my relay to NO configuration and when my arduino start my pin must to be slow

**Comment by Bob-the-Kuhn** [comment]
If you give me the part number of the relay or the link to where you bought it I expect that I can answer that question.

Chances are good that it'll work.  The Mega2560 pins are spec'd to sink & source the same amount of current.

The alternative is to put a FET in between the relay and pin 6.

**Comment by fabio-pulcini** [comment]
my relay is like this:
[https://ae01.alicdn.com/kf/HTB118h4OpXXXXafXXXXq6xXFXXXX/-font-b-3D-b-font-font-b-printer-b-font-accessories-high-power-hot-bed.jpg](url)

**Comment by Bob-the-Kuhn** [comment]
Here's the best I could find on that module.
https://drepart.en.alibaba.com/product/60451429598-802072120/Low_Level_Triger_with_Optocoupler_Relay_Module_12V_for_Arduino.html?spm=a2700.8304367.0.0.TiY4mj

It says it's optocoupled so you can drive it directly from any Mega2560 pin.  It also allows you to set the active level as low or high.

I suggest you start looking for a solid state relay.  Mechanical ones like this will eventually wear out.

**Comment by fabio-pulcini** [comment]
with my relay you can choose if you want activate it when pin is low or high (now i know it thanks bob!).
but it will be good if you can do it by software!
thanks!

**Comment by Bob-the-Kuhn** [comment]
There isn't a configuration option for this.  Any software solution would require custom code.

The jumper on the module is the only hardware method available to invert the signal.  My earlier comments don't apply to this module.

**Comment by thinkyhead** [comment]
IOW — it would need to invert the bed PWM, which could also be done by inverting the duty cycle.

However, the result would be that the Arduino would have to keep pumping 5V into the relay to keep it from heating the bed, and it would be better if it had the opposite fail condition. That is, if it got disconnected, it shouldn't start to heat the bed.

For that reason, I strongly disfavor this feature request and advocate for pebble bed reactors.

**Comment by boelle** [comment]
@thinkyhead i agree

@fabio-pulcini have you found a "fix" ?

**Comment by ellensp** [comment]
Non supported version of marlin.
