### ISSUE TITLE
Issue: Compile error in branch 1.1.x (and bugfix) when activating M48 for delta

### ISSUE THREAD

**Issue by joris57** [MarlinFirmware/Marlin#6754]
```
sketch\Marlin_main.cpp: In function 'void gcode_M48()':

Marlin_main.cpp:6275: error: 'DELTA_PROBEABLE_RADIUS' was not declared in this scope

                   DELTA_PROBEABLE_RADIUS / 8, DELTA_PROBEABLE_RADIUS / 3

                   ^

exit status 1
'DELTA_PROBEABLE_RADIUS' was not declared in this scope
```

**Comment by Roxy-3D** [comment]
@joris57    I have verified what you said with the Kossel-XL files...   I'm trying to correct it.  But it is mixed up with other changes I have going.    In an hour or two I'll have the corrected file merged for you to grab.

If you are willing to flash a second time in an hour or two, you can just turn off M48 for now knowing soon you can turn it on.

**Comment by oldmcg** [comment]
@joris57, for now, in configuration.h, just after #define DELTA_PRINTABLE_RADIUS, add #define DELTA_PROBEABLE_RADIUS DELTA_PRINTABLE_RADIUS.

I will fix this in the delta sample configuration.h files but the final fix might be a little different.

**Comment by Roxy-3D** [comment]
@oldmcg    What I just merged is 'Reasonable'.  But you may have better ideas on how it should be done.

Update:  I see what you did!   I don't think we will have DELTA_PROBEABLE_RADIUS  problems again!

Thanks!

**Comment by joris57** [comment]
Issue resolved.
