### ISSUE TITLE
Flow rate modification when printing seems to cause erratic movement

### ISSUE THREAD

**Issue by jdelahayes** [MarlinFirmware/Marlin#6765]
It seems that when i change the flow rate of an extruder while printing there is few seconds later erratic movements of the carriage. The carriage start to go left, then reprint quite well, then go to the back of the bed, then there is movements on the z axe causinf the head to crash on the bed. I can repeat that every time i change flow rate when printing. The same gcode print well if i don't touch the flow rate.

I use bugfix-1.1.x, core xy, ramps, bilinear bed levelling. My config is here https://github.com/jdelahayes/Marlin/blob/bugfix-1.1.x-voron/Marlin/Configuration.h

![path](https://cloud.githubusercontent.com/assets/5601969/26129562/f6f9e642-3a90-11e7-83eb-7c5ffac18816.png)

**Comment by Maglin** [comment]
Just wanted to say I love the color of your Voron.  Have you recompiled and retired today?  A lot of changes have happened the last few days.

**Comment by jdelahayes** [comment]
Thank you @Maglin. I tested last night babystepping and I had the same problems. I will update the firmware with the latest commits and retest with babystepping.

**Comment by jdelahayes** [comment]
With the last bugfix-1.1.x commit i still have the same behavior. A line is skipped when the movement occurs.
![inked20170519_105013_li](https://cloud.githubusercontent.com/assets/5601969/26242897/501954a6-3c8a-11e7-8a75-1cf0d3b0bf0f.jpg)

**Comment by jdelahayes** [comment]
The print stopped suddenly ... the screen was frozen and the menus were no longer accessible. Strange movements had occurred at least 5 or 6 times during printing. Any idea on how i can debug or help debuging ?
![inked20170519_122302_li](https://cloud.githubusercontent.com/assets/5601969/26244331/85bc94ce-3c8f-11e7-82b4-c09d7c0bf5f5.jpg)

**Comment by jdelahayes** [comment]
Aaaargh ... the current limit of XY stepper drivers wasn't egal and too low ... sometimes one motor did not have enought torque and the carriage go straight to the back or the right of the bed ! it's always good to check everything before thinking it's the other's work that not work :) it's not a bug. Thank you for your time.

**Comment by Roxy-3D** [comment]
Yeah...  This is complicated stuff with a million variables...
