### ISSUE TITLE
RCBugfix vs bugfix-1.1.x

### ISSUE THREAD

**Issue by jasoncross** [MarlinFirmware/Marlin#6770]
What is the difference between the "RCbugfix" branch and the bugfix-1.1.x branch?  I had been using RCBugfix, but when 1.1.0 went final, it disappeared and bugfix-1.1.x appeared.  Now they both exist, and both get updates.  Which branch should be used for the latest in-development updates?

**Comment by FHeilmann** [comment]
I agree that RCBugFix should probably renamed to "devel" or something, since we are not updating RCs at the moment.

From the way I see it new commits are pushed both to bugfix-1.1.x and RCBugFix, but my best guess is that bugfix-1.1.x will stop receiving them at some point and RCBugFix will become the most bleeding edge again.

But maybe @thinkyhead can chime in what is plans are.

**Comment by Roxy-3D** [comment]
Good guess!  But "No!"   Please check out:  https://github.com/MarlinFirmware/Marlin/issues/6744

**Comment by jasoncross** [comment]
@Roxy-3D I'm not seeing how #6742 applies to this thread?

**Comment by Roxy-3D** [comment]
Sorry...   Let me find the right number.   I goofed up a Cut & Paste....

Fixed up above...

**Comment by jasoncross** [comment]
Ok, so bug-1.1.x is the one to use?

**Comment by Roxy-3D** [comment]
Yes, https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x

RCBugFix will go away when everything is moved to bugfix-1.1.x

**Comment by FHeilmann** [comment]
Maybe we want to consider making these things a little more clear.

One Idea:

- `master`
- `maintenance`
- `rc`
- `devel`

The workflow would then be as follows:

- `master` is what everyone should grab for a stable version of marlin
- `maintenance` contains fixes for either `master` or `rc` depending on whether we are moving towards a minor or major release
-  `rc` contains the newest release candidate once we are moving towards a major release
-  `devel` contains the bleeding edge

After a major release, `maintenance` is based on `master` and receives bugfixes.
During a minor release, `master` becomes `maintenance`.
Once a new major release is planned, `rc` and `maintenance` are moved up to `devel` and `rc` is released as the first release candidate. `maintenance`, at this point, receives bugfixes for `rc`.
During new release candidates,` rc` catches up with `maintenance`.
During a major release, `rc` and `master` become `maintenance`.

This would also solve one of the problems with current Marlin development: Feature Freezes. One could simply disallow anything but bugfixes against `maintenance` which would result in a feature freeze as soon as `rc` moves up to `devel` during the first release candidate. At the same time, `devel` could go wild all the time with new features.

The only thing one would have to take care of is applying fixes in `maintenance` to `devel` also if applicable.

**Comment by fiveangle** [comment]
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/README.md

> ## Contributing to Marlin
> 
> Click on the Issue Queue and Pull Requests links above at any time to see what we're currently working on.
> 
> _**To submit patches and new features for Marlin 1.1 check out the bugfix-1.1.x branch, add your commits, and submit a Pull Request back to the bugfix-1.1.x branch. Periodically that branch will form the basis for the next minor release.**_
> 
> Note that our "bugfix" branch will always contain the latest patches to the current release version. These patches may not be widely tested. As always, when using "nightly" builds of Marlin, proceed with full caution.

**Comment by Roxy-3D** [comment]
The current RCBugFix should go away when everything associated with it is moved.   But it probably re-appears when another Release Candidate appears.

**Comment by fiveangle** [comment]
Extraneous branches have been removed (or hidden) so this can be closed @jasoncross (or anyone with godmode powers 😊 )
