### ISSUE TITLE
Feature request: printing QUEUE

### ISSUE THREAD

**Issue by batata004** [MarlinFirmware/Marlin#6771]
Hi,

As some of you advised me in this GITHUB community, sometimes I need to execute a bunch of GCODES right after turning on my printer. I dont want to execute these GCODEs before everyprint, just before the printer is turned on.

So I created a GCODE file that runs perfectly all the procedures the printer has to do. But often I have to go to PRINT FROM SD CARD (LCD) and print this initial file and I HAVE TO WAIT it finishes so I can choose the actual printing file that I wanna print.

I need to wait all the procedures to finish so only after that I can tell the printer to print the actual file.

Is there someway I can "queue" printing SD files?

**Comment by fiveangle** [comment]
https://github.com/MarlinFirmware/Marlin/wiki/Autostart

This likely has had limited/no testing recently so unsure of state of the feature.  I believe SD card sorting has been implemented recently so you may need to ensure sorting direction matches what this feature expects.

Good luck !

-=dave

**Comment by batata004** [comment]
Grea great great!!!

**Comment by batata004** [comment]
@fiveangle actually I was wrong. You suggestion may sound good but it's not. Indeed the printer starts printing the auto0 file right when I turn it on BUT it does not allow me to queue the final file that I indeed wold like to print.

I need to wait the auto0 procedures to be completely done so I can, after that, start printing my file. I need to be around, close to the printer till it finishes the procedures of auto0 so I can click PRINT FROM SD and choose the right file.

**Comment by batata004** [comment]
Would it maybe be possible to me add a menu entry in the LCD that runs some gcodes? Is it possible to me create an entry in the LCD menus so when I click this entry it runs some gcode?

**Comment by fiveangle** [comment]
No, you rename the file you want to print auto1...
