### ISSUE TITLE
UBL should prohibit PROBE_MANUALLY

### ISSUE THREAD

**Issue by AlkalineJaunt** [MarlinFirmware/Marlin#6778]
The sanity check for UBL checks for a probe, but should exclude PROBE_MANUALLY.

Just making a note. I don't have time to fix it right now, but it causes compile errors.

**Comment by Roxy-3D** [comment]
Yeah...  I don't even know off the top of my head what the sanity check currently does.   It won't be much.   

UPDATE:  Oooops...  Upon review I think you meant SanityCheck.h   I was talking about UBL's extra sanity check.   

But the thing is...  We want to go the opposite direction.   UBL should work just fine with no probe.  We need to start relaxing constraints.   And let the user start with a G29 P0 (totally zero'ed mesh) or maybe G29 P0 and some G29 P2's  (manual probes).    And then let them jump to filling in the mesh with P3's.

Anybody that knows C and wants their non-probe printer to be able to bring up UBL...   I'll coach and help!!!  Just let me know.

**Comment by thinkyhead** [comment]
Let's think about whether we can make `probe_pt` do a manual probe via the LCD when there's no electronic probe. Then all the code that calls `probe_pt` can stay the same.

Manual probing via GCode-only is a little more tricky. See the ABL or MBL version of `G29` for the lowdown on how that can be implemented.

**Comment by thinkyhead** [comment]
#6791 should catch this scenario now.
