### ISSUE TITLE
Little Marlin 1.1.1 bug

### ISSUE THREAD

**Issue by edautz** [MarlinFirmware/Marlin#6790]
Upgrade my CTC Prusa I3 from 1.1.0-RC8 to 1.1.1.

I noticed a little bug. When using the manual bed level feature, after the start of this feature through the display menu, the text on my display vanished, after turning the rotary encoder the text appears. Same for the first calibration point. This bug was not present in 1.1.0-RC8.

I using a (GT)2560 rev A clone control board with a Amtel 1280 AVR and LCD2004 Reprap discount controller with rotary encoder.

**Comment by thinkyhead** [comment]
The LCD code has gotten a tweak here and there. I'll look into this some time today.

**Comment by Maglin** [comment]
I've seen the same behavior.  I never mentioned it though.  Using a Delta and UBL.

**Comment by thinkyhead** [comment]
> When using the manual bed level feature…

@edautz
`MESH_BED_LEVELING` or `PROBE_MANUALLY`?

**Comment by edautz** [comment]
@thinkyhead

Manual mesh bed leveling. I also noticed this sometimes after starting print from SD card, right after the heating and the leveling tasks. Kust when the printong task starts. Turning or pushing the encoder trigger text again.

**Comment by edautz** [comment]
@thinkyhead.

It is manual mesh bed leveling. I noticed sometimes after I start print from SD, after heating and homeing, printing starts and the text on the display also vanishes. Turn the encoder also displays the text again.

**Comment by thinkyhead** [comment]
Are you saying that the Status Screen disappears also?

**Comment by Roxy-3D** [comment]
> I noticed a little bug. When using the manual bed level feature, after the start of this feature through the display menu, the text on my display vanished, after turning the rotary encoder the text appears. 

This sounds similar to this:  https://github.com/MarlinFirmware/Marlin/pull/6822#pullrequestreview-39521334

That is why I added the 
```cpp
     lcdDrawUpdate = LCDVIEW_REDRAW_NOW;
```

**Comment by thinkyhead** [comment]
Hmm… well that indicates a bug that we're just hacking around. I'll re-examine the display logic some more. Is this the graphical or character display, or both?

**Comment by thinkyhead** [comment]
Hmm… well that indicates a bug that we're just hacking around. I'll re-examine the display logic some more. Is this the graphical or character display, or both?

Thing is, we must use `LCDVIEW_KEEP_REDRAWING` because it works on both.
```cpp
#if ENABLED(DOGLCD)
  bool drawing_screen = false;
  #define LCDVIEW_KEEP_REDRAWING LCDVIEW_CALL_REDRAW_NEXT
#else
  #define LCDVIEW_KEEP_REDRAWING LCDVIEW_REDRAW_NOW
#endif
```
If you're seeing the issue on one type of display but not the other, that would point to the use of `LCDVIEW_CALL_REDRAW_NEXT` or `LCDVIEW_REDRAW_NOW` instead of `LCDVIEW_KEEP_REDRAWING`.

**Comment by thinkyhead** [comment]
See if #6830 heralds a return to normalcy.

**Comment by Roxy-3D** [comment]
I saw the problem on a Graphical LCD Display.   I don't know that I've seen it on a 20x4 LCD Panel.

**Comment by thinkyhead** [comment]
Graphical display would be the one that manifests the issue, if it is related to the choice of `LCDVIEW` flag. The character display would not.

**Comment by edautz** [comment]
The screen is going complete blank, if this occurs with beginning of the print, the status screen is going complete blank. I use a lcd 20x4 char display.

**Comment by Maglin** [comment]
I experience the same thing using a 20x4 GLCD.  On a AnyCubic TriGorilla controller.  I'm using the RAMPS 1.4 define for the MB.  The stock FW was using MB 33 which I think is RAMPS1.3.  Is there even a difference?  Could this be the cause?

**Comment by Tannoo** [comment]
I see this now (when editing UBL mesh points) after running the code from this morning.

**Comment by renfrobr** [comment]
Same here using a 20x4 LCD. Screen blanks all over the place, any menu really. Touching the rotary encoder brings it back only to go blank again in the next screen/selection.

**Comment by Roxy-3D** [comment]
So the screen blanking problem is happening on both Graphical and 20x4 displays now???

**Comment by renfrobr** [comment]
Here we go ...

![blank-optimized](https://cloud.githubusercontent.com/assets/28952507/26473781/b2d8729a-4183-11e7-8974-e8738dde218b.gif)

**Comment by ghost** [comment]
I made a video about this bug. Look the issue: #6856

**Comment by gtavo** [comment]
I have the same problem, when trying to level the bed, the text vanishes, I have a REPRAP_DISCOUNT_SMART_CONTROLLER with 20x4

**Comment by emartinez167** [comment]
This is now fixed with the latest patches.

**Comment by renfrobr** [comment]
I can verify, it's fixed on my end

**Comment by edautz** [comment]
Marlin upgraded to 1.1.3. Problem gone.
