### ISSUE TITLE
Delta processing question

### ISSUE THREAD

**Issue by Maglin** [MarlinFirmware/Marlin#6801]
Does this bit of code get processed for every delta move?  Or does it figure it once and store it as XYZ_STEPS.  If it's the earlier I'll just replace this with the actual steps so this doesn't have to be mathed 160 times a second.
```
`// variables to calculate steps
#define XYZ_FULL_STEPS_PER_ROTATION 200
#define XYZ_MICROSTEPS 16
#define XYZ_BELT_PITCH 2
#define XYZ_PULLEY_TEETH 20

// delta speeds must be the same on xyz
#define XYZ_STEPS (XYZ_FULL_STEPS_PER_ROTATION * XYZ_MICROSTEPS / double(XYZ_BELT_PITCH) / double(XYZ_PULLEY_TEETH))`
```

**Comment by Roxy-3D** [comment]
The preprocessor of GCC does the calculations and the code 'knows' the number to use.
