### ISSUE TITLE
1284P with 1.1.1 restart loop

### ISSUE THREAD

**Issue by fred2088** [MarlinFirmware/Marlin#6803]
1284P with 1.1.1 release 
1. work fine by just define the board and TinyBoy2 - take up 72% of the program mem, 28% of global variable
2. restart loop when enabled SDSUPPORT - take up 77% of the program mem, 28% of global variable

**Comment by Bob-the-Kuhn** [comment]
Please ZIP up your FAILING configuration files & post them.  I'll see if I can reproduce it on a Sanguino.

**Comment by fred2088** [comment]
```cpp
#define MOTHERBOARD BOARD_MELZI
#define OLED_PANEL_TINYBOY2
#define SDSUPPORT
```
only changed 3 lines

**Comment by Bob-the-Kuhn** [comment]
I'm getting a boot loop also with 1.1.1 but not when using bugfix-1.1.x.

Please switch to [bugfix-1.1.x](https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x ) and see if that fixes the problem.

**Comment by thinkyhead** [comment]
@Bob-the-Kuhn I'll do a 1.1.2 release later today, assuming we don't have any serious regressions.

**Comment by Bob-the-Kuhn** [comment]
@fred2088 - better hold off on switching.  There's been reports on intermittent head crashes with the latest bugfix-1.1.x

**Comment by fred2088** [comment]
still got restart loop on 1284p with 1.1.2 
if enabled both
#define sdsupport
#define U8GLIB_SSD1306
or
#define sdsupport
#define OLED_PANEL_TINYBOY2

**Comment by Bob-the-Kuhn** [comment]
I forgot about this.  Sorry

Please try bugfix-1.1.x.

**Comment by fred2088** [comment]
oh.! sorry, tried bugfix-1.1.x also got the same restart loop error !!!

**Comment by fred2088** [comment]
either 
 #define sdsupport
 or
 #define OLED_PANEL_TINYBOY2
can work, but not both at the same time on bugfix 1.1.x and 1.1.2

**Comment by Bob-the-Kuhn** [comment]
I tried changing just the three lines on today's bugfix-1.1.x and didn't have any problems.

Please post a copy of what the host screen/log shows from a power up through 2 or 3 restarts.

**Comment by fred2088** [comment]
my bugfix.1.1.x is upto 14/5/2017, tried the lastest bugfix.1.1.x work fine

thanks, will try it out upto bugfix.1.1.x

**Comment by fred2088** [comment]
fixed by comment the following line from pin_Sanguino11.H on 1.1.2, 1.1.3, bugfix1.1.x
  #elif ENABLED(OLED_PANEL_TINYBOY2)  || ENABLED(U8GLIB_SH1106) || ENABLED(U8GLIB_SSD1306)
    #define BTN_ENC             28
//    #define LCD_SDSS            -1

**Comment by Bob-the-Kuhn** [comment]
I can't find that line in any of the pins_s*.* files.

**Comment by fred2088** [comment]
it's already deleted from 1.1.2, 1.1.3 and the lastest bugfix.1.1x
while the code from this section will work fine with comment out #define LCD_SDSS -1 ...

**Comment by Bob-the-Kuhn** [comment]
That's strange.  Usually a -1 will result in it being ignored.
