### ISSUE TITLE
Floating point temperatures

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#6805]
People seem to really want the decimal place back on the temperature displays.

http://forums.reprap.org/read.php?415,769199

Maybe we should change that back.  Except change the int to a double instead of a float ????

**Comment by Grogyan** [comment]
Why `double`? A `float` should be fine.

I too would like to see the return of the decimal point precision of the temperatures.

**Comment by Roxy-3D** [comment]
https://github.com/MarlinFirmware/Marlin/issues/6728#issuecomment-301285735

**Comment by teemuatlut** [comment]
All that's needed is to change degHotend (and degBed) to float and as far as I can tell, it is not called by an ISR. The temperature itself is already stored as float. The original PR doesn't explain why the change was made.


![class_temperature_a5c91c0779ca7d3ebcc58d5bb04f9eab5_icgraph](https://cloud.githubusercontent.com/assets/7762686/26279165/c43f463a-3db4-11e7-98aa-78490d407bf0.png)

**Comment by Roxy-3D** [comment]
What are the steps to get GitHub to generate a picture like that for other variables?

**Comment by teemuatlut** [comment]
It's generated by Doxygen (and graphviz). While Marlin doesn't yet officially use it and provide it somewhere, it already has adopted the proper comment styling for Doxygen to work.

**Comment by thinkyhead** [comment]
I recently changed all temperature handling code that didn't need `float` to use `int` — for performance and size. So don't just change it all back, please.

Just coerce the temperatures to `float` when they're printed or if they're being converted from sensor values, do that as `float`, but only for display. In most places temperatures can and should be handled as integers.

**Comment by thinkyhead** [comment]
I'll review my changes and see where these temperatures with decimals were coming from, and I should have a patch pretty soon.

**Comment by teemuatlut** [comment]
> where these temperatures with decimals were coming from

`degHotend()` - All this method is is a getter for "`current_temperature[HOTEND_INDEX]`". The variable already is a `float` and the method just returns it as `int16`.

> Just coerce the temperatures to `float` when they're printed

Can't just use type conversion if the decimal information is already lost in the method above. The easiest would be to have the `M105` and LCD to call for the member variable directly, since that it made public by the class. Which I actually find odd, usually class variables are private and accessed by getters/setters, yes?

**Comment by thinkyhead** [comment]
The getter has always been that way. Code that displayed the value as float in the past was merely bypassing the getter.

**Comment by teemuatlut** [comment]
It's returning float on all the 1.1.0-RCx tags.

**Comment by thinkyhead** [comment]
You're right, I was mis-remembering. Anyway, I have a patch pending that should clear up this issue.

**Comment by thinkyhead** [comment]
#6811 should have it covered.
