### ISSUE TITLE
End Stops 

### ISSUE THREAD

**Issue by Radiu** [MarlinFirmware/Marlin#6813]
My machine build will be the bed plate that moves up and down(Z axis), so my question is 
Where will i put my Z end-stops on bottom off my bed?
Do i use on my ramps 1.4 the  Zmin pins or Zmax pin?
Where im confused is if i use Zmin on bottom of bed-plate when i do homing  the plate will go to the bottom, so then do i have to put on software the piece to start at top?
or do i use the Zmax end-stop on bottom and when machine goes home hits the max travel and when i send G code will go to point 0 that will be touching the nozzle?
im confused in how it works, any help in explanation would help

thanks

**Comment by Bergerac56** [comment]
Hello,
In my case, I use the "min" option (Xmin, Ymin and Zmin). I use a contactless probe for the Z axe. The probe is mounted on the extruder carriage. This means that Z=0 when the bed is on top of the building chamber and at the correct distance of the nozzle. Z increases(Z>0)  when the bed goes down. Please note that the Zprobe does NOT detect directly the position of the bed, but the relative position of the nozzle as the probe is located on the extruder carriage. So, when the probe is correctly calibrated, the bed will never touch the nozzle and it becomes possible to do bed levelling. (In my case, the Zprobe is very near the hotend nozzle)

By the way, your question is not really an "issue" related to the firmware I think. It would be better to post it on one or another forum to get more answers ;).

Kind regards
