### ISSUE TITLE
"Set home offsets" not work.

### ISSUE THREAD

**Issue by dobryj** [MarlinFirmware/Marlin#6828]
Hello,

"Set home offsets" menu function working only when original offsets are zero. Problem is simple, it accidentally use old offset twice in calculation.

In details:
"Set home offsets" from menu execute function gcode_M428(). This function contain this two eqations:
 ```cpp
diff = current_position[i] - LOGICAL_POSITION(base, i);
set_home_offset((AxisEnum)i, home_offset[i] - diff);
```
Problem is that add home_offset[i] (and something more) to argument.
This mean that in result command execute

```cpp
set_home_offset((AxisEnum)i, home_offset[i] - (current_position[i] - ( base  + home_offset[i])));
```
This is equivalent to 
```cpp
set_home_offset((AxisEnum)i, 2*home_offset[i] - current_position[i] + base);
```
This is reason why it work only `if (home_offset == 0)`. Any other value work like poison for this equations.

I fix it to:
```cpp
set_home_offset((AxisEnum)i,  -diff);
```

It works perfectly for me now. But I don't know all possible configurations. It need to be fixed with someone with better knowledge of Marlin internals.

Found on version 1.1.1 (release)

Jiri

**Comment by thinkyhead** [comment]
Thanks! I've applied the fix you suggested…
https://github.com/MarlinFirmware/Marlin/commit/d4d703d29935cff4f38ad33deaa1cd10609f06df
