### ISSUE TITLE
Cross platform primitive types

### ISSUE THREAD

**Issue by p3p** [MarlinFirmware/Marlin#6835]
Marlin uses both platform dependent types (int, long) and constant bitwidth types (`int16_t`, `int32_t`). Having just rebased the 32bit branch again this caused a bit of frustration with the new ultralcd code, could there be an addition to the coding standards that require constant bitwidth types?

**Comment by thinkyhead** [comment]
I definitely patch up primitive types whenever I have a chance. I'll add a note about this to the coding standards page shortly. I have some other things I want to include there too, now that we've been doing this a while.

**Comment by Roxy-3D** [comment]
@thinkyhead   @p3p    Your thoughts on:  https://github.com/MarlinFirmware/Marlin/pull/6228#issuecomment-303504855
