### ISSUE TITLE
MKS-Gen-L controler pins?

### ISSUE THREAD

**Issue by Radiu** [MarlinFirmware/Marlin#6859]
could you tell me what is the board pins config to chose for the 
MKS-Gen-L controler 

http://www.ebay.com/itm/MKS-Gen-L-3D-Printer-Control-Board-Replace-Ramps-1-4-Mega-2560-R3-New/252814652501?_trksid=p2045573.c100033.m2042&_trkparms=aid%3D111001%26algo%3DREC.SEED%26ao%3D1%26asc%3D41376%26meid%3D14d2989d255c4af0b169c0d5fca3b7d9%26pid%3D100033%26rk%3D5%26rkt%3D8%26sd%3D311579630884

is the MKS-Gen-L a better choise vs the ramps 1.4?

thanks

**Comment by Bob-the-Kuhn** [comment]
Looks like you just specify one of the RAMPs flavors in your config file.

The nice thing is there are fewer boards needed.  A RAMPS system requires the Mega2560, the RAMPS shield and a display adapter.  Looks like they did a decent job of documenting the logical pins on all the connectors.

Doesn't appear to be much of a cost savings.

The bad thing is it's from MKS.  All their stuff is proprietary and they don't release the schematics.  This is only a problem if you're trying to do something unusual.
