### ISSUE TITLE
Loaded RC8 but extruder only extrudes through Pronterface

### ISSUE THREAD

**Issue by Crimsus** [MarlinFirmware/Marlin#6878]
EDIT: I can extrude manually through the controls as well. For some reason, the printer just won't extrude during a print. I can make it extrude manually ever other way possible except that one--the one that counts!

So RC8 solved a nasty bed leveling issue I had but now I have a new mystery. After loading RC8, my extruder will not extrude. I can command it through Pronterface to extrude for miles and miles, but I can't get it to extrude when printing or deliberately telling it too through the controls. Has someone else had this problem and beat it?

-Crimsus

**Comment by Tannoo** [comment]
Post your config files.

**Comment by Tannoo** [comment]
RC8 is old news. There is 1.1.x now.
