### ISSUE TITLE
Bed won't move above probe point using 'G30 S-1'

### ISSUE THREAD

**Issue by jeremyherbert** [MarlinFirmware/Marlin#6884]
With soft limits disabled, after using 

```
G28
G30
```

I can move the z axis to wherever I want. However, if I use

```
G28
G30 S-1
```

which I believe [is supposed to](http://reprap.org/wiki/G-code#G30:_Single_Z-Probe) just stop at the point that the probe triggers. From here, I can't move beyond the trigger point and I just get the following message:

```
echo:endstops hit:  Z:8.28 P:8.28
```

Software endstops are still disabled: `
echo:Soft endstops: Off  Min: X0.00 Y0.00 Z0.00  Max: X205.00 Y255.00 Z160.00`

Does anyone else have this issue? I am using the latest 1.1.1 release.

**Comment by thinkyhead** [comment]
```cpp
  /**
   * G30: Do a single Z probe at the current XY
   *
   * Parameters:
   *
   *   X   Probe X position (default current X)
   *   Y   Probe Y position (default current Y)
   *   E   Engage the probe for each probe
   */
```
