### ISSUE TITLE
Redefinition errors after defining TEMP_SENSOR_1_AS_REDUNDANT

### ISSUE THREAD

**Issue by SturmGhost** [MarlinFirmware/Marlin#6885]
After defining TEMP_SENSOR_1_AS_REDUNDANT I get two redifinition errors. Latest release.

In temperature.h 183-186

` #if ENABLED(TEMP_SENSOR_1_AS_REDUNDANT)
      static int redundant_temperature_raw;
      static float redundant_temperature;
    #endif`

Redefinition of static float redundant_temperature; (commenting out fixed the problem)

And in temperature.cpp line 128-131

`#if ENABLED(TEMP_SENSOR_1_AS_REDUNDANT)
  int Temperature::redundant_temperature_raw = 0;
 float Temperature::redundant_temperature = 0.0;
#endif`

Redefinition of float Temperature::redundant_temperature = 0.0; (commenting out fixed the problem)

**Comment by Bob-the-Kuhn** [comment]
It's been this way since at least RC8.

Strange seeing it in both the public & private areas.

I've initiated PR #6948 to make it only private.

**Comment by Roxy-3D** [comment]
How can it be both public and private?  Shouldn't that cause a compiler error?

**Comment by Bob-the-Kuhn** [comment]
It definitely is causing a compiler error now.
