### ISSUE TITLE
LCDVIEW_KEEP_REDRAWING not defined in latest commit

### ISSUE THREAD

**Issue by DaveAhrendt** [MarlinFirmware/Marlin#6888]
@Bob-the-Kuhn  
Compiling with MENU_ITEM_CASE_LIGHT defined results in compile error that LCDVIEW_KEEP_REDRAWING is not defined in scope.

Also note that there is no "default" configuration file entry for #define CASE_LIGHT_ENABLE as now required for case light support. Prior to 1.1 just CASE_LIGHT_PIN being defined was sufficient.  Now, without CASE_LIGHT_ENABLE defined, you get a compile error.

**Comment by Tannoo** [comment]
And the refernced issue is closed now. How about this one?
