### ISSUE TITLE
Printer resets on first layer when nozzle diameter >0.4

### ISSUE THREAD

**Issue by MennoLauwerens** [MarlinFirmware/Marlin#6891]
Hi,

After the upgrade to 1.1 my printer resets on some prints when I have sliced with a nozzle size 0.6 or 0.8 mm.
This happens while printing witch Octoprint and also when printing from SD.
There are no error messages to be seen anywhere.
I have tried lowering the feedrate, segments_per_second, acceleration, but nothing helps.
Calibration cubes and Benchy print out without problems.
I've attached the Gcode and the terminal output.

What is happening here ??

Printer : FLSun Mini Delta (Autocalibrate template)
Mainboard : MKS Base V1.5
Slicer : Simplify 3D

[files.zip](https://github.com/MarlinFirmware/Marlin/files/1035947/files.zip)

**Comment by thinkyhead** [comment]
Presuming solved…?
