### ISSUE TITLE
Error compiling in gcode.h

### ISSUE THREAD

**Issue by BlackLightUK** [MarlinFirmware/Marlin#6902]
Hi there. 

I've just tried compiling 1.1.2 after tweaking the configuration.h and configuration_adv.h for my Tevo Tarantula - and arduino 1.6.8 threw up an " invalid conversion from 'const char*' to 'char*' [-fpermissive] " on line 138 of gcode.h

**Comment by BlackLightUK** [comment]
There also appears to be a missing ) at the end of line 103 of the same file.

**Comment by p3p** [comment]
Hey, I think you misread at line 103 (the preprocessor makes it less clear) though I can confirm the warning at line 138 with FASTER_GCODE_PARSER disabled, It's probably just a missing typecast. This is just a warning though so it shouldn't have resulted in a failed build?

**Comment by Bob-the-Kuhn** [comment]
Try replacing line 138 with this:
`if (b) value_ptr = (char*) (DECIMAL_SIGNED(p[1]) ? &p[1] : NULL);`

That took care of a compile error in 1.1.x for me.

**Comment by BlackLightUK** [comment]
Many thanks, @Bob-the-Kuhn - that sorted the compile error. 
@p3p - yeah I misread the 103 bit - it was late and missed the ) a few lines down - my bad !

**Comment by Bob-the-Kuhn** [comment]
PR #6914 implements this fix.
