### ISSUE TITLE
G29 command and not printing bltouch

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#6926]
I'm using simplyf3d I put g29 command for bl touch after g28 it did auto leveling but It didnt start printing and just print % got high and it showed print done. How can I fix this or what can be problem?

**Comment by ghost** [comment]
but if i dont use g29 it starts

**Comment by Roxy-3D** [comment]
G29 does different things depending on which bed leveling system you are using.  In the UBL system, G29 (with no parameters) does nothing....   We need to know which system you are using.

**Comment by Bob-the-Kuhn** [comment]
Goes G29 work properly when you enter the commands by hand?

Please ZIP & post the following.  I'll see if there's anything really strange in it.
1. The first 100 lines of the file you're trying to print.
2. Configuration.h
3. Configuration_adv.h
