### ISSUE TITLE
Calibrating my nozzle

### ISSUE THREAD

**Issue by jamesjfc123** [MarlinFirmware/Marlin#6930]
How can I calibrate my nozzle with marlin firmware.

**Comment by Roxy-3D** [comment]
Typically....  the size of the nozzle's hole is a specified number.  Where ever the nozzle came from would tell you that number.    But you can raise the nozzle up 100mm above the bed and extrude 10mm of filament and then measure the thickness of the extruded material.  It won't be super accurate, but you can use a micrometer to decide if it is closer to .3mm or .4mm for example.

**Comment by jamesjfc123** [comment]
How would I tell it to extrude 10mm

**Comment by Maxqia** [comment]
http://lmgtfy.com/?q=extruder+calibration
:D (sorry couldn't help myself)

**Comment by Tannoo** [comment]
Yes. There is no "extruder calibration" in Marlin. Turn to your choice of host sofware for that.

**Comment by jamesjfc123** [comment]
Thank you. Any suggestion on what host software to use.

**Comment by Tannoo** [comment]
Pronterface, Repetier, Octoprint, Matter Control, Cura... bash prompt, Putty, etc, etc...

**Comment by Tannoo** [comment]
Google agrees:

https://www.google.com/search?q=3d+printer+host+software

**Comment by Tannoo** [comment]
Not trying to be mean.... but this is not a firmware issue. Please close.
