### ISSUE TITLE
G29 issue

### ISSUE THREAD

**Issue by raoul596** [MarlinFirmware/Marlin#6933]
I have a Prusa i3 with a probe sensor. G28 works fine, but after that I want to do the G29 command, but it just goes to the given locations without even going down in the Z axis (probing the bed). I have enabled the bilinear bed leveling. anyone that can help me out?

**Comment by raoul596** [comment]
I am sorry. I got what I had done wrong. didn't turn off the endstop pullup of the probe

**Comment by p3p** [comment]
Can you close the issue if it's resolved.

**Comment by Bob-the-Kuhn** [comment]
Usually the pullup is a good idea.  Try flipping the invert flags on Z_MIn and Z_PROBE.  That's the usual cause of this issue.
