### ISSUE TITLE
[Support]  Code to reset time?

### ISSUE THREAD

**Issue by mperdue** [MarlinFirmware/Marlin#6937]
Is there a code that can be sent to the printer to reset the time on the LCD to zero? It seems that when I have to about a print and restart it the elapsed time display continues from where it was. If there was a reset code I could add it to my start-up script and not have to mess with it any more.

**Comment by p3p** [comment]
I don't think there is a reset specifically, but M77 should stop the timer, and when started again it is reset. Although I would assume the Stopwatch should be stopped on abort, how are you stopping the print?

**Comment by mperdue** [comment]
I just use the stop button in Simplify 3D so I'm not really sure what it does.

**Comment by p3p** [comment]
Ah, I jumped to the conclusion you were printing from SD and stopping the print via lcd, pretty much everything is up to the host application when printing over serial, I'm not familiar with Simplify 3D they may not be sending an M77 when you click stop.

**Comment by mperdue** [comment]
I'll figure something out.
