### ISSUE TITLE
BABYSTEP_ZPROBE_OFFSET Didn't do Babystepping Properly

### ISSUE THREAD

**Issue by sarf2k4** [MarlinFirmware/Marlin#6944]
Running the bugfix 1.1.x downloaded on 30th May, I decided to enable the `BABYSTEP_ZPROBE_OFFSET` and test the printer today. Apparently the printer didn't adjust the z axis accordingly and more likely only adjust the z-offset. 

So I had to restart the print to see whether or not the z-offset has been adjusted properly.

I do know that this option is to integrate the babystepping z with m851 but there were no babystepping were done in the process except adjusting the z-offset, got to restart the print process to see the changes.

Was this intentional to change only z-offset instead of babystepping and offset at the same time?
If I enable `BABYSTEP_ZPROBE_OFFSET`, do I have to use "store memory" under control section?

**Comment by tcm0116** [comment]
Had you recently executed a G29? The Z axis will only be babystepped when adjusting the Z Offset if the machine has been leveled and the motors have not timed out (note that homing after leveling resets the leveling).

**Comment by sarf2k4** [comment]
I usually do babystepping during printing, i always have g28 followed by
g29, after both heaters reached theor target. Once the machine starts, i
check on the first layer if i need to use babystepping or not

**Comment by dot-bob** [comment]
Are you by chance using UBL?  If so see #6488

**Comment by RalphSch** [comment]
I also got the issue with not working z-baby-stepping when using bilinear abl and activated BABYSTEP_ZPROBE_OFFSET. I can babystep as much as I want but the nozzle stays at the same height. Using UBL to avoid this behavior is not an option ;)

**Comment by S1CAR1US** [comment]
why is this closed?  what is the solution?  I have same issue.

**Comment by thinkyhead** [comment]
@S1CAR1US — Please test `bugfix-1.1.x` and file a new report if you have this problem.
