### ISSUE TITLE
Enabling Dual_X_Carriage prevents moving axis other than homing

### ISSUE THREAD

**Issue by AndrewDiehl** [MarlinFirmware/Marlin#6956]
Trying to use the latest stable version.

When dual_X_carriage is defined I can home all axis successfully, but can not jog X0, X1, Y or Z. 
Un-defining dual_x_carriage allows the printer to run successfully in single head mode. 

My specific config files and pins definitions are attached. 
[pins_FABLICATOR.zip](https://github.com/MarlinFirmware/Marlin/files/1051102/pins_FABLICATOR.zip)

Thanks,
~Andrew

**Comment by oysteinkrog** [comment]
I can confirm this, it worked in 1.1.0.
Controlling from the LCD seems to work.

**Comment by oysteinkrog** [comment]
Also works in 1.1.1.

**Comment by oysteinkrog** [comment]
Hmm, for some reason my merged PR did not correctly close this, please close it now.
