### ISSUE TITLE
Annoyance: start PSU before move/heat

### ISSUE THREAD

**Issue by rubdos** [MarlinFirmware/Marlin#6968]
Hi,

This is a slight annoyance for me: when starting a print with a turned off power supply, it is impossible to start the power supply (M80) while Marlin waits for the heat-bed to heat (probably M190: Wait for bed temperature to reach target temp).

It would be nice if Marlin recognised this condition (heater on, but PSU off), and starts the PSU. Currently, I have to reset the printer in Pronterface, or, if I didn't notice, Marlin will terminate because of a heater failure.

**Comment by mtowara** [comment]
There is already a PR for this. It might end up in some later release.
#5875

**Comment by thinkyhead** [comment]
Merged!
