### ISSUE TITLE
Activate UBL compensation before print

### ISSUE THREAD

**Issue by sschueller** [MarlinFirmware/Marlin#6981]
Do I need to activate the UBL compensation before each print in my GCODE? Do I need to do a `G29 L1` and `G29 A` before each print after `G28`?

I couldn't find the answer anywhere.

**Comment by Roxy-3D** [comment]
What ever the state of the UBL Bed Leveling System when G28 happens...  That state will be restored at the end of G28.    If you activate UBL and do a M500...  The printer will power up with UBL active.   

That is what I do.   I don't even have a G29 in my Slic3r's startup GCode.    UBL is always active.
If you are unsure...  Do a G29 W and you will get all the facts about what UBL thinks is happening.   Close to the top of the list it will tell you if the system is active and which mesh (if any) is loaded.
