### ISSUE TITLE
Newest bugfix-1.1.x pretty much breaks CoreXY (and possibly others?)

### ISSUE THREAD

**Issue by FHeilmann** [MarlinFirmware/Marlin#6988]
I just tried to switch to MESH_BED_LEVELING for the fun of it and my CoreXY printer went batshit crazy as a result of it.

My working copy can be found here:

https://github.com/FHeilmann/Marlin/tree/bugfix-1.1.x

What I have found so far:

Homing performs a double touch, even though it is disabled. The double touch is made at full speed for Z and "minimum speed" for X and Y, even though HOMING_BUMP_DIVISOR is set to reasonable values in the configuration regardless of the bump being used or not.

Is there supposed to be no mention of leveling in the LCD anymore? I also think "Level Bed" disappeared for BILINEAR as well.

Fast movements in XY direction cause grinding steppers at speeds which are perfectly fine with BILINEAR.

This is all on a freshly synced bugfix-1.1.x from today.

edit: I am switching to UBL right now to test whether switching to MESH is the culprit or if any of the recent changes are responsible.

edit2: Happens with UBL too, so its not specific to MESH

edit3: Also, I saw messages like `"Endstops       Z  " ` show up on the LCD which seems to point to a memory issue

edit4: ALso happens on the configuration that was working fine before the last slew of commits.

**edit5: To confirm I did a "coarse" revert to 7f0945d and the issues are resolved so it is definately one of the commits since then that broke my printer.**

**Comment by Bob-the-Kuhn** [comment]
Please download [bugfix-1.1.x](https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x).  We just did a couple of changes that could solve this problem.

**Comment by FHeilmann** [comment]
Synced again today, Issues are resolved as far as I can tell.
