### ISSUE TITLE
G26 starts flooding the terminal

### ISSUE THREAD

**Issue by FHeilmann** [MarlinFirmware/Marlin#6989]
I wanted to bring up UBL, probed my bed whilst my temps were at 220/60, then issued a

`G26 B50 H200 F1.75 L0.3 N0.4`

which resulted in my terminal being flooded with temperature reports which also don't have proper line endings so they show up without any "newlines". This happens until the heaters reach the appropriate temps

**Comment by bgort** [comment]
I'm aware of this one and it's on my to-do list.  I'm pretty sure I know where the problem is, but I haven't yet tried my fix.

**Comment by BlackLightUK** [comment]
@FHeilmann `N0.4` isn't defined in the gcode documentation for G26 - what is it ? Nozzle diameter ?

**Comment by bgort** [comment]
Nozzle size is `S`.  As in `S0.4` .. I don't think there's an `N`.

EDIT:  Looks like someone changed it.. Pretty sure it used to be `N`.  I hadn't noticed until now.

EDIT2:  Yeah, it looks like it was changed about a month ago from `N` to `S`.

**Comment by FHeilmann** [comment]
Then the [comments on marlinfw.org](http://marlinfw.org/docs/features/unified_bed_leveling.html) should probably also change ;)

Regardless, if the parameter mixup really is the reason for the flooding it should be fixed too.

**Comment by bgort** [comment]
The parameter mixup isn't the issue, as far as I know now.  I'll try to fix it later today.  Have been meaning to for a while.

**Comment by FHeilmann** [comment]
@bgort can you point me towards your fix idea for this?

**Comment by FHeilmann** [comment]
solved by #7515
