### ISSUE TITLE
Error G command still return ok by serial

### ISSUE THREAD

**Issue by zhubinghan** [MarlinFirmware/Marlin#7002]
Hi:
  I send a error G command by serial. for example: I send 'G1  DDRE' by serial. FW return 'ok' . all 'G' and 'M' start string be send to FW, receive 'ok'.
marlin 1.1.3

**Comment by Tannoo** [comment]
Nothing happened except for `ok`, right?

**Comment by bobc** [comment]
Are you sure that is an invalid command ?  With Marlins' G code spec, it is interpreted as 

G1 D{d} D{d} R{r} E{e}

where {x} is current value of parameter x. This is effectively G1 to current position (the other parameters have no effect).

Edit: oops

**Comment by thinkyhead** [comment]
That's valid G-code.

Marlin doesn't return an error for unrecognized G-codes. They are all treated as no-op.
