### ISSUE TITLE
Reprap i3 prusa on t8, no boot ? 

### ISSUE THREAD

**Issue by jfxmedia** [MarlinFirmware/Marlin#7017]
So I'm trying to upgrade my firmware for my i3 prusa printer from reprap to Marlin RC8 to make use of the z probe options and install a bltouch bed leveler. When flashing to the rc8 firmware I only get a frozen LCD display with the booting lines and it never boots. Help !

**Comment by Tannoo** [comment]
Choose the correct LCD and flash it again.
