### ISSUE TITLE
Only Full Degrees via Serial?

### ISSUE THREAD

**Issue by ss89** [MarlinFirmware/Marlin#7018]
Hello everyone,

since i upgraded 2 of my printers to marling 1.1.0, they only output full degrees in serial (Repetier Host).
My Upgrade procedure is as follows:
1. update my git branch
2. resolve Configuration.h conflicts
3. upload to printer via Arduino IDE

Is this a configurable behaviour or even wanted? (I could imagine that since we are on an 8 bit platform for now, that non floating point calculations are just the better way for us to be faster/more responsive)

**Comment by p3p** [comment]
I think this was resolved in #6811

**Comment by ss89** [comment]
That's right. Sorry, i looked for "degree" like in degree celsius.
