### ISSUE TITLE
Can i use i2c to send Gcode to the Marlin ?

### ISSUE THREAD

**Issue by Zipstar** [MarlinFirmware/Marlin#7020]
Hello

I used to send G Code live through serial port rx tx with Arduino uno to the Arduino Mega with ramps 1.4 , but due to a lot of problems i try to find another way .
can i use i2c to do so ?

thanks in advance

**Comment by p3p** [comment]
There isn't a setting you can change to enable that as far as I'm aware. In general i2c is less robust than serial as it's a chip to chip standard, If you are having communication errors over serial they are likely to be worse with i2c over the same physical connection.
