### ISSUE TITLE
Heated bed temperature rises during printing

### ISSUE THREAD

**Issue by adasko1** [MarlinFirmware/Marlin#7043]
Hi, I recently changed my board to arduino mega clone + ramps 1.4. I flashed marlin 1.1 bugfix from marlin site. I would say nearly everything works, but I have one problem. 

When I preheat for example temps for PLA it heats up and stays on demanded temp. If I than set the temp to 0, bed cools down just fine. 
But when Im trying to print the temp of the bed starts continously  rising over the seted temp. Even setting bed temp during print to 0 doesnt change anything. Only way to stop bed temp from rising is resetting the board.
![20170612_122523](https://user-images.githubusercontent.com/28888274/27029864-600ce6d2-4f6a-11e7-9859-58367c9dcaf3.jpg)

**Comment by adasko1** [comment]
bump

**Comment by adasko1** [comment]
Ok, I figured out that the bed start heating above set temp, when i set the cooling fan on 100%, anybody know what can be wrong?

**Comment by Bob-the-Kuhn** [comment]
Could the fan shorted to the bed?

**Comment by ss89** [comment]
I do have the same problem with Marlin 1.1.1 stable, will try to just unplug the fans and report back
EDIT: Same problem happening, when fans are unplugged.

**Comment by ss89** [comment]
Last thing i did was replacing the arduino and the ramps board.
Since i just tested that the arduino is fine, i will now replace the ramps board with the one that was inside that machine before.

**Comment by ss89** [comment]
@adasko1 Please try to replace your ramps board. I had just replaced mine and after switching back the problem was gone. I had mine from here: https://www.aliexpress.com/item/F401-1pcs-RAMPS-1-4-3D-printer-control-panel-printer-Control-Reprap-MendelPrusa/1519223336.html?spm=2114.13010608.0.0.XHORbf
So you better NOT buy from that seller.

**Comment by Bob-the-Kuhn** [comment]
Please ZIP up both your config files & drop on your reply.

With that I can see if there's something wrong in your setup.
