### ISSUE TITLE
Strange behavior at Ultimaker Original when homing - need assistance

### ISSUE THREAD

**Issue by Drayson80** [MarlinFirmware/Marlin#7049]
Dont know if it is a bug or just an Error80 (so my fault) but I could not manage to port my config.h and .adv settings form a 2014 Marlin to the new 1.1.3
Issues: 
when homing, it ignores the endstops
when moving (independend of 0,1 or 1 or 10mm) it makes a few mm and then stops
moving into "negaitve" direction is not possible, also when proir moving (a few mm) into "positive" direction.

I assume, it's a fault in settings so if anybody could take a look, I would be gratefull.

Ultimaker setup with dual extrusion, self built heat bed and Silent Step Stick drivers TMC2100 at all 5 steppers.
Attached also my 1.1.3 config files
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/1070745/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/1070746/Configuration_adv.h.txt)

**Comment by raguera** [comment]
Hello,

Have you tried to invert your endstops logic?

I have dual extrusion in my printer and endstops work fine.

**Comment by Drayson80** [comment]
thank you for the hint - will doublecheck it...

**Comment by Drayson80** [comment]
seems I inverted the endstops twice... so that was the issue. Thanks for the hint.
now start testing...
