### ISSUE TITLE
Marlin serial connect to another arduino.

### ISSUE THREAD

**Issue by Zipstar** [MarlinFirmware/Marlin#7055]
Hello 
I have Arduino mega with ramps 1.4 and i try to connect another Arduino to send G Code live through the serial port .
When i open serial connection and send the G Code through the computer everything work fine and i see the messages and can send the code but when i try to do so with another Arduino that will send the G Code to the Mega its not working and i don't see any  message.
i will be more than happy if someone can help me with that issue.
Thanks

**Comment by Tannoo** [comment]
RX and TX not correct?
Transmitting to the incorrect Mega serial port?

**Comment by Zipstar** [comment]
RX TX correct ... its like the Marlin waiting to some code to send to start working

**Comment by Tannoo** [comment]
That's what it sounds like. So, serial port selection, wiring, or speed issues.

**Comment by Zipstar** [comment]
but its not ..
i think Marlin firmware is waiting to some command to start the serial communication .
when i plug the Mega to the computer and "listen" with another arduino connect to the 0/1 (Rx Tx) i can see the communication between them .

**Comment by Tannoo** [comment]
Aren't ports 1 and 2 for Serial0? Same port as the usb?

**Comment by Tannoo** [comment]
Well, ports 0 and 1.

**Comment by Zipstar** [comment]
yup , usb connection is serial

**Comment by Tannoo** [comment]
Search for serial here and see what you can find in pas discussions. You can also search arduino forums. Maybe even 3D printer forums.

**Comment by Tannoo** [comment]
*past

**Comment by Tannoo** [comment]
Yes, but USB is  special. Lol

**Comment by Tannoo** [comment]
I believe it also using RS232 which does not support more than 2 devices talking to each other.

**Comment by jimovonz** [comment]
Are you using the correct EOL char? I believe that Marlin expects a \n char terminating the command. Also, it seems you need to use uppercase.
