### ISSUE TITLE
QuadRap support (and axis-swapping generally)

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#706]
A new RepRap printer called the "QuadRap" has just recently been released, and it uses a somewhat different arrangement of motors. The X axis uses two stepper motors, while the Z axis uses only one. So, it would be simplest for most boards if we could simply swap the "X" and "Z" axes. However, pins.h makes no allowances for this kind of setup, except through direct editing.

I'd rather not add a setting for QuadRap specifically, but I would like to see better support for atypical arrangements, as we are seeing more of these all the time. So I propose to add a Configuration.h (or _adv) setting for swapping axes. It would either be a single setting such as "swap_axes" which you could set to "XZ" or "YZ" (or even "XY", "XE1", "YE1" etc.) or, more verbosely, a group of boolean settings such as SWAP_X_WITH_Z, SWAP_Y_WITH_Z, etc.

I'd be interested in any feedback on this idea before I proceed to implementation.

**Comment by boelle** [comment]
since we have agreed that hardware support should come from the vendors should this one not be closed?

**Comment by fmalpartida** [comment]
Yep.
