### ISSUE TITLE
1.1.3 Custom Bootup Logo Screen // RepRap FullGFX Discount LCD

### ISSUE THREAD

**Issue by bolsoncerrado** [MarlinFirmware/Marlin#7061]
So I've googled past and present issues with RepRap LCDs and I did generate a logo to customize our printers, created the _Bootscreen.h as adviced and posted it on the Marlin folder. Everything compiles fine, but the bootup logo screen doesnot change at all.

Is it defined at dogm_bitmaps.h now, no matter which LCD you have? Do I have to change all the WIDTH/HEIGHT shown there?

Or what am I missing here??

Thanks!

**Comment by tcm0116** [comment]
You might try adding:

```
#if ENABLED(SHOW_BOOTSCREEN) && ENABLED(SHOW_CUSTOM_BOOTSCREEN)
  #include "_Bootscreen.h"
#endif
```

after

```
#define SHOW_CUSTOM_BOOTSCREEN
```

in Configuration.h

**Comment by Roxy-3D** [comment]
If you post your boot screen source code...   I can turn it into a text file....  So you can see it without hoping it is hooked into the LCD Panel code right.

**Comment by bolsoncerrado** [comment]
Yeah but main question is: where is the width/height of the LCD being used defined? Is the dogm_bitmaps.h file used always anyway?

**Comment by HoangHai1411047** [comment]
128 for the width and 64 for the height
