### ISSUE TITLE
G33 Probe retract and extend.

### ISSUE THREAD

**Issue by dagnall53** [MarlinFirmware/Marlin#7065]
Is it necessary to do an explicit Z probe deploy/retract before and after each individual G33 measurement? 

Would it be possible to leave the probe down and just go to the next measurement in the sequence? 
This is especially "interesting" with an Allen Key Z probe, as the G33 sequence seems to spend almost all of its time retracting and deploying the probe...  
Or am I missing something subtle about the G33 test sequence?
Many thanks
Dagnall

**Comment by oldmcg** [comment]
I think bugfix_1.1.x branch has that behavior changed recently to default no retract between probes.

**Comment by LVD-AC** [comment]
has also been merged into 1.1.3

**Comment by LVD-AC** [comment]
Can be closed now
