### ISSUE TITLE
Bed Level has phantom points that are way off

### ISSUE THREAD

**Issue by Whytehorse** [MarlinFirmware/Marlin#7088]
I ran g33 and then g26 and got the perfect first layer. When I load up Cura, I tell it to load the mesh in slot 0 and activate bed leveling. At X=80, Y=0 it raises the nozzle to 50mm for no reason. Here's the mesh it's loading and the bracketed value is the nearest point:
 0.207    0.136    0.064   -0.100   -0.082    0.057    0.019    0.049    0.087    0.125

  0.101    0.069    0.038    0.030   -0.037    0.032    0.099    0.049    0.059    0.068

 -0.112    0.003    0.011    0.061    0.037    0.036    0.031    0.068    0.031    0.008

 -0.112   -0.087   -0.051   -0.039    0.020    0.000   -0.046    0.030    0.000   -0.053

 -0.050   -0.049   -0.050   -0.055   -0.100   -0.100    0.000   -0.001   -0.039  [-0.055]

  0.028   -0.150   -0.061   -0.110   -0.095   -0.100    0.000   -0.060   -0.044   -0.086

  0.107    0.044   -0.028   -0.080   -0.069   -0.017    0.011   -0.021   -0.073   -0.019

  0.186    0.033   -0.027   -0.091   -0.093   -0.031   -0.002    0.000   -0.009    0.047

  0.199    0.073   -0.053   -0.111   -0.120   -0.021    0.043    0.037    0.171    0.306

  0.280    0.114   -0.053   -0.138   -0.130    0.005    0.097    0.074    0.351    0.629

I'm guessing there is some calculation being performed and this is outside the probeable radius?

**Comment by Roxy-3D** [comment]
Yes...  You need to keep the nozzle over the mesh with UBL.   This restriction is being relaxed.   But for right now, don't go off of the 'Printable Radius' while printing.
