### ISSUE TITLE
discount reprap full graphic display issue

### ISSUE THREAD

**Issue by Gigglebear1** [MarlinFirmware/Marlin#7099]
im using u8glib 1.18.0 and i have tried 1.19.0 with no luck. trying to figure out if this is a display issue or a firmware issue.

here the symptoms. display starts and displays proper for about 10-15 min then it does something like this

![img_2044](https://user-images.githubusercontent.com/8579841/27314253-94b40dd0-5540-11e7-8cf9-ad72e9d09fd0.JPG)

then after about 2 hours it goes complete bonkers and looking like this 

![img_2049](https://user-images.githubusercontent.com/8579841/27314272-aab70c54-5540-11e7-9995-8c2e37c60e42.JPG)

i downloaded the u8glib 1.18.0 and 1.19.0 from the website listed in marlin 1.1.3.

only thing that points me to a firmware issue is that it is fine for 10-15 minutes

i have the full graphic discount uncommented as well as the sdsupport(which works fine even whe display is not displaying properly )

please help and thanks you in advance. 👍

**Comment by Bob-the-Kuhn** [comment]
Chances are good that you have a bad LCD.  My unit looked like your first photo after a couple of hours, then 1 hour and eventually after 2-3 minutes and now dead.  A new unit works just fine.

This was with bugfix-1.1.x a month ago without downloading/using any newer u8glib revisions than what is in the Arduino IDE.

**Comment by pmbroth** [comment]
looks like a bad lcd, I have the same one connected along with the mkstft 32 and do not have any issues.

**Comment by luisqcosta** [comment]
I have the exact same issue with my lcd. Most likely it is a defective one... I tried every combination of libs in the hope that it would fix the issue, but no success. Anyway, it came from a Chinese vendor who refunded me (lucky me!). Time to get a new one and play the lcd lottery again!

PS: mine also refers www.bigtechtree.com as its origin, for what it´s worth.
