### ISSUE TITLE
Non G29 Z offset?

### ISSUE THREAD

**Issue by Sungod3000** [MarlinFirmware/Marlin#7102]
Hi,

Im looking for a software z offset that isnt connected to G29. As far as I understand it M851 only works in conjuction with G29.

I tried M206 but the command never gets confirmed and it also shows up empty in the eeprom settings. 
Should autobedlevel be completly deactived in order for M206 to work or is there a different setting or Gcode that has this z offset function?

Cheers

**Comment by Roxy-3D** [comment]
What are you trying to accomplish?

**Comment by Sungod3000** [comment]
Im printing on different materials like paper and cardboard that I tape to my normal bed. To not always have to move the z endstop (which has no simple adjustment screw) I would like to offset the Z axis by software.

**Comment by Roxy-3D** [comment]
But isn't that the intended purpose of a Z-Probe?  It doesn't really care where the bed is...  It just finds it and sets the zero point from that information?

**Comment by Sungod3000** [comment]
Im working on that seperatly but I havent had much succes with that, so for now I work without z probe, just manual levelling.

**Comment by CantSayIHave** [comment]
I believe you're looking for M212. You can do M212Z-0.1 to offset the extruder 0.1mm below measured 0. I use this every time I have a material change on my printrbot

**Comment by CantSayIHave** [comment]
To add to that, you can check your offsets with M114 and store them with M500

**Comment by Sungod3000** [comment]
yes i saw M212 as well but its printerbot specific.

**Comment by thinkyhead** [comment]
Either `M206` or `G92` will offset the coordinate space.
