### ISSUE TITLE
Current Layer info instead ETE print on LCD

### ISSUE THREAD

**Issue by fonst3r** [MarlinFirmware/Marlin#7108]
Can I change LCD info from ETE to Current Layer/Final Layer info?
I'm using "RepRapDiscount Full Graphic Smart Controller"

**Comment by FHeilmann** [comment]
As far as I am aware, Marlin does not do any ETE computations to display. That's done by your host software.

**Comment by Lord-Quake** [comment]
That's the case with Repetier-Host. It sends the information periodically to the printer.

**Comment by fonst3r** [comment]
I see, yes I am using repetier host, and I doesnt like the ETE time, because its not so accurate.
thanks
