### ISSUE TITLE
G33 P7 V1 stops early on bugfix-1.1.x

### ISSUE THREAD

**Issue by joris57** [MarlinFirmware/Marlin#7111]
G33 P7 V1 stops after 2 iterations at a std dev of 0.44 where previously on the same printer a std dev of 0.016 was achieved (after several more iterations).

**Comment by thinkyhead** [comment]
@LVD-AC Do you know what might be going on here?

**Comment by PatDW** [comment]
Experiencing the same issue with G33 P3, stops at 2 iterations with std. dev. 0.404. My pull from 06.09.2017 is working fine and continues to probe.

**Comment by LVD-AC** [comment]
Sometimes there is a bump in the road towards the ideal solution. Setting the height off by 1mm with M665 Hx.x. and rerun G33 usually helps to get over it... 

I've been cracking my brain for a while to detect this automatically... In the mean time I could introduce a Fn parameter for that purpose that forces the routine to do at least n iterations.

See #7148

**Comment by joris57** [comment]
I don't think this will solve it. I think something is wrong with the probing (see the issue of the 'shrinking delta').

Below you'll find the G33 output from the same calibrated printer, the first one from bugfix-1.1.x, the 2nd one from your own 1.1.3 repository. bugfix-1.1.x reports a height discrepancy (c:+0.57) where 1.1.3 AC finds the printer calibrated (as I would expect : c:+0.00).

```
Send: G33 P4 V2
Recv: G33 Auto Calibrate
[...]
Recv: Checking... AC
Recv: .Height:303.60    Ex:-6.34  Ey:+0.00  Ez:-3.01    Radius:99.16
Recv: .Tower angle :    Tx:-0.24  Ty:+0.06  Tz:+0.00
[...]
Recv: .      c:+0.57     x:+0.54   y:+0.54   z:+0.55
Recv: .                 yz:+0.56  zx:+0.57  xy:+0.57
Recv: Iteration : 01                                    std dev:0.556
Recv: .Height:303.01    Ex:-6.34  Ey:+0.00  Ez:-3.01    Radius:99.10
Recv: .Tower angle :    Tx:-0.25  Ty:+0.04  Tz:+0.00
Recv: 
[...]
Recv: .      c:+0.56     x:+0.55   y:+0.56   z:+0.56
Recv: .                 yz:+0.58  zx:+0.57  xy:+0.58
Recv: Calibration OK                                    rolling back.
Recv: .Height:303.60    Ex:-6.34  Ey:+0.00  Ez:-3.01    Radius:99.16
Recv: .Tower angle :    Tx:-0.24  Ty:+0.06  Tz:+0.00
Recv: Save with M500 and/or copy to Configuration.h
```
```
Send: G33 P4 V2
Recv: G33 Auto Calibrate
Recv: Checking... AC
Recv: .Height:303.60    Ex:-6.34  Ey:+0.00  Ez:-3.01    Radius:99.16
Recv: .Tower angle :    Tx:-0.24  Ty:+0.06  Tz:+0.00
[...]
Recv: .      c:+0.00     x:-0.02   y:-0.02   z:-0.01
Recv: .                 yz:+0.01  zx:-0.00  xy:+0.00
Recv: Iteration : 01                                    std dev:0.014
Recv: .Height:303.60    Ex:-6.34  Ey:+0.00  Ez:-3.00    Radius:99.12
Recv: .Tower angle :    Tx:-0.22  Ty:+0.06  Tz:+0.00
Recv: 
[...]
Recv: .      c:-0.01     x:-0.03   y:-0.01   z:-0.01
Recv: .                 yz:+0.01  zx:-0.01  xy:-0.01
Recv: Calibration OK                                    rolling back.
Recv: .Height:303.60    Ex:-6.34  Ey:+0.00  Ez:-3.01    Radius:99.16
Recv: .Tower angle :    Tx:-0.24  Ty:+0.06  Tz:+0.00
Recv: Save with M500 and/or copy to Configuration.h
```

**Comment by LVD-AC** [comment]
Something weird going on in BugFix...

**Comment by LVD-AC** [comment]
Bug 'fixed' for now in #7148 by reverting to previous state. But someone needs to check that change from current_position to RAW_CURRENT_POSITION and the use of home_offset[Z_AXIS].

**Comment by joris57** [comment]
Some further testing : looks like the delta observed in subsequent G33 P1 is equal to (z probe offset (as set with M851) minus 0.04).

**Comment by LVD-AC** [comment]
Bug fixed more permanent for Delta's; probing did report false results with G29 G33 as well on Delta's. Someone needs to check this on Cartesians as well.

PS: error was home_offset[Z_AXIS]; for Delta's this is DELTA_HEIGHT from Configuration.h - delta_height set with M665 or by G33 calibration; on Cartesians home_offset is set with M206 or M428 and is used for a different purpose but IMO will result in the same Z-error.

**Comment by LVD-AC** [comment]
Issue closed?

**Comment by joris57** [comment]
Let's assume so. At the moment, I am using your 1.1.3-AC branch. Thanks for looking into this.
