### ISSUE TITLE
X and Y - Axis make short stop after G29

### ISSUE THREAD

**Issue by petrusmuc** [MarlinFirmware/Marlin#7140]
Hi All,
I have a weird effect lately on my printer:
When printing some item the first layers (app. 20 - 30) print well and then there is a shift in position (app 5 mm) which makes all further layers printing partly outside the model and therefore the print is rendered useless.
After checking the mechanical part of the printer thoroughly and changing both x and y stepper drivers without positive results I detected a weird behaviour:

- reset the printer
- issue G28 (Home All Axis)
- issue G1F1000
- move x-axis from X20 to X170 and back
   no issue
- issue G1F2000
- move x-axis from X20 to X170 and back
  no issue
- issue G29 (Auto Bed Leveling)
after completition:
- issue G1F1000
- move x-axis from X20 to X170 and back
   no issue
- issue G1F2000
- move x-axis from X20 to X170 and back
  X - Axis makes a short stop at app. X140 and continues
Same effect for Y - Axis.
Only at speeds below F1500 axis moves continuously from end to end.

My machine:
Prusa i3 pro B clone
Geeetech GT2560 A+ Board
Stepper driver DRV8825
Marlin version 1.1.2
Op Voltage: 24V 15A

Has anyone any good idea how to "cure this ailment" ?

Thanks in advance and best regards

Peter

**Comment by thinkyhead** [comment]
Presuming this is fixed.
