### ISSUE TITLE
Can't compile with #define PINS_DEBUGGING on Atmega1284p

### ISSUE THREAD

**Issue by benlye** [MarlinFirmware/Marlin#7151]
@Bob-the-Kuhn, I tried to compile with `#define PINS_DEBUGGING` enabled on my Atmega1284p-based Anet board and ran into a bunch of compiler errors to do with fastio and pins 46 and 47.

In pinsDebug.h I noticed that you have two types of conditionals for TeensyDuino - `#if AVR_AT90USB1286_FAMILY` and `#ifdef AVR_AT90USB1286_FAMILY`.  If I change all the `#ifdef`s to `#if`s everything compiles and M43 works.

Is it as simple as a replacing the check?  Do you want me to submit a PR for my fix?

**Comment by Bob-the-Kuhn** [comment]
Yes, please submit the PR.
