### ISSUE TITLE
issue with feed rate over 5900

### ISSUE THREAD

**Issue by cdedwards** [MarlinFirmware/Marlin#7154]
I'm using 1.1.3 currently and setting up my delta for the first time. found a odd issue that has to be firmware as it locks up the display as well as the connection from simplify and marlin.

G0 F8000 X-77.94 Y-45 Z0

the F8000 is the culprit and if I change it to 6000 the same happens. it will work correctly at 5900, so somewhere in between there is a problem.

**Comment by fiveangle** [comment]
known issue as delta kinematics require more cpu, so you are exhausting the capacity.  Easiest solution if you must print faster is to drop microstepping from 1/16 to 1/8 or 1/4 (and deal with the increased stepper noise)
