### ISSUE TITLE
SD is not init on startup ?

### ISSUE THREAD

**Issue by fred2088** [MarlinFirmware/Marlin#7155]
Dear Sirs,

SD is not init on startup while RC1.0.8 work fine, is there default #define is changed ?

I have try to #define sd_detect_pin -1
also try to disable sd_detect_inverted, but no lucik

TIA

**Comment by Bob-the-Kuhn** [comment]
Check SDSUPPORT in configuration .h.  It's disabled by default.

**Comment by fred2088** [comment]
#define SDSUPPORT already, but need to select "init sd card" manually every startup the printer

**Comment by Bob-the-Kuhn** [comment]
What host software are you using?

What happens (or doesn't happen) when you do not issue the  "init sd card" ?


Please post the log of the following sequence:
1. power up/reset the controller
2. issue `M20` command to the controller

**Comment by fred2088** [comment]
I am not connecting any pc, power on the printer, and the sd card is not init by default(enabled from firmware) after I press the init sd card, it can list and print the file from sd card, 

Regards

**Comment by fred2088** [comment]
M145 S1 H240 B110 F0
echo:PID settings:
echo:  M301 P22.20 I1.08 D114.00
Begin file list    <<<<<<<<<<<<<<<< M20, the SD card is always there
End file list
ok
echo:enqueueing "M21"  <<<< "INIT SD CARD from LCD Menu"
echo:SD card ok
Begin file list   <<< M20 again the SD card is always there
YODA.GCO 18065447
BODY.GCO 17498505

**Comment by Bob-the-Kuhn** [comment]
Please ZIP up your entire Marlin directory and attach it to your reply.  I need to know what version of Marlin you are working with.

As best I can tell the SD_DETECT_PIN is disabled or doesn't exist on your system.  When I do that the LCD now shows two LCD menu lines:
```
Print from SD ->
Change SD card
```

When I click `Print from SD ->` I get the file list plus a `Refresh` menu item. 

When I click the `Change SD card` I see `echo:enqueueing "M21"` in the console log.

----

I'm not seeing "init sd card" on the LCD, In Repetier Host or Pronterface.  You'll need to take a picture or a screen shot so I understand what you mean by "press the init sd card".

**Comment by fred2088** [comment]
![github](https://user-images.githubusercontent.com/8401029/27649331-04f5a098-5c64-11e7-8a20-cfe69cfda08c.jpg)

can't upload the marlin zip file, sorry, it's saying that my zip can't support to upload 
I am using bugfix 1.1.x

**Comment by Bob-the-Kuhn** [comment]
The picture gave me enough info to track down the code.

I need more info.  Please do the following:
- hook up the USB cable to the PC
- start the host software
- clear the host software's log
- connect to the printer
- wait for the startup messages to finish
- use the LCD to issue the init SD card command
- copy the entire log into a .TXT file
- attach the .TXT file to your reply.

I'd still like to see your configuration.h file.  Make a copy of it and then add .TXT to the file name after the .h.  Now you can attach the copy to your reply.

**Comment by fred2088** [comment]
it's seem don't have init sd card from marlin when boot up
echo:Material heatup parameters:
echo:  M145 S0 H180 B70 F0
  M145 S1 H240 B110 F0
echo:PID settings:
echo:  M301 P22.20 I1.08 D114.00
echo:Filament settings: Disabled
echo:  M200 D3.00
echo:  M200 D0
echo:enqueueing "M21"  < ------ Manually init sd card from LCD Menu
echo:SD card ok

[github.txt](https://github.com/MarlinFirmware/Marlin/files/1110741/github.txt)

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/1110742/Configuration.txt)

**Comment by Bob-the-Kuhn** [comment]
You're not running Marlin bugfix-1.1.x.  You're running a modified version of it.

I can't find the software for a Tinyboy E8.

I can't find a schematic or a pinout for the TINYOLED.

At a minimum I need the software that you're running.  Please try to attach the .ZIP file again.  If that doesn't work then use a service like [DropBox](https://www.dropbox.com/downloading) and include the link.  If you do use DropBox get the Basic version - that one is free.

Can you point me to any technical documentation on the TINYOLED?

**Comment by fred2088** [comment]
find the problem that when enable this define, it will not init sd on starting the printer
#define SHOW_CUSTOM_BOOTSCREEN
if #define CUSTOM_BOOTSCREEN_TIMEOUT   3000 <<<  ---- it will not init sd on starting the printer
if #define CUSTOM_BOOTSCREEN_TIMEOUT   2000 <<<  ---- it will not init sd on starting the printer
if #define CUSTOM_BOOTSCREEN_TIMEOUT   1900 <<<  ---- work fine
if #define CUSTOM_BOOTSCREEN_TIMEOUT   1800 <<<  ---- work fine
if #define CUSTOM_BOOTSCREEN_TIMEOUT   1500 <<<  ---- work fine
if #define CUSTOM_BOOTSCREEN_TIMEOUT   1000 <<<  ---- work fine

otherwise it works fine ...

**Comment by Bob-the-Kuhn** [comment]
I'd never have guessed that they would interact.

Glad you found a solution.

**Comment by thinkyhead** [comment]
I believe the problem is that `safe_delay` is being called from `lcd_implementation_init`, preventing initialization from completing.

You can try this…. In `ultralcd.cpp` find the `lcd_init` function (around line 4050). Move these lines from their current position near the end of that function…
```cpp
  #if ENABLED(SDSUPPORT) && PIN_EXISTS(SD_DETECT)
    SET_INPUT_PULLUP(SD_DETECT_PIN);
    lcd_sd_status = 2; // UNKNOWN
  #endif
```
…to the beginning of the `lcd_init` function, right before the call to `lcd_implementation_init`.

If that doesn't fix the issue, a small re-work of the lcd init routines will be done to address it.

**Comment by thinkyhead** [comment]
See if #7211 has any effect. It's a minor cleanup of the boot screen code.

**Comment by Uinden** [comment]
Hi. 
I have same problem.
My printer is `Anet A6` and boad is `Anet V1.0`
Host is `Repeiter-Host V2.1.3`
Tried `Marlin 1.1.9` release and `bugfix-1.1.x` branch, both have same problem.
Modified configs from `example_configurations/Anet/A6/`
After boot I have menu items `No SD card` and `Init. SD card`
After I press `Init. SD card` it start to work.
`M20` shows this:
```code
00:50:20.548 : N15 M20*37
00:50:20.552 : Begin file list
00:50:20.552 : End file list
00:50:20.553 : ok
```
Clear log, power on, wait, press `Init. SD card` produces this log:
[bugfix-boot-log.txt](https://github.com/MarlinFirmware/Marlin/files/2320001/bugfix-boot-log.txt)
Enabling `#define SHOW_CUSTOM_BOOTSCREEN`, downloading random `_Bootscreen.h` and adding `#define CUSTOM_BOOTSCREEN_TIMEOUT 1900` did not help.
Attaching my configs.
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/2319989/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/2319990/Configuration_adv.h.txt)

Any ideas?

**Comment by LemaruX** [comment]
Same issue here on an Ender 3 since updating to 1,1.9

**Comment by gloomyandy** [comment]
A similar problem was reported on the Marlin facebook group:
https://www.facebook.com/groups/1049718498464482/permalink/1331365776966418/?__xts__[0]=68.ARC-du0IBlVP7E8a5AnAsNGzotyR6sWgSnenHfwdTBuGYho-6wMizdNqth-O3txP8CLkyBlcqMsea8k7bQ2i2-wG1OoSNWIx_Mf3tESxbNiKo-ClvuvuzylgO-V3I71tOZNRk6E5SND3naS380DwI8jiguLZ6jgysby8xgUlcVQKdxEQX1lR4w&__tn__=-R

There is a possible solution in that thread.

**Comment by Uinden** [comment]
@gloomyandy 
Adding 
```code
  /* power on init. sd card */
  #if ENABLED(SDSUPPORT)
    if (!card.cardOK) card.initsd();
  #endif
```
In `void setup()` of `Marlin_main.cpp` solved the problem. 
Thanks!

**Comment by LemaruX** [comment]
I'll give it a go, thanks. Though not sure that the cause is no SD detect pin as the SD card used to initialise fine before upgrading Marlin. 

If this sorts it though then all good

**Comment by fred2088** [comment]
2.0.x got the same problem that can't init sd on startup, while 1.1.x can init sd correctly on startup

no. init sd from startup 2.0.x, no matter have custom bootscreen or not...
find the problem that the if statement `&& DISABLED(ULTRA_LCD)` disable the `card.init` to run.
```cpp
//  #if ENABLED(SDSUPPORT) && DISABLED(ULTRA_LCD)
  #if ENABLED(SDSUPPORT)
    card.beginautostart();
  #endif
}
```

```
start
echo:Marlin bugfix-2.0.x

echo: Last Updated: 2018-01-20 | Author: (none, default config)
echo:Compiled: Nov  2 2018
echo: Free Memory: 3593  PlannerBufferBytes: 1184
echo:V62 stored settings retrieved (569 bytes; crc 55966)
echo:  G21    ; Units in mm (mm)
echo:  M149 C ; Units in Celsius

echo:Filament settings: Disabled
echo:  M200 D3.00
echo:  M200 D0
echo:Steps per unit:
echo:  M92 X100.00 Y100.00 Z6400.00 E88.16
echo:Maximum feedrates (units/s):
echo:  M203 X800.00 Y800.00 Z2.00 E60.00
echo:Maximum Acceleration (units/s2):
echo:  M201 X1500.00 Y1500.00 Z5.00 E800.00
echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P1500.00 R3000.00 T2000.00
echo:Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
echo:  M205 B20000.00 S0.00 T0.00 X8.00 Y8.00 Z0.40 E5.00
echo:Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:Material heatup parameters:
echo:  M145 S0 H180 B70 F0
echo:  M145 S1 H240 B110 F0
echo:PID settings:
echo:  M301 P22.20 I1.08 D114.00
echo:Filament load/unload lengths:
echo:  M603 L0.00 U100.00
```

**Comment by thinkyhead** [comment]
@fred2088 — Try adding this to the end of the `setup()` function in `Marlin.cpp`:
```cpp
 #if ENABLED(SDSUPPORT) 
  if (!card.cardOK) card.initsd();
 #endif
```

**Comment by billsierer** [comment]
I was running Marlin 1.1.8 and everything work fine I uploaded my firmware to Marlin 1.1 .9 I set my defines and I too am having the exact same issue my SD card is installed I turn on the printer but it says no SD card found but if I go into menu and click initialize SD card it will load just fine why is it not Auto initializing I have all the Define set to what they need to be but it's still not working.  I did not have this issue with Marlin 1.1.8 and I also compared my configuration files and configure advance and everything matches perfectly

**Comment by thinkyhead** [comment]
Try the workaround I posted above and see if it helps.

**Comment by amedranogil** [comment]
Same issue in 1.1.9.
Proposed solution works.
Strange there is no pull request for this...

**Comment by LemaruX** [comment]
Strangely it doesn't work on mine. At least not every time. I often have to eject and reinsert an SD card for it to be recognised

On 28 Dec 2018 22:10, Alejandro Medrano <notifications@github.com> wrote:

Same issue in 1.1.9.
Proposed solution works.
Strange there is no pull request for this...

**Comment by momo42** [comment]
I'm also affected with unmodified Marlin 1.1.9 on Creality Ender 2.
The proposed solution also worked for me.

**Comment by momo42** [comment]
I tested with 1.1.x bugfix release and this bug is persistent!

**Comment by leolimajr** [comment]
Proposed solution also worked for me! I'll create a PR for this.

**Comment by robbycandra** [comment]
My solution is to change the code at the end of setup() at Marlin_main.cpp:

From 

```
#if ENABLED(SDSUPPORT) && DISABLED(ULTRA_LCD)
    card.beginautostart();
  #endif

```
To :

```
#if ENABLED(SDSUPPORT) 
    card.beginautostart();
  #endif
```

**Comment by thinkyhead** [comment]
That helpfully causes the `card.beginautostart()` code to be invoked twice. Once when the LCD is done initializing, and again at the end of `setup()`.

**Comment by merdok** [comment]
Hello,

why this is still not fixed? I had to add the following code on my Ender 3 with the 1.1.5 Mainboard with the latest 1.1.x bugfix to make the sd card init on start:

```
  /* power on init. sd card */
  #if ENABLED(SDSUPPORT)
    if (!card.cardOK) card.initsd();
  #endif
```

**Comment by InsanityAutomation** [comment]
> 
> 
> Hello,
> 
> why this is still not fixed? I had to add the following code on my Ender 3 with the 1.1.5 Mainboard with the latest 1.1.x bugfix to make the sd card init on start:
> 
> ```
>   /* power on init. sd card */
>   #if ENABLED(SDSUPPORT)
>     if (!card.cardOK) card.initsd();
>   #endif
> ```

1.1.x is EOL, try 2.0

**Comment by merdok** [comment]
I guess a lot of people still using the 1.1.x bugfix on the Creality Melzi board, so shouldn't at least this be fixed? I mean there are still fixes coming in to this branch so why not this?

**Comment by nyxaria** [comment]
bump, can this be integrated upstream into 1.1.x? Just because it's EOL doesn't mean it shouldn't be supported for a few years, at least.

**Comment by leolimajr** [comment]
I'm using a fix since long ago on my fork so I created a PR for this so everyone can benefit from it. Credits to @robbycandra.
