### ISSUE TITLE
Kossel Mini and G33

### ISSUE THREAD

**Issue by pyfontan** [MarlinFirmware/Marlin#7171]
I'm trying to upgrade my Kossel Mini from 1.0 to 1.1.

I'm using this Configuration:
https://gist.github.com/pyfontan/27faf57a3908d062595afad79242daf2
based on file present in example_configurations directory, with Marlin branch bugfix-1.1.x

I have an "allen key probe" but i manually deploy it (no mechanism on tower) and use pronterface to connect the printer and send Gcodes.

When i send a G33 code with a Zprobe deployed, i have the following error:
https://gist.github.com/pyfontan/875722734bdbdbade6ed951eb5b130ea
And the head stops at X0 Y0 Z50 with no stow.

When i send a G33 code with a Zprobe not deployed, the head starts:
  - to move at a speed not corresponding to XY_PROBE_SPEED
  - to move vertically along Z tower but never reaches the coordinates specified in Z_PROBE_ALLEN_KEY_DEPLOY_1_[X|Y|Z]
If I deploy manually the probe during this move, the head returns at X0 Y0 Z_MAX and starts to probe correctly (no error) but with no final stow. As previously the head stops at X0 Y0 Z50 but i do not need a M999 to reset the printer.

What can i do ?
Thank you.
Pierre-yves

**Comment by LVD-AC** [comment]
Try the latest version, a lot has changed recently for eccentric probes
