### ISSUE TITLE
G33 and probe_manually?

### ISSUE THREAD

**Issue by dagobertch** [MarlinFirmware/Marlin#7173]
I tried yesterday to calibrate my delta 101Superhero (a modified 101Hero) with G33
If I press the item on LCD or start via G33, nothing happend.
should it work with probe_manually?
Here my config: [https://www.dropbox.com/s/7i97h8tr51928pf/Configuration.h?dl=0](https://www.dropbox.com/s/7i97h8tr51928pf/Configuration.h?dl=0)

**Comment by joris57** [comment]
G33 requires a probe, it won't work with manual probing.

**Comment by thinkyhead** [comment]
Added a sanity check to prevent compiling this combination.

**Comment by LVD-AC** [comment]
See PR #7226 and https://github.com/LVD-AC/Marlin-AC/tree/1.1.3d-AC
