### ISSUE TITLE
#error "LCD_BED_LEVELING requires MESH_BED_LEVELING or PROBE_MANUALLY."

### ISSUE THREAD

**Issue by Nickduino** [MarlinFirmware/Marlin#7176]
When I turn the LCD bed leveling on **with PROBE_MANUALLY turned on as well**, I get a compilation error.

I have to activate MESH_BED_LEVELING **and** PROBE_MANUALLY for it to work.

**Comment by Tannoo** [comment]
The current error is misleading.

`PROBE_MANUALLY` needs one of the following defined:
```
//#define AUTO_BED_LEVELING_3POINT
//#define AUTO_BED_LEVELING_LINEAR
//#define AUTO_BED_LEVELING_BILINEAR
//#define AUTO_BED_LEVELING_UBL
//#define MESH_BED_LEVELING
```

**Comment by Tannoo** [comment]
This is the sanity check:
```
/**
 * LCD_BED_LEVELING requirements
 */
#if ENABLED(LCD_BED_LEVELING)
  #if DISABLED(ULTIPANEL)
    #error "LCD_BED_LEVELING requires an LCD controller."
  #elif DISABLED(MESH_BED_LEVELING) && !(HAS_ABL && ENABLED(PROBE_MANUALLY))
    #error "LCD_BED_LEVELING requires MESH_BED_LEVELING or PROBE_MANUALLY."
  #endif
#endif
```
`!(HAS_ABL && ENABLED(PROBE_MANUALLY))` is what's giving you the error. It's looking for a type of leveling to be enabled also.

**Comment by Nickduino** [comment]
Could it be that the documentation isn't completely clear?
I thought I could do a manual bed leveling (with the bed screws) asking the printer only to park the nozzle at the four corners.

**Comment by Tannoo** [comment]
I do that also, but it's so rare, that I do it manually -- 
`G28` or Auto Home from LCD.
`G1 X10 Y10`, adjust.
`G1 X190 Y10`, adjust.
`G1 X190 Y190`, adjust.
`G1 X10 Y190`, adjust.

I do it that way because setting up bed leveling to do 4 points requires changing the firmware settings accordingly and flashing. Then changing things back for the actual leveling.

**Comment by Tannoo** [comment]
I do use Unified Bed Leveling now. As a lot can be done on-the-fly without changing the firmware.

**Comment by Roxy-3D** [comment]
You can do a partial G29 P1 T U using UBL to help with the physical adjustment of the bed.  The U is for Uneven bed.  It will spread the probe points out as far as possible.  When you have enough points sampled...  You stop it and physically level the bed.   And then do it again until the bed is as level as you can get it.

**Comment by Nickduino** [comment]
> I do it that way because setting up bed leveling to do 4 points requires changing the firmware settings accordingly and flashing. Then changing things back for the actual leveling.

I don't get you.

**Comment by Tannoo** [comment]
Lol

**Comment by thinkyhead** [comment]
I believe the issue in the OP is now patched in `bugfix-1.1.x`.

**Comment by boelle** [comment]
@Nickduino do you still have the problem with latest bugfix 2.0 ?

**Comment by Nickduino** [comment]
Wow, I haven't tried that in quite a while (I've since created a "leveling gcode")

**Comment by disappear123df** [comment]
how did you guys solve it

**Comment by HexiDev** [comment]
idk
