### ISSUE TITLE
Z Movement latest build via controller issue

### ISSUE THREAD

**Issue by pmbroth** [MarlinFirmware/Marlin#7181]
Hello

I noticed with the latest build on my Marlin Gen 1.4 board, with the mkstsft 32, If I select Z to move up or down will not work, Will work with the regular reprap 64128 controller. Rolling back to 2 days ago build works fine.  I always use the latest bugfix11x

**Comment by Andrei-Pozolotin** [comment]
https://github.com/MarlinFirmware/Marlin/issues/7166

**Comment by pmbroth** [comment]
Thank you, did not see that issue logged.

**Comment by Tannoo** [comment]
#7183 fixed it.

**Comment by pmbroth** [comment]
It is fixed, verified!! Great Job!!!
