### ISSUE TITLE
Turn on extruder fan always (i am not using extruder)

### ISSUE THREAD

**Issue by Kondenado** [MarlinFirmware/Marlin#7185]
Dear All

Long history short, for very particular reasons (I am using the 3D printer as a robotic arm, more than a   printer, and I do not have neither the extruder, neither the thermocouple connected to the microcontroller) I need the extruder fan (D9) to be on always on. 

When I connect my laptop and I run the command M106 through the serial connection, the fan works well. But now I want the to start the fan without sending any command, I want it to start automatically.

I have tried to make many things but any of them worked.

- I have tried to set the "auto_fan" starting temperature to -300 (as long as i do not have the thermocouple connected, the temperature value is 0 (M105)). But, it doesn't work. 

- I have also tried to set the D9 output as a controller fan, but it doesn´t work either.

Sometimes some compiling errors appear (you can not set this as a controller fan ...") but i have just disabled the error, as long as i am not using extruder  it should not be a problem.

My configuration
Printer: 3D maker
Controller: Arduino Mega + Ramps 1.4 + Marlin

Thank you very much.

**Comment by martindb** [comment]
Why not just connect your fan to vcc directly?

**Comment by Kondenado** [comment]
Because the fan requires 12 V.

**Comment by martindb** [comment]
So connect it to your 12v power supply.

**Comment by Kondenado** [comment]
Sorry, the fan requires 24 V,

Second, I am concerned about supplying to much current (i will supply 12V and 5A). While I guess that small fans don't require so much (It requires 0.8 W; so between 300-700 mA). I think this might be too much for the fan right? I am not the biggest electronic expert on the world. 

Btw, thank you very much for your kind response.

**Comment by martindb** [comment]
If your fan is 24V, your power supply should be 24v.... D9 outputs same voltage that you put in the 11A input of your RAMPS, just give you the posibility to control it (with M106 Sxxx, M107). If you need just the fan turned on full speed all the time, connect it to 24v in a direct way.

**Comment by Kondenado** [comment]
Thanks! It worked!
