### ISSUE TITLE
Nonlinear Auto Bed Leveling with Delta Printer behaves strange

### ISSUE THREAD

**Issue by Ralfono** [MarlinFirmware/Marlin#7186]
After the nozzle touched the heat bed while Auto Bed Leveling, the printer starts to move upward instead of sideways. The Marlin software is new uploaded and raw. Has anyone ideas?

Here is a video of the problem:

https://youtu.be/t9eKzlZjdjg?t=19s

[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/1112477/Configuration.h.txt)

**Comment by Roxy-3D** [comment]
This is a very old version of Marlin.  You will get much better support (and probably be happier with your printer) if you move to the current version.   https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x
