### ISSUE TITLE
Easy Calibration method to remove concave Delta movements

### ISSUE THREAD

**Issue by radzia2** [MarlinFirmware/Marlin#719]
After moving my printer around, small deformations occur in my printer frame. This means you need to calibrating for DELTA_RADIUS over and over again. (the software doesn't take the small changes in DELTA_RADIUS into account.

The delta code from Johann features an auto leveling code "G29 Z-0.4". With the Z-0.4 part, you can compensate the automatic leveling option with .4 mm ( you put the nozzle .4 mm closer than you would have hard programmed in the arduino code)

It would be nice if there was a comparable feature you could "modify" the DELTA_RADIUS value with Gcode. After moving the printer around from point A to B, you could just add or retract .5mm out of your slicer program to adjust the DELTA_RADIUS without having to reprogram your Arduino board. 

Is this possible guys? I'm a real noob in Arduino programming but thought it might be a useful feature to improve user experience.

Regards,
R-

**Comment by thinkyhead** [comment]
Johann's delta code has been merged, for the most part, including the newest non-linear leveling. Hopefully it is working better now that the code is also using the leveling results during printing.

**Comment by boelle** [comment]
Just going through everything  to see what is solved etc...

Could this one be closed on the grounds that Johann's code has been merged? Also i dont see any new comments from the initial poster..

And in the end how many would this request benefit? for me it still looks like solving a hardware issue with software in the sence that moving the printer will result in hardware not alligned right

**Comment by thinkyhead** [comment]
@boelle During leveling I heard there had still been some curved movements, but that may also be resolved. We'll try to catch that as part of the bed leveling and probing bug dragnet.

**Comment by boelle** [comment]
@radzia2 are you still arround?

**Comment by a4jp-com** [comment]
@radzia2 are you there?

**Comment by linchunguang** [comment]
The book research 3 d printers algorithm

**Comment by clefranc** [comment]
@radzia2 Try this http://clefranc.github.io/Marlin4Delta
@linchunguang You're looking for documentation on Delta kinetics?

**Comment by a4jp-com** [comment]
Nice work @clefranc

**Comment by jbrazio** [comment]
Thank you for your interest making Marlin better.
You should re-open this topic on [MarlinFirmware/MarlinDev](https://github.com/MarlinFirmware/MarlinDev) for proper followup from the development team. We suggest you to use the `MarlinFirmware/Marlin#<topic id>` markdown to link back to this original topic.
