### ISSUE TITLE
Thinky has been quiet...

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#7192]
It is possible we have a new folder and file layout Sunday evening!...

My wish list is:
- Not just an LPC1768 HAL
- I want some (any) 20X4 LCD display to compile clean with the Re-ARM board.

Add your wish list item here!

**Comment by fiveangle** [comment]
- super-efficient realtime PROGMEM compression so 128k boards can run all the cool new marlin features ;) bwahahahahhaa

**Comment by Tannoo** [comment]
All of Marlin working on the Re-Arm.

**Comment by Tannoo** [comment]
Easier form-based configuration of Marlin (mainly for new users).

**Comment by TGMods** [comment]
> All of Marlin working on the Re-Arm.

Especially the LCDs particularly the miniVIKI as I bought one especially for my Re-Arm

**Comment by Tannoo** [comment]
A new `C1 Sx` for remote coffee machine control. ;)

**Comment by p3p** [comment]
@Roxy-3D The only reason the 20x4 displays don't work (I think) is I had to strip out the Arduino Print API from U8glib, (it was the quickest solution to make graphical displays work), It shouldn't be very hard to add back into https://github.com/p3p/u8glib_arm_platformio when I get round to it. I've been away for a bit but I should have time for more work on the LPC1768 HAL next week.

**Comment by thinkyhead** [comment]
I'm on the case at the moment, just scanning issues to see if anything serious needs a patch ahead of doing a quick 1.1.4 release. Then, diving into the current HAL work to make sure I understand it well. The big code re-organization is tomorrow's big half-day task, which I'll probably get a start on tonight.

**Comment by Roxy-3D** [comment]
> I want some (any) 20X4 LCD display to compile clean with the Re-ARM board.

> The only reason the 20x4 displays don't work (I think) is I had to strip out the Arduino Print API from U8glib,

It is OK if the first version of the LPC1768 HAL doesn't support everything.  It already supports the Graphical displays.  It would be good if it supported at least some of the 20x4 displays.

But I have other agendas.   It turns out the place I can put my Re-ARM board has a 20x4 display.  So...  I at least want that to compile.  I can do the debugging if it needs it.  But it would be nice if the 20x4 LCD Displays at least compiled.

If I can get that display to run...  I can start adding to and fixing LPC1768 HAL issues.   The whole trick to getting the 32-Bit boards up and running is getting enough support in place that other people can work on their issues.  We are almost at 'critical mass' for that to happen.
