### ISSUE TITLE
Support: BILINEAR with PROBE_MANUAL "ABL Adjustment" changes ?

### ISSUE THREAD

**Issue by fiveangle** [MarlinFirmware/Marlin#7193]
The [BILINEAR bed leveling docs](http://marlinfw.org/docs/features/auto_bed_leveling.html) appear to be sorely outdated (I will try to fix if I can understand how it works eventually):

> Currently, Marlin doesn’t save the bed leveling results to EEPROM, and it throws away the probe results on G28. So the machine must always do a new G29 after any G28

I've been told this is not true.

[G29 gcode docs](http://marlinfw.org/docs/gcode/G029-abl.html) appear more up-to-date but are incomplete with respect the various options.

In this discussion I am referring to `AUTO_BED_LEVELING_BILINEAR` with `PROBE_MANUALLY`.

Following the steps G28, G29 (with manual probe of 5x5 grid) results come out to ("`<--------`" denoting my questions/comments):

<details><summary>Terminal Output</summary>

```
Recv: Grid probing done.
Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3      4
Recv:  0 -0.772 -0.810 -0.833 -0.843 -0.849
Recv:  1 -0.904 -0.929 -0.970 -0.959 -0.956
Recv:  2 -0.908 -0.929 -0.925 -0.937 -0.968
Recv:  3 -0.876 -0.840 -0.874 -0.889 -0.955
Recv:  4 -0.890 -0.882 -0.899 -0.900 -0.945
Recv: 
Recv: X:152.00 Y:152.00 Z:0.00 E:0.00 Count X:3040 Y:3040 Z:-479
Recv: ok P15 B3
[...]
Send: M500 <--------assumed this saved grid info to EEPROM
Recv: echo:Settings Stored (529 bytes; crc 21334)
Recv: ok P15 B3
[...]
Send: G29 Q <------queried leveling state
Recv:   current_position=(152.00, 152.00, 0.00) : >>> gcode_G29
Recv: Machine Type: Cartesian
Recv: Probe: PROBE_MANUALLY
Recv: Auto Bed Leveling: BILINEAR (enabled) <----shows enabled
Recv: ABL Adjustment Z-0.95 <------------------shows -0.95mm Z adjustment
Recv: Manual G29 idle
Recv: ok P15 B3
[...]
Send: M420 S1
Recv: echo:Bed Leveling On
Recv: echo:Fade Height Off
Recv: ok P15 B3
[...]
Send: G29 T   <------------assumed would output topology report
Recv: ok P15 B3
<-----bot moved to grid position #1 and awaited further instruction - this was unexpected.
<-----Only documentation for G29 T command shows:
<-----
<-----    [T<flag>] - Generate a Bed Topology Report (AUTO_BED_LEVELING_LINEAR)
<-----
<-----But gives no indication what <flag> denotes.  As usage standards aren't used
<-----such as "[ ]" to denote optional arguments, it is unclear what is required here.
<-----
<-----I suspect the parser ignored the "T" without the <flag> argument and interpretted
<-----this as "G29" so began reprobe of grid.
[...]
Send: G28  <---------send autohome in order to exit grid re-probe process
Recv: echo:busy: processing
Recv: X:76.00 Y:76.00 Z:0.00 E:0.00 Count X:1520 Y:1520 Z:0
Recv: ok P15 B3
Send: G29 Q  <----------------queried state again
Recv:   current_position=(76.00, 76.00, 0.00) : >>> gcode_G29
Recv: Machine Type: Cartesian
Recv: Probe: PROBE_MANUALLY
Recv: Auto Bed Leveling: BILINEAR (disabled)  <------ disabled ?  Should I assume G28 disables bed leveling automatically ?
Recv: 
Recv: Manual G29 idle
Recv: ok P15 B3
[...]
Send: M420 S1   <----------------enabled bed leveling again
Recv: echo:Bed Leveling On
Recv: echo:Fade Height Off
Recv: ok P15 B3
[...]
Send: G29 Q
Recv:   current_position=(76.00, 76.00, 0.00) : >>> gcode_G29
Recv: Machine Type: Cartesian
Recv: Probe: PROBE_MANUALLY
Recv: Auto Bed Leveling: BILINEAR (enabled)
Recv: ABL Adjustment Z-0.93  <-----------ABL Adjustment is now changed to +0.02mm
<-----from previous value of -0.93 (Is this expected ???)
Recv: Manual G29 idle
Recv: ok P15 B3
[...]
```
</details>

...

Digging into Marlin_main.cpp, it shows [here](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/Marlin_main.cpp#L4206-L4209):

```
   *  T  Generate a Bed Topology Report. Example: "G29 P5 T" for a detailed report.
   *     This is useful for manual bed leveling and finding flaws in the bed (to
   *     assist with part placement).
```

So it seems that the "topology report" is not reported from presumably stored EEPROM, and is really just "probe all points and report what is observed" which means for manual probing, requires to re-probe all points again.

Is there any method to output the grid that is stored in EEPROM (if it is even stored at all) ?

And is the _ABL Adjustment_ value changing by 0.02mm typical, given the above command sequence ?  If so, can you tell me why (what was done wrong in the above terminal output, if this is WAD).

The goal here (if it isn't evident" is to replace Mesh Bed Leveling with Bed Leveling Bilinear.  Automatic probing of my printer doesn't get a perfect first layer, presumably due to inductive probe repeatability, and inability to probe entire bed due to probe offset.  And no, I cannot run UBL due to the PROGMEM requirements.

Update: and so there is yet a 4th documentation location [here](http://marlinfw.org/docs/configuration/configuration.html#bed-leveling-style) which does add a lot more detail:

> Bed Leveling Style
> Bed Leveling is a standard feature on many 3D printers. It takes the guess-work out of getting a good first layer and good bed adhesion. All forms of bed leveling add G29 Bed Probing, M420 enable/disable, and can save their results to EEPROM with M500. Bravo!
> 
> With Bed Leveling enabled:
> 
> G28 disables bed leveling, but leaves previous leveling data intact.
> G29 automatically or manually probes the bed at various points, measures the bed height, calculates a correction grid or matrix, and turns on leveling compensation. Specific behavior depends on configuration and type of bed leveling.
> M500 saves the bed leveling data to EEPROM. Use M501 to load it, M502 to clear it, and M503 to report it.
> M420 S<bool> can be used to enable/disable bed leveling. For example, M420 S1 must be used after M501 to enable the loaded mesh or matrix, and to re-enable leveling after G28, which disables leveling compensation.

But M503 doesn't report the bed leveling mesh data, only the Z-fade, Z-offset (which I still don't know why it changed) and whether or not it is enabled.

Thanks !

-=dave

**Comment by fiveangle** [comment]
Looking through the code for what seems like forever, it appears there's no way to report the stored probe values with BILINEAR + PROBE_MANUAL so I'm giving up on this and going back to MBL, since without the ability to see the stored values, the feature is too difficult to use because if there is any doubt in what values are stored (like now, my printing is about 1mm above the bed without reason), one needs to reperform a tedious manual probe of every point to (hopefully) ensure they're set correctly (on faith).  I still have no way of knowing that the mesh is stored correctly, other than the conflicting "documention" mentioned above so it could be the mesh isn't stored at all, which also makes this a non-starter to replace MBL.

As I understand it, MBL has the limitation that it retains the bed countour throughout the print (which is what I was trying to get away with by switching to BILINEAR with the Z fade height feature) but it seems it just isn't mature enough to replace MBL at this time (and perhaps never will be, as most people are just using some kind of probe).

**Comment by fiveangle** [comment]
BTW- everywhere I search on the big I'net for info on this, all I find is confusion, and @Roxy-3D suggesting everyone try UBL and "don't look back" - lol

**Comment by thinkyhead** [comment]
This is slightly more up to date. As always, when corrections are needed, please contrib if possible!

http://marlinfw.org/docs/gcode/G029-abl.html

**Comment by thinkyhead** [comment]
> Looking through the code for what seems like forever, it appears there's no way to report the stored probe values with BILINEAR + PROBE_MANUAL

`M420 V` should print them. See http://marlinfw.org/docs/gcode/M420.html

**Comment by fiveangle** [comment]
Yeah, tried that one too, but the Bot reacts as if I sent it G29 without any parameters:

```
Send: G29 V
Recv:   current_position=(38.00, 0.00, 0.00) : >>> gcode_G29
Recv: Machine Type: Cartesian
Recv: Probe: PROBE_MANUALLY
Recv: Auto Bed Leveling: BILINEAR (disabled)
Recv: 
Recv: Save X1 Y0 Z0.00
Recv: ok P15 B3
[...]
Send: G29 V
Recv:   current_position=(76.00, 0.00, 0.00) : >>> gcode_G29
Recv: Machine Type: Cartesian
Recv: Probe: PROBE_MANUALLY
Recv: Auto Bed Leveling: BILINEAR (disabled)
Recv: 
Recv: Save X2 Y0 Z0.00
Recv: ok P15 B3
```

I suspected it may be some FASTER_GCODE_PARSER weirdness, but then when trying with the old parser, it wouldn't compile:

```
In file included from /var/folders/q1/g9l9mqmn319fh27k43yqpy440000gr/T/arduino_build_54543/sketch/Marlin_main.cpp:259:0:
/var/folders/q1/g9l9mqmn319fh27k43yqpy440000gr/T/arduino_build_54543/sketch/gcode.h: In static member function 'static volatile bool GCodeParser::seen(char)':
gcode.h:155: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
       if (b) value_ptr = DECIMAL_SIGNED(p[1]) ? &p[1] : (char*)NULL;
                        ^
Using library U8glib at version 1.19.1 in folder: /Users/speedster/Documents/Arduino/libraries/U8glib 
Using library Wire at version 1.0 in folder: /Applications/Arduino 1.8.2-teensy.app/Contents/Java/hardware/teensy/avr/libraries/Wire 
invalid conversion from 'const char*' to 'char*' [-fpermissive]
```

So I decided I was probably too far off the beaten path and that I should get back home for dinner before sundown ;)

I don't want to be known as "that guy who always finds the broken tedious little things" :)

**Comment by thinkyhead** [comment]
If `G29 V` doesn't report the leveling grid with bilinear, it means the leveling data is bogus and you do need to re-level to generate valid data.

**Comment by thinkyhead** [comment]
> I don't want to be known as "that guy who always finds the broken tedious little things" :)

Honestly, we need exactly what you're doing. ¡Muchas gracias!

**Comment by fiveangle** [comment]
> If G29 V doesn't report the leveling grid with bilinear, it means the leveling data is bogus and you do need to re-level to generate valid data.

It's odd then why G29 S1 succeeds.  If G29 V fails, then G29 S1 should fail as well, no ?

Question: does the FASTER_GCODE_PARSER make it inefficent to throw an error when G29 V finds bogus data ?  If someone sends G29 V, ideally the bot should never interpret that as G29 (start bed levelling procedure) and move to grid point 0,0.  G29 V is a reporting function, not a movement function, so movement is unexpected in this case (I know I did not expect it).

It's unfortunate that the syntax between MBL and BBL-with-manual-probe schemes are so disjointed. I understand how they evolved the way they did, but it makes anyone who used MBL extremely frustrated that up is now down, right is left, the blue dress is now gold :)   I'll try to put some thought into if it can be improved at all.   At a minimum documentation could solve this, but knowing what to document is proving more difficult than I could have imagined.

**Comment by thinkyhead** [comment]
For ABL with Bilinear, read the documentation at http://marlinfw.org/docs/gcode/G029-abl.html — just updated with some additional notes.

When using ABL Bilinear with `PROBE_MANUALLY` you just use `G29` repeatedly — there's no `S` parameter. (MBL does have an `S` parameter.)

**Comment by fiveangle** [comment]
Big help Scott.  I'm sure this will help a lot of people down the road.  I'll try to improve if I find opportunities.  Thanks !

**Comment by fiveangle** [comment]
M420 V doesn't print grid, but is otherwise ignored. V4 does print more info as leveling
Progresses. But no way to validate existing mesh or even view it. The reason this is critical is that one has no way to prevent this from happening (identical GCODE as printed the night before):

![img_5708](https://user-images.githubusercontent.com/2219447/27837576-e7b9b9a8-6099-11e7-82ab-ff3d469a5b23.JPG)

if a relatively technical user can't get BILINEAR working consistently without destroying $100 beds and $20 ultem sheets,  I call it unfortunately broken, but I'm not sure how to fix it. At least I gave it a shot. Others must not have a problem since there isn't much speak of it… oh wait, no, there's actually issues filed nearly every day on confusion around BILINEAR. But I guess if there weren't, Roxy wouldn't have anywhere to pimp her UBL wares ;)
