### ISSUE TITLE
Homing issue on Prusa (Marlin 1.02)

### ISSUE THREAD

**Issue by mandeep255** [MarlinFirmware/Marlin#7195]
I have an issue with Z Homing using inductive sensor. The issue cropped up only when I upgraded to MARLIN 1.02.
The Z homes above the bed more than required, The inductive sensor is triggering perfectly, working perfectly with previous version. It now homes but rises more than required. PL help!

**Comment by Bob-the-Kuhn** [comment]
I'm not sure what you mean by "rises more than required".  

Is it: "In the old software, after G28, G0 Z0 resulted in the nozzle being x mm above the bed but with the new software, after G28, G0 Z0 results in the nozzle being x + y mm above the bed (where y is a positive number)"

Most inductive sensors use a high impedance resistor network to interface to the controller.  The internal pullup can cause problems if it's enabled.  The following will disable the internal pullup on the inductive sensor.  Note that both ZMIN & ZMIN_PROBE have to be disabled.
```
//#define ENDSTOPPULLUPS // Comment this out (using // at the start of the line) to disable the endstop pullup resistors

#if DISABLED(ENDSTOPPULLUPS)
  // fine endstop settings: Individual pullups. will be ignored if ENDSTOPPULLUPS is defined
  #define ENDSTOPPULLUP_XMAX
  #define ENDSTOPPULLUP_YMAX
  #define ENDSTOPPULLUP_ZMAX
  #define ENDSTOPPULLUP_XMIN
  #define ENDSTOPPULLUP_YMIN
  //#define ENDSTOPPULLUP_ZMIN
  //#define ENDSTOPPULLUP_ZMIN_PROBE
#endif
```

**Comment by mandeep255** [comment]
Thanks Bob, 
The sequence of Homing is under
nozzle moves to center of the bed
Extruder moves down till proximity sensor is triggered
The extruder rises up to a certain height , approx 10mm.
The Z probe  axis reads 0 on the Repetier Host
While printing the nozzle prints in the air, ie above  the surface.
Endstoppullup had been disabled since I was using a NPN sensor.

Autolevelling is on.

Thanks and regards

**Comment by Bob-the-Kuhn** [comment]
Please do a` M420 V`, copy the result to a .TXT file and then drop the .TXT file onto your reply.

I expect that you need to adjust your Z_PROBE_OFFSET_FROM_EXTRUDER.  You can use the `M851 Zxxx` to set this offset.  You may need to repeat G29 for the new value to take effect.

Don't forget update the configuration.h file and to do a `M500` command to save the new offset value to EEPROM.

**Comment by mandeep255** [comment]
Thanks Bob, will revert back.

**Comment by mandeep255** [comment]
[420Vresults.txt](https://github.com/MarlinFirmware/Marlin/files/1128046/420Vresults.txt)
The file is uploaded, I performed a G28 then a G29 followed by M420V
regards

**Comment by mandeep255** [comment]
[PrinterVideo.zip](https://github.com/MarlinFirmware/Marlin/files/1128947/PrinterVideo.zip)
Pl also see the att videos, one shows the homing sequence of my printer and second for auto bed levelling, I think the sequence is also incorrect.  regards

**Comment by mandeep255** [comment]
Firmware now used Marlin 1.1.4

**Comment by mandeep255** [comment]
[configH.txt](https://github.com/MarlinFirmware/Marlin/files/1129703/configH.txt)
copy of config.h 
thanks
