### ISSUE TITLE
'CUSTOM_BOOTSCREEN_TIMEOUT' was not declared in this scope

### ISSUE THREAD

**Issue by Bergerac56** [MarlinFirmware/Marlin#7213]
Hello,

The last bugfix of today does not compile correctly for me if I do not add "#define CUSTOM_BOOTSCREEN_TIMEOUT   2500" just after line (13036 lcd_init();) in marlin_main.cpp (not sure it is the best place to add it...)

**Comment by benlye** [comment]
Related to #7211?

**Comment by petrzjunior** [comment]
@Bergerac56  What configuration file are you using? Some of the example ones or custom? Did you add custom booscreen (is `SHOW_CUSTOM_BOOTSCREEN` enabled in your config)?

**Comment by Bergerac56** [comment]
Yes, the "bugfix" version is related to #7211. I use a quite modified configuration.h and configuration_adv.h and have developped a small bootscreen. I have different printers. One is a "Atlas Jacbot" I modified (other motors, hotend adaptation, electronic improvement,etc...) I use this printer for my tests.

When I try a new "bugfix" I compare the modified files with those of the "bugfix" version. And do the adaptations when needed (hoping always not to have missed something ;) )

I attach a zip of the modified files: 
[JacBot OdB.zip](https://github.com/MarlinFirmware/Marlin/files/1117810/JacBot.OdB.zip)

**Comment by petrzjunior** [comment]
I replicated the problem, with newest `bugfix-1.1.x` and any example config using custom Bootscreen. There must be an `#include` problem, pasting `#include "_Bootscreen.h"` in `Marlin_main.cpp` fixes the bug.

**Comment by Bergerac56** [comment]
Yes This is what I did too. I pasted the #include just after the header "lcd_init(). I just made some prints with this release (and the small correction) All seems fine till now

**Comment by thinkyhead** [comment]
If omitted, I'll have it use 2500.

**Comment by petrzjunior** [comment]
#7219 fixed compile error, but editing the _Bootscreen.h TIMOUT does nothing. I guess #includes must be reorganized somehow.

**Comment by Bergerac56** [comment]
You are right. 
I propose another modification of marlin_main.cpp:
Add just after line 259 (#include "gcode.h")

#if ENABLED(SHOW_CUSTOM_BOOTSCREEN)
  #include "_Bootscreen.h"
#endif

This will define the delay with the one included in the _Bootscreen.h.

**Comment by Bergerac56** [comment]
In the last "bugfix" of today (Latest commit df87278 13 hours ago) the LCD problem is still not completely solved. The program compiles but the delay is still  not respected (as already described above).

In order to minimize the modifications, and without beeing sure that it is the best place, I propose to add (marlin_main.cpp: line 13050)
   #include "_Bootscreen.h"

and to drop  (marlin_main.cpp: line 13043 to 13045)
  #ifndef CUSTOM_BOOTSCREEN_TIMEOUT
    #define CUSTOM_BOOTSCREEN_TIMEOUT 2500
  #endif

This way, all is fine at least for me (delay respected, no compilation errors with or without bootscreen)

The new "lcd_init();" would then be:

  lcd_init();
  
  #if ENABLED(SHOW_BOOTSCREEN)
    #if ENABLED(DOGLCD)                           // On DOGM the first bootscreen is already drawn
      #if ENABLED(SHOW_CUSTOM_BOOTSCREEN)
        **#include "_Bootscreen.h"                  // Include custom bootscreen details**
        safe_delay(CUSTOM_BOOTSCREEN_TIMEOUT);    // Custom boot screen pause
        lcd_bootscreen();                         // Show Marlin boot screen
      #endif
      safe_delay(BOOTSCREEN_TIMEOUT);             // Pause
    #elif ENABLED(ULTRA_LCD)
      lcd_bootscreen();
      #if DISABLED(SDSUPPORT)
        lcd_init();
      #endif
    #endif
  #endif

**Comment by Bergerac56** [comment]
Still not definitively solved in the last bugfix ( ef94ddf)

**Comment by Bergerac56** [comment]
Hello Thinkyhead,

Could you please modify lcd_init() as proposed above? 

Thanks a lot
