### ISSUE TITLE
Calibrate Home Feature Request

### ISSUE THREAD

**Issue by bstott** [MarlinFirmware/Marlin#722]
Hello - Great Software! I am enjoying learning about your firmware for the printers.

I'm finishing a Delta Printer now and have not noticed the easyway to calibrate home. Yes, it is not hard BUT - 

Request - Could you implement the following process?

1. Place the print head/nozzle onto the print surface with a piece of paper as the small space (normal process.).
2. Run a command (? Gcode or ???) to Calibrate Home.
3. The machine then takes it's initial/start position as a zero (0) point and goes to Home - The Endstops. And stops.
4. The firmware then registers each axis distance and records this into EEPROM as  the X, Y, Z distances to the print surface center.
Now these values would be used to calculate all actions going forward for the positioning of the print head/nozzle tip.

OR did I miss where this is and how initiated?

Best Regards,

Brian. 
Pittsburgh

**Comment by thinkyhead** [comment]
I think this would be really good. And it should be able to save the results to EEPROM so it's set until… whenever. I would surely use this feature as a complement to a fixed z endstop.

**Comment by thinkyhead** [comment]
@bstott We now have something pretty cool: Manual bed leveling. It moves between a set number of grid points and allows you to record the height at each point. At the end you store the result in EEPROM and it uses the data to compensate, just as with automatic probing.

**Comment by boelle** [comment]
I'm tempted to close this one as there is not much interest shown.... would it be wrong to do so?

**Comment by thinkyhead** [comment]
Mesh Bed Leveling is essentially this, and it works well.
