### ISSUE TITLE
Explicit heat bed enable pin?

### ISSUE THREAD

**Issue by wrouesnel** [MarlinFirmware/Marlin#723]
Several Aluminatus A1 printers have had catastrophic heat bed failures from FETs which failed into an always on situation. In this situation, Marlin can no longer issue any output from the heat bed pin which will actually shutdown the heat bed.

In the interests of good thermal control and safety, it'd be great if a spare pin could be assigned as a "heat bed enable" output, which could be wired to an NO relay to provide emergency control of heat bed output (i.e. Marlin sets temp to 0, relay turns off and cuts power to the FET).

A separate pin is preferable since relays wear out, and a relay switching 17A will wear out quite quickly if simply connected in the bang-bang control mode.

**Comment by boelle** [comment]
I will close this one... The best fix here is a thermal fuse.. doing an explicit pin would only add to the code and it too can fail. you can find thermal fuses in most house hold stuff. A clothes drier have them and a dishwasher too... they pop if it gets to hot and when you have fixed the issue in some cases you just push a small pin to reset it
