### ISSUE TITLE
AUTOLEVELLING WITH INDUCTIVE PROBE , FAULTY

### ISSUE THREAD

**Issue by mandeep255** [MarlinFirmware/Marlin#7239]
I am using Inductive probe for autolevelling with Marlin 1.01 using Grid Method.
Everything functions well, however , the movement of Z Axis is opposite to the incline, that is in case the tilt of bed requires the nozzle to mov down, it moves up.  Any suggestions pl.

**Comment by Tannoo** [comment]
Try [bugfix-1.1.x](https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x) for the latest of possible fixes. This may have already been addressed.

**Comment by mandeep255** [comment]
Tried but the results are same. regards

**Comment by Tannoo** [comment]
Ok. You stated "Autolevel" but did not state which one.

Which one are you having troubles with and have yoou tried any of the others?

**Comment by mandeep255** [comment]
Using Inductive Sensor, Linear Method, regards

**Comment by mandeep255** [comment]
18 mm NPN probe

**Comment by Tannoo** [comment]
Have you tried Bilinear?

**Comment by Tannoo** [comment]
Or better yet, UBL?

**Comment by mandeep255** [comment]
No , none of them

On Jul 9, 2017 15:08, "Tannoo" <notifications@github.com> wrote:

Or netter yet, UBL?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MarlinFirmware/Marlin/issues/7239#issuecomment-313909462>,
or mute the thread

**Comment by mandeep255** [comment]
Will these help?

**Comment by Tannoo** [comment]
Try and see.

**Comment by Tannoo** [comment]
On bugfix-1.1.x.

**Comment by Tannoo** [comment]
I used to run bilinear with no issues. I now run UBL with very little issues.

**Comment by mandeep255** [comment]
Ok will try and revert

**Comment by Tannoo** [comment]
Umm. That would not be a revert. Just an option change. Bugfix-1.1.x is the lastest bugfixes applied to all versions of 1.1.x.

**Comment by mandeep255** [comment]
Ok
