### ISSUE TITLE
[FR] WS2812B leds (NeoPixels)? 

### ISSUE THREAD

**Issue by nesalkiN** [MarlinFirmware/Marlin#7271]
Hello, 

I know that Tanoo (spelling?) had support for the  ws2812b ledstrips and I used that fork with my leds mounted on one of my printers but not anymore because I want to have the latest released Marlin (stable). I would like to use more ws2812b on my other printers so I am wondering. What happened to the efforts to support that kind of leds? Thanks!

**Comment by Tannoo** [comment]
I know I said I would update the one I still use, I've just been busy. Marlin is changing at a very fast pace. It didn't make since to keep rebasing every few days to ensure that it works.

When things settle down a bit after 2.0(?) Is released, I will re-configure and rebase to that and submit another PR.

**Comment by Tannoo** [comment]
What I do have current is in my `current_running` branch.

**Comment by nesalkiN** [comment]
I always used RCBugFix before but because of more frequent releases of stable version I only update when Marlin gets released. Good to hear that it is still being worked on. Thanks!

**Comment by Tannoo** [comment]
So far, I haven't had to do any "work" to it. It works they way it is. And for most calls also. I did have to change how it was being handled during the stepper timeout, but I believe I have that resolved.

**Comment by Tannoo** [comment]
So, currently it is just maintained on my printer for my printer.
Current_running does have other 'features' setup in it. This is a 'backup' of my printer's firmware.

**Comment by Tannoo** [comment]
If you were to run that, you would have to reconfigure the config files for your printer... they are not defaulted like the marlin base.

**Comment by RalphSch** [comment]
Take a look at #7340 ;)
