### ISSUE TITLE
Save 40 bytes of RAM memory...

### ISSUE THREAD

**Issue by Roxy-3D** [MarlinFirmware/Marlin#7274]
In ultralcd.cpp we have the declaration:
```cpp
uint8_t lcd_status_message_level;
char lcd_status_message[3 * (LCD_WIDTH) + 1] = WELCOME_MSG; // worst case is kana with up to 3*LCD_WIDTH+1
```
It would seem...   if the user doesn't have  STATUS_MESSAGE_SCROLLING enabled...  And they are using a western type font we can save 40 bytes of RAM by shrinking the array size.    Kana fonts need the 3x size.   Does anybody know if the Greek and Cyrillic need double byte characters?

**Comment by thinkyhead** [comment]
See if #9545 has it covered.

**Comment by boelle** [comment]
@Roxy-3D did #9545 cover it?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by Roxy-3D** [comment]
Yes...   This is now covered.   And with a good solution.   People with multi-byte fonts can still use them.   And it is only these people that get nicked for the extra memory.

**Comment by boelle** [comment]
@Roxy-3D so maybe close the  issue? if nothing else then just for the sake of not having "fixed" issues on the list :-D
