### ISSUE TITLE
'Simulation Mode' Bug

### ISSUE THREAD

**Issue by BigBox3D** [MarlinFirmware/Marlin#7291]
Running IDEX Dual X-Carriages.

Send movement commands over serial I get the OK back from Marlin but nothing actually moves.

The LCD controls work as expected and I can move the head(s) around. 

If I send a G10 X150 Y100 Z50 F3000 command the LCD updates the position on the LCD but the machine remains motionless. However using the LCD to move the head will immediately move to the position set with the G1 command, plus any changes in position made via the LCD.

If I try to print via Octoprint all the lines are sent, OKs are received and the LCD updates the XYZ positions, but it sits perfectly still.

Same error with both 1.1.4 and 1.1 bugfix.

It is what I would term to be Simulation Mode.

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/1148162/configs.zip)

**Comment by FHeilmann** [comment]
did it ever work with a version of Marlin you compiled yourself?

Seems like a PIN assignment is faulty. Make sure you select the right motherboard.

**Comment by oysteinkrog** [comment]
There is a nasty bug with IDEX/DUAL_X now where it does not work at all.
See https://github.com/MarlinFirmware/Marlin/issues/7050 and https://github.com/MarlinFirmware/Marlin/issues/6956

**Comment by teemuatlut** [comment]
To reproduce:
* Enable DUAL_X_CARRIAGE
* Power up the machine
* On serial send G1 X100

Is there anything else needed to reproduce the problem? No T0/T1 commands needed?
If 1.1.1 works, does 1.1.2? 1.1.3? This would help me track down the specific commit.

You can easily switch through versions with ```git checkout 1.1.2```

**Comment by oysteinkrog** [comment]
I've previously confirmed that 1.1.2 and later do not work.
I'm currently bisecting my way to the commit that introduced the problem, I'll let you know once I have it nailed down.

**Comment by oysteinkrog** [comment]
Ok, 91841d75c9a473e15932bd4589d64ee59efe947e is the commit that introduced the problem.

**Comment by oysteinkrog** [comment]
I've found the bug (easy to spot), will submit a PR.

**Comment by oysteinkrog** [comment]
Hmm, for some reason my merged PR did not correctly close this, please close it now.
