### ISSUE TITLE
Feed rate control has no effect while printing for delta kinematics

### ISSUE THREAD

**Issue by cristiansavaro** [MarlinFirmware/Marlin#7295]
- Marlin version : 1.1.4 / 1.1.5 (haven't verified older 1.1.x versions)
- Description: Feed rate control has no effect while printing
- Expected behaviour: have speed increased or reduced
- Actual behavior: no effect on speed
- Kinematics : delta (others like cartesian & corexy are not affected)
- Steps to reproduce:
  - start printing
  - change feed rate anywhere from 10% to 999% either by sending M220 g-code or through the lcd encoder

[pack.zip](https://github.com/MarlinFirmware/Marlin/files/1150089/pack.zip)

**Comment by cristiansavaro** [comment]
any word on this issue ?

**Comment by kevintong116** [comment]
I also have this problem using bugfix version

**Comment by kevintong116** [comment]
@cristiansavaro have you solve the problem?

**Comment by Roxy-3D** [comment]
Let's be scientific and find the commit that broke the feedrate for Delta's.
