### ISSUE TITLE
[FR] Debug Mode similar to repetier firmware. 

### ISSUE THREAD

**Issue by mmiscool** [MarlinFirmware/Marlin#7299]
Hello,
In the repetier firmware you can enable a debugging mode that constantly sends a wait msg when the machine is doing nothing.

I have a gcode sender program that is part of a larger system and requires the machine send a msg regularly when it is not busy. In repetier firmware it sends "WAIT"

I searched around and was unable to find a similar option in marlin. 

Would it be possible to add such an option or if it is there point me to it?

**Comment by fiveangle** [comment]
Search configuration.h for HOST_KEEPALIVE_FEATURE.  I believe it does what you want, but doublecheck.

**Comment by mmiscool** [comment]
I did try to enable that and looked with a serial terminal. Did not see any thing happening when the printer was idle.

**Comment by p3p** [comment]
HOST_KEEPALIVE_FEATURE is only for keeping the Host notified when running a long command, so its a busy signal rather than idle signal, as far as I know there is no idle keep alive feature available in Marlin.

**Comment by thinkyhead** [comment]
What you're looking for is `NO_TIMEOUTS`. Set to non-zero to get a "wait" message.
