### ISSUE TITLE
Delta with bugfix-1.1.x always halts when printing 1st raft layer

### ISSUE THREAD

**Issue by nomukaiki** [MarlinFirmware/Marlin#7303]
I've always had issues with the 1.1.x even during RC version, but thought it would be fixed with the recent improved Delta math code.

The problem happens **only** during the **1st layer** and printing a **raft** (extrusion is much higher than other layers), **regardless of speed**.
I tested many different scenarios and it is always reproducible.

Here is a short snippet of the log when the printer fails:
```
Send: N257 G1 X-38.630 Y20.397 E31.5717*72
Recv: ok
Send: N258 G1 X-39.074 Y20.205 E31.7619*71
Recv: ok
Send: N259 G1 X-39.749 Y19.761 E32.0795*67
Recv: ok
Send: N260 G1 X-40.162 Y19.345 E32.3094*79
Recv: ok
Send: N261 G1 X-40.625 Y18.627 E32.6454*71
Recv: ok
Send: N262 G1 X-40.770 Y18.286 E32.7909*78
Recv: ok
Send: N263 G1 X40.766 Y18.286 E64.8252*108
Recv: start
```
This is when the halt/restart happens.

Full gcode here:
[Fidget_Cube_2.5cm_-_0.4mm.gcode.zip](https://github.com/MarlinFirmware/Marlin/files/1151063/Fidget_Cube_2.5cm_-_0.4mm.gcode.zip)

And configuration files:
[configuration_files.zip](https://github.com/MarlinFirmware/Marlin/files/1151064/configuration_files.zip)

If I disable the base raft layers, it always prints perfectly fine...

Any suggestions?
Which other logs would be useful to find the issue?

Thank you

**Comment by thinkyhead** [comment]
Reboots occur due to too much CPU usage. Various things can fix this:
- Slow down printing
- Reduce the `DELTA_SEGMENTS_PER_SECOND` value
- Reduce microstepping to 16x or less
