### ISSUE TITLE
Atmega1284p (Melzi 2.0)

### ISSUE THREAD

**Issue by Duck-Development** [MarlinFirmware/Marlin#7306]
Have somebody a running Marlin 1.1 and Arduino 1.8.3 with a Melzi 2.0?

In my case the end switch does not work (z and y ) the z switch works perfect. The stepper DIR is not working, the steppers moves only in  one direction. 

With Arduino 1.0.5 and Repetier 0.91 it is working.

**Comment by p3p** [comment]
This sounds like you have your X and Y end stop logic inverted (Marlin thinks they are triggered)  can you double check you copied those settings across properly.

M119 should respond with something like:

```
Send: M119
Recv: Reporting endstop status
Recv: x_min: open
Recv: x_max: open
Recv: y_min: open
Recv: y_max: open
Recv: z_min: open
Recv: z_max: open
```
