### ISSUE TITLE
Z-probe offset

### ISSUE THREAD

**Issue by tafadafi** [MarlinFirmware/Marlin#7307]
Hi all,
my setup is a Anet A8 with BlTouch Sensor running Marlin and Octoprint. The stability of the z-probe offset is not really good - so i have to do. the paper test befor each print. 
I know want to send M851 z-2.00 and i get 
M851 z-1.86 back what is the last stored value from the LCD / touch pad.
Even if i send M500 and M851 again, the old value is stored. 
In general the EEPROM is enabled - is there a specific entry in the configuration.h needed for the M851 command?!?
Many thanks in advance.

**Comment by flodejr** [comment]
I think your command is not correct,  You should use uppercase Z as in M851 Z-2.00 otherwise the system will just not do anything
