### ISSUE TITLE
SD card not working

### ISSUE THREAD

**Issue by fr33dimension** [MarlinFirmware/Marlin#7309]
I am using Marlin 1.1.4 with a viki LCD. The sd card is not working correctly. The light on the viki is off, The viki displays no card. I can select "no card" and see the card content, and when selecting a file to print, the sd led blinks a few times and goes dark and nothing else happens. The sd content is also displayed in Repetier. When inserting or removing the card, nothing happens.

This is the case since upgrading to 1.1

**Comment by simon-jouet** [comment]
Did you see https://github.com/MarlinFirmware/Marlin/issues/7279? it might be that the pins are incorrect

**Comment by fiveangle** [comment]
and if that isn't relevant, you may want to provide your config*.h zipped up and attached here for review

**Comment by fr33dimension** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1174577/Configuration.zip)
Thanks guys for getting back and sorry for the delay, please see attached and let me know if you see anything.

**Comment by fr33dimension** [comment]
It's pin 82 SD card detect, for the Viki (not viki2), it was on pin 81.

**Comment by thinkyhead** [comment]
We have `miniVIKI` and `LCD_I2C_VIKI` as alternative options, but no plain "Viki" to select from.

The `SD_DETECT_PIN` assigned for most displays in `pins_RAMBO.h` is still 81.

**Comment by boelle** [comment]
@fr33dimension you still have an issue with latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
