### ISSUE TITLE
Auto Level Correct is inverted

### ISSUE THREAD

**Issue by agambini** [MarlinFirmware/Marlin#7313]
Hi Guys
I trying to configure the Auto Level in a Ramps 1.4 
But the auto level looks correct inverted, where nozzle have to up, down , where have to down , up
I tried all the found in internet and nothing resolve this issue
Can you help me ?
I put a picture from the printed test 

Marlin 1.1.X (1.1.3)
![img_20170719_013143](https://user-images.githubusercontent.com/30281580/28351102-197e1796-6c24-11e7-965f-748edced5a92.jpg)

[log-autolevel.txt](https://github.com/MarlinFirmware/Marlin/files/1158027/log-autolevel.txt)

**Comment by cisforcer** [comment]
i   have the same  problem with  1.1.0 RC8 custom by sean liang （https://github.com/sean-liang/Marlin）  which  running in anycubic I3。
this is my pic showing the moving of extruder  ，its looks like correct over

**Comment by cisforcer** [comment]
![222229](https://user-images.githubusercontent.com/30031297/28353484-8f59f862-6c8e-11e7-9b24-e0bc699c6b2f.jpg)

**Comment by FHeilmann** [comment]
> 1.1.0 RC8 custom by sean liang

you probably won't get any support for this issue unless you update to a current version of the firmware (as of now, 1.1.4) and stay away from custom versions (unless their changes are limited to the configuration changes)

**Comment by cisforcer** [comment]
@FHeilmann    i modified  the   firmware  that  given by  the  anycubic i3 （no ABL ）  to  add  AUTO BED LEVEL ， i  had the same problem。

**Comment by agambini** [comment]
Hi guys , after very very long time, the things look work now
I had to desactive EEPROM in firmware and adjust the Z offset in slicer, and all looks good
I'm doing more tests to have sure

**Comment by cisforcer** [comment]
you mean // #define eeprom？
not to use eeproom？

**Comment by agambini** [comment]
yes

**Comment by agambini** [comment]
Unfortunately , after some prints , I realize that not was working proper, the auto bed still not working
I dont know what do more
Have someone some clue  ?
Is possible that probed values no saved ?
Why the inverted values are apllied ?

**Comment by agambini** [comment]
I already using the current version 1.1.4

**Comment by cisforcer** [comment]
see more in #7278

**Comment by Roxy-3D** [comment]
@agambini 
Different people wrote and support different AUTO_BED_LEVELING systems.   Which one are you seeing the problem on?

**Comment by agambini** [comment]
Auto bed level bilinear grid

**Comment by agambini** [comment]
Hi guys
I tried to use manual probe option, and works great
So I don't understand because the automatic option not work, looks the auto option not store the mesh

**Comment by cisforcer** [comment]
manual  probe option works？ so the auto  bed levelling  has bugs we dont konw？

**Comment by agambini** [comment]
Hi
Works, I too not understood
and works very, very well

Em 22 de jul de 2017 10:32 PM, cisforcer <notifications@github.com> escreveu:

manual probe option works？ so the auto bed levelling has bugs we dont konw？
