### ISSUE TITLE
SWITCHING_EXTRUDER/SWITCHING_NOZZLE E1 cannot print if E0 temperature is below safe extrude limit

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#7316]
### Bug Report
- Description: Dondolo like extruder cannot print only with E1 if temperature of E0 is room temperature
- Expected behaviour: Can print E1 with cold E0
- Actual behaviour: E1 cannot print
- Steps to reproduce:
Enable SWITCHING_EXTRUDER with servo and SWITCHING_NOZZLE with same servo (Dondolo like extruder)

**Comment by thinkyhead** [comment]
Presuming now fixed.
