### ISSUE TITLE
[FR] Reprobe and rewipe in G29

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#7325]
The LulzBot printers touch the hotend to washers on the corner of the print bed for auto-leveling. If the nozzle is dirty, Marlin upstream will continue to push into the bed indefinitely, damaging the printer.

I have patched this behavior in our Marlin 1.1.4 branch and implemented a rewipe and reprobe. I would like to begin the discussion about whether this should be implemented upstream.

I can share my solution if there is an interest in doing this.

**Comment by thinkyhead** [comment]
What's your solution?

**Comment by marcio-ao** [comment]
Closing this because the related PR has already been merged https://github.com/MarlinFirmware/Marlin/pull/10450
