### ISSUE TITLE
Add support for macro/sub-programs M98-M99

### ISSUE THREAD

**Issue by Kenzu** [MarlinFirmware/Marlin#733]
Hey

I'am trying to move as much as posible away from the slicer. (so you don't have to remember settings between different slicers)
For that i need macro support. Say I have a start.gcode file on my sdcard, and i run it with M98 start.gcode from my slicer as the only start code.
The start code could the setup max speeds, homing, priming and so on.
It could also be a filament.gcode with esteps and temps for the active filament i my machine. Combine that with firmware retraction and volumetric e step as per http://reprap.org/wiki/Triffid_Hunter's_Calibration_Guide#Optional:_Switch_to_volumetric_E_units I can use the same gcode on all my machines without thinking about temps, filament multiplier, different start codes, retraction and so on.

Thanks

Jesper

**Comment by boelle** [comment]
could this one be closed given that only 2 or so people have shown interest in it ?

**Comment by thinkyhead** [comment]
Currently there is a similar solution, but you still have to have your files already written to the card. You need to set `SD_PROCEDURE_DEPTH` to a value greater than 1, and then you can then use `M23` within a GCode file to start printing another GCode file. When that file is finished printing then reading continues with the next command. You can nest as many files deep as the number set for `SD_PROCEDURE_DEPTH`.

The code exists for this, but I cannot attest that it works. Should be easy to test, however!

**Comment by boelle** [comment]
hmm.. then i will close it at we can reopen if it shows not to work

**Comment by thinkyhead** [comment]
@boelle Using `M23` from within a GCode file seems to be sketchy so far in my testing, where I just put three `M23` commands in a row. The result was that only one of the files was executed. The most likely problem is that all the `M23` commands were going into the ring buffer before the first one was executed. The solution is to block new commands entering the ring buffer after an `M23` until the buffer is empty. (This same approach might be used for any other commands that ought to block, such as `M190` – and could make it easier to implement interruptible commands.)
