### ISSUE TITLE
Odd Printer Behavior

### ISSUE THREAD

**Issue by devekrehbiel** [MarlinFirmware/Marlin#7330]
I upgraded to the latest Marlin about 3-4 weeks ago and also upgraded to Cura 2.6 when the problem in these pictures arrived. It could very well be my inexperience but I am desperately hoping someone here can help. I went to an older Cura but it didnt help. I am running an Anet A8.  
Here are 8 pictures of the problem. What am I doing wrong?
http://devestechnet.com/Images/TopLayerIssue01.jpg
http://devestechnet.com/Images/TopLayerIssue02.jpg
http://devestechnet.com/Images/TopLayerIssue03.jpg
http://devestechnet.com/Images/TopLayerIssue04.jpg
http://devestechnet.com/Images/TopLayerIssue05.jpg
http://devestechnet.com/Images/TopLayerIssue06.jpg
http://devestechnet.com/Images/TopLayerIssue07.jpg
http://devestechnet.com/Images/TopLayerIssue08.jpg
Is it the slicer or the sketch or me?

**Comment by devekrehbiel** [comment]
I upgraded to the latest Marlin about 3-4 weeks ago and also upgraded to Cura 2.6 when the problem in these pictures arrived. It could very well be my inexperience but I am desperately hoping someone here can help. I went to an older Cura but it didnt help. I am running an Anet A8.  
Here are 8 pictures of the problem. What am I doing wrong?
http://devestechnet.com/Images/TopLayerIssue01.jpg
http://devestechnet.com/Images/TopLayerIssue02.jpg
http://devestechnet.com/Images/TopLayerIssue03.jpg
http://devestechnet.com/Images/TopLayerIssue04.jpg
http://devestechnet.com/Images/TopLayerIssue05.jpg
http://devestechnet.com/Images/TopLayerIssue06.jpg
http://devestechnet.com/Images/TopLayerIssue07.jpg
http://devestechnet.com/Images/TopLayerIssue08.jpg
Is it the slicer or the sketch or me?

**Comment by thinkyhead** [comment]
Keep adjusting those slicer settings.
