### ISSUE TITLE
BL-Touch issue -- Nozzle crashes into bed in between prints when G28 issued in start script.

### ISSUE THREAD

**Issue by klcjr89** [MarlinFirmware/Marlin#7333]
I've been having a heck of a time trying to get UBL working reliably the past couple of days, I had several crashes trying to understand the documentation and offsets, but I managed to generate a 15x15 mesh automatically with G29 P1. The link where I got and digested the UBL info is from here: http://marlinfw.org/docs/features/unified_bed_leveling.html

Before I used bilinear leveling before every print, and my gcode start script before each print looked like this:

> M190 S[bed0_temperature] ; Set bed temperature and wait
> G28 ; Home all axes
> G29 ; Auto bed level
> M117 Printing ; Display 'Printing' message

After enabling and activating UBL and saving to EEPROM and from what I gathered from the confusing documentation I changed my start script to this:

> M190 S[bed0_temperature] ; Set bed temperature and wait
> G28 ; Home all axes
> M117 Printing ; Display 'Printing' message

The first print on powerup goes fine, but if I start another print without power cycling then the G28 proceeds to crash into the bed. I assumed from the documentation that once UBL is activated, there's no need for G29 anymore, correct? But this doesn't explain the G28 crashing problem.

Can someone help me figure this out? It may be a good idea to add simple script documentation to the UBL pages because it isn't user friendly by any means. Even with several googlings I came up with not much or any info on the subject.

I hope this post doesn't sound like a rant, I really appreciate all the hard work that has been put into Marlin. :)

Thank you!

**Comment by Roxy-3D** [comment]
What is the purpose of the G29 with no parameters on it?    I don't think that is causing the bad behavior.   But that serves no purpose.

**Comment by klcjr89** [comment]
If you read my post carefully you will see the G29 without parameters was from when I had Bilinear enabled (I probably didn't word that properly in hind-sight) before upgrading to UBL. Do I need M420 S1 before G28 now?

Edit: still got a crash after trying M420 S1 before G28 :(

The doc is confusing because it says: `WARNING: UBL will be active at power up, before any G28`

Do I not need anything in my start script besides G28?

I wonder if the issue is my BLTouch (genuine) causing the crash, the BLTouch datasheet said to have the bottom of the body of the BLTouch set 8.3mm above the nozzle tip, but from what I can see the nozzle barely doesn't crash. My Z offset is extremely low:

`#define Z_PROBE_OFFSET_FROM_EXTRUDER -0.3`

Is the BLTouch datasheet wrong?

Thanks!

**Comment by klcjr89** [comment]
Update: I can confirm it isn't a Marlin issue, it's the BLTouch being way too high, despite reading their documentation.

Sorry for opening this issue :)
