### ISSUE TITLE
Marlin Delta Homing Issue

### ISSUE THREAD

**Issue by yashunandansureka** [MarlinFirmware/Marlin#7335]
Thank you for submitting your feedback to the Marlin project.
Please use one of the templates below to fill out this box.

### Bug Report
- Description: --- The Delta axis hits the endstop and crashes into it. Shows crazy behaviors. 
- Expected behaviour: --- The axis should home on G28
- Actual behaviour: --- The axix go up and crash into the endshop. The Belts start to vibrate crazy.
- Steps to reproduce: G28, Should home correctly
[config.zip](https://github.com/MarlinFirmware/Marlin/files/1164661/config.zip)

**Comment by teemuatlut** [comment]
Verify your endstops are working by using M119.

**Comment by yashunandansureka** [comment]
I tried that. It is all weird. 

I have two deltas. One of them runs older version of marlin and actually works pretty well.

This second delta i recently made, i wanted to put the latest marlin with auto bed leveling.
Somehow it just does not work.

I have noticed that in the new Marlin fw, 1.1.4, there are a lot a settings regarding delta printers that are missing,such as DELTA_CARRIGE_OFFSET, DETLA_EFFECTOR_OFFSET. This also left me a bit puzzled.

**Comment by RATT88** [comment]
Yes. This is what is happening. I can rectify it temporarily in repetier host by hitting all home and then setting home. I thought it was sorted but when I came back to it the next day (and didn't go through repetier) and tried to just print from sd card the problem returned. It's as if it's defaulting to something buried in the firmware code.

**Comment by RATT88** [comment]
Also ran m119 and verified that all switches are working.

**Comment by yashunandansureka** [comment]
Yeah, some times it works, some times it doesn't.
I'm thinking of changing the wiring of the end-stops and the end-stops too.

Will keep ya'll posted.

**Comment by yashunandansureka** [comment]
Okay, Update.

The situation seems to be solved. I changed the endstop wiring. 

The z and x axis edstops were problematic but now they seem to work fine. The x axis is a little but moody sometimes but as of now it seems ok.

**Comment by RATT88** [comment]
Cool. I might try this. How exactly did you change the wiring?

**Comment by yashunandansureka** [comment]
I changed the wires that were going from the endstops to the Ramps.

**Comment by ScanmanIR** [comment]
I believe that I have a similar problem on a Hatchbox Alpha Delta printer. My Z Axis hits the stop at the home position and continues to run with the belt shaking until we turn it off.  I am not too familiar with coding, but I come from an electronics background.  I have family that can code.  What kind of diagnostics can I run to check out the system?

**Comment by yashunandansureka** [comment]
Hi,

Try changing the wires that connect the endstop. I hope that works.

BTW, sending M119 to the printer will give you an echo of which endstop is triggered and which is not, you can use it to see if the endstops work properly or not.
