### ISSUE TITLE
Acceleration issue

### ISSUE THREAD

**Issue by oribotic** [MarlinFirmware/Marlin#7337]
------------------------------------------------------------
### Bug Report
- Description: G1 Acceleration for XYZ works only when E is NOT included in the command
- Expected behaviour: G1 Acceleration for XYZ should work with or without E in the command
- Actual behaviour:  G1 Acceleration is not obeyed, ie. zero acceleration (instantaneous change) occurs for movements that include E.  default acceleration settings XYZ should work with or without E in the command

- Special note:
This is a custom large format printer 1000x1000 bed, its in testing phase and we found this strange behaviour with acceleration not being applied for moves with extrusion.

- Steps to reproduce:
UBL is enabled
15 point grid is used (maximum setting) as the printer bed is 1000x1000mm
UBL grid data is captured and appears to be working ok.

G28
G1 Z5 ;; lift off the bed
; GCODE WITHOUT E - acceleration is ok.
G1 X278.857 Y83.815 F3000
G1 X279.422 Y83.815 
G1 X278.575 Y84.662 
G1 X278.575 Y85.228
G1 X279.988 Y83.815 

; GCODE WITHOUT E - acceleration is not ok - direction changes are instantanous.
G1 X278.857 Y83.815 E0.0035 F3000
G1 X279.422 Y83.815 E0.0049
G1 X278.575 Y84.662 E0.0105
G1 X278.575 Y85.228 E0.0049
G1 X279.988 Y83.815 E0.0174
G1 X280.554 Y83.815 E0.0049

I was able to correct this behaviour by sending: 
M201 E10000
setting the acceleration of the E axis, the XY axes then showed normal damping effects of acceleration. 

We experimented with various acceleration values, none of which changed the behaviour to normal. Only by using M201 E10000, did we see a change to the expected behaviour. Previous usage of this command only set the values we wanted to change i.e M201 X100 Y100. The default values from the firmware were not applied for XY until a value for E was provided. 

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/1166068/Archive.zip)

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.

**Comment by thinkyhead** [comment]
```cpp
/**
 * M204: Set Accelerations in units/sec^2 (M204 P1200 R3000 T3000)
 *
 *    P = Printing moves
 *    R = Retract only (no X, Y, Z) moves
 *    T = Travel (non printing) moves
 */
```
Marlin has three acceleration settings: Printing moves, E-only moves, and Travel-only moves.
