### ISSUE TITLE
[FR] Add an example for RAMPS board

### ISSUE THREAD

**Issue by bryonbaker** [MarlinFirmware/Marlin#7344]
There is no example for RAMPS and a RepRapDiscount Smart Controller.
I have one on a branch ready to push if this feature is accepted.

**Comment by fiveangle** [comment]
Isn't this simply defining RAMPS board, then uncommenting RepRapDiscount Smart Controller define ?  If a user is compiling Marlin (instead of installing pre-compiled from somewhere else) they would be expected to understand how to enable/disable features in Configuration.h so I'm not sure what the value add here is ?

**Comment by Bergerac56** [comment]
I agree. Except a RAMPS board and the LCD, there are a lot of parameters dependent from the stepper motors, the endstops switches and the Z probe, to take only some examples.

If you want just to try and learn, you can first, as fiveangle suggests, enable the RAMPS board and RepRapDiscount Smart Controller and use the per default parameters. BUT you will have to be carefull. The way the motors will react (rotation, speed,...) and the endstops will be... what they are per default... and could damage the printer mechanic. So a finger on the power switch.

For a printer I modified some time ago (without knowing exactly the initial caracteristics), I proceeded motor per motor (disconnecting the others), endstop per endstop to assess first the correct behavior of all the axes and the nozzle. Then I inputed the values of the build "chamber" and calculated the correct numbers for the steps, the extrusion etc...

It is a long, minutious and  interesting task and helps a lot to understand the caracteristics of marlin. 

Ohh BTW: Never forget to "restore failsafe" and "save settings" (in the "control area) after each reflash of the firmware. If not, your new parameters will not be applied or saved after power off. You could spend time trying to adjust thinks... without adjusting them ;)

Good luck

**Comment by fiveangle** [comment]
@bryonbaker - so did we misunderstand your suggestion, or do you think this should be closed ?

**Comment by bryonbaker** [comment]
Hi,
No, I think you understood the question; but maybe not the value of it for people who are new to the platform. :-)
I struggled getting the display to work with my RAMPS board and there are numerous threads with the same challenge. That is because the configuration option is actually not apparent. That is captured in Issue 7301 that I raised and subsequently closed. Reading through it it appears at first read that ULTRA_LCD is all you need to define. (In fact in a prior Marlin release that is all I needed to get it to work.)
So all I am suggesting is that we provide a configuration.h for a RAMPS board that makes it clear you also need to configure the controller (in my case REPRAP_DISCOUNT_SMART_CONTROLLER). Obvious to you; not so obvious to people getting started.
There are other examples in the example_configurations folder with similarly simple config examples - I just thought this might help someone. You can close this if you want though.
Regards
Bryon

**Comment by fiveangle** [comment]
I think you misunderstood the response: certainly an example could be created that takes the default Marlin code and changes only 2 characters:

`//#define REPRAP_DISCOUNT_SMART_CONTROLLER`

to 

`#define REPRAP_DISCOUNT_SMART_CONTROLLER`

But this does not help probably 99% of RAMPS users configure their printer.  The need to understand how to confiure Marlin using the existing Config*.h files is really the minimum level of entry.  If users are less savvy than that, it is not likely that they have built thier own printer so are not likely attempting to compile/install Marlin from source.

Further, even a simple search engine query of natural language "configure marlin for ramps 1.4 with lcd" comes up with a first page full of answers that are far more useful than the above change.

It's unfortunate that occasionally there is a user who struggles with the process, but all we can do is try to improve to prevent these things, and I don't see how adding another configuration example will accomplish that.

That's not to say there isn't other opportunities to improve.  Based on your experience, if you think the display section of Configuration.h needs some improvement, please submit a PR with your suggestion.  I could envision a "_These are general display features (20x4 text, and U8glib graphics) so are normally incldued automatically by selecting a specific display, so are not normally selected here_" addition, or something even simpler.  This would be far more likely to prevent users from falling into the same trap as you did than some languishing config exmample that nobody looks at, in my opinion.

There is a big desire to make configuration simpler such as @akaJes's #6722, Scott's own https://github.com/thinkyhead/MarlinConfigurator and so don't think everyone doesn't feel your pain ! :)  It's just that yet another ignored configuration example doesn't probably solve much of it :/
