### ISSUE TITLE
How Marlin interpolate trajectories

### ISSUE THREAD

**Issue by NervenCid** [MarlinFirmware/Marlin#7346]
Hello:

I Beg your pardon, but i'm researching about Marlin firmware for my master thesis, and i wonder how marlin makes tajectory interpolation, what algorithm uses... if it is cubic or LSBP polinomials...

Do you have recommended speeds and accelerations? i'm new on this and i still trying to research something in order to apply my limited knowledge into robotics into this field...

Thank you

**Comment by Grogyan** [comment]
What area is your masters in, may I ask?

**Comment by NervenCid** [comment]
Hello @Grogyan : 

I'm making my master degree in industrial automation, and i'm making my thesis about 3D printing, in fact this is my project:

http://reprap.org/wiki/UNAL_FDM

I hope to release all documentation soon, but i'm working now in theoretical work know, i'm re doing all calculus and mathematical stuff again in order to give more theorital strenght to the final report, and i'm making some simulations about speeds, and trajectories in order to calculate dynamic model.

**Comment by Grogyan** [comment]
@NervenCid Those last photos you have used are from the Darwin G1 printer.  
That machine is currently in my room awaiting refurbishment.

Personally, IMO you probably need to do more physics papers.

In your OP the answer is in the Planner.cpp file

**Comment by Roxy-3D** [comment]
> In your OP the answer is in the Planner.cpp file

Or from another perspective...   GRBL is the foundation for Marlin's simultanious movements.  bengler.no/grbl   

> i'm re doing all calculus and mathematical stuff again in order to give more theorital strenght to the final report, 

There is plenty of room to optimize the bed leveling area too.   And the automatic self calibration of the different axis of movement (whether Cartesian or Delta or Scara).

**Comment by NervenCid** [comment]
Yep.... @Grogyan 

I'm using a template, i hope into having more time for editing the wiki, and change the pictures... the entire project is under my responsability, and i don't have time even to learn git and upload all here :(... Sadly i don't have any more time, and i even integrate web services via octoprint...

@Roxy-3D since you mention, i'm planning to use the estra stepper (i'm using r
RAMPS 1.4) in order to implement a transfer system for automatizate part extraction, i don't know if the recent version of marlin, allows to use E2 for another utilities apart of second extruder

I will upload the changes to github if i learn to use Git :(

**Comment by thinkyhead** [comment]
> trajectory interpolation, what algorithm uses

Hi @NervenCid,

Marlin uses a simple Bresenham algorithm at the stepper steps level to interpolate its moves. This allows all steppers to arrive at the same point at the same time, while they each do exactly the number of steps needed, using only integer addition and subtraction.

As you can probably guess, in this algorithm, for each linear move we set a threshold (**T**) equal to the largest number of steps that any individual stepper does. The stepper with the most steps also determines how often the stepper interrupt will occur. Each stepper has a counter (initialized to **T / 2**). On each iteration of the loop, each stepper's total number of steps (i.e., "addend") is subtracted from its counter. Each time the counter goes below zero, a step is done and the threshold (**T**) is added to the counter.

As you know, with Bresenham, the dimension with the most steps uses an addend of **T**, so it will step every time. All other steppers end up stepping in proportion to that threshold.

> Do you have recommended speeds and accelerations?

These depend on your mechanical system. See the example configurations for the ranges of values typically used.

> In your OP the answer is in the Planner.cpp file

Read through the `Stepper::isr` method in `stepper.cpp` to see how the Bresenham step counters and steps are handled. As for the varying rate of stepping, acceleration and deceleration are pre-determined in the planner using the various "trapezoid" methods before moves are given to the stepper ISR.
