### ISSUE TITLE
Manual Mesh Bed Leveling Not Saving pts??

### ISSUE THREAD

**Issue by Moostemaster** [MarlinFirmware/Marlin#7361]
Hey everyone, i am completely new to 3d printing and finished assembling by repRapGuru Prusa i3 mk2 about a week ago. At first using repRapGuru's version of Marlin, things where printing fine without too much issue but after i was continually having bed leveling problems, i decided to upgrade to the true marlin firmware and look into the manual mesh bed leveling via my lcd panel. Although i can access the option through the panel and begin manually probing, when i look at the feedback through repetier host, it seems to just be reading back all points values as just being zero and ultimately causing no change to my prints. So basically it would read back x:0 Y:0 Z:0 instead of the point value and the individual z offset for each point. So does anyone know what could be the possible issues or if i happen to be doing things wrong? Any help is greatly appreciated, i just want to finally have a functional 3d printer.

This is basically all i get in the command log after probing 9 points:
13:07:39.306 : echo:enqueueing "G28"
13:07:49.569 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
13:13:12.231 : X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0

interesting thing i just noticed is that when i start a print, bed leveling: ON, disappears from the prepare menu

**Comment by Moostemaster** [comment]
I would love to give manual mesh bed leveling a try via g-code instead of through my lcd panel as a possible fix but i dont know the actual code to do it, if someone can enlighten me with the code, that would be great as well. many thanks in advance

**Comment by fiveangle** [comment]
https://github.com/MarlinFirmware/Marlin/wiki/Mesh-Bed-Leveling

**Comment by chanddan** [comment]
@fiveangle isn't mesh bed levelling default in the easyconfig? Not sure how this helps?
