### ISSUE TITLE
Any way we getting this ridiculously important feature to marlin?

### ISSUE THREAD

**Issue by batata004** [MarlinFirmware/Marlin#7366]
Hi,

Today I stumbled accross this new feature of PRUSA:

https://www.facebook.com/PrusaResearch/videos/1208374315899553/

I got amazed how it corrects its XY axis and make a rectangle a really rectangle (with 90 degrees sides).

Maybe we could place 4 small metal circles in the bed and make the inductive sensor see them. It would be a beggining not needing to buy a whole new bed

**Comment by Grogyan** [comment]
Skewness correction has been discussed before.
I believe Marlin is now on a feature freeze right now, while the HAL is done to enable 32 bit board support

**Comment by batata004** [comment]
Thanks man! I will close the thread.

**Comment by thinkyhead** [comment]
#8204
