### ISSUE TITLE
Home on Z MAX with Bed Gantry, Z Probe cycle move Gantry to Z Min

### ISSUE THREAD

**Issue by ConniesZA** [MarlinFirmware/Marlin#7367]
I am converting an CubeX ( Bed Gantry on Z) to an open source printer. I installed a Ramps 1.4 with LCD and changed some of the End Stops. I did the configuration to a point where I have everything working, somewhat. 

The printer home is Z at MAX, Y at MAX and X at Min. G28 Homes all Axis, 100% . M48 test starts but homes the Z Axis to Z Min and starts the Probe Bump process. 

I changed various entries with luck.

**Comment by thinkyhead** [comment]
Presuming solved.
