### ISSUE TITLE
on my Rambo v1.3 board when i comment out #define AUTO_BED_LEVELING_BILINEAR i get the following error, any ideas ?  pasting "SWITCH_ENABLED_" and ">>" does not give a valid preprocessing token   -    as for the  #define ENDSTOPPULLUP_ZMIN   #define ENDSTOPPULLUP_ZMIN_PROBE i did try commenting one out and then the other but no different either way

### ISSUE THREAD

**Issue by stefi01** [MarlinFirmware/Marlin#7370]
```

------------------------------------------------------------
### Bug Report
- Description: ---wont compile
- Expected behaviour: ---to compile
- Actual behaviour: ---sod all


-----------------------------------------------------------

**Comment by stefi01** [comment]
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/1182813/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/1182814/Configuration.txt)

**Comment by stefi01** [comment]
files uploaded

**Comment by stefi01** [comment]
fixed it, no worries

**Comment by amacgregor** [comment]
What was it ?

**Comment by stefi01** [comment]
i cant remember even though i should have

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
