### ISSUE TITLE
Z Homing Failed

### ISSUE THREAD

**Issue by KheeSiangPey** [MarlinFirmware/Marlin#7371]
### Bug Report
 - Description: 
	I have a BLTouch Sensor mounted on my DIY 3D Printer running with Megatronics V3.0 (Motherboard). My printer has never worked properly with different issues on each version of firmware I used. I am currently using the latest marlin firmware this time (Version 1.1.4) and Repetier Host for the Slicer. 

- Expected behaviour: 
	I have successful experience before using the older firmware (which got another issue), this is what I expected when homing. After I sent homing (G28) command to the firmware, it should home both X, Y axis, then move the print head toward the centre of the bed. After that, it should lower down the BLTouch probe pin and slowly move downward (Z axis) toward the bed to home Z axis.

- Actual behaviour: 
	After homing both X, Y axis (move to the end-stops), it moved the print-head toward the centre of the bed. After that, it stopped, the BLTouch probe was not lowered down. This is what I got in the log:

> 20:03:28.933 : echo:N15 G28*39
> 20:03:28.933 : >>> gcode_G28
> 20:03:28.933 : Machine Type: Cartesian
> 20:03:28.933 : Probe: BLTOUCH
> 20:03:28.934 : Probe Offset X:0 Y:-30 Z:0.00 (Middle-Front & Same Z as Nozzle)
> 20:03:28.934 : Auto Bed Leveling: BILINEAR (disabled)
> 20:03:28.934 : current_position=(0.00, 0.00, 0.00) : setup_for_endstop_or_probe_move
> 20:03:28.934 : > endstops.enable(true)
> 20:03:28.934 : Raise Z (before homing) to 5.00
> 20:03:28.934 : >>> do_blocking_move_to(0.00, 0.00, 5.00)
> 20:03:30.222 : <<< do_blocking_move_to
> 20:03:30.222 : >>> homeaxis(X)
> 20:03:30.223 : Home 1 Fast:
> 20:03:30.223 : >>> do_homing_move(X, -375.00, 0.00)
> 20:03:30.223 : current_position=(0.00, 0.00, 5.00) : sync_plan_position
> 20:03:30.894 : echo:busy: processing
> 20:03:32.892 : echo:busy: processing
> 20:03:34.891 : echo:busy: processing
> 20:03:36.889 : echo:busy: processing
> 20:03:38.903 : echo:busy: processing
> 20:03:40.902 : echo:busy: processing
> 20:03:42.900 : echo:busy: processing
> 20:03:44.898 : echo:busy: processing
> 20:03:46.598 : <<< do_homing_move(X)
> 20:03:46.598 : Move Away:
> 20:03:46.598 : >>> do_homing_move(X, 5.00, 0.00)
> 20:03:46.598 : current_position=(0.00, 0.00, 5.00) : sync_plan_position
> 20:03:46.902 : echo:busy: processing
> 20:03:46.936 : T:31.72 /0.00 B:32.15 /0.00 @:0 B@:0
> 20:03:47.205 : <<< do_homing_move(X)
> 20:03:47.205 : Home 2 Slow:
> 20:03:47.226 : >>> do_homing_move(X, -10.00, 25.00)
> 20:03:47.226 : current_position=(0.00, 0.00, 5.00) : sync_plan_position
> 20:03:47.418 : <<< do_homing_move(X)
> 20:03:47.476 : >>> set_axis_is_at_home(X)
> 20:03:47.476 : For X axis:
> 20:03:47.476 : home_offset = 0.00
> 20:03:47.476 : position_shift = 0.00
> 20:03:47.476 : soft_endstop_min = 0.00
> 20:03:47.476 : soft_endstop_max = 250.00
> 20:03:47.476 : > home_offset[X] = 0.00
> 20:03:47.476 : current_position=(0.00, 0.00, 5.00) :
> 20:03:47.476 : <<< set_axis_is_at_home(X)
> 20:03:47.476 : current_position=(0.00, 0.00, 5.00) : sync_plan_position
> 20:03:47.476 : current_position=(0.00, 0.00, 5.00) : > AFTER set_axis_is_at_home
> 20:03:47.476 : <<< homeaxis(X)
> 20:03:47.476 : current_position=(0.00, 0.00, 5.00) : > homeX
> 20:03:47.476 : >>> homeaxis(Y)
> 20:03:47.477 : Home 1 Fast:
> 20:03:47.477 : >>> do_homing_move(Y, 325.50, 0.00)
> 20:03:47.477 : current_position=(0.00, 0.00, 5.00) : sync_plan_position
> 20:03:48.915 : echo:busy: processing
> 20:03:49.009 : <<< do_homing_move(Y)
> 20:03:49.009 : Move Away:
> 20:03:49.009 : >>> do_homing_move(Y, -5.00, 0.00)
> 20:03:49.009 : current_position=(0.00, 0.00, 5.00) : sync_plan_position
> 20:03:49.135 : <<< do_homing_move(Y)
> 20:03:49.135 : Home 2 Slow:
> 20:03:49.135 : >>> do_homing_move(Y, 10.00, 25.00)
> 20:03:49.135 : current_position=(0.00, 0.00, 5.00) : sync_plan_position
> 20:03:49.310 : <<< do_homing_move(Y)
> 20:03:49.310 : >>> set_axis_is_at_home(Y)
> 20:03:49.373 : For Y axis:
> 20:03:49.373 : home_offset = 0.00
> 20:03:49.373 : position_shift = 0.00
> 20:03:49.373 : soft_endstop_min = 0.00
> 20:03:49.373 : soft_endstop_max = 217.00
> 20:03:49.373 : > home_offset[Y] = 0.00
> 20:03:49.373 : current_position=(0.00, 217.00, 5.00) :
> 20:03:49.373 : <<< set_axis_is_at_home(Y)
> 20:03:49.373 : current_position=(0.00, 217.00, 5.00) : sync_plan_position
> 20:03:49.373 : current_position=(0.00, 217.00, 5.00) : > AFTER set_axis_is_at_home
> 20:03:49.373 : <<< homeaxis(Y)
> 20:03:49.373 : current_position=(0.00, 217.00, 5.00) : > homeY
> 20:03:49.373 : Z_SAFE_HOMING >>>
> 20:03:49.373 : current_position=(0.00, 217.00, 5.00) : sync_plan_position
> 20:03:49.374 : destination=(125.00, 138.00, 5.00) : Z_SAFE_HOMING
> 20:03:49.374 : >>> do_blocking_move_to(125.00, 138.00, 5.00)
> 20:03:50.972 : echo:busy: processing
< 20:03:55.073 : Printer reset detected - initalizing
> 20:03:55.073 : start
> 20:03:55.073 : echo:Marlin 1.1.4
> 20:03:55.073 : echo: Last Updated: 2017-07-04 12:00 | Author: Eu-ET Invention
> 20:03:55.073 : Compiled: Jul 28 2017

The printer reset itself and I have completely no idea on why it behaved like this. It reset itself every time before homing the Z-axis. Please help me> Thank you
- Steps to reproduce:
	G28 and wait

[My Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1182957/My.Configuration.zip)

**Comment by thinkyhead** [comment]
Presuming solved.
