### ISSUE TITLE
enqueue_and_echo_commands_P calls drain_injected_commands_P only once.

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#7374]
When using "enqueue_and_echo_commands_P", it is possible to enqueue multiple commands by separating them with '\n'. However, enqueue_and_echo_commands_P() only calls drain_injected_commands_P() once, so only the first command gets executed in immediately, the others do not.

Since drain_injected_commands_P() returns true if more commands remain, would it make sense to make a loop, i.e:
```cpp
void enqueue_and_echo_commands_P(const char * const pgcode) {
  injected_commands_P = pgcode;
  while(drain_injected_commands_P()); // execute commands asap (when possible)
}
```
My use case is that I want to be able to execute a sequence of GCODE commands after G28 completes, and so I added a  enqueue_and_echo_commands_P("G92 Z5.5\nG0 Z16") to the end of gcode_G28. However, what happens is that G92 Z5.5 happens immediately, but G0 Z16 only happens after a few other commands from the buffer are executed. I believe the above loop would fix the issue, but I do not know whether it would break anything else.

**Comment by thinkyhead** [comment]
That would work.

**Comment by thinkyhead** [comment]
That could lead to a lockup. It would be vital to break out of that `while` loop in the event that the queue is full. Otherwise it will never return, because we rely on the main loop for commands to go out of the queue.

**Comment by marcio-ao** [comment]
Closing this because it sounds like the current behavior is there for a reason. Also, execute_commands_immediate_P introduced in PR https://github.com/MarlinFirmware/Marlin/pull/10450 is a far better alternative to enqueue_and_echo_commands_P.
