### ISSUE TITLE
where did "change filament" go?

### ISSUE THREAD

**Issue by thomllama** [MarlinFirmware/Marlin#7383]
### Bug Report?
- Description:  Change Filament no longer in LCD menu
- Expected behaviour:  be able to change filament using LCD/click wheel
- Actual behaviour: none
- Steps to reproduce:
  - Do this
  - Do that

Recently updated Marlin and just went to use the "change filament" option in the LCD menu and it is gone. :(     Or is it now something I have to turn on?  I got to say the newest Config h file is a tad confusing in it's order/layout.  had a hard time matching settings from my old version to new version.

**Comment by Hypertoken** [comment]
If you've enabled "ADVANCED_PAUSE_FEATURE" in the firmware, then you must also have pre-heated your hot end before you can do "Change Filament"

**Comment by thomllama** [comment]
can't find any setting anywhere with that title.. did a complete search after looking using textWrangler and nothing comes up.  looked both ConfigH and Adv. config H

**Comment by Roxy-3D** [comment]
Its at the bottom of the 'Tune' menu.   It will be the very last item in that list.
```cpp
  /**
   *
   * "Tune" submenu
   *
   */
  void lcd_tune_menu() {
    START_MENU();
...
    //
    // Change filament
    //
    #if ENABLED(ADVANCED_PAUSE_FEATURE)
      if (!thermalManager.tooColdToExtrude(active_extruder))
        MENU_ITEM(function, MSG_FILAMENTCHANGE, lcd_enqueue_filament_change);
    #endif

    END_MENU();
  }
```
But it will only be there if ADVANCED_PAUSE_FEATURE is turned on and the active extruder is not too cold.

https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Configuration_adv.h#L787

**Comment by Hypertoken** [comment]
@thomllama If you aren't up to date on firmware, the "ADVANCED_PAUSE_FEATURE" has recently been renamed from  "FILAMENT_CHANGE_FEATURE" 

EDIT: I believe its because there is added functionality to this feature beyond changing filament!
