### ISSUE TITLE
Probing with BLTouch and incorrect delta height can damage printer

### ISSUE THREAD

**Issue by tcm0116** [MarlinFirmware/Marlin#7387]
When performing `G33` or `G29` on a delta printer with a BLTouch that has a delta height that is too large, the print nozzle can be pressed into the bed, causing damage to the diagonal rods. Looking into this issue, I've determined the following contributing factors:

1. The BLTouch isn't deployed until after the Z height is lowered to Z_CLEARANCE_BETWEEN_PROBES.
2. If the probe is triggered during the fast movement down to Z_CLEARANCE_BETWEEN_PROBES, the printer immediately starts the slow downward movement without moving up to give the probe clearance to reset. 
3. The slow portion of the probe sequence can set the destination Z position to large negative numbers (I've seen -100).

Having the delta height set incorrectly is obviously user error, but it seems to me that there are some things that could be done in the firmware to help prevent damage to the printer in the event that the delta height is set incorrectly (or of there's some obstruction on the bed, such as someone accidentally starting a new print before clearing the bed). Here are a few things I've been looking at:

1. Handle BLTouch more like a traditional servo mounted probe. Currently, the BLTouch is deployed and stowed in `do_probe_move` which is why it's not deployed until the Z height is already lowered to Z_CLEARANCE_BETWEEN_PROBES. If control of the BLTouch is moved to `set_probe_deployed`, then it will be deployed prior to moving down. The one caveat is that the `stow` parameter to `probe_pt` will need to be always set to *true* for the BLTouch. 
2. If the probe is triggered during the fast initial movement in `run_z_probe`, it should be handled like PROBE_DOUBLE_TOUCH, and raise the Z height before lowering slowly.
3. The probe event should fail if the probe is not triggered within a few mm of where it was expected to be triggered. This will prevent the printer from driving the probe to an unreachable position significantly below the bed in the event of a failure of the probe. One issue with this is that it will break `G33 P1`'s ability to find the bed if the delta height is to small, but I think conservatism is better here since breaking people's printers is no good. I think this can be somewhat alleviated be manually setting the Z home offset to get the total delta height closer to reality before running `G33 P1`, and we could also add the ability to adjust the height via the Delta Configuration menu as well. 

I've started making progress on implementing these changes, but I'd like to get a discussion started to make sure I'm not missing something in my thinking. Please comment if you have any thoughts or suggestions on this.

**Comment by thinkyhead** [comment]
> The BLTouch isn't deployed until after the Z height is lowered to `Z_CLEARANCE_BETWEEN_PROBES`.

Important because BLTouch errors if it doesn't trigger within a short time after deployment.

I believe latest probing code is more conservative about the downward move to avoid the main issue.
