### ISSUE TITLE
Z height doesn't update from repetier printer settings 

### ISSUE THREAD

**Issue by dylanpil** [MarlinFirmware/Marlin#7391]
----
### Bug Report
- Description: Z height of LCD not updating to what setting in the repetier printer settings
- Expected behaviour: When setting my Home Z in repetier i expect the limit to be the same on the 3d printer LCD
- Actual behaviour: The Z limit on the printer LCD is what has been set in configuration.h

Issue: I have to set my Max home height in configuration.h and upload firmware to effect the z height max 

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1189619/Configuration.zip)

------------------------------------------------------------

**Comment by fiveangle** [comment]
is there someone here who speaks Repetier who can translate ? ;)

unless you can explain better, or show that Repetier is sending the correct gcode to "set max home height" but Marlin is not honoring it, i'm not quite understanding how this is a Marlin issue.

can you explain more about what you mean by "Z limit", "Max home height" and "z height max" and how they are related ?
