### ISSUE TITLE
[FR] Move hot nozzle if printer stalls

### ISSUE THREAD

**Issue by bipsendk** [MarlinFirmware/Marlin#7407]
It would be nice, if some sort of watchdog functionality could be implemented on gcode received via the serial port.

The firmware knows the printing area of the printer via the configuration.
So it should be possible to calculate timeout value if the printer is moving form coordinate x,y to w,z in speed S mm/sec (so that the firmware knows when to expect the next gcode command). Then multiply the value by e.g. 5 (just to be on the safe side).
Another option culd for example be if nothing was received on the serial port for x minutes when one or more heaters are enabled.

The watchdog functionality could be enabled/disabled by custom gcode commands - so that the watchdog can be enabled in the start gcode after the heated bed and the nozzle reaches the specified temperatures, and disabled when the print job finishes; or the watchdog will not start before the first command is sent to move the print head/extrude material.

The reason for the request: If using a computer (PC/RaspBerry Pi with octoPrint) suddenly stops sending gcode commands, the nozzle will stop at the last known end-position - and will stay there with heat enabled on both the bed and the hotend. If a watchdog timer could intercept such an issue, it would be possible to raise the nozzle e.f. 10mm (if not colliding with the upper limit of the printer), and disable heating on the heated bed and the hotend.

**Comment by ellensp** [comment]
Firmware has HOTEND_IDLE_TIMEOUT, effectively same thing.
