### ISSUE TITLE
RepRap Discount Full Graphic Display blank, printer works fine

### ISSUE THREAD

**Issue by discojon** [MarlinFirmware/Marlin#7408]
### Bug Report
- Description: Configured and flashed latest 2.0 Bugfix.  Printer works fine using Octoprint as controller but the display stays blank.  Rotary Encoder sounds like it is working (beeps).  LCD works fine on previous FW (1.1)

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/1194976/Archive.zip)

**Comment by fiveangle** [comment]
2.0 is not released and there are countless known issues.  Please use the stable or bugfix 1.1 branch (and close this issue for now).  Once 2.0 is out and you still ahve a problem, please resubmit.

Thx !

-=dave
