### ISSUE TITLE
Can't compile bugfix-1.1 without SDSUPPORT since #7397

### ISSUE THREAD

**Issue by benlye** [MarlinFirmware/Marlin#7411]
### Compile Error
When I compile without `SDSUPPORT` I get an error:
```
sketch\ultralcd.cpp: In function 'void lcd_prepare_menu()':

ultralcd.cpp:2417: error: 'card' was not declared in this scope

       if (!thermalManager.tooColdToExtrude(active_extruder) && !card.sdprinting)

                                                                 ^

exit status 1
'card' was not declared in this scope
```
I believe this commit breaks things:
https://github.com/MarlinFirmware/Marlin/commit/6ef71c3d5f5ef727cfb6c0cd997f7d2a7fa6a2fe

Because it doesn't check if `SDSUPPORT` is enabled or disabled.  Reverting the change gets things compiling.

**Comment by FHeilmann** [comment]
also found this one. Suggested fix @ #7412
