### ISSUE TITLE
Function "get_sdcard_commands" will cause wdt reset when print sdcard file

### ISSUE THREAD

**Issue by MS1987** [MarlinFirmware/Marlin#7449]
------------------------------------------------------------
### Bug Report
- Description: ---
  When I print a gcode file (from sdcard) which has plenty of comment lines continuously, it causes the board reset.

- Analasy: ---
  As the watchdog was enabled, in the function "get_sdcard_commands()" there is code as following:
`  if (!sd_count) continue; // skip empty lines (and comment lines)`
 This "continue" will cause long time in the get command loop when the gcode file has enougth comment  lines to  consume.
- Solve: ---
  Replace the "continue" above with "return"

- reproduce:
  Use the gcode file to test.

[test.zip](https://github.com/MarlinFirmware/Marlin/files/1204049/test.zip)

------------------------------------------------------------

**Comment by iosonopersia** [comment]
Hi @MS1987 
> Replace the "continue" above with "return"

I suggest to edit code as follows:

```
  // skip empty lines (and comment lines)
  if (!sd_count) {
      #if ENABLED(USE_WATCHDOG)
          watchdog_reset();
      #endif
      continue;
  }
```

Do you think this would work?

**Comment by MS1987** [comment]
Yes, I think so!

2017-08-08 


LMS




发件人：Simone Persiani <notifications@github.com>
发送时间：2017-08-08 17:46
主题：Re: [MarlinFirmware/Marlin] Function "get_sdcard_commands" will cause wdt reset when print sdcard file (#7449)
收件人："MarlinFirmware/Marlin"<Marlin@noreply.github.com>
抄送："MS1987"<lms228@163.com>,"Mention"<mention@noreply.github.com>

Hi @MS1987
Replace the "continue" above with "return"
I suggest to edit code as follows:
  // skip empty lines (and comment lines)
  if (!sd_count) {
      #if ENABLED(USE_WATCHDOG)
          watchdog_reset();
      #endif
      continue;
  }

Do you think this would work?

**Comment by MS1987** [comment]
But it will still block the other operation( like button operation and lcd refresh). So I  think skip out will be better. What do you think?

2017-08-08 


李满森
Menson
广州谦辉信息科技有限公司
广州市荔湾区东沙工业区荷景南路23号C栋407-408房
Phone：020-81653576
Fax： 020-81653576
Mobil：13794310267
www.makerbase.com.cn



发件人："lms228"<lms228@163.com>
发送时间：2017-08-08 17:47
主题：Re: Re: [MarlinFirmware/Marlin] Function "get_sdcard_commands" will cause wdt reset when print sdcard file (#7449)
收件人："MarlinFirmware/Marlin"<reply@reply.github.com>
抄送：

Yes, I think so!

2017-08-08 


LMS




发件人：Simone Persiani <notifications@github.com>
发送时间：2017-08-08 17:46
主题：Re: [MarlinFirmware/Marlin] Function "get_sdcard_commands" will cause wdt reset when print sdcard file (#7449)
收件人："MarlinFirmware/Marlin"<Marlin@noreply.github.com>
抄送："MS1987"<lms228@163.com>,"Mention"<mention@noreply.github.com>

Hi @MS1987
Replace the "continue" above with "return"
I suggest to edit code as follows:
  // skip empty lines (and comment lines)
  if (!sd_count) {
      #if ENABLED(USE_WATCHDOG)
          watchdog_reset();
      #endif
      continue;
  }

Do you think this would work?

**Comment by MS1987** [comment]
But it will still block the other operation( like button operation and lcd refresh). So I  think skip out will be better. What do you think?

**Comment by MS1987** [comment]
@iosonopersia, I agree that your method would prevent the wdt reboot. But it will still block the other operation( like button operation and lcd refresh). So I think skip out will be better. What do you think?

**Comment by iosonopersia** [comment]
Hi @MS1987,
I thought about it and I think your approach would be better than mine. We should prepare a PR for that.

That behaviour should be used both in get_sdcard_commands() and in get_serial_commands().

I add that in those functions, the cycle continues also if MAX_CMD_SIZE is reached. If that happens, those functions continue to read chars until they find a \n or a \r char. So if someone sends a very long string without \n and \r, the printer will also get stuck for a while, until those EOL characters are found. I'm wondering if we could exit the cycle in that case too.

**Comment by thinkyhead** [comment]
Patch will be merged shortly.

**Comment by thinkyhead** [comment]
> if someone sends a very long string without \n and \r, the printer will also get stuck for a while

Less worried about this.
