### ISSUE TITLE
MINIMUM_STEPPER_PULSE issue

### ISSUE THREAD

**Issue by mvsmaker** [MarlinFirmware/Marlin#7461]
Hey. Faced with a very unpleasant bug in version 1.1.4 - when changing the parameter MINIMUM_STEPPER_PULSE> 0, the marlin starts do resets at an random place in the gcode. And it does not depend on the source of the gcode. If the parameter is set equal to 30 ms, then reset takes place on the first lines of gcode.
    The thing is that I use tb6600 and they need a longer pulse, otherwise there are shifts in microsteps. And here this parameter solves the problem but leads to random reboots. Help me pls.

[configs here](https://drive.google.com/file/d/0B6qdCJhpoRvKai1WRVFqQjc1TDQ/view?usp=sharing)

**Comment by thinkyhead** [comment]
Presuming this is now fixed.
