### ISSUE TITLE
Text too long in Italian (Temperature menu)

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#7462]
In a system with 2 hotends and the heated bed when you enter temperature menu some line are too long to be completely read.

I think then replacing "Preriscalda PLA"/"Preriscalda ABS" with "Prerisc.PLA"/"Prerisc.ABS" maybe will solve

**Comment by Kaibob2** [comment]
Can you make a PR to solve this?

**Comment by GMagician** [comment]
I never used github and I'll make a mess if I try to use it.
At the moment my printer is "down" and I don't remember exatly which messages are too long

**Comment by GMagician** [comment]
Pull request done
