### ISSUE TITLE
[FR] Allow change of Baud Rate at runtime

### ISSUE THREAD

**Issue by mperdue** [MarlinFirmware/Marlin#7463]
Is it possible to select the baud rate from the menu somewhere? If not, is that something that can be added? I use different computers to control the printers and they don't all support the same baud rates. I'd hate to have to set things to the lowest common denominator.

**Comment by Vertabreak** [comment]
kinda old this one but this is a feature now.
// Add M575 G-code to change the baud rate
#define BAUD_RATE_GCODE
@boelle think this one is safe to close.
