### ISSUE TITLE
[FR] how to enable Z goes down a little distance after the printing finish?

### ISSUE THREAD

**Issue by hackqiang** [MarlinFirmware/Marlin#7465]
### Feature Request
As I remember, in the old version of Marlin(0.9), the Z will go down for a little distance after the printing finish.
But in v1.1, the Z won't move after the printing finish. So the Nozzle and the model are connected.
Is there any configure items for enable this feature?
( my machine is CoreXY)
thanks!

**Comment by klcjr89** [comment]
Just change your ending script to move the axes where you want them. Or use the nozzle park feature gcode, `G27` , after enabling it in the firmware. :)

**Comment by RalphSch** [comment]
The behavior after finishing the print job is part of the gcodes which are generated by the slicer.

**Comment by hackqiang** [comment]
I see the G27 docs: http://marlinfw.org/docs/gcode/G027.html
but I still confused: in the config:
`P0  (Default) If Z is below park Z raise the nozzle.`
`#define NOZZLE_PARK_POINT { (X_MIN_POS + 10), (Y_MAX_POS - 10), 20 }`
what does the "20" meaning?
If I add the `G27` in my .gcode file, after finish the printing, Z will go down for 20mm?

**Comment by FHeilmann** [comment]
the 20 here means if the nozzle is below 20mm it will be raised to 20mm, otherwise the nozzle will simply move away for `G27 P0`. The behavior you want (always move up) can be achieved using `G27 P2`

If you don't want to use G27 simply paste:

```
G91
G0 Z+5
G90
```
at the end of your g-code. This will raise the nozzle by 5mm, no matter which Z it is currently at.

**Comment by fiveangle** [comment]
[removed inaccurate information]

**Comment by teemuatlut** [comment]
By default G27 will not crush your print as it will only raise the nozzle. You can force the Z destination with P1 parameter however.

OP can use G27 P2 to raise the nozzle (or in his case lower the bed) and park the nozzle at point XY.

[[doc]](http://marlinfw.org/docs/gcode/G027.html)

**Comment by fiveangle** [comment]
i should learn not to post so early in the morning ;)

**Comment by hackqiang** [comment]
thanks all, I will enable the G27 in firmware and add below G code in the end of .gcode:
`G27 P2`
