### ISSUE TITLE
ADVANCED PAUSE  compilation error

### ISSUE THREAD

**Issue by michu556** [MarlinFirmware/Marlin#7466]
Hello i have compilation error

Arduino:1.6.7 (Windows 7), Płytka:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch\MarlinConfig.h:39:0,

                 from E:\MEGAsync\Marlin-RC\Marlin-1.1.x.1\Marlin\Marlin.ino:31:

SanityCheck.h:323: error: #error "ADVANCED_PAUSE_FEATURE currently requires an LCD controller."

     #error "ADVANCED_PAUSE_FEATURE currently requires an LCD controller."

      ^

exit status 1
#error "ADVANCED_PAUSE_FEATURE currently requires an LCD controller."

This is pure marlin 1.1.4 with option enabled

Configuration.h
#define FILAMENT_RUNOUT_SENSOR
Configuration_adv.h
#define ADVANCED_PAUSE_FEATURE

  help

**Comment by FHeilmann** [comment]
The error message gives you all the information you need about this error:

`ADVANCED_PAUSE_FEATURE` can only be used with an LCD display 

so you need to either enable one LCD variant in the config or disable `ADVANCED_PAUSE_FEATURE`

**Comment by michu556** [comment]
LCD is on.  Does it not work with LCD 2004?
#define DISPLAY_CHARSET_HD44780 JAPANESE
#define ULTRA_LCD   // Character based
//#define DOGLCD      // Full graphics display
#define SDSUPPORT

**Comment by fiveangle** [comment]
I think we need to take ULTRA_LCD and DOGLCD out of Configuration.h because this keeps coming up.

```
#if ENABLED(ADVANCED_PAUSE_FEATURE)
  #if DISABLED(NEWPANEL)
    #error "ADVANCED_PAUSE_FEATURE currently requires an LCD controller."
```

NEWPANEL is supposed to be set by controllers with a display.  For LCD 2004 you should select reprap smart controller.

**Comment by FHeilmann** [comment]
You also need a controller type, not just an LCD type. As @fiveangle mentioned uncomment `#define REPRAP_DISCOUNT_SMART_CONTROLLER` if you have a 2-line character LCD or `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` if you have a full graphic lcd

**Comment by Roxy-3D** [comment]
> uncomment #define REPRAP_DISCOUNT_SMART_CONTROLLER if you have a 2-line character LCD or

I have a 20x4 LCD on my Folger Tech.   This works for that size also.

**Comment by michu556** [comment]
Thank you very much for the prompt and reliable help. Everything works ;)
And i for two // i lost 8 hours hehe

**Comment by fiveangle** [comment]
@michu556 - please close this if it worked for you

**Comment by rouhit110** [comment]
Hi friends
I have exactly the same problem
 #error "ADVANCED_PAUSE_FEATURE currently requires an LCD controller."
I recently installed a filament runout sensor  and I made the settings that were needed
I use MKS tft 2.8 display and MKS Gen 1.4 and Arduino 1.6.13
@fiveangle 
@Roxy-3D 

http://s9.picofile.com/d/8348489734/0f28a0a4-41f0-4766-8993-22e55104dd34/Configuration.h Configuration.h
http://s8.picofile.com/d/8348489784/2f44c1a0-34ac-4c48-8691-43519b3be9c8/Configuration_adv.h Configuration_adv

Please help me dears
Thanks...

**Comment by michu556** [comment]
Hi
this error is caused by not selecting the screen in the marlin
settings. you must delete 2 //  appropriate screen in the settings
Regard
M.

czw., 10.01.2019, 11:29: rouhit110 <notifications@github.com> napisał(a):

**Comment by rouhit110** [comment]
Thanks dear @michu556 but i uncomment and select #define DOGLCD in configuration.h. 
I did not notice closing the thread. Excuse me
I created a new topic to solve this problem
