### ISSUE TITLE
[FR] Allow redefinition of FIL_RUNOUT_PIN and PS_ON_PIN

### ISSUE THREAD

**Issue by paulr4** [MarlinFirmware/Marlin#7473]
Hi, can I request #ifndef conditions around the definitions of FIL_RUNOUT_PIN and PS_ON_PIN in pins_RAMPS.h? It would be useful to be able to change from the defaults in config.h without having to modify the board definition. Thanks!

**Comment by thinkyhead** [comment]
Done!
