### ISSUE TITLE
Problem offset anet A8

### ISSUE THREAD

**Issue by funaro13** [MarlinFirmware/Marlin#7478]
Hi, I am here to ask for help from you, I am having adjustment problem in the displacement of my anet a8 capacitive sensor LJC18A3-HZ / BX connected directly to the board, the problem is the following of the calibration procedure With M851Z0, M500, G28, G1X110 Y110 correct Gap, G92. Z0, when I run the command G30 X110 Y110, the offset values of the Z axis are never equal and are with a very large variation, eg first command G30 offset 1.30 second command G30 1.38 and therefore it is different each time, I already checked the Z axis bars all ok, please help me
Paulo

**Comment by benlye** [comment]
I suspect you have your probe connected to the 5V endstop pins?  If so, you might want to try one of the various wiring options to power it with 12V.  These probes are quite unreliable when driven from 5V.

To confirm that the probe is the problem enable `Z_MIN_PROBE_REPEATABILITY_TEST` in configuration.h and use `M48` to test your probe.

**Comment by benlye** [comment]
Also, capacitive probes can be affected by the current running through the bed so you may like to try enabling `PROBING_HEATERS_OFF` (or just probing with the bed heater disabled).

**Comment by funaro13** [comment]
How do I enable this command to delete #define and put enable ??

**Comment by benlye** [comment]
Delete the slashes (`//`) at the start of the line, so it begins `#define `.

**Comment by funaro13** [comment]
ok

**Comment by funaro13** [comment]
I used the M48 command during an impression and it appeared
![img_20170810_232149](https://user-images.githubusercontent.com/30848864/29199434-67027780-7e23-11e7-8f2f-decf8ae72984.jpg)
![img_20170810_232329](https://user-images.githubusercontent.com/30848864/29199466-8fb54748-7e23-11e7-867b-9f400dfe0566.jpg)

**Comment by benlye** [comment]
You don't put M48 in your print code.  

You need to connect to the printer with some kind of serial host - the Arduino IDE has one, or you can use Pronterface or Octoprint - and use a command like `M48 X110 Y110 P10 V3` to do 10 probes in the middle of the bed.  You will get output telling you the variation between the probes.

**Comment by benlye** [comment]
Also, which branch of Marlin did you download and install?

**Comment by funaro13** [comment]
1.1.4

**Comment by funaro13** [comment]
Look at the result, I do not understand anything.
![img_20170811_120301](https://user-images.githubusercontent.com/30848864/29219222-d3dfc3b6-7e8d-11e7-8202-86fac611506d.jpg)
![img_20170811_120414](https://user-images.githubusercontent.com/30848864/29219223-d3e1f71c-7e8d-11e7-84cb-7ef9fa0a2ef1.jpg)

**Comment by Roxy-3D** [comment]
a standard deviation of .0039 mm is actually very good.   You should check that number in a few places on the bed.  (Especially near the edges)       But compared to the typical layer height of .2 or .3 mm, you won't have any problems due to non-repeatability of the probe.

**Comment by funaro13** [comment]
Ok, the sensor is working normal ???

**Comment by funaro13** [comment]
I tried to print a single piece at 0.12mm I could not get the nozzle scraped on the table and the filaments did not come out, the sensor should not check this difference between the Z0 point and the nozzle of the extruder and fix those differences ???

**Comment by funaro13** [comment]
?????

**Comment by thinkyhead** [comment]
Presuming solved.
