### ISSUE TITLE
[FR] Scroll filenames in menu if too long for one line

### ISSUE THREAD

**Issue by ReneHezser** [MarlinFirmware/Marlin#7482]
### Feature Request
Filenames that are long are cut. That makes it hard to decide which file to print from the SD card.
My suggestion is to scroll filenames, if they are too long to be displayed.

**Comment by Roxy-3D** [comment]
Agreed....

**Comment by marcio-ao** [comment]
I already put in a pull request for this #7637

**Comment by ReneHezser** [comment]
@marcio-ao Great. Thank you.
Will it work with a 20x4 display? In the pull request "graphical LCD" is mentioned...

**Comment by marcio-ao** [comment]
@ReneHezser: No, but it could easily be adapted to work with it. The "lcd_implementation_drawmenu_sd" in "ultralcd_impl_HD44780.h" would need to have a few modifications done, similar to the modification I made to "_drawmenu_sd" in "ultralcd_impl_DOGM.h". I don't have one of those displays to test, so I guess someone else would have to do this.

**Comment by marcio-ao** [comment]
@ReneHezser: I updated my pull request with changes to HD44780, but I was not able to test since I don't have compatible hardware. Would you be able to test for me?

**Comment by ReneHezser** [comment]
@marcio-ao Thanks. I can test it. But probably not before next week.

**Comment by ReneHezser** [comment]
Finally I found some time to test your work. I've uploaded a video [here](https://1drv.ms/v/s!AipoXl75Rt3kgYgEZPN1pzPhv7j7vg).
It kind of works. At least partially. In the video you can see what I mean.

**Comment by marcio-ao** [comment]
@ReneHezser: Thanks for posting the video! @Phr3d13 said he would take a look at it once Marlin 2.0 stabilized. This particular fix might end up being a team effort :)

**Comment by Phr3d13** [comment]
This can be closed now, right?

**Comment by ReneHezser** [comment]
Can it be associated two Marlin 2? Or is it on the Roadmap somewhere? I just don't want it to get lost.

**Comment by Phr3d13** [comment]
As of the latest bugfix-1.1.x, this feature is implemented

**Comment by ReneHezser** [comment]
I see. The referenced pull request (7637) contains some additional information.
So I guess closing this FR is OK. Thanks for the work.
