### ISSUE TITLE
Move Axis via Menu freezes until move completed

### ISSUE THREAD

**Issue by ZhuDaHai** [MarlinFirmware/Marlin#7492]
### Bug Report
Marlin 1.1.4
- Description: Select Move Axis from menu (Z, Y, or Y) and 1mm move. Turn the knob to move and the knob becomes ineffective until the move has completed.
- Expected behaviour: Previous version would allow continues movement settings via the knob while the movement was being executed on the selected axis. 
- Actual behaviour: When you turn the knob to move the axis, the input halts while the axis is actually moving. Thus locking you out from moving the axis further until the current move is completed. 
Its an annoying time-wasting bug that was not present in previous versions of Marlin.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1220205/Configuration.zip)

**Comment by Roxy-3D** [comment]
I'm working in the bugfix-2.0.0 branch with the 32-bit stuff.  I'm seeing some issues with respect to very short moves and I know it has something to do with nested interrupts and the head and tail pointer not being fully 'volatile'.     This kind of feels like it is related.

These issues may all be related to each other:
https://github.com/MarlinFirmware/Marlin/pull/7390
https://github.com/MarlinFirmware/Marlin/issues/7491
https://github.com/MarlinFirmware/Marlin/issues/7493

**Comment by ZhuDaHai** [comment]
Ok. Thanks for the info.
FYI: I'm using Marlin 1.1.4 on an Arduino/Genuino Mega or Mega 260 style 8bit board.

**Comment by Roxy-3D** [comment]
These types of problems always are difficult.   But with everybody aware of the issue and the possible cross correlation, we probably will figure it out 'relatively quickly'. 

I'm not a Git expert.   But if somebody with good Git skills has a few minutes, it would be very good to know what changes have been made to the interrupt handlers (and vectors and setup code) in the last month.    That might narrow the search and help us find the issue quicker.

**Comment by thinkyhead** [comment]
Please check the latest `bugfix-1.1.x` branch and see if the problem still exists. We're focusing more attention on the LCD menus lately, so this is a good time to address it.

**Comment by boelle** [comment]
@ZhuDaHai Please check the latest `bugfix-2.0` branch and see if the problem still exists. We're focusing more attention on the LCD menus lately, so this is a good time to address it.

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by Phr3d13** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
