### ISSUE TITLE
sensor no trigger

### ISSUE THREAD

**Issue by echadow** [MarlinFirmware/Marlin#7499]
hi in old versión i no have problem but in 1.1.4 no work, 
npn sensor y try m119 and never work inverted o no

**Comment by echadow** [comment]
Solved, the sensor was connected by a diode and not with the 2 resistors I changed the way to connect it and everything works correc
![screen shot 2014-11-23 at 23 53 16](https://user-images.githubusercontent.com/19215497/29289268-b6447f7e-8133-11e7-8f91-1327f8e79bfd.png)
tly

**Comment by fiveangle** [comment]
please close if you're all good

**Comment by echadow** [comment]
Ok sorry. 
Is my first time here
