### ISSUE TITLE
Setting LCD contrast doesn't affect Full Graphic Display.

### ISSUE THREAD

**Issue by MatixYo** [MarlinFirmware/Marlin#751]
I can't set contrast on RepRapDiscount FULL GRAPHIC Smart Controller using "LCD contrast" option in menu. It should be fixed if possible or removed.

**Comment by thinkyhead** [comment]
@MatixYo Does that graphical controller have a little potentiometer on the board for setting the contrast? I'm trying to determine which displays can have their contrast set by software, and which cannot.

**Comment by Blue-Marlin** [comment]
@thinkyhead 
a. Search for `U8GLIB_` in `dogm_lcd_implementation.h`
b. grep for `U8G_DEV_MSG_CONTRAST` in u8glibs `utility` folder.
c. search for corresponding filenames.

==> 

```
u8glib                        hardware
no  U8GLIB_ST7920_128X64_RRD  REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER no
yes U8GLIB_NHD_C12864         MAKRPANEL yes, VIKI2 yes, miniVIKI yes,
yes U8GLIB_LM6059             ELB_FULL_GRAPHIC_CONTROLLER yes,
no  U8GLIB_SSD1306_128X64     U8GLIB_SSD1306 no,
yes U8GLIB_MINI12864          MINIPANEL no,
yes U8GLIB_DOGM128            ? ?
```

==>

```
#define`HAS_CONTRAST ( ENABLED(MAKRPANEL) || ENABLED(VIKI2) || ENABLED(miniVIKI) || ENABLED(ELB_FULL_GRAPHIC_CONTROLLER) )
```

u8glib now scales for all hardware from 0-255 to the value the hardware needs.

**Comment by MatixYo** [comment]
@thinkyhead It does have.

**Comment by thinkyhead** [comment]
Thanks, I just want to be able to state in the documentation that…

> if your controller doesn't support setting your contrast with the LCD menu item, then you should be able to set the contrast using the potentiometer on the controller board. In some cases, a board may have a fixed resistor instead of a potentiometer. The resistor can be replaced with a different ohm resistor to set a new contrast, or a variable resistor for adjustable contrast.

Probably this stuff is already covered pretty well in the RepRap wiki.
