### ISSUE TITLE
Marlin Hangs or Restarts @ random times

### ISSUE THREAD

**Issue by nLoom** [MarlinFirmware/Marlin#7522]
### Bug Report
- Description: Printer Halts or Restarts mid print (Firmware Version 1.1.4)
- Expected behaviour: Finish printing :)
- Actual behaviour: Printer restarts or halts after sometime into printing, time is random, sometimes around 10 min, other times around 30 or 40 minutes, on some prints it finishes even with longer times.
- Steps to reproduce:
  - Not sure
  - Not sure

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1229577/Configuration.zip)
------------------------------------------------------------

**Comment by Tannoo** [comment]
I would tend to believe there is a short somewhere.
Try moving the nozzle to various points while monitoring the the 5V.
If nothing there, I would turn on the heaters and do the same thing but monitor the 12V.
If either of those are shorting, the board will shut down.
