### ISSUE TITLE
Compile error after 'Implement SERVO_DELAY as array' integration

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#7528]
A bed integration has been done from my code to definitive.
I had removed
> undef SERVO_DELAY
> #define SERVO_DELAY 50 (now is #define SERVO_DELAY { 50 })

from Conditionals_LCD.h because when you have more than one servo this will lead to a compile error...
If someone has BLTOUCH and more than one servo it has to specify "50" directly in "configuration.h"

**Comment by Roxy-3D** [comment]
50 ms?   That is awful fast.   Do you REALLY need to specify that fast of a time?   That is just asking for a problem.

**Comment by GMagician** [comment]
It's not me is firmware default that set 50 for bltouch, but maybe you are ironic?
Sorry I'm not english and I can misunderstand you :-)

**Comment by Roxy-3D** [comment]
OK!  It must be fine.   But that seems awful fast to me...

**Comment by GMagician** [comment]
Consider that there is a 375ms after detach (custom define for bltouch)

**Comment by GMagician** [comment]
[PR] #7529 fix it
