### ISSUE TITLE
Max6675 thermocouple conflicts 

### ISSUE THREAD

**Issue by Grogyan** [MarlinFirmware/Marlin#753]
The MAX6675 conflicts with the RepRap Discount Full Graphic+SDCard
RAMPS V1-4
Marlin V1.0
Repository shows no updates recently for MAX6675 or Full Graphic display.
Display turns on, however it is completely blank

http://www.reprapdiscount.com/home/34-full-graphic-smart-lcd-controller.html#

No conflicts occur with the MAX6675 when used without an LCD display with included SDCard
Full Graphic Display works when setting Temp_0 to anything else other than -2, MAX6675

No temperature reading at all from the MAX6675
MAX6675 uses CS on pin 49
Full Graphic Display CS on pin 53

Disabling the SDSupport and Disabling the display and changing the CS for the MAX6675 to pin 53 (also moving the wire from pin 49 to pin 53), gives a temperature reading.
Enabling SDSupport and Disabling the display gives no temperature reading (wire and CS for SDCard on pin 53, MAX6675 on 49), no display as well (cause I disabled it)
Enabling Display and SDSupport (CS and wire for SDCard pin 53, MAX6675 on on pin 49) gives no display or temperature reading.
Have also swapped the CS for Display and SD, and MAX6675 CS and ran the same tests, still no go.

Some mention on this blog, about reading the temperature too quickly
http://www.brokentoaster.com/blog/?p=561

**Comment by JTrantow** [comment]
See issue #168. It should work as long as your selects are unique AND the other three lines are initialized prior to use. I found that I needed to change the initialization in temperature.cpp, tp_init()

``` cpp
  #ifdef HEATER_0_USES_MAX6675
    #ifndef SDSUPPORT
      SET_OUTPUT(MAX_SCK_PIN);
      WRITE(MAX_SCK_PIN,0);

      SET_OUTPUT(MAX_MOSI_PIN);
      WRITE(MAX_MOSI_PIN,1);

      SET_INPUT(MAX_MISO_PIN);
      WRITE(MAX_MISO_PIN,1);
    #endif

    SET_OUTPUT(MAX6675_SS);
    WRITE(MAX6675_SS,1);
  #endif
```

**Comment by alien2108** [comment]
I can confirm, problem remains! I tried to remap the pins for thermocouple in pins.h (when SDSUPPORT is enabled) to:

``` cpp
#ifndef SDSUPPORT
// these pins are defined in the SD library if building with SD support
  #define MAX_SCK_PIN          52
  #define MAX_MISO_PIN         50
  #define MAX_MOSI_PIN         51
  #define MAX6675_SS       53
#else
  // REMAP THE PINS
  #define MAX_SCK_PIN          63
  #define MAX_MISO_PIN         40
  #define MAX_MOSI_PIN         64
  #define MAX6675_SS           59
#endif
```

LCD stays blank even though nothing should interfere anymore with RepRap Discount Full Graphic+SDCard.

**Comment by alien2108** [comment]
Yes it actually is the LCD code (I have reprapdiscount smart LCD with sd card reader). Can you let us know the changes to code?

The code you mention up there (from 2nd April) is already in my source:

  #ifdef HEATER_0_USES_MAX6675
    #ifndef SDSUPPORT
      SET_OUTPUT(MAX_SCK_PIN);
      WRITE(MAX_SCK_PIN,0);

```
  SET_OUTPUT(MAX_MOSI_PIN);
  WRITE(MAX_MOSI_PIN,1);

  SET_INPUT(MAX_MISO_PIN);
  WRITE(MAX_MISO_PIN,1);
#endif

SET_OUTPUT(MAX6675_SS);
WRITE(MAX6675_SS,1);
```

  #endif

I checked and SDSUPPORT is defined for me, since my LCD also has SD CARD slot.

I also wonder why there are all this pins defined:

``` cpp
  #define MAX_SCK_PIN        
  #define MAX_MISO_PIN       
  #define MAX_MOSI_PIN       
  #define MAX6675_SS
```

MAX_MOSI_PIN or MAX_MISO_PIN is not used, since we only read from MAX (use the S0 pin on MAX). Which one is the correct one?

**Comment by Grogyan** [comment]
I have had some success

First thing I did was add this line to temperature.cpp and pins.h
#include "Sd2PinMap.h"

In pins.h from line 825, I removed the "MAX_" prefix
changed the code to

``` cpp
#ifndef SDSUPPORT
// these pins are defined in the SD library if building with SD support
  #define SCK_PIN          52
  #define MISO_PIN         50
  #define MOSI_PIN         51
  #define MAX6675_SS       66//53
#else
  #define SCK_PIN          52
  #define MISO_PIN         50
  #define MOSI_PIN         51
  #define MAX6675_SS       66//49
#endif
```

The MAX6675_SS pin definition was changed to digital pin 66, for the RAMPS 1.4 board, as that was the closest available, otherwise unused pin

Then in temperature.cpp from line 742

``` cpp
#ifdef HEATER_0_USES_MAX6675
    #ifndef SDSUPPORT 
      SET_OUTPUT(MAX_SCK_PIN);
      WRITE(MAX_SCK_PIN,0);

     SET_OUTPUT(MAX_MOSI_PIN);
      WRITE(MAX_MOSI_PIN,1);
     SET_INPUT(MAX_MISO_PIN);
      WRITE(MAX_MISO_PIN,1);
    #endif
        #ifndef SDSUPPORT
      SET_OUTPUT(SCK_PIN);
      WRITE(SCK_PIN,0);

      SET_OUTPUT(MOSI_PIN);
      WRITE(MOSI_PIN,1);

      SET_INPUT(MISO_PIN);
      WRITE(MISO_PIN,1);
    #endif
      /*    SET_OUTPUT(SCK_PIN);
      WRITE(SCK_PIN,0);

      SET_OUTPUT(MOSI_PIN);
      WRITE(MOSI_PIN,1);

      SET_INPUT(MISO_PIN);
      WRITE(MISO_PIN,1);*/
      pinMode(SS_PIN, OUTPUT);
   //SET_OUTPUT(SS_PIN);
  // WRITE(SS_PIN,0);
digitalWrite(SS_PIN,0);  
pinMode(MAX6675_SS, OUTPUT);
   digitalWrite(MAX6675_SS,1);/*
   SET_OUTPUT(MAX6675_SS);
   WRITE(MAX6675_SS,1);*/
  #endif 
```

In short, I renamed the declarations to the standard SPI commands, in other words, removed the "MAX_" part of it
The next thing is essentially toggle the SD card select pin "SS_PIN" to 0.
Reason for this is that the program has to STOP talking to the SD card FIRST!
otherwise you are attempting to talk with both the MAX6675 and the SD card at the same time.

I used `pinMode` and `digitalWrite` as that was the only way I could get the code to compile and run.

If someone could verify this change and or improve on it, that would be great.

The next small caveat is the display reads the temperature unevenly, this is due to some capacitance (I used my finger to test if the temperature changes), and I am not sure also if the code to read the SD card needs to toggle the MAX6675 off first before talking with the SD card.
