### ISSUE TITLE
Mismatch of Z offset in uploaded firmware and the displayed data in host software

### ISSUE THREAD

**Issue by classbproject** [MarlinFirmware/Marlin#7534]
### Bug Report (Not sure if this is a bug but... here goes)
- Description: I've set the Z-probe offset in the firmware to be -1.05. However when I connect to the machine the host software shows it as -1.06. Though this may seem very small it seems to be affecting print aesthetics. 
- Expected behaviour:  Z-probe offset when connected to the machine to be -1.05
- Actual behaviour: Z-probe offset when connected to the machine shows -1.06
- Steps to reproduce: No specific steps really. 

The configuration.h is attached here.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1236659/Configuration.zip)

**Comment by tcm0116** [comment]
Did you run `M502` followed by `M500` after loading the firmware?
