### ISSUE TITLE
Thermal Runaway -and- Infill Ghosting

### ISSUE THREAD

**Issue by rebeltaz** [MarlinFirmware/Marlin#7538]
### Bug Report
- Description: ---
So I upgraded my Tevo Tarantula with an MKS Base controller to Marlin 1.1.4 to make better use of the autobed leveling features - bilinear leveling to be exact. Ever since, though, I've notice at least two issues that were not there before. 

First, using a 40mm radial fan on a "fang" duct, I am having to drop my fan speed from 100% to 75% to prevent the machine from shutting down due to Thermal Runaway whereas this never occurred under Marlin 0.1d. 

Second, using two walls (0.8mm) in Cura 2.7, I am getting ghosting of the internal infill on the outside of the model. I had overlap set to 30% before under Marlin 0.1d (with the same two walls) with no issues at all. Now, with overlap set to 10% I am still getting ghosting. 

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1237236/Marlin.zip)

**Comment by thinkyhead** [comment]
- Ghosting is not a firmware issue.
- Presuming you solved the thermal issue.
