### ISSUE TITLE
Marlin 2 Z offset values wildly different that 1.1.4.

### ISSUE THREAD

**Issue by KevMags** [MarlinFirmware/Marlin#7540]

**Comment by KevMags** [comment]
@This is not a big issue and I'm not complaining, just curious.  After upgrading from 1.1.4 BugFix to Marlin 2.0 BugFix I have to set my Z offset values much higher.  On one machine up from 0.41 to 0.71, another machine up from 0.47 to 0.91. 
Are these arbitrary numbers or are they supposed to reflect a true distance? 
Is the distance displayed in Babystepping proportional to the Z offset distance?  They don't seem to be with 2.0.  
I am also unable to set particular values for the Z offset Via the LCD as mentioned in #6172.  (no big deal)

**Comment by thinkyhead** [comment]
Keep checking in as 2.0.x develops. Some issues are sure to come and go up till release. Hopefully we'll have a testable official beta release soon.
