### ISSUE TITLE
[FR] Add GT2560 

### ISSUE THREAD

**Issue by Sblop** [MarlinFirmware/Marlin#7542]
I wonder why the GT2560 PCB is not added as a preset mainboard.
If any specific reason not, I suggest we add this.

**Comment by thinkyhead** [comment]
I presume you found `BOARD_GT2560_REV_A` and `BOARD_GT2560_REV_A_PLUS`!

**Comment by Sblop** [comment]
I was actually looking in the 2.0 bugfix, where it was not added, but realizing this I quickly closed this issue, as it is indeed added in the 1.1 bugfix release.
I will for now stay with 1.1 bugfix, as this is more stable, but still cutting edge. :-)
