### ISSUE TITLE
Filamentwidthsensor bug in marlin bugfix 1.1.x

### ISSUE THREAD

**Issue by Erlandsson** [MarlinFirmware/Marlin#7552]
I am running Velleman K8200 with Simplify3d 4.0, servo-bedleveling and filamentwidthsensor
The bug could be also in 1.1.4 i just did not notice it when trying it.
Had to try 1.1.bugxfix because of watchdog halts.

- Description: ---

I have startscript with M405 to turn on sensor, endscript is M406.
But the M406 does not seem to work, because when i in s3d extrude 10mm manually it extrudes about 15-16mm (consistent with filament aprox 2.65mm and Nominal width set to 3.0mm).

If i reset the controller and extrude 10mm it extrudes 10mm.
If i then M405 and extrude 10mm it extrudes 15-16mm as it should?
M406 to turn off still extrude 15-16mm not 10mm as expected.

- Expected behaviour: ---

M406 expected to turn off sensor compensation.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1246795/Configuration.zip)

**Comment by GMagician** [comment]
I checked the code M405 set filament_sensor=true and this flag will change
volumetric_multiplier[FILAMENT_SENSOR_EXTRUDER_NUM] value. 
M406 doesn't restore this value...maybe this is the issue.
Since I'm new to this firmware I may be terribly wrong...
Try using M200 with no parameters. It call a function that should reset it

If skilled developpers confirm this is an issue I may target this fix

**Comment by Erlandsson** [comment]
Ok , so after print script should be: M200 (without diameter) and then M406? Or do i skip M406 ?
I'll have to try and see if it behaves as if M405 is never used.
Sadly i have no display yet to confirm, so i have to manually extrude to check.

**Comment by GMagician** [comment]
First M406 then M200

**Comment by Erlandsson** [comment]
Thanks, that helped.

**Comment by GMagician** [comment]
Good to ear that.
If any developper can confirm me this is an issue I can try to let M406 behaves as required.
Maybe this is an intended way of act...

**Comment by GMagician** [comment]
You can close issue and if developpers consider it a bug they will integrate my fix for M406 so you don't need anymore to call M200

**Comment by GMagician** [comment]
@Erlandsson I think you can close this now.
