### ISSUE TITLE
Sanity check errors when update from 1.1.0 RC8 to 1.1.4

### ISSUE THREAD

**Issue by EnricoSx** [MarlinFirmware/Marlin#7559]
Sanity check error when update from 1.1.0 RC8 edit by anycubic for Delta Linear **PLUS** to 1.1.4

` #error "DELTA requires GRID_MAX_POINTS_X and GRID_MAX_POINTS_Y to be odd numbers."`
`#error "Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN requires Z_MIN_ENDSTOP_INVERTING to match Z_MIN_PROBE_ENDSTOP_INVERTING."`

[config.zip](https://github.com/MarlinFirmware/Marlin/files/1251213/config.zip)

Anycubic configuration.h contain
```
  #define GRID_MAX_POINTS_X 5
  #define GRID_MAX_POINTS_Y ABL_GRID_POINTS_X
```
```
// Enable Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN to use the Z_MIN_PIN for your Z_MIN_PROBE.
// The Z_MIN_PIN will then be used for both Z-homing and probing.
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN

// To use a probe you must enable one of the two options above!
```

Other info:
Anycubic Delta Kossel Linear **_PLUS_**
Firmare stock Marlin 1.1.0-RC8 edit from Anycubic
Arduino IDE 1.8.1

**Comment by fiveangle** [comment]
> Other info:
> No AutoLeveling

`#define AUTO_BED_LEVELING_BILINEAR`

?

**Comment by EnricoSx** [comment]
what?

**Comment by fiveangle** [comment]
You say "No Autoleveling" and yet have autolevelling defined (sorry, I thought the conext was obvious).

**Comment by fiveangle** [comment]
Your configuration.h is highly modified from the default: please hand-port your changes into configuration*.h in bugfix1.1.x and see if you still ahve an issue.  The obvious reason for your error above is you have an undefined ABL_GRID_POINTS_X that you're trying to set MAX_GRID_POINTS_X to.

You need to go back and fix your modifications to configuration*.h as they are extensive and if not the source of the problem, the source of at least SOME problems :)

If you can simplify and still show an issue then we might be able to help you.

**Comment by fiveangle** [comment]
also, when you got back and edit your original post to remove incorrect information that was pointed out, as if it was never there, you make things even more confusing :)

**Comment by EnricoSx** [comment]
mmm... ok

**Comment by EnricoSx** [comment]
there is an easy way to do this?

**Comment by EnricoSx** [comment]
i try marlin firmware migration tool
but with error
DELTA_SMOOTH_ROD_OFFSET 
DELTA_EFFECTOR_OFFSET
DELTA_CARRIAGE_OFFSET
Z_PROBE_ALLEN_KEY_STOW_DEPTH
min_software_endstops
MESH_NUM_X_POINTS
MESH_NUM_Y_POINTS
MESH_HOME_SEARCH_Z
ABL_GRID_POINTS_X
is obsolete :\ and now? 

anycubic write
#define INVERT_X_DIR **true** // DELTA does not invert
but is correct ? :\ it's a Delta Printer

**Comment by EnricoSx** [comment]
SanityCheck.h:564: error: #error "Enable only one option: Z_MIN_PROBE_ENDSTOP or Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN."

       #error "Enable only one option: Z_MIN_PROBE_ENDSTOP or Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN."

**Comment by EnricoSx** [comment]
i try correct and update

**Comment by Tannoo** [comment]
I use WinMerge to compare differences of files.
