### ISSUE TITLE
ramps 1.4 can't connect to pronterface

### ISSUE THREAD

**Issue by DJ0202** [MarlinFirmware/Marlin#7568]
Hello,

I have a Ramps 1.4 board witch is running on Marlin 1.1.4 and i use the g-code sender pronterface.

now when I connect my ramps board to my computer and try to connect pronterface with the board, my ramps board resets and pronterface keep saying "connecting...".  When i type a command pronterface says 'error# printer is offline' and i cant get it working not on a baud rate of 115200 neither on a baudrate of 250000.

plz help.

[configurations.zip](https://github.com/MarlinFirmware/Marlin/files/1253493/configurations.zip)

**Comment by DirtyDerv** [comment]
is your comport correct mine shifted for some reason about 2 days ago

**Comment by DJ0202** [comment]
In the configuration.h I have set COM 3 and Pronterface is also set to COM 3. 
The weird thing is, when I click on the button connect in Pronterface the ramps bord does restart itself, but Pronterface keep saying "connecting...".

**Comment by yashunandansureka** [comment]
Is your arduino having an active connection with some other program?

For example, i used to upload my firmware from the arduino IDE and then try to connect the printer in pronterface without it being disconnected in the arduino IDE.

Used to have the same issues

**Comment by Tannoo** [comment]
The serial port in `configuration.h` does not refer to your PC's port. That is the Arduino port. Leave it at 0.

**Comment by DJ0202** [comment]
@Tannoo thank you for your comment, that was the problem. tanks
