### ISSUE TITLE
After update from Rc8 to 1.1.4 nozzle fan not start

### ISSUE THREAD

**Issue by EnricoSx** [MarlinFirmware/Marlin#7570]
![fan](https://user-images.githubusercontent.com/16323227/29742351-f6d9ab38-8a7d-11e7-95c3-21df556df458.JPG)
After update from Rc8 to 1.1.4 nozzle fan (B04) not start.
what parameter i need to check?
Repetier Control only one fan now

**Comment by kevintong116** [comment]
check the `E0_AUTO_FAN_PIN` in configuration_adv.h 
Should be 44 for Trigorilla board

**Comment by EnricoSx** [comment]
works, thanks
