### ISSUE TITLE
Saving mesh for firmware update?

### ISSUE THREAD

**Issue by gcormier** [MarlinFirmware/Marlin#7582]
I'd like to flash 1.1.5 tonight - what is the best way to save the mesh from UBL and re-load it once the new firmware is flashed?

**Comment by Roxy-3D** [comment]
If you have a well tuned mesh...   You should save it (even if you are not doing a firmware update).
You can do that by saving it to mesh slot # -1.    G29 S -1
Later you can load that code into PronterFace and 'Print' it.   You mesh will be loaded and you can save it to an EEPROM mesh slot by doing something like G29 S1

**Comment by gcormier** [comment]
Sweet! Looks good :) Thank you as always!
