### ISSUE TITLE
Programming thermistor

### ISSUE THREAD

**Issue by Kondenado** [MarlinFirmware/Marlin#7583]
Dear all

I am trying to use a thermistor (Semitec 104GT2, 10K pullup resistor) as a thermometer, and so far I have managed to get the resistance values. 

I went to the webpage of the manufacturer to see if i could find any diagram relating resistance-temperature but they only speak about a "B" constant so i want to the marlin firm to see the part of the code that does that but i am unable of finding it.

Somebody could give me a hint please?

**Comment by FHeilmann** [comment]
thermistor readings are stored as lookup tables in marlin.

check this script from the repository: https://github.com/MarlinFirmware/Marlin/blob/1.1.x/buildroot/share/scripts/createTemperatureLookupMarlin.py

to see how they are generated.
