### ISSUE TITLE
[FR] Heater shutoff inactivity timer

### ISSUE THREAD

**Issue by marcio-ao** [MarlinFirmware/Marlin#7594]
It would be nice to have the ability to shut off all heaters after X minutes of inactivity. This value should be user customizable either through the LCD or an Mcode (options may be 30 minutes, 1 hour, 3 hrs, etc). This would be useful because certain slicers set the bed temperature to a part removal temperature, but if the user doesn't come to remove the part, it would be nice to eventually power down the heaters both for safety and for energy conservation.

This would be similar to DEFAULT_STEPPER_DEACTIVE_TIME, but for the hot end and bed heaters.

**Comment by gordo3di** [comment]
Wee set it in the end gcode. So the user determines it.

**Comment by cdedwards** [comment]
Thought about adding this myself. great idea, as I have discovered my hotend and bed still hot over night.

**Comment by marcio-ao** [comment]
@gordo3di: Yes, the part removal temperature is set in the end GCODE, but the printer will maintain that temperature indefinitely. It would be nice if the there was a timeout value that would cause all the heaters to turn off after a certain amount of time of inactivity.

**Comment by marcio-ao** [comment]
I am closing this FR since I was told that allowing the bed to cool completely could damage the print bed surface. So I am no longer looking to implement this timeout.
