### ISSUE TITLE
Display error with G28 -

### ISSUE THREAD

**Issue by Xserxes** [MarlinFirmware/Marlin#7599]
### Bug Report
Marlin 1.1.5
- Description: When using a Z-Probe and Homing with G28 the text is not correct. Function is perfect!
"echo:endstops hit:  **Z:1.00**" schould be "echo:endstops hit:  **Z:-1.00**" -> the minus is missing
- Steps to reproduce:
```
>>> m851 z-1
SENDING:M851 Z-1
echo:Z Offset -1.00
>>> m500
SENDING:M500
echo:Settings Stored (498 bytes; crc 685)
>>> g28
SENDING:G28
echo:endstops hit:  **Z:1.00**
```

**Comment by GMagician** [comment]
Hello,

maybe I'm wrong but messages are not related.

`M851 Z-1` set an offset (I think probe offset) while `G28` messages is where endstop has been hit

**Comment by riverratdc** [comment]
This sounds like the same problem I describe in issue #7081. I've had the "Endstops Z" message throughout the 1.1.x release branch. The last code I can use that doesn't display the error is RC8. The message does appear to be spurious, as the printer works well in all respects with 1.1.5 EXCEPT for the G28 being immediately followed with the "Endstops Z" message.

**Comment by thinkyhead** [comment]
Be sure to disable `ENDSTOPS_ALWAYS_ON_DEFAULT`.
