### ISSUE TITLE
Why is there a delay before Z Safe Homing only not in previous version

### ISSUE THREAD

**Issue by moth4017** [MarlinFirmware/Marlin#7603]
Version 1.1.5  #define Z_SAFE_HOMING on Core XY
in previous version all working ok, in 1.1.5 issue G28 - x and y home coreectly but just before homeing Z there is a pause and the Exturder motor sounds like its is being sent commands as you can hear it pulsing for about 10 seconds but not moving .  

If //#define Z_SAFE_HOMING is disabled z homing works correctly no delay ..

**Comment by thinkyhead** [comment]
Presuming solved.
