### ISSUE TITLE
UBL + Chimera BUG

### ISSUE THREAD

**Issue by Bolino08C** [MarlinFirmware/Marlin#7604]
Hello !

Hello ! When the UBL is active, I have a bug when changing the nozzle. The Z moves ... Why? 
Thanks You !

**Comment by joris57** [comment]
Glad to see that someone else also raises this problem. See issue #7469.

**Comment by Bolino08C** [comment]
Hello ! This is exactly the same problem

**Comment by thinkyhead** [comment]
Fixed in the current `bugfix-1.1.x` branch?

**Comment by boelle** [comment]
@Bolino08C is the problem gone with the latest bugfix 2.0?
