### ISSUE TITLE
NEW FIRMWARE RETRACT For SLIC3R and other

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#7607]
@thinkyhead 

> Here is my experience , and all i want to transmit to you about the new possibilities of FWretraction , for the new release ' SLIC3R' , that is now ready for MARLIN , in multi extrusion printing
> A few days before , SLIC3R couldn't make a gcode 100% FWretract . Now it's made . The release is only ' beta' but ready .

Printer in action
[Look Firmware retract in action and in SINGLE NOZZLE SYSTEM](https://www.youtube.com/watch?v=n3wsoSrxNNM)
References ;
[Understanding FIRMWARE RETRACTATION](https://github.com/MarlinFirmware/Marlin/issues/7597)
[Firmware Retract G10 S1](https://github.com/alexrj/Slic3r/issues/4106)

**The actual FWretract need this** 

*   **Only one ZLIFT** _In all situations_
    ` if (has_zhop && !hop_amount) {`

*   **Swap Recovery feedrate on LCD**
`MENU_ITEM_EDIT(float3, "Ech Unret V", &swap_retract_recover_feedrate_mm_s, 1, 999);`

*   **Speed of ZLIFT independently of Printing Feedrate** .. For ex you can set to the max 
`feedrate_mm_s = planner.max_feedrate_mm_s[Z_AXIS]; // Z feedrate to max 
// and restoration of the old feedrate just after`    .
_If you have time to make a lcd + eeprom + gcode M207  for the zlift feedrate , it's ok too :smile:_
*   **Possibility of a Z move between G10/G10S1/G11** _Compatibility with Simplify3d_
``` 
//if (hop_amount && NEAR(hop_height, destination[Z_AXIS])) {
if (hop_amount) { // avoid corruption of Z axis in all cases
```
*  **Possibility of a G10S1 after G10 with length correction** _Slic3r compatibility_ 
         *   **+ G10 ignored after G10 S1**
_To make it , we have to memorise swap status , it's why now it is not forced by the gcode but only by us_
```
inline void gcode_G10() {
    #if EXTRUDERS > 1
      const bool rs = parser.boolval('S');
      // NOT APPLIED HERE but only applied by the FWretract code
      //retracted_swap[active_extruder] = rs; // Use 'S' for swap, default to false
      //if (rs) retracted_swap[active_extruder] = rs; // Use 'S' for swap, default to false
    #endif
    retract(true
      #if EXTRUDERS > 1
        , rs
      #endif
    );
```

*   And some eject or allow conditionnals 

```
       // No double pure G10 or G1 + No G10 after G10S1
       if (!swapping && (retracted[active_extruder]== retracting))  return;
       // Allow G10S1 after G10
       if (swapping && (retracted_swap[active_extruder]== retracting))  return;
```
*    The length correction 
```
// if G10+G10S1
if retracting && swapping  then retract=  Swap retract - Normal retract      
 If G10 retract length = 4mm , if a G10 S1= 20mm
       then a G10 + G10S1 must retract 16 mm to be perfect on recover
```

Please can you make a PR :smile:

_Note; Slic3r have a little g10 appears on each first tool change , and impossible to be deleted , it's why , we have to tweak a little to be compatible with the flavor

**Comment by thinkyhead** [comment]
> Please can you make a PR 😄

Please, can you learn to do this on your own? You seem to be here often enough, you might as well learn to use Github. We all have many other things to work on, and not a lot of time for doing contributors' work for them. Please write the code, test it, and post it to a branch in your fork of Marlin, and then you can make a PR.
