### ISSUE TITLE
incorrect errormessage

### ISSUE THREAD

**Issue by ctday** [MarlinFirmware/Marlin#7612]
### Compile Error
```
Arduino: 1.8.3 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch\MarlinConfig.h:39:0,

                 from D:\cygwin64\home\Scots\Marlin\Marlin\Marlin.ino:31:

SanityCheck.h:973: error: #error "TEMP_SENSOR_1 shouldn't be set with only 1 extruder."

   #error "TEMP_SENSOR_1 shouldn't be set with only 1 extruder."

    ^

exit status 1
#error "TEMP_SENSOR_1 shouldn't be set with only 1 extruder."

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

I had CONFIGURE.H set for two extruders, one nozzle, and two hotend temp sensors. This is indeed an error, but the message should read "...with only 1 nozzle."

**Comment by Tannoo** [comment]
Please rename your `configuration.h` file to `configuration.txt` and post it here.

**Comment by ctday** [comment]
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/1277996/Configuration.txt)

**Comment by Tannoo** [comment]
Why don't you have `MIXING_EXTRUDER` enabled?

**Comment by ctday** [comment]
By my understanding, neither MM nor Prometheus is a mixing system, i.e., one where multiple filaments are fed to the nozzle simultaneously. They each withdraw one filament before feeding and clearing another filament. Also, that configuration is not necessarily a complete, consistent configuration; I've just started.

**Comment by Tannoo** [comment]
Ok... multiples and mixing is out of my league just yet.
Someone else will have to step in. Sorry

**Comment by ctday** [comment]
No problem.

**Comment by GMagician** [comment]
Sorry but if you have SINGLE_NOZZLE way do you have 2 temp sensors configured?

**Comment by GMagician** [comment]
Changed messages in sanitycheck from extruder to hotends, since these should be correct error messages.
I'll post a PR

**Comment by ctday** [comment]
The two temperature sensors and one nozzle was a mistake on my part, but it triggered the incorrect message.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by GMagician** [comment]
I think this can be closed

**Comment by MohamedSheblSaQr** [comment]
i have the same error now while trying edit  CONFIGURE.H set for two extruders one nozzle for each extruder. it's my graduation project and i need help plz.

**Comment by thinkyhead** [comment]
@MohamedSheblSaQr — 
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
