### ISSUE TITLE
[FR]Notice host on Run Out

### ISSUE THREAD

**Issue by miblooming** [MarlinFirmware/Marlin#7614]
### Feature Request
When marlin detected a run out signal, it could send a msg to notice the host to stop printing.
such as:
SERIAL_PROTOCOLCHAR("Filament change required");

**Comment by thinkyhead** [comment]
When filament runs out, Marlin will (by default) invoke `M600` (as soon as possible). While `M600` is active, the host receives a message that Marlin is busy.
