### ISSUE TITLE
Set the Points for LCD Leveling - ANET A8 example is wrong

### ISSUE THREAD

**Issue by SphaeroX** [MarlinFirmware/Marlin#7620]
Hi, if I level via the display on my Anet A8 with the example configuration, then I have the problem that he wants to level left over the hole for the screw. Where can I adjust this without changing the size of the print bed?

**Comment by Tannoo** [comment]
```
  #define LEFT_PROBE_BED_POSITION 15
  #define RIGHT_PROBE_BED_POSITION 170
  #define FRONT_PROBE_BED_POSITION 20
  #define BACK_PROBE_BED_POSITION 170
```

**Comment by SphaeroX** [comment]
I have already tried to change these values but unfortunately it has no effect on it.

But I'll try it again tomorrow or so, thank you for your help.

**Comment by Soulreaver76** [comment]
I have the same problem
Nothing changes at the position.

**Comment by Phr3d13** [comment]
I think you may have to load firmware defaults or load from eeprom or whatever it's called after changing some things.
