### ISSUE TITLE
LCD_BED_LEVELING wont work at Anet A8

### ISSUE THREAD

**Issue by SphaeroX** [MarlinFirmware/Marlin#7621]
I tried to level my print bed with the help of LCD_BED_LEVELING, after I levelled my print bed and saved the settings, I tried to print something.

But when I was printing, I realized that I was too close to the printing bed, so I decided to go up a few millimetres to test it. Marlin's just not hiring.

I also tried the launch code.

G29; bed level 
M420 S1; bed leveling on

Here are the settings I changed for levelling:

#define LCD_BED_LEVELING
#define MESH_BED_LEVELING
#define PROBE_MANUALLY

i also try it without PROBE_MANUALLY

**Comment by Tannoo** [comment]
Marlin is volunteer work.

Could you post your config files?

**Comment by SphaeroX** [comment]
I know Marlin works on a voluntary basis, and I'm very grateful that people are doing it.  The firmware is awesome and I'm very happy with it, but it would be nice if the features also work so that the work wasn't for free: =)

Here is my configs

Configuration.h
https://drive.google.com/open?id=0B0NMAY4eAucoVkJzRHU0alVBcWs

Configuration_adv.h (didnt cahnge anything)
https://drive.google.com/open?id=0B0NMAY4eAucoQmVYZkFpTWVtSW8

**Comment by Soulreaver76** [comment]
I have the same problem.

**Comment by SphaeroX** [comment]
When I connect the printer to my PC via USB and open the Arduino console, I see that the levelling values are stored. But he doesn't use them for printing.

**Comment by MasterPIC** [comment]
I found that the home command disables home leveling (you can check the state by G29).
To solve the issue you've to send M420 S1.

I hope it helps.

**Comment by SphaeroX** [comment]
Thanks for the solution

**Comment by SphaeroX** [comment]
Thanks for the solution

**Comment by Roxy-3D** [comment]
Not all of the bed leveling systems disregard the users preference and clear it with a G28.  At entry it remembers the state:

https://github.com/cdedwards/Marlin-cde/blob/bugfix-1.1.x/Marlin/Marlin_main.cpp#L3940-L3947

UBL was designed to respect the user's preference and preserve it across a G28.  At the end of G28 UBL restores the state:

https://github.com/cdedwards/Marlin-cde/blob/bugfix-1.1.x/Marlin/Marlin_main.cpp#L4094-L4097

**Comment by guiseco** [comment]
UBL on anet A8 ?

**Comment by SphaeroX** [comment]
Yeah UBL wont Work with Anet Boards (memory) ;)
