### ISSUE TITLE
Flashing Marlin doesn't set default steps correctly

### ISSUE THREAD

**Issue by Louis-Cypher** [MarlinFirmware/Marlin#7633]
### Bug Report
- Description: Marlin doesn't set values for default steps
- Expected behaviour: Uploading the image should set values
- Actual behaviour: I changed Z steps to 2560 instead of 4000 as well as Extruder values but the values didn't change after a successfull compile and upload. Setting values using M92 works fine.
- Steps to reproduce:
  - Flash 1.1.5
  - Change value for Z steps
  - Check default step settings on LCD.

**Comment by KevMags** [comment]
Either clear EEPROM before upload or send "M502" (Reset to default/firmware settings).

**Comment by Louis-Cypher** [comment]
Am I getting you right that this is intended behavior? I never had to do that before.

**Comment by KevMags** [comment]
This only happens when you reflash with the same version of Marlin.  Flashing a different version will overwrite EEPROM with firmware settings.

**Comment by Louis-Cypher** [comment]
Ok,  thanks, got it. But is this intended or not? In case yes this is no bug and I'll close this issue

**Comment by psavva** [comment]
Agree that this is by design.  Please close this incident if you're happy with the explanation

**Comment by Louis-Cypher** [comment]
Thanks a lot for the clarification and the great work you are doing!
