### ISSUE TITLE
fine tuning UBL with G26 P4 does not work without an LCD screen and encoder wheel

### ISSUE THREAD

**Issue by jsundahl** [MarlinFirmware/Marlin#7640]
It seems like I'm unable to edit my UBL mesh if I don't have an LCD and encoder wheel. No serial commands are being processed, and the message my board is sending is 'busy: processing'. Is there something I'm not seeing?

**Comment by Roxy-3D** [comment]
For $10.00 including shipping you can put an LCD Panel on your printer:  http://www.ebay.com/itm/Reprap-RAMPS1-4-2004-LCD-display-controlle-with-adapter-Mendel-Prusa-3D-Printer-/310741823606?epid=678434634&hash=item4859a7f076:g:ykAAAOSw~e5ZSiMG

UBL's G29 P4 does assume the existence of an LCD Panel.   And just for the mesh editing, it is worth the $10.    But in the mean time, you can edit the mesh with M421.  You can edit any mesh point that you want to change the value of.
