### ISSUE TITLE
Markforged Mark 2 type 3d printer firmware

### ISSUE THREAD

**Issue by emrecanunat** [MarlinFirmware/Marlin#7642]
Hi everyone, I built a 3d printer whose x and y axis so much similar to markforged mark two 3d printer. The problem is that I couldnot figure the configuration for that type of printer. For example, when I want the nozzle to be still and move the axis to the x direction I need to move both of the motors. and I want to move the nozzle I need y motor working and x motor lock . 

    Can you help me out with this issue ?

**Comment by VBen** [comment]
For me the markforged looks like a COREXY
one the following configuartion options should help you
```
//===========================================================================
//============================= Mechanical Settings =========================
//===========================================================================

// @section machine

// Uncomment one of these options to enable CoreXY, CoreXZ, or CoreYZ kinematics
// either in the usual order or reversed
//#define COREXY
//#define COREXZ
//#define COREYZ
//#define COREYX
//#define COREZX
//#define COREZY
 
```
