### ISSUE TITLE
Delta G29 - Unified Bed Leveling, Grid Mesh Leveling

### ISSUE THREAD

**Issue by novio8** [MarlinFirmware/Marlin#7643]
Hi,
if I run G29 J6 (Grid Mesh Leveling with 6 points)
only 1/4 of the surface is probed - right back part.
Am I doing something wronge here ?
If I run G29 P1 whole surface is probed.

Regards
Mario

**Comment by Roxy-3D** [comment]
A regression has crept into the code base.   Please see #7572
