### ISSUE TITLE
Tevo Tornado not making Marlin Firmware open source 

### ISSUE THREAD

**Issue by uwuscutely** [MarlinFirmware/Marlin#7644]
The Tevo Tornado is using a Marlin Firmware however they are not making it open source. That is considered violating the open source law of Marlin. Any solutions? [](https://m.facebook.com/groups/241512023021682?view=permalink&id=273401006499450)

**Comment by Roxy-3D** [comment]
The first step is make a formal request that they provide the current (shipping) source to their customers.

**Comment by uwuscutely** [comment]
Someone has already done so but the CEO declined

**Comment by Jinxycob** [comment]
maybe a few emails from the marlin Dev team could clear this up, its striking a startup like Tevo would do this. "kimhee you have the email addr. spare  a willing Dev from having to search for it"
  did the printer come with an Sd card ? is it on there.

**Comment by uwuscutely** [comment]
It did come with an SD card however it's not in there

**Comment by marcio-ao** [comment]
The following may be a resource: http://gpl-violations.org

**Comment by dot-bob** [comment]
They have released the firmware.  Right now it is posted in their facebook group under the files section.

**Comment by Roxy-3D** [comment]
> it is posted in their facebook group under the files section

Can you provide a link?   I was trying to check it out and I can't find the 'Files' section.

**Comment by dot-bob** [comment]
The firmware can be downloaded here but you will need to join the TEVO Tornado Owners group: https://www.facebook.com/groups/TEVO.Tornado.Owners/274134936426057/

**Comment by thisiskeithb** [comment]
Here's a non-Facebook link to the Tevo Tornado firmware (Marlin 1.1.4) that @dot-bob posted above: https://file.io/fTfKNc

**Comment by bogaskilop** [comment]
This. Fb group is not egist any more ? (It has a lot of users, now it shows me only 5 and i'm not in that group lol but why? I was in that fb group). Non fb link is also down :(

**Comment by jannis77** [comment]
http://tevo.cn/software-download.php

**Comment by thinkyhead** [comment]
That's better. Under GPL a vendor cannot require you to sign up for a group or attach extra conditions to obtain the firmware.
