### ISSUE TITLE
Reduce Height that Z Axis Lists on Homing

### ISSUE THREAD

**Issue by noctain** [MarlinFirmware/Marlin#7658]
Hi, my request isn't a bug. I just want to change the setting that raises the Z-AXIS after homming the X-AXIS and Y-AXIS. I have two stepper motors that lift my Z-AXIS. After homing (X and Y) the Z-AXIS lifts very high and then when it homes my motors seem to come down at different speeds so that the Z-AXIS is not level and the Z-AXIS homes at different heights. Could you direct me to where I can reduce the height the Z-AXIS lifts?

**Comment by GMagician** [comment]
Not sure but take a look at the bigger value between `Z_CLEARANCE_BETWEEN_PROBES` and `Z_CLEARANCE_DEPLOY_PROBE`.
They are also used during probing...
