### ISSUE TITLE
Reprap discount full graphic smart controller 

### ISSUE THREAD

**Issue by vMeph** [MarlinFirmware/Marlin#7659]
my lcd dont show this selection type higlighted, insted just shows a line square arround selection
![2017-09-14_122716](https://user-images.githubusercontent.com/12812111/30427698-af0ade4c-9948-11e7-83be-0551645b3ea6.png)
to make it show like the pic , the selection higlighted do i have to config anything?

**Comment by Tannoo** [comment]
Comment out this line in `configuration_adv.h`:

`#define XYZ_HOLLOW_FRAME`

**Comment by vMeph** [comment]
@Tannoo thanks alot for the info
