### ISSUE TITLE
[FR] Support U8g2

### ISSUE THREAD

**Issue by Xeroxxx** [MarlinFirmware/Marlin#7668]
### Feature Request

As development of U8glib has been discontinued, are there any thoughts about or progression on supporting U8g2 with future update like 2.x or later?

Cheers

**Comment by fiveangle** [comment]
There's be lots of thought, but as the U8glib lib used in Marlin is highly modified for Marlin use, the work to port would likely be extensive to retain performance and low resource usage, so it has not been tackled and I don't think it will be for the 8-bit platforms.

Thanks,

-=dave

**Comment by mtowara** [comment]
how is the U8glib used in Marlin any different?
At least according to the Makefile the regular library is used?
```
ifeq ($(U8GLIB), 1)
VPATH += $(ARDUINO_INSTALL_DIR)/libraries/U8glib
VPATH += $(ARDUINO_INSTALL_DIR)/libraries/U8glib/utility
endif
```
(note that this snippet actually doesn't work anymore, but its fairly similar)

**Comment by Xeroxxx** [comment]
Actually I don't see any modification in U8glib, as Marlin doesn't deliver a own version. I'm using the one from the creators repo.

I'm aware this is more work than swapping the library's files. However shouldn't there be a performance improvement and less custom code?

https://github.com/olikraus/u8g2/wiki/u8gvsu8g2

Cheers

**Comment by fiveangle** [comment]
I meant that * Marlin * was highly optimized to use U8glib and performance of U8g2 is abysmal vs U8g, plus much larger PROGMEM than U8g, sorry.

https://www.youtube.com/watch?v=fyPpYOoHn0I

Author's response:

> Obviously... u8g2 has not been optimized for speed but for portability

https://github.com/olikraus/u8glib/issues/447#issuecomment-262707911

Enjoy the rabbit hole ;) : 

https://github.com/olikraus/u8glib/issues/447, #5274, #5288

The larger solution is Marlin is moving to 32-bit so any work to port to U8g2 for 8-bit AVR would be pretty much wasted effort in the long run.

Please close once you've satisfied your curiosity that this has already been explored _ad nauseum_ :)

Thanks,

-=dave

**Comment by Bob-the-Kuhn** [comment]
@fiveangle - I've been playing with u8g2 in the 32 bit branch.  Didn't take long before I realized I was in over my head (which is easy to do).

It sounds like there were a couple of forks that had u8g2 running in the 8 bit branch.  Maybe one of those can help me get moving again.  Could you point me to those branches or to the owners of the branches?

**Comment by fiveangle** [comment]
Bob, I'm not aware of any live ones (that havent been deleted :), but I think @AnHardt had come closest ?

**Comment by Xeroxxx** [comment]
@fiveangle 

Thanks for the links. I agree with you if this is actual behavior of u8g2 :)
