### ISSUE TITLE
compilation issue with 2.0 bugfix

### ISSUE THREAD

**Issue by 69kevinutah69** [MarlinFirmware/Marlin#7671]
### Compile Error
When I compile with UBL enabled I get an error:
```
sketch\src\gcode\calibrate\G33.cpp: In static member function 'static void GcodeSuite::G33()':

sketch\src\gcode\calibrate\G33.cpp:177:21: error: 'reset_bed_level' was not declared in this scope
```

**Comment by fiveangle** [comment]
Please read the template questions that you deleted when you opened this issue.  Can't help you without that info.

**Comment by Tannoo** [comment]
I am using bugfix-2.0.x and UBL works and even prints just fine.

**Comment by Tannoo** [comment]
It seems as though you are trying bugfix-2.0.x-new-layout?
