### ISSUE TITLE
how use g33 on delta?

### ISSUE THREAD

**Issue by EnricoSx** [MarlinFirmware/Marlin#7675]
hello, i try in my delta auto calibration with MANUAL probe
set delta heigh with m666 h301
execute g33
touch the paper
execute g33 until go to home
execute m500
`Calibration probing done.
	Calibrated 7 factors using 7 points, deviation before 3.3017 after 0.0367
	Endstops X-0.934 Y-1.770 Z0.000 height 307.825 diagonal rod 290.643 delta radius 159.371 Towers radius correction I6.56 J1.45 K0.00`

now my bed is Z7.8
if i try another G33 , the first point is out of bed.

can you teach me how to use it? thank you

**Comment by LVD-AC** [comment]
Are you sure you're using Marlin FW? What version?

**Comment by EnricoSx** [comment]
MalinKimbra MK4Duo, i know is similar to Marlin

**Comment by LVD-AC** [comment]
The delta calibration is completely different in MarlinKimbra (a variant of Rich Cattell Marlin maybe?)

**Comment by EnricoSx** [comment]
Ok, thanks

**Comment by LVD-AC** [comment]
You can give the Marlin 1.1.5 from here a try; there's some mathematical errors in the MarlinKimbra and Rich Cattell calibration algorithms.

**Comment by EnricoSx** [comment]
I contact magokimbra

**Comment by LVD-AC** [comment]
close issue
