### ISSUE TITLE
Issue with large prints, firmware locks up and skips gcode

### ISSUE THREAD

**Issue by nucu** [MarlinFirmware/Marlin#7677]
Whenever I print objects where a single extrusion line exceeds a certain length/feedrate ratio (long and slow), some weird stuff happens:

> -the controller stops recieving gcode and just sends busy signals
> -when the last acknowledged gcode comannd is reached, **a lot of gcode commands are then skipped and just the E-Axis is driven a lot**, then at some point the firmware begins to accept and exec gcode and continues, but at a wrong point
> -also noticed that the displayed nozzle position is wrong and steady

### Infos:
Cartesian "BQ Hephestos 2" with "BQ_ZUM_MEGA_3D" board (Atmega2560)
Firmware: 1.1.4/1.1.5

### Tried:
-disabled watchdog, printjobtimer, print counter -> no result
-diabled "PREVENT_LENGTHY_EXTRUDE" -> no result
-disabled Display to get more cpu power ->no result
-Octopi as well as SD-card -> error with both

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/1309243/Config.zip)
Includes the two gcode files that fails and passes, but are nearly the same in size.
The Octopi Terminal log shows the point where "Send: N86" happens. Thats the last gcode that is send before the firmware refuses to accept more and also the last that is executed properly.

There were some similar bugs, but only related to delta printers:
#6703 #7303 #7510

Best regard, please be gentle with me, i dont do bug reports every day.

EDIT:
The problem seems to be time/timing related, the bug occures much further ahead in gcode with larger prints. The bug also scales with feedrate, with a higher feedrate the bug occures later, with even higher feedrate the bug disappeares.

**Comment by nucu** [comment]
I found the problem.

EXTRUDER_RUNOUT_PREVENT is not blocked during printing and will inject/add an extrude command into the planner. This will only happen when very long/slow moves are performed who exceedes EXTRUDER_RUNOUT_SECONDS.

Note: The planner ringbuffer is corrupted by this.

**Comment by thinkyhead** [comment]
See if it helps to change the conditions to these:
```cpp
  #if ENABLED(EXTRUDER_RUNOUT_PREVENT)
    if (thermalManager.degHotend(active_extruder) > EXTRUDER_RUNOUT_MINTEMP
      && !planner.blocks_queued()
      && ELAPSED(ms, gcode.previous_cmd_ms + (EXTRUDER_RUNOUT_SECONDS) * 1000UL)
    ) {
```
If so then we can use this as our solution.

**Comment by boelle** [comment]
@nucu do you still have the problem with the latest bugfix 2.0 ?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
i think there might be something to this issue

i tried to create a large cube 160x160x158.4 and print it as single wall

when print starts it probes bed like it should and heats up bed, but when bed it heated up it does not go to start pos. like the gcode says, but it tries to print outside the bed

i have marked with a red arrow in slic3r where it should start

![image](https://user-images.githubusercontent.com/3832239/54483054-a043f280-484d-11e9-836d-4c861fd68417.png)

**Comment by boelle** [comment]
but it does start at the other side of the object
![image](https://user-images.githubusercontent.com/3832239/54483060-c5d0fc00-484d-11e9-96dc-762c8c237ed0.png)

test code(rename from big cube test.gcode.txt to big cube test.gcode)
[big cube test.gcode.txt](https://github.com/MarlinFirmware/Marlin/files/2974611/big.cube.test.gcode.txt)

**Comment by boelle** [comment]
been printing a 160x160x158.4 cube in wase mode for 36 mins and so far i cant see any problem

**Comment by nucu** [comment]
The problem only occurs when a single gcode command is longer than EXTRUDER_RUNOUT_SECONDS. 

#define EXTRUDER_RUNOUT_PREVENT 
#define EXTRUDER_RUNOUT_SECONDS = 10

G1 X0 Y0 E0 F900
G1 X200 Y200 E10

// 282mm total length with 15mm/s result in 18.8sec single gcode execution time
// 18.8sec > 10sec
// problem occurs, ring buffer gets corrupted, unexpected behaviour

I did not tested it since then because i dont use this feature anymore. And im on 1.1.9 sorry :-(
