### ISSUE TITLE
Bad spiraling circles

### ISSUE THREAD

**Issue by Leenderm** [MarlinFirmware/Marlin#7682]
### Bug Report
- Description: --- Large circles progressively warp into ovals spiraling up the print see pic
- Expected behaviour: --- Circular circles
- Actual behaviour: ---  Large circles progressively warp into ovals spiraling up the print
- Steps to reproduce:
 CoreXY printer, print tall round vase, seems to occur when Z is greater than 256mm
![20170918_144010](https://user-images.githubusercontent.com/32079858/30568786-8480cdf0-9d1a-11e7-8837-8282eaa82a97.jpg)

**Comment by Tannoo** [comment]
I will say, that is impressive. Too bad I can't replicate that.

**Comment by fiveangle** [comment]
Agree - that is awesome !

**Comment by Leenderm** [comment]
The CoreXY forum helped identify the problem, it was the print flexing from the extruded, once printed 1.1mm thick it printed fine.
![img_0083](https://user-images.githubusercontent.com/32079858/31060383-8ea4511e-a75e-11e7-8f97-021e25f0f427.JPG)

**Comment by Tannoo** [comment]
Oooh... that's even nicer!
