### ISSUE TITLE
UBL Fine Mesh Bed leveling adjustment steps

### ISSUE THREAD

**Issue by devils27** [MarlinFirmware/Marlin#7684]
Hi, I have set up my UBL mesh but when trying to do the G29 P4 on a point I am limited in the amount/steps to increase or decrease a point to adjust it.  If it is initially set by the probing to be 0.054, if I turn the knob to decrease it goes to 0.050 and if I increase it goes to 0.060, but if I try to go decrease again I cannot get back to 0.54, only 0.050.  Is there a way to configure Marlin to allow fine tuning to be less steps instead of being 0.01? I would like 0.001 steps since that is what probing does anyway.  I did it with manual mesh bed leveling to allow "finer" steps when manually leveling, how can I do this with the fine UBL leveling?  Thanks.

Also, Is there a way to manually input point numbers for a UBL Mesh?  I copied all of my 5x5 mesh point numbers down.  If I were to get a new board or erase EEPROM is it possible to manually input all of my UBL mesh point numbers as to not have to go through the whole probing and fine tuning again? (issue is when fine tuning you have to put the nozzle at a specific point and sometimes it may not be exact so inputting numbers that way will be inaccurate)

Thanks!!!!

**Comment by Roxy-3D** [comment]
The step size is mostly limited by how many encoder clicks you have per menu item.   

It might be good to have a way to dynamically adjust this.  But for right now...   Make it so it takes more encoder clicks per menu item.   And this will carry over into the G29 P4 editing.

> Also, Is there a way to manually input point numbers for a UBL Mesh? I copied all of my 5x5 mesh point numbers down. If I were to get a new board or erase EEPROM is it possible to manually input all of my UBL mesh point numbers as to not have to go through the whole probing and fine tuning again? (issue is when fine tuning you have to put the nozzle at a specific point and sometimes it may not be exact so inputting numbers that way will be inaccurate)

Yes...  First, you can save your mesh so it is easy to move to another machine or a new version of the firmware by saving it to mesh slot -1.    Do a G29 S -1 and save that output.  You can 'print' that output later to get the new mesh to a new machine (or a new version of the firmware).

But independent of that... you can do M420 to set any mesh point to any value.

**Comment by devils27** [comment]
How do I change encoder clicks per menu item.  every turn of the knob goes increases or decreases 0.010 for ubl mesh fine tuning but only for that from what i can see.  Is it at the bottom of the configuration.h somewhere that I am not seeing?

**Comment by devils27** [comment]
Is that "//#define ENCODER_STEPS_PER_MENU_ITEM 5"?  how would that correlate to ubl fine mesh steps when fine tuning?

**Comment by devils27** [comment]
Great thanks, i saved mesh to gcode that I can run if i need to reload it.  As for the steps, i found that I can modify one of the .cpp files but that might make the firmware unstable, plus leveling to that degree probably wont make a whole lot of difference and/or able to be kept that strict.  ty
