### ISSUE TITLE
Z Endstop frequency

### ISSUE THREAD

**Issue by RajaaKahel** [MarlinFirmware/Marlin#7686]
Hi, please I need to know the frequency/response time of Z Endstops pins, and if possible the frequency/response time MKS gen 1.4 capable of on Z Endstop. Thank you!

**Comment by AnHardt** [comment]
There is no fixed time.
The endstops are checked once per (quad-) (double-) step - and only if movement is towards the switch. Time depends on the current speed.

**Comment by RajaaKahel** [comment]
Awesome, thank you!
