### ISSUE TITLE
[Marlin 2.0 Bugfix Branch new layout] - Compile Error with BLTOUCH and PROBING_HEATERS_OFF

### ISSUE THREAD

**Issue by DaveAhrendt** [MarlinFirmware/Marlin#7688]
Compiling for MOTHERBOARD BOARD_RAMPS_14_EFB
With BLTOUCH and PROBING_HEATERS_OFF defined compiling fails with:

Arduino: 1.8.4 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

Stuff deleted...

C:\Users\Dave\AppData\Local\Temp\arduino_build_63964\sketch\src\module\motion.cpp: In function 'void do_homing_move(AxisEnum, float, float)':

C:\Users\Dave\AppData\Local\Temp\arduino_build_63964\sketch\src\module\motion.cpp:888:43: error: 'probing_pause' was not declared in this scope

     if (axis == Z_AXIS) probing_pause(true);

                                           ^

C:\Users\Dave\AppData\Local\Temp\arduino_build_63964\sketch\src\module\motion.cpp:908:44: error: 'probing_pause' was not declared in this scope

     if (axis == Z_AXIS) probing_pause(false);

                                            ^

Using library LiquidCrystal at version 1.0.7 in folder: C:\Program Files (x86)\Arduino\libraries\LiquidCrystal 
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

**Comment by Phr3d13** [comment]
I may be wrong, but I think 2.0 is only 32bit at the moment.

**Comment by fiveangle** [comment]
No, the flood gates were just opened for AVR issues in the 2.0 "new layout" branch.

Prepare yourselves.  Bug reports are coming... :)

But you will need to provide your configs for anyone to help resolving your compile error (it shoudl have shown you a template with this requirement when you opened the issue.

**Comment by DaveAhrendt** [comment]
Just use the default config files from the release and uncomment the BLTOUCH and PROBING_HEATERS_OFF #defines and try to compile.  My specific config files are irrelevant in this case.

**Comment by fiveangle** [comment]
PR #7699 should resolve

You can drop this file into your tree until it's merged.  Scott might have a more elegant way to resolve as well, but this should work for now:

https://github.com/fiveangle/Marlin/blob/bf20ng-undefined_probe_fn_fixes/Marlin/src/module/probe.h

**Comment by fiveangle** [comment]
#7699 has been merged; please update your local and test/close if resolved.

Thanks,

-=dave
