### ISSUE TITLE
Creality cr10 example config: #define TEMP_SENSOR_0 issues

### ISSUE THREAD

**Issue by totalitarian** [MarlinFirmware/Marlin#7691]
- Description: 
The wrong temp sensor is in the creality cr10 config file, #define TEMP_SENSOR_0 5 is for the e3d v6, stock hot end requires #define TEMP_SENSOR_0 1

- Expected behaviour: --- #define TEMP_SENSOR_0 1
- Actual behaviour: --- #define TEMP_SENSOR_0 5

**Comment by totalitarian** [comment]
PR submitted https://github.com/MarlinFirmware/Marlin/pull/7692

**Comment by fiveangle** [comment]
Can please close this since PR is opened ?
