### ISSUE TITLE
display settings for velocity don't change

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#7693]
bugfix-1.1.x-ca97348
the velocity max shown on the display is 200 for x&y. I change it in config to 500 and upload it and it remains 200.
Text says if eprom is enabled the saved settings override the config. But I don't see any eprom enable any more.
I change it on the display and save settings and I get a beep (I think it is an error beep) but nothing happens. I go back and look and it is still 200.
What am I missing?

The reason I am doing anything with this is since I loaded this release it runs about 1/3 the speed it used to.

**Comment by ruggb** [comment]
bugfix-1.1.x-ca97348
the velocity max shown on the display is 200 for x&y. I change it in config to 500 and upload it and it remains 200. 
Text says if eprom is enabled the saved settings override the config. But I don't see any eprom enable any more.
I change it on the display and save settings and I get a beep (I think it is an error beep) but nothing happens. I go back and look and it is still 200. 
What am I missing?

**Comment by ruggb** [comment]
never mind. I rebooted everything and it is back to "normal"
thx

**Comment by fiveangle** [comment]
close then ?

**Comment by ruggb** [comment]
sorry
