### ISSUE TITLE
_Bootscreen.h

### ISSUE THREAD

**Issue by vMeph** [MarlinFirmware/Marlin#7703]
shouldnt the _Bootscreen.h be included on lcd section on  Marlin-bugfix-2.0.x-new-layout?
cant find fie _Bootscreen.h only under exemples, where i need to put this file if not using exemples? 
Shouldnt file be on defaults or lcd folder?

**Comment by Phr3d13** [comment]
That file is only needed if a _custom_ bootscreen is desired. If you wish to build your own bootscreen to be shown before the marlin one, look at the example in the BQ Hephestos_2 folder, there are comments at the top of the file that lists tools to generate your own bitmap array.

**Comment by Phr3d13** [comment]
If you now consider this issue closed, could you please mark it as such?

**Comment by vMeph** [comment]
Thanks i was able to figuer out from exemples
