### ISSUE TITLE
[Marlin 2.0 Bugfix Branch new layout] Anet compile issues

### ISSUE THREAD

**Issue by Phr3d13** [MarlinFirmware/Marlin#7704]
### Compile Error
When I compile with the anet a8 example config I get an error:
```


C:\Users\Phr3d\AppData\Local\Temp\arduino_build_182463\sketch\src\module\temperature.cpp: In static member function 'static void Temperature::isr()':

C:\Users\Phr3d\AppData\Local\Temp\arduino_build_182463\sketch\src\module\temperature.cpp:1975:33: error: 'START_ADC' was not declared in this scope

         START_ADC(ADC_KEYPAD_PIN);

                                 ^

Using library LiquidCrystal at version 1.0.7 in folder: C:\Program Files (x86)\Arduino\libraries\LiquidCrystal 
exit status 1
Error compiling for board Anet V1.0.
```
[anet-board-master.zip](https://github.com/MarlinFirmware/Marlin/files/1322003/anet-board-master.zip)

[Anet example configs.zip](https://github.com/MarlinFirmware/Marlin/files/1321230/Anet.example.configs.zip)

**Comment by fiveangle** [comment]
Please provide configs that result in above error, and provide correct board selection that should be set in Arduino IDE

**Comment by Phr3d13** [comment]
I added the board definition, and fixed the tagging of my previous post.

**Comment by Phr3d13** [comment]
[This](https://github.com/MarlinFirmware/Marlin/pull/7767/commits/33588081783cab7252f6fcff5d05b064ae6993fb) commit should fix this.

**Comment by Phr3d13** [comment]
Thinkyhead's recent commit fixes this.
