### ISSUE TITLE
[Marlin 2.0 Bugfix Branch new layout] GT2560 example compile issues

### ISSUE THREAD

**Issue by Phr3d13** [MarlinFirmware/Marlin#7705]
### Compile Error
When I compile with Geeetech GT2560 example config I get an error (actually 2, but the first was just complaints about old version config, I edited the #'s after comparing the new default example and the new gt2560 example and not seeing any big differences) :
```
C:\Users\Phr3d\AppData\Local\Temp\arduino_build_251570\sketch\src\gcode\control\M80_M81.cpp: In static member function 'static void GcodeSuite::M81()':

C:\Users\Phr3d\AppData\Local\Temp\arduino_build_251570\sketch\src\gcode\control\M80_M81.cpp:106:13: error: 'suicide' was not declared in this scope

     suicide();

             ^

Using library LiquidCrystal at version 1.0.7 in folder: C:\Program Files (x86)\Arduino\libraries\LiquidCrystal 
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
```

**Comment by fiveangle** [comment]
Please provide the updated config that results in the above error

**Comment by Phr3d13** [comment]
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/1321989/Configuration.h.txt)

**Comment by Phr3d13** [comment]
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/1321992/Configuration.h.txt)

**Comment by Phr3d13** [comment]
I don't think this is related to the long filename issue

**Comment by Phr3d13** [comment]
Adding
 `  #ifndef suicide()
  #define suicide()
  #endif`
before 
`suicide();`
in M80_M81.cpp
allows this to compile, don't know if it will break anything though.

**Comment by Phr3d13** [comment]
[This](https://github.com/MarlinFirmware/Marlin/pull/7709/commits/f42c1ea149cff45f08fc5bce650048fd4917ca7d) and [this](https://github.com/MarlinFirmware/Marlin/pull/7709/commits/c674adc1d99d883264927e5789567d3a0fd4318e) should fix this

**Comment by Phr3d13** [comment]
Should I submit new PR's (for this board and the Anet) for the renamed fork (now bugfix-2.0.x)?

**Comment by Roxy-3D** [comment]
Yes.  We are trying to merge everything back together again.   bugfix-2.0.x  is the main development branch (even if everything isn't 100% working yet).

**Comment by Phr3d13** [comment]
[This](https://github.com/MarlinFirmware/Marlin/pull/7767/commits/33588081783cab7252f6fcff5d05b064ae6993fb) commit should fix this.

**Comment by Phr3d13** [comment]
Thinkyhead's recent commit fixes this.
