### ISSUE TITLE
Feature request: Turn off ATX power after a timeout.

### ISSUE THREAD

**Issue by andrewsil1** [MarlinFirmware/Marlin#771]
After a long overnight print finishes, it'd be nice if the ATX power could shutdown automatically after an idle timeout.  I suppose I could solve this with Gcode postscript too, of course, but I used Repetier firmware for a little while and this was a feature I appreciated that I don't think is in Marlin.

**Comment by Ziggy2013** [comment]
IMO this feature "Turn off ATX power after a timeout" (or after cooling down) is already available in Marlin - just not actually called that.

A very simple way to do what you want is use the output PIN(s) from the temp status leds. When a print finishes, the extruder/bed starts cooling down. When the temp of both is below 54C the red led is switched off. Use that led output to turn off your power supply.  Might be nice to have the temperature defined as a config parameter as well though. 

code from configuration.h

```
// Temperature status LEDs that display the hotend and bet temperature.
// If all hotends and bed temperature and temperature setpoint are < 54C then the BLUE led is on.
// Otherwise the RED led is on. There is 1C hysteresis.
#define TEMP_STAT_LEDS
```

**Comment by boelle** [comment]
This one i will close... it can all be done in Gcode... and also some simple rewire of the fan can make it turn off with the extruder

adding this feature will just make the more complex while the gain of it is just to little...

the best fix here is to wire the fan to the extruder so it turns off as soon the extruder is off

and turn off the ATX with a Gcode
