### ISSUE TITLE
Question about AUTO_BED_LEVELING_BILINEAR

### ISSUE THREAD

**Issue by guiseco** [MarlinFirmware/Marlin#7711]
Can i use ABL with AUTO_BED_LEVELING_BILINEAR, run G29 just once and than save the MESH to future use with M420 ?

Att,

**Comment by Phr3d13** [comment]
Looking quickly at the docs section, I don't think M420 works that way. It appears that the mesh is saved if EEPROM is on. Have a read through [this](https://github.com/MarlinFirmware/Marlin/issues/5996) bug report. Also, maybe have a look at [G29 docs](http://marlinfw.org/docs/gcode/G029-abl.html), and [M420 docs](http://marlinfw.org/docs/gcode/G029-abl.html).

**Comment by guiseco** [comment]
Is, it works but bilinear sucks!
