### ISSUE TITLE
case light brightness

### ISSUE THREAD

**Issue by vMeph** [MarlinFirmware/Marlin#7731]
Marlin-1.1.x
case light brightness lcd control 
if light brightness is set at 255 it will work the on off button
if light brightness is less then 255 the on off button dont works

**Comment by AnHardt** [comment]
Be sure to use hardware pwm-able pin.

**Comment by vMeph** [comment]
Its o d4 it dimms perfect using lcd meno brigthness just dont works the on and off if is less the 255

**Comment by Tannoo** [comment]
Driving the case light via a relay can also cause this.

**Comment by vMeph** [comment]
Im using ULN2003 IC to drive

**Comment by RalphSch** [comment]
If I understand vMeph right than he doesn't have a problem with dimming the case light. I saw this bug also, if you are using a pwm value lower then 255 then the lcd menu action on/off does not work at all.

**Comment by vMeph** [comment]
ya thats what i tought, if ou put a value below 255 then dont works

**Comment by jmdearras** [comment]
I have the same issue, using pin 2  anything under 255  is off.  Fet drive, no relay.

**Comment by RalphSch** [comment]
Is it fixed?

**Comment by jmdearras** [comment]
Yes, in latest bugfix 1.1.x
