### ISSUE TITLE
[FR] Nozzle touch auto bed-leveling

### ISSUE THREAD

**Issue by vido89** [MarlinFirmware/Marlin#7732]
Add feature to marlin which will enable us to do accurate bed leveling by nozzle touching heated bed we can use slow speeds and even decrease speed to even slower when nozzle come 2cm near heated bed

**Comment by Roxy-3D** [comment]
There are already ways to do manual probing.   More of an explanation would be helpful.

**Comment by vido89** [comment]
Tnx for quick reply but explanation of what. Many people need this feature it should be implemented just let people decide do they gone use it or not

**Comment by AnHardt** [comment]
Recent versions of Marlin already have all you need to probe automatically with the nozzle - including approximation speed and cleaning it before.

```
// Speed for the first approach when double-probing (with PROBE_DOUBLE_TOUCH)
#define Z_PROBE_SPEED_FAST HOMING_FEEDRATE_Z

// Speed for the "accurate" probe of each point
#define Z_PROBE_SPEED_SLOW (Z_PROBE_SPEED_FAST / 2)

```

**Comment by Roxy-3D** [comment]
> Tnx for quick reply but explanation of what. Many people need this feature it should be implemented just let people decide do they gone use it or not

Manual probing exists in several forms.  But if you turn on UBL...   You can manually probe the unreachable parts of your bed with G29 P2.    Please check out what is already in place.

**Comment by vido89** [comment]
Thats great thank you very much is there any documentation on this topic how to enable autobed leveling ?

**Comment by vido89** [comment]
@Roxy-3D You say manual Im trying to do auto-bed leveling

**Comment by Roxy-3D** [comment]
> You say manual I'm trying to do auto-bed leveling

All of the various Auto Bed Leveling schemes work best if the bed is physically leveled as much as possible.    Please check out https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/ubl_G29.cpp#L163-L187 to see how UBL's MANUAL PROBING works.

**Comment by deram** [comment]
I'd like to use UBL and its G29 P2 B, but UBL won't compile without a probe, and PROBE_MANUALLY is not counted as one anymore.

**Comment by vido89** [comment]
@Roxy-3D Thank you also **[this](http://marlinfw.org/docs/features/unified_bed_leveling.html)** and [this](https://github.com/MarlinFirmware/Marlin/issues/6510) helped a lot

**Comment by RalphSch** [comment]
I'm using the direct nozzle touch method now for some weeks and it works great. There are some problems, like homing with cold filament .... take a look at #7680 ;)
