### ISSUE TITLE
Kossel mini Z height

### ISSUE THREAD

**Issue by roudybeest** [MarlinFirmware/Marlin#7740]
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/1329178/Configuration.h.txt)

[configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/1329175/configuration_adv.h.txt)

Hello guys,

i've been having this problem for the last 2 weeks.
I wanted to change my Z height for my printer since it wasnt calibrated right after the moving.
Since then, the z height wont change. it's "stuck" at 191,2.
In the Marlin i can change it to lets say 160, but when i try to move it down with S3D, it still goes down to 191,2. Even though it uploaded correctly. at least, i hope.
My printer is a Kossel Mini. And i change my z height in the software under the name: manual_z_home_pos: 

But as a few other people here, i'm still new to 3d printing and the marlin software in general.
I'm using a marlin i got from my old school, since i built it there with help from one of my teachers.
And since this marlin is kinda outdated, im also using an older version of arduino.

One other strange thing i noticed was that i cant manually bring down my z height with repetier software. I can make it go down by typing it manually, but not via the panel.

I hope someone can help me with this, since i have no clue where to start.

Kind regards,

**Comment by Phr3d13** [comment]
When changing values, make sure to load defaults and save to eeprom, otherwise your new firmware values won't get used. You also have to change the value in your slicer, it doesn't update the values itself
