### ISSUE TITLE
Wrong x carriage moved when active tool = T1 for dual_x_carriage configuration

### ISSUE THREAD

**Issue by w1ebr** [MarlinFirmware/Marlin#7745]
### Bug Report
- Description: --- Move x axis does not account for current tool in dual_x_carriage configuration
- Expected behaviour: --- After selecting T1, an x axis move should move the second x carriage. 
- Actual behaviour: --- The carriage x location as shown on the LCD is correct, but a move x axis only moves the T0 carriage, regardless of the active tool.
- Steps to reproduce:
  - Set the active tool to T1 (done via a custom menu)
  - Move the carriage on the x axis using the LCD menu
  - The wrong x carriage moves.

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1329936/Configuration.zip)

**Comment by thinkyhead** [comment]
Ah, good point… I'll make a patch for this today. In the long run, we should have a menu that includes special options for Dual X, such as parking, unparking, switching, etc.

**Comment by w1ebr** [comment]
Was the patch made?
Thanks!

**Comment by thinkyhead** [comment]
Working on this at the moment. I hope to have a patch soon.

**Comment by thinkyhead** [comment]
Patched! Turned out to be a simple solution.

**Comment by w1ebr** [comment]
NOOB question: How do I pick up this patch?

**Comment by w1ebr** [comment]
This does not appear to be fixed in 1.1.6. Is there a patch to 1.1.6 that I should make to get this?
Thanks!
