### ISSUE TITLE
Make printer execute script when is poweredon

### ISSUE THREAD

**Issue by batata004** [MarlinFirmware/Marlin#7788]
Hi,

I loved the new feature of Marlin that allows user to add custom scripts the LCD menu. That's nice! But everytime I boot up my printer I need to execute a script (it's a routine that heats up things, auto level, home...).

Is it possible to make the printer everytime it is powered on it executed a script? Is this feature already implemented? I belive so cause I think many people execute the same procedure when they usually turn on their printer, but I searched at google and couldnt find it.

ONE MORE THING: is it possible to make the printer automatically print the most recent file of the SD card everytime it's inserted in the SD slot? This would save lots of time cause everytime I need to start a print I need to go thought the tedious process of navigatin in the  menu to select the file to print.

**Comment by teemuatlut** [comment]
[auto0.g file on an SD card](https://github.com/MarlinFirmware/Marlin/wiki/Autostart)

**Comment by batata004** [comment]
@teemuatlut that's nice, really nice! But if I already have my printer turned on and insert the card it will not automatically play the auto0.g file, right?

**Comment by fiveangle** [comment]
No

http://bfy.tw/ECOX

**Comment by thinkyhead** [comment]
Careful. You wouldn't want Marlin to do a `G28` if it rebooted in the middle of a print.
