### ISSUE TITLE
[FR] Remote Serial Display Functionality for External LCD Controllers

### ISSUE THREAD

**Issue by Deneteus** [MarlinFirmware/Marlin#7790]
I would like to see some sort of external serial display functionality so I can do stuff like add an Android display as an external monitor for multiple printers. The ability for Marlin to output data to an external display allows boards with lower available memory to still use remote displays which will lower the size of the code needed for basic monitoring functionality. Wanhao i3 Plus does something like this and so does Kimbra by using external LCD's with their own dedicated storage/controller. 

I am envisioning something like loading an android app on my LG or Samsung Smart TV and being able to monitor print status without needing OctoPI or an external controller since remote control is built into the TV itself. 

FYI - This can be related to CAN bus (#7735) and Adding Nextion HMI Display support (#7754)

**Comment by pyr0ball** [comment]
I believe the DuetWifi also does this, but that's an ARM32 processor board from the getgo

**Comment by Grogyan** [comment]
Yes, CAN bus would be ideal for these types of displays.
Hence #7735

**Comment by AnHardt** [comment]
Original request is done in several ways.
