### ISSUE TITLE
Thermistors reading unstable on AVR on 2.0

### ISSUE THREAD

**Issue by alexxy** [MarlinFirmware/Marlin#7795]
Thermistor reading is unstable on AVR with bugfix-2.0

![screenshot_20170929_201429](https://user-images.githubusercontent.com/100408/31027550-2e662dac-a553-11e7-9afe-b3a8ac43deeb.png)

**Comment by thinkyhead** [comment]
Some boards have poor power regulation and need a better capacitor.
