### ISSUE TITLE
Issue when using BABYSTEP_ZPROBE_GFX_OVERLAY

### ISSUE THREAD

**Issue by dot-bob** [MarlinFirmware/Marlin#7797]
@marcio-ao,
If I enable the option #define BABYSTEP_ZPROBE_GFX_OVERLAY in configuration.h with the latest bugfix-1.1x branch I am getting the following errors (see my Travis CL output): [https://travis-ci.org/dot-bob/Marlin/builds/280716639?utm_source=github_status&utm_medium=notification](https://travis-ci.org/dot-bob/Marlin/builds/280716639?utm_source=github_status&utm_medium=notification)

Am I missing something that is causing these errors?

This seems to happen on all my builds derived from the latest bugfix-1.1.x as of today.  Perhaps it should be added it to the travis build check.

**Comment by Roxy-3D** [comment]
I think you found a bug!   We should @ that PR's author.

**Comment by Tannoo** [comment]
I ran into the same thing in `bugfix-2.0.x`. I couldn't seem to get the bitmaps declared. So....

In `dogm_bitmaps.h`, Move `#endif // HAS_TEMP_BED` to just before `#if ENABLED(BABYSTEP_ZPROBE_GFX_OVERLAY)`.

**Comment by apballard** [comment]
Yeah also having this issue.

**Comment by Tannoo** [comment]
BTW, @cdedwards gave me the correct correction. I thought I would update that here.
