### ISSUE TITLE
compile warning when EEPROM_CHITCHAT is disabled 

### ISSUE THREAD

**Issue by PxT** [MarlinFirmware/Marlin#7798]
When EEPROM_CHITCHAT is disabled:
```
/var/folders/_l/_rqp5xfn6p37y2ppx8zy376w0000gn/T/arduino_build_127709/sketch/configuration_store.cpp: In static member function 'static bool MarlinSettings::save()':
configuration_store.cpp:648: warning: unused variable 'eeprom_size' 
       const int eeprom_size = eeprom_index;
                 ^
```

Occurs because `eeprom_size` is defined in all cases but then only used inside an `ENABLED(EEPROM_CHITCHAT)` block. Pretty sure the compiler optimizes this away so it doesn't waste memory but for clarity it could be moved inside the proper block.

**Comment by GMagician** [comment]
I think this is already fixed, see closed PR #7715
