### ISSUE TITLE
Temperature reports approx 70 degrees higher than normal

### ISSUE THREAD

**Issue by kruuth** [MarlinFirmware/Marlin#7804]
Thank you for submitting your feedback to the Marlin project.
Please use one of the templates below to fill out this box.

------------------------------------------------------------
### Feature Request
Please put [FR] in the issue title: `[FR] Add-on that goes 'ping'`

------------------------------------------------------------
### Compile Error
When I compile with `FEATURE_X` I get an error:
```
Paste_the_error_text_here
```

------------------------------------------------------------
### Bug Report
- Description: --- temperature is returning 90-100 degrees on bed.  When you attempt to heat the bed beyond this temperature it behaves normally.  However, the display is always registering values between 93 and 100 degrees.  Setting the value to anything below this results in the printer thinking that the bed temperature is already high.  With no heating at all, using ambient temperature, it should be reporting 25-27 degrees.

- Expected behaviour: --- bed should be reporting around 25 degrees ambient
- Actual behaviour: --- bed reports 90-100 degrees ambient temperature
- Steps to reproduce:  Download and install bugfix1.1.x.  Copy Anet A8 Configuration.h and Configuration_adv.h.   
  - Enable inductive sensor
  - Compile as normal

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1346933/Marlin.zip)

------------------------------------------------------------
### Bug Report Tips
- When troubleshooting, use `M502` followed by `M500` to reset EEPROM to defaults.
- Use `DEBUG_LEVELING_FEATURE` with `M111 S247` for detailed logging of homing/leveling.
- Format text with: **bold**, _italic_, `code`.
- Format C++ with three backticks, plus "cpp":
```cpp
void my_function(bool do_it) {
  // Hold this spot
}
```

**Comment by kcheeeung** [comment]
You may want to check if you have the right thermistor profile in your config file. That is my first guess as to why the temperature looks like it's wrong.

Thermistors have different profiles, and if you use the wrong one, you will get readings that are off.

**Comment by kruuth** [comment]
That's what I thought at first, however I'm using the correct settings for the default A8 bed.

**Comment by Tannoo** [comment]
Bad connection?

**Comment by kruuth** [comment]
No, It reports fine at higher temperatures.

**Comment by Tannoo** [comment]
Maybe it is a wrong default thermocouple.

**Comment by kruuth** [comment]
Do you know what the default is for the Anet A8?  It is presently set for 100K thermistor - ATC Semitec 104GT-2 (Used in ParCan & J-Head) (4.7k pullup), which is in the default config.

**Comment by Tannoo** [comment]
I don't. Just try another one. 100k... try #1.

**Comment by kruuth** [comment]
I did.  It's returning 112 now.

**Comment by kcheeeung** [comment]
A8 is your **printer.** The manufacturer may provide different thermistors, and you have to find out which one. 

Otherwise you can also buy another thermistor with a known profile and use that.

**Comment by kruuth** [comment]
I've gone through the entire list in the config file.  Nothing.  The lowest I got it was 87.

**Comment by kruuth** [comment]
If it helps, this is the Anet A8 from Gearbest.

**Comment by kruuth** [comment]
Ok.  I've gone through the entire list.  I've gotten as high as 550 and as low as 50 but it's still much higher than ambient temperature.

**Comment by Tannoo** [comment]
I would tend to believe a bad thermo, or bad connection.

I haven't that issue with mine accross many different versions of Marlin.

**Comment by Tannoo** [comment]
Mine is not an A8 though... maybe a board issue?

**Comment by AnHardt** [comment]
Connect the thermistor to the pin for the second extruder. Swap the pins in the pin-file.
If you get the same readings, it's reasoned by thermistor or cabling (or software error). If not, by the board.

**Comment by kruuth** [comment]
Ok.  Tried that.  Same issue.  Replaced the board and it's working.  Chalk this up to a bad board.
