### ISSUE TITLE
Understanding Arduino PWM (non-standard PWM mode, compare interrupt enabled)

### ISSUE THREAD

**Issue by kcheeeung** [MarlinFirmware/Marlin#7805]
Hello everyone,

I am trying to take advantage of some of the PWMs available on my Azteeg X3 Pro board and have encountered something interesting. This has quite a few heater ports, many of which are PWM capable. One pin in particular is pin 11 and it shows **"non-standard PWM mode   compare interrupt enabled".** What does this mean? 

When I use the M42 P11 S### code, I am only able to turn it OFF (0) or ON (255), meaning when I measure the voltage, it shows us as either 0V or 24V. It is supposedly PWM capable, yet I cannot achieve anything in between.

`
PIN:  11   Port: B5        <unused/unknown>            Output = 1    TIMER1A   PWM:  2000    WGM: 4    COM1A: 0    CS: 2    TCCR1A: 0    TCCR1B: 10    TIMSK1: 2   non-standard PWM mode   compare interrupt enabled`

**Comment by AnHardt** [comment]
```
#define ENABLE_STEPPER_DRIVER_INTERRUPT()  SBI(TIMSK1, OCIE1A)
#define DISABLE_STEPPER_DRIVER_INTERRUPT() CBI(TIMSK1, OCIE1A)
```
Timer 1A is used by the stepper interrupt. Not a good idea to reuse it for a hardware PWM.
