### ISSUE TITLE
[FR] About

### ISSUE THREAD

**Issue by HappySock** [MarlinFirmware/Marlin#7809]
please add an about feature within one of the menus where we can see:

firmware version and date
Configured bed size ( see [FR] configure bed size)
plus perhaps for fun:
hours used
filament used
prints complete
print aborted

**Comment by thinkyhead** [comment]
Enable `LCD_INFO_MENU` and see if it contains enough information for you.

Includes:
- Marlin Version
- Build Date
- Print Count
- Completed Prints
- Total print time
- Longest job time
- Extruded total

Some of these require `PRINTCOUNTER` to be enabled.

**Comment by HappySock** [comment]
wow. almost nailed my list item for item.
