### ISSUE TITLE
Reboot loop

### ISSUE THREAD

**Issue by kruuth** [MarlinFirmware/Marlin#7825]
### Bug Report
- Description: ---  Anet A8 motherboard reboots every 5 seconds.  System otherwise seems to be working fine.  However, during uploading firmware system does not reboot.
- Expected behaviour: ---  Marlin doesn't reboot
- Actual behaviour: ---  Marlin reboots every 5 seconds

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1350656/Marlin.zip)

**Comment by Tannoo** [comment]
It you thinks it's firmware related, diable all options except for MB, thermo and movement settings, and see what happens.

**Comment by kruuth** [comment]
Ok.  Flashed with nothing but the MB, thermo, and movement stuff.  Getting same loop.  I'm guessing this is a HW issue.  Again.

**Comment by Tannoo** [comment]
Look for shorts on the 5v stuff... that can overload the regulator causing reboots.

**Comment by Tannoo** [comment]
Unplug all limits and see if that's it.

**Comment by kruuth** [comment]
I've unplugged everything and it's still rebooting.  I'm guessing it's the board.  Again.

**Comment by Tannoo** [comment]
Well... that sux.

**Comment by Tannoo** [comment]
Can you remove the drivers?

**Comment by Phr3d13** [comment]
@Tannoo Built-in drivers. @kruuth I can confirm that bugfix-1.1.x works on an anet board.
