### ISSUE TITLE
M600 'pause/parking ' bug 1.1.5 and the new bugfix not the other

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#7827]
**On M600**

1-)  **Retract and recover immediatly** .... ?????? 
2-) The first unload works but **The loading is 3 times the distance of my settings**

Code of M600 is the same as the old releases
Just ' RUNPLAN ' merged code appears
On last bugfix , and 1.1.5 

Try by yourself 
My old release ' one or two month ' works PERFECT
I have worked tow days and night , the problem need a better knowledge of the code , and I'm a newbie 
Set to destination or RUNPLAN not working well and not apply values when finish to move, or something like this
Thks

**Comment by studiodyne** [comment]
Same bug on the last 1.1.5 😢

**Comment by studiodyne** [comment]
After some hours 
Set destination to current 'uncommented ' , i see the carriage , go down and up , and it explains why, the extruder retract and recover quickly at the same time
The destinations in the planner are wrong or anything sound like this
I'm stopping here , to find this fix , need to be more intelligent 
iT's for you 👍

**Comment by ghost** [comment]
@thinkyhead 
@Roxy-3D 
@Bob-the-Kuhn 
@Tannoo 

Please , can you make an experience , try just once , the M600 command , but , in your firmware , define a park location , with a zlift 

and tell me if all is NORMAL , or  if your zlift not works before to go on nozzle park
I have a bad sensation of a merge PR that have destroy the actual release of marlin 
The M600 code is the same of the last , it's a RUNPLAN problem
The zlift/retract have issue and not work , the recover is doubled ,  the M600 source code is the same , ' set current to destination ' have problems or something sounds like this
Please try and let tell me if it's just me
Because i'm working on a new great feature of the M600 and i can make a PR if i have this destroyed behavior

Thks
