### ISSUE TITLE
Need help setting probe points for UBL

### ISSUE THREAD

**Issue by totalitarian** [MarlinFirmware/Marlin#7835]
I have a 300 x 300 bed, my probe has offsets of

X -29 
Y -51  

I need around 10mm clearance around the edges of the bed to avoid my binder clips. Due to the position of the probe, I can reach the front and left edges of the bed but not the rear and right edges.

What values do I need to set for the following and how do I calculate them?

>   #define UBL_MESH_INSET 30          // Mesh inset margin on print area
>   #define GRID_MAX_POINTS_X 15      // Don't use more than 15 points per axis, implementation limited.
>   #define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X
>   
>   #define UBL_PROBE_PT_1_X 50       // Probing points for 3-Point leveling of the mesh
>   #define UBL_PROBE_PT_1_Y 220
>   #define UBL_PROBE_PT_2_X 50
>   #define UBL_PROBE_PT_2_Y 90
>   #define UBL_PROBE_PT_3_X 240
>   #define UBL_PROBE_PT_3_Y 90

**Comment by thinkyhead** [comment]
Did you figure it out?

**Comment by ferrocam** [comment]
No I need points for a 220 by 220 bed with 10mm all around probe is -33 offset

**Comment by thinkyhead** [comment]
With the current Marlin ("nightly" bugfix-x.x.x branches) there are simpler options. Just set your probe offsets, then set `MIN_PROBE_EDGE` to 10 to avoid the binder clips. Everything else will be calculated automatically.

**Comment by jonathanweinberg** [comment]
@thinkyhead ~ Does that apply to UBL use or just ABL etc?

**Comment by Roxy-3D** [comment]
MIN_PROBE_EDGE should behave the same across all bed leveling systems.   It should restrict the nozzle's movement such that it stays that far away from the edge of the bed on all sides and for all bed leveling systems.

(If it doesn't...   We need to know so we can fix it.)

On the mesh based bed leveling systems...   We should probably have some logic to set MESH_INSET using MIN_PROBE_EDGE.   But for now, it probably makes sense to just manually set MESH_INSET to the same number as MIN_PROBE_EDGE.

**Comment by jonathanweinberg** [comment]
@Roxy-3D ~ Let me play. I *may* have had this set to `1`. For..._uh_...reasons? I wish I knew what reasons those were....
