### ISSUE TITLE
Strange behavior of the G33 of my new Delta 3d printer!

### ISSUE THREAD

**Issue by OldMzee** [MarlinFirmware/Marlin#7841]
When I issue "G33", only two of the axes move the third one seated (Home).
I can control all three as usual, with the control panel, or from Repetier-Host etc.
But not G33 or G29 ???
I am using Marlin 1.1.5, I tested other versions also it gives the same result !! 

/ I'm an old handicapped man who built "RepRap Mendel" that works well!

Please help !!
Bertil

**Comment by thinkyhead** [comment]
Try the latest `bugfix-1.1.x` and see if `G33` is now more to your liking.
