### ISSUE TITLE
[FR] File error action

### ISSUE THREAD

**Issue by JerryDurand** [MarlinFirmware/Marlin#7844]
I just printed one of my medium sized files using Marlin 1.1.5.  The file was created by Simplify3D, latest version on Windows.  I was printing from SD card.  Controller card is MKS Base

As the print was getting to where I knew it was almost done, I noticed the % done was at 58%.  ???

As I'm in the office with all the printers, I figured I'd keep an eye on it.  When it finished instead of the normal BEEP I have in the scrip it was quiet.  I jumped up and went to look at it, the system was rebooting.

The good news is, the heaters were off so the system failed safely.

On inspecting the file on the SD card I see there are 24,263 lines filed with spaces (0x20).  No idea why they are there.

Of course a proper reaction would be to simply ignore this white space no matter how much there is.

So, FR is to soft-fail on file oddities.

End of file here:
https://drive.google.com/open?id=0B3z7JJjmkXckOHNIbEg1bHBnZHc

**Comment by thinkyhead** [comment]
Marlin doesn't pre-scan SD files, as this takes forever.
