### ISSUE TITLE
[FR] Support for TRAMS (tmc5130)

### ISSUE THREAD

**Issue by detoxity** [MarlinFirmware/Marlin#7858]
Hello, will there be support for the TRAMS in Marlin?

**Comment by teemuatlut** [comment]
Yes.

**Comment by nwieb** [comment]
Hi, any news on this? I still have a trams laying around and im wondering if i should just throw it out. Thanks

**Comment by teemuatlut** [comment]
No need to throw it out even if it wouldn't work.
I recently "finished" a more universal library for the TMC drivers that supports more chips. This was one of the requirements for TRAMS support. Another requirement was for me to have more than one printer and that's fulfilled now as well.
So this summer is looking better progress wise. But it will definitely target the Marlin 2.0 branch and that's another thing to migrate.

**Comment by detoxity** [comment]
Hello! how about my question? Now trams are working on marlin?

**Comment by sidhant** [comment]
I too have a couple TRAMS boards lying around and it would make for an incredible controller if Marlin would support it.

**Comment by ellensp** [comment]
tmc5130 support is in marlin.
