### ISSUE TITLE
Z-Axis incorrect height after z homing and autolevel probing

### ISSUE THREAD

**Issue by ProfessionalTrash** [MarlinFirmware/Marlin#7889]
### Marlin 1.1bugfix Bug Report
- Description: Raises the z axis before homing x/y when a G28 is sent (which I am fine with), then raises it after homing x/y and before z (am fine with this), but after homing z raises by a few mm (5-10 maybe) instead of stopping after second probe tap, it then sets z position to 0 after homing and AFTER raising, so the nozzle is above from the bed and unable to be moved down (setting z_min to -10 doesn't allow it to be moved down, it raises it up another 10mm then sets the position to 0). Running G29 raises the z axis about 5mm as it should, then moves it to the first probe position, continues on through the probing procedure and raising about 5mm between each probe, then raises the z axis again after probing is done (instead of just stopping at the position of the second probe tap). By then z is set to around 5.4 (even though its the same position as when it raises after z homing), but can be lowered close to the bed (where it does read 0 at that point). The problem is, when I start a print, the nozzle remains at the 5mm position from when it lifted up after probing the bed. It also cannot be moved down close to the bed after homing z unless a G29 is run.
- Expected behaviour: z axis should stay at the position of second probe tap after both homing z and probing the bed for autoleveling.
- Actual behaviour: Stated in description.
- Steps to reproduce:
run G28
run G29

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1366349/Configuration.zip)

**Comment by thinkyhead** [comment]
If this issue persists in the latest nightly build (`bugfix-1.1.x`) please re-open.
