### ISSUE TITLE
Manual mesh bed levelling starting Z height

### ISSUE THREAD

**Issue by gapx15** [MarlinFirmware/Marlin#7898]
Hello, 

I have a problem with manual mesh bed levelling. I do bed levelling on LCD display and I see small issue  there. First levelling point always moves to Z_MIN_POS (my setting: Z_MIN_POS -2)position which is 2mm under the bed and crash nozzle into the bed. Display correctly shows -2. 

But I wonder how to set that first levelling point go to the Z 0 position and wouldn't crash into the bed at first levelling point.

Thank for the help in advance.

**Comment by thinkyhead** [comment]
See if the issue still exists in the latest `bugfix-1.1.x` nightly build. If it does, please re-open this issue.
