### ISSUE TITLE
G38.2 does not stop on Contact with Z_Min

### ISSUE THREAD

**Issue by Edgar48** [MarlinFirmware/Marlin#7907]
### Bug Report
- Description: Im using Marlin 1.1.3 also tried Marlin1.1.5 ; G38.2 Z does not stop on Contact with Z_MIN-G28 and G30 are working correct--
- Expected behaviour: G38.2 would stop on Contact
- Actual behaviour: >>>M502
echo:Hardcoded Default Settings Loaded
>>>M500
SENDING:M500
echo:Settings Stored (481 bytes; crc -31085)
>>>M111 S247
SENDING:M111 S247
echo:DEBUG:ECHO,INFO,ERRORS,COMMUNICATION,LEVELING
echo:G91
echo:G1 Z10.0 F3000
echo:G90
echo:M114
>>>G38.2 Z
SENDING:G38.2 Z
echo:G38.2 Z
  current_position=(0.00, 0.00, 10.00) : setup_for_endstop_or_probe_move
echo:busy: processing
  current_position=(0.00, 0.00, 0.00) : sync_plan_position
Error:Failed to reach target

Find ZIP of `Configuration.h` and `Configuration_adv.h`  here.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1367847/Configuration.zip)

Tried to follow simmilar Problemreports but it seems that all these bugfixes already have been implemented.

**Comment by fiveangle** [comment]
I'm not sure but are endstops required to be enabled for G38 to work ?

Have you tried after issuing M120 immediately prior ?

Also, once you reach target, endstop should be already triggered, so what is output of M119 at that point ?

**Comment by fiveangle** [comment]
Also, this wording seems like it can be slightly confusing if, like me, one isn't familar with the feature. 
G38.2 attempts to move to the position entered as parameters to the command and expects to trigger an endstop before reaching that end position.  However, the error message presented if it reaches end-position without triggering the endstop is:

`SERIAL_ERRORLNPGM("Failed to reach target");`

A clearer error might be "_Target not detected_" since with "_Failed to reach target_" one could conflate end-position (known and entered) with the target location (unknown which we are hoping to find), or otherwise question if they understand how the feature works, which is what happened to me.

But I digress...   :smile:

**Comment by Edgar48** [comment]
Thank you for your reply fiveangle. I tried M120 prio to G38.2 but didnt help. The M119 shows that Z_Min is trigered on contact, but z axis continues to move after contact  until Z=0 which is the target.
>>>M120
SENDING:M120
>>>G38.2 Z
SENDING:G38.2 Z
echo:busy: processing
Error:Failed to reach target
[ERROR] Error:Failed to reach target

>>>M119
SENDING:M119
Reporting endstop status
x_min: open
y_min: open
z_min: TRIGGERED


I had a look into the code :
#if ENABLED(G38_PROBE_TARGET)

  static bool G38_run_probe() {

    bool G38_pass_fail = false;

    #if ENABLED(PROBE_DOUBLE_TOUCH)
      // Get direction of move and retract
      float retract_mm[XYZ];
      LOOP_XYZ(i) {
        float dist = destination[i] - current_position[i];
        retract_mm[i] = FABS(dist) < G38_MINIMUM_MOVE ? 0 : home_bump_mm((AxisEnum)i) * (dist > 0 ? -1 : 1);
      }
    #endif

    stepper.synchronize();  // wait until the machine is idle

    // Move until destination reached or target hit
  

   **endstops.enable(true);**

    G38_move = true;
    G38_endstop_hit = false;
    prepare_move_to_destination();
    stepper.synchronize();
    G38_move = false;

    endstops.hit_on_purpose();
    set_current_from_steppers_for_axis(ALL_AXES);
    SYNC_PLAN_POSITION_KINEMATIC();

    if (G38_endstop_hit) {

      G38_pass_fail = true;

      #if ENABLED(PROBE_DOUBLE_TOUCH)
        // Move away by the retract distance
        set_destination_to_current();
        LOOP_XYZ(i) destination[i] += retract_mm[i];


        **endstops.enable(false);**


        prepare_move_to_destination();

        stepper.synchronize();

        feedrate_mm_s /= 4;

        // Bump the target more slowly
        LOOP_XYZ(i) destination[i] -= retract_mm[i] * 2;

        **endstops.enable(true);**


        G38_move = true;
        prepare_move_to_destination();
        stepper.synchronize();
        G38_move = false;

        set_current_from_steppers_for_axis(ALL_AXES);
        SYNC_PLAN_POSITION_KINEMATIC();
      #endif
    }

    endstops.hit_on_purpose();
    endstops.not_homing();
    return G38_pass_fail;
  }
Looks like G38.2 doesnt need a M120 prior as it takes care of endstop enabeling by itself

I have put a SERIAL_ERRORLNPGM("G38 if Endstopp hit  was reached"); into the If(G38_endstop_hit) and checked and it did not show up.

**Comment by Edgar48** [comment]
I'm currently trying to dig my way trough the code but I cant find the definition of the funktion  endstops.hit_on_purpose(). so i'm stuck

**Comment by AnHardt** [comment]
https://github.com/MarlinFirmware/Marlin/blob/99d18ecd0cc9be27cfc32f37cc7d1b476b4139a1/Marlin/endstops.h#L78

**Comment by Edgar48** [comment]
Thank you AnHardt.

I now found following:
In Routine
// Check endstops - Called from ISR!
void Endstops::update() {
    
 
is a fork G38  and I found, that in my case the expression PIN_EXISTS(Z_MIN_PROBE) is not giving True
  Z_MIN_PROBE is actualy -1

  //hier Test 
  #if ENABLED(G38_PROBE_TARGET)    && !(CORE_IS_XY || CORE_IS_XZ)  //&& PIN_EXISTS(Z_MIN_PROBE)
    // If G38 command is active check Z_MIN_PROBE for ALL movement
    
    if (G38_move) {
      UPDATE_ENDSTOP_BIT(Z, MIN_PROBE);
      
   SERIAL_ERRORLNPGM("update: G38_move reached"); 

      if (TEST_ENDSTOP(_ENDSTOP(Z, MIN_PROBE))) {
        if      (stepper.current_block->steps[_AXIS(X)] > 0) { _ENDSTOP_HIT(X, MIN); stepper.endstop_triggered(_AXIS(X)); }
        else if (stepper.current_block->steps[_AXIS(Y)] > 0) { _ENDSTOP_HIT(Y, MIN); stepper.endstop_triggered(_AXIS(Y)); }
        else if (stepper.current_block->steps[_AXIS(Z)] > 0) { _ENDSTOP_HIT(Z, MIN); stepper.endstop_triggered(_AXIS(Z)); }
        G38_endstop_hit = true;
      }
    }
  #endif    ........

I also found PIN_EXISTS(Z_MN_PROBE) means by this definition:

#define PIN_EXISTS(PN) (defined(PN ##_PIN) && PN ##_PIN >= 0)

Z_MIN_PROBE_PIN has to be defined and should be positiv or zero
There are a lot of definitions for Z_MIN_PROBE_PIN obviously depending on the Hardware used

My Motherboard is 
 #define MOTHERBOARD BOARD_RAMPS_14_EFB

My Procesor is Arduino Mega2560

Trying to find out how where "my" #define Z_MIN_PROBE_PIN is to be found.

**Comment by Edgar48** [comment]
finaly  I endet up finding that the Definition of Z_MIN_PROBE in ramps.h is not going tru to the Endstops::update routine. Don't know why. I changed Z_MIN_Probe to Z_MIN like this and it works.
I feel this is a quick and dirty solution. Maybe one of the Godfather of code here in MArlin know what to do with this Informations. Sorry I tried to contribute as good as it was possible with my small knodledge.

#if ENABLED(G38_PROBE_TARGET)    && !(CORE_IS_XY || CORE_IS_XZ) && PIN_EXISTS(Z_MIN)
    // If G38 command is active check Z_MIN_PROBE for ALL movement
        if (G38_move) {
     
      UPDATE_ENDSTOP_BIT(Z, MIN);
         
      if (TEST_ENDSTOP(_ENDSTOP(Z, MIN))) {
        if      (stepper.current_block->steps[_AXIS(X)] > 0) { _ENDSTOP_HIT(X, MIN); stepper.endstop_triggered(_AXIS(X)); }
        else if (stepper.current_block->steps[_AXIS(Y)] > 0) { _ENDSTOP_HIT(Y, MIN); stepper.endstop_triggered(_AXIS(Y)); }
        else if (stepper.current_block->steps[_AXIS(Z)] > 0) { _ENDSTOP_HIT(Z, MIN); stepper.endstop_triggered(_AXIS(Z)); }
        G38_endstop_hit = true;
      }
    }
  #endif

**Comment by Bob-the-Kuhn** [comment]
Sorry - been busy in the 32 bit branch.

This is the third or fourth time that the G38 logic has been broken. 

I spent a couple of hours looking at all the logic and ended up with a headache.

Hopefully I'll have a fix tested tomorrow.

**Comment by Bob-the-Kuhn** [comment]
Question - why do you have both UBL enabled and G38 enabled?

My understanding is that the bed leveling systems don't take into account the offsets that are usually generated when using G38.  

I could be out of date.  I haven't been paying much attention to Marlin 1.x.

**Comment by fiveangle** [comment]
Yeah, I looked at was like 🤷‍♂️

**Comment by Edgar48** [comment]
Thank you Bob the Kuhn:  Im using my self-designed 3D Printer also as pcb board cnc and CNC for foam. I have to touch the surface of the workpice and I thought g38.2 z would be helpfull. maybe I did not understand UBL completely but I find it very complicatated to define the UBL testspots just to touch the surface. Is there a way of using UBL defining manualy the spots to test by going there in xy direction?

**Comment by Bob-the-Kuhn** [comment]
Take a look at Issue #7972.  Fixing the G38 logic the correct way is a lot of work.  Looks like it'll be a while before I get comments on my proposal and have it ready for prime time.

I think your change is a good interim solution as long as the Z_MIN endstop is setup as ENDSTOP_INVERTING true (the way it is in your config files).

----

Follow Issue #7970 on using bed leveling and G38.  I expect that others have already come up with ways to use G38 with bed leveling.

**Comment by Edgar48** [comment]
@fiveangle : I didnt quiete understand your comment. What you are trying to say? As i'm new into Marlin and also new into Github maybe I'm not contributing the proper way. I just tried to explain my thoughts and show how I aproach the problem so that the experienced ones can give me hints where i'm thinking wrong or give me hints on the Structure of marlin. If i did not behave properly I want to excuse myself and would be more than happy if you or someone could give a starter like me a hint what and how I can do better. I find it marvelous what the conributers to Marlin have created and I realy want to contribute with my small skills as good as possible.

**Comment by fiveangle** [comment]
I looked at [the code]…

**Comment by fiveangle** [comment]
You explained yourself just fine !

It was the G38 code that was perplexing :)

**Comment by MxFrs** [comment]
Hey, are there any news on this topic? I'm trying to use G38.2 as well but have the same issue in Marlin 2.0.5.2. As I'm pretty new to Marlin Code I don't fully understand what the result of this is. I've seen some old Issues here like this one but somehow it still isn't working. 
I read a lot of comments using some kind of dirty way to make it running. If G38 still is known to be broken could you give a more detailed explanation on what to do to get this running? 

I really appreciate all of the amazing work that was done to get Marlin to what it is today!

**Comment by fiveangle** [comment]
This issue is closed so I'd open a new issue if you want it looked at.
