### ISSUE TITLE
Question: G28 Recovery

### ISSUE THREAD

**Issue by apballard** [MarlinFirmware/Marlin#7925]
Hi All, quick question.

I've been looking into the config and what not, and when I do a G28, because of the sensor offset from the actual nozzle, instead of probing at X150 Y100, it does more of a X150 Y88 and in that way the sensor is at the X150 Y100 location.

Is there an option to return the nozzle after the probing back to X150 Y100?

**Comment by Roxy-3D** [comment]
You can put an extra line into your Slicer's start up GCode to move it there.   A G1 X150 Y100.    But you can also pick the SAFE_HOMING coordinates.   You could pick a location offset by some amount to put the nozzle at the center of the bed.

But really...  Why do you care?   It probably is best to probe the center of the bed, and when you start printing your GCode file, the nozzle will move to where it is supposed to go.

**Comment by apballard** [comment]
@Roxy-3D Thanks for the reply.  It dawned on me that I did not mention that I do want it to probe the centre, but I then like to double check the z-offset at the probed point.  Not sure if this makes a difference.

**Comment by Roxy-3D** [comment]
Well...   At some point, you need to trust the configuration of your machine.   And...   Really...   the proof is in the pudding.   The whole purpose of having everything configured correctly is so you can print.   After a G28, you are ready to heat things up and print.

**Comment by apballard** [comment]
I agree, thanks
