### ISSUE TITLE
[FR] Pin Writes gCode

### ISSUE THREAD

**Issue by AcrimoniousMirth** [MarlinFirmware/Marlin#7932]
Hi all, 
       First off thanks to the awesome dev team for the work done to make this incredible software. Been using it for a long time now and love seeing the new updates roll in.
       My request is perhaps a bit selfish but I’m looking for a sort of reverse M42. I’m working on an integrated design for my university final project that I can’t say too much about but will be making opensource after graduating.
      Basically I need to easily send a command from a separate microcontroller to move to a specific X, Y and Z.
       I could use “Park position” by figures if mention this as it could be useful. What I suggest is: 
When not printing, if pin x written high, execute script.
       This in my case would park the nozzle and bed precisely where they need to be but could be used for other things such as button-settable heating presets and so on. If this feature already exists, my apologies, I haven’t seen it! But if it doesn’t I think it should be decently easy to implement (oops, my naivety is showing).
Thanks and keep being awesome!

**Comment by terryb58** [comment]
Can't you just send a G27 instead of having to mess with pins?  Or are you trying to communicate with Marlin from, let's say, OctoPrint on a Raspberry Pi without using gcode?

**Comment by thinkyhead** [comment]
An i2c interface would probably be more powerful and easier to implement. I've done just this sort of thing using the TWIBus class included with Marlin. See https://github.com/MarlinFirmware/Marlin/issues/4776#issuecomment-246262879 for the details.

**Comment by boelle** [comment]
@AcrimoniousMirth is this one still relavant?

**Comment by boelle** [comment]
wrong label

**Comment by InsanityAutomation** [comment]
This may be applicable to the discussion on input to trigger macro dealing with some hardware on the Dagoma printers. Basically another use case for the same function. Id tag it 2.1.

**Comment by thisiskeithb** [comment]
Added in https://github.com/MarlinFirmware/Marlin/pull/18389
