### ISSUE TITLE
Can't compile older Marlin with Arduino 1.8.4

### ISSUE THREAD

**Issue by fermin-diez** [MarlinFirmware/Marlin#7940]
> **_Arduino:1.8.4 (Windows 10), Tarjeta:"Arduino/Genuino Uno" C:\Users\fermi\AppData\Local\Temp\Temp1_Marlin-1.0.x.zip\Marlin-1.0.x\Marlin\Marlin.ino:33:27: fatal error: Configuration.h: No such file or directory #include "Configuration.h" ^ compilation terminated. exit status 1 Error compilando para la tarjeta Arduino/Genuino Uno. Este reporte podría tener más información con "Mostrar salida detallada durante la compilación" opción habilitada en Archivo -> Preferencias._**

**Comment by psavva** [comment]
Please download version 1.1.x which is the latest stable version and try again
