### ISSUE TITLE
G26 after G28 with safe home will try to print outside the bed.

### ISSUE THREAD

**Issue by Festivejelly** [MarlinFirmware/Marlin#7949]
------------------------------------------------------------
### Bug Report
- Description: The G26 validation print tries to print outside of the bed
- Expected behaviour: Prints a validation print inside of the allowed bounds
- Actual behaviour: Ignores current location and starts printing outside of the bed when it reaches the end.
- Assumptions: You already have a valid mesh
- Steps to reproduce:
  - Turn on safe Z homing in config
  - Do G28, which should home your nozzle in the middle of the bed
  - Do G26, which will start the mesh validation print and it ends up printing out of bounds
  - If you then scrape all that mess off and again do G28
  - Then do G28 X0 Y0
  - Then do G26 it prints inside of bounds.

**Comment by thinkyhead** [comment]
Does this issue still exist in the latest code — in the `bugfix-1.1.x` branch? If so, please re-open this issue.
