### ISSUE TITLE
  3.2 Inch MKS TFT28 V1.2 Full Color Touch Screen Support 

### ISSUE THREAD

**Issue by Radiu** [MarlinFirmware/Marlin#7958]
hi was wondering if marlin have suport for LCD MKS TFT28 V1.2 Full Color Touch Screen 
i see many people using with ramps 1.4, but i dont see on Config files nothing about that type of lcd

**Comment by fiveangle** [comment]
https://github.com/MarlinFirmware/Marlin/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20MKS%20TFT28

https://github.com/MarlinFirmware/Marlin/issues/6025
