### ISSUE TITLE
[FR] I2C bridge TMC2130

### ISSUE THREAD

**Issue by Grogyan** [MarlinFirmware/Marlin#7960]
I have been having a thought experiment on a [I2C to SPI](https://www.nxp.com/docs/en/data-sheet/SC18IS602_602B_603.pdf) bridge for the TMC2130.
Wondering if anyone else would like that feature?

This would enable a single bus to communicate with every driver.

The TMC2130, has quite a few neat features, that Josef Prusa has utilized in his I3 Mk3.
Downside is that you need a CS pin for every driver, and the SPI is in significant use anyways with the SD card.

**Comment by teemuatlut** [comment]
Sounds overly complicated just to save a few pins. I'd say that I've got more peripherals connected than most and even I'm not running out of pins yet.

> the SPI is in significant use anyways with the SD card

Doesn't matter as the TMC communication normally is done once only on startup.
