### ISSUE TITLE
2.7.16: Marlin fly-out on right side gets annoying

### ISSUE THREAD

**Issue by ScruffR** [MarlinFirmware/Marlin#7971]
When running mct 2.7.16 in Chrome on Win8.1 tablet the fly-out to select the respective settings tab keeps popping out and sliding back whenever I touch the screen to scroll the page or select an option.

Over time this gets somewhat annoying ;-)

Keeping it hidden till it's actively touched would be fine for me.

**Comment by Tannoo** [comment]
Umm.. I don't think whatever you are explaining has to do with Marlin as Marlin doesn't have any touch support.

**Comment by ScruffR** [comment]
Sorry, I just hit the Issues button in Marlin Configuration Tool 😳 and I didn't check which repo this linked me to 😊 
I was talking about this fly-out in Marlin Configuration Tool on my windows tablet with touch 
![image](https://user-images.githubusercontent.com/6604878/31573276-c926ab3a-b0b8-11e7-9c24-83921cc8bcb9.png)
I'll close here and open there.

Sorry!
