### ISSUE TITLE
Serial Syntax error, "Material heatup parameters", wrong formating

### ISSUE THREAD

**Issue by HailToDodongo** [MarlinFirmware/Marlin#7978]
### Bug Report
- Description:  "Material heatup parameter" info at startup has a wrong syntax
- Expected behaviour: 
`echo:Material heatup parameters:`
`echo:  M145 S0 H190 B60 F0  M145 S1 H240 B90 F0`
- Actual behaviour: ---
`echo:Material heatup parameters:`
`echo:  M145 S0 H190 B60 F0`
` M145 S1 H240 B90 F0`
- Steps to reproduce:
  - Start printer and watch the serial output

[The Line that is wrong](https://github.com/MarlinFirmware/Marlin/blob/f6f881f5ed954bc2f44ca64895b6af99e74265a2/Marlin/configuration_store.cpp#L1680)

From what i understand the "CONFIG_ECHO_START;" should be either placed inside the loop, or the "SERIAL_ECHOLNPAIR" should be replaced with "SERIAL_ECHOPAIR".

I have currently no way to change and test it myself, can someone check this out?
It makes it more difficult to parse the output from the serial port.

**Comment by thinkyhead** [comment]
Aaaaaaaaannnnnnnddddd………… It's fixed now.
