### ISSUE TITLE
Board GT2560 A+ wrong servo pin

### ISSUE THREAD

**Issue by dobryj** [MarlinFirmware/Marlin#7981]
### Bug Report
Header for board GT2560 A+ define wrong servo pin number when BLTOUCH is enabled.
In history geeetech boards until A+ revision don't have servo connector. Therefore it exist hack to use Z-max pin to this functionality. Problem is that this hack need HW modification to solder another connector on board. This is difficult for some users.
A+ board have new functionality with servo connector on pin 11 (arduino numbering). Therefore easiest way to connect BLtouch is connect it to this connector without any HW modification.
Problem is on accepted pull request https://github.com/MarlinFirmware/Marlin/pull/7769
This modification do not solve problem on boards until A+ and devastate solution prepared on PCB.
It is extremely strange.

Correct solution is this:
on file pins_GT2560_REV_A_PLUS.h remove dependency to ENABLED(BLTOUCH) and use simply
```
  # ifndef SERVO0_PIN
  #    define SERVO0_PIN 11 // original servo connector on A+ board
  # endif
```
on file pins_GT2560_REV_A.h
```
  # if !defined(SERVO0_PIN) && ENABLED(BLTOUCH)
  // HW modification needed 
  // see https://www.geeetech.com/forum/viewtopic.php?t=18713
  // see http://www.geeetech.com/blog/2016/09/how-to-use-3dtouch-auto-leveling-sensor-on-your-geeetech-prusa-i3/
  #    define SERVO0_PIN 32 // Z-max pin on board 
  # endif

```
This solution is more universal because allow to use old hack which is not needed now (if somebody want it). And this solution didn't break solution from factory.

Best regards, Jiri

**Comment by Phr3d13** [comment]
I can make these changes and shoot another PR, but I don't have BLTouch on my machine to test... Can anyone else confirm that this is what it should be (before I make another blind PR :) )?

**Comment by dobryj** [comment]
I have BLtouch connected on "servo connector" on GT2560 A+
It is really pin 11 (arduino numbering). I can confirm it.

**Comment by fiveangle** [comment]
@dobryj - Since you know intimately about this, perhaps you can submit PR with the pin change that also includes a warning in SanityCheck.h stating for user to double-check pin usage ( if BLTOUCH is enabled for this specific board (due to the community consensus problem you detailed above).

If you want to get even more user friendly, you can add a USE_SERVO_PIN_FOR_BLTOUCH option at the top of the board pins file, then put the redefine in a code block as you have later down in the pins.

**Comment by wittsan** [comment]
Hello,
I have a problem with the BLTouch and the last marlin.
_(But maybe it's a configuration problem for me)_
To make it work I have to reverse in pins_GT2560_REV_A_PLUS.h the numbers of the PINs

```cpp
#include "pins_GT2560_REV_A.h"

#undef BOARD_NAME
#define BOARD_NAME "GT2560 Rev.A +"

#if ENABLED (BLTOUCH)
   #define SERVO0_PIN 11 // 32
#else
   #define SERVO0_PIN 32 // 11
#endif
```
It only works like that for me.
On the GT2560 A +, it is the PIN11 which must be activated instead of 32. I think there is a reversal.

And dobryj says the same thing:

> I have BLtouch connected on "servo connector" on GT2560 A+
>It is really pin 11 (arduino numbering). I can confirm it.

Thank you

**Comment by FabLab-du-Don** [comment]
Il confirm : 
```
#include "pins_GT2560_REV_A.h"

#undef BOARD_NAME
#define BOARD_NAME "GT2560 Rev.A +"

#if ENABLED (BLTOUCH)
   #define SERVO0_PIN 11 
#else
   #define SERVO0_PIN 32 
#endif
```

**Comment by thinkyhead** [comment]
Patched! (again)

**Comment by mmpires** [comment]
I'm using this board on my UM clone so i did set the board to UM and i confirm that we must change the Servo Pin to 11 on UM Pins.

#define DEFAULT_MACHINE_NAME    "Ultimaker"
// Servos
`#define SERVO0_PIN       11    `

**Comment by mudmarron** [comment]
Hi guys,

I have a geeetech i3 printer. with a gt2560 rev a+ board. I have fitted the 3d touch. 

I have the 2 pin connector fitted to the z min stop, and the 3 pin fitted to the 3d touch part of the board.

I have checked with my multimeter and I think maybe this sensor is faulty.

When I turn the printer on it will do the test up and down but then nothing. When it goes to home the z axis it drives the extruder into the bed and none of the test commands (g code) respond to the sensor. 

I am completely new to this and if I can get some help that would be appreciated.

**Comment by titeuf9987** [comment]
Hi mudmarron ,

did you have any chance in this? I am currently facing the same issue...

Thanks.

**Comment by mudmarron** [comment]
No I didn't get it to work. I suspect a faulty sensor. I have decided to go back to the Z axis one and modify it to remove any slop in the system.

**Comment by titeuf9987** [comment]
Thanks for the answer.

On my side, I could finally make it work. 

The connections are:

1. on ZMAX: from top: brown, orange, red
2. on ZMIN (black on top)

I am attaching the files I modified, in case it can help ([Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2717041/Marlin.zip)).
