### ISSUE TITLE
Firmware retract - auto retract

### ISSUE THREAD

**Issue by Kenzu** [MarlinFirmware/Marlin#800]
Hey

I cannot get auto retract to work.
I have set #define FWRETRACT in configuration_adv.h
Put M209 S1 in my gcode

This is my retract settings
# ifdef FWRETRACT

  #define MIN_RETRACT 0.1                //minimum extruded mm to accept a automatic gcode retraction attempt
  #define RETRACT_LENGTH 2.5               //default retract length (positive mm)
  #define RETRACT_FEEDRATE 25_60         //default feedrate for retracting
  #define RETRACT_ZLIFT 0.1                //default retract Z-lift
  #define RETRACT_RECOVER_LENGTH 0       //default additional recover length (mm, added to retract length when recovering)
  #define RETRACT_RECOVER_FEEDRATE 15_60  //default feedrate for recovering from retraction
# endif

It does not detect retracts at all.

Thanks

**Comment by OhmEye** [comment]
I'm curious if this fix was fixed and if so which branch/commit it was. I just merged my own mods with current dev branch yesterday and FWRETRACT is working but if I use gcode without G10/G11 the autoretract seems to miss half or more of the retractions and I'm poking around the issues and commits as a first step looking into it. So I'm curious to know if there are indeed any current known issues with autoretract before I dig into it deeper.

**Comment by thinkyhead** [comment]
@OhmEye Autoretract is not on the radar at the moment. Post a new issue about it, I recommend. It sounds different from this issue, and we definitely want to keep an eye on things like this, especially if it might reveal an underlying problem. If you can isolate variables involved that will help a lot (whether affected by jerk, acceleration, or anything like that). But meanwhile please post about whatever you are able to figure out.
