### ISSUE TITLE
T parameter not working without argument

### ISSUE THREAD

**Issue by LVD-AC** [MarlinFirmware/Marlin#8013]
`parser.seen('T')` seems no longer to be working when no argument is passed (I guess since the introduction of the T-codes)

e.g.
- GXX T is not recognized while GXX T0 and GXX T123 are.
- GXX P1 T V0 C: P1 is recognized T, V0 and C are not
- GXX P1 T1 V0 C works fine

note: would be the same problem with `parser.seen('G')` and `parser.seen('M')`, but those are never used as parameters.

**Comment by Roxy-3D** [comment]
I was just using this yesterday and it worked as expected.    But I have #define FASTER_GCODE_PARSER turned on.   Do you have that disabled?

**Comment by LVD-AC** [comment]
I retested and the problem disappeared. Beats me... ???

**Comment by Roxy-3D** [comment]
I did make a change to my branch in one place of the UBL-G29 code to used the parsed value for map type.   I don't think this is what you are seeing, but it should insulate us from the parser.
```cpp
 g29_map_type = parser.intval('T');
```
Right now, the change is only at:  https://github.com/Roxy-3D/SD-Reselect-and-Print-v5   but it should be merged soon.

**Comment by LVD-AC** [comment]
Seems the trouble comes from (parser.h):
`  FORCE_INLINE static bool     boolval(const char c, const bool dval=false)   { return seen(c)    ? value_bool()         : dval; }
`
when using this without an argument **(seen(c) is true)**, it gives an undefined result **(value_bool() is undefined)** (and stops parsing further parameters !!!).
I suggest to change this to:
`
  FORCE_INLINE static bool     boolval(const char c)  { return seenval(c) ? value_bool()         : seen(c); }`

**Comment by LVD-AC** [comment]
See #8016 and #8017 (my troubles are over with this)

**Comment by Roxy-3D** [comment]
Yes...   It is already merged.    I just checked that it was in place because I did a new fork and if it wasn't in place...  I was going to add it to my fork.  (That way, it would get merged in the next day or two.)
