### ISSUE TITLE
 Autobed ​​level inverted correction on the X and Y axes

### ISSUE THREAD

**Issue by greg60greg** [MarlinFirmware/Marlin#8018]
Hello, sorry for English translator.
I have a problem with the autobed ​​level. The correction is applied upside down on the X and Y axes.
The correction taken on this site works:
https://plus.google.com/+MateuszPerlak/posts/XNpAhkCKPCE

    vector_3 pt1 = vector_3 (ABL_PROBE_PT_1_X, ABL_PROBE_PT_1_Y, -z_at_pt_1);
    vector_3 pt2 = vector_3 (ABL_PROBE_PT_2_X, ABL_PROBE_PT_2_Y, -z_at_pt_2);
    vector_3 pt3 = vector_3 (ABL_PROBE_PT_3_X, ABL_PROBE_PT_3_Y, -z_at_pt_3);

On the other hand, it only works on the three point system.
I am forced to comment AUTO_BED_LEVELING_GRID. But how does it work with the grid has nine points?

Thanks for telling me the fix this firmware is a perfect copy of mine but with unadjusted values. Just for my "test".

Thank you in advance.
[firmware.zip](https://github.com/MarlinFirmware/Marlin/files/1395985/firmware.zip)

**Comment by Roxy-3D** [comment]
> The correction is applied upside down on the X and Y axes.

You may not have your axis in the 'correct' direction.   You can try inverting the direction on X or Y and see if the bed leveling does the 'right' thing.

**Comment by greg60greg** [comment]
The machine is fully finished. I spent a lot of time doing it (one and a half years). I do not want to edit anything except the firmware.

If I invert my X and Y I should reverse the direction of the engines if I do not touch the endstop what would be the same.

I am currently looking at the code with my father and am looking for a solution.

Many people have already had the trouble but I found no answer apart for the debug of the three probing point.

**Comment by AnHardt** [comment]
Please look up "right handed coordinate system" and "left handed coordinate system".
To make work any kind of ABL you have to have a right handed. Lots of beginners are confused by this - especially when the bed is moving up and down instead of the nozzle.

**Comment by greg60greg** [comment]
Or can I see this parameter?

```cpp
#define INVERT_X_DIR false    // for Mendel set to false, for Orca set to true
#define INVERT_Y_DIR false    // for Mendel set to true, for Orca set to false
#define X_HOME_DIR 1
#define Y_HOME_DIR -1
```
You think that putting that parameter will solve my worries?
```cpp
#define INVERT_X_DIR true // for Mendel set to false, for Orca set to true
#define INVERT_Y_DIR true // for Mendel set to true, for Orca set to false
#define X_HOME_DIR -1
#define Y_HOME_DIR 1
```

**Comment by AnHardt** [comment]
No. There is no parameter.
You have to reverse an axis - and logically your max-endstop (on this axis) becomes a min and the other way around.

An other symptom of a left handed coordinate system is getting mirrored parts.

In our example configurations the 3 points are always defined counter clockwise. That can't be so bad.

```
  // 3 arbitrary points to probe.
  // A simple cross-product is used to estimate the plane of the bed.
  #define ABL_PROBE_PT_1_X 15
  #define ABL_PROBE_PT_1_Y 180
  #define ABL_PROBE_PT_2_X 15
  #define ABL_PROBE_PT_2_Y 20
  #define ABL_PROBE_PT_3_X 170
  #define ABL_PROBE_PT_3_Y 20
```

Ihe .zip file in the first message is empty.

**Comment by AnHardt** [comment]
When you are talking about `AUTO_BED_LEVELING_GRID` you are not using one of our recent versions. From where did you get it? When did you get it? What version?

**Comment by greg60greg** [comment]
I had mirror parts but following a reversal of X problem solved.

So if I do G29 with:
```cpp
  // 3 arbitrary points to probe.
  // A simple cross-product is used to estimate the plane of the bed.
  #define ABL_PROBE_PT_1_X 15
  #define ABL_PROBE_PT_1_Y 180
  #define ABL_PROBE_PT_2_X 15
  #define ABL_PROBE_PT_2_Y 20
  #define ABL_PROBE_PT_3_X 170
  #define ABL_PROBE_PT_3_Y 20
```
I would have clockwise? And if it is not the case I have to reverse as I quoted previously?

I attach the firmware sorry for the empty file and thank you again for your help.

For the latest firmware version normally.
[fIRMWARE.zip](https://github.com/MarlinFirmware/Marlin/files/1402921/fIRMWARE.zip)

**Comment by greg60greg** [comment]
Thank you the problem was the coordinate system.
I am trying to install the 1.1.6 marlin now.

Thanks again to all.

**Comment by ripp2003** [comment]
Hi, I've got the same problem : compensation of the bed is inverted.
I've got an Anet A8 with Anet board inside : I'm running 
*  Marlin 1.1.6 
*  3 point ABL

This printer is a leftHanded so, counterwise.....
Can you tell me how did you solve your problem because, I know it's relative to coordinate system but really don't know how to solve this...

Many thanks

**Comment by Roxy-3D** [comment]
> Can you tell me how did you solve your problem because, I know it's relative to coordinate system but really don't know how to solve this...

You can invert the direction of travel of either the X or Y axis.   By doing that, you will also need to change that axis endstop from Max to Min or vice versa.

**Comment by greg60greg** [comment]
Hello,
 I still have my worries. I'm trying to reduce my offsets. I reverse the X and Y and the minimum and maximum.
I printed with the reversed correction on the X and Y. I now have the impression that the Y is compensated upside down.
If I ever find the solution I will come and post it but I start to hope.

**Comment by ripp2003** [comment]
oK, thanks for the quick reply, I'm trying to invert my Y axe, and will post my result ;-)

Thanks to Roxy and Greg !!!

**Comment by ripp2003** [comment]
Here the variable I've modified to invert Y axe wich seems to be inverted:
->  Commented define USE_YMIN_PLUG
->  Commented out define USE_YMAX_PLUG
->  Y_MIN_ENDSTOP_INVERTING from true to FALSE
->  Y_MAX_ENDSTOP_INVERTING from false to TRUE
->  Y_HOME_DIR from -1 to 1

And now, Homing (G28) only center X Axe 
M114 tell me 
*  X = 45 (with offset probe (65) , it's 110 so OK)
*  Y = 155 (with offset probe (-45), it need to be 110 but is not.....

So I've modified the Y offset of nozzle probe  from -45 to 45 so from a negative value to a positve one : 

Now, Probing seems to works well (clockwise : when front of me, LEFT-DOWN then LEFT UP then RIGHT up then print) but, problem still persist, overcompensate at left and not really at right....

**Comment by greg60greg** [comment]
Try to reverse X and Y:
#define X_STEP_PIN 54
#define X_DIR_PIN 55
#define X_ENABLE_PIN 38
#define X_CS_PIN 53

#define Y_STEP_PIN 60
#define Y_DIR_PIN 61
#define Y_ENABLE_PIN 56
#define Y_CS_PIN 49

In :
#define Y_STEP_PIN 54
#define Y_DIR_PIN 55
#define Y_ENABLE_PIN 38
#define Y_CS_PIN 53

#define X_STEP_PIN 60
#define X_DIR_PIN 61
#define X_ENABLE_PIN 56
#define X_CS_PIN 49

and the pins for the endstop reverse X and Y. I had some improvement in doing that.

**Comment by ripp2003** [comment]
so with this mod, you use the X stepper driver for Y and the Y for X ? very strange, but I' will test

**Comment by ripp2003** [comment]
Hi, for now, I'm waiting for a ramps board so, I 'will make some test to see if, for me, it's an anet board bug

**Comment by greg60greg** [comment]
hello, yes that's right for X and Y. Let us know about the map but I do not think it will change. for my part I am waiting for a sensor that I would bring the maximum of the nozzle and I would try all the positions

**Comment by ripp2003** [comment]
I'll test this night but, what slicer do you use ? (most important question is height of first layer)
I use Simplify and 1st layer is set to 90% so very low, maybe this could be the problem.....
I compare with same model in Cura 15 and, first layer start at 0.200

**Comment by greg60greg** [comment]
I'm using Slic3R and simplify3D. My first layer is 0.3mm.

**Comment by greg60greg** [comment]
I resumed my tests. I brought the sensor closer to the offsets and put a sensor with a smaller one.
The problem is small but is still existent.
Before I varied from 0mm to 0.6mm of the plateau and now from 0.20 to 0.40 or so.

A question ripp2003 how much do you have of extruder informed in configuration. I wonder if I have two extruders if the autobed ​​does not average between the two or something else.

Still sorry for my English and I hope to find a solution.

**Comment by ripp2003** [comment]
Hi, sorry for the late reply but, I have received my ramps 1.4 3 days ago and just finished the assembly.... god this is a nightmare loooooool. 
For now, I've tested directly UBL and, I'm printing a third model successfully (no inverted no problem)

I'm printing models to fix the ramp on my anet and then, I' will try to go back to 3 points BL to see if everyhting's OK .

In my config, I've just one extruder, no more

**Comment by ripp2003** [comment]
I've try the ABL linear and for me,  no more problem.
I suspect a bug on my anet board or, misconfiguration (but really don't know what I was doing wrong) but now, with Ramps, I don't have any problem.

For now, I stay with UBL and BabyStep .
