### ISSUE TITLE
2.0 +1.1.6+bugfix MEMCOPY inverted arguments

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#8025]
@Roxy-3D @AnHardt @thinkyhead @Tannoo @tcm0116 
**I HAVE FOUND THE BUG , and it's a big BUG** 

Code bad written
Memcpy(destination , source )

Look a this 
`inline void set_current_to_destination() { COPY(current_position, destination); }`
Inversion in arguments
`inline void set_destination_to_current() { COPY(destination, current_position); }`
Inversion in arguments

1.1.6 is dead
2.0  dead too
It's why we have tons of issues ! Why M600 buggy and more

With this PR , i think many things will become right , or breaks if some have not sure code

@thinkyhead @Roxy-3D @Bob-the-Kuhn 

> set_destination_to_current()  **NOT WORKING** 

The issue is  '  set_destination_to_current() = COPY( = 'memcopy ' and memcopy need ' pointers ' , because of the array structure and not a single data or to be redeclared more closely , or anything i don't know with my six months of c++ in all my life 😢 
In motion.h i have modified like this and all becomes perfect
Before 
```
inline void set_current_to_destination() { COPY(current_position, destination); }
inline void set_destination_to_current() { COPY(destination, current_position); }
```
After
```
inline void set_current_to_destination() { COPY(&current_position, &destination); }
inline void set_destination_to_current() { COPY(&destination, &current_position); }
```
And pointers are transmitted
all works fine

**Comment by Roxy-3D** [comment]
current_position[] and destination[] are arrays.   And as such, they are passed as pointers.   So the & operator to get their address should not be needed.

Technically... by using just the name, you are actually doing a &current_position[0] and &destination[0]

**Comment by ghost** [comment]
Yes i know now , but it' doesn't work on 2.0 in M600 function
Destinations are not applied  
In set_current_to_destination() , all the array is transmitted not just one item ' Memcopy(destination, current) 
There is a confusion somewhere or may be the compiler
And it works so fine that all the code in M600 must be perfect because the old code was written with this issue and now , it shows no mercy

**Comment by AnHardt** [comment]
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/macros.h#L136

memcopy() needs pointers and gets them in both cases.
How about sizeof()?

> Application to arrays[edit]
See also: Wikibooks:C Programming/Pointers and arrays § sizeof
When sizeof is applied to the name of an array, the result is the number of bytes required to store the entire array. This is one of the few exceptions to the rule that the name of an array is converted to a pointer to the first element of the array, and is possible just because the actual array size is fixed and known at compile time, when the sizeof operator is evaluated.

**Comment by ghost** [comment]
inline void set_current_to_destination() { COPY(current_position, destination); }
inline void set_destination_to_current() { COPY(destination, current_position); }
Same allocation. .. " size of "disabled in this case ? No ?

**Comment by ghost** [comment]
Float array vs float array

**Comment by ghost** [comment]
I can give you a proof ...
Tomorrow i give you a test code  overloaded of serial echoes
You will see by yourself 
With and without "&"

**Comment by ghost** [comment]
Hey !!! I have seen the initial declaration of destination and current have only 2 items and not 4 .. x + y + z + e 

May be the compiler is assuming an array of 2 items 
I will try tomorrow

**Comment by ghost** [comment]
I think you have given me the explanation 
I test my code after boot .. and arrays are not filled

Destination have not  x y z or e datas 
Current too
If one if this two arrays are different  ... memcopy is down 

I will change declaration of destination and current with 4 item equal to zero to fill at max .
I'm sure this is a sizeof  bad trip ☺

**Comment by ghost** [comment]
But this ... not explain why it works with "&"

**Comment by AnHardt** [comment]
Can you point us to the location where only 2 elements are defined? All i can find are ether XYZE or NUM_AXIS - both is 4.

**Comment by ghost** [comment]
@Roxy-3D @AnHardt @thinkyhead @Tannoo @tcm0116 
**I HAVE FOUND THE BUG , and it's a big BUG** 

Code bad written
Memcpy(destination , source )

Look a this 
`inline void set_current_to_destination() { COPY(current_position, destination); }`
Inversion in arguments
`inline void set_destination_to_current() { COPY(destination, current_position); }`
Inversion in arguments

1.1.6 is dead
2.0  dead too
It's why we have tons of issues ! Why M600 buggy and more



With this PR , i think many things will become right , or breaks if some have not sure code

**Comment by AnHardt** [comment]
These functions/macros follow the logic `functionname(target, source)`, with the same order as in `target = source`. That's a very common scheme, the same scheme as in memcopy().

If something is going wrong with this functions, its the use of this function by some developers, ignoring the required order of arguments. It may help to remember the correct order by looking at the functions names - same order.

**Comment by AnHardt** [comment]
Maybe things would be more clear to you, if the function names are changed

set_current_**to**\_destination() -> set_current_**from**\_destination()
set_destination_**to**\_current() -> set_destination_**from**\_current()

At least if translated to my native language this is the same, because "Set target" is the *strong* part in this order.
There is no way to interpret the current wording as copy_target_to_source(). 

Even better would be to omit this redundant functions at all. Let's expand them to:

memcpy( target, source, min( sizeof( target), sizeof( source)));

That would be readable by any c-novis, knowing a bit about the standard libraries. Because of inlining they expand to this anyway, always and everywhere. But it's contrary to @thinkyhead 's philosophy of deepy hiding everything in functions/macros, so only Marlin experts, having looked up functions/macros -  definitions long/often enough to know them by heart, can read/use this code.

**Comment by Roxy-3D** [comment]
> These functions/macros follow the logic functionname(target, source), with the same order as in target = source. That's a very common scheme, the same scheme as in memcopy().

Agreed.  Changing the order is going to cause more confusion and problems than just leaving it alone.

> set_current_to_destination() -> set_current_from_destination()
> set_destination_to_current() -> set_destination_from_current()

I'm in favor of the change.   If there are no objections...   Let's make this change.

**Comment by ghost** [comment]
@Roxy-3D  make a simple batch and original files will no be impacted , i have tried it and it's perfect ,
Please leave original Names ..... Please ... because i'm writting code and i don't want to have a new view

set_current_to_destination  ----> set_current_to_destination2
set_destination_to_current -----> set_current_to_destination 
set_current_to_destination2 ----> set_destination_to_current

in 1.1.6 / bugfix 1.1.x / 2.0 👍

**Comment by Roxy-3D** [comment]
No...   People are pretty much used to the way it is.   And AnHardt is correct that the established order of parameters match the standard memcopy (strcpy) etc.      

We can put the 'from' in the name to make things much more clear.

**Comment by AnHardt** [comment]
Thanks @Roxy-3D.
That could be step 1.
Then one has to search for the not working parts of the code where, maybe, the wrong direction was used.
A **global** swap will, for sure, destroy more than it helps.

**Comment by ghost** [comment]
Yes it's a good idea for all that have already develloped some code , and this will avoid confusion 
If there are some new name , it's better to mix the old inverted names with our newest code that have the old inverted name 
LOLLL

Yes , to avoid a big crisis , it's better to change radically the names

**Comment by ghost** [comment]
I have made the PR and detailled explanation 
[Advanced Pausing - M600 fix , works fine now](https://github.com/MarlinFirmware/Marlin/pull/8040)

**Comment by ghost** [comment]
@AnHardt  A global swap is good , if the dev work alone , but in a git communauty .... This simple batch can make so many wasted time for so many people 
Changing name is radical , visible , easy to understand and to fix

**Comment by AnHardt** [comment]
A global renaming will just help to lower the likelihood someone assumes they do the opposite of what they do.
A global reversion of what they do, will mess up all the code, currently properly working, with this functions - will (maybe) help at the few places currently not working.

dot

**Comment by Roxy-3D** [comment]
Agreed.    A global change of names from the first to the second 
```cpp
set_current_to_destination() -> set_current_from_destination()
set_destination_to_current() -> set_destination_from_current()
```
is safe and potentially will help people.    But changing the order of parameters is guaranteed to cause huge problems.

@thinkyhead    If you have no objections....   I'll convert these names tomorrow.
