### ISSUE TITLE
Setting X_MIN_POS to a negative value?

### ISSUE THREAD

**Issue by gcormier** [MarlinFirmware/Marlin#8027]
When homed at the corner, 0,0, I have spare travel on my X axis. I want to put a brush there for nozzle wipe.

Is setting X_MIN_POS to -10 acceptable? From my side, it's easiest - no offsets or anything needed in slicer, no worries about ever printing outside the bed. (Slicer will never print below 0,0)

Thanks!

**Comment by fiveangle** [comment]
Yes.  That's exactly how it is supposed to be used.  In conjunction with the BED_SIZE parameters, it locates the movable/probable area (with probable areas beyond the bed available by manually hard-coding the probing limits).

-=dave

**Comment by gcormier** [comment]
Thanks @fiveangle ! And it will still respect the end-stops, so if I (stupidly) set X_MIN_POS to -100, it would stop sooner? (Let's say my bed starts at 20 offset from the X stop).

**Comment by Roxy-3D** [comment]
Sorry...   My touch screen thought I clicked close...

**Comment by gcormier** [comment]
Thought it was something I said :)

> // Travel limits (mm) after homing, corresponding to endstop positions.
> #define X_MIN_POS 0
> 

The comment in Configuration.h might need some changes. It doesn't necessarily correspond to end-stop positions. I could do a PR, basically suggesting that MIN_POS must be ideally somewhere between the edge of the bed and the end-stops, but also adding if it's beyond the end-stop, it will stop at the end stop... not sure if that 2nd part is true?

**Comment by Roxy-3D** [comment]
And some additional Sanity Checks would be wise.    The switch to X_BED_SIZE and Y_BED_SIZE wasn't done as transparently as it should have been done.   It broke a lot of the example Configuration.h files.

**Comment by gcormier** [comment]
Yeah.. I was worried about UBL, it talks about MIN_POS.. I think it should be fine however as I traced some of the header files and it's ok, UBL starts at some offset (1) for X and Y and moves to the max bed size.
