### ISSUE TITLE
Tevo Black Widow does not load at startup (1.1.6)

### ISSUE THREAD

**Issue by KeMpeRr** [MarlinFirmware/Marlin#8034]
### RC6

"The flight is normal"

But it is necessary to update the firmware

### 1.1.6

The printer does not start. 
Why? i do not know :/

**Comment by AnHardt** [comment]
If not you, how can we - with the provided information?
Config-files please. If possible the old and the new. 
What are the symptoms of "does not start"? Any activity on LEDs, display, comport, fans. motors?

**Comment by KeMpeRr** [comment]
Ok! 

[Marlin-1.1.6conf.zip](https://github.com/MarlinFirmware/Marlin/files/1402038/Marlin-1.1.6conf.zip)
[Marlin-RC6.zip](https://github.com/MarlinFirmware/Marlin/files/1402039/Marlin-RC6.zip)

**Comment by AnHardt** [comment]
Differences at:

POWER_SUPPLY
TEMP_SENSOR_0
TEMP_SENSOR_BED
???ENDSTOP_INVERTING block
...

stopped searching here.
Please have an other look into your new configuration files

**Comment by KeMpeRr** [comment]
I tried to correct all the inconsistencies in configuration.h
[Marlin-1.1.6conf2.zip](https://github.com/MarlinFirmware/Marlin/files/1402636/Marlin-1.1.6conf2.zip)

![img_20171021_024502](https://user-images.githubusercontent.com/29354002/31831606-707e1d34-b607-11e7-8a9a-5f1b353620dd.jpg)

¯\_(ツ)_/¯

**Comment by jannoke** [comment]
You don't have a display controller defined...
//
// RepRapDiscount Smart Controller.
// http://reprap.org/wiki/RepRapDiscount_Smart_Controller
//
// Note: Usually sold with a white PCB.
//
//#define REPRAP_DISCOUNT_SMART_CONTROLLER

This needs to be set.
