### ISSUE TITLE
NeoPixels with NEOPIXEL_STARTUP_TEST causes bootloop

### ISSUE THREAD

**Issue by nesalkiN** [MarlinFirmware/Marlin#8036]
### Bug Report
- Description: Using NEOPIXEL_LED (type NEO_GRB) with NEOPIXEL_STARTUP_TEST enabled, the printer bootloops. With NEOPIXEL_STARTUP_TEST disabled the printer boots and the colors work (including blue)
- Expected behaviour: LEDs should cycle colors on printer startup
- Actual behaviour: LEDs displays red, green and then the firmware reboots, nothing on the LCD. It never shows blue color.
- Steps to reproduce:
  - Enable NEOPIXEL_LED
  - Enable NEOPIXEL_TYPE   NEO_GRB
  - Enable NEOPIXEL_STARTUP_TEST

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1402670/Configuration.zip)

Not getting green at the end btw. Does Marlin look for some specific end gcode?

*Marlin 1.1.6 stable

**Comment by AnHardt** [comment]
Without having looked at the actual code:
Watchdog is already active but not refreshed in your long lasting (>3s) procedure.

**Comment by Tannoo** [comment]
I had the same.
I did this to mine (in `neopixel.cpp`) to make it work.

```
void setup_neopixel() {
  pixels.setBrightness(NEOPIXEL_BRIGHTNESS); // 0 - 255 range
  pixels.begin();
  pixels.show(); // initialize to all off

  #if ENABLED(NEOPIXEL_STARTUP_TEST)
    delay(2000);
    #if ENABLED(USE_WATCHDOG)
      watchdog_reset();
    #endif
    neopixel_set_led_color(255, 0, 0, 0, 255);  // red
    delay(2000);
    #if ENABLED(USE_WATCHDOG)
      watchdog_reset();
    #endif
    neopixel_set_led_color(0, 255, 0, 0, 255);  // green
    delay(2000);
    #if ENABLED(USE_WATCHDOG)
      watchdog_reset();
    #endif
    neopixel_set_led_color(0, 0, 255, 0, 255);  // blue
    delay(2000);
    #if ENABLED(USE_WATCHDOG)
      watchdog_reset();
    #endif
  #endif
  neopixel_set_led_color(0, 0, 0, 255, 255);    // white
}
```

**Comment by Tannoo** [comment]
Neopixel strip now looks like a disco when warming up any heater.
Neopixel strip is also now unreliable on color selections.

**Comment by AnHardt** [comment]
Someone promised this.
https://www.youtube.com/watch?v=YxvBPH4sArQ from about 1:46
Do you remember? :-(

**Comment by Tannoo** [comment]
Yup. Lol

**Comment by Tannoo** [comment]
I've changed this to what it should have been:

```
void setup_neopixel() {
  pixels.setBrightness(NEOPIXEL_BRIGHTNESS); // 0 - 255 range
  pixels.begin();
  pixels.show(); // initialize to all off

  #if ENABLED(NEOPIXEL_STARTUP_TEST)
    safe_delay(2000);
    neopixel_set_led_color(255, 0, 0, 0, 255);  // red
    safe_delay(2000);
    neopixel_set_led_color(0, 255, 0, 0, 255);  // green
    safe_delay(2000);
    neopixel_set_led_color(0, 0, 255, 0, 255);  // blue
    safe_delay(2000);
  #endif
  neopixel_set_led_color(0, 0, 0, 255, 255);    // white
}
```

**Comment by Xeroxxx** [comment]
I can confirm this happens for me too. LCD Display stays empty, LED cycles through green, red, off etc.

@Tannoo
Where I've to add this?

**Comment by Tannoo** [comment]
In `neopixel.cpp`.

**Comment by Tannoo** [comment]
It's not an addition... it's a change.

In the funtion `setup_neopixel()`, change all the `delay(2000)`'s to `safe_delay(2000)`.

**Comment by Tannoo** [comment]
That will insure all background processes keep processing.

**Comment by Xeroxxx** [comment]
Hmm...and this file can be found where?

Can't find the function in Marlin or NeoPixel Library.

**Comment by Tannoo** [comment]
Marlin/src/feature/leds/neopixel.cpp

**Comment by Xeroxxx** [comment]
Ahh okay this is 2.x. However search function of github does not work properly and I haven't been able to find the code.

Code for 1.1.x can be found in Marlin_main.cpp

**Comment by Xeroxxx** [comment]
Works great, are you going to push this to the repo? If you don't mind I can do this.

**Comment by Tannoo** [comment]
I can't push. I'm not that important. Lol

**Comment by Tannoo** [comment]
I can nudge.

**Comment by Xeroxxx** [comment]
gj :) 👍 

@Tannoo 
ssafe_delay?

Isn't it "safe_delay"?

**Comment by Tannoo** [comment]
Did I have a type-o?

**Comment by Xeroxxx** [comment]
I guess so.

**Comment by SCiunczyk** [comment]
Issue could be closed I think. There are PR fixing this.
