### ISSUE TITLE
Fix #7745 not working - please look at this!

### ISSUE THREAD

**Issue by w1ebr** [MarlinFirmware/Marlin#8055]
Description: --- Move x axis does not account for current tool in dual_x_carriage configuration
Expected behaviour: --- After selecting T1, an x axis move should move the second x carriage.
Actual behaviour: --- The carriage x location as shown on the LCD is correct, but a move x axis only moves the T0 carriage, regardless of the active tool.
Steps to reproduce:
Set the active tool to T1 (done via a custom menu)
Move the carriage on the x axis using the LCD menu
The wrong x carriage moves.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1433038/Configuration.zip)

#7745

**Comment by psavva** [comment]
Please use the template when reporting issues.  You must also provide your config files.

**Comment by thinkyhead** [comment]
We can re-open this issue if the problem still exists in the current `bugfix-1.1.x` branch.
