### ISSUE TITLE
Make pulse with different frequency

### ISSUE THREAD

**Issue by eeerfan** [MarlinFirmware/Marlin#8069]
Hi Dears
i try to use mksTB6600 step motor driver for my Z axis and Drv8825 step motor driver fo X&Y axises.
but apparently this two kind of driver works with different puls frequency.and now i want make two different puls,one of them for mks driver and another one for drv drivers. i want to now is it possible or no?
and if is possible how can i do it?

**Comment by thinkyhead** [comment]
Unlikely this will be implemented, as it only makes the core stepping interrupt unnecessarily complicated. Stepper drivers are cheap, and we recommend using a matched set.
