### ISSUE TITLE
[FR] using e1 pin as x pin

### ISSUE THREAD

**Issue by goker1** [MarlinFirmware/Marlin#8096]
hey guys! i have tevo tarantula classic. i have a problem with x pin on motherboard. so i want to use E1 pin for control x step motor. i try to change on configration.h file x pin to E1 pin but i couldn't. if you can do this for me i will be happy. :)

**Comment by Phr3d13** [comment]
An excerpt from the template you deleted to post this 'issue':
```
Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.
```

**Comment by goker1** [comment]
I added configration files. TEVO 3D Printer bord is  MKS Base V1.4 3D Printer Control Board With USB Mega 2560 R3 Motherboard RepRap Ramps1.4 Compatible. so i don't know which configration file is correct, i added 3 of them. thank you so much.

[New folder.zip](https://github.com/MarlinFirmware/Marlin/files/1416913/New.folder.zip)

hey guys! i have tevo tarantula classic. i have a problem with x pin on motherboard. so i want to use E1 pin for control x step motor. i try to change on configration.h file x pin to E1 pin but i couldn't. if you can do this for me i will be happy. :)

**Comment by Phr3d13** [comment]
I'll take a look next time I'm in front of my computer

**Comment by thinkyhead** [comment]
If you want to make this kind of customization, change the pins in your board's pins file so that the X stepper pins use the E1 pin numbers. This is not something you can do from your configuration.

**Comment by marcio-ao** [comment]
I second @thinkyhead's suggestion. We remap stuff all the time in "pins__boardname_.h"
