### ISSUE TITLE
[FR] Printer wait, I applying the glue on the bed.

### ISSUE THREAD

**Issue by cedcaz** [MarlinFirmware/Marlin#8116]
Hello,
I haven't LCD screen (an old computer with Linux and Repetier-Host pilots the printer).
But I would want to use the M0 command with a switch button.
-M28 etc... (Preparation of the printer, Bed temperature ok...)
-M0 printer waiting for me to spread the glue on the bed.
-When I'm finished applying the glue I click on the button and the printer starts its work
My question: how to activate M0 without LCD screen? On what pins of Ramps 1.4 to connect the switch?

**Comment by mcmatrix** [comment]
Simple workaround is to use wait or delay.
http://marlinfw.org/docs/gcode/G004.html
Insert into your start script.
For example. (Check needed gcodes from docs).
....
Beep
Wait a minute or two
Beep
....

**Comment by cedcaz** [comment]
Ok, that's not true what I wanted, but it's actually the simplest solution. Thank you mcmatrix

**Comment by mcmatrix** [comment]
There’s also a pin state wait gcode
http://marlinfw.org/docs/gcode/M226.html
If you have any unused endstop pins or actually any digital pin will work.

For example, cheap endstop switch
https://m.aliexpress.com/s/item/32549454222.html?trace=storeDetail2msiteDetail

Connect it to unused endstop pins, find what is the needed pin number and use gcode to wait until you click that endstop

**Comment by mcmatrix** [comment]
Any arduino button module will work too.
Search module from google.
Just find right pins (signal, +5v, ground) from board.

**Comment by cedcaz** [comment]
YES! that's exactly what I was looking for. BIG thank you

**Comment by mcmatrix** [comment]
I'm glad it helped. You can close this issue.
