### ISSUE TITLE
problem in LCD 2004

### ISSUE THREAD

**Issue by ahmedpowera** [MarlinFirmware/Marlin#8125]
hi
i have problem in this version , when i do compile source code , the software give me good but the LCD not show any data why
i have LCD 2004
thank you

**Comment by Tannoo** [comment]
Don't know what version and you didn't post your config files.

Likely the display used was not specified in `Configuration.h`.

**Comment by ahmedpowera** [comment]
this code
#define REPRAP_DISCOUNT_SMART_CONTROLLER
now it show bad symbole in lcd
why

**Comment by ahmedpowera** [comment]
![img_20171028_004944](https://user-images.githubusercontent.com/33166752/32128919-2ef0ac06-bb7a-11e7-9108-92c4040baa0d.jpg)

**Comment by Tannoo** [comment]
Idk. Follow the issue template.

**Comment by Tannoo** [comment]
Could be a bad display, bad cables / connectors, bad breakout board, or bad controller.

If sofware... bad config is most likely.

**Comment by Tannoo** [comment]
A not yet supported controller is another option.

**Comment by ahmedpowera** [comment]
i was solve this problem thank you
but the heat extruder and fun extruder not work
not heating
