### ISSUE TITLE
1000 issues ... Let's PARTY !!

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#8132]
It's just to party about the thousandth issue !

Enjoy !!

**Comment by thinkyhead** [comment]
Consider yourself censured. Please cut down on the crack, meths, and caffeine.

**Comment by ghost** [comment]
You learn me c++ , but you need i learn you HOW TO LAUGH sometimes 😄 
May be , you need an algorythm because not implemented in your brain mdrrrrrrrrr

You work every day , all the time ,  humor is your regeneration !  Try it !!! I'm sure this will be good for you
