### ISSUE TITLE
Filament change loading Bug

### ISSUE THREAD

**Issue by Nuttavoot** [MarlinFirmware/Marlin#8140]
### Bug Report
- Description: When using Filament change, the filament unload fine but re-load length is shorter than the specify value. 
- Expected behaviour: Filament change re-load lenght 600mm
- Actual behaviour: Filament change re-load only about 50mm
- Steps to reproduce:
  - Preheat hot end
  - Select Filament change
  - Wait until unload done
  - Insert filament when prompt

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1424845/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/1424846/Configuration_adv.zip)

**Comment by AnHardt** [comment]
`FILAMENT_CHANGE_UNLOAD_FEEDRATE` too high?

**Comment by Nuttavoot** [comment]
No problem with filament unload, re-load is the problem.

**Comment by AnHardt** [comment]
FILAMENT_CHANGE_LOAD_FEEDRATE too high?
Also check the other values near that. (Configuration_adv.h)

**Comment by tcm0116** [comment]
The 50 mm is from your `ADVANCED_PAUSE_EXTRUDE_LENGTH` value. `M600` should first load the `FILAMENT_CHANGE_LOAD_LENGTH` at the `FILAMENT_CHANGE_LOAD_FEEDRATE`, and then the `ADVANCED_PAUSE_EXTRUDE_LENGTH` at the `ADVANCED_PAUSE_EXTRUDE_FEEDRATE`. The idea is to get the filament to the hot end quickly, but then slow down for the last bit. In your case, it appears to be skipping the first part of the load operation.

On your LCD, are you seeing the "Wait for filament load" or "Loading..." message followed by the "Wait for filament extrude" or "Extruding..." message, or just the extruding message when it's loading the filament?

Can you try manually running `M600` from the terminal with the L parameter? For example, `M600 L500` should cause it to load 500 + `ADVANCED_PAUSE_EXTRUDE_LENGTH ` mm after the unload.

**Comment by Nuttavoot** [comment]
Yes, skipping the load operation that is what I am thinking. Will try to follow your advice, thanks.

**Comment by Nuttavoot** [comment]
Got it sorted out, the problem are these 2 settings in "configuration.h"; 

#define PREVENT_LENGTHY_EXTRUDE
#define EXTRUDE_MAXLENGTH 1250

I have to increase "EXTRUDE_MAXLENGTH" from 1000 to 1250 for it to work properly. The magic number 1250 came from summing up FILAMENT_CHANGE_UNLOAD_LENGTH + FILAMENT_CHANGE_LOAD_LENGTH + ADVANCED_PAUSE_EXTRUDE_LENGTH
and in my case it is 600+600+50 = 1250

**Comment by tcm0116** [comment]
I believe that's a bug. Each one of those movements should be considered unique so far as `EXTRUDE_MAXLENGTH` is concerned.

**Comment by Nuttavoot** [comment]
OK, reopen it.

**Comment by tcm0116** [comment]
@Nuttavoot Do you know if you have volumetric extrusion enabled when you were having this issue?

**Comment by Nuttavoot** [comment]
@tcm0116 No, I have not done any changes to it.

**Comment by tcm0116** [comment]
I did some testing last night, but I was unable to replicate this using the
latest bugfix-2.0.x. I did find some issues associated with volumetric
extrusion and flown rate, so I've submitted some fixes for those.

**Comment by epoxi** [comment]
I could verify this on 1.1.6. The load filamet lenght is ommited. 

I have a bowden setup with 700mm tube (plus 50mm hotend), with the EXTRUDE_MAXLENGTH defined to 725mm.

**Comment by tcm0116** [comment]
@epoxi can you try using bugfix-1.1.x to see if the problem remains?

**Comment by Hesi-Re** [comment]
This problem continues with Marlin 2.0.2. Change filament option in LCD works well (650 unload /600 load) , but with M600 printer unloads correctly but only loads about 550 mm of filament.
