### ISSUE TITLE
extruder can't work

### ISSUE THREAD

**Issue by ahmedpowera** [MarlinFirmware/Marlin#8154]
hi
i have extruder with fan not work
i dont now why maybe the confugiration
i have this version framware
Marlin-1.1.x
thank you

**Comment by thinkyhead** [comment]
Try asking for help here: http://forums.reprap.org/list.php?415

**Comment by boelle** [comment]
@ahmedpowera use latest bugfix 2.0 and Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by Phr3d13** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
