### ISSUE TITLE
Printing thinking so much

### ISSUE THREAD

**Issue by mikko70** [MarlinFirmware/Marlin#8163]
My own build printer keep long waitings when print this part. I try check, if problem is Marlin, Cura or my printer.
Is small part between linear rail and linear screw , no take normally long time print. 
Can anybody confirm problem or no problem. (Everybody can use it, linear rail is installed stepper bracket and x movement happen between this part and linear rail)
 i use Marlin 1.16, 0.3mm nozzle, 1.75mm PLA and cura 3.03, freecad 0.17
note temp is high (245), because my sensor has error. Please change your own.

https://filebin.ca/3fa0n6FNXaWd/OT_pidsimple.gcode

**Comment by thinkyhead** [comment]
The top print speed (120mm/s) might be a little high depending on your machine. Try re-slicing with a lower print speed. I'm not sure otherwise what might be leading to "long waitings." Do you mean that there are long pauses between some moves, or do you mean that everything just moves too slowly?

**Comment by mikko70** [comment]
It do 1mm, think 10sec, do couple mm and thinking long time again etc. until start do longer area.
I investigated it, marlin can't handle small rounds. (Maybe cura problem, i have read it can do smaller routes than printer can do.)
I fixed problem after fix item dimensions bigger holes etc.  Maybe marlin need some error handling or warning message if it can't hande things? 

Yes 120 is too big, i test my printer  limits :), 100 start do sometimes missing steps.
It not my printer problem, it is Marlin route calculation problem, maybe no enought brain power (arduino mega)

**Comment by mikko70** [comment]
Video show problem, 
https://1drv.ms/v/s!AnWG6o77egjrhJgHdnAG3eKw5EdAcA

**Comment by thinkyhead** [comment]
> Maybe marlin need some error handling or warning message if it can't hande things?

Too many diagnostics, too much processing, even slower performance. It seems to me that Marlin is telling you there is a problem in very plain terms. 😉 

I agree with your theory. Cura is creating lines far below the threshold that Marlin will do by default. However, you can try lowering `MIN_STEPS_PER_SEGMENT` from the default 6 to 0 and see if it eliminates the pauses.

**Comment by mikko70** [comment]
Sorry, i have deleted old cad design.

But if you want test i used Freecad 0.17 and when design was ready, select all from image or make union and export to .OBJ file.
And this file drag in CURA
My fault bore was 1,5 mm i think this cause problems, before this i was part of sphere what caused similar problems. Or if item contain 0.1 fillet.


where MIN_STEPS_PER_SEGMENT can found ?

What marlin do when it thinking? if it not do anything, maybe timeout and faster skip.

**Comment by mikko70** [comment]
i think it is same problem than
https://github.com/MarlinFirmware/Marlin/issues/3981

Hanging start after brim.
Brim prints fine.
[O0_medium_flake_2.zip](https://github.com/MarlinFirmware/Marlin/files/1463977/O0_medium_flake_2.zip)


EDITED:

This bug seems be so long when Marlin has been.

http://forums.reprap.org/read.php?4,161124,174248

2012: "with marlin I noticed the printer would slow down on some portions of models with large numbers of polygons. The printer would also crash intermittently with a line number error and this would occur more frequently the more complex the model I tried to print. I then tried repetier and this gave print quality similar to marlin, but the printer no longer slowed down on complex prints and crashed much less frequently.."

**Comment by thinkyhead** [comment]
Can you provide any concrete information that can be used to narrow down the issue? Theories and references to 5-year-old issues are of little utility.

**Comment by boelle** [comment]
@mikko70 do you still have an problem with latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
