### ISSUE TITLE
problem in extruder

### ISSUE THREAD

**Issue by ahmedpowera** [MarlinFirmware/Marlin#8164]
hi
the extruder doesnt work am using D10 it not heating
but when i test them with converter it work
the problem D10 not have power
and when i want to preheat it give to me a message is "Err:MAXTEMP printer halted please reset"
in the info screen it write tempurature are "330/0"

**Comment by mikko70** [comment]
Have your temp sensor working ?  Maybe it is short circuit and you change low temp level 15->0?

enable it in configuration.h
```cpp
#define TEMP_SENSOR_0 11
#define TEMP_SENSOR_1 0
#define TEMP_SENSOR_2 0
#define TEMP_SENSOR_3 0
#define TEMP_SENSOR_4 0
#define TEMP_SENSOR_BED 11
```

**Comment by ahmedpowera** [comment]
sensor are work but it give maxtemp
maybe from the option

**Comment by ahmedpowera** [comment]
it change to 834-838 temp
and when i write -1   #define TEMP_SENSOR_0 -1
it give 4-7
i was trying all option and get -90,120,898,578,468,925,658,...
it give crazy number
maybe my ntc not found in this options
like this in aliexpress
3D V6 3D Printer long distance J-head&Single Cooling Fan

**Comment by thinkyhead** [comment]
If you don't know which `TEMP_SENSOR_0` value to use, you can use trial-and-error. After each re-flash of the firmware check that the reading is correct. Somewhere between 20-30 at room temperature.

**Comment by ahmedpowera** [comment]
am trying all option but same problem it give like 892 and other 458 ...
it hight why
i need to change thermistortable_5.h file to my thermistor
how can i to do this

**Comment by ghost** [comment]
Try the sensor on another pin 
try another resistor
Verify if it's sensor or hardware
Use Pins that have not soldererd pull resistor
verify if not short circuit betwen wires of resistor ' very known problem'
Verify if short circuit witch hotend connected to ground
verify ' if resistor ' , if you have 5v when not connected ' pull resistor is needed to supply the resistor '

verify in the name of the pin is really the good value
You must know what is the problem , hardware or software
Make all ' school ' test
and only after you can find

**Comment by ahmedpowera** [comment]
i use T0 pins not work
