### ISSUE TITLE
Feature Request: Tool-change via LCD-Menu

### ISSUE THREAD

**Issue by JamesT42** [MarlinFirmware/Marlin#818]
Hi!

I have a machine with 3 extruders and it would be really nice to extrude something from the 2nd and 3rd extruder (via movement of E) with only the LCD.
So a menu item to change the current tool qould be very cool.

I'm unfortunately not skilled enough to implement that my myself alone. But I would appreciate some pointers on how to do that. (Editing ultralcd.cpp probably?)

**Comment by kharar** [comment]
You could probably write a .gcode file with just "T1" in it and drop it onto your sdcard.

**Comment by boelle** [comment]
Given that there has not been much interest in this one i will close it

if you want to print an allready sliced object just with another extruder the better option is to reslice it... i guess that adding a feature like this would add more complexity than you gain from it

**Comment by JamesT42** [comment]
That is definitely not the feature I had in mind! I want this for the LCD-Menu so you can better prepare the printer, like changing the filament on several extruders and extruding something to test the nozzle etc.
This would be a few lines of code! Nothing more.

**Comment by kharar** [comment]
I have a subdir containing a set of files named T0.gcode T1.gcode and
T2.gcode, their only content is T0, T1 and T2 respectively.
Then I have another set of files handling load and unload of a bowden
extruder...
This effectively works as LCD-menu tool-change-commands provided that the
remaining gcode files does not execute any tool-changes themselves..

I have put the stuff on Thingiverse: http://www.thingiverse.com/thing:795664

2015-04-27 13:43 GMT+02:00 JamesT42 notifications@github.com:

**Comment by thinkyhead** [comment]
@kharar Yes, having GCode for common tasks is a good thing. I have "Load.gcode", "Eject.gcode", and "Center.gcode" in the "Utility" folder on my SD card, and I use them fairly often. I even have a couple of files to set the steps-per-mm when I need to swap extruders. Some options, such as load, eject, and filament change can be improved by making them into interruptible interactive menu items, but as long as the load / eject gcode does many small moves they can be stopped midway.

Related to this issue, I was brainstorming on the idea of having a GCode that you could use to create your own menu items. Something like this would be useful, but would need to have a fixed limit on the buffer size:

```
M430 ; Start recording GCode
G28 ; home
G1 X100 Y100 ; move to center
M431 Center ; Make a "Center" menu item with the preceding gcode.
```
