### ISSUE TITLE
Error compiling 'PROPORTIONAL_FONT_RATIO' was not declared in this scope

### ISSUE THREAD

**Issue by knotbeerdan** [MarlinFirmware/Marlin#8194]
### Compile Error

'PROPORTIONAL_FONT_RATIO' was not declared in this scope

I am attempting to update from version 1.1.0 and I have made all the changes required in my configuration.h and configuration_adv.h files. The last error that I have is 
```
> PROPORTIONAL_FONT_RATIO was not declared in this scope.
```

The error is on the serial.cpp file. I saw another issue where they added `#define PROPORTIONAL_FONT_RATIO 1.0`

If I do the same then I can compile without any issues, though I wanted to know if there was something else wrong.

I am using Arduino IDE Version 1.8.5(latest) and have tried 1.8.3 with the same results.

**Comment by psavva** [comment]
To which version are you using to?
Can you please post your config files?

**Comment by AnHardt** [comment]
Don't copy old config files into newer versions of Marlin!

 https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Configuration_adv.h#L1266-L1274

**Comment by thinkyhead** [comment]
Add this line to your `Configuration_adv.h` so you can get a different error on the next compile…
```cpp
#define PROPORTIONAL_FONT_RATIO 1.0
```
It may help to use a "diff" tool to compare your old config and the newest configuration files side-by-side, to make sure you have all settings. Better yet, start with the new config files and then make the needed changes from your old configurations.
