### ISSUE TITLE
[FR] Re-ARM UART to USB host bridge

### ISSUE THREAD

**Issue by Grogyan** [MarlinFirmware/Marlin#8195]
Re-ARM has a UART brekout that is otherwise unused, and with the issues relating to long, and unshielded, ribbon cables for external SD card comms.
Suggest as an alternative, that gcode loading and running be done from an thumb drive connected to a UART to USB converter connected to this port.

**Comment by AnHardt** [comment]
You'll need a usb-host in between of the both usb-devices. How about a Raspberry PI? :-(

**Comment by Grogyan** [comment]
Just a USB host controller connected to the UART is all the that should be needed to communicate with a flash drive

**Comment by Grogyan** [comment]
Such break out boards a somewhat common.  
Here is one [USB Host Breakout](http://www.hobbytronics.co.uk/usb-host-board-v2) that I found

**Comment by boelle** [comment]
is this a marlin problem??

**Comment by sjasonsmith** [comment]
This is an old request, and seems to be superseded by the popularity of serial-connected TFT displays which have their own SD and USB connections.

In addition, the referenced module seems to be no longer available.

I am going to close this as no longer relevant, but please reply with further explanation if you disagree.
