### ISSUE TITLE
 First pull request - help wanted

### ISSUE THREAD

**Issue by stuartmp** [MarlinFirmware/Marlin#8203]
#8133
 
Hi All,

This is my first post.
I wanted to add another predefined material to the preheat options
I managed to modify the code and get it working.

However when I try and submit my pull request and the system runs its checks it tells me that

`PREHEAT_3_TEMP_HOTEND`, `PREHEAT_3_TEMP_BED` and `PREHEAT_3_FAN_SPEED` are not defined

However I can clearly see that they are

They are defined right under the preheat 1 and preheat 2 variables

...
```cpp
#define PREHEAT_3_TEMP_HOTEND 250 
#define PREHEAT_3_TEMP_BED 80 
#define PREHEAT_3_FAN_SPEED 0// Value from 0 to 255
```
Please help me out or give me some guidance on how to solve the issue.

I did try replacing the variables in the configuration_store.cpp with static values and the code check out ok. 

So it appears to be just the fact that the system checker thinks the variables are not defined.

Not sure what to try next.

```
### Compile Error
When I compile with `FEATURE_X` I get an error:
Picked up JAVA_TOOL_OPTIONS: 

Loading configuration...
Xlib:  extension "RANDR" missing on display ":1.0".
Initializing packages...
Preparing boards...
Verifying...
sketch/configuration_store.cpp: In static member function 'static void MarlinSettings::reset()':
configuration_store.cpp:1254: error: 'PREHEAT_3_TEMP_HOTEND' was not declared in this scope
  lcd_preheat_hotend_temp[2] = PREHEAT_3_TEMP_HOTEND;
                               ^
configuration_store.cpp:1258: error: 'PREHEAT_3_TEMP_BED' was not declared in this scope
  lcd_preheat_bed_temp[2] = PREHEAT_3_TEMP_BED;
                            ^
configuration_store.cpp:1262: error: 'PREHEAT_3_FAN_SPEED' was not declared in this scope
  lcd_preheat_fan_speed[2] = PREHEAT_3_FAN_SPEED;
                             ^
exit status 1
'PREHEAT_3_TEMP_HOTEND' was not declared in this scope
```

**Comment by thinkyhead** [comment]
Please give a link to your branch on Github. I'll download it, patch the error, and submit a PR to your branch.

**Comment by stuartmp** [comment]
https://github.com/stuartmp/Marlin

Thank you scott.

On 2 November 2017 3:17:27 PM AEST, Scott Lahteine <notifications@github.com> wrote:
>Please give a link to your branch on Github. I'll download it, patch
>the error, and submit a PR to your branch.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/issues/8203#issuecomment-341320188

-- 
Sent from my Android device

**Comment by thinkyhead** [comment]
Which branch are you working with?
![image](https://user-images.githubusercontent.com/698003/32311344-2360df92-bf66-11e7-90a1-2cbfb29ce03c.png)

**Comment by thinkyhead** [comment]
Looks like you've been modifying the 1.1.x branch. Note that if you want to submit a PR in future, you'll need to apply all changes to a copy of the `bugfix-1.1.x` branch.

**Comment by stuartmp** [comment]
I believe that it is 1.1x




On 2 November 2017 3:38:47 PM AEST, Scott Lahteine <notifications@github.com> wrote:
>Which branch are you working with?
>![image](https://user-images.githubusercontent.com/698003/32311344-2360df92-bf66-11e7-90a1-2cbfb29ce03c.png)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/issues/8203#issuecomment-341322787

-- 
Sent from my Android device

**Comment by stuartmp** [comment]
Ok. Thank you. I  did not know that as I am just starting out with github.com 

On 2 November 2017 3:39:59 PM AEST, Scott Lahteine <notifications@github.com> wrote:
>Looks like you've been modifying the 1.1.x branch. Note that if you
>want to submit a PR in future, you'll need to apply all changes to a
>copy of the `bugfix-1.1.x` branch.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/issues/8203#issuecomment-341322946

-- 
Sent from my Android device

**Comment by thinkyhead** [comment]
It compiles fine for me. Sometimes with Arduino IDE it may help to close and re-open the project, if it doesn't notice your edits.

**Comment by stuartmp** [comment]
Have a look under commit notes and you will see what I tried. 

On 2 November 2017 3:39:59 PM AEST, Scott Lahteine <notifications@github.com> wrote:
>Looks like you've been modifying the 1.1.x branch. Note that if you
>want to submit a PR in future, you'll need to apply all changes to a
>copy of the `bugfix-1.1.x` branch.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/issues/8203#issuecomment-341322946

-- 
Sent from my Android device

**Comment by thinkyhead** [comment]
Enabling lcd to recompile and test some more…

**Comment by thinkyhead** [comment]
Again, compiles ok.

**Comment by stuartmp** [comment]
Yes it compiles ok in the Arduino IDE but I am unable to submit a pull request.

When I submit the pull request the system  runs a check. That fails.

If you look under the pull requests for 1.1.x you will see some about new pre heat option added.



On 2 November 2017 3:45:02 PM AEST, Scott Lahteine <notifications@github.com> wrote:
>It compiles fine for me. Sometimes with Arduino IDE it may help to
>close and re-open the project, if it doesn't notice your edits.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/issues/8203#issuecomment-341323587

-- 
Sent from my Android device

**Comment by thinkyhead** [comment]
> Yes it compiles ok in the Arduino IDE

For me too.

> I am unable to submit a pull request.

The presence of a compile error won't prevent submitting a PR. (I do it all the time.)

In any case, you won't be able to submit a PR with that branch, regardless. It will be rejected. You'll need to rebase the changes onto `bugfix-1.1.x` before submitting a PR.

**Comment by thinkyhead** [comment]
The above commit references this issue so we can see it undergoing Travis CI tests. That should reveal where any errors lie.

Side-note: There's no need to add a 3rd preheat option if you only tend to use two materials.

**Comment by stuartmp** [comment]
Thank you Scott I will give that a try.

What do I do with the current PR. Do I Delete it some how? 

On 2 November 2017 3:52:05 PM AEST, Scott Lahteine <notifications@github.com> wrote:
>> Yes it compiles ok in the Arduino IDE
>
>For me too.
>
>> I am unable to submit a pull request.
>
>The presence of a compile error won't prevent submitting a PR. (I do it
>all the time.)
>
>In any case, you won't be able to submit a PR with that branch,
>regardless. It will be rejected. You'll need to rebase the changes onto
>`bugfix-1.1.x` before submitting a PR.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/issues/8203#issuecomment-341324524

-- 
Sent from my Android device

**Comment by stuartmp** [comment]
Yes its the Travis CI tests that fails it says that there is un declared variables when infact they are defined.

I use 3 material all the time. So its helpful for me to have this option 


On 2 November 2017 3:57:28 PM AEST, Scott Lahteine <notifications@github.com> wrote:
>The above commit references this issue, so we can see it undergoing
>Travis CI tests. That should reveal where any errors lie.
>
>Side-note: There's no need to add a 3rd preheat option if you only tend
>to use two materials.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/issues/8203#issuecomment-341325213

-- 
Sent from my Android device

**Comment by thinkyhead** [comment]
I found that it was quite easy to rebase it onto 1.1.x using `git cherry-pick` but I won't insist you go down that path. If you're curious, I first used `git rebase -i upstream/1.1.x` to squash all commits down to a single commit. Then I did `git reset --hard upstream/bugfix-1.1.x` to reset the branch to `bugfix-1.1.x`, and finally, I did a `git cherry-pick 5557f89` to take that single squashed commit and apply it onto the branch. The result, your changes applied to the latest `bugfix-1.1.x` code.

Since I've done all the work already, you can just create a new branch based on `bugfix-1.1.x` to start with, then download my branch at https://github.com/thinkyhead/Marlin/tree/stuart_fixup, copy the changed files into your branch, and create a shiny new commit.

Changed files are…

![image](https://user-images.githubusercontent.com/698003/32312105-e4950fa0-bf69-11e7-8e93-1bfb95626222.png)

**Comment by stuartmp** [comment]
Wow... Thank you Scott. I can see that your skills and knowledge of Github are right up there. I would love to lean some more but find it difficult to source good material online that doesn't just repeat the basics.

So what is the best way to copy the files back into my branch. 

On 2 November 2017 4:05:50 PM AEST, Scott Lahteine <notifications@github.com> wrote:
>I found that it was quite easy to rebase it onto 1.1.x using `git
>cherry-pick` but I won't insist you go down that path. If you're
>curious, I first used `git rebase -i upstream/1.1.x` to squash all
>commits down to a single commit. Then I did `git reset --hard
>upstream/bugfix-1.1.x` to reset the branch to `bugfix-1.1.x`, and
>finally, I did a `git cherry-pick 5557f89` to take that single squashed
>commit and apply it onto the branch. The result, your changes applied
>to the latest `bugfix-1.1.x` code.
>
>Since I've done all the work already, you can just create a new branch
>based on `bugfix-1.1.x` to start with, then download my branch at
>https://github.com/thinkyhead/Marlin/tree/stuart_fixup, copy the
>changed files into your branch, and create a shiny new commit.
>
>Changed files are…
>
>![image](https://user-images.githubusercontent.com/698003/32312105-e4950fa0-bf69-11e7-8e93-1bfb95626222.png)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/issues/8203#issuecomment-341326296

-- 
Sent from my Android device

**Comment by stuartmp** [comment]
Wow I see that you added labels to this item too. How did you do that. I tried but could not see how to.

**Comment by thinkyhead** [comment]
As an admin I have label power.

The best way to copy files from my branch into yours is to use your computer's Finder or Explorer.

I assume you are using Github Desktop as your gateway to Github…?

**Comment by stuartmp** [comment]
I have switch my branch on my Github desktop to bugfix-1.1.x and I have cloned your branch to my local pc under a directory marlin bug fix. What is the best way now to copy the files into my original repository? Do I just use file explorer and just copy those changed files that you show me above?

**Comment by stuartmp** [comment]
Ok I will just copy then using file explorer.

**Comment by thinkyhead** [comment]
If you're into puzzle-like tutorials and curious about Git, the thing that got me started in comprehending its quirks (though it is a dream compared to CVS or SVN) was this interactive tutorial: https://learngitbranching.js.org/ . I had to do it many times to start getting the gist. In the end, I use a very small and specific subset of Git's full power, along with some helper scripts, and it lets me fly through my work now.

**Comment by stuartmp** [comment]
Thank you for the notes and the tutorial link I will certainly looks into that.

OK I have the files as you did it above. Do I just commit it now and Push it to the origin?

![image](https://user-images.githubusercontent.com/4042250/32312706-f7f691aa-bfea-11e7-8061-5d9a40a346ce.png)

**Comment by stuartmp** [comment]
Just to clear things up for me Scott. Did my attempt fail because I was trying to create a PR to the wrong branch or was there something else?

**Comment by stuartmp** [comment]
I also just changed my default branch on GitHub online to bugfix-1.1.x I hope this was the right thing to do?

**Comment by thinkyhead** [comment]
![image](https://user-images.githubusercontent.com/698003/35850793-9d120372-0aeb-11e8-926d-bc23a01afff5.png)
