### ISSUE TITLE
Sdcard failed to init ### Bug Report

### ISSUE THREAD

**Issue by karabas** [MarlinFirmware/Marlin#8210]
------------------------------------------------------------
### Bug Report
- Description: ---

MKS Sbase + GLDC display ( or RRD SC  Display)
 #define SDSUPPORT 
 #define SDCARD_SORT_ALPHA

- Actual behaviour: ---
When inserting I get "Card inserted" on main displey window
Blinking lines on screen for several seconds ( some spi pins are used by lcd)
After that menu shows "No card"

I tried different cards
Displays and board are proved to work under smoothieware.

------------------------------------------------------------

**Comment by thinkyhead** [comment]
Presuming solved.
