### ISSUE TITLE
How to configure Software serial correctly?

### ISSUE THREAD

**Issue by karabas** [MarlinFirmware/Marlin#8212]
I need to control external mp3 player via serial 9600 Tx only.
On marlin 1xxx and mega2560 I use SoftwareSerial lib
Now I jump to Marlin2 and Sbase. As I have told there are no spare hardware serials on that chip. 
If it is correct I want set configure seftware serial for my usage, 
( I already done  it on smoothieware)

**Comment by tcm0116** [comment]
If you're using the emulated serial port over the USB for normal host comms, then UART0 is available for use on the MKS SBASE. The recently updated HardwareSerial class in the LPC1768 HAL can be used to communicate over the UART.

**Comment by karabas** [comment]
Thanx! Any examples of config?  But... hardware serial I want to use with wifi ESP8266.
May I setup UART1 for player?

**Comment by tcm0116** [comment]
I assume you're working custom code to achieve this be function? If so, the instances of HardwareSerial are already created and just need to be initialled, and used. If you want to use UART1 @ 115200 baud, then just write `Serial1.begin(115200);`. You can then use the read, write, and print functions on Serial1 to read and write data.

**Comment by karabas** [comment]
Thanx a big!  I need set correct pins for every SerialXXX. I will look into code to find out.

**Comment by tcm0116** [comment]
The pins should already be setup correctly. Once you can begin on the
appropriate SerialX object, it will be mapped to the correct pins for that
port.
