### ISSUE TITLE
ROXY-3D I have a job for you :-)

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#8217]
Hi, Roxanne , you told me you contributed to create UBL then , Now i know you can create this

**The  ' Z_PROBE_OFFSETTING  Menu '** 
With this all in one menu , we can set nozzle offsets in one click
If you don't want to make it , i can make it but not for the moment 
Thk you 

I explain the more clear as possible : To set a zprobe offset it's not easy , you must go on motion menu , increase the offset , return to z homing , go to move 0.1 , test , and to apply value , return to motion and many times to verify all ,  so ,  the job is to make a menu that simply all , and looks like this 

Step by Step
**BUTTON  ' Make offset '**
- Set z_probe_offset = 10  ' it's enough in all cases '
- Make a Z homing 
- Show the move menu z ' 0.1mm ' but with another message 
       ' Place paper Under Nozzle and touch it '
       ' Click when finish '
- After menu clic ---> Calculation of Z_probe_offset = 10 - current height  
                          ---> Apply  the value

 **BUTTON  ' Test Offset '**
- G28Z
- - Show the move menu z ' 0.1mm ' but with another message 
       ' Place paper Under Nozzle and touch it '
       ' Click when finish '

Easy to make
I want to make it , but , i need to take a pause , ' spool swap feature have taken time and my wife want to divorce ' 😄

**Comment by pandel** [comment]
Why don't you just use babystepping in combination with setting z probe offset? See configuration_adv.h for details...

**Comment by ghost** [comment]
You start a print , you adjust by babystepping in real time and you have perfect real a tested value 
It's your way to find it ?
If not , explain me all 😄
