### ISSUE TITLE
[FR] Unwanted Auto Cooldown

### ISSUE THREAD

**Issue by joeedh** [MarlinFirmware/Marlin#8223]
I just upgraded my printer's Marlin, and it's now automatically cooling down the printer if I do "stop print" from the menu.  I very, very much do not want this to happen.  From my reading of the code (in lcd_sdcard_stop()), there is no configuration option to turn this off.

Anyway, I propose encapsulating:

thermalManager.disable_all_heaters();

in an #ifdef, and an appropriate entry added to Configuration.h

I'm not sure if I should submit a pull request, since it's such a simple change and this seems like the sort of thing the developers will want to do themselves (to fit naming/doc conventions, etc).

Thanks.

**Comment by psavva** [comment]
I suggest you create a pull request.  
Nothing like a PR to contribute :)

**Comment by thinkyhead** [comment]
What do you think, @tcm0116 ? Does it make sense to revert this element of #6567 / #6553?

**Comment by tcm0116** [comment]
I don't think we should revert it, but rather make it a configuration option as @joeedh has suggested.

**Comment by stuartmp** [comment]
I think it a great idea. you could possibly have some type of time out so if no other input is given within x seconds then the cool down could start. I would love to see a re-print option too. Just a double press of the control button like micro stepping works after you start a print. You could then select from a yes / no to re-print.  As I hate having to re browse my sd card to find the file I want. If for instance something goes wrong on the first layer.

**Comment by Roxy-3D** [comment]
> I would love to see a re-print option too. Just a double press of the control button like micro stepping works after you start a print. You could then select from a yes / no to re-print. As I hate having to re browse my sd card to find the file I want.

It wasn't done as a Double Click like the Z-BabyStepping...   But if you go into `Configuration_adv.h` you can turn on 
```cpp
  /**
   * This option makes it easier to print the same SD Card file again.
   * On print completion the LCD Menu will open with the file selected.
   * You can just click to start the print, or navigate elsewhere.
   */
  //#define SD_REPRINT_LAST_SELECTED_FILE
```
I'm not sure what happens if you stop the print and don't let it finish to completion.   But we probably can make that do the same thing.   (This was done to help people that are using their printers to manufacture the same part again and again.)

**Comment by stuartmp** [comment]
Nice... Thanks for the response. I will look into that option and what can be done to to improve it.
I will start my own issue, so not to hijack joeedh and his cooldown

**Comment by thinkyhead** [comment]
I also never miss a change to pimp my latest feature.

**Comment by stuartmp** [comment]
So are you able to point me in the right direction for the modifications or are you thinking of adding this feature to the work that you have done.... 

On 14 November 2017 5:14:12 PM AEST, Scott Lahteine <notifications@github.com> wrote:
>I also never miss a change to pimp my latest feature.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/issues/8223#issuecomment-344166761

-- 
Sent from my Android device

**Comment by thinkyhead** [comment]
Trying to get 1.1.7 out. This is on the low priority list. It's not a difficult thing to do, just not vital for the upcoming release.

**Comment by stuartmp** [comment]
Nice... keep up the awesome work.

On 14 November 2017 5:31:21 PM AEST, Scott Lahteine <notifications@github.com> wrote:
>Trying to get 1.1.7 out. This is on the low priority list. It's not a
>difficult thing to do, just not vital for the upcoming release.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/issues/8223#issuecomment-344169870

-- 
Sent from my Android device

**Comment by joeedh** [comment]
Okay, I have created a pull request, feel free to redo it (it really is like three lines of code).  #8494

**Comment by wikolii** [comment]
I can't find any updates on this issue, i just updated (too late, i know) to 1.1.9 and can't disable auto cooldown on print stop the way i used to on previous versions.

I used to comment out 1 line on Ultralcd.cpp and now that line doesn't existe anymore.
"thermalManager.disable_all_heaters();"

Thanks

**Comment by boelle** [comment]
@thinkyhead since there is a PR could this one not be closed?

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by InsanityAutomation** [comment]
FYI this has been implemented in config adv

 // Leave the heaters on after Stop Print (not recommended!)
  //#define SD_ABORT_NO_COOLDOWN

So this can be closed.

**Comment by boelle** [comment]
Closing as this has been implemented
