### ISSUE TITLE
[FR] Turn Off/On M200 Feature Completely - AKA completely shut off volumetric extrusion option

### ISSUE THREAD

**Issue by houseofbugs** [MarlinFirmware/Marlin#8232]
I have a lot of people accidentally turning on the volumetric extrusion and it causes issues for them because its on. 

Can we have an option in the Configuration.h or Configuration_adv.h to disable this completely (as in not put into the compiled firmware at all)? Not many people use it and it would also be great to remove it to save space on the 1284P boards.

**Comment by thinkyhead** [comment]
Sounds like a good idea. We'll look into it soon.

**Comment by houseofbugs** [comment]
Thanks. I run a small maker space where we do a lot of support and work with marlin printers. We get at least 2-3 people a week that change the filament diameter and then it turns this on. They then go on a hunt to recalibrate their extruder and it's a mess.

**Comment by houseofbugs** [comment]
In the mean time is there a way I can manually remove it?

**Comment by houseofbugs** [comment]
Just following up. Was any progress made on this? I checked the 1.1.7 and it doesn't look like it is an option. If I'm correct I'll start working on stripping it out.

**Comment by thinkyhead** [comment]
No, it hasn't been made strippable yet. It should be straightforward to do so.

**Comment by thinkyhead** [comment]
Here you go. The above PRs allow volumetric extrusion to be completely disabled.
