### ISSUE TITLE
UBL 1.1.x and 2.0.x don't match

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#8235]
One of these things is not like the others.
One of these things just doesn't belong.
One of these things is not like the others.
Can you tell which one it is…
Before I finish this song?

Somehow changes to UBL were made to one branch and not the other. This is especially obvious with `find_closest_mesh_point_of_type` but probably impacts other methods also. Please check it over and make a PR with the necessary updates to the appropriate branch.

**Comment by Roxy-3D** [comment]
I will be putting some fixes into the bugfix-v1.1.x branch very soon.    The 
```cpp
  inline bool prepare_move_to_destination_cartesian() {}
```
routine is doing the wrong thing for UBL and it is causing issues with the circle drawing for G26.    

I can get UBL identical across the two branches at the same time.     The difference is only for the G29 P1 U option to space out the probes to assist with physical bed leveling.   The new code does a better job but the old code does work.    

With that said...   I'll do a 3-way merge in the next day or two and get everything identical.  But I need to understand and resolve the G26 Circle problem first.  It is very possible this flaw in 
```cpp
  inline bool prepare_move_to_destination_cartesian() {}
```
is the source of the Z-Axis creeping up with each tool change too.  It might be that problem goes away when the G26 Circles are fixed.

**Comment by thinkyhead** [comment]
Pretty well matching now? I'd guess they are close. Try pasting code from each branch to replace the equivalent code on its counterpart and see what diffs show up in Github Desktop.

**Comment by boelle** [comment]
do they match now?
