### ISSUE TITLE
1000 and 1 ways to set Z_probe_offset , give your own pls ' not an issue '

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#8245]
Hi , I have my own way to make my z_probe_offset , but i'm curious to know if someone here can give me a better solution 

**First :** I use a cnc jauge or a paper , I increase the value , homing z , and by lcd i go down to press the paper/jauge and I apply the value ....Need tons of lcd navigations 👎 
**Second : ** I start a print and i use Babystepping , to make the last correction 

And You  ?

**Comment by thinkyhead** [comment]
FFS @studiodyne — This isn't a social club. Please post such things to Facebook or http://forums.reprap.org/
