### ISSUE TITLE
Two folders for STM32F103RET6 example configuration

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#8251]
@thinkyhead,

A recent update has created two folders for 'STM32F103RET6' in the example configurations folder. One is uppercase and one is lowercase.

This is causing issues with git on windows machines which, being a bit dumb, can't distinguish between upper and lower case for folder and file names.

I have no idea how to fix this, so must leave it in your capable hands.

Thanks.

**Comment by fiveangle** [comment]
#8253 submitted

**Comment by thinkyhead** [comment]
Sorry about that. I forgot how Git "mishandles" renames where only case is involved.
