### ISSUE TITLE
Pin definition error in RAMPS_RE_ARM.h

### ISSUE THREAD

**Issue by Bergerac56** [MarlinFirmware/Marlin#8266]
there is an error in the pin definition for RE-ARM EFB
In pins_RAMPS_RE_ARM.h, 
  #define RAMPS_D8_PIN   P2_8 has to be replaced by   #define RAMPS_D8_PIN   P2_7

**Comment by tcm0116** [comment]
Oops. Looks like I fat-fingered that when I was converting to the new pin mapping.

**Comment by Bergerac56** [comment]
Thanks Thomas ;)
