### ISSUE TITLE
Different filament diameter sizes in multi extrude environment

### ISSUE THREAD

**Issue by lavato** [MarlinFirmware/Marlin#8268]
Hi,
I have two questions:

* Is it possible to assign a filament size of 1.75mm to one and 3mm to another extruder?
* If not, can filament size be updated via a menu option?

**Comment by AnHardt** [comment]
If not in volumetric mode Marlin has no clue about you nozzle or filament diameter and dos not use it.
Your slicer has to know about it. All Marlin knows about is extruders steps/mm.

**Comment by lavato** [comment]
Ahh, of course!!! Sorry about the stupid question.

Thank you.

I was not doing any 3D printing "stuff" for couple of months and am planning to convert my printer to use 3mm as well as 1,75mm.
