### ISSUE TITLE
2.0 error in G33.cpp, sprintf_P not for ARM

### ISSUE THREAD

**Issue by Vynt-1** [MarlinFirmware/Marlin#8277]
### Feature Request
"sprintf_P(...)" and similar functions don't work with ARM core

----

### Compile Error
When I compile with `#define DELTA_AUTO_CALIBRATION` I get an error:
```
...AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\cores\arduino/avr/pgmspace.h:99:59: error: expected primary-expression before ')' token

 #define sprintf_P(s, f, ...) sprintf((s), (f), __VA_ARGS__)

...sketch\src\gcode\calibrate\G33.cpp:652:9: note: in expansion of macro 'sprintf_P'

         sprintf_P(mess, PSTR("Calibration sd:"));

etc.
```

----

### Bug Report
- Description:  "sprintf_P(...)" and similar functions don't work with ARM core

----

### Bug Report Tips
I use standard configuration from ..\Marlin\src\config\examples\delta\FLSUN\auto_calibrate
```

**Comment by thinkyhead** [comment]
Looks like that particular instance is wasteful. It should just be `strcpy_P`.

I don't think it's a problem of ARM. It's that the definition of `strcpy_P` requires at least 3 arguments, and if there are only two then it chokes.

**Comment by thinkyhead** [comment]
Please check against the latest code, patched to remove the problem instances of `sprintf_P`. If the problem isn't resolved, feel free to re-open the issue.
