### ISSUE TITLE
Printing bed size error MARLIN 1.1.6

### ISSUE THREAD

**Issue by Stempek5** [MarlinFirmware/Marlin#8279]
Hi there,

Hardware:
-Arduino Mega 2560
-RAMPS 1.4
-A4988 stepsticks
-self build drawing plotter made of DVD/floppy drive motors 

I've got an error while trying to compile program:
![obraz](https://user-images.githubusercontent.com/32224257/32420182-81d746a6-c286-11e7-81ae-f0921017bdd9.png)

I don't use any of extruders, temperature sensors, nor endstops. It's just a drawing machine to prepare myself building larger 3D printer in the future.

Work area is like 45mm x 50 mm but i set parameters like this:
![obraz](https://user-images.githubusercontent.com/32224257/32420222-1608f784-c287-11e7-8d25-0a0c2e61084b.png)

I have also set rest of parameters like this:

```
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 30, 30, 40, 500 }
#define DEFAULT_MAX_FEEDRATE          { 10, 10, 2, 25 }
#define DEFAULT_MAX_ACCELERATION      { 100, 100, 10, 10000 }
#define DEFAULT_ACCELERATION          50    
#define DEFAULT_RETRACT_ACCELERATION  50    
#define DEFAULT_TRAVEL_ACCELERATION   10 
```
but I have no idea I did it properly.

Motors used in CNC:
Y axis (ground/working area):
Resistance per coil 9,5ohms
so I calculated Vref=0,420V
X axis (horizontally left-right movement):
Resistance per coil 11,8ohms
so I calculated Vref=0,340V
Z axis (motor used from floppy drive):
Resistance per coil 30,3ohms
so I calculated Vref=0,133V

Do you have any advices what is set wrong (I'm almost sure I set something wrong - but have no idea what)?

**Comment by RowanMeara** [comment]
If you attach your config file we can try compiling it to help find your error.

**Comment by thinkyhead** [comment]
You will need to upgrade your Arduino IDE. Version 1.5 doesn't do C++11.

**Comment by thinkyhead** [comment]
You will need to upgrade your Arduino IDE. Version 1.0.5 doesn't do C++11.
