### ISSUE TITLE
Anet A8 Eeprom CRC Mismatch

### ISSUE THREAD

**Issue by agreen** [MarlinFirmware/Marlin#8289]
### Bug Report
- Description: Running latest version of 1.1.x-bugfix and keep getting Eeprom CRC mismatch errors
- Expected behaviour: load values from eeprom
- Actual behaviour: default values loaded, due to CRC mismatch
- Steps to reproduce:
  - use latest 1.1.x-bugfix, flash to Anet A8 board.

**Comment by agreen** [comment]
Also, Not sure if there are any eeprom tests you'd like me to run, just to make sure the eeprom hasn't gone bad...  I did notice the CNC_COORDINATE_SYSTEMS patch made some changes to EEPROM though, so thought I'd check here first.

**Comment by halfluck** [comment]
Hey Guys,

Just flashed 1.1.x-bugfix and i'm getting "Error: EEPROM CRC mismatch - (stored) 8865 != 25765 (calculated)!"

in my logs too tried a M502 then M500 multiple times without any luck.

Cheers Rob.

**Comment by Roxy-3D** [comment]
Does #8283 or #8284 fix it for you?   I suspect it will....

**Comment by agreen** [comment]
Yes it fixed the issue. Thanks.

**Comment by Roxy-3D** [comment]
OK...   It should be fixed and working in the main bugfix-v1.1.x branch.    (You don't have a 'special' version.   You have what is in the main branch.)

**Comment by halfluck** [comment]
Thanks!

**Comment by psavva** [comment]
Suggest to please close this issue as it is resolved.
