### ISSUE TITLE
[Bugfix 1.1.x] Bug Report: G92 broken?

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#8307]
### Bug Report
- Description: G92 is not working to zero the extruder
- Expected behaviour: zero the extruder
- Actual behaviour: does not zero the extruder
- Steps to reproduce:
  - Send the following:
G1 E10; extrudes 10mm
G92 E0; zero the extruder
G1 E10; extrude another 10mm. It does not.

*OR*

G1 E10; extrudes 10mm
G92 E0; zero the extruder
G1 E0; extruder retracts 10mm. It should not.

Comparing G92 code between Bugfix 1.1.x and Bugfix 2.0.x, there are a couple of lines missing in Bugfix 1.1.x:

In Bugfix 2.0.x:
```cpp
  if (IS_G92_0) LOOP_XYZE(i) {
    if (parser.seenval(axis_codes[i])) {
      #if IS_SCARA
        current_position[i] = parser.value_axis_units((AxisEnum)i);
        if (i != E_AXIS) didXYZ = true;
      #else
        #if HAS_POSITION_SHIFT
          const float p = current_position[i];
        #endif
        const float v = parser.value_axis_units((AxisEnum)i);

        current_position[i] = v;
```
In Bugfix 1.1.x:
```cpp
  if (IS_G92_0) LOOP_XYZE(i) {
    if (parser.seenval(axis_codes[i])) {
      #if IS_SCARA
        if (i != E_AXIS) didXYZ = true;
      #else
        #if HAS_POSITION_SHIFT
          const float p = current_position[i];
        #endif
        const float v = parser.value_axis_units((AxisEnum)i);
```
The missing lines update `current_posistion[]`.

**Comment by thinkyhead** [comment]
Aha, right. The updated coordinate space code doesn't need to update XYZ but it should be updating E. I will post a fix momentarily.
