### ISSUE TITLE
Connect self-made printer with bluetooth?

### ISSUE THREAD

**Issue by Hypersparking** [MarlinFirmware/Marlin#8316]
Now I'm trying to connect my self-made printer just with bluetooth on my mobile phone. However, my printer can't get rid of the USB wire connected with my printer while controlling it by my phone. Could you tell me how to set serial ports so that I can pull it off?

**Comment by Hypersparking** [comment]
Marlin 1.1.5 though

**Comment by thinkyhead** [comment]
Presumably you just need to enable `BLUETOOTH`. I've never personally used it, so I'm not sure what else may be required.

**Comment by Hypersparking** [comment]
Emmm...However,I've enabled bluetooth in configuration.h. But I still need to plug the wire on my computer otherwise my phone can't control it. Quite puzzled XD.

**Comment by Tannoo** [comment]
A bluetooth module of some type is needed for most boards.

**Comment by Tannoo** [comment]
I have done it on the Mega2560 / Ramps. The phone only gives basic controls, but it did work for me.

That was a long time ago.

**Comment by Tannoo** [comment]
I like the Octopi setup better and can access / control / watch print from any computer / tablet / phone that's on the same wifi network.

**Comment by Hypersparking** [comment]
@Tannoo  I do use a special kind of bluetooth module. How did you get it work without the USB cable? I use mega2560/Ramps too. I knew it might can only control the printer basically but I really want to do it.

**Comment by Tannoo** [comment]
Well, aux2 on the Ramps has pins for the main serial connection.

**Comment by Tannoo** [comment]
I've used that for the bluetooth and an serial based lcd touch screen.

**Comment by Hypersparking** [comment]
@Tannoo Not need to modify some parameters in Marlin Firmware?

**Comment by Tannoo** [comment]
I don't think anything other than enabling BLUETOOTH.

**Comment by Hypersparking** [comment]
Anyway thank you very much!@Tannoo

**Comment by Tannoo** [comment]
I haven't found the bluetooth module I used, so I can't test it.
