### ISSUE TITLE
Not a issue but a question about Mesh Leveling

### ISSUE THREAD

**Issue by budi67** [MarlinFirmware/Marlin#8346]
Hello all

Sorry for my bad english.
I don't have sensor
I would want to know how to have operational the mesh leveling.
There is a command to be written in the gcode ?
I have make the mesh with the LCD menu and when i make a G29 S0 i have my grid
![mesh](https://user-images.githubusercontent.com/23610289/32593269-969a51f2-c527-11e7-9059-632299cb9fac.PNG)
But when i launch a print, the Z don't move

A big thanks

**Comment by ghost** [comment]
Try adding M420 S1 to your start gcode. http://reprap.org/wiki/G-code#M420:_Leveling_On.2FOff.2FFade_.28Marlin.29

**Comment by budi67** [comment]
Thanks JimBrown ;) i will try this when the print is finished.
In the gcode, i have to add G29 or no ?

**Comment by ghost** [comment]
My understanding is no, you do not add G29 to the start gcode when using manual mesh leveling.

**Comment by thinkyhead** [comment]
You should use `M420 S1` in your startup G-code, as this will make sure your saved leveling mesh is used for the print.

**Comment by budi67** [comment]
A big thanks, M420 S1 work great !!!

**Comment by budi67** [comment]
A big thanks, M420 S1 work great !!!
