### ISSUE TITLE
[FR] Junction deviation instead of Jerk settings

### ISSUE THREAD

**Issue by Sineos** [MarlinFirmware/Marlin#8348]
I have been playing with the Smoothieware Firmware on a friend's printer (and I have to say I like Marlin a lot more).
Nevertheless I stumbled upon an interesting setting that I really did like:
http://smoothieware.org/motion-control#junction-deviation

Playing around with this setting on his printer was a real eye-opener and the logic behind is more easily to grasp compared to the Jerk setting.

It also seems to be a common setting for CNC type of machines when going by this information: 
https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.8#9---junction-deviation-mm

**Comment by thinkyhead** [comment]
Looks like a neat alternative to jerk. We'll add it to the things-to-try list.

**Comment by lenne0815** [comment]
First i didnt even understand the implications of "jerk" in marlin and thought of it as the physics term jerk. Later on i realised that jerk was in fact an instantaneous change in speed causing all kinds of problems ( ringing, inconsistent stepper torque output etc etc etc ). After being dumbfounded by that ( Coming from mach 3 and cncing in general where something like "jerk" is unheard of ) I started looking for alternatives and luckily enough quickly found one; kevinoconnors klipper firmware does proper lookahead / toolpath prediction on 8 bit boards while being able to pulse up to 150khz.

**Comment by Sineos** [comment]
I tried to integrate https://github.com/grbl/grbl/blob/658eb6a8b3cff0da59a61cbb5aa04d2c693c36c3/grbl/planner.c#L356-L402 into Marlin but failed miserable. As a "script kiddie" (not age wise :-P) this is way above my head.

**Comment by thinkyhead** [comment]
Junction Deviation is now integrated. See MarlinFirmware/Marlin#10650, MarlinFirmware/Marlin#10651.

**Comment by boelle** [comment]
are there any documentation on how to tune it? i just found the feature today

**Comment by kAdonis** [comment]
@boelle No, not that I know
You are not alone
MarlinFirmware/MarlinDocumentation#500
https://github.com/MarlinFirmware/Marlin/issues/9917#issuecomment-396085333
You could try the Jerk Tower:
https://www.youmagine.com/designs/multi-angle-test-tower-for-calibrating-jerk#documents

**Comment by boelle** [comment]
read through the jerk tower explanation and see this:

"Jerk" is called "Junction Deviation" in other firmware and is calculated differently, and so has different setting/values.

spec the part: is calculated differently, and so has different setting/values.

so far a dummie like me that does not help much as he does not explain how to find junction deviation 

if it's as simple as just turning on junction deviation and using the same test method then i get it, but some more detailed explanation could be very usefull

does it even matter in regards to print quality if i use jerk or deviation?

**Comment by boelle** [comment]
i think the best bet is to use the jerk tower guide and use values 0.01 to 0.3 and see what is the fastest before print quality suffers

**Comment by kAdonis** [comment]
I thought you read what it is and were just seeking information how to tune it

> "Jerk" is called "Junction Deviation" in other firmware

thats an over-simplification, I wont subscribe on that
If you want to dive into the maths read this
https://onehossshay.wordpress.com/2011/09/24/improving_grbl_cornering_algorithm/
I didn't see any difference in print quality but my test are several month ago

**Comment by boelle** [comment]
no it was the part that said: "is calculated differently, and so has different setting/values."

is the jerk tower page insttructions still valid? i'm veru much in doubt since it says that deviation is calculated different and has different values than when you calculate jerk

but they do not say how to use the tower for deviation

hope that made sense

**Comment by kAdonis** [comment]
Sorry, its a long time since I used the tower
You can use it analog to jerk settings
M205 J sets the Junction Deviation
~~M205 Z sets the z-jerk which is still used~~

**Comment by boelle** [comment]
oki, then i just have to wait until they fix an issue on the latest version where i cant control a 2nd extruder fan, currently i have to run a 2 month old copy where junction deviation is not introduced yet

i use the 2nd extruder fan to control a fan that cools of the bed after print is complete so the PEI releases faster

https://github.com/MarlinFirmware/Marlin/issues/12831

**Comment by Squid116** [comment]
> M205 Z sets the z-jerk which is still used

What gives you that impression @kAdonis ? Unless I have missed something if you are using JD, then it replaces all the jerk values.

**Comment by boelle** [comment]
but some documentation on how to tune it would be nice :-D

**Comment by Squid116** [comment]
@boelle if it is that important to you, you could put a bounty on the documentation ;)

**Comment by kAdonis** [comment]
@Squid116 of course, you are right. Z-jerk isn't used
I was confusing Z-jerk with E-jerk
