### ISSUE TITLE
Sbase: Display MKS MINI12864 works as VIKI2 or ASZMZ 

### ISSUE THREAD

**Issue by karabas** [MarlinFirmware/Marlin#8361]
It works
 but USB mount stops working and saving to EEPROM causes hanging.
Cardreader is able to read some sdcards. 

```
#if ENABLED(AZSMZ_12864) || ENABLED(VIKI2) 
#define BEEPER_PIN       P1_31
#define DOGLCD_A0        P1_23
#define DOGLCD_CS        P1_22
#define BTN_EN1          P3_26
#define BTN_EN2          P3_25
#define BTN_ENC          P1_30
#define LCD_SDSS         P0_28
#define SD_DETECT_PIN    P0_27
#define DEFAULT_LCD_CONTRAST     100
#endif
```
If I define MKS_MINI_12864 display does not work

spi_pins.h
```
/** onboard SD card */
#define SCK_PIN           P0_7
#define MISO_PIN          P0_8
#define MOSI_PIN          P0_9
#define SS_PIN            P0_6
/** external */ /*
#define SCK_PIN           P0_15
#define MISO_PIN          P0_17
#define MOSI_PIN          P0_18
#define SS_PIN            P1_23
*/
#define SDSS              -1 //SS_PIN

```

**Comment by thinkyhead** [comment]
I think this may now be working in `bugfix-2.0.x`. Please give it a test.

**Comment by boelle** [comment]
@karabas did you try bugfix-2.0?

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed? Sorry, I got bored.

**Comment by boelle** [comment]
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
