### ISSUE TITLE
M428 changes nothing but says offsets applied

### ISSUE THREAD

**Issue by FX117** [MarlinFirmware/Marlin#8362]
### Bug Report
- Description: Sending M428 changes nothing but says offsets applied 
- Expected behaviour: The current position is set to the native home position. As described [here](http://marlinfw.org/docs/gcode/M428.html)
- Actual behaviour: It changes nothing, but the display says offsets applied
- Steps to reproduce:
  - Send M428 to Marlin

Background: I thought M428 would be a good way to set a persistent offset that I could return to after power loss on my Mostly printed CNC.

[config.zip](https://github.com/MarlinFirmware/Marlin/files/1462354/config.zip)

**Comment by thinkyhead** [comment]
Same with `M206`?

**Comment by FX117** [comment]
No M206 works fine

Edit: [here](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Marlin_main.cpp#L9554) it is checked if the axis is homed, but if it is not it displays success despite doing nothing.

**Comment by RowanMeara** [comment]
Interesting, I'll take a look at this.
