### ISSUE TITLE
NeoPixel Loop NEOPIXEL_STARTUP_TEST

### ISSUE THREAD

**Issue by fred2088** [MarlinFirmware/Marlin#8369]
Thank you for submitting your feedback to the Marlin project.
Please use one of the templates below to fill out this box.

 #define NEOPIXEL_LED
 #define NEOPIXEL_STARTUP_TEST

1.1.6
Start Loop ....

**Comment by Tannoo** [comment]
Try bugfix-1.1.x.

**Comment by thinkyhead** [comment]
As mentioned by Tannoo, it's vitally important that you test against the latest `bugfix-1.1.x` before reporting an issue, since it's always possible that we fixed it already.

**Comment by Tannoo** [comment]
I know it works fine in bugfix-2.0.x.

**Comment by fred2088** [comment]
it's work fine from bugfix-1.1.x, thanks
