### ISSUE TITLE
WS2812 VS NEOPIXEL

### ISSUE THREAD

**Issue by fred2088** [MarlinFirmware/Marlin#8370]
enable neopixel,
not work with ws2812 ?
WS2812 work with fastled lib, how to modify to use neopixel ?

**Comment by Tannoo** [comment]
From Adafruit:
"Not all addressable LEDs are NeoPixels.“NeoPixel” is Adafruit’s brand for individually-addressable RGB color
pixels and strips based on the WS2812, WS2811 and SK6812 LED/drivers, using a single-wire control protocol.
Other LED products we carry — DotStars, WS2801 pixels, LPD8806 and “analog” strips — use different
methodologies (and have their own tutorials). When seeking technical support in the forums, a solution can be
found more quickly if the correct LED type is mentioned, i.e. avoid calling DotStars “NeoPixels”…similar, but
different!"

**Comment by Tannoo** [comment]
I would try using Neopixel library examples. If it doesn't work... talk to Adafruit or the supplier of your strip.

**Comment by Tannoo** [comment]
This is not a Marlin issue. Leds recognized or not by the Neopixel library is out of Marlin's scope.

**Comment by Tannoo** [comment]
FastLED supports more types of 5050 leds than Neopixel.

**Comment by Tannoo** [comment]
Also from Adafruit about FastLED:
https://learn.adafruit.com/adafruit-neopixel-uberguide/advanced-coding
