### ISSUE TITLE
MKS SBASE board with eeprom enabled crashes if you do a M500 or M501

### ISSUE THREAD

**Issue by Spawn32** [MarlinFirmware/Marlin#8375]
Board crashes a few seconds after doing a M500 or M501, needs a hard reset to work again.
so no UBL for me yet :)
[config.zip](https://github.com/MarlinFirmware/Marlin/files/1464149/config.zip)

**Comment by karabas** [comment]
What display do you use?

**Comment by Spawn32** [comment]
MKS TFT 3.2 :)

**Comment by karabas** [comment]
Strange. M500 works for me perfectly if I do not use spi display. It saves eeprom.dat. Sdmounting succesfull?

**Comment by ihagon** [comment]
M500 works fine for me too. I'm also using a MKS TFT 3.2 I do have a Full Graphic display connected too but I'm using the wifi connection via the MKS TFT to issue the M50X commands.

**Comment by Spawn32** [comment]
strange :/
You have only enabled #define EEPROM_SETTINGS in config ? this happens when i do a 500/501 from simplify3d, could somone test that ?

**Comment by Spawn32** [comment]
@karabas 
I dont have #define SDSUPPORT enabled, dont think you need that for eeprom ?
when i enable eeprom with #define EEPROM_SETTINGS it makes a eeprom file side by side of the binary.cur file...

**Comment by karabas** [comment]
```
#define EEPROM_SETTINGS // Enable for M500 and M501 commands
//#define DISABLE_M503    // Saves ~2700 bytes of PROGMEM. Disable for release!
#define EEPROM_CHITCHAT   // Give feedback on EEPROM commands. Disable to save PROGMEM.
```
I didnot try without SDSUPPORT

**Comment by Pentelfrost** [comment]
I also have an SBASE and it doesn't crash after M500/M501 commands. I'm using printrun via the MKS wifi to issue the commands.

**Comment by Glod76** [comment]
I have an anet a8 with the mks sbace and reprap full graphics display and was wondering if someone could give me a full step by step on configuring and compiling this to work on my board. I have an inductive probe as well.
