### ISSUE TITLE
Strange output from M114 on MKS SBASE

### ISSUE THREAD

**Issue by Spawn32** [MarlinFirmware/Marlin#8376]
While calculating my z probe offset i noticed that the M114 has a strange output, or is it me that have done something ?

M114 after a G28:

SENT: M114
READ: X:74.000000 Y:105.000000 Z:6.200000 E:2452.038818 Count X:14800 Y:21000 Z:4960
[config.zip](https://github.com/MarlinFirmware/Marlin/files/1464157/config.zip)

**Comment by thinkyhead** [comment]
What should it say instead?

**Comment by Spawn32** [comment]
I might have misunderstood this, but take the Z, when i am at Z -1.2, shoulden't M114 say something like z:-1.2 ?

**Comment by Spawn32** [comment]
Ahh... sorry, feel like a jerk, i stared my self blind on the last Z that oblivious is the stepper :/
Z:6.200000 is what i should have looked at ...

Closing issue :)

**Comment by thinkyhead** [comment]
M114 itself had an issue, now patched. See if that clears it up.

**Comment by thinkyhead** [comment]
No problemo! That's why we do the interrogations. 😁
