### ISSUE TITLE
2.0.x ArduinoDUE and Full Graphic Smart Controller

### ISSUE THREAD

**Issue by sh4jonny** [MarlinFirmware/Marlin#8394]
try to use Full Graphic Smart Controller on ArduinoDUE and HackedRAMPS but display didn't work.
it works for somebody now? i try to check correct pins definitions by PINS_DEBUGGING but #8393 
thank you.

**Comment by fiveangle** [comment]
Come on in, the water's fine ! https://github.com/MarlinFirmware/Marlin/issues/7687
