### ISSUE TITLE
Bltouch PIN issue?

### ISSUE THREAD

**Issue by EnricoSx** [MarlinFirmware/Marlin#8401]
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/1466538/Configuration.h.txt)

[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/1466502/Configuration_adv.h.txt)

i have this issue when use G29
https://youtu.be/Hx6NyPTb1TM

FW: Marlin 1.1.6
Printer: Anycubic Kossel Linear Plus
Board: Anycubic Trigorilla
Bltouch connect to servo and z-min

M401  nozzle go up and touch all microswitch on top
```gcode
M280 P0 S10   ; works
M280 P0 S90   ; works
M280 P0 S120  ; works
M280 P0 S160  ; works
```

**Comment by thinkyhead** [comment]
Please test `bugfix-1.1.x` and see if the problem still exists.

**Comment by EnricoSx** [comment]
Ok

**Comment by EnricoSx** [comment]
@thinkyhead i load bugfix-1.1.x , 
now g29 
https://youtu.be/nT_SW1JG7aY

**Comment by thinkyhead** [comment]
It looks to me like the BLTOUCH is failing because it's triggering too often. Try slowing down the feed-rates among these options.… 
```cpp
// X and Y axis travel speed (mm/m) between probes
#define XY_PROBE_SPEED 4000

// Speed for the first approach when double-probing (with PROBE_DOUBLE_TOUCH)
#define Z_PROBE_SPEED_FAST (20*60)

// Speed for the "accurate" probe of each point
#define Z_PROBE_SPEED_SLOW (Z_PROBE_SPEED_FAST / 2)

// Use double touch for probing
#define PROBE_DOUBLE_TOUCH
```

**Comment by EnricoSx** [comment]
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/1484958/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/1484959/Configuration_adv.h.txt)


```cpp
#define XY_PROBE_SPEED 2000
#define Z_PROBE_SPEED_FAST HOMING_FEEDRATE_Z
#define HOMING_FEEDRATE_Z  (20*60)
#define Z_PROBE_SPEED_SLOW (Z_PROBE_SPEED_FAST / 2)
#define PROBE_DOUBLE_TOUCH
```
after some probe
```
20:28:01.118 : Error:Probing failed
20:28:02.046 : X:97.00 Y:-36.00 Z:17.85 E:0.00 Count X:14394 Y:22688 Z:16221
```
@thinkyhead : Error:Probing failed when is it activated? thanks

**Comment by thinkyhead** [comment]
Presuming this is solved.
