### ISSUE TITLE
Erratic extrusion on 2.0.x

### ISSUE THREAD

**Issue by timmit99** [MarlinFirmware/Marlin#8413]
### Bug Report
- Description: 
          Erratic movement on extruder when printing using Marlin bugfix_2.0.x
- Expected behaviour: 
          Standard movement and extrusion
- Actual behavior: 
       Print heats up, bed levels, and moves to first location and then does a giant retraction and then seemingly at random decides which direction to move the extruder during the printing moves.

[Config Files.zip](https://github.com/MarlinFirmware/Marlin/files/1469589/Config.Files.zip)

**Comment by thinkyhead** [comment]
Can you try sending each command from your test G-code one at a time? First, enable the option `M114_DETAIL` in `Configuration.h`. In-between each command use `M114` to check the `current_position`. When you start to see weirdness happening, either stop there or continue with a few more commands.

Alternatively, edit your G-code file and stick `M114` after every G-code command. Use `M111 S247` to enable max logging before you start, and that way all commands will end up in the log.

Thanks! Hopefully with that information we'll have a better idea what kind of issue we have.

**Comment by Roxy-3D** [comment]
I've seen this too.   If I reset the board, connect with PronterFace and tell it to extrude some amount....

Usually, the first extrude is  too fast and it jumps.    And it doesn't always go the right direction.   It is like the extruder's position isn't being initialized to a good value.

**Comment by thinkyhead** [comment]
@Roxy-3D To help narrow down this issue please apply the debugging procedure described above.

**Comment by Roxy-3D** [comment]
I'll try to remember to do that in the morning...

**Comment by timmit99** [comment]
@Roxy-3D Thats is exactly what happenes. I have done a driver swap, full reboot, computer restart and no luck. The g-code looks no different than any other ones i have used. the "E" values increase slowly as expected yet the motor seems to jump around as if it was doing random retracts and extrudes.

@thinkyhead let me do  a COMPLETE marlin 2.0.x reinstall. I have been working on the LED menu options and i might have messed something up between versions. I'll do that tomorrow night after work.

**Comment by Roxy-3D** [comment]
@timmit99    I'm not seeing it do it again and again.   It is the very first extrusion after a reset.   

Are you seeing it do it repeatably?

**Comment by timmit99** [comment]
yeah, ill take a video of it tomorrow if i can. It just seems to go whichever direction it wants with a really large movements

**Comment by karabas** [comment]
I saw the similar on marlin RC0.7. But cannot replicate.

**Comment by thinkyhead** [comment]
An `M114` at any point may be revealing.

**Comment by boelle** [comment]
@timmit99 have you tried bugfix 2.0?

**Comment by timmit99** [comment]
@boelle this was over a year ago, I have since switched to Klipper on that machine and didn't even remember this was an open issue.
