### ISSUE TITLE
Z Axis Not Homing Correctly

### ISSUE THREAD

**Issue by Deneteus** [MarlinFirmware/Marlin#8415]
I have 2 HICTOP Creality CR10s and with their stock firmware it homes X & Y and then Z moves up instead of down and stops after 5-10mm. So then I built and compiled a new firmware using Marlin Bugfix using the CR10 profile and it does the exact same thing. I would think if the motor wiring was reversed that it would keep moving Z up till it failed. Homing again gets the same result where Z is 5-10mm higher than where it stopped before.

https://youtu.be/IID9n4psiPo

**Comment by Deneteus** [comment]
Not even 10 seconds after I recorded a video I figured out it was the end stop switch. 

The JST connector was plugged in but a single pin had slipped out. As soon as I locked the pin in the JST connector and reconnected it. Then it Z axis homed correctly.

**Comment by thinkyhead** [comment]
Thanks for the update!
