### ISSUE TITLE
[FR] Wanhao D6 Example Configuration files

### ISSUE THREAD

**Issue by Deneteus** [MarlinFirmware/Marlin#8421]
I just recently created some configuration files for the Wanhao D6 for use with the Bondtech Wanhao D6 Upgrade. The upgrade has you change the default eSteps to 415 via a command added to your start GCODE. That means its a hassle if you change Slicers using multiple computers and you forget that setting. I built mine using 11/10 Bugfix 1.1.x and I know FW 1.1.7 is out soon so I am going to wait till you have it posted to attach my files.

Bondtech D6 BMG
http://shop.bondtech.se/ec/upgrade-kits/wanhao/extruder-upgrade-kit-wanhao-d6.html

I also sent an email to support@wanhao3dprinter.com to see if they will officially send me the D6 default configs since their firmware is pretty old at this point. 

D6 Stock Settings Referenced from @dod-bob  https://github.com/dot-bob/Marlin-Duplicator-6

**Comment by dot-bob** [comment]
I submitted two pull requests with example configurations for the Duplicator 6 in Stock form for both bugfix-1.1.x and bugfix-2.0.x (see #8614 and #8615).  I didn't include any for the bondtech extruder or any auto level probes at this time.  This will give most people a good starting point to work with.
