### ISSUE TITLE
How to add HTML file with embedded JS to Marlin docs ?

### ISSUE THREAD

**Issue by fiveangle** [MarlinFirmware/Marlin#8427]
@thinkyhead : how can the HTML file with embedded JS be published so that it so it works and can be linked to from the .md page on Lin-Adv ?  This is the latest rev that will start with if you want to just make this work.  Once it has a home in the repo, it can be finalized (typos, formatting, etc):

https://github.com/Sineos/k-factorjs/blob/master/k-factor.html

**Comment by thinkyhead** [comment]
In the MarlinDocumentation `master` branch, have a look at `_includes/navbar.html` (`converter.html` link) and the folder `_tools/u8glib` for a prime example.

**Comment by fiveangle** [comment]
resolved with https://github.com/MarlinFirmware/MarlinDocumentation/pull/101/commits
