### ISSUE TITLE
No example files

### ISSUE THREAD

**Issue by android444** [MarlinFirmware/Marlin#8466]
The files are missing in bugfix 1.1.x and bugfix 2.0.x.

**Comment by Tannoo** [comment]
You mean these?

https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x/Marlin/example_configurations

https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/Marlin/src/config/examples

**Comment by android444** [comment]
Where is RAMPS and more boards?

**Comment by Tannoo** [comment]
Ramps is not a controller or a printer model.

**Comment by android444** [comment]
There was always RAMPS board.

**Comment by Tannoo** [comment]
Not in examples. These are printer make/model example configurations.

**Comment by Tannoo** [comment]
You select a supported controller board from the boards.h file.

Ramps is named there. Although, it's still not a controller, but that's what most ATMega setups use and are known as RAMPS.

**Comment by Tannoo** [comment]
Mortherboard, rather..

**Comment by Tannoo** [comment]
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/boards.h

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/core/boards.h

**Comment by android444** [comment]
I understand. thanks.
