### ISSUE TITLE
[FR] Prevent axis damages

### ISSUE THREAD

**Issue by mikko70** [MarlinFirmware/Marlin#8467]
I hope new option or via Configuration.h

10mm axis movement disabled before you are homing first. It is too fast for moving, if you are wrong place.

code Marlin 1.16 ultralcd.cpp (row about 3070): 
Before: 
```cpp
   MENU_BACK(MSG_MOVE_AXIS);
     MENU_ITEM(submenu, MSG_MOVE_10MM, lcd_move_menu_10mm);
     MENU_ITEM(submenu, MSG_MOVE_1MM, lcd_move_menu_1mm);
     MENU_ITEM(submenu, MSG_MOVE_01MM, lcd_move_menu_01mm);
    END_MENU();
```

After (spaces before 10mm menu, seems be missing):
```cpp
   MENU_BACK(MSG_MOVE_AXIS);
	if ((axis_known_position[X_AXIS] && axis_known_position[Y_AXIS] && axis_known_position[Z_AXIS]))            
            MENU_ITEM(submenu, MSG_MOVE_10MM, lcd_move_menu_10mm);
	MENU_ITEM(submenu, MSG_MOVE_1MM, lcd_move_menu_1mm);
    MENU_ITEM(submenu, MSG_MOVE_01MM, lcd_move_menu_01mm);
    END_MENU();
```

[ultralcd.zip](https://github.com/MarlinFirmware/Marlin/files/1481698/ultralcd.zip)

**Comment by Tannoo** [comment]
`NO_MOTION_BEFORE_HOMING` won't work?

**Comment by mikko70** [comment]
I think then no any motion?

**Comment by Tannoo** [comment]
Correct.

**Comment by mikko70** [comment]
I think this can hardcoded  somewhere prevent all (new) users.

**Comment by Tannoo** [comment]
In ` Configuration.h`:

```
//#define NO_MOTION_BEFORE_HOMING  // Inhibit movement until all axes have been homed
```

It's not enabled by default.

**Comment by boelle** [comment]
wrong label, should be feature request (Hint: REQ)
