### ISSUE TITLE
[2.0 bgfix] Bug - Delay not work in ultralcd_st7920_u8glib_rrd_AVR.cpp

### ISSUE THREAD

**Issue by android444** [MarlinFirmware/Marlin#8471]
Delay does not work in ultralcd_st7920_u8glib_rrd_AVR.cpp
In version 1.1.x otherwise this was done.

**Comment by thinkyhead** [comment]
It seems like the 1.1.x and 2.0.x versions of these files differ a bit, with some new updates to the 1.1.x branch that never made it to 2.0.x. Does it seem like we should bring over all the 1.1.x changes to 2.0.x?

**Comment by android444** [comment]
I don't know

**Comment by Bob-the-Kuhn** [comment]
What board are you compiling for?

**Comment by android444** [comment]
Silver gate. I try on RAMPS - it was the same.

**Comment by thinkyhead** [comment]
Presuming solved.
