### ISSUE TITLE
Bug Homing,M851 and G33 P1  bugfix-2.0.x

### ISSUE THREAD

**Issue by cdedwards** [MarlinFirmware/Marlin#8476]
the value of M851 is being subtracted from the correct delta height twice. run G33 P1, and the delta height goes from a correct value to a value which is Delta height - M851 * 2. My second delta is running a Re-Arm board and doesn't have a sensor. I built one which attaches to the hotend therefore the switch is lower than the nozzle by 21.31mm. My correct height is 207.35mm. M851 is set to 21.31 (yes I fixed the configuration.h z_max/min). After G33 P1, my new delta height is now 164.77. which is 2 x the value in M851.  I also get a homing failed error.

**Comment by thinkyhead** [comment]
I'm favoring the removal of the modification to `delta_height` (and _**any**_ other things) in response to `M851 Z`. I think it's an attempt to be too clever, and it only opens us up more issues of this kind. The very specific intent of the z probe offset is to determine the behavior of the probe, and if you change the probe offset, it should pertain to the next `G29`, `G30`, etc., and not retractively apply to every previous stored probe result. If people want to raise or lower all the values in the mesh, we can certainly add or augment a different G-code to achieve that. And we already have `M665 H` to change the delta height.

**Comment by thinkyhead** [comment]
The PRs #8456 #8458 now include a total removal of all cleverness tied to `M851`.

**Comment by thinkyhead** [comment]
Give `bugfix-2.0.x` another try and see if it works better now. I got the idea that you were doing an `M851` somewhere in your process. Be sure to use `M851 Z-21.31` and to also set your `Z_PROBE_OFFSET_FROM_EXTRUDER` to `-21.31`. That minus sign is very important.

**Comment by LVD-AC** [comment]
Z_probe_offset should be negative if the probe is below the nozzle.

`#define Z_PROBE_OFFSET_FROM_EXTRUDER 0.10  // Z offset: -below +above  [the nozzle]
`
