### ISSUE TITLE
SDSUPPORT NOT WORKING MARLIN 2.0 MKS_SBASE_1.3 REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

### ISSUE THREAD

**Issue by maar1201gh** [MarlinFirmware/Marlin#8498]
[configurtion_marlin_2.0.zip](https://github.com/MarlinFirmware/Marlin/files/1485854/configurtion_marlin_2.0.zip)

In the meantime I send the gcode files through the computer

Thanks

**Comment by Bob-the-Kuhn** [comment]
I'm afraid that you're stuck with sending the gcodes through the computer for the time being.  

Making the SD card on the LCD controller functional is still a work in progress.

**Comment by Spawn32** [comment]
Or get a MKS TFT works fin with printing from sd :) it uses only a serial connection to the MKS SBASE

**Comment by Bob-the-Kuhn** [comment]
There is an ugly method of getting access to the LCD's SD card.  It requires making an octopus cable and using some non-standard options.  These non-standard options could get wiped out if you upgrade to a newer version of Marlin 2.0.x.

The octopus cable may not be so bad.  You could use the two cables that came with the RepRap Discount Full Graphics controller and a single [Adafruit 10-pin IDC Socket Rainbow Breakout Cable [1199] ](https://www.adafruit.com/product/1199).

I may not be able to get to the software this week.

**Comment by Bob-the-Kuhn** [comment]
The software change turned out to be pretty simple.  Try this:
1. In the directory HAL_LPC1768 replace the file spi_pins.h with this one  [spi_pins.zip](https://github.com/MarlinFirmware/Marlin/files/1486620/spi_pins.zip)
2. ~Move the wire from EXP2-2 to J8-2~
3. ~Move the wire from EXP2-1 to J8-3~
4. ~Move the wire from EXP2-6 to J8-4~

----

UPDATE    3 DEC 2017

I forgot about the backwards LCD connectors on MKS products.
```
MKS   RepRap
1      10
2       9
3       8
4       7
5       6
6       5
7       4
8       3
9       2
10      1
```


The corrected pin numbers on the MKS Sbase board are:
2. Move the wire from EXP2-9 to J8-2
3. Move the wire from EXP2-10 to J8-3
4. Move the wire from EXP2-5 to J8-4

In order to attach the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER you'll need to do something like one of the following for both EXP1 & EXP2:
a) on one end only,  shave the keying plug off the cable and plug the cable in backwards
b) on one end only, carefully pry the housing off the boar, rotate them 180 degrees and press them back onto the pins
c) make custom cables where one connector is rotated 180 degrees

Because you'll need a custom cable solution for EXP2 no matter what I suggest using something like the  Adadfruit octopus cable mentioned earlier

**Comment by karabas** [comment]
Already used them for LCD2004 ( reprap discount smart controller) :((

**Comment by Bob-the-Kuhn** [comment]
Any available pins will do.  You'll need to change spi_pins.h to match.

**Comment by Pentelfrost** [comment]
So I'm using the MKS TFT/Wifi to send my gcode currently. Is there anyway to use the onboard SD for gcode? Using smoothieware the TFT would show the internal card and also an EXT dir which I assume was for the LCD but with Marlin I just get No SD card even though using M50X commands creates an eeprom.dat file on the internal SD.

**Comment by Bob-the-Kuhn** [comment]
Marlin can not currently use the main board's on-board SD card for gcode files.  Right now only the LCD's SD card can be used for gcode files.  Unfortunately that isn't officially supported yet.

**Comment by maar1201gh** [comment]
@Bob-the-Kuhn 
I did the changes to EXP2 cable and SD CARD Is working now.
Thank you.

**Comment by ghost** [comment]
Hello, an error occurs when the installation of Marlin 2.0 mks sbase. Board appears in device Manager as" usb device marlin " My steps for installation.

I downloaded the Marlin 2.0
Set Atom
Downloaded PIO
Changed the #define MOTHERBOARD BOARD_MKS_SBASE
IN the lower left corner clicked on PIO Bulid (дсз1768)
Downloaded firmware.bin from .pioenvs/lpc1768 7) zacamil on the stick
connect the charge mks sbase and it appears as :" marlin usb device "
What are your thoughts...
![mkssbase](https://user-images.githubusercontent.com/34142344/33480728-c7082972-d6a2-11e7-9b03-7ebc257eb3c4.PNG)

**Comment by lkvapil** [comment]
@Bob-the-Kuhn 

> Move the wire from EXP2-2 to J8-2
Move the wire from EXP2-1 to J8-3
Move the wire from EXP2-6 to J8-4

Do you mean the pins on Sbase labeled as EXP2  and pins like on the image on url ?

 [https://www.google.cz/search?q=pin+header+numbering&prmd=isvn&source=lnms&tbm=isch&sa=X&ved=0ahUKEwidtfeNnezXAhVF6KQKHSnyBIMQ_AUIESgB&biw=360&bih=564#imgrc=VTT_65kYYvdQMM:](url)

Thanks

**Comment by Bob-the-Kuhn** [comment]
Yes, the 2x5 header labeled EXP2 on the board.  NOT the one labeled AUX1 on the board..


![mks_sbase_picture](https://user-images.githubusercontent.com/20692583/33528389-2e9a7300-d825-11e7-8cfe-6f3d804f3191.jpg)
![mks_sbase_pinout](https://user-images.githubusercontent.com/20692583/33528390-2eb8311a-d825-11e7-8d3b-81bf357705b9.jpg)

**Comment by Bob-the-Kuhn** [comment]
@vladimirRUS007 

Looks like you need to install the correct driver for the virtual disk. See the [Smoothieware drivers page](http://smoothieware.org/windows-drivers) for instructions.


Here's what my Re-ARM card looks like.

![image](https://user-images.githubusercontent.com/20692583/33528483-a585ed9a-d826-11e7-8627-21ba9059afcc.png)

**Comment by lkvapil** [comment]
So if the schematic is correct, so it won´t work again.. (and I changed the spi_pins.zip too)

![sbaselcdschematic](https://user-images.githubusercontent.com/16653942/33529141-a3cace58-d86c-11e7-893f-9424eb4b60bc.jpg)

**Comment by Bob-the-Kuhn** [comment]
Don't tie the pins together.  You'll need a custom cable.  In that custom cable you'll need to move the pin/wire that used to go to P0.8 to J8-3, P0.7 to J8-2 and P0.5 to J8-4

MKS & their %^*@##$% backwards LCD connectors!!!

Please see my updated/corrected comment above.

**Comment by Spawn32** [comment]
@Bob-the-Kuhn Does a LOL fit here ? 😄

**Comment by Bob-the-Kuhn** [comment]
Not much else we can do.  The MKS %^$* pain is here to stay which means constantly having to re-explain the problem & the solution.

**Comment by Spawn32** [comment]
Maybe we could add a readme in the SBASE examples directory ?

**Comment by Bob-the-Kuhn** [comment]
Great idea!  

I'll add it in a bit.

**Comment by Spawn32** [comment]
yes, would probably be the right place to add things like this for all board's and shields...
Would probably offload the ISSUE queue a lot :)

**Comment by karabas** [comment]
![mks-sbase-3dq_mods](https://user-images.githubusercontent.com/67457/33543348-bad3e8e8-d8e7-11e7-9808-dea3fcd4d486.jpg)
This is the mod for LCD2004 non graphic display  rrd smart controller
I need more spare pins for sdcard

**Comment by lkvapil** [comment]
@Bob-the-Kuhn  Will give a try the new idea..
I had to get working letters to turn 180° the connectors on one side of connectors

**Comment by Bob-the-Kuhn** [comment]
@karabas -yes, the RepRap Smart Controller uses those pins.  Thanks for the connection diagram.

You can use any free pins for the SD card.  You'll just need to modify the spi_pins.h file accordingly.

The "Cut CDdetect" - what is that for?

**Comment by lkvapil** [comment]
Many thanks to everyone, who gave me some advice ! ! !! 
Now I can see :D print from SD card and it works ! ! 
So first of all to get working the LCD to show the letters I had to cut the stumps on 1 side of connectors EXP1 & EXP2 and turn the connectors behind the LCD 180°..
So on MKS Sbase are connectors slipped right direction and on LCD 180°..
Then, as said @Bob-the-Kuhn here : 

> The corrected pin numbers on the MKS Sbase board are:
> 2. Move the wire from EXP2-9 to J8-2
> 3. Move the wire from EXP2-10 to J8-3
> 4. Move the wire from EXP2-5 to J8-4I

I picked up some jumpers and connected wires from EXP2 connector as described above..
And connected obviously the other wires to EXP2 connector on the Sbase...
Last step, I changed the spi_pins.h as uploaded above and rebuilt..

Many thanks to everyone ! !

**Comment by karabas** [comment]
On Sbase both cddetects of onboard sdcard and display sdcard join together on one pin!!!!!
So if you change sdcard in display cddetect will NOT do any action. You can check it trying to display several sdcards with different content.

**Comment by teddybee** [comment]
Could somebody tell me what is the difference between the reprap full graphics lcd and the Anet A6 12864 LCD pinout? (it doesn't have an sdcard reader)  [https://ae01.alicdn.com/kf/HTB1NqVoQFXXXXXiXpXXq6xXFXXXj/Anet-12864-LCD-Smart-Display-Screen-Controller-Module-with-Cable-3D-Printer-Accessory-for-Reprap-3D.jpg](url)
I didn't find so much code for Anet LCD on mks sbase's pins.h so I turned on the reprap lcd in config file. I rotated the lcd's plugs 180° but still just the backlight turned on and keeps beeping...

**Comment by lkvapil** [comment]
Hi,

I moved to SBASE again and now I´m again troubleshooting connection with RepRap Discount Full Graphics controller. 
I did the proccess as before and potenciometer won´t work on the controller.

Lukas
