### ISSUE TITLE
A better way to enumerate G- and M-codes?

### ISSUE THREAD

**Issue by whosawhatsis** [MarlinFirmware/Marlin#850]
I've been brainstorming for a few days trying to come up with a better way to enumerate the G- and M-codes known by the firmware and link them to their functions, but it looks like the answer will be in an area of programming that I'm not very familiar with (because most of my experience is in higher-level languages that would make what I'm trying to do easy, and damn the consequences for speed and memory usage). I'm looking for something that will meet the following criteria:

1. Each code should point to a named function. These functions can be defined with the inline keyword which (as I understand it) should make them compile the same way as if the code were inline, but it would make the list of codes much easier to read than the current switch statement full of inline codes linked to mis-ordered M-codes. Using named functions will also make the source somewhat self-commenting, which would help with some of the inconsistencies in the current comments.
2. The list of codes that a code received is checked against should be a data structure, like an array, that would allow the list to be serialized and converted to a string, so that the printer can have a code that reports a list of the G- and M-codes it understands, without needing to maintain a second copy of this data just for this purpose (which would increase program size, though probably not memory usage, if done right) and make it possible for the two lists to get out of sync.
3. Obviously, increases in processor/memory usage to perform the existing behavior are undesirable, as well as significant increases in the compiled program size.

My research has indicated that the current switch statement is probably being compiled to a hash table or lookup table (I've never used either directly, and I'm not entirely clear about the difference) to make it faster than an if... else if... else construction. The latter construction could be built to loop through an array and check each element for a match to the received code, which would make 1 and 2 easy, but violates 3.

Because the compiler creates one of these tables from the current switch statement, it should be possible to create this table explicitly so that it can be used to better-organize the code for 1, and allow the table to be referenced in other ways to satisfy 2, while the way the code recognition occurs in the compiled code would be the same that it is now, satisfying 3.

What I'd like is input from others on whether these are goals worth pursuing, and any better ideas about how to implement them (and obviously, any help doing so).

**Comment by thinkyhead** [comment]
TBC @ #1456 **_many inline functions**_
