### ISSUE TITLE
Question: #define PENDING(NOW,SOON) ((long)(NOW-(SOON))<0)

### ISSUE THREAD

**Issue by Amachete** [MarlinFirmware/Marlin#8517]
Hello

Where is defined SOON and NOW.

I am new at coding, I have been googling and searching for this information but I have not been able to get it.

i am not able to find their definition. It is just to study the code and learn.

Thank you.

Bye.

**Comment by teemuatlut** [comment]
`NOW` and `SOON` are the macro parameters.

So `PENDING(1,2)`
becomes `((long)(1-(2))<0)`

[Further reading about macro definitions](http://www.cplusplus.com/doc/tutorial/preprocessor/).

**Comment by thinkyhead** [comment]
Specifics of these macros…
http://marlinfw.org/docs/development/coding_standards.html#time-comparison
