### ISSUE TITLE
EEPROM not working correctly in last builds on MKS BASE

### ISSUE THREAD

**Issue by mexusbg** [MarlinFirmware/Marlin#8529]
### Bug Report
- Description: EEPROM values are not read by Repetier Host or Octoprint. Changes made to the EEPROM are not saved. I've reset the EEPROM to default values. But it still doesn't work.
EEPROM works perfect on Build 1.1.1 but not on Build 1.1.6.
Steps per mm and other values are 0 when read from EEPROM. Setting them to the correct value, storing the settings, reading them back and they are still 0-s

My configurations:
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1498693/Marlin.zip)

**Comment by AnHardt** [comment]
It's always nice to know what went wrong.
I don't make statistics, but it will get a exclamation make, somewhere in my memory.
Not activated EEPROM?

**Comment by mexusbg** [comment]
@AnHardt  I don't know what went wrong. EEPROM was activated. There was a wrong board selected in configuration.h - but this was not the problem.
Tried the RC-Fix version and it worked.
Then started working on 1.1.6 again and made few changes at a time and cannot pinpoint which one got the eeprom settings working properly. I don't have time to reproduce the problem.
I'll post my working configs just in case if it helps.

[Working configs.zip](https://github.com/MarlinFirmware/Marlin/files/1501297/Working.configs.zip)

**Comment by mexusbg** [comment]
@AnHardt Investigated a bit more:
one of the following options breaks EEPROM/Settings saving (reported values are zeroes and cannot be changed)
```cpp
#define INCH_MODE_SUPPORT
```
or
```cpp
#define TEMPERATURE_UNITS_SUPPORT
```
