### ISSUE TITLE
BUG: encoder button BTN_ENC broken in bugfix-1.1.x

### ISSUE THREAD

**Issue by karabas** [MarlinFirmware/Marlin#8537]
RRD Smart Controller + arduino 2560./ ramps1.4
I am able to change frame rate on display rotating encoder. But encoder button does not work.
1.1.6  - works!
I tried to replace pins_ramps.h to file from 1.1.6 - nothing changes.

I copied old configuration.h, modified version and soft enstops and it works!
I compared both files with Meld utility - no sighnificant differences...

Finally found:
If you activate G26_MESH_VALIDATION (!) the encoder button stops working.

I have not Zprobe sensor so my config is:
Manual Probe
Manual mesh leveling or bilinear
Reprapdiscount smart controller.

**Comment by benlye** [comment]
Related to #8522?

**Comment by pmbroth** [comment]
Sorry, I did not see this error already opened.  But I will still leave mine opened.  :-)

**Comment by Bob-the-Kuhn** [comment]
Try it with the latest 1.1.x

It worked for me with a failing config from another issue.   I did the download about 15 minutes ago.

**Comment by thinkyhead** [comment]
I'm glad to hear the encoder works properly. I noticed that the condition in `lcd_update` for the user-click debouncer was reversed. I just now patched it in https://github.com/thinkyhead/Marlin/commit/59a699063a49c1384c184c22ddccc12aa9feb538. So, the right-now `bugfix-1.1.x` should be in best shape.
