### ISSUE TITLE
Bugfix 1.1X,  REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER    Dial not work on controller.

### ISSUE THREAD

**Issue by pmbroth** [MarlinFirmware/Marlin#8546]
Hello,
I downloaded Bugfix 1.1 today, made my configuration changes as I always do, uploaded and all works well except on the controller dial does nothing. Clicking it, or tuning it - no affect.  I have ensured the controller is enable, and looked at all my changes as I always use winmerge to do so.   I rolled back to my distribution from 10/25 and all works.  So something  had to change some where.  Thank you.

**Comment by benlye** [comment]
Same as #8537?  

Does it work if you disable G26_MESH_VALIDATION?

**Comment by pmbroth** [comment]
Trying it now, I will let you know

**Comment by pmbroth** [comment]
With G26 Mesh Validation disabled - still does not work..

**Comment by pmbroth** [comment]
I have attached configs from 10/25 that work with my printer
[config.zip](https://github.com/MarlinFirmware/Marlin/files/1502442/config.zip)

**Comment by pmbroth** [comment]
[config 1124.zip](https://github.com/MarlinFirmware/Marlin/files/1502471/config.1124.zip)
config for my printer that do not work, based on changed config compared to my previous config that work 10/25, posted in last post

**Comment by Bob-the-Kuhn** [comment]
Maybe the bug has been fixed.  They've been working on a couple of issues today.

I downloaded bugfix-1.1.x about 10 minutes ago, copied over the two config.1124.zip files, compiled with Arduino 1.8.4 and the encoder works on the main/info screen and on the submenus.

**Comment by Bob-the-Kuhn** [comment]
Per the notes in Issue #8537, 1.1.x was changed about 20 minutes ago to fix this issue.

**Comment by pmbroth** [comment]
Hello, I just downloaded, and the fix seems good, all is working!  I will test more tomorrow, but the dial works great!  Thank you
