### ISSUE TITLE
[FR] LIN ADVANCE only for the outer layers

### ISSUE THREAD

**Issue by BeerStein** [MarlinFirmware/Marlin#8594]
Would it be at all possible to enable LIN ADVANCE only for the outer layers. I believe that is where one need  quality improvement.  Doing LIN Advance during say a honeycomb infill only adds noise during the print. 
Thanks for all the hard work.

**Comment by coolio986** [comment]
I don't know of any way to add this in firmware directly. The gcode parser doesn't know the difference between infill and outer perimeters, only the slicer would know that. 

One could make the case that the slicer could inject M900 Kxx (where xx is the linear advance factor) for perimeters, then M900 K0 to disable it for infill. But that could interfere with the E counts when turned on and off in the motion planner.

**Comment by thinkyhead** [comment]
If your slicer can insert G-code at the start of perimeters and different G-code at the start of infill, you can have it insert `M900 K[yourKvalue]` at the start of infill and `M900 K0` at the start of perimeters.

**Comment by thinkyhead** [comment]
Marlin can't differentiate between infill and perimeters. If your slicer can insert G-code at the start of perimeters and different G-code at the start of infill, you can have it insert `M900 K[yourKvalue]` at the start of perimeters and `M900 K0` at the start of infill.

**Comment by thinkyhead** [comment]
> that could interfere with the E counts when turned on and off in the motion planner.

I'm pretty sure there's no problem, since the previous move finishes before the new `M900` takes effect, and the high-level E value works just the same with and without advance.

**Comment by ghost** [comment]
I can confirm that injecting M900 in the gcode to enable lin advance only for permiters works just fine. Did it for a while when I had a bowden set up.

Using Simplify3D, I added this to my post processing commands:
```
{REPLACE "perimeter\nG" "perimeter\nM900 K400\nG"}
{REPLACE "; solid layer\n" "; solid layer\nM900 K0\n"}
{REPLACE "fill\n" "fill\nM900 K0\n"}
{REPLACE "; skirt\n" "; skirt\nM900 K0\n"}
{REPLACE "; bridge\n" "; bridge\nM900 K0\n"}
```
No idea how to do this with other slicers.

**Comment by BeerStein** [comment]
Thanks to all who have responded. 
Jim, I am using slic3r and will certainly investigate the possibility to add some processing commands. Thanks for the tip.

Leaving this one open for a while. Hopefully I could find a solution for slic3r. If so I will post it.

**Comment by PolloPequeno** [comment]
@JimBrown, that's quite the K value! I think I'm using 15. You running a bowden setup?

**Comment by coolio986** [comment]
I use a K of 200-250 on my bowden setup, 20 - 40 on direct.

**Comment by ghost** [comment]
@Lonczakt, yes, I was. Now using direct drive and K value is 40.
