### ISSUE TITLE
G26 Prints Incomplete Pattern with Bilinear Levelling

### ISSUE THREAD

**Issue by benlye** [MarlinFirmware/Marlin#8609]
I'm trying out G26 on my printer (Cartesian RAMPS setup) with bilinear levelling and the test pattern is weird.  
* There are lines missing
* Some lines are printed multiple times
* The lines seem out of alignment with the circles (they don't make the little cross-hair pattern)

Config files as well as serial output from the test with G26 debug enabled are attached.  This is with bugfix-2.0.x downloaded and compiled tonight.

The missing lines are not bad adhesion - they were never printed:
![img_20171130_203703](https://user-images.githubusercontent.com/23322579/33454358-87450900-d610-11e7-9282-c6d69a60df9d.jpg)

The crosshairs don't line up:
![img_20171130_203640 large](https://user-images.githubusercontent.com/23322579/33454377-95cb3cd8-d610-11e7-9c4c-7555d7218214.jpg)

[config.zip](https://github.com/MarlinFirmware/Marlin/files/1519450/config.zip)
[serial.log](https://github.com/MarlinFirmware/Marlin/files/1519453/serial.log)

If this isn't supposed to fully work with bilinear levelling yet, I'm happy to be told that's the case.

Ben

**Comment by Roxy-3D** [comment]
It is supposed to work with Bi-Linear.   But you maybe the first person to use it.

**Comment by benlye** [comment]
> It is supposed to work with Bi-Linear. But you maybe the first person to use it.

OK, good to know.

I goofed up the config files in the first post, and posted them while in the middle of a Github merge.  Here are the correct ones.

[config-corrected.zip.zip](https://github.com/MarlinFirmware/Marlin/files/1519521/config-corrected.zip.zip)

**Comment by Roxy-3D** [comment]
I'm bringing up a new mesh on a new piece of glass.  The mesh needs to be fine tuned.  But the G26 pattern prints correctly with UBL.   We might need somebody with C coding skills that is running Bi-Linear to take a look at this:

![20171130_183205](https://user-images.githubusercontent.com/8404322/33462608-156b5ada-d5fe-11e7-8362-6d6ae635369b.jpg)

**Comment by benlye** [comment]
I've been trying to wrap my head around this...

The configuration was for a 5x5 bilinear grid, with these boundaries:
```
  #define LEFT_PROBE_BED_POSITION 15
  #define RIGHT_PROBE_BED_POSITION 195
  #define FRONT_PROBE_BED_POSITION 15
  #define BACK_PROBE_BED_POSITION 180
```

So probe point [0,0] is at [15,15] and the distance between horizontal mesh points is 45.

In G26.cpp:
```
#define SIZE_OF_INTERSECTION_CIRCLES 5
#define SIZE_OF_CROSSHAIRS 3
```

So there should be circles at [60,15] and [105,15] and a horizontal line between them from [62,15] to [103,15].

According to the log this is the line which was printed:
`Recv:  Connecting with horizontal line (sx=107.00, sy=15.00) -> (ex=60.00, ey=15.00)`

Still trying to work out why 😕

**Comment by Roxy-3D** [comment]
Those probe bed positions are not used by UBL.    You can reserve a border around the bed with INSET.

It might make sense to capture the entire debug log.   And while you are doing that, please pay attention to the question:  Does the nozzle go to the areas where no lines are being printed?  Or does it totally ignore those areas of the bed?

**Comment by benlye** [comment]
I'm not using UBL.  The entire debug log is in the first post.

The nozzle goes to all areas, as all the circles seem to be printed correctly, it's the lines between them that are screwed up.

**Comment by benlye** [comment]
A couple more observations:
* Lines printed 'forward' (i.e. low X to higher X) seem OK, only lines printed backwards appear to be too long

e.g. `Recv:  Connecting with horizontal line (sx=17.00, sy=56.00) -> (ex=58.00, ey=56.00)` is OK (17-58 is right)

* There are lots of short backwards lines, e.g. 
`Recv:  Connecting with vertical line (sx=15.00, sy=58.00) -> (ex=15.00, ey=55.00)`

What I don't understand (yet) is why lines are planned backwards at all.  I know that the printing will be reversed if nozzle is nearer the end than the beginning, but that seems to happen after the line is planned and the debug output written, so even for a reversed line it should appear in the log as 'forwards'

I'm suspicious of these lines:
```
sx = _GET_MESH_X(  i  ) + (SIZE_OF_INTERSECTION_CIRCLES - (SIZE_OF_CROSSHAIRS)); // right edge
ex = _GET_MESH_X(i + 1) - (SIZE_OF_INTERSECTION_CIRCLES - (SIZE_OF_CROSSHAIRS)); // left edge
```

Because the maths doesn't correlate to the comments - `GET_MESH_X(i + 1)` should be to the right of `GET_MESH_X( i )` not the left, shouldn't it?

I guess my question is are the lines supposed to be planned for printing left to right or right to left (or both, and I really don't understand what's going on here)?

**Comment by Roxy-3D** [comment]
Yeah...  Those comments are wrong.   It scans through each circle and looks to see if the circle next to it exists.  If it does and there isn't a line there, it puts a lint there.    But the left and right comments are flipped.

Lets replace this function with this code.   There is extra debug information to tell us when a line isn't drawn because one coordinate of the line is not reachable.
```
  inline bool look_for_lines_to_connect() {
    float sx, sy, ex, ey;

    for (uint8_t i = 0; i < GRID_MAX_POINTS_X; i++) {
      for (uint8_t j = 0; j < GRID_MAX_POINTS_Y; j++) {

        #if ENABLED(NEWPANEL)
          if (user_canceled()) return true;     // Check if the user wants to stop the Mesh Validation
        #endif

        if (i < GRID_MAX_POINTS_X) { // We can't connect to anything to the right than GRID_MAX_POINTS_X.
                                     // This is already a half circle because we are at the edge of the bed.

          if (is_bitmap_set(circle_flags, i, j) && is_bitmap_set(circle_flags, i + 1, j)) { // check if we can do a line to the left
            if (!is_bitmap_set(horizontal_mesh_line_flags, i, j)) {

              //
              // We found two circles that need a horizontal line to connect them
              // Print it!
              //
              sx = _GET_MESH_X(  i  ) + (SIZE_OF_INTERSECTION_CIRCLES - (SIZE_OF_CROSSHAIRS)); // right edge
              ex = _GET_MESH_X(i + 1) - (SIZE_OF_INTERSECTION_CIRCLES - (SIZE_OF_CROSSHAIRS)); // left edge

              sx = constrain(sx, X_MIN_POS + 1, X_MAX_POS - 1);
              sy = ey = constrain(_GET_MESH_Y(j), Y_MIN_POS + 1, Y_MAX_POS - 1);
              ex = constrain(ex, X_MIN_POS + 1, X_MAX_POS - 1);

              if (position_is_reachable(sx, sy) && position_is_reachable(ex, ey)) {

                if (g26_debug_flag) {
                  SERIAL_ECHOPAIR(" Connecting with horizontal line (sx=", sx);
                  SERIAL_ECHOPAIR(", sy=", sy);
                  SERIAL_ECHOPAIR(") -> (ex=", ex);
                  SERIAL_ECHOPAIR(", ey=", ey);
                  SERIAL_CHAR(')');
                  SERIAL_EOL();
                  //debug_current_and_destination(PSTR("Connecting horizontal line."));
                }
                print_line_from_here_to_there(sx, sy, g26_layer_height, ex, ey, g26_layer_height);
              }
              else {
                  SERIAL_ECHOPAIR(" position not reachable for horizontal line (sx=", sx);
                  SERIAL_ECHOPAIR(", sy=", sy);
                  SERIAL_ECHOPAIR(") -> (ex=", ex);
                  SERIAL_ECHOPAIR(", ey=", ey);
                  SERIAL_CHAR(')');
                  SERIAL_EOL();
              }
              bitmap_set(horizontal_mesh_line_flags, i, j);   // Mark it as done so we don't do it again, even if we skipped it
            }
          }

          if (j < GRID_MAX_POINTS_Y) { // We can't connect to anything further back than GRID_MAX_POINTS_Y.
                                           // This is already a half circle because we are at the edge  of the bed.

            if (is_bitmap_set(circle_flags, i, j) && is_bitmap_set(circle_flags, i, j + 1)) { // check if we can do a line straight down
              if (!is_bitmap_set( vertical_mesh_line_flags, i, j)) {
                //
                // We found two circles that need a vertical line to connect them
                // Print it!
                //
                sy = _GET_MESH_Y(  j  ) + (SIZE_OF_INTERSECTION_CIRCLES - (SIZE_OF_CROSSHAIRS)); // top edge
                ey = _GET_MESH_Y(j + 1) - (SIZE_OF_INTERSECTION_CIRCLES - (SIZE_OF_CROSSHAIRS)); // bottom edge

                sx = ex = constrain(_GET_MESH_X(i), X_MIN_POS + 1, X_MAX_POS - 1);
                sy = constrain(sy, Y_MIN_POS + 1, Y_MAX_POS - 1);
                ey = constrain(ey, Y_MIN_POS + 1, Y_MAX_POS - 1);

                if (position_is_reachable(sx, sy) && position_is_reachable(ex, ey)) {

                  if (g26_debug_flag) {
                    SERIAL_ECHOPAIR(" Connecting with vertical line (sx=", sx);
                    SERIAL_ECHOPAIR(", sy=", sy);
                    SERIAL_ECHOPAIR(") -> (ex=", ex);
                    SERIAL_ECHOPAIR(", ey=", ey);
                    SERIAL_CHAR(')');
                    SERIAL_EOL();

                    #if ENABLED(AUTO_BED_LEVELING_UBL)
                      debug_current_and_destination(PSTR("Connecting vertical line."));
                    #endif
                  }
                  print_line_from_here_to_there(sx, sy, g26_layer_height, ex, ey, g26_layer_height);
                }
                else {
                  SERIAL_ECHOPAIR(" position not reachable for vertical line (sx=", sx);
                  SERIAL_ECHOPAIR(", sy=", sy);
                  SERIAL_ECHOPAIR(") -> (ex=", ex);
                  SERIAL_ECHOPAIR(", ey=", ey);
                  SERIAL_CHAR(')');
                  SERIAL_EOL();
                }

                bitmap_set(vertical_mesh_line_flags, i, j);   // Mark it as done so we don't do it again, even if skipped
              }
            }
          }
        }
      }
    }
    return false;
  }
```

**Comment by benlye** [comment]
Thanks, Roxy, I'll give it a whirl.  I've added a bit more debugging output of my own as well.  I think I'm getting close to figuring it out.

**Comment by Roxy-3D** [comment]
What ever is wrong...  It isn't much.    I say that for two reasons.  First, it works with UBL.   But the other thing is you do get a lot of circles and lines.    So what gives?    There is some small logic error that is causing trouble....

It will be interesting if those connecting lines are not being drawn because the 'position is not reachable'.   If that turns out to be the case, we will have to figure out why it is coming up with that idea.

**Comment by benlye** [comment]
Just ran the debug code.  There were no 'position not reachable' results.  I'm pretty sure that it's breaking when it tries to find the location of `_GET_MESH_X(i + 1)`.

I modified the debug output to include the index of the mesh point as well as it's coordinates.

Check this out:
`Recv:  Connecting sxi=1 at 60,15 with exi=2 at 61,15 with horizontal line (sx=62.00, sy=15.00) -> (ex=53.00, ey=15.00)`

exi=2 (as in X mesh location 2) should be at 105,15, yet it's given as 61, which is `_GET_MESH_X( i ) + 1` for i = 1.

So perhaps `_GET_MESH` works differently for ABL vs. UBL?

I'm closing in...

**Comment by Roxy-3D** [comment]
```
#if ENABLED(AUTO_BED_LEVELING_BILINEAR)
  #define _GET_MESH_X(I) bilinear_start[X_AXIS] + I * bilinear_grid_spacing[X_AXIS]
  #define _GET_MESH_Y(J) bilinear_start[Y_AXIS] + J * bilinear_grid_spacing[Y_AXIS]
#elif ENABLED(AUTO_BED_LEVELING_UBL)
  #define _GET_MESH_X(I) ubl.mesh_index_to_xpos(I)
  #define _GET_MESH_Y(J) ubl.mesh_index_to_ypos(J)
#elif ENABLED(MESH_BED_LEVELING)
  #define _GET_MESH_X(I) mbl.index_to_xpos[I]
  #define _GET_MESH_Y(J) mbl.index_to_ypos[J]
#endif
```
I'm wondering if bilinear_grid_spacing[X_AXIS] & bilinear_grid_spacing[Y_AXIS] are correct?   And for that matter...   Is bilinear_start[X_AXIS] and bilinear_start[Y_AXIS] correct?   We may want to print those out too with the error message.   It seems to be coming up with the wrong location.

**Comment by benlye** [comment]
Yep, chasing that down now.

**Comment by benlye** [comment]
Got it!

The problem is here,
`ex = _GET_MESH_X(i + 1) - (SIZE_OF_INTERSECTION_CIRCLES - (SIZE_OF_CROSSHAIRS));`

in the passing of `i + 1` to the macro:
`#define _GET_MESH_X(I) bilinear_start[X_AXIS] + I * bilinear_grid_spacing[X_AXIS]`

For i=2, the macro expands as:
15 + 2 + 1 * 45 = 63 (wrong) 

Change the macros to evaluate the input parameter by enclosing it in parentheses:
```
#define _GET_MESH_X(I) bilinear_start[X_AXIS] + (I) * bilinear_grid_spacing[X_AXIS]
#define _GET_MESH_Y(J) bilinear_start[Y_AXIS] + (J) * bilinear_grid_spacing[Y_AXIS]
```
And it evaluates as:
15 + (2+1) * 45 = 150 (right)

😄 

I'll put a PR together for that change - it doesn't seem like modifying the macro in that way will impact any other functionality.

**Comment by Roxy-3D** [comment]
We need to change both branches...   I can do it easier...  I'll do it right now!

THANKS SO MUCH!!!!    (It did turn out to be very simple logic problem!)

**Comment by benlye** [comment]
And here's the proof - it's a bit scruffy, but I think it's beautiful 😉 

![img_20171202_200556 large](https://user-images.githubusercontent.com/23322579/33519322-71d5afe2-d79c-11e7-9d69-1f3266e418e9.jpg)

Thanks, Roxy.

**Comment by Roxy-3D** [comment]
THANK YOU!!!

**Comment by benlye** [comment]
@Roxy-3D just saw your commit in bugfix-2.0.x - you put the parenthesis in the wrong place!

You changed it to `#define _GET_MESH_X(I) (bilinear_start[X_AXIS] + I * bilinear_grid_spacing[X_AXIS])`

But it needs to be `#define _GET_MESH_X(I) bilinear_start[X_AXIS] + (I) * bilinear_grid_spacing[X_AXIS]`

So that the part which gets passed as the parameter is evaluated first.

Ben

**Comment by benlye** [comment]
Never mind, fixed now 👍

**Comment by Roxy-3D** [comment]
Yeah...   I made a mistake....   But when I went and double checked things I found it.

**Comment by benlye** [comment]
BTW, I had to fix M49 to get the G26 debugging to work.  It's not super important, but I opened #8607 to fix it if you want to take a look.  It's a simple serial output fix.

**Comment by Roxy-3D** [comment]
That has kind of been on my To Do list.   It was the G26 stuff that necessitated having more debug information on the movement.   But  it was mis-named because it is also used within the UBL code.

I wonder if it would be better to fix this via:
```
 serialprintPGM(g26_debug_flag ? PSTR("On\n") : PSTR("Off\n"));
```
That adds two bytes of text but it eliminates the call to SERIAL_EOL();
