### ISSUE TITLE
Marlin 2.0 on MKS sbase 

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#8618]
Hello, error occurs when you install Marlin 2.0 mks sbase. Board appears in device Manager as "USB device marlin". My steps for installation.

1. I uploaded Marlin 2.0
2. Downloaded Atom
3. Uploaded PIO
4. Changed #define MOTHERBOARD BOARD_MKS_SBASE
5. In the bottom left corner clicked on PIO Bulid
6. Load the firmware.bin from .pioenvs / lpc1768 7) loaded on a microsd
7. hooked mks sbase, the Board appears in device Manager as "USB device marlin"
![mkssbase](https://user-images.githubusercontent.com/34142344/33481112-222ba800-d6a4-11e7-94e9-6cc7fa25bdc2.PNG)

What are your thoughts ...

**Comment by AnHardt** [comment]
Install the Smoothie device driver. See http://smoothieware.org/windows-drivers.

**Comment by ghost** [comment]
well, now try

**Comment by ghost** [comment]
driver installed, but nothing has changed

**Comment by ghost** [comment]
Thank you all, turned out...

**Comment by madmax2** [comment]
@vladimirRUS007 how did you fix it?

**Comment by thinkyhead** [comment]
@madmax2 — Full instructions for ARM installation are now posted at http://marlinfw.org/docs/basics/install_arm.html
