### ISSUE TITLE
Simultaneous extrusion of two extruders filament

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#8620]
Hi all. Required command G code, after which will begin simultaneously push the two plastic extruders.

**Comment by AnHardt** [comment]
Likely it needs more a new Configuration.h then a g-code.

**Comment by ghost** [comment]
ok, what do I change in the config?

**Comment by AnHardt** [comment]
Impossible to say - without your config - without you stating what variete you want to go to.

**Comment by ghost** [comment]
I want to use a marlin 2.0, but the configuration is not ready, because I can't make friends marlin 2.0 and MKS sbase

**Comment by vladimirRUS007** [comment]
driver installed, but nothing has changed

**Comment by ghost** [comment]
@AnHardt 
I don't know what to change in the configuration, I want to command g code like this.
G91 E0 E1
G1 F100 E1xxx E2xxx 
How to implement this?
![ex](https://user-images.githubusercontent.com/34142344/33503891-722c861a-d6f6-11e7-90c4-43fd1b4caecd.png)
the following files of my firmware

[config.zip](https://github.com/MarlinFirmware/Marlin/files/1523003/config.zip)

**Comment by bjarchi** [comment]
Is the goal of this to do what's called 'copy printing' or the like? In other words, to have both extruders simultaneously print the same object in a standard dual-extrusion setup? If so, that's already implemented in bugfix-1.1.x and I think also mainline 1.1.6.

You need to enable it in firmware, first, by finding the following define in `Configuration_adv.h`:
`#define DUAL_NOZZLE_DUPLICATION_MODE`
And making sure it is uncommented (therefore enabled)

Then you enable to dual-nozzle simultaneous extrusion mode before a print by issuing a G-code command `M605 S2` to put the machine into simultaneous extrusion mode. See the documentation for `M605` [here](http://marlinfw.org/docs/gcode/M605.html). 

I don't think this will get you independent control over the extrusion length for each extruder; not sure if that's important for your use case. You can enable a define to allow you to set different esteps/mm though - search for `//#define DISTINCT_E_FACTORS` in `Configuration.h`

**Comment by ghost** [comment]
@bjarchi 
Thank you

**Comment by bjarchi** [comment]
> Thank you

You're welcome; I'm glad to help! Does that solve your problem/question? If so you can mark the issue closed via the web interface and it will drop off of the open issues feed.
