### ISSUE TITLE
G code or function that returns which Gcode line is being printed

### ISSUE THREAD

**Issue by alequeiroz** [MarlinFirmware/Marlin#8626]
Hello to all, i´ve been working on a feature that shows on the lcd which G code line is been printing, both on SD, or Host software but i´m having some trouble determining which g code line is been printed to show on the lcd, is that already been implemented? An another thing, is there a way to star a print from a specific line of the g code?

**Comment by Roxy-3D** [comment]
No way currently to start the print from a specific line of GCode.  

The N parameter of a line of GCode is only available when printing is being done from a host.  It isn't present with a print from an SD-Card.   We could count lines of GCode withing the SD Memory card reader.   But is this worth displaying on the LCD Panel?
