### ISSUE TITLE
Not an issue but a tip: Compiling Marlin with Arduino in Windows 10 ?

### ISSUE THREAD

**Issue by Spawn32** [MarlinFirmware/Marlin#8642]
Turn of Windows 10 real-time virus protection, will give you about 10 times the compiling speed.
Please remember to turn it on again when you are finished :)

To bad you can't make a real-time protection exception rule in Windows :/

This works perfect in my windows 10 Insider (RS4) release and should be the same for normal releases as well...

**Comment by ghost** [comment]
But you can make real-time exclusions in Windows Defender... https://www.tenforums.com/tutorials/5924-add-remove-windows-defender-exclusions-windows-10-a.html

Are you sure this is a thing though? I just tried it with Defender on and off. I did not see any appreciable difference in speed. I did clear the Arduino cache before each run. Is it possible you are seeing the speed increase due to the second run using cached objects?

**Comment by Spawn32** [comment]
Did you try to turn the part called realtime protection off ? inside defender ? makes a hugh difference at least on the Insider releases, goes from taking 0.5 to 2 seconds for every compiler line to just flying through them..  (AMD Ryzen and a very fast M.2 samsung ssd)

Will have a look at that link, thanks :)

**Comment by Spawn32** [comment]
added an exception for the arduino folder and also the arduino-builder process, diden't help, turn'd off realtime protection and it was flying again , typical Microsoft, LOL

regarding "second run" if you close and restart arduino it builds from scratch, the cache is deleted when you close it..

**Comment by Tannoo** [comment]
I don't have an issue with PlatformIO flying through the compilation process. Is this just an Arduino IDE issue?

**Comment by ghost** [comment]
@Spawn32, yep, turned off realtime protection as you describe. Made no difference here. Typical Microsoft. ;-)

**Comment by Spawn32** [comment]
@JimBrown Have a look her, no ider whats going on, but it's crazy :)

And that's why i wrote this tip ;)

https://www.youtube.com/watch?v=ynwIXLhSONo&feature=youtu.be

**Comment by fiveangle** [comment]
My 4yr old Macbook Pro compiles literally  13 times faster than on Windows 10, with Arduino and PlatformIO temp and working directories whitelisted from Symantec Security.

Late 2013 1TB SSD-equipped 16GB DDR3 RAM MacBook Pro (22nm "Haswell/Crystalwell" 2.6 GHz Intel "Core i7" processor (4960HQ)):
```
AVR Memory Usage
----------------
Device: at90usb1286
Program:  116928 bytes (89.2% Full)
(.text + .data + .bootloader)
Data:       3973 bytes (48.5% Full)
(.data + .bss + .noinit)
========================= [SUCCESS] Took 10.21 seconds =========================
```

2 month old 512GB NVMe-equipped 16GB DDR4 RAM Dell Latitude 7280 with Symantec Endpoint Protection whitelisted build dirs (14nm "Kaby Lake/Coffee Lake" 2.8 GHz Intel "Core i7-7600U" processor):
```
AVR Memory Usage
----------------
Device: at90usb1286
Program:  117014 bytes (89.3% Full)
(.text + .data + .bootloader)
Data:       3981 bytes (48.6% Full)
(.data + .bss + .noinit)
 [SUCCESS] Took 143.58 seconds 
```

To add insult to injury, it's quite odd that resulting binary compiled with PIO on Windows 10 system is slightly larger in both PROGMEM and SRAM usage to same compiled on Mac OS.

Not trying to start a platform war, just reporting facts * shrug *

I'd quote the Arduino, but Arduino won't even compile on Windows 10 w/o hacks (and I haven't re-installed the latest 1.9 beta yet) but I can tell you that it didn't perform any miracles.

-=dave

**Comment by fiveangle** [comment]
I'll bet that if you load a Debian VM into Hyper-V and run PIO, it will run closer to the 11 second compile that it does on Mac OS (or faster !)

So the real tip sould be: don't use Windows to develop on with PlatformIO unless you're a masochist.

**Comment by TadyTheFish** [comment]
can i ask a noob question.. how do you compile Marli 2.0 with arduino ?

**Comment by ghost** [comment]
With Arduino IDE version 1.9.0-Beta (or newer.)

**Comment by TadyTheFish** [comment]
Does 1.9.0 need the teensyduino install? I'm asking because i's not supported... I want no compile for teensy 3.5
I was reading the latest release of teensyduino and it says that support was added for 1.9.0 beta but it expects 1.8.5

**Comment by thinkyhead** [comment]
If you're feeling adventurous, try PlatformIO. It might be simpler in the long run. Instructions are posted at http://marlinfw.org/ for ARM-based builds.
