### ISSUE TITLE
[2.x] Compile error when LCD_SET_PROGRESS_MANUALLY is defined

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#8644]
'ultralcd_impl_hd44780.h':
```cpp
#if DISABLED(LCD_SET_PROGRESS_MANUALLY)
  const uint8_t progress_bar_percent = card.percentDone();
#endif
if (progress_bar_percent > 2 && (ELAPSED(millis(), progress_bar_ms + PROGRESS_BAR_MSG_TIME) || !lcd_status_message[0]))
  return lcd_draw_progress_bar(progress_bar_percent);
```

'ultralcd_impl_dog.h':
```cpp
#if DISABLED(LCD_SET_PROGRESS_MANUALLY)
  const uint8_t progress_bar_percent = card.percentDone();
#endif

if (progress_bar_percent > 1) {
```

variable is not defined but used...

**Comment by thinkyhead** [comment]
You can use three-backticks for multi-line plaintext or code. See https://guides.github.com/features/mastering-markdown/

**Comment by thinkyhead** [comment]
Are you getting a real compile error or just scanning the code for logic errors?
```cpp
#if DISABLED(LCD_SET_PROGRESS_MANUALLY)
  const uint8_t progress_bar_percent = card.percentDone();
#endif
```
When `LCD_SET_PROGRESS_MANUALLY` is disabled there is no global variable named `progress_bar_percent` so the code defines a local variable with that name and assigns it from `card.percentDone()`.

When `LCD_SET_PROGRESS_MANUALLY` is enabled there is a global variable named `progress_bar_percent` which may be assigned the value of `card.percentDone()` in `lcd_status_screen`…
```cpp
    // Set current percentage from SD when actively printing
    #if ENABLED(LCD_SET_PROGRESS_MANUALLY)
      if (IS_SD_PRINTING)
        progress_bar_percent = card.percentDone();
    #endif
```

**Comment by GMagician** [comment]
Well, I was looking into code to know what was good to include and what was useless (for my printer of course).
I saw that part of code and I saw that it's true you don't have any 'progress_bar_percent' variable defined but in the same time you use it...
Check 'ultralcd_impl_dog.h'. After #ifdef #endif (line 570) you have an if clause that uses 'progress_bar_percent' and that can't be possible since you don't have any variable with such name

```cpp
    #if DISABLED(LCD_SET_PROGRESS_MANUALLY)
      const uint8_t progress_bar_percent = card.percentDone();
    #endif
    if (progress_bar_percent > 2 && (ELAPSED(millis(), progress_bar_ms + PROGRESS_BAR_MSG_TIME) || !lcd_status_message[0]))
      return lcd_draw_progress_bar(progress_bar_percent);
```

also in 'ultralcd_impl_hd44780.h' line 876 such variable is used but not always defined

**Comment by GMagician** [comment]
@thinkyhead sorry, I tryed to use markdown but it seems not to work as expected. Example uses 3 ' symbols ad start and 3 at end. If I do the same I got....normal text

**Comment by GMagician** [comment]
@thinkyhead re-reading your post I now understood what you said...but trying to compile I really get an error
