### ISSUE TITLE
ENDSTOPS_ALWAYS_ON_DEFAULT not initializing endstops state at power-up

### ISSUE THREAD

**Issue by ScottWell1** [MarlinFirmware/Marlin#8662]
- Description: ---
With ENDSTOPS_ALWAYS_ON_DEFAULT defined, endstops should be (but are NOT) enabled globally at power-up.  They are enabled only by M502, or M120. 

- Expected behaviour: ---
Endstops should be enabled globally at power-up when ENDSTOPS_ALWAYS_ON_DEFAULT is defined.

- Actual behaviour: ---
Endstops are not enabled globally at power up, despite having ENDSTOPS_ALWAYS_ON_DEFAULT defined. 

M502 - Settings reset - has code snippet to check ENDSTOPS_ALWAYS_ON_DEFAULT, and set endstop state.
M500/M501 Settings Save/Load - Does not mention endstops because they are not part of EEPROM save/load. 
Marlin_main.cpp Setup() - Does not set endstop state (it should have same code from M502 to set endstop global state (on/off) at power-up based on ENDSTOPS_ALWAYS_ON_DEFAULT (defined/undefined).

I propose that the same code used in M502 settings::reset(), which checks ENDSTOPS_ALWAYS_ON_DEFAULT and sets endstops on/off globally, be added to main loop Setup() routine so that endstop state is initialized correctly during power-up.  
 ```
endstops.enable_globally(
    #if ENABLED(ENDSTOPS_ALWAYS_ON_DEFAULT)
      true
    #else
      false
    #endif
     )
```

**Comment by thinkyhead** [comment]
Patched so the state is set correctly on boot.
