### ISSUE TITLE
Anycubic Delta auto-level error "ZPROBE"

### ISSUE THREAD

**Issue by FlailAway** [MarlinFirmware/Marlin#8675]
Not sure if it is a bug, or something I have, or have-not done.

Anycubic-Linear-Plus, Delta used Anycubic's version of Marlin 1.1.0, dated 07-12-2017 but the auto-level never worked. 

I downloaded Marlin 1.1.6 (stable) and then using the Generic Delta example went through and changed the 1.1.6 configuration.h and configuration_adv.h to match the Anycubic 1.1.0 versions.

All look good, correct Z-height 297.4 and paper-clearance at Z0. Tried the Bed Level and it probed a bunch of spots that looked consistent and regular positions. After what looked like a uniform covering of probing, it stopped at the rear and raised to about Z-20. It then moved to what would be something like X-110/Y0 and moved toward X0. Allmost at the center of the bed, it declared "Err: ZPROBE" and stopped.

I cannot easily get the two configuration files to post here as they are on Ubuntu-PC for the printer at a friend's house. 

What or where should I start looking to fix this error?

Thanks

**Comment by ghost** [comment]
I have also had this error but it is most likely a bad config, I should be able to iron it out tomorrow and then I will PR a example config for the anycubic kossel with trigorilla board for use into bug fix.

**Comment by laveur** [comment]
Is there any update on this?

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see if we fixed this issue. If the problem has been solved then we can close it. If you still see the bad behavior we should investigate further.

**Comment by thinkyhead** [comment]
If we can get some tuned AnyCubic configs, they would be most welcome.

**Comment by ghost** [comment]
My Linear Plus in the office is pretty close, but I have had it better before; will re-tune and send over. 

I believe the stock config from anycubic has several elements wrong... especially the pid values for temps.

**Comment by maz3max** [comment]
this would be awesome!

**Comment by boelle** [comment]
@FlailAway Please test with the latest `bugfix-2.0.x`

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by Phr3d13** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
