### ISSUE TITLE
Problem with LCD1602

### ISSUE THREAD

**Issue by Alil2096** [MarlinFirmware/Marlin#8689]
Hi everyone, i've a big problem during the configuration of Marlin. 

I'm using a MKS Base_l v2.1 board, and I want add a minimal display (16x2), but, I can't change the settings for width and height. because there are a lot of error during the compilation. 

Any idea? 

Thanks :)

**Comment by GMagician** [comment]
Maybe same issue than #8633?

**Comment by Bob-the-Kuhn** [comment]
The following will be a big help in getting you going:
1. your configuration.h and configuration_adv.h files
2. your pins_MKS_BASE.h file
3. the flavor of Marlin that you're using (1.16, bugfix-1.1.x, bugfix 2.0.x, ...)
4. a link to the display that you're using
