### ISSUE TITLE
Homing broken by recent commit

### ISSUE THREAD

**Issue by cg9999** [MarlinFirmware/Marlin#8700]
On my delta kossel the recent commit
"Use block cleaning instead of split flag" (commit 840289e7ccaa79846acfdceee63ffc1baa77168c)
broke the homing function.

Easiest to see if I manually move each carriage down, but position X carriage the lowest.
Now when I do G28, Y and Z seem to home but X stops as soon as other carriage hits the end stop.
X stays halfway, never hitting the endstop and machine thinks it's homed. Starting a print now will cause the head to hit the bed :(

**Comment by AnHardt** [comment]
Do you get a message "Homing failed"?
Do B and C tower home normally - with backing up from endstops?

**Comment by cg9999** [comment]
No fail message, and B and C do not back up like normally.
I can post a video if it helps

**Comment by thinkyhead** [comment]
Thanks for the report! I believe it's patched now. We forgot we had to deal with interrupted split moves. Now we have a better way to deal with interrupted moves in the future, so, cheers.

Please give the latest bugfix a try and let us know if we got it.

**Comment by cg9999** [comment]
Thank you, the issue is fixed now!
