### ISSUE TITLE
[bugfix-1.1.x] Homing broken by latest commits

### ISSUE THREAD

**Issue by bjarchi** [MarlinFirmware/Marlin#8704]
Probably similar to #8700 but I'm on a cartesian machine and I don't know how much difference there is in terms of homing behavior.

I'm trying to work on another bug right now, and I'm still not very well oriented to the structure of the whole firmware, so I'm not sure I can track this one down (though I will look through recent commits). 

### Bug Report
- Description: After pulling latest commits on bugfix-1.1.x, homing (w/ Z_SAFE_HOMING, though I don't think it matters) no longer works properly
- Expected behaviour: on `G28` machine homes X and Y, then moves to center of bed and homes Z using bed probe
- Actual behaviour: Depends on starting location. If starting from the endstops, the machine moves immediately to bed center (no homing re-bump) and seems to kind of do the right thing. If not starting from endstops, machine starts homing normally but doesn't re-bump after hitting endstops, doesn't always hit both endstops, and tries to home Z wherever it ends up. Repeated `G28`s seem to produce additive error in home reference frame. 
- Steps to reproduce: 
  - Flash latest commits
  - Initialize EEPROM (M502; M500; M501)
  - `G28` and watch behavior

[config-20171207.zip](https://github.com/MarlinFirmware/Marlin/files/1540520/config-20171207.zip)

**Comment by Tannoo** [comment]
I can't find `bugfix-1.1.6` to check this out.

**Comment by bjarchi** [comment]
My bad, bugfix-1.1.x

The main bugfix branch for 1.1. development.

**Comment by thinkyhead** [comment]
We can have one topic for both 1.1 and 2.0. Make it #8700.
