### ISSUE TITLE
[2.0.X]- LPC1768 -  TCNT0 not defined when using LIN_ADVANCE or BABYSTEPPING

### ISSUE THREAD

**Issue by Nutz95** [MarlinFirmware/Marlin#8710]
### Compile Error
I've got a build error on LPC1768 platform when i enable either `LIN_ADVANCE` or `BABYSTEPPING` inside configuration_adv.h.
The Build error message is **"Marlin\src\module\stepper.cpp:1304:54: error: 'TCNT0' was not declared in this scope"**
When i check inside the code, marlin is using specific register TCNT0, and i believe this register doesn't exist on LPC1768 platform.

**Comment by Bob-the-Kuhn** [comment]
Does the latest bugfix work?

**Comment by thinkyhead** [comment]
#8725 should solve the issue.
