### ISSUE TITLE
extruder is feeding much more in the last version

### ISSUE THREAD

**Issue by hadisalame** [MarlinFirmware/Marlin#8711]
### Bug Report

I installed the latest marlin firmware and everything is working perfectly except one issue. the extruder is feeding much more filament despite the fact that the steps per mm are the same in the previous version (which works perfectly when I go back to it ) and in the current version too.
I tried to reduce half of the steps per mm but it is still printing in the same rate !!!
So I think that it is not working according to the applied steps per mm.
BTW the XYZ steps per mm are working perfectly.
Does anyone know what I have to do ?

**Comment by boelle** [comment]
@hadisalame do you also have the problem with latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
