### ISSUE TITLE
[2.0.X]- LPC1768 issue with homing Delta

### ISSUE THREAD

**Issue by robertbba** [MarlinFirmware/Marlin#8728]
Hi, 

I updated the last bugfix 2.0.x today to my SBASE Delta printer.
After G28 only one tower moves and hits the endstop.  It hits the endstop but doesn't come back and the whole printer freeze in this position. In the console after the tower reaches the endstop I have three messages processing 
then raport from G28 

Can somebudy help me with this  

![astro](https://user-images.githubusercontent.com/34353663/33794367-39d718ae-dccb-11e7-9c6b-a02f724a6c3b.jpg)

**Comment by psavva** [comment]
I suggest you provide your config files to review
