### ISSUE TITLE
4D LCD support

### ISSUE THREAD

**Issue by yellobello** [MarlinFirmware/Marlin#874]
Hi,
as far as i see 4D LCD support has been dropped from the current marlin version.
I would really love to re-implement it.
I don´t exactly understand yet what has to be edited, but i am figuring out. As far as I see, MYSERIAL1 has to be implemented as well as LCD_4D and pins.h has to be modified.. anything else???

**Comment by boelle** [comment]
as there have not been any more new activity i will kill this one... only one asked for support and in the end i guess this would also just add even more complexity
