### ISSUE TITLE
[2.0.X] MKS Sbase compile error with ENDSTOP_INTERRUPTS_FEATURE

### ISSUE THREAD

**Issue by teddybee** [MarlinFirmware/Marlin#8751]
When I compile with `ENDSTOP_INTERRUPTS_FEATURE` I get an error:
```
In file included from Marlin\src\Marlin.cpp:99:0:
Marlin\src\HAL/HAL_endstop_interrupts.h:51:4: error: #error Unsupported Platform!

#error Unsupported Platform!
^~~~~
Compiling .pioenvs\LPC1768\src\src\feature\bedlevel\abl\abl.o
Marlin\src\Marlin.cpp: In function 'void setup()':
Marlin\src\Marlin.cpp:825:30: error: 'setup_endstop_interrupts' was not declared in this scope
setup_endstop_interrupts();
^
*** [.pioenvs\LPC1768\src\src\Marlin.o] Error 1
 [ERROR] Took 11.06 seconds
```
P.S.: I copied the wrong logs and I see now the platform is not supported, maybe it is a feature request.

**Comment by teddybee** [comment]
Maybe this helps in the implementation:
[http://users.ece.utexas.edu/~valvano/Volume1/E-Book/C12_Interrupts.htm](http://users.ece.utexas.edu/~valvano/Volume1/E-Book/C12_Interrupts.htm)

**Comment by fiveangle** [comment]
The error is the answer:

> #error Unsupported Platform!

It means `ENDSTOPS_INTERRUPT_FEATURE `is not supported on MKS Sbase.

**Comment by Bob-the-Kuhn** [comment]
~The ENDSTOPS_INTERRUPT_FEATURE is not needed in Marlin 2.0.x.  Since the stepper ISR runs every millisecond then BLTouch detection is already guaranteed.~

~Maybe the message should be changed to something like "Warning - ENDSTOPS_INTERRUPT_FEATURE ignored (not needed)"~

NEVER MIND ...  I realized that's not always true.

**Comment by AnHardt** [comment]
I did not create the `ENDSTOPS_INTERRUPT_FEATURE` for Marlin to support the BL-touch.
I made it for saving the time for checking the endstops in every step during the stepper ISR.
What is now done for the BL-touch, now checking even in between of the steps, feels perverse to me.
The positive side effect of having no minimal speed (limited by timer overflow) anymore is not used up to now.

**Comment by thinkyhead** [comment]
> What is now done for the BL-touch, now checking even in between of the steps, feels perverse to me.

Some felt that brute force was needed to make that fickle little hall effect probe meet the performance claimed in its promotional materials — within Marlin and not just on a test rig. I haven't checked out the additions lately. Maybe they are overkill.

**Comment by thinkyhead** [comment]
> What is now done for the BL-touch, now checking even in between of the steps, feels perverse to me.

Ah, I see…
```cpp
  #define ENDSTOP_NOMINAL_OCR_VAL 3000
  // Check endstops every 1.5ms to guarantee two stepper ISRs within 5ms for BLTouch
```
According to this the extra logic for the ISR to run earlier (to check endstops again) may not be needed without `BLTOUCH`. If that's the only reason the extra logic exists, and not for the benefit of endstops/probes generally, then it could be simplified for other setups.

**Comment by teddybee** [comment]
Thank you for the clarification. This was enabled on my old Anet controller, I thought it would be useful if the controller doesn't waste some cpu time with the continuous loop.
