### ISSUE TITLE
UBL and #error "LCD_BED_LEVELING requires MESH_BED_LEVELING or PROBE_MANUALLY with auto bed leveling enabled."

### ISSUE THREAD

**Issue by v-mat** [MarlinFirmware/Marlin#8753]
When I compile with AUTO_BED_LEVELING_UBL and PROBE_MANUALLY I get the error:
```
LCD_BED_LEVELING requires MESH_BED_LEVELING or PROBE_MANUALLY with auto bed leveling enabled.
```
I have an LCD and can compile with AUTO_BED_LEVELING_BILINEAR and PROBE_MANUALLY. Is UBL and PROBE_MANUALLY currently not supported?

**Comment by PolloPequeno** [comment]
`LCD_BED_LEVELING ` is for the mesh bed leveling. Comment that line out and it should compile fine.

**Comment by v-mat** [comment]
Yes, it worked. Thanks!

**Comment by PolloPequeno** [comment]
Anytime, happy to help.
