### ISSUE TITLE
one time loop between reprap logo and info screen... Pls help

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#8764]
Hi sir, When I am switch ON machine. Its flow is showing REPRAP logo and then INFO SCREEN. But when click encoder its coming like its showing again REPRAP logo and then its going to PREPARE and all...

I wanted like when I click encoder in DEFAULT HOME SCREEN, its should go straightly go to PREPARE, CONTROL MENU... but now its coming different like when I click on DEFAULT HOME SCREEN , firstly its showing REPRAP logo for 1 second and then its going to PREPARE, CONTROL MENU..

What to do... pls help

**Comment by Shrikant888** [comment]
The flow should be Power ON->REPRAP Logo->HOME SCREEN->Click ENCODER->INFO SCREEN (PREPARE, CONTROL, SD CARD)

but I am getting as Power ON->REPRAP Logo->HOME SCREEN->Click ENCODER->REPRAP Logo for 1 second->INFO SCREEN (PREPARE, CONTROL, SD CARD).. Pls note it sir

**Comment by cjsoong** [comment]
You can try M502 & M500 instructions back to the default value

**Comment by AnHardt** [comment]
If you really see a 'REPRAP Logo' and not a 'Marlin logo' you should try a newer Marlin. Yours is ancient.

**Comment by Tannoo** [comment]
You could have a bad display.

**Comment by Shrikant888** [comment]
Sir, REPRAP MARLIN logo is coming. its coming two times. As of now flow is like this

Power ON LCD boot
REPRAP MARLIN Logo
HOME SCREEN (temperature, Fan, X, Y, Z )
Clicking Rotary Encoder
REPRAP MARLIN Logo displays for 1 second
INFO SCREEN (Prepare, Control etc)

I wanted like this (skipping 5th step from above)

Power ON LCD boot
REPRAP MARLIN Logo
HOME SCREEN (temperature, Fan, X, Y, Z )
Clicking Rotary Encoder
INFO SCREEN (Prepare, Control etc)

Where to change in MARLIN FIRMWARE. Please tell

**Comment by psavva** [comment]
Please provide your configuration files.

**Comment by thinkyhead** [comment]
Are you using `bugfix-1.1.x`? We heard about this problem and fixed it a while ago.
