### ISSUE TITLE
GT2650_REV_A_PLUS - BLTouch wrong pins

### ISSUE THREAD

**Issue by OctavioMaia** [MarlinFirmware/Marlin#8774]
Bug Report
- Description: I currently own a GT2560 REV A+ and I couldn't get my BLTouch to work at all. It would never respond to M280 commands. The REV A+ has a proper servo pin header for the BLTouch alone, which seems to be maped to pin 32 on the config.
I managed to fix this by editing the SERVO0_PIN from 32 to 11 when the BLTouch is enabled.

- Expected behaviour: BLTouch should trigger
- Actual behaviour: It does not trigger/does not respond to M280
- Way to fix:

> #include "pins_GT2560_REV_A.h"
> 
> #undef BOARD_NAME
> #define BOARD_NAME  "GT2560 Rev.A+"
> 
> #if ENABLED(BLTOUCH)
>#define SERVO0_PIN  11
> #else
> #define SERVO0_PIN  11
> #endif

**Comment by wittsan** [comment]
Hello,
I found the same problem. I'm watching a discussion on this topic https://github.com/MarlinFirmware/Marlin/issues/7981.

I allow myself to correct your code below because if the BlTouch is not activated, pin 32 must be activated to return to the normal configuration (in case you unplug the bltouch).

```
#include "pins_GT2560_REV_A.h"

#undef BOARD_NAME
#define BOARD_NAME "GT2560 Rev.A +"

#if ENABLED (BLTOUCH)
   #define SERVO0_PIN 11 // instead of 32
#else
   #define SERVO0_PIN 32 // instead of 11
#endif
```
W.

**Comment by OctavioMaia** [comment]
Thanks for your update.
I'll do that on my config

**Comment by wittsan** [comment]
With pleasure ;-)
It is good if we are several to confirm the error on the current version for a future patch ...
Have a good day.

**Comment by thinkyhead** [comment]
It's almost as easy to make a patch as it is to make an issue, if anyone wants to try and get one in ahead of 1.1.7 release…

**Comment by wittsan** [comment]
Hello Thinkyhead,
_(Sorry I'm not sure I understand the meaning)_ You say we should submit the patch directly, is that it?  how?
Thanks

**Comment by landodragon141** [comment]
I'll do it later tonight, I have that same board.

**Comment by thinkyhead** [comment]
> how?

That sounds like a good question for Github.
https://help.github.com/articles/creating-a-pull-request/

**Comment by wittsan** [comment]
Thank you.

**Comment by wittsan** [comment]
I just made the submission. thx!

**Comment by wittsan** [comment]
I do not know if I did well .. I have to make a "pull request" on the bugfix 1.1.x (and also bugfix 2.0.x) or is it good?
_I think it's a 1.1.7 submission I made._

**Comment by boelle** [comment]
@thinkyhead we have an PR so could we not close this one?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
