### ISSUE TITLE
Bed leveling ENABLE_LEVELING_FADE_HEIGHT problem

### ISSUE THREAD

**Issue by lonelymyp** [MarlinFirmware/Marlin#8782]
Marlin 1.1.3

I enabled option #define AUTO_BED_LEVELING_BILINEAR
enabled option #define ENABLE_LEVELING_FADE_HEIGHT
Set the compensation height M420 Z4
got 2 problems: 
1. the height of the model is 2 mm higher than it should be
2. The first 5.5 mm models are printed with badges. the height of the layer does not correspond to extrusion.
![img_0457](https://user-images.githubusercontent.com/2085051/34004634-7d4e103c-e109-11e7-9f13-5dff4dc0cc15.jpg)

if I turned off the option #define ENABLE_LEVELING_FADE_HEIGHT, everything is fine.

**Comment by PolloPequeno** [comment]
Pull down the bug fix branch, that will most likely fix this issue. Marlin is currently at 1.1.6 and 1.1.7 is close to release.

**Comment by lonelymyp** [comment]
I tried version 1.1.6
The problem became the opposite, is slight overextrusion.

**Comment by PolloPequeno** [comment]
If the over extrusion is happening only on the first couple layers, try adjusting the Z endstop or the probe offset if you're using a probe. Otherwise you can adjust the steps per mm or the flowrate. 
[marlinfw.org](http://marlinfw.org/) contains allot of useful information on gcode and setting marlin up.

**Comment by thinkyhead** [comment]
Please test `bugfix-1.1.x`. Version 1.1.6 is quite old now.

Meanwhile, `M420 Z4` is bound to give you some over-extrusion if you have an uneven bed. Try `M420 Z10` or higher.

**Comment by lonelymyp** [comment]
bugfix corrected the problem. but now another problem, before the retract the printer hangs for a second.
https://youtu.be/WiMiXhZ2tW0
but I'm not sure that this is related, hangs at any height.

**Comment by lonelymyp** [comment]
checked again, turned off the calibration option, hanging before the retract is in the same place
 :(

the bug appeared only in the bugfix firmware.

**Comment by lonelymyp** [comment]
I just tried 1.1.7, the problem disappeared.
