### ISSUE TITLE
[FR] More than one MAX31855

### ISSUE THREAD

**Issue by pbrgle1** [MarlinFirmware/Marlin#8788]
Hi.

Why is the MAX31855 only possible for sensor 0? The Ultratronics board has 2 (4 in the PRO version) possibilities for MAX31855.

In marlin_kimbra it is possible to set two -3 sensors but the firmware has some other crucial problems and it's not usable for me...

**Comment by thinkyhead** [comment]
> Why is the MAX31855 only possible for sensor 0?

Because it hasn't been implemented for more than 1 sensor. However #8686 aims to remedy this.

**Comment by boelle** [comment]
@thinkyhead since #8686 is merged could we not close this one? #8686 does provide more than 1

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
