### ISSUE TITLE
[1.1.x] UBL and Firmware Retract don't play nicely with Hop 

### ISSUE THREAD

**Issue by tcm0116** [MarlinFirmware/Marlin#8802]
On both 1.1.6 and 1.1.7, if a hop value is set in Firmware Retract while UBL is enabled, the hop will occur, but will not be completely restored. This results in the nozzle continuously raising after each retract.

I noticed that this only seems to occur during printing as issuing G10/G11 commands while the printer was stationary resulted in the nozzle moving back down as expected.

**Comment by thinkyhead** [comment]
Does this continue to manifest if `M420 Z0` turns off the fade height?
