### ISSUE TITLE
suggestion needed for compile

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#8826]
### Compile Error with ver 2.0.x-957bbab and Arduino 1.8.6
When I compile with my config files I get this error.
```
fork/exec C:\Users\Bill\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-gcc.exe: The filename or extension is too long.
Error compiling for board Arduino/Genuino Mega or Mega 2560.
```
It does not occur compiling the distribution.
how do I resolve it? I can't shorten anything past LOCAL

the Arduino install file says 1.8.5 and the exe file shows 1.8.6 - ?

**Comment by Bob-the-Kuhn** [comment]
Try the Arduino 1.9 beta.  

The "too long" solution is slated for the 1.9 release.

**Comment by ruggb** [comment]
didn't work

**Comment by hicsvntdracones** [comment]
Remove the IDE's preferences.txt file line 54 # to build.path = F: \ tmp

**Comment by ruggb** [comment]
I reinstalled Arduino 1.8.5 and retried. Got the same error with a different path. BUT noticed that the path is not Widows compliant. The same as the previous one -- **..tools\avr/bin/avr-gcc.exe** -- which I did not notice b4. So it isn't TOO LONG, it is looking for a file **AVR/BIN/AVR-GCC.EXE** in tools folder.
it should be **tools\avr\bin\avr-gcc.exe**
Is that from the IDE or Marlin?

1.1.x compiles without the problem.

**Comment by thinkyhead** [comment]
Seems to an Arduino for Windows issue. Please report to the Arduino project.
