### ISSUE TITLE
Slow 2nd layer printing (with TMC2130's)

### ISSUE THREAD

**Issue by SpeedGP** [MarlinFirmware/Marlin#8837]
### Bug Report
- Description: Printer seems overloaded after 2nd layer of print with TMC2130's
- Expected behaviour: 2nd layer print as fast as the 1st
- Actual behaviour: Printer seems to print at about 1mm/s
- Steps to reproduce:
  - Do Install TMC2130's
  - Do Print anything

I Upgraded from version RC8 straight to 1.1.6, installed TMC2130's, everything seems great, including sensorless homing, so I know they, and the diagnostic pins are working. On the second layer of any print (I've tested large and small prints, drivers around 110F) it, Ramps 1.4, seems to be overloaded and drops the speed to about 1mm/s, even during a pause and jog z (without a TMC). Octoprint's terminal window displays "Recv: echo:busy: processing" after every command.

My configuration files are attached, also a youtube video of layer 2
https://youtu.be/8Y3bHX9r-AA

[configruation.zip](https://github.com/MarlinFirmware/Marlin/files/1570109/configruation.zip)

**Comment by SpeedGP** [comment]
I apologize, I may have found the cause. It appears whenever the parts fan comes on, M106 (currently on pin D11 or D6), the printer starts printing that slow. Is this interfering with SPI or something? I saw the Software/Hardware PWM settings, but I do not know much about thost. Do you think those will help?

Thank you!!!!

James

Followup;

M106 S255 works great, fan spins at 100% and motors work. M106 S254 (or less), fan does not spin, and motors do not work. Thoughts?

**Comment by teemuatlut** [comment]
The drivers are not run by the SPI interface, just configured through it and so shouldn't have any effect on the printing speeds. There is some communication a couple times a second but shouldn't cause too drastic slowdowns.
Also there was an update to the TMC support in v1.1.7 but it wasn't listed in the change log.

**Comment by SpeedGP** [comment]
I was just told (in a different forum) that there was a fan bug that was fixed in v1.1.7. I was planning to upgrade tonight.

Stupid question, Is there an easy way to upgrade yet?

**Comment by SpeedGP** [comment]
Upgraded to v1.1.7, same issue. Thoughts?

**Comment by SpeedGP** [comment]
I've been playing around some more... It looks like The fan won't actually blow unless at 100%, M106 S254 doesn't work, but M106 S255 does.

After changing the FAST PWM settings or whatever, the axises move a little faster, but there is still obviously an issue.
