### ISSUE TITLE
[FR] Auto level, Servo angle save to eeprom?

### ISSUE THREAD

**Issue by jackshi618** [MarlinFirmware/Marlin#8838]
open auto level,Servo  angle save to eeprom?

**Comment by psavva** [comment]
Can you please be more specific in your question?

**Comment by Roxy-3D** [comment]
I think he wants the servo angles to be adjustable and saved to the EEPROM without having to edit and rebuild the firmware.     This sounds like a good thing to do.   But we probably would want to hard allocate 6 or 8 bytes and handle 3 or 4 servos (even if the system only has one).    And of course, there would need to be a way to change the per servo values.   (Yet another MCode...)

**Comment by jackshi618** [comment]
Exactly what I want to say

**Comment by thinkyhead** [comment]
Anything is possible. You just need to recruit a willing developer to code it.

**Comment by jackshi618** [comment]
I want to do it, but I don't know where to start.

**Comment by Roxy-3D** [comment]
> I want to do it, but I don't know where to start.

Fork the Marlin repository, modify a Bugfix branch to have your changes working.  And then issue a Pull Request.

Probably the first thing to do is modify Configuration_Store.cpp to have the space allocated for the values.   Then, modify the initialization code to pick up and use those values.   And then define and implement some MCode function to set the values.
