### ISSUE TITLE
Question: Trigger three endstops using one input?

### ISSUE THREAD

**Issue by BETLOG** [MarlinFirmware/Marlin#8848]
Question: I have a precisionpiezo IC board that can connect several piezo 'sensors', but it only outputs to a single vcc/gnd/sig channel.
Is it possible to tell Marlin to individually trigger X, Y, and Z endstops, and Z probe when a single RAMPS endstop channel is triggered?

My plan was to add piezo disks in all the usual endstop places, and use a single endstop input to sequentially recognise them all, but now that I try to implement the firmware I'm pretty sure I cannot.

**Comment by revilor** [comment]
If you want to go the "piezo way" for all endstops, I would suggest to use the precision-piezo for Z, and get yourself two of these or something similar for X and Y: https://www.ebay.com/itm/5V-Piezoelectric-Film-Vibration-Sensor-Switch-Module-TTL-Level-Output-ForArduino-/222478721708. Or build the piezo2TTL adapter yourself: https://michaelfranzl.com/2016/05/09/diy-piezo-electric-touch-probe-high-sensitivity/

This way you could use Marlin out of the box.

**Comment by BETLOG** [comment]
Stupid and probably out-of-scope question: How does a 4pin TTL output interface a 3pin ramps endstop input?

Also; what *does* AD0 stand for? (printed those first things you linked)

**Comment by BETLOG** [comment]
I actually already have two of those.
....and a folder full of various circuit designs for the relevant pcb

I'm starting to see a pattern here; i research stuff, decide how to implement it, usually with plan A and plan B, order the parts.... wait a month or two.... and then forget why I bought the things or exactly how I planned to use them.

Thanks. :)

**Comment by boelle** [comment]
@BETLOG Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D
