### ISSUE TITLE
Motherboard on Geetech I3X PRO is BOARD_GT2560_REV_A_PLUS

### ISSUE THREAD

**Issue by FabLab-du-Don** [MarlinFirmware/Marlin#8856]
https://github.com/MarlinFirmware/Marlin/blob/459094e8d226c1f3535529ef00e1bd3d1df488ef/Marlin/example_configurations/Geeetech/I3_Pro_X-GT2560/Configuration.h#L122

`#define MOTHERBOARD BOARD_GT2560_REV_A_PLUS  // Geeetech GT2560 Rev. A+ (with auto level probe)`

**Comment by thinkyhead** [comment]
Does this comport with your setup @Roxy-3D ?

**Comment by thinkyhead** [comment]
Does this work for you @richarddeweerd ?
