### ISSUE TITLE
Thermistor table #8

### ISSUE THREAD

**Issue by ABH10** [MarlinFirmware/Marlin#8862]
In Configuration.h and in thermistortables.h it is listed that thermistor table # 8 can be used for a
thermistor like Vishay NTCS0603E3104FXT with a 4.7k pullup resistor.
NTCS0603E3104FXT is a 100 kOhm thermistor with beta_25/85 = 4100K according to this components datasheet.

This seems to be wrong: Table 8 cannot not linearize this combination of thermistor and pullup.
Table 8 seems to be for a 100 kOhm thermistor with beta_25/85 = 3950K using 10 kOhm pullup resistor.

**Comment by thinkyhead** [comment]
@DanieleSdei — Would you care to comment on this? This particular table seems to have come from the RepRapPro Huxley fork of Marlin.

Thermistor 12 seems to be an alternative table for E3104FXT calibrated for Makibox. Possibly it's closer to the correct values.

**Comment by boelle** [comment]
@ABH10 @DanieleSdei is this still an issue?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by Phr3d13** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
