### ISSUE TITLE
[bugfix-1.1.x] Official Linear Advance test pattern file is printed strange

### ISSUE THREAD

**Issue by ikarisan** [MarlinFirmware/Marlin#8874]
### Bug Report
- Description: I generated some GCODE files via this website: [http://marlinfw.org/tools/lin_advance/k-factor.html](url) to calibrate linear advance. But neither with Octoprint nor with other software like "S3D" or pronterface it is possible to print the code with Marlin 1.1.7.

- Expected behaviour: Calibration pattern printed as expected. 

- Actual behaviour: The printer print the prime line from X50 Y67.5 to X50 Y167.5 and then starts acting strange.  It moves the nozzle to the first start point at X70 Y67.5 and prints from X70 to X150. But instead of just moving the X axis the printer also moves to Y axis to Y=0. Once reached Y=0 every following line is printed at Y=0! See the following link to [my YouTube](https://youtu.be/zoTm1md4AD8) video that will visualize the problem.

- Steps to reproduce: Flash Marlin 1.1.x(bugfix) [1.1.7] (on an Anet A8 board) and print the attached GCODE file. 

[Marlin_Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1584304/Marlin_Configuration.zip)
[GCODE kfactor_strange.zip](https://github.com/MarlinFirmware/Marlin/files/1584302/kfactor_strange.zip)

Seems to me like a G90 problem. O.o

**Comment by Sineos** [comment]
Actually the pattern itself is printed as G91 using relative coordinates. You can try the attached version (same settings as yours) using purely absolute coordinates.
[kfactor.gcode.txt](https://github.com/MarlinFirmware/Marlin/files/1584411/kfactor.gcode.txt)

**Comment by ikarisan** [comment]
@Sineos Thanks! Printing with absolute coordinates is working as expected.

**Comment by Sineos** [comment]
Well the gcode file looks fine and it is working for 1.1.6 with relative coordinates. Looks like G91 then. Maybe @thinkyhead or @Bob-the-Kuhn can have a look.

**Comment by ikarisan** [comment]
Yes, it worked for me on 1.1.6 either.

**Comment by thinkyhead** [comment]
The 1.1.7 planner is a bit different from 1.1.6, but the simple behavior of Relative Mode is precisely the same. When coordinates are fetched from the G-code, the current position is added to them before use. That's the only difference, and it should yield good results with the given G-code.

I've tweaked the script at http://marlinfw.org/tools/lin_advance/k-factor.html to produce slightly slimmer output, but it still uses relative mode.

If there's a general issue with `G91`, it should be easy to spot by doing `G1` moves from the host.

**Comment by chambm** [comment]
I've used that generator code with 1.1.7 without a problem. Well, I'm not too happy with the linear advance behavior, but the calibration pattern itself prints as expected.

**Comment by ikarisan** [comment]
Did you use the tweaked (by thinkyhead two days ago) code or the old one?

**Comment by chambm** [comment]
No, I was using the original 1.1.7 (2f2564350d5)

**Comment by Sineos** [comment]
The tweak by thinkyhead should not change anything. It just made the gcode a bit leaner but did not change any logic.

**Comment by ikarisan** [comment]
@Sineos : The tweaked version does not contain the "Y0" coordinates"!

I tried a "dry run" without extruding. This GCode is not working (as expected):
```gcode
G28; Using "safe homing", sensor is at X:110 and Y:110
G21; set units to mm
G90; use absolute coordinates
G1 X110 Y110; nozzle to center of the bed
G91; relative coordinates
G1 X20 Y0; moves 20mm to the right and Y MOVES BACK a few mm
G1 X20 Y0; moves 20mm to the right and Y MOVES BACK a few mm
G1 X-20 Y0; moves 20mm to the left and Y MOVES BACK a few mm
G1 X-20 Y10; moves 20mm to the left and **Y IS NOT MOVING**!
G1 X-20 Y0; moves 20mm to the left and Y MOVES BACK a few mm
```
While this one works (partly):
```gcode
G28; Using "safe homing", sensor is at X:110 and Y:110
G21; set units to mm
G90; use absolute coordinates
G1 X110 Y110; nozzle to center of the bed
G91; relative coordinates
G1 X20; moves 20mm to the right and Y IS NOT MOVING
G1 X20; moves 20mm to the right and Y IS NOT MOVING
G1 X-20; moves 20mm to the left and Y IS NOT MOVING
G1 X-20 Y10; moves 20mm to the left and **Y IS NOT MOVING**
G1 X-20; moves 20mm to the left and Y IS NOT MOVING
```
Maybe it has something to do with the "home offset"?!

Home offset:
```gcode
  M206 X1.00 Y10.00 Z0.00
```
The common denominator for both is the Y10

**Comment by Sineos** [comment]
> The tweaked version does not contain the "Y0" coordinates"!

For me that should not make any difference. Y0 is correct from the coordinates (talking relative) and as such should not produce any strange movement. It is true, that it is surplus but still it does in no way change the logic.

**Comment by thinkyhead** [comment]
Presuming this is solved.
