### ISSUE TITLE
[2.0.x] Can't move anymore stepper

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#8877]
Description:
  once installed latest 2.x bugfix it seems step motors can't be moved.
 once you move am axes it seems that everything is slowed down (trying to move a servo if moves after several seconds) but stepper never moves.
Expected behaviour:
 once commanded motors should move
Actual behaviour:
  step motors don't move (nor X, Y or Z)
Steps to reproduce:
  go to lcd menu and move a stepper (or even by repetier host)

N.B. bug is caused by #8852 or #8863 because I reverted to version before these merge and now everything work as expected.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1584443/Configuration.zip)

**Comment by DaveAhrendt** [comment]
Was just coming here to report this issue. Same problem here with a Folger I3 2020.  Z stepper just vibrates.
Commit 5BC2..... works OK
Commit 97D5..... fails.
I replaced the planner.cpp from 97D5 with the one in 5Bc2 and the steppers work OK

**Comment by tcm0116** [comment]
Can you try the fix from #8878 to ensure that is fixes the issue?

**Comment by DaveAhrendt** [comment]
Went back to 97d5... and added the patch from #8878.  Steppers are moving fine now.

**Comment by tcm0116** [comment]
@DaveAhrendt can you verify that #8878 added to the current bugfix-2.0.x works for you?

**Comment by DaveAhrendt** [comment]
Yes, just downloaded the current bugfix and applied the two line patch to planner.cpp.
Stepper motors seem OK now. I can home now and move XYZ.  Didn't try to print anything.
