### ISSUE TITLE
BLTouch Smart 1.0 Blue Light, No retract or extend, Hypercube

### ISSUE THREAD

**Issue by mzj9k0** [MarlinFirmware/Marlin#8885]
How do i activate a BLtouch smart 1.0, I have a 5V Ramps 1.4, working fine with a prox sensor, I changed from fixed_mounted_probe to BLTOUCH. I also left it on the servo 0 connector.
I try to run the M280 P0 S90, M280 P0 S120 and M280 P0 S160 commands and nothing happens, the bltouch is connected, the blue light is on.
There is no test on power up, the Z_Min reads correctly, and I tried linking Vcc and 5V even, what am i missing in the code, i did not copy the BLTouch code from antclabs into the Configuration.h and Configuration_adv because i thought that in 1.1 that there was no need to.
Am i wrong? struggling to know if i have a bad BLTouch or if I am just not activating it somehow.
Any ideas gratefully received.

**Comment by thinkyhead** [comment]
Also try http://forums.reprap.org/list.php?415 to get help from other users of BLTouch.
