### ISSUE TITLE
[FR] Update Ultimaker Pins for TMC2130 Compatibility

### ISSUE THREAD

**Issue by AcrimoniousMirth** [MarlinFirmware/Marlin#8902]
Once again a great thank you to the wonderful devs who keep this awesome firmware going!
And a merry Christmas to you all.

I’ve got my hands on some TM2130 silent stepsticks and while I could put them all in my RAMPS based machine I’d like to put two in my GT2560.
Now I’m not experienced in programming enough to sort this myself. 
The GT2560 motherboard has very few spare pins and the TMC2130 needs a few to run its SPI interface (the EMF endstop signals can run directly into the original endstop connectors). However I think it should be possible to reuse the max endstops and possibly spare motor driver pins (?) to communicate with the TMCs.
So would it be possible to add a few definitions to the end for TMC2130 control that override these pins?

Many thanks!

**Comment by teemuatlut** [comment]
To me it sounds like you're asking for software SPI interface for the drivers.
Does the board not have HW SPI pins broken out?

**Comment by thinkyhead** [comment]
`TMC_USE_SW_SPI`

**Comment by AcrimoniousMirth** [comment]
@teemuatlut no, the board is fairly minimal, hence my question. 

@thinkyhead okay, but will that allow me to set which pins are used? No point enabling that if it doesn’t correspond to the righ pins on the board.

**Comment by thinkyhead** [comment]
> …will that allow me…?

```cpp
/**
 * Use software SPI for TMC2130.
 * The default SW SPI pins are defined the respective pins files,
 * but you can override or define them here.
 */
//#define TMC_USE_SW_SPI
//#define TMC_SW_MOSI       -1
//#define TMC_SW_MISO       -1
//#define TMC_SW_SCK        -1
```

**Comment by roosevelt155** [comment]
I am wondering the same. I am using a Cohesion3D Remix board and am not sure what the default pins are set to. I am also not sure what these "MOSI", "MISO", and "SCK" pins correspond to what pins on the TMC2130. I am only finding the SCK pin on my TMC2130.

**Comment by thinkyhead** [comment]
@roosevelt155 — A Google Image search "TMC2130 MISO" shows us

![image](https://user-images.githubusercontent.com/698003/36380531-3ddb1fe4-1548-11e8-8a87-32131f82889d.png)

- SDO -> MISO
- SDI -> MOSI
- CS -> digital pins
- SCK -> SCK

A Google search for "SCK serial" leads to https://en.wikipedia.org/wiki/Serial_Peripheral_Interface_Bus where we find
- MISO = Master In Slave Out
- MOSI = Master Out Slave In
- SCK = Serial Clock
- CS = Chip Select
