### ISSUE TITLE
Does not build out-of-the-box for CR-10

### ISSUE THREAD

**Issue by RudolphRiedel** [MarlinFirmware/Marlin#8905]
### Compile Error
I only copied _Bootscreen.h, Configuration.h and Configuration_adv.h from example_configurations/Creality/CR-10 over and the result is this:
```
Compiling 'Marlin' for 'Sanguino w/ ATmega1284 or ATmega1284P (16 MHz)'
 
MarlinConfig.h:40: In file included from
Marlin.ino:30: from
 
SanityCheck.h: 418:6: error: #error "ADVANCED_PAUSE_FEATURE requires NOZZLE_PARK_FEATURE"
   #error "ADVANCED_PAUSE_FEATURE requires NOZZLE_PARK_FEATURE"
 
MarlinConfig.h:40: In file included from
blinkm.cpp:27: from
 
SanityCheck.h: 418:6: error: #error "ADVANCED_PAUSE_FEATURE requires NOZZLE_PARK_FEATURE"
Error compiling project sources
Build failed for project 'Marlin'
   #error "ADVANCED_PAUSE_FEATURE requires NOZZLE_PARK_FEATURE"
```

**Comment by v1ru3** [comment]
they moved the pause for M600 under configuration (not configuration_adv). You will need to uncomment NOZZLE_PARK_FEATURE and define x,y,z.

**Comment by RudolphRiedel** [comment]
Fixing that individually is not the issue. :-)

**Comment by v1ru3** [comment]
not sure i understand.

**Comment by fiveangle** [comment]
Yes, it appears there were configs that weren't updated.  I noted this here:

https://github.com/MarlinFirmware/Marlin/pull/8866#issuecomment-353923441

-=dave

**Comment by RudolphRiedel** [comment]
Yes, the issue is that it does not build with the provided example configuration and the fix would be to provide a valid example configuration for the next release.
As of why it fails, almost no problem at all.

**Comment by tcm0116** [comment]
I missed that in #8864. I'm working on cleaning up #7107, which I've included the change to the CR-10 example config. It should hopefully be merged in the next few days  Sorry about that.

**Comment by thinkyhead** [comment]
> the fix would be to provide a valid example configuration for the next release. ;-)

D'oh!

> #7107 … should hopefully be merged in the next few days

I'm testing it now and will merge it today.

**Comment by tcm0116** [comment]
>I'm testing it now and will merge it today.

Don't merge it quite yet. I'm working on adding the configurable
load/unload lengths and I found some issues with the LCD not being
displayed at the start of the action.

**Comment by thinkyhead** [comment]
Does the LCD issue only manifest on the 2nd and later invocations?

**Comment by tcm0116** [comment]
No. It manifests at the start of the process. For change filament, if you have the home before filament change option enabled and while it's homing, and for unload filament while it does the z lift. In both cases, the LCD (full graphic in my case), will be in an ambiguous state until the next step of the process.

I was working on it this morning, but I had to leave for the day. I'll get back to it this evening.

**Comment by thinkyhead** [comment]
> I was working on it this morning, but I had to leave for the day. I'll get back to it this evening.

Some thoughts…

- If the requested nozzle isn't heated it might be better to just start heating it and jump to the wait for heating screen. This will probably simplify some code also.
- When the nozzle is done heating, it shouldn't start loading or unloading right away, but should beep and go to the "Click to Load" or "Click to Unload" screen and wait for a click.
- The waiting screens should beep according to the `FILAMENT_CHANGE_NUMBER_OF_ALERT_BEEPS` setting. We should give the beep a distinctive sound, audible but less annoying than the current one. Something sort of like this…
```gcode
M300 S880 P50
G4 S1
M300 S660 P50
G4 S1
M300 S880 P50
G4 S1
M300 S660 P50
G4 S1
M300 S880 P50
G4 S1
M300 S660 P50
G4 S1
M300 S880 P50
G4 S1
M300 S660 P50
```
- Should the `load_filament` function also do the `extrude_length` as part of a complete load? Currently it will only do the post-load extrude when an LCD is present.
  - Perhaps we should use the word `PURGE` instead of `EXTRUDE` in reference to this part of the procedure.

**Comment by boelle** [comment]
@tcm0116 is this one "fixed"?

**Comment by tcm0116** [comment]
@boelle - I would think so, but it's been almost a year.

**Comment by boelle** [comment]
@tcm0116 just stiring the pot so to speak as to try and figure what issues have been solved and could be closed

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@RudolphRiedel status?

**Comment by RudolphRiedel** [comment]
I have no idea right now since it has been a while since I built a Marlin for one of my printers.
Not this long but maybe half a year.

I was about to check out a new archive and I am not sure which one.
The 1.1.x one seems to be getting updates despite the statement that it won't after 1.1.9.
The bugfix-1.1.x might be  the one to go then but "This branch is 44 commits ahead, 48 commits behind 1.1.x. "
Then the bugfix-2.0.x maybe? "This branch is 3534 commits ahead, 1816 commits behind 1.1.x."

**Comment by RudolphRiedel** [comment]
Okay, I went for 2.0, changed env_default in plattformio.ini to melzi.optiboot, copied over the files for the CR-10 and apart from two warnings it just built.
Then I updated my vscode and platformio, issued a Clean and then a Build again.
And it just built (same two warnings), data is 91,5% (14984 / 16384) and program is 93,1% (121064 / 130048).

**Comment by boelle** [comment]
> Then the bugfix-2.0.x maybe?

yes, its updated most and it has config files for CR-10 https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/config/examples/Creality/CR-10

**Comment by boelle** [comment]
as long you get a success in vscode after build you are good :-)
