### ISSUE TITLE
m420 command causes rough surface oncircles

### ISSUE THREAD

**Issue by Alexanderio99** [MarlinFirmware/Marlin#8906]
- Description: 
on my anycubic kossel plus and marlin 1.1.4 I use command
`M420 S1 Z10` before printing and get result as on the picture (some extra extrusion on the end of segments of circles)
![20171226_145114](https://user-images.githubusercontent.com/34868830/34363847-a1b66312-ea90-11e7-95f3-a11799d4b917.jpg)
![20171226_145040](https://user-images.githubusercontent.com/34868830/34363848-a1da41ce-ea90-11e7-8585-d2047005e8dd.jpg)

- Expected behaviour: 
should work fine with smooth wall

- Actual behaviour: 
uneven surface of the walls

- Steps to reproduce:
use `M420 S1 Z10` after bed leveling and print cilinder

- Workaround
if I use `M420 S1 Z5000` instead `M420 S1 Z10` everything works fine

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1587820/Marlin.zip)

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see if we fixed this issue. If the problem has been solved then we can close it. If you still see the bad behavior we should investigate further.

**Comment by Alexanderio99** [comment]
tested on bugfix-1.1.x - works fine. Thanks)
