### ISSUE TITLE
Linear Advance K-Factor Calibration G-code Generator Not Working

### ISSUE THREAD

**Issue by TurboChum** [MarlinFirmware/Marlin#8909]
Pressing Generate G-code then waiting or immediately following it by pressing download as file does nothing.
Tried on Mac with Chrome and Safari 
Tried on Windows with Chrome and Microsoft Edge
With no difference in result

**Comment by Sineos** [comment]
There is a typo in the script, thats why it is not working:
https://github.com/MarlinFirmware/MarlinDocumentation/pull/120

@thinkyhead or @Roxy-3D or @Bob-the-Kuhn: Please merge PR

**Comment by ArtemKuchin** [comment]
script http://marlinfw.org/tools/lin_advance/K-factor.js
not found, K must be lower case
NEED IT ASAP!

**Comment by cebtenzzre** [comment]
@ArtemKuchin In the Chrome developer console, I ran `var _loadScript = function(path){ var script= document.createElement('script'); script.type= 'text/javascript'; script.src= path; document.head.appendChild(script); }` and then `_loadScript('k-factor.js')` as a workaround.

**Comment by Sineos** [comment]
@thinkyhead 
Please...PLEASE merge https://github.com/MarlinFirmware/MarlinDocumentation/pull/120 or just swap the K for a k.
Another thread or pull request about a lower case 'k' and I will mutilate my printer with a fire axe and kill my dog. 

![insanity](https://user-images.githubusercontent.com/4459312/34424220-4df2dc4a-ec22-11e7-8a85-f44081fa04d3.jpg)

**Comment by plunderfest** [comment]
Not sure I understand the adding of a lowercase k, and how that resolves this?

**Comment by cebtenzzre** [comment]
The pull request was merged and as far as I can tell the issue has been resolved.  Someone should close this.
