### ISSUE TITLE
[BR] NO_VOLUMETRICS Compile Error ULTRALCD.CPP

### ISSUE THREAD

**Issue by houseofbugs** [MarlinFirmware/Marlin#8910]
I had to comment out the filament menu and 

![javaw_2017-12-26_17-28-16](https://user-images.githubusercontent.com/25088191/34366714-9d186376-ea65-11e7-92b3-430758beb2d2.png)
![javaw_2017-12-26_17-27-05](https://user-images.githubusercontent.com/25088191/34366715-9d25928a-ea65-11e7-8ef1-8ccd38c6e3ce.png)

I fixed it and will merge changes into the codebase.

**Comment by v1ru3** [comment]
I did the same this morning, however when I uploaded to my CR-10 the E motor makes a continuous whine noise (more like a hissing noise) and it doesn't move when commands are issued for it (gcode or via the screen).

Did you have any issues like that on yours?

**Comment by TurboChum** [comment]
@v1ru3 Same issue with mine when I defined NO_VOLUMETRICS hopefully its fully patched soon

**Comment by TurboChum** [comment]
@v1ru3 Just uploaded the latest bugfix and #define NO_VOLUMETRICS doesnt appear to be effecting the extruder anymore

**Comment by v1ru3** [comment]
Thanks for the follow up. I agree, they actually fixed it the day after.
However, the M851 issue still seems to linger with bilinear bed leveling though.
On mine it varies with M851 Z (if diferent z is specified, the M851 value is different)... good times!

**Comment by v1ru3** [comment]
Thanks for the follow up. I agree, they actually fixed it the day after.
However, the M851 issue still seems to linger with bilinear bed leveling though.
On mine it varies with M851 Z (if diferent z is specified, the M851 value is different)... good times!

**Comment by TurboChum** [comment]
@v1ru3 is it a rounded value? I set my Z on the controller and a M851 shows it rounded (3.875 to 3.88) but it is always correct on the controller

**Comment by v1ru3** [comment]
my issue with the offset is more like this
M420 Z5
G28
G29
the offset is 1.250

restart/reset
M420 Z10
G28
G29
the offset is 0.999
