### ISSUE TITLE
Is it possible to use 2 arduinos on a single printer?

### ISSUE THREAD

**Issue by manotroll** [MarlinFirmware/Marlin#8919]
I wonder if it is possible to use 2 arduinos together to add multi-color support on an A8?
using serial / spi or pi to manage this

**Comment by tcm0116** [comment]
Not currently. Does your control board have two Z Motor plugs? If so, you can just wire up the Z motors in parallel using something like this:

LERDGE 3D Printer Parts Motor Parallel Module for Double Z Axis Dual Z Motors for Lerdge 3D Printer Board
http://s.aliexpress.com/AreYNf2Y

**Comment by tcm0116** [comment]
Just took a closer look at the control board, and it looks like it only has 4 stepper drivers, so I guess the two Z Motor plugs are already wired to a single driver. 

Your best solution is probably to swap out the control board for one that has 5 drivers on it. 

Sorry for the confusion.

**Comment by manotroll** [comment]
yes maybe this is the best option

**Comment by thinkyhead** [comment]
@manotroll See also https://github.com/MarlinFirmware/Marlin/issues/4776#issuecomment-246262879
