### ISSUE TITLE
[FR] failed end-stop protection

### ISSUE THREAD

**Issue by ArtemKuchin** [MarlinFirmware/Marlin#8921]
I have seen on several occasions printers with failed end-stops at the end of print or intermittent failures.
Currently marlin just continues to find position where ens stop is triggered. However, it would be safer to check if the distance traveled in search of end-stop is already more than  total allowed movement distance then just stop.

**Comment by teemuatlut** [comment]
[That's kind of already the case.](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/module/motion.cpp#L1177)
The axis is moved 1.5 times the max length of an axis to the direction of homing dir.
