### ISSUE TITLE
http://marlinfw.org/tools/lin_advance/k-factor.html

### ISSUE THREAD

**Issue by plunderfest** [MarlinFirmware/Marlin#8938]
### Bug Report
- Description: --- http://marlinfw.org/tools/lin_advance/k-factor.html
- Expected behaviour: --- compile K factor code  
- Actual behaviour: ---  Does nothing - will not compel code 
- Steps to reproduce: 

  http://marlinfw.org/tools/lin_advance/k-factor.html
Page will allow you to change values, but does nothing after pressing button to compile G-CODE

**Comment by fiveangle** [comment]
Dupe of #8909

Fixed by https://github.com/MarlinFirmware/MarlinDocumentation/pull/120 (if/when it is merged)

-=dave

**Comment by chinoox** [comment]
the gcode view is very small :( in chrome. In firefox it is ok

**Comment by fiveangle** [comment]
close ?

**Comment by ikarisan** [comment]
Maybe this Google Chrome issue should be fixed, too:
![k-factor](https://user-images.githubusercontent.com/14032966/34455883-eb9945b2-ed88-11e7-8ecb-7bea5a31a4f1.png)

**Comment by Sineos** [comment]
https://github.com/MarlinFirmware/MarlinDocumentation/pull/124
Just needs merging.
