### ISSUE TITLE
[bugfix 2.0.x] Due not starting up if #define HAVE_TMC2130

### ISSUE THREAD

**Issue by dembach** [MarlinFirmware/Marlin#8939]
if #define HAVE_TMC2130 is active, i can compile, but the Arduino Due is not starting up.

i only disable this line and it is working.... same on MK4Due (marlin4kimbra).

it seems there is an issue with 32-bit and the TMC2130 library.

**Comment by teemuatlut** [comment]
I was just testing a printer with Archim2 which has the same MCU as DUE and has TMC2130 drivers, so this would seem very odd. I'll try this out tomorrow with a regular Arduino DUE board.

**Comment by dembach** [comment]
@teemuatlut : where can i get an Archim2 ? Ultimachine has none yet.... 
your Library is faulty , changes to get it working can be found here:

[https://github.com/Beherith/TMC2130Stepper](url)

thanks goes to @Beherith of MK4Duo Team ....
Issue was solved here:
[https://github.com/MKFirmware/MK4duo/issues/268](url)

i created a pull request regarding the changes on your GIT

**Comment by teemuatlut** [comment]
The Archim2 is a sample board provided by UltiMachine so that I can bring support for it both in the TMC2130 library and in Marlin.

**Comment by ImplementOfWar** [comment]
@teemuatlut How do you have an Archim2 board?  How do I get one for testing?  Ultimachine told me it wouldn't be available until early next year.

**Comment by teemuatlut** [comment]
Ultimachine came asking for official upstream support in Marlin 2.0 and I was interested but my first question was if they were going to provide a sample board to help with the development. I think it also weighed some that I was responsible for the TMC Arduino libraries and the implementation in Marlin, as well as having worked with Watterott and Trinamic before. So it's always about what you can do for them.

I believe this issue has been solved by recent changes to the TMC2130 library.

**Comment by ImplementOfWar** [comment]
@teemuatlut I hate you, :)  I offer them nothing other then the general user feedback I could give.  I just want to print stuff..  I'm using the MKS SBASE right now on most of my printers;  I want to upgrade to a nicer 32 bit board.  I didn't want to go REARM or AZTEEG.  I saw in the commits that Ultimachine was coming out with Archim 2.0 so I decided thats the board I was going to wait for.   I am waiting while YOU get to play with it (and make sure the stepper drivers are supported).  This is where my HATE comes from.   Its more envy then HATE;  I'm just not good with words and feelings. :D

**Comment by teemuatlut** [comment]
You could look into something like the ReprapWorld Ultratronics Pro.
It has the same Atmel chip as Archim2 and DUE and it has 7 removable stepper sockets. Even an integrated ethernet jack when we decide to do something in that area.

**Comment by dembach** [comment]
seems to work fine with tmc lib 2.1.4

**Comment by thinkyhead** [comment]
Yes, the latest TMC libs are looking good!
