### ISSUE TITLE
M115 Extended capabilities report appears incorrect, compared to documentation

### ISSUE THREAD

**Issue by zarthcode** [MarlinFirmware/Marlin#8943]
### Bug Report
- Description: Capabilities listed appear to be formatted incorrectly.
- Expected behaviour: 
Cap:SERIAL_XON_XOFF:1 (colon is documented as being included.)
- Actual behaviour: 
Cap:SERIAL_XON_XOFF1 (note the missing colon ':')
- Steps to reproduce:
As viewed from octoprint:
Send: M115
Recv: FIRMWARE_NAME:Marlin bugfix-1.1.x (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Black Widow (Z) EXTRUDER_COUNT:1 UUID:2ba3e31f-92b5-493b-91a6-caac3610c196
Recv: Cap:SERIAL_XON_XOFF1
Recv: Cap:EEPROM1
Recv: Cap:VOLUMETRIC1
Recv: Cap:AUTOREPORT_TEMP1
Recv: Cap:PROGRESS0
Recv: Cap:PRINT_JOB1
Recv: Cap:AUTOLEVEL1
Recv: Cap:Z_PROBE1
Recv: Cap:LEVELING_DATA1
Recv: Cap:BUILD_PERCENT0
Recv: Cap:SOFTWARE_POWER0
Recv: Cap:TOGGLE_LIGHTS0
Recv: Cap:CASE_LIGHT_BRIGHTNESS0
Recv: Cap:EMERGENCY_PARSER1
Recv: ok P15 B3

------------------------------------------------------------
Suggested fix/code in Marlin_main.cpp
```cpp
/**
 * M115: Capabilities string
 */

#if ENABLED(EXTENDED_CAPABILITIES_REPORT)
  static void cap_line(const char * const name, bool ena=false) {
    SERIAL_PROTOCOLPGM("Cap:");
    serialprintPGM(name);
    SERIAL_PROTOCOLPGM(":");
    SERIAL_PROTOCOLLN(int(ena ? 1 : 0));
  }
#endif
```

**Comment by thinkyhead** [comment]
Thanks for the patch!
