### ISSUE TITLE
Z axis issues

### ISSUE THREAD

**Issue by usajet** [MarlinFirmware/Marlin#8957]
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/1593651/Configuration_adv.txt)

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/1593650/Configuration.txt)

This is a home built Cartesian-XZ-head printer. When I home the z axis or do a bed leveling It lowers until PS light turns on then back up and down again until the light turns on then up about 10mm and stops. My other printer (Anet A8 type) homes until the z probe lights up and stops. Any ideas what it can be?

Also my other printer when I home it homes to the center of the bed and this one doesn't. Plus with the home built printer after I do a G28 and try to move the y axis to go to y- 0.10 it goes to the y- endstops and vibrates then stops.

**Comment by thinkyhead** [comment]
Closing as a non-question.
