### ISSUE TITLE
SD Card not working

### ISSUE THREAD

**Issue by R3play210** [MarlinFirmware/Marlin#8969]
Have Marlin 1.1.8
Using Ramps 1.4 with full graphic smart controller (SD card slot built in LCD)
When I insert a SD card the LCD says that a card has been inserted, however when you go into the menu it says that there is no SD card.
Simplify3D also says after connecting to the printer SD init fail.

Any idea what's happening here?

**Comment by R3play210** [comment]
SDSUPPORT is enabled btw

**Comment by frixuelos** [comment]
I solved it some weeks ago, try formating the SD card with https://www.sdcard.org/downloads/formatter_4/index.html

Try it.

**Comment by R3play210** [comment]
No results.
Found a 2gb card tried the same but still nothing :(

**Comment by R3play210** [comment]
Upon inserting the SDCard during a print the printer stops for a brief moment and then resumes.
Thougt of mentioning this aswell

**Comment by GMagician** [comment]
I have the same issue

**Comment by frixuelos** [comment]
Changing SD card and formating with that software works fine for me, still SD init error on the log, but working.

**Comment by GMagician** [comment]
Can't change SD, I have just one, reformatted but nothing changes

**Comment by R3play210** [comment]
I just replaced the EXP2 ribbon cable with another one I had laying around and it works!
Fitted the old ribbon cable back in and it doesn't work.

So I'm guessing a faulty ribbon cable :)

**Comment by GMagician** [comment]
I don't have other cables so I swapped the ones I have and issue is still present (in version 2.0)

**Comment by GMagician** [comment]
I made some test and it fails due to 'SD_CHECK_AND_RETRY' in this part:
```cpp
if (cardCommand( CMD59, 1 ) != R1_IDLE_STATE) {
    error(SD_CARD_ERROR_CMD59);
```

**Comment by houseofbugs** [comment]
Just chiming in here. SD is broken in 1.1.8. Cannot get it working on any machines with it.

**Comment by GMagician** [comment]
I made other test. CMD59 return 5 that is invalid command but I'm almost sure that before I saw it working!
CRC is not supported by all SD?

**Comment by GMagician** [comment]
Please note that #9164 doesn't solve @R3play210 issue.
My reported issue is only present in marlin 2.0

**Comment by shinigamiburakku** [comment]
Hola a todos use te traslate Google please,, la solución al problema de la sd está en ultralcd.cpp en la línea 1181 y 1188,, dice así #if !PIN_EXISTE (SD_DETECT) en las dos parte pero en la definísimo de pines se nombra como SD_DETECT_PIN solo cambiar lo que está entre paréntesis y solucionado en la pantalla lcd aparecerá el menú para cambiar la SD está es la solución que encontre marlin 1.1.9 y 2.0 bugfix testeado en ramps 1.4

**Comment by GMagician** [comment]
@shinigamiburakku if you look at PIN_EXISTS define you will see that _PIN will be added in test:
`#define PIN_EXISTS(PN) (defined(PN ##_PIN) && PN ##_PIN >= 0)` 
so if you pass to macro the complete name `SD_DETECT_PIN` the real tested name will be `SD_DETECT_PIN_PIN` and this won't exists for sure... I think that defining  `#define SD_DETECT_PIN   -1` is the same thing. So to resume your simply compiled with no SD pin detect logic
