### ISSUE TITLE
Testing motion control without thermistors installed + LCD enabled

### ISSUE THREAD

**Issue by barnyrelph** [MarlinFirmware/Marlin#898]
So I'm running Marlin v1, compiled under Arduino 1.05. Below are my changes to Configuration.h

```
#define MOTHERBOARD 33
#define ULTIPANEL  //the UltiPanel as on Thingiverse
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```

I've not yet got a heated bed or extruder, but I've got enough electronics together to start testing motion control.

```
Attempting any kind of motion in Pronterface results in this error:: 
Extruder switched off. MAXTEMP triggered !
Error:Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)
```
Looking at configuration.h, it looks like I can set the following:

```
#define TEMP_SENSOR_0 0
#define TEMP_SENSOR_1 0
```

However, when i do that, I get compilation errors :
```
ultralcd.cpp: In function 'void lcd_tune_menu()':
ultralcd.cpp:374: error: 'HEATER_0_MAXTEMP' was not declared in this scope
ultralcd.cpp: In function 'void lcd_control_temperature_menu()':
ultralcd.cpp:780: error: 'HEATER_0_MAXTEMP' was not declared in this scope
ultralcd.cpp:793: error: 'HEATER_0_MAXTEMP' was not declared in this scope
ultralcd.cpp:794: error: 'HEATER_0_MAXTEMP' was not declared in this scope
ultralcd.cpp: In function 'void lcd_control_temperature_preheat_pla_settings_menu()':
ultralcd.cpp:816: error: 'HEATER_0_MAXTEMP' was not declared in this scope
ultralcd.cpp: In function 'void lcd_control_temperature_preheat_abs_settings_menu()':
ultralcd.cpp:831: error: 'HEATER_0_MAXTEMP' was not declared in this scope
```
It looks like configuration_adv.h #undefs HEATER_0_MAXTEMP if TEMP_SENSOR_0 is set to 0, but then it's being relied on in ultralcd.cpp.

Is this an error which should be addressed or is it just that I'm attempting to something nonsensical? Is there another way to achieve stepper control without any thermistors present?

**Comment by alhirzel** [comment]
It might be cool to add a gcode which disables this check, akin to M302: http://reprap.org/wiki/G-code#M302:_Allow_cold_extrudes

**Comment by boelle** [comment]
@barnyrelph @nothinman @JackWS  @whosawhatsis @alhirzel 

is this still an issue with a fresh copy of marlin and IDE updated to latest non-beta?

**Comment by alexborro** [comment]
This is no more an issue.

One can set the thermistor to 999 to ignore the hardware input.

Cheers.

Alex.

2015-03-11 5:48 GMT-03:00 Bo Herrmannsen notifications@github.com:

> @barnyrelph https://github.com/barnyrelph @nothinman
> https://github.com/nothinman @JackWS https://github.com/JackWS
> @whosawhatsis https://github.com/whosawhatsis @alhirzel
> https://github.com/alhirzel
> 
> is this still an issue with a fresh copy of marlin and IDE updated to
> latest non-beta?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/issues/898#issuecomment-78224867
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by boelle** [comment]
ok closing then

**Comment by LukaBanovic** [comment]
@barnyrelph re to your comment "A few #ifdefs placed around all usages of TEMP_SENSOR_0 and HEATER_0_MAXTEMP did the trick!....". Could you tell what exactly you've done? I'm having the same issue and it doesn't work with 999 value as @alexborro  says.

Thanks!
