### ISSUE TITLE
Different behaviour of babystepping when BABYSTEP_ZPROBE_OFFSET btw lcd and m290

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#8997]
z babystepping is always done (lcd and m290) when BABYSTEP_ZPROBE_OFFSET is disabled but when enabled lcd babystepping is blocked if not `planner.leveling_active`.

Is there a reason for such different behaviour?

**Comment by Roxy-3D** [comment]
I don't think that makes sense...    At least for me, if I'm Baby Stepping, I'm not sure I want the machine second guessing me.   Baby Stepping moves slow enough (and I'm in control of the movement), I don't think we need to worry about any damage.

My opinion is we need to pull out the 'if' part and just do the  'then' clause unconditionally...
```
        if (planner.leveling_active)
              thermalManager.babystep_axis(Z_AXIS, babystep_increment);
```

**Comment by GMagician** [comment]
@Roxy-3D this is my idea too but since I don't have enough experience and historical knowledge maybe there was a reason to do that

**Comment by Roxy-3D** [comment]
I think this is safe to change...   I'll change it in both BugFix branches...
