### ISSUE TITLE
Help programming  :  classroom

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#8998]
This line works fine
`MENU_ITEM(function, MSG_FILAMENTCHANGE " " MSG_E1, lcd_enqueue_filament_change_e0);`

`lcd_enqueue_filament_change_e0` not a var but a function

but when i make a function like this , `lcd_enqueue_filament_change_e0` is unknown and not in the scope, but this function is global and accessible before
```
void  lalalalalla () {
MENU_ITEM(function, MSG_FILAMENTCHANGE " " MSG_E1, lcd_enqueue_filament_change_e0);
}
```
How to transmit it , in the scope 

thks

**Comment by Roxy-3D** [comment]
Declare your lcd_enqueue_filament_change_e0() function immediately above the function where you are trying to put the statement:
```
MENU_ITEM(function, MSG_FILAMENTCHANGE " " MSG_E1, lcd_enqueue_filament_change_e0);
```
That probably will resolve the scope problem.  (But it might not be the 'clean' way to get things defined.)

**Comment by ghost** [comment]
Hello @Roxy-3D 
Thks for your help , but finally it was a school old problem
Scope is a unit , some {} , but scope is also ' #if  + #endif ' 
And i have made a function with some inside function that have been created under ' #if  + #endif '  , and just for this , the compilator EXPLODE WITHOUT SAYING ' not under compilator scope '

I'm beginner 😄
