### ISSUE TITLE
http://marlinfw.org/tools/lin_advance/k-factor.html - RETRACTION BUG on alternate pattern

### ISSUE THREAD

**Issue by MasterPIC** [MarlinFirmware/Marlin#8999]
Please refer to the issue #8935 
By giving a look at gcode generated by the tool available online (to test LIN_ADVANCE) I found retractions (useful when not using alternate pattern) are still present at the start of each alternate pattern line.

**Comment by Sineos** [comment]
Fixed: https://github.com/MarlinFirmware/MarlinDocumentation/pull/124
