### ISSUE TITLE
[BR] Bed PID Autotune kills Heater Immediately

### ISSUE THREAD

**Issue by houseofbugs** [MarlinFirmware/Marlin#9005]
Running 1.1.8 release with PIDTEMPBED enabled. When going to tune the bed it immediately kills the printer. Tried on a Melzi board and MKS Gen 1.4. Same result on both.

> Send: M303 E-1 C8 S60
> Recv: PID Autotune start
> Recv:  T:23.19 /0.00 B:23.41 /0.00 @:0 B@:127
> Recv: Error:Heating failed, system stopped! Heater_ID: bed
> Changing monitoring state from 'Operational' to 'Error: Heating failed, system stopped! Heater_ID: bed
> '
> Recv: Error:Printer halted. kill() called!
> Changing monitoring state from 'Error: Heating failed, system stopped! Heater_ID: bed
> ' to 'Offline'

**Comment by Ordenkeim93499** [comment]
Maybe you can upload your Configuration.h and Configuration_adv.h just to see if there is something wrong

**Comment by revilor** [comment]
PR  #9037 fixes the issue, or setting WATCH_BED_TEMP_PERIOD in Configuration_adv.h to no more than 127 seconds
