### ISSUE TITLE
[BR] Probing Heaters Off does not kill bed in non-PID mode 1.1.8 RELEASE

### ISSUE THREAD

**Issue by houseofbugs** [MarlinFirmware/Marlin#9006]
When using PROBING_HEATERS_OFF it does not stop the bed from being turned on during probing when not using PIDBEDTEMP. This should also stop bang-bang regulation as well. It will affect sensors. Using 1.1.8 release.

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see if we fixed this issue. If the problem has been solved then we can close it. If you still see the bad behavior we should investigate further.
