### ISSUE TITLE
c++ classroom  VAR to string HELP

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#9015]
hi , i need to make a dynamic menu but , i don't know how to insert the active extruder inside the title
I have all tried , i need helP

STATIC_ITEM( "::" MSG_MOVE_E " E"   **active_extruder** , true);

To have this results as menu label  '  :: Extruder 1 '  for example

**Comment by thinkyhead** [comment]
```cpp
switch (active_extruder) {
  case 0: STATIC_ITEM( "::" MSG_MOVE_E1 , true); break;
  case 1: STATIC_ITEM( "::" MSG_MOVE_E2 , true); break;
  case 2: STATIC_ITEM( "::" MSG_MOVE_E3 , true); break;
  case 3: STATIC_ITEM( "::" MSG_MOVE_E4 , true); break;
  case 4: STATIC_ITEM( "::" MSG_MOVE_E5 , true); break;
}
```
