### ISSUE TITLE
marlin define pins as mega pin #s, not as ramps pin #s

### ISSUE THREAD

**Issue by pbbob** [MarlinFirmware/Marlin#9055]
I am designing my own shield for the mega2650 that i will use to control my printer. however, when defining pins in the marlin firmware, the pin numbers are the pin numbers of the RAMPS, not the Arduino Mega itself. How do i define pins so that i could write `#define HEATER1PIN 5` and it will make heater1pin be on _**arduino mega pin 5**_ __--NOT--__ _**RAMPS pin 5_**

**Comment by Tannoo** [comment]
![ramps 1 4 pinout](https://user-images.githubusercontent.com/26955383/34589604-dbd41b72-f16e-11e7-99a5-c91d116a0bd9.png)

**Comment by Tannoo** [comment]
Pin 5 = D5 = Servo 3

**Comment by pbbob** [comment]
what is D66 then? there is no pin 66 on the arduino mega. the mega only has 54 pins

**Comment by Tannoo** [comment]
D66 = A12

**Comment by Tannoo** [comment]
Look at the drawings. It's all there.

**Comment by Bob-the-Kuhn** [comment]
Here's a couple of items I found useful.  

Curiosity - what does your shield do that RAMPS doesn't?

![arduino-mega-pinout-diagram](https://user-images.githubusercontent.com/20692583/34590037-e9602c08-f179-11e7-84fb-4d53956b04b6.png)
[arduino-mega2560-schematic.pdf](https://github.com/MarlinFirmware/Marlin/files/1605139/arduino-mega2560-schematic.pdf)

**Comment by Tannoo** [comment]
ooh... I like the finger. lol
