### ISSUE TITLE
Looking for Geetech Delta firmware

### ISSUE THREAD

**Issue by ChrisP28** [MarlinFirmware/Marlin#9061]
### Firmware for Geetech Delta printerRostok Mini Copy.

Has any one got a copy of firmware that will work with this printer? I have tried for nearly a year now and I have been unable to get a copy of the software that will compile. Either Fpos or position errors stop the compiling. I'm not a programmer and have no C++ experience so I'm unable to repair the problem. Could someone point me in the direction of a complete programme ans the correct version of Arduino to compile it and upload it to the machine. I understand that the final calibration of the printer will be required, I can do that bit.

**Comment by cjsoong** [comment]
download firmware marlin 1.1.8
http://marlinfw.org/meta/download/
arduino ide V1.90 BETA版 
  https://www.arduino.cc/en/Main/Software

**Comment by Roxy-3D** [comment]
> Has any one got a copy of firmware that will work with this printer.

Ah...  Yes.   If you mean the printer in this review:  http://3dprintboard.com/showthread.php?16024-Geeetech-G2s-Printer-Kit-Review

**Comment by dembach** [comment]
on Geetech they are referring to Marlin ;-)

https://www.geeetech.com/wiki/index.php/GT2560

the Link to the Firmware archive : 
http://www.geeetech.com/wiki/images/3/39/Marlin-Marlin_v1.zip

so you only need examine the configuration and the pins to find out, if the board is anything special.

The configuration for a delta is described on the marlin.org documetation.
the Initial Parameters for the delta are described here:
https://www.geeetech.com/wiki/index.php/Delta_Rostock_mini_G2s
Board Type:
`#define MOTHERBOARD BOARD_GT2560_REV_A`
only missing parameters are the thermistors of heatbed and hotend.
so if you start with a fresh download of marlin , open it in arduino , use a delta example configuration as start, put in the given parameters , it should work fine with compiling.
if not, just post the error message here.,,,

**Comment by boelle** [comment]
@ChrisP28 
Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
