### ISSUE TITLE
MKS GEN 1.4 + TMC2130: Printer freezes after 4 layers

### ISSUE THREAD

**Issue by mesnik** [MarlinFirmware/Marlin#9082]
Hopefully someone can help me!! Thanks in advance!!!!

### Bug Report
- Description: Printer halts before finishing firs layer (benchy boat). Have to reboot printer, but issue persists.

- Expected behaviour: Print the entire part without stopping mid print.

- Actual behaviour: in the middle of the firslt layer, the printer halts requiring reboot.

- Steps to reproduce: every time I send a part to print, using Simplify3D.

Got this error message once:
READ: E driver error detected:
READ: Error:Printer halted. kill() called!
WARNING: Firmware unresponsive.  Attempting to force continue...

And this on the next repeating attempts:
READ: E driver error detected:
READ: overtemperature
READ: Error:Printer halted. kill() called!
WARNING: Firmware unresponsive.  Attempting to force continue...

EXTRA INFO:  I first had a bad TMC driver (noticed a small splatter of solder on the pot) and I replaced it on the X axis.  I have since swapped the X TMC with the extruder TMC in case that driver was also damaged BUT issue still happening the same way.  So in my mind, I am either connecting the extruder TMC to wrong pins (I am following Tom's youtube layout - have checked at least 10 times with at least 4 different cables) or I have something missing/wrong on the firmware.

I can also add that is not the power supply as I hooked up a 45A, heavy duty to it and it did the same thing...
; )

Thanks for the help!!!

[Marlin118.zip](https://github.com/MarlinFirmware/Marlin/files/1609190/Marlin118.zip)

**Comment by mesnik** [comment]
IGNORE

**Comment by lemmingDev** [comment]
Are they the fysetc or watterott ones?

I'm having problems with the fysetc ones...

**Comment by mesnik** [comment]
I bought them at Digikey, in the US... not sure how to tell the difference...

**Comment by mesnik** [comment]
...looking closer, I see the www.watternott.com printed on them

**Comment by mesnik** [comment]
FINAL RESULTS and ISSUE UPDATED on first post

**Comment by mesnik** [comment]
The drivers needed cooling!!
