### ISSUE TITLE
BLTouch Smart sets nozzle too high off bed

### ISSUE THREAD

**Issue by mistsoul** [MarlinFirmware/Marlin#9089]

**Comment by Roxy-3D** [comment]
After homing...    Can you use PronterFace to lower the nozzle (very carefully) until the nozzle just touches the bed.    What does the printer think the Z-Height is?    (Look at the LCD and/or issue a M114 command)

**Comment by mistsoul** [comment]
thanks for your help @Roxy-3D 

with a paper sliding under the nozzle it is about -31.5 to lower it to the paper. 

To be able to do this i had to temporarily undefine MIN_SOFTWARE_ENDSTOPS or set my zmin to a high negative in the firmware.

With G28 the probing works and it goes to the middle of the bed, then m114 returns x,y,z at 0,0,0 eventhough z is well above the bed. This is the case even if i set a -z offset. Then G1 Z0 does not do anything since it thinks it is already at 0.

G29 does not bring the probe back to x,y 0,0, it skips to the right then tries to probe but fails. If i trick it by placing something under the probe before it fails, it continues moving to the x axis but rams the xmax extrusion since it thought the middle was point 0. In any case G29 either fails to reach the bed or reaches it but does not retract, both case sends it into an error.

Trying to home z individually sends it to the back right corner which would theoretically correspond to the middle if was trully starting at x,y, 0,0. There the head rattles also, then the probing there goes into an error too.

Latest configuration is attached.

[Marlin-1.1.x - MT2.0.zip](https://github.com/MarlinFirmware/Marlin/files/1613851/Marlin-1.1.x.-.MT2.0.zip)

**Comment by Roxy-3D** [comment]
@thinkyhead  is the Bi-Linear expert....    Let's wait and see what he says...

**Comment by mistsoul** [comment]
Thanks
 
MY safe homing issue is as described in #1502 however in my case it is not an issue between repetier or ponterface, even the LCD values show 0 so i believe it is something in my firmware config having to do with the safe homing overwriting the x and y home values. 

I thought my G28 Z forbidden and no movement on G1 Z0 and G29 failed probing was related to incorrectly setting the steps/mm in my configuration but it is not the case as I have corrected the steps.

Having Z safe homing is rewriting my x/y zero position and the software endstops is preventing -z offsets from taking place. I have tried switching to the latest release but it won't compile as it does not acknowledge that a pin board was already define in the configuration h. I will keep searching and wait to see if anyone has a suggestion.

**Comment by mistsoul** [comment]
Apparently the firmware I was using had additional files from the printer manufacturer which had some modifications made by them on how G28 behaves, maybe to accommodate their laser toolhead. I am not sure if this is the cause of my issue, but I have now migrated to the latest Marlin version 010107 and updated/compiled it without the extra files. I will give it a try later and see if i still have the issues above.

Edit: Using the latest Marlin and omitting the aforementioned files fixed my rezeroing on G28 issue. My Z still ends up too high so I will need to look at the configuration further. G1 Z0 also works correctly now, so once I am able to get my G28 Z close to the bed I assume that G29 will work. Will keep this post update and hopefully i can close it soon.

**Comment by mistsoul** [comment]
Problem fixed.

**Comment by tramage** [comment]
I'm having the same issue.  I have spent numerous hours following several tutorials on YouTube for Lowering the nozzle to the correct distance from the bed that should be Z0 including the instructions listed in this thread.  I used the long list of commands on Pronterface including the M211 S0, slowly lowering my nozzle then trying to set that for my new Z0 but when I home again it goes right back to being nearly 3 or more mm higher.  
The one video I watched the most that seemed to help at first was:
https://www.youtube.com/watch?v=y_1Kg45APko&t=6s
But I still cannot get the nozzle at the correct height.
Any suggestions?

**Comment by RFBomb** [comment]
@tramage  
The order should be:
M211 S0
M851 Z0
G28
G0 X Y [Middle of bed]    (so current position - probe offset for X and Y respecitvely)
Manually lower Z until nozzle touches bed. 
M851 [Current Z value]  (SO if you are at -2.1, then that is your new Z offset)

Repeat the process. Your nozzle should be at z0 touching the bed.

**Comment by mistsoul** [comment]
@tramage

I am not sure if your issue has to do with how you edited your firmware, if so the Marlin team may need to see a log of your changes.

Otherwise the video you posted is very good, and I derived the following steps from it not long ago, and this is how I level my bed (some of the steps are not absolutely needed but it works for me):

Home
M851 Z0
M500 [save]
M501 [active]
M503 [read]
G28 Z
G1 F50 Z0
M211 S0 

Slide paper underneath and lower nozzle as indicated in the video
When you reach the right Z height, don't forget to account for the paper thickness (0.1)
So if you obtain an offset of -1.3 your final Z offset is -1.3-0.1=-1.4 which is # per Z# below

M851 Z#
M211 S1 
M500 save
M501 active
M503 read
