### ISSUE TITLE
[Question] Disabling Z home double bumping in Marlin 1.1.8


### ISSUE THREAD

**Issue by ismangil** [MarlinFirmware/Marlin#9100]
Since using a piezo sensor, I want to disable the double bump feature of Z homing.

I've already increased the double bump speed (piezo requires certain speed to make sure it triggers) by setting divisor to 1.

Configuration_adv.h:
```
#define Z_HOME_BUMP_MM 5
#define HOMING_BUMP_DIVISOR { 2, 2, 1 }
```

Is it possible to disable it entirely?

**Comment by GMagician** [comment]
Setting Z_CLEARANCE_BETWEEN_PROBES and/or Z_HOME_BUMP_MM to 0 should disable second search but I 'don't know if something else will be touched by these values.
N.B If HOMING_Z_WITH_PROBE is set then only first define is necessary
