### ISSUE TITLE
Auto-Calibration V Auto-Leveling - Terminology

### ISSUE THREAD

**Issue by JackWS** [MarlinFirmware/Marlin#911]
Auto-calibration is when you tell software to read external environments. Auto-leveling might, I guess say you are auto-leveling what Z is within software.

Auto- Bed Leveling - is misleading. There are non-printer devices that physically do bed leveling.

Can you please change the term Auto-leveling to Auto-Calibration or Auto-Bed Mapping or something so there can be a single page that everyone can get on?

thanks!!!

**Comment by boelle** [comment]
i will kill this one again... to me it was just a fight over wording things
