### ISSUE TITLE
Bug Report 1.1.7 Mesh Bed Leveling Fade height

### ISSUE THREAD

**Issue by jfodor1975** [MarlinFirmware/Marlin#9118]
### Bug Report
- Description: 1.1.7 Mesh Bed Leveling Fade height
- Expected behaviour: no Z axis jumps 
- Actual behavior: z axis jump @ 8.1mm+- height
- Steps to reproduce: set fade height to 10mm

  - Do this: set fade height to 10 mm, z axis will jump and effectually create what looks like a missed layer or an improperly adhered layer, orange cube in picture, stopped print early.

  - Do that: set fade height to 0.00 mm, no missed layers, red cube in picture.

![fade height](https://user-images.githubusercontent.com/11047532/34745499-ba58e18c-f55e-11e7-9af9-bdba8db60fe0.jpg)

i'm using mesh bed leveling active with the following settings:
```gcode
Send: M503
Recv: echo:  G21    ; Units in mm
Recv: echo:  M149 C ; Units in Celsius
Recv: 
Recv: echo:Filament settings: Disabled
Recv: echo:  M200 D1.75
Recv: echo:  M200 D0
Recv: echo:Steps per unit:
Recv: echo:  M92 X100.00 Y100.00 Z400.00 E156.90
Recv: echo:Maximum feedrates (units/s):
Recv: echo:  M203 X400.00 Y400.00 Z2.00 E15.00
Recv: echo:Maximum Acceleration (units/s2):
Recv: echo:  M201 X9000 Y9000 Z25 E10000
Recv: echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
Recv: echo:  M204 P2000.00 R2000.00 T3000.00
Recv: echo:Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_us> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
Recv: echo:  M205 S0.00 T0.00 B20000 X10.00 Y10.00 Z0.40 E5.00
Recv: echo:Home offset:
Recv: echo:  M206 X0.00 Y0.00 Z0.00
Recv: echo:Mesh Bed Leveling:
Recv: echo:echo:  M420 S1 Z0.00
Recv: echo:  G29 S3 X1 Y1 Z1.08500
Recv: echo:  G29 S3 X2 Y1 Z1.42500
Recv: echo:  G29 S3 X3 Y1 Z1.45000
Recv: echo:  G29 S3 X1 Y2 Z1.05000
Recv: echo:  G29 S3 X2 Y2 Z1.35000
Recv: echo:  G29 S3 X3 Y2 Z1.35000
Recv: echo:  G29 S3 X1 Y3 Z0.97500
Recv: echo:  G29 S3 X2 Y3 Z1.12500
Recv: echo:  G29 S3 X3 Y3 Z1.17000
Recv: echo:Material heatup parameters:
Recv: echo:  M145 S0 H180 B70 F0
Recv: echo:  M145 S1 H240 B110 F0
Recv: echo:PID settings:
Recv: echo:  M301 P25.32 I1.66 D96.46
Recv: echo:Z-Probe Offset (mm):
Recv: echo:  M851 Z-1.49
Recv: ok
```

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/1616845/Configs.zip)

i haven't seen this sort of issue reported, and if it's truly and issue i'm glad i could help.

**Comment by thinkyhead** [comment]
Please test the latest `bugfix-1.1.x` branch. This issue may already have been fixed.
