### ISSUE TITLE
[FR] Anet A2 Support ?

### ISSUE THREAD

**Issue by dustinreeves** [MarlinFirmware/Marlin#9135]
https://github.com/thijsk/Skynet3d/tree/master/SkynetV2.3.2/Configuration%20Profiles/Anet%20A2

^-Can we port these anet a2 configuration profiles into marlin current ?

**Comment by fiveangle** [comment]
Yes, it should not be hard.  Easiest is to use some text comparison utility such as WinMerge, BeyondCompare, or even "_vim -d_" then migrate the settings by hand to the new Configuration.h and Configuration_adv.h files from current Marlin.

-=dave

**Comment by dembach** [comment]
maybe it can be moved to the example folders and altered to the new marlin version..

**Comment by dustinreeves** [comment]
I'm half ass handy I'll do a diff and see if I can do my first merge tonight (was really hoping someone had already done the legwork for me :p )

**Comment by dustinreeves** [comment]
this has turned into a much more daunting task than i originally imagined, (very new to 3d printing)  Will probably wait this out until someone with more experience chimes in ?

**Comment by diegohsoriano** [comment]
Same case here, I need to install Marlin into an Anet A2.  Could you please share the instructions to create the config files? Thanks! :)

**Comment by thinkyhead** [comment]
Keep on trying. Examine the example configurations for guidance. Get a "merge" or "diff" plugin for your favorite text editor. Compare the default configs to some of the example configs for practice. You'll get it.

**Comment by IngoTheMan** [comment]
Is it only the configuration.h and configuration_adv.h files that need to be changed to make this work? I did take a quick look at the files and it seems that the configuration_adv.h file don't need to be changed at all. Also, if I manage to port skynet 2.3.2 settings to newest marlin (I'm totally new at this) how do I share my work?

**Comment by thinkyhead** [comment]
@IngoTheMan — http://marlinfw.org/docs/development/getting_started_pull_requests.html

**Comment by beukhof1** [comment]
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/2178112/Configuration.txt)

Ok so i compared the merlin A8 config to the skynet A2 config and this is what i changed. Can someone take a look at it and see if its save to use this?

@IngoTheMan Can u please share your config? And is it working right?

**Comment by nicopenna** [comment]
Hi @beukhof1 did you tried the firmware?? I getting some problems with marlin 1.1.9 and my anet A2.
