### ISSUE TITLE
[FR] [bugfix_2.0.x] Definition of PID Values per Extruder

### ISSUE THREAD

**Issue by dembach** [MarlinFirmware/Marlin#9137]
like in MK4Duo:

```
#define DEFAULT_Kp {6.47,40,40,40}
#define DEFAULT_Ki {0.43,7,7,7}
#define DEFAULT_Kd {24.46,60,60,60}
```

**Comment by GMagician** [comment]
Have you tried to enable PID_PARAMS_PER_HOTEND in your configuration file?
You can't define pid in such way but you can have different values per each extruder

**Comment by dembach** [comment]
Ohh.. thanks.... not seen that parameter....
