### ISSUE TITLE
MarlinFirmware is now on Slack

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#9154]
https://marlinfirmware.slack.com/

This is a web-based chat style interface with Channels similar to IRC. It then adds the ability to embed media including formatted code. This should help to improve the back and forth between hardcore code monkeys where the forum style doesn't do as well. Slack itself is a fairly unobtrusive service, and sign-up takes seconds.

I invite the @MarlinFirmware/general-maintainers and regular contributors to join.

@tcm0116 @teemuatlut @LVD-AC @akaJes @Sebastianv650 @Bob-the-Kuhn @AnHardt @p3p 

Feel free to invite any others I have omitted.

![image](https://user-images.githubusercontent.com/698003/34865907-282690d2-f740-11e7-90f7-d74e968930fb.png)

**Comment by teemuatlut** [comment]
Great, but how do I get on?
> Don't have an account on this workspace yet?
Contact the workspace administrator for an invitation

I created an account but it doesn't work for Marlinfirmware. All I can do with it is create a new workspace.

**Comment by LVD-AC** [comment]
I got this:

 

We couldn't find workspaces for this address.

If you're looking for a specific workspace, you can try contacting your
Workspace Administrator for an invitation.

 

I'll just wait for formal r.s.v.p. in the mail.

 

-----Original Message-----

**Comment by psavva** [comment]
I would approve an invite too @thinkyhead

**Comment by Bergerac56** [comment]
I would like to be "invited" too ;)

**Comment by Sebastianv650** [comment]
So do we need an invitation before we can register or vice versa?

**Comment by fiveangle** [comment]
Most other projects that use slack simply set permissions so anyone can join 🤷‍♂️

**Comment by Zakm0n** [comment]
In Replicape's slack they have permissions set where contributors and devs have their own code monkey channel, and there is general troubleshooting and config help separately. I feel like it is much more accessible than using github's issues forum for newer users trying to troubleshoot.

**Comment by oysteinkrog** [comment]
For what it's worth I agree with what Zakm0n said.

**Comment by jbrazio** [comment]
@thinkyhead I can't join, it tells me to contact you.

**Comment by LVD-AC** [comment]
I can created a workspace with my email and could set up a password for it but that login doesn't work.

**Comment by thinkyhead** [comment]
Ah, I have to use your email address to send an invite…
Easiest way to send it to me is to use my contact form:

http://www.thinkyhead.com/contact — Choose the "**Marlin Firmware**" category.

**Comment by boelle** [comment]
should be pinned
