### ISSUE TITLE
[2.0.x] Unable to save EEPROM on Re-ARM

### ISSUE THREAD

**Issue by tcm0116** [MarlinFirmware/Marlin#9156]
I'm on https://github.com/MarlinFirmware/Marlin/commit/da600e5fbed07c98580681fb81be0077deda7f56 with a Re-ARM board on my Delta machine. Trying to save the EEPROM results in a size error. I enabled `DEBUG_EEPROM_READWRITE`, and it failed on `home_offset`. I ended up adding `_FIELD_TEST` checks for each of the `planner` values between `esteppers` and `home_offset`, and it failed at `planner_axis_steps_per_mm`. Everything looks correct in `SettingsData` as well as in `HAL::PersistentStore::write_data` for the LPC1768 HAL, so I'm not sure where the issue lies.

**Comment by p3p** [comment]
Same issue as mentioned in #9056? Haven't had time to look into it yet was hoping @thinkyhead would fix it before I had to ^^

**Comment by tcm0116** [comment]
@p3p Yes, it is the same issue. Hopefully the details I provided above will
help with the diagnosis. It seems like there's an issue with eeprom_index,
but it wasn't obvious.

**Comment by cjsoong** [comment]
I use arduino due + ramps fd is the same problem.
This problem is added G-code M504 began to appear,
Before 2018-01-05 download version is ok

**Comment by tcm0116** [comment]
Turns out that it's due to the variables within structs being aligned on 4-byte boundaries on 32-bit systems. Just submitted a PR to address it.

**Comment by Roxy-3D** [comment]
Good change!   And this is mostly a rhetorical question.   But now would be a good time to say everything in the 32-bit world is aligned on DWORD boundaries if that made sense.   Do we really need to save every byte of data space in the 32-Bit world?

**Comment by tcm0116** [comment]
@Roxy-3D for the EEPROM, it needs to be byte aligned since the values are
written without padding. The structure that gets wrapped by the #pragma is
actually only used to determine what the length of the EEPROM data should
be.

**Comment by chrisjenda** [comment]
I have tried again with the latest #9236 merge on my re-arm+ramps setup and I am still getting the error.   I have the default config consisting of only two changes; the Motherboard Define being set to BOARD_RAMPS_14_RE_ARM_EFB and EEPROM_SETTINGS un-commented.  This causes the following error on M500

Recv: Error:EEPROM datasize error.
Changing monitoring state from 'Operational' to 'Error: EEPROM datasize error.

Pastebin of the config:
https://pastebin.com/pBPH6RLf

**Comment by tcm0116** [comment]
Can you try enabling `DEBUG_EEPROM_READWRITE` in configuration_store.cpp and report the result?

**Comment by chrisjenda** [comment]
Recv: Error:Field lpq_len mismatch.
Changing monitoring state from 'Operational' to 'Error: Field lpq_len mismatch.

**Comment by tcm0116** [comment]
I found the problem. Line 550 of configuration_store.cpp needs to change
from int to int16_t for the lcd_preheat variables. Can you try that and
confirm (my printer is currently occupied printing a Bullet Bill).

**Comment by tcm0116** [comment]
I just submitted #9240 with the change above. That should resolve the issue for when there's not an LCD.
