### ISSUE TITLE
Serial disconnecting from host mid print - mks sbase/2.0

### ISSUE THREAD

**Issue by Zakm0n** [MarlinFirmware/Marlin#9170]
Print is going excellent for a couple layers then this:

SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

This is happening with my windows machine using s3d as a host as well as my linux machine with octoprint. Any ideas where to start troubleshooting?

**Comment by Spawn32** [comment]
I run s3d on windows and use a MKS Sbase, never had this problem :/

**Comment by Zakm0n** [comment]
Well I have linear advance and a bunch of other features enabled and I'm printing decently fast. Is it possible it is just too much for usb printing?  Is it possible to print from sd  with this setup?

**Comment by p3p** [comment]
@Zakm0n It shouldn't be too much, the Native USB serial support on the LPC1768 boards runs at USB speed its not limited by the baud rate you specify, I have had an odd issue recently where Octoprint disconnected just after I connected a few times with this error, but never during a print, I'l have a look into it.

**Comment by Zakm0n** [comment]
@p3p I have my baud rate set at 115200 in firmware, should I speed that up?

**Comment by p3p** [comment]
The setting has no effect, the USB serial on the LPC1768 is not a usb to serial converter chip like on (most?) Arduino boards it uses the native USB layer from end to end. It will run as fast as it can over USB (1.1 12Mbit) using the normal USB flow control.

**Comment by Zakm0n** [comment]
Ok, well I'm trying a new cable now. I can't come up with anything else that would cause that to happen mid print. Typically octo users see this error with a bad cable or PSU, but I'm using a laptop to run octo and I've tried two different cords with the same outcome. Maybe 3rd time is a charm.

**Comment by tcm0116** [comment]
I was setting a somewhat similar issue yesterday. After connecting with the PlatformIO serial monitor and sending a M500 command, the serial monitor would crash. The printer didn't seem to crash,  I could reconnect, and continue normally.
