### ISSUE TITLE
Help: Marlin 1.1.8 - 'e' was not declared in this scope

### ISSUE THREAD

**Issue by dcwalmsley** [MarlinFirmware/Marlin#9181]
Compile Error
When I attempted to compile I received this, 'e' was not declared in this scope.

```
Marlin_Main.cpp
Line 10998 - select_multiplexed_stepper(e);  is highlighted
```
I'm attempting to configure Multimaterial configuration to my HyperCube installed with Prusa's MMU upgrade kit and his multiplexer board.

[Files.zip](https://github.com/MarlinFirmware/Marlin/files/1629944/Files.zip)

r,
Doug W

**Comment by revilor** [comment]
I guess the line in question is 10098 (and not 10998) where e is supposed to be s.

**Comment by thinkyhead** [comment]
Your best bet is to use `bugfix-1.1.x` which has some 1.1.8 issues patched, including this one.

**Comment by dcwalmsley** [comment]
bugfix-1.1.x did the job!  I was able to enable 
#define EXTRUDERS 4
#define SINGLENOZZLE
and
#define MK2_MULTIPLEXER
#if ENABLED(MK2_MULTIPLEXER)
  // Override the default DIO selector pins here, if needed.
  // Some pins files may provide defaults for these pins.
  #define E_MUX0_PIN 40  // Always Required
  #define E_MUX1_PIN 42  // Needed for 3 to 8 steppers
  //#define E_MUX2_PIN 44  // Needed for 5 to 8 steppers
#endif

Compile worked without any errors messages.
