### ISSUE TITLE
Custom Boot Screen Error

### ISSUE THREAD

**Issue by yurtkan** [MarlinFirmware/Marlin#9192]
Hi i am using marlin 1.1.8 version and Rumba Board . I tried to add custom boot screen but i receive error message.
exit status 1
'custom_start_bmp' was not declared in this scope
Can anybody help me ?

**Comment by AnHardt** [comment]
example in ...\examples\BQ\Hephestos_2

**Comment by yurtkan** [comment]
Sorry i forgot write in issue . I modified _Bootscreen.h and copyed to marlin folder but i receive error

**Comment by AnHardt** [comment]
Doublecheck your bootscreens array name. It must be 'custom_start_bmp', Any other name will fail.

**Comment by Yurtkany** [comment]
i checked all is ok but its still receive error. can you write full instructions because i cant find in internet.

**Comment by yurtkan** [comment]
ok i did it thanks
