### ISSUE TITLE
Enable BedLevel as option in Prepare menu

### ISSUE THREAD

**Issue by snowzach** [MarlinFirmware/Marlin#920]
Self explanatory enhancement.

I think this should be the code:
ultralcd.cpp in function lcd_prepare_menu()

Add:
#ifdef ENABLE_AUTO_BED_LEVELING	
	MENU_ITEM(gcode, MSG_BED_LEVEL, PSTR("G29"));
#endif

In language.h you'll have to define the message MSG_BED_LEVEL

**Comment by boelle** [comment]
looking at this one... dont we have manual bed level implemented?

**Comment by thinkyhead** [comment]
Yes we do! It uses a 3x3 mesh system by default, with manual adjustment between steps, and it saves the results to EEPROM.

**Comment by snowzach** [comment]
The request was actually for the auto bed level gcode option in the menu. Was that implemented?

**Comment by thinkyhead** [comment]
@snowzach I see that only the _mesh bed leveling__ is in the menu so far. So I have just added an option for _Auto Bed Leveling_ too: #1984

**Comment by snowzach** [comment]
Sweeeeeeeet thanks!
