### ISSUE TITLE
[Question] Step Rates 

### ISSUE THREAD

**Issue by CCS86** [MarlinFirmware/Marlin#9207]
Hi guys,

I am running 20 tooth GT2 pulleys on my UMO, formerly with 1.8* steppers and configured at 80 steps/mm (X&Y) and 16 microstepping. I recently swapped out to steppers with 0.9* step angle. I doubled the steps/mm to compensate initially. I did subsequently change to non-integer steps/mm (159, 159.2) to fine tune sizing, which I read isn't an issue. But, I have noticed an odd resonance in Y axis only, at moderate speeds (20-60mm/s).  I'm not sure if that is related to the non-integer steps/mm setting or not.

In hopes of higher torque and better positional accuracy, I plan to switch to 8 microstepping; halving the steps/mm.

Have I been anywhere near the maximum step rate of the ATMega2560? The bold entry in the table here suggests maybe (but also says the table is out of date and the limits are too high):

http://reprap.org/wiki/Step_rates

Thoughts?

On a similar note, I have a question about Z stepping resolution. Occasionally, I do spiral vase prints. Looking at Cura's gcode output, the Z movements are in increments of 0.001mm. My Z drive is 200 steps/mm (and 16 microstepping). 200 * 0.001 = 0.2 steps... but that is micro steps right? How does Marlin handle moves that are less than 1 microstep? Does it accumulate them until they total a full microstep?

Thanks!!

**Comment by Sebastianv650** [comment]
It's not possible to give a maximum possible step rate, it depends on way too much factors. All we can speak about are the limits where Marlin will switch to double and quad stepping:
0-10kHz: single steps
10-20kHz: double steps
above 20kHz: quad stepping

I prefer to stay within single step range for print moves, for example if you want to print at 80mm/s your maximum steps/mm value is allowed to be <125. 125*80 = 10kHz.

Second question:
Don't mix up microstepping and Marlin steps. Yes, 200steps/mm * 0.001mm are 0.2 steps. This means, Marlin will do nothing in Z. Marlin always calculates the target position in steps, the needed steps along an axis is target-last position. So as long as target_mm * [steps/mm] = last_position, nothing will happen.

**Comment by CCS86** [comment]
Awesome, thank you for the insight @Sebastianv650! 

When calculating step rate limitations (or even steps/mm) for Marlin, we are talking about microsteps though, yes? Otherwise, you could change microstepping, without adjusting steps/mm.

Do you think 8 microstepping could be the cause of that resonance? I've been changing a bunch of stuff lately, so it's hard to say for sure. Mechanically, it is in really good shape. I have gantry friction down very low and even.

**Comment by CCS86** [comment]
Well, apparently I got ahead of myself. I have not flashed the new settings to drop to 8 microstepping. The machine is still at 16 microstepping and around 160 steps/mm (interestingly X is at 159 and the resonating axis Y is at 159.2).

[original post edited to fix my mistake]

**Comment by Sebastianv650** [comment]
> When calculating step rate limitations (or even steps/mm) for Marlin, we are talking about microsteps though, yes? Otherwise, you could change microstepping, without adjusting steps/mm.

In fact microstepping is only relevant for the stepper driver. For Marlin, it's all about "steps". If Marlin has to execute 10 steps, it's not important if the stepper driver sends signals for full steps, microsteps or whatever. It just has to trigger 10 steps at proper steprate.
As you already stated, for the final result the important one is that steps/mm setting is adjusted as needed. If you need 10 full steps to get from point A to B, after switching to 16x microstepping on the stepper driver this will become 160 steps.

**Comment by CCS86** [comment]
Okay, good, that was my understanding.

Any thoughts on non-integer steps/mm causing resonance? I never noticed it at the beginning of a print, only after it had been running for a bit. Loudest on Y only moves, still there on compound moves, quiet on X only. I'll keep my ear out for it and try setting Y axis to an integer steps/mm if I hear it again.

Thanks!

**Comment by Sebastianv650** [comment]
No, step/mm is not related to resonance in terms of float or integer. Resonance is a function of mass and frequency. If if you compare noise at a fixed feed rate changing steps/mm, you are actualy changing the feed rate so you can get a difference.

**Comment by GMagician** [comment]
@Sebastianv650 that interesting....
I have 32 microsteps and a 0.9°/step motor hence I have 400 steps x unit.
Max speed is 120mm/s that means 48KHz and it seems working...
This frequency is far from values you write...maybe I badly translated your above post

**Comment by Sebastianv650** [comment]
I'm sure what you mean. There was a Markdown format error in my first post, maybe you read 20kHz as max frequency? It's not, above 20kHz Marlin switched to quad stepping. I corrected the format error.

There is no fixed upper limit in Marlin (OK there is one, but you will most likely never reach it..). At some point your CPU load will be 100%, meaning you get no higher speed even if you double the feed rate and you might see some fancy errors showing up like bad heater handling and so on.

**Comment by GMagician** [comment]
Ok that was what happened when speed was higher than 120...
Thanks for your reply
