### ISSUE TITLE
feature request : multiple extruders running simultaneously 

### ISSUE THREAD

**Issue by ekaggrat** [MarlinFirmware/Marlin#923]
hi,

i am experimenting with a color mixing extruder.. would it be possible to add a feature to run multiple extruders simultaneously in different ratios? i am generating the gcode using a grasshopper script  
example : g1 x100 y100 z10 e1 10 e2 20 

thanks

**Comment by boelle** [comment]
This one is nearly a year old and it will only benefit a few people.. as @nothinman  said people are very welcome to contribute by adding a PR...

so this one is closed

**Comment by Virtox** [comment]
With the arrival of the diamond hot-end 3-in-1-out and similar type extruders, this question has become a bit more valid.
And I'd be happy to team up with some-one to see if we can implement something useful.
But reading the above, with regard to the load on the mcu:
If the g-code is implemented to specify mixing with something like E0.33:0.33:0.33, I expect the extra loads should be minimal? (And I will look into the mentioned M160)
Or is processing data for two more steppers really too much for the small mcu?
Any advice is welcome before I spend too much time on a lost cause ;-)

**Comment by T3P3** [comment]
Things have moved on a lot since I suggested `M160` and implemented an example in old versions of RepRapFirmware.

Have a look at the `M563` gcode command on the RepRap wiki. This is how we do it in the RepRapFirmware - once you get into the region of multiple drives feeding one hotend this is a better solution.

**Comment by Virtox** [comment]
Thanks I will have a look at that too! As I was also looking at repetier which uses a similar scheme with virtual extruders.
But at the moment I am also very much interested in the possibility of driving the extruders directly from g-code.

**Comment by thinkyhead** [comment]
Definitely post this as a new issue on MarlinDev. It's something we definitely want to continue to look at.

**Comment by Virtox** [comment]
Thanks, done!

**Comment by thinkyhead** [comment]
Trackback: MarlinFirmware/MarlinDev#361
