### ISSUE TITLE
FWRetract slow speeds.

### ISSUE THREAD

**Issue by Squid116** [MarlinFirmware/Marlin#9250]
### Bug Report
- Description: retraction speeds are slow with high values of retraction speed and length.
  - I recently changed my titan to run as Bowden, and have hit this problem when trying to tube retraction.

- Expected behaviour: 
  - retractions occur at speed in retraction settings.

- Actual behaviour: 
  - Retraction is slow, when higher values of speed and length are used.

- Steps to reproduce:
  - Slice a file using fw retract
  - increase retraction speed and distance and the problem occurs, retraction is slow and acceleration seems erratic (sometimes 90% will happen quickly, then the last 10% will be really slow.
  - same appears to occur on unretractions

Eg 
40mm/s and 10mm causes the issue.
20mm/s and 10mm doesn't.

Using retraction from slic3r these speeds and lengths work fine.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1647788/Marlin.zip)

EEPROM status:
```
Send: M503
Recv: echo:  G21    ; Units in mm
Recv: echo:  M149 C ; Units in Celsius
Recv: 
Recv: echo:Filament settings: Disabled
Recv: echo:  M200 D3.00
Recv: echo:  M200 D0
Recv: echo:Steps per unit:
Recv: echo:  M92 X160.00 Y160.00 Z800.00 E1674.18
Recv: echo:Maximum feedrates (units/s):
Recv: echo:  M203 X300.00 Y300.00 Z5.00 E160.00
Recv: echo:Maximum Acceleration (units/s2):
Recv: echo:  M201 X400 Y400 Z3000 E10000
Recv: echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
Recv: echo:  M204 P200.00 R3000.00 T600.00
Recv: echo:Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_ms> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
Recv: echo:  M205 S0.00 T0.00 B20000 X5.00 Y5.00 Z0.40 E5.00
Recv: echo:Home offset:
Recv: echo:  M206 X0.00 Y0.00 Z0.00
Recv: echo:Unified Bed Leveling:
Recv: echo:  M420 S1 Z10.00
Recv: 
Recv: Unified Bed Leveling System v1.01 active.
Recv: 
Recv: Active Mesh Slot: 0
Recv: z_offset: 0.000000
Recv: EEPROM can hold 33 meshes.
Recv: 
Recv: echo:Material heatup parameters:
Recv: echo:  M145 S0 H190 B80 F0
Recv:   M145 S1 H240 B110 F0
Recv: echo:PID settings:
Recv: echo:  M301 P19.80 I1.39 D70.57
Recv: echo:  M304 P273.73 I44.55 D420.45
Recv: echo:Retract: S<length> F<units/m> Z<lift>
Recv: echo:  M207 S2.00 W0.00 F2400.00 Z0.00
Recv: echo:Recover: S<length> F<units/m>
Recv: echo:  M208 S0.00 W0.00 F4200.00
Recv: echo:Auto-Retract: S=0 to disable, 1 to interpret E-only moves as retract/recover
Recv: echo:  M209 S0
Recv: echo:Z-Probe Offset (mm):
Recv: echo:  M851 Z-2.48
Recv: echo:Linear Advance:
Recv: echo:  M900 K0.00 R0.00
Recv: ok
```

**Comment by Squid116** [comment]
I blew away my repo and got latest bugfix 1.1.x and it seems to be going better.  Will continue to monitor and report back.

**Comment by jameswood** [comment]
Are you using TMC2130 drivers? I was having the same problem and solved it with tweaks to the current.

**Comment by Squid116** [comment]
@jameswood nope, drv8825

I can confirm this is happening... Feels like an overflow issue - (years of Dev experience) but I could be wrong.

Drv8825 32 microsteps.
0.9 degree stepped
3:1 titan extruder
1674 esteps/mm

All of these are pretty high from what I have seen.

Only happens when velocity, length and acceleration are sufficiently high.  I can see a quick extruder move. (jerk?) followed by a long slooooow series of steps till (can be 20+ seconds) the end of the retraction.

Is there some debugging I can insert to help diagnose?

**Comment by Squid116** [comment]
@roxy-3d sorry to tag you just to bump this up, but this issue is killing me - could I get some advice on how to get the debugging output you guys would need?

**Comment by Squid116** [comment]
Switched to 1/16 microsteps, and can definitely retract more, will play with speed tonight.

**Comment by Squid116** [comment]
I think this was a limit of the stepping rate on the mega - I have since upgraded to a re-arm so I am unable to reproduce/test so I'm going to close this off.

**Comment by Arismane** [comment]
@jameswood Can you please tell me what tweaks to the current did you do to solve the problem, because I have the exact same problem with TMC2130 drivers installed and I choose to retract maximum on 25mm/s in order to get rid of it. Thanx in advanced.

**Comment by jameswood** [comment]
@Arismane From memory, I think I had to turn the current up. This made the driver eventually overheat, so I added a fan to cool it. Every machine is different, but if it helps at all, I presently have the current set at:
`#define E0_CURRENT         800`

I usually retract 2mm at 40mm/s (Bowden, Titan, E3D v6, 2.85mm)
