### ISSUE TITLE
[Question] Info about disable_all_heaters method

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#9260]
inside the function there is:
```cpp
  HOTEND_LOOP() setTargetHotend(0, e);
  setTargetBed(0);
```
and then call to `DISABLE_HEATER(NR)` that do almost the same things. there is a reason for this duplicated code?

Theoretically 'setTargetHotend' inside DISABLE_HEATER could be removed

**Comment by AnHardt** [comment]
The one is setting the target temperature. The other sets the pins directly for the case the regulation does not work anymore.

**Comment by GMagician** [comment]
@AnHardt that's not completly true. Latter also set target temperature so first should be a duplicate

**Comment by thinkyhead** [comment]
I was wondering about it myself. If both heater disables are in fact needed then it should be explained in a comment so that future developers will not be confused by this duplication.

**Comment by thinkyhead** [comment]
The original code contained only the direct heater disable code. The new loop at the top was added by @Bernhard here [in this commit](https://github.com/MarlinFirmware/Marlin/commit/415aadf704ff545de2db90ffaf2fc351af78331a#diff-7e90b29c765c3047c7dc2aa8eff0856cR546), also here [at the top of the commit log](https://github.com/MarlinFirmware/Marlin/commits/bugfix-1.1.x?before=415aadf704ff545de2db90ffaf2fc351af78331a+35).
