### ISSUE TITLE
1.1.8 Print Counter issue

### ISSUE THREAD

**Issue by jamesbit** [MarlinFirmware/Marlin#9266]
```cpp
/**
 * Print Counter
 *
 * Track statistical data such as:
 *
 *  - Total print jobs
 *  - Total successful print jobs
 *  - Total failed print jobs
 *  - Total time printing
 *
 * View the current statistics with M78.
 */
#define PRINTCOUNTER
```
In 1.1.8 release I can't get the INFO MENU with print counter ecc. on the LCD screen.

Can anyone help me ?

Thank you.

Jamesbit.

**Comment by thinkyhead** [comment]
Did you enable `LCD_INFO_MENU`?

**Comment by jamesbit** [comment]
No...I forgot to enable it in the advance configuration...
Now works !!!
Thank you...
