### ISSUE TITLE
Pi and Printer 

### ISSUE THREAD

**Issue by donal1** [MarlinFirmware/Marlin#9268]
I'm working on a small project. I want to be able to send g code from my pi to my ramps and mega running marlin. As well as work in a depth sensor that can read distance and convert the distance to g code, that can send it to my printer. I've read a bit about echo and serial communication and know it plays a role but this is a little above my skill set. 

Firstly I need a way to send g code from a Linux terminal (Pi).
Secondly a way to convert distance to g code.
Thirdly a way to send this converted g code to the printer.

(this may be the wrong forum if it is let me know and I can move it)

**Comment by thinkyhead** [comment]
It's a pretty involved question. You should post it at http://forums.reprap.org/list.php?415
