### ISSUE TITLE
Preventing pre-homing crashes

### ISSUE THREAD

**Issue by whosawhatsis** [MarlinFirmware/Marlin#927]
When Marlin starts up, it assumes its position is zero. Most printers home to zero, which means that, if soft endstops are enabled) they will be unable to move toward their endstops except by homing, but they will be able to move in the opposite direction, which usually has no endstop. This is not a very safe way to operate, and the situation should really be reversed so that the axes can ONLY move toward their endstops (or at least not past their starting point in that direction) until they have been homed.

There are several ways to achieve this. The most obvious is to home all axes to MAX instead of MIN, but this is not how most machines are built, so I wanted to get opinions on some of the other options. Here are some of the possible ways to make this happen:

1. Change the starting position (where the printer thinks it is when it starts up) to the MAX position for any axis that homes MIN, and vice versa.
2. Always make the axes' zero points the furthest points from their endstops.
3. Prevent all non-homing moves for an axis until it has been homed.
4. Use a boolean flag (set false at startup) to indicate whether an axis has been homed, and restrict each axis to moving only toward the endstop (MIN or MAX) until the flag indicates that it has been homed.
5. like 4, use special start-up values for software endstops instead of the values set in the configuration, and replace those values with the ones in defined in the configuration file when homing occurs.

Any of these could result in unexpected behavior, but that behavior should result in safer failure modes than the current behavior. I'm leaning towards 5, but I wanted to get some more opinions and see if anyone else has a better idea before proceeding.

**Comment by thinkyhead** [comment]
Closing this for now! Maybe open a feature request or a PR with homing improvements later. Homing is one of the big 7 topics.
