### ISSUE TITLE
Feature Request: Limit carriage position to positive float: Improved software end stop for Deltas?

### ISSUE THREAD

**Issue by MRGiacalone** [MarlinFirmware/Marlin#928]
Hi,
I am doing a few tests on the delta moves using different Marlin distribution (i.e. Zalm, Cattell, Hercek). I encountered a problem when testing manual moves using both Repetier-Host and Pronterface. As discussed here (http://forums.reprap.org/read.php?267,355792) and here (https://groups.google.com/forum/#!topic/deltabot/tUJ1ty6yebg) the main thing that we are testing is the furthest reach of the delta arms using numeric manual moves. (one of the carriages is at 0.00 or close)
The initial problem is that at a certain point (where the delta arm cannot reach according to its length) one of my steppers gets stuck running continuously. It would be better if it stop al together rather than running wild.
M114 in both hosts show that after such point one the carriage is sent to a very low position (negative number) causing it to spin continuously.

http://forums.reprap.org/file.php?267,file=33256

    Repetier-Host:
    X:  0.00 Y:  0.00 Z:0.00 E:0.00 Count X: 253.31 Y:253.31 Z:253.31
    X:  0.00 Y:104.45 Z:0.00 E:0.00 Count X: 205.79 Y:205.79 Z:274.00
    X:134.30 Y:104.45 Z:0.00 E:0.00 Count X:   3.68 Y:220.47 Z:238.83
    X:134.40 Y:104.45 Z:0.00 E:0.00 Count X:-958.72 Y:220.47 Z:238.83

    Pronterface:
    X:  0.00 Y:  0.00 Z:0.00 E:0.00 Count X: 253.31 Y:253.31 Z:253.31
    X:  0.00 Y:104.45 Z:0.00 E:0.00 Count X: 205.79 Y:205.79 Z:274.00
    X:134.30 Y:104.45 Z:0.00 E:0.00 Count X:   3.68 Y:220.47 Z:238.83
    X:134.40 Y:104.45 Z:0.00 E:0.00 Count X:-418.61 Y:220.47 Z:238.83

Would it be possible to limit the position of the carriage to no less than Z + Vertical effector offset?
This would avoid the carriages to try to reach a position lower than the effector. In addition to changing the software end stops to simulate a triangular region rather than a rectangular or circular one, might even be used as an improved software end stop for the Delta's.
![points](https://cloud.githubusercontent.com/assets/7512698/3042065/2fd73d00-e0fa-11e3-8633-25d7f490eb67.png)

**Comment by thinkyhead** [comment]
@MRGiacalone I'm not sure I have the right value from config for the vertical effector offset, but here's what I have so far for limiting the delta movement:

```
void calculate_delta(float cartesian[3]) {
  // Proposed in #928 to limit these values to
  // Z plus the vertical effector offset
  // Impossible positions will just be in the wrong place
  float cx = cartesian[X_AXIS], cy = cartesian[Y_AXIS], cz = cartesian[Z_AXIS],
        dx = sqrt(delta_diagonal_rod_2 - sq(delta_tower1_x - cx) - sq(delta_tower1_y - cy)),
        dy = sqrt(delta_diagonal_rod_2 - sq(delta_tower2_x - cx) - sq(delta_tower2_y - cy)),
        dz = sqrt(delta_diagonal_rod_2 - sq(delta_tower3_x - cx) - sq(delta_tower3_y - cy));

  dx = constrain(dx, 0, DELTA_DIAGONAL_ROD / 1.414);
  dy = constrain(dy, 0, DELTA_DIAGONAL_ROD / 1.414);
  dz = constrain(dz, 0, DELTA_DIAGONAL_ROD / 1.414);

  delta[X_AXIS] = dx + cz;
  delta[Y_AXIS] = dy + cz;
  delta[Z_AXIS] = dz + cz;
}
```

**Comment by Wurstnase** [comment]
```cx = cartesian[Z_AXIS],```
cx? or cz?

**Comment by thinkyhead** [comment]
@Wurstnase CQ!

**Comment by boelle** [comment]
So this one should really be moved to a bug fix milestone?

**Comment by thinkyhead** [comment]
@boelle Yeah, I think this counts as a bug, and a pretty serious one. At the very least, it needs to disallow negative values, but constraining the ABC carriages so that they can never be very far from each other should be the most reliable, and allow for free movement regardless of how "twerked" the delta arms might get.

So, let's add this to a milestone and try to get it fixed for the next round!

**Comment by boelle** [comment]
will also close this one... OP have not said anything nor have anyone else. we have enough issues to deal with and non-active ones loose
