### ISSUE TITLE
[FR] Is there a way to compile and/or upload without the arduino-IDE

### ISSUE THREAD

**Issue by schorsch3000** [MarlinFirmware/Marlin#9291]
#### prolog
At first, this is not a Feature Request, but is it the closes match.
I even don't knof if this is the right place to ask, but i did not found a mailinglist or a chat, so this seems to be my only option, so feel free to point me to the right place for something like this.

#### My real Question
My current setup as an Anet A8 (with optiboot), running Marlin 1.1 connected to a raspberry pi running Octoprint.
My current workflow for flashing new / reconfigured version of marlin is:
 - remove my laptop from its dockingstation
 - walk over to the printer
 - disconnect the printer from the RPI
 - connect the printer to the laptop
 - open the arduino ide and upload
 - reconnect and reloacate everything

I really would like do simplify this workflow, basically i would like to flash the printer from the rpi.
Optional i would like to compile marlin without the arduino-ide.

Is this possible and there some Documentation anywhere how to do this?
I don't need a ready-out-of-the-box solution, i'll happily write some shellscripts to glue everything together, there are 2 things that i don't know how to do:
 - how can i compile marlin without the arduino-ide, or with the arduino-ide, but headless.
 - how would i flash the binary from the step before, is that just a avrdude call with the right params? maybe thay are even in the arduino-ide's log?

Thanks Dirk

**Comment by oakdesign** [comment]
Have a look at Platformio CLI which would be able to run of a any Platform including RPi and can perform all the requested task such as compile, upload from command line
http://platformio.org/get-started/cli

**Comment by schorsch3000** [comment]
That look great, i'll try out later, thanks!

2018-01-22 14:13 GMT+01:00 oakdesign <notifications@github.com>:

**Comment by benlye** [comment]
This OctoPrint plugin lets you flash compiled firmware hex files to the printer from OctoPrint:
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater

For the Anet A8 choose `Atmega1284p` as the MCU, and `arduino` as the programmer.  It requires you to install avrdude on the Raspberry Pi.

**Comment by oysteinkrog** [comment]
The current platformio setup works great for exactly this scenario, just make sure to disconnect from the printer in octoprint before you run the pio command to compile and upload.

**Comment by tcm0116** [comment]
OctoPrint-FirmwareUpdater is exactly what you want. You can keep your laptop in the dock, build Marlin, and then flash the hex file to your printer from the Pi via OctoPrint.

**Comment by schorsch3000** [comment]
So, platformio on my Laptop and FirmwareUpdated in Octoprint bundles with sum curl in a shellscript seems to be my sweet spot.
I'll give it a try and will report back.
Thanks so long for all the hints!

**Comment by tcm0116** [comment]
You don't necessarily need PlatformIO. When you click verify in Arduino IDE, it generates the hex file. It's a bit of a pain to find, but here's a little guide:

http://www.theengineeringprojects.com/2015/10/hex-file-arduino.html

**Comment by schorsch3000** [comment]
@tcm0116 Not using the arduino-ide is one half of the whole point :)
I really would like to just `make upload` or something like that and, without running some gui, build and flash my new firmware :)

So, firmware-updater doesn't work for me, the dialog closes, no logline is written.

i came up with a buildUpload.sh like so:
```
#!/bin/bash
set -e
set -x
platformio  run -e anet10 -v
scp .pioenvs/anet10/firmware.hex octopi.local:
ssh octopi.local "sudo service octoprint stop && avrdude  -patmega1284p -carduino -P/dev/ttyUSB0 -b115200 -D -Uflash:w:firmware.hex:i ;  sudo service octoprint start"
```
which works fin for me.
Thanks!

**Comment by benlye** [comment]
> So, firmware-updater doesn't work for me, the dialog closes, no logline is written.

Did you actually click the big blue 'flash from file' button after selecting your hex file?

**Comment by schorsch3000** [comment]
> Did you actually click the big blue 'flash from file' button after selecting your hex file?
In fact: no, i didn't get it.

While trying to reproduce my steps, i'm quite sure that button was disabled all the time, maybe i've missed some setting last time.
I tried again, it works as it should.
But i stay with my solution, less mouse movement included :)

**Comment by benlye** [comment]
The button stays disabled until all the requirements are met - if you hover over it while it is disabled you get a tool-tip telling you why it is disabled.  I'm the plug-in author, so I just wanted to make sure it wasn't a bug.

I'm glad it worked in the end, even if you don't use it.
