### ISSUE TITLE
Unicode Static menu bug

### ISSUE THREAD

**Issue by karabas** [MarlinFirmware/Marlin#9294]
### Bug Report
- Description: ---
Marlin 1.1.16  1.1.8
Cyrillic support is incorrect for static menu items. For LCD2004 ( rrd smart controller)

- Expected behaviour: ---
correct unicode translation as it is for nonstatic menu items.

- Actual behaviour: ---
F.e.
Move axis -> Move X -> Move 10mm -> 
Correctly displaying.
-> Move X: xxxx 
Incorrectly displaying. 
Looks like it forgets about unicode  and displays raw strings, two bytes per char.  

Something wrong with STATIC_MENU functions.

**Comment by karabas** [comment]
Printer Info translates correctly

**Comment by thinkyhead** [comment]
I'm unable to see any difference in `lcd_implementation_drawmenu_static` and `lcd_implementation_drawmenu_generic`. They both use `charset_mapper` to put characters to the display.

Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see if we fixed this issue. If the problem has been solved then we can close it. If you still see the bad behavior we should investigate further.

**Comment by boelle** [comment]
@karabas Please test with the latest `bugfix-2.0.x`
