### ISSUE TITLE
UBL Mesh issues with 1.1.8

### ISSUE THREAD

**Issue by modem7** [MarlinFirmware/Marlin#9316]
### Bug Report
- Description: Mesh is not using full bed size
- Expected behaviour: Mesh uses full bed size
- Actual behaviour: Mesh is not using full bed size, starts at wrong point.
- Steps to reproduce:
  - Building mesh in step-by-step UBL configuration
  - Probing reaches all accessible points

Updated firmware, cloned settings. 

Wanhao i3 v2.1, 200x200x180 w/ BLTouch.

If I'm being an idiot, please let me know!

Thanks!

-----------------------------------------------------------

[config.zip](https://github.com/MarlinFirmware/Marlin/files/1657801/config.zip)

**Comment by Festivejelly** [comment]
Does this same behaviour exist in an earlier version? Such as 1.1.5? I run this version with a 5mm inset and have no issues.

**Comment by modem7** [comment]
The 10mm inset was just a test I did, but no, previous version had zero issues

Here's my config from earlier version (prior to update) 

[config early.zip](https://github.com/MarlinFirmware/Marlin/files/1657843/config.early.zip)

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see if we fixed this issue. If the problem has been solved then we can close it. If you still see the bad behavior we should investigate further.

**Comment by Roxy-3D** [comment]
I believe this issue came about with the change to use BED_SIZE.    It was fixed roughly a month ago.

**Comment by modem7** [comment]
Will give it a whirl this weekend to test!

**Comment by thinkyhead** [comment]
We can re-open this if the problem recurs.
