### ISSUE TITLE
Board resets while printing some specific gcode files

### ISSUE THREAD

**Issue by aaulick** [MarlinFirmware/Marlin#9329]
### Bug Report
- Description: 
When printing certain gcode files (I have two), the printer will reset to splash screen as if I hit the reset button early in the print, always at the same line.  Other files print fine to the end.  Nothing obviously special about the failing files.  
- Expected behaviour: 
Printer should print the full file without reset.
- Actual behaviour:
On reaching the certain spot in the print, printer will reset as if I had power-cycled it or hit the hardware reset button.  Once only, I have seen it freeze with blank LCD screen instead of reset.
- Steps to reproduce:
Print any of the attached gcode.
I have edited the "snakes" gcode included in problem.files.zip to include only the crashing portion, crash is reproducible identically with all three versions of this tiny file.  The final line 76 is a long, straight extrude line.  This line gets printed correctly, then the firmware crashes.  Doesn't matter what comes after the "bad" line, if I add the normal file which continues printing the skirt, or the end-print GCode, or just end the file there abruptly, behavior is the same.  If I comment the "bad" line 76, the crash just moves to the next line.  If I rotate the model and slice it that way, then it prints fine.

Also included "sponge_holder1.gcode" in problem.files.zip, this one gets through the skirt and crashes early in the first layer, also after a long, straight extrusion.

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.
[Customized source.zip](https://github.com/MarlinFirmware/Marlin/files/1658595/Customized.source.zip)
[Problem Files.zip](https://github.com/MarlinFirmware/Marlin/files/1658602/Problem.Files.zip)

Using Arduino MEGA 2650 clone with RAMPS 1.4

**Comment by AnHardt** [comment]
The 'delta' problem with 'long' lines should be fixed in the newest bugfix versions.
