### ISSUE TITLE
[Q] How to add "pugging"

### ISSUE THREAD

**Issue by shinss86** [MarlinFirmware/Marlin#9349]
I wish to add material pugging function for few second before start printing part, where should i add the coding into?

**Comment by revilor** [comment]
Please be a little bit more specific in what you are looking for. Do you need 

- a way for your (clay?) printer to pause for a few seconds like G4?
- to turn on e.g. a MOSFET to activate some kind of mechanics?
- to implement some custom g code?
- something completely different
