### ISSUE TITLE
[2.0.x] With newest firmware printer seems to work in a 'simulated mode'

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#9350]
After update my firmware with latest PR the printer doesn't work anymore.

Al manual commands works as expected but once I start printing from repetier.
gcode is executed in a 'simulation mode'. Doesn't wait temperature on bed nor hotend, gcode advance (with cold extrusion prevention fault) but axes are stopped

**Comment by GMagician** [comment]
If seems that new implementation of _BV is not working as expected

**Comment by GMagician** [comment]
@thinkyhead don't tell me why but g800 P1 set codebits to 0xFFFF8000
Maybe is only debug mode that display a wrong value...

**Comment by benlye** [comment]
There's definitely something wonky with the parser since #9327.  Also, trying to compile with `FASTER_GCODE_PARSER` disabled fails:
```
In file included from Marlin\src\gcode/gcode.h:250:0,
from Marlin\src\Marlin.cpp:49:
Marlin\src\gcode/parser.h: In static member function 'static bool GCodeParser::seen(char)':
Marlin\src\gcode/parser.h:147:43: error: 'valid_float' was not declared in this scope
if (b) value_ptr = valid_float(&p[1]) ? &p[1] : (char*)NULL;
^
```

**Comment by benlye** [comment]
Reverting 80d3ded89523b741cec40c43cc09673411eaf168 and 399bca316a5abe64f18ce202699822fcd9738b98 seem to make the parsing problem go away.

**Comment by GMagician** [comment]
@thinkyhead I confirm, new _BV implementation doesn't works as expected. I tried different fix but it seems that compiler works with signed variables

**Comment by Allted** [comment]
Just to re-enforce this I am seeing the same sort of issues.

**Comment by GMagician** [comment]
It has no sense to keep open more issues about the same problem. Since #9366 better resume who is "guilty". I close mine
