### ISSUE TITLE
[2.0.x bugfix] firmware dont report temperature to host

### ISSUE THREAD

**Issue by Alissonverd** [MarlinFirmware/Marlin#9353]
The version of today 26-01-2018 dont report temps to host.
The command M155 dont work.

Older version of firmware (2.0.x bugfix) works fine.

**Comment by GMagician** [comment]
I think this has something in common to #9350. I think it's a parser issue

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see if we fixed this issue. If the problem has been solved then we can close it. If you still see the bad behavior we should investigate further.

**Comment by boelle** [comment]
@Alissonverd Please test with the latest `bugfix-2.0.x`

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
