### ISSUE TITLE
TMC2130, DON'T WORK IN SPEADCYCLE

### ISSUE THREAD

**Issue by benny64** [MarlinFirmware/Marlin#9359]
Can't get tmc2130's to work in speadcycle, When I try to home x and y just have a mind of the own and go opposite way, sensor-less homing also doesn't work in speadcycle tried -60 to 60 still crashes.
Switching to Stealthchop on and problems go away.
I've attached config if anyone fancys a look, 
cheers  

[config.zip](https://github.com/MarlinFirmware/Marlin/files/1669042/config.zip)

**Comment by oysteinkrog** [comment]
@benny64: were you able to fix this?
