### ISSUE TITLE
DUE TMC2130 SoftSPI

### ISSUE THREAD

**Issue by sh4jonny** [MarlinFirmware/Marlin#9372]
Hi all! How to build bugfix-2.0.x branch with teemuatlut/TMC2130Stepper in soft spi mode for DUE board? and how to config soft spi pins?
thank you!!!!

**Comment by sh4jonny** [comment]
Can i use it in HW SPI maybe ?

**Comment by teemuatlut** [comment]
HW and SW SPI are working with DUE and latest library from git.
The options to configure the pins and enable SW SPI are coming with PR #9114.

**Comment by sh4jonny** [comment]
Hi All! Excuse me pls...  @teemuatlut 
i make 
#define TMC_USE_SW_SPI
#define TMC_SW_MOSI 4
#define TMC_SW_MISO 6
#define TMC_SW_SCK 5

in my pins_RAMPS_DUO.h

and get Driver erron PRINTER HALTED on my LCD...
where i'm wrong ? thank you

P.S: yesterday it work on mk4duo with Soft SPI and https://github.com/Beherith/TMC2130Stepper.git

**Comment by teemuatlut** [comment]
I will need more information to help you.
What's the serial output?
Does it halt right after booting?
What fork are you running?

**Comment by sh4jonny** [comment]
@teemuatlut thank you for reply. so look. i try to run tmc2130 on DUE with hacked RAMPS with your TMC2130Stepper lib. Marlin last bugfix-2.0.x And try to do this in Soft SPI mode. i read PR #9114 and try to enable SW SPI like this
#define TMC_USE_SW_SPI
#define TMC_SW_MOSI 4
#define TMC_SW_MISO 6
#define TMC_SW_SCK 5
and I get Driver error PRINTER HALTED on my LCD... Yes right after booting.

**Comment by teemuatlut** [comment]
Are you running the upstream bugfix-2.0.x or are you running my LPC_TMC2130 fork?
The software SPI integration hasn't been merged into upstream yet.

**Comment by sh4jonny** [comment]
"The software SPI integration hasn't been merged into upstream yet."
there is a answer!!! thank you! i understand now!!!

**Comment by NeelD87** [comment]
@teemuatlut  is software SPI now available in bugfix 1.1 branch ? I have the drivers working well in hardware SPI but connected them over LCD adapter and had to disable SD card.
