### ISSUE TITLE
Compilation error with #define NO_WORKSPACE_OFFSETS and Delta 

### ISSUE THREAD

**Issue by brunogm0** [MarlinFirmware/Marlin#9376]
### Compile Error
When I compile with `#define NO_WORKSPACE_OFFSETS` I get an error:
```
update_software_endstops   not declared
```

i think is because of  Marlin_main.cpp:L1284

**Comment by GMagician** [comment]
Which version are you using? 1.1.8 or bugfix 1.1.x?
Both bugfix (1.1.8 and 2.0x) compile with no problems.

Maybe your configuration may help

**Comment by brunogm0** [comment]
1.1.8, also tried the bugfix;
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/1674259/Configuration_adv.zip)

**Comment by blueeagle69** [comment]
I'm not sure if I'm running the bugfix, but I'm running Marlin is 1.1.8.
I just set #define NO_WORKSPACE_OFFSETS to use my Resumer 3D, and it compiled and uploaded fine to my printer.
