### ISSUE TITLE
[2.0.X] SERIAL_PORT_2

### ISSUE THREAD

**Issue by kevintong116** [MarlinFirmware/Marlin#9377]
Is the SERIAL_PORT_2 now working in 2.0?
I would like to connect my Touch screen (sth similar to mks tft)
I set the SERIAL_PORT_2 to 3 and I modified the pins_RAMPS.h so that nothing is using pin 14 and 15
```
#define Y_MIN_PIN          100
#define Y_MAX_PIN           3
```
But I still can't get it connected.
What can I do?

**Comment by cjsoong** [comment]
@kevintong116ｎMaybe does not support software uart
So it can not be defined on a non-UART PIN

**Comment by Nutz95** [comment]
I could make it work with my MKS using #define SERIAL_PORT_2 -1.
I'm connected on the AUX 1 output of my ramps board.

**Comment by tcm0116** [comment]
`SERIAL_PORT_2` currently does not work with the AVR processors. What control board are you using?

**Comment by kevintong116** [comment]
@Nutz95 Yes, I know AUX 1 would work, even when I set SERIAL_PORT_2 to 3
But as I want to control my printer using octoprint, I would need to connect my screen using other serial

@tcm0116 I'm using mks gen 1.4.

**Comment by thinkyhead** [comment]
Likely `SERIAL_PORT_2` will be back-ported to AVR "pretty soon."

**Comment by boelle** [comment]
@thinkyhead should this not have the feature request label?

**Comment by boelle** [comment]
missing label

**Comment by InsanityAutomation** [comment]
AVR hal does have code for serial 2, so i believe this is completed and can be closed.
