### ISSUE TITLE
[2.0.x] Compile Error   Teensy 3.6

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#9385]
### Compile Error
In Teensy 3.6, a compile error occurs in the latest Marlin 2.0.x.

Windows10 Pro
Arduino 1.8.5
Teensyduino 1.41

### Error information
`'_BV' was not declared in this scope`

When I changed two places, it caused no compile error.

**/src/core/macros.h : 99**
`#define _BV(b) (1<<(b))`
↓
`#define _BV(n) (1<<(n))`

**/src/HAL/HAL_TEENSY35_36/HAL_Teensy.h : 34**
`#undef _BV`
↓
`#define _BV(n) (1<<(n))`

**Comment by ghost** [comment]
Correction:
/src/HAL/HAL_TEENSY35_36/HAL_Teensy.h: 34
It is enough to delete  `#undef _BV
`

**Comment by thinkyhead** [comment]
Seems to be corrected in the latest code.

**Comment by TadyTheFish** [comment]
what board have you selected?
