### ISSUE TITLE
Clone BL-TOUCH doesn't work correct

### ISSUE THREAD

**Issue by maks2018** [MarlinFirmware/Marlin#9389]
Hello, I have a clone of BLTouch and RAMPS 1.4 (MKS BASE 1.5)
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1674756/Marlin.zip)
 at delta printer. 

When I run auto calibration (G29 or G33), printer starts to do it at the height of  Z236.5, but there is #define DELTA_HEIGHT 284.00 in the configuration.

M119 will report TRIGGERED when the clone is deployed, and OPEN when it is stowed.

Please, help me with the configuration.

```
M43 S
READ: Servo probe test
READ: .  using index:  0
READ: .  deploy angle: 10
READ: .  stow angle:   90
READ: . probe uses Z_MIN pin: 18
READ: . uses Z_MIN_ENDSTOP_INVERTING (ignores Z_MIN_PROBE_ENDSTOP_INVERTING)
READ: . Z_MIN_ENDSTOP_INVERTING: false
READ: . deploy & stow 4 times

READ: WARNING - INVERTING setting probably backwards
READ: BLTouch clone detected
READ: .  DEPLOYED state: HIGH (logic 1)
READ: .  STOWED (triggered) state: LOW (logic 0)
READ: ERROR: BLTOUCH enabled - set this device up as a Z Servo Probe with inverting as true.
```

**Comment by GMagician** [comment]
Usually bltouch should always return open because triggered is just for 5ms (impossible to read)..

Try reading #9320 if there is something useful

**Comment by ExtremeSitting** [comment]
I don't know much about this application with the BLtouch let alone a clone, but have you tried commenting out the BLtouch definition? Based on the original way you had to get these things working, the servo definition and the BLtouch definition are redundant (and possibly conflicting) in this situation. I could be totally wrong here, but it seems like it would be worth a try.

**Comment by Bob-the-Kuhn** [comment]
The setup for a clone is different than for a BLTouch.

If I remember correctly the clone configuration is:
```
#define Z_ENDSTOP_SERVO_NR 0   // Defaults to SERVO 0 connector.
#define Z_SERVO_ANGLES {10,90}  // Z Servo Deploy and Stow angles
//#define BLTOUCH
#define SERVO_DELAY { 750, 0, 0, 0 }
```

**Comment by thinkyhead** [comment]
Closing in 1… 2…

**Comment by boelle** [comment]
@thinkyhead what number have you reached ? :-P :-D

**Comment by boelle** [comment]
@maks2018 Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
