### ISSUE TITLE
auto resume print off

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#9404]
Hello

on my creality 3d cr-10s original I could after a power failure make a resumption of printing in court

with marlin 1.1.8 update to enable BLtouch this option is no longer available

how to put it in place auto resume print off

**Comment by houseofbugs** [comment]
You can't. Creality never released the source code. Please contact them and demand it.

**Comment by thinkyhead** [comment]
> You can't. Creality never released the source code. Please contact them and demand it.

Agreed!

We plan to incorporate this feature after the rollout of Marlin 2.0, but even at that time you'll need to know how to talk to the specific hardware they're using to detect the power loss.
