### ISSUE TITLE
Z Probe to Z_MAX pin

### ISSUE THREAD

**Issue by jamesbit** [MarlinFirmware/Marlin#9409]
Hi !

I need to connect my proximity inductive sensor to Z_MAX pin.

I use in Configuration.h :

#define Z_MIN_PROBE_ENDSTOP 

and I get :

#error "Z_MIN_PROBE_ENDSTOP requires the Z_MIN_PROBE_PIN to be defined."

Can anyone help me ?

**Comment by cjsoong** [comment]
@jamesbit  
Try this...
```cpp
// #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define Z_MIN_PROBE_ENDSTOP   Z_MAX_PIN
```

**Comment by jamesbit** [comment]
I tried but I get : 
error "You must enable either Z_MIN_PROBE_ENDSTOP or Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN to use a probe."

**Comment by revilor** [comment]
The comment in Configuration.h claims that "By default Marlin assumes the Z-Max endstop pin." As SanityCheck tells us this is not correct, you have to define the pin to use. Therefore
```cpp
#define Z_MIN_PROBE_ENDSTOP
#define Z_MIN_PROBE_PIN <Z_MAX_PIN>
```
should do the trick. Replace <Z_MAX_PIN> by whatever pin the z-max endstop uses on your printer board (19 for RAMPS).

**Comment by jamesbit** [comment]
Thank you revilor !
I have no error.
I will try it in the next days...
