### ISSUE TITLE
cura connection USB

### ISSUE THREAD

**Issue by boubouexpress** [MarlinFirmware/Marlin#9410]
Marlin  bugfix-1.1.x

unable to connect to CURA via USB

repetier host and simplifyt3d connection usb ok

**Comment by Sebastianv650** [comment]
Why do you think it's a Marlin issue when you can connect with repetier and simplify?

**Comment by boubouexpress** [comment]
simply when I put back the original firmware it connects

**Comment by cjsoong** [comment]
@boubouexpress 
check CURA com port & Baud rate  (normal is AUTO)
Maybe you have set to fixed com port & Baud Rate?

**Comment by boubouexpress** [comment]
in cura 3.1.0 I can not find the setting

**Comment by psavva** [comment]
Have a look at this same issue reported to Cura
https://github.com/Ultimaker/Cura/issues/2957

**Comment by GMagician** [comment]
I just connected this evening Cura 3.1.0 to my printer. And it worked (N.B. COM & baud are set and not AUTO)

**Comment by boubouexpress** [comment]
I edit in marlin the BAUDRATE in 250000
with CURA 3.1 still the problem of usb connection but with CURA 3.2 beta I connect
