### ISSUE TITLE
[Question] Limits on retract acceleration

### ISSUE THREAD

**Issue by GMagician** [MarlinFirmware/Marlin#9428]
Not sure about what I read on code but it seems that retract acceleration is not limited. Value on configuration are used directly...correct or is my oversight?

**Comment by Sebastianv650** [comment]
You mean retract acceleration is not checked against E axis max. acceleration? True, but as retract acceleration is only applicable to E, it makes no real sense to check that. In my oppinion we shouldn't spend cycles during runtime checking for user faults.

**Comment by GMagician** [comment]
ok but `DEFAULT_MAX_ACCELERATION` has values also for E then I expected a check against this limit.

**Comment by Sebastianv650** [comment]
This limit is checked for non retract (print and travel) moves. A check at compile time (retract accel <= DEFAULT_MAX_ACCELERATION of E axis) would cost nothing, but it would be also quite worthless as it can be changed anytime after compilation on LCD or gcode.

**Comment by GMagician** [comment]
ok thanks for quick response
