### ISSUE TITLE
Error  #define DEBUG_LEVELING_FEATURE is enabled

### ISSUE THREAD

**Issue by andylh** [MarlinFirmware/Marlin#9429]
------------------------------------------------------------
### Compile Error in version 2.0a bugfix
When compiled with #define DEBUG_LEVELING_FEATURE in configuration.h get an error:

Arduino undefined reference 'ftostr43sign(float const&, char)'

Everything compiles fine is this #define is not enabled.

**Comment by GMagician** [comment]
I tried my version and it compiles with no errors

**Comment by GMagician** [comment]
but compiled with platformIO

**Comment by paukstelis** [comment]
I have the same issue. Tried compiling with arduino 1.8.2 and 1.8.5. I noticed the same thing with bugfix 1.1.8
EDIT: This only occurs when an LCD is not defined.

**Comment by GMagician** [comment]
Maybe attaching configuration may help. Only enabling DEBUG_LEVELING_FEATURE will compile correctly

**Comment by thinkyhead** [comment]
Patched.

**Comment by jackbradach** [comment]
It looks like this same issue occurs with the head of the 2.0 bugfix branch.  There needs to be an || ENABLED(DEBUG_LEVELING_FEATURE) added at utility.cpp:51.  Should I open a new bug?

**Comment by thinkyhead** [comment]
Thanks! It's now patched.
