### ISSUE TITLE
Merlin Problems

### ISSUE THREAD

**Issue by Leonnsiae** [MarlinFirmware/Marlin#9432]
I can't for the life of me get firmware uploaded. I've managed to get one uploaded but I don't think it's working. My LCD lights up and shows the regular printer setting screen then says "Killed. Printer Halted"
I've tried so many different configs. I can't seem to get it right. Can anyone help me out? I'm trying to set up RAMPS 1.4 with Arduino Mega 2560 for a Wanhao Duplicator i3 V2

**Comment by Bob-the-Kuhn** [comment]
Please ZIP up your Configuration.h and Configuration_adv.h files and attach to your reply.  

We'll need these files to try to reproduce the problem.

**Comment by Leonnsiae** [comment]
[Wanhao-I3-Plus-master.zip](https://github.com/MarlinFirmware/Marlin/files/1687720/Wanhao-I3-Plus-master.zip)
[Monoprice_1_1_6.zip](https://github.com/MarlinFirmware/Marlin/files/1687721/Monoprice_1_1_6.zip)
Here are two that I have that I can't for the life of me get to work. The monoprice one I kind of can but I don't think it's fully setup for the i3 v2. I'm also having the problem of when it's loaded on and I disconnect it from the PC and start the printer the LCD doesn't turn on .

**Comment by Leonnsiae** [comment]
OKay. I got the second zip (Monoprice) uploaded and my screen is working when I start up my printer. I'm not sure if everything is right because it just blinks to the Marlin startup screen on and off.

**Comment by thinkyhead** [comment]
Apologies, but we can't reasonably support 3rd-party forks of Marlin based on older releases. We suggest you contact your vendor.

You may also try uploading Marlin 1.1.8 or the current `bugfix-1.1.x` which includes configurations for the Wanhao Duplicator 6. (Is that your machine? The 'Monoprice' firmware you uploaded seems to think so.) At that point we can assist.

**Comment by thinkyhead** [comment]
I see that the usual Wanhao Duplicator 6 config uses MOTHERBOARD `BOARD_ULTIMAIN_2` but in your configuration it's set to `BOARD_RAMPS_14_EFB`. Again, if what you have is a Duplicator 6 then you may want to try the latest Marlin.
