### ISSUE TITLE
incorrect z movement after ABL enabled

### ISSUE THREAD

**Issue by jackhuntingtonliu** [MarlinFirmware/Marlin#9436]
Hi 

I have a Delta printer. I am using Marlin 1.1 firmware. This is my problem.

when I set up ABL with bilinear mode and save the mesh to the EEPROM, the ABL will not enable even if I run the M420 S1.
However, If I set my ABL in 3 Points mode or linear mode. The Z axis will adjust it height, only before or after X-Y move to the new position. 
I don't know what information I should post in order to solve this problem. So if you are interesting in solve this problem and need more information. Please tell me. if you have same problem, please share it with me.  Thank you

**Comment by jackhuntingtonliu** [comment]
Hi 

I have a Delta printer. I am using Marlin 1.1 firmware. This is my problem.

when I set up ABL with bilinear mode and save the mesh to the EEPROM, the ABL will not enable even if I run the M420 S1.
However, If I set my ABL in 3 Points mode or linear mode. The Z axis will adjust it height, only before or after X-Y move to the new position. 
I don't know what information I should post in order to solve this problem. So if you are interesting in solve this problem and need more information. Please tell me. if you have same problem, please share it with me.  Thank you

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by boelle** [comment]
@jackhuntingtonliu Please test with the latest `bugfix-2.0.x`

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
