### ISSUE TITLE
Setting Z-Offset in LCD (control > motion > z-offset)

### ISSUE THREAD

**Issue by Nordphilz** [MarlinFirmware/Marlin#9438]
Yesterday I flashed Marlin 1.1.8 to my printer. Until yesterday I only used Skynet, where I could define my Z-Offset at the printer (without re-flashing) in Control -> Motion -> Z-Offset.

In Marlin I can't find this option. Can you tell me how to activate that menu?

I already checked this thread https://github.com/MarlinFirmware/Marlin/issues/6103, but unfortunately it didn't really help me. Changing my config to FIX_MOUNTED_PROBE gave me serveral new errors. 

Thanks

**Comment by cjsoong** [comment]
@Nordphilz 
Try this modified version

[Marlin-1.1.8_Z_offset.zip](https://github.com/MarlinFirmware/Marlin/files/1691950/Marlin-1.1.8_Z_offset.zip)

**Comment by insanity67** [comment]
Will this come back to the official version?

**Comment by Nordphilz** [comment]
Thank you very much.
