### ISSUE TITLE
BIBO Touch Laser X Configuration not available in example_configurations

### ISSUE THREAD

**Issue by shaktee** [MarlinFirmware/Marlin#9443]
### Feature Request

[FR] I have configuration files for BIBO Touch Laser X 3D printer based on Marlin. I would like to contribute that to the example_configurations.

Attached is a patch.

[BIBO.patch.txt](https://github.com/MarlinFirmware/Marlin/files/1690508/BIBO.patch.txt)

**Comment by shaktee** [comment]
Patch attached
[BIBO.patch.txt](https://github.com/MarlinFirmware/Marlin/files/1690412/BIBO.patch.txt)

**Comment by shaktee** [comment]
I apologize. I realized the custom machine name in the previous patch was a bit too custom! Please find updated patch here

[BIBO.patch.txt](https://github.com/MarlinFirmware/Marlin/files/1690417/BIBO.patch.txt)

**Comment by GMagician** [comment]
This configuration has been added (#9467 and #9469).
I think issue can be closed

**Comment by shaktee** [comment]
Thank you!
