### ISSUE TITLE
Anet A8 pins in Marlin

### ISSUE THREAD

**Issue by stumichaels** [MarlinFirmware/Marlin#9444]
------------------------------------------------------------
### Question about the pins defined by pins_ANET_10.h in Marlin 1.1.8.

I recently installed Marlin 1.1.8 on my Anet A8 and it's working just fine.  However, I'm curious about the pins.  The pins defined in pins_ANET_10.h do not match the pins in the board schematic.  Comparing the actual board to the schematic shows that the schematic is correct.  The pins in pins_ANET_10.h must also be correct as Marlin works with no problems.  Therefore, there must be a translation table from the  definitions in pins_ANET_10.h and the actual pins of the board but I can't find the such a table.  Help!

**Comment by melvinisken** [comment]
Which pins do you mean exactly?

**Comment by stumichaels** [comment]
Actually most pins.  I'll give an example: the SERVO0   pin is defined as 27.  Pin 27 on the ATMEGA1284P is AVCC.  Another example is the X_STOP_PIN which is defined as 18 but 18 is GND; the actual x-stop pin is 21.

**Comment by melvinisken** [comment]
Be aware that the Arduino pin numbering is different than the chip pin numbering. For example, ground pins don’t have any number. Google for 1284p Arduino pinout. Or did you consider this already?

**Comment by stumichaels** [comment]
I had assumed that the Arduino and chip pin numbering was the same.  That's why I was confused by the lack of correspondence.  It quickly became obvious that the numbering wasn't the same.  So, there must be a document or table that relates the two.  My question is what is the name of the file that contains said document or table and where can I find it and is it easy to read?

**Comment by melvinisken** [comment]
It depends a little on the library (or better: hardware definition) you use. The ATmega1284p is not officially supported as far as I know, so you need to install those (you did, if you were able to compile). I guess it was Sanguino. But anyhow, there is a hardware folder within the Arduino package, where you can find pins_arduino.h files for all supported controllers. The location depends on your OS. It shuold be a 10 second google to find out yours. Here's what my 5 second googling revealed:
![atmega1284-pintout](https://user-images.githubusercontent.com/10966010/35770240-ecd5bd5c-0917-11e8-9ac7-02653e30b3bc.png)

**Comment by stumichaels** [comment]
I found a similar display for the ATMEGA1284P in the 44 pin package.  So, the definitions are in pins_Arduino.h for your particular implementation.  I have my answer.  Thanks.  Now, the trick is understanding pins_Arduino.h.

**Comment by melvinisken** [comment]
Ok, fine. That's up to you then. You can ask at the Arduino forums in that case. I guess you can get better support there regarding Arduino stuff. I suggest to close this issue.

**Comment by stumichaels** [comment]
Agreed, close the issue.  Thanks for your help.

**Comment by melvinisken** [comment]
Just a note: you need to close it, since you opened it. Thanks.
