### ISSUE TITLE
PID autotune Heating Failed

### ISSUE THREAD

**Issue by Zacharandir** [MarlinFirmware/Marlin#9447]
### Bug Report
- Description: When using M303 to tune PID values I get a Thermal Runaway error.

- Expected behaviour: Sending M303 to the printer runs the tuning routine and returns new PID constants
- Actual behaviour: The printer halts with a thermal runaway error partway through the first cycle.
- Steps to reproduce:
  - Send M503
  - Wait.
  - Printer stops due to thermal runaway

This first started happening after i updated my firmware to a recent bugfix version. When I reverted to version 1.1.5 I had no issues, even though they have the same settings as far as i can tell. This issue has been observed on multiple machines after updating from Version 1.1.5 to bugfix1.1.x

Thank you for your help.

[Bugfix1.1.x..zip](https://github.com/MarlinFirmware/Marlin/files/1691102/Bugfix1.1.x.zip)
[Version 1.1.5.zip](https://github.com/MarlinFirmware/Marlin/files/1691103/Version.1.1.5.zip)

**Comment by cjsoong** [comment]
@Zacharandir 
Try run M303 E0 S200 C8

**Comment by Zacharandir** [comment]
Same outcome, this time it said heating failed

**Comment by GMagician** [comment]
Maybe first things should be configure the machine in the same way (if you want same behaviours):
  WATCH_TEMP_INCREASE, MAX_BED_POWER are different (and may be related to your issue)

**Comment by Zacharandir** [comment]
I changed those parameters and it still failed.  what seems to be happening is that after a few cycles the heater stops turning back on, I can hear the fan speed on my power supply change when the extruder turns on and off  and it never turns back on after the last temperature dip be for the thermal runaway error. 

Here is a graph of the temperature after  sending the command M303 E0 S200 C8. Thermal runaway occurs at the end of the graph:
![pid_tune_fail](https://user-images.githubusercontent.com/33377365/35769311-ba5664c4-08ce-11e8-80f0-9d9732a21144.PNG)

Here is another graph after preheating, preheating starts at 42:15 and M303 E0 S220 C8 was sent at 44:00.
![pid_tune_fail](https://user-images.githubusercontent.com/33377365/35769407-e9ea5a14-08cf-11e8-82e5-ada6785efe58.PNG)

**Comment by GMagician** [comment]
Sure are you using bugfix 1.1.x? because 1.1.8 has a bug on pid autotune, fixed in bugfix branch

**Comment by Zacharandir** [comment]
That might be it I downloaded my copy mid-January, i'll see if it's fixed.

**Comment by GMagician** [comment]
Fix done 14 days ago #9265

**Comment by Zacharandir** [comment]
The latest version fixed it! thanks for the tip.
