### ISSUE TITLE
[FR]  Output z-offset at XY extrapolated from 3-point plane

### ISSUE THREAD

**Issue by bcsteeve** [MarlinFirmware/Marlin#9463]
### Feature Request

Given all the magic that goes on with ABL, I hope this is a breeze to implement.

What I'd like to see is the ability to know how much I should adjust my leveling screws to achieve coplanar between the bed and the print plane.  If I could probe at the screw points, this would be easy (using G30), but my machine can't get the probe to all four screws.  So what I was hoping is that I could do the 3 point measurement to get the plane (or maybe linear or bilinear works too?) and extrapolate that out to an arbitrary X,Y position (ie. where the screws are) and get a z-value spit out.  

I don't know how useful this would be to the average user, so don't put too much effort into it.   I thought that 99% of the work is already done and its just a matter of plugging in my XY into an equation you've already worked out and spitting out Z.

**Comment by thinkyhead** [comment]
That's how "3-point" and "Linear" leveling both work. They define a plane and tilt the entire print to that plane. The "Bilinear" leveling method includes the sub-option `EXTRAPOLATE_BEYOND_GRID` which causes Marlin to extrapolate bed tilt based on nearby grid measurements. (Ordinarily it retains the height of the closest edge.)
