### ISSUE TITLE
Sensorless homing with TMC 2130 not working when homing all axes at once

### ISSUE THREAD

**Issue by Tamonir** [MarlinFirmware/Marlin#9471]
Hi
- Description:
I have some issues using sensorless homing feature of Fysetc 2130. SPI - resistor is soldered out, CF4 and CFG5 are properly soldered. When Homing via GCODE "G28 X", X homes successfully by sensorless homing and detects the end of the axis. Same for "G28 Y". However, if I say "G28" or "G28 XY", both axes are raming into the end without detecting anything.

- Expected behaviour:
Proper detection of sensorless X and Y endstops

- Actual behaviour:
"G28 X" and "G28 Y" working fine with sensorless homing but "G28 XY" and "G28" do not (ramming without detection)
- Steps to reproduce:
  - MKS Gen L 1.0
  - all axes TMC 2130 (so far properly working)
  - Marlin Tarantula (1.1.8 with quick setup from here ( https://github.com/JimBrown/MarlinTarantula )
  - My current config:
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1692639/Configuration.zip)

Thanks in advance

**Comment by lemmingDev** [comment]
//#define QUICK_HOME

make sure QUICK_HOME is disabled

**Comment by Tamonir** [comment]
Thanks a lot! I would never have found that one. Works perfect!

**Comment by thinkyhead** [comment]
See if adding this to the very end of `quick_home_xy` helps, and you may then be able to use `QUICK_HOME` again…
```cpp
    #if ENABLED(SENSORLESS_HOMING)
      safe_delay(500); // Short delay needed to settle
    #endif
```
