### ISSUE TITLE
[FR] Sensorless(tmc2130) homing on Deltas (and other bots that home to max on Z)

### ISSUE THREAD

**Issue by Hywelmartin** [MarlinFirmware/Marlin#9475]
Today there is only two axis that is configurable from within Marlin (X and Y). If not TMC_ADV is used.

in * Configuration_adv.h it looks like this under // @Section TMC2130, TMC2208
```cpp
//#define SENSORLESS_HOMING // TMC2130 only

#if ENABLED(SENSORLESS_HOMING)
#define X_HOMING_SENSITIVITY 8
#define Y_HOMING_SENSITIVITY 8
#endif
```
To safely implement this feature it could  be present ONLY on the preconfigured delta  files or checked during sanity check, that #define Z_HOME_DIR is -1(max)

In the future:
```cpp
#if ENABLED(SENSORLESS_HOMING)
#define X_HOMING_SENSITIVITY 8
#define Y_HOMING_SENSITIVITY 8
//#define Z_HOMING_SENSITIVITY 8 // WARNING Use only with deltas/ bots that home to max
#endif
```

**Comment by tcm0116** [comment]
I just got my Delta machine setup with TMC2130s, and this is on my list of things to work on.

**Comment by Hywelmartin** [comment]
Obviously, me too, so i can test

**Comment by dembach** [comment]
looking forward to that..... maybe more accurate than microswitches and  less cables ;-)

**Comment by tcm0116** [comment]
If you're running 2.0.x, I just submitted #9516 which adds Z axis sensorless homing and enabled it to work on delta machines. I was going to wait until I got some testing on it before making a 1.1.x version, but I can if needed.

**Comment by Hywelmartin** [comment]
I'm running 1.1.x(8) right now and don't have a 32 Bit board

**Comment by tcm0116** [comment]
You can run 2.0.x on your 8-bit board. You'll just need to get the current
beta version of Arduino to be able to compile.

**Comment by tcm0116** [comment]
I just pushed #9532, which are the changes applied to the bugfix-1.1.x branch.

**Comment by Hywelmartin** [comment]
I take a look at it during the weekend

**Comment by tcm0116** [comment]
It's been merged into the bugfix1.1.x and bugfix-2.0.x branches, so you can
just download whichever one you use and go from there.

**Comment by Hywelmartin** [comment]
I meant... I test it in the wild....

**Comment by Hywelmartin** [comment]
tested
it homed

but I do get reboot if I remove/ insert the sd-card
do G33 P1
xxx



There seems to be a lot of problems with the 1.1.8-bugfix
https://github.com/MarlinFirmware/Marlin/issues/9598
https://github.com/MarlinFirmware/Marlin/issues/9589
https://github.com/MarlinFirmware/Marlin/issues/9560

I'm experience all of those, so its hard to try out the new feature

I'm not sure that I am to so much help here..

shout if I can help
