### ISSUE TITLE
[2.0.x] MKS sbase digipots not taking any notice of the current values

### ISSUE THREAD

**Issue by adamd76** [MarlinFirmware/Marlin#9477]
------------------------------
### Bug Report
- Description: MKS sbase digipots not working
- Actual behaviour: 
When changing current values in configuration_adv.c this doesn't seem to have any effect on the drivers.
My extruder motor was getting very hot even though the current was set to 0.6A (same value I used in smoothie). I tried to lower the current but this wasn't making any difference.
I changed all current values to 0.1A to see if setting current was working at all:
#define DIGIPOT_I2C_MOTOR_CURRENTS { 0.1, 0.1, 0.1, 0.1, 0.1 } 
After that all motors were still pulling strong as though the drivers were still set to high current.
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1693087/configuration.zip)

**Comment by curly-paul** [comment]
Also having the same issue, unless I should be changing values somewhere else for Sbase ?
![27661874_10215385953348195_1158924811_n](https://user-images.githubusercontent.com/36135554/35780516-629630dc-09d4-11e8-8ff4-5f746b58f1b4.png)

**Comment by Spawn32** [comment]
This is the correct place to change the values, i know this used to work, haven't re compiled any new source for a while, but have moved to a Tronxy X5S corexy and will need to use the sbase on it (that little tinny thing they call a controller on the X5S is just funny, LOL) , so should be able to test this in a day or two...

**Comment by adamd76** [comment]
Spawn32 - I've just compiled from your fork with my configuration files and the digipots are working just fine in your version. It must be something broken in the new sources....
Thanks,
Adam

**Comment by Spawn32** [comment]
Ahh, ok :)
That fork is from the 25 Dec, a lot has been added and fixed since then, one of the dev's will probably look at this soon since this will have a impact on a lot of boards ...

@thinkyhead ? :)

Can't remember that anything was done / modified to the digipots...

**Comment by adamd76** [comment]
OK. I managed to track down the commit that brakes the digipots.
It's the commit from 24th Jan. Looks like there are some changes to mcp4451 digipot routine.
![captureg](https://user-images.githubusercontent.com/11603192/35829463-d67a4966-0aba-11e8-8b67-53cef51897f0.PNG)

https://github.com/MarlinFirmware/Marlin/commit/45cfb1642493017b1203e35753fc258579b4d055

Prior to this commit digipots seem to work fine.

**Comment by Spawn32** [comment]
Nice, should be easy'er for @thinkyhead to fix it then :)

**Comment by adamd76** [comment]
Would be nice if he could fix it. For the time being I just removed the change from that commit and I've got the latest build working just fine.

**Comment by Spawn32** [comment]
@tcm0116 
Anything you could have a look at ?
Probably affects all digipot boards, so it's more or less a major bug: /

**Comment by tcm0116** [comment]
I don't have a board with digipots, so I can't really look at it.

**Comment by Spawn32** [comment]
ah,, ok, to bad :)

**Comment by Spawn32** [comment]
just got my X5S corexy running with the Sbase board, can confirm that they get very hot, almost like they are running on full amp's...

**Comment by Spawn32** [comment]
@thinkyhead you should upgrade me so i can slapp labels on stuff, this one need a big red "BUG" on it, LOL

**Comment by thinkyhead** [comment]
@adamd76 — Which part of #8355 seems to be causing the breakage? I'm just casually scanning issues to close and resolve the easier ones at the moment, but would like to come back to this later today.

**Comment by adamd76** [comment]
@thinkyhead I don't know exactly which part of the code breaks it. All I know that when I removed the changes from that commit by replacing the files from the previous commit it all started working again.

**Comment by Spawn32** [comment]
Is this being looked at ?
I know that @tcm0116 doesn't have a digipot device, so it's not easy for him to test :/
For us with digipot devices it's pretty big, it's  like having a older stepper driver with a missing pot 😄 

Could it also mess up the board during a print so the watchdog is triggered ?
I cant finish any prints, not from USB and not from SD, totally random disconnects and board gets unresponsive / crashes ..

https://github.com/MarlinFirmware/Marlin/issues/9593

And if i compile without watchdog i get compile errors...

**Comment by thinkyhead** [comment]
Try changing this line in [`Marlin/src/HAL/HAL_LPC1768/Wire.cpp`](https://github.com/MarlinFirmware/Marlin/pull/8355/files#diff-4fe7b8b061f2be44e942e738f815fdc3R118):
```diff
-  transferMCfg.sl_addr7bit = txAddress >> 1; // not sure about the right shift
+  transferMCfg.sl_addr7bit = txAddress; // Right-justified 7-bit address
```
@tcm0116 — Would you agree that this will most likely fix the issue?

**Comment by As3uS** [comment]
Hi guys , i will try if i see amelioration, just with the motors noise i will know ^^ i give you a feedback if this fix solved the issue.
And thank all of you for your big work

Edit: Nope it always seems ignore the current's setting

**Comment by thinkyhead** [comment]
Ah, well here's the problem. The old `Wire.h` code was being conceited. It was all about digipots and specific to MKS SBASE. The following lines were removed from the class, which also removed all initialization of the digipots.
```diff
-extern "C" uint8_t digipot_mcp4451_start(uint8_t sla);
-extern "C" void digipot_mcp4451_init(void);
-extern "C" uint8_t digipot_mcp4451_send_byte(uint8_t data);
. . .
-void TwoWire::beginTransmission(uint8_t sla) { digipot_mcp4451_start(sla);}
-void TwoWire::begin(void) {digipot_mcp4451_init();}
-size_t TwoWire::write(uint8_t data) {return digipot_mcp4451_send_byte(data);}
```

**Comment by thinkyhead** [comment]
See if #9927 fixes the issue. It causes the generic digipots code to call the custom i2c functions supplied for the MCP4451 in place of the `Wire.h` methods, but only for MKS SBASE.

**Comment by thinkyhead** [comment]
@tcm0116 — Not sure who to ask, and I'll do more online research in the meantime, but…

Does it seem to you that the i2c code used by these digipots is specific only to the digipots and the bus(es) on the MKS SBASE board, or does it seem like it might generally apply to LPC and some other boards? I ask, because maybe for MKS SBASE the generic Wire class might not be needed — but then, it might be if a separate i2c bus is also desired.

**Comment by p3p** [comment]
There is nothing MKS SBASE specific, other than that the board comes with the digipots connected to that specific i2c channel, the generic Wire implementation should have been fixable, but I don't have any i2c devices, and I don't think @tcm0116 does either (which is why it was untested).

**Comment by thinkyhead** [comment]
Darn. Well, I'll soon recruit some MKS SBASE testers and do a debug session in my copious free time.

**Comment by As3uS** [comment]
i have compiled yesterday but i don't have the time to test, i will try tonight.

**Comment by adamd76** [comment]
I will try to test it tonight.

**Comment by curly-paul** [comment]
Can confirm latest build (from ~9:00am GMT) works regarding digipot current values.
Tested will all at 0.1 and now running with 'normal' values 
Thankyou

**Comment by As3uS** [comment]
Hi can't try, it seems have heating problem on the last build, printer can't stabilize the temperature brefore start print :'( but it seems okay for other

**Comment by thinkyhead** [comment]
> Can confirm latest build (from ~9:00am GMT) works regarding digipot current values.

I just knew it would work. Kudos to me! Meanwhile, still wondering why it doesn't work with the regular ol' I2C library. What is this strange voodoo?
