### ISSUE TITLE
[bugfix-1.1.x] G26_Mesh_Validation_Tool.cpp is missing some declarations

### ISSUE THREAD

**Issue by ikarisan** [MarlinFirmware/Marlin#9491]
Hi!

After updating to the latest bugfix version ( 4d2355cc9ea7379ef7563c86b1c89794aaf78358 ) I can no longer compile because there are two variable declarations missing!

1) N is not declared in line 733. My temporary workaround was to insert a `#define N 5` before line 733. But I don't know what N is for. :) 
2) "location" is not defined for the while statement of the do/while loop! It is first defined within the loop but "location" should be defined outside. My workaround was to add a "const mesh_index_pair location;" in front of the do/while loop.

Now I can compile again, but I won't try the G26 command. ;)

**Comment by thinkyhead** [comment]
Patched.
