### ISSUE TITLE
[FR] M851 new options

### ISSUE THREAD

**Issue by Alissonverd** [MarlinFirmware/Marlin#9496]
Hello.
I would like to ask for new options for the M851 command.
M851 U - up 0.01mm nozzle from bed.
M851 D - down 0.01mm nozzle from bed.
M851 S - save settings and load.
M851 C - cancel settings.

New M851 code:
[M851.txt](https://github.com/MarlinFirmware/Marlin/files/1696993/M851.txt)

**Comment by thinkyhead** [comment]
I don't think we would incorporate this change. But of course, keep it for your own use.

**Comment by boelle** [comment]
wrong label

**Comment by InsanityAutomation** [comment]
This overlaps with M290 and if configuration_adv is set to merge M851 and babystepping the functionality requested here exists. Id say close this one as its doable in a slightly different approach.
