### ISSUE TITLE
[Other] Customization of Marlin Firmware

### ISSUE THREAD

**Issue by unknown1312** [MarlinFirmware/Marlin#9521]
Hello together,

I am actually working with the Ramps 1.4 (Arduino Mega) and Marlin Firmware Version 1.1.6.

I have a custom printer that should melt aluminum filament through induction. Due to the inductive field around the filament, a thermocouple in combination with the MAX31855 amplifier does not work to monitor the temperature of the filament.

Now I want to use the D10 output of the Ramps 1.4 (Hotend Temperature) to send a signal every time when a G1 command including the E<> argument is executed in order to control the power to melt the aluminum with the help of this information. This could just be by driving the output with 24V for a specific duration.

My problem is that I'm not quite sure where to add my code and where to change the code of marlin without to cause errors.

**Comment by unknown1312** [comment]
nobody?

**Comment by revilor** [comment]
How about using the extruder step signal?

**Comment by unknown1312** [comment]
@revilor do you mean by directly using the physical connection from the stepper? That would cause that the heat source is always running, also only for extrude/rectract commands..

**Comment by Roxy-3D** [comment]
The top level G1 command is very small.   Just modify it to supply the extra information you want to a pin when the 'right' event happens.

**Comment by thinkyhead** [comment]
Roxy has the right idea. Add your code to `gcode_G0_G1` (or to `gcode_get_destination` which is used by all G-move commands).
