### ISSUE TITLE
[2.0.x] Anet A6 LCD (Solved)

### ISSUE THREAD

**Issue by JohnnyTheOne** [MarlinFirmware/Marlin#9536]
The LCD screen does not work properly in 2.0.x but in 1.1.x it does
![20180208_101526](https://user-images.githubusercontent.com/20972801/35972805-8f6a3548-0cd3-11e8-9f17-b153fa971f1e.jpg)
my printer is Anet A6 I use the same `Configuration.h` and `Configuration_adv.h` files for both versions

**Comment by AnHardt** [comment]
The picture is typical for a too fast timing caused by:
Not enough waits, (*)
too long cables, (dropping voltage and catching noise)
too low voltage, (slowing down the display)
...

(*)
```
// If you want you can define your own set of delays in Configuration.h
//#define ST7920_DELAY_1 DELAY_0_NOP
//#define ST7920_DELAY_2 DELAY_0_NOP
//#define ST7920_DELAY_3 DELAY_0_NOP
```

**Comment by JohnnyTheOne** [comment]
I've tried it and it does not work.
```cpp
#define ST7920_DELAY_1 DELAY_0_NOP
#define ST7920_DELAY_2 DELAY_0_NOP
#define ST7920_DELAY_3 DELAY_0_NOP
```
en
```cpp
#define ST7920_DELAY_1 DELAY_0_NOP
#define ST7920_DELAY_2 DELAY_2_NOP
#define ST7920_DELAY_3 DELAY_4_NOP
```
but why does it work for the same printer with Bugfix 1.1.x? there is no change in hardware

**Comment by JohnnyTheOne** [comment]
#9255 solved this problem.
Is there better way to fix instead modify 
```
//set optimization so ARDUINO optimizes this file
//#pragma GCC optimize (3)
```
in
`ultralcd_st7920_u8glib_rrd_AVR.cpp`

**Comment by thinkyhead** [comment]
Perhaps the whole file doesn't need optimization, but only part.
