### ISSUE TITLE
Z homing with a swinging-out servo arm

### ISSUE THREAD

**Issue by 3ntrlab** [MarlinFirmware/Marlin#954]
Hello All,
I am using a z homing switch mounted on a retractable arm.
Everything works quite well when G28 Z0 is issued, BUT the arm retracts as soon as the homing process is completed (dragging on printing surface... sometimes the arm gets stuck out for excessive friction).
Is there any way to raise a bit the extruders BEFORE arm retraction ?

Best Regards
Davide Ardizzoia

**Comment by boelle** [comment]
closing this one as the user just found a fix and never submitted a PR

**Comment by thinkyhead** [comment]
Yes, it's based on older code without all the latest fancy z lift options…
