### ISSUE TITLE
[bugfix-1.1.x] SD insertion or removal resets printer

### ISSUE THREAD

**Issue by lemmingDev** [MarlinFirmware/Marlin#9560]
### Bug Report
- Description: SD insertion or removal resets printer
- Expected behaviour: printer should not restart - 
- Actual behaviour: printer resets on SD insertion or removal
- Steps to reproduce:
  - Insert or remove an SD
  - Watch the printer restart

Have MKS Gen 1.4
I have TMC2130 setup through SPI
I have the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER enabled
1.1.8 firmware works fine
Bugfix from a week or two ago is ok

My current - non-working files [Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1713162/Marlin.zip)

Bugfix from today 10/02/18 causes printer to reset
I think it might have to do with changes to SPI stuff in Configuration_adv.h and pins_RAMPS.h

**Comment by cjsoong** [comment]
Marlin 2.0 2018-02-10 also have the same problem

Maybe this problem? 
"Size lcd_status_message based on language #9546"

**Comment by lemmingDev** [comment]
Yep - that was the problem

I reverted back ultralcd.cpp to just before that change was made and everything works fine.

**Comment by ImplementOfWar** [comment]
Can confirm this issue.

**Comment by thinkyhead** [comment]
- What is your `LCD_LANGUAGE` setting?
- Do you have `STATUS_MESSAGE_SCROLLING` enabled?

See if it helps to add this line:
```diff
inline void pad_message_string() {
  uint8_t i = 0, j = 0;
  char c;
+ lcd_status_message[MAX_MESSAGE_LENGTH] = '\0';
  while ((c = lcd_status_message[i]) && j < LCD_WIDTH) {
```
