### ISSUE TITLE
Probed Height Increments with repeated UBL G29 J (Mesh being double compensated?)

### ISSUE THREAD

**Issue by dagnall53** [MarlinFirmware/Marlin#9561]
### Bug Report 
I am using 1.1.8, recently downloaded, on a XL delta.

I believe that I have uncovered a bug in the way that G29 J operates. 

What I saw was a continual "creep" in the bed height measurement when using repeated UBL G29 J.
What I would have expected is that a "G28 G29 J" should result in consistent readings of my three points on the bed. Instead what I see is a consistent increment in the "read bed heights", when using a non zero mesh. 

As I understand it, the selected mesh is tilted and height compensated by the J probing, and then used for subsequent print operation. What I have noted is that G29 J will "double compensate" if the mesh is tilted and or offset. 

I would have anticipated that a tilted mesh , subsequently "J" probed, should remain substantially unchanged. 

However this is not the case. and it manifests as an increment in height with repeated G29 J probings. 
With a null mesh, there is no bed height shift, but with a real mesh, the bed height apparently increments with repeated G29 J even if preceded by a G28. 
To me it would appear that the G29 J compensation needs to look at the existing mesh tilt and offset before compensating for the " J probed" tilt and height offset.

 
I do wonder if this is similar to the reported height increasing issues, #9344 but it seems subtly different.  

Code below shows what happened during my tests.., but I suspect the real issue is that G29 J is "double compensating" for preexisting mesh tilts and average height offsets.  

```
>>> G29 T1
SENDING:G29 T1
Bed Topography Report for CSV:
NAN,NAN,NAN,NAN,NAN,NAN,NAN
NAN,NAN,NAN,NAN,NAN,NAN,NAN
NAN,NAN,NAN,NAN,NAN,NAN,NAN
NAN,NAN,NAN,NAN,NAN,NAN,NAN
NAN,NAN,NAN,NAN,NAN,NAN,NAN
NAN,NAN,NAN,NAN,NAN,NAN,NAN
NAN,NAN,NAN,NAN,NAN,NAN,NAN
>>> G29 J V4
SENDING:G29 J V4
Bed X: 67.175 Y: 67.175 Z: 0.062
Bed X: -91.763 Y: 24.588 Z: 0.248
Bed X: 24.588 Y: -91.763 Z: -0.033
bed plane normal = [0.0014348,-0.0009816,0.9999985]
rotation matrix:+0.999999 +0.000000 -0.001435
+0.000001 +1.000000 +0.000982
+0.001435 -0.000982 +0.999999
D constant: 0.0924826
>>> G29 J V4
SENDING:G29 J V4
Bed X: 67.175 Y: 67.175 Z: 0.054
Bed X: -91.763 Y: 24.588 Z: 0.236
Bed X: 24.588 Y: -91.763 Z: -0.045
bed plane normal = [0.0014151,-0.0010013,0.9999985]
rotation matrix:+0.999999 +0.000000 -0.001415
+0.000001 +1.000000 +0.001001
+0.001415 -0.001001 +0.999999
D constant: 0.0818259
>>> G29 J V4
SENDING:G29 J V4
Bed X: 67.175 Y: 67.175 Z: 0.082
Bed X: -91.763 Y: 24.588 Z: 0.266
Bed X: 24.588 Y: -91.763 Z: -0.009
bed plane normal = [0.0014141,-0.0009507,0.9999985]
rotation matrix:+0.999999 +0.000000 -0.001414
+0.000001 +1.000000 +0.000951
+0.001414 -0.000951 +0.999999
D constant: 0.1131551

Mesh loaded from slot 0
Done.
>>> G29 J V4
SENDING:G29 J V4
Bed X: 67.175 Y: 67.175 Z: 0.085
Bed X: -91.763 Y: 24.588 Z: 0.171
Bed X: 24.588 Y: -91.763 Z: -0.040
bed plane normal = [0.0001487,-0.0008442,0.9999998]
rotation matrix:+1.000000 +0.000000 -0.000149
+0.000000 +1.000000 +0.000844
+0.000149 -0.000844 +1.000000
D constant: 0.0387606
>>> G29 J V4
SENDING:G29 J V4
Bed X: 67.175 Y: 67.175 Z: 0.119
Bed X: -91.763 Y: 24.588 Z: 0.118
Bed X: 24.588 Y: -91.763 Z: 0.086
bed plane normal = [-0.0014577,0.0009124,0.9999985]
rotation matrix:+0.999999 +0.000000 +0.001458
+0.000001 +1.000000 -0.000912
-0.001458 +0.000912 +0.999999
D constant: 0.0822211
>>>    G28
SENDING:G28
>>> G29 J V4
SENDING:G29 J V4
Bed X: 67.175 Y: 67.175 Z: 0.530
Bed X: -91.763 Y: 24.588 Z: 0.508
Bed X: 24.588 Y: -91.763 Z: 0.368
bed plane normal = [-0.0003661,0.0017746,0.9999983]
rotation matrix:+1.000000 +0.000000 +0.000366
+0.000001 +0.999998 -0.001775
-0.000366 +0.001775 +0.999998
D constant: 0.6249018
>>>    G28
SENDING:G28
>>> G29 J V4
SENDING:G29 J V4
Bed X: 67.175 Y: 67.175 Z: 1.785
Bed X: -91.763 Y: 24.588 Z: 1.394
Bed X: 24.588 Y: -91.763 Z: 1.372
bed plane normal = [0.0010205,0.0053798,0.9999850]
rotation matrix:+1.000000 +0.000000 -0.001021
-0.000005 +0.999985 -0.005380
+0.001021 +0.005380 +0.999985
D constant: 2.2144265
```

-
Thanks
Dagnall

**Comment by dagnall53** [comment]
@thinkyhead @Roxy-3D  Sorry to poke you on this.
Have I misunderstood the purpose of UBL "G29 J". 
If done with no previous mesh, it does a nice 3 point level and height adjust. (as expected)
If done with a non zero mesh, it appears to try to correct the mesh, but because it is using the "new" 3 point probe depths (not taking into account previous mesh probes), it effectively double correctsheight and tilt offsets.

Given that any multi probed mesh is already trying to correct bed height, tilt ,concavity, surface , etc, It appears to me that a G29 J should be probing **using** the (current) mesh offsets. 
If the 3 probes then read the same as the multi probed mesh measurements at the probe points, then any tilt (etc) change will be zero. If there are "no" mesh offsets or the mesh is null, the result will still give a simple tilt and height corrected mesh. 

The reason this is important is that currently I (and others I assume) have to do a G29 P1 before prints, which can be tedious. Using  a G29 J to correct any minor tilt / height offset (but retaining the basic Multi probe bed "shape") is much faster. 

- Again ,sorry to poke you on this, but I got no comments from the issue as presented, so I presume it did not get noticed.

**Comment by Roxy-3D** [comment]
> Given that any multi probed mesh is already trying to correct bed height, tilt ,concavity, surface , etc, It appears to me that a G29 J should be probing using the (current) mesh offsets.

I agree...   I think the probing for G29 J should be using the mesh points to correct the probed values to be used to generate the mesh tilt.

**Comment by thinkyhead** [comment]
Closing since the discussion at #9622 is converging on the solution. Please continue there.
