### ISSUE TITLE
upgraded to Marlin 1.1 used with hictop MKS board dual extruder SD card no longer works

### ISSUE THREAD

**Issue by kpdelucia** [MarlinFirmware/Marlin#9567]
### Bug Report
- Description: --I upgraded to marlin 1.1 posted by gameofthefuture on thingiverse to use MKS board not ramps generic. It enable my second extrude head properly but now it doesnot see my sdcard in my repwrap discount smart controller-
- Expected behaviour: --The SD card reader worked previously-
- Actual behaviour: --sd card inserted message comes up   but when i navigate to print from SD " it says "NO SD CARD"-

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by boelle** [comment]
@kpdelucia Please test with the latest `bugfix-2.0.x`

**Comment by kpdelucia** [comment]
Ok i have had many problems using using newer versions of Arduino with that printer.  But I will give it a try this weekend. Using latest Arduino and latest Marlin

**Comment by boelle** [comment]
@kpdelucia what results did you get that weekend?

@thinkyhead i think we can close this one

**Comment by kpdelucia** [comment]
Sorry to hold you up I had to print a $$ job on that printer last weekend with a single extruder.  I will try this weekend but if you are really anxious to close this out, Don't wait for me. I will likely figure it out.

**Comment by boelle** [comment]
no no, we can wait a few more days :-D

**Comment by kpdelucia** [comment]
tried latest marlin but I am having a hard time setting steps per mm for each extruder.
```
  //#define DISTINCT_E_FACTORS                             //   *****************kirk look************

/**
 * Default Axis Steps Per Unit (steps/mm)
 * Override with M92
 *                                      X, Y, Z, E0 [, E1[, E2[, E3[, E4]]]]
 */
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 200, 200, 1200, 180 }    // z was 1159
```
If I put a number after the 180,  I get a compile error about too many arguments.  I suspect I have to uncomment the "define distinct" above it ...
update.  uncommented that line and now it compiles and uploads.  ...
after uploading I Insert the SD CARD and it doesn't even show up in the menus.  so that's where i am stuck

**Comment by boelle** [comment]
attach 2 config files as zip

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by kpdelucia** [comment]
Thanks @boelle I got it mostly working now but I don't want to discuss it in the wrong place so Thanks for showing me the bug was fixed for the sd card not found
