### ISSUE TITLE
printer halts after inserting sd card

### ISSUE THREAD

**Issue by mdhms** [MarlinFirmware/Marlin#9569]
- Description: Printer halts after putting in a sd card into RepRapDiscount Smart Controller with version 1.1.6 and 1.1.8
- Expected behaviour: initialize sd card
- Actual behaviour: Printer halts and i have to reset it. Error from S3D: 
Recv: sd card Error:KILL caused by KILL button/pin

- Steps to reproduce:
  - Insert SD card or start with sd card inside RAMPS RepRapDiscount Smart Controller

[configuration_h_files.zip](https://github.com/MarlinFirmware/Marlin/files/1713687/configuration_h_files.zip)

**Comment by ghost** [comment]
it's a bad pin configuration
Verify all pins attributions , ask your reseller , ask all that have the same printer here
You will gain time if you place here  the name of your printer , the board , and your pins config
Test all configurations template given 
You can begin by yourself , go on pin.h , may be , there is other bad attributions s 
Use google to know pins attribution of your board

**Comment by mdhms** [comment]
Thank you for your reply @studiodyne 
It's an Anet A8 with RAMPS 1.4 with [this](http://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller) display

[pins.zip](https://github.com/MarlinFirmware/Marlin/files/1713702/pins_RAMPS.zip)
