### ISSUE TITLE
Can't calibrate using commands M360-M364

### ISSUE THREAD

**Issue by aesazonov** [MarlinFirmware/Marlin#9578]
### Bug Report
- Description: After sending the file to arduino and issuing commands to go home, it goes correctly. After that, a command m114 shows it's coordinates. During calibration by using m360 and related, it only returns "ok" and doesn't move or anything at all.
- Expected behaviour: after the m360 is issued, printer's arm should go to a position (0,120)
- Actual behaviour: nothing happens.

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.
