### ISSUE TITLE
[2.0.x] SBASE serial disconnect, no digipot control, requires watchdog to compile

### ISSUE THREAD

**Issue by Spawn32** [MarlinFirmware/Marlin#9593]
Get random disconnects on the USB port, can be after a minute and even 2 hours, haven't been able to finish 1 print.

Only thing changed on my side is that i have changed from a I3 clone to a big corexy..

Also got Firmware unresponsive / stuck, a few times..

The Digipot current setup also dosent seem to be working, whatever you set them to they act exactly the same..   https://github.com/MarlinFirmware/Marlin/issues/9477

And yet another bug, tested to turn of the watchdog to see how it behaved, not possible, it throws a compile error without it...
```
.pioenvs/LPC1768/src/src/Marlin.o: In function `setup()':
C:\Users\Familien\Desktop\Mks Sbase X5S\Marlin-bugfix-2.0.x100218/Marlin\src/Marlin.cpp:693: undefined reference to `HAL_get_reset_source()'
C:\Users\Familien\Desktop\Mks Sbase X5S\Marlin-bugfix-2.0.x100218/Marlin\src/Marlin.cpp:699: undefined reference to `HAL_clear_reset_source()'
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\LPC1768\firmware.elf] Error 1
```
Ended up using a small AVR melzi board with Marlin 1.1.8 to get my prints done 😭 

My "The Borg" board is undergoing surgery and getting a stepper driver transplant, still waiting for a hot air nozzel, so cant test that one yet.

**Comment by Spawn32** [comment]
Just remembered, i got a warning that there was a new version of platformio so i updated, could that be the problem with the usb disconnects ?

**Comment by Spawn32** [comment]
Would be very nice if someone with a similar setup or even just a mks sbase, LPC1768 or a Re-Arm could try to verify this faults for me..

If i leave the board connected and just communicating (not printing) with simplify3d it dose not disconnect..

**Comment by briareos77** [comment]
I have 2 Re-Arm with ramps 1.4 on two of my core xy printers. I get random disconnects also from octoprint and just printing directly from SD card. After the disconnect, everything is frozen.

If i turn off linear advance, it prints all the way through. I have not been able to print a benchy all the way through with linear advance on. I'm not sure if it's related to linear advance, since the disconnects are kind of random.

@Spawn32 Do you have linear advance on also?

**Comment by Spawn32** [comment]
I had a very bad Y axes shift when i tested with linear advance enabled, but i found that linear advance wasn't the problem that made the shift happen, but have turn it off just to have one less variable until this get sorted, so my problem is not caused by linear advance.

No octoprint on this one, and like you say, totally frozen, reset doesen't do it, have to power down to fix it..

linear advance should / could make problems on slower MCU's like the AVR, but a fast 32bit should be ok...

I have a old (nov 2017) branch of 2.0 bug fix, and that dose not have the usb drops or the digipot problem, but not sure where to look, it's a lot of commits since November and until today  :)

**Comment by briareos77** [comment]
@Spawn32 Have you been able to isolate the commit that the printer started to freeze at?

I'm using a bltouch and tmc 2130 drivers. What do you have hooked up to your core xy printer?

**Comment by cdedwards** [comment]
did you ever get your random disconnects figured out? I'm running into the same situation with a delta and re-arm board. doesn't happen during a print, but randomly while doing other commands. G28, G29, G48 etc.

**Comment by boelle** [comment]
@Spawn32 still having issues with latest bugfix 2.0?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
