### ISSUE TITLE
probe pin D1 troubles the connection to host software (auto bed leveling)

### ISSUE THREAD

**Issue by Yalman** [MarlinFirmware/Marlin#9594]
If i use pin D1 for "Z_MIN_PROBE_PIN 1" then the connection to Pronterface is faulty. Its put a message likewise: write error.
If i reconnect the pin during controller power is on, i can send commands with Pronterface, but i cant receive the state of the Controller.
If i use pin D20 (Z_MIN_PROBE_PIN 20) instead D1 everything works fine.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1714419/Configuration.zip)

**Comment by thinkyhead** [comment]
It's probably because Pin 1 is the serial line.
