### ISSUE TITLE
[FR] Level Check First Layer

### ISSUE THREAD

**Issue by KupipiKuki** [MarlinFirmware/Marlin#9595]
There are a number of things that I am working on contributing on for newer releases, one that I would like to see and help on is a level check prior to first layer.  This would eliminate the need to check bed coating heights such as tape or build tak. On the first layer an option could be added to check the z offset from the stored leveling matrix.  This would eliminate failed prints by verifying that there is indeed material to print on at the nozzle height.

An extension of this could be to check various points of the model first layer but that would require significantly more coding.

**Comment by tcm0116** [comment]
Are you using a probe to home Z? If so, then any material on the bed will already be automatically accounted for when homing at the start of a print.

**Comment by KupipiKuki** [comment]
Ah, I think I have a configuration issue, I'll work on this, thanks for pointing it out.
