### ISSUE TITLE
[bugfix-1.1.x] The name of the printer and the "ready" message are not shown [Anet A8]

### ISSUE THREAD

**Issue by FreeLuck** [MarlinFirmware/Marlin#9598]
### Bug Report
- Description:  
With the Marlin version 1.1.8 it's ok, I decided to go to the bugfix 1.1.x for other bugs corrected later. But now with the bugfix the name of the printer and the "ready" message, with my Anet A8, are not displayed on the main screen.
Firmware loaded all default and same problem.

[Anet A8 default settings.zip](https://github.com/MarlinFirmware/Marlin/files/1714751/Anet.A8.default.settings.zip)

**Comment by DaveAhrendt** [comment]
Same issue on a FolgerTech 2020.

**Comment by sh4jonny** [comment]
confirm on 2.0.x branch

**Comment by GMagician** [comment]
I think this has been solved, try updated bugfix branches

**Comment by FreeLuck** [comment]
I now confirm with the bugfix 1.1.x the name is shown

Thanks

**Comment by Spoons** [comment]
Interesting, having this problem on my printer on the latest bugfix 1.1.x.
