### ISSUE TITLE
confused about the Z_PROBE options

### ISSUE THREAD

**Issue by xKoldx** [MarlinFirmware/Marlin#9613]
Sorry for posting this here, but there is no documentation about this.

With configuration.h it states that if you do not use the Z_MIN_PROBE_USES_Z_MIN_ENDSTOP and only use Z_MIN_PROBE_ENDSTOP
then Marlin will default to using the Z_MAX_PIN.

That's fine and dandy, but it also says "to use a custom z probe pin Set Z_MIN_PROBE_PIN below.
where do I set that in configuration.h?

or do I just define that under "genericboard_pins.h" ?

also, once defined under board_pins.h, because that's what I did and it seems to work,  do I define the Z_PROBE_PIN? like in the ultimaker_pins.h config? 
or do I define the Z_MAX_PIN? 

And when trying to invert the logic of the endstop, and /or use the endstop pullup, do I do that under Z_PROBE_PIN or under Z_MAX_PIN? or both? 

dosnt make a lot of sense.

please help! 

Also thank you! this marlin stuff is amazing!

**Comment by Bob-the-Kuhn** [comment]
Take a look at the [Marlin Firmware doc site](http://marlinfw.org/) for a better description of the options.

Most people use the Z_probe for both probing (bed leveling) and homing (endstop).  In this case tie the Z probe to the Z_MIN endstop and enable Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN.

When Z_MIN_PROBE_ENDSTOP is enabled, Marlin uses the Z_MIN_PROBE_PIN for the input.  If Z_MIN_PROBE_PIN isn't defined in your pins_YOUR_BOARD.h file then Marlin will use the Z_MAX input.

For Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN set the Z_MIN options.

For Z_MIN_PROBE_ENDSTOP always set the ZMIN_PROBE options.  I'm not sure if the Z_MAX options need to be set when using the Z_MAX input.
