### ISSUE TITLE
Nothing useful

### ISSUE THREAD

**Issue by bcsteeve** [MarlinFirmware/Marlin#9616]
Not a contribution

**Comment by houseofbugs** [comment]
Did you happen to have any butterflies fly by your window during the test?

**Comment by Roxy-3D** [comment]
First...   .004 mm of standard deviation is **_VERY_** good.    But different locations are going to have more or less 'slop' in the mechanics of the machine.    And if you add the 'S' option to M48 you will get a more realistic value than if you are simply making the probe go up and down.   'S' will shake the extruder around a little bit before each probe.   So any backlash and looseness in the mechanisms should be exposed.

**Comment by bcsteeve** [comment]
I think you both may be missing my point.  The numbers don't matter absolutely, I'm talking about the relative difference from one set to another.  It doesn't seem likely (or even possible) to me that a butterfly flying by my window only affects the result between tests, but not within a test.  My tests - as you can see - are very good...  but 10x less good from one to the other.  The whole point of a sensor test spitting out standard deviation is to determine the repeatability of that sensor.  So while I understand the S parameter for gauging the SYSTEM's function... for the SENSOR (and that's what M48 says), it is introducing a variable for no reason.  It makes the test LESS reliable, not more (again, from the perspective of the sensor on its own, and not the system as a whole).  Regardless, that is moot because it still has nothing to do with the drift between tests.

Let me put this another way.  If I run with a P100 (I don't think that's possible due to resources, but let's just pretend) the result should even out enough that it should be identical to two subsequent P50's run quickly one after another  But that's not what's happening.   I do a set and then another set and each set is individually spot on, yet compared to each other there's a significant difference.

I get sensor drift.  And that's exactly why I started down this M48 path.  I was getting weird results from M29 and M30 so I wanted to see if it was my sensor causing the problem. But what I'm seeing and reporting SHOULD be impossible, and I'm wondering if there's some variable that's not clearing and introducing some cumulative error artificially?

**Comment by Roxy-3D** [comment]
> I think you both may be missing my point.

I said:

> But different locations are going to have more or less 'slop' in the mechanics of the machine. And if you add the 'S' option to M48 you will get a more realistic value than if you are simply making the probe go up and down. 'S' will shake the extruder around a little bit before each probe. So any backlash and looseness in the mechanisms should be exposed.

DID YOU EVEN TRY THE 'S' OPTION on M48?

**Comment by bcsteeve** [comment]
I've seen from your other posts that you have a particular disdain for people that you assume don't try things you suggest :)

Yes, as a regular matter of course I always use S2.  It was irrelevant to the point though.  And **for this particular exercise**, as I said, it introduces variables when the whole point here is to limit them.   But for the record, when I did it with S2 my numbers were (predictably) slightly worse than what I reported above, yet still out of whack from one test to the next.  For completeness, I also removed the glass bed because I get more consistent results directly on the aluminum.  That's not "real world" but again, the point is to eliminate variables and focus on the sensor.  Having things shake around, etc, may simulate real world... but that's not the point.  The test ITSELF needs to be reliable, and I think I've introduced evidence to suggest it may not be.

**Comment by bcsteeve** [comment]
Really?  wow.

**Comment by AnHardt** [comment]
What is your Z's steps/mm?
Don't trust any result better than that. +-1 is always possible.
If Z is in the mid of two steps you may get a super result. 
If right at the border even the best probe will show one time the one and one time the other result.

I don't see factor 10, is see a bit more than 3.

**Comment by bcsteeve** [comment]
I have to correct myself (and ask @Roxy-3D what you meant).

I did *not* try any "S" flag for M28.  I got confused (and you did?).  From the documentation, there is no S flag.  I thought you meant L and that's what I was answering.  Please confirm or clarify.

**Comment by bcsteeve** [comment]
@AnHardt 
Z steps/mm is 400.  What is that... 0.0025mm, right?  When I say factor of 10, I mean a typical difference I'm seeing from one average test result to the next is about 10 times that of the intra-test standard deviation.  Let's look at the data I originally posted (which i just a micro sample of all the tests I've been doing).   Std Dev's of 0.001 and 0.004, yet the average of the first test was 1.74 and the second was 1.69, or a difference of .05... or between 12.5x and 50x the Std Dev's.  So 10x was hardly an exaggeration.

Again, the actual figures don't really matter.  The point remains... VERY tight tolerances when performing an M48, yet wildly (relatively speaking) different results from one test to the next with no changes and only seconds apart.  To be clear, that's with NO physical contact with the machine (everything remote).

**Comment by AnHardt** [comment]
@bcsteeve 
I'd have more trust in the author of that function than in documentation.

There is always one definitive source

<details><summary>*THE Source*</summary>

```cpp
/**
 * M48: Z probe repeatability measurement function.
 *
 * Usage:
 *   M48 <P#> <X#> <Y#> <V#> <E> <L#>
 *     P = Number of sampled points (4-50, default 10)
 *     X = Sample X position
 *     Y = Sample Y position
 *     V = Verbose level (0-4, default=1)
 *     E = Engage Z probe for each reading
 *     L = Number of legs of movement before probe
 *     S = Schizoid (Or Star if you prefer)
 *
 * This function requires the machine to be homed before invocation.
 */
void GcodeSuite::M48() {

  if (axis_unhomed_error()) return;

  const int8_t verbose_level = parser.byteval('V', 1);
  if (!WITHIN(verbose_level, 0, 4)) {
    SERIAL_PROTOCOLLNPGM("?(V)erbose level is implausible (0-4).");
    return;
  }

  if (verbose_level > 0)
    SERIAL_PROTOCOLLNPGM("M48 Z-Probe Repeatability Test");

  const int8_t n_samples = parser.byteval('P', 10);
  if (!WITHIN(n_samples, 4, 50)) {
    SERIAL_PROTOCOLLNPGM("?Sample size not plausible (4-50).");
    return;
  }

  const bool stow_probe_after_each = parser.boolval('E');

  float X_current = current_position[X_AXIS],
        Y_current = current_position[Y_AXIS];

  const float X_probe_location = parser.linearval('X', X_current + X_PROBE_OFFSET_FROM_EXTRUDER),
              Y_probe_location = parser.linearval('Y', Y_current + Y_PROBE_OFFSET_FROM_EXTRUDER);

  #if DISABLED(DELTA)
    if (!WITHIN(X_probe_location, MIN_PROBE_X, MAX_PROBE_X)) {
      out_of_range_error(PSTR("X"));
      return;
    }
    if (!WITHIN(Y_probe_location, MIN_PROBE_Y, MAX_PROBE_Y)) {
      out_of_range_error(PSTR("Y"));
      return;
    }
  #else
    if (!position_is_reachable_by_probe(X_probe_location, Y_probe_location)) {
      SERIAL_PROTOCOLLNPGM("? (X,Y) location outside of probeable radius.");
      return;
    }
  #endif

  bool seen_L = parser.seen('L');
  uint8_t n_legs = seen_L ? parser.value_byte() : 0;
  if (n_legs > 15) {
    SERIAL_PROTOCOLLNPGM("?Number of legs in movement not plausible (0-15).");
    return;
  }
  if (n_legs == 1) n_legs = 2;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  const bool schizoid_flag = parser.boolval('S');
  if (schizoid_flag && !seen_L) n_legs = 7;
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  /**
   * Now get everything to the specified probe point So we can safely do a
   * probe to get us close to the bed.  If the Z-Axis is far from the bed,
   * we don't want to use that as a starting point for each probe.
   */
  if (verbose_level > 2)
    SERIAL_PROTOCOLLNPGM("Positioning the probe...");

  // Disable bed level correction in M48 because we want the raw data when we probe

  #if HAS_LEVELING
    const bool was_enabled = planner.leveling_active;
    set_bed_leveling_enabled(false);
  #endif

  setup_for_endstop_or_probe_move();

  double mean = 0.0, sigma = 0.0, min = 99999.9, max = -99999.9, sample_set[n_samples];

  // Move to the first point, deploy, and probe
  const float t = probe_pt(X_probe_location, Y_probe_location, stow_probe_after_each, verbose_level);
  bool probing_good = !isnan(t);

  if (probing_good) {
    randomSeed(millis());

    for (uint8_t n = 0; n < n_samples; n++) {
      if (n_legs) {
        const int dir = (random(0, 10) > 5.0) ? -1 : 1;  // clockwise or counter clockwise
        float angle = random(0, 360);
        const float radius = random(
          #if ENABLED(DELTA)
            (int) (0.1250000000 * (DELTA_PROBEABLE_RADIUS)),
            (int) (0.3333333333 * (DELTA_PROBEABLE_RADIUS))
          #else
            (int) 5.0, (int) (0.125 * min(X_BED_SIZE, Y_BED_SIZE))
          #endif
        );

        if (verbose_level > 3) {
          SERIAL_ECHOPAIR("Starting radius: ", radius);
          SERIAL_ECHOPAIR("   angle: ", angle);
          SERIAL_ECHOPGM(" Direction: ");
          if (dir > 0) SERIAL_ECHOPGM("Counter-");
          SERIAL_ECHOLNPGM("Clockwise");
        }

        for (uint8_t l = 0; l < n_legs - 1; l++) {
          double delta_angle;

          if (schizoid_flag)
            // The points of a 5 point star are 72 degrees apart.  We need to
            // skip a point and go to the next one on the star.
            delta_angle = dir * 2.0 * 72.0;

          else
            // If we do this line, we are just trying to move further
            // around the circle.
            delta_angle = dir * (float) random(25, 45);

          angle += delta_angle;

          while (angle > 360.0)   // We probably do not need to keep the angle between 0 and 2*PI, but the
            angle -= 360.0;       // Arduino documentation says the trig functions should not be given values
          while (angle < 0.0)     // outside of this range.   It looks like they behave correctly with
            angle += 360.0;       // numbers outside of the range, but just to be safe we clamp them.

          X_current = X_probe_location - (X_PROBE_OFFSET_FROM_EXTRUDER) + cos(RADIANS(angle)) * radius;
          Y_current = Y_probe_location - (Y_PROBE_OFFSET_FROM_EXTRUDER) + sin(RADIANS(angle)) * radius;

          #if DISABLED(DELTA)
            X_current = constrain(X_current, X_MIN_POS, X_MAX_POS);
            Y_current = constrain(Y_current, Y_MIN_POS, Y_MAX_POS);
          #else
            // If we have gone out too far, we can do a simple fix and scale the numbers
            // back in closer to the origin.
            while (!position_is_reachable_by_probe(X_current, Y_current)) {
              X_current *= 0.8;
              Y_current *= 0.8;
              if (verbose_level > 3) {
                SERIAL_ECHOPAIR("Pulling point towards center:", X_current);
                SERIAL_ECHOLNPAIR(", ", Y_current);
              }
            }
          #endif
          if (verbose_level > 3) {
            SERIAL_PROTOCOLPGM("Going to:");
            SERIAL_ECHOPAIR(" X", X_current);
            SERIAL_ECHOPAIR(" Y", Y_current);
            SERIAL_ECHOLNPAIR(" Z", current_position[Z_AXIS]);
          }
          do_blocking_move_to_xy(X_current, Y_current);
        } // n_legs loop
      } // n_legs

      // Probe a single point
      sample_set[n] = probe_pt(X_probe_location, Y_probe_location, stow_probe_after_each, 0);

      // Break the loop if the probe fails
      probing_good = !isnan(sample_set[n]);
      if (!probing_good) break;

      /**
       * Get the current mean for the data points we have so far
       */
      double sum = 0.0;
      for (uint8_t j = 0; j <= n; j++) sum += sample_set[j];
      mean = sum / (n + 1);

      NOMORE(min, sample_set[n]);
      NOLESS(max, sample_set[n]);

      /**
       * Now, use that mean to calculate the standard deviation for the
       * data points we have so far
       */
      sum = 0.0;
      for (uint8_t j = 0; j <= n; j++)
        sum += sq(sample_set[j] - mean);

      sigma = SQRT(sum / (n + 1));
      if (verbose_level > 0) {
        if (verbose_level > 1) {
          SERIAL_PROTOCOL(n + 1);
          SERIAL_PROTOCOLPGM(" of ");
          SERIAL_PROTOCOL((int)n_samples);
          SERIAL_PROTOCOLPGM(": z: ");
          SERIAL_PROTOCOL_F(sample_set[n], 3);
          if (verbose_level > 2) {
            SERIAL_PROTOCOLPGM(" mean: ");
            SERIAL_PROTOCOL_F(mean, 4);
            SERIAL_PROTOCOLPGM(" sigma: ");
            SERIAL_PROTOCOL_F(sigma, 6);
            SERIAL_PROTOCOLPGM(" min: ");
            SERIAL_PROTOCOL_F(min, 3);
            SERIAL_PROTOCOLPGM(" max: ");
            SERIAL_PROTOCOL_F(max, 3);
            SERIAL_PROTOCOLPGM(" range: ");
            SERIAL_PROTOCOL_F(max-min, 3);
          }
          SERIAL_EOL();
        }
      }

    } // n_samples loop
  }

  STOW_PROBE();

  if (probing_good) {
    SERIAL_PROTOCOLLNPGM("Finished!");

    if (verbose_level > 0) {
      SERIAL_PROTOCOLPGM("Mean: ");
      SERIAL_PROTOCOL_F(mean, 6);
      SERIAL_PROTOCOLPGM(" Min: ");
      SERIAL_PROTOCOL_F(min, 3);
      SERIAL_PROTOCOLPGM(" Max: ");
      SERIAL_PROTOCOL_F(max, 3);
      SERIAL_PROTOCOLPGM(" Range: ");
      SERIAL_PROTOCOL_F(max-min, 3);
      SERIAL_EOL();
    }

    SERIAL_PROTOCOLPGM("Standard Deviation: ");
    SERIAL_PROTOCOL_F(sigma, 6);
    SERIAL_EOL();
    SERIAL_EOL();
  }

  clean_up_after_endstop_or_probe_move();

  // Re-enable bed level correction if it had been on
  #if HAS_LEVELING
    set_bed_leveling_enabled(was_enabled);
  #endif

  report_current_position();
}
```
</details>

**Comment by bcsteeve** [comment]
> I'd have more trust in the author of that function than in documentation.

Point taken (but they should be consistent).

Documentation exists because source is difficult to read.

Changes nothing though.  I tried it.  It moves things around (in a nice smooth pretty pattern).  If anything, that just makes it less accurate of a test **for what we're discussing**.  I fully appreciate the real world application.

**Comment by bcsteeve** [comment]
lol... but "discussing" is not the appropriate term.  My point is being completely ignored.  Closed even, without a word.   Whatever.  THIS particular thing isn't much of an issue.  I'm trying to HELP diagnose a larger issue with ABL, and all I wanted to do was confirm consistancy with my probe to rule that variable out.  Apparently I can't do it with this in-built test, which obviously (by the author's comments) not actually intended to do what it is called, which is "Probe Accuracy Test".   In fact, it seems it is more of a "Probe precision test".  My results are very precise... not very accurate (the terms are often confused.  See  http://cdn.antarcticglaciers.org/wp-content/uploads/2013/11/precision_accuracy.png, for example)

**Comment by AnHardt** [comment]
Let me tell you a little half offtopic story about things that repeat and have at least similar results contrary to your M48 experience.

About the first thing when @Roxy-3D joined us, was to invent M48. All worked pretty well but 'S' behaved much more random than expected. Roxy searched for weeks but could not find the problem. Finally 'S' stayed in, to repair it later, but was likely not propper documented for that reason. Much later we discovered that Roxy tried to use sin()/cos() with grad instead of rad parameters, because (and now the clue) Arduino documentation was unclear about that, at that time.

If things are really repeatable the M48 documentation will be improved pretty soon now, like the Arduino documentation for sin/cos/tan did.


I'd really like to know why your probe system produces that big inter M48 discrepancies. I could now write about some dozen speculations how a dozen kinds of probe systems can fail to be repeatable, but a hint about _your_ system would be highly appreciated.

**Comment by Roxy-3D** [comment]
> which obviously (by the author's comments) not actually intended to do what it is called, which is "Probe Accuracy Test". In fact, it seems it is more of a "Probe precision test". 

Very literally...   It is a Z-Probe Repeatability Test.    It is documented as such.  For example here:   http://reprap.org/wiki/G-code#M48:_Measure_Z-Probe_repeatability

Or here in our source code:  https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Marlin_main.cpp#L104  
or here:
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Marlin_main.cpp#L7257-L7273

**Comment by bcsteeve** [comment]
Yeah... I get that.  Well, sort of.  To be nit-picky, it is more publicly documented as [M48 - Probe Accuracy Test](http://marlinfw.org/docs/gcode/M048.html).

But as YOU suggested to introduce shake, movement, etc... that no longer becomes about the probe, but about the probe + whatever it is attached to + what is moving it, etc.

**Comment by AnHardt** [comment]
@Roxy-3D 
+
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/gcode/gcode.h#L100
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/gcode/calibrate/M48.cpp#L43
https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/Marlin_main.cpp#L104
https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/Marlin_main.cpp#L7345

**Comment by thinkyhead** [comment]
Should I add `S` to the `M48` docs at the marlinfw website? It seems like a fun option.

**Comment by AnHardt** [comment]
Yes please. Just to make my story true.
