### ISSUE TITLE
WHO IS THE GUY THAT HAVE MADE THE PR FOR THE ACTUAL PAUSE SYSTEM

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#9617]
**PLEASE STOP YOUR ETERNAL MODIFICATION I'M REALLY TIRED !!!!!!!!!

Not tested , not finished ,  and MADE ONLY FOR YOUR MACHINE

Every day something is modified  , and now pause system IS SHIT

YOU CAN NOT MODIFY ETERNALLY , because we built our machine and we need A FIX PSYCHOLOGY 

You change the names every weeks , You change all 

AND NOT TESTED NOT VERIFIED**

@thinkyhead   please stop to merge pause system , before asking me to check  , looks the tons of shit , i don't know who is the guy that write this but , since one year , every week i have modifications , eternally modifications , and it's enough now , i need progression , no regression 

First : 
```
/**
 * Unload filament from the hotend
 *
 * - Fail if the a safe temperature was not reached
 * - Show "wait for unload" placard
 * - Retract, pause, then unload filament
 * - Disable E stepper (on most machines)
 *
 * Returns 'true' if unload was completed, 'false' for abort
 */
```
This code says '  retract , pause to cool and unload ' ,   HERE I UNDERSTAND  the filament is cooled to avoid to dirty the gear when go out and look the bad syntax in the description 
But later in the code 
```
  // Filament Unload does a Retract, Delay, and Purge first:
  #define FILAMENT_UNLOAD_RETRACT_LENGTH 13   // (mm) Unload initial retract length.
  #define FILAMENT_UNLOAD_DELAY 5000          // (ms) Delay for the filament to cool after retract.
  #define FILAMENT_UNLOAD_PURGE_LENGTH 8      // (mm) An unretract is done, then this length is purged.
```
 Now it's impossible to understand because NOW  WE PURGE after RETRACT , and we don't UNLOAD, and we have purge length value ' why '

and later in the code 

```
// Retract filament
  do_pause_e_move(-FILAMENT_UNLOAD_RETRACT_LENGTH, PAUSE_PARK_RETRACT_FEEDRATE);

  // Wait for filament to cool
  safe_delay(FILAMENT_UNLOAD_DELAY);

  // Quickly purge
  do_pause_e_move(FILAMENT_UNLOAD_RETRACT_LENGTH + FILAMENT_UNLOAD_PURGE_LENGTH, planner.max_feedrate_mm_s[E_AXIS]);

  // Unload filament
  do_pause_e_move(unload_length, FILAMENT_CHANGE_UNLOAD_FEEDRATE);
```
Here we have  PURGE  + UNLOAD , I DON T UNDERSTANT , and the worst is the MAX FEEDRATE that can explodes the filament or  sand it , in the pause definition  we have defined a FEEDRATE for unload , why not used here , this CODE IS SHITTTTTTTTTTTTTTTTTTTTTTTTT ! We retract , we cool , and we return in the hotend , and we unload ,  it's the fifth dimensions here !

IT S NOT SERIOUS , i'm tired  to see eternal VERY BAD modification OF OUR PRECIOUS PAUSING PROCESS

And stop to change the name  ETERNALLY , because , just for one or two words , we can not drop our config and configadv to test new release , i'm ok for deep modification , but  just for one new modified word , the unit is dead

PLEASE DOWNGRADE !
The thinkyHead Punition requiered !
Some guys here are too much happy to contribute and forget to give priority to the quality instead of to be merged the more quickly as possible to feel good and feel ' great engineer'

**Comment by Squid116** [comment]
1. If you require stability - why would you be pulling and compiling frequently? surely you would only want to use a stable branch?
2. Why don't you watch the areas of the code you are particularly interested in and add some constructive criticism on any PRs which impact this feature?  This might would help both you and the devs in a positive manner.
3. If you are frequently pulling new versions, you can commit and merge your configs in your own fork (or local repo).  There shouldn't be a need for 'dropping' a config in and out regularly if you do this.
4. The **VOLUNTEER** devs are working very hard, they are maintaining an enormous code base, adding new features and moving towards 2.0 and 32 bit compatibility.  They are going to get some stuff wrong occasionally (I'm not sure they are in this case), as they are after all human - however a long rant like this does nothing to help and only distracts them from these tasks.

**Comment by ghost** [comment]
Yes , I know
But , the first line of the rules here is  ' RESPECT THE MILLIONS HOUR OF WORKS GIVEN gratefully by everyone here ' , the second lines is ' MAKE ALWAYS A PROGRESS AND DONT DESTROY ALL THAT HAVE ALREADY MADE

**Comment by ghost** [comment]
To answer you
I discover an old bug of UBL , i'm talking about this , in the issue tab ,  and i discover a second bug again , and the communauty tell me that all is fixed in the last bugfix , it's why , i decide again and again , to update , but i have my own features to install over it ,  i have made ' spool swapping , my own filament loading , my own multi pin sensor runout ' and MANY MORE

So , i decide , to fuck a few hours  to make my new release , but , i discover , THE PAUSE SYSTEM IS DESTROYED , totally DEAD
And it's not the first time someone make some BAD PR about the pause system , i'm in favor of progression , but ,  there is no progression , always regression
It's not me when i scream here , but , trust me when i say , the PAUSE SYSTEM IS FUCKED on the last bug fix

**Comment by AnHardt** [comment]
@studiodyne 
I would have much more trust in what you tell us if you wouldn't be that loud an selve confident.
Always you are writing in capitals using superlatives and claiming to be the best and writing error free code. That's simply unlikely. What can we trust in and what not? Reading your comments leave the impression you are not trustworthy

Ok. You want your extra attention. But if you continue that way you will end in my killfile.

By the way. Yes, we have a problem with code changed by programmers not knowing what they do. But every now and then we all do that. Marlin is too complex now to have a complete overview. A year ago i knew the code nearly by heart. But after a break for about half a year i have no chance to keep up. Marlin is moving faster than i can follow it. That's frustrating for me, but a sign for a much more active community - what makes me lucky.

**Comment by thinkyhead** [comment]
http://marlinfw.org/docs/development/contributing.html#community-guidelines

I may need to add a new section for mad Frenchmen.

**Comment by thinkyhead** [comment]
Did you actually create 5 sock-puppet Github accounts to upvote this nonsense?

Thin ice is breaking.

**Comment by ghost** [comment]
@AnHardt  I totally don't care what you always says , i hate your style of communication and i never read all you say
@Thinkyhead , i love your style , your brain , this extraordinary brain , and every day when i use marlin , this magic firmware that is truely a great advance firmware , babystep/ubl/Fw , i think about you , and the chance to have you as boss here, and the time you spent everyday FOR ME , and all people of this world , and all the companies that love marlin. 
But i'm not engineer like you , but , i know when SHIT IS DONE !!!!!!!!!!!! and i know the last PR is not thinkyheadstyle , you trust too quickly some guys and you merge them . The last pause system is modified everyweek , it's too much ! Names are changed all the time ! Impossible to try a new release just because of a little name. What a surprise when i would help roxy to find the fix for ubl strange behavior , to see what is became the config adv ... changed again , and again , and always THE PAUSE SYSTEM !
STOP !!! too much ! And i was afraid to try it. I know it's not you , because , you don't have this writting style , but you trust too much some bad writters.
In all i have said about this topic , you will never the target of my words , only the guys you trust too much !
@AnHardt  : do not answer me , i will never read

**Comment by ghost** [comment]
@thinkyhead   I came too late in c++world and i can not contribute as the same powerfull way you do it , so i want to make a donation to you for the time and the talent you place in this firm , but , in all your website or anywhere , it's totally impossible to talk to you in private. I have a modest life , it will be a modest donation , but i want to thank you , i love my firmware , it's really a GREAT ADVANCED SOFTWARE !
You understand why i want to fight everyone who want to kill the millions hours of job that have made born this firm !

**Comment by AnHardt** [comment]
Plonk
