### ISSUE TITLE
Second extruder addition

### ISSUE THREAD

**Issue by tr247** [MarlinFirmware/Marlin#9618]
Hi,

i was wondering if you could help me with the addition of a second extruder on the UMO+ using marlin. I am looking to use a second stepper motor using the spare driver on the V2 board. However i cant seem to get it working using marlin i only get it using the original extruder stepper.

any help greatly appreciated

**Comment by tr247** [comment]
@thinkyhead do you have any idea?

**Comment by Drayson80** [comment]
Hi @tr247 .
pls. discuss this in the Ultimaker Forum @ ultimaker.com - there are a lot of people which can help you more in detail.
UMO+ uses a UM2 board with a highly customized, much older fork of marlin
It´s quite simple, but ther you will find assistance...

**Comment by thinkyhead** [comment]
Yeah, sorry @tr247 — With all the code and logistical things going on here leading up to the next release I can hardly remember my name. You'll definitely find more help from other UM users than from the core Marlin developers.
