### ISSUE TITLE
I wanted to display zh_CN on LCD Marlin. Please help

### ISSUE THREAD

**Issue by Shrikant888** [MarlinFirmware/Marlin#9628]
sir, I am using Marlin with Sanguinololu board. I wanted to display zh_CN on 128*64 LCD.

I am changing in Configuration.h file. But seems I am only getting utf8 of zh_CN on LCD. Please tell me what I have to do? Thanks in advance

**Comment by cjsoong** [comment]
@Shrikant888 
#define LCD_LANGUAGE cn
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
