### ISSUE TITLE
[2.0.x] STEPPER_DIRECTION_DELAY exists, not implemented

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#9634]
While there is a `STEPPER_DIRECTION_DELAY` setting, currently it does nothing.

Is it needed, or can we drop it?

**Comment by p3p** [comment]
Looking at a few (drv8825, 4988, tmc2130) datasheets worst case (drv8825) for Dir setup time is 650ns which is high enough to start causing issues in 32bit land depending on instructions between the pin toggle operations and mcu specifics, This also applies to Enable but I assume that's not as tightly coupled with the stepping. so .. in theory its needed at least.

**Comment by smoki3** [comment]
is this maybe the problem for my not moving z axis with drv8825 on radds?

**Comment by p3p** [comment]
@smoki3 It's unlikely, if this is an issue I think it will just be a single microstep in the wrong direction when changing directions, I'm sorry you haven't manged to solve that problem yet.

**Comment by smoki3** [comment]
i dont know whats the problem. now i orded some new stepper drivers (tmc2130) i will try to replace the drv8825. maybe than its working for me. but the problem still exists

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
