### ISSUE TITLE
Is M500 really saving mesh?

### ISSUE THREAD

**Issue by batata004** [MarlinFirmware/Marlin#9639]
Hi,

I am using BILINEAR to map a mesh of my bed. I never had eeprom enabled so I enabled it now in MARLIN. So I booted up my printer, executed G29 and after it finishes I executed M500 to save data.

Then I turn the printer off. When I turn on my printer I only home the 3 axis and start printing and it's not good result. Do I need to execute any code, after turning on my printer, to make sure the mesh is loaded from the eeprom and used?

**Comment by GMagician** [comment]
~~G29 S0 I suppose~~
Sorry I was "drunk" ;-)
M420 S1 (don't know if it works also with bilinear)

**Comment by batata004** [comment]
kkkk thanks!

**Comment by Roxy-3D** [comment]
Did you save your mesh with M500 ?     If not...   You probably don't have good mesh information.

**Comment by batata004** [comment]
YEAP I followed your advice from another thread @Roxy-3D ! I saved then I loaded ;) thanks!
