### ISSUE TITLE
G29 response "OK" but hotend is not moving

### ISSUE THREAD

**Issue by raymondlml** [MarlinFirmware/Marlin#9644]
I flashed marlin 1.1.8 on my CR-10S with bltouch installed. Other commend such as G28, G29 P1 works great but not G29. 

When I use the terminal on Octoprint to send "G29" right after "G28", the hotend is not moving. According to what I found, the probe should move around an perform auto bed levelling. I am not sure what went wrong.

Configuration.h and Configuration_adv.h can be found here. Thanks in advance for all your help.
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/1727610/Config.zip)

**Comment by GMagician** [comment]
UBL and only G29 does nothing, as I know...

http://marlinfw.org/docs/gcode/G029-ubl.html

**Comment by Roxy-3D** [comment]
Correct.   A G29 with no other information is basically a NOP.

**Comment by tcm0116** [comment]
@Roxy-3D is there any reason why UBL's G29 with no parameters couldn't go ahead and probe the entire bed and activate UBL? This with allow UBL to be compatible with the standard definition of G29. 

I realize a lot of the purpose of UBL is to provide a more sophisticated approach to bed leveling, but seeing as it's supposed to be "Unified", it should also encompass the basic function of the other leveling methods. 

I brought this up with @thinkyhead, and he seemed surprised that UBL's G29 with no parameters had no function.

**Comment by thinkyhead** [comment]
> probe the entire bed and activate UBL

That would be a good default behavior. Is there any technical reason why it should not?

**Comment by Roxy-3D** [comment]
Do you mean probe the portion of the bed that the probe can reach and then activate?

We could do that...    But is that a useful shortcut?   If that is what they wanted to do we only saved them from typing a P1 after the G29.     It maybe a more useful thing to assume is they want to do G29 P0 J4.   That would behave like the old school grid based leveling.   We could always add a #define to specify what the default G29 (with no parameters) is.      My vote would be it is G29 P0 J4 A

**Comment by thinkyhead** [comment]
> But is that a useful shortcut?

It is a reasonable user expectation, as they say in the software biz.
Most users know about `G29` … but ask them what "`P4`" means.

> We could always add a #define to specify what the default `G29` (with no parameters) is.

Sure, I suppose so. People are clamoring for more options. This one is pretty concise.

**Comment by Roxy-3D** [comment]
>> We could always add a #define to specify what the default G29 (with no parameters) is.

> Sure, I suppose so. People are clamoring for more options. This one is pretty concise.

How about we change the focus a little bit...   We can use this as a test case.   How about we have a macro or a super small function that can tell us how many parameters have been specified for the command.   In this case, if the answer is zero, we just parse the specified, default command.
   
That way, other functions might be able to benefit from it....    I'll write it if you don't feel like doing it.  Probably...  After the command is chopped off the front of the line, I'm thinking we can scan across the remaining part of the line looking for letters.   It maybe we can just extend the parser code to leave the number of parameters laying around for the command to look at...

**Comment by thinkyhead** [comment]
```cpp
if (!parser.seen_any()) SERIAL_ECHO("No arguments.");
```

**Comment by Roxy-3D** [comment]
OK!  

We still want to use the normal parser functions...   So I presume the 'right' answer is to do a strcpy() ( or strcpy_P() ) to move the specified default string into the string buffer.    Basically, over write the simple G29 with what ever the user specifies...   And then tell the parser to re-initialize what it thinks is there....

**Comment by boelle** [comment]
@raymondlml Please post your question either on discord: https://discord.gg/n5NJ59y or on facebook: https://www.facebook.com/groups/2080308602206119/
The issue list is for bugs and feature requests only
Please close this issue once you have posted it on one of the 2 links
Thanks :-D
