### ISSUE TITLE
Extruder fan reversed

### ISSUE THREAD

**Issue by cube0712** [MarlinFirmware/Marlin#9664]
I got my extruder auto fan working, but it's reversed. When the hotend is under 50°C the fan is on, and when above 50°C the fan turns off. 

How can i reverse the output of the D6 pin i use for the fan?

**Comment by Bob-the-Kuhn** [comment]
What board are you using?

You probably have the fan wired up wrong.

If it's tied to a power FET then + lead of the fan goes to power (usually the terminal marked +) and the - lead of the fan goes to the other terminal.

If it's tied to a logic pin (must be a low power 5V fan) then the + lead goes to the logic signal and the - lead goes to ground.
