### ISSUE TITLE
Prb with my 3d printer program

### ISSUE THREAD

**Issue by sathishcores** [MarlinFirmware/Marlin#9679]
I have a prb with my program so someone can edit for me
I don't have Endstops 
So please eliminate it 
And it should also work without hotend when k calibrate it

**Comment by sathishcores** [comment]
Can you provide me your program

**Comment by sathishcores** [comment]
For testing

**Comment by sathishcores** [comment]
Don't enable the Endstops

**Comment by thinkyhead** [comment]
http://forums.reprap.org/list.php?415
