### ISSUE TITLE
2.0 DUMMYB Not In Scope in cfgstore.cpp IMPOSSIBLE TO COMPILE

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#9681]
Dummyb have been created between  ' no ubl and no Fw '
But later in the code ' if disabled ' no volumetrics '  ,  dummyb is used in the else conditionnals

I have UBL+FW+NOVOLUMETRICS and no compilation possible
I don't know who have written this , but , seems to be easy to fix for his author

Thks

**Comment by thinkyhead** [comment]
```diff
- #if DISABLED(AUTO_BED_LEVELING_UBL) || DISABLED(FWRETRACT)
+ #if DISABLED(AUTO_BED_LEVELING_UBL) || DISABLED(FWRETRACT) || ENABLED(NO_VOLUMETRICS)
    bool dummyb;
  #endif
```
