### ISSUE TITLE
Bed Autotune Failure

### ISSUE THREAD

**Issue by Cr3470r** [MarlinFirmware/Marlin#9696]
### Bug Report
- Description:
When attempting to tune PID for heat bed, temperature reaches target temp then drops linearly until I receive a THERMAL RUNAWAY error.

- Expected behaviour: 
Use command "M303 E-1 C8 S60", expect bed to reach 60C and cycle 8x, provide new PID values.

- Actual behaviour:
Reaches target temperature (or as much as 5C below target) then drops and throws error at about 40C.  Bed reaches target temp and maintains it otherwise.

- Steps to reproduce:
In Pronterface issue command: "M303 E-1 C8 S60"

[Config Files.zip](https://github.com/MarlinFirmware/Marlin/files/1734430/Config.Files.zip)

------------------------------------------------------------
Thanks Guys!
```

**Comment by Cr3470r** [comment]
May be a hardware problem; will replace the RAMPS and report if there is any change.

**Comment by enigmarobo** [comment]
Good day. Isn't E -1 extruder other than bed? I got an error the other day on PID autotune when I specified bed temps for extruder. On my setup, E0 is the bed.

**Comment by Cr3470r** [comment]
"E0" is the designation for the first extruder (in Marlin).  Additional extruders would count up (E1, E2).  E-1 refers to the bed.  Syntax for tuning the bed would be: "M303 E-1 C8 S60"  autotune bed for eight cycles at temperature 60C.

**Comment by enigmarobo** [comment]
Maybe it's different for other printers. I have a Robo 3D R1+ and E0 is the bed. E -1 is the hot end. I just compiled and uploaded 1.1.8 two days ago. When I performed the PID auto tuning at first I sent M303 E -1 S50 C8 and received incorrect extruder error. The temp didn't match any hot end temp I imagine. It seems like it should be a standard in the firmware.

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by AnHardt** [comment]
@enigmarobo 
Is `PIDTEMPBED` active at all?

**Comment by enigmarobo** [comment]
I'll have to see when I get home from work. Tuning completed for me once I
specified the correct target temps for the extruders.

Raymond Ilano

**Comment by thinkyhead** [comment]
> Tuning completed for me once I specified the correct target temps for the extruders.

Interesting… I wonder what our defaults are and whether they're reasonable…

**Edit:** 70 for bed, 150 for extruder. Hmm

**Comment by enigmarobo** [comment]
@AnHardt PIDTEMPBED is active. Here's a photo of my machine heating up. The bed is already done. This is the hotend is heating up. 
![bedtemp](https://user-images.githubusercontent.com/36683358/36622464-3b4bc180-18cb-11e8-9601-ac1bf6001558.jpg)

**Comment by AnHardt** [comment]
Did you look it up in your config?
If `PIDTEMPBED` is not active the bangbang does heat up the bed but obviously there is no way to tune the PID parameters. Up to now this was always the reason for an unexpected "There is no bed". 
`PIDTEMPBED` is not active by default.

**Comment by enigmarobo** [comment]
Yes. In configuration.h it is active, not commented out. Perhaps it is a misprint on the LCD side. The machine works as expected when printing.

**Comment by markolo25** [comment]
Had the same issues updated to bugfix-1.1.x it's fixed 😄

**Comment by TheAdminKing** [comment]
I'm experiencing the same issue here. Figured won't open a new case as this is open. I am using 1.1.x the latest version download from the site and I cannot get the PID to recognize the bed. When putting E-1 I get unrecognized extruder using E0 well that is where my extruder is plugged into I have nothing connected to E1 yet. Don't know how to approach this as I haven't been able to get my bed to heat up to what it should be able to. I can only get it to about 70C. Any thoughts or suggestions are welcome

**Comment by gloomyandy** [comment]
If you want help you really need to post your configuration files. But it sounds very much like you do not have PIDTEMPBED defined in your configuration. You can only tune the bed PID if you are using PID for the bed and the default is to use bang, bang control. 

If you want help on the general question about heating your bed then you probably need to provide details of your printer/bed/controller/power supply. Though you may get better answers by posting in a forum (or facebook page) that is specific to your machine (as people will be more familiar with what you have).

**Comment by boelle** [comment]
@Cr3470r still having issues?

**Comment by Cr3470r** [comment]
@boelle  My issue was a hardware failure. Turned out to be a faulty mosfet.

**Comment by boelle** [comment]
Then maybe click close below?

**Comment by thinkyhead** [comment]
> Then maybe click close below?

Let's use this canned reply: "**If this issue is resolved, please click the close button below. Thanks!**"
