### ISSUE TITLE
Delay needed before moving to Z_SAFE_HOMING position after sensorless homing with TMC2130

### ISSUE THREAD

**Issue by quittenkaes** [MarlinFirmware/Marlin#9704]
If using TMC2130 drivers with SENSORLESS_HOMING and Z_SAFE_HOMING enabled either the x or y axis will not move to the safe homing position. Which axis doesn't move depends on which axis was homed last. 

By adding a short delay before moving to the safe homing position this behaviour can be fixed.

I'll submit a pull request with a possible fix later.

**Comment by thinkyhead** [comment]
Patched for both safe homing and quick xy homing.
