### ISSUE TITLE
dual z rumba don't work

### ISSUE THREAD

**Issue by amirgaziel0** [MarlinFirmware/Marlin#9719]
Hello everyone
I tried everything
I do not know what to do anymore
I'm adding photos of settings I've set up
My board is RUMBA BIQU

1. my board configuration.h
![image](http://www.interload.co.il/upload/5673096.jpg)
2. configuration_avd.h
![image](http://www.interload.co.il/upload/4422559.jpg)
3. pins_RUMBA.H
![image](http://www.interload.co.il/upload/908096.jpg)

  
please help me
Thank you

**Comment by revilor** [comment]
The image links are broken. But please don't replace the images, attach your configuration files instead.

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by thinkyhead** [comment]
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files and drop them into your next reply. We'll check them over and see if anything is amiss.

**Comment by amirgaziel0** [comment]
Configuration.h and Configuration_adv.h files
[conf.zip](https://github.com/MarlinFirmware/Marlin/files/1754692/conf.zip)

**Comment by thinkyhead** [comment]
We have a form that needs to be filled out for issues so that we can understand your problem. If you don't want to fill out the form then we can't help you. This is not a new policy, but we are going to be especially strict about this for support requests.
