### ISSUE TITLE
Idea da aggiungere nel menu

### ISSUE THREAD

**Issue by philfire** [MarlinFirmware/Marlin#9725]
Il mio, non e un vero problema, ma uno spunto per una aggiunta nel menu, del marlin. L'idea, mi e venuta, quando ho sostituito i pololu 8825 con i tmc2100, che richiedono l'inversione dei motori. Perché, avendo la EPROM attiva, non inserire la possibilità di invertire la marcia e salvare l'impostazione in EPROM, direttamente da display? Sarebbe comodo.

**Comment by GMagician** [comment]
"Visto che tutti scrivono in Inglese sarebbe una cortesia non usare la tua lingua"
As everybody write in English it should be a courtesy not to use your own language

In my opinion that will increase code size and slow down execution for something that has to be changed only once, when you prepare your machine.. I may be completly wrong though

**Comment by thinkyhead** [comment]
@GMagician — Agreed.

Una sola parola: efficienza. Le costanti producono codice molto più veloce delle variabili.

**Comment by GMagician** [comment]
@thinkyhead do you know Italian? wow you astonish me!
This seems not a google translation, too correct

**Comment by thinkyhead** [comment]
I can't speak Italian to save my life. But I can tell a bad translation from a good one in most Romantic languages.
