### ISSUE TITLE
add chamber Temp in the display

### ISSUE THREAD

**Issue by sikousikou** [MarlinFirmware/Marlin#973]
I have a Rumba board with dual extruders and a full graphic display 
how can I display the temperature of the chamber sensor in the display?
please add the setting of chamber thermistor + dual extruder to the config
sorry for my bad englisch

**Comment by etogburn** [comment]
I second this. Would be nice to see M141 used to set chamber temp. Not sure if there is a standard "wait for temp" gcode for chambers but that would be nice too

**Comment by boelle** [comment]
How many would benefit from this?

**Comment by sikousikou** [comment]
This feature is very useful to monitor the ambient temperature for all user who have a 3d printer with closed  chamber or heated chamber 
sorry for my bad englisch

**Comment by boelle** [comment]
yes but so far you are the only one requesting it...

i wonder how people manage to monitor temp in chambers so far... 

if it was me i would just hook up a thermistor and monitor that one... example: i have a machine with 1 extruder but the host displays temp for 2 extruders... so i could just hook up a thermistor to extruder input 2

no new coding needed... and if i want to add heating i can just connect the heating to extruder 2 output and set the temp from the host

**Comment by etogburn** [comment]
The main reason I'm requesting this is for use on an azteeg x3 pro. I will have a 4 extruder setup. I would have used an extra extruder heater for the chamber if I wasn't going to use the 4 available anyways. It would be nice to use chamber Gcode but the ability to add extra heaters to match the board I have would suffice

**Comment by thinkyhead** [comment]
@etogburn The quick workaround is to hack the firmware so it still reads the heater sensor even though there's no extruder with it. At the moment the code naively assumes that every heater has either an extruder or a bed, so it needs a lot of work to get it to a place where these are more separated concepts.

**Comment by grob6000** [comment]
I currently have a temperature-controlled chamber, and use a second extruder channel, as it was a quick way to get host support. I'd be interested in a tidier implementation too.

**Comment by etogburn** [comment]
@thinkyhead That would work. I could manually toggle a pin using M42. (my air heaters are going to be driven by external MOSFETs anyways) So I would just need to monitor the temperature in the chamber for the time being. Just to be sure it doesn't get too hot. I haven't had a chance to really look into the code, I may spend some time doing that before I complete my build.

**Comment by boelle** [comment]
i will close this one as there are to little people that show interest in it. If someone would like to do the feature they should just send a PR

**Comment by Kriechi** [comment]
I'm also interested in doing something like this.
Hooking my heater up as second extruder sounds easy - but I'm not sure what happens if the temp-protection stuff messes up everything? is there a way to disable it?

**Comment by Blue-Marlin** [comment]
How about THERMAL_PROTECTION_HOTENDS?

Or tuning

```
#if ENABLED(THERMAL_PROTECTION_HOTENDS)
  #define THERMAL_PROTECTION_PERIOD 40        // Seconds
  #define THERMAL_PROTECTION_HYSTERESIS 4     // Degrees Celsius

  /**
   * Whenever an M104 or M109 increases the target temperature the firmware will wait for the
   * WATCH_TEMP_PERIOD to expire, and if the temperature hasn't increased by WATCH_TEMP_INCREASE
   * degrees, the machine is halted, requiring a hard reset. This test restarts with any M104/M109,
   * but only if the current temperature is far enough below the target for a reliable test.
   */
  #define WATCH_TEMP_PERIOD 16                // Seconds
  #define WATCH_TEMP_INCREASE 4               // Degrees Celsius
#endif
```

for the slowest heater.
Opening the door will still be a problem.

**Comment by Kriechi** [comment]
Yes - it would be a nice feature if we could set `THERMAL_PROTECTION_HOTENDS` for each hotend individually - this would solve my problem.

**Comment by thinkyhead** [comment]
To disable thermal protection for specific hot-ends, currently you can modify the `manage_heater()` function, and in the "Loop through all extruders" block, do something like `if (e != 0) continue;`. Later it would be nice to have a formal `AMBIENT_TEMP_SENSOR` feature.

**Comment by mrsnowin** [comment]
Very usefull feature! I really need this.

**Comment by xbranca** [comment]
Hello,

I am looking for the same feature. 
I am actually running marlin on a Ramps 1.4 with 1 extruder / 1 Fan / 1 Bed (EFR).
T0 is used by hot end thermistor, T1 by the bed's one and my wish is to use T2 to monitor temperature in my printer chamber.
It seems actually impossible but evrything is hers so shouldn't be a big issue to enable T2 temp measurement in this setup.

Thank you for your help.

Xavier

**Comment by nitso** [comment]
:+1:

**Comment by thinkyhead** [comment]
Still set for the 1.1.1 milestone.

**Comment by Anry777** [comment]
1.1.1 is over
But there no this future

**Comment by pablogventura** [comment]
I'm interested in implementing this functionality. Is there any recommendation to make me, before I start?

**Comment by SturmGhost** [comment]
Also interested in this feature...

**Comment by lukeskymuh** [comment]
I am also interested. 

To have it displayed would be great. To have  the possibility to controll woud be amazing.

Personally I need only the ability to cool as my HB generates enough heat.

Therefore it would be at best for me to have the possibility to use 2 output pins:
- control fan speed or on/off. (PID would be great to to reduce noise)
- a servo to open a hatch (PID would be great also) to let air in.

For safety: In case of fire(high temperature limit) I would like to shut down everything and close the hatch.

Remark: I know of some guys using the "second extruder" as a work aroud.

**Comment by davidmonten** [comment]
I'd be interested too.
I'm using a Megatronics 3, with several temp sensors (I'm actually using just two, planning to install the third).
In my opinion having a dedicated tool to manage chamber temp and emergencies would be helpful for the development of more advanced printers.

**Comment by fvergniaud** [comment]
I 'm already implementing this  using a free extruder, but this isn't nice, The best way to do is duplicate de bed function, because the heated chamber is very near to this. I'm on this now.

**Comment by bliser3d** [comment]
Sorry for my bad english (my language is russian).
I have a Rumba board, two extruders and a full graphic display.
I made a display of the temperature of the printer's camera on the printer's display.
The temperature is displayed on the display at the location of the third extruder.
Next, I will bring my code to display the temperature on a full graphic display.
The code works on my self-made printer with Marlin 1.1.8 firmware.
If you (developers) decide that it is not bad then add it to your project. I will be grateful to you for this. I think that it will be interesting to others.

File **Configuration.h**:
After the line 
`#define TEMP_SENSOR_BED ...`
Add code:
`#define TEMP_SENSOR_CHAMBER ...`

File **pins_RUMBA.h**:
After the line 
`//#define TEMP_X_PIN ...`
Add code:
`#define TEMP_CHAMBER_PIN   12`

Other modified files **Conditionals_post.h, temperature.cpp, temperature.h, thermistortables.h, ultralcd_impl_DOGM.h**
In order to see that I added code to the program - I send the original and changed files in two archives (Changed.zip, Original.zip).

[Original.zip](https://github.com/MarlinFirmware/Marlin/files/1627553/Original.zip)
[Changed.zip](https://github.com/MarlinFirmware/Marlin/files/1627554/Changed.zip)

I hope this will be useful to other users of 3d printers.

**Comment by fvergniaud** [comment]
bliser3d , I'm testing your changes, looks great, I implement this on standard RAMPS , It look so good. Thanks.

**Comment by fvergniaud** [comment]
Did you also work de temperature controller?, I'm planning to use a driver with a moc3041 and a triac to control a hairdryer, as a heater for the chamber. at least in the begining.

**Comment by xbranca** [comment]
A bit out of scope but i use a reptile heat wire inside the wooden box i
made for my printer.

https://m.ebay.co.uk/itm/4m-5m-7m9m-15w-25w-50w-80w-Reptile-Waterproof-Heat-Cord-Cable-/391793513696

A 100w watt model regulated with a cheap chinese temp controller enable me
to have 15-20 degc into the box which is in my garage at 0 degrés.

This while waiting kind programmers to add this chamber temperature sens
and control feature to marlin. ; ).

Cheers.

message saisi sur smartphone

**Comment by bliser3d** [comment]
**fvergniaud**: Did you also work de temperature controller?
No. 
I do not control the temperature (inside the printer's camera). I just need to see the temperature value.

**Comment by Lenbok** [comment]
Initial cut of chamber temp monitoring and chamber cooling fan control at #9789, if people want to test, comment.

**Comment by bliser3d** [comment]
My advice on January 13 "add a camera temperature display to the display screen" works in version 1.1.8, but does not work in version 1.1.9.

**Only for version 1.1.9**:
I displayed the temperature of the printer's camera on the printer's display. I have a Rumba board, two extruders and a full graphic display. The temperature of the camera (from the T3 sensor) is displayed on the display at the location of the third extruder. If you use 3 extruders, the temperature (in the printer's camera) on the printer's display is not displayed.

To display the temperature - make the following changes to the firmware code Marlin ver: 1.1.9:

File **Configuration.h**:
Activate the camera's temperature sensor (change the value from 0 to 1 or more)
#define TEMP_SENSOR_CHAMBER 1

File **pins_RUMBA.h**:
Uncomment line
#define TEMP_CHAMBER_PIN   12

File **temperature.h**:
1. Before the code block:
  ```cpp
    #if ENABLED(BABYSTEPPING)
      static volatile int babystepsTodo[3];
    #endif
  ```
  Add code:
  ```cpp
    #if HAS_TEMP_CHAMBER
      static float current_temperature_chamber;
      static int16_t current_temperature_chamber_raw;
    #endif
  ```

2. Change code in block:
  ```diff
    #if HAS_TEMP_CHAMBER
      static uint16_t raw_temp_chamber_value;
-   static float current_temperature_chamber;
-   static int16_t current_temperature_chamber_raw;
    #endif
  ```

File **status_screen_DOGM.h**:
After the code block:
```cpp
// Heated bed
    #if HOTENDS < 4 && HAS_HEATED_BED
      _draw_heater_status(STATUS_SCREEN_BED_TEXT_X, -1, blink);
    #endif
```
Add code:
```cpp
    // The temperature in the chamber (inside the printer).
    #if EXTRUDERS < 3 && TEMP_SENSOR_CHAMBER > 0
      u8g.drawFrame(52, 0, 24, 26);
      _draw_centered_temp(thermalManager.current_temperature_chamber + 0.5, 54, 15);
    #endif
```

**Comment by italocjs** [comment]
Sorry for reopening this, but there is the pin for the output set on marlin 1.1.9?  i cant find it.
