### ISSUE TITLE
Missing  jerk steps and other setting in lcd menu rc bugfix downloaded yesterday and today 

### ISSUE THREAD

**Issue by bogaskilop** [MarlinFirmware/Marlin#9736]
Hi  yesterday i tried to compile new fw rcbugfix  for tmc2130 and all goes smooth and printer is working  but ...
in LCD menu there are missing settings like steps.  jerks, accelleration , velocity.  I got only Z offset in this menu tree 

i downloaded rcbugfix today  20.02.2017 compiled and still the same situation.

only this option is available in Motion  menu 
Z Offset 

missing : 

Feedrate » | Feedrate settings |  
Acceleration » | Acceleration settings |  
Jerk » | Jerk settings |  
Steps/mm » | Steps/mm for XYZ axes and extruders

#

**Comment by Sebastianv650** [comment]
Do you accidentally enable `#define SLIM_LCD_MENUS` in `Configuration_adv.h`?

**Comment by bogaskilop** [comment]
yes i always used that option in older FW versions

**Comment by bogaskilop** [comment]
Ok thx   this solve the problem
