### ISSUE TITLE
[ThinkyHead] - Filament RUNOUT COMPILE ERROR 'make a fix '

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Marlin#9766]
2 issues
1. In the class FilamentRunoutSensor, all is private by default  , and all your functions are used in extern  
2. Before  ' reset ' function , you have forgotten ' void '

If you make these two corrections , all works and no compiler warning

I'm the new thinkyheadizer here ! 😅 
look : 
```
class FilamentRunoutSensor {
	public:   <---------------------------------------- added

  FilamentRunoutSensor() {}

  static bool filament_ran_out;
  static void setup();

  FORCE_INLINE static void reset() { filament_ran_out = false; }    <--------' void added '
```

Help: Please can you make something special for me ,  ' Fw swap status ' to public , because this variable need to be accessible , it's for my future project , Thks

**Comment by teemuatlut** [comment]
https://github.com/MarlinFirmware/Marlin/pull/9769

**Comment by ghost** [comment]
Yes 👍 
But you scarify too much the thinkyhead style loll
He will never love you re write so many lines

Thinkyheadisation ! Is the first rule here lollllllllll

**Comment by thinkyhead** [comment]
@Studiodyne — _"Brevity is the soul of wit."_

❌ Love you man, but these kinds of "charming" antics will get you banned. Fair warning. ❌

**Comment by ghost** [comment]
Please  your are develloper , don't try to be a menace for society 👍  you are not good in this job
and , please , inform this issue of what you have decided ,  if you have fixed something , if issue have a happy end 
Thks

**Comment by thinkyhead** [comment]
I'm much happier now. I can come to work everyday assured of less nonsense.
