### ISSUE TITLE
Stepper motors have no power since steps/mm change

### ISSUE THREAD

**Issue by blackdevil8975** [MarlinFirmware/Marlin#9776]
Since I change my steps/mm to 2560 my stepper Motors have no power anymore. It worked fine with 80steps/mm. There they had plenty of power and moved the x and y axis easily. Now they cant even move the axis anymore.

I got 1.8° stepper motors with 16x microstepping and M8 rods

Any solutions?

**Comment by TheSFReader** [comment]
Did you try and decrease the movement speed (at first to get to a similar steps timing, and speed it up later)? I think if the steps are too fast, the driver can't follow so can't provide adequate power to the steppers.

**Comment by blackdevil8975** [comment]
Thanks! You were right!
