### ISSUE TITLE
[bug-fix-2.0.x] [solved-need commit]TMC-CS Pin not found in configuration_adv.h

### ISSUE THREAD

**Issue by dembach** [MarlinFirmware/Marlin#9778]
cannot compile.
using delta default config and altered with : 
```
#define HAVE_TMC2130
#define X_IS_TMC2130
#define Y_IS_TMC2130
#define Z_IS_TMC2130
```

PINS are defined in my board file... (as usual)
but if i try to compile i encounter following error:
```
in file included from sketch/src/inc/MarlinConfig.h:34:0,
                 from sketch/src/Marlin.h:25,
                 from sketch/src/Marlin.cpp:31:
sketch/src/inc/SanityCheck.h:1529:6: error: #error "X_CS_PIN is required for X_IS_TMC2130. Define X_CS_PIN in Configuration_adv.h."
     #error "X_CS_PIN is required for X_IS_TMC2130. Define X_CS_PIN in Configuration_adv.h."
      ^
```

is it work in progress to alter the assignment of the CS-Pins ?

**Comment by dembach** [comment]
definition file for pins is wrong... altered RAMPS_FD_v1 : 
```
@@ -63,42 +63,42 @@
#define X_STEP_PIN         63
#define X_DIR_PIN          62
#define X_ENABLE_PIN       48
-#ifdef X_CS_PIN
+#ifdef X_IS_TMC2130
  #define X_CS_PIN         68
#endif

#define Y_STEP_PIN         65
#define Y_DIR_PIN          64
#define Y_ENABLE_PIN       46
-#ifdef Y_CS_PIN
+#ifdef Y_IS_TMC2130
  #define Y_CS_PIN         60
#endif

#define Z_STEP_PIN         67
#define Z_DIR_PIN          66
#define Z_ENABLE_PIN       44
-#ifdef Z_CS_PIN
+#ifdef Z_IS_TMC2130
  #define Z_CS_PIN         58
#endif

#define E0_STEP_PIN        36
#define E0_DIR_PIN         28
#define E0_ENABLE_PIN      42
-#ifdef E0_CS_PIN
+#ifdef E0_IS_TMC2130N
  #define E0_CS_PIN        67
#endif

#define E1_STEP_PIN        43
#define E1_DIR_PIN         41
#define E1_ENABLE_PIN      39
-#ifdef E1_CS_PIN
+#ifdef E1_IS_TMC2130
  #define E1_CS_PIN        61
#endif

#define E2_STEP_PIN        32
#define E2_DIR_PIN         47
#define E2_ENABLE_PIN      45
-#ifdef E2_CS_PIN
+#ifdef E2_IS_TMC2130
  #define E2_CS_PIN        59
#endif
```

**Comment by teemuatlut** [comment]
It should be `#ifndef X_CS_PIN`.
Basically a typo then.

**Comment by dembach** [comment]
but there is no X_CS_PIN definition in the configuration files... right ?

**Comment by teemuatlut** [comment]
No not yet.

**Comment by dembach** [comment]
?_IS_TMC2130 is already there.... and we have to define it.... so why not use that ?

**Comment by teemuatlut** [comment]
It was decided that the CS pin definitions will move to `configuration_adv.h` but with `pins_` files providing a board specific default value. It would cause a redefinition error if the `pins_` file would define a CS pin even when it was already defined in `configuration_adv.h`.

**Comment by dembach** [comment]
But still you have got to alter the pins_ file if you need pins that are already in use...
i.e. RAMPS_FD file is using CS Pins that i cannot find on the board ;-) 
so i have to wait again to get things working completely....

**Comment by teemuatlut** [comment]
No, `configuration_adv.h` will have a section for defining the CS pins. However, if you don't do that, Marlin will use the **default** values from the respective `pins_` file.

**Comment by thinkyhead** [comment]
Patched.
