### ISSUE TITLE
Geeetech 3dTouch not retracting always. Help

### ISSUE THREAD

**Issue by Margus113** [MarlinFirmware/Marlin#9808]
Former FLSUN cube. Now upgraded to rail system and 3dtouch.
Tried a lot of setups etc. i dont know anymore, what now.
I will add configuration.h, can some smarter look, what i missing.
Sensor working, can perform all tests, but cant get work.
Sometimes, can do G28 ok, and G29 first few points, but after that,
senosor stay in upper position and nozzle rushing in to bed.

[HELF.txt](https://github.com/MarlinFirmware/Marlin/files/1755965/HELF.txt)

At first, after uploading marlin M43 S working ok. Tsting and ask to trigger probe.
But after starting print, nothing happening, probe just stay in upper pos.

**Comment by psavva** [comment]
Can you run the selftest for 10 or 20 mins without failure?

Is the pin loose when powering your bltouch clone down?

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by Margus113** [comment]
After approx 1min self test, probe stay in upper pos and alarms.

**Comment by thinkyhead** [comment]
Try enabling and increasing `BLTOUCH_DELAY`.
```cpp
#if ENABLED(BLTOUCH)
   //#define BLTOUCH_DELAY 375   // (ms) Enable and increase if needed
#endif
```

**Comment by Margus113** [comment]
After 2 days of having love with that sensor, i finally get it to work.
Exact problem i cant say, but seems that were needed to adjust probe, from hex screw.
After adjusting /some random screwing.../ it not giving alert and working now.
Thanks

**Comment by Bob-the-Kuhn** [comment]
What color is your 3D Touch?  Is it black or white?

Another user is having problems with a black one.  I haven't seen a black one until recently.
