### ISSUE TITLE
RIGHT_PROBE_BED_POSITION can't be reached by the Z probe

### ISSUE THREAD

**Issue by roosevelt155** [MarlinFirmware/Marlin#9822]
I get a compile error when attempting to set my RIGHT_PROBE_BED_POSITION. My probe offsets are X-42 and Y80, but when I set the RIGHT_PROBE_BED_POSITION to 190 (to reach the far side of the bed) I get the error RIGHT_PROBE_BED_POSITION can't be reached by the Z probe. This should work because my X probe offset is a negative but it is acting as if the offset is positive and a negative. 

[Config Files.zip](https://github.com/MarlinFirmware/Marlin/files/1758695/Config.Files.zip)

**Comment by thinkyhead** [comment]
These need to be rectified:
```cpp
#define X_BED_SIZE 180
#define X_MAX_POS 190
```
