### ISSUE TITLE
[Configuration] UBL Problem

### ISSUE THREAD

**Issue by Gigahertz77** [MarlinFirmware/Marlin#9823]
I don't know how to resolve this problem, step 1 ( G29 P1   ) after 58 test point, the probe come out of the bed.  I have try every number.
Bed 220x220

#define X_PROBE_OFFSET_FROM_EXTRUDER 38   // X offset: -left  +right  [of the nozzle]
#define Y_PROBE_OFFSET_FROM_EXTRUDER 5   // Y offset: -front +behind [the nozzle]
#define Z_PROBE_OFFSET_FROM_EXTRUDER -1.05   // Z offset: -below +above  [the nozzle]

  #define UBL_PROBE_PT_1_X 25     // Probing points for 3-Point leveling of the mesh
  #define UBL_PROBE_PT_1_Y 200
  #define UBL_PROBE_PT_2_X 25
  #define UBL_PROBE_PT_2_Y 30
  #define UBL_PROBE_PT_3_X 200
  #define UBL_PROBE_PT_3_Y 30
![20180226_133028 1 _preview](https://user-images.githubusercontent.com/34447792/36672897-48f67b08-1b01-11e8-80b4-1bc7399d4ab6.jpeg)

**Comment by Roxy-3D** [comment]
You probably should shrink the effective bed size with an INSET....     And once everything stays on the bed, you can increase the INSET on the unaffected sides of the bed, one side at a time...

**Comment by Gigahertz77** [comment]
this parameter? #define MESH_INSET 1              // Mesh inset margin on print area

**Comment by Roxy-3D** [comment]
Yes.     But if that works...   In Configuration_adv.h you will be able to set the INSET for each side of the bed.      There is something else wrong with your settings.  But this will help you work around in and figure out the problem.

**Comment by ghost** [comment]
To probe too close to the edge will give issues in the future , a lag with the endstop or anything that make busy the machine , and the positions have 1mm less , it's why , apply a margin of 2mm or more just to ensure all situations of not perfect 'endstoping'

**Comment by gregspruce** [comment]
Can I have that inset, but then tell UBL to apply matrix points outside of the inset area so I can fill it in with G29 P2/P3? I guess the UBL raise/lower to infinity bug is fixed in one of the more recent commits to the bugfix branch but still...

**Comment by ghost** [comment]
No ... Ubl is not windows Xperience with 10 years old and 300 engineers lolll
Ubl is beautifull , but  , when someone doesn't know it , sometimes he wants something impossible.
For example in my situation , i have an outside purge bucket , and ubl can go on this area but no bed , the ubl don't set outside mesh points as the nearest , it's why @Roxy-3D have made a secure z height for off mesh points 
Try to improvise and find solution by creativity lollllllllllllll

Note : Bug of raise up , or raise down  , is solved , i have tested three times on dual extrusion print , that go outside of the bed every layer to change color , on the old bugged releases i used G29 disable to go on pause , and G29a to back , now , i have deleted these instructions
all is fine

**Comment by thinkyhead** [comment]
> Bug of raise up , or raise down , is solved

Do you mean, "is solved" just for you, or "is solved" in the latest code?

**Comment by thinkyhead** [comment]
@Gigahertz77 — The automated settings that determine the probing boundaries normally consider your probe offset, but for some reason this has been removed for UBL. The comment (below) says "UBL is careful not to probe outside the bed." However it still apparently tries to use the areas you can never reach.

I believe the intent was that you would have to set those unreachable points manually after auto probing. However, in this case it looks like the points where your probe cannot reach are not, in fact, being left out.

----
@Roxy-3D — Can you have a look at UBL and see how it handles the probe boundaries? First of all, there is this block from `Conditionals_post.h`…

```cpp
#if ENABLED(AUTO_BED_LEVELING_UBL)
  #define _MESH_MIN_X (max(X_MIN_BED + MESH_INSET, X_MIN_POS))  // UBL is careful not to probe off the bed.  It does not
  #define _MESH_MIN_Y (max(Y_MIN_BED + MESH_INSET, Y_MIN_POS))  // need *_PROBE_OFFSET_FROM_EXTRUDER in the mesh dimensions
  #define _MESH_MAX_X (min(X_MAX_BED - (MESH_INSET), X_MAX_POS))
  #define _MESH_MAX_Y (min(Y_MAX_BED - (MESH_INSET), Y_MAX_POS))
#else
  #define _MESH_MIN_X (max(X_MIN_BED + MESH_INSET, X_MIN_POS + X_PROBE_OFFSET_FROM_EXTRUDER))
  #define _MESH_MIN_Y (max(Y_MIN_BED + MESH_INSET, Y_MIN_POS + Y_PROBE_OFFSET_FROM_EXTRUDER))
  #define _MESH_MAX_X (min(X_MAX_BED - (MESH_INSET), X_MAX_POS + X_PROBE_OFFSET_FROM_EXTRUDER))
  #define _MESH_MAX_Y (min(Y_MAX_BED - (MESH_INSET), Y_MAX_POS + Y_PROBE_OFFSET_FROM_EXTRUDER))
#endif
```

And then in `UBL.h` it is definitely not considering the probe offset when deciding how large the mesh is or how far apart the grid lines are:
```cpp
#define MESH_X_DIST (float(MESH_MAX_X - (MESH_MIN_X)) / float(GRID_MAX_POINTS_X - 1))
#define MESH_Y_DIST (float(MESH_MAX_Y - (MESH_MIN_Y)) / float(GRID_MAX_POINTS_Y - 1))
```

Am I correct in my assumption that your plan was to allow people to specify the whole bed, even if their probe cannot reach it, and then have them do manual probing for the points the probe cannot reach?

A more general problem is, there is only one mesh inset, but the probe offset only applies limits to one or two sides of the bed at the most. So increasing the mesh inset is not the most ideal solution to make sure all points are reachable.

**Comment by thinkyhead** [comment]
A good rule of thumb, by the way, if your nozzle can move outside the bed, is to install your probe on the side of the nozzle where it will still be on the bed when the nozzle is outside.

**Comment by Gigahertz77** [comment]
Not yet, because it's not my language, and I have a little problem to understand the right procedure.

**Comment by thinkyhead** [comment]
Hmm. If I run the instructions through Google Translate perhaps I can make them more comprehensible…. What language are you most fluent in?

**Comment by Roxy-3D** [comment]
> And then in UBL.h it is definitely not considering the probe offset when deciding how large the mesh is or how far apart the grid lines are:

That is true.   With no INSET, and a X or Y_PROBE_OFFSET_FROM_EXTRUDER it is not possible to auto probe the entire bed.   But those points can be acquired and filled in easily with manual probing or with a G29 P3 (which does a smart fill).

**Comment by thinkyhead** [comment]
So it sounds like the comparison that prevents the probe from going outside of the bed is potentially failing in `ubl.G29` / `probe_entire_mesh`. I'll look through the code and see if it's anything obvious.

**Comment by thinkyhead** [comment]
Ah. Well here's the issue. There is no check. It just goes happily on with `probe_pt` whether the point can be reached or not. I suggest that it do the following:
```cpp
const float measured_z = position_is_reachable_by_probe(rawx, rawy)
                         ? probe_pt(rawx, rawy, stow_probe, g29_verbose_level)
                         : NAN;
```

**Comment by thinkyhead** [comment]
Ah. Well here's the issue. There is no check. It just goes happily on with `probe_pt` whether the point can be reached or not. I suggest that it do the following:
```cpp
const float measured_z = position_is_reachable_by_probe(rawx, rawy)
                         ? probe_pt(rawx, rawy, stow_probe, g29_verbose_level)
                         : NAN;
```
Or, if it's better to leave the unreachable points unchanged…
```cpp
if (position_is_reachable_by_probe(rawx, rawy))
  z_values[location.x_index][location.y_index] = probe_pt(rawx, rawy, stow_probe, g29_verbose_level);
```
I guess the first option is better, since it then knows that the requested points need to be manually probed.

**Comment by thinkyhead** [comment]
Possibly this test is now failing?
```cpp
        if (location.x_index >= 0) {    // mesh point found and is reachable by probe
```

**Comment by thinkyhead** [comment]
So the logic of `find_closest_mesh_point_of_type` appears pretty sound. I can't see any reason why it would let an "unreachable" point through. So, maybe something is just amiss about @Gigahertz77's probe offset or probing boundaries.

**Comment by Roxy-3D** [comment]
Yes...  I think the numbers are wrong.   But if he puts a big offset (like 50mm) in...   I bet it stays on the bed.    And then he can start playing with one number at a time until he figures out what is wrong.

**Comment by thinkyhead** [comment]
So theoretically, you could put points off the bed if you wanted to. The probe couldn't reach them, but you could still manually set them. In that case, maybe it makes sense to skip probe points where neither the nozzle nor the probe can reach.

**Comment by Roxy-3D** [comment]
In fact...   That is what happens with Delta's.   Each corner has a bunch of mesh points that are off the bed.

**Comment by thinkyhead** [comment]
Indeed! That's why ABL operates the way it does. It inherits directly from the work by **jcrocholl**.

---
> That is what happens with Delta's.

Delta's … _what?_ Delta's birthday?
Apostrophes are not needed to make a noun plural.
#grammarnazi 😈

**Comment by Roxy-3D** [comment]
Or show possession.   The Delta owns those locations on the bed.

**Comment by gloomyandy** [comment]
A setting I've found really useful is MIN_PROBE_X, MIN_PROBE_Y, MAX_PROBE_X, MAX_PROBE_Y. These settings allow you to override the defaults for the probable area without impacting the mesh size. So in my case I wanted to have a mesh that covers all of the bed (to allow me to print edge to edge), but to only automatically probe the area reachable by the probe (obviously) plus an extra margin because probing close to the edge of my bed gives odd results (the sensing area of the inductive probe is partly off the bed). Using the above settings with the following definitions:
```
// Min/Max probe area. We can only probe inside of the bed and really need to be 10mm away from an edge to get a good reading.
// Boundaries for Cartesian probing based on bed limits
#define MIN_PROBE_X (max(X_MIN_POS+10, X_MIN_POS + X_PROBE_OFFSET_FROM_EXTRUDER))
#define MIN_PROBE_Y (max(Y_MIN_POS+10, Y_MIN_POS + Y_PROBE_OFFSET_FROM_EXTRUDER))
#define MAX_PROBE_X (min(X_MAX_POS - 10, X_MAX_POS + X_PROBE_OFFSET_FROM_EXTRUDER))
#define MAX_PROBE_Y (min(Y_MAX_POS - 10, Y_MAX_POS + Y_PROBE_OFFSET_FROM_EXTRUDER))
```
does this for me and works very well. I get the centre part of the mesh probed automatically with a strip down each side which I either do a manual probe for or use auto-fill on. Note that this is not the same as using the UBL MESH_INSET which would inset the mesh by 10mm (or whatever), I have MESH_INSET set to 0 so the mesh covers my entire reachable area (which in my case is all of the bed).

**Comment by ManuelMcLure** [comment]
Thank you, thank you, thank you! `[MIN|MAX]_PROBE_[X|Y]` is what I've been looking for to allow me to make the jump to UBL, since I have an inductive probe and need to keep the probe away from the edges of the bed. Assuming @Roxy-3D doesn't know any reason why this wouldn't work for my situation (want to use the whole bed but don't want to probe near the edges of the bed), I may give UBL another try this weekend.

**Comment by Roxy-3D** [comment]
I think that should work...

**Comment by boelle** [comment]
@Gigahertz77 problem solved?

**Comment by Gigahertz77** [comment]
No, I quit, I have try 2 days without result.

Il giorno mer 20 feb 2019 alle ore 10:21 Bo Herrmannsen <
notifications@github.com> ha scritto:

**Comment by boelle** [comment]
@Gigahertz77 maybe click the green button below?

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
