### ISSUE TITLE
Z axis won't move after upgrading from 1.0 to 1.1.x

### ISSUE THREAD

**Issue by m-dan-7** [MarlinFirmware/Marlin#9829]
I'm trying to upgrade a TAZ 4 to the bugfix-1.1.x version of marlin, and was able to flash it with the correct configuration file ( [link](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/example_configurations/AlephObjects/TAZ4/Configuration.h) ) for the printer. However the Z axis stopped working; the motors seem to be trying to turn since they vibrate/make an awful humming noise, but nothing moves. I tested the Z stepper motors with the harness from the Y axis and that worked, so I doubt it's the motors ; the X and Y axes are also both working fine, as I homed them before trying to move Z. I also doubt it's the board or a wiring connection, since when I re-flashed back to the previous Marlin version I had on it the axes all worked without issues. Is this an issue that anyone has experienced previously in upgrading to 1.1, and is there anything besides the configuration.h and configuration_adv.h that I needed to change in the new firmware specific to the printer?

**Comment by thinkyhead** [comment]
Reduce your X, Y, and Z jerk by 50% and if needed also lower your Z acceleration.

**Comment by m-dan-7** [comment]
So I changed the jerk from 8, 8, 0.4 to 4, 4, 0.2 ; the Z axis still didn't budge, but the noise from the motors wasn't nearly as bad. Is there a setting to individually change the Z acceleration besides default_max_acceleration? The travel acceleration value for X, Y, and Z is much higher than the default for Z, I'm assuming the travel acceleration overrides the default?

**Comment by thinkyhead** [comment]
You can use these commands to tune it:
```
 * M201 - Set max acceleration in units/s^2 for print moves: "M201 X<accel> Y<accel> Z<accel> E<accel>"
 * M203 - Set maximum feedrate: "M203 X<fr> Y<fr> Z<fr> E<fr>" in units/sec.
 * M204 - Set default acceleration in units/sec^2: P<printing> R<extruder_only> T<travel>
 * M205 - Set advanced settings. Current units apply:
            S<print> T<travel> minimum speeds
            B<minimum segment time>
            X<max X jerk>, Y<max Y jerk>, Z<max Z jerk>, E<max E jerk>
```
And see the more detailed documentation at http://marlinfw.org/meta/gcode/

**Comment by psavva** [comment]
What drivers are u using?

**Comment by m-dan-7** [comment]
After trying most possible combinations of jerk, accel, steps/mm, and minimum stepper pulse possible, I noticed that '#define DIGIPOT_MOTOR_CURRENT' was commented out in configuration_adv. Uncommented it, set the values to { 175, 175, 240,135,135 } (what they were in the old Marlin configuration for Taz 4), seems to have worked.

**Comment by thinkyhead** [comment]
@m-dan-7 — Sounds like we need to fix that in the Taz 4 configuration. Is that standard?

**Comment by m-dan-7** [comment]
I'd assume so, the printer I was upgrading didn't have any hardware modifications that I know of. I re-checked the [configuration_adv file](https://devel.lulzbot.com/TAZ/Guava/software/current/Marlin/Marlin/Configuration_adv.h) from Lulzbot and the z-motor current value in that vector should actually be 220, not 240. I had to change the Z-axis steps per unit from 400 to 1600 for the z-axis to move the correct amount,  but 400 was also the value in the old Taz configuration.h file. Also, I believe that the baudrate should be 115200.

**Comment by thinkyhead** [comment]
@marcio-ao — Can you confirm (or refute) the settings that @m-dan-7 has described concerning the [Taz 4 configuration](https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x/Marlin/example_configurations/AlephObjects/TAZ4) we include in our distribution? It doesn't seem like the Z axis would really use 1600 steps-per-mm out of the box.

**Comment by marcio-ao** [comment]
@thinkyhead: This was way before my time, so I don't know the back history on the TAZ 4 config file in Marlin, but our current FW does indeed use 1600 steps-per-mm for Z.

**Comment by marcio-ao** [comment]
We no longer officially compile FW for the TAZ 4, but anecdotally, TAZ 5 FW seems to work. The Marlin config parameters used for that FW are captured here:

http://devel.lulzbot.com/software/Marlin/1.1.8.10/Marlin_TAZ5_SingleExtruder_1.1.8.10_daaacf751.config

The config files do not capture all the modifications we make to Marlin, however, so I can't guarantee that simply compiling Marlin with the correct config files will yield a working FW file, but it might get you close for a TAZ 4 or 5.

**Comment by marcio-ao** [comment]
@m-dan-7: You could also throw the official TAZ 5 FW on your printer:

http://devel.lulzbot.com/software/Marlin/1.1.5.75/Marlin_TAZ5_SingleExtruder_1.1.5.75_046c594ee.hex

Or:

http://devel.lulzbot.com/software/Marlin/1.1.8.10/Marlin_TAZ5_SingleExtruder_1.1.8.10_daaacf751.hex

Although we no longer support TAZ 4s, it *should* work, as the printers are very similar.

**Comment by thinkyhead** [comment]
Thanks for the info! I'll use these as references to update to our example config.

Now, gotta run… Running a print with 625nm layer heights and I'm sure it's going to take a while.

**Comment by marcio-ao** [comment]
@thinkhead: 625nm that is 0.000625 mm ... how is that even possible? We did experiment with a 0.15mm nozzle once -- it was nice for really tiny prints.

**Comment by thinkyhead** [comment]
@marcio-ao Printing with 1600 steps/mm and 1 micro-step per layer didn't work too well. Ooze alone steals all the material. It was funny to try though.

**Comment by marcio-ao** [comment]
@thinkyhead: The decision to move to 1600 steps/mm predates most everyone still at the company. In our marketing, we only claim layer heights of 50 microns, yet at some point a change was made from 400 to 1600 steps/mm on Z.

One possible explanation is that the 1600 steps/mm comes from the fact our motors have 200 steps/revolution, we use 16 microstepping and the pitch of the lead screw is 2 mm:

```
200 steps         16 microsteps      1 rev     
----------     * ---------------- * -------  =  1600 microsteps per mm
  1 rev            1 step             2 mm
```

The other explanation is that we wanted users to be able to vary their layer heights by .01 mm, while still having the steps be an integer number. I was told that if this is not the case, then there are Z banding due to rounding making the layers unequal. This would mean that at 16 microstepping, the microsteps per mm value could be no less than 1600.

I'm not sure which one of these explanations are ultimately the correct ones, but these is the best I could come up with by talking to a few folks around here.

-- Marcio

**Comment by thinkyhead** [comment]
I could've gone even lower in my tongue-in-cheek exercise — to 0.25µm — using a different machine. (The lead/pitch on my i3's Z axis threaded rod is a mere 0.8mm.) But who has the patience to print 4000 layers just to get 1mm height? Not me! Of course, we like the extra micro-stepping for the quieter movement, not necessarily for the ridiculously-fine resolution it makes possible.

**Comment by marcio-ao** [comment]
@thinkyhead: Maybe someone can use Marlin to make an open-source scanning tunneling microscope to push atoms around. This is after all a necessary step for a true Star Trek like replicator.
