### ISSUE TITLE
Does such thing as a Feature Proposal exist ?

### ISSUE THREAD

**Issue by TheSFReader** [MarlinFirmware/Marlin#9855]
This is not a bug, nor a feature request, but wanted to ask the correct process for checking interest before proposing (and taking time to implement / clean/ pull request) a feature ?

**Comment by AnHardt** [comment]
Make a feature request like:
```
Marlin needs to have feature X because of Y.
A way to implement could be Z.
I could make a PR.
```
And wait for response.
