### ISSUE TITLE
M303 auto PID on Bed give immediate error.

### ISSUE THREAD

**Issue by creatron** [MarlinFirmware/Marlin#9858]
### Bug Report
I added a silicon bed heater and wanted to enable PID as the new system had some overshoot.
Enable PID for bed in configure.h, compile and downlaod

- Description: --- The E303 works on the extruder but if the bed PID is enabled you immediately get an error and abort the auto pid. 
- Expected behaviour: ---
Must start with the auto bed leveling, must heat up bed and this takes some time
- Actual behaviour: ---
It immediately abort with a error message
- Steps to reproduce:
   Run M303 E-1 C3 S120 from console in octoprint

I solved the problem, the variables is too small to hold the content in temperature.cpp line 243. (Version 1.1.8)
I changed the two variable to 16 bit values and the auto PID seem to function for both extruder and bed.

      //const int8_t **watch_temp_period** = Gerrie de Jager
      **const int16_t watch_temp_period** =
        #if ENABLED(THERMAL_PROTECTION_BED) && ENABLED(PIDTEMPBED) && ENABLED(THERMAL_PROTECTION_HOTENDS) && ENABLED(PIDTEMP)
          hotend < 0 ? WATCH_BED_TEMP_PERIOD : WATCH_TEMP_PERIOD
        #elif ENABLED(THERMAL_PROTECTION_BED) && ENABLED(PIDTEMPBED)
          WATCH_BED_TEMP_PERIOD
        #else
          WATCH_TEMP_PERIOD
        #endif
      ;
      //const **int8_t watch_temp_increase** = Gerrie changed this
      **const int16_t watch_temp_increase** = dito 
(Could not upload the file)

**Comment by FreeLuck** [comment]
Try the `bugfix-1.1.x` branch. This has already been fixed.
