### ISSUE TITLE
Flsun i3 clone ignoring Z end stop

### ISSUE THREAD

**Issue by Classictinker** [MarlinFirmware/Marlin#9861]
Hi.

I'm new to 3D printing and I'm trying to set up my Flsun i3 plus. I'm still trying to get the configuration sorted out but I'm having trouble with the Z end stop. The printer came with an induction Z probe but I just couldn't get it come to life even when placed directly onto the print bed of a metal plate is  still seemed lifeless **so I've resorted to a micro-switch** as used for the x and y end stops. In repetier-host I can see that all 3 end stop switches are triggering at the correct time but the Z axis end stop is just ignored and the nozzle keeps on going down. The steppers stop correctly in the x and y planes it's just the z plane that seems to be ignored even though M119 shows it has been triggered.

Can anybody point me in the right direction?

**Comment by thinkyhead** [comment]
Please post your `Configuration.h` and `Configuration_adv.h` files (as already requested in the issue template). You can ZIP them up and drop them on your reply.

**Comment by AnHardt** [comment]
It begins with thinking and talking about the right things. Endstop != Probe.

**Comment by Classictinker** [comment]
Sorry, I didn't use the template as I thought that was for actual bug reports whereas my issue is most certainly user error rather than a bug :( I've attached a zip [TMP.zip](https://github.com/MarlinFirmware/Marlin/files/1770575/TMP.zip)  of configuration.h and configuration_adv.h. I hadn't looked in configuration_adv.h before as I thought anything with adv in its' name was probably better left alone by a noob but I had a quick look before zipping them and noticed the line;

//#define ENDSTOPS_ALWAYS_ON_DEFAULT

I wonder if this is contributing to my issue and should be uncommented? I've left both files as they were so we don't end up shooting at moving goal posts.

The kit I bought is based on a vanilla clone Reprap/Prusa I3 200 * 200 * 300 with optional extras added to the base kit components. This comprised of the addition of cyclops and chimera extruders, additional filament (extruder?) stepper motor, a z sensor and size increase to 300 * 300 * 420. As for the supplied software and instructions, there are a few pieces of paper with German text and an SD card with Chinesenglish build instructions for the base kit with separate files for the various addons mostly just photos with no explanation. There is also a file containing a "user manual", all the files seem to be a mishmash of the base kit with the odd reference to other files for the upgrade options. As for the conf files I have no idea what printer setup they are aimed at so any help sorting them out would certainly move the project along nicely.

My strategy so far has been to ignore all the upgrades I bought and just build the standard 300 * 300 * 420 single nozzle extruder printer and sort the upgrades out later once my knowledge and experience has improved. I did fit the Z sensor at first as the conf files seemed to be set up for it but as I said above it just wouldn't do anything so I removed it and fitted the basic micro switch and did my best to sort out configuration.h

Many thanks,

Rich

**Comment by Classictinker** [comment]
A quick update, I've just noticed that the supplied configuration.h files had the motherboard set as a Ramps board when in fact it's a Makerbase MKS Gen_L V1.0 also they sent me Marlin V1.1.2 so I've downloaded the latest version and am slowly going through the configuration.h and configuration_adv.h files.

**Comment by Classictinker** [comment]
Success I now have 3 working end stops :) Hopefully getting the inductive sensor working will just be a case of Googling and hunting around the various forums for info but at least I can now finish off the printers set-up and try a little test print.

Many thanks for your help so far :)

Rich

**Comment by psavva** [comment]
@Classictinker, I suggest to close this issue, and open a me one if/when needed for the probe if you don't manage to get it working.

**Comment by Classictinker** [comment]
Done :)

**Comment by dasmith152** [comment]
Can you share them files? Mine is doing the same thing. Please help..

**Comment by bmwertman** [comment]
I also just got an FLSUN i3 w/ Makerbase Gen. L v1.0 running MArlin 1.1.2 and am having the same issue with Z limit. Can you share your configuration file?

**Comment by dasmith152** [comment]
I will when I get home.
