### ISSUE TITLE
[FR] use esp8266 as coprocessor for mega2560?

### ISSUE THREAD

**Issue by lbhk** [MarlinFirmware/Marlin#9867]
Hi everyone,

    or use to store the bed level data or something else to help the mcu? is possible?

Thanks

**Comment by yellobello** [comment]
Sure, it would be possible but it is not implemented and the question is, is it really necessary?
A better thought is that 2.0 could be ported to the esp32 using the whole, cheap mcu as a controller.
I think someone at least started looking into this possibility.. I am not sure about the state though...

edit:  here, look for yourself: https://github.com/simon-jouet/Marlin

**Comment by boelle** [comment]
@lbhk is this still relavant?

**Comment by boelle** [comment]
missing label

**Comment by AnHardt** [comment]
This ideas are very general.
If say they are done.
