### ISSUE TITLE
[QUESTION] SOFTWARE_ENDSTOPS

### ISSUE THREAD

**Issue by toenish** [MarlinFirmware/Marlin#9875]
Hi,

I have set that my printer dimensions are the following (I have the version from [here](https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x)):
```
// The size of the print bed
#define X_BED_SIZE 200
#define Y_BED_SIZE 215

// Travel limits (mm) after homing, corresponding to endstop positions.
#define X_MIN_POS -42
#define Y_MIN_POS -25
#define Z_MIN_POS 0
#define X_MAX_POS X_BED_SIZE
#define Y_MAX_POS Y_BED_SIZE
#define Z_MAX_POS 200
```

Now, when I upload it to the printer and ask M211 I get the following:
```
echo:Soft endstops: On   Min: X-42.00 Y0.00 Z0.00  Max: X200.00 Y214.00 Z200.00
```

X and Z are OK, but Y is very strange. What could be the reason for such interesting behavior? Where could I change manually the soft end-stop values?

**Comment by thinkyhead** [comment]
Do you get the same results after `M502`?

**Comment by toenish** [comment]
Yes, the same results.

**Comment by thinkyhead** [comment]
What version of Marlin are you using?

`Conditionals_post.h` does this:
```cpp
// Get the linear boundaries of the bed
#define X_MIN_BED (X_CENTER - (X_BED_SIZE) / 2)
#define X_MAX_BED (X_CENTER + (X_BED_SIZE) / 2)
#define Y_MIN_BED (Y_CENTER - (Y_BED_SIZE) / 2)
#define Y_MAX_BED (Y_CENTER + (Y_BED_SIZE) / 2)
```
This is where the software endstops get their default values.

**Comment by toenish** [comment]
I'm using the version I downloaded from Github ([here ](https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x)) on Wednesday. I assume it's the latest version.

**Comment by thinkyhead** [comment]
You may get more help at the [Marlin Help Forum](http://forums.reprap.org/list.php?415) and the [Marlin Facebook Group](https://www.facebook.com/groups/1049718498464482/). We're bogged down in preparing the next release.

**Comment by boelle** [comment]
@toenish 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by boelle** [comment]
@toenish i see you use 1.1.x, try with 2.0.x instead as 1.1.x is not updated anymore

**Comment by boelle** [comment]
as this is a question or support Q rather than a bug i will close this one, should it be a bug we can always reopen

https://github.com/MarlinFirmware/Marlin/issues/14694
