### ISSUE TITLE
TEMP_STAT_LEDS cannot be enabled

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#9886]
Is it the intent that unless VIKI2 || miniVIKI displays are enabled the TEMP_STAT_LEDS cannot be enabled?

If not, then there appears to be a problem, because the only place the STAT_LED_RED_PIN and STAT_LED_BLUE_PIN for RAMPS are defined is in an #elif statement for those displays. I have the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER and I want to use that functionality to drive a discrete red LED connected to an unused port.

How do I do it?

**Comment by thinkyhead** [comment]
Just add the pins you want to use to your configuration file:
```cpp
#define TEMP_STAT_LEDS
#define STAT_LED_RED_PIN  32
#define STAT_LED_BLUE_PIN 35
```
