### ISSUE TITLE
Marlin wont unzip properly 

### ISSUE THREAD

**Issue by beemergb** [MarlinFirmware/Marlin#9894]
I am trying to download and upload Marlin 1.1.8 ,it seems ok but when I unzip it the Marlin Icon does not appear, just a Attribution card sighn ! What am I doing wrong ? Hope you can help, thank you.

**Comment by ikarisan** [comment]
I cannot confirm that. Are you using Windows, Linux or MacOS?
If your system does not show an Arduino icon for .ino files this file type is not registered within your system!

For windows:

1) Download Arduino IDE 
1a) Windows: https://www.arduino.cc/download.php?f=/arduino-nightly-windows.zip 
1b) MacOS: https://www.arduino.cc/download.php?f=/arduino-nightly-macosx.zip
1c) Linux: https://www.arduino.cc/download.php?f=/arduino-nightly-linux64.tar.xz

2) Unpack the archive and copy the content to a location within your user directory
3) Start the Arduino IDE once (to make sure it is known by the system)
4) Windows: Right click on the .ino file, select "open with" and then "Arduino IDE"
5) The icon should have been changed to the Arduino IDEs one.

**Comment by thinkyhead** [comment]
Downloads from here seem ok: https://github.com/MarlinFirmware/Marlin/releases

**Comment by boelle** [comment]
@beemergb problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
