### ISSUE TITLE
Z-Probing fails after turning on ATX PSU

### ISSUE THREAD

**Issue by uuzi** [MarlinFirmware/Marlin#9895]
------------------------------------------------------------
### Bug Report
- Description: After issuing M80 to turn on my ATX PSU, the first homing (and only the first, second try is perfectly fine) works ok for X and Y but for Z it just moves along the X axis to the middle and stays at the Y-min position. 
- Expected behaviour: Hotend should move to middle of bed for Z-probing

Just to emphasize, this ONLY happens on the first homing after I turn on the PSU. Every homing try after that works just as expected, until I turn off the PSU again. After that the first try will fail again.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/1776123/config.zip)

**Comment by AnHardt** [comment]
Does it make a difference if you switch the power supply or if you just reset the processor?

**Comment by golobodo** [comment]
Here was my workaround. Put it in your start gcode before homing:
G0 Y1 ; TMC2130 Y-axis workaround

**Comment by uuzi** [comment]
> Here was my workaround. Put it in your start gcode before homing:
G0 Y1 ; TMC2130 Y-axis workaround <

strangely enough, that works. so there is a bug in the tmc2130 implementation?

**Comment by golobodo** [comment]
It is already fixed in the bugfix1.1.x branch.

**Comment by thinkyhead** [comment]
Please test with the latest `bugfix-1.1.x` (and/or `bugfix-2.0.x`) branch to see where it stands. If the problem has been resolved then we can close this issue. If you still see the bad behavior we should investigate further.

**Comment by uuzi** [comment]
confirmed working correctly in `bugfix-1.1.x`
