### ISSUE TITLE
LCD corruption with Marlin-bugfix-1.1 Anycubic Kossel

### ISSUE THREAD

**Issue by rszasz** [MarlinFirmware/Marlin#9902]
I've had a few instances of LCD corruption while changing speed during a print, and just now had it corrupt about 22 hours into a print.

Going to the menu screen and back to the info screen cleans most of it up but leaves some corruption. 

Is there a known fix for this, or is there an option for forcing a full refresh of the screen every few minutes?

[configfiles.zip](https://github.com/MarlinFirmware/Marlin/files/1776888/configfiles.zip)

**Comment by gloomyandy** [comment]
Might be worth providing details (picture if you can) of what exactly the corruption looks like.

**Comment by rszasz** [comment]
Will do if I can get it to happen again, but it looks like random garbage was written to the LCD. And switching to the menu and back clears up all but one or two characters of it.

**Comment by hapklaar** [comment]
Same issue here. I suspect static electricity might play a role as it often happens when I touch the printer.

**Comment by thinkyhead** [comment]
With character LCDs it's almost always poor contact between plug and pins — sometimes static. Try bending the LCD connector pins in a little to make a tighter fit, both on the LCD and on the board.

**Comment by boelle** [comment]
@rszasz problem solved?

**Comment by boelle** [comment]
@thinkyhead i think we can close this one

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.
