### ISSUE TITLE
[bugfix-1.1.x] Misuse of kill() in emergency_parser()

### ISSUE THREAD

**Issue by ABH10** [MarlinFirmware/Marlin#9906]
When the emergency_parser() catches an M112 command it calls the kill() function.
The kill() function is supposed to send status messages to the host (MSG_ERR_KILLED and ACTION_ON_KILL), but as the emergency_parser() and the kill() function are invoked from inside an ISR, these status messages never reaches the host. The kill() function was not designed to be called from inside an ISR.
Instead of actually calling kill() inside the emergency_parser(), I propose to flag the detection of M112 and then postpone the call of kill() to the idle() "task". This is how I have solved it locally, as my host relies on receiving the MSG_ERR_KILLED message.

**Comment by Roxy-3D** [comment]
I wonder if it would be better (and make the code cleaner) if we made kill() callable at interrupt time?   Setting flags and hoping to see them later just makes the code paths more difficult to follow.   And there are very real issues why the emergency parser needs to be at interrupt time.   

What if we always had a non-interrupt driven serial transmit routine available...   And kill() used that to send the MSG_ERR_KILLED message?    It would end up being a few extra bytes of code space used...   But the code would be cleaner.

**Comment by AnHardt** [comment]
All it needs is a sei(); at the beginning of the kill() function - i guess.

**Comment by thinkyhead** [comment]
Well, the main purpose of catching `M112` in the emergency parser is so we don't have to wait for it to come up in the queue before it gets executed.

So all we need to do is to add a `bool killed_by_M112` flag and set that in response to `M112`. Then the `idle()` (or `manage_heater`) function can call `kill()` in response to that flag.

**Comment by Roxy-3D** [comment]
> Well, the main purpose of catching M112 in the emergency parser is so we don't have to wait for it to come up in the queue before it gets executed.

If I remember right...  There was also an issue where the serial buffer space could be full.   So, catching it in the ISR made sure the firmware would see it before it got lost.

**Comment by thinkyhead** [comment]
Ah yes, I remember that being a consideration, and it applies to the other emergency commands too.
