### ISSUE TITLE
[2.0.x] STM32F! Maylan 200 / MPSM question

### ISSUE THREAD

**Issue by yellobello** [MarlinFirmware/Marlin#9908]
Hi,

I saw that there is a port for the Maylan M200 printer and I am just curious since there appears to also be some driver for the LCD screen.
OK, the LCD screen of this printer has its own STM32 dedicated processor, much like the DUET-LCD or the MKS LCD, so I wonder if the supported screen on the M200 displays marlin´s internal LCD menu or adapts to the M200´s LCD menu.

best regards,

**Comment by xC0000005** [comment]
The malyan LCD driver doesn't run on the LCD, which is an ESP8266. There is some code that runs on the actual display, but this isn't that. The LCD driver simply interprets between the LCD's curly brace language and relatively standard gcode (there's some special support for how file listing and print commands are handled.)

**Comment by thinkyhead** [comment]
Is this different from the one we currently support?
```cpp
//
// LCD for Malyan M200 printers.
// This requires SDSUPPORT to be enabled
//
//#define MALYAN_LCD
```

**Comment by xC0000005** [comment]
Ok, re-reading the original question:
Marlin's LCD support adapts to the Malyan LCD menu's language - it does not display Marlin's LCD menu on the Malyan display controller.

**Comment by boelle** [comment]
@yellobello 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by boelle** [comment]
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
