### ISSUE TITLE
[Bugfix_2.0.x] Custom Bootscreen Inop Radds LCD

### ISSUE THREAD

**Issue by bwgeez02** [MarlinFirmware/Marlin#9918]
Custom bootcreen doesn't show anything on the Radds LCD. Marlin bootscreen works. Not a big deal, but I've been trying to get it to work for hours over the last few days.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1777876/Configuration.zip)
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/1777877/Configuration_adv.zip)
[_Bootscreen.zip](https://github.com/MarlinFirmware/Marlin/files/1777879/_Bootscreen.zip)

**Comment by AnHardt** [comment]
As far i can remember the 'official' RADDS-display is a text display.
So no chance to display a custom boot screen, only defined for graphical displays.

**Comment by bwgeez02** [comment]
So it will display the Marlin bootscreen, but won't display the binary bootscreen from Marlins bitmap converter? Correct me if I'm wrong but isn't the Marlin logo, that it is displaying, from dogm_bitmap.h which is binary?

**Comment by AnHardt** [comment]
What you see on the RADDS-display is
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/ultralcd_impl_HD44780.h#L521-L526
with
https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/ultralcd_impl_HD44780.h#L231-L269
And i'm proud about the similarity.

**Comment by bwgeez02** [comment]
Gotcha. Just changed Marlin to my name and uploaded it to be sure. Thank you. I've spent hours researching this. Would've been nice to have an explanation in Configuration.h that a graphical display is needed for custom bootscreen, for those that don't know better.

**Comment by AnHardt** [comment]
Please onore Marlin and don't change the bootscreen. And if you do so, don't tell us about it. It makes us sade.
Please don't force us to write a custom boot screen for text displays.

**Comment by bwgeez02** [comment]
I only did it for testing purposes. And no I'm not interested in a custom bootscreen option for text displays. I'd rather upgrade my display.

**Comment by thinkyhead** [comment]
I'll be sure to add a sanity-check that throws an error if `CUSTOM_BOOTSCREEN` is enabled when no graphical display is enabled.

**Comment by bwgeez02** [comment]
Thank you! Is there any reason the PanelDue isn't supported in 2.0.x? I've been thinking about upgrading to one for awhile, but I like Marlin and the only firmware I find for it is Repetier and RepRap.

**Comment by AnHardt** [comment]
Currently 'PanelDue' is not supported by Marlin.

Color displays are not supported.
Graphical displays other than 128x64 are not supported.
Touch controllers are not supported.

So, a bit larger task.

**Comment by thinkyhead** [comment]
> Is there any reason the PanelDue isn't supported in 2.0.x?

Because no one has yet contributed code to support it.

**Comment by bwgeez02** [comment]
I would if I could. The best I can do is testing the code. This morning I emailed Duet3d to apply to register with them. I'll see if I can get somebody to help.
