### ISSUE TITLE
trying to compile with tmc2130 support throws up an error

### ISSUE THREAD

**Issue by wbarber69** [MarlinFirmware/Marlin#9928]
Using the 1.1.x bugfix branch as of 3/4/18.  I cannot finish compiling my build.  I have enabled the trinamic 2130 drivers and all the specific pins references and everything else.  I have them fuctioning somewhat in regular Marlin1.1.8 and copied my settings over.  I am getting this error:
```
exit status 1
expected initializer before '.' token

in reference to this line of Marlin_main.cpp:

stepperZ.setCurrent(_rms, R_SENSE, HOLD_MULTIPLIER);
```
I have already signed up for the reprap forums but i am [ending admin approval and would like some help please.
[files.zip](https://github.com/MarlinFirmware/Marlin/files/1778261/files.zip)

**Comment by teemuatlut** [comment]
Thanks for the bug report.
#9930
