### ISSUE TITLE
Z high is short by 10%-ish

### ISSUE THREAD

**Issue by Classictinker** [MarlinFirmware/Marlin#9936]
Before I forget my conf files are here [Marlin-Conf.zip](https://github.com/MarlinFirmware/Marlin/files/1778824/Marlin-Conf.zip)
So Hello again :)

I finally have the printer printing rather than blocking the extruder throat so I'm make some head way. My 1st few attempts were terrible due to over extrusion but lowering the extrusion multiplier to 0.9 seems to have sorted that issue out.

My problem now is that my test prints are about 10-15% short...well the 10mm cube I printed out certainly is.

I'm printing in 1.75mm PLA, bed temp 55, extruder 210,  0.35mm 1st layer all others are 0.25 with rectilinear infill at 20% density.

When printing I can see the nozzle digging in to the previous layer as it does the infill. I measured the bed high then raised it 100mm using the touch screen, remeasured and it had raised exactly 100mm so I think my z calibration is correct in configuration.h although it's much smaller than the values I see in examples????

I don't want to start blindly adjusting things as I'll probably make things worse. Could somebody suggest a sensible approach to figuring out the problem? It doesn't help that I can't find any specs on my z Stepper motors other than the number 42SHDC4047Z-23B. Other than that all I know is that the Z lead screws are 8mm and to raise the bed 10mm takes approximately 1.25 turns of the lead screws. Are there any gcode commands I can use to determine the specs of the Z stepper motors?

I've attached a couple of pics of the 10mm cube below.

Many thanks

Rich
EDIT: I#ve had a look at Repetier host's calculator and it looks like my Z set-up is;
leadscrew TR8 X 2.0, Microstepping 1/4, step angle 1.8 degrees.

![20180304_135219](https://user-images.githubusercontent.com/33553873/36949330-9d0602f4-1fde-11e8-8978-8d3b744f8a5b.jpg)
![20180304_135237](https://user-images.githubusercontent.com/33553873/36949331-9d21809c-1fde-11e8-857d-46fab8e0318b.jpg)

**Comment by thinkyhead** [comment]
We are asking users to please in the future, ask for help in the [Marlin Forum](http://forums.reprap.org/list.php?415) and the [Marlin Facebook Group](https://www.facebook.com/groups/1049718498464482/) before interrupting the developers to ask these kinds of questions.

To figure out your discrepancy:
- Put a flag on your Z screw.
- Measure the height of the carriage with a caliper or ruler, and use `M114` to see the current Z.
- Move Z up with your host until it has done 10 full 360 rotations.
- Measure the height and subtract the starting height.
- Compare the measured movement to the movement reported by `M114`.

Correct your Z steps with `M92 Znnn`:
- CURRENT_Z_STEPS_PER_MM * (DESIRED_MM / ACTUAL_MM)

**Comment by boelle** [comment]
@Classictinker 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a bug report.

**Comment by boelle** [comment]
@thinkyhead i think we can close this one
