### ISSUE TITLE
How to run a big cool down fan

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#9951]
I am running out of usable output pins. The PS_ON pin might work for this, as I don't use it for a PSU, but how? I have a big fan that will cool down my 600W hotbed AL plate when the print is done.
I could connect it to pin 4 (5 & 6 are used for Temp LEDs) and make an end script to turn it on, but then I must manually turn it off or run a D4 delay.
As best as my little brain can figure, it looks like the AUTO_POWER_E_FANS function might work as this is tied to temp. (My E fan is always on). I think what I need to do is to add a condition to this IF statement in power.cpp (approx line 45) to test that the print is finished.

   #if ENABLED(AUTO_POWER_E_FANS)
    HOTEND_LOOP() if (thermalManager.autofan_speed[e] > 0) return true;
  #endif

Any suggestions?

With the arrival of these high wattage heaters and PET film there is more need to configure a rapid cool down. Otherwise, one is just replacing a very slow heat up to start a print with a much slower cool down to get to the print. Maybe this is a good function to have in the firmware.

**Comment by thinkyhead** [comment]
Suggest that you seek this kind of help in the [Marlin Forum](http://forums.reprap.org/list.php?415) or the [Marlin Facebook Group](https://www.facebook.com/groups/1049718498464482/).
