### ISSUE TITLE
[bugfix_2.0.x][TMC2130] temperature prewarn gets triggered for E (which E?)

### ISSUE THREAD

**Issue by dembach** [MarlinFirmware/Marlin#9966]
Description: The temperature prewarn flag is set . Message "00:00: E driver overtemperature warning!" is displayed . But which E ? (ok got only one but it should be E0 in the message)
Expected behaviour: Prewarn flag is set  and should report the correct E0/E1/E2....
Actual behaviour: Prewarn flag is set only E is reported, but M911 - Report stepper driver overtemperature pre-warn condition is correct with E0.

Steps to reproduce:

    Install the TMC2130 stepper driver and enable TMC2130 in Configuration_adv.h
    exchange MOSI and MISO for Extruder
    now you have got prewarn triggered due to non-working communication to TMC2130 and register are reported with the prewarn condition.

**Comment by thinkyhead** [comment]
Thanks for the report. This is now patched.
