### ISSUE TITLE
M420 data explanation please

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/Marlin#9967]
what does this data tell me from M420 V command?
probe order was  right back, right front, left center
home is left front
X is left-right
y is front-rear
Bed Level Correction Matrix:+1.000000 +0.000000 +0.000587
+0.000000 +1.000000 -0.000377
-0.000587 +0.000377 +1.000000

**Comment by AnHardt** [comment]
https://en.wikipedia.org/wiki/Rotation_matrix

**Comment by ruggb** [comment]
I have already looked at that. It is a little heavy for my brain. Can you tel me in 1st yr college terms. My latest one is
+1.000000 +0.000000 -0.000002
+0.000000 +1.000000 +0.000004
+0.000002 -0.000004 +1.000000

is this better or worse for a 3 point level

**Comment by AnHardt** [comment]
Position vectors are multiplied with this matrix to get the corrected positions.
A ideally level bed has the matrix
```
1 0 0
0 1 0
0 0 1
```
Larger differences to this mean larger tilt. -> Your bed is verry level.
