### ISSUE TITLE
Marlin Turn off heaters when Z homing and bed leveling

### ISSUE THREAD

**Issue by noel841106** [MarlinFirmware/Marlin#9982]
I've got anet A6 and marlin 1.1.x.
I install proximity sensor, and connect it to Zmin endstop.
When printer start moving down in Z axis searching bed in G28 command or G29, heaters is off.
On lcd numbers with temperature is start to blink in this situation, so it's like a pause in heating or some others software issue/feature.
How to fix that?
Regards.

**Comment by dtandersen** [comment]
`//#PROBING_HEATERS_OFF`

**Comment by noel841106** [comment]
So easy... I spend many hours fo searching this.
Thank you.

**Comment by thinkyhead** [comment]
Note that `PROBING_HEATERS_OFF` is needed if your probe readings get worse as a result of noisy PWM which can interfere with some probes..
